### ISSUE TITLE
Get Brave added to atom/electron.atom.io application list w/ a new pull request

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1000]
Posting here in case a contributor can make the pull request.

http://electron.atom.io/#get-started lists a bunch of electron apps.  We should list Brave there with a link back to brave.com.   Images for this can be found in `app/img` of this repo.

Pull request can be made here:
https://github.com/atom/electron.atom.io

**Comment by viswanathamsantosh** [comment]
Started contributing to brave with this first good first bug! \o/

**Comment by bbondy** [comment]
Thanks @viswanathamsantosh !

**Comment by viswanathamsantosh** [comment]
perhaps we can close this issue now! :)
