### ISSUE TITLE
"recently closed tabs" should be global, not per window

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#10002]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
closedFrames is stored in perWindowState and should be stored once in global state

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/ff263c05b8b03ccf649b8f90f40b4ac4e484a17b

**Comment by bsclifton** [comment]
Related: the menu code makes an attempt at this (for use w/ the History menu)
https://github.com/brave/browser-laptop/blob/9b64f5854ecb78dce2c0bfda598b66687b911777/app/browser/menu.js#L681
