### ISSUE TITLE
about favicons are taking up way too much space in the session store

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#10000]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A fresh profile that opens about:preferences, about:history and about:bookmarks is ~180K

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Fresh profile
    2. Open about:preferences, about:history and about:bookmarks
    3. Close Brave
    
- Actual result:
session store is huge

- Expected result:
session store should not be huge

**Comment by NejcZdovc** [comment]
congrats on 10000 issue :tada: :tada:
