### ISSUE TITLE
Getting an error "navigator.getBattery" when embed youtube video

### ISSUE THREAD

**Issue by alokpant** [brave/browser-laptop#10003]
When youtube videos are embed in the page, it gives error:

```
Uncaught (in promise) Error: navigator.getBattery not supported.
    at Promise (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/content/scripts/navigator.js:12)
    at Promise (<anonymous>)
    at Navigator.getBattery (chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/content/scripts/navigator.js:12)
```

Multiple videos give same multiple errors:
<img width="1131" alt="screen shot 2017-07-16 at 12 52 44" src="https://user-images.githubusercontent.com/6135761/28246909-c38f55e8-6a25-11e7-9b33-9cead6fdd19a.png">

Even after putting shield down it gives same error:
<img width="1129" alt="screen shot 2017-07-16 at 12 54 20" src="https://user-images.githubusercontent.com/6135761/28246913-fde8ae10-6a25-11e7-9965-0df65c677e1f.png">

Not able to reproduce on:
Chrome 'Version 59.0.3071.115 (Official Build) (64-bit)'
Firefox 52.0.2 (64-bit)
Safari Version 10.1.1 (12603.2.4)

Current version of Brave | 0.17.13
Operating System: macOS Sierra 10.12.5

Video can be reproduced by inspecting the page at:
https://codepen.io/gorkhali/pen/NgmRBR

I am trying to debug my own script and because of navigator.getBattery, all debuggers are skipped.

Thank you very much.

**Comment by Liunkae** [comment]
For privacy reasons, `navigator.getBattery` is not available in Brave. (Issue #1885, commit 7e3d749) It is also not available in Firefox or WebKit-based browsers, but only Chromium-based browsers.

YouTube probably assumes Brave supports `navigator.getBattery` since it's Chromium-based. Not sure how to work around that.

**Comment by luixxiul** [comment]
wontfix? @diracdeltas

**Comment by alokpant** [comment]
Honestly I do not have any use-case for 'navigator.getBattery'. I just embedded  3 videos. However the impact of this error message was that my debugger on console was getting skipped. So it was difficult for me to test feature. I used chrome for all additional testing as there was no error there. 

Please feel free to close it.

**Comment by Liunkae** [comment]
I wonder if we could temporarily spoof `navigator.getBattery` just for YouTube until the API is removed in Chromium.

**Comment by diracdeltas** [comment]
thanks, closing as wontfix since all major browsers are removing support for this API or have already done so
