### ISSUE TITLE
nonexisiting about:.* urls load forever

### ISSUE THREAD

**Issue by ari-s** [brave/browser-laptop#10014]
about:.* urls that do not exist look like they'd load forever with the loading circle in the tab and a blank page otherwise. I'd expect something along the lines of "address isn't valid / can't be reached" (ff / chrome respectively)

examples I tried: 
- about:addons (which is of course a firefoxism)
- about:foobar

This is a fresh installation of brave 2d2ee2f on win7/amd64

**Comment by luixxiul** [comment]
Closing in favor of #9130
