### ISSUE TITLE
Only store menu in appState on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10016]
Currently, we store / update the menu on all platforms, even though it's only used on Windows

We should only take action if the platform is Windows.  Also, instead of serializing the raw template (which has functions, etc), we should store only the menu data

**Comment by bbondy** [comment]
Could you merge to 0.19.x, 0.18.x and 0.17.x? There are some conflicts that you'd be best to resolve. Thanks.

**Comment by bsclifton** [comment]
done! 😄
