### ISSUE TITLE
Whitelist DuckDuckGo for Brave UA

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10020]
Duck Duck Go has a good use case to provide special instructions for better privacy for Brave, and wants to have Brave in the UA.

We do this also for adobe which needs special instructions on desktop.
https://github.com/brave/browser-laptop/blob/master/js/data/siteHacks.js#L64

You should still keep Chrome in the UA, but make it like that link above shows, only for duckduckgo.com.

**Comment by bsclifton** [comment]
Steps to test manually (I ran and verified it works fine)
1. Launch Brave and visit https://duckduckgo.com
2. Open the developer tools (F12 or shift + option + i)
3. Force reload the page (shift + cmd + R or shift + ctrl + R)
4. Inspect the network tab for the `duckduckgo.com` resource
5. Under request headers, you should see the user agent:
"user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/59.0.3071.115 Safari/537.36"

**Comment by bbondy** [comment]
For testing open up the content dev tools and make sure the User Agent (shown on bottom right corner shows "Brave" in the string only for adobe.com and for duckduckgo.com

<img width="1427" alt="screen shot 2017-07-17 at 3 18 02 pm" src="https://user-images.githubusercontent.com/831718/28291721-a9430bae-6b19-11e7-9bf8-1aa23ec1c67d.png">

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/28306299-b16d6c98-6b96-11e7-8cba-029741bc9746.png)

**Comment by LaurenWags** [comment]
adobe.com and duckduckgo.com

![screen shot 2017-07-18 at 10 17 58 am](https://user-images.githubusercontent.com/28145373/28321959-b38ab5d8-6ba2-11e7-8a3f-db941d037d26.png)

**Comment by bbondy** [comment]
lgtm, third test would be making sure a different site doesn't have the word Brave in it.

**Comment by LaurenWags** [comment]
agreed, @bbondy - checked youtube.com also:

![screen shot 2017-07-18 at 1 28 39 pm](https://user-images.githubusercontent.com/28145373/28330856-162fde7e-6bbd-11e7-9182-08b3bc0cb76a.png)

**Comment by bbraithwaite** [comment]
Thank you very much for adding this! I'm a dev @ DDG and was wondering if there is a way to extend this functionality to whitelist the useragent further so that I can be access via JavaScript e.g. `navigator.userAgent`?

Am happy to help out with making the change if you want to point me in the right direction.

**Comment by bsclifton** [comment]
@bbraithwaite good question- maybe we can consider a similar filtering based work-around:
cc: @diracdeltas

**Comment by bbraithwaite** [comment]
@bsclifton Just following up here to ask if this change will be possible in the future? Thank you.

**Comment by bsclifton** [comment]
@bbraithwaite thanks for following up! Would you be able to create a new issue to track that work? I think it's do-able and would be a nice addition 😄
