### ISSUE TITLE
Provide a way to export bookmarks

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1002]
Since we have a way to import now, we should really have a way to export too.

## Test Plan
First scenario
- Go to Bookmarks menu
- Select Export Bookmarks
- Select destination
- Bookmarks are exported

Second scenario
- Go to Bookmarks Manager
- Click on Export icon
- Select destination
- Bookmarks are exported

**Comment by duff2481** [comment]
Completely agree.  +1

**Comment by srirambv** [comment]
[+1](https://linkbubble.zendesk.com/agent/tickets/5465) from support

**Comment by tleger1958** [comment]
Completely agree. +1 

This function is very important to my eyes.

**Comment by luixxiul** [comment]
> And it is very simple to create.

If so, would you please consider to create it?

**Comment by tleger1958** [comment]
My comment was not at all condescending. I love the Brave project, otherwise why would I be using?

I just want to say that it is not at all complicated to make a html file to export bookmarks.

**Comment by luixxiul** [comment]
@tleger1958 I know that. I was just wondering if you don't mind creating the feature. I thought you were a developer :-)

**Comment by tleger1958** [comment]
I could but I never did not propose an improvement. Frankly, I do not know how it really works, because I never wanted to understand. But maybe I'll do someday? (It should not be complicated ...)

**Comment by luixxiul** [comment]
fyi importer has been implemented with #4049

**Comment by alexwykoff** [comment]
+1 from support

**Comment by CelsoGoya** [comment]
+1 Agree

**Comment by oikonang** [comment]
It would be a great feature! +1

**Comment by nsbasic** [comment]
+1

**Comment by tleger1958** [comment]
Thank you!
And the new version is very appreciable.
