### ISSUE TITLE
Bookmarks toolbar : imported sorted bookmarks are represented in wacky order

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10026]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Importing a small set of sorted bookmarks ( < 50 ) the bookmarks menu representation is in order but the bookmarks toolbar menu is not.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
7b31653eb555ba8f00395cd593f9b948ada296fe

- Steps to reproduce:
    1. Import 
[brave_sorted_simple.html.zip](https://github.com/brave/browser-laptop/files/1153889/brave_sorted_simple.html.zip)
    2. Check representations in UI

    
- Actual result:
Bookmarks toolbar menu isn't sorted

- Expected result:
Bookmarks toolbar menu should be sorted

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Likely

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="719" alt="screen shot 2017-07-17 at 3 21 28 pm" src="https://user-images.githubusercontent.com/1434040/28288240-35a22758-6b04-11e7-866b-c3c474352289.png">
vs
<img width="878" alt="screen shot 2017-07-17 at 3 21 39 pm" src="https://user-images.githubusercontent.com/1434040/28288245-39961bd0-6b04-11e7-9ab2-047096d93dad.png">

- Any related issues:

**Comment by NejcZdovc** [comment]
Should be fixed with #9979
