### ISSUE TITLE
Specific tab closing steps makes the active tab to set the wrong index

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10038]
STR: 

1. Open 4 tabs
2. Set 3rd to active
3. Close 1st tab

Expected is that the active tab is set to 2nd but instead it keeps on the 3rd position.

cc @brave/release-team for milestone triage.

**Comment by cezaraugusto** [comment]
may be related https://github.com/brave/browser-laptop/issues/9671, https://github.com/brave/browser-laptop/issues/9083

**Comment by bsclifton** [comment]
This happens all the time; moving to 0.18.x

**Comment by Jacalz** [comment]
Is this the same as https://github.com/brave/browser-laptop/issues/9096

**Comment by bbondy** [comment]
How are you closing the tab in Step 3. Do you set the 1st tab as active first or using right click and close?

**Comment by Liunkae** [comment]
Closing the first tab with the tab's x button reproduces for me.

**Comment by bbondy** [comment]
I'm fairly sure the index work I'm doing in https://github.com/brave/browser-laptop/pull/10095 will also solve this. But there are several problems with it. I'm working through them in that PR.

**Comment by cezaraugusto** [comment]
I hover over the first tab and close by click. No other active tab is set other than step 2

**Comment by Liunkae** [comment]
Maybe related: #9385
