### ISSUE TITLE
Sites shows up with 0 views in payments 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10036]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sites shows up with 0 views in payments 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.17.17
-- | --
rev | dbc3c4d
Muon | 4.1.8

- Steps to reproduce:
    1. Clean install 0.17.17
    2. Enable payments (keep defaults)
    3. Visit sites(both on exclude list and not on exclude list), show up as 0 views instantly after opening the page
    
- Actual result:
Sites shows up with 0 views in payments 

- Expected result:
Should show proper view count for added sites

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes (https://github.com/brave/browser-laptop/issues/9980)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28324065-6e1d14de-6bd2-11e7-806e-df6fdab2bf75.png)

- Any related issues:
https://github.com/brave/browser-laptop/issues/9980

**Comment by luixxiul** [comment]
@NejcZdovc will this issue be fixed with #11037?

**Comment by NejcZdovc** [comment]
@luixxiul hope so :smiley:

**Comment by NejcZdovc** [comment]
this was broken with #9952
