### ISSUE TITLE
spell check not working on Disqus comment boxes

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10040]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported by community (https://community.brave.com/t/spellchecker-install-difficulty/4811)

Spell check is not working in Disqus comment boxes (misspelled words are not underlined in red).

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.17.17
rev | dbc3c4d
Muon | 4.1.8

- Steps to reproduce:
    1. Navigate to a site that uses Disqus comments (I used kpwags.com and opened a blog post).
    2. Type some misspelled words in the comments.
    3. Misspelled words are not underlined in red.
    
- Actual result:
Misspelled words are not underlined.

- Expected result:
Misspelled words should be underlined.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version? 
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by darkdh** [comment]
Please try 0.18.14 and upward because 0.17.17 still use old electron spellchecker implementation

**Comment by LaurenWags** [comment]
@darkdh looks good to me, I've asked community user to confirm also.

**Comment by alexwykoff** [comment]
i think this was fixed by 0.18.x change to spellchecker

**Comment by luixxiul** [comment]
Added the milestone for QA
