### ISSUE TITLE
Import cookie error

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#10043]
`Error: Setting cookie failed`
due to
1. strict secure cookies (https://chromium.googlesource.com/chromium/src.git/+/a26e439d02baa9514b09c637bf5fa9f6790c4c3e)
2. GetCookieDomainWithString check failed

**Comment by luixxiul** [comment]
@darkdh would you mind specifying the manual test plan? thanks!

**Comment by darkdh** [comment]
Test plan
---
1. Go to chrome's user folder and `sqlite3 Cookies`
2. `insert into cookies (creation_utc, host_key, name, value, path, expires_utc, secure, httponly, last_access_utc) values (13145664238592695, '.brave.com', 'brave_test', 'test', '/', 13177200238592692, 1, 1, 13145666083244049);` <=== test for strict secure cookies 
3. `insert into cookies (creation_utc, host_key, name, value, path, expires_utc, secure, httponly, last_access_utc) values (13145664238595566, 'braave.com', 'brave_test', 'test', '/', 13177200238595566, 0, 1, 13145666083245566);` <=== test for GetCookieDomainWithString check failed
4. exit sqlite3
5. Launch Brave and import cookies from Chrome
6. There will not be any console errors `Error: Setting cookie failed`

**Comment by darkdh** [comment]
wrong scenario so and it is reverted here https://github.com/brave/muon/commit/3a6ee2ab99d9cfb5d9f6be2c38df46e8ff5faff0
so no qa required
