### ISSUE TITLE
Encrypt Cookies

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#10044]
We need to encrypt our cookie value in `User Dir/Cookies`
so that we will see `encrypted_value` instead of plain `value`

**Comment by darkdh** [comment]
blocks #10045

**Comment by luixxiul** [comment]
@darkdh would you mind specifying the manual test plan? thanks!

**Comment by darkdh** [comment]
Test Plan
---
1. Go to usr dir and `sqlite3 Cookies`
2. `select host_key, name, value, encrypted_value from cookies;`
3.  you will see value is empty and we have encrypted_value (before this change, you can see a plaintext value and an empty encrypted_value)
