### ISSUE TITLE
Allow multi select of bookmarks w/ drag & drop for bookmark manager

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1005]
Currently it's impossible to manage multiple bookmarks at the same time, you have to do it one at a time.

**Comment by bsclifton** [comment]
Assigned @darkdh- we should get this for free with the work you're doing w/ sortableTable :smile:

**Comment by bsclifton** [comment]
@darkdh finished this functionality with https://github.com/brave/browser-laptop/pull/4607

I've pulled that code in and am making some changes needed in order to use it :smile:
