### ISSUE TITLE
do not allow emojis for page title in titlemode

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10051]
## Test plan
1. have title mode enabled
2. go to http://xn--https-5w14d.cf/paypal.com/
3. titlebar should NOT have emoji in it (should NOT look like picture below)

## Original issue description
1. have title mode enabled
2. go to http://xn--https-5w14d.cf/paypal.com/

result: 

<img width="377" alt="screen shot 2017-07-19 at 12 02 54 am" src="https://user-images.githubusercontent.com/4672033/28349338-b01e20d0-6c18-11e7-814a-a7ec412e1222.png">

cc @diracdeltas

**Comment by bsclifton** [comment]
We are showing punycode... however, the page title is showing emoji (which is tricky).  We may consider filtering certain emoji?

**Comment by diracdeltas** [comment]
i'm a fan of erring on the safe side and not allowing emoji to show up in titleMode. @bradleyrichter thoughts?

**Comment by bradleyrichter** [comment]
I agree. Sounds messy and problematic.

**Comment by cezaraugusto** [comment]
# baby steps to make it cool

for the person interested: we render the title for titleMode in urlBar component, most precisely in [this line](https://github.com/brave/browser-laptop/blob/master/app/renderer/components/navigation/urlBar.js#L377). A safe way to solve this is to install the `emoji-regex` module, which is a small package made just for emojis: 

```
npm i emoji-regex --save
```

you can check our `package.json` to ensure we have it. Once confirmed, include it on top of `urlBar.js` as a dependency:

```js
const emojiRegex = require('emoji-regex')
```

Then still in `urlBar.js`, search for the `titleValue` getter. That's where our hero is waiting for a fix. At the moment of this writing the method looks like this:

```js
  get titleValue () {
    // For about:newtab we don't want the top of the browser saying New Tab
    // Instead just show "Brave"
    const title = 
    return ['about:blank', 'about:newtab'].includes(this.props.urlbarLocation)
      ? '' : this.props.title // HERE'S OUR HERO!!
  }
```

See that the else condition in the above ternary? `this.props.title` is the code for the title you want to strip out the emojis.

You can make use of the `emoji-regex` module we just installed, and just `replace()` all emoji occurrences with an empty string:

```diff
  get titleValue () {
    // For about:newtab we don't want the top of the browser saying New Tab
    // Instead just show "Brave"
    const title = 
    return ['about:blank', 'about:newtab'].includes(this.props.urlbarLocation)
-      ? '' : this.props.title
+      ? '' : this.props.title.replace(emojiRegex(), '')
  }
```

ensure to run our app again and test http://xn--https-5w14d.cf/paypal.com/ to see if you still see that golden evil lock emoji. Don't you? We're waiting for your PR!

**Comment by prasanthp96** [comment]
I am interested to fix this bug.

**Comment by prasanthp96** [comment]
hy @cezaraugusto how to enable the title mode in brave??

**Comment by cezaraugusto** [comment]
if you're running Windows you'll need to disable "always show the URL bar" it in advanced->URL Bar Options:

<img width="517" alt="screen shot 2017-08-03 at 10 37 00 am" src="https://user-images.githubusercontent.com/4672033/28930248-fb558072-7837-11e7-8031-4457da2d82fe.png">

we call `titleMode` the additional layer which hides the urlbar form until you mouse over the chrome bar. It looks like the screenshot I added in the first comment.

**Comment by prasanthp96** [comment]
hello @cezaraugusto , I have sent a PR . Kindly have a look at it.

**Comment by prasanthp96** [comment]
hy @cezaraugusto , my pr does not pass the travis test cases.. can you help me to fix the issue ?

**Comment by luixxiul** [comment]
@prasanthp96 currently there are some travis tests which consistently fail (we are trying to fix them all). If you see that your change does not break another test, then please leave the change as it is. If you cannot tell, please ping @cezaraugusto for audit :-)

**Comment by srirambv** [comment]
Still happens on Windows. 
![10051](https://user-images.githubusercontent.com/17010094/34262055-1b81ab7a-e663-11e7-86b8-c155cef85ff8.gif)

**Comment by srirambv** [comment]
Works as expected
