### ISSUE TITLE
Pinned tabs lost when browser closes abruptly 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10053]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Pinned tabs lost when browser closes abruptly 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.17.16 / 0.17.17
-- | --
rev | 2d2ee2f / dbc3c4d
Muon | 4.1.8

- Steps to reproduce:
    1. Create 5-6 pinned tabs (normal and session tabs)
    2. Open few tabs and load pages in them
    3. Ensure the system memory usage and CPU usage is high by opening VM guest or other heavy applications
    4. Ensure Brave is not the active app when the CPU is at  95% and Memory is at >60%
    5. Click on Brave to make it active
    6. Application inactive window is shown which says `Brave stopped responding` with `Debug` and `Close application` buttons
   7. Click on `Close application` so that the app is killed by Windows process
   8. Relaunch Brave, all pinned tabs are lost, only the normal tabs are shown
    
    
- Actual result:
Pinned tabs lost when browser closes abruptly 

- Expected result:
App state should not change and all tabs should be restored

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes. Experienced it once on 0.17.16 and once on 0.17.17. Could be there in previous builds as well. Have seen the `Application not responding` window before but no pinned tabs were there (as far as i can tell)

- Can this issue be consistently reproduced?
It can be reproduced may be not consistently. 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Edit: Added screenshot of the error message after which the pinned tabs are lost
![image](https://user-images.githubusercontent.com/17010094/28494083-e9f4599a-6f1b-11e7-9a7d-b1c6f849f47b.png)

- Any related issues:
cc: @bbondy @bridiver @bsclifton

**Comment by srirambv** [comment]
Experienced it on 0.17.19 as well. After reopening all pinned tabs lost. Had to quite the browser(Ctrl+Q) and then restart to get back the pinned tabs

**Comment by alexwykoff** [comment]
@srirambv let's retest with 0.18.x please

**Comment by bsclifton** [comment]
Closing as this needs to be retested.  If issue still occurs, let's re-open 😄

**Comment by srirambv** [comment]
Still see this on the latest hotfix. Browser memory and CPU usage spikes up quite a lot and causes it to crash. Have experienced it at least 5 times already on the latest hotfix.
