### ISSUE TITLE
Error while build-package

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10060]
**Describe the issue you encountered:** error while build-package

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master

- Steps to reproduce: `git checkout master && git rebase upstream/master && rm -rf ~/.electron && rm -rf node_modules && npm i && CHANNEL=dev npm run build-package`
    
- Actual result:
    ````
    Packaging app for platform darwin x64 using electron v4.4.0
    Wrote new app to /Users/Suguru/browser-laptop/Brave-darwin-x64
    There were errors during the copy.
    Error: ENOENT: no such file or directory, lstat '/Users/Suguru/browser-laptop/node_modules/spellchecker/vendor/hunspell_dictionaries'
    ````

- Expected result: that error should not happen

- Any related issues:

**Comment by bsclifton** [comment]
Nice catch 😄  I believe this is happening because of https://github.com/brave/browser-laptop/issues/9880

@darkdh we may need to remove these two lines:
https://github.com/brave/browser-laptop/blob/master/tools/buildPackage.js#L127-L128
