### ISSUE TITLE
Sync should synchronize Payments

### ISSUE THREAD

**Issue by DavidRBailey** [brave/browser-laptop#10066]
Brave Sync should synchronize Brave Payment status.

Users should be prompted only once per month to make payments on Brave across all synchronized devices. Additional devices that have Brave Sync enabled should not prompt for payments once payment has been made on any synchronized device.

Browser history, time, views, and percentages should be reflected and considered across all synchronized devices rather than individually on each device when the Brave Payments payment cycle occurs.

[As stated in Brave design wiki](https://github.com/brave/sync/wiki/Design)- "we plan to add support for syncing Brave Payments data..."

**Comment by bsclifton** [comment]
cc: @bradleyrichter @mrose17

**Comment by DavidRBailey** [comment]
Here are some mockups.

Note the new toggle on the first one, and explanatory text and link to the Sync tab on the second mockup. All of the data in the sites list would be aggregated between and the payment would be valid for all synchronized browsers.

![brave payments sync mockup 1](https://user-images.githubusercontent.com/5591109/28594303-b5ab09d0-714c-11e7-8ee9-3a279d515213.png)
![brave payments sync mockup 2](https://user-images.githubusercontent.com/5591109/28594304-b5ae041e-714c-11e7-9c5d-608924888ab6.png)

**Comment by bradleyrichter** [comment]
@DavidRBailey Thanks for the mockups. This looks good.

We should be starting the plumbing for this soon, which will come easier once history and tab data is privately synced. (WIP)

**Comment by ocramc** [comment]
It really feels like this should be more of a priority seeing as how the BAT is the unique selling point of the browser
