### ISSUE TITLE
dual screen minimize

### ISSUE THREAD

**Issue by bhuettmann** [brave/browser-laptop#10067]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
maybe its display adapter or version specifically so here info about: nvidia GTX970, driver 22.21.13.8253

- Platform (Win7, 8, 10? macOS? Linux distro?):
win7

- Brave Version (revision SHA):
2d2ee2f

- Steps to reproduce:
    1. have a brave-window open
    2. minimize it with the top right window-minimize-button(not the shortcut: ALT(hold)-blank-n) and hurry, so the hovering test 'Minimize' do not appear before you had clicked.
    3. see the the hovering text appears on the second screen and stay till you bring the window back.
    
- Actual result:
some left over

- Expected result:
no left over

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
don't know

- Can this issue be consistently reproduced?
yes

- Screenshot if needed:
this is the window looking nice:
![brave_min_0 17 16_01](https://user-images.githubusercontent.com/30300530/28387217-834b08e6-6cce-11e7-8804-85783a91a1d6.png)

this is the left-over on the second(left) screen 
![brave_min_0 17 16_02](https://user-images.githubusercontent.com/30300530/28387260-ae991696-6cce-11e7-960b-b49a33be55d3.png)

**Comment by bsclifton** [comment]
Thanks for the report, @bhuettmann 😄  We're tracking this already with https://github.com/brave/browser-laptop/issues/8697, so I'd like to close this issue as a duplicate (please subscribe to that issue for updates).  Really weird to see a dual screen variant
