### ISSUE TITLE
Commands for webdriver tests will be deprecated 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10072]
**Describe the issue you encountered:** Commands for webdriver tests will be deprecated and need updating.

See: https://travis-ci.org/brave/browser-laptop/jobs/255111151#L3536

`
WARNING: the "timeoutsAsyncScript" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
`
`
WARNING: the "keys" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
`
`
WARNING: the "moveTo" command will be depcrecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
`

and so on.

- Brave Version (revision SHA): master branch

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
Yes this should be fixed sooner then later, because it's hard to read test reports

**Comment by luixxiul** [comment]
`keys` command does not seem to be replaced straightforward: 

See: https://stackoverflow.com/questions/44339046/browser-keys-is-not-working-on-firefox-53-0-webdriver-io#44372787

**Comment by NejcZdovc** [comment]
for now they don't have any upgrade paths, so we should downgrade and fix webdriver to 4.7.x

https://github.com/webdriverio/webdriverio/issues/2076

**Comment by luixxiul** [comment]
Is it impossible to suppress the warning messages without downgrading only to hide the messages? It looks to me that it just postpones fixing the issues, which would be required eventually.

IMHO we should investigate each command and triage which one can be fixed easily or not, and suppress the warning message only of the commands which takes time to fix.

**Comment by NejcZdovc** [comment]
correct. As you can see author of webdriver is suggesting to downgrade, because there is no upgrade path for any commands. There is currently no other ways to remove this message other then downgrade or remove webdriver.

**Comment by luixxiul** [comment]
@NejcZdovc mind taking look at this? https://stackoverflow.com/a/44712416

**Comment by NejcZdovc** [comment]
@luixxiul what would we benefit from upgrading to 4.8.x?

I looked at link that you posted and this workaround would cover most of our use cases, but not all of them.

>So if you want to hold a key and do mouse interactions, then tough luck buddy, perhaps we have to wait for the browsers to implement the Webdriver Actions API

**Comment by luixxiul** [comment]
I'm not sure of the benefit of either upgrading or downgrading. Still, if displaying the warning messages can be suppressed by configuration, that seems to me better than downloading.

If you are sure that downgrading does not block a future upgrade, I don't think it is not a bad idea to do so. Still, if the workaround would reduce the warning messages as much as we could endure, I think implementing the workaround should be better than downgrading or suppressing the messages.

**Comment by NejcZdovc** [comment]
Benefit of downgrading is removal of this notifications which are really annoying and they can be time consuming when you are going though tests.

I think that we should just lock it because even core team said to do so. With upgrade we don't benefit anything really (AFAIK) and if we upgrade we would need to spend quite some dev time doing a lot of workaround to fix everything. I think it's jus not worth it based on what we get with 4.8. When they provide official upgrade path then it's time to upgrade IMHO.

**Comment by luixxiul** [comment]
CC @bbondy for a final call.

**Comment by bsclifton** [comment]
I agree with the recommendation by @NejcZdovc, which is what the core members / maintainers for WebDriver.io recommend:
> https://github.com/webdriverio/webdriverio/issues/2076#issuecomment-304981623
https://github.com/webdriverio/webdriverio/issues/2076#issuecomment-304981623

and
> Make sure you use the downgraded version. These message got introduced in v4.8
https://github.com/webdriverio/webdriverio/issues/2076#issuecomment-309724115

@luixxiul unless you're willing to support WebDriver issues when they arise and help with fixing broken tests, I don't think it makes sense to go against the maintainers recommendations.  Upgrading will introduce more problems and doesn't appear to solve any problems
