### ISSUE TITLE
Extension updating : The system needs a way to unload/reload an extension which doesn't require restart or user intervention

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10076]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Attempting to update an extension now requires a restart.

**Comment by alexwykoff** [comment]
It's believed we used to have this functionality and this is actually a regression.

**Comment by bsclifton** [comment]
cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
would this be the same as #7822?
