### ISSUE TITLE
HTTPSE issue with http://www.thompsonhotels.com

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10081]
CSS doesn't seem to load due to HTTPSE on the following URL:
http://www.thompsonhotels.com/hotels/chicago/thompson-chicago/accommodations/rooms-suites

Could you investigate @diracdeltas? Thanks!

**Comment by bsclifton** [comment]
Verified it works correctly! 😄 

Marked as no QA needed since this is not part of the 0.18.x release. I'll also remove milestone.  This is live
