### ISSUE TITLE
Regression : Toolbar and UI Elements scale control is not working

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10089]
## Test plan

https://github.com/brave/browser-laptop/pull/10578#issue-251151787

----

Steps to reproduce:
1. Go to Preferences > Advanced
2. Under "Toolbar and UI Elements scale", pick a different value from the drop down
3. you'll be prompted to restart. Ignore this or click "no"
4. Notice that the top area (where the URL bar is) hasn't changed in size
5. Open a new window and notice the size is different

**Comment by Liunkae** [comment]
Maybe related: #9334

**Comment by bsclifton** [comment]
This works when you exit and relaunch- it's no longer taking immediate effect. Looking into why...

**Comment by bsclifton** [comment]
Code path looks to be the same when you launch (and it gets set) versus setting once the browser is already loaded:
```
WebContents::SetZoomLevel
ZoomController::SetZoomLevel
ZoomController::SetZoomLevelByClient
> ZoomController::SetZoomLevelForHost
```

Will continue digging in

**Comment by bsclifton** [comment]
It also seems that if the setting changes and the window gets minimized, when restored it will be the proper size

**Comment by bsclifton** [comment]
This is a regression in Muon- I can't repro the issue with Muon 4.1.9... but 4.3.x has the issue for sure

**Comment by bsclifton** [comment]
Created https://github.com/brave/browser-laptop/issues/10132 as a work-around for 0.18.x. I think Chromium 60 upgrade is affecting this

cc: @hferreiro, @bridiver

**Comment by bridiver** [comment]
this needs STR

**Comment by bsclifton** [comment]
@bridiver steps added 😄

**Comment by bsclifton** [comment]
See notes in Chromium review by @bridiver for more info:
https://codereview.chromium.org/2888203006
