### ISSUE TITLE
1Password 6.8 Plugin Broken

### ISSUE THREAD

**Issue by stevespringett** [brave/browser-laptop#10080]
Brave 0.17.16 does not work with 1Password 6.8.

After the 1Password 6.8 upgrade from the Mac App Store, the integration with Brave ceased to work.

<img width="504" alt="screen shot 2017-07-20 at 2 36 44 pm" src="https://user-images.githubusercontent.com/3878933/28435539-109f98a8-6d59-11e7-96f0-398b2bb06c90.png">

**Comment by alexwykoff** [comment]
We're about to update the extension so it will support 6.8.

Thanks for the report!

**Comment by alexwykoff** [comment]
Should be fixed now, please update & restart Brave, thanks!

**Comment by stevespringett** [comment]
Perfect! Thanks a bunch
