### ISSUE TITLE
Basque language is missing translations in 0.18.x

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10088]
Attached are screenshots highlighting missing translations in our preference panes
[Basque 0.18.7.zip](https://github.com/brave/browser-laptop/files/1166655/Basque.0.18.7.zip)

Kabob menu
<img width="241" alt="screen shot 2017-07-21 at 3 22 13 pm" src="https://user-images.githubusercontent.com/1434040/28480950-816af080-6e28-11e7-9f86-d344a981700f.png">
<img width="499" alt="screen shot 2017-07-21 at 3 22 25 pm" src="https://user-images.githubusercontent.com/1434040/28480949-81689254-6e28-11e7-8032-9b1623bea850.png">
<img width="456" alt="screen shot 2017-07-21 at 3 22 31 pm" src="https://user-images.githubusercontent.com/1434040/28480951-8172d232-6e28-11e7-904d-e81f8ee784fe.png">

Main menus
<img width="275" alt="screen shot 2017-07-21 at 3 23 45 pm" src="https://user-images.githubusercontent.com/1434040/28481003-bce47bf4-6e28-11e7-809b-6657bef8b7fe.png">
<img width="569" alt="screen shot 2017-07-21 at 3 23 59 pm" src="https://user-images.githubusercontent.com/1434040/28480998-bcdff4e4-6e28-11e7-90d5-079a83438fd6.png">
<img width="313" alt="screen shot 2017-07-21 at 3 24 05 pm" src="https://user-images.githubusercontent.com/1434040/28481001-bce2b31e-6e28-11e7-8f2d-d1d1ab90b6e4.png">
<img width="238" alt="screen shot 2017-07-21 at 3 24 11 pm" src="https://user-images.githubusercontent.com/1434040/28481002-bce36a8e-6e28-11e7-876a-3a8b538ade83.png">
<img width="263" alt="screen shot 2017-07-21 at 3 24 16 pm" src="https://user-images.githubusercontent.com/1434040/28480999-bcdfdb08-6e28-11e7-8fa8-1de687fc43c7.png">
<img width="387" alt="screen shot 2017-07-21 at 3 24 20 pm" src="https://user-images.githubusercontent.com/1434040/28481000-bce164d2-6e28-11e7-8345-5a27b89dd0ba.png">

Bravery (Shields) menu
<img width="535" alt="screen shot 2017-07-21 at 3 25 27 pm" src="https://user-images.githubusercontent.com/1434040/28481039-e6b961d8-6e28-11e7-969d-5cd483a319f7.png">

**Comment by luixxiul** [comment]
isn't it just because the strings are not translated yet?
