### ISSUE TITLE
Improve CSS for SSL Cert Warnings to Look More Aesthetically appealing.

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1008]
@bradleyrichter  See <img width="828" alt="screen shot 2016-03-04 at 1 55 57 pm" src="https://cloud.githubusercontent.com/assets/470705/13538561/ee2d9c86-e210-11e5-99bf-017ffb612cae.png"> for an Example from Chrome.

**Comment by bradleyrichter** [comment]
yes! this is an ugly wrinkle in the fabric of UI polish. I'll zap that one soon. Thanks for GITing it up here.
