### ISSUE TITLE
Missing translation tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10087]
- Basque https://github.com/brave/browser-laptop/issues/10088
 - Bengali (Bangladesh)
 - Bengali (India)
 - Chinese (Simplified)
 - Czech
 - Dutch
 - French
 - German
 - Hindi
 - Indonesian
 - Italian
 - Japanese
 - Korean
 - Malay
 - Polish
 - Portuguese (Brazil)
 - Russian
 - Slovenian
 - Spanish
 - Tamil
 - Telugu
 - Turkish
 - Ukranian

**Comment by alexwykoff** [comment]
Updating for 0.18.x

Will edit main post with links to subtasks

**Comment by luixxiul** [comment]
Swedish is not available at all, cc @Jacalz

**Comment by Jacalz** [comment]
Yeah no sign of Swedish on master 😕
