### ISSUE TITLE
0.18.x: Lock icon not showing in URL bar

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10093]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
The "lock" icon is no longer showing in the URL bar. It worked fine in 0.17.x but stopped working in 0.18.x.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.18.8 (32d8cf8)

- Steps to reproduce:
    1. Open a new window.
    2. Go to github.com.
    
- Actual result:
The "search" icon is shown in the URL bar.

- Expected result:
The "lock" icon should be shown to indicate that the site is secure.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a new window.
    2. Go to github.com.
    3. Make sure the "lock" icon is shown in the URL bar.

- Screenshot if needed:
![](https://user-images.githubusercontent.com/19424103/28494988-b782e902-6f04-11e7-9e9e-86ba109a59f9.png)

- Any related issues:
None.

**Comment by bbondy** [comment]
fixed here
https://github.com/brave/browser-laptop/commit/639013e4aaf51ead0d33f7bc4d40dfd5b31adfa3
