### ISSUE TITLE
Vertical alignment is off on Payments "Add Funds" button

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10098]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
0.18.10 beta

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/73465bb6af2289ede944b9bd6349cdef65859efa

- Steps to reproduce:
    1. Go to Preferences > Payment
    2. Enable payments
    3. Notice button text
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screen shot 2017-07-23 at 7 45 34 pm](https://user-images.githubusercontent.com/4733304/28506375-bfe51148-6fdf-11e7-89b3-22377a6967c4.png)

- Any related issues:

cc: @luixxiul

**Comment by bsclifton** [comment]
Does this button properly match the style examples shown on `about:styles`? I didn't notice any issues with buttons there

**Comment by luixxiul** [comment]
weird, the issue was fixed on 0.17.19. https://github.com/brave/browser-laptop/pull/9487 CC @cezaraugusto

**Comment by bsclifton** [comment]
good catch- it was missed in 0.18.x

@cezaraugusto can you please merge into 0.18.x? I get a conflict when cherry-picking. It's already in master and 0.19.x 😄 

`git cherry-pick -m 1 ddc30fda6fd4596d48f63d154f4dee10014f55d0`

**Comment by luixxiul** [comment]
@bsclifton thanks for digging in :smile:

**Comment by cezaraugusto** [comment]
thanks team, cherry-picked to 0.18.x https://github.com/brave/browser-laptop/commit/67b911bd09f433bde15ab0f1568def015f25d079. Closing

**Comment by bsclifton** [comment]
Thanks, @cezaraugusto! :smile:

**Comment by NejcZdovc** [comment]
@cezaraugusto should we change milestone of #9487 from 0.19 to 0.18?

**Comment by bsclifton** [comment]
@NejcZdovc good catch! I just moved those now, so that they're in 0.18.x 😄
