### ISSUE TITLE
Foward and Back button not working on Logitech MX Masters

### ISSUE THREAD

**Issue by chris1000** [brave/browser-laptop#10099]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: Cannot use the forward and back button on my MX Masters mouse like I can with Google Chrome (that way I can easily go from page to page)

- Platform (Win7, 8, 10? macOS? Linux distro?): MacOS (10.12)

- Brave Version (revision SHA): 4e46480

- Steps to reproduce:
    1. Click forward and back button on mouse
    2.
    3.
    
- Actual result: Nothing happens at all

- Expected result: Allow me to navigate pages with the buttons that way I can go from previous pages back to other pages

- Will the steps above reproduce in a fresh profile? Yes. If not what other info can be added? Nothing extra needed

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Thanks for the report, @chris1000!  We have captured this issue here, which you can track for updates:
https://github.com/brave/browser-laptop/issues/3101

Closing this issue as a duplicate
