### ISSUE TITLE
Update acorn to 5.1.1

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10097]
**Describe the issue you encountered:** Update acorn to 5.1.1, which is the latest version.

https://www.npmjs.com/package/acorn

Travis run result: https://travis-ci.org/brave/browser-laptop/builds/256630076

- Brave Version (revision SHA): https://github.com/brave/browser-laptop/commit/2ceca288c99650dfeb55a2e7533da6601e630a0f

- Any related issues:

**Comment by bsclifton** [comment]
FYI- Acorn is only used in the ledger... specifically in `cacheRuleSet`
https://github.com/brave/browser-laptop/blob/2ceca288c99650dfeb55a2e7533da6601e630a0f/app/ledger.js#L1321

@mrose17 what would a good way test this? The code is loading the ruleset... what exactly is that? Is that the exclusion list? (ex: leave out .gov, etc)

**Comment by bsclifton** [comment]
Closing this issue because it's not required and there hasn't been any input
