### ISSUE TITLE
Browser freezes per 5 minutes with existing profile

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10094]
**Describe the issue you encountered:** Browser freezes with existing profile. The issue is not reproducible for me on macOS. I have not tested the issue on a linux distribution or Windows 7.

A related issue was reported here: https://community.brave.com/t/brave-freezes-after-short-period-of-being-idle/4783/10

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.17.19

- Steps to reproduce:
    1. Use the browser long (to load much data on the browser's profile)
    2. Load a youtube video (to make the lag noticiable)
    
- Actual result: the browser freezes for seconds per some minutes

- Expected result: the browser should not freeze

- Will the steps above reproduce in a fresh profile?
   No, I don't think so.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9808 #9311

**Comment by luixxiul** [comment]
According to this report, the issue can be reproduced on macOS too: https://community.brave.com/t/browser-frequently-freezes-mac-osx/4923/3?u=suguru

**Comment by luixxiul** [comment]
I noticed that the browser freezes around each 5 minutes, suspecting that the issue is related with writing/reading data.

**Comment by luixxiul** [comment]
@bsclifton / @bridiver what do you think about ^?

On https://github.com/brave/browser-laptop/issues/5512#issue-188317874

> Session should auto-save itself every 5 minutes. (added with https://github.com/brave/browser-laptop/commit/931facfafc8a4caaceb2440e18df8e1b0c0c8199)

If the value [here](https://github.com/brave/browser-laptop/commit/931facfafc8a4caaceb2440e18df8e1b0c0c8199#diff-2018087f584c4398b5c3a23fc0e5f9dbR367) is changed to `1 * 60 * 1000` and the UI is locked each minute, then it is highly likely that the saving session file locks the UI.

I would like to test that, if test build is released for testing. Also there are some users reporting the similar issue on community, and we would be able to ask them to run the binary to verify the issue.

**Comment by bsclifton** [comment]
A potential fix for the underlying issue may be possible with upcoming Muon build (see https://github.com/brave/muon/commit/57ecc85913296dc29d6bce708aba77018884e9bc).  Once this is built, we can update browser-laptop to use this `sendShared` method

cc: @bridiver @bbondy

**Comment by bridiver** [comment]
@luixxiul I don't think that saving the session file is causing the UI to lock because it happens on a separate thread. What is more likely causing the UI to lock is the ipc transfer of the window state that @bsclifton referenced

**Comment by luixxiul** [comment]
Added the milestone based on https://github.com/brave/browser-laptop/pull/10305#event-1193965004

**Comment by luixxiul** [comment]
Playing 30 min video on Netflix, the browser's UI was not locked at all :-)

**Comment by luixxiul** [comment]
Recently Netflix video started freezing for a couple of seconds again. It happens sometimes. I am not sure how to reproduce the issue. I am wondering if it is related with the URL bar performance issue reported on https://github.com/brave/browser-laptop/issues/11066.
