### ISSUE TITLE
Tab preview does not work properly with DnD

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10103]
**Describe the issue you encountered:** Tab preview does not work properly with drag-and-drop.

![tabpreview](https://user-images.githubusercontent.com/3362943/28509495-b7d39670-707d-11e7-8789-a40cf7db4d06.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open https://developer.mozilla.org/en/docs/Web/API/Geolocation/Using_geolocation
    2. Open https://twitter.com/brave in a new tab
    3. Drag and drop the 1st tab after the 2nd one
    
- Actual result: the 1st tab (which is inactive) preview is displayed, until you move the mouse cursor

- Expected result: the 2nd tab (which is active) preview should be displayed soon after the tab is dropped

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #8902

**Comment by cezaraugusto** [comment]
I think we should cancel the preview if tab is being dragged

**Comment by cezaraugusto** [comment]
actually I'm going to do this ^^^ way. let me know if you disagree

**Comment by cezaraugusto** [comment]
cc @zentagonist setting to sprint/1 and tagging for 0.20.x as it will be fixed by #10691
