### ISSUE TITLE
Importing HTML with Imported name

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10106]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):
probably all
- Brave Version (revision SHA):
2ceca28
- Steps to reproduce:
    1. go to importer
    2. import attached file
    
- Actual result:
![image](https://user-images.githubusercontent.com/9574457/28527499-f3654de8-708a-11e7-906e-7e91a1cb9141.png)

- Expected result:
Bookmarks should be imported and displayed correctly
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

**File:** https://gist.github.com/NejcZdovc/315605c304659c98e3cd7b48d624626d

cc @darkdh

**Comment by WausauBill** [comment]
This is still a bug on this version:
 
Brave: 0.20.15 
V8: 6.3.292.48 
rev: 6fd801b0cb23c8d22c2653f66fd61ed6b813ce79 
Muon: 4.5.33 
OS Release: 4.8.0-53-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 63.0.3239.108

Chrome and Firefox bookmarks import properly, but not the stand alone .html file.
