### ISSUE TITLE
Update doesn't work on macOS

### ISSUE THREAD

**Issue by namflashback** [brave/browser-laptop#10100]
Hi,
The updater doesn't work on MacOS Sierra. I'm running it on the newest gen of the iMac.
Searching, I found this issue #2184 
That lead me to a [closed bug.](https://community.brave.com/t/browser-update-bug/3751/5
)

The updater doesn't actually update anything. It just closes the browser, and no other processes spawn as far as I can tell.  

I'm using a standard account (not sudoer). I'm not sure if that has any impact or not.

**Comment by gpatkinson** [comment]
Yeah, I'm having the same issue on all three macs that I use, two with El Capitan and one with an older version (sorry, don't know which one). I tried following the instructions here:

https://github.com/brave/browser-laptop/wiki/End-User-FAQ#updates-are-available-but-applying-them-doesnt-work-on-macos

The file mentioned isn't living in /Application_Support.

**Comment by alexwykoff** [comment]
@gpatkinson do you have both 'Admin' and 'standard' user accounts on your machines?

**Comment by pleticha** [comment]
I have had the same issue - The update button only shuts down Brave - no apparent attempt to install a new version.   I am running the latest Sierra version.  I am a standard User (not an Admin). 
And yes there is an Admin acct on the system -

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/hello-a-brave-update-was-just-released-requires-a-quick-relaunch/14746

**Comment by sophiataskova** [comment]
Is this referring to the 0.20.30 update? I thought Brave had been updating fine until this version came along, but I might be misremembering.

**Comment by pleticha** [comment]
I have never had it ‘update’ without manually downloading the new version and reinstalling.

with the latest 29.29 to 20.30 - when I clicked update - it did shut down Brave - but the new version was NOT download nor was anything installed


Mark 


___________________________

**Comment by petemill** [comment]
Confirmed - we have replicated this now. The autoUpdater will fail to update on a non-admin user account is running, even if that user account has ownership, and write permissions, to the app.

**Comment by bsclifton** [comment]
+1 from @justsee via https://github.com/brave/browser-laptop/issues/12991

**Comment by praveenc** [comment]
Hi, this is still happening even in version `v.22.810` - any idea when will this be fixed?

**Comment by namflashback** [comment]
I can confirm that the update worked properly, and asked for a user name / password for the admin account. I will close this issue.
Thank you guys so much :)

Below is the version that I upgraded to:


Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71
