### ISSUE TITLE
Missing translation for bookmark list

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10105]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Translation is missing for multiple bookmarks dnd. Problematic code can be found here https://github.com/brave/browser-laptop/blob/master/app/renderer/about/bookmarks/bookmarksList.js#L48.

**Comment by Liunkae** [comment]
PR: #13010

**Comment by srirambv** [comment]
Drag and drop bookmarks on text editor doesn't work on Windows. Is this OS X specific issue?

**Comment by bsclifton** [comment]
@srirambv I believe it is - can you try on Linux? (with gEdit or similar)

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.11 6565c06
* Muon 7.1.0
* libchromiumcontent 67.0.3396.87

**Comment by btlechowski** [comment]
Drag and drop bookmarks on text editor doesn't work on Ubuntu 17.10.
