### ISSUE TITLE
Bookmark cannot be moved to bookmark folder on bookmark toolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10101]
**Describe the issue you encountered:** Bookmark cannot be moved to bookmark folder on bookmark toolbar.

![bookmark](https://user-images.githubusercontent.com/3362943/29101650-a63f4364-7cee-11e7-92d1-3300706bf80a.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 2ceca28

- Steps to reproduce: Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works

- Actual result: it does not work

- Expected result: it should work

- Any related issues:

**Comment by tblu** [comment]
confirmed on win10, rev 4e46480

**Comment by NejcZdovc** [comment]
@luixxiul can you please try it on the latest master? For me it's working, but it's hard to nail it :smiley:

**Comment by pullingour** [comment]
same issue happened.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X 10.11.6

- Brave Version (revision SHA):
0.18.14

![brave_bug2](https://user-images.githubusercontent.com/7346730/29005543-5dc4fade-7b18-11e7-83ce-aff5577864f8.gif)

**Comment by luixxiul** [comment]
@pullingour I'm not quite sure how this is the same one.

**Comment by pullingour** [comment]
@luixxiul Should I make a new issue?

**Comment by luixxiul** [comment]
@pullingour yes please, thanks.

**Comment by sjlehn** [comment]
@pullingour I just entered a defect for that #10323

**Comment by bsclifton** [comment]
@pullingour In your screenshot, it shows you drag to the `.ca` folder... Can you try this again, but this time click somewhere else (like inside the page)... then re-click the `.ca` folder? I believe the issue is that the context menu didn't get re-rendered yet (with the new item inside). Once you force the app to re-create + show the menu again, it usually shows the correct menu

**Comment by pullingour** [comment]
@sjlehn Thanks! I'll post description and screenshot for #10323

@bsclifton I tried again, the same problem happened. I'll post another screenshot for #10323 
This issue happen when I try drag and drop bookmark that top of folder only. Another bookmarks are fine. I will write more detailed explanation for #10323

**Comment by alexwykoff** [comment]
@luixxiul this needs comparison vs other browsers. the interaction makes sense for files but we need to compare vs browsers

**Comment by luixxiul** [comment]
This is the issue I reported:

![bookmark](https://user-images.githubusercontent.com/3362943/29101650-a63f4364-7cee-11e7-92d1-3300706bf80a.gif)

Actually this is a regression based on 0.18.14.

**Comment by zentagonist** [comment]
Removing from the milestone, and will be addressed when drag/drop in the browser is addressed with more focus.

**Comment by luixxiul** [comment]
This seems to have been fixed with 0.18.26. Assigning the milestone for QA
