### ISSUE TITLE
Cursor not shown when editing a bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10104]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Cursor not shown when editing a bookmark

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.0
-- | --
rev | 676ab6a 
Muon | 4.4.3

- Steps to reproduce:
    1. Build from 676ab6a and launch
    2. Add a bookmark 
    3. Edit the bookmark, Cursor is not shown, makes it extremely impossible to edit the bookmark
    
- Actual result:
Cursor not shown when editing a bookmark

- Expected result:
Cursor should blink to indicate where it is

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Found it while verifying #9602 
    2.
    3.

- Screenshot if needed:
![9602](https://user-images.githubusercontent.com/17010094/28514892-9725b84c-7053-11e7-8def-daa28287b8a9.gif)

- Any related issues:
cc: @NejcZdovc @bsclifton

**Comment by bsclifton** [comment]
I think it's been called out elsewhere... but when this happens to me, I can minimize/restore Brave or switch to another app and then switch back and the cursor seems to magically reappear

**Comment by bsclifton** [comment]
Marking as closed- @luixxiul said this should be fixed by https://github.com/brave/browser-laptop/pull/10165
