### ISSUE TITLE
Cancel button needed on add bookmark

### ISSUE THREAD

**Issue by seeam** [brave/browser-laptop#1011]
If I right click and choose **Add Bookmark**, there is no visible cancel button. To cancel it requires to click on any empty place, which is somewhat confusing I think. So a cancel button will be comfortable.

**Comment by luixxiul** [comment]
I think this is a good idea and should be labelled as good-first-bug.

How do you think, @bbondy?

**Comment by luixxiul** [comment]
Closing for now based on the discussion #2091
