### ISSUE TITLE
Brave should not exit when every tab is pinned

### ISSUE THREAD

**Issue by dogancelik** [brave/browser-laptop#10117]
#### Did you search for similar issues before submitting this one?  
Kinda

#### Describe the issue you encountered:  
Brave closes completely when you press Ctrl+W and there is no normal tab.

#### Platform (Win7, 8, 10? macOS? Linux distro?):  
Windows 8.1

#### Brave Version (revision SHA):  
dev channel / 4e46480561da44d76d6ee4c60d6979df80d339f8

#### Steps to reproduce:
1. I have 7 pinned tabs
2. I close unpinned tabs and I switch to a pinned tab.
3. I press <kbd>Ctrl</kbd> + <kbd>W</kbd>
4. Whole Brave window closes
    
#### Actual result:  
Brave completely exits / closes

#### Expected result:  
<kbd>Ctrl</kbd> + <kbd>W</kbd> should NOT close Brave, should not even close Pinned tab.

#### Will the steps above reproduce in a fresh profile? If not what other info can be added?  
This is a really fresh install, installed today.

#### Is this an issue in the currently released version?
I don't know, new install after a long time

#### Can this issue be consistently reproduced?  
Yes

**Comment by luixxiul** [comment]
I remember that @bradleyrichter agreed with this.

**Comment by bsclifton** [comment]
I tried this out on master- appears to have been fixed by https://github.com/brave/browser-laptop/pull/10531 😄

**Comment by LaurenWags** [comment]
Reproduced on MacOS. STR:
1. have 7 pinned tabs
2. close unpinned tabs and you switch to a pinned tab.
3. press Cmd + W
4. Whole Brave window closes

![10117](https://user-images.githubusercontent.com/28145373/33047497-20b5077e-ce24-11e7-9c2b-12dc0d6f4633.gif)

**Comment by dogancelik** [comment]
Also Pinned tabs should not close at all

**Comment by bradleyrichter** [comment]
Windows 8 does not have the ability to have a no-window app open state. This is why closing the last window closes Brave. If we want to eliminate this issue, we need to create a blocking feature. 

One solution is to create a New Tab after the user closes the last non-pinned tab in a given window. If the new tab is the last, then disable the close button.

@bsclifton What do you think of this solution? Safari on Mac does something similar.
