### ISSUE TITLE
Lastpass Issues with 0.17.19

### ISSUE THREAD

**Issue by mistertempy** [brave/browser-laptop#10114]
- Describe the issue you encountered:
Cannot access Lastpass settings, Vault, etc. I can log in and fill forms, but getting through to the Lastpass menus and such isn't working.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7 x64

- Brave Version (revision SHA):
0.17.19

- Steps to reproduce:
    1. Set password manager in Brave to Lastpass
    2. Log in
    3. Click the Lastpass icon near the top right of the browser, attempt to go to Vault or other settings
    
- Actual result:
Nothing happens.

- Expected result:
New page with Vault or other Lastpass setting should open.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/10029
