### ISSUE TITLE
Brave freezes when attempting to delete a download

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#10121]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
After stopping a download and clicking on the delete icon, the browser permamently freezes.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10x64
- Brave Version (revision SHA):
0.17.19
- Steps to reproduce:
    1.Start downloading a file
    2.Stop the download
    3.Click to thrash icon to delete the file
    
- Actual result:
The browser freezes
- Expected result:
The downloaded file should be deleted without freezing the browser
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by kjozwiak** [comment]
@darkgalaxy4 are you still seeing this with newer versions of Brave? Would you be able to provide us with more detailed information?

* is it a particular website?
* is it a particular file type?
* are you saving the file into another destination other than Downloads?

I couldn't reproduce the issue using the following builds:

> Brave: 0.17.9 rev: 2606974546348a8d5d3afd4761a2df8c6e5ee88d 
> Muon: 4.1.4 
> libchromiumcontent: 59.0.3071.109

> Brave: 0.18.29 rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 
> Muon: 4.3.16 
> libchromiumcontent: 60.0.3112.113 

> Brave: 0.18.32 rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 
> Muon: 4.3.18 
> libchromiumcontent: 61.0.3163.71 

**STR being used:**

1. Open Brave and load https://www.thinkbroadband.com/download
2. Start downloading the "Very Large File (1GB)"
3. Once the file starts downloading, stop the download using the "X" button on the download toolbar
4. Once the download has been cancelled, click on the "Trash" button and click "Delete"

**Other STR being used:**

1. Open Brave and load https://www.ubuntu.com/download/desktop/thank-you?country=CA&version=17.04&architecture=amd64
2. Once you start downloading the ISO, stop the download using the "X" button on the download toolbar
3. Once the download has been cancelled, click on the "Trash" button and click "Delete"

**Comment by srirambv** [comment]
I believe this is an issue depending on the size of the downloaded file. The bigger the file size the more evident it becomes of browser freezing. @kjozwiak you can reproduce this if you complete the 1GB file download and then try to delete the file from the download bar browser freezes as it is trying to delete the entire 1GB file via browser process

**Comment by kjozwiak** [comment]
> @kjozwiak you can reproduce this if you complete the 1GB file download and then try to delete the file from the download bar, browser freezes as it is trying to delete the entire 1GB file via browser process.

I tried a few more cases and I still couldn't reproduce the original issue using 0.17.9 rev: 2606974546348a8d5d3afd4761a2df8c6e5ee88d:

* downloaded the 1GB file, waited till it was completed and deleted it via the downloads toolbar
* downloaded a 6.5GB file, waited till it was completed and deleted it via the downloads toolbar
* downloaded a 10GB file, waited till it was completed and deleted it via the downloads toolbar
* started downloading the 1GB file, cancelled it once it reached about 60% completed and deleted the download via the downloads toolbar
* started downloading the 6.5GB file, cancelled it once it reached about 60% completed and deleted the download via the downloads toolbar
* started downloading the 10GB file, cancelled it once it reached about 60% completed and deleted the download via the downloads toolbar

I tried the above cases on a Win 10 x64 desktop machine and a Win 10 x64 VM instance. @srirambv, have you been able to reproduce this behaviour?

**Comment by darkgalaxy4** [comment]
@kjozwiak sorry for the delay, it happens randomly, the size of the download does not seem to matter, however I have moved the destination from Downloads to Desktop
