### ISSUE TITLE
Failed to play Adobe Flash Player content

### ISSUE THREAD

**Issue by TTYu** [brave/browser-laptop#1012]
1. Downloaded Flash Player installer
2. Installed Flash Player as instructed
3. Closed Brave
4. Restarted Brave
5. Navigated to http://www.bbc.co.uk/news/world-us-canada-35730273
6. Message to download Flash Player is still displayed. Reloaded page and problem still persists.

**Comment by diracdeltas** [comment]
Brave doesn't support flash. #386

**Comment by luixxiul** [comment]
This is being worked on with #1093, closing.
