### ISSUE TITLE
LastPass not signing in correctly

### ISSUE THREAD

**Issue by darkgalaxy4** [brave/browser-laptop#10125]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
1. If the browser is set not to save logins, on startup LastPass prompts you to enter your credentials, but when you do so the access is stuck on a spinning circle even though the extension is active.
2. If the access data are not entered on browser startup, LastPass won't let you enter them later and won't sign in.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10x64
- Brave Version (revision SHA):
0.17.19
- Steps to reproduce:
    1.Set LastPass as your password manager
    2. On startup, enter your credentials
    3. Note that the indicator is stuck on a spinning circle, but the extension is red and working
    4. Log out and restart the browser
    5. Don't enter your credentials when prompted
    6. Click the extension icon and try to enter your credentials. Notice that you are not able to write anything in the two fields.

    
- Actual result:
LastPass should close after entering your credentials on startup and should accept them later anyway
- Expected result:
LastPass signin windows is stuck on startup and the extension won't let you enter any data if you decide to login later
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
I have always noticed the issue 1), I can't say if the isssue 2) is a regression or has always been present.
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by jonathansampson** [comment]
I believe this is covered by #10029 and #4687.

**Comment by bsclifton** [comment]
@darkgalaxy4 hang tight- we got a fix in the works 😄
