### ISSUE TITLE
pinned tab will not display

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#10122]
There will be an error 
```An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'includes' of undefined
    at state.get.toList.filter (/Users/darkdh/Projects/browser-laptop/app/browser/windows.js:74:28)
...
```
cause by a site entry
`"https://smile.amazon.com/gp/buy/spc/handlers/display.html?hasWorkingJavascript=1%7C0%7C0":{"favicon":"https://smile.amazon.com/favicon.ico"}`

**Comment by NejcZdovc** [comment]
@darkdh tags will be deprecated in 0.20.x with my split sites PR

**Comment by NejcZdovc** [comment]
So just a heads up if you targeting this for 0.20.x as well

**Comment by darkdh** [comment]
Thanks for the heads up. Changing it to 0.19.x before your PR landed

**Comment by bsclifton** [comment]
This is kind of an anomaly case... @darkdh do you mind writing up some manual QA steps and/or creating a sample session file (and attaching) for QA to use?

**Comment by darkdh** [comment]
Please use attached session file to test. Thanks
[session-store-1.zip](https://github.com/brave/browser-laptop/files/1188527/session-store-1.zip)
