### ISSUE TITLE
Issue: Webservice page from Skype and Hotmail+Skype function consume rather much CPU

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1013]
CPU consumption under Windows 8 here with Brave is right now between 15-26% with 30 tabs open and no other program running, CPU temp hovers around mid 50C.

If i open either Hotmail and the integrated Skype service or go right to the Skype online page, CPU consumption goes up to 30-40%, CPU temp rises towards 65C-70C and does not fall below lower CPU consumption percentages like before i open one of those 2 pages/using that specific Skype service.

Point is, both pages do increase CPU power consumption and increase CPU temp quite a lot, much more as compared to pages like Twitter or the stand alone Google hangout page, with both pages this rise does not appear.

Related: #861

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-webservice-page-from-skype-and-hotmail-skype-function-consume-rather-much-cpu/10065

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
