### ISSUE TITLE
bitwarden menu items not working like expected

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10130]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
after enabling bitwarden, i could not log in or create an account via the URLbar menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.18.10

- Steps to reproduce:
    1. enable bitwarden
    2. attempt to log in or create an account
    
- Actual result:
nothing happens when clicking on the menu items

- Expected result:
i should be able to log in or create an account

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This should be fixed after https://github.com/brave/browser-laptop/commit/38f46189571710189a3702926d8d40b465fc953a
