### ISSUE TITLE
chrome-extension link shown instead of about:safebrowsing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10143]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
chrome-extension link shown instead of about:safebrowsing

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Name | Version
-- | --
Brave | 0.18.12
rev | 2ca400c
Muon | 4.3.6

- Steps to reproduce:
    1. Clean install 0.18.12
    2. Visit downloadme.org
    3. About:safebrowsing page opens but shows as `chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-newtab.html`
    4. Shields shows the correct domain name
    
- Actual result:
chrome-extension link shown instead of about:safebrowsing

- Expected result:
Should properly show the correct domain name after about:safebrowsing

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Disable `Block phising` switch on the page shows about:error (as the page is dead)
    2. Navigating back shows correct url `about:safebrowsing#http://downloadme.org/`
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28611338-5f4ca638-71e3-11e7-8949-573b88e30c49.png)

- Any related issues:
#9441 
cc: @diracdeltas

**Comment by Jacalz** [comment]
Have been seeing this on settings too sometimes on 0.18.x, maby related to the about pages?

**Comment by bsclifton** [comment]
Found the issue... looking at a fix

**Comment by Jacalz** [comment]
Still seeing in 0.18.13 on ia32 :confused:
