### ISSUE TITLE
bitwarden: Site autofill doesn't work

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10140]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
bitwarden: Site autofill doesn't work

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.12
-- | --
rev | 2ca400c
Muon | 4.3.6

- Steps to reproduce:
    1. Clean install 0.18.12
    2. Enable bitwarden and login to your account
    3. Visit a site with saved credentials, right click -> autofill -> credentials nothing happens
    
- Actual result:
Site autofill doesn't work

- Expected result:
Should autofill credentials and login

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by kspearrin** [comment]
See #10202 for more details, but this is happening because of missing APIs on `chrome.contextMenus`

**Comment by jonathansampson** [comment]
Working on this now with @kevinlawler. We've identified the needed fix, and are working towards resolving.

**Comment by jonathansampson** [comment]
The following resolves this issue, but likely isn't ideal. @kevinlawler, can you suggest a better place to make a similar modification?

```diff
diff --git a/js/contextMenus.js b/js/contextMenus.js
index 7095bd4..5555868 100644
--- a/js/contextMenus.js
+++ b/js/contextMenus.js
@@ -1174,6 +1174,9 @@ function mainTemplateInit (nodeProps, frame, tab) {
               label: extensionContextMenu.properties.title,
               click: (item, focusedWindow) => {
                 if (focusedWindow) {
+                  if (extensionContextMenu.properties.parentId) {
+                    info.parentMenuItemId = extensionContextMenu.properties.parentId
+                  }
                   extensionActions.contextMenuClicked(
                     extensionContextMenu.extensionId, frame.get('tabId'), info)
                 }
```

**Comment by kevinlawler** [comment]
Seems fine to me. If there's a better place I don't know where it is.

**Comment by jonathansampson** [comment]
@kevinlawler I'm going to look at adding it here: https://github.com/brave/browser-laptop/blob/fb844bb3f202254b1948f9fa3115faa3bbb86b5f/app/common/state/extensionState.js#L151

**Comment by darkdh** [comment]
@jonathansampson extensionState would be the perfect place to add.

**Comment by jonathansampson** [comment]
@darkdh Working on adding it there. I just issued a PR to first optimize much of extensionState, and assigned it to you for review :)

**Comment by jonathansampson** [comment]
I believe I now have a fix for this, and will be opening a PR momentarily.
