### ISSUE TITLE
Download progress indicator continues after pause

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10148]
- Did you search for similar issues before submitting this one?
Yes, may be a dupe of existing issue

- Describe the issue you encountered:
While verifying #9260, found download progress indicator continues after pause

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.12
-- | --
rev | 2ca400c
Muon | 4.3.6

- Steps to reproduce:
    1. Clean install 0.18.12
    2. Download a file 
    3. Click on the pause button, progress indicator continues a little and then stops
    
- Actual result:
progress indicator continues a little and then stops

- Expected result:
Should stop when pause button clicked

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yet to verify, could be regression 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![downlaod](https://user-images.githubusercontent.com/17010094/28614532-155ad7ce-71ee-11e7-857c-ec3e201881d0.gif)

- Any related issues:
#9260
marking for 0.18.x hotfix as its a low priority. Please change if needed @brave/release-team

**Comment by luixxiul** [comment]
I assume it is because of transition animation

**Comment by NejcZdovc** [comment]
@srirambv is this dupe of #9320?

**Comment by srirambv** [comment]
Yup its a dupe. Exactly same. Closing this as dupe
