### ISSUE TITLE
Bookmarks cannot be moved to Other Bookmarks folder

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10157]
**Describe the issue you encountered:** Bookmarks cannot be moved to `Other Bookmarks` folder.

![bug](https://user-images.githubusercontent.com/3362943/28627091-bf6762ba-725b-11e7-8383-4a761c027f83.gif)

In the gif the bookmark is moved to the last row inside `Bookmarks Toolbar` folder.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.18.12

- Steps to reproduce:
    1. Bookmark a page
    2. Open about:bookmarks
    3. Drag and drop the bookmark to `Other Bookmarks`
    
- Actual result: the bookmark is not moved to the folder

- Expected result: the bookmark should be moved to the folder

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #8024

**Comment by NejcZdovc** [comment]
Yes this is because we only allow 0+ (not -1) for parent folder id. I notice this as well while I was working on my PR as well

**Comment by luixxiul** [comment]
fyi it has been possible to do so when I opened https://github.com/brave/browser-laptop/issues/8024

**Comment by NejcZdovc** [comment]
yeah I think that this was a regression

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/other-bookmarks-folder-does-not-work/4853)

**Comment by LaurenWags** [comment]
Similarly with moving a folder to 'Other Bookmarks' - but only on Linux (I was using Ubuntu). I could not repro this on MacOS.

![ubuntuotherfolder](https://user-images.githubusercontent.com/28145373/28685570-3ed4e110-72d6-11e7-9759-d76282ad85cf.gif)

**Comment by johnstrasser** [comment]
+1
FWIW I am having this problem as well. The "Other Bookmarks" folder might as well not exist.

 
Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64

**Comment by Cavadus** [comment]
+1 on this issue.  Cannot move a single bookmark into "Other Bookmarks."

 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by NejcZdovc** [comment]
@Cavadus this will be fixed in version 0.21.x

**Comment by jamesray1** [comment]
+1. Couldn't today. When I created a folder in Other Bookmarks, I could move bookmarks to that folder.

**Comment by NejcZdovc** [comment]
@jamesray1 this was fixed in 0.20 version, so in the next major release

**Comment by LaurenWags** [comment]
@NejcZdovc should this work when moving a folder to 'Other Bookmarks' (see https://github.com/brave/browser-laptop/issues/10157#issuecomment-318444002)? Because right now the folder you move disappears from Bookmark Manager but stays on the Toolbar:
![10157](https://user-images.githubusercontent.com/28145373/34278550-877c533c-e679-11e7-9fbb-8b34fed22b42.gif)

cc @kjozwiak @srirambv

**Comment by NejcZdovc** [comment]
yes it should work

**Comment by NejcZdovc** [comment]
can you please open new issue for this one, because steps are not the same as a main issue
