### ISSUE TITLE
"View Source" on about pages does not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10156]
**Describe the issue you encountered:** "View Source" on about pages does not work.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.18.12

- Steps to reproduce:
    1. Open about:preferences
    2. Select `View Source` on the context menu
    
- Actual result: the source code is not displayed

- Expected result: either 1) the view-source tab should be displayed or 2) the context menu item `View Source` should be hidden on about pages

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
This option was removed from about pages 😄
