### ISSUE TITLE
Issue with Gmail 2 step verification login ( login using phone prompt)

### ISSUE THREAD

**Issue by raj-ahmed** [brave/browser-laptop#10159]
There is an issue with the brave browser while I am trying to login gmail with 2 step verification on with me having the 2nd step verification as  login using phone prompt

**Comment by luixxiul** [comment]
thanks for reporting. The issue has been reported on #7866. So I'm going to close this issue as a duplicate of #7866. Please subscribe to the issue if you would like to follow the discussion :-)
