### ISSUE TITLE
Facebook popup messages

### ISSUE THREAD

**Issue by thbtm** [brave/browser-laptop#1016]
When I'm going to Facebook a popup with the following message appears : "www.facebook.com is requesting permission to show you notifications".  I click on "Deny". 

Then a second popup appears wit the following message : "Would you like to remember this decision on www.facebook.com until Brave closes?" I click on "Yes"

But, if I close and reopen Brave and go to Facebook again, these messages appears again.

**Comment by bbondy** [comment]
@diracdeltas putting this in 0.8.1, pls take if you can.

**Comment by diracdeltas** [comment]
That's the expected behavior for now. As the prompt says, your decision was remembered until Brave closed. It pops up again when Brave is re-opened.

**Comment by bbondy** [comment]
Sorry I misread originally and didn't realize there was a close.  Closing this issue since it is expected for now.

**Comment by bogas04** [comment]
Can we stop it from asking again and again ?

**Comment by diracdeltas** [comment]
@bogas04 yep that's in 0.9.3
