### ISSUE TITLE
Different channels should have different icons and install paths

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10189]
Currently, we have both `dev` and `beta` channels available. However, they are currently mutually exclusive (you can't install both at the same time).  We need to be able to install multiple channels on a single machine.

Each channel should
- have a different profile folder (for the session)
- have a different icon

cc: @bradleyrichter for the icons 😄 

Related https://github.com/brave/browser-laptop/issues/4120

**Comment by Liunkae** [comment]
Icons: #4120

**Comment by luixxiul** [comment]
I thought it looks the same, but slightly different (the right one has scars on the face) 🦁 

![clipboard01](https://user-images.githubusercontent.com/3362943/32437401-8e5cd9aa-c32a-11e7-96cd-647fb7963395.png)

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/32437648-ee32f986-c2df-11e7-8aa0-ec3ac8bb4e7e.png)
Its quite impossible to distinguish on Windows

**Comment by bsclifton** [comment]
+1 from me; very hard to see on macOS.  I shared the problem with @bradleyrichter yesterday

**Comment by luixxiul** [comment]
We have had an issue for that: https://github.com/brave/browser-laptop/issues/4898
