### ISSUE TITLE
Small Bugs Found in First Couple Hours of Using Brave

### ISSUE THREAD

**Issue by haflg19** [brave/browser-laptop#10184]
- Did you search for similar issues before submitting this one?
  Yes, but this issue contains several mostly related bugs I have noticed, so no issue has all of these, and I didn't find all of these in other issues.

  

Hopefully its allowed to post multiple bugs in the same issue in this repository. I am not sure whether it is or isn't, but these bugs mostly seem related anyways so perhaps it would be one issue. But, if it is not allowed I apologize. Also I apologize for not having the steps to reproduce many of these, but I gave as much detail as I had on some of these bugs when I described them, but all of the bugs I am listing have happened more than once in the first few hours of my first ever time using the Brave browser so it was 100% a fresh install, and clearly at least somewhat reproducible to happen multiple times that fast.

- Describe the issue you encountered:
  Below is a list of the issues that I have seen in my first couple hours using Brave, I think there were a few more than what I have listed here, but I can't remember right now. So I will edit and add any other small bugs that I find if I come across them any time, or remember them. Some of the issues in this list have screen shots at the bottom, if I was able to get one, and it was relevant, as well.

Here is the list, but since I know this is going to be long, here are the numbers in the list below I feel are the most urgent, or cause the biggest problems and need to be looked into as soon as possible: 1, 2, 5, 7, 15, 16

  *also i feel i should say that i know some of the list (especially towards the bottom) involves some of my "person opinion" but for these ones where i do give my opinion on something, i know of people who agree with me, or use these features or whatever, and i know there are more people outside these handful that i know agree with me on some of these bugs/suggestions... so its not really just my personal opinion, but rather something that i know many other people agree with as well*

  1. #10183 (created by me just before this one, which details a larger bug involving tab drag & drops)
    2. occasionally attempting, to reopen tabs, causes similar issues to #10183 (i have not tested with right clicking tab bar and choosing the button to reopen tab)
    3. preview on tabs sometimes displays only gray screen (in #10183, but has other causes as well)
    4. occasionally when typing in text boxes (like the ones used to write issues like this) I have been unable to drag around the bottom corner to change the box size (this mainly happens when I am clicked in the text box, but has been times where I could move it and couldn't move it either way)
    5. sometimes the browser will not display a cursor when in any text box (including the browser's own search bar at the top) and when highlighting text, it does not highlight blue like normal, instead it highlights in gray
        * you are still able to type when this happens but it makes it much harder to see what you are doing
        * sometimes this issue is only within a single tab, and sometimes it seems to effect the entire window (all of the tabs)
        * this only fixes upon closing the page or window from what I have seen, reloading the page, or tabbing out and back in does not seem to fix this ever
        * also, any textarea that you click on, where it normally highlights the outline of the textarea in a light blue color, this no longer shows at all (which ultimately makes it so you have no clue where your cursor is on the page when typing, or if you are even inside the textarea at all)
        * i also remember at least one time where copy/paste wasnt working correctly but I have no clue if it was during this bug or unrelated
        * NOTE: while typing this issue and trying to screenshot all these bugs that I could display with a  screenshot, this specific bug happened for whatever reason, so i just clicked in the textarea for the issue and made sure I was actually in the area and could type and everything, then I pushed my key to launch LightShot to screenshot it, which I did, but right after I screenshotted it and came back the text area problem was not occurring anymore... i belive that all of the times i have encountered this bug it started right after i was inside a textarea and then instead of just clicking away or something like normal, I used some shortcut or something similar to do something that unfocused my browser on the textarea instantly, then this time when LightShot was activated, it obviously was a keyboard button I pushed to launch which unfocused the textarea and ended up solving the bug for that occurrence, so it seems focusing out of a textarea without clicking away first has something to do with this bug activating and deactivating 🤔 
    6. the browser always opens windows in a non-maximized view which is always basically maximized size however it is offset for some reason
    7. not sure if this is a bug or done on purpose, but I think everyone would agree that Brave should not have 'Windowed History' per say, meaning that when you close a tab in a window I think most people would agree that choosing 'Reopen Last Closed Tab' in another window, should just reopen that tab that was just closed
        * the reason i find this to be such a problem is that if you accidentally close a window with multiple tabs on it and then in another window try to reopen them you are not able to, you would have to go into History and find all of them
        * this also is what I believe leads to the issue of closing multiple windows to exit the browser not remembering everything, for example with two windows open you use 'CTRL+SHIFT+W' to close them, then later when you come back you open Brave and it will only open one of the windows and you effectively lose all the things open in the other window when you closed it
        * I and I know many other people use this feature in other browsers so PLEASE PLEASE PLEASE fix this, and if this is how it is meant to be and not a bug , please change this or add an option to make tabs not follow a 'Windowed History'
        * #10002 seems related but i haven't read this issue, but its title describes this exact problem
    8. there have been a few times where other issues in #10183 came about from other reasons (such as not being able to use the X at the top right to close a window, or tab previews not working, or not being able to mute tabs properly, etc...) but I have no clue on the causes or anything, just that they happened to me a couple times each
    9. i have only tested this on here (github issues) but when typing if you highlight and drag text and then drop it a couple things happen that may or may not be on purpose
        * the text is copied not moved, so when you drop the text somewhere else in the same textarea you will have two lines of the same text, which I personally like, however other browsers do not do this (i dont think) so this may be a bug
        * also, after doing this, if you attempt to 'CTRL+Z' it does not recognize this and undo whatever you typed or did before dragging the text around, and the text you dropped would still be there
    10. using 'CTRL+H' does not seem to do anything, however using 'CTRL+Y' opens History
        * this annoys me because when typing if I undo something with 'CTRL+Z' and then decide I should not undo it, so I start 'CTRL-Y'-ing, when I get caught up to the front and nothing more is left to un-undo the browser automatically opens History, which I would not want in this case, plus it tabs me out of whatever I was working on, especially when it seems 'CTRL+H', which every other browser uses, does not seem to do anything (it is my belief that any keybind that basic should be kept in accordance across all browsers and software)
        * this is partly just personal opinion, but I felt I had to explain why it didn't make sense to me, if this isn't a bug and was done on purpose
    11. this is most likely not a bug and is done on purpose, but when you click the Brave icon in the top right corner of the window and toggle Shields it reloads the page, but I have just noticed that there have been a couple times where I wish it would not have reloaded the page, and instead just turned it off for that page in the future
    12. I also think the tab bar should be slightly taller, i think it is a little harder to use the tab bar when it is so thin, plus it would look better in my opinion
    13. the time that you have to hover over a tab to display the preview is too short, i think
        * sometimes when i go up to the tab bar to close one or just go to the tab bar with my mouse on the right side and have to slide over to a tab on the left or something like that, the preview will come up which annoys me
        * i think the time it takes for the preview to come up should be increased, or better yet, make it so when the mouse stops moving on a tab *then* the preview comes up
    14. im not sure if this is a bug or not but when you hover on the maximize/minimize buttons at the top right they do not change at all to indicate you are actually hovering over them, but the X does
        * they should definitely get a small tint to their background when you are hovering on them, because right now whenever I hover on them, the thought that pops into my head is that the buttons are not working, the browser is lagging, etc...
    15. I also really do not like the fact that you cannot use the function key 'F3' to Find in Page, it isn't that big of a deal to initially bring it up, I can use 'CTRL+F', thats fine but I cannot get over having to use Enter to go the next found text, instead of using F3 to cycle the selections
        * this is especially important when you type in the find something and then click somewhere on the page or even in the Find bar, then the only way I have seen to go back to being able to cycle the search for things is to go back and click in the text box and then use Enter again, which is very inefficient
        * again, this is kinda personal annoyance, but it also is another thing that Brave breaks from traditional browsers for no obvious reason (much like the CTRL+H not bringing up History)
    16. another thing I noticed which is important is that when I first started Brave is that i was not able to sign into my Google account while Shields was up for whatever reason, which is a **BIG PROBLEM**
        * and went to sign into Google i typed in my email and then it showed the prompt saying a number which it displayed an option for on my phone and i had to choose the correct number on my phone and then it would allow me to continue... i have this turned on and it works fine in other browsers however, the instant the prompt shows on Brave (saying to select the correct number on my phone), another prompt also came up which said something along the lines of it didn't work and I had to try again, or I ran out of time and needed to try again or something like this, which I would then click Try Again, and the exact same thing would happen... even if I went on my phone and selected the right number and my phone said that I was right and could continue on my PC, Brave would not let me, until I luckily tried turning off the Brave Shields, and then the problems went away and I was allowed into my account. but basically with this bug and shields turned on, **you are not able to log into your google account with 2FA turned on**
    17. when users click the scroll wheel to then allow scrolling by moving the mouse, it acts like you clicked the mouse and starts highlighting everything, which i dont think was intentional, but i definitely dont think people want this if you did put it in on purpose
    18. one last thing to note, is that following with the inconsistencies that i have mentioned between Brave and other browsers, i think Brave should try to standardize its shortcuts such as the ones I have noticed so far: CTRL+H does not seem to open History, F3 does not cycle finding in a search, CTRL+B does not seem to bring up bookmarks list, CTRL+E does not focuses the search bar, CTRL+Q instantly quits the browser (with no warning?), CTRL+SHIFT+O opens bookmark manager for some reason?, CTRL+SHIFT+N does not open incognito window (although im not sure if there is one, if there is only incognito tabs, then id say this should open a new window with an incognito tab)... im sure you get the point so ill stop there but i think all of Brave's users would issue a giant thanks if you standardize more of the functions on the browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10

- Brave Version (revision SHA):
  Brave -> 0.18.14
  Rev -> ad92d02
  Muon -> 4.3.6

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
  Yes, I found these bugs after just starting to use Brave, so it was pretty much 100% fresh install besides a few small settings I tweaked (which were unrelated to any of the bugs).

- Is this an issue in the currently released version?
  Yes

- Can this issue be consistently reproduced?
  Some of them can be. I do not know the exact cause for most of these, but I know that some of them have been caused multiple times by me doing a similar action as the previous time. I just don't know the exact way to reproduce most of them, but I am confident that they are probably all reproducible (I know some of them are).

![offset_window_brave_bug](https://user-images.githubusercontent.com/25330146/28705264-05cbe370-733d-11e7-9c0e-661cee707519.png)

  This screenshot (above) shows what a Brave window looks like when I first open it. You can see in the top right, it is not maximized and it is slightly shifted to the right for some reason. This happens irrelevant of my previous session's windows, or how many windows are opened at that time, or seemingly anything else.

![invis_cursor_brave_bug](https://user-images.githubusercontent.com/25330146/28705268-09f5a21a-733d-11e7-8504-0d5d371402da.png)

  In this screenshot, I am in a textarea (yes, my cursor is in side the textarea... when i push a key on my keyboard it types correctly but still without a cursor) and my cursor is invisible. Also the blue outline is not showing around the textarea I am in, so there is no indication that I am focused inside the text area currently. And even worse, no indication of where in the textbox I am typing. Also when this bug happens if I highlight text, clicking and dragging mouse over the text or something like CTRL+A then the highlighting on the text is a lightish gray color not blue. This is solved by closing the tab (or window when it occasionally happens for the entire window).
  
  Sorry if this seems harsh or excessive or is irrelevant or anything else, I really like Brave but I don't think I could make the full switch to it from Firefox and Chrome, or use it as one of my main ones (right now i switch between those two) until some of these are addressed. Also hopefully its not too opinionated, like I said I only gave my opinion if I felt like there was MANY other people who would agree with me on whatever it was, so its not really just my opinion. Thanks if you read all that (although I understand if not haha).

- Any related issues:
  #10183 
    * I made this issue right before this with a bug that is likely related to some of the smaller ones mentioned here. This one is separate because I know the way in which that issue is reproduced, and what causes it to some extent. The ones here are just things I have noticed, but may not know the cause for.

**Comment by jamesray1** [comment]
Related to 5: the flashing | symbol to indicate where the active typing position is has often not showed for me. The cursor still shows all the time. For instance, just now when using Google sheets, I click on a cell, in a formula bar if I click inside it doesn't show the flashing | symbol. Then when I come back to this window and click in this comment box (as I type) the flashing | symbol doesn't show. When I tried to delete a sentence by highlighting a sentence and pressing backspace or delete, the cell value deletes.  Also, if I just click in the formula, and press backspace or delete, the cell value deletes.

**Comment by jamesray1** [comment]
I disagree with 7. The last tab closed in memory should be for each window, not for the whole browser application (all windows). If you want to move a tab to a new window, just drag it to the new window.
14. This doesn't occur for me. They brighten when hovering over each button.
I think it is better to open a separate issue for each logically independent issue. For similar issues, you can always cross reference.
15. I didn't even know you could do that in other browsers. I just use CTRL+F. Thanks for the tip and picking that up.
16. If any issues occur where a page doesn't load properly, try to enable all cookies just for that site by clicking in the shield icon (if you have third parties cookies disabled by default).

I have also experienced that tabs sometimes don't move as expected, but have been unable to discover how to consistently reproduce this. Reopening tabs doesn't cause the issue.

I suggest that you use the latest version 0.19.x rather than the latest stable release.

**Comment by jamesray1** [comment]
Actually I checked my version and I was using the latest stable release. I've upraded to 0.19.16 (beta) now, and the flashing icon is showing.
