### ISSUE TITLE
Not blocking the ad in Gmail.

### ISSUE THREAD

**Issue by vikram-raj** [brave/browser-laptop#10185]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered: It blocks the ad for other website and brave not blocking the for Gmail.

- Platform (Win7, 8, 10? macOS? Linux distro?): Fedora 26

- Brave Version (revision SHA): 0.18.14

- Steps to reproduce:
    1. Open Gmail in the brave browser.
    2. Go to the social tab.
    3. You will see the ad in the first row.
    
- Actual result: Showing ad in Gmail.

- Expected result: Should block the ad for Gmail as well.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screenshot from 2017-07-28 14-22-26](https://user-images.githubusercontent.com/2561818/28710071-4cacbe28-73a0-11e7-84f6-4499008ef7c6.png)

- Any related issues:

**Comment by luixxiul** [comment]
Thanks for the report. That issue is tracked here: https://github.com/brave/browser-laptop/issues/344
