### ISSUE TITLE
Linux rpm is not signed

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10188]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Users in the field cannot install the latest rpm due to it being unsigned.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux

- Brave Version (revision SHA):
0.18.14

- Steps to reproduce:
    1. Use a linux system like Fedora
    2. Attempt to install from apt repo
    
- Actual result:
Brave doesn't install

- Expected result:
Brave should install

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Presumably

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by evq** [comment]
This particular rpm has been re-uploaded correctly, and a PR is out to prevent it from happening again :)
