### ISSUE TITLE
Browser (Almost Completely) Stops Working in After Dragging Tab Around

### ISSUE THREAD

**Issue by haflg19** [brave/browser-laptop#10183]
- Did you search for similar issues before submitting this one?
  Yes, nothing was found.

- Describe the issue you encountered:
  In short, when you drag tabs around (within the same window, or from one window to another) many errors arise.

  The following is a (long) list of all the errors and issues that I came across as a result of this bug, some only showed up in some cases (*see Note in 'Steps to Reproduce' section*) and some issues recurred every single time no matter what case was tested. I have not done enough testing to see which case causes which exact errors only enough to find which case(s) can actually cause these errors (**all of these were tested with mouse, shortcuts, and menus; where applicable**):
    1. Not able to
        * Open/Close tab(s)
        * Open/Close window(s)
        * Switch tabs (switching to and from offline tabs seemed to work occasionally)
        * Interact with icons next to the minimize button (*ie.* Brave and LastPass buttons)
        * Refresh page
        * Go Back/Forward
        * Mute tab(s) (could click or toggle the speaker icon for muting, but it did not actually function)
    2. Hovering over tabs sometimes only displays gray screen (#10155 ?)
    3. Clicking tab does nothing
    4. Clicking tab and then moving mouse off of the tab, occasionally took longer to stop displaying the preview than it normally does in a non-broken window (up to ~0.5 seconds for broken tabs)
    5. Dragging tabs around occasionally did not function (sometimes able to, sometimes could drag but not drop, sometimes could not even drag tab around)
    6. Closing all tabs which are working after invoking this bug causes the window to only display a white background, as though nothing is on the page and the window does not even recognize the tab is still there, though, the dashboard is not displayed
</br>

- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10

- Brave Version (revision SHA):
  Brave -> 0.18.14
  Rev -> ad92d02
  Muon -> 4.3.6

- Steps to reproduce:
    1. Open Brave (clean install v0.18.14)
    2. Open multiple tabs
    3. Drag & Drop tab(s) from Brave window anywhere outside the tab bar, so a new window is opened
    4. Drag & Drop tab(s) back into the original Brave window (using one of the cases from the Note below)
    5. Brave window which tab was dropped into in previous step now has **almost no functionality**.
 .

  Note: *each of the following produces slightly different errors/problems, however all of them **consistently** produced errors when tested by me*
    1. Drag & Drop tab with YouTube video playing from one window to another
    2. Drag & Drop tab with YouTube video playing from one window to another however, when dropping the tab,  this time, drop the tab all the way to the left of the other tabs so it ends up being in the first tab spot
        * This method is what I originally did to discover the bug (unknowingly of course), and **this method seemingly produces the most errors**, although I am not sure why dropping into the first position would cause more errors than any other position
    3. Repeating method 1 with any other kind of tab (non-YouTube/non-Video)
    4. Repeating method 2 with any other kind of tab (non-YouTube/non-Video)

.
- Actual result:
  Tab is moved to desired window, and stops functioning. Window also stops responding to most commands.

- Expected result:
  Tab is moved to desired window and continues functioning.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
  Yes, I found and tested this issue after only using Brave for around an hour. Nothing was installed or changed about the browser from a clean install, except a few settings but the settings that I changed would not have caused anything like this I do not believe.

- Is this an issue in the currently released version?
  Yes

- Can this issue be consistently reproduced?
  Yes, in my limited testing the drag & drop functionality of tabs always caused some sort of issue, however, certain ways of moving the tabs around and what kind of tab you are actually trying to move changes the issues that actually occur.

- Any related issues:
  #10155 
    * Hovering on a tab after invoking these issues causes only a gray screen to display in the preview, which was described from a different cause here.
</br>.

  #10184 
    * I will be making another issue after this one describing a couple other bugs I found, which seem to be related to this, however they are not caused by the same methodology so I will not overload this issue with what could be multiple issues. 
</br>

- Notes:
  I apologize if any, or a lot, of this seemed scrambled or confusing or irrelevant, I know I have this tendency. I would be willing to clarify any questions if this is the case, or rewrite the issue if need be, but basically, just: **moving tabs around by dragging and dropping causes basic functions of the browser to stop working**.

  Also, if any actually was really confusing I may have been confusing this issue with something in #10184. See related issues above for more info, but some of these issues are closely related to this issue and I couldn't tell if it was caused by the same thing or not so I was likely confusing myself.

*the random '.' in some places are just there because the formatting was being stupid and wouldn't let me put lines in*

**Comment by rebron** [comment]
Closing. wontfix here. Looks fixed in brave-core though.
