### ISSUE TITLE
emailto <a> links should not invoke new tab

### ISSUE THREAD

**Issue by nullinfinite** [brave/browser-laptop#1018]
OS X 10.10.5.  If I click on an email link, the OS X built-in mail app opens...and the tab title in Brave browser changes to the email address, even after closing external email app.

**Comment by bradleyrichter** [comment]
@bbondy I think the problem is that we are creating a new tab because a link is clicked. We need to add a filter to cancel the new tab action while we pass it to the default mail program for "mail:to" links.

**Comment by bradleyrichter** [comment]
![image](https://cloud.githubusercontent.com/assets/13509546/14613330/bd1b7d12-0550-11e6-84e8-69a6b73eeb74.png)

**Comment by bbondy** [comment]
same for downloaded files btw where we update the nav to url when instead we should do a different action

**Comment by diracdeltas** [comment]
@bradleyrichter it doesn't seem to always open a new tab. ex: the support@brave.com link on https://brave.com
