### ISSUE TITLE
appStore calls `diff` on the state without first checking to see if there are changes

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#10195]
`diff` is a relatively expensive operation on the state and we should short-circuit emitChanges if `lastEmittedState === appState`

**Comment by NejcZdovc** [comment]
@bbondy I putted this into 0.21, but please move it into earlier branches if needed.

**Comment by luixxiul** [comment]
added release-notes/include since every improvement of perf is worth mentioning on the release note
