### ISSUE TITLE
Popup alert buttons need padding

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10198]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Popup alert buttons need padding

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.1
-- | --
rev | 2ee7a49
Muon | 4.4.4

- Steps to reproduce:
    1. Update to 0.19.1 Preview build
    2. Visit any page with forms on it and try to close the tab
    3. Ensure the warning message is shown, <kbd>Cancel</kbd><kbd>Ok</kbd> don't have spacing between them
    
- Actual result:
See screenshot

- Expected result:
Should have proper spacing between buttons

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![buttons](https://user-images.githubusercontent.com/17010094/28746470-f4e2ecfe-7484-11e7-86c4-cb613ac5b1fc.PNG)

- Any related issues:
cc: @luixxiul

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/9973

**Comment by luixxiul** [comment]
it has been fixed with https://github.com/brave/browser-laptop/issues/9973
