### ISSUE TITLE
Brave 0.18.14 doesnt work/cant start.

### ISSUE THREAD

**Issue by Kaysod** [brave/browser-laptop#10191]
Hi, Brave dont work anymore since today. I use it for few months without problems.
the newest version 0.18.14 can not start. i click on it and nothing happend, even taskmanager show nothing.
after 1 hour i go to AppData\Local\brave and start the old version 0.17.19. This version works fine.
Is this a bug for all users or just by me something destroyed?

-Windows 10 x64, AMD Phenom x2 555, HD750

Thanks i love Brave, best Browser ever. sry for my bad english.

**Comment by alexwykoff** [comment]
Could you try temporarily renaming AppData/Roaming/brave and launching 0.18.14 again?

**Comment by bsclifton** [comment]
Closing issue as there hasn't been a response

@Kaysod if you can try the steps that @alexwykoff provided, please feel free to report back and reopen.  Thanks 😄
