### ISSUE TITLE
Upgrade to 0.8.0 fails on Mac OS 

### ISSUE THREAD

**Issue by brad2014** [brave/browser-laptop#1019]
Running, Brave 0.7.14 (installed from Brave.dmg) on Mac OS 10.11.3 (El Capitan).

From Brave->Check for Updates, the update to 0.8.0 is getting downloaded, but when I hit install, the browser dies, and the /var/log/system.log has:

```
/private/var/log/system.log:Mar  6 03:48:41 XXXXX ShipIt[51453]: Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7faf39e03b70 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Application Support/com.electron.brave.ShipIt/ShipItState.plist, NSUnderlyingError=0x7faf39e03910 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
/private/var/log/system.log:Mar  6 03:48:41 XXXXX ShipIt[51453]: ShipIt quitting
/private/var/log/system.log:Mar  6 03:48:41 XXXXX com.apple.xpc.launchd[1] (com.electron.brave.ShipIt[51453]): Service exited with abnormal code: 1
```

I notice that the file ShipIt.plist was actually placed in:
```/Users/me/Library/Application Support/com.electron.brave.ShipIt/ShipItState.plist```
rather than in the file referenced in the system.log error message:
```/var/root/Library/Application Support/com.electron.brave.ShipIt/ShipItState.plist```.

**Comment by enjikaka** [comment]
Same here. I am stuck on 0.7.7.

**Comment by weems** [comment]
My user is the owner of the file referenced by @brad2014 

`$ ls -lat /Users/weems/Library/Application\ Support/com.electron.brave.ShipIt/ShipItState.plist
-rw-r--r--  1 weems  staff  280 Mar 24 08:05 /Users/weems/Library/Application Support/com.electron.brave.ShipIt/ShipItState.plist`

**Comment by luixxiul** [comment]
This should be fixed for now, closing. If not let me know and I will reopen this one.
