### ISSUE TITLE
Mac OS install creates files in user directory owned by root

### ISSUE THREAD

**Issue by brad2014** [brave/browser-laptop#1020]
When I open the installation download "Brave.dmg" and drag Brave to the Application folder to install, 
files are created in my home directory that are owned by root (this is upon install, not on first run):
```
$ sudo find . ! -user me -ls
2367388        0 drwxr--r--    4 root             staff                 136 Mar  6 04:53 ./Library/Application Support/com.electron.brave.ShipIt
2367391      344 -rw-r--r--    1 root             staff              173340 Mar  6 05:02 ./Library/Application Support/com.electron.brave.ShipIt/ShipIt_stderr.log
2367389        0 -rw-r--r--    1 root             staff                   0 Mar  6 04:53 ./Library/Application Support/com.electron.brave.ShipIt/ShipIt_stdout.log
```

Expected: only files owned by me should appear in my home directory.
Also, permissions 744 are weird - shouldn't they be 755?

Note: This may be related to #1019. Should these have gone into /var/root/Library instead?
Note: ShipIt is in the Squirrel framework

**Comment by luixxiul** [comment]
@bbondy is it reproducible?

**Comment by diracdeltas** [comment]
those files exist in my home dir and are owned by me, not root

**Comment by brad2014** [comment]
After wiping and rebuilding machine and reinstalling Brave, I couldn't reproduce this. Closing.
