### ISSUE TITLE
bitwarden issues while testing

### ISSUE THREAD

**Issue by kspearrin** [brave/browser-laptop#10202]
At the request of @jonathansampson , here are a list of known issues while testing bitwarden v1.14.2 with Brave 0.18.14. This list is a WIP and will be amended as issues are found.

#9437

--------

Macbook
==============

```
Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.6.0 
OS Architecture: x64
```

**1. Cannot expand vault to full screen** - Low priority

1. Navigate to My Vault tab
2. Click arrow at the top to open the extension in a browser tab
3. New tab opens and just shows loading forever

**2. Default browser_action keyboard shortcut does not work** - Low priority

1. Press `command + shift + y` to open bitwarden.
2. Nothing happens.

Popup should open with hotkey as defined in https://developer.chrome.com/extensions/commands

See bitwarden implementation here: https://github.com/bitwarden/browser/blob/master/src/manifest.json#L74

Chrome docs state:

> Also note that on Mac 'Ctrl' is automatically converted to 'Command'. If you want 'Ctrl' instead, please specify 'MacCtrl'.

**3. Vault locks while popup is still open** - High Priotity

1. Navigate to Setting tab and enable "Lock Options" to "Immediately"
2. Close popup, open popup and enter password to unlock it
3. While the popup is still open the extension will lock again, causes it to purge the encryption key from memory (the point of it being locked) and therefore stop functioning with anything to do with crypto. Try to view a new login and you will see it is broken.

Locking is not suppose to occur while the popup is open. This is prevented by checking for the popup to be open with `chrome.extension.getViews({ type: 'popup' })`. See here: https://github.com/bitwarden/browser/blob/master/src/services/lockService.js#L25

I'm guessing that this API is not implemented on Brave.

**4. Dev tools content scripts doesn't show i18n extension name** - Priority low

![screen shot 2017-07-30 at 9 17 26 pm](https://user-images.githubusercontent.com/1190944/28759543-c0c153b4-756c-11e7-9feb-8a4857042198.png)

Dev tools is showing the i18n variable name instead of the `messages.json` value.

I know there was an issue in the extension listing page a while back that was related to this. Saw it while debugging so thought I would report it.

**5. Notification bar doesn't work due to CSP violation from content script injection** - Priority medium/high

bitwarden shows a notification bar to assist with adding new sites to your vault whenever you log in manually and the extension detects the credentials don't already exist in your vault. This is failing due to a CSP violation when the content script tries to inject an iframe into the host page.

1. Be logged into bitwarden.
2. Go to GitHub login page
3. Enter some bogus credentials that do not exist in your vault (anything will work, doesn't have to succeed). Post the form.
4. CSP violation on host page occurs and notification bar does not show (see Chrome for how it is suppose to work).

![screen shot 2017-07-30 at 9 30 31 pm](https://user-images.githubusercontent.com/1190944/28759703-57ce1368-756e-11e7-9b13-1da1f77b12c1.png)

bitwarden source: https://github.com/bitwarden/browser/blob/master/src/content/notificationBar.js#L185

**6. Wrong logo size makes the icon look blurry and low res** - Priority low

This is bitwarden i Brave compared to chrome:
![image](https://user-images.githubusercontent.com/25466657/37861515-be98a02c-2f3b-11e8-8f95-88f11224df9a.png)

Brave are using "Icon19":
![icon19_locked](https://user-images.githubusercontent.com/25466657/34950838-98a8cde4-fa14-11e7-83f2-19694b3e9a0c.png)
![icon19](https://user-images.githubusercontent.com/25466657/34950842-9b8d5d90-fa14-11e7-8cb1-50b77fc52517.png)
While chrome are using "Icon38":
![icon38_locked](https://user-images.githubusercontent.com/25466657/34950887-bfec0dd0-fa14-11e7-80bc-121c7debbd6e.png)
![icon38](https://user-images.githubusercontent.com/25466657/34950896-c3e87f04-fa14-11e7-9f0d-28d5582fbf9f.png)

**Comment by kspearrin** [comment]
Updated with a few more testing on my windows laptop. One critical issue discovered with autofill.

**Comment by jonathansampson** [comment]
@kspearrin Thank you! We'll take a look asap.

**Comment by kspearrin** [comment]
@jonathansampson Added 2 new issues for macbook, see 4 and 5 above. 5 is a high priority.

**Comment by jonathansampson** [comment]
@kspearrin Working on resolving #10140 right now.

**Comment by luixxiul** [comment]
@kspearrin would you mind checking a report from an user here? https://community.brave.com/t/bitwarden-extension/5403?u=suguru thanks!

**Comment by bsclifton** [comment]
@luixxiul we did not intentionally release bitwarden and we have known issues

@kspearrin I responded to the user and let them know that we're working to fix the issues on our (Brave) side 😄

**Comment by jonathansampson** [comment]
@kspearrin I wasn't able to reproduce _Vault locks while popup is still open_. Could you record a small GIF or video showing the precise steps to follow?

**Comment by kspearrin** [comment]
@jonathansampson See https://www.youtube.com/watch?v=gYoup_W86Xc&feature=youtu.be

**Comment by kspearrin** [comment]
Any idea if 3 and 5 will make it into the v0.19 release? Those are really the only 2 big ones that I can find while using the beta.

**Comment by kspearrin** [comment]
Testing brave v0.19 now with bitwarden. Issues 1, 2, 3, 4, and 5 from above are still happening.

**Comment by Jacalz** [comment]
The extension has now been updated to latest (1.25.3) in Brave thanks to me and @jonathansampson doing some testing. So it is finally updated but lets see what issues are still present...

**Comment by Jacalz** [comment]
All issues 1, 2, 3, 4 and 5 are still reproducible when using brave 0.21.24 and bitwarden 1.25.3!
I added one more issue to to the issue at top that I found while testing 🙂

**Comment by bsclifton** [comment]
We haven't updated our extension support in Muon for a while- but we will get proper extension support when we move over to [brave-core](https://github.com/brave/brave-browser). @kspearrin thanks for all the work you did with us in the past as we did try to add those missing APIs
