### ISSUE TITLE
Disable Ctrl+MouseWheel zooming

### ISSUE THREAD

**Issue by broros** [brave/browser-laptop#10201]
Disable "Ctrl+MouseWheel" to prevent unwanted zooming

- Platform macOS

- Brave Version 0.18.14

**Comment by luixxiul** [comment]
Are there browsers out there that support the function? I'm not sure.

**Comment by haflg19** [comment]
@luixxiul I don't know about Browsers, but I know that Atom (the text editor) supports this functions, and I know I just recently, as in the last few days installed something that supports this function, but I cannot for the life of me remember what that software is.

I mainly made this response to request that, when zoom scrolling, the user should probably recieve some indication of what percentage zoom they are at (*ie. 70%, 90%, 110%, 200%, etc...*), like every other browser displays.

**Comment by luixxiul** [comment]
> the user should probably recieve some indication of what percentage zoom they are at (ie. 70%, 90%, 110%, 200%, etc...), like every other browser displays.

+1. I'm opening a new issue to track the suggestion.

**Comment by Liunkae** [comment]
Firefox allows this with the "advanced" settings in about:config (`mousewheel.with_meta.action`). IMO, this setting should definitely be added if Brave gets about:config (#545).

**Comment by broros** [comment]
the browser zooms uncontrollably when holding down control and right click. I understand that you can zoom by holding down control and moving your finger up and down the mouse.

**Comment by cezarlz** [comment]
Any progress here? This is very boring, I switch between tabs pressing ctrl + tab or ctrl + shift + tab and there is a delay when you switch between tabs. When I switch I start scrolling and the page zoom in and out wildly. 

Related: https://github.com/brave/browser-laptop/issues/1280

**Comment by bsclifton** [comment]
+1 from @broros via https://github.com/brave/browser-laptop/issues/14172

**Comment by bsclifton** [comment]
Confirmed this is fixed with our [developer channel release](https://brave.com/download-dev) (brave-core)
