### ISSUE TITLE
Clipboard copies URL instead of text selected on webpage

### ISSUE THREAD

**Issue by HP4k1h5** [brave/browser-laptop#10214]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
copy and paste non-functioning, seems "stuck" on URL or other page feature

- Platform (macOS sierra 10.12.5):

- Brave Version (0.8.14):

- Steps to reproduce:
    1. Visit a site which has text you can select (ex: https://brave.com)
    2. Click into the URL bar. Ensure all text is selected (Ctrl + A or Cmd + A)
    3. Highlight text on the web page
    4. Copy selection using Ctrl + C / Cmd + C
    5. Paste into a text editor like Notepad or Sublime

- Actual result:
pastes either page URL(which i never even copied!) or some other feature from the page (that i never copied), not the selected text.
    
- Expected result:
selected and copied text will paste 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
not sure
- Can this issue be consistently reproduced?
yes this is at least the second time i encounter this bug. i think a brave restart will mitigate this but it seems to be persistent 
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@HP4k1h5 thanks for the report! 😄  I have seen this (or something like it) too (and I know others have- cc: @bbondy, @jonathansampson)

**Comment by thbtmntgn** [comment]
Same problem for me on macOS Sierra 10.12.6 and Brave 0.8.14 !

**Comment by NejcZdovc** [comment]
STR:
*not working*
1) focus url bar (make sure that url is selected)
2) copy something from the webview

*working*
1) focus url bar
2) place cursor at the end of the url bar
3) copy something from the webview

**Comment by bsclifton** [comment]
This works great in 0.17.19 but happens in all versions of 0.18.x (I went as far back as 0.18.1). Needs more investigation

**Comment by bsclifton** [comment]
I went back through old versions of 0.18.x and found the commit in which this breaks:
https://github.com/brave/browser-laptop/commit/6cf20980584a1b3bbf508fca43ba637667311aba

If you grab this commit and then run the following:
```
rm -rf node_modules && npm install
CHANNEL=dev npm run build-package
CHANNEL=dev npm run build-installer
```

You can install that version of Brave and the bug is present.  If you [check out the prior commit](https://github.com/brave/browser-laptop/commit/61d52ec2408cde5830fe0b3874fc00344115dfb8) and follow those same steps, it works.

**Comment by bsclifton** [comment]
I used the above commit (https://github.com/brave/browser-laptop/commit/6cf20980584a1b3bbf508fca43ba637667311aba) and tried an earlier version of Muon (4.3.0 is the first which uses Chromium 60).  This also fails

**Comment by darkdh** [comment]
We need to revert this
https://github.com/brave/browser-laptop/commit/43e5541e8033b9405b8ea62b72710855d489ae89
