### ISSUE TITLE
TVGuide.com displaying ads

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10217]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
tvguide.com is displaying ads when Block Ads is enabled.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Reported on MacOS

- Brave Version (revision SHA):
Brave | 0.18.14
rev | ad92d02
Muon | 4.3.6

- Steps to reproduce:
    1. Verify Block Ads is enabled by default.
    2. Navigate to http://www.tvguide.com/listings
    3. Ads are displayed.
    
- Actual result:
Ads are displayed.

- Expected result:
Ads should not be displayed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screen shot 2017-07-31 at 5 34 53 pm](https://user-images.githubusercontent.com/28145373/28799536-0171ff8a-7617-11e7-9a44-f8a8291f5248.png)

- Any related issues:

cc: @lukemulks

**Comment by eljuno** [comment]
It's blocked on my laptop.
Win 8.1 x64
Brave 0.18.14 (ad92d02)
Muon 4.3.6
![brave-tvlistings](https://user-images.githubusercontent.com/25360853/28800279-2e0d8c26-7676-11e7-85d6-1ab3447642c2.png)

**Comment by lukemulks** [comment]
Hi @LaurenWags!

I took a look, and similar to @eljuno - I am not seeing the ads. 

However, the page refreshes at least 2x when I have dev tools open. My block counts are also different than what you'd captured on macOS. I suspect that the CBS/TVGuide ad configuration is able to detect WindowsOS and has a different loading strategy that includes a refresh. 

Browser Profile: 
```
Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64
```

I think I see what's up, but am going to run a couple of tests. 

Can you do me a favor, and copy-paste the URLs that are blocked with shields enabled in macOS when you get a moment? @LaurenWags
