### ISSUE TITLE
MacOS 10.10.5: npm run build-package fails

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#1022]
I ran into a problem which seems to appear since the pull on March 4th. When running npm run build-package the following error occurs:

```
> brave@0.8.0 build-package /Users/rodger/Projects/browser-laptop
> node ./tools/buildPackage.js

/Users/rodger/Projects/browser-laptop/tools/buildPackage.js:31
  throw new Error('CHANNEL environment variable must be set to dev, beta or stable')
  ^

Error: CHANNEL environment variable must be set to dev, beta or stable
    at Object.<anonymous> (/Users/rodger/Projects/browser-laptop/tools/buildPackage.js:31:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/rodger/.nvm/versions/node/v5.7.1/bin/node" "/Users/rodger/.nvm/versions/node/v5.7.1/bin/npm" "run" "build-package"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! brave@0.8.0 build-package: `node ./tools/buildPackage.js`
npm ERR! Exit status 1
```

**Comment by bbondy** [comment]
You only need to npm run build-package if you're distributing a package.  The CHANNEL environment variable it mentions specifies which release channel you want to build, each has a different update URL.   If you just want something local you can just set it to dev.   We recommend using the prebuilt ones though, at least for the following platforms:
https://laptop-updates.brave.com/latest/osx
https://laptop-updates.brave.com/latest/winx64
https://laptop-updates.brave.com/latest/linux64

**Comment by cyberrob** [comment]
Change this
```
var env = {
  NODE_ENV: 'production',
  CHANNEL: process.env.CHANNEL
}
```
to this
```
var env = {
  NODE_ENV: 'production',
  CHANNEL: 'dev'
}
```

**Comment by bbondy** [comment]
The error message is correct, CHANNEL is a required env variable now.
`CHANNEL=dev npm run build-package` it indicates which release channel will be used for updates.
