### ISSUE TITLE
Visited link color does not get reset

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10221]
**Describe the issue you encountered:** Visited link color does not get reset.

Reported on https://community.brave.com/t/bug-report-on-clear-browsing-history-when-i-close-brave/5192?u=suguru

Brave: 0.18.14
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8
Muon: 4.3.6
libchromiumcontent: 60.0.3112.78
V8: 6.0.286.44
Node.js: 7.9.0
Update Channel: dev
OS Platform: Microsoft Windows
OS Release: 10.0.15063
OS Architecture: x64

- Steps to reproduce: 
    1. Option "Clear browsing history when I close Brave" is enabled.
    2. Search something on Google.
    3. Click in some result.
    4. Close Brave.
    5. Open Brave.
    6. Search the same stuff.
    
- Actual result: The link on the page that I clicked before is showed as visited (the color is different). It looks like the history is not cleared

- Expected result: Make sure the history including visited link should be cleared

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed: https://streamable.com/ktie0

- Any related issues:

**Comment by eljuno** [comment]
Related to #9351?

**Comment by luixxiul** [comment]
duplicate of #9351
