### ISSUE TITLE
When open in one tab too long, cannot access other already opened tabs

### ISSUE THREAD

**Issue by inertialize** [brave/browser-laptop#10229]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When the browser is open on a single tab for too long, other open tabs become inaccessible without closing and reopening brave.  The only accessible tab can open new tabs that can be accessed, but the other active tabs are not active.  The ability to preview is still maintained, but clicking on the tab does not activate the tab. There does not seem to be a determinate time necessary to cause the effect, nor is there any one particular action that appears to cause it.  The inaccessible tabs cannot be closed when this occurs, closing the accessible and active tab will close the whole browser. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):
latest version as of 08/01/2017
- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
This has been an issue for about the last 45 days. 
- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Similar to #9865  #10094

**Comment by inertialize** [comment]
is there a fix?

**Comment by bsclifton** [comment]
@inertialize no fix yet... having exact steps to reproduce the issue is very helpful though

When this happens, I can usually switch to another tab and then switch back.  Interesting feedback about how the browser closes when you close the tab having this issue

**Comment by inertialize** [comment]
when you close the tab having issues, the whole browser closes.  It reopens with everything that was previously open, including the tab that was having issues.  The problem with listing the steps for reproduction of the issue is that it seems to happen randomly, it doesn't happen with a particular site or time spent on the a particular tab. The closest I can come to steps for reproduction is this: 
1: have more than one tab open
2: pick a tab and browse on that tab for a decent amount of time (problem is intermittent and not dependent on a specific amount of time)
3: try to access another tab
4: when other tabs are inaccessible, close the only accessible tab, the whole browser will close
5: reopen Brave, tab accessibility restored.

**Comment by billsaysthis** [comment]
I have a similar but somewhat different experience with inaccessible tabs, but generally after Brave is accessed for the first time after laptop goes to sleep.

For me, some tabs are reachable and some are not, though once a tab is unreachable it stays that way. Pinned tabs (I have six) are always reachable, but unpinned tabs vary.

Also, the About dialog, Preferences and Check for Updates are unreachable. CMD+Q won't quit the browser but choosing Quit from the macOS Dock context menu will.

After restarting Brave all tabs are reachable.

Brave v0.18.14
