### ISSUE TITLE
Use better name mappings for channels on about:brave

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10239]
We should map the following identifiers in about:brave to the real channel name:

This will avoid people using the confusing internal names to refer to the channels.

dev -> Release
beta -> Beta
developer -> Developer
nightly -> Nightly

**Comment by bsclifton** [comment]
@baoqchau would you be interested in this one? It would be pretty similar to the fix you did with https://github.com/brave/browser-laptop/pull/10047

We just need a mapping between the channel (ex: `dev`) and the human readable name (ex: `Release`) 😄

**Comment by prasanthp96** [comment]
hello @bsclifton! I am interested to work on this bug, if it is not taken yet, can I fix it ?

**Comment by baoqchau** [comment]
@prasanthp96 Go ahead. I am a little busy these days so I cannot take on this issue.

**Comment by bsclifton** [comment]
@prasanthp96 that would be great! 😄  Please do work on it (I'll reserve it for you by assigning myself).  Let me know if you have any questions 😄

**Comment by bsclifton** [comment]
@prasanthp96 have you had a chance to check this one out yet? Let me know how it's going 😄

**Comment by prasanthp96** [comment]
Hy @bsclifton , sorry for the delay, I will start working on this today.

**Comment by prasanthp96** [comment]
@bsclifton I could see only three channels listed in [https://github.com/brave/browser-laptop/blob/master/app/channel.js](here). Will it suffice changing these alone ? or should I alter any other code?

**Comment by bsclifton** [comment]
@prasanthp96 I'd say let's move forward with just `dev` and `beta` for now 😄  We will be adding support for the other two very soon and `stable` isn't used (we can ignore it for now).

Once you have the mapping in place, it should be easy to adjust once we have the new channels (`developer`, `nightly`) added 😄

**Comment by prasanthp96** [comment]
@bsclifton I have sent an PR, have a look!
