### ISSUE TITLE
1Password Context Menu opens again automatically after filling in form on macOS Sierra

### ISSUE THREAD

**Issue by davidcelis** [brave/browser-laptop#10233]
- Describe the issue you encountered:

Pressing the 1Password extension's button and then clicking a login item fills in the password but then re-opens the 1Password menu an additional time. I then have to click elsewhere to close it.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS Sierra 10.12.6

- Brave Version (revision SHA):

ad92d029e184c4cff01b2e9f4916725ba675e3c8

- Steps to reproduce:
    1. Click 1Password button
    2. Click a login item to fill in a website's login form
    
- Actual result:

Login form is filled in and 1Password context menu closes before re-opening a second time

- Expected result:

Login form is filled in and 1Password context menu closes

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

**Comment by NejcZdovc** [comment]
is happening for me as well

**Comment by bsclifton** [comment]
This appears to be a bug with 1Password; I'll contact the developers for next steps

**Comment by bsclifton** [comment]
Tried to reproduce on Windows, but selecting the password from the helper doesn't do anything :(

**Comment by srirambv** [comment]
Just a note, <kbd>Ctrl+\\</kbd>  doesn't auto fill on the pages. Right click context menu entry opens the mini app and then clicking on the saved entry autofills and logins.
