### ISSUE TITLE
Optimization Opportunities in extensionState

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10235]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The extensionState module can be optimized in many places.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.19.1

- Steps to reproduce:
N/A
    
- Actual result:
N/A

- Expected result:
N/A

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
I added `release-notes/include` as I thought every perf improvement should be mentioned :-)
