### ISSUE TITLE
Restructure paymentsTab with grid property

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10236]
## Test plan

https://github.com/brave/browser-laptop/pull/10238#issue-247151904

----

**Describe the issue you encountered:** Restructure paymentsTab with display:grid. It is more simple than using display:table.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master 

- Extra QA steps:
    1. Open `about:preferences#payments`
    2. Enable payments
    3. Make sure the elements are aligned equally on both rows and columns
    4. Disable payments
    5. Make sure the switch is placed on the same place

- Screenshot if needed:

    From:
    <img width="857" alt="screenshot 2017-08-02 1 53 04" src="https://user-images.githubusercontent.com/3362943/28838713-27718082-772c-11e7-8845-a9c498188153.png">

    To:
    <img width="829" alt="screenshot 2017-08-02 13 34 17" src="https://user-images.githubusercontent.com/3362943/28857852-556b5782-7787-11e7-90ce-cedbc1b9ed84.png">

    Please see the width of the pulldown and the textarea becomes equal.

- Any related issues: #10146

**Comment by srirambv** [comment]
This is still not fixed on Windows
![image](https://user-images.githubusercontent.com/17010094/34719182-bc4c8e8e-f55f-11e7-81c6-41f1ad6e4663.png)

**Comment by luixxiul** [comment]
It's been fixed since quite a long time and the tab page has been worked on massively. Let me close this issue and open a new one to track the misalignment issue above.

**Comment by LaurenWags** [comment]
Looks good on MacOS - https://github.com/brave/browser-laptop/issues/12572 will cover mis-alignment of 'auto-include' switch:
![screen shot 2018-01-23 at 2 59 22 pm](https://user-images.githubusercontent.com/28145373/35297905-7061c094-004e-11e8-8305-11f261b66293.png)
