### ISSUE TITLE
Bookmark Folder issue

### ISSUE THREAD

**Issue by LoloIrie** [brave/browser-laptop#1023]
Bookmark created with the bookmark manager is always in the default folder insteed the selected folder in the dropdown menu.
Change the folder later is working well as temporarly workaround...

Windows version (Brave 8.0).

**Comment by bbondy** [comment]
Can no longer reproduce, I think it was fixed as part of:
https://github.com/brave/browser-laptop/commit/5fbeb3321dd0fa9fc24ac2b29afc2d6fd33f9ebd

Closing.

**Comment by LoloIrie** [comment]
I confirm, with last Brave release it works fine. Well done :)

Just a minor bug about bookmarks:
Title for the Star icon near the URL input field is always "Remove bookmark".
Should be "Add as Bookmark" if not yet as bookmark.

Do you need a new bug report for that ?
Cheers

**Comment by bbondy** [comment]
@LoloIrie  normally that's best but I fixed it here this time:
https://github.com/brave/browser-laptop/commit/515d6714993e9fdd204021bcbd33dd1e475392b1
It'll be included in 0.9.0.
