### ISSUE TITLE
Add ability for bookmarks to open in a new tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10230]
Request from community: https://community.brave.com/t/open-of-bookmarks-toolbar/4120

Good Day Devs and Community,

I realised just now that a feature I would really love to see in Brave is how it behaves when opening bookmarks. 
Let's say you have one tab open and you're on a website browsing, it would be awesome if one can then select a bookmark (toolbar or otherwise), click on it and Brave opens up the selected bookmark in a new tab automatically, instead of opening it in the current tab (as is the behaviour now).

Regards

**Comment by LaurenWags** [comment]
Similar to https://github.com/brave/browser-laptop/issues/4313 but not right-click.

**Comment by Liunkae** [comment]
You can already do this with Ctrl/Cmd+Click on any bookmark.

**Comment by bsclifton** [comment]
Middle click also works great

If there was any change to be made, we'd want it to be an option (since this is not standard behavior). cc: @alexwykoff @bradleyrichter

**Comment by eljuno** [comment]
+1 from community - option in settings to open bookmark in new tab with left-click  https://community.brave.com/t/option-to-open-bookmark-in-new-tab/15101?u=eljuno

**Comment by rebron** [comment]
Closing, tracking in https://github.com/brave/brave-browser/issues/1021 . 
Leaning towards wontfix though.
