### ISSUE TITLE
Hide enpass & metamask for 0.19

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10232]
## Test plan
See https://github.com/brave/browser-laptop/pull/10246

**Comment by luixxiul** [comment]
Note: when unhiding `enpass`, please close #7778.

**Comment by luixxiul** [comment]
@alexwykoff / @bsclifton / @cezaraugusto would one of you mind explaining why those were hidden?

CC:  @andrewalker

**Comment by bsclifton** [comment]
We ultimately need to do a test with it and uncover any potential blockers. From what I last thought, Muon didn't have support (but I could be wrong- is there an issue in brave/muon?)

@alexwykoff why did we choose to hide this during triage?

**Comment by andrewalker** [comment]
It's a bit confusing, since people reported it working with #7778, and in my tests it worked as well. Is it broken in a specific platform? Do we need unit tests for it?

**Comment by bsclifton** [comment]
@andrewalker I'll bring up with our team to see if we can expedite.  When we first release an extension, we want to make sure everything works as expected. We just haven't had enough time to properly test this yet on our side

**Comment by alexwykoff** [comment]
@luixxiul it was triaged out due to resource constraints.
