### ISSUE TITLE
Changelog (feature suggestion)

### ISSUE THREAD

**Issue by LoloIrie** [brave/browser-laptop#1024]
It would be nice to get a changelog (short/nice version) directly frome Brave (Help menu) instead to check on Github for new features or bug corrections. Just an idea ;)

**Comment by bbondy** [comment]
sounds like a good idea to me but probably not the highest priority, will leave open.

**Comment by jonathansampson** [comment]
Recent changes to _about:brave_ have added a link to _Release Notes_. These notes serve as a popular level changelog for major releases of the Browser:

![image](https://cloud.githubusercontent.com/assets/815158/26290833/00cbee4e-3e70-11e7-850f-10c48477e780.png)
