### ISSUE TITLE
make sure we pass basic Electron security audit

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#10240]
Most of https://doyensec.com/resources/us-17-Carettoni-Electronegativity-A-Study-Of-Electron-Security-wp.pdf does not apply to Muon but we should go through it anyway and make sure we don't have any security gaps.

**Comment by alexwykoff** [comment]
@diracdeltas how is this looking for 0.20?

**Comment by diracdeltas** [comment]
@alexwykoff waiting on @bridiver review
