### ISSUE TITLE
Fix issue where pinned tab can't be really unpinned

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#10241]
## Test Plan
1. Go to feedly.com
2. Pin the tab
3. Bookmark it and change the location to https://feedly.com
4. Unpin the pinned tab
5. Relaunch Brave
6. There shouldn't be any pinned tab

## Original issue description
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Pinned tabs reappear next load after unpinning
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/526dc49875fc03c6b72f7d200939a05849c6ffca

- Steps to reproduce:
    1.  go to feedly.com
    2. pin the tab
    3. bookmark it and change the location to `https://feedly.com`
    4. unpin the pinned tab
    5. relaunch Brave
    
- Actual result:
There shouldn't be any pinned feedly tab
- Expected result:
The tab is still there

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/8477

cc @bsclifton

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/10326
