### ISSUE TITLE
Set time zone value to "0"

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10247]
**Describe the issue you encountered:**
Set time zone value to "0" to reduce bits of identifying information.

On Tor Browser:
![clipboard01](https://user-images.githubusercontent.com/3362943/28861920-18af37b6-779e-11e7-9b60-dad1b1afe956.jpg)

On Brave:
![clipboard02](https://user-images.githubusercontent.com/3362943/28861939-28d47de0-779e-11e7-9945-4b09762baafc.jpg)

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open https://panopticlick.eff.org
    2. Conduct a test
    
- Expected result: time zone value to "0".

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by riastradh-brave** [comment]
https://github.com/brave/brave-browser/issues/723

**Comment by bsclifton** [comment]
Closing as `wontfix` - thanks for opening in brave-core, @riastradh-brave 😄
