### ISSUE TITLE
Show tooltips over "Minimize", "Maximize", and "Close" buttons on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10244]
The tooltips were originally implemented but was reverted to solve https://github.com/brave/browser-laptop/issues/8697

The issue is captured upstream
- [in electron](https://github.com/electron/electron/issues/9943)
- [in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=724538)

When the root cause is fixed, this issue can be solved by reverting the following commit https://github.com/brave/browser-laptop/commit/0d584b9ba39db83539825d0b35641d59efe8d8a4

**Comment by withmetta** [comment]
Tooltips in Brave exist for me. Any ETA on when this issue will get fixed?

Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by bsclifton** [comment]
Hi @withmetta 

The fix will be available in our next release.  This will be out within the next week 😄

**Comment by bsclifton** [comment]
This could potentially be solved by reverting the above commit after patching https://github.com/electron/electron/pull/11629 against Muon

**Comment by bsclifton** [comment]
This isn't fixed with our [Developer channel release](), but the behavior is consistent with Chromium/Chrome.
