### ISSUE TITLE
Site favicon with badge doesn't align with other 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10259]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Site favicon with badge doesn't align with other 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.14
-- | --
rev | ad92d02
Muon | 4.3.6

- Steps to reproduce:
    1. Open Gmail in two session tabs
    2. Pin both the tabs
    3. Wait till one of them shows the mail count 
    
- Actual result:
See screenshot

- Expected result:
Should resize the favicon if it has a badge and should align with others

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Must be 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28918125-0c44c58e-7840-11e7-90cb-fa461e223edd.png)

- Any related issues:
cc: @bradleyrichter @cezaraugusto

**Comment by alexwykoff** [comment]
@srirambv what does chrome do?

**Comment by srirambv** [comment]
This is on Chrome
![image](https://user-images.githubusercontent.com/17010094/30267527-7e259b54-9700-11e7-8f10-9c6a81f2cf25.png)
