### ISSUE TITLE
ctrl + F5 does not clear cache before or after reload

### ISSUE THREAD

**Issue by golyalpha** [brave/browser-laptop#10256]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Using the key shortcut to reload pages with clearing cache doesn't work
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10 x64
- Brave Version (revision SHA):
ad92d02
- Steps to reproduce:
    1. Load a page
    2. Open up dev console
    3. Check which files are loaded from cache
    4. Ctrl + F5 
    
- Actual result:
Files are still loading from cache
- Expected result:
Everything reloads from the server
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
All my settings are default, Flash installed and enabled, LastPass is enabled, Torrent Viewer is enabled
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes.

**Comment by luixxiul** [comment]
Would you test with `Ctrl + Shift + R`, which is the default shortcut?

**Comment by golyalpha** [comment]
If Ctrl + Shift + R is the default shortcut, you should update your Wiki, since it says that Ctrl + F5 is the "Clear Cache and Reload" function.

**Comment by golyalpha** [comment]
Just checked, Ctrl + Shift + R doesn't work either, at least not in the latest version available on the website. (I have reinstalled my computer, so had to fresh install the latest version of Brave Browser)

**Comment by bsclifton** [comment]
@srirambv can you please try this on our latest release? (0.18.21) This should definitely be working

**Comment by srirambv** [comment]
@bsclifton Still loading from disk cache and memory cache
![10256](https://user-images.githubusercontent.com/17010094/29160490-53434cfc-7daa-11e7-97d3-1b0cf3f48a31.gif)

**Comment by jabowery** [comment]
This brain-dead caching is a perennial issue with Chrome and now apparently with Brave.  Does anyone know why it is so hard to get a bug free implementation of clean reload?

**Comment by bsclifton** [comment]
Tentatively assigning to 0.21.x since this is an important feature

**Comment by sgnls** [comment]
I am sure it's already on the radar of many, but this remains an issue with 178c3fb. Is this bug likely to be continued following the migration to Chromium and is there an owner yet?

**Comment by xurshid29** [comment]
Same issue here, Shift+CMD+R is not clearing. But, checking the **Disable cache**  on Network tab of Developer tool is working.

**Comment by golyalpha** [comment]
For some reason, this reason is being pushed back, which I find frustrating...

**Comment by bsclifton** [comment]
With our Developer channel build available today, folks can try (and verify) the fix there:
https://brave.com/download-dev

Closing as issue is resolved there
