### ISSUE TITLE
Suggestion: Better Protocol Handler Notification

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10251]
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
Based on this tweet https://twitter.com/gortok/status/892448941928742912
And this one from community https://community.brave.com/t/gmail-and-bitcoin-protocol/4185

Notification for protocol handler is too general. The string is contain other protocol that can confuse user. Like "`:bitcoin` protocol for gmail?"
Maybe remove `:bitcoin, etc` from the notification? And make a "dynamic/per protocol" notification?

Not sure about other browser behaviour about this.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Maybe all.

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Fresh install/fresh profile
    2. Log in to gmail
    3. See the notification. `:bitcoin, etc` listed along with `:mailto` that can confuse user
    
- Actual result:
`:bitcoin, etc` listed in notification along with `:mailto`

- Expected result:
Only show `:mailto` for Gmail or other similar service.
And only show `:bitcoin` for service that use that protocol.
And for other protocols as well.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-protocol-handler-notification](https://user-images.githubusercontent.com/25360853/28891729-b28af116-77f5-11e7-9d28-98443eb04b9b.png)

- Any related issues:

**Comment by luixxiul** [comment]
related with #3246 #2461

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/google-to-handle-special-protocols-bitcoin-in-brave/26367?u=eljuno
