### ISSUE TITLE
Provide an AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [brave/browser-laptop#10250]
I would like to try out your browser but without letting it change repositories or libraries in my system.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If you are interested, I am happy to help you make it happen. Just let me know.

**Comment by bsclifton** [comment]
@probonopd I think this would be awesome 😄  Any help is appreciated

**Comment by probonopd** [comment]
Sure, since you are already using Travis CI I would propose to use that for automatic AppImage generation, too. There are [many examples](https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt) of real-world applications already doing exactly that.

Alternatively, you could use the [Open Build Service](https://git.io/obs-ai) which would even update the bundled dependencies for you automatically.

**Comment by posix4e** [comment]
Love it. I think we mainly use jenkins since the muon build requires building chromium. We are looking for ways of providing a better experience to the community in regards to this. I'd love for more feedback. Tell me more about your usecase.

**Comment by probonopd** [comment]
My use case: Run the Live ISO of any major Linux distribution, download an AppImage, run the application - without installation. As for how to do it, please have a look at the examples linked above. I am happy to help if you run into any issues. Plus, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by posix4e** [comment]
I have uploaded a appimage preview package for 32 and 64 bit to my personal bucket (http://storage.googleapis.com/posis-brave-mirror/

**Comment by probonopd** [comment]
Wow @posix4e thanks for making these. The AppImage is 270 MB large, much larger than any browser I have seen as an AppImage before. Is this expected, or is it maybe by mistake? (I didn't analyze the content of the AppImage yet.) How did you make it?

**Comment by posix4e** [comment]
Yea i think it might be the gtk stuff.

**Comment by Plasmoner** [comment]
I would love a Brave appimage. I was actually intending to open an issue kindly requesting it. Please, please make a Brave appimage. Adorable browser.

**Comment by posix4e** [comment]
DId you see the preview image? Would you be willing to help/beta test?

**Comment by probonopd** [comment]
What is the status on this? Any chance that the AppImage will see the light of day?

**Comment by posix4e** [comment]
@probonopd we have some preview images did you try them out?

**Comment by probonopd** [comment]
http://storage.googleapis.com/posis-brave-mirror/ is not letting me access the files @posix4e

**Comment by probonopd** [comment]
As for the "raw x86-64 binaries", I am getting on Ubuntu 16.04:

```
me@host:~$ /home/me/Brave-linux-x64/brave
[9363:9389:1221/224923.003601:FATAL:nss_util.cc(631)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
Aborted
```

**Comment by posix4e** [comment]
Woops forgot to pay the bill one sec

**Comment by posix4e** [comment]
```
<Message>
Your Google account is not currently enabled for this operation. Please check https://console.developers.google.com/billing to see if you have a past due balance or if the credit card (or other payment mechanism) on your account is expired. You can find additional information at https://developers.google.com/storage/docs/signup
</Message>
<Details>
The billing account for the requested project is disabled in state 'closed'
</Details>
</Error>
```

**Comment by posix4e** [comment]
Try now

**Comment by posix4e** [comment]
Like http://storage.googleapis.com/posis-brave-mirror/brave-0.20.0-x86_64.AppImage

**Comment by probonopd** [comment]
With 270 MB in size it is _way_ larger than other AppImages of browsers such as Beaker. Why is that?

**Comment by posix4e** [comment]
We ship gtk still

**Comment by cmatomic** [comment]
Why brave appimage is not official ?
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

**Comment by cmatomic** [comment]
I can not see what is inside the appimage, very strange this appimage is not possible to extract it.

**Comment by probonopd** [comment]
@cmatomic with recent AppImages (built with recent versions of `appimagetool` or `linuxdeployqt`) it should be possible to extract the AppImage using the `--appimage-extract` command line option. For older AppImages, you should be able to loop-mount them to inspect their contents.

@posix4e are you interested in making the AppImage official? Can I help with anything?

**Comment by probonopd** [comment]
Will there be new versions on http://storage.googleapis.com/posis-brave-mirror/?

**Comment by posix4e** [comment]
I should do this. Wanna grab a time to chat about how we can work together on it? Email me at posix4e at gmail

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1060
