### ISSUE TITLE
Brave allows ads, Firefox does not

### ISSUE THREAD

**Issue by DazzaRPD** [brave/browser-laptop#10268]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Since the introduction of the "Reddit ads" on Reddit, Brave + Ad Blocker shields on has ads displaying on Reddit, whereas Firefox + uBlock Origin does not.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 8.1

- Brave Version (revision SHA):
0.18.14 rev ad92d02 (commit ad92d029e184c4cff01b2e9f4916725ba675e3c8)

- Steps to reproduce:
    1. Open Brave and Firefox (uBlock Origin must be enabled)
    2. Navigate to reddit and view the page
    
- Actual result:
Ads display on Brave - despite ad blocking being fully enabled

- Expected result:
No ads should be displayed, as ad blocking is disabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
As far as I know, yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
http://imgur.com/R2kYi6z - on Firefox + uBlock
http://imgur.com/Lf26Ef3 - on Brave with ad block

- Any related issues:

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/8211#issuecomment-293121704
> Thanks! Blocking native ads (including promoted tweets) is being tracked in #527. It does not have a milestone yet, but you can subscribe to the issue for any further updates. Closing this one as a duplicate.
