### ISSUE TITLE
Choose default download path not working

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#10260]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
It is not possible to choose where to save downloads the menu appears but nothing happens when you choose where to download.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X 10.9.5
- Brave Version (revision SHA):
0.18.14
- Steps to reproduce:
    1. Open brave with new profile
    2. Choose where to download a file
    
- Actual result:
Does not work, the download destination never gets set
- Expected result:
Default download path should be setable
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Possibly blocking by #13570 

cc: @kjozwiak @bsclifton

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
