### ISSUE TITLE
Issue to check for new release

### ISSUE THREAD

**Issue by LoloIrie** [brave/browser-laptop#1026]
I'm not able to check for new releases... Proxy issue maybe

2016-03-07T15:17:39.287Z - checkForUpdates
2016-03-07T15:17:39.289Z - lastCheckYMD = 2016-03-07
2016-03-07T15:17:39.294Z - https://brave-laptop-updates.global.ssl.fastly.net/1/releases/dev/0.8.0/winx64?daily=false&weekly=false&monthly=false&first=false
2016-03-07T15:17:39.294Z - firstCheckMade = true
2016-03-07T15:17:39.291Z - lastCheckWOY = 10
2016-03-07T15:17:39.293Z - lastCheckMonth = 3
2016-03-07T15:17:39.329Z - Error: tunneling socket could not be established, cause=Parse Error

**Comment by LoloIrie** [comment]
Hi,
if it's not possible to quickly fix this issue, it would be really helpful to see on the Brave website which version is the current one...
Thanks :)

**Comment by luixxiul** [comment]
What do you think, @bbondy?

**Comment by bbondy** [comment]
Could you navigate to `https://brave-laptop-updates.global.ssl.fastly.net/1/releases/dev/0.8.0/winx64?daily=false&weekly=false&monthly=false&first=false` and paste what you see?

**Comment by cezaraugusto** [comment]
@LoloIrie could you please follow @bbondy recommendation and show us what happens?

**Comment by LoloIrie** [comment]
Sorry I missed the answers here. :(
I will try it this monday like I get the issue at the office only, and will post here then... Thanks for your support.

**Comment by LoloIrie** [comment]
Now when I check for updates I get a javascript error message popup (error in the main process)...

When I access the required page I get following info:

`{"version":"0.10.3","name":"Brave 0.10.3","pub_date":"2016-06-08T16:23:55.491Z","notes":"Update to libchromiumcontent 51.0.2704.84\n\nCrash fix for Windows with some link types.\n\nFingerprint protection in the Bravery panel and various fixes. Full notes: https://github.com/brave/browser-laptop/releases/v0.10.1dev\n\nPer site Bravery panel, error pages, and much more. Full detail: https://github.com/brave/browser-laptop/releases/tag/v0.10.0dev\n\nChromium 50.0.2661.102 and various bug fixes. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.6dev\n\nSpell check, script blocking similar to NoScript, and much more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.5dev\n\nStartup fix if profile dir does not exist\n\nDashlane support, external protocol handling, permission prompts, Chromium 50.0.2661.86, and more\n\nWindows 32-bit support, Windows default browser handling, fingerprinting protection, zoom fixes, multi language support, printing fix, and more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.2dev\n\nVarious fixes. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.1dev\n\n1Password support, malware protection, phishing protection and more.  Details: https://github.com/brave/browser-laptop/releases/tag/v0.9.0dev\n\nDownloads manager, downloads toolbar, passwords manager, and more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.8.3dev\n\nPassword saving, single instance app, more HTTPS Everywhere info, full screen mode fixes, and more.  More details here: https://github.com/brave/browser-laptop/releases/tag/v0.8.2dev\n\nSecurity updates, basic HTTP auth support, and more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.8.1dev"}`

hope it helps

**Comment by LoloIrie** [comment]
I get now the following JS error when I try the update check (Just one popup) or when I start the browser (4 popups) (Tried to uninstall and install again):
Good luck to fix this annoying issue and thanks again for the job.

http://hpics.li/ef44e3e

**Comment by luixxiul** [comment]
+1 from support

**Comment by plrgrs** [comment]
when I access the page https://brave-laptop-updates.global.ssl.fastly.net/1/releases/dev/0.8.0/winx64?daily=false&weekly=false&monthly=false&first=fals

, I get this text

> 
{"version":"0.11.3","name":"Brave 0.11.3","pub_date":"2016-08-06T05:06:58.325Z","notes":"PDF, zoom, URL bar fixes, and libchromiumcontent 52.0.2743.116. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.11.3dev\n\nLong tap history on back button, search shortcuts like 'yt cat videos', tab and nav cloning,  and much more: https://github.com/brave/browser-laptop/releases/tag/v0.11.2dev\n\nPDF viewing, more data clearing options, navigator.registerProtocolHandler support, copy image option and more: https://github.com/brave/browser-laptop/releases/tag/v0.11.1dev\n\nLastPass support, WebRTC fingerprinting protection, Flash click to play if Flash is enabled, and more: https://github.com/brave/browser-laptop/releases/tag/v0.11.0dev\n\nAutocomplete, new suggestions UX, experimental Flash support and more: https://github.com/brave/browser-laptop/releases/v0.10.4dev\n\nUpdate to libchromiumcontent 51.0.2704.84\n\nCrash fix for Windows with some link types.\n\nFingerprint protection in the Bravery panel and various fixes. Full notes: https://github.com/brave/browser-laptop/releases/v0.10.1dev\n\nPer site Bravery panel, error pages, and much more. Full detail: https://github.com/brave/browser-laptop/releases/tag/v0.10.0dev\n\nChromium 50.0.2661.102 and various bug fixes. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.6dev\n\nSpell check, script blocking similar to NoScript, and much more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.5dev\n\nStartup fix if profile dir does not exist\n\nDashlane support, external protocol handling, permission prompts, Chromium 50.0.2661.86, and more\n\nWindows 32-bit support, Windows default browser handling, fingerprinting protection, zoom fixes, multi language support, printing fix, and more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.2dev\n\nVarious fixes. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.9.1dev\n\n1Password support, malware protection, phishing protection and more.  Details: https://github.com/brave/browser-laptop/releases/tag/v0.9.0dev\n\nDownloads manager, downloads toolbar, passwords manager, and more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.8.3dev\n\nPassword saving, single instance app, more HTTPS Everywhere info, full screen mode fixes, and more.  More details here: https://github.com/brave/browser-laptop/releases/tag/v0.8.2dev\n\nSecurity updates, basic HTTP auth support, and more. Full details: https://github.com/brave/browser-laptop/releases/tag/v0.8.1dev"}

**Comment by plrgrs** [comment]
workaround is to uninstall the old version of the Brave browser and re-install the latest version of the browser

**Comment by luixxiul** [comment]
It seems the issue has been fixed already, closing.
