### ISSUE TITLE
Indicate Audio During Speech Synthesis Utterance

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10278]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
No indication that audio is being placed during speech synthesis utterance playback.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.19.1

- Steps to reproduce:
  1. Visit https://jonathansampson.github.io/browser-tests/brave/speech-synth-indicator/
  2. Click 'Speak' button
 <br>

- Actual result:
Tab indicates no audio is being played.

- Expected result:
Tab indicates that audio is being played.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/886
