### ISSUE TITLE
Margin seems wrong for downloads

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#10277]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Margin on view all button on the downloads bar is wrong on 0.18.x
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 and MacOS (Checked by @LaurenWags)
- Brave Version (revision SHA):
0.18.15 and 0.14.14
- Steps to reproduce:
    1. Download something
    2.
    3.
    
- Actual result:
View all seems to have wrong margin
![image](https://user-images.githubusercontent.com/25466657/28939274-0b4af1b6-7891-11e7-9e43-e81ed46ee3b0.png)

- Expected result:
Right margin, master and 0.19.x:
![image](https://user-images.githubusercontent.com/25466657/28939296-1e493c5a-7891-11e7-98bd-420184db443e.png)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. Go to brave.com 
    2. Download any version
    3. look at downloads bar, should have correct margin

- Screenshot if needed:
See actual and expected
- Any related issues:

**Comment by Jacalz** [comment]
cc @luixxiul

**Comment by Jacalz** [comment]
Margin seem to be the same on master and 0.18.x in the code

**Comment by luixxiul** [comment]
On master this looks to have been fixed: https://github.com/brave/browser-laptop/commit/cdaee376e59f35619f4d2854b8a1c059430636ca#diff-feb05dc9da2c7d58a56f56f53d3b9a43R94. CC @cezaraugusto

**Comment by cezaraugusto** [comment]
thanks for reporting, yes this is fixed in 0.19.x. closing
