### ISSUE TITLE
Cannot Mute Speech Synthesis Audio

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10284]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The user is unable to mute Speech Synthesis audio.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.19.1

- Steps to reproduce:
  1. Open New Tab
  2. Open 2nd New Tab
  1. Visit https://jonathansampson.github.io/browser-tests/brave/speech-synth-indicator/ in 2nd tab
  2. Click 'Speak' button
  3. While audio is playing, right-click first New Tab and select _Mute other Tabs_
<br>
- Actual result:
Tab is not muted

- Expected result:
Tab is muted

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues:
#10278

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/885
