### ISSUE TITLE
Add Swedish (Sweden) language

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#10297]
Add the Swedish (Sweden) language to about:preferences

QA Steps:

1. Start browser, navigate to about:preferences
2. Change language setting to Swedish (Sweden), restart browser
3. Ensure language has changed to Swedish

**Comment by alexwykoff** [comment]
@Jacalz please ping @aekeus once the strings are updated in transifex 😸

**Comment by Jacalz** [comment]
Yeah will do, have yet to get some time to do it yet sadly 😕 But I will sure make this happen in time 🙂

**Comment by Jacalz** [comment]
I can not see swedish in the latest master :(

**Comment by Jacalz** [comment]
Adding this to 0.19.x since it is done just needs the new transifex strings pulled down...

**Comment by Jacalz** [comment]
Preferably I would like to get this in the 0.18.x hotfix 2 🙂
