### ISSUE TITLE
remove uneeded animation for tab previews

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10298]
we are calling the animation twice for two diff elements and that triggers more repaints/reflows than needed

**Comment by bsclifton** [comment]
@cezaraugusto was this issue resolved?

**Comment by cezaraugusto** [comment]
it wasn't really an issue but we are making previews using two different elements which is kind of redundant but after profiling for a couple more times there's no real performance gain and given it will eventually be fixed with #6716 I preferred to close.
