### ISSUE TITLE
Use shared memory for transfering window state to the browser process

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10292]
This will possibly fix https://github.com/brave/browser-laptop/issues/10094 but keeping it separate in case not. It's still a good perf win either way.

**Comment by bsclifton** [comment]
Fixed in 0.18.x with https://github.com/brave/browser-laptop/pull/10294

**Comment by bsclifton** [comment]
- Fixed in 0.19.x with https://github.com/brave/browser-laptop/commit/13c8b3b2cd0839e0063db8d65a3741c7eb9b8ac9
- Fixed in 0.20.x with https://github.com/brave/browser-laptop/commit/938e570dc80fa72957371cb9f08e0ab432169115
- Fixed in master with https://github.com/brave/browser-laptop/commit/3b832979d875d5cf9bb09e00a0284e5ff64fa22a

cc: @bbondy for audit

**Comment by luixxiul** [comment]
See https://github.com/brave/browser-laptop/pull/10294#issuecomment-320846632 and #10332

**Comment by bsclifton** [comment]
Missing from this was the upgrade to Muon `4.4.6`.  I went ahead and updated that for all branches (0.18.x already had the update, which was in Muon `4.3.9`) and I cannot reproduce the issue @cezaraugusto reported

**Comment by bbondy** [comment]
Reverted:
0.18.x: 2c7141fadb06b1b4c4bc15896795cacf869e4842
0.19.x: 1194c1c05ac8c75d5845dfebff2e173f90832c4b
0.20.x: b08ff11aab7372780c1e0f58c565e67229b598d4
master: 69eee4205e487351952393d1c6b99a6c10a3978b

**Comment by bbondy** [comment]
This isn't working on Windows currently until we have a new muon so moving this back to 0.21.x for now.  I'll PR it and block it on another issue for shared memory in renderer on Windows within sandbox.

**Comment by bbondy** [comment]
Re-landed on 0.19.x, 0.20.x, master with the new muon 4.4.7

**Comment by luixxiul** [comment]
no-qa-needed?

**Comment by bbondy** [comment]
it'll be caught by a general regression pass if any issues, adding that label.
