### ISSUE TITLE
do not show loading icon for about pages

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10303]
about pages are expected to be fast and load instantly and having a loading icon is unnecessary and cause perf junk.

**Comment by mursalal** [comment]
Hello! Please add user manager, so that all users have own cookies.

**Comment by Liunkae** [comment]
@mursalal I opened a separate issue: #10324

**Comment by bsclifton** [comment]
Steps added
cc: @cezaraugusto
