### ISSUE TITLE
When I push the minimize option the words "Minimize" do not go away

### ISSUE THREAD

**Issue by NewBreed117** [brave/browser-laptop#10308]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
  When I click on the minimize button the word "Minimize" does not go away after the browser has minimized. The only way to get the minimize text to go away is to select the Brave browser icon.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 10.0.15063
- Brave Version (revision SHA):
  0.18.14
- Steps to reproduce:
    1. Use mouse to select the minimize button in the top right hand corner of the browser screen.
    2.
    3.
    
- Actual result:
  Browser minimizes but "Minimize" text overlay does not go away.
- Expected result:
  Browser minimizes and "Minimize" text overlay goes away.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
  Yes
- Can this issue be consistently reproduced?
  Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  
![image-01](https://user-images.githubusercontent.com/13923648/28998109-9e6e69aa-79e0-11e7-90e4-75cf16f46079.PNG)

- Any related issues:

**Comment by Jacalz** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/8697

**Comment by Jacalz** [comment]
Should be foxy with next release also 🙂
