### ISSUE TITLE
Brave.com should be able to detect if you visit using Brave

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10329]
## Test plan
Steps to test manually (I ran and verified it works fine)
1. Launch Brave and visit https://brave.com
2. Open the developer tools (F12 or shift + option + i)
3. Force reload the page (shift + cmd + R or shift + ctrl + R)
4. Inspect the network tab for the `brave.com` resource
5. Under request headers, you should see the user agent (`Brave` being the important part):
"user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) **Brave** Chrome/59.0.3071.115 Safari/537.36"

## Original issue description
request per @too4words:
Instead of prompting user with "Download Brave" we may instead show "Thank you for using Brave"

In order to do this, we'd need a way to detect the browser is Brave (via user agent string)

**Comment by srirambv** [comment]
Works on Windows
![image](https://user-images.githubusercontent.com/17010094/34256958-b6ec0bf0-e64f-11e7-91f3-f2afc0b85cfe.png)

**Comment by LaurenWags** [comment]
MacOS:
![screen shot 2017-12-21 at 5 11 57 pm](https://user-images.githubusercontent.com/28145373/34277030-1e1ae9dc-e672-11e7-8799-7bb2b240356a.png)
