### ISSUE TITLE
Release notes for 0.18.x hotfix

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10320]
Release Notes:
 - Tab previews: stick to changing properties that can be handled by the compositor alone. ([#10291](https://github.com/brave/browser-laptop/issues/10291))
 - Findbar slowness (cmd + F, typing). ([#10271](https://github.com/brave/browser-laptop/issues/10271))
 - Upgrade to muon 4.3.9. ([#10262](https://github.com/brave/browser-laptop/issues/10262))
 - Upgrade to Chromium 60.0.3112.90. ([#10261](https://github.com/brave/browser-laptop/issues/10261))
 - Optimization Opportunities in extensionState. ([#10235](https://github.com/brave/browser-laptop/issues/10235))
 - Extension Popup Not Showing. ([#10224](https://github.com/brave/browser-laptop/issues/10224))
 - Linux rpm is not signed. ([#10188](https://github.com/brave/browser-laptop/issues/10188))
 - Pinned tab will not display. ([#10122](https://github.com/brave/browser-laptop/issues/10122))
 - Cursor not shown when editing a bookmark. ([#10104](https://github.com/brave/browser-laptop/issues/10104))
 - Optimized window initialization data to use shared memory. ([#10018](https://github.com/brave/browser-laptop/issues/10018))
 - About favicons are taking up way too much space in the session store. ([#10000](https://github.com/brave/browser-laptop/issues/10000))
 - Bitwarden widget not shown on webpages, shows only on about pages. ([#9437](https://github.com/brave/browser-laptop/issues/9437))
 - Opening URL from external application (Thunderbird/LibreOffice) does not work any more. ([#9193](https://github.com/brave/browser-laptop/issues/9193))
 - Unhide bitwarden password manager. ([#7921](https://github.com/brave/browser-laptop/issues/7921))
 - Added Bitwarden Password Manager. ([#4776](https://github.com/brave/browser-laptop/issues/4776))

**Comment by luixxiul** [comment]
@alexwykoff the last two should be omitted.

**Comment by bsclifton** [comment]
We do want to keep https://github.com/brave/browser-laptop/issues/4776, but we should hide https://github.com/brave/browser-laptop/issues/7921 because it's basically a duplicate. I updated the labels accordingly 😄

**Comment by luixxiul** [comment]
@bsclifton thanks!
