### ISSUE TITLE
Bookmarks deleted, preferences reset

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1032]
Yesterday I set up preferences and about 20 bookmarks and folders. Today all bookmarks are gone and the preferences were reset to "standard".

**Comment by bbondy** [comment]
Sorry to hear this :( Can you think of any steps to reproduce which could have led to that?

**Comment by krzysmierz** [comment]
same happened for me. reset today pc. and full everything reseted to begining - even opened tabs (34) back to this what was opened 2 days ago (4)

**Comment by bbondy** [comment]
I'll add this to 0.8.1 to periodically save the session store, I think these issues would have bee resolved if that was in place.  We're only saving on shutdown right now.

**Comment by cfumante** [comment]
Sorry __
 
No smoking gun.
 
I set my bookmarks/prefs one day, put the desktop to sleep for the night
and the next moring it was all reset, looking like it had been
reinstalled. There wasn't an update release the night before last was
there?
 
mahalo,
 

Carl Fumante                                                : 

The surest sign that there is intelligent life in the universe is that
they haven't tried to contact us.

 

-----Original Message-----

**Comment by cfumante** [comment]
djunkuya for confirmation. wasn't sure if I had screwed up 
 
 

Carl Fumante                                                : 

The surest sign that there is intelligent life in the universe is that
they haven't tried to contact us.

 

-----Original Message-----

**Comment by cfumante** [comment]
mahalo,
 
 

Carl Fumante                                                : 

The surest sign that there is intelligent life in the universe is that
they haven't tried to contact us.

 

-----Original Message-----
