### ISSUE TITLE
Detached tabs keep loading

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10334]
**Describe the issue you encountered:** Detached tabs keep loading.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.18.17

- Steps to reproduce:
    1. Clear your browser's profile
    2. Open https://github.com
    3. Click `Business` to open it in a new tab
    4. Make sure the loading finishes
    5. Detach the tab via tab context menu   
    
- Actual result: The detached tab keeps loading

- Expected result: It should finish loading and the beachball should disappear

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
@bbondy is this duping to #10376 as well as https://github.com/brave/browser-laptop/issues/10365#event-1200253457 is?

**Comment by Liunkae** [comment]
Seems OK for me in 0.18.22 (d850e28)

**Comment by bsclifton** [comment]
@luixxiul this should already be fixed- can you please try 0.18.22?

**Comment by luixxiul** [comment]
Yes I confirmed that has been fixed.
