### ISSUE TITLE
Duplicate Brave windows appear on relaunch

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#1034]
I relaunched Brave to update to version 0.8.0 on Windows. The three tabs I had open before reappeared as expected, but two separate Brave windows appeared. (Each with the three tabs.)

I think I had this issue earlier on Windows but my memory is fuzzy and I don't remember details, but I don't think it's a new issue.

**Comment by luixxiul** [comment]
Closing for the moment. Please update to the latest version and comment here if this problem still exists.
