### ISSUE TITLE
Crashing main process is losing window state

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10349]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Using debug menu 
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, probably others

- Brave Version (revision SHA):
0.18.x through master

- Steps to reproduce:
    0. Clean session store (or not is fine)
    1. Open Brave and open a few tabs
    2. Quit normally
    3. Startup normally, and see tabs restored.
    4. `BRAVE_ENABLE_DEBUG_MENU=1  open -a Brave`
    5. Select crash main process
    6. Start Brave 
    
- Actual result:
Tabs aren't restored.

- Expected result:
Tabs are restored.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
Just for reference: original fix was delivered with https://github.com/brave/browser-laptop/pull/9912

**Comment by bbondy** [comment]
0.18.x: 1dfd76e8e567b872158a3c1079f0f177d20fc71c
0.19.x: b8296c13671ece01a1d3ff0b22766fa988ee0a53
0.20.x: f9d09f3249444d6e617d4b36e138bcbd47fab979
master: 2634bbfc8ac397c1b426a8dad2244bcbae61b9c4

**Comment by LaurenWags** [comment]
Losing window state on MacOS

![10349](https://user-images.githubusercontent.com/28145373/29179527-a904f74a-7dc2-11e7-83b8-c4a61e99bc6f.gif)

**Comment by bbondy** [comment]
I think this is actually fixed and it's just an issue with the way it's being tested.

Could you confirm @LaurenWags ?

`open -a Brave.app` will always open Brave.app in /Applications even if you are in a directory that has a different Brave.app.
I think `open ./Brave.app` would open the one in the local directory.

I'm thinking each time the right build is started, until you use the command line in the video. Then it uses the wrong one. 

Marking as closed for retesting.

**Comment by LaurenWags** [comment]
Used suggestion from @bbondy for testing and window state was preserved.
