### ISSUE TITLE
Hide bitwarden and pinterest for 0.18.x 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10343]
## Test plan
1. Open Preferences > Security and verify that bitwarden is not shown in the drop down under "Passwords and forms"
2. Visit Preferences > Extensions and verify that bitwarden and Pinterest do not show

## Original issue description
Mea culpa. QA should have spent more time on this before we made it visible. 

We'll be focused on having it fixed in the near future.

**Comment by bsclifton** [comment]
Updated to call out hiding pinterest as well, until it's ready

cc: @jonathansampson @kevinlawler

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/10345 (merged into all branches, including [master](https://github.com/brave/browser-laptop/commit/4cae9819e61ad276de57a0d6b2972da5159c41ce))

**Comment by LaurenWags** [comment]
On MacOS Bitwarden and Pinterest are hidden in a clean profile, but if they were previously enabled on 0.18.14 (released version), they are still visible under about:preferences#extensions and beside the URL bar.

![10343](https://user-images.githubusercontent.com/28145373/29180036-6e81742a-7dc4-11e7-8fbf-713607066728.gif)

**Comment by bsclifton** [comment]
Great find, @LaurenWags 😄  I've got a fix here, will submit a PR shortly

**Comment by LaurenWags** [comment]
Verified using update from 0.18.14 where they were enabled and on 0.18.22 using clean profile.
