### ISSUE TITLE
No release file

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10350]
**Describe the issue you encountered:** https://community.brave.com/t/no-release-file/5471?u=suguru

> I have the same issue as [this post in Spanish](https://community.brave.com/t/no-funciona-repositorio/4937) on Linux Mint 18.2 Cinnamon Edition: 
>
>    E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt sonya Release' does not have a Release file.
>    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
>    N: See apt-secure(8) manpage for repository creation and user configuration details
>
> **EDIT**: I'm also getting a secondary error from the Update Manager:
>
> `Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/sonya/main/binary-amd64/Packages  403  ForbiddenSome index files failed to download. They have been ignored, or old ones used instead.`
>
> I already had `lsb-release` installed, so I installed `lsb-core` but it made no difference. 
>
> brave-sonya.list: `deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt sonya main`

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux Mint 18.2 Cinnamon Edition

- Brave Version (revision SHA):

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
CC @posix4e

**Comment by sergiuszm** [comment]
I have the same issue with Linux Mint 18.2

**Comment by posix4e** [comment]
https://s3-us-west-2.amazonaws.com/brave-apt/dists/sonya/main/binary-amd64/Packages <- We have different instructions for non supported repos, like linux mint

**Comment by jeanpaullinux** [comment]
I got the same issue on Linux Mint 18.2. 

@posix4e The link that you posted unfortunately does not work.

**Comment by posix4e** [comment]
@jeanpaullinux there's special instructions for linux mint please read down the page

**Comment by luixxiul** [comment]
there are some people who say it is not fixed yet. @posix4e would you please mind providing them instructions? 

https://community.brave.com/t/no-release-file/5471/4?u=suguru

**Comment by posix4e** [comment]
Great
