### ISSUE TITLE
undefined symbol: gdk_screen_get_monitor_scale_factor

### ISSUE THREAD

**Issue by wolkym** [brave/browser-laptop#10352]
**0.18 version doesn't run on Ubuntu 12.04 LTS.**

It fails with **`undefined symbol: gdk_screen_get_monitor_scale_factor`**
```
cracs@ddmstat:~/Downloads$ brave
brave: symbol lookup error: brave: undefined symbol: gdk_screen_get_monitor_scale_factor

cracs@ddmstat:~/Downloads$ which brave
/usr/bin/brave
```

Platform:
```
cracs@ddmstat:~/Downloads$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
cracs@ddmstat:~/Downloads$ uname -a
Linux ddmstat 3.13.0-77-generic #121~precise1-Ubuntu SMP Wed Jan 20 18:02:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cracs@ddmstat:~/Downloads$ aptitude versions ~ilibgdk
Package libgdk-pixbuf2.0-0:                       
i   2.26.1-1ubuntu1.3                                                                                                   100 

Package libgdk-pixbuf2.0-common:
i   2.26.1-1ubuntu1.3                                                                                                   100 

Package libgdk-pixbuf2.0-dev:
i A 2.26.1-1ubuntu1.3                                                                                                   100 
```

Brave Version (revision SHA):
`0.18.16-1`

Steps to reproduce:
    1. Install brave 0.18.16-1
    2. run brave
    
Is this an issue in the currently released version? **YES**

Can this issue be consistently reproduced? **YES**

**Comment by bsclifton** [comment]
Ubuntu 12 is a little old- I don't know if Chromium is supported on that spec.  @cronacronis does Chrome / Chromium work OK for you?

**Comment by cronacronis** [comment]
@bsclifton version 0.17 works fine. Chrome works as well :)

**Comment by bsclifton** [comment]
@cronacronis what version of Chrome? With 0.18.14, we upgraded to Chromium 60

**Comment by bsclifton** [comment]
cc: @hferreiro

**Comment by ltilve** [comment]
It seems it could be a missing gtk3 dependency issue. The symbol for  `gdk_screen_get_monitor_scale_factor` should come with `/lib64/libgdk-3.so`.
Apparently it happens too with upstream `Chrome 60` and `Red Hat 7` https://stackoverflow.com/questions/45312030/chrome-60-undefined-symbol-gdk-screen-get-monitor-scale-factor-on-redhat-7

**Comment by cronacronis** [comment]
Looks like I have it, but indeed no `gdk_screen_get_monitor_scale_factor`
```bash
cracs@ddmstat:~$ readelf -s -W /usr/lib/x86_64-linux-gnu/libgdk-3.so | grep gdk_screen_get_monitor
   604: 0000000000028d60   196 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_plug_name
   680: 0000000000028e30   185 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_geometry
   692: 0000000000029000   315 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_at_window
   716: 0000000000028ba0   223 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_width_mm
   869: 0000000000028c80   223 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_height_mm
  1070: 0000000000029140   233 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_at_point
  1134: 0000000000029230   185 FUNC    GLOBAL DEFAULT   11 gdk_screen_get_monitor_workarea
```

**Comment by ltilve** [comment]
ftr, on my Debian env seems to be correct: 
```bash
$ readelf -s -W /usr/lib/x86_64-linux-gnu/libgdk-3.so | grep gdk_screen_get_monitor_scale
  1097: 00000000000436f0   268 FUNC    GLOBAL DEFAULT   12 gdk_screen_get_monitor_scale_factor
```

**Comment by cronacronis** [comment]
@ltilve what is the version of `libgtk-3-dev` you have installed? (`$ aptitude versions ~ilibgtk-3-dev`)

**Comment by ltilve** [comment]
It's the `3.22.17-1` from debian testing

**Comment by hferreiro** [comment]
The oldest Ubuntu version supported by Chromium is 14.04. Commit https://chromium.googlesource.com/chromium/src.git/+/b50cab37a165f1f11d9a046d7f3367e4a563a73f
 introduced a dependency on gtk+ 3.9.10 which isn't available in Ubuntu 12.04.

**Comment by cronacronis** [comment]
@hferreiro thanks for the information
@bsclifton who can be responsible to add  the requirement in the deb file for `libgtk` to be at least `3.9.10`?

**Comment by bsclifton** [comment]
@posix4e would you be able to help me update the requirements (per the above)? 😄

**Comment by posix4e** [comment]
Yea that should be fine. I'll try to get to it soon.
