### ISSUE TITLE
Fix the wrong spacing around the per cent number on ledger panel

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10356]
**Describe the issue you encountered:** Polish pinnedInput.js

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Run `npm run add-simulated-synopsis-visits 100`
    2. Open about:preferences#payments
    3. Pin some sites
    
- Actual result:
  <img width="189" alt="screenshot 2017-08-09 18 48 31" src="https://user-images.githubusercontent.com/3362943/29115672-61a069be-7d33-11e7-9a76-eb0e52801291.png">

- Expected result: the padding and margin around the input area should be normalized.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
note: the styles such as `padding` will be normalized later after https://github.com/brave/browser-laptop/pull/10265 is merged. The styles are scattered everywhere, not only less files which will be converted later but files which have already been converted eg `ledgerTable.js`, which is why some styles are just redundant, creating table layout inconsistency. cc: @cezaraugusto, related: #9032

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
