### ISSUE TITLE
Split navigator in smaller components

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10354]
## Test plan

https://github.com/brave/browser-laptop/pull/10355#issue-248977058

----

**Describe the issue you encountered:**
Split navigator and navigationBar into:
- bookmarkButton
- homeButton
- reloadButton
- stopButton
- forwardButton
- backButton

for #9283

**Comment by srirambv** [comment]
Reload button doesn't work. Removing Linux check to be retested with 0.20.8
![reload](https://user-images.githubusercontent.com/17010094/34256488-7c6a584e-e64d-11e7-882d-c52a50cf04ca.gif)

**Comment by LaurenWags** [comment]
Reproduced on MacOS.

**Comment by NejcZdovc** [comment]
I tried to reproduce this on brach 0.20 but without any luck. @bsclifton could this be happening only on the build?

**Comment by bsclifton** [comment]
Component is working as expected, but while debugging @NejcZdovc and I discovered root cause. Opening a new issue to track that (all reloads are affected, and more)
