### ISSUE TITLE
Increase Padding on Pinned Tabs

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10368]
## Test plan

https://github.com/brave/browser-laptop/pull/10533#issue-250567316

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pinned tabs would benefit from better UI/UX with greater lateral padding. See [this tweet](https://twitter.com/orangefallz/status/895322726436528133) by a Brave user.

If this request is implemented, we should probably consider the UI/UX of narrow tabs in general. A cursory glance at the current implementation reveals that pinned tabs, and standard narrow tabs, are displayed differently.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
N/A

- Steps to reproduce:
    1. Create a pinned tab
    
- Actual result:
Padding is tight, at `2px`.

- Expected result:
More lateral padding (perhaps `5px`?)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
(Top: Safari, Bottom: Brave)
![image](https://user-images.githubusercontent.com/815158/29134891-e164cbf8-7cfd-11e7-8b48-e71a75d32d9b.png)

**Comment by cezaraugusto** [comment]
+1
