### ISSUE TITLE
0.18.20: Open link in new window is broken

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10376]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Opening a link in a new window, manually with Open Link in New Window or automatically with `target=_blank`, is broken in 0.18.20. I think this is related to #10371.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.18.20 (60bb9e6)

- Steps to reproduce:
    1. Open Brave.
    2. Go to https://github.com/brave/browser-laptop
    3. Right click the Brave link at the top.
    4. Select Open Link in New Window.
    
- Actual result:
A new window with a new, blank tab appears.

- Expected result:
A new window with the linked page should appear.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

- Any related issues:
#10371

**Comment by bsclifton** [comment]
I believe this is the same root cause as https://github.com/brave/browser-laptop/issues/10365
