### ISSUE TITLE
Brave does not show anything on page https://www.coinjar.com/

### ISSUE THREAD

**Issue by el-gallo-azul** [brave/browser-laptop#10379]
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
I am trying to start using Brave as my default browser. I was prompted to start a Brave Wallet, which I think is a good idea, so I decided to start a Brave Wallet. On the pop-out dialog box "Three ways to add funds to your Brave Wallet", I chose the first option "Buy Bitcoin at our recommended source" and clicked the button "CoinJar". A new tab opened for URL https://www.coinjar.com/, but the page is blank (see screenshot http://imgur.com/jOCWVJE).

- Platform (Win7, 8, 10? macOS? Linux distro?):

Ubuntu 16.04.3

- Brave Version (revision SHA):

Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

This software uses libraries from the FFmpeg project under the LGPLv2.1

- Steps to reproduce:
    1. Turn Brave Payments "on"
    2. Click "Add funds"
    3. Click "CoinJar"
    
- Actual result:

http://imgur.com/jOCWVJE (from Brave)

- Expected result:

http://imgur.com/9IaMCja (from Google Chromium)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

I suspect so.

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

I don't know

- Extra QA steps:
    1. Nothing to suggest
    2.
    3.

- Screenshot if needed:

As above

- Any related issues:

None

**Comment by luixxiul** [comment]
note: if you open https://www.coinjar.com/ directly from the link, the page is rendered.

**Comment by NejcZdovc** [comment]
this is not a case anymore, because we implemented BAT
