### ISSUE TITLE
after close/reopen, pinned tab is duplicated as normal tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10374]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After pinning a tab, closing/reopening Brave, my pinned tab is duplicated as a regular tab. Subsequent close/reopen of Brave results in another (regular) tab added each time for the pinned tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.20
rev | 60bb9e6
Muon | 4.3.9

- Steps to reproduce:
    1. Start with a clean profile/install of 0.18.20.
    2. Open a new tab, visit a site.
    3. Open another new tab, visit a different site.
    4. Nav back to the site from step 2. Pin this tab.
    5. Close/Reopen Brave.
    6. Pinned site remains, but it also displays as a regular tab.

    
- Actual result:
Pinned tab displays as pinned tab and regular tab. Additionally, if you continue to close/reopen Brave each time a new (regular) tab will be added with the site from the pinned tab.

- Expected result:
No duplicate tabs should be opened, just the pinned tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![dup_tab2](https://user-images.githubusercontent.com/28145373/29140569-e895d1f4-7d18-11e7-8b2e-b3619371d57b.gif)

- Any related issues:
Possibly https://github.com/brave/browser-laptop/issues/10179

**Comment by bsclifton** [comment]
I confirmed this is caused by https://github.com/brave/browser-laptop/commit/cccb3dd489907ca83cbdb10c4a55bf6221b85f62

Looking into a fix...

**Comment by luixxiul** [comment]
I noticed a similar issue, where you get duplicate pinned tabs when you open a link in a new tab. Is this also caused by the same commit?

**Comment by bbondy** [comment]
master: e3e285587d9d4a0692c39b3f75fc167f5f8a8309
0.20.x: c5c37873b46fcff022fc5463e26198b4ee3464cf
0.19.x: beac410f0e07f862daf5fb057f577757effacbdf
0.18.x: 3f21513721c7b818e603798f82955772832dd519
