### ISSUE TITLE
Pop-ups showing pinned sites

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#1037]
When I click in a pop-up like a chat, it opens other windows with my pinned sites too, not only the pop-up...

**Comment by Kzeir** [comment]
![xxxxxxxxxxxxxxxxxxxxxxxxxxxxx](https://cloud.githubusercontent.com/assets/17557010/13607299/3786c194-e52e-11e5-9817-11574f7d7beb.png)

**Comment by diracdeltas** [comment]
This also happens for login popups, preventing the popup from auto-closing.

**Comment by bbondy** [comment]
Fixed here but also requires a patch to Electron that @bridiver is doing.
BrianJ please resolve this with reference to the commit when you're done. Thanks!
https://github.com/brave/browser-laptop/issues/626

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/24a1b0e5c417884c65e1c338ab104545e367ca72
https://github.com/brave/electron/commit/8419f1d2edc233278a5d4e514b0d84ff43047e81
