### ISSUE TITLE
bookmark name updates when you View Page Source

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10372]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When you 'View Page Source' for a bookmarked page, the bookmark name updates to be view-source:<URL> 

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.20
rev | 60bb9e6
Muon | 4.3.9

- Steps to reproduce:
    1. Navigate to a non-bookmarked page.
    2. Bookmark the page to the Bookmark Toolbar.
    3. Right click on the page and select 'View Page Source'
    
- Actual result:
Bookmark name updates to be view-source:<URL>

- Expected result:
Bookmark name should not update.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

![screen shot 2017-08-09 at 2 18 11 pm](https://user-images.githubusercontent.com/28145373/29137558-b9a52534-7d0e-11e7-9da1-594933322cdc.png)

- Any related issues:

**Comment by luixxiul** [comment]
@NejcZdovc was this fixed with the split PR you merged recently?

**Comment by NejcZdovc** [comment]
Yeah please test this on the latest master

**Comment by bsclifton** [comment]
Closing this out since it was fixed in master with site splitting

Please re-open if the issue still happens in master
