### ISSUE TITLE
about: pages are not always being populated

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10384]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Visiting about: pages doesn't always populate the page with the required information/data. This affects almost all of the about: pages including about:bookmarks, about:adblock and about:extensions.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 (10.0.15063) - Can't check other platforms as MBP is currently being repaired

- Brave Version (revision SHA):

> Brave | 0.18.14
> rev | ad92d029e184c4cff01b2e9f4916725ba675e3c8
> Muon | 4.3.6
> libchromiumcontent | 60.0.3112.78

> Brave | 0.18.20
> rev | 60bb9e64f43f1b078e1a3276bfbc3d08125249e5
> Muon | 4.3.9
> libchromiumcontent | 60.0.3112.90

- Steps to reproduce:

  1. Launch a new instance of Brave and load about:brave in the initial tab that's loaded/opened
  2. Open a new tab and close the previous tab that has about:brave currently opened
  3. Load about:brave in the new tab and you'll notice that the page hasn't been populated
  4. Click on the about:brave tab and the page will repopulate correctly

- Actual result:
about: pages are not always being populated when directly visiting them when there's no other tabs opened. 

- Expected result:
about: pages should always be populated the first time around, even when users directly visit them.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, this issue is 100% reproducible with a clean install/profile.

- Is this an issue in the currently released version?
Yes, currently affects 

- Can this issue be consistently reproduced?
Yes, this issue is 100% reproducible.

- Screenshot if needed:

![aboutissue](https://user-images.githubusercontent.com/2602313/29155435-048b7048-7d6a-11e7-8afe-cf76191138ec.gif)

![issue](https://user-images.githubusercontent.com/2602313/29155614-3b8f695e-7d6b-11e7-8c72-6cd69f17e002.PNG)

**Comment by luixxiul** [comment]
I believe this is related with #10370.

**Comment by srirambv** [comment]
Could be similar to the one here (https://github.com/brave/browser-laptop/issues/5712) relating to adblock
