### ISSUE TITLE
Bookmark folder menu not visible on the right side of the browser

### ISSUE THREAD

**Issue by JGH1000** [brave/browser-laptop#10388]
A bit hard for me to take a screenshot but basically when I expand a bookmark folder on the right side of the bookmark bar (close to the window border), most of the menu is not visible - it should be moved to left when it does not fit.

Thank you for looking into this!

**Comment by NejcZdovc** [comment]
@JGH1000 is this the same as #6869?

**Comment by JGH1000** [comment]
Not exactly, but probably related.

![img_20170810_172701614](https://user-images.githubusercontent.com/27884805/29161469-4fb8a158-7df1-11e7-9460-f832a5b570dd.jpg)

**Comment by srirambv** [comment]
This is same as #4745

**Comment by srirambv** [comment]
Closing this as Dupe of #4745 and #5956

**Comment by JGH1000** [comment]
Ah, sorry for not noticing it!

**Comment by srirambv** [comment]
No worries :smile:
