### ISSUE TITLE
Buttons and keys are not aligned properly on wallet backup dialog

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10389]
**Describe the issue you encountered:** Buttons and keys are not aligned properly on wallet backup dialog. This is because the width of the strings are sometimes different though the number of the characters are same.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open about:preferences#payments
    2. Open Brave wallet backup dialog
    
- Actual result:

  <img width="505" alt="screenshot 2017-08-10 17 46 09" src="https://user-images.githubusercontent.com/3362943/29162381-39a3833a-7df4-11e7-9c1d-ca2f4d979719.png">

- Expected result:

  <img width="516" alt="screenshot 2017-08-10 18 26 18" src="https://user-images.githubusercontent.com/3362943/29164117-745c3346-7df9-11e7-88e4-d630176f6b41.png">

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment]
Can the text **Key 1/2** be moved into the button itself? This way you can remove the line break before the key value
![image](https://user-images.githubusercontent.com/17010094/29163080-44444cf2-7db3-11e7-9daa-3589ba0f353a.png)

cc: @bradleyrichter

**Comment by luixxiul** [comment]
I have a fix already and am going to PR :-)

**Comment by luixxiul** [comment]
Moving the label into the button looks a nice idea too!

**Comment by bradleyrichter** [comment]
This should not be happening? Both buttons should be left aligned with strings on the right.

**Comment by luixxiul** [comment]
@bradleyrichter please see #10390 for the change to close this issue. I edited https://github.com/brave/browser-laptop/issues/10389#issuecomment-321496529 to add a screenshot of the modified proposal.

**Comment by bradleyrichter** [comment]
Thanks all!
