### ISSUE TITLE
mobile emulator is absent in brave-laptop that comes in chrome by default in developer tools

### ISSUE THREAD

**Issue by Rafi993** [brave/browser-laptop#10385]
- Did you search for similar issues before submitting this one?
   yes
- Describe the issue you encountered:
    mobile emulator is absent in brave-laptop that comes in chrome by default in developer tools
- Platform (Win7, 8, 10? macOS? Linux distro?): All
- Brave Version (revision SHA):  0.18.20 
- Steps to reproduce:
    1. Open developer tools
    2. the mobile preview icon is absent that is present near the elements tab in chrome
- Actual result:
    the mobile preview icon is absent that is present near the elements tab in chrome
- Expected result:
    Enabling the mobile preview mode
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
   yes
- Is this an issue in the currently released version?
   yes
- Can this issue be consistently reproduced?
  yes
- Screenshot if needed:
   
![data](https://user-images.githubusercontent.com/8092120/29155858-2f43e570-7dbc-11e7-91fd-f89fb5139860.png)

**Comment by luixxiul** [comment]
Hi, thanks for the report. The issue has been reported https://github.com/brave/browser-laptop/issues/7386 and I am going to close this issue in favor of that. Please subscribe it for discussions and announcements.
