### ISSUE TITLE
Changing color of visited hyperlinks

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-laptop#1038]
Comment from Support:

When you are on a web-site, it would be nice if you could turn hyperlinks red if the user has already read them. That makes it easier to scan them for new articles you haven’t seen yet.

Harald H.

**Comment by FrancisTurner** [comment]
This is a dupe of #512  and related to  #505  and #444

**Comment by bbondy** [comment]
Thanks, closing in favour of #512.
