### ISSUE TITLE
Extension API: chrome.runtime.onInstalled

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10399]
https://developer.chrome.com/extensions/runtime#event-onInstalled

Fired when the extension is first installed, when the extension is updated to a new version, and when Chrome is updated to a new version.

Blocks #9531

**Comment by darkdh** [comment]
this has been fix in
https://github.com/brave/muon/commit/8d101b291d9fa19bc90aaf899e6ca5aa64d423e1#diff-de8087233b6a6103f47616e02dcfff1a
and 
https://github.com/brave/muon/commit/ad8523348e6fa9729a5b336050d33db8d022d2ef#diff-de8087233b6a6103f47616e02dcfff1a
