### ISSUE TITLE
feature request: Ability to increase font size and keep it larger. 

### ISSUE THREAD

**Issue by ElissaBeth** [brave/browser-laptop#1039]
feature request: Ability to increase font size and keep it larger.

**Comment by yanterrien** [comment]
I totally agree. The fonts are too small for my old eyes. Please add this feature to the options menu.

**Comment by bbondy** [comment]
We have per site zoom in 0.9.2 but there are a couple more issues with it that will be fixed with 0.9.3.
Global zoom will be handled in https://github.com/brave/browser-laptop/issues/1401

**Comment by GarrettS** [comment]
I am on iPad. How can I adjust the font size of web pages?
