### ISSUE TITLE
Requested to update to preview build when not selected in Prefs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10415]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While checking how an item behaved on 0.18.20, I was prompted to update to 0.18.21 when this preference was not enabled under about:preferences#advanced

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
0.18.20

- Steps to reproduce:
    1. Open 0.18.20 (I used a clean profile)
    2. Navigate around.
    3. Prompt to update was displayed.
    4. Check preferences, verify update to preview builds is not enabled.
    
- Actual result:
Prompted to update

- Expected result:
Since preference was not turned on, should not have been prompted to update.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![update](https://user-images.githubusercontent.com/28145373/29192057-e42b380e-7ded-11e7-828e-1d1ff956ff30.gif)

- Any related issues:

**Comment by srirambv** [comment]
Closing the issue. Need to verify on the next build

**Comment by srirambv** [comment]
Verified no update check done for 0.18.23 from 0.18.22

**Comment by LaurenWags** [comment]
Using 0.18.22, verified was not prompted to update to 0.18.23 on MacOS.
