### ISSUE TITLE
not prompted to restart Brave when changing preferences marked with an asterisk

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10410]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Preferences marked with an asterisk are not prompting for Brave to be restarted. This was working in 0.18.20.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
Brave | 0.18.21
rev | 263b6d5
Muon | 4.3.9

- Steps to reproduce:
    1. In Preferences change language (or any other preference marked with an asterisk)
    2. You are not prompted for restart.

    
- Actual result:
You are not prompted to restart Brave.

- Expected result:
Should be prompted to restart Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No (was last working in 0.18.20)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

Actual:
![language_change](https://user-images.githubusercontent.com/28145373/29187357-6e186f7a-7ddd-11e7-8249-1f4a1e9a660a.gif)

Expected:
![screen shot 2017-08-10 at 3 01 03 pm](https://user-images.githubusercontent.com/28145373/29187362-747cd630-7ddd-11e7-876b-38f7bb9e25df.png)

- Any related issues:

**Comment by Liunkae** [comment]
Same here, with Brave 0.18.21 (263b6d5) on macOS 10.12.x.

**Comment by bbondy** [comment]
getOrigin('about:preferences') would give about:
new:
getOrigin('about:preferences') gives null

And the issue manifests itself inside about:preferences changes when you get a restart notification

```  render () {
  const activeOrigin = getOrigin(this.props.activeFrame.get('location'))
    if (!activeOrigin) {
      return null
    }
...
```

returns null there
