### ISSUE TITLE
0.18.21 Brave fails to remember notification setting

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10413]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
After updating to 0.18.21, Brave didn't remember the 'allow' choice for http://www.bennish.net/web-notifications.html

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version (revision SHA):
0.18.21

- Steps to reproduce:
    1. Visit http://www.bennish.net/web-notifications.html
    2. Make a notification occur
    3. Select to 'allow' and select to 'remember this decision'
    4. Make another notification occur
    5. Observe that the choice notification returns.
    
- Actual result:
The notification to choose is presented

- Expected result:
The choice should be remembered and the notification should not exist.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
Still investigating around this. Will update in just a bit

**Comment by NejcZdovc** [comment]
@alexwykoff is this the same as #10391?

**Comment by alexwykoff** [comment]
ah, dupe it is. that's nuts too because i absolutely used the words 'remember notification' in my title search ☹️

**Comment by luixxiul** [comment]
@alex googling is often better when you search duplicates: `site:github.com/brave/browser-laptop remember notification`
