### ISSUE TITLE
Feature Request- Auto complete url bar

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-laptop#1041]
Support Request:

Please add the feature of auto completeing web addresses in the URL bar.

**Comment by jbshirk** [comment]
I also suggest during history lookup to at least show page title if not whole/more of url. currently it is not possible to know what i am going to land on when typing facebook.com/(and I can't guess the rest.) simple use case: www.wordreference.com - is it going to land on .../en-pt/, /home, /login, etc?

**Comment by luixxiul** [comment]
Duping to #179 and #241
