### ISSUE TITLE
session not being saved during shutdown

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10423]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave is currently not saving sessions on shutdown under Windows. If a user closes Brave before it can autosave the session within the browser (I believe this happens every 5mins), the user will lose all the changes/data that hasn't been autosaved when Brave is closed. Example:

> A new user imports all their bookmarks into Brave and quickly opens several websites. They close Brave before the 5min autosave launches within the browser. The user comes back to the machine, launches Brave and notices that their session hasn't been saved.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 Build: 10.0.15063

- Brave Version (revision SHA):

Brave | 0.18.22
rev | d850e287ace296e2c62e28ba2979cf172e41cc45
Muon | 4.3.9
libchromiumcontent | 60.0.3112.90

- Steps to reproduce:

1. Install & launch a fresh instance of Brave | 0.18.22, rev | d850e287ace296e2c62e28ba2979cf172e41cc45
2. Quickly load several websites in new tabs
3. Quickly import or save several bookmarks
4. Quickly close Brave before the session is saved via the 5min session autosave
5. Re-launch Brave and you'll notice that your session hasn't been saved on shutdown

- Actual result:
Sessions are note being saved during shutdown. If a user closes Brave before the autosave runs, they'll lose some of their changes/data.

- Expected result:
Sessions should always be saved on shutdown.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No, I couldn't reproduce the issue using Brave: 0.18.14 Rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8

- Can this issue be consistently reproduced?
Yes, 100% reproducible using the STR from above.

- Screenshot if needed:

![restoringissue](https://user-images.githubusercontent.com/2602313/29203234-8585ab2c-7e3d-11e7-80b1-918aa6b86266.gif)

Extra QA notes:
https://github.com/brave/browser-laptop/issues/10423#issuecomment-321892963

**Comment by LaurenWags** [comment]
Could not repro on MacOS.

**Comment by LaurenWags** [comment]
Repro'd on Win10 VM.

**Comment by bbondy** [comment]
The same bug causes History -> re-open last closed window to fail as well.
Just noting for the sake of QA.
