### ISSUE TITLE
Autocomplete still shows history entries even after they are cleared

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10421]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If you clear all history with the Clear Browsing Data option, the url-bar autocomplete still shows past history entries. The autocomplete entries are removed when Brave is restarted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.18.21 (263b6d5). I think the problem was introduced sometime in 0.18.x.

- Steps to reproduce:
    1. Go to any site.
    2. Clear the history with Menubar > History > Clear Browsing Data or Preferences > Security > Clear Browsing Data Now
    3. Make sure the Show history matches option is turned on. Preferences > Search > Show history matches
    4. In the url-bar, enter the name of the site that you visited.
    
- Actual result:
The site is shown in the history autocomplete section.

- Expected result:
The site should not be shown since history was cleared.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Not sure.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Go to any site.
    2. Clear the history with Menubar > History > Clear Browsing Data or Preferences > Security > Clear Browsing Data Now
    3. Make sure the Show history matches option is turned on. Preferences > Search > Show history matches
    4. In the url-bar, enter the name of the site that you visited.
    5. Make sure the site is not shown in the autocomplete suggestions.

- Screenshot if needed:
None.

- Any related issues:
None.

**Comment by luixxiul** [comment]
duplicate of #9736?

**Comment by Liunkae** [comment]
@luixxiul Yes, thanks!
