### ISSUE TITLE
Add a remember password feature for basic http auth

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1042]
This should tie into Yan's work.
#370 https://github.com/brave/browser-laptop/commit/0830d6dc615e92cca2f924349ac4613b7073a7cb

**Comment by diracdeltas** [comment]
Yep, I can add this after I open a pull req for remembering page login details

**Comment by luixxiul** [comment]
+1 from https://community.brave.com/t/password-manager-support-for-www-authenticate/7000

**Comment by diracdeltas** [comment]
cc @darkdh - maybe this is easier now that we use chromium's password manager since they are able to fill HTTP Basic Auth passwords

**Comment by bsclifton** [comment]
FIxed with [brave-core](https://github.com/brave/brave-browser)
![screen shot 2018-08-19 at 10 11 57 pm](https://user-images.githubusercontent.com/4733304/44321457-0aea9800-a3fd-11e8-9368-a06d6052bd1e.png)
