### ISSUE TITLE
active tab isn't always maintained on close/reopen

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10433]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Active tab isn't always maintained on close/reopen. This worked in 0.18.19, stopped working in 0.18.20.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
found with Brave | 0.18.22
rev | d850e28
Muon | 4.3.9
Also occurs in 0.18.20, last worked in 0.18.19

- Steps to reproduce:
    1. Clean profile using 0.18.22. Close the welcome tab, but do not close the first tab.
    2. Enter a URL in URL bar for first tab. Open a new tab, enter a new URL. Repeat until you havee 5 different sites open in 5 tabs. 
    3. Leave 5th tab as active tab.
    4. Close/Reopen Brave. Active tab (5th tab) is maintained.
    5. Close/Reopen Brave. Active tab is now the 4th tab.
    6. Close/Reopen Brave. Active tab is now the 3rd tab.
    
- Actual result:
Active tab isn't always maintained.

- Expected result:
Active tab should be maintained.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes, using 0.18.20, 0.18.21, or 0.18.22

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![activetab](https://user-images.githubusercontent.com/28145373/29217028-7e6c5188-7e7e-11e7-9cea-d4328b7b8b24.gif)

- Any related issues:

**Comment by bsclifton** [comment]
I'm having a hard time reproducing this one reliably (doesn't seem to matter whether I run form source or the packaged build)

When I quit the first time after opening tabs, sometimes the focus goes to the wrong tab or to a white page.  If I go and set the focus back to the last tab, it never happens again.

@bbondy did you say this was a Muon issue? Or is this related to the white tab (active tab index) issue you were looking at?

**Comment by bsclifton** [comment]
I'd like to propose pushing this to 0.19.x

**Comment by bbondy** [comment]
I think we should fix since this isn't in the live version, we'd be releasing a worse experience than is available today.

**Comment by bbondy** [comment]
I'm trying the exact steps described as well and am not able to reproduce it with several Quit -> Open attempts.  It always keeps the 5th tab selected for me. 

I tried using the same tab URLs as well that you are using. 

I did notice a strange observation that on the reload attempt every tab that is bigger than the new active tab gets loaded and doesn't stay unloaded.

@LaurenWags any extra steps that would help me reproduce? 
You mentioned it is consistently reproducible, so I think I'm missing something.

**Comment by LaurenWags** [comment]
@bbondy unfortunately nothing additional, it worked with those steps for me 100% of the time. I just pulled down latest 0.18.x and built that, could not repro this issue with it.

**Comment by bbondy** [comment]
@LaurenWags do you mean in the last message that you tried from source and can't repro?
If that's the case can you still repro from 0.18.22?

**Comment by bbondy** [comment]
I'll remove from milestone like @bsclifton suggested until we can confirm if reproducible.

**Comment by LaurenWags** [comment]
@bbondy yes, built from source and couldn't repro. can still repro in 0.18.22 packaged build. tweaked steps in the description slightly to see if that helps.

**Comment by LaurenWags** [comment]
Can't repro in 0.18.23 packaged build.
