### ISSUE TITLE
Suggestion: Allow user to customize bookmark and URL bar placement

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10438]
- Did you search for similar issues before submitting this one?
Yes. Maybe I missed the existing issue.

- Describe the issue you encountered:
From community https://community.brave.com/t/bookmarks-toolbar-placement/5464?u=eljuno

The placement of the bookmarks toolbar. It’s taking up a whole row. Maybe it could go to the right or left of the URL bar.

Chrome, Firefox and Edge all use three rows at the top; one for tabs, one for URL bar, and one for bookmarks bar.  Brave too uses three - but with the excellent shortened URL bar, you could put the URL bar and bookmarks on the same row.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Expected result:
User have an option to costumize bookmark and URL bar placement

- Any related issues:
Maybe #6928

**Comment by luixxiul** [comment]
#2185 #5208
