### ISSUE TITLE
Google Sheets Crash

### ISSUE THREAD

**Issue by rtloeffler** [brave/browser-laptop#10444]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered: Opened Google Sheet that already had data and charts, Crashed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS: 10.12.6 (16G29) 64bit

- Brave Version (revision SHA):
Brave: 0.18.14

- Steps to reproduce:
    1. Open Google Drive
    2. Navigate to a Sheet document that has data and charts
    3. Open document, wait for it to try and load
    
- Actual result:
Crash report that is sent to Google

- Expected result:
Should load the document with multiple tabs

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
should

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps: Console error
```295605113-ritz_waffle_integrated_i18n_core.js:2317 Uncaught 
ldb
jo
:
Error: Module errback failures: CustomError: Error in protected function: Deferred has already fired at https://docs.google.com/static/spreadsheets2/client/js/295605113-ritz_waffle_integrated_i18n_core.js:94:1173 at c (https://docs.google.com/static/spreadsheets2/client/js/295605113-ritz_waffle_integrated_i18n_core.js:2317:94)
message
:
"Error in protected function: Module errback failures: CustomError: Error in protected function: Deferred has already fired"
stack
:
"Error: Module errback failures: CustomError: Error in protected function: Deferred has already fired↵    at https://docs.google.com/static/spreadsheets2/client/js/295605113-ritz_waffle_integrated_i18n_core.js:94:1173↵    at c (https://docs.google.com/static/spreadsheets2/client/js/295605113-ritz_waffle_integrated_i18n_core.js:2317:94)"
__proto__
:
Ma```

**Comment by rtloeffler** [comment]
Found a way to get it to work. I had to turn off Fingerprinting Protection and Block Phishing/Malware

**Comment by rtloeffler** [comment]
Found another website where i have to disable both `Fingerprinting` and `Block Phishing`

[https://console.aws.amazon.com/iam/home?region=us-west-2#/security_credential](https://console.aws.amazon.com/iam/home?region=us-west-2#/security_credential)

**Comment by luixxiul** [comment]
Duping to #2343. The issue is tracked on #2965.
