### ISSUE TITLE
Unable to Recover Wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10442]
## Test plan

https://github.com/brave/browser-laptop/pull/10447#issue-249783445

----

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Reported via community: https://community.brave.com/t/can-not-recover-my-wallet/5614

When attempting to enter recovery keys manually and select 'Recover' button or 'Import recovery keys', nothing happens when either button is clicked.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Reported on MacOS 

- Brave Version (revision SHA):
Reported on 0.18.14, reproduced on 0.18.14 and 0.18.22

- Steps to reproduce:
    1. Navigate to about:preferences#payments
    2. If not already on, enable payments.
    3. Open Advanced Settings.
    4. Click on Recover your wallet.
    5. Select Import recovery keys.
    6. Enter keys manually. Select Recover.
    
- Actual result:
Nothing happens when selecting either Recover or Import recovery keys.

- Expected result:
User should be able to import their keys or enter manually.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/10447

**Comment by luixxiul** [comment]
On Debian the `key 2` is not restored correctly.

STR:
1. `rm -rf ~/.config/brave`
2. Open the browser 
3. Enable Payments
4. Save your Payments backup keys
5. Close the browser
6. `rm -rf ~/.config/brave`
7. Open the browser,
8. Enable Payments
9. Recover your wallet and Import recovery keys
10. Click `Backup your wallet`

Actual result:
![clipboard01](https://user-images.githubusercontent.com/3362943/29369185-dae573ec-82dc-11e7-8999-91ba52c5bf7f.png)

Clicking the second `Copy` button prompts this error on Terminal:
````
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from null
    at EventEmitter.ipcMain.on (/usr/lib/brave/resources/app.asar/app/index.js:255:26)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/lib/brave/resources/electron.asar/browser/api/web-contents.js:182:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
````

**Comment by luixxiul** [comment]
I reopened the issue but if that is a different issue, please let me know. I'll open another one for that.

**Comment by LaurenWags** [comment]
@luixxiul same as https://github.com/brave/browser-laptop/issues/9740 ?

**Comment by luixxiul** [comment]
It looks so, but I'm not sure if the log for that issue is not present.

**Comment by bsclifton** [comment]
Closing because the original reported issue was fixed.  You can recover your wallet.  I'll add notes from above to https://github.com/brave/browser-laptop/issues/9740
