### ISSUE TITLE
Brave prompts to create new keychain named "Default Keychain"

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#10448]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:

With the [recent muon change to encrypt cookie data at rest](https://github.com/brave/muon/pull/262), Brave now has a hard dependency on gnome-keyring on linux (before it was only needed if you opted to use the builtin password manager). As a result, if you do not already have a keychain, Brave will prompt you to create a new one. I cannot confirm, but I would imagine that if there is an existing keychain, the user would be prompted to allow access. If possible we should use a keychain name that better indicates why Brave is asking for keychain access.

Furthermore, despite being used to protect user data - having to allow keychain access will be seen by some users as concerning. Some users will want a way to stop all requests for keychain access.

See a similar discussion about Chrome asking for access:
https://productforums.google.com/forum/#!topic/chrome/BPLVDSeTmgI

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux

- Brave Version (revision SHA):
0.19.2

- Screenshot if needed:
![keychain](https://user-images.githubusercontent.com/8796196/29239183-758f84ea-7f37-11e7-8b94-0ecfe11f2db1.png)

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by darkdh** [comment]
libgnome-keyring is almost deprecated by libsecret
https://bugs.chromium.org/p/chromium/issues/detail?id=466975

**Comment by luixxiul** [comment]
Is it OK to close this?

**Comment by darkdh** [comment]
need investigation, I will check with @evq
