### ISSUE TITLE
Suggestion: allow custom research parameters

### ISSUE THREAD

**Issue by Caspian1892** [brave/browser-laptop#10446]
Did you search for similar issues before submitting this one?
Yes !

Describe the issue you encountered:
I have check the different keys that we can use in the url address bar. It works fine, and it is a pleasure to use it. However, I didn't find a way to use custom research parameters.
Can we do this or not ?
I check in parameters -> research parameters, but there is no way to add new one.
It a pity that I can't do that, because it could be very useful...

**Comment by luixxiul** [comment]
Hi, the suggestion is tracked https://github.com/brave/browser-laptop/issues/3053. Please subscribe it for future discussions/announcements, thanks!
