### ISSUE TITLE
Suggestion: add a session manager

### ISSUE THREAD

**Issue by JIVS** [brave/browser-laptop#10453]
I would suggest this feature to be built-in into Brave in the future

As for layout and functionality I think the Session Buddy extension for Chromium browsers is a good example of a session manager done right

Session sync would be a good feature too

**Comment by Liunkae** [comment]
Related: #5388 (Create about:sessions for session-management)

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/5388
