### ISSUE TITLE
[BUG] New window not full screen

### ISSUE THREAD

**Issue by theriverman** [brave/browser-laptop#10455]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When I open a new Brave window (doesn't matter if Brave's already running or now), it starts in non-full screen mode and and the full windows is a little bit off-screen to the left. (see attachment)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10
- Brave Version (revision SHA):

Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.16257 
OS Architecture: x64

- Steps to reproduce:
    1. Open Brave
    2. Maximize the windows
    3. Press Ctrl+N
    
- Actual result:
New window opens, but not full screen

- Expected result:
New windows is supposed to open full screen because the `parent window` is full screen too.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Hopefully yes.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes 

- Extra QA steps:
    1. -
    2. - 
    3. -

- Screenshot if needed:
 See attached 
- Any related issues:
Nada
![brave_bug](https://user-images.githubusercontent.com/22156894/29248336-c5074812-8015-11e7-9cc7-fb48073109d0.png)

**Comment by NejcZdovc** [comment]
@theriverman thank you for reporting it. We already have a tracking issue for that #8600, so I will close this as a dupe. I am already working on a solution, so it should be fixed in 0.20 release
