### ISSUE TITLE
hide page load time info in Address Bar below 600px window width

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1046]
Let's keep things tidy in the URL bar when editing, and previewing mobile responsive sizes...

![screen shot 2016-03-09 at 9 26 23 am](https://cloud.githubusercontent.com/assets/13509546/13644239/9306a448-e5d9-11e5-91c3-2572ef446225.png)

**Comment by luixxiul** [comment]
Partially addressed #2045

**Comment by bsclifton** [comment]
PR submitted- not required for 0.12.3, but I was already in there :smile:
