### ISSUE TITLE
Civic authentication does not work in Brave

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#10469]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicked on "Civic Sign in"

I got "It seems there was an issue processing your request.
Please press retry so we can do this again."
 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS 10.12

- Brave Version (revision SHA):
0.18.14
ad92d02

- Steps to reproduce:
    1.  Go to https://bnktothefuture.com/users/sign_in#
    2.  Click  "Civic Sign in"
    
- Actual result:
"It seems there was an issue processing your request.
Please press retry so we can do this again."

- Expected result:
QR code to be displayed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by luixxiul** [comment]
You can display the QR code by enabling the 3rd party cookie.

CC @BrendanEich @lukemulks

**Comment by kjozwiak** [comment]
@patrick99e99 I managed to create a new account and login using the default shield settings without any issues using `0.22.727` which is the latest release. I also managed to enable 2FA using the QR code and then login once again using 2FA.

Mind checking again and see if you're still having an issue logging in using the latest release?

**Comment by bsclifton** [comment]
Seems to work great for me too - we've had various updates and changes to the default settings which could have fixed this
