### ISSUE TITLE
Description for Session Tab on Hover

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10464]
- Did you search for similar issues before submitting this one?
No.

- Describe the issue you encountered:
Description tooltip when hovering on session tab have tofu and description not show properly.
See screenshot and record for better explanation.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 8.1 

- Brave Version (revision SHA):
0.18.14 (ad92d02)

- Steps to reproduce:
    1. Set to 20 tab per tab set on about:preferences#tabs
    2. Create session tab,
    3. Hover to "person icon"
    
- Actual result:
See screenshot 

- Expected result:
description show correctly like this one (from clicking lock icon on URL bar)
![image](https://user-images.githubusercontent.com/25360853/29253302-f3d0ce9c-80a2-11e7-9f90-0d409687b880.png)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-session-tab-description](https://user-images.githubusercontent.com/25360853/29253262-44e031c0-80a2-11e7-93ca-8d2332ded937.png)

![brave-session-tab-description](https://user-images.githubusercontent.com/25360853/29253267-502cb1d4-80a2-11e7-8690-ddc927b1830a.gif)

- Any related issues:

**Comment by Liunkae** [comment]
Looks like the variable `partitionNumber` is not being substituted properly either.

Also, that tooltip is not shown unless the tabs are small enough to hide the close button. Might be a usability problem.

**Comment by cezaraugusto** [comment]
setting to sprint/1 and tagging for 0.20.x as this will be fixed by #10691 cc @zentagonist
