### ISSUE TITLE
Tearing off tab leaves blank window

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10467]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If you tear off a tab, the previous window is left blank.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.18.22 (d850e28)

- Steps to reproduce:
    1. Open a new window.
    2. Navigate to any website (e.g. brave.com).
    3. Open a new tab.
    4. Navigate to another website (e.g. github.com).
    5. Tear off the second tab.
    6. Close the new window with the second tab.

- Actual result:
The original window is blank.

- Expected result:
The original window should have the content of the first tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Probably.

- Is this an issue in the currently released version?
Not sure.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a new window.
    2. Navigate to any website (e.g. brave.com).
    3. Open a new tab.
    4. Navigate to another website (e.g. github.com).
    5. Tear off the second tab.
    6. Close the new window with the second tab.
    7. Make sure the original window has the content of the first tab.

- Screenshot if needed:
None.

- Any related issues:
Maybe #9083

**Comment by srirambv** [comment]
Same as #9671?

**Comment by Liunkae** [comment]
Yes, thanks!
