### ISSUE TITLE
CanvasRenderingContext2D#measureText returns undefined 100% of the time

### ISSUE THREAD

**Issue by bdsomer** [brave/browser-laptop#10461]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
[`measureText`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) always returns `undefined`.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.6
- Brave Version (revision SHA):
ad92d029e184c4cff01b2e9f4916725ba675e3c8
- Steps to reproduce:
    1. Run the [`measureText`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText) on a [`CanvasRenderingContext2D`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) object
    2. It will return `undefined`, unexpectedly
    
- Actual result:
Returns `undefined`
- Expected result:
Returns a [`TextMetrics`](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics) object
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
did you turn off fingerprinting protection?

**Comment by bdsomer** [comment]
@luixxiul Of course! Thanks. 🎉
