### ISSUE TITLE
Confusing tab colours

### ISSUE THREAD

**Issue by JaneSmith** [brave/browser-laptop#10462]
I'm running Brave 0.18.14 on Windows 10. I'm quite confused by the tab colours though, and can't seem to find any meaning or pattern behind them. Sometimes the tabs are white, sometimes blue, sometimes red, sometimes black.

At first I thought that red tabs had something to do with media playing on the tab, as YouTube tabs are red. However, tabs on the Blender StackExchange site are also red, and there is no media there...

I also thought that maybe it's based on the favicon colour, but that doesn't seem quite right too, as it isn't always the case. I also thought that maybe it's based on the background colour of the web page, but that also doesn't seem right, as it sometimes matches and sometimes doesn't. Either way, having the tab colour based on the page style doesn't seem to make any sense, so that can't be it...

I find this very confusing. Is there a list somewhere of what each tab colour means? Or is there some kind of bug causing them to have random colours?

**Comment by bsclifton** [comment]
Hi there @JaneSmith 😄 

The colors you're seeing on tabs are an attempt to make the tab blend in with the top of the page.  I believe it's calculated by averaging the colors found in the favicon

You can disable this behavior by opening Preferences > Tabs and disabling "Show tabs in page theme color"
