### ISSUE TITLE
Multi selecting tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10471]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Couple of requests from community users for allowing selecting multiple tabs.
https://community.brave.com/t/use-good-features-from-other-browsers-e-g-reading-list-and-draw-from-edge-ctrl-and-or-shift-to-select-tabs-bookmark-multiple-tabs-at-once-and-change-the-order-of-bookmarks/4196/3?u=sriram

https://community.brave.com/t/mutli-selecting-tabs/5808

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Stable release

- Steps to reproduce:
    1.  Users should be able to select multiple tabs and perform context menu options 
    2.
    3.
    
- Screenshot if needed:
https://community.brave.com/t/use-good-features-from-other-browsers-e-g-reading-list-and-draw-from-edge-ctrl-and-or-shift-to-select-tabs-bookmark-multiple-tabs-at-once-and-change-the-order-of-bookmarks/4196/3?u=sriram

- Any related issues:
cc: @bradleyrichter

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/select-move-close-and-pin-multiple-tabs/28731?u=eljuno

> Please implement the ability to select, move and close multiple tabs using SHIFT + click - as you can with Google Chrome.

Also, fixed with rave-core? :smile:

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/multiple-tabs-selection-to-separate-into-new-window/28909?u=eljuno

**Comment by tomlowenthal** [comment]
I'm pretty sure this works out of the box in Brave Core.

**Comment by bsclifton** [comment]
I confirmed this does indeed work in [Brave Core](https://github.com/brave/brave-browser) 😄
