### ISSUE TITLE
Can't create folder when selecting the download folder

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#10479]
Brave: 0.18.14 
rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64

--

When selecting Downloads folder at about:preferences#general, there isn't option to create a new folder in case I need one.

<img width="735" alt="screen shot 2017-08-14 at 21 44 43" src="https://user-images.githubusercontent.com/266306/29290991-fa1d3bcc-8139-11e7-8834-e045103501f4.png">

As a workaround, I need to create one manually by opening _Finder_.

I've checked with Chrome, and I can create the folder there when selecting the folder.

**Comment by Liunkae** [comment]
QA steps:

**Note: macOS-only**

1. Open about:preferences > General tab.
2. Under "Save my downloads here:", click the path field or the pencil icon.
3. Make sure there is a "New Folder" button at the bottom left (see screenshot).
