### ISSUE TITLE
WhatsApp favicon displays generic favicon, not site specific favicon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10476]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
WhatsApp favicon doesn't display in Brave but does display in other browsers such as Chrome and Firefox.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
0.18.22

- Steps to reproduce:
    1. Navigate to web.whatsapp.com
    2.
    3.
    
- Actual result:
Generic favicon displayed on tab.

- Expected result:
Site specific favicon displayed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. If you put the shields down for the site the expected favicon flashes, but changes to the generic one.    
    2. 
    3.

- Screenshot if needed:
Actual:
![screen shot 2017-08-14 at 9 54 19 am](https://user-images.githubusercontent.com/28145373/29274663-9464e900-80d6-11e7-96d6-bab6089e9c50.png)

Expected:
<img width="117" alt="screen shot 2017-08-14 at 9 55 24 am" src="https://user-images.githubusercontent.com/28145373/29274715-b7529bec-80d6-11e7-8550-d21ed3f74cbe.png">

![favicon](https://user-images.githubusercontent.com/28145373/29274889-546ce2d4-80d7-11e7-83c5-3d8f60fcce54.gif)

- Any related issues:

**Comment by zentagonist** [comment]
Additional info - The favicon correctly displays in the tab when browse directly to - https://web.whatsapp.com/favicon.ico. or https://web.whatsapp.com/favicon-64x64.ico.

Other sites appear to have smaller favicon.ico images available. Size at 64px or favicon png support related?

**Comment by luixxiul** [comment]
Favicons are fetched with the code:

https://github.com/brave/browser-laptop/blob/149a9eab775b407369783e50bf8fa196a2b1615e/js/lib/urlutil.js#L338-L349

**Comment by thenets** [comment]
Doesn't work for me. Windows 10.
 
Brave: 0.18.15 
rev: 2ca81b89f24a28b05ff78738e790eec7cee2bbab 
Muon: 4.3.7 

libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

![image](https://user-images.githubusercontent.com/2138276/29284925-ffe7cab8-8102-11e7-9a90-0bfc927fbda6.png)

**Comment by thenets** [comment]
I think the problem is related with JS and the dynamic favicon. In my PC the favicon appear for 0.5s and disappear.

**Comment by thenets** [comment]
Yes. It is. The problem doesn't happen if I disable de JS:

![image](https://user-images.githubusercontent.com/2138276/29285644-82f68d20-8105-11e7-9d0b-f289e242ad62.png)

**Comment by srirambv** [comment]
Similar issue for community.brave.com 
![image](https://user-images.githubusercontent.com/17010094/29304597-b85f711e-8148-11e7-98a5-40655019259d.png)

For Whatsapp, I see an intermittent issue when the page is loaded the icon is shown but when logged in the icon becomes generic

**Comment by nufrifin** [comment]
Hi hi, at first browser displays favicon.ico and that works great:
![favicon](https://user-images.githubusercontent.com/19377887/29318130-ff0aa9b0-818b-11e7-9c65-ab1a200fa572.png)


 But then whatsapp adds 
`<link id="favicon" rel="shortcut icon" href="blob:https://web.whatsapp.com/86458e1f-6542-448a-918d-38d42e3bbdbc" type="image/png"> `
Which resolves to this:
![blob-favicon](https://user-images.githubusercontent.com/19377887/29318143-0e963426-818c-11e7-89a0-5180f1a0cbae.png)

And that browser does not display, replacing it with a default favicon.

**Comment by BenoitZugmeyer** [comment]
Thank your @nufrifin for your investigation, I managed to use it in my little extension, [see here](https://github.com/BenoitZugmeyer/tabcenter-redux/blob/86d077fc47ea2b91054684b4445127d30a82fc1c/src/panel/store.tsx#L84-L95). WhatsApp is using a serviceworker to intercept the `blob:` url, so we have to resolve the URL via an XHR call like you guessed.

This is working nicely, even when the favicon changes (ex: is blinking when you have a new message) :)
