### ISSUE TITLE
pinned tab is not being saved

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10480]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
when closing a window where the pinned tab is the only item, on relaunch the pinned tab is lost and the prior session info is presented

- Platform (Win7, 8, 10? macOS? Linux distro?):
win7 ia-32

- Brave Version (revision SHA):
0.18.22

- Steps to reproduce:
    1. if other tabs are open, reduce to 1 tab
    2. visit a new domain and pin it
    3. close the window
    4 . reopen brave and observe state
    
- Actual result:
the old state is displayed

- Expected result:
the pinned tab should be the only thing displayed in the window

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/10053

**Comment by alexwykoff** [comment]
on os x, the pinned tab is retained, and a totally blank about:newtab is displayed

**Comment by bbondy** [comment]
I think this could be related to https://github.com/brave/browser-laptop/issues/10485

**Comment by bbondy** [comment]
Please re-test with that and re-open if not working.

**Comment by LaurenWags** [comment]
Using 0.18.23 I see same results as this comment: https://github.com/brave/browser-laptop/issues/10480#issuecomment-322332216
