### ISSUE TITLE
Green tick on payments icon disappears by moving to sub level of the verified site

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10484]
**Describe the issue you encountered:**
The green tick on payments icon disappears by moving to sub level of the verified site. Is this intended?

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): 0.18.22

- Steps to reproduce:
    1. Open https://brianbondy.com
    2. Click "Filters"
    
- Actual result: the green tick on the payments icon disappears

- Expected result: ?

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
CC @bradleyrichter

**Comment by alexwykoff** [comment]
"If it qualifies as a part a verified domain, it should have the mark" - @bradleyrichter

**Comment by jasonrsadler** [comment]
@luixxiul , Do you have any more example urls that didn't show verified at sub levels?

**Comment by jasonrsadler** [comment]
The STR should be sufficient. I would test out with other known verified sites as well. One thing to note is that bat-client is putting out 429's - too busy so it could take 60 seconds or more before a verified site gets placed into state.

The brianbondy site was the only site I could reproduce the issue with (that site either preloads on enter or uses historyAPI that doesn't do a full POST or GET)

**Comment by LaurenWags** [comment]
Thanks @jasonrsadler 😄

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
