### ISSUE TITLE
permission prompts should be able to save decisions between restarts

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1049]
Currently it can only save the decision until the browser restarts; would be good to have an option to save the decision on the site persistently. This blocks somewhat on #923 because otherwise the UI to present the 6 different permission options (`[Allow, Deny] * [This time only, Until browser restart, Persistently]`) will be unpleasant.

There also needs to be some sort of UI in `about:preferences` to manage all the site-specific decisions that the user has made. This is also needed for when we have site-specific Bravery settings. Chrome has something like this in chrome://settings -> content settings.
![screen shot 2016-03-09 at 11 36 38 am](https://cloud.githubusercontent.com/assets/549654/13647950/42da166e-e5eb-11e5-8a25-89b8e229e985.png)

**Comment by diracdeltas** [comment]
subticket of #923

**Comment by bbondy** [comment]
Moving to 0.9.1
