### ISSUE TITLE
implement open bookmark folder as a group of tabs

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#1050]
Other browsers offer a feature that makes opening a whole folder of bookmarks a two click operation. Firefox has a "open all in tabs" item visible in the folder view. Chrome and Firefox have an item on the context menu for a folder of bookmarks.

**Comment by asadotzler** [comment]
you could also implement "open in new windows", "open in new private windows" etc. but I'd be satisfied with just the tab solution.

**Comment by bbondy** [comment]
We added the open all tabs functionality via middle click here:
https://github.com/brave/browser-laptop/commit/db7fef00a171e5ea86f8a260164444461cb8a4f8

We should add a context menu here though too.

**Comment by bbondy** [comment]
The above is only in 0.8.1 btw which is in the next release.
