### ISSUE TITLE
Favicons of imported bookmarks on the toolbar are missing

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10503]
**Describe the issue you encountered:**
Favicons of imported bookmarks on the toolbar are missing. So are the title and the URL.

Brave: 0.20.0 
V8: 6.0.286.52 
rev: 46b16c5841988ec98b7ce15a667a0218564c2db2 
Muon: 4.4.7 
OS Release: 16.7.0 
Update Channel: dev 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.90

- Steps to reproduce 1:
    1. Import bookmarks from Safari
    2. Open about:bookmarks
    3. Move `icloud.com` to `Bookmarks Toolbar`
    4. Open about:preferences
    5. Change the favicon setting to `Text and Favicons`
    6. Click `iCloud`
    7. **The favicon is not displayed. The bookmark's URL and title are not populated on the dialog either**
      <img width="403" alt="screenshot 2017-08-15 20 36 05" src="https://user-images.githubusercontent.com/3362943/29314583-893c5b66-81f9-11e7-8892-8182a30b43eb.png">
    1. Input something on the empty fields
    2. Click `Done`
    3. **The bookmark is duplicated**
    4. Click the dupe
    5. **The UI hangs with this error:**
    ````
    bookmarkFoldersState.js:39 Uncaught TypeError: Cannot read property 'toString' of undefined
        at Object.getFolder (bookmarkFoldersState.js:39)
        at Object.findBookmark (bookmarksState.js:56)
        at mergeProps (bookmarkToolbarButton.js:179)
        at buildPropsImpl (reduxComponent.js:14)
        at ReduxComponent.buildProps (reduxComponent.js:88)
        at ReduxComponent.componentWillReceiveProps (reduxComponent.js:74)
        at ReactCompositeComponent.js?d2b3:610
        at measureLifeCyclePerf (ReactCompositeComponent.js?d2b3:75)
        at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js?d2b3:609)
        at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js?d2b3:546)
    assert.js?9281:84 Uncaught AssertionError {name: "AssertionError", message: "state must contain an Immutable.Map of historySites", actual: false, expected: true, operator: "==", …}

    ````

- Any related issues:

**Comment by luixxiul** [comment]
Also the browser cannot be restarted due to the error.

**Comment by NejcZdovc** [comment]
this happens in `Brave: 0.20.0`?

**Comment by luixxiul** [comment]
on the latest master

**Comment by NejcZdovc** [comment]
will add this to 0.21 where we introduce this change

**Comment by luixxiul** [comment]
i confirmed that cannot be repro'd on 0.18.22

**Comment by cezaraugusto** [comment]
ok I followed the same STR being the only change I imported from Chrome instead of Safari. While the main issue persists (no favicon for imported BM), the dialog was properly populated w/o errors. So apart from no favicon, I'm not able to reproduce other errors.

tested in:

* master 327382d1b9b4e37974ee4f57f7d2399cc29b7668
* 0.21.x 27f560b63ccbe67496f9ad3094abe9ab7d160768
* 0.20.x b86fafe5916b9cb0f35454cc776cc769d919d4e2

**Comment by cezaraugusto** [comment]
@luixxiul mind confirming the above pls? If the issue is only w/ favicons I think we can remove the `relase-blocking` label.

**Comment by luixxiul** [comment]
It's been fixed 👍

**Comment by srirambv** [comment]
Verified on Windows. No favicon for imported BM but bookmark hanger is populated
