### ISSUE TITLE
"Search with Google" should be opened in Brave regardless of default browser setting

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#10500]
Brave: 0.18.22 
rev: d850e287ace296e2c62e28ba2979cf172e41cc45 
Muon: 4.3.9 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64

- Steps to reproduce (on macOS):
    1. In the current GitHub page click in the padlock icon, then View Certificate and Details.
    2. Double or triple click on any text to select it, and choose _Search with Google_ from the context menu.
    
- Actual result:

The page is opened in _Safari_. Please note that _Safari_ isn't my default browser, but Chrome is.

- Expected result:

I expect the links are open in Brave.

- Can this issue be consistently reproduced?
Yes.

- Screenshot if needed:

<img width="448" alt="screen shot 2017-08-15 at 12 10 06" src="https://user-images.githubusercontent.com/266306/29313606-e1ac2016-81b2-11e7-861d-8ec170eb4206.png">

https://github.com/brave/browser-laptop/issues/10499

**Comment by bsclifton** [comment]
Closing as `wontfix`; this happens in other browsers too
