### ISSUE TITLE
Suggestion: Update MDN name on Search Setting

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10511]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Just simply because their change the name to MDN Web Docs.
https://twitter.com/MozDevNet/status/872188410420633600

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/25360853/29334840-f7c70282-8232-11e7-9419-7fa9b58d1f03.png)

- Any related issues:

**Comment by NejcZdovc** [comment]
This file is a good staring point :wink:  https://github.com/brave/browser-laptop/blob/master/js/data/searchProviders.js
