### ISSUE TITLE
No welcome page shown for offline installation

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10523]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
No welcome page shown for offline installation

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10

- Steps to reproduce:
    1. Download any 0.18.x packaged build
    2. Go offline and install the setup 
    3. Browser launches, about:welcome is a blank page. 
    
- Actual result:
See screenshot

- Expected result:
Should show about:welcome page even if the machine is offline

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/29351284-0a9560a8-825a-11e7-9352-d44b0099d11f.png)

- Any related issues:
#9423 #7821 
cc: @bradleyrichter @cezaraugusto

**Comment by luixxiul** [comment]
I noticed it as well, although it should not be the high priority issue as you should be online when you downloaded the package and installed it to run the browser. Unless you move the installer via USB stick to the offline computer or disable the internet connection for some reason, this won't be a great issue.

Still I think it would be a good idea to include the about page as a offline page for faster start up with a slow network connection.

**Comment by srirambv** [comment]
> disable the network connection for some reason (which is exceptional because you would not go offline after you downloaded the browser installer; that does not make sense in the real world)

I don't think this is exceptional at all. User can download and decide to install at a later point of time  and may be offline at that time or might have network issues, in which case this becomes a real problem and is not a good first experience. It should not be expected that the user has to be online just because he/she downloaded the setup. I think this should be included in packaged build soon. 

cc: @bradleyrichter for thoughts

**Comment by luixxiul** [comment]
> decide to install at a later point of time and may be offline at that time

I simply could not imagine which situations are common where you would like to install a Internet browser, *being conscious that the network connection is offline..* There could be a person who would install the browser on a train / in a cafe where the Internet connection is not available, and that can be the case here.

Opening the browser for the first time, you would expect something but a white tab would be displayed. The welcome page obviously should be displayed on any case, and I'm not against for it at all.

**Comment by bradleyrichter** [comment]
I think it would be nice to have a solution but lower priority than many other open issues.

**Comment by evq** [comment]
bump! noticed into this when updating in a qubes templatevm (restricted internet access)

**Comment by cezaraugusto** [comment]
is the welcome page hosted as a WP page or just a redirect from another source? we could cache contents w/ a service worker for offline support or maybe just put some message as a fallback in the browser when the page is unavailable.

**Comment by bsclifton** [comment]
@cezaraugusto I think a good solution would be to (during the build process) do a wget for the page and store the HTML in a static location, which would then be accessible once Brave is installed.  We could always fall back to that version if the internet is not available

We should have detection code for network up / network down (originally implemented for use w/ Ledger)

**Comment by srirambv** [comment]
Closing the issue as https://github.com/brave/browser-laptop/issues/12691 got closed as fixed in brave-core https://github.com/brave/brave-core/pull/130#discussion_r193189213
