### ISSUE TITLE
Implement a better about:newtab start page

### ISSUE THREAD

**Issue by bhyde64** [brave/browser-laptop#1052]
Upon opening Brave browser, neither the homepage or my bookmarks come up.The only thing that shows up is a blank new tab.

**Comment by bbondy** [comment]
CC'ing @bradleyrichter for a design of a better newtab page.

**Comment by deacl** [comment]
Yes, please add:
  1. an option to open new tab page to homepage.
  2. a homepage icon or other method to change the current page to the homepage.

thank you.

**Comment by bbondy** [comment]
duping to https://github.com/brave/browser-laptop/issues/3001
