### ISSUE TITLE
Allow for custom labels for sessions instead of numbers

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10539]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When using sessions, just using numbers is not as obvious as a name or label.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.21.0

**Comment by alexwykoff** [comment]
@bradleyrichter is going to hunt for the dupe 📦

**Comment by bsclifton** [comment]
related: 
the interface for session tabs is awkward #7783
Session tabs grouped by color. #5643
Create about:sessions for session-management #5388
Context menu to open in session tab: X for all available sessions #788

**Comment by eljuno** [comment]
+1 from community about ability to set a custom name for session tab https://community.brave.com/t/session-tabs-names-and-color/11974?u=eljuno

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/34
