### ISSUE TITLE
notification setting is retained w/o checking 'remember this decision'

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10537]
**Describe the issue you encountered:** notification setting is retained w/o checking 'remember this decision'. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

- Steps to reproduce:
    1. Open https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
    2. Click `Show my location` button
    3. Click `Deny` on the notification bar
    4. Click `Show my location` button again
    
- Actual result: Location is not detected

- Expected result: The setting should not be retained. Location should be detected

- Screenshot if needed:

- Any related issues: #10391

**Comment by bsclifton** [comment]
This behavior already exists- you have to reload the page in order to get prompted again.  I'm going to remove milestone

**Comment by luixxiul** [comment]
> This behavior already exists- you have to reload the page in order to get prompted again

my muscle memory says no :-/ CC @alexwykoff @srirambv

**Comment by srirambv** [comment]
Unfortunately yes, this behavior is what it has always been there. I remember there was a discussion to change the behaviour from reloading the page each time when #5197 was logged but it hasn't been implemented yet. Same goes for deny full screen (#3887,#4574) access where the page becomes useless (scroll) unless the page is reloaded.

**Comment by luixxiul** [comment]
so basically is this behavior what should actually be?

**Comment by srirambv** [comment]
Yes . But this behaviour has to be changed. Page reload should not be mandatory to get the prompt again

**Comment by bsclifton** [comment]
Definitely needs to be fixed- thanks for capturing @luixxiul 😄  But yeah... per the above, it has always been this way (so it's not a regression)
