### ISSUE TITLE
Tabs cannot be muted via speaker icon

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10544]
**Describe the issue you encountered:**
Tabs cannot be muted via speaker icon. That icon does not work.
 
Brave: 0.20.0 
V8: 6.0.286.52 
rev: 3e8c8dd696bc8586c4631168ba649f26857fb564 
Muon: 4.4.7 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.90

- Steps to reproduce:
    1. Open https://www.youtube.com/watch?v=kLiLOkzLetE
    2. Click the speaker icon
    
- Actual result: it does not work, while `Mute` on the tab's context menu works

- Expected result: it should work

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by alexwykoff** [comment]
@alexwykoff double-check that options work in 0.19

**Comment by kjozwiak** [comment]
Only reproducible using `0.20.x`. I couldn't reproduce the issue using ` 0.18.23` and ` 0.19.3`.

The following commit has caused the regression:

> commit 33c7dab003469d0fdd9a4ed09a921c5ca9259a44
> Author: Brian Clifton <brian@clifton.me>
> Date:   Mon Aug 14 23:21:16 2017 -0700
> 
>     Merge pull request #9887 from brave/tabsbar--preview-timing
> 
>     make tab previews based on mouse idle time

**Results:**

> Brave 0.20.0 rev | 33c7dab003469d0fdd9a4ed09a921c5ca9259a44 - _**100% Reproducible**_
> Muon 4.4.7
> libchromiumcontent 60.0.3112.90

> Brave 0.19.3 rev | 053c863b789c864bc83782520818ae91e4b7df49 - _**Couldn't reproduce**_
> Muon 4.4.9
> libchromiumcontent 60.0.3112.101

> Brave 0.18.23rev | 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 - _**Couldn't reproduce**_
> Muon 4.3.10
> libchromiumcontent 60.0.3112.90
