### ISSUE TITLE
Mute on tab's context menu should change to Unmute before switching tabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10545]
## Test plan
  1. Open https://www.youtube.com/watch?v=kLiLOkzLetE
  2. `Mute` via context menu
  3. Display the context menu again
  4. Menu should now properly show `Unmute`

## Original issue description
**Describe the issue you encountered:** `Mute` on tab's context menu should change to `Unmute` before switching tabs.

Brave: 0.20.0 
V8: 6.0.286.52 
rev: 3e8c8dd696bc8586c4631168ba649f26857fb564 
Muon: 4.4.7 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.90

- Steps to reproduce:
    1. Open https://www.youtube.com/watch?v=kLiLOkzLetE
    2. `Mute` via context menu
    3. Display the context menu again
    
- Actual result: `Mute` is still there. After switching tabs `Mute` is changed to `Unmute`.

- Expected result: It should have been changed to `Unmute` before switching the tab.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
+1 from @TheCNixon via https://github.com/brave/browser-laptop/issues/11849
> there was no option to umute and if I clicked mute tab again it wouldn't unmute.

**Comment by bsclifton** [comment]
@NejcZdovc we can recheck this after https://github.com/brave/browser-laptop/issues/12375 is fixed

**Comment by bsclifton** [comment]
May not be new- could be in 0.19.x
