### ISSUE TITLE
Allow for easy profile switching

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10542]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
QA and general users who share machines would both benefit from profile switch capability.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.21.0

**Comment by bsclifton** [comment]
@alexwykoff is this a duplicate of https://github.com/brave/browser-laptop/issues/10324 ?

**Comment by alexwykoff** [comment]
"Let's pony up and do it right" - @bradleyrichter

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/10324

**Comment by dausoc** [comment]
good
