### ISSUE TITLE
Pocket Options tab name mentions Chrome

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10549]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you open Pocket options (chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/options/options.html), tab name says 'Pocket for Chrome Options'.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. Have Pocket enabled/be logged into Pocket.
    2. Open new tab and enter URL: chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/options/options.html
    3. Note tab name.
    
- Actual result:
Tab name mentions chrome.

- Expected result:
Tab name would not mention chrome

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Have Pocket enabled/be logged into Pocket.
    2. Navigate to an article you wish to save.
    3. Select the pocket icon.
    4. When you get the confirmation popup, click on the three dots ( ... ) and select Settings.
    5. This brings up the URL from description and you can see the tab name.

- Screenshot if needed:
![screen shot 2017-08-16 at 4 23 31 pm](https://user-images.githubusercontent.com/28145373/29383876-08e8e3c4-82a0-11e7-80af-9e8311f40c01.png)

- Any related issues:

cc: @jonathansampson @kevinlawler

**Comment by bsclifton** [comment]
Looks like this is no longer an issue - verified using brave-core
![screen shot 2018-08-24 at 1 05 03 am](https://user-images.githubusercontent.com/4733304/44572776-c3844480-a739-11e8-9f97-3055bd63a25c.png)
