### ISSUE TITLE
Request: Option to hide download bar

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#10548]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
From community https://community.brave.com/t/let-me-permanently-hide-download-bar/5906?u=eljuno
>I’d like to be able to just turn it off so it doesn’t pop up and obscure the bottom of the screen when I download something.

Additional info from reporter:
If I remember correctly Internet Explorer/Edge auto-hides the download bar once the download is completed and Firefox doesn’t use a download bar at all, they have an icon in the menu bar and the download menu remains hidden unless you open it manually.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/download-pop-up-bar-at-bottom-of-screen/6427?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/download-bar-options/8364?u=eljuno
> I get weirded out when things pop up on my screen, aka the downloads bar at the bottom. I should be able to disable that in some fashion IMO.

**Comment by bsclifton** [comment]
Note: work was done for this with https://github.com/brave/browser-laptop/pull/11547, but the PR was closed. The commit can easily cherry-picked for folks wanting to solve this one (just needs some additional testing)

Moving to backlog

**Comment by skotzko** [comment]
_1

**Comment by srirambv** [comment]
This will be an out-of-the-box feature on brave-core. Closing as wont fix 😄

**Comment by Rencer** [comment]
This is the reason why I UNINSTALL BRAVE RIGHT NOW! Superannoying impossibly huge download bar that there is no option to disable permanently. The first thing is there ar no real fullscreen. And other things like Brave doesn't give a fuck about my settings; they are randomly revert back to default, regardless that is turned on or off. Oh and the built in EU Prebake Cookie Filter NEVER WORK!
2 or 3 days ago there was an updte to Brave (I'm using linux, and it is build from source) but I see NOTHING that changed. I only see that now starting the browser takes MORE TIME than before the update. I cleared everything, so it has nothing to do with cache or anything, it just slowed down, and of course it was slow as hell before the updte! I don't know what are those "high priority requirements" things that you do, but NOT FIXING AT FIRST what makes your browser to be one of the most annoying program that I ever see; those what are real pain in the ass in every second while trying to browse the internet, those that everyone see all the time, and COVERS UP THE MOST OF THE SCREEN...
Have you EVER USED YOUR OWN BROWSERS? I can't believe why is that a fun that when I go to fullscreen, and downlaoding something, those idiot bars LITERALLY covers the THIRD OF THE WHOLE SCREEN! Pffff... Have fun with your...I better not write down what in my mind right now!

**Comment by bsclifton** [comment]
Thanks for the feedback, @Rencer - let's keep things civil here (watch the language, etc).

I assure you, we're not trying to make the experience worse. There are open issues tracking everything that we know is an issue. In your case, you're building from source which means (if you're using master) you're using unreleased code. If you're running from source, you might want to try the `0.22.x` branch (and not master)

I'm not aware of a EU Prebake Cookie Filter? Maybe you can share more information

As for Brave and all other browsers crashing for you, I'm not sure how to respond. Without helpful information like crash details or steps which always produce a crash, there are no actions we can take to solve the issue. It's impossible to take action when the only feedback is "it crashes"
