### ISSUE TITLE
Allow for portable profiles

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10541]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Allowing for relative directory profiles would be useful for QA and certain users.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.21.0

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/2953
