### ISSUE TITLE
Lastpass doesn’t work on Ubisoft Club website 

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#10543]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
From community:
https://community.brave.com/t/bug-lastpass-doesnt-work-on-ubisoft-club-website/5887
- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by thenets** [comment]
https://community.brave.com/t/bug-lastpass-doesnt-work-on-ubisoft-club-website/5887

Brave: 0.18.15 
rev: 2ca81b89f24a28b05ff78738e790eec7cee2bbab 
Muon: 4.3.7 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64
