### ISSUE TITLE
Set brave as default browser

### ISSUE THREAD

**Issue by alex-wilmer** [brave/browser-laptop#1055]
Is it possible to set Brave as my default browser in OSX? Most instructions say to go to Safari and do it from there, but I don't see an option to do so.

<img width="1440" alt="screen shot 2016-03-10 at 5 47 19 pm" src="https://cloud.githubusercontent.com/assets/2880089/13687250/2de880d0-e6e8-11e5-98dc-02f91fc81819.png">

**Comment by bbondy** [comment]
Go to System Preferences, then General, then in the Default web browser section

**Comment by alex-wilmer** [comment]
@bbondy Thanks! <3 Brave. So fast.

**Comment by RemoteCoderz** [comment]
I had an issue where I was using Firefox as a default, and removed/uninstalled it thus going into System Preferences>General>Default Web Browser was blank with a check mark and no other browser option was available including Safari (which you can't remove). To fix this, I was able to install an app called "Choosy" and after doing that Brave showed up as an option and I then set Brave as default and removed Choosy. It's a workaround fix that got me to the above solution.
