### ISSUE TITLE
Mouse4 and mouse5 (previous, forward) not working [Linux]

### ISSUE THREAD

**Issue by RobertLemmens** [brave/browser-laptop#10556]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
None

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux  4.9.40-1-MANJARO

- Brave Version (revision SHA):
Brave | 0.18.14
rev | ad92d02

- Steps to reproduce:
    1. Open brave
    2. Browse to a webpage
    3. Browse to another webpage in the same tab
    4. Press mouse4
    
- Actual result:
Nothing happens

- Expected result:
Return to the previous webpage

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
It was a clean install on my system. this 'might' be a problem related to the install method? I installed it on my system through the AUR (brave-bin) package. I am not familiar with these things so im not sure if that the problem.

- Is this an issue in the currently released version?
I think so.

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
Is this the same issue as reported here: https://github.com/brave/browser-laptop/issues/628 ?

**Comment by RobertLemmens** [comment]
@luixxiul Yes! Im terribly sorry for not searching hard enough! I will divert my attention towards that thread.

**Comment by luixxiul** [comment]
no problem! github search is not as good as other search engines ;-)
