### ISSUE TITLE
--proxy-pac-url option doesn't work

### ISSUE THREAD

**Issue by Ajaja** [brave/browser-laptop#10553]
v.0.18.23
Errorr message: "A mandatory proxy configuration could not be used. Currently this means that a mandatory PAC script could not be fetched, parsed or executed."

Has this feature not been implemented yet?

**Comment by bsclifton** [comment]
We should get support for all the command line options that we don't already support when switching over to [brave-core](https://github.com/brave/brave-browser) 😄
