### ISSUE TITLE
Blocking scripts by default breaks extensions such as Pocket

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10564]
**Describe the issue you encountered:** Recommendations on Pocket not displayed on blocking scripts by default and the list keeps loading.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian, Windows 10

- Brave Version (revision SHA): 0.18.23

- Steps to reproduce:
    1. Open about:preferences#extensions
    2. Enable Pocket
    3. Log in with your account
    4. Open about:preferences#shields
    5. Enable `Block Scripts`
    6. Open twitter.com
    7. Click the Pocket icon
    
- Actual result: the recommendation list keeps loading

- Expected result: a) the list should be displayed regardless of noscript setting or b) if the global noscript setting should be applied to extensions the loading message should be replaced with `loading failed` with a notification message that the noscript setting needs to be enabled to let the extension work properly.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
CC @jonathansampson

**Comment by luixxiul** [comment]
Here is a relevant case on LastPass; 

> I choose to delete all cookies / browser history / etc. when I close my browser. However, everytime I reopen Brave I need to login back to Lastpass with the same two-step verification.

https://community.brave.com/t/lastpass-cookie-exception/2236

It seems that users do not expect that those global options are applied to the extensions.

**Comment by jonathansampson** [comment]
I think this is _by-design_. We warn the user that blocking scripts could break many websites, and that is precisely what we see. Perhaps we should amend the warning to include extensions too?
