### ISSUE TITLE
Bookmarks don't work in certain situation

### ISSUE THREAD

**Issue by plieblang** [brave/browser-laptop#1056]
I have https://github.com/brave/browser-laptop/milestones bookmarked.  If I open the bookmark, click on one of the browser versions to see the list of issues, then click on the bookmark again, the page only refreshes.  The same happens if I go to a specific issue from the list and then click the bookmark.
I have tried this on other sites but haven't found another repeatable example.
Brave 0.8 on Windows 10.

**Comment by bbondy** [comment]
Great find, this has always been around but is just hit more often now that we have bookmarks.
