### ISSUE TITLE
Window menu on session restore doesn't populate for too long

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10568]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you have a lot of windows, each containing a lot of tabs, then you close and open the browser, the Window menu should list everything. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. Open several windows each with several tabs
    2. Close Brave
    3. Open Brave
    4. Goto the Window menu
    5. Leave it open and watch
    
- Actual result:
It takes a long time to populate, and maybe doesn't fully populate.
For Brendan this takes 10-20s on his profile.

- Expected result:
Should restore active tab titles from session storage.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
A fresh profile that you build up several windows from, yes.

- Is this an issue in the currently released version?
Yes 

- Can this issue be consistently reproduced?
Yes

**Comment by zentagonist** [comment]
I am able to reproduce this. Each entry in the 'Window' menu list starts as 'Brave' then is updated to 'about:blank' after a few seconds. Then later as the windows and tabs load the list updates with correct window titles. I didn't notice any missing entries.


Brave | 0.18.29
-- | --
rev | 85f059d
Muon | 4.3.16
libchromiumcontent | 60.0.3112.113
V8 | 6.0.286.56
Node.js | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 16.7.0
OS Architecture | x64

**Comment by alexwykoff** [comment]
@NejcZdovc tested on windows, this is mac only
