### ISSUE TITLE
Permissions get recorded on about:preferences#security without prompt.

### ISSUE THREAD

**Issue by w0ts0n** [brave/browser-laptop#10574]
- Did you search for similar issues before submitting this one?
Yes. (but may have failed at searching)

- Describe the issue you encountered:
No prompt for  ‘accept once’ or ‘accept always’ in private tab on videos, automatically recorded in about:preferences#security

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X
- Brave Version (revision SHA):
0.18.23
rev 36ae2ec

- Steps to reproduce:
    1. Clear "Saved site permissions" or use clean profile.
    2. Open Private tab, open a video site. it will play without prompt
    3. Go to about:preferences#security and the sites will be listed as "Always, allow" 
    
- Actual result:
Auto playing videos in private tab,  about:preferences#security stores as  "Always, allow" 

- Expected result:
Be presented with choice  "Always, allow" or  "Allow, once" and not store website URL in about:preferences#security if selecting "Allow once"

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes. Tried on my machine (non fresh) and a second machine with a fresh profile.

- Is this an issue in the currently released version?
Only tested on 0.18.23

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/9008 (which is fixed in 0.20.x and newer)
