### ISSUE TITLE
Using Alt+Left, toggles menu

### ISSUE THREAD

**Issue by CoalaJoe** [brave/browser-laptop#10571]
- Did you search for similar issues before submitting this one?
Nope

- Describe the issue you encountered:
When going back in history using Alt+Left. The upper menue toggles.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04 with KDE

- Brave Version (revision SHA): 8003c66

- Steps to reproduce:
    1. Use Alt+Left
    
- Actual result:
Goes back in history and toggles menue

- Expected result:
Goes back in history

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I looked into the sourcecode, it seems like the problem lies here: https://github.com/brave/browser-laptop/blob/master/app/renderer/components/main/main.js#L128

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced?
Happens everytime

- Extra QA steps:

- Screenshot if needed:

- Any related issues:

**Comment by eljuno** [comment]
Related to #5775 ?

**Comment by luixxiul** [comment]
Yes, I'm going to close this in favor of #5775. Thanks for the report anyway.
