### ISSUE TITLE
Bug: Sign into Google with 2FA yes/no sign in prompt on phone doesn't work in Brave

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#10579]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Can't sign in with phone yes/no sign in prompt on phone.

Ubuntu Desktop 16.04.3 LTS
Brave 0.18.23

- Steps to reproduce:
    1. Open a new private tab (CTRL+Shift+P)
    2. Sign into google, e.g. by going to inbox.google.com.
    3. On your phone, for the prompt: "Trying to sign in from another computer?"
<insert your email here>," tap yes.
    
- Actual result: The phone says: "sign-in approved", however a pop-up window says: "Try again? Your sign-in attempt timed out. Resend the prompt to sign in again." Resending the prompt, tapping yes, immediately produces the same result. Signing in via 2FA via an authenticator app or SMS works.

- Expected result:

Sign in works when tapping yes.

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

**Comment by luixxiul** [comment]
Thanks for the report. I assume this is a duplicate of https://github.com/brave/browser-laptop/issues/7866, isn't it?

**Comment by jamesray1** [comment]
Whoops, obviously I didn't look carefully enough!

**Comment by luixxiul** [comment]
Nevermind, search engine on GitHub is not as good as Google or DuckDuckGo ;-)

**Comment by jamesray1** [comment]
Haha, yes I will use both in future.

**Comment by jamesray1** [comment]
GitHub, then DuckDuckGo (my default), then Google.
