### ISSUE TITLE
thehill.com is inaccessible

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10586]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When _HTTPS Everywhere_ is enabled, the website thehill.com is inaccessible. The user is instead presented with a `ERR_INSECURE_RESPONSE` response. Attempting to navigate directly to https://thehill.com yields a `ERR_CERT_COMMON_NAME_INVALID` response.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. Type thehill.com into your address bar and press <kbd>Enter</kbd>
    
- Actual result:
Website is inaccessible.

- Expected result:
Website works as expected.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Disabling HTTPS Everywhere resolves

**Comment by jonathansampson** [comment]
@diracdeltas, do we typically just make an exception for HTTPS Everywhere in these cases? Or is there a more scalable approach that we can use to resolve cert-related issues like this?

Chrome presently warns the user that the cert (for a248.e.akamai.net) doesn't match the domain (thehill.com), and allows the user to _Proceed to thehill.com (unsafe)_. This override is buried beneath a toggle, which adds another layer of protection.

Brave should probably also have an _Unsafe_ option for users who wish to proceed in spite of the certificate differences. Thoughts?

**Comment by diracdeltas** [comment]
@jonathansampson basically we manually disable the ruleset for the site and then push an httpse update. https://github.com/brave/https-everywhere-builder

**Comment by diracdeltas** [comment]
Brave does have an option to ignore the cert error though:

![screen shot 2017-08-18 at 9 31 09 pm](https://user-images.githubusercontent.com/549654/29478460-8491e8aa-845c-11e7-8ff6-9986aa0bf4d0.png)

**Comment by jonathansampson** [comment]
@diracdeltas The option to ignore is only encountered if you navigate directly to the HTTPS. If HTTPS Everywhere attempts to upgrade the connection, no option to ignore is presented. At least, that's what I can determine in the brief bit of testing I just did.

**Comment by alexwykoff** [comment]
You have to disable HTTPSE first to see the option. Perhaps we should consider that a bug in and of itself.

**Comment by diracdeltas** [comment]
@alexwykoff i saw the option without disabling HTTPSE

There seems to be a separate issue here that our cert error pages do not show up for certain navigations

**Comment by dredeyedick** [comment]
I noticed thehill.com  issue, too. Currently, Brave will present me with an empty page "site may have moved...yadayada". But if I change the URL to http from https, I'll get a dialogue that permits me to ignore the Cert error... & if I do that, the page will load. No changes were made by me to the default Site Shield settings in this excercise.

**Comment by jonathansampson** [comment]
@alexwykoff I see the option with HTTPSE enabled, _when I explicitly navigate to the HTTPS enpoint_.

**Comment by alexwykoff** [comment]
@bradleyrichter we should review our error pages to make sure users have good exit paths

**Comment by diracdeltas** [comment]
^ PR above updates our ruleset selection to be more conservative which fixes this issue
