### ISSUE TITLE
adding the "CTRL + E" search shortcut

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10585]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Received a request from the community [1] to add the "CTRL + E" search shortcut to Win platforms. When a user presses the "CTRL + E" shortcut, the browser should initiate a search through either the URL bar (Chrome) or the search box (Firefox).

[1] https://community.brave.com/t/add-control-e-shortcut/6179

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 (I'll look into the other platforms and see what they use instead of the "CTRL + E" shortcut.)

- Brave Version (revision SHA):

Brave v0.18.23 rev 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 - Reproducible
Muon 4.3.10
libchromiumcontent 60.0.3112.90

- Steps to reproduce:
    1. Open Brave
    2. Press "CTRL + E" under Windows (nothing happens)
    
- Actual result:
Pressing the "CTRL + E" keyboard shortcut in Windows doesn't do anything at the moment

- Expected result:
Pressing the "CTRL + E" shortcut should initiate a search via the URL bar

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes, 100% reproducible using the STR from above

**Comment by bsclifton** [comment]
Confirmed this is fixed with our [Developer channel](https://brave.com/download-dev) 😄 👍
