### ISSUE TITLE
Downloading a wrong Dropbox installer for the OS on Mac

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#10588]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Getting the wrong dropbox installer file for the OS, when the request was made from Brave
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.6
- Brave Version (revision SHA):
0.18.23
- Steps to reproduce:
    1. Go to https://www.dropbox.com/install (or within Dropbox web, once signed in, click on the user menu at the top right avatar, and then click on 'Install' menu item, located above Sign out)
    2. Click on 'Download Dropbox' button
    3. Client request is https://www.dropbox.com/download?os=mac
    
- Actual result:
Brave tries to download “DropboxInstaller.exe” file 
- Expected result:
"DropboxInstaller.dmg" for macOS
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. Tested on Safari and Chrome: both auto download .dmg file to user's Downloads folder
    2.
    3.

- Screenshot if needed:
![screen shot 2017-08-18 at 3 57 11 pm](https://user-images.githubusercontent.com/4369856/29480557-f7e40f9c-842d-11e7-82f4-c00ee67653de.png)

- Any related issues:

**Comment by celicoo** [comment]
Same issue here. Brave informations:

                        Name | Version
                              -- | --
Brave                         | 0.18.23
rev                             | 36ae2ec
Muon                         | 4.3.10
libchromiumcontent | 60.0.3112.90
V8                              | 6.0.286.52
Node.js                      | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 16.6.0
OS Architecture | x64

**Comment by celicoo** [comment]
The function responsible for downloading the file is the `registerForDownloadListener`, which registers a listener for the `will-download` event using the [electron session](https://github.com/electron/electron/blob/master/docs/api/session.md). The callback for the will-download receives 3 parameters: 'event', 'item' and 'webContent'. The item parameter is an object with the getURL method. This method is returning the following link:

https://dl-web.dropbox.com/installer?authenticode_sign=True&build_no=32.4.23&juno=True&juno_use_program_files=True&plat=win&tag=eyJUQUdTIjoiZUp5clZpcE9MUzdPek0tTHoweFJzbEl3TkRVM056U3hNREEzTnpHd3NEUTN0akN3TkxVd01yQzBOREd5TkRNM01qTUZpcGliMUFJQW5oME5wZ35-QE1FVEEifQ&tag_token=AHrAeoQC1lnsRpTc7P2oTuUqpaqYLkdTJVF9V8v3OBYdHg

When it should be:

https://dl-web.dropbox.com/installer?build_no=32.4.23&plat=mac&tag=eJyrVipOLS7OzM-Lz0xRslIwNDU3NzSxMDA3NzGwsDQ3tjCwNLUwMrC0NDGyNDM3MjMFipib1AIAnh0Npg~~%40META&tag_token=AHoYZbCl9XgViodp5JrYy4LQZYJryEdOEY7qHiYj4LihIg

I'm still trying to study the code, but the event seems to be part of the Electron framework. Perhaps this issue should be moved to the Electron repository.

**Comment by luixxiul** [comment]
@celicoo do you know how to fix that? If so it would be appreciated if you could create a PR on https://github.com/brave/muon, our folk of the original electron. thanks!

**Comment by celicoo** [comment]
@luixxiul Sure :blush:

**Comment by bsclifton** [comment]
@celicoo nice find! Please ping @bridiver, @darkdh, @bbondy, or myself if you need help with creating a patch 😄

**Comment by celicoo** [comment]
@bsclifton I was able to track the `will-download` event until [here](https://github.com/brave/muon/blob/master/atom/browser/api/atom_api_session.cc#L373), but now i'm not finding how to recompile only the muon code, if possible.

**Comment by bsclifton** [comment]
@celicoo when building (fresh and after making changes), I'll use the browser-laptop-bootstrap project and build using the following:
`npm run build -- --debug_build=true --official_build=false`

As long as your changes are isolated to Muon (ex: the under `src/electron`), it likely won't cause a full recompile.  In the area you linked, you can easily add some debug statements like so:
```cpp
LOG(ERROR) << "message goes here";
```

(of course, you'd have to find how to get the DownloadItem into a string or otherwise printable object)

**Comment by darkdh** [comment]
you can use 
```cpp
LOG(EROR) << item->GetTargetFilePath().value();
```

**Comment by bridiver** [comment]
for some reason we're sending an empty user-agent when the link is clicked, but when you type `https://www.dropbox.com/download?os=mac` manually it works correctly. The resourceType is listed as `other` which also seems odd, but might be correct. I've never looked closely at the resource type for a download link. I see the same thing with shields up and down

**Comment by jonathansampson** [comment]
This issue was also reported by [a user on Twitter](https://twitter.com/MykolaRadchenko/status/957429997735587840).

**Comment by rederekt** [comment]
Testing with 0.25.0, this issue appears to be fixed. @bsclifton , can you close the issue?
