### ISSUE TITLE
Should RTCPeerConnection and RTCDataChannel be disabled?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10592]
**Describe the issue you encountered:**
There is a discussion on the community that  `RTCPeerConnection` and `RTCDataChannel` are not disabled on Brave while other browsers do.

https://community.brave.com/t/webrtc-block-for-2017/3882/5?u=suguru

Should they be disabled from a viewpoint of security?

- Platform (Win7, 8, 10? macOS? Linux distro?): All 

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Enable Fingerprinting Protection
    2. Visit https://browserleaks.com/webrtc
    
- Actual result:  `RTCPeerConnection` and `RTCDataChannel` are not disabled

- Expected result: ?

- Any related issues:

**Comment by diracdeltas** [comment]
They're also enabled in Chrome.

With Fingerprinting Protection on in Brave, we do not disable those APIs because there is no fingerprinting risk since we disable IP leakage.

**Comment by mikeyb** [comment]
> With Fingerprinting Protection on in Brave, we do not disable those APIs because there is no fingerprinting risk since we disable IP leakage.

Should this read:
> we do not disable those APIs because there is no **known** fingerprinting risk

I would like to disable these regardless of brave's perception of my security.  Can this be re-opened and possibly added as an option to disable, or not enable when unnecessary?

**Comment by luixxiul** [comment]
It should be reopened if this is not right: as long as "we disable IP leakage", there will be no fingerprinting risk.

**Comment by luixxiul** [comment]
https://community.brave.com/t/webrtc-requests-leak/10924/4?u=suguru

> Tried https://browserleaks.com/webrtc and this just reinforces my belief that Brave is just not there yet. Chrome does it too is not an answer. Users like to have control over their privacy.
