### ISSUE TITLE
Session runPreMigrations is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10595]
**Describe the issue you encountered:**
Session upgrade is not working anymore, because now we merge default app state and current session data. Because of that things that should not exist (before 0.21 for example bookmarks (https://github.com/brave/browser-laptop/blob/master/app/sessionStore.js#L631) and bookmarkFolders (https://github.com/brave/browser-laptop/blob/master/app/sessionStore.js#L587)) are now empty lists or objects. Because of that all our checks are failing.

This was broken with #10305, were we merged this data https://github.com/brave/browser-laptop/pull/10305/files#diff-9e0c81a9a3f51c8a895685e3183a1452R754.

**Comment by bbondy** [comment]
We used to have an upgrade version value in session store, I don't see it anymore. And you could control whether an upgrade path is run or not.  I think that would be the best way to control whether to have migrations steps or not.  If it's not there anymore then you can just create a new one and if it isn't present then go to the migration step and set that version up one.

**Comment by bbondy** [comment]
I think you can use lastAppVersion, if it's not equal or greater than the current version, or doesn't exist, then you can assume pre-migrations need to run.

**Comment by bsclifton** [comment]
This should only be an issue with 0.21 and newer (specifically with site split).  I verified this by writing tests for the existing migrations, which worked OK.  You can see those here:
https://github.com/brave/browser-laptop/commit/9ad7b4fa208fa61488c92d8f27ecd965d3d90ca1

You can view the 0.18.x sessionStore here (before bookmark, bookmarkFolders, etc)
https://github.com/brave/browser-laptop/blob/a83fc648d77f1cda890302ed677fdb8ee9eccfe8/app/sessionStore.js#L473 (which doesn't have bookmarks, bookmarkFolders, etc)

**Comment by bsclifton** [comment]
I'd like to propose moving this to 0.21.x (where site split happened).  @NejcZdovc, maybe you can help me write the tests 😄

**Comment by bsclifton** [comment]
More progress made with https://github.com/brave/browser-laptop/commit/0dfd283a4fe1c1790670d37f70aa1524f81ad473

(I've been writing tests and then fixing the issue after the test fails)

**Comment by bsclifton** [comment]
We're finally coming around to 0.20.x 😄  To recap, here's the work I've done so far:

**_Commit 1 - add unit tests for existing code_**
master/0.21.x/0.20.x https://github.com/brave/browser-laptop/commit/9ad7b4fa208fa61488c92d8f27ecd965d3d90ca1

**_Commit 2 - adding tests for site split code migrations; fixing as needed_**
master/0.21.x/0.20.x https://github.com/brave/browser-laptop/commit/0dfd283a4fe1c1790670d37f70aa1524f81ad473

Commit 3 - fixing more of the site split code migrations
master https://github.com/bsclifton/browser-laptop/commit/5f3a54e37eea2765d038999460a1bac3e44bc51d
0.21.x TODO
0.20.x TODO

**Comment by bsclifton** [comment]
Covered by automated tests- but manual test plan captured in https://github.com/brave/browser-laptop/pull/12369 😄 👍

**Comment by bsclifton** [comment]
Opening after @NejcZdovc found an issue with cache
