### ISSUE TITLE
Netflix with widevine not working Error Code: M7121-1331-P7

### ISSUE THREAD

**Issue by ricardosaracino** [brave/browser-laptop#10593]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Netflix wont work, error code
Error Code: M7121-1331-P7

- Platform (Win7, 8, 10? macOS? Linux distro?):
win10

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Widevine is endabled, restarted the browser a few times
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Hi, is this duping to #10449 ?

**Comment by ricardosaracino** [comment]
yes it is my bad

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by luixxiul** [comment]
nevermind :-)
