### ISSUE TITLE
Bookmarks Toolbar Not Fully Utilized

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10594]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Only about 40% of the bookmarks toolbar is showing (favicon w/ label) bookmarks. The rest are placed in the dropdown menu to the right. Resizing the browser to a small width will show even fewer items.

More bookmarks are shown if:
1. I switch to favicons only
2. Expand the width of the browser
3. Decrease the size of the UI

Fewer bookmarks are shown if:
1. I switch to favicons and labels, or just labels
2. Decrease the width of the browser
3. Increase the size of the UI

*This issue reportedly began one or two months ago.*

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7, Windows 10

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/36ae2ec06efed0057ae16351108bf4d4c10a7ab4

- Steps to reproduce:
_See conditions above_
    
- Actual result:
Bookmarks toolbar isn't fully populated by bookmarks

- Expected result:
More than ~40% of space would be used.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
might be duping to https://github.com/brave/browser-laptop/issues/4116
