### ISSUE TITLE
Hide Close Button on Tab

### ISSUE THREAD

**Issue by VxMxPx** [brave/browser-laptop#10602]
- Did you search for similar issues before submitting this one?

Yep.

- Describe the issue you encountered:

I'd like an option which would enable/disable close button on tabs altogether. (Vivaldi has an option: Display Close Button, under Tabs settings, so basically, it would be great to have the same thing in Brave).

- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux, Arch

- Brave Version (revision SHA):

ad92d029e184c4cff01b2e9f4916725ba675e3c8

- Steps to reproduce:

Open about:preferences#tabs

- Actual result:

No `Display Close Button` toggle.

- Expected result:

`Display Close Button` toggle, which when enabled would hide close buttons on tabs.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/10491
