### ISSUE TITLE
State the fingerprint of your PGP signing keys

### ISSUE THREAD

**Issue by DarkCoridor** [brave/browser-laptop#10601]
- Did you search for similar issues before submitting this one?

No open or closed issues mention word `fingerprint`

- Describe the issue you encountered:

I am unable to find the fingerprint of the various PGP signing keys you use to sign Linux packages. Thus there is no way to know if the key you downloading at:

https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc

Is actually the key meant to be there. Any malicious party with access to the AWS infrastructure could swap out malicious code and sign that with a fake key and it would seem "secure" to an end user.

The rest of the issue questions are irrelevant.

**Comment by bsclifton** [comment]
@DarkCoridor thanks for the report! We're tracking this issue (in a more general sense) with issue https://github.com/brave/browser-laptop/issues/197

I'm going to close this issue as a duplicate and give that one a +1 on your behalf 😄
