### ISSUE TITLE
Wrong tooltip on Reload button

### ISSUE THREAD

**Issue by shamrin** [brave/browser-laptop#1061]
Reload button tooltip always says "Stop loading" for me:

![brave 2016-03-12 17-20-05](https://cloud.githubusercontent.com/assets/510678/13723455/016457e2-e877-11e5-8488-038ef69235b4.png)

Version: 0.8.0
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110
Channel: dev
OS X 10.11

(Also see #1062.)

**Comment by bbondy** [comment]
Nice find, fixed here:
https://github.com/brave/browser-laptop/commit/6a1826d61136c1d34ddb5d71b977e3cb6dfd3dc1
Will be in the 0.8.1 release coming hopefully very soon.

**Comment by shamrin** [comment]
That was fast, thank you!

P.S. Very interesting, you use React to implement browser chrome. Looks like it would be very easy to hack on Brave.

**Comment by bbondy** [comment]
Yes we do, we'd love our help contributing, please feel free :)
