### ISSUE TITLE
Enable Brave in the UA for www.netflix.com

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10614]
## Test plan
1. Launch Brave and visit https://netflix.com
2. Open the developer tools (F12 or shift + option + i)
3. Force reload the page (shift + cmd + R or shift + ctrl + R)
4. Inspect the network tab for the `netflix.com` resource
5. Under request headers, you should see the user agent (`Brave` being the important part) which should be like:
"user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) **Brave** Chrome/60.0.3112.90 Safari/537.36"

## Original issue description
Apparently VMP requires it

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/30009379-c5f34544-911f-11e7-8981-7a454cc5c25a.png)
