### ISSUE TITLE
Middle mouse click scrolling grabs also content from page

### ISSUE THREAD

**Issue by MuhammedKpln** [brave/browser-laptop#10613]
- Did you search for similar issues before submitting this one?
Yes i do, and i found #10405  this issue.
- Describe the issue you encountered:
When i scrolling with mouse middle click it grabs content of page also. I'm toggling middle mouse click so when i just click it once then pull the down it grabs also contents in pages.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Creators Update
- Brave Version (revision SHA):
0.18.23
- Steps to reproduce:
    1. Toggle mouse middle click
    2. Pull down
    3. It grabs also content
Here is the gif link for better explanation:
- Actual result:
It grabs also page content
- Expected result:
It should just go down without grabs the page content.

- Is this an issue in the currently released version?
Yes.

- Screenshot if needed:
Gif instead;
[https://giphy.com/gifs/12Z53WG2iRTLqw/fullscreen](https://giphy.com/gifs/12Z53WG2iRTLqw/fullscreen
)

**Comment by NejcZdovc** [comment]
@MuhammedKpln thank you for your report. Is this the same one as #10405?
