### ISSUE TITLE
Most recent release is laggy/hangs if window not maximized

### ISSUE THREAD

**Issue by samteezy** [brave/browser-laptop#10619]
- Did you search for similar issues before submitting this one? 
Yes, I searched recent open/closed tickets with similar keywords.

- Describe the issue you encountered: 
After the most recent update, 0.18.23, I've noticed that the browser is extremely slow and laggy on startup. Maximizing the window (as it always starts not maximized for me) seems to fix the issue. I don't remember seeing this issue in the previous release.
Edit: Upon a little further testing what I am finding is that my interactions in the browser - like typing in the omnibar at top - don't actually display in the window when it's _not_ maximized. I can replicate this by un-maximizing the window as well. The issue will even replicate when I'm attempting to type in this text box in the page.

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Win 10

- Brave Version (revision SHA): 
Full version info:
Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

- Steps to reproduce:
    1. Launch Brave
    2. Click, navigate to websites, etc.
    
- Actual result: 
Typing in a URL and hitting "enter" should cause the browser to immediately start the page retrieval process.

- Expected result: 
The window doesn't display typed characters or start loading a page for several seconds (5-10?)

- Will the steps above reproduce in a fresh profile? If not what other info can be added? 
I haven't been able to test this yet.

- Is this an issue in the currently released version? 
Yes, 0.18.23

- Can this issue be consistently reproduced? 
Yes, every startup.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed: N/A

- Any related issues: N/A
 
P.S. Thank you Brave team for all your hard work!

**Comment by bsclifton** [comment]
I suspect some of these issues are DPI related... @samteezy, are you at 125% or 150% scale? If so, please try changing it to 100% and logging out / logging back in.  It should work good at 100%.  If you can confirm that works, then we know it's DPI related 😄  (we just need more info to confirm)

**Comment by samteezy** [comment]
@bsclifton, I'm actually at 100% because so many apps I work with haven't adapted to high DPI.

I should note that it seems like after the latest update (there's been at least one since my post, right?) I don't see the lag, but sometimes I don't see any interaction in the window until it's maximized (e.g., I attempt to type a URL and nothing shows up on the screen). Hard to replicate on command.

**Comment by bsclifton** [comment]
@samteezy sorry for taking so long to respond-  if you're willing to give Brave another chance, you should be able to follow the steps here to update your shortcut to disable hardware acceleration.  After you shared that you're at 100%, I suspect hardware acceleration is having issues
https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003

**Comment by bsclifton** [comment]
Closing this issue for the time being- please re-open if you do give it a shot
