### ISSUE TITLE
Slack Magic Link (link to desktop application) causes the Brave browser to freeze

### ISSUE THREAD

**Issue by syuan100** [brave/browser-laptop#10626]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When opening a Slack Magic link (slack://....) it will open Slack successfully upon authorization, but then it will freeze the Brave browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.23
rev | 36ae2ec

- Steps to reproduce:
    1. Add a slack team to the Slack desktop App.
    2. Click sign-in via magic link
    3. Go to email in Brave browser (I was using Gmail) and click through the magic link.
    4. Brave asks for permission to open app
    5. Click Allow
    6. Slack opens
    7. Brave doesn't freeze
    
- Actual result:
Brave Freezes

- Expected result:
Brave doesn't freeze

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. 
    2. 
    3. 

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@syuan100 did the eventually work for you? Curious why it was closed?  If the issue is still happening, let's re-open it 😄

**Comment by syuan100** [comment]
Hello, yes it seemed to have stopped hanging! I'm not sure why I can't recreate it anymore :P I'll reopen it if it happens again!
