### ISSUE TITLE
No longer able to remove thumb from new tab window

### ISSUE THREAD

**Issue by bfioca** [brave/browser-laptop#10622]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Removing Thumb no longer works.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Open a new tab
    2. Hover over a thumb and click the X
    
- Actual result:
The Thumb is not removed even though the undo dialog pops up

- Expected result:
The thumb is removed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Unsure - I think it might have started after I Imported my browser data from Safari.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
NA

- Screenshot if needed:
<img width="920" alt="screen shot 2017-08-21 at 8 35 54 pm" src="https://user-images.githubusercontent.com/21037/29547745-d0901438-86b0-11e7-88e0-2516e4dd0d23.png">

- Any related issues:

**Comment by NejcZdovc** [comment]
@bfioca thank you for your report. Is this the same as #10411?

**Comment by happyhero0** [comment]
+ 1

**Comment by NejcZdovc** [comment]
closing as a duplication of #10411
