### ISSUE TITLE
Reopen Last Closed Tab sometimes results in a dead ghost tab

### ISSUE THREAD

**Issue by JaneSmith** [brave/browser-laptop#10636]
- Describe the issue you encountered:
When reopening the last closed tab with Ctrl+Shift+T, sometimes it results in a dead ghost tab. By this I mean the tab has a basic "document" favicon, no title, and no X button. The tab cannot be selected. Right-clicking on the tab does not display any menu. The tab can't even be closed - it's just there forever until the window is closed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro.

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Have Brave's "new tab" setting set to "blank page".
    2. Open a new Brave window.
    3. Press Ctrl+T to open a new tab. There should now be two tabs, both showing a blank page.
    4. Open the menu and go to Preferences. There should now be three tabs.
    5. Press Ctrl+W to close the Preferences tab. There should now be two tabs (both blank).
    6. Press Ctrl+W to close the second tab. There should now be one blank page tab.
    7. Press Ctrl+Shift+T to reopen the last closed tab.
    
- Actual result:
A dead, buggy, broken, ghost tab appears.

- Expected result:
The blank page tab should re-open.

- Can this issue be consistently reproduced?
Yes.

- Additional information:
    1. Closing another tab like the Preferences one seems to be necessary first. If you just close a blank page tab right away, Ctrl+Shift+T doesn't resurrect anything.
    2. After doing this a few times to reproduce it, I noticed Brave started getting extremely sluggish, and Task Manager shows it's using a whopping 1.8 GB of memory on just a single process (and more memory if you count the other processes: e.g. 400 MB, 360 MB, etc.).

**Comment by bsclifton** [comment]
cc: @bbondy who has done a lot of work with tabs recently

**Comment by bbondy** [comment]
This is fixed in 0.18.29, if you update it should go away. Thanks!
