### ISSUE TITLE
vid.me signup

### ISSUE THREAD

**Issue by ricardosaracino** [brave/browser-laptop#10635]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
vid.me sign up causes js error
- Platform (Win7, 8, 10? macOS? Linux distro?):
win 10
- Brave Version (revision SHA):

36ae2ec
-
- Steps to reproduce:
    1. hit sign up
    2.
    3.
    
- Actual result:
js error
- Expected result:
js pop up
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Uncaught TypeError: Cannot read property 'join' of undefined
    at e.getWebglFp (index.724cd946.js:sourcemap:40)
    at e.webglKey (index.724cd946.js:sourcemap:40)
    at e.get (index.724cd946.js:sourcemap:40)
    at index.724cd946.js:sourcemap:41
    at d (index.724cd946.js:sourcemap:41)
    at Object.<anonymous> (index.724cd946.js:sourcemap:41)
    at Object.execCb (require.js:1693)
    at Module.check (require.js:876)
    at Module.enable (require.js:1173)
    at Object.enable (require.js:1554)

![image](https://user-images.githubusercontent.com/759253/29594000-ef494072-877b-11e7-9821-7d4834159ddb.png)

- Any related issues:

**Comment by bsclifton** [comment]
@ricardosaracino do you have fingerprint protection enabled?  Enabling this affects webgl.  Can you please try turning that off?

If you click the lion (in the top right) while on that site and disable finger print protection, it will remember it only for that domain.  I think that should fix the issue 😄

**Comment by ricardosaracino** [comment]
That is the issue. You might want to consider having it off by default. Maybe a global white list? Either way, ill keep submitting issues as they come up, Brave is a great product.

**Comment by bsclifton** [comment]
@ricardosaracino great!

It should be off by default... but you can change it globally too, which affects any sites you visit.  If you wanted to toggle that off, you can visit Preferences > Shields and turn it back off
![screen shot 2017-08-23 at 8 26 56 am](https://user-images.githubusercontent.com/4733304/29624032-faa3da70-87dc-11e7-83b7-475893a55d15.png)

Having it on is great though- but unfortunately it does break some sites.  @diracdeltas recently added a new feature (coming soon) which allows you to only block 3rd party fingerprinting.  This helps to prevent tracking while not breaking the site and it will be enabled by default
