### ISSUE TITLE
Multiple extension login page opened with multiple pinned session tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10641]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Multiple extension login page opened with multiple pinned session tabs

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10

- Steps to reproduce:
    1. Ensure no extension is enabled
    2. Pin 3-4 session tabs
    3. Enable LastPass/Pocket
    4. Multiple login pages are loaded
    
- Actual result:
Multiple extension login page opened with multiple pinned session tabs

- Expected result:
Should only one login page should be loaded

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
I notice that this steps cause crash on the latest master.

STR:
- start browser with a clean profile
- disabled all extensions (even torrent and pdf)
- re-lunch browser
- stop it via terminal
- start it again (`npm run start`)
- open 4 session tabs (load top sites in each)
- pin all 4 tabs
- go to preferences and enable LastPass
- brave crashes
```
Brave(12181,0x700009540000) malloc: *** error for object 0x7f96c50b2168: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
process exited with code 0
```

Funny thing is that when you start it again after crash you loose all session pinned tabs

**Comment by NejcZdovc** [comment]
after some more test we get 4 request into this function

https://github.com/brave/browser-laptop/blob/f9f4aeb83573e3475af4cfab05592c6f796032a1/app/browser/tabs.js#L347-L412

I suspect that problem is in muon so I am cc-ing @jonathansampson for his thoughts

**Comment by jonathansampson** [comment]
I was able to reproduce this on master. I see LastPass' _Create Account_ page opened 5 times (with four pinned session tabs). Only the first of the 5 is actually loaded. The remaining 4 do not load the resource.

This area may be a little out of my wheelhouse, but I'll take a closer look and see if I can find something of value in the next 20 minutes or so.
