### ISSUE TITLE
white tab displayed if 'last viewed tab' isn't available

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10645]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When the setting for 'When closing an active tab' is set to 'Select the last viewed tab', and you close the first tab (of two tabs), this results in a white tab being displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.19.3
rev | 053c863
Muon | 4.4.9

- Steps to reproduce:
    1. Verify in Preferences > Tabs you have 'Select the last viewed tab' as the setting for 'When closing an active tab.
    2. Start with a new window (just one new tab).
    3. In the new tab navigate to a site like theverge.com.
    4. Cmd+click (MacOS) on a link to open a link in a new tab but not switch to it. (you now have two tabs).
    5. Cmd+w to close the active (first) tab.
    
- Actual result:
White tab is displayed.

- Expected result:
I was expecting to see the second tab since I closed the first one in the window.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes (0.18.23)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Close the active tab in other ways (right click on tab > select Close tab, close active tab with X).
    2. 
    3. 

- Screenshot if needed:
![whitetab](https://user-images.githubusercontent.com/28145373/29638324-ece8560c-8824-11e7-869c-fa4f9e741c5c.gif)

- Any related issues:

**Comment by bsclifton** [comment]
I believe this will be fixed with @bbondy's upcoming changes
