### ISSUE TITLE
Window opens to a maximized size but is offset by several pixels to the left and right.

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#10646]
- Did you search for similar issues before submitting this one?

Yes. Related issues, but not the same, include #9371, #2438 and #3558.

- Describe the issue you encountered:

Open Brave and it is offset up and to the left by several pixels. If I maximize the window, close and reopen, it still opens in the same position. I have two monitors that aren't the same size. This is an ongoing issue that has occurred on multiple computer cycles.

Name | Version
-- | --
Brave | 0.18.23
rev | 36ae2ec
Muon | 4.3.10
libchromiumcontent | 60.0.3112.90
V8 | 6.0.286.52
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Comment by jonathansampson** [comment]
I believe this is largely covered by our lack of preserved state around the maximized/minimized state. This will be resolved soon, as it was tracked by this issue: #3138 

Closing in favor of the aforementioned issue.
