### ISSUE TITLE
Three-finger "Look up" tap should work

### ISSUE THREAD

**Issue by shamrin** [brave/browser-laptop#1064]
OS X supports three-finger "Look up" tap to look up words in a dictionary. Very useful when learning languages, for example. Unfortunately it doesn't work in Brave.

(Look up could also be invoked by `cmd-ctrl-d`.)

If you are not familiar with this feature, here it is in Google Chrome:

![monosnap 2016-03-12 18-00-07](https://cloud.githubusercontent.com/assets/510678/13723649/b49abb58-e87c-11e5-8069-f3385f9a135f.png)

Version: 0.8.0
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110
Channel: dev
OS X 10.11

Some probably related bugs:
- https://github.com/atom/atom/issues/441
- https://github.com/atom/atom/issues/5967
- https://bugzilla.mozilla.org/show_bug.cgi?id=1212527

**Comment by shamrin** [comment]
It seems to be a bug with Electron `<webview>`. I've submitted an issue: https://github.com/atom/electron/issues/4772

**Comment by Liunkae** [comment]
Since #1627 (Look Up in the context menu) has already been implemented, we just need Brave to recognize the three finger gesture.

**Comment by Liunkae** [comment]
Update: With the current master (rev b288e18, 0.13.0 dev), now the Dictionary app opens with the search term "http". This behavior probably changed with Chromium 54.

**Comment by darkdh** [comment]
With chromium54 change (since 0.13.0), `three finger tap` or `control + command + d` will open a empty Dictionary.app but still needs a fix.
I believe this is what @bbondy discovered in https://github.com/brave/browser-laptop/issues/7043 and it is not limited in input field.

**Comment by bbondy** [comment]
I was definitely using the Lookup option from the context menu, so it could be I was doing something wrong at the time in addition to that, or using a wrong build somehow or something like that, or an intermittent bug.

**Comment by darkdh** [comment]
will be fixed in 0.13.3 by
https://chromium.googlesource.com/chromium/src.git/+/3f7daa9733a4d5d3c06359b9f92c3bde20c7dd5d
