### ISSUE TITLE
Superhuman: Failure to append iframe

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10642]
## Extension: Superhuman

| Name | Value |
| --- | --- |
| Version | 2.0.36 |
| Ext ID | dcgcnpooblobhncpnddnhoendgbnglpn |
| BG Page | chrome-extension://dcgcnpooblobhncpnddnhoendgbnglpn/background/background.html |

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Superhuman attempts to create an iframe, but fails due to CSP restrictions. This appears to set-off a chain of additional errors.

> extension_frame_api.cjsx:29 Refused to frame 'chrome-extension://dcgcnpooblobhncpnddnhoendgbnglpn/superhuman.html#src=https%3A%2F%2Fmail.superhuman.com%2F~backend%2Fbuild%2Febb9cb1b6c6759bbb27d.extension_frame.js' because it violates the following Content Security Policy directive: "default-src 'self' https: data: blob: ws:". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
Desktop

**Brave Version (revision SHA):**
0.20.0 (https://github.com/brave/browser-laptop/commit/12cd539e98f78303bb54fd1c394bfe10c4132aff)

**Steps to reproduce:**
    1. Enable the Superhuman extension
    2. Attempt to log-in via https://mail.superhuman.com
    3. Check console for inbox page
    
**Actual result:**
Several errors, preceded by a CSP exception.

**Expected result:**
Page/extension should work as expected.

**Comment by jonathansampson** [comment]
@bridiver Is this CSP header (see above) ours? I did a quick search, but wasn't able to locate these directives. Any direction would be greatly appreciated.

**Comment by jonathansampson** [comment]
Current thinking is that this may be an issue with Chrome being _too relaxed_ around enforcing CSP. See this comment for additional context: https://github.com/brave/browser-laptop/issues/6825#issuecomment-324402798.

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
