### ISSUE TITLE
Frozen tabs when splitting/joining windows

### ISSUE THREAD

**Issue by GGurtner** [brave/browser-laptop#10650]
- Did you search for similar issues before submitting this one?
Yes. Some of them seem to be similar, but none exactly the same.

- Describe the issue you encountered:
Tabs are unresponsive when taken from a window and then put back in.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux 17.1 and 17.2

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Open new window
    2. Go to any website
    3. Open a new tab
    4. Go to any other website in this tab
    5. Detach one of the tabs to form a new window
    6. Put back the tab into the initial window

- Actual result:
    7. At this stage, a blank page appears instead of the content of the tab reattached. You can still switch to the other tab and its content appears.
    8. Now two things can happen, but I can't tell when one or the other happens:
        - either only the reattached tab is unresponsive: impossible to switch to it or close it, but you can still open, close, and switch to the other tabs. Other windows are not impacted.
        - or all the tabs are unresponsive: impossible to close them or switch from one to the other. Impossible also to open new tabs, either with the '+' or with the menu. You can still use the content of the active tab normally (e.g. do a search with google). All the interface is responsive apart from the tabs. All the other windows opened have their tabs frozen too.

- Expected result:
All tabs should be responsive when the tab is reattached.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not tested with a fresh profile.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes, even if the final state seems to be a bit random between the two states described above.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/10538. please see https://github.com/brave/browser-laptop/issues/9722.
