### ISSUE TITLE
Extension page not allowing to search and install

### ISSUE THREAD

**Issue by unixbhaskar** [brave/browser-laptop#10658]
How can I install firefox extension to brave?? It seem the extension page doesn't allow searching facility and install.

**Comment by bsclifton** [comment]
@unixbhaskar Brave is based on Chromium and does have support for Chromium extensions (we're still in the process of adding more support).  One of our engineers, @jonathansampson, wrote up a great blog post about how to try out extensions:
https://brave.com/loading-chrome-extensions-in-brave/

We don't plan to add support for Firefox extensions though, unfortunately.  Sorry ☹️

**Comment by NumDeP** [comment]
@unixbhaskar what are the FF extensions that you would have wanted to use but can't/won't be able to?
