### ISSUE TITLE
I can detect brave browser

### ISSUE THREAD

**Issue by AhsanE** [brave/browser-laptop#10655]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Brave browser is detectable
- Platform (Win7, 8, 10? macOS? Linux distro?):
win 10
- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
what do you mean by "detectable"? would you explain about that please?

**Comment by AhsanE** [comment]
I have made a script, that can detect it. Its pretty easy

**Comment by AhsanE** [comment]
Using Canvas I can detect of the user is using brave or not. The way brave renders is the culprit here.

**Comment by AhsanE** [comment]
Brave renders <code> element differently than chrome.

**Comment by bsclifton** [comment]
@AhsanE can you share more details? maybe a working example

cc: @diracdeltas

**Comment by AhsanE** [comment]
I'll be submitting the report on hackerone. Wont publicly disclose.

**Comment by diracdeltas** [comment]
closing this because it will be triaged through hackerone.
