### ISSUE TITLE
Upgrade to Brave 0.8 failed

### ISSUE THREAD

**Issue by michael-oneill** [brave/browser-laptop#1065]
I tried to upgrade  a previous version to 0.8 and the install failed. I had been running the old version, but had closed it. 

The log of that is attached

I noticed that 2 brave.exe processes were running, killed both of them, then the install worked.

[SquirrelSetup2.zip](https://github.com/brave/browser-laptop/files/170575/SquirrelSetup2.zip)

**Comment by bbondy** [comment]
You're still on the old version right?
Looks like something permissions related:
install, is the app still running???: System.UnauthorizedAccessException: Access to the path 'C:\Users\Mike\AppData\Local\Brave\app-0.7.11\Brave.exe' is denied.

Are you logged in with an admin account or limited user account?

**Comment by michael-oneill** [comment]
I installed 0.8 fine once I deleted the old brave.exe processes. Unfortunately I did not take a note of the old version, I installed that about 2 months ago. 

I was logged in as my Admin account.

**Comment by michael-oneill** [comment]
I downloaded it  (the old version) 30/1/2016

**Comment by bbondy** [comment]
Closing this since we have another task about better handling here.
