### ISSUE TITLE
"Save Image..." very often crashes the browser

### ISSUE THREAD

**Issue by JaneSmith** [brave/browser-laptop#10653]
- Describe the issue you encountered:
When I right-click on an image and choose "Save Image...", the save dialog appears. Sometimes this works fine. However, very often the browser will crash as the dialog window appears.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro.

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Right-click on an image.
    2. Choose "Save Image..."
    
- Actual result:
The browser crashes.

- Expected result:
I should be able to save the image without issues.

- Can this issue be consistently reproduced?
No.

I save images quite often. As a result, I'm experiencing browser crashes at least 20+ times a day, and then when I restart the browser I end up with a session from some time ago. There are various other bugs with Brave that I can overlook, but unfortunately this one is becoming way too big of an issue for me. I'm becoming very frustrated with the browser crashing constantly over and over and over and over again, and then as a result losing my open tabs, losing my position in videos, losing my current input into forms, losing my scroll position on long pages...

I love Brave for the clean and compact UI, the Shields system, and for being designed with privacy in mind... But sadly I am going to have to stop using it as my main browser until it becomes more stable. :(

**Comment by bsclifton** [comment]
@JaneSmith can you check out https://github.com/brave/browser-laptop/issues/3313? I'm curious if this is the same issue

**Comment by JaneSmith** [comment]
Hmm... I'm not sure. It sounds similar, but I can't reproduce the issue by following any of the steps listed on that bug report. I also never needed to Alt+Tab out in order to get this issue. It would just occur randomly when trying to save images, without me switching to another window.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
