### ISSUE TITLE
Imported Bookmark Folder Right Click -> Delete Folder Does Not Function

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1066]
In 0.8.1
**STR**:

1. Import Bookmarks
2. Right Click on the Folder Wished to be Deleted and Click 'Delete Folder' Context Menu Item
3. Observe The Folder Is Not Deleted

**Comment by bbondy** [comment]
Please post a minimal bookmarks import html which reproduces and also specify where you are deleting from, is it from the bookmarks manager or the bookmarks toolbar? Thanks!

**Comment by luixxiul** [comment]
Okay to regard this fixed?

**Comment by cezaraugusto** [comment]
Closing as too old, lacking info and not reproducible in any OS anymore. Running tests on v0.11.0
