### ISSUE TITLE
Sound plays on Twitter, but not TweetDeck

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10664]
#### Did you search for similar issues before submitting this one?
Yes

#### Describe the issue you encountered:
When viewing embedded media in TweetDeck, no sound plays. When opening the same tweet on Twitter.com, the sound plays as expected.

#### Platform/Brave version:

| Key | Value |
| --- | --- |
| Brave | 0.18.23 |
| rev | 36ae2ec |
| Muon | 4.3.10 |
| libchromiumcontent | 60.0.3112.90 |
| V8 | 6.0.286.52 |
| Node.js | 7.9.0 |
| Update Channel | dev |
| OS Platform | Linux |
| OS Release | 4.12.5-300.fc26.x86_64 |
| OS Architecture | x64 |

#### Steps to reproduce:
    1. Locate [this tweet](https://twitter.com/MuslimIQ/status/900877438317719552) in TweetDeck
    2. Play the embedded media
    
#### Actual result:
No audio plays with the video.

#### Expected result:
Audio channel is played.

#### Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

#### Is this an issue in the currently released version?
Yes

#### Can this issue be consistently reproduced?
Yes

**Comment by alexwykoff** [comment]
@jonathansampson do shield settings have any effect?

**Comment by jonathansampson** [comment]
The user who reported this issue to me stated that the problem no longer repros. Closing, until somebody else reports a similar issue.
