### ISSUE TITLE
[Suggestion] Tab Bar Kinetic Mouse Wheel Scrolling (with settings)

### ISSUE THREAD

**Issue by JonnyRedHed** [brave/browser-laptop#10676]
Would be really great to have Tab bar scrolling left and right with the mouse wheel, using kinetic scrolling (with settings for speed, acceleration/deceleration etc).   For those of use wanting to use 100-200+ open tabs daily.  Scrolling much like FireFox has. But with your own Brave flavour of doing things.

The current option (tab Sets) is pretty good, but some of us do prefer to kinetic scroll left and right to whiz up and down out 100-200+ daily tabs real fast.

Could this be considered please.

**Comment by luixxiul** [comment]
duping to https://github.com/brave/browser-laptop/issues/879, https://github.com/brave/browser-laptop/issues/6728.
