### ISSUE TITLE
[Feature Request/Question] Create custom extensions?

### ISSUE THREAD

**Issue by bdsomer** [brave/browser-laptop#10674]
- Did you search for similar issues before submitting this one?
Yes

Could us developers get a system to create custom extensions? I just want to create some personal extensions for myself (and possibly some friends). Bonus points if the extension is compatible with Chrome.

I'm pretty sure there's a way to do this, but if there isn't, than this is a feature request, rather than a question.

**Comment by CrisBRM** [comment]
https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions

**Comment by bdsomer** [comment]
@ChrisBRM Thanks!
