### ISSUE TITLE
Brave should only intercept top-level reqs for .torrent files, not requests from fetch()

### ISSUE THREAD

**Issue by kirkins** [brave/browser-laptop#10672]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The service bitchute.com doesn't work on brave.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version (revision SHA):
0.18.23 36ae2ec

- Steps to reproduce:
    1. Goto bitchute.com
    2. Click a video
    
- Actual result:
Am asked to download the torrent that powers the video.

- Expected result:
In chrome and firefox the torrent is some how downloaded in the background and provides a decentralized youtube-like service.

- Screenshot if needed:
![screenshot from 2017-08-26 13-42-07](https://user-images.githubusercontent.com/9503662/29743663-62a319c2-8a64-11e7-9c2a-af2b2c299053.png)

- Any related issues:

**Comment by anon376** [comment]
i have the same problem.

**Comment by Laz3rPanth3r** [comment]
Confirming that this behavior with bitchute is the same on Windows 10 1703 as well and is not the expected result. Works fine in Chrome on Windows.

**Comment by carsongross** [comment]
Does not work on Brave/OSX either

**Comment by eljuno** [comment]
+2 from community

**Comment by kirkins** [comment]
I imagine this will become popular as there is significant cross-over between people who are using Brave as a protest against Google/Mozilla and people who want to use Bitchute for similar reasons.

Also I turned off the torrent extension to see if that would work but still a problem.

If I have time later I'll try reading through BitChute's source code to get a better idea of the problem.

**Comment by dseeker** [comment]
same here, windows 8.1
seems like brave is tracking the torrent files used by bitchute webtorrent and offers to download it instead, the torrents are associated to the to Torrent Viewer extension, unfortunately disabling it still returns an error, it stills finds the webtorrent file and takes it from the page, you can still see the video, but it totally breaks the user experience with the website.

**Comment by dseeker** [comment]
![image](https://user-images.githubusercontent.com/11655138/29897582-f09fafee-8de1-11e7-827c-fca0f888216a.png)

**Comment by stephenkru** [comment]
+1 Brave Win10

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10
libchromiumcontent | 60.0.3112.90
V8 | 6.0.286.52
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Comment by stephenkru** [comment]
Here is from the BITCHUTE.com FAQ: 

> BitChute is powered by WebTorrent. WebTorrent is an independent project started by Feross Aboukhadijeh in October 2013 and is the first torrent client that works in the browser. YEP, THAT'S RIGHT. THE BROWSER.
> 
> I cannot overstate the importance of WebTorrent. The Internet is full of centralized monsters and WebTorrent is the magical sword we will use to slay them.
> 
> You can find out more about WebTorrent here: https://webtorrent.io/faq.

**Comment by bsclifton** [comment]
cc: @feross

**Comment by kirkins** [comment]
@dseeker interesting looks like it's trying to use some built in chrome-extension?

I'm reading that Brave can use chrome extensions with manual setup. 

https://brave.com/blog/loading-chrome-extensions-in-brave/

Would that mean it's possible to figure out which is used here and import it?

**Comment by dseeker** [comment]
@kirkins the problem seems to be that any torrent files exposed to brave gets sent to the torrent viewer extension. the problem is not the extension itself, but allowing the website to use .torrent files without being interrupted by brave

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/bitchute-broken/7102/2

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/brave-browser-doesnt-work-with-bitchute/7420?u=eljuno

**Comment by jim3** [comment]
+1 on Windows 10


```
Name	Version
Brave	0.18.36
rev	7ab85e9
Muon	4.3.22
libchromiumcontent	61.0.3163.79
V8	6.1.534.32
Node.js	7.9.0
Update Channel	dev
OS Platform	Microsoft Windows
OS Release	10.0.15063
OS Architecture	x64
```

**Comment by rayvahey** [comment]
Just took a look. When the webtorrent.js script in bitchute page uses fetch() on a .torrent file, Brave intercepts that req and redirects.

Brave should only intercept top-level reqs for .torrent files, not requests from fetch(), etc. Probably an easy fix (but I have no time)

https://twitter.com/feross/status/916145619902783488

https://twitter.com/feross/status/916145982080823297

**Comment by rayvahey** [comment]
@kirkins could we change the title to something along the lines of "Brave should only intercept top-level reqs for .torrent files, not requests from fetch()"
As the problem doesn't seem to be specific to BitChute

**Comment by rayvahey** [comment]
In the meantime, a workaround for anyone else who needs this is to present the file extension as .webtorrent instead of .torrent. 
.webtorrent will still be recognized in the desktop client but will not trigger the Brave intercept.

**Comment by ReK2Fernandez** [comment]
This is also happening with PeerTube so nobody can see videos on our site using brave browser.

**Comment by kirkins** [comment]
This is now working for me on both BitChute and PeerTube.

So I will mark this as closed.

**Comment by scanlime** [comment]
I'm still having this problem with all PeerTube sites, as of Brave 0.25.2 (8ea2a9c)

**Comment by raisty** [comment]
Link back to PeerTube: https://github.com/Chocobozzz/PeerTube/issues/1374
Both are using webtorrent.
Brave should find out better handling 💃

**Comment by the-sushi** [comment]
On PeerTube sites I still (0.57.6) get the "Sorry, but this video is not available because the remote instance is not responding"

**Comment by bsclifton** [comment]
@scanlime @raisty @the-sushi can you all please try the new version of Brave?
https://brave.com/download

If the problem is still happening, I can help create an issue in the new repository:
https://github.com/brave/brave-browser
