### ISSUE TITLE
Node.js does not exit when you cancel watcher process (Windows)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10670]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:

  On Windows, when doing development you'll have two windows setup:
  - Window 1 runs `npm run watch`
  - Window 2 runs `npm start`

  After running these, Brave will launch. You can then quit and control is restored to Window 2. If you switch to window 1 and try to use Ctrl + C to cancel the watcher process, it appears to exit but the process stays in memory

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Clone repo; run npm install
    2. Open task manager and confirm there are no `node.exe` processes running
    3. In command window, run `npm run watch`
    4. Let webpack finish and test that it's loading by opening a new command window and running `npm start`
    5. Exit the Brave app that launches
    6. Switch focus to the window you started the watcher in
    7. Use Ctrl + C to exit the watcher process
    8. Open task manager and search for node.exe
    
- Actual result:
Node.exe is still in memory after receiving the ctrl + c signal

- Expected result:
It should quit

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
This may or may not be related to this commit: https://github.com/brave/browser-laptop/commit/3ef36a4817c5679d054ae3da7fc431fe014b8c6d

Possible fix (which I reported not being able to get working): https://github.com/brave/browser-laptop/pull/9377

cc: @bridiver

**Comment by darkdh** [comment]
also npm run build

**Comment by kjozwiak** [comment]
This happens to me all the time on my Win 10 x64 machine... Makes it really difficult to QA sometimes. Definitely adding a 👍.

**Comment by bsclifton** [comment]
This issue has been fixed! Tested with a new release of Git Bash
