### ISSUE TITLE
Strange wording for restart notification

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10688]
**Describe the issue you encountered:**
I think that we need change wording for this notification. Now it sounds really strange. This was added with #10180.

![image](https://user-images.githubusercontent.com/9574457/29772277-52c8b256-8bf8-11e7-91ec-d929851dc0d4.png)

cc @bradleyrichter @cezaraugusto

**Comment by bradleyrichter** [comment]
Should be No/Yes.
