### ISSUE TITLE
webview recreated when use electron v0.37.1

### ISSUE THREAD

**Issue by cucung** [brave/browser-laptop#1068]
I want to use electron v0.37.1 (latest version), not brave's fork.

But the webview tag was recreated many times! Brave can't load any websites, Preferences and Bookmarks pages!

**Comment by bbondy** [comment]
> I want to use electron v0.37.1 (latest version), not brave's fork.

We only support Brave's fork of Electron.  Is there a particular reason why you want to use Electron which is missing key components with Brave's front end?

**Comment by cucung** [comment]
Is this the difference: 'add webview settings for secure display and running of content' https://github.com/brave/electron/commit/dfcc06589e5362c793a599c2f7a552fcad0fc938

**Comment by bbondy** [comment]
there's probably about 40 commits, you can look on the repo to see the changes.
