### ISSUE TITLE
onTabMouseMove is called too many times

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10689]
**Describe the issue you encountered:**
Window action `onTabMouseMove` is called too many times (it's not debounced) when you move mouse inside the tab. Issue is set to the same milestone as #9887

**Comment by bridiver** [comment]
Tab.onMouseMove should be debounced I think, not the action itself

**Comment by NejcZdovc** [comment]
yeah I can move debounce from action inside onMouseMove to the whole onMouseMove

**Comment by zentagonist** [comment]
@bridiver - can we get an update from you on this one.
