### ISSUE TITLE
Not being able to run master

### ISSUE THREAD

**Issue by diasdavid** [brave/browser-laptop#10681]
- Did you search for similar issues before submitting this one?

I did, didn't find any, it seems new, only started seeing it today

- Describe the issue you encountered:

I'm being unable to launch Brave in development mode

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac OS X 10.12.6

- Brave Version (revision SHA):

`e5566db96e096446742aae97610368863b32a800`

- Steps to reproduce:
    1. git clone git@github.com:brave/browser-laptop.git
    2. cd browser-laptop
    3. npm install
    4. npm run watch
    5. (in another terminal) npm run start
    
- Actual result:

![image](https://user-images.githubusercontent.com/1211152/29760956-064491d8-8bc7-11e7-91ce-afe1edbbc9bd.png)

- Expected result:

Brave running normally.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

No

- Can this issue be consistently reproduced?

Yes

- Screenshot if needed:

See above

- Any related issues:

**Comment by NejcZdovc** [comment]
@diasdavid I just tried the latest master and it's working for me. This is my setup

![image](https://user-images.githubusercontent.com/9574457/29761777-344250f8-8bcb-11e7-9839-a7f99b6de6f3.png)

**Comment by bsclifton** [comment]
@diasdavid when the `npm install` finished, were there any errors? If so, you may have to scroll up a ways (past the part where npm shows versions installed) to see the actual error

With macOS, you'll need to install Xcode tools:
`xcode-select --install`

And then I'd recommend using node version 7.9 if you're on a 8.x version and it's not working

**Comment by diasdavid** [comment]
Got it! I had an IPFS daemon running and for some reason, when running `npm run watch`, the process was not complaining that port 8080 was already being used and that is why the process of `npm run app` couldn't find the assets.

Apologies for taking your time, I was running around in circles :)
