### ISSUE TITLE
Browser crashes when trying to close other tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10696]
## Test plan

https://github.com/brave/browser-laptop/pull/11311#issue-263338498

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser crashes when trying to close other tabs

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.3
-- | --
rev | 0adbd61
Muon | 4.4.11

- Steps to reproduce:
    1. Build 0adbd61
    2. Set browser to start with home page
    3. Add multiple start pages in setting
    4. Close and relaunch the browser, ensure added pages are opened in individual tabs
    5. Open a new tab, right click on the new tab and click on close other tabs, browser crashes
    
- Actual result:
Browser crashes when trying to close other tabs

- Expected result:
Should close the other tabs

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed: Console log
``` 
$ npm start

> brave@0.19.3 start E:\srirambv\master\browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

Crash reporting enabled
[6192:5188:0828/182648.049:ERROR:CONSOLE(37293)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: http://localhost:8080/gen/app.entry.js (37293)
[6192:5188:0828/182648.049:ERROR:CONSOLE(37293)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: http://localhost:8080/gen/app.entry.js (37293)
[6192:1792:0828/182651.316:ERROR:connection.cc(1963)] Web sqlite error 5, errno 33: database is locked, sql: COMMIT
[6192:1792:0828/182651.316:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 1
process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.19.3 start: `node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.19.3 start script 'node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sriram BV\AppData\Roaming\npm-cache\_logs\2017-08-28T17_27_54_963Z-debug.log
```

- Any related issues:
cc: @bsclifton

**Comment by NejcZdovc** [comment]
@srirambv is it possible that you have two instances that are reading from the same folder. Because it says that database is locked. Can you try it again and check that one one browsers is running and you have a fresh profile? Thank you

**Comment by srirambv** [comment]
Happens even when the installed browser instance is closed.  And only one browser window open from the build . Even tried clearing `brave-development` and still happens on the new profile.

**Comment by LaurenWags** [comment]
Additional STR: tear off a tab also produces this crash.

**Comment by kjozwiak** [comment]
I'm going to rest this with newer builds as we've landed a bunch of tab improvement work in the past week or so. This might have been fixed in the process.

**Comment by bbondy** [comment]
0.19.x: 511bf20846d967d8cbfa57c5b681173ba5f5eeb3
0.20.x: 7bb52863e7412d225da791464849d2a35f101fd8
master: bf4726d9b7a780b133bb5144e08435ab798e0861
