### ISSUE TITLE
Tabs with long text overflow available area

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#1069]
<img width="1437" alt="screen shot 2016-03-13 at 5 10 01 pm" src="https://cloud.githubusercontent.com/assets/210240/13731459/7bbd28de-e93f-11e5-8e96-9860fdbd5b59.png">

To recreate - open five or six tabs with long titles in full screen mode OSX. The rightmost tabs will be larger than the available space and will not be closable.

**Comment by bbondy** [comment]
Fixed in https://github.com/brave/browser-laptop/commit/33a303f1d13eb812fdf7855dd807b7cd345ad61b
