### ISSUE TITLE
Feature Request : Feature flipper for experimentation

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10694]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
To facilitate more iterative development of features while reducing risk, it would be good to implement a feature flipper.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.21.0

Perhaps a preference pane would be the most useful instead of a degree of obfuscation via about pages.

**Comment by Jacalz** [comment]
+1 from me, great way to enable experimental features 👍

**Comment by bsclifton** [comment]
brave-core has chrome://flags available 😄
