### ISSUE TITLE
Debug not working with visual studio code

### ISSUE THREAD

**Issue by Gabrielglvr** [brave/browser-laptop#10695]
- Describe the issue you encountered:
I'm trying to debug with vscode, but the application is not starting when i selected the "launch" mode. I added in start script the "--inspect" annotation and finally node launch with debug mode but when i'm debugging the break point is not hitting.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04.02 LTS
Node v8.4.0
Visual studio code 1.15.1

- Brave Version (revision SHA):
053c863

- Steps to reproduce:
    1. git clone from git@github.com:brave/browser-laptop.git
    2. npm install in application folder
    3. open with vs code and select launch in debug mode.

**Comment by bsclifton** [comment]
@Gabrielglvr can you check what you've tried against the docs here?
https://github.com/brave/browser-laptop/blob/master/docs/debugging.md#debugging-the-browser-process-with-vs-code
