### ISSUE TITLE
Torrent viewer URL bar has border radius 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10692]
## Test plan
1. Enable Brave payments
2. Visit https://webtorrent.io/torrents/big-buck-bunny.torrent
3. Put mouse over title bar area if needed (if title bar is enabled)
4. URL bar should not have border radius with publisher icon

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Torrent viewer URL bar has border radius 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.3
-- | --
rev | 0adbd61
Muon | 4.4.11

- Steps to reproduce:
    1. Visit https://webtorrent.io/torrents/big-buck-bunny.torrent
    2. URL bar has border radius with publisher icon
    3. Open a new tab, visit any site, URL bar doesn't have any border radius
    
- Actual result:
See screenshot

- Expected result:
Should only show border radius when publisher icon is not shown 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/29780728-b373d6ec-8c0e-11e7-8d5d-a7755ca41012.png)

- Any related issues:
#7449

**Comment by arsalankhalid** [comment]
Is this issue still available? I'd like to take this over :)

**Comment by bsclifton** [comment]
@arsalankhalid absolutely! I'll assign myself so that nobody grabs it 😄

**Comment by arsalankhalid** [comment]
Sure thing, thanks for the quick response. How come it's assigned to you though, shouldn't it be assigned to the developer carrying out the task (: 

But will carry this out!

**Comment by arsalankhalid** [comment]
I'm not sure I'm seeing what you're describing, i.e:

![image](https://user-images.githubusercontent.com/5307218/35477967-7f931768-039e-11e8-94e3-2254771777e6.png)

Any advice?

**Comment by bsclifton** [comment]
@arsalankhalid It's hard to spot- but the right-hand side of the URL bar should not be rounded (for some reason, it has border-radius). It should be square, like this:
![screen shot 2018-01-27 at 11 13 03 pm](https://user-images.githubusercontent.com/4733304/35479563-ccd826ee-03b7-11e8-8b85-652b68566918.png)

I assigned myself since you are not added to the Brave organization or the browser-laptop repo 😄 Unfortunately, GitHub won't allow people to be assigned unless they're added OR they're the one who opened the issue

**Comment by arsalankhalid** [comment]
Ah thank you sir, much more noticeable now. 
However, what's interesting is that when running brave through a dev environment - one doesn't even see the heart/book mark option: 

![image](https://user-images.githubusercontent.com/5307218/35488739-176fd38e-045b-11e8-9d7b-442bbb988ec3.png)

Interestingly enough, the URL bar is rounding for every URI in my dev browser, im investigating where the border-radius is defined though, thanks for your help so far!

**Comment by arsalankhalid** [comment]
Here you are sir: https://github.com/brave/browser-laptop/pull/12897
Note that I changed a line in the docs too, found the directory structure there to be wrong, and also effed up a commit, so reverted it. There doesn't seem to be aggressiveness on dirty commits in PRs from what I've seen so far, but if preferred than I can remove it. 

Thanks for your help thus far, if solution too hacky please advise :)
