### ISSUE TITLE
right-click to open link in new tab does not open link to direct right of parent tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10709]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When you right-click on a link to 'open link in new tab', the tab is not opened directly to the right of the parent tab. Instead, the new tab is placed at the far right of all open tabs.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
0.19.x
rev | ea0ea7b
Muon | 4.4.11

- Steps to reproduce:
    1. Using clean profile, open 0.19.x.
    2. In the first tab open a site that has links, such as nytimes.com.
    3. Open a second tab and navigate to a different site.
    4. Go back to the first tab and right click on a link, select 'Open link in new tab' option.
    
- Actual result:
Link is opened as 3rd tab.

- Expected result:
Link should be opened as 2nd tab, directly to the right of the parent tab. (this is how it works in 0.19.3 packaged build and 0.18.23 released version).

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
0.19.x
![taborder](https://user-images.githubusercontent.com/28145373/29844501-81f60b10-8cdd-11e7-92c6-c65f1a027ccc.gif)

0.18.23
![taborder01823](https://user-images.githubusercontent.com/28145373/29844983-2eb28ae4-8cdf-11e7-9e35-f0257fb9bc05.gif)

- Any related issues:

**Comment by diracdeltas** [comment]
i'm seeing this issue in 0.18.23

**Comment by diracdeltas** [comment]
as of today i no longer see this issue in 0.18.x or master. i think @bbondy fixed it with 35ea80248a22daccb21f3c76bb21d5bbeca27018

@LaurenWags please confirm it's fixed for you too

**Comment by bbondy** [comment]
moving to 0.18.x and marking as closed so QA will pick it up. 
cc @kjozwiak  too
