### ISSUE TITLE
Publisher icon is not shown on URL after page load

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10707]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Publisher icon is not shown on URL after page load

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.3
-- | --
rev | 0adbd61
Muon | 4.4.11

- Steps to reproduce:
    1. Build from 0adbd61
    2. Enable payments and disable auto-include sites
    3. Visit sites in new tab, publisher icon is not instantly loaded after page load is complete
    
- Actual result:
See screenshot

- Expected result:
Should load the publisher icon when the page is loaded

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes was able to reproduce it on new development profile

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![publishers1](https://user-images.githubusercontent.com/17010094/29832315-b342f7da-8cdf-11e7-8163-17283ec37cee.gif)

- Any related issues:

**Comment by alexwykoff** [comment]
@srirambv this needs to a regression range check vs prior releases

**Comment by srirambv** [comment]
Verified on packaged builds `0.15.2`, `0.15.310`,`0.15.314`,`0.16.9`,`0.17.13`,`0.18.14`,`0.18.23`, `0.18.29` but was not able to reproduce it

**Comment by NejcZdovc** [comment]
@srirambv I tried to reproduce this on 0.19.x branch but I am not successful, if I paste http://timesofindia.indiatimes.com/ into url and press enter everything is working correctly.

**Comment by srirambv** [comment]
I tried 0.19.x with 26d5e7e and could not reproduce.

**Comment by alexwykoff** [comment]
Let's close this @srirambv feel free to reopen if you see it again.
