### ISSUE TITLE
Sites are not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10702]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Friend of mine reported a problem to me. He couldn't add any bookmarks. When I loaded his session into 0.18.x branch I noticed that `sites` in the state was List and not Map. Because of that bookmarks, history and everything related to sites is not working.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
0.18.23
- Steps to reproduce:
I don't have any particular steps (couldn't reproduce it on a clean profile), but he said that chrome imported failed for him. Also he didn't visit any site. He just imported from chrome and then go directly to the preferences and enable sync and ledger (ledger didn't work for him; toggle didn't do anything). After that he started visiting sites. Tabs are working correctly and pages are loaded, but you can't bookmark it or see history.
    
- Actual result:
Browser is not usable, because bookmarks are not working
- Expected result:
Bookmarks should work
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
not yet :smiley: 
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
not yet :smiley:

**Comment by bsclifton** [comment]
@NejcZdovc can you update the title to be more descriptive? (ex: what is the symptom?)

**Comment by NejcZdovc** [comment]
@bsclifton any ideas to what? Basically sites are empty and are defined as List and not as Map, because of that bookmarks, history, top sites, etc are not working (you can't add it to the list as you would for map like `sites.setIn(['sites', key], object)`)

**Comment by bsclifton** [comment]
@NejcZdovc was this from a fresh install? You mention the 0.18.x branch... so it sounds like this was when running from source.  To characterize this, I think we need to do the following:
- Delete any existing Brave installs / data associated
- Clean install Brave
- Re-run the import bookmarks process
- Confirm/Deny if bookmarks show in bookmarks manager / bookmarks toolbar
- Confirm/Deny if history shows after visiting a few sites

**Comment by NejcZdovc** [comment]
@bsclifton this was a production build that my friend installed from brave page. I tried to reproduce it, but so far without success. I tried everything that you listed above. So far my only solution is to check if object is list and convert it to map before adding into sites. I know that this is not a solution to the original problem, but at least user can use browser.

**Comment by bsclifton** [comment]
Closing as there isn't enough information here to troubleshoot
