### ISSUE TITLE
Bitwarden has issues on Windows with high DPI

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10706]
Per https://github.com/brave/browser-laptop/issues/4776#issuecomment-325640315 (by @srirambv)
![image](https://user-images.githubusercontent.com/17010094/29819498-ebf9519a-8cb8-11e7-95fd-7a787a65dad1.png)

(notice the popup)

Resolution is 1920x1080  with DPI set at 125%. The browser UI scale is default.

**Comment by bsclifton** [comment]
related / possible duplicate of https://github.com/brave/browser-laptop/issues/7051

**Comment by jonathansampson** [comment]
Duplicate issue detailed in #10213. I believe this is the same as #7051.

**Comment by bsclifton** [comment]
Closing as duplicate of #7051
