### ISSUE TITLE
Drag tab to new window

### ISSUE THREAD

**Issue by ricardosaracino** [brave/browser-laptop#10710]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Drag a tab to create a new window, previous window has a blank tab, it should default to the last active tab on that window

- Platform (Win7, 8, 10? macOS? Linux distro?):
win 10

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. create new tab
    2. drag out of window
    
- Actual result:
new window, previous window is blank

- Expected result:
previous window should show last active tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![2017-08-29 1](https://user-images.githubusercontent.com/759253/29845626-a0956be8-8ce1-11e7-9157-a178834b3e51.png)

- Any related issues:

**Comment by bsclifton** [comment]
Thanks for the report, @ricardosaracino 😄  @bbondy is working on this- we actually have this captured with issue https://github.com/brave/browser-laptop/issues/9671 if you wanted to track it.  I'll close this issue since it's a duplicate
