### ISSUE TITLE
Top of Brave Disappears

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10729]
#### Did you search for similar issues before submitting this one?
Yes

#### Describe the issue you encountered:
At times, the top of Brave will disappear. It's as if the entire UI of the browser has been shifted upwards. When this happens, only the bottom portion of the active tab is visible.

#### Platform (Win7, 8, 10? macOS? Linux distro?):
Windows (Tentatively)

#### Brave Version (revision SHA):
Brave: 0.18.23
Revision: 36ae2ec
Muon: 4.3.10
OS: Windows (10.0.14393) x64

#### Steps to reproduce:

_The following steps need to be carried out from the Master branch._

1. Open a fresh window
2. Navigate to `chrome://crash`
3. Type 'f' in address-bar to invoke _Suggestion List_
4. Press down-arrow to move down the suggestion list

Note the disrupted UI.
    
#### Actual result:
Brave UI is prone to break.

#### Expected result:
Brave's UI should not break; ever.

#### Is this an issue in the currently released version?
Yes

#### Can this issue be consistently reproduced?
No

#### Screenshot if needed:

![zsfabup](https://user-images.githubusercontent.com/815158/29950583-4aa7562c-8e82-11e7-8b02-278645f11957.gif)

**Comment by bbondy** [comment]
@bridiver mentions:

```
[9:48] 
I’ve seen something like this, but I thought it was only happening in debug builds


[9:48] 
I know what causes it in debug builds and I have a fix for that


[9:48] 
but not sure if this is the same issue


[9:49] 
in some cases we are attempting to call `chrome.webFrame.setGlobal` on an undefined object/property
```

**Comment by bsclifton** [comment]
I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/8574

**Comment by bridiver** [comment]
@bsclifton I don't think this is a duplicate. When I saw the problem the UI was completely gone and it wasn't autocomplete related

**Comment by jonathansampson** [comment]
### Repro Steps:

_The following steps need to be carried out from the Master branch._

1. Open a fresh window
2. Navigate to `chrome://crash`
3. Type 'f' in address-bar to invoke _Suggestion List_
4. Press down-arrow to move down the suggestion list

Note the disrupted UI.

**Comment by jonathansampson** [comment]
After further discussion with @bridiver, we feel this issue is sufficiently similar to https://github.com/brave/browser-laptop/issues/8574 that it can be closed as a duplicate. A fix for both issues is in motion, and should land soon.

**Comment by bbondy** [comment]
master: e1066fd
0.20.x: a2cf1b5
0.19.x: 2636521
