### ISSUE TITLE
Http referrer not blocked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10721]
## Test plan

https://github.com/brave/browser-laptop/pull/10726#issue-254163106

----

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
From community 
>why does Brave not hide my referer by default? How do I hide my referer? I thought this browser is about protecting me from ads and beeing tracked?
Tested with DuckDuckGo, Bing and Google:
https://www.whatismyreferer.com/2
https://referer.rustybrick.com/1

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.18.23
-- | --
rev | 36ae2ec
Muon | 4.3.10

- Any related issues:
https://community.brave.com/t/tracking-not-blocked/6787
cc: @diracdeltas

**Comment by diracdeltas** [comment]
Appears to be a regression. Marking for hotfix
