### ISSUE TITLE
Crash sometimes occurs when moving Brave tabs between windows

### ISSUE THREAD

**Issue by bytesoverbombs** [brave/browser-laptop#10724]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When moving a tab from one Brave window to another
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7
- Brave Version (revision SHA):
Brave Version: 0.18.23 (36ae2ec06efed0057ae16351108bf4d4c10a7ab4)
- Steps to reproduce:
    1. Open two Brave browser windows
    2. Move tab between windows
    3. Observe that the tab becomes unresponsive
    
- Actual result:
Tab crashes (i.e. becomes unresponsive)
- Expected result:
Tab continues to work as expected
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
No, this error occurs rarely, but enough that it felt sufficient to file a bug report.
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
No, but the issue is reoccurring
- Extra QA steps:
    1.None
- Screenshot if needed:
N/A
- Any related issues:
No

**Comment by oscalation** [comment]
so, i experience this bug. It's not rare for me in my environment. If you open a brave instance, open multiple tabs. Then drag and drop the tab into a new window - then drag it back into the original window - 9 times out of 10 it will crash. I can reproduce this pretty easily on my end.

**Comment by NumDeP** [comment]
I had a similar issue After 04:30 PDT, before 04:50 PDT 14/Sep/17 - I have 'Send anon crash reports to Brave' enabled and was wondering if you can disclose what happened.
 
I basically just opened a Git account, had around four tabs opened, the fourth tab being my email account to verify the Git account, my email has two steps to it which require two passes (not 2-factor) and the browser displayed both times if Brave should save password, I declined and a minute or so after I entered the account and as the second verification email appeared and just before I went to open it the browser, the browser crashed.
