### ISSUE TITLE
Newer tabs turn black and don't work on a reload

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#1072]
I've noticed that when I have brave open for a long time (days, with periods of suspend) and have numerous tabs open, newer tabs that were opened by a link from another tab (e.g. from facebook) and that I have switched away are sometimes displayed black when I switch back to them. If I hit reload the tab redisplays the content as it was when I left it but I can't scroll, click on links or do anything else with it. 

This is on Windows 10

Brave Version: 0.8.0
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110
Channel: dev

This may be related to issue #1053 but I'm not sure as the way to produce the effect seems wildly different

**Comment by FrancisTurner** [comment]
Further playing

Once a tab is in this dead state it is possible to load a new page by typing a URL in the address bar, but, as with a reload, once the page has displayed you can scroll, click links etc.

**Comment by FrancisTurner** [comment]
Additional note. I had originally thought this applied to all tabs. It doesn't. Older tabs that have been around for days work fine. NEWER tabs are the ones that exhibit the problem.

**Comment by bbondy** [comment]
Pls check `Command + Alt + I` next time it happens for JS console issues on the webview.

**Comment by FrancisTurner** [comment]
(Assuming you mean Ctrl-alt-I since this is windows)

When it's black I get the following
![2016-03-15](https://cloud.githubusercontent.com/assets/991242/13779043/5a544992-ea76-11e5-8c8b-8332ccd270e9.png)
When white I get no console errors
![2016-03-15 1](https://cloud.githubusercontent.com/assets/991242/13779108/b35a4ef6-ea76-11e5-970f-3872603c95aa.png)

**Comment by FrancisTurner** [comment]
Further observation. If you have a history in this dead tab, you can go back and forward using the < and > buttons at the top. Each page loads but you that is all

**Comment by bbondy** [comment]
You can check Control+Alt+J as well for the Browser level dev tools to see if that shows anything in that console.  I would have hoped for something in the content level dev tools though which was blank.

**Comment by luixxiul** [comment]
Maybe fixed in #1588?

**Comment by luixxiul** [comment]
Closing for now.
