### ISSUE TITLE
Bloodhound improvements for start up time

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10723]
**Describe the issue you encountered:**
As described in https://github.com/brave/browser-laptop/issues/3025#issuecomment-323767720 bloodhound takes 3-4 seconds when starting up. We will save this with chunking sites into multiple intervals, this way we will not block startup time. Also we can remove `fromJS()` conversion and make bloodhound Immutable

**Comment by luixxiul** [comment]
needs-qa-test?

**Comment by bbondy** [comment]
QA needed for this one yes, make sure suggestions work properly in general. Nejc can say more specifically.

**Comment by cezaraugusto** [comment]
@NejcZdovc could you make a test plan for this so QA could validate? thanks!

**Comment by NejcZdovc** [comment]
@cezaraugusto no specific QA steps. Just make sure that auto suggestion is working, which I think is already part of general pass
