### ISSUE TITLE
Tabs not rendering properly

### ISSUE THREAD

**Issue by ritesh-pandey** [brave/browser-laptop#1073]
![screenshot from 2016-03-14 18 40 43](https://cloud.githubusercontent.com/assets/1433681/13745495/5cca9d14-ea14-11e5-9af4-fa8205e83240.png)

CSS rule `overflow: auto` on class `tabs` seems to be the problem.

System
Ubuntu 14.04 64 bit

**Comment by bbondy** [comment]
you're doing a build right? I think you need to upgrade to Chrome v49 based electron.  
Note that it'll change again though before the 0.8.1 release so you'll want to rm -Rf ~/.electron when 0.8.1 is released and npm install again.

To fix what you have now you can just re-install your node_modules

**Comment by bbondy** [comment]
Please let us know if it's still a problem after that, closing for now.

**Comment by cwmke** [comment]
I'm having this same issue on 0.8.1 using the binary in Arch Linux.

Brave: 0.8.1
Electron: 0.37.2
libchromiumcontent: 49.0.2623.75
V8: 4.9.385.28
Node.js: 5.8.0
Update channel: dev

**Comment by ritesh-pandey** [comment]
Run 
`npm install` 
and try again.

It worked for me.

**Comment by bbondy** [comment]
Also try removing ~/.electron before doing another npm install, and clear out your node_modules.

**Comment by cwmke** [comment]
I deleted the directory as instructed and tried again but no luck.  I didn't install with npm.  Arch uses the binaries from github.  Thanks.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brave-browser-bin
