### ISSUE TITLE
Gap on bookmarks toolbar on Mac

### ISSUE THREAD

**Issue by paulusm** [brave/browser-laptop#10740]
There is a waste of real estate and some of my bookmarks are wrapped and invisible, even though there is space to show them

Mac Yosemite
Brave 0.18.23

Steps to reproduce:
    1. Add lots of bookmarks (icon + text)
    2. Size window to large

  
<img width="1229" alt="screen shot 2017-08-31 at 12 19 58" src="https://user-images.githubusercontent.com/808541/29920738-bfb31190-8e46-11e7-9dcb-735e91d83d20.png">

- Expected result:
should be able to see more bookmarks

**Comment by luixxiul** [comment]
duping to:
https://github.com/brave/browser-laptop/issues/4116
https://github.com/brave/browser-laptop/issues/9939
https://github.com/brave/browser-laptop/issues/10594

please subscribe to https://github.com/brave/browser-laptop/issues/9939 for future announcements, thanks.
