### ISSUE TITLE
Downloading a file with the same name overwrites first download file

### ISSUE THREAD

**Issue by schopenhauer** [brave/browser-laptop#10741]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Downloading a file with the same name overwrites first download file

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
36ae2ec

- Steps to reproduce:
    1. Download a first file named "download.pdf"
    2. Download a second file named "download.pdf"
    
- Actual result:
There is only one file in the Downloads folder with the contents of the second "download.pdf"

- Expected result:
This should append an index to the filename to avoid overwriting, e.g. "download (2).pdf"

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![image](https://user-images.githubusercontent.com/2085103/29928093-5ca29946-8e68-11e7-96f1-ef976b333519.png)

- Any related issues:
None

**Comment by luixxiul** [comment]
it's been fixed on https://github.com/brave/browser-laptop/issues/7764. The fix will be available on 0.21, thanks.
