### ISSUE TITLE
Support for Ubuntu Artful

### ISSUE THREAD

**Issue by mati865** [brave/browser-laptop#10755]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Ubuntu Artful beta has been released today and it will encourage people to try it, Brave should prepare repository for it.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 17.10
- Brave Version (revision SHA):
NA
- Steps to reproduce:
    1. Follow [official instructions](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-zesty-yakkety-xenial-and-trusty-amd64)
    2. `apt update` throws 403 error
    3. `apt install brave` fails
    
- Actual result:
Cannot install Brave.
- Expected result:
Brave should install.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. Test on Ubuntu Artful
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
This issue should be named "Support for Ubuntu Artful".

**Comment by Ramon-Cornelius** [comment]
I'm encountering the same thing on LinuxMint.  Presumable the same issue since LinuxMint is based on Ubuntu, right?

**Comment by mati865** [comment]
@Liunkae Oops, my bad.

@Ramon-Cornelius I don't know how Mint repository structure, could you post full log in separate issue?

**Comment by bsclifton** [comment]
@mati865 this should be live now 😄  Please let us know if you're able to get it

**Comment by mati865** [comment]
It works fine. Error on `apt update` is gone and `apt install brave` installs package.
