### ISSUE TITLE
cannot sort by publisher verification status in about:preferences#payments

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#10752]
- Did you search for similar issues before submitting this one?
yes

- Platform (Win7, 8, 10? macOS? Linux distro?):
macos

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. go to about:preferences#payments
    2. click on the first column header to sort by publisher verification status
    
- Actual result:

the table is not sorted

- Expected result:

the table should be sorted

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by arsalankhalid** [comment]
Pretty sure this issue should be closed now, no?

**Comment by NejcZdovc** [comment]
It will be closed when we merge #12750, but we need to wait until correct milestone is up before merging

**Comment by srirambv** [comment]
Works fine on Windows
![10752](https://user-images.githubusercontent.com/17010094/36481909-5fa3a2e0-1737-11e8-86ba-1cc2dad2ac7a.gif)

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.
