### ISSUE TITLE
Unable to view 'My Vault' in LastPass or Edit Sites, causes UI to become unresponsive

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10769]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Using 0.18.24 when I try to view 'My Vault' in LastPass, the UI freezes and my vault never displays. I can scroll, click on links, etc in the tab I am currently in, but I am unable to navigate to any other tabs or use back button, hamburger menu, etc.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.24
rev | 1853c35
Muon | 4.3.14

- Steps to reproduce:
    1. Using 0.18.24 enable LastPass and login.
    2. Have a couple of tabs open.
    3. Click on LastPass icon > select My Vault.
    
- Actual result:
UI (except for current tab) is unresponsive (can't click on other tabs, use back button, 3 dots menu, etc). My Vault doesn't display. 

- Expected result:
UI should be responsive. My Vault should open in a new tab as it did in 0.18.23.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Click on LastPass Icon > Sites > Navigate to a site you have saved in the list, click on the wrench for that site (icon on the right)
    2. Click on Edit.
    3. Again, UI becomes unresponsive and you cannot edit the site.

- Screenshot if needed:
![lastpass](https://user-images.githubusercontent.com/28145373/29987531-a92d6ad8-8f36-11e7-919a-85b74a67899a.gif)

- Any related issues:

cc: @jonathansampson

**Comment by LaurenWags** [comment]
Different behavior on 0.18.25. UI is no longer unresponsive after selecting 'My Vault' etc. However, when you do select 'My Vault' or try to edit a site, a blank tab that you cannot click on is opened. So you still cannot access your vault or add/edit sites, etc.

![screen shot 2017-09-01 at 5 42 30 pm](https://user-images.githubusercontent.com/28145373/29988773-f5167880-8f3c-11e7-9487-089a2ed1bfb6.png)

**Comment by Samizdata** [comment]
I am seeing exactly the same "broken tab" behaviour as posted in the .18.25 follow up.  I only went dev branch to fix the Netflix problem.  I have noticed when I try to access settings after the "broken tab" appears, it will create a second "broken tab".  

Really, folks, I want to make Brave my one browser, but the ongoing issues are precluding that as well as other issues as not getting extensions like GreaseMonkey/TamperMonkey and getting shopping extensions instead, making me also unable to recommend it to other people.

**Comment by bbondy** [comment]
Fixed:
https://github.com/brave/muon/commit/4372ae43408f012dbe496d3f1dac136aac43ddc7

Fix will be in muon 4.3.16

**Comment by srirambv** [comment]
Verified. Works on upgrade from 0.18.24 - 0.18.27

**Comment by Samizdata** [comment]
Seconding confirmation on bugfix.
