### ISSUE TITLE
Private tab in its own window causes that window to be white on relaunch (and sometimes unusable)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10768]
## Test plan

https://github.com/brave/browser-laptop/pull/11169#issue-260846709

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When a Private tab is in its own window prior to Brave being is closed/relaunched, that window appears all white on relaunch and is in some cases unusable.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS, verified on Win by @kjozwiak 

- Brave Version (revision SHA):
0.18.24

- Steps to reproduce:
    1. Launch Brave. 
    2. Load two tabs with any two sites. 
    3. Create a new Private tab and load a site.
    4. Tear off/detach the Private tab so it is now in its own window. (you now have two windows)
    5. Close/relaunch Brave.
    6. Window which had the Private tab displays all white.
    
- Actual result:
Window which had the Private tab displays all white (appears dead). You can however type in the URL bar and load a site.

- Expected result:
Window should either display what your selection for what 'a new tab shows' or not be there at all since it held a private tab prior to closing Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, 0.18.23

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Launch Brave. 
    2. Load two tabs with any two sites. 
    3. Create a new Window (you now have two windows). Create a Private tab and load a site. Close the normal tab that was in this window.
    4. Close/relaunch Brave.
    5. Window which had the Private tab displays all white. Note - this time you can't reuse this window. If you type in the URL bar, the tab loads with site tab name, but no content displays in the tab.

- Screenshot if needed:
Prior to close:
![screen shot 2017-09-01 at 4 02 55 pm](https://user-images.githubusercontent.com/28145373/29985909-0ef8bbea-8f2f-11e7-855f-680f2481c1c3.png)

After relaunch:
![screen shot 2017-09-01 at 4 03 33 pm](https://user-images.githubusercontent.com/28145373/29985919-205538c8-8f2f-11e7-9204-9328caf33801.png)

- Any related issues:

**Comment by syuan100** [comment]
If there's only one incognito tab then the window probably shouldn't even re-open right?

**Comment by bsclifton** [comment]
@syuan100 great point 😄  That tab should be removed

@LaurenWags what happens to private tabs when there is only one window (which has other tabs)?  I'm guessing the private tabs are just removed.  I think we'll need to update the logic here to auto-close the window when no more tabs exist

**Comment by LaurenWags** [comment]
You are correct @bsclifton - the private tab is just removed from the window with other tabs.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
