### ISSUE TITLE
Clicking on Pocket icon saves the Pocket login page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10762]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicking on Pocket icon saves the Pocket login page

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.24
-- | --
rev | 1853c35
Muon | 4.3.14

- Steps to reproduce:
    1. Enable Pocket from Extensions page, Wait for the login page to open in a new tab
    2. Use the login page opened to sign in to your account
    3. Once logged in click on the Pocket icon, launches a new tab for pocket login and saves it. 
    
- Actual result:
Clicking on Pocket icon saves the Pocket login page

- Expected result:
Should just open the login page but not save it

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes on 0.18.23. Need triage

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @jonathansampson @kevinlawler

**Comment by jonathansampson** [comment]
Repros in Chrome. Closing as `by-design`.
