### ISSUE TITLE
Brave Browser fonts look bad on the snap.

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#10761]
Hi. When i open brave after installing the snap (snap install brave --beta), fonts look bad. (Windows XP Like)

My distro is Solus.

Please fix, thanks.

**Comment by luixxiul** [comment]
how bad is that? mind taking a screenshot of the window? thanks

**Comment by As4fN1v** [comment]
Bad font:
http://i.cubeupload.com/wYGhwy.png
Good font:
http://i.cubeupload.com/wyRP1p.png

**Comment by CrisBRM** [comment]
Same here.

**Comment by Jacalz** [comment]
Same issue for me, the font looks absolutely terrible when using from snap package 😕

**Comment by veshi11** [comment]
same issue with my brave browser..on solus os after install brave from snap fonts of browser are not good.

**Comment by Jacalz** [comment]
I tested on Solus and the font looks absolutely terrible and it seems like most of us are having the issue on Solus. Were you testing on Solus too @CrisBRM ?
I believe that the font looks good on Ubuntu and Debian but I have no idea of Arch 😅

**Comment by CrisBRM** [comment]
@Jacalz Yup. I could try on gentoo, but that will have to be a bit later.

**Comment by Jacalz** [comment]
Awesome, will see on Ubuntu 16.4.4 🙂

**Comment by taaem** [comment]
Its probably the same issue the chromium guys faced when snapping up chromium.
You can follow their bug tracing here: https://forum.snapcraft.io/t/call-for-testing-chromium-61-0-3163-100/2278/21
Looking at the latest stable chromium snap, they *still* have the same issue so maybe it makes sense to connect with the devs behind that snap and work on a solution together.

**Comment by flare04** [comment]
I have the same issue on Fedora 28.  Few sites look sane, most look awful
