### ISSUE TITLE
Disabling Torrent Viewer doesn't disable Torrent Handling

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10767]
## Test plan
1. Visit about:preferences#extensions and disable `Torrent Viewer` (if not already disabled)
2. Restart if prompted
3. Verify extension is disabled
4. Visit https://www.qubes-os.org/downloads/
5. Click `Torrent` button
6. You should be prompted to save the torrent file

#### Did you search for similar issues before submitting this one?
Yes

#### Describe the issue you encountered:
Brave's native handling of .torrent files can be problematic for some sites (#10672). In an attempt to work around this issue, I sought to disable the built-in Web Torrent extension. Unfortunately, Brave still attempts to pass .torrent requests off to Web Torrent, which is unavailable after being disabled.

#### Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

#### Brave Version (revision SHA):
0.18.23 (https://github.com/brave/browser-laptop/commit/36ae2ec06efed0057ae16351108bf4d4c10a7ab4)

#### Steps to reproduce:
1. Disable Torrent Viewer in about:preferences#extensions (and restart Brave)
2. Open Brave, then attempt watch a video on bitchute.com
3. Note that Brave attempts to pass .torrent requests to extension
    
#### Actual result:
Brave attempts to handle torrent requests long after Torrent Viewer has been disabled.

#### Expected result:
Disabling Torrent Viewer causes Brave to leave .torrent requests alone.

#### Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

#### Is this an issue in the currently released version?
Yes

#### Can this issue be consistently reproduced?
Yes

#### Screenshot if needed:

![image](https://user-images.githubusercontent.com/815158/29985269-d92763a0-8f23-11e7-8239-498becb9e767.png)

#### Any related issues:
#10672

**Comment by luixxiul** [comment]
I remember @srirambv maybe has reported a similar issue for a while ago.

**Comment by pongraczi** [comment]
+1 Linuxmint 64 bit
Brave: 0.18.29 
rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 
Muon: 4.3.16 
libchromiumcontent: 60.0.3112.113 
V8: 6.0.286.56 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

![kijeloles_582](https://user-images.githubusercontent.com/5891983/30333880-4eb83f6e-97de-11e7-8c93-093252f325f5.png)

**Comment by pongraczi** [comment]
Still exists in    
Brave: 0.18.32 
rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 
Muon: 4.3.18 
libchromiumcontent: 61.0.3163.71 
V8: 6.1.534.31 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by pongraczi** [comment]
FYI: still exists in
 
Brave: 0.19.24 
rev: 3b3fba2074395acb60954629a429b2d03d777f4a 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/brave-closes-the-page-and-tries-to-download-torrent/10214/2

**Comment by vaguiners** [comment]
jesus fuck
someone do something wtf 
this is the only thing that keeps me from having brave as my main browser. a userscripts plugin would be useful as well and would bring many users to the community, but TAKE THIS ERROR AWAY PLEASE GOD

**Comment by bsclifton** [comment]
@vaguiners let's keep it civil in here please.  I would like this issue fixed too, but let's refrain from using nasty language

**Comment by ocramc** [comment]
Still present in 0.20.30, release channel

**Comment by hugobuddel** [comment]
The torrent file is actually downloaded in 0.20.30 though, so it is not that problematic. But since #11452 is fixed, I'll try to reenable the plugin.

**Comment by pongraczi** [comment]
Still exists:
 ```
Brave: 0.20.46 
V8: 6.4.388.41 
rev: 5eb035c2d68225994a572a1d62861cf961355ab2 
Muon: 4.8.2 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140```

**Comment by bsclifton** [comment]
+1 from @kjozwiak via https://github.com/brave/browser-laptop/issues/13619
> Saving .torrent files while Torrent Viewer is disabled via about:preferences#extensions will produce a This site can’t be reached tab page while the Save as.. prompt is displayed.

**Comment by przemika** [comment]
+1

**Comment by lvella** [comment]
It is sad to not be able to use the browser because you can't download a plain torrent file.

**Comment by kjozwiak** [comment]
@bsclifton can we include this into https://github.com/brave/browser-laptop/milestone/114? @NejcZdovc has a PR ready and we've gotten a good amount of folks from the community that would like this fixed as well.

**Comment by bsclifton** [comment]
@kjozwiak absolutely 😄 👍

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.718 11dcd19
* muon 6.0.12
* libchromiumcontent 66.0.3359.170

**Comment by srirambv** [comment]
@bsclifton @NejcZdovc does the fix for the issue removes handling of .torrent files? With Torrent viewer enabled in extensions, clicking a .torrent file used load it in the tab for download but not any more. Is this expected?

**Comment by NejcZdovc** [comment]
@srirambv so torrent viewer is not loaded anymore if you have it enabled?

**Comment by srirambv** [comment]
@NejcZdovc yes correct

**Comment by NejcZdovc** [comment]
let me try it

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
* 0.22.719     a9e0956
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
