### ISSUE TITLE
tab name for about pages not always updated

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10766]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When reusing a tab that has an about page loaded (about:bookmarks, about:extensions, etc) to view another about page (about:history, etc) doesn't always update the tab name (sometimes it shows the name of the previous about page, sometimes it displays 'chrome-extension...').

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.24
rev | 1853c35
Muon | 4.3.14

- Steps to reproduce:
    1. Navigate to a page that already has an 'about' page loaded (such as about:adblock, about:bookmarks, etc).
    2. In the URL change the about page to be a different one that you haven't visited yet (about:extensions, about:history, etc). Be sure not to move your mouse.
    3. 
    
- Actual result:
Sometimes the tab name doesn't update to reflect the new about page. It either displays the previous tab name or the tab name shows 'chrome-extension...'. If you hover over the tab name it updates or if you click on another tab, it updates.

- Expected result:
Tab name should update to reflect the new page.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, but not consistently. It seems as though it happens more if you've closed/relaunched Brave.

- Is this an issue in the currently released version?
Yes (0.18.23)

- Can this issue be consistently reproduced?
No, not consistently.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screen shot 2017-09-01 at 2 39 34 pm](https://user-images.githubusercontent.com/28145373/29983820-95922aa6-8f25-11e7-9b37-1b99951607f3.png)

![screen shot 2017-09-01 at 2 47 28 pm](https://user-images.githubusercontent.com/28145373/29983831-9d76cbc8-8f25-11e7-8be6-b38334d4996e.png)

![screen shot 2017-09-01 at 2 48 56 pm](https://user-images.githubusercontent.com/28145373/29983838-a4d2e816-8f25-11e7-9d3c-5c3cc3230c6e.png)

- Any related issues:

**Comment by kjozwiak** [comment]
Reproducible under Win 10 x64 Build 15063 as well.

![aboutissue1](https://user-images.githubusercontent.com/2602313/29984793-f69c9c6a-8f29-11e7-82d7-2195fe53b7ae.PNG)

![aboutissue2](https://user-images.githubusercontent.com/2602313/29984796-f8b315ba-8f29-11e7-8a96-9e7431a3d80d.PNG)

**Comment by bsclifton** [comment]
@LaurenWags @kjozwiak is this issue the same as https://github.com/brave/browser-laptop/issues/7765?

**Comment by NejcZdovc** [comment]
@bsclifton yeah I think it's the same, we have this problem for a while now
