### ISSUE TITLE
Display Torrents in Downloads Bar

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10770]
#### Feature Request

The torrent-download experience is currently different from the standard download experience. A user [recently suggested](https://twitter.com/Kerberosmansour/status/903744805259407360) the two be brought more into alignment by showing torrent-downloads and download progress in the Downloads Bar.

> **Sherif Mansour (Kerberosmansour)**
> *Replying to BraveSampson brave kalilinux*
> #FeatureRequest brave integrate the torrents into the download section  Want to close the webtorrent window and know its still running

**Comment by bsclifton** [comment]
cc: @bradleyrichter @jenn-rhim @alexwykoff

**Comment by tomlowenthal** [comment]
Do we have this one in the Chromium codebase slash should we open an enhancement for it there?
