### ISSUE TITLE
Tabs per tab page input bug

### ISSUE THREAD

**Issue by plieblang** [brave/browser-laptop#1077]
The Tabs per tab page preference doesn't allow you to type in double-digit numbers.  If you do so, it ends up at 20.
If you type a number from 10-19, it goes briefly to 3 and then to 20.  I think this happens because it doesn't allow the first digit to be less than 3 and so sets it to 3 immediately after an "invalid" number is detected.  Then once you type in the second digit, it will interpret it as 30-something and so set it to 20.
Brave 0.8.0 on Windows 10

**Comment by bbondy** [comment]
We currently limit between 3 and 20 intentionally because the tabs get too small.  We need some UI tweaks to support higher.

**Comment by plieblang** [comment]
"We currently limit between 3 and 20 intentionally"
I know, but 15 is a valid number but you can't type in 15, or any other double-digit number less than 20.  You can only set it to 10, 11, 12 etc. via the up/down mouse buttons.

**Comment by bbondy** [comment]
gotcha

**Comment by erikvold** [comment]
Mind if I try to tackle this one?

**Comment by bbondy** [comment]
that'd be great, thanks!

**Comment by erikvold** [comment]
hmm well I think I have a patch here, but I ran into issue #1098 and can't seem to try my change out atm..

**Comment by bbondy** [comment]
pls try again

**Comment by erikvold** [comment]
hmm my patch didn't work so well, I was delaying the event handler, but it appears that the `event.target` is a dead node after a 250ms delay, I'm guessing because the shadow dom is replacing the node when there is a new value, after pressing the `5` in `15` for example.

**Comment by erikvold** [comment]
an easy idea was to use `min="1"` but that doesn't appear to work well either because the prefence change happens immediately, and the UI starts appearing glitchy.

**Comment by erikvold** [comment]
I guess I could go back to delaying the event handler, but remove the use of the `event.target` and store the `min`, `max`, `value`, `type` values of the node that we need.  Any better ideas @bbondy ?

**Comment by bbondy** [comment]
I'd probably stick with allowing 1 as the min input.  I haven't tried but maybe the 1-tab temporary display isn't so bad. If it is you could try setting state but delaying the live update to minimize it.

**Comment by erikvold** [comment]
> "If it is you could try setting state but delaying the live update to minimize it."

@bbondy I think it is pretty bad, since typing `1` then `5` would make everything below the location bar shift down (to show tab groups) then back up (to hide them).  How would you suggest going about delaying the live update?   Testing this works correctly seems a bit tough too.. since we are adding exceptions to live updates where we want to delay and will then want to test that the delay behaves correctly.

I think delaying the events from emitting makes more sense to me fwiw, it should be easier to test that an event for `1` does not emit when `1` is typed then a quick `5` typed, and that a `15` is emitted after the `5` is typed for example :)

**Comment by bbondy** [comment]
I'd try wrapping this in a function `aboutActions.changeSetting(key, value)` and then debouncing it.  See other uses of debounce `git grep debounce`.  Possibly selectively debouncing.
