### ISSUE TITLE
Extension request: Ledger Manager

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#10771]
I can't add a new request for extensions on projects.

I want the Brave Browser to have [a Ledger Manager extension](
https://chrome.google.com/webstore/detail/ledger-manager/beimhnaefocolcplfimocfiaiefpkgbf) and [a Ledger Wallet Ethereum extension](https://chrome.google.com/webstore/detail/ledger-wallet-ethereum/hmlhkialjkaldndjnlcdfdphcgeadkkm).

It's sad that I have had to resort to using Mozilla for using Medium and Wordpress, and now I need to use Chrome to use these extensions.

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄

**Comment by bsclifton** [comment]
Regarding this specific functionality, we've also done some great prototyping and investigation work into adding a built in ETH wallet. @tomlowenthal will be looking more into that (I'm not sure if there's a project tracking that work in brave-core yet?)

**Comment by tomlowenthal** [comment]
There's a placeholder issue for now: https://github.com/brave/brave-browser/issues/248 .
There's also a general label for this broader bucket of work: https://github.com/brave/brave-browser/labels/feature%2Fcryptocurrency .

But we have a bunch of research and specification to do before we get underway building this feature for the new Brave. Currently, we're planning to get started on the implementation work after we release Brave 1.0. Of course, schedules can always change as other needs and priorities arise, and everything always takes longer than anticipated.
