### ISSUE TITLE
Unable to login to GMX mail

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10786]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Several reports on community regarding login issues on gmx.net

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.18.23

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/gmx-net-you-cant-open-emails/6689/3

**Comment by itsBehindYou** [comment]
I don't think it's so much an issue with logging in to GMX mail (or mail.com, they use the same platform) - it's an issue that people were having with being unable to open the individual mails from the main screen once you're logged in, unless you allow 3rd party cookies. I can't speak for everyone but for me at least, this issue has now gone away in recent versions of Brave; I can now make full use of GMX mail with 3rd party cookies blocked.
