### ISSUE TITLE
Browser URL bar color with SSL connection always grey, should be green

### ISSUE THREAD

**Issue by pongraczi** [brave/browser-laptop#10792]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
It is a design question: the URL should be green if a trusted SSL certificate is used and grey, if not, for example self-signed cert.
Also, a better help with details could help users to learn SSL basics: difference between trusted SSL, self-signed SSL, expired SSL, etc.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linuxmint 17 64bit

- Brave Version (revision SHA):
Brave | 0.18.23
rev | 36ae2ec

- Steps to reproduce:
Visit a trusted SSL site, like github.
    
- Actual result:
Everything grey.

- Expected result:
Should be colorful :) Green if everything seems ok. On right click, brief description and option to learn more.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Fresh installation.

- Screenshot if needed:
![kijeloles_579](https://user-images.githubusercontent.com/5891983/30050957-8b69abb4-9220-11e7-842e-1004199c2640.png)

**Comment by srirambv** [comment]
Same as https://github.com/brave/browser-laptop/issues/8064 ?

**Comment by pongraczi** [comment]
@srirambv Thank you, seems exactly, yes. I close this issue, as it is a duplicated one.
