### ISSUE TITLE
Netflix tiles not working when users click on "Back to Browse" while watching media

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10797]
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

When you're watching a show/movie, hitting the "Back to Browse" button and then selecting another show/movie doesn't work. You'll have to refresh the entire page to select something else. I checked under the latest Chrome/Firefox and it worked as expected. So it's definitely something with Brave since we've updated Widevine via #10449.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

macOS 10.12.6 x64 - Reproduced (@LaurenWags also reproduced the issue)
Win 10 x64 - Reproduced

**- Brave Version (revision SHA):**

```
Brave: 0.18.26 
rev: 67f256891907248a20563451d8ed455493bc4cc2 
Muon: 4.3.15 
libchromiumcontent: 60.0.3112.101
```

**- Steps to reproduce:**

1. Login into Netflix
2. Once logged in, play anything
3. Once the media starts playing, hit the "Back to Browse" button
4. Try playing another show/media via clicking on the tiles

**- Actual result:**

Clicking on the tiles has no effect and users won't be able to play another show/movie. User will need to refresh the page before they can select something else.

**- Expected result:**

Users should be able to click the "Back to Browse" button and select other media without any issues.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

Widevine doesn't currently work, #10449 fixes the issue. From what I remember, using "Back to Browse" worked before.

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

![netflixissue](https://user-images.githubusercontent.com/2602313/30072930-f058f926-9239-11e7-9168-d9292ac313ee.gif)

**- Any related issues:**

Netflix Streaming Error #10449

**Comment by darkdh** [comment]
This might not related to #10449 and we can't even verify previous build which can't get widevine running. I would prefer set this issue as a separate webcompat issue

cc @bsclifton

**Comment by kjozwiak** [comment]
> This might not related to #10449 and we can't even verify previous build which can't get widevine running.

I think you're probably right. Even though you can't play any media in the current `0.18.23` build, you can still reproduce this issue where the tiles stop working once you head back to the "Browse" page view via the "Back to Browse" button.

STR under `0.18.23`:

* login into netflix
* play any media (you'll get an error message which is expected)
* select "Back to Browse" and try clicking on tiles (nothing works)
* refresh the page and the tiles will start working again

So it seems like the issue is also present in `0.18.23`.

**Comment by kjozwiak** [comment]
Moved this into the [0.20.x (Developer Channel)](https://github.com/brave/browser-laptop/milestone/76) milestone as it's not a new regression and present under `0.18.23`. We haven't received any complaints of users running into this either. However, we should definitely fix this to make the Netflix experience a lot smoother.

**Comment by luixxiul** [comment]
I remember I perhaps experienced the same issue on chrome as well.

**Comment by kjozwiak** [comment]
I rechecked this on `0.22.669` on both macOS `10.13.3` & `Win 10 x64` and it works as expected. I played through a bunch of media and had no issues going back to the home page and playing other media. Tried it multiple times and everything worked as expected.
