### ISSUE TITLE
Select text and middle click does not work as expected in linux

### ISSUE THREAD

**Issue by pongraczi** [brave/browser-laptop#10791]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Under linux it is a common thing, when I select a text anywhere on the desktop (console, browser, text editor, whatever) and I middle click somewhere else, the previously selected text will be inserted into the clicking point. Easy, clean, fast way.
With brave it is not working: cannot exchange selections between linux and brave, even inside brave it does not work. It will insert text from the system clipboard or from its own clipboard (no idea yet, I had no patience to test this).

- Platform (Win7, 8, 10? macOS? Linux distro?):
LinuxMint 17 64 bit, Mate desktop

- Brave Version (revision SHA):
Brave Brave 0.18.23 rev 36ae2ec

- Steps to reproduce:
    1. Select text with mouse inside a terminal or 3rd party application (4ex: keepassx)
    2. Move the mouse cursor into the brave: login credentials or github opened issue text editor area, click on the middle button.
    3. Result: get whatever was in the clipboard, but not the selected text.
    Alternative test:
    1. Open a new issue under brave on the github.
    2. Select text from the text area.
    3. Click on the middle click inside the text editor area.
    4. Result: get whatever was in the clipboard, but not the selected text.
    
- Actual result:
   Get whatever was in the clipboard, but not the selected text.

- Expected result:
   Same behaviour as in normal is linux: the selected text must be entered, not the clipboard.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
  It is independent of profiles, it is working like this right after installing brave.

- Is this an issue in the currently released version?
  No idea, I just started using the version I wrote above.

- Can this issue be consistently reproduced?
   Sure, I did not find any workaround. Using Ctrl+C or right click and Copy is not an option, but very frustrating, breaks the fastest select-insert method and lead to a lot of mistakes -> frustration -> wasting time -> annoying and blood pressure increasing.

PS: Anyway, I really like brave, even with this issue.

**Comment by pongraczi** [comment]
More info: something not ok. After a Brave crash, it seems it sometimes working as expected, sometimes not. I did not find any special case, why it happens.
Computer uptime does matter?
Confusing.
Anyway, I use Linuxmint Mate 18.2 since yesterday.

**Comment by pongraczi** [comment]
It still exists. Ctrl+C, Ctrl-V or middle click, or right click on selected text and Copy -> messing up. not random, but annoying and cannot trust, that will happen what I wanted.  
Even from other applications: text editor, keepassx, whatever.  

[![Video about the middle click issue](https://img.youtube.com/vi/G3i_SsXbcEY/0.jpg)](https://youtu.be/G3i_SsXbcEY)

**Comment by pongraczi** [comment]
Select text with mouse inside the browser, and middle click somewhere else (text editor for example) still sucks with this issue. It pastes from the normal clipboard.

 
Brave: 0.19.23 
rev: 7941690ada962e67f7881c442ca4fec533a9f699 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by muxspace** [comment]
I get this as well. Basically middle click is same as Ctrl-V and pastes from the clipboard via Ctrl-C. The text selection buffer is ignored, so now I have to Ctrl-C everything instead of just highlighting the text. Not mission critical though mildly annoying.

My info:
```
$ apt-cache policy brave
brave:
  Installed: 0.18.36-1
  Candidate: 0.18.36-1
  Version table:
 *** 0.18.36-1 500
        500 https://s3-us-west-2.amazonaws.com/brave-apt xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by pongraczi** [comment]
I still have this issue 
 
Brave: 0.19.50 
rev: 5e2c26a14881662b553e0239103ea674fda8ac6a 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by pongraczi** [comment]
In 0.19.61 it is still exists. Even, I experienced this issue right after starting brave. It is really annoying and break existing workflows and reflexes, producing a log of problems.

 
Brave: 0.19.61 
rev: c8e042cd4bd700e277b35d8b584e622ed89dcb51 
Muon: 4.5.6 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by hugobuddel** [comment]
Not being able to paste with the middle mouse button is indeed rather annoying. I thought it worked fine for a while, but it doesn't work in 0.19.95.

Or well, it doesn't *always* work. That "0.19.95" was copied from about:brave by selecting it and pasted with the middle mouse. So some things *can* be copied through selection, and some things *can't* or can, but only *sometimes*.

There are two clipboards:

- the 'CtrlC clipboard', normally used through Ctrl-C and Ctrl-V
- the 'X clipboard', normally used through selection and middle mouse

There seem to be (at least) three cases:

- Text on about:brave: Can be copied through selection with mouse to the X-clipboard, can be pasted with middle click.
- Text on other pages: Usually cannot be copied through selection, but might change the X-clipboard anyway. For example, if I currently select normal website text in brave, it will always put 'libchromiumcontent' in the X-clipboard (a string that might have been there before). Sometimes it works though.
- Editable text, such as the url field: this will sometimes work, sometimes won't. In this particular Brave window I can (usually) copy the URL by tripple-clicking, but in another window it will (usually) put 'libchromiumcontent' in the X-clipboard.

It is super confusing.

**Comment by hugobuddel** [comment]
Ok, it seems that the text that will be copied when you select something, is the oldest selected text on any tab. So:

- Open a normal text editor, write some text
- Open Brave with two tabs with different pages
- Select something in tab 1 (called TextA), paste with middle click in text editor (TextA appears)
- Select some text in text editor (TextB), paste again with middle-mouse (TextB appears)
- Select something in tab 2 (TextC) (while ensuring that the selection in tab 1 is not undone), paste in text editor (TextA appears!!!)

So ensure that you always unselect text after pasting it elsewhere.

Or something like that, not entirely sure what is happening.

**Comment by pongraczi** [comment]
Still exists. Using brave without this feature is not very productive. 
It is hard to believe, almost nobody use this feature and this bug is not as annoying as it really is.
 
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by hugobuddel** [comment]
What sort-of works is to always do this:

1. select some text (copying it)
2. click somewhere else on the page to clear the selection (copy buffer stays intact)
3. paste somewhere with middle mouse
4. click somewhere else again on the original page again

That way I can most of the time copy and paste successfully. It makes sure that no text is ever highlighted in any tab. Sometimes it suffices to do either 2 or 4, not sure when, so I do both.

Still very frustrating, because it doesn't always work and you might forget and have some text highlighted somewhere on some tab.

**Comment by pongraczi** [comment]
Still exists.

 
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-26-generic 
OS Architecture: x64

**Comment by pongraczi** [comment]
Still exists.

Brave: 0.20.46 
V8: 6.4.388.41 
rev: 5eb035c2d68225994a572a1d62861cf961355ab2 
Muon: 4.8.2 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
