### ISSUE TITLE
improving about:history access (especially under Windows)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10807]
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

We should look into ways of improving access to `about:history` for users on Windows. Currently, these are the only ways of accessing `about:history` which isn't really intuitive for the average user:

* Pressing "ALT" and access History in the file menu
* typing in `about:history` under the URL bar
* Going into the Settings -> General and disable "Hide the menu bar by default"

Under macOS/Linux, the File Menu is usually visible the entire time so it's a lot easier to figure out where about:history can be access from.

I personally think we should add access to about:history in the following locations:

* adding History under the Brave menu
* adding History access under about:preferences#security (currently you can only clear)

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

Windows 10 x64 - Reproduced
macOS 10.12.6 x64 - Reproduced
Ubuntu 17.04 x64 - Reproduced

**- Brave Version (revision SHA):**

Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 

**- Steps to reproduce:**

N/A
    
**- Actual result:**

 `about:history` is currently hard to access on Windows.

**- Expected result:**

 `about:history` should be a lot easier to access on Windows

**- Is this an issue in the currently released version?**

Yes

**Comment by eljuno** [comment]
Related to #6934?

**Comment by kjozwiak** [comment]
Yup, thanks @eljuno! I added the above feedback into #6934 and will close this off.
