### ISSUE TITLE
the app icon is not displayed on Linux

### ISSUE THREAD

**Issue by hferreiro** [brave/browser-laptop#10803]
#10801 fixes this.

**Comment by luixxiul** [comment]
@hferreiro would you mind specifying the test plan?

1.
2.
3. 
...

**Comment by hferreiro** [comment]
@luixxiul it is difficult to test because the icon was showing when installed system-wide. This bug was only present when running from a local build. In any case:

1. Run Brave
2. Check that the Brave icon is shown when using Alt+Tab to change windows

**Comment by luixxiul** [comment]
I confirmed it worked on Debian. Let's open another issue if we find an issue with other distros.
