### ISSUE TITLE
Some Images on a Page Won't Load

### ISSUE THREAD

**Issue by CAPerkins22** [brave/browser-laptop#1080]
I've encountered this on websites belonging to SBNation.com. Some images on the pages will load, while others remain blank.

Here are two examples:
1. http://www.sbnation.com/nhl/2016/3/14/11223836/daryl-katz-son-oilers-draft-childhood-photos
2. http://www.sbnation.com/nhl/2016/3/10/11195050/nhl-winter-classic-outdoor-games-venues

**Comment by luixxiul** [comment]
> Refused to load the script 'https://optimize-stats.voxmedia.com/loader.min.js?key=98f696dfb03d127e' because it violates the following Content Security Policy directive: "script-src 'none'".

ref: #584

**Comment by luixxiul** [comment]
The pictures are displayed. It seems that the issue has been fixed by their side.
