### ISSUE TITLE
backup ECC key seed instead of priv key passphrase

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#10802]
brought up by @evq during security confab today. when we switch from BTC to BAT wallets, it seems more efficient/secure to present the ECC seed for the wallet keypair to the user for backup instead of presenting a passphrase which is used to encrypt the private key.

cc @mrose17

**Comment by diracdeltas** [comment]
close this once bat wallet is integrated in browser-laptop

**Comment by NejcZdovc** [comment]
bat was merged so closing this one

**Comment by luixxiul** [comment]
no-qa-needed?
