### ISSUE TITLE
Brave UA whitelist only applies to top level page loads

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10800]
## Test plan

https://github.com/brave/browser-laptop/pull/10904#issue-256869633

----

**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

Brave's UA whitelist only applies to top level page loads and not sub resources. I believe it's this line in the code:

https://github.com/brave/browser-laptop/blob/master/js/data/siteHacks.js#L46

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

macOS 10.12.16 x64 - Reproduced
Win 10 x64 - Reproduced

**- Brave Version (revision SHA):**

Brave: 0.18.26 
rev: 67f256891907248a20563451d8ed455493bc4cc2 
Muon: 4.3.15 
libchromiumcontent: 60.0.3112.101 

**- Steps to reproduce:**

1. load adobe.com within Brave
2. open the developer tools via "option + command + I"
3. select the "Network" tab and reload adobe.com via "command + r"
4. select on the first resource and you'll notice the correct `Brave Chrome/60.0.3112.101` UA
5. select another resource that's underneath the first one and is from `Host:www.adobe.com`

You'll notice that the incorrect UA is being used.
    
**- Actual result:**

Only the first resource (top level) is correctly using the UA.

**- Expected result:**

The correct UA should be applied to every resource that's from the whitelist domain.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

#10614 was supposed to fix this issue, however it only partially fixed the problem.

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

Correct Example:

<img width="1447" alt="good" src="https://user-images.githubusercontent.com/2602313/30080404-7f3eaf20-9251-11e7-8aeb-1ec80de3f3a5.png">

Incorrect Example:

<img width="1445" alt="bad" src="https://user-images.githubusercontent.com/2602313/30080424-926a398e-9251-11e7-846f-de7c8876e44c.png">

**- Any related issues:**

#10614

**Comment by LaurenWags** [comment]
Verified on MacOS:
<img width="871" alt="screen shot 2017-12-20 at 2 49 40 pm" src="https://user-images.githubusercontent.com/28145373/34225634-1acd8e70-e595-11e7-8071-cb94e37c8203.png">
