### ISSUE TITLE
Switch order should be same on the bravery shield panel and the preference page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10813]
**Describe the issue you encountered:** Switch order should be same on the bravery shield panel and the preference page.

On the compact panel:

![clipboard01](https://user-images.githubusercontent.com/3362943/30097221-88572314-9317-11e7-8dbb-e9085ff3dcae.png)

On the preference page:

![clipboard01](https://user-images.githubusercontent.com/3362943/30097232-9779a5e2-9317-11e7-98e7-a3d0221aa757.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): 0.18.x

- Actual result: See above

- Expected result: Block Phishing / Malware option should be moved to the bottom, following the panel. 

  For reference this is the original panel switch alignment:

  ![clipboard01](https://user-images.githubusercontent.com/3362943/30097333-1d588156-9318-11e7-8d58-4175b11cf137.png)

- Any related issues:

----

on the master branch the fingerprinting protection option has been moved to a pulldown option.

**Comment by srirambv** [comment]
Updated screenshot for reference
`about:preferences#shields`
![image](https://user-images.githubusercontent.com/17010094/34215303-d4fd2f9c-e59c-11e7-8989-c6d7b3d69ca3.png)
Compact shields panel
![image](https://user-images.githubusercontent.com/17010094/34215330-e52579a6-e59c-11e7-888e-7a07e7694fd7.png)
