### ISSUE TITLE
Verified publisher icon not shown on manual upgrade 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10814]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Verified publisher icon not shown on manual upgrade 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 

- Brave Version (revision SHA):

Brave | 0.18.27
-- | --
rev | eba55a1
Muon | 4.3.16

- Steps to reproduce:
    1. Install 0.18.23 build, do not enable payments
    2. Manually upgrade to 0.18.27 by running the setup 
    3. Once updated to 0.18.27, enable payments and visit any verified publisher link (eg: brianbondy.com)
    4. Wait for the entry to be added in the ledger table, no verified publisher icon is shown in URL or in ledger table
     5. Quit and restart browser, no change
     6. Disable/enable payments, no change
     7. Delete all ledger*.json files from brave profile and relaunch browser and visit the same sites, verified publisher icon is shown
    
- Actual result:
Verified publisher icon not shown on manual upgrade 

- Expected result:
Should show the verified publisher icon irrespective of when payment is enabled and how the browser update is done 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, 
Updated manually from 0.17.13 to 0.18.14, no verified publisher icon shown
Auto updated from 0.18.14 to 0.18.23, still no verified publisher icon shown

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @mrose17 @NejcZdovc @cezaraugusto

**Comment by luixxiul** [comment]
@srirambv does this issue still exist?

**Comment by zentagonist** [comment]
May be resolved by refactor #11037 . QA to recheck after

**Comment by srirambv** [comment]
Yes this is still an issue on the latest build.

**Comment by NejcZdovc** [comment]
verified publisher icon is delayed, so it's ok if only appears after 10 sec

**Comment by NejcZdovc** [comment]
closing for now as it works
