### ISSUE TITLE
Brave fails to launch properly in the latest dev release

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10812]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
I started Brave after the latest dev channel update, but it did not launch properly. The Brave app was active, but there was no window, and the menu only had the Brave > Quit item. I tested several versions of Brave and found that the problem happens in 0.18.27 and 0.19.5 but not 0.18.26.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x.

- Brave Version (revision SHA):
0.18.27 and 0.19.5

- Steps to reproduce:
    1. Make sure you have a clean profile.
    2. Start Brave.
    3. Quit Brave.
    4. Start Brave again.
    
- Actual result:
Brave does not launch properly.

- Expected result:
Brave should launch properly.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
None.

- Any related issues:
None.

**Comment by srirambv** [comment]
Specific to mac. Works on Windows upgrade to 0.18.27.

**Comment by NejcZdovc** [comment]
@Liunkae there was a problem with one package, so @bsclifton is creating a new build for macOS

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/1493f22a928d154e2e342d2cf0e08881c72e6157; build in progress 😄
