### ISSUE TITLE
Security webdriver tests failing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10825]
**Describe the issue you encountered:**

```
  13) noscript can allow scripts when the url host is an ipv6 address:
     Promise was rejected with the following reason: timeout
  Error
```

@diracdeltas can you please check if this is a problem in the test or we regressed

**Comment by NejcZdovc** [comment]
please check this one as well

```
 16) navigationBar tests navigation tabnapping updates the location in the navbar when changed by the opener:
     Promise was rejected with the following reason: timeout
  Error
```

**Comment by diracdeltas** [comment]
the noscript ipv6 is an actual regression, appears to be caused by the switch to muon.url.parse. i think https://github.com/brave/muon/pull/300 will fix it
