### ISSUE TITLE
Active tab flicker on hover

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10838]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Active tab flicker on hover

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.18.29
-- | --
rev | 85f059d
Muon | 4.3.16

- Steps to reproduce:
    1. Hover over background tab see the hover effect
    2. Hover over active tab, see the hover effect
    3.
    
- Actual result:
See screenshot link 

- Expected result:
Should not flicker

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
http://bigredbell.com/tab.mp4
- Any related issues:
https://community.brave.com/t/active-tab-flicker-on-hover/7242
cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
yes it annoys me a lot. 

I'll put in 0.20.x as it shares the same fix as other tab issues and should be fixed by the same PR. Thanks.
