### ISSUE TITLE
Address bar mouse selection not working properly

### ISSUE THREAD

**Issue by stephenkru** [brave/browser-laptop#10840]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

When the address bar is highlighted either from manually highlighting the text, or from switching tabs and it auto highlights, you cannot click to modify any part of the text for a random period of time.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Brave | 0.18.30
-- | --
rev | 795cc10
Muon | 4.3.17
libchromiumcontent | 61.0.3163.71
V8 | 6.1.534.31
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes
![addressbar](https://user-images.githubusercontent.com/23619351/30162074-e4475f1e-9398-11e7-96b8-89a5c2d6149e.gif)

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Thanks for your report. The issue is tracked on https://github.com/brave/browser-laptop/issues/8472. Did you change the DPI setting, as mentioned on https://github.com/brave/browser-laptop/issues/8472#issuecomment-322885380 ?
