### ISSUE TITLE
Add a built in PDF reader

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1084]

**Comment by tylerl0706** [comment]
Thoughts on using: 

https://github.com/mozilla/pdf.js/

for this task?

**Comment by weems** [comment]
I'm a big fan of pdf.js. Would like to learn about steps to implement in Brave.

**Comment by tylerl0706** [comment]
I'm running a hack night in Orlando for BeBraveDay. I thought this might be and interesting one to look into.

**Comment by bbondy** [comment]
I think electron supports PDFium, would be the easiest to support that probably.
