### ISSUE TITLE
Spell Check fails on Windows 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10849]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Spell Check fails on Windows 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.31
--|--
rev | a5a7280
Muon | 4.3.17

- Steps to reproduce:
    1. Update to 0.18.31
    2. Open about:styles and type a wrong word in text field
    3. Spell check doesn't indicate wrong spelling
    
- Actual result:
Spell Check fails on Windows 

- Expected result:
Spell check should work 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Not an issue on mac confirmed by @LaurenWags 
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by kjozwiak** [comment]
Also reproduced on the following Win platforms:

* Win 7 Pro x86 using `0.18.29` - Couldn't Reproduce
* Win 7 Pro x86 using `0.18.31` - Reproduced
* Win 10 x64 using `0.18.29` - Couldn't Reproduced
* Win 10 x64 using `0.18.31` - Reproduced

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/spell-check-not-working/7407?u=eljuno
Windows 8.1

Brave	0.18.30
rev	795cc10
Muon	4.3.17
libchromiumcontent	61.0.3163.71
V8	6.1.534.31
Node.js	7.9.0
Update Channel	dev
OS Platform	Microsoft Windows
OS Release	6.3.9600
OS Architecture	x64
