### ISSUE TITLE
Add yellCast as a Search Provider

### ISSUE THREAD

**Issue by agbodike** [brave/browser-laptop#10853]
Test plan

Make sure yellCast can be found on the preferences page and :yc works

Requires modification to browser-laptop/js/data/searchProviders.js

**Comment by luixxiul** [comment]
For me https://yellcast.com/ is not displayed; it prompts just a white page.

**Comment by luixxiul** [comment]
@agbodike does the site work for you?

**Comment by agbodike** [comment]
@luixxiul  In what sense, just clicking on the link and viewing in any browser? That certainly works for me:

![screenshot-yellcast com-2017-09-08-11-45-17](https://user-images.githubusercontent.com/6569567/30226561-4928bf3e-948b-11e7-9e43-b3a573ee37ca.png)

**Comment by luixxiul** [comment]
With VPN the page is displayed. I suspect it blocks foreign IPs.

**Comment by bsclifton** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/10868
