### ISSUE TITLE
"Clone Tab" opens a new tab but never loads the targeted website

### ISSUE THREAD

**Issue by ricardosaracino** [brave/browser-laptop#10850]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
clone tab doesnt open

- Platform (Win7, 8, 10? macOS? Linux distro?):
win 10

- Brave Version (revision SHA):
a5a7280

- Steps to reproduce:
    1. right click tab and hit clone 
    2. 
    3.
    
- Actual result:
opens about:blank and spins

- Expected result:
tab should be cloned

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/759253/30187605-56af1b1e-93f8-11e7-8864-05d397411df4.png)

- Any related issues:

**Comment by kjozwiak** [comment]
Thanks for the report @ricardosaracino! I reproduced the issue under both macOS 10.12.6 x64 and Ubuntu 17.04 x64 using the following build:

> Brave: 0.18.32 rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 
> Muon: 4.3.18 
> libchromiumcontent: 61.0.3163.71

I couldn't reproduce the issue with the latest release version of Brave:

> Brave: 0.18.29 rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 
> Muon: 4.3.16 
> libchromiumcontent: 60.0.3112.113

I'm going to move this into the latest 0.18.x Hotfix 2 milestone as it's working under `0.18.29` but has regressed in the current preview releases. Users shouldn't be losing functionality that's currently working in the latest release. @bbondy @bsclifton, please let me know if you feel differently.

**Comment by bbondy** [comment]
Cherry-picked to 4.3.x+61.0.3163.71 here:
https://github.com/brave/muon/commit/856d3bca81c8fb9847c21356bd7cc5ecb013b7d0

It'll be in 4.3.20

**Comment by ricardosaracino** [comment]
still having this issue 
win 10 
e94738d

![image](https://user-images.githubusercontent.com/759253/30354212-3059b258-97f9-11e7-9a06-e4f18308a20f.png)

**Comment by luixxiul** [comment]
@ricardosaracino please wait for the next build to see the fix is available :-) thanks!
