### ISSUE TITLE
Brave should allow search engines to be added via OpenSearch

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10868]
### Did you search for similar issues before submitting this one?
Yes

### Describe the issue you encountered:
Per https://github.com/brave/browser-laptop/issues/3053#issuecomment-244539801 by @da2x:
> All search engines, and then I mean every single one of them, have OpenSearch auto-discovery on their home pages and search result pages. Safari and Edge automatically detects OpenSearch-enabled search engines and lists them as suggested search engines in their Preference panes.
> 
> This means that every user will find their favorite search engine in the list of possible search engines without having to configure it; they just need to perform one search with their favorite engine and it will then become available. I [wrote about this on my blog](https://www.slightfuture.com/blog/safari-decentralizes-search) for anyone interested in the specifics.
>
> I think this is an elegant solution that empowers even inexperienced users to change their search engine to whichever they prefer without technical knowledge. It also exposes many more possible search engines than a browser could reasonably build-in by default. The approach sounds like a good fit for Brave.

Example steps outlined (showing what to look for):
- https://ctrl.blog/entry/safari-quick-website-search
- https://davidwalsh.name/open-search

### Platform (Win7, 8, 10? macOS? Linux distro?):
All

### Brave Version (revision SHA):
All

### Steps to reproduce:
    1. Visit https://translate.google.com
    2. Open Preferences > Search
    3. Notice that `translate.google.com` was not added automatically as a detected search engine
    
### Actual result:
Nothing happens

### Expected result:
`translate.google.com` should be added to an "Other search engines" list on the page. An example of what this looks like in Chrome:
![screen shot 2017-09-08 at 4 27 39 pm](https://user-images.githubusercontent.com/4733304/30234553-0a0be8ee-94b3-11e7-888b-29fdfb8a8eef.png)

### Is this an issue in the currently released version?
Yes

### Can this issue be consistently reproduced?
Yes

- Any related issues:
Allow user to add custom search engines #3053

**Comment by da2x** [comment]
OpenSearch is the right way to go here. Though please pay special notice to the drive-by search provider installation protection feature which work slightly differently in [Safari](https://ctrl.blog/entry/safari-quick-website-search) and [Edge](https://ctrl.blog/entry/edge-search-provider). Safari also has a fallback for websites that don’t have an OpenSearch Description file (described in the previous link) which can be a … good source for inspiration.

PS: Chrome’s UI is the worst out of the lot here. Look at Edge and Safari instead. Firefox is more discovererable than the rest, but requires a separate search field/icon.

**Comment by DeviatedMind** [comment]
If you guys can't give a simple important feature after so long, you shouldn't make a browser, make a brave extension.
An ad-blocker which can pay the parties.
Although I understand you are renovating browsers, yet there are many extensions I need:
Stylish, OpenSearch, Domain Blocker, Div Blocker, etc.

**Comment by bsclifton** [comment]
cc: @davidtemkin @zentagonist for prioritization

**Comment by eljuno** [comment]
Related to #10675?

**Comment by Lythimus** [comment]
Brave nearly meets my browser needs, but it's frustrating that I can see the search engine list with shortcuts, but can't add my own. I've used this feature in Opera for like 10 years, so I may have to switch back to it if I can't figure out how to add searches through config files or something.

**Comment by bsclifton** [comment]
Happy to report this is fixed with [brave-core](https://github.com/brave/brave-browser) 😄 
![screen shot 2018-08-24 at 10 56 29 pm](https://user-images.githubusercontent.com/4733304/44615535-08b77d80-a7f1-11e8-8df2-4ff2f77e744e.png)

**Comment by tomlowenthal** [comment]
But what if we added an "off" switch? brave/brave-browser#867
