### ISSUE TITLE
Unable to open some PDFs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#10867]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When navigated to http://www.mckinsey.com/business-functions/mckinsey-analytics/our-insights/how-artificial-intelligence-can-deliver-real-value-to-companies?utm_content=buffer64f12&utm_medium=social&utm_source=linkedin.com&utm_campaign=buffer if you click on the 'Full Report (PDF ~3MB)' button, page opens up as a PDF but no PDF is displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave | 0.18.29
rev | 85f059d
Muon | 4.3.16

- Steps to reproduce:
    1. Navigate to http://www.mckinsey.com/business-functions/mckinsey-analytics/our-insights/how-artificial-intelligence-can-deliver-real-value-to-companies?utm_content=buffer64f12&utm_medium=social&utm_source=linkedin.com&utm_campaign=buffer
    2. Locate the 'Full Report (PDF ~3MB)' button (near the top)
    3. Click on the button.
    
- Actual result:
Page displays PDF viewer but no PDF is displayed.

- Expected result:
PDF should be displayed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. When you do this on Chrome, the PDF is downloaded and then you can open in Chrome or other source.
    2.
    3.

- Screenshot if needed:
![screen shot 2017-09-08 at 3 06 27 pm](https://user-images.githubusercontent.com/28145373/30227340-50f4b616-94a7-11e7-8ed7-8b79e2af1d85.png)

- Any related issues:

**Comment by LaurenWags** [comment]
Other PDFs (http://www.orimi.com/pdf-test.pdf or navigate to https://basicattentiontoken.org/faq/#meaning and click Download the Whitepaper) display without issue.

**Comment by luixxiul** [comment]
Reproduced:

````
pdf.worker.js:342 Uncaught (in promise) Error: Bad end offset: 5510192
    at error (pdf.worker.js:342)
    at assert (pdf.worker.js:353)
    at ChunkedStream_onReceiveData [as onReceiveData] (pdf.worker.js:15019)
    at ChunkedStreamManager_onReceiveData [as onReceiveData] (pdf.worker.js:15361)
    at ChunkedStreamManager.<anonymous> (pdf.worker.js:15240)
    at <anonymous>
````

**Comment by diracdeltas** [comment]
I believe this is an issue in mozilla/pdf.js because the problem also occurs in Chrome with the pdf.js extension (version  1.8.557)

**Comment by diracdeltas** [comment]
found a way to fix it in https://github.com/brave/pdf.js/pull/3
