### ISSUE TITLE
Brave not asking for permissions when loading geolocations

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10864]
## Test plan

load https://browserleaks.com/geo within Brave

----

**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

Geolocation data is being loaded without prompting the user for permission.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

Win 7 x86 - Reproduced
Win 10 x64 - Reproduced
macOS 10.12.6 - Reproduced

**- Brave Version (revision SHA):**

Brave: 0.18.31 
rev: a5a7280219b930bc3f3ce1b83a29afedc71bbd79 
Muon: 4.3.17 
libchromiumcontent: 61.0.3163.71 

**- Steps to reproduce:**

1. load https://browserleaks.com/geo within Brave

You'll notice that the geolocation data will load without asking for the required permissions.
    
**- Actual result:**

Users geolocation data loads without asking the user for the required permissions.

**- Expected result:**

Brave should be prompting the user for permission before loading geolocation data.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

No. Looks like it's a new regression in `0.18.31`

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

![permissionissue](https://user-images.githubusercontent.com/2602313/30216809-2ff4bb84-9482-11e7-94b4-1709dfd1bb7b.gif)

**Comment by kjozwiak** [comment]
Still an issue with the following build:

> Brave: 0.18.32 
> rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 
> Muon: 4.3.18 
> libchromiumcontent: 61.0.3163.71

Platforms checked:

* Win 7 Pro x86 - Reproduced
* Win 10 Pro x64 - Reproduced
* macOS 10.12.6 x64 - Reproduced
* Ubuntu 17.04 x64 - Reproduced

**Comment by bbondy** [comment]
This is all merged above for 4.3.21 and 0.18.x so marking this as complete.

**Comment by luixxiul** [comment]
Was the fix merged to 0.19?

For me the geolocation issue on https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation is reproduced on:

Brave: 0.19.7 
rev: c8481a9ecae07ddf816aea0c8d7a38b744c2b42d 
Muon: 4.4.16 
libchromiumcontent: 61.0.3163.71 
V8: 6.1.534.31 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Comment by NejcZdovc** [comment]
This was not merged into 0.19.x yet, see #10896

**Comment by bbondy** [comment]
0.19.x: 16a6c86fe4a6c5383d6cbb183efb4a6ccde4f163
0.20.x: 423706ebcb9811efb5d4ee5ec234ae426da21e0d
master: 5e5f089566770905bb13df86994b56591923c1cb
