### ISSUE TITLE
Every time I try to update Brave, it never updates.

### ISSUE THREAD

**Issue by Coaggly** [brave/browser-laptop#10874]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When I use "check for updates" in Brave, it says it's downloading the update. But when Brave restarts and I check, it hasn't updated yet. As in, when I click "check for updates" after it restarts, Brave still says it "found an update" and says it's downloading the update. It's stuck in a loop of never properly installing the update.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS Sierra

- Brave Version (revision SHA):
Brave version 0.18.23

- Can this issue be consistently reproduced?
Yes

**Comment by eljuno** [comment]
Duplicate of #2184?
