### ISSUE TITLE
Error related with webFrame

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10872]
**Describe the issue you encountered:** On http://www.athome.co.jp/chintai/tokyo/rosen_map/ the railmap is not displayed due to an error.

Disabling the shield does not work.

````
VM4139 extensions::webFrame:10 Uncaught TypeError: Cannot set property 'get' of undefined
CService.js:49 Uncaught ReferenceError: _jp_co_val_baseURL is not defined
    at CService.js:49
(anonymous) @ CService.js:49
VM4363 extensions::webFrame:10 Uncaught TypeError: Cannot set property 'get' of undefined
````

![clipboard01](https://user-images.githubusercontent.com/3362943/30241146-8d323d4e-95b8-11e7-8a4b-defee4c7323f.png)

On `extensions::webFrame:10`

````
  apiFunctions.setHandleRequest('setGlobal', function(path, value) {
    return webFrameNatives.setGlobal(path.split('.'), value)
  })
````

![clipboard02](https://user-images.githubusercontent.com/3362943/30241147-8d335008-95b8-11e7-93a5-21a6eec495ed.png)
 
Brave: 0.18.30 
rev: 795cc102729fc843ea82757c9e9508242fd5830e 
Muon: 4.3.17 
libchromiumcontent: 61.0.3163.71 
V8: 6.1.534.31 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

- Steps to reproduce:
    1. Open http://www.athome.co.jp/chintai/tokyo/rosen_map/
    
- Actual result: The railmap of Tokyo should be displayed

- Expected result: It is not

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
CC @jonathansampson @kevinlawler

**Comment by jonathansampson** [comment]
We don't appear to implement [`navigator.credentials`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/credentials).

**Comment by bridiver** [comment]
this actually happens on every page I navigated to. It appears that chromium must have removed navigator.credentials so our `get`/`set` overrides fail

**Comment by bsclifton** [comment]
Verified this works w/ brave-core
