### ISSUE TITLE
Report: Google Chat not working w/latest release

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#10875]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Received a report from a b2b partner that Gchat (likely hangouts text via gmail UI) on browser-laptop no longer works in the latest release. 

Note: contact mentioned the lack of Gchat functionality forced a switch from Brave to Chrome as their default browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
tbd: assume global. 

- Brave Version (revision SHA):
"Current version" as of 09.08.17 (waiting on actual vConfirmation.)

- Steps to reproduce:
    1. Open gmail 
    2. Open a Google chat dialogue via the hangouts module in the gmail web client.
    3. Attempt to chat. Reports are that it fails. 
    
- Actual result:
Gchat doesn't work.

- Expected result:
Gchat should work. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Should
- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
Tbd. Needs testing. 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Potentially related to: https://github.com/brave/browser-laptop/issues/2101

**Comment by lukemulks** [comment]
+1 from community.brave on macOS 
https://community.brave.com/t/latest-brave-update-gchat-blocked-by-3rd-party-cookie-control/7477

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/google-hangouts-bug-message-not-delivered/7464?u=eljuno

Brave: 0.18.30 on Windows
>And I noticed that I can no longer send messages over Gmail (Hangouts).

**Comment by darkdh** [comment]
this requires 3rd party cookies blocking disabled. We can use the sitehack solution just like we did on google drive

**Comment by bsclifton** [comment]
Another report of the same issue (when inside Google Hangouts): https://github.com/brave/browser-laptop/issues/10862

**Comment by bsclifton** [comment]
larger discussion here (maybe we need to revisit): https://github.com/brave/browser-laptop/issues/3715

**Comment by lindsm** [comment]
> this requires 3rd party cookies blocking disabled. We can use the sitehack solution just like we did on google drive

Is this something users can do, or are we talking behind the curtains things here.  I also have issues with Google Hangouts and Google Drive not working.  My solution is to just open those things in Chrome.  Would love to not have to do that.

**Comment by darkdh** [comment]
@lindsm you can turn the cookie control setting to
<img width="271" alt="screen shot 2017-10-06 at 12 30 20 pm" src="https://user-images.githubusercontent.com/11330831/31295124-2f369aac-aa92-11e7-837a-4cd9f14326f3.png">

**Comment by lindsm** [comment]
Perfect, thank you @darkdh.  In case anyone else stumbles upon this googling, the site cookie control is found in the "Open Brave Shields Panel" icon.

**Comment by Danl2620** [comment]
Is there any update on this?  Brave reverts the cookie setting to "Block 3rd Party" every time it updates or restarts...

**Comment by gbisaga** [comment]
Thank you @lindsm I was just about to ask. :-)

**Comment by srirambv** [comment]
+1 from @rjdp via #14117

**Comment by bsclifton** [comment]
Confirmed this is fixed and working great (thanks @NejcZdovc for confirming). Possibly fixed with https://github.com/brave/browser-laptop/pull/13820
![screen shot 2018-07-02 at 12 32 27 am](https://user-images.githubusercontent.com/4733304/42150736-85028f2e-7d8f-11e8-841e-f869eaf4bf8d.png)
