### ISSUE TITLE
loading a torrent link over HTTPS displays the unlock icon on URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10888]
**Describe the issue you encountered:** loading a torrent link over HTTPS displays the unlock icon on URL bar. It should display the lock icon if the resource is actually loaded over HTTPS in order to avoid misunderstanding.

![clipboard01](https://user-images.githubusercontent.com/3362943/30258890-14dcc1b6-96f8-11e7-8137-7677f0e425d4.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): 0.18.32 (it can be reproduced on the lower versions)

- Steps to reproduce:
    1. Open https://webtorrent.io/torrents/big-buck-bunny.torrent
    
- Actual result: on the URL bar the unlock icon is displayed

- Expected result: it should display the lock icon, as long as the resource is actually loaded on HTTPS.

- Any related issues:

**Comment by sergiorojasa** [comment]
I would like to work on this issue.

**Comment by bsclifton** [comment]
@sergiorojasa let's do it 😄 I self-assigned the issue, it's all yours!

**Comment by sergiorojasa** [comment]
@bsclifton I tried to fix the issue but I couldn't fix it.
