### ISSUE TITLE
Brave RPM repository access denied

### ISSUE THREAD

**Issue by git-ingham** [brave/browser-laptop#10894]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
zypper dup on OpenSUSE tumbleweed gives:
Permission to access 'https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media' denied.
Visiting https://s3-us-west-2.amazonaws.com/brave-rpm-release/ in a browser gives;
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F293577D864A2DAC</RequestId><HostId>nf6K365Yvl7upFFvtwQ8gZpS6CKmLND48OUcf6qqsyR3FTl4LFIyJJ6XA1GMHDGGh2wtSEFgNGM=</HostId></Error>

- Platform (Win7, 8, 10? macOS? Linux distro?):
OpenSUSE tumbleweed

- Brave Version (revision SHA): Irrelevant since I cannot get it.

- Steps to reproduce:
    1. Visit the brave RPM repository
    2. See error message.
    3.
    
- Actual result:
See above

- Expected result:
Getting the latest version of Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
They should work for anybody.

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
cc: @posix4e

**Comment by posix4e** [comment]
Can you tell me what commands you ran?

**Comment by git-ingham** [comment]
Go to this page:
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
Look under "OpenSUSE AMD64"
Look at the "sudo zypper addrepo" line
The URL listed gives a "Access Denied" XML reply.

So, what repository should I be using?

**Comment by tqdv** [comment]
@git-ingham Ok, so I managed to refresh the repository on openSUSE Leap 42.3.

What happened was that the repository type defaults to `rpm-md`, while brave's repo is `yast2`.
There doesn't seem to be a way to modify the repo type using `zypper modifyrepo` so edit the file directly.
(You can use `grep -l brave /etc/zypp/repos.d/*`to find it)

This should probably be added to the install instructions if it's correct.

**Comment by git-ingham** [comment]
That solves the repository problem.  However, I do get:
`Problem: nothing provides GConf2 needed by brave-0.20.30-1.x86_64`
I think that this is just a naming difference.  OpenSUSE Tumbleweed has this as:
gconf2-3.2.6-11.1.x86_64 (version installed on my system)
Brave 0.20.30 installs (and more importantly appears to run OK) if I tell it that breaking the dependency is OK.
