### ISSUE TITLE
About Brave doesn't show details on tab hover

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10890]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
About Brave doesn't show details on tab hover

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Open about:brave and a couple more tabs
    2. Set any other tab as active and close and relaunch browser
    3. Hover over about:brave, doesn't show details
    4. Click on about:brave tab, details show up
    
- Actual result:
See screenshot

- Expected result:
Should show details on hover

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![aboutbrave](https://user-images.githubusercontent.com/17010094/30265164-f62226ac-96f8-11e7-8cd0-37c09d0d1515.gif)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
@srirambv is this still an issue in 0.19.x?

**Comment by srirambv** [comment]
Yes it is
![1](https://user-images.githubusercontent.com/17010094/30848552-1c7021e0-a2bd-11e7-9602-372692a651c6.gif)
