### ISSUE TITLE
tab preview should be optional  and added to preferences

### ISSUE THREAD

**Issue by sinsunsan** [brave/browser-laptop#10891]
I am used to use google chrome. 
At first I was  exited by the tab preview feature of brave. 
But using brave  a bit more, I felt rapidly that it is too much visual noise, as often I preview by error. 

There is 2 problems : 

* unwanted preview that switch my display (a lot of cognitive load implied)
* people  that  do not know it is a preview and want to interact with the page...

So I think tab preview can be great  but should be an option that we can switch on / off in preferences. 

For the moment it is my n°1 problem switching entirely to brave.

**Comment by luixxiul** [comment]
Hi, you can disable the preview on the preference, about:preferences#tabs.

**Comment by sinsunsan** [comment]
Thanks!  I've just done it. May be it should be disabled by default, but probably more user feedbacks like mine should be necessary to decide that.
