### ISSUE TITLE
Brave loses track of 'last viewed tab' selects pinned tab instead

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#10903]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave loses track of the last viewed tab and jumps to a pinned tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.18.29

- Steps to reproduce:
    1. Add 3 pinned tabs
    2. Open several tabs randomly
    3. Open a few more windows with more tabs
    4. Select a middle tab
    5. Select the tab next to it
    6. Use the keyboard or mouse to close that selected tab
    7. Notice that the selected tab becomes the previous tab correctly
    8. Close current tab
    9. Notice a pinned tab has become selected

    
- Actual result:
A pinned tab is selected

- Expected result:
The last viewed tab should have been selected

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This is a nasty one- happens to me all the time
