### ISSUE TITLE
opening lots of tabs via "ctrl+t" and quickly closing them using "ctrl+w" created dead tabs

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10905]
## Test plan

https://github.com/brave/browser-laptop/pull/11311#issue-263338498

----

**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

When opening large quantities of tabs using "ctrl+t" and than quickly closing them using "ctrl+w", you'll sometimes get "dead" tabs that cannot be closed or used. If you manage to create a lot of these dead tabs, "ctrl+w" eventually stops working.

The UI is still responsive and the user can always restart so it's not as bad as #9083.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

macOS 10.12.16 x64 - Reproduced
Win 10 x64 - Reproduced

**- Brave Version (revision SHA):**

Brave 0.18.33

**- Steps to reproduce:**

1. Open Brave and start creating a lot of tabs via "ctrl+t"
2. Once you have a page or two worth of tabs, quickly switch over and start pressing "ctrl+w"

**- Actual result:**

Some of the tabs will become "dead" and cannot be closed or used. Going through the above STR, you'll sometimes manage to create ~10 dead tabs. When this happens, "ctrl+w" stops working.

**- Expected result:**

Tabs should be easily created and closed without creating dead tabs. When this happens, "ctrl+w" shouldn't break and should always work as expected.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

Yes

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

![deadtabs](https://user-images.githubusercontent.com/2602313/30303321-41b87a4e-9735-11e7-8412-4b132ca598a5.gif)

**Comment by bbondy** [comment]
0.19.x: 511bf20846d967d8cbfa57c5b681173ba5f5eeb3
0.20.x: 7bb52863e7412d225da791464849d2a35f101fd8
master: bf4726d9b7a780b133bb5144e08435ab798e0861

**Comment by srirambv** [comment]
Found one dead tab when opened a lot of tabs(5 tab pages) holding Ctrl+T and closing tabs(4 tab pages) by holding down Ctrl+W. 
![11322](https://user-images.githubusercontent.com/17010094/34213936-b02eee66-e598-11e7-9e1a-c65d5a6f042f.gif)
![11322-1](https://user-images.githubusercontent.com/17010094/34213996-f49d1690-e598-11e7-92fa-5b51d2814910.gif)

**Comment by srirambv** [comment]
Same single dead tab on 0.20.8 as well
