### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by cwmke** [brave/browser-laptop#1090]
An option for some sort of dark theme for the browser and a night mode for web browsing would be great down the road.

#271 

Edit: https://github.com/brave/browser-laptop/issues/1090#issuecomment-298203676
> For a global solution please check out this software: https://justgetflux.com/

**Comment by SJ-Diamond** [comment]
Very much agreeing with that. Dark theme... as it is hard for me to use browsers with a light UI. I am not the only one with that problem btw.

**Comment by bradleyrichter** [comment]
I definitely want it down the road. Thanks for the support!

**Comment by luixxiul** [comment]
Title changed. Let's continue the discussion about the dark UI at #271

**Comment by cwmke** [comment]
Aren't these two seperate issues though?  The mentioned discussion is talking about the UI, not actual webpages.

**Comment by luixxiul** [comment]
I thought that "night mode" was one which changes not only the UI color but also the background and font color for web browsing. Sorry if I'm wrong.

**Comment by cwmke** [comment]
That is indeed what I believe it meens but the other thread seems to be talking about only the shell.  For example, the tab bar, and navigation bar.  My appologies if I am mistaken.  :-)

**Comment by luixxiul** [comment]
Maybe the dark UI would be introduced one of the themes according to https://github.com/brave/browser-laptop/issues/271#issuecomment-174372741. Night mode as an extension, in my opinion.

**Comment by cwmke** [comment]
An extension wouldn't be a bad option, but I think this sort of thing often works better if built-in.  For example, Firefox Android has an automatic night mode when you enter reading mode which is wonderful at night.  In the end if the team decides to let extension developers create this, I'll still be happy with that solution.  Thanks for your thoughts.

**Comment by wastedsunsets** [comment]
I consider this a requirement for any browser.

**Comment by CliqueBait** [comment]
Is this likely to get some attention any time soon?

I'm guessing the full implementation is likely to require substantial work which should be focussed on more central features/issues at this point. Would it be ok to have an interim implementation of a simple "invert colours" toggle? I've found that that can often yield reasonable results for night time reading.

Advantage: There would be an early form of theming which serves a practical useability purpose (as opposed to purely cosmetic purpose.)

Disadvantage: The toggle may amount to an ugly wart in the source code when work commences on the full implementation.

**Comment by bsclifton** [comment]
@CliqueBait our stylemaster @jkup is working hard on a restyle which should make theming much easier :smile: Coming soon will be a new `about:styles` where you can see all the controls we create and maintain and that should help greatly when it comes to theming. 

If you wanted to skim his proposal doc, take a peek here:
https://github.com/brave/browser-laptop/pull/5205

Any input is greatly appreciated :smile: Right now, the styles are not encapsulated well enough that making changes can be scary and even trying to offer just 1 alternate theme color set might be too risky

**Comment by JonnyRedHed** [comment]
Would be nice to see some default add-on to change a website or page on
a website to nightime mode. Like the very good Chrome add-on called
'Care your Eyes'. go look it up. Install it in Chrome or Opera or
Vivaldi, choose whitelist mode and then when you get a bright white page
just click its add-on icon and choose 'enable this site' and watch it
change to a nice dark theme based on browns.

I use it every day in the above browsers I mentioned and find it the
best of the free nightime add-ons, outside of using Stylish.

Using a large 50inch plasma TV screen for my computer in a dimmed front
room I really need my nightime themes so have like 100+ stylish ones.
But the 'Care your Eyes' add-on makes for a quick switch if your reading
some article on some random site. It remembers the domain, and soon the
dev plans to make it remember just one page on a domain, jot the whole
domain if you desire.

Please consider some default built in thing like this.

URL:
https://chrome.google.com/webstore/detail/care-your-eyes/fidmpnedniahpnkeomejhnepmbdamlhl?hl=en

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/7243)

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/nightmode-any-news-about-it/848

**Comment by rchrdnsh** [comment]
+1 for a dark mode :-)

**Comment by twhiting** [comment]
+1 for night/dark mode... a must when i'm working late.

**Comment by srirambv** [comment]
+1 from community
https://community.brave.com/t/hi-love-your-browser-just-1-question/1215

**Comment by JonnyRedHed** [comment]
Opera dev browser has a built in UI dark mode for the window frame and top tool bars etc.  And Vivialdi is doing it right adding so many UI theme options for dark modes right in the browser with some cool sections.   I would like to see Brave go even further, once dark mode is set, custom or pre-set etc,  also all the settings pages. ALL.

Just to recap.....



Nightmode for the UI yes, but also any webpage. Read on...

Would be nice to see some default add-on to change a website or page on
a website to nightime mode. Like the very good Chrome add-on called
'Care your Eyes'. go look it up. Install it in Chrome or Opera or
Vivaldi, choose whitelist mode and then when you get a bright white page
just click its add-on icon and choose 'enable this site' and watch it
change to a nice dark theme based on browns.

Care Your Eyes - add-on
https://chrome.google.com/webstore/detail/care-your-eyes/fidmpnedniahpnkeomejhnepmbdamlhl?hl=en

I use it every day in the above browsers I mentioned and find it the
best of the free nightime add-ons, outside of using Stylish.

Using a large 50inch plasma TV screen for my computer in a dimmed front
room I really need my nightime themes so have like 100+ stylish ones.
But the 'Care your Eyes' add-on makes for a quick switch if your reading
some article on some random site. It remembers the domain.

In white list mode all I need to do is click the add-on icon on the add-on bar and choose enable night mode and it remembers the domain. I have requested the dev also add options to just allow one page on domain but not whole domain.

Please consider some default built in thing like this.

URL:
https://chrome.google.com/webstore/detail/care-your-eyes/fidmpnedniahpnkeomejhnepmbdamlhl?hl=en

**Comment by Mooties** [comment]
I need dark mode especially night mode for the hideous white youtube. I've tried googling all over to find a solution but nothing works or it take extreme effort to actually do it

**Comment by luixxiul** [comment]
For a global solution please check out this software: https://justgetflux.com/

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/dark-reader-extension/3580/2

**Comment by JonnyRedHed** [comment]
Don't forget night mode should go further than the new Opera dark mode UI.  It should also cover all the settings and security and add-ons pages etc.   I have tried to point this out to Opera devs as well.  For a full complete night mode not just the UI frame and tab bar.

**Comment by mirkinoid** [comment]
dark theme was literally the first thing I've been looking after initial install

**Comment by JonnyRedHed** [comment]
If going further and adding a dark mode UI to all settings and add-on and security pages etc.  Maybe a switch top right of each window can be shown once the main dark mode UI switch is on. So users can turn off one or a few settings pages if so desire.    

If using stylus or care your eyes (add-on) to make web pages look dark,  the last thing you want late at night on a large screen is to go onto a bright background settings or add-on page.   

A complete dark mode UI and all settings pages.

**Comment by Dudes1** [comment]
@luixxiul

Thanks for sharing the below, it rocks!

https://justgetflux.com/

**Comment by ChillyHellion** [comment]
I think Dark UI Mode is a feature worth focusing on.  Comparing Mozilla Firefox, Google Chrome, Microsoft Edge, Opera, Vivaldi, and Brave - Brave is the only browser on this list that doesn't have a dark UI option.  Firefox, Opera, Vivaldi, and Edge have it built in, while Google Chrome supports third-party dark UI themes.

**Comment by JonnyRedHed** [comment]
I agree.     Opera has their new dark mode UI switch which works well and they are working on making icons look good with the dark mode UI on.  But they have not gone far enough I think by not also covering all settings pages, security, add-ons, experiments etc.  Having an option top screen left or right to also toggle those settings pages dark also.    I let them know this.  And also here for Brave, you have a chance to do this now you've seen Opera's dark mode and can go further with all settings pages as well for a real full dark mode UI.

**Comment by jamesray1** [comment]
+1 for dark mode. I already use f.lux, but it just ain't enough. On a white background, it's way too glary still. It's also important to make sure that images aren't inverted, e.g. so that people don't look like this:
 
![image](https://user-images.githubusercontent.com/16969914/28066585-ec93d34a-6680-11e7-9c91-2804773f03d8.png)
![image](https://user-images.githubusercontent.com/16969914/28066762-9010d46e-6681-11e7-86e5-9c4c2ea75238.png)
![image](https://user-images.githubusercontent.com/16969914/28066820-dc3ff310-6681-11e7-843c-6a91b46ba59b.png)

**Comment by Rafi993** [comment]
I am using this bookmarklet http://tonymuka.com/js/ for now and it does not invert images

**Comment by Rafi993** [comment]
on plus side it works on android brave too

**Comment by Dudes1** [comment]
CF Lumen is way better than flux but, anyway, for a browser that offers dark mode, I'm using Firefox now. 
![screenshot_20170713-193128](https://user-images.githubusercontent.com/2838746/28196090-296449ca-6803-11e7-9a75-f19fda799912.png)

**Comment by JonnyRedHed** [comment]
Dark UI mode will be great. But you could also go the extra mile and also include ALL settings, extensions etc pages in the dark mode UI once turned on.   Maybe even allow each settings page to override dark mode if one so desires.    Making it a full and proper dark mode, front UI and back end pages and UI dark mode.  Mirror over to Android as well please.   Be the first dev team to have truly dark mode UI right through the browser on all platforms.

**Comment by eljuno** [comment]
+2 from community https://community.brave.com/t/any-consideration-being-given-for-a-night-mode-extension/5608

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/needs-a-bark-theme-or-a-way-to-add-themes/5867/2 and many more

**Comment by jonathansampson** [comment]
Should we dupe this to #271, or vise versa? cc @bradleyrichter @cezaraugusto

**Comment by bsclifton** [comment]
@jonathansampson although they're similar, I think they're different

Dark UI would be just offering a theme that has darker colors.  Night mode would be similar to what Apple offers which is stripping out the blue colors to make things easier on the eyes

**Comment by Liunkae** [comment]
#271 is just about the UI; this issue is to make everything darker (including websites themselves).

**Comment by JonnyRedHed** [comment]
For me at the moment to make web pages dark, the best two options are below in my opinion.


'**Care your eyes**' - chrome extension - can be used in Opera, Chrome, Vivaldi etc. Good for random web pages you want dark.  Care your eyes uses a nice dark brown hue for the dark mode which is quite a nice balance of night time or dimmed room colors.   **It also Remembers top level domains**. Dev is working on remembering single pages rather than just top level domain.

*set up: choose white list mode, then just use the 'Enable at this site' to make a page dark and have it remember. Very easy for those random web pages and articles you want dark.

url:
https://chrome.google.com/webstore/search/care%20your%20eyes

--
**Stylus** - better than Stylish - no data mining etc of your history and habits. 
                   Far fewer permissions than stylish.
https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en

Stylus Dark UI - Manage styles page etc with the stylus UI in dark mode.  
https://userstyles.org/styles/142097/stylus-gray-matter-chromium-based-or-firefox

**Comment by sogasg** [comment]
Here is a good example: [https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj?hl=en](https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj?hl=en)

**Comment by srirambv** [comment]
Closing in favour of #271 as it has been added to triage backlog and the issue has been cross referenced here.

**Comment by apandji42** [comment]
+1

**Comment by RaviH** [comment]
+1

**Comment by tsingi** [comment]
Just adding my two cents.
I really hate that Brave doesn't have a dark theme.
It's why I haven't used it up to now.  Firefox is becoming such a pig, and now they're also morally suspect.  I'd love to switch over.

**Comment by JonnyRedHed** [comment]
I see Opera v55 has now also done the settings page in their dark mode UI.  Also the update page.   And soon they will be doing the extensions page and in time the on page right click context menu and menu drop downs in dark theme.  Once dark mode is turned on.

It would be good if the brave devs take a look at what opera v55 is doing.  Open a new tab and click the settings on the right and turn on dark mode UI.  Then see the UI frame and tab bar go dark, and settings page, and update page.


They are continuously doing work on the tab bar to make fav icons of websites look good in dark mode.

**Comment by superherointj** [comment]
How do I enable Dark mode in Brave?

**Comment by JonnyRedHed** [comment]
There is no dark mode UI to enable. Not yet at least, thats the whole point of this request thread.

**Comment by crysman** [comment]
+1 for implementig "dark mode"

**Comment by himynamesned** [comment]
+1 for dark mode

**Comment by Liunkae** [comment]
Using the [Dark Reader extension](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/related) on the developer release of Brave ([brave-browser](https://brave.com/download-dev)). Looks great!
![](https://user-images.githubusercontent.com/19424103/45257898-264d2100-b373-11e8-9028-ffef7e00ed57.png)

**Comment by JonnyRedHed** [comment]
Looks good.  Shame I can never get the developer release of Brave to install, it just fails every time trying to access the internet. Even with whitelisting the exe through the firewall.

**Comment by srirambv** [comment]
@JonnyRedHed  are you on Windows 7?

**Comment by JonnyRedHed** [comment]
Yep.

**Comment by JonnyRedHed** [comment]
@srirambv  yes thats better. Installed now.   Is dark mode on by default then, are there other dark mode settings one can enable.   Is there a forum for discussion of the dev Brave.

**Comment by Liunkae** [comment]
@JonnyRedHed Here's what I've found:
1. Dark mode is on by default in Settings. This covers the url bar and toolbar.
![](https://user-images.githubusercontent.com/19424103/45311384-90d69c00-b4ee-11e8-9b24-b8f30d670b5b.png)
2. Dark mode needs to be turned on separately for developer tools.
![](https://user-images.githubusercontent.com/19424103/45311458-c54a5800-b4ee-11e8-810e-dc7413e6db15.png)
3. Third party extensions can be installed to make websites look dark.
4. Dark mode is not available yet for browser pages (e.g., `chrome://settings/`) and popups (Brave shields and the "kabob" menu).

**Comment by JonnyRedHed** [comment]
Thanks, all turned on.   Yes, a good start, look forward to the next steps.  But yes, the shields UI will benefit a lot from dark mode, and settings pages in time.  In time the right click context menu (which I understand is tricky with chrome). And then drop down menus.

Vivaldi is doing a good job with dark mode UI extending onto setting pages, history, bookmarks etc.  And so is Opera with its most recent v55 onwards releases.
