### ISSUE TITLE
Brave does not respond on clicks

### ISSUE THREAD

**Issue by pongraczi** [brave/browser-laptop#10910]
- Describe the issue you encountered:
Cannot change tabs, brave does not respond to clicking on tabs anymore.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Mint 18.2 64 bit, X

- Brave Version (revision SHA):
```
Brave: 0.18.29 
rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 
Muon: 4.3.16 
libchromiumcontent: 60.0.3112.113 
V8: 6.0.286.56 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64
```

- Steps to reproduce:
    1. Trying to remove a tab from the main screen -> did no happen, brave did not respond to clicking on tabs anymore
    
- Actual result:
![brave_01](https://user-images.githubusercontent.com/5891983/30317051-4b058cbc-97a9-11e7-92dc-2349321f7b7d.gif)

**Comment by luixxiul** [comment]
Hello, would you mind updating to 0.18.30 and see if it would be fixed? thanks!

**Comment by pongraczi** [comment]
Sure, but I only have 0.18.29-1.  
I tried the following:  
- deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt xenial main
- deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt-staging xenial main
-  https://laptop-updates.brave.com/latest/mint64
All of them are 0.18.29-1.

**Comment by NejcZdovc** [comment]
@pongraczi you can enable `previews` in Preferences->Advance->Update to preview releases

**Comment by pongraczi** [comment]
Thank you, but I have to tell you, I have no idea, where to enable preview.  
I tried with synaptic (Preferences), Brave itself (about:preferences#advanced), directly, I did not find such an option: **Update to preview**  
Could you please be more specific, like a good father to his stupid son? Thanks. :)

**Comment by NejcZdovc** [comment]
@pongraczi under Advanced tab you can find it under first toggle

![image](https://user-images.githubusercontent.com/9574457/30323441-8453c0f6-97bd-11e7-9bfd-c498b2001d80.png)

**Comment by pongraczi** [comment]
Ok, I understand. Unfortunately I have no such an option:  
![kijeloles_580](https://user-images.githubusercontent.com/5891983/30323509-c2b0f512-97bd-11e7-84a0-6cc7087dd3c7.png)

**Comment by pongraczi** [comment]
If you can give me a direct link for a deb package, it is not a problem to test it for bugs.

**Comment by Liunkae** [comment]
The latest builds are available here: https://github.com/brave/browser-laptop/releases

**Comment by pongraczi** [comment]
Thanks, I found it and I already upgraded to the latest, so, we will see.

**Comment by luixxiul** [comment]
Closing as stale. Let's reopen this if we still see the issue on 0.19 👍
