### ISSUE TITLE
Fix the wrong BEM naming on paymentsTab.js

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10912]
**Describe the issue you encountered:** Update paymentsTab.js to the modified BEM style (ref: https://github.com/brave/browser-laptop/blob/master/docs/style.md#defining-our-blocks-elements-and-modifiers).

I have refactored that file before the rule was created, so the styles are not organized well.

- Brave Version (revision SHA): master branch

- Any related issues:

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
