### ISSUE TITLE
Inconsistent address bar behavior for the text input

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#10915]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
address bar treats the input entry as a URL instead of a query when it looks similar to domain address
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.6
- Brave Version (revision SHA):
0.18.29
- Steps to reproduce:
    1. type 'f.lux' in the address bar (where f.lux is a name of software)
    2. get the "server DNS address could not be found" error
    3.
    
- Actual result:
"server DNS address could not be found" error
- Expected result:
search result page based on the keyword entered
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

![screen shot 2017-09-12 at 1 20 58 pm](https://user-images.githubusercontent.com/4369856/30346559-02c13392-97be-11e7-8476-33bbce9dd5a8.png)

- Any related issues:

**Comment by luixxiul** [comment]
that issue is tracked on https://github.com/brave/browser-laptop/issues/3317
