### ISSUE TITLE
Combined Tab and Navigation Toolbars Option

### ISSUE THREAD

**Issue by cwmke** [brave/browser-laptop#1091]
One of the annoyances I always had with Chromium and now Firefox was the inability to combine the two bars into one to maximize screen space.  This could be a nice option for the future.

**Comment by SJ-Diamond** [comment]
Exactly. It would be nice to have the option to have both tabs and url field/forward/backwards/reload button in one single bar as additional option at some point. Saves tones of screenspace ad the OP has already written and offers for power users a very nice workflow.

**Comment by Arandhras** [comment]
I kinda like the idea too! It's not much relevant for big screens (1080p and above), but on smaller screens like the ones in economic laptops and netbooks, it's definitely something that could be nice to have.

**Comment by SJ-Diamond** [comment]
It depends. Also on larger screens you have that way the 2 most important elements in one single bar :)

**Comment by paanvaannd** [comment]
For reference, there is a great Firefox addon that does just this and it executes it wonderfully: https://addons.mozilla.org/en-US/firefox/addon/prospector-oneLiner/?src=userprofile. Though it was last updated in 2011, it still works well in current Firefox versions. I would really like to see this implemented in Brave as well.

I think it would mesh with Brave's `auto title bar` feature to hide the search bar when not in use as well as move it over to the left side of the bar to allow room for tabs from the middle to the right. Furthermore, `tab sets` makes sure that tab overflow is not an issue with the shorter room given to tabs in this layout.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-combined-tab-and-navigation-toolbars-option/10062

If you guys are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for issues you might experience :+1: Thanks!
