### ISSUE TITLE
clicking on "magnifying glass" in URL bar under about:newtab displays certificate modal when loading website

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10922]
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

Clicking on the "magnifying glass" in the URL bar under `about:newtab` will popup the certificate modal once a website has been loaded within the same tab.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

macOS 10.12.6 x64 - Reproduced
Win 10 x64 - Reproduced
Ubuntu 17.04 x64 - Reproduced

**- Brave Version (revision SHA):**

> Brave: 0.18.29 
> rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 
> Muon: 4.3.16 
> libchromiumcontent: 60.0.3112.113

> Brave: 0.18.32 
> rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 
> Muon: 4.3.18 
> libchromiumcontent: 61.0.3163.71 

**- Steps to reproduce:**

1. launch Brave
2. under `about:newtab`, click on the magnifying glass in the URL bar (nothing should happen)
3. load brave.com and you'll notice that the certificate modal appears while the page is being loaded
    
**- Actual result:**

Certificate modal appears during page load.

**- Expected result:**

Certificate modal shouldn't be appearing on the initial page load.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

Yes

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

![certissue](https://user-images.githubusercontent.com/2602313/30359242-5b9c1ca8-9817-11e7-8b15-01c460124f3e.gif)

**Comment by NejcZdovc** [comment]
@kjozwiak I tried this with the latest 0.21.x and can't reproduce, can you please specify issue range

**Comment by kjozwiak** [comment]
@NejcZdovc, added the regression ranges for both the 0.18.x and 0.19.x branches.

**_Regression range from the 0.18.x branch:_**

The following commit caused the regression which is still present in the latest 0.18.32 rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 build.

> commit b332d8e69f987a9e3e82c1334299446b2e92e0dc
> Author: Brian R. Bondy <bbondy@gmail.com>
> Date:   Fri Jun 9 06:08:45 2017 -0700
> 
>     Merge pull request #9154 from brave/navigation-state2
> 
>     Navigation state

**_Regression range from the 0.19.x branch:_**

The following commit introduced the regression:

> commit f3b80609976d90ef120bdcffbd7cd466e8ff4fc5
> Merge: f1ab99705 c4a0eb3aa
> Author: Brian R. Bondy <bbondy@gmail.com>
> Date:   Fri Jun 9 06:08:45 2017 -0700
> 
>     Merge pull request #9154 from brave/navigation-state2
> 
>     Navigation state

The following commit fixed the regression:

> commit 3ef36a4817c5679d054ae3da7fc431fe014b8c6d
> Author: bridiver <github@brianjohnson.cc>
> Date:   Fri Jun 9 16:18:27 2017 -0700
> 
>     handle exit signals cleanly
>     possible fix for #9373

**Comment by NejcZdovc** [comment]
so if I understand this correctly, this was fixed in 0.19.x?

**Comment by kjozwiak** [comment]
> so if I understand this correctly, this was fixed in 0.19.x by 3ef36a4?

Yup, that's correct. The issue was fixed in 0.19.x by 3ef36a4. Closing the issue.
