### ISSUE TITLE
"Save As:" field not scrollable when downloading long filenames

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#10924]
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

Filenames under the "Save As:" field when downloading a file are not scrollable. When a filename is longer than the default width, users won't be able to scroll through the entire filename.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

macOS 10.12.6 x64 - Reproduced

**- Brave Version (revision SHA):**

> Brave: 0.18.29 
> rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 
> Muon: 4.3.16 
> libchromiumcontent: 60.0.3112.113

> Brave: 0.18.32 
> rev: e94738d9f289e9fb1a0e95aea29ee2c37196a271 
> Muon: 4.3.18 
> libchromiumcontent: 61.0.3163.71 

**- Steps to reproduce:**

1. Open Brave and visit https://www.deviantart.com/art/Dark-and-Day-Al-Jebra-208669006
2. Right click on the image and select "Save Image"
3. Attempt to scroll through the filename in the "Save As:" field

**- Actual result:**

The filename text under "Save As:" field isn't currently scrollable.

**- Expected result:**

The filename text under the "Save As:" field should be scrollable. User should be able to scroll through the entire filename that's being displayed.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

Yes

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

![downloadscroll](https://user-images.githubusercontent.com/2602313/30360576-4cdebc62-9820-11e7-8e42-c64324f39031.gif)

**Comment by NejcZdovc** [comment]
@kjozwiak was this working before 0.18.x?

**Comment by kjozwiak** [comment]
> @kjozwiak was this working before 0.18.x?

Looks like the issue has been in Brave for sometime now. I went through the following builds and could still reproduce the original issue mentioned above using the same STR:

- Brave: 0.18.29 rev: 85f059d83b8861b3a7e127c42b2fe9d574be5810 - Reproduced
- Brave: 0.18.23 rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 - Reproduced
- Brave: 0.18.14 rev: ad92d029e184c4cff01b2e9f4916725ba675e3c8 - Reproduced
- Brave: 0.17.19 rev: 4e46480561da44d76d6ee4c60d6979df80d339f8 - Reproduced

I checked `Chrome 60.0.3112.113` and it looks like it's working there.

**Comment by Liunkae** [comment]
Related: #12628

**Comment by Liunkae** [comment]
May be fixed by #11906 in 0.21.0, but I have not tested yet.

**Comment by Liunkae** [comment]
I have confirmed this was fixed by #11906 in 0.21.x.

**Comment by bsclifton** [comment]
@Liunkae awesome! thanks for testing 😄  I'll close / mark milestone as 0.21.x

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
