### ISSUE TITLE
URL bar autocomplete does not pull the web site suggestion at top

### ISSUE THREAD

**Issue by dq429** [brave/browser-laptop#10928]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X Sierra 10.12.6

- Brave Version (revision SHA): 85f059d

- Steps to reproduce:
    1.  I visit theverge.com often.  Start typing 'theverg'
    2. It only gives me a story I clicked on a few times.  
    3. I would like the site to be the top suggestion.  Similar to Chrome.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/10662
