### ISSUE TITLE
pinch zoom parity

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#10921]
Compare these items with Chrome:
1. Zoom in/out at Google Map, Chrome will only affect map view not entire webview
2. Chrome doesn't allow to zoom out < 100%
3. Zoom in/out is not smooth

related issue: https://github.com/brave/browser-laptop/issues/1364

**Comment by Liunkae** [comment]
Seems fixed. I cannot reproduce with Brave 0.20.30 on macOS 10.13.x. This may have been fixed at the same time as #1364.

**Comment by bsclifton** [comment]
Awesome, thanks for confirming @Liunkae! Also confirmed by @darkdh.  Closing issue
