### ISSUE TITLE
Alt+Tab_Number To Select Tabs

### ISSUE THREAD

**Issue by cwmke** [brave/browser-laptop#1092]
Currently only Ctrl + tab number is selecting tabs on Linux.  That traditional option in most browsers is Alt + tab number.

**Comment by bbondy** [comment]
I have a patch for this but it's not working because electron local shortcuts uses focused window only and when you press Alt on Ubuntu it shows the menubar and removes focus.

**Comment by cwmke** [comment]
Alt showing menubar is annoying so it is probably better to get used to Ctrl for now.  Thanks for your comment.

**Comment by skovsgaard** [comment]
Any news on this? Or still the Ubuntu issue?

**Comment by Liunkae** [comment]
+1 from #7174.

**Comment by develCuy** [comment]
Ubuntu 14.04 user here. This bug is annoying ;(

**Comment by skovsgaard** [comment]
This is fixed for Fedora 25, Brave v0.13.4.

**Comment by nikolas** [comment]
Chrome and Firefox both use Alt-<number> to open tabs. Is there anything preventing this from happening?

The alt key also opens up the menubar in Firefox as well, but alt-<number> still opens the appropriate tab and it works fine.
