### ISSUE TITLE
Unique icons needed for the different product channels

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10938]
This is a continuation of https://github.com/brave/browser-laptop/issues/4120

We have all the icons for the product itself.  However, we are missing icons for:
- installer (the EXE on Windows or the DMG once mounted)
    -  brave_installer.icns, brave_installer.ico, brave_installer.png
- the Brave logo when inside the DMG installer 
    - background.png
- the Brave logo when inside the Windows installer
    - brave_splash_installing.gif

cc: @darkdh 

The work to create separate channels was done with https://github.com/brave/browser-laptop/pull/10552

**Comment by bradleyrichter** [comment]
@bsclifton Here are the new app icons for all build types:

![image](https://user-images.githubusercontent.com/13509546/33358916-5fa666be-d480-11e7-856e-2a51d59f9392.png)


[Brave_Desktop_iconset.zip](https://github.com/brave/browser-laptop/files/1512592/Brave_Desktop_iconset.zip)

**Comment by bsclifton** [comment]
@darkdh should be an easy one if you wanted to grab this 😄 👍

**Comment by bradleyrichter** [comment]
@darkdh ok, refreshed ZIP and previews above...
