### ISSUE TITLE
Translator plugin/extension for brave? 

### ISSUE THREAD

**Issue by briannyeko** [brave/browser-laptop#10949]
- Did you search for similar issues before submitting this one?
yeah. 
- Describe the issue you encountered:
no automatic translation plugin(chinese => english, japanese => english, korean => english etc). 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS
- Brave Version (revision SHA):
the latest one 
- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Hi @briannyeko, thanks for the report 😄   We have talked about integrating with a translation service. I'd like to close this issue in favor of the one we've been using to track that request.  Please see https://github.com/brave/browser-laptop/issues/858
