### ISSUE TITLE
Implement BAT into payments

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10945]
**Describe the issue you encountered:**
Implement BAT into the existing ledger code.

Notes from @mrose17:
1. you no longer need the `ledger*` packages
2. instead, put this in `package.json`
```
"bat-balance": "^0.9.0",
"bat-client": "^0.9.0",
"bat-publisher": "^0.9.0",
"bignumber.js": "^4.0.4",
```
3. wherever you see `require('ledger-*')` in `app/ledger.js` use the `bat-*` package instead
4. get rid of anything relating to `geoip`, as this is no longer used
5. when you instantiate `ledgerClient = ...` include `version: 'v2'` in the `options` parameter. the easiest way to do this is to add that value to `clientOptions` near the top of the file
6. you can continue to call `ledigerClient.getWalletAddress`, which returns the BAT address, or you can call `ledgerClient.getWalletAddresses` which returns an array of all addresses
7. you will probably make the most changes in the `updateLedgerInfo` and `getPaymentInfo` routines because this is where you get the current wallet state
7a. here is an example of what `getPaymentInfo` gets when the callback to `client.getWalletProperties` invokes the callback:
 ```
{
  "paymentStamp": 0,
  "rates": {
    "USD": 0.19361672240887554
  },
  "addresses": {
    "BAT": "0x7c31560552170ce96c4a7b018e93cddc19dc61b6"
  },
  "altcurrency": "BAT",
  "probi": "32061750000000000000",
  "balance": "32.0618",
  "unconfirmed": "0.0000"
}
```
the  `balance` and `unconfirmed` fields are now denominated in BAT rather than BTC. instead of `satoshis`, the `probi` field shows the BAT "wei", so if you want the exact number of BAT, you'll need to put that into a BigNum and then divide by 10^18. you can convert to USD by doing balance * rates.USD
you may notice that `buyURL`and `buyURLExpires` have gone away.
when we have a buy widget for BAT, then `buyURL` will come back.
7b. here is an example of what `updateLedgerInfo` sees in `ledgerInfo._internal.paymentInfo`:
 ```
{
  "balance": "32.0618",
  "altcurrency": "BAT",
  "probi": "32061750000000000000",
  "address": :0x7c31560552170ce96c4a7b018e93cddc19dc61b6",
  "addresses": {
    "BAT": "0x7c31560552170ce96c4a7b018e93cddc19dc61b6"
  },
  "amount": 5,
  "currency": "USD",
  "BAT": "25.7854"
}
```
again, no `btc` and `satoshis` fields, but `BAT` and `probi` fields.
8. finally, there is one bit of information hiding that i missed in the `ledger-client` package: in `getStateInfo` instead of doing
`ledgerInfo.passphrase = state.properties.wallet.keychains.passphrase`
do
`ledgerInfo.passphrase = ledgerClient.prototype.getWalletPassphrase(state)`

**Comment by NejcZdovc** [comment]
@mrose17 I noticed that we renamed ledger into bat. Should we rename `.json` files as well?

**Comment by mrose17** [comment]
_you have questions, we have answers!_

1. _I noticed that we renamed ledger into bat. Should we rename .json files as well?_ you can if you wish, but i wouldn't. we went from "btc" to "bat", but it's still "the ledger"

2. _I notice that we don't actually use satoshis in the current code, should we implement probi?_ i wouldn't bother doing that until we need it. you can probably just do `1,$s/stoshis/probi/g` in the code and forget about it.

3. _should we already see this amount when you create a new wallet?_ yes, because you are talking to a "mock" server that pre-loads some bat into your wallet. when we move it to the uphold server (probably today or tomorrow), it will start at zero.

4. _What will happen with this section?_ `1,$s/Bitcoin/Ethereum/g` and `1,$s/BTC/ETH/g` with *one exception* the final text should read `Use any ETH wallet that can transfer BAT to your Brave wallet`

ps: @NejcZdovc - thanks for finding and fixing the bugs in the `1ledger-client` repo. i am pushing a new version in about 10m

**Comment by NejcZdovc** [comment]
thank you for answers, I have few more

1) what happens with this section
![image](https://user-images.githubusercontent.com/9574457/30430215-cbf95f58-995a-11e7-855f-b15425a255c3.png)
2) are we still limiting section mentioned above by countries?
3) add found uphold widget is still in WIP phase right?

**Comment by mrose17** [comment]
_and i have a few more answers_

1. _what happens with this section_: It becomes *Buy BAT at our recommenced source* and says "Uphold" and takes them to https://uphold.com

2. _re we still limiting section mentioned above by countries?_ no, there is no more "geoip" in use . ... it is possible in the future we may return "geoip" to find other places selling BAT to consumers, but not for the immediate future.

3. _add found uphold widget is still in WIP phase right?_ i'm not sure what "found uphjold widget" refers to!

**Comment by NejcZdovc** [comment]
> add found uphold widget is still in WIP phase right
I think that you answered it with 1 answer

**Comment by mrose17** [comment]
got it, thanks!

**Comment by bradleyrichter** [comment]
adding crypto svg icons for buttons

[crypto_icons.zip](https://github.com/brave/browser-laptop/files/1326677/crypto_icons.zip)

**Comment by luixxiul** [comment]
no-qa-needed (as it had been done already) ?

**Comment by kjozwiak** [comment]
@NejcZdovc, can we mark this as `no-qa-needed` as the BAT implementation is being tested through the test plan that @srirambv, @LaurenWags and myself created?

**Comment by NejcZdovc** [comment]
no I don't think so. BAT flow become main stream now with ledger manual test plan
