### ISSUE TITLE
Site added instantly to the ledger

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10955]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Site is added instantly to the ledger, minimum visit time is not used.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
b0d7fc0
- Steps to reproduce:
    1. go to payments and enable it
    2. visit a site and switch to payments immediately
    
- Actual result:
![image](https://user-images.githubusercontent.com/9574457/30429988-e40b8586-9959-11e7-9ebd-a1e65f6e82c9.png)
- Expected result:
site should be added only after 8s on that site
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
I think this is same as #10036
