### ISSUE TITLE
Installing While Brave is Open Crashes the Installer, Error Should be Handled

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1096]
Handle Error of if Brave is Open, Handle the Error, By Prompting User to Close or Have a Auto-Close Timer of 10-15 Seconds. 
[Log](https://github.com/brave/browser-laptop/files/176977/SquirrelSetup.txt)

**Comment by bbondy** [comment]
Should be handled by: https://github.com/brave/browser-laptop/issues/523
