### ISSUE TITLE
Downloads bar: View All and Close seem too close together

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#10966]
Brave 0.18.29 on macOS 10.12.x

For some reason, the buttons look too close together to me. Thoughts anyone?

![image](https://user-images.githubusercontent.com/19424103/30466796-f80b070e-99a5-11e7-9f02-cd6b9c749237.png)

**Comment by luixxiul** [comment]
It was fixed for 0.19 series. See: https://github.com/brave/browser-laptop/issues/10277

**Comment by Liunkae** [comment]
@luixxiul Thanks. I searched but couldn't find it.

**Comment by luixxiul** [comment]
@Liunkae Try duckduckgo or Google. They are obviously better than GitHub search ;-)
