### ISSUE TITLE
Clearing history should clear url suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#10962]
@NejcZdovc mind taking this? Please make sure it works across the branches. It might already work for sites splitting branch for example but need it fixed on 0.19.x too.

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Clearing history in about:preferences (on demand or on shutdown) keeps url suggestions

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):
0.18.29

- Steps to reproduce:
    1. Make a backup of your profile
    2. Go to about:preferences
    3. Clear browsing history
    4. Restart the app
    5. Type a URL that's in your history into the URL bar, it should not show up as a suggestion.
    
- Actual result:
about:history doesn't have the entry, but the URL bar does.

- Expected result:
Suggestions should no longer show.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by NejcZdovc** [comment]
@bbondy only in 0.21.x we added remove functionality for bloodhound. Should we trigger complete re-initialization of bloodhound when clear is triggered manually?

On shutdown there shouldn't be any problems

**Comment by bbondy** [comment]
Actually this is invalid / a dupe of something already fixed.
If you close the browser it doesn't show up, it's just the in memory cache while it is open.

**Comment by bbondy** [comment]
Dupe of https://github.com/brave/browser-laptop/issues/10723
