### ISSUE TITLE
Session-Store-1 file saves necessary information but unnecessarily stores it

### ISSUE THREAD

**Issue by NumDeP** [brave/browser-laptop#10975]
- Did you search for similar issues before submitting this one? 
Yes
- Describe the issue you encountered: 
Session-Store-1 file saves data/links even after a fresh profile from previous crashes or when quitting via task manager because of a freeze (when everything become unresponsive) It also seems to store the same data twice.

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Win10

- Brave Version (revision SHA): 
0.18.36 (7ab85e9)

- Steps to reproduce:
    1. AppData - Roaming - brave
    2. Open session-store-1 file with Notepad
    3. It displays many links and it seems like it's either all or most of the links from previous crashes.
    
- Actual result:
I should mention this also seems to be repetitive as you scroll down it seems do store the same website twice, so it looks like there are hundreds of websites separated like the below information x2 as you scroll.

x.com|0|0":{"lastAccessedTime":

x.com/favicon.ico","location":"https://www.x.com/","title":"x |

,"https://www.x.com/":["https://www.x.com|0|0"],

- Expected result:
Personally, I think it's alright that it sort of stores some data at least until I can cross it over elsewhere but the expected result should be what the session-store-1 file looks like from a fresh install only I find this dubious considering in about:preferences#security Private Data - I've got all but 6 of the preferences selected. 'Saved site settings and permissions' being the one not selected as notification can be annoying.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes. 

- Is this an issue in the currently released version?
Yes. Data has been seen since the last two releases but I think there's links available from several versions ago if that makes sense.

- Can this issue be consistently reproduced?
I could consider uninstalling it but I've got a bit of data stored so unless you ask me to I'm going to avoid it for the time being at least. This seems to be the only option to analyse consistency even though the data shouldn't be there especially after an update. 

- Extra QA steps:
    1. I've got all but the last feature in Private Data to be cleared on exit.

- Any related issues:

I usually just open and pose questions in the community page but I suppose I've annoyed the hell out of some of the members but this is pertaining to something related to @diracdeltas posted before so I hope you don't mind me posing a few questions related to session-store-1's. 

I've sort of been copy and pasting session-store-1 files all in all around 16 on my desktop that's after I realized your post explaining about the 5mins rule and before browser refresh you can manage to essentially recover the websites that were lost because of a browser crash or freeze (completely unresponsive). 

I imagined that the website links in the file would be neatly paragraphed one under the other so I can just simply copy and paste URLs in the address bar but it seems incredibly messy when opening with Notepad, possibly you can do something about this before a 'graceful session restore' because honestly it's really frustrating when you got dozens of tabs open and it crashes and you have to highlight every single link to retrieve the websites. 

Nevertheless, I noticed several things that I was sort of stumped by, one of which was the session-store-1 file seems to remain at 2,104 KB,
I can remember the s-s-1's used to be around 5,970 KB then after an update the s-s-1's the size reduced dramatically under 1000 KB so between 600 and 900 KB then after another update I noticed the size of the s-s-1's began to rise again 1,100-2000 KB and recently I've noticed the size of the s-s-1's being around 2,100 and 2,500 KB. I should mention that before most of the crashes I consistently had around 80 tabs not fully opened, this is data retrieved from all the times the browser has crashed on me which is in the dozens and I mean over 40, no joke; I think I was one of the first to report it in community.brave. (Not fully opened meaning right-clicking links without heading to the website/tab; I've got this terrible tendency to open multiple tabs without viewing them then shutting off once the links are saved) 

So opening the s-s-1 files with Notepad seems to show the history of all the tabs that remained either on a crash or freeze (when everything becomes non-clickable) which I found rather dubious considering in about:preferences#security Private Data, I've got all but 6 of the preferences selected, 'Saved site settings and permissions' being the only one not selected as notifications can be annoying.

Just another note in case it helps is that I also noticed there are multiple links within the s-s-1 of the same website despite there was only one tab opened related to that site before ending task via task manager or a crash.

**Comment by luixxiul** [comment]
CC @bsclifton and @NejcZdovc about that.

**Comment by bsclifton** [comment]
@NumDeP I recently ran across this when working on an issue with @darkdh... We basically have a cache (which is also stored in session-store-1) used to speed up lookups for bookmarks, history, etc.  Unfortunately, this can get quite large (my session file was near 30 MB).

@darkdh recently resolved that with https://github.com/brave/browser-laptop/pull/11162 which will be in our next release (you can also grab it from our releases page). You can go to clear history and that will actually clear the cache.  The fix also prevents duplicate entries from being added.

You also note the window state is being stored. I don't know offhand if there's a way to clear it, but as a work-around you can switch your settings to start brave with a home page and that will cause the window state to not get saved. After relaunching, you can set it back to "My windows / tabs from last time".  We intentionally save this information so that you can re-open previously closed tabs and windows (useful if Brave crashes and you want to reload that window because it had something important).

I hope this helps!  I'll close the issue, but please feel free to continue the discussion (I'll try to answer any questions you have 😄 )

**Comment by NumDeP** [comment]
Thanks for replying @bsclifton . It seem like there's going to be quite a few essential improvements made to 0.19.x so I don't want to badger you with plenty of questions just yet. However, could you perhaps ask @diracdeltas considering she was the one that suggested copying the s-s-1's or inform me yourself as to how I can retrieve the lost tabs/links neatly from the session-store-1 files I've stored over the months.

Using yourself as an example, if your session file was near 30 MB and you had 2 tabs open with 20 tabs per tab set and it either crashed or froze and then you immediately saved the s-s-1 file, how can you easily find/view the last websites/links within the s-s-1 file or even refresh it back to the browser?

Thanks.

**Comment by bsclifton** [comment]
@NumDeP the way most users would be restoring windows or closed tabs should be via the menu (or the associated shortcut).  This is an example on macOS:
![screen shot 2017-09-29 at 10 03 39 am](https://user-images.githubusercontent.com/4733304/31027588-900b1f08-a4ff-11e7-83bc-bdd591b14bc7.png)

On Windows, it should be Ctrl + Shift + T

**Comment by NumDeP** [comment]
@bsclifton I meant from each of the session-store-1 files users have copy and pasted locally. 

Say if you've got all Private Data to be erased on exit and whenever a crash occurred you saved (copy and pasted) a couple of s-s-1's outside the brave folder (locally) because you wanted to recover lost tabs later on when you're not so busy, considering after 5 minutes and after a second browser refresh (exiting and starting again) the browser will erase most of the data stored in the session-store-1 that is in the brave folder, how do you then begin to recover the lost tabs due to a crash or freeze from the session-store-1 files you saved locally on previous occasions?
