### ISSUE TITLE
Google Play Music broken

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#10972]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Main page of Google Play Music (https://play.google.com/music) doesn't display or work correctly. I get an error message at the bottom "Couldn't display recommendations" and nothing is clickable. Mouse scrolling doesn't work either. Additionally, after I try clicking on something, it seems to mess up my ability to change tabs with Ctrl-tab on MacOS. I can still click a different tab with the mouse to leave the tab. It works OK in Chrome stable right now.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12.6 on MacBook Pro (15-inch, 2016)

- Brave Version (revision SHA):
Brave	0.18.36
rev	7ab85e9
Muon	4.3.22
libchromiumcontent	61.0.3163.79
V8	6.1.534.32
Node.js	7.9.0
Update Channel	dev
OS Platform	macOS
OS Release	16.7.0
OS Architecture	x64

- Steps to reproduce:
    1. Load https://play.google.com/music/
    
- Actual result:
Page renders incompletely, clicking is inconsistent or broken. I can't play any music, scroll, or otherwise interact.

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
unknown

- Is this an issue in the currently released version?
yes

**Comment by Kr4ken-9** [comment]
I've encountered this problem on both 0.18.36 and previous versions.

**Comment by simonlayfield** [comment]
Homepage shows the below error for me:

<img width="421" alt="screen shot 2017-09-26 at 10 35 30 am" src="https://user-images.githubusercontent.com/2576361/30837181-859bfed0-a2a6-11e7-8986-4ce24beef6fd.png">

Console errors:

<img width="445" alt="screen shot 2017-09-26 at 10 39 55 am" src="https://user-images.githubusercontent.com/2576361/30837280-23aac6e2-a2a7-11e7-8c4a-1b656609675f.png">

Browsing and playing music generally seems to work, however selecting Start Radio on a track (shown below) doesn't work either.

<img width="207" alt="screen shot 2017-09-26 at 10 37 14 am" src="https://user-images.githubusercontent.com/2576361/30837281-2919b23c-a2a7-11e7-87c0-e1a867fb1e3d.png">

------
**Brave**	0.18.36
**rev**	7ab85e9
**Muon**	4.3.22
**libchromiumcontent**	61.0.3163.79
**V8**	6.1.534.32
**Node.js**	7.9.0
**Update Channel**	dev
**OS Platform**	macOS
**OS Release**	16.7.0
**OS Architecture**	x64

**Comment by luixxiul** [comment]
would you mind changing settings from the top right lion icon and let us know if it works (and which changes work?) thanks!

**Comment by luixxiul** [comment]
It look like Google is doing some changes, which break the services which has worked properly. See another example of me: #11078

**Comment by luixxiul** [comment]
here is an error which I get when I click the play button of an album cover: 
`listen__ja.js:1920 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.`

Actually I click the button by myself and that is obviously my gesture, though.

**Comment by stshank** [comment]
With shields down it works fine.

The setting that seems to break it is block all third-party cookies. It works fine with all cookies enabled.

Disabling HTTPS everywhere didn't fix.
Disabling block phishing/malware didn't fix.

**Comment by nevins-b** [comment]
Newest stable seems to have made this worse, unable to stream even with shields down. Reverted to 0.18.36

**Comment by stshank** [comment]
I have the same experience as above. I can't stream either with shields down or up.

**Comment by DanielJenkyn** [comment]
Seem to be having the same issue with Google Music not playing/streaming with shields up and down.

```
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64
```

**Comment by HCastano** [comment]
I'm getting the same error message from Google Play Music as @DanielJenkyn.

```
Brave: 0.19.48 
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64
```

I tried with shields up and down, but no luck with either.

**Comment by aneyeforsecrets** [comment]
Ditto.

```
listen__de.js:1917 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.
d.play @ listen__de.js:1917
d.play @ listen__de.js:1943
d.JDa @ listen__de.js:1946
d.Xnb @ listen__de.js:1939
(anonymous) @ listen__de.js:1938
d.$H @ listen__de.js:712
d.dispatchEvent @ listen__de.js:711
d.Ux @ listen__de.js:1916
$g @ listen__de.js:708
Vg @ listen__de.js:709
c @ listen__de.js:1175
(anonymous) @ listen__de.js:705
Promise (async)
d.play @ listen__de.js:1917
d.play @ listen__de.js:1943
d.JDa @ listen__de.js:1946
d.Xnb @ listen__de.js:1939
(anonymous) @ listen__de.js:1938
d.$H @ listen__de.js:712
d.dispatchEvent @ listen__de.js:711
d.Ux @ listen__de.js:1916
$g @ listen__de.js:708
Vg @ listen__de.js:709
c @ listen__de.js:1175
(anonymous) @ listen__de.js:705

```
 
```
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
```

**Comment by DanielJenkyn** [comment]
Related to #11527 

I'm also getting a similar error on another audio streaming/playing website [noisli](https://www.noisli.com/)

`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()`

**Comment by O1O1O1O** [comment]
Still getting this problem with 0.19.70

**Comment by KevDoy** [comment]
I have the same issue. 
It seems to affect play.pocketcasts.com as well.

**Comment by luixxiul** [comment]
Closing in favor of #11527.

For reporting the issue on other sites, please post one here: https://community.brave.com/c/qa/web-compatibility 😄
