### ISSUE TITLE
Brave Processes Not Auto Killing After Brave is Closed

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1097]
Brave Processes should be killed after closing to cleanly exit. Important for both Security and Performance. Particularly for Users on Windows who are affected by #1096

**Comment by bbondy** [comment]
Brave process shoudl be closed in the actual release of Brave (which matches RC 7).  Could you try the latest and confirm exact STR?

**Comment by bbondy** [comment]
This one is more exact of what I see:
https://github.com/brave/browser-laptop/issues/1119

**Comment by weems** [comment]
I installed 0.8.1 Beta. After running install and launching Brave I closed the window. The processes were still running afterwards.

**Comment by onmyouji** [comment]
I also experienced the same thing on Windows 7.

**Comment by bbondy** [comment]
@weems please forget about the pre-release builds of 0.8.1, they had an issue for this and it was fixed. Does the current and live release of 0.8.1 reproduce and if so what are the exact steps?

**Comment by bbondy** [comment]
For the pre-release if you have processes left over just kill them with the task manager to test fresh.

**Comment by weems** [comment]
@bbondy I see you have a pre-release fix, but in 0.8.1 Production processes are not being killed. STR is basically close Brave and use 'taskman' to see if processes remain. and currently they do.

**Comment by bbondy** [comment]
Confused because in Slack around the same time you said the opposite:

> confirmed processes are closed after Brave closes in the newest 0.8.1 dev channel on Win7 x64

**Comment by weems** [comment]
@bbondy at that time I had not yet updated to the pre-release version with the fix for processes closing

**Comment by bbondy** [comment]
OK thanks, closing this.
