### ISSUE TITLE
Support for blocking cross-site tracking?

### ISSUE THREAD

**Issue by rogersachan** [brave/browser-laptop#10983]
# Feature Request
Seeing as Apple is doing this now, I see good reason to be one of the first cross-platform solutions to do this.

EDIT: Firefox is doing this too, even by default on mobile/soon desktop.

# Sources
* https://webkit.org/blog/7675/intelligent-tracking-prevention/
* https://techcrunch.com/2017/06/05/apple-adds-a-tracker-blocker-to-desktop-safari/
* https://9to5mac.com/2017/09/16/apple-ad-tracking-statement/
* https://www.engadget.com/2017/09/16/advertisers-are-upset-with-safaris-new-anti-tracking-features/

**Comment by bsclifton** [comment]
cc: @diracdeltas

**Comment by rogersachan** [comment]
Here's an article from WebKit on how this works: https://webkit.org/blog/7675/intelligent-tracking-prevention/

**Comment by flamsmark** [comment]
Moving to the new codebase: brave/brave-browser#539
