### ISSUE TITLE
Extension API: chrome.browserAction.setPopup

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#10984]
https://developer.chrome.com/extensions/browserAction#method-setPopup

Pass a single _details_ object:
```
chrome.browserAction.setPopup(object details)
```

**Comment by mantriv** [comment]
Hi,
I am trying to open a popup using background script. I tried chrome.browserAction.setPopup passing the tabId and popup HTML url, but its not opening the popup. My requirement is to open the popup and display the content from the web page.

Thanks in advance.

**Comment by jonathansampson** [comment]
@mantriv I think you may be confusing this method (it has a confusing name). This method sets the browser action popup, which is the small window that appears when you click the browser action icon in the chrome of the browser. It sounds like you're wanting to open a popup window (`window.open`).

**Comment by mantriv** [comment]
Thanks for the response. Well my requirement is to open up the Chrome extension popup (popup.html) when I mouse hover on the web page say on link of google search result. 
I don't want user to manually click on the Chrome extension icon on the browser toolbar.
After opening the popup html, read the content from the web page and show on the chrome extension popup. Hope you are clear with the requirement. Thanks and appreciate your help.

**Comment by jonathansampson** [comment]
Dupe of #10986
