### ISSUE TITLE
Extension Needed Ultrasurf

### ISSUE THREAD

**Issue by arunkumarpalaniappan** [brave/browser-laptop#10990]
- Did you search for similar issues before submitting this one?
  Yes
- Describe the issue you encountered:
 Need Ultrasurf extension to bypass blocked websites using brave.
- Platform (Win7, 8, 10? macOS? Linux distro?):
 Debian 9
- Brave Version (revision SHA):
 7ab85e9

**Comment by bsclifton** [comment]
Added to our extension tracking 😄   You can follow the progress at https://github.com/brave/browser-laptop/projects/1
