### ISSUE TITLE
Close tab button is on the wrong side for Mac users regarding UX

### ISSUE THREAD

**Issue by Kwadz** [brave/browser-laptop#10993]
Steps to reproduce the problem:
1. Open a teb
2. Notice the close tab button in on the right

What is the expected behavior?
With an ergonomic approach, the close tab button **should be on the same side as the OS ones**, therefore **on the left**.

What went wrong?
The close tab button is on the right. It should be at least configurable or by default on the left like every close button in the OS.

Opera browser has implemented a very nice solution (the close tab button appears and replaces the icon on mouse over).

**Comment by NejcZdovc** [comment]
cc @bradleyrichter

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/8341
