### ISSUE TITLE
Brave has frozen twice today

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#10998]
- Did you search for similar issues before submitting this one?
Yes, there are 25 issues with "freeze".

- Describe the issue you encountered:
Brave comes up with an error, something like this 'unfortunately Brave has stopped. Please wait for it to reload or close the browser'. I left it for an hour but it was still frozen. It's hard to determine what causes the error, but I will keep an eye on it. I had around 5 tabs open each time.

- Brave Version (revision SHA):
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

- Steps to reproduce:
Unsure

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
No.

**Comment by srirambv** [comment]
Is this similar to https://github.com/brave/browser-laptop/issues/10053 ?

**Comment by jamesray1** [comment]
It is similar with the same error message. As to what was causing it at the time, it's hard to say. I didn't check the CPU and memory usage. But I didn't have heavy applications open at the time, I think it was just Brave and Windows file explorer.

**Comment by jamesray1** [comment]
It froze again with the same message:
![2017-09-20 12_36_28-greenshot](https://user-images.githubusercontent.com/16969914/30624572-8166cf7e-9e01-11e7-9fe0-518f7e866288.png)
Memory was 80% but CPU usage wasn't that high: about 30% for Brave and 40% total.
Right clicking on the Brave button in the taskbar and clicking close didn't close it. The close button didn't show in the top corner. So I had to use the error window to close it. Reopening the browser loaded all of the same tabs.

**Comment by Liunkae** [comment]
You might want to try the latest 0.19.x beta build. There were a few "freeze" issues fixed in 0.19.x. https://github.com/brave/browser-laptop/releases

**Comment by jamesray1** [comment]
Oki doki, happy to be a guinea pig. I also have experienced a couple of times today that nothing happens when I click on a non-active tab, so I have to restart the browser.

**Comment by jamesray1** [comment]
I've just updated it.

**Comment by jamesray1** [comment]
It keeps happening on Windows, just randomly. I can't switch to other tabs but can continue using the active tab.

**Comment by luixxiul** [comment]
Many issues will be fixed on 0.20.x including the tab freeze.

From my own experience I suspect the tabs are frozen when the browser consumes most of available RAM memory.

**Comment by jamesray1** [comment]
Yeah it's a possibility. It will be good to see that fixed.

**Comment by bsclifton** [comment]
Closing this issue as it's too vague and there aren't steps to reproduce

I think @jamesray1 captured a good way to find related issues, searching for "freeze".  Also, some known issues are captured in https://github.com/brave/browser-laptop/issues/9311

**Comment by jamesray1** [comment]
OK It does need to be fixed as it is hard to use the browser if it keeps happening. I don't have a lot of time to try to try to reproduce it but some options are try using a lot of RAM with several tabs with the resource monitor and note how much RAM is being used at the time of a freeze.

**Comment by jamesray1** [comment]
I updated today and now not all tabs are freezing, only some. If I think of any way that might or does reproduce it I will let you know. At the moment I have 12 tabs open and just one window. 3 tabs don't open or close (two are Google spreadsheets and one is on a Zoho forum). Hover over them and it shows a grey page. 

![2017-12-04 10_27_35-settings](https://user-images.githubusercontent.com/16969914/33531204-d95e2cc4-d8dd-11e7-9ba7-ca1bec8e9844.png)

![2017-12-04 10_33_58-](https://user-images.githubusercontent.com/16969914/33531273-b15dde30-d8de-11e7-853f-88c6e3fb61d3.png)

I will try using less tabs and see how often it occurs.
