### ISSUE TITLE
Ledger refactoring

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11009]
### Description

This is a tracking issue for ledger refactoring.

#### Phase I #11209
In this phase we will introduce state into the ledger. Everything should be handled with appState now and events should be transmitted via reducers.
**NOTE** This refactor will not have working add founds. This is because we will do complete rewrite of this dialog in next phases

**QA first pass:**
https://github.com/brave/browser-laptop/issues/11214
https://github.com/brave/browser-laptop/issues/11217

MacOS: https://github.com/brave/browser-laptop/pull/11037#issuecomment-333235964
Windows: https://github.com/brave/browser-laptop/pull/11037#issuecomment-333236594

#### Phase || #10945
In this phase we will add support for bat libraries. We will also remove all add found related code that will not be used anymore.

#### Phase ||| #11193
In this phase we will add add found wizard back to the ledger. After this phase ledger should be fully functional again.

#### Phase IV #11210
In the last phase we will do some cleanup and optimisations that were wound while refactoring. We will also add remanning  tests so that coverage will be as good as possible.

**Comment by bsclifton** [comment]
Closing this issue- we've got everything merged and the rest of the work is captured in https://github.com/brave/browser-laptop/issues/11210, which is in 0.19.x release 2
