### ISSUE TITLE
Add a search bar in preferences

### ISSUE THREAD

**Issue by DeviatedMind** [brave/browser-laptop#11003]
For searching all the preferences add a search bar
Thanks

**Comment by bsclifton** [comment]
Thanks for the suggestion 😄  We're tracking that with https://github.com/brave/browser-laptop/issues/7150, so I'll close this issue as a duplicate

**Comment by Ornataweaver** [comment]
Can you please update my username in your comment on 7150?
I didn't use # 7150 so this wouldn't crowd that.

**Comment by Ornataweaver** [comment]
@bsclifton 
Thank you very much for thanking me.
It inspire me a lot.
I'm working on #IDEAsPlatform, a viable version of it is called #UserStoryHub. Your feedback makes me believe the time for the #IDEAsPlatform is getting closer.
