### ISSUE TITLE
[hackerone] homepage homograph attack

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11001]
## Test plan

https://github.com/brave/browser-laptop/pull/11006#issue-258702443

----

from https://hackerone.com/bugs?report_id=268984&subject=brave:
```
Steps To Reproduce:

In browser add homepage with IDN @ebаy.com/ or just ebаy.com/
now close and open browser again
click the homepage button. you can see it's redirect to http://xn--eby-7cd.com/
```

expected result: in the 'home button' field in about:preferences, it should show '@xn--eby-7cd.com/' instead of '@ebаy.com/'

video https://www.youtube.com/watch?v=UgN-XJew9Es&feature=youtu.be

**Comment by diracdeltas** [comment]
Actually this works even if you don't prefix the URL with '@'. Updating issue accordingly.

**Comment by bbondy** [comment]
master: f2e438d6158fbc62e2641458b6002a72d223c366
0.20.x: 905d6c9a6f5c783671c30f206dca7fed3ac112e6
0.19.x: a7060a1f4c1c967266f97f087e3a827efddac03e
