### ISSUE TITLE
Running BraveSetup.exe on windows leaves behind 2 processes

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1100]
I think we've had this forever but if you run BaveSetup.exe and then close the browser you'll still have 2 processes left behind that you have to later kill.

Normal app startup / shutdown works as expected and closes the processes.

**Comment by weems** [comment]
maybe I pre-empted you but this is what I meant in the following https://github.com/brave/browser-laptop/issues/1097

**Comment by bbondy** [comment]
This is actually invalid now.
