### ISSUE TITLE
make password manager page

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1101]
there needs to be somewhere in about:preferences to see which passwords have been saved and edit/delete them. https://github.com/brave/browser-laptop/pull/1051

**Comment by bbondy** [comment]
Is this going to make 0.8.2 or shoudl we move to 0.8.3? I'd rather have the bugfixes if it's one or the other.

**Comment by diracdeltas** [comment]
bugfixes first, then this

**Comment by diracdeltas** [comment]
moving to 0.8.3 for now.
