### ISSUE TITLE
JS Prompt does not display on screen

### ISSUE THREAD

**Issue by peterkroon** [brave/browser-laptop#11010]
### Description
JS prompt dialog does not display on screen

### Steps to Reproduce
  1. Go to: https://www.w3schools.com/js/tryit.asp?filename=tryjs_prompt
  2. Click on button "Try it!"

**Actual result:**
Prompt dialog is not visible and action is logged as cancelled by user.

**Expected result:**
Prompt dialog displayed on screen and ready for interaction

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

Brave | 0.18.36
-- | --
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Comment by bsclifton** [comment]
Thanks for the report, @peterkroon!  We have this captured with https://github.com/brave/browser-laptop/issues/94, so I'm going to close this issue as a duplicate
