### ISSUE TITLE
PDF Presentation Mode banner lists Chrome Extension

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11020]
### Description
When you have a PDF open and select the 'Switch to Presentation Mode' button, the notification banner displays 'Allow chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb to use fullscreen mode?'. This is confusing, I as expecting it to say something like 'PDF Viewer' instead of 'chrome-extension...'.

### Steps to Reproduce

  1. Open a PDF/Navigate to a PDF.
  2. Click on the 'Switch to Presentation Mode' button.
  3. Banner displays.

**Actual result:**
![screen shot 2017-09-19 at 3 47 13 pm](https://user-images.githubusercontent.com/28145373/30615957-a1d6b29a-9d5e-11e7-9bb4-72367b851493.png)

**Expected result:**
Banner should still display, but say something like 'PDF Viewer' instead of 'chrome-extension...'

**Reproduces how often:** 
every time.

### Brave Version
Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22

**Comment by diracdeltas** [comment]
should probably wait til https://github.com/brave/browser-laptop/pull/10896 is merged before fixing this since it will cause merge conflicts
