### ISSUE TITLE
Downloads Tab on the Windows Version

### ISSUE THREAD

**Issue by carecollabo** [brave/browser-laptop#1102]
I cannot find the Downloads Tab/Page just to view my downloads. If it is really there on the Windows OS version then i think maybe you ought to make it a lot more visible to see. I JUST CAN'T FIND IT

**Comment by bradleyrichter** [comment]
more info on the downloads bar which is entering development...
#1076

**Comment by bbondy** [comment]
Also there is this:
https://github.com/brave/browser-laptop/issues/533

I'm going to close this task in favour of those 2.

**Comment by carecollabo** [comment]
Thanks
