### ISSUE TITLE
HTTPSe, domain: larryreznick.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#11022]
### Description
Reported from community.brave.com: https://community.brave.com/t/no-https-upgrade-on-insecure-sight-s-how-come/7897/6

The larryreznick.com domain has an SSL cert, and can be manually overridden to upgrade the connection to https, but HTTPSe is loading the insecure connection by default. 

I've been able to repro in Windows. 

### Steps to Reproduce

  1. Go to larryreznick.com w/httpse enabled
  2. Note http:// connection
  3. Override by hard coding https:// in the url. 
  4. https connection loads for the domain 
**Actual result:**

http:// connection loads by default, w/HTTPSe enabled. 

**Expected result:**
https connection should load. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 
### Brave Version

https://github.com/brave/browser-laptop/commit/7ab85e97318fef041433b0c3d73b457205fae805
### Additional Information

@diracdeltas as an FYI - I've taken a look at the source code and it appears to be a wordpress-hosted domain, with mixed http:// https:// and protocol relative urls for page resources. Not sure if it is related, but the urls I'm referring to are in the head section of the page source.

**Comment by diracdeltas** [comment]
HTTPS Everywhere does not upgrade every HTTP connection to HTTPS, only when there is an applicable rule for it. We do not maintain the rulesets ourselves so this needs to be filed with https://github.com/efforg/https-everywhere.

**Comment by bsclifton** [comment]
@lukemulks @diracdeltas we may need to update our rules- looking at Jenkins, the last time we ran https://github.com/brave/https-everywhere-builder/ and pushed to prod was July 25th

**Comment by diracdeltas** [comment]
closing this as it should be an upstream issue, and the ruleset update issue is covered by #11598
