### ISSUE TITLE
Add notification after Brave app update for BAT Mercury

### ISSUE THREAD

**Issue by davidtemkin** [brave/browser-laptop#11021]
For BAT Mercury, show a notification after update/relaunch, under the following circumstances:

* That the user has enabled payments
* That the user's (bitcoin) balance isn't zero

When these circumstances are true, Brave should show a notification banner saying "Your Brave wallet has been updated" [OK] [Learn More] -- Exact copy is TBD

The "OK" button should dismiss the notification.

The "Learn more" button should take the user to a page, content TBD, that explains the fact that the user's bitcoin has been converted to BAT.

**Comment by mrose17** [comment]
just to be clear: the goal is to have a update/relaunch notification facility, which can, among other things be triggered on this event.

**Comment by bsclifton** [comment]
Notification to look like this:
![image](https://user-images.githubusercontent.com/4733304/31104954-585682e4-a795-11e7-89b8-074ad0bca887.png)

**Comment by bsclifton** [comment]
This is basically a newer version of https://github.com/brave/browser-laptop/issues/4847 (which was never done because there isn't a way to deep link to the backup modal)

**Comment by srirambv** [comment]
This should be shown when wallet is converted immediately after upgrade or after wallet is created. But only shows after the browser is restarted a second time after everything is done.

@bsclifton @NejcZdovc @mrose17

**Comment by NejcZdovc** [comment]
this one is tracked here https://github.com/brave/browser-laptop/issues/11333
