### ISSUE TITLE
Match case toggle doesn't perform search always

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11039]
### Description
Match case toggle doesn't perform search 

### Steps to Reproduce

  1. Visit https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
  2. Enter `Geo` as search term, verify search count
  3. Toggle Match case, verify search count shows correct for both match and unmatch case
  4. Visit https://browserleaks.com/geo
  5. Search for `geo`, verify search count
  6. Toggle match case, doesnt show the correct total count

**Actual result:**
![search](https://user-images.githubusercontent.com/17010094/30640304-08f312ae-9e20-11e7-99fe-f690f0f24712.gif)

**Expected result:**
Should show correct count irrespective of match case toggle

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

Brave | 0.19.7
-- | --
rev | c8481a9
Muon | 4.4.16

### Additional Information

This is same behaviour on Vivaldi as well.

**Comment by luixxiul** [comment]
@srirambv what do you ask with this issue? I'm wondering because you added `question` label.

**Comment by srirambv** [comment]
Weather it will be something we can fix or won't fix

**Comment by bsclifton** [comment]
Removed question label- we should definitely fix 😄  I verified it happens on macOS also
