### ISSUE TITLE
Provide a lot more search engines for default search engine preference

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1103]
We can get the list from Chrome's settings:
<img width="705" alt="screenshot 2016-03-17 10 23 03" src="https://cloud.githubusercontent.com/assets/831718/13848926/4c372ac2-ec2a-11e5-91cd-913df640f692.png">

Also we can support a simpler format than having to parse the open search xml formats. We should leave support for open search xml too though.
#790

**Comment by thepup** [comment]
Just looked through __all__ the supoort tickets that mentioned search engines, and here are the one's that were requested:

1. startpage.com
2. bing.com
3. ecosia.org
4. qwant.com
5. yahoo.com
6. wikipedia.org

I'll add any new ones that come up periodically.

**Comment by bsclifton** [comment]
Besides having support for a good number of search engines, we should allow the user to edit or delete the existing search engines

**Comment by bsclifton** [comment]
Tentatively assigned this to 1.1.0 milestone after seeing comment in https://github.com/brave/browser-laptop/issues/3053

cc: @bradleyrichter

**Comment by Aeyoun** [comment]
See my [comment here](https://github.com/brave/browser-laptop/issues/3053#issuecomment-244539801) for a method for automatically adding the user's favorite search engines. I think that approach is better than bundling 100 search engines by default.

**Comment by luixxiul** [comment]
I think this can be closed because the requests for adding search engines have been made in other tickets, and this seems to track nothing specific.

**Comment by bsclifton** [comment]
@luixxiul I agree- as long as the other items are labelled with `feature/search`, we should be good to go :smile: The user-editable one (which includes the suggestion by @da2x) can be found here:
https://github.com/brave/browser-laptop/issues/3053
