### ISSUE TITLE
Drag padlock to add bookmark doesn't show bookmarked icon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11033]
### Description
Drag padlock to add bookmark doesn't show bookmarked icon

### Steps to Reproduce
  1. Clean install 0.19.7
  2. Visit any site, enable bookmark toolbar
  3. Drag padlock to add as bookmark, bookmark shown on toolbar but doesnt show the bookmarked orange star

**Actual result:**
![addbmk](https://user-images.githubusercontent.com/17010094/30635342-bf5160d4-9e0f-11e7-99ad-62dfb420f04a.gif)

**Expected result:**
Should add bookmark and show the bookmarked icon

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% regression
### Brave Version

Brave | 0.19.7
-- | --
rev | c8481a9
Muon | 4.4.16

### Additional Information

Visiting the site in a new tab shows the bookmarked icon on both the tabs 
#9753

**Comment by bbondy** [comment]
0.19.x: aae724b28d5548ababd634c169aab83d2da9e3a9
0.20.x: 1bf4cbaffc7991b188cd1542eff58f8427b838f2
master: 29e0d3441724c2be5430d2c9f6ebbfad386577ed (was mostly fixed there, so this is just a subset of the above 2)
