### ISSUE TITLE
URL Text is way low compared to URL elements

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11032]
### Description
URL Test is way low compared to URL elements

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/30634702-94474d24-9e0d-11e7-92b2-bc0796089806.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/30634711-9b023156-9e0d-11e7-8966-795dec9a5832.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
Yes
### Brave Version

Name | Version
-- | --
Brave | 0.19.7
rev | c8481a9
Muon | 4.4.16

### Additional Information

#5624,#6505
cc: @luixxiul @bradleyrichter

**Comment by luixxiul** [comment]
is this reproducible only on Windows?

**Comment by srirambv** [comment]
This is on Ubuntu VM 
![image](https://user-images.githubusercontent.com/17010094/30636808-17d7cdfc-9e14-11e7-933f-a1bd95d10231.png)

**Comment by luixxiul** [comment]
@srirambv is it also a regression?

**Comment by luixxiul** [comment]
also please try with tall alphabets like `h` ie `https://github.com` and see if it is still really low and not high unnaturally.

**Comment by srirambv** [comment]
Looks much better on the latest build
![image](https://user-images.githubusercontent.com/17010094/30959430-c125c25c-a45d-11e7-86ee-2d7cda78115d.png)

**Comment by srirambv** [comment]
This is how visiting google.com looks on 0.19.20
![image](https://user-images.githubusercontent.com/17010094/30959656-7c5ab848-a45e-11e7-9f77-d26f310c263b.png)
