### ISSUE TITLE
Impossible to add bookmark with dnd of padlock if toolbar is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11034]
### Description
Impossible to add bookmark with dnd of padlock if toolbar is disabled

### Steps to Reproduce

  1. Disable bookmark toolbar
  2. Right click right above the tabs where the bookmark toolbar context menu is shown
  3. Drag and drop the padlock where the bookmark toolbar context menu was shown, doesnt dd the page as bookmark, 

**Actual result:**

![addbmk1](https://user-images.githubusercontent.com/17010094/30635702-dab1ac34-9e10-11e7-810e-1c431c13f4af.gif)

**Expected result:**
Should add bookmark and enable bookmark toolbar 
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version
 All

### Additional Information

Existing behaviour

#11033

**Comment by luixxiul** [comment]
@bbondy does your commit https://github.com/brave/browser-laptop/commit/29e0d3441724c2be5430d2c9f6ebbfad386577ed fix this one too?

**Comment by bbondy** [comment]
I don't think so, the drop handler is on the bookmarks toolbar and if it is disabled then there is no bookmarks toolbar.

**Comment by luixxiul** [comment]
@srirambv do you see the issue on the latest 0.20.x build?

**Comment by srirambv** [comment]
Happens on 0.20.6 as well
![11034](https://user-images.githubusercontent.com/17010094/32494376-5f3db434-c3b9-11e7-93c7-d3679d56fc00.gif)

**Comment by kjozwiak** [comment]
Still reproducible using `0.21.12` 246f9008be47dbdcc6dc9ded5690a847eee8a4e0 under Win 10 x64.

**Comment by rebron** [comment]
Closing. Marking wontfix here but fixed in brave-core..
