### ISSUE TITLE
Bookmark and Bookmark folder cannot be dragged and dropped into another folder on the bookmark toolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11040]
### Description

Bookmark folder cannot be moved into another folder on the bookmark toolbar.

### Steps to Reproduce

  1. Display the bookmark toolbar
  2. Create two empty bookmark folders
  3. Drag the one and drop onto the other

**Actual result:** The bookmark folder is not moved.

![bug](https://user-images.githubusercontent.com/3362943/30643111-9c9e6ce2-9e48-11e7-8649-91a935a088c4.gif)

**Expected result:** It should be moved.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Brave Version

Brave: 0.19.7 
rev: c8481a9ecae07ddf816aea0c8d7a38b744c2b42d 
Muon: 4.4.16 
libchromiumcontent: 61.0.3163.71 
V8: 6.1.534.31 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

 The issue cannot be reproduced on the latest 0.18.

### Additional Information

Found during QA on #9712. Also the bookmark folders can be drag and dropped each other on the bookmarks manager.

#11033 #11034

**Comment by LaurenWags** [comment]
I'm also unable to drag/drop a bookmark on the toolbar to a folder on the toolbar:
![bookmarktoolbardnd](https://user-images.githubusercontent.com/28145373/30648909-2c57ff26-9ded-11e7-86f3-045fb234d3ac.gif)

**Comment by NejcZdovc** [comment]
@LaurenWags you need to drop it on empty item

**Comment by NejcZdovc** [comment]
more info here #5193

**Comment by LaurenWags** [comment]
@NejcZdovc i'm not dragging and dropping tabs though, i'm drag/drop bookmarks on the toolbar to a folder on the toolbar. this works in 0.18.36: 
![bkmktoolbar01836](https://user-images.githubusercontent.com/28145373/30649738-14cbccaa-9def-11e7-9fc7-4e023c3c857b.gif)

**Comment by NejcZdovc** [comment]
I didn't know that this is working :D

**Comment by LaurenWags** [comment]
it was before, is not now :(

**Comment by bbondy** [comment]
0.19.x: 5ca3af8aae38a74fd74d3a16fb5f5f35231ba53c
0.20.x: c53fc240cf55bf12a8e433e05df0b0d9cc62d90a
master: 0c0524cda459f3171222ac7ccc713c0aefcc7cd6 (This one also includes an unrelated fix on master for drag and drop not updating the bookmarks toolbar)
