### ISSUE TITLE
Brave pre-release testing updates without BRAVE_UPDATE_HOST on Windows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1104]

**Comment by bbondy** [comment]
Moving this to 0.9 so focus can be on localization

**Comment by bbondy** [comment]
Moved to 0.9.3.

**Comment by luixxiul** [comment]
How is it now?

**Comment by aekeus** [comment]
We have solidified our release procedures. Not sure if this need anymore? cc @bbondy

**Comment by bbondy** [comment]
I'd need to try on next release if I can get an update when things are staged without setting BRAVE_UPDATE_HOST

**Comment by zentagonist** [comment]
@bbondy Please close if possible.

**Comment by bbondy** [comment]
I don't think this is a problem anymore.
