### ISSUE TITLE
Pinned tabs lost after moving from Release to Beta channel

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#11049]
All pinned tabs from a Release channel session were lost after moving to the Beta channel release

  1. In a Release channel browser add a series of pinned tabs
  2. Install the latest Beta release
  3. Open the browser and confirm that pinned tabs are lost

**Comment by bbondy** [comment]
I think this might be an intermittent problem that was happened to happen, but was not introduced in this release.

**Comment by bsclifton** [comment]
I've hopped between channels and haven't had this happen... I did have my bookmarks get re-ordered in a weird way though

**Comment by aekeus** [comment]
I wonder if it is a sessions tab issue. @LaurenWags asked me about that when it happened. I thought that none of the pinned tabs were session tabs at the time but now I am not so sure. I will test this out bit to see if I can re-produce.

**Comment by bbondy** [comment]
I'll remove from milestone but if anyone reproduces again then let's move it back in.

**Comment by LaurenWags** [comment]
@aekeus I tried some pinned session tabs, but was unable to repro.

**Comment by bsclifton** [comment]
Something good to test once we introduce a Beta channel on [brave-core](https://github.com/brave/brave-browser)
