### ISSUE TITLE
Top Site Tiles disappear after clicking on them

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11043]
### Description
With a clean profile on 0.19.7, if you click on one of the top site tiles, after 5 seconds it is removed from the Dashboard.

### Steps to Reproduce

  1. Clean install of 0.19.7
  2. Open up a new tab, click on one of the top site tiles. 
  3. Site is loaded in the tab.
  4. Open a new tab. 
  5. If it took you less than 5s to open the new tab, your tile will be displayed and then it will disappear from view. If you took more than 5s to open the new tab, the tile will not be there at all.

**Actual result:**
![topsitetiles](https://user-images.githubusercontent.com/28145373/30646465-16781570-9de7-11e7-82fe-45683e1ad8f9.gif)

**Expected result:**
Top site tile should not disappear after it is used.

**Reproduces how often:** 100%

### Brave Version
Brave | 0.19.7
rev | c8481a9
Muon | 4.4.16

**Comment by LaurenWags** [comment]
this issue is not reproducible in 0.18.36: 
![topsitetiles01836](https://user-images.githubusercontent.com/28145373/30649381-2187079e-9dee-11e7-904e-c9a8934e649d.gif)

**Comment by bbondy** [comment]
@LaurenWags is this still reproducible with 0.19.12 or later? I can't reproduce.  It does change the icon with a similar affect but it doesn't remove the tile.

**Comment by srirambv** [comment]
It is still reproduced on 0.19.13
![11043](https://user-images.githubusercontent.com/17010094/30742411-850fcc96-9fb6-11e7-9a0e-78d57a187e9f.gif)

**Comment by LaurenWags** [comment]
@bbondy I am still reproducing in 0.19.13 but only if you click on those tiles with a clean profile:
![11043](https://user-images.githubusercontent.com/28145373/30746644-6f13e35c-9f78-11e7-8b53-91308ca99023.gif)


If I have a profile that I've been using for a bit (like the profile I used for testing yesterday), clicking on the tiles does not make them disappear:
![11043-existingprofile](https://user-images.githubusercontent.com/28145373/30746829-28407afc-9f79-11e7-8d36-f24b201c666c.gif)

**Comment by bbondy** [comment]
Thanks for the confirmations.

I can reproduce on the release profile no problem.
I cannot reproduce on my dev profile with the same changeset.

Strange

**Comment by bbondy** [comment]
By profile above I meant config actually. Both are fresh profiles.  Production builds cause the problem, development builds do not.

**Comment by bbondy** [comment]
Even stranger I reproduce when I build a production build locally with a fresh profile.

**Comment by bbondy** [comment]
Fixed:

0.19.x: 82d2eacbd57b15a1394bb0b4c771108c557c7917
0.20.x: 12f516da86186b453198924a353ecfefe096bc86
Fix does not apply to 0.21.x, but 0.21.x (currently master) has other issues which I posted for

**Comment by bsclifton** [comment]
@bbondy looks like you got bit by the wonderful Cmd + C bug 😄 
0.19.x hash is https://github.com/brave/browser-laptop/commit/455742d45de2897fa1b2cdcd31c182cbb44bcc30
