### ISSUE TITLE
Autoplay notification bar not shown when set to "always ask"

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11042]
### Steps to Reproduce

  1. Set auto media play to always ask
  2. Visit https://vimeo.com/215927968
  3. Click play, No notification bar for auto play is shown, media starts play.

**Actual result:**

Notification bars not shown

**Expected result:**
Should show notification bar for auto play media 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

Brave | 0.19.7
-- | --
rev | c8481a9
Muon | 4.4.16

### Additional Information

#11036 
@LaurenWags  to confirm for macOS

**Comment by luixxiul** [comment]
You'll need to visit vimeo.com at first to display the notification bar, though I'm not sure that is intentional.

**Comment by LaurenWags** [comment]
Reproduced on MacOS.

**Comment by bbondy** [comment]
I think it's just because this wasn't in the build, please do per OS testing on the next build:
https://github.com/brave/browser-laptop/issues/10864

**Comment by LaurenWags** [comment]
still seeing issue as described, requested @kjozwiak to check.

**Comment by LaurenWags** [comment]
still see this issue on 0.19.23

**Comment by srirambv** [comment]
Works fine on Windows 
![autoplay](https://user-images.githubusercontent.com/17010094/30971230-f612f62a-a484-11e7-80fb-643da600db73.gif)

**Comment by bsclifton** [comment]
Works for me as expected...

@LaurenWags, in your screenshot you're clicking play (which would override the video setting).  Do you have an exception in place for vimeo.com? If not, does the autoplay alert show if you force a reload with Cmd + R?

**Comment by LaurenWags** [comment]
@bsclifton I do not have an exception in place for vimeo.com. Here's a quick gif of what I did and I included the cmd+R - still no notification. I clicked play at the end.

I will note, that if i just visit vimeo.com, I do get the notification asking 'Allow https://vimeo.com to autoplay media?', but not on the video specified in the issue.

![11042-cmt](https://user-images.githubusercontent.com/28145373/31099726-f77f8e70-a794-11e7-8759-516bf45291cf.gif)

**Comment by bsclifton** [comment]
@LaurenWags I can repro now- for some reason, my profile had shields down on vimeo.com.  When I enabled them again, I no longer get the notification

**Comment by bsclifton** [comment]
This may be related: https://github.com/brave/browser-laptop/issues/11069

Because this feature appears to be related to shields, I'm going to remove the `release-blocking` tag and also the milestone from this issue

**Comment by darkdh** [comment]
Vemeo will not autoplay if you directly navigate to it through url. (you can try other browsers as parity check)
It will only autoplay from search result (ex. google search)
So in this case, user initiated playing video doesn't count as autoplay
