### ISSUE TITLE
URL suggestions for simple domain names sometimes don't appear up top

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11057]
### Description
Sometimes typing a site like twitter.com will result in a first suggestion of a longer URL instead of just matching to twitter.com

### Steps to Reproduce
Pre-req you must have URLs that are frequently visited with a high count  

  1. Type `twi`

**Actual result:**

Matches to twitter.com/i/notifications

**Expected result:**

Matches to twitter.com

### Brave Version

**about:brave info:**

0.18.36

**Reproducible on current live release:**
Yes

### Additional Information

This was introduced when we switched URL parsing libraries because now parsed URL attributes are not null but instead an empty string.

**Comment by bbondy** [comment]
0.19.x: db2d286c0fa1bcd35d0b196742e855a6a8be00cc
0.20.x: 720f97df472ae1ff025f8daab23adf123f6837fb
master: db2d286c0fa1bcd35d0b196742e855a6a8be00cc

**Comment by bbondy** [comment]
cc @bsclifton forgot to mark auditor please check out https://github.com/brave/browser-laptop/commit/db2d286c0fa1bcd35d0b196742e855a6a8be00cc

**Comment by bsclifton** [comment]
++

**Comment by LaurenWags** [comment]
@bbondy asked a user who was also experiencing this issue ( @tbates) to check this out and he provided some feedback here: https://github.com/brave/browser-laptop/issues/6537#issuecomment-331641529. Wondering if you could review? I'm thinking they might need to be logged separately instead of trying to resolve with this issue.

**Comment by bbondy** [comment]
@LaurenWags I don't think those are related to this.  You'll have to please create new issues, 1 for each individual thing and then actual results vs expected results. Easiest with a fresh profile so that the use case can be reproduced.
