### ISSUE TITLE
Netflix/Widevine notification banner does not go away

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11054]
### Description
When you navigate to netflix.com (using a clean profile) in 0.19.9, you are prompted to install widevine. Once you accept this and try to login, you get a notification at the top of the login screen for remember this decision allow/deny. Clicking any of the buttons or checkboxes on this notification banner does not cause it to go away. Additionally, in 0.18.36 there was an entry in about:preferences#security under Site Settings for netflix/widevine that is not there in 0.19.9.

### Steps to Reproduce

  1. Open 0.19.9 in a clean profile.
  2. Navigate to netflix.com and accept the widevine install.
  3. Go to about:preferences#security and look at Site Settings. An entry was not added for Netflix/Widevine. (there was one added at this point in 0.18.36)
  4. Go back to netflix.com and click the login button.
  5. On the notification banner (which did not exist in 0.18.36), Remember this Decision, Deny, and Allow don't seem to work. Clicking on them doesn't do anything and the banner does not go away.

**Actual result:**
![0199widevine](https://user-images.githubusercontent.com/28145373/30664671-854febaa-9e1c-11e7-92f2-3d9da0b6107a.gif)

**Expected result:**
This is what happened in 0.18.36:
![01836widevine](https://user-images.githubusercontent.com/28145373/30664686-8dfc2e08-9e1c-11e7-9db7-48392ecf34ca.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.9
rev | 2a9a56f
Muon | 4.4.19

**Reproducible on current live release:**
No

**Comment by srirambv** [comment]
Confirmed on Windows too.

**Comment by bbondy** [comment]
0.19.x: f697e053d0b87982c379413738e42ac0bffeef27
0.20.x: a2c4124e94c86b2db3d9a3c82b5aec9e8fb91da5
master: 799e0f51a5b547343715bc3b6cde90cda5ddced1
