### ISSUE TITLE
Session tab border is hidden when an inactive tab is loading

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11058]
### Description

Session tab border is hidden when an inactive tab is loading

### Steps to Reproduce

  1. Have a few tabs loaded with pages ans have an empty session tab at the end
  2. Close and reopen the browser
  3. Hover over the unloaded tabs to load, session tab right border disappears while the page is loading on other tabs

**Actual result:**
![sessiontab](https://user-images.githubusercontent.com/17010094/30677919-549c54d6-9eac-11e7-983b-74f58b32b7ae.gif)

**Expected result:**
Should show tab border all the time 
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.9
-- | --
rev | 2a9a56f
Muon | 4.4.19

**Reproducible on current live release:**
Yes

### Additional Information

cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
thanks I think it will be fixed in 0.20.x but assigning to keep track
