### ISSUE TITLE
Double click on tab bar should spawn a new tab

### ISSUE THREAD

**Issue by eduardonunesp** [brave/browser-laptop#11068]
Description

I would like to spawn a new tab on double click on tab bar, instead of click on the `+` sign, I know that plus sign has more options, but the default option can be used when the user double clicks on tab bar.

Steps to Reproduce

Open Brave and double click on tab bar

Actual result:
None

Expected result:
Spawn a new tab bar open a blank bar using default config for new tabs

Brave Version

Brave | 0.18.36

**Comment by bsclifton** [comment]
@edouard-lopez this is an interesting feature request- are there other browsers which do that?

**Comment by edouard-lopez** [comment]
@bsclifton I think you mis-mention me, but there is addons that do the opposite, _i.e._ double-click close a tab

* Chrome [Double Click Closes Tab](https://chrome.google.com/webstore/detail/double-click-closes-tab/megplcpdkmjjoondippkedoaidkeikcm?hl=en)
* Firefox [Double Click Closes Tab](https://addons.mozilla.org/en-US/firefox/addon/double-click-closes-tab/)

**Comment by srirambv** [comment]
Middle click close tab, is an out-of-the-box functionality

**Comment by bsclifton** [comment]
@edouard-lopez apologies! I totally did (autocomplete mistake on my part)- I had meant to tag @eduardonunesp

**Comment by eduardonunesp** [comment]
@bsclifton I think not today in the modern browser, I think it was something that I miss. The browsers today have a plus button or something to add the new tab, and Brave has a tab bar with a plus button and a wide open space, maybe add this double click creates a new tab will give a better use to that unused space
