### ISSUE TITLE
Prompt user to close Chrome when trying to Import Browser Data

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11067]
### Description
When importing Browser Data from Chrome, if Chrome is open not all data will import correctly. Chrome needs to be closed in order for this to happen. User should be prompted to close Chrome the same way they are prompted to close Firefox.

### Steps to Reproduce
  1. Open Chrome.
  2. Open Brave and go to Import Browser Data.
  3. Select Chrome, leave all toggles on. 
  4. Import Browser Data.

**Actual result:**
Not all data is imported.

**Expected result:**
User should be prompted to close Chrome prior to importing Browser Data.

**Reproduces how often:**  100%

### Brave Version
Brave | 0.19.11
rev | 3252249
Muon | 4.4.19

**Reproducible on current live release:**
Yes

**Comment by bbondy** [comment]
Since it has always worked this way moving this down to 0.21.x
