### ISSUE TITLE
DuckDuckGo scroll position not restored after pressing back button

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1106]
See after clicking the search result, then back, the scroll position is not restored, I was on the 2nd page of results
![ddg-back](https://cloud.githubusercontent.com/assets/5495083/13854184/9f32e89a-ec40-11e5-8261-0e838c17e1df.gif)

**Comment by garvankeeley** [comment]
On the links in 'Bravery settings'  in this issue https://github.com/brave/browser-laptop/issues/1537
After clicking them, then back, the scroll position is not restored.

**Comment by bsclifton** [comment]
This specific issue seems to have been fixed... but I know the behavior does exist on some other sites. I'd like to close this in favor of https://github.com/brave/browser-laptop/issues/1766
