### ISSUE TITLE
replace moment with date-fns for date helpers

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#11061]
## Test plan

https://github.com/brave/browser-laptop/pull/11062#issue-259406143

----

Initially, the plan was to reduce bundle cost given `moment` is enourmous. However after reading [this](https://medium.com/node-security/pull-requests-welcome-we-need-your-help-to-fix-some-redos-vulnerabilities-da9fc74b4fd5) and looking at [this](https://github.com/moment/moment/issues/4163) this killed two birds with one stone.

**Comment by cezaraugusto** [comment]
**EDIT:** Turns out that `Joi` has it as a dependency so if this is not a security issue please ignore/remove the label

**Comment by cezaraugusto** [comment]
**EDIT:** Turns out that `Joi` has it as a dependency so I don't think we can remove it completely. Based on that if this is still a security problem but unsolvable ATM please let me know

**Comment by diracdeltas** [comment]
@cezaraugusto it looks like joi is only used in tools/transactionHelpers.js which is not a package dependency, only a dev dependency (unless i'm mistaken)

**Comment by diracdeltas** [comment]
actually joi is used in the ledger packages, but it looks like Joi no longer uses moment: https://github.com/hapijs/joi/issues/1037

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87

**Comment by LaurenWags** [comment]
QA Blocked on #14407

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
