### ISSUE TITLE
Remove custom classes from switchControl.js

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11065]
## Test plan

https://github.com/brave/browser-laptop/pull/11954#issue-273803005

----

### Description

Remove custom classes from switchControl.js by creating components to avoid visual fragmentation.

### Additional Information

See #10482 

Related: #7321

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
