### ISSUE TITLE
Crash resets prefs to default, deletes all bookmarks

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1107]
While using a mouse to highlight text, the entire page went black except for the space with the minimize, maximize,& close buttons. The page was not recoverable, so I used the close button to stop the browser. When I restarted the browser all bookmarks were deleted and preferences reset to default.

**Comment by bbondy** [comment]
Were you using 0.8.1?  We save periodically starting with 0.8.1.

**Comment by cfumante** [comment]
No, I just loaded 8.1 last night. However, the problem seems to have
occurred due to a crash, deleting all the bookmark & preference info
which had been previously saved since it was present on the startup
before the crash. This seems to indicate that even if the info has been
saved, a crash can corrupt/delete it.
 
I've reloaded bookmarks/prefs and will try the same activity that caused
the previous crash and see what results.
 
mahalo,

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by cfumante** [comment]
Update:
 
Looks like the problem is resolved with 8.1. 
 
 I induced the "black screen" crash 5 times and the bookmarks and prefs
were restored on startup each time. 
 
 
FYI__ I cause the crash by:
 
    -  highlighting text from an open page
    -  grabbing it with a left click
    -  moving the text to a different location on the page, and
    -  right-clicking
 
Note that this is irregular - it doesn't always work and seems to be
streaky in that it will happen a number of times in a row or it will
fail to occur at all. It may be some cumulative hiccup caused by the
unconventional activity.
 
mahalo,
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
From: Carl Fumante [mailto:cf@hawaii.rr.com] 
Sent: Friday, March 18, 2016 7:21 AM
To: 'brave/browser-laptop'
Subject: RE: [browser-laptop] Crash resets prefs to default, deletes all
bookmarks (#1107)


No, I just loaded 8.1 last night. However, the problem seems to have
occurred due to a crash, deleting all the bookmark & preference info
which had been previously saved since it was present on the startup
before the crash. This seems to indicate that even if the info has been
saved, a crash can corrupt/delete it.
 
I've reloaded bookmarks/prefs and will try the same activity that caused
the previous crash and see what results.
 
mahalo,

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by luixxiul** [comment]
Closing for now. If this error appears again please leave a comment to reopen the issue thanks.

**Comment by cfumante** [comment]
will do
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
