### ISSUE TITLE
Dragging a link from content onto the bookmarks bar no longer works

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11077]
### Description
Drag a link from a webpage onto the bookmarks toolbar. 
It used to create a bookmark, it doesn't anymore.

### Steps to Reproduce

  1. Go to slashdot.org, or any site
  2. Click and drag a link onto the bookmarks bar

**Actual result:**
It doesn't create a bookmark or show an indication that the drop is even allowed.

**Expected result:**
It shows an indication that the drop is allowed and it creates a bookmark.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% always

### Brave Version
0.18.36

**Reproducible on current live release:**
Yes, 0.18.36 is live.

**Comment by Liunkae** [comment]
This took a lot of time traveling. 😉 

It was working in 0.13.2, and it had stopped working in 0.13.3.

**Comment by BraveSauce** [comment]
Dragging links or images to the URL or Tabs bar doesn't work either.
