### ISSUE TITLE
unable to open Bitwarden vault in a tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11076]
### Description
When you have 'My Vault' opened in Bitwarden and you click on the icon in the upper left corner (it's a box with an arrow pointing out), this just opens a blank tab that never loads.

### Steps to Reproduce

  1. Enable Bitwarden as the password manager.
  2. Login to Bitwarden.
  3. Click on the icon and then select 'My Vault' at the bottom of the popup.
  4. Now click on the icon in the upper left corner next to the search box (the icon looks like this: 
![screen shot 2017-09-21 at 2 32 39 pm](https://user-images.githubusercontent.com/28145373/30712350-bfe1a840-9ed9-11e7-9b02-8c22fb24ade1.png)

**Actual result:**
Untitled tab is opened and it never loads, just keeps spinning.
![bitwarden](https://user-images.githubusercontent.com/28145373/30712449-1d035870-9eda-11e7-8687-78b5548a2b93.gif)

**Expected result:**
When you do this in Chrome, it opens the vault in a new tab.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version
Brave | 0.19.12
rev | 063f110
Muon | 4.4.19

**Reproducible on current live release:**
no

### Additional Information

cc: @jonathansampson

**Comment by jonathansampson** [comment]
The issue appears to be with a relative path being passed to `chrome.tabs.create`.

```js
$scope.expandVault = function (e) {
    $analytics.eventTrack('Expand Vault');
    chrome.tabs.create({ url: '/popup/index.html#!/tab/vault' });
};
```

If we create an absolute URL, the method succeeds:

```js
chrome.tabs.create({
    url: chrome.runtime.getURL('/popup/index.html#!/tab/vault')
});
```

**Comment by jonathansampson** [comment]
@bridiver It looks like we pass the URL as-is to the `webContents.createTab` method. Should the fix happen in the implementation of that method, or should we resolve the path to an absolute URL before pass it in? I'm fairly certain I can do the latter, but would need some guidance if we prefer to instead do the former.
