### ISSUE TITLE
site missing indication of audio (speaker icon on tab) and unable to mute tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11079]
### Description
When visiting http://alexwykoff.com/2/demo/ there is no indication on the tab (speaker icon) that the tab has audio. Additionally, you are unable to mute this tab.

### Steps to Reproduce

  1. Visit http://alexwykoff.com/2/demo/
  2. Look on the tab, no audio icon/speaker is displayed on tab.
  3. Tab plays audio, but no way to mute tab - right click on tab does not provide mute option.

**Actual result:**
No speaker icon is displayed on tab, no way to mute this tab.

**Expected result:**
Speaker icon should be displayed, right click on tab should have option to mute tab.

**Reproduces how often:** 100%

### Brave Version
Brave | 0.19.12
rev | 063f110
Muon | 4.4.19

**Reproducible on current live release:**
Yes. Checked on 0.18.36.

**Comment by bsclifton** [comment]
@LaurenWags did this ever work in Brave? When I visit the page, it's not always making sound (only makes sound when it's clicked)

If Audio isn't playing (without interaction), I'm not sure if a speaker icon should be shown?

**Comment by alexwykoff** [comment]
Confirmed this is a regression present in 0.19.70 (macOS) and happens for other domains as well : 
http://signalsandsorcery.com/

Audio is playing, no indicator present on tab control : 
<img width="369" alt="screen shot 2017-10-29 at 10 17 33 am" src="https://user-images.githubusercontent.com/1434040/32145222-d466b018-bc92-11e7-9348-7e48df89a7ff.png">

Audio is playing, tab switched : 
<img width="202" alt="screen shot 2017-10-29 at 10 18 07 am" src="https://user-images.githubusercontent.com/1434040/32145226-e8190a84-bc92-11e7-9d0d-1e8f4c10a159.png">

**Comment by bsclifton** [comment]
@alexwykoff what is the last version of Brave that this failed to work on?  I suspect the one-off sites mentioned are playing the audio in a different manner than most regular content (like YouTube, etc) and that it never worked
