### ISSUE TITLE
notification bar not appearing on mailto: link command+click

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11075]
found while testing https://github.com/brave/browser-laptop/issues/4198#issuecomment-331062347

STR:
1. make sure you have an external application set as your default mail handler
2. go to brave.com and cmd+click any of the mailto: links at the bottom to open in a new tab
3. the new tab does not show the notification bar (it seems to load forever) whereas previously it did

the notification bar does appear if you click on the mailto: link (instead of cmd+click) so this may not be an issue with the notification bar itself

**Comment by bbondy** [comment]
I don't think this is a bug.

We only ever prompted for this for external applications. 
If you have brave as your default handler it just goes to it, always has for us. 

<img width="1920" alt="screen shot 2017-09-21 at 8 32 28 pm" src="https://user-images.githubusercontent.com/831718/30724525-551ccf84-9f0c-11e7-9f40-b6b113085b35.png">

**Comment by bbondy** [comment]
Verified the default handler link is also present.  I'm going to remove this from the milestone, but I think it should be closed. But let me know if I'm not understanding what the regression is and if it should go back in.

**Comment by bbondy** [comment]
Removing from milestone since this is only with command+click and I think it's a subset of an existing bug with command+click (for safe browsing was it?) anyway let me know if that's a  problem.
