### ISSUE TITLE
Copying and bookmarking bookmarklets with right-click does not work

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#11088]
### Description
Right clicking on a bookmarklet link and choosing either 'Copy Link Address' or 'Bookmark This Link' will copy/bookmark "about:blank" instead of the javascript url.

E.g. these bookmarklets: https://pinboard.in/howto/

### Steps to Reproduce

  1. Go to https://pinboard.in/howto/
  2. Right click a bookmarklet, e.g. 'popup'
  3. Select 'Bookmark This Link'

**Actual result:**

An 'Edit Bookmark' popup with Location set to 'about:blank'.

**Expected result:**

An 'Edit Bookmark' popup with Location set to the bookmarklet, e.g. `javascript:q=location.href;if(document.getSelection){d=document.getSelection();}else{d='';};p=document.title;void(open('https://pinboard.in/add?url='+encodeURIComponent(q)+'&description='+encodeURIComponent(d)+'&title='+encodeURIComponent(p),'Pinboard','toolbar=no,width=700,height=350'));`

**Reproduces how often:** 100%

### Brave Version

**about:brave info:**
 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.16288 
OS Architecture: x64

**Reproducible on current live release:**

Yes.

### Additional Information

Also tried with https://www.squarefree.com/bookmarklets/zap.html

**Comment by luixxiul** [comment]
bookmarklet does not work yet: https://github.com/brave/browser-laptop/issues/3218

**Comment by hugobuddel** [comment]
The particular bookmarks from pinboard (a bookmark service) do work when added manually. I've successfully added bookmarks to pinboard using a bookmarklet in Brave.

It's just that adding the bookmarklet cannot be done easily, as per this issue. Also, it is not possible to right-click in the 'edit bookmark' window, so pasting the link(/bookmarklet) has to be done with Ctrl-V, but this is an even smaller annoyance.

**Comment by bsclifton** [comment]
Good find, thanks for reporting @hugobuddel! 😄

**Comment by bsclifton** [comment]
Should be fixed with brave-core, if you wanted to try @hugobuddel 😄

**Comment by hugobuddel** [comment]
Great @bsclifton! This seems like a typical thing to be solved with brave-core. I'll try the Ubuntu version on https://brave.com/download-dev ASAP.

**Comment by jf** [comment]
Just a note: it's not necessary to use another browser, @hugobuddel . Pls see https://github.com/brave/browser-laptop/issues/3218#issuecomment-426129509

**Comment by hugobuddel** [comment]
It (sort-of) works on brave-core. That is, you can copy a bookmarklet-link and create a new bookmark with it. You cannot bookmark the link directly, because that is apparently not supported by Chromium (also not for regular links). But that's not such a problem.
