### ISSUE TITLE
remove unittest from pre-push hook

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11081]
i find that the unittest pre-push hook is more annoying than useful. ex:

1. unittests are sometimes broken on master (such as right now) for reasons unrelated to my change, so i end up having to use --no-verify.
2. pre-push hooks aren't run when merging via Github's UI so ultimately there is no guarantee that the unittests are passing
3. unittests take a long time to run and should be checked after-push in Travis anyway

**Comment by luixxiul** [comment]
CC @bbondy

**Comment by NejcZdovc** [comment]
I would keep this, because I sometimes forgot to run unittest manually and this helps me out

**Comment by luixxiul** [comment]
If there was `git push --unittest --lint` that would be great for me.

**Comment by diracdeltas** [comment]
@NejcZdovc i think #11084 probably wouldn't change things for you because you would still have the unittest pre-push hook in `.git/hooks`. however if you did a fresh clone, it would not have the hook by default.

**Comment by bsclifton** [comment]
This would be a good one to discuss in our weekly CI meetings (Friday)

**Comment by bbondy** [comment]
I personally prefer having it even for merging on diff branches and pushing.
It doesn't take very long and `--no-verify` isn't hard to add when you don't need it.

unit tests and lint checks both have saved me several times from accidentally pushing things int he past

**Comment by bsclifton** [comment]
I do a lot of merging and testing with PRs and I definitely enjoy this feature

@diracdeltas what do you think about updating the pre-commit hook to not run if you have a specific environment variable defined, like NO_PRECOMMIT_TESTS.  If that's defined, we can just noop

**Comment by bbondy** [comment]
env variable one way or the other seems like a good solution to this.

**Comment by diracdeltas** [comment]
@bsclifton @bbondy https://github.com/brave/browser-laptop/pull/11084 already uses the env variable approach
