### ISSUE TITLE
site that i've never visited shows up in the synopsis

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11080]
i opened about:preferences#payments yesterday and noticed a site i haven't visited (i subsequently visited it to see what it was): 
![screen shot 2017-09-21 at 7 57 46 pm](https://user-images.githubusercontent.com/549654/30716607-2f4e9636-9f0a-11e7-93e4-774b5e038da0.png)

it appears this site just became a verified publisher yesterday (maybe coincidence, maybe not)

**Comment by NejcZdovc** [comment]
this should be fixed with refactor
