### ISSUE TITLE
Netflix fails to login after import cookies from other browsers

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11089]
### Description
Netflix imported credentials fails to login

### Steps to Reproduce

  1. Save Netflix credentials on Chrome, close the browser
  2. Import credentials into Brave on 0.19.13
  3. Visit Netflix, Click on login with auto populated credentials, doesnt login

**Actual result:**

Doesnt login with imported credentials
**Expected result:**
Should login
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

Brave | 0.19.13
-- | --
rev | e577865
Muon | 4.4.19

**Reproducible on current live release:**

### Additional Information

cc: @darkdh

**Comment by LaurenWags** [comment]
I see this on MacOS as well.

**Comment by darkdh** [comment]
![kapture 2017-09-22 at 9 56 31](https://user-images.githubusercontent.com/11330831/30766344-28ffe20e-9fa9-11e7-8d2a-b1bd4801d9ba.gif)
1password and manually typing from my end.

**Comment by darkdh** [comment]
Couldn't reproduce on master

**Comment by srirambv** [comment]
Login works when Cookies are no imported. Just importing Credentials allows to login

**Comment by LaurenWags** [comment]
I am able to consistently reproduce with these steps:
In Chrome, open netflix, if not logged in, login.
Log out of Netflix on Chrome.
Close Chrome.
Open Brave (I'm using 0.19.16).
Import only cookies from Chrome.
Once this is successful, navigate to netflix.
Type in your credentials. You are not able to login to Netflix.

**Comment by darkdh** [comment]
Same thing happens when importing cookies from Firefox

**Comment by kjozwiak** [comment]
I'll mark this as `QA/checked-Linux` once password importing into brave from chrome/chromium has been fixed in https://github.com/brave/browser-laptop/issues/9434#issuecomment-333955149.

Importing the password/cookies for Netflix from Firefox under Ubuntu 16.04 x64 and Ubuntu 17.04 x64 is working as expected.

**Comment by darkdh** [comment]
Please noted this issue has nothing to do with import password which was a redundant step to reproduce this bug.

**Comment by kjozwiak** [comment]
Waiting for #11280 to be fixed so I can make sure that this issue also works with Chrome once importing cookies has been fixed.
