### ISSUE TITLE
Closing tab page while tabs are loading can lead to dead tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11085]
### Description
Closing a tab page (with the tab page right click menu option) while tabs are loading can lead to dead tabs.

### Steps to Reproduce

  1. Open up several tab pages
  2. Before the tab pages finish loading, right click on the tab page and close the tab page

**Actual result:**
Sometimes a dead tab is left behind

**Expected result:**

No dead tab should be left behind.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Often but not always

### Brave Version

0.18.36

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@cezaraugusto I think this is related to the issue we were debugging (https://github.com/brave/browser-laptop/issues/11028)

**Comment by bsclifton** [comment]
@bbondy I believe you fixed this, right?

**Comment by bbondy** [comment]
yes there remains some kind of intermittent crash that can happen but it's related to tab close and not related to this which caused dead tabs.
