### ISSUE TITLE
Open link from external application creates new brave window

### ISSUE THREAD

**Issue by orschiro** [brave/browser-laptop#11098]
Steps to reproduce:

1. Close your Brave session that contains some tabs
2. Open a link from Thunderbird email
3. Brave opens with your session from step 1. and in addition a new window with the link from step 2

Tested on:

Ubuntu MATE 17.10
Thunderbird 52
Brave 0.18.36

**Comment by srirambv** [comment]
This happens for any link opened with Brave set as default browser. Not specific to Thunderbird. Reproduced on Windows as well

**Comment by bsclifton** [comment]
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/4197.  This has a better title- I'll update the original to have this title 😄
