### ISSUE TITLE
Redirection Error for CloudFlare enabled websites

### ISSUE THREAD

**Issue by BraveSauce** [brave/browser-laptop#11093]
### Description
Browsing websites with the CloudFlare CDN enabled results in a redirection error:

`Attempting to load an URL resulted in too many redirects.`

### Steps to Reproduce
Simply open a website that uses CloudFlare. 

**Actual result:**
After the "browser check" page, the error page is shown. At this point, if the URL is edited manually to just the root of the domain, the page works.

**Reproduces how often:**
This happens 100% of the time in my tests.

### Brave Version
` Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64`

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/redirect-limit-stopping-site-access/7913?u=eljuno

Brave 0.18.36
rev 7ab85e9
Windows 10

**Comment by luixxiul** [comment]
do you reproduce the issue with HTTPS everywhere disabled?

**Comment by BraveSauce** [comment]
Hmm, indeed HTTPSe seems to be the problem. I had some success loading up sites with it enabled. That doesn't make sense though since CloudFlare still uses HTTPS for its requests. Could this be a loop of both the HTTPSe and the site itself trying to redirect to the same URL?

**Comment by orosseel** [comment]
+1 for me too!

Very annoying bug.

Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Comment by luixxiul** [comment]
It is a bug of HTTPS Everywhere and that issue should be forwarded to https://github.com/EFForg/https-everywhere

**Comment by orosseel** [comment]
Even with HTTPS Everywhere disabled, I get this issue.

**Comment by bsclifton** [comment]
@orosseel do you get the issue with shields down?

**Comment by orosseel** [comment]
It seems to be solved in release 0.19.48. I think I tried it with shields off but can't remember.

**Comment by bsclifton** [comment]
Appears to be fixed now; example given above is  http://overkillsoftware.com/ which did not work with Brave 0.18.36 on Sep 19th
