### ISSUE TITLE
Failed to fetch /dists/artful/InRelease

### ISSUE THREAD

**Issue by orschiro** [brave/browser-laptop#11092]
I performed the following two commands on Ubuntu MATE 17.10:

    curl https://s3-us-west-2.amazonaws.com/brave-apt-staging/keys.asc | sudo apt-key add -
    echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt-staging `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list

Now I am getting this error when running `sudo apt update`:

    Reading package lists... Done
    E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt-staging/dists/artful/InRelease  403  
    Forbidden
    E: Some index files failed to download. They have been ignored, or old ones used instead.

What can I do?

**Comment by orschiro** [comment]
Can be resolved by going into `/etc/apt/sources.list.d/brave-artful.list` and replacing `artful` with `zesty as follows:

    deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt-staging zesty main

**Comment by bsclifton** [comment]
@orschiro is there something which can be updated in our documentation?
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

**Comment by orschiro** [comment]
@bsclifton I think the documentation is actually correct. I just guess that there is no package for staging available yet for 17.10 artful which is the one I am using.

**Comment by bsclifton** [comment]
Interesting- support was added with https://github.com/brave/browser-laptop/issues/10755

I wonder if staging hasn't been updated yet? Can you try the production URL? We aren't fully utilizing the staging (yet). When we do publish, we typically update both at the same time

**Comment by orschiro** [comment]
@bsclifton sorry but which one is the production URL?

**Comment by bsclifton** [comment]
@orschiro that would be the one you add with this:
```
curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -
echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list
```

**Comment by orschiro** [comment]
@bsclifton these commands succeed but the latest version I get is `0.18.36-1`.

**Comment by bsclifton** [comment]
@orschiro that is the latest version.  What version do you get with the staging repo url?

**Comment by orschiro** [comment]
@bsclifton let's roll back to the beginning. I am getting lost here. :-) 

All I wanted was to test the Beta, Alpha or whatever you may call that on my Ubuntu 17.10. 

How do I do this?

**Comment by bsclifton** [comment]
@orschiro good idea!

Just to be clear, the process you followed was 100% correct! 😄  Unfortunately, when we do releases, we haven't been running the job for the staging (beta) repo ☹️ 

I made some tweaks to this script (it was only working for the release channel, unfortunately) and it should now be working for you! Please let me know and you can close the issue if it's working as expected

In case the staging url is neglected (we'll be getting better at this, I promise!), you can always wget/curl the package from https://github.com/brave/browser-laptop/releases and install (but using apt is a lot nicer of course).  The additional channels are we have are still a work-in-progress (beta, developer, nightly).

**Comment by orschiro** [comment]
> In the future: if the staging url is neglected (we'll be getting better at this, I promise!), you can always wget/curl the package from https://github.com/brave/browser-laptop/releases and install (but using apt is a lot nicer of course).

This is useful to know. Thanks! :-)
