### ISSUE TITLE
Zoom-in/Zoom-out option

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1110]
Hello Dev team,

i noticed that Control key+mouse scroll doesn't minimize the page like in firefox and chrome .

can that be added to brave?
i notice that Control key with +/- keys only allow for minimize or maximize the page zoom.
one more thing is that the browser resets that zoom selection once you open any site again without saving the preference of the zoom.

regards,
Haze

**Comment by bbondy** [comment]
Fixed via https://github.com/brave/browser-laptop/commit/d70bb786382e512b28af962c6fd8d3c467a5cee3
