### ISSUE TITLE
visiting about:preferences#search should not set cookies

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11108]
i noticed that opening about:preferences#search causes cookies to be set for various sites, probably because Brave is making requests to load their favicons:
![screen shot 2017-09-23 at 6 53 48 am](https://user-images.githubusercontent.com/549654/30770922-2747ff0e-a02c-11e7-8155-23275c224f01.png)

we should not load the favicons remotely

**Comment by luixxiul** [comment]
related: #2697 - Cache favicons (to prevent fetching each time Brave is reloaded)
