### ISSUE TITLE
Why is Brave rather slow to open? ~5-7 seconds at least.

### ISSUE THREAD

**Issue by DiscoPoloMan** [brave/browser-laptop#11119]
### Steps to Reproduce

  1.Opening browser
  

**Actual result:**

**Expected result:** 
Instantly to 2 seconds.
**Reproduces how often:** 100%

**Reproducible on current live release:**
Live build

**Comment by luixxiul** [comment]
The performance issue is discussed here: https://github.com/brave/browser-laptop/labels/perf

we're working hard on that issue.
