### ISSUE TITLE
Bookmark order is not correct

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11116]
### Steps to Reproduce

  1. Install Brave 0.18.36
  2. Create several bookmark folders; manually sort the order, add a few bookmarks
  3. Install Brave 0.19.x
  4. Notice that the bookmark toolbar order is not respected

**Actual result:**
<img width="432" alt="btb-0 19 x" src="https://user-images.githubusercontent.com/4733304/30780188-307fa1e2-a0ba-11e7-8306-2aba4de167b6.png">

**Expected result:**
<img width="436" alt="btb-0 18 x" src="https://user-images.githubusercontent.com/4733304/30780189-35582f86-a0ba-11e7-9b6c-9ac590e39bda.png">

**Reproduces how often:** 
100%

### Brave Version

**about:brave info:**
 
Brave: 0.19.14 
rev: b051f3dbd1be9b2e997cd585cb19eaa934006713 
Muon: 4.4.19 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
No (works as expected with 0.18.36)

**Comment by NejcZdovc** [comment]
fixed with #11144

**Comment by bsclifton** [comment]
- Marked as `release-notes/exclude` since this was introduced with 0.19.x
- Marked as `QA/no-qa-needed` since this is covered with automated tests
