### ISSUE TITLE
Feature Request/Polish New Tab Clock doesn't respect regional settings

### ISSUE THREAD

**Issue by Krakass** [brave/browser-laptop#11117]
### Description
Regardless of settings in the OS, the clock in the new tab is formatted based on the language selected in the browser's settings.

### Steps to Reproduce
  1. In Windows, change the clock to 24 hours.
  2. Open browser to new tab
  3. See settings are not reflected

**Actual result:**
![image](https://user-images.githubusercontent.com/7534487/30780824-a7a4d9bc-a0d9-11e7-9d28-5b30ba6547a8.png)

Not the best example due to the current time, but if I choose Japanese for example, it displays correctly.

**Expected result:**
Clock matches settings.

### Brave Version
18.36

**Reproducible on current live release:**
Yes

**Comment by eljuno** [comment]
Related to #7781?

**Comment by Krakass** [comment]
Ugh. Yes, this is a duplicate of that. I searched too.
