### ISSUE TITLE
Proxy option

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1111]
Hello Dev team,

so i started using Brave for my work related tasks.
unfortunately at work sometimes requires us to have a proxy present int he browser to get to external sites.
i noticed that there is no option anywhere to add modify proxy related information.

can this be added ? are you already working on that?

Regards,
Haze

**Comment by tanay1337** [comment]
@Haze-Aulaian AFAIK Brave currently makes use of system proxy, but yes an explicit option to set proxy like Firefox would be very helpful!

**Comment by Haze-Aulaian** [comment]
System proxy as in what? Chrome , Firefox or IE ?
i didnt see that documented in where , but its crucial to have that option especially if we are targeting people in companies who use internal proxy like me to access internal sites.

**Comment by tanay1337** [comment]
@Haze-Aulaian I was referring to the Network proxy that can be set from the Settings in OS X. Brave by default uses that proxy in this operating system. But yes, an explicit proxy menu is important.

**Comment by luixxiul** [comment]
Closing this in favor of #770
