### ISSUE TITLE
Reopen closed tab causes ghost tab and browser unresponsive

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11129]
### Description

Reopen closed tab causes ghost tab 
### Steps to Reproduce

  1. Open a new profile on 0.19.16
  2. Open a few tabs and close some of them
  3. Use keyboard shortcut to open closed tab, creates a ghost tab

**Actual result:**

ghost tab created when reopening closed tab, browser becomes unresponsive

**Expected result:**
Should just reopen the closed tab
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

Brave | 0.19.16
-- | --
rev | 88d0bc1
Muon | 4.4.19

**about:brave info:**

**Reproducible on current live release:**

No

**Comment by bbondy** [comment]
I think this was just a consequence of this error:
https://github.com/brave/browser-laptop/issues/11133

Please re-open if you see again though.
