### ISSUE TITLE
Option to disable Alt menu key trigger

### ISSUE THREAD

**Issue by orschiro** [brave/browser-laptop#11127]
I raised this question on the [community forum](https://community.brave.com/t/disable-alt-menu-key-trigger/8106) but didn't get any reply yet. 

Basically, I wish you request a feature that disable the Alt menu key trigger. Alt is involved in many other keyboard shortcut combinations and this keeps triggering the menu in Brave unless I always show the menu, which I don't want either.

Hence, I would welcome another option to disable the Alt menu key trigger that I can combine with always hiding the menu. 

Thanks!

Robert

**Comment by luixxiul** [comment]
duping to #5775 and #9253?

**Comment by orschiro** [comment]
@luixxiul yes, definitely related. Thanks! Will close this and comment in #5775.
