### ISSUE TITLE
Maybe Bug: UI get larger even it set to Normal

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#11121]
### Description

Brave UI get larger accidentally. Even it set to **Normal** under Preferences > Advanced.
Reopen the browser, will take it back to Normal.

### Steps to Reproduce

  1. Not sure about the STR, since it happen accidentally. And happened for the first time. What I notice is it get larger when I switch tab and scroll through the page using trackpad on my laptop.
  2.
  3.

**Actual result:**

UI get larger. You'll see it set to **Normal**.
![bug-25-09](https://user-images.githubusercontent.com/25360853/30785657-80c2cb18-a194-11e7-97b3-6ae470e4b4f7.png)

**Expected result:**
Stayed like what user set.

**Reproduces how often:** [What percentage of the time does it reproduce?]
First time face this. Will look if it happen again.
 
### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0
Update Channel | dev
OS Platform | Microsoft Windows
OS Release | 6.3.9600
OS Architecture | x64

**Reproducible on current live release:**

**Comment by eljuno** [comment]
Possible STR (not 100% work)

- Have few tabs
- Switch between tab using Ctrl+Tab/Ctrl+Shift+Tab
- After tab switched, immediately scroll using trackpad

**Comment by srirambv** [comment]
I guess this is same as https://github.com/brave/browser-laptop/issues/3244
