### ISSUE TITLE
Adapting size of tabs in tabs bar

### ISSUE THREAD

**Issue by huntingorion** [brave/browser-laptop#1112]
Hello there, here a user of brave since its first beta release. It kinda become my second browser but I'm still struggling with your "tab pages". I mean the tabs have fixed size on the tabs bar and we are forced to move through differrent pages just to find a tab. I was hoping you'll make tab size adapt to number of opened tabs (in a way that there want be "pages of tabs") in the recent update but still nothing.
Will it be possible to include this feature in the next update cuz seriously, I'm dying of scrolling between "tab pages" with so much tabs opened.
Thank you and Good continuation.

**Comment by bradleyrichter** [comment]
Hi @huntingorion. Thanks for the feedback. 

How many tabs do you typically find that you keep open?

Have you tried to adjust the tabs-per-set option to allow up to 20 tabs?

We are trying to address "tab overfow" in a better way than Chrome or Firefox and so far the feedback on tab sets has been more positive than negative but not unanimous. So we added the pref to increase.

I may end up adding an option to just keep shrinking like chrome for those who prefer the micro tabs over tab sets. But we do have some powerful/useful features planned for tab sets that are not possible with chrome-style shrinking.


Thanks again...

Brad

**Comment by huntingorion** [comment]
Thanks for the answer, if you decided it's better to have tab sets, I'll adapt then (I'll be bravish).
Many thanks again :)

**Comment by bradleyrichter** [comment]
Ha! Thank you for giving it a try. Only time will tell if this is the right move. I will be interested to learn if your adaptation is going smoothly.

BTW - here is a proposed improvement that we hope to implement soon: #955

If JS animations are your thing...have at it. I'd be thrilled to get it into the codebase.


Thanks,
Brad
