### ISSUE TITLE
Create our bot with auto-reply

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11137]
### Description

Create our bot with auto-reply by @parkr.

https://github.com/parkr/auto-reply
https://byparker.com/go/auto-reply

By default it would make it possible to do these automatically:

- Add proper milestone and labels for PRs and issues 

    - Add `PR/needs-rebase` to PRs which conflict with others because of another PR merged before
- Delete branches
- Update changelog

and so on.

Here is an example how the bot would work: https://github.com/jekyll/jekyll/pull/6377#issuecomment-331274103

We could enhance it to do like these:

- `@bravebot: merge +0.19.x +testplan`

  Merge to master, cherry-pick to `0.19.x`, `0.20.x`, add the label `QA/test-plan-specified` and the milestone `0.19.x`. 

- `@bravebot: merge ==0.19.x`

  Merge to `0.19.x` only, add the milestone to the issue and PR.

- `@bravebot: merge &(feature/ledger, polish) +0.20.x`

  Merge to master, cherry-pick to `0.20.x`, add the labels `feature/ledger` and `polish` and the milestone `0.20.x`.

It would be fantastic :-)

### Additional Information

Here are possible use cases:

- `@bravebot: merge ==0.19.x +testplan`
- `@bravebot: merge ==0.19.x -testplan`
- `@bravebot: merge ==0.19.x`
- `@bravebot: merge <=0.19.x`
- `@bravebot: merge >=0.19.x`
- `@bravebot: merge &(feature/ledger, bug) ==0.20.x +testplan`
- `@bravebot: merge &(feature/ledger, bug) >=0.20.x -testplan`

etc.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/909
