### ISSUE TITLE
lock icon missing when clicking on mailto: link

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11131]
### Description
When I click on a mailto: link (like on brave.com), the padlock icon is removed from URL bar and doesn't return until I refresh the page.

### Steps to Reproduce

  1. Navigate to brave.com
  2. Go to the footer and click on one of the contacts email links.
  3. View URL Bar

**Actual result:**
Once you click on the email link, the lock icon disappears:
![screen shot 2017-09-25 at 9 38 41 am](https://user-images.githubusercontent.com/28145373/30811152-6065e9a4-a1d5-11e7-88b8-3bc6ede9b7cf.png)

![screen shot 2017-09-25 at 9 39 12 am](https://user-images.githubusercontent.com/28145373/30811164-68f4806c-a1d5-11e7-97b1-3cc1151ecbab.png)

**Expected result:**
Lock icon should not disappear.

**Reproduces how often:** 100%

### Brave Version

**about:brave info:**
Brave | 0.19.16
rev | 88d0bc1
Muon | 4.4.19

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Tentatively marking as `sec-low`
cc: @diracdeltas for triage
