### ISSUE TITLE
about:newtab tile favicons are inconsistent in size

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#11132]
### Description
When visiting the new tab page, the favicons are different sizes.

### Steps to Reproduce
Visit a random set of sites, usually Hacker News is ok, but Facebook & YouTube occasionally go through the shrink ray.

  1. Visit a few different sites
  2. Open a new tab
  3. Observe favicons in tiles

**Actual result:**
<img width="1438" alt="screen shot 2017-09-11 at 10 29 55 am" src="https://user-images.githubusercontent.com/1434040/30813084-1564385a-a1d2-11e7-80ec-ecf33ede4966.png">

**Expected result:**
The favicons should all be of a consistent size.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version
It's been an issue since newtab was implemented.

**about:brave info:**

**Reproducible on current live release:**
Yes

**Comment by MargarytaChepiga** [comment]
Hello! I think this is because we set the img to max-width and max-height. Which sets the limit only for the maximum size of the image. So if the favicon is smaller than 64px it will display it's original weight and height. Here:
https://github.com/brave/browser-laptop/blob/56f9e724c74d0929ec70aeca214a5c0c4a2078f3/less/about/newtab.less#L235
The solution I see to this is to make the size static. Any ideas? Is anyone is working on this btw?

**Comment by bradleyrichter** [comment]
@MargarytaChepiga My only concern with this otherwise nice fix is that, as you said, the 16x size icons will scale up and look fuzzy. Is there a way to add an exception to prevent this? 

(only allow favicons to scale up to the desired height/width if they are large enough.)

**Comment by MargarytaChepiga** [comment]
@bradleyrichter yes, I can do that. But again, the icons won't be the same size.

**Comment by MargarytaChepiga** [comment]
@bradleyrichter If you mean to leave them the same size ( as in don't scale up 16px) then it's pretty much the same thing as it was before with the only difference that the favicons size is smaller now. Take a look please:
![max-32](https://user-images.githubusercontent.com/15698572/38838218-2dd681b0-41a3-11e8-9c5b-06ad393086a9.PNG)
