### ISSUE TITLE
Refactor menu into a reducer file

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11136]
`app/browser/menu` should be split into an api file and a reducer file.  The reducer should go in `app/browser/reducers`

**Comment by dskeppstedt** [comment]
Is this still an active issue? I have a team of five that could out.

**Comment by bsclifton** [comment]
@dskeppstedt absolutely 😄 

If you open `app/browser/menu`, you'll notice there's a big function `doAction`. This could be broken out to a new `menuReducer.js` or similar and then invoked via the appStore:
https://github.com/brave/browser-laptop/blob/901e94175fbd7340ad0593b8303926a1758462c3/js/stores/appStore.js#L179

**Comment by dskeppstedt** [comment]
Cool, working on a fix!

**Comment by dskeppstedt** [comment]
@bsclifton Is there a reason that not all actions are covered in MenuTest.js? For example `APP_ADD_BOOKMARK` is missing.

**Comment by bsclifton** [comment]
@dskeppstedt I think the reason was just lack of time 😄 Help with unit tests is VERY much appreciated! Our coverage is not horrible, but it could be a lot better

**Comment by dskeppstedt** [comment]
@bsclifton I just created a pull request
https://github.com/brave/browser-laptop/pull/13187
