### ISSUE TITLE
Brave decides to open all tabs at once in a given window

### ISSUE THREAD

**Issue by gettyhub** [brave/browser-laptop#11141]
### Description

Not sure what provokes it but waving the mouse over a tab, causes all tabs in a given window try to open all at once causing a sudden overload as the browser tries to open several pages at once, instead of only opening a particular tab that is waved over by the mouse.

### Steps to Reproduce

  1. Not exactly sure, but seems to be waving the mouse over a tab causes multiple tabs to open in a given window.  Breaking up the tabs into separate windows limits the ability of this miscuing.  
  2.  If all your tabs are in one window, they will all be opened at the same time, but it does not affect other windows.
  3.  Default behavior is for only one tab to open at a time being waved over by the mouse, this might be a setting in the setting box, but seems to be ignored under this incursion.  

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.18.36
-- | --
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0
Update Channel | dev
OS Platform | Linux
OS Release | 4.12.13-1-ARCH
OS Architecture | x64

**Reproducible on current live release:**

This has been going on for several versions, not sure when it initially started.

**Comment by bsclifton** [comment]
Similar to https://github.com/brave/browser-laptop/issues/8749

**Comment by bsclifton** [comment]
I haven't seen this happen at all- but if it IS happening still for anybody, I'd encourage them to check out our new [developer channel release](https://brave.com/download-dev) (brave-core). Closing as `wontfix`
