### ISSUE TITLE
extension icons do not appear at top right of app

### ISSUE THREAD

**Issue by kevinlawler** [brave/browser-laptop#11142]
### Description
Extensions like Pocket or Pinterest do not have their icons appear in the top right of the app. This is due to the wrong protocol (`file://`) being caught by CSP restrictions.

### Steps to Reproduce

Build and load browser. Turn on Pocket extension

**Actual result:**
![screen shot 2017-09-25 at 2 29 12 pm](https://user-images.githubusercontent.com/376238/30831864-f0d23772-a1fd-11e7-944c-6b1104d9ecf8.png)

Note vertical grey bar `|`.

**Expected result:**
Pocket icon should appear.

**Reproduces how often:**
100%

### Brave Version

Brave: 0.21.0 
V8: 6.1.534.39 
rev: 25130655e6717f9e3b6f77d6dfed94e990a09960 
Muon: 4.6.3 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 61.0.3163.98

**Reproducible on current live release:**
No. Not a problem on the live build.

### Additional Information
None

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11143
