### ISSUE TITLE
bookmarks bar site icons

### ISSUE THREAD

**Issue by Crocodile73** [brave/browser-laptop#1114]
would like to see the option, to have the icon of the website on the bookmark bar next too the name. looks better to me.

**Comment by bsclifton** [comment]
I'd love to see the favicons also- checking out this issue...

It would be ideal if their display could be toggleable. Let's see how hard this is :smile:

**Comment by bsclifton** [comment]
I was able to get that area of the code toggling pretty easy:
https://github.com/bsclifton/browser-laptop/commit/2c78f41bdf092e156d26d1ba50bcb53a61615c86

The hard part would be storing the icons and then loading them. I'll keep looking into this

**Comment by bsclifton** [comment]
I got this mostly working, can definitely use an assist cc: @bbondy 

I squashed the previous commit + another coding session into a single commit:
https://github.com/bsclifton/browser-laptop/commit/1cde3bf174233d96d5fb9b22f0924d93a632a5a6

The preferences screen now shows Bookmarks Toolbar / favicon checkboxes that do work; the icon will show (not in the folder unfortunately, need to see why). The positioning is all jacked though :/

**Comment by bsclifton** [comment]
Submitted https://github.com/brave/browser-laptop/pull/1454 which adds icons for the buttons in the Bookmarks Toolbar. If accepted, I'd like to make a 2nd PR which puts the icons into the folders (context menus).

**Comment by bbondy** [comment]
That works, I think Brad wanted the borders though, but I want him to reply first.  @bradleyrichter

**Comment by bsclifton** [comment]
I think we can address everything with the PR:
* Bookmarks toolbar fixes that already work (DONE)
* Adding the icon to context menu, per the comments in the PR (pending)
* UX decisions (borders needed on top of bookmarks toolbar?) and tweaks

I'll try to wrap up the context menu part tonite, will stay tuned for comments :smiley:

**Comment by bradleyrichter** [comment]
@bsclifton @bbondy 

Favicons certainly add to the visual noise, but I know they do help with bookmark recognition. Here is a mockup showing the borders removed:

![image](https://cloud.githubusercontent.com/assets/13509546/14773623/030e7c1a-0a61-11e6-9bd2-ed50fd14a273.png)


I think I prefer the borders but they could be softened later.

I would also prefer to retain the thin height for favicons-off if possible. I don't think there is a happy medium unless it becomes too problematic.

**Comment by bbondy** [comment]
I think we're ready to merge after Brad's comments. Thanks again for the awesome work @bsclifton

**Comment by bsclifton** [comment]
You're very welcome :) Give me another coding session to knock out the rest and I'll notify you all

**Comment by bbondy** [comment]
@bsclifton if there are any other changes that you were planning other than the ones I already did, feel free to open another pull request. Thanks again, great to have this work landed.
