### ISSUE TITLE
Release notes modal is not dismissed when manually updated

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11165]
### Steps to Reproduce

  1. Install an older build
  2. Check for update, ensure the update is shown and the release note modal is shown
  3. Keep the release notes modal and manually upgrade to the new build, modal is retained after upgrade

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/30893521-3825fd8e-a35c-11e7-85a6-4a68f6bc4482.png)

**Expected result:**
Modal should be dismissed when manually upgraded

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
> Keep the release notes modal and manually upgrade to the new build

Do you mean the you install the new build, without closing the browser? I cannot close the browser, without closing the release note dialog (which is closed when you click somewhere outside of the dialog).

**Comment by srirambv** [comment]
>Do you mean that you install the new build, without closing the browser?  

Yes that is correct. With the browser window still open, run the new setup and after launch the modal is still retained with the release notes for the installed build as shown in the screenshot
