### ISSUE TITLE
Display confirmation dialog when clicking the trash icon on about:payments ledger table

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11164]
### Test plan
See https://github.com/brave/browser-laptop/pull/13128

### Description

Display confirmation dialog when clicking the trash icon on about:payments ledger table.

### Steps to Reproduce

  1. Visit some sites
  2. Open about:payments
  3. Click a trash icon

**Actual result:**

The entry is deleted without confirmation and you cannot redo deletion

**Expected result:**

The entry should be deleted with confirmation

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

 
Brave: 0.19.17 
rev: e7e4365f727619a0f2f895c814411de06de9b7d8 
Muon: 4.4.20 
libchromiumcontent: 61.0.3163.98 
V8: 6.1.534.39 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

Reproducible.

### Additional Information

https://github.com/brave/browser-laptop/issues/4634#issuecomment-332379472

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
