### ISSUE TITLE
Pinned tabs disappear from tabs bar until restart

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11171]
## Test plan

See below

----

### Description

Pinned tabs disappear from tabs bar until you restart the browser

### Steps to Reproduce

  1. Delete the browser's profile
  2. Open the browser
  3. Open a new tab
  4. Click the twitter tile
  5. Open another new tab
  6. Click the facebook tile
  7. Pin about:welcome, twitter, facebook tabs
  8. Reorganize the pinned tabs
  9. Unpin two of them

**Actual result:**

They disappear, until you close and restart the browser

**Expected result:**

They should not disappear

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Brave Version

**about:brave info:**

Brave: 0.19.20 
rev: d9566ab3cab788c5157a9d281de5201afe27e47e 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
![bug](https://user-images.githubusercontent.com/3362943/30896998-dac9e032-a38e-11e7-96db-5c6e2a85ad9f.gif)

**Comment by kjozwiak** [comment]
@luixxiul, is this a regression? Does this happen under `0.18.36`?

**Comment by luixxiul** [comment]
No.

**Comment by bbondy** [comment]
0.19.x:
11aacb0943c00de996df269fbbf60f8b53f048b3
5e81ea705838deab1e1e28ca6ce9c6856be2b14b

0.20.x:
b30a22eb5a1af745ccd658cf7b546a6c346fe878

master:
d8a932cf2b9da52ec7e449529eafc16fe31f0144

**Comment by bbondy** [comment]
@kjozwiak @LaurenWags @srirambv When testing this, please also test https://github.com/brave/browser-laptop/issues/11070 because it fixes a bug which that issue's fix introduced.  I reset the QA checked flag on #11070 to make that explicit. Thanks!

**Comment by srirambv** [comment]
Still reprodicible on 0.19.29. Not able to repro #11070 though on the same build

**Comment by bbondy** [comment]
0.19.x: e25da7fc0028507ec3a41629b08e86760582aeef
0.20.x: 1d44bef8e5ac1c565fa519c66b71a28bcb044792
