### ISSUE TITLE
Brave Payments Import/Export and whitelist or blacklist

### ISSUE THREAD

**Issue by anonlksadjlsakjdlsak** [brave/browser-laptop#11179]
Adnauseum firefox user here who is considering switching to brave at some point in the near future.

I would be willing to pay monthly for websites using Brave Payments that follow EFF's Do Not Track policy found here: https://www.eff.org/dnt-policy but not for websites that are using tracking ads.

I've noticed that all Brave whitelists have to be set manually as you browse, there is not even an option to write in websites.

I was thinking it would be very useful if you could copy+paste a list of websites you want to pay and those you don't. Also to have them exportable for sharing among browsers. Even including [EFF's whitelist](https://www.eff.org/files/effdntlist.txt) by default would be an excellent way to improve the internet as a whole.

**Comment by bsclifton** [comment]
This is a great idea 😄  
cc: @mrose17 @diracdeltas @bradleyrichter @davidtemkin
