### ISSUE TITLE
Ledger transfer PDF opens another window

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11173]
### Description

When you open transaction from ledger, you get additional window and brave becomes unresponsive.

### Steps to Reproduce

  1. Create wallet
  2. Generate some transactions
  3. Click on one transaction

**Actual result:**

![image](https://user-images.githubusercontent.com/9574457/30897866-e27c21cc-a358-11e7-8ad3-499337e6eb86.png)

**Expected result:**
There shouldn't be any additional window and brave should work.
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

 
Brave: 0.19.20 
rev: ec880d04ad36d45b14c162554d58c726c7f0cf7b 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**

Yes
### Additional Information

https://github.com/brave/browser-laptop/pull/10691#issuecomment-329850074

**Comment by NejcZdovc** [comment]
After some digging I found out that we actually open this new window and save dialog modal, which is hidden behind this new window. So the only thing here to do is don't show this window from the start

**Comment by NejcZdovc** [comment]
For some reason window is always opening. What I did to solve it is basically set width and height to 0. Now everything is working again

**Comment by bsclifton** [comment]
@NejcZdovc great find! That is always a small detail that annoyed me but I hadn't taken the time to create an issue 😄

**Comment by bsclifton** [comment]
Since this has been the behavior for several releases, I'm going to remove `release/blocking`
