### ISSUE TITLE
Inform user when FLV has been blocked

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11176]
### Description
When an FLV is the sole source for a `<video>` element, the media will be blocked. The user, however, is not made aware that the media has been blocked. Instead, the user is given an error message _No compatible source was found for this media._

### Steps to Reproduce
  1. Navigate to https://dotsub.com/view/c2992e57-2df7-459c-91f4-48ba4e94f1a7
  2. Attempt to play the embedded video

**Actual result:**
Video cannot be played.

**Expected result:**
Video is either played, or the user is informed as to why the video cannot be played.

**Reproduces how often:**
100%

### Additional Information
The FLV is blocked, presumably, because it requires Flash logic. In spite of its dependency on Flash, the user is never prompted to allow the media, or to allow Flash (if even for the session).

In Chrome, the user is also not prompted, but can enable the media via the omnibar:

![allow-flash](https://user-images.githubusercontent.com/815158/30920767-6a250466-a36a-11e7-99cd-a3baa2a6e825.gif)

**Comment by bsclifton** [comment]
Removing milestone (please feel free to reassign if there's a PR to fix this)
