### ISSUE TITLE
add maps.google.com to top site list for suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11181]

**Comment by LaurenWags** [comment]
STR:
Open a new tab. 
Start to type maps.google.com
Verify that maps.google.com is available in the 'Top Site' section on the URL drop down:
![screen shot 2017-10-03 at 11 18 27 am](https://user-images.githubusercontent.com/28145373/31133144-a7bd0e92-a82c-11e7-9719-650a8db46215.png)

**Comment by LaurenWags** [comment]
The rationale behind this is that maps.google.com redirects to google.com/maps, however many people type maps.google.com. This was added to make a better user experience.
