### ISSUE TITLE
Opensuse repo unsigned

### ISSUE THREAD

**Issue by badarotti** [brave/browser-laptop#11182]
Hi,

Trying to install Brave on OpenSUSE 42.3 following the instructions on https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md , unfortunalty I get the following error:

`File 'repomd.xml' from repository 'brave-rpm-release' is unsigned, continue? [yes/no] (no): 
`

Tried in on 2 different computers.
Regards,

**Comment by bsclifton** [comment]
cc: @posix4e

**Comment by posix4e** [comment]
@badarotti you ran
```
sudo rpmkeys --import https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc
sudo zypper install lsb
sudo zypper addrepo https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/ brave-rpm-release
sudo zypper ref
sudo zypper install brave

```

**Comment by badarotti** [comment]
Thanks, but I did all that as the described in the Linux Install Instruction page I linked in the original question. Still getting that error. Any ideas on how to fix the problem?

**Comment by posix4e** [comment]
@badarotti just clarifying. Did i state your commands correct? I'm still not sure what you ran

**Comment by kalvisbuls** [comment]
I'm getting the same warning on Tumbleweed. I ran the exact same commands as listed in the installation instructions:

```
sudo rpmkeys --import https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc
sudo zypper install lsb
sudo zypper addrepo https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/ brave-rpm-release
sudo zypper ref
sudo zypper install brave
```

**Comment by badarotti** [comment]
Yes @posix4e I tried those commands and got that error..

**Comment by posix4e** [comment]
I have verified this on my container

**Comment by huwie-blue** [comment]
Yes, same here.  The file repomd.xml is simply not signed, that's all there is to it.  Would you please sign it?

**Comment by stan-qaz** [comment]
I can force an update to complete from zypper by ignoring the lack of a signature on repomod.xml

`stan:/home/data/download> sudo zypper update brave
Retrieving repository 'brave-rpm-release' metadata -----------------------------------------------------------------------------------------[\]
Warning: File 'repomd.xml' from repository 'brave-rpm-release' is unsigned.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: We can't verify that no one meddled with this file, so it might not be trustworthy
    anymore! You should not continue unless you know it's safe.

File 'repomd.xml' from repository 'brave-rpm-release' is unsigned, continue? [yes/no] (no): y
Retrieving repository 'brave-rpm-release' metadata ......................................................................................[done]
Building repository 'brave-rpm-release' cache ...........................................................................................[done]
Loading repository data...
Reading installed packages...
No update candidate for 'brave-0.19.53-1.x86_64'. The highest available version is already installed.
`

**Comment by posix4e** [comment]
OK great! THanks

**Comment by bsclifton** [comment]
@aspiers can you please try the new version of Brave? If that isn't working, we can open a ticket here:
https://github.com/brave/brave-browser

The Linux install instructions for the new Brave can be found here:
https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux

**Comment by aspiers** [comment]
[**@bsclifton**](https://github.com/bsclifton) commented on [23 Nov 2018, 20:12 GMT](https://github.com/brave/browser-laptop/issues/11182#issuecomment-441312340 "2018-11-23T20:12:42Z - Replied by Github Reply Comments"):
> [@aspiers](https://github.com/aspiers) can you please try the new version of Brave? If that isn't working, we can open a ticket here:  
> 
> [brave/brave-browser](https://github.com/brave/brave-browser)
> 
> The Linux install instructions for the new Brave can be found here:  
> 
> [brave-browser.readthedocs.io/en/latest/installing-brave.html#linux](https://brave-browser.readthedocs.io/en/latest/installing-brave.html#linux)

Unfortunately I can't try that straight off the bat, because there are no instructions for openSUSE.  But I work for SUSE and know the openSUSE software management ecosystem very well, so I would be happy to help you formulate an installation procedure for openSUSE.

**Comment by stan-qaz** [comment]
I tried to translate the Centos instructions to OpenSuse and got nowhere trying to add the repo.

From Yast's add repository dialog, adding https://brave-browser-rpm-beta.s3.brave.com/x86_64/ I get:
Permission to access 'https://brave-browser-rpm-beta.s3.brave.com/x86_64/repo/repoindex.xml' denied.

Brave has seemed like a good solution for many of the folks I support on OpenSuse but the install/update has never worked well enough I could risk deploying it.

**Comment by posix4e** [comment]
Hi @stan-qaz . Thanks for reporting in. I just checked out the new dev version and at first glance it works great. https://github.com/posix4e/brave-browser/pull/1
