### ISSUE TITLE
Chrome://crash causes existing about pages to crash

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11189]
### Description

Chrome://crash causes existing about pages to crash

### Steps to Reproduce

  1. Keep few about pages open (new tab/about:welcome/about:preferences)
  2. Open a new tab and type `chrome://crash` and ensure webview crashes
  3. Wait for a couple of minutes, all about pages have webview crash

**Actual result:**

![webview_crash](https://user-images.githubusercontent.com/17010094/30947110-725d6158-a425-11e7-9388-b82afb1bd8e7.gif)

**Expected result:**
Only the visited tab should crash

**Reproduces how often:** [What percentage of the time does it reproduce?]
~~Just once. Needs more investigation~~
Edit: 100% reproducible.  
### Brave Version

**about:brave info:**

Brave | 0.19.20
-- | --
rev | d9566ab
Muon | 4.4.25

**Reproducible on current live release:**

`chrome://crash` doesn't work so not reproducible 
### Additional Information

cc: @bridiver @darkdh

**Comment by kjozwiak** [comment]
I think @bbondy mentioned that this is expected behaviour. I believe it's one process per origin and all the about: pages share the same origin, hence loading `chrome://crash` takes down all the other about: pages.

**Comment by srirambv** [comment]
Closing as expected behaviour
