### ISSUE TITLE
Reattaching a tab doesnt always gets added in the same place

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11191]
### Description
Reattaching a tab doesnt always gets added in the same place

### Steps to Reproduce

  1. Have a set of tabs 
  2. Right click on any tab and click on detach to create tab into window
  3. Drag and drop the tab in the tabs bar, more often or less gets added at the end. Doesn't get added where it was dropped

**Actual result:**

Reattaching a tab doesnt always gets added in the same place. 
**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]
Happens 2/5 times 

### Brave Version

**about:brave info:**

Brave | 0.19.20
-- | --
rev | d9566ab
Muon | 4.4.25

**Reproducible on current live release:**
Yes happens 2/5 times

### Additional Information
cc: @bbondy

**Comment by kjozwiak** [comment]
Possibly related to #10961 that @bbondy found [here](https://github.com/brave/browser-laptop/issues/10939#issuecomment-329642585) during 0.18.x Hotfix 2 testing. Seems like not all the cases have been fixed.

**Comment by alexwykoff** [comment]
@srirambv can you retest this and move up if fixed?

**Comment by alexwykoff** [comment]
@srirambv might you retest when @petemill 's tab tearing works lands?
