### ISSUE TITLE
implement new add-funds wizard UI to support BAT

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#11193]
The new UI is specified in the attached PDF.

[bat_ledger_integration_spec2.pdf](https://github.com/brave/browser-laptop/files/1339622/bat_ledger_integration_spec2.pdf)

**Comment by NejcZdovc** [comment]
blocked by #10945

**Comment by NejcZdovc** [comment]
[crypto_icons.zip](https://github.com/brave/browser-laptop/files/1345031/crypto_icons.zip)

**Comment by alexwykoff** [comment]
It appears to be a very slight difference between the BAT logo in the zip and the one shown in the PDF. 

In the PDF there appears to be a small text of 'BAT' with the logo on the prefpane picker.

**Comment by luixxiul** [comment]
@bradleyrichter would you mind specifying the latest mockup which #11231 should implement, to remove `QA/test-plan-required`? thanks!
