### ISSUE TITLE
Sync reset modal buttons need padding 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11195]
### Description
![image](https://user-images.githubusercontent.com/17010094/30951170-1f2a37b2-a43f-11e7-91ea-e2855bbeb0b2.png)

### Steps to Reproduce

  1. Enable Sync
  2. Click on `Reset Sync` 
  3. Conformation modal buttons don't have spacing

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.20
-- | --
rev | d9566ab
Muon | 4.4.25

**Reproducible on current live release:**

### Additional Information

Unable to verify this on 3acca8dd8e826f56a32f30e9d8ca1c7477c1713b as the reset sync button causes the browser to hang

**Comment by bsclifton** [comment]
Removing milestone. The reviewer can add it back (if needed) when a PR is ready / being reviewed 😄

**Comment by luixxiul** [comment]
It was fixed for 0.20.x:
https://github.com/brave/browser-laptop/blob/0.20.x/app/renderer/components/common/messageBox.js#L93

duping to https://github.com/brave/browser-laptop/issues/9973
