### ISSUE TITLE
Bug, Brave leaks webrtc ip

### ISSUE THREAD

**Issue by nyancat18** [brave/browser-laptop#11206]
Connection: VPN

Shields: ON

Link: https://ipleak.net/

**Comment by luixxiul** [comment]
do you enable fingerprinting protection from the top right lion icon?

**Comment by nyancat18** [comment]
yeah

version 0.18.36

**Comment by luixxiul** [comment]
what do you see instead of this?

<img width="276" alt="screenshot 2017-09-29 3 19 36" src="https://user-images.githubusercontent.com/3362943/30983323-12364524-a4c5-11e7-8334-20d4fd45d8a1.png">

do you mind taking a screenshot?

**Comment by nyancat18** [comment]
ok
https://u.teknik.io/3mMtN.png

**Comment by luixxiul** [comment]
It shows webrtc is blocked. Are you really sure that you do see the private IP like this?

<img width="958" alt="screenshot 2017-09-29 3 35 16" src="https://user-images.githubusercontent.com/3362943/30984074-407c0674-a4c7-11e7-8af9-935086efe9ba.png">

**Comment by nyancat18** [comment]
nom  i see my real ip, instead of *private use*

or at least my  vpn ip

**Comment by luixxiul** [comment]
OK, then that is a correct behavior. Please remember you cannot hide an IP address when you surf, which is why some people use VPN / Tor to hide your own IP address.

If you see your VPN's IP address, it is exactly what you should see.

**Comment by luixxiul** [comment]
also please try this one, which is much more clean: https://browserleaks.com/webrtc

**Comment by nyancat18** [comment]
sorry


you're misunderstanding



>i see my **real** ip instead of my vpn ip

**Comment by luixxiul** [comment]
If you see nothing under `WebRTC Detection` row, it is OK.

If you see nothing on `Your public IP addresses:` on https://www.privacytools.io/webrtc.html, it is OK.

If you see something, let me know.

**Comment by nyancat18** [comment]
no

ith 0.19   i can see my REAL IP (instead of vpn ip)

**Comment by nyancat18** [comment]
afik  its related to #1310

**Comment by nyancat18** [comment]
and   i can say  (brave 019)  

https://www.perfect-privacy.com/webrtc-leaktest/  WORKS (10/10)   i cant see my ip

https://torguard.net/vpn-webrtc-leak-test.php work

ipleak.net NO NO NO NO NO  WORK  :)

you could test it *linux64*   +  *openvpn*

**Comment by luixxiul** [comment]
As long as other sites work, it is ok

**Comment by nyancat18** [comment]
but at ipleak.net no work

i've tried all (even changing userprefs) 
 "webrtc": {"multiple_routes_enabled": false}

i've putted this setup and i now get
>vpn ip
>REAL ip


before to do this i got
>vpn ip
>REAL IP
>REALIP

**Comment by nyancat18** [comment]
https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia

**Comment by luixxiul** [comment]
Please add a series of steps to reproduce the problem. See https://stackoverflow.com/help/mcve for in depth information on how to create a mimimal, complete, and verifiable example.

Describe the problem. "It doesn't work" is not a problem statement. Tell us what the expected behavior should be. Tell us what the exact wording of the error message is, and which line of code is producing it. Put a brief summary of the problem in the title of your question.

**Comment by robertobenzi** [comment]
nyancat18 is right, when you use ios 11  + a vpn + Brave browser with block script otion disabled, you encounter a Big webrtc Leak !
This problem can be verified  at : https://www.browserleaks.com or https://www.whoer.net
Most of other browsers have already fixed this failure , Brave's Team is adviced since 3 weeks and must react now.

**Comment by Jacalz** [comment]
@robertobenzi I think you got the wrong repository, this repository is for Linux, Windows and Mac versions of Brave. Browser-iOS is the repo for iOS 😉
The webrtc leak is a well known issue on iOS 11, please see: https://github.com/brave/browser-ios/issues/1148

**Comment by luixxiul** [comment]
> This problem can be verified at : https://www.browserleaks.com or https://www.whoer.net

It must have been verified on https://ipleak.net/, nowhere else.
