### ISSUE TITLE
favicons not displayed after import of bookmarks from Safari / Chrome

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11203]
### Description
I imported a small amount of bookmarks (7 bookmarks and 2 folders) from Safari. Favicons for the imported bookmarks were not displayed after being imported.

### Steps to Reproduce

  1. Have bookmarks set up in safari and verify you can see their favicons. Close safari.
  2. Import bookmarks from Safari.

**Actual result:**
Favicons were not displayed after import:
<img width="1012" alt="screen shot 2017-09-28 at 10 42 15 am" src="https://user-images.githubusercontent.com/28145373/30972875-c479490c-a439-11e7-87dd-8a25ec8a1bd1.png">

**Expected result:**
Favicons should be displayed after import of bookmarks.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.23
OS Release | 16.7.0
Muon | 4.4.25

**Reproducible on current live release:**
Yes, can reproduce on 0.18.36, back to 0.16.6

### Additional Information

cc: @kjozwiak

**Comment by darkdh** [comment]
`importer.on('add-favicons'` in app/importer.js is not being hit which means muon doesn't emit this event

**Comment by kjozwiak** [comment]
@NejcZdovc is this the same issue that I was experiencing in https://github.com/brave/browser-laptop/pull/10325#pullrequestreview-63469444? I believe it was fixed in that PR as well but I could be wrong.

@LaurenWags can you see if this is happening in the `0.20.x` branch?

**Comment by LaurenWags** [comment]
@kjozwiak still experiencing this with 0.20.6

**Comment by bsclifton** [comment]
+1 from @comodoro via https://github.com/brave/browser-laptop/issues/12996
> After install and importing bookmarks from Chrome everything imported correctly, but favicons have been the generic grey sheets without image. This is on the bookmarks toolbar as well as the bookmarks menu. 
>
> Current Brave 0.20.30, Windows 10.
>
> ![image](https://user-images.githubusercontent.com/925466/35745886-1b5985c4-0845-11e8-8712-f3bdb7d3ea93.png)

**Comment by eljuno** [comment]
+1 from community. Imported from Chrome https://community.brave.com/t/bookmarks-bar-showing-as-a-list/24130?u=eljuno

**Comment by rebron** [comment]
Closing and marking wontfix. Reopen if still an issue in brave-core.
