### ISSUE TITLE
how to convert brave scripts to normal addons?

### ISSUE THREAD

**Issue by nyancat18** [brave/browser-laptop#11204]
addons just like  
blockcanvasfingerprinting  and blockflash

https://github.com/brave/browser-laptop/tree/master/app/extensions/brave/content/scripts

**Comment by bsclifton** [comment]
@nyancat18 are you asking if those two features for example are available as a separate Brave extension (available in the Chrome Web Store, for example)?

**Comment by nyancat18** [comment]
no

>scriptsafe offers some webgl  protection but sometimes fails

>webgl2 its exclusive

**Comment by luixxiul** [comment]
please read https://developer.chrome.com/extensions/getstarted

**Comment by bsclifton** [comment]
Closing issue as there is no action for us to take.  Let's keep discussing though- please do check out the link that @luixxiul shared 😄
