### ISSUE TITLE
Set bravery shields policy per subfolder

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11213]
### Description

Make it possible to set bravery shields per subfolder of a website. 

It has been possible to apply different shield settings between https://google.com and https://maps.google.com, yet it became impossible because maps.google.com is now redirected to https://www.google.com/maps.

You would have been able to set the strictest settings to https://google.com (Blocking scripts and all cookies) as you used that site just for searching something. These settings break https://www.google.com/maps and you are requested to enable them when you go to /map, and you will need to revert the change on https://google.com.

I could imagine Google would change other sites' address in the same way. eg. https://google.com/music, https://google.com/keep etc., which do not exist yet.

### Steps to Reproduce

  1. Open maps.google.com

**Actual result:**

On brevery shields the same setting on `google.com` is applied

**Expected result:**

Set an option `Allow setting per subfolder`  on about:preferences#shields

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by luixxiul** [comment]
The same problem is applied to Geolocation too. By allowing Geolocation on https://google.com/maps, you allow it on https://google.com/ as well.

**Comment by flamsmark** [comment]
Not going to implement this because it doesn't mesh with the way that web security and origins work in general.
