### ISSUE TITLE
Check for updates opens new tab

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#11221]
### Description
If you select Check for Updates from the menu bar, a new tab is opened. It does not happen if you select Check for Updates from the kabob menu.

### Steps to Reproduce
  1. Open Brave.
  2. Select Menu bar > Brave > Check for Updates

**Actual result:**
A new tab is opened.

**Expected result:**
A new tab should not open.

**Reproduces how often:**
100% reproducible

### Brave Version

**about:brave info:**

Brave: 0.19.24 
rev: 3b3fba2074395acb60954629a429b2d03d777f4a 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Reproducible on current live release:**
No, I don't think so.

### Additional Information
Probably macOS-only. I think it started happening in the last few 0.19.x builds.

**Comment by bsclifton** [comment]
Problem was introduced here:
https://github.com/brave/browser-laptop/commit/008fdd41aae72a730a80ae55ce652185da9317cb

**Comment by bsclifton** [comment]
0.20.x https://github.com/brave/browser-laptop/commit/f673a86c2373b6357c42a4286a77cea734e266a9

**Comment by bbondy** [comment]
Modified fixed here:
0.19.x: 64b14034ecc28c3858da38b9d4e02e7f89ba52e3
0.20.x: 7a067d1359854cc806e7d25cb83ab798be1c5871
master: 643c14c576ab2fef30ebe3ff16f9ab22f06b96fb
