### ISSUE TITLE
Customization idea: advanced custom.css option

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1122]
That one would be also nice to have in Brave, as both Brave and Vivaldi have a non native UI. With the help of custom.css you can for example add numbers in front of the tabs, change the UI color, place bars to the very bottom of the browser, or to left or right of the browser vertically.

Would be nice if Brave offers the same amount of customization for the user, with adding additional CSS lines to such a user defined file.

**Comment by 64py** [comment]
Would wish something like this existed in brave. I know firefox/chrome have an addon called stylish. Basically gives you full control changing CSS stuff etc.

**Comment by SJ-Diamond** [comment]
Pretty sure this can be done, as the UI is basically not really hard coded same like in Vivaldi, so you could change how the browser looks and you could change how elements are located with such a file and proper CSS code.

**Comment by justanironic** [comment]
I'd definitely love to edit the UI, not a fan of how brave looks at the moment and I'd love to rice it.

**Comment by 1337Nerd** [comment]
One of my favorite things about Firefox is ricing and I would love to be able to do the same on Brave.

**Comment by ronilaukkarinen** [comment]
+1 for this. I love the Safari-like UI of Brave, but would like to tweak a little bit more. For example identical width for tabs would be the cherry on top of the cake.

**Comment by bsclifton** [comment]
When moving to [brave-core](https://github.com/brave/brave-browser), we'll lose the HTML/CSS/JavaScript UI that we have now (implemented using Muon). Closing this issue as the UI will be native (C++) in brave-core
