### ISSUE TITLE
pinning a tab leads to previous tab to be wrapped as pinned too

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#11220]
SHA c5a903cc2672577a41fdf8ad070aec245ecaa367

STR:

1. Open 3 tabs
2. Pin far-right tab
3. tab next to pinned one becomes smaller, `inspect` shows them all wrapped around element w/ `.pinnedTabs` class. Next tab is not pinned but still child of wrapper element

This is failing several pinned tabs tests

setting as `needs-investigation` to check if previous versions were affected too

**Comment by luixxiul** [comment]
@cezaraugusto do you think this issue has the same root cause as #11205?

**Comment by cezaraugusto** [comment]
correct they're related

**Comment by cezaraugusto** [comment]
not happening w/ sha 5af92b45b74572ad3d8a49c8416015114d7763f2 (current 0.20.x latest) so I'm closing for now.

**Comment by luixxiul** [comment]
Added to 0.20.x for QA 😄
