### ISSUE TITLE
Contribution Notification being cut off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11224]
### Description

Contribution Notification being cut off. Copied from https://github.com/brave/browser-laptop/pull/11037#issuecomment-333236594
### Steps to Reproduce

  1.launch brave, enable payments and close brave once the wallet has been created
  2.`run npm run add-simulated-payment-history 50`
  3.re-open brave

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

![image](https://user-images.githubusercontent.com/9574457/31051510-6a29cf5c-a66a-11e7-9c53-88cfa747c8be.png)

**Comment by luixxiul** [comment]
I am wondering if it is duping to #11201

**Comment by NejcZdovc** [comment]
@luixxiul not sure

**Comment by bsclifton** [comment]
@luixxiul does your fix from https://github.com/brave/browser-laptop/pull/11202 also fix this issue?

**Comment by luixxiul** [comment]
Yes, it fixed this one as well.
