### ISSUE TITLE
Refactor drag and drop bookmarks to be done in store

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11226]
This is not working properly after the Redux refactor.  There was a temporary fix to hold us over in 0.19.x

**Comment by cezaraugusto** [comment]
removing release/blocking label as all boomark dnd features are working now. please add it back if I'm wrong.

will leave it open as it's still a better take than what we have but shouldn't block a release.

**Comment by bsclifton** [comment]
Moving to 0.22.x
