### ISSUE TITLE
Manually entered value is not retained for publisher

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11238]
### Description
Manually entered value is not retained for publisher

### Steps to Reproduce

  1. Build from ad111f2fa4cbe95a8dece4153ef5704ac222835a and create a clean profile
  2. Visit couple of sites to add to list and pin all of them
  3. Manually change one of the site % to 3, doesnt retain the entered value, instead recalculates the % for all pinned publishers 

**Actual result:**

![ledgerrefactor](https://user-images.githubusercontent.com/17010094/31081856-183c513a-a785-11e7-998b-19e88351b027.gif)

**Expected result:**
manually entered value should be retained and other pinned publisher values should be recalculated 
to bring to 100%

**Reproduces how often:** [What percentage of the time does it reproduce?]
consisten
### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | 233dae1
Muon | 4.4.25

**Reproducible on current live release:**

No, retains value entered

**Comment by NejcZdovc** [comment]
this is not a bug, it's designed like this. We only retain value when pinned publisher sum is over 100%. Changing this to the suggestion

**Comment by luixxiul** [comment]
we could display a tooltip / warning which says "please make the sum more that 100%". Obviously we do not want to see that modifying one value of a bunch of sites changes every favorite site's value. We also cannot redo anything on that table, including deleting sites (see https://github.com/brave/browser-laptop/issues/11164 https://github.com/brave/browser-laptop/issues/4634#issuecomment-332379472).

**Comment by NejcZdovc** [comment]
Agree that we can improve this functionality, the only thing that I am saying is that this is not a bug

**Comment by NejcZdovc** [comment]
+1 from https://www.reddit.com/r/BATProject/comments/7sc5qp/trying_to_adjust_payment_percent_seems_to_be/

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.

**Comment by srirambv** [comment]
Verified on 0.21.16

**Comment by kjozwiak** [comment]
Before going through verification, I reproduced the original issue using `0.20.30` 8b78402e7b3b91d44d8146cbe4dc8013592c33fd with the STR that @LaurenWags provider above.

Verified using `0.21.18` 580be782bc37ed8580dd22f79e1d2d355fddfb89 under Ubuntu 17.10 x64.
