### ISSUE TITLE
Open preferences screen in a new window (configurable - default off)

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1123]
Not all users like to have the settings opened in a new tab. If it would be easily to implement for you guys, it would be cool to have the additional option to have settings also in a special window.

**Comment by bbondy** [comment]
Thanks for posting but we're going to stick with preferences in a tab for now.   All of the browser level content will be the same way implemented via about:* pages, so for consistency sake we want to keep it the same.  If there is a very big use case to change it that you think a tab is missing, then we can reconsider, but otherwise I'm closing this for now since I wouldn't want anyone to spend time on something we would't accept as a pull request.

**Comment by bbondy** [comment]
Will re-open for these reasons:
- Takes focus away from active tab
- Could be easier to find than mixed in with tab.

Would like more feedback of pros / cons before considering a change though.  Also low priority to change  if we do based on other things we need.

I still prefer in tab non modal windows though.

**Comment by SJ-Diamond** [comment]
Opening this request was not meant to ask for a change - just for adding a checkbox for people who would want something like that. As some of you also have been thinking about offering a checkbox for shrinking tabs for people who love that, i guess, one more checkbox like that in the future would do no harm.

Different users, different workflows. The more choice you offer, the more users you will get.

**Comment by Arandhras** [comment]
I don't know how much of the current UI code for the options window could be used in a new, dedicated window; in the case it is possible to share most of all of it, this could be a nice addition.

**Comment by Emperor-Lestat** [comment]
I would love to see a special check-box for this. Because when i want to open the options i do not want to be dragged away from the tab i am visiting right now.

So, count another vote in favor of having a function like that. Not as standard of course, but for the users who want it that way.

**Comment by Emperor-Lestat** [comment]
I would love to see a special check-box for this. Because when i want to open the options i do not want to be dragged away from the tab i am visiting right now.

So, count another vote in favor of having a function like that. Not as standard of course, but for the users who want it that way.
