### ISSUE TITLE
Verified publisher icon shown only after tab focus changes

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11248]
### Description
Verified publisher icon shown only after tab focus changes

### Steps to Reproduce

  1. Clean build from master
  2. Enable payments
  3. Visit brianbondy.com, keep the tab active, Verified publisher icon is not shown
  4. Switch focus to other tab and com back to brianbondy.com, shows verified publisher icon in URL

**Actual result:**

Verified publisher icon shown only after tab focus changes
**Expected result:**
Should show the icon when criteria is met
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | de5f381
Muon | 4.4.25

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
we only show verified status after page is added to the ledger table. To trigger adding site to the ledger table you need to change focus, visit new site, open new tab, etc. Closing as this is expected behaviour
