### ISSUE TITLE
Publisher list not shown when min visit is changed to different value

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11247]
### Description

Publisher lilst not shown when min visit is changed to different value

### Steps to Reproduce

  1. Clean build from master
  2. Enable payments
  3. Visit any site ensure its added to the list
  4. Change min visit to 5 from 1
  5. Visit a new site in a new tab, visit more than 5 times in a new tab each time, site is not added to list
  

**Actual result:**
Publisher list not shown when min visit is changed to different value

**Expected result:**
Should add publisher when criteria is met 

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | de5f381
Muon | 4.4.25

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
I think this is not related to this setting, but on general adding sites via new tab. I tried visiting sites, by actually visit different site and it's added to the ledger even when you change this setting. Closing for now, if you thing that there is something different going on, please reopen it. Recording sites with new tab (not recorder every single time is a know bug)
