### ISSUE TITLE
Hide lower button hides all entries in ledger table

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11246]
### Description

Show lower hides all entries in ledger table
### Steps to Reproduce

  1. Enable payments on 0.19.25
  2. Visit sites to get entries in ledger table and show the hide lower button
  3. Click hide lower hides all entries
  4. Include/exclude some entries, click hide lower, all entries are hidden
  5. Repeat step 5 for other entries some may show up when you click hide lower 

**Actual result:**

![showlower](https://user-images.githubusercontent.com/17010094/31129592-ef4f0baa-a84c-11e7-87c8-e2ffbfcd85dc.gif)

**Expected result:**
Should always show enabled entries irrespective of hide/show button toggle

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.25
-- | --
rev | d4fd17a
Muon | 4.4.25

**Reproducible on current live release:**

Not checked
### Additional Information

cc: @NejcZdovc @cezaraugusto

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/be048b8835a681175178c720bb5e203767bb6505
