### ISSUE TITLE
Tab colour has weird fade in paint effect when switching

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11249]
### Description

Tab colour has weird fade in paint effect when switching

### Steps to Reproduce

  1. Build from master
  2. Visit brianbondy.com, tab colour has weird paint effect
  3. Open any about page, same weird effect

**Actual result:**

![tabcolour](https://user-images.githubusercontent.com/17010094/31134606-7af28f4e-a85a-11e7-9d7d-cda0486cf8dc.gif)

**Expected result:**
Should paint entire tab 

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | de5f381
Muon | 4.4.25

**Reproducible on current live release:**

No
### Additional Information

cc: @cezaraugusto

**Comment by luixxiul** [comment]
how weird is it?

**Comment by srirambv** [comment]
Its pretty obvious and doesnt look good. May be not very noticeable in the gif image. Dark tab colour makes it more prominent because of the light tab colour

**Comment by srirambv** [comment]
Here's a better recording
![tabcolour1](https://user-images.githubusercontent.com/17010094/31135027-bd97327c-a85b-11e7-8a0e-8bd218498a1f.gif)

**Comment by luixxiul** [comment]
That kind of fading effect is intentional I think. Do you think it is too slow or something?

**Comment by luixxiul** [comment]
This is on macOS. Though it looks not good with this gif image, it actually is rendered naturally.

![tab](https://user-images.githubusercontent.com/3362943/31135156-26dafd0c-a89f-11e7-8753-43895aaf792b.gif)

**Comment by srirambv** [comment]
Never seen that fade-in effect till now. But its definitely not looking good on Windows. Sometimes the colour paints slow on the close tab button so it looks really bad. may be fade-in from centre would be a good idea rather than fade-in from left that way it evens out the effect on the close button as well

**Comment by srirambv** [comment]
cc: @jenn-rhim @bradleyrichter

**Comment by luixxiul** [comment]
If the perf issue was confirmed on Windows globally, we could turn off the fading effect on Windows. We would not have to disable it on macOS as well. CC @cezaraugusto https://github.com/brave/browser-laptop/pull/10691

**Comment by cezaraugusto** [comment]
it is intentional how it looks now but I'm open for improvements. If there's a "slow" feeling on Windows please let me know. Deferring UX decision to design team.

**Comment by srirambv** [comment]
Its definitely looks bad on Windows and its quite noticeable and isn't appealing. It definitely needs some rework for Windows

**Comment by luixxiul** [comment]
It might be well rendered with a better graphic card on board.

**Comment by cezaraugusto** [comment]
thanks I'm taking let's make it better

**Comment by petemill** [comment]
Correct me if I'm wrong, but I'm guessing the issue here is the difference in speed fading from the background color, and the background color of the right edge, which is different and changes instantly. The right edge is different because in the current implementation it is used to fade out the text when the title text is too long. This is solved (mostly) by #12565 .

By the way, you can see this even more obviously by slowing down animations in devTools. Open the 'animations' panel, and hit '10%'. Then change active tab, especially between a dark one (like the New Tab page)...

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
