### ISSUE TITLE
Updating installed extension

### ISSUE THREAD

**Issue by walshie4** [brave/browser-laptop#11254]
### Steps to Reproduce

  1. Install browser, Honey is 9.7.7  Latest per mentioned download link is 10.4.0

**Actual result:**
9.7.7 listed as Honey version

**Expected result:**

Auto-update or have option to manually trigger update

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 16.7.0
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Hi @walshie4- thanks for the report.  We control the updating of extensions and are due for an upgrade.  I'll review with team and report back

**Comment by bsclifton** [comment]
I updated some of the extensions last nite- @jonathansampson will be helping check out Honey and the others (1Password, etc) 😄  Hang tight!

**Comment by bsclifton** [comment]
@walshie4 I updated the extension via https://github.com/brave/vault-updater/commit/a08520dc073f7cdef685fdc25c0061d6781390b7.  You should see an update soon 😄   Please let me know if you have the new version (which should be 10.5.1)
