### ISSUE TITLE
ledger notification should appear above the tab area

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11256]
ledger notifications are appearing in the tab area instead of above it. this is not ideal because:
1. they are browser notifications, not tab-specific notifications. i.e., if you change tabs, the notification still appears.
2. they can be spoofed by an attacker webpage if they are in the tab area

![screen shot 2017-10-03 at 5 49 53 pm](https://user-images.githubusercontent.com/549654/31140318-962df27c-a863-11e7-984c-90eacac61c6c.png)

expected behavior: browser notifications that are not tab-specific should appear above the tab strip, like the update notification for example:
![screen shot 2017-10-03 at 5 53 38 pm](https://user-images.githubusercontent.com/549654/31140434-e0c91d98-a863-11e7-8631-df165a84f83a.png)

 
Brave: 0.19.27 
rev: e7f3a69f10bb7688841947efe56c302ed2f8d1dd 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 15.6.0 
OS Architecture: x64

cc @cezaraugusto @NejcZdovc

**Comment by diracdeltas** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
@diracdeltas yes...absolutely.

see also: https://github.com/brave/browser-laptop/pull/11265

**Comment by diracdeltas** [comment]
moving the milestone to 0.19.x based on what @luixxiul set for https://github.com/brave/browser-laptop/issues/8934

**Comment by bsclifton** [comment]
@diracdeltas @bradleyrichter is this a blocker for 0.19.x / the BAT Mercury launch?

**Comment by bradleyrichter** [comment]
@bsclifton Can't we just define it correctly to use the same alert bar as the update notification?
