### ISSUE TITLE
Console error when opening page tools for about pages

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11253]
### Description

Console error when opening page tools for about pages
### Steps to Reproduce

  1. Upgrade to 0.19.27
  2. open any about page and open page dev tools (F12)
  3. console throws error

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31138530-ba007442-a866-11e7-88e3-70b8b3d3e00f.png)

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.27
-- | --
rev | e7f3a69
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

No
### Additional Information

cc: @bridiver @bsclifton

**Comment by kjozwiak** [comment]
Reproducible on all three platforms using the above STR. If you don't get the error right away, use the following STR:

* launch brave via `/Applications/Brave.app/Contents/MacOS/Brave --console-log`
* open about:about and open several about: pages in new tabs
* switch through each one and launch the page devtools via keyboard shortcut

You'll eventually see the following as @srirambv mentioned above:

`[45583:33283:1003/135524.650737:ERROR:extension_protocols.cc(360)] Allowing load of chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/gen/aboutPages.entry.js.mapfrom unknown origin. Could not find user data for request.`

* Win 10 x64 - Reproduced
* macOS 10.12.6 x64 - Reproduced
* Ubuntu 16.04 x64 - Reproduced

**Comment by bridiver** [comment]
console errors can be mostly ignored unless they are associated with an actual problem. The `.map` file just maps the webpack aboutPages.entry.js to the source files lines for debugging

**Comment by bridiver** [comment]
there is actually a more much important error here which is the failure to open the web database. That error indicates that you have another instance of Brave running that has it locked

**Comment by bsclifton** [comment]
This has been resolved 😄
