### ISSUE TITLE
default value for 'Minimum page time before logging a visit'

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11258]
### Description
In 0.18.x the default value for 'Minimum page time before logging a visit' was 8 seconds. In 0.19.27 it is showing as 5 seconds.

### Steps to Reproduce

  1. Enable payments in 0.19.27.
  2. Open Advanced Settings.
  3. Minimum page time before logging a visit is set to 5, should be 8.

**Actual result:**
Default value is 5s.
![minimumpagetime01927](https://user-images.githubusercontent.com/28145373/31141888-aef05d4e-a846-11e7-82e6-62e395886790.gif)

**Expected result:**
Default value should be 8s, not 5s.
![minimumpagetime01836](https://user-images.githubusercontent.com/28145373/31141815-6c5f95a8-a846-11e7-936b-3a1c0bc70d43.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.27
rev | e7f3a69
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information

Reproduced by @srirambv on Windows.
cc @kjozwiak

**Comment by NejcZdovc** [comment]
fixed with be048b8835a681175178c720bb5e203767bb6505
