### ISSUE TITLE
sometimes Payments is hanging on creating wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11252]
### Description
When updating 0.18.36 to 0.19.27, if you did not have payments enabled, on 0.18, you will sometimes hang when creating a wallet on 0.19.27.

### Steps to Reproduce

  1. Install 0.18.36. Visit a couple of sites, etc. Do not enable payments.
  2. Close 0.18.36.
  3. Manually install and launch 0.19.27.
  4. Open about:preferences#payments.
  5. Enable payments.
  6. hanging on creating wallet.

**Actual result:**
Stuck on creating wallet.
![screen shot 2017-10-03 at 12 36 48 pm](https://user-images.githubusercontent.com/28145373/31137463-592231ec-a839-11e7-89b9-c03f0bcd3a8d.png)

**Expected result:**
Wallet should be created.

**Reproduces how often:** 
unknown - maybe 50% of the time

### Brave Version

**about:brave info:**
Brave | 0.19.27
rev | e7f3a69
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information

Confirmed repro by @srirambv on Windows. I reproduced a couple of times on MacOS, but not every time.

**Comment by LaurenWags** [comment]
I'm also experiencing this (sometimes) on a clean profile in 0.19.27 intermittently.

**Comment by LaurenWags** [comment]
could not reproduce on bat-integration branch.

**Comment by NejcZdovc** [comment]
@LaurenWags closing for now, if you see it again when bat is merged, please re-open it

**Comment by srirambv** [comment]
Not seeing overlay but shows normal wallet creation . Doesnt hang as mentioned in original issue description
