### ISSUE TITLE
Anti-adblocker on Womenshealthmag.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11257]
**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31140405-35016fa2-a86c-11e7-91f7-9b3a9700e5a6.png)

**Expected result:**
Should not be blocked

**Comment by bbondy** [comment]
@srirambv pls include the URL for easy opening in addition to the screenshot for future reports like
 this. Thanks!

**Comment by bbondy** [comment]
Possibly fixed by https://github.com/brave/ad-block/commit/4360345f35efcbd0b314e874ba55c40ccb7f2230 if not please re-open this and move out of 0.19.x
