### ISSUE TITLE
keytar@3.0.0 breaks build on Ubuntu 14.04

### ISSUE THREAD

**Issue by ritesh-pandey** [brave/browser-laptop#1126]
![screenshot from 2016-03-19 16 28 13](https://cloud.githubusercontent.com/assets/1433681/13898196/cc549822-edef-11e5-8cc7-27f2020cbd50.png)

`npm i` breaks on installing keytar@3.0.0

System
Ubuntu 14.04
Linux 3.16.0-44-generic
node v5.5.0
npm  v3.3.12

@diracdeltas May be you can help on this.

**Comment by bbondy** [comment]
Not sure why but I was able to npm install ok on my Ubuntu 14.0.4.

**Comment by ritesh-pandey** [comment]
Fixed
`libgnome-keyring-dev` was missing.
Thanks.

**Comment by diracdeltas** [comment]
@ritesh-pandey i suspected that would be the issue. i will mention it in the README for linux users, thanks.
