### ISSUE TITLE
Add 2 decimal places (rounded for display) to BAT wallet balance

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#11264]
![image](https://user-images.githubusercontent.com/13509546/31152176-cf4beb7c-a84f-11e7-8b24-f5f84bab8760.png)

The actual wallet balance may have 4 decimals but the display should be rounded to 2 decimals.

The monthly budget remains fixed.

CC @mrose17 @zentagonist

**Comment by zentagonist** [comment]
Updated the priority labels to reflect the guidelines from here:

*  P1 - Blocks development or testing. Product cannot run.
* . P2 - Crashes. Loss of data. Severe memory leak.
* . P3 - Major loss of function.
* . P4 - Minor loss of function. Workaround usually present.
* . P5 - Cosmetic. Spelling, copy, layout.

**Comment by kjozwiak** [comment]
Using the STR from https://github.com/brave/browser-laptop/issues/11264#issue-262611620, went through the following verifications:

* ensured that all the entries within the monthly budget are using two decimal places
* ensured that the account balance uses two decimal places
* ensured that the "pending funds" message is using two decimal places
* ensured that the "balance" under "Add funds to your Brave Wallet" is using two decimal places
