### ISSUE TITLE
'Allow contributions to non-verified sites' toggle doesn't do anything

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11261]
### Description
In 0.19.27 if you modify the 'Allow contributions to non-verified sites' toggle, nothing happens. You can save this change and it will be retained, but it doesn't seem to do anything.

### Steps to Reproduce

  1. Have some verified publishers in your ledger table.
  2. Open Advanced Settings.
  3. Switch the toggle to off. (nothing changes in your table.
  4. Select Done on the Advanced Settings window.
  5. No changes to ledger table.
  6. Reopen Adv Settings. 
  7. Your selection has been retained.

**Actual result:**
Changing the toggle doesn't appear to make any updates:
![pubtoggle01927](https://user-images.githubusercontent.com/28145373/31143389-37b910f4-a84b-11e7-9637-cc836cc2dd83.gif)

**Expected result:**
Was expecting the toggle to work as it did in 0.18.36:
![pubtoggle01836](https://user-images.githubusercontent.com/28145373/31143407-41730e42-a84b-11e7-8f00-a1b30d7a662a.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.27
rev | e7f3a69
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information

Reproduced by @srirambv although I believe he saw slightly different results.
cc @kjozwiak

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/be048b8835a681175178c720bb5e203767bb6505
