### ISSUE TITLE
URL Icon doesn't toggle include/exclude for non-verified publishers

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11263]
### Description
When payments are enabled, the URL heart icon doesn't work to toggle include/exclude if the publisher isn't Verified.

### Steps to Reproduce

  1. Have a mix of verified/not verified publishers in your ledger list.
  2. Navigate to a verified publisher site.
  3. Click on the heart icon. 
  4. Verify that the verified publisher is marked as include/exclude as appropriate.
  5. Navigate to another site where the publisher is not verified but the site is marked as include in the table.
  6. The heart icon is not yellow. Click on the heart icon, no change. (you can still toggle include/exclude from the ledger table).

**Actual result:**
![urliconnotworking01927](https://user-images.githubusercontent.com/28145373/31151426-671fe5d8-a865-11e7-8720-245a36094cd6.gif)

**Expected result:**
Clicking on the icon in the URL bar should work if the publisher is not verified as well as if the publisher is verified.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.27
rev | e7f3a69
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information

cc @kjozwiak

**Comment by LaurenWags** [comment]
cc @NejcZdovc

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/be048b8835a681175178c720bb5e203767bb6505
