### ISSUE TITLE
BAT browser-laptop integration security audit

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11262]
Adding https://github.com/brave/internal/issues/118 here so it can be added to the 0.19.x milestone. See that issue for subtasks.

**Comment by NejcZdovc** [comment]
closing as #118 is closed

**Comment by luixxiul** [comment]
how is #118 related with this issue?

**Comment by luixxiul** [comment]
also no-qa-needed?

**Comment by diracdeltas** [comment]
#118 is a duplicate, i only opened this issue here so it could be added to the milestone

**Comment by luixxiul** [comment]
ah, I understand it is not #118 of this repo but https://github.com/brave/internal/issues/118.
