### ISSUE TITLE
Min page time and min visit selections are not being saved in Advanced Settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11260]
### Description
If you update the Minimum page time before logging a visit and the Minimum visits for publisher relevancy drop lists in Advanced Settings, and go back into Advanced Settings, you can see that your selections were not retained.

### Steps to Reproduce

  1. Open Advanced Settings.
  2. Select a different value for one or both drop lists.
  3. Select Done.
  4. Reopen Advanced Settings.
  5. Your selections are not maintained.

**Actual result:**
![selectionsnotsaving01927](https://user-images.githubusercontent.com/28145373/31142483-6d92be62-a848-11e7-971e-826908e4a98d.gif)

**Expected result:**
Selections should be maintained as they were in 0.18.36:
![selectionssaving01836](https://user-images.githubusercontent.com/28145373/31142651-eaf7bbc8-a848-11e7-8f41-a561518fd916.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.27
rev | e7f3a69
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @srirambv on Windows.
cc: @kjozwiak

**Comment by kjozwiak** [comment]
This was reported as issue#6 in https://github.com/brave/browser-laptop/pull/11037#issuecomment-333236594 and should have been fixed as it wasn't mentioned in https://github.com/brave/browser-laptop/pull/11037#issuecomment-333279270.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/be048b8835a681175178c720bb5e203767bb6505

**Comment by LaurenWags** [comment]
Minimum visits for publisher relevancy is not saving. Gif is of update from 0.18.36 to 0.19.28, but this also happens on a clean profile with 0.19.28:
![minvisit](https://user-images.githubusercontent.com/28145373/31180691-45e72308-a8ed-11e7-8c2e-56b8dc98a438.gif)

I reproduced on MacOS, @srirambv repro'd on Windows.

**Comment by luixxiul** [comment]
confirmed on Debian

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/d266f64f1762a6a90b680dc70a738fdf4373dfda
