### ISSUE TITLE
Close tabs in the reverse order of being opened

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1127]
How to reproduce (Have around 30-40 tabs open as a whole):

1) open a new tab, go to some webpage
2) open from the same tab with middle click a link in another tab 
3) Click on a random tab from the ones you have open
4) Close the tab from step number 2
5) No matter which tab you have picked in step 3 you land at the tab from step number 1

Brave should stay with the tab of your choice, when you close a tab, but as steps mentioned above show, it does not work that way so far.

**Comment by alexwykoff** [comment]
Another user from support has a suggestion and has created the following gist: https://gist.github.com/Moeriki/8fc23f38d4caf19b4ad2b2f0045b7377

**Comment by bsclifton** [comment]
This was fixed quite a while ago 😄
