### ISSUE TITLE
Some sites are excluded by default even when auto-include is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11276]
### Description

Some sites are excluded by default even when auto-include is enabled
### Steps to Reproduce

  1. Clean install 0.19.28
  2. Enable payments
  3. Visit github.com in a new tab
  4. While page is loading, open new tab and visit a different site
  5. Both sites are added to list but github is excluded even though no settings are changed

**Actual result:**

Some sites are excluded by default even when auto-include is enabled

**Expected result:**

If criteria is met should add and include it

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.28
-- | --
rev | 08781a5
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
@srirambv We have exclusion list and if even we have auto suggestions on, if this page is on exclusion list we will add it as excluded. Same happens with facebook, twitter, youtube etc. Working as expected.
