### ISSUE TITLE
Adjacent tab looks lower when tab colour is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11277]
### Description
Adjacent tab looks lower when tab colour is enabled

### Steps to Reproduce

  1. Enable tab colour from tab settings
  2. Pin any tab
  3. Open preferences tab next to the last pinned tab
  4. Preferences tab look slightly unaligned with other tabs

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31192530-67f97530-a939-11e7-9f05-c4fb9879d45b.png)
![image](https://user-images.githubusercontent.com/17010094/31192543-707bb074-a939-11e7-9a38-de8b9bc125a8.png)

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.28
-- | --
rev | 08781a5
Muon | 4.4.25

**Reproducible on current live release:**

Yes 
### Additional Information

Tab colour is filled inside the tab border which makes it look unaligned with other tab
cc: @bradleyrichter @jenn-rhim @cezaraugusto

**Comment by luixxiul** [comment]
do you mean the grey border around the tab?

**Comment by srirambv** [comment]
Yes, its visible in the second image. There is thin grey line border in tab and the tab colour fills inside of that

**Comment by srirambv** [comment]
This is more evident on 0.20.x and quite distracting. 
![image](https://user-images.githubusercontent.com/17010094/32513382-f7253b2c-c3f1-11e7-80cf-16702b31f20f.png)

cc: @bradleyrichter

**Comment by srirambv** [comment]
This is how it looks magnified at 200%
![image](https://user-images.githubusercontent.com/17010094/32513558-6fbd605a-c3f2-11e7-921a-b9a2944b49cc.png)
