### ISSUE TITLE
Netflix doesn't autoplay

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#11270]
### Description
When starting a stream in Netflix, the user has to click play. 

### Steps to Reproduce
  1. Go to Netflix with a clean profile
  2. Try to start playing a show or movie

**Actual result:**
The show doesn't autoplay.

**Expected result:**
The show should autoplay.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**
This was introduce with autoplay settings, but is still present in 0.19.27

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Is this a dupe of https://github.com/brave/browser-laptop/issues/11069?
