### ISSUE TITLE
Convert tabs bar with Aphrodite to remove tabs.less

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11272]
### Description

Refactor tabs bar to remove `tabs.less`.

### Additional Information

It would be appreciated if #10686 would be based on this task. CC @petemill

**Comment by petemill** [comment]
Moved to milestone 0.22.x due to requiring it for a clean merge of #12565 and the same / similar test plan for that version.

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
