### ISSUE TITLE
ledger table data is not cleared properly

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11278]
### Description
Ledger table data is not cleared properly when clearing Browser History with Payments Disabled.

### Steps to Reproduce

  1. Have a ledger with some entries (some included, some not included).
  2. Note views/amt of time spent for a couple of sites.
  3. Disable payments.
  4. Go to about:preferences#security, click on Clear Browsing Data Now, enable toggle for 
  5. Browser History, click Clear
  6. Enable payments.
  7. Table is blank as expected.
  8. Visit one of the sites you noted that was marked as include. 
  9. Note as soon as the page loads (prior to default value of 8s) your URL heart icon is yellow indicating it is in the table.
  10. Go back to Payments (you might have to refresh due to another issue)
  11. Your site is listed in the table with similar visit#/time spent as prior to clearing data. I was expecting the counters to start over.
  12. Repeat with another site that had been in the table prior to clearing Browser History. You will see a similar result.

**Actual result:**
![ledgernotrestartingat0](https://user-images.githubusercontent.com/28145373/31193866-492e18e8-a913-11e7-9adb-40789d678bce.gif)

**Expected result:**
Since table data had been cleared, I was expecting the number of visits and time spent counters to reset. The amount of time of the gif above is less than 1.5 minutes, so it's not possible that I spent 4+ minutes on brianbondy.com and 2+ minutes on thepioneerwoman.com.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100% for me

### Brave Version

**about:brave info:**
Brave | 0.19.28
rev | 08781a5
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information

Reproduced by @srirambv on Windows
cc @kjozwiak 

Ledger table data prior to clearing browsing history:
<img width="699" alt="screen shot 2017-10-04 at 2 27 30 pm" src="https://user-images.githubusercontent.com/28145373/31193994-bb6285d4-a913-11e7-876d-fdc0ecb1b80a.png">

Ledger table data after clearing browsing history and visiting two of the above sites. They're readded and retain some of the previous data:
![screen shot 2017-10-04 at 2 43 10 pm](https://user-images.githubusercontent.com/28145373/31194020-d1ad5044-a913-11e7-8f15-32d03b861774.png)

**Comment by srirambv** [comment]
Should ledger table be removed when browser data is cleared with payments disabled?

**Comment by NejcZdovc** [comment]
@srirambv yes this is current workflow
