### ISSUE TITLE
Copied text overlaps on the info message

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11289]
### Description
Copied text overlaps on the info message

### Steps to Reproduce

  1. Build on the `bat-integration` branch
  2. Enable payments
  3. Click `Add funds`
  4. Click any currencies button
  5. Click the clipboard icon to copy the wallet address,

**Actual result:**

copied text overlaps on the info text

![copy](https://user-images.githubusercontent.com/17010094/31219689-0434af1a-a9b6-11e7-9c58-554d69ea25cc.gif)**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | 2ca8815
Muon | 4.4.25

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
On which rev?

**Comment by srirambv** [comment]
Sorry thought had pasted the info. Updated issue

**Comment by cezaraugusto** [comment]
fixed in `bat-integration` branch thanks for reporting!

**Comment by luixxiul** [comment]
how the tooltip should actually appear?

**Comment by cezaraugusto** [comment]
at the top
