### ISSUE TITLE
bookmark "star" icon under URL not being updated right way when dragging and dropping

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11284]
### Description

When dragging and dropping a website into the "Bookmarks Toolbar" via the URL bar, the "star" bookmark icon under the URL bar won't be updated until either:

* refresh the tab
* switch to a different tab, return to the tab that was just bookmarked

### Steps to Reproduce

  1. launch `0.19.28` and enable the "Bookmarks Toolbar"
  2. visit any website, drag and drop it into the "Bookmarks Toolbar" via the "lock" icon

**Actual result:**

You'll notice that the "star" icon under the URL isn't being updated when the website is bookmarked via drag and drop.

![bookmarkupdate](https://user-images.githubusercontent.com/2602313/31213990-3035ac02-a977-11e7-89b5-0092a624dc4c.gif)

**Expected result:**

The "star" icon under the URL should be updated as soon as the website has been dropped into the "Bookmarks Toolbar"

**Reproduces how often:** [What percentage of the time does it reproduce?]

Reproducible 100% of the time using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.28 
> rev: 08781a596c1a0a461c8863692e4be51ebb3babf2 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 
> V8: 6.1.534.41 
> Node.js: 7.9.0 
> Update Channel: Beta 
> OS Platform: macOS 
> OS Release: 16.7.0 
> OS Architecture: x64

**Reproducible on current live release:**

This is working correctly under `0.18.36` and appears to be a recent regression in `0.19.x`.

**Comment by bbondy** [comment]
0.19.x: de2caca0786949178c753058010347562cb9a8bd
0.20.x: 8e97420d3da6f1116af835d3bca65aeeb86ef346
This is not landing on master because there's a big refactor going on there.

**Comment by kjozwiak** [comment]
This didn't land into `0.19.33`. However, I had the incorrect STR which made it seemed like it was fixed. Edited the original comment to include the correct STR.
