### ISSUE TITLE
Idea for tab pages: define keyboard shortcuts fro switching in a simple and fast way between pages

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#1128]
As the topic says, it would be good to have in the future the option to choose keyboard shortcuts which enables it to switch in a fast and efficient way between tab pages.

**Comment by bbondy** [comment]
I was just thinking about the same thing. Both going to prev / next and also things like CommandorControl+Number to go to that tab page, equivalent to tab navigation.

**Comment by SJ-Diamond** [comment]
Also, mousewheel scrolling between tabs would be a good option for switching between tabs/tab pages.

**Comment by amonks** [comment]
I'd love to be able to use page switching in conjunction with selecting tabs by number:

- [command-= (or something)] to advance to the next page
- [command-5] to select the fifth tab *on that page*

**Comment by luixxiul** [comment]
Closing this in favor of #1374
