### ISSUE TITLE
Missing text in BAT add funds modal

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11285]
### Steps to Reproduce

  1. Build from https://github.com/brave/browser-laptop/tree/bat-integration
  2. Enable payments
  3. Click add funds
  4. Text missing as to what to do

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31214885-1cc6eb9e-a9a5-11e7-99fc-44f4c473b275.png)

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
fixed in #11231

**Comment by luixxiul** [comment]
what should the test be?
