### ISSUE TITLE
Quit brave with more than one window, reopen only opens the last active window

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#11286]
Searched for "quit brave with more than one window, reopen only opens the last active window" on Github issues and Google.

### Steps to Reproduce
  1. Set tabs to open from where I left off.
  2. Open a second window. Take note of which tabs are open in which windows (have different tabs to differentiate between them).
  3. Quit brave. In Ubuntu 17.04, right click the Brave icon in the launcher, click "Quit".
  4. Reopen Brave.

**Actual result:**
Brave only opens the last active window, i.e. the Brave window that you last clicked in, with those tabs from where you left off.
**Expected result:**
Brave opens all previous windows with all tabs from where you left off.
**Reproduces how often:**
100%
### Brave Version
 
Brave: 0.19.24 
rev: 3b3fba2074395acb60954629a429b2d03d777f4a 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.10.0-35-generic 
OS Architecture: x64
**Reproducible on current live release:**
I haven't updated to the latest beta yet because it doesn't automatically prompt me to do that on Ubuntu (although it does on Windows). I've posted another issue about that [here](https://github.com/brave/browser-laptop/issues/11287)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bug-brave-starts-with-only-one-window-from-last-time-appears-instead-of-all-windows-windows-10/8796?u=eljuno

Windows 10

Brave: 0.18.36
rev: 7ab85e97318fef041433b0c3d73b457205fae805
Muon: 4.3.22
libchromiumcontent: 61.0.3163.79
V8: 6.1.534.32
Node.js: 7.9.0
Update Channel: dev
OS Platform: Microsoft Windows
OS Release: 10.0.15063
OS Architecture: x64
