### ISSUE TITLE
Recovery keys fail both manual/import

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11293]
### Description
Recovery keys fail both manual/import

### Steps to Reproduce

  1. Build from 2ca8815
  2. Enable payments and save recovery key
  3. Clear profile and launch new one
  4. Enable payments and import recovery keys from step 2
  5. Recovery fails

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31230491-19c2a21c-a9dc-11e7-9756-834318444435.png)

**Expected result:**
Should import successfully
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | 2ca8815
Muon | 4.4.25

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
fixed with #11231

**Comment by zentagonist** [comment]
Adjusting priority: 

* P1 - Blocks development or testing. Product cannot run.
* P2 - Crashes. Loss of data. Severe memory leak.
* P3 - Major loss of function.
* P4 - Minor loss of function. Workaround usually present.
* P5 - Cosmetic. Spelling, copy, layout.
