### ISSUE TITLE
Autocomplete search results show gibberish when typing non-ASCII characters

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#11297]
### Test plan
See https://github.com/brave/browser-laptop/pull/12173

### Description

Typing Å or Ä or Ö in the address bar just gets you jibberish text that is totally unreadable
### Steps to Reproduce

  1. Write in the address bar with these symbols
  2. See how it returns the symbols as jibberish

**Actual result:**

Text is jibberish, can see any of those letters in the suggestions
![image](https://user-images.githubusercontent.com/25466657/31236567-bbf75736-a9f4-11e7-8307-6570005378b8.png)

**Expected result:**
SHould see ÅÄÖ in the suggestions
**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time
### Brave Version
0.19.29 and beyond
**about:brave info:**

Name | Version
-- | --
Brave | 0.19.29
rev | c10b3ea
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

Yes
### Additional Information

You might need a Swedish keyboard to replicate

**Comment by luixxiul** [comment]
Could we close this in favor of https://github.com/brave/browser-laptop/issues/9139 ?

**Comment by Jacalz** [comment]
Is it exactly the same? I can´t tell

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
