### ISSUE TITLE
Transition the wallet from BTC to BAT

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11308]
### Description
For the BAT Mercury launch, we'll want to make a one time call from the client to initiate the transfer of BTC to BAT.

```
// create a new client:
newClient = ledgerClient(null, 
  underscore.extend({roundtrip: roundtrip}, clientOptions), null)

// do not persist newClient's state

// 2. on the existing client, call:
client.transition(newClient.properties.wallet.paymentId, (err) => {
  if (err) complain
  client = newClient
  // persist client's state, overwriting the old state      
})
```

**Comment by mrose17** [comment]
i've changed my mind on this. after reviewing the code, all we need to do is this on success in the callback:

        newClient.state.transactions = client.state.transactions
        client = newClient
        // persist client's state, overwriting old state

@bsclifton - can we do just that?

**Comment by bsclifton** [comment]
@mrose17 done! (see https://github.com/brave/browser-laptop/pull/11231/commits/deb0662cdbacf4b826420bdb6b587bc715837b1a)

Since that is acceptable, I closed https://github.com/brave/browser-laptop/issues/11307

**Comment by zentagonist** [comment]
Adjusting priority based on these guidelines:

*  P1 - Blocks development or testing. Product cannot run.
* P2 - Crashes. Loss of data. Severe memory leak.
* P3 - Major loss of function.
* P4 - Minor loss of function. Workaround usually present.
* P5 - Cosmetic. Spelling, copy, layout.

**Comment by NejcZdovc** [comment]
@zentagonist I think this is P1, because production can't run BAT payments without this transition fix

**Comment by NejcZdovc** [comment]
@luixxiul no need for triage, it will be fixed in the next hour. We will not release without it

**Comment by luixxiul** [comment]
or `no-qa-needed?`

**Comment by kjozwiak** [comment]
We've done several `0.18.36` -> `0.19.x` upgrades using the following test cases:

* install `0.18.36`, create a wallet and fund it with BTC
* Save the "Brave" folder and remove `0.18.36`
* install `0.19.x` and replace the "Brave" folder with the one from `0.18.36` (which includes the BTC wallet)
* ensure that you receive the "transition overlay" under `about:preferences#payments` while the wallet is being converted from BTC -> BAT
* ensure that the BTC was converted into BAT and appears correctly under the "Balance"

We also used the above test case with a $0 balance and ensured that the update worked correctly and the wallet was converted into a BAT wallet. We'll also go through these one more time with the RC build.
