### ISSUE TITLE
past contribution statements change when the ledger synopsis changes

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11306]
Brave: 0.19.29 
rev: c10b3ea2222ddf9325d359ccd973517cbe26ef38 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 15.6.0 
OS Architecture: x64

After updating to the latest beta, I noticed 2 issues in about:preferences#payments:

1. All my Brave contribution statements show $5 going to a single site. For instance this is the August contribution statement:
![screen shot 2017-10-05 at 11 47 52 pm](https://user-images.githubusercontent.com/549654/31257379-cc01d1aa-aa27-11e7-8173-ecb50c58b083.png)
I'm 99% sure that before this release, my contribution statements all had multiple sites.

2. The synopsis table also only shows one site
![screen shot 2017-10-05 at 11 50 28 pm](https://user-images.githubusercontent.com/549654/31257432-0083979c-aa28-11e7-9d4d-89c00c4e1ff2.png)

cc @bsclifton

**Comment by diracdeltas** [comment]
btw i had these settings turned on:
![screen shot 2017-10-06 at 6 39 09 pm](https://user-images.githubusercontent.com/549654/31293375-87604a6e-aac6-11e7-9c5d-48eddbe27a2f.png)

@NejcZdovc mentions that this behavior in 0.19.29 might be correct and the behavior prevoiusly was a bug. So perhaps this isn't a blocker

**Comment by zentagonist** [comment]
Adjusting priority labelling based on:

* P1 - Blocks development or testing. Product cannot run.
* P2 - Crashes. Loss of data. Severe memory leak.
* P3 - Major loss of function.
* P4 - Minor loss of function. Workaround usually present.
* P5 - Cosmetic. Spelling, copy, layout.

**Comment by NejcZdovc** [comment]
yes before 0.19.29 we had a bug because setting values were renamed, which @bsclifton fixed in 0.19.29. Advance settings weren't applied to the ledger table correctly.

**Comment by diracdeltas** [comment]
So probably the only bug here is that it seems very weird that my payment history has changed (the user would assume the payments are already done by the time they appear in the contribution statement)

**Comment by NejcZdovc** [comment]
they shouldn't change, so this is a bug for sure

**Comment by NejcZdovc** [comment]
not sure if related or not https://github.com/brave/browser-laptop/issues/11447. Pushing it back to 0.19 2, because we don't have STR

**Comment by alexwykoff** [comment]
Closing due to lack of STR or signal from support
