### ISSUE TITLE
Allow user to opt into a different search engine for private tabs

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11305]
### Description
The private tab screen should show a recommended search engine, which would apply only to private tabs if enabled.  It would go into the place where the red selection is in the screenshot below:
![screen shot 2017-10-05 at 11 10 20 am](https://user-images.githubusercontent.com/4733304/31245518-7fb531ba-a9bf-11e7-8471-424b972fa438.png)

The engine to use (and text to be displayed) is still TBD, but this could look something like this:
![screen shot 2017-10-05 at 11 24 59 am](https://user-images.githubusercontent.com/4733304/31245779-3c93b4fa-a9c0-11e7-9fc7-a8406820434c.png)

Since we don't have a way to do private windows, simply showing the toggle in the private tab should work great.  

In the future, we may allow the search screen to show (and allow changing) the search engine used for private tabs (see https://github.com/brave/browser-laptop/issues/11218)

### Open items
- [ ] Search engine to use
- [ ] Resources to use (SVG, icons, etc)
- [ ] Text to use / final mock up

**Comment by petemill** [comment]
I've done an initial implementation of this on a branch, using a random search provider (GitHub).

Question for @bradleyrichter - at the moment, when typing a search query in to the UrlBar, you only see the icon for the search provider when using a provider shortcut, e.g. ':a my search term'. i.e. you don't see Google's search icon, if that's your default. The way I've implemented this, when performing a default search in a private tab, and if you've opted in to a different private tab provider, you will see that provider's icon when typing a query. Do we want that? Do we want that for the default provider in non-private tabs too?

![brave-search-private-icon-vlow](https://user-images.githubusercontent.com/741836/31296874-c112a79e-aa98-11e7-9bd7-712c470f4a89.gif)

**Comment by bradleyrichter** [comment]
@petemill For non-private, I don't think the user would need to see a google icon every time they are typing. Only when you actively modify it with the shortcut.

I like the idea of showing it for Private Tab Search IF you have modified your private tab default. It's a nice reminder.

**Comment by petemill** [comment]
@bradleyrichter thanks - I'll keep as is implemented then

**Comment by petemill** [comment]
As discussed with @davidtemkin, the current thinking is:
- This will be an opt-in feature (off by default)
- There will be an item on the *Search* section of the *Settings* UI. It will go underneath the *Search Engine choice table*. This item will allow to turn on / off the "Use search engine XXX by default on Private Tabs"
- There will be more of a description, and the same settings toggle on the *New Private Tab* page (as in this issue's description above)

And there are no blockers to implementing this unless I hear otherwise.

**Comment by srirambv** [comment]
Blocked by #12207. Private tab is also blank
