### ISSUE TITLE
Rename instead of delete the old ledger-state file

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11307]
### Description
Per @mrose17:
> Instead of deleting then overwriting `ledger-state.json` on a successful callback from client.transition that the old file should be renamed and kept. We can get rid of it in a month or so, but for now, we should probably keep the file around to see what's in it that we need to worry about
>
> my guess is that we're probably going to have to copy over `transactions: []` and maybe something else

**Comment by NejcZdovc** [comment]
@bsclifton should we also keep old `ledger-synopsis.json` file just for a backup?

**Comment by bsclifton** [comment]
Closing as `wont-fix` after comment here:
https://github.com/brave/browser-laptop/issues/11308#issuecomment-334632244
