### ISSUE TITLE
Muted tab state lost after tear off

### ISSUE THREAD

**Issue by kevinlawler** [brave/browser-laptop#11304]
### Description

Muting a tab and then tearing it off causes the tab to start playing sound again. The image depicting the speaker state falsely indicates the tab is still muted.

### Steps to Reproduce

  1. Go to and address that plays audio, for example https://apple.news/AjVbOd78-SZSt_wI5JbhVqg

![screen shot 2017-10-05 at 11 17 15 am](https://user-images.githubusercontent.com/376238/31245555-946c6dbc-a9bf-11e7-8ca0-5ff15bb26d41.png)

  2. Mute the tab's sound using the speaker icon at the top

![screen shot 2017-10-05 at 11 17 41 am](https://user-images.githubusercontent.com/376238/31245564-9b3f1cca-a9bf-11e7-8bd4-1289a4c80462.png)

  3. Drag the tab to tear it off the current browser window, resulting in a new window

![screen shot 2017-10-05 at 11 18 13 am](https://user-images.githubusercontent.com/376238/31245572-a14d6716-a9bf-11e7-93cd-619b762d9897.png)

**Actual result:**

![copy](https://user-images.githubusercontent.com/376238/31245544-8ec394da-a9bf-11e7-97d9-cca5d6d26849.png)

**Expected result:**

Sound should not be playing.

**Reproduces how often:**

100% (macOS)

### Brave Version

Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**

Yes

### Additional Information

Tested on macOS using bluetooth headset.

**Comment by petemill** [comment]
This will be fixed with next muon build for 0.22.x-release3

**Comment by btlechowski** [comment]
Duplicated by #13979 

Verified on Ubuntu 17.10 x64
* 0.22.703 903b8d0d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.8
