### ISSUE TITLE
HTTPS Everywhere breaks lat.ms shortlinks

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11303]
### Description
HTTPS Everywhere breaks lat.ms shortlinks, via the enforcement of HTTPS.

### Steps to Reproduce
Navigate to lat.ms/2wAnkJF with HTTPS Everywhere enabled.

**Actual result:**
![image](https://user-images.githubusercontent.com/815158/31238916-fd553be6-a9c0-11e7-9501-c7e60cd4a444.png)

**Expected result:**
The user expects to be forwarded to the end-point.

**Reproduces how often:**
As long as HTTPS Everywhere is enabled on the origin.

### Brave Version
0.19.29

**about:brave info:**
 
Brave: 0.19.29 
rev: c10b3ea2222ddf9325d359ccd973517cbe26ef38 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Yes

### Additional Information
Disabling HTTPS Everywhere on the origin resolves the issue.

**Comment by ericlaw1979** [comment]
Upstream: https://raw.githubusercontent.com/EFForg/https-everywhere/5.2.10/src/chrome/content/rules/Bitly_branded_short_domains.xml

**Comment by diracdeltas** [comment]
This appears to be fixed now since https://lat.ms/2wAnkJFv resolves correctly

**Comment by luixxiul** [comment]
Added the nearest milestone to track QA.
