### ISSUE TITLE
Ad blocking detection + ad replacement on tomshardware.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#11312]
### Description

- On 64bit Windows10, observing ad blocking detection + ad replacement on www.tomshardware.com
- Ad blocking detected, Purch Calypso ads from Amazon display in-page. 
- Purch product, 300x600 | 300x1050 vertical (in right rail), or 600x300 | 1050x300 horizontal (center-aligned sectional ad slot. Ad slot contains 3-4 product tiles with clickthru URLs. 
- Will provide screenshots, request strings & sequencing. 

### Steps to Reproduce

  1. Go to tomshardware.com
  2. See the problem. 
  3. Want to fix the problem. 

**Actual result:**

**Expected result:**
No ads. No proxied consumer surveillance. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
- Consistently on desktop (win10). 
- Android appears to not have the same issue. 

### Brave Version
Latest w/prvw toggled. Will update with version info. 

**about:brave info:**

**Reproducible on current live release:**

**Comment by bbondy** [comment]
Possibly fixed by https://github.com/brave/ad-block/commit/4360345f35efcbd0b314e874ba55c40ccb7f2230 in the next build. If not, please re-open.
