### ISSUE TITLE
Open browser with a private session - enhancement suggestion

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1131]
The preferenes allow you to choose to open a new browser session on a homepage or a (non-private) tab. Please include the option to open the session with a private tab, or better yet include a preference option that all new tabs be private.

**Comment by luixxiul** [comment]
@bbondy Any plan or is this ongoing?

**Comment by luixxiul** [comment]
Duping to #597, thanks for your suggestion

**Comment by cfumante** [comment]
appreciate it....
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
