### ISSUE TITLE
Multiple homepage issue 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11317]
### Description
Multiple homepage issue 

### Steps to Reproduce

  1. Install 0.19.33
  2. Open settings, type **`,`** adds `%2C/` to the url
  3. delete the additional char and type **`|`** after https://brave.com, Adds the pipe operator before /

**Actual result:**

![multihomepge](https://user-images.githubusercontent.com/17010094/31296051-e3378ac0-aad8-11e7-9c93-5163abed6ce5.gif)

**Expected result:**
Should work properly
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.33
-- | --
rev | d0bface
Muon | 4.4.25

**Reproducible on current live release:**

Yes. Needs regression range
### Additional Information

#7442,

**Comment by NejcZdovc** [comment]
I fixed this one, but I forgot in which release, can you please try it with 0.20 and 0.21 :smiley:

**Comment by bsclifton** [comment]
yup- this is a dupe
