### ISSUE TITLE
Address bar doesn't understand dates

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11316]
### Description
Users are unable to search dates using the address bar.

### Steps to Reproduce
Type 11/10/2017 into the address bar and press <kbd>enter</kdbd>.

**Actual result:**
Brave navigates to http://0.0.0.11/10/2017

**Expected result:**
Brave navigates to https://www.google.com/search?q=11%2F10%2F2017

_The search engine used should be determined by the user's settings_.

**Reproduces how often:**
100% Repro

### Brave Version
0.19.30

**about:brave info:**
 
Brave: 0.19.30 
rev: 4ca2e2aab4a075336f848f0b401b305f3d72f637 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Yes

### Additional Information
- #4761

**Comment by bsclifton** [comment]
Verified this is fixed in [brave-core](https://github.com/brave/brave-browser) 😄
