### ISSUE TITLE
No keyboard shortcuts to re-order tabs

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#11310]
### Description
Re-ordering the tabs can only be done with the mouse. There are keyboard shortcuts to change which tab is active, but not to move tabs. Other browsers (such as Firefox on all platforms and Chrome on linux) use the ctrl-shift-pageup and ctrl-shift-pagedown to move a tab's index up or down.

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
