### ISSUE TITLE
1st party ads should be blocked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11315]
### Description
1st party ads should be blocked

### Steps to Reproduce

  1. Install 0.19.x build
  2. Visit YouTube and search for anything
  3. Ads shown before the search result. Clicking on it opens a YT video

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31279125-c2126a2e-aa9f-11e7-88e0-6592f82387e7.png)

**Expected result:**
Should block ads 
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**
Brave	0.19.30
rev	4ca2e2a
Muon	4.4.25

**Reproducible on current live release:**
No

### Additional Information

cc: @bbondy @lukemulks

**Comment by luixxiul** [comment]
duping to #344 ?

**Comment by srirambv** [comment]
Closing as not able to reproduce on packaged build and production build
