### ISSUE TITLE
File downloads not working

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#11326]
### Description
When saving a file, after confirming the macOS Save dialog, the download does not proceed, and OS-level browser functionality is disabled, such as the OS Brave menu -> Quit Brave

### Steps to Reproduce
- Choose a file to download (at atom.io)
- Save dialog pops up
- Press `Save` on dialog (`Cancel` also causes menus to grey out and become unavailable)

**Actual result:**

- Dialog disappears, but nothing happens, browser is still in the state that the dialog is there, e.g. menu items are greyed out, like Brave > Quit Brave
- Temporary download file which was created during dialog open is removed

**Expected result:**

- File is downloaded, and download bar shows

**Reproduces how often:** 100%
### Brave Version

 
Brave: 0.20.3 
rev: 10ec013c90047608f8e285e934a17a67ec69667f 
Muon: 4.5.3 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: developer 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Reproducible on current live release:**
No

**Comment by LaurenWags** [comment]
Reproduced by @aekeus on Linux, removed MacOS label.

**Comment by bridiver** [comment]
there are many different types of file download links, can you please provide a specific url?

**Comment by bridiver** [comment]
nvm, I was able to repro at brave.com download

**Comment by petemill** [comment]
@bridiver report description also mentions atom.io

**Comment by bbondy** [comment]
master: 36445285828d143fcdbdc0582d59e2d8c6e98553
0.21.x: 6169150d030355fcdde99fb1b679796a2655d002
0.20.x: 976f1cb2d0f3cc0577408f52d81abb7a43685723
0.19.x-c62: ff0e16acb2ab13fd0430d94111c87e5a9df47dc1
