### ISSUE TITLE
Setup fails on Windows x64

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11325]
### Description
Setup fails on Windows x64

### Steps to Reproduce

  1. Run setup for 0.20.3
  2. See error message during install
  3.

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31299240-655a1f0c-aae5-11e7-8efb-d6a798f2a1bd.png)

**Expected result:**
Should complete setup

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bridiver** [comment]
chrome_elf.dll is included in the dist and needs to be included in the packaged builds as well

**Comment by JMccormick264** [comment]
I am having this issue as well. Dev Channel Beta v0.20.3developer in releases

**Comment by bridiver** [comment]
fixed in muon dist, but might be other places it needs to be added

**Comment by kjozwiak** [comment]
Checked and ensured that 0.19.62 rev: fe3f350d2b5a014cde485b126788d3661e9f451a installed under the following platforms without any issues:

* Win 10 Pro x64 - PASSED (installed without issues)
* Win 10 Pro x86 - PASSED (installed without issues)
* Win 7 Pro SP1 x64 - PASSED (installed without issues)
* Win 7 Pro SP1 x86 - PASSED (installed without issues)

Build being used:

> Brave: 0.19.62 
> rev: fe3f350d2b5a014cde485b126788d3661e9f451a 
> Muon: 4.5.7 
> libchromiumcontent: 62.0.3202.62
