### ISSUE TITLE
Web notifications fails on CR62

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11327]
### Description
Web notifications fails on CR62

### Steps to Reproduce

  1. Clean Install 0.20.3 build
  2. visit http://www.bennish.net/web-notifications.html
  3. Click show notification, shows error 

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31300388-63b874ea-aaeb-11e7-83ce-6d5d44dd5987.png)

**Expected result:**
Should queue up notification
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.20.3
-- | --
rev | 1855f1a
Muon | 4.5.3

**Reproducible on current live release:**

No

**Comment by LaurenWags** [comment]
Reproduced by @zentagonist on MacOS, removed OS/linux-distros label.

**Comment by bridiver** [comment]
this appears to be a "feature". See devtools console output - "The Notification API may no longer be used from insecure origins". Everything works as expected if you go to `https://www.bennish.net/web-notifications.html`
