### ISSUE TITLE
LastPass account cannot be logged in

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11337]
### Description

LastPass account cannot be logged in. 

### Steps to Reproduce

  1. Install a build before 0.19.34
  2. Enable LastPass
  3. Log in
  4. Install 0.19.34
  5. Start the browser

**Actual result:**

You are logged out from the account, and you cannot log in to the account from the extension icon. Neither can you log in via the dialog (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html); you get the infinite loading icon.

**Expected result:**

The extension should be loaded properly.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

 
Brave: 0.19.34 
rev: d87b7caf57ae9d4aa88a275abca46b4a4619e34d 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

I'm not sure.

### Additional Information

After disabling and re-enabling the extension via about;preferences#security, the extension is no longer loaded properly.

![clipboard01](https://user-images.githubusercontent.com/3362943/31304924-c436f328-ab68-11e7-847b-77c007cc3d28.png)

**Comment by luixxiul** [comment]
CC @jonathansampson

**Comment by jonathansampson** [comment]
I'm not presently able to reproduce this, and I've been using LastPass daily on all builds of Brave that I install. I am currently on 0.19.37 as of this morning.

**Comment by bsclifton** [comment]
Moving to 0.19.x release 2

**Comment by luixxiul** [comment]
With the latest build, 0.19.39, that issue seems to have been fixed for me. Closing for now. I'll reopen this when I see that issue again.
