### ISSUE TITLE
Currency QR Code missing after upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11338]
## Test plan

https://github.com/brave/browser-laptop/pull/11395#issue-263840000

----

### Description
Currency QR Code missing after upgrade

### Steps to Reproduce

  1. Set browser to 0.18.36 and enable payments
  2. Upgrade to 0.19.34
  3. Click add funds in payment
  4. Click on currencies button, QR code is missing for all available currencies

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31305260-7fbc205a-ab2d-11e7-910c-a278ede31d81.png)

**Expected result:**
Should show the QR code 
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.34
-- | --
rev | d87b7ca
Muon | 4.4.25

**Reproducible on current live release:**

N/A
### Additional Information

cc: @NejcZdovc

**Comment by luixxiul** [comment]
Reproduced by me as well.

**Comment by NejcZdovc** [comment]
@srirambv but after a while (few minutes) you see correct data right?

**Comment by srirambv** [comment]
No have been using for about an hour and restarted twice but still no QR Code

**Comment by NejcZdovc** [comment]
@srirambv I just tried this scenario and I can't reproduce it. At the beginning there is blank QR, but after few minutes transition is done and everything is populated. If you still manage to reproduce it, please send me this profile, so that I can debug it.
