### ISSUE TITLE
Browser crash when allowing protocol handler

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11330]
### Description

Browser crash when allowing protocol handler
### Steps to Reproduce

  1. Clean install 0.20.3
  2. Login to gmail
  3. Cliick allow for protocol handler, browser crashes with segmentation fault

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31300662-c302fb2c-aaec-11e7-8a98-4d5f154bd5b0.png)

**Expected result:**
Should register protocol handler

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.20.3
rev | 10ec013
Muon | 4.5.3

Name | Version
-- | --
Brave | 0.19.33 
rev | d0bface89b0363ebdd528a2f67ffb382f0422d67 
Muon | 4.4.25 

**Reproducible on current live release:**
Yes

**Comment by bridiver** [comment]
this was introduced in 4.4 so shouldn't be labelled as cr62
