### ISSUE TITLE
Notification not shown after transition was triggered

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11333]
## Test plan

https://github.com/brave/browser-laptop/pull/11395#issue-263840000

----

### Description
For the BAT Mercury launch we are planning to show a notification that the funds get transferred from BTC to BAT. 

https://github.com/brave/browser-laptop/pull/11231 delivered most of this- the only problem is the notification is not shown.  The state needed to show the notification is only triggered after the transition has started... however the only place where these are checked is during launch

### Steps to Reproduce
- Have a bitcoin wallet (ex: use 0.18.x)
- Launch a BAT Mercury build using `LEDGER_VERBOSE=true` on command line
- Verify transition is triggered (this starts the process; it takes a while)
- Notice you are not shown alert

**Comment by kjozwiak** [comment]
Using the STR from https://github.com/brave/browser-laptop/issues/11333#issue-263601298, I went through the following verification under macOS 10.12.6 x64:

* ensured that clicking on "Back Up Your New Wallet" opens `about:preferences#payments?ledgerBackupOverlayVisible`
* ensured that clicking "Learn more" opens https://brave.com/faq-payments/#brave-payments and doesn't close the notification
* ensured clicking on "Later" closes the notification
