### ISSUE TITLE
Videos on gamespot.com cannot be played

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1133]
Certain sites give an error message

No video has been loaded
Error Code: PLAYER_ERR_NO_SRC

Not sure what player is involved. One siite with the problem is gamestop.com

**Comment by bbondy** [comment]
Please give an exact link to a video, thanks!

**Comment by cfumante** [comment]
Sorry don't have one, can't view the source.
 
However, the problem exists for all videos on gamestop.com , The
following lig will get you to one of the pages with a video that fails:
 
http://www.gamespot.com/articles/new-fallout-4-automatron-dlc-image-rele
ased/1100-6435808/
 
 
mahalo,
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by luixxiul** [comment]
Confirmed, still exists. On Chrome the video can be played by allowing "cdn.goroost.com" on Privacy Badger. CC: @diracdeltas

**Comment by diracdeltas** [comment]
It appears that the videos on gamespot.com all require Flash, so they can't be played in Brave even if the CDN is allowed through (it's not blocked in the first place AFAICT)

**Comment by luixxiul** [comment]
Closing for now in favor of #1093

**Comment by bbondy** [comment]
@luixxiul not sure if you are doing already but for any flash or plugin related issues just add it to the list here and close. Thanks!
https://github.com/brave/browser-laptop/wiki/Flash-and-Other-Non-Supported-Plugin-Sites-(Video-and-Non-Video)
