### ISSUE TITLE
Global Block scripts not functioning as expected

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11335]
### Description
Reported by @aekeus on Linux while testing 0.20.3 - Global Block scripts not functioning as expected, particularly for a site where shield settings had been modified previously (like brianbondy.com). 

### Steps to Reproduce

(same steps as in comment by @srirambv )
1. Enable block script globally
2. Visit brianbondy.com, site blocked
3. Disable scripts in shields, page loads
4. Disable scripts globally, should show site setting off exception
5. Delete site exception for block script
6. Enable global block script
7. Reload brianbondy.com, page loads no scripts blocked

**Actual result:**
Scripts are not blocked on brianbondy.com. Screenshot in comments.

**Expected result:**
Scripts should be blocked on brianbondy.com

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**
0.20.3

**Reproducible on current live release:**
no, not reproducible on 0.19.37 either.

### Additional Information

cc @kjozwiak

**Comment by luixxiul** [comment]
I thought it surely has been covered by travis :-o @diracdeltas

**Comment by bridiver** [comment]
I also marked this as "needs-info" because there are no steps to repro or actual/expected result

**Comment by srirambv** [comment]
STR 
1. Enable block script globally
2. Visit brianbondy.com, site blocked
3. Disable scripts in shields, page loads
4. Disable scripts globally, should show site setting off exception
5. Delete site exception for block script
6. Enable global block script
7. Reload brianbondy.com, page loads no scripts blocked

![image](https://user-images.githubusercontent.com/17010094/31394324-f04561ec-add5-11e7-830b-16e06c5b561f.png)

**Comment by bridiver** [comment]
the initial comment references 0.20.3. Is this reproducible on `0.19.x-c62` and not on `0.19.x`. I want to verify that it is really a cr62 issue and not something else in 0.20.x

**Comment by diracdeltas** [comment]
works as expected on mac on 13ab771a5869cd2c7d51f1194ffabc1a2180315f

**Comment by bridiver** [comment]
yea, I can't repro on mac either. The STR is also impossible to follow exactly because you can't delete the site exception when scripts are allowed globally

**Comment by luixxiul** [comment]
Is this not a same issue?

1. Open http://xxxblink.com/js/pops.test in a new private tab
2. The page is loaded
3. Open http://xxxblink.com/js/pops.test in a new normal tab
4. The page is blocked 

Expected result: the page should not be loaded in the private tab
