### ISSUE TITLE
Site favicon is not shown when bookmarked either dnd or bookmark icon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11341]
### Description
Site favicon is not shown when bookmarked either dnd or bookmark icon

### Steps to Reproduce

  1. Install/build 0.19.34
  2. Set bookmarks to show icon and title
  3. Visit any site and add bookmark via button , shows favicon on toolbar
  4. Delete bookmark and add by dnd the lock icon on toolbar, shows generic favicon, updates when visited
  5. Delete bookmark and add by clikig bookmark icon, shows generic icon, updates when visited

**Actual result:**

![11284](https://user-images.githubusercontent.com/17010094/31305676-43ec377c-ab37-11e7-872c-2d2cd8f291da.gif)

**Expected result:**
Should show the icon irrespective of how its added 
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.34
-- | --
rev | d87b7ca
Muon | 4.4.25

**Reproducible on current live release:**

No
### Additional Information

Found while  verifying #11284

**Comment by rebron** [comment]
Closing. wontfix.
