### ISSUE TITLE
Can't click on top bookmark inside folder on bookmark toolbar

### ISSUE THREAD

**Issue by csleary** [brave/browser-laptop#11345]
### Description

Bookmark toolbar folders: top bookmark inside bookmark folders can't be clicked properly. The cursor only highlights it at the very upper/lower edges, and doesn't highlight it at all in the center. Other bookmarks in the folder list don't have this problem; it's just the top one. Happens with both subfolders and bookmarks.

Instead, this area is treated as window chrome (i.e. double-clicking will toggle window resize).

### Steps to Reproduce

1. Add a folder to your bookmark toolbar.
2. Add more than one bookmark to this folder.
3. Try to click on the topmost bookmark.

### Brave Version

Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by bsclifton** [comment]
I've had a similar issue before in the past... it seems the hitbox isn't always detected properly.  What would happen is that the click wouldn't register unless I click past the half-way point of that first item.  The root cause (when I had looked at it before) was a nearby style had the draggable style set to true

**Comment by LaurenWags** [comment]
+1s from twitter:
https://twitter.com/InTrachimbrod/status/928760763556167680
https://twitter.com/rupaulstiltskin/status/928761603889213440

**Comment by eljuno** [comment]
Duplicate of #9088? It's been an issue for a while. :)

**Comment by luixxiul** [comment]
Closing as duplicate of #9088.
