### ISSUE TITLE
Remove SHORTCUT_ACTIVE_FRAME_FORWARD and SHORTCUT_ACTIVE_FRAME_BACK

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11346]
Both of them should be converted to an app action that accept a tabId. 
Use `TAB_ID_ACTIVE` in places like `main.js`where there is no tabId explicitly in the context.  
Handle these 2 new app actions in the `tabsReducer` and call into `app/browser/tabs`'s already available `goForward` and `goBack`.

**Comment by bsclifton** [comment]
Closing as `wontfix`. Moving to the new Chromium UI (Brave Core) will make this issue obsolete
