### ISSUE TITLE
Disable backup wallet button until wallet is ready 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11340]
## Test plan

https://github.com/brave/browser-laptop/pull/11395#issue-263840000

----

### Description

Disable backup wallet button until wallet is ready
### Steps to Reproduce

  1. Upgrade to 0.19.34
  2. Open payments
  3. Before wallet is converted, click on advance setting and click on back up wallet 
  4. No code words are shown

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31305383-8db90486-ab30-11e7-86f3-58b5e38684a8.png)

**Expected result:**
Should show an appropriate message or disable the button all together

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.34
-- | --
rev | d87b7ca
Muon | 4.4.25

**Reproducible on current live release:**

N/A
### Additional Information

cc: @evq @NejcZdovc

**Comment by luixxiul** [comment]
how about replacing its whole div wrapper with one with message like `please wait for a moment until wallet is ready`, rather than simply disabling the button?

**Comment by srirambv** [comment]
Sounds even better :+1:
