### ISSUE TITLE
Failure to open new pages

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1134]
Some sites have a problem that when you click on a link within the site, a blank page appears. This occurs whether you open the link in a new tab or just click on it. Private vs non-private tabs makes no difference.  IE 11 (Increasingly Evil Eleven) doesn't have this problem.

Cutting and pasting the link doesn't work either, though the main page link works - problem is links within the site.

one site where it consistently occurs is gameinformer.com

**Comment by bbondy** [comment]
Which link on that page reproduces?

**Comment by cfumante** [comment]
The video is the one directly following the text:
 
The DLC centers on a character called the Mechanist who has unleashed a
horde of malevolent robots into the Commonwealth. Players will be able
to hunt down robots and harvest parts to build their own custom robot
companions. A new trailer was released this week and you can check it
out below.
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by cfumante** [comment]
Sorry, I got the issues confused in previous email. 
 
On the gameinformer site, ALL links have the problem. This also occurs
very infrequenlly on other sites, but so rarely that I never made note
of the issue/site.
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by bbondy** [comment]
When I click on a link on that site it just opens  in the same tab and works ok for me.

**Comment by cfumante** [comment]
I just reconfirmed - I click on the link and I get a blank page with the
new URL. reload just cycles for a bit then returns the same blank page.

 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by cfumante** [comment]
sigh. Tested this again a few hours later and after a number of reboots
for unrelated issues - works fine now.
must have been aa Win10 issue - sorry for the false alarm.
 
/c/.
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
From: Carl Fumante [mailto:cf@hawaii.rr.com] 
Sent: Saturday, March 19, 2016 11:04 AM
To: 'brave/browser-laptop'
Subject: RE: [browser-laptop] Failure to open new pages (#1134)


I just reconfirmed - I click on the link and I get a blank page with the
new URL. reload just cycles for a bit then returns the same blank page.

 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by cfumante** [comment]
FYI__
 
This has reared its head again. It seems to be totally unpredictable. 
Sometimes it works normally, sometimes it just opens a blank page. 
It happens on one machine and not the other then vice versa. 
It happens on one machine and then with no updates or changes (just a
sleep) it works fine on that machine. Sometimes a freshly woken machine
works, sometimes not.  
 
The only consistency I can find is that often, but not always, it works
at night but not during the day - maybe a traffic issue?
 
Anyway, this is not a request to reopen the issue - it's too bizarre and
unpredictable for a serious bugstomping effort; I'm just letting you
know to keep you in the loop.
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
From: Carl Fumante [mailto:cf@hawaii.rr.com] 
Sent: Saturday, March 19, 2016 8:59 PM
To: 'brave/browser-laptop'
Subject: RE: [browser-laptop] Failure to open new pages (#1134)



sigh. Tested this again a few hours later and after a number of reboots
for unrelated issues - works fine now.
must have been aa Win10 issue - sorry for the false alarm.
 
/c/.
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
From: Carl Fumante [mailto:cf@hawaii.rr.com] 
Sent: Saturday, March 19, 2016 11:04 AM
To: 'brave/browser-laptop'
Subject: RE: [browser-laptop] Failure to open new pages (#1134)


I just reconfirmed - I click on the link and I get a blank page with the
new URL. reload just cycles for a bit then returns the same blank page.

 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
