### ISSUE TITLE
Move brave/ad-block and brave/tracking-protection deps to muon

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11352]
This task:
- Remove the deps from browser-laptop
- Add muon DEPS for the 2 repos

Later v2 o this work:
- Put it on the IO thread
- Expose an API or use content settings to control ad-block from browser-laptop
This should solve what is currently the biggest perf jank around page load.
This also gets us a step closer to node removal.

**Comment by luixxiul** [comment]
Do we need QA on this issue or do general regression tests cover this?

**Comment by bbondy** [comment]
Just basic spot check on ad-blocking working in general. Also make sure regional adblock list gets loaded. Nothing specific beyond that.
