### ISSUE TITLE
Saved wrong passwords can't be fixed

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1136]
I accidentally saved a wrong password on Twitter. Then when I tried to change it, it logs in correctly with the new password, but my old password is remembered forever.   Marking this for 0.8.2.

**Comment by bbondy** [comment]
btw I did this on Ubuntu 14.0.4 and the password feature worked great otherwise.

**Comment by diracdeltas** [comment]
I think this is a subtask of #1101, which I will try to make a rough version of by 0.8.2.

**Comment by diracdeltas** [comment]
When you login with the new password, it should ask if you want to update your password for X on twitter.com and then autofill the new one in the future. Did that at least work? If not, might be related to #1113

**Comment by bbondy** [comment]
I didn't see a prompt for updating my password.
