### ISSUE TITLE
When opening custom homepage, URL bar should also be focused

### ISSUE THREAD

**Issue by vdveen** [brave/browser-laptop#11366]
Have you searched for similar issues?  Yep

### Description

Custom homepage doesn't focus on URL when opening a new tab or window. This is not the case when selecting Dashboard, which does focus on the URL immediately.

### Steps to Reproduce

  1. Under 'Brave starts with' or 'A new tab shows', select 'Homepage'
  2. Open new window or tab
  3. URL bar is not focused

**Actual result:** Nothing happens

**Expected result:** Focus on URL so that I can immediately start typing instead of having to press F6

**Reproduces how often:** 100%

### Brave Version

**about:brave info:**
 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
This is expected behavior.  For example, if you open a new tab and your homepage is `google.com`.  Once the tab is open, most users would expect to be able to type into the search box (which is what gets focus by default).

You can use hotkeys to focus the URL bar, like F6 or Cmd/Ctrl + L 😄
