### ISSUE TITLE
Polish clipboardButton

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11373]
## Test plan

https://github.com/brave/browser-laptop/pull/11374#issue-263743079

----

### Description

Polish clipboardButton

- by applying the modified BEM style to dedupe properties
- by replacing span with browserButton

### Brave Version

**about:brave info:**

3544244689c7119c5aa4ebcc41d2d67e65982d1a

**Reproducible on current live release:**

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
