### ISSUE TITLE
Ledger  shows negative percentage

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11370]
### Description
Ledger  shows negative payments

### Steps to Reproduce

1.  Upgrade to 0.19.35
2. Have three publishers pinned
3. One at 90%, second at 4%, third at 4%
4. Have one publisher enabled, set at 2% completing 100%
5. Use browser normally for a while
6. Open payments
7. One of the pinned publisher with 4% is unpinned but still enabled
8. Unpinning one of the two publishers causes new disabled publisher to show up in negative % by auto enabling itself
**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31318453-fe2267ba-ac4a-11e7-8399-cbd17a0858be.png)

**Expected result:**
Calculations should not change for publisher

**Reproduces how often:** [What percentage of the time does it reproduce?]
Seen once
### Brave Version

**about:brave info:**

Brave | 0.19.35
-- | --
rev | eda2732
Muon | 4.4.25

**Reproducible on current live release:**
N/A

### Additional Information

#11369 #10534 
cc: @mrose17

**Comment by NejcZdovc** [comment]
tried to reproduce it, but without success

**Comment by mrose17** [comment]
technically, this is a negative percentage, not a negative payment. there is probably something wrong in the percentage normalization code. seems to me that there could be an additional pass to set percentages<0 to 0.

**Comment by diracdeltas** [comment]
also happening for me with 0 publishers pinned

**Comment by luixxiul** [comment]
I am not quite sure at all but is this issue related? https://github.com/brave/browser-laptop/issues/6944

**Comment by NejcZdovc** [comment]
I tried to reproduce it again, but without any success. @srirambv can you please try again on the latest master. Thank you

**Comment by NejcZdovc** [comment]
if there is negative % let's save it into the memo (remove publisher keys, rename to Publisher 1, Publisher 2, etc). We need to save before and after data

**Comment by diracdeltas** [comment]
I am seeing this in latest release. 

the site is muramatsu-america.com, it has 6 views and 59s of time, and it shows percentage -1. 

i have 4 pinned sites and i've manually excluded some sites.

**Comment by ryanml** [comment]
@diracdeltas I'll take another stab at repro and fixing this issue

**Comment by NejcZdovc** [comment]
@diracdeltas do you still have this in your table?
