### ISSUE TITLE
[Feature] Auto focus address bar when opening new tab

### ISSUE THREAD

**Issue by aaronovz1** [brave/browser-laptop#11372]
### Description
Feature request to make opening tabs work like Chrome where the address bar is focused. Ideally make it a configurable option to keep everyone happy.

**Actual result:**
For the case where google.com is the page set for new tabs, the focus is in the search box on the page.

**Expected result:**
The focus is always in the address bar

**Comment by bsclifton** [comment]
Thanks for the report @aaronovz1!  Looks like we just received a report of this earlier, which can be tracked with https://github.com/brave/browser-laptop/issues/11366.  I'm going to close this issue as a duplicate
