### ISSUE TITLE
Fix the wrong BEM naming on addFundsWizardAddress.js 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11378]
## Test plan

https://github.com/brave/browser-laptop/pull/11379#issue-263789116

----

### Description

Polish addFundsWizardAddress.js 

### Brave Version

**about:brave info:**

3544244689c7119c5aa4ebcc41d2d67e65982d1a

**Reproducible on current live release:**

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
