### ISSUE TITLE
Update style-loader to ~0.19.0

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11385]
### Description

Update style-loader to `~0.19.0`.

https://www.npmjs.com/package/style-loader
https://github.com/webpack-contrib/style-loader/blob/master/CHANGELOG.md#0190-2017-10-03

diff: https://github.com/webpack-contrib/style-loader/compare/v0.18.2...v0.19.0

**Comment by bsclifton** [comment]
Manually tested- this is used by webpack to load .less and .css files. I verified styles from those were being loaded/rendered as expected
