### ISSUE TITLE
Restoring a wallet backup (wallet v2) sometimes fails and then only shows "a"

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11383]
### Description
I migrated from wallet 1 to 2 and did the backup/recover process. Now that I've restored, the backup screen simply shows "a" as the keyword?
![screen shot 2017-10-08 at 11 33 30 pm](https://user-images.githubusercontent.com/4733304/31327125-dae92892-ac81-11e7-9449-1c4577afb920.png)

### Steps to Reproduce
  ~1. Have a wallet with v2 (BAT) that is displaying and working properly~
  ~2. Go to advanced => backup~
  ~3. Copy the keywords to clipboard and store somewhere~
  ~4. Go to advanced => restore~
  ~5. Input the keywords copied from step 3~
  ~6. After recovery finishes, go to advanced => backup~

Updated steps per @srirambv via [his post below](https://github.com/brave/browser-laptop/issues/11383#issuecomment-335865271)
1. Upgrade from 0.18.36 with wallet created
2. Wait for the transition to complete
3. Recover wallet using different wallet backup codes
4. Recover wallet without selecting any file or typing any code and ensure it fails
5. Repeat steps 3 & 4 around 4-5 times
6. Change reconcile stamp in ledger-state.json
7. Relaunch payments tab open up with the code as `a`

**Actual result:**
See screenshot

**Expected result:**
Should be showing all 32 words

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**
 
Brave: 0.19.34 
rev: d87b7caf57ae9d4aa88a275abca46b4a4619e34d 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
no

**Comment by bsclifton** [comment]
Per @NejcZdovc's request, I checked my seed in `ledger-state.json` and it appears that is the issue:
```json
{
  //...
  "properties": {
    "setting": "adFree",
    "fee": {
      "currency": "BAT",
      "amount": 10
    },
    "days": 30,
    "wallet": {
      "keyinfo": {
        "seed": {
          "0": 0,
          "1": 0
        }
      },
      //...
```

**Comment by NejcZdovc** [comment]
tried to reproduce this one, but without success

**Comment by bsclifton** [comment]
Per discussion w/ @NejcZdovc, we suspect this may be because I was switching between staging and production URLs several times (also, some updates had to be made for the endpoint; cc: @evq).  I'll close this issue for now and we can re-open if we see again

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/31452814-faae9590-aea7-11e7-8830-adf93b6e6976.png)
Seeing this on 0.19.41
STR I followed 
1. Upgrade from 0.18.36 with wallet creaeted
2. Wait for the transition to complete
3. Recover wallet using different wallet backup codes
4. Recover wallet without selecting any file or typing any code and ensure it fails
5. Repeat steps 3 & 4 around 4-5 times
6. Change reconcile stamp in ledger-state.json
7. Relaunch payments tab open up with the code as `a`

**Comment by bsclifton** [comment]
@srirambv based on your steps, it seems there is an intermittent failure somewhere which we need to be handling.  I'm going to update the text of this issue to reflect that

**Comment by LaurenWags** [comment]
Reproduced on 0.19.93.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/backup-your-wallet-showing-a-as-the-anonymised-recovery-key/11610

**Comment by bsclifton** [comment]
+1 from @jenn-rhim and also +1 from @disfit (still troubleshooting with them via https://github.com/brave/browser-laptop/issues/12122)

**Comment by bsclifton** [comment]
Here are some steps I can easily reproduce the problem
1. Clean profile
2. Launch Brave in staging
```
LEDGER_ENVIRONMENT=staging npm run start
```
3. Enable payments
4. Go to advanced (gear icon), restore, and then use the following words:
```
straightest cooker ringer beslime larch earthliest carabineer necrophilism hexed jerusalem sherry tart stratospheric casuistical damson cooeyed
```
5. Quit Brave
6. Relaunch (same as step 2)
7. Go to advanced (gear icon), backup, and then notice it shows "a"

**Comment by NejcZdovc** [comment]
@bsclifton thx for the steps, taking a look now

**Comment by srirambv** [comment]
This is reproducible on 0.19.48 and all hotfix release.

**Comment by srirambv** [comment]
Works fine on 0.19.113

**Comment by LaurenWags** [comment]
Reproduced issue using steps from https://github.com/brave/browser-laptop/issues/11383#issuecomment-349818315 on MacOS using 0.19.113 

![wallet-restore](https://user-images.githubusercontent.com/28145373/33838338-490f6b6c-de5d-11e7-845d-db6cb05162a2.gif)

**Comment by bsclifton** [comment]
Moving issue back a milestone. The problem was happening 100% of the time, which I instead captured with https://github.com/brave/browser-laptop/issues/12254.  It now works, but as seen above, it seems to intermittently fail

We'll need to continue investigating to understand to find the root cause

**Comment by bsclifton** [comment]
Moving to 0.19.x hotfix 12

**Comment by bsclifton** [comment]
Fixed in 0.19.x with 395e12bf36a961f9872fcb1490278df4e58edbbc

**Comment by srirambv** [comment]
Verified the steps mentioned in test plan. Repeated step 6, 10-12  times in quick succession and was still able to get the backup code. 👍

**Comment by jenn-rhim** [comment]
this is still happening to me. i'm on vs. 0.19.134.

**Comment by jenn-rhim** [comment]
sorry, scratch the above comment. @LaurenWags just pinged me that i should restore my wallet key first and see if the key sticks.  it looks like it's sticking. i'll keep an eye on it.  thanks @LaurenWags!

**Comment by LaurenWags** [comment]
thanks @jenn-rhim 😄
