### ISSUE TITLE
HTML5 stream [object MediaError]

### ISSUE THREAD

**Issue by 0x24D** [brave/browser-laptop#1139]
Every so often when watching a twitch.tv stream using html5 the stream stops and I receive the following error: [object MediaError]. The only way I have found to resolve this error is to refresh the page.

Brave: 0.8.1
Electron: 0.37.2
libchromiumcontent: 49.0.2623.75
V8: 4.9.385.28
Node.js: 5.8.0
Update channel: dev
![screenshot_2016-03-21_00-25-45](https://cloud.githubusercontent.com/assets/8465663/13908524/e88adf58-eefb-11e5-9978-ce9b76ae921b.png)

**Comment by bbondy** [comment]
Would you mind cross posting to Twitch as well? I think it's possibly a bug with their HTML video support.

**Comment by luixxiul** [comment]
ref: #1308

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of a topic on our community site.

https://community.brave.com/t/discussion-html5-stream-object-mediaerror/10050

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
