### ISSUE TITLE
"npm run add add-simulated-synopsis-visits" does not work on master

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11394]
## Test plan

https://github.com/brave/browser-laptop/pull/12014#issue-274793402

----

### Description

`npm run add-simulated-synopsis-visits` does not work on master.

````
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/Suguru/Library/Application Support/brave-development/ledger-synopsis.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at updateExistingSynopsisFile (/Users/Suguru/browser-laptop/tools/lib/synopsisHelpers.js:26:45)
    at addSimulatedSynopsisVisits (/Users/Suguru/browser-laptop/tools/lib/utilApp/index.js:47:3)
    at App.app.on (/Users/Suguru/browser-laptop/tools/lib/utilApp/index.js:60:7)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
````

### Steps to Reproduce

  1. `npm run add-simulated-synopsis-visits`

**Actual result:**

See above.

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

433e69fb0efc0be3ed3b5370e4b46f40612aa686

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Removed bug label- there is not a bug with Brave.  This extra functionality for testing is broken after recent changes to the ledger.  I believe with the reworking, `ledger-synopsis.json` was removed entirely

cc: @NejcZdovc

**Comment by luixxiul** [comment]
The script is actually useful to test the ledger table (such as displaying `Show Less` button for example), so it would be appreciated if it is fixed soon.

**Comment by luixxiul** [comment]
checked on master and works nicely.

**Comment by kjozwiak** [comment]
Re-opening as this doesn't seem to be working... @bsclifton also confirmed that it wasn't working for him.. STR:

* checkout any of the branches
* ensure that you've removed the `node_modules` folder
* `npm install` && `npm run watch`
*  run brave via `npm start` and enable the wallet via `about:preferences#payments`
* close brave once the wallet has been created
* `npm run add-simulated-synopsis-visits 100` within the `browser-laptop`
* re-launch brave via `npm start` and you'll notice that the ledger table hasn't been filled under `about:preferences#payments`

Checked both macOS 10.13.1 x64 & Ubuntu 17.10 x64:
* `master` branch: FAILED (didn't populate the table)
* `0.21.x` branch: FAILED (didn't populate the table)
* `0.20.x` branch: FAILED (didn't populate the table)
* `0.19.x` branch: FAILED (didn't populate the table)

@luixxiul when you ran this on Debian, did the ledger table get populated? Maybe we're doing something incorrectly?

**Comment by NejcZdovc** [comment]
this was broken with the latest bat libraries
