### ISSUE TITLE
.google.com cookie mismatch after import

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#11401]
## Test plan

https://github.com/brave/browser-laptop/pull/11647#issue-267885634

----

### Description
Import cookies from Chrome/Firefox will cause cookie mismatch error on google.com

### Steps to Reproduce

  1.  Clean cookies on Chrome/Firefox and login in google account
  2.  Import cookies from Chrome/Firefox to Brave
  3.  Login google account on Brave

**Actual result:**

<img width="710" alt="screen shot 2017-10-08 at 2 32 17 pm" src="https://user-images.githubusercontent.com/11330831/31355229-46f395a6-acee-11e7-9bc8-18c624ff3964.png">

**Expected result:**
No cookie mismatch error
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version
0.19.36
**about:brave info:**

 
Brave: 0.19.36 
rev: d24779f2704b4eb6fd5e7b0502a9ff1227f616bb 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64
**Reproducible on current live release:**

Yes
### Additional Information

Opera has the same problem
related to #11356

**Comment by darkdh** [comment]
cc @bbondy

**Comment by kjozwiak** [comment]
Using the STR from https://github.com/brave/browser-laptop/issues/11401#issue-264003667, went through the following verification:

* macOS 10.12.6 x64 - (imported cookies from Chrome/Chromium/Firefox) - PASSED
* Win 10 x64 - (imported cookies from Chrome/Chromium/Firefox) - PASSED

**Comment by darkdh** [comment]
chrome doesn't actually work

**Comment by kjozwiak** [comment]
New Test Plan: https://github.com/brave/browser-laptop/pull/11647#issue-267885634

**Comment by LaurenWags** [comment]
So when testing this using the steps specified in https://github.com/brave/browser-laptop/pull/11647#issue-267885634 while importing from Firefox, no errors. However, after those I took an additional step to login to a different gmail account than what was used in steps 1&3 and got the cookie mismatch error. Should that scenario be covered by this issue or is it different? cc @darkdh @kjozwiak

**Comment by srirambv** [comment]
I get cookie mismatch error when I reload the gmail tab before logging out.  Also seeing error mention by @LaurenWags when logging into a different account

**Comment by jonathansampson** [comment]
+1 from Twitter: https://twitter.com/edmorrissey/status/924318224707137537

**Comment by tomasdev** [comment]
Having this issue not by importing. Simply sign into 2 or 3 different gmail accounts and it breaks.

**Comment by jonathansampson** [comment]
@tomasdev We're able to set exceptions, but aim to do so with caution. I am regularly signed into 2 GMail accounts (without any issue). Would you be available to hop on a Skype or Google Hangout call sometime? I'd love to see the problem first-hand.

**Comment by Hjohnson14** [comment]
Hi all,
I'm having this problem too. I've tried both clearing cookies on Chrome and then importing the data to Brave and allowing all cookies for Google on the site shield setting, but neither has worked. Is there another solution? Access to gmail is essential to my browser usage.

**Comment by tomasdev** [comment]
@Hjohnson14 what I did to fix it was `Preferences » Shields » Cookie Control: Allow all cookies` until there's an option to whitelist 3rd party cookies per domain

**Comment by jonathansampson** [comment]
Thank you, @tomasdev. I'll email you shortly :)

**Comment by mikeongit** [comment]
What worked for me was to navigate to google.com and deactivate the Brave Shield.
Deactivating it for accounts.google.com only didn't do the trick for me, you also have to explicitly deactivate for the google.com domain.

Next, I signed in and was able to access my mail without any trouble.

**Comment by walker2** [comment]
@mikeongit 
Thanks, your solution worked.

**Comment by kjozwiak** [comment]
@mikeongit @walker2 were guys importing cookies from either Firefox or Chrome? Or did you run into this issue when migrating from the `muon` version of Brave (old)?

**Comment by mikeongit** [comment]
Heya,

I imported cookies from both, Firefox and Chrome.

**Comment by walker2** [comment]
@kjozwiak Yeah just imported everything from Firefox

**Comment by kjozwiak** [comment]
@mikeongit @walker2 the Brave `muon` version isn't being supported anymore. I would suggest switching to the new version of the browser which can be found here:

* https://brave.com/download (Download Link)
* https://github.com/brave/brave-browser/ (GitHub Page)

We also have a `dev` and `beta` channel which can be found here:

* https://brave.com/download-dev
* https://brave.com/download-beta
