### ISSUE TITLE
Error when launching Brave: ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11402]
### Description
Submitting on behalf of @incitadus (so that we don't lose track of this)
https://github.com/brave/browser-laptop/pull/3381#issuecomment-329971056

Getting error:
> Your file was not found
> 
> It may have been moved or deleted.
> ERR_FILE_NOT_FOUND

That's the error they get when trying to open Brave (Using win10).  Worked for
about a week then the error started when pinned to start menu.  User has deleted and reinstalled several times w/o success

**Comment by incitadus** [comment]
Hi Brian moved Brave from the start menu and desk top,  pinned it to the
task bar and now opens without issue.
