### ISSUE TITLE
Accessing Youtube video from Google's homepage notification would crash the browser

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-laptop#1140]
Step to reproduce

1. Login to your Google account.
2. [Access your Google notification.](http://i.imgur.com/pMS7NVt.png) This notification is from my Google+ account.
3. Click the Youtube video.
4. Browser immediately crashed.

Win 7-64bit

**Comment by bbondy** [comment]
Probably related to this:
https://github.com/atom/electron/issues/4681

Which will be in the next version of Electron, if I had to guess I'd say will be 0.8.3.

**Comment by bbondy** [comment]
I think this is probably fixed upstream, but please let me know if not and Ill re-open.
