### ISSUE TITLE
Installation on AUR fails

### ISSUE THREAD

**Issue by createchange** [brave/browser-laptop#11404]
### Description
On an Arch Linux host, I am unable to install Brave, whether it's the stable release, bin or git releases. I did a complete system upgrade. Uname -r returns "4.13.4-1-ARCH" - log of the failed installation is here: https://ptpb.pw/Xw2t
### Steps to Reproduce

  1. yaourt brave
  2. Select either brave, brave-bin or brave-git
  3. Install fails

**Actual result:**
Failed installation - 
npm ERR! Cannot read property 'pause' of undefined
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jhw/.npm/_logs/2017-10-10T02_40_32_275Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build brave.

**Expected result:**
Brave would install correctly.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version
Attempted installation is of version 0.18.36-3

**Reproducible on current live release:**
 Not sure what is meant by this questions, happy to provide more information as needed.

**Comment by ladislavkrivy** [comment]
Same problem here, using pacaur. log: https://ptpb.pw/44Ce

**Comment by Legogris** [comment]
Same here.

**Comment by luixxiul** [comment]
which npm version are you using?

**Comment by Legogris** [comment]
5.4.2
