### ISSUE TITLE
Menubar setting issue on ubuntu/elementary os

### ISSUE THREAD

**Issue by The-Clockmaker** [brave/browser-laptop#11403]
After the update from 17.x to 18.x nearly all issues seem fixed for me, except for 1, when I go to settings and I select to always hide the menu bar it seems to ignore that setting upon rebooting brave browser, it seems to remember the setting choice in the settings menu or in the right click menu, but it just seems to ignore it, so every time I boot the browser I have to unselect "hide the menubar", and reselect "hide the menu bar"
I'm using elementary os freya with all the latest updates which is based on ubuntu 14.04, and I am also running the latest stable version of brave browser as of right now

**Comment by bsclifton** [comment]
Thanks for the report, @The-Clockmaker 😄  We are tracking this issue with https://github.com/brave/browser-laptop/issues/5086 which you can follow.  I'm going to close this particular issue as a duplicate.  Thanks!
