### ISSUE TITLE
Blocked elements counts increase on shield by opening external links 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11400]
### Description

Blocked elements counts of other tabs increase on the shield by opening external links.

### Steps to Reproduce

  1. Install 0.19.36
  2. Open https://github.com/brave/browser-laptop/issues/11393
  3. Click `http://slashdot.org/` there

**Actual result:**

The counts of the blocked elements increases on the GitHub page's tab. Click the gif image for larger one.

![bug](https://user-images.githubusercontent.com/3362943/31349761-8727b9ba-ad5f-11e7-8df4-bfddce12a9d1.gif)

**Expected result:**

It should not

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Brave Version

**about:brave info:**

Brave: 0.19.36 
rev: d24779f2704b4eb6fd5e7b0502a9ff1227f616bb 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Reproducible on current live release:**

No.

**Comment by bsclifton** [comment]
@luixxiul related? https://github.com/brave/browser-laptop/issues/2626

**Comment by luixxiul** [comment]
no, that is a different issue.

**Comment by bbondy** [comment]
0.19.x: c0aea8f7eb0dc3491c2defd3b7265f3f8fab7420
0.20.x: 9459573faff3cbb84f19ea297e3f630575ae2c30
master: 2257e1d73a1a1c23059f0a93ce5e249893c44efb
