### ISSUE TITLE
Backing up wallet to file creates recovery file in AppData

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#11419]
### Description
The `brave_wallet_recovery.txt` file is stored in `%appdata%\brave\` before offering it for saving.

The file's content contains this sentence "Save this key in a safe place, separate from your Brave browser.", so Brave acts against its own advice by saving this file in the profile.

### Steps to Reproduce
  1. Go to about:preferences#payments
  2. Click the cogwheel
  3. Click 'Back up your wallet'
  4. Click 'Save recovery file...'

**Actual result:**
The file being stored in `%appdata%\brave\` as well as the location specified by the user.

**Expected result:**
The file only being stored in the location indicated by the user.

**Reproduces how often:**
Each time.

### Brave Version

**about:brave info:**

Brave | 0.19.37
-- | --
rev | c6ee3b2
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.16296
OS Architecture | x64

**Reproducible on current live release:**
This is the live beta release.

### Additional Information
Technically, all information to get the wallet would already be available in `%appdata%\brave\`, but having the recovery file there seems a bit overdoing it.

**Comment by srirambv** [comment]
When you click on import recovery key, default location opened is `%appdata%/brave` so am guessing it the expected behaviour to allow user to store a copy in desired location apart from storing in the profile folder. 

cc: @NejcZdovc

**Comment by hugobuddel** [comment]
Maybe it is a non-issue at the moment, but I was assuming that the Brave wallet could somehow be encrypted (perhaps in the future). Especially since it will at some point it will be possible to move BAT from the wallet to elsewhere (which supposedly is not possible now). And then you don't want people to have access to your funds simply by copying a file (in a known location) from your computer.

**Comment by diracdeltas** [comment]
until #10705 is done, the Brave wallet recovery data is also stored in session-store-1 (unencrypted) in the appData directory, as you mentioned. so there seems to be no reason to have the recovery file also in the directory.

**Comment by srirambv** [comment]
Verified on no recovery code file created in profile folder when building from source. Need to verify once on packaged build as well.

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
