### ISSUE TITLE
returning to the "recover" modal when recovering fails

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11422]
### Description

Failing a  wallet recovery will take the user back to the `about:preferences#payments` page. I think when a recovery fails, rather than closing the "Advanced" modal and returning the user to `about:preferences#payments`, we should leave the "Recovery" modal opened incase the user wants to retry.. It's pretty annoying having to go through the "Advanced" options every time a recovery as failed.

### Steps to Reproduce

  1. visit `about:preferences#payments` and create a wallet
  2. select "Advanced Settings" -> "Recover your waller"
  3. select "Recover" and press "OK" on the "Recovery Failed" message

**Actual result:**

The "Recovery" modal is closed and the user is returned to `about:preferences#payments`. The user now has to go through the "Advanced" settings once more to retry recovery.

**Expected result:**

When a wallet recovery fails, we shouldn't be closing the "Recover" window and users should be able to retry rather than going through "Advanced" settings all over again.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.37 
> rev: c6ee3b2de7fd15adc5af65dd4709283cfc30aa07 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

Yes, currently reproducible with the latest released version: 

> Brave: 0.18.36 
> rev: 7ab85e97318fef041433b0c3d73b457205fae805 
> Muon: 4.3.22 
> libchromiumcontent: 61.0.3163.79

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
