### ISSUE TITLE
With many tabs, startup is very slow

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#11424]
### Description
On a user profile which has 100 unique tabs, app startup time is significantly slower vs startup with a fresh profile.
Total time to start, type a URL in the nav bar and navigate was ~7500 ms vs 4000 ms.

### Steps to Reproduce
Automated test (feature/perf-tests branch): https://github.com/brave/browser-laptop/pull/10517/commits/648bafdaaf1308d966d415b98beba5e22664d457#diff-e5c305031ff191e0f8d1fb021abeb435

  1. Start Brave
  2. Open 100 tabs each with unique URLs
  3. Close Brave
  4. Open Brave. It should remember the 100 tabs.
  5. Focus the URL bar, type a URL and hit enter to navigate.

**Actual result:**
Much slower with many tabs

**Expected result:**
Similar speed to a fresh profile

**Reproduces how often:**
Always in the perf tests

### Brave Version
master 29bdbd5b9500a6e73967a263ca52e5776c4e8e4d

Also repro'd on

Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22
libchromiumcontent | 61.0.3163.79
V8 | 6.1.534.32
Node.js | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 15.6.0
OS Architecture | x64

**Reproducible on current live release:**

### Additional Information
![screen shot 2017-10-10 at 20 20 41](https://user-images.githubusercontent.com/521861/31408555-847a8b9a-adf8-11e7-83f8-0a9d5e6d4912.png)

**Comment by petemill** [comment]
Attacking part (most?) of this with #13216

**Comment by petemill** [comment]
Closing in favor of the more detailed #13216

**Comment by GeetaSarvadnya** [comment]
Tested by loading win3-tabs105 in Roaming profile.  3 windows with 105 tabs in each window. There is no performance lag, click on each tab opens the website immediately. Click on new tab with new website is also opens website quickly.

Verified on Windows x64 
* 0.22.702 e4a853d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
