### ISSUE TITLE
certificate errors not being initially displayed when opening pages using "Open Link in New Tab"

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11426]
### Description

When opening a page with a certificate error using "Open Link in New Tab" under macOS, the page will initially appear blank until it's refreshed.

### Steps to Reproduce

  1. open https://badssl.com/
  2. right click "expired" -> Open Link in New Tab
  3. right click "wrong.host" -> Open Link in New Tab
  4. right click "self-signed" -> Open Link in New Tab
  5. click on the "expired" tab and you'll notice it's blank (refresh and it will load)
  6. click on the "wrong.host" tab and you'll notice it's blank (refresh and it will load)
  7. click on the "self-signed" tab and you'll notice it's blank (refresh and it will load)

**Actual result:**

Rather than loading the certificate error within the tab, the page will appear blank. Once the tab has been refreshed, the certificate error will load correctly.

![certissue](https://user-images.githubusercontent.com/2602313/31412778-78f9d6b8-ade4-11e7-82c7-85115a6b21d1.gif)

**Expected result:**

The certificate error should be loading within the tab without any issues.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.37 - **Reproduced**
> rev: c6ee3b2de7fd15adc5af65dd4709283cfc30aa07 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

Yes, currently reproducible with the latest release 
> Brave: 0.18.36 - **Reproduced**
> rev: 7ab85e97318fef041433b0c3d73b457205fae805 
> Muon: 4.3.22 
> libchromiumcontent: 61.0.3163.79

**Comment by Liunkae** [comment]
+1 from me. I've noticed this a few times recently.
