### ISSUE TITLE
Any VMs / images / iso / containers available for compile?

### ISSUE THREAD

**Issue by hohmd** [brave/browser-laptop#11433]
Hello.
Is there any virtual machines / images / iso / containers available for compile brave?

**Comment by bsclifton** [comment]
@hohmd the only information we have available is here:
https://github.com/brave/browser-laptop/blob/master/test/vms/vagrant/README.md

There are vagrant files for Debian Jesse, CentOS, and Ubuntu 14.04
https://github.com/brave/browser-laptop/tree/master/test/vms/vagrant

Any updates in this area are extremely welcome 😄  Let us know if you have any questions
