### ISSUE TITLE
Convert from l20n to l10n and get it in transifex

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1143]

**Comment by bbondy** [comment]
Adding to 0.8.3 which is not this next release but the one next week.

**Comment by nashe** [comment]
Can you provide the link to the Transifex, once created? I can do the translation to French.

**Comment by bbondy** [comment]
https://www.transifex.com/brave/brave-laptop/ is / will be the link.

**Comment by nashe** [comment]
Can you validate the three applications for the French team? Thanks!

**Comment by bbondy** [comment]
Tous les 3 sont ajouté

**Comment by viswanathamsantosh** [comment]
Can we add Indian languages Tamil, Bengali, Hindi and telugu as well? Brave India community will help with the translations.

**Comment by bbondy** [comment]
@viswanathamsantosh You can request it, and then I can approve it on Transifex.

**Comment by c0b41** [comment]
@bbondy hey can you add turkish language?

**Comment by bbondy** [comment]
Just request it pls and I'll approve.

**Comment by seeam** [comment]
@bbondy, can't see Bengali (Bangladesh) on the transifex menu.

**Comment by nashe** [comment]
@seeam: the locale bn_IN exists, did you clicked on "show all languages"?

**Comment by seeam** [comment]
@nashe sorry, I mean bn_BD. And the localization is 100% completed also merged with the current code in github.

**Comment by bbondy** [comment]
@aekeus please upload those too.

**Comment by bbondy** [comment]
bn_BD I guess there was some kind of file encoding issue so it's being tracked here (0.9.3):
https://github.com/brave/browser-laptop/issues/1397

Closing this task in general because it was merged here though:
https://github.com/brave/browser-laptop/commit/63d754b48cbdb493f0dc6efb53db27ed0ecfcf02
