### ISSUE TITLE
BTC-BAT Pending funds stay pending after being added to balance

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#11439]
### Description
The payment screen lists payments as 'pending' even after they are added to the balance.

See screenshot below. 38 BAT were added through uphold, the other 21.06 through automatic BTC-BAT conversion when upgrading to Brave 19. Both the uphold-bought BAT and the BTC-converted BAT are added to the balance, but the converted ones are also pending.

![screenshot](https://user-images.githubusercontent.com/1306453/31429082-4d400ab8-ae6d-11e7-9b6c-af3749769197.png)

The BTC-part of the BTC-BAT conversion took over 13 hours to confirm, maybe that is related to the problem.

### Steps to Reproduce
Not exactly sure, costs money and quite some time to test.

  1. Fill Brave 18 wallet with some BTC.
  2. Upgrade to Brave 19 and start BTC-BAT conversion (automatic).
  3. Wait (many hours) till the BAT wallet is filled.

**Actual result:**
BAT is added to balance, and still pending. See screenshot.

**Expected result:**
BAT balance is not pending anymore.

**Reproduces how often:**
Unsure

### Brave Version

**about:brave info:**
 Several brave versions were involved. The Brave version from https://basicattentiontoken.org/mercury-preview-now-available/ was used for the initial conversion (v0.19.34beta). Below is the current version

Brave: 0.19.39 
rev: ebcd28052155dc6cffcafc13e8606f792c4745b5 
Muon: 4.4.27 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**
Don't know

**Comment by LaurenWags** [comment]
Reproduced on 0.19.43 using MacOS.
![screen shot 2017-10-11 at 4 56 31 pm](https://user-images.githubusercontent.com/28145373/31466597-c74521f8-aea5-11e7-8302-ca4fef7f10b6.png)

**Comment by LaurenWags** [comment]
cc @bsclifton @NejcZdovc

**Comment by bsclifton** [comment]
This may have been fixed with recent commits and/or by server updates made by @evq.  I'll close this issue- let's reopen if the problem still occurs 😄

**Comment by LaurenWags** [comment]
looks good now on MacOS.

**Comment by hugobuddel** [comment]
fixed on Windows as well with 0.19.45
