### ISSUE TITLE
'"" is ready' notification appears by clicking import recovery key button on Debian

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11435]
### Description

`"" is ready` notification appears by clicking import recovery key button on Debian

### Steps to Reproduce

  1. On Debian, open about:preferences#payments
  2. Open advanced settings
  3. `Recover your wallet`

**Actual result:**

![clipboard01](https://user-images.githubusercontent.com/3362943/31425839-efc3d340-ae9b-11e7-85f7-8e0905a4ccc0.png)

**Expected result:**

It should not appear

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave: 0.19.39 
rev: ebcd28052155dc6cffcafc13e8606f792c4745b5 
Muon: 4.4.27 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
moving to 0.19.x release 2

**Comment by kjozwiak** [comment]
This is also reproducible under Ubuntu 17.10 x64 using `0.19.98`.

**Comment by NejcZdovc** [comment]
tried this on Ubuntu and couldn't reproduce. Closing for now
