### ISSUE TITLE
Widevine resource ID should be obtained properly

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11430]
Currently we use appConfig.widevine.resourceId which is undefined so the improper setting is set.

We should do it like `getFlashResourceId`.

It was originally set to only the mac path which was wrong.
And then went to undefined here:
https://github.com/brave/browser-laptop/commit/f682695ab999e32e80c3773d0421e5c11836bd4a

I did a simple test and simply using the old value before that commit doesn't work properly.

**Comment by diracdeltas** [comment]
marking as security, per comment in https://github.com/brave/browser-laptop/issues/13552
