### ISSUE TITLE
animation overlay not stopping after wallet has been created

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11432]
### Description

When enabling payments under v0.19.38 rev: fa3d144edb796192487ccc89ac771f4f9b954e57 with a zero balance, the progress overlay that's being displayed during the transition phase will keep going and will never "complete" despite the wallet being ready. The animation will keep going until you either disable/enable the wallet or restart the browser.

Also tried the following:

* checking console via "option + command + i"
* checking console via "fn + shift + f8"
* closing the about:preferences page and re-opening (animation kept going)

### Steps to Reproduce

  1. install & launch v0.19.38 rev: fa3d144edb796192487ccc89ac771f4f9b954e57 
  2. visit about:preferences#payments and enable payments

**Actual result:**

The overlay animation will keep going despite the wallet being ready.

Attached log from macOS: [log.txt](https://github.com/brave/browser-laptop/files/1374244/log.txt)

**Expected result:**

Once the transition phase has been completed, the animation overlay should stop and the wallet should be displayed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.38 
> rev: fa3d144edb796192487ccc89ac771f4f9b954e57 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

BAT integration was added in `0.19.x` and isn't available under `0.18.x`, hence not reproducible in the latest release.

**Comment by bbondy** [comment]
maybe just change the text to say check back later and no animation?

**Comment by luixxiul** [comment]
This bug breaks `npm run test -- --grep='Regular payment panel tests can setup payments advanced settings is visible when payments are enabled'` etc. on ledgerPanelTest.js
