### ISSUE TITLE
Add the ability to switch languages

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1144]
Ideally we'd pull the OS language and set the language code based on that.  Default to English.

**Comment by bbondy** [comment]
https://github.com/sindresorhus/os-locale

**Comment by bobvanluijt** [comment]
Where is the language set currently?

**Comment by bbondy** [comment]
we just simply always do English right now.

**Comment by aekeus** [comment]
Language is selectable in about:preferences
