### ISSUE TITLE
About pages from macOS menu are not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11442]
### Description

When I click on File->Preferences nothing happens. Same thing happens for every single about page (history, about brave, bookmarks, etc)
### Steps to Reproduce

  1. Latest 0.19 branch on clean profile
  2. Open menu File->Preferences

**Actual result:**

Nothing happens
**Expected result:**
Preferences pages should open
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

 
Brave: 0.19.39 
rev: 6d58e75815219fae587b8c06abcd59ff099f48f4 
Muon: 4.4.27 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Comment by NejcZdovc** [comment]
Note: this was working yesterday

**Comment by NejcZdovc** [comment]
broken with https://github.com/brave/browser-laptop/commit/6d58e75815219fae587b8c06abcd59ff099f48f4

**Comment by bbondy** [comment]
0.19.x: 64b14034ecc28c3858da38b9d4e02e7f89ba52e3
0.20.x: 7a067d1359854cc806e7d25cb83ab798be1c5871
master: 643c14c576ab2fef30ebe3ff16f9ab22f06b96fb

**Comment by kjozwiak** [comment]
Using the STR from https://github.com/brave/browser-laptop/issues/11442#issue-264576907, went through the following verification process:

* enabled the File menu
* ensured Brave -> Preferences opens `about:preferences` without issues
* ensured Edit -> Settings opens `about:preferences` without issues
* ensured History -> Show History opens `about:history` without issues
* ensured Bookmarks -> Bookmarks opens `about:bookmarks` without issues
* ensured Shields -> Brave Payment opens `about:preferences#payments` without issues
* ensured Window -> Bookmarks opens `about:bookmarks` without issues
* ensured Window -> Downloads opens `about:downloads` without issues
* ensured Window -> Extensions opens `about:preferences#extensions` without issues
* ensured Window -> Password opens `about:passwords` without issues
* ensured Help -> About Brave opens `about:brave` without issues
