### ISSUE TITLE
Brave cannot read root directory (or /home, etc) on Ubuntu 16.04.2 LTS

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#11440]
### Description
It seems not possible for Brave 0.18.36 to read the root directory (`/`) or `/home` or `/etc` on Ubuntu 16.04.2 LTS.

### Steps to Reproduce
  1. Open a Save As dialog (e.g. file, link, image), or other file browser dialog (e.g. where to store downloads in settings).
  2. Try to browse to `/`, `/home` or anything outside the users home directory.

**Actual result:**
Popup with

> Could not read the contents of /
> Error opening directory '/': Permission denied

**Expected result:**
The directory being opened.

**Reproduces how often:**
Each time, also after restarting Brave.

### Brave Version

**about:brave info:**
 
Installed through snap.

Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.10.0-30-generic 
OS Architecture: x64

**Reproducible on current live release:**
Don't know what this means.

### Additional Information
Two maybe related things:

1. Some directory symlinks cannot be followed, that is Brave asks to overwrite the file instead of entering the directory. This is hard to reproduce. It happens for me with `~/Dropbox` which is a symlink to a directory on another partition.

2. 'Home' in these dialogs goes to `~/snap/brave/6`.

**Comment by hugobuddel** [comment]
Terminal message when the save-as dialog is opened:

> (brave:4538): GLib-GIO-WARNING **: Error creating IO channel for /proc/mounts: Permission denied (g-file-error-quark, 2)
> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by hugobuddel** [comment]
Fixed by removing the snapcraft version (0.18.36) and installing through apt (0.19.48).

My guess is that this issue has the same cause as #11443, maybe a conflict between the snapcraft version and AppArmor. Or perhaps something has changed in 0.19, don't know whether it is possible to install that version through snapcraft. The 'save-as' window looks rather different between these two versions.

**Comment by bsclifton** [comment]
cc: @posix4e

**Comment by posix4e** [comment]
@bsclifton  Cheers. Yea another reason to move to our own snap
