### ISSUE TITLE
$BAT does not show up in ledger in multiple browsers

### ISSUE THREAD

**Issue by tapdancemobile** [brave/browser-laptop#11448]
I am running two instances of Brave: 0.19.41 on two macbooks. I would have expected the $BAT wallet to be shared between these two synced devices? Is a wallet device specific? If so, kindof defeats the power of using a ledger...

**Comment by srirambv** [comment]
Sync is currently limited to bookmarks history and site settings.

**Comment by bsclifton** [comment]
Thanks for the report, @tapdancemobile!  That behavior is known and we're tracking this feature request with issue https://github.com/brave/browser-laptop/issues/10066.  Please subscribe to that issue for updates.  Thanks! 😄
