### ISSUE TITLE
Contribution Statement does not accurately reflect ledger table

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11447]
### Description
When my Contribution Statement was generated it did not reflect my ledger table.

### Steps to Reproduce

1. Have a wallet with an account balance that is greater than 25 BAT. Ensure you have some ledger entries (some marked as ‘include’, some not marked as ‘include’).
2. Verify updating the reconcilestamp value in ledger-state.json changes your ‘Next contribution:’ to display ‘Overdue’ under monthly balance and the update is reflected in your contribution. 
3. Contribution Statement reflects contribution amount 
4. Contribution statement does not accurately reflect rank and percentages for sites listed in ledger table.

**Actual result:**
This is my ledger table:
![screen shot 2017-10-11 at 10 32 55 am](https://user-images.githubusercontent.com/28145373/31450422-5dccdc3a-ae77-11e7-9fcf-6e598da5a84f.png)

This is my contribution statement. Note that rank and percentages for sites do not match ledger table:
![screen shot 2017-10-11 at 10 37 32 am](https://user-images.githubusercontent.com/28145373/31450442-694fab78-ae77-11e7-9bf7-b929d0569655.png)

**Expected result:**
Contribution Statement should reflect rank and percentages for sites in ledger table.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**
Brave | 0.19.41
rev | c33d1c3
Muon | 4.4.27

**Reproducible on current live release:**

### Additional Information

cc @NejcZdovc @kjozwiak

**Comment by NejcZdovc** [comment]
second contribution, triggered with the same ledger table
[Brave_Payments_2017-10-11-afternoon.pdf](https://github.com/brave/browser-laptop/files/1376773/Brave_Payments_2017-10-11-afternoon.pdf)

**Comment by NejcZdovc** [comment]
So for final contribution we are using statistically voting, this means that votes are adjusted through time. As you can see from the second PDF, with the same ledger table you are getting better % (closer to what you have in the table). If you would do this process few more times, % would be exact or almost exact. This is expected result, so I am closing this one.
