### ISSUE TITLE
Netflix audio out-of-sync

### ISSUE THREAD

**Issue by Kieran-X** [brave/browser-laptop#11446]
### # Description

Upon watching a show on Netflix, about a couple of minutes in, you will start to see the delay between the video and audio slightly, to the point where its really noticeable. For me, you can hear like a little pop sound every once in a while, that's when it's starts to go out-of-sync.

I've looked up the issue to see who else has had it, solutions:

- Change video quality (done, still does it even on the lowest)
- Check internet connection (Internet's not an issue: http://beta.speedtest.net/result/6697819823
- Outdated hardware (Nope, https://i.imgur.com/nMgcFPc.png)
- Update drivers (All updated)

I've tried other browsers (Chrome, Edge and Firefox) and they've not had any issues. I've even reinstalled windows to be sure.

### Steps to Reproduce

Just watch anything. Try a hour program.

**Actual result:**
Audio out of sync,

**Expected result:**
Audio in sync.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**
 
Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
This is live version, yes?

### Additional Information

There was a solution that you're able to switch from Silverlight and HTML5 on Netflix but I'm not sure. I think Netflix is only HTML5 now.

**Comment by bsclifton** [comment]
Closing as stale since there haven't been any additional comments or +1s. Let's please re-open if this is still an issue. Thanks 😄
