### ISSUE TITLE
Update text on Progress Screen/Transition Overlay for when wallet is BTC->BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11459]
### Description
Text on progress screen/transition overlay/animation for when your prior BTC wallet is being converted to a BAT wallet says 'This can take a few minutes' but in reality we in QA are seeing this take 30-40+ minutes. We would like this text to be updated to more accurately reflect the amount of time this process takes.

### Steps to Reproduce

  1. Have 0.18.x wallet (mine had more than $0 USD in it)
  2. Update to 0.19.43.
  3. Navigate to about:preferences#payments
  4. Transition overlay is displayed.

**Actual result:**
![screen shot 2017-10-11 at 4 08 49 pm](https://user-images.githubusercontent.com/28145373/31465963-912f79b2-aea3-11e7-8064-0deaefdd0f0e.png)

**Expected result:**
Would like text in red box to be updated. Text TBD, but maybe something like 'This will take 30+ minutes' or 'This will take some time depending on network load'. 

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.43
rev | 24df93d
Muon | 4.4.27

**Reproducible on current live release:**
no

### Additional Information

cc @davidtemkin for actual text if it is decided to update this text.

Related to: https://github.com/brave/browser-laptop/issues/11389

**Comment by bsclifton** [comment]
Per @davidtemkin, we'll be using the following text:
> Please wait while we convert your Bitcoin to BAT. This can take anywhere from a few minutes to several hours, due to the Bitcoin transaction confirmation process, and will continue normally even if you quit Brave.

**Comment by bsclifton** [comment]
Here's a static shot of what the transition looks like with the new text:
![screen shot 2017-10-11 at 3 20 10 pm](https://user-images.githubusercontent.com/4733304/31469726-c2f78824-ae97-11e7-932c-94c6a65fedd5.png)

And here's an in progress shot showing the transition complete (empty wallet):
![transfer2](https://user-images.githubusercontent.com/4733304/31469747-d2758cba-ae97-11e7-812d-76b17d8195fd.gif)

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/6b8c99fbbf99e599bb7faf2e794583f91febb76c
0.20.x https://github.com/brave/browser-laptop/commit/6795ec5d7d415d8913f160a66a959a824d79b9f8
0.19.x https://github.com/brave/browser-laptop/commit/231802878de9b10428550a41eb68db000b67582a
