### ISSUE TITLE
Update LastPass to 4.1.65

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11451]
Brave currently supports LastPass 4.1.45. This issue proposes upgrading to LastPass 4.1.65.

Test results with LastPass 4.1.65.12:

- [x] Popup displays
- [x] "Create an account" works
- [x] Able to log-in
- [x] Log-in window self-closes
- [x] Context menu populated
- [x] Copy from context menu works
- [x] Autofill works as expected
- [x] Password generation works

**Comment by jonathansampson** [comment]
Closed by https://github.com/brave/vault-updater/commit/66a61983a392690b6fd18b3a648fdb83542fcda1

**Comment by bsclifton** [comment]
marked as `QA/no-qa-needed` since this is already live
