### ISSUE TITLE
"Save Torrent" button does not seem to do anything

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#11452]
Similar, but seemingly different, issue: #8146

### Description
Pressing the "Save Torrent File..." button on a torrent download doesn't seem to do anything.

### Steps to Reproduce
  1. Go to e.g. https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/
  2. Click on a torrent and open the torrent download page, e.g. https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.2.0-amd64-netinst.iso.torrent
  3. Click on the 'Save Torrent File...' button.

**Actual result:**
Nothing, no indication that anything happens.

**Expected result:**
Save-as popup with option to save the .torrent file.

**Reproduces how often:**
Always, tried with some torrents.

### Brave Version

0.18.36 on Ubuntu 16.04.3 installed with snap
0.19.42 on Windows 10

**Reproducible on current live release:**
Don't know what this means.

### Additional Information
(Why is there a torrent downloader at all? Where do the files go that it downloads?)

**Comment by umutkacar** [comment]
Same issue on;
Brave 0.19.131 on MacOS 10.11.16

**Comment by kjozwiak** [comment]
Still an issue with the latest 0.20.19 BETA:

> Brave: 0.20.19 - Reproducible
> V8: 6.4.388.29 
> rev: 3d05e917690f302c677f4386870ec1721aa0ec01 
> Muon: 4.7.3 
> libchromiumcontent: 64.0.3282.99

**Comment by srirambv** [comment]
Blocked on #13365

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
