### ISSUE TITLE
add error to Transition Overlay if error occurs when changing wallet from BTC -> BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11460]
### Description
BTC --> BAT wallet is taking more time than expected during QA (30-40+ minutes). Per discussions, if an error occurs during this process we should display this error on the transition overlay/progress screen. TBD: wording for this and if we show generic error or raw error. cc @davidtemkin @bsclifton @NejcZdovc 

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**
If error occurs, there isn't an indication on the transition overlay.

**Expected result:**
Error to be displayed, text and what kind of error are TBD.

**Reproduces how often:** [What percentage of the time does it reproduce?] unknown

### Brave Version

**about:brave info:**
Brave | 0.19.43
rev | 24df93d
Muon | 4.4.27

**Reproducible on current live release:**
n/a

**Comment by bsclifton** [comment]
moving to 0.19.x release 2-  for the time being, we can advise folks to run command line with `LEDGER_VERBOSE=true` and share logs.  In order to handle this issue properly, we'd need a decision on what text to show (above) and we'd need to know how it should look 
cc: @bradleyrichter @davidtemkin

**Comment by cezaraugusto** [comment]
adding `needs-info` as this requires input from outside engineering team

**Comment by bsclifton** [comment]
@bradleyrichter is this issue sufficiently addressed by putting "Loading..." in the address field? (see https://github.com/brave/browser-laptop/pull/11771)

**Comment by bsclifton** [comment]
Moving out from milestone 😄  We'll need to solve this. I'll assign myself and document possible error states so that we can create mock ups

**Comment by bsclifton** [comment]
Generic error states:
- can't reach server
- a very specific error is returned from eyeshade (probably not something we want to display as-is)
- a generic 422 or 503 error is returned (server is busy / unprocessable)

**Comment by bsclifton** [comment]
cc: @alexwykoff @bradleyrichter @jenn-rhim for mockup

**Comment by NejcZdovc** [comment]
close it as won't fix, because we should be good now
