### ISSUE TITLE
BAT Wallet shows empty upon upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11462]
### Description
BAT Wallet shows empty upon upgrade

### Steps to Reproduce

  1. Install 0.18.36
  2. Enable payments and fund your wallet
  3. Ensure the pending BTC message is shown below the `Add funds` button
  4. Upgrade to 0.19.43 build
  5. Ensure the conversion overlay is shown informing about BTC->BAT conversion
  6. Wait till the overlay finishes and show payment window
  7. Account balance shows `0.00BAT (0.00 USD)`, doesnt show BAT amount even after ~1 hr after transition is done

**Actual result:**
BAT Wallet shows empty upon upgrade

**Expected result:**
Should show correct account balance

**Reproduces how often:** [What percentage of the time does it reproduce?]
Once
### Brave Version

**about:brave info:**

Brave | 0.19.43
-- | --
rev | 24df93d
Muon | 4.4.27

**Reproducible on current live release:**

### Additional Information

cc: @evq is this related to BitGo transaction delay ?

**Comment by bsclifton** [comment]
I believe this is fixed with the work that @evq did... I'll close for now.  Let's reopen if the issue still occurs

**Comment by srirambv** [comment]
Took ~48 mins for wallet conversion BTC->BAT, Took around ~57 mins for BAT to show up. Working as expected.
