### ISSUE TITLE
Upgrade to 1Password 4.6.11.91

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11461]
Brave currently supports 1Password 4.6.7.90. This issue proposes upgrading to 1Password 4.6.11.91.

Test results with 1Password 4.6.11.91:

- [x] Clicking browser action icon invokes extension logic
- [x] Context menu is populated, and responds
- [x] Credentials are found
- [x] Site forms are filled/submitted automatically
- [x] New passwords can be generated
- [x] Able to login (browser action opens welcome page, which refreshes ad nauseam)

~The above issue is (partially?) triggered by the attempt to remove a non-existing element from the `<body>` element. When stepping around this _throw_, you may briefly see an attempt to open an external application. This window is quickly dismissed, as the page which invokes it is still caught-up in a self-refresh cycle.~

**Resolved:** The user must have the native client installed beforehand

![image](https://user-images.githubusercontent.com/815158/31468206-6927d60e-aea2-11e7-86df-7343a723ba62.png)

**Comment by jonathansampson** [comment]
Closed by https://github.com/brave/vault-updater/commit/328d74b75cb96262302a1b6677b621552dce8765.

**Comment by bsclifton** [comment]
@luixxiul this is not specific to 0.19.x; it was released globally (existing users now have this).  Removing milestone

**Comment by kjozwiak** [comment]
Added the `QA/no-qa-needed` label as this has already been pushed and is live.
