### ISSUE TITLE
(minor) Tab performance - aphrodite stylesheets created during render

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#11465]
### Description

Some of the components used to render tabs are calling Stylesheet.create on every render() call. This was introduced in f9b2a2c543a9f514782c7c689bbe544422d13c9a which was the tab component module split (#8347, #8348). This can create a lot of unnecessary css rules added to the document, and maybe even unnecessary paints.

Affected components:
tab.js
favIcon.js
tabIcon.js

### Brave Version
master - introduced in f9b2a2c543a9f514782c7c689bbe544422d13c9a
**Reproducible on current live release:** Affected code not yet deployed to master

**Comment by cezaraugusto** [comment]
note for QA team: while this is a refactor this is also related to performance so please put something related in release notes, I'm setting for 0.22.x. Thanks

**Comment by petemill** [comment]
Moved to milestone 0.22.x due to requiring it for a clean merge of #12565 and the same / similar test plan for that version.
