### ISSUE TITLE
check if ledger client is busy before attempting transition

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#11464]
it occurs to me that before we tell people that we are beginning the transition process, we ought to see whether the ledger client is busy or not. "busy" means that it still has votes to cast and that if we transition, then those votes will be lost.

the test `if (client.busyP()) { ... }` can be used for this test. if the client busy, then we shouldn't check again until after the next restart.

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/c35d95ac1859cf373b6127df48af39994c3faeb8
0.20.x https://github.com/brave/browser-laptop/commit/3c8e79dff881c9fd19a5fdcd9d56852d43eb33fb
0.19.x https://github.com/brave/browser-laptop/commit/2617c2f6226928aaf6ecc922471334d222f848bf

**Comment by bsclifton** [comment]
I marked as `no-qa-needed` since this is covered by automated tests
