### ISSUE TITLE
Tab 'appear' animations run again when tab is moved

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#11470]
## Test plan

https://github.com/brave/browser-laptop/pull/11501#issue-265163822

----

## Description

Tab 'appear' animations run again when tab element is moved via a new sort order.

![59deb7b94d9cd406032710](https://user-images.githubusercontent.com/741836/31473544-1786afd4-aeaa-11e7-91c3-52938c23bd81.gif)

### Steps to Reproduce

  1. Create multiple tabs
  2. Observe that the tab icon fades in with animation
  3. Change tab order

**Actual result:**

  - Observe that tabs that are moved have their icons fade in with animation again

**Expected result:**
  - no fade-in animation

**Reproduces how often:** always

### Brave Version
master, introduced in 33c5d10c16624eade868e2150ee43b96384ed82c for issue #10883 and PR 

## Test Plan
From PR #10691 / issue #10883 (create smooth transitions for tab components)

- close icon, favicon, private, new session icons will have a smooth transition when enabled
- audio icon will slightly scroll to the right when enabled

Resolving this issue
- Create multiple tabs with favicons
- Have a tab with audio playing and audio icon shown
- Move the tabs around, there should be no flicker off / fade-in of favicon or audio icon
- Repeat with tabs showing private icon, and session icon

**Comment by petemill** [comment]
Moved to milestone 0.22.x due to requiring it for a clean merge of #12565 and the same / similar test plan for that version.

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
