### ISSUE TITLE
Context menu action is sent to the wrong window

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11483]
### Description
When you have more than 1 window open, it's possible to open a context menu and pick an option (like reload) and it sends the action to the other window.

### Steps to Reproduce

(steps were done on macOS; I didn't test on Windows or Linux)
  1. Open two windows:
    - window 1: go to `https://github.com`
    - window 2: go to `https://brave.com`
  2. Make the windows small enough that you can put them side by side
  3. Give window 1 the focus. Select some text using the mouse for example
  4. While window 1 has the focus, right click (or cmd + click) on window 2
  5. Context menu is shown; pick "Reload page"

**Actual result:**
Window 1 is reloaded, even though the context menu was shown inside window 2

**Expected result:**
Window 2 should get the focus and the action should be sent to it

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**
 
Brave: 0.19.46 
rev: c5168d22ef696d3c9cce8e0710aa9fafcbb3d2f0 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
I believe so (but not 100% sure- would have to reinstall 0.18.36 in order to test).

**Comment by Liunkae** [comment]
Confirmed on the current release 0.19.48 on macOS.

**Comment by bsclifton** [comment]
Looks like this has been fixed 😄 👍
