### ISSUE TITLE
Bitcoin to BAT conversion dialog infinitely shown in Payments tab

### ISSUE THREAD

**Issue by aliakyurek** [brave/browser-laptop#11485]
### Description

Bitcoin to BAT conversion dialog infinitely shown in Payments tab since two days. I've been updating to preview builds. So I'm not sure in which version this started.
### Steps to Reproduce

  1. One thing is certain that I didn't have any BTC in my wallet.
  
**Actual result:**

Please wait while we convert your Bitcoin to BAT dialog shown infinitely.
**Expected result:**
Since I didn't have any Bitcoin, this conversion should have proceeded at all. But somehow it started and did not end.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

 
Brave: 0.19.46 
rev: c5168d22ef696d3c9cce8e0710aa9fafcbb3d2f0 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64
**Reproducible on current live release:**

**Comment by srirambv** [comment]
How long has the process been going on? It takes ~40-60 mins to convert the wallet itself (irrespective of the balance)

**Comment by aliakyurek** [comment]
Hi @srirambv 
It started two days ago.

**Comment by NejcZdovc** [comment]
@aliakyurek did you leave your browser open or not this whole time? In the last version we implemented safety mechanism. Do you have backup of any kind from 0.18?

**Comment by aliakyurek** [comment]
- Closed and re-opened several times.  
- No. I don't have any backup.

Is there a workaround to recover from this state (some kind of deleting some files or editing registry etc...). Because uninstall&reinstall didn't work as well.

**Comment by NejcZdovc** [comment]
Did you ever made any contribution with brave payments? What password manager do you use in brave? Do you use sync? Do you use autofill?

**Comment by aliakyurek** [comment]
- No contribution done.
- Password manager: Brave Built-in
- Autofill enabled.
- Sync not used.

**Comment by aliakyurek** [comment]
By the way, when I remove the modal of  "conversion busy indicator" via developer tools, here is the result:
![image](https://user-images.githubusercontent.com/5635699/31491082-c06e8f96-af4e-11e7-9029-4f95e3529e1e.png)

**Comment by NejcZdovc** [comment]
I can easily help you with that then. You will need to modify your session file.

1) Close your browser
2) Go to `%appdata%\brave` and open `session-store-1`
3) search for `btc2BatTransitionPending` and replace `true` with `false`
4) search for `btc2BatTransitionDone` and replace `false` with `true`
5) save file
6) start browser again
7) report results back to me :smiley:

**Comment by aliakyurek** [comment]
Yeah things are easier when we both are developers. :)

- I've found the` btc2BatTransitionPending` key inside session file, it was `true`, I changed it to `false`.
- `btc2BatTransitionDone` was not in file. I've added it under `migrations` with value `true`.
- Restarted browser but again conversion modal shown.

Maybe we need to do something with *timestamp keys?

**Comment by NejcZdovc** [comment]
Yeah let's change `batMercuryTimestamp` and `btc2BatTimestamp` to the current time. This values should be the same. Also don't forget to change `btc2BatTransitionPending` back to `false`.

**Comment by aliakyurek** [comment]
I changed it as the following, but this also didn't work. What if I delete this file at all, and restart browser?
`"migrations":{"batMercuryTimestamp":1507808591,"btc2BatTimestamp":1507808591,"btc2BatNotifiedTimestamp":1507808591,"btc2BatTransitionDone":true,"btc2BatTransitionPending":false}`

**Comment by NejcZdovc** [comment]
Let's try one more thing, before deleting anything. Set `firstRunTimestamp` to the same value that you set `batMercuryTimestamp` and `btc2BatTimestamp`

**Comment by aliakyurek** [comment]
Yes, the last one suggestion worked like a charm @NejcZdovc 
Thx.

**Comment by aliakyurek** [comment]
Closing the issue.

**Comment by rupl** [comment]
I had this same issue except I have previously added BTC to my Brave wallet. It was a small amount but in case others have the same problem I am coming here to attempt to provide more debug info.

I followed the steps already listed in this thread regarding the `bat*` timestamps, but it didn't change anything. Adding the `firstRunTimestamp` prop to my session data did allow me to get back to the payments screen without the "pending" message but my balance says zero. I dug around the app data folder and found my `session-store` backup to restore my config, but the Payments UI returns to this "hung" state when I restore old settings (bookmarks, history, etc).

I never saved my Brave wallet seed, but I'm not worried about recovering the funds. I'm more interested in helping debug this problem.

## `about:brave`

|Name|Version|
|----|-------|
|Brave|0.19.48|
|rev|de939f6|
|Muon|4.4.28|
|libchromiumcontent|61.0.3163.100|
|V8|6.1.534.41|
|Node.js|7.9.0|
|Update Channel|Release|
|OS Platform|macOS|
|OS Release|16.7.0|
|OS Architecture|x64|

**Comment by jamesray1** [comment]
I agree that it is confusing to say "your Bitcoin", since not all users have Bitcoin. I suggest changing the message to something else, e.g.: "Please wait while we convert the unit of account used by Brave Payments from Bitcoin to BAT."

**Comment by despairblue** [comment]
I have the same problem, but I actually had a significant amount of BTC in my wallet.

<img width="853" alt="screen shot 2017-12-18 at 11 19 55" src="https://user-images.githubusercontent.com/927609/34101643-96fe5228-e3e6-11e7-91dd-197a02bdb5b2.png">

I downgraded back to 0.18, which enabled me to see my BTC wallet again and to back it up. Then brave upgraded and I'm back to the waiting screen.

If the conversion does not happen automatically I'm also happy to transfer the funds manually I just need a way to convert the 2 strings I backed up to an actual wallet. 

Is there any documentation about that?

**Comment by NejcZdovc** [comment]
@despairblue you can contact me at nejc[at]brave.com and we can jump on a quick call if you want and I will try to help you out

**Comment by jason-azze** [comment]
I've also been having this problem since October of 2016. I've tried the various combination and permutations of changes to the session file suggested in this issue, but have had no success. It's too bad. I regularly contributed to my account before this change.
