### ISSUE TITLE
Additional footer text causes button misalignment

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11489]
### Description
Additional footer text causes button misalignment

### Steps to Reproduce

  1. Install 0.19.48
  2. Open payments, click add funds
  3. Click any currency icon, buttons are not aligned

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31506982-fe7b1c60-af70-11e7-99fa-455823d34c66.png)

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.48
-- | --
rev | de939f6
Muon | 4.4.28

**Reproducible on current live release:**

N/A

**Comment by luixxiul** [comment]
By setting `display: flex` to the footer button wrapper you'll get:

![buttons](https://user-images.githubusercontent.com/3362943/31509417-5e578f42-afbc-11e7-9274-0b2515207e88.gif)

Removing `easily` from the string you'll get:

![buttons](https://user-images.githubusercontent.com/3362943/31509463-8b8daa3c-afbc-11e7-964f-054bc13268d0.gif)

which looks good on macOS at least. Please make sure this is not a l10n-friendly solution.

**Comment by bsclifton** [comment]
@luixxiul would you be able to fix this up? 😄

**Comment by luixxiul** [comment]
@bradleyrichter which one do you prefer above?

**Comment by NejcZdovc** [comment]
@luixxiul I would go with the first one because of i10n
