### ISSUE TITLE
Brave profile going in local directory from npm start

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11497]
With master 4.5 muon,
`npm start` from browser-laptop and it will create a local folder called brave-development.

cc @bridiver @darkdh

**Comment by darkdh** [comment]
we need to merge https://github.com/brave/browser-laptop/pull/11104 into mastr

**Comment by darkdh** [comment]
or you can change `--user-data-dir` to `--user-data-dir-name`

**Comment by darkdh** [comment]
you need to cherry-pick new force push commit https://github.com/brave/browser-laptop/pull/11104/commits/f8cb7d4c81db6cb3de80066143e1ae2649320571
which contains `package.json` change

**Comment by darkdh** [comment]
0.19.x-cr62: f59ab4c2ac1d811e0732f844c302d19d55fa124e
0.20.x: 5c6f15775ecfe19fb5cd642acae52db990e8238b
0.21.x: 4b350ed56b3d93fe2cd7bd0a32afe9d76e352aa3
master: 81eea0fc483cfd946d7e0643e2f3a76a83234728

**Comment by bbondy** [comment]
0.19.x: 976ba294aafe364526f4e94185f18992820b20a4
