### ISSUE TITLE
Display Favicons in History

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11509]
### Description
The History doesn't presently display a favicon for each entry.

### Steps to Reproduce
Press Ctrl+Y

**Actual result:**
Titles alone are shown.

**Expected result:**
Favicons are displayed, helping the user to more easily distinguish entires.

### Brave Version
0.19.48

### Additional Information
Related to #3050?

**Comment by luixxiul** [comment]
note: I think this requires https://github.com/brave/browser-laptop/issues/2697; otherwise we would release a software which does favicon DDOS.
