### ISSUE TITLE
Transition Overlay displayed when wallet was created in previous version

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11506]
### Description
Transition Overlay is displayed in 0.19.49 when wallet was created with 0.19.48.

### Steps to Reproduce

  1. Clean install 0.18.36.
  2. Check for Updates > update to 0.19.48.
  3. Go to about:preferences#payments
  4. Enable payments. Wait for wallet to be created.
  5. Navigate to Advanced.
  6. Turn on update to preview releases, restart Brave.
  7. Check for updates > Update to 0.19.49.
  8. Navigate to Payments.
  9. Transition Overlay is displayed.

**Actual result:**
Transition overlay is displayed, but since my wallet was previously created this is confusing and seems unnecessary.
![overlay](https://user-images.githubusercontent.com/28145373/31551010-39970bfc-b001-11e7-9544-f75765882f63.gif)

**Expected result:**
No transition overlay displayed.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.49
rev | 0f0a5d6
Muon | 4.4.28

**Reproducible on current live release:**
no

### Additional Information

found on MacOS, reproduced by @srirambv on Win.
Here is ledger_verbose output from Mac: 
[ledger_verbose_output copy.txt](https://github.com/brave/browser-laptop/files/1382912/ledger_verbose_output.copy.txt)

Also, I was not able to reproduce this when starting with a clean install of 0.19.48 (instead of a clean install of 0.18.36).

**Comment by NejcZdovc** [comment]
really nice steps, will take a look on monday

**Comment by LaurenWags** [comment]
Still seeing issue using STR in description when updating to 0.19.52 on MacOS.

![overlay-11056](https://user-images.githubusercontent.com/28145373/31626493-e383af6c-b277-11e7-98bb-fdde7477f7ac.gif)

**Comment by NejcZdovc** [comment]
With this fix we are only covering feature releases. For example scenario you upgrade from 0.18.36 to 0.19.52 (where this fix landed) to 0.19.53. In this scenario this error shouldn't happen anymore.

**Comment by LaurenWags** [comment]
verified working on MacOS using the steps from https://github.com/brave/browser-laptop/issues/11506#issuecomment-336991791
