### ISSUE TITLE
bootstrap script fails

### ISSUE THREAD

**Issue by nolash** [brave/browser-laptop#11514]
Attempting to follow the recipe for dev environment installation in https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions#dev-env-setup-for-adding-a-new-extension the bootstrap script step fails. 

```
$ python script/bootstrap.py -v --target_arch=x64
  File "script/bootstrap.py", line 51
    print "We suggest not running this as root, unless you're really sure."
                                                                          ^
SyntaxError: Missing parentheses in call to 'print'
$ python2 script/bootstrap.py -v --target_arch=x64
usage: bootstrap.py [-h] [-v] [-y]
bootstrap.py: error: unrecognized arguments: --target_arch=x64
$ python2 script/bootstrap.py -v 
Running in verbose mode
/usr/bin/python2 setup.py build
/usr/bin/python2: can't open file 'setup.py': [Errno 2] No such file or directory
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 79, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 32, in main
    setup_python_libs()
  File "script/bootstrap.py", line 60, in setup_python_libs
    execute_stdout([sys.executable, 'setup.py', 'build'])
  File ".../ext/electron/script/lib/util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python2', 'setup.py', 'build']' returned non-zero exit status 2
```

Happens on commit adbd3e0b, but had same problem in my first attempt on cloned repo july 13th (both `master` branch)

Running 4.11.3-1-ARCH, python 3.6.1/2.7.13

**Comment by bsclifton** [comment]
@nolash thanks for noticing! Our docs were a bit out of date.  I went ahead and updated just now 😄 

Please see https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions for more information

**Comment by bsclifton** [comment]
@nolash some other articles you may be interested in, courtesy of our own @jonathansampson:
- [Hacking Chrome Extensions](https://medium.com/@jonathansampson/hacking-chrome-extensions)
- [Testing Chrome Extensions in Brave](https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave)

**Comment by nolash** [comment]
Thanks @bsclifton I will have a read through!

**Comment by nolash** [comment]
@bsclifton sorry to say there were issues there too: https://github.com/brave/browser-laptop-bootstrap/issues/25
