### ISSUE TITLE
Ads are not blocked on a private tab until you reload the tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11511]
### Description

On a private tab ads are not blocked as expected

### Steps to Reproduce

  1. Open http://xxxblink.com/js/pops.test in a new private tab
  2. Make sure the page is loaded
  3. Click reload button
  4. Make sure the page is blocked

**Actual result:**

**Expected result:**

The page should be blocked before you click the reload button

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Brave Version

**about:brave info:**

e1fb1d349d322b32e53b85bd2d2b1a88b3a40696

**Reproducible on current live release:**

### Additional Information

Run `npm run test -- --grep='Bravery Panel'` to confirm that the issue is fixed.

Upgrade to C62
https://travis-ci.org/brave/browser-laptop/builds/287360179

**Comment by luixxiul** [comment]
The failure might be duping to #11518

**Comment by alexwykoff** [comment]
@luixxiul please retest on the latest build when you have a moment, thanks!

**Comment by luixxiul** [comment]
The issue is still reproduced on 0.19.66.

**Comment by bbondy** [comment]
This page is never actually blocked for me

**Comment by bbondy** [comment]
Is it the page should be blocked by safe browsing? Or ads on the page should be blocked?

**Comment by luixxiul** [comment]
That page is used for the webdriver test (fixtures/adblock.html) and I think the page should be blocked inside the iframe. Please see: `downloads and detects regional adblock resources in private tab`.

**Comment by cezaraugusto** [comment]
cc @kjozwiak
