### ISSUE TITLE
"Error: ENOENT: no such file or directory, scandir" on npm run test

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11512]
### Description

By running `npm run test` you get the many errors such as:

````
{ Error: ENOENT: no such file or directory, scandir '/var/folders/9n/qn8fx58s5rd9p438_gvkdssw0000gn/T/brave-test/150792234527038'
    at Object.fs.readdirSync (fs.js:911:18)
    at rmDir (/Users/Suguru/browser-laptop/test/lib/brave.js:35:20)
    at Context.cleanup (/Users/Suguru/browser-laptop/test/lib/brave.js:1204:26)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/var/folders/9n/qn8fx58s5rd9p438_gvkdssw0000gn/T/brave-test/150792234527038' }
````

This error should be fixed to make it easy to read the test log.

### Steps to Reproduce

  1. `npm run test`
  2.
  3.

**Actual result:**

See above.

**Expected result:**

The error should not happen

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

e1fb1d349d322b32e53b85bd2d2b1a88b3a40696

**Reproducible on current live release:**

### Additional Information

The issue seems to have started to appearing since #11499 

Upgrade to C62
https://travis-ci.org/brave/browser-laptop/builds/287360179

**Comment by bbondy** [comment]
I think you just need a new npm install because it is chromium 62 upgrade

**Comment by luixxiul** [comment]
From which job on Travis do these errors disappear? I still see a lot on https://travis-ci.org/brave/browser-laptop/jobs/289192772 for example.

**Comment by luixxiul** [comment]
Reopening in case as it is reproduced on the latest Travis runs: https://travis-ci.org/brave/browser-laptop/jobs/290531592

**Comment by luixxiul** [comment]
@brave/automated-tests-team could you please fix the issue to make the log readable? thanks!

**Comment by luixxiul** [comment]
This error is no longer reproduced on Travis. I'm going to close the issue for now. Let's re-open if we see the errors again 👍
