### ISSUE TITLE
Convert permissions list with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11513]
## Test plan

https://github.com/brave/browser-laptop/pull/11416#issue-264245109

----

### Description

Convert permissions list on about:preferences with Aphrodite

**Comment by luixxiul** [comment]
Closed with #11416

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
