### ISSUE TITLE
Tabs Settings option doesn't work correctly after 0.19.48 update

### ISSUE THREAD

**Issue by NumDeP** [brave/browser-laptop#11526]
Have you searched for similar issues? Yes. Edit: I found a separate issue #11632 of the preview issue which I initially thought was a result of the tab bar not working correctly.

### Description

I've noticed an error in the tab area, which is when you've got 'Select the next tab' chosen in 'When closing an active tab:', it seems to skip or jump a tab every time you close a tab and it if you've got the 'Show tab preview on hover', after it jumps a tab, it shows a preview of the actual tab it should be on without even moving the mouse over tab.

As a matter of fact I don't think any of the options available in 'When closing an active tab' in about:preferences#tabs is functional.

### Steps to Reproduce

Select 'Show tab previews on hover' and right-click and open several youtube videos and I think you'll get a better understanding of it and or open around a dozen or so links and begin closing them. 
As I mentioned above, I don't think it matters if you've got 'Select the next tab' or 'Select its parent tab' selected, you should encounter exactly the same results.

**Expected result:**  A comment of expectation has been made here - https://community.brave.com/t/new-tabs-vs-closing-tabs/8748

**Reproduces how often:** 100%

### Brave Version

Brave: 0.19.48 
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**

Is this a problem with the live build? Yes.

### Additional Information

I didn't want to create another issue as I may be incorrect but previously (I'm probably wrong) whenever I used to to accidentally tear of a tab, closing the tab in the accidentally created new window and pressing Ctrl and T used to re-attach it to the main window and back to its original position, where as now, not only does it not go back to it's original position but it also doesn't display the website the tab was on as it currently displays the Brave dashboard.

**Comment by NumDeP** [comment]
It's also been referenced in the community - https://community.brave.com/t/new-tabs-vs-closing-tabs/8748

**Comment by luixxiul** [comment]
thanks, we'll work on those issues next week.

**Comment by bsclifton** [comment]
cc: @bbondy

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
