### ISSUE TITLE
DOMException: play() can only be initiated by a user gesture

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11527]
### Description

You cannot play tracks on https://di.fm with this error by selecting a station:

````
application-eda7502f5aee7c6b656cd6956e1bbeb5.js:67415 Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.
application-eda7502f5aee7c6b656cd6956e1bbeb5.js:67415 Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.
````

It has been reported that Google Play Music did not work due to the issue. See: https://github.com/brave/browser-laptop/issues/10972. 

### Steps to Reproduce

  1. Go to https://di.fm
  2. Click a station

**Actual result:**

Nothing is played, though you click the station thumbnail by yourself, which should be that `user gesture`.

**Expected result:**

Music should be loaded and played

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Brave Version

**about:brave info:**

 
Brave: 0.19.45 
rev: cddf9a560535f889201fc0157ebf0b982ea19c00 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

Yes

### Additional Information

Affected sites:

- Google Music
- Pandora
- di.fm
- AccuRadio
- http://beirutnights.com/ (https://github.com/brave/browser-laptop/issues/11069)
- Amazon Music
- DuckDuckGo Tracks via search result (SoundCloud)
- VK.com https://github.com/brave/browser-laptop/issues/11988
- deezer.com

**Comment by luixxiul** [comment]
The same issue happens on Google Play Music as well. #10972

**Comment by CyberScooby** [comment]
I encountered the same issue for [AccuRadio](www.accuradio.com) on Windows 8.1. It was working on whatever the official release was prior to 0.19.48.

**Comment by luixxiul** [comment]
Added priority/p3 based on https://github.com/brave/browser-laptop/issues/10972#event-1303228168

**Comment by jonathansampson** [comment]
Impacts Pandora as well: https://twitter.com/gortok/status/930480452279906306

**Comment by luixxiul** [comment]
FWIW: https://github.com/goldfire/howler.js/issues/609, https://github.com/goldfire/howler.js/pull/694, https://stackoverflow.com/a/32571967

**Comment by luixxiul** [comment]
Also DuckDuckGo Tracks via search result is affected

**Comment by julien-l** [comment]
Same for deezer.com (music streaming).

**Comment by jonathansampson** [comment]
Related: https://github.com/brave/browser-laptop/issues/11988

**Comment by eolszewski** [comment]
+1

**Comment by eTorAken** [comment]
Have the same problem on SoundCloud.

**Comment by siliconsorcery** [comment]
No sound from Google Music.

Brave | 0.19.122
rev | 009e792
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Comment by bugchk** [comment]
+1

**Comment by kjozwiak** [comment]
@darkdh I'm still seeing `Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.` within the console here and there when loading http://byblosradio.com/ in a brand new profile using `0.19.125` under Linux. However, after a few seconds, the audio eventually starts playing.

STR:

* load http://byblosradio.com/ within a brand new profile
* open the browser console and you'll notice the above error

However, most of the websites seem like they're working correctly.

**Comment by darkdh** [comment]
that is the different error `Failed to load because no supported source was found.`  which is not related to autoplay
