### ISSUE TITLE
Don't execute script for Dapp detection after being dismissed

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11537]

**Comment by kjozwiak** [comment]
STR/Test Plan:

* visit https://tokenfactory.surge.sh and ensure that you receive the "Dapp" notification
* open the developer tools for https://tokenfactory.surge.sh via "option + cmd + i"
* expand `<head></head>` under "Elements" and ensure that `<meta name="web3-installed">` is present
* ensure "Remember this decision" is selected and click on "No Thanks"
* refresh the page and ensure that you're not getting the "DApp" notification
* open the developer tools for https://tokenfactory.surge.sh via "option + cmd + i"
* expand `<head></head>` under "Elements" and ensure that `<meta name="web3-installed">` is NOT BEING injected into the header
