### ISSUE TITLE
metamask notification is missing the caret extending into trusted UI

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11536]
we show a caret on Brave notification bars to indicate that they are "trusted UI" (not spoofable by a web page). the metamask notification is missing it, but permission notifications have it. 

![screen shot 2017-10-15 at 2 17 56 am](https://user-images.githubusercontent.com/549654/31581033-ae048358-b14f-11e7-97dc-139800bc0c86.png)
^ note the small triangle pointing into the Google tab title area

either it should have the caret or it should appear above the tab bar

**Comment by kjozwiak** [comment]
STR/Test Case:

* create a new tab and visit https://ethwaterloo.herokuapp.com/, ensure that you receive a "Dapp" notification
* create a new tab and visit https://www.stateofthedapps.com/dapps/adchainregistry, ensure that you receive a "Dapp" notification
* create a new tab and visit https://tokenfactory.surge.sh, ensure that you receive a "Dapp" notification
* create a new tab and visit https://leeroy.io/, ensure that you receive a "Dapp" notification
* click through each tab and ensure that the selector caret is correctly pointing to the tab that's currently being selected (example in https://github.com/brave/browser-laptop/issues/11536#issue-265539766)
* ensure that the URL under the notification message and the caret selector are pointing to the correct website
