### ISSUE TITLE
add notification that installs MetaMask when visiting DApp websites

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11532]
### Description

When a user visits a DApp website, Brave should prompt the user if they would like to enabled the MetaMask extension if it's currently disabled via a notification.

### Steps to Reproduce

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://tokenfactory.surge.sh
* ensure that you receive a "This page contains a Dapp, would you like to enable the MetaMask extension?" notification
* click on "Install MetaMask"
* ensure that MetaMask is installed (verify via about:preferences#extensions)
* once installed, refresh  visit https://tokenfactory.surge.sh
* ensure that you can see the "Block Numbers" being updated

### Brave Version

**about:brave info:**

> Brave: 0.19.49 
> rev: 67959340e713e5e9f9e564f764acf493befb9b67 
> Muon: 4.4.28 
> libchromiumcontent: 61.0.3163.100

**Comment by darkdh** [comment]
closed by #11534
