### ISSUE TITLE
metamask notification should be tab-specific

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11535]
the metamask notification refers to the page below it, but it's still there when you switch tabs. ex:

correct tab - 
![screen shot 2017-10-15 at 2 17 18 am](https://user-images.githubusercontent.com/549654/31581024-7264b64c-b14f-11e7-91fa-504a70ef1dd5.png)
 
incorrect tab -
![screen shot 2017-10-15 at 2 17 30 am](https://user-images.githubusercontent.com/549654/31581027-7dff7776-b14f-11e7-94fe-686b104194dc.png)

**Comment by kjozwiak** [comment]
STR/Test Case:

* create a new tab and visit https://ethwaterloo.herokuapp.com/, ensure that you receive a "Dapp" notification
* create a new tab and ensure that you're not seeing the "Dapp" notification that was spawned from https://ethwaterloo.herokuapp.com/
* create a new tab and visit https://brianbondy.com/, ensure you're not seeing any "Dapp" notifications
* create a new tab and visit https://www.stateofthedapps.com/dapps/adchainregistry, ensure that you receive a "Dapp" notification
* create a new tab and ensure that you're not seeing the "Dapp" notification that was spawned from https://www.stateofthedapps.com/dapps/adchainregistry
* create a new tab and visit https://clifton.io/, ensure you're not seeing any "Dapp" notifications
* switch to the https://ethwaterloo.herokuapp.com/ tab, ensure that the "Dapp" notification is still being displayed
* switch to the https://brianbondy.com/ tab, ensure that you're NOT seeing any "Dapp" notifications
* switch to the https://www.stateofthedapps.com/dapps/adchainregistry tab, ensure that the "Dapp" notification is still being displayed
* switch to the https://clifton.io/ tab, ensure that you're NOT seeing any "Dapp" notifications
