### ISSUE TITLE
Preferences can get into a state of not saving when > 100 tabs.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1153]

**Comment by bbondy** [comment]
CC @SergeyZhukovsky

**Comment by bbondy** [comment]
@SergeyZhukovsky do you think it could be the same as this?
https://github.com/brave/browser-laptop/issues/1225

Do you remember if other preferences were not working?

**Comment by SergeyZhukovsky** [comment]
Didn't try other properties sorry. Not sure it is the same, as all links were loading nice for me after restart.

**Comment by luixxiul** [comment]
Not fixed yet?

**Comment by bbondy** [comment]
Probably the same as the process left behind issue which causes state to not be flushed (or the wrong state to be flushed)
