### ISSUE TITLE
Add Brave to Ubuntu software center

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#11546]
### Description

Brave should be available as a package to download through the software center on Ubuntu and Ubuntu based operating systems.

Brave is already available on Ubuntu MATE software boutique but not Ubuntu software center.

How it should be done can be done by following this wiki:
https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages

**Actual result:**

Brave not available in Ubuntu Software Center
**Expected result:**
Should be availiable

**Reproduces how often:** [What percentage of the time does it reproduce?]
All the time

### Additional Information

I would be very happy to try this out when somebody fixes this 🙂

**Comment by posix4e** [comment]
Seems reasonable

**Comment by srirambv** [comment]
+1

**Comment by Jacalz** [comment]
Brave is available in the software center from the Snap store so this would be fair to close now...
