### ISSUE TITLE
Website specific keyboard shortcuts do not work after task switching in windows

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1154]
Certain websites have keyboard shortcuts on which actions are taken. Examples include gmail (you have to enable shortcuts in the settings first), trello and many other websites.

Shortcuts work when you browse to these websites. For instance, in gmail and trello typing the '?' key shows a help div.

When you switch to another window using Alt+Tab and return to Brave, the shortcut does not work. Clicking in the Brave browser makes the shortcut work again.

Steps:

- launch brave.exe
- go to gmail or trello and log in
- press '?': the help shows
- press Alt+Tab or Win+E to switch the focus
- press Alt+Tab to come back to Brave
- press '?': does not work

Expected: the help shows
Actual: the help does not show

**Comment by bradleyrichter** [comment]
sounds like a focus state init problem. @bbondy ?

**Comment by tetrode** [comment]
Also the following scenario:
- open a long web page (I used nytimes.com)
- use down arrow, up arrow to scroll: works OK
- Alt-tab away to another app (or select one from the task bar)
- return to the browser
Expected:
- down arrow, up arrow works to scroll the page
Actual:
- down arrow, up arrow do not work

By clicking within the page, down arrow, up arrow automagically start to work again.

**Comment by bradleyrichter** [comment]
@bbondy seeing several requests for this and just tested 0.9.1 and it's still an issue. Can we try to get this in?

**Comment by bbondy** [comment]
@bradleyrichter yep!

**Comment by bbondy** [comment]
See also this which was fixed:
https://github.com/brave/browser-laptop/issues/1406
