### ISSUE TITLE
Error: Cannot find module '../../../js/state/siteUtil'

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11541]
### Description

````
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module '../../../js/state/siteUtil'
````

### Steps to Reproduce

  1. git fetch upstream master && git rebase upstream/master
  2. npm run watch
  2. npm start

**Actual result:**

See above.

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

b3f61eebcd6849631df5cf58dbb8faa7699e9952

**Reproducible on current live release:**

No.

**Comment by bsclifton** [comment]
This may need to be uplifted into 0.21.x
cc: @bbondy, @kjozwiak

**Comment by bbondy** [comment]
0.21.x: e75eba5df5e98b9729b2ab53498584cb971ccf39
