### ISSUE TITLE
Publishers auto-included  even with auto-include switch disabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11553]
### Description
Publishers auto-included  even with auto-include switch disabled 

### Steps to Reproduce

  1. Enable payments  in 0.18.36
  2. Upgrade to 0.19.48 so that wallet is converted to BAT
  3. While conversion is happening, disable the auto-include switch
  4. Visit some random sites, some of them gets auto included even though `auto-include` switch is turned off

**Actual result:**
Publishers auto-included  even with auto-include switch disabled

**Expected result:**
No publisher should be included if auto-include switch is turned off

**Reproduces how often:** [What percentage of the time does it reproduce?]
Reproduced and confirmed by @LaurenWags 
### Brave Version

**about:brave info:**

Brave | 0.19.48
-- | --
rev | de939f6
Muon | 4.4.28

**Reproducible on current live release:**

Yes 

### Additional Information

#7451 #7850

**Comment by NejcZdovc** [comment]
@srirambv so this is only when you toggle auto-include while in transition?

**Comment by srirambv** [comment]
I guess not. I just put the steps that I followed. @LaurenWags could you confirm if you had the same STR

**Comment by LaurenWags** [comment]
Yes, that is the STR I followed.
