### ISSUE TITLE
Build Target Request : Support for Chromebooks

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#11555]
### Description
Users from the field have asked for support by building an install for Chromebooks. 

### Steps to Reproduce
  1. Own a Chromebook
  2. Attempt to install Brave

**Actual result:**
No install available

**Expected result:**
A user should be able to install the worlds most amazing browser

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 😺

**Comment by Jacalz** [comment]
Does this intend to go through the google play store?

**Comment by Zach-15803** [comment]
Probably would build our own Chromium build and replace Chrome with Brave, and make it lighter and faster to run,
