### ISSUE TITLE
allow proper support of large amount of data in tabular content

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#11551]
For now, [we limit our history entries to 500](https://github.com/brave/browser-laptop/blob/master/app/common/lib/historyUtil.js#L9) due to rendering issues of large amounts of data. This may also happen with a very long list of publishers in ledger and issue is very clear w/ the upcoming cookie manager. 

We should make a way to show long lists of tabular data in a progressive way to avoid browser freeze due to memory consumption and rendering issues.

**Comment by cezaraugusto** [comment]
changing milestone to 0.21.x to match #11107

**Comment by bsclifton** [comment]
This is not something we'll be able to address before switching over to the Chromium UI (Brave Core)
