### ISSUE TITLE
Brave window title bar is not set consistently

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1155]
The window title bar (blue windows bar with brave icon on the left, minimize, maximize, close on the right) is not set correctly.

Scenario:
- start brave or open a new window
- go to a website from bookmarks, or type a URL
Expected: title bar reflects the ``<title>`` attribute
Actual: title bar remains 'New Tab'

- Alt-Tab away from it and come back
- title bar remains 'New Tab'
- resize the window
Now the title bar reflects the html page title

- add a new tab
Actual: Title still shows the previous title
Expected: show Brave just as when opening a new window

**Comment by luixxiul** [comment]
Not reproducible with the latest version, closing for the moment. Thanks for your report.
