### ISSUE TITLE
Handle all bad state scenarios for the ledger

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11566]
### Description
Scenarios where the user can be in a bad state:
-  [x] Wallet disabled before upgrade (from 0.18.x => 0.19.x), then they enable it #11626
-  [x] User upgrades from 0.18.x => 0.19.x... transition completes. Then they get notice for another upgrade #11552
-  [ ] User can be in a bad state if they experienced the number 2 bug before 0.19.52 version #11506

**Comment by srirambv** [comment]
Should the payment on/off switch also be disabled during wallet transition so that it avoids the wrong amount to show up when its turned off/on
![image](https://user-images.githubusercontent.com/17010094/31665662-8125b19c-b341-11e7-9ca3-029c8525b1e5.png)

**Comment by bsclifton** [comment]
+1 from https://community.brave.com/t/bitcoins-from-previous-wallet-never-made-it-to-new-bat-wallet/9086/7

**Comment by LaurenWags** [comment]
@NejcZdovc will this issue cover the bad state users get into when the toggle payments on/off during transition?  cc @evq

**Comment by NejcZdovc** [comment]
@LaurenWags not sure that I understand the question

**Comment by srirambv** [comment]
@NejcZdovc Its the case when user turns off payment after the transition overlay is shown and then enables payment causing the crazy USD amount to show up for BAT.

**Comment by NejcZdovc** [comment]
ok will check that out as well, right now I am working on the first one. Created issue for it https://github.com/brave/browser-laptop/issues/11611

**Comment by LaurenWags** [comment]
thanks @NejcZdovc - a lot of users are doing as @srirambv described and that's definitely causing some kind of problem.

**Comment by bsclifton** [comment]
Checking this one out now... looks like unit tests were missed when adding the new transition flag (and there's also a part which reads using a misspelling of the state).  Working on a fix now...

**Comment by LaurenWags** [comment]
Still seeing overlay in 0.19.82 when I shouldn't be. STR:
Clean install 0.18.36
Update to 0.19.48
Enable Payments, wallet is created
Update to 0.19.49 (any version prior to 0.19.52 per https://github.com/brave/browser-laptop/issues/11506#issuecomment-336991791)
You will see the overlay transition on Payments page when it is not needed as your wallet was already created in previous version.
Update to 0.19.82.
You will still see the overlay transition, it does not go away.

**Comment by srirambv** [comment]
Scenario mentioned in https://github.com/brave/browser-laptop/issues/11566#issuecomment-342930339 doesn't happen anymore. Upgrading from 0.19.48 with v2 wallet doesn't show transition overlay on 0.19.87
