### ISSUE TITLE
footer buttons for adding BAT funds looks janky

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#11567]
### Description
"Previous" / "Done" buttons are collapsed and look terrible.

### Steps to Reproduce

  1. select the brave payments settings and click "add funds", observe footer

**Actual result:**
<img width="702" alt="screen shot 2017-10-16 at 12 12 56 pm" src="https://user-images.githubusercontent.com/28946/31630573-d254d4de-b26b-11e7-827d-b7c19e850745.png">

**Reproduces how often:** 100%

### Brave Version

**about:brave info:**
0.19.48

**Comment by kjozwiak** [comment]
Thanks for the report @patrick99e99! This is going to be fixed in the next `0.19.x` hotfix via #11489.
