### ISSUE TITLE
Metamask popup has scrollbars

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11561]
### Description
Metamask popup has scrollbars

### Steps to Reproduce

  1. Clean install 0.19.52
  2. Enable Metamask
  3. Popup has scrollbar and text is magnified

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31626525-f67aafc4-b2a1-11e7-8245-2346ae750098.png)
![image](https://user-images.githubusercontent.com/17010094/31626536-ff5ee4f2-b2a1-11e7-9a04-d7b1a15786ad.png)

**Expected result:**
Should not have scrollbar, text should be normal

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.19.52
-- | --
rev | c40e249
Muon | 4.4.29

**Reproducible on current live release:**

No

**Comment by bbondy** [comment]
not blocking this release and probably related to the already existing DPI one so I'm removing milestone.

**Comment by bsclifton** [comment]
This may be related to https://github.com/brave/browser-laptop/issues/7051

Removing Cezar since this is likely DPI related

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/metamask-extension-scaling-issues/10865?u=eljuno
