### ISSUE TITLE
Set as default browser doesn't work on Linux

### ISSUE THREAD

**Issue by agilob** [brave/browser-laptop#11562]
### Description
Clicking on set as default browser doesn't work. Brave is not set as default browser and the text above the button doesn't change from `Brave is not your default browser.`.

### Brave Version

**about:brave info:**
 
Brave: 0.19.48 
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.5-1-ARCH 
OS Architecture: x64

### Additional Information
Installed from https://aur.archlinux.org/packages/brave-bin

**Comment by bsclifton** [comment]
cc: @darkdh who recently made changes with this

@agilob what window manager are you using?  @darkdh had fixed this (and I tested) on GTK based window managers, like Gnome and Unity

**Comment by agilob** [comment]
>@agilob what window manager are you using?

Plasma5

**Comment by darkdh** [comment]
@agilob ,

Could you run these commands on your terminal and tell us the result of it?
```
xdg-settings get default-web-browser
xdg-settings check default-web-browser brave.desktop
xdg-settings get default-url-scheme-handler http
xdg-settings get default-url-scheme-handler https
xdg-settings check default-url-scheme-handler http brave.desktop
xdg-settings check default-url-scheme-handler https brave.desktop
```

Thanks

**Comment by agilob** [comment]
```
➜  ~ xdg-settings get default-web-browser
brave.desktop
➜  ~ xdg-settings check default-web-browser brave.desktop
no
➜  ~ xdg-settings get default-url-scheme-handler http
firefox.desktop
➜  ~ xdg-settings get default-url-scheme-handler https
firefox.desktop
➜  ~ xdg-settings check default-url-scheme-handler http brave.desktop
no
➜  ~ xdg-settings check default-url-scheme-handler https brave.desktop
no
```

I think this might be useful, when I went to control panel and checked default browser there, there was no default:

![screenshot_20171017_210120](https://user-images.githubusercontent.com/2544251/31686590-75cbe842-b37e-11e7-96fd-5d379f4aa156.png)

So I clicked on a link in thunderbird, the link was opened in firefox. I cltr+click on a link from a terminal and it was also opened in firefox.

Brave is available on the list of browsers but wasn't set:
![screenshot_20171017_210343](https://user-images.githubusercontent.com/2544251/31686696-c50925be-b37e-11e7-9af3-74c9298704b5.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/setting-brave-as-default-browser-causes-firefox-to-be-launched-instead/9435?u=eljuno

> After installing brave, it asks if you want to set it as your default browser. Whether doing this at this time, or later through the settings menu, whenever a link is clicked from some other program that’s expected to launch the default browser (e.g. Mozilla Thunderbird), Firefox ends up getting launched instead.

User use Ubuntu

>Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.10.0-35-generic 
OS Architecture: x64
