### ISSUE TITLE
Non focussed windows still have the title bar color of a focussed window

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1156]
Scenario:
- start brave
- open a new window

Expected
- one window (the focussed one) has the blue window title bar appearance of a focussed window, the other one has the grey window title bar appearance
Actual
- both windows have a blue bar

Environment
- Windows 7, classic view.

**Comment by bradleyrichter** [comment]
@tetrode if you have a chance, could you post a screen shot please?

**Comment by tetrode** [comment]
Screenshot here: http://imgur.com/LAFhzl1 after pressing Ctrl+N a couple of times

**Comment by bradleyrichter** [comment]
ah ha! Thanks @tetrode 

This will go away as soon as we can fix an Electron "bug" that allows us to remove that extra title bar like Chrome does. 

@bridiver If that is too far out, then we should try to fix this...

**Comment by tetrode** [comment]
@bradleyrichter Are you planning to change the title bar / browser URL / bookmarks / tabs area?

For me this is using too much space compared to other browsers. WRT real estate, IE, FF, Chome are  doing much better, using only halve of the area Brave is using

**Comment by bradleyrichter** [comment]
I recently reduced the total stackup and at least on Mac OS, we are now 2 pixels shorter than Chrome, and much shorter than FX.

You might be seeing the extra title bar on Windows which we are trying to remove soon?

mac:

![image](https://cloud.githubusercontent.com/assets/13509546/14004052/8ccc3d2c-f114-11e5-86bb-bc07aa607d2e.png)


Would you mind posting a similar screen shot from Win7 or 8?

**Comment by tetrode** [comment]
Here you are

[image: Inline image 1]

Best

Mark
+ 32 474 92 06 59
.

**Comment by bsclifton** [comment]
Would be good to retest when https://github.com/brave/browser-laptop/issues/3036 is resolved (coming soon)

**Comment by bsclifton** [comment]
This is now fixed and will be released w/ 0.12.6 :smile: (specifically was resolved with PR https://github.com/brave/browser-laptop/pull/4856)
