### ISSUE TITLE
Only run dapp detection if metamask is not installed

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11569]

**Comment by bbondy** [comment]
0.19.x: 911febce11930113038670990f8d1ecc350abb9c
0.20.x: edabfa02ec0778ae0bcff11cb08e03c4d1aa1110
0.21.x: 3113e670ef8f8aa2ab2e366761b0c1c0cb07459c
master: 843bcc64f94a844cb962e3e4e123ba0c60926c4b

**Comment by kjozwiak** [comment]
STR/Test Cases:

Case 1:

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://ethwaterloo.herokuapp.com/
* ensure that you receive a "This page contains a Dapp, would you like to enable the MetaMask extension?" notification
* click on "Install MetaMask"
* ensure that MetaMask is installed (verify via about:preferences#extensions)
* click on the "MetaMask" icon that appears next to the "Brave" shield icon
* accept the terms and quickly create a new account
* click on "I've copied it somewhere safe" under "Vault Created"
* select the "Ropsten Test Net" from the MetaMask dropdown menu
* under https://ethwaterloo.herokuapp.com/, refresh the page and select "Go" and ensure the app loads a blockchain map

Case 2:

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://ethwaterloo.herokuapp.com/
* ensure that you receive a "This page contains a Dapp, would you like to enable the MetaMask extension?" notification
* click on "No Thanks" and ensure "Remember this decision" is selected
* refresh the website and ensure that the notification isn't being displayed anymore
* visit https://tokenfactory.surge.sh and ensure that the notification isn't appearing

Case 3:

* ensure MetaMask is enabled via about:preferences#extensions
* visit https://ethwaterloo.herokuapp.com/ and ensure that the "DApp" notification isn't being displayed
* visit https://tokenfactory.surge.sh and ensure that the "DApp" notification isn't being displayed

Case 4:

* ensure MetaMask is disabled via about:preferences#extensions
* visit https://brianbondy.com/, https://www.facebook.com, https://www.twitter.com
* ensure that the "DApp" notification isn't being displayed
