### ISSUE TITLE
Extension page opens with each browser launch

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11578]
### Description
Metamask site opens with each browser launch

### Steps to Reproduce

  1. Install 0.19.54
  2. Install metamask extension, ensure https://metamask.io/#how-it-works page is launched in a new tab, keep the tab open
  3. Close the browser and restart, a new tab is launched with https://metamask.io/#how-it-works along with the existing one from step 2

**Actual result:**
Metamask site opens with each browser launch

**Expected result:**
Should only launch when the extension is enabled 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

### Brave Version

**about:brave info:**

Brave | 0.19.54
-- | --
rev | 7ce342d
Muon | 4.4.29

**Reproducible on current live release:**

Yes

**Comment by aekeus** [comment]
Confirmed on osx

**Comment by eljuno** [comment]
I think it's not limited to MetaMask? I have Honey installed and it open honey page every startup.
Same from community https://community.brave.com/t/honey-extension-keeps-showing-installation-success-webpage-after-i-open-brave/9291?u=eljuno

And this one, user reported for bitwarden https://twitter.com/exeo5/status/920785451560009728

**Comment by maurelian** [comment]
Also seeing this with both metamask and honey. I disabled honey due to this. 
No such effect is seen with pocket or 1pass.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/issues-with-extention-plugins/9438?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/metamask-opens-welcome-tab-every-time-the-browser-is-opened/9539?u=eljuno

**Comment by kjozwiak** [comment]
Verified by checking both `metamask` & `Honey` using the STR mentioned in the original comment https://github.com/brave/browser-laptop/issues/11578#issue-266157369
