### ISSUE TITLE
Page data refactor

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11575]
## Test plan

https://github.com/brave/browser-laptop/pull/11592#issue-266394313

----

### Description

Refactor page data so that we handle about pages as well.

**Comment by kjozwiak** [comment]
@NejcZdovc, is there anything QA can do here? Maybe load all the `about:` pages listed under `about:about` and ensure they're all being loaded/behaving correctly?

Can we remove the `PR/pending-review` label now that this has been closed? It looks like it's been reviewed by @bbondy in https://github.com/brave/browser-laptop/pull/11592.

**Comment by NejcZdovc** [comment]
test plan is specified in #11592

**Comment by LaurenWags** [comment]
Test Plan C from linked test plan does not produce the expected results.

**Comment by srirambv** [comment]
For plan C the view count is staying as 1 when the tab switch back to old site. Reloading the page and staying for another 15 sec just adds the time not the view. But opening the site in a new tab view count goes up to 2 and adds the time.

**Comment by NejcZdovc** [comment]
@LaurenWags @srirambv I think this is the same problem as defined here https://github.com/brave/browser-laptop/issues/11633. Will close it for now. If you find anything else please create another issue for it.

**Comment by srirambv** [comment]
@NejcZdovc I think the steps are a little different.  For Plan C this is what I followed
1. Enable payments
2. Visit site in tab 1 stay for 15 secs
3. Visit different site in tab 2, stay for 15sec
4. Switch back to tab 1, stay for 15 secs
5. Payment shows view count 1 for both sites, and site from tab 1 has 30+secs and site from tab 2 has 15+sec

But as per steps in #11633, you mention stay on site for 2sec, which will not be added as the min time is not validated. Switching back and forth and staying on site for 15+ secs will add the view count as 1 as it would have satisfied the min time visit criteria

**Comment by NejcZdovc** [comment]
@srirambv this Plan C is ok, because you switched back to existing tab you are basically revisiting site, so there shouldn't be counted as a new view, so view count should be 1

**Comment by NejcZdovc** [comment]
I think that Plan C is not valid, will change it

**Comment by LaurenWags** [comment]
https://github.com/brave/browser-laptop/issues/11685 logged for issues with test plan D from https://github.com/brave/browser-laptop/pull/11592#issue-266394313. Other tests passed on MacOS.
