### ISSUE TITLE
Cannot play some media resources

### ISSUE THREAD

**Issue by igorlash** [brave/browser-laptop#11573]
### Description

After updating to version 0.19.53 some media resources cannot be played. 

### Steps to Reproduce
  1. Open this url https://forvo.com/word/associated/#en
  2. Click any play button.

### Brave Version

Brave version 0.19.53

### Additional Information
Reproducible on Windows 10 and Linux Mint 18.2

**Comment by igorlash** [comment]
This problem is not reproducible in Brave version 0.19.131 any more. 
I have checked on LinuxMint and Windows 10. 
Looks like it was fixed.

**Comment by luixxiul** [comment]
Thanks for checking.
