### ISSUE TITLE
"makensis.exe is not recognized as an internal or external command,"

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#11571]
### Description
Whenever I go to run` npm run build-package` I get to the making for Electron page, but then eventually I get a big wall of text. Something about makensis and then the buildPackage

Node: v8.6.0
NPM: 5.3.0

### Steps to Reproduce

  1. Have Node 8.6.0
  2. Python 2.7.14
  3. Run Npm install
  4. Once it gets to Packaging app for Electron
  5. a few seconds later it should spit out what is in "Actual Result"

**Actual result:**

```
'makensis.exe' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
```

Along with: 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.21.0 build-package: `node ./tools/buildPackage.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.21.0 build-package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\legit\AppData\Roaming\npm-cache\_logs\2017-10-17T01_28_02_080Z-debug.log
```

Add screenshots if needed
https://i.imgur.com/vhFwoZ2.png

**Expected result:**
To be able to build with no errors. I didn't used to get the makensis error. Not sure what happened

**Reproduces how often:** Everytime

### Brave Version
N/A (Compiling error)

### Additional Information
N/A

**Comment by bsclifton** [comment]
@JMccormick264 this is expected if you don't have NSIS installed.  We have more documentation about the packaging process here:
https://github.com/brave/browser-laptop/wiki/Packaging-for-bundles,-installers,-and-updates#windows-7810-x64
