### ISSUE TITLE
Brave starts but window not shown

### ISSUE THREAD

**Issue by aliakyurek** [brave/browser-laptop#11588]
## Possible repro steps (per https://github.com/brave/browser-laptop/issues/3558)
  1. Use a Laptop with Windows
  2. Plug in external monitors
  3. Leave Brave Open
  4. Reboot Laptop
  5. ???
  6. Attempt to open Brave
  7. Cannot see `ui` window

### Steps to Reproduce

  1. Execute Brave executable
  2.
  3.

**Actual result:**

![image](https://user-images.githubusercontent.com/5635699/31702779-f92a2146-b3e1-11e7-8429-d217da5e2a70.png)

**Expected result:**
Main window shown.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Couldn't add since the window now shown. But the latest update applied was v0.19.53.
**Reproducible on current live release:**

**Comment by luixxiul** [comment]
on which OS?

**Comment by aliakyurek** [comment]
![image](https://user-images.githubusercontent.com/5635699/31704010-0a62fe6e-b3e8-11e7-9f31-fc65e17f8be1.png)

64-bit

**Comment by aliakyurek** [comment]
Deleting session-store file fixed the issue. Of course I backed it up first. If you want to ask some values inside it, please let me know.

**Comment by aliakyurek** [comment]
Thx @shortstuffsushi 
Yeah same problem. Workaround mentioned there didn't work. Because mentioned keys are no more available in session-store-1 file.

Instead I've found the current keys for ui positioning in 0.19.53:
"defaultWindowParams".
There I set x and y to 0. Now I can see window again. :)

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-windows-off-screen-are-especially-difficult-to-return-to-main-display/30763

**Comment by srirambv** [comment]
@bsclifton this is fixed in brave-core. Ok to close the issue?

**Comment by bsclifton** [comment]
@srirambv yup! let's close it out
