### ISSUE TITLE
reduce size of session-store-1 by removing 'data:' URLs

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11582]
## Test plan

https://github.com/brave/browser-laptop/pull/11754#issue-270469950

----

My production session-store-1 file is now 23MB. `egrep -o '"data:(.+?)"'` shows that nearly 80% of this (18MB) of this is `data:` URLs, mostly favicons it seems. We should investigate if the favicons can be moved to external files or replaced with links to the favicon URL.

**Comment by bridiver** [comment]
see https://github.com/brave/browser-laptop/commit/11a2bc4849eade05eec5ba603be8298684aee64e#diff-70ca3257d79251708167c6ce9bf1cd81
You may have some leftover in your session store, but there shouldn't be any new ones being created

**Comment by diracdeltas** [comment]
i think most/all of the data URLs are from external sites which use data: URLs as their favicon URL

**Comment by NumDeP** [comment]
@diracdeltas I made a bloody inference to this here #10975 and you completely blanked me. I've been waiting around like a nervous hooker.

**Comment by bsclifton** [comment]
@NumDeP she ( @diracdeltas) wasn't involved with that issue, I was.  There are thousands of issues in our backlog, so even though I was involved I had to re-read the details

I don't see any reference to data URL/URIs in that issue, so I wasn't ignoring you

Let's keep things civil here- we want to help 😄

**Comment by NumDeP** [comment]
Sorry. It's just that from all the crashes I've been hoarding all the S-S-1's locally and going through the process of going through unnecessary data.

**Comment by bsclifton** [comment]
@NumDeP I understand your frustration- there are a lot of small details that we're constantly evaluating and trying to assess the priority for (if you use GitHub's `Watch` feature for this repo for a few days, you'll get a sense of how many requests we get).

If you have a suggestion for what we can remove, that is appreciated.  Please do know that harassment of any kind (including comments or language which make a contributor uncomfortable) is not welcomed

We keep a fairly up to date record of what goes into the session store here:
https://github.com/brave/browser-laptop/blob/master/docs/state.md

If you find data that you think can be removed, please open an issue.  If you're not comfortable with making a PR, we should be able to help make the change (or we could also give it some visibility by tagging it as `good-first-bug` or similar).

**Comment by diracdeltas** [comment]
i have a fix for this, it seems to help for performance but would be good to test against a benchmark

**Comment by diracdeltas** [comment]
added ledger label because all the data favicons i had were from the ledger

**Comment by bsclifton** [comment]
Moving to 0.20.x (as the next 0.19.x release is reserved for Chromium 63)
