### ISSUE TITLE
ledger persists newClient but restores it to newClient.state

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#11585]
aka yo dawg I heard you lik state

This issue can lead to an unlimited wait while performing conversion from BTC->BAT. We should be persisting `newClient.state` instead essentially. We will need some recovery logic to rescue improperly persisted state files.

This issue was originally noted in - https://github.com/brave/browser-laptop/pull/11495

It was marked as a bat-client issue, but I've closed that issue since it is actually due to browser-laptop persistence of the client - https://github.com/brave-intl/bat-client/issues/18

**Comment by kjozwiak** [comment]
@evq should we put this into [`0.19.x Hotfix 2`](https://github.com/brave/browser-laptop/milestone/86) since the milestone will mostly concentrate on ledger/payment fixes/improvements?

**Comment by evq** [comment]
Yes, let's target [`0.19.x Hotfix 2`](https://github.com/brave/browser-laptop/milestone/86)

**Comment by kjozwiak** [comment]
@evq are the STR in https://github.com/brave/browser-laptop/pull/11495#issuecomment-336361446 sufficient for this issue/case?

**Comment by evq** [comment]
@kjozwiak yes, those steps are sufficient - I was able to reproduce using them

**Comment by kjozwiak** [comment]
Test Case to be used: https://github.com/brave/browser-laptop/pull/11495#issuecomment-336361446
