### ISSUE TITLE
Selected form item is no longer selected when focus is lost and regained

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1158]
Scenario:
- You are at a web page with a form where you need to put in multiple fields
- you select the field that you want to put information in
- The information that you need to put in is located in another (windows) application
- You use Alt+Tab to go to the other application to select the information and select and copy the information to the clipboard
- You press Alt+Tab again to go back to Brave
Expected:
- the field that you selected previously is still selected
Actual:
- no field is selected, you need to click with your mouse to select the field and then you can paste information.

Background
I'm using KeePass a lot keep track of 500+ passwords for different sites. It has a nice feature to paste username/password to sites - this is working for Chrome, FF, IE but not for Brave, due to this issue.

**Comment by luixxiul** [comment]
Duping to #957
