### ISSUE TITLE
Error: HTTP response 503 & Error: HTTP response 422

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11590]
### Description

As discussed in our triage meeting, these issues will be fixed via server side. Created the following bug as reminder so QA tests and makes sure that the errors that are listed below are not happening once the fixes have landed on the server.

**Actual result:**

```
Error: HTTP response 503 for GET /v2/registrar/persona
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.52\resources\app.asar\app\browser\api\ledger.js:1491:9)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.52\resources\app.asar\js\lib\request.js:55:5)
```

```
ledger client error(3): {}
Error: HTTP response 422 for POST /v2/registrar/persona/9ca4e85d6a51d84bcea9e99ec621025
    at request.request (/usr/lib/brave/resources/app.asar/app/browser/api/ledger.js:1491:9)
    at Function.defaultSession.webRequest.fetch (/usr/lib/brave/resources/app.asar/js/lib/request.js:55:5)
```

### Brave Version

**about:brave info:**

> Brave: 0.19.53 
> rev: e09025bf61debc46c03459def2501b3367f182d7 
> Muon: 4.4.29 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

Yes, the above errors have appeared in the released version as well.

**Comment by evq** [comment]
The 422's have no associated server side fix, they will be solved by #11601

**Comment by srirambv** [comment]
Reopening and moving to hotfix3 as its not completely resolved and still occurring, but not as often as before

cc: @kjozwiak @LaurenWags

**Comment by bsclifton** [comment]
+1 from @srirambv via https://github.com/brave/browser-laptop/issues/11881
> Console throws Error: HTTP response 503 for GET /v3/publisher/timestamp

**Comment by NejcZdovc** [comment]
I will close this one, because I think that things were fixed. Please reopen if it's still happening.
