### ISSUE TITLE
update HTTPS Everywhere

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11598]
latest version is 2017.10.4

**Comment by diracdeltas** [comment]
there are some breaking ruleset format changes which will require updates to all Brave clients: https://github.com/brave/browser-laptop/issues/10976#issuecomment-340223921

**Comment by btlechowski** [comment]
Verified on Windows 7 x64
* 0.22.7  8bb7e77f
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
