### ISSUE TITLE
Pressing the shortcut key for the address bar followed by Esc does not cancel it

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1159]
Scenario:
- open Brave
- go to a web site
- use Ctrl+D or cick on the address bar
- try to cancel it by Esc
Expected:
- the address bar selection is undone
Actual
- the address bar is stil selected

**Comment by bbondy** [comment]
I think this is as expected, both Chrome and Firefox also maintain the selecting when you press Esc.  lmk if I'm missing something though and I can re-open.
