### ISSUE TITLE
Metamask contentscript is injected on about pages when it should not be

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11596]
### Description:

Metamask contentscript is injected on all pages when enabled
### Steps to Reproduce

Scenario 1
  1. Clean install 0.19.53/54/57
  2. Enable metamask from extensions
  3. Open a new tab and visit any site
  4. Open dev tools, shows metamask content script injected (image 1)

Scenario 2
  1. Clean install 0.19.53/54/57
  2. Do not enable metamask from extensions
  3. Enable 1password
  3. Open the 1password background page by navigating to: chrome-extension://aomjjhallfgjeglblehebfpbcfeobpgk/_generated_background_page.html
  4. Shows error in console for inject script (image 2)

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/31735885-10f26ee2-b43b-11e7-9e8b-d5619921bcf5.png)
![image](https://user-images.githubusercontent.com/17010094/31735936-3cdd1458-b43b-11e7-897b-ebd83f9479aa.png)

**Expected result:**
Should only inject script where required

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

### Brave Version

**about:brave info:**

Brave | 0.19.57
-- | --
rev | 2d55158
Muon | 4.5.4

**Reproducible on current live release:**

Yes 
### Additional Information

cc: @bbondy

**Comment by bbondy** [comment]
Is this still valid @srirambv ? I thought I fixed this in the last hotfix.

**Comment by bbondy** [comment]
ok makes sense now, I was confused by the title, but after reading the description it makes sense.

**Comment by bbondy** [comment]
Scenario 1 is no problem by the way

**Comment by bbondy** [comment]
master: 27f4a4e656dac8a9e38c15474b638293f12178ed
0.21.x: 010c0bdaf2ce03f30115d5455240ad944952fbd3
0.20.x: 6e8dc88bb9b5072693e6cd303fa143342c50e11d
0.19.x: 5484ba6b8b2ab07761d5a0fcefeb9af256ded81a
