### ISSUE TITLE
Autoplay allow dialogue intermittently failingto clear

### ISSUE THREAD

**Issue by psmalone** [brave/browser-laptop#11594]
### Description
When opening some sites that have autoplay media, the bar to autoplay fails to clear, whether "Yes" or "No" is checked. I have had this change to proper function on a given site ( http://tv.com ) with a restart, but it does not change on a tab refresh.

### Steps to Reproduce

  1. Open a new tab that has autoplay media (e.g., https://inbox.google.com )
  2. Select any combination of "Remember this decision" and "Yes" or "No"

**Actual result:**
No response to selecting Yes or No. Bar stays visible. Screenshot.
![screenshot 2017-10-18 10 54 24](https://user-images.githubusercontent.com/23506653/31725928-8fc97eec-b3f3-11e7-92dd-7e67feb03a0a.png)

**Expected result:**

Bar clears and setting is in effect

**Reproduces how often:** [What percentage of the time does it reproduce?]

10%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.19.53
rev | e09025b
Muon | 4.4.29
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 16.7.0
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Closing as I believe this issue has been addressed

@psmalone do you still encounter this? We've recently pushed autoplay improvements.  If you still have this issue, let's re-open the issue 😄
