### ISSUE TITLE
Extension tab throws blank page in MAC

### ISSUE THREAD

**Issue by Prasanth-V-K** [brave/browser-laptop#11602]
### Steps to Reproduce

  1. Open the Brave Browser
  2. Click on the "Extensions" tab
  

**Actual result:**
Blank page is displayed

**Expected result:**
The extension page should be displayed.

**Reproduces how often:** [100%]

### Brave Version
**about:brave info:** 0.19.57

<img width="1274" alt="screen shot 2017-10-19 at 7 05 21 am" src="https://user-images.githubusercontent.com/19169333/31752460-b4b3a498-b4a8-11e7-9853-6307ef0a80b1.png">

**Reproducible on current live release:** Yes

**Comment by bsclifton** [comment]
@Prasanth-V-K does this still happen for you? If so, would you mind opening up the developer tools? On Windows, this will be F12.  From there, you can see the console tab and there may be errors in red

**Comment by Prasanth-V-K** [comment]
@bsclifton I could not replicate this issue now.
