### ISSUE TITLE
close tab page closes the wrong tabs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11608]
### Description
When you have pinned tabs and more than one tab page, if you select 'Close tab page' the wrong tabs can be closed.

### Steps to Reproduce

  1. Have a couple of pinned tabs (I had three but have seen this issue with 1 or 2 tabs pinned)
  2. Set number of tabs per page to 6.
  3. Open at least 8 non-pinned tabs so you have two tab pages (use a mix of different sites so you can distinguish between the tabs).
  4. On the second tab page, make second normal tab the active tab.
  5. Right click on the first tab page box and select 'Close tab page'.

**Actual result:**
In the below screenshot, after selecting 'Close tab page', the tabs from the second tab page are not displayed:
![tabpages](https://user-images.githubusercontent.com/28145373/31792353-b5829fc8-b4e9-11e7-9492-fee58f0a568d.gif)

**Expected result:**
The two tabs from the second tab page (a recipe for avocado salad and twitch) should have been displayed.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.58
rev | fe749c5
Muon | 4.5.4

**Reproducible on current live release:**
yes, repro'd on 0.19.53, 0.19.48

### Additional Information
Seems to be introduced with 0.19.x, as the below gif is from 0.18.36 (note, you do have to click on the back arrow on the tab bar in this version, but at least the correct tabs were maintained):
![tabpages01836](https://user-images.githubusercontent.com/28145373/31792447-169a6822-b4ea-11e7-979d-57e616357807.gif)

Reproduced by @srirambv on Windows.

**Comment by NejcZdovc** [comment]
@cezaraugusto can you please check this one out, probably regressed with this PR #11228
