### ISSUE TITLE
Shortcut keys do not work in the context menu

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1160]
Scenario
- open any webpage with links
- click right on a link
- the context menu opens
  Expected:
- a keypress opens the context menu item (this works in Chrome: pressing N opens a new window, pressing T opens a new tab)
  Actual:
- nothing happens

**Comment by luixxiul** [comment]
Shortcut keys in the context menu aren't implemented. Is there any plan, @bbondy?

**Comment by bbondy** [comment]
do any other browsers do this? I don't think is normal behaviour and might be frustrating if we do actions unexpectedly.

**Comment by tetrode** [comment]
Yes other browsers do it.

Open this (https://github.com/brave/browser-laptop/issues/1160) page, click right on browser-laptop at the top:

in Firefox

![image](https://cloud.githubusercontent.com/assets/5877361/15285255/52025520-1b56-11e6-9430-8592570a8f6c.png)

context menu shows with keys underlined.

in Chrome

context menu shows, no underlining but T (new tab), W (new window) work.

in Internet Explorer

context menu shows, no underlining but W (new tab), N (new window) work.

**Comment by cezaraugusto** [comment]
@bbondy what's your opinion on this? `enhancement` / `wontfix`?

**Comment by bbondy** [comment]
low prior but it seems valid.

**Comment by peakhope** [comment]
This is an absolutely essential feature for me. My normal workflow is to right-click on a link, and hit T to open it in a new tab. I probably use it 100 times per day, so without it, I'm not sure I could switch to brave. How do other people open links in new tabs without this?

**Comment by tetrode** [comment]
Hi

This might help

Ctrl + click: open in new tab
Ctrl + Shift + click: open in new tab and focus on this tab

Mark

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/please-add-key-shortcuts-to-right-click-menu/14758?u=eljuno

>I wish right-click + T  would open up a link in a new tab

**Comment by peakhope** [comment]
Right-click T only requires one hand, where ctrl-click requires 2. Aside from convenience and consistency with FF and Chrome, there seems to be an accessibility benefit?
