### ISSUE TITLE
Youtube ads shown after upgrade to chromium 62

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#11619]
### Description

After upgrading to 0.19.57 and 58 the are ads on youtube.
### Steps to Reproduce

  1. Go to this link https://www.youtube.com/watch?v=XZUBZTlhR80
  2. Refresh until you get an ad to show (Can be on first run or second)

**Actual result:**

Ads shown:
![image](https://user-images.githubusercontent.com/25466657/31850691-ef02a860-b656-11e7-8afb-d2000b552648.png)

**Expected result:**
No ads shown
**Reproduces how often:** [What percentage of the time does it reproduce?]
Not on every video but almost 100% on the video that I linked above.
### Brave Version
0.19.58
**about:brave info:**

 
Brave: 0.19.58 
rev: fe749c59b743160c55fdad906c13c798c7141562 
Muon: 4.5.4 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
**Reproducible on current live release:**

No I have tested this on my Mac on 0.19.53 and there are no ads and then I downgraded my PC to 0.19.53 and there were no ads. @srirambv  also reported the same thing.

### Additional Information

cc @lukemulks  cc @srirambv

**Comment by Jacalz** [comment]
Actually happens almost 100% on videos with ads on them.

**Comment by Jacalz** [comment]
I am going to assign this to the appropriate milestone but please remove milestone or change it if necessary.

**Comment by Jacalz** [comment]
Not able to reproduce on MacOS using 0.19.53
 
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Comment by Jacalz** [comment]
Not able to reproduce on windows using 0.19.53:
 
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Comment by DanielJenkyn** [comment]
Couldn't reproduce either in High sierra

``` 
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64
```

**Comment by pongraczi** [comment]
I have this with   
Brave: 0.19.61 
rev: c8e042cd4bd700e277b35d8b584e622ed89dcb51 
Muon: 4.5.6 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

![kijeloles_606](https://user-images.githubusercontent.com/5891983/31864487-4ab405f2-b75e-11e7-94c2-312d923d2eac.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/ads-starting-to-bleed-thru-on-you-tube/9506?u=eljuno

windows 7 (sp 1 )
brave 0.19.61
rev c8e042c

**Comment by bbondy** [comment]
this is probably duping to https://github.com/brave/browser-laptop/issues/11621

**Comment by Jacalz** [comment]
Yes, seems to be the same
Should we keep this to the milestone and close when aI have tested it? @bbondy

**Comment by pongraczi** [comment]
Even ads appear in the video stream from youtube, before the requested content. I found it only once today, in a linked video of a disqus (whatever) post. Completly forgot to save the link, maybe next time, sorry.
 
Brave: 0.19.62 
rev: fe3f350d2b5a014cde485b126788d3661e9f451a 
Muon: 4.5.7 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by bbondy** [comment]
master: 81b7b7f795304b0fb7391806e672055366e90707
0.21.x: d3e9270da4ab3f5ad16b613ebafa70d2b6c9d385
0.20.x: 83928ac9a528cdb3974cdc168849a62fb0255f35
0.19.x: 4eb31eae11bff6023ad0cc4e3bcec07bc6bfa914

**Comment by Jacalz** [comment]
I can confirm that this is fixed and works like it should 👍
