### ISSUE TITLE
It keeps pausing my youtube videos when im playing games.

### ISSUE THREAD

**Issue by LethalManBoob** [brave/browser-laptop#11612]
It get stuck in a perma buffer loop. Even if its fully loaded. 

Im in the latest beta.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/pause-youtube-videos-when-playing-games/10585

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
