### ISSUE TITLE
Add option to block third party scripts

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#11617]
### Description

A user from community https://community.brave.com/t/block-third-party-scripts-toggle-remember-custom-script-toggles/9352 is requesting that there should be "an option to “Block third-party scripts”, thus allowing only scripts that come from the same top-level domain."

**Actual result:**

No blocking of only third party scripts
**Expected result:**
Should be possible to block only third part scripts
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

### Additional Information

cc @diracdeltas

**Comment by flamsmark** [comment]
Moving to the new codebase: brave/brave-browser#538
