### ISSUE TITLE
Publishers lost if upgrading from 0.18 with wallet disabled

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11614]
## Test plan

https://github.com/brave/browser-laptop/pull/11626#issue-267553513

----

### Description

When you upgrade form 0.18.x wallet to 0.19.x wallet, where wallet is disabled when upgrading, you lose all your publishers from 0.18.
### Steps to Reproduce

  1. launch `0.18.36` and enable payments via `about:preferences#payments`
  2. visit several websites and ensure they're appearing under the ledger table
  3. disable payments via the "On/Off" switch under `about:preferences#payments`
  4. if you haven't received an "Update", check for updates and update Brave
  5. Once Brave has been updated, go back into `about:preferences#payments` and enable payments

**Actual result:**

Once you've updated, you'll notice that the transition animation wasn't executed, the websites have been removed from the ledger table and the USD rates aren't correctly being updated.

![transitionissues](https://user-images.githubusercontent.com/2602313/31837214-f394bfa0-b5a5-11e7-9e5f-d69a1cd437ef.gif)

**Expected result:**

Once the user has updated, a transition animation should have been shown. Once BTC have been converted and the correct USD rates pulled into the client, the transition animation should disappear. The ledger table shouldn't have been cleared either.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible when using the above STR.

### Brave Version

**about:brave info:**

Brave: 0.19.53 - Reproducible
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

> Brave: 0.18.36 - Reproducible
> rev: 7ab85e97318fef041433b0c3d73b457205fae805 
> Muon: 4.3.22 
> libchromiumcontent: 61.0.3163.79

**Comment by LaurenWags** [comment]
Reopening, seeing errors when executing Test Plan D from the linked test plan.
STR:
launch 0.18.36 and enable payments via about:preferences#payments
visit several websites and ensure they're appearing under the ledger table
disable payments via the "On/Off" switch under about:preferences#payments
close 0.18.36, open 0.19.66
go to preferences and try to toggle payments on/off multiple times (i was only able to toggle a few times before my toggle got 'stuck' in the off position).
Restarting allowed me to use the toggle again but then I started seeing 402 errors.
[PlanD-errors.txt](https://github.com/brave/browser-laptop/files/1415426/PlanD-errors.txt)

**Comment by LaurenWags** [comment]
reopened in error, should have reopened https://github.com/brave/browser-laptop/issues/11611

**Comment by LaurenWags** [comment]
upon further discussion with @srirambv this would need to be retested along with 11611, so reopened.

**Comment by NejcZdovc** [comment]
tried to reproduce this problem with @LaurenWags, but without any luck. Will close this one for now and if we find any more problems, please open new issue
