### ISSUE TITLE
send updates to `about` pages more efficiently

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11615]

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/pull/11223

**Comment by kjozwiak** [comment]
@bbondy, is the test case that's being listed under https://github.com/brave/browser-laptop/pull/11223#issue-261874383 PR sufficient enough? QA would go through all the `about:about` pages and ensure that they're correctly being updated when changes are made?

**Comment by bbondy** [comment]
@kjozwiak yep just make sure that data is retained in about pages, like when going to a different tab and then back, or closing and re-opening.
