### ISSUE TITLE
Clicking link in this tweet causing cannot read property guest of undefined

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1161]
https://twitter.com/rmflight/status/712729532248301568
CC @bridiver

**Comment by weems** [comment]
Chrome states the certificate is expired. Not sure if that is relevant.

**Comment by bbondy** [comment]
That link is no longer reproducing for me, but used to reproduce consistently.

**Comment by mozjag** [comment]
I get this when I cmd+click either of the Twitch.tv links on http://friendshipmoose.com/

**Comment by luixxiul** [comment]
On 0.9.6, the link to twitter is not reproducing me neither, while links to twitch.tv are.

**Comment by luixxiul** [comment]
On Ubuntu 14.04

STR
    1. open philosophyguides.org/decoding/
    2. click "about"
    3. Open console ``GET https://www.philosophyguides.org/about/undefined 404 ()``

**Comment by diracdeltas** [comment]
i get this error when i click on https://www.twitch.tv/vgbootcamp in 0.9.6

**Comment by bridiver** [comment]
This appears to be related to the twich.tv site hack to allow insecure content. Allowing insecure content triggers the creation of a new webview and the old guest instance id is reused. We can work around that issue, but the reloading of the webview will break window.opener if it is used.
