### ISSUE TITLE
Drag and drop tab to bookmarks opens the tab in a new window

### ISSUE THREAD

**Issue by agilob** [brave/browser-laptop#11618]
### Description
When I d&d a tab to bookmarks panel it opens the tab in new windows instead adding new element to the panel.

### Steps to Reproduce
  1. Drag opened tab
  2. Drop it on bookmark panel
  3. Done

**Actual result:**
https://gfycat.com/gifs/detail/FortunateHalfBubblefish

**Expected result:**
Add link from tab to bookmark panel

**Reproduces how often:**
always

### Brave Version 
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.7-1-ARCH 
OS Architecture: x64

**Comment by bsclifton** [comment]
Thanks for the report, @agilob 😄  I captured this in a larger task we have for improving drag and drop for the bookmarks toolbar area (https://github.com/brave/browser-laptop/issues/6245 if you wanted to track).  I'll close this issue as a dupe
