### ISSUE TITLE
reattaching tab freezes all tabs

### ISSUE THREAD

**Issue by joshkestenberg** [brave/browser-laptop#11613]
### Steps to Reproduce

  1. detatch tab
  2. reattach tab

**Actual result:**
All tabs are non-responsive

**Expected result:**
Don't crash the browser.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always.

### Brave Version

**about:brave info:**
0.18.23

**Comment by srirambv** [comment]
Could you try updating to the latest version and check.  Which OS you are experiencing this?

**Comment by joshkestenberg** [comment]
Ubuntu 16.04 LTS

Updated Brave to 0.19.53; issue is resolved! Thanks.
