### ISSUE TITLE
Upgrading to 0.19.61 from 0.19.50 wiped out settings and saved passwords

### ISSUE THREAD

**Issue by pongraczi** [brave/browser-laptop#11620]
It is easy to describe.  
Installing the latest 0.19.61 just "forgot" all my settings, saved passwords, browser history.  

I expected the new version will keep them.

**Comment by pongraczi** [comment]
Brave: 0.19.61 
rev: c8e042cd4bd700e277b35d8b584e622ed89dcb51 
Muon: 4.5.6 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

The problem seems more bigger than I thought. It wiped out everything: all bookmarks I collected also gone. Hundreds.

Anyway, I just checked the .config/brave directory and seems history is probably there (more contents than I visited after upgrading), but everything else seems wiped.  
I also found a file named session-store-1 which seems contains links from my before-upgrade session.

**Comment by pongraczi** [comment]
WAIT a minute.  
I did a test, because the situation seems like brave started with a new, empty profile.  
It seems, it just happened.  

- I closed the new brave instance and I waited a minute and checked there is no brave processes.
- I started brave just like before.
- I got back my session closed right before the upgrade.
- I checked saved passwords -> exist.
- Bookmarks - exist.

So, my theory: I just started the new brave too early and it started a new profile.

Steps I did during the upgrade:  
- I used 0.19.50 and I started the upgrade without closing brave browser.
- Upgrading happened using gdebi.
- After upgrading finished, I closed the brave and I started again with short time between closing-starting. I guess the key point was this -> new brave process detected an already running one or something like this.
- So, I got a brave with new/empty profile.

So, technically all previous settings etc. are not removed, but brave started with a new profile.  Should be [PEBCAK](https://www.urbandictionary.com/define.php?term=PEBCAK).

This issue should be closed.

**Comment by pongraczi** [comment]
@luixxiul I close this ticket as I think, it is not really a bug.

**Comment by luixxiul** [comment]
OK, if you find this actually is a bug, please re-open to investigate. thanks!
