### ISSUE TITLE
hiding/removing "update to preview release"

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11638]
I've started to notice that some of our user base might have the wrong impression of what exactly a "preview" build means. Because the "enable previews" option is easily accessible, I feel that a good percentage of our users are enabling it automatically with the expectation that the "preview" build will be somewhat equal to the release in terms of quality which isn't the case.

We've had several instances in the past few months where we've released a preview version that either:

* completely breaks and stops launching (this has happened a few times)
* crashes every few minutes making the product unstable and unusable

When this happens, we usually get a large influx of support requests/rants/complaints via various social media channels. We're most likely losing users every time a preview build completely breaks the entire Brave experience. These users shouldn't have been on the preview build from the start.

We should still allow users to enable "preview" builds, but we need to ensure that only advanced users that are aware of the risks are using previews, and not regular users who might think that the "preview" build is basically an equivalent to the release build. We could either:

* hide the "preview" toggle deeper into the settings (makes it harder to find/enable)
* remove it entirely from Brave and require a environment variables to download previews

CC'ing @bbond @aekeus, @bsclifton, @LaurenWags, @srirambv

**Comment by srirambv** [comment]
>hide the "preview" toggle deeper into the settings (makes it harder to find/enable)

With limited amount of settings this would seem hard to do.

>remove it entirely from Brave and require a environment variables to download previews

Many users might not be able to do it as its quite different on each platform. I'd suggest remove the switch and have a link to the most recent preview build for a release on github. And add a disclaimer that preview builds are still in development and unstable and **will have known bugs**. Upgrading might _may_ cause issue while using the browser.

**Comment by bbondy** [comment]
I think an environment variable will be a better way. We want a lot less users using preview builds, mainly just QA.  We'll still have instructions for very advanced users that want to use it. But we're going to channels instead for Beta, Developer, and Nightly so it's kind of confusing that preview builds aren't related to those and only to hotfixes.  So removing the checkbox and using an env variable I think is best.

**Comment by srirambv** [comment]
Verified setting env variable 0.19.66 found update to 0.19.67

**Comment by LaurenWags** [comment]
Worked on MacOS also

**Comment by bsclifton** [comment]
Great call on removing this 😄  I've felt beyond guilty about the bug the Windows users have experienced (where it fetches the preview instead of the last release)

**Comment by hugobuddel** [comment]
Good to have this. Now I do consider myself to be someone who wants to be on the preview releases, but I also get confused very much with Brave's versioning. Things should be clarified much more.

E.g. there is

- Release, Beta, Developer, Nightly: release channels
- 0.18, 0.19, 0.20, 0.21, 0.22: brave versions
- Preview: as referenced in this issue
- Master: as the branch

And it is often very much unclear how these relate to each other. A specific Brave deployment can have almost an arbitrary combination of those identifiers although not all combinations are possible at any specific time.

An example of this inconsistency. about:brave says: "Brave: 0.19.70, Update Channel: Release". But the link to the release notes says "Dev Channel Beta v0.19.70dev". So what is it? Release, Beta or Dev? It can't be all three at the same time!
