### ISSUE TITLE
After closing a tab when multiple tab pages are present, tab bar doesn't always leave preview mode

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11632]
## Test plan

https://github.com/brave/browser-laptop/pull/11958#issue-273911077

----

### Description

Tab bar sometimes looks like this after closing a tab:
<img width="539" alt="screen shot 2017-10-23 at 8 49 37 am" src="https://user-images.githubusercontent.com/831718/31889882-4a98e134-b7cf-11e7-851c-1d1b4db07069.png">

### Steps to Reproduce

  1. Create 3 tab pages
  2. Close a tab with your mouse

**Actual result:**
Sometimes preview mode stays

**Expected result:**
Preview mode should be gone and new active tab should show selected without the lighter color overlay on the tab bar.

**Reproduces how often:** [What percentage of the time does it reproduce?]
30%

### Brave Version

0.19.62

**about:brave info:**
 
Brave: 0.19.62 
rev: fe3f350d2b5a014cde485b126788d3661e9f451a 
Muon: 4.5.7 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes

**Comment by NumDeP** [comment]
HI @bbondy I was wondering could you merge this tab issue (#11526) to Hotfix 3 as I think it's related and would be brilliant if you could offer a fix in the same release. I also made an inference to this issue there. Thanks.

**Comment by bbondy** [comment]
I moved it to hotfix 3 @NumDeP

**Comment by LaurenWags** [comment]
Still able to reproduce on MacOS using STR in description:
![screen shot 2017-11-08 at 5 20 57 pm](https://user-images.githubusercontent.com/28145373/32577858-41c863c2-c4a9-11e7-8139-29024b3a3460.png)

**Comment by srirambv** [comment]
Reproed on Windows too

**Comment by bsclifton** [comment]
Tentatively moving to the next release- @cezaraugusto, can you check this out?

If there isn't a quick fix (or it'll require more investigation work), let's un-assign the milestone.  Thanks 😄

**Comment by cezaraugusto** [comment]
failing to reproduce locally but I'll take a new look after Sri/Lauren reports.

yes next milestone should be fine. thanks

**Comment by bbondy** [comment]
Original PR backed out here:

master: 06e535cdf16325a2980e839d3e6968b54ca518a7
0.21.x: a604752c2f334b67e8c0efc7fac98c70544013ca
0.20.x: 1c8d5e558a2067847bf2ad5dadebd9696e4228a0
0.19.x: 340e4e515871a417c1209711f632feb777a537d1

**Comment by srirambv** [comment]
Seeing a quick switch between first and third tab page when closing a tab. 
![11632](https://user-images.githubusercontent.com/17010094/32627194-89906912-c589-11e7-879d-ce5f40190c13.gif)

**Comment by srirambv** [comment]
on 0.19.87 , closing a tab sets focus on the third tab page but the active tab is still in first tab page

**Comment by cezaraugusto** [comment]
@srirambv I opened a new issue per your comment above #11902.

**Comment by srirambv** [comment]
Reopening the issue based on https://github.com/brave/browser-laptop/pull/11958#issuecomment-344520838
![11632](https://user-images.githubusercontent.com/17010094/32826244-8673e060-c9df-11e7-8054-2b05dfaf56c0.gif)

**Comment by bsclifton** [comment]
Reverting...

**Comment by cezaraugusto** [comment]
did revert my changes fixed the last issue @srirambv reported?  this seems related to wrong index not really previews

**Comment by cezaraugusto** [comment]
un-reverting the change and moving issue back to hotfix 5 as the issue was fixed, and @srirambv reported that https://github.com/brave/browser-laptop/issues/11632#issuecomment-344521477 is unrelated to this change as still exists after the revert.

**Comment by bbondy** [comment]
should this be closed?

**Comment by cezaraugusto** [comment]
yes I was waiting to post the revert sha

**Comment by cezaraugusto** [comment]
Changes un-reverted

master 2819e39cf
0.21.x 43d36d85ec93faecf25cbea4d2d9ee68c1aa25a5
0.20.x 348159353
0.19.x 2e71dfdb1
