### ISSUE TITLE
Keyboard shortcut for reverse tab cycling doesn't work correctly

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#11636]
### Steps to Reproduce

  1. Open multiple tabs
  2. hit Ctrl-Shift-tab

**Actual result:**

**Expected result:**
Brave shifts active tab one tab to the left

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.19.62
rev | fe3f350
Muon | 4.5.7
libchromiumcontent | 62.0.3202.62
V8 | 6.2.414.32
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS 10.13.1 Beta (17B35a)
OS Release | 17.2.0
OS Architecture | x64

**Reproducible on current live release:**

Yes

**Comment by stshank** [comment]
I should have mentioned that this has been a problem for this and, I think, the prior two dev versions of Brave. It's not not a new problem with the 2017-10-23 release.

**Comment by petemill** [comment]
Thanks @stshank, reopening the original at https://github.com/brave/browser-laptop/issues/11331
