### ISSUE TITLE
Alt-D not focusing URL navigation

### ISSUE THREAD

**Issue by startupbrewery** [brave/browser-laptop#11634]
### Steps to Reproduce

  1. press alt-d
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by srirambv** [comment]
Which version of Brave are you using? I can see it highlights URL on Windows.

**Comment by startupbrewery** [comment]
thanks!

Name
Version
Brave 0.19.53
rev e09025b
<https://github.com/brave/browser-laptop/commit/e09025bf61debc46c03459def2501b3367f182d7>
Muon 4.4.29
libchromiumcontent 61.0.3163.100
V8 6.1.534.41
Node.js 7.9.0
Update Channel Release
OS Platform Linux
OS Release 4.4.0-97-generic
OS Architecture x64
ᐧ

Gary A Hoffman

Director, Sales Enablement

O: +1-408-256-1394 <gary@tourmalinelabs.com>

tourmalinelabs.com

**Comment by grand-lotus-iroh** [comment]
(L) ALT + D = broken
(R) ALT + D = works

https://streamable.com/r3hqq

I do not wish to use CTRL+L or F6.
