### ISSUE TITLE
SHA1 signed certificates accepted with no warning

### ISSUE THREAD

**Issue by nicdoye** [brave/browser-laptop#1164]
Web sites using the SHA-1 Signature hash algorithm are displayed in the browser without even a warning. (Brave 0.8.2). I believe Brave should block connections to such sites as Firefox already does, and Chrome, IE and Edge by Jan 01 2017.
- Chrome 49 shows a red cross on the padlock, and the "https" part of the URL is also red with red line through it. [They will completely stop supporting SHA-1 by Jan 01 2017](https://security.googleblog.com/2015/12/an-update-on-sha-1-certificates-in.html).
- Firefox has rejected such sites [since version 43 (Jan 01 2016)](https://blog.mozilla.org/security/2016/01/06/man-in-the-middle-interfering-with-increased-security/) bringing up a page saying "Your connection is not secure" and does not connect to the site (unless you add an exception). (Tested with 45.0.1)
- Microsoft Edge will ["deprecate" them later this year and block them by Jan 01 2017](https://blogs.windows.com/msedgedev/2015/11/04/sha-1-deprecation-update/).  (Currently, version 25.10586.0.0 issues no warning and displays the page).
- Microsoft IE will presumably be aligned with the Edge timescales, if it is a pan-Microsoft decision (Currently, version 11.103.10586.0 issues no warning and displays the page).
- Opera - I can't find anything about their policy and don't have it installed.
- Vivaldi - I can't find anything about their policy and don't have it installed.

**Comment by diracdeltas** [comment]
I think we should display sha1 certs as non-secure. Right now there is no way to get cert info unless there's a certificate error but that is a todo for 1.0.

**Comment by nicdoye** [comment]
Would you need an extra prop to check in  in `SiteInfo.render()`, other than `isSecure` and `isMixedContent` to set the icon to (some colour lock/unlock)? 

Or would you set a certificate error (which I think happens via an electron `ipc.send()` call from the `loadStart()` event listener in `Frame.addEventListners`) and deal with it like that?

**Comment by diracdeltas** [comment]
We would modify our fork of electron to send the cert info via IPC when the tls connection is established.

**Comment by bbondy** [comment]
Adding @bridiver for this.

**Comment by bridiver** [comment]
cert information could be made available in the `navigation-entry-commited` event

**Comment by diracdeltas** [comment]
it would be useful if electron could send the parsed x509 cert info instead of just the raw cert, so the browser doesn't have to re-parse it in JS

**Comment by bridiver** [comment]
it is available in SecurityStyleChanged and we could add an event for it

**Comment by bridiver** [comment]
it is available from AtomSecurityStateModelClient and we could fire an event when it changes with SecurityStyleChanged

**Comment by luixxiul** [comment]
Setting 1.0 milestone based on the comment by @diracdeltas above.

**Comment by diracdeltas** [comment]
As of 0.12.9, Brave will show the insecure UX for sha1 certs that expire after 2017. Hooray!
![screen shot 2016-11-14 at 2 00 51 pm](https://cloud.githubusercontent.com/assets/549654/20284654/e1e75ca2-aa72-11e6-971f-0f7530d3bddb.png)
