### ISSUE TITLE
unable to highlight sync words for copying

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11641]
## Test plan

https://github.com/brave/browser-laptop/pull/11670#issue-268478919

----

### Description
On the 'Sync a new device' popup we are no longer able to highlight the sync words so we can copy/paste them. This last worked with 0.19.54 and stopped working in 0.19.57.

### Steps to Reproduce

  1. Enable sync.
  2. Open 'Sync a new device' popup.
  3. Select 'show secret code words'.

**Actual result:**
Unable to highlight the sync code words:
![syncwords](https://user-images.githubusercontent.com/28145373/31909474-402c7bc8-b808-11e7-837d-db2d0927475d.gif)

**Expected result:**
Should be able to highlight the sync code words as before.
![syncwords01954](https://user-images.githubusercontent.com/28145373/31909478-48fc62c2-b808-11e7-815b-46a752a2e28f.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.62
rev | fe3f350
Muon | 4.5.7

**Reproducible on current live release:**
no, this is not broken on 0.19.53

### Additional Information
Possibly introduced with cr62, which was also introduced in 0.19.57.
cc @srirambv

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/blame/1bb8ff174e8781db05d48c0c86de41e19d04e048/app/renderer/components/preferences/syncTab.js#L608

`user-select: initial` seems to have changed how it behaves since cr62 (since the code has been there for 6 month). there might be a similar case inside the code.

changing it to `user-select: text` should work.

**Comment by luixxiul** [comment]
Since the fix is ready (PR has been submitted), it is ok to escalate this to hotfix 2.

**Comment by bsclifton** [comment]
This will be an important one to test on Windows (which is a little more picky about these attributes)

**Comment by kjozwiak** [comment]
This issue also affected the backup keys under `about:preferences#payments`, checked on all the platforms to ensure that it has been resolved with this fix as well:

* Ubuntu 17.04 x64 - Copied both sync & wallet keys using the cursor without any issues
* macOS x64 - Copied wallet keys using the cursor without any issues (sync already checked)
* Win 10 x64 - Copied wallet keys using the cursor without any issues (sync already checked)
