### ISSUE TITLE
Adress Bar Lagging

### ISSUE THREAD

**Issue by stormy706** [brave/browser-laptop#11640]
Extreme Lag

When typing the first (1-3) letters it lags really hard and you might have to enter the letters again. After that it works much faster.

This is probably because it is trying to autocomplete and the autosearch is slow :(

It is faster with the autocomplete turned off, but I need autocomplete!

**Actual result:** Lag

**Expected result:** No Lag

**Reproduces how often:** 100%

### Brave Version

**about:brave info:**

Brave | 0.19.62
-- | --
rev | fe3f350
Muon | 4.5.7
libchromiumcontent | 62.0.3202.62
V8 | 6.2.414.32
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 6.1.7601
OS Architecture | x64

**Comment by stormy706** [comment]
?

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/11066

**Comment by bsclifton** [comment]
Thanks for the report, @stormy706 😄   As @luixxiul mentioned, we are tracking this issue with https://github.com/brave/browser-laptop/issues/11066 (which you can subscribe to) and this issue was closed as a duplicate

**Comment by stormy706** [comment]
Okay I see, thanks. 
However this is an important issue.
The browser works, but it creates an awful UX, making users switch back to their old browser!
