### ISSUE TITLE
Alt+F4 doesn't close the browser window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11652]
### Description
Alt+F4 doesn't close the browser window

### Steps to Reproduce

  1. Install 0.19.62
  2. Try closing browser window using Alt+F4
  3. Browser window doesn't close, Ctrl+Q works

**Actual result:**

Alt+F4 doesn't close the browser window
**Expected result:**
Should close the browser window
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.62
-- | --
rev | 9c33f43
Muon | 4.5.7

**Reproducible on current live release:**

No, Works fine 0.19.53

**Comment by bbondy** [comment]
master: a75d7391ddc0ed6266275eb7f7849d5ea8877f26
0.21.x: d6a02714b29c82d59b0353b232a99375354ccedc
0.20.x: ef0887017f29855cb0b92d120512e555efdc69c9
0.19.x: bcec3be7511d0ebbc95426cd7656799c643661ee
