### ISSUE TITLE
Google 2FA Try Again

### ISSUE THREAD

**Issue by pantocrator27** [brave/browser-laptop#11659]
### Description
When I clear my cookies & cache and then I authenticate to gmail.com, Google prompts me for 2FA.  However it immediate switches to their "Try Again" model window without ever being able to supply my 2FA.  It prompts me to "Try Again" immediately. 

### Steps to Reproduce

This assumes that you have Google 2FA enabled connected to a start phone.  This is not the 2FA where Google sends an SMS message.

  1.  Open Brave
  2.  Clear Cookies & Cache
  3.  Close Brave
  4.  Open Brave
  5.  Navigate to gmail.com
  6.  Sign In
  7.  Wait for Google to prompt for 2FA
  

**Actual result:**
https://imagebin.ca/v/3ewnldoaEaur

**Expected result:**
I should be able to supply my 2FA from the Google App on my phone and the Google in the browser should log me in.

**Reproduces how often:**
100% of the time

### Brave Version

Name | Version
-- | --
Brave | 0.19.53
rev | e09025b
Muon | 4.4.29
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.10.0-37-generic
OS Architecture | x64

**Reproducible on current live release:**
I do not know ....

### Additional Information
None

**Comment by luixxiul** [comment]
thanks for the report. it's been reported here: https://github.com/brave/browser-laptop/issues/7866

closing in favor of that.
