### ISSUE TITLE
Saving a password throws an error

### ISSUE THREAD

**Issue by neurobashing** [brave/browser-laptop#1165]
Attempting to save a password shows the following error:

Uncaught Exception:
Error: Invalid key length
    at Error (native)
    at new Cipheriv (crypto.js:187:16)
    at Object.Cipheriv (crypto.js:185:12)
    at Object.module.exports.encryptAuthenticateInternal (/Applications/Brave.app/Contents/Resources/app.asar/js/lib/cryptoUtil.js:81:23)
    at Object.module.exports.encryptAuthenticate (/Applications/Brave.app/Contents/Resources/app.asar/js/lib/cryptoUtil.js:21:34)
    at Function.dialog.showMessageBox.buttonId (/Applications/Brave.app/Contents/Resources/app.asar/app/index.js:424:38)

No password is saved.

**Comment by diracdeltas** [comment]
What OS? Is this on the latest release or building from github?

**Comment by neurobashing** [comment]
oops, sorry: Mac OS X 10.11.4
Latest Brave release (not built by me):
Brave: 0.8.2
Electron: 0.37.2
libchromiumcontent: 49.0.2623.87
V8: 4.9.385.28
Node.js: 5.9.0
Update channel: dev

**Comment by diracdeltas** [comment]
Does password saving ever work successfully, or does it always show this error?

Could you open OSX Keychain Access and search for an item named "Brave"? If it exists, could you please double-click on it, show password, and check how long it is?

**Comment by neurobashing** [comment]
It always shows this error. I've tried it on about half a dozen sites (HN, Reddit, AWS, and a few others).

It's about 20 or 30 characters of what I guess is unicode? (len() in python2 and python3 report different results)

**Comment by diracdeltas** [comment]
It should be a binary-encoded 32-byte string. I'm guessing the problem is that OS X keychain is mangling some characters. We should probably switch to hex. 

In the meantime, can you send me the password (yan@brave.com) for debugging? If you then delete the item from the keychain, Brave will make a new master key and maybe that one will work.

**Comment by diracdeltas** [comment]
(The password is just used for on-disk encryption of passwords; they aren't synced or anything so I can't read your passwords even if I have it)

**Comment by diracdeltas** [comment]
Ugh, looks like OS X keychain expects utf8 and we are saving passwords in latin1. Unfortunately the workaround for now is to just keep regenerating Brave master passwords (by manually deleting them from the keychain) until you end up with one that works. I'll fix by 0.8.3.

**Comment by neurobashing** [comment]
deleting the keychain entry and reopening Brave fixes password saving. Thanks!

**Comment by michaelhwan** [comment]
@neurobashing @diracdeltas I'm running OS X 10.11.4 running Brave v 0.8.2 as well and have not encountered errors saving my passwords...

**Comment by michaelhwan** [comment]
@diracdeltas take a look at #1183 I suspect passwords can't exceed certain length or browser won't save password.

**Comment by michaelhwan** [comment]
@neurobashing how long is your password length?

**Comment by mjoyce4550** [comment]
I'm getting the same JS error in Win 7 Pro 64-bit.

**Comment by mjoyce4550** [comment]
Not clear why this has been closed. I’m still getting the same error when attempting to save any password, even very short, simple (8 digits) ones.

 

Do I need to start a new thread or just wait for an update that resolves this?

 

Thanks,

 

Michael Joyce

A T Marketing, LLC

4220 Proton Rd Ste 160

Dallas TX 75244

214-453-2515 Ofc

214-906-2717 Cell

**Comment by weems** [comment]
Not Yet Live in Prod vs. in Repo but not live yet. You *could* build it yourself for your platform, @mjoyce4550 :)
