### ISSUE TITLE
Crtl+Tab (Switch tab) after scrolling a long page zooms the next tab

### ISSUE THREAD

**Issue by ckarthik17** [brave/browser-laptop#11661]
### Description
Crtl+Tab (Switch tab) after scrolling a page zooms the next tab

### Steps to Reproduce
  1. Open 2 or 3 tabs with long pages having scroll bars
  2. Scroll the page using touch bar and switch tab using Crtl + Tab
  3. Next tab that is focused gets zoomed in or out, depending on the scroll direction

**Actual result:**
Next tab that is focused gets zoomed in or out, depending on the scroll direction

**Expected result:**
Next tab should not get zoomed

**Reproduces how often:** [What percentage of the time does it reproduce?]
80-90% of the time in Macbook Pro

### Brave Version

**about:brave info:**
Brave: 0.19.53 
rev: e09025bf61debc46c03459def2501b3367f182d7 
Muon: 4.4.29 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes

### Additional Information
NA

**Comment by eljuno** [comment]
Related to #3244?

**Comment by ckarthik17** [comment]
Yes similar, but the steps to recreate is slightly different

**Comment by luixxiul** [comment]
could I know how they are different?

**Comment by ckarthik17** [comment]
Order of the events : 
This issue :  Scroll a long page, then switch tab
Other issue : Switch tab and then scroll

Technically they may be same
