### ISSUE TITLE
Error: ENOENT: no such file or directory, access 'profile\ledger-newstate.json' while upgrading

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11669]
### Description
Error: ENOENT: no such file or directory, access 'profile\ledger-newstate.json' while upgrading

### Steps to Reproduce

  1. Install 0.18.36, enable payments
  2. Visit sites to add in ledger table and disable payments
  3. Upgrade to 0.19.66
  4. Launch from console
  5. Shows error 

**Actual result:**

```
Error: ENOENT: no such file or directory, access 'C:\Users\Sriram BV\AppData\Roaming\brave\ledger-newstate.json'
```
**Expected result:**
Should not show error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.19.66
-- | --
rev | 148f5b0
Muon | 4.5.9

**Reproducible on current live release:**

### Additional Information

Confirmed by @LaurenWags on macOS
Confirmed by @kjozwiak  on Linux

**Comment by svillar** [comment]
I hit that in Windows too
