### ISSUE TITLE
Unable to login to jira cloud (auth via https://id.atlassian.com)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11662]
### Description
 Reported via community 

### Steps to Reproduce

  1. Use google authentication to login to jira cloud
  2.
  3.

**Actual result:**

https://community.brave.com/t/unable-to-login-to-jira-cloud-auth-via-https-id-atlassian-com/9607

**Expected result:**
Should login
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

Enabling all cookies doesn't allow login or disabling shields
https://community.brave.com/t/unable-to-login-to-jira-cloud-auth-via-https-id-atlassian-com/9607/3

**Comment by bsclifton** [comment]
I believe this works great if you disable 3rd party cookies for that domain

**Comment by mazzma12** [comment]
I had the same problem and I had to disable 3rd party cookie by clicking on the menu button (the lion on the top right). I think it only affects the current website

**Comment by bsclifton** [comment]
@mazzma12 I don't recall seeing that issue... but even in Chrome, I believe it was hard to get the interface where the sidebar is showing.  Can you verify in another browser please?  If it's still an issue, creating an issue with details would be great 😄

**Comment by mazzma12** [comment]
@bsclifton I have it working on Chrome and Firefox, but Brave is struggling... I have an error popping at the left bottom : 
<img width="402" alt="screen shot 2017-12-08 at 11 50 07" src="https://user-images.githubusercontent.com/23187108/33778252-37cb50c6-dc48-11e7-977f-e05d7120b4e9.png">

It totally prevent

**Comment by samelawrence** [comment]
I'm not able to log into Atlassian JIRA Cloud with Brave Browser, even after completely disabling all shields.
![screen shot 2018-01-17 at 11 27 37 am](https://user-images.githubusercontent.com/170246/35053914-72caf852-fb79-11e7-9030-22a6e6cd6a16.png)

**Comment by sarahthomson** [comment]
I am having the same issue as @samelawrence. Disabled shields and still cannot login. Was able to log in fine until a few days ago when I believe I updated to latest release (0.20.30).

**Comment by traderd65** [comment]
Same issue as @samelawrence on Window 10 x64 Brave 0.21.24

**Comment by darmstrong11** [comment]
Not sure if this helps but I was running into the same issue, I decided to leave my Shield menu up while the browser was "trying again" and I noticed that a redirect was happening on the login attempt and I was able to quickly down my shield for that page as well (id.atlassian.com or something like that) and then it let me through. Might be worth checking out if you are seeing something similar.

**Comment by traderd65** [comment]
Confirmed @panchromatic242 solution works.

**Comment by panchromatic242** [comment]
Meaning you no longer have to manually exempt both domains?

**Comment by mazzma12** [comment]
No, meaning it worked after allowing cookies on both domains

**Comment by panchromatic242** [comment]
Oh good deal!  Not sure what was confusing me about the original comment. :)

**Comment by audip** [comment]
I was facing this problem: https://user-images.githubusercontent.com/170246/35053914-72caf852-fb79-11e7-9030-22a6e6cd6a16.png

Had to disable shields on id.atlassian.com to get Jira to work for me.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/third-party-cookies-issue/32726. User says with shields down as well it doesn't work.

**Comment by srirambv** [comment]
User Win Han confirmed from https://community.brave.com/t/third-party-cookies-issue/32726/6?u=sriram  that the issue is resolved on brave-core with allowing third party cookies and no need to disable shields to make it work. 

@bsclifton ok to close this issue in favour of that confirmation?

**Comment by bsclifton** [comment]
@srirambv yup- sounds good 😄 👍
