### ISSUE TITLE
Time is not displayed correctly 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11675]
### Description

When you visit a site for more then 1min and 30s you actual get 2m 30s in ledger table

### Steps to Reproduce

  1. Enable payments
  2. Visit a site for 1min 40s
  3. Go to payments

**Actual result:**
You will see site with 2min 40s

**Expected result:**
You should see 1min 40s

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by kjozwiak** [comment]
Reproduced the issue using `v0.19.66` rev: 148f5b066d5d0d786bafaf80f396e753d42e0412 with several different websites. Using the above STR, I used the same websites and ensured that it was working correctly under `v0.19.67` rev: b3a897eef1f1d8d6594e2d8e862bf7a874e86e73.
