### ISSUE TITLE
Error: ENOENT: no such file or directory, access '/Users/kjozwiak/Library/Application Support/brave/ledger-synopsis.json' 

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11674]
### Description

When launching Brave for the first time with a brand new profile, you'll receive the following error message in the terminal/console:

`Error: ENOENT: no such file or directory, access '/Users/kjozwiak/Library/Application Support/brave/ledger-synopsis.json'`

### Steps to Reproduce

  1. install v0.19.66 rev 148f5b0
  2. ensure that you remove any existing profiles in ~/Library/Application\ Support/brave
  2. launch Brave via the terminal/console (/Applications/Brave.app/Contents/MacOS/Brave)

**Actual result:**

You'll get the following error in the terminal/console:

`Error: ENOENT: no such file or directory, access '/Users/kjozwiak/Library/Application Support/brave/ledger-synopsis.json'`

**Expected result:**

You shouldn't be getting the above error message in the terminal/console.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.66 
> rev: 148f5b066d5d0d786bafaf80f396e753d42e0412 
> Muon: 4.5.9 
> libchromiumcontent: 62.0.3202.62 

**Reproducible on current live release:**

Not reproducible in the current live build, seems like the issue was introduced in the following build:

> Brave: 0.19.65 
> rev: ccac8cc9d1d8867d6c2effe23975be2a573ac1ce 
> Muon: 4.5.9 
> libchromiumcontent: 62.0.3202.62 

### Additional Information

* macOS 10.12.6 x64 - Reproduced
* Ubuntu 17.04 x64 - Reproduced
* Win 10 Pro x64 - Reproduced

**Comment by NejcZdovc** [comment]
Yeah we can remove console log for it, but there is nothing wrong.
