### ISSUE TITLE
Moving bookmark into folder removes title and address and cannot delete it

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11672]
### Description
Moving bookmark into folder removes title and address and cannot delete it

### Steps to Reproduce
  1. Clean install 0.19.66
  2. Add a bookmark, click on edit bookmark,click on remove, should remove the bookmark
  3. Create a bookmark folder, add a bookmark, move it into folder
  4. Click on bookmark icon again, address and title is missing, clicking on remove doesn't delete the bookmark

**Actual result:**
![bookmark](https://user-images.githubusercontent.com/17010094/32016114-f4ed2f40-b9ba-11e7-9052-c8054c6fb7a1.gif)

**Expected result:**
Should be deleted even if its under folder

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.19.66
-- | --
rev | 148f5b0
Muon | 4.5.9

**Reproducible on current live release:**
Yes, broken in all 0.19.x release, works fine on 0.18.36

**Comment by NejcZdovc** [comment]
@srirambv can you please check if this is reproducible on 0.21.x?

**Comment by srirambv** [comment]
@NejcZdovc it works fine on 0.21.x (729c840)

**Comment by cezaraugusto** [comment]
I'm on 0.20.x sha b86fafe5916b9cb0f35454cc776cc769d919d4e2 and couldn't reproduce. @srirambv mind checking again if works there?

**Comment by cezaraugusto** [comment]
also confirmed the above in 0.21.x unable to reproduce sha 27f560b63ccbe67496f9ad3094abe9ab7d160768

**Comment by bbondy** [comment]
re-open if not fixed, thanks.

**Comment by srirambv** [comment]
@cezaraugusto @bbondy Able to repro this on 0.20.x sha 087853d. 
![11672](https://user-images.githubusercontent.com/17010094/32095205-52348ef6-bafa-11e7-93b2-551e90f0ab2c.gif)

**Comment by cezaraugusto** [comment]
still can't repro. sha ea8929b2aa83d951e14c319a57cd9fdc728d3314 which is one before latest in 0.20.x

<img width="662" alt="screen shot 2017-10-27 at 2 41 35 pm" src="https://user-images.githubusercontent.com/4672033/32115418-88f6ef1c-bb25-11e7-83ff-39b8aa8965ef.png">


![1 oct-27-2017 14-47-49](https://user-images.githubusercontent.com/4672033/32115602-2f6eb60e-bb26-11e7-82a2-1485886fea5a.gif)

**Comment by bsclifton** [comment]
@srirambv 0.20.0 was recently overwritten with 0.21.x... looking at your commit hash, that is the old one.  You'll need to do a `git fetch origin` and pull in latest.  You'll likely get a conflict, so you can run:
```
git checkout 0.20.x
git fetch origin
git reset --hard origin/0.20.x
```

**Comment by srirambv** [comment]
Verified can't repro this on a42cac1d0 which is latest on 0.20.x. Did find another issue with bookmark toolbar right click context menu  on 0.20.x will log a separate issue for it
