### ISSUE TITLE
VPNs?

### ISSUE THREAD

**Issue by briannyeko** [brave/browser-laptop#11686]
Is brave compatable with VPNs(ProtonVPN,NordVPN, Tunnelbear)?

**Comment by Liunkae** [comment]
I have used Brave with ProtonVPN using Tunnelbear. It works fine on macOS.

**Comment by purema4** [comment]
Vpn works on both network and transportion tcp/ip layers while Brave works on the application layer. So yes, you can always confirm if your vpn is  turned on  by checking where's your IP on google.

**Comment by luixxiul** [comment]
Closed as answered
