### ISSUE TITLE
Need to sign in to Lastpass and Google each time I log in and open the browser on Linux

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#11692]
Yes.

### Description
Open Brave with tabs set to restore from where I left off after logging in. Accounts are not automatically signed in, requiring sign in again, e.g. Lastpass, Google, Github is signed in.

### Steps to Reproduce
Will post once I confirm steps for reproducibility.

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

 
Brave: 0.19.24 
rev: 3b3fba2074395acb60954629a429b2d03d777f4a 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.13.0-16-generic 
OS Architecture: x64
**Reproducible on current live release:**
Yes, current beta.

**Comment by luixxiul** [comment]
> Will post once I confirm steps for reproducibility.

thanks in advance!

**Comment by jamesray1** [comment]
Closing until I can reproduce this.
