### ISSUE TITLE
Window reopens in the centre of screen when browser is docked to left/right

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11697]
### Description
Window reopens in the centre of screen when browser is docked to left/right

### Steps to Reproduce

  1.  Install 0.19.67
  2. Use Windows logo key  + Left arrow to dock window to the left of screen
  3. Close and reopen, window opens in the centre of the screen

**Actual result:**
Window reopens in the centre of screen when browser is docked to left/right

**Expected result:**
Should retain last position of window

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.19.67
-- | --
rev | b3a897e
Muon | 4.5.9

**Reproducible on current live release:**
Yes

### Additional Information
Settings are default, not to be confused to #3754

**Comment by NejcZdovc** [comment]
@srirambv  can you check it out on the latest master, I am wondering if #10458 maybe fixed it

**Comment by srirambv** [comment]
@NejcZdovc works fine on master (e02bafd)

**Comment by NejcZdovc** [comment]
will assign it to 0.20, because #10458 is on 0.20 and close it.
