### ISSUE TITLE
Uncaught Exception: TypeError: ledgerClient is not a function while transition from .18.x to .19.x

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11703]
### Description
Uncaught Exception: TypeError: ledgerClient is not a function while transition from .18.x to .19.x

### Steps to Reproduce

  1. Install 0.18.x, enable payments
  2. Upgrade to 0.19.67, wait for transition to wallet start
  3. Close the browser window after the update and relaunch from console
  4. Console logs error, but transition completes successfully, wallet doesn't get into bad state

**Actual result:**
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: ledgerClient is not a function
    at fs.readFile (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.67\resources\app.asar\app\browser\api\ledger.js:2358:21)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Expected result:**
Should not log error, transition should happen

**Reproduces how often:** [What percentage of the time does it reproduce?]
Initially noted by @kjozwiak and was able to reproduce consistently  , verified on Windows as well for the same behaviour 

### Brave Version

**about:brave info:**

Brave | 0.1836
-- | --
rev | 7ab85e9
Muon | 4.3.2

Brave | 0.19.67
-- | --
rev | b3a897e
Muon | 4.5.9

**Reproducible on current live release:**

### Additional Information
Not reproduce on macOS by @LaurenWags

**Comment by LaurenWags** [comment]
Was able to reproduce on MacOS this morning.
