### ISSUE TITLE
1Password can't verify the identity of your web browser

### ISSUE THREAD

**Issue by blacktop** [brave/browser-laptop#11714]
### Description

1Password can't verify the identity of your web browser

### Steps to Reproduce

  1. download latest
  2. enable 1pass
  3. open browser

**Expected result:**

It used to work

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Brave Version

**about:brave info:**
 
Brave: 0.19.70 
rev: d4b94c6215bb130250fe5245787a5884dc9b51fe 
Muon: 4.5.9 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Reproducible on current live release:**
not sure

### Additional Information

comes with  version `4.6.11.91`, however, the latest is: **4.6.12.90**

**Comment by blacktop** [comment]
So I think this was related to me installing from `brew cask` OR because I had it in my users `Applications` folder and NOT the systems `Applications` folder?

**Comment by blacktop** [comment]
I installed fresh from you website and put in the systems `/Applications` folder and it works again.

**Comment by bsclifton** [comment]
@blacktop awesome, thanks for the update 😄  There is a process you can use on macOS to check if your build is signed (if it's not signed, that would explain why 1Password didn't work):
`spctl --assess --verbose /Applications/Brave.app/`

I'll close this issue as your problem has been resolved.  Thanks again for the update- please re-open if it happens again
