### ISSUE TITLE
sometimes wallet recovery doesn't occur

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11718]
### Description
Sometimes wallet recovery fails. Nothing is going on in the UI but when I run LEDGER_VERBOSE=true I see a 400 error. However, sometimes if I wait long enough I do get my wallet, but this is confusing to the user.

### Steps to Reproduce

  1. I used a profile that I had trouble with previously (422 and 503 errors).
  2. Opened Brave, waited for transition to finish (it hadn't finished prior to build 0.19.70)
  3. Tried to recover my wallet, both by entering keys manually one time and importing another time.

**Actual result:**
UI didn't look like anything was going on. LEDGER_VERBOSE=true showed a 400 error.
https://gist.github.com/LaurenWags/a156933a2acaaa43bfef199390c02ec3#file-400error-txt-L231

**Expected result:**
Wallet should be recovered.

**Reproduces how often:** [What percentage of the time does it reproduce?] unknown

### Brave Version

**about:brave info:**
Brave | 0.19.70
rev | d4b94c6
Muon | 4.5.9

**Reproducible on current live release:**
yes

**Comment by LaurenWags** [comment]
Sometimes you may also get a 'Recovery Failed' message in the UI after waiting for a period of time.

**Comment by evq** [comment]
based on those transcripts the 400 error appears only tangentially related to failed wallet recovery. (it is not a recovery operation returning 400, instead during recovery it would appear that normal polling of wallet information is still performed and fails, as one would expect.)

interestingly the wallet recovery failed with 503 at first but appears to have succeeded on the second try - but it sounds like your experience was that it still wasn't working / reflected in the ui?

**Comment by LaurenWags** [comment]
I've seen it work eventually, but some users are reporting seeing 'Recovery Failed' each time (but not immediately). They've reported waiting 10-15 minutes and then finally seeing Recovery Failed.

**Comment by NejcZdovc** [comment]
@LaurenWags is this still a problem?

**Comment by LaurenWags** [comment]
@NejcZdovc I haven't had reports of this since Nov. I think we can close for now and reopen if needed.
