### ISSUE TITLE
Brave 0.19.70 macOS web sockets not working. 

### ISSUE THREAD

**Issue by MoMannn** [brave/browser-laptop#11716]
### Description
Webpages that use sockets are not working. 

### Steps to Reproduce
If I open a webpage like: asana, zeplin, slack after a few seconds I get an error that they lost connection and cannot reconnect due to socket problems.

**Actual result:**
Error from zeplin:
<img width="1031" alt="screen shot 2017-10-29 at 20 27 28" src="https://user-images.githubusercontent.com/8865298/32147444-aa565c06-bce7-11e7-87dc-71118d818b8a.png">

**Expected result:**
Normal working webpage

**Reproduces how often:** 
Always

### Brave Version

Brave: 0.19.70 
rev: d4b94c6215bb130250fe5245787a5884dc9b51fe 
Muon: 4.5.9 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.5.0 
OS Architecture: x64

**Comment by luixxiul** [comment]
Will this be available on 0.19.x?

**Comment by bbondy** [comment]
Fixed with muon 4.5.12

**Comment by kjozwiak** [comment]
Adding a WebSocket test into the wikitemplate-cr-upgrade template so we can catch any further issues when updating chromium.

**Comment by bbondy** [comment]
I Incorrectly referenced this issue for 4.5.13 commits above, when it was meant to say: https://github.com/brave/browser-laptop/issues/11471
