### ISSUE TITLE
Brave browser doesn't open on Windows 10 laptop after upgrade to 0.19.70.0 version.

### ISSUE THREAD

**Issue by f7l** [brave/browser-laptop#11715]
I downloaded the Brave browser in November of 2016 and stopped using it after a few months, it was working normal though, I just stopped using it. Then a few weeks ago I decide to use it and it doesn't open.

I uninstall it and remove the related folders then install the new version (which was 0.19.48.0 two weeks ago), yet when it finished installed, I double clicked on the new icon and nothing, maybe a brief loading on my mouse icon before it went away and nothing happened. Clicked the Brave icon that I pinned to my taskbar, still nothing.

I decide to try again today, but I accidentally double clicked on the Brave Setup installer that was downloaded back in November 2016, this time it worked. Brave Browser opened and was working like it used to before. I checked the version that was now running successfully and it said 0.12.7.0, and after a while an update notice asked me if I wanna update to the newest version. I did. It closed itself, saying it had to restart, then nothing. It didn't open again. I double clicked the icon on my desktop and taskbar and still nothing.

So I uninstall again and remove the folders, then I install the old version again, 0.12.7.0, and it worked. The Brave browser opened and was working fine. So I figured I just wouldn't update it. But when I closed it, while it was closed I'm not sure if it updated on its own cause I tried to double click on the shortcuts on my desktop and taskbar again and nothing.

I don't understand what the problem is if the old version works but the new versions don't. I feel like it's doomed and I should just stick with FireFox.

**Comment by luixxiul** [comment]
I suspect downgrading has broken the profile data.

**Comment by bsclifton** [comment]
@f7l we have had users report that Brave shows in the taskbar but just isn't visible.  This may be remedied by using Windows key + arrow keys (like Windows + Up arrow)

If it's not showing in the taskbar, I'm curious if the process is open.  You should be able to hit Ctrl + Alt + Del, open task manager, and then look for any `Brave.exe` entries. (this will
![screen shot 2017-10-30 at 12 07 54 am](https://user-images.githubusercontent.com/4733304/32158594-ac6967e4-bd06-11e7-8389-6f81d7b4e600.png)
 be on the details tab on Windows 10)


If the profile folder is what is broken (as @luixxiul hints at above), you can try deleting that folder.  You'll find the `brave` folder at `%appdata%` (if you're not sure where to put that, hold Windows key + push R, then paste that into the Run box).  You can either delete the old `brave` folder or rename it (ex: `brave-old`)

**Comment by f7l** [comment]
Wow, that really helped. I had no idea about that appdata folder. I deleted it and reinstalled 0.19.70.0, and now the new version of Brave is working fine. Thank you.

**Comment by bsclifton** [comment]
@f7l awesome, glad to hear 👍  Happy browsing 😄
