### ISSUE TITLE
Tabs not closing + visualization issues

### ISSUE THREAD

**Issue by egferro** [brave/browser-laptop#11713]
### Description
Often the first tabs (those on the left hand side of the window) I open do not disappear when I click on the x to close them .
Also when I launch brave after I used a double scree it often does not appear in the foreground. I need to use a keyboard trick to visualize it (start + arrows). I was told this issue was solved with version 18 but now I am using 19.53 and it is still there.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
> I was told this issue was solved

could I know where you were told that?

**Comment by bsclifton** [comment]
The tabs not closing issue appears to be the same issue as reported in https://github.com/brave/browser-laptop/issues/11593

For the other issue (browser not showing), this is reported with https://github.com/brave/browser-laptop/issues/11698.  I'll share the work-around you mentioned

I'll close this issue as a duplicate.  If you had more info about the work-around (using start + arrows), please do let us know 😄  Thanks!

**Comment by egferro** [comment]
@luixxiul  it was a person from Brave support I guess on github.
