### ISSUE TITLE
Contribution amounts were not updated during BTC => BAT conversion

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11719]
## Test plan

https://github.com/brave/browser-laptop/pull/11722#issue-269750293

----

### Description
Before BAT Mercury was released (0.19.x), there were a few contribution amounts you could pick:
$5, $10, $15, $20 (USD)

After BAT Mercury, users could choose:
25, 50, 75, 100 (BAT)

However, the amounts were never converted.

### Steps to Reproduce

  1. Use an older version of Brave (0.18.36 for example)
  2. Enable payments and set contribution amount as one of the original amounts (like $10 for example)
  3. Upgrade to latest Brave
  4. In preferences#payments, you should notice it say 25 BAT
  5. Open the `ledger-state.json` file and inspect, looking for the properties section:
```json
{
  "properties": {
    "setting": "adFree",
    "fee": {
      "currency": "BAT",
      "amount": 10
    },
    // other data...
  },
  // other data...
```

**Actual result:**
Value is kept as 10

**Expected result:**
Value should be converted to equivalent:
5 USD => 25 BAT
10 USD => 50 BAT
15 USD => 75 BAT
20 USD => 100 BAT

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**
 
Brave: 0.19.70 
rev: d4b94c6215bb130250fe5245787a5884dc9b51fe 
Muon: 4.5.9 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
yes

### Additional Information

Here's a screenshot showing that payment for 10 BAT was processed (and you can see the UI shows 25 BAT as my selection)
![image](https://user-images.githubusercontent.com/4733304/32187013-f0574674-bd60-11e7-8d67-b1bc45b95395.png)

**Comment by srirambv** [comment]
Still seeing this on upgrade from 0.18.36 to 0.19.71
![11719](https://user-images.githubusercontent.com/17010094/32276575-787760d2-bf07-11e7-8ada-fb290bb00f79.gif)

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/13c479b8715f709889a3462794cb1644bb902533
0.21.x https://github.com/brave/browser-laptop/commit/23e8c4821808a11fbe907661f4d38288e11355c1
0.20.x https://github.com/brave/browser-laptop/commit/837761445d650427a985a4d5cf322a6121ba1dd9
0.19.x https://github.com/brave/browser-laptop/commit/8a49077b56d8149ef8192365feee8f79fbbe8849
