### ISSUE TITLE
No way to mute individual tabs.

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11724]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
which site do you experience the issue?

**Comment by luixxiul** [comment]
if you are not quite sure about the issue, let's continue the discussion on https://community.brave.com/c/qa.

**Comment by TheCNixon** [comment]
Sorry, I don't know where to suggest features but there is a lack of individual page muting options at least on the Windows application, and this is a vital feature that every other browser has.

**Comment by luixxiul** [comment]
I see. For feature suggestions, please have a look at this category of the forum: https://community.brave.com/c/feature-requests. Thanks!
