### ISSUE TITLE
The Atlantic - anti-ad blocking content blocker

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#11729]
### Description

Anti-ad blocking has returned to theatlantic.com

This was resolved: https://github.com/brave/browser-laptop/issues/6291 but has been updated by The Atlantic, and needs to be neutralized. 

### Steps to Reproduce

 - Navigate to https://theatlantic.com. 

 - User navigates to an article from the homepage. 

 - Once the article loads, about 10-15 seconds after the page load is completed, they are displayed this message. 

![brave-theatlantic-10312017-blocking](https://user-images.githubusercontent.com/8979240/32235709-74e5f856-be1d-11e7-9df2-727f76c51781.PNG)

On first pass, it appears to be an updated script that is making the call (potentially from Optimizely), that is not covered on the filter list. 

**Actual result:**
See screenshot above. 

**Expected result:**
No blocked content. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

### Brave Version

**about:brave info:**
Brave | 0.19.70
rev | d4b94c6

**Reproducible on current live release:**
Yes

**Comment by dxxvi** [comment]
0.19.139 also has this issue.

**Comment by lukemulks** [comment]
Fixed here: https://github.com/brave/adblock-lists/commit/43ea3e9c5d86463b1001f72791694e4d2a3e2447#diff-3d05cf908db454bc68b7983ddc029cb0

**Comment by jonathansampson** [comment]
@lukemulks I popped the adblock message today when visiting the site; after manually adding your changes to about:adblock, the issue was resolved. Do we need to refresh Heroku or something with your changes?
