### ISSUE TITLE
Not automatically updating Windows Brave browser with prompts to update

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#11734]
### Brave Version

**about:brave info:**
 
Brave: 0.19.58 
rev: fe749c59b743160c55fdad906c13c798c7141562 
Muon: 4.5.4 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Not sure.

### Additional Information
https://github.com/brave/browser-laptop/wiki/How-auto-updates-for-Brave-work-on-Windows

**Comment by hugobuddel** [comment]
FWIW, it is not clear to me whether you want Brave to auto-update and it is not happening, or whether Brave is auto-updating when you don't want it to happen. Or whether there is a problem with the prompting.

I'm not a Brave developer so my thoughts are not really relevant; maybe the Brave developers do understand. It reminds me of this Simpsons clip: https://www.youtube.com/watch?v=aEimfudOW6U

**Comment by jamesray1** [comment]
The latest stable release is the version that I have. So that's why I haven't got a prompt to update.

**Comment by srirambv** [comment]
@jamesray1 https://github.com/brave/browser-laptop/issues/11638 is the reason why you are not getting prompt for upgrading to preview build.

**Comment by jamesray1** [comment]
I'm not sure I don't remember enabling any preview option.
