### ISSUE TITLE
Spell check should be disabled if no language is set

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11739]
## Test plan

https://github.com/brave/browser-laptop/pull/11758

----

### Description

Spell check should be disabled if no language is set.

### Steps to Reproduce

STR:
1. Clear the browser profile
2. Start the browser
3. Open about:preferences#general
4. Remove `English`
5. Restart the browser
6. Open about:styles
7. Enter some random words on a text box

**Actual result:**

The words are underlined, suggesting the correct spells in English

**Expected result:**

The words should not be underlined (even if the spell check option is enabled)

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Brave Version

**about:brave info:**

0.19.71

**Reproducible on current live release:**

No.

### Additional Information

Follow-up to https://github.com/brave/browser-laptop/pull/11710. https://github.com/brave/browser-laptop/issues/7898

**Comment by darkdh** [comment]
any OS or just Mac?

**Comment by srirambv** [comment]
Same on Windows as well.

**Comment by luixxiul** [comment]
I experience the issue on Debian.
