### ISSUE TITLE
marketwatch.com - Ad slot "loading" icon

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#11730]
### Description
https://www.marketwatch.com/ displays loading icons in the ad slots that do not stop spinning. 

![brave-marketwatch-10312017](https://user-images.githubusercontent.com/8979240/32236281-f3f402f4-be1e-11e7-94be-30805d1be599.PNG)

### Steps to Reproduce

  1. go to https://www.marketwatch.com/
  2. see ad slots with spinning icons
  3. fight hypnosis.

**Actual result:**
See above
**Expected result:**
No spinning icons. 
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

Brave | 0.19.70
rev | d4b94c6

**Reproducible on current live release:**
Yes

**Comment by kjozwiak** [comment]
This doesn't appear to be a new regression, looks it was happening under `Brave v0.19.53` rev: e09025bf61debc46c03459def2501b3367f182d7 as well. Was double checking to ensure that it wasn't introduced in `0.19.70`.

**Comment by jonathansampson** [comment]
Looks like it's just an animated pseudo element. We could hide them with our own injected stylesheet.

![marketwatch-loading](https://user-images.githubusercontent.com/815158/32252245-8261df0a-be62-11e7-9a9d-c6d31badaad9.gif)

**Comment by btlechowski** [comment]
Verified Win7 x64 v0.22.108

**Comment by kjozwiak** [comment]
@GeetaSarvadnya can you recheck this on Win?
