### ISSUE TITLE
Add Copying an Image Directly to the Clipboard Through the Context Menu

### ISSUE THREAD

**Issue by Mrfiregem** [brave/browser-laptop#1174]
In most other browsers, you're able to copy an image directly to the clipboard through the context menu by right-clicking it, but in Brave you can't do that. I know copying the image link was recently added to the context menu but it'd be nice to have this feature as well

**Comment by bradleyrichter** [comment]
let's get this party started!

![image](https://cloud.githubusercontent.com/assets/13509546/16509372/c8e62438-3ef0-11e6-95d2-50805565ac3d.png)

@bsclifton ?   :   )

**Comment by bsclifton** [comment]
This would be a good one, self assigning :smile: I was thinking about doing this the other day (along with adding Search <provider> with this image)

**Comment by bsclifton** [comment]
This one ended up not being as easy as I initially thought. The electron `webContents` object does have a `hasImageContent` boolean when the `context-menu` event is fired and it's also easy to get the URL.  However, I'm not sure how to get the image into the clipboard.

I tried loading the URL into a `nativeImage` object and using `clipboard.writeImage(imageObjectHere)`, but was not successful (DataURL is a typo on their part, it's not actually a URL- it's supposed to be in [Data URI format](https://en.wikipedia.org/wiki/Data_URI_scheme).

Any advice on what to look at? Hoping I'm missing something obvious

cc: @bbondy @bridiver

**Comment by bbondy** [comment]
You can get a data URL from an image if you create a canvas element, draw an image to it and use `<canvas>.toDataURL`. [Here](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/js/about.js#L33)'s some relevant code, but I don't think you need to actually insert it into the DOM (although, maybe you do temporarily, not 100% sure).

Also for this type of task (clipboards & drag'n drop) it's useful to use a clipboard viewer program and compare to the other browsers. There are a lot of little free apps that do that out there, just grab one of those.

**Comment by bbondy** [comment]
Sorry for jumping in @bsclifton, just happened to try what I suggested and it worked.  Hope you don't mind!

**Comment by bsclifton** [comment]
It's all good, I had forgotten about this :smile:

**Comment by BrendanEich** [comment]
Sweet!

**Comment by luixxiul** [comment]
It seems that it does not work on Ubuntu 14.04. You cannot paste image on Gimp.

**Comment by bbondy** [comment]
You might want to try to make sure the same works on chrome, it is probably the same data clipboard format. It might just be Gimp on Ubuntu not supporting the paste format.  If it's an issue though just post a new issue and reference this one.
