### ISSUE TITLE
Spell check should auto include the language set in browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11743]
### Description
Spell check should auto include the language set in browser

### Steps to Reproduce
  1. Install 0.19.71
  2. Change browser language to Spanish
  3. Restart the browser from the notification
  4. Only English spell check is shown, no Spanish

**Actual result:**
Only shows default spell check (English)

**Expected result:**
Should automatically detect browser language and add that language spell check

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.19.71
-- | --
rev | 3b03f08
Muon | 4.5.12

**Reproducible on current live release:**
N/A

### Additional Information
cc: @darkdh

**Comment by bsclifton** [comment]
Unfortunately, we won't be able to address this before switching to [brave-core](https://github.com/brave/brave-browser)
