### ISSUE TITLE
Spell check clear all button is too close to pull down button

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11741]
### Description

Spell check clear all button is too close to pull down button.

![clipboard01](https://user-images.githubusercontent.com/3362943/32267665-65987f5a-bf2f-11e7-8d90-0ef2d81a2df9.png)

### Steps to Reproduce

  1. Open about:preferences#general
  2. Click around the spell check pull down button

**Actual result:**

Sometimes the clear all button is pressed

**Expected result:**

The clear confirmation message should be displayed if the button cannot be moved next to the languages

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Brave Version

**about:brave info:**

0.19.71

**Reproducible on current live release:**

No.

### Additional Information

https://github.com/brave/browser-laptop/pull/11710

**Comment by luixxiul** [comment]
The tab close button styling could be applied here.

**Comment by luixxiul** [comment]
Maybe we do not need that clear all button at all, as probably there are usually only a couple pf languages selected. It should be a rare case that many languages like 10 or more are selected.

**Comment by bsclifton** [comment]
Closing as `wontfix` - created issue in [brave-core](https://github.com/brave/brave-browser) to ensure we have parity for this functionality:
https://github.com/brave/brave-browser/issues/726
