### ISSUE TITLE
Cannot switch to old tabs

### ISSUE THREAD

**Issue by yesmar12** [brave/browser-laptop#11750]
### Description
I cannot switch to tabs that I have not opened in a while. Using shift+ctrl+[ and click ing isineffective at switching over to the failing tab(s). Right clicking and closing, detaching, and pinning does not work. Right clicking on the bad tab and pressing new tab does work. Reloading does seem to work as the tab preview shows the it refreshing but the tab is still unselectable.

This issue seems to be similar to #10910. My issue is not reproducible the same way #10910 is. 

So far the only way I have found to get around this issue is to restart brave as a whole.

### Steps to Reproduce

Not sure how to reproduce yet but this has happend a few times so it should be easy to figure out. Will update with more information.

### Brave Version

 
Brave: 0.19.70 
rev: d4b94c6215bb130250fe5245787a5884dc9b51fe 
Muon: 4.5.9 
libchromiumcontent: 62.0.3202.62 
V8: 6.2.414.32 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**

### Additional Information

![bravetaberror](https://user-images.githubusercontent.com/15841504/32287546-33baf90c-beff-11e7-9696-b4485a2b18d9.gif)

**Comment by yesmar12** [comment]
I cannot find any reason why it happens, so far. It happens to some tabs but not all. Any tips to help me recreate this?

**Comment by bsclifton** [comment]
@yesmar12 have you experienced this recently? I know we've had several specific fixes for this issue and there haven't been any new reports here.  I'll close the issue for now; please reply or re-open if you still experience. Thanks! 😄
