### ISSUE TITLE
gmail load bar is broken by fingerprinting protection

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11751]
see https://github.com/brave/browser-laptop/issues/11683#issuecomment-341224448

**Comment by srirambv** [comment]
Getting an second WebRTC FP block on 0.19.80
![image](https://user-images.githubusercontent.com/17010094/32320970-8c847a3c-bfb7-11e7-9f9b-c3ded03071bc.png)

on 0.19.70
![image](https://user-images.githubusercontent.com/17010094/32322424-619363e2-bfbc-11e7-8039-6a4c3978219c.png)

**Comment by diracdeltas** [comment]
this can be closed because we reverted the original fix for #11683

**Comment by bsclifton** [comment]
PR has been reverted with https://github.com/brave/browser-laptop/commit/fe2fcedfdca94aeb29351fdd2388a3dca23fcedd

Re-opening so that we can look at a fix for 0.20.x

**Comment by diracdeltas** [comment]
Closing this because it wasn't an issue before https://github.com/brave/browser-laptop/commit/fe2fcedfdca94aeb29351fdd2388a3dca23fcedd (the PR that created this issue was https://github.com/brave/browser-laptop/pull/11708, which was also reverted)
