### ISSUE TITLE
Implement native GTK buttons on Linux

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11767]
### Description

https://community.brave.com/t/implement-native-gtk-buttons-on-linux/10058

> Currently, Brave uses the native Linux title bar and it would be awesome if native GTK buttons could be implemented so that a title bar is not needed. Brave would look much cleaner and there would be more space for websites, especially on laptops. Chrome has a good approach where by default native buttons are used and the user can switch to a full title bar depending on the preference.
> 
> Chrome CSD:
> http://www.omgubuntu.co.uk/2017/10/chrome-gtk-window-controls
>
> Chrome bug tracker link:
> https://bugs.chromium.org/p/chromium/issues/detail?id=753067
>
> Firefox CSD:
http://www.omgubuntu.co.uk/2017/08/firefox-client-side-decoration-coming-soon
> 
> Firefox bug tracker link:
https://bugzilla.mozilla.org/show_bug.cgi?id=1283299

**Comment by Jacalz** [comment]
+1 on this! Really a great option to add. Integrating native GTK buttons will make Brave way better.

**Comment by Jacalz** [comment]
Please move it up in priority :)

**Comment by NumDeP** [comment]
+1

**Comment by JamesTiberiusKirk** [comment]
+1
