### ISSUE TITLE
Spellcheck is slow to show misspellings with three or more languages

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11765]
### Description

Adding three or more languages into the spellcheck feature under `about:preferences#general` will break spellcheck throughout the browser. If there's a limitations on languages that can be selected, we need to incorporate that into the UI. Example, if it only supports two language, only allow the user to pick two languages via the UI under `about:preferences#general.

### Steps to Reproduce

  1. visit `about:preferences#general` and select "English" & "Spanish" (restart)
  2. visit `about:styles" and type in "websdfay tomrrow" into a text area (should highlight)
  3. go back into `about:preferences#general` and add another language (restart)
  4. go back into `about:styles" and type in "websdfay tomrrow" (won't be highlighted)
  5. type in "responsobilidad amstoso" (won't be highlighted - Spanish)
  6. go back into `about:preferences#general` and remove the third language (restart)
  7. repeat step 2 and 5 and highlighting will work again

**Actual result:**

Spellcheck stops working throughout the browser when you add a third language

**Expected result:**

Spellcheck should work despite the amount of languages being selected.

**Reproduces how often:**

100% reproducible when following the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.80 
> rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
> Muon: 4.5.13 
> libchromiumcontent: 62.0.3202.75 

**Reproducible on current live release:**

The feature hasn't been released yet. However, when it's being fixed, the issue will be in the live release.

### Additional Information

* @LaurenWags working under macOS (see https://github.com/brave/browser-laptop/issues/11765#issuecomment-341465202)
* @srirambv reproduced the issue under Windows 10
* @kjozwiak reproduced the issue under Ubuntu

CCing @darkdh

**Comment by LaurenWags** [comment]
update: on MacOS I'm seeing highlighting but no suggestions when right-click.

**Comment by darkdh** [comment]
@kjozwiak how long did you wait after you add a new language? It's async and will take time when first time loaded.
![kapture 2017-11-02 at 9 10 13](https://user-images.githubusercontent.com/11330831/32336847-a95d1556-bfad-11e7-8599-ae87a43a5cf7.gif)

@LaurenWags mac is different than linux and windows so please open another issue for mac

**Comment by bsclifton** [comment]
Works great for me too on both Windows and macOS

Please note that it may take a few seconds to show the underline.  I pasted and then hit enter, it showed about 3 seconds later

**Comment by cezaraugusto** [comment]
should we inform the user that "this might take a few seconds"?

**Comment by bsclifton** [comment]
cc: @bradleyrichter @alexwykoff @jenn-rhim @jamesmudgett for comment

**Comment by kjozwiak** [comment]
> should we inform the user that "this might take a few seconds"?

I'm not sure if that's necessary as adding a new language into the list prompts the user to restart the browser via a notification. Do we even need the restart notification? From the sounds of what @bsclifton and @darkdh mentioned above, all the user has to do is wait a few seconds before the changes take affect.

I can't seem to reproduce this with `0.19.89`, however I did notice that sometimes incorrectly spelled words will stop being underlined unless something new is typed into the same textbox or the spaces between the incorrectly spelled words are adjusted... I'll see if I can get better STR.

**Comment by bsclifton** [comment]
Closing as stale- let's reopen if this is still a problem
