### ISSUE TITLE
Make release upload names less confusing

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11761]
Someone noted recently, but I can't find the issue how confusing our releases page is, and they were right.

"Dev Channel Beta v0.19.75dev"

This is actually for the release channel but it has the internal name "dev" all over the place and it also has the word beta in it.  Github already has a pre-release marker so we don't need to make the name confusing like that to scare people away from using pre-release builds.

**Comment by kjozwiak** [comment]
@bbondy were you looking for https://github.com/brave/browser-laptop/issues/11638#issuecomment-341066069?
