### ISSUE TITLE
running "npm start" places "Crashpad" into "brave" rather than "brave-development"

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11760]
### Description

@LaurenWags noticed that `npm start` under macOS creates the following two directories when running a build from source:

* /Users/kjozwiak/Library/Application Support/brave
* /Users/kjozwiak/Library/Application Support/brave-development

It looks like `Crashpad` is being placed into `brave` rather then `brave-development` under macOS. I checked on both Ununtu 17.04 and Win 10 and couldn't reproduce.

### Steps to Reproduce

  1. pull the latest changes into any branch under macOS (reproduced `0.19.x`, `0.20.x` & `0.21.x`)
  2. once you have the latest changes, `npm install`
  3. once installed, `npm run watch` & `npm start`

**Actual result:**

`Crashpad` is being placed inside the `brave` folder

**Expected result:**

`Crashpad` should be placed inside the `brave-development` folder

**Reproduces how often:**

100% reproducible under macOS using the above STR.

### Brave Version

**about:brave info:**

* 0.21.x branch under macOS - Reproduced
* 0.20.x branch under macOS - Reproduced
* 0.19.x branch under macOS - Reproduced

### Additional Information

* Win 10 Pro x64 - Couldn't Reproduce
* Ubuntu 17.04 x64 - Couldn't Reproduce

CC'ing @LaurenWags @darkdh

**Comment by bsclifton** [comment]
P5 since it's only affecting dev builds; may have been fixed with https://github.com/brave/browser-laptop/pull/11808

**Comment by darkdh** [comment]
caused by https://github.com/brave/muon/pull/376

**Comment by darkdh** [comment]
actually I couldn't reproduce it.
can you show me your muon version?

**Comment by kjozwiak** [comment]
I can't reproduce this anymore either. The `Crashpad` folder is being placed inside `brave-development` as expected. I went through the following branches on macOS:

* v0.22.0 fe63aae57ebc753ec674058c836ff45c6ae51c5c - couldn't reproduce
* v0.21.0 94cc016f78a8595a548559cdefc767b32c6a365a - couldn't reproduce
* v0.20.x d201e0d5b53e2639ec0b3fd3862f1fb955e812b7 - couldn't reproduce
* v0.19.x 20badac0c818421c22310c3805a07e2caaea20bb - couldn't reproduce

@LaurenWags can you check and see if you can reproduce this anymore as you've also seen the issue?

**Comment by LaurenWags** [comment]
@kjozwiak I was unable to reproduce this issue.

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by kjozwiak** [comment]
Going to quickly recheck this one more time and close it off if I can't reproduce. Looks like @LaurenWags isn't seeing the issue anymore either.

**Comment by kjozwiak** [comment]
Closing... I couldn't reproduce the issue using the following branches:

* v0.22.0 3f6fcc5736b95ac6125ca18bde4813cdf75f83ef - couldn't reproduce
* v0.21.2 81f0f6010efa9e8017ec89ae29682617a912ca96 - couldn't reproduce
* v0.20.7 787b5ea1c14549dfa165fa0f755376d5cbf4c1fd - couldn't reproduce
* v0.19.106 61b231a0f842afe18a32bc9980b0d50be41d83a5 - couldn't reproduce

@LaurenWags couldn't reproduce this on her machine either as mentioned above.
