### ISSUE TITLE
Pinned tabs will not load on startup

### ISSUE THREAD

**Issue by tdarr2201** [brave/browser-laptop#11783]
### Description

I've created some pinned tabs and everything was working fine. This morning, when I started Brave, some of the pinned tabs just show the spinning wheel as if they are trying to load. There is one pinned tab that loads correctly. I have searched for similar issue and tried deleting the profile folder and that did not work.

Also, if I select Help->About Brave, a tab is created, but there is nothing in the tab and I cannot select the tab. Same with Edit->Settings, etc.

![capture](https://user-images.githubusercontent.com/16431081/32377053-85529f38-c074-11e7-89d3-648aec7313dc.JPG)

### Steps to Reproduce

  1. Create some pinned tabs - I don't think there is anything special about what I pinned
  2. Quit Brave
  3. Run Brave
  4. Select Help->About Brave - tab comes up but nothing is there and nothing can be selected

**Actual result:**

Screen shot attached for loading pin problem.

**Expected result:**

**Reproduces how often:**

Since the problem started, it happens all the time.

### Brave Version

**about:brave info:**

This does not work - see description.

**Reproducible on current live release:**

Don't know.

**Comment by luixxiul** [comment]
Hi, does restarting not work for you?

**Comment by tdarr2201** [comment]
No. I have tried re-starting several times.

**Comment by tdarr2201** [comment]
The only pinned tab that works is feedly as can be seen in the screen shot.

**Comment by bsclifton** [comment]
I have this problem too- it's happened for several versions (it's not specific to 0.19.x).  I believe this is a duplicate of https://github.com/brave/browser-laptop/issues/9001

@tdarr2201 are you willing to share the sites you have pinned? (please don't share if the URL has any sensitive info, like username, etc)

**Comment by tdarr2201** [comment]
To be honest, I cannot recall what sites are pinned. I just started using the Brave browser less than a week ago. I also don't think it is exactly like https://github.com/brave/browser-laptop/issues/9001. I would be happy enough at this point to be able to remove the pinned tabs. I can always remove my profile and / or re-install to get back to the original settings.
