### ISSUE TITLE
"Save Link As" doesn't follow redirects

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11788]
### Description
The _Save Link As_ option doesn't follow redirects, and thus will attempt to download the intermediary file, rather than the end of a redirect chain.

For instance, assume the following: `<a href="download.php?file=18112">Download PDF</a>`. If the _download.php_ file uses a `location` header to redirect to a PDF, Brave will download the HTML response for _download.php_, rather than downloading the PDF in the `location` header.

### Steps to Reproduce
TBD: Need to find a public example. Only repro site I have at this time requires authentication.

**Actual result:**
HTML of response is downloaded.

**Expected result:**
If a location header is present, it will be followed.

**Reproduces how often:**
100%

### Brave Version
0.19.80

**about:brave info:**
```
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
```

**Reproducible on current live release:**
Yes

### Additional Information
Similar to https://github.com/brave/browser-laptop/issues/8463.

**Comment by jonathansampson** [comment]
I'm working on a repro of this, and will be speaking with a community user against Monday (Nov 04, 2017) to get access to the original, impacted website (requires credentials, which I do not have at this time).

**Comment by hugobuddel** [comment]
"Save link as" does not work at all with websites that require authentication. It will download the login page, I think because it does not send cookies with credentials, see #11444. So maybe that's what you are seeing? Or did you manage to reproduce this on a authentication-free website?
