### ISSUE TITLE
Enabling both English (US) and Japanese for spellcheck does not check spells in English

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11782]
### Description

Enabling both English (US) and Japanese for spellcheck does not check spells in English. 

If only English is enabled, it works correctly.
If English and Japanese are enabled, it does not work correctly.

I have not tested other languages but @srirambv @eljuno could test other languages 😄 

### Steps to Reproduce

Case 1
  1. Open about:preferences
  2. Enable English only for spell check
  3. Open about:styles
  4. Input some random words
  5. Make sure the words are underlined

Case 2
  1. Open about:preferences
  2. Enable English and Japanese for spell check
  3. Repeat 3-4 above
  4. Make sure the words are not underlined

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

Yes.

**Comment by bsclifton** [comment]
Unfortunately, we won't be able to address this before switching to [brave-core](https://github.com/brave/brave-browser)
