### ISSUE TITLE
Long bookmarks menu that crosses screen border not scrollable

### ISSUE THREAD

**Issue by beingalink** [brave/browser-laptop#1178]
I can't access all of my bookmarks because the navigation isn't scrollable if the menu is too long and crosses the bottom screen border.

Brave 0.8.2 on OS X 10.11.4

**Comment by marti1125** [comment]
I would like to take this issue. I have OS X 10.11.4

**Comment by bbondy** [comment]
Sure thanks @marti1125 if you have any questions just let us know.  
See https://github.com/brave/browser-laptop/blob/master/docs/debugging.md for some tips.

**Comment by marti1125** [comment]
Hi @bbondy  I have problem when I tried to run: sudo npm install

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.4.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE

npm ERR! abp-filter-parser-cpp@1.1.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abp-filter-parser-cpp@1.1.10 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the abp-filter-parser-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs abp-filter-parser-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls abp-filter-parser-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/willyaguirre/Documents/browser-laptop/npm-debug.log

**Comment by luixxiul** [comment]
@marti1125 please follow the latest instruction on the README and try again, without ``sudo``

**Comment by marti1125** [comment]
ok :)

**Comment by marti1125** [comment]
Hi @beingalink and @bbondy  I can not replicate this issues :( could you share a screentshoot?
Here you are my test
<img width="539" alt="captura de pantalla 2016-05-29 a las 11 08 28" src="https://cloud.githubusercontent.com/assets/223240/15634600/c1b87b10-258d-11e6-9bd8-2f14a032b531.png">

<img width="1279" alt="captura de pantalla 2016-05-29 a las 11 06 52" src="https://cloud.githubusercontent.com/assets/223240/15634599/a504fb74-258d-11e6-93a3-20250fb5b9b3.png">

**Comment by beingalink** [comment]
@marti1125 It looks like scrolling works now in current brave. There are lots of other issues with bookmarks in brave but this one seems fixed.

**Comment by luixxiul** [comment]
OK closing.
