### ISSUE TITLE
Disabling 'Show bookmark matches' does not work.

### ISSUE THREAD

**Issue by KenyaAdams** [brave/browser-laptop#11787]
### Steps to Reproduce

  1. Navigate to 'about:bookmarks'
  2. Add a new bookmark to a site that you have never visited (Ex: www.TestPage920492.biz)
  3. Navigate to 'about:preferences#search'
  4. Disable 'Show bookmark matches'
  5. Start typing the bookmarked site (Ex: 'TestPage920492.biz') into the address bar

**Actual result:**
The bookmarked site appears as a history suggestion.

**Expected result:**
No bookmarks should be matched when typing in the address bar.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**

Yes

**Comment by echosa** [comment]
Relatedly, if you have "Show bookmark matches" enabled but "Show history matches" disabled, bookmark matches do not show up in search, even though it's marked as enabled. I believe this is related to the combining of bookmarks and history in the search area (a decision I personally disagree with), which is discussed and mentioned here and in other issues: https://github.com/brave/browser-laptop/issues/11802

Essentially, it seems like the "Show bookmark matches" toggle is useless, and the "Show history matches" toggle unfortunately controls both.

```
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```

CC @luixxiul @NejcZdovc

**Comment by rebron** [comment]
Closing. Dupe and tracking here: https://github.com/brave/brave-browser/issues/1048
