### ISSUE TITLE
Ledger faq icon alignment issue

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#11786]
### Description
FAQ icons in Brave Payments ledger are vertically misaligned. 

 - This has been observed in Win64. 
 - Have not attempted to repro on macOS. 
 - Screencap below with icons and guidelines to illustrate. 
![brave-payments-alignment-highlight-11032017](https://user-images.githubusercontent.com/8979240/32402767-833cc9ac-c0e8-11e7-8b2a-ebfe7e602b3a.PNG)

### Steps to Reproduce

  1. Navigate to Brave Payments ledger.
  2. Observe the faq icon alignment. (see screenshot above)

**Actual result:**
see screenshot above.

**Expected result:**
faq icons should be vertically aligned.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
yes

**Comment by NejcZdovc** [comment]
closing this one as we don't have two FQA icons anymore
