### ISSUE TITLE
Updates on Beta channel are not working 

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#11795]
### Description
Check for updates, get a message beginning with "Oops! We were not able to update."

[updateLog.log](https://github.com/brave/browser-laptop/files/1444553/updateLog.log)

**Reproduces how often:**
100%

### Brave Version
 
Brave: 0.19.58 
rev: fe749c59b743160c55fdad906c13c798c7141562 
Muon: 4.5.4 
libchromiumcontent: 62.0.3202.38 
V8: 6.2.414.23 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Not sure.

### Additional Information
Brave also keeps crashing randomly without any apparent cause.

**Comment by jamesray1** [comment]
I went to brave.com and installed Brave, and now I have Brave 0.19.7, but the tab got frozen on that, so I think I'll need to use another browser.

**Comment by bsclifton** [comment]
@jamesray1 0.19.58 is a beta release and it may not have been a proper release either.  Can you please download a stable channel release?
https://github.com/brave/browser-laptop/releases/tag/v0.19.80dev

**Comment by bsclifton** [comment]
OK I did verify it was an actual Beta release- this can be seen here:
https://github.com/brave/vault-updater/blob/master/data/beta/winx64.json

@aekeus any ideas on why the update would fail?

**Comment by jamesray1** [comment]
If I ran the install from brave.com, shouldn't this install the latest stable release? When I ran the install it installed 0.19.7. I'll try that again as I may have used an older installation file with the same filename. If it doesn't install the latest release (0.19.80) I'll try downloading and installing that.

**Comment by bsclifton** [comment]
@jamesray1 I just tried right now with Windows and the download link on Brave.com is for 0.19.80, as expected.  Are you running a cache/proxy at your house (like squid?) 

The link on Brave.com is to:
https://laptop-updates.brave.com/latest/winx64

**Comment by bsclifton** [comment]
Regarding 0.19.58 (Beta) not able to upgrade, there is an actual issue with our beta releases at the moment.  The binaries were not properly uploaded to S3.  I'll be looking at investigating this issue

**Comment by jamesray1** [comment]
I downloaded and installed Brave 0.19.80 for Windows from brave.com. As I suspected I think I must have used an installation file that I downloaded from before.

**Comment by bsclifton** [comment]
Not actually fixed (yet)

The uploads were fixed correctly with https://github.com/brave/release-tools/pull/2, but the service isn't taking `Beta-` in the filename into account.  We'll need to update the server side on that one.

@aekeus can you help me look at this one? 😄

**Comment by jamesray1** [comment]
OK, keep up the good work, the browser keeps getting better and better! I love the open-source approach. It'll be great to try out the BAT.

**Comment by bsclifton** [comment]
@aekeus when you're back from holiday, can you help me with this one? 😄

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/35327081-9db31860-011e-11e8-8836-eb0c6cfc837b.png)
