### ISSUE TITLE
loading/progress indicator for wallet recovery

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11790]
### Description
Several users have mentioned that after entering or importing their BAT wallet recovery keys, it doesn't appear as though anything is happening on the UI. They have requested some kind of loading or progress indicator to let the user know something is happening. If a progress indicator isn't possible, maybe some kind of transition overlay (spinning circle?) to let the user know something is going on in the background.

### Steps to Reproduce

  1. Have backup words for a BAT wallet.
  2. Create a new profile and enable payments.
  3. Recover your wallet.

**Actual result:**
Sometimes wallet recovery takes up to 10 minutes, during this time there is no visual indication in the UI that anything is happening.

**Expected result:**
Some kind of visual notifier that a wallet recovery is being attempted.

**Reproduces how often:**
unknown. sometimes wallets recover fast, so this isn't an issue. other times it takes up to 10 minutes.

### Brave Version
BAT Mercury enabled versions (0.19.48, 0.19.70, etc)

**Reproducible on current live release:**
yes

**Comment by bsclifton** [comment]
Is this server related (ex: see https://github.com/brave/browser-laptop/issues/11590)?

**Comment by bsclifton** [comment]
Would adding a "Please wait a few minutes" be fine?

cc: @alexwykoff @bradleyrichter

**Comment by alexwykoff** [comment]
We're currently investigating a similar problem on the publisher side.  $0.00 is distressing so it would make sense to obfuscate the amount until we know for sure it is $0.00 😸

**Comment by srirambv** [comment]
Blocked on  #14014

**Comment by kjozwiak** [comment]
Unfortunately this still doesn't resolve the issue 100%. Sometimes you'll still notice the $0.00 value appear before the real amount is displayed via the modal. Sometimes the transition is instant and sometimes the transition takes a few seconds. I'm guessing this depends on the latency of your network and the ledger server.

**Comment by kjozwiak** [comment]
Moving this out as it still needs some more improvements. As mentioned above, we're still displaying `$0.00` at times when recovering. However, this has improved the experience by letting the user know that we're actually doing a recovery rather than just displaying `$0.00` for a longer period of time.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87

**Comment by kjozwiak** [comment]
Great work BTW, this looks and behaves so much better. Huge improvement IMO 👍
