### ISSUE TITLE
about:blank on URL bar of a tab opened with control key

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11796]
### Test plan
See https://github.com/brave/browser-laptop/pull/12388

### Description

The URL bar of a new tab opened by clicking a link pressing <kbd>Control</kbd> key is filled with `about:blank`.

### Steps to Reproduce

  1. Open https://github.com/brave/browser-laptop/issues
  2. Open a link with <kbd>Control</kbd> key
  3. Select the tab 

**Actual result:**

The URL bar is filled with `about:blank`. Hitting <kbd>Escape</kbd> displays the correct URL.

**Expected result:**

It should display the correct URL.

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

No.

**Comment by bsclifton** [comment]
+1 from @riastradh-brave
