### ISSUE TITLE
Fails to install on Ubuntu

### ISSUE THREAD

**Issue by sgehrman** [brave/browser-laptop#11794]
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/brave_0.19.80-1_amd64.deb (--unpack):
 cannot copy extracted data for './usr/lib/brave/brave' to '/usr/lib/brave/brave.dpkg-new': unexpected end of file or stream
Errors were encountered while processing:
 /var/cache/apt/archives/brave_0.19.80-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by luixxiul** [comment]
Hi, would you mind sharing the steps to reproduce the issue?

**Comment by sgehrman** [comment]
I followed the instructions on your site. For Linux.

**Comment by bsclifton** [comment]
@sgehrman did you make sure to run with sudo?

Linux instructions for reference:
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-artful-zesty-yakkety-xenial-and-trusty-amd64
