### ISSUE TITLE
display visual indication of trackpad gesture to "Go back"

### ISSUE THREAD

**Issue by rothos** [brave/browser-laptop#11792]
### Description

The trackpad two-finger gesture to "Go back" to the previous page has caused me some grief. In Brave, if I am on a page that scrolls horizontally, and I scroll to the right and then back to the left, I find that sometimes I swipe too far and end up loading the previous webpage I was on (specific description below). This is a frustrating behavior.

Part of the problem is that there is no visual indication of swiping forward/back like there is in e.g. Google Chrome:

![chrome_back](https://user-images.githubusercontent.com/913747/32417359-5110738e-c250-11e7-9f83-308579682c45.jpg)

I am on a MacBook Air; not sure if that matters.

### Steps to Reproduce

Here is an example of unwanted behavior:

  1. Begin a two-finger scroll to the right (i.e. to view content out of sight on to right of the screen)
  2. Without lifting fingers, scroll back to the left to the original location
  3. But scroll a little too far to the left before releasing fingers
  4. For me, this causes a "Go back"

### Proposal

  1. There should be a visual indication of swiping to "Go back" and "Go forward", and the indication should show when the threshold is reached.
  2. Swipe gestures to "Go back" (and "Go forward") should only activate if the same swipe gesture hasn't activated scrolling. (In other words, the horizontal scroll location of the page should have to be at the appropriate endpoint in order to swipe to "Go back" or "Go forward".)

### Brave Version

**about:brave info:** 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 15.5.0 
OS Architecture: x64

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by darkdh** [comment]
https://github.com/brave/browser-laptop/pull/9617
we will have visual indicator in 0.20.x

**Comment by rothos** [comment]
Ah, I see that this issue was already raised more than once — in the future I'll remember to look at closed issues as well as open ones when searching for duplicates.

**Comment by luixxiul** [comment]
@rothos you are always welcome to https://community.brave.com as well :-)
