### ISSUE TITLE
Cannot build or start. Electron not found, cannot install it

### ISSUE THREAD

**Issue by gargsms** [brave/browser-laptop#1179]
I am trying to run `npm run build-package` or `npm start` but it fails with this error
```
> brave@0.8.2 build-package /home/gargsms/Documents/gitRepos/browser-laptop
> node ./tools/buildPackage.js

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './node_modules/electron-prebuilt/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/gargsms/Documents/gitRepos/browser-laptop/tools/lib/versionInfo.js:3:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-package"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! brave@0.8.2 build-package: `node ./tools/buildPackage.js`
npm ERR! Exit status 1
```

I am using `node@5.9.0` and `node-gyp@3.2.1` as suggested in the README. I tried doing `npm install -g electron` but still there is no `$ electron` found. It shows up in `npm ls -g | grep electron` as `electron@0.4.1`

I am using Ubuntu 14.04.2LTS x86_64

**Comment by gargsms** [comment]
I downgraded my Node installation to 5.5.0, still the same issue. Cannot build.
I tried using `electron-prebuilt` from npm, which made some progress but gave an error that the app is not a valid electron app.
I have no clue how to debug this. Wiki also has no steps.

**Comment by bbondy** [comment]
Did you `npm install` ? 
You'll also want to start fresh as we use our own fork of electron.

**Comment by gargsms** [comment]
I did `npm install`
Just to make sure I am not doing something wrong, I cloned the repository twice and did npm install repeatedly.

@bbondy Can you tell me how do I get it to work with the required electron fork?

**Comment by bbondy** [comment]
It complains about a missing file here `./node_modules/electron-prebuilt/package.json`
Try doing this:
```
rm -Rf ~/.electron
npm install
```

If that still doesn't work then I'm guessing there is some error in the npm install log that can give more information.  The README should be all that you need to do.

**Comment by gargsms** [comment]
@bbondy Turns out I keep on getting different errors every time I try to do `npm install`.

This is the tail of npm-debug.log

```
231948 info lifecycle electron-chromedriver@0.36.0~install: electron-chromedriver@0.36.0
231949 verbose lifecycle electron-chromedriver@0.36.0~install: unsafe-perm in lifecycle true
231950 verbose lifecycle electron-chromedriver@0.36.0~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/browser-laptop/node_modules/electron-chromedriver/node_modules/.bin:/tmp/browser-laptop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/java/jdk1.8.0_74/bin:/usr/local/java/jdk1.8.0_74/jre/bin
231951 verbose lifecycle electron-chromedriver@0.36.0~install: CWD: /tmp/browser-laptop/node_modules/electron-chromedriver
231952 silly lifecycle electron-chromedriver@0.36.0~install: Args: [ '-c', 'node ./download-chromedriver.js' ]
231953 silly lifecycle electron-chromedriver@0.36.0~install: Returned: code: 1  signal: null
231954 info lifecycle electron-chromedriver@0.36.0~install: Failed to exec install script
231955 verbose unlock done using /home/XXXXXXX/.npm/_locks/staging-893cdc616788fb14.lock for /tmp/browser-laptop/node_modules/.staging
231956 silly rollbackFailedOptional Starting
231957 silly rollbackFailedOptional Finishing
231958 silly runTopLevelLifecycles Starting
231959 silly runTopLevelLifecycles Finishing
231960 silly install printInstalled
231961 verbose stack Error: electron-chromedriver@0.36.0 install: `node ./download-chromedriver.js`
231961 verbose stack Exit status 1
231961 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
231961 verbose stack     at emitTwo (events.js:100:13)
231961 verbose stack     at EventEmitter.emit (events.js:185:7)
231961 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
231961 verbose stack     at emitTwo (events.js:100:13)
231961 verbose stack     at ChildProcess.emit (events.js:185:7)
231961 verbose stack     at maybeClose (internal/child_process.js:821:16)
231961 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
231962 verbose pkgid electron-chromedriver@0.36.0
231963 verbose cwd /tmp/browser-laptop
231964 error Linux 3.13.0-83-generic
231965 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
231966 error node v5.5.0
231967 error npm  v3.3.12
231968 error code ELIFECYCLE
231969 error electron-chromedriver@0.36.0 install: `node ./download-chromedriver.js`
231969 error Exit status 1
231970 error Failed at the electron-chromedriver@0.36.0 install script 'node ./download-chromedriver.js'.
231970 error Make sure you have the latest version of node.js and npm installed.
231970 error If you do, this is most likely a problem with the electron-chromedriver package,
231970 error not with npm itself.
231970 error Tell the author that this fails on your system:
231970 error     node ./download-chromedriver.js
231970 error You can get their info via:
231970 error     npm owner ls electron-chromedriver
231970 error There is likely additional logging output above.
231971 verbose exit [ 1, true ]
```

**Comment by bbondy** [comment]
It seems like something is wrong with your node install. I don't think this is anything specific Brave can fix on our side.  These packages install fine for others.  You might want to completely uninstall node and npm and cache files for node and see if that helps.

**Comment by gargsms** [comment]
It seems like there was indeed some problem with my node installation.
I purged my old node installation and installed node@5.5.x again. Build succeeded. :smile: I can do `npm run watch` and it works perfectly. 
`npm run build-package` however, fails (or succeeds, I can't detcide because there is a `done` at the end) with a 404 for [https://github.com/atom/electron/releases/download/v0.37.3/brave-v0.37.3-linux-x64.zip] which is indeed not present. I can't see the built files either because there is no dist folder created.
In case of `npm start` I am getting #820 for me. I am on Linux, so I don't exactly know what is supposed to be in the path.txt file

**Comment by bbondy** [comment]
shouldn't be using this path at all: `https://github.com/atom/electron/releases/download/`
maybe you're not using the right electron-prebuilt.
Maybe something was changed while you were debugging the previous problem.
I'd suggest just cloning new and doing an npm instal then doing it.

**Comment by bbondy** [comment]
Turns out there was an actual problem relating to env mismatches for the last problem of downloading from `electron-chromedriver`.  It's fixed now though.  Closing this.
