### ISSUE TITLE
It's hard to select text because window drags

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#118]
URL bar should not allow window dragging.
I think this is a bug in electron when using a BrowserWindow with option  'title-bar-style': 'hidden-inset'.

**Comment by skeep** [comment]
Just realised that it is possible to select text but it's just that the selection area is too small. So whenever the `I` cursor comes it's possible to select text in the URL bar.

**Comment by luixxiul** [comment]
Was fixed?

**Comment by bbondy** [comment]
Yes, thanks for helping triage 👍
