### ISSUE TITLE
Forward and Back Buttons do not Highlight when hovered 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11807]
### Description
Reported from community 
>Forward and Back Buttons do not Highlight when hovered 

### Steps to Reproduce

  1. Open a tab, visit different sites to add history
  2. Mouse over back button doesn't highlight, click the back button goes back to previous page
  3. Mouse over forward button doesn't highlight, click the forward button goes back to next page

**Actual result:**

Forward and Back Buttons do not Highlight when hovered 

**Expected result:**
![history_butons](https://user-images.githubusercontent.com/17010094/32454141-3d233b9c-c316-11e7-9d0a-f3e5e9777e11.gif)

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

Brave	0.19.80
rev	7d07299
Muon	4.5.13
libchromiumcontent	62.0.3202.75
V8	6.2.414.36
Node.js	7.9.0
Update Channel	Release
OS Platform	Microsoft Windows
OS Release	10.0.15063
OS Architecture	x64

**Reproducible on current live release:**

Yes

### Additional Information

https://community.brave.com/t/forward-and-back-buttons-do-not-highlight-when-hovered-over-v19-80-windows/10318

**Comment by cezaraugusto** [comment]
`-webkit-app-region: drag;` cancels mouse events and hover including even w/ property declared. In the top-level window drag:

```css
.navbarCaptionButtonContainer.allowDragging {
    -webkit-app-region: drag;
}
```

**Comment by cezaraugusto** [comment]
also several other selectors sharing the same property

**Comment by petemill** [comment]
@cezaraugusto looks like if you set `-webkit-app-region: no-drag` on a container (even the immediate parent) then it restores mouse events. Setting  `-webkit-app-region: no-drag` directly on the `<button />` does not work though, so looks like just have to move that to parent.

**Comment by petemill** [comment]
@cezaraugusto ...or maybe that doesn't work either and sometimes the inspector resets state with that property....

**Comment by cezaraugusto** [comment]
ya `-webkit-app-region` is super restrictive. The case is worst on Windows. FYI conflict w/ `:hover` is a known bug but archived unfortunately https://bugs.chromium.org/p/chromium/issues/detail?id=411217

Tweaking the devtools fixes momentarily but applying the same fix in code doesn't. Seems to me that `no-drag`  must be set async (either before or after), given in devtools tweaking the property fixes the issue. 

I'm not on this right now but maybe @luixxiul who fixed several cases of this has some insight.

**Comment by cezaraugusto** [comment]
I'm wondering if the selector order has some effect on this. Maybe no need to javascript just change selectors or applying inline styles.

**Comment by fizzyfrosty** [comment]
Wanted to point out that this also exists in macOS, v0.19.80.

**Comment by bsclifton** [comment]
Not a regression- this has been happening for a while

**Comment by bsclifton** [comment]
this has since been fixed 😄
