### ISSUE TITLE
Selecting "Close" on pinned tabs creates a copy of the tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11805]
### Description

This is a follow-up to https://github.com/brave/browser-laptop/issues/4063.

Selecting "Close" on pinned tabs creates a copy of the tab.

![bug](https://user-images.githubusercontent.com/3362943/32437934-2fea207e-c32c-11e7-994d-fbcb0134d040.gif)

### Steps to Reproduce

  1. Open any page in a new tab (Open https://twitter.com for example)
  2. Pin it
  3. Close it

**Actual result:**

The copy of the tab is created.

**Expected result:**

The pinned tab should be closed

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@luixxiul in the recording above, you are picking "Clone", not "Close"

**Comment by luixxiul** [comment]
Yes, my bad 😅
