### ISSUE TITLE
Stop recreating shortcut on my desktop after every update

### ISSUE THREAD

**Issue by Tarabass** [brave/browser-laptop#1181]
Every time Brave has an update the shortcut to Brave returns on my desktop. Maybe Brave should check, not with clean install though, that if the shortcut to Brave doesn't exist it should not be created?

I like to keep my Windows desktop nice and clean.

**Comment by echosa** [comment]
Agreed. Having the desktop shortcut recreate itself every time is quite annoying. It's certainly not the most pressing of issues, but it will be greatly appreciated when fixed.

**Comment by bbondy** [comment]
https://github.com/mongodb-js/electron-squirrel-startup/blob/master/index.js#L21

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/blob/master/app/windowsInit.js#L40

**Comment by aekeus** [comment]
Issue seems to be static value sent to function that controls the shortcut building:

https://github.com/Squirrel/Squirrel.Windows/blob/ee32fb469fc1ace0af6aef7edc389e27b8c063bb/src/Update/Program.cs#L464

**Comment by aekeus** [comment]
Issue created in Squirrel.Windows

https://github.com/Squirrel/Squirrel.Windows/issues/831

**Comment by aekeus** [comment]
This is only testable via an auto-update on Windows. Will need to defer testing until binary up on updater dyno.

**Comment by aekeus** [comment]
Re-opened for more testing

**Comment by aekeus** [comment]
Testing is going to be quite complex. We need to make sure that the following all work correctly:

a) New installations should have a shortcut created on the desktop pointing to the most recent version
b) Updates with a shortcut on the desktop should modify the shortcut to point to the new version
c) Updates without a shortcut on the desktop should not recreate the shortcut

In the c) scenario you should see a line like the following in the SquirrelSetup.log file

`2016-09-23 16:03:41> ApplyReleasesImpl: Wanted to update shortcut C:\Users\Aubrey\Desktop\Brave.lnk but it appears user deleted it`

**Comment by aekeus** [comment]
Testing steps for a)

  Install Brave on either an exiting or new installation

Ensure:

  Shortcut on desktop is created and has line like `C:\Users\Aubrey\AppData\Local\brave\app-0.12.2` in the Start In: field

**Comment by aekeus** [comment]
Testing steps b)

1. Install Brave 
2. Copy `c:\users\[username]\AppData\Local\Brave\app-0.12.2` to `c:\users\[username]\AppData\Local\Brave\app-0.12.1`
3. Edit shortcut on desktop and change Start In: to point to app-0.12.1 [press Ok to close]
4. In `c:\users\[username]\AppData\Local\Brave` run .\app-0.12.2\Brave.exe --squirrel-updated

Ensure

Shortcut on desktop is modified and has line like C:\Users\Aubrey\AppData\Local\brave\app-0.12.2 in the Start In: field

**Comment by aekeus** [comment]
Testing steps for c)

1. Install Brave
2. Delete desktop Brave shortcut
3. In `c:\users\[username]\AppData\Local\Brave` run `.\app-0.12.2\Brave.exe --squirrel-updated`

Ensure

Desktop icon is NOT recreated and the following line appears in SquirrelSetup.log

`2016-09-23 16:03:41> ApplyReleasesImpl: Wanted to update shortcut C:\Users\Aubrey\Desktop\Brave.lnk but it appears user deleted it`

**Comment by aekeus** [comment]
Bonus testing step

  1. run `.\app-0.12.2\Brave.exe --squirrel-install`

Ensure

  Desktop icon is created and points to the correct version

**Comment by bbondy** [comment]
Marking as closed since it is done but please note the label to manually test this in depth @alexwykoff

**Comment by srirambv** [comment]
>Testing steps for c)
Install Brave
Delete desktop Brave shortcut
In c:\users\[username]\AppData\Local\Brave run .\app-0.12.2\Brave.exe --squirrel-updated

Deleting the existing shortcut and then manually running the setup to upgrade Brave to next version still creates a shortcut on Desktop. (Windows 10 x64)

**Comment by alexwykoff** [comment]
To clarify on part C, per @aekeus :
A shortcut SHOULD be created on a clean install.
A shortcut SHOULD NOT be created on an auto-update.

**Comment by aekeus** [comment]
@alexwykoff your comment is correct. Deleted shortcuts should not be re-created on an auto-update.

Deleted shortcuts will be created if the main installer is run, regardless of installation status.

**Comment by aekeus** [comment]
<img width="586" alt="screen shot 2016-09-29 at 8 47 32 pm" src="https://cloud.githubusercontent.com/assets/210240/18977168/0b4e1920-8686-11e6-83a3-50aaf1f01319.png">

Updates the shortcut as expected.

**Comment by aekeus** [comment]
This seems to be the issue:

https://github.com/brave/browser-laptop/blob/master/app/windowsInit.js#L48

The call is intercepted and forwarded to BraveDefaults.exe instead of being handled directly by Brave.exe

**Comment by bbondy** [comment]
talked to you about the above, just tacking here in case anyone else is following along.  BraveDefaults.exe is just the nsis script which sets defaults so it shouldn't cause something to be wrong with the icon like the start in folder not being updated.  It is also called from the uninstaller to do cleanup.

**Comment by bbondy** [comment]
would like to get this in after preview-1 @aekeus
