### ISSUE TITLE
Empty autofill context menu for password autofill

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11828]
### Description

The context menu is displayed with null item after the saved password is cleared on `about:passwords`.

![bug](https://user-images.githubusercontent.com/3362943/32516154-b89f7062-c445-11e7-9ec6-f01d45ab3dcd.gif)

![clipboard01](https://user-images.githubusercontent.com/3362943/32516076-6e08d44e-c445-11e7-8b7b-36e479bfb281.png)

![clipboard01](https://user-images.githubusercontent.com/3362943/32516060-5fdc56ac-c445-11e7-99ee-2c5e9c8d8cb3.png)

I noticed this one while checking if https://github.com/brave/browser-laptop/issues/3541 has been fixed on 0.20.5.

### Steps to Reproduce

  1. Clear your browser's profile
  2. Open the browser
  1. Visit https://trac.torproject.org/projects/tor/login
  2. Log in
  3. Save your password
  3. Visit about:password
  4. Delete the saved value
  4. Reload to https://trac.torproject.org/projects/tor/login
  5. Attempt to log in

**Actual result:**

The empty contextMenu appears as above.

**Expected result:**

It should not be displayed.

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

Not for me. CC @srirambv for confirmation.

**Comment by bsclifton** [comment]
Confirmed this is not an issue
