### ISSUE TITLE
Bookmarks not showing in search bar

### ISSUE THREAD

**Issue by butlermatt** [brave/browser-laptop#11823]
### Description
Similar to the description of #9039, bookmarks are not showing in the search bar when history is enabled. However the difference is that I'm not referring to the section, but the bookmark itself is not in the search bar when typing part of the address. Similar history components are but not the actual bookmarked page.

### Steps to Reproduce
  1. Under preferences, all except "Autocomplete as you type" are enabled for search bar options.
  2. Bookmark this page http://weather.gc.ca/city/pages/ns-31_metric_e.html
  3. Browse around that link including the various radar or even other forecasts for other cities, provinces.
  4. Close the tab and open a new one and begin typing weather
  5. After several days, I can't determine exactly when, along with other browsing, the link from step 2 no longer shows up in the history section when typing "weather" in the search bar, even though it's a bookmarked site.

**Actual result:**
After a few days, the bookmarked item never shows up in suggestions/history when typing the address in the address bar. See screenshots.
Link is the last one in the bookmark list.
<img width="1301" alt="screen shot 2017-11-07 at 9 26 02 am" src="https://user-images.githubusercontent.com/1148886/32495891-e0672746-c39d-11e7-9cf3-8527b055c2b0.png">

The following is my suggestions when I start typing "weather" in the search bar
<img width="889" alt="screen shot 2017-11-07 at 9 27 57 am" src="https://user-images.githubusercontent.com/1148886/32495954-07aae41e-c39e-11e7-9cdd-8e416cfc777c.png">

**Expected result:**
Bookmarks show _always_ show up in the search suggestions. Even if not the first history element, they should certainly always be displayed in the list and not superseded by history that I may have only visited once in the past.

**Reproduces how often:**
I have removed the bookmark, re-added and cleared history. Initially it started working as expected, but as I browsed and accessed other pages on their, as well as outside of the weather page, within a couple of days I was no longer seeing my bookmark within the suggestions list.

### Brave Version

**about:brave info:**
 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
Live release being the download from the website? Yes. This version is from the brave.com download and from automatic updates.

**Comment by luixxiul** [comment]
The same issue as https://github.com/brave/browser-laptop/issues/11802#issuecomment-342109366 ?

> We have two lists history and bookmarks. We merge this two lists into one under History section in autocomplete. Why you still have this item in the list is because is bookmarked.

**Comment by butlermatt** [comment]
No. This is almost the opposite of this issue. I _expect_ that because I have it bookmarked that the site would appear in the "History" list. However in this case, it is not showing up in the list at all. Others from the history are, but the book mark does **not** appear
