### ISSUE TITLE
Profile in use by another Chromium process -- ERROR:process_singleton_posix.cc(323)

### ISSUE THREAD

**Issue by aumars** [brave/browser-laptop#11829]
### Description
Brave fails to initialise at all.

### Steps to Reproduce

  1. Install Brave using official instructions in Fedora
  2. Execute Brave in the terminal

**Actual result:**
```
Error: unrecognized flag --icu_case_mapping
Try --help for options
[7410:7410:1107/212703.629045:ERROR:process_singleton_posix.cc(323)] The profile appears to be in use by another Chromium process (2727) on another computer (localhost.localdomain). Chromium has locked the profile so that it doesn't get corrupted. If you are sure no other processes are using this profile, you can unlock the profile and relaunch Chromium.
```

**Reproduces how often:**
It just spontaneously happened today for no apparent reason. I tried restarting the computer and reinstalling Brave but nothing seems to work.

### Brave Version

**about:brave info:**
0.19.80-1

**Reproducible on current live release:**
Yes.

**Comment by bsclifton** [comment]
cc: @bridiver @darkdh

**Comment by insanerwayner** [comment]
This happened to me today. On Pop_OS!.

May be related to me changin my hostname on my machine. Will try reverting and update with results.

**Comment by insanerwayner** [comment]
That didn't work either.

**Comment by insanerwayner** [comment]
Actually it did. I misspelled the first time. Set it back to the name of the computer it was showing in the error string and it worked. Now the question is. How can I avoid this after changing my hostname?

**Comment by amorrisbpsd** [comment]
I was able to fix this by removing the SingletonLock file.

`rm /home/$USER/.config/brave/SingletonLock`

**Comment by bsclifton** [comment]
This usually happens when multiple instances of Brave are running (ex: if one got hung and is still running and then you open another).  Closing since there haven't been any updates
