### ISSUE TITLE
Where is the code block the youtube ads?

### ISSUE THREAD

**Issue by salamsoliman** [brave/browser-laptop#11826]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
Please have a look at this FAQ on our community 🦁 

https://community.brave.com/t/all-about-ad-blocking/10004

Thanks 😄
