### ISSUE TITLE
0.19.80 Windows close tab, doesn't close and tab width changes, restart and closes

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#11830]
### Description

![tab close and reopens](https://user-images.githubusercontent.com/16969914/32522494-a316b19e-c46b-11e7-9ed1-4e96684d6d4b.gif)

### Steps to Reproduce
Not sure how to consistently reproduce. Occurred after installing 0.19.80 with Brave 0.19.7 open with tabs set to open from where I left off before running the installation. 

**Actual result:**
Doesn't close, tab widths change.

**Expected result:**
Tabs close.

**Reproduces how often:**
Not sure.

### Brave Version

 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by bsclifton** [comment]
@jamesray1 have you experienced this recently? We've had some related fixes which may have fix this issue for you

I'll close for now, but please re-open if you still experience this (along with relevant details). Thanks! 😄
