### ISSUE TITLE
Linux cibuild script fails on Jenkins

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11831]
### Description
When doing builds (release channel, beta channel, etc), the Linux job is always failing

I believe the root cause was unintentionally introduced with https://github.com/brave/browser-laptop/pull/10274

The upload script is recursively searching for all matching binaries and finding the RPM under the `suse` folder.  

- A proper fix would choose a different name for the SUSE binary
- A work-around would be to exclude the `suse` folder in upload.py
- A quick work-around would be to delete the `suse` folder before starting the upload

### Steps to Reproduce

  1. Go to https://jenkins.brave.com/view/laptop%20builds%20(child%20jobs)/
  2. Pick the "browser-laptop-build-linux" type and queue a build (beta channel, 0.20.x branch)

**Actual result:**
It will eventually fail with an error like so:
```
{
  "documentation_url": "https://developer.github.com/v3",
  "message": "Validation Failed",
  "errors": [
    {
      "field": "name",
      "code": "already_exists",
      "resource": "ReleaseAsset"
    }
  ],
  "request_id": "924F:1690:30E530:34464A:5A015C2A"
}
```

**Expected result:**
the cibuild should not fail

**Reproduces how often:**
100%

**Comment by posix4e** [comment]
Whoops Ye do that

**Comment by bsclifton** [comment]
@posix4e it's all good 😄  Having the suse binary is awesome- I think the proper solution would be to choose a name that doesn't conflict.  Take a peek at https://github.com/brave/browser-laptop/pull/12397 and let me know what you think 😄 👍
