### ISSUE TITLE
Javascript error when saving a new password

### ISSUE THREAD

**Issue by cgcardona** [brave/browser-laptop#1183]
## Summary

When saving my password to Twitter.com I am getting a popup w/ a javascript error.

## Steps to reproduce

(Steps are also below as screenshots)

1. Sign in to Twitter.com
2. Agree to have brave browser save your password when prompted
3. 
  * EXPECTED BEHAVIOR: Password is saved
  * ACTUAL BEHAVIOR: Javascript error

From checking out the stack trace I think it's related to https://github.com/brave/browser-laptop/blob/master/js/lib/cryptoUtil.js#L81

<img width="346" alt="screen shot 2016-03-27 at 10 27 56 am" src="https://cloud.githubusercontent.com/assets/260614/14066768/aef08782-f407-11e5-94be-aa73be66058f.png">
<img width="526" alt="screen shot 2016-03-27 at 10 28 11 am" src="https://cloud.githubusercontent.com/assets/260614/14066775/ef1fe53c-f407-11e5-9b10-6362a48ef4fe.png">
<img width="417" alt="screen shot 2016-03-27 at 10 28 26 am" src="https://cloud.githubusercontent.com/assets/260614/14066767/aeefc658-f407-11e5-820b-95fcdc1d72ac.png">

**Comment by michaelhwan** [comment]
@cgcardona I can't re-create this error using my saved password when logging into Twitter. Have you upgraded to latest operating system?

I'm running OS X 10.11.4

**Comment by cgcardona** [comment]
@michaelhwan, no I'm running OS X 10.11.3. I'll update tomorrow and report back here w/ an update. Thanks!

**Comment by michaelhwan** [comment]
@cgcardona take a look at issue #1165 upgrading to latest OS X version probably won't solve your error. I'm wondering why I don't see errors...

**Comment by cgcardona** [comment]
@michaelhwan FWIW I'm using a 63 character password though I don't know if the length of the password is the source of the error as I'm unclear if `Invalid key length` refers to the password length.

**Comment by michaelhwan** [comment]
@cgcardona my password is less than 15 characters

**Comment by diracdeltas** [comment]
I am 90% sure this will be fixed by #1166 (next release).

**Comment by diracdeltas** [comment]
^ Invalid key length refers to the length of the master password used to encrypt passwords on disk, not the length of the password (which would be the ciphertext).

**Comment by cgcardona** [comment]
Thanks for weighing in @diracdeltas. I'm really loving brave browser so far and keep it open all the time. Keep up the great work. :alien:
