### ISSUE TITLE
Webview crashes by displaying this corrupted png file

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11848]
### Description

Webview crashes by displaying this corrupted png file.

https://discourse-cdn-sjc1.com/standard2/uploads/brave/original/2X/3/3157f3cdba9e256895c15b754cf0c3daefcdda91.png

### Steps to Reproduce

  1. Open the file https://discourse-cdn-sjc1.com/standard2/uploads/brave/original/2X/3/3157f3cdba9e256895c15b754cf0c3daefcdda91.png

**Actual result:**

Webview crashes.

**Expected result:**

It should not.

**Reproduces how often:**

For me consistently, on Windows and on Debian.

### Brave Version

**about:brave info:**

Windows: 

Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

Debian:

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

Yes.

### Additional Information

I think https://github.com/brave/browser-laptop/issues/11664 is duping to this one.

**Comment by bsclifton** [comment]
@luixxiul does this still reproduce? If not, let's close it up 😄  If so- we'll need to update the link above (it's a 404 now)

**Comment by luixxiul** [comment]
I have not seen the issue recently. I'm going to close the issue for now.
