### ISSUE TITLE
Pinning tabs takes 4-8 seconds and freezes the browser [Windows 10] [Desktop]

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11840]
When I go to pin a tab the browser completely freezes for a period of anywhere from 4 to 10 seconds meanwhile all other browsers I've tried don't have this issue? Why.

Running:
```
WIndows 10 on an SSD
FX 8350
8gb Ram
GTX 970
```

Brave about:
```
Name | Version
-- | --
Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.14393
OS Architecture | x64
```

**Comment by luixxiul** [comment]
that kind of the performance issue will be fixed after 0.20 is released. please hang tight.

**Comment by TheCNixon** [comment]
Thank you again! I'm just trying to report any issues I find incase no one else has yet.

**Comment by luixxiul** [comment]
Thanks 👍 Would you mind checking the beta build and see if the browser does freeze yet?

I think this has been fixed there already, so closing just for now. Please let us know if the issue still persists 😉
