### ISSUE TITLE
Bookmarked thumbnail on Dashboard should have a filled star icon

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11847]
### Description

Bookmarked thumbnail on Dashboard should have a filled star icon

### Steps to Reproduce

  1. Open a new tab (Dashboard)
  2. Click the star icon of a tile

**Actual result:**

The bookmark star icon on the tile is not filled.

**Expected result:**

The bookmark star icon on the tile should be filled

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

Yes.

**Comment by revelt** [comment]
I just checked, yeah, "star" buttons don't recognise the tile has been already bookmarked. It's a good one, @luixxiul thanks!
