### ISSUE TITLE
Update country name in autofill

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11843]
### Description
Update to official country name in autofill

**Actual result:**
Autofill doesn't show official country name

**Expected result:**
Should show official country name

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.80
-- | --
rev | 7d07299
Muon | 4.5.13

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Removing milestone; 0.20.x is already full.  With our somewhat new process, we should leave the issues without a milestone, so that the reviewer can choose where to land it 😄

**Comment by Jacalz** [comment]
Don’t think that this will be necessary

**Comment by bsclifton** [comment]
Closing as `wontfix` (see comments in https://github.com/brave/browser-laptop/pull/11844)
