### ISSUE TITLE
Wrong title (Youtube) [Windows 10]

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11846]
![image](https://user-images.githubusercontent.com/10780361/32539038-6d0dc6a0-c425-11e7-9849-c6a1b74b02b0.png)
When I go to a video, search and click another video, the title is still the original video watched on that tab.

Running:
```
WIndows 10 on an SSD
FX 8350
8gb Ram
GTX 970
```

Brave about:
```
Name | Version
-- | --
Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.14393
OS Architecture | x64
```

**Comment by luixxiul** [comment]
@TheCNixon There will be a bunch of fixes available around the tabs bar. When you find that kind of bugs, would you please try with the beta build at first to see if they are not fixed there already 😄 

The beta builds are available on https://github.com/brave/browser-laptop/releases 🦁 

If you could reproduce the bug there, please ping me. I'm going to close the issue for now 😉
