### ISSUE TITLE
Can't import bookmarks from Chrome or from Chrome bookmarks exported to html [Windows 10] [Desktop]

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11841]
I attempted 3 ways of importing my bookmarks from Chrome, first way was importing from chrome while closed (Brave froze), second way was from exported chrome html of my bookmarks (Brave froze), and third way was through Chrome import while it was open (Brave froze). And each time Brave froze I had to force close it from Task Manager.

Running:
```
WIndows 10 on an SSD
FX 8350
8gb Ram
GTX 970
```

Brave about:
```
Name | Version
-- | --
Brave | 0.19.80
rev | 7d07299
Muon | 4.5.13
libchromiumcontent | 62.0.3202.75
V8 | 6.2.414.36
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.14393
OS Architecture | x64
```

**Comment by luixxiul** [comment]
Closing for now, on the same reason as https://github.com/brave/browser-laptop/issues/11846#issuecomment-342750622

Let's reopen if this issue is still reproduced on 0.20 👍 Let me know 😃
