### ISSUE TITLE
No way to unmute tabs

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11849]
### Description

No way to unmute tabs. 

### Steps to Reproduce

  1. muted two tabs by right clicking
  2. clicking mute

**Actual result:**

there was no option to umute and if I clicked mute tab again it wouldn't unmute.

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.20.5 on Windows 10

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
@TheCNixon Thanks for the bug report. From next time, please use the default template to make it possible to troubleshoot 😄 Thanks! 👍

**Comment by hferreiro** [comment]
This is a duplicate of #10545.

**Comment by bsclifton** [comment]
Great catch, thanks @hferreiro ! 😄
