### ISSUE TITLE
APP_WINDOW_CLOSED action is never fired

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#11859]
### Description
When closing a window, this action is not called, therefore state / cache cleanup is not happening. I haven't personally invesitgated yet, so I don't know when in the window closing lifecycle it was supposed to be closed.

### Brave Version

**about:brave info:**
master (0.22.0)

**Comment by NejcZdovc** [comment]
This called was removed in this commit https://github.com/brave/browser-laptop/commit/22a1c33c1560a817034e11c56cd23fab8d4e8a4c#diff-5fdd9f55221fe32ba22dea6484d4135cL24

cc @bbondy

**Comment by bsclifton** [comment]
I've manually tested this and it also has an automated test 👍
