### ISSUE TITLE
Ledger Wallet Recovery dialog needs updating

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#11857]
The text and button arrangement should be updated to reflect that attached mockup:

![image](https://user-images.githubusercontent.com/13509546/37496448-c41ffe78-286f-11e8-86ed-c730fde39042.png)

**Comment by bradleyrichter** [comment]
@NejcZdovc The mockup above is valid but "Import recovery key" should be grey instead of orange.

**Comment by NejcZdovc** [comment]
@bradleyrichter thank you
