### ISSUE TITLE
Spell check fails on 0.19.82

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11858]
### Description
Spell check fails on 0.19.82

### Steps to Reproduce
  1. Clean install 0.19.82
  2. Open about:styles 
  3. Type `fead` in one of the text box
  4. May show red underline for misspelt word
  5. Click away from the input box 
  6. Click back inside the input box to focus, no more underline on misspelt word
  7. Type another wrong word, no more highlighting done for any misspelt word

**Actual result:**
Spell check fails on 0.19.82

**Expected result:**
Should show misspelt word and allow to correct it via context menu 

**Reproduces how often:**
Consisitent

### Brave Version

**about:brave info:**

Brave | 0.19.82
-- | --
rev | 4324d42
Muon | 4.5.15

**Reproducible on current live release:**
No

### Additional Information
reproded on mac by @LaurenWags

**Comment by darkdh** [comment]
`fead` seems not an invalid word. you can also try it on Chrome
You can use `feadd` which is definitely spelled wrong

**Comment by bsclifton** [comment]
I tried also and can confirm no issue.  @darkdh tried both macOS and Windows

@srirambv if you're still able to reproduce, can you try with:
`efdkodfo okdo sokdf oksdfdff`

For me, each of those 4 words highlights for me

**Comment by srirambv** [comment]
@bsclifton reproducible with your text on 0.19.86 clean profile as well 
![11858](https://user-images.githubusercontent.com/17010094/32592667-b6448e1a-c51c-11e7-8740-08c77a82552d.gif)

**Comment by srirambv** [comment]
`feadd` also results in same 
![11858-1](https://user-images.githubusercontent.com/17010094/32592773-2e007ebe-c51d-11e7-95b3-b31311911928.gif)

**Comment by bsclifton** [comment]
@srirambv what do your spell checking settings look look? Can you screen cap that? (ex: is spell check enabled? if so, what languages are selected)

**Comment by srirambv** [comment]
Default English(US). The screen record is on a clean profile
![11858-2](https://user-images.githubusercontent.com/17010094/32592963-e183a5e2-c51d-11e7-84ce-483fe6a05bfa.gif)

**Comment by srirambv** [comment]
Works on 0.19.87 👍
