### ISSUE TITLE
Running release build closes beta browser window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11856]
### Description
Running release build closes beta browser window

### Steps to Reproduce
  1. Install 0.19.80 and open the browser window
  2. Install 0.20.6 and keep the beta browser window 
  3. Run 0.19.82 setup, both the browser window closes 

**Actual result:**
Running release build closes beta browser window

**Expected result:**
Beta browser window should not be closed

**Reproduces how often:**
Consistent

### Brave Version

**about:brave info:**

Brave | 0.19.82
-- | --
rev | 4324d42
Muon | 4.5.15

Brave | 0.20.6
-- | --
V8 | 6.2.414.36
rev | 18f7d1e
Muon | 4.5.14

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment]
Still happens when installing 0.19.88, 0.20.7 window closes out.

**Comment by bsclifton** [comment]
This is resolved now 👍 I believe it was a problem before we had a proper Beta channel on Windows (something with @darkdh fixed 😄 )
