### ISSUE TITLE
Persist Certain 3rd Party Cookies

### ISSUE THREAD

**Issue by pantocrator27** [brave/browser-laptop#11866]
It appears that there are certain 3rd party website that govern opting out of digital advertisements such as:
* http://optout.aboutads.info/#!/
* http://optout.networkadvertising.org/#!/

Should there be a whitelist of these and maybe other 3rd party cookies that are persisted or accessible within Brave even when the user has explicitly opted out of 3rd party cookies?

**Comment by bsclifton** [comment]
cc: @diracdeltas
