### ISSUE TITLE
Make BAT matching promotion configurable

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11869]
This is a sub-task of https://github.com/brave/browser-laptop/issues/11100

## Description
The promotion should be able to be turned on or off (client side) via a single configuration value.  This config setting would be checked by other issues, such as https://github.com/brave/browser-laptop/issues/11867 and https://github.com/brave/browser-laptop/issues/11868

### When disabled
Promotional text will not be shown

### When enabled
We can either:
- make a call to the back end to see if the promotion is still in effect
OR
- show the promotion

**Comment by NejcZdovc** [comment]
@bsclifton I think that all configuration will be done in libraries/server and browser will just read data. This way we don't need to deploy new version to turn promotion on/off

cc @mrose17

**Comment by mrose17** [comment]
@NejcZdovc - that is my belief as well. it is all data-driven! i hope to have the repos updated by COB us/pacific!

**Comment by bsclifton** [comment]
@NejcZdovc totally agree- as long as the bat-client can handle offline scenarios (returning false for promotion enabled, for example)

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11874 - all info comes from server side
