### ISSUE TITLE
Show notification for BAT Matching - users with payments disabled

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11867]
This is a sub-task of https://github.com/brave/browser-laptop/issues/11100

### Description
This notification would be shown under the following conditions:
- promotion is enabled (see https://github.com/brave/browser-laptop/issues/11869)
- user has Brave Payments disabled
- user has not claimed tokens already
- user has payment notifications enabled (they didn't silence it yet)

We would prompt them to open the Preferences > Payments screen like so:
![image](https://user-images.githubusercontent.com/4733304/32591537-c44f27c6-c4dc-11e7-8678-9fdf9cfc482b.png)

Alert Bar Text:
“Hello! Ready to support your favorite sites? Brave will fill your wallet with tokens to get you started!

Button Left: “Maybe later”
Action: resets alert bar counter to 24 hours

Button Right: “I’m ready”
Action: Opens Brave Payments prefs panel.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11874

**Comment by srirambv** [comment]
@NejcZdovc @bradleyrichter Should `I'm Ready` button be secondary button or primary button as per the original mockup?
![image](https://user-images.githubusercontent.com/17010094/33379365-d9a280d0-d50f-11e7-9197-d42cb17c7654.png)

**Comment by NejcZdovc** [comment]
it should be primary and this was broken on b-l level, so it's ok for now
