### ISSUE TITLE
Nested bookmark folders go off screen on about:bookmarks

### ISSUE THREAD

**Issue by gauthierhaas** [brave/browser-laptop#1187]
Using the bookmark bar, nested folders appear next to each other, each child to the right of its parent.

If too many childs are added, this makes a chain that goes out of the computer's screen, and it is thus impossible to access to the latest child using the bookmark bar.

See the pictures attached for a clearer understanding of the issue. Additionally, as see on the first picture, on the bookmarks manager page the nested folders are not rendered correctly.

https://i.imgur.com/n8UHe0I.png
https://i.imgur.com/vOHmgoM.png

**Comment by luixxiul** [comment]
@bbondy +1

**Comment by bsclifton** [comment]
Bookmarks manager recently updated with https://github.com/brave/browser-laptop/pull/4658 (which was followed up by https://github.com/brave/browser-laptop/pull/4690).  This is still an open issue

**Comment by bsclifton** [comment]
And updated #4690 to include a fix for this :smile:

**Comment by alexwykoff** [comment]
In the second image we see that the bookmarks toolbar has an issue with nested folders.
Based on the latest build, it would appear that it has not been fixed.
<img width="1131" alt="screen shot 2016-10-13 at 7 01 37 pm" src="https://cloud.githubusercontent.com/assets/1434040/19346887/526d1034-9178-11e6-882c-c93df85c15d1.png">

**Comment by bsclifton** [comment]
Created https://github.com/brave/browser-laptop/issues/4745 to track the bookmarks toolbar issue :smile:

**Comment by luixxiul** [comment]
pinging @bsclifton for triaging the milestone.
