### ISSUE TITLE
Browser whiped of data

### ISSUE THREAD

**Issue by TheCNixon** [brave/browser-laptop#11875]
### Description
Lost all open tabs, passwords, bookmarks, auto fill, settings, etc. on Brave Beta.

### Steps to Reproduce
  1. Open browser, open tabs and sign into websites
  2. Sign out of Windows 10 account
  3. Sign back in

**Actual result:**
Browser completely clean.

**Expected result:**
I'd have my data.

**Reproduces how often:**
Every time, don't understand why as I have closed the browser on numerous times this week without restarting or signing out with no issue until I sign out.

### Brave Version

```
Name | Version
-- | --
Brave | 0.20.6
V8 | 6.2.414.36
rev | 18f7d1e
Muon | 4.5.14
OS Release | 10.0.14393
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.75
```

**Reproducible on current live release:**
No

### Additional Information
N/A

**Comment by bsclifton** [comment]
@TheCNixon this is a weird experience, but it's expected

We recently created a real `Beta` channel.  Your data is still there! 😄  You can install the latest `Release Channel` version of Brave and you'll see everything there

If you want to stay on Beta, you can move your data by doing the following:
- Close all instances of Brave
- Press Window + R, type `%appdata%` and hit enter
- Look for the `brave` folder
- Rename as `brave-beta`
- Relaunch the Beta version of Brave (0.20.6)
