### ISSUE TITLE
Updating on Linux Mint shows error message

### ISSUE THREAD

**Issue by durbanpoison** [brave/browser-laptop#11872]
### Description

Linux Mint Update Manager app is throwing me errors when I try to update Brave.

### Steps to Reproduce

  1. Download Brave with Linux Mint 18.2 following instructions on the brave.com website  
  2. Try to update using the Update Manager  
  3. See error message  

**Actual result:**

Error message:  
```
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
```

**Expected result:**

No error message, update software as normal.

**Reproduces how often:**

100% of the time

### Brave Version

0.19.80

**Reproducible on current live release:**

Yes

**Comment by TheCNixon** [comment]
Have you tried installing the update through terminal to see if it still persists outside of the update manager?

**Comment by durbanpoison** [comment]
Yes, this is the message Terminal returns after entering `sudo apt-get update`  

```
Ign:1 http://packages.linuxmint.com sonya InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Hit:3 http://archive.canonical.com/ubuntu xenial InRelease                     
Hit:4 http://packages.linuxmint.com sonya Release                              
Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease                        
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]       
Get:7 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Hit:9 https://updates.signal.org/desktop/apt xenial InRelease
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [382 kB]
Hit:11 https://s3-us-west-2.amazonaws.com/brave-apt xenial InRelease
Get:12 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [353 kB]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [169 kB]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [178 kB]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [153 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [94.4 kB]
Fetched 1,636 kB in 2s (555 kB/s)                                  
Reading package lists... Done
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/brave-xenial.list:1 and /etc/apt/sources.list.d/brave-xenial.list:2

```

**Comment by durbanpoison** [comment]
@NumDeP I'm not sure what you mean by "figure out an efficient way to download updates as they're pushed". The Update Manager app in Linux Mint is how I manage all of my software updates. FWIW I am still getting these errors.

**Comment by jamesray1** [comment]
I have a similar issue. https://gist.github.com/jamesray1/2ccff8ece9534a253755fedab3bd513a

**Comment by Souravgoswami** [comment]
Similar issue here!

Also there's one more issue with the GTK buttons. I can't use them. If I use system borders, I can close, minimize, maximize as normal, but if I use GTK buttons without system default borders, as I said, I can't close, minimize or maximize brave browser.

This is because it is not configured properly. I also use Google chrome. I don't have the GTK button issue with Chrome.

However, in this comment, I want the apt update problem to get resolved! This is happening because there are multiple sources of Chrome (and Brave is based on Chrome). Note that I have Opera too... Opera is based on Chrome, but as expected it doesn't reproduce any warnings on the terminal...

**Comment by bsclifton** [comment]
This version of Brave is deprecated; I'd encourage folks experiencing this to try the new version of Brave available at https://brave.com/download

If the problem is still happening when following the new install instructions, let's open an issue in the new repo here:
https://github.com/brave/brave-browser
