### ISSUE TITLE
Shields menu cover entire browser view when clicked on view count

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11878]
## Test plan

https://github.com/brave/browser-laptop/pull/11880#issue-272623676

----

### Description
Shields menu cover entire browser view when clicked on view count

### Steps to Reproduce
  1. Build from #11727 
  2. Visit YouTube and view couple of videos
  3. Click on shields, expand the adblock count to see details
  4. Shields menu covers 90% of the browser window. Doesn't happen on when shields is set to compact view

**Actual result:**
Normal Shields menu 
![image](https://user-images.githubusercontent.com/17010094/32611799-7a16ec84-c55e-11e7-81f7-45eb10c018ff.png)
Compact Shields menu
![image](https://user-images.githubusercontent.com/17010094/32611787-7098b6ce-c55e-11e7-84fa-ceea3c1479f6.png)

**Expected result:**
Shields should not cover the browser window 

**Reproduces how often:**
Consistently on that PR. was able to see it on two different profile

### Brave Version

**about:brave info:**

Brave | 0.22.0
-- | --
V8 | 6.2.414.36
rev | 145f454
Muon | 4.5.14

**Reproducible on current live release:**
No

### Additional Information
cc: @luixxiul @bradleyrichter

**Comment by srirambv** [comment]
Happens on 0.20.x and 0.21.x as well. Marking as triage backlog

**Comment by luixxiul** [comment]
Regression by https://github.com/brave/browser-laptop/pull/10489
