### ISSUE TITLE
Payments screen should have a "Claim free tokens" button

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11871]
This is a sub-task of https://github.com/brave/browser-laptop/issues/11100

### Description
This button would be shown under the following conditions:
- promotion is enabled (see https://github.com/brave/browser-laptop/issues/11869)
- user has Brave Payments enabled
- user has not claimed tokens already

The Preferences > Payments screen would display a `Claim my free tokens` button, like so:
![image](https://user-images.githubusercontent.com/4733304/32591676-86d9a528-c4dd-11e7-878a-6cb59c609823.png)

When clicked, the server side call would be made to claim the tokens

**Comment by NejcZdovc** [comment]
@bradleyrichter do we display text bellow add founds as well?

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11874

**Comment by srirambv** [comment]
Should `Claim My Tokens` be primary button as original mockup or secondary button as seen on 0.19.99
![image](https://user-images.githubusercontent.com/17010094/33380492-30f0583c-d513-11e7-9a1b-5a1405a9a817.png)

**Comment by bradleyrichter** [comment]
It should be primary and orange.

**Comment by NejcZdovc** [comment]
@srirambv this will not be fixed in this release, because it's not a ledger problem, but global notification component. It's like this for couple of releases.

**Comment by srirambv** [comment]
Thanks for the confirmation 
cc: @kjozwiak @LaurenWags
