### ISSUE TITLE
Text on Payments screen should be retrieved from server side

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11870]
This is a sub-task of https://github.com/brave/browser-laptop/issues/11100

### Description
The text shown in Preferences > Payments should be retrieved from the server side (via BAT client).  If the client can't be reached OR if the user has no internet connection, fallback text should be shown instead. 

Here's a screenshot showing some example text:
![image](https://user-images.githubusercontent.com/4733304/32591537-c44f27c6-c4dc-11e7-8678-9fdf9cfc482b.png)

> Brave has created a simple way for you to contribute to the sites you use most
> 
> Now, for a limited time, Brave will fund your wallet with tokens to get you started!
> 
> To start using Brave Payments and accept your tokens, simply flip the switch at the top of this window and then choose "Claim my free tokens"
> 
> The rest is easy

**Comment by NejcZdovc** [comment]
@bradleyrichter what will be alternative message?

**Comment by bradleyrichter** [comment]
@NejcZdovc Here is the screen showing updated text for the case when UGP is not active:

![image](https://user-images.githubusercontent.com/13509546/32640613-6b57077c-c57e-11e7-9e31-d84ecb0ab48e.png)

**Comment by NejcZdovc** [comment]
@bradleyrichter thank you

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11874
