### ISSUE TITLE
switching tabs via keyboard shortcuts doesn't switch tab page

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11884]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bbondy** [comment]
0.19.x: 24d4fda7c628443175ce9ae962585d9ebccc3c44
0.20.x: 493c5761b97c815c1b5d78556532a58a44f31861
0.21.x: 5591e975a82c8a0b2a753b36cf48f4d53faa97b8
master: 230ccbcb6b0c669ec1d170243381aa65ecb1a78d
