### ISSUE TITLE
restrict origins that brave app proccess can connect to

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#11889]
we have CSPs that limit what the Brave main renderer process and what Brave about: pages can connect to, but there is currently nothing that limits the main app process. we should find a way to do this so that PRs like https://github.com/brave/browser-laptop/pull/11727 don't add arbitrary domain connections. also we should never connect to unencrypted origins in the main app process.

**Comment by diracdeltas** [comment]
cc @jumde since https://github.com/brave/browser-laptop/issues/12190 and this issue both require figuring out what origins Brave is actually connecting to

**Comment by flamsmark** [comment]
Closed in favor of brave/brave-browser#163 .
