### ISSUE TITLE
Bookmark can't move to a subfolder

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#11893]
### Description
Create a folder in the bookmarks bar, then add a sub-folder to that folder. Then add a bookmark to the bookmarks bar, and click and drag it to the empty sub-folder. It doesn't work.

If you add a sub-folder to that sub-folder, you are then able to click and drag the bookmark. This bug appears to be related to #10157, not being able to click and drag a bookmark to the other bookmarks folder in the bookmark manager. Generally, you can't click and drag a bookmark to an empty bookmark folder. You have to add something to the empty folder via starring a page to said empty folder, or by adding a folder to the empty folder. There is no issue dragging bookmarks or folders to a non-empty folder.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**
 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-17-generic 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by NejcZdovc** [comment]
can't reproduce this on 0.20 so appears to be fixed

**Comment by kjozwiak** [comment]
@jamesray1 if you have the time, could you download the latest `0.20.x` BETA [1] and see if you can reproduce this anymore?

[1] https://github.com/brave/browser-laptop/releases/

**Comment by jamesray1** [comment]
Works now!

 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.13.0-36-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by kjozwiak** [comment]
Awesome, thanks for checking @jamesray1!
