### ISSUE TITLE
Chromium 63 Upgrade

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11890]
Chromium 63.0.3239.84

**Comment by bsclifton** [comment]
Last updated to Chromium 63.0.3239.84 (see https://github.com/brave/browser-laptop/issues/12206#issuecomment-350589728)

**Comment by kjozwiak** [comment]
Clearing tags and ensuring that `0.19.121` is using `63.0.3239.108` as per https://github.com/brave/browser-laptop/issues/12206#issuecomment-352831875

**Comment by bsclifton** [comment]
@kjozwiak that is the correct version 😄   Updated with https://github.com/brave/browser-laptop/commit/d3b15a6e96a0b1b4286779de02b9181ae2a63fab
