### ISSUE TITLE
anti webgl fingerprint Doesn't Work Anymore

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#11896]
Brave v0.19.88 x86
w7 x64

![untitled](https://user-images.githubusercontent.com/19530450/32663721-d332de9c-c5e3-11e7-9aa0-2293617bc508.jpg)

**Comment by bsclifton** [comment]
@gameb0y are you not getting `0C21A6FA2A9BD79DFF6E128FE55094B4` as the hash?

Looks like you had last reported this with https://github.com/brave/browser-laptop/issues/8448, which was fixed with https://github.com/brave/browser-laptop/pull/8781/files

cc: @diracdeltas @snyderp

**Comment by diracdeltas** [comment]
on mac latest release i also get 0C21A6FA2A9BD79DFF6E128FE55094B4

**Comment by diracdeltas** [comment]
to clarify, we don't block the hash but it should be the same for all users regardless of their setup
