### ISSUE TITLE
Add "trimming" to long URLs in Shields Panel blocked URLs

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#11899]
This layout problem can be solved and simplified by trimming the extra path info past the first slash.

The link itself should remain linked and allow for rt-click menu access to "copy link".

![image](https://user-images.githubusercontent.com/13509546/32680543-01683410-c620-11e7-9b1c-66f5b3199f36.png)

Actual URL:

https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1036322744/?value=0&label=AgenCNqg-QMQuI-U7gM&guid=ON&script=0&url=creditcards.chase.com%2Faudiences%2F62334757

Displayed URL:
https://googleads.g.doubleclick.net/

**Comment by luixxiul** [comment]
this can be solved with https://github.com/brave/browser-laptop/pull/11880

**Comment by luixxiul** [comment]
By fixing in the above way you would avoid having duplicate domains in the list.

**Comment by bradleyrichter** [comment]
I don't mind duplicate domains if the full URL is available by hover and rt-click to copy.
