### ISSUE TITLE
[Windows, Dual Monitors] Entering and exiting full screen causes window to be too large

### ISSUE THREAD

**Issue by Sirius902** [brave/browser-laptop#11891]
Whenever I enter full screen mode and then exit, the window bleeds over to my other monitor instead of staying on the monitor I have the browser.

Steps to reproduce:
  1. Maximize the window
  2. Enter full screen mode
  3. Exit full screen mode

I would expect the browser to be the same size after entering and exiting full screen and stay contained in one monitor.

This has happened every time.

 
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Comment by bsclifton** [comment]
This should be fixed with our [Developer channel release](https://brave.com/download-dev) if you wanted to confirm 😄
