### ISSUE TITLE
Unable to Create Bookmarks

### ISSUE THREAD

**Issue by DevinWiley** [brave/browser-laptop#11897]
### Description
Attempting to create a bookmark either from the star on the URL bar or within the about:bookmarks does not work.
Clicking on the star on the URL bar will cause the bookmarks toolbar to appear if it was hidden, but star will not light up and bookmark bar will remain unpopulated.
Attempting to import bookmarks will display a "Your data has been imported to Brave successfully" but no bookmarks are created. Additionally the bookmark toolbar will appear if it was hidden similar to above.

### Steps to Reproduce

  1. Attempt to bookmark an arbitrary website.

**Actual result:**
Bookmark toolbar appears if hidden.
Bookmark toolbar will remain empty and a favorite/bookmark is not created.

**Expected result:**
Star next to URL bar to be filled in if visiting a bookmarked site.
Bookmark is created which can be used to navigate to site.

**Reproduces how often:**
100% of attempts to create bookmarks.

### Brave Version

**about:brave info:**
 
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by luixxiul** [comment]
I suspect it has been fixed on the 0.20 beta builds. Is it OK to close this issue until 0.20 is released so we could re-visit the issue again? 😄

**Comment by DevinWiley** [comment]
It appears to be fixed in the beta build.
Thank you.

**Comment by luixxiul** [comment]
Thanks for testing!
