### ISSUE TITLE
Verified mark needs to be displayed for the verified publishers

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#11904]
### Description

Verified mark indicates publishers who successfully verified their domain and needs to be displayed next to the domain in the Brave Payments table.

### Steps to Reproduce

  1. Open Settings and go to Payments.
  2. View site list in the table
  3.

**Actual result:**

Mark is missing for the ones that are verified.

**Expected result:**
Verified mark in front of the site favicon

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.19.88

**Reproducible on current live release:**

### Additional Information

![screen shot 2017-11-10 at 4 36 26 pm](https://user-images.githubusercontent.com/4369856/32684334-7379ab6c-c637-11e7-9e2e-617d64b7bfcc.png)

**Comment by NejcZdovc** [comment]
@jenn-rhim on which version you are? Please paste data from `about:brave`

**Comment by jenn-rhim** [comment]
0.19.88

**Comment by bsclifton** [comment]
@mrose17 if this is present in our current release, should this block our next release?

**Comment by NejcZdovc** [comment]
It's working for me on clean profile on the latest master.

![image](https://user-images.githubusercontent.com/9574457/32687490-c6c5b528-c6bd-11e7-8332-4ad146924164.png)


Will check out 0.19.88 as well

**Comment by mrose17** [comment]
@bsclifton & @NejcZdovc - my thinking is that this isn't a blocker.

also, based on  my read of https://github.com/brave-intl/bat-publisher/commit/dc8f2b65c9fd8e7c41a9bd412b32c3dc908c0723#comments ... i believe the security review is complete for now.  

let us begin the merge, thanks!

**Comment by jenn-rhim** [comment]
I agree this shouldn't be a blocker, but something we should fix soon if it is actually reoccurring bug.

**Comment by bsclifton** [comment]
@NejcZdovc weird- it's understandable that master works, since everybody is developing using that.  This checkmark was recently added back in with our last release (when the new integration was done).  That issue passed QA (which included this exact use-case), so I'm surprised to see this happen

**Comment by NejcZdovc** [comment]
tried it on 0.19 version and it's working for me, @jenn-rhim can you please try it again. Steps that I did

1) clean profile on 0.19 latest
2) enable payments
3) go to new tab and load ddg site
4) wait on this site for 15s
5) go back to ledger and see that ddg is added (no verified icon yet, we need to trigger some action to show it)
6) go back to ddg and check that verified icon is on the left side of the url bar
7) go back to ledger and you should see verified icon there as well

**Comment by jenn-rhim** [comment]
@NejcZdovc i see more of them now than when the issue was created. but i need a way to cross check that all verified pubs are in fact having the mark.

**Comment by NejcZdovc** [comment]
@jenn-rhim I think that @alexwykoff can help you with that

**Comment by NejcZdovc** [comment]
closing this one as it seems that it's working ok, didn't receive any new reports about it.
