### ISSUE TITLE
Replace "Submit Feedback" with other words such as "Help Center"

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11918]
### Description

Replace `Submit Feedback` inside "Help" with other words, such as `Help Center` to make it clear that on https://community.brave.com/ users are expected to help each other. `Submit Feedback` sounds unidirectional.

### Brave Version

**about:brave info:**

 
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**

Yes.

**Comment by Rahmeen14** [comment]
Hi! I am completely new to open source and would like to work on this issue as my first, in case nobody is currently working on it
Thank you!

**Comment by srirambv** [comment]
@Rahmeen14 please go ahead and submit a PR.

**Comment by NejcZdovc** [comment]
@Rahmeen14 if you need any help or directions just let me know. Welcome in the open source community 😃

**Comment by Rahmeen14** [comment]
Thank you so much. I'll just get to work, thanks! :)

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.8 06c657b
•	Muon 6.1.5
•	libchromiumcontent 66.0.3359.181
