### ISSUE TITLE
Google directory is created in Application Support

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#11917]
### Description
Whenever Brave is opened, a directory named `Google` is created in the Application Support directory. The URL for the created directory is `~/Library/Application Support/Google`. Since Brave is not associated with Google, Brave should not be creating a directory called Google. I suspect that Chromium may be causing this. I have only tested on macOS.

### Steps to Reproduce
(for macOS)
  1. If Brave is running, quit it.
  2. Open your Application Support directory at `~/Library/Application Support`.
  3. If there is a directory named Google in the Application Support directory, delete or rename it.
  4. Open Brave.

**Actual result:**
A directory named Google appears in the Application Support directory.

**Expected result:**
No directory except `brave` should be created by Brave in the Application Support directory.

**Reproduces how often:**
Always.

### Brave Version

**about:brave info:**

Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.2.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes, 0.19.88.

### Additional Information
None.

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by darkdh** [comment]
the reason we create the folder `NativeMessagingHosts` under Google is here
https://github.com/brave/muon/commit/eda99ede604a3e6d6fb9f843aa81c23617ce0922
