### ISSUE TITLE
System "password keychain" dialogue pops-up on each keystroke

### ISSUE THREAD

**Issue by bnvk** [brave/browser-laptop#1191]
Using current `master` of Brave on Debian Jessie triggers the "password keychain" pop-up on each keystroke even after `cancel` has been clicked cc: @diracdeltas

**Comment by diracdeltas** [comment]
btw this was on debian

**Comment by bnvk** [comment]
daaaaaang `throttleKeytar` is so :metal: :guitar: :musical_keyboard: :grinning: thnx @diracdeltas
