### ISSUE TITLE
Make "URL / Title" event have more graceful transitions

### ISSUE THREAD

**Issue by bnvk** [brave/browser-laptop#1192]
I find the current transition from `URL` to `Title` to be slightly jaring, it happens a bit too quickly and harshly. I'd wager adding a 25 ms delay to the transition, as well as maybe a 50 - 100 ms "fade" would make Brave feel a bit more solid and polished!

This also "feels" in the territory of the the "hover on tab for preview" feature, which I disabled and found to be highly jaring. Might be worth doing some quantitaitve user testing to choose ideal default? :smile:

**Comment by stewhouston** [comment]
About 60% of the time tab labels are not switching to the page's title, just defaulting to the page URL. Not sure if this is a known bug, or only happening for me. Running Brave on Windows 8.1 x64.

**Comment by bradleyrichter** [comment]
@bnvk  I agree. A transition would add some polish. Thanks for the suggestion.

**Comment by cezaraugusto** [comment]
@bradleyrichter is this enchancement open for implementtion? If so, Is there a standard for effects/transitions on Brave?
