### ISSUE TITLE
Download bar cannot be closed with an active download

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11923]
### Test plan
See https://github.com/brave/browser-laptop/pull/13040

### Description
Download bar cannot be closed with an active download

### Steps to Reproduce

  1. Install/upgrade to 0.19.88
  2. Download a huge file
  3. Close the download bar while the download is active
  4. Download bar closes and becomes active again

**Actual result:**
Download bar cannot be closed with an active download

**Expected result:**
Should close the download bar even if there is an active download

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.88
-- | --
rev | c29eca6
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
cc: @LaurenWags to verify on mac

**Comment by LaurenWags** [comment]
Reproduced on MacOS. Removed Win label.

**Comment by bsclifton** [comment]
+1 from @eljuno via https://github.com/brave/browser-laptop/issues/13232

**Comment by btlechowski** [comment]
No longer blocked as fix for #14398 is in 0.23.1.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.17 - `bc754eb`
* Muon - `7.1.2`
* libchromiumcontent - `67.0.3396.87`
