### ISSUE TITLE
Consider using new Chromium 63 feature: font-variant-east-asian

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11934]
### Description

On cr63 the `font-variant-east-asian` property will be enabled.

https://www.chromestatus.com/features/4965040604053504
https://drafts.csswg.org/css-fonts-3/#font-variant-east-asian-prop

We'll be able to set `font-variant-east-asian: traditional` for zh-TW (Taiwan) and `font-variant-east-asian: simplified` for zh-CN, setting `proportional-width` as well.

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@luixxiul do you have more information about this?  Is this issue a feature request for us to add this new attribute on existing pages? Or is this something which should already be present and needs to be tested with Chromium 63

**Comment by luixxiul** [comment]
We'll need to investigate how the properties can be applied and see if there would be use cases.

**Comment by bsclifton** [comment]
@luixxiul OK great- title updated 😄 👍
