### ISSUE TITLE
adjust 'Allow contributions to videos' toggle text display

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11937]
### Description
Adjust display of 'Allow contributions to videos' toggle text.

### Steps to Reproduce

  1. Enable payments/have payments enabled.
  2. Click on Advanced Settings.
  3. 

**Actual result:**
'Allow contributions to videos' toggle text goes to the next line, but looks different than the toggle text (which also goes to the next line) above it for 'Allow contributions to non-verified sites'.
![screen shot 2017-11-13 at 3 30 47 pm](https://user-images.githubusercontent.com/28145373/32747923-73190566-c888-11e7-88f9-844cc12e7e98.png)

**Expected result:**
Toggle text should be stylized the same when it goes to the next line.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave | 0.19.91
rev | a308504
Muon | 4.5.15

**Reproducible on current live release:**
No

**Comment by luixxiul** [comment]
It'll be fixed on https://github.com/brave/browser-laptop/pull/10482.

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/blob/a308504326c004da103375e5e3da9508851fc457/app/renderer/components/preferences/payment/advancedSettings.js#L73-L91

`className={css(styles.listItem)}` should be added to the bottom SettingCheckbox.

**Comment by bbondy** [comment]
Can you PR it @luixxiul ?

**Comment by bbondy** [comment]
can you PR just a small change for this @luixxiul ?

**Comment by luixxiul** [comment]
OK, will do :-)

**Comment by NejcZdovc** [comment]
fixed with #11974
