### ISSUE TITLE
Folders from other channels need to be disregarded when building package

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11939]
### Description

While on the same machine, if you build a package for `beta` channel and then one for `nightly`, the `nightly` package will be significantly larger.  This is because the `build-package` step will pack the `beta` content into the nightly's ASAR file

A fix for this issue was introduced with https://github.com/brave/browser-laptop/pull/10552, but it has a side-effect of causing this issue:
https://github.com/brave/browser-laptop/issues/11799

In the 0.19.x branch, the ignorePaths was removed with https://github.com/brave/browser-laptop/commit/41dc7cfd822b5b12f95328f2dac863458ac25124

### Steps to Reproduce

  1. Be on 0.20.x or newer
  2. Cherry-pick https://github.com/brave/browser-laptop/commit/41dc7cfd822b5b12f95328f2dac863458ac25124
  3. `CHANNEL=beta npm run build-package`
  4. `CHANNEL=beta npm run build-installer`
  5. `CHANNEL=nightly npm run build-package`
  6. Note the size of the `resources/app.asar` (should be ~266 megs, not > 1 GB)

### Brave Version
0.20.x and newer (when packaging)

**Reproducible on current live release:**
No

### Additional Information
This should be fixable by either hardcoding the names or creating a stronger regex match (which matches only the builds, not libraries like `brave-crypto`)

**Comment by luixxiul** [comment]
![clipboard01](https://user-images.githubusercontent.com/3362943/33259125-34c31316-d39f-11e7-912b-9d49216ffaab.png)

The installers size looks normal.
