### ISSUE TITLE
not getting USD rates

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11931]
### Description
Not seeing USD rates on Payments page. With LEDGER_VERBOSE=true it looks like rates aren't being received.

### Steps to Reproduce

  1. Clean install of 0.19.89
  2. Run with LEDGER_VERBOSE=true
  3. Enable Payments

**Actual result:**
No USD values displayed
![screen shot 2017-11-13 at 10 30 06 am](https://user-images.githubusercontent.com/28145373/32733563-a11d20ee-c85d-11e7-8b70-6e86d6523314.png)

**Expected result:**
USD values should be visible

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave | 0.19.89
rev | 20badac
Muon | 4.5.15

**Reproducible on current live release:**
Yes (0.19.88) (Confirmed by @srirambv on Windows and me on MacOS)

### Additional Information
https://gist.github.com/LaurenWags/c4ebcfa5ce2dbaa71a6dc7db742d7745#file-rates-txt-L149
Unable to check on current release for Win/Ubuntu due to https://github.com/brave/browser-laptop/issues/11929

**Comment by bsclifton** [comment]
Moving to Hotfix 6.  @mrose17 can you give an update on this? Is the issue on the server side?

**Comment by mrose17** [comment]
@bsclifton - it is server-side and should be fixed. apparently, the bittrex websocket stream went sideways yesterday. i have updated the code plus added a flatline detector.

**Comment by kjozwiak** [comment]
Moving this back into https://github.com/brave/browser-laptop/milestone/87

**Comment by kjozwiak** [comment]
Closing as @mrose17 fixed the issue as mentioned above.

**Comment by kjozwiak** [comment]
Looks like the USD rates are now being displayed in the wallet... Thanks for the fix @mrose17!!

I went through the following test cases:

* ensured that the correct USD rates are being displayed for each BAT entry using [CoinGecko](https://www.coingecko.com/en/price_charts/basic-attention-token/usd)
* created a new wallet using both `0.19.88` & `0.19.91`, ensured USD rates are being displayed
* upgraded from `0.18.36` -> `0.19.88` & `0.19.91`, ensured USD rates are being displayed
* disabled/enabled the wallet several times and ensured that the USD rates are still appearing

**Comment by darkdh** [comment]
<img width="240" alt="screen shot 2017-11-15 at 12 21 37 pm" src="https://user-images.githubusercontent.com/11330831/32858212-9cffadbc-c9ff-11e7-8d2f-7dea07c15ca7.png">
but the rate isn't correct for me

**Comment by kjozwiak** [comment]
@darkdh are you seeing this every single time? What version of Brave are you using? I just checked under Ubuntu/macOS and I pulled the correct rates when creating a new wallet via `0.19.93`.

Did you see the above when creating a net wallet? Upgrade from an older version?

**Comment by darkdh** [comment]
Brave: 0.19.93 
rev: 25085d0b5a0a6cf8a740cac8b246ebf1a97146f7 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

I've always seen this balance since I migrated from BTC to BAT
Please notice my BAT amount is huge and my migration from BTC to BAT is manual and painful(I have to use fresh profile to recover BTC wallet first and then make it migrated)
@evq can vouch this for me
