### ISSUE TITLE
brave ads are not being displayed when enabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11948]
### Description

Brave ads are not being displayed when `Show Brave Ads` is selected under  `Ad Control` via the Brave Shield.

### Steps to Reproduce

  1. launch brave and load https://slashdot.org/
  2. click on the "Brave" shield and select `Show Brave Ads` under "Ad Control"
  3. https://slashdot.org/ will refresh and you'll notice that there isn't any Brave ads being displayed

**Actual result:**

There's no Brave ads being displayed, example:

<img width="1435" alt="bad" src="https://user-images.githubusercontent.com/2602313/32765865-5e692450-c8da-11e7-9d4a-03c98a18296d.png">

**Expected result:**

Brave ads should be displayed, example:

<img width="1559" alt="good" src="https://user-images.githubusercontent.com/2602313/32765879-6d8a06f2-c8da-11e7-98ce-5530958ea979.png">

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

* `v0.19.70` rev: d4b94c6215bb130250fe5245787a5884dc9b51fe - PASSED (brave ads loaded)
* `v0.19.80` rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 - FAILED (not loading brave ads)
* `v0.19.88` rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 - FAILED (not loading brave ads) - **_Current Release_**
* `v0.19.91` rev: a308504326c004da103375e5e3da9508851fc457 - FAILED (not loading brave ads)

**Reproducible on current live release:**

Yes, see above.. Reproducible under `v0.19.88`

### Additional Information

Platforms Used/Checked:

* macOS 10.12.6 x64 - Reproduced
* Ubuntu 16.04.3 LTS x64 - Reproduced 

@srirambv can you check and see if this is reproducible on Win as well?

**Comment by srirambv** [comment]
Reproduced on Windows as well. Per @bbondy this is expected as it was a placeholder and disabled for perf reasons.

**Comment by luixxiul** [comment]
IMO the option should be grayed out or hidden until we start serving the ads, as currently "Show Brave Ads" is no different than "Block ads".
