### ISSUE TITLE
[Extension Request] Surfingkeys

### ISSUE THREAD

**Issue by duranivan** [brave/browser-laptop#11949]
Please add extension Surfingkeys ([here](https://github.com/brookhong/Surfingkeys)). It is not working following @jonathansampson [tutorial](https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d).

Thanks in advance!

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/9396. Let's talk about the issue there 😄
