### ISSUE TITLE
Add link on about:preferences#payments panel to Brave Payments Contributors Terms of Service

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#11942]
![1](https://user-images.githubusercontent.com/400552/32757679-8e48f6e0-c895-11e7-93b0-0d12c7591462.png)

as noted in the mockup above, there should be a link on about:preferences#payments labelled "Terms of Service" that opens a new tab at https://basicattentiontoken.org/contributor-terms-of-service/

**New mock for ledger table**

![1](https://user-images.githubusercontent.com/4733304/32812194-138e66ac-c961-11e7-8373-b454f7994c77.png)

**Comment by bsclifton** [comment]
Moving back to Hotfix 6; if we can get a PR for this today, reviewer can decide on whether or not to pull into Hotfix 5 (since we need a release candidate today)

**Comment by cezaraugusto** [comment]
Opened #11957 moving back to hotfix 5

**Comment by srirambv** [comment]
Not as per mockup spec. Terms of service link is shown below the table. 
![image](https://user-images.githubusercontent.com/17010094/32826302-cc76238e-c9df-11e7-9da6-cdbd43523150.png)

**Comment by NejcZdovc** [comment]
@srirambv mock was updated and you can find it here https://github.com/brave/browser-laptop/pull/11957#issuecomment-344446018. Will update this issue as well

**Comment by kjozwiak** [comment]
Currently, the ToS only appears in the wallet when there's entries within the the ledger table... However, the ToS are not being displayed in the following cases:

* initial wallet creation
* empty ledger table

After a quick discussion with @mrose17, the ToS should be visible at all times.

STR:

* install brave and create a wallet (no ToS being displayed)
* visit a website and popular the ledger table (ToS visible)
* remove the entry from the table (no ToS being displayed)

![tosexample](https://user-images.githubusercontent.com/2602313/32844645-f7edac7e-c9f0-11e7-80e9-79a3577113f8.gif)

**Comment by luixxiul** [comment]
If TOS should be displayed even before enabling the payments, the link should be displayed just above the closing div tag.

https://github.com/brave/browser-laptop/blob/83e78cb8591b28554af8ef46d86f7dfc291a6183/app/renderer/components/preferences/paymentsTab.js#L287-L297

**Comment by NejcZdovc** [comment]
@kjozwiak I think that need to display it only when wallet is enabled. Can you please confirm this?

**Comment by mrose17** [comment]
@NejcZdovc - it's needs to be there even when the wallet is enabled. it is entirely reasonable for someone to want to look at the terms of service before opting in. we need to give them that opportunity.

of course, "nobody reads those things" (or so i'm told), but it still needs to be available to allow people to make a fully informed decision, if they so chose.

that's one reason why the publishers.basicattentiontoken.org has a link to the publishers' terms of service on the home page, even if you haven't logged in...
