### ISSUE TITLE
Removing and adding ledger entry for video doesn't show correct source/publisher name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11953]
### Steps to Reproduce
  1. Install 0.19.91
  2. Visit some YT channels, and watch videos
  3. Make sure the channels are listed in the ledger table
  4. Clear all entries in the ledger table including YT publisher and all other sites listed in the table
  5. Clear the deleted entries listed under shields
  6. Visit tvfplay.com and play any of the embedded YT video 
  7. Switch to payments, shows channel name but source is shown as undefined

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/32779057-3da95fd2-c934-11e7-8e0c-6dfb1e38a29c.png)

**Expected result:**
Should show the source name

**Reproduces how often:**
Not sure

### Brave Version

**about:brave info:**

Brave | 0.19.91
-- | --
rev | a308504
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
NA

**Comment by srirambv** [comment]
Some channels show up as below and when clicked doesn't load the page. After few mins this changes to channel name on undefined as posted in the original issue
![image](https://user-images.githubusercontent.com/17010094/32783214-ddcd28aa-c942-11e7-81e2-8663e892f777.png)

**Comment by LaurenWags** [comment]
not quite the same issue, but I ran into this display issue below:
![screen shot 2017-11-14 at 5 39 37 pm](https://user-images.githubusercontent.com/28145373/32808968-11162674-c963-11e7-9511-bd24dcd4b7b7.png)

**Comment by mrose17** [comment]
@NejcZdovc - i think the issue is that when `getPublisherData` is called, the structure doesn't have all the expected fields,  e.g., `providerName` (hence, `"on undefined"`)

**Comment by NejcZdovc** [comment]
@mrose17 yeah, it's strange because we only add media publisher when we get all informations about it. Need to reproduce it first
