### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11952]
https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

Requested here: https://community.brave.com/t/the-list-of-the-requested-extensions/10278

**Comment by bsclifton** [comment]
Closing as we will get extension support with [Brave Core](https://github.com/brave/brave-browser) and folks will be able to use the Chrome Web Store (or our own extension store)
