### ISSUE TITLE
time spent not always being added when viewing live YT video's

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11956]
### Description
Live video doesn't show the time spent on YT

#### Original steps
  1. Install 0.19.91, enable payments
  2. Visit YouTube and launch a live video, play it for a while
  3.  Switch to payments, no time spent shown but lists other values
#### Updated steps per https://github.com/brave/browser-laptop/issues/11956#issuecomment-344667208
  1. Clean install 0.19.92, enable payments
  2. Change advance settings to 5 visits
  3. Continue watching the channel for other videos
  4. Change settings back to default 1 visit, time spent is not shown

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/32793552-2e259268-c95e-11e7-9bde-0ec6b33dba2f.png)

**Expected result:**
Should be able to record the time the live video is watched

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.91
-- | --
rev | a308504
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
N/A

### Additional Information

**Comment by bsclifton** [comment]
Removing milestone- @davidtemkin this would require investigation and code changes. Let's chat about when this should be done 😄

**Comment by darkdh** [comment]
shows for me on Mac 
<img width="774" alt="screen shot 2017-11-14 at 10 38 00 am" src="https://user-images.githubusercontent.com/11330831/32797887-f7a523ce-c927-11e7-8a68-fabe789dd6a3.png">

**Comment by bsclifton** [comment]
@darkdh wow, nice! ❤️

**Comment by srirambv** [comment]
Seeing the time spent on a new profile 
![image](https://user-images.githubusercontent.com/17010094/32798647-42941648-c96d-11e7-9af3-2848914370fd.png)

**Comment by LaurenWags** [comment]
Seeing the same as @srirambv mentioned here: https://github.com/brave/browser-laptop/issues/11956#issuecomment-344360190 for both new profile and profile upgrade.

**Comment by kjozwiak** [comment]
Seems like there's an edge case somewhere where sometimes the time won't appear... However, it looks like it's generally working right now... I checked on Ubuntu, and  the times are appearing as expected....

We'll leave this issue in the "Prioritization" milestone and see if we can get more detailed STR.

**Comment by srirambv** [comment]
Found good STR for this
Clean install 0.19.92, enable payments
Change advance settings to 5 visits
Continue watching the channel for other videos
Change settings back to default 1 visit, time spent is not shown

![image](https://user-images.githubusercontent.com/17010094/32850592-7e86dee8-ca2a-11e7-8911-a7d092a75f6b.png)

**Comment by NejcZdovc** [comment]
@srirambv can you please try this one with the latest beta?

**Comment by srirambv** [comment]
Looks fixed for now. Followed steps mentioned in https://github.com/brave/browser-laptop/issues/11956#issuecomment-344667208. Tried on existing beta profile and on a clean profile and both the times time spent was shown correctly. 

Closing for now. Can reopen it if it happens again.
