### ISSUE TITLE
After exit, runs in background

### ISSUE THREAD

**Issue by Edjamacator** [brave/browser-laptop#1196]
After exiting cleanly on several occasions, I've noticed that there are three instances of Brave still running for an interdetermined time. I usually just force stop them to close. This happens on a Win 7 64 bit system.

**Comment by frenchbread** [comment]
Same issue on Mac OSX 10.11.3
Brave version: 0.8.2

**Comment by luixxiul** [comment]
Fixed with #1540, closing. If you still encounter the error please leave comments, thanks.
