### ISSUE TITLE
video not appearing in ledger table after modifying settings and setting back to defaults

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11972]
### Description
After enabling payments if you modify Adv Settings to be different than defaults and then immediately change back to default (8s/1visit), videos do not display in ledger table.

### Steps to Reproduce

  1. Clean profile on 0.19.92.
  2. Enable payments.
  3. Change default settings (I used 5s/5visits)
  4. Close Advanced Settings.
  5. Reopen Advanced Settings, change back to default (8s/1visit)
  6. Go to YT and watch any video.
  7. Even after viewing entire video it will not be displayed in ledger table.

**Actual result:**
Video is not added to ledger table (but youtube.com is)

**Expected result:**
Video (and youtube.com) should be added in ledger table.

**Reproduces how often:**
Easy - reproduced by @srirambv on Win and @kjozwiak on Ubuntu.

### Brave Version

**about:brave info:**
Brave | 0.19.92
rev | af635fb
Muon | 4.5.15

**Reproducible on current live release:**
no (n/a)

**Comment by NejcZdovc** [comment]
@LaurenWags can you check if #11977 fixes this one as well. It should because it's the same root cause

**Comment by LaurenWags** [comment]
looks good with https://github.com/brave/browser-laptop/pull/11977 - can you check too @srirambv @kjozwiak ?

**Comment by srirambv** [comment]
Verified  #11977  works fine on Windows
