### ISSUE TITLE
Option to turn off smooth scrolling.

### ISSUE THREAD

**Issue by GrimReaper34** [brave/browser-laptop#1197]
Are there any plans to implement an option to turn off smooth scrolling? I know the Android version has it but there's no such option on Windows, that's the only thing that keeps me from using Brave exclusively, I don't like smooth scrolling in any of the mainstream browsers because it makes me nauseated. Cheers!

**Comment by nickfletcher** [comment]
+1

**Comment by capouch** [comment]
Same for me.

**Comment by luixxiul** [comment]
You can disable smooth scrolling (requires browser restart) on about:preferences#advanced

**Comment by capouch** [comment]
@luixxiul Why does the option say "ENABLE smooth scrolling???"

**Comment by luixxiul** [comment]
if you have a suggestion let us know ("Use" smooth scrolling?)

**Comment by capouch** [comment]
My point is that you can't turn it on and off--it does smooth scrolling no matter which way you put that setting!

**Comment by luixxiul** [comment]
On which OS? I cannot reproduce the issue on Windows 10

**Comment by capouch** [comment]
Linux.  I must not be the only one, as per the above.  Smooth scrolling no matter what the setting.  I use Electron for other things and have never figured out how to get it to stop that behavior.

**Comment by luixxiul** [comment]
I'm not sure about the above ("there's no such option on Windows"). Which distro do you use? there could be a compatibility issue between Electron and the distro you use.

**Comment by capouch** [comment]
Slackware.  I have others on VMs, though.  I will play around but smooth scrolling really annoys me and I would love to have a way to shut it off.

**Comment by capouch** [comment]
Success!  brave --disable-smooth-scrolling &

Found the answer on the Electron list.

**Comment by luixxiul** [comment]
cc: @bridiver

**Comment by bridiver** [comment]
#2795 should have been marked as a dup of this
