### ISSUE TITLE
videos not displaying in ledger table properly after modifying Advanced Settings

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#11973]
### Description
Videos are not displayed properly (or sometimes at all) in ledger table after modifying advanced settings.

### Steps to Reproduce

  1. Clean profile on 0.19.92
  2. Enable payments
  3. Modify Advanced Settings to be something like 5s/5visits.
  4. Visit at least 5 videos from the same channel for at least minimum amount of time.
  

**Actual result:**
I found that the channel was displayed in the table, but was missing 'Time Spent' as below. @srirambv found that his channel was never displayed in the ledger table at all.
![screen shot 2017-11-15 at 11 16 00 am](https://user-images.githubusercontent.com/28145373/32847709-c7605054-c9f8-11e7-8d63-fa2119e3e390.png)

**Expected result:**
Once video meets advanced settings it should be displayed in the table.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.92
rev | af635fb
Muon | 4.5.15

**Reproducible on current live release:**
no (n/a)

**Comment by srirambv** [comment]
STR on Windows 
1. clean install 0.19.92
2. Change advance settings to 5sec/5visit
3. Open any YT channel and play 5 videos for 1 min each
4. No YT/channel details added to ledger

**Comment by LaurenWags** [comment]
Additional STR: 
1. Clean profile on 0.19.92
2. Enable payments
3. Just modify one of the settings (i.e. 1minute/1visit)
4. Watch 1+ minutes of a video, it was not added to the ledger table.

**Comment by kjozwiak** [comment]
While going through this ticket, I ran into another case where the entry in the ledger table wasn't being displayed correctly.. The time spent was miscalculated my a large margin...

STR:

* launch `0.19.95` and create/enable the wallet via `about:preferences#payments`
* Click on the "Advanced" settings and select `1 minute` & `1 visit`
* open a new tab and load https://www.youtube.com/watch?v=8-Cjsnq8kVU
* let the video play for ~1.5 min, and switch over to `about:preferences#payments`

You'll notice that the "time spent" will be anywhere in the range of ~4-6mins when in reality you've only spent ~1minute on the video.

Platforms:

* macOS 10.12.6 x64 using `0.19.95`- Reproduced
* Win 10 x64 using `0.19.95` - Reproduced
* Ubuntu Ubuntu 17.04 x64 - Reproduced

Example:

<img width="867" alt="screen shot 2017-11-15 at 11 55 03 pm" src="https://user-images.githubusercontent.com/2602313/32874476-77afb44c-ca60-11e7-9fb2-0c7ab9933c36.png">

**Comment by NejcZdovc** [comment]
closing this one as it's not related to the initial issue. @kjozwiak please open another issue for it
