### ISSUE TITLE
Using bat-publisher@1.3.0 causes TypeError exception

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#11987]
TypeError: Cannot set property 'faviconName' of undefined
        at Object.onMediaPublisher (/Users/mrose/Documents/Projects/brave.com/browser-laptop/app/browser/api/ledger.js:2292:51)
        at ledgerReducer (/Users/mrose/Documents/Projects/brave.com/browser-laptop/app/browser/reducers/ledgerReducer.js:414:27)

apparently, we have `!publisher.isEMpty()` and `synopsis.publishers[publisherKey]` is `undefined`

cf., https://github.com/bsclifton/browser-laptop/commit/67b1d5d23f952bfbc38a0cc6d2f2ab5f96faab68

**Comment by mrose17** [comment]
*update* - with a clean profile, i am unable to reproduce this. if i don't see it again, and QA doesn't see it, let's close this issue. sorry for the false alarm, if so...

**Comment by bbondy** [comment]
@kjozwiak @bsclifton ok to close this given the above message?

**Comment by bsclifton** [comment]
Closing- I am not able to repro. I have a dirty profile and deleted all items, cleared, re-added... could not get an error to happen

**Comment by kjozwiak** [comment]
@mrose17 can you add some STR?

**Comment by mrose17** [comment]
it happened once, when i wasn't using a clean profile. my guess is that the change of using the new `bat-publisher` repository resulted in a `publisherKey` mismatch. only someone who watched youtube with the old repository and then switched to the new one would see the problem.

when i tried again with a clean profile there was no error.

**Comment by kjozwiak** [comment]
As per @mrose17 comment above, adding `QA/no-qa-needed`.
