### ISSUE TITLE
Music on vk.com may not play reliably

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#11988]
### Description
The music player on vk.com may not play music reliably.

### Steps to Reproduce
0. _Sign up if necessary_
1. Select _Music_ from the left
2. Press the _play_ button on whatever is loaded

**Actual result:**
Music _does not_ play. The console has the following error:

> Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

The user may also see the following dialog:

![An error occurred while downloading the audio file. Please refreshing the page.](https://user-images.githubusercontent.com/815158/32866036-63c49248-ca2b-11e7-9b78-f9e12d488729.png)

**Expected result:**
Music should play.

**Reproduces how often:**
The first time you interact with the audio player.

### Brave Version
0.19.88

**about:brave info:**
```
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
```

**Reproducible on current live release:**
Yes

### Additional Information

https://github.com/brave/browser-laptop/issues/11527

Reported on Twitter: https://twitter.com/HammerCorsa/status/930878637095751681

The relevant JavaScript:

```js
AudioPlayerHTML5.prototype.play = function(t) {
    this._stopFrequencyAnalise(),
    this._prefetchAudioEl.src == (0,
        _audio_unmask_source.audioUnmaskSource)(t) 
        && this._prefetchAudioEl.readyState > AudioPlayerHTML5.STATE_HAVE_NOTHING 
        && (this._setAudioNodeUrl(this._currentAudioEl, AudioPlayerHTML5.SILENCE),
        this._currentAudioEl = this._prefetchAudioEl,
        this._prefetchAudioEl = this._createAudioNode(),
        this.opts.onCanPlay && this.opts.onCanPlay()
    );
    var e = this._currentAudioEl;
    if (e.src) {
        var i = e.play();
        isUndefined(i) || i["catch"](function(t) {
            t.code != t.ABORT_ERR 
                ? setWorkerTimeout(function() {
                      triggerEvent(e, "error", !1, !0)
                   }, 10) 
                : debugLog("HTML5 audio play error: " + t)
        }),
        this._startFrequencyAnalise()
    }
}
```

**Comment by bsclifton** [comment]
Removing milestone, added dupe tag; this is a duplicate of https://github.com/brave/browser-laptop/issues/11527
