### ISSUE TITLE
Pinned tabs steal focus when closing non-pinned tabs

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#11980]
### Description
As reported by @bradleyrichter, when having any pinned tabs in a window, closing non-pinned tabs, and having a setting for _Tabs > When closing an active tab..._ of _'Select the last viewed tab'_, focus does not shift in an expected way.

### Steps to Reproduce
0. setting: select the last viewed tab
1. pin a tab
2. close the window
3. open a new window (should have 1 pinned and 1 new tab)
4. hit command+T 30 times to make 30 new tabs
5. click on the left most tab (not the pinned tab)
6. command+W until the pinned tab steals focus (just happened on 2 closes)
7. Keep closing with command+W and notice every other time it changes focus to the pin.

### Brave Version
0.19

**Reproducible on current live release:**
yes

### Additional Information

It's probably due to both new tabs opening too quick to register that they have been focused, and _perhaps_ remembering the last viewed tab by index instead of something non-ephemeral, like tabId or frameKey

**Comment by LaurenWags** [comment]
+1 from me, just encountered this on 0.19.88 and 0.19.95

**Comment by bsclifton** [comment]
+1 from me- I hate this one 😠
