### ISSUE TITLE
contribution notification says "5 USD" instead of "100 BAT"

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#11989]
## Test plan

https://github.com/brave/browser-laptop/pull/12060#issue-276093993

----

### Steps to Reproduce
  1. Whenever a contribution is made, the notification says "5 USD" instead of "100 BAT"

**Actual result:**
![0](https://user-images.githubusercontent.com/400552/32866576-4de0aa42-ca1d-11e7-8d4e-c6e3c292ee1a.png)

**Expected result:**
The notification says "100 BAT" instead of "5 USD"

**Reproduces how often:**
Every contribution period.

### Brave Version
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

### Additional Information
From `ledger-state.json`:

  "properties": {
    "setting": "adFree",
    "fee": {
      "currency": "BAT",
      "amount": 100
    },

**Comment by LaurenWags** [comment]
In image below the notification banner says 75 BAT but last contribution was 50 BAT:
![screen shot 2017-11-27 at 3 43 52 pm](https://user-images.githubusercontent.com/28145373/33288340-e5c223de-d389-11e7-8e7a-8248f0ace9c0.png)

**Comment by bsclifton** [comment]
@LaurenWags what build are you using?

**Comment by LaurenWags** [comment]
Brave | 0.19.98
rev | 1909179
Muon | 4.5.16

@bsclifton

**Comment by NejcZdovc** [comment]
@LaurenWags this happens with fake transactions right? Problem with fake transactions is that they are not sorted (will fix it in one PR) and that's why this is probably not working. If you would do it with real transactions it should be ok.

**Comment by bsclifton** [comment]
ah- great catch, @NejcZdovc.  Are you saying that it shows the last contribution amount as the one at the very top?  So @LaurenWags, the top-most item must be showing as 75 BAT.  The PR which fixed the sorting (only affects fake transactions- real ones are always sorted correctly) is https://github.com/brave/browser-laptop/pull/12069

**Comment by NejcZdovc** [comment]
@bsclifton yeah but we need to be careful about #12069. This only sorts transactions in the dialog. So if you have transactions out of order, you will see the first item in this un-ordered list in your notification. Will create fix now for fake transactions, so that this transactions will be ordered as well before saved in the state.

**Comment by NejcZdovc** [comment]
with #12118 fake transaction generator should be working correctly now (sort should be ok)

**Comment by bsclifton** [comment]
Created https://github.com/brave/browser-laptop/issues/12119 to address the issue @NejcZdovc mentioned

**Comment by LaurenWags** [comment]
I tried testing this with a "real" transaction per https://github.com/brave/browser-laptop/issues/11989#issuecomment-347409856 but when I update `reconcileTimestamp` in ledger-state.json that doesn't cause a contribution. Am I attempting this incorrectly @NejcZdovc @bsclifton ? (note, I tried with fake transactions again using `npm run add-simulated-payment-history` and it worked)
cc @kjozwiak @srirambv

**Comment by bsclifton** [comment]
@LaurenWags I believe it should be called `reconcileStamp`; after editing that, you should be able to open the browser and you may have to wait ~15 minutes for it to process.  Should be easy to see it happen if you launch w/ `LEDGER_VERBOSE=true` (like you usually do 😄  )

**Comment by srirambv** [comment]
@bsclifton Even after changing the `reconcileStamp` and waiting for ~30mins I don't see the payment history

**Comment by NejcZdovc** [comment]
@srirambv we trigger contribution as soon as stamp is old, but to get payment history it can take hours based on tests that I did when we launched BAT in October

**Comment by kjozwiak** [comment]
This still hasn't been verified/tested.. Possibly due to #12201.

**Comment by LaurenWags** [comment]
Was able to verify with 0.19.110 on MacOS: https://github.com/brave/browser-laptop/issues/12201#issuecomment-350381362
