### ISSUE TITLE
Adding decimal value to pinned site cause it to unpin

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12001]
### Description
Adding decimal value to pinned site cause it to unpin

### Steps to Reproduce
  1. Enable payments, visit few sites to add it to ledger
  2. Pin 3-4 sites in the ledger table
  3. Change one of the pinned site value to random decimal value 
  4. Site gets unpinned

**Actual result:**
![pinned value](https://user-images.githubusercontent.com/17010094/32890382-7360e3fa-cac6-11e7-977d-231f3b749488.gif)

**Expected result:**
Should not unpin the publisher and retain the original value

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.95
-- | --
rev | cc0ebad
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
Yes, same behaviour on 0.19.88

### Additional Information
#11369 #11238 #10534
cc: @mrose17 @NejcZdovc @bsclifton

**Comment by ryanml** [comment]
@srirambv @NejcZdovc I think I'd like to grab this one. To clarify, we should just fall back to the original value, and _not_ allow any decimal values inside the ledger, correct?

**Comment by ryanml** [comment]
I was taking a look at this one, and it seems that inside the PinnedInput component, the callback for onBlur was interpreting decimal values as falsey, causing them to be unpinned.

Doing that additional check here solves the unpin issue, but I'm not sure if the expectation here is that they be reset to 1. I can only assume so, as the previous check was for values less than one.

Let me know your thoughts on this one and I can change as needed and open up a PR. See: [here](https://github.com/ryanml/browser-laptop/commit/60ae3f89f194c38a37664b2853fed6312a572da9)

**Comment by ryanml** [comment]
I was taking a look at this one, and it seems that inside the PinnedInput component, the callback for onBlur was interpreting decimal values as falsey, causing them to be unpinned.

Doing that additional check here solves the unpin issue, but I'm not sure if the expectation here is that they be reset to 1. I can only assume so, as the previous check was for values less than one.

Let me know your thoughts on this one and I can change as needed and open up a PR. See: [here](https://github.com/ryanml/browser-laptop/commit/60ae3f89f194c38a37664b2853fed6312a572da9)

cc: @NejcZdovc @srirambv

**Comment by NejcZdovc** [comment]
@ryanml yeah we need to always default to 1 if you are bellow 0 or value is not a number

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
