### ISSUE TITLE
Hyperlinks in about:brave always looks grey

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12015]
## Test plan

https://github.com/brave/browser-laptop/commit/8110f82a01a65882657b55b2e954e3e1f53bedd3

Ensure the following appear as orange anchor links:
1. Payment FAQ on `about:preferences#payment`
2. Adobe and wiki `about:preferences#plugins`
3. Release notes and revision on `about:brave`
4. Inspect pages on `about:extensions`
5. Community under `about:preferences#extensions`
6. Manage passwords on `about:preferences#security`

----

### Description
Hyperlinks in about:brave always looks grey

### Steps to Reproduce

  1. Open about:brave
  2. Hyperlinks on the page looks greyed out 
  3. Hover over doesn't change 

**Actual result:**
![hyperlink](https://user-images.githubusercontent.com/17010094/32940079-883007bc-cb79-11e7-96e9-20721d662e0c.gif)

**Expected result:**
Should be similar to the beta version

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
This will be fixed with https://github.com/brave/browser-laptop/commit/8110f82a01a65882657b55b2e954e3e1f53bedd3#diff-83a9c31b7f8db399cce791535a519b5f. Closing and adding the milestone as the PR https://github.com/brave/browser-laptop/pull/10163 does not have the tracking issue for it.

**Comment by kjozwiak** [comment]
Generally working well! However, hovering over the `community` link under `about:preferences#extensions` doesn't change as expected. Example:

![communitylink](https://user-images.githubusercontent.com/2602313/34272490-79c8d898-e65e-11e7-8b65-2e7b8419ae17.gif)

All links under `about:preferences` should behave the same. This should be a minor/quick fix. I've also ended the above Test Plan to include this case.

**Comment by luixxiul** [comment]
I'll take this one, thanks for checking.

**Comment by bsclifton** [comment]
@luixxiul are you actively working this issue?
