### ISSUE TITLE
the password manager prompt should have an option to remember the setting

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1201]
when prompted to save a password or for notification/etc.. permissions, there should be an option to save the response (past the current session). This probably also requires a UI to manage the saved responses or at the very least a method to reset all of them.

**Comment by bbondy** [comment]
about:passwords exists as of this latest version btw. The remember part of this still valid though.

**Comment by diracdeltas** [comment]
permissions issue: #1049 
aaf4c1ec584b2cf8b13dea656d11fae6f1278ecf makes it possible to disable the password manager in about:preferences, so i'll change the title to reflect that this refers to disabling the password manager from the prompt itself

**Comment by diracdeltas** [comment]
subticket of #923
