### ISSUE TITLE
samsung.com not working as expected

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#12011]
### Description

Different views of the product not clickable:
https://www.samsung.com/us/mobile/wearables/smartwatches/gear-sport-blue-sm-r600nzbaxar/?cid=dis-mb-wea-1017-2009826

### Steps to Reproduce

  1. go to https://www.samsung.com/us/mobile/wearables/smartwatches/gear-sport-blue-sm-r600nzbaxar/?cid=dis-mb-wea-1017-2009826
  2. click on left-hand product thumbnails
  3.

**Actual result:**

not clickable, not responding

**Expected result:**
click each thumbs to display enlarged images

**Reproduces how often:**

50%

### Brave Version

**about:brave info:**

0.19.95

**Reproducible on current live release:**

### Additional Information

this works when putting the shield down (i thought we have a report link for sites that are not working, but couldn't locate it)

**Comment by jenn-rhim** [comment]
looks like the '?cid=dis-mb-wea-1017-2009826' (referral key?) is affecting this. removing it makes it work.  it works with or without in Chrome and Firefox.

**Comment by bsclifton** [comment]
Appears to be fixed now 😄
