### ISSUE TITLE
brave is ad-blocking non ads on kitchen.manualsonline.com 

### ISSUE THREAD

**Issue by Alino** [brave/browser-laptop#12016]
latest brave version on MacOS high sierra
visiting this url
http://kitchen.manualsonline.com/manuals/mfg/samsung/da9901220j.html?p=2

the PDF manual is ad-blocked, but with shields down the site displays correctly.

**Comment by luixxiul** [comment]
I'm going to close this issue in favor of our community site.

https://community.brave.com/c/qa/web-compatibility

To report similar issues on other sites, please do so there 😄Thanks!
