### ISSUE TITLE
top site tiles go missing

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12027]
## Test plan
See https://github.com/brave/browser-laptop/pull/12470

### Description
Using 0.19.95, each time I open a new tab after close/reopen of Brave, a top site tile goes missing. Meaning, I start with 6 tiles, then next time I open Brave again and open a new tab, I only have 5 top site tiles.

### Steps to Reproduce

1. Use a profile where you have enough visits to sites that the top site tiles are not the defaults.
2. Open Brave.
3. Open a new tab. (you will encounter https://github.com/brave/browser-laptop/issues/12026)
4. Note number of tiles displayed. Close new tab.
5. Close/Reopen Brave.
6. Open another new tab.
7. You have one less tile than you did previously and encounter https://github.com/brave/browser-laptop/issues/12026 again)
8. If you continue to repeat, you will have one less tile after each close/reopen.
Note - it doesn't matter if you close the new tabs or leave them open, top site tiles disappear regardless.

**Actual result:**
A top site tile goes missing from the new tab display on each close/reopen of Brave.
https://drive.google.com/a/brave.com/file/d/1RP64tyzv8eCkZuNFZbzyhE7J8-IvRTES/view?usp=sharing

**Expected result:**
Top site tiles should not go missing.
https://drive.google.com/a/brave.com/file/d/1RxeV2U5v5-6Kp6M-f13fZqAAtkZHfzC2/view?usp=sharing

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.19.95

**Reproducible on current live release:**
yes

### Additional Information
Could not reproduce on 0.19.88, only seems to happen with 0.19.95.

Additionally, you can reproduce this with a clean profile but the steps are a little different:
1. Clean profile.
2. Visit a couple of sites that are not in default tiles.
3. Open a new tab, you will see your top site tiles change to reflect sites.
4. Close/Reopen Brave.
5. Default top site tiles are displayed and don't change.
6. Go back to some of the sites.
7. Click on new tab again.
8. You will issue described in https://github.com/brave/browser-laptop/issues/12026 and then your tiles will change but be one less than you had before. 

https://drive.google.com/open?id=1RxeV2U5v5-6Kp6M-f13fZqAAtkZHfzC2

**Comment by cezaraugusto** [comment]
I did a regression check and can confirm this is older than 0.19.88. From browser-laptop side, there were no changes in this area ranging between 0.19.88 and 0.19.95, while I still can reproduce the bug almost 100%.

Given the above, I'm moving this and #12026 to 0.20.x, where it should match #11102 together with other big changes in this logic. Let me know if you think otherwise and we'll find a way. Thanks @LaurenWags

**Comment by cezaraugusto** [comment]
note to self: 

latest working version is prior to 5017bdded9db6b2634c73a675e3275076f3e84f5. 

TODO:

- [ ] check history after that commit
- [ ] should newtab data be debounced? likely causing #12026

**Comment by luixxiul** [comment]
Maybe we should consider to remove skip on https://github.com/brave/browser-laptop/commit/d44f35f66d52a8bf18e4b157a305f05e181b61f0#diff-0a9ec054c57d2a0b36c47fff4c08c704R90 on newTabTest.js.

The issue to track that flag has been closed for a long time ago (https://github.com/brave/browser-laptop/issues/6408); I am wondering if the flag has been tracked on somewhere else.
