### ISSUE TITLE
top site tiles momentarily display defaults before showing actual ones

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12026]
## Test plan
See https://github.com/brave/browser-laptop/pull/12470

### Description
Using 0.19.95, when opening a new tab, default top site tiles display for a few seconds before displaying the actual ones. 

### Steps to Reproduce

  1. Use a profile where you have enough visits to sites that the top site tiles are not the defaults.
  2. Open Brave.
  3. Open a new tab.

**Actual result:**
Top site tiles are displayed for a few seconds before the actual tiles display.
![01995topsitetiles](https://user-images.githubusercontent.com/28145373/32982088-ce6edc84-cc4c-11e7-9a50-2991e8d26e6c.gif)

**Expected result:**
Actual top site tiles should be displayed as they are in 0.19.88.

https://drive.google.com/a/brave.com/file/d/1kIqFaf32Q8rboXnCYwgrSuThXYgwWqBc/view?usp=sharing

**Reproduces how often:**
reproduces 100% for me

### Brave Version

**about:brave info:**
Brave | 0.19.95
rev | cc0ebad
Muon | 4.5.16

**Reproducible on current live release:**
yes

### Additional Information
Could not reproduce on 0.19.88, but could repro on 0.19.95

Also, you can repro this with a clean profile, but steps are slightly different. 
1. Clean profile.
2. Visit a couple of sites that are not in default tiles.
3. Open a new tab, you will see your top site tiles change to reflect sites.
4. Close/Reopen Brave.
5. Default top site tiles are displayed and don't change.
6. Go back to some of the sites. 
7. Click on new tab again. 
8. You will see defaults and then they will change to reflect the sites you visited again.

https://drive.google.com/a/brave.com/file/d/1UnZqtam7x8ifHcNsiIFVI3N-licltaj6/view?usp=sharing

**Comment by cezaraugusto** [comment]
moving to 0.20.x please see comment in https://github.com/brave/browser-laptop/issues/12027#issuecomment-346436847. Thanks!
