### ISSUE TITLE
energy usage on macOS

### ISSUE THREAD

**Issue by bobinson** [brave/browser-laptop#12022]
### Description
Average energy impact of the Brave browser seems to be quite high. This report is not a very accurate one IMHO as I lack the know-how to track the KPI required for energy usage. I have used htop as well as mac's in built Activity monitor.

![2017-11-18_07-28-58](https://user-images.githubusercontent.com/18070249/32976085-0c49120c-cc36-11e7-8684-e840d36b0c9e.png)

Brave on the top 10 in terms of CPU usage as well.

### Steps to Reproduce

  1. Open Brave and it was upgraded to latest build
  2. Open few tabs I think this application is important as it has some JS ( https://steemworld.org/@bobinson )
  3. Other tabs are not heavy on JS and in total there are 5 open
4. Keep them running for 12 - 15 hours
5. Simultaneously I have iTerm2 and Firefox 58 beta running for long duration. (iTerm2 for 4 - 5 days and FF for a day or two)
6. Brave is using lot of energy 

**Actual result:**
![2017-11-18_08-01-02](https://user-images.githubusercontent.com/18070249/32976143-d0cde9e0-cc36-11e7-9c78-e459ee97ca6e.png)

**Expected result:**

much lower energy footprint

**Reproduces how often:**
every time

### Brave Version

**about:brave info:**
 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**

its a development build - cc0ebad

### Additional Information
NA

**Comment by luixxiul** [comment]
per your screenshot Firefox consumes much resource but is it not an issue for you?

**Comment by bobinson** [comment]
@luixxiul  - yes, but it is running for more than 48 hours with more than dozen tabs which has the same tabs as that of Brave + 2 gmail sessions + one zero cash pool which keeps updating frequently. So is iTerm - its running for 4+ days. So I guess I can't complain about their memory usage.

**Comment by luixxiul** [comment]
I am not sure at all but on macOS does energy impact increase by running an app longer?

**Comment by bsclifton** [comment]
This is an issue we won't be fixing with our current Muon based product. I'd welcome you to try the new [developer channel release](https://brave.com/download-dev) (aka brave-core) and see if it's still a problem. If so, you can report the issue here:
https://github.com/brave/brave-browser/issues
