### ISSUE TITLE
Tabs on Reddit threads omit sections of spoiler tagged content

### ISSUE THREAD

**Issue by faragorn01** [brave/browser-laptop#12020]
When browsing Reddit.com, any text blocs tagged as spoilers are omitted in Brave when they should be enclosed as spoilers but available to the user. Chrome works correctly as a comparison

### Steps to Reproduce

  1. Browse to the following url: https://www.reddit.com/r/Stormlight_Archive/comments/7dllrd/oathbringer_passion/
  2. In Chrome, the Spoiler block correctly displays
  3. In Brave, the spoiler block is completely missing

**Actual result:**
![brave browser spoiler block bug in reddit](https://user-images.githubusercontent.com/13441342/32964136-0c624d58-cb87-11e7-9669-cab8b37ca5c1.PNG)

**Expected result:**
See the Chrome screen shot for a correct result
![chrome browser spoiler block correctly shows for comparison vs brave](https://user-images.githubusercontent.com/13441342/32964137-0c7f7d74-cb87-11e7-9b83-cf343076bc09.PNG)

**Reproduces how often:**
Happens always

### Brave Version

**about:brave info:**
 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64

**Reproducible on current live release:**
Yes, the most recent update

**Comment by faragorn01** [comment]
It went away for a while but it's back as of the latest Brave update.

**Comment by bsclifton** [comment]
Confirmed this is fixed with our developer channel release 😄 
https://brave.com/download-dev
