### ISSUE TITLE
suggested about:welcome page updates

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#12024]
### Description
The about:welcome page is pretty outdated, and has potential to feature more BAT utility during the first run process that could be key in getting active utility users. There's some room to simplify copy and bring in line with some of the copy that has performed well in field trial campaigns. 

I dug for a similar issue, and couldn't locate one. Adding notes here. If this is already in progress, maybe these notes will help. Unable to determine that based on hunting for issues here. 

This is a pretty vital area to get updated, imo. This page is the first impression the user encounters in Brave, there are opportunities to get them on board with activating payments, etc. 

Also need to update Brave Payments graphic. 

Suggestions for some text updates as well to simplify. 

*Above the Fold* 
![brave-about-welcome-11182017-atf-export](https://user-images.githubusercontent.com/8979240/32979812-cd86ed2a-cc10-11e7-800d-dc9de4b02843.jpg)

1. Suggested title change: "Prepare to Experience a Better Web" 
 - "Experience a Better Web" has outperformed other messaging in field trials. 
 - Positive message. 

2. To the right of *Edit Shields*, include a new button to *Activate Brave Payments* in flow. This could be a big utility driver on first run. Opt in, but no question it helps with the experience at a core level.

3. Include MetaMask icon with other extensions. This is a win, and will help with key demos. 

*Mid-fold* 
![brave-about-welcome-11182017-midfold-export](https://user-images.githubusercontent.com/8979240/32979847-5bfc276e-cc11-11e7-80fd-dd09f65f99c8.jpg)

1. Shorten extension title to "Extensions" 

2. Add MetaMask icon to extension icons listed. 

3. Update Brave Payments image to include the BAT icon. 

4. Update browser tabs title to: "A new spin on browser tabs"

*Below the fold* 
![brave-about-welcome-11182017-btf-export](https://user-images.githubusercontent.com/8979240/32979875-d32139d8-cc11-11e7-8a04-9afd0fd9bae5.jpg)

1. Add the BAT icon to the left of the verification icon. 

2. Update title text to: "Fund publishers and creators you love." 

3. Update the description text to: 
"Brave Payments utilizes the Basic Attention Token to allow you to contribute to sites you frequent most. Opt in, it's automatic. 
Or, turn your own dials and customize on a site-by-site basis."

### Brave Version

**about:brave info:**
``` 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64
```

**Reproducible on current live release:**
yes

Attn: @bradleyrichter @davidtemkin @BrendanEich @bbondy

**Comment by luixxiul** [comment]
related: https://github.com/brave/browser-laptop/issues/11927

**Comment by davidtemkin** [comment]
Thanks. This page is going to get a from-scratch redesign not long from now. Exact timing TBD.

**Comment by bradleyrichter** [comment]
Long overdue. 

But we may need to implement new code that allows for deep linking to sub dialogs within a prefs page. Currently we are blocked by this issue for better usability and options.

**Comment by davidtemkin** [comment]
That's an important feature, agree (i.e., send a user directly to payments prefs).

**Comment by bsclifton** [comment]
Closing as this page is implemented differently in [brave-core](https://github.com/brave/brave-browser)
