### ISSUE TITLE
Tweak download usability problems

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1202]
- [x] Don't prompt for save location by default (make it a preference)
  ![screenshot 2016-03-30 13 12 45](https://cloud.githubusercontent.com/assets/831718/14150861/21aaa212-f679-11e5-939e-2d4306202261.png)
- [x] Add a Show All button to the downloads toolbar.
- [x] Only active state downloads should have a white background, completed state items should have a gray background.
  ![screenshot 2016-03-30 13 13 25](https://cloud.githubusercontent.com/assets/831718/14150880/38dfa040-f679-11e5-8ca3-c6d6492e19a0.png)
- [x] Show some kind of confirmation when a link is copied to the clipboard.  I think using a web notification works here.
- [x] Ask to confirm whether or not to delete an item after the trash can is clicked
- [ ] Show downloaded file size next to progress complete
- [ ] Downloads toolbar should only display new things since it was opened

CC @bradleyrichter

**Comment by pedro7** [comment]
Sometimes a download is started but doesn't trigger the download bar. It happened at least twice but I've yet to find out how to trigger it on purpose.

**Comment by bbondy** [comment]
I think I've seen this before too. Once you're in this state can any download show it? Or only a browser restart fixes?

**Comment by pedro7** [comment]
I think only a browser restart fixed it.
If it happens again, I'll report it.

**Comment by pedro7** [comment]
Hasn't happen again.

**Comment by bbondy** [comment]
were you using a normal tab or was it a private tab / session tab? Thanks.

**Comment by bbondy** [comment]
>  Only active state downloads should have a white background, completed state items should have a gray background.  (0.9.2)

**Comment by bbondy** [comment]
> Show some kind of confirmation when a link is copied to the clipboard. I think using a web notification works here.

Fixed for 0.9.3

**Comment by Liunkae** [comment]
> Don't prompt for save location by default (make it a preference)

To prevent rogue websites from downloading tons of files, I think there should still be some sort of prompt.

**Comment by Liunkae** [comment]
> Ask to confirm whether or not to delete an item after the trash can is clicked

Fixed in 0.13.5 with #7072.

**Comment by Liunkae** [comment]
> Don't prompt for save location by default (make it a preference)

Fixed in 0.14.0 with #7023.
