### ISSUE TITLE
Add pinboard.in extension

### ISSUE THREAD

**Issue by chmanie** [brave/browser-laptop#12049]
### Description
It'd be great to have an extension for pinboard (https://pinboard.in), similar to the pocket one. I'd be happy to help out realising this.

There's been requests for this in the community already:

https://community.brave.com/t/new-extension-request-pinboard-in/3582

Prior art: https://pinboard.in/resources

**Comment by luixxiul** [comment]
Your suggestion was added here: https://github.com/brave/browser-laptop/projects/1#card-5782468

**Comment by hugobuddel** [comment]
I've added the pinboard bookmarklet to the bookmarks toolbar. That works quite nicely, but takes up an entire toolbar for a single (ugly) button.

It is a bit difficult to create the bookmarklet though, you need to copy the bookmarklet-link using another browser and then manually create the bookmark in Brave, see #11088 .

A pinboard extension would be way nicer, but the bookmarklet is workable for me. (Without it, I would probably not use Brave.)

(Any suggestion on how to improve this are welcome, e.g. is it possible to assign a keyboard shortcut to a bookmark so I can hide the bar?)

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
