### ISSUE TITLE
Netflix autoplay notification keeps showing up even after selecting allow

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12048]
### Description
Netflix autoplay notification keeps showing up even after selecting allow

### Steps to Reproduce
  1. Install 0.20.7
  2. Visit Netlfix
  3. Click Allow on autoplay notification
  4. Go back to main screen, autoplay notification shows up
  5. Go to preferences, Run widevine shows always allow under saved site settings

**Actual result:**
Netflix autoplay notification keeps showing up even after selecting allow

**Expected result:**
Should not keep prompting autoplay notification once allow is clicked

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.7
-- | --
V8 | 6.2.414.42
rev | a2ba3e8
Muon | 4.5.16
OS Release | 10.0.15063
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.94

**Reproducible on current live release:**
No

**Comment by luixxiul** [comment]
I once saw that on 0.19.95 as well.
