### ISSUE TITLE
Clicking anchor with hash and onClick does not work as it should

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12044]
### Description

Clicking anchor with hash and onClick does not work as it should.

### Steps to Reproduce

  1. Open https://www.wsl.waseda.jp/syllabus/JAA101.php
  2. Copy `ARTT232L` and paste it on the 1st input form
  3. Click the most left button on the footer, `検索`
  4. On the search result, click `Contemporary Performing Arts`

**Actual result:**

A new window is opened with a blank tab loading `about:blank`

Nothing is output on Devtool console.

![clipboard01](https://user-images.githubusercontent.com/3362943/33032641-396ce69c-ce65-11e7-96a0-8fc767f79b38.png)

**Expected result:**

This URL `https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EX31700512017210EX3170021&pLng=jp` should be opened. 

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

0.19.95

**Reproducible on current live release:**

Yes.

### Additional Information

The link works on Chrome.

**Comment by bsclifton** [comment]
@luixxiul can you retest this please?

**Comment by luixxiul** [comment]
@bsclifton it's been solved :-)
