### ISSUE TITLE
Records for recent contributions aren't showing up

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#12055]
### Description

![missing_contrib](https://user-images.githubusercontent.com/8796196/33095680-5e12e8c4-cefc-11e7-9bcc-dd94dea17166.png)
Basically after a contribution is known to have occurred the "Last contribution:" is not updated. Furthermore the contribution history is not accessible.

This issue has occurred for at least 3 users. I first investigated a user report that their transfer did not all make it into their BAT wallet. It turned out that the correct amount did get transferred, however a settlement payment was made immediately afterwards. It was not obvious that this happened because the "last contribution" did not update and continued to say "No previous contributions".

This user on our community site is also affected - https://community.brave.com/t/bat-funds-distributed-today-yet-no-previous-contributions-listed-in-payments-tab/10866/5

Finally, now I have been affected :) I have been having an issue where I am being asked for a contribution despite having sufficient funds and my settlement payment was not being attempted despite being long overdue. 
![false_add_funds_alert](https://user-images.githubusercontent.com/8796196/33095507-cc9b57d2-cefb-11e7-9c41-e839d0e10ce1.png)
However after update to master (bbab253d2c217f11e7c51c2f2d24396b708e20a2) this previous issue was resolved and a payment was successful. I am not sure if this previous issue is related but I have included it for completeness.

### Steps to Reproduce

1) Clean profile
2) start browser with staging server
```
LEDGER_ENVIRONMENT=staging npm run start
```
3) Enable payments
4) Visit some sites so that you have a few ledger entries showing on the Payments tab
5) Fund wallet (ex: claim UGP grant)
6) Close Brave
7) Update `reconcileStamp` in `ledger-state.json` to the epoch for now (or a time in the past). ([This site](https://www.freeformatter.com/epoch-timestamp-to-date-converter.html) is handy for conversions)
8) Launch Brave again using
```
LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging npm run start
```
9) Wait for contribution to be made (watch console for success)
10) Quit Brave before it syncs
11) Relaunch and visit Preferences > Payments
12) Balance will update- a payment was clearly made but there is no history

**Comment by KarmaMonk** [comment]
same here
 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.14.0-041400-generic 
OS Architecture: x64

**Comment by LaurenWags** [comment]
+1 from me, reproduced on 0.19.107

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/bat-funds-distributed-today-yet-no-previous-contributions-listed-in-payments-tab/10866/7

**Comment by kjozwiak** [comment]
+1 from me when using `0.19.107` under Ubuntu 17.10 x64.

**Comment by bsclifton** [comment]
Root cause discovered-

When it's settlement time, the code will do `bat-client`.`reconcile`.  This actually settles the transaction (funds transfer, server side is updated).  However, the record of that happening isn't stored until `bat-client`.`sync` is executed.  This will happen periodically at a random interval... but if you're unlucky and quit before that happens, your "receipt" is lost

**Comment by mrose17** [comment]
@bsclifton - i looked at https://github.com/brave-intl/bat-client/blob/master/index.js#L368 et. seq. and i don't see a return in which state has changed *and* `callback` is not invoked. can you give me a path in the code where that happens? thanks!

**Comment by bsclifton** [comment]
I jumped to conclusions a little too early! Thanks for helping me debug, @mrose17 

Basically, the data appears to be there in the `ledger-state.json`.  However, the `ballots` array is missing (instead of being populated on the sites which were voted on). Also, there are fields which probably don't need to be stored (`credentials`, etc).  I need some help understanding this

**Comment by LaurenWags** [comment]
+1 from community (original thread here, additional details leading to this diagnosis were provided over DM): https://community.brave.com/t/bat-sent-to-brave-wallet-address-does-not-appear-in-brave-account-balance/11542

**Comment by LaurenWags** [comment]
Verified was able to get an updated 'Last Contribution Date' and Payment History on MacOS using 0.19.110:
![screen shot 2017-12-08 at 4 48 24 pm](https://user-images.githubusercontent.com/28145373/33786794-87986b6c-dc38-11e7-87f5-2a4e83e0f9b8.png)
![screen shot 2017-12-08 at 4 48 47 pm](https://user-images.githubusercontent.com/28145373/33786802-8dfb9f92-dc38-11e7-967e-ee72ff0612d7.png)

**Comment by bsclifton** [comment]
Took longer than expected on Windows (I had waited ~30 minutes after settlement... then quit and relaunched)... but contribution does now show on Windows 😄 
![screen shot 2017-12-08 at 4 44 13 pm](https://user-images.githubusercontent.com/4733304/33789658-7db08bbc-dc37-11e7-9407-cf7d0f6e3af1.png)

**Comment by srirambv** [comment]
Works on Windows too but found issue with losing ledger entries (#12245)
![image](https://user-images.githubusercontent.com/17010094/33827987-2dfaa2a6-de62-11e7-8e8b-9b16b7a99f9f.png)

**Comment by kjozwiak** [comment]
I went through the following test cases under both the `production` and `staging` servers:

* Contributed/Reconciled 25 BAT and ensured that `Last contribution` and `Payment history` were both updated and displayed the correct information
* Contributed/Reconciled 50 BAT and ensured that `Last contribution` and `Payment history` were both updated and displayed the correct information
* Contributed/Reconciled 75 BAT and ensured that `Last contribution` and `Payment history` were both updated and displayed the correct information
* Contributed/Reconciled 100 BAT and ensured that `Last contribution` and `Payment history` were both updated and displayed the correct information

**_Quick Note:_** the 100 BAT case was only tested against the staging server.

Build being used:

> Brave: 0.19.115 
> rev: 584e69490e984bb0909aa45edfec778ed91ee370 
> Muon: 4.5.25 
> libchromiumcontent: 63.0.3239.84

Environmental Variables being used:

* Staging Server -->` LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true`
* Production Server --> `LEDGER_VERBOSE=true LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true`
