### ISSUE TITLE
Brave doesn't seem to update the autocomplete list based on frequency of access

### ISSUE THREAD

**Issue by Alino** [brave/browser-laptop#12050]
### Description

as mentioned in this closed issue by ezyang https://github.com/brave/browser-laptop/issues/3049
The second point of that issue is not still fixed.

in my case, if I type "coin" in the url bar. I expect coinmarketcap.com to be the first result, because I visit this site most frequently compared to other autocomplete results.

![image](https://user-images.githubusercontent.com/763194/33071916-b6d69a44-cebd-11e7-8e9b-12103ddc5238.png)

### Brave Version
0.19.95

**Comment by Miyayes** [comment]
+1 from community: https://www.reddit.com/r/BATProject/comments/8pmkk3/this_needs_to_stop_after_dealing_with_brave/

> "This needs to stop. After dealing with Brave Browser for 6+ months, this is one of the most annoying features out there, surpassing all the most tedious bugs I've dealt with in my time."

**Comment by bsclifton** [comment]
This issue should be fixed in our [developer channel](https://brave.com/download-dev)
