### ISSUE TITLE
Moving nested bookmarks folder to root folder is not shown on toolbar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12052]
### Description
Moving nested bookmarks folder to root folder is not shown on toolbar

### Steps to Reproduce
  1. Clean install 0.20.7
  2. Import 5k bookmark with nested folders
  3. Move nested folder to root folder, all nested folders and bookmarks are lost
  4. Move individual bookmark to root folder, shows up on toolbar

**Actual result:**
![bookmarks](https://user-images.githubusercontent.com/17010094/33074650-dbeaae14-cebe-11e7-979b-6511d1c46c16.gif)

**Expected result:**
Should show bookmark nested folder on toolbar when moved to root folder

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.7
-- | --
V8 | 6.2.414.42
rev | a2ba3e8
Muon | 4.5.16
OS Release | 10.0.15063
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.94

**Reproducible on current live release:**
No

**Comment by luixxiul** [comment]
Should its milestone not be escalated to `0.20.x` as it is a regression?

**Comment by NejcZdovc** [comment]
@srirambv can you please check if this issue is fixed with this PR https://github.com/brave/browser-laptop/pull/12517

**Comment by srirambv** [comment]
Will do

**Comment by srirambv** [comment]
Tested the PR works fine
![12517](https://user-images.githubusercontent.com/17010094/34622781-86ae5408-f274-11e7-9866-661629da6790.gif)

**Comment by cezaraugusto** [comment]
thanks @srirambv just landed #12517 I'm closing this
