### ISSUE TITLE
passwords not saved

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12063]
### Description
Brave is not saving passwords. 

### Steps to Reproduce

  1. Clean profile for 0.20.7 (packaged beta build)
  2. Navigate to site (I used https://trac.torproject.org/projects/tor/login) and enter login credentials.
  3. Select 'Allow' in notification.
  4. Navigate to about:passwords

**Actual result:**
Username/Password is not saved.
![pwdoesntsave](https://user-images.githubusercontent.com/28145373/33137388-d27c4af6-cf75-11e7-9973-3e15b400ae1f.gif)

**Expected result:**
Username/Password should be saved.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.7
V8 | 6.2.414.42
rev | a2ba3e8
Muon | 4.5.16

**Reproducible on current live release:**
Not for me, but there is this issue which was reported for current release: https://github.com/brave/browser-laptop/issues/12038

### Additional Information
I can repro on MacOS consistently, @srirambv does not see this on Windows.

**Comment by kjozwiak** [comment]
@LaurenWags is it possible that you clicked on "Deny" when you were prompted for "Chromium Safe Storage" access? When I select "Deny", passwords aren't being added into `about:passwords`. However, when I allow access, the passwords are being saved under `about:passwords` without any issues...

Example of the "Chromium Safe Storage" permission prompt:

<img width="1604" alt="screen shot 2017-11-22 at 1 15 06 pm" src="https://user-images.githubusercontent.com/2602313/33143356-a4fab380-cf87-11e7-9da5-58cc910cf800.png">

**Comment by alexwykoff** [comment]
@LaurenWags please retest when you have a moment, thanks!

**Comment by LaurenWags** [comment]
couldn't repro, closing issue.
