### ISSUE TITLE
password save prompt stops feedly login window from closing

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1206]
Steps to reproduce:
1. Log out of feedly and any service you use as a login provider (google, etc..)
2. Click the login link and login using the popup window
3. When prompted to save your password click "no"
4. Feedly usually opens in the main window, but the popup doesn't close. Sometimes feedly also fails to reload

**Comment by diracdeltas** [comment]
subticket of #923

**Comment by diracdeltas** [comment]
btw feedly also fails to close if there are any pinned tabs. related: #1037

**Comment by bbondy** [comment]
Moving this to 0.9.1
