### ISSUE TITLE
Context menu on bookmarksToolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12064]
### Description

There is a gap between the icons and the label on the context menu items on bookmarksToolbar.

<img width="256" alt="screenshot 2017-11-23 3 35 45" src="https://user-images.githubusercontent.com/3362943/33144253-bb3363fe-cfff-11e7-9926-ead3aa0ab160.png">

This is a regression bug caused by https://github.com/brave/browser-laptop/pull/11528/files#diff-d967b08f3e2eb972f1c3242327c1a4a1R292 of #11428.

### Brave Version

**about:brave info:**

c5186d5829e6aa5cd18ec3d6b125aaa4c9d810fe

**Reproducible on current live release:**

No.

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
