### ISSUE TITLE
Claim token notification should be shown once wallet is created

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12079]
### Description
Claim token notification should be shown once wallet is created

### Steps to Reproduce
  1. Clean install 0.19.96
  2. Enable payments
  3. Claim free tokens notification is shown even before wallet is created

**Actual result:**
![claim token](https://user-images.githubusercontent.com/17010094/33172718-2f928b5a-d049-11e7-9895-23b02168d351.gif)

**Expected result:**
Claim token notification should be shown once wallet is created

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.96
-- | --
rev | 9d72944
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
N/A

**Comment by NejcZdovc** [comment]
that's by design. Initial notification is delayed 15s after browsers starts and when you switch enable we just replace disabled notification with enabled on.
