### ISSUE TITLE
Text needs alignment in payment window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12076]
### Description

![image](https://user-images.githubusercontent.com/17010094/33166600-badc7020-d032-11e7-9786-0fcb4d3d0a33.png)

**Actual result:**
![marginbottom](https://user-images.githubusercontent.com/17010094/33166787-6fc0bfbe-d033-11e7-8da6-adf8e8596f83.gif)

**Expected result:**
All text should be properly aligned

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.96
-- | --
rev | 9d72944
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
this is only problematic on `0.19.x_UGP` (merge problem) and should be fixed when we will merge PR into master and rebase it back to 0.19 branch

**Comment by luixxiul** [comment]
Closing for QA.

**Comment by kjozwiak** [comment]
Everything looks like it's aligned correctly under `0.19.99`:

<img width="842" alt="screen shot 2017-11-28 at 11 13 59 pm" src="https://user-images.githubusercontent.com/2602313/33357734-228784c2-d492-11e7-94df-897c02a75b8a.png">
