### ISSUE TITLE
Problem claiming promotion Error: HTTP response 404 shown when clicked on Claim my tokens

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12074]
### Description
Problem claiming promotion Error: HTTP response 404 shown when clicked on Claim my tokens

### Steps to Reproduce
  1. Create wallet in 0.19.95 and visit sites and YT channels to add it to ledger table
  2. Disable wallet and update to 0.19.96
  3. Click on the `I'm ready` button in the optin notification bar, wallet doesn't get enabled
  4. Manually enable payments, Click `Claim my free tokens` button, nothing happens
  5. Click on `Claim my free tokens` button above the add fund button, nothing happens, console shows 404 error

**Actual result:**
```
<<< PUT https://ledger-staging.mercury.basicattentiontoken.org/v1/grants/09a5af68-36d8-4a62-af76-bc00541d1853
<<< content-type: application/json; charset=utf-8
<<< accept-encoding:
<<<
<<< {
<<<   "promotionId": "1"
<<< }
[ response for PUT https://ledger-staging.mercury.basicattentiontoken.org/v1/grants/09a5af68-36d8-4a62-af76-bc00541d1853 ]
>>> HTTP/1.1 404
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 103
>>> content-type: application/json; charset=utf-8
>>> date: Thu, 23 Nov 2017 08:22:01 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 58
>>> x-rate-limit-reset: 1511425365
>>>
>>> {"statusCode":404,"error":"Not Found","message":"no such wallet: 09a5af68-36d8-4a62-af76-bc00541d1853"}
Problem claiming promotion Error: HTTP response 404 for PUT /v1/grants/09a5af68-36d8-4a62-af76-bc00541d1853
```

**Expected result:**
Should not give 404 error

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.96
-- | --
rev | 9d72944
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
N/A

### Additional Information
cc: @evq @mrose17 @NejcZdovc

**Comment by NejcZdovc** [comment]
based on conversation with @evq this is a problem because master branch is on production server, but UGP is still on staging. This will be solved when we switch to production servers

**Comment by luixxiul** [comment]
Closing for QA.

**Comment by srirambv** [comment]
Seeing the error on clean profile as well
```
<<< GET https://ledger-staging.mercury.basicattentiontoken.org/v1/grants
<<< content-type: application/json; charset=utf-8
<<< accept-encoding:
<<<
[ response for GET https://ledger-staging.mercury.basicattentiontoken.org/v1/grants ]
>>> HTTP/1.1 404
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 74
>>> content-type: application/json; charset=utf-8
>>> date: Thu, 23 Nov 2017 13:52:07 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1511445187
>>>
>>> {"statusCode":404,"error":"Not Found","message":"no promotions available"}
Error retrieving promotion Error: HTTP response 404 for GET /v1/grants

```

**Comment by luixxiul** [comment]
> This will be solved when we switch to production servers

So basically this seems to happen until the servers are switched to production ones?

**Comment by NejcZdovc** [comment]
correct, note that 0.19.96 is based off #11874 branch and it's not in the master yet

**Comment by srirambv** [comment]
Verified on Windows. `Claim my tokens` work and shows success message. Tokens added is reflected after ~18mins of claiming token. 

cc: @kjozwiak @LaurenWags
