### ISSUE TITLE
Unable to delete brave local profile when beta browser window is open

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12077]
### Description
Unable to delete brave local profile when beta browser window is open

### Steps to Reproduce

  1. Install Brave Beta alongside Brave release version
  2. Keep Brave beta window open close brave release window
  3. Open `%userprofile%/local` and try deleting brave folder, shows error that file is active
  4. Close Brave beta window, try deleting brave folder, deletes without complaint

**Actual result:**
![bravelocal](https://user-images.githubusercontent.com/17010094/33169169-86fc6ac2-d03b-11e7-9834-76386ddaf702.gif)

**Expected result:**
Should be able to delete without having to close brave beta browser window

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.95
-- | --
rev | cc0ebad
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

Brave | 0.20.7
-- | --
V8 | 6.2.414.42
rev | a2ba3e8
Muon | 4.5.16
OS Release | 10.0.15063
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.94

**Reproducible on current live release:**
Yes

### Additional Information
Issue could be due to #11760 & #11856 
Adding same priority as #11856

**Comment by bsclifton** [comment]
Should be addressed with [brave-core](https://github.com/brave/brave-browser) - should be retested once it moves to Beta channel
