### ISSUE TITLE
Embeded Tweets

### ISSUE THREAD

**Issue by CAPerkins22** [brave/browser-laptop#1208]
Embeded tweets aren't loading on pages. Here's the link that was used for the attached screenshots: http://www.thescore.com/nba/news/995729

**Brave**: 
![brave - kyrie_irving_addresses_personal_life_on_twitter__then_deletes_tweets___thescore_com](https://cloud.githubusercontent.com/assets/16940931/14178136/56fa50d0-f727-11e5-8eb1-429a110cd00f.jpg)

**Chrome**: 
![chrome - kyrie_irving_addresses_personal_life_on_twitter__then_deletes_tweets___thescore_com](https://cloud.githubusercontent.com/assets/16940931/14178150/5acf6542-f727-11e5-8491-286f74bd745f.jpg)

**Comment by weems** [comment]
Addressed in PR. https://github.com/bbondy/abp-filter-parser-cpp/pull/26
