### ISSUE TITLE
Error retrieving promotion Error: HTTP response 404 for GET /v1/grants on clean profile

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12080]
### Description
Error retrieving promotion Error: HTTP response 404 for GET /v1/grants on clean profile

### Steps to Reproduce

  1. Clean install 0.19.96
  2. Launch from console
  3. Enable payments, no claim tokens notification shown
  4. Console shows error 404

**Actual result:**
![404 clean profile](https://user-images.githubusercontent.com/17010094/33176292-7d2e1142-d056-11e7-8c23-3acfabfd6290.gif)

**Expected result:**
Should not fail on clean profile

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.96
-- | --
rev | 9d72944
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
N/A

### Additional Information
#12074
cc: @evq @NejcZdovc

**Comment by kjozwiak** [comment]
Also reproducible on both macOS and Linux.... Once you've enabled `Payments`, you'll get the following errors as @srirambv mentioned above:

```
<<< GET https://ledger-staging.mercury.basicattentiontoken.org/v1/grants
<<< content-type: application/json; charset=utf-8
<<< accept-encoding: 
<<<
[ response for GET https://ledger-staging.mercury.basicattentiontoken.org/v1/grants ]
>>> HTTP/1.1 404 
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 74
>>> content-type: application/json; charset=utf-8
>>> date: Thu, 23 Nov 2017 15:42:33 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1511451813
>>>
>>> {"statusCode":404,"error":"Not Found","message":"no promotions available"}
```

**Comment by NejcZdovc** [comment]
@evq is it possible that we already react some limit?

**Comment by NejcZdovc** [comment]
we were using staging a lot :smiley:

**Comment by NejcZdovc** [comment]
just tried it on my machine and it's not working anymore (it was working few hours ago, with the same code), so I guess we spend it all :moneybag:

**Comment by evq** [comment]
yeah we ran out of grants lol. i'll load a bunch in a bit

**Comment by NejcZdovc** [comment]
closing this one as @evq added more grants
