### ISSUE TITLE
Netflix missing component error 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12085]
### Description
Netflix missing component error 

### Steps to Reproduce
 
  1. Clean install 0.19.101
  2. Visit Netflix and play a video 
  3. Throws missing component error

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/33187069-fd579548-d086-11e7-9fa6-85b90bd8a5c9.png)

**Expected result:**
Should stream video

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.101
-- | --
rev | 30c42b5
Muon | 4.5.18
libchromiumcontent | 63.0.3239.40
V8 | 6.3.292
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No. Works fine on 0.19.95

### Additional Information
#11928
cc: @bbondy 
Same issue on mac verified by @kjozwiak

**Comment by darkdh** [comment]
Widevine will allow us to download it when Chrome stable upgrade to chromium 63.
If you want to test before that, you can append `--component-updater=test-request` and launch from command line

Mac:
`open /Application/Brave.app --args --component-updater=test-request`

Win:
`"Location of exe" --component-updater=test-request`

**Comment by srirambv** [comment]
Works with `--component-updater=test-request` parameter on Windows
