### ISSUE TITLE
Geo location fails to retrieve location

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12087]
# Test plan
    1. Clean install 0.19.101
    2. Visit https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
    3. Click on Show my location should show the user location
# 

### Description
Geo location fails to retrieve location

### Steps to Reproduce
  1. Clean install 0.19.101
  2. Visit https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
  3. Click on Show my location, shows `Unable to retrieve your location`

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/33187552-778eb00a-d08a-11e7-99c1-7542e410594d.png)

**Expected result:**
Should show location

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.101
-- | --
rev | 30c42b5
Muon | 4.5.18
libchromiumcontent | 63.0.3239.40
V8 | 6.3.292
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
Reproed on mac and Linuxby @kjozwiak

**Comment by bridiver** [comment]
chromium no longer provides a way to override the geolocation url - need to look at alternatives

**Comment by srirambv** [comment]
Working on 0.19.106
