### ISSUE TITLE
Browser randomly crashes

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12088]
### Description
Browser randomly crashes when in background

### Steps to Reproduce
  1. Clean install 0.19.101
  2. Open couple of tabs 
  3. Background brave and make other application active
  4. Browser crashes without errors

**Actual result:**
Browser randomly crashes when in background

**Expected result:**
Should not crash 

**Reproduces how often:**
Intermittent

### Brave Version

**about:brave info:**

Brave | 0.19.101
-- | --
rev | 30c42b5
Muon | 4.5.18
libchromiumcontent | 63.0.3239.40
V8 | 6.3.292
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
Same behavoiur confirmed on mac and Linux  by @kjozwiak

**Comment by kjozwiak** [comment]
Doesn't necessarily have to be in the background... I've had Brave crash on me at least 10 different times tonight while I was going through the manual regression passes.

I watched a few YT videos and it randomly crashes on me a few times as well.

**Comment by bridiver** [comment]
is this windows only?

**Comment by kjozwiak** [comment]
> is this windows only?

It's reproducible on all the platforms (Ubuntu/Win/macOS). It's pretty easy to reproduce as it happens pretty often once Brave has been running for a few minutes. The easiest way to reproduce the issue is simply running Brave and leaving it idle.. Eventually it will crash one you.

**Comment by srirambv** [comment]
Looks fixed on Windows with 0.19.102. Hasn't crashed either with Brave in background or active window. Still needs verification on mac and Linux

**Comment by srirambv** [comment]
Closing as its working on Windows for 0.19.106.

cc: @kjozwiak @LaurenWags to verify on mac and Linux

**Comment by kjozwiak** [comment]
Haven't seen a random crash while using `0.19.107`... It was pretty noticeable before as the browser would randomly crash every few minutes making it unusable.
