### ISSUE TITLE
pdf.js not loading PDF's within the browser

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12089]
### Description

When loading a PDF directly into the URL, you'll receive a `Your file was not found` page error and when clicking on an external PDF link, you'll be asked to download the PDF rather than opening it within the browser.

Disabling/Enabling PDF.js from `about:preferences#extensions` and restarting the browser didn't help either.

### Steps to Reproduce

  1. load https://bitcoin.org/bitcoin.pdf within the URL bar (PDF not being loaded)
  2. search for `BTC pdf` within Google and click on the first search result (should be the PDF)
  3. you'll be asked to download the PDF rather than opening it within the browser

**Actual result:**

PDF's are not being displayed/loaded within the Brave browser.

<img width="1043" alt="screen shot 2017-11-23 at 3 25 02 pm" src="https://user-images.githubusercontent.com/2602313/33187806-81d8488c-d062-11e7-905f-08ab096ec11d.png">

**Expected result:**

PDF's should be loaded within the Brave browser.

**Reproduces how often:**

100% reproducible when using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.101 
> rev: 30c42b5435b9169b528226608973ddd22679ed59 
> Muon: 4.5.18 
> libchromiumcontent: 63.0.3239.40 

**Reproducible on current live release:**

Nope, looks like a C63 regression.

### Additional Information

* macOS 10.12.6 x64 - Reproduced
* Win 10 x64 - Reproduced by @srirambv 
* Ununtu 17.10 x64 - Reproduced

**Comment by srirambv** [comment]
Seems to be fixed on Windows for 0.19.103. PDF loads properly

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/muon/commit/fd36d1ab79b08d915eeb284643602442ed495dbc

**Comment by Corporate-Solutions** [comment]
Persistent issue in Android.  Just downloaded Brave to tablet two days ago.  No PDFs.  As if reader is not native.
