### ISSUE TITLE
loading unsafe unscripts via active mixed content doesn't always turn the page red under badssl.com

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12095]
### Description

Sometimes loading "Unsafe Scripts" from https://mixed-script.badssl.com/ doesn't turn the page red.

### Steps to Reproduce

  1. load https://mixed-script.badssl.com/
  2. click on the "lock" icon under the URL bar
  3. click on "Load Unsafe Script" (page should turn red)
  4. click on "Stop Loading Unsafe Scripts (page should turn grey)
  5. repeat step 3-4 several times and you'll notice that you'll get into a state where loading the unsafe script won't turn the page red

**Actual result:**

Loading unsafe scripts from https://mixed-script.badssl.com/ doesn't always turn the page red.

![mixedcontent](https://user-images.githubusercontent.com/2602313/33199654-21524ea6-d0bf-11e7-9c4e-1696620bad15.gif)

**Expected result:**

When loading unsafe scripts, the page should be turning red.

**Reproduces how often:**

100% reproducible when going through the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.95 - Reproducible
> rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94 

> Brave: 0.20.7  -Reproducible
> rev: a2ba3e8c4c86f029b73b47c8185e9e851825e04a 
> Muon: 4.5.16
> libchromiumcontent: 62.0.3202.94

**Reproducible on current live release:**

Yes, currently reproducible using `0.19.95` which is the current release.

### Additional Information

* macOS 10.12.6 x64 - Reproduced
* Win 10 Pro x64 - Reproduced
* Ubuntu 17.10 x64 - Reproduced

CC'ing @diracdeltas

**Comment by diracdeltas** [comment]
cannot repro on mac (tried 46b538714343d64dcb9020210bc534fc3e746695 and 0.19.105). at least if the page is grey, it means unsafe scripts are still being blocked so this is not a large security problem.

**Comment by kjozwiak** [comment]
@diracdeltas I can still reproduce this with `0.19.105`, it sometimes takes 10-15 attempts to reproduce. The main concern is that the page appears grey, but the page is still loading unsecured scripts:

<img width="1396" alt="screen shot 2017-12-06 at 5 11 00 pm" src="https://user-images.githubusercontent.com/2602313/33688218-a7a98986-daa8-11e7-94cc-d0ac580fbd00.png">

You'll notice that the tab is still appearing red and the lock info says that page is still loading scripts from an insecure source.
