### ISSUE TITLE
Claim token button should be hidden if a wallet is recovered with ugp token

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12098]
### Description
Claim token button should be hidden if a wallet is recovered with ugp token

### Steps to Reproduce 
   1. Clean install 0.19.96
   2. Create wallet and claim ugp tokens
   3. Backup wallet and clear browser profile
   4. Create a new browser profile
   5. Enable wallet and recover the wallet from step 3 
   6. Claim free token button is still shown, clicking on the button shows promotion not available

**Actual result:**
```
>>> {"statusCode":422,"error":"Unprocessable Entity","message":"promotion already in use"}
Problem claiming promotion Error: HTTP response 422 for PUT /v1/grants/51245323-b45b---ee0584e183de 
```

**Expected result:**
If wallet already contains ugp tokens, claim token button should not be shown

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.96
-- | --
rev | 9d72944
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
N/A

### Additional Information
Confirmed by @LaurenWags on macOS

**Comment by NejcZdovc** [comment]
this has the same fix as #12075

**Comment by LaurenWags** [comment]
Still seeing issue as described on MacOS, Win & Ubuntu (confirmed by @kjozwiak )

**Comment by bsclifton** [comment]
Closing for now- let's retest once builds are available

**Comment by NejcZdovc** [comment]
this is not yet fixed

**Comment by kjozwiak** [comment]
Test Cases Used:

* imported wallet that included UGP tokens, ensured that the button as been removed
* imported a wallet that didn't include UGP tokens, ensured that the button wasn't removed
* ensured that I could still claim UGP tokens when importing wallet that didn't have UGP tokens and the button was removed once UGP has been claimed
* ensured that the button as been removed when claiming UGP in a new wallet
