### ISSUE TITLE
No icon for Brave in Cinnamon panel (Linux Mint)

### ISSUE THREAD

**Issue by ham1** [brave/browser-laptop#1209]
Running 0.8.2 on Linux Mint 17.3:

![image](https://cloud.githubusercontent.com/assets/3393038/14180692/16446050-f75c-11e5-919c-852e39f6160f.png)

**Comment by majomuchi123** [comment]
Hope this helps, #1235

**Comment by luixxiul** [comment]
Please let me know if the issue persists in spite of the PR.

**Comment by luixxiul** [comment]
Confirmed. 

![](https://cloud.githubusercontent.com/assets/3362943/15769829/a25f617e-2999-11e6-9eb5-c8bbd02f8197.jpg)

**Comment by ham1** [comment]
No longer an issue for me on Mint.

**Comment by luixxiul** [comment]
Thanks, let me close the issue.
