### ISSUE TITLE
text case needs to be updated on Payments page

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12099]
### Description
L in 'CLaim' needs to be lowercase.

### Steps to Reproduce

  1. Clean profile on UGP build.
  2. Wait for notification and then click 'I'm Ready'
  3. View Payments page.

**Actual result:**
![screen shot 2017-11-24 at 12 14 03 pm](https://user-images.githubusercontent.com/28145373/33220023-90ca3e48-d113-11e7-953c-7cda292bf7be.png)

![claim](https://user-images.githubusercontent.com/28145373/33220026-950ee9ae-d113-11e7-9d71-e9d0c797b6df.gif)

**Expected result:**
 CLaim should be Claim.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave | 0.19.98
rev | 1909179
Muon | 4.5.16

**Reproducible on current live release:**
no

**Comment by evq** [comment]
this should be fixed server side, let me know if the fix is working browser side @LaurenWags 
thanks!

**Comment by LaurenWags** [comment]
lgtm, thanks @evq 

![screen shot 2017-11-24 at 2 53 35 pm](https://user-images.githubusercontent.com/28145373/33222737-51db0be0-d127-11e7-8a6b-c1cef6ea8c30.png)

**Comment by kjozwiak** [comment]
Waiting for a new build as per #12123 to finish verification on both Win and Linux. Currently, the Payments Info page looks like the following:

`Map { "message": List [ "To start using Brave Payments and accept your tokens, simply flip the switch at the top of this window and then choose \"Claim my free Tokens\".", "The rest is easy." ], "title": "Brave has created a simple way for you to contribute to the sites you use most." }`
