### ISSUE TITLE
tearing & attaching tabs not working correctly

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12092]
### Description

When tearing off tabs, the window that the tab was torn from isn't being correctly updated to show the new state of the toolbar. The tab that was moved will now appear as a separate window (expected) and still be listed in the initial windows toolbar (unexpected). Once you change focus to the original window, the tab that was moved will disappear from the toolbar as expected.

With the latest `0.19.107` build, it seems like tearing/reattaching tabs as completely regressed. When attempting to reattach a tab within `0.19.107`, all the windows will turn completely white (Example 2 below) and Brave will eventually crash.

### Steps to Reproduce

  1. launch `0.19.107` which includes C63
  2. open several different tabs (FB, Twitter, Brave, DuckDuckGo, etc..)
  3. tear off one of the tabs into it's own separate window
  4. attempt to reattach the tab

You'll notice that the original window that the tab was moved from hasn't correctly updated the tab bar to show the new state.

**Actual result:**

Tearing off tabs doesn't update the original window state

**Example 1:**

![movingtabs](https://user-images.githubusercontent.com/2602313/33197155-b417fd3e-d0b1-11e7-9d69-0180ec4ba246.gif)

**Example 2:**

![attachingtabs](https://user-images.githubusercontent.com/2602313/33629475-282192d4-d9d2-11e7-84f7-26051f77f225.gif)

**Expected result:**

The toolbar on the original window should be update instantly once the tab as been torn off.

**Reproduces how often:**

100% reproducible using the STR mentioned above.

### Brave Version

**about:brave info:**

> Brave: 0.19.101 
> rev: 30c42b5435b9169b528226608973ddd22679ed59 
> Muon: 4.5.18 
> libchromiumcontent: 63.0.3239.40 

> Brave: 0.19.107 
> rev: 54a209f96441d646585c510dadf6eac96cb2d5c3 
> Muon: 4.5.21 
> libchromiumcontent: 63.0.3239.59 

**Reproducible on current live release:**

Not reproducible under `0.19.95` which 

### Additional Information

* macOS 10.12.6 x64 - Reproduced
* Ubuntu 17.10 x64 - Couldn't Reproduce
* Windows 10 Pro x64 - Couldn't Reproduce

**Comment by srirambv** [comment]
Still reproduced on Windows. Trying to reattach causes window crashed  and causes white screen
```
[1205/202656.051:ERROR:process_info.cc(632)] range at 0x6b265a0600000000, size 0x194 fully unreadable
[1205/202656.051:ERROR:process_info.cc(632)] range at 0x0, size 0x194 fully unreadable
Window crashed. Reloading...
```

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/cdeecd9c9110ffe99aba4c9b8cc075cef56e8023
muon 4.5.22
