### ISSUE TITLE
browser randomly crashing when quitting application

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12093]
### Description

Sometimes when you quit Brave, you'll receive a "Brave quit unexpectedly" crash. 

### Steps to Reproduce

  1. open `0.19.101` which includes C63
  2. use brave for several minutes and quit

Unfortunately I don't have STR that can reproduce the issue 100% but this happens pretty often and shouldn't be hard to reproduce. I've seen the crash happen at least a dozen times within ~20min.

**Actual result:**

Brave sometimes crashes when quitting.

![crashingshutdown](https://user-images.githubusercontent.com/2602313/33197660-d19b3e04-d0b4-11e7-9439-ffe52f8cce4f.gif)

**Expected result:**

Brave shouldn't be crashing when quitting.

**Reproduces how often:**

You can reproduce the issue above about 30% of the time when following the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.101 
> rev: 30c42b5435b9169b528226608973ddd22679ed59 
> Muon: 4.5.18 
> libchromiumcontent: 63.0.3239.40 

**Reproducible on current live release:**

Definitely not reproducible in `0.19.95` or we would have heard it by now from the community.

### Additional Information

Possibly related to the random crash in #12088

**Comment by capouch** [comment]
I just played around a bit with 101 before seeing this issue.  It is NOT just upon quitting the browser; it crashed on me twice in 10 minutes, both times on different site in the active tab, and both times as I was just sitting and idly perusing a page's contents. 

Environment Linux Slackware 14.x-current.

**Comment by kjozwiak** [comment]
Thanks for the info @capouch! #12088 has already been created to address the random crashing that you're seeing. It's possible that the cashes in both #12088 and #12093 might be the same bug.

**Comment by srirambv** [comment]
Doesn't seem to happen on Windows for 0.19.103.

**Comment by kjozwiak** [comment]
Haven't seen it happen with `0.19.107` either.... It was pretty noticeable before and the crashes happened pretty often making it impossible to use Brave for more then 15-20mins. Looks like this has been addressed/fixed.
