### ISSUE TITLE
back and forward buttons disappear

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#12103]
### Description
Occasionally I will go to a webpage, such as youtube, search for a video topic, click on a video, watch it, and then want to go back to my original search to watch other related videos...  but I can't because the "< >" navigation buttons are GONE!

### Steps to Reproduce
It happens fairly often to me, but I cannot find a specific group of actions that will always make it happen.

### Brave Version

**about:brave info:**
0.19.95

**Comment by luixxiul** [comment]
Do you happen to take a screenshot when you experience that? thanks!

**Comment by bsclifton** [comment]
We haven't been able to reproduce and there haven't been other reports of this, unfortunately. Are you still experiencing this, @patrick99e99? 

I'm going to close the issue for now- please do reopen if you still see this. More specific steps to reproduce or more info (ex: a screenshot) would be very helpful in trying to diagnose the issue
