### ISSUE TITLE
First notification bar is not dismissed when payment is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12100]
### Test plan
See https://github.com/brave/browser-laptop/pull/11874

### Description
First notification bar is not dismissed when payment is enabled

### Steps to Reproduce
  1. Clean install 0.19.98
  2. Open preferences and enable payments and disable before 15 seconds when the first ugp notification is shown
  3. Enable payments again, second notification is stacked below the first notification

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/33220180-2df7f4f6-d13e-11e7-8b7f-6a940b9eff19.png)

**Expected result:**
First notification should be dismissed if payment is enabled

**Reproduces how often:**
Easy

### Brave Version

**about:brave info:**

Brave | 0.19.98
-- | --
rev | 1909179
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
n/a

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11874
