### ISSUE TITLE
YouTube doesn't get excluded after heartbeat is received

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12101]
### Description
YouTube doesn't get excluded after heartbeat is received

### Steps to Reproduce
  1. Clean install 0.19.98
  2. Enable payments, claim tokens
  3. Visit YouTube and play any video
  4. YouTube channel and YouTube gets added but after the first heart beat YouTube isn't excluded

**Actual result:**
YouTube doesn't get excluded after heartbeat is received

**Expected result:**
Excluded publisher should not be included in ledger table

**Reproduces how often:**
Easy

### Brave Version

**about:brave info:**

Brave | 0.19.98
-- | --
rev | 1909179
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
Not happening on Windows x64 on 0.19.95

### Additional Information
@kjozwiak wasn't able to repro the issue on Windows/Ubuntu

**Comment by NejcZdovc** [comment]
@srirambv can you please try again this one on the latest version

**Comment by srirambv** [comment]
Unable to reproduce on the latest release. Closing the issue for now.
