### ISSUE TITLE
some publishers not appearing as verified under the ledger table

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12106]
### Description

DDG isn't being marked as a verified publisher under the ledger table when using `0.19.98`. I checked `0.19.95` which is the latest released build and the verified icon is correctly being displayed.. Regressed between `0.19.95` & 0.19.98`.

### Steps to Reproduce

  1. launch `0.19.98` and enable payments via `about:preferences#payments`
  2. once enabled, visit DDG and spend some time there (~1-2 mins)
  3. revisit `about:preferences#payments` and you'll notice that DGG is not being marked as verified

**Actual result:**

DDG isn't being marked as a verified publisher within the ledger table.

**Expected result:**

DDG should have the verified icon next to the entry within the ledger table.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.98 
> rev: 1909179d9b538dad5074a2631f10e16ea1996de1 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94 

**Reproducible on current live release:**

Couldn't reproduce it under `0.19.95`... The verified icon appears next to DDG.

### Additional Information

Reproduced on the following platforms:

* Win 10 Pro x64 - Reproduced
* Ubuntu 17.10 x64 - Reproduced
* macOS 10.12.6 x64 - Reproduced

CC'ign @mrose17 @evq

**Comment by kjozwiak** [comment]
@srirambv & @LaurenWags.... can you guys check this on your end and make sure you can reproduce?

**Comment by NejcZdovc** [comment]
@kjozwiak can you please add this two steps to your STR and try again
4) open new tab and visit one different site
5) go back to payments and check if check is there

**Comment by srirambv** [comment]
Verified DDG entry doesn't have verified icon in ledger table

STR
1. Enable payments
2. Visit DDG in a new tab and stay on the tab for >10sec
3. Switch to payments, has an entry for DDG but doesn't have verfiied icon
4. Open a new tab and visit a different site stay for ~8 secs
5. Go back to payments, still no verified icon for DDG

**Comment by kjozwiak** [comment]
Thanks for taking a look @srirambv!

> @kjozwiak can you please add this two steps to your STR and try again
> 4) open new tab and visit one different site
> 5) go back to payments and check if check is there

@NejcZdovc I went through the above several times before creating the bug as well... Went through some of these cases and still couldn't get the verified icon to appear:

* restarted the browser several times
* disabled/enabled payments several times
* revisited DDG in different tabs several times
* close DDG, visited several other websites before checking the ledger table again

**Comment by LaurenWags** [comment]
I can confirm I see the same as @srirambv using steps from https://github.com/brave/browser-laptop/issues/12106#issuecomment-347178543

**Comment by mrose17** [comment]
when i go to

    https://ledger.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=duckduckgo.com

i get back

    {
      "TLD": "com",
      "SLD": "duckduckgo.com",
      "RLD": "",
      "QLD": "",
      "publisher": "duckduckgo.com",
      "properties": {
        "timestamp": "6489171250353537031",
        "verified": true
      }
   }

so i am investigating further.

**Comment by mrose17** [comment]
![0](https://user-images.githubusercontent.com/400552/33336564-3a7fcf70-d425-11e7-8be2-ae818deb2a48.png)

**Comment by mrose17** [comment]
who can duplicate this (it works for me!), please start the browser with `LEDGER_VERBOSE=true` and capture the output. i want to see what this says:

    [ response for GET https://mercury-proxy.privateinternetaccess.com/v3/publisher/identity?publisher=duckduckgo.com ]
    >>> HTTP/1.1 200 
    >>> accept-ranges: bytes
    >>> cache-control: private
    >>> connection: keep-alive
    >>> content-length: 148
    >>> content-type: application/json; charset=utf-8
    >>> date: Tue, 28 Nov 2017 18:16:23 GMT
    >>> server: Cowboy
    >>> strict-transport-security: max-age=31536000
    >>> vary: accept-encoding
    >>> via: 1.1 vegur
    >>> x-rate-limit-limit: 9007199254740991
    >>> x-rate-limit-remaining: 9007199254740989
    >>> x-rate-limit-reset: 1511892984
    >>>
    >>> {"TLD":"com","SLD":"duckduckgo.com","RLD":"","QLD":"","publisher":"duckduckgo.com","properties":{"timestamp":"6489171250353537031","verified":true}}

**Comment by kjozwiak** [comment]
@mrose17  using `0.19.98`, I'm getting the following when visiting DDG:

```
[ response for GET https://ledger-staging.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=duckduckgo.com ]
>>> HTTP/1.1 200 
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 99
>>> content-type: application/json; charset=utf-8
>>> date: Tue, 28 Nov 2017 18:24:51 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1511893551
>>>
>>> {"TLD":"com","SLD":"duckduckgo.com","RLD":"","QLD":"","publisher":"duckduckgo.com","properties":{}}
```

Seems like the properties are missing... Could this be a Staging vs Production issue?

**Comment by mrose17** [comment]
i believe so. let me update staging. brb.

**Comment by srirambv** [comment]
Same on Windows as well for me running 0.19.98
```
[ response for GET https://ledger-staging.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=duckduckgo.com ]
>>> HTTP/1.1 200
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 99
>>> content-type: application/json; charset=utf-8
>>> date: Tue, 28 Nov 2017 18:28:22 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1511893762
>>>
>>> {"TLD":"com","SLD":"duckduckgo.com","RLD":"","QLD":"","publisher":"duckduckgo.com","properties":{}}
<<< GET https://balance-staging.mercury.basicattentiontoken.org/v2/wallet/363b2537-0eac-4a9a-83f0-77e3854223be/balance
<<< content-type: application/json; charset=utf-8
<<< accept-encoding:
<<<
```

**Comment by NejcZdovc** [comment]
correct on 0.19.98 we are using staging server

**Comment by mrose17** [comment]
i have updated the staging server.

**Comment by srirambv** [comment]
Seeing verified icon for DDG now on 0.19.98
```
[ response for GET https://ledger-staging.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=duckduckgo.com ]
>>> HTTP/1.1 200
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 148
>>> content-type: application/json; charset=utf-8
>>> date: Tue, 28 Nov 2017 19:06:47 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1511896067
>>>
>>> {"TLD":"com","SLD":"duckduckgo.com","RLD":"","QLD":"","publisher":"duckduckgo.com","properties":{"timestamp":"6489171250353537031","verified":true}}
```
