### ISSUE TITLE
URLs of the tiles on the Dashboard are logged on History

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12108]
### Description

URLs of the tiles on the Dashboard are logged on History.

### Steps to Reproduce

  1. Start the browser with a clean profile
  1. Open a new tab
  2. Go to https://github.com on the tab
  3. Pin the tab
  4. Close other 2 tabs (New Tab and about:welcome) with Control + W
  5. Another Control + W
  6. The browser is closed
  7. `$ brave`
  8. Control + Y

**Actual result:**

![clipboard01](https://user-images.githubusercontent.com/3362943/33258193-09045594-d39c-11e7-849d-9904fd18419f.png)

**Expected result:**

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.19.101 
rev: 30c42b5435b9169b528226608973ddd22679ed59 
Muon: 4.5.18 
libchromiumcontent: 63.0.3239.40 
V8: 6.3.292 
Node.js: 7.9.0 
Update Channel: nightly 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64

**Reproducible on current live release:**

No.

**Comment by kjozwiak** [comment]
I'm removing the `cr63` tag as I've seen this a few times in the past but could never reproduce the issue. I've talked to @bsclifton about this issue in the past and I'm pretty sure he mentioned that he's seen this before as well. This definitely existed before `cr63`.
