### ISSUE TITLE
Mouse cursor disappears often

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#12102]
### Description
Occasionally when switching between tabs, my mouse cursor will completely disappear.  I will have to move my mouse all over the screen, and eventually it will come back.

### Steps to Reproduce
Cannot find specific way to reproduce.

### Brave Version

**about:brave info:**
0.19.95

**Comment by luixxiul** [comment]
Is it ok to close this one and re-open this https://github.com/brave/browser-laptop/issues/10299 where you left a comment?

**Comment by bsclifton** [comment]
Closing as there have not been more reports and there are not specific steps to reproduce. Let's re-open if issue persists and/or if there are steps
