### ISSUE TITLE
Entire ledger should be sorted before display

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12119]
### Description
Naturally (ex: just by using Brave), the transactions shown in History under Preferences > Payments will be in order. The newest transactions will be at the top and the older ones towards the bottom.  However, you can (for testing purposes) generate a fake history which would put things in the wrong order (this was fixed with https://github.com/brave/browser-laptop/pull/12118)

The original sorting fix was done by @josiah-keller when fixing https://github.com/brave/browser-laptop/issues/11300 and works great.  However, it has the following problems:
- it runs each time the view is shown
- it only sorts what is stored in `ledgerData.get('transactions')`. If the state has things out of order, this could potentially leave out entries.  Thanks to @NejcZdovc for sharing this logic in `getStateInfo`:
  https://github.com/brave/browser-laptop/blob/9da47f43e115281e30dc2452fe458e8fadff6a42/app/browser/api/ledger.js#L1333-L1335

  If the timestamp is older than a year, the for loop stops ☹️ 
  https://github.com/brave/browser-laptop/blob/9da47f43e115281e30dc2452fe458e8fadff6a42/app/browser/api/ledger.js#L1382

The ideal fix would:
- run one time
- sort on startup

The change could go here:
https://github.com/brave/browser-laptop/blob/9da47f43e115281e30dc2452fe458e8fadff6a42/app/browser/api/ledger.js#L1782

`parsedData` contains the raw JSON blob for the `ledger-state.json`, which includes all the transactions.  The sort that was done in https://github.com/brave/browser-laptop/pull/12118 could be done here too, before the call to `getStateInfo`

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
yes- but only by hand-editing the `ledger-state.json`

### Additional Information

cc: @josiah-keller in case you wanted to give this one a shot 😄

**Comment by sergiorojasa** [comment]
@bsclifton Can I work on this bug.

**Comment by NejcZdovc** [comment]
@sergiorojasa sure, if you need you need any help don't hesitate to reach out. Thank you

**Comment by bsclifton** [comment]
+1 to what @NejcZdovc said!  Let us know if you have any questions, @sergiorojasa 😄 👍

**Comment by sergiorojasa** [comment]
@bsclifton What properties of the ledger-state.json do I hand-editing?

**Comment by sergiorojasa** [comment]
@bsclifton @NejcZdovc Should the sorting on parsedData affect the ledger-state.json or should I create a new array and fill the array element with the transaction in parsedData and then sort the new array and pass it to getStateInfo().

**Comment by NejcZdovc** [comment]
@sergiorojasa yeah I think that we should only sort data from parsedData when we read it

**Comment by bsclifton** [comment]
@sergiorojasa you can just modify `parsedData` directly before `getStateInfo` gets called 😄

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
