### ISSUE TITLE
Looks good!??

### ISSUE THREAD

**Issue by Magaly1956** [brave/browser-laptop#12117]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Hi @Magaly1956- I am guessing you are enjoying Brave 😄 

I'm going to close this issue as there is no action needed- but we for sure appreciate the feedback ❤️ 

Let us know if you have any questions or feedback.  You can also reach out via out forum at https://community.brave.com/
