### ISSUE TITLE
New tab shows a black layout before showing smooth fade-in transition 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12111]
### Description
New tab shows a black layout before showing smooth fade-in transition 

### Steps to Reproduce
  1. Clean install 0.19.98
  2. Open a new tab, shows black layout before an image is downloaded and shows smooth fade-in transition
  3. Note which image is downloaded, keep opening new tabs, Image loaded in step2  again shows up but still has the black layout for about 2 secs before showing smooth fade-in transition

**Actual result:**
New tab shows a black layout before showing smooth fade-in transition 

**Expected result:**
If image is already downloaded, then it should be cached and subsequent show of the image should not result in black layout

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.98
-- | --
rev | 1909179
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
Could be due to the fix for #11813 . Issue reproduced on mac by @LaurenWags 
cc: @petemill 
https://github.com/brave/browser-laptop/issues/6503

**Comment by petemill** [comment]
@srirambv when you say reproducible 100%, meaning you never get a cached image? Note that the background will always fade in over 0.5 seconds, after the page load. So, to be explicit:

Uncached image: image will start to fade-in after image downloads, fade-in will take 0.5 seconds
Cached image: image will start to fade-in almost immediately after page load, fade-in will take 0.5 seconds

**Comment by srirambv** [comment]
Cached image does appear to load under 0.5 seconds of fade-in transition. Working as expected so closing the issue
