### ISSUE TITLE
`npm install` fails on Ubuntu 14.04 with recent node/npm

### ISSUE THREAD

**Issue by bitemyapp** [brave/browser-laptop#1212]
```
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.6
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
```

**Comment by OlegKuts** [comment]
Same on Xubuntu 14.04
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
`

**Comment by bbnnt** [comment]
same here
ubuntu 15.10
node v5.10.1
npm 3.8.7

**Comment by allupaku** [comment]
Same here.. any update on this issue ?

**Comment by trustfarm-dev** [comment]
same on ubuntu 15.10

**Comment by gersonZaragocin** [comment]
The workaround used to solve this is to delete completely the **node_modules** folder and execute `npm install` again

**Comment by demipel8** [comment]
same on antergos (Arch Linux). The workaround isn't functioning for me

**Comment by h4nN** [comment]
Same Xubuntu 15.04.

**Comment by cpappen** [comment]
I'm with the same problem on ubuntu 16.04 beta.
Even deleting the folder** node_modules** and execute _npm install_ does'nt fixed the error for me.
nodejs v5.10.1
npm 3.8.6

**Comment by brunocascio** [comment]
Hi! this work for me:

`rm -rf node_modules/ && npm install && npm rebuild`

I'm using node **5.10** and npm **3.8.7**

**Comment by rnorden** [comment]
@brunocascio 
That didn't work for me.

npm ERR! Linux 4.4.6-201.fc22.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "fsevents"
npm ERR! node v0.10.42
npm ERR! npm  v3.8.7
npm ERR! code EBADPLATFORM

**Comment by brunocascio** [comment]
Hi @rnorden 
Maybe that is related with your kernel version (4.4.6-201).
I'm using 3.19.X Linux Kernel Version.

**Comment by mikela** [comment]
Hi, fsevents is for Mac OSX only, not Linux. https://www.npmjs.com/package/fsevents

**Comment by Citrullin** [comment]
Same issue in Babel. Why it's a dependency? oO

**Comment by luixxiul** [comment]
FWIW the solution that worked on Ubuntu 14.04.01 (clean install on VMware player): https://gist.github.com/luixxiul/e294f2e5ef5bdf5ab6910d8224a9b7a9

**Comment by luixxiul** [comment]
@bbondy Closing this with https://github.com/brave/browser-laptop/pull/1682?

**Comment by bbondy** [comment]
Let us know if there's still an issue after the update on the documentation just referenced, thanks.

**Comment by luixxiul** [comment]
Closing for a moment. If this is persistent please leave a log, thanks.

**Comment by luixxiul** [comment]
For the participants: the instruction for installation has been updated. Would you please retry following it on README and tell me if the error persists? If so I will reopen the issue. Thanks!

**Comment by mangar** [comment]
If you're running that on a CI server, try to remove the node_modules dir before run the npm install.
This worked for me.

**Comment by katlehotech** [comment]
Please help, this is important work stuff

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

**Comment by Citrullin** [comment]
@katlehotech It's a Mac specific thing. If you have a Linux/Windows System you don't need to care of it.

**Comment by bsclifton** [comment]
@katlehotech are you all using Brave at your work? (that would be cool) 🦁

**Comment by luc-chevaux** [comment]
Hi this works also for me on ubuntu 16.04 x64:

> rm -rf node_modules/ && npm install && npm rebuild

**Comment by jcsky** [comment]
`rm -rf node_modules/ && npm install && npm rebuild`
It's not work on ubuntu 16.04, node v7.7.2, npm 4.1.2

**Comment by luixxiul** [comment]
will you paste here what is the output of the error?

**Comment by Tomasz-Silpion** [comment]
Same problem

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
```

Ubuntu 16.04

**Comment by Tomasz-Silpion** [comment]
nvm, error is gone after updating node to the latest https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

**Comment by manjujidagi** [comment]
Same issue on Lubuntu 18.04

npm install --save-dev fsevents

npm ERR! Linux 4.15.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "fsevents"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /media/qrera/490A42B3186E319A/TASKS/qpulse_app/npm-debug.log

**Comment by cosmin** [comment]
fsevents isn't going to install on Linux because it's only designed for OS X, see the https://www.npmjs.com/package/fsevents

**Comment by Creative9991** [comment]
Can you please some one help me with the below error,
I am getting this error while i am building angular app, npm install and almost every time when i am using npm. 

npm ERR! path /home/user/.npm/_cacache/index-v5/9a/e4/c8b1b5f5ecdb3896ae63d10f31b93c6e3785501944906912db49c8ba02da
npm ERR! code Unknown system error -117
npm ERR! errno -117
npm ERR! syscall open
npm ERR! Unknown system error -117: Unknown system error -117, open '/home/user/.npm/_cacache/index-v5/9a/e4/c8b1b5f5ecdb3896ae63d10f31b93c6e3785501944906912db49c8ba02da'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-04-01T23_17_14_132Z-debug.log

**Comment by bsclifton** [comment]
Hi @Creative9991 -
Your issue is not related to Brave. You'll want to search StackOverflow or similar for more details about that error
