### ISSUE TITLE
Incorrect text on Brave Payments page

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12123]
### Description
Text on Brave Payments page isn't displaying properly.

### Steps to Reproduce

  1. Clean profile on 0.19.98
  2. Wait for banner notification, click Maybe Later
  3. Navigate to about:preferences#payments

**Actual result:**
Text under Brave Payments does not display properly
![payment_text](https://user-images.githubusercontent.com/28145373/33328960-670ff8fe-d429-11e7-9bf3-33f14dc5a9af.gif)

**Expected result:**
Text should be displayed without code.

**Reproduces how often:**
Easy

### Brave Version

**about:brave info:**
Brave | 0.19.98
rev | 1909179
Muon | 4.5.16

**Reproducible on current live release:**
no

**Comment by srirambv** [comment]
Reproduced on Windows as well.

**Comment by NejcZdovc** [comment]
this is ok now. We changed format on the server and we update UGP branch, but we didn't release new build. It will be fixed in new build.

**Comment by kjozwiak** [comment]
Ensured that the JSON data was being correctly pulled once the initial UGP notification was displayed using `LEDGER_VERBOSE=true`:

<img width="1338" alt="screen shot 2017-11-28 at 11 04 02 pm" src="https://user-images.githubusercontent.com/2602313/33357513-8a97f332-d490-11e7-9008-388b41215dc6.png">

Once the JSON data was pulled, ensured that the text was correctly being displayed under `about:preferences#payments`.
