### ISSUE TITLE
Copy to clipboard icon replaced with text on Add funds dialog

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12120]
### Description
Copy to clipboard icon replaced with text on Add funds dialog

### Steps to Reproduce
  1. Build from master
  2. Enable payments and click on Add funds button to bring up add funds dialog
  3. Copy to clipboard icon is replaced by text which overlaps on the QR code

**Actual result:**
![copytoclipboard](https://user-images.githubusercontent.com/17010094/33317374-d90500d0-d42e-11e7-9420-6ea1775b3727.gif)

**Expected result:**
Should show icon and tool tip should show `Copy to clipboard` text

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
1db0346 

**Reproducible on current live release:**
No

**Comment by luixxiul** [comment]
I see the button rendered on https://github.com/brave/browser-laptop/commit/9da47f43e115281e30dc2452fe458e8fadff6a42 on the payment page; if `copyButton` had the issue it would have not rendered on about:brave either. 

Would you please let me know how the element is like on devtool under `clipboardButton_1b4y7iu`? This one is mine:

<img width="565" alt="screenshot 2017-11-29 1 52 55" src="https://user-images.githubusercontent.com/3362943/33332617-10bb4d30-d4a8-11e7-85ac-730140fdc24f.png">

**Comment by NejcZdovc** [comment]
@srirambv can you please retest this one? I can't reproduce it

**Comment by srirambv** [comment]
Still reproducible on master
![clipboard](https://user-images.githubusercontent.com/17010094/36366036-3ebfbabc-1572-11e8-9383-19f15cbd8120.gif)

**Comment by NejcZdovc** [comment]
I think that this is specific to windows then

**Comment by srirambv** [comment]
Works on 0.21.x branch btw 
![clipboard1](https://user-images.githubusercontent.com/17010094/36366177-f2ab36e6-1572-11e8-98ce-f911f0a6f38d.gif)

**Comment by NejcZdovc** [comment]
@srirambv what about 0.22?

**Comment by NejcZdovc** [comment]
Well guess because it's the old issue, I think it was broken in 0.22

**Comment by srirambv** [comment]
0.22.x is on master so this is same on 0.22.x

**Comment by jasonrsadler** [comment]
@srirambv Can you retry. I can't reproduce on win10 pro 1709

**Comment by srirambv** [comment]
Looks fixed on master 
![12120](https://user-images.githubusercontent.com/17010094/39244023-5cf19eba-485d-11e8-822a-fa611c1ff565.gif)
 
and on 0.23.x
![12120_23](https://user-images.githubusercontent.com/17010094/39244317-5480af68-485e-11e8-916e-df5f5925cd14.gif)

Not sure whats fixed the issue but good to close it for now.
