### ISSUE TITLE
Contribution not happening & now overdue using BTC to BAT converted wallet

### ISSUE THREAD

**Issue by disfit** [brave/browser-laptop#12122]
My BAT wallet is the result of a troubled conversion from my previous BTC wallet. Two days ago my contribution was up and one or two days before that I received a notification to add funds to my wallet even though there was plenty of BAT to cover the contribution (see [issue #12078](https://github.com/brave/browser-laptop/issues/12078)).

The contribution date came and went without  a notification or indication that something was or was not happening. The day after (yesterday) the payment screen shows that the contribution is overdue:

![screenshot from 2017-11-28 08-27-45](https://user-images.githubusercontent.com/25134539/33324667-8cdeb4b8-d450-11e7-8c18-09b8d09a3cf5.png)

The BAT amount is the same since the BTC to BAT conversion: I have not added any funds.

In order to see if I could get something to happen, I switched payments off and on again. This gave me the old BTC wallet notification that my contribution of 10 USD was successful:

![screenshot from 2017-11-28 08-29-03](https://user-images.githubusercontent.com/25134539/33324889-280fdf70-d451-11e7-943d-eec88faed593.png)

I can repeat this behavior by again switching payments off and on. And when I look at the contribution history (a day later) I see that no new contribution has been made:

![screenshot from 2017-11-28 08-28-25](https://user-images.githubusercontent.com/25134539/33325137-c4636b12-d451-11e7-9efb-18280ae4c4c3.png)

It feels like the BAT wallet is not active or the contribution process is still pointed to the old BTC wallet which of course either no longer exists or at the very least has no funds attached to it.

I am currently using 0.19.95 on linux.

The troubled BTC to BAT conversion is well documented in PM's on the community board with @LaurenWags and she has my permission (hereby) to share this if necessary.

And of course I am willing to supply more information as well :-)

**Comment by LaurenWags** [comment]
cc @NejcZdovc @bsclifton

**Comment by bsclifton** [comment]
@disfit can you please try changing your amount? For example, change from 50 BAT to 25 BAT... and then back again (to 50 BAT).  If that doesn't have any effect, the next thing you can do is to run Brave via command line so that you can get more logs

`LEDGER_VERBOSE=true Brave | tee failed-settlement.log`

This will spit out a ton of messages to the logs- if you could save this file and share with me at `clifton@brave.com` I can help assist you further 😄  We direct settlements through a proxy and I suspect this may be blocked (ledger-proxy.privateinternetaccess.com)

**Comment by disfit** [comment]
@bsclifton I should have mentioned that I also tried to se if I could get things happen by changing the contribution amount. It had no effect. I will run the command line / log collection later tonight and mail it to you asap.

Many thanks and all the best :-)

**Comment by disfit** [comment]
And as an extra bit of information and for a bit of fun. At least, I can see the humor of this notification in the same screen as a funded wallet:

![screenshot from 2017-11-28 20-12-11](https://user-images.githubusercontent.com/25134539/33339311-01c18012-d479-11e7-859d-3aa745a449ef.png)

**Comment by bsclifton** [comment]
@disfit thanks for sharing your logs! I was able to see an error in the logs:
```
<<< GET https://mercury-proxy.privateinternetaccess.com/v2/surveyor/contribution/current/YOUR-GUID-HERE
<<< content-type: application/json; charset=utf-8
<<< accept-encoding: 
<<<
[ response for GET https://mercury-proxy.privateinternetaccess.com/v2/surveyor/contribution/current/YOUR-GUID-HERE ]
>>> HTTP/1.1 404 
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 103
>>> content-type: application/json; charset=utf-8
>>> date: Tue, 28 Nov 2017 19:27:51 GMT
>>> server: Cowboy
>>> strict-transport-security: max-age=31536000
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 9007199254740991
>>> x-rate-limit-remaining: 9007199254740990
>>> x-rate-limit-reset: 1511897272
>>>
>>> {"statusCode":404,"error":"Not Found","message":"personaId not valid: YOUR-GUID-HERE"}
```

To troubleshoot further, I'd need help from @mrose17 or @evq

**Comment by disfit** [comment]
Thanks to the Brave BAT giveaway I have something new to add to the weird and wonderful re this issue.

I was totally prepared to find out that something would not work and that the 30 BAT could not be added to my wallet, but it went through without a glitch and resulting in (compared with earlier above):

![screenshot from 2017-12-06 19-18-27](https://user-images.githubusercontent.com/25134539/33681467-ec1d4bfe-dac4-11e7-9687-09de8ef3536c.png)

I have no idea if this helps in finding the solution to the issue or not. It makes sense that a deposit can be made in the wallet and still not being able to make a contribution from the wallet. The first likely only needs the wallet ID / address, the second probably needs the personal key / ID that is only available in the browser. And which seems to be unavailable and/or superseded by the wrong or an old value.

Anyway: thanks for the BAT :-) Though I hope to be able to spend them soon.

**Comment by bsclifton** [comment]
Possibly fixed by https://github.com/brave/browser-laptop/pull/12204

**Comment by MatthewDLudwig** [comment]
You should check the backup code of your current wallet.  I was watching this bug for the answer until I saw that my backup code was "e".  I wish I had reported it then, but I just used the correct key for that converted wallet and now everything seems to be normal.  

Unfortunately though I didn't get to give last months payment as my wallet seems to think I'm no longer overdue.  There are no payments in the history and the balance didn't change (still had the givaway too).

**Comment by da2x** [comment]
I think I’ve got the same issue on three different computers (Linux, macOS, and Windows) no less. All had a BTC wallet, converted to Brave, claimed some free tokens, and then ended up with “Next contribution: Overdue”. Turning payments off and on again results in a notification toolbar, but nothing is deducted from my account balance. Payment history doesn’t contain any entries (although two of the machines had made payments in BTC in the past!), and changing the amount makes no difference.

**Comment by evq** [comment]
hey @da2x. did you have funds before accepting the free tokens on those computers?

there is a different known issue that can cause settlement to fail if there are not enough tokens to cover settlement (not counting free tokens that were accepted). currently we are not allowing settlement using free tokens (it is allowed anytime after 30 days from when we first made them available).

most users had their contribution date changed when they accepted the grant, however for earlier users who accepted tokens this did not happen. as a result they will see "overdue" until settlement using the free tokens is allowed.

**Comment by disfit** [comment]
Hi @bsclifton & @evq,

I just updated to 0.19.116 and got some progress (see below). I am running a verbose log and will report back when things happen (or when they do not). Again many thanks.

![screenshot from 2017-12-14 18-55-07](https://user-images.githubusercontent.com/25134539/34007135-048b3e34-e101-11e7-8269-ffa4a6ebf11b.png)

**Comment by bsclifton** [comment]
Thanks for the update, @disfit! 😄  You should see a payment go through in the next 10 - 20 minutes (if it hasn't already gone through by the time you're reading this).  Will stay tuned!

**Comment by disfit** [comment]
Hi @bsclifton,

Unfortunately the same error shows up in the verbose ledger log:

![screenshot from 2017-12-14 20-31-47](https://user-images.githubusercontent.com/25134539/34010663-db554020-e10d-11e7-8bd2-e5da08cb9d5b.png)


I recovered the wallet and restarted brave a couple of times with no effect. Switching the payments off and on again gives me the earlier reported old BTC notification (contribution of USD 10 has been processed). 

Let me know if you want the verbose ledger logs or if there is anything else you would like me to try.

**Comment by disfit** [comment]
Hi @bsclifton and others,

I seem to have solved my problem, though probably not in a way that helps you to solve the underlying issue. And I am not sure if I would recommend it to everybody with a similar issue> Simply because I have no idea if this will be a solution for all (similar) instances.

Due to the continuing error message on the personaId, I decided to try out the following:

1. Move of ~/.config/brave (OLD) to save location;
2. Complete removal of brave;
3. Restart PC
4. Install brave
5. Restore wallet
6. Close down brave
7. Move of the newly created ~/.config/brave (NEW) to a save location;
8. Copy back the OLD to ~/.config/brave
9. Replace the personaId and persona vars in the OLD ledger-state.json with the vars from the NEW ledger-state.json

![screenshot from 2017-12-19 08-17-32](https://user-images.githubusercontent.com/25134539/34164803-d1cc0c5c-e4da-11e7-9e79-e6ecefeb68b7.png)

10. Start brave
11. Wait for contribution process to kick in and gets confirmed, resulting in:

![screenshot from 2017-12-19 02-47-27](https://user-images.githubusercontent.com/25134539/34165023-73f72c00-e4db-11e7-9767-a8a077488d63.png)

and a bit later:

![screenshot from 2017-12-19 02-49-46](https://user-images.githubusercontent.com/25134539/34165040-81c9d422-e4db-11e7-8a28-6139deeec9f5.png)

I have not found or seen any errors or atypical behavior during or since the above. I will keep the backup of the OLD situation. If you do find a possible solution to the issue, I have no problems switching it back and test it. I also have the full verbose ledger log for steps 10 & 11 above if you think this can help you.

All the best and many thanks,

disfit

**Comment by bsclifton** [comment]
@disfit this is great! Thank you for being so patient and for troubleshooting the issue yourself (after our fixes didn't work).  This information is extremely helpful- cc: @LaurenWags, @kjozwiak 

@evq given the notes above, would it make sense to create an issue for detecting/fixing corruption?  It seems something about the ledger-state wasn't correct and creating a new one / hand editing the personaId fixed the issue

**Comment by bsclifton** [comment]
Closing issue as this individual case is solved. Based on the above comment, we can possibly create a new issue for detecting/fixing a bad state
