### ISSUE TITLE
Add Wallabagger extension

### ISSUE THREAD

**Issue by eriteric** [brave/browser-laptop#12125]
Was not able to find any mention of wallabag in the extension requests or issues.

### Description
This extension adds URLs to a wallabag account for read-later type functionality (similar to pocket). The difference is that wallabag can be self-hosted, and in my mind anyways probably appeals more to the brave user base than a freemium service. You can also annotate articles and have them read aloud to you, both of which are quite handy.

The chrome wallabagger extension can be found here:
https://chrome.google.com/webstore/detail/wallabagger/gbmgphmejlcoihgedabhgjdkcahacjlj

The firefox wallabagger extension can be found here:
https://addons.mozilla.org/en-US/firefox/addon/wallabagger/

**Comment by nicosomb** [comment]
FYI, we already discussed about wallabag here: https://github.com/brave/browser-laptop/issues/516

**Comment by eriteric** [comment]
Thanks. Agree, the SaaS option covers the non-techie adoption concern. www.wallabag.it I believe, is where it's accessible.

**Comment by pakman** [comment]
Just made a community post about this here: https://community.brave.com/t/wallabagger-extension/14197

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
