### ISSUE TITLE
Fingerprinting methods not properly blocked 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12121]
### Description
Fingerprinting methods not properly blocked 

### Steps to Reproduce

  1. Clean install 0.19.98, Enable block fingerprint from shields
  2. Visit https://audiofingerprint.openwpm.com/, Click on fingerprint, shows the audiofingerprint graph 
  3. Visit https://jsfiddle.net/bkf50r8v/13/, output shows got webgl and canvas fingerprint

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/33322928-cbcb780e-d442-11e7-9026-57f298aff9b9.png)
![image](https://user-images.githubusercontent.com/17010094/33322619-d6a70b68-d441-11e7-987c-722c0a56bdb4.png)

**Expected result:**
Should properly block all fingerprinting methods

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.98
-- | --
rev | 1909179
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
No, All fingerprinting methods are blocked on 0.19.95

### Additional Information
cc: @kjozwiak @LaurenWags

**Comment by diracdeltas** [comment]
may be due to https://github.com/brave/browser-laptop/pull/11784. @snyderp do you have time to take a look?

**Comment by snyderp** [comment]
Yep, I can see if these are related.  Will get back by the EOD at the latest

**Comment by snyderp** [comment]
@diracdeltas @srirambv Apologies, but after digging into this, I'm not sure I understand the issue.  I'm able to recreate the steps in the issue, but I don't understand which aspect is the bug / error.

For the audio fingerprinting, I'm getting the below:

```
Fingerprint using OscillatorNode:

0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...
Fingerprint using hybrid of OscillatorNode/DynamicsCompressor method:

0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
```

Which seems correct and also whats in the image in the issue.

For the JS fiddle, I'm getting 

```
fingerprinting test
got canvas fingerprint 0
got webgl fingerprint 00
```

which also seems like the expected value if shields are working correctly, and whats in the *Actual result* images.

W/o blocking, for example, I get:

```
fingerprinting test
got canvas fingerprint data:image/png;base64,… (truncated)
got webgl fingerprint ANGLE_instanced_arrays;… (truncated)
got webrtc fingerprint
```

Apologies if I'm missing something, but whats the success condition here?

**Comment by diracdeltas** [comment]
i think this is the success condition (nothing shown under 'fingerprinting test'):

![screen shot 2017-11-28 at 12 55 37 pm](https://user-images.githubusercontent.com/549654/33343809-8a6d2116-d43b-11e7-805a-fdfa6696ed6f.png)

@snyderp i agree this seems like probably not an actual bug but instead a situation where the success condition needs to be updated

**Comment by srirambv** [comment]
@snyderp For jsfiddle, it should only show `fingerprint test` in the output window. the output should be like this 
![image](https://user-images.githubusercontent.com/17010094/33343807-9827dd80-d47e-11e7-861a-60474afff839.png)

For audiofingerprint.openwpm.com, once the test is successful with thankyou message, it should not show the audio graph
![image](https://user-images.githubusercontent.com/17010094/33343862-c0c76c7e-d47e-11e7-80c0-4e50b9b7ec5b.png)

This is the expected behaviour.

**Comment by diracdeltas** [comment]
@srirambv 

for the jsfiddle, the manual test should actually be updated. if fingerprinting is working correctly, it will report 0's now instead of nothing in the jsfiddle output.

for the audiocontext fingerprinting test, i think the red line is some kind of calibration line, not the user fingerprint. the legend says that the blue line is the user fingerprint. so IIUC, fingerprinting protection is working as long as there is no blue line.

**Comment by diracdeltas** [comment]
^ confirming the above - the red line in the princeton test is a sample fingerprint. 

![screen shot 2017-11-28 at 1 07 19 pm](https://user-images.githubusercontent.com/549654/33344239-2748ea00-d43d-11e7-909e-5151ddd86638.png)

so i think this can be closed but the manual test plans need to be updated

**Comment by srirambv** [comment]
Thanks @diracdeltas  @snyderp  for confirming. Will close the issue and update the manual test plans.

**Comment by snyderp** [comment]
@diracdeltas I think the "blocks fingerprinting including WebGL" test might need to be updated too.  If that seems right to you too, I can give up looksie

**Comment by diracdeltas** [comment]
@snyderp can't remember if that needs an update since i thought it checks the number of FP stats, not the page content. also note that WebGL doesn't work in the Travis environment so the test condition in Travis is different. feel free to poke at it.
