### ISSUE TITLE
Only TOS text should be clickable

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12137]
## Test plan

https://github.com/brave/browser-laptop/pull/12140

----

### Description
Only TOS text should be clickable

### Steps to Reproduce

  1. Clean install 0.19.99
  2. Open payments
  3. Hover over TOS div, click anywhere on the div, opens TOS tab 

**Actual result:**
![bat-tos](https://user-images.githubusercontent.com/17010094/33398045-7f3383ac-d545-11e7-9b67-df1cb2fc7ca5.gif)

**Expected result:**
Only the TOS text should be clickable

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.99
-- | --
rev | 43f7a01
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
cc: @cezaraugusto @NejcZdovc

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.8 06c657b
•	Muon 6.1.5
•	libchromiumcontent 66.0.3359.181
