### ISSUE TITLE
Screenshot functionality similar to Mozilla

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12139]
### Description
Look here: https://screenshots.firefox.com/. It's best if you actually try it out in Mozilla.

Functions that are particularly useful includes:
- it's easier to select parts of a page just by clicking on them (then being able to modify them)
- capture a whole page
- share the page

**Comment by eljuno** [comment]
Related to #7554?

**Comment by jamesray1** [comment]
It's similar but my request is specifically to have the same functions in Firefox screenshots.

**Comment by bsclifton** [comment]
+1 from @JAD1932 via https://github.com/brave/browser-laptop/issues/13175

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1374
