### ISSUE TITLE
Hangouts does not work with Fingerprinting Protection enabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12144]
### Description
After https://github.com/brave/browser-laptop/issues/11683 was implemented, we saw that when logging into gmail with Fingerprinting Protection enabled, Google Hangouts doesn't work. You get a message saying that 'Something's not right. We're having trouble connecting to Google. We'll keep trying...' Additionally, the FP count continues to increase.
(initially noted here: https://github.com/brave/browser-laptop/issues/11683#issuecomment-347665009)

### Steps to Reproduce

  1. Enable FP in shields.
  2. Login to mail.google.com
  3. 

**Actual result:**
Hangouts displays a message:
![screen shot 2017-11-30 at 1 34 54 pm](https://user-images.githubusercontent.com/28145373/33448152-44b36bbe-d5d3-11e7-88cb-88e528dab2cf.png)

Additionally, Fingerprinting Methods Blocked count increases each time hangouts tries to connect.

**Expected result:**
Ideally hangouts should work normally when FP is enabled as it does in 0.19.95.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.104
rev | 07fb562
Muon | 4.5.16

**Reproducible on current live release:**
no, does not occur on 0.19.95

### Additional Information

cc: @snyderp @diracdeltas

**Comment by diracdeltas** [comment]
We are planning to revert https://github.com/brave/browser-laptop/pull/11784 so this would be fixed by that

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/fe2fcedfdca94aeb29351fdd2388a3dca23fcedd
