### ISSUE TITLE
All tooltips when brave opened are black

### ISSUE THREAD

**Issue by SudoLinux** [brave/browser-laptop#12148]
I am using Ubuntu mate and in the browser (latest version), and by tooltips I mean [ file, about, edit, etc ] at top bar, they are black, and I have a black background for my theme which looks ugly, when I minimize and maximize it removes tooltips which I guess fixes it. Please fix this! Thanks :)

**Comment by luixxiul** [comment]
Is this a same issue as https://github.com/brave/browser-laptop/issues/11109 ?

**Comment by SudoLinux** [comment]
@luixxiul Yes it is, any chances you are to fix and merge it? Thanks a lot!

**Comment by luixxiul** [comment]
Closing as duplicate of #11109. Let's track the issue there 😄
