### ISSUE TITLE
Promotion banners need a line break between text

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12145]
### Test plan
See https://github.com/brave/browser-laptop/pull/12153

### Description
Promotion banners need a line break between text

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/33450332-5f20afb8-d603-11e7-8ddc-25821e32ab95.png)
![image](https://user-images.githubusercontent.com/17010094/33450391-8bfbb884-d603-11e7-84ee-01baa3d26b17.png)

**Expected result:**
Should cover the payment info behind the banner

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.104
-- | --
rev | 07fb562
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
N/A

**Comment by bsclifton** [comment]
Fixed via https://github.com/brave/browser-laptop/pull/12153

**Comment by srirambv** [comment]
Line break is after the OK button 
![image](https://user-images.githubusercontent.com/17010094/33782267-e7633e20-dc4f-11e7-8366-7a5fac2d59f6.png)

**Comment by NejcZdovc** [comment]
@srirambv that's expected, because we are forcing min-height to this whole block.

**Comment by LaurenWags** [comment]
Verified Success and Network error banners on MacOS, unable to verify Promotion ended banner at this time.

**Comment by kjozwiak** [comment]
We'll need to ask @evq if we can turn off the promotion on the staging server quickly so we can test the final case.
