### ISSUE TITLE
Microsoft Surface -- Page Appears to Load but No Elements are Visible 

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1215]
_Page is Blank Yet Shows All Indications of Successfully Loading_

Bravery Menu Options Used in Testing on Microsoft Surface:
- Allow Ads and Tracking On
- Block 3rd Party Cookies Off
- HTTPS Everywhere Off

-Discovered when testing 0.8.3, but exists _at least_ as far as back as 0.8.1, perhaps even further. 

(Could also affect all Windows Versions though until personally testing that with a Desktop / Laptop Machine I will withhold judgment, OSX Version Loads Pages Fine).
@bbondy

**Comment by bbondy** [comment]
you're saying that no pages load at all? 
Or is there a specific site which doesn't load?

**Comment by weems** [comment]
None Load whatsoever.

**Comment by bbondy** [comment]
possibly also a corrupted data file.  Do the pages work fine when allow ads and tracking is on?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-investigation-brave-on-surface-4-pro/10224/2?u=suguru

Let's reopen if we get reports and could find steps to reproduce the issue 😄
