### ISSUE TITLE
Muted Media should be able to autoplay

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#12152]
## Test plan
1. Visited https://giphy.com/gifs/volkswagen-beetle-vw-3o6ozgHi0Fv82zA12M
2. We should default allow it without asking

**Comment by LaurenWags** [comment]
If you have your Autoplay Media set to 'Always Ask', and you visit https://giphy.com/gifs/volkswagen-beetle-vw-3o6ozgHi0Fv82zA12M, you are asked if you want to allow the video to play, but it is already playing:
![12152-a](https://user-images.githubusercontent.com/28145373/34578328-86d5e6ee-f152-11e7-8d6e-39ba730fdbb8.gif)

**Comment by darkdh** [comment]
this requires uplift some 0.20.x PRs 0.19.x
https://github.com/brave/browser-laptop/pulls?q=is%3Apr+milestone%3A%220.20.x+%28Beta+Channel%29%22+is%3Aclosed+label%3Afeature%2Fautoplay

**Comment by darkdh** [comment]
fixed by d81a458f6e9851a88045f8a336c0fb8b14cff4ed

**Comment by darkdh** [comment]
this will be reverted in 0.20.x

**Comment by kjozwiak** [comment]
@darkdh @bsclifton and myself had a quick chat. Because we're getting some user concerns on social media, this is going to be reverted in `0.19.x hotfix12`.

Clearing all the `QA Checked` flags so this can be retested once the change has been reverted from `muon` and a new `0.19.x` build becomes available sometime today.

**Comment by srirambv** [comment]
Test plan works fine on Windows

For test plan 1
Prompted notification when opened https://twitter.com/cricbuzz/status/951687708438552581 and https://www.cnet.com/news/oneplus-ceo-were-going-to-start-talking-to-us-carriers/ 
![12152-ask](https://user-images.githubusercontent.com/17010094/34861706-6fbf2638-f78c-11e7-9826-e346e596e0b3.gif)

For test plan 2 
Video notification didn't prompt when opened https://twitter.com/cricbuzz/status/951687708438552581 and https://www.cnet.com/news/oneplus-ceo-were-going-to-start-talking-to-us-carriers/ 
![12152-deny](https://user-images.githubusercontent.com/17010094/34861692-4e722e58-f78c-11e7-8683-1b772958bb10.gif)

For test plan 3
Media autoplayed when opened https://twitter.com/cricbuzz/status/951687708438552581 and https://www.cnet.com/news/oneplus-ceo-were-going-to-start-talking-to-us-carriers/ 
![12152-allow](https://user-images.githubusercontent.com/17010094/34861643-1ff2bb9c-f78c-11e7-9ff7-ebb8f3836abf.gif)

**Comment by srirambv** [comment]
Works on Linux as well. Followed the same steps as above^
