### ISSUE TITLE
Can't delete search terms or links.

### ISSUE THREAD

**Issue by BlackRabbit22** [brave/browser-laptop#12157]
Unsure if this isn't a feature or if it doesn't exist but whenever I search something in the search bar, and I want to delete it so that it won't come as an auto-suggestion in the url bar, it doesn't work.
The default for chromium, and chrome is shift+del. 
Clearing my browser history does not work either.

**Comment by luixxiul** [comment]
might be duping to https://github.com/brave/browser-laptop/issues/9094 ?

**Comment by BlackRabbit22** [comment]
Yes, its a duplicate.
