### ISSUE TITLE
Funds added to Brave wallet are not always displayed in Account Balance

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12150]
### Description
Some users from community are reporting that they fund their wallets with various currency but the funds do not display in their account balance.

### Steps to Reproduce

  1. Have Brave wallet
  2. Fund wallet (LTC or ETH)
  3. Funds do not display in account balance.

**Actual result:**
Funds are not displayed in Account Balance.

**Expected result:**
Funds should be visible in Account Balance.

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
0.19.95

**Reproducible on current live release:**
reported with current live release (0.19.95)

### Additional Information
Reported via community:
https://community.brave.com/t/eth-sent-to-brave-wallet-address-does-not-appear-in-brave-account-balance/11426
https://community.brave.com/t/i-transfered-5-in-eth-and-it-did-not-show-up-in-my-bat-balance/11152
https://community.brave.com/t/bat-auto-conversion-in-progress-for-days-now/9365/28

**Comment by bsclifton** [comment]
There were some difficulties earlier which have been resolved.  Customers affected by any outage will be fixed by @mrose17 😄

**Comment by NejcZdovc** [comment]
@LaurenWags is this still a problem?

**Comment by LaurenWags** [comment]
Can close per https://github.com/brave/browser-laptop/issues/12150#issuecomment-348548409
