### ISSUE TITLE
detach tab / new tab show garbled code

### ISSUE THREAD

**Issue by beenotung** [brave/browser-laptop#12169]
yes

### Description

When I press Ctrl + N to open a new tab in separate window, or when I drag a existing tab into new window, or when I right click a tab then click 'detach'. The original tab is disappeared, a new window of garbled code is shown (without url bar).

This do not always happens but it's not the first time.

### Steps to Reproduce

  1. Open Brave Browser
  2. Go to https://github.com/brave/browser-laptop/issues/new
  3. Press Ctrl + N
  4. See the bug

**Actual result:**
![1](https://user-images.githubusercontent.com/6007292/33577753-0043d7b6-d97f-11e7-9c81-a1109c8abf56.png)

A window of garbled code is displayed.

**Expected result:**
The original content of the tab should be displayed.

**Reproduces how often:**

When it happens, 100% reproducible for sub-sequence operation.
But it happens less than 10 times a week in general.

### Brave Version

**about:brave info:**

```
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.14.3-1-ARCH 
OS Architecture: x64
```

**Reproducible on current live release:**

Don't know.

### Additional Information

I am using awesome from startx directly (without DE)

archey3 output:
```
OS: Arch Linux x86_64
Hostname: BeenoTung-Archlinux-laptop-kudu
Kernel Release: 4.14.3-1-ARCH
Uptime: 7:22
WM: Awesome
DE: None
Packages: 1755
RAM: 3885 MB / 15936 MB
Processor Type: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
$EDITOR: vim
Root: 18G / 20G (90%) (ext4)
```

**Comment by beenotung** [comment]
This time it's showing javascript code.
Seems to be the same code when I press 'Ctrl + N' or tear off tabs
![1](https://user-images.githubusercontent.com/6007292/35746357-7d4db49e-0881-11e8-8928-113d2b8167bf.png)

Name | Version
-- | --
0 | Brave0.19.134
1 | rev316cfa522ffe6a558fe9f2f3f299c0c602dfb691
2 | Muon4.5.38
3 | libchromiumcontent63.0.3239.132
4 | V86.3.292.49
5 | Node.js7.9.0
6 | Update ChannelRelease
7 | OS PlatformLinux
8 | OS Release4.14.15-1-ARCH
9 | OS Architecturex64

**Comment by luixxiul** [comment]
Is it same on 0.20.x?

**Comment by beenotung** [comment]
@luixxiul so far this problem does not occur again (using Brave 0.20.46)

**Comment by bsclifton** [comment]
@beenotung thanks for letting us know you haven't experienced the problem again 😄 I'll go ahead and close this issue- let's re-open if it happens again. Thanks! 👍
