### ISSUE TITLE
Websites not loading

### ISSUE THREAD

**Issue by AwesomeTech10** [brave/browser-laptop#12162]
When I try to load a website, Brave doesn't load the site. I don't know why.

**Comment by bsclifton** [comment]
Closing as there is no action we can take ☹️ 

@AwesomeTech10 please re-open if you're able to list a few example URLs which are broken (screenshots are helpful too).  Did you try with shields down? (Lion in top right- can toggle on and off per domain). Some sites don't work when shields are enabled
