### ISSUE TITLE
usernames/passwords wiped out after update

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12167]
### Description
Some users in community and internally (@diracdeltas ) have reported that their usernames and passwords were wiped out after updating to 0.19.105. However, close/reopen of Brave seems to have resolved the issue. 
https://community.brave.com/t/my-saved-logins-and-passwords-are-gone-after-last-update/11476
https://community.brave.com/t/all-passwords-wiped/11596

### Steps to Reproduce

  1. Update from 0.19.95 to 0.19.105
  2.
  3.

**Actual result:**
In some cases usernames/passwords appear to be wiped out. Restart Brave and you see them again.

**Expected result:**
Usernames/passwords should be retained without restart of Brave.

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
0.19.105

**Reproducible on current live release:**
possibly, @diracdeltas mentioned she had seen this before.

### Additional Information
Possibly related to https://github.com/brave/browser-laptop/issues/12063, https://github.com/brave/browser-laptop/issues/12038

Reported cases thus far have been MacOS users.

Any usernames/passwords created when it looks like the usernames/passwords were lost are not retained after restart. (reported via community link above)

**Comment by diracdeltas** [comment]
The issue for me was that Brave could not access the keychain and did not prompt to do so. Closing/reopening did not fix the issue. I had to reboot.

**Comment by bsclifton** [comment]
This was a very specific issue that happened between Chromium 65 and Chromium 66 I believe. Since there haven't been any more reports or +1's, I'm going to close this issue as stale
