### ISSUE TITLE
Add v8-compile-cache

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#12168]
### Description
App startup can be slow  (related issue: https://github.com/brave/browser-laptop/issues/11944).
We can improve it by caching results of Module.compile to a tempfile for improved load times, using https://github.com/zertosh/v8-compile-cache. This should save a 100–300 ms on each load.

#### Measuring start time:

Log run time of app/index.js from 0 to perWindowStateLoaded ready = true
a. To L10 add:
const tStart = process.hrtime()
b. To L361 after ready = true add:

const tTime = process.hrtime(tStart)
console.log(`index.js window ready: ${tTime[0] * 1e3 + tTime[1] * 1e-6} ms`)
Start brave and record the run time.
Repeat

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/12006
