### ISSUE TITLE
Brave launches but isn't visible

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12163]
### Description

https://community.brave.com/t/launching-succeeds-but-doesnt-open/10417/8?u=suguru

> I should've replied sooner, but got caught with a bunch of other stuff.... anyways, I tried your solution and it still did not correct the issue for me. I re-downloaded Brave just to be met with the same issue. I did some further searching on the forum and came across this:
>
>> Brave, The Browser Itself Won't Open
>> QA, Bug Reports, Feedback
>> I fixed this by pressing shift+alt+space to maximize, then make the window smaller, it will disappear, then press shift+alt+space, the window will now be smaller and you can maximize and minimize, I don’t know why this fixes the bug, but it does. It’s not permanent, you have to do it every time, this bug really needs to be fixed.
>
> This worked for me, however there is still a bug present as this guy mentioned. If i go to minimize the screen the only way to have show back up on the screen is to do the shift-alt-space trick. I hope this helps.
>
> Brave support please fix this annoying bug!

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Closing as there hasn't been any updates to this issue and there aren't clear steps to reproduce. Please re-open if you experience this issue. Thanks! 😄
