### ISSUE TITLE
The dialog to enable insecure resources is not triggered

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12179]
### Description

The dialog to enable insecure resources is not triggered on https://mixed-script.badssl.com/

### Steps to Reproduce

  1. Open https://mixed-script.badssl.com/
  2. Click the lock icon

**Actual result:**

![bug](https://user-images.githubusercontent.com/3362943/33597446-cd11bfca-d9e2-11e7-899e-0059dc3400bf.png)

**Expected result:**

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.19.106 
rev: 88cb988a2796b81c391b4302c04a6fb9df4f979d 
Muon: 4.5.21 
libchromiumcontent: 63.0.3239.59 
V8: 6.3.292 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.9.0-4-amd64 
OS Architecture: x64

**Reproducible on current live release:**

No.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/6c2890dd52279ec22763da2023606686341ef8f4
muon 4.5.23

**Comment by kjozwiak** [comment]
@luixxiul can you check this on your end and see if this has been fixed for you? Working correctly using Ubuntu 17.10 x64 with `0.19.109`.

**Comment by luixxiul** [comment]
Fixed.
