### ISSUE TITLE
Blocked scripts are not counted

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12178]
### Description

Blocked scripts are not counted. Also the noScript icon is not displayed on the URL bar.

### Steps to Reproduce

  1. Open https://brianbondy.com/
  2. Toggle Block Scripts on the bravery panel

**Actual result:**

![bug](https://user-images.githubusercontent.com/3362943/33597256-2bd151d4-d9e2-11e7-8714-d0eba91c3cd3.png)

**Expected result:**

1. The number of the blocked scripts, which should be `3`, should be displayed
2. The noScript icon should be displayed on the URL bar

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

Brave: 0.19.106 
rev: 88cb988a2796b81c391b4302c04a6fb9df4f979d 
Muon: 4.5.21 
libchromiumcontent: 63.0.3239.59 
V8: 6.3.292 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.9.0-4-amd64 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/c307d77e3136f683d7e58c1d903a93b029d00c99
muon 4.5.23
