### ISSUE TITLE
URL bar unlock icon disappears by opening http://www.orimi.com/pdf-test.pdf

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12177]
### Description

URL bar icon disappears by opening http://www.orimi.com/pdf-test.pdf

### Steps to Reproduce

  1. Open http://www.orimi.com/pdf-test.pdf

**Actual result:**

![bug](https://user-images.githubusercontent.com/3362943/33594886-216fd52a-d9d9-11e7-85b8-017699405dfe.png)

**Expected result:**

The unlock icon should be displayed

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

Brave: 0.19.106 
rev: 88cb988a2796b81c391b4302c04a6fb9df4f979d 
Muon: 4.5.21 
libchromiumcontent: 63.0.3239.59 
V8: 6.3.292 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.9.0-4-amd64 
OS Architecture: x64

**Reproducible on current live release:**

No.

**Comment by srirambv** [comment]
Not specific to http. I see it on https links as well
![image](https://user-images.githubusercontent.com/17010094/33617612-1123f09e-d9d8-11e7-93af-7cc0869c85d0.png)

Some links show the icon and some doesn't

**Comment by darkdh** [comment]
fixed by brave/muon@cdeecd9
muon 4.5.22
