### ISSUE TITLE
displayed Brave wallet address and QR code do not have the same value after restoring wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12170]
## Test plan
1. Create a BAT wallet (does not have to have funds). Save recovery file for this wallet. 
  2. Set profile aside and create a clean profile.
  3. Enable payments, grab screenshots of wallet addresses and QR codes for currencies.
  4. restore wallet from step 1.
  5. Go to the Add Funds dialog and verify wallet addresses against QR codes. 

### Description
Sometimes the displayed Brave wallet address (for any currency: BTC, ETH, BAT, LTC) does not match the QR code value. I have only been able to reproduce this on a recovered wallet.

Reported via community: https://community.brave.com/t/alphanumeric-address-qr-code-address-when-i-add-funds/11613

### Steps to Reproduce

  1. Create a BAT wallet (does not have to have funds). Save recovery file for this wallet. 
  2. Set profile aside and create a clean profile.
  3. Enable payments, grab screenshots of wallet addresses and QR codes for currencies.
  4. restore wallet from step 1.
  5. Go to the Add Funds dialog and verify wallet addresses against QR codes. QR codes match step 3 but displayed wallet addresses are for the restored wallet.

**Actual result:**
When backup words are not displayed correctly because you restored your wallet, your QR code address does not match your displayed wallet address.
Ex: Displayed value is in image below. However, if you scan the QR code, you will get a different value of bitcoin:13JoDbYTG9RQZkuDUhtKHY8B7vHAUYa3Ni
![screen shot 2017-12-04 at 5 02 20 pm](https://user-images.githubusercontent.com/28145373/33578549-f8b8b198-d914-11e7-9ce4-029a541c7d49.png)

**Expected result:**
These should always match.

**Reproduces how often:**
easy

### Brave Version

**about:brave info:**
Brave | 0.19.105
rev | 51f8ba5
Muon | 4.5.16

**Reproducible on current live release:**
Yes

**Comment by LaurenWags** [comment]
Another way to reproduce this:
Have a wallet created.
Close Brave.
Delete your ledger* files and folders from ~/Library/Application Support/brave
Reopen Brave
New wallet is created.
QR code does not match displayed wallet address.

**Comment by srirambv** [comment]
Works fine on Windows

**Comment by LaurenWags** [comment]
Reproduced on MacOS and Win by @srirambv using steps from https://github.com/brave/browser-laptop/issues/12170#issuecomment-350373166

**Comment by NejcZdovc** [comment]
@LaurenWags can we close this one and create another issue, because this issue is about recovery, where we reopen it because of another scenario. Already looking into this second scenario.

**Comment by LaurenWags** [comment]
Created https://github.com/brave/browser-laptop/issues/12592 and assigned you @NejcZdovc for issue described in https://github.com/brave/browser-laptop/issues/12170#issuecomment-350373166
