### ISSUE TITLE
browser becomes unresponsive when enabling Pocket

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12187]
### Description

@darkdh found that enabling Pocket on a C63 build causes Brave to become completely unresponsive and unusable.

### Steps to Reproduce

  1. launch `0.19.107`
  2. enable the `Pocket` extension via `about:preferences#extensions`
  3. once enabled, close and relaunch Brave

On Win it's actually worse, once you enable `Pocket`, the entire browser becomes unresponsive without even a restart. 

**Actual result:**

Entire browser becomes unresponsive when enabling `Pocket` from `about:preferences#extensions`

**Expected result:**

Browser shouldn't become unresponsive/unusable when enabling `Pocket`

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.107 - Reproducible
> rev: 54a209f96441d646585c510dadf6eac96cb2d5c3 
> Muon: 4.5.21 
> libchromiumcontent: 63.0.3239.59 

**Reproducible on current live release:**

> Brave: 0.19.105 - No Reproducible 
> rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94 

### Additional Information

* macOS 10.13.1 x64 - Reproduced (also reproduced by @darkdh)
* Ubuntu 17.10 x64 - Reproduced
* Win 10 x64 - Reproduced

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/7a9dea4cdcb4116e6ec68b34fc7a72180cdb0006
muon 4.5.23

**Comment by srirambv** [comment]
Works on muon 4.5.22 as well. Verified by enabling pocket and relaunching the browser works just fine on Windows.

**Comment by kjozwiak** [comment]
I also went through each extensions listed under `about:preferences#extensions` and ensured enabling/disabling them didn't cause Brave to become unresponsive.

Used:
* `0.19.113` with `muon 4.5.25` under Ubuntu 17.10 x64
