### ISSUE TITLE
Investigate function F12 and related shortcut keys

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1218]
We have reports of F* shortcut keys not working on Windows:
F12 for dev console
F5 for refresh
F11 for full screen

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/e185d6fe75a1927d45c73b00686e713a310bd0d7
https://github.com/brave/browser-laptop/commit/a145cb867e1a6ad91c6c86d3772c9dab1b1fa382

Fixed.

**Comment by bsclifton** [comment]
Huge thanks for this fix :smile: As a Windows dev, I am so used to F12 that I thought Brave actually didn't have developer tools
