### ISSUE TITLE
Menu is not shown on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12185]
### Description
Menu is not shown on Windows

### Steps to Reproduce
    1. Clean install 0.19.106
    2. Click on <kbd>Alt</kbd> 
    3. Menu shows and hides again

**Actual result:**
![menu_c63](https://user-images.githubusercontent.com/17010094/33621817-eedd5a78-d9e3-11e7-9a1d-7514eee7882d.gif)

**Expected result:**
Should show the menu and retain it when <kbd>Alt</kbd> is pressed

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.106
-- | --
rev | 88cb988
Muon | 4.5.21
libchromiumcontent | 63.0.3239.59
V8 | 6.3.292
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/237a6eeee62c97abddfbcb009935acf7478992ae
muon 4.5.22
