### ISSUE TITLE
"TypeError: callback is not a function" in bat-client

### ISSUE THREAD

**Issue by svillar** [brave/browser-laptop#12180]
### Description
Brave issues the following error after launching it, without having to navigate to any web page, just showing the start page:
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: callback is not a function
    at ~/checkout/browser-laptop-bootstrap/src/browser-laptop/node_modules/bat-client/index.js:690:21
    at self.roundtrip (~/checkout/browser-laptop-bootstrap/src/browser-laptop/node_modules/bat-client/index.js:1180:65)
    at request.request (~/checkout/browser-laptop-bootstrap/src/browser-laptop/app/browser/api/ledger.js:1310:14)
    at Function.defaultSession.webRequest.fetch (~/checkout/browser-laptop-bootstrap/src/browser-laptop/js/lib/request.js:54:5)
```

### Steps to Reproduce

  1. Launch Brave. Front page is shown
  2. Wait for ~10s
  3. The error message is shown in console

**Actual result:**
The error I mentioned above

**Expected result:**
No error should be shown

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
Name | Version
-- | --
Brave | 0.22.0
V8 | 6.4.370
rev | 81f7991
Muon | 4.6.3
OS Release | 4.14.0-1-amd64
Update Channel |  
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3278.0

**Comment by luixxiul** [comment]
Should this be addressed on https://github.com/brave/browser-laptop-bootstrap?

**Comment by svillar** [comment]
not sure, the original call comes from browser-laptop, but I far from an expert on that part of the code.
