### ISSUE TITLE
"Settings Menu" isn't working

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12186]
### Description

The `Settings` menu isn't working. Selecting items like `Quit Brave`, `Preferences`, `Print..`, `New Tab` doesn't do anything.

### Steps to Reproduce

  1. launch `0.19.106`
  2. click on the `settings" menu and select `New Tab` (nothing will happen)
  3. click on the `settings" menu and select `Quit Brave` (nothing will happen)
  4. click on the `settings" menu and select `Preferences` (nothing will happen)

**Actual result:**

Selecting items under the `settings` menu doesn't do anything.

![settingmenuissue](https://user-images.githubusercontent.com/2602313/33625667-4b850618-d9c6-11e7-856d-3c7ea2e70684.gif)

**Expected result:**

Items under the `settings` menu should be working once selected/clicked on.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.106 
> rev: 88cb988a2796b81c391b4302c04a6fb9df4f979d 
> Muon: 4.5.21 
> libchromiumcontent: 63.0.3239.59 

**Reproducible on current live release:**

Only reproducible with the C63 build.

### Additional Information

* macOS 10.13.1 x64 - Reproduced (also reproduced by @LaurenWags)
* Win 10 x64 - Reproduced (also reproduced by @srirambv)
* Ubuntu 17.10 x64 - Reproduced

**Comment by capouch** [comment]
It seems a variety of menu items are now dead; including the "Menu -> Help -> * functions.  

Right-clicking after selecting text also fails to post the normal UI menu, which may be related??

**Comment by capouch** [comment]
None of the items on the "three dots" menu appear to work, and the bug appears to affect both versions 0.19.106 and 0.19.107.

**Comment by kjozwiak** [comment]
> None of the items on the "three dots" menu appear to work, and the bug appears to affect both versions 0.19.106 and 0.19.107.

Yup, it looks like something regressed with the C63 builds... Possibly related to #12185 and #12175.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/237a6eeee62c97abddfbcb009935acf7478992ae
muon 4.5.22
