### ISSUE TITLE
Incorrect amount deducted from wallet for payment processing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12183]
### Description
While verifying #12154 , came across a scenario where the balance is below the minimum BAT balance and if the user claims token, then the amount deducted from wallet for payment processing is wrong

### Steps to Reproduce
   1. Build from #12154
   2. Launch `LEDGER_ENVIRONMENT=staging npm run start`
   3. Enable payments and add 20 BAT so that its lesser than the min BAT 
   4. Change `reconcileStamp` to older date
   5. Relaunch `LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging npm run start`
   6. Ensure Next contribution:overdue 
   7. Claim tokens so that balance becomes 50
   8. Wait for contribution to be made so that you see the notification 
![image](https://user-images.githubusercontent.com/17010094/33612713-6284d09c-d9ca-11e7-8a36-082b74b1bb39.png)
   9. Once the payment is processed amount of 40 BAT is deducted from account when the monthly budget is set at 25BAT

**Actual result:**
Monthly payment processing amount is incorrectly deducted 

**Expected result:**
Should only deduct amount equal to the monthly set budget

**Reproduces how often:**
Consistent on Windows

### Brave Version

**about:brave info:**

Brave | 0.19.106
-- | --
rev | 7394478
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Not sure

### Additional Information
cc: @mrose17 @evq

**Comment by NejcZdovc** [comment]
@srirambv is this still a problem?

**Comment by srirambv** [comment]
Can't reproduce this any more on 0.19.136. Closing for now.
