### ISSUE TITLE
Consider setting Payments contribution date based on funding date or delay withdrawal

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#12189]
### Description

The current system treats user who already opted in to Payments as if they owe to us. It shouldn't be.  We should consider setting up the contribution cycle based on when the user actually funded the wallet, not the date the user expressed the interest (by turning in on).

The result of that is when I transferred BAT to my wallet for the first time, it was taken out immediately without any indication, my balance was constantly 0 because I only added the exact monthly budget (I was watching it for a while to see what gets displayed on the UI). Consequently, I thought BAT transfer was not successful and something went wrong, only later to find out via History that it was debited as soon as the funds arrived.

a. this can happen to a lot of the users: turn on the feature, but adding funds much later.
b. I don't remember seeing the contribution date (cycle) before I funded, to figure that this might have happen
c. Even after, contribution date is not the first thing I look to verify if my action took place, it's the balance. 
d. History is not the place I imagine going there to get the answer.

2 problems to solve:
1. Reasonable determination of contribution date/cycle
2. Better informing users of what the system had done, especially when it comes to sensitive events such as involving currencies.

[Brave_Payments_2017-11-10.pdf](https://github.com/brave/browser-laptop/files/1533073/Brave_Payments_2017-11-10.pdf)

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Tackling the loss of contribution details with https://github.com/brave/browser-laptop/issues/12055

Moving this to the triage backlog
