### ISSUE TITLE
Blocked item details not shown when clicked on the blocked number

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12184]
### Description
Blocked item details not shown when clicked on the blocked number

### Steps to Reproduce
   1. Clean install 0.19.106
   2. Visit any site which has blocked items
   3. Open site shields and click on the blocked item, details pane is not loaded 

**Actual result:**
![shields](https://user-images.githubusercontent.com/17010094/33618697-26fb6e76-d9db-11e7-9f87-6991106fa543.gif)

**Expected result:**
Should show the blocked items details

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.106
-- | --
rev | 88cb988
Muon | 4.5.21
libchromiumcontent | 63.0.3239.59
V8 | 6.3.292
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/cdeecd9c9110ffe99aba4c9b8cc075cef56e8023
muon 4.5.22

**Comment by kjozwiak** [comment]
Ensured that the details pane was shown for:
* Ads & Trackers Blocked - PASSED
* HTTPS Upgrades - PASSED
* Scripts Blocked - PASSED
* Fingerprinting Methods Blocked - PASSED
