### ISSUE TITLE
enable SSL certificate pinning for important Brave domains

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12190]
we should mitigate against TLS MITM attacks by using certificate pinning / expect-CT for important domains in browser-laptop (Brave update server, Brave extensions update server, ledger servers, etc.). this may be doable by simply adding to https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json 

cc @jumde

**Comment by diracdeltas** [comment]
This was done in https://github.com/brave/muon/pull/401

**Comment by diracdeltas** [comment]
Test plan:
1. remove the browser profile foldre
2. open devtools and go to http://roundcube.mayfirst.org 
3. in the network requests devtools tab, you should see 'http://roundcube.mayfirst.org' redirect to https with a 307 code

**Comment by LaurenWags** [comment]
Works on MacOS:
![screen shot 2018-01-18 at 1 08 19 pm](https://user-images.githubusercontent.com/28145373/35113784-b4b45448-fc50-11e7-808a-b8ee26f40535.png)

**Comment by kjozwiak** [comment]
Same results as @LaurenWags under Win 10 x64 and Ubuntu 17.10 x64 using `0.19.138`38f85090d93ce665fbe6eb347d2ea4cc5d5c8d62.
