### ISSUE TITLE
Cannot login with 2FA enabled

### ISSUE THREAD

**Issue by DCodeOS** [brave/browser-laptop#12196]
### Description
Cannot login with a google account with 2FA enabled

### Steps to Reproduce
  1. Go to google login page
  2. Sign in with username and password
  3. With 2 factor authentication method enable displayed an error message ( method used: Google Authenticator app )

**Actual result:**
Dialog window popups saying
"Try again? Your sign-in attempt timed out. Resend the notification to try again."

**Expected result:**
Login successfully

**Reproduces how often:**
Always.

### Brave Version

**about:brave info:**
 
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.2.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by srirambv** [comment]
This is same as  #7866 . Closing as dupe
