### ISSUE TITLE
Unable to turn on payments

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12208]
### Description
Unable to turn on payments

### Steps to Reproduce

  1. Clean install 0.19.108
  2. Enable payments nothing happens
  3. Launch from console, enable payments, just throws `properties error: Error: Ledger client initialization incomplete.`

**Actual result:**
Unable to turn on payments

**Expected result:**
Should enable payments and create wallet

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

**Comment by LaurenWags** [comment]
Reproduced on MacOS (no error though) STR:
Clean profile with 0.19.108
Navigate to about:preferences#payments
Try to switch toggle to 'On', nothing happens (toggle does not move).

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23

**Comment by Hesesses** [comment]
Just installed Brave for the first time and having the same problem

Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Comment by bsclifton** [comment]
@Hesesses do you have more information? You can start Brave via the command line with a special flag if you wanted to see more detailed information:
`LEDGER_VERBOSE=true /Applications/Brave.app/Contents/MacOS/Brave`

The server side may have experienced an issue when you were trying

**Comment by Hesesses** [comment]
Maybe it was server side problem as it seems to work now 👍
