### ISSUE TITLE
New tab to open with dashboard loads a blank tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12207]
### Description
New tab to open with dashboard loads a blank tab

### Steps to Reproduce

  1. Clean install 0.19.108
  2. Open a new tab
  3. Opens a blank tab, no top tiles or background images are loaded

**Actual result:**
![dashboard](https://user-images.githubusercontent.com/17010094/33706399-f3da9a9c-db2b-11e7-982f-ad255c428f11.gif)

**Expected result:**
Should load dashboard unless new tab is set to open a blank tab

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
Initially reported by @petemill

**Comment by LaurenWags** [comment]
Reproduced on MacOS using 0.19.108

**Comment by kjozwiak** [comment]
Reproduced on Ubuntu 17.10 x64 using `0.19.108` as well.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23
