### ISSUE TITLE
Extensions page is empty and only lists when reloading the page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12209]
### Description
Extensions page is empty and only lists when reloading the page

### Steps to Reproduce

  1. Clean install 0.19.108
  2. Open preferences using keyboard shortcut <kbd>Ctrl+,</kbd>
  3. Open Extensions, shows empty page, reload the page via F5, all extensions gets listed

**Actual result:**
![extension](https://user-images.githubusercontent.com/17010094/33710133-8a45d1c6-db37-11e7-87f3-d419d453d965.gif)

**Expected result:**
Should load and list all the extension when the extension page is opened

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

**Comment by srirambv** [comment]
Same issue on about:brave as well

**Comment by LaurenWags** [comment]
Reproduced on MacOS.

**Comment by kjozwiak** [comment]
Reproduced on Ubuntu 17.10 x64 using `0.19.108`.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23
