### ISSUE TITLE
notification not appearing after a contribution is made

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12201]
### Description

It appears that the notification that lets users know that a contribution has been made including the amount that was contributed are not being displayed. After going through the below STR several times and waiting a few hours, the notification never ended up being displayed.

### Steps to Reproduce

  1. install `0.19.107` and claim a UGP grant once prompted
  2. once you've received your UGP grant, close brave
  3. change `reconcileStamp` under `ledger-state.json` to Nov. 30th (using epoch time)
  4. once changed, launch brave via `LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true`
  5. open `about:preferences#payments` and you'll notice that `Contribution: Overdue`
  6. Wait till you see your balance change which means a contribution was made

You'll notice that you won't get a notification letting you know that a contribution as been made.

**Actual result:**

Once a contribution has been made, the notification that lets users know that a contribution has been made doesn't seem to be appearing.

**Expected result:**

Once a contribution has been made, a notification should appear letting the user know the amount that was contributed which should match what they've selected via the monthly budget.

**Reproduces how often:**

100% reproducible when going through the above test case/str.

### Brave Version

**about:brave info:**

> Brave: 0.19.107 
> rev: 54a209f96441d646585c510dadf6eac96cb2d5c3 
> Muon: 4.5.21 
> libchromiumcontent: 63.0.3239.59 

**Reproducible on current live release:**

This was tested against UGP with `0.19.107` using production servers. I'll retest once UGP goes live.. However, QA needs the `LEDGER_NO_FUZZING` environmental variable which currently isn't available in the release build.

### Additional Information

@srirambv and @LaurenWags both saw this behaviour under Win and macOS.

**Comment by bsclifton** [comment]
Confirmed this is fixed with https://github.com/brave/browser-laptop/pull/12204 😄

**Comment by LaurenWags** [comment]
Received message on MacOS using 0.19.110
![screen shot 2017-12-08 at 4 47 20 pm](https://user-images.githubusercontent.com/28145373/33786709-1cf6fd46-dc38-11e7-8240-b8ffb5a344fc.png)

**Comment by srirambv** [comment]
Received on Windows with 0.13.113
![image](https://user-images.githubusercontent.com/17010094/33828432-0982a192-de64-11e7-97fe-74e7c70a3cab.png)

**Comment by kjozwiak** [comment]
I went through the following test cases under both the `production` and `staging` servers:

* Contributed/Reconciled 25 BAT and ensured that the notification displayed the correct amount
* Contributed/Reconciled 50 BAT and ensured that the notification displayed the correct amount
* Contributed/Reconciled 75 BAT and ensured that the notification displayed the correct amount
* Contributed/Reconciled 100 BAT and ensured that the notification displayed the correct amount

**_Quick Note:_** the 100 BAT case was only tested against the staging server.

Build being used:

> Brave: 0.19.115 
> rev: 584e69490e984bb0909aa45edfec778ed91ee370 
> Muon: 4.5.25 
> libchromiumcontent: 63.0.3239.84

Environmental Variables being used:

* Staging Server -->` LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true`
* Production Server --> `LEDGER_VERBOSE=true LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true`
