### ISSUE TITLE
Inconsistent progress loading feedback when clicking links

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#12218]
Inconsistent progress loading feedback when clicking links

### Steps to Reproduce

  1.  Visit a webpage
  2.  Click a link
  3.  Notice that everything is just frozen, no spinner, no progress, can't tell if it registered my click or not.. 
  4.  Then finally I arrive at the page I clicked.

...  Doing this over and over, some times there is a spinner, sometimes there is not.

**Expected result:**

Expect to always get feedback when clicking links or visiting webpages in new tabs.

**Reproduces how often:**
very often during daily use.

### Brave Version

**about:brave info:**
0.19.105

**Comment by bsclifton** [comment]
This should be much better now - are you still experiencing this issue, @patrick99e99 ?

**Comment by patrick99e99** [comment]
Well I just opened another issue related to this, because it just
happened to me and drives me insane everytime it does...
https://github.com/brave/browser-laptop/issues/14363

Patrick J. Collins
http://collinatorstudios.com

**Comment by petemill** [comment]
Possibly fixed with #14384
