### ISSUE TITLE
Global shields settings are disabled by default but enabled for a site 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12213]
### Description
Global shields settings are disabled by default but enabled for a site 

### Steps to Reproduce
  1. Clean install 0.19.108
  2. Visit about:preferences#shields
  3. HTTPSE/Block Phishing is disabled by default 
  4. Visit https://theverge.com in a new tab, open site shields settings, HTTPSE & Block Phishing is enabled on the site 

**Actual result:**
Global shields settings are disabled by default but enabled for a site 

**Expected result:**
Default global shields settings should be enabled 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
cc: @diracdeltas @bridiver 
@LaurenWags @kjozwiak

**Comment by LaurenWags** [comment]
Reproduced on MacOS using 0.19.108

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23
