### ISSUE TITLE
Sync not enabled on CR63 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12212]
### Description
Sync not enabled on CR63 

### Steps to Reproduce
  1. Clean install 0.19.108
  2. Enable Sync, nothing happens
  3. Launch browser from console, Enable sync, nothing happens, console shows reloading sync but nothing happens 

**Actual result:**
Sync not enabled on CR63 

**Expected result:**
Should enable sync

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
cc: @LaurenWags @kjozwiak

**Comment by kjozwiak** [comment]
Reproduced on Ubuntu 17.10 x64 using `0.19.108`.

**Comment by LaurenWags** [comment]
Reproduced on MacOS using 0.19.108

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23
