### ISSUE TITLE
Video sound disappears when shifting to other tabs

### ISSUE THREAD

**Issue by egferro** [brave/browser-laptop#12215]
When I am streaming a video on youtube, if I shift to another tab, it often happens that the audio of the video disappears and cannot be turned back on.  This does not happen always but often.
Thanks for the support.
I actually found the problem: placing the volume button on the tab makes you disable the sound without noticing. You may want to think about keeping that command there.

Description

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by srirambv** [comment]
@egferro  do you mind using the template to provide steps to reproduce. Its not quite clear from what you have written

**Comment by bsclifton** [comment]
Closing as there is not enough information for us to investigate. Please re-open if you have more info (ex: steps that we can follow to reproduce the issue, so we can investigate)
