### ISSUE TITLE
Flash not detected on CR63

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12214]
### Description
Flash not detected on CR63

### Steps to Reproduce

  1. Clean install 0.19.105
  2. Enable Flash from plugins
  3. Update to 0.19.108
  4. Flash switch is disabled

**Actual result:**
![flash](https://user-images.githubusercontent.com/17010094/33719878-1440ac6c-db5a-11e7-8841-2f2823e01210.gif)

**Expected result:**
Flash should be enabled during upgrade

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
cc: @diracdeltas @bridiver

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23
