### ISSUE TITLE
Pocket login page is not loaded when clicked on the widget

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12210]
### Description
Pocket login page is not loaded when clicked on the widget

### Steps to Reproduce
  1. Clean install 0.19.108
  2. Enable pocket from extensions page
  3. Close the pocket login page that is opened on enabling the extensions
  4. Click on pocket, nothing happens, login page is not loaded in a new tab
  5. Launching from console and following the above steps shows error 
![image](https://user-images.githubusercontent.com/17010094/33716182-1d99da0c-db4d-11e7-9e5e-214480f16e9e.png)

**Actual result:**
Pocket login page is not loaded when clicked on the widget

**Expected result:**
Should open the login page when widget is clicked and not signed in

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.108
-- | --
rev | d1b0922
Muon | 4.5.22
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
cc: @LaurenWags @kjozwiak

**Comment by LaurenWags** [comment]
Reproduced on MacOS with 0.19.108.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd
muon 4.5.23
