### ISSUE TITLE
Unable to open new instance in Windows

### ISSUE THREAD

**Issue by jaxidian** [brave/browser-laptop#12228]
### Description
I'd like to open new instances of Brave in Windows. Specifically, I'd like to do this using the icon in the Taskbar while utilizing Windows 10's built-in Virtual Desktop functionality and have my new instance open in the same Virtual Desktop that I'm actively working in.

I have tried in various ways to utilize [commandline parameters](https://peter.sh/experiments/chromium-command-line-switches/) without luck, specifically attempting to use the `--new-window` parameter, as Issue #388  suggests I should be able to do.

### Steps to Reproduce
  1. Enable Virtual Desktops (VD) in Windows 10 and have the Brave icon pinned on your Taskbar.
  2. Under Home -> System -> Multitasking, set the "On the taskbar, show windows that are open on" dropdown to "Only the desktop I'm using" option.
  3. Open Brave on VD 1 and navigate to some site.
  4. Switch Windows such that you're now viewing VD 2.
  5. Observe that the Brave icon appears as though Brave is not open.
  6. Attempt to open a new instance in any of the following ways:
  6.a. Click on the Brave Icon
  6.b. Right-click on the Brave icon, right-click again on the Brave logo in that context menu, and select Open
  6.c. Open a CMD window in the correct directory and execute `brave.exe`

**Actual result:**
Windows switches the display to VD 1 and gives the already-opened instance focus.

**Expected result:**
I expect a new instance of Brave to open on VD 2 and receive focus.

**Reproduces how often:**
100%

### Brave Version

0.19.105

**Reproducible on current live release:**
Yes

### Additional Information
I have been unable to get the `--new-window` parameter to work. I might have some syntax wrong but that would be an acceptable work-around if I knew how to make it work, then I'd just run the equivalent of `brave.exe --new-window "about:newtab"` and I'd be good.

**Comment by jonathansampson** [comment]
+1 as I am able to reproduce the issue.

- Open Chrome and Brave on Desktop 1
- Create Desktop 2
- Run Chrome from Start Menu (Results in instance on Desktop 2)
- Run Brave from Start Menu (Switches focus back to Desktop 1)

**Comment by rkhe** [comment]
+1 able to reproduce similar issue.
Add `Brave` browser for debugging purposes in VS2019 with parameters `--profile-directory="Profile 2" --new-window` does not open in a new window but appends as a new tab on an opened browser instead.

**Comment by bsclifton** [comment]
@rkhe thanks for the comment - this version of the product is deprecated. Can you please try the new version of Brave? https://brave.com/download
