### ISSUE TITLE
mitigate HSTS fingerprinting

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12223]
## Test plan
See https://github.com/brave/browser-laptop/pull/13437

## Original issue description
context: it has been reported in various places that Criteo is using HSTS supercookies (where they buy a bunch of domains and set HSTS on a different subset of domains for each user in order to uniquely identify them) for ad tracking. https://www.gothamcityresearch.com/single-post/2017/10/12/Criteo-SA-NASDAQ-CRTO-Why-We-Believe-Criteo%E2%80%99s-Undisclosed-Practices-are-Illegal-and-Harmful-to-Advertisers

possibilities:
1. double-key HSTS
2. disallow 3rd parties from setting HSTS

**Comment by diracdeltas** [comment]
adding to 0.20.x, per @BrendanEich suggestion

currently the proposal seems to boil down to: don't apply HSTS on 3rd party subresource loads, unless that subresource has been visited as a first party (similar to Safari's 3rd party cookie policy)

**Comment by bsclifton** [comment]
Moving to 0.21.x for now- let's move it back if this is finished before Jan 8th and doesn't require a Muon change 😄

**Comment by alexwykoff** [comment]
@diracdeltas is this release blocking?

**Comment by diracdeltas** [comment]
it would be really good if this were included in 0.21.x since people have been asking for it for a while. cc @jumde

**Comment by bsclifton** [comment]
Depends on https://github.com/brave/muon/pull/527

@diracdeltas please note that the milestone was adjusted; once the work is complete, we can find the right place for it 😄

**Comment by diracdeltas** [comment]
it now depends on https://github.com/brave/muon/pull/532 which is a simpler change. moving to 0.22.x for now

**Comment by bsclifton** [comment]
Re-opening after reverting browser-laptop code with https://github.com/brave/browser-laptop/pull/13638

**Comment by btlechowski** [comment]
Verified Win7 x64 v0.22.108

Steps used to verify:
1. Clear browsing history and cache
2. Go to https://jsfiddle.net/pqwdgr5x/5/
3. Bring Debugger(F12) and open Network tab
4. Tick 'Preserve log' and select 'Other'
5. Press F5 to reload

Expected result:
301 redirect

Steps used to verify:
1. Clear browsing history and cache
2. Go to https://avatars2.githubusercontent.com/u/1903815?s=40&v=4
3. Go to https://jsfiddle.net/pqwdgr5x/5/
4. Bring Debugger(F12) and open Network tab
5. Tick 'Preserve log' and select 'Other'
6. Press F5 to reload

Expected result:
307 redirect
