### ISSUE TITLE
Stop asking me if im ready to start the payments beta. Ive been asked 4 times in one month. 

### ISSUE THREAD

**Issue by LethalManBoob** [brave/browser-laptop#12226]
Thats it. Provide me with a way to disable this or i will leave this browser behind. I will not have brave advertising its features to me without my consent.

**Comment by srirambv** [comment]
You can disable it in advance settings. To disable notification you need to enable payments turn it off and then if you wish you can turn off the payments. 

![image](https://user-images.githubusercontent.com/17010094/33775384-183c100e-dc36-11e7-89dc-b4e2b32c8a5d.png)
