### ISSUE TITLE
tab opens and never finishes loading on payments saveRecoveryFile

### ISSUE THREAD

**Issue by anaran** [brave/browser-laptop#12221]
### Description

tab opens and never finishes loading on payments saveRecoveryFile.

Its URL is chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-blank.html and it contains:

```html
<!DOCTYPE html>
<!-- This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
<html>
  <head>
    <meta charset="utf-8">
    <meta name="availableLanguages" content="">
    <meta name="defaultLanguage" content="en-US">
    <meta name="referrer" content="no-referrer">
    <title data-l10n-id="aboutBlankTitle"></title>
    <script src="ext/l20n.min.js"></script>
    <script src="gen/aboutPages.entry.js" async></script>
    <link rel="localization" href="locales/{locale}/common.properties">
  </head>
  <body />
</html>
```

### Steps to Reproduce

  1. Open payments -> extended settings
  2. click button data-l10n-id="saveRecoveryFile"
  3. Notice how new unnamed tab opens and never finishes loading

**Actual result:**

New tab with infinite progress spinner is irritating and brave consumes a lot of CPU resources.

**Expected result:**

No tab unless it contains info and finishes loading

**Reproduces how often:**

100%

### Brave Version

```
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.4.0-102-generic 
OS Architecture: x64
```

**Comment by NejcZdovc** [comment]
closing this one as a dup of #9677
