### ISSUE TITLE
textbox not large enough to display large balances

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12220]
### Description

@darkdh noticed that the textbox under `about:preferences#payments` isn't big enough for larger balances. We'll either need to make the textbox longer or come up with a better solution for displaying balances.

### Steps to Reproduce

N/A... Simply have a wallet with a large balance and you'll notice the issue happening under `about:preferences#payments`.

**Actual result:**

![example](https://user-images.githubusercontent.com/2602313/33461703-91ac133e-d601-11e7-8902-dbde900f776e.gif)

**Expected result:**

The entire balance should be visible under `about:preferences#payments`.

**Reproduces how often:**

100% reproducible if the user has a large balance.

### Brave Version

**about:brave info:**

> Brave: 0.19.105 
> rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94 

**Reproducible on current live release:**

Yes, reproducible using `0.19.105` which is the current released version.

**Comment by NejcZdovc** [comment]
@bradleyrichter what should we do here?

**Comment by bradleyrichter** [comment]
We can easily add more width to the field to accommodate 4-6 more decimal places for these edge cases.

**Comment by kjozwiak** [comment]
Example of the original issue under `0.22.669` using a staging wallet with `1000 BAT` tokens:

<img width="842" alt="screen shot 2018-05-08 at 4 36 12 pm" src="https://user-images.githubusercontent.com/2602313/39781699-fa033d64-52dd-11e8-880c-699e7578b214.png">

Example when using `0.22.703` with the same wallet as mentioned above:

<img width="843" alt="screen shot 2018-05-08 at 4 33 37 pm" src="https://user-images.githubusercontent.com/2602313/39781826-494c8506-52de-11e8-8ee9-14f0c82fe036.png">

**Comment by kjozwiak** [comment]
Verified on macOS 10.13.3 x64 using the following build:
 
* `0.22.703` 903b8d0d3703b5fdc5a719294403e7460d9b806d 
* libchromiumcontent: `66.0.3359.139`
* Muon: `6.0.8 `
