### ISSUE TITLE
Additional BAT Contribution Amounts

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12234]
### Test plan
1. Visit about:preferences#payments
2. Ensure the following amounts are shown (including decimal point):
`5.0, 7.5, 10.0, 17.5, 25.0, 50.0, 75.0, 100.0`

![image](https://user-images.githubusercontent.com/4733304/34632543-3c0274b6-f233-11e7-99ff-c053a35bb83f.png)

3. Try a reconcile / settlement to ensure it goes through (see https://github.com/brave/browser-laptop/wiki/Ledger-testing for helper flags)

### Description
Requested via DM in Community: User would like additional BAT contribution Amounts (one mentioned was 500) because per the user "the current limit of donating BAT is too low. I would like to donate more BAT to publishers to increase awareness, hence why I would like to donate 500 BAT."

### Steps to Reproduce

  1. Navigate to Payments
  2. Have additional BAT contribution amounts
  3.

**Actual result:**
Current amounts are 25, 50, 75, 100 BAT

**Expected result:**
Additional amounts

**Reproduces how often:**
n/a

### Brave Version

**about:brave info:**
n/a

**Reproducible on current live release:**
n/a

**Comment by jeffbricco** [comment]
Personally, I would like to see lower amounts. Current minimum is around $10/month. In the screenshots on brave.com it shows the 25 BAT being worth $3. Maybe add the ability to enter a custom amount (which would prevent a constant stream of requests like this) or add an amount for 10 BAT?

**Comment by NumDeP** [comment]
@jeffbricco I figured seeing as I requested something similar but more extensive (#12335) to inform you both Laurens DM user and yourself will most likely have your demands met in the next update #12495 #12473

**Comment by bsclifton** [comment]
Proposed amounts by @davidtemkin:
5.0, 7.5, 10.0, 17.5, 25.0, 50.0, 75.0, 100.0

**Comment by srirambv** [comment]
Reconcile goes through but no notification bar shown for successful payment process nor the report is generated
![image](https://user-images.githubusercontent.com/17010094/34660571-5faf67e2-f469-11e7-8027-c9a489a73b55.png)
