### ISSUE TITLE
Better support for Reopen last closed window

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12239]
If you have more than one window open and close a window, there is no option to reopen that window with the tabs set to open to where you left off. Similarly if you close Brave with more than one window open, it will only reopen the last active window with the tabs open where you left off. It would be 

### Brave Version
 
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by jamesray1** [comment]
I just noticed that if I restart without closing Brave with two windows open, it reopens them with the tabs open from where I left off. However, if I close all windows by right clicking on brave and click close all windows, then reopen, it just opens one window.

**Comment by bsclifton** [comment]
This is definitely fixed with [brave-core](https://github.com/brave/brave-browser) 😄
