### ISSUE TITLE
Browser crashes when disconnected from network

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12230]
### Description
Browser crashes when disconnected from network

### Steps to Reproduce
  1. Launch browser from staging `LEDGER_ENVIRONMENT=staging <path for browser>`
  2. Enable payments, wait till `Claim my Token` button shows up
  3. Disable network, browser crashes

**Actual result:**
Browser crashes when disconnected from network

**Expected result:**
Should not crash

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.109
-- | --
rev | 9c674b5
Muon | 4.5.23
libchromiumcontent | 63.0.3239.70
V8 | 6.3.292.44
Node.js | 7.9.0
Update Channel | nightly
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Not sure

### Additional Information
Can't reproduce on Production version as promotion is over

**Comment by kjozwiak** [comment]
Receive the following crash dump under macOS 10.13.1 x64:

[macOScrash.txt](https://github.com/brave/browser-laptop/files/1543680/macOScrash.txt)

**Comment by kjozwiak** [comment]
Simpler STR:

* launch `0.19.109`
* once brave has launched, simply disable the network

Similar to #12232

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/01616a8015750ac335003118c7b0c78e0e68fe77
muon 4.5.24
