### ISSUE TITLE
Inbox by Google - UI Elements & Images Not Loading

### ISSUE THREAD

**Issue by emm3ttarmstrong** [brave/browser-laptop#1223]
None of the UI elements (which are images) load when I visit inbox.google.com. Everything on the login screen loads properly, but when I log in to the actual app, no images from any email and no UI element images load at all. I'm seeing the "broken image" icon in place of the real image. Good news is that the functionality is not broken, just the visuals.

I'm running Brave on Ubuntu 16.04. 
Brave: 0.8.3
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 6.0.0-pre
Update channel: dev
-Replace Ads
-Block 3rd Party Cookies
-Block Popups
-HTTPS Everywhere

**Comment by weems** [comment]
@bbondy this may be a issue isolated to *nix. Using Brave 0.8.3 on OSX 10.11.4, I was able to see all UI elements on https://inbox.google.com

**Comment by admshao** [comment]
It was related with the ad blocker failing under some rules. It was fixed on 0.9.0 But now twitch.tv ONLY plays video when is set to allow tracking. =(

**Comment by bbondy** [comment]
@admshao tracking Twitch here:
https://github.com/brave/browser-laptop/issues/1308

**Comment by luixxiul** [comment]
Does this still persist on Inbox?

**Comment by cezaraugusto** [comment]
Everything showing as expected on OS X. How is it with Linux/Windows variants?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/is-https-inbox-google-com-not-loaded-on-brave/10194

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
