### ISSUE TITLE
Efficiently Bypassing SNI-based HTTPS Filtering

### ISSUE THREAD

**Issue by HLFH** [brave/browser-laptop#12235]
I precise I am using the [Quad9 public DNS resolver](https://labs.ripe.net/Members/stephane_bortzmeyer/quad9-a-public-dns-resolver-with-security) to bypass DNS filtering issues.

**Use case:** [In UK](https://en.wikipedia.org/wiki/Internet_censorship_in_the_United_Kingdom), London, the ISP TalkTalk is proceeding to HTTPS traffic filtering based on SNI. When you launch `https://thepiratebay.org`, the firewall of TalkTalk inspects:

> the SNI within the Client-Hello message to check if the ”server name” is in a black/white list or not, and according to the response, the firewall resets the connection or allows the
Client-Hello message to pass toward the destination server, and further complete the TLS handshake.

![snifiltering](https://user-images.githubusercontent.com/2359059/33792375-42ae4c58-dc95-11e7-8d0b-487141c68ae7.PNG)

![snihttpsfiltering](https://user-images.githubusercontent.com/2359059/33792510-f072434a-dc99-11e7-8306-9d667d52c268.PNG)
**Here see comparison of Brave and Firefox 32 with Escape extension**

**Workaround solutions:**

1. Use Firefox browser with the [Escape extension](http://madynes.loria.fr/Research/Software#toc2) compatible [up to Firefox 32](https://ftp.mozilla.org/pub/firefox/releases/32.0/).
2. Use a browser that is not [compatible](https://en.wikipedia.org/wiki/Server_Name_Indication#Support) with SNI like [Firefox 1](https://ftp.mozilla.org/pub/firefox/releases/1.0/).
3. Use [Tor Browser](https://www.torproject.org/projects/torbrowser.html.en)
4. Implement [Tor Private Browsing tabs within Brave](https://github.com/brave/browser-laptop/issues/1185)
5. Use a VPN
6. Implement opt-in feature to enable override of the "server name" field of the SNI extension
7. Wait for implementation of SNI encryption within TLS 1.3 or TLS 1.4

In France, they may implement the [same Internet censorship as UK in the next three years](https://www.generation-nt.com/macron-csa-regulation-contenu-internet-pornographie-jeu-video-actualite-1948488.html). Considering the fact in the West, you have a [`New Democrats`](https://en.wikipedia.org/wiki/New_Democrats) political agenda, that is enforcing measures of censorships of political dissidents or in general, counter-cultures opposed to neoliberalism and [societal collapse](https://en.wikipedia.org/wiki/Societal_collapse), I would advise Brave to add the possibility to bypass SNI-based HTTPS filtering, for example, by overriding the ”server name” field of the SNI extension.

In the base specification of TLS 1.3, there is still no plan to [implement SNI encryption](https://github.com/tlswg/tls13-spec/issues/1), even if there are [*an interesting IETF Internet-Draft*](https://tools.ietf.org/html/draft-ietf-tls-sni-encryption-00) and [slides](https://www.ietf.org/proceedings/94/slides/slides-94-tls-8.pdf) that promote it wisely.

[Research paper source](https://hal.inria.fr/hal-01202712/document)

**Comment by diracdeltas** [comment]
I think disabling SNI generally is a non-starter. Opt-in override might be doable. Most likely our short-term fix is going to be Tor private tabs and the longer-term fix is pushing for SNI encryption in future TLS specs.

**Comment by diracdeltas** [comment]
closed by tor/0.23.x branch

**Comment by aaomidi** [comment]
Can we change the SNI value without using tor?

**Comment by mrsylerpowers** [comment]
@aaomidi I was also wondering that. Like even if it is possible to create an extension like escape.

**Comment by diracdeltas** [comment]
Extensions in Chrome can't modify TLS info

**Comment by aaomidi** [comment]
Is it possible to add support to brave just for this?

This would literally bypass Iran, China, and Russia's internet blocking without the speed loss that comes with Tor/VPN.

**Comment by diracdeltas** [comment]
that's an interesting idea. do you know how servers generally respond to a spoofed SNI value (say for a hostname that doesn't exist on that server)?

**Comment by aaomidi** [comment]
It depends on the service, for example Google/Facebook/Other major sites with SAN certificates don't care at all whats in there.
