### ISSUE TITLE
Browsing history only shown after reloading about:history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12246]
### Description
Browsing history only shown after reloading about:history

### Steps to Reproduce

  1. Clean install 0.19.113
  2. Visit a couple of sites in a different/same tab
  3. Open about:history, shows empty, reload page, history entries shown

**Actual result:**
![history](https://user-images.githubusercontent.com/17010094/33831990-1e1da6a2-de72-11e7-9f95-1c66f2748680.gif)

**Expected result:**
Should show then about:history is opened

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.113
-- | --
rev | 043c506
Muon | 4.5.25
libchromiumcontent | 63.0.3239.84
V8 | 6.3.292.46
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

### Additional Information
#12209
cc: @darkdh

**Comment by darkdh** [comment]
couldn't reproduce on Mac

**Comment by bsclifton** [comment]
I believe the page gets added to history once it finishes loading.  If the page takes a while to load, it might now show up immediately.  Also, I don't think the history page updates itself (which is a separate issue)

**Comment by bsclifton** [comment]
Confirmed this works great on C62 using 0.19.x (basically, I reverted to Muon 4.5.16 and it works great)

This does appear to be C63 related
cc: @darkdh

**Comment by bsclifton** [comment]
Results for me show if I hit Ctrl + R to reload the page. @darkdh is this related to https://github.com/brave/muon/commit/4004dc1faba5d86d274ea3e46e6e383fc7b3d6fd ?

**Comment by bsclifton** [comment]
Did some debugging- definitely not related to the above Muon issue. The page is getting an empty map when loading. Time to figure this out 😄

**Comment by bsclifton** [comment]
I believe I've found the issue

The following code has the proper value. It's using shared memory to send the detail object used on the about:history page
https://github.com/brave/browser-laptop/blob/94a24e37b2521bc6f6efa5a7763b155058f94221/app/browser/tabs.js#L195-L197

However, when the receiver gets it, I have verified it gets an empty map.
https://github.com/brave/browser-laptop/blob/94a24e37b2521bc6f6efa5a7763b155058f94221/js/about/history.js#L148-L150

If you hit Ctrl + R to reload though, it gets the expected value

**Comment by bsclifton** [comment]
Interesting find: I commented out the two following lines:
https://github.com/brave/browser-laptop/blob/94a24e37b2521bc6f6efa5a7763b155058f94221/app/browser/tabs.js#L201-L202

With these commented out, the value isn't cached and `tab.sendShared` is called on each update (which happens a lot). This does not fix the issue

**Comment by srirambv** [comment]
This issue doesn't happen on Linux. Opening about:history using the keyboard shortcuts loads the history instantly
