### ISSUE TITLE
Ledger table entries removed after payment is processed 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12245]
### Description
Ledger table entries removed after payment is processed 

### Steps to Reproduce

  1. Clear existing profile 
  2. Launch browser from console with `LEDGER_ENVIRONMENT=staging <path to browser>`
  3. Enable payments, Claim free tokens 
  4. Visit 5-6 sites to add them in the ledger table
  5. Close browser and change `reconcileStamp` in `session-store-1` and `ledger-state.json` file to an older date to trigger payment process
  6. Start browser with `LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging <path to browser>`, ensure Next contribution reads `Overdue`
  7. Wait till the payment is processed and the Next contribution reads proper date and account balance is reduced
  8. Quit and relaunch browser with `LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging <path to browser>`
 9. Wait for a couple of minutes, some of the ledger entries disappear from the list

**Actual result:**
Ledger table entries removed after payment is processed. 
https://youtu.be/pKeH_n2Ll6M

**Expected result:**
Ledger table entries should not be lost when browser is quit and relaunched 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.113
-- | --
rev | 043c506
Muon | 4.5.25
libchromiumcontent | 63.0.3239.84
V8 | 6.3.292.46
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Not sure. Yet to verify

### Additional Information
#9938 
cc: @kjozwiak @LaurenWags @mrose17 @evq

**Comment by srirambv** [comment]
Payment history has different ledger entries compared to what is shown on the ledger table. Some of the deleted entries are restored and gets removed again
![table](https://user-images.githubusercontent.com/17010094/33826951-85c57b9a-de5e-11e7-8d18-13409e1a5db4.gif)

**Comment by bsclifton** [comment]
This may be intended behavior- since the voting process takes place, all entries used during that process may be getting removed (so that it won’t count them again)

@mrose17 @evq could you help clarify? I can start to look into the code to double check

**Comment by srirambv** [comment]
Same behaviour on production wallet as well.

**Comment by srirambv** [comment]
I found something interesting. When I close the browser and open nothing happens to the table. When I switched to the inactive tabs which were having the sites from the table, most entries vanished from the ledger table and finally 3-4 of them were back on the ledger table

**Comment by bsclifton** [comment]
Confirmed with @mrose17 - the ledger should ALWAYS keep the last 30 days of activity (ex: items would only fall off the list off if 30 days went by)

Assigning myself to check this out

**Comment by cryptoaddict1** [comment]
Cancel

**Comment by bsclifton** [comment]
@NejcZdovc is this intentional? During the prune synopsis, it calls an action (which saves synopsis)... but then it also saves synopsis itself

https://github.com/brave/browser-laptop/blob/94a24e37b2521bc6f6efa5a7763b155058f94221/app/browser/api/ledger.js#L365-L367

https://github.com/brave/browser-laptop/blob/94a24e37b2521bc6f6efa5a7763b155058f94221/app/browser/reducers/ledgerReducer.js#L429-L439

**Comment by NejcZdovc** [comment]
@bsclifton yes this is intentionally. So we need to save this new state into our state, because when pruning actually happens is here https://github.com/brave/browser-laptop/blob/94a24e37b2521bc6f6efa5a7763b155058f94221/app/browser/api/ledger.js#L1963, where we don't return state back. But we also need to call `ledgerState.saveSynopsis` so that we have up to date state (same as in the action) which we can use then in run function

**Comment by bsclifton** [comment]
@NejcZdovc ah ok- makes sense. Thanks for the explanation 😄 

@srirambv the history issue you also reported may be related to this.  After you see the entry disappear, can you please try hitting Ctrl + R and see if it refreshes?

@LaurenWags @kjozwiak if my suspicion is correct, this bug would only be happening on Windows.  Are either of you able to repro on macOS?

**Comment by srirambv** [comment]
@bsclifton Am unable to reproduce the issue consistently now on the latest build. Entries are not getting removed when I follow the steps from initial issue

**Comment by bsclifton** [comment]
@srirambv awesome- I'd like to propose closing the issue until we see it again and can confirm the above (do the entries re-show if you do Ctrl + R)

**Comment by srirambv** [comment]
Sounds good. Will try to reproduce and see if Ctrl+R brings back the entries 👍

**Comment by srirambv** [comment]
Unable to reproduce on 0.19.117. All entries are retained even after payment is processed
