### ISSUE TITLE
Math inputs in search with . or / are treated as URL strings

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12240]
### Description
If I enter 24/6 in the URL bar, irrespective of the default search engine and OS, it directs to http://0.0.0.24/6. Similarly if I enter 2.4*5 it directs to http://2.4%2A5/. If I do the same thing in Firefox or Chrome, it returns the calculator result at the top of search results of the default search engine. I would like the functionality to be the same as Firefox and Chrome.

 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-19-generic 
OS Architecture: x64

**Comment by Liunkae** [comment]
These problems are covered in #3317 (decimal) and #5834 (division).

**Comment by Liunkae** [comment]
See also my comment for some workarounds: https://github.com/brave/browser-laptop/issues/5834#issuecomment-263074625
