### ISSUE TITLE
Provide flag to perform immediate payment settlement 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12249]
### Test plan
See https://github.com/brave/browser-laptop/pull/12251

### Description
Provide flag `LEDGER_NO_DELAY` to perform immediate payment settlement 

**Expected result:**
Use `LEDGER_NO_DELAY` flag to perform immediate payment settlement

### Brave Version

**about:brave info:**

**Comment by kjozwiak** [comment]
Definitely a +1..... This would make life a lot easier for QA when we're testing contributions/reconciliation issues. With the current implementation, it takes about ~1hr to go through an end to end test.
