### ISSUE TITLE
The "Start With" Preference - "Show my Windows/Tabs from Last Time" Desn't Work

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1225]
When you select this, it defaults to whichever of the other two options (blank tab or home page) that you selected previous to setting the "show my Windows" option. This occurs whether the tabs were private or not.

**Comment by umbralupinus** [comment]
I can confirm this behavior.

**Comment by bbondy** [comment]
Could you post the exact steps and OS you're using? I'm not able to reproduce this on OS X.

**Comment by umbralupinus** [comment]
OS is Win 10 Pro x64

[DxDiag.txt](https://github.com/brave/browser-laptop/files/201604/DxDiag.txt)

I launch the browser via a pinned icon or shortcut on the desktop. I open a couple browsing tabs(e-mail, reddit, bing), I opened the preferences tab, and changed the preferences on the General tab to "Show my windows/Tabs from Last Time.", I click out of the drop-down box, and close the Preferences browsing tab. Leaving only the other tabs remaining (mail, reddit, bing), I close the Browser entirely, and re-launch from the shortcut or pinned icon (I've tried both).

**Comment by cfumante** [comment]
I'm using Windows 10.
 
-Open Brave via toolbar
-open preferences
- select "show windows/tabs from last time" on general preferences tab
- open several tabs from booklist (mix of private and non-private
- close Brave down
 
-restart Brave
- opens with a blank tab or the homepage, depending on how it was set
prior to changing to "last time"
 
mahalo.
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by bbondy** [comment]
If anyone can do a video if it happening that'd be useful maybe. I still can't reproduce it but there's a few people that see it so I'm sure there's an issue somewhere. 

Do other settings work by the way? Do they persist?

**Comment by cfumante** [comment]
other options for the starting screen do work - both homepage and new
tab
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by weems** [comment]
So I had a number of github tabs open, the setting for Show My Tabs from Last Time is On, but when I close and reopen, there are none of my tabs. I am on Win7 Brave 0.8.3

**Comment by umbralupinus** [comment]
[Video of Behavior](https://drive.google.com/file/d/0B81dIWMTwIBiOWhVOHJBa01iUFk/view?usp=sharing)

I finally  had some time to take a quick capture of the behavior. I did just recently update to 0.9.0 and am still receiving the behavior (the video was taken with 0.9.0)

**Comment by bbondy** [comment]
Wow strange, thanks for the video. I did the exact thing here and it works so it seems like there's some timing / race condition issue here.

**Comment by cfumante** [comment]
This is very consistent for me - in the 30-40 times I've tested it, it
always behaves the same way. I don't believe timing is the issue. I
wonder if there is a set up difference that shadow wolf and I have that
you do not on your test Windows 10 machine.
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by bbondy** [comment]
there's an IPC message that's sent when a new browser opens to restore the message. I'm thinking on your machine that IPC is received too soon before the licenser is registered, or something like that.  Perhaps it's (mostly) consistent per machine.

**Comment by cfumante** [comment]
understood - glad it's your job and not mine..... 8p
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by umbralupinus** [comment]
This behavior _seems_ to be resolved for me as of 0.9.1, I closed and re-opened sucessfully a couple times now. Will update if issue re-occurs.

**Comment by bbondy** [comment]
sweet, ya I don't think we did anything specific to fix it, but perhaps it's fixed as a side effect of moving a lot of things around for extensions.  Let me know if you see it again.

**Comment by cfumante** [comment]
Brian__
 
I still have the problem, but I think I've isolated the nature of the
failure. I always use private sessions and the restart doesn't
accomodate them. I tested with a session containing the preferences tab,
a non-private session and a private session. Only the private session is
missing on re-start.
 
This actually ties in with some feedback (not a submitted issue) that I
put in a few weeks ago - to allow the browser to start with a blank
private session tab as well as a regular tab.
 
mahalo,
 
/c/ 
 
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by bbondy** [comment]
We intentionally do not resotre private tabs.  It should be the same with other browers too.

**Comment by cfumante** [comment]
Don't understand the reason - makes it's utility less than optimal.
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
