### ISSUE TITLE
Prompted for deposit even though there's enough balance in the wallet.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#12250]
### Description
 Is this notification (in the attached screenshot) supposed to come on regardless of the fact that the balance is enough to cover the current contribution? 

Let's reduce the number of notifications we sent out to users to events absolutely necessary.

![screen shot 2017-12-11 at 10 39 37 am](https://user-images.githubusercontent.com/4369856/33847694-47c968c2-de60-11e7-94c3-558e2adeadca.png)

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Thanks for the report, @jenn-rhim 😄  This has been captured in https://github.com/brave/browser-laptop/issues/12078 which was fixed by @NejcZdovc and will be in our next release! Closing this issue as a duplicate
