### ISSUE TITLE
Safe Browsing not functioning as expected

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12253]
### Description
Safe Browsing enable/disable is not functioning as expected in C63 build.

### Steps to Reproduce

  1. Clean profile on 0.19.113.
  2. Navigate to https://www.raisegame.com/
  3. Safe Browsing stops you.
  4. Toggle off Block Phishing/Malware
  5. Site loads.
  6. Toggle Block Phishing/Malware back on.
  7. Site is blocked.
  8. Toggle shields off.

**Actual result:**
Site is not loaded, you see a page of text.
![safebrowsing019113](https://user-images.githubusercontent.com/28145373/33851299-8a6f772e-de84-11e7-8b2b-8b9cc868e145.gif)

**Expected result:**
Site should be loaded. This is how this works in 0.19.105 for the same site:
![safebrowsing019105](https://user-images.githubusercontent.com/28145373/33851315-95d91502-de84-11e7-8797-bceeb5fa6ddb.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.113
rev | 043c506
Muon | 4.5.25

**Reproducible on current live release:**
no, not reproducible on 0.19.105

### Additional Information
If you toggle shields off first, then back on, then toggle Block Phishing/Malware off the result is the same - it doesn't matter which order.

**Comment by bsclifton** [comment]
Confirmed this works great on C62 using 0.19.x (basically, I reverted to Muon 4.5.16 and it works great)

This does appear to be C63 related
cc: @darkdh

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/12255
