### ISSUE TITLE
sometimes unable to update on Release Channel

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12267]
### Description
Reported via Twitter: https://twitter.com/vladastojanovic/status/939934306990002177

User is unable to update from 0.19.95 to latest. I instructed user to do a system restart and then try updating but that did not resolve the issue.

### Steps to Reproduce

  1. Have 0.19.95 installed on Windows
  2. Check for Updates
  3. Get 'oops...' message

**Actual result:**
Unable to update
![win10-unabletoupdate2](https://user-images.githubusercontent.com/28145373/33912254-25cffaa2-df63-11e7-8e27-39f4ccafda03.jpg)

This is the error encountered:
![win10-unabletoupdate](https://user-images.githubusercontent.com/28145373/33912264-2ee9d39c-df63-11e7-9ba2-1917bb4415e1.jpg)

**Expected result:**
When update is available, should be able to update.

**Reproduces how often:**
Unknown - probably not easily.

### Brave Version

**about:brave info:**
![win10-unabletoupdate-3](https://user-images.githubusercontent.com/28145373/33912288-4ae41e4a-df63-11e7-80f9-837584efe9ef.jpg)

**Reproducible on current live release:**
found on 0.19.95

### Additional Information
Found issue logged for trouble updating Beta channel (https://github.com/brave/browser-laptop/issues/11795) but error does not appear the same.

**Comment by bsclifton** [comment]
cc: @aekeus

**Comment by bsclifton** [comment]
Closing as there hasn't been any activity lately. @LaurenWags please re-open if you run into this again 😄
