### ISSUE TITLE
the contribution due date is passed but it has not been debited and indicated as overdue.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#12262]
### Description

![image](https://user-images.githubusercontent.com/4369856/33904507-95619a70-df30-11e7-8eaf-5ad976f4199c.png)

![image](https://user-images.githubusercontent.com/4369856/33904513-9c6f4efc-df30-11e7-8d1d-bb34911124d2.png)

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@jenn-rhim we've had a lot of fixes recently... is this still occurring for you?

**Comment by jenn-rhim** [comment]
@bsclifton yes, it's still not debited, but the overdue messaging is not there anymore.

**Comment by bsclifton** [comment]
Root cause for this is likely https://github.com/brave/browser-laptop/issues/13046
