### ISSUE TITLE
Non responsive tabs on macOS High Sierra

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#12266]
Operating system: macOS High Sierra (10.13.2)

Repro Steps:
- Open any URL in tab 1
- Open a new tab. Try to switch tabs or open a new URL in the current tab.

Side Effects:
- Cannot switch tabs
- Requests to any domain is not initiated from the current tab.

about:brave:

Brave | 0.19.105
rev | 51f8ba5
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.3.0
OS Architecture | x64

**Comment by bsclifton** [comment]
Likely issue has been solved- not enough info to debug and there hasn't been any additional comments. Closing
