### ISSUE TITLE
sync v2: Add first-use wizard dialogs

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12269]
**Overview:**

The wizard guides the user step by step through an optimal path based on their choice of device type to sync with. 

Additionally, imagery at each step (if applicable) adds clarity to the task and reduces time for understanding.

Most wizard pages will allow back/forward navigation. 

If the wizard is closed BEFORE the user adds the first device, they will return to the first-use state. If they close the wizard AFTER a device is added, they will be taken to the device list and options view.

Wizard Screens:

First-run landing page for sync (to be detailed in a different issue)
![image](https://user-images.githubusercontent.com/13509546/34424985-d9aee5f8-ebdc-11e7-8546-bb078e347b43.png)

Start a New Sync Chain: Wizard Screen 1: Choose a device type
![image](https://user-images.githubusercontent.com/13509546/34425542-a7b73910-ebe1-11e7-96d1-2b2428db4395.png)

Start a New Sync Chain: Wizard Screen 2a: Scan the code
![image](https://user-images.githubusercontent.com/13509546/34425677-0cc132e2-ebe3-11e7-9c52-d6d6cf8c033b.png)

Start a New Sync Chain: Wizard Screen 2b: Enter the code (viewer)
![image](https://user-images.githubusercontent.com/13509546/36551102-b39fdd22-17ab-11e8-92cd-f257a1610620.png)

Start a New Sync Chain: Wizard Screen 3: Device list (loading devices)
![image](https://user-images.githubusercontent.com/13509546/34425665-e60acdde-ebe2-11e7-8d17-c446bbfbb631.png)

Start a New Sync Chain: Wizard Screen 4: Device list (view or add devices)
![image](https://user-images.githubusercontent.com/13509546/34425670-f345c666-ebe2-11e7-88ed-7e22db6a4793.png)

Enter a sync code: Wizard screen 1
![image](https://user-images.githubusercontent.com/13509546/36551229-faed2a5e-17ab-11e8-913d-a71f11728fd6.png)

Enter a sync code: Match check failure
![image](https://user-images.githubusercontent.com/13509546/36551303-274f4938-17ac-11e8-9a38-990eccb60c06.png)

![image](https://user-images.githubusercontent.com/13509546/36551404-5b59b006-17ac-11e8-863e-7932eef61bff.png)

**Comment by bradleyrichter** [comment]
@cezaraugusto screens above have been revised for the code display, entry and error display.

**Comment by bsclifton** [comment]
Closing as `wontfix` since we're going to switch gears and focus more on Brave Core. This is captured there with https://github.com/brave/brave-browser/issues/356
