### ISSUE TITLE
Proper Brave browser attribution is needed in session info of the sites' security section

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#12264]
### Description

Github thinks Brave is Chrome.

![image](https://user-images.githubusercontent.com/4369856/33910139-9fe9f3b8-df42-11e7-8a89-213a357b5497.png)

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@jenn-rhim this is intentional for now, so that Brave users can't be targeted / blocked

cc: @diracdeltas

**Comment by diracdeltas** [comment]
duplicate of https://github.com/brave/browser-laptop/issues/3693

**Comment by luixxiul** [comment]
Closing in favor of #3693.
