### ISSUE TITLE
Feature Request: Adding "CTRL + X" to close tabs

### ISSUE THREAD

**Issue by SupremeRumHam** [brave/browser-laptop#12265]
Have you searched for similar issues? 
Yes

### Description

It would be good to have a shortcut to close tabs, CTRL + X on Windows and CMD + X on Mac.

**Expected result:**
Pressing CTRL + X would close the current tab instead of having to click the close button on the top. Makes for a better UX and help users to manage their tabs with ease.

/* I hope this was enough for a feature request
I tried to follow the contribution guidelines and am not sure if I did or not
*/

**Comment by eljuno** [comment]
I'm not sure why Ctrl+X since it used for "Cut" shortcut. But, Brave use Ctrl+W for close tabs. [See Brave shortcuts](https://community.brave.com/t/brave-browser-shortcuts-currently-for-windows-only/10001/4).

**Comment by SupremeRumHam** [comment]
Oh I forgot about "Cut"
I've tried Ctrl + W several times and it doesn't work for me, so I think I reported the wrong issue then.

**Comment by bsclifton** [comment]
Closing this issue in favor of https://github.com/brave/browser-laptop/issues/1374, which is for tracking the ability to customize the keyboard shortcuts 😄  Please subscribe to that issue for updates
