### ISSUE TITLE
Formatting for Saved Site Exceptions (deleted YT channels) should match ledger table

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12271]
### Description
After deleting a YT channel from your ledger table, if you go to re-add it under Shields > Saved Site Exceptions > Brave Payments, the YouTube channel is listed, the formatting doesn't match how the payments screen displays it.

### Steps to Reproduce

  1. Visit a YT channel for min time so it displays in your ledger table
  2. Click the trash can icon to remove from ledger table
  3. Navigate to Shields > Saved Site Exceptions > Brave Payments

**Actual result:**
Formatting for site name doesn't display the way it does on ledger:
![screen shot 2017-12-13 at 8 55 57 am](https://user-images.githubusercontent.com/28145373/33942286-73084a42-dfe3-11e7-85fd-b04446f0906c.png)

**Expected result:**
Formatting should match ledger for readability and in case user had accidentally removes one.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.115
rev | 584e694
Muon | 4.5.25

**Reproducible on current live release:**
yes

### Additional Information
Similar to https://github.com/brave/browser-laptop/issues/12217

**Comment by NejcZdovc** [comment]
do you think that we need to update old (existing) entries as well or only new ones?

**Comment by LaurenWags** [comment]
@NejcZdovc I think it would be great if we could update the existing entries. WDYT @kjozwiak @srirambv @bsclifton ?

**Comment by srirambv** [comment]
Agreed would be good to have the existing entries updated.

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/39594683-622035b6-4edb-11e8-96e3-ca1cf891dd3e.png)
Verified on Windows x64 
* 0.22.702 e4a853d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7

**Comment by LaurenWags** [comment]
@NejcZdovc if a YouTube or Twitch site was deleted in 0.22.669 and you update to 0.22.702, it displays as below. Expected? 
![screen shot 2018-05-03 at 5 15 12 pm](https://user-images.githubusercontent.com/28145373/39603232-a4f451f0-4ef5-11e8-83e4-a386a35f9077.png)

**Comment by NejcZdovc** [comment]
Just did some more testing and with the latest code that we have for 0.22 we can't preform upgrade for this case anymore, because we don't have information about the name. So this scenario is expected.
