### ISSUE TITLE
Improve verified-caching

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#12272]
## Test plan

https://github.com/brave/browser-laptop/pull/12287#issue-282131024

----

The present algorithm is:

1. Keep a cache of sites mapping to verified status & timestamp
2. On startup, go to the ledger server to determine the latest timestamp
3. When visiting a site, consult the cache: if the entry is present and the timestamp >= the latest timestamp, use that verified status
4. Otherwise, go to the ledger server to get the verified status for the site and cache with timestamp

Proposed changes:

1. In addition to "on startup, get the latest timestamp at regular intervals after startup (I suggest every hour)
2. When the user switches to `about:preferences#payments`, get the latest timestamp -- also make sure that if something changes for a site being listed on that page, that the page gets updated to reflect the current verified status

**Comment by NejcZdovc** [comment]
pulling this one into hotfix 7, because we are receiving quite a lot of questions and comments why verified status is not displayed

**Comment by srirambv** [comment]
Verified time stamp on Windows
```
[ response for GET https://mercury-proxy.privateinternetaccess.com/v3/publisher/timestamp ]
>>> HTTP/1.1 200
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 35
>>> content-type: application/json; charset=utf-8
>>> date: Tue, 09 Jan 2018 10:03:28 GMT
>>> server: Cowboy
>>> strict-transport-security: max-age=31536000
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 9007199254740991
>>> x-rate-limit-remaining: 9007199254740990
>>> x-rate-limit-reset: 1515492209
>>>
>>> {"timestamp":"6508987018276503553"}
```
