### ISSUE TITLE
Clicking on pinned sites in Brave Payments removes them from the pinned list.

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#12274]
### Description

[before clicking Stereokroma YT]
![screen shot 2017-12-13 at 1 11 36 pm](https://user-images.githubusercontent.com/4369856/33962801-97234354-e007-11e7-866c-46679d9a60dc.png)

[after clicking]
![screen shot 2017-12-13 at 1 11 50 pm](https://user-images.githubusercontent.com/4369856/33962807-994dc046-e007-11e7-974b-2a7d5493c1fa.png)

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.19.116

**Reproducible on current live release:**

### Additional Information

Mac 10.13.2

**Comment by NejcZdovc** [comment]
@jenn-rhim I tried to reproduce this, but without success. Can you please provide some more info?
OS, how to reproduce, which version, is this reproducible every time, etc?

**Comment by jenn-rhim** [comment]
I've added Brave vs and OS info above.

It is happening right now, consistently for me.

Go to the Preferences > Payments > click on a pinned site > return to Payments: the site you clicked gets removed from pinned list.  It appears that the same phenomenon doesn't happen on the sites that are not pinned.  -- I've tried this 5 sites each, pinned sites and unpinned sites.

**Comment by NejcZdovc** [comment]
hmm, that's really strange. Will ping you on slack and maybe we can do screen share and figure it out what's going on 😃

**Comment by NejcZdovc** [comment]
@jenn-rhim can you please try this with the latest beta version

**Comment by jenn-rhim** [comment]
@NejcZdovc yes, it is still happening on my browser. i just updated to 0.19.134.  i had @alexwykoff sitting next to me to observe it. :)

**Comment by bsclifton** [comment]
Oh wow- this is really bad. It's happening to me... seems easy to reproduce.  I've lost most of my ledger screen now because of this 😦 

I think this might be the root cause for https://github.com/brave/browser-laptop/issues/12262 which @jenn-rhim also reported

**Comment by bsclifton** [comment]
@NejcZdovc this seems to be related to how there are two synopsis...

For the about page, we set the synopsis here:
https://github.com/brave/browser-laptop/blob/6dece0e68be249b57454fb739a2c97ae2cd90a6b/app/browser/tabs.js#L242

However, in ledgerState, it's setting a different location:
https://github.com/brave/browser-laptop/blob/6dece0e68be249b57454fb739a2c97ae2cd90a6b/app/common/state/ledgerState.js#L96-L107

I found a comment where you reference the duplicate entries:
https://github.com/brave/browser-laptop/blob/6dece0e68be249b57454fb739a2c97ae2cd90a6b/app/sessionStore.js#L479-L483

I suspect that clicking the entry is removing the entry from the `'ledger', 'about'` synopsis by calling prune.  I still have the value in my session store, but it's in the other location `'ledger', 'synopsis'`

**Comment by NejcZdovc** [comment]
I don't have STR, but I have a profile on which I can reproduce it constantly.

**Comment by kjozwiak** [comment]
@bsclifton @NejcZdovc do we have any STR that we could use as a test plan?

**Comment by bsclifton** [comment]
Removing milestone; the issue (as described) was fixed with 0.20.x.  The underlying issue was fixed with https://github.com/brave/browser-laptop/pull/13103
