### ISSUE TITLE
Feature request: multiple users saved

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12270]
### Description
I'd like to be able to have multiple accounts saved, with a different taskbar icon for each acocunt. Avira Scout has this feature, but the browser is not maintained. At the moment I use different browsers for each account.

**Comment by bsclifton** [comment]
Thanks for the report, @jamesray1 😄  I'm going to close this issue as a duplicate of https://github.com/brave/browser-laptop/issues/10324

Please subscribe to that issue for updates.  Thanks!

**Comment by jamesray1** [comment]
Thanks! I did search, but maybe not enough.

**Comment by kenorb** [comment]
> At the moment I use different browsers for each account.

Same as me. I've got over 13 web browser installed on my macOS.
