### ISSUE TITLE
Add links to the grammarly extension request

### ISSUE THREAD

**Issue by CalebBurton** [brave/browser-laptop#12289]
### Description
Grammarly seems to be among the most widely requested extensions (and currently one of the most popular extensions on the Chrome web store), but the card on the Requested board is really bare and doesn't link to any of the requests. I'm not sure if it makes much of a difference to how quickly the extension gets implemented, but could we add the following links to the card so it's easier to see what it is and how much demand there is?

Info about the extension:
- https://www.grammarly.com/
- https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen

Community posts requesting it:
- https://community.brave.com/t/evernote-clearbit-grammarly-pushbullet-mercury-reader-instapaper/4282
- https://community.brave.com/t/grammerly-extension/6685
- https://community.brave.com/t/grammarly-extension/8121
- https://community.brave.com/t/closed-grammarly-coming-soon/1335
- https://community.brave.com/t/consider-adding-grammarly/7811
- https://community.brave.com/t/extensions-we-need-grammarly/7400

**Comment by sergiorojasa** [comment]
I would like to contribute to Grammarly extension.

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄

**Comment by TravisEz13** [comment]
grammarly is not working for me  in brave-core.   This icon shows up 
![image](https://user-images.githubusercontent.com/10873629/45568454-8cbdbd80-b811-11e8-917c-e912550b5a6c.png)
which makes it seem like the extension cannot talk to whatever service it uses.

**Comment by limonte** [comment]
> grammarly is not working for me in brave-core. This icon shows up

Same here (e.g. for github.com):

![image](https://user-images.githubusercontent.com/6059356/45570478-8ceaa700-b86b-11e8-8fac-29cf159fbe7d.png)

BraveDev latest (Version 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit))

**Comment by bsclifton** [comment]
@TravisEz13 @limonte I created a new issue to track the problem you're experiencing:
https://github.com/brave/brave-browser/issues/1141

This repo (`browser-laptop`) is for the older version of the browser. If you run into any more issues, you can search/open new issues here:
https://github.com/brave/brave-browser
