### ISSUE TITLE
Fonts not loading correctly on master

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12280]
There are problems with the rules introduced in #12225 - font files are matching multiple rules causing the browser to not be able to parse and display the fonts.

### Steps to Reproduce
Open new tab page

**Actual result:**
Fonts are system fonts.
Console has many errors related to fonts.

![image](https://user-images.githubusercontent.com/741836/33985155-a41a43f6-e11e-11e7-8bc0-40e8dac8f5e0.png)

**Expected result:**
Fonts used are Poppins / Muli.
Console has no errors.

![image](https://user-images.githubusercontent.com/741836/33985223-e2c97e28-e11e-11e7-99ca-5a7e567f37b9.png)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
master

**Reproducible on current live release:**
No

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
