### ISSUE TITLE
LastPass disappears, loses all functionality (ERR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by DanielJenkyn** [brave/browser-laptop#12285]
Have you searched for similar issues? 

- Yes

### Description

After logging back into my Macbook (2016 model) in the morning, Lastpass has suddenly disappeared with the following error:

<img width="298" alt="screen shot 2017-12-14 at 09 59 45" src="https://user-images.githubusercontent.com/11617329/33986518-ae6f52f6-e0b5-11e7-948e-228d19eac21d.png">
(This what it actually looks like, I haven't awkwardly cropped this screenshot on the right hand side)
After killing and reopening Brave several times, LastPass reappears

### Steps to Reproduce

  1. Log off Macbook / close lid
  2. Open lid, log back in
  3. LastPass Extension icon disappears with the error 

`Your file was not found It may have been moved or deleted. ERR_FILE_NOT_FOUND` 

**Actual result:**

- See above Image

**Expected result:**

- LassPass to open as usual

**Reproduces how often:**
~25%

### Brave Version

**about:brave info:**

``` 
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.2.0 
OS Architecture: x64
```
**Reproducible on current live release:**

- Yes

### Additional Information

- All LastPass functionality is lost
- Whilst logged off I thought my Macbook may of updated - it hadn't

**Comment by traderd65** [comment]
Lastpass extension stopped working (blank popup dialog shows when pressing on extension icon) then disappears altogether with latest browser upgrade 0.19.139 on Windows 10 (x64) Dell laptop. When disabling then re-enabling the extension, the logo shows up but same problem. Have to use a full Lastpass browser tab (vault) to use the pwd mgr logins.

**Comment by DanielJenkyn** [comment]
@bsclifton In the past few weeks I've only seen it once. From a user perspective, not an issue anymore

**Comment by bsclifton** [comment]
@DanielJenkyn awesome- I'll close this issue for now... but let's re-open if it resurfaces 😄 Thanks for verifying 😄

**Comment by atrepca** [comment]
Just bumped into this too, the extension was gone after a reboot, with the error described here. I was able to restore functionality by disabling the extension, restarting Brave, and re-enabling it.

**Comment by deronsizemore** [comment]
I forgot to follow up. Seemed to be fin after closing the browser a couple times. I'm good to go now.

**Comment by srchulo** [comment]
I'm still seeing this now on Windows 10 with LastPass version 4.9.1.0 and this Brave Version Info:


Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Comment by srchulo** [comment]
When I closed and opened Brave it appeared again, but I had to login.
