### ISSUE TITLE
"Never include" messaging needs awareness

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12296]
## Test plan

https://github.com/brave/browser-laptop/pull/12960#issue-293269896

----

### Description
When right-clicking a YouTube Channel in Brave Payments, the user is provided the option to _Never include this site_. Instead, the option should be aware that the user has not selected a site, but a YouTube Channel. Perhaps a general term (_Never include this content_) should be adopted.

### Steps to Reproduce
1. Right-click a YouTube channel in Brave Payments.

**Actual result:**
_Never include this site_

**Expected result:**
_Never include this content_

**Reproduces how often:**
100%

### Brave Version
0.19.116

![image](https://user-images.githubusercontent.com/815158/34017852-f9ed16e6-e0ec-11e7-95b7-e386cc65e7d8.png)

**Comment by NejcZdovc** [comment]
@jonathansampson what if we would say `Never include this publisher`?

**Comment by jonathansampson** [comment]
@NejcZdovc That would be better, but I don't think _Publisher_ really describes YouTube Channels very well. I think we should either come up with a single word/phrase that describes both, or conditionally check the type of item before printing the label.

**Comment by NejcZdovc** [comment]
@jonathansampson yeah we can do type check, but why I said publisher is because when communicating to the public we always say publishers and we have publishers.basicattentiontoken.org

**Comment by jonathansampson** [comment]
@NejcZdovc Publishers was the original term used, when we were supporting only sites. But when we added support for YouTube, we made brave.com/creators. It could go either way. To me, "publishers" refers only to text. Something vague like _Content Creator_ can be any type of media and/or format.

**Comment by NejcZdovc** [comment]
maybe `Never include this creator`?

**Comment by NejcZdovc** [comment]
To fix this problem we need to modify string `deleteLedgerEntry` in `.properties` file.

**Comment by MargarytaChepiga** [comment]
Hi, I am new to Brave and I would love to work on this if this is still available!

**Comment by NejcZdovc** [comment]
@MargarytaChepiga yes it's still available. Will assign issue to me, so that no one will take it. If you need any help let me know

**Comment by MargarytaChepiga** [comment]
Hello, I am all set to fix this. The only thing is that I am not sure is to which message I should change the existing one. How about  `Never include this content creator`? Or should I stick to the mentioned above `Never include this creator `? Thanks!

**Comment by MargarytaChepiga** [comment]
I know Ukrainian and Russian, so I might as well change the string in those languages as well.  Is that okay?

**Comment by bsclifton** [comment]
@MargarytaChepiga no need to modify Ukrainian or Russian- the process for translations is a little different. In this repo, you only need to update the `en-US` version

For more information on our translations (and to sign up to help 😄 ), please see:
https://github.com/brave/browser-laptop/blob/master/docs/translations.md

**Comment by MargarytaChepiga** [comment]
@bsclifton Great! Thank you so much!

**Comment by btlechowski** [comment]
Verified 0.21.9 Win64

**Comment by kjozwiak** [comment]
As per our earlier conversation with @NejcZdovc in the `#testers` channel, ledger functionality won't work until the twitch code is pulled in which includes the updated BAT libraries.

Removed ` QA/checked-Win64` as we should re-test this just incase once Twitch lands.

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.

**Comment by srirambv** [comment]
Reopening based on https://github.com/brave/browser-laptop/pull/12960#issuecomment-368814216

**Comment by srirambv** [comment]
Closing the issue as its an issue with missing translations
