### ISSUE TITLE
Add tests for pinned tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#123]

**Comment by bbondy** [comment]
- Test closing a pinned tab should go to next tab
- Test closing a pinned tab when no other tabs exist should close the window

**Comment by rob-blasetti** [comment]
The tests have been added in a pull request! :D

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/b17bb89f656e982d4140aed172539d6d5f8f30aa
https://github.com/brave/browser-laptop/commit/4a9aa677efe5c5fc65148c05af413c220bda91e4
https://github.com/brave/browser-laptop/commit/0f0fa250ac7434433a5b719c079556f68b2654ba
