### ISSUE TITLE
Updating UPDATE_HOST to point to brave.com cname

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#12304]
UPDATE_HOSTs are set to *.fastly.net. Update these entries to point to brave.com cnames

**Comment by bsclifton** [comment]
@jumde can you provide a test plan for this issue?

**Comment by jumde** [comment]
From the PR: 
```
Testing Notes: Geo logs for brave stats are captured using fastly. After this change download and update requests will go through brave domains which should go through fastly.net. Verify if stats is working correctly.

Also, verify if the  request for Brave updates are going through brave domains, instead of fastly.net.
```

cc: @diracdeltas

**Comment by cezaraugusto** [comment]
I guess this should be in `release-notes/exclude` given this seems more like an infrastructure thing? not sure if this improves something for users

**Comment by cezaraugusto** [comment]
thus `no-qa-needed`?
