### ISSUE TITLE
Check for updates does not work over SOCKS5 proxy on OSX on Brave 0.8.3

### ISSUE THREAD

**Issue by zeroshirts** [brave/browser-laptop#1230]
Corporate firewall blocks TCP/443 and TCP/80, so I have a SOCKS5 proxy configured in System Preferences -> Network -> {Interface} -> Proxies.  Would be great if Brave could respect this setting and update.  FWIW, Chrome is able to update over SOCKS5.

**Comment by luixxiul** [comment]
Has this been fixed, or will be? CC'ing @bbondy

**Comment by zeroshirts** [comment]
Still broken for me on OSX Brave 0.9.6
"Oops!  We were not able to update."

2016-05-15T17:02:43.334Z - https://brave-laptop-updates.global.ssl.fastly.net/1/releases/dev/0.9.6/osx?daily=true&weekly=true&monthly=true&first=false
2016-05-15T17:03:59.011Z - Error: connect ETIMEDOUT 23.235.40.249:443

**Comment by luixxiul** [comment]
Duping to #770
