### ISSUE TITLE
Lastpass doesn't work in username and password fills for Google after updating to 0.19.118 today

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12309]
### Description
Lastpass doesn't work in username and password fills for Google after updating to 0.19.118 today.

### Steps to Reproduce
  1. Try to log in to Google. Select your account and click the lastpass icon to the right of the password field.

**Actual result:**
Nothing happens.

**Expected result:**
The password fills in.

**Reproduces how often:**
100%

### Brave Version
 
Brave: 0.19.118 
rev: ac83e87a682b0899b3d3723efb1aaa08c8bc2ad1 
Muon: 4.5.28 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by echosa** [comment]
I'm experiencing the same issue. I can use the LastPass icon in the URL bar area to autofill, but clicking the icons in the form fields themselves doesn't work. Nothing happens when you click them (no menu is presented).

```
Brave | 0.19.134
-- | --
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.3.0
OS Architecture | x64
```

**Comment by jamesray1** [comment]
@echosa thanks for pointing this out, I've continued to experience this on Windows annnd Linux.

 
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-29-generic 
OS Architecture: x64

**Comment by jamesray1** [comment]
This doesn't work on Firefox either, but it does on Google Chrome.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/lastpass-form-fill-unresponsive/22401
