### ISSUE TITLE
Multiple deprecated Warnings

### ISSUE THREAD

**Issue by Rahmeen14** [brave/browser-laptop#12306]
### Description
Hi! I'm new to open source and want to begin contributing with Brave. For that, i followed the [Windows build guide](https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide). After ```npm install``` I found a lot of deprecation warnings:
```
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.7 should be installed with -g
```
There are many other such warnings. Is that a problem only with my system? Or is package.json required to be updated, in which case I would like to this up as my first my first ever PR attempt for Brave and Open Source. 
Thank You.

**Comment by bsclifton** [comment]
@Rahmeen14 they should only be warnings and everything should still work as expected.  Can you confirm that you're able to run the browser locally from source? If so, the warnings can be ignored.  

Since warnings are not ideal, we can use this issue to track the work needed to fix them 😄
