### ISSUE TITLE
Error retrieving promotion

### ISSUE THREAD

**Issue by SohumB** [brave/browser-laptop#12311]
### Description
#12080 again. Error retrieving promotion Error: HTTP response 404 for GET /v1/grants?paymentId=[id]

### Steps to Reproduce
1. Clean install 0.19.116
2. Launch from console
3. Enable payments, no claim tokens notification shown
4. Console shows error 404

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.19.116 
rev: 139c117e9b1935029682d207798a3f47b5bdd1fe 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-1-amd64 
OS Architecture: x64

**Comment by NejcZdovc** [comment]
@SohumB this is expected, because currently no promotion is active. Will remove logging for this use case. Thank you for your report

**Comment by SohumB** [comment]
Oh, my apologies. The actual issue then is that no wallet addresses for funding payments shows up. I'll make a new issue.

**Comment by NejcZdovc** [comment]
@SohumB yes please do if you have any more problems with payments

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.

**Comment by LaurenWags** [comment]
In addition to Test Plan, started Brave with LEDGER_VERBOSE=true to see 404 promotion error.

**Comment by kjozwiak** [comment]
Received the 404 when running brave via `LEDGER_VERBOSE=true brave-beta --user-data-dir-name=brave-beta`:

> >>> {"statusCode":404,"error":"Not Found","message":"no promotions available"}
> Error retrieving promotion Error: HTTP response 404 for GET /v1/grants

Ensure that I didn't get the above 404 error when running brave without `LEDGER_VERBOSE=true`.
