### ISSUE TITLE
entire window goes completely white/non-responsive under linux and produces "Window crashed, Reloading..." via terminal

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12317]
### Description

When closing Brave under Ubuntu, the entire window will go "white" and will take anywhere between 15-30s to close the browser. You'll sometimes also see the following error in the terminal:

`Window crashed, Reloading...`

When running via source, you'll see the following errors in the terminal when closing:

```
Crash dump id: OK
Crash dump id: OK
process exited with code 0
```

### Steps to Reproduce

  1. launch `0.19.119` which includes `63.0.3239.108`
  2. click on the `Kabob` menu and select `Quit Brave`

**Actual result:**

![exitubuntu](https://user-images.githubusercontent.com/2602313/34127438-28b7e930-e40b-11e7-97fb-da0307095957.gif)

**Expected result:**

Brave should quit instantly, or at least quickly without any issues.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.119 
> rev: 697289eab4c232af18c1ed8c34a8a7bb6a9a3ccf 
> Muon: 4.5.29 
> libchromiumcontent: 63.0.3239.108 

**Reproducible on current live release:**

Not reproducible under `0.19.116` which is the currently released version.

### Additional Information

* Ubuntu 17.10 x64 - Reproduced
* Ubuntu 17.04 x64 - Reproduced
* Ubuntu 16.04 x64 - Reproduced
* macOS 10.13.1 x64 - Not reproducible by @LaurenWags 
* Win 10 x64 x64 - Not Reproducible by @srirambv 

CC'ing @darkdh & @bridiver.... Possibly related to #12298

**Comment by kjozwiak** [comment]
While watching a YT Live video while testing the ledger, Ubuntu crashed and noticed `Window crashed, Reloading...` under the terminal again:

<img width="1538" alt="screen shot 2017-12-18 at 4 15 32 pm" src="https://user-images.githubusercontent.com/2602313/34128643-5dfdff40-e40f-11e7-8d2c-a96c79d6cd95.png">

I'm not 100% sure if this is the same issue but figured I would add the info here. Unfortunately, I don't have STR.

**Comment by capouch** [comment]
@kjozwiak Looks like .120 is good to go, so far.  Been up 20-30 minutes without any issues.

**Comment by srirambv** [comment]
Quits properly on 0.19.120 under Kabob menu.
![12317](https://user-images.githubusercontent.com/17010094/34155866-e47f4238-e4b2-11e7-984b-5a343a4fbf43.gif)

**Comment by kjozwiak** [comment]
I've been using `0.19.121` for a few hours now and haven't seen the random window crashes as mentioned under https://github.com/brave/browser-laptop/issues/12317#issuecomment-352561860. 👍
