### ISSUE TITLE
'open in new window' does not cascade as expected

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12315]
### Description
When you 'open in new window' Brave cascades as per https://github.com/brave/browser-laptop/issues/8925 - however once the cascaded window opens at the bottom of your screen, new windows only open offset to the right, not up and to the right (see gifs below) and eventually pile on top of each other again.

### Steps to Reproduce

  1. Position Brave window in similar point to gif in Actual result section.
  2. Continue to open new windows.
  3.

**Actual result:**
![brave-cascade](https://user-images.githubusercontent.com/28145373/34122306-f9255cf4-e3f9-11e7-8669-b9f45f2e60bd.gif)

**Expected result:**
Expected cascading similar to Chrome:
![chrome-cascade](https://user-images.githubusercontent.com/28145373/34122311-01aa492a-e3fa-11e7-99fe-ea322c12e42e.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.20.7

**Reproducible on current live release:**
no

**Comment by srirambv** [comment]
Personally I prefer the current behaviour only because all windows are visible and easy to switch unlike Chrome where after a set of windows it starts overlapping from top.

**Comment by srirambv** [comment]
On Windows, it doesn't stack next to each other after the browser window hits the screen bottom. It continues to cascade in front 
![image](https://user-images.githubusercontent.com/17010094/34274175-562548f0-e68f-11e7-83ca-d1a40f90974c.png)

**Comment by srirambv** [comment]
This will be fixed in brave-core. Out-of-box feature in brave-core
