### ISSUE TITLE
Investigate if heroku can fetch geo location logs for laptop-updates/download.brave.com

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#12320]
For enabling PKP for requests for Brave artifacts, see: https://github.com/brave/muon/pull/401. 

We need to update `*_UPDATE_HOSTS` to have granular control.

**Comment by diracdeltas** [comment]
this may not be necessary. as mentioned in slack, i think if fastly is set up properly as a cname for brave.com domains then it should be able to get the logs for those domains regardless of https://github.com/brave/browser-laptop/pull/12305/
