### ISSUE TITLE
Browser crash when visiting URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12327]
### Description
Reported by @bbondy  when opening the URL browser crashes 

### Steps to Reproduce

  1. Clean install/upgrade to 0.19.120
  2. Visit the URL https://bat-publishers-staging-2.herokuapp.com/
  3. Browser crashes

**Actual result:**
Browser crashes when opening the link

**Expected result:**
Should not crash

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.120
-- | --
rev | 028351e
Muon | 4.5.30
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
No

**Comment by kjozwiak** [comment]
Great catch @bbondy 👍
