### ISSUE TITLE
Idle mouse interferes with address bar searching

### ISSUE THREAD

**Issue by jaxidian** [brave/browser-laptop#12329]
### Description
An idle mouse cursor below the address bar will interfere with behavior if you are using the address bar to perform a search.

### Steps to Reproduce
  1. Have a tab browsing pretty much any web page
  2. Click on the page to put focus into that web page
  3. Move mouse cursor to a couple inches below the address bar
  4. Press CTRL+L to put focus into the address bar to perform a search
  5. Begin typing such that you get history results displaying (I'm testing with "wifi", no quotes, which brings up several pages I've previously viewed)
  6. Without ever touching your mouse, after you're done typing the above text ("wifi"), hit [ENTER].
  7. **BUG**: Observe that instead of performing a search for that term, instead, the idle mouse highlighted one of your history items and the [ENTER] keypress then navigates you to that page.

**Actual result:**
The tab navigates to the page in your history that the idle mouse cursor just happened to be over. This is especially confusing when you want to enter a search term very quickly and hit enter without waiting for anything - it still opens a seemingly-random page.

**Expected result:**
I expect the tab to submit my search text to the search engine (or navigate to a URL if I had typed one). It should ignore the mouse cursor unless I am actively using it.

**Reproduces how often:**
100%

### Brave Version
Brave: 0.19.116 
rev: 139c117e9b1935029682d207798a3f47b5bdd1fe 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/12530
