### ISSUE TITLE
USD first, BAT second in the monthly budget dropdown

### ISSUE THREAD

**Issue by Alino** [brave/browser-laptop#12321]
could we get this functionality as mentioned here? It makes much more sense.
https://www.reddit.com/r/BATProject/comments/7klngl/bat_monthly_budget_dropdown_should_revert_the/

currently there are these options:

     25 BAT (9.11 usd)
     50 BAT (18.22 usd)
     75 BAT (27.33 usd)    
     100 BAT (36.44 usd)

I believe this should be reversed and fixed by amount of usd. Something like this:

     5 usd (13.16 BAT)
     10 usd (26.32 BAT)
     20 usd (52.64 BAT)
     custom amount of usd

The reason is, that the price is too volatile, and people don't want to donate 25 BATs if it will mean that it is 20 bucks.

related issue -> https://github.com/brave/browser-laptop/issues/3654

**Comment by bsclifton** [comment]
cc: @bradleyrichter @jenn-rhim @alexwykoff

**Comment by NejcZdovc** [comment]
@Alino if we switch to USD we have can have a big problem. Everything in payments is based on BAT's. You have BAT wallet, you transfer money in crypto currency that is then converted in BAT, etc. Problem like you said is that price is quite volatile. So let's say that you transfer 10BAT's that is equivalent to 5$ and you have your monthly budget set to 5$. Now it's contribution date and BAT takes a big hit. Your 10 BAT's are now worth 2$, but your monthly budget is still 5$. So you would need to transfer some more BAT's to meet 5$ amount. Which is a problem. But if everything is based on the same currency all this problems are gone.

**Comment by Alino** [comment]
@NejcZdovc I don't see any problems if we switch to USD.
1. You are correct that we do have BAT wallet (not usd wallet) - this is not a problem.
2. And as you mentioned if you had 10 BAT and they became worth of $2,
then you would contribute just $2 instead of $5.
Why do you see this as a problem?

**Comment by NejcZdovc** [comment]
@Alino problem is that we have a check in the code. Let's say that you have not $2 and monthly budget is $5. We will not allow contribution until you have $5 in your wallet.

**Comment by Alino** [comment]
@NejcZdovc What's good about code is that it can be changed :) I believe you should change this.

**Comment by NejcZdovc** [comment]
well how can we know if user have enough balance in the wallet. What should be our check (of course we need to have a check)? Now for example if you have 20 BAT's and your monthly budget is 25 BAT's, we inform you that you need to deposit 5 more BAT's to make monthly contribution. But if we switch to USD and we don't have any checks how do we know that you have enough money for monthly contribution?

**Comment by Alino** [comment]
I don't understand why do you need to send the exact amount that you set in monthly budget.
I would just make it possible to send even lesser amount that you have in currently in the wallet.

Scenario 1:
Given that user has 10 BAT
And 10 BAT is worth of 20$
And the user has set monthly budget for 10$
Then 5 BAT are spend on contribution

Scenario 2:
Given that user has 10 BAT
And 10 BAT is worth of $5
And the user has set monthly budget for $10
Then 10 BAT are spend on contribution

**Comment by NejcZdovc** [comment]
ok I think that I have a clearer image now about your proposal. I see that you already found #3654 about monthly fixed budgets. So yeah to achieve your proposal we would need to remove strict monthly budget and allow contributions bellow monthly budget. Not sure that I am fan of this, because currently you know exactly how much BAT you are sending, but if you are sending USD you never know how much you will send.

@bsclifton already cc-ed design and product members to check this thread out. Thank you for your suggestion

**Comment by Alino** [comment]
@NejcZdovc I understand your point of view that you don't know the amount of BAT that you would be sending, but I believe for people BAT is not important, but **value** is.
Thank you very much for the discussion on this.

**Comment by NejcZdovc** [comment]
@Alino my pleasure, I think that we made a lot of useful pointers for out team to help them decide

**Comment by Alino** [comment]
@NejcZdovc exactly.
By the way team, I think it is important to address this issue with higher priority, I think market cap of BAT will soon get to 1 billion.  📈 
Only small amount of people are willing to donate $25 per month. 💰 
In order to keep the donations flowing 🚰 , this needs to be fixed.

**Comment by bradleyrichter** [comment]
There are some issues on both sides of this argument. For a quick improvement, I agree we should add a lower and higher amount in the list. I removed 75 BAT just to keep the list shorter.

We can also step-move as BAT value increases to keep selections available in the 5-20 USD range.

![image](https://user-images.githubusercontent.com/13509546/34186957-a4ead0de-e4e3-11e7-9cf5-9e44f2cc8f88.png)
@Alino , @NejcZdovc do you think this is a good step?

**Comment by NejcZdovc** [comment]
@bradleyrichter yeah I think that there were some demand for this as well, so adding some more budgets would be a nice start

**Comment by Alino** [comment]
@bradleyrichter as a quick fix, it's good to add lower amount of BAT in the list.
But I still believe it should be reversed as I have suggested for the reasons I already mentioned.
If you see any issues in my suggestion, please let's discuss them.
