### ISSUE TITLE
Reload sometimes stops working until browser restart

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#12333]
### Description
Sometimes I hit ^R or press the reload button, and nothing happens, whether I do a normal reload or clean reload.

### Steps to Reproduce

  1. Use Brave for a while.
  2. Try to reload the page.
  3. Not sure I have any other brilliant ideas for how to reproduce.

**Actual result:**
Nothing.

**Expected result:**
Page should reload.

**Reproduces how often:**
Every hour or so, maybe.  Haven't been keeping close track.

### Brave Version

**about:brave info:**

Brave | 0.20.6
-- | --
V8 | 6.2.414.36
rev | 18f7d1e
Muon | 4.5.14
OS Release | 4.10.0-40-generic
Update Channel | Beta
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.75

**Reproducible on current live release:**
Not sure, have not noticed on not-beta.

**Comment by kjozwiak** [comment]
@bbondy has ran into this several times in the past few days. @riastradh-brave mentioned that it used to happen every ~hour, now it happens every ~day or so. Once you run into the issue, `command + r` breaks throughout Brave and requires a restart. However, `Shift+Command+R` seems to always be working.

If this gets reproduced/fixed before `0.20.x Hotfix 2`, we should probably uplift.

**Comment by bsclifton** [comment]
@riastradh-brave are you still experiencing this with the live release (0.20.30)? I believe this was fixed before we shipped 0.20.x.  You can also try the latest Beta (0.21.x) 😄 which I just released (0.21.9)
