### ISSUE TITLE
Opening and closing the console via F12 terminates the browser

### ISSUE THREAD

**Issue by NumDeP** [brave/browser-laptop#12343]
Have you searched for similar issues? Yes

### Description
I was in the community page and I accidentally must have pressed F12 which loaded the console and after closing the console it practically immediately exited the browser. 

### Steps to Reproduce

  1. Obviously open the browser
  2. Go to https://community.brave.com/
  3. Press F12 in Win and close console after it appears. 

**Reproduces how often:**
I've tried it five times already and it terminated the browser immediately all five times. 

What percentage of the time does it reproduce? 100% with https://community.brave.com/ on one tab

### Brave Version

**about:brave info:**
 
Brave: 0.19.121 
rev: 9e8ffc423a7061e5cafd262bb46c1ada17971db0 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

### Additional Information
I've noticed this issue mostly if not always occurs with https://community.brave.com/ as the first tab to be loaded from startup

**Comment by bsclifton** [comment]
@NumDeP does this still happen with our latest release?

**Comment by NumDeP** [comment]
Sorry for the late reply @bsclifton I'm coherently using Linux Mint Xfce and sure enough it is. Though I should mention I cannot repeat it as often as before.

Just a small side note, the version I'm using is the latest one under Snap, I can't for some reason successfully make Yarn work properly in Mint. I'll probably try it in Suse.

Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by jonathansampson** [comment]
I just tried reproducing this on Windows (using the STR above) and was unsuccessful. I suspect this issue no longer exists. @NumDeP, can you ensure that you are running the latest version of Brave, and see if this still reproduces?

**Comment by NumDeP** [comment]
Hi @jonathansampson you're best of closing it the issue; I'm using 0.22.810 in Suse (not Mint) and I can no longer reproduce the issue.
