### ISSUE TITLE
Paste and search uses default search engine instead of DDG in private tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12346]
### Description
Paste and search uses default search engine instead of DDG in private tabs

### Steps to Reproduce
  1. Enable Private search in Search settings
  2. Open a private tab
  3. Copy a text and right click in URL bar and `Paste and Search`, opens default search engine page instead of DDG

**Actual result:**
![ddg](https://user-images.githubusercontent.com/17010094/34230379-d4a563c4-e5cf-11e7-87cd-d733650095a9.gif)

**Expected result:**
Should search using private search engine DDG

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.121
-- | --
rev | 9e8ffc4
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
~~@w0ts0n confirmed working as expected on macOS~~ Same behaviour on macOS as well.

**Comment by kjozwiak** [comment]
Still reproducible with `0.21.24` 19c78a1 using macOS 10.13.3 x64.

**Comment by Slava** [comment]
I dug a little into this, seems like the code for using private search is never reached as a conditional branch here is always hit: https://github.com/brave/browser-laptop/blob/c08c815177a074d68f155614895f17bbacb31f50/app/renderer/reducers/urlBarReducer.js#L29
