### ISSUE TITLE
brave not launching under linux

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12348]
### Description

Brave BETA doesn't launch after being installed via the `.deb` package. Launching Brave via the terminal using `brave-beta` doesn't do anything.

### Steps to Reproduce

  1. install brave via `sudo dpkg -i Desktop/brave-beta_0.20.8_amd64.deb`
  2. if missing dependencies, run `sudo apt --fix-broken install`
  3. once you've installed brave, run it via `brave-beta` under the terminal

**Actual result:**

<img width="1257" alt="screen shot 2017-12-20 at 5 08 54 pm" src="https://user-images.githubusercontent.com/2602313/34231048-7bc2631e-e5a8-11e7-82a5-54a1c5d77e64.png">

**Expected result:**

Brave should be launching without any issues.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

 

> Brave: 0.20.8 
> rev: 015a3db28920076ee5951d6e21580dd0520ec1c3 
> libchromiumcontent: 63.0.3239.108
> V8: 6.3.292.48 

**Reproducible on current live release:**

Not reproducible under `0.19.121` which is the current release.

### Additional Information

* Ubuntu 17.10 x64 - Reproduced
* Ubuntu 17.04 x64 - Reproduced
* Ubuntu 16.04 x64 - Reproduced

**Comment by darkdh** [comment]
0.20.8 uses muon 4.5.28.
Please upgrade to 4.5.31 which will solve this problem.

**Comment by bsclifton** [comment]
Building a new version now 😄

**Comment by bsclifton** [comment]
@darkdh with the latest (which has updated Muon), I'm seeing it launch quickly and then exit
https://github.com/brave/browser-laptop/releases/tag/v0.20.9beta

Could this be related to the relaunch that happens for `user-data-dir-name`?  I tried manually specifying that and it seems to crash:
```
clifton@clifton-VirtualBox (master *=) $ brave-beta --user-data-dir-name=brave-beta
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
Waiting 60 seconds for process to load
Trace/breakpoint trap (core dumped)
```

**Comment by darkdh** [comment]
<img width="452" alt="screen shot 2017-12-21 at 5 54 34 am" src="https://user-images.githubusercontent.com/11330831/34258612-827a805e-e613-11e7-9747-db7902cccd98.png">

I can't reproduce it with or without `user-data-dir-name`.
without `user-data-dir-name`, it will just relaunch brave with `user-data-dir-name`. so it is not a cause to the crash you saw.

**Comment by bsclifton** [comment]
I was accidentally testing using the old version, I believe. I removed using `dpkg -r brave-beta` and reinstalled 0.20.9 and it worked great, as expected 😄  Thanks, @darkdh!

**Comment by kjozwiak** [comment]
Using `0.20.9`, went through the following platforms:

* Ubuntu 17.10 x64 - PASSED
* Ubuntu 17.04 x64 - PASSED
* Ubuntu 16.04 x64 - PASSED
