### ISSUE TITLE
View page source shows about:blank in URL and URL missing from the source page tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12344]
### Description
View page source shows about:blank in URL and URL missing from the source page tab

### Steps to Reproduce

  1. Clean install 0.20.8
  2. Visit any page and right click -> view page source
  3. Page source is opened in a new tab but has `about:blank` in URL bar
  4. Switch back to source page tab, URL is missing (intermittent issue)

**Actual result:**
![view_page_source](https://user-images.githubusercontent.com/17010094/34229349-d7907f1e-e5cb-11e7-8ded-c74323dfb737.gif)

**Expected result:**
View page source tab should show proper URL formatting `view-source:<full URL>`

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.8
-- | --
V8 | 6.3.292.48
rev | 015a3db
Muon | 4.5.28
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton

**Comment by diracdeltas** [comment]
cannot repro on mac. tried 09728fe689297eeb1248f2b9759e6b0f8074ca11 and 8dc6b12a5a3233a55916757f8931fea750c367ea

**Comment by srirambv** [comment]
Dupe of #11796
