### ISSUE TITLE
about pages is listed in the history menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12359]
### Description
About pages are listed in the history menu

### Steps to Reproduce
   1. Open couple of about pages
   2. Close the about pages
   3. Open menu-> history -> all closed about pages are listed in history menu

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/34263126-5902841c-e666-11e7-88f1-bf252e975c29.png)

**Expected result:**
Should not list about pages in history menu

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.122
-- | --
rev | 009e792
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by luixxiul** [comment]
I'm neutral to hide about pages from the list. Is it a de facto standard maybe?

**Comment by PatMB30** [comment]
Hi, i'd like to start working on this issue.
