### ISSUE TITLE
sync V2: Add remove function for any single device in sync chain

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12356]
As a user, I need to be able to remove a device from my device list in the case that that device was lost or otherwise no longer accessible to me.

**Feature:**
Any device in the sync chain will have the ability to remove any other device. When a device is removed, a new file is posted to the server and the previous data file is deleted. The new data file holds a record of the deleted device. 

See desktop UI:
![image](https://user-images.githubusercontent.com/13509546/34239326-8ec2f1a0-e5bb-11e7-9354-8f046d3d9c6e.png)

**Approach:**
This record is read by other devices in the sync chain so that they can update the status of the deleted device in their local lists. 

If the device itself has been deleted from the chain, it will read it's own deletion file and display a dialog. "The sync chain is no longer available to this device."

**Dialogs:**
If the active device (this computer) is removed, a warning dialog will appear explaining the result.

![image](https://user-images.githubusercontent.com/13509546/34269481-50a82114-e639-11e7-9617-37cc7429600e.png)

If a different device is removed, a different warning dialog appears to confirm the result. 

![image](https://user-images.githubusercontent.com/13509546/34269511-745f4a38-e639-11e7-805a-e6ad3c819eda.png)

Notes:
If the active device is removed, the UI will reset to the first-time-use wizard.

The delete button from the ledger UI control should be used in this device list.

The device list styles should match other list controls.

**Comment by bsclifton** [comment]
Closing as `wontfix` since we're going to switch gears and focus more on Brave Core. This is captured there with https://github.com/brave/brave-browser/issues/356
