### ISSUE TITLE
Brave Web Browser .Desktop File

### ISSUE THREAD

**Issue by majomuchi123** [brave/browser-laptop#1235]
Please make the installer add .desktop file during installation.

In the mid-time, everyone who wants a workaround, make your own Brave.desktop file in `/usr/share/applications` with the following content:

But first download icon from  [Brave icon](https://www.brave.com/favicon.ico) and make it .png with [Iconvert Icons](https://iconverticons.com/online/)

```
[Desktop Entry]
Name=Brave Web Browser
GenericName=Web Browser
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=/opt/Brave-linux-x64/brave
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/icons/Brave.png
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
```

**Comment by luixxiul** [comment]
If you submit PR it will be appriciated, thanks.

**Comment by luixxiul** [comment]
Please let me know if the issue persists in spite of the PR.

**Comment by bsclifton** [comment]
This should be fixed now 😄  I believe the icon was added by @Sh1d0w last year and our rpm/deb packagers are creating this .desktop file

cc: @darkdh who also recently dealt with this code too (and has some changes landing soon in the upcoming channels release)
