### ISSUE TITLE
sync v2: finish total sync-chain removal feature

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12364]
As a user, I need to be able completely remove a sync chain from any device where all devices in the chain will be removed after a confirmation dialog.

![image](https://user-images.githubusercontent.com/13509546/34270372-d6e1e4a6-e63c-11e7-8d68-0c850d55ef8a.png)

The device that executes the command will update the sync database to remove all files. Each individual device will need to recognize that they were removed and update accordingly. This includes a notification message to the user when they next poll the sync server, or push new data.

**Comment by cezaraugusto** [comment]
how this differs from current "reset sync" functionality?

<img width="741" alt="screen shot 2018-02-05 at 4 41 43 pm" src="https://user-images.githubusercontent.com/4672033/35822481-8d2cc6ac-0a93-11e8-9bbe-e3f4344005b3.png">

**Comment by NejcZdovc** [comment]
@cezaraugusto I think this feature removes data from other devices as well, where reset removes it only from this device

**Comment by bsclifton** [comment]
Closing as `wontfix` since we're going to switch gears and focus more on Brave Core. This is captured there with https://github.com/brave/brave-browser/issues/356
