### ISSUE TITLE
Authentication with embedded MJPEG stream

### ISSUE THREAD

**Issue by af7567** [brave/browser-laptop#1236]
I have a webpage showing a few MJPEG streams from IP cameras.  Some require authentication and some don't.  The ones which don't need authentication display OK but the ones needing a login show as broken images and I am not asked for any login details.

If I go directly to the MJPEG url then I get asked for the login details and the stream works OK, I am not asked if I would like to save the credentials though.

**Comment by cezaraugusto** [comment]
@af7567 could you please upgrade to the current version and see if it still persists?

**Comment by af7567** [comment]
I just downloaded 0.11.0 and tried it but I still have the same problem. 
The HTML of the page with the problem is just this:
````
<html>
<title>Camera 4</title>

<body>
<h1>Camera 4</h1>

    <img src="http://82.70.xxx.xxx:8004"/>
</body>
</html>
```

I see a broken image link, but if I right click the broken image and open image in a new tab it asks me for the username and password and then displays the MJPEG stream OK.
