### ISSUE TITLE
Duplicate pinned tabs on tear off window which doesn't close when all tabs are closed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12377]
## Description
Duplicate pinned tabs on tear off window which doesn't close when all tabs are closed

### Steps to Reproduce
  1. Clean install 0.20.9
  2. Open a new site in a tab
  3. Tear off the about:welcome tab into a new window
  4. Go back to window 1 and pin the site you opened in step 2
  5. Tear off window has duplicate pinned tabs,  right click context menu doesn't work due to #12345
  6. Go back to Window 1 and unpin the site, window 2 loses both the pinned tabs
  7. Ctrl+W on window 1 to close the window
  8. Ctrl+W on the about:welcome page, tab closes but window is intact with new tab + icon
  9. Able to open and close single tabs but window doesn't quit

**Actual result:**
![duplicate-pin-tabs](https://user-images.githubusercontent.com/17010094/34293274-1c4cecec-e6fc-11e7-9ec8-1cfa91ceb6ce.gif)

**Expected result:**
Shouldn't duplicate pinned tabs in tear off window and when all tabs are closed window should be closed

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.9
-- | --
V8 | 6.3.292.48
rev | b5aec10
Muon | 4.5.31
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
No

### Additional Information
cc: @LaurenWags @kjozwiak

**Comment by LaurenWags** [comment]
Removed Windows tag, can repro on MacOS.

**Comment by kjozwiak** [comment]
I can reproduce the duplicate pins issue pretty easily but I can't reproduce the white window issue under Ubuntu 17.10 using `0.20.10`. I reproduced the "white window" issue with Win 10 x64 several times but couldn't reproduce it under Ubuntu/macOS...

It seems like the "duplicate" pin creation happens on all three platforms but the "white window" issue is only reproducible on Win. 

@LaurenWags did you end up reproducing the "white window" portion of the issue on macOS?

**Comment by petemill** [comment]
Possibly a duplicate of #11861

**Comment by petemill** [comment]
Leaving open to confirm that #11862 fixes both the duplicate pinned tabs issue (#11861) and the window-with-no-tabs issue on all platforms

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11862
