### ISSUE TITLE
'update date handling' unit tests fail for some timezones

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12370]
### Description
The following test fails, because the epoch `1510687381887` is not 2017-11-14 in every timezone. For example I ran the tests in the NZ timezone, where that time is 2017-11-15. I would change this myself to a more universal time, but it's unclear if any real code which relies on this needs to take timezone in to account.

```
  1) update date handling todayYMD returns YYYY-MM-DD of today:

      AssertionError [ERR_ASSERTION]: today
      + expected - actual

      -2017-11-15
      +2017-11-14

      at Context.<anonymous> (test/unit/app/browser/datesTest.js:23:14)
```

### Steps to Reproduce

  1. Change local timezone to New Zealand
  2. `npm run unittest -- --grep "update date handling"`

**Comment by diracdeltas** [comment]
i also noticed this but forgot about new zealand being on earth: https://github.com/brave/browser-laptop/pull/12192

**Comment by diracdeltas** [comment]
actually it looks like 10:30 AM UTC falls on the same day in every timezone :). i can fix this

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
