### ISSUE TITLE
Fetch failed NPM install react0.14

### ISSUE THREAD

**Issue by CartridgeGen** [brave/browser-laptop#1237]
This is what it gave me on NPM install command : 
`npm install
npm ERR! fetch failed https://registry.npmjs.org/react/-/react-0.14.8.tgz`

There may be more, I just started it. Just giving a heads up.

**Comment by bbondy** [comment]
I just did a fresh `npm install` last night and it worked fine.  Maybe there was a connection problem at the time of npm installing last time for you?

**Comment by bbondy** [comment]
No answer for 15 days, and it works for me. Closing.
