### ISSUE TITLE
Tab selecting in autocomplete dropdown fills in the following text box

### ISSUE THREAD

**Issue by paulizleet** [brave/browser-laptop#12383]
### Description
Selecting an option from the autocomplete dropdown using the arrow keys and tab button puts the remaining characters in the next text box.

### Steps to Reproduce
  1.  Select any field where autocomplete data will show up
  2.  Use the arrow keys to highlight an option
  3.  Press tab to fill in the box with that option, and move focus to the next text box 

**Actual result:**
  [Example](https://dl.dropboxusercontent.com/s/004kmgest3x4cl8/brave_annoyance.webm)
  The selected text box stays as is, and the rest of the string is put into the next field

**Expected result:**
[Done properly in Firefox](https://dl.dropboxusercontent.com/s/mh2u3kwlzod1h3y/expected_result_in_firefox.webm)
The field is filled using the entire string from the autocomplete dropdown

**Reproduces how often:**

100%

### Brave Version
Version 0.19.122
Windows 7 x64

**Reproducible on current live release:**
Yes.

**Comment by srirambv** [comment]
Same as #9170. Closing as dupe
