### ISSUE TITLE
Brave leaks internal IP addresses via WebRTC by default

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [brave/browser-laptop#12389]
### Description
Brave leaks internal IP addresses via WebRTC. This is a common ad tracking mechanism.

### Steps to Reproduce
https://browserleaks.com/webrtc

**Actual result:**
Leaks internal IPs

**Expected result:**
Expect this NOT to happen

**Reproduces how often:**
Always

### Brave Version
0.20.6

**about:brave info:**
Brave	0.20.6
V8	6.2.414.36
rev	18f7d1e
Muon	4.5.14

**Reproducible on current live release:**
Only beta was available at this time. Likely same result on live release.

### Additional Information
n/a

**Comment by jonathansampson** [comment]
You can prevent this in Brave by turning-on _Fingerprinting Protection_. By default, this is off, as it will break some sites. You can enable it globally by visiting about:preferences#shields in Brave, and flipping the _default shield setting_ the _On_ state.
