### ISSUE TITLE
New tab should not be black if you disable "show backgrounds"

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#12380]
### Description

A time ago the new tab color changed to being black. It does look very good with backgrounds on the new tab but it does look terrible when you turn off the backgrounds:
![image](https://user-images.githubusercontent.com/25466657/34305244-6f0cbae8-e73d-11e7-8e4c-73e1e3f0afb5.png)

### Steps to Reproduce

  1. Go to about:preferences/tabs 
  2. Turn off "show images"
  3. Open a new tab with the dasboard

**Actual result:**

The tab is black and it just looks strange like the color chooser missed something, look at the above picture!

**Expected result:**
Should have the same color as the pixels beneath the tab.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.19.120 
rev: 028351ee3a93e7493556448c9247aa1e0755ef12 
Muon: 4.5.30 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**

Yes

**Comment by modusops** [comment]
I can't reproduce what you have described above.  

While looking to create an unrelated design suggestion ticket, found this ticket to be outdated? Looks like the new update is:
- Preference > Tabs > Show/Hide tabs in page theme color

No issues with turning off and opening a new tab. BG is the default grey. 

Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Comment by MargarytaChepiga** [comment]
It is still reproducible on windows.

**Comment by MargarytaChepiga** [comment]
Do we want to change it though? It looks really great when the background is on. Or should we change the tab color to be grey when the background is off and leave if black when it is on?

**Comment by Jacalz** [comment]
This should be changed in my opinion in order for it to look better but ONLY for when backgrounds are turned off 🙂

**Comment by MargarytaChepiga** [comment]
@Jacalz Oh okay, sorry I misunderstood you :smile:

**Comment by Jacalz** [comment]
I have tested on Windows, MacOS and also on Linux ([Solus](https://solus-project.com) to be more specific) and all platforms have the same issue.

**Comment by Jacalz** [comment]
I sat down with gimp an created a little mockup on how it could look when fixed:
![newtab-mockup](https://user-images.githubusercontent.com/25466657/37863660-f912eb60-2f61-11e8-858a-2be46addc55c.png)

**Comment by MargarytaChepiga** [comment]
@Jacalz I am looking at this right now, and I was able to do this:
![variant 1](https://user-images.githubusercontent.com/15698572/38346795-6b55a13e-3865-11e8-8fb8-16c365475737.png)
I can do with different variations of having more/less of any of the colors. However, I couldn't figure out a way yet of how we can have a radiant-gradient for the whole page and only on the top to have a linear black.
