### ISSUE TITLE
continually prompted to play YT videos

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12382]
### Description
If you have 'Autoplay Media' set to 'Always ask' and you do not select 'remember this decision', you will be continually prompted to 'Allow youtube to autoplay media?' and can't actually view the video.

### Steps to Reproduce

MacOS steps:
  1. Clean profile on 0.20.9
  2. Navigate to about:preferences#security
  3. Set Autoplay Media to 'Always ask'
  4. Clear any pre-set settings for Autoplay Media (for YT and Twitch)
  5. Navigate to YT, select a video to display
  6. Notification displays, select Allow.
  7. Video plays for a split second and then you get the notification again.
  8. Navigate to a different site to view a video (I used an nytimes.com article with a video)
  9. Notification displays, select Allow.
  10. Video plays without issue.

Win/Linux steps (slightly different):
  1. Clean profile on 0.20.9
  2. Navigate to about:preferences#security
  3. Set Autoplay Media to 'Always ask'
  4. Clear any pre-set settings for Autoplay Media (for YT and Twitch)
  5. Navigate to YT, select a video to display
  6. Video plays without any notification bar (this is pre-existing on 0.19.122)
  7. Restart browser, navigate to YT video.
  6. Notification displays, select Allow.
  7. Video plays for a split second and then you get the notification again.
  8. Navigate to a different site to view a video (I used an nytimes.com article with a video)
  9. Notification displays, select Allow.
  10. Video plays without issue.

**Actual result:**
Unless you select 'Remember this decision' you will be continually prompted for YT videos and cannot actually view them. 

![play-notif](https://user-images.githubusercontent.com/28145373/34306905-8e3ab372-e713-11e7-9809-4551bdee9f3c.gif)

**Expected result:**
You should only have to select 'Allow' once and then the YT video should play. (this is how this works on 0.19.122

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.20.9

**Reproducible on current live release:**
no, not reproducible on 0.19.122

### Additional Information
See slightly different Win/Linux steps which were confirmed by @srirambv and @kjozwiak

**Comment by petemill** [comment]
I can reproduce the Win/Lunux-only steps above, on Mac

**Comment by srirambv** [comment]
Verified on 0.19.126. Works fine. https://github.com/brave/browser-laptop/issues/12514 is still an issue which requires restart for settings to take effect.

**Comment by kjozwiak** [comment]
As per our discussion in Slack last night, I'm moving this back into the `0.20.x` milestone. This particular issue was only reproducible under `0.20.x` and wasn't an issue in `0.19.x`. However, because the refactored code from this bug was required in `0.19.x`, QA double checked and made sure this didn't regress anything in `0.19.x`. It passed on all three platforms and was tagged as `Checked`.

Cleared the `Checked` tags so it gets retested in `0.20.x`.
