### ISSUE TITLE
not prompted to save Contribution Statement

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12385]
### Description
When clicking on a link for Contribution Statement from Payment History, you are not prompted to save your Contribution Statement.

### Steps to Reproduce

1. Had a profile with 0.20.10 (packaged build) where payments were enabled, closed Brave.
2. Renamed profile to be brave-development.
3. Built 0.20.x from source.
4. Ran npm run add-simulated-payment-history.
5. Renamed brave-development back to brave-beta.
6. Opened 0.20.10 (packaged build) again.
7. Went to about:preferences#payments.
8. Opened payment history and clicked on a link.
9. On the new tab that opened with the contribution statement, I was not prompted to save my statement. 

**Actual result:**
I was not prompted to save the statement that opened.

![contrib-statement-02010](https://user-images.githubusercontent.com/28145373/34313582-323e972e-e73a-11e7-814f-f72f4ea19f1c.gif)

**Expected result:**
Should have been prompted to save statement as in 0.19.122

![contrib-statement-019122](https://user-images.githubusercontent.com/28145373/34313552-f26562e0-e739-11e7-8d23-af18a6237f4d.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.10
V8 | 6.3.292.48
rev | 313dbc6
Muon | 4.5.31

**Reproducible on current live release:**
no, not on 0.19.122

### Additional Information
Maybe similar to https://github.com/brave/browser-laptop/issues/11471 ? Or possibly related to https://github.com/brave/browser-laptop/issues/12381 ?

**Comment by petemill** [comment]
Possibly related to https://github.com/brave/browser-laptop/blob/master/app/pdfJS.js#L55

Should be `details.resourceType === 'mainFrame'`

**Comment by petemill** [comment]
Fixed by #11531
