### ISSUE TITLE
large gap on the top & dark mode

### ISSUE THREAD

**Issue by Vispocks** [brave/browser-laptop#12396]
1) You may make the space from the TAP to UP much smaller. ( like google chrome)
I can see the gap from UP to DOWN on the TOP (large)!

2) when you will offering the dark mode?

Thank you~

**Comment by bsclifton** [comment]
Hi @Vispocks,

1. I'm not exactly sure what you're asking for- smaller space at the top? Which platform are you using? (Windows, macOS, Linux?). Currently, Linux has a large gap which is tracked with issue https://github.com/brave/browser-laptop/issues/3126
2. Dark mode is tracked here: https://github.com/brave/browser-laptop/issues/271

**Comment by Vispocks** [comment]
Hi @bsclifton,

1) I am on GNU/ Linux and yes it has a large gap on the top, that's my q :)   ( I couldn't add screenshot here to prove)

2) dark mode when will that comes?

thank you ~

**Comment by bsclifton** [comment]
@Vispocks perfect! Both items are captured

RE: dark mode, it's something we'd really like to do... but there always seem to be things which have higher priority.  I'd love to work with a contributor to help make it happen, but I can't give an estimate for when we'd be able to start dev on it
