### ISSUE TITLE
Reddit does not render when use Brave Browser

### ISSUE THREAD

**Issue by Hellaphant75** [brave/browser-laptop#1239]
I just installed Brave and while searching the web I notice that Reddit doesn't render. I tried other sites(EPSN,CNN,Github) and they all render prefectly fine.

Step to Reproduce
1. Download and Install Brave v0.37.3
2. Navigate to the search bar and go to Reddit.com

**Comment by bbondy** [comment]
Reddit is rendering fine for me.  Perhaps this was an intermittent problem?  Could you try again?

**Comment by weems** [comment]
fine for me as well. Try the latest version.

**Comment by bbondy** [comment]
I am but it's rendering correctly for me.

**Comment by admshao** [comment]
I have this issue as well. If you have Bravery set to replace or block ads, Javascripts from Facebook.com, Reddit.com and even parts of gmail.com aren`t executed thus the wrong rendering.


![facebook_console](https://cloud.githubusercontent.com/assets/8628354/14268237/1826bdae-faaf-11e5-8eb0-1a3e112abefc.png)
![facebook_network](https://cloud.githubusercontent.com/assets/8628354/14268238/1826f01c-faaf-11e5-8f66-3175f63fe63a.png)
![gmail_console](https://cloud.githubusercontent.com/assets/8628354/14268242/182816ae-faaf-11e5-9080-37fd2610130c.png)
![gmail_network](https://cloud.githubusercontent.com/assets/8628354/14268240/1827d036-faaf-11e5-9ceb-05c7ef40e065.png)
![reddit_console](https://cloud.githubusercontent.com/assets/8628354/14268241/182820c2-faaf-11e5-8b5e-fef5ec6930c7.png)
![reddit_network](https://cloud.githubusercontent.com/assets/8628354/14268239/1827cf64-faaf-11e5-8374-bf23506580b0.png)

**Comment by bbondy** [comment]
sounds like some people have a corrupted tracking protection or adblock list.

**Comment by admshao** [comment]
I tried the .tar.bz and the .deb version. I have this issue on both.
I don't have the requirements to try building from source right now =(

**Comment by Hellaphant75** [comment]
I'm going to uninstall and reinstall Brave now. I'll let you guys know what happens. And thanks for the advice.

**Comment by zvezdaburya** [comment]
Just chiming in here, running Brave: 0.8.3 and having the same trouble with reddit when bravery is set to replace or block ads. Yandex.com is also affected.

**Comment by Michael-Free** [comment]
Reporting the same sort of behaviour with Brave 0.8.3 on Ubuntu 14.04 LTS - this only occurs when Bravery is set to either Replace or Block Ads

**Comment by zvezdaburya** [comment]
I am using Brave 0.9.1 and don't have these problems anymore. Reddit and yandex seems to be working fine.

**Comment by bbondy** [comment]
It'd be useful if someone can confirm if they still have this problem with 0.9.  
If you do please let me know the file size of your:
`~/Library/Application\ Support/Brave/ABPFilterParserData.dat` file on OSX, or
`%appData%\brave\ABPFilterParserData.dat` file on Windows

**Comment by Liunkae** [comment]
No recent reports. Closing.
