### ISSUE TITLE
Cannot open photos.google.com

### ISSUE THREAD

**Issue by rolandixor** [brave/browser-laptop#12395]
### Description
If you try to go to photos.google.com, it will tell you that there were too many redirects.

### Steps to Reproduce
  1. Attempt to go to photos.google.com
  2. Cry.
  3. Sit and ponder the very meaning of life.

**Actual result:**
![selection_532](https://user-images.githubusercontent.com/558147/34322155-49234982-e7f6-11e7-8aea-89002eb5b252.png)

**Expected result:**
A living, breathing Google Photos tab.

**Reproduces how often:**
1000%

### Brave Version
0.19.122

**Reproducible on current live release:**
I don't know.

### Additional Information
Disabling all shields, including HTTPS Everywhere, makes no difference. It's still dead, Jim.

**Comment by luixxiul** [comment]
For me it cannot be reproduced. Would you mind retrying again? It might have been fixed.

**Comment by rolandixor** [comment]
So what should I do? I have the latest version available in the Brave Debian/Ubuntu repository. Since Brave doesn't use external addons, it clearly can't be that either.

**Comment by luixxiul** [comment]
please try disabling the shield and see if it would fix the redirect issue, thanks.

**Comment by tbates** [comment]
just a note that this i working fine on the beta chrome version (mac os)

 
Brave: 0.19.121 
rev: 9e8ffc423a7061e5cafd262bb46c1ada17971db0 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Comment by rolandixor** [comment]
I figured out how to trigger it, and how to get Google Photos to load in brave. It *might* be due to HTTPS Everywhere.

To trigger it, you must not have logged into Google Photos in Brave before, and you have to enter the URL as "photos.google.com" (without the https://)

If you load https://photos.google.com, it loads and you're able to sign in (or signed in automatically if you were already logged into to your Google account), and after this is it is not possible to replicate the bug.
