### ISSUE TITLE
Fullscreen doesn't work properly

### ISSUE THREAD

**Issue by Kasmetski** [brave/browser-laptop#12399]
### Description
Fullscreen option doesn't work. It hides only the menubar and topbar.
I'm expecting to hide everything like Chrome & Firefox. It should hide bookmarks, url bar and everything other except opened page.

### Steps to Reproduce
Click F11 or View - Toggle Full screen

### Brave Version
0.19.105

**Comment by bsclifton** [comment]
Thanks for the report @Kasmetski 😄  This has been reported with https://github.com/brave/browser-laptop/issues/4371 which you can follow for more info (it wasn't worded very clearly, so I updated it just now). I'll close this issue as a duplicate
