### ISSUE TITLE
Reload tab doesn't load PDF after quit-restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12408]
## Test plan

https://github.com/brave/browser-laptop/pull/12431#issue-284948162

----

### Description
Reload tab doesn't load PDF after quit-restart

### Steps to Reproduce
  1. Clean install 0.20.11
  2. Visit https://basicattentiontoken.org/ and click on the Whitepaper to load the pdf in a new tab
  3. Quit/Close and reopen browser, Shows pdf is not loaded
  4. Press the reload button, pdf still doesn't load
  5. Highlight URL and press Enter, pdf is loaded
  6. Type in http://orimi.com/pdf-test.pdf/ in a new tab and repeat steps 3-5, same result

**Actual result:**
![pdf](https://user-images.githubusercontent.com/17010094/34382438-cef28aa6-eb06-11e7-9817-16e20fe499ba.gif)

**Expected result:**
PDF should load when the browser is restarted

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.11
-- | --
V8 | 6.3.292.48
rev | 9bb3c67
Muon | 4.5.31
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
Partially, After restart, PDF tab shows file not found, Reload the tab loads the pdf. 
![pdf-019](https://user-images.githubusercontent.com/17010094/34382505-4f110ed8-eb07-11e7-9230-c0358663181c.gif)

### Additional Information
cc: @petemill @diracdeltas @NejcZdovc 
Could be related to the recent reload fix

**Comment by diracdeltas** [comment]
it's also broken on master (didn't try 0.20.x yet) if you simply reload any PDF. it shows file not found. fix incoming.

**Comment by srirambv** [comment]
Issue still happens when you quit the browser and relaunch. Reloading the tab loads the pdf. Same behaviour on all platforms.

**Comment by diracdeltas** [comment]
@srirambv i thought this issue was for reloading the tab not loading the PDF. please open a separate issue for PDF not loading after restart.

**Comment by srirambv** [comment]
Will do
