### ISSUE TITLE
1px gap at the bottom of maximized window - Windows 7

### ISSUE THREAD

**Issue by Alan-FGR** [brave/browser-laptop#12410]
### Description
There's a 1px gap at the bottom of maximized window.

### Steps to Reproduce
  1. Maximize the browser window

**Actual result:**
![image](https://user-images.githubusercontent.com/8399299/34385670-7a29e3e8-eb0b-11e7-89d4-3da06c22cf6c.png)

**Expected result:**
Maximized windows should be maximized?

**Reproduces how often:**
Always.

### Brave Version
**about:brave info:**
Brave: 0.19.122 
rev: 009e79278cba9e3e0e5498d64739b0cb0a5b4696 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64

### Additional Information
Windows 7 Home Premium
Just checked for updates to make sure there are none (Help>Check for Updates)

**Comment by Alan-FGR** [comment]
Also, when I minimize and restore the window this happens:
![17-12-27-116](https://user-images.githubusercontent.com/8399299/34386634-c90aa574-eb10-11e7-8484-b22d807c3837.gif)

**Comment by bsclifton** [comment]
Thanks for the report, @Alan-FGR 😄  This issue is captured already with https://github.com/brave/browser-laptop/issues/10599.  I gave that a bump on your behalf
