### ISSUE TITLE
Browsing history not deleted when set to clear on quit

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12427]
### Description
Browsing history not deleted when set to clear on quit

### Steps to Reproduce
  1. Clean install 0.20.12
  2. Visit a few sites to add history
  3. Open preferences-> Security and enable Browsing History, Download history, Cached images and files, All site cookies 
  4. Open a new tab and close all open tabs
  5. Close the browser and restart
  6. Type the site name you visited in step 2, shows up in history 
  7. Open about:history, all visited sites are still there not cleared upon close

**Actual result:**
![history](https://user-images.githubusercontent.com/17010094/34406872-417dea96-ebb3-11e7-8406-bf778a7f79eb.gif)

**Expected result:**
Browsing history should be cleared upon exit when clear browsing data is set 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.12
-- | --
V8 | 6.3.292.48
rev | 22e9c48
Muon | 4.5.32
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
No

### Additional Information
Same behaviour on the previous 0.20.x builds
cc: @bsclifton @diracdeltas @bridiver

**Comment by diracdeltas** [comment]
appears to have been caused by c2fd650aad68832b1eccc34cc2d71372b58dc918
