### ISSUE TITLE
Desktop shortcut icon not updated to the new icon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12426]
### Description
Desktop shortcut icon not updated to the new icon

### Steps to Reproduce
  1. Install 0.20.11, ensure desktop shortcut has old icon 
  2. Upgrade to 0.20.12 which has the new icon set 
  3. Icon on Start menu and app changes, but desktop shortcut still has the old icon 

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/34406612-f68ea26a-ebb1-11e7-8c6f-1bdb9c6f610f.png)

**Expected result:**
Desktop shortcut icon should also update to new icon

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.12
-- | --
V8 | 6.3.292.48
rev | 22e9c48
Muon | 4.5.32
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

**Reproducible on current live release:**
N/A

### Additional Information
#12411
cc: @darkdh @bsclifton

**Comment by bsclifton** [comment]
Happens on macOS too (basically pin 0.20.11 to your dock and then manually install 0.20.12)

**Comment by darkdh** [comment]
@bsclifton, the icon will be updated automatically when you launch it after upgrade. (on Mac)
