### ISSUE TITLE
Brave keychain access prompt appears 3 times if user clicks 'cancel'

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1242]
Because there is no way for `keytar` to tell the difference between the user clicking `cancel` and there being no matching keychain entry, the prompt appears 3 times in a row if the user clicks `cancel`. Once to check for the v0.8.2 password, once to check for the v0.8.2+ password, and once to try to create a password if none exists. After we deprecate the v0.8.2 password check, the prompt will appear 2 times instead of 3.

**Comment by alexwykoff** [comment]
@diracdeltas need update on if this is still an issue, thanks!

**Comment by diracdeltas** [comment]
it appears 2 times now. calling it good enough. :)
