### ISSUE TITLE
Wiki: Contributing: Broken link to contributors documentation.

### ISSUE THREAD

**Issue by sergiorojasa** [brave/browser-laptop#12423]
Have you searched for similar issues? Yes

### Description
There is a broken link in the contributing wiki page.

### Steps to Reproduce

  1. Visit: https://github.com/brave/browser-laptop/wiki/Contributing
  2. Scroll down to **work on code** section.
  3. Look for **Check out our contributors documentation for helpful tips**
  3. Click on the **contributors documentation** 

**Actual result:**
Github 404 page

**Expected result:**
A link to CONTRIBUTING.md

**Reproduces how often:**
100%

### Brave Version
N/A

**Reproducible on current live release:**
N/A

### Additional Information
N/A

**Comment by jeffbricco** [comment]
Hi sergiorojasa. I believe I fixed the link.

**Comment by jeffbricco** [comment]
@sergiorojasa I fixed the link.

**Comment by bsclifton** [comment]
Thanks for the report, @sergiorojasa (and thanks for the fix, @jeffbricco!) 😄 👍
