### ISSUE TITLE
Fingerprinting Protection breaks avatar upload on Twitter.com & Mega.nz

### ISSUE THREAD

**Issue by TheAresjej** [brave/browser-laptop#12420]
### Description
Fingerprinting Protection breaks avatar upload on Twitter.com & Mega.nz

### Steps to Reproduce
  1. Enable Fingerprinting Protection
  2. Try to change avatar on this sites 

**Actual result:** No reaction - back to upload

**Reproduces how often:** 100%

### Brave Version
Brave: 0.19.122 
rev: 009e79278cba9e3e0e5498d64739b0cb0a5b4696 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:** YES

**Comment by eljuno** [comment]
For Twitter, it's reported before #3720.
