### ISSUE TITLE
cmd-W shortcut does not work when tab is opened with target="_new"

### ISSUE THREAD

**Issue by atotic** [brave/browser-laptop#1243]
Platform: Mac
Version: 0.8.3

To reproduce: 
- go to http://news.google.com./
- click on any news link, get a new tab open
- now hit cmd-W to close the just opened tab. It won't work, until you focus the tab by clicking on it.

**Comment by weems** [comment]
@atotic Interesting find. Thanks, I also confirmed on OSX 10.11.4 & Brave 0.8.3.
