### ISSUE TITLE
Windows should load more instantly

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12437]
As part of the performance initiative, it has been determined that a task to attack is the time a user must wait for new windows to be created and rendered, before creating / viewing the tab(s) for that window.

Adding timing to measure this from window creation to when react has finished rendering, it seems to take 1s to render a window (+1s/-0.5s depending on system).

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
