### ISSUE TITLE
MaidSafe: collaborate with or imitate features?

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12444]
It would be good to make one browser that has all of the good features of the MaidSafe and Brave browsers.

https://github.com/maidsafe-archive/MaidSafe/issues/237

A related issue is #2933.

**Comment by jamesray1** [comment]
Too hard to label as a project, with relevant features in separate issues?

**Comment by bsclifton** [comment]
@jamesray1 if you wanted to call out specific issues here, please do (and then feel free to reopen)

As-is, there isn't enough information to be actionable (which is why I closed it). Thanks 😄
