### ISSUE TITLE
i686?

### ISSUE THREAD

**Issue by handicraftsman** [brave/browser-laptop#1245]
Of course, it's old CPU architecture, but there's still much old pc's (like my). So, it will be cool, if you'll include i686 builds. Is it hard to add 1-2 arguments for compiler to make i686 builds? No.

**Comment by luixxiul** [comment]
Assumed to be fixed with https://github.com/brave/browser-laptop/issues/397#issuecomment-213488206. Closing for the moment. Please leave a comment if it is my misunderstanding.
