### ISSUE TITLE
UX | Design : Tab hover UX

### ISSUE THREAD

**Issue by modusops** [brave/browser-laptop#12454]
Some minor UX issues I have w/ tabs in the Brave browser:

1. Hovering on each inactive tab by default, enables a preview of the page. As it is quite easy to accidentally hover into the tab zone, the current experience is jarring when you have many tabs open. 

Might I suggest a subtle transition animation (fade in) similar to the one you're already using for new tabs. The preview for each inactive tab will more user friendly. 

2. The hover state for each inactive tab is currently a slight shift in tone of grey. While this is similar to Chome, I wonder if this could be improved by making the hover state even more obvious. This would make it more accessible for users with visual impairment, low screen brightness, for users who have adjusted screen resolution, or users w/ many tabs. 

3. While hovering over a tab, user can create a new tab. However, the new tab is immediately presented while the hover is still over the previous tab. This UX could be improved, as the user's mental model becomes inconsistent with what they have previously learnt. I think this is where a more obvious "active tab" could help. 

Hope this helps! Liking everything else so far!

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
