### ISSUE TITLE
Changing pinned values is not working correctly

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#12450]
### Description

This was first noticed on reddit https://www.reddit.com/r/BATProject/comments/7ls63a/brave_setting_payment_s_in_brave_is_extremely/. Actually what is happening is that when you set a pinned value and then just clicking to another pin inputs values changes randomly.

### Steps to Reproduce

  1. Add 3 publishers to the clean ledger
  2. Pin this 3 publishers
  3. Set % to one input
  4. Click to another two inputs and value will change

**Actual result:**

Values changes when you click on other inputs

**Expected result:**
Values shouldn't change for other inputs

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.2.0 
OS Architecture: x64

**Reproducible on current live release:**

yes

### Additional Information

![dec-31-2017 19-04-17](https://user-images.githubusercontent.com/9574457/34463480-8210f6b4-ee5d-11e7-9815-a1823ff3f9ab.gif)

**Comment by srirambv** [comment]
This is dupe to https://github.com/brave/browser-laptop/issues/11238 and https://github.com/brave/browser-laptop/issues/12002 ?

**Comment by NejcZdovc** [comment]
no it's not a dupe, because this issue/PR fixes only one regression and don't fix this two existing issues
