### ISSUE TITLE
Add lower and higher amounts to Brave Payments monthly budget choices

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12465]
As a user, I need more options for monthly budget choices to meet my contribution needs.

![image](https://user-images.githubusercontent.com/13509546/34186957-a4ead0de-e4e3-11e7-9cf5-9e44f2cc8f88.png)

**Comment by kjozwiak** [comment]
Verified that the following worked as expected using `0.19.126`:

* ensured that `10 BAT` is appearing under the monthly budget
* ensured that `10 BAT` is being listed under the Contribution Statement
* ensured that when a contribution is made, 10 BAT is being subtracted from the amount

Ensured that once you've selected 10 BAT as the default monthly budget, it's correctly being reflected under `ledger-state.json`

```
"fee": {
  "currency": "BAT",
  "amount": 10
},
```

**Comment by LaurenWags** [comment]
Verified items from https://github.com/brave/browser-laptop/issues/12465#issuecomment-355486700 on MacOS.
