### ISSUE TITLE
IndexedDB not working in web worker

### ISSUE THREAD

**Issue by armhub** [brave/browser-laptop#12463]
## Test plan
See https://github.com/brave/muon/pull/629

### Description
IndexedDB can not be used in web workers. The call indexedDB.open() never returns. In the gui thread it works fine.
You can test it here: http://raananw.github.io/WebWorkers-IndexedDB/

### Steps to Reproduce
Call indexedDB.open("a") in a worker context.

**Actual result:**
The call never returns.

**Expected result:**
The call returns.

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
Brave | 0.19.123
rev | f45cb3a
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.10.0-42-generic
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by ptrwllrd** [comment]
any chance this gets some attention soon?

**Comment by ryanpcmcquen** [comment]
This one really hurts ...

**Comment by eljuno** [comment]
cc @bsclifton

**Comment by lo-nyi** [comment]
+1 Tutanota is my main email service provider

**Comment by janos-szenfner** [comment]
When will you fix the issue?

**Comment by janos-szenfner** [comment]
I can understand it. I am thinking the same. Please fix this issue.

**Comment by bsclifton** [comment]
Got a fix for this! Hang tight

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.31 - 3148ace
* Muon - `7.1.5`
* libchromiumcontent - `67.0.3396.103`

**Comment by janos-szenfner** [comment]
Please put it into the beta, dev and nightly channel and put it on to download it. Thanks.

**Comment by jasonrsadler** [comment]
Verified on XUbunti 18.04 using
- 0.23.31 - 3148ace
- Muon - `7.1.5`
- libchromiumcontent `67.0.3396.103`

**Comment by ryanpcmcquen** [comment]
@bsclifton, can we get this on Android too?

**Comment by ryanpcmcquen** [comment]
@bsclifton, thanks! Created:
https://github.com/brave/browser-android-tabs/issues/679
