### ISSUE TITLE
need sitehack for Wired

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1247]
STR:
1. go to http://www.wired.com/2016/04/reporters-pulled-off-panama-papers-biggest-leak-whistleblower-history/
2. scroll down for a bit
3. after a while, the article is replaced with a page asking you to turn off your adblocker

Local storage:
![screen shot 2016-04-04 at 10 32 11 am](https://cloud.githubusercontent.com/assets/549654/14257093/f1594fc4-fa50-11e5-815d-bcbda4cc428b.png)

It appears that Wired periodically checks if you are using an adblocker and sets `adBlocked` to 1 if so.

**Comment by weems** [comment]
In Chrome You can install a third party filter list to uBlock Origin found at the following github page: https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek. I confirmed that following Installation at the Wired Page linked above in Chrome, no adblocker interstitial appears. This requires a Chromium Plugin in [uBlock Origin](https://github.com/gorhill/uBlock). But Perhaps the filter list could be useful for us: https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt.

**Comment by diracdeltas** [comment]
Thanks, @weems, that was a useful pointer. I ended up using the method from https://github.com/gorhill/uBlock/blob/master/assets/ublock/resources.txt
