### ISSUE TITLE
Fingerprinting: Brave's headers, plugins different from Chrome

### ISSUE THREAD

**Issue by tadatitam** [brave/browser-laptop#12479]
### Description

Brave reports the User-Agent as Chrome, but reports certain fingerprintable attributes differently. This can make Brave users easily distinguishable from Chrome users.
1. Brave's header reports the Accept-Language as `en-US`, whereas Chrome's header reports `en-US,en;q=0.9`. 
2. Brave reports an empty list of plugins, but Chrome does not. 

The bits of entropy leaked by these attributes on Brave is misleading. While the values of the headers and the plugins that Brave exposes are very common, their combination with User-Agent set to Chrome makes the fingerprint unique. 

A possible alternative may be to report Chrome's header values and Chrome's default plugin list, which is ['Chrome PDF Plugin', 'Chrome PDF Viewer', 'Native Client', 'Widevine Content Decryption Module'] on macOS and Ubuntu. 

### Steps to Reproduce

  1. Visit panopticlick.eff.org and generate fingerprint on Chrome
  2. Visit panopticlick.eff.org and generate fingerprint on Brave
  3. Compare fingerprints.

**Actual result:**

<img width="614" alt="chrome fingerprint" src="https://user-images.githubusercontent.com/6851424/34529989-96354436-f062-11e7-849c-9ffc90f5a39c.png">
<img width="605" alt="brave fingerprint" src="https://user-images.githubusercontent.com/6851424/34529988-961550b8-f062-11e7-8be8-944543948fa2.png">

**Expected result:**
Both fingerprints should be the same

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Version | 0.19.123
OS Platform | macOS
OS Architecture | x64

**Reproducible on current live release:**

**Comment by srirambv** [comment]
cc: @diracdeltas

**Comment by diracdeltas** [comment]
HTTP Accept headers issue is covered in https://github.com/brave/browser-laptop/issues/2229

For plugins, I don't think we can safely set our plugin list to Chrome's by default without breaking sites that expect us to actually have those plugins enabled if they are advertised in the headers. In the future we should have a feature for users to set whatever headers they want.

**Comment by tadatitam** [comment]
Allowing users to set whatever headers they want is great for providing control, however most users will leave them at the default values. Even if they do update, they may not be aware of good choices, and may end up making themselves more fingerprintable. Since Brave is trying to disguise itself as Chrome, the default values should be as close as possible to Chrome. If users want to still change them, they are free to.

With reference to #2229, evaluating the uniqueness of the HTTP headers in isolation may not be appropriate. 

As for the plugins, why not enable those plugins by default?

**Comment by diracdeltas** [comment]
> Since Brave is trying to disguise itself as Chrome

Only in the short-term. Long term, our goal is to make all Brave users look as similar to each other as possible, but still be distinguishable as Brave. It is already infeasible to make us look exactly the same as Chrome and will become more difficult as we add more features.

> As for the plugins, why not enable those plugins by default?

mostly for security reasons. for instance, PDFium (chrome's PDF plugin) is a relatively large source of externally-reported Chrome CVEs, so we replace it with a HTML5+JS pdf viewer.

**Comment by tadatitam** [comment]
Hmm, that makes sense. The severity of these minor differences may be a function of the number of users. The Tor browser, for example, can afford to be distinguishable with close to 4 million daily users (though there is no hard evidence if that is true). 

I apologize if I sound like a jerk. I really *really* appreciate the tremendous amount of work that has gone into Brave and I prefer it over Tor any day. I am humbly trying to make a contribution here. My layman brain tells me standardizing the Accept-Language header may be a low-hanging fruit, but I could be wrong. :)

**Comment by diracdeltas** [comment]
@tadatitam definitely, no offense taken. the Accept-Language header is probably low-hanging fruit, feel free to take a stab at it if you want.

**Comment by tadatitam** [comment]
@diracdeltas thanks a lot! So, the goal is to modify how Brave assigns Accept-Language header values so that it matches with how Chrome does it. 

In Accept-Language, `q` is the relative quality factors (`q`) of languages. ref: https://stackoverflow.com/questions/8552927/what-is-q-0-5-in-accept-http-headers

It seems that Chrome assigns the primary language to be the same as the environment variable` LANG` (e.g. `en-US`), and adds the general variant of that language with -0.1q (e.g. `en-US,en;q=0.9`). Again, if I run `locale-gen de-DE.UTF-8` and set `LANG` to `de-DE.UTF-8`, Chrome sends out `de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7`. My guess is that since `en-US` continues to be on the locale, Chrome continues to send it, but with a lower relative quality factor. 

My limited experiments reveal that Brave sends the primary language without sending any second choices or their `q`s. Any pointers to what part of the codebase I should look to modify this behavior?

**Comment by diracdeltas** [comment]
@tadatitam pretty sure that the Accept-Language header is set in https://github.com/brave/muon (our fork of Electron). may be worth looking at https://github.com/brave/muon/commit/0404cc850b19de72e98ae43c2b50bc54296aefdc

**Comment by tadatitam** [comment]
@diracdeltas thanks a lot for the pointer. Digging around a little more, looks like the accept_language is being set here: [muon/brave/browser/brave_content_browser_client.cc](https://github.com/brave/muon/blob/59218c6844f9ba7badd7e56493e932c81e3ffb99/brave/browser/brave_content_browser_client.cc)

Fixing the accept-language is already set as a TODO. Maybe I can work with them to patch this? 

Corresponding code snippet:
```
std::string BraveContentBrowserClient::GetAcceptLangs(
    content::BrowserContext* context) {
  // TODO(bridiver) - this should be set to all accept langs, not just
  // the default locale
  return GetApplicationLocale();
}
```

**Comment by diracdeltas** [comment]
@tadatitam cc @bridiver

**Comment by riastradh-brave** [comment]
@tomlowenthal Is this fixed with brave-core or merely now open in brave-core?

https://github.com/brave/brave-browser/issues/722
