### ISSUE TITLE
unable to drop lock/unlock icon onto folder on toolbar to create bookmark

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12476]
### Description
When user drag and drop the un/lock icon from URL bar onto a folder in the toolbar, a bookmark should be created in that folder but it is not.

### Steps to Reproduce

  1. Open a site.
  2. Add a bookmark folder to the bookmarks toolbar.
  3. Drag and drop the unlock / lock icon from URL bar onto the folder.

**Actual result:**
Bookmark is not added into the folder:
![dnd-lock-02014](https://user-images.githubusercontent.com/28145373/34523860-3779320e-f067-11e7-8890-1ad425169e01.gif)

**Expected result:**
Bookmark should be added to the folder it was dropped onto as it is in 0.19.123:
![dnd-lock-019123](https://user-images.githubusercontent.com/28145373/34523888-60df1b9a-f067-11e7-828d-a025b08496ca.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.14
V8 | 6.3.292.48
rev | 5d75826
Muon | 4.5.33

**Reproducible on current live release:**
no

### Additional Information
Reported and fixed in 0.19.x with this issue: https://github.com/brave/browser-laptop/issues/11180

**Comment by srirambv** [comment]
Confirmed on Windows too

**Comment by srirambv** [comment]
Works on Windows now
![12476](https://user-images.githubusercontent.com/17010094/34826044-07b51502-f6fb-11e7-8a30-6d57a8a2aeac.gif)
