### ISSUE TITLE
Drag and Drop bookmark from folder on toolbar to Bookmarks Toolbar does not work

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12481]
### Description
If you drag and drop a bookmark from a folder on the toolbar to the Bookmarks Toolbar, the bookmark should be moved to the toolbar. However, the bookmark remains in the folder.

### Steps to Reproduce

  1. Clean profile on 0.20.14
  2. Add a folder on the Bookmarks Toolbar.
  3. Add a bookmark to this folder.
  4. Expand the folder from the toolbar.
  5. Attempt to drag and drop the bookmark from the folder onto the Toolbar.

**Actual result:**
Bookmark is not moved to the toolbar:

![dnd-from-toolbar-folder-02014](https://user-images.githubusercontent.com/28145373/34533606-03abc3c0-f089-11e7-9064-30091e5a2064.gif)

**Expected result:**
Bookmark should be moved to the toolbar as it was in 0.19.123:

![dnd-from-toolbar-folder-019123](https://user-images.githubusercontent.com/28145373/34533622-0ebc944c-f089-11e7-8588-0197bb69b2c9.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.14
V8 | 6.3.292.48
rev | 5d75826
Muon | 4.5.33

**Reproducible on current live release:**
no

**Comment by NejcZdovc** [comment]
this one have the same root problem than #12476

**Comment by srirambv** [comment]
Can't drag the bookmark to toolbar on Windows. 
![12481](https://user-images.githubusercontent.com/17010094/34726323-a895d17e-f579-11e7-94fa-05cbd62536b3.gif)

**Comment by NejcZdovc** [comment]
I will close this one, because dnd not working in windows is not related to this PR. Will open another issue for it.

**Comment by NejcZdovc** [comment]
created new issue #12590
