### ISSUE TITLE
Bookmark Folder not pre-selected when adding from Title pane in Bookmark Manager

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12486]
### Description
When you add a bookmark via right-click in the 'Title' pane from Bookmarks Manager, the folder you are on is not pre-selected as it is when adding bookmarks other ways (i.e. right click or the star+ icon in title pane).

### Steps to Reproduce

  1. On Bookmarks Manager, have at least one folder under 'Bookmarks Toolbar'
  2. Right click on the sub folder and select Add Bookmark, the sub-folder is pre-selected on the 'Create New Bookmark' dialog.
  3. Click on the star+ icon in the Title pane to Add Bookmark, the sub-folder is pre-selected on the 'Create New Bookmark' dialog.
  4. Right click in the 'Title' pane and select Add Bookmark.

**Actual result:**
Sub-folder is not pre-selected.

![rt-click-title-pane-02014](https://user-images.githubusercontent.com/28145373/34536765-364b35e4-f094-11e7-807c-7a5b547b1ce8.gif)

**Expected result:**
Sub-folder should be pre-selected.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.14
V8 | 6.3.292.48
rev | 5d75826
Muon | 4.5.33

**Reproducible on current live release:**
Yes

**Comment by NejcZdovc** [comment]
@bsclifton please up lift if needed, I set 0.22 milestone to it
