### ISSUE TITLE
sometimes there is a delay when closing Brave-Beta

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12488]
### Description
Sometimes when quitting Brave-Beta there is a delay in closing (5-10s). This is reproducible on a clean profile without a large amount of data.

### Steps to Reproduce

  1. Clean profile on 0.20.14
  2. Open Bookmark Manager
  3. Add a folder under Bookmarks Toolbar in the tree (Folder A)
  4. Add a sub-folder (Folder AA)
  5. Add a sub-subfolder (Folder AAA)
  6. Quit Brave.

**Actual result:**
5-10s delay in closing Brave (closer to 10s):

![brave-beta-closing-delay](https://user-images.githubusercontent.com/28145373/34541641-00e1aa92-f0a7-11e7-9eee-a3b335862a21.gif)

**Expected result:**
No delay in closing.

**Reproduces how often:**
Easily with these steps. Other steps probably produce this result as well.

### Brave Version

**about:brave info:**
Brave | 0.20.14
V8 | 6.3.292.48
rev | 5d75826
Muon | 4.5.33

**Reproducible on current live release:**
no, STR do not reproduce on 0.29.123

### Additional Information
Found on MacOS, Reproduced on Linux and Win 10 x64 by @kjozwiak

**Comment by bsclifton** [comment]
wow- great find! 😄  Taking a look...

**Comment by petemill** [comment]
Timeout for waiting for windows to respond with their state on shutdown is 10 seconds, so probably hitting that

**Comment by petemill** [comment]
Looks like an extra hidden window is being created when those settings are changed
