### ISSUE TITLE
Metamask broken on idex.market

### ISSUE THREAD

**Issue by Panoplos** [brave/browser-laptop#12499]
### Description

After enabling Metamask, it seems not to work on [idex.market](https://idex.market).

### Steps to Reproduce

  1. Enable Metamask
  2. Navigate to idex.market
  3. Click on Unlock Wallet
  4. Select "Metamask" and click on "Unlock Metamask"

**Actual result:**

Get a "Metamask not installed" error.

**Expected result:**
Successful unlocking of wallet.

**Reproduces how often:**

Every time.

### Brave Version

**about:brave info:**

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**

No idea.

### Additional Information

None

**Comment by jonasman** [comment]
For me the problem with IDEX and Metamask is to deposit.

**Comment by bsclifton** [comment]
cc: @jonathansampson

**Comment by JoshuaDuChene** [comment]
I'm reproducing this issue according to the steps above with the exact same outcome, also on Brave browser. Here is my browser information:

Brave: 0.22.669
V8: 6.6.346.24
rev: 6cda2e8
Muon: 5.2.7
OS Release: 10.0.16299
Update Channel: Release
OS Architecture: x64
OS Platform: Microsoft Windows
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 66.0.3359.117
