### ISSUE TITLE
Open URL with Brave

### ISSUE THREAD

**Issue by MrHappy45** [brave/browser-laptop#1249]
I am not able to open any URL inside Brave

e.g: Click on a link > Opens in Brave

It doesn't work...
I don't know if it's a known bug I searched in the issues section nothing came up.

**Comment by weems** [comment]
@MrHappy45 Please provide your OS and Brave Version, and more detailed Steps to Recreate the Issue (eg: What Page you are on when you click a link and am unable to load the page, etc). Thanks.

**Comment by MrHappy45** [comment]
Yes, sorry...

I have a Windows 10 PC
and Brave Version 0.8.3

**Comment by luixxiul** [comment]
Closing for now. Please leave comments if it still exists to reopen this issue, thanks.
