### ISSUE TITLE
When dragging a newly made folder to a new position, the folder doesn't place properly in the bookmark toolbar.

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#12506]
### Description
When I add a new folder into the bookmarks toolbar and then try to drag that new folder to a new position, the folder stays in the same spot until I move a current bookmark to a new position. After I move a current bookmark to a new position then the new folder I made will shift into the position I dragged it to previously.

### Steps to Reproduce

  1. Have a few bookmarks already bookmarked in the toolbar
  2. Add a new folder to the toolbar. Right click > "Add Folder"
  3. Once the folder is made, try and move it to a new position in the toolbar.
  4. When you release your mouse, the folder will not be placed.
  5. Move a bookmark that is already in the toolbar to a new position along the toolbar
  5. The folder you recently added will move after you move a current bookmark to a new position

**Actual result:**
![brave bookmark issue](https://user-images.githubusercontent.com/8153239/34586064-49ca0dca-f157-11e7-9877-f4615cc838f7.gif)

**Expected result:**
The new folder to move to a new position without having to move a current bookmark. In the Live Build, 
from https://www.brave.com/download/, the non Dev build, it works as it's supposed to. 

**Reproduces how often:**
100%

### Brave Version
Brave	0.22.0
V8	6.3.292.48
rev	47fe275
Muon	4.6.3
OS Release	10.0.17063
Update Channel	Nightly
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	63.0.3239.108

I am on latest Github commit [aba789a](https://github.com/brave/browser-laptop/commit/aba789a20b4f1902a32398be4913f4afb6f82a9f) when this is happening. Not sure what is the cause, but that commit is the one I am on. So the latest.

**Reproducible on current live release:**
Does not reproduce in the build downloaded from the website
0.19.123 
https://www.brave.com/download/

### Additional Information
N/A

**Comment by LaurenWags** [comment]
+1 from me using 0.20.15
