### ISSUE TITLE
Add cryptotokenPrivate and device support (hid and usb) for U2F

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#12507]
For tracking:
https://github.com/brave/muon/pull/268

**Comment by NejcZdovc** [comment]
closing as muon PR was merged

**Comment by bsclifton** [comment]
@evq can you provide some testing steps (you can edit the top post).  Thanks! 😄 👍

**Comment by evq** [comment]
@bsclifton should I add them here, or edit https://github.com/brave/browser-laptop/pull/10530  ?

**Comment by bsclifton** [comment]
@evq here would be great 😄

**Comment by evq** [comment]
Added, thanks @bsclifton  :)

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0

Test plan works but still have issues relating to other domain login (#13564)

**Comment by kjozwiak** [comment]
This will appear in the release notes via #518.
