### ISSUE TITLE
no longer prompted to save wallet recovery file

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12508]
### Description
In 0.19.123 when you select Backup your wallet > Save recovery file... you are prompted to save the file. In 0.19.125 when you do these same steps, the file opens in a new tab and you are not prompted to save. (Print key/Save recovery file... have the same outcome, opening the file in a new tab)

### Steps to Reproduce

  1. Clean install 0.19.125
  2. Enable payments.
  3. Open Adv Settings
  4. Select Backup your wallet
  5. Select Save recovery file...

**Actual result:**
File is opened in a new tab:
![walletbackup-019125](https://user-images.githubusercontent.com/28145373/34591554-68468e24-f18c-11e7-950b-caf5834b4f9b.gif)

**Expected result:**
You should be prompted to save the file:
![walletbackup-019123](https://user-images.githubusercontent.com/28145373/34591561-6f61c552-f18c-11e7-92fe-acb916e56f8e.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.125
rev | d81a458
Muon | 4.5.34

**Reproducible on current live release:**
no

**Comment by NejcZdovc** [comment]
I checked out code that was changed in b-l and I can't find anything that could cause it. Is it possible that there was something changed in Muon? @bsclifton @darkdh

**Comment by bsclifton** [comment]
Manually cherry picked in https://github.com/brave/browser-laptop/pull/11531 (which was missing). This should fix the issue. Will test locally and close issue if so 😄

**Comment by bsclifton** [comment]
Also present in 0.20.x... I'd like to propose pushing the issue to that release

**Comment by cezaraugusto** [comment]
cc @darkdh I recall you fixed system prompt a while ago and may have some thoughts
