### ISSUE TITLE
Tabs permanently stuck if Brave is out of RAM

### ISSUE THREAD

**Issue by Katamori** [brave/browser-laptop#12516]
### Description

If used under heavy RAM load, then, when resource is taken away from tabs, thy become unresponsive. You can't click back on them, and given the lack of internal task manager, you can't even close them.

### Steps to Reproduce

  1. Make your RAM usage above 90%.
  2. Open multiple tabs in Brave and switch to another program. Use it and wait.
  3. Return to Brave and try to click on tabs.

**Actual result:**
 
Tabs don't react to any mouse-based interaction.

**Expected result:**

Tabs can be opened as always.

**Reproduces how often:**

Frequent under heavy RAM load.

### Brave Version

**about:brave info:**

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**

Yes

**Comment by srirambv** [comment]
This issue has been captured here #12202. Closing as dupe. Added +1 on the issue

**Comment by Katamori** [comment]
Oh, sorry, the different wording made me confused.

**Comment by srirambv** [comment]
No worries. Thanks for reporting

**Comment by kjozwiak** [comment]
Thanks for taking the the time to report this @Katamori! Closing as this is a dupe.
