### ISSUE TITLE
Dual Factor Auth not working properly for gmail

### ISSUE THREAD

**Issue by modusops** [brave/browser-laptop#12511]
**Description**
When loading gmail account requiring DFA, user gets a modal that doesn't resolve the issue. 

### Steps to Reproduce
Load a gmail account requiring DFA

**Actual result:**
User gets an error (timed out) modal
![screen shot 2018-01-04 at 8 35 57 pm](https://user-images.githubusercontent.com/7923023/34593610-fa040d3e-f199-11e7-9ef6-1edecdfea392.jpg)

**Expected result:**
User should see modal to enter the key code

**Reproduces how often:**
100%
 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/7866
