### ISSUE TITLE
Brave doesn't auto-include sites by default

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#12512]
### Description
Brave missing new sites for auto-include

### Steps to Reproduce
  1. Visit new website
  2. Check preferences to see if it's included in Brave payments system

**Actual result:**
New site not included

**Expected result:**
New site should be included

**Reproduces how often:**
I just noticed for a slew of sites.

### Brave Version

**about:brave info:**

Brave | 0.19.123
-- | --
rev | f45cb3a
Muon | 4.5.31
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.4.0
OS Architecture | x64

**Reproducible on current live release:**
Unknown. I'm on dev.

### Additional Information
I noticed this today for VentureBeat, FierceCable, iPhoneHacks, AppleInsider, and some other sites I forgot.

**Comment by NejcZdovc** [comment]
Did you changed your limits (min visit time/min visit count) in advance settings?

**Comment by stshank** [comment]
I've changed settings several times but for the last few months I haven't. It's currently set at auto-include, 8 seconds minimum page time, 1 visit for relevancy. I'm not sure if this problem is still happening, though. I think I did see a case but also I saw cases where it didn't. (Sorry I haven't tracked closely.)

**Comment by NejcZdovc** [comment]
closing for now, if you maybe have any new info or steps how to reproduce it please let me know
