### ISSUE TITLE
revoked SSL cert not showing cert error for some users

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12510]
https://revoked.badssl.com/ does not show a cert error for me on 0.19.x or master, but it does show an error (expected) for @jumde. I am on El Cap.

**Comment by jumde** [comment]
From @petemill : 
"
- shows error on master / macOS 10.13.2
- does *not* show error on master / ubuntu 16.04 and master / win10 "

**Comment by diracdeltas** [comment]
seems to work for High Sierra

does not work for el cap, ubuntu 16.04, windows 10

**Comment by diracdeltas** [comment]
waiting on new muon build

**Comment by bsclifton** [comment]
Waiting for review / merge via https://github.com/brave/muon/pull/431

**Comment by diracdeltas** [comment]
@bsclifton my local mac muon build hasn't been working in a while but i will try to test out the PR today. moving to hotfix for now

**Comment by bsclifton** [comment]
@diracdeltas @jumde the muon PR (https://github.com/brave/muon/pull/431) was merged; anything else needed in browser-laptop for this to be complete?

**Comment by diracdeltas** [comment]
the Muon PR doesn't actually fix the issue
