### ISSUE TITLE
Auto play site settings is retained even after clearing it until browser restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12514]
### Test plan
See https://github.com/brave/browser-laptop/pull/12785

### Description
Found while testing #12149, Auto play site settings is retained even after clearing it. 

### Steps to Reproduce
  1. Clean install 0.19.126
  2. Clear auto play site setting in security
  3. Change autoplay setting to always ask
  4. Visit YT in a new tab and play video, notification bar not shown for autoplay, video starts playing
  5. Visit Vimeo in a new tab and play video, notification bar is shown to allow playing video

**Actual result:**
![12149](https://user-images.githubusercontent.com/17010094/34602289-3205c84a-f225-11e7-83cd-2271cee7ba94.gif)

**Expected result:**
Should ask to allow video playback for YT when the site setting is cleared

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.126
-- | --
rev | a8cd0cc
Muon | 4.5.35
libchromiumcontent | 63.0.3239.108
V8 | 6.3.292.48
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment]
Moving to 20.x as its an existing behaviour

**Comment by LaurenWags** [comment]
I can't reproduce in 0.19.123 on MacOS:
![12514-019123](https://user-images.githubusercontent.com/28145373/34612671-aeb5f1d0-f1f8-11e7-9882-c3f81182823b.gif)

**Comment by bsclifton** [comment]
cc: @srirambv @kjozwiak can you please retest this? 😄

**Comment by darkdh** [comment]
The culprit is `Clear All` which will not have effect immediately so it is not Windows specific
