### ISSUE TITLE
Restored tab can't go back

### ISSUE THREAD

**Issue by frap129** [brave/browser-laptop#12525]
### Description
Using ctrl+shift+t to restore a tab doesn't restore the back/forward history of the tab

### Steps to Reproduce

  1. Open a tab
  2. Navigate multiple pages (ex. Google -> search -> click a result) 
  3. Close tab
  4. Press ctrl+shift+t to restore tab
  5. Back button is not useable

**Actual result:**
Cannot go back

**Expected result:**
Full back history is retained

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**

Yes

### Additional Information

This may be considered a security feature I guess, but it's not the behavior in Chrome or Firefox, so I'd prefer if its fixed or a toggle is added to enable/disable this.

**Comment by eljuno** [comment]
Duplicate of #2702?

**Comment by frap129** [comment]
@eljuno well I guess I need to work on my searching skills, couldn't find that earlier.
