### ISSUE TITLE
sometimes unable to scroll on pages when site isolation is enabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12526]
### Description
Sometimes when strict site isolation is enabled, you are unable to scroll using mouse wheel/track pad on some sites. 

### Steps to Reproduce

  1. Clean profile 0.19.127. 
  2. Nav to brianbondy.com
  3. Click on twitter icon, his twitter opens in a new tab. you can scroll up and down using track pad and/or mouse wheel.
  4. Close twitter tab.
  5. Open about:preferences#security
  6. Enable strict site isolation and restart Brave.
  7. Go back to brianbondy.com
  8. Click on twitter icon.

**Actual result:**
Unable to scroll in twitter tab (use arrow keys as work around).

**Expected result:**
Should be able to scroll without problem.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.127
rev | d29f891
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132

**Reproducible on current live release:**
no

### Additional Information
Also, if you copy/paste the URL from step 8 into a completely new tab, you can scroll without issue.

Reproduced on Win 10 x64 by @kjozwiak

**Comment by darkdh** [comment]
I've experience the same phenomenon and especially when open a new tab through a link. I visited the same site by directly opening a new tab and navigate to it on url bar to verify but it worked fine.
However, I still don't know the accurate steps to reproduce.

**Comment by darkdh** [comment]
Also noticed I couldn't drag the time progress bar or click the play/pause button on youtube video

**Comment by srirambv** [comment]
+2 from community https://community.brave.com/t/cannot-scroll-any-page-with-touchpad-only-scroll-with-buttons-up-and-down/13771/6

**Comment by LaurenWags** [comment]
+1 from twitter: https://twitter.com/CaptnBaz/status/954480280986898435
Also, user found that:
1. It happens when following a link with the target="_blank" attribute
2. If I manually open the link in a new tab (cmd + click), everything's fine

**Comment by Liunkae** [comment]
+1 from me (#12638). @darkdh See https://github.com/brave/browser-laptop/issues/12638#issuecomment-357584583 for my STR.

**Comment by PayLeaseBrian** [comment]
I experience in 0.20.30 as well.

Didn't realize it was specific to site isolation. May disable in short term.

**Comment by bsclifton** [comment]
Issues with strict site isolation are fixed with brave-core 😄 

You can download the developer channel release here:
https://brave.com/download-dev
