### ISSUE TITLE
`snap refresh brave` with 0.19.123 outputs `snap "brave" has no updates available`

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12531]
`snap refresh brave` with 0.19.123 outputs `snap "brave" has no updates available`. However, the latest version is 0.20.

Additionally I logged in as a root user with `su -` and ran `apt-get update && apt-get upgrade -y`, but that output ended with `0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.`

### Brave Version

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-22-generic 
OS Architecture: x64

**Comment by bsclifton** [comment]
@jamesray1 0.19.123 is the latest release version. The 0.20.x series are on the BETA channel, which is separate. You can actually install both at the same time... however, I don't think there are snaps for the beta version
