### ISSUE TITLE
First entry in history has invalid date

### ISSUE THREAD

**Issue by gillespiecd** [brave/browser-laptop#12536]
### Description

1. First history date is December 31, 1969. Which is 1 day before the first epoch date?

I think this might happen when `this.props.date` is empty.

### Steps to Reproduce

  1. Go to `about:history`
  2. Scroll to bottom of page.
  3. See the first date as December 31st, 1969.

**Actual result:**

![screen shot 2018-01-06 at 4 29 10 pm](https://user-images.githubusercontent.com/6572184/34645320-cdb45782-f2fe-11e7-88c9-b2192c6730e7.png)

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.1.0 
OS Architecture: x64

**Reproducible on current live release:**

I just upgraded and still saw the issue.

**Comment by bsclifton** [comment]
This has been addressed with 0.20.x which finally split the history and bookmarks apart 😄 Before then, a timestamp of -1 was used to signify these were example bookmarks to show on a fresh `New Tab` page
