### ISSUE TITLE
Unable to open local HTML file

### ISSUE THREAD

**Issue by alaminos** [brave/browser-laptop#12539]
### Description
If Brave is already launched, double-clicking an HTML file that is stored in my machine will not cause Brave to open it. Nothing happens.

Notice Brave is set as default browser.
I have tried with different HTML files of varying complexity, same result.
I have tried opening the file by right-click and then click Open, same result.
When Brave not set as default, trying to get Brave to open the file is also impossible.
Default or not, getting any other of my browsers to open the file works fine.

### Steps to Reproduce

  1. Launch Brave in a Windows 8.1 machine
  2. Try to get Brave to open an html file stored on your hard drive, either by double-clicking the file (if Brave is default browser), or choosing Brave from the list displayed under "Open with" within contextual menu of file.

**Actual result:**
Nothing.

**Expected result:**
Brave opens the file.

**Reproduces how often:**
Systematically apparently.

### Brave Version

**about:brave info:**
 
Brave: 0.19.130 
rev: baf4da348024ce13950b77c22249858dda742447 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.3.9600 
OS Architecture: x64

**Reproducible on current live release:**
I don't know.

### Additional Information
Related issue: If Brave is NOT launched, double-clicking the HTML file will launch Brave but the file will be in an extra window, so Brave opens in two windows: one window for the html file and another containing tabs from last session.

**Comment by zzamboni** [comment]
I am seeing the same behavior on the Mac. Brave version:

Brave: 0.23.104 
V8: 6.8.275.24 
rev: b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
Muon: 8.0.8 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

The behavior is as follows:

- If Brave is already running when I double click (or use `open` on) an HTML file, then a new tab gets created, but it remains empty (the URL bar says "about:blank")
- If Brave is not already running, then it gets executed, previous tabs restored, and an additional about:blank window created.
- If I enter the path of the file in the URL bar, then it gets displayed correctly.

**Comment by bsclifton** [comment]
Confirmed this is fixed with our [Developer channel](https://brave.com/download-dev) 😄
