### ISSUE TITLE
decimal points are not working as expected under ledger-state.json

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12533]
### Description

Selecting `7.5 BAT` as the monthly budget will result in the following entry in `ledger-state.json`:

```
  "ballots": [],
  "transactions": [],
  "properties": {
    "setting": "adFree",
    "fee": {
      "currency": "BAT",
      "amount": 7
    }
```

Selecting `17.5 BAT` as the monthly budget will result in the following entry in `ledger-state.json`:

```
  "ballots": [],
  "transactions": [],
  "properties": {
    "setting": "adFree",
    "fee": {
      "currency": "BAT",
      "amount": 17
    }
```

### Steps to Reproduce

  1. launch `0.19.129` and enable payments via `about:preferences#payments`
  2. select `7.5 BAT` in the monthly budget and close Brave
  3. `vim ~./config/brave/ledger-state.json`

**Actual result:**

You'll notice that `7.5 BAT` appears as `7` and `17.5 BAT` appears as `17` within `ledger-state.json`. See above for examples.

**Expected result:**

Values should be appearing as `7.5` and `17.5 BAT` within `ledger-state.json`.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.129 
> rev: 762e2c4fc539c31ea99d2cb1aa10c7ff75aa0de8 
> Muon: 4.5.36 
> libchromiumcontent: 63.0.3239.132 

**Reproducible on current live release:**

N/A (this has been added within this milestone and doesn't exist in the latest release)

### Additional Information

* Ubuntu 17.10 x64 - Reproduced
* Win 10 x64 - Reproduced
* macOS 10.13.2 x64 - Reproduced

**Comment by bsclifton** [comment]
Fixed by cherry picking into 0.19.x with https://github.com/brave/browser-laptop/commit/f502089a162a448bbee6364c361675dd269fabfe

https://github.com/brave/browser-laptop/pull/12535 covers the other branches

**Comment by srirambv** [comment]
Verified for Windows on build 0.19.130
![image](https://user-images.githubusercontent.com/17010094/34660539-15105354-f469-11e7-9f92-b3935cb3c1c1.png)

**Comment by LaurenWags** [comment]
Works on MacOS:
![screen shot 2018-01-08 at 9 59 10 am](https://user-images.githubusercontent.com/28145373/34676399-adea4a1c-f45a-11e7-9141-97d2ae7bf6c1.png)
