### ISSUE TITLE
Tab opening enhancement

### ISSUE THREAD

**Issue by philhellmuthIE** [brave/browser-laptop#12546]
### Description
This happens when you're on the last tab at 1st page, and every new tab would be opening on the page 2 (http://prntscr.com/hxmhwm).
If you start opening new tabs from the last tab on page 1, you will know only if the first one opened successfully because an arrow will appear at the end of tab bar.
But after this first tab in the page 2 you won't be getting any other indicators that the new tabs are getting successfully opened in page 2.

### Steps to Reproduce
1. Open 20 tabs to fill page 1
2. Inside the last tab (so that all new tabs get opened in the page 2) start clicking links holding "CTRL+" to open new tabs
3. You'll know that the first tab successfully opened in page 2 because the arrow will appear at the end of the tab bar on the page 1, but there will be no other indicators that you kept opening tabs #22,23,24... successfully.

**Actual result:**
http://prntscr.com/hxmoto

**Expected result:**
In my opinion it would be an enhancement if the arrow which leads to page 2 of tabs would blink every time we click links while we're in opening tabs in the new tab page.

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/955
