### ISSUE TITLE
When you "Copy Image" from Google images and try to paste, the image you copied doesn't paste.

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#12540]
### Description
When you go into google images and search for an image. Then right click --> "Copy Image", when you go to paste the image, it doesn't paste the image. It will paste whatever you had on your clipboard previously, but not the image you just copied

### Steps to Reproduce
  1. I am doing this from the latest commits from github.
  2. Go to google images, or Imgur, or any image hosting site. (I only checked those two)
  3. Find an image
  4. Right click on it and press "Copy Image".
  5. Go to an app that can paste images. I used Discord and Telegram
  6. Paste the image
  7. If you had copied something before the image, you will see that paste instead of the image you just copied.

**Actual result:**
![brave copy and paste issue](https://user-images.githubusercontent.com/8153239/34654857-2c58f2b8-f3b6-11e7-8ff0-d926c38bcf0a.gif)

**Expected result:**
The image I selected to copy to be pasted successfully. It seems like pressing "Copy Image" does not do anything right now.

**Reproduces how often:**
100% of the time in the latest commits from github

### Brave Version

Brave | 0.22.0
-- | --
V8 | 6.3.292.48
rev | 667f95d
Muon | 4.6.3
OS Release | 10.0.17063
Update Channel | Nightly
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

I am on the latest github commit [667f95d](https://github.com/brave/browser-laptop/commit/667f95d5fea262fe4320d6578482b875f6086c75)

**Reproducible on current live release:**
This does not reproduce in the non developer version from https://www.brave.com/download/
Version: 0.19.123. It also does not reproduce in the latest pre-release in releases channel. Version v0.19.130

### Additional Information
I have only tested this with Google Images and Imgur using telegram. But I did the same websites in the live version, 0.19.123, and it worked as intended.

**Comment by bsclifton** [comment]
Thanks for the report @JMccormick264 - I believe this has been an issue for a while and is captured with https://github.com/brave/browser-laptop/issues/7388.  I'll add your notes there
