### ISSUE TITLE
Touch Bar support for newer MacBook Pro machines

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12549]
Instead of function keys, newer MacBook Pro machines have a touch-sensitive display above the number keys. Applications can show custom controls in this space. Brave could take advantage of this space to improve usability. Developer docs for this feature start at <https://developer.apple.com/macos/touch-bar/>.

**Comment by Liunkae** [comment]
See also the Electron TouchBar API: https://electronjs.org/docs/api/touch-bar

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/touchbar-in-macbook-pro/13891

**Comment by lucasrodes** [comment]
+1

**Comment by frankieshakes** [comment]
+1

**Comment by Liunkae** [comment]
The new Chromium-based version of Brave already has touch bar support. However, Brave may still want to add custom buttons (for Brave shields panel, etc.).
![](https://user-images.githubusercontent.com/19424103/41926906-45c5c3a6-7936-11e8-8e09-63011232196c.png)

**Comment by Liunkae** [comment]
@frankieshakes Yes.

**Comment by bsclifton** [comment]
Closing as `wontfix` since we'd have to do quite a bit of work to get this working (pulling in patches from Electron, etc)

As noted above, Brave core already has support for this 😄 Thanks for confirming, @Liunkae!

**Comment by tbates** [comment]
Suggestions about what functions would be useful on the touch bar [here](https://community.brave.com/t/touch-bar-support/1046/2).

Things with an often-used easily-hit keyboard short cuts seem of not much use: like search: it's just cmd-L and start typing...
