### ISSUE TITLE
Sync - Bookmarks are not sync correctly

### ISSUE THREAD

**Issue by janos-szenfner** [brave/browser-laptop#12542]
### Description
When I sync 2 machines the bookmarks are not merged, but duplicated.

It would be great if it would work like Firefox or Chrome. The bookmark management across devices are very beta.

Also the sync is not stable.

### Steps to Reproduce

  1. Start sync on one machine
  2. Add a second machine to the sync
  3. Check the bookmarks.

**Actual result:**

The bookmarks are duplicated

**Expected result:**
Work as in chrome or firefox or Opera or Edge

**Reproduces how often:**

Every time

### Brave Version

**about:brave info:**

0.19.123
--

**Reproducible on current live release:**

**Comment by srirambv** [comment]
What exactly do you mean duplicated? Are these bookmarks duplicated on the same device where the bookmarks are imported/created and not propagated to the other device?

**Comment by janos-szenfner** [comment]
If there is a same folder and within the bookmark folder there are same bookmarks the sync not merging, but duplicating it.

1, Browser 1 - Bookmark Imported from Chrome
2. Browser 2 - Bookmark imported from same Chrome bookmarks, although different environment
3. Setting up Brave sync

Bookmarks are not merged, but the folders with the same name are duplicated.

**Comment by arooni** [comment]
is this a closed issue?

i have an ubuntu latop and a mac desktop and i've linked the two but find that there's no favorite/bookmark sync working
