### ISSUE TITLE
Unable to install brave snap "brave" already installed

### ISSUE THREAD

**Issue by plaxer** [brave/browser-laptop#12541]
### Description

Getting the following error `unable to install brave snap "brave" already installed` when trying to install Brave from snap on Ubuntu 17.10. It shows the install button but after clicking, it shows the above error. I have checked for installed packages using `sudo dpkg --list` but brave wasn't found. I've also tried purging Brave but it says not installed. 

I can see the brave icon in my software menu. I click on it but it won't launch. I've installed Brave in the past and got the same issue launching Brave as the browser was installed but the window won't launch. I've also checked list of installed snap software and Brave doesn't seem to be there.

### Steps to Reproduce

  1. Launch software program on Ubuntu and search for Brave
  2. Click on install button and `unable to install brave snap "brave" already installed` error appears
  3. Click on installed software tab to see if Brave is on list of installed software - Brave not seen.
  4. Click on menu and Brave is seen on software list.
  5. Click on Brave but no window appears

**Actual result:**

`unable to install brave snap "brave" already installed`

**Expected result:**

Brave should show in list of installed software and should display a windows when launched.

**Reproduces how often:**

100% - Happens whenever I launch Brave

### Brave Version

**about:brave info:**

Unable to launch Brave to find out but here is the info from the snap software store;

Version: v0.19.123dev
Updated: 28/12/17
License: Unknown
Developer: brave
Source: Snap Store

**Reproducible on current live release:**

Yes

### Additional Information

N/A - Broken package

**Comment by natanielcz** [comment]
Could you please type in terminal command `snap list brave` to see If brave is installed? 
And If It's installed you can remove it typing `sudo snap remove brave`
