### ISSUE TITLE
Fix initial 2000 grants during last promotion

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12547]
### Description
When we did a promotion using the BAT user-growth-pool (UGP), the first 2000 had a settlement time in seconds instead of milliseconds.

We need to make an update to the `bat-client` library to include a fix for this situation so that folks can reconcile

**Comment by evq** [comment]
# Test Plan
1. load a wallet with a grant
2. modify ledger-state.json to trigger immediate reconcile
3. modify ledger-state.json to insert an old `currentReconcile`
4. ensure that after failure to reconcile the value of `surveyorId` in  `currentReconcile` is cleared and pulls updated values from the server
