### ISSUE TITLE
"Always show the URL bar" text missing in preferences

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#12559]
### Description
Look in Preferences > Advanced > URL Bar Options. There is an option titled `disableTitleMode`, which is the localization variable name. In English, the localized text should be `Always show the URL bar` ([source](https://github.com/brave/browser-laptop/blob/aba789a20b4f1902a32398be4913f4afb6f82a9f/app/extensions/brave/locales/en-US/preferences.properties#L107)). As far as I can tell, this only happens with English. I tried Spanish and French, and it looks fine.

### Steps to Reproduce

  1. Open Brave and navigate to Preferences > Advanced > URL Bar Options.
  2. Look at the options in that screen.

**Actual result:**
There is an option titled `disableTitleMode`.
![](https://user-images.githubusercontent.com/19424103/34705725-2c6ae5f0-f4c8-11e7-92ec-659a13c65201.png)

**Expected result:**
The option should be titled `Always show the URL bar`.

**Reproduces how often:**
Always, if using English.

### Brave Version

**about:brave info:**
 
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes, 0.19.131.

### Additional Information
I think it changed between 0.19 hotfixes 10 (0.19.123) and 11 (0.19.131), but I'm not sure.

**Comment by cezaraugusto** [comment]
can't repro on 0.20.16 @Liunkae @srirambv could you please confirm?

**Comment by Liunkae** [comment]
I cannot repro on 0.20.16 either. Looks like it's confined to 0.19.x.

**Comment by bsclifton** [comment]
Only impacted 0.19.x (accidentally removed with https://github.com/brave/browser-laptop/commit/e2d0ed6c77b723b5cf5dae171d31e9e879d75755)

Fixed with https://github.com/brave/browser-laptop/commit/832e1fdb81725f5ba4a1c17fdccddf9578c3419d
