### ISSUE TITLE
Ledger test run on Linux for 0.19.x Hotfix 11 (Release Channel)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12552]
## Per release specialty tests
 - [x] Fix initial 2000 grants during last promotion. ([#12547](https://github.com/brave/browser-laptop/issues/12547))

## Ledger

- [x] Verify wallet is auto created after enabling payments
- [x] Verify monthly budget and account balance shows correct BAT and USD value
- [x] Click on `add funds` and click on each currency and verify it shows wallet address and QR Code
- [x] Verify that Brave BAT wallet address can be copied
- [ ] Verify adding funds via any of the currencies flows into BAT Wallet after specified amount of time
- [ ] Verify adding funds to an existing wallet with amount, adjusts the BAT value appropriately 
- [x] Change min visit and min time in advance setting and verify if the publisher list gets updated based on new setting
- [x] Visit nytimes.com for a few seconds and make sure it shows up in the Payments table.
- [x] Check that disabling payments and enabling them again does not lose state.
- [x] Upgrade from older version
   - [x] Verify the wallet overlay is shown when wallet transition is happening upon upgrade 
   - [x] Verify transition overlay is shown post upgrade even if the payment is disabled before upgrade
   - [x] Verify publishers list is not lost after upgrade when payment is disabled in the older version

## Ledger Media

  - [x] Visit any YouTube video in a normal/session tab and ensure the video publisher name is listed in ledger table
  - [x] Visit any YouTube video in a private tab and ensure the video publisher name is not listed in ledger table
  - [x] Visit any live YouTube video and ensure the time spent is shown under ledger table
  - [x] Visit any embeded YouTube video and ensure the video publisher name is listed in ledger table
  - [x] Ensure total time spent is correctly calculated for each publisher video
  - [x] Ensure total time spent is correctly calculated when switching to YouTube video from an embeded video
  - [x] Ensure YouTube publishers are not listed when `Allow contributions to video` is disabled in adavanced settings
  - [x] Ensure existing YouTube publishers are not lost when `Allow contributions to video` is disabled in adavanced settings
  - [x] Ensure YouTube publishers is listed but not included when `auto-include` is disabled
  - [x] Update Advanced settings to different time/visit value and ensure YouTube videos are added to ledger table once criteria is met

**Comment by LaurenWags** [comment]
Tests were as expected.

**Comment by kjozwiak** [comment]
Awesome, thanks for going through these @LaurenWags!
