### ISSUE TITLE
Closing fixed-width tabs and then moving mouse away animates tabs past bounds of tab-bar

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12566]
### Description
Bug introduced by #11438 and reported by @luixxiul in https://github.com/brave/browser-laptop/pull/11438#issuecomment-336662415

### Steps to Reproduce
from https://github.com/brave/browser-laptop/pull/11438#issuecomment-337137402
1. Open 10 tabs (until the tab size changes)
2. Click the close button on a tab
3. Move the mouse cursor from the tabs bar

![tabs](https://user-images.githubusercontent.com/3362943/31578821-08f754ca-b164-11e7-9e6c-95f4545c725e.gif)

Should animate to final width, not too wide and then back to final width.

**Reproduces how often:**
100% on master

### Brave Version

**about:brave info:**
0.22

**Reproducible on current live release:**
No

**Comment by petemill** [comment]
#12567 does not cater for pinned tabs, or for multiple tab pages. Reverting that and reopening this issue...

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87

**Comment by LaurenWags** [comment]
@petemill still experiencing this on 0.23.14, reproduced by @srirambv

**Comment by bsclifton** [comment]
This should be fixed in our next build- closing so that it can be retested 😄
