### ISSUE TITLE
[Intermittent] Closing browser doesn't kill background worker processes instantly

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12564]
### Description
Closing browser doesn't kill background worker processes instantly

### Steps to Reproduce
  1. Clean install 0.20.16
  2. Close the browser from window action button
  3. Background process takes time to close

**Actual result:**
Closing browser doesn't kill background worker processes instantly

**Expected result:**
Should kill all background process when the browser is quit

**Reproduces how often:**
Intermittent issue

### Brave Version

**about:brave info:**

Brave | 0.20.16
-- | --
V8 | 6.3.292.49
rev | 0c42d0b
Muon | 4.5.36
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.132

**Reproducible on current live release:**
No

### Additional Information
Happened 3/5 times before logging the issue. Unable to capture the issue in gif

**Comment by srirambv** [comment]
Here's a recording of the task manager where the background process is still active when the browser window is closed 
![backgroundprocess](https://user-images.githubusercontent.com/17010094/34711814-abe363c4-f546-11e7-907d-2d44a3190d65.gif)

**Comment by bsclifton** [comment]
Closing as we accepted https://github.com/brave/browser-laptop/pull/12582; next build, let's test this 😄
