### ISSUE TITLE
App icon generic in Browserism

### ISSUE THREAD

**Issue by TraderStf** [brave/browser-laptop#1256]
The lion icon is displayed as a generic app icon (~white with 3 tools-A) in Browserism menu in the menu bar.

https://itunes.apple.com/fr/app/browserism-for-safari-google/id979047768?mt=12

All other browsers appear correctly (safari, ff, chrome, opera...)

**Comment by luixxiul** [comment]
related: #1282

**Comment by ntmbayfield** [comment]
Hi, I'm a student in the Web Development program at Galvanize and am looking to contribute to my first open-source project.  Could I have this issue assigned to me?

**Comment by ryanml** [comment]
Hi @ntmbayfield ! I've self-assigned this issue so it's all yours :D Let us know if you have any questions.

**Comment by ntmbayfield** [comment]
Thank you, I'll start working on this issue on Thursday

**Comment by bsclifton** [comment]
appears to be resolved
