### ISSUE TITLE
Brave reports as vulnerable to spectre on test site

### ISSUE THREAD

**Issue by g33xter** [brave/browser-laptop#12570]
I'm using Brave 0.19.131 & checked the new security feature which is related to Spectre & Meltdown vulnerability. So, I tried using this [http://xlab.tencent.com/special/spectre/spectre_check.html](url), it's saying it's vulnerable for Spectre. Check the Screenshot. I'm using macOS Sierra.

![screen shot 2018-01-09 at 03 25 33](https://user-images.githubusercontent.com/8503135/34719096-30b19be2-f4ee-11e7-9d41-4b2e5629fbfc.png)

**Comment by srirambv** [comment]
cc: @diracdeltas

**Comment by g33xter** [comment]
You need to enable manually, I guess. use this link chrome://flags/#enable-site-per-process. 
![screen shot 2018-01-09 at 04 19 04](https://user-images.githubusercontent.com/8503135/34720662-5e237a40-f4f4-11e7-8c89-6677e2574208.png)
I don't have any issues with Chrome/Firefox/Safari, they are not vulnerable.

**Comment by srirambv** [comment]
Thanks for the confirmation @g33xter

**Comment by diracdeltas** [comment]
Strict Site isolation only mitigates against Spectre by enhancing separation between iframes and the parent context. It does not prevent Spectre if the parent context is trying to use the attack against you. According to @jumde, we will need to disable SharedArrayBuffer in order to appear as "not vulnerable" according to this test.

**Comment by srirambv** [comment]
Works on Windows 
![image](https://user-images.githubusercontent.com/17010094/34808996-2267a006-f6b8-11e7-8c37-122b8e6b0e5e.png)

**Comment by srirambv** [comment]
Worked on Linux as well
![image](https://user-images.githubusercontent.com/17010094/34812826-6d0e41ea-f6cd-11e7-85d9-37a652890377.png)

**Comment by LaurenWags** [comment]
MacOS using 0.19.132:
![screen shot 2018-01-11 at 9 09 20 am](https://user-images.githubusercontent.com/28145373/34829580-2b57c834-f6af-11e7-8b8e-22291abf4906.png)

**Comment by g33xter** [comment]
@diracdeltas thanks for clarifying.
