### ISSUE TITLE
Align stuff properly on paymentsTab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12572]
### Description

Align stuff properly on paymentsTab

https://github.com/brave/browser-laptop/issues/10236#issuecomment-356260316

> ![image](https://user-images.githubusercontent.com/17010094/34719247-08b27928-f560-11e7-901c-c357566b1d46.png)

### Steps to Reproduce

  1. Open about:preferences#payments

**Actual result:**

See above

**Expected result:**

The switches on the 1st row should be aligned vertically with the stuff inside the gray box.

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

0.20.x

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
cc: @bradleyrichter 

We may chose to close this in favor of the new redesign
