### ISSUE TITLE
does not remember the full size of the window

### ISSUE THREAD

**Issue by GetTurnedOn** [brave/browser-laptop#12571]
does not open to full screen
does not remember the previous event, and the position of the window, on Linux (ubuntu 17.10)
Windows 10
picture for windows 10
This bug is 1 year old !!!!
[pic](https://imgur.com/OlUXWPt)

**Comment by GetTurnedOn** [comment]
It should not be a hidden setting, it should work on the machine

**Comment by dronehitech** [comment]
+1. Still not working.

**Comment by bsclifton** [comment]
Hi folks

This has been fixed via https://github.com/brave/browser-laptop/pull/10458 in our 0.20.x release (beta channel).  You can try our latest build here:
https://github.com/brave/browser-laptop/releases/tag/v0.20.16beta

I'm going to close this issue as a duplicate- but please know that we are trying our best to expedite our release of 0.20.x (which has a LOT of bug fixes! will be over 500 issues).  You can review some of what's included here:
https://github.com/brave/browser-laptop/milestone/76
