### ISSUE TITLE
Autoplay blocking does not work on aftonbladet.se

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#12576]
### Description

Autoplay blocking on Aftonbladet.se does not work and that is probable due to the implomentation of videos they use because I have tested and it works on every other site that I tested! It also worked in Safari with there blocking. Please note that is is one of the biggest news sites in sweden 😓

### Steps to Reproduce

  1. Go to about:preferences > security and set "Autoplay Media" to "Allways deny"
  2. Go to this aftonbladet article: https://www.aftonbladet.se/nyheter/krim/a/Kvprry/polisen-om-bmw-ligan-extremt-effektiva

**Actual result:**

The video starts playing an ad automatically and then goes over to playing the video (see #12575)

**Expected result:**
Videos should not start playing!!!

**Reproduces how often:**

It was originally reported by my dad that this was not working on aftonbladet and i have checked hissettings in brave and everything but the ads still play. I can not get them to play on my Mac or my Windows pc. My dad has macOS El Capitan but I use Sierra.

### Brave Version

**about:brave info:**

Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 15.6.0 
OS Architecture: x64

As said above, can only get it to work on my dads mac with el capitan but not my mac with sierra or my windows pc.

**Reproducible on current live release:**

Yes

### Additional Information

cc @darkdh because I belive you worked on autoplay, right?

**Comment by darkdh** [comment]
@Jacalz can you check the `Autoplay Media` site settings under `about:preferences#security` on your dad's machine?

**Comment by Jacalz** [comment]
Looks like it should to me:
[![D87_D7_F82-5_F04-4_AA3-_B564-_B31381_E612_D4.jpg](https://s14.postimg.org/crnutuwtd/D87_D7_F82-5_F04-4_AA3-_B564-_B31381_E612_D4.jpg)]

**Comment by darkdh** [comment]
ah sorry I meant setting like this
![screen shot 2018-01-09 at 1 00 06 pm](https://user-images.githubusercontent.com/11330831/34743012-1843407a-f53d-11e7-839d-827682036b2b.png)

**Comment by Jacalz** [comment]
Oh yeah, those settings must have been the problem 😓 Did not think for a moment that those could do it because I figured that if the switch was set to "always deny" it would override it 😅 Sorry to bother then 😉
