### ISSUE TITLE
Bad state when updating to Beta 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12586]
### Description
Experienced bad state in browser when upgrading from release build to beta build

### Steps to Reproduce
  1. Clean install 0.19.131 and 0.20.16
  2. Visit few sites on both builds
  3. Enable payments in 0.19.x and set contribution amount to a random value other than default  and close a couple of tabs
  4. Close the beta build window and rename or delete the profile folder (I usually delete)
  5. Copy `brave` folder into `%appdata% and rename it to `brave-beta`
  6. Launch brave-beta window, tabs closed in step 3 is reopened and payments is disabled. Enabling payments shows amount set to 10BAT and not the value set in step 3

**Actual result:**
Bad state when updating to Beta 

**Expected result:**
Settings made in 0.19.x should be retained when the same profile is opened in Beta build

**Reproduces how often:**
Intermittent. Happened twice unable to reproduce it consistently 

### Brave Version

**about:brave info:**

Brave | 0.19.131 | 0.20.16
-- | --| --
rev | da2f347 | 0c42d0b
Muon | 4.5.36 | 4.5.36 
libchromiumcontent | 63.0.3239.132 | 63.0.3239.132
V8 | 6.3.292.49 | 6.3.292.49
Node.js | 7.9.0 | 7.9.0
Update Channel | Release | Beta
OS Platform | Microsoft Windows | Microsoft Windows
OS Release | 10.0.16299 | 10.0.16299
OS Architecture | x64 | x64

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton

**Comment by bsclifton** [comment]
@srirambv did you experience during any recent testing? I'd like to propose that we close the issue

**Comment by srirambv** [comment]
Will give it a try. Haven't checked beta off late. Will update in notes
