### ISSUE TITLE
pinned tabs duplicated after update to 0.20.16

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12580]
### Description
Pinned tabs are duplicated after update to 0.20.16

### Steps to Reproduce

  1. Create a profile on 0.19.131 with a few pinned tabs (I had 3) and multiple windows (I had 3).
  2. Manually update your profile to 0.20.16 
  3. Open 0.20.16.
  4. Your pinned tabs in at least one window are duplicated.
  5. Close/Reopen Brave.
  6. Now pinned tabs in all windows are duplicated.

**Actual result:**
Pinned tabs are duplicated.

**Expected result:**
Pinned tabs should not be duplicated.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.16
V8 | 6.3.292.49
rev | 0c42d0b
Muon | 4.5.36

**Reproducible on current live release:**
no

### Additional Information

I have a profile I can share (testing profile) if that will help.

**Comment by petemill** [comment]
Jazzy gif from @LaurenWags illustrating the issue:
![duplicatepinnedtabs](https://user-images.githubusercontent.com/741836/34753127-27d45234-f61b-11e7-966d-492d3d57c614.gif)
