### ISSUE TITLE
Inspector opens non-visibly

### ISSUE THREAD

**Issue by Lewiscowles1986** [brave/browser-laptop#12585]
### Description

Right click "inspect" or `<ctrl>`+`<shift>`+`<i>` both result in the inspector window opening but not gaining focus, so the webpage is displayed, sometimes highlighting page sections (but without showing the inspector pop-out window).

### Steps to Reproduce

  1. Ubuntu xenial, follow setup guide from master branch of this repo to add to sources.list.d, install brave
  2. visit any website
  3. Right click "inspect" or `<ctrl>`+`<shift>`+`<i>`

**Actual result:**

inspector window opening but not gaining focus, so the webpage is displayed, occasionally with the element, the pointer is over highlighting (as to expect in inspector mode), but without showing the inspector window.

**Expected result:**

inspector window appearing and having focus so I can see it's window in-front of the page (until it can be docked, in that case I don't suppose this would be an issue).

**Reproduces how often:**

100% (I've never seen it take focus)

### Brave Version

**about:brave info:**

 
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.4.0-104-generic 
OS Architecture: x64

**Reproducible on current live release:**

N/A

### Additional Information

I am running Ubuntu Xenial 64-bit with unity. It has oddities with the compositor and occasionally the window manage is unresponsive with core apps like thunar.

**Comment by bsclifton** [comment]
Closing as `wontfix` since this is already fixed with [Brave Core](https://github.com/brave/brave-browser) (coming soon!)
