### ISSUE TITLE
'Enable Publisher' Button Should be Contextually Aware

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12598]
### Description
Brave Payments supports (at the time of this writing) two types of content platforms: personal publishing platforms (like a self-hosted blog), and shared platforms (such as YouTube). The Brave browser offers an _Enable Publisher_ button for easily opting a publisher in or out of your monthly contribution list. This button, however, doesn't distinguish between personal platforms, and shared platforms.

### Steps to Reproduce
1. Navigate to a Channel on YouTube
2. Click _Enable Publisher_

**Actual result:**
YouTube is added to your monthly contributions list

**Expected result:**
The channel being viewed on YouTube should be added to your monthly contributions list

**Reproduces how often:**
100%

### Brave Version
0.19.131

**Reproducible on current live release:**
Yes

**Comment by ryanml** [comment]
@jonathansampson

I'd like to take this on, however, I'm having some trouble seeing where this component (Specifically the Enable Publisher action) exists in the browser and the codebase. Where can I find this? Thanks!
