### ISSUE TITLE
Bug: Login Info for Autofill Appear on Other Tab

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#12595]
### Description

When open a site that require login in new tab, the login info for autofill appear on current tab. Notice this after update to 0.19.131.

### Steps to Reproduce

  1. Use brave built-in password manager to save login info.
  2. Open site in first tab (e.g. brave.com) or dashboard.
  2. Right-click bookmark/thumbnail then open a site that require login (e.g. Uphold) in new tab.
  3. On the current tab/first tab, login info from second tab appear.

**Actual result:**

![login-autofill](https://user-images.githubusercontent.com/25360853/34794186-7c2f9bf8-f680-11e7-8116-de818d086dad.png)

**Expected result:**
No login info appear.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**
Brave | 0.19.131
rev | da2f347
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 6.3.9600
OS Architecture | x64

**Reproducible on current live release:**
NDA

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by NumDeP** [comment]
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

![peek 2018-03-25 02-04](https://user-images.githubusercontent.com/31957540/37870568-4c849bb2-2fd1-11e8-9a74-529ea2559faa.gif)

**Comment by eljuno** [comment]
So far, not face this issue with

Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by NumDeP** [comment]
Neither have I in the same version on Linux. You're best off closing the issue as I doubt it will show up in Brave-Core.

**Comment by darkdh** [comment]
@NumDeP I can assure you it won't show up in different tabs in brave-core but it will still show up when you stay in the same tab until load complete
