### ISSUE TITLE
Bookmark and tabs DND are not working on Windows

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#12590]
### Test plan
  1. Create new folder in the toolbar
  2. Add another folder in this new folder
  3. Try to dnd this folder on the toolbar
  4. Drag and drop should work

### Description

Drag and drop in bookmark toolbar is not working on windows anymore.

### Steps to Reproduce

  1. Create new folder in the toolbar
  2. Add another folder in this new folder
  3. Try to dnd this folder on the toolbar

**Actual result:**

dnd is blocked

**Expected result:**
dnd shouldn't be blocked

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

More info https://github.com/brave/browser-laptop/issues/12481#issuecomment-356303529
  
Related issue #11728

**Comment by NejcZdovc** [comment]
As far as I can see this was broken with #10512 where we moved allowDrag on level up and because of that on Windows dnd is not working for bookmarks and tabs

cc @petemill

**Comment by petemill** [comment]
@bsclifton @NejcZdovc how annoying, I'm on it. 👍
