### ISSUE TITLE
Feature Request: Keyboard Shortcut for toggling Bookmarks Toolbar

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12594]
### Description
The user should be able to toggle Bookmarks Toolbar visibility with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>.

### Steps to Reproduce
1. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>

**Actual result:**
Nothing

**Expected result:**
Bookmarks Bar toggles

**Reproduces how often:**
100%

### Brave Version
0.19.131

### Additional Information
Related to #5212

**Comment by jbyte** [comment]
Hello, I would like to do this one.

**Comment by jonathansampson** [comment]
@jbyte That would be awesome! Let us know if you have any questions about cloning or setting-up the local repo.

**Comment by jbyte** [comment]
The cloning and setup went fine from what I can tell (brave launches normally).

The only question I have is regarding the Brave version. In the issue contents it is stated that this relates to the 0.19.131 version. So should I create my feature branch from the 0.19.x branch or is master ok?

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
