### ISSUE TITLE
If page dont have favicon pin page icon is invisible.

### ISSUE THREAD

**Issue by danielgomezrico** [brave/browser-laptop#1260]
Theres just an space, like something is there and is but without an icon.

As you can see at the left theres a space and then fabric pinned page.
If I click that space it opens the pinned page.

![screen shot 2016-04-05 at 10 59 15 am](https://cloud.githubusercontent.com/assets/76348/14288836/fb4b3eb6-fb1d-11e5-85b6-14a88c1f4e3d.png)

it looks tricky for UX this one, 

maybe:
- have a default favicon for those without one
- use background color for pinned items as selected page color by default

You can try with web.whatsapp.com page.

**Comment by luixxiul** [comment]
ref: #1656

**Comment by luixxiul** [comment]
Fixed with #1656. Update to the latest version and if this still persists please leave a comment. Closing for now.
