### ISSUE TITLE
openSUSE: GConf2 dependency doesn't exist, gconf2 does. 

### ISSUE THREAD

**Issue by fusion809** [brave/browser-laptop#12609]
Hi,

openSUSE install instructions exist, yet when I copy-paste the repository install instructions I get the error (out of `sudo zypper install brave`):

```bash
Problem: nothing provides GConf2 needed by brave-0.19.131-1.x86_64
 Solution 1: do not install brave-0.19.131-1.x86_64
 Solution 2: break brave-0.19.131-1.x86_64 by ignoring some of its dependencies
```

GConf2 doesn't exist as you can see. You can also see evidence of its non-existence here at software.opensuse.org: https://software.opensuse.org/package/GConf2. [gconf2](https://software.opensuse.org/package/gconf2) does exist though. 

Thanks for your time,
Brenton

**Comment by NumDeP** [comment]
@fusion809 @posix4e says in #5580 you'll need to install gconf2-devel and libgnome-keyring-devel

**Comment by fusion809** [comment]
Not sure why the -devel package is needed as all they contain is the development headers. For me gconf2 was all I needed. I suppose libgnome-keyring might come in handy if I need a keyring to store my passwords.

**Comment by NumDeP** [comment]
In addition to those, he also mentioned he downloaded sudo zypper install libxss1 libatk-bridge-2_0-0 libgtk-3-0
