### ISSUE TITLE
nytimes.com is incorrectly allowed to autoplay media

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#12600]
### Description
Currently, [nytimes.com](https://nytimes.com/) is running a feature on their homepage with an autoplayed video.  My autoplay media setting is set to "Always ask," and I do not have nytimes.com under the saved site permissions.

However, when I visit the homepage, the "Allow autoplaying media?" prompt briefly flashes at the top of the screen, then disappears, and then the video is allowed to play.  Under my saved site permissions, nytimes.com is now listed as "Always allow."

I have a GIF below.

### Steps to Reproduce
Unfortunately reproducing might be tied to how long the video stays on the homepage.  I briefly looked for a more permanent example, but couldn't find anything - for example, the actual video section of the site doesn't do the same thing.

Here are the steps:

  1. Go to about:preferences#security and verify that "Autoplay Media" is set to "Always ask." Using CTRL+F, verify that nytimes.com is not in the saved site permissions.
  2. Go to [nytimes.com](https://nytimes.com/).  As of this writing, there is a feature titled "52 Places to Go in 2018" that includes a looping autoplayed video.
  3. A prompt to request autoplay permission for nytimes.com will appear, but will disappear a second later.
  4. The video will start playing
  5. Go back to about:preferences#security and use CTRL+F to see that nytimes.com is now listed under saved site settings for "Autoplay Media," with "Always allow" permissions.

**Actual result:**
Video plays and nytimes.com is incorrectly given permission to *always* autoplay media

**Expected result:**
Video should not play, and nytimes.com should not be given a blank check to autoplay media in the future.

**Reproduces how often:**
Right now, always (as long as the feature is still present on the nytimes front page)

### Brave Version

**about:brave info:**
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**
Yes

### Additional Information
![nytautoplay](https://user-images.githubusercontent.com/13000059/34806120-63987d5c-f64f-11e7-9534-8a4e084b13c9.gif)

**Comment by srirambv** [comment]
I think this is due to the muted media being allowed to play https://github.com/brave/browser-laptop/issues/12152. The video is defaulted to mute 
![image](https://user-images.githubusercontent.com/17010094/34819127-edaa8d6c-f6e2-11e7-9e56-4dc10e564a05.png)

If you close the NYTimes tab you'll see the autoplay site setting gets removed

cc: @darkdh

**Comment by josiah-keller** [comment]
@srirambv @darkdh OK, I didn't realize that was intended.  Now, if this happened and the page later loads in another video that has sound, will that one be allowed to play since that temporary permission is there?  Also, why is the permission prompt displayed at all?

**Comment by darkdh** [comment]
@josiah-keller muted video will not be allowed in 0.21.x
@bsclifton do you think we can uplift the fix into 0.19.x or 0.20.x? 
here is the fix: https://github.com/brave/muon/pull/428

**Comment by bsclifton** [comment]
@darkdh we can uplift the fix into 0.20.x if we were able to get this patch into Muon 4.5.  Do you think that might be possible?

**Comment by darkdh** [comment]
definitely doable

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/ba3906a7288aaada6862901f1de5a8849fe1bcbf
