### ISSUE TITLE
"show my windows / tabs from last time" does not work 

### ISSUE THREAD

**Issue by kwanaa** [brave/browser-laptop#1261]
I have set the start-with drop down to "show my windows / tabs from last time" in the preference page.
But found that the still browser opens to a blank page after restarting the browser.
Did I miss anything?
Thank you.

**Comment by weems** [comment]
@bbondy I have confirmed that closing Brave 0.8.3 and reopening with show tabs from last time in about:preferences does not preserve the tabs which were previously open prior to reopening. I seem to remember this functioning in 0.8.2, but I am not sure if I am doing something incorrect.

**Comment by bbondy** [comment]
there's another issue like this as well but it's working for me on both OS X and Windows 10.  I suspect maybe I'm doing something different but not sure what.  Maybe a video would help.

**Comment by kwanaa** [comment]
It works.
I made a mistake that I opened another Brave instance without closing the other one properly.
Thank you.

**Comment by luixxiul** [comment]
Closing for now, related: #854
