### ISSUE TITLE
Rename Brave Laptop to a more appropriate name

### ISSUE THREAD

**Issue by AluminiumTech** [brave/browser-laptop#12615]
### Description
Brave for PCs is branded and marketed as Brave for Laptops despite many individuals using Brave on Desktops.

It's misleading and just frustrating that there is such ignorance for Desktop users. 

You're assuming that everybody uses laptops when a large number of people use desktops. It's just insulting to say the least. 

It would seem more appropriate to call it Brave for PC, Brave for Computers, just "Brave", or Brave for Desktop (as this can refer to both laptops and desktops as it does with Windows).

Or any name really that doesn't imply that it's just for laptops.

Firefox, Chrome, Vivaldi and others either add the suffix of "Desktop" or just simply state their name and add a suffix to describe what mobile platform they are for on mobile devices with the desktop version having no suffix.

### Steps to Reproduce
  1. Go To Brave.com

**Actual result:**
* Brave referenced as "Brave for Laptops"

**Expected result:**
* Brave referenced as "Brave for PC" or any other more appropriate name.

**Reproduces how often:**
Every time.

### Brave Version
0.19.131

**Reproducible on current live release:**
Yes, name is the same.

**Comment by Jacalz** [comment]
Don’tget me wrong here, I have nothing against the name but I do see that it can cause some confusion. If it was to change I would rename it to “browser-x86” because it works only on x86 operating systems. The it could say: “Brave for x86 architecture operating systems”

**Comment by AluminiumTech** [comment]
>> Don’t get me wrong here, I have nothing against the name but I do see that it can cause some confusion. If it was to change I would rename it to “browser-x86” because it works only on x86 operating systems. Then it could say: “Brave for x86 architecture operating systems”


But that in itself would also be misleading since Windows and Linux can run on ARM chips as well.

**Comment by jernejml** [comment]
@AluminiumTech 
I am using laptop as a transferable workstation on a docking station connected to large monitor. :)
I would prefer name "Brave Desktop" over using outdated term such as PC.

**Comment by Liunkae** [comment]
+1 to "Brave Desktop". "Desktop" is widely used with desktop vs. mobile comparisons, like http://gs.statcounter.com/platform-market-share/desktop-mobile-tablet

**Comment by davidtemkin** [comment]
There's no perfect answer here, but, per @Liunkae and @AluminiumTech,  "desktop" is the conventional term used to describe the PC platform in a general sense (including laptops and Mac -- "PC" doesn't quite cover it). The browser is named "Brave" and "Brave" alone; but there are times when we need to refer specifically to the version that runs on Win/Mac/Linux. In those cases we describe the product as "Brave for desktop" or "Brave desktop browser" (see Brave.com -- it doesn't say "laptop"). That's also the term we use when describing those versions of the product in most public venues. Yes, the name of the repository is "browser-laptop". But in the end, we are talking about the name of the repository, not the name of the product. I think we can live with the divergence.

**Comment by bsclifton** [comment]
+1 on what @davidtemkin said above 😄 

I think it's important we prefer "Desktop" over "Laptop" when referring to the product (which we seem to, from my experience). On GitHub... even though the repo is named "browser-laptop", the description for this repo does make it clear it's for desktop:
> Brave browser for Desktop and Laptop computers running Windows, OSX, and Linux

Please let us know if there are places we refer to the product as a "Laptop" product 😄

**Comment by Liunkae** [comment]
Just for the record, the repository for the new Chromium based version of Brave is called "brave-browser": https://github.com/brave/brave-browser
