### ISSUE TITLE
Unable to move Bookmarks into "Other Bookmarks" also Other Bookmarks not showing in Menu

### ISSUE THREAD

**Issue by TLHN** [brave/browser-laptop#12610]
Hi,

as stated above it is not possible to move anything into other Bookmarks via the Bookmarks Manager. It always ends up in the Bookmarks Bar and messes up pretty much everything.

Also the extensions ads are disgusting.

**Comment by NejcZdovc** [comment]
Hi, thank you for your report. Everything related to the other bookmarks folder will be fixed in 0.20.x.

One of the related issues #10157
