### ISSUE TITLE
[Security] DNS rebinding attack against webtorrent

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12616]
our webtorrent integration may be vulnerable to the DNS rebinding attack described in https://github.com/transmission/transmission/pull/468. the torrent server uses CORS but it doesn't check the Host header. 

impact: remote sites may see what a user is torrenting

**Comment by diracdeltas** [comment]
this does affect webtorrent but the impact is relatively low - the attacker can see the torrented files. however this is usually possible for torrents anyway (unless you're using a private tracker) since the attacker can just join the swarm.

**Comment by diracdeltas** [comment]
general issue: https://github.com/brave/browser-laptop/issues/12671

**Comment by bsclifton** [comment]
Still waiting on merge upstream... moving to tentative 0.20.x hotfix 1 milestone

**Comment by diracdeltas** [comment]
upstream webtorrent fix has been merged, we need to add an option to webtorrent-remote though: https://github.com/dcposch/webtorrent-remote/issues/9.

**Comment by feross** [comment]
I think the `hostname` option can be specified by the `webtorrent-remote` user and it will be passed through to webtorrent.

You can see how `opts` from `torrent.createServer(opts)` gets passed through in this commit where it was added: https://github.com/dcposch/webtorrent-remote/commit/5b0cec4c0f6672498cd987261324a8eb08482d26
