### ISSUE TITLE
Disable auto-include publisher causes existing publishers to be excluded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12621]
### Description
Disable auto-include publisher causes existing publishers to be excluded

### Steps to Reproduce
  1. Clean install 0.19.133
  2. Enable payments, visit some publishers to add entry in ledger table 
  3. Disable `auto-include`, visit a new site, all entries gets disabled

**Actual result:**
On 0.19.133
![ledgeryt](https://user-images.githubusercontent.com/17010094/34864081-94b22b82-f798-11e7-88ac-89a7cbb35f8c.gif)
On 0.19.131
![ledgeryt-131](https://user-images.githubusercontent.com/17010094/34864182-049c92c0-f799-11e7-9902-13ba09535c38.gif)

**Expected result:**
Should not exclude all existing publishers form the table

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.131 | 0.19.133
-- | -- | --
rev | da2f347 | e05a8ef
Muon | 4.5.36| 4.5.38
libchromiumcontent | 63.0.3239.132 | 63.0.3239.132
V8 | 6.3.292.49| 6.3.292.49
Node.js | 7.9.0 | 7.9.0
Update Channel | Release | Release
OS Platform | Microsoft Windows | Microsoft Windows
OS Release | 10.0.16299 | 10.0.16299
OS Architecture | x64 | x64

**Reproducible on current live release:**
No

### Additional Information
Same behaviour on 0.20.x as well
cc: @NejcZdovc @bridiver @bsclifton

**Comment by NejcZdovc** [comment]
This regressed with muon upgrade from .36 to .38

**Comment by srirambv** [comment]
Same issue on Linux as well
![ledger-linux](https://user-images.githubusercontent.com/17010094/34867389-f21b4044-f7a5-11e7-9be6-ac9c8633b6b5.gif)

But with a different(new) profile it wasn't reproduced. Although it did have other publishers listed
![image](https://user-images.githubusercontent.com/17010094/34867448-26875a7a-f7a6-11e7-8062-53159b811a18.png)

**Comment by NejcZdovc** [comment]
ok this is not a new thing it's just timing thing

**Comment by NejcZdovc** [comment]
I still thing that we need to fix it soon, could be quite a problem, so I will add it into 0.20.x

**Comment by LaurenWags** [comment]
Reproduced on MacOS with 0.19.133
