### ISSUE TITLE
Save Page as dialog broken on macOS

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#12628]
### Description
When trying to save a page on macOS, the save as dialog box does not expand properly.

### Steps to Reproduce
  1. Open Brave and navigate to any webpage.
  2. Select File > Save Page as
  3. Press the expansion arrow button: 
![](https://user-images.githubusercontent.com/19424103/34892048-65136a80-f79d-11e7-8df3-ed3574ddefde.png)

**Actual result:**
The dialog box is not expanded properly. See the screen recording below:
![](https://user-images.githubusercontent.com/19424103/34892227-132b3058-f79e-11e7-8248-59d2d9ed63eb.gif)

**Expected result:**
The dialog box should be expanded properly.

**Reproduces how often:**
Always.

### Brave Version

**about:brave info:**
Brave: 0.19.131 
rev: da2f34787e51eb44190a7a77249e100fb2368306 
Muon: 4.5.36 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes, 0.19.131

### Additional Information
Related: #10924

**Comment by Liunkae** [comment]
May be fixed by #11906 in 0.21.0, but I have not tested yet.

**Comment by humphd** [comment]
I'm not able to reproduce this on master (9c4159a36) on macOS 10.13.3.

**Comment by Liunkae** [comment]
@bsclifton Could we include this in the 0.21.x milestone? Thanks.

**Comment by bsclifton** [comment]
@Liunkae done- thanks for calling this out 😄 (fixed by @darkdh)

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
