### ISSUE TITLE
Context searches in private tabs uses default search engine instead of DuckDuckGo

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#12639]
### Description
Reported on community https://community.brave.com/t/context-searches-in-private-tabs-use-default-search-engine-when-set-to-use-duckduckgo/13682?u=eljuno

When setting private tabs to use DuckDuckGo for searches, the right click menu search continues to use your default search engine.

### Steps to Reproduce

  1. Set Google for default search engine
  2. Open a private tab.
  3. Turn on the “Private search with DuckDuckGo” toggle.
  4. In private tab, open any site.
  5. Highlight any text, right click to open the context menu and search for text.

**Actual result:**
The search page opened uses the default search engine set in the user settings.
![search-context-menu](https://user-images.githubusercontent.com/25360853/34910747-6151c9c6-f8ee-11e7-9601-f5ff116cb7e0.gif)

**Expected result:**
Use DuckDuckGo instead of default search engine.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.19.134
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691
Muon: 4.5.38
libchromiumcontent: 63.0.3239.132
V8: 6.3.292.49
Node.js: 7.9.0
Update Channel: Release
OS Platform: Microsoft Windows
OS Release: 10.0.16299
OS Architecture: x64

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@petemill can you check this out? 😄

**Comment by eljuno** [comment]
@arsalankhalid It's different things. That is to set DDG as default search engine for private tab. This issue is about Brave use default search engine (if it's not DDG) when right-click search in private tab even already set DDG as search engine for private tab.

**Comment by bsclifton** [comment]
@arsalankhalid as @eljuno said, this is basically a spot we missed. If you use right click -> search (from the context menu), it's not respecting the preference 😄

**Comment by LaurenWags** [comment]
Reproduces in 0.23.8 with Tor enabled on Private Tabs.

**Comment by eljuno** [comment]
Closing this in favor of #14530? :smile:

**Comment by bsclifton** [comment]
@eljuno that is a different case (specifically "paste + search" context menu in the URL bar)

However, this issue may be fixed with https://github.com/brave/browser-laptop/pull/12613

**Comment by eljuno** [comment]
Not able to reproduce on latest version 0.23.19. Both for Private tab and Private tab with Tor. Still believe it's fixed with 14530. :D 

STR:
- Set Google for default search engine
- Set DDG as default search engine for private tab/private tab with tor
- Open private tab/private tab with tor
- Open any site
- Highlight any text, right click to open the context menu and search for text.

![private-context-search](https://user-images.githubusercontent.com/25360853/42062615-4b830992-7b58-11e8-960d-901cddfd58c1.gif)

**Comment by bsclifton** [comment]
@eljuno great find- this is indeed fixed 😄👍 I believe it was fixed with https://github.com/brave/browser-laptop/pull/14531
