### ISSUE TITLE
Inspect element sometimes selects <html> element instead of the selected element.

### ISSUE THREAD

**Issue by Sileax** [brave/browser-laptop#1263]
Hi, i've downloaded brave from the AUR on manjaro, the browser is great (Maybe the lack of extensions may be annoying but nevermind it's not the subject)

I've caught a problem, i'm a web developper so, I use the Inspect Element and the console many times, but the problem is, when we clic on an element either it doesn't go to the good line (I click on an input text and it goes to a video tag, either it goes to the html tag so the beginning of the document and it's pretty annoying to develop and debug...

Anyway thank's for your great job on this browser and hope this little bug will be fixed soon (And I hope this ticket isn't a duplicate neither :D) 

Sorry if i've made some grammar faults i'm French and English isn't my native language ^^

**Comment by bbondy** [comment]
I've noticed this too, it sometimes works and sometimes selects the top level html element.

**Comment by Sileax** [comment]
On a local html file the inspection has never worked, on websites it sometimes work, and when the console is already open, click again on inspect element don't put it in front of the browser, it reload well but stay in the background.
