### ISSUE TITLE
tabs resize down when they don't have to

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12634]
### Description
Tabs seem to resize down when they don't need to.

### Steps to Reproduce

  1. I have my tabs per tab set = 20
  2. Open enough tabs so there's a noticeable difference in tab size (I had 13)
  3. Start closing tabs with the X, close about half the tabs
  4. Move your mouse out of the tab bar area, tabs resize appropriately to fill the tab bar.
  5. Close a tab with X again.
  6. Tabs resize down to the size they were in step 2.
  7. Move mouse from tab bar area, tabs resize appropriately again.
  8. Repeat step 5, notice resize down again

**Actual result:**
Tabs resize down:
![tab-resize-02016](https://user-images.githubusercontent.com/28145373/34902202-a07a48b8-f7e4-11e7-8d20-a81a7e6eb30b.gif)

**Expected result:**
Tabs to maintain size or maybe expand slightly (depending on window size, tabs per tab set, etc)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.16
V8 | 6.3.292.49
rev | 0c42d0b
Muon | 4.5.36

**Reproducible on current live release:**
Yes, reproduces on 0.19.134 

### Additional Information
Happens on current release but seems more obvious/jarring on 0.20.16

**Comment by bsclifton** [comment]
Confirmed this is fixed (tested on macOS, version 0.23.79) 😄
