### ISSUE TITLE
Multiple Tabs Don't Open or Close As Intended.

### ISSUE THREAD

**Issue by stephenkru** [brave/browser-laptop#12637]
Opening multiple bookmarks through middle mouse button click or right click 'open all tabs' does not open them in the hierarchical order you have them arranged in your bookmarks folder/bar.

When closing the tabs with OPTIONS 'Settings>Tabs>When closing an active tab: 'Select the next tab' a middle click to close the tab or clicking the X button in a tab will selection will skip over a tab. 

IE: If tabs are open in this Order:
(Tab 5 [x])(Tab 4 [x])(Tab 3 [x])(Tab 2 [x])(Tab 1 [x])

Middle Click close, or clicking the X on Tab 5 will select Tab 3 instead of Tab 4. Etc... while 'Right Click>Close'  works as intended.

![tabs](https://user-images.githubusercontent.com/23619351/34909691-84b95efc-f86b-11e7-8b90-b57909f8ae64.gif)

### Brave Version

Please open about:brave, copy the version information, and paste it.

Name | Version
-- | --
Brave | 0.19.134
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Comment by bsclifton** [comment]
Confirmed this is fixed with [brave-core](https://github.com/brave/brave-browser)! Closing as `wontfix` for this repo (our Muon based product)
