### ISSUE TITLE
Brave not installable from repo on Debian Buster

### ISSUE THREAD

**Issue by ruxandra-valcu** [brave/browser-laptop#12636]
### Description

Brave fails to install from repo on Debian Buster using the apt and lsb_release method described on https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-zesty-yakkety-xenial-and-trusty-amd64 because the repo is not signed

### Steps to Reproduce

  1. curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -

  2.echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list

  3. sudo apt-get update

**Actual result:**
Err:13 https://s3-us-west-2.amazonaws.com/brave-apt buster InRelease                                          
  403  Forbidden [IP: 52.218.128.116 443]
Reading package lists... Done                       
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/buster/InRelease  403  Forbidden [IP: 52.218.128.116 443]
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Expected result:**
Have apt-get update

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by DestinFaroda** [comment]
I too use Buster and I get the same error.
While checking apt-key list, I didn't notice anything weird.
I'd rather have Brave on my system than Firefox, as my internet speed is slow (typical for Germany) and Brave really speeds things up.

**Comment by VaclavSynacek** [comment]
I also get the same error
```
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/buster/InRelease  403  Forbidden [IP: 52.218.201.216 443]
```
When using browser, the same URL returns 403 with the following headers:
```
x-amz-request-id: 2861AF1FA39E52C1
x-amz-id-2: g3qZYwNrhdFAqIlk8uW0D+wheVDvMjcyY5yDhH6v+DQkHBgSRQSRRYyFsFaPCG+z5NqzMp0P3/A=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Sat, 10 Feb 2018 14:09:32 GMT
Server: AmazonS3
```
and content:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2861AF1FA39E52C1</RequestId><HostId>g3qZYwNrhdFAqIlk8uW0D+wheVDvMjcyY5yDhH6v+DQkHBgSRQSRRYyFsFaPCG+z5NqzMp0P3/A=</HostId></Error>
```

I assume this means brave's AWS-S3 is misconfigured and this prevents any apt based installation on debian based systems. Unfortunately the same is true for brave-beta on brave-apt-staging.

**Comment by sepastian** [comment]
I'm experiencing the same problem.

Any progress on this? Can't install brave in Debian.

**Comment by miltonhowe** [comment]
same here using PureOS green.

**Comment by malachid** [comment]
Same with Ubuntu 18.04

**Comment by nikolas** [comment]
I'm getting this problem on Debian buster.

```
~ $ curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1828  100  1828    0     0   1740      0  0:00:01  0:00:01 --:--:--  1742
OK
(nik@acid) :) (22:05)
~ $ echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list
deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt buster main
(nik@acid) :) (22:05)
~ $ grep lsb_release /etc/apt/sources.list.d/brave*
(nik@acid) :( 1 (22:05)
~ $ sudo apt update
Hit:1 http://ftp.us.debian.org/debian buster InRelease
Hit:2 https://cli-assets.heroku.com/branches/stable/apt ./ InRelease                                   
Hit:3 http://security.debian.org/debian-security buster/updates InRelease                              
Hit:4 https://deb.nodesource.com/node_9.x buster InRelease                                             
Err:5 https://s3-us-west-2.amazonaws.com/brave-apt buster InRelease                                    
  403  Forbidden [IP: 52.218.196.112 443]
Reading package lists... Done
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/buster/InRelease  403  Forbidden [IP: 52.218.196.112 443]
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by rook2pawn** [comment]
I have debian buster as well. This is how I fixed it

Edit your file  `/etc/apt/sources.list.d/brave-buster.list`

and change

    deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt buster main

to 

    deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt stretch main


Since `stretch` is the closest release to `buster`. I verified that Brave works just fine after doing this.
Of course, do `apt-get update` and `apt-get install brave`.

**Comment by nikolas** [comment]
@rook2pawn thanks. I just switched `buster` to `stretch` and that worked on my system.

**Comment by cblancos** [comment]
This worked for me, thanks

**Comment by DestinFaroda** [comment]
The snapcraft version too works quite well.

**Comment by bsclifton** [comment]
@ruxandra-valcu @DestinFaroda @cblancos @nikolas @rook2pawn @malachid @miltonhowe @VaclavSynacek I've updated our release script to include `buster` and re-pushed. Can you please try again? Should work great without changing your apt sources list 😄

Ubuntu 18 (bionic) was also updated recently too- should work great 👍

**Comment by VaclavSynacek** [comment]
Works on Debian buster now. Thanks.

**Comment by peculiarity** [comment]
@rook2pawn Thanks for the tip! :) That works fine with Horizon as well!
