### ISSUE TITLE
Brave vs chrome

### ISSUE THREAD

**Issue by Vispocks** [brave/browser-laptop#12642]
Hi,

I tested Brave on GNU/Linux and comparing with chrome.

The result:
abcnews.com  
cbsnews.com 
cnn.com 
foxnews.com 
huffingtonpost.com 
latimes.com 
msnbc.com 
time.com 

chrome is faster with 1-3 sec in each site

even chrome has these extensions:
ScriptSafe
Ghostery
HTTPS Everywhere
AdBlock
and Plus 5 more!

**Comment by NumDeP** [comment]
Considering your statement, their landing page could be construed as misleading for the time being as it needs to re-evaluate how it's engine is still better and why.   

@Vispocks when I first installed Brave close to a year ago I can still remember being in slight awe of how efficient it was compared to Firefox (with the older Gecko engine not the new Quantum) and Chrome and it has without a doubt been steadily decreasing in terms of efficiency in the ad-blocking side of things as well as the browser startup in general. So I think it's widely understood, at least by those that have been using it probably primarily as a secondary browser that this is obviously a concern which has already been acquiesced but just hasn't been attended to, to fix the other necessities of the browser.

However, I do agree with you, Firefox Quantum with uBlock Origin (with Fanboys toggled in preferences) Flipping heck!

**Comment by davidtemkin** [comment]
@Vispocks On Brave.com, the comparison between Brave and Chrome uses each browser as it is provided by Brave and Google, respectively, with default settings and no user-installed extensions. @NumDeP It is not a comparison of rendering technologies, but of end-user results with common sites using out-of-the-box configurations. In fact, Brave is based on the same core rendering engine as Chrome.
