### ISSUE TITLE
Cargocollective.com does not fully load due to HTTPS Everywhere rule

### ISSUE THREAD

**Issue by midi** [brave/browser-laptop#1264]
The partial rule is active by default. De-activating HTTPS Everywhere for the site fixes it.

I don't use HTTPS Everywhere because of situations like this, random sites not working.
I think it would maybe a bit much for the average user to learn and remember to try disabling ad-blocking AND HTTPS Everywhere, should a site not load.

**Comment by diracdeltas** [comment]
I will do a https-e update today that disables this rule.
