### ISSUE TITLE
Website (linkedin.com) keeps reloading constantly

### ISSUE THREAD

**Issue by Dakicka** [brave/browser-laptop#12645]
Have you searched for similar issues?
Yes, seems to be the same symptoms as in #7214 but the solution does not work

### Description

After I imported my firefox bookmarks and went though the preferences page, the website https://linkedin.com keeps reloading constantly. After the page is loaded (which is impressively fast) it immediately loads again and again and again.... I already changed the settings back that I changed in the preferences but without success. The fingerprinting protection was never enabled.

### Steps to Reproduce

I just have to open the LinkedIn website. Haven't had that issue on other websites thus far. I don't know how to reproduce it on a fresh install, probably by importing 

**Actual result:**

Pages keeps reloading

**Expected result:**
Page should just load once

**Reproduces how often:**

100% of the times

### Brave Version

**about:brave info:**

Name | Version
Brave | 0.19.134
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**

Yes

**Comment by bsclifton** [comment]
@Dakicka do you have more information about your setup?

For example, linkedin.com works fine for me with these settings (clicked the lion icon in the top right)
![screen shot 2018-01-14 at 6 16 36 pm](https://user-images.githubusercontent.com/4733304/34923217-2b53623a-f957-11e7-8754-50fc2d5ac592.png)

**Comment by Dakicka** [comment]
@bsclifton thanks. Yes, it counts up to 10 right before the reload of the page. 
![2018-01-15 08_42_03-](https://user-images.githubusercontent.com/16510737/34931665-28a5d472-f9d0-11e7-904a-ccbe07c53ccb.png)

The issue still exists if I deactivate shields for LinkedIn completely (flip the switch in the top right corner).

**Comment by Dakicka** [comment]
Hi, I reinstalled Brave, following this guide https://community.brave.com/t/how-to-solve-almost-every-problem-after-install/605 and it solved the problem. Sorry we couldn't find the root cause. Thanks for your help though.

**Comment by bsclifton** [comment]
Glad you were able to solve it (and apologies that you ran into it!).  Thanks for updating this issue with your solution.  I'll close it out for now 😄
