### ISSUE TITLE
Lost Characters in "My Home Page Is" Input Field

### ISSUE THREAD

**Issue by hyph3n** [brave/browser-laptop#12647]
### Description

When typing quickly into the "My home page is" input field, individual characters are sometimes lost in no obvious pattern; they sometimes appear on screen very briefly and then disappear, leaving typos in the input text.  If the user types more slowly, characters do not seem to disappear.

### Steps to Reproduce

  1. Preferences > General > My home page is
  2. Press the 'a' key five times in quick succession.
  3. Observe that the input field has only four letters in it.

**Actual result:**

![peek 2018-01-14 13-03](https://user-images.githubusercontent.com/5378617/34919048-c478399e-f92b-11e7-8135-7627b446155a.gif)

After the first two letters appear, notice the hesitation, and slower appearance of the last two letters. It's during that initial pause that a typed letter is lost. NOTE: When watching the screen as I type, the lost letter sometimes appears for a split second, but I can't seem to capture this in the gif.

**Expected result:**

![peek 2018-01-14 12-59](https://user-images.githubusercontent.com/5378617/34919004-e19f5d1e-f92a-11e7-9a08-9ca6538e8507.gif)

Five key presses should result in five characters in the input field.

**Reproduces how often:**

This occurs nearly every time I try to reproduce it, though occasionally I see the expected result above. Typing more slowly seems to always work as expected.

### Brave Version

**about:brave info:**

Brave | 0.22.0
-- | --
V8 | 6.3.292.48
rev | 1e43f3d
Muon | 4.6.4
OS Release | 4.14.11-200.fc26.x86_64
Update Channel |  
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 63.0.3239.108

Name | Version
-- | --
Brave | 0.19.134
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.14.11-200.fc26.x86_64
OS Architecture | x64

**Reproducible on current live release:**

So far I've reproduced the problem on Brave 0.22.0 (from Github) and on Brave 0.19.0 (installed from repository).

**Comment by bsclifton** [comment]
@hyph3n does this still happen for you?

**Comment by hyph3n** [comment]
Yes, still able to reproduce on:

Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 4.15.14-300.fc27.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
