### ISSUE TITLE
Add option in about:preferences#extensions to only show open source extensions

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#12644]
### Description 
Add an option in about:preferences#extensions for only showing extensions where the code base is open source. This would be great to hide proprietary extensions from users only wanting open source extensions. brave is open source and thus should help to show what extension that are open source or not 👍

**Comment by bsclifton** [comment]
The biggest challenge for this would be knowing if an extension is open source or not (and if so, where the code is).  If you look at the Chrome web store, I don't think this data is being stored anywhere:
https://chrome.google.com/webstore/category/extensions

Somebody would need to compile a list of this and keep it up to date (which I don't think is feasible).

I'm going to close this as `wontfix`, but I encourage folks to re-open if there is a realistic way to implement this
