### ISSUE TITLE
Autofill dropdown is not shown below the input field

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12652]
### Description
Autofill dropdown is not shown below the input area

### Steps to Reproduce
  1. Have autofill data saved in `about:autofill`
  2. Visit https://www.roboform.com/filling-test-all-fields 
  3. Click on First name, autofill data is not shown below the clicked field

**Actual result:**
0.19.134 vs 0.19.135
![autofill](https://user-images.githubusercontent.com/17010094/34929284-e2d847c2-f9e8-11e7-8974-58db0e150490.gif)

**Expected result:**
Autofill suggestion should be shown below the clicked input area

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.135| 0.19.134
-- | -- | --
rev | 1f3af75 | 316cfa5
Muon | 4.7.0 |  4.5.38
libchromiumcontent | 64.0.3282.71 | 63.0.3239.132
V8 | 6.4.388.12 | 6.3.292.49
Node.js | 7.9.0 | 7.9.0
Update Channel | Release | Release
OS Platform | Microsoft Windows | Microsoft Windows
OS Release | 10.0.16299 | 10.0.16299
OS Architecture | x64 | x64

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton @darkdh

**Comment by kjozwiak** [comment]
This is also affecting where saved passwords are being displayed when clicking on input fields. 

Using `0.19.136` 1659471cf1b1016568f63a6ab3e35b604d7e3db3 under macOS 10.13.2

<img width="1387" alt="screen shot 2018-01-15 at 3 04 02 pm" src="https://user-images.githubusercontent.com/2602313/34959636-611b3f7e-fa05-11e7-9cd6-e646f690e715.png">

<img width="917" alt="screen shot 2018-01-15 at 3 07 16 pm" src="https://user-images.githubusercontent.com/2602313/34959735-d0f6e172-fa05-11e7-8a4b-21994e9d6c5e.png">

**Comment by bsclifton** [comment]
Here's an example of the coordinates involved with Chromium 63
![autofill63](https://user-images.githubusercontent.com/4733304/35016341-5bab256a-fad5-11e7-8c14-816b6eaa482a.png)

and with Chromium 64 (same code)
![autofill64](https://user-images.githubusercontent.com/4733304/35016351-62346b76-fad5-11e7-8da3-bfb2ea7dc6bf.png)

**Comment by bsclifton** [comment]
continuing on the above...

With 63 (and existing code), targetRect is added to boundingClientRect (notice the `top` value of 74) because the targetRect is for inside the webview.

With 64, targetRect is using screen coordinates already (instead of being relative to the webview). Therefore, we don't need to add the window chrome size (boundingClientRect) to it

**Comment by bsclifton** [comment]
Fixed in 0.19.x with a7c1cbe6479b9de566cef6d04d6119c91b8986ff
