### ISSUE TITLE
Accidentally swiping back on macOS

### ISSUE THREAD

**Issue by gnapse** [brave/browser-laptop#12658]
As some others have stated in #5907, I find that Brave is too sensitive in detecting the gesture for swiping from right to left in the trackpad to go back in history. I don't want to disable the feature, as I relied on it when I used Chrome. But Brave is too sensitive. Sometimes I make the gesture to scroll up or down, and apparently in my movement in the trackpad, I also did move my fingers to the left slightly while doing the most significant up-or-down movement. Because it's happened to me several times that I go back in history with having had the intent to do so.

**Comment by bsclifton** [comment]
@gnapse I'm happy to report that with our latest release (0.20.30), this feature was finally delivered 😄 

It was originally reported with https://github.com/brave/browser-laptop/issues/9615 and fixed with https://github.com/brave/browser-laptop/pull/9617
