### ISSUE TITLE
Add cc support

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#12653]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
pushing back to 0.22.x

**Comment by bsclifton** [comment]
@NejcZdovc was this intentionally closed?

**Comment by NejcZdovc** [comment]
yes, we will not be implementing this one

**Comment by bsclifton** [comment]
@NejcZdovc OK great- removing milestone 👍

**Comment by empaempa** [comment]
Please re-open this. I want to give you money but the crypto-hurdle is too high - and I even own ETH. Stripe just released a billing service you probably could use:

https://stripe.com/se/billing

**Comment by NejcZdovc** [comment]
@empaempa we are preparing this feature, don't worry we got you 😃

**Comment by empaempa** [comment]
@NejcZdovc Wonderful! Love the browser, keep up the great work!
