### ISSUE TITLE
requestPointerLock not working

### ISSUE THREAD

**Issue by AlbertoElias** [brave/browser-laptop#12668]
### Description
This Web feature doesn't seem to work on Brave

### Steps to Reproduce
Executing `element.requestPointerLock` on any element doesn't do anything and `document.pointerLockElement` is `null`.

**Actual result:**
Mouse is not captured by the element

**Expected result:**
Mouse is captured by the element

**Reproduces how often:**
100%

### Brave Version

Brave | 0.19.134
-- | --
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by petemill** [comment]
Confirmed this is not working with test case at https://mdn.github.io/dom-examples/pointer-lock/

**Comment by AlbertoElias** [comment]
It seems like it's related to this Electron bug: https://github.com/electron/electron/issues/9817
