### ISSUE TITLE
clicking on some notifications will create dead tabs within Brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12663]
### Description

Clicking on some notifications will cause the creation of dead tabs within Brave. These tabs cannot be closed within the same session and requires a restart.

### Steps to Reproduce

  1. visit https://jsfiddle.net/yoshi6jp/Umc9A/
  2. click on `Request Permissions` and select `Allow` & `Remember this decision` when the notification appears
  3. type in "brave" in the `title` input field and "hey hey" in the `body` input field
  4. click on `Show`
  5. double click on the notification that appears in the OS

**Actual result:**

When clicking on some notifications, a new "dead" tab will appear within Brave that cannot be closed until the browser is restarted.

![notificationissue](https://user-images.githubusercontent.com/2602313/34961081-a823b738-fa0b-11e7-973f-2bfcf4c19c93.gif)

**Expected result:**

Dead tabs shouldn't be appearing within Brave when clicking on notifications.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.136 - Reproduced
> rev: 1659471cf1b1016568f63a6ab3e35b604d7e3db3 
> Muon: 4.7.1 
> libchromiumcontent: 64.0.3282.85

> Brave: 0.20.16 - Reproduced
> rev: 0c42d0b7774fe878b482af917f291904dc3e8c45 
> Muon: 4.5.36
> libchromiumcontent: 63.0.3239.132

**Reproducible on current live release:**

Yes, currently reproducible under `0.19.134`:

> Brave: 0.19.134 - Reproduced
> rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
> Muon: 4.5.38 
> libchromiumcontent: 63.0.3239.132

### Additional Information

Adding this into `0.20.x` as it would be nice to fix dead tabs. We've been receiving several complaints from several social media platforms regarding dead tabs being created that cannot be closed unless you restart the browser. If we don't have time to fix this, I'm okay moving it to another milestone.

**Comment by kjozwiak** [comment]
Still reproducible with `0.20.29` rev: 4fc3c8ff3bcb6af75088b125e00d3a70382b9bec  using the above STR on macOS 10.13.2.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/hanging-tabs-don-t-close-o-open-the-page/15415/
