### ISSUE TITLE
Menu Bar Keeps showing up when Browser is reopened

### ISSUE THREAD

**Issue by insanerwayner** [brave/browser-laptop#12665]
### Description
When I open the Browser it shows the menu bar. I have to right click and put the checkmark on to active the menu bar then right click again to to turn it off, then the menu bar disappears.

### Steps to Reproduce

  1. Open the Browser
  2. Menu Bar is visible
  3. Right Click in blank space by tabs and you will see the menu bar is not showing to be actived.
  4. Click the Option for Menu Bar.
  5. Right click the same blank space as before. The Menu Bar is now showing it is active.
  6. Click the menu bar option and the menu bar will disappear.
  7. Close and Reopen the browser and the Menu Bar is back.

**Reproduces how often:**

Every Time

### Brave Version

**about:brave info:**

0.19.134

### Additional Information

Running on Pop!_OS (Basically Ubuntu 17.10)

**Comment by hyph3n** [comment]
I'm seeing the same behavior on 0.22.0.

Brave: 0.22.0 
V8: 6.3.292.48 
rev: 1e43f3df19a687723d7d343b16c34f3cf54e2fe5 
Muon: 4.6.4 
OS Release: 4.14.13-200.fc26.x86_64 
Update Channel:  
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 63.0.3239.108

**Comment by insanerwayner** [comment]
It also did it with the snap version of Brave

**Comment by bsclifton** [comment]
Hi folks- thanks for the report 😄  This is a known issue on Linux; we have it captured with https://github.com/brave/browser-laptop/issues/5086 if you wanted to follow for updates.  I'll close this issue as a duplicate
