### ISSUE TITLE
Add the ability to customize shortcuts

### ISSUE THREAD

**Issue by nlhnt** [brave/browser-laptop#1266]
Hello, 
cannot find any "about" page or menu to edit my shortcuts - these are starting to annoy me whenever i push "alt + s" i get a new tab. 
Also I cannot find the history tab - is this still to be added?

**Comment by bbondy** [comment]
We don't have history yet, it is tracked here: https://github.com/brave/browser-laptop/issues/444
But I renamed the title here for the ability to customize shortcuts.

**Comment by luixxiul** [comment]
Closing this in favor of #1089
