### ISSUE TITLE
Throttle loads/requests for background tabs

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12669]

**Comment by luixxiul** [comment]
Would https://github.com/brave/browser-laptop/pull/11968 not cover the issue?

**Comment by bsclifton** [comment]
@luixxiul this is a little different- it requires a Muon change. @bridiver is checking this out

**Comment by bsclifton** [comment]
Pushing back to 0.21.x

**Comment by bsclifton** [comment]
Pushing back to 0.22.x
cc: @bridiver
