### ISSUE TITLE
New issues needp help

### ISSUE THREAD

**Issue by mortellus** [brave/browser-laptop#12662]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by kjozwiak** [comment]
Closing as there's no information here. @mortellus, if you're still having issues, please create a new bug with more information. You could also checkout the Brave Community https://community.brave.com/
