### ISSUE TITLE
Incorrect decimal values shown for BAT-USD after reconcile

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12666]
### Description
Incorrect decimal values shown for BAT-USD after reconcile

### Test plan / Steps to Reproduce
  1. Fund wallet with decimal values such as 7.51 BAT
  2. Change reconcilestamp to trigger payment process
  3. Once reconcile is complete, shows incorrect decimal values for BAT-USD

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/34976441-aa9f5dd0-fabc-11e7-858e-9b46c4b64ad6.png)

**Expected result:**
Should show correct BAT-USD values even for decimal values

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.136
-- | --
rev | 1659471
Muon | 4.7.1
libchromiumcontent | 64.0.3282.85
V8 | 6.4.388.20
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
Found the scenario on staging wallet.
[browser profile]( https://drive.google.com/file/d/15Wvg8TvG8Dy0PUuZ6HgUQIgoDKVgYeBD/view?usp=sharing)
cc: @mrose17 @evq @bsclifton

**Comment by NejcZdovc** [comment]
@bradleyrichter what should we display here? USD value is `0.0066051665` and we only show two places and because of rounding we are currently displaying `0.01 USD` which is of course wrong

**Comment by NejcZdovc** [comment]
This line is problematic https://github.com/brave/browser-laptop/blob/master/app/browser/api/ledger.js#L1614

**Comment by mrose17** [comment]
how about `<.01USD` ?

**Comment by bradleyrichter** [comment]
This should work!

**Comment by LaurenWags** [comment]
Showing <.01 USD on MacOS:
![screen shot 2018-02-23 at 2 50 46 pm](https://user-images.githubusercontent.com/28145373/36613952-ffacd26c-18a8-11e8-99d2-565f144fc90f.png)

**Comment by bradleyrichter** [comment]
@NejcZdovc I think it would look better to add a leading 0. 

So, 0.01 BAT (< 0.01 USD)

**Comment by LaurenWags** [comment]
And a space between the < and the leading zero as in your example @bradleyrichter ? Meaning:
0.01 BAT (< 0.01 USD) vs 0.01 BAT (<0.01 USD)

**Comment by NejcZdovc** [comment]
Reopening, so that we can adjust this value

**Comment by srirambv** [comment]
Looks good on Windows
![image](https://user-images.githubusercontent.com/17010094/36727831-b4c38f2c-1be4-11e8-9e24-14b9c1a0dbbe.png)

**Comment by LaurenWags** [comment]
MacOS:
![screen shot 2018-02-27 at 11 07 17 am](https://user-images.githubusercontent.com/28145373/36739631-674f16b6-1bae-11e8-8e55-da373be7f783.png)

**Comment by kjozwiak** [comment]
Looks good under Ubuntu 17.10 x64 👍 Used `0.21.16` a7bed47f55863b9f48e5ce31bcaf8c6ee21c10d5 without any issues.

<img width="843" alt="screen shot 2018-02-27 at 9 26 31 pm" src="https://user-images.githubusercontent.com/2602313/36766681-efe9c060-1c04-11e8-8688-c387c998c4b9.png">
