### ISSUE TITLE
Ledger USD conversion values not updating via server

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12674]
Noticed that the budget values were not updating.

Name | Version
-- | --
Brave | 0.19.134
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | macOS
OS Release | 17.3.0
OS Architecture | x64

{"altcurrency":"BAT","probi":"138068757400864961624","balance":"138.0688","unconfirmed":"0.0000","rates":{"BTC":"0.00004166","ETH":0.0005248047649144608,"LTC":0.002877533039647577,"USD":0.6390408570000001,"EUR":0.521047075081806}}

**Comment by NejcZdovc** [comment]
closing this one as this was not noticed anymore. Let's reopen if we see it again
