### ISSUE TITLE
GPS Notifications -- Allow or Deny Sites which Use GPS Location Tracking

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1267]
Users should be able Allow or Deny a Website The Ability to Track you using GPS Tracking. 

Ex: This can be easily demonstrated by using [Webkay](http://webkay.robinlinus.com/): "Webkay uses the Google Geolocation API to locate you. This is an educated guess and never as accurate as a GPS Location. The accuracy depends on your location and also on your connection type. If you are on a mobile network expect an error of up to 50km.
This example just tries to demonstrate how accurate a website can guess your location without asking you for permission to access your GPS."

**Comment by diracdeltas** [comment]
If I understand correctly, the only possible mitigation is to fake your IP address. So it's not addressable by us except with #1111.

**Comment by weems** [comment]
Perhaps the mitigation I have in mind is for another GPS issue, but when a site requests location, Chrome alerts the user to that request and allows the user to allow or refuse that request.

**Comment by diracdeltas** [comment]
We do alert you when there is a location request on https://permission.site/. Are you not seeing a permission request prompt?

**Comment by weems** [comment]
I do not see this on sites which definitely use Location. Like https://maps.google.com loads with my location without a Notification. If I zoom to another location and then click the crosshair button to return to my current location in the lower right hand corner, then I get a notification but not on the initial load of the page. Perhaps this is site specific depending on frameworks / tags used on the page.

**Comment by diracdeltas** [comment]
Those sites might be using your IP and/or google's geolocation service, which (as mentioned above) can't be avoided except via a proxy server. But do you see a permission request on sites like http://html5demos.com/geo ?

If not that's a bug.

**Comment by weems** [comment]
No, definitely can see the notification at that demo site. I guess it's not possible to mitigate with IP based / geo API.
