### ISSUE TITLE
Add WebAuthn support

### ISSUE THREAD

**Issue by herrjemand** [brave/browser-laptop#12670]
### Description

So there is a new W3C standard that is called WebAuthn. It's public key credential management API extension for challenge-response authentication. 

https://w3c.github.io/webauthn/

Firefox, Chrome and Edge announced that they will implement it.

Would be nice to see it in brave. And it's not really hard, as it goes through the same interface as U2F

**Comment by bsclifton** [comment]
Closing as `wontfix` since this will be addressed with [Brave Core](https://github.com/brave/brave-browser)
