### ISSUE TITLE
Browser should poll server for UGP promo whenever payments prefs is opened

### ISSUE THREAD

**Issue by davidtemkin** [brave/browser-laptop#12688]
Currently Brave only checks to see if a UGP promotion is active at browser startup time and at 24 hour intervals. The effect of this is that users who hear about a newly-launched promo are not able to take advantage of it without one of a few unappealing actions (wait 24 hours; turn payments on/off; restart the browser). 

In order to satisfy users who have just heard about a new UGP promo (e.g. via an announcement, press, social media) and want to immediately accept the token grant, the browser should poll the server to see if a promo is active whenever a user opens payments preferences.

**Comment by kjozwiak** [comment]
Is this urgent enough to push into https://github.com/brave/browser-laptop/milestone/98?

**Comment by davidtemkin** [comment]
No, I don't think so. For the current promo, it wouldn't help, because more than 24 hours will have passed since the promo went live (i.e., all browsers will poll the server) before any update is released.

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.
