### ISSUE TITLE
Ship hard-coded search engine favicons

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12689]
Per @Liunkae's comment on #12632, we automatically try to fetch favicons for search engines shipped in <about:preferences#search>. We shouldn't make any non-user-initiated requests to those sites. I'd like to shipped cached favicons for those sites, and have the search UI only read out of the favicon cache. That way, we can always show icons shown in the search pane, they'll always be as current as our latest release. If a user regularly visits a site and that site updates their icon, the user will see a newer icon in the search pane based on the timing of their recent visits.

**Comment by flamsmark** [comment]
We'll need the favicon cache from #2697 to update them based on user activity. Until that's available, I'd prefer to ship hardcoded icons for these sites to avoid making non-user-initiated requests.

**Comment by diracdeltas** [comment]
related to https://github.com/brave/browser-laptop/issues/11108

**Comment by diracdeltas** [comment]
shipping hardcoded icons is easy. i think we will probably do that first and have a follow up issue for cache invalidation

**Comment by diracdeltas** [comment]
@flamsmark unless i'm misunderstanding, let's use https://github.com/brave/browser-laptop/issues/2697 for the caching issue and use this issue for hard-coding favicons in the browser

**Comment by diracdeltas** [comment]
Going to mark for 0.20.x since it is an easy privacy win and relatively low-risk code change
