### ISSUE TITLE
Show Definition (Look Up) popup sometimes selects the wrong text

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12695]
### Description
Sometimes when you highlight text and select 'Look Up' from context menu the text that is looked up (highlighted in yellow) is different then what you had selected. 

### Steps to Reproduce

  1. Highlight text
  2. Right click and select 'Look Up'
  3. 

**Actual result:**
Popup is displayed, sometimes the yellow text is not what you had selected (may have to repeat steps 1 and 2 several times to get this to happen):
![8554](https://user-images.githubusercontent.com/28145373/35071812-1872567a-fbb0-11e7-9e61-91c28075adf7.gif)

**Expected result:**
Text you select (right click on) should be what is looked up.

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
Brave | 0.19.137
rev | d72f7a3
Muon | 4.7.2
libchromiumcontent | 64.0.3282.85

**Reproducible on current live release:**
Yes (0.19.134):
![screen shot 2018-01-17 at 6 03 05 pm](https://user-images.githubusercontent.com/28145373/35071965-b6c9cdda-fbb0-11e7-8105-44adf5bf9c6c.png)

**Comment by bsclifton** [comment]
Doesn't seem to be a problem when you double click the words (to cause selection), only when dragged
