### ISSUE TITLE
Geolocation does not prompt for permission (and fails) on some pages

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12692]
See https://github.com/brave/browser-laptop/issues/12651#issuecomment-358250087 for more infomation

> Still broken on https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation  but works https://browserleaks.com/geo
![geo1](https://user-images.githubusercontent.com/17010094/35034832-78eab2d8-fb95-11e7-8e52-cd3ab16e6b28.gif)

> Opening the codepen/jsfiddle  link from https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation shows the location but not the Mozilla link 

> Same behaviour on Windows and Linux as mentioned in the previous comment

**Comment by bsclifton** [comment]
When opening the console, you'll see the following:
![image](https://user-images.githubusercontent.com/4733304/35072310-4286bae6-fba1-11e7-9ec6-6ccc0530b3bf.png)

This is working as expected due to deprecation of permissions:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

**Comment by kjozwiak** [comment]
As mentioned above by @bsclifton, due to chromium deprecating geolocation permissions from cross-origin iframes, we'll be replacing the Mozilla Geo website from our test plans [here](https://github.com/brave/qa-resources/issues/44).
