### ISSUE TITLE
Error: Cannot find module 'request'.

### ISSUE THREAD

**Issue by Doimatcuabautroi** [brave/browser-laptop#1269]
"The app provided is not a valid Electron app, plz read  the docs on how to write one: https://github.com/atom/electron/tree/v0.37.4/docs
Error: Cannot find module 'request'.

**Comment by weems** [comment]
@Doimatcuabautroi  Are you trying the latest version 0.8.3? https://github.com/brave/browser-laptop/releases/tag/v0.8.3dev

**Comment by Doimatcuabautroi** [comment]
yea.

**Comment by Doimatcuabautroi** [comment]
i don't use setup, i install it through github
i use win 7

**Comment by weems** [comment]
Then there was a error in the build process. Please use our builds or work to get a successful build using https://github.com/brave/electron/blob/master/docs/development/build-instructions-windows.md Documentation.

**Comment by Doimatcuabautroi** [comment]
tks, but at "Bootstrapping"
 i dont  understand, how to "$ python script\bootstrap.py -v", 
it notify:"bash: python: command not found", i install python :((

**Comment by weems** [comment]
@Doimatcuabautroi afaik python is not a pre-req to building for windows

**Comment by weems** [comment]
but perhaps this issue is best moved over to the electron fork https://github.com/brave/electron/

**Comment by Doimatcuabautroi** [comment]
i fixed it, and more error
![new bitmap image](https://cloud.githubusercontent.com/assets/18320809/14402818/9b69177e-fe48-11e5-9beb-040fdfe769e0.png)
electron ver0.37.5
win 7 32bit

**Comment by bbondy** [comment]
You get this because a fresh npm install needs to work. 
But this error specifically could also be fixed by running `npm run postinstall`
