### ISSUE TITLE
Bake about:welcome into Brave

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12691]
Per @Liunkae's comments on #12632, <about:welcome> makes a bunch of network requests without user interaction, a move that surprises users. We  should avoid requesting remote resources unless a user initiates the interaction.

**Comment by diracdeltas** [comment]
this is coming from https://brave.com/welcome/ - may be a better issue for the brave-website repo?

**Comment by flamsmark** [comment]
As a user, it's surprising that an about: page is just a remote resource. IMO, we should bake this whole page into the Browser.

**Comment by bsclifton** [comment]
@flamsmark pulling in @bradleyrichter and @cezaraugusto 

I believe that was the long term goal. This was a great first rev solution since updating the content for users is relatively easy

**Comment by bradleyrichter** [comment]
Interesting of note, Opera and Edge both use a remote resource as well.

For us, the reason was to allow for faster iteration and building without dev resources.

Our next version of the welcome experience will need to go through a refinement stage as we get more feedback. After it solidifies, we could move it to browser-internal if resources are available.

**Comment by flamsmark** [comment]
Beyond the privacy and perf benefits, a local page can be given greater capabilities. We could put things like a safe browsing or analytics switch right in the page, rather than bouncing the user out to a separate settings page. That could make it so much easier for folks to turn on important features.

**Comment by bridiver** [comment]
any objections to closing this in favor of https://github.com/brave/brave-browser/issues/276 ?

**Comment by bsclifton** [comment]
@bridiver nope- let's close it up
