### ISSUE TITLE
Is there any way to write browser extensions for Brave?

### ISSUE THREAD

**Issue by fristys** [brave/browser-laptop#12707]
### Description

Is there any formal process for developing extensions for Brave? What about an extension gallery?

I'd like to give it a go and develop an extension myself, that's why I'm interested.

**Comment by Tomatoshadow2** [comment]
Jonathan wrote a medium post a few months ago about testing Chrome extensions in Brave. https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d

**Comment by fristys** [comment]
So...basically, the only way possible is through some hacky injection way? That's pretty disappointing.

**Comment by Tomatoshadow2** [comment]
I believe at the moment yes, not 100% sure. But, as he mentioned more extension support will be coming.

**Comment by srirambv** [comment]
@fristys  There are tons of extensions that need contributions. You can check the list [here](https://github.com/brave/browser-laptop/projects/1)

You can start working on any extension and submit a PR. You can refer to guidelines [here](https://github.com/brave/browser-laptop/blob/master/CONTRIBUTING.md). Someone from the team would be glad to help you out
cc: @jonathansampson
