### ISSUE TITLE
lacking transparent technical documentation for Brave's built-in password manager

### ISSUE THREAD

**Issue by fermulator** [brave/browser-laptop#12701]
### Description
As a new user to Brave (coming from Firefox), I was first and foremost interested in investigating Brave's password manager security features. Primarily the encryption methods used, and how this interacts with the Brave-sync featureset.

At the onset, was unable to find any official technical documentation surrounding how this feature works and what the underlying technology is. (hence this issue submission)

Prior to submitting, I found various other issues related, and community forum posts asking similar questions. I think this therefore shows a gap in Brave's documentation on this topic.

### Steps to Reproduce & Actual Results

To start with, the user is aware of the password manager via: about:preferences#security
, and can maybe passwords via: about:passwords
 -> from either of these views, there is no obvious way to learn more information about the features
 -> https://community.brave.com/t/where-are-my-passwords-saved/12696
 -> https://community.brave.com/t/enhancing-private-data-security-braves-built-in-about-passwords/9858

Coming from Firefox land with a master password, after enabling "Brave Built-In" as the password manager, it may be highly surprising that there was no prompt for a passphrase to be used for the on-disk encryption of said password storage.
 -> ah, see: https://github.com/brave/browser-laptop/issues/1385

There is a loose claim that it integrates/leverages the systems keychain management (i.e. on Linux, gnome-keyring or perhaps k-wallet)
 -> https://github.com/brave/browser-laptop/issues/2589

Further, comparing the built-in to "others supplied via extensions", I have no idea why I should trust one or the other; or even if Brave's itself is secure and trustworthy enough.
 -> see my reddit post asking here: https://www.reddit.com/r/braveproject/comments/7r6awh/brave_password_manager_vs_others/?st=jcjuitcx&sh=13114369

Finally, when coupled with Brave's sync feature, how does all of this interact? Where are the encrypted files stores?
 -> https://github.com/brave/sync/wiki/Design
, that wiki has a great start to this topic, however doesn't mention the word "password" at all.

**Expected result:**

I think we should provide a complete and comprehensive set of documentation surrounding Brave's built-in password manager, cryptography techniques for security used, comparisons/guidelines for 3rd party password manager extensions, and the interactions with the Sync feature.

For high level considerations, compare to the complete documentation supplied from Firefox (as an example)
 * https://support.mozilla.org/en-US/kb/password-manager-remember-delete-change-and-import
 * https://support.mozilla.org/en-US/kb/use-master-password-protect-stored-logins
 * https://support.mozilla.org/en-US/kb/using-master-password-sync

**Reproduces how often:**
100%
, an immediate gap to a security minded person attempting to switch to Brave from Firefox.

### Brave Version

**about:brave info:**
```
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.10.0-42-generic 
OS Architecture: x64
```

**Reproducible on current live release:**
yes

### Additional Information
If someone from the Brave team would mentor/guide me, happy to help the community/project by writing content; just need some content, references, and support to get started.

**Comment by fermulator** [comment]
Initial trolling of source code leads me to the conclusion that the built-in Brave password manager is not much (if at all) different from what's provided by Chromium's source.

i.e.
 -> https://github.com/brave/muon/blob/master/brave/browser/password_manager/brave_password_manager_client.cc#L379
 -> https://github.com/brave/muon/blob/master/brave/utility/importer/chrome_importer.cc#L357

Which likely means we're subject to the same considerations from Chromium?
 -> https://www.chromium.org/Home/chromium-security/security-faq#TOC-Does-the-Password-Manager-store-my-passwords-encrypted-on-disk-

**Comment by polymorpher** [comment]
+1. This is the only thing stopping me from switching from Chrome to Brave for everyday use. A lot of people like myself need a way to verify Brave is secure enough to handle sensitive information such as passwords and credit cards, before we can start using it for anything on daily basis.

**Comment by Dnominated** [comment]
I ran into the same problem.

> You can't switch from one platform to another on the same computer, because Sync goes directly between two instances of the browser running simultaneously.
 
> There is no 'pack-and-go' option to backup a profile, even with the browser closed, and restore it elsewhere. The documentation on how to backup your profile is a lie.

**Comment by bsclifton** [comment]
This is something we unfortunately won't be able to get to before switching over to [brave-core](https://github.com/brave/brave-browser). I'd encourage taking a look at one of our experimental installs there to see if you have any questions about the new product
