### ISSUE TITLE
Basic Attention Token (BAT) Website Intergration

### ISSUE THREAD

**Issue by Oflameo** [brave/browser-laptop#12704]
I want to integrate Basic Attention Token (BAT) support into some websites, mostly websites based on MediaWiki and DokuWiki frameworks. What Libraries do I need to set that up?

I have one website that can take BAT now, [Binding Mandatory Arbitration Blacklist](https://www.bmablacklist.com/index.php/Binding_Mandatory_Arbitration_Blacklist:About ), but it just a link backed by an Exodus Wallet.

**Comment by bsclifton** [comment]
Hi @Oflameo 

If you're just wanting to receive BAT from Brave users, you don't have to do anything special.  Sign up at https://publishers.basicattentiontoken.org/ and you can get started

If you're wanting to use BAT on your site, that's a little different. I can't offer any advice regarding that as this is a repository for the Brave desktop browser.  You might join our Rocket chat server if you wanted to run your idea by more folks
https://basicattentiontoken.rocket.chat/
