### ISSUE TITLE
When browser starts, delete the verified publisher cache

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#12713]
When the browser starts, it's a good idea to delete the cache of verified publishers. This allows us to tell people to restart their browser if they're not seeing a green-check mark when they should.

**Comment by NejcZdovc** [comment]
let's wait with this one and see how https://github.com/brave/browser-laptop/issues/12272 will improve things

**Comment by mrose17** [comment]
agreed!

**Comment by NejcZdovc** [comment]
@mrose17 do you think that we still need to do anything about it?

**Comment by mrose17** [comment]
@NejcZdovc - yes, i would still implement this.

**Comment by NejcZdovc** [comment]
@mrose17 I just checked and we don't have any specific cache right now. The only thing that we have is `verifiedTimestamp` timestamp that prevents pulling from the server every time (only when there is a change). What we could do is clear that timestamp on start up, but I don't see any reports about verified publishers anymore so I think this is overkill. Based on that I would close this issue, wdyt?

**Comment by mrose17** [comment]
agreed: OBE.
