### ISSUE TITLE
inbox.google.com not supported

### ISSUE THREAD

**Issue by tbates** [brave/browser-laptop#12723]
### Description
Even with shields down, navigating to inbox yields this:

"Oops, your browser is not yet supported. Inbox works best on Chrome, Firefox, Edge or Safari."

### Steps to Reproduce

  1. navigate to https://inbox.google.com

**Actual result:**

<img width="716" alt="screenshot 2018-01-19 08 12 09" src="https://user-images.githubusercontent.com/736156/35140800-81746bc2-fcf0-11e7-9d62-cbcc716ebaec.png">

**Expected result:**
load inbox

**Reproduces how often:**
everytime

### Brave Version

 
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**
not sure

**Comment by bsclifton** [comment]
Thanks for the report, @tbates! Have you tried turning off the shields (lion icon in top right; toggle from on to off). I suspect one of the blocking features may be affecting your experience with this site
