### ISSUE TITLE
Dynamically build monthly amount dropdown 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#12727]
### Test plan
See https://github.com/brave/browser-laptop/pull/12728

### Description

We need to get data from server about monthly amount drop down. If user has different amount selected than we provide in the server list we need to keep it.

**Comment by bsclifton** [comment]
@NejcZdovc when you have time, can you create a test plan for this? Thanks 😄 👍

**Comment by NejcZdovc** [comment]
@bsclifton test plan can be found here https://github.com/brave/browser-laptop/pull/12728#issue-290014643

**Comment by kjozwiak** [comment]
@NejcZdovc I've also noticed the following possible issues. I'm assuming these are expected I wanted to double check with you first. Possible issues:

You can only set `payments.contribution-amount` to either a whole number (10 BAT) or a half number (10.5 BAT). Using other denominations such as 10.7 BAT and 10.3 BAT doesn't work.

The second thing that I noticed is that once you change the value to something else from the dropdown menu, the "dynamic" value is removed from the dropdown list. Should those values be saved in the dropdown list? I'm assuming this is expected so we don't end up polluting the dropdown with a bunch of different values.

**Comment by LaurenWags** [comment]
@NejcZdovc - noticing that if I change my Monthly Budget to 15 BAT and close/reopen Brave, it changes to 75 BAT. Similarly, if I choose 20 BAT and close/reopen, it changes to 100 BAT.

**Comment by srirambv** [comment]
Modified value is retained after restart on 0.20.20. Tried the following scenarios
1. Changed payments.contribution-amount value to 0.99 -> Restart -> Showed 1.0 BAT
2. Changed payments.contribution-amount value to 4 -> Restart -> Retained 4 BAT
3. Changed payments.contribution-amount value to 0.8 -> Restart -> Retained 0.8 BAT
4. Changed payments.contribution-amount value to 17.35 -> Restart -> Showed 17.4 BAT
