### ISSUE TITLE
Some favicons are distorted

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12722]
### Description
Dark themed tabs apply a filter to favicons which often distorts them beyond recognition or does not fit in with the rest of Brave's flat(ter) visual style.

### Steps to Reproduce
Ensure themed tabs are on (the default)

  1. Visit apple.com in active tab

**Actual result:**
Favicon is blurred beyond recognitino

**Expected result:**
Favicon is Apple logo

![image](https://user-images.githubusercontent.com/741836/35140244-639dcf84-fcab-11e7-84c9-01af357c1b40.png)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.19

**Reproducible on current live release:**
yes

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
