### ISSUE TITLE
Tab background gradient is visible when switching tabs

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12721]
### Description
When switching tabs, a gradient is visible for a brief moment. This adds to the feeling of jank.

### Steps to Reproduce

  1. Activate a themed dark tab (e.g. new tab page)
  2. Switch tabs (e.g. using ctrl-tab)

**Actual result:**
Janky visual transition

**Expected result:**
Smooth transition

![issue-tab-background-gradient-transition-visible](https://user-images.githubusercontent.com/741836/35139804-9a332622-fca9-11e7-8a34-fcdecc2d8ada.gif)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.20

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
