### ISSUE TITLE
username autofill appearing on the top left corner when loading twitter using brave's password manager

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12733]
### Description

When you've saved a password for Twitter using brave's built in password manager, the autofill username will appear on the top left corner of the page which indicates that there might be an abusive login form attempting to steal the credentials. We should look into why this is happening as it might confuse some users or scare the more privacy oriented users.

### Steps to Reproduce

  1. launch `0.19.134` and visit https://twitter.com/
  2. login into twitter and save the password using brave's password manager 
  3. once the password been saved, logout and refresh the page

**Actual result:**

You'll notice that the autofill username will keep appearing in the top left corner indicating that there's a hidden login form somewhere on the page that's trying to access login credentials.

![twitterautofill](https://user-images.githubusercontent.com/2602313/35164418-4bf4d18a-fd18-11e7-9d1f-167762996786.gif)

**Expected result:**

Not 100% sure, we should investigate to figure out why it's being triggered.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.134 
> rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
> Muon: 4.5.38 
> libchromiumcontent: 63.0.3239.132 

**Reproducible on current live release:**

Yes, currently reproducible under `0.19.134` which is the current release.

### Additional Information

* Win 10 x64 - Reproduced
* macOS x64 - Reproduced (@LaurenWags also reproduced)
* Ubuntu 17.10 x64 - Reproduced

**Comment by eljuno** [comment]
Related to #12595? Since it happen for me on every sites that require log in. :)

**Comment by darkdh** [comment]
it's expected because the form is already there just not being displayed
so before the password popup changes, it is actually autotfilled when page load. You will only see it when you click login and let it display the form.

![kapture 2018-01-22 at 11 02 09](https://user-images.githubusercontent.com/11330831/35238875-ba758990-ff63-11e7-964f-e7f11870fd53.gif)
