### ISSUE TITLE
Unity3d Web Player

### ISSUE THREAD

**Issue by MegaUber** [brave/browser-laptop#1274]
Possible work around? Loading plugin from other browser or maybe older version of Chrome? I know that it's no longer supported by Chrome, but would still be a nice addition.

Side note, I have the plugin for unity pulled as a .plugin so it might or might not work.

How would one go about 
`app.commandLine.appendSwitch('??????', unityPath);`
`app.commandLine.appendSwitch('??????', unityVersion);`

ref #468, #1293

**Comment by luixxiul** [comment]
ref #468, #1293

**Comment by Jacalz** [comment]
+1 from community https://community.brave.com/t/can-unity-be-installed/4882

**Comment by luixxiul** [comment]
I'm going to close this issue as there is not a possible solution to fix that. Let's talk about it more on that community topic 😉
