### ISSUE TITLE
Use Pocket reading list activity as ledger signal

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#12740]
Most of my reading activity isn't in the browser itself. I'm constantly saving links to Pocket, which is where I spend most of my time actually reading news and articles. The things I read in Pocket are usually the ones that matter most to me — the creators I most want to support — but they aren't represented in my Brave Payments list.

Brave on my laptop could use OAuth to access my reading activity, favorites, and recommendations on Pocket and incorporate that as a signal about my attention on those sites.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/pocket-integration/18730?u=eljuno
