### ISSUE TITLE
Multiple Reports of versions 0.19.139 and above Crash on install with MacOS 10.9.5

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12744]
### Description
After update/restart users of MacOS 10.9.5 are reporting that 0.19.139 crashes for them:
https://community.brave.com/t/most-recent-version-of-brave-crashes-on-launch/14336
https://community.brave.com/t/last-update-crash-on-restart-and-startup/14332/3

### Steps to Reproduce

  1. Using MacOS 10.9.5 update Brave to 0.19.139
  2. Open
  3. Brave Crashes

**Actual result:**
Crash on loading new version.

**Expected result:**
No Crash

**Reproduces how often:**
Easily for the OS listed

### Brave Version

**about:brave info:**
0.19.139

**Reproducible on current live release:**
Yes

**Comment by Tomatoshadow2** [comment]
+1 from community, https://community.brave.com/t/brave-automatically-shuts-down/14516/2

**Comment by LaurenWags** [comment]
Multiple +1s from community: https://community.brave.com/t/browser-crash-upon-opening/14394

**Comment by LaurenWags** [comment]
+1: https://community.brave.com/t/update-to-0-19-139-crash-on-restart-and-startup/14332/13

**Comment by Tomatoshadow2** [comment]
My apologies that I missed those Lauren.

**Comment by LaurenWags** [comment]
no worries at all @Tomatoshadow2 - I appreciate you linking any community posts you find to the appropriate issue 😄  It is especially helpful on this so we can reach out to these folks when there's a resolution.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/update-button-made-brave-inoperable/14523

**Comment by Tomatoshadow2** [comment]
Awesome, thanks so much Lauren. +1 in the last two hours, since your last post https://community.brave.com/t/most-recent-version-0-19-139-of-brave-crashes-on-launch/14336/20

**Comment by Tomatoshadow2** [comment]
+1 https://community.brave.com/t/clicked-update-on-mavericks-now-brave-crashes-on-launch/14558

**Comment by vanclute** [comment]
+1 here too.

**Comment by SaXeee** [comment]
+1 here too. Macbook Pro with OSX 10.9.5.
I've tried with release V0.19.138, v0.19.139 and v0.19.140. Same problem.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/brave-crashes-instantly-on-my-mac/14600

**Comment by LaurenWags** [comment]
+2 from community: https://community.brave.com/t/mac-brave-crashes-on-startup/14597

**Comment by bsclifton** [comment]
There is a preview version that folks can try which may resolve the issue OR will at least (hopefully) collect more details
https://github.com/brave/browser-laptop/releases/tag/v0.19.141dev

cc: @SaXeee @vanclute

**Comment by bsclifton** [comment]
Also- some great info here about crash reporting and how you can help us debug 😄 
https://github.com/brave/browser-laptop/wiki/Crashes

**Comment by Tomatoshadow2** [comment]
@bsclifton Should I let people in the community know about this from now on?

**Comment by LaurenWags** [comment]
I heard from a user in community who tried the latest 0.19.143 build and said no .dmp file was created :( what do you make of that @bsclifton ?

**Comment by bsclifton** [comment]
Yikes- sucks to hear the dump file isn't created. We can always have the user install the last known good version of Brave and then open `chrome://crashes` to see if anything is there (and if so, manually submit the crash report)

**Comment by LaurenWags** [comment]
@bsclifton @bridiver not sure if this information which was provided by a community member re: crash on opening 10.9.5 is helpful (some is in Japanese but there is an error from the terminal): 

```$ /Applications/Brave.app/Contents/MacOS/Brave 
dlopen /Applications/Brave.app/Contents/MacOS/../Frameworks/Brave Framework.framework/Brave Framework: dlopen(/Applications/Brave.app/Contents/MacOS/../Frameworks/Brave Framework.framework/Brave Framework, 265): Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
  Referenced from: /Applications/Brave.app/Contents/Frameworks/Brave Framework.framework/Brave Framework
  Reason: image not found```

https://community.brave.com/t/update-to-0-19-139-crash-on-restart-and-startup/14332/17

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/brave-20-update-causing-websites-to-not-load/15218/3

**Comment by LaurenWags** [comment]
+1s from community: https://community.brave.com/t/unable-to-opwn-brave-browser-on-my-desktop-running-mac-10-9-5-maverick/15660

**Comment by LaurenWags** [comment]
@bsclifton and @bridiver is there anything else community members can do to assist? A couple of them have asked: https://community.brave.com/t/most-recent-version-0-19-139-of-brave-crashes-on-launch/14336/31

**Comment by kjozwiak** [comment]
@bridiver got his hands on 10.9.5 so hopefully we'll have a fix soon once he's done investigating.

**Comment by breadesign** [comment]
Hi there - is there any news on this issue?

Thanks in advance

Ben

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/unable-to-install-os-x-requirements-legacy-versions/18961

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/crashes-on-startup-on-mac-10-9-5/19544

**Comment by pautasso** [comment]
FWIW I can also confirm that the latet? Brave 0.22.22 will also crash on my Mac 10.9.5.

/Applications/Brave.app/Contents/MacOS/../Frameworks/Brave Framework.framework/Brave Framework: dlopen(/Applications/Brave.app/Contents/MacOS/../Frameworks/Brave Framework.framework/Brave Framework, 265): Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth

**Comment by kjozwiak** [comment]
Thanks for the check @pautasso 👍 Looks like this is still an issue with `C66` as well:

```
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```

**Comment by drewreece** [comment]
Is Brave actually supporting 10.9.5?
There are around 14 threads listed in the community page that seem to share the same issue (after a cursory glance of them), https://community.brave.com/search?q=10.9%20crash%20
– Brave cannot open successfully on 10.9.5.

I understand it is difficult to support older OS's & would love Brave to work on 10.9.5. 

The post below from February 14th by By0Ir9 does allow Brave to open for me.
https://community.brave.com/t/update-to-0-19-139-crash-on-restart-and-startup/14332/25

I used this command to symlink the framework as it specifies the target as well as the source without 'cd'ing to the directory…
`sudo ln -s  /System/Library/Frameworks/IOBluetooth.framework/Frameworks/CoreBluetooth.framework/ /System/Library/Frameworks/CoreBluetooth.framework`

Clearly this is a System hack (kittens might cry in Cupertino). 
I can't see where Brave sets up the framework paths in the source code to attempt any fixes - I'm not a node developer so maybe just rebuilding Brave on 10.9.5 will correct the path? I tried to build but npm dependancies just keep throwing errors so I gave up.

**Comment by bsclifton** [comment]
Hi folks,

I don't believe that we'll be able to address this before we make the switch over to Brave Core ([see our engineering blog for more info on that](https://brave.com/development-plans-for-upcoming-release/)).

When we make that switch, we should have exactly the same system requirements as Chrome / Chromium.  If latest Chrome is working on 10.9.5, then this issue should be fixed at that time 😄 

Hang tight- for the more tech savvy folks, you might try the work-around mentioned by @drewreece (if you feel comfortable doing so)
