### ISSUE TITLE
Uncaught ReferenceError: OAS_rdl is not defined when loading monster.ca

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12747]
### Description

Originally a report from the community:
* https://community.brave.com/t/monster-ca-login-screen-reloads-every-second/14325

When attempting to login into monster.ca, the website will refresh itself every few seconds and produce the following error message within the browser console:

```
Uncaught ReferenceError: OAS_rdl is not defined
    at <anonymous>:5:154
    at Object.generateOASAd (login20_js.axd?s=1:17)
    at Object.generateAd (login20_js.axd?s=1:20)
    at SignIn:559
  | (anonymous) | @ | VM548:5
  | generateOASAd | @ | login20_js.axd?s=1:17
  | generateAd | @ | login20_js.axd?s=1:20
  | (anonymous) | @ | SignIn:559

```

Either blocking the Brave shield or disabling "Block Ads" will resolve the issue.

### Steps to Reproduce

  1. launch `0.19.139` 
  2. load https://login20.monster.ca/Login/SignIn with the brave shield enabled

**Actual result:**

Website keeps refreshing itself every few seconds making it very difficult to use when "Block Ads" is enabled.

**Expected result:**

Website shouldn't be refreshing itself every few seconds when "Block Ads" is enabled.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

Yes, currently reproducible under `0.19.139` and `0.19.134`:

> Brave: 0.19.139 - Reproduced
> rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
> Muon: 4.7.2 
> libchromiumcontent: 64.0.3282.85

> Brave: 0.19.134 - Reproduced
> rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
> Muon: 4.5.38 
> libchromiumcontent: 63.0.3239.132 

### Additional Information

* macOS 10.13.2 x64 - Reproduced
* Win 10 Pro x64 - Reproduced

**Comment by snyderp** [comment]
cant reproduce in beta

**Comment by kjozwiak** [comment]
Thanks for the double check @snyderp! I couldn't reproduce the above issue using the following `muon` build:

```
 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

Couldn't reproduce the issue with b-c `beta` either:


Brave | 0.55.10 Chromium: 70.0.3538.22 (Official Build) beta(64-bit)
-- | --
Revision | ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364-refs/branch-heads/3538@{#468}
OS | Mac OS X
