### ISSUE TITLE
"Pocket: Installed" tab opens every session

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#12752]
Similar to #11578, but for pocket instead of metamask.

### Description
The ["Pocket: Installed"](https://getpocket.com/installed/) page opens in a new tab every time Brave starts. I have logged into pocket a couple of months back, but haven't been using it actively for a while.

### Steps to Reproduce

  1. Enable the pocket plugin and login to pocket. 
  2. Close and reopen Brave.

**Actual result:**
A tab with the ["Pocket: Installed"](https://getpocket.com/installed/) page. It is loaded after any session reloading, as a new tab.

**Expected result:**
Just the session reloading.

**Reproduces how often:**
Seems to be reproducable most of the time, not sure if it is 100% because I wouldn't notice it if it doesn't happen. Happens often enough to be annoying. Perhaps it is more likely to happen after updating Brave.

### Brave Version

**about:brave info:**
 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.17025 
OS Architecture: x64

**Reproducible on current live release:**
Think so

**Comment by bsclifton** [comment]
@hugobuddel does this still happen?

**Comment by bsclifton** [comment]
Closing as I believe this was fixed by @darkdh quite a while ago. I tried w/ Pocket enabled and did not run into this

**Comment by hugobuddel** [comment]
I've not had pocket enabled since, so reenabled it. Everything seems to work fine. I'll let it know if the issue returns. (FWIW, I started using pocket because it synchronizes with my kobo e-reader and stopped using it because  the kobo client has no 'random' option. But this is irrelevant to Brave)
