### ISSUE TITLE
Crash on this site

### ISSUE THREAD

**Issue by RSCipher001** [brave/browser-laptop#12751]
### Description
Brave crashes every-time when I try to open this link

### Steps to Reproduce
1. Click http://beautifytools.com/html-to-json-converter.php and done

**Reproduces how often:**
Every time

### Brave Version
Name	Version
Brave	0.19.131
rev	da2f347
Muon	4.5.36
libchromiumcontent	63.0.3239.132
V8	6.3.292.49
Node.js	7.9.0
Update Channel	Release
OS Platform	Linux
OS Release	4.13.0-26-generic
OS Architecture	x64

**Comment by bsclifton** [comment]
@RSCipher001 can you please try with the latest release? I am using 0.19.139 (which uses Chromium 64) and am not able to reproduce (I tried on both Linux and macOS)
