### ISSUE TITLE
History is cleared when browser updates

### ISSUE THREAD

**Issue by linuslagerhjelm** [brave/browser-laptop#12757]
### Description

Whenever the browser is updated, it clears all browsing history. I tried to search for a setting that could affect this but the closest I got was "Clear the following data types when I close Brave" > Browsing history. Which is not selected and on normal restarts, the history is kept intact.

### Steps to Reproduce

  1. Press the "Update" button when Brave notifies you about a new version

**Actual result:**

![image](https://user-images.githubusercontent.com/10388912/35186065-7f3a2fa8-fe0e-11e7-8323-2148bcdee358.png)

**Expected result:**
The history should still be there

**Reproduces how often:**

I am quite new to brave but so far, it has happened every time I updated Brave which is 3 times.

### Brave Version

**about:brave info:**

 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by Tomatoshadow2** [comment]
Does the browser save your history for you usually?

**Comment by linuslagerhjelm** [comment]
Yes it does

**Comment by Tomatoshadow2** [comment]
Do you have it set to clear upon you closing Brave?

**Comment by linuslagerhjelm** [comment]
I am sorry about my somewhat confusing description. I don't have it configured to remove history when I close Brave. This is my settings:

![image](https://user-images.githubusercontent.com/10388912/35238707-9cebd960-ffae-11e7-8b3c-46fbc3ece15c.png)

**Comment by Tomatoshadow2** [comment]
Totally fine, that's interesting, you have none of those checked and your history disappears, hmm.

**Comment by esmail** [comment]
I think I also got hit with this when I updated to v0.20.30

**Comment by TimSoethout** [comment]
Same on 0.24.0 on OSX.

**Comment by bsclifton** [comment]
Hi folks- this is something that we won't be able to address with the current code-base. I'd suggest installing our latest Beta release (and then importing your Brave settings!):
https://brave.com/download-beta

The issue should be fixed there 😄
