### ISSUE TITLE
what prevents people from forking brave and hiding brave network ads as well?

### ISSUE THREAD

**Issue by mcandre** [brave/browser-laptop#1275]

**Comment by MegaUber** [comment]
Nothing, that's the point of it being open source. Ideally one would hope that people are jerks and don't try to take claim of something that isn't theirs, but shares with the community of individuals that have worked on it. :)

**Comment by bbondy** [comment]
Nothing, it's probably easier to just select Block ads from the menu we provide though.

<img width="226" alt="screenshot 2016-04-07 23 47 34" src="https://cloud.githubusercontent.com/assets/831718/14373730/1cd0eb9a-fd1b-11e5-8b32-6d6bca004380.png">
