### ISSUE TITLE
Remove CoinMarketCap Empty Elements

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12755]
### Test plan
See https://github.com/brave/browser-laptop/pull/12756

### Description
Ad removal on CoinMarketCap leaves empty elements.

### Steps to Reproduce
Navigate to coinmarketcap.com, and note spaces.

**Actual result:**
Large empty regions remain.

**Expected result:**
Large empty regions should be collapsed when ads are removed (when appropriate)

**Reproduces how often:**
100%

### Brave Version
0.19.139

**about:brave info:**
```
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
```

**Reproducible on current live release:**
Yes

**Comment by LaurenWags** [comment]
@jonathansampson This is what I'm seeing when using packaged build 0.20.17. Based on the Test Plan (https://github.com/brave/browser-laptop/pull/12756) - I'm still seeing empty spaces on MacOS. Could you take a look?

![12755](https://user-images.githubusercontent.com/28145373/35239984-081d5f30-ff80-11e7-805d-c181ed81b580.gif)

**Comment by srirambv** [comment]
Seeing same on Windows as well

**Comment by kjozwiak** [comment]
Looks good on Ubuntu. I spent some time browsing through CoinMarketCap and I didn't notice any awkward spaces/modals/popups. Examples:

<img width="1421" alt="screen shot 2018-01-23 at 11 02 52 pm" src="https://user-images.githubusercontent.com/2602313/35314180-6b31934e-0092-11e8-8b5f-3defd2a79c59.png">

<img width="1421" alt="screen shot 2018-01-23 at 11 03 40 pm" src="https://user-images.githubusercontent.com/2602313/35314177-674881ac-0092-11e8-9c2e-112aa5ab6a5c.png">

<img width="1423" alt="screen shot 2018-01-23 at 11 12 44 pm" src="https://user-images.githubusercontent.com/2602313/35314258-f55c414a-0092-11e8-892c-084d0d883553.png">
