### ISSUE TITLE
PDF render if content-type is HTML

### ISSUE THREAD

**Issue by sepeiFH** [brave/browser-laptop#12763]
### Description
Website is rendered as PDF because the url ends with pdf but the content type is text/html

### Steps to Reproduce

  1. Open https://www.waveshare.com/wiki/File:SDRAM-Board-B-schematic.pdf

**Actual result:**

![image](https://user-images.githubusercontent.com/22662993/35193786-3b2b57ac-fea8-11e7-84fa-7885189e63bb.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/22662993/35193790-4d381868-fea8-11e7-8fda-f9158613299e.png)

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.3.9600 
OS Architecture: x64

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@eljuno yup- appears to be a dupe (good catch!) 😄 👍
