### ISSUE TITLE
Use follow activity as a ledger signal

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#12761]
On many multi-publisher sites like YouTube, users can take action to add particular creators or publishers to the user's feed by subscribing, following, or so on. These represent user-initiated action to indicate that they would like to see more of whatever the content might be. It's reasonable to assume that folks are more excited to contribute to the creators to which they subscribe. If feasible, Brave should try to reflect those preferences in <about:preferences#payments>.

**Comment by bsclifton** [comment]
Closing as `wontfix`- but it might be worth adding into the `brave-core` issue backlog 😄
