### ISSUE TITLE
Ctrl + mouse click zooms page in/out

### ISSUE THREAD

**Issue by broros** [brave/browser-laptop#12764]
macOS environment.

### Description
zooms in and out uncontrollably.

### Steps to Reproduce

  1. When holding down control on keyboard and mouse click the browser zooms in and out.
  2.
  3.

**Actual result:**
zooms in and out 

**Expected result:**
no zooming action.

**Reproduces how often:**
most of the time.

### Brave Version

**about:brave info:**

0.19.139
--

**Comment by bsclifton** [comment]
@broros just wanted to confirm: you are clicking, not using the mouse wheel, right?

Ctrl + Mouse wheel will zoom in/out

**Comment by broros** [comment]
this is happening on magic mouse ( macOS), there is no mouse wheel.  
It happens most of the time when I try to control + click

also this feature is not present on safari, so why have it on brave?

**Comment by gkarthiks** [comment]
is there any update on this issue ?

**Comment by bsclifton** [comment]
@gkarthiks can you please give our [Developer channel release](https://brave.com/download-dev) a try? This issue should be resolved there
