### ISSUE TITLE
Publisher added back after restart

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#12766]
### Description

Site is re-enabled when you restart browser and site was added when auto-include was on off.

### Test plan / Steps to Reproduce

  1. Enable payments
  2. Disable auto-include
  3. Visit some sites (meet the visit/time criteria)
  4. Restart browser
  5. Publishers are re-enabled

**Actual result:**

![image](https://user-images.githubusercontent.com/9574457/35208136-fcfbb446-ff46-11e7-8c16-983a687674dc.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/9574457/35208139-016fb644-ff47-11e7-95d1-e4dadbfca547.png)

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**

yes

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.
