### ISSUE TITLE
Upgrade to React v15

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1277]

**Comment by bbondy** [comment]
Might or might not be a good first bug depending on how the upgrade goes. Marking it as such for now in case someone wants to grab it.

**Comment by weems** [comment]
want to learn but perhaps without knowing react it is complex for me :p

On Fri, Apr 8, 2016 at 12:23 AM, Brian R. Bondy <notifications@github.com>
wrote:

> Might or might not be a good first bug depending on how the upgrade goes.
> Marking it as such for now in case someone wants to grab it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/1277#issuecomment-207220387>
>



-- 
Michael Weems
c: 205.435.0770
