### ISSUE TITLE
Payments page is missing spacing between buttons

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12776]
### Description
'Claim my free tokens' button for UGP promotion and 'Add Funds...' button should have space between them.

### Steps to Reproduce

  1. Have active UGP promo (prod) or use staging to create a wallet
  2. View Payments page
  3.

**Actual result:**
Button spacing is incorrect:

![screen shot 2018-01-22 at 2 37 30 pm](https://user-images.githubusercontent.com/28145373/35240954-002fdb10-ff83-11e7-8d09-2aeb0a60cf29.png)

**Expected result:**
Button spacing should be as it is in 0.19.139:

<img width="863" alt="screen shot 2018-01-22 at 2 38 08 pm" src="https://user-images.githubusercontent.com/28145373/35240966-09bc132e-ff83-11e7-900c-bf5ac1a77ced.png">

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.17
V8 | 6.4.388.29
rev | 5fa67ff
Muon | 4.7.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.99

**Reproducible on current live release:**
no

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/12779
