### ISSUE TITLE
Crash reporting / stats reporting should be using version (not rev)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12772]
## Test plan (WIP)
1. Go to chrome://crashes and confirm crash reporting is NOT disabled
2. Go to chrome://crash to cause a crash
3. Go to chrome://crashes - a new report (for the crash in step 2) show show up and be uploaded
4. Go to https://stats.brave.com/dashboard#recent_crashes and login
5. Crash should show up there and version should be 0.19.144 (not a GUID)

## Original issue description
Appears we missed a patch
https://github.com/brave/browser-laptop/commit/7317c707667d0b434d94aa916523ad588552f4ed

**Comment by kjozwiak** [comment]
Can't check this again Linux because of #12839.
