### ISSUE TITLE
Improve typography in Brave Payments notification panel

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12770]
Sub-text issues to improve:
- line spacing too tight
- text color too light
- string width to narrow, creating orphans in EN strings

Current:
![image](https://user-images.githubusercontent.com/13509546/35233230-58bf70c8-ff52-11e7-8999-96c85898b14b.png)

Improvements:
- increase line spacing by 30%
- darken grey value by 30%
- extend text area width by 50px

![image](https://user-images.githubusercontent.com/13509546/35233370-d468cf3a-ff52-11e7-9952-4bc1725311d0.png)

**Comment by arsalankhalid** [comment]
Hey guys, is this still available - would love to take a stab at this :)

**Comment by bradleyrichter** [comment]
@arsalankhalid We'd love your help! Go for it... 

cc @NejcZdovc

**Comment by NejcZdovc** [comment]
@arsalankhalid yes it's still available. If you need any help let me know. Thank you

**Comment by arsalankhalid** [comment]
Great, thanks for passing it over - will reach out :)

**Comment by arsalankhalid** [comment]
@NejcZdovc hard to re-create this, what are your thoughts?

![image](https://user-images.githubusercontent.com/5307218/35779255-fabe2b7c-0997-11e8-9a92-11b413c30a3c.png)

Is this fixed/non-existent, or an edge case based on specific messages the user received, just as the million dollar give away example, how can I re-create that?

**Comment by NejcZdovc** [comment]
@arsalankhalid try starting your run with `LEDGER_ENVIRONMENT=staging npm run start` (don't forget to clean profile). We still have some promotions on our staging servers. Please while you are working on this one just claim one promotion and then don't click `OK` or `X` until you are done. This way you will not run out of promotions.

**Comment by arsalankhalid** [comment]
Great thanks, let me give that a shot.

**Comment by arsalankhalid** [comment]
Sorry for the radio silence, been a bit busy. Will take a stab tomorrow I more than hope :)

**Comment by arsalankhalid** [comment]
Hey still not sure how to re-create, how exactly do i 'claim' a promo?

**Comment by NejcZdovc** [comment]
@arsalankhalid check out this video


https://drive.google.com/file/d/1Rr2uUDILM44MIW8T7ZzrFYWtuzz9PdmI/view?usp=sharing

**Comment by arsalankhalid** [comment]
Sadly don't see it when I run it, even in staging :( 

![image](https://user-images.githubusercontent.com/5307218/36235940-5badb5d4-11c1-11e8-8f57-44c1cd5bb4bf.png)

I was hoping there was a way to test running the promos, or not possible? It would be easier to ensure the typography is good for all types of promo messages...as long as those promos are actually fake :P 

It's also possible i tried to run the promo already, in staging - but not sure. Please advise

**Comment by NejcZdovc** [comment]
[Archive.zip](https://github.com/brave/browser-laptop/files/1726630/Archive.zip)

You can use this profile. Just copy it into user profile folder and run `LEDGER_ENVIRONMENT=stagingn npm run start` and you should see the overlay that you need.

**Comment by arsalankhalid** [comment]
I hate to be the local noob, but wheres our user profile? Trying to find Brave directory on OSX. Almost seems like a feature for users to easily switch their profiles through preferences/settings? I saw some open and closed tasks regarding to 'portable profiles', but don't see anything in preferences to easily switch. 

Also that archive.zip file looks sketchy at first look lol, but i guess its a profile :P

**Comment by NejcZdovc** [comment]
your user profile is in `/Users/username/Library/Application Support`. In there you will find `brave-development` folder. Delete whatever is in this folder and extract zip into it.

**Comment by arsalankhalid** [comment]
in my brave-development folder, but don't see anything:

![image](https://user-images.githubusercontent.com/5307218/36271525-d715fb42-124c-11e8-84ca-025de2a33919.png)

**Comment by NejcZdovc** [comment]
@arsalankhalid if you have time we can jump on a call and check it out. Just send me an email to `nejc at brave.com`
