### ISSUE TITLE
Read promo code from profile directory and set AppState

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12789]
- There should be an argument passed during first run (on Windows there is; not sure about macOS after it's changed to PKG format). 
- During this first run, we should check for the presence of the `promoCode` file inside the user's profile directory (ex: `~/Library/Application Support/brave/promoCode`)
- Once file is detected and if code is valid, we need to set App State:
`state.setIn(['updates', 'promoCode'], promoCode)`

**Comment by LaurenWags** [comment]
See https://github.com/brave/browser-laptop/issues/12791#issuecomment-365710416 for MacOS tests with 10.13.3 ( @kjozwiak) and 10.12.6 ( @LaurenWags)
