### ISSUE TITLE
Configure promo API key

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12788]
Details pending security review here:
https://github.com/brave/internal/issues/189

**Comment by diracdeltas** [comment]
i feel this is unnecessary; see https://github.com/brave/internal/issues/189#issuecomment-360226992 for details.

**Comment by NejcZdovc** [comment]
What we need to do here for now is to add API that was provided into jenkins build. We should consume it the same was as we do `CHANNEL`

**Comment by NejcZdovc** [comment]
@evq adde API key to the jenkins job so I am closing this one

**Comment by kjozwiak** [comment]
@bsclifton @NejcZdovc is there any specific tests that QA needs to go through? From the sounds of the information available under https://github.com/brave/internal/issues/189, a simple end-to-end test should be sufficient enough to see if the API is working correctly.

If there's an easier way to make sure that the API is working, could you please add a test plan that we can follow? If not, we can mark this `QA/no-qa-needed` and cover it when going through end-to-end testing.

**Comment by NejcZdovc** [comment]
@kjozwiak I think that we don't have an easy plan. It's just end-to-end test
