### ISSUE TITLE
Update DMG installer to PKG format (macOS)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12784]
## Test plan

https://github.com/brave/browser-laptop/pull/12946

----

Packaging for macOS is currently done with https://github.com/electron-userland/electron-builder

Requirements:
- Outputs a single PKG file (not a PKG and a ZIP)
- PKG needs to run a script during the install
- **Script that runs NEEDS to be able to read the executable name**
- We may need to provide EULA
- Install location should NOT be configurable
- Custom icon would be great (if possible)

**Comment by bsclifton** [comment]
I've started checking this out and have a branch [referral-installer-macos](https://github.com/brave/browser-laptop/tree/referral-installer-macos). I have it successfully creating a PKG file, but it also creates a zip.
![pkg-installer](https://user-images.githubusercontent.com/4733304/35250671-00a4323c-ff95-11e7-9d49-9db29cac6013.png)

Electron builder has some good documentation available here:
https://www.electron.build/configuration/mac#MacConfiguration-target
https://www.electron.build/configuration/pkg

**Comment by petemill** [comment]
Note that we cannot customise the icon @bradleyrichter.

We _could_ add an image background / log to the window itself, i.e. put the PNG that we wanted on the left, underneath the 'steps' list. But this would be a medium effort, as would need to fork and modify the pkg file builder we are using.

Install location is not configurable, but the user still has a screen to select the disk to install on, even if there is only one disk.

**Comment by bradleyrichter** [comment]
I recommend that we continue with DMG for all normal builds and only use PKG for promo builds.


Are there other benefits to switching all over to PKG that I am overlooking?

**Comment by LaurenWags** [comment]
pkg file works on MacOS 10.12.6

**Comment by kjozwiak** [comment]
Went through the test plan mentioned above using the following platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX  10.10 x64 VM - PASSED

Thanks for going through `MacOS 10.12.6` @LaurenWags!
