### ISSUE TITLE
Script to read executable name (PKG) and output to profile directory

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12786]
## Test plan

https://github.com/brave/browser-laptop/pull/12953#issue-293024981

----

**NOTE: https://github.com/brave/browser-laptop/issues/12784 must be completed first**

During the PKG file install for a Release channel build (not BETA/DEVELOPER/NIGHTLY), a custom script should run. This script needs to do the following:
- Read executable name (ex: `Brave-ABC.pkg`)
- Look for / parse out a promotion code (ex: `ABC`)
- Put this promotional code into a file `promoCode` in the profile directory  (ex: `~/Library/Application Support/brave`)

**Comment by LaurenWags** [comment]
Works on MacOS 10.12.6
![screen shot 2018-02-13 at 4 51 16 pm](https://user-images.githubusercontent.com/28145373/36175626-23a44a4c-10de-11e8-9cb2-cf2122cce533.png)

**Comment by kjozwiak** [comment]
Went through the above STR/Test Case using the following platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX 10.10.5 x64 VM - PASSED
