### ISSUE TITLE
Ledger doesn't count visits to or time spent reading PDFs

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12792]
There doesn't seem to be a good root reason why PDF content shouldn't earn BAT.

**Comment by LaurenWags** [comment]
@NejcZdovc - PDFs don't have a favicon. Just want to confirm this is expected:
![screen shot 2018-04-12 at 6 14 52 pm](https://user-images.githubusercontent.com/28145373/38707001-6b38fb6a-3e7d-11e8-8800-f8d227aabf13.png)

I verified the following PDFs showed up in the ledger:
https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
http://www.pdf995.com/samples/pdf.pdf

I also verified that PDFs on my laptop opened with Brave did not display in the ledger.

**Comment by NejcZdovc** [comment]
@LaurenWags Yes this is expected, because PDF's don't have favicon.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.702 https://github.com/brave/browser-laptop/commit/e4a853d9990c62328a8a4320fec21f58c9cdc0c1
* muon 6.0.7
* libchromiumcontent 66.0.3359.139
