### ISSUE TITLE
Contact promo API after 30 days of usage

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#12791]
If `promoCode` is set and 30 days have gone by, the promo API should be contacted. It would pass (as input) the DownloadID obtained in the call made during first run

**Comment by petemill** [comment]
I believe this is fixed by #12798

**Comment by NejcZdovc** [comment]
correct, closing

**Comment by LaurenWags** [comment]
A. Happy Path steps for MacOS:
