### ISSUE TITLE
Developer Tools always show content of the first tab, not the current

### ISSUE THREAD

**Issue by anselmh** [brave/browser-laptop#1279]
So, I’ve just installed the latest version of Brave here:
```
Brave: 0.8.3
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 6.0.0-pre
Update channel: dev
```

When using secondary click action to inspect an element, the Developer Tools open up but they always show the content of the first open tab, not the current one I just wanted to inspect and that is active.

_I’ve not yet found an issue related to it so I report it now. It might be obsolete by some release that popped up just now in the github repo but is not available as update in the browser yet._

**Comment by anselmh** [comment]
Additional information: Calling the Developer Tools via `cmd + shift + i` opens up the correct page inspector. That said, I realize that I forgot to say I’m on latest OS X.

**Comment by bbondy** [comment]
Great find, thanks @anselmh.

**Comment by anselmh** [comment]
Wow that was fast. Thanks for fixing! :)
