### ISSUE TITLE
Enhancement: when highlighting text, right clicking and selecting search, open the new tab in the same position as a cloned tab, rather than the new tab position.

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#12793]
### Description
Enhancement: when highlighting text, right clicking and selecting search, open the new tab in the next tab (right of the current tab), rather than the new tab position as is the case now. That is, the new tab gets inserted in the same position as a cloned tab.

### Brave Version

**about:brave info:**
 
Brave: 0.19.134 
rev: 316cfa522ffe6a558fe9f2f3f299c0c602dfb691 
Muon: 4.5.38 
libchromiumcontent: 63.0.3239.132 
V8: 6.3.292.49 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-30-generic 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by grand-lotus-iroh** [comment]
+1 open new tab next to current (pinned) tab - right now, open new CTRL + T moves tab all the way to the right
