### ISSUE TITLE
does not load webpage https://www.nowinstock.net/ properly/formatting issues

### ISSUE THREAD

**Issue by griefage** [brave/browser-laptop#12805]
### Description
when visiting any page from www.nowinstock.net, brave does not load the webpage properly or have the correct formatting

### Steps to Reproduce

  1. visit https://www.nowinstock.net/
  2.
  3.

**Actual result:**

![untitled](https://user-images.githubusercontent.com/35741937/35294841-8ca1773a-0045-11e8-9d3f-17e1ff4234f6.jpg)

**Expected result:**

**Reproduces how often:**
100

### Brave Version

**about:brave info:**
 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**
yes

**Comment by luixxiul** [comment]
Did you try disabling the shield?

**Comment by griefage** [comment]
that worked, thanks.
