### ISSUE TITLE
Zoom happens by itself

### ISSUE THREAD

**Issue by deitch** [brave/browser-laptop#1280]
Using brave on Mac (10.11.4). It often will zoom in or out on a page without my intending. It mostly seems to happen when I do one of the following. Assume that the active tab is the first one.

* Switch between tabs using ⌘-2 to the second tab and then ⌘-1 back to the first.
* Switch between brave and another app using ⌘-tab

I cannot reproduce it reliably enough to know if it zooms out/in when I am *leaving* the tab (i.e. ⌘-2) or *returning* to the tab (i.e. ⌘-1), but then I have to use the menu to select View->ActualSize.

Similarly, I cannot reproduce it reliably enough to know if it zooms out/in when I am *leaving* the window (i.e. ⌘-tab away) or when I am *returning* to brave (i.e. ⌘-tab to brave).

Either way, when I return to the window/tab, the content is zoomed in or out. Most of the time it is zoom-in, but sometimes zoom out.

Is there a way I can turn on some form of debugging for it to tell me what commands it is receiving and when?

**Comment by bbondy** [comment]
This is definitely a consequence of scrolling (or smooth scrolling slightly after you've stopped) and hitting Command.   We may want to disable this or try to tweak it more.

**Comment by bbondy** [comment]
Maybe keep enabled if possible for mouse but not for trackpads.

**Comment by deitch** [comment]
Ah, that is interesting @bbondy. You are saying because it switches in using ⌘-tab or ⌘-1, and might have my fingers on the trackpad scrolling, if there is a tiny overlap of time, it might be scrolling in? 

Is there a way to disable zoom-in/out using ⌘-scroll, or reduce sensitivity slightly?

**Comment by bbondy** [comment]
yep that's right. I noticed that Chrome doesn't have this ability but firefox does. This might be why.
Ideally we'd just disable for trackpads and allow for mice scroll button turning I think.
I'd also accept a patch for a pref.  Marking good-first-bug in case someone jumps in.

**Comment by deitch** [comment]
Or make it an option, or with a timeout. I like the timeout idea: no ⌘-scroll to zoom for 1-2 seconds after window gains focus.

I'd be happy to try a PR, cannot recall last time I did any Cocoa programming, but whatever. Send me a pointer to a starting point in the source to jumpstart me?

**Comment by bbondy** [comment]
We changed the scroll zoom shortcut to control so this shouldn't happen anymore on OS X.

**Comment by bbondy** [comment]
As of 0.9.2 (next release coming ~tomorrow)

**Comment by deitch** [comment]
Thanks @bbondy . I would have been happy to do a PR with a pointer in the right direction, but you beat me to it!
