### ISSUE TITLE
Theme color is displayed incorrectly due to transparency

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12803]
### Description
If a theme color is provided with an alpha transparency channel, we preserve that transparency when displaying the theme color on the tab control background. This then causes the theme color to be blended with the tab bar background color, making the theme color match incorrectly.

### Steps to Reproduce

  1. Visit apple.com
  2. Observe tab theme color when tab is active
  3. Observe apple.com's navigation bar color

**Actual result:**
Colors do not match

**Expected result:**
Colors match

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.19 / 0.20

**Reproducible on current live release:**
👍

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
