### ISSUE TITLE
sometimes attention/time is logged within YT entry rather than creating a channel entry

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12816]
### Description

Sometimes when viewing media under TY, the time/attention is logged under the YT entry rather than creating a new ledger entry specifically for that particular channel.

### Steps to Reproduce

  1. launch `0.19.139` using a fresh brave profile
  2. visit `about:preferences#payments` and enable Brave Payments
  3. visit https://www.youtube.com
  4. search for `Datadash` and select the `Datadash` YT channel
  5. click on a random video and wait ~2min
  6. visit `about:preferences#payments` and you'll notice YT has logged ~2min rather than the channel being created under the ledger

**Actual result:**

Sometimes time/attention is added into the YT entry rather than creating a new ledger entry or adding the time/attention to the correct channel that's already listed.

Example of issue:

https://drive.google.com/file/d/1k_W9v-f24bK7h6sxkK79aqkCsPTkk5i3/view?usp=sharing

**Expected result:**

The time/attention should be added into the correct channel, or create a new entry if the channel doesn't already exists under the ledger table.

**Reproduces how often:**

I've managed to reproduce the issue 100% of the time using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.20.19 - Reproducible
> rev: 3d05e917690f302c677f4386870ec1721aa0ec01 
> Muon: 4.7.3 
> libchromiumcontent: 64.0.3282.99

**Reproducible on current live release:**

Yes, currently reproducible using `0.19.139`:

> Brave: 0.19.139 - Reproducible
> rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
> Muon: 4.7.2 
> libchromiumcontent: 64.0.3282.85 

### Additional Information

CCing @NejcZdovc

**Comment by arsalankhalid** [comment]
I really like this task, happy to take this on. May I assume it's still available? :)

**Comment by NejcZdovc** [comment]
tried to reproduce this on the latest master, but couldn't. @kjozwiak can you please re-check this one?

**Comment by NejcZdovc** [comment]
Closing this one. If we see this is happening again let's reopen it.
