### ISSUE TITLE
Mousepointer just dissappears.

### ISSUE THREAD

**Issue by HawsomeOslo** [brave/browser-laptop#1281]
Just happens every now and then, closing the application and starting it up again wont help, then after i've been using Chrome or any other browser without any problems for a while and try Brave again, its back. 
This happens only for the Brave area of the screen if i have several windows side by side, it only disappears when hovering over brave.

Running windows 10 x64 on surfacepro4 fully updated.
Would be nice with a "clean startup" option i could boot into to have all settings reset.

**Comment by luixxiul** [comment]
I don't have surface so I cannot confirm this. Would someone please try to reproduce this?

CC: @bbondy

**Comment by bbondy** [comment]
I haven't seen this but I'll keep an eye on it when using the Surface. I don't use it often though.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-investigation-how-responsive-is-brave-on-surface-4-pro/10224/2?u=suguru

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
