### ISSUE TITLE
[Windows, Dual Monitors] Disconnecting monitor - Brave stays at imaginary same position

### ISSUE THREAD

**Issue by JakobFerdinand** [brave/browser-laptop#12822]
# Repro Steps:

1. Connect a second monitor
2. Open Brave on second monitor (not the main monitor!)
3. Disconnect monitor

When I try to open Brave, it opens the window in the same place as on the disconnected monitor.
[Windows]+[left arrow/right arrow] does not work

I would expect the browser to open on the main monitor/display when the original one was disconnected.

This happens every time.

Name | Version 
-- | --
Brave | 0.19.139
libchromiumcontent | 64.0.3282.85
Muon | 4.7.2
Node.js | 7.9.0
OS Architecture | x64
OS Platform | Microsoft Windows
OS Release | 10.0.16299
rev | 99aa17d
Update Channel | Release
V8 | 6.4.388.20

**Comment by NejcZdovc** [comment]
We fixed couple fo things in 0.20. Currently 0.20 is in beta. Can you please check out if this is fixed for you in the latest beta? Thank you very much

You can find latest beta here https://github.com/brave/browser-laptop/releases/tag/v0.20.20beta

**Comment by bsclifton** [comment]
Closing as this should have been fixed.  @JakobFerdinand please try out the beta above and let us know if the issue persists.  We're hoping to ship this as a stable release soon 😄 👍

**Comment by JakobFerdinand** [comment]
Hello! 
I just tried to reproduce the bug as well with: 

Name | Version
-- | --
Brave | 0.20.20
V8 | 6.4.388.29
rev | df8eaf7
Muon | 4.7.3
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
libchromiumcontent | 64.0.3282.99

and with:

Name | Version
-- | --
Brave | 0.20.23
V8 | 6.4.388.40
rev | 5a2da66
Muon | 4.7.8
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

Unfortionally the bug is still there - in both Versions.
So the bug should be reopend again.
