### ISSUE TITLE
Javascript stack traces can contain unique identifiers in the path

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#12827]
### Description
see https://stats.brave.com/dashboard#crash/5a68a4ce83f757001fa70da8

**Comment by flamsmark** [comment]
@bridiver When do we get those stack traces — is there a step where the user decides to send it to us, where we could show a warning?

I'm amenable to the idea of trying to scrub things we know to be likely leaks. But I'm certain we can't find all of them — a stack trace always risks leaking private info.

**Comment by bsclifton** [comment]
@flamsmark crash reports can be disabled, but it's opt-out (advanced tab in prefs):
![screen shot 2018-03-09 at 11 46 37 pm](https://user-images.githubusercontent.com/4733304/37239198-33152f90-23f4-11e8-9067-e86fae8b4cdc.png)

We could add some UX to mention this concern

**Comment by flamsmark** [comment]
I think there are a couple of things going on here that we should address. Even if we don't add identifiers to crash reports, there's always a solid chance that they'll contain personal info — potentially info which could distinctively identify the users.

* * * * *

We should rename that toggle and add the information that folks need to make an informed decision. The reports aren't guaranteed to be anonymous, but they can be sent anonymously.

>"Anonymously send crash reports to Brave.*†"
…
>"†Brave doesn't send any additional information with crash reports. We try to remove potentially-identifying information from crash reports before they're sent, but we can't be sure of catching everything that might identify you. If we find something that looks identifying in a crash report we've received, we'll remove it." 

Then we need to actually follow through on that promise. That means:
- no IP (&c.) logs from crash report submissions
- scrub reports for obvious PII
- delete PII from a report whenever we stumble across it

* * * * *

Even with those protections, we should make sure that reports only get sent by users who have made that choice. IMO that means that we need an interactive prompt before sending the first crash report with [yes]/[no] choices and an [always] toggle. This is also something we could ask about in a first-run experience, along with telemetry. But crash reports are always much more potentially-identifying/personal, so more scrutiny applies.
