### ISSUE TITLE
after using 0.20.20 for a bit new tabs are blank, about:brave is missing info

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12828]
### Description
After using version 0.20.20 for some time my new tabs started showing up as blank (they're set to display the Dashboard per about:preferences) and the about:brave page didn't show information.

### Steps to Reproduce

  1. Use brave normally for some time (15-30 minutes maybe?)
  2. 
  3.

**Actual result:**
New tab does not display dashboard, about:brave does not display information:
![odd-new-tab](https://user-images.githubusercontent.com/28145373/35343466-bc323ad0-00f8-11e8-818d-32dea7ee0c15.gif)

Note: restart resolves this issue.

**Expected result:**
New tab should display per about:preferences (in my case show Dashboard) and about:brave should contain information.

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
Brave | 0.20.20
V8 | 6.4.388.29
rev | df8eaf7
Muon | 4.7.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.99

**Reproducible on current live release:**
unknown

**Comment by bsclifton** [comment]
I've had this happen on 0.19.x before at least once... closing and relaunching fixed it for me

@LaurenWags has this happened to you more than once?

**Comment by LaurenWags** [comment]
Happened once this morning, I saw it once before on 0.20.x but not again until today

**Comment by bsclifton** [comment]
I've been using 0.20.x for a while and haven't been able to reproduce this ☹️ Until we have more steps, I'd like to propose that we leave this open without a milestone attached.  What do you think, @LaurenWags?

**Comment by LaurenWags** [comment]
I think that sounds good @bsclifton - I've removed the milestone until we can determine additional information.

**Comment by LaurenWags** [comment]
Reproduced on 0.20.42 but no clear steps yet.

**Comment by LaurenWags** [comment]
+1 from @mandar-brave on 0.20.42. Also seeing that when trying to access release notes when about:brave is like the above, they result in 404.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/back-button-inconsistently-not-functional-after-browser-update-restart/16140

**Comment by LaurenWags** [comment]
+1 from @bbondy
