### ISSUE TITLE
Add option for no tab preview delay

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#12823]
### Description
Opened this per discussion with @cezaraugusto and @bradleyrichter in #9887 

The new setting in 0.20.x to setting tab preview delay should have an option to have no tab preview because some people like me are used with the old timing (no timing) and using the short timing is still to slow. Fells like i waist a couple seconds every time I want to use that previews. The no delay option should be set as default for people coming from 0.19.x and upgrading.

![image](https://user-images.githubusercontent.com/25466657/35341612-5a162784-0126-11e8-8c99-454734771d34.png)

### Steps to Reproduce

  1. Go to about:preferences#tabs in 0.20.x
  2. Click on the drop down for "Time to wait before previewing a tab"

**Actual result:**
No option to have no delay
![image](https://user-images.githubusercontent.com/25466657/35341746-afa1b92a-0126-11e8-9471-e8979014e5c0.png)

**Expected result:**
Should be an option to have no delay at all

**Reproduces how often:**
All the time

### Brave Version

**about:brave info:**
 
Brave: 0.20.20 
V8: 6.4.388.29 
rev: df8eaf7e05a802d1e49c189c67ad0c8a6c554db2 
Muon: 4.7.3 
OS Release: 10.0.16299 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.99

**Reproducible on current live release:**

No not yet

### Additional Information

cc @cezaraugusto and @bradleyrichter

**Comment by cezaraugusto** [comment]
thanks @Jacalz! I'm closing this and re-opening #12823 with your claim so it's easier for QA
