### ISSUE TITLE
Crash report doesn't send crash ID on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12838]
### Description
Crash report doesn't send crash ID on Windows

### Steps to Reproduce
  1. Follow test plan from https://github.com/brave/browser-laptop/issues/12772
  2. Generate a crash
  3. Shows `Uploaded Crash Report ID OK` doesn't generate an actual ID

**Actual result:**
Crash report doesn't send crash ID on Windows

**Expected result:**
Should generate crash ID and send it

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.144
-- | --
rev | 4e4470d
Muon | 4.7.4
libchromiumcontent | 64.0.3282.99
V8 | 6.4.388.29
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

**Comment by bridiver** [comment]
actually this is an issue for stats.brave.com because the crash server generates the ID. cc @aekeus

**Comment by bridiver** [comment]
I'm not going to close this yet because it could still be a metadata issue with the version we send, but this shouldn't block release

**Comment by bridiver** [comment]
we may want to block on this after all. I'm looking into it now because it looks like a metadata issue

**Comment by bridiver** [comment]
fixed in https://github.com/brave/muon/commit/dcae63204172317a8bede807c820896dded8c486

**Comment by srirambv** [comment]
Working on 0.19.146. Able to generate crash ID and verify

**Comment by kjozwiak** [comment]
For the following OS, I ensured that:
* `chrome://crash` produced a crash report under `chrome://crasehs` that included a `crash id`
* visiting stats.brave displayed the crash including the `crash id`

OS:

* Win 10 Pro x64 - PASSED
* Win 10 Pro x86 - PASSED

**Comment by kjozwiak** [comment]
@bridiver it looks like reporting doesn't really work under Win 7. When you crash the browser via `chrome://crash`, you'll notice that the crash report is grey and will never get sent out. Even when you manually click on "Send", restarting the browser will display the "Send" button even though you've already clicked on "Send". The other thing you'll notice is that it only generated a `local crash id`.

Example:

<img width="527" alt="screen shot 2018-01-26 at 10 44 41 am" src="https://user-images.githubusercontent.com/2602313/35447876-c83004cc-0286-11e8-8692-8a0666c46bc7.png">

![win7crashes](https://user-images.githubusercontent.com/2602313/35447949-f2fda56a-0286-11e8-9ea3-0522cf83263a.gif)
