### ISSUE TITLE
Decentraleyes

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#12836]
https://community.brave.com/t/stop-tracking-through-centralized-content-delivery-plus-speed-up-brave/1748
https://chrome.google.com/webstore/detail/decentraleyes/ldpochfccmkkmhdbclfhpagapcfdljkj

**Comment by luixxiul** [comment]
It seems that resources loaded via Decentraleyes are not loaded when subresource integrity attributes are enabled: https://github.com/Synzvato/decentraleyes/issues/212

**Comment by flamsmark** [comment]
I think we should work to avoid this bug. If our version of the resource matches the SRI hash, we should load it. If our doesn't match we should get the remote resource and see if it matches. If neither resource matches, the site's broken either way. If the remote resource matches but ours doesn't, we load the remote resource and think about what else to do.

Should we cache the remote resource and use it without another remote request when we se the same SRI hash for that resource? Should we worry about our own store being out of date? Seems like something worth capturing in opt-in telemetry.

**Comment by bsclifton** [comment]
+1 from @androiduser9 via https://github.com/brave/browser-laptop/issues/14624
> Idea:
>
> Just like Brave implements HTTPS Everywhere functionality, it would be interesting if it could implement by default Decentraleyes functionality, the latter is an extension that blocks requests for libraries from CDNs (think google libraries, cdnjs, ...) and serves them locally to prevent tracking by CDNs.

**Comment by bsclifton** [comment]
Decentraleyes should be available for use in [brave-core](https://github.com/brave/brave-browser)
