### ISSUE TITLE
Move Ledger Deleted Sites List to a new dialog

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#12833]
As a user, I need more intuitive access to the sites I may have deleted from my Brave Payments list.

Currently, users are confused by the action of deletion and the location in prefs where these sites are managed.

A new link will be added to the bottom text navigation in the ledger list as shown:
(Show Deleted Sites)
![image](https://user-images.githubusercontent.com/13509546/35352959-7a605428-00fa-11e8-90b6-0b315ed76ca6.png)

Clicking this link will open a dialog with scrolling content:
![image](https://user-images.githubusercontent.com/13509546/35352989-9bc2dd70-00fa-11e8-8f92-bff57b8b93bb.png)

The scrolling dialog will use the same list that is already maintained within the Prefs/Shields list. 

A new feature with button "Clear All" will be added to assist in resetting the deleted sites list if needed.

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.

**Comment by kjozwiak** [comment]
Also checked the following under Linux 17.10 x64:

* have around 20 removed websites being listed under `about:preferences#shields` using `0.20.46`
* update brave to `0.21.16` a7bed47f55863b9f48e5ce31bcaf8c6ee21c10d5
* ensure that all the websites being listed under `about:preferences#shields` have been moved into the `Deleted Sites` within `about:preferences#payments`
