### ISSUE TITLE
Other tabs are forced to pinned-tab size after closing tab that used to be pinned

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12837]
### Description

When you're closing a tab that was perviously pinned and has been unpinned, the tab next to it will quickly appear as a pinned tab until the mouse is moved. Please see the GIF example below.

You'll also see the following error message in the terminal but this also appears in `0.19.139` which is the latest released version:

`[31659:31659:0124/195057.560341:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error.", source: chrome://brave/usr/lib/brave-beta/resources/app.asar/app/extensions/brave/index.html (0)`

### Steps to Reproduce

  1. launch `0.20.20`
  2. open a new tab and visit motorsport.com (make sure it's the only tab opened)
  3. open a new tab and visit reddit.com (you should now have two tabs opened)
  4. pin the second tab (reddit.com)
  5. unpin reddit.com and close the tab
  6. you should have a single tab left opened (motorsport.com)
  7. open a new tab and visit reddit.com (you should now have two tabs opened)
  8. pin the second tab (reddit.com)
  9. unpin reddit.com and close the tab (don't move your mouse once you click close)

**Actual result:**

![tabbingissue](https://user-images.githubusercontent.com/2602313/35365048-6df5074c-0140-11e8-895e-956170974ec8.gif)

**Expected result:**

The second tab shouldn't appear as pinned when the first tab that used to be pinned is closed.

**Reproduces how often:**

100% reproducible using the above STR mentioned above.

### Brave Version

**about:brave info:**

> Brave: 0.20.20 
> V8: 6.4.388.29 
> rev: df8eaf7e05a802d1e49c189c67ad0c8a6c554db2 
> Muon: 4.7.3 
> libchromiumcontent: 64.0.3282.99

**Reproducible on current live release:**

I couldn't reproduce this under `0.19.139` after about 5 minutes of trying. Easily reproducible using `0.20.20`.

### Additional Information

CCing @petemill

**Comment by petemill** [comment]
I can reproduce in 0.20. I can**not** reproduce on master / 0.22 / 0.21, so I'll look for a fix directly to 0.20.

**Comment by petemill** [comment]
Fixed in #11436
