### ISSUE TITLE
Ad-Removal Should Collapse/Remove Ad-Containers on YouTube

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12845]
### Description
Ad-containers often exist after ad-removal, and may take up a large amount of screen-space.

### Steps to Reproduce
1. Go to youtube.com

**Actual result:**
Large empty region at the top of the page.

**Expected result:**
No empty region should remain after ad-removal.

**Reproduces how often:**
100%

### Brave Version
0.19.139

**about:brave info:**
``` 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64
```

**Reproducible on current live release:**
Yes.

### Additional Information
![image](https://user-images.githubusercontent.com/815158/35412796-03ad297a-01e3-11e8-9cb5-0eeaca5b5864.png)

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
