### ISSUE TITLE
Bookmarks: Cannot use 'Other Bookmarks' Folder, only use 'Bookmarks Toolbar'

### ISSUE THREAD

**Issue by theangellmethod** [brave/browser-laptop#12842]
I have searched for similar issues but can't find anything related.

### Description
When I try to save bookmarks, they will only save under the bookmarks toolbar.  I can see the 'other bookmarks' folder but cannot add new links to it, cannot drag and drop links from the bookmarks toolbar folder into it, and cannot create subfolders in it.  

### Steps to Reproduce

  1. Install Brave
  2. Try to save any link to the 'Other Bookmarks' folder.
  
**Actual result:**

All bookmarks will only go in the 'Bookmarks Toolbar' folder.

**Expected result:**
Able to use the 'Other Bookmarks' folder and to be able to create other folders (all other folders will currently be added to 'Bookmarks Toolbar.'

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by NejcZdovc** [comment]
can you please try it with our latest beta version 0.20 where we fixed other bookmarks.

You can find it here https://github.com/brave/browser-laptop/releases/tag/v0.20.21beta

Thank you
