### ISSUE TITLE
put cursor in 'Search' box when opening LastPass

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12843]
### Description
When you click on the extension icon for Last Pass the cursor is not put in the 'Search' box. User requested this via twitter: https://twitter.com/indicru/status/955943235569856513

### Steps to Reproduce

  1. Have LastPass enabled and be logged in.
  2. Click on extension icon.
  3.

**Actual result:**
Cursor is not in 'Search' box.

**Expected result:**
Cursor should be in search box so you can begin typing right away. (this is how it works in Chrome)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.19.145

**Reproducible on current live release:**
Yes

**Comment by bbw22** [comment]
I agree with this one. In FireFox this is how it works. The functionality is hit or miss in other browsers.

**Comment by ocramc** [comment]
Would extend this to the login box within the extension and the 2FA popup - both have focus set on relevant textbox in Chrome but not Brave

**Comment by bsclifton** [comment]
@LaurenWags is this fixed with brave-core?
