### ISSUE TITLE
Cursor clicks occasionally don't match UI

### ISSUE THREAD

**Issue by CrisBRM** [brave/browser-laptop#12848]
Occasionally, where the mouse cursor is won't represent the element that's selected (not limited to UI).

![screenshot from 2018-01-25 22-24-54](https://user-images.githubusercontent.com/9098352/35415850-fb350f1a-021e-11e8-8497-f255c827a66c.png)

Note where the cursor is and what is being selected (the scrollbar).
Does not happen reliably. Simply put, even if I were to go to https://www.sharelatex.com/learn/Paragraphs_and_new_lines there's a very high likelihood that the bug won't happen, but it happens often enough that I'm opening a bug report.

### Brave Version (installed from snap)

Brave | 0.19.139
-- | --
rev | 99aa17d
Muon | 4.7.2
libchromiumcontent | 64.0.3282.85
V8 | 6.4.388.20
Node.js | 7.9.0
Update Channel | Release
OS Platform | Linux
OS Release | 4.14.14-47.current
OS Architecture | x64

**Comment by Liunkae** [comment]
@CrisBRM Do you happen to have strict site isolation enabled? (Settings > Security > Strict Site Isolation) If so, it could be related to #12638.

**Comment by bsclifton** [comment]
@CrisBRM can you provide more info about your window manager? (including version - are you just using Gnome?) I suspect there's an issue there

**Comment by MarkStair** [comment]
I get same or similar issue.  Brave will preview a tab as you hover over it but doesn't actually select the tab.  This makes the tab switching clunky especially when you have way too many tabs like I do.

**Comment by bsclifton** [comment]
@MarkStair that is expected behavior (at least, with default profile). You can turn off that behavior by going into preferences and turning off `Show tab previews on hover`
![tab-preview](https://user-images.githubusercontent.com/4733304/43737329-cba8632a-9975-11e8-8100-347dba3c05a3.png)

**Comment by bsclifton** [comment]
Since there's no information about the originally reported issue, I'm going to close this issue as stale

@MarkStair if you're experiencing the app not responding properly to where the mouse is, please re-open this issue and provide some more info 😄 ex: window manager on Linux? or DPI setting (100%? 150%?) on Windows

**Comment by CrisBRM** [comment]
Sorry.
Brave settings were the default ones. Window manager is the one used by Solus at the time of opening the issue, so, Mutter.
