### ISSUE TITLE
instagram photos blocked

### ISSUE THREAD

**Issue by Licenser** [brave/browser-laptop#1284]
Taking this as an example:

https://www.instagram.com/p/BD8ZgmeP0VL/

The photo itself gets blocked, my guess is that it has to do with it being served throguh fb-cdn instead of directly.

**Comment by diracdeltas** [comment]
Seems to work for me but i see the photo coming from https://scontent-iad3-1.cdninstagram.com/t51.2885-15/e35/12424427_944581495640659_1502023824_n.jpg instead of fb-cdn. can you copy-paste the exact link that is being blocked?

**Comment by Licenser** [comment]
thanks for the quick reply :)

the blocked links are:

`https://instagram.ftxl1-1.fna.fbcdn.net/t51.2885-19/s150x150/11909106_492705750901224_317524674_a.jpg`
and 

`https://instagram.ftxl1-1.fna.fbcdn.net/t51.2885-15/e35/12424427_944581495640659_1502023824_n.jpg?ig_cache_key=MTIyMzk2NTM5MDIzMzYxNzczOQ%3D%3D.2`

The image link itself is:

```html
<img alt="My new bus route takes me by the Troll in the morning. Nice to see it without the crowd!" class="_icyx7" id="pImage_0" src="https://instagram.ftxl1-1.fna.fbcdn.net/t51.2885-15/e35/12424427_944581495640659_1502023824_n.jpg?ig_cache_key=MTIyMzk2NTM5MDIzMzYxNzczOQ%3D%3D.2" data-reactid=".0.1.0.0.0.$https=2//instagram=1ftxl1-1=1fna=1fbcdn=1net/t51=12885-15/e35/12424427_944581495640659_1502023824_n=1jpg?ig_cache_key=0MTIyMzk2NTM5MDIzMzYxNzczOQ%3D%3D=12.0.0.$pImage_0">
```

**Comment by franckuestein** [comment]
The photo that you shared is working fine for me, too.
Brave 0.8.3

**Comment by Licenser** [comment]
This is how it looks for me:
![image](https://cloud.githubusercontent.com/assets/119093/14397325/0701c1b4-fddd-11e5-9dbc-df429fb85816.png)

My only thought is that it could be location based? I'm sitting in Germany so they might choose a different CDN? I'll try that with going through a VPN to the US and get back to you in a few minutes.

**Comment by Licenser** [comment]
Yes indeed,
once I go through a VPn with the endpoint in the US the photo shows, so it sees to be locaiton dependant.

**Comment by TheFallenOneGOTH** [comment]
@Licenser I don't think location matters, I am having the same problem viewing the photo in Brave 0.9.0 and I am in the U.S. I did find a workaround for this until the Brave team fixes this bug: I changed my ad settings to "Allow ads and tracking" in the Bravery menu and the photo shows normally.

**Comment by Licenser** [comment]
Yea it's not a huge problem for me, I just noticed it and thought to report it :). Fortunately I barely ever use instagram so I can ignore it without much bother. Perhaps it's not location but ISP based? (just a thought) there must be some logic wich decides what CDN serves the content.

**Comment by diracdeltas** [comment]
I started seeing this too; pushing a fix now

**Comment by Licenser** [comment]
Thank you! :)
