### ISSUE TITLE
Geolocation broken on 0.19.146

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12857]
### Description
Geolocation broken on 0.19.146

### Steps to Reproduce

  1. Clean install 0.19.164
  2. Visit https://browserleaks.com/geo
  3. Click allow in notification bar, doesn't show the location coordinates

**Actual result:**
![geoloc](https://user-images.githubusercontent.com/17010094/35425605-f844baae-0281-11e8-8696-becde4a7d7a3.gif)

**Expected result:**
Should show geo location coordinates

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.146
-- | --
rev | 1345885
Muon | 4.7.6
libchromiumcontent | 64.0.3282.119
V8 | 6.4.388.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/12855

**Comment by srirambv** [comment]
Works on 0.19.147
