### ISSUE TITLE
NETWORK PRINTER 

### ISSUE THREAD

**Issue by MikeKel** [brave/browser-laptop#1285]
HI, I'm running windpoze 7 and not getting it to print to my network printer.
 Printer is working fine from any other program on the same box.
     Love brave so far, but I need printouts to work.
 Thank you for your efforts :)
     Mike

**Comment by luixxiul** [comment]
@bbondy Hasn't this already been implemented?

**Comment by bbondy** [comment]
I think this should be working now, please re-open if not.
