### ISSUE TITLE
Always deny doesn't let stream on Netflix and doesn't go full screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12856]
### Description
Always deny doesn't let stream on Netflix

### Steps to Reproduce

  1. Clean install 0.19.x build
  2. Set auto play to `Always Deny`
  3. Visit Netflix, load a video, nothing happens shows a blank black screen
  4. Hover over video controls not shown. Intuitively click where the controls are they show up. 
  5. Doesn't enter full screen when click on  

**Actual result:**
Always deny doesn't let stream on Netflix and doesn't go full screen

**Expected result:**
Should show the video controls and should be allowed to go full screen when video is played

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.19.146
rev | 1345885
Muon | 4.7.6
libchromiumcontent | 64.0.3282.119
V8 | 6.4.388.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
Full screen is intermittent sometimes the video goes full screen on double click sometimes it doesn't
cc: @darkdh @bbondy

**Comment by darkdh** [comment]
fullscreen issue should be in 0.19.147

**Comment by srirambv** [comment]
Same issue on Twitch as well. Keeps showing the loading spinner giving indication that the video is buffering when it isn't. 
https://youtu.be/5j-iiF9B_AA
