### ISSUE TITLE
inspect element on a tab but the first shows developper tools for the first tab

### ISSUE THREAD

**Issue by Licenser** [brave/browser-laptop#1286]
When using the context menues 'inspect element' anything but the first tab the developper tools of the first tab are used instead of the tools from the current tab. This leads to a wrong element showing. I am not 100% sure how it is selected but it seems to be something as close es possible on tab 1.

To reproduce: 

* Open tab 1 brows a webpage
* Open tab 2 brows to a *different* webpage
* Go to tab 2
* Choose any element on the page and use the context menue (right click) then pick `inspect element`
* Go the the newly opened Developper Tools
* Check the window title bar for the url (it is the url of the 1st tab)
* Check the content of `Elements` in the Developper Tools (it is the html from the 1st tab)

**Comment by bbondy** [comment]
Was fixed here:
https://github.com/brave/browser-laptop/issues/1279

Will be in 0.9.0

**Comment by Licenser** [comment]
wehhhh thanks! :) that was quick sorry about the apearent double entry I didn't find a related ticket.

**Comment by bbondy** [comment]
NP we appreciate the reports. Thanks!
