### ISSUE TITLE
Extension: Cisco WebEx Extension

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12877]
https://chrome.google.com/webstore/detail/cisco-webex-extension/jlhmfgmfgeifomenelglieieghnjghma

![image](https://user-images.githubusercontent.com/815158/35469225-93c94502-02f6-11e8-8f6a-f234b8ea7c51.png)

Cisco's WebEx extension _is not_ presently supported in Brave. To gauge the effort, I took some time this evening to run through [the side-loading process](https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d) with [a user on Twitter](https://twitter.com/BraveSampson/status/957115151425163265). On the same Twitter thread, @diracdeltas shared [coverage of _now-patched_ vulnerabilities](https://twitter.com/bcrypt/status/957117019245064193) in the Cisco WebEx Extension that we should be mindful of moving forward.

We started by side-loading through the Honey extension directory. After restarting Brave we confirmed that the Cisco WebEx Extension was listed in _about:extensions_. In spite of our success in loading the extension, the user was unable to successfully spawn a call from the browser.

Our next step was to inspect the _background page_ for any obvious errors. The following screenshot is the console for the _generated background page_ for Cisco's WebEx Extension:

![image](https://user-images.githubusercontent.com/815158/35469302-ffb12522-02f7-11e8-92d7-2007d9f7ceea.png)

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄

**Comment by vernonk** [comment]
For what it's worth, I'm using latest Brave on Chromium and still am unable to join a WebEx meeting within Brave using the standard approach. Depending on WebEx version (which luckily I have this option) there is a "Launch in Browser" link on the join/start page. This approach *does* work for attending and running WebEx meetings in-browser.
