### ISSUE TITLE
Bookmarks toolbar unresponsive after importing large number of bookmarks.

### ISSUE THREAD

**Issue by binarysubstrate** [brave/browser-laptop#12871]
**Did you search for similar issues before submitting this one?**
Similar to #7240 (Closed, but not resolved in version 19.)
#4044 (Open, little info provided.)
#5404 (Open, but specific to favicons.)

**Describe the issue you encountered:**
The bookmarks toolbar unresponsive after importing large number of bookmarks.  (~1200)

- Clicking  the "Imported" folder causes the browser to become unresponsive.
- And simply dragging a new bookmark to the toolbar also causes this.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
Windows 10 x64

**Brave Version (revision SHA):**
Brave	0.19.139
rev	99aa17d

**Steps to reproduce:**
- Import data from Firefox 57.0.4 (64-bit) including about 1000 bookmarks.
- Enable the bookmarks toolbar.
- Click the "imported" folder. Or try to create a new bookmark on the toolbar.

**Actual result:**
Browser becomes unresponsive for 10-20 seconds.

**Expected result:**
Imported bookmarks should not impact browser performance.

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Other browser info:**
Brave	0.19.139
rev	99aa17d
Muon	4.7.2
libchromiumcontent	64.0.3282.85
V8	6.4.388.20
Node.js	7.9.0
Update Channel	Release
OS Platform	Microsoft Windows
OS Release	10.0.16299
OS Architecture	x64

**Comment by luixxiul** [comment]
Hi, that performance issue should be fixed on 0.20.x releases. thanks!

**Comment by bsclifton** [comment]
Closing since 0.20.x has been released.  Please re-open if you still find the performance to be bad 😄
