### ISSUE TITLE
Printing doesn't work when Strict Site Isolation is enabled

### ISSUE THREAD

**Issue by b-xk** [brave/browser-laptop#12879]
Have you searched for similar issues? Yes

### Description
File - Print - PDF - Save As PDF results in Blank pages.

### Steps to Reproduce
Please add a series of steps to reproduce the problem. See https://stackoverflow.com/help/mcve for in depth information on how to create a minimal, complete, and verifiable example.

  1.  Navigate to https://github.com/EvidentSecurity/custom_signatures/blob/cfca8dd63477462e03e37b99483826837a25f6d6/README.md
  2.  File - Print... - PDF - Save As PDF

**Actual result:**
7 blank pages  (PDF container document created, no content)

**Expected result:**
7 pages with content

**Reproduces how often:**
100%

No Errors shown in Developer Console.

### Brave Version

**about:brave info:**
 Brave: 0.19.147 
rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
Muon: 4.7.6 
libchromiumcontent: 64.0.3282.119 
V8: 6.4.388.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.4.0 
OS Architecture: x64

**Reproducible on current live release:**
Is this a problem with the live build? Yes

### Additional Information
[testprint.pdf](https://github.com/brave/browser-laptop/files/1670262/testprint.pdf)
Any additional information, related issues, extra QA steps, configuration or data that might be necessary to reproduce the issue.

**Comment by luixxiul** [comment]
Hi, do you experience the issue on other files consistently?

**Comment by b-xk** [comment]
Hi @luixxiul - Yes, it is consistently reproducible, and I have worked out the root-cause.
The issue occurs only if the 'Strict Site Isolation' option is enabled in the Security Preferences.

If you Disable 'Strict Site Isolation' option, then the page saves-as -PDF correctly.

**Comment by socketbox** [comment]
For what it's worth, confirming that this is an issue with an earlier version of macOS and a later version of Brave:

Name | Version
-- | --  
Brave | 0.22.13
V8 | 6.5.254.41
rev | a8cfb16
Muon | 5.1.2
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181
