### ISSUE TITLE
Video frame overlaps when a new window is moved to an external monitor

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12870]
### Description
Video frame overlaps when a new window is moved to an external monitor

### Steps to Reproduce
  1. Clean install 0.19.147
  2. Play video on Netflix on primary screen do not enter full screen
  3. Create a new browser window and move it to the extended screen
  4. Move back the new window to primary screen and move it back to extended screen
  5. Video frame is frozen to original size and the new frame size overlaps

**Actual result:**
Video frame overlaps when a new window is moved to an external monitor
https://youtu.be/5MfipO9NCw0

**Expected result:**
Moving windows between screen should not affect video frame size

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.147
-- | --
rev | f1b90a3
Muon | 4.7.6
libchromiumcontent | 64.0.3282.119
V8 | 6.4.388.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
May be not noticeable on the video
cc: @bsclifton @petemill

**Comment by EmdaviesSeneca** [comment]
Hello,
I have been looking into this bug. I will reply here in the coming days with my findings. I am leaving this comment as a (though belated) indicator that I am working on this bug.

**Comment by bsclifton** [comment]
Closing as this should be fixed with our [Developer channel build](https://brave.com/download-dev). (We don't have Widevine support in the packaged build yet, so there isn't a quick way to confirm)
