### ISSUE TITLE
Huobi not loading api.huobi.com and you can't login

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#12886]

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/adblock-lists/commit/5cae2aebb14576daac5531553b094ff0ff375a68

**Comment by bsclifton** [comment]
No QA needed w/ regards to 0.20.x since this is already live (see comment https://github.com/brave/adblock-lists/commit/5cae2aebb14576daac5531553b094ff0ff375a68#commitcomment-27158165)
