### ISSUE TITLE
Feature request: new Private window

### ISSUE THREAD

**Issue by mlogic** [brave/browser-laptop#1288]
With Firefox I always keep at least two windows open: one for non-private, one for private. All new tabs opened in the private window are automatically private. I haven't yet found a way with Brave to do this. Please consider add a new feature for opening a Private window, in which all new tabs are automatically private. Thanks.

**Comment by luixxiul** [comment]
ref: #597

**Comment by luixxiul** [comment]
Duping to #597

**Comment by bbondy** [comment]
I think this one is different it is for private window only.

**Comment by alexwykoff** [comment]
Shipped

**Comment by luixxiul** [comment]
This was not shipped. We have shipped Private tab, not Private Window (where every tab should be opened in a private mode and no browsing data is saved).

**Comment by bbondy** [comment]
This is still pretty useful in that a user sometimes just wants a complete workspace (window) to perform private actions and then close it all in one swoop.  No risk of entering basic browsing mode from it.  It's a bit of a different use-case than our per tab private browsing which is mostly jus for a single page load and then you want to close it.

**Comment by aaronovz1** [comment]
I also think this would be useful. Even as basic starting point it would be nice to have an option in the File menu for "New Private Window" which launches a private window. The user can then open private or non-private tabs after that. I believe this is how Chrome works. Right now it's a little annoying to open a new window, then make a private tab, then close the default non-private tab that comes default with the new window.

**Comment by bsclifton** [comment]
Marking as `wontfix` and closing. When we move to Brave Core (forked Chromium UI instead of Electron/Muon), we'll get this behavior by default
