### ISSUE TITLE
different colored Brave logos on MacOS installer

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12906]
### Description
When installing on MacOS the Brave icons are two different colors.

### Steps to Reproduce

  1. Download 0.20.23
  2. Double click .dmg file
  3.

**Actual result:**
Brave icons have different colors:

<img width="683" alt="screen shot 2018-01-29 at 9 49 36 am" src="https://user-images.githubusercontent.com/28145373/35517761-6c2adc7a-04dd-11e8-9292-daf831c425a6.png">

**Expected result:**
Icons should be the same color

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.23
V8 | 6.4.388.40
rev | 5a2da66
Muon | 4.7.8
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
no

**Comment by darkdh** [comment]
@bradleyrichter can you provide images resources for 
https://github.com/brave/browser-laptop/blob/master/res/background.png 
and https://github.com/brave/browser-laptop/blob/master/res/brave_splash_installing.gif?

**Comment by bradleyrichter** [comment]
new MacOS install folder BG image that uses our new grey values which coincide with the new logo color:
![background_brave_2018](https://user-images.githubusercontent.com/13509546/35540088-11dcf1b4-0509-11e8-97d1-fd547a7c2121.png)

**Comment by LaurenWags** [comment]
MacOS 0.20.27: 
<img width="619" alt="screen shot 2018-01-30 at 9 13 48 am" src="https://user-images.githubusercontent.com/28145373/35570702-f2e2a96c-059d-11e8-9cb9-1718c86e7134.png">

**Comment by srirambv** [comment]
Any good installer splash screen for Windows @bradleyrichter  😁

**Comment by bradleyrichter** [comment]
Do we have more options besides the animated gif?

**Comment by srirambv** [comment]
Nope. Not until #432 is implemented giving a setup screen.
