### ISSUE TITLE
Bookmark star is filled when upgrading to 0.20.23

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12903]
### Description
Bookmark star is filled when upgrading to 0.20.23

### Steps to Reproduce
  1. Clean install 0.19.147  
  2. Visit brianbondy.com in a new tab
  3. Upgrade to 0.20.23
  4. Site shows as bookmarked but doesn't list in about:bookmarks
  5. Clicking on the bookmark icon shows empty fields 

**Actual result:**
![bookmarkadd1](https://user-images.githubusercontent.com/17010094/35510872-dc32cdb0-051f-11e8-9532-9e3185bda98b.gif)

**Expected result:**
Should not show the bookmark filled icon upon upgrade until the site is actually bookmarked

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.23
-- | --
V8 | 6.4.388.40
rev | 5a2da66
Muon | 4.7.8
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
No

### Additional Information
cc: @petemill @NejcZdovc

**Comment by LaurenWags** [comment]
Reproduced on MacOS

**Comment by bbondy** [comment]
is this only for the already opened tab? wondering how bad the bug is if we ship with it?

**Comment by LaurenWags** [comment]
@bbondy I created a profile with 0.19.147 and opened a couple of windows with some tabs in each window. I then opened 0.20.23 using that profile and each tab (when clicked on) showed the star as filled in: 
![12903](https://user-images.githubusercontent.com/28145373/35537500-6b86406c-0518-11e8-9fbb-ec83466e2e6a.gif)

**Comment by cezaraugusto** [comment]
self note: we're caching locations in bookmarks, which is why you don't see it in bookmarks page but still makes a valid key (turning bookmark button on)

**Comment by bbondy** [comment]
@LaurenWags @cezaraugusto is it your opinion we should block on this bug?
For example if you close and open the tab, is the problem gone? If you close the browser and open another time is it gone?

I'm of the opinion if the user can easily work around it and it only happens once then we don't need to block on it.

**Comment by LaurenWags** [comment]
Close/reopen of Brave did not resolve the issue (star was still filled in)

**Comment by kjozwiak** [comment]
Great find @srirambv & @laurenwags!
