### ISSUE TITLE
Debug window opened when upgrading the browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12901]
### Description
Debug window opened when upgrading the browser

### Steps to Reproduce
  1. Upgrade from 0.19.147 to 0.20.23
  2. debug window is opened which is unresponsive
  3.

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/35509937-2d7647b4-051c-11e8-9f6e-2ed4cbf2aa2b.png)

**Expected result:**
Should not open the debug window

**Reproduces how often:**
Not sure happened after importing bookmarks to test  #12768 

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by kjozwiak** [comment]
@NejcZdovc noticed a debug window when importing `Bookmarks` as well. Will this PR fix that instance as well?

<img width="1086" alt="screen shot 2018-01-29 at 4 40 45 pm" src="https://user-images.githubusercontent.com/2602313/35535966-564acc0e-0513-11e8-9b92-3a181cddc809.png">
