### ISSUE TITLE
x64 installer blurry on high resolution displays

### ISSUE THREAD

**Issue by mikemaccana** [brave/browser-laptop#12905]
Instaling Brave 0.19.147 on a Surface Book, the installer is blurry:

![image](https://user-images.githubusercontent.com/172594/35517130-75b0e208-0505-11e8-9f72-00c1b62e975b.png)

Installing on any high res display should reproduce problem.

**Comment by bsclifton** [comment]
This should be addressed in our [Developer release build](https://brave.com/download-dev) 😄
