### ISSUE TITLE
Need onboarding page explaining ad replacement

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1291]
Not all users who install Brave will have read enough of our blog posts / website to understand that ad replacement is going to happen. They need to be aware of it and be given a chance to turn it off if they don't find it is in their best interest.

A friend today gave me this feedback: 

> I just installed Brave. When I installed it, it didn't tell me it was going to replace ads. It didn't issue a popup or any indication of what was going to happen to content I was browsing. 
> The download page clearly states "The new Brave browser automatically blocks ads and trackers, making it faster and safer than your current browser." The keyword here is "BLOCKS."
> Yet on installation, the Bravery > Replace ads checkbox was checked by default. I didn't consent to that. On the first page I loaded, I did get the "Faster safer ads coming to this space" message with a link, so that was a good thing.

I think we should have a popup page when the browser is first installed, which has a walk-through of ad replacement and how to pick other options in the Bravery menu.

@bradleyrichter thoughts?

**Comment by weems** [comment]
Would it be a good idea to have a checkbox in installer or some way to control if you want to see it. Veteran Users Upgrading to a new version likely will not want to see this on every install.

**Comment by diracdeltas** [comment]
> Would it be a good idea to have a checkbox in installer or some way to control if you want to see it. Veteran Users Upgrading to a new version likely will not want to see this on every install.

It wouldn't be shown on updates.

**Comment by rohanthacker** [comment]
This was an issue I face too, Although I heard and read alot about it on twitter. It wasn't  obvious what the fuss was about.
Then I stumbled upon the Brave Logo in the top right which had all the information and made me really happy :)

I would suggest that, this be as simple as informing the user of the brave logo button (top-right button) and allow them to discover the features that brave has to offer.

**Comment by luixxiul** [comment]
I'm going to close this for now as `about:welcome` explains that ads are blocked, and the browser currently blocks ads by default. ie. this argument is not valid:

> The keyword here is "BLOCKS." Yet on installation, the Bravery > Replace ads checkbox was checked by default

**Comment by luixxiul** [comment]
Also we have a awesome FAQ originally written by @lukemulks

https://community.brave.com/t/all-about-ad-blocking/10004 👏
