### ISSUE TITLE
Empty Ad Containers on Yahoo!

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12918]
### Test plan
See https://github.com/brave/browser-laptop/pull/12964

### Description
Brave is successfully blocking ads and trackers, but isn't removing empty ad containers. The following screenshot was procured from [@spencernoon's tweet](https://twitter.com/spencernoon/status/958113062824923136):
![image](https://user-images.githubusercontent.com/815158/35542120-eb637e48-0523-11e8-9aa6-d46d023f1e25.png)

### Steps to Reproduce
1. Navigate to https://yahoo.com

**Actual result:**
Empty ad containers are visible

**Expected result:**
Empty ad containers should be hidden

**Reproduces how often:**
Always

### Brave Version
0.19.147

**Reproducible on current live release:**
Yes

### Additional Information
There are additional ad containers as you browse the Yahoo! site.

Related to #8057

**Comment by MargarytaChepiga** [comment]
I would love to give it a try to fix! Can I work on it?

**Comment by sepeiFH** [comment]
adding **#my-adsLDRB** to the list in 
**browser-laptop/app/extensions/brave/content/styles/removeEmptyElements.css** 
should fix the problem

**Comment by GeetaSarvadnya** [comment]
@bsclifton Issue still persists on 0.23.8

**Comment by bsclifton** [comment]
The selector might have changed- did you want to check this out, @jonathansampson?

**Comment by bsclifton** [comment]
Moving out of milestone; if we get a fix we can pull back in

**Comment by I3uckwheat** [comment]
I would like to work on this :)

**Comment by ryanml** [comment]
@I3uckwheat awesome :D Thanks for taking it on.

I've self-assigned this issue so no one else will take it :) Feel free to let myself or another team member know if you have any questions. 🎊
