### ISSUE TITLE
cannot drag/drop un/lock icon to Bookmarks Toolbar if Toolbar is empty

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12911]
### Description
If nothing is on the Bookmarks Toolbar, you cannot drag and drop the lock/unlock icon to add a bookmark to the toolbar.

### Steps to Reproduce

  1. Load 0.20.23 with clean profile
  2. Enable 'Bookmark Toolbar' via right-click context menu (or from Bookmarks > Bookmarks Toolbar)
  3. Visit a website and attempt to drag and drop the lock/unlock icon to the toolbar

**Actual result:**
Site is not added to the toolbar:
![bkmk-toolbar-02023](https://user-images.githubusercontent.com/28145373/35537981-48553e3e-051a-11e8-936c-8638b8a1ac57.gif)

**Expected result:**
Site should be added to the toolbar:
![bkmk-toolbar-019147](https://user-images.githubusercontent.com/28145373/35537983-4b6ecc66-051a-11e8-9e9e-4f4debd20aa8.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.23
V8 | 6.4.388.40
rev | 5a2da66
Muon | 4.7.8
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
No

### Additional Information
cc @kjozwiak reproduced on Ubuntu and MacOS

**Comment by srirambv** [comment]
This has been a long standing issue on Windows without items on bookmark toolbar it is impossible to add by dnd on toolbar. 
Also mentioned here https://github.com/brave/browser-laptop/issues/11034#issuecomment-342471296

**Comment by cezaraugusto** [comment]
reason is that emptu bm toolbar is too narrow for being the drop area. A quick fix would be keeping the toolbar size even if empty not sure why we resized it to what it is now.

if blank space is a problem we could have a placeholder like "add or drag a bookmark from urlbar to populate this area"

**Comment by bradleyrichter** [comment]
We need a "drop zone" that would toggle the visibility of the BM bar during the drag action.

Possible @cezaraugusto ?

**Comment by rebron** [comment]
Closing. Looks like this is fixed in brave-core. https://brave.com/download-dev
