### ISSUE TITLE
"Onions Everywhere" when using Tor

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#12927]
When someone accesses a site over Tor, they'd probably prefer to connect to that service's official onion service rather than accessing the regular HTTPS or (gasp!) 😱HTTP😱 site through a Tor exit which could deliberately or accidentally mangle that connection.

Providing this sort of transparent upgrade relies the browser knowing with some certainty that a particular site is available as a particular onion. One unenviable option would be for us to maintain a canonical list of sites' onion services, and only accepting authentic additions to this list.

Alternatively, we could work to standardize a safe way for sites to advertise their onion service addresses. One approach could be using the [`alt-svc` header](https://trac.torproject.org/projects/tor/ticket/21952#comment:31) served from a secure origin. Alternatively, it might be possible to rely on a DNS record to identify the service(s) safely. Working out how to enumerate canonical onion services is probably the more-challenging part of this work.

**Comment by Bisaloo** [comment]
Did you hear about this [highly relevant (but unmaintained) project](https://github.com/chris-barry/darkweb-everywhere)?

**Comment by flamsmark** [comment]
We don't want to be in the position of maintaining a central repository of onions or evaluating evidence about the authenticity of a particular onion service. Upgrades should be based on a signal which sites can send securely themselves. Preloading like HSTS makes sense, but only in the context of that secure signal from sites.

**Comment by tomlowenthal** [comment]
I think we should rely on the `alt-svc` feature for this. brave/brave-browser#1121
