### ISSUE TITLE
Use Tor for ledger proxy instead of PIA

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#12923]
Once we have Tor working, we should consider using it for the ledger proxy, rather than PIA.

If Brave is connecting to a ledger service over Tor, we should probably configure that as an onion service on our end. Should we use a [single onion service](https://www.torproject.org/docs/tor-manual.html.en#HiddenServiceSingleHopMode) rather than a full hidden service? We should consider using something like Alec Muffett's [Enterprise Onion Toolkit](https://github.com/alecmuffett/eotk) on the infrastructure side.

**Comment by diracdeltas** [comment]
Setting a milestone, per discussion in Slack ledger channel. 

https://github.com/brave/internal/issues/298

**Comment by alexwykoff** [comment]
@flamsmark please migrate this issue to Brave core repos as needed

**Comment by tomlowenthal** [comment]
This is probably brave/brave-browser#804 now.
