### ISSUE TITLE
Use Tor for update checks and downloads

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#12924]
Once we have Tor working, we should consider using it for update pings and downloads.

If Brave is connecting to a the update service over Tor, we should probably configure that as an onion service on our end. Should we use a [single onion service](https://www.torproject.org/docs/tor-manual.html.en#HiddenServiceSingleHopMode) rather than a full hidden service? We should consider using something like Alec Muffett's [Enterprise Onion Toolkit](https://github.com/alecmuffett/eotk) on the infrastructure side.

Tor — even a single onion service — is still probably slower than a regular connection. However, browser update checks happen silently in the background. As long as we can reliably obtain updates, there's no reason for the user to be aware of how long it takes to download the update: we can just inform them when the process is complete.

**Comment by riastradh-brave** [comment]
arma adds: https://blog.torproject.org/tor-heart-apt-transport-tor-and-debian-onions

In particular, beyond individual privacy, always downloading updates anonymously makes it difficult for an adversary to target anyone with a malicious update.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/804 which calls out some specific use-cases for using Tor in a background service
