### ISSUE TITLE
page with long, invalid host causes browser to freeze

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1292]
this page: https://inputoutput.io/non-wp/data.html

i thought it would be fixed by #1289 but it's happening even with HTTPS Everywhere turned off

**Comment by weems** [comment]
not sure if this helps but Chrome Stable on Windows 7 x64 also crashes with this page.

**Comment by diracdeltas** [comment]
did you do the check with any browser extensions installed?

**Comment by weems** [comment]
I do have them installed, should I disable them all and try again?
