### ISSUE TITLE
sometimes Brave crashes when closing

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12939]
### Description
Sometimes after closing Brave, the 'Brave unexpectedly quit' message displays.

### Steps to Reproduce

  1. Use Brave normally.
  2. Quit Brave.
  3.

**Actual result:**
Sometimes Brave crashes when closing.

**Expected result:**
Brave should not crash on close.

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
Brave | 0.20.27
V8 | 6.4.388.40
rev | 76102c5
Muon | 4.7.9
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Possibly, also unknown

**Comment by bridiver** [comment]
this particular crash is a downstream effect of a problem with urlParse in the filtering code

**Comment by kjozwiak** [comment]
@bridiver could you provide a test case that can be used for verification? Would using @LaurenWags's profile that reproduced this crash be sufficient enough?

**Comment by LaurenWags** [comment]
Using profile that initially had the crashes I am still seeing some crashes on close with 0.20.29.
