### ISSUE TITLE
Automatically update Tor with Brave

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12933]
If we distribute Tor with Brave (#12932), we should ensure that it remains up-to-date. Should we just ship new binaries with Brave updates, or should we use a separate update mechanism to allow Tor to be updated on a different schedule?

**Comment by diracdeltas** [comment]
I think if we ship Tor with Brave, we should tie Tor updates to Brave updates for now. Tor updates are less frequent than Brave updates and it's not too much effort to ship a Brave hotfix for a Tor update if it is seriously needed.

**Comment by NumDeP** [comment]
I'm sorry but I have to agree with @flamsmark 's second suggestion as I think this would be regarded as unnecessary for users that won't use the feature at all or not very often.

Personally, I think it should work similarly to the toggle functionality in Payments with a couple of additional security requisites. Firstly, it should push updates in the same secure manner in which the Tor browser coherently does, i.e, it initially establishes a secure connection (not undermining that a user is using Tor often) then downloads the updates and then installs it afterwards. The second one being as soon as (TAB) Tor Amnesiac Browsing is toggled in about:preferences, (BB) Brave Browser should from that moment recognize that this user expects to use the service occasionally or often, thus applying the updates when released (only when toggled of course). 

Not to come across as pompous @diracdeltas but I think you may agree with me as I sort of understood your statement '...for now.' but don't you think it would beneficial for Brave to ascertain similarly to Ledger system being toggled, how many users are also toggling TAB or any other kind of anonymous information you retain/analyze from it?

We should coherently experience how Brave will function in the long-run as it may be annoying if major changes in mechanisms are made later :(

Furthermore, I think this would also be helpful in the long run for SMBs if you (hopefully) include an enterprise version :)

Depending on how good you brain-boxes make this, you may just kill a significant portion of the VPN trade with this implementation :(

**Comment by diracdeltas** [comment]
Closing this for now since we agreed that we are just shipping Tor with Brave (no separate update mechanism) in the foreseeable future. see https://github.com/brave/browser-laptop/issues/12932 and https://github.com/brave/browser-laptop/issues/12934
