### ISSUE TITLE
brave is non-functional (white canvas area, only menubar visible)

### ISSUE THREAD

**Issue by hasufell** [brave/browser-laptop#12937]
### Description
Build succeeds, tested both master and v0.19.147dev release. The browser is totally non-functional though. A window opens, the menubar is visible, but nothing else. If the window is moved somehow, the menubar also disappears.

### Steps to Reproduce

  1. clone brave
  2. `npm install`
  3. `npm start`

**Actual result:**
![brave](https://user-images.githubusercontent.com/1241845/35585084-3b92271a-05f7-11e8-919c-02b48b8be3b3.png)

**Expected result:**
a functional browser

**Reproduces how often:**
Always.

### Brave Version
tested on master and v0.19.147dev 

### Additional Information

System: exherbo
Node: tried with both 8.9.4 and 9.4.0

**Comment by Alino** [comment]
I had something similar right now after upgrading to 0.20 (on mac)
The browser did restart for me automatically into a state with white background,
it was very laggy and when I moved mouse around tabs they became visible on mouseover.
Then I tried to restart Brave by pressing command + Q and opening it again, now I could se 70% of the homepage and other 30% were white squares.
Restarted again, and now it's fine.

**Comment by hasufell** [comment]
I noticed this during build, I'm not sure if that is related:

```
/home/hasufell/git/brave/node_modules/node-abi/index.js:45
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 5.0.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/home/hasufell/git/brave/node_modules/node-abi/index.js:45:9)
    at module.exports (/home/hasufell/git/brave/node_modules/prebuild-install/rc.js:57:12)
    at Object.<anonymous> (/home/hasufell/git/brave/node_modules/prebuild-install/bin.js:9:25)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```

**Comment by luixxiul** [comment]
would you mind trying `rm -rf ~/.electron && rm -rf node_modules` before `npm install`?

**Comment by hasufell** [comment]
Doesn't help.

**Comment by hasufell** [comment]
any other information you need?

**Comment by bsclifton** [comment]
@hasufell can you try opening the Browser developer tools? <kbd>Shift</kbd> + <kbd>F8</kbd>
Once these are open, the console tab may have more information

**Comment by hasufell** [comment]
That doesn't even work. Brave is forced into foreground now kinda fullscreen and 95% of everything doesn't work. I cannot open developer tools or anything else. I can just quit the browser.

**Comment by hasufell** [comment]
I can open the console with `v0.19.147dev`:

![brave_2](https://user-images.githubusercontent.com/1241845/35945442-92f3b392-0c60-11e8-9738-2812c5d8c745.png)

**Comment by jempis** [comment]
I have the same problem, my windows is completely white, whitout the menu bar.
When i open the console the error are equals.
my system is windows 7 and the node versione 3.2.0.

Can someone help us?

Thanks

**Comment by bsclifton** [comment]
@jempis @hasufell there are some documented steps which you can try here:https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003

Please let us know if this helps

**Comment by L1fescape** [comment]
@hasufell you need to run `npm run watch` first before `npm start`

**Comment by hasufell** [comment]
@L1fescape then I would argue the documentation is a bit misleading: https://github.com/brave/browser-laptop#running-brave

It says

> One terminal can be used just to watch for changes to the code
>   npm run watch

which doesn't say anything about a dev server, nor that this is a required step. I don't want to watch for code changes, I want to run brave.

**Comment by bsclifton** [comment]
Thanks for the feedback, @hasufell - I opened a PR which I'd welcome feedback on which addresses this: https://github.com/brave/browser-laptop/pull/14114

**Comment by hasufell** [comment]
Thanks!
