### ISSUE TITLE
Use Tor as a subprocess

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#12934]
We shouldn't assume that a user has installed and configured Tor on their own. Instead, we should ship a Tor binary (#12932) and run it as a Brave subprocess, using our own `torrc` and live control mechanism.

**Comment by bradleyrichter** [comment]
We may decide that Tor is fully integrated but something to consider here is a growing request to not install things by default and provide an easier way to remove them. Mostly for extensions...

**Comment by riastradh-brave** [comment]
This issue is for _executing_ Tor as a subprocess, however we distribute it.  Will follow up about how it should be distributed in https://github.com/brave/browser-laptop/issues/12932.

**Comment by diracdeltas** [comment]
done in tor/0.23.x
