### ISSUE TITLE
top site tiles not being populated when updating profile from 0.19.147

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12941]
## Test plan

https://github.com/brave/browser-laptop/pull/12968#issue-293390058

----

### Description
I have a profile that I was using with version 0.19.147 which encountered issue https://github.com/brave/browser-laptop/issues/12027 (to the degree that I only have one (default, pinned) top site tile). When this profile was updated to 0.20.27 and I began to browse, I noticed my top site tiles were not being populated.

### Steps to Reproduce

  1. Have a profile from 0.19.x that is missing top site tiles due to https://github.com/brave/browser-laptop/issues/12027
  2. Update profile to 0.20.27.
  3. Open a new tab, note you still have the one (default, pinned) top site tile.
  4. Browse normally (visit some sites in new tabs, etc). 
  5. Open another new tab.

**Actual result:**
No new top site tiles added, only the default, pinned top site tile is displayed:
![screen shot 2018-01-30 at 6 14 57 pm](https://user-images.githubusercontent.com/28145373/35596829-810a6aae-05e9-11e8-94f9-8ae0e7961e3d.png)

**Expected result:**
Additional top site tiles should appear based on your browsing.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.27
V8 | 6.4.388.40
rev | 76102c5
Muon | 4.7.9
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
n/a

### Additional Information
Missed when testing https://github.com/brave/browser-laptop/issues/12027

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/thumbnails-except-twitter-are-gone-from-dashboard/15289?u=eljuno

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/add-home-screen-icons/15550

**Comment by LaurenWags** [comment]
@cezaraugusto test plan works (0.19.x -> 0.20.x) but doesn't work when going from 0.20.30 (currently released version) to 0.20.40. I suspect a majority of users will be updating from 0.20.30 to the next 0.20 version.

**Comment by bsclifton** [comment]
@cezaraugusto the change you made only executes when upgrading from 0.19.x to 0.20.x (hence the behavior @LaurenWags reports). Is there another way we can detect this broken state (and fix)?

**Comment by NejcZdovc** [comment]
@bsclifton should we push this into 0.22 or in the backlog?

**Comment by bsclifton** [comment]
@NejcZdovc let's push to 0.22 for now- if a quick fix comes in, we can consider doing a new build and
 uplifting 😄

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
