### ISSUE TITLE
'View Certificate' non-functional on Linux

### ISSUE THREAD

**Issue by 0xmohit** [brave/browser-laptop#12955]
### Description
When attempting to click the "View certificate" button in the Developer Tools Security tab, nothing happens.  (This is the same behavior reported earlier in #2611 that is marked fixed.)  The issue was observed on Linux.

### Steps to Reproduce

  1. Navigate to a HTTPS site, say https://duckduckgo.com
  2. Choose the menu: View > Developer Tools > Security > Overview > View Certificate
  3. Click the 'View Certificate' button

**Actual result:**

Nothing happens.

**Expected result:**

Certificate details to show up.

**Reproduces how often:**

Always.  Tried several URLs.

### Brave Version

**about:brave info:**
 
Brave: 0.19.147 
rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
Muon: 4.7.6 
libchromiumcontent: 64.0.3282.119 
V8: 6.4.388.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.4.0-57-generic 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

**Comment by luixxiul** [comment]
Thanks for your report. I'm going to close this one in favor of https://github.com/brave/browser-laptop/issues/7669 (Show Certificate detail on padlock and devtools on linux), which is a follow-up of #7319.
