### ISSUE TITLE
Linux build from master has no window decorations, ignores keyboard input, appears on all workspaces

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#12958]
### Description

Launching the browser yields a window with no window manager decorations that is omnipresent on all workspaces and ignores all keyboard input, as if it were a notification window that cannot take focus.  The menu bar responds to clicks, and some menu items function such as opening new tabs and loading the community help center and quitting, but some do not function such as toggling developer tools.

### Steps to Reproduce

  1. Build browser-laptop-bootstrap with `npm run build -- --debug_build=true --official_build=false` on Ubuntu 17.04.
  2. Launch with `npm run watch` in blb/src/browser-laptop and `npm run start` in blb.
  3. Try to interact with it.

**Actual result:**

The window has no window manager decorations, never takes focus so that keyboard input goes into whatever window has focus otherwise, and generally does not function.

**Expected result:**
A normal Brave browser that accepts keyboard input.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

The Help ---> About Brave menu item does not work and I can't type a URL, so I can't view about:brave.  Relevant git states:

- browser-laptop-bootstrap: commit 4fb98e79a4d7ce0327a313c2fb19b22cb83fc499
- blb/src/browser-laptop: commit ce2026d36de970ff9a3519219b9dd1468baed377, plus one commit to add draft Tor support (https://github.com/riastradh-brave/browser-laptop/commit/f9bf34b207712e4a3638d0c351c98e839f5376d7)
- blb/src/electron: commit d6f9ad610b0da24580d033e9e8dccda1b5a259de, plus one commit to add draft SOCKS5 authentication support (https://github.com/riastradh-brave/muon/commit/e2fb1a1c44ec91930623625e055ece8c6b30aecc)

**Reproducible on current live release:**

No.  Does not appear in 0.19 or 0.20 and did not appear in master until at least the Chromium 64 update.

**Comment by riastradh-brave** [comment]
Duplicate issue submitted simultaneously: https://github.com/brave/muon/issues/467

**Comment by petemill** [comment]
Issue with Muon 5.x, does not reproduce in 4.7.1 - assigning same milestone as muon 5.x

**Comment by riastradh-brave** [comment]
This is happening in the brave-beta 0.21.7-1 package for Ubuntu from the apt repository too, so `apt-get upgrade` rendered it nonfunctional and I had to switch to the brave 0.20.30-1 package.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/pull/495

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍
