### ISSUE TITLE
AltGr + Number opens up a new session tab

### ISSUE THREAD

**Issue by rasved** [brave/browser-laptop#12956]
## Test plan

https://github.com/brave/browser-laptop/pull/13042#issue-167512154

----

The shortcut for <tt>New Tab</tt> is the same as @ (at-sign) on Nordic keyboards. That's pretty annoying when typing in email addresses in web forms... 
Just realized that when I type square brackets (as in the subject) I open new tabs as well...
So the result after this posting is 4 new tabs... 🐛 

I can't find anywhere I can change it myself. 
Are this option missing in the menues, or do I oversee something? 

Thanks in advance, 
Rasmus

**Comment by sepeiFH** [comment]
+1 very annoying. Combination is ALT GR + 2

**Comment by ceasefire95** [comment]
+1 really frustrating! Please change the shortcut to something else or let us disable it!

**Comment by vinicentus** [comment]
+1 So annoying! Can we get a fix ASAP please?

**Comment by eljuno** [comment]
+2 from community https://community.brave.com/t/typing-in-brave-opens-a-new-tab/15067?u=eljuno

One of reporter said s/he used Estonian keyboard.
cc @bsclifton

**Comment by aliakyurek** [comment]
+1 Same for me. Issue started with 0.20.29. 
Any attempt to type special characters using Alt gr + number like #,$,[.. opens a new tab.
A hotfix is immediately necessary. 
Keyboard layout is Turkish.

**Comment by raakis** [comment]
+1 Same for me. Issue also started with 0.20.29.
Finnish keyboard layout in use.

**Comment by srirambv** [comment]
This is not specific to any keyboard. Happens even on English keyboard as well. Pressing <kbd>AltGr</kbd> + number causes a session tab to open.  

 Pressing <kbd>AltGr</kbd> + number key combination changes to Ctrl+Alt+<number> as seen in the  recording
![altgr](https://user-images.githubusercontent.com/17010094/35673677-45d63c80-0768-11e8-8744-e31c9dd62104.gif)

Here's what it looks like on 0.19.147
![altgr1](https://user-images.githubusercontent.com/17010094/35673852-b05526f2-0768-11e8-8817-b9128b51f7f2.gif)

Pressing and holding <kbd>AltGr</kbd> keeps switching between <kbd>Ctrl+Alt</kbd> and <kbd>Alt</kbd> although not noticeable on the recording but clearly visible.

**Comment by gert7** [comment]
+1 for the Estonian keyboard. version 0.20.30

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-its-complete-unusable-now-slow-laggy-and-more/15278/2

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/trying-to-do-a-on-a-swedish-language-keyboard-does-not-work-it-opens-tab/15279

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/alt-numbers-keyboard-shortcut-to-opening-tabs/15244?u=eljuno

+1 from community https://community.brave.com/t/when-i-type-the-with-alt-2/15314?u=eljuno

**Comment by eiyey** [comment]
+1 from Spanish (Spain) keyboard.
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by kjozwiak** [comment]
Thanks for bringing this up in Slack @srirambv! This should definitely get fixed ASAP as it's affecting a large % of the community as demonstrated by all the +1's above.

**Comment by Jacalz** [comment]
+1 from me using Swedish keyboard, really annoying

**Comment by ElucGeek** [comment]
+1 from Swiss keyboard and german keyboard. It's a nightmare as it make my password manager entering password in the URL field and send to search engine !

**Comment by vinicentus** [comment]
The original problem lies here: #6915
A solution: #13015 Note that this would change the shortcut to `Control + Shift + [session number]` for Windows and `Command + Shift + [session number]` on Mac OS.

**Comment by vinicentus** [comment]
Just noticed the reopening. Take a look at #13015.

**Comment by chrisvanderheyden** [comment]
+1 from Belgian Keyboard ... This is really a showstopper, i won't be using brave until this gets fixed

**Comment by NejcZdovc** [comment]
@chrisvanderheyden we reverted PR that broke this one and new version should be out next week. Sorry for your trouble

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/altgr-registrers-as-ctrl-alt-in-brave/15691

**Comment by daath** [comment]
+1 Just installed to day, eager to start using it - Now I'm forced to wait until a new version without the bug is released - I can't wait :)

**Comment by tomasroaldsnes** [comment]
+1 Norwegian
