### ISSUE TITLE
sometimes Brave crashes on close

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12957]
### Description
Originally reported with https://github.com/brave/browser-laptop/issues/12939 however after the fix for that still sometimes seeing crashes with the same profile in 0.20.29 (profile was provided to @bridiver for debugging)

### Steps to Reproduce

  1. Open Brave (this particular profile has been updated from 0.18.x to 0.19.x to 0.20.x)
  2. Browse normally.
  3. Close Brave.

**Actual result:**
Sometimes Brave crashes on close. Example crash IDs: 72ec4000147844fd and 9c7208c093540492

**Expected result:**
Brave should not crash when closing.

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
Brave | 0.20.29
V8 | 6.4.388.40
rev | 4fc3c8f
Muon | 4.7.9
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Yes to an extent, although doesn't seem to crash as often on 0.19.147 (example crash ID from 0.19.147: 05f8042d6d4bcaa6 )

### Additional Information
I have a profile which can be used for debugging, was already provided to @bridiver but can provide to anyone else as needed.

**Comment by alexwykoff** [comment]
@bridiver have you had a moment to debug this?

**Comment by kjozwiak** [comment]
Moving this into the next milestone as we're planning on a release for tomorrow.

**Comment by petemill** [comment]
Unfortunately these crashes have not made it to the crash server.

**Comment by LaurenWags** [comment]
+1 from community member using 0.21.18 (and earlier versions): https://community.brave.com/t/mac-os-error-message-after-quitting-brave/17194

**Comment by davidtemkin** [comment]
I get this all the time. Even on update. May have gotten worse of late.

**Comment by kjozwiak** [comment]
@bridiver mind taking a look at this again if you have some time?

**Comment by LaurenWags** [comment]
I agree @davidtemkin - it happens way more often than when originally reported.

**Comment by bsclifton** [comment]
The original fix for this caused https://github.com/brave/browser-laptop/issues/12959 - we'll definitely want to look at the fix that was done

**Comment by petemill** [comment]
Just got a crash on quit:
`Brave(31361,0x7fff93bb6380) malloc: *** error for object 0x7fba51150428: pointer being freed was not allocated`

Here's the stack: https://gist.github.com/petemill/d1536fcab55d9ba45b65ea50dd02ea89

**Comment by alexwykoff** [comment]
We're unlikely to fix this before brave-core switchover.
