### ISSUE TITLE
auto-include turned off but sites are still auto included

### ISSUE THREAD

**Issue by SupremeRumHam** [brave/browser-laptop#12969]
Yes I have searched for something similar and didn't find anything.

### Description

I have auto-include turned off but sites are still added to my contribution list and included.

### Steps to Reproduce

  1. Have auto-include turned off
  2. Go to random website
  3. Check Payments to see random site has been added to contribution list

**Actual result:**
https://twitter.com/SupremeRumHam/status/958930308417466370

**Expected result:**
The expected result is that sivers.org is not my contributions list as included

**Reproduces how often:**
 Don't have a number or percentage but it happens often

### Brave Version

**about:brave info:**
 Brave Version 0.20.29

**Reproducible on current live release:**
 Yes I updated it hours ago and it happened

**Comment by SupremeRumHam** [comment]
![preferences 1_31_2018 9_04_21 pm](https://user-images.githubusercontent.com/29110697/35662210-c5fe30a4-06cb-11e8-9496-de23dea8d939.png)

**Comment by NejcZdovc** [comment]
@SupremeRumHam so you started with the empty list and you visit some random sites? or was this two included sites already on the list?

**Comment by SupremeRumHam** [comment]
The YouTube Channel I added, but sivers.org I went on just to see if it would be auto-included and it was. While my auto-include was turned off. Sorry I didn't clarify
