### ISSUE TITLE
Installation Failed on Windows 10 pro

### ISSUE THREAD

**Issue by sajalbdt** [brave/browser-laptop#1296]
Installation Failed due to Some errors like " Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\GBB Wimax\AppData\Local\Brave\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)"
How do I Fix it?

**Comment by bbondy** [comment]
Up to what directory in the path `C:\Users\GBB Wimax\AppData\Local\Brave\packages\RELEASES'` does exist for you?

**Comment by sajalbdt** [comment]
Yes it's already exist.

**Comment by sajalbdt** [comment]
I founded this releases file "6D3775D6E66C6E1949905F65B31E70FCFA7FF542 Brave-0.9.0-full.nupkg 99690045" as per following path.

**Comment by luixxiul** [comment]
Does this error still exist?

**Comment by luixxiul** [comment]
Closing this due to lack of information.
