### ISSUE TITLE
Security/privacy slider to disable features with greater risk of privacy leaks

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12961]
At minimum we should disable (and make it impossible to enable):
* flash
* webtorrent
* all external extensions
* widevine
* urlbar remote autocomplete suggestions
* brave payments
* sync
* autofill (including passwords?)

We should also make sure:
* favicons in the tab area are loaded in the same circuit/session as the page
* strict site isolation is enabled (tbd in muon)
* no data from Tor private tabs is part of telemetry 

Debatable:
* block all unencrypted HTTP requests (or show a warning page before allowing clickthrough?)
* block scripts by default
* enable 1st party fingerprinting protection

**Comment by flamsmark** [comment]
Following in-person discussion, this doesn't seem like the right fit for our initial Tor private browsing implementation because the core goal is to make Tor easier. Instead, these seem like a good fit for a more general-purpose security/privacy slider feature.

**Comment by tomlowenthal** [comment]
This has made the leap to brave/brave-browser#876
