### ISSUE TITLE
I cant open site cobinhood with brave

### ISSUE THREAD

**Issue by raulnovella** [brave/browser-laptop#12973]
I took a good scare because I thought they had closed the website, but with chrome I can enter. I do not know how to solve it.

**Comment by TDeisinger** [comment]
Check this issue and make sure it's not because of it:

https://github.com/brave/browser-laptop/issues/12959

**Comment by raulnovella** [comment]
Yes I have seen it before, but I do not understand anything. I do not know about problems with proxy, only at the user level. Anyway, my message is different.
"It is possible that the website https://cobinhood.com/ is temporarily inactive or has been permanently moved to another address.
ERR_FAILED"

**Comment by bsclifton** [comment]
@raulnovella I'm unable to reproduce this... I am curious if you are experiencing the proxy issue that was mentioned by @TDeisinger 

Are other sites working?

**Comment by raulnovella** [comment]
![cobinhood](https://user-images.githubusercontent.com/4912508/36019899-9e1b965e-0d78-11e8-98a2-c380ce2132ba.jpg)

Haciendo ping a cobinhood.com [104.20.83.5] con 32 bytes de datos:
Respuesta desde 104.20.83.5: bytes=32 tiempo=64ms TTL=57
Respuesta desde 104.20.83.5: bytes=32 tiempo=61ms TTL=57
Respuesta desde 104.20.83.5: bytes=32 tiempo=51ms TTL=57
Respuesta desde 104.20.83.5: bytes=32 tiempo=56ms TTL=57

Estadísticas de ping para 104.20.83.5:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 51ms, Máximo = 64ms, Media = 58ms

**Comment by raulnovella** [comment]
I tried to reinstall the browser but it's the same

**Comment by cocoin1** [comment]
also for me the same problem. not load cobinhood.com website. same error as raulnovella

**Comment by matteomac** [comment]
same for me, worked only once. 
dunno if it caused it, but it stopped working after I activated metamask extension

**Comment by cocoin1** [comment]
do u have any plan to fix or not?

**Comment by raulnovella** [comment]
Finally "fixed", I can already see the web of Cobinhood.

**Comment by bsclifton** [comment]
@cyjambo @cocoin1 @matteomac can you confirm this works?
