### ISSUE TITLE
Tabs are not loading discarded, even when requested to

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#12976]
### Description
https://github.com/brave/browser-laptop/issues/12916 was mitigating a bug with discarding tabs (automatically) which had already been loaded, and causing them to not be able to be switched to (#10673).

However, it also unintentionally results in startup tabs not being created 'unloaded' (or 'discarded'), meaning they all load simultaneously. This does not need to be the case as tabs during startup are not affected by #10673.

### Steps to Reproduce

  1. Create many tabs (regular http / https sites)
  2. Quit Brave
  3. Load Brave again

**Actual result:**
Tabs are all loaded

**Expected result:**
Only active tab is loaded

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.20

**Comment by esmail** [comment]
Thanks for fixing. Just want to point out that this was especially painful for us tab hoarders, since #2702 meant that any tabs that didn't end up loading successfully were effectively lost for good after quitting.
