### ISSUE TITLE
GET chrome-extension://invalid/ error when loading magnet/torrent file

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12971]
### Description
GET chrome-extension://invalid/ error when loading magnet/torrent file

### Steps to Reproduce
  1. Open browser dev tools
  2. Open any magnet/torrent link
  3. Console throws error

**Actual result:**
![webtorrent](https://user-images.githubusercontent.com/17010094/35664880-d494782a-0749-11e8-9552-77faf697a3c8.gif)

**Expected result:**
Shouldn't throw error

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.5
-- | --
V8 | 6.4.388.40
rev | 6c8a992
Muon | 4.7.5
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Yes

### Additional Information
cc: @bridiver @feross @diracdeltas

**Comment by bsclifton** [comment]
Confirmed I get this, but I don't see it as critical since the functionality still works as expected
