### ISSUE TITLE
Dev tools - Audits > Stubborn "Can only audit tabs"

### ISSUE THREAD

**Issue by nkempe** [brave/browser-laptop#12974]
### Description
In the dev tools, tab Audits, the audit function keeps displaying the message "Can only audit tabs. Navigate to this page in a separate tab to start an audit.".
I'm already in a tab with a website when I try this, and trying it on a new tab with the same site has the same result.

I just tried this out of curiosity for the feature so for me it's a low priority issue.

### Steps to Reproduce
  1. Open a website in a tab
  2. Press F12 to open the Dev Tools
  3. Open the tab "Audits"
  4. Click the button "Perform an audit..."
  5. A box appears with the options. At the bottom the notification message appears in red.

**Actual result:**
!["Can only audit tabs"](https://i.imgur.com/H8mwG0N.png)

**Expected result:**
"Run audit" button is enabled and audit can be executed.

**Reproduces how often:**
Every attempt.

### Brave Version
Brave | 0.20.29
V8 | 6.4.388.40
rev | 4fc3c8f
Muon | 4.7.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Comment by JamieFarrelly** [comment]
I was about to raise this, the reason it happens is because you need to be able to open dev tools in the same window for it to work. If [this issue](https://github.com/brave/browser-laptop/issues/3555) is fixed I assume it'll then work.
