### ISSUE TITLE
Download torrent file fails

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12970]
### Description
Download torrent file  fails

### Steps to Reproduce
  1. Clean install 0.21.5
  2. Open the link https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-9.3.0-amd64-netinst.iso.torrent
  3. Click download, doesn't work. Console throws error

**Actual result:**
![download](https://user-images.githubusercontent.com/17010094/35664641-f8c72b3a-0748-11e8-9a71-7b34cb252106.gif)

**Expected result:**
Should download the torrent

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.5
-- | --
V8 | 6.4.388.40
rev | 6c8a992
Muon | 4.7.5
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
No

### Additional Information
cc: @diracdeltas @feross

**Comment by bsclifton** [comment]
Tested with 0.21.9 and this is working as expected (tested both on macOS and Windows 7)

**Comment by btlechowski** [comment]
Verified 0.21.9 Win64

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
used this link as the one in the issue returned 404: https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-mac-9.4.0-amd64-netinst.iso.torrent
