### ISSUE TITLE
Visual element to indicate zoom level for the UI

### ISSUE THREAD

**Issue by andreanidouglas** [brave/browser-laptop#12983]
For the desktop browser, it needs a visual element to report which level of zoom is selected

**Comment by srirambv** [comment]
There is a zoom indicator on the kabob(hamburger) menu. 
![image](https://user-images.githubusercontent.com/17010094/35715706-2b4a9a72-07fa-11e8-9fa0-152b8a814d25.png)

**Comment by Liunkae** [comment]
@andreanidouglas Do you mean a zoom indicator in the url bar, like Firefox does when the zoom level is not 100%:
![](https://user-images.githubusercontent.com/19424103/35749783-5b0f35ec-0818-11e8-8ccc-a4d4eaaaba0f.png)

**Comment by andreanidouglas** [comment]
it's not related to the web renderer itself, but the UI. on Windows if you hold ctrl and scroll over (let's say the refresh button) the interface, it will change the GUI elements zoom level.

https://imgur.com/a/XGvh7

**Comment by Liunkae** [comment]
The UI scale is supposed to be changed via `Settings > Advanced > Toolbar and UI elements scale`:
![](https://user-images.githubusercontent.com/19424103/35773011-0f21faa8-090c-11e8-98b6-20b1b3f27bad.png)

The behavior you are describing sounds like a bug. The UI scale shouldn't change when you Ctrl+Scroll.

**Comment by andreanidouglas** [comment]
just to complement, the behaviour is the same on my linux desktop on version 0.19.123

my windows pc is at: 0.20.30

**Comment by srirambv** [comment]
> Windows if you hold ctrl and scroll over (let's say the refresh button) the interface, it will change the GUI elements zoom level.

This sounds like the issue logged here https://github.com/brave/browser-laptop/issues/12764. That is a known bug Ctrl+Scroll causes either Zoom in/out. @andreanidouglas could you confirm this is exactly what you see?

**Comment by andreanidouglas** [comment]
@srirambv,
It does not look related to me. those two appears to refer to the ability to zoom the page content and 
issues with the Mac Magic mouse.

**Comment by dustcrawler** [comment]
> @andreanidouglas Do you mean a zoom indicator in the url bar, like what Firefox has when the zoom level is not 100%:
> ![](https://user-images.githubusercontent.com/19424103/35749783-5b0f35ec-0818-11e8-8ccc-a4d4eaaaba0f.png)

This would be a nice feature.

**Comment by andreanidouglas** [comment]
actually no, I haven't tested this in some time. but the UI was scaling as a scroll the mouse with ctrl over them, not the web page
