### ISSUE TITLE
Sites automatically included in Brave Payments even when auto-include is turned off

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#12994]
### Description
In my Brave Payments settings, I have auto-include turned off. However, sites that I visit keep getting added to Payments as enabled/included instead of being added to the list as disabled/not included.

### Steps to Reproduce
  1. Turn on Brave Payments. 
  2. Turn off auto-include.
  3. Visit sites not already in the Payments list.

**Actual result:**
The visited sites are added to the Payments list as enabled/included.

**Expected result:**
The visited sites should be added to the Payments list as disabled/not included.

**Reproduces how often:**
Sometimes. I haven't figured out why/when it happens. I welcome suggestions one ways to test and troubleshoot.

### Brave Version

**about:brave info:**
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
tried to reproduce it, but sadly without success

**Comment by echosa** [comment]
The most recent for me:

https://3v4l.org/
https://send-email.org/
https://slashdot.org/

I think there's more going on, though. For instance, Slashdot was a site that I specifically tested around the time I submitted this PR. However, when I went to Slashdot (for the first time in Brave) then checked the Payments settings, it was *not* enabled but was in the list. Today, when I went to check in order to respond to your question, it *is* enabled. So, apparently:

- I went to Slashdot with "auto-include" turned off in Payments.
- I checked the Payments settings page and Slashdot was in the list but correctly not enabled.
- Today (three days later), I checked the Payments settings page again, and Slashdot is now enabled.

Not that I have not visited Slashdot anymore. It shows 1 visit totaling 24 seconds of time spent on the site.

<img width="870" alt="screen shot 2018-02-05 at 9 22 58 am" src="https://user-images.githubusercontent.com/133786/35812470-a564a934-0a56-11e8-844c-d7ef890e0741.png">

**Comment by srirambv** [comment]
Repro'd on 0.20.30. Not sure if this qualifies as proper STR

Enable auto-include and visit few sites to add to ledger table
Once you have a decent list of sites, turn off `auto-include`
Restart browser and visit sites, 8/10 sites visited gets added to the list with include switch turned on

@echosa could you confirm if this is what you also did to see the publishers included with `auto-include` turned off?

**Comment by echosa** [comment]
@srirambv That sounds right to me, or at least close. Not sure if all the steps are necessary, like visiting sites with `auto-include` on first or restarting the browser. Either way, the end result seems correct: turn `auto-include` off, visiting new sites, they (eventually) show up as included when they shouldn't.

Also, what is "STR"?

**Comment by srirambv** [comment]
@echosa STR -> Steps to reproduce 😃 

@NejcZdovc  does including sites in table before turning off `auto-include` makes a difference. I couldn't reproduce the issue when I disabled `auto-include` immediately after enabling payments.

**Comment by jonathansampson** [comment]
I repro. The following GIF displays the STR, but after a bit of closer inspection, I find that I don't even need to switch browser windows. I can simply click a link on the page, and when the next page loads, the domain is supported.

![auto-include-error](https://user-images.githubusercontent.com/815158/37568003-1475f592-2a9d-11e8-8b0e-87f5af1452c3.gif)

**Comment by NejcZdovc** [comment]
I tried to reproduce it, but couldn't. @jonathansampson can you please try again on the latest master? Thank you
