### ISSUE TITLE
Virtual keypad not shown when opening citibank login in PB

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#12993]
### Description
Virtual keypad not shown when opening citibank login 

### Steps to Reproduce
  1. Open a new Private tab
  2. Visit citibank.com and login
  3. Enter user name, check the use virtual keyboard for password
  4. Virtual keyboard doesn't work

**Actual result:**
Virtual keypad not shown when opening citibank login 

**Expected result:**
Should be able to use virtual keyboard to login

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.30
-- | --
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Yes

### Additional Information
Same result with shields off

**Comment by bsclifton** [comment]
unable to repro when testing with `brave-core`; I think the site changed
