### ISSUE TITLE
LastPass unable to use 2FA with SMS code

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#12999]
### Description
Reported via community: https://community.brave.com/t/lastpass-2-factor-auth-problem/10501 and twitter: https://twitter.com/PhilMoscovitch/status/958789159711277057

If you use LastPass with 2FA via SMS codes, the screen where you enter the code freezes in Brave.

### Steps to Reproduce

(via community)
  1. Click lastpass icon
  2. Enter email and password
  3. On next page send code to SMS
  4. (Receive SMS)

**Actual result:**
It is not possible to type or paste my code.

**Expected result:**
Able to enter SMS code.

**Reproduces how often:**

### Brave Version

**about:brave info:**
Multiple versions, LastPass version 4.5.0.5

**Reproducible on current live release:**
yes

### Additional Information
Maybe related to https://github.com/brave/browser-laptop/issues/11660 ?

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/jchristiaanvos/status/960167295766188033

**Comment by ermattson** [comment]
I am facing this issue as well. Just downloaded Brave and enabled LastPass. 

Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Comment by cottonsean** [comment]
Same Here.  Unable to enter sms code.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/lastpass-multifactor-auth-dont-work/26538?u=eljuno

**Comment by Brave-Matt** [comment]
+1 from Twitter: https://twitter.com/TwitLurkr/status/1022143370850967554
