### ISSUE TITLE
implement Tor 'new identity' button (or menu item)

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12997]
Functionality: clears storage partition for a site and creates a new Tor circuit for it

**Comment by flamsmark** [comment]
I was talking about this with @alexwykoff at the dev/design chat today. The UX for this is a little fraught: in order for the button to be useful, folks have to know to use it and what it does. Alex suggested that it might be useful to heuristically guess when a circuit is slow, and switch up then: we passed the question of what heuristics to use off to Ben.

I think it might make sense to conceal this functionality behind an existing user gesture — hard refresh. That seems like a gesture that encodes many of the high-level semantics of new-identity, and bundles it with other behavior that a user already expects, and it doesn't introduce any new interface elements. Are there cases where hard-referesh for new-identity really wouldn't work?

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
