### ISSUE TITLE
Cannot type into iframe with Strict Site Isolation

### ISSUE THREAD

**Issue by bdukes** [brave/browser-laptop#13007]
### Description
With strict site isolation turned on, keyboard input doesn't have any effect on content inside an iframe.

### Steps to Reproduce
  1. Turn on strict site isolation
  2. Navigate to http://www.brianthicks.com/state-of-elm/2018/
  3. Attempt to type (e.g. press enter, or the letter of one of the options on the form)

**Actual result:**
The form does not respond to the input

**Expected result:**
The form responds to the input, selects the option, moves on to the next question

**Reproduces how often:**
100% of the time (on both macOS 10.11.6 El Capitan and Windows 10)

### Brave Version

**about:brave info:**
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 15.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**
Yes

**Comment by bdukes** [comment]
### Brave Version (Windows)

**about:brave info:** 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by srirambv** [comment]
Also an issue with typing into icloud login with site isolation enabled. Reported via https://community.brave.com/t/icloud-webversion/19203/2

**Comment by lmenus** [comment]
+1

**Comment by bsclifton** [comment]
Issues with strict site isolation are fixed with brave-core 😄 

You can download the developer channel release here:
https://brave.com/download-dev
