### ISSUE TITLE
Suggestion: Add option to mute notification sounds

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#13001]
### Description
Already search existing issue, maybe I missed one.

Requested on Reddit https://www.reddit.com/r/BATProject/comments/7us6ma/mute_desktop_notifications/
> Is there any way to mute notifications?
>Really annoying sound, even though I like the notifications.

### Steps to Reproduce

  1. Visit https://www.bennish.net/web-notifications.html > click Show > Allow
  2. Notification appears with sounds
  3.

**Actual result:**
Brave show notification with sounds

**Expected result:**
Brave show notification without sound if users choose to `mute`.

**Reproduces how often:**
Easy

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 6.3.9600
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Yes

### Additional Information
NDA

**Comment by Liunkae** [comment]
Is there already a system setting for this on Windows? I know macOS has a setting (`System Preferences > Notifications > Play sound for notifications`):
![](https://user-images.githubusercontent.com/19424103/35773101-2af5e008-090e-11e8-9aa0-c3be52715a29.png)

**Comment by Liunkae** [comment]
Looks like Windows 10 has a setting: https://www.howtogeek.com/219703/how-to-disable-notification-sounds-in-windows-10/

**Comment by bsclifton** [comment]
Closing as the OS has a way to disable the sound (thanks for the link, @Liunkae!)
