### ISSUE TITLE
Switch Control Animations in Brave Payments

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13006]
### Description
Switch Control animations aren't displayed properly within the Brave Payments interface.

### Steps to Reproduce
_With many properties included in Brave Payments_
1. Click the _include_ control next to an item

**Actual result:**
List is sorted before the include animation is played.

**Expected result:**
List is resorted after the include animation is played.

**Reproduces how often:**
Always

### Brave Version
0.2030

**about:brave info:**
``` 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```

**Reproducible on current live release:**
Yes

**Comment by BrendanEich** [comment]
Does anyone know what regressed this?

**Comment by NejcZdovc** [comment]
this didn't regressed as far as I know, code was not changed in that regards. One thing that did change in 0.20 is toggle, where we change it to Aphrodite and refactor it. That's why cursor is gone as well. But this is not limited to ledger table but to all switches.

**Comment by NejcZdovc** [comment]
To properly address this issue we need to remove our custom sort table component (or fix performance problems) and add some perf optimized component in

**Comment by NejcZdovc** [comment]
Based on the fact that things will be changed (ledger table will be completely new) and the fact that this issue would require a lot of work compared to the output, I will close it for now
