### ISSUE TITLE
Brave Shows Different Shortcuts for New Session Tab

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#13000]
### Description
Brave shows different shortcuts for creating session tabs.  The shortcut previously added in #10363. See screenshot :) 

### Steps to Reproduce

  1. Right click `+` button on tabs bar > New Session Tab
  2. Shortcuts shows `Ctrl+1` etc. for session tab. This shortcuts used for navigating between tabs.
  3. Open `File` menu (press `alt` if menu hidden) > New Session Tab
  4. Shortcuts shows `Ctrl+Alt+1` etc. This one is the expected shortcuts.

**Actual result:**
![sessiontab-1](https://user-images.githubusercontent.com/25360853/35754843-8a252164-0897-11e8-980f-1d97cdf877d1.png)

**Expected result:**
Should show the right shortcuts
![sessiontab-2](https://user-images.githubusercontent.com/25360853/35754900-b9372880-0897-11e8-8848-d7d62c316889.png)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.30
-- | --
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 6.3.9600
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Yes

### Additional Information
cc @aekeus @bsclifton

**Comment by Liunkae** [comment]
Looks fine on macOS. May be Windows-only.

![](https://user-images.githubusercontent.com/19424103/35773069-6a2da82e-090d-11e8-9105-f2ce197af33d.png)

**Comment by srirambv** [comment]
I think that shortcut should be <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Number</kbd>. 

Also <kbd>Ctrl</kbd>+<kbd>Number</kbd> just switches the tab 1-9 and not create a session tab.

**Comment by vinicentus** [comment]
Notice that if this #13015 passes, we will need to change thees again.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/13042

**Comment by srirambv** [comment]
Seeing this on latest build (0.20.41)
![image](https://user-images.githubusercontent.com/17010094/36196362-8e26e6fa-1196-11e8-9d55-6c9dd7c6d20d.png)

**Comment by LaurenWags** [comment]
Verified keyboard shortcuts removed on MacOS:

![screen shot 2018-02-14 at 9 00 38 am](https://user-images.githubusercontent.com/28145373/36208304-a504f07c-1166-11e8-975a-d4c91596160b.png)

**Comment by btlechowski** [comment]
Verified 
 ```
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.13.0-21-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
```
