### ISSUE TITLE
Add back/forward gesture touchpad and shortcut trouble

### ISSUE THREAD

**Issue by eiyey** [brave/browser-laptop#13009]
Hi!

It would be so nice to be able to scroll horizontally with the touchpad with two or three fingers so you can go back/forward in history. I find it really useful as it reduces the time for doing the same thing. Also, I see that the shortcut for doing this is Alt + [ or Alt + ]  , the thing is that in Spanish (Spain) keyboard for accessing the key [ or ] is by Altgr + ` or Altgr + +, so it doesn't work properly.

Thanks.

Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by srirambv** [comment]
Added +1 on #1847.
