### ISSUE TITLE
Downloading latest (0.20.30) linux binary gives 404

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#13013]
Could not find a similar issue.

### Description
It is not possible to download the latest (0.20.30) Brave binaries for Linux.

### Steps to Reproduce
  1. Go to https://brave.com/
  2. Click download button and go to https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
  3. Scroll to "Raw x64 binaries" and follow instructions
  4. `wget -v https://laptop-updates.brave.com/latest/linux64`

**Actual result:**
<pre>
$ wget -v https://laptop-updates.brave.com/latest/linux64
--2018-02-05 12:14:53--  https://laptop-updates.brave.com/latest/linux64
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.37.7
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.37.7|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /latest/dev/linux64 [following]
--2018-02-05 12:14:53--  https://laptop-updates.brave.com/latest/dev/linux64
Reusing existing connection to laptop-updates.brave.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/0.20.30/linux64/Brave.tar.bz2 [following]
--2018-02-05 12:14:53--  https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/0.20.30/linux64/Brave.tar.bz2
Resolving brave-download.global.ssl.fastly.net (brave-download.global.ssl.fastly.net)... 151.101.37.194
Connecting to brave-download.global.ssl.fastly.net (brave-download.global.ssl.fastly.net)|151.101.37.194|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-05 12:14:53 ERROR 404: Not Found.
</pre>

**Expected result:**
Brave being downloaded.

**Reproduces how often:**
100%

### Brave Version
0.20.30

**Comment by aekeus** [comment]
This is the likely cause of the issue:
https://github.com/brave/browser-laptop/blob/master/tools/buildInstaller.js#L46

**Comment by btlechowski** [comment]
Verified Ubuntu 17.10.
 
```
Brave: 0.20.38 
V8: 6.4.388.41 
rev: f4ecddc0cbc5a053904e9be8d1e2b0f1d902c953 
Muon: 4.7.10 
OS Release: 4.13.0-21-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
```
