### ISSUE TITLE
Can't Open Link in New Tab

### ISSUE THREAD

**Issue by dolebas** [brave/browser-laptop#13017]
### Description

On several occasions over the past week "Open Link in New Tab" simply fails. No links in the current tab can be opened in a new tab.

Copying the link and pasting it to a new tab works. Cloning the current tab and opening the link in another new tabs works as well.

### Steps to Reproduce

Browse randomly with multiple tabs over a period of time.

**Reproduces how often:**

The issue occurs on average once every other hour.

### Brave Version

**about:brave info:**

Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by bsclifton** [comment]
I've noticed slowness with this

@bridiver @petemill any thoughts on why middle clicking or right click > "Open in New Tab" would cause a blank tab to open? I know this happens via the renderer... sometimes it seems to take 5-10 seconds to load the title for the tab.  It seems also, as @dolebas experienced, it doesn't open altogether

**Comment by bsclifton** [comment]
@dolebas are you seeing a blank tab when you try to open? Or is nothing happening?

**Comment by petemill** [comment]
I've noticed the slowness in recent versions. Nothing I've changed, that's been merged to a reliase that would cause it, so I'm not personally sure (yet).

**Comment by dolebas** [comment]
@bsclifton no, I'm not seeing a blank tab when I try to open, nothing visible is happening.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/cannot-open-links-in-new-tabs/16077

**Comment by cryptojennie** [comment]
+1 from community in Rocket.chat: https://basicattentiontoken.rocket.chat/channel/brave-browser-bugs?msg=q7hPKYWKsRx8QgcpA

**Comment by wing-puah** [comment]
Mine open new tab seems to be working with the sites except for google search. 
Using Linux Ubuntu 16.04.4 LTS

Brave: 0.21.18
V8: 6.4.388.41
rev: 580be78
Muon: 4.8.2
OS Release: 4.13.0-36-generic
Update Channel: Release
OS Architecture: x64
OS Platform: Linux
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.140

**Comment by rabus** [comment]
Hello

Same as above, no luck except Google search.

 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by dolebas** [comment]
Since I changed my default search engine from Google to DuckDuckGo a couple of weeks ago, this issue has disappeared for me.

**Comment by bsclifton** [comment]
Possibly related to https://github.com/brave/browser-laptop/issues/13394 and https://github.com/brave/browser-laptop/issues/13058

**Comment by bsclifton** [comment]
I believe this may be a dupe of https://github.com/brave/browser-laptop/issues/12362

**Comment by arsalankhalid** [comment]
I had also accidentally created a duplicate with #13413, looked up relating issue and sadly didn't find this. I have re-created this:

![open_new_tab](https://user-images.githubusercontent.com/5307218/37257221-77d6b146-253c-11e8-816a-123b1c3524d9.gif)

**Comment by MBLHarrison** [comment]
I usually do not have this problem, only on specific websites does this occur.
I can reliably get this issue to occur 100% of the time when on www.Andertons.co.uk

**Reproduction Steps**

1. Enter a search term in the Search field
2. Right click OR Middle Mouse Button on any result and select open in a new tab

**Actual Result**
Link does not open in new tab

**Expected Result**
Link opens in new tab


**Example**
On this [page of search results](https://www.andertons.co.uk/search?categoryId=&storeId=10151&catalogId=3074457345616676668&langId=-1&sType=SimpleSearch&resultCatEntryType=2&showResultsPage=true&searchSource=Q&pageView=&beginIndex=0&pageSize=24&searchTerm=rg&authToken=-1002%252CXZvf36sLiPiYegUJrwTEpYgBzE92SYyViFqNTYY0v8k%253D&#facet:&productBeginIndex:0&facetLimit:&orderBy:&pageView:grid&minPrice:&maxPrice:&pageSize:&)
Right click on any result and select open in a new tab.
To verify that there is a link you can copy the address of the link and open a new tab manually and paste it in.


Brave | 0.21.18
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/open-in-new-tab-not-working/18199?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/right-clicking-to-open-new-tab-does-not-work/18495?u=eljuno

Brave 0.21.24, right-click link not open new tab

**Comment by nckraghu** [comment]
Issue present in when trying to open links in wikipedia pages too.

Brave 0.22.13, Windows 10 Home Edition 64 bit
