### ISSUE TITLE
Idea: Write a script that will help automate the process of adding Chrome Extensions

### ISSUE THREAD

**Issue by st333v** [brave/browser-laptop#13028]
Could someone with the technical know how write a script that will help automate the process of adding Chrome Extensions.

Jonathan Sampson wrote a great article on how to get Chrome extensions running in Brave at
https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d

I feel a great deal of the process which currently needs to be done manually could be automated, 
For example a DOS batch file or VBS script  (or platform equivalent scripting language) could open the extensions directory at either 

%localappdata%\Google\Chrome\User Data\Default\Extensions (Windows)

or 

~/Library/Application Support/Google/Chrome/Default/Extensions   (macOS)

then scan the currently loaded extensions manifest files in that directory to get the extension names, then let you choose the one they want to "overwrite" with the new extension, then it would rename the existing extension folder, and then copy in the Chrome extension from a zip file or wherever.

I don't have sufficient batch file scripting skills to do this, but if anyone out there could do this, i think it would be very useful for the less technically capable Brave users.

**Comment by bsclifton** [comment]
We're planning to switch our UI from Muon to Brave Core (forked from Chromium's UI) which should give us the same extension support as Chromium. Given that, I don't think we'll implement this with the current version of the product (`browser-laptop`).

@AilinLiao has started work on the extensions store.  I think this is definitely an issue she'll need to solve- how do new extensions get added (and once added, stay up to date).

Closing this issue as `wontfix` - but we should be able to address in Brave Core
