### ISSUE TITLE
YouTube "Theater Mode" not remembered when Brave is closed

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#13029]
### Description
When I watch videos on YouTube, I do so in "Theater mode". However, every time I close Brave and open it again, I have to turn "Theater mode" on again. It doesn't remember like Firefox does.

### Steps to Reproduce
  1. Open a YouTube video.
  2. Turn on Theater mode. (It's between "full screen" and "settings" on the right side of the video controls area.
  3. Close Brave and open it again.
  4. Open a YouTube video.

**Actual result:**
The video is opened in "normal view" not "theater mode".

**Expected result:**
The video should open in "theater mode".

**Reproduces how often:**
100% of the time

### Brave Version

**about:brave info:**
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**
Yes

**Comment by Raindeer44** [comment]
YouTube uses a session cookie called 'wide' to track Theater Mode. The 'session' part of session cookie means the cookie is to be cleared as soon as the browser is closed, meaning this is a choice on the part of YouTube and Brave is behaving correctly. 

Firefox is the odd browser out; they made a deliberate decision a long time ago (10+ years) to keep session cookies for the use of restoring tabs and whatnot. This decision has been somewhat controversial: https://bugzilla.mozilla.org/show_bug.cgi?id=530594

**Comment by srirambv** [comment]
@Raindeer44 thanks for the explanation. 

@echosa If you set `Allow all cookies` and not clear browsing history when browser is closed the setting remains set. 

Going to close the issue and can continue the conversation. We can reopen the issue if required
