### ISSUE TITLE
'Notify me about token promotions' switch doesn't work if you've already said 'Maybe Later'

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13021]
### Description
If you are prompted for a promotion and you select 'Maybe Later', the remindTimestamp is set to remind you 24h later. If you then go into Adv Settings and toggle 'Notify me about token promotions' off, you will still be reminded 24h later.

### Steps to Reproduce

  1. Clean install of 0.20 using ledger_environment=staging.
  2. Get notification.
  3. Select Maybe Later.
  4. Go to Adv Settings, toggle 'Notify me about token promotions' off.
  5. Close Brave.
  6. Open session-store-1 and locate remindTimestamp. Using https://www.epochconverter.com/ you can see that it is set to 24h later.
  7. Change this value to 5-10 minutes from now.
  8. Relaunch Brave (make sure you still use ledger_env staging)

**Actual result:**
In 30-60 minutes you will be notified about the promotion again. 

**Expected result:**
You should not be notified about the promotion since you toggled the switch to off.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.20.30

**Reproducible on current live release:**
Yes

### Additional Information
Missed when testing https://github.com/brave/browser-laptop/issues/12313

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.

**Comment by kjozwiak** [comment]
Before going through verification, I reproduced the original issue using `0.20.30` 8b78402e7b3b91d44d8146cbe4dc8013592c33fd with the STR that @LaurenWags provider above.

Verified using `0.21.18` 580be782bc37ed8580dd22f79e1d2d355fddfb89 under Ubuntu 17.10 x64.
