### ISSUE TITLE
Suggestion: stress test brave and firefox to have more than 30+ tabs on at the same time

### ISSUE THREAD

**Issue by DonaldTsang** [brave/browser-laptop#13025]
### Description
Can't open more than 10 tabs without the computer slowing down

### Steps to Reproduce

Laptops with less than 8GB of RAM

### Additional Information

Firefox can do this with 50+ tabs without slow down.
Slow downs only happens after 80+ tabs, which is 8x the amount of brave

**Comment by bsclifton** [comment]
Closing as duplicate of https://github.com/brave/browser-laptop/issues/9389
