### ISSUE TITLE
Pinned and unpinned ledger values are not aligned properly

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13024]
### Description
Pinned and unpinned ledger values are not aligned properly

### Steps to Reproduce
  1. Visit few sites and populate ledger table
  2. Pin a few sites
  3. See the awkward alignment of % values

**Actual result:**
0.22.0
![image](https://user-images.githubusercontent.com/17010094/35813400-8b8e1fc8-0ab9-11e8-8601-bb656744a0ee.png)
0.20.30
![image](https://user-images.githubusercontent.com/17010094/35813433-9cb656da-0ab9-11e8-8e18-6b4e41a68a37.png)

**Expected result:**
Should be similar to how it looks on 0.20.30

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.0
-- | --
rev | ac59a52
Muon | 5.0.1
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
No

**Comment by NejcZdovc** [comment]
this was broken in 0.22 branch

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
