### ISSUE TITLE
Pinning a publisher causes excluded publisher to momentarily turn on and off

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13023]
### Description
Pinning a publisher causes excluded publisher to momentarily turn on and off

### Steps to Reproduce
  1. Enable payments and visit some sites to add it to ledger table
  2. Exclude a few publishers if not already excluded
  3. Pin other pubs, excluded pub quickly toggles the excluded switch

**Actual result:**
![pinpubs](https://user-images.githubusercontent.com/17010094/35813052-9ee02b58-0ab8-11e8-879c-3ddd4d838586.gif)

**Expected result:**
Excluded publisher switch should not be affected with pinning a publisher

**Reproduces how often:**
Yes

### Brave Version

**about:brave info:**

Brave | 0.20.30
-- | --
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Yes

**Comment by NejcZdovc** [comment]
closing this one as we will change logic with new design and we will not have time to fix this until then
