### ISSUE TITLE
sometimes unable to reorder pinned tabs

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13022]
### Description
Reported via twitter: https://twitter.com/dfwdraco76/status/960210761414074374

Sometimes after using Brave for a period of time, pinned tabs will not allow them selves to be reordered.

### Steps to Reproduce

  1. Have some pinned tabs. (user reported only using one window at the time)
  2. Use Brave for some time.
  3. Attempt to reorder pinned tabs.

**Actual result:**
Sometimes pinned tabs will not allow them selves to be reordered and snap back to their original position. A restart of Brave seems to solve the issue. Here's a user provided video: https://t.co/QBrfpclxDt

**Expected result:**
Pinned tabs should be allowed to be reordered.

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
0.20.30

**Reproducible on current live release:**
Yes

**Comment by Liunkae** [comment]
+1 from https://medium.com/@PaulRBerg/constructive-feedback-for-the-brave-browser-9f08b422a05

**Comment by srirambv** [comment]
This will be autofixed in brave-core. 

cc: @bsclifton to either keep the issue open or close it

**Comment by bsclifton** [comment]
This behavior is already fixed with [brave-core](https://github.com/brave/brave-browser) 😄 We won't be fixing in `browser-laptop`
