### ISSUE TITLE
Suggestion: having PassWordStore or KeePass as password manager by default

### ISSUE THREAD

**Issue by DonaldTsang** [brave/browser-laptop#13027]
# KeePass
chrome: https://chrome.google.com/webstore/detail/chromeipass/
firefox: https://addons.mozilla.org/en-US/firefox/addon/keefox/

# Password Store
chrome: https://chrome.google.com/webstore/detail/chrome-pass-zx2c4/
firefox: https://addons.mozilla.org/en-US/firefox/addon/passff/

**Comment by srirambv** [comment]
Both extension requested here 
https://github.com/brave/browser-laptop/projects/1#card-3549743
https://github.com/brave/browser-laptop/projects/1#card-972721
