### ISSUE TITLE
sometimes cookies aren't being saved

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13030]
### Description
Reported via community: https://community.brave.com/t/saving-cookies-doesnt-work-need-to-re-type-everything-to-login-to-places/15231 and Twitter: https://twitter.com/vladastojanovic/status/959483070670917632

A couple of users have reported that they are not staying logged into sites after close/reopen of Brave (Twitter, Facebook, etc). Confirmed that users aren't clearing any data on exit.

### Steps to Reproduce

Per discussion with user on Twitter, these are their steps
  1. Clean install of 0.20.30
  2. Login to Twitter (https://twitter.com/login - be sure 'remember me' checkbox is selected)
  3. Allow Brave to save password.
  4. Close Brave
  5. Reopen Brave

**Actual result:**
Have to login to Twitter again

**Expected result:**
Should not have to login to twitter again.

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
0.20.29, 0.20.30

**Reproducible on current live release:**
reported with current live release

### Additional Information
I can repro if I do the above steps quickly (less than 15s, but not sure how much less) - maybe something isn't being saved in the session in a timely manner?
Also, one user mentioned they don't see this issue with Chrome but do experience this issue with Vivaldi.

**Comment by btlechowski** [comment]
Here are two scenarios I could reproduce the issue:
- Wrong Permissions on Cookies file. -
1. Close Brave
2. Revoked the Modify permissions for Cookies file
3. Start Brave
4. Login twitter
5. Restart Brave

Result:
The cookies were not saved. There was no error, just cookies were not saved.

- Corrupted Cookies file -
1. Close Brave
2. Delete old Cookies and created a text file with random letters in its place.
3. Start Brave
4. Login twitter
5. Restart Brave

Result:
The cookies were not saved.
Note: after yet another restart the cookies started to work

Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 6.1.7601
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows

On windows Cookies file can be found in:
c:\Users\[User]\AppData\Roaming\brave\

The best way to fix these problems is to close Brave and delete Cookies file.
Upon next start a valid Cookies file will be generated.

**Comment by NejcZdovc** [comment]
pushing back to 0.22

**Comment by LaurenWags** [comment]
+1 from twitter: https://twitter.com/djSTICKYBUDS/status/969667329847013376?s=19

**Comment by jonathansampson** [comment]
I believe I'm experiencing this too:

``` 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Comment by diracdeltas** [comment]
i have seen this issue appear before, but it was due to Brave not working with the system encrypted storage mechanism (same as the one used for the password manager) after restart. i appeared to be logged out of google/github and `about:passwords` showed no passwords anymore, but the issue was fixed as soon as i unlocked / relocked my system keychain on MacOS.  (so the data wasn't actually lost)

**Comment by kjozwiak** [comment]
I've managed to reproduce this pretty easily only on Twitter with the current `0.21.24` release and the `0.22.13` RC using the same STR that @btlechowski mentioned above:

* install/launch either `0.21.23` or `0.22.13` (using a new profile)
* once installed, login into Twitter
* close/re-launch Brave and you'll be logged out of Twitter

Once you've restarted and stay logged in, you won't run into the above issue anymore. However, it does take a few tries for the session to stick.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/logged-out-after-brave-restarts/21542

**Comment by btlechowski** [comment]
Worth checking if the issue reproduces for all the visited websites or websites that are opened.

**Comment by kjozwiak** [comment]
When I was investigating this a while back using the Twitter case, the session would be lost even if I closed the tab, example:

* launch a brand new installation of Brave
* login into Twitter (save password and select `Keep me logged in`), close the tab
* close/re-launch Brave and re-open Twitter in a new tab (you'll be logged out)

Definitely worth trying with different websites though.

**Comment by DeftNerd** [comment]
@diracdeltas - I was having this same problem, thanks for leading me down the right path. I just switch my desktop from Gnome to KDE and the KDE encrypted keyring/wallet wasn't working properly. After disabling it, now Brave remembers my cookies and sessions properly again.

**Comment by srirambv** [comment]
This issue happens only when you close the browser immediately after logging in. If the tab is kept open for a min and then the browser is relaunched it doesn't lose the cookie and retains the login session.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/logging-me-out-too-frequently/27140

**Comment by ar-jan** [comment]
Same problem. Restarting Brave --> logged out of Twitter. But additionally, I was just logged out after keeping Brave and my Twitter tab open for a couple of hours (with another tab active).

> Brave: 0.23.79 
> V8: 6.8.275.24 
> rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
> Muon: 8.0.7 
> OS Release: 6.1.7601 
> Update Channel: Release 
> OS Architecture: x64 
> OS Platform: Microsoft Windows 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 
> libchromiumcontent: 68.0.3440.84

**Comment by kjozwiak** [comment]
+1 from the community: https://community.brave.com/t/logouts-happening-for-no-reason/24013

From the above thread, it seems like folks are suggesting that the issue started happening on `0.22.810`.

**Comment by Brave-Matt** [comment]
Related, from reddit: https://www.reddit.com/r/brave_browser/comments/9ar3lp/constantly_logged_out_of_everything/
Also  probably related to #14959

**Comment by ar-jan** [comment]
Same in v 0.23.105. Just clicking a link on Twitter immediately logged me out.

**Comment by ar-jan** [comment]
WAT!? How is this a wontfix? I like what Brave is aiming for, but this makes it basically unusable.

**Comment by tagawa** [comment]
Thanks for the explanation @kjozwiak. So this won't be an issue in `brave-core`?

**Comment by kjozwiak** [comment]
Correct! Haven't heard any complaints about folks losing sessions/cookies. In fact, I've been using `brave-core` for a while and have never lost a session when running into a crash or relaunching the previous session.

**Comment by tagawa** [comment]
That's great to hear - thank you.

**Comment by bsclifton** [comment]
What @kjozwiak said 😄👍 Apologies for not including a blurb when I closed this out earlier today

**Comment by ar-jan** [comment]
Thanks! (I didn't know about brave-core).
