### ISSUE TITLE
mac pkg installer is not signed

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13032]
### Description
On top of the .app requiring signing by the 'Developer ID Application' Apple certificate, the pkg installer needs to be signed by the 'Developer ID Installer' Apple certificate. Both these certificates have the same private key file.

### Steps to Reproduce

  1. Download .pkg installer from releases page
  2. Run installer

**Actual result:**
  2. macOS should complains that the installer is not signed
  3. `pkgutil --check-signature ./dist/Brave-0.20.31.pkg` shows 'no certificate'

**Expected result:**
  2. macOS should not complain that the installer is not signed
  3. `pkgutil --check-signature ./dist/Brave-0.20.31.pkg` should show certificate

**Comment by kjozwiak** [comment]
Received the following output when running `pkgutil --check-signature` against `Brave-0.20.39.pkg`:

```
Kamils-MBP:browser-laptop kjozwiak$ pkgutil --check-signature ~/Downloads/Brave-0.20.39.pkg
Package "Brave-0.20.39.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Brave Software, Inc. (KL8N8XSYF4)
       SHA1 fingerprint: AB 03 A4 2A 25 0B 5F 7D F9 A0 69 16 17 51 3A 22 97 F2 A3 A8
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

Also ensured that you could view the certificate via the `lock` icon during the `pkg` installation process, example:

<img width="631" alt="screen shot 2018-02-13 at 10 34 14 am" src="https://user-images.githubusercontent.com/2602313/36158303-fbbd0002-10a9-11e8-959d-4a61aec9d876.png">
