### ISSUE TITLE
the app icon for 0.20.30 is not displayed on Ubuntu 16.04

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#13031]
Similar to #10803, which says to open new issues if the problem occurs.

### Description
The app icon for Brave 0.20.30 is not displayed on Ubuntu 16.04 using MATE in the alt-tab window or in the panel.

### Steps to Reproduce
  1. Start Brave
  2. Alt-tab
  3.

**Actual result:**
Brave icon not shown

**Expected result:**
Brave item shown

**Reproduces how often:**
100%

### Brave Version

Brave installed through apt-get repository.

**about:brave info:**
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 4.13.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**
yes

**Comment by srirambv** [comment]
+1 from @sterno1966  from #13051 
Screenshot from #13051 
![screenshot from 2018-02-06 19 27 41](https://user-images.githubusercontent.com/33036050/35893488-ebf34248-0b73-11e8-8307-d893b974f609.png)

**Comment by hugobuddel** [comment]
Also broken on Scientific Linux (~Centos) 7.4 when installing from tarball

**Comment by bsclifton** [comment]
+1 from @edmundlaugasson via https://github.com/brave/browser-laptop/issues/14442
> When to run Brave then in taskbar or switching between apps using ALT+TAB there is icon missing. In main menu, desktop and quick launchbar there is that icon. The running command is:
`sh -c "brave --user-data-dir-name=brave -- %U"`
Actually while opened properties of Brave choice in main menu and when to click the icon button then the file `/usr/share/pixmaps/brave.png` exist and also default permissions, ownership are fine:
`$ stat -c '%A %a %U %G %n' /usr/share/pixmaps/brave.png`
`-rw-rw-r-- 664 root root /usr/share/pixmaps/brave.png`
... but it does not show in taskbar or while switching apps.

64-bit Linux Mint 18.3 MATE

**Comment by ElGatoLoco** [comment]
Can confirm the issue on Debian Testing, Brave v0.23.105, installed via package manager.
