### ISSUE TITLE
Store browser data on private servers

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [brave/browser-laptop#13037]
I would like to provide a suggestion for the Brave browser, and I hope Github is the right place.

The sync option, while very important and many people need it, makes some people uncomfortable because their data is stored on your servers (albeit encrypted). How about allowing users to sync their data to their own place? Like to some SFTP/SSH directory, or similar protocols? Implementing that is not difficult at all, and it will make your browser certifiably the best for privacy, because no one will ever doubt that you don't store any data on your servers, and it'll be even testable with Wireshark!

**Comment by flamsmark** [comment]
This is addressed in brave/sync#58 .
