### ISSUE TITLE
Brave wallet backup key displayed on the UI as 'a' regressed

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#13046]
### Description

I had an issue with the Brave wallet recovery key displayed on the UI as 'a', which was fixed in the prior vs of Brave,  0.19 I believe. Double, triple checked to make sure that it's shown correctly for a few days.

It's back with 0.20.30. Again, I see 'a'

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

![screen shot 2018-02-06 at 1 44 37 pm](https://user-images.githubusercontent.com/4369856/35885838-02bae8a8-0b44-11e8-96b1-8fcf4250f59d.png)

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

related #11383

**Comment by kjozwiak** [comment]
@jenn-rhim can you see if recovering your key and restarting Brave resolves the issue? Similar to what you did in https://github.com/brave/browser-laptop/issues/11383#issuecomment-358075919. Once you restart the browser, does it stick or does it revert back to `a`?

We'll need to find out if this is still happening in certain edge cases... @LaurenWags @srirambv @btlechowski, keep your eyes opened for corrupted backup keys.

**Comment by NejcZdovc** [comment]
closing this one as we don't have STR and we added new overlay that alerts users about it. Please create new issue with STR if we see it again.
