### ISSUE TITLE
Update to muon 4.7.10

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#13041]
## Test plan
1. Visit `about:brave`
2. `Muon` version should be `4.7.10`

**Comment by darkdh** [comment]
closed by https://github.com/brave/browser-laptop/pull/13034

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/35899125-b578eefc-0bf0-11e8-8ddd-eb31d420c68e.png)

**Comment by bsclifton** [comment]
Update to 4.8.1 was done with https://github.com/brave/browser-laptop/commit/c46fde9d6e8ca770ea01c47c53360dac1359eef4

And then reverted with https://github.com/brave/browser-laptop/commit/7c04e80d74e3fa3b0f1e18f82f33b02e706f8b93

**Comment by bsclifton** [comment]
Updated to 4.8.2 with 322079ac9aea526cc688cbaa159d89edfb724d4c

**Comment by kjozwiak** [comment]
```
Brave: 0.20.39 
rev: 9d61c2055f8811df8a6a4c43f65fdad6a7f7136e 
Muon: 4.8.2 
libchromiumcontent: 64.0.3282.140
```

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/36194803-32bc0e44-1191-11e8-8bb3-adecd43bd91b.png)

**Comment by btlechowski** [comment]
Verified 
```
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.13.0-21-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```
