### ISSUE TITLE
Open Windows Search Results in Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13043]
### Description
When performing a search from the Windows 10 start menu, Brave is not offered as a browsing option.

### Steps to Reproduce
_On Windows 10_:
1. Press the Windows key (or click the Cortana tray icon)
2. Search a string like 'javascript documentation'
3. When search string appears beneath *Best Match*, press Enter key

**Actual result:**
Non-Brave browsers are offered to the user.

**Expected result:**
Brave should be listed (if installed), or be the default (if set to default browser).

**Reproduces how often:**
Always.

### Brave Version
0.19.30

**about:brave info:**
``` 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```

**Reproducible on current live release:**
Yes

### Additional Information
The machine on which this method was tested has the following browsers installed:
- Microsoft Edge
- Google Chrome
- Mozilla Firefox
- Opera
- Brave (Release and Beta)

![image](https://user-images.githubusercontent.com/815158/35883777-13910392-0b4e-11e8-8981-a5eb212d1df0.png)

![no-brave-from-search](https://user-images.githubusercontent.com/815158/35883573-45ab5932-0b4d-11e8-8dd6-582b965332a3.png)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1020
