### ISSUE TITLE
Tapping URL Bar Crashes Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13054]
### Description
Repeatedly tapping the URL bar crashes Brave.

### Steps to Reproduce
_On a touch-enabled device:_
1. Tap URL bar repeatedly, and rapidly.

**Actual result:**
Brave crashes.

**Expected result:**
Brave does not crash.

**Reproduces how often:**
Always.

### Brave Version
0.19.30

**about:brave info:**
```Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```

**Reproducible on current live release:**
Yes

### Additional Information
Originally reported by [a user on Twitter](https://twitter.com/infinityblok/status/961123773633171456):

![image](https://user-images.githubusercontent.com/815158/35903446-db4108f0-0ba4-11e8-9939-78063c4cf749.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/brave-bug-on-surface-tablet/16141?u=eljuno

**Comment by kjozwiak** [comment]
I tried reproducing this on a Lenovo X1 Carbon running Ubuntu 17.10 but couldn't reproduce after repeatedly tapping on the URL bar. Might be Win related.

**Comment by MargarytaChepiga** [comment]
Hey, I am using Windows 10, can't reproduce it.

**Comment by jonathansampson** [comment]
@kjozwiak @MargarytaChepiga Here's a video of the crash... https://youtu.be/GXhN1anVIfk

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/url-bar-touchscreen-crash/18680?u=eljuno

> Tapping on URL bar and Ctrl + F search box.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/finger-highlighting-then-trying-to-copy-closes-down-brave-ms-surface-pro-4/26584?u=eljuno
