### ISSUE TITLE
ERR_FAILED on every google search request

### ISSUE THREAD

**Issue by sylvainjule** [brave/browser-laptop#13058]
### Description
I'm running into an error page (blank with ```ERR_FAILED```, see images attached) whenever I try to run a search request through google search.

### Steps to Reproduce
Basically, try a ```:g```search. 
Further details are hard to determine since I have been a brave user for a few weeks and never ran into this issue before. Didn't change any habit, didn't change a setting. No VPN. I have google set as my default search engine but get the issue even if I don't.

**Actual result:**
Here is a screenshot of the page as well as the console error.
<img width="1280" alt="capture d ecran 2018-02-07 a 14 04 34" src="https://user-images.githubusercontent.com/14079751/35918118-e8015524-0c10-11e8-88ac-7df3360170a7.png">
<img width="1131" alt="capture d ecran 2018-02-07 a 13 53 03" src="https://user-images.githubusercontent.com/14079751/35918312-a806cebc-0c11-11e8-9ab5-bc90bb405da1.png">

**Expected result:**
A completed search query.

**Reproduces how often:**
Everytime I try a ```:g``` research (or everytime I try a "blank research" if google is my default search engine)

### Brave Version

**about:brave info:**

Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 16.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Comment by mgoelzer** [comment]
I have the same problem.  There's an even simpler reproduction:  just type `https://www.google.com/search?q=test` into the address bar and press enter.  Same result as @sylvainjule, same error message.

![image](https://user-images.githubusercontent.com/225111/37162720-d83bd082-22aa-11e8-88c7-f61f1a64c119.png)

This only happens on `https://www.google.com/search*` URLs.  I can load the `https://www.google.com/` home page without problems.

**about:brave**
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 15.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by bsclifton** [comment]
possibly related: https://github.com/brave/browser-laptop/issues/13394

**Comment by bsclifton** [comment]
@sylvainjule @mgoelzer do either of you use a system proxy?  We do have an open issue for problems loading content behind a proxy: https://github.com/brave/browser-laptop/issues/12959
