### ISSUE TITLE
Crash report not being reported to stats

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13057]
### Description
Crash report not being reported to stats

### Steps to Reproduce

  1. Clean install 0.20.32
  2. Open chrome://crash in a new tab to cause a webview crash
  3. Ensure the crash is listed on chrome://crashes with a proper crash id
  4. Crash not reported on stats

**Actual result:**
Crash report not being reported to stats

**Expected result:**
Should list the crash on stats

**Reproduces how often:**

### Brave Version

**about:brave info:**

Brave | 0.20.32
-- | --
V8 | 6.4.388.41
rev | d167cd3
Muon | 4.7.10
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
No

### Additional Information
cc: @bridiver @aekeus

**Comment by kjozwiak** [comment]
@aekeus I think you mentioned this was due to the large queue of crashes that haven't been parsed/added into stats.brave correct?

**Comment by aekeus** [comment]
Yes, we are behind in parsing crash reports. We brought up a full large instance on S3 to handle the current load.

**Comment by alexwykoff** [comment]
@srirambv could we double-check on stats.brave.com to see if we have cleared the queue?

**Comment by kjozwiak** [comment]
@alexwykoff @aekeus just checked again.. looks like the last reports are from ~16hrs ago.

**Comment by kjozwiak** [comment]
Closing this off... I'm pretty sure this is due to the crash server being behind.. I believe we're almost 2 days behind at this point.. However, crash reports are coming in so this seems to be working.
