### ISSUE TITLE
Password session storage sometimes causing app level exception

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1305]
We have a couple of reports of this:
<img width="434" alt="screenshot 2016-04-09 12 45 35" src="https://cloud.githubusercontent.com/assets/831718/14404949/165d9876-fe51-11e5-9c61-19373f982246.png">

It looks related to session storage and passwords.

**Comment by bbondy** [comment]
When you fix this problem, please also handle the case that if someone is already in this state it'll gracefully fix it for them. Thanks!

**Comment by diracdeltas** [comment]
argh, it turns out url.parse throws this error if the input is `null`, which is probably what was happening on some pages. fixing

**Comment by weems** [comment]
for historical knowledge I had this app level error when I installed the first 0.9 RC. Seems to be fixed in RC2
![2016-04-08 22_18_28-preferences](https://cloud.githubusercontent.com/assets/470705/14408107/6bc6ccc8-feac-11e5-9753-2e795464f6ab.png)

**Comment by bbondy** [comment]
I think if we used `flow` this would have been prevented for free.  Adding a label so we can keep track if it happens often or not.

**Comment by diracdeltas** [comment]
I think this could have been prevented with `flow` + a string type annotation on the form action. i just tried out `flow weak` on some files and it wasn't as noisy as i thought it would be.
