### ISSUE TITLE
icon missing from toolbar panel

### ISSUE THREAD

**Issue by sterno1966** [brave/browser-laptop#13051]
![screenshot from 2018-02-06 19 27 41](https://user-images.githubusercontent.com/33036050/35893488-ebf34248-0b73-11e8-8307-d893b974f609.png)

### Description

icon missing from toolbar panel

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

20.30 linux ubuntu

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
hi, would you please elaborate more what you mean "no icon"? thanks!

**Comment by hugobuddel** [comment]
See the lower left corner of the screenshot, next to the text 'Inbox' there should be the Brave logo, but it shown an empty window logo. It's the same issue as #13031 and possibly #10803

**Comment by hugobuddel** [comment]
It is quite annoying though, I often 'cannot find Brave'. Apparently I'm visually oriented and and essentially have to retrain myself to find the one application without an icon. E.g. I suddenly have to think when alt-tabbing, a weird experience and maybe distracts me enough from what I'm doing to switch to another browser.

**Comment by srirambv** [comment]
Closing in favour of #13031 . Can continue the discussion there.
