### ISSUE TITLE
Load favicons over Tor when Tor's enabled

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#13065]
Favicons in the tab area should be loaded over Tor. They can be loaded in the same circuit as the tab they belong to, or each icon can be loaded in its own separate circuit. They shouldn't be batched into the same circuit.

**Comment by diracdeltas** [comment]
i'm pretty sure that if i load favicons in the `persist:tor` partition, then they will be loaded in the same circuit as the tab that they belong to. @darkdh can confirm/deny

**Comment by darkdh** [comment]
yes, each origin has its own unique circuit

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
