### ISSUE TITLE
Disable webtorrent whenever Tor is enabled

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#13063]
Torrents rek Tor; it's just science.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87

**Comment by kjozwiak** [comment]
@flamsmark when you load `https://webtorrent.io/torrents/sintel.torrent` within a PT without Tor, it doesn't load/do anything. Expected? I don't remember if we allow webtorrent on regular PT's.

**Comment by srirambv** [comment]
>Probably not a blocker but we should probably stop the page load once the user hits OK on the modal. 

@kjozwiak Logged https://github.com/brave/browser-laptop/issues/14472 and added to 0.24.x milestone

**Comment by diracdeltas** [comment]
@kjozwiak IIRC we intentionally also don't load webtorrent in regular PT

**Comment by kjozwiak** [comment]
> @kjozwiak Logged #14472 and added to 0.24.x milestone

Thanks @srirambv 👍 

> @kjozwiak IIRC we intentionally also don't load webtorrent in regular PT

Looks like it's working on `0.22.810`, `0.22.727`, `022.721`, `0.22.714` so it seems like a `0.23.x` regression. @srirambv is filing a bug 👍

**Comment by diracdeltas** [comment]
@kjozwiak i think i was thinking of https://github.com/brave/browser-laptop/issues/12631 - looks like we warn users that webtorrent is a privacy risk but don't intentionally disable it in private tabs
