### ISSUE TITLE
When Tor's enabled, remote autocomplete must also go over Tor

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#13064]
If we can't run remote autocomplete over Tor, it should just be unavailable.

**Comment by diracdeltas** [comment]
For now, I will disable remote autocomplete when the current focused tab is a tor tab

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
