### ISSUE TITLE
Store bookmarks (and passwords?) into a separate json file

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1306]
Sometimes we have to ask users to clear session storage because of some bug as a workaround. It might be better to have these stored separately because they are the most important thing to users.

**Comment by pedro7** [comment]
And history, as well. Using Firefox as example, all three are in: _places.sqlite_ (bookmarks & history), _logins.json_ and _key3.db_ for the master password.
Alternatively, a functionality like Firefox's "[Refresh Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings)".

**Comment by luixxiul** [comment]
@pedro7 I created a issue for it, #1864

**Comment by NejcZdovc** [comment]
closing in favor of #9978
