### ISSUE TITLE
YouTube videos lag/stop working

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13079]
### Description
Reported via twitter: https://twitter.com/glaucocustodio/status/961728287990042624 and internally by @NejcZdovc 

YouTube is lagging after viewing for some time and/or having multiple tabs open. @NejcZdovc noticed that if he clicks the video lags - and if he clicks continuously the video stops working until he stops clicking.

### Test plan / Steps to Reproduce

1) start browser (make sure you have a folder with at least 20 bookmarks)
2) open YouTube player
3) right click on a folder and select `Open all in tabs`
4) then immediately after they are opened start closing them with mouse middle button (rapidly)
5) youtube starts lagging and then if you just click on a youtube page (on white section) video lags
note: if you don't experience the issue after the first try, go to step 3 and repeat from there

**Actual result:**
Video lags, especially when clicking anywhere in the whitespace of the page. Errors are generated in the main browser console (not the window's console):
```
An uncaught exception occurred in the main process Uncaught Exception:
param str (null) is not a string
```

**Expected result:**
Video should not lag.

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
0.20.30

**Reproducible on current live release:**
yes

**Comment by mr2cats** [comment]
Same problem. It appeared with the last update for me.

**Comment by LaurenWags** [comment]
+1 from @bbondy - seems to occur at the same time as https://github.com/brave/browser-laptop/issues/12333 https://github.com/brave/browser-laptop/issues/12828 and https://github.com/brave/browser-laptop/issues/13157

maybe related @bsclifton ?

**Comment by petemill** [comment]
STR from @NejcZdovc as provided in #13087 :
1) start browser (make sure you have a folder with at least 20 bookmarks)
2) open YouTube player
3) right click on a folder and select `Open all in tabs`
4) then immediately after they are opened start closing them with mouse middle button or cmd+w
5) youtube starts lagging and then if you just click on a youtube page (on white section) video lags

**Comment by srirambv** [comment]
Verified on 0.21.12 no lag on video playback based on the test plan

**Comment by kjozwiak** [comment]
Clearing `QA/checked` tags as this is now landing in 0.20.x for the hotfix. We should recheck against all there platforms and make sure things are still working as expected.

**Comment by petemill** [comment]
This did not just affect youtube, but all video / audio media playback, and probably also anything the tab may be running in JS, whilst the browser created a crash report upon every click (or other action)
