### ISSUE TITLE
ESPN 3 requires flash player

### ISSUE THREAD

**Issue by Wahoospa** [brave/browser-laptop#1307]
I cannot watch ESPN 3.com because it requires flash player. Brave does not use flash player. Any way around this?

**Comment by TheFallenOneGOTH** [comment]
![espn3 on brave bug](https://cloud.githubusercontent.com/assets/8735509/14405120/521a4c2a-fe55-11e5-99c9-867f9027375f.PNG)
Able to confirm:
**Operating System**: Windows 10 Version 1511 (OS Build 10586.164)
**Brave**: 0.9.0
**Electron**: 0.37.3
**libchromiumcontent**: 49.0.2623.108
**V8**: 4.9.385.33
**Node.js**: 5.10.0
**Update channel**: dev

**Comment by luixxiul** [comment]
Being worked on with #1093, closing.
