### ISSUE TITLE
Promo setup fails to install on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13077]
### Description
Promo setup fails to install on Windows

### Steps to Reproduce
  1. Download the promo build installer
  2. Download takes more than half hour to complete. 
  3. Run the setup, complains setup is incompatible

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/36012376-bed75378-0d83-11e8-8e4d-ddc9b40e26db.png)
Installer shows generic windows app icon and not the installer icon
![image](https://user-images.githubusercontent.com/17010094/36012411-eee0c0d6-0d83-11e8-814b-9114211a2070.png)

**Expected result:**
Should install correctly 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
N/A

### Additional Information
cc: @bsclifton @petemill @aekeus

**Comment by petemill** [comment]
Github release .exe works fine, so would be good to check the download from s3, before taking a look at the renamed-url-fetching code on staging.brave.com

**Comment by srirambv** [comment]
Working now. Closing the issue
