### ISSUE TITLE
the "Actions" column on about:preferences#payments should not be clickable because it isn't sortable

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13074]
if you go to about:preferences#payments and click on the "Action" column header, it attempts to sort. 

it shouldn't be clickable.

**Comment by btlechowski** [comment]
Verified 0.21.9 Win64

**Comment by LaurenWags** [comment]
Removed QA/checked labels due to changes in milestones. Please recheck with 0.21.15 and higher.
