### ISSUE TITLE
Ref code missing in update string

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13082]
### Description
Ref code missing in update string

### Steps to Reproduce
  1. Install promo build
  2. Click on update from settings
  3. Open updateLog.log, ref code is set to none in the update string

**Actual result:**
Ref code missing in update string

**Expected result:**
Should contain ref code

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
N/A

### Additional Information
cc: @aekeus

**Comment by diracdeltas** [comment]
note from slack: promo code should be deleted from state 90 days after first run

**Comment by btlechowski** [comment]
Verified.
updateLog contains the promoCode in the link
sessionstore contains referralPromoCode.
 
```
Brave: 0.20.38 
V8: 6.4.388.41 
rev: f4ecddc0cbc5a053904e9be8d1e2b0f1d902c953 
Muon: 4.7.10 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
```

**Comment by kjozwiak** [comment]
Thanks for the verification @btlechowski! Marking as "Verified" under Win.

**Comment by LaurenWags** [comment]
Works on MacOS 10.12.6 (using ledger_environment=staging and `0.20.40`):
![screen shot 2018-02-13 at 6 43 32 pm](https://user-images.githubusercontent.com/28145373/36180309-d19b3a98-10ed-11e8-931b-d61ccfad1d8f.png)

**Comment by kjozwiak** [comment]
Went through the above STR/Test Case using `0.20.41` 7bc4c2c8e6ef052407c581a61fc00b584b78f17d on the following macOS/OSX platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX 10.10.5 x64 VM - PASSED

Quick Note: to get this correctly working, ensure that you're actually using a real promo code that has been created via publishers.
