### ISSUE TITLE
promoCode file is NOT generated when installation file has (1) suffix

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13089]
## Test plan

https://github.com/brave/browser-laptop/pull/13091#issue-168381710

----

### Steps to Reproduce

  1. Open Firefox
  2. Download Brave from https://staging.brave.com/ABC-123
  3. Download again Brave from https://staging.brave.com/ABC-123
  4. Run downloaded file from 3.

**Actual result:**
promoCode file is NOT generated

**Expected result:**
promoCode file is generated

**Reproduces how often:**
100%

### Brave Version
Brave: 0.20.33 
V8: 6.4.388.41 
rev: 820ba31f6f1faa314ffef34881ead052cba8abd5 
Muon: 4.7.10 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 

### Additional Information
This only happens in Firefox, which appends (1) just after the file being downloaded, if the file of the same name exists. Chrome adds a space before (1) and promoCode is created.
```
Firefox: BraveSetup-x64-ABC123(1).exe
Chrome: BraveSetup-x64-ABC123 (1).exe
```

**Comment by LaurenWags** [comment]
Test on MacOS 10.12.6 when downloading from both FireFox and Chrome.
