### ISSUE TITLE
macOS download info: File download progress

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#13086]
When downloading a file from Safari, there is a progress bar shown on the file in the Finder:

![](https://user-images.githubusercontent.com/19424103/36044000-cd2fbe48-0d96-11e8-9a03-35d7d926929d.png)

To implement this, the `com.apple.progress.fractionCompleted` file attribute should be set to a number from 0.0 to 1.0, and the file creation date should be set to `1984-01-24 08:00:00 +0000`. ([info](https://stackoverflow.com/questions/15018052/how-to-show-a-progress-bar-on-files-icon))

Labels:  `suggestion`, `OS/macOS`, `feature/download`

**Comment by bsclifton** [comment]
Mildly related: https://github.com/brave/browser-laptop/issues/3023 (Support tray progress bars for downloaded items)

Unless this functionality is already present, it would need to be implemented in Muon

**Comment by Liunkae** [comment]
Implemented in brave-core.
