### ISSUE TITLE
Back and forward keyboard shortcuts don't work (on nordic keyboards?)

### ISSUE THREAD

**Issue by vinicentus** [brave/browser-laptop#13096]
### Description

**EDIT:** I'm using a Nordic keyboard (Swedish).
The current shortcuts `Ctrl + [` for back and `Ctrl + ]` for forward don't work. To type `[` on a Nordic keyboard you need to press `Altgr + 8`, unlike on English ones where there is a specific button for it.  `Ctrl + 8` shows tab number 8 and `Ctrl + Altgr + 8` does nothing.

[image of nordic keyboard](https://linustechtips.com/main/applications/core/interface/imageproxy/imageproxy.php?img=http://i.imgur.com/GWhEX.png&key=0e7ae215e9d9801fa53f6b29e2c1282b2fc51346b510a9242d4463ada5e382fa)

### Steps to Reproduce

Try to type `Ctrl + [` **on a Nordic keyboard** and you'll see.

**Actual result:**

Nothing happens.

**Expected result:**

The shortcuts should go back or forward in browsing history for the current tab.

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

Yes

**Comment by eiyey** [comment]
+1, I said this too in this post #13009

**Comment by srirambv** [comment]
@vinicentus  is this on specific keyboard layout like @eiyey mentioned in his post?

**Comment by vinicentus** [comment]
> @vinicentus is this on specific keyboard layout like @eiyey mentioned in his post?

Yes, I'm using a nordic keyboard, where `AltGr + 8` types `[` and `AltGr + 9` types `]`.

**Comment by bsclifton** [comment]
Shortcut works on macOS; I wonder if there is a conflict with the shortcut (ex: two actions are assigned the same shortcut / accelerator)

**Comment by vinicentus** [comment]
> Shortcut works on macOS; I wonder if there is a conflict with the shortcut (ex: two actions are assigned the same shortcut / accelerator)

@bsclifton Using what keyboard layout? English probably works as expected, Nordic on the other hand...

**Comment by ile** [comment]
I have been using Alt-left and Alt-right on Chromium, and they don't seem to work on Linux/Brave 0.22.669.

**Comment by bsclifton** [comment]
I have a feeling this is fixed with the Developer channel release that we had yesterday:
https://brave.com/download-dev

@vinicentus it's still experimental, but if you wanted to confirm that this new Dev channel build fixes it, that would be awesome. @Jacalz are you able to test this too?

**Comment by vinicentus** [comment]
@bsclifton You can't really add a key to a keyboard by software xd. So the shortcut doesn't work (even when pressing `Ctrl + Altgr + 8`. Pressing `Alt + LeftArrow` / `Alt + RightArrow` does work on both brave stable and dev (probably on all keyboard layouts). It's just misleading that brave stable states that `Ctrl + ]` works when there is no single button on nordic keyboards for `]`.

**Comment by bsclifton** [comment]
@vinicentus I understand that- but with the new Developer channel, are the shortcuts more friendly? So that you're not having to push <kbd>Altgr</kbd>?
