### ISSUE TITLE
No history for reopened tabs

### ISSUE THREAD

**Issue by vinicentus** [brave/browser-laptop#13095]
### Description

No tab specific history available in reopened tabs (`Ctrl + Shift + T`).

### Steps to Reproduce

  1. Open a new tab.
  2. Browse to a website.
  3. Browse to another website.
  4. Close the tab.
  5. Reopen the tab using `Ctrl + Shift + T`.

**Actual result:**

The last viewed website loads, but you can not see that you in the same tab viewed another website before that.

**Expected result:**

The last viewed website loads and you should be able to go back to the first website you opened in the same tab.

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

Yes

**Comment by eljuno** [comment]
Duplicate of #2702?

**Comment by vinicentus** [comment]
> Duplicate of #2702?

Yup. Nevermind then
