### ISSUE TITLE
Adblock issue on v0.20.35 (allmusic.com, youtube.com)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13090]
### Description
Ad's leak on allmusic.com

### Steps to Reproduce

  1. Visit allmusic.com
  2. Select a genre and click on an artist page
  3. Scroll down, ad's seen on the right navigation pane

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/36057290-52b0d098-0e32-11e8-9c6a-6cc87532fbc5.png)

**Expected result:**
Ads to be blocked

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.35
-- | --
V8 | 6.4.388.41
rev | 6e8dbe6
Muon | 4.8.1
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Yes

### Additional Information
#7421

**Comment by lukemulks** [comment]
Note - also seeing issues reported with display ad in hero panel on youtube.com on brave v0.20.35 muon v4.8.1 

Block counts display as 0 on v0.20.35 from @srirambv profile
I'm seeing blocking function as expected on v0.20.30. 
cc: @bsclifton

**Comment by lukemulks** [comment]
Note: I ran an additional check - this time for allmusic.com - in v0.20.30, and confirm that I'm observing ad blocking function as expected for allmusic.com in 0.20.30. 
![brave-allmusic-02092018-luke-windows](https://user-images.githubusercontent.com/8979240/36058967-cb33663e-0de2-11e8-9551-7507b967fdce.PNG)

**Comment by bbondy** [comment]
confirming latest hotfix is not working as in comment 0

**Comment by bbondy** [comment]
Verified this is broken for muon 4.8.1 but works in muon 4.7.10

**Comment by cryptojennie** [comment]
+1 from community here (0.20.35) for YouTube: https://www.reddit.com/r/BATProject/comments/7wlf26/getting_youtube_ads_on_the_brave_browser_since/

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/ecamer34/status/962355380977205249

**Comment by eiyey** [comment]
Ads leak on Twitter too.

It only happens with ads that display videos, with pictures the blocker works fine.

![ads](https://user-images.githubusercontent.com/36115757/36074246-bda8fcb6-0f3d-11e8-9f7e-7676925c0116.png)
![ads1](https://user-images.githubusercontent.com/36115757/36074278-2b42aefc-0f3e-11e8-88a2-6c3208fec999.png)
![ads2](https://user-images.githubusercontent.com/36115757/36074280-30515dbc-0f3e-11e8-8eb1-34ada660bf86.png)
