### ISSUE TITLE
Replace Fanboy's Swedish with Frellwit's Swedish Filter for Swedish regional adblock filters

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#13092]
## New description

This fix was broken by [this commit](https://github.com/brave/muon/commit/3fb05f239797bfe7aa8ac13962aba81600c87618#diff-946813de8d9b30857edae58aec4f3a7f) in [brave/muon](https://github.com/brave/muon) since the new ad-block dep has one new fix but is currently 16 commits behind master! That is why the better ad-block fix for Swedish users are not there yet. Since it sadly got removed from what I see was a mistake 👍 Thus should [this commit](https://github.com/brave/ad-block/compare/C65) be merged to master and then the ad-block dep should be updated in Muon 🙂 

### Test plan

1. Go to about:adblock
2. Verify that it says Frellwit's Swedish and not Fanboy's Swedish for the swedish filter lists
3.  Go to [Expressen](https://expressen.se) and verify that no ads are shown

### Description
Fanboy's Swedish is no longer maintained and has not been maintained for a year now, thus we should replace it with [Frellwit's Swedish Filter](https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt) that is maintained almost every day!
The new filter is way better with blocking ads on Swedish sites and will probably result in a better ad blocking experience for Swedish users.

Initial support is already merged to brave/ad-block with https://github.com/brave/ad-block/commit/d549e9afb5ec6ce01c6be3193b631db8bee53fe5 now we are just waiting for a new muon build containing the latest ad-block dependency.

See: https://github.com/brave/muon/pull/486

**Comment by bsclifton** [comment]
The new 0.21.x is still using Muon 4.8.2; I'll move this to 0.22.x (what used to be 0.21.x) which features Muon 5.0 and has the fix needed for this 😄

**Comment by Jacalz** [comment]
Thanks 🙂

**Comment by bsclifton** [comment]
Looks like this shipped with 0.21.x (via Muon 4.8.3). Adjusting milestone to match

**Comment by Jacalz** [comment]
This did not ship with Muon 4.8.3, I have 4.9.3 and it is not in that version. I have tested with 5.x.x and it is in those releases for me...

**Comment by Jacalz** [comment]
To be honest I dont see it in latest 0.22.x build either right now, but I did in an earlier version 😓

**Comment by bsclifton** [comment]
@Jacalz can you check the Muon branch used for this, to see if your change is there?
https://github.com/brave/muon/tree/5.1.x+65.0.3325.181

**Comment by bsclifton** [comment]
@Jacalz do you have steps to test this also? or can you provide the testing support?

**Comment by Jacalz** [comment]
I see the problem here now why this is not fixed! First I updated it to latest version [here](https://github.com/brave/muon/pull/486/files) then @bridiver changed the ad-block dep [here](https://github.com/brave/muon/commit/3fb05f239797bfe7aa8ac13962aba81600c87618#diff-946813de8d9b30857edae58aec4f3a7f) but that commit has not been merged in to [brave/ad- block](https://github.com/brave/ad-block) yet and that branch does not have my fix since it is 16 commits behind master 👎

**Comment by Jacalz** [comment]
The issue has been updated with test plan and the news about what happened @bsclifton 👍

**Comment by Jacalz** [comment]
First step to fix this is in ad-block and can be found here: https://github.com/brave/ad-block/pull/94

**Comment by Jacalz** [comment]
Second step will be to update the ad-block dep in brave/muon

**Comment by bbondy** [comment]
I'll be updating the dep soon for inclusion of easy privacy by default.

**Comment by bsclifton** [comment]
Per @bbondy next steps:
> Update the [muon DEPS here](https://github.com/brave/muon/blob/master/DEPS) to the latest rev for ad-block, tracking-protection, hashset-cpp, and bloom-filter-cpp and make sure it builds.  Then QAing to make sure it downloads the new DAT file for the .dat file and doesn't try to use the old v3 one

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/muon/pull/614

Along with that, we should also get Easy Privacy

**Comment by Jacalz** [comment]
Awesome work guys, thanks for getting this now 👍 Will have a go at testing this as soon as we get a new 0.23.x build 😀

**Comment by Jacalz** [comment]
After testing around 30 Swedish sites and comparing to the current stable releases, the conclusion is that sites generally have a lot more trackers and ads blocked but a lot of sites show a noticeable speed improvement. 👍  Have not been able to find any regressions and things are looking really smooth 😄

**Comment by Jacalz** [comment]
No additional testing will be required in my opinion 👍

**Comment by kjozwiak** [comment]
@Jacalz thanks for going through this and verifying the fix! Really appreciate all your hard work and effort ❤️
