### ISSUE TITLE
No shortcuts for opening session tabs

### ISSUE THREAD

**Issue by vinicentus** [brave/browser-laptop#13094]
### Description

We don't currently have any shortcuts for opening session tabs (edit: we do have `Ctrl + Shift + S`). `Ctrl + Alt + number` for Windows and Linux and `Option + Cmd + number` on MacOS were removed because they interfered with typing special characters (#13015, #13042). What should the shortcut(s) be now? Should it stay the same?

I think we can make it stay the same with event handlers:
https://github.com/brave/browser-laptop/blob/6fb1ad5ca10fea5dd8b9cdf3b6400b1784c08f8b/app/renderer/components/main/main.js#L147

https://github.com/brave/browser-laptop/blob/46a3b05646be013efffc8ed1eb931ebde66bda2d/app/common/constants/keyLocations.js#L5-L10

Or we could change it to `Ctrl + Shift + number` on Windows and Linux (my suggestion). We have to think about the MacOS shortcuts though.

### Steps to Reproduce

Press session tab shortcut (previously `Ctrl + Alt + number` for Windows and Linux and `Option + Cmd + number` on MacOS)

**Actual result:**

Nothing happens on Mac and Linux, Windows handles Ctrl + Alt as AltGr and therefore you can type special characters this way (see #6915).

**Expected result:**

A session tab should open.

**Reproduces how often:**

Always, starting from [Release Channel v0.20.36](https://github.com/brave/browser-laptop/releases/tag/v0.20.36dev).

### Brave Version

**about:brave info:**

 
Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

No

### Additional Information

We probably don't want to type @ when pressing Ctrl + alt + 2 if we just want to open a new session tab...

**Comment by eiyey** [comment]
Ctrl + T works for me. Try it and tell us if work for you.

Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by vinicentus** [comment]
> Ctrl + T works for me. Try it and tell us if work for you.

`Ctrl + T` is hte shortcut for opening a new tab, not a new session tab.

**Comment by vinicentus** [comment]
> Ctrl+Shift+S works fine on Windows for opening a session tab on the release build and beta build. Not sure if it is set different on a different regional keyboard.

Thanks! Didn't even know about that shortcut. To clarify though, I'm talking about the ones that got removed here:  #13042.

**Comment by eljuno** [comment]
+1 from me. As a user who uses session tabs often, shortcut to open specific session would really help. The current `Ctrl + Alt + number` on stable version is working great although it should be reverted in next release.

 Would love to have `Ctrl + Shift + number` as a replacement. :)

**Comment by vinicentus** [comment]
+1 from [here](https://github.com/brave/browser-laptop/issues/13000#issuecomment-362880783)

**Comment by madorb** [comment]
Agreed, session tabs are the "killer feature" that keep me using brave. Would really love for this to return

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/hanifigunes/status/1010563751274151941

`Ctrl + Shift + Number to open specific session tab.`

**Comment by efugier** [comment]
For me (linux) `Ctrl + Shift + Number` doesn't work and `ctrl + Shift + S` increments the session number every time, making it unsuable.

**Comment by bsclifton** [comment]
Unfortunately, this isn't something we'll be able to address with the current code-base. You can track the session window feature request in the new code-base with https://github.com/brave/brave-browser/issues/34
