### ISSUE TITLE
Brave icon looks too small on Windows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#13093]
Please see this reddit thread:
https://www.reddit.com/r/BATProject/comments/7whl3r/sorry_if_im_being_too_picky_but_for_such_an/

@jamesmudgett or @bradleyrichter could you assist?

**Comment by bradleyrichter** [comment]
I’ll enlarge them in the 0.21.0 builds.

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13290; icons were updated 😄 👍
