### ISSUE TITLE
brave won't find updates after cancelling `Add Helper` prompt

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13109]
### Description

When you click on `Cancel` during the `Add Helper` prompt while updating Brave from a `pkg` installation, Brave will stop finding updates until the browser is restarted.

As mentioned below, this might be resolved/fixed once #13106 is addressed.

### Steps to Reproduce

  1. install `0.20.36` using the `pkg` installer
  2. launch brave and select `Hamburger Menu` -> `About Brave` -> `Check for updates`
  3. click on `Update` once Brave finds and update and displays the update notification
  4. click `Cancel` on the `Add Helper` prompt
  5. check for updates again using `Hamburger Menu` -> `About Brave` -> `Check for updates`

You'll receive `Sorry, there are no updates yet. Please check back soon.`

**Actual result:**

Once clicking on `Cancel` on the `Add Helper` prompt, Brave will stop finding updates until it's restarted.

**Expected result:**

Even if a user clicks on `Cancel` on the `Add Helper` prompt, Brave should let the user know that there's an update when using `Check update...` under the hamburger menu.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**

No, only reproducible when Brave was installed using a `pkg` installation.

### Additional Information

This could possibly be resolved/fixed when #13106 is addressed

**Comment by LaurenWags** [comment]
Checked on MacOS 10.12.6 updating `0.20.39` to `0.20.40`:
- No 'Add Helper'
- Brave automatically relaunched
- Verified about:brave was updated as expected

**Comment by kjozwiak** [comment]
Went through the same test cases that @LaurenWags mentioned above using the following macOS/OSX platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX 10.10.5 x64 VM - PASSED
