### ISSUE TITLE
download save-as window 'pops under' when opening auto-download link in new tab

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#13101]
Could not find a similar issue.

### Description
The save-as window 'pops under' when opening an auto-download link in a new tab in Linux. This makes Brave unresponsive until one shifts focus to the save-as window (e.g. through alt-tab) and closes it.

### Steps to Reproduce
  1. Go to https://brave.com/download/
  2. Ctrl-click the windows logo
  3. or right-click the windows logo and chose 'open link in new tab'

**Actual result:**
![bravedownload](https://user-images.githubusercontent.com/1306453/36101643-30b1e37c-100a-11e8-9003-5e6a8072f92f.png)

The save-as window is behind the Brave window. The save-as window is therefore not visible at all when the Brave window is maximized.

**Expected result:**
Save-as window in front of Brave window.

And: the Brave window should stay responsive while the save-as window is open. (Maybe I need the browser to determine where to save the file or how to name it.)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 3.10.0-693.11.6.el7.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**
I think so.

**Comment by bsclifton** [comment]
@hugobuddel does this still happen? With 0.22.13, we had some dialog improvements. Please let us know 😄

**Comment by hugobuddel** [comment]
Thanks @bsclifton the problem is gone!

I do not like such modal dialogs much though:
- Often I want to base the name of the file on some text shown on the page. (E.g. sometimes pdfs are just an article identifier, while I'd like the title or authors in the filename.) But it is not even possible to see the text once the save dialog is open, let alone copy it. (E.g. moving the dialog box also moves the parent window.)
- It is impossible to use any of the other tabs while the save dialog is open. There is, in my mind, no strong correlation between activities in different tabs, so no reason to block other tabs if there is a file being saved. "The browser is the operating system," so it should never block.

This is not Brave specific it seems, because other apps like Firefox and Geany do this too. But e.g. Evince shows the same dialog box as Brave, but still allows the main window to be activated. (Using Scientific Linux 7.4 at work, with some Gnome 3 version as WM.) I don't really see the use case for modal save dialogs.

But that is a different problem, the 'hidden-dialog' problem is solved so closing this.
