### ISSUE TITLE
updates are not working under macOS when using pkg installers

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13106]
### Description

Brave installations using the `pkg` installers are not updating to the latest version. It's correctly working when using `dmg` installers. Example:

* installing `0.20.36` via `pkg` and updating -> `0.20.37` - FAIL
* installing `0.20.36` via `dmg` and updating -> `0.20.37` - PASS

### Steps to Reproduce

  1. install `0.20.36`
  2. select `Hamburger Menu` -> `About Brave` -> `Check for Updates..`
  3. you'll receive a macOS prompt requesting credentials to install a new helper tool
  4. insert your macOS credentials and select `Add Helper`
  5. click on `Update` and Brave will close (notice Brave won't relaunch automatically anymore)
  6. open Brave and visit about:brave, it's still on `0.20.36`

**Actual result:**

Brave is not re-launching/updating `pkg` installations.

**Expected result:**

Updates should be correctly working when updating a `pkg` installation. Should behave the same way `dmg` installers do.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

 
```
Brave: 0.20.36 
V8: 6.4.388.41 
rev: bba0b928164f8b3056a1d9be02c738c66202807c 
Muon: 4.7.10 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**

Recent regression when using the `pkg` installer.

**Comment by bsclifton** [comment]
@petemill and I have updated the `update-external-binaries.py` file in Muon to the latest release (1.2.2 https://github.com/electron/electron-frameworks/releases - was on 1.1.0).  This has fixes, such as this one that Pete found:
https://github.com/Squirrel/Squirrel.Mac/pull/207

We're in the process of compiling so we can build a package + try the installation / update process

**Comment by LaurenWags** [comment]
Checked on MacOS 10.12.6 updating `0.20.39` to `0.20.40`:
- No 'Add Helper'
- Brave automatically relaunched
- Verified about:brave was updated as expected

**Comment by kjozwiak** [comment]
Went through the same test cases that @LaurenWags mentioned above using the following macOS/OSX platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX 10.10.5 x64 VM - PASSED
