### ISSUE TITLE
Some entries (including pinned) disappear and then get re-added to ledger as unpinned

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13102]
### Description

This issue depends on the profile (it won't reproduce on a clean profile), but I am seeing entries disappear from Brave Payments and then get re-added. It seems that each visit removes/re-adds the entry.  The sites which are affected are ones that disappeared after experiencing this bug:
https://github.com/brave/browser-laptop/issues/12274

### Steps to Reproduce

  1. Have my profile
  2. Pin wikipedia.org
  3. Visit wikipedia.org

**Actual result:**

Synopsis information (time spent, # visits, etc) is lost and a new entry is created

**Expected result:**
The existing entry should accumulate and increment for additional visits

**Reproduces how often:**

100% of the time w/ my profile

### Brave Version

**about:brave info:**

0.20.x

**Reproducible on current live release:**

Yes

### Additional Information

Related: https://github.com/brave/browser-laptop/issues/12274

**Comment by bsclifton** [comment]
+1 via https://community.brave.com/t/pinned-brave-payments-getting-unpinned-automatically-macos-0-20-30/15772

**Comment by bsclifton** [comment]
+1 via https://www.reddit.com/r/BATProject/comments/7wjf1b/psa_my_pinned_brave_payment_sites_have_been/

**Comment by kjozwiak** [comment]
@bsclifton is this the same bug as #12274 as they share the same PR/Fix? Do they share the same STR/Test Plan?

**Comment by kjozwiak** [comment]
While going through the above with @bsclifton, we also found #13134.
