### ISSUE TITLE
Charles Schwab website doesn't work

### ISSUE THREAD

**Issue by Tomatoshadow2** [brave/browser-laptop#13100]
Charles Schwab website is blank white page, only allowing you to log in

### Steps to Reproduce

  1. Go to https://lms.schwab.com/Login?clientId=schwab-prospect&startInSetId=1&redirectUri=https://client.schwab.com/login/signon/authcodehandler.ashx&enableappd=false
  2. Should send you to the website, but redirects to this with just login displaying
  3.

**Actual result:**
Displays blank white page, with just a login box on upper right

**Expected result:**
Should load page and display normally

**Reproduces how often:**
100%
Also happens on Beta and Release builds. Doesn't occur in Firefox Nightly, could someone please check in Chrome?

 Brave Version
 
Brave: 0.22.2 
V8: 6.4.388.41 
rev: 0c9cccffc00bbdf812c416adc2f9bb9fbbb22425 
Muon: 5.0.2 
OS Release: 17.4.0 
Update Channel: Nightly 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Yes

**Comment by benjibee** [comment]
The you provided has the same behavior in Firefox, Safari, and Google Chrome, as well as Brave. But if I go to [https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx](https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx) I can see the issue you mention, and it only has this behavior in Brave.

**Comment by Tomatoshadow2** [comment]
Yes, it would just redirect me to that link you mentioned.

**Comment by bsclifton** [comment]
Looks like this is fixed with brave-core 😄

**Comment by arooni** [comment]
running 

0.25.2
--

the basics of the schwab.com site seem to be working but one thing that definitely doesn't work is the handy live chat feature.  

any plans to support this?

**Comment by arooni** [comment]
> Looks like this is fixed with brave-core

?? i'm still experencing this with 0.25.2  --- the live chat doesn't seem supported.

**Comment by bsclifton** [comment]
@arooni "Brave Core" is the new version of Brave on desktop. You can download a copy here and import your profile:
https://brave.com/download
