### ISSUE TITLE
Can't log in to site members.spamcop.net because login dialog isn't displayed

### ISSUE THREAD

**Issue by BertHyman** [brave/browser-laptop#1311]
Brave 0.9.0
Windows 7 Pro SP1 64-bit

When connecting to http://members.spamcop.net the site should generate an "Authentication Required" dialog for me to enter my userid and password. This works on IE, Firefox and Chrome.

With Brave, the dialog is never displayed, perhaps because Brave thinks it's a popup that needs to be blocked. Since popup blocking can't be disabled, I'm stuck.

**Comment by TheFallenOneGOTH** [comment]
Able to confirm:
**Operating System**: Windows 10 Version 1511 (OS Build 10586.164)
**Brave**: 0.9.0
**Electron**: 0.37.3
**libchromiumcontent**: 49.0.2623.108
**V8**: 4.9.385.33
**Node.js**: 5.10.0
**Update channel**: dev

**Comment by luixxiul** [comment]
I think this is the same issue as #902

**Comment by privatzee** [comment]
The auth prompt works now, 
Win7 x64
Brave 0.12.5

**Comment by bsclifton** [comment]
Closing issue as I've also confirmed this works now; browser-laptop side was fixed with https://github.com/brave/browser-laptop/commit/bb27ec23021680ecb314e33fa24b7a3dfd8a2d33
