### ISSUE TITLE
Publisher option update is called to often

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13116]
### Description

In https://github.com/brave/browser-laptop/pull/12287 we added more aggressive verification, which is called very often. We need to batch requests together, so that we can free the process.

**Comment by kjozwiak** [comment]
@NejcZdovc could you please add a test plan that will cover this so QA can run through it?

**Comment by srirambv** [comment]
Discussed with @NejcZdovc  and did the following steps to verify 
1. Enable payments on 0.21.17
2. Add 1K + ledger entries using `npm run -simulated-synopsis-visits 1000`
3. Ensure the list of dummy ledger entries is shown
4. Verify browser doesn't slow down or shows any lag when browsing with 1k+ ledger entries

Note:  Browser doesn't lag when I add 1k+ publishers but scrolling through the list of publishers does lag a little bit

**Comment by kjozwiak** [comment]
> Note: Browser doesn't lag when I add 1k+ publishers but scrolling through the list of publishers does lag a little bit

Quick note, the following issue was created for the above problem @srirambv noticed.

* https://github.com/brave/browser-laptop/issues/13340
