### ISSUE TITLE
publishers should not make requests to youtube, twitch, etc in the main process

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13114]
related: #12938

**Comment by alexwykoff** [comment]
@NejcZdovc - If we wish to change anything in bat-publisher, we'll need to land this too.

**Comment by NejcZdovc** [comment]
changing this to 0.22, because https://github.com/brave/browser-laptop/issues/13330 is in 0.22 and this will have version increase

**Comment by diracdeltas** [comment]
Test Plan: 

1. turn on Brave Payments
2. browse Youtube for a while in a regular tab; the publishers should show up in the ledger payments panel
3. repeat Step 2 for Twitch
4. browse Youtube in a private tab; this time the publishers should *not* show up in the payments panel

**Comment by bsclifton** [comment]
moved to 0.22.x

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
