### ISSUE TITLE
Block WebRTC

### ISSUE THREAD

**Issue by sterno1966** [brave/browser-laptop#13117]
### Description

it needs to block webrtc

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by luixxiul** [comment]
You can block WebRTC on the shield setting. If you don't think so, please share the URL you experience the issue. We'll invesitgate. Thanks.

**Comment by sterno1966** [comment]
ok i see it does block my bad thank you
