### ISSUE TITLE
Downloading torrent file w/o torrent viewer extension causes error

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#13121]
### Description
Downloading torrent while torrent viewer extension is disabled causes an error, even though the file is downloaded.

### Steps to Reproduce

  1. Disable torrent viewer in about:preferences#extensions (it was still disabled from 0.19.x)
  2. Go to https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/
  3. Left-click on one of the torrents and save it

**Actual result:**
Error:
> This site can’t be reached
> The webpage at chrome-extension://fmdpfempfmekjkcfdehndghogpnpjeno/webtorrent.html#https%3A%2F%2Fcdimage.debian.org%2Fdebian-cd%2Fcurrent%2Famd64%2Fbt-cd%2Fdebian-mac-9.3.0-amd64-netinst.iso.torrent might be temporarily down or it may have moved permanently to a new web address.
> ERR_FAILED

Torrent file is downloaded though.

**Expected result:**
No error.

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.17025 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119

**Reproducible on current live release:**
I think so.

**Comment by srirambv** [comment]
Think this is dupe of https://github.com/brave/browser-laptop/issues/10767

**Comment by hugobuddel** [comment]
Oh I guess you are right @srirambv. Don't know why I missed that one.
