### ISSUE TITLE
crash report generated on each launch when using referral code installer

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13127]
### Description
I noticed crash reports being generated and shown in chrome://crashes on each launch when I had installed from Brave-refcode.pkg file.

### Steps to Reproduce

Pre-req: remove any existing Brave installations and profiles.
  1. Nav to releases page and download Brave-0.20.40.pkg
  2. Install from this pkg.
  3. Launch Brave. Navigate to chrome://crashes. No crash reports listed.
  4. Remove profile and Brave.app file from Applications.
  5. Rename above package to be Brave-refcode.pkg (alternatively, you can download a new, already branded package, it doesn't matter)
  6. Install from this pkg.
  7. Launch Brave. Navigate to chrome://crashes.

**Actual result:**
Crash Report generated, but Brave continues to run. If you close and re-launch Brave, another crash report will be generated.

**Expected result:**
No Crash Report.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.20.40

**Reproducible on current live release:**
no

**Comment by kjozwiak** [comment]
Possibly related to the issue mentioned above:

When running Brave using an installer that includes the referral campaign, you'll get the following exception when launching without `LEDGER_REFERRAL_CHECK_TIME=5000 LEDGER_ENVIRONMENT=staging <app path>`:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'split' of undefined
    at onBeforeSendHeaders (/Applications/Brave.app/Contents/Resources/app.asar/js/data/siteHacks.js:134:30)
    at Array.Filtering.registerBeforeSendHeadersFilteringCB (/Applications/Brave.app/Contents/Resources/app.asar/app/siteHacks.js:34:47)
    at Function.<anonymous> (/Applications/Brave.app/Contents/Resources/app.asar/app/filtering.js:320:53)
```

We need to investigate and ensure that the above error doesn't occur for users that won't be part of the referral campaign once the production servers are live. @NejcZdovc mentioned that he'll take a look tomorrow and check against production.

**Comment by srirambv** [comment]
No crash id generated when launching 0.20.41 without `LEDGER_ENVIRONMENT=staging` variable

**Comment by kjozwiak** [comment]
Went through the above STR/Test Case using `0.20.42` 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed on the following macOS/OSX platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX 10.10.5 x64 VM - PASSED
