### ISSUE TITLE
pkg-installed Brave.app should only be updatable by admin users

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13130]
### Description
#13111 introduced a fix for updater by setting permissions on the freshly-installed Brave.app in a postinstall script. During security review it was decided it was most appropriate to set group owner to admin, and not staff, ensuring that only admin users can perform an update or removal of the app.

### Test plan
Ensure installation, running, updating and removal of the app work without error.

**Comment by diracdeltas** [comment]
(cross-posting discussion from slack)

we found that if we change the group owner to admin, we should set the owner to USER instead of root

**Comment by LaurenWags** [comment]
Verified on MacOS 10.12.6

**Comment by kjozwiak** [comment]
Went through the above STR/Test Case using `0.20.42` 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed on the following macOS/OSX platforms:

* macOS 10.13.3 x64 Desktop - PASSED
* OSX 10.11.6 x64 VM - PASSED
* OSX 10.10.5 x64 VM - PASSED

Also used `ls -alh /Applications` and ensured the entries appeared as:
* `drwxrwxr-x   3 kjozwiak  admin    96B 14 Feb 14:21 Brave.app`
