### ISSUE TITLE
When profile is corrupt, broken entries need to be pinned twice to stay pinned

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13134]
When testing https://github.com/brave/browser-laptop/issues/13102, @kjozwiak and I noticed that the fix didn't solve the issue 100%.  

We had to do the following steps to "fix" the issue:

1. Have my profile (I have a backup- contact me; needs `session-store-1` and `ledger-state.json`)
2. Pin wikipedia.org
3. Visit wikipedia.org for ~10 seconds
4. Go to preferences#payments
5. Notice wikipedia.org got unpinned
6. Pin wikipedia.org again
7. Visit wikipedia.org for ~10 seconds
8. Go to preferences#payments
9. Notice that pin stayed this time 😄

**Comment by kjozwiak** [comment]
@bsclifton we'll need to go this together on all three platforms like we did before. Hopefully you still have that profile available!

**Comment by kjozwiak** [comment]
I went through the above issue with @bsclifton while we were on a Zoom call using his personal profile. We couldn't reproduce the issue with `0.21.16` a7bed47f55863b9f48e5ce31bcaf8c6ee21c10d5. Went through the following platforms:

* Win 10 x64 VM - PASSED (couldn't reproduce the original issue)
* Ubuntu 17.10 x64 VM - PASSED (couldn't reproduce the original issue)
* macOS 10.13.3 x64 VM - PASSED (couldn't reproduce the original issue)
