### ISSUE TITLE
Add Twitch support

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13139]
### Description

Add support for Twitch into Brave Payments

**Comment by LaurenWags** [comment]
Test Cases for Twitch Testing on MacOS:
### Ledger Media - Twitch
  - [x] Visit any Twitch VOD in a normal/session tab and ensure the video publisher name is listed in ledger table
  - [x] Visit any Twitch Stream in a normal/session tab and ensure the video publisher name is listed in ledger table
  - [x] Visit any Twitch VOD in a private tab and ensure the video publisher name is not listed in ledger table
  - [x] Visit any Twitch Stream in a private tab and ensure the video publisher name is not listed in ledger table
  - [x] Visit any Twitch VOD and ensure the time spent is shown under ledger table
  - [x] Visit any Twitch Stream and ensure the time spent is shown under ledger table
  - [ ] Visit any embedded Twitch video (VOD or Stream) and ensure the video publisher name is listed in ledger table (unable to locate a site for testing embedded Twitch)
  - [x] Ensure total time spent is correctly calculated for each Twitch publisher video (note, timing for twitch is slightly different then YT - heartbeats occur anywhere from 40s to 1min20s)
  - [ ] Ensure total time spent is correctly calculated when switching to Twitch video (Stream/VOD) from an embedded video (unable to locate a site for testing embedded Twitch)
  - [x] Ensure Twitch publishers are not listed when `Allow contributions to video` is disabled in advanced settings
  - [x] Ensure existing Twitch publishers are not lost when `Allow contributions to video` is disabled in advanced settings
  - [x] Ensure Twitch publishers is listed but not included when `auto-include` is disabled
  - [x] Update Advanced settings to different time/visit value and ensure Twitch videos (Stream/VOD) are added to ledger table once criteria is met
  - [x] Perform a contribution while Twitch channels are included on the ledger. Ensure Twitch channels are listed on the contribution statement.
  - [x] Verify able to delete Twitch publishers from ledger table.
  - [x] Verify able to re-add Twitch publishers to ledger table
  - [x] Verify if you minimize a Twitch video (Stream/VOD) and navigate around the site, the video is counted in ledger.
  - [ ] Verify when resume play on a Twitch VOD the time will continue to be counted in the ledger. (issue logged for this: https://github.com/brave/browser-laptop/issues/13257)

**Comment by NejcZdovc** [comment]
@LaurenWags you can click on one of this https://www.joindota.com/en/livestreams (note you need to disable shields)
