### ISSUE TITLE
Welcome page says to click on shield icon, shield icon doesn't work

### ISSUE THREAD

**Issue by haster** [brave/browser-laptop#13138]
### Description
Shield button ("Lion"-icon) doesn't work on welcome page which tells you to click on the shield button, leading to getting stuck following "welcome" instructions.

### Steps to Reproduce
  1. (Install Brave fresh)
  2. Open brave and/or go to about:welcome
  3. Follow the instructions on the page. The 2nd set-up step is "Click on the shield icon". Try it.
  4. See how nothing happens.

**Actual result:**
Nothing happens, the shield icon is grey and doesn't respond.

**Expected result:**
The shield icon menu would appear or I would be taken to the "set up default settings" page.

**Reproduces how often:**
100% of the time

### Brave Version

**about:brave info:**
Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 4.13.0-32-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Don't know / didn't try.

### Additional Information
The shield icon's behaviour is probably working as intended, however it doesn't mash particularly well with the welcome page's onboarding guide. If a welcome page tells me to click on a menu item I expect something to happen. There are a number of possible resolutions:
- Tell the new user to go to google.com and then click on the icon (less attractive)
- Make the icon have some default behaviour in a disabled state (for example, to go to the default settings page)
- Tell the user how it clicking on the icon would work on a normal page, then tell it to click a different button to set up default preferences (my preferred solution)

**Comment by bsclifton** [comment]
cc: @bradleyrichter @davidtemkin
