### ISSUE TITLE
URL bar is slow in responding to what I am typing

### ISSUE THREAD

**Issue by haster** [brave/browser-laptop#13140]
### Description
Starting to type in the url bar of a browser tabe will lead to a visible delay (~1s) before letters start to appear in the url bar and suggestions start to appear in the suggestions list. (It seems the url bar is waiting for the suggestions to load).
Sometimes the first letter will show and then the freeze happens, sometimes no letters will show. 
At my typing speed the suggestions will usually show around the fourth letter, at which time the url bar will show the letters also.

### Steps to Reproduce
  1. Open a new browser tab
  2.  Focus the url bar
  3. Start typing the first 4+ letters of a site (eg, "face" for "facebook").

**Actual result:**
A visible delay will happen, resulting in a disconcerting experience from the url bar not showing the letters I am typing, until suddenly the suggestions list and contents of the url bar are showing all at the same time.

**Expected result:**
The letters show in the url bar as I'm typing, with no visible delay. Suggestions are shown when loaded/rendered.

**Reproduces how often:**
100% of the time, both in new browser tabs, new browser windows, and existing browser tabs where I've selected the contents of the url bar (so as to replace it) or cleared the url bar.

### Brave Version

**about:brave info:**
Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 4.13.0-32-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Didn't try.

**Comment by LaurenWags** [comment]
Reproduced this on `0.22.706` when using a large profile and typing in the URL bar showed the first character quickly, but subsequent characters were slow to show. Definitely saw this slowness when typing 'huf' and 'cnn' into the URL bar. Typing nytim or pinter didn't produce this slowness.
![lag](https://user-images.githubusercontent.com/28145373/39895380-007f2b30-5478-11e8-811a-95647fc44cca.gif)

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/elementary-os-0-4-1-loki-search-bar-autocomplete-is-to-slow/23273

**Comment by ElGatoLoco** [comment]
Any update on the issue? It's really a deal breaker for otherwise great product.
Problem persists on v0.23.79, Debian Testing.

**Comment by kenneho** [comment]
@ElGatoLoco and @LaurenWags , this sounds similar to https://github.com/brave/browser-laptop/issues/11066. Does disabling "Show history matches" in Search preferences help with the delay issue?

**Comment by kenneho** [comment]
I run the same version on my Ubuntu Budgie laptop, but still has the same issue.

**Comment by ivannp** [comment]
Able to reproduce on Windows Server 2016.

**Comment by prigoose** [comment]
Same problem on macOS High Sierra, using Brave 0.24.0. It's a big enough blocker to make Brave unusable for me

![screen shot 2018-10-01 at 9 14 28 am](https://user-images.githubusercontent.com/34298715/46301174-74140e00-c55a-11e8-9d90-cccb2dfe4319.png)
