### ISSUE TITLE
Add separator for urlBarIconContainer where EVC is not available

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13159]
### Description
Follow up of https://github.com/brave/browser-laptop/pull/13147#issuecomment-366129213

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by Liunkae** [comment]
Maybe not needed if the following comment is still relevant.

https://github.com/brave/browser-laptop/issues/7888#issuecomment-292683092 @bradleyrichter:
> a border? I like Chrome's "border". Invisible. ; )

**Comment by bsclifton** [comment]
Good catch, @Liunkae! Let's close this issue for now

@MargarytaChepiga no need to add the border (per comment by our head of design, @bradleyrichter in the original issue)
