### ISSUE TITLE
Facebook "Like Widget" looks weird

### ISSUE THREAD

**Issue by TheFallenOneGOTH** [brave/browser-laptop#1315]
![weird facebook widget on community wiki](https://cloud.githubusercontent.com/assets/8735509/14405513/7a973966-fe5e-11e5-987b-290983d49c54.PNG)

I went to visit [Wikia](http://community.wikia.com/) and immediately noticed something very strange. The notable "Like Widget" for Facebook looks weird (it's circled in the screenshot). I am running Brave 0.9.0 on Windows 10. Can anybody else confirm?

**Comment by TheFallenOneGOTH** [comment]
Able to confirm on [Planet Minecraft](http://www.planetminecraft.com) and [Minecraft.net](http://minecraft.net/). It's still a bug in Brave 0.9.1.

**Comment by TheFallenOneGOTH** [comment]
Can I get an acknowledgement from @bbondy or another Brave developer, please?

**Comment by bbondy** [comment]
third party trackers are blocked currently so this is why you're seeing it.  We'll probably be adding an option to allow social widgets though in the future.

**Comment by luixxiul** [comment]
Closing as this question has been answered.
