### ISSUE TITLE
Error page text is too light

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#13162]
### Description
IMO, some of the text on the error page is too light.

### Steps to Reproduce

  1. Disconnect from the Internet.
  2. Open Brave and navigate to any URL.
  3. Look at the text that says "The Internet connection has been lost."

**Actual result:**
The text is too light to read clearly.
![](https://user-images.githubusercontent.com/19424103/36295008-2cba02f2-12aa-11e8-9e60-e990705179f9.png)

**Expected result:**
The text should be darker so that it's readable. Maybe it should be [`@chrometext`](https://github.com/brave/browser-laptop/blob/fbdf34dfa1784501b042f900f6ee2050bd130617/less/variables.less#L23) (`#555555`)?
![](https://user-images.githubusercontent.com/19424103/36295070-95fbff22-12aa-11e8-829a-205c1f456c84.png)

**Reproduces how often:**
Always.

### Brave Version
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Yes, 0.20.42.

### Additional Information
None.

**Comment by GeetaSarvadnya** [comment]
@bsclifton Issue still persists on 0.23.8

**Comment by bsclifton** [comment]
@srirambv did you want to check this out? I verified the commit IS in 0.23.x, so I'm not sure if another style is overriding this. You might want to test using the `tor/0.23.x` branch

**Comment by srirambv** [comment]
I can check that again
