### ISSUE TITLE
Icon for mixed content is unintentionally shown as green

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13163]
### Test plan
See https://github.com/brave/browser-laptop/pull/13164

### Description

Unintentionally caused by https://github.com/brave/browser-laptop/pull/13147

### Steps to Reproduce

  1. Visit https://www.wsj.com/europe

**Actual result:**

![image](https://user-images.githubusercontent.com/4733304/36295291-d0b63102-12a3-11e8-9cf8-835953394414.png)

**Expected result:**
Page should be mixed (HTTP/HTTPS); the unlock icon should be gray
![screen shot 2018-02-15 at 11 02 26 pm](https://user-images.githubusercontent.com/4733304/36295354-606e824a-12a4-11e8-9f92-720714308d0b.png)

**Reproduces how often:**

### Brave Version
master
**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@MargarytaChepiga I self-assigned this issue to reserve it for you 😄 Will keep an eye out for a PR.  Please let me know if you have any questions

**Comment by MargarytaChepiga** [comment]
@bsclifton Thank you!

**Comment by bsclifton** [comment]
@MargarytaChepiga you probably already saw, but @srirambv had an assist for you to check out and review 😄 
https://github.com/brave/browser-laptop/pull/13164

**Comment by bsclifton** [comment]
Closing as this was fixed with https://github.com/brave/browser-laptop/commit/49a9b7379bbaf03d48bb1438512195fd6b3fdb66

The proper fix is now contained in https://github.com/brave/browser-laptop/pull/13164 😄
