### ISSUE TITLE
Downgrade .net to 3.5 in Windows 7

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-laptop#1316]
Brave installer requires .NET 4.5  to install Brave browser in Windows 7.
People don't sit and install .NET 4.5 first and then Brave.

It will be better to downgrade to 3.5 as it is coming by default.

**Comment by SJ-Diamond** [comment]
I would prefer that too. Have on several computers Windows 7 and i do not like the fact that i have to upgrade .Net ;)

**Comment by bbondy** [comment]
@paulcbetts I haven't looked into this at all yet but any particular reason why it needs .NET 4.5? If 3.5 is installed by default on Win7. Thanks!

**Comment by paulcbetts** [comment]
Porting Squirrel to .NET 3.5 would be very difficult, and also require everyone on Windows 8+ to download and install .NET 3.5. We should optimize toward people running modern software, not software old enough to start grade school :)

**Comment by bbondy** [comment]
OK thanks @paulcbetts

@iamVP7 although it would be best to not require .NET at all for an app that doesn't use it, it's the best option we have for now and porting down isn't as simple as a recompile. So I'll close this.
