### ISSUE TITLE
Search not working on ansible's doc pages

### ISSUE THREAD

**Issue by srinathkotu** [brave/browser-laptop#13166]
### Description

Searching for text on ansible's documentation pages does not work.

### Steps to Reproduce

  1. Open 'https://docs.ansible.com/ansible/latest/intro_inventory.html'
  2. Search for text 'Inventory'.
  3. None of the text in the page gets highlighted.

**Actual result:**

**Expected result:**
Text that has been searched should be highlighted

**Reproduces how often:**

anytime i try to search in ansible's documentation page

### Brave Version

**about:brave info:**

 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

**Comment by btlechowski** [comment]
Works for me on Windows 7.

@srinathkotu Does restarting the browser helps?

@LaurenWags Can you check on Mac?

```
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Comment by LaurenWags** [comment]
Unable to repro on MacOS, interested in knowing if restarting the Brave helps. If not, how are you trying to search? Right-click, select 'Find in Page' or using the keyboard shortcut (cmd/ctrl + f) or menu > edit > find in page or some other way?

**Comment by akaihola** [comment]
I can't reproduce this on the ansible page, but I get this behavior a lot on different pages. Most of the time `Ctrl-F` works just fine, but sometimes the search bar is broken.

The symptom is (in Brave 0.22.17 on Fedora 26):
- press `Ctrl-F`
- the search bar appears
- type a search term which does exist on the page
- the `<n> matches` text does not appear (not even `0 matches`)
- closing the search bar and redoing the search doesn't help
