### ISSUE TITLE
Make active tab more distinguishable than background tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13165]
### Description
Feedback from community https://community.brave.com/t/the-head-of-a-focused-tab-is-not-distinguishable-enough/16162/2

**Expected result:**
Tabs are not clearly distinguishable 

**Reproduces how often:**
100% 

### Brave Version
All

**Reproducible on current live release:**
Yes

### Additional Information
+1 from me as well
cc: @bradleyrichter @bsclifton

**Comment by rebron** [comment]
Closing. wontfix here, looks like this is fixed in brave-core with both light and dark themes.
