### ISSUE TITLE
Enhancement : One-click file open for a completed download

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#13167]
### Description

With other browsers it is quite easy to open a downloaded file from the tray. In our case, users have to do extra steps. 

Users should be given the ability to open a downloaded file with one click. 

### Steps to Reproduce

  1. Download a file
  2.Move mouse to the generated download tray card
  3.Click on the card, file should open

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

Cited request for enhancement : https://www.reddit.com/r/BATProject/comments/7xvrs6/questions_for_brave_on_mac/

**Comment by bsclifton** [comment]
Closing as `wontfix`- we can try to address this with [brave-core](https://github.com/brave/brave-browser)
