### ISSUE TITLE
Feature Request -- Arguments loaded with browser

### ISSUE THREAD

**Issue by ryanmusante** [brave/browser-laptop#13173]
How do I enable these features without using loading arguments? Which of them are redundant? I want gpu rasterization, native gpu memory buffers and fast open definitely always on. I cannot check through chrome://gpu so there is no way to verify if these are default brave settings.

### Description
--enable-zero-copy --enable-experimental-canvas-features --enable-fast-unload --javascript-harmony --enable-gpu-rasterization --enable-native-gpu-memory-buffers --enabled-new-style-notification --enable-quic --site-per-process --enable-tcp-fastopen --ignore-gpu-blacklist --save-page-as-mhtml --enable-smooth-scrolling --enable-features=CheckerImaging,MaterialDesignExtensions,OmniboxDisplayTitleForCurrentUrl,OmniboxTailSuggestions,OmniboxUIExperimentShowSuggestionFavicons,OmniboxUIExperimentVerticalLayout,SecondaryUiMd --disable-features=MaterialDesignBookmarks

### Brave Version
Brave | 0.20.42
V8 | 6.4.388.41
Muon | 4.8.2
OS Release | 4.15.4-2-MANJARO

**Comment by srirambv** [comment]
cc; @bridiver @darkdh

**Comment by bsclifton** [comment]
Happy to report this is fixed with [brave-core](https://github.com/brave/brave-browser). With this new version, you can visit `chrome://flags`. You can also view the active flags by viewing `chrome://version`
