### ISSUE TITLE
Private tab animation sometimes gets stuck

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#13178]
### Description
Sometimes, when I'm creating new private tabs with Cmd+Click, the animation gets stuck, and a dark purple gradient appears on the right side of the tab. Mousing over the tab resets the appearance and fixes the problem.

It usually happens with an inactive tab immediately to the right of the active tab. After it happens in a particular window, it usually does not happen again.

### Steps to Reproduce
  1. Open Brave, open a new private tab, and navigate to any link (e.g. GitHub).
  2. Use Cmd+Click to open links in new private tabs.

**Actual result:**
This is what the bug looks like:
![](https://user-images.githubusercontent.com/19424103/36359157-ac1ac2ea-14dd-11e8-9f7d-7a6c095fc1cb.png)
Note that the first tab is the active tab. The second tab is inactive but has a partial active gradient.

**Expected result:**
The inactive tab should look like this:
![](https://user-images.githubusercontent.com/19424103/36359180-f36643f4-14dd-11e8-9961-5e4e361f89fe.png)

**Reproduces how often:**
I run into it at least once every time I'm using private tabs.

### Brave Version

**about:brave info:**
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Yes, 0.20.42.

### Additional Information
Maybe related: #12721

**Comment by srirambv** [comment]
Possibly related to #11249. The same fix might fix this as well

**Comment by Liunkae** [comment]
Appears fixed in both 0.23.105 (current release).
