### ISSUE TITLE
Bookmark search

### ISSUE THREAD

**Issue by thynquest** [brave/browser-laptop#13172]
### Steps to Reproduce
  1. go to the browser settings 
  2. from there go to the search tab
  3. in the search parameter section check only 'show bookmark matches'

**Actual result:**
When you make a search on the address bar you have no result.

**Expected result:**
since you have bookmarked some pages, you should be able to have some results when you start searching from the address bar.

**Reproduces how often:**
Every time

### Brave Version

**about:brave info:**
Brave | 0.20.42
-- | --
V8 | 6.4.388.41
rev | 096c7cb
Muon | 4.8.2
OS Release | 4.4.0-109-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

### Additional Information
As a workaround, you have to check also "show history matches" but once you start searching from the address bar you have history macthes and bookmarks matches (which is normal btw).

Thank you for your help

**Comment by srirambv** [comment]
This is expected behaviour. Bookmarks and History search is tied together so enabling history search shows the bookmark suggestions as well. Are you expecting a different behaviour?

**Comment by thynquest** [comment]
Thank you for your answer.
Actually I think we should be able to activate only bookmarks search or history search if we want instead of tying both together; because during bookmarks search we will be polluted with history search as well even if we don't want history search; and second why giving the possibility to check one of these independently if they are tied together ?

**Comment by thynquest** [comment]
this used to work this way on the previous version and it was a good flexibility for the user to choose between having only history search, bookmarks search or both; hence the two check buttons.

**Comment by andrewklimek** [comment]
I agree with thynquest.  URL suggestions seem to favor history instead of my bookmarks, which is annoying, so I'd like to disable history suggestion.  

There are certain pages I visit many times a day, and I have them bookmarked, yet they are never the top suggestion when I start typing.  Not sure if I'm doing something wrong.

**Comment by TJ-Hooker15** [comment]
I have the same issue. If I only have the "show bookmark matches" enabled, if I start typing in the address of a site I have bookmarked no suggestions come up. If I then enable "show history matches", I then get suggestions from my bookmarks in the address bar (even though the bookmarked site is not in history). If I have only "show history matches" selected, I still get results from my bookmarks. Basically, the "show bookmark matches" toggle is currently useless.

Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Comment by arsalankhalid** [comment]
Agreed with all of the above, I'm finding the Show bookmark matches is not actually doing anything, going to debug this a little.

**Comment by Brave-Matt** [comment]
+1 from Community: https://community.brave.com/t/about-bookmarks/28103

**Comment by rebron** [comment]
Closing, marking wontfix. Sending over to brave-core #1048
