### ISSUE TITLE
Remove deadcode in menu.js

### ISSUE THREAD

**Issue by dskeppstedt** [brave/browser-laptop#13189]
### Description
There is some dead code in [menu.js](https://github.com/brave/browser-laptop/blob/master/app/browser/menu.js) that can be removed for brevity. Is this something that could be done?

For example:
https://github.com/brave/browser-laptop/blob/0777c0e0d1ee786865d382308f354bb4b1353873/app/browser/menu.js#L218-L231

https://github.com/brave/browser-laptop/blob/0777c0e0d1ee786865d382308f354bb4b1353873/app/browser/menu.js#L241-L265

**Comment by irrationalRock** [comment]
hi, i'll like to work on this
