### ISSUE TITLE
Brave fails to manipulate data-* attributes while using DataTables JavaScript library

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#13188]
Brave fails to manipulate _data-*_ attributes while using [_DataTables_ JavaScript library](https://www.datatables.net/) (e.g. "_data-title_" we are using).

Firefox is OK, Chrome is OK, even IE 11.x is OK...

What we do in one of our pages is that we transform a table before printing it. Unfortunately, it's our internal page, so I cannot give you access to it. But you should be able to reproduce it yourselves easily.

Xubuntu 17.10
Brave	0.20.42, V8	6.4.388.41, rev	096c7cb
DataTables.js version 1.10.12
JQuery 1.12.0

**Comment by btlechowski** [comment]
Thank you for the report.

Can you try turning off Brave Shield and see if it helps?

**Comment by crysman** [comment]
It seems to be working now. Even with the shield up - I do not understand... I'll try again later on to be sure. Thanks.
