### ISSUE TITLE
Remove "mailto:" When Copying Email Address

### ISSUE THREAD

**Issue by cwmke** [brave/browser-laptop#1318]
It would be nice to have the email address copied by itself similarily to what happens in Firefox.  For example, right clicking and selecting 'copy link address'  at the below address,

https://wikimediafoundation.org/wiki/Contact_us

results in 

`````
mailto:legal@Wikimedia.org
`````

Ideally, it would appear as, 

`````
legal@Wikimedia.org
`````

Thanks.

**Comment by bbondy** [comment]
For this task please make the menu item be called `Copy Email Address` and do the parsing as per above.  This would be a great first bug for a contributor.

**Comment by manninglucas** [comment]
Saw the good-first-bug tag and would like to contribute. Can I give it a go?

**Comment by bbondy** [comment]
Sure! Let us know if you have any questions. 
To get you started you'll want to change code in `js/contextMenu.js` and setup instructions are in the README.  Make sure to use Node v5.10 so the npm install works.
