### ISSUE TITLE
Add local for delete all passwords

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13181]
### Test plan
1. Fresh profile
2. Login to https://trac.torproject.org/projects/tor/login (create login if needed)
3. When prompted to remember password, choose `Allow`
4. Visit `about:passwords`
5. Click `Delete all saved passwords`
6. Verify the new string shows up (`Are you sure you want to delete all saved passwords? This cannot be undone.`)

### Description

We are missing translation for the confirmation dialog for all password deletion.

You can find missing translation here: https://github.com/brave/browser-laptop/blob/master/js/about/passwords.js#L164

**Comment by vinicentus** [comment]
Created #13196, hopefully everything ok, as I'm new to this. I used an existing string because it said the same thing and wasn't used anywhere.
