### ISSUE TITLE
Use unified uint converter

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13183]
### Description

We should use `uintKeySeed` function when dealing with the seed conversion.

**Comment by NejcZdovc** [comment]
When we start browser, seed is an object so we need to cover this scenario as well.

**Comment by bsclifton** [comment]
@NejcZdovc I know this is marked with `QA/no-qa-needed`, but do we want to cover a few scenarios? (ex: the one I discovered)
