### ISSUE TITLE
Ledger Doesn't Handle Long Titles Neatly

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13195]
### Description
A Site or YouTube Channel with a sufficiently long title can break the ledger UX.

### Steps to Reproduce
1. Visit https://www.youtube.com/watch?v=SqqqRqA2caA
2. View other videos on Channel until Creator appears in Ledger

**Actual result:**
"ThePotatoIsAStarchyTuberousCropFromThePerennialSolanumTuberosumOfTheNightshadeFamilyLOL" breaks the ledger layout.

**Expected result:**
Creator's name should not break the ledger layout.

**Reproduces how often:**
Always

### Brave Version
0.20.42

**about:brave info:**
``` 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**
Yes.

**Comment by ryanml** [comment]
Was thinking about taking this on, but then I see @NejcZdovc got it :) 

I would motion towards truncating it to n characters and then adding a trailing '...', then adding a title/label property that would show the full value on hover perhaps. Is that what you were thinking?

**Comment by NejcZdovc** [comment]
@ryanml you can take it, no problem. I was thinking of fixing all of this with css

**Comment by ryanml** [comment]
@NejcZdovc got it, thanks. I certainly don't want to over-engineer anything if you have a pure CSS solution though. If you're fine with a truncation solution, I'll open a PR, else, maybe we could go over what stylistic change might work for this. Thanks!

**Comment by ryanml** [comment]
@NejcZdovc this is what I put together [here:](https://github.com/ryanml/browser-laptop/commit/85f2cf922e02f59af384d7ff7a9c64dac00d163b)

Truncating at 45 characters was the most sensible limit before it started bleeding over.

**Comment by ryanml** [comment]
@petemill I'll squash everything before a PR would be open, but how does [that](https://github.com/ryanml/browser-laptop/commit/009e10ee5eeff6bc156e33e0a8d5c9861bc6c89b) look?

cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
pulling this one into 0.22 based on the triage call

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0

![image](https://user-images.githubusercontent.com/17010094/37800938-884ea932-2e1c-11e8-9121-789e0b7dcfbd.png)
