### ISSUE TITLE
Restricted embedding 

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13190]
### Description

Some youtube videos has restriction on them and because of that we can't log them. More info here https://support.google.com/youtube/answer/6301625?hl=en

### Steps to Reproduce

  1. go to https://www.youtube.com/watch?v=wnVWlChmxao

**Actual result:**

You are receiving 401 in the terminal and video is not added to the ledger table
`Error while getting publisher from media Error: HTTP response 401 for GET /oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DwnVWlChmxao`

**Expected result:**
Video should be added to the table

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
@flamsmark do you think that we should be adding video to the ledger table in this case or not?

**Comment by mrose17** [comment]
i will as soon as i talk to @bradleyrichter ...

**Comment by bradleyrichter** [comment]
How about adding it to the ledger with a fixed disabled include switch state?

"[YT Icon] wnVWlChmxao"   and linked back to the YT video source.

**Comment by mrose17** [comment]
there is no consensus on this. the only solution that does not involve either acrobatics or confusing the user is the one i suggested. since no one else likes that. i am moving this to the boneyard.
