### ISSUE TITLE
Login to Gmail shows the user names on the side of the page.

### ISSUE THREAD

**Issue by FirefoxWas** [brave/browser-laptop#13191]
### Description

[Description of the issue]

Gmail shows the user names on the side of the page on gmail site.

### Steps to Reproduce

  1. When I click on gmail account, I see popup with my user names on the side of gmail page.

**Actual result:**

![vxufckc](https://user-images.githubusercontent.com/32176749/36388923-539717fc-1552-11e8-847f-8b8ce01b483c.png)

**Reproduces how often:**

Everytime

What percentage of the time does it reproduce?

100%

### Brave Version

Name | Version
-- | --
Brave | 0.20.42
V8 | 6.4.388.41
rev | 096c7cb
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by btlechowski** [comment]
Thank you for the report.

Only way for me to reproduce the issue is:

**Comment by bsclifton** [comment]
cc: @darkdh

**Comment by darkdh** [comment]
intended behavior. there must be a hidden username/password form on that page.
see https://github.com/brave/browser-laptop/issues/12733
