### ISSUE TITLE
Unable to access input fields on VFS Global site when link opens via target="_blank"

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13200]
### Description
Unable to access input fields on VFS Global site when link opens via target="_blank"

### Steps to Reproduce

  1. Visit VFS Global India website
  2. Select track application
  3. Input fields are read only. Doesn't allow to type in tracking number and DOB fields
  4. Copy URL and open in a new tab, input fields are accesible

**Actual result:**
![vfs](https://user-images.githubusercontent.com/17010094/36423974-cde89cd6-1667-11e8-9463-0f53ac34c4dc.gif)

**Expected result:**
Should work

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.42
-- | --
V8 | 6.4.388.41
rev | 096c7cb
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Yes

### Additional Information
Works fine on other browsers
cc: @diracdeltas @bridiver

**Comment by diracdeltas** [comment]
do you have 'strict site isolation' enabled by chance?

**Comment by srirambv** [comment]
Yup missed that. My bad.
