### ISSUE TITLE
Linux Beta is completely broken

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13208]
Main Window is misplaced. Covers Taskbar and lacks Titlebar with Minimize/Maxmize/Close buttons. 
Cannot move the window around.
Most of the items in Menubar don't work. Those that work are: File-New Tab; File-New Private Tab; File-New Session tab; File-New Window; File-Quit Brave
Cannot type into URL

Tested on Ubuntu, BraveBeta v0.21.9. Cannot access about:brave for full report.
![image](https://user-images.githubusercontent.com/34715963/36439320-d21c58d8-166c-11e8-9e7c-2dedb7b44f22.png)

**Comment by darkdh** [comment]
fixed by brave/muon#495

**Comment by bsclifton** [comment]
@btlechowski if this is a dupe (you'll be able to test once a new build is available), can you label this issue with `duplicate` and remove the milestone? Thanks 😄
