### ISSUE TITLE
Double lines in right click

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-laptop#1321]
![right_click](https://cloud.githubusercontent.com/assets/3106852/14409022/6630d7fa-ff28-11e5-8c6e-cd82e7e4a0f5.png)

OS : Ubutnu 14.04 x86_64

In Google search, right click on the links gives list of option. We have both double lines and single lines, instead of Single lines alone.

**Comment by TheFallenOneGOTH** [comment]
Confirmed for Windows 10, Brave 0.9.0. The double lines are barely visible.
