### ISSUE TITLE
set duckduckgo as default search engine in tor mode

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13212]
test plan:
1. open new private tab, disable both tor and ddg.
2. turn on tor
3. DDG should also turn on
4. it should be possible to disable DDG
5. it should be possible to still use DDG with Tor off

**Comment by flamsmark** [comment]
If DDG is already the default, what's the change here?

**Comment by diracdeltas** [comment]
default for all browsing or default for private browsing only?

either way, if someone sets non-default search settings, those shouldn't be affected by this change

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
