### ISSUE TITLE
Brave Payments turned OFF automatically + Extensions Tab = empty

### ISSUE THREAD

**Issue by mandar-brave** [brave/browser-laptop#13226]
### Description

After some usage (no particular pattern) I have my 'payments flag' turned off - see image.
I am unable to turn it back ON

### Steps to Reproduce

  1. Just regular usage - did not do anything particular (will update here if there is something to update)
  2. New tabs are black
  3. Extension tab on settings is blacked out (so may be related to existing issue)

A restart clears the issue; flag is toggled OFF but can be toggled back ON.

**Actual result:**

![image](https://user-images.githubusercontent.com/35932307/36492712-9f18b550-16e2-11e8-8d93-332867e4427a.png)
![image](https://user-images.githubusercontent.com/35932307/36492720-a90b4bcc-16e2-11e8-82d6-ef2963b4686d.png)

**Expected result:**
Flag was ON and should be set as ON
Extensions tab cannot be empty
New tab should show homepage

**Reproduces how often:**

Seen it only once

### Brave Version

**about:brave info:**

v.20 (Latest build on Feb 21, 2018)

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
I suspect this was fixed with https://github.com/brave/browser-laptop/pull/13234
