### ISSUE TITLE
Brave prevents the computer from shutting down (macOS-only)

### ISSUE THREAD

**Issue by louity** [brave/browser-laptop#1322]
When brave is running on my mac, even if no window is open, when I try to shut my computer down i get this alert message (my computer in in French) (see comment below), which means : Brave interrupted shutting down. Quit Brave and re-try. 

So i have to go and  brave and do a <cmd> + Q to quit brave to be able to shut down the computer.

**Comment by louity** [comment]
<img width="1280" alt="capture d ecran 2016-04-10 a 12 35 19" src="https://cloud.githubusercontent.com/assets/14196488/14409645/9663c112-ff19-11e5-9fa1-a933da3ef538.png">

**Comment by endeakidz** [comment]
I got this error too

**Comment by 1F506** [comment]
can't shut down or log out.

**Comment by luixxiul** [comment]
Reproducible? CC'ing @bbondy

**Comment by bbondy** [comment]
I think this was fixed with 0.9.6, but please re-open if you still see it.

**Comment by Hazz223** [comment]
Hi, I'm running 0.10.0 and found this is still an issue.

**Comment by bbondy** [comment]
@bridiver do you think your shutdown fixes will solve this?

**Comment by bbondy** [comment]
0.10.2

**Comment by bbondy** [comment]
Let's mark as completed for 0.10.1 because there's work here and if it still fails after that we'll reopen

**Comment by bridiver** [comment]
this doesn't seem to be related to the shutdown issue because Brave is still visibly running. Perhaps it's not responding to the OS shutdown notification? SIGTERM probably?

**Comment by bbondy** [comment]
I was assuming we're getting a quit but we aren't actually quitting.

**Comment by bbondy** [comment]
I tried to repro and couldn't before by the way.

**Comment by bbondy** [comment]
has anyone seen this again?

**Comment by bridiver** [comment]
I was able to replicate last time I tried and I believe this is the problem
```
- (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication*)sender {
  atom::Browser* browser = atom::Browser::Get();
  if (browser->is_quiting()) {
    return NSTerminateNow;
  } else {
    // System started termination.
    atom::Browser::Get()->Quit();
    return NSTerminateCancel;
  }
}
```

**Comment by bridiver** [comment]
it should return `NSTerminalLater` and call `[NSApp terminate:nil]` when shutdown is complete

**Comment by Liunkae** [comment]
Is this something that needs to be fixed on the Muon side?

**Comment by bsclifton** [comment]
Closing as stale since there haven't been any reports. I haven't experienced this myself- please reopen if you do experience this 😄
