### ISSUE TITLE
Save link as doesn't add file extension to save dialogue window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13228]
### Description
Save link as doens't add file extension to save dialogue window

### Steps to Reproduce

1. Go to https://brave.com/
2. Right click on Download Brave
3. Save Link As
4. The default path should be your download path
5. The dialog doesn't have  extension option with dmg/exe/deb

**Actual result:**
![11906-savelink](https://user-images.githubusercontent.com/17010094/36495090-285fea6e-175a-11e8-9420-bb1dc2bdf3e9.gif)

**Expected result:**
Should detect and add file extension automatically 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.10
-- | --
V8 | 6.4.388.41
rev | fd80122
Muon | 5.0.2
OS Release | 10.0.16299
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
N/A

### Additional Information
Found while testing #11906

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Works on 0.22.x branch
![image](https://user-images.githubusercontent.com/17010094/37701196-079fb966-2ce6-11e8-9854-328d3aa17a37.png)

**Comment by kjozwiak** [comment]
Verified that the above issue has been fixed on `macOS 10.13.3 x64` using the following build:
* 0.22.6 `e6ff4ea`
* libchromiumcontent: `65.0.3325.162`
* muon: `5.1.0`
