### ISSUE TITLE
second window is opened when launching 0.21.11 for the second time

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13238]
### Description
If you open 0.21.11 with a clean profile, you get one window, with one tab as expected. If you close Brave-Beta and open again, you now have two windows. This second window has the welcome page (about:welcome).

### Test plan / Steps to Reproduce

  1. Launch 0.21.11 with a clean profile.
  2. See one window with one tab.
  3. Close Brave-Beta.
  4. Open Brave-Beta again.

**Actual result:**
Two windows are displayed.
![twowindows-02111](https://user-images.githubusercontent.com/28145373/36506354-650bb28a-1724-11e8-857b-f51b270cdb8f.gif)

**Expected result:**
Only one window.

**Reproduces how often:**
Easily on MacOS. @kjozwiak reported he has seen it on Win 10 x64 but not consistently.

### Brave Version

**about:brave info:**
0.21.11

**Reproducible on current live release:**
no

**Comment by petemill** [comment]
It's weird that the welcome tab does not show on the first load, but does on the second. I have a feeling the welcome tab is being added to the buffer window. Which is then being saved to state because it does not have 0 tabs.

**Comment by petemill** [comment]
Hopefully fixed with https://github.com/brave/browser-laptop/pull/13244

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
