### ISSUE TITLE
Save Torrent doesn't add torrent extension

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13230]
### Description
Save Torrent doesn't add torrent extension

### Steps to Reproduce

1. Go to https://webtorrent.io/torrents/big-buck-bunny.torrent
2. Click Save Torrent File...
3. The dialog doesn't show torrent as extension

**Actual result:**
![11906-torrent](https://user-images.githubusercontent.com/17010094/36495355-efa40984-175a-11e8-9d0f-79a7d92e7272.gif)

**Expected result:**
Should automatically add the extension

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.10
-- | --
V8 | 6.4.388.41
rev | fd80122
Muon | 5.0.2
OS Release | 10.0.16299
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
N/A

### Additional Information
Found while testing #11906

**Comment by srirambv** [comment]
Blocked on #13365

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Works on 0.22.x branch 
![image](https://user-images.githubusercontent.com/17010094/37701149-db4dccc2-2ce5-11e8-98e8-1d1c910dd353.png)

**Comment by kjozwiak** [comment]
Verified that the above issue has been fixed on `macOS 10.13.3 x64` using the following build:
* 0.22.6 `e6ff4ea`
* libchromiumcontent: `65.0.3325.162`
* muon: `5.1.0`
