### ISSUE TITLE
Removing URL doesn't remove the EVC details 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13256]
### Description
Removing URL doesn't remove the EVC details 

### Steps to Reproduce
  1. Clean install 0.21.11
  2. Visit Github.com, ensure the EVC is shown once URL is loaded
  3. Select URL and delete, EVC is still shown 

**Actual result:**
![evc](https://user-images.githubusercontent.com/17010094/36555398-e462ceac-1827-11e8-9592-e864746530f6.gif)

**Expected result:**
Site EVC should be removed when the URL is removed 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.11
-- | --
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
N/A

### Additional Information
cc: @MargarytaChepiga @bsclifton  @diracdeltas

**Comment by alexwykoff** [comment]
If reviewed by eob it stays in, otherwise pushed to another release.

**Comment by diracdeltas** [comment]
PR has been approved

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
