### ISSUE TITLE
Trying to save page offline always shows Downloading...

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13250]
### Description
While testing #3784 found that when trying to save a page in offline mode, the downloader dosn't cancel or warn about being offline instead keeps showing `Downloading...` message

### Steps to Reproduce
  1. Clean install 0.21.11
  2. Load any site in a new tab and go offline
  3. Save page, doesn't cancel or error keeps showing downloading
  4. Go online, still doesn't change remains downloading.

**Actual result:**
![saveoffline](https://user-images.githubusercontent.com/17010094/36520788-346e979c-17b9-11e8-8aaa-680c5d67279f.gif)

**Expected result:**
Should error/cancel the download when offline

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.11
-- | --
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Yes

### Additional Information
cc: @darkdh

**Comment by bsclifton** [comment]
@srirambv does this happen in 0.20.x (or earlier?)
