### ISSUE TITLE
Twitch: Log time when closing a video

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13259]
### Description

We want to log remaining time (not logged yet) when you switch to another video or when video ends.

**Comment by arsalankhalid** [comment]
I really like this task, would love to take a stab after we sync up in a discussion, and close out that other minor rewards typography issue. 

Arsalan

**Comment by NejcZdovc** [comment]
@arsalankhalid Sure we can talk about this one

**Comment by NejcZdovc** [comment]
Problem with this issue is that twitch is not handling video end correctly. We added support for video end event in #13326 so we should be good when twitch fixes it.

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
