### ISSUE TITLE
unable to export bookmarks

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13255]
### Description
Bookmarks don't export. See test case D from https://github.com/brave/browser-laptop/pull/11906

### Steps to Reproduce

  1. Set up some bookmarks on a clean profile (I had 2 on my toolbar and 2 in a folder on the toolbar)
  2. Menu->Bookmarks->Export bookmarks
  3. The default path should be your download path
  4. The dialog should have extension option with html
  5. Default extension is html
  6. Click Save on the dialog.

**Actual result:**
Bookmark export file is not created.

**Expected result:**
Bookmark export file should be created.

**Reproduces how often:**
Easily. Confirmed by @btlechowski on Linux and @srirambv on Windows.

### Brave Version

**about:brave info:**
Brave | 0.21.11
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
no

### Additional Information
cc @darkdh

**Comment by srirambv** [comment]
Default path in save file window isn't download path.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
