### ISSUE TITLE
page load end scripts not executing anymore

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1325]
on a site like http://www.wired.com/2016/04/layer3-tv/, it appears that the pageLoadEndScript is no longer being executed.

**Comment by diracdeltas** [comment]
`this.webview.executeJavaScript` is silently failing; cc @bridiver @bbondy

**Comment by bridiver** [comment]
https://github.com/brave/electron/commit/5c27a0fd51ee8db2df240a52c857aa68d731a8ea
