### ISSUE TITLE
Saved performance profile in Developer Tools is empty

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13254]
### Steps to Reproduce

  1. Open Developer Tools (F12) and Open Performance tab
  2. Click Record button and record for few seconds
  3. Save the profile

**Actual result:**

Profile file is created but has 0 size

**Expected result:**
Profile file is saved

**Reproduces how often:**

100%

### Brave Version
 
```
Brave: 0.21.11 
V8: 6.4.388.41 
rev: e146cd88d6cc5c91f8e772a18cd6c604fe903f58 
Muon: 5.0.5 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```
```
Brave: 0.21.11 
V8: 6.4.388.41 
rev: e146cd88d6cc5c91f8e772a18cd6c604fe903f58 
Muon: 5.0.5 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```
### Additional Information
TC taken from #11906 

Not reproducible in 0.20.42

**Comment by LaurenWags** [comment]
Reproduced on MacOS

Brave | 0.21.11
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
