### ISSUE TITLE
Appear.in does not load

### ISSUE THREAD

**Issue by datenreisender** [brave/browser-laptop#13251]
### Description
No connection on appear.in-calls.

https://appear.in/ is a site for video calls which (among other browsers) also supports chrome. But using Brave it is not possible to connect to a call there, there is just an endless spinner.

### Steps to Reproduce

  1. Visit any appear.in-room (e.g. https://appear.in/brave-test) in Brave (no matter whether shields up or down).

**Actual result:**
![image](https://user-images.githubusercontent.com/260705/36530237-d6ce0b5c-17ba-11e8-9f95-b7a77fbb7cda.png)

**Expected result:**
Either a page that tells me, that my mic and camera are not active and request me to activate it:
![image](https://user-images.githubusercontent.com/260705/36530305-04d6acde-17bb-11e8-99f2-b99c277c1b01.png)

Or the video call itself (there is no registration needed): 
![image](https://user-images.githubusercontent.com/260705/36530325-12077c58-17bb-11e8-9510-bb53b00a83a8.png)
 
**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by btlechowski** [comment]
Thank you for the report.
I have checked Brave v0.20.42 on Win7 x64 and it worked.

Not reproducible v0.20.42, Win7 x64

@LaurenWags Can you check on Mac?

**Comment by datenreisender** [comment]
Before I did not get the banner but I just retried it with the recent Brace 0.21.18 (rev 580be78). Now I got the banner and after answering „Allow“, appear.in did load correctly. Thus, I close this issue.

**Comment by LaurenWags** [comment]
thanks for reporting back @datenreisender - we appreciate the confirmation. Let us know if it happens again.
