### ISSUE TITLE
Make browser level dev tools less discoverable - cmd-r wipes tabs with devtools open

### ISSUE THREAD

**Issue by dignifiedquire** [brave/browser-laptop#1326]
I found this issue today

1. Open multiple tabs
2. Open developer tools
3. Hit `CMD-R`
4. All tabs are wiped and reset as if I would open a new window

---

Browser details

```
Brave: 0.9.0
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 5.10.0
Update channel: dev
```

**Comment by bbondy** [comment]
Do you maybe have the browser level dev tools instead of the content level dev tools open?

CommandOrControl+Alt+I to get the content ones.

**Comment by bbondy** [comment]
Control+Shift+I on Windows actually I think.

**Comment by dignifiedquire** [comment]
I use `Cmd+Shift+J` to open them the same way I do in Chrome. Looks like they open the browser level dev tools, instead of the content ones as you suggested. Maybe you could display a warning or something when openening these, as on first view the console looks pretty identical.

**Comment by bbondy** [comment]
Ya making these less discoverable for accidental opening seems like a good idea. Thanks for the report.

**Comment by bbondy** [comment]
Toggle Browser Console from the View menu should be removed.
Do you think we should change the shortcut too?

**Comment by dignifiedquire** [comment]
I think it would be really good to change the shortcut, coming from Chrome and spending a lot of my time in the devtools it's pretty counterintuitive to get the devtools for Brave itself on that shortcut.

**Comment by Alexander-Attar** [comment]
I second this idea!
