### ISSUE TITLE
Being able to "zoom in" with fingers on touch screen laptops. 

### ISSUE THREAD

**Issue by pcatana** [brave/browser-laptop#13260]
### Description
On touch screen laptops one cannot pinch and zoom on any page like in Chrome Browser
It's a feature I really like on Chrome. I use it a lot personally and would love to have it on Brave too. 
Latest version of Brave.

**Comment by bsclifton** [comment]
This should have been fixed on macOS with https://github.com/brave/browser-laptop/issues/1364

We should test this on Windows/Linux
