### ISSUE TITLE
pinned tabs do not retain order when moved with keyboard shortcut

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13264]
### Description
If you reorder your pinned tabs using the keyboard shortcut (ctrl+shift+pg up/down), and then close/reopen Brave, your pinned tabs order is not maintained. 

### Test plan / Steps to Reproduce

  1. Clean profile with 0.21.11.
  2. Open several tabs with several sites.
  3. Pin some of the tabs. Note pinned order.
  4. Move pinned tabs around using keyboard shortcut described in #11313
  5. Note new order.
  6. Close/Reopen Brave.

**Actual result:**
Reordered pinned tabs are back to their original placement.

**Expected result:**
Pinned tabs should retain the order you set using the keyboard shortcut.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.11
V8 | 6.4.388.41
rev | e146cd8
Muon | 5.0.5
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
n/a

### Additional Information
If you drag and drop pinned tabs into a new order this is kept.

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
