### ISSUE TITLE
Docusign not remembering passwords

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1327]
Form detection needs to be tweaked.
https://eu1.docusign.net/Member/MemberLogin.aspx?event=logout

**Comment by bbondy** [comment]
I noticed the selector for this has `:not(autocomplete=off) but the password on that site has `autocomplete=off`.  Why do we exclude `autocomplete=off`?
input[type=password]:not([autocomplete=off i])

**Comment by diracdeltas** [comment]
@bbondy historically, sites were supposed to use `autocomplete=off` to indicate that a field shouldn't be autofilled by the browser for whatever reasons. Chrome started ignoring it relatively recently, which caused a lot of controversy (https://groups.google.com/a/chromium.org/forum/#!searchin/security-dev/autocomplete/security-dev/wYGThW5WRrE/qiWrKwJ79S4J). However, I just noticed that FF and IE also ignore it, so it's not unreasonable for us to do so as well.

**Comment by bbondy** [comment]
I'm in favour of removing, If people complain we could add as a preference.

**Comment by diracdeltas** [comment]
Ok will do
