### ISSUE TITLE
Download torrent prompts to save and tries loading the torrent page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13275]
### Description
While verifying #13269 found having the torrent viewer disabled and clicking on a torrent causes the torrent file to download as well as open the torrent file.

### Steps to Reproduce
  1. Disable torrent viewer on 0.21.12
  2. Open https://webtorrent.io/free-torrents and click on a torrent link
  3. Prompts to save the torrent file but also opens the torrent page

**Actual result:**
![torrentdownload](https://user-images.githubusercontent.com/17010094/36590580-1ed97d0a-18b5-11e8-8fba-7cb03c5b078b.gif)

**Expected result:**
Should only prompt to download and not load the torrent page

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.12
-- | --
V8 | 6.4.388.41
rev | 246f900
Muon | 5.0.5
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
N/A

**Comment by stevebro1** [comment]
This is still an issue. Also when the torrent is at 100% and seeding, when you save the video file to a USB drive for example, only part of it is saved.  I am unable to watch the full video in the browser either.

Brave	0.21.24
V8	6.5.254.36
rev	19c78a1
Muon	4.9.3
OS Release	6.3.9600
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	65.0.3325.162

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14134 and https://github.com/brave/browser-laptop/pull/14218
