### ISSUE TITLE
Publisher icon doesn't show enabled for some sites but enabled in ledger table

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13276]
### Description
Publisher icon doesn't show enabled for some sites but enabled in ledger table

### Steps to Reproduce
  1. Clean install 0.21.12
  2. Enable payments
  3. Visit few sites and stay on the page for min time so that it shows up on ledger table
  4. Switch tabs so that publisher icon shows enabled in URL
  5. Some site doesn't show included publisher icon in URL but shows included in ledger table

**Actual result:**
![pubs](https://user-images.githubusercontent.com/17010094/36594137-f4f950ba-18c2-11e8-9a34-1341e3b1be39.gif)

**Expected result:**
If the publisher is included in ledger table then publisher icon should be enabled in URL bar

**Reproduces how often:**
Found it happen twice but not consistent

### Brave Version

**about:brave info:**

Brave | 0.21.12
-- | --
V8 | 6.4.388.41
rev | 246f900
Muon | 5.0.5
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Not seen on release build

### Additional Information
cc: @NejcZdovc @bsclifton

**Comment by NejcZdovc** [comment]
I will put this into triage backlog for now. This functionality will be removed in 0.22/0.23 so I think that we can skip it until now

**Comment by NejcZdovc** [comment]
closing as we will be removing this icon
