### ISSUE TITLE
Tab session not restored after restart

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13278]
### Test plan / Steps to Reproduce

  1. Clean Install
  2. Open Brave on Windows or Linux
  3. Open youtube.com
  4. Close Brave through titlebar's close button (x)
  5. Open Brave

**Actual result:**
Tabs are NOT restored
Only New Tab is shown

**Expected result:**
Tabs are restored

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.21.12 
V8: 6.4.388.41 
rev: 246f9008be47dbdcc6dc9ded5690a847eee8a4e0 
Muon: 5.0.5 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

### Additional Information
The Brave was run through the shortcut
Very likely related to #13233, cc @petemill
Cannot reproduce when closing through CTRL+Q

**Comment by kjozwiak** [comment]
Managed to reproduce this on the following platforms:

* Win 10 x64 VM - Reproduced
* Ubuntu 17.10 x64 VM - Reproduced

@srirambv also reproduced this on his Win 10 desktop.

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
