### ISSUE TITLE
Backup keys import/export not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13274]
### Steps to Reproduce

Export
  1. Enable payments
  2. Go to advance settings
  3. Try to export backup keys

Import
  1. Enable payments
  2. Go to advance settings
  3. Try to import backup keys

**Actual result:**

Browser crashes

**Expected result:**
Keys should be saved

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
