### ISSUE TITLE
contribution notification displays again after toggle payments off/on

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13287]
### Description
If you toggle payments off/on after a contribution is made, you get the contribution notification again.

### Steps to Reproduce

1. Launch 0.21.12 using LEDGER_ENVIRONMENT=staging 
2. visit about:preferences#payments and enable payments
3. sites/YT videos
4. close brave and fund the staging wallet.
5. change reconcileStamp under ledger-state.json so Next Contribution is Overdue
6. launch 0.21.12 using LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging 
7. wait till the contribution is made and you get a notification letting you know that X amount of BAT has been processed
8. select OK on the banner notification 
9. Toggle Payments off/on 

**Actual result:**
You get the contribution notification again.

![contrib](https://user-images.githubusercontent.com/28145373/36620935-7d905900-18c3-11e8-8242-f61cf4573fe2.gif)

**Expected result:**
No contribution notification.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.21.12

**Reproducible on current live release:**
Yes

### Additional Information
Unsure if this should have been resolved by https://github.com/brave/browser-laptop/issues/12817 - that scenario has you turning notifications off, but here you are leaving them on.
cc @NejcZdovc

**Comment by srirambv** [comment]
Verified on e6ff4ea muon 5.1.0
