### ISSUE TITLE
Ledger table entries logged based on view and not on time spent

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13280]
### Description
Ledger table entries logged based on view and not on time spent

### Steps to Reproduce
  1. Clean install 0.21.12 and enable payments 
  2. View few twitch channels ensure they show up in ledger table
  3. Doesn't sort based on time spent but instead lists based on view order

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/36602742-cfaf2174-18de-11e8-9195-875af08e94e8.png)

**Expected result:**
Should be sorted based on time spent 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.12
-- | --
V8 | 6.4.388.41
rev | 246f900
Muon | 5.0.5
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
N/A

### Additional Information
Reproduced on mac by @LaurenWags

**Comment by srirambv** [comment]
This is not limited to publisher entry. Happens with other ledger entries as well
![image](https://user-images.githubusercontent.com/17010094/36604946-38059342-18e5-11e8-8ccc-01950cee4877.png)

**Comment by arsalankhalid** [comment]
Happy to take a stab :) Already trying to re-create, and am I correct in my thinking that I can't see this view from master?

**Comment by NejcZdovc** [comment]
Closing as this will be fixed with #13721 where default sort will be %
