### ISSUE TITLE
Deleted sites dialog isn't fixed size

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13284]
### Test plan
See https://github.com/brave/browser-laptop/pull/13294

### Description
Per https://github.com/brave/browser-laptop/issues/12833 I was expecting the Deleted Sites dialog to be a fixed size and contain a scroll bar inside it for when there is a large number of sites. It looks as though the dialog box just expands as the number of sites listed increases.

### Steps to Reproduce

  1. Build 0.21.x from source and launch. (clear node modules and brave-development)
  2. Enable payments.
  3. Close 0.21.x.
  4. Use `npm run add-simulated-synopsis-visits 500` to add a bunch of sites to your ledger table.
  5. Rename brave-development profile to brave-beta
  6. Launch Brave-Beta (0.21.12)
  7. Delete a many sites from your ledger table.
  8. Open Deleted Sites dialog.

**Actual result:**
![deleted-sites-dialog-no-scroll](https://user-images.githubusercontent.com/28145373/36610752-55d07766-189f-11e8-9148-674fb4a84b0c.gif)

**Expected result:**
Deleted sites dialog should look as it does in https://github.com/brave/browser-laptop/issues/12833

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
0.21.12

**Comment by bradleyrichter** [comment]
@NejcZdovc This is an important fix for this one.

**Comment by LaurenWags** [comment]
MacOS:
<img width="1193" alt="screen shot 2018-02-26 at 7 05 09 pm" src="https://user-images.githubusercontent.com/28145373/36703102-183f53aa-1b28-11e8-9193-2467227b3203.png">
