### ISSUE TITLE
some sites are 'included' after being re-added but should not be

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13283]
### Description
Even with 'auto-include' ON, some sites are set to 'Include' OFF by default (youtube.com, github.com, etc). So when you visit these sites they are displayed in your ledger table but do not have their 'include' toggle on. If you delete these sites and re-add them, they are getting added back with 'Include' ON and it does not change to OFF. 

Since we now are going to make it easier to re-add sites (the 'Clear All' option is more accessible), it seems to me like users may accidentally re-add these sites.

### Steps to Reproduce

  1. With payments enabled, visit sites like youtube.com, github.com, pinterest.com, instagram.com, etc for enough time.
  2. See sites in ledger table with Include toggle Off.
  3. Delete these sites.
  4. Open deleted sites link, sites are displayed in the dialog box.
  5. Clear one or more (or all) sites.
  6. Visit sites again.

**Actual result:**
Sites added back with Include as ON:

![screen shot 2018-02-23 at 12 36 54 pm](https://user-images.githubusercontent.com/28145373/36607963-3fc47b92-1896-11e8-966c-9fa8c9af254f.png)

**Expected result:**
Sites added back with include OFF (they way they were prior to deleting):

![screen shot 2018-02-23 at 12 30 03 pm](https://user-images.githubusercontent.com/28145373/36607689-5b3295c2-1895-11e8-8a06-87699fcaf895.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.21.12

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
This is expected, since you deleted them and we lose track of which ones are disabled on which ones are not

**Comment by NejcZdovc** [comment]
I think this was fixed with https://github.com/brave/browser-laptop/pull/13285

**Comment by LaurenWags** [comment]
@NejcZdovc one of the sites got added back as excluded automatically, but the others were added back as included:
![screen shot 2018-02-27 at 9 57 44 am](https://user-images.githubusercontent.com/28145373/36735689-ba563452-1ba4-11e8-9a9b-330d2f842faa.png)

**Comment by NejcZdovc** [comment]
@LaurenWags do you see any errors in the console? I see that images are working now, which is something 😃

**Comment by LaurenWags** [comment]
yes!  👍 👍 on the icons!
