### ISSUE TITLE
update app icons for all desktop build types

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#13290]
Here are new icons that have been adjusted for the following attributes:

- larger size to appear balanced next to other icons on windows and Mac docks
- color adjustment to bring back more orange
- color adjustment for blue themed icons
- increased shading effect based on internal feedback
- installer drive icons use latest version from Mac OS

@bsclifton - ball passed to you!

[brave_desktop_appicons_0-21-0.zip](https://github.com/brave/browser-laptop/files/1753683/brave_desktop_appicons_0-21-0.zip)

**Comment by bsclifton** [comment]
Marked as `QA/no-qa-needed` since I peer approved this with Brad
