### ISSUE TITLE
Unmet dependencies when installing on kubuntu

### ISSUE THREAD

**Issue by mer23** [brave/browser-laptop#13309]
`$ sudo apt-get install brave
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  desktop-file-utils gawk gvfs gvfs-bin gvfs-common gvfs-daemons gvfs-libs
Suggested packages:
  gir1.2-gnomekeyring-1.0 gawk-doc gvfs-backends
The following NEW packages will be installed:
  brave desktop-file-utils gawk gvfs gvfs-bin gvfs-common gvfs-daemons gvfs-libs
0 upgraded, 8 newly installed, 0 to remove and 1 not upgraded.
Need to get 863 kB/90.5 MB of archives.
After this operation, 506 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://il.archive.ubuntu.com/ubuntu yakkety/main amd64 gawk amd64 1:4.1.3+dfsg-0.1build1
  404  Not Found
Err:2 http://il.archive.ubuntu.com/ubuntu yakkety-updates/main amd64 desktop-file-utils amd64 0.23-1ubuntu1.1
  404  Not Found
Ign:3 http://il.archive.ubuntu.com/ubuntu yakkety/main amd64 gvfs-common all 1.28.2-1ubuntu2
Err:4 http://il.archive.ubuntu.com/ubuntu yakkety/main amd64 gvfs-bin amd64 1.28.2-1ubuntu2
  404  Not Found
Err:5 http://il.archive.ubuntu.com/ubuntu yakkety/main amd64 gvfs-libs amd64 1.28.2-1ubuntu2
  404  Not Found
Err:6 http://il.archive.ubuntu.com/ubuntu yakkety/main amd64 gvfs-daemons amd64 1.28.2-1ubuntu2
  404  Not Found
Err:7 http://il.archive.ubuntu.com/ubuntu yakkety/main amd64 gvfs amd64 1.28.2-1ubuntu2
  404  Not Found
Err:3 http://il.archive.ubuntu.com/ubuntu yakkety/main i386 gvfs-common all 1.28.2-1ubuntu2
  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/g/gawk/gawk_4.1.3+dfsg-0.1build1_amd64.deb  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/d/desktop-file-utils/desktop-file-utils_0.23-1ubuntu1.1_amd64.deb  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/g/gvfs/gvfs-common_1.28.2-1ubuntu2_all.deb  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/g/gvfs/gvfs-bin_1.28.2-1ubuntu2_amd64.deb  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/g/gvfs/gvfs-libs_1.28.2-1ubuntu2_amd64.deb  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/g/gvfs/gvfs-daemons_1.28.2-1ubuntu2_amd64.deb  404  Not Found
E: Failed to fetch http://il.archive.ubuntu.com/ubuntu/pool/main/g/gvfs/gvfs_1.28.2-1ubuntu2_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

This is happening when using apt-get and also with wget + dpkg (same unmet dependencies).

When doing `sudo apt-get update` I get the following output:

`E: The repository 'http://il.archive.ubuntu.com/ubuntu yakkety Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://il.archive.ubuntu.com/ubuntu yakkety-updates Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://il.archive.ubuntu.com/ubuntu yakkety-backports Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://security.ubuntu.com/ubuntu yakkety-security Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.hhvm.com/ubuntu yakkety InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B4112585D386EB94
`

Thank you.

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
