### ISSUE TITLE
Font looks blurry on Linux

### ISSUE THREAD

**Issue by thynquest** [brave/browser-laptop#13300]
Have you searched for similar issues? 
Yes

### Description
the font looks on brave whatever the web page

### Steps to Reproduce
Just open any web page

**Actual result:**
Here is a capture with brave
![capturebrave](https://user-images.githubusercontent.com/3199630/36639631-3b1e5d8e-1a11-11e8-9043-b5cb20f1c5d5.png)

**Expected result:**
The same result with firefox
![captureff](https://user-images.githubusercontent.com/3199630/36639632-3f3c8d50-1a11-11e8-81aa-f7564abb35e4.png)

**Reproduces how often:**
Every time

### Brave Version

**about:brave info:**
 Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.4.0-109-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

Thank you for your help

**Comment by sandangel** [comment]
This is because of the libfreefont6 >=2.8.1 bug in linux. Downgrade to 2.8.0 will fix this

**Comment by Jacalz** [comment]
Is this only on HIDPI displays?

**Comment by thynquest** [comment]
Hello 
Actually I've found out the problem. I just had to remove the anti aliasing on my graphic card and all went back to normal. 
But thank you guys for your help
