### ISSUE TITLE
Youtube starts playing on startup

### ISSUE THREAD

**Issue by atotic** [brave/browser-laptop#1330]
When "show my windows from last time" is active, and you restart to update Brave, Youtube video starts playing in a hidden tab. It does not do this in Chrome.

To reproduce, close everything, navigate to these two tabs, restart:
http://news.ycombinator.com/
https://www.youtube.com/watch?list=PLOU2XLYxmsIIuiBfYad6rFYQU_jL2ryal&v=cKxRvEZd3Mw

The video will start playing.

It shouldn't play.

**Comment by luixxiul** [comment]
@bbondy Any idea?

**Comment by bbondy** [comment]
We just need a way to pause tabs that aren't active and on startup until first click.

**Comment by luixxiul** [comment]
Closing this in favor of #1533
