### ISSUE TITLE
Typos in dashboard background image names

### ISSUE THREAD

**Issue by dwperrin** [brave/browser-laptop#13301]
### Description
There are a couple of typos in the dashboard background image names. They are:

Paris:Conciergeri -> should be Paris:Conciergerie
Paris:The Seant  -> should be Paris:The Senate

### Brave Version

**about:brave info:**
 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 10.0.17083 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:** yes

**Comment by kjozwiak** [comment]
Thanks for the contribution @dwperrin. @bsclifton, can we stick this into the 0.21.x milestone? It's a really low risk change. Would be nice to get this community contribution into the browser. 👍

**Comment by LaurenWags** [comment]
MacOS:
![screen shot 2018-02-27 at 10 07 05 am](https://user-images.githubusercontent.com/28145373/36736257-2aa940ae-1ba6-11e8-970e-5fd76c0fe8ac.png)
![screen shot 2018-02-27 at 10 07 53 am](https://user-images.githubusercontent.com/28145373/36736267-2d391790-1ba6-11e8-8598-8fed76c08f6d.png)
