### ISSUE TITLE
Recovery Code isn't localized for other languages

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13311]
### Description
Recovery Code isn't localized for other languages

### Steps to Reproduce
  1. Clean install 0.20.46 build, Set browser language to English (U.K)
  2. Enable wallet
  3. Print recovery keys, shows `Recovery Code 2`

**Actual result:**
![recovery keys](https://user-images.githubusercontent.com/17010094/36680135-f676db04-1b3a-11e8-99ff-5ce808dfaf58.gif)

**Expected result:**
Should not show `Recovery Code 2` either in print keys or on saved keys

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.46
-- | --
V8 | 6.4.388.41
rev | 5eb035c
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
Yes

**Comment by kjozwiak** [comment]
Went through the following languages using `0.21.17` 57e6145f13e79a53c3823df518f0d7852c607ff5 under Ubuntu 17.10 x64 and ensured that `Recovery Code 2` wasn't be displayed when backing up the recovery codes via both `Print` and `Save` methods:

* English (U.K) - PASSED
* French - PASSED
* Slovenian - PASSED
* Russia - PASSED
* Japanese - PASSED
* Italian - PASSED
