### ISSUE TITLE
MetaMask not prompting popup to confirm transactions.

### ISSUE THREAD

**Issue by tmashuang** [brave/browser-laptop#13315]
This issue was initially created by the MetaMask designer here https://github.com/MetaMask/metamask-extension/issues/3219. I was hoping to get clarification on this issue and insight on enabling the confirmation popup.

**Comment by srirambv** [comment]
cc: @jonathansampson

**Comment by cppfuns** [comment]
I've been waiting for the problem to be solved, and can I raise the priority?

**Comment by jonathansampson** [comment]
@cppfuns Does this issue still exist?

**Comment by cppfuns** [comment]
Yes, there is still a problem with trying to download the latest version of Brave browser.

**Comment by cppfuns** [comment]
Brave: 0.22.667 
V8: 6.6.346.24 
rev: 0433b26a03c8daf9b181057cd2ffa7b530496faf 
Muon: 5.2.6 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/JeanMaloLeDreff/status/1013706910191837184

**Comment by jonathansampson** [comment]
@cppfuns I believe this is solved in our new brave-core builds. We've replaced the builds on brave.com, and will be upgrading users of the previous Brave Muon builds in the very near future.
