### ISSUE TITLE
Bookmark search does not work, cannot type in letters in the search field.

### ISSUE THREAD

**Issue by mhouse777** [brave/browser-laptop#13322]
### Description
You cant type in the bookmark search field.

### Steps to Reproduce

  1. just try and type in the search field, you can't
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**
%100

### Brave Version

0.20.46
--

**about:brave info:**

**Reproducible on current live release:**

**Comment by Tomatoshadow2** [comment]
Also post what OS you are using.

**Comment by srirambv** [comment]
You need to have these two enabled for bookmark suggestions to show up. 
![image](https://user-images.githubusercontent.com/17010094/36711321-c6270712-1ba8-11e8-9f28-a8cc5c147b85.png)

Also please provide more info so that we can figure out what issue you are facing. Its not very clear from the issue

**Comment by mhouse777** [comment]
windows 10 , 64 bit.  go to bookmarks tab  in brave browser. select bookmarks. You are now in book mark manager, On the right you will see a field that says, "search Bookmarks". Try to type a search term in it., You can't , it doesn't work.

**Comment by jasonrsadler** [comment]
Reproduced under 0.23 after importing a large bookmark test file.

Win10 x64, working on STR

**Comment by jasonrsadler** [comment]
STR:

Create a bookmark (it can be fake). Put a single quote in the url (example: [http://www.example.org/quote'test].

export the bookmarks to a file. 

reimport the file.

Search tries to work but clears immediately. console displays sql lock errors. state becomes empty with title = undefined and .match is not a function

suspecting importing HTML bookmark files not escaping single quotes properly.

**Comment by diracdeltas** [comment]
> could this potentially be a sqlite injection vulnerability?

brave uses JSON, not sqlite, for its internal bookmarks store. but it's possible that you would see errors like this if you created the bookmarks profile in a browser that does use sqlite for its store and then imported into Brave.

either way, the risk is low if the user has to manually edit the bookmark URL for it to work.

**Comment by jasonrsadler** [comment]
Thanks for the clarification. The only reason I was asking was after importing a 'bad' bookmarks input and trying to run a bookmark search, the console spammed a bunch of sqlite lock errors at me. May be something else indirectly related but knowing that bookmarks is JSON based I would thing eliminates that as a possible vector.

**Comment by diracdeltas** [comment]
i've seen some sqlite lock errors when trying to run two instances of Brave at once from the same profile

**Comment by jasonrsadler** [comment]
That didn't seem to be the case on this, but I did notice I had to kill the residuals after closing the browser. Where are the bookmarks JSON kept?

Thanks.

**Comment by jasonrsadler** [comment]
This will not fix those already affected by the issue. To resolve for end users, recommend deleteing session-store-1 file from appdata

**Comment by LaurenWags** [comment]
multiple +1s from community: https://community.brave.com/t/bookmark-search-field-does-not-work/16154

**Comment by bsclifton** [comment]
@jasonrsadler deleting the `session-store-1` file is pretty extreme and IMO shouldn't be done unless there is no other choice (and even then, we'd want to back up the file).  Please keep in mind, users may be reading this issue and may have a lot of data associated in their session store (ledger, bookmarks, history, etc)

Would the user be able to work-around this issue by exporting / importing their bookmarks?

**Comment by jasonrsadler** [comment]
@bsclifton I agree deleting sessionStore is a last resort. I don't think exporting and reimporting the bookmarks fixes it as the bug is introduced upon first import. In fact, if you manually create a bookmark with a single-quote in it, export the bookmarks and reimport them, the bug is introduced.

But yes. Definitely a backup of the file should be made if the user goes that route. Otherwise, they would need to open the sessionStore, prettify it, and remove the corrupt entry by hand.

**Comment by jasonrsadler** [comment]
Resolved in 122aa709cb0c3c5fb3caaae7ad8d54d03843eb5e

**Comment by bsclifton** [comment]
@jasonrsadler I updated the original post with your test steps and assigned this to the 0.22.x release 3 milestone.  Also tagged with release notes include/test plan specified

Do you mind looking over the steps to see if they look correct? Thanks 😄 👍

**Comment by jasonrsadler** [comment]
@bsclifton Yes. Those steps are correct. Obviously to STR now, you'll need a commit before 122aa70. Thank you sir!
