### ISSUE TITLE
RPM Keys import failed on OpenSUSE

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13323]
### Description
RPM Keys import failed on OpenSUSE

### Steps to Reproduce

  1. Run `sudo rpmkeys --import https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc`
  2. Console throws error saying ` Could not resolve host: s3-us-west-2.amazonaws.com`
  3.

**Actual result:**
```
osboxes:/home/osboxes # sudo rpmkeys --import https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc
curl: (6) Could not resolve host: s3-us-west-2.amazonaws.com
error: https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc: import read failed(2).
```

**Expected result:**
Should import keys

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**
Yes

### Additional Information
Reported on community https://community.brave.com/t/rpm-repository-permissions-problem/16746/

**Comment by pakman** [comment]
The real problem seems to be with access permissions, see my [original post ](https://community.brave.com/t/rpm-repository-permissions-problem/16746)on the QA forum.

The error "Could not resolve host" is misleading, the host resolves fine:

```
dig s3-us-west-2.amazonaws.com

; <<>> DiG 9.9.9-P1 <<>> s3-us-west-2.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44011
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;s3-us-west-2.amazonaws.com.	IN	A

;; ANSWER SECTION:
s3-us-west-2.amazonaws.com. 3	IN	A	54.231.184.168

;; AUTHORITY SECTION:
amazonaws.com.		120120	IN	NS	u1.amazonaws.com.
amazonaws.com.		120120	IN	NS	u2.amazonaws.com.
amazonaws.com.		120120	IN	NS	r2.amazonaws.com.
amazonaws.com.		120120	IN	NS	r1.amazonaws.com.

;; ADDITIONAL SECTION:
u1.amazonaws.com.	457	IN	A	156.154.64.10
r2.amazonaws.com.	147827	IN	A	205.251.195.199
u2.amazonaws.com.	162798	IN	A	156.154.65.10
r1.amazonaws.com.	1324	IN	A	205.251.192.27

;; Query time: 30 msec
;; SERVER: 192.168.131.10#53(192.168.131.10)
;; WHEN: Tue Feb 27 09:10:16 GMT 2018
;; MSG SIZE  rcvd: 203
```

Downloading keys.asc is also possible, since this works.

`wget https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc`

Browsing to the repo URL https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media with a browser gives this:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>C58DC20C1E838DCA</RequestId>
<HostId>
tiattjtWOW4iFtOEj9RJYhwT0g27aAeimk0CGfFkg3+JwLGKkevPHFcMlBhz6TCWiB3tDISibmQ=
</HostId>
</Error>
```

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
