### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by CarolSmall** [brave/browser-laptop#1332]
![screen shot 2016-04-11 at 08 27 12](https://cloud.githubusercontent.com/assets/18392134/14419764/e5645118-ffbf-11e5-890e-bd5e018b27a6.png)

Uncaught javascript exception occurred when trying to launch Brave. Killing the process and relaunching allowed startup ok.

**Comment by bbondy** [comment]
This is being fixed here and will be included in 0.9.2:
https://github.com/brave/browser-laptop/issues/1298

It happens if you click the app icon a lot of times when opening, thne you have to quit as you mentioned for it to work again. Thanks for the report.
