### ISSUE TITLE
Browser freezes when a wrong URL is entered

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13339]
### Description
Browser freezes when a wrong URL is entered

### Steps to Reproduce
  1. Clean install 0.21.17
  2. Launch browser with `LEDGER_ENVIRONMENT=staging` (not sure if this makes any difference but issue found when launched with this env variable
  3. Enable payments and add some funds
  4. Open a new tab and type a wrong URL ( i had typed http://epcohconverter.com)
  5. Console shows error 
  6. Try entering correct URL, doesn't work
  7. Try opening a new tab, doesn't load a new tab
  8. Unable to close browser have to kill the app

**Actual result:**
Browser freezes when a wrong URL is entered
Console throws the following error
```
[7904:6136:0228/150903.448:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'filterNot' of undefined", source: chrome://brave/C:/Users/SriramBV/AppData/Local/BraveBeta/app-0.21.17/resources/app.asar/app/extensions/brave/gen/app.entry.js (1)
```

**Expected result:**
Should not freeze when a wrong URL is typed in

**Reproduces how often:**
Reproduced twice but not sure if its consistent 

### Brave Version

**about:brave info:**

Brave | 0.21.17
-- | --
V8 | 6.4.388.41
rev | 57e6145
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
No

### Additional Information
Not sure if Steps 2/3 is required. I was able to reproduce it both the times when I followed steps 2 & 3. 
cc: @bsclifton @NejcZdovc @petemill

**Comment by NejcZdovc** [comment]
@srirambv I think that this issue has the same error as this one, so probably fix from @petemill will fix both of them https://github.com/brave/browser-laptop/issues/13261

**Comment by petemill** [comment]
@srirambv were you able to use the browser after restart?

**Comment by srirambv** [comment]
@petemill  Yes browser works fine after restart

**Comment by petemill** [comment]
Closing in favor of #13261
