### ISSUE TITLE
Brave Beta asks me to add helper tool on Mac, doesn't update

### ISSUE THREAD

**Issue by Tomatoshadow2** [brave/browser-laptop#13341]
Description

Was going to update Brave Beta today, update was found clicked update. Mac says Brave would like to add a helper tool, put in my password, update doesn't occur. Just updated Release channel, didn't ask for the helper tool.

 Steps to Reproduce

  1. Check for update on Mac OS
  2. Click update, Brave Beta asks to install a helper tool
  3. Doesn't restart and apply update

Actual result: Doesn't update.

Please add screenshots if needed.

**Reproduces how often:**
100%
What percentage of the time does it reproduce?
100% as far as I've tried

Brave Version

 
Brave: 0.21.12 
V8: 6.4.388.41 
rev: 246f9008be47dbdcc6dc9ded5690a847eee8a4e0 
Muon: 5.0.5 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
 
Beta doesn't allow me to update to most recent build.

**Reproducible on current live release: No, Release channel updates properly. 

Additional Information - Might be considered a regression as I've never had this issue before.

**Comment by Jacalz** [comment]
This should be resolved now, they changed to .pkg file and they that introduced the help service stuff, that was however fixed at a later point :+1:

**Comment by bsclifton** [comment]
@Tomatoshadow2 can you please try installing Beta manually? You should then be able to upgrade next time a release comes out 😄 I ran into the same thing- I may have accidentally released a bad build.  Should be fixed now though 👍

**Comment by Tomatoshadow2** [comment]
Thanks guys, appreciate it will do!
