### ISSUE TITLE
Brave leaks my IP

### ISSUE THREAD

**Issue by nagybarnabas** [brave/browser-laptop#13348]
Latest install
Fingerprinting Protection ON

Verified that my IP leaks even though VPN is on. Tested with same services on Firefox and it does not leak.

Verified with:
https://www.privacytools.io/webrtc.html
https://torguard.net/vpn-webrtc-leak-test.php
https://www.perfect-privacy.com/webrtc-leaktest/
https://whoer.net/

**Comment by NejcZdovc** [comment]
cc @diracdeltas

**Comment by srirambv** [comment]
Some similar issues which have been closed before
#12389 #11206 https://github.com/brave/browser-laptop/issues/10592#issuecomment-324778000

**Comment by nagybarnabas** [comment]
Before opening the thread I checked some of those threads and they didn't help me. Fingerprinting Protection is ON.

**Comment by diracdeltas** [comment]
works fine for me on 

 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

did you set fingerprinting protection to 'block all fingerprinting'? (default is block 3rd party)
![screen shot 2018-03-01 at 11 20 57 am](https://user-images.githubusercontent.com/549654/36864857-b447a074-1d42-11e8-9149-5185d9496575.png)

**Comment by nagybarnabas** [comment]
My fingerprinting is set to 3rd parties. Does it have to be set to all?

**Comment by diracdeltas** [comment]
@nagybarnabas 3rd party only blocks 3rd party fingerprinting. the sites you linked do 1st party fingerprinting, so yes it has to be set to 'block all'
