### ISSUE TITLE
U2F is not working on Mac

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#13344]
### Test plan
See https://github.com/brave/browser-laptop/pull/13345

### Description
While U2F support is working on linux and windows, there is a platform specific bug preventing it from working on mac.

### Steps to Reproduce
1. Go to https://demo.yubico.com/u2f?tab=register
2. Make up a username and password and click next

**Actual result:**
3. You will not be prompted to plug in your u2f key and cannot complete registration

**Expected result:**
3. You should be prompted to plug in your u2f key
4. You will be prompted to touch the sensor on your u2f key
5. On success you can attempt login using the same username and password
6. You will be prompted to again plug in / touch the sensor on your u2f key

**Reproduces how often:**
Always

### Brave Version
Beta release

**Reproducible on current live release:**
Yes, beta release

**Comment by srirambv** [comment]
U2F device is detected on the site mentioned in STR but doesn't recognize on Gmail on Windows

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
