### ISSUE TITLE
Can't Print

### ISSUE THREAD

**Issue by freshcut1** [brave/browser-laptop#1335]
Using Brave, it won't allow me to print from the web page Print button, or the Brave Print button. Press Print and nothing happens

**Comment by cesarmarinhorj** [comment]
works for me in ubuntu 14.04 LTS
what is your OS?

**Comment by freshcut1** [comment]
Win10

 

Bob Swartwout

 <mailto:freshcut1@outlook.com> freshcut1@outlook.com

(214) 269-6540 Cell

**Comment by freshcut1** [comment]
Yep, won’t print from web page print button or from the Brave Print button. No error message or anything, just doesn’t print

 

Bob Swartwout

 <mailto:freshcut1@outlook.com> freshcut1@outlook.com

(214) 269-6540 Cell

**Comment by bbondy** [comment]
Dupe of https://github.com/brave/browser-laptop/issues/1246
(also fixed in 0.9.2 which will be out very soon)
