### ISSUE TITLE
BAT balance is gone

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#13354]
### Description
I noticed that my remaining BAT balance is gone. Someone mentioned this issue in the Discord #desktop channel, so I checked for myself. Sure enough, my balance is gone.

Previously, I had the free 10 BAT that was given to use for starting with payments. I have currently made one contribution of 5 BAT on 2018-02-21. That should leave me with a balance of 5 BAT. However, my current balance shows 0 BAT instead. Where did my other 5 go? 

As I said, I'm not the only one experiencing this. 

Also, I checked my contribution statements, and there is, as expected, only one statement for the single 5 BAT contribution.

### Steps to Reproduce
I have no idea how to reproduce this. If it happened to multiple people, perhaps it happened to everyone and you can just go look at your own account balance?

**Actual result:**
I should still have my remaining balance.

**Expected result:**
I don't have my remaining balance.

**Reproduces how often:**
Again, no idea.

### Brave Version

**about:brave info:**
```
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproducible on current live release:**
Yes

**Comment by rjro** [comment]
+1 from me, something similar happened:

I had 20.3 BAT in my wallet, 10 from the UGP.

Contribution date came and passed, nothing happened. Overdue next day, nothing happened. Then a few days later, I receive my Contribution statement showing that I had given out my 20 BAT.

Yet in my account balance, I had 10.3 BAT remaining. How did I pay out 20BAT if only 10 are gone from my wallet?

Seems to be connected as well: https://www.reddit.com/r/BATProject/comments/822dd0/grant_wallet_had_10_bat_in_it_i_donated_75_now_my/

**Comment by cryptojennie** [comment]
+1 from reddit community: https://www.reddit.com/r/BATProject/comments/822dd0/grant_wallet_had_10_bat_in_it_i_donated_75_now_my/

**Comment by mlhaufe** [comment]
The reddit link mentions an expiration date? Is this true? I assume even if it was, it would not apply here. My concern would be what happens if this issue is fixed in say, 60 days, and our balances are restored to simply expire immediately.

**Comment by echosa** [comment]
FYI - My March contribution went through and did not clear out my remaining balance. Whatever happened in February didn't happen this time. Maybe that will help find the problem.

**Comment by mrose17** [comment]
Moved to https://github.com/brave-intl/bat-ledger/issues/205
