### ISSUE TITLE
Update Muon

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13357]
### Description
Update to Muon 4.9.1

### Test plan
  1. Visit `about:brave`
  2. `Muon` version should be `4.9.1`

**Comment by bsclifton** [comment]
Updated to 5.1.3 with https://github.com/brave/browser-laptop/commit/acdf55e5d867c9c8712a6a80daab325d745057b5

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/36883950-aa53f83a-1e03-11e8-8507-92fd16690e79.png)

**Comment by bsclifton** [comment]
Will be downgrading soon to 4.9.0 so that we ONLY get Chromium 65 (and not the Dialog changes and other changes made with Muon 5.0.x)

**Comment by bsclifton** [comment]
Muon updated to 4.9.0 with 39573e464297e4a4583fbf7f665d3e463e9c5427

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/37262975-0362d7a0-25cc-11e8-9e97-9b59564d9fae.png)

**Comment by bsclifton** [comment]
Updated to 4.9.1 with https://github.com/brave/browser-laptop/pull/13409/commits/b9c7ca73da93b3d9c9fb1c83447fe95b701ef857

**Comment by kjozwiak** [comment]
Clearing, need to re-check and ensure that builds are using 4.9.2.

**Comment by bsclifton** [comment]
Updated to 4.9.3 with https://github.com/brave/browser-laptop/commit/e92dccdcf38788cb00a9d70ada714a02f1e9ca57

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/37586253-b3d78720-2b53-11e8-89da-d4a8c48e3b5f.png)
