### ISSUE TITLE
Using the "copy to clipboard" button to copy version information from about:brave results in an extra line at the top.

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#13355]
## Test plan
See https://github.com/brave/browser-laptop/pull/13389

### Description
Using the "copy to clipboard" button to copy version information from about:brave results in an extra line at the top.

### Steps to Reproduce
  1. Go to `about:brave`
  2. Click "copy to clipboard" to get the version information
  3. Paste the copied text somewhere.

**Actual result:**
Notice the top line which contains a single space. 
```
 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Expected result:**
```
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
See the actual/expected results.

**Reproducible on current live release:**
Yes

### Additional Information
It'd be great if, when fixing this, you could add a new line at the end, as well, so that the cursor ends up on the next line instead of directly after the `libchromiumcontent` version.

**Comment by jasonrsadler** [comment]
Closed with #13389
