### ISSUE TITLE
Allow to set default browser on Ubuntu

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1336]
Details here:
https://github.com/brave/browser-laptop/issues/429#issuecomment-206527667

**Comment by luixxiul** [comment]
Fixed already? https://github.com/brave/browser-laptop/issues/429#issuecomment-211413390

**Comment by bbondy** [comment]
nope not fixed yet.

**Comment by Sh1d0w** [comment]
Any info when this will be available for the Linux version?

Thanks

**Comment by henrikhodne** [comment]
As a workaround, this worked for me:

```
xdg-mime default brave.desktop text/html
xdg-mime default brave.desktop x-scheme-handler/http
xdg-mime default brave.desktop x-scheme-handler/https
xdg-mime default brave.desktop x-scheme-handler/about
```

This is assuming you're running a GNOME-like desktop of some kind, not sure if this works on KDE or Xfce or other desktop environments.

**Comment by Sh1d0w** [comment]
Thanks @henrikhodne 

To help others with similar problem, this is what I have done:

`vi ~/.local/share/applications/mimeapps.list`

And put the following code there:

`[Default Applications]
text/html=brave.desktop
x-scheme-handler/http=brave.desktop
x-scheme-handler/https=brave.desktop
x-scheme-handler/about=brave.desktop
x-scheme-handler/unknown=brave.desktop`

Brave is now the default browser on the system.

**Comment by willy-b** [comment]
This is fixed with #2839, I think. (Tested on Ubuntu 14.04)

**Comment by gutigen** [comment]
I suspect this is similar issue, if Brave is set as default browser all links from other apps put Brave in focus, but do not open in it (just focus, nothing else happens).

Arch Linux with GNOME Desktop, I added mimelist config too, still same issue. Brave compiled with `brave-git` from AUR.

**Comment by molinadavid** [comment]
same for me on Ubuntu 16.04
 
Brave: 0.18.16 
rev: 8003c6652559b1b624f8de37fc60e80f3a7cc01d 
Muon: 4.3.6 
libchromiumcontent: 60.0.3112.78 
V8: 6.0.286.44 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.4.0-87-generic 
OS Architecture: x64

**Comment by bsclifton** [comment]
+1 from @GGurtner via https://github.com/brave/browser-laptop/issues/10295
(Linux Mint 17.1 and 17.2)
