### ISSUE TITLE
Webview crash after detaching the tab

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13369]
### Steps to Reproduce
  1. add new tab (with plus sign)
  2. detach the added tab

**Actual result:**
Webview crash
the pages on the original window may crash also

**Expected result:**
No webview crash

**Reproduces how often:**
100%

### Brave Version
 
```
Brave: 0.21.654 
V8: 6.5.254.26 
rev: bc6272cac63ac15bf1449017c991243c1c843644 
Muon: 5.1.3 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.88
```

cc: @NejcZdovc @bsclifton @darkdh @kjozwiak

**Comment by hferreiro** [comment]
This bug was previously reported here: https://github.com/brave/muon/issues/478.

**Comment by bridiver** [comment]
so this is windows/linux only? Can't be reproduced on mac?

**Comment by hferreiro** [comment]
@bridiver correct, Windows/Linux only

**Comment by srirambv** [comment]
On 0.21.656 it doesn't cause webview crash instead it shows white blank screen. Reattaching on reloading the page doesn't load it correctly.

**Comment by bridiver** [comment]
@srirambv what muon version does 0.21.656 have? I'm not able to reproduce on win10 with a local build

**Comment by bridiver** [comment]
I'm using 4.9.0. I tried dragging the tab out of the window and the detach context menu item and both worked without a problem.

**Comment by bridiver** [comment]
I take that back, I can repro the white screen when detaching a background tab

**Comment by srirambv** [comment]
@bridiver this is about:brave info

Brave | 0.21.656
-- | --
V8 | 6.5.254.31
rev | c8e9925
Muon | 4.9.0
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.146

**Comment by hferreiro** [comment]
The crash is related to not creating new surface ids when the device scale factor is not 1.

I have applied some upstream commits that fix the issue in https://github.com/brave/muon/commits/fix/13369. I had to cherry-pick from my PR about using `git apply` (https://github.com/brave/muon/pull/341) because the current hook doesn't support creating new files.

**Comment by bridiver** [comment]
closed with https://github.com/brave/muon/commit/2231f5b7716e6bfeffa6ed06d5b2d6f0fe4c9a26
