### ISSUE TITLE
Add more functionality around suspending tabs

### ISSUE THREAD

**Issue by cesarmarinhorj** [brave/browser-laptop#1337]
hi,
nice work doing Brave. Amazing!

I start using it and has a quastion about memory consumption.

one chrome plugin that saved my life in my modest (really) desktop - 2GB of RAM was "The Great Suspender", it disable tabs not used to save memmory. Link: https://github.com/deanoemcke/thegreatsuspender

how Brave handle that?
 - it magically do that?
- it will support some essentials chrome plugins?

thanks!

**Comment by bbondy** [comment]
We actually want similar functionality built in.

**Comment by luixxiul** [comment]
Closing this duping to #415. Let's continue discussion there.
