### ISSUE TITLE
Strange console logs (beta)  

### ISSUE THREAD

**Issue by HotelBellaMuerte** [brave/browser-laptop#13379]
version: 0.21.654

kernel: 4.15.7

gpu: rx 560

https://p.teknik.io/3zMif

**Comment by bn0785ac** [comment]
chromium embeded: 65.0.3325.88

PD it must be updated to 65.0.3325.106

**Comment by bn0785ac** [comment]
you couldreview your gn flags (i mantain some chromium based browsers and i dont get this bug)  

its a bit disturbing because if you run brave from terminal,  you need run Ctrl+C / kill the terminal tab
