### ISSUE TITLE
disable webusb API

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13374]
webusb can be used to bypass yubikey phishing protection at the moment: https://www.wired.com/story/chrome-yubikey-phishing-webusb/ -> we should disable navigator.usb

@flamsmark also suggested disabling navigator.bluetooth

maybe also https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon ?

**Comment by diracdeltas** [comment]
we actually don't support bluetooth yet AFAIK. https://googlechrome.github.io/samples/web-bluetooth/device-info.html?allDevices=true fails without showing a prompt in Brave.

**Comment by diracdeltas** [comment]
will use the same implementation as https://github.com/titanous/disable-webusb

**Comment by karel-3d** [comment]
Hello

I am a developer of Trezor - a cryptocurrency hardware wallet - and in next iteration of our products, we will support WebUSB.

I have tested WebUSB version of Trezor, and WebUSB doesn't actualy work in Brave. (Tested on Linux.)

`navigator,usb` is defined, but `navigator.usb,getDevices()` does not show the device picker, so the web never gets the permissions.

Our web wallet detects whether webusb is defined via navigator.usb, if it is not defined, we offer user to install a local server which browser then connects to. Anyway, this detection is broken in Brave - navigator.usb is defined, yet `navigator.usb.getDevices()` never shows anything.

So please, either disable it or fix it. Right now, webUSB is enabled, but broken. Which is actually good security-wise (nobody can access any device anyway), but bad from web developer point of view.

(Btw - [here is the public Chrome issue that deals with this](https://bugs.chromium.org/p/chromium/issues/detail?id=819197&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) - Google's solution is just blacklist the yubikey IDs. This is working to patch the bug, but not fixes the underlying issue, which would be fixable by *at least* optional descriptors, as I noted there and on the webusb github https://github.com/WICG/webusb/issues/127 )

**Comment by karel-3d** [comment]
I would personally prefer if the webusb was enabled, but the descriptor rules enforced :) but that would require changes probably beyond the scope of Brave

**Comment by diracdeltas** [comment]
@karel-3d as you can see in https://github.com/brave/browser-laptop/pull/13375 it's going to be disabled for now

**Comment by karel-3d** [comment]
Hm, this seems that navigator.webusb is still defined, but the functions return error. This is not ideal :/ as it requires special casing

**Comment by diracdeltas** [comment]
@karel-3d good point. i think i can set them to undefined

**Comment by karel-3d** [comment]
Thanks, this will help!

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-laptop/pull/13375 updated
