### ISSUE TITLE
Sign-In Popup Windows/General Legit Popup Windows don't close automatically.

### ISSUE THREAD

**Issue by adambirds** [brave/browser-laptop#13370]
### Description
When you try and sign-in on a website, which opens a sign-in popup in a new window. These windows do not automatically close upon sign-in like they do in Chrome/Firefox/Opera. This doesn;t just affect sign-in windows, but any site which uses popup windows that then close. For example we use a ticket system called AutoTask. To add a time entry it opens a window, you click save time entry, and this should close the window automatically, it doesn't.

### Steps to Reproduce

  1. Use a website that has you sign-in using a pop-window. One example is netflix.com when you try to sign-in using Facebook.
  2. Sign In.
  3. The window will not close automatically.

**Actual result:**
Window doesn't close automatically.

**Expected result:**
Window should close automatically.

**Reproduces how often:**
99.9% - 100%

### Brave Version

**about:brave info:**
 
Brave: 0.20.46 
V8: 6.4.388.41 
rev: 5eb035c2d68225994a572a1d62861cf961355ab2 
Muon: 4.8.2 
OS Release: 4.14.14-300.fc27.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Yes, happens in both Linux (Fedora) and Windows that I have tested.

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/9610
>When composing an email on mail.google.com and trying to 'pop-in' a new message which I had already chosen the 'pop-out' option for, the extra popup window does not close automatically.
>
> Steps to reproduce:
> 
> 1. Open mail.google.com and login.
> 2. Select the 'Compose' button. New message is displayed within the browser.
> 3. Locate the double arrow (upper right corner of the new message).
> 4. Shift + click on this icon.
> 5. New Message is opened in a popup window as expected.
> 6. Locate the arrow pointing down and to the right (upper right corner of the new message).
> 7. Click on this icon.
> 8. New message window stays open as well as opens up back in the browser.

**Comment by bsclifton** [comment]
I believe this issue is happening because the API called (chrome window close) is not supported (yet)

cc: @jonathansampson

**Comment by jonathansampson** [comment]
I have noticed this too, with Tweet-popups. We do have support for `window.close`, but in cases where the tab closed was the only tab in the Window, the Window itself remains open. I believe this is the issue.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/office365-popup-email-windows-do-not-close/21072?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/login-popups-never-close-after-login-is-complete/25973?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/login-with-facebook-leaves-popup-open/26461?u=eljuno

**Comment by pbreit** [comment]
I am experiencing this issue, too both on Google and Facebook single sign ons. Not only does the pop-up not close but the login doesn't appear to actually happen (ie, I am not granted access to the website that initiated the "Sign In with Google"; for example Glassdoor).

**Comment by bsclifton** [comment]
This issue is fixed with Brave Core (our upcoming replacement for the current Muon codebase)
