### ISSUE TITLE
Clicking on Dashlane icon goes to about:blank

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#13384]
### Description

I've enabled Dashlane as my password manager and I've also desktop app running and it works in other web browsers. When I click the Dashlane icon: 
<img width="58" alt="screen shot 2018-03-04 at 18 48 49" src="https://user-images.githubusercontent.com/266306/36949180-bb3d9f7c-1fdc-11e8-9113-625f6bfb38fa.png">, and new tab is open, but nothing is loaded. The tab reads Untitled and its address is `about:blank`.

### Steps to Reproduce

  1. Enable Dashlane as password manager.
  2. Click on the top-right Dashlane icon (should be grayed-out).

**Actual result:**

<img width="858" alt="screen shot 2018-03-04 at 18 50 22" src="https://user-images.githubusercontent.com/266306/36949195-f110886c-1fdc-11e8-9f0a-b3321f09c630.png">

**Reproduces how often:** Always.

### Brave Version
 
Brave: 0.20.46 
V8: 6.4.388.41 
rev: 5eb035c2d68225994a572a1d62861cf961355ab2 
Muon: 4.8.2 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:** Yes.

**Comment by eljuno** [comment]
Can not reproduce on Win 8.1 x64 with Brave 0.21.18.

- Clicking grayed Dashlane icon will open Dashlane app log-in dialog.
- Log-in to Dashlane app make Dashlane extension active and logged in.

**Comment by Userbv** [comment]
Same problem for me here

**Comment by leiberl** [comment]
Same here. The extension doesn't work at all.
MacOs 10,13,3
Brave: 0,21,18

**Comment by eljuno** [comment]
++ from community https://community.brave.com/t/dashlane-sign-on-does-not-work/17422?u=eljuno

cc @bsclifton @jonathansampson for visibility. :)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/dashlane-extension-not-working/17523?u=eljuno

Brave: 0.21.18 on Windows 10
> The extension is on in preferences but is greyed out in Brave and clicking on the icon results only in an untitled tab opening

**Comment by ConnoisseurDave** [comment]
same issue reproduced consistently here
Brave: 0.21.18
V8: 6.4.388.41
rev: 580be78
Muon: 4.8.2
OS Release: 10.0.16299
Update Channel: Release
OS Architecture: x64
OS Platform: Microsoft Windows 10
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.140

Dashlane: 5.7

**Comment by bsclifton** [comment]
+1 from @Ben-Epstein via https://github.com/brave/browser-laptop/issues/13448
> The dashlane plugin for brave is no longer working on V0.21.18
When attempting to click "login" on login box, or the icon on top left, new blank tab opens but nothing ever loads.

**Comment by bsclifton** [comment]
+1 from @iamaya via https://github.com/brave/browser-laptop/issues/13479
> ### Steps to Reproduce
> 1. Open Preferences -> Extensions
> 2. Turn On Dashlane Plugin
> 3. Dashlane icon (greyed out) shows up in the top bar
> 4. Opens an empty tab when clicked on the Dashlane icon and nothing happens

**Comment by CountZachula** [comment]
Same issue here---only I discovered it when attempting to log into Dashlane from a form popover. See screenshot.

Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

## Steps to Reproduce

1. Enable Dashlane plugin
2. Navigate to a login form
3. Focus on form and Dashlane sign-in prompt should appear
4. Click "Log in now"
5. `about:blank` tab is created

<img width="402" alt="screen shot 2018-03-21 at 09 28 20" src="https://user-images.githubusercontent.com/2559507/37700031-5a52cf6e-2cea-11e8-8f79-eb46e5401b75.png">
<img width="413" alt="screen shot 2018-03-21 at 09 30 17" src="https://user-images.githubusercontent.com/2559507/37700084-7f2d82d4-2cea-11e8-9782-36fb0bc3c227.png">

**Comment by leiberl** [comment]
I still have the same issue although I have updated Brave.
Mac 10.13.3

Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by btlechowski** [comment]
Reproduced in v0.22.6 Win7

**Comment by Dawsonjjune** [comment]
I was able to fix this issue in a roundabout way. 

By going to the Dashlane website and logging in on Brave, the login page was treated as a Chrome extension. When I logged in, Dashlane finally began working on Brave, storing passwords and such.

I'd rather login on the extension itself, but this worked. Hope it helps.

**Comment by iamaya** [comment]
@Dawsonjjune - This works on the Mac. Good suggestion. Thanks!

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/dashlane-extension-does-not-work-opens-an-empty-tab-when-trying-to-auth/18666?u=eljuno

**Comment by niallone** [comment]
Can confirm that going to the Dashlane website and logging in causes the greyed out icon to become active again, and appears to resolve the problem. Thanks for the suggestion @Dawsonjjune 
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/dashlane-extension-not-working-opens-blank-tab/19003?u=eljuno

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/dashlane-isnt-helping/22880

**Comment by bsclifton** [comment]
workaround described here:
https://github.com/brave/browser-laptop/issues/13479#issuecomment-386884245
> [ Posting here as it appears first in google results ]
> 
> To fix this problem :
> 
> Open : https://app.dashlane.com in the brave browser as normal page, log in, restart browser.
> Extension should start working.
> 
> If that doesn’t work :
> 
> type chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/login in the address bar then log in. Restart browser.
> 
> Extension should be working now.
> 
> PS. got few core dumps on linux trying to user the extension so might actually be unstable.

**Comment by ScoobyJD** [comment]
I can confirm that the first fix from bsclifton has worked for me. Windows 10 x64, latest brave version.

**Comment by ScoobyJD** [comment]
I have been noticing every time I close brave and reopen that I have to go and sign into dashlane every time. Is there any way that we can get this fixed? I never use to have this problem, I have no idea what has changed.

**Comment by ScoobyJD** [comment]
So when is this going to be fixed? Every time we close the browser we are automatically logged out. This as a base feature needs to be fixed especially when its is the main featured plugin. Please update us on the current status of this.

**Comment by darkdh** [comment]
fixed in muon 8.0.9

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using 
* 0.23.105 9a46f8f
* Muon `8.0.9`
* libchromiumcontent `68.0.3440.84`
* Verified enabling extension opened Dashlane create account page
* Verified Autofill works on a saved credential in Dashlane
* Verified clicking on Dashlane icon open up vault manager
* Verified no errors shown on extension background page
