### ISSUE TITLE
Frozen Pages from Left Click Tabs Opener

### ISSUE THREAD

**Issue by Hempthusiast** [brave/browser-laptop#13387]
Yes I did try to find my issue by typing up to 50 words that could be related and couldn't find anything similar.

### Steps to Reproduce

  1. https://www.Twitch.tv/Hempthusiast
  2. Click on any links with the Left Click.

**Actual result:**

**Expected result:**
Just cannot click anything neither scroll,

**Reproduces how often:**

100% times I right click; Middle click doesn't make it happens.

### Brave Version

**about:brave info:**

 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

Live build? Meaning the browser, if so; yes!?

**Comment by bsclifton** [comment]
Unable to reproduce on latest version- if there was a problem, it was likely fixed 😄 👍
