### ISSUE TITLE
google search does not work

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#13394]
### Description
Google search does not work. Type into location bar: `asdfasdf` — OR — go to https://www.google.com and type into the search field: `asdfasdf`

**Actual result:**
This site can’t be reached page.

**Expected result:**
Should work like it does in Chrome.

**Reproduces how often:**
100% repeatable. Restarted computer; same result.

### Brave Version
0.21.18
**about:brave info:**

**Reproducible on current live release:**

**Comment by GarrettS** [comment]
![dxizztwvqaizkeo jpg_large](https://user-images.githubusercontent.com/56098/37213324-915ccc86-2366-11e8-86da-c37acc213b6e.jpg)

**Comment by coreyhaines** [comment]
I get this, as well.

**Comment by jonathansampson** [comment]
Are either of you able to confirm whether a request is being made in the first place, and what the server-response is? For instance, you could use [Fiddler ](https://www.telerik.com/download/fiddler) to monitor the request/response.

**Comment by coreyhaines** [comment]
Have to go, but will do more debugging this weekend. I did a quick look into the dev console, and I'm not sure that the request is being made at all.

![image](https://user-images.githubusercontent.com/3962/37217815-345cc16c-2384-11e8-9135-3ead2258b4fc.png)

**Comment by coreyhaines** [comment]
I'll bring fiddler up tomorrow.

**Comment by bsclifton** [comment]
@GarrettS do any sites work for you? We have a known issue for when you're setup using a proxy:
https://github.com/brave/browser-laptop/issues/12959

**Comment by bsclifton** [comment]
possibly related: https://github.com/brave/browser-laptop/issues/13058

**Comment by GarrettS** [comment]
Yes, @bsclifton other websites work. 

Funny thing is that Gmail was blocked in brave for a while but I could use it in other browsers. Then one day Gmail working brave but google search stopped working in brave.

I don’t know what strategy google was using to retrieve this resolved but it sure is strange.

**Comment by GarrettS** [comment]
Achieve this result, not retrieve this resolved. Apple dictation really as shit

**Comment by eljuno** [comment]
++ from community https://community.brave.com/t/google-search-returns-blank-page-with-err-failed-message/17447?u=eljuno and https://community.brave.com/t/google-search-not-working/15671?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/brave-doesnt-open-google/18099?u=eljuno

**Comment by GarrettS** [comment]
Today, Google search is working for the first time in many weeks using Brave. I use brave everyday.

**Comment by bsclifton** [comment]
@GarrettS @coreyhaines I'm curious: do either of you have the following item enabled on the Preferences > Search page?
![screen shot 2018-03-22 at 10 28 16 pm](https://user-images.githubusercontent.com/4733304/37812994-6695f594-2e20-11e8-85c5-61e39ffb1be9.png)

If so, this may be related to this issue: https://github.com/brave/browser-laptop/issues/13469

**Comment by Beasta** [comment]
having this issue. this [post](https://www.reddit.com/r/BATProject/comments/83ryko/google_searches_not_working_on_brave_browser/dvn7tyf/) on reddit mentioned something about vpn being the issue? I'm using a vpn.

**Comment by soldcake** [comment]
google search works again on brave for windows version 0.22.13
+1

**Comment by ceich** [comment]
I cleared all browsing data and it works again. Just clearing cache didn't do the job, might be cookies.
