### ISSUE TITLE
Close tab to the right closes the tab that is right clicked on as well

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#13391]
### Steps to Reproduce

  1. Right click on a tab.
  2. Select "Close tabs to the right".

**Actual result:**
The tab and tabs to the right of it are closed.

**Expected result:**
Only tabs to the right of it are closed.

**Reproduces how often:**
Sometimes.

### Brave Version
 
Brave: 0.20.46 
V8: 6.4.388.41 
rev: 5eb035c2d68225994a572a1d62861cf961355ab2 
Muon: 4.8.2 
OS Release: 4.13.0-36-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
Yes.

**Comment by jwalker** [comment]
This should be fixed in Brave: 0.21.18. Can you confirm after upgrading to the current release @jamesray1  ?
