### ISSUE TITLE
Local storage is blocked on `127.0.0.1`

### ISSUE THREAD

**Issue by wbobeirne** [brave/browser-laptop#13390]
### Description

When running a website on `127.0.0.1`, local storage is blocked with the following warning:

> Warning: corrupted local storage DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

However, running the exact same site on `localhost` doesn't encounter that problem.

### Steps to Reproduce

I'll try to whip up a quick example of this in isolation, but I can say this happens when running our MyCrypto app with `npm run dev` here: https://github.com/MyCryptoHQ/mycrypto. `localhost:3000` is fine, but `127.0.0.1:3000` is not.

**Reproduces how often:** 100%

### Brave Version

**about:brave info:**
Brave | 0.21.18
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 17.3.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by bsclifton** [comment]
You should be able to turn off shields / allow cookies for 127.0.0.1 via the Shields menu (the lion icon in the top right). If that doesn't do the trick, this should be addressed for sure with our developer channel release, which you can check out here:
https://brave.com/download-dev
