### ISSUE TITLE
ads bypassing shields on coinmarketcap.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#13398]
### Description
Ads appearing below the fold on coinmarketcap.com on macOS. 
![macos-cmc-ad-in-page-03062018](https://user-images.githubusercontent.com/8979240/37066688-67a9c392-215b-11e8-9f9a-2a86d4002245.png)

Unable to reproduce on win64. 

### Steps to Reproduce

  1. From macOS, go to coinmarketcap.com
  2. Scroll below the fold.
  3. See ad.

**Actual result:**
see screenshot above

**Expected result:**
no ads

**Reproduces how often:**

100% reported from macOS. 

### Brave Version

**about:brave info:**

0.21.18
--

**Reproducible on current live release:**

yes

### Additional Information

ad call identified on macOS: 
`https://l1.appsha3.space/js/?wkey=asjap8`

![macos-cmc-ad-network-traffic-0-03062018](https://user-images.githubusercontent.com/8979240/37067133-4c18255e-215d-11e8-97b5-6a9b811ac9ed.png)

![macos-cmc-ad-network-traffic-1-03062018](https://user-images.githubusercontent.com/8979240/37067139-50b69974-215d-11e8-90bc-0bb7b0bebaa2.png)

we block the same request on win64: 
![coinmarketcap-network-03062018-blocked-requests](https://user-images.githubusercontent.com/8979240/37067162-6debbf6a-215d-11e8-919d-0e50d68505ac.PNG)

The only difference observed from brave shields was that block all fingerprinting was enabled on macos, but block 3rd party fingerprinting was set on win64. That said, a re-test with block 3rd party fingerprinting enabled on macOS returned the same result. 

shield in macOS
![macos-cmc-ad-blocking-shields-03062018](https://user-images.githubusercontent.com/8979240/37067191-9d93170e-215d-11e8-9401-760574f878be.png)

shield in win64
![win64-cmc-ad-blocking-shields-03062018](https://user-images.githubusercontent.com/8979240/37067235-cbe44f74-215d-11e8-8c88-11ac34d1b385.PNG)

Next steps: 
 - test filtering rule in macOS for the ad call: `||l1.appsha3.space^$third-party`
 - if test resolves on macOS, apply custom filter rule to resolve. 

cc: @NejcZdovc for visibility.

**Comment by jamesray1** [comment]
I get ads on coinmarketcap.com with Ubuntu.

**Comment by bbondy** [comment]
Is this still happening? I think an upstream list might have handled this. I was getting it too but not anymore.

**Comment by jwalker** [comment]
I do not see any ads so no replication for me.
 
about:brave info:
![screen shot 2018-03-10 at 2 57 18 pm](https://user-images.githubusercontent.com/4896469/37247668-97ef8d0a-2473-11e8-99f4-5a6e6191664c.png)

Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by bbondy** [comment]
Closing this since I think it was a temporary thing fixed by an adblock update.  If anyone still experiences this regardless of the platform, a restart of the app should fix it.
