### ISSUE TITLE
Error when trying to save password

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13408]
### Description
Discovered via our error reporting:
https://stats.brave.com/dashboard#crash/5a95892d61aacc001f002e82

```
Error: Object has been destroyed at Object.passwordCallbacks.(anonymous function)
(/Applications/Brave.app/Contents/Resources/app.asar/app/browser/reducers/passwordManagerReducer.js:110:17)
  at EventEmitter.ipcMain.on
  (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/reducers/passwordManagerReducer.js:22:33)
  at emitMany (events.js:132:20) at EventEmitter.emit (events.js:204:7)
  at WebContents.
  (/Applications/Brave.app/Contents/Resources/electron.asar/browser/api/web-contents.js:180:13)
  at emitTwo (events.js:106:13) at WebContents.emit (events.js:194:7)
```

### Test plan / Steps to Reproduce

1. run brave from terminal
2. Use Brave as password manager (not extension)
3. Open a site which has login via password (e.g. twitter.com)
4. Login
5. Observe prompt to save password
6. Close tab which was used for login
7. Click save password

**Actual result:**

Error in console as above

**Expected result:**
No error in console and no crashes appearing under `chrome://crashes/`

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

yes

**Comment by kjozwiak** [comment]
I went through https://github.com/brave/browser-laptop/issues/13408#issue-303748653 and also ensured the following:

* ensured that clicking on `Deny` doesn't produce the original issue mentioned above
* ensured that clicking on `Never for this site` doesn't produce the original issue mentioned above
