### ISSUE TITLE
selector spilling when viewing imported bookmarks

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13419]
### Description

When scrolling through imported bookmarks, you'll notice that the selector will spill over on the right hand side.

### Steps to Reproduce

  1. launch `0.21.656` b780074db7f2400296e9f2747f3f6dbae2a0d4c7
  2. visit `about:bookmarks` and import the file linked below
  3. once imported, move the `Sec Tools` folder onto the Bookmark Toolbar
  4. click on `Sec Tools` and scroll through the bookmarks, you'll notice the selector is being spilled

Example file that can be used: https://drive.google.com/file/d/1hTlLtP2bkNM-265ilSJGWejHtG3T1NzR/view?usp=sharing

**Actual result:**

![importedbookmarks](https://user-images.githubusercontent.com/2602313/37267704-70b572c4-2598-11e8-9eed-1c1bdee01b80.gif)

**Expected result:**

Selector shouldn't be spilling over.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> 
> Brave: 0.21.656 
> V8: 6.5.254.31 
> rev: b780074db7f2400296e9f2747f3f6dbae2a0d4c7 
> Muon: 4.9.0 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 
> libchromiumcontent: 65.0.3325.146

**Reproducible on current live release:**

No, I couldn't reproduce the above issue under `0.21.18` 580be782bc37ed8580dd22f79e1d2d355fddfb89 after several attempts.

### Additional Information

* macOS 10.13.3 x64 - Reproduced
* Win 10 x64 - Reproduced

**Comment by darkdh** [comment]
dup https://github.com/brave/browser-laptop/issues/13373 because your data has long name

**Comment by kjozwiak** [comment]
Thanks @darkdh, missed #13373 when going checking for similar issues, hence creating one. I'll leave it in the milestone so we can double check and make sure the highlighting works as expected once #13373 has been fixed.
