### ISSUE TITLE
Sites are not added to the ledger table

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13410]
### Description

This was broken with https://github.com/brave/browser-laptop/pull/13236

### Steps to Reproduce

  1. Enable payments
  2. Visit a site

**Actual result:**

Site is not added to the table

**Expected result:**

**Reproduces how often:**

Site should be added to the table

### Brave Version

**about:brave info:**

0.23 up

**Reproducible on current live release:**

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.8 06c657b
•	Muon 6.1.5
•	libchromiumcontent 66.0.3359.181
