### ISSUE TITLE
LastPass not autofilling or filling in a private tab

### ISSUE THREAD

**Issue by bbw22** [brave/browser-laptop#13412]
### Description
I could not find this exact issue. If you open a private tab and have the login information in LastPass. Not only does LastPass not show the its icon beside the login fields, it does not auto fill. Either by itself or by selecting auto fill from the LastPass menu

### Steps to Reproduce

  1. Open a private tab
  2. Enter the url to a site where you have login credentials in LastPass. (e.g., LinkedIn.com, Google.com)
  3. Look to see if the Lastpass icon is next to the login fields
  4. If not then use the auto fill option from the LastPass menu for that site

**Actual result:**
literally nothing happens. you have to copy and paste or type in the login information

**Expected result:**
LastPass should know that there are login credentials for the site. It should place an icon next to the login fields that you can select. You should also be able to use the auto fill menu from the LastPass menu for that site.

**Reproduces how often:**
100%

### Brave Version
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
yes

### Additional Information
There were also issues with 2FA with Google in the private tab (still need to search on this one to see if anyone else encountered it).

**Comment by eljuno** [comment]
Dupe of #6722?

**Comment by bbw22** [comment]
It looks like it is.
