### ISSUE TITLE
Sometimes hyperlinks don't open a new tab

### ISSUE THREAD

**Issue by arsalankhalid** [brave/browser-laptop#13413]
### Description
Sometimes specific hyperlinks don't open a new tab. On OSX, even cmd click doesn't open a new tab, nor does right clicking and selecting 'open in new tab'.

### Steps to Reproduce
  1. Go to a site like: https://docs.corda.net/tutorial-observer-nodes.html?highlight=observer%20node
  2. Scroll to the very bottom
  3. Click hyperlink which is prefaced with 'the issue is tracked here'
  4. Try opening a new tab using cmd click, or right click, open a new tab

GIF

**Expected result:**
A new tab should open when pressing cmd click, or right click, open in new tab

**Reproduces how often:**
100% of the time for this specific link, but doesn't seem to happen for other links

### Brave Version
Latest user version

### Additional Information
![open_new_tab](https://user-images.githubusercontent.com/5307218/37254414-dc089d7e-2513-11e8-8349-4c3ae40996cd.gif)

**Comment by eljuno** [comment]
Same as #13017?

**Comment by arsalankhalid** [comment]
Yes @eljuno you're right, closing and reposting on that issue - will actually try taking a stab at it :)
