### ISSUE TITLE
Prefetch Requests like UC Browser

### ISSUE THREAD

**Issue by i2plover** [brave/browser-laptop#1342]
This is a feature request / enhancement for Brave.

UC Browser will prefetch/prerender requests when you hover over links (Such as text links, or images) so that the next page will load instantly. It does this with up to 5 links, then it will discard the oldest prefetch on that page so it can prefetch the next one you hover over. 

If I hover over 6 images that link to new pages, the first image I hovered over will be discarded so that the 6th image is fresh and pre rendered.

**Comment by luixxiul** [comment]
@bbondy doesn't Brave use the resource hints as other browsers like Chrome/Firefox do?

**Comment by bbondy** [comment]
I'm not sure off hand. CC'ing @bridiver and @diracdeltas to see if they know.

**Comment by bridiver** [comment]
prefetch is part of chrome/browser so we don't currently support it
