### ISSUE TITLE
Handle bat-client errors more gracefully

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13426]
If the `bat-client` doesn't return a wallet within 20 seconds, then `ledger.js` should tell the user that the service is unavailable.

**Comment by NejcZdovc** [comment]
@bradleyrichter how/where should we display this?

**Comment by bradleyrichter** [comment]
@NejcZdovc Perhaps you could use the recent alert panel that we used for grants.

**Comment by NejcZdovc** [comment]
@bradleyrichter sure I can use that. Can you create a mock for it?

**Comment by mrose17** [comment]
i am closing this due to lack of interest.
