### ISSUE TITLE
As soon as a transfer happens, update the status immediately to indicate contribution in progress 

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13423]
at present, there is a time interval in which the transfer has occurred, but the status doesn't indicate anything. It should say something like "Your contribution is being processed." @bradleyrichter will provide the exact wording.

**Comment by NejcZdovc** [comment]
@bradleyrichter can you please provide wording

**Comment by bradleyrichter** [comment]
@mrose17 @NejcZdovc 

how about this?

![image](https://user-images.githubusercontent.com/13509546/37324101-c27d5fde-2644-11e8-8882-1900510959c4.png)


"Currently in process"

**Comment by mrose17** [comment]
that works!

**Comment by LaurenWags** [comment]
@NejcZdovc @bradleyrichter I'm seeing 'Currently processing' instead of 'Currently in process' - expected?

![screen shot 2018-03-23 at 4 02 52 pm](https://user-images.githubusercontent.com/28145373/37851033-c91a5c3a-2eb3-11e8-9b0a-30b44d0f6d3c.png)

**Comment by bradleyrichter** [comment]
@LaurenWags yes, we changed it. (shorter and sweeter, and more grammatically correct)

**Comment by LaurenWags** [comment]
awesome, thanks for the confirmation!

**Comment by kjozwiak** [comment]
Went through verification on both macOS 10.13.3 x64 and Windows 10 x64 using the following build:

* `0.22.7` 8bb7e77
* libchromiumcontent: `65.0.3325.181`
* muon: `5.1.1`
