### ISSUE TITLE
contribution statement very different from ledger table

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13427]
### Description
Some users have reported that the content creators included in their contribution statement are very different than what was expected based on those listed in their ledger table. Reported both internally (@kjozwiak ) and in community (https://community.brave.com/t/monthly-payment-completely-different-than-projected/17740)

### Steps to Reproduce

Unknown. Users have generally reported that they view their ledger table expecting one set of sites to get contributions but then other sites get contributions instead.

Here is an example from @kjozwiak:
This is his ledger table:
<img width="443" alt="screen_shot_2018-02-25_at_9 19 21_pm_1024" src="https://user-images.githubusercontent.com/28145373/37309784-5354d118-2618-11e8-8605-36c539d7850a.png">

And these are the sites which were included on his contribution statement:
<img width="833" alt="screen_shot_2018-02-25_at_9 19 31_pm" src="https://user-images.githubusercontent.com/28145373/37309887-ad77341a-2618-11e8-957c-89b85f4c5e6b.png">

Kamil made these observations:
* humblebundle.com (12 views, 11min34s) - there's definitely websites that have more views but this was selected
* AwakenWithJP on YT (2 views, 4min 13s) - this one definitely shouldn't have been added
* battle.net (11 views, 11min19s) - basically spent some time restarting 2FA/changing password over the weekend.. Surprised this was added
* chromium.org (1 view, 42s) - this one definitely shouldn't have been added (probably the most alarming one)
* wikipedia.org (12 views, 15min20s) - there's definitely websites that have more views but this was selected

**Actual result:**
sites only visited once or a couple of times were selected over sites that had many more views/time spent

**Expected result:**
contribution should have been more in line with ledger table sites

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
multiple

**Reproducible on current live release:**
Yes

**Comment by upcyclist** [comment]
@NejcZdovc, my experience was similar--only 9 sites/channels out of the many I visited got 11.11% each. I'm happy to post a screenshot & my last payment report if you wish.

**Comment by NejcZdovc** [comment]
@srirambv please past ledger-state.json file that was generated when doing this last test
