### ISSUE TITLE
The favorites order is not respected when using sync

### ISSUE THREAD

**Issue by eTorAken** [brave/browser-laptop#13420]
### Description
When I try to sync 2 Brave browsers from two different computers, the favorites are synchronized correctly but the order that they appears in the personal task bar is not respected.

### Steps to Reproduce
  1. Install and sync the first computer's Brave browser
  2. Install and set-up sync into a second computer's Brave browser

**Actual result:**
Computer 1 favorites order: ![Computer #1 favorites order](https://i.gyazo.com/3e8fd81fcdd506efca1d9b9c9d3a9293.png)
Computer 2 favorites order: ![Computer #2 favorites order](https://i.gyazo.com/a180bdb8d4d9594c18f503eb4fab8dfb.png)

**Expected result:**
Computer 1 favorites order: ![Computer #1 favorites order](https://i.gyazo.com/3e8fd81fcdd506efca1d9b9c9d3a9293.png)
Computer 2 favorites order: ![Computer #2 favorites order](https://i.gyazo.com/3e8fd81fcdd506efca1d9b9c9d3a9293.png)

**Reproduces how often:**
It never worked, even if I do a "Reset Sync..." from the second computer.

### Brave Version

**about:brave info:**
```
Brave | 0.21.18
-- | --
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140
```

**Reproducible on current live release:**
Yes: 0.21.18

**Comment by MargarytaChepiga** [comment]
If no one is working on it, I would love to give it a try!

**Comment by bsclifton** [comment]
@MargarytaChepiga this would likely be a fix needing to happen in https://github.com/brave/sync (doesn't look like there's an owner yet)

This bug is tracked with these two issues:
[Bookmarks Out of Order across Devices](https://github.com/brave/sync/issues/176)
[sync : bookmark order inside of folders is not being maintained](https://github.com/brave/sync/issues/104)

**Comment by bsclifton** [comment]
marked as upstream since fix would be in the sync client library
