### ISSUE TITLE
Remind the user to generate a backup file

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13425]
## Test plan
See https://github.com/brave/browser-laptop/pull/13504

## Original issue description
If the user has not created a backup file within 1 week of `bootStamp`, generate a notification reminding them to do so, with a button that brings up the dialog. The usual rules apply: "don't remind me", "remind me later", etc.

**Comment by jasonrsadler** [comment]
@mrose17 @bradleyrichter 
We have no way of knowing if an existing user has backed up their keys.
How should notifications be handled for existing users that update to new version?

Option 1:
This change should only work for new users (existing users that haven't backed up will not receive notification)

Option 2:
This change works for all users (which means existing users that have backed up will receive notification)

**Comment by srirambv** [comment]
@jasonrsadler mind updating the issue with verification steps.

**Comment by srirambv** [comment]
Moving based on feedback triage discussion and assigning to @mandar-brave

**Comment by bsclifton** [comment]
Closing as the revert was reverted

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.714 fa2fbca
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
