### ISSUE TITLE
Brave adblocker isnt working

### ISSUE THREAD

**Issue by HotelBellaMuerte** [brave/browser-laptop#13435]
Site with the trouble:  #[Link](http://www.tvxpc.com/tv/musica/vh1/) 

I see an ad  [Brave screenshot](https://u.teknik.io/1rmKq.png)

And i've brave adblocker turned + antifingerprint  turned on

This is what i want to see (ublock+umatrix+https everywhere)   
[Inox + *edgy* extensions](https://u.teknik.io/wt22e.png)

Sorry for disturb

**Comment by Stosswalkinator** [comment]
What are steps to produce? Is it only on that one site or others? What is your about:brave info?

**Comment by bn0785ac** [comment]
just browse to this site and click play  

no more

**Comment by bn0785ac** [comment]
https://u.teknik.io/1hYLV.png
