### ISSUE TITLE
Handle pinned sites separately when doing contribution

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13431]
### Test Plan
https://github.com/brave/browser-laptop/pull/13530

### Description

Pinned sites should be excluded from the statistical voting.

**Comment by LaurenWags** [comment]
@NejcZdovc @mrose17 How 'off' is acceptable for pinned sites (per the test plan)? one of mine is off by almost 20:

![screen shot 2018-03-23 at 4 14 46 pm](https://user-images.githubusercontent.com/28145373/37851503-83ff5be4-2eb5-11e8-91cc-9786e4d59d4e.png)

![screen shot 2018-03-23 at 4 16 25 pm](https://user-images.githubusercontent.com/28145373/37851507-8e0d24a4-2eb5-11e8-91eb-054473116636.png)

cc @kjozwiak @btlechowski

**Comment by NejcZdovc** [comment]
@LaurenWags can you please provide monthly amount, ledger-state and which version you are on

**Comment by LaurenWags** [comment]
monthly amount is 7.5 and I was using 0.22.7. I don't have ledger state.

**Comment by NejcZdovc** [comment]
This is what I get when I set 10 BAT

<img width="1899" alt="screen shot 2018-03-27 at 8 24 05 am" src="https://user-images.githubusercontent.com/9574457/37950276-3ce8ed84-3198-11e8-8fb1-163d5adca83b.png">

Will try with 7.5 now

**Comment by NejcZdovc** [comment]
Closing this as this was implemented, but we will need to fine tune it a little bit more. Will create another issue for that.

**Comment by LaurenWags** [comment]
Thanks for opening up the new issue @NejcZdovc !

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.8 https://github.com/brave/browser-laptop/commit/3ae27f2cf188b50ff64877a0968361d625fb84ca
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
