### ISSUE TITLE
Geolocation often times out/is generally sluggish

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13446]
### Description
Geolocation tests are often timing out/generally slow to find location as compared to version 0.21.18.

### Steps to Reproduce

1. Clean install of 0.21.657
2. Navigate to https://browserleaks.com/geo, Allow on the Notification. Your location is displayed.
3. Navigate to https://html5demos.com/geo/, Allow on the Notification. It won't display your location.
4. Close/Restart Brave.
5. Navigate to https://html5demos.com/geo/, Allow on the Notification. Your location is displayed.
6. Navigate to https://browserleaks.com/geo, Allow on the Notification. It won't display your location.

**Actual result:**
Sometimes your location is displayed, sometimes you timeout. 

**Expected result:**
Always find location and relatively same performance as 0.21.18

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.657
V8 | 6.5.254.31
rev | 5237bae
Muon | 4.9.1
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.146

**Reproducible on current live release:**
No

### Additional Information
Reproduced by @kjozwiak on MacOS and Windows. Also @kjozwiak got this error:
util.js:230 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
CB.j @ util.js:230
(anonymous) @ js?sensor=false:142
(anonymous) @ js?sensor=false:62
(anonymous) @ js?sensor=false:60
(anonymous) @ js?sensor=false:62
(anonymous) @ js?sensor=false:120
(anonymous) @ js?sensor=false:60
(anonymous) @ js?sensor=false:120
(anonymous) @ js?sensor=false:60
(anonymous) @ js?sensor=false:120
(anonymous) @ js?sensor=false:60
(anonymous) @ js?sensor=false:120
Zd @ js?sensor=false:62
Yd.ua @ js?sensor=false:120
(anonymous) @ common.js:1
util.js:230 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

**Comment by kjozwiak** [comment]
Using https://browserleaks.com/geo, I often get `(3) TIMEOUT Timeout expired` when attempting to refresh the website using `0.21.657`. Sometime it takes me 10 retries to finally get my location. Other times, I have to close/re-open the tab and the location loads pretty quickly.

Trying the same thing with `0.21.18`, the location is retrieved pretty quickly every single time. Definitely seems like the performance/UX has degraded in `0.21.657` when it comes to retrieving geolocations.

**Comment by bridiver** [comment]
this appears to be an upstream bug. I see the same behavior in Chrome 65

**Comment by kjozwiak** [comment]
> this appears to be an upstream bug. I see the same behavior in Chrome 65

Confirmed as well. Seeing the same thing while using `Chrome 65.0.3325.162` `5d04e9e9c8ce31bee0923a8c326a7e9e19c492a3-refs/branch-heads/3325@{#695}` on macOS.

**Comment by bsclifton** [comment]
Removing the milestone for the time being- I'll push it to 0.22.x so we can recheck

**Comment by bsclifton** [comment]
This appears to be resolved now 🎉

**Comment by kjozwiak** [comment]
> This appears to be resolved now 🎉

Awesome, much better now! Went through the STR using `0.23.72` c3b1cac002d807409d8438dc72688d9ae553cea5 and couldn't reproduce the original issue. 👍
