### ISSUE TITLE
deny geolocation permission in tor mode

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13447]
https://github.com/brave/muon/issues/518#issuecomment-373186135

test plan:
go to https://browserleaks.com/geo in a tor tab
you should not see a prompt asking to access your location
the tab should show "PERMISSION DENIED - user denied geolocation"

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by kjozwiak** [comment]
@srirambv @btlechowski @GeetaSarvadnya we'll need to retest these with newer builds.

**Comment by kjozwiak** [comment]
Verified on `macOS 10.13.4 x64` using the following build:

* `0.23.12` 88f6f0767c05ba5c4793ec2430a5cd742092fa6d 
* muon: `7.1.1`
* libchromiumcontent: `67.0.3396.87`
