### ISSUE TITLE
Reports of lags while typing into text fields

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#13454]
See convo starting in https://bravesoftware.slack.com/archives/C0YL5KMA8/p1521051553000340.

Brave v0.21.657
SHA 5237bae2be5bd7d2b1ced36f2979baaf72fc1dc0

STR tried were:

**First method**
1. Log into Facebook
2. Start typing a message
3. Check for typing lags

**result:** (unable to reproduce)

**Second method**
1. Open a GH issue
2. Start typing issue's title
3. Check for typing lags

**result:** (reproduced)

Tests made were:

`REDUCER_TIME_LOG_THRESHOLD=5`:

```
1521126880549,app-set-state,243.243061
1521126892297,app-on-promotion-get,881.404701
```

Main process profile:

<img width="955" alt="screen shot 2018-03-15 at 12 53 11 pm" src="https://user-images.githubusercontent.com/4672033/37474785-f6fef9cc-284f-11e8-8280-c611655fd366.png">

Window renderer profile:

<img width="700" alt="screen shot 2018-03-15 at 12 56 05 pm" src="https://user-images.githubusercontent.com/4672033/37474936-48f237b2-2850-11e8-8ae6-f05eb5ac7101.png">

As of this test, all of the profiled methods shows a regular tree and no performance gaps were found.

Testing Chrome `65.0.3325.162` using the second method has shown a similar lag while typing. Given this I'm labeling this issue as `upstream`.

**Comment by cezaraugusto** [comment]
@darkdh also reported that this is a bug as of C64 so known bug just not fixed in C65 which is the version tested in this profile.

**Comment by bbondy** [comment]
I suspect that what you see with Chrome doesn't match this because for my wife for example when there is typing sometimes it's several seconds until the typing shows up. I think with Chrome's user base it's impossible for that to be that widespread across more than 1 chromium version.  @NejcZdovc can you confirm if you see what you experienced with Brave with Chrome?

**Comment by bsclifton** [comment]
Able to reproduce for GitHub issue on Chrome 65 and Brave w/ C65.  Lag is only 1 or 2 seconds at most though.  Unable to repro on Facebook messenger

As @cezaraugusto notes, it only happens on `text` input fields (not `textarea`). Trying to get more information
