### ISSUE TITLE
Brave is refreshing webpage automatically

### ISSUE THREAD

**Issue by ploughpuff** [brave/browser-laptop#13453]
### Description
Brave appears to be stuck in auto refresh loop with a particular web page.  The same web page behaves as expected in Chrome.

### Steps to Reproduce
  1. Start Brave and go to https://shop.ee.co.uk/broadband
  2. Enter text into POSTCODE field

**Actual result:**
1. Page appears to automatically refresh every ~7 seconds
2. Any enter text is lost

**Expected result:**
1. Page not auto refresh
2. Enter text is retained

**Reproduces how often:**
100% repeatable

### Brave Version

**about:brave info:**
 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**
unknown

### Additional Information
Not reproducible in Chrome or IE.

**Comment by Tomatoshadow2** [comment]
Can also confirm this occurs on Mac OS as well.
 
Brave: 0.21.658 
V8: 6.5.254.36 
rev: ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f 
Muon: 4.9.2 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by vinicentus** [comment]
Confirmed on Windows x64, brave 0.21.18. Seems to be caused bby the error "Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://broadband.ee.co.uk/line-checker?origin=shop.ee.co.uk:19:9
(anonymous) @ line-checker?origin=shop.ee.co.uk:19" as seen in developer tools. When allowing all cookies the problem is gone.

**Comment by bsclifton** [comment]
Verified you can work-around the issue by picking "Allow all cookies" for that site 😄

**Comment by bsclifton** [comment]
Not able to reproduce with brave-core (either issue is fixed or site has been fixed)
