### ISSUE TITLE
Ubuntu 14.04: Youtube videos does not have any sound

### ISSUE THREAD

**Issue by lekanovic** [brave/browser-laptop#13452]
### Steps to Reproduce

  1. open brave browser
  2. go to youtube
  3. play video

**Actual result:**

**Expected result:**
Sound

**Reproduces how often:**

### Brave Version

Name | Version
-- | --
Brave | 0.21.18
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 3.13.0-53-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**about:brave info:**

**Reproducible on current live release:**

**Comment by btlechowski** [comment]
Thank you for reporting the issue.

I could not reproduce the issue on Ubuntu 17.10, Brave v0.21.18. The sound is played on youtube.

Is the sound played in other browsers?

**Comment by lekanovic** [comment]
Yes when I use chrome or firefox the sound does plays

**Comment by Tvax** [comment]
I am using Ubuntu 17.10 and I'm experiencing the same issue.
I tried installing it from source, via snap and via apt and I still can't hear a damn thing :)

**Comment by lekanovic** [comment]
Yeah this has been an issue for me for a long time, not sure if the problem is tied to a specific sound HW

**Comment by Tvax** [comment]
That kind of issue makes the browser useless
