### ISSUE TITLE
Create an option to prevent infinite alert dialogs

### ISSUE THREAD

**Issue by vartan** [brave/browser-laptop#1345]
Brave doesn't have an option to prevent alert dialogs from infinitely holding the window hostage, requiring a force-quit to get out.
<img width="536" alt="messages image 2739584247" src="https://cloud.githubusercontent.com/assets/3300248/14471646/611031f8-00a4-11e6-9e7b-e724a9ff761d.png">

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/3794, which has more detail
