### ISSUE TITLE
fix the order and alignment of the alert bar buttons

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#13464]
they should all use the same order and be aligned properly. 

![image](https://user-images.githubusercontent.com/13509546/37495957-1a28ed96-286d-11e8-82a1-0c31237f1c1a.png)

**Comment by jonathansampson** [comment]
Related to https://github.com/brave/browser-laptop/issues/8956

**Comment by riastradh-brave** [comment]
![allowdeny](https://user-images.githubusercontent.com/34034191/39894735-6005a506-5497-11e8-88e6-7cdbbbf72f86.png)

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/make-allow-deny-buttons-always-be-at-the-same-place/27327/2 regarding alignment of allow/deny buttons

**Comment by flamsmark** [comment]
Not going to fix this in Muon IMO.
