### ISSUE TITLE
change ledger contribution period

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13462]
currently the delayTime is a random time in the range between 1 and 10 minutes to avoid correlating ledger contribution votes using timing. https://github.com/brave/browser-laptop/blob/master/app/browser/api/ledger.js#L2356

this interval range was set back when we had approximately 0 ledger users and thus was somewhat arbitrary. 

it affects UX because users expect their contributions to settle within a reasonable time frame. currently the delay is quite noticeable.

here is a proposal to reduce the delayTime without affecting privacy (hopefully):

1. instead of settling N*30 days after their wallet is created, all users will settle on the same day; let's say this is the 15th of each month.
2. for users whose brave browser is online and able to settle on the 15th of the month, they will settle with delayTime set to a random time in the interval [1s, 5s]
3. for users who are unable to settle on the 15th, they default to the current behavior (settle with random time in the interval [1m, 10m])

cc @NejcZdovc

**Comment by NejcZdovc** [comment]
cc @mrose17 @davidtemkin for confirmation

**Comment by mrose17** [comment]
The same day? Please no. No, no, no. This does not scale.

Here's an alternative, change 1m..10m to 10s..1m

**Comment by diracdeltas** [comment]
we discussed this with @davidtemkin and agreed this would depend on better ledger scaling

**Comment by diracdeltas** [comment]
we need to do the math given the number of currently funded ledger wallets, but `10s..1m` over a 30day interval might be a non-starter because it would make time-based vote correlation possible. 

let's say there's 10k active, funded wallets (this is an arbitrary estimate; i don't think we can post the real number on a public github issue). if their settlement times were evenly distributed over a 30day interval, one wallet would settle approximately every 4.32 minutes. 

it seems to me that if you fuzzed 1 settlement per 4.32 minutes over the course of only a minute, it would be fairly easy to correlate votes to the same settlement.

**Comment by diracdeltas** [comment]
@mrose17 gave me the actual number of funded wallets. assuming they reconcile in a uniform distribution over 30 days (probably not realistic given UGP promo, etc.) i think [10s, 4m] would be an appropriate range. 

the smaller the reconciliation window, the shorter the delayTime can be, in general.

**Comment by NejcZdovc** [comment]
@diracdeltas can we for this issue just reduce delay time and we create another issue for items in the first comment?

**Comment by mrose17** [comment]
@diracdeltas said: @mrose17 gave me the actual number of funded wallets. assuming they reconcile in a uniform distribution over 30 days (probably not realistic given UGP promo, etc.) i think [10s, 4m] would be an appropriate range.

the smaller the reconciliation window, the shorter the delayTime can be, in general.

**Comment by diracdeltas** [comment]
^ specifically that is what my comment that @mrose17 deleted said (in case anyone is wondering)

**Comment by diracdeltas** [comment]
@NejcZdovc sure, please create the issues as needed
