### ISSUE TITLE
brave shield appears greyed out in normal tabs when disabling in PB

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13467]
### Description

When disabling the Brave shield in PB on a particular website, the shield will appear greyed out when visiting the same website in a normal tab. This gives the user the illusion that the shield is disabled but is technically still enabled and keeping them safe.

### Steps to Reproduce

  1. visit zerohedge.com in PB
  2. disable the brave shield and close the PB tab
  3. visit zerohedge.com in a regular tab

You'll notice that the Brave shield is greyed out even though it's still enabled/active.

**Actual result:**

<img width="569" alt="screen shot 2018-03-15 at 8 35 26 pm" src="https://user-images.githubusercontent.com/2602313/37497712-7010a80c-2890-11e8-8acb-236dcd54dfc9.png">

![shieldscolour](https://user-images.githubusercontent.com/2602313/37499380-c46c37e6-2899-11e8-930b-db1556060572.gif)

**Expected result:**

Brave shield should appear `Orange` rather than being greyed out.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.21.658 
> V8: 6.5.254.36 
> rev: ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f
> libchromiumcontent: 65.0.3325.162
> Muon: 4.9.2 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently reproducible under `0.21.18` 580be78 which is the current release.

### Additional Information

* macOS 10.13.3 x64 - Reproducible
* Win 10 x64 - Reproducible
* Ubuntu 17.10 x64 - Reproducible

**Comment by flamsmark** [comment]
If this is a case of the feature looking off when it really is on, is it a security issue or just a UX issue with Shields?

**Comment by kjozwiak** [comment]
Ya, you're probably right. It's more of a UX/UI issue. Shields are still working as expected in this instance.

**Comment by kjozwiak** [comment]
@diracdeltas are we landing this in https://github.com/brave/browser-laptop/milestone/108? If so, can we move this issue into that milestone as well?

**Comment by diracdeltas** [comment]
@kjozwiak good catch, i moved it
