### ISSUE TITLE
swipe navigation stops working intermittently when brave is refocused

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13468]
### Description

Sometimes swipe navigation stops working when refocusing on Brave. Once you click on the page that's currently opened in the active tab, swipe navigation will work as expected.

### Steps to Reproduce

  1. launch any 0.20.x versions of brave
  2. visit brave.com and click on Jobs -> About -> Blog
  3. using the trackpad, swipe backwards to navigate back to the main page
  4. switch focus on another application like Slack or another browser that you have opened
  5. refocus on brave by clicking on it and attempt to use swipe navigation

**Actual result:**

When returning focus back on Brave, swipe navigation stops working until the user clicks on the page that's currently opened in the active tab.

Example: https://drive.google.com/file/d/1L7R07inOhChU1oWK02y67f_rpgLAVVcI/view?usp=sharing

**Expected result:**

Swipe navigation should work as soon as the user refocuses on brave.

**Reproduces how often:**

It takes a few attempts but it shouldn't be that hard to eventually reproduce using the above STR. @LaurenWags has also reproduced this a few times on her macOS machine.

### Brave Version

**about:brave info:**

> Brave: 0.21.658 
> V8: 6.5.254.36 
> rev: ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f
> libchromiumcontent: 65.0.3325.162
> Muon: 4.9.2 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently also reproducible under `0.21.18` 580be78 which is the latest released build.

### Additional Information

CCing @darkdh, @LaurenWags and @bsclifton

**Comment by LaurenWags** [comment]
Similar report from community: https://community.brave.com/t/mac-os-back-two-finger-swipe-gesture-rarely-works/28210

**Comment by bsclifton** [comment]
Likely fixed with brave-core; definitely something we won't be addressing with browser-laptop
