### ISSUE TITLE
ledger vote "cost" should be fixed in USD, not BAT

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13463]
cc @NejcZdovc

**Comment by mrose17** [comment]
i'm not sure what the "ask" is here. if i look at the current contribution surveyor:

   ... {"fee":{"USD":5},"votes":50,"altcurrency":"BAT","probi":"34396087616888563802"} ...

which says 5USD equivalent of BAT (34.396087616888563802 at the then exchange rate) gets 50 votes.

is that the "ask". if so, done. if not, then what is the "ask".

**Comment by diracdeltas** [comment]
@mrose17 so @NejcZdovc asked me to open this issue; he can clarify because i don't really know

**Comment by mrose17** [comment]
@diracdeltas - thanks. i'll wait for @NejcZdovc to brief me on it.
