### ISSUE TITLE
Windows 10, Pin icon

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#1347]
When I pin Brave on the task bar and open it, it open another icon.... 
![well](https://cloud.githubusercontent.com/assets/17557010/14476996/8004c0c8-00e1-11e6-8ea9-71904cb12819.png)

**Comment by TheFallenOneGOTH** [comment]
Confirmed for Windows 10 Version 1511 (OS Build 10586.164)

**Comment by rooflack** [comment]
Same here with Windows 10.0.10240 Professional and Brave 0.9.1.

**Comment by rooflack** [comment]
Seems to be fixed in 0.9.2 with Windows 10.0.10586.
I don't know which upgrade fixed it, as Windows and Brave both got updated around the same time on my computer... but according to @TheFallenOneGOTH 's comment, I assume this is related to Brave 0.9.2.

**Comment by luixxiul** [comment]
Closing as this has been fixed.
