### ISSUE TITLE
brave doesn't check URL protocol and requests external application permissions

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13471]
### Test plan
See https://github.com/brave/browser-laptop/pull/13475

### Description

Brave will requests for `external application` permissions when a URL with an invalid protocol is used. We shouldn't be asking for `external application` permissions when an invalid protocol is being used.

### Steps to Reproduce

  1. launch brave and load reddit.com in a new tab
  2. within the same tab, type in abc://google.com and press 'enter'
  3. reddit.com will request for `external application` permissions

**Actual result:**

![protocalcheck](https://user-images.githubusercontent.com/2602313/37505380-fe4f035a-28ba-11e8-9df1-a6d0e273c4ef.gif)

<img width="1557" alt="screen shot 2018-03-16 at 1 12 14 am" src="https://user-images.githubusercontent.com/2602313/37505342-bcf0af58-28ba-11e8-93b7-cd6af2ed5cd3.png">

<img width="1551" alt="screen shot 2018-03-16 at 1 11 49 am" src="https://user-images.githubusercontent.com/2602313/37505344-be4c83f4-28ba-11e8-9e6d-a3effece9fab.png">

**Expected result:**

Brave shouldn't be asking for external application permissions when loading a URL with an invalid protocol.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.21.658 
> V8: 6.5.254.36 
> rev: ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f
> libchromiumcontent: 65.0.3325.162
> Muon: 4.9.2 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently also reproducible under 0.21.18 580be78 which is the latest released build.

### Additional Information

CC'ing @diracdeltas @flamsmark for proper triage.

**Comment by diracdeltas** [comment]
It might be hard to detect all valid external protocols since people are constantly creating new ones. However we should probably show the origin of the external site in the URL bar instead of the origin of the page that the user is currently on.

**Comment by kjozwiak** [comment]
@LaurenWags @btlechowski easiest way to get a local webserver going so you can go through the test plan that was added is using `python -m SimpleHTTPServer`.

**Comment by kjozwiak** [comment]
Verified on `Ubuntu 17.10 x64` using the following build:
* `0.22.8` 3ae27f2cf188b50ff64877a0968361d625fb84ca
* libchromiumcontent: `65.0.3325.181`
* muon: `5.1.2`
