### ISSUE TITLE
Refactor needed because of deprecation of `did-get-response-details`

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13472]
## Test plan
1. Launch Brave and enable payments
2. Open 3 new tabs
3. Switch between the 3 tabs and load a unique site in each
4. Switch between the tabs and wait a few seconds, to build a history
5. Visit the payments screen. Visit time should be recorded properly

## Description
When doing Chromium 65 upgrade, the emitting of `did-get-response-details` was removed with https://github.com/brave/muon/commit/00d729f2585964027deff728a1ef3b32f7f21d65

Unless replacement code is found, this code will not execute

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/13461

**Comment by srirambv** [comment]
Verified visit time using stop watch to match the visited time and confirmed

**Comment by LaurenWags** [comment]
Did the same as https://github.com/brave/browser-laptop/issues/13472#issuecomment-373714215 on MacOS, looks good.
