### ISSUE TITLE
expanding/making the "Save Download As.." prompt smaller doesn't work correctly

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13470]
### Description

Expanding/making the `Save Download As..` modal prompt smaller doesn't work under macOS.

### Steps to Reproduce

  1. visit https://www.thinkbroadband.com/download under macOS
  2. download any of the files and you'll receive the `Save Download As` modal prompt
  3. attempt to expand/make the `Save Download As` modal prompt smaller

**Actual result:**

<img width="844" alt="screen shot 2018-03-16 at 12 26 06 am" src="https://user-images.githubusercontent.com/2602313/37504363-3341d314-28b4-11e8-94a0-d2d73a3ed25e.png">

![downloadprompt](https://user-images.githubusercontent.com/2602313/37504304-cd4d3756-28b3-11e8-93ea-e070728f1be2.gif)

**Expected result:**

Expanding/making the `Save Download As` modal prompt smaller should work as expected without any UI artifacts.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> 
> Brave: 0.21.658 
> V8: 6.5.254.36 
> rev: ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f
> libchromiumcontent: 65.0.3325.162
> Muon: 4.9.2 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently reproducible using `0.21.18` 580be78 which is the latest released version.

**Comment by kjozwiak** [comment]
@darkdh, @bsclifton mentioned that some of the work that you've been doing in 0.22 might fix this particular issue. Could you please triage this if that's not the case? Thanks!

**Comment by darkdh** [comment]
fixed with muon 5.0.0 and above
![untitled](https://user-images.githubusercontent.com/11330831/37506392-dabd4ad2-28a6-11e8-9dfe-a4fd0e2873a8.gif)

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
