### ISSUE TITLE
When typing in url and going to address, switches to tab instead

### ISSUE THREAD

**Issue by lbellows** [brave/browser-laptop#13486]
### Description
When you have a google tab open and then try to go to google.com it switches to the tab rather than letting you search again.

### Steps to Reproduce

  1. Go to google.com
  2. Search for something
  3. Open new tab, type google.com, enter

Note: This was after a session restore (saved tabs) and an update which seems to sometimes leads to strange behavior

**Actual result:**
Switches to existing google.com tab

**Expected result:**
Go to google.com in current tab

**Reproduces how often:**
All the time

### Brave Version
Name | Version
-- | --
Brave | 0.21.19
V8 | 6.5.254.36
rev | f359e6e
Muon | 4.9.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
+1 from @tommycarstensen via https://github.com/brave/browser-laptop/issues/14007
> It is really annoying that Brave switches to an already open tab, when I type in the URL and that URL is open in another tab. Sometimes the user wants to open two tabs. I think you should make it possible to disable this "feature" and not have it enabled by default. Thanks!
