### ISSUE TITLE
Install failed on linux 3013.0-85-generic

### ISSUE THREAD

**Issue by BigMcLargeHuge** [brave/browser-laptop#1348]
Hi All,

I'm attempting to install the beta-test level of the brave browser but am running into the following error:

>239296 warn optional Skipping failed optional dependency /electron-builder/appdmg:
>239297 warn notsup Not compatible with your operating system or architecture: appdmg@0.3.6
>239298 warn optional Skipping failed optional dependency /chokidar/fsevents:
>239299 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.11
239300 verbose stack Error: keytar@3.0.0 install: node-gyp rebuild
239300 verbose stack Exit status 1
239300 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
239300 verbose stack     at emitTwo (events.js:100:13)
239300 verbose stack     at EventEmitter.emit (events.js:185:7)
239300 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
239300 verbose stack     at emitTwo (events.js:100:13)
239300 verbose stack     at ChildProcess.emit (events.js:185:7)
239300 verbose stack     at maybeClose (internal/child_process.js:850:16)
239300 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
239301 verbose pkgid keytar@3.0.0
239302 verbose cwd /home/sam/github/browser-laptop
239303 error Linux 3.13.0-85-generic
239304 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
239305 error node v5.10.1
239306 error npm  v3.8.3
239307 error code ELIFECYCLE
239308 error keytar@3.0.0 install: node-gyp rebuild
239308 error Exit status 1
239309 error Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
239309 error Make sure you have the latest version of node.js and npm installed.
239309 error If you do, this is most likely a problem with the keytar package,
239309 error not with npm itself.
239309 error Tell the author that this fails on your system:
239309 error     node-gyp rebuild
239309 error You can get information on how to open an issue for this project with:
239309 error     npm bugs keytar
239309 error Or if that isn't available, you can get their info via:
239309 error     npm owner ls keytar
239309 error There is likely additional logging output above.

I'm not very familiar with nodejs so it's entirely possible that it's just something basic that I'm missing.  Unfortunately that also means that I don't have any interesting guesses as to what might be happening here.

**Comment by luixxiul** [comment]
Fixed with #1682.

**Comment by luixxiul** [comment]
If it does not fix the issue let us know here.
