### ISSUE TITLE
trackpad zoom on tradingview.com zooms whole page not just chart

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13481]
### Description
In 0.21.18 if you used trackpad to zoom in/out on the chart on tradingview.com, only the chart was zoomed (as expected). If you do this on the same site with 0.21.19, the entire page zooms which is not the intent.

### Steps to Reproduce

  1. Open tradingview.com and open the chart.
  2. Hover over the chart
  3. Use two fingers to zoom the chart

**Actual result:**
Entire page is zoomed
![02119zoomtradingview](https://user-images.githubusercontent.com/28145373/37542749-a459f7c6-2935-11e8-846d-d4062271df32.gif)

**Expected result:**
Only the chart should be zoomed
![02118zoomtradingview](https://user-images.githubusercontent.com/28145373/37542758-aac088fa-2935-11e8-8270-5366525fb9df.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.21.19
V8 | 6.5.254.36
rev | f359e6e
Muon | 4.9.2
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
reproduces on 0.21.19 but not 0.21.18

### Additional Information
Reported via community: https://community.brave.com/t/page-zoom-on-mac-conflict-with-macos/17999

**Comment by bridiver** [comment]
closed by https://github.com/brave/muon/commit/ebac9c9f7b64e50547afa3314ae9ff78ee741d2e

**Comment by srirambv** [comment]
Still seeing the issue on Windows. 
![13481](https://user-images.githubusercontent.com/17010094/37586561-9f576a9e-2b54-11e8-8163-b82c5b41e45c.gif)
