### ISSUE TITLE
tabs lost/session not saved 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13483]
### Description
While investigating an issue (https://github.com/brave/browser-laptop/issues/13481) on released version 0.21.19, I lost my tabs on restart. This does not happen consistently.

Note, I had seen this while testing the test plan from https://github.com/brave/browser-laptop/issues/11576  (and using `BRAVE_SESSION_SAVE_INTERVAL=1`) I found that usually my tabs were lost on restart. However, with some discussions over slack we thought this was due to the short interval, so I switched the `BRAVE_SESSION_SAVE_INTERVAL` to be 10 and could not reproduce the issue.  

### Steps to Reproduce

  1. Have a few tabs open
  2. I was investigating https://github.com/brave/browser-laptop/issues/13481 at the time so I has about:brave and tradingview.com open.
  3. I closed Brave

**Actual result:**
All open tabs gone.

**Expected result:**
No tab loss.

**Reproduces how often:**
Difficult, only happened once.

### Brave Version

**about:brave info:**
Brave | 0.21.19
V8 | 6.5.254.36
rev | f359e6e
Muon | 4.9.2
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
Only experienced on 0.21.19 so far.

### Additional Information
Issue originally reported with https://github.com/brave/browser-laptop/issues/11576

These are the steps this issue was originally found with and we determined that the short interval was the culprit:
Launch brave with `BRAVE_SESSION_SAVE_INTERVAL=1`
Have a several (I had 4) tabs open with different sites.
Close/relaunch brave with `BRAVE_SESSION_SAVE_INTERVAL=1` to verify session state was saved.
Click on a different tab to make it the active one.
Once tab has loaded, close/relaunch brave with `BRAVE_SESSION_SAVE_INTERVAL=1` --> session state is not saved, your tabs are lost.
*note, sometimes my tabs are saved, sometimes they are not

**Comment by LaurenWags** [comment]
+1 from https://github.com/brave/browser-laptop/issues/11576#issuecomment-373941205

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/11576 since it was not fixed
