### ISSUE TITLE
Don't package extension resources in Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13485]
### Description
While Brave doesn't package extension data, it does package some extension icons. These are shown within the in-browser list of available extensions. These icons, however, should not be packaged with the browser. Instead, they should be downloaded at a later time.

**Actual result:**
Extension icons are shipped with Brave.

**Expected result:**
Extension icons are downloaded by Brave during first run.

### Brave Version
0.21.19

**about:brave info:**
``` 
Brave: 0.21.19 
V8: 6.5.254.36 
rev: f359e6ed2616360456945bff01bac707895fd651 
Muon: 4.9.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

**Reproducible on current live release:**
Yes

### Additional Information
See https://github.com/brave/browser-laptop/blob/49523fafd9103c3ba378ac7bf4795135387880d4/app/renderer/lib/extensionsUtil.js#L32-L90

Icons are stored here: https://github.com/brave/browser-laptop/tree/49523fafd9103c3ba378ac7bf4795135387880d4/app/extensions/brave/img/extensions

**Comment by flamsmark** [comment]
Where should icons be fetched from?

**Comment by jonathansampson** [comment]
@flamsmark Great question; it is my understanding that we can download from just about anywhere (even a cache of our own creation). But there is, if I'm not mistaken, a conflict in shipping these with the browser bits.

**Comment by flamsmark** [comment]
I think there are some privacy implications to either fetching them from the CWS or from a cache of our own. Either approach makes a new ping we need to handle safely.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/825
