### ISSUE TITLE
Taco Bell favicon flashes on mouseover

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13487]
### Description
Introduced with #12565. Haven't been able to reproduce on any other sites apart from tacobell.com.
Thanks for the find @bsclifton 

### Steps to Reproduce

  1. Have a tab with tacobell.com's favicon
  2. Mouse over tab

**Actual result:**

  3. Icon flashes on and off

**Expected result:**
Icon remains visible

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

No

**Comment by kjozwiak** [comment]
Also noticed this happening on https://badssl.com/ when QAing `0.22.13`.. Example:

![icoflash](https://user-images.githubusercontent.com/2602313/38156245-8109e342-344a-11e8-8eaa-80778fb02f57.gif)

**Comment by jayyyin** [comment]
if it's ok I'd like to look into this...

**Comment by petemill** [comment]
@jayyyin go for it - please! Would be great to try and reproduce on something like codepen.io in order to experiment with fixing in a small reproducible scenario. It's possible that the gradient is interfering with certain types of favicon image encoding, as you've found in #13746. Forcing the favicon to paint on a new layer may help, but I think I tried that in initial investigation and promptly gave up for the time being!

**Comment by jayyyin** [comment]
@petemill yah, I found basically disabling the gradient fixes the issue, but I'm pretty sure that's not the way to go, how would I go about trying to paint it on a separate layer?

**Comment by jayyyin** [comment]
note the Favicon also "flashes" when you initially move the mouse into the tab area

**Comment by jayyyin** [comment]
This issue, seems to be related https://bugs.chromium.org/p/chromium/issues/detail?id=387146

**Comment by petemill** [comment]
@jayyyin actually I don't think that's related. This looks to me a css display / painting issue. The chromium issue you linked to is literally Chromium changing the favicon when the Url changes via `pushState`.

**Comment by jayyyin** [comment]
@petemill yah I found another lead, the icon isn't cached correctly and is being redownloaded constantly, you can see using the networks tab that it is for some reason

**Comment by jayyyin** [comment]
@petemill, ok so from what I've learned making a new layer should fix the issue, since the icon shouldn't be getting invalidated anymore along with the CSS change for the gradient, so thus the no-cache issue won't affect it, but this should be noted for future reasons.

**Comment by jayyyin** [comment]
>>>TO sum up what I've found so far heres a blog post http://jyopensource.blogspot.ca/2018/04/brave-laptop-dev-interesting-issue-part.html
