### ISSUE TITLE
reCAPTCHA not working with site isolation enabled

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#13496]
### Description
Can not solve reCAPTCHA because selection box not clickable. Happened after updated to 0.21.19 and 0.21.20 with site isolation enabled.
Previously working fine on 0.21.18 with site isolation enabled.

### Steps to Reproduce

  1. Visit site that have reCAPTCHA. I reproduce on `Uphold.com` login page.
  2. Try to solve reCAPTCHA.
  3. Box not clickable. The button also not responsive.

**Actual result:**
![recaptcha-1](https://user-images.githubusercontent.com/25360853/37559773-3c7f7eb2-2a5e-11e8-8e3a-1be29a3bdd21.gif)

**Expected result:**
It should work with site isolation enabled like in 0.21.18

Record with site isolation disabled
![recaptcha-2](https://user-images.githubusercontent.com/25360853/37559790-7b3f9588-2a5e-11e8-9899-e3e4e6fea725.gif)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.21.20 
V8: 6.5.254.36 
rev: 6b04acd1a2d1c8edf4c228bb7ffe9fd3a68b0116 
Muon: 4.9.3 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**
Not sure. Since latest release is 0.21.18 but I got notification update to 0.21.19 and 0.21.20

### Additional Information
cc @bsclifton

**Comment by eljuno** [comment]
++ from community https://community.brave.com/t/recaptcha-stopped-working-completely-since-last-update/18033?u=eljuno and https://community.brave.com/t/strict-site-isolation-captcha-bug/18064?u=eljuno

**Comment by bsclifton** [comment]
Problem likely introduced by upgrading to Chromium 65

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/cant-interact-with-captcha/18467

**Comment by eljuno** [comment]
Still an issue with the latest stable version

>Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by srirambv** [comment]
+1 from egferro  via #14509

**Comment by mrphs** [comment]
> +1 from egferro via #14509

Similarly, I can't get that box to work. This becomes a pain if Tor mode is enabled as it constantly hits CloudFlare captchas.

**Comment by srirambv** [comment]
@mrphs Tor tabs hitting CloudFlare captcha is different from the original issue. Tor tabs captcha is expected . Does it fail on Tor tabs with or without site isolation enabled?

**Comment by mrphs** [comment]
@srirambv I'm aware. I'm just saying this becomes more of a pain when you use Tor because you see captchas more often. And to answer your question it fails _with_ site isolation enabled, hence commenting on this ticket :)

**Comment by lembitk** [comment]
+1

> Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Comment by bsclifton** [comment]
Issues with strict site isolation are fixed with brave-core 😄 

You can download the developer channel release here:
https://brave.com/download-dev
