### ISSUE TITLE
Mouse cursor does not change over valid URL - only arrow - Linuxmint 18.3 Mate

### ISSUE THREAD

**Issue by pongraczi** [brave/browser-laptop#13498]
### Description, actual result
When I move the mouse cursor over a valid URL, it should change to a hand icon. Instead it is a constant arrow as you can see below.

![brave_cursor_does_not_change_over_url](https://user-images.githubusercontent.com/5891983/37594494-9218b6dc-2b75-11e8-8fa1-c70db282cdf1.gif)

### Steps to Reproduce

  1. Hover the mouse cursor over a valid link on a page.
  2. For me, it does not change.

**Expected result:**
Should be a hand icon imitating a click.

**Reproduces how often:**
It seems, this bug appeared in the latest release and it is 100%

### Brave Version
```
Brave: 0.21.19 
V8: 6.5.254.36 
rev: f359e6ed2616360456945bff01bac707895fd651 
Muon: 4.9.2 
OS Release: 4.13.0-37-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

### Additional Information
Linuxmint 18.3 MATE

**Comment by srirambv** [comment]
Do you mind checking it on 0.21.20 build?

**Comment by pongraczi** [comment]
Thanks, it seems the 0.21.20 is working as expected.
