### ISSUE TITLE
Translations broken on beta channel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13499]
### Description
Translations broken on beta channel

### Steps to Reproduce

  1. Upgrade to 0.22.5
  2. Open preferences page, none of the text is translated but instead shows the variable names
  3.

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/37597026-03b0120e-2b76-11e8-9416-c7e8babc7521.png)

**Expected result:**
Text should be translated

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.5
-- | --
V8 | 6.4.388.45
rev | 94d33ff
Muon | 5.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.167

**Reproducible on current live release:**
No

### Additional Information
cc: @bsclifton

**Comment by bsclifton** [comment]
Commit that broke this: https://github.com/brave/browser-laptop/commit/e62e1ecf0e2cef0aaa372b2a2f0f7fa53f9c4f53

**Comment by eljuno** [comment]
Also happened on Brave 0.21.21

**Comment by bsclifton** [comment]
Moving to 0.22.x because we reverted https://github.com/brave/browser-laptop/pull/13115 from 0.21.x

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
