### ISSUE TITLE
use the latest bat-* package versions

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13509]
bat-client@2.1.2
bat-publisher@2.0.16

**Comment by mrose17** [comment]
with this in place, also make use of `bat-client::memo`, perhaps like this in ledger.js:

        @@ -2325,10 +2325,23 @@ const run = (state, delayTime) => {
         
           if (data) {
             let weights = []
        +
        +    let map = {}
        +    data.forEach((datum) => {
        +      map[datum.publisherKey] = underscore.extend({
        +        votes: 0
        +      }, underscore.pick(datum, [ 'verified', 'exclude', 'score', 'pinPercentage', 'percentage', 'weight' ]))
        +    })
        +
             data.forEach((datum) => {
               weights.push({publisher: datum.publisherKey, weight: datum.weight / 100.0})
             })
        -    winners = synopsis.winners(ballots, weights)
        +    winners = synopsis.winners(ballots, weights) || []
        +
        +    winners.forEach((winner) => {
        +      map[winner].votes++
        +    })
        +    client.memo('run:ballots', underscore.values(map))
           }
         
           if (!winners) winners = []

**Comment by NejcZdovc** [comment]
added `QA/no-qa-needed`
