### ISSUE TITLE
google asking for flash permissions when clicking the adobe test page via search results

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13500]
### Description

Clicking on `https://get.adobe.com/flashplayer/about/` via a Google search result will prompt the user the `Allow https://www.google.ca to run Flash Player?` notification. Google shouldn't be asking for Flash permissions in this case.

### Steps to Reproduce

  1. launch `0.21.20` and enable Flash via `about:preferences#plugins`
  2. using google, search for `flash test`
  3. click on the `https://get.adobe.com/flashplayer/about/` search result

You'll receive a `Allow https://www.google.ca to run Flash Player?`. Clicking on `Allow` or `Deny` doesn't do anything either.

**Actual result:**

![notificationflash](https://user-images.githubusercontent.com/2602313/37607419-5938baee-2b6e-11e8-8b77-d111185d370e.gif)

**Expected result:**

Clicking on the `https://get.adobe.com/flashplayer/about/` search result shouldn't display the Flash permission notification.

**Reproduces how often:**

100% reproducible when using the STR mentioned above.

### Brave Version

**about:brave info:**

* `0.19.147` f1b90a3 - Reproduced
* `0.21.18` f359e6ed2616360456945bff01bac707895fd651 - Reproduced
* `0.21.20` 6b04acd - Reproduced

**Reproducible on current live release:**

Yes, currently reproducible using `0.21.18` f359e6ed2616360456945bff01bac707895fd651 which is the latest release build.

### Additional Information

* Reproduced by @LaurenWags under macOS as well.

**Comment by diracdeltas** [comment]
for reference, this was originally fixed in https://github.com/brave/browser-laptop/commit/4ffcfcbcd13b37d68e0f8255f83cfd3a643dc26d

**Comment by alexwykoff** [comment]
Looks like it's merged.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.80 53a429f
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
