### ISSUE TITLE
saving recovery file doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13510]
### Description

Saving a recovery file via `about:preferences#payments` has stopped working and will display the following error in the terminal:

`[4320:12772:0319/232648.466:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while running tabViewInternal.getTabID: Could not find guest", source: chrome://brave/C:/Users/kamil/AppData/Local/Brave/app-0.21.23/resources/app.asar/app/extensions/brave/index.html (0)`

### Steps to Reproduce

  1. launch `0.21.23` 6f9c4f7 and visit  `about:preferences#payments`
  2. enable payments
  3. once the wallet has been created, click on `Advanced Settings` -> `Backup your wallet`
  4. click on `Save recovery file...` Nothing happens.

**Actual result:**

Clicking on  `Save recovery file...` doesn't do anything.

![recoveryissues](https://user-images.githubusercontent.com/2602313/37634902-ea4b52ac-2bce-11e8-8618-50f02f3a45eb.gif)

**Expected result:**

Clicking on  `Save recovery file...` should prompt the user to save the recovery file.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.21.23 
> rev: 6f9c4f7bfe298317bd5a00b979e28b33f4c769eb 
> Muon: 4.9.3
> libchromiumcontent: 65.0.3325.162
> OS Release: 10.0.16299 
> Update Channel: Release 
> OS Architecture: x64 
> OS Platform: Microsoft Windows 
> Node.js: 7.9.0
> V8: 6.5.254.36 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Nope, couldn't reproduce the issue with `0.21.18` 580be78 which is the current live released build.

### Additional Information

* `0.21.20` 6b04acd - Reproduced
* `0.21.21` 56a3d76 - Reproduced

**Comment by darkdh** [comment]
https://github.com/brave/muon/blob/3fb05f239797bfe7aa8ac13962aba81600c87618/atom/browser/atom_download_manager_delegate.cc#L155
web_contents is null

**Comment by bsclifton** [comment]
Fixed in 0.21.x with https://github.com/brave/browser-laptop/pull/13513

We'll want to retest this on 0.22.x

**Comment by srirambv** [comment]
Save recovery key works. But doesn't show it under downloads or on download bar. 
![13510](https://user-images.githubusercontent.com/17010094/37647473-3cd30362-2c24-11e8-9005-148130e1072e.gif)
