### ISSUE TITLE
Option in Developer Tools Crashes Brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13521]
### Description
Opening Developer Tools -> Sources (tab) -> Overrides (sub-tab) and clicking ‘Select folder for overrides’ crashes Brave.

Reported via community: https://community.brave.com/t/developer-tools-select-folder-for-overrides-crashes-brave/18215

### Steps to Reproduce

  1. Select View > Toggle Developer Tools
  2. Select Sources tab > Overrides sub-tab
  3. Select the 'Select folder for overrides' under the sub-tab.

**Actual result:**
Brave Crashes.

**Expected result:**
Brave should not crash.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.21.23

**Reproducible on current live release:**
No, that option is not available on 0.21.18

### Additional Information
CR65 related? cc @bsclifton 
Reported with Windows, reproduced with MacOS

**Comment by kjozwiak** [comment]
Moved into this into the 0.21 milestone so @bsclifton is made aware. However, this will most likely be triaged out into another milestone/backlog.

**Comment by kjozwiak** [comment]
Moving into 0.22 after speaking with @bsclifton.

**Comment by darkdh** [comment]
will not crash with muon 5.0.0 and above but still need to make it functioning normally.
Currently it behaves same as `Add folder to workspace`

**Comment by kjozwiak** [comment]
Using the above STR, I reproduced the issue using `0.21.24` 19c78a1. Once reproduced, I went through verification with Ubuntu 17.10 x64 using the following build:

* `0.22.7` 8bb7e77
* libchromiumcontent: `65.0.3325.181`
* muon: `5.1.1`

**Comment by bsclifton** [comment]
@kjozwiak it doesn't crash, but fix isn't in place quite yet (will be delivered with Muon 5.1.2). I believe it will just not do anything at the moment

**Comment by darkdh** [comment]
Before muon 5.1.2 the folder will be added to workspace even if you add it in `Overrides`
<img width="369" alt="screen shot 2018-03-22 at 2 47 36 pm" src="https://user-images.githubusercontent.com/11330831/37981406-7b98847c-31a2-11e8-9c1a-888d2db289fc.png">
<img width="348" alt="screen shot 2018-03-27 at 9 40 00 am" src="https://user-images.githubusercontent.com/11330831/37981568-db221138-31a2-11e8-8d4e-1cb80ba4e3fd.png">

After 5.1.2, you can successfully add it to `Overrides`
<img width="359" alt="screen shot 2018-03-27 at 9 38 32 am" src="https://user-images.githubusercontent.com/11330831/37981470-a2b319d2-31a2-11e8-891d-6472dd13158e.png">

**Comment by kjozwiak** [comment]
> @kjozwiak it doesn't crash, but fix isn't in place quite yet (will be delivered with Muon 5.1.2). I believe it will just not do anything at the moment
> 
> Removing `QA/checked-Linux` label so that we can retest when new Muon is available

Thanks @bsclifton, I was going to create a new issue after the triage meeting for Overrides not working correctly. Makes sense on why it wasn't working.

**Comment by btlechowski** [comment]
Verified on Windows 7 x64
* 0.22.8    3ae27f2
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
