### ISSUE TITLE
Default favicon on dark theme color should not have hover color

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13524]
### Description
#12565 introduced new tab styles. I found a regression whereby our default favicon, which is displayed on sites with no favicon of their own, has a different color on hover, when the tab is active and if the tab has a default theme color

### Steps to Reproduce

  1. Visit google.com
  2. Right-click content area and save page as... local file on desktop
  3. Drag local html file to brave
  4. Observe new tab has dark theme color when active

![image](https://user-images.githubusercontent.com/741836/37670269-1ba72770-2c26-11e8-98e1-b2a36751731a.png)

  5. Hover over this active tab

**Actual result:**
Favicon color is different.
![image](https://user-images.githubusercontent.com/741836/37670289-25e03312-2c26-11e8-9797-a34fd3e0fb16.png)

**Expected result:**
Favicon color stays same as when not hovered.

**Reproducible on current live release:**
No

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
