### ISSUE TITLE
Payment to Website owners is too complicated - put meta tag

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13522]
### Description

It is very hard to understand how to payment for website owner is working.
The tokens should make it easy, but not so complicated with Uphold.
Just let people put meta tag on website with address and this it's.

### Steps to Reproduce

Website owners should receive BAT by meta tags
  1. Add to head meta tag with address to receive payments
  2. People will pay to this address

**Actual result:**

Not implemented

**Expected result:**
Implementing technology which will divide revenue to website owner and this project by meta tag

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

not implemented

**Comment by bsclifton** [comment]
cc: @mrose17, @davidtemkin, @mandar-brave

**Comment by mrose17** [comment]
this suggestion is entirely incompatible with the way that BAT is architected or operates. if an approach like this is "interesting", it ought to use a different utility token...
