### ISSUE TITLE
Ledger Recovery file download isn't showing up on about:downloads

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13520]
### Description
Ledger Recovery file download isn't showing up on about:downloads

### Steps to Reproduce

  1. Clean install 0.21.24
  2. Enable payments
  3. Save recovery key, file download isn't shown in about:downloads

**Actual result:**

Ledger Recovery file download isn't showing up on about:downloads

**Expected result:**
Should show the download file in about:downloads

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.24
-- | --
V8 | 6.5.254.36
rev | 19c78a1
Muon | 4.9.3
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
No

**Comment by bsclifton** [comment]
This should be closed as `wontfix` since the behavior was change... but before doing that, let's test and confirm with 0.22.x (the current beta)

I believe this was removed with https://github.com/brave/browser-laptop/pull/13279 which I partially pulled into 0.21.x to fix an issue with Chromium 65

**Comment by alexwykoff** [comment]
Closing wontfix per ^
