### ISSUE TITLE
Payment reconcile doesn't reduce the wallet balance 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13529]
### Description
Payment reconcile doesn't reduce the wallet balance 

### Steps to Reproduce
  1. Clean install 0.21.24
  2. Enable payment and create wallet on production
  3. Add sufficient funds to wallet to match monthly contribution
  4. Visit some sites and ensure its added into ledger table
  5. Change reconcile timestamp in `ledger-state.json`
  6. Launch browser with `LEDGER_NO_FUZZING=true LEDGER_NO_DELAY=true`  to ensure payment goes through
  7. Wait for the transaction successful notification to show up
  8. Balance amount remains as is but payment goes through 

**Actual result:**
Payment reconcile doesn't reduce the wallet balance 

**Expected result:**
Wallet amount should reduce by monthly budget set 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.21.24
-- | --
V8 | 6.5.254.36
rev | 19c78a1
Muon | 4.9.3
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
Maybe

### Additional Information
cc: @bsclifton

**Comment by LaurenWags** [comment]
Same on MacOS using 0.21.24. Account Balance should be 2.5 BAT:
![screen shot 2018-03-20 at 4 52 48 pm](https://user-images.githubusercontent.com/28145373/37682217-425e5fda-2c5f-11e8-9e9b-ae34d999c797.png)

**Comment by srirambv** [comment]
Happens on 0.21.18 as well. Reproduced on all platforms by @LaurenWags @kjozwiak as well

**Comment by bsclifton** [comment]
@mrose17 can you check this out?

**Comment by NejcZdovc** [comment]
@srirambv can you please re-check this one?

**Comment by NejcZdovc** [comment]
@LaurenWags can you please re-check this one?

**Comment by LaurenWags** [comment]
My balance did update after I got the notification that my contribution went through, took about 45 minutes. 

cc @kjozwiak

**Comment by kjozwiak** [comment]
Closing as per above. @NejcZdovc @bsclifton if you disagree, please re-open.
