### ISSUE TITLE
whitelist script signatures

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1353]
I recently went to adops.com and the site was basically unusable because they are on the blocking list. I don't really see any reason why we should be blocking jquery and other scripts that are not ad related. Not sure if a whitelist is the answer, but maybe consider the referrer url (when not in an iframe) because these are 1st-party scripts in this context.

**Comment by diracdeltas** [comment]
this is a bug - TP/AB should not be blocking first party resources in the first place

**Comment by diracdeltas** [comment]
need @bbondy input. i would have expected `adblock.matches(details.url, mapFilterType[details.resourceType], firstPartyUrl.host)` to return false when `details.url` is first-party to `firstPartyUrl.host`. apparently this is not the case. should this be fixed in the ABP module or is it a check we need to add to `app/adBlock.js`?

**Comment by bbondy** [comment]
I thought we already had this check but apparently not.  We should just do an extra check to make sure the `details.url` host is different from the `firstPartyUrl.host` in app/adBlock.js.

**Comment by bbondy** [comment]
re-opening, I think a rule like this will fix: `||adops.com$~third-party`

**Comment by bbondy** [comment]
mostly fixed by the filtering rule committed above, but some things are still getting blocked that shouldn't (logo). I think it's a bug in the ad block library and could be a more generalized problem so blocking on this since the first party filtering change first lands in 0.20.x too.

**Comment by bbondy** [comment]
Never mind, I just tested with combined data file and it's working. I was testing before with custom adblock rule exception which runs  in an independent instance

**Comment by cezaraugusto** [comment]
heads-up I added a basic test plan please add more checks in case mine is incomplete. Thanks
