### ISSUE TITLE
Variable names displayed instead of human friendly strings

### ISSUE THREAD

**Issue by matthewberryman** [brave/browser-laptop#13538]
### Description
Variable names displayed instead of human friendly strings

### Steps to Reproduce
Clean install of Brave beta 0.22.5
OS and langauge settings per additional information below.

**Actual result:**
Variable names instead of human readable strings throughout, including preferences as in screenshot:
<img width="551" alt="screenshot 2018-03-21 11 15 11" src="https://user-images.githubusercontent.com/2288238/37689623-2f2a147c-2cfa-11e8-9783-f22d42be6633.png">

**Expected result:**
Human readable strings.

**Reproduces how often:**
All the time.

### Brave Version
beta 0.22.5

**Reproducible on current live release:**
Present in latest beta 0.22.5.
Not present in latest stable release 0.21.24.

### Additional Information
macOS High Sierra 10.13.3
Brave selectedLanguage: en-GB
System language: en-AU

**Comment by MargarytaChepiga** [comment]
If no one is working on this, I would love to tackle this!

**Comment by NejcZdovc** [comment]
@MargarytaChepiga this was already fixed with https://github.com/brave/browser-laptop/pull/13501, but we just didn't push new beta out yet.

cc @bsclifton
