### ISSUE TITLE
Security risk in information about certificates

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13542]
### Description

The information about certificate, don't show full information for user.

### Steps to Reproduce

  1. Visit for example myetherwallet.com
  2. Check top bar, where the name of website is
  3. Information about certificate is missing

**Actual result:**

Don't show information about certificate

**Expected result:**
Show information

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

yes

### Additional Information

Comparsion between chrome and brave
![screen shot 2018-03-21 at 10 51 18](https://user-images.githubusercontent.com/537310/37703556-5cee285c-2cf6-11e8-9fb8-5b78a7d2bf66.png)

**Comment by srirambv** [comment]
This is available in 0.22.x release. Here's the issue for reference https://github.com/brave/browser-laptop/issues/791
