### ISSUE TITLE
Windows printing issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13546]
### Description
Reports of printing issues in community with 0.21.24:
https://community.brave.com/t/unable-to-print-to-printer-or-pdf-from-brave-ad-of-3-19/18260
https://community.brave.com/t/i-cannot-print-using-the-brave-browser/18305
https://community.brave.com/t/now-i-cant-print-out-from-website/18257

### Steps to Reproduce

From one of the community issues:
Tried printing form site. Nothing happens, nothing in printer queue
Tried printing to pdf. Document name exists but file will not open (FoxIt PDF Printer)
Restarted computer, still unable to print
Used a different browser and printed to printer and to pdf from the same site.
Printing to printer and to pdf worked from different browser.

**Actual result:**
Unable to print.

**Expected result:**
Able to print.

**Reproduces how often:**
Easily for Windows users

### Brave Version

**about:brave info:**
0.21.24

**Reproducible on current live release:**
Yes

### Additional Information
Could not reproduce with MacOS (printing a web page or printing to PDF). @AlexeyBarabash confirmed printing to MS PDF printer did not generate the result file.

**Comment by LaurenWags** [comment]
One user in community with both Mac and Win confirmed this is only occurring on their Win machine.

**Comment by srirambv** [comment]
I tried printing an article using the print option, Acrobat PDF doesn't save, Microsoft print to pdf saves but no file is created
Same for pdf file as well

**Comment by srirambv** [comment]
Same issue on 0.21.18 as well

**Comment by eljuno** [comment]
++ from community https://community.brave.com/t/printing-from-brave-no-longer-works/18181?u=eljuno

**Comment by LaurenWags** [comment]
+1s from community https://community.brave.com/t/beware-if-you-want-to-print-out-something-from-brave-it-didnt-go-print/18421

**Comment by bsclifton** [comment]
Errors seen when running Muon debug build:
```
[1112:5104:0323/101754.908:ERROR:service_manager_connection_impl.cc(309)] Can't create service chrome_printing. No handler found.
[1112:720:0323/101754.908:ERROR:pdf_to_emf_converter.cc(556)] Failed to convert PDF: Connection to PdfToEmfConverterFactory error.
```

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/cannot-print-using-brave/18527?u=eljuno

>  Brave 0.21.24, Windows 10 Home version

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.8 https://github.com/brave/browser-laptop/commit/3ae27f2cf188b50ff64877a0968361d625fb84ca
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
