### ISSUE TITLE
Dev Tools Elements missing right-click context menu + edit capabilities

### ISSUE THREAD

**Issue by pingram3541** [brave/browser-laptop#13549]
### Description
When opening dev tools and wanting to modify a dom element the right-click menu of choices is missing:

![screen shot 2018-03-21 at 11 16 02 am](https://user-images.githubusercontent.com/319284/37729106-50cba5a6-2cf9-11e8-9629-dcbead3a56dd.png)

Additionally, double-clicking a node does not allow for editing, i.e. add a new div inside an existing one.

### Steps to Reproduce
  1. Open dev tools
  2. Right-click on a node
  3. Or double-click on a node

**Actual result:**
Nothing, nada, nilche

**Expected result:**
Right click menu or double-click edit of entire node and children

**Reproduces how often:**
Every time

### Brave Version
0.21.19

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Thanks for the report 😄 We're tracking this functionality being broken with https://github.com/brave/browser-laptop/issues/6724

Please subscribe to that issue for updates.  Thanks 😄
