### ISSUE TITLE
transactions not recorded in ledger-state.json

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13544]
### Description
Contribution made with UGP tokens but no PDF statement generated. Closer inspection (using information from user's `ledger-state.json` file) it was determined that the transactions were not recorded in the ledger-state.json file. Additionally, Last Contribution Date says 'no contributions made' and Contribution Date is 'overdue'.

Reported via community post/DM: https://community.brave.com/t/when-or-were-can-i-see-a-payment/17750

### Steps to Reproduce
Unknown - I have not reproduced this in testing.

**Actual result:**
Transactions were not recorded in ledger-state.json

**Expected result:**
Transactions are recorded in ledger-state.json

**Reproduces how often:**
Difficult

### Brave Version

**about:brave info:**
0.21.18

**Reproducible on current live release:**
unknown

### Additional Information
I have additional information from the user if needed for investigation.

**Comment by LaurenWags** [comment]
cc @kjozwiak @bsclifton @NejcZdovc

**Comment by NejcZdovc** [comment]
will be fixed with https://github.com/brave-intl/bat-client/pull/53

**Comment by kjozwiak** [comment]
@NejcZdovc as @LaurenWags mentioned above, this seems hard to reproduce. Is there anything specific that needs to be checked/verified with this change? Would contributing/reconciling with only UGP grants on the staging server suffice?

**Comment by NejcZdovc** [comment]
@kjozwiak yeah just spot check it, to verify that we didn't break anything

**Comment by kjozwiak** [comment]
Thanks @NejcZdovc. I marked this as `QA/no-qa-needed` as we don't have a reproducible case. QA we'll go through the ledger while going through the manual passes and ensure that nothing has regressed.

@LaurenWags if you do end up finding a test case somewhere in the meantime, please attach it here :)
