### ISSUE TITLE
Numbers Blurred in GDAX and Not Visible on Graph Axis on GDAX/Trading View

### ISSUE THREAD

**Issue by Muzzleford** [brave/browser-laptop#13557]
When trying to view the websites https://www.gdax.com/trade/ETH-EUR the price numbers cannot be read clearly as they are blurred under both the order book and sales sections.

Also the on the graph scale numbers do not appear only the 1st number e.g 4 instead of 400 appears.

The same graph issues occurs on https://www.tradingview.com/chart/4JbVEHy0/

This has occurred for about 2/3 months I was awaiting a release to fix it.

![image](https://user-images.githubusercontent.com/37650807/37755242-f2114456-2da4-11e8-9ded-5c3cc1c30e00.png)

![image](https://user-images.githubusercontent.com/37650807/37755249-f9a9b338-2da4-11e8-84f4-3d787f0e024d.png)

<!

**Comment by bsclifton** [comment]
@Muzzleford do you have more information about your setup? Are you on Windows? If so, do you have a DPI setting which is larger than 100%?

**Comment by Muzzleford** [comment]
Sure i am on a macbook pro and I have not changed any settings, the interesting thing is that in the earlier versions of the browser it was fine it has just been in the last few months that I've had this issue.

**Comment by jonathansampson** [comment]
I spoke with https://twitter.com/OddStockTrader over Twitter about this; he too was experiencing similar (the same?) issues, but reports no further problems since updating to 0.21.24. Here are the contents of his _about:brave_ page. @Muzzleford, do you still see this problem after on 0.21.24+?

![image](https://user-images.githubusercontent.com/815158/37996073-141a7cb2-31dc-11e8-9f13-8155a46d9dca.png)

**Comment by Muzzleford** [comment]
Hi all

Yes I still have this problem and I think I am on the same Brave version.

Should I try deleting it and re-installing it ?





On 27 March 2018 at 23:33:00, Sampson (notifications@github.com) wrote:

I spoke with https://twitter.com/OddStockTrader over Twitter about this; he too was experiencing similar (the same?) issues, but reports no further problems since updating to 0.21.24. Here are the contents of his about:brave page. @Muzzleford, do you still see this problem after on 0.21.24+?

**Comment by snyderp** [comment]
i am not able to recreate in the beta
