### ISSUE TITLE
Win10 version: Stuck in nighttime viewing

### ISSUE THREAD

**Issue by DanielGuerin** [brave/browser-laptop#1355]
My install on a Windows turned pink a few days back, as if a setting for night-time (low-blue) use were permanently turned on.  This may have happened when I upgraded an Nvdia driver, and it has persisted through a few upgrades and an uninstall/reinstall cycle.

**Comment by bbondy** [comment]
We've seen this on some outdated video drivers, but upgrading them has fixed it. Is it possible there' a newer driver update available?

**Comment by DanielGuerin** [comment]
Well, the Nvidia drivers and software claim to be  up to date, but I will keep checking periodically.

**Comment by bbondy** [comment]
You may have to go direct to the nvidia site for your video card and see / download the latest driver version is there.

**Comment by luixxiul** [comment]
Closing for now.
