### ISSUE TITLE
Shortcuts doesn't work when the input alphabet is not Latin.

### ISSUE THREAD

**Issue by g-ki** [brave/browser-laptop#13559]
### Description
Shortcuts like `CmdOrCtrl+C` / `CmdOrCtrl+C` / `CmdOrCtrl+A` doesn't work when the input alphabet is different from Latin. I have to switch my input language to English every time I have to copy text or open new tab with `CmdOrCtrl+T`.

### Steps to Reproduce
  1. Add language that doesn't use Latin alphabet to your input sources (example: Bulgarian)
  2. Select this language
  3. Open a web page and try to copy, paste or select all
  

**Reproduces how often:**
100%

### Brave Version
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 15.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by g-ki** [comment]
@eljuno yes, but it is not limited to cyrillic and korean.

**Comment by KignorChan** [comment]
Mine is fine when typing Chinese.

**Comment by sliday** [comment]
@bsclifton These are essentially the same, I believe: all shortcuts _not working_ when using non-English kb layout. (Russian in my case)

- https://github.com/brave/browser-laptop/issues/14238
- https://github.com/brave/browser-laptop/issues/14197

**Comment by g-ki** [comment]
From what I saw [here](https://github.com/brave/browser-laptop/blob/master/app/browser/menu.js) Brave uses electron.Menu module. I searched for related issues in the electron community  and I found this:

https://github.com/atom/atom-keymap/issues/203
https://github.com/electron/electron/issues/9352
https://github.com/electron/electron/issues/8741

I hope this may help you.

**Comment by bsclifton** [comment]
I believe this is the same issue as https://github.com/brave/browser-laptop/issues/11908
