### ISSUE TITLE
YouTube requests to show notification only when opened in a Private tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13567]
### Description
YouTube requests to show notification only when opened in a Private tab

### Steps to Reproduce
  1. Clean install 0.22.6
  2. Open a new tab and visit YouTube, no notification bar is shown to show YT notification
  3. Open a private tab and visit YouTube, shows notification bar asking permission for YT notification

**Actual result:**
YouTube requests to show notification only when opened in a Private tab

**Expected result:**
Should ask for notification permission only when user is logged and not when opening the site in a new tab

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.6
-- | --
V8 | 6.5.254.36
rev | e6ff4ea
Muon | 5.1.0
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
Yes

### Additional Information
Issue reproduced on macOS by @kjozwiak

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/it-doesnt-give-me-the-option-to-enable-notifications-on-youtube/21559?u=eljuno

+1 from me. :-)
