### ISSUE TITLE
Dragging pinned tab shows the pin outside the browser window frame

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13566]
### Description
Dragging pinned tab shows the pin outside the browser window frame

### Steps to Reproduce

  1. Clean install 0.22.6
  2. Pin 4-5 tabs
  3. Click and drag one of the pinned tabs, the pinned tab is shown outside the browser window frame

**Actual result:**
![pinnedtab_movement](https://user-images.githubusercontent.com/17010094/37781437-9ffc4faa-2de8-11e8-8bc4-89bef78cce43.gif)

**Expected result:**
Should not show outside the frame when dragging the pin 

**Reproduces how often:**

### Brave Version

**about:brave info:**

Brave | 0.22.6
-- | --
V8 | 6.5.254.36
rev | e6ff4ea
Muon | 5.1.0
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
No

### Additional Information
cc: @petemill @bsclifton

**Comment by LaurenWags** [comment]
Reproduced on MacOS

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.8 https://github.com/brave/browser-laptop/commit/3ae27f2cf188b50ff64877a0968361d625fb84ca
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
