### ISSUE TITLE
Hover preview gets stuck on pinned tab when trying to unpin

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13569]
### Description
Hover preview gets stuck on pinned tab when trying to unpin

### Steps to Reproduce

  1. Clean install 0.22.x 
  2. Visit few sites in new tabs and pin them
  3. Set focus on an unpinned tab
  4. Hover over pinned tab wait for it to show full tab preview
  5. When tab preview is enabled on pinned tab the borders have extra pixel for pinned tab
  6. Unpin the pinned tab which is showing tab preview, preview gets stuck and overlaps on the favicon of pinned tab to the left. Have to click to move away from the hover preview

**Actual result:**
![pin_tab_hover](https://user-images.githubusercontent.com/17010094/37790148-99179c3e-2dfd-11e8-83de-f2aededd3e60.gif)

**Expected result:**
hover preview should not get stuck when the pinned tab is unpinned

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.6
-- | --
V8 | 6.5.254.36
rev | e6ff4ea
Muon | 5.1.0
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
No

### Additional Information
cc: @petemill

**Comment by petemill** [comment]
I think this is reproducible in Windows but not Mac, since there is no preview on Mac whilst context menu is open, whereas Windows has a known issue that hovering over a context menu does not un-hover an element.

**Comment by NejcZdovc** [comment]
pushing this into triage
