### ISSUE TITLE
pinned tabs don't display correctly when closing normal tabs via the X icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13578]
### Description
Closing tabs (via the X) causes pinned tabs display to (sort of) disappear until you either move your mouse out of the tab bar area. Additionally, if you close enough tabs, you'll see that the pinned tabs look like they're displaying behind the normal tabs (almost ghost like) again, until you move your mouse out of the tab bar area.

### Steps to Reproduce

  1. Have some pinned tabs and some non pinned tabs (non pinned tabs can just be new tabs, they don't have to have sites loaded).
  2. click on one of the non pinned tabs. 
  3. Close tab via the X.
  4. Don't move your mouse from tab bar area, you'll see that your pinned tabs aren't displaying correctly.
  5. Continue to close tabs via the X (again, don't let your mouse leave the tab bar area), close enough so that you only have 1-2 tabs left.
  6. Your pinned tabs are sort of displaying behind the non pinned tabs
![screen shot 2018-03-22 at 6 34 52 pm](https://user-images.githubusercontent.com/28145373/37808032-dfba35f4-2e1e-11e8-81fc-cb629b9b749b.png)

**Actual result:**
Tabs display oddly until you leave the tab bar
![tabcloseweirdness](https://user-images.githubusercontent.com/28145373/37808049-ebf7bfee-2e1e-11e8-9dae-1c0be845912e.gif)

**Expected result:**
Tabs should display normally (this is 0.21.24)
![tabclose-02124](https://user-images.githubusercontent.com/28145373/37808058-f5847e80-2e1e-11e8-9646-9111b88b463a.gif)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.6
V8 | 6.5.254.36
rev | e6ff4ea
Muon | 5.1.0
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @kjozwiak on MacOS and Win.

**Comment by petemill** [comment]
Fixed with b1cddd6

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
