### ISSUE TITLE
Unable to switch tabs

### ISSUE THREAD

**Issue by deonblaauw** [brave/browser-laptop#13571]
This is happening every day now. I have a couple of tabs open, no more than 5. Then, all of a sudden, I cannot switch between tabs and I'm able to only use a single tab. The only way to fix this, is by restarting the browser completely. I'm using Brave on Ubuntu 17.10.

**Comment by Tomatoshadow2** [comment]
What Brave version are you using?

**Comment by deonblaauw** [comment]
Brave: 0.20.30
V8: 6.4.388.40
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd
Muon: 4.7.9
OS Release: 4.13.0-32-generic
Update Channel: Release
OS Architecture: x64
OS Platform: Linux
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.119

**Comment by jonathansampson** [comment]
Related to (and possibly a dupe of) https://github.com/brave/browser-laptop/issues/12753.

**Comment by bsclifton** [comment]
@deonblaauw can you please try updating your Brave version? I believe our last version fixed a related bug

If you upgrade and still experience the problem, please re-open this issue.  Thanks 😄
