### ISSUE TITLE
mailto link opens Gmail composer without any styling

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#13588]
### Description

mailto links open Gmail composer without any styling

### Steps to Reproduce
  1. Open sample html file below in both Chrome and Brave
  2. Click mailto link
  3. Note difference; Chrome composer is styled; Brave's is not

**Actual result:**
![mailtobrave](https://user-images.githubusercontent.com/5156230/37861665-f1ca47ec-2f14-11e8-9fad-9454c45d0102.png)

**Expected result:**
![mailtochrome](https://user-images.githubusercontent.com/5156230/37861667-fc9b5058-2f14-11e8-9449-d816ff7ab1d0.png)

**Reproduces how often:**
Always

### Brave Version
0.21.24

### Additional Information

    <html>
       <a href="mailto:user@example.com">Click here</a>
    </html>

**Comment by vinicentus** [comment]
Confirmed. After reloading the website looks normal.

The devloper tools gives repeated 404:s for an iframe.


Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
