### ISSUE TITLE
unable to open Recover wallet dialog a second time from corrupt wallet overlay

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13584]
### Description
If you click on 'Recover my Brave Wallet' button from the corrupt wallet overlay, close the popup (without copy/paste or import of keys), and click on the 'Recover my Brave Wallet' button again, the popup won't display. You have to close/reopen Brave to get the recover dialog again.

### Steps to Reproduce

1. Launch brave with `LEDGER_ENVIRONMENT=staging` and `LEDGER_VERBOSE=true` with a clean profile
2. Enable payments
3. Save recovery key
4. Close Brave
5. Open ledger-state.json and modify seed (remove some of them)
6. Launch Brave with same parameters from step 1
7. Navigate to Payments, overlay is shown.
8. Click on recover button. Close recover popup.
9. Click on recover button again.

**Actual result:**
Popup is not displayed. If you close/relaunch Brave and you’re on the payments page the recover popup is opened automatically without clicking on the button.

![corrupt-overlay2](https://user-images.githubusercontent.com/28145373/37846934-902a8854-2ea5-11e8-949a-3896ea8ca8d9.gif)

**Expected result:**
Recover wallet dialog should open when you click on the recover button from the overlay.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.7

**Reproducible on current live release:**
no

**Comment by bsclifton** [comment]
confirmed this is still an issue (even after https://github.com/brave/browser-laptop/pull/13607 was merged)

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.9 https://github.com/brave/browser-laptop/commit/e0fc1523b132cd618f95682193050103dc680c83
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
