### ISSUE TITLE
Brave in Mac os x full screen black bar on top

### ISSUE THREAD

**Issue by molinadavid** [brave/browser-laptop#1358]
I am using the current version of Brave (0.91) for Mac OS X and when I enter full screen there is black bar on top of the browser where the normal menu bar would be on the desktop (Please see attached image for reference) it did not happened on the previous version of the browser (or Mac OS X I am not 100% sure).

the information of Brave version is as follows:
Brave: 0.9.1
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 5.10.0
Update channel: dev

The version of my Mac OS X is El capitan 10.11.4 (15E65)

![image](https://cloud.githubusercontent.com/assets/4196411/14517058/48eacefc-0244-11e6-9ab0-21bef9a8c7ea.png)

**Comment by endeakidz** [comment]
Got same error !
