### ISSUE TITLE
search

### ISSUE THREAD

**Issue by Exotic-Code** [brave/browser-laptop#13586]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by Tomatoshadow2** [comment]
Please fill out your issue.

**Comment by kjozwiak** [comment]
Closing this due to lack of information. @Exotic-Code, please add more information when creating a bug as there's nothing actionable here. Thanks!
