### ISSUE TITLE
formatting is off on the corrupted wallet overlay

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13582]
### Description
Formatting is off on the corrupted wallet overlay. The FAQ link and the recover button should be on the same line.

### Test plan / Steps to Reproduce

1. Launch Brave from terminal with LEDGER_ENVIRONMENT=staging and LEDGER_VERBOSE=true with a clean profile
2. enable payments
3. close browser
4. open ledger-state.json and modify seed (remove some of them)
5. start browser again with same parameters
6. navigate to payments

**Actual result:**
![screen shot 2018-03-23 at 11 57 30 am](https://user-images.githubusercontent.com/28145373/37843697-1219e8a0-2e9c-11e8-99ec-1394622b9ce6.png)

**Expected result:**
From https://github.com/brave/browser-laptop/issues/13424#issuecomment-373568005
![proposedwalletoverlay](https://user-images.githubusercontent.com/28145373/37843779-40f890ea-2e9c-11e8-8db0-b6dab0f679f3.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.7

**Reproducible on current live release:**
no

### Additional Information

cc @NejcZdovc @bradleyrichter

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/13605

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.9 https://github.com/brave/browser-laptop/commit/e0fc1523b132cd618f95682193050103dc680c83
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
