### ISSUE TITLE
Last Pass extension

### ISSUE THREAD

**Issue by DFjjjjfdjjjfdjj** [brave/browser-laptop#13585]
### Description
Adding securenote - add attachment. Prompts for installation of binary version of browser. Installation does not fix issue. 

### Steps to Reproduce

  1. add securenote
  2. add attachment
  3.

**Actual result:**

![image](https://user-images.githubusercontent.com/37716337/37854005-f80fab44-2ee0-11e8-804b-a4373296142d.png)

**Expected result:**

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
6.5.254.36

**Reproducible on current live release:**

**Comment by Tomatoshadow2** [comment]
What version of Brave are you using and what OS are you on?

**Comment by DFjjjjfdjjjfdjj** [comment]
64bit windows 7 

Brave | 0.21.24
-- | --
V8 | 6.5.254.36

**Comment by jonathansampson** [comment]
@DFjjjjfdjjjfdjj Can you navigate to _about:brave_ and share here what you see there?
