### ISSUE TITLE
Need feature : being able to create a shortcut to brave application to launch a defined url

### ISSUE THREAD

**Issue by MacKentoch** [brave/browser-laptop#1359]
## FEATURE SUGGESTION : Being able to create a shortcut to brave application that launch a defined website

It seems like it is not yet implemented (_I'm not an experienced electron developer, maybe I missed it_).

This feature would be useful at office (_current operating system is **Windows7**_).

I would need to make a win shortcut like  : 
`BRAVE_DIR\Update.exe —processStart Brave.exe  "https://www.brave.com"`

**Comment by luixxiul** [comment]
You can create shortcut ``C:\Users\Temp\AppData\Local\Brave\app-0.9.6\Brave.exe "https://www.brave.com"`` to open the page. Isn't it what you want?

**Comment by MacKentoch** [comment]
Yes it works better when pointing to brave.exe directly.

Thank you for answer it is all ok like this for me.

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5227

**Comment by bsclifton** [comment]
This was fixed after Squirrel moved to a stub executable (late 2016? early 2017?)
