### ISSUE TITLE
twitch not working with brave, time not being recorded/added in ledger

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13597]
### Description

Looks like Twitch has regressed around Friday and is not being added into the ledger table on both the latest `0.22.7` 8bb7e77 BETA and the current `0.21.24` 19c78a1 released/live build.

I don't think this is a regression with the client as it also stopped working on `0.21.24` 19c78a1. Seems like the issue is either server side, or Twitch pushed an update that broke Brave.

### Test plan / Steps to Reproduce

  1. launch `0.21.24` 19c78a1 or
  2. enable payments via `about:preferences#payments`
  3. visit twitch.tv and watch a video (either live/vod) for ~2mins

You'll notice that the entry isn't being added into the ledger table under Payments.

**Actual result:**

Twitch entries are not being added into the ledger table under Payments.

**Expected result:**

Twitch entries should be added into the ledger table under Payments when viewing content.

**Reproduces how often:**

100% reproducible when using the above STR.

### Brave Version

**about:brave info:**

Brave: 0.22.7 
V8: 6.5.254.41 
rev: 8bb7e77f69bca186429aafda4bc6ba4d82a5de47 
Muon: 5.1.1
libchromiumcontent: 65.0.3325.181
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently reproducible using `0.21.24` 19c78a1 which is the latest released version.

### Additional Information

* Win 10 x64 - Reproduced
* macOS 10.13.3 - Reproduced

Also reproduced by both @btlechowski and @LaurenWags as well.

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.8 https://github.com/brave/browser-laptop/commit/3ae27f2cf188b50ff64877a0968361d625fb84ca
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
