### ISSUE TITLE
Private tab record history

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13601]
### Description

Private tab record and store history

### Steps to Reproduce

  1. Open private tab
  2. Visit some page there
  3. You can find it in history

**Actual result:**

Websites from private tab in history.

**Expected result:**
No sites from private tab in history.

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

yes

**Comment by NejcZdovc** [comment]
cc @diracdeltas

**Comment by kjozwiak** [comment]
@raisty, do you have a specific test cases/STR? I tried the following:

* launched `0.21.24` 19c78a1
* opened PB and visited reddit.com, facebook.com, ebay.com. brave.com in several tabs
* checked `about:history` and didn't see any entries from PB being listed
* restarted the browser with the PB tabs opened
* checked `about:history` and didn't see any entries from PB being listed

Can you reproduce this 100% of the time using a specific case?

@LaurenWags @btlechowski mind taking a look and seeing if you could reproduce?

**Comment by LaurenWags** [comment]
I have not been able to reproduce. Will see if @raisty is able to provide some steps, might be helpful to know how private tabs are being opened (keyboard shortcut, context menu, etc)?

**Comment by btlechowski** [comment]
I have not been able to reproduce. Maybe it is a session tab that op is using?

**Comment by raisty** [comment]
I can reproduce it with issue #13604 
Then I think, this issue is solved.

**Comment by kjozwiak** [comment]
@raisty from the looks of #13604, it sounds like you thought you were in a PB window. Unfortunately, Brave doesn't have PB windows. You need to specifically open PB tabs.

Closing the following issue. Please re-open if the above assumption isn't correct.
