### ISSUE TITLE
New window with private tab open normal tabs

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13604]
### Description

In chrome, when you open private window all tabs are private. But in Brave browser new window with private window open normal tabs. This workflow should be changed, because you can easily forgot you are not in private mode. Please add new private window, not only private tab.

### Steps to Reproduce

  1. Open new private tab.
  2. Move it to new window. (Drag&Drop tab)
  3. Click on "+", new tab

**Actual result:**

Open normal tab

**Expected result:**
Private window should open only private tabs.

**Reproduces how often:**

If you forgot - always.

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

yes

### Additional Information

New private window should be added.

**Comment by kjozwiak** [comment]
Closing as a duplicate. We have a feature request in #1288 for PB windows.
