### ISSUE TITLE
Ctrl+f search bar not functional

### ISSUE THREAD

**Issue by ryanmusante** [brave/browser-laptop#13602]
### Description
CTRL+F search pops up the search bar however it is not functional. 

### Steps to Reproduce

1. CTRL+F
2. Use search term
3. No search prompted
-->
**Actual result:**

![searchplease](https://user-images.githubusercontent.com/26808646/37908907-752ca2a2-3144-11e8-80f8-77ded0562c24.png)

**Expected result:**
SEARCH TERM: "Please" for example does not work.

**Reproduces how often:**

What percentage of the time does it reproduce?
---Intermittent

### Brave Version

**about:brave info:**

Please open about:brave, copy the version information, and paste it.

Name | Version
-- | --
Brave | 0.21.18
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 4.15.13-1-MANJARO
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**

**Comment by btlechowski** [comment]
Thanks for reporting.

Can you update your Brave to 0.21.24 and recheck?

**Comment by ryanmusante** [comment]
brave-snapshot-bin 0.21.24-1 in AUR. I will update tonight and check and re-post details.

**Comment by jonathansampson** [comment]
I am _unable_ to reproduce from my build:

``` 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

**Comment by kjozwiak** [comment]
I couldn't reproduce the issue under Ubuntu 17.10.1 x64 using the latest BETA:

```
Brave: 0.22.7 
V8: 6.5.254.41 
rev: 8bb7e77f69bca186429aafda4bc6ba4d82a5de47 
Muon: 5.1.1 
OS Release: 4.13.0-36-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

@ryanmusante  could you share some more information with us? Which website are you visiting where you're seeing this happen?

**Comment by ryanmusante** [comment]
Bug seemed only present for sites using forum softwares: PHPBB / Discourse.
It is working without problems with beta.

**Comment by ryanmusante** [comment]
@kjozwiak I'm still testing with the latest git branch and it seems to be working good now. I'll keep posted on any changes

**Comment by kjozwiak** [comment]
Awesome! Thanks @ryanmusante, much appreciated!

**Comment by bsclifton** [comment]
@ryanmusante is this still happening on our latest build?

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
