### ISSUE TITLE
Account Balance takes longer to update than before

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13618]
### Description
Account Balance on Prod wallets takes longer to update than it did previously in the following scenarios:
a. When adding funds from an Uphold acct to your Brave wallet using `CARD_ID` this should be quick, but Brave takes about 45 minutes to display the increased balance.
b. When checking a reconcile/payment, Brave does not display the decreased balance until about 45 minutes after you begin the process

### Steps to Reproduce

Adding Funds to a Brave Wallet using `CARD_ID`
  1. Launch Brave with a clean profile
  2. Enable Payments
  3. Close Brave
  4. Open ledger-state.json file and locate `CARD_ID`
  5. Copy this value and save off to the side. Close ledger-state.json file.
  6. Login to Uphold and send BAT to the `CARD_ID` noted.
  7. Launch Brave again. 
  8. Wait 45 minutes for balance to be updated. This used to be quicker (and is quicker on staging).

Reconcile/Payment
  1. Launch Brave with payments enabled and BAT already in the wallet (from the above scenario is fine)
  2. Visit sites/videos (YT/Twitch)
  3. Close Brave. 
  4. Change `reconcileStamp` in ledger-state.json
  5. Re-launch Brave using `LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true`
  6. Wait for about 5mins for the reconcile to occur, see Currently processing msg
  7. Wait for about 10-15min and receive the notification and an updated Last Contribution Date
  8. Wait another 30-40 minutes for your account balance to reflect the new decreased amount

**Actual result:**
Takes approximately 45 minutes to reflect a change in account balance

**Expected result:**
Expected this to be quicker as it was previously and as it is on Staging

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.7

**Reproducible on current live release:**
Yes, reproduces on 0.21.24

### Additional Information
If you try these with a staging wallet you do not have to wait as long as on Prod. 
See also https://github.com/brave/browser-laptop/issues/13529#issuecomment-376392851
cc @kjozwiak

**Comment by NejcZdovc** [comment]
I think this is because we have caching for 45min

cc @evq

**Comment by kjozwiak** [comment]
Moving this into the `0.22` milestone for the discussion. We'll most likely move this out.

**Comment by evq** [comment]
Yes, this was changed a while back so these wait times are not unexpected. We have plans to move to a better cache invalidation mechanism which should resolve this.

**Comment by bsclifton** [comment]
Let's open an issue in brave-core if we experience a long wait time there too (as we begin deving/testing features there)
