### ISSUE TITLE
Trying to create own extension

### ISSUE THREAD

**Issue by MegaUber** [brave/browser-laptop#1361]
Is there a guide or any specific guidelines as to how to load my own extension? Looking to convert a extension that I built for chrome and load it into Brave.

I added the following 
`process.emit('load-extension', 'EXTENSION NAME', path.join(__dirname, '..', '..', 'extensions'))`
in index.js after lines 361 and 365

Am I missing another area where it calls and loads the extensions?
But it doesn't seem to want to load, i even looked over the manifest.json in 1pass and brave and everything seems to be right. Any help would be greatly appreciated.

**Comment by bbondy** [comment]
The extension support we have so far is here:
https://github.com/brave/browser-laptop/wiki/Extensions-API-support

But basically I think that's all you'll need to do until we expose a UI.
@bridiver to confirm.

**Comment by bridiver** [comment]
The extension api support is somewhat limited right now. We are working on adding more comprehensive support, but the current release implemented the bare minimum that we needed for 1password. If you are using background pages you can navigate directly to the page chrome-extension://extensionid/_generated_background_page.html to see if there are any errors that are preventing it from loading correctly

**Comment by bridiver** [comment]
The extension api support is somewhat limited right now. We are working on adding more comprehensive support, but the current release implemented the bare minimum that we needed for 1password. If you are using background pages you can navigate directly to the page chrome-extension://extensionid/_generated_background_page.html to see if there are any errors that are preventing it from loading correctly

**Comment by cezaraugusto** [comment]
Closing for now.
