### ISSUE TITLE
Fine tune pinned % when doing a contribution

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13620]
### Description

We need to tune % so that we are even closer to the pinned % from the ledger table

## **10 BAT (15 votes)**

<img width="1899" alt="screen shot 2018-03-27 at 8 24 05 am" src="https://user-images.githubusercontent.com/9574457/37950276-3ce8ed84-3198-11e8-8fb1-163d5adca83b.png">

[ledger-state.json.zip](https://github.com/brave/browser-laptop/files/1850865/ledger-state.json.zip)

Publisher | Pinned | % table | Votes | % votes
------------ | ------------- | ------------- | ------------- | -------------
slo-tech.com|Yes|30|5|33.33
Brave on YouTube|Yes|20|4|26.67
TechGumbo on YouTube|Yes|10|3|20
24ur.com|Yes|5|1|6.67
Chris' Tutorials on YouTube|No|17|0|0
ThioJoe on YouTube|No|8|1|6.67
Popesites on YouTube|No|6|1|6.67
CNET on YouTube|No|4|0|0

----

## **7.5 BAT (11 votes)**
![image](https://user-images.githubusercontent.com/9574457/37956549-f1af637a-31ab-11e8-96fb-ad26c8f253d9.png)

[ledger-state.json.zip](https://github.com/brave/browser-laptop/files/1851130/ledger-state.json.zip)

Publisher | Pinned | % table | Votes | % votes
------------ | ------------- | ------------- | ------------- | -------------
slo-tech.com|Yes|30|4|36.36
Brave on YouTube|Yes|20|3|27.27
TechGumbo on YouTube|Yes|10|1|9.09
24ur.com|Yes|5|1|9.09
Chris' Tutorials on YouTube|No|17|2|18.18
ThioJoe on YouTube|No|8|0|0
Popesites on YouTube|No|6|0|0
CNET on YouTube|No|4|0|0

**Comment by bsclifton** [comment]
Will be addressed with brave-core
