### ISSUE TITLE
URI handling security risk.

### ISSUE THREAD

**Issue by zaabalonso** [brave/browser-laptop#1362]
Windows 10.
Brave 0.9.1.
Have Skype Installed.

When a website tries to use a URI, there is no pop-up asking the user if he wants to trigger the action. That can be a security flaw.

e.g. https://join.skype.com/ocChbo2ozTef which is trying to launch Skype: URI.

**Comment by diracdeltas** [comment]
Here's what Chrome's external protocol prompt looks like:
![screen shot 2016-04-14 at 6 31 28 pm](https://cloud.githubusercontent.com/assets/549654/14548790/3528a300-026f-11e6-8eaa-16e6b575ac52.png)

**Comment by diracdeltas** [comment]
It appears this was by design in Electron (https://github.com/electron/electron/issues/2687). Thoughts on simply reverting https://github.com/electron/electron/pull/2933 in our fork for now and whitelisting the common ones like `mailto:`? @bbondy

**Comment by bbondy** [comment]
API is here: https://github.com/electron/electron/pull/5231

**Comment by diracdeltas** [comment]
yep, please ping me when we are updated to v0.37.6 and i'll add this

**Comment by bbondy** [comment]
We're on 0.37.6 already but I think this landed after that so once there's a 0.37.7.

**Comment by diracdeltas** [comment]
oops, i meant 0.37.7

**Comment by bbondy** [comment]
@diracdeltas we're at 0.37.7 now
