### ISSUE TITLE
Don't Generate Crash Reports when Reporting is Disabled

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13625]
### Description
When Brave is _not configured_ to report crash data, the browser should not generate temporary crash files.

### Steps to Reproduce
1. Disable crash reporting in Brave
2. *Crash Brave*
3. See `%appdata%/brave` for crash files

**Actual result:**
Crash files are still generated.

**Expected result:**
No files should be generated when reporting is disabled.

**Reproduces how often:**
Always.

### Brave Version
0.21.24

**about:brave info:**
N/A

**Reproducible on current live release:**
Yes

### Additional Information
Reported by a user over Twitch stream.

**Comment by akashnimare** [comment]
@jonathansampson this should fix it -
```javascript
exports.init = (enabled) => {
  if (enabled) {
    initCrashKeys()
    muon.crashReporter.setEnabled(enabled)
    console.log('Crash reporting enabled')
  } else {
    console.log('Crash reporting disabled')
  }
}

```

**Comment by flamsmark** [comment]
Currently, we create reports but don't send them?

**Comment by akashnimare** [comment]
> Currently, we create reports but don't send them?

Looking at the code, yes we don't send it. You need to dump the crash data to Sentry or somewhere else (ex - [here](https://github.com/zulip/zulip-electron/blob/master/app/main/crash-reporter.js)).

**Comment by akashnimare** [comment]
@bsclifton let me know if you want me to send a PR with [this](https://github.com/brave/browser-laptop/issues/13625#issuecomment-376709536) fix.

**Comment by bsclifton** [comment]
hi @akashnimare - please do PR this 😄

**Comment by bsclifton** [comment]
Closing as `wontfix`. Let's revisit this in [brave-core](https://github.com/brave/brave-browser)

**Comment by akashnimare** [comment]
What's going on here? Is this repo deprecated or something?

**Comment by bsclifton** [comment]
@akashnimare kind of - we are in the process of moving to a new code-base. We'll definitely offer hotfix support (security fixes, etc) and critical bug fixes, but basically all new development is happening on the new code-base

You can download the developer channel release (which uses this new code-base) here:
https://brave.com/download-dev

And then there is information about the new repository here:
https://github.com/brave/brave-browser
