### ISSUE TITLE
Lastpass form fill does not appear in Twitter, Facebook and horizontal scrollbar appear instead

### ISSUE THREAD

**Issue by vuongggggg** [brave/browser-laptop#13637]
### Description
When I click Lastpass icon on login form of Facebook or Twitter, it does not show the Lastpass form fill and horizontal scrollbar appears instead.

### Steps to Reproduce

  1. Open Facebook https://www.facebook.com/ or Twitter https://twitter.com/
  2. Click on the Lastpass icon of login inputs 

**Actual result:**
The Lastpass form fill does not show, horizontal scrollbar appears instead. An exception throw in Console

> Refused to frame 'chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/' because it violates the following Content Security Policy directive: "frame-src 'self' https://staticxx.facebook.com https://twitter.com https://*.twimg.com https://5415703.fls.doubleclick.net https://player.vimeo.com https://pay.twitter.com https://www.facebook.com https://ton.twitter.com https://syndication.twitter.com https://vine.co twitter: https://www.youtube.com https://platform.twitter.com https://upload.twitter.com https://s-static.ak.facebook.com https://4337974.fls.doubleclick.net https://8122179.fls.doubleclick.net https://donate.twitter.com".

Exception:
![image](https://user-images.githubusercontent.com/3168632/38041397-d012f3fe-32db-11e8-8a13-c4ff8f5d9862.png)

Horizontal scrollbar problems:
![image](https://user-images.githubusercontent.com/3168632/38041486-0de659b4-32dc-11e8-80e7-b1682de983e8.png)
![image](https://user-images.githubusercontent.com/3168632/38041520-24b6f3d8-32dc-11e8-8d7e-a70d21538d8e.png)

**Expected result:**
The Lastpass form fill appears.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**
<Sorry, but I don't understand this definition>

### Additional Information
May it related with this problem: I just try to make it again in MacOS, but I couldn't login Lastpass extension, the same exception has been thrown, when I disable Strict Site Isolation I has successful to login Lastpass. I think it has some conflicts between extensions with this feature.

MacOS version:
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by Liunkae** [comment]
Related: #12612 (Extensions, including LastPass, not working with Strict Site Isolation)

**Comment by bsclifton** [comment]
Issues with strict site isolation are fixed with brave-core 😄 

You can download the developer channel release here:
https://brave.com/download-dev
