### ISSUE TITLE
Ability to customize the new tab page

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1363]
Allow the ability to customize the new tab page.
I think that's probably different from the home page which is set in preferences.

https://github.com/brave/browser-laptop/issues/2106#issuecomment-228938494

**Comment by rohanthacker** [comment]
Is this feature road mapped? or any plans to implement it soon?

**Comment by kingscott** [comment]
Hey @rohanthacker! I've been working on it piece by piece - not to interject. 

Referencing #2106. You may be able to collab on this specific issue when I have a bit more complete, possibly with some of the logic. I wouldn't mind sharing :)

**Comment by kingscott** [comment]
@rohanthacker We could use some help on this issue. Tagging @bradleyrichter, as he has the knowledge of tasks for this one...

**Comment by rohanthacker** [comment]
@kingscott Sure! What you thinking about ?

**Comment by kingscott** [comment]
This one is probably going to more in the way of styles. Referring to #2106, we discussed a mock-up for what the new tab page should look like. This is the list of tasks that are not being worked on as of now:

* time permitting - allow local image folders for BG image source
* set up frecency-based top-sites list collection/management 
* set up data collection/connection to cumulative ads/tracker blocking, plus user-reset command (for display purposes)

**Comment by rohanthacker** [comment]
@kingscott I guess this is now spec'ed under  #3001 ? 
I'd be happy to work on the tasks mentioned above.

**Comment by bradleyrichter** [comment]
Hi @rohanthacker... I am just now creating the real task for the new-tab. The one here grew out of the pref-related item. The parent will be #3001 and we'll make children for each sub task listed in the bottom of the description.

**Comment by kingscott** [comment]
I believe this has been added. Closing for now...

**Comment by benyben123** [comment]
Want this as well (:

**Comment by ExpandingMan** [comment]
This feature is still pretty limited.  It would be nice to be able to add ones on icons to a complete grid and re-organize it with folders.  Currently it's not possible to manually place a site on the "top sites" list a la opera and vivaldi.  It would also be nice to be able to change the background image and time formats.

Is there enough interest in this to open another issue?

**Comment by bsclifton** [comment]
@ExpandingMan as we've shifted development to brave-core, we're not actively developing this version of the browser (other than security + bug fixes). 

You can download the latest Beta for brave-core here:
https://brave.com/download-beta

You can check out this issue and give it a +1
https://github.com/brave/brave-browser/issues/353
