### ISSUE TITLE
PDF Printing - PDFs show as blank after print to file

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13636]
### Description
Found while testing https://github.com/brave/browser-laptop/issues/13546 - if you select 'Save as PDF' on the print dialog for a file that is already a PDF and try to open that file in Brave, it will display as blank. System viewer shows the PDF content.

### Steps to Reproduce

  1. Navigate to a PDF such as http://www.orimi.com/pdf-test.pdf
  2. Select File > Print
  3. On the Print dialog, under 'PDF' drop down, select 'Save as PDF' enter a title and Save.
  4. Open PDF in system viewer or another browser.
  5. PDF is viewable.
  6. Open PDF with Brave.
  

**Actual result:**
PDF displays as blank:
![screen shot 2018-03-28 at 11 34 42 am](https://user-images.githubusercontent.com/28145373/38039794-0745f516-327c-11e8-8ea1-3acc4e2e3c8b.png)

This is the file I saved with Brave: 
[PDF-test2.pdf](https://github.com/brave/browser-laptop/files/1856626/PDF-test2.pdf)

**Expected result:**
PDF should display text.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.8
V8 | 6.5.254.41
rev | 3ae27f2
Muon | 5.1.2
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
yes reproduces on 0.21.24

### Additional Information
Workaround: Use the 'download PDF' button instead of print to file.
Reproduced by @kjozwiak on MacOS and Ubuntu

**Comment by diracdeltas** [comment]
Do you have 'Site Isolation' enabled by chance?

**Comment by kjozwiak** [comment]
@darkdh nope, this happens without SI being enabled.

**Comment by LaurenWags** [comment]
@diracdeltas - same answer as @kjozwiak, no SI enabled.

**Comment by GeetaSarvadnya** [comment]
1+ from community: https://community.brave.com/t/printing-pdf-from-gmail-launches-save-pop-up-rather-than-print/27116/2
