### ISSUE TITLE
22.8 its a duplicated

### ISSUE THREAD

**Issue by bn0785ac** [brave/browser-laptop#13631]
You've uploaded  22.7 binaries at 22.8

https://github.com/brave/browser-laptop/releases/tag/v0.22.8beta

**Comment by kjozwiak** [comment]
I downloaded the following from https://github.com/brave/browser-laptop/releases/tag/v0.22.8beta:

* Brave-Beta-0.22.8.dmg
* brave-beta_0.22.8_amd64.deb
* BraveBetaSetup-x64.exe

I received the correct version of Brave every single time:

```
Brave: 0.22.8 
V8: 6.5.254.41 
rev: 3ae27f2cf188b50ff64877a0968361d625fb84ca
libchromiumcontent: 65.0.3325.181
Muon: 5.1.2 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
```

@bn0785ac are you not getting `0.22.8` when downloading from https://github.com/brave/browser-laptop/releases/tag/v0.22.8beta?

**Comment by bsclifton** [comment]
@bn0785ac these installed version 22.8 for me? We also now have a 22.9 which you can check out

**Comment by bn0785ac** [comment]
I'll try 22.9 now :)


f3d5c5a66275dc2d551db31239fdc7d268385fced2e8d03669eb279b4751aceb  brave-snapshot-bin-0.22.7.tar.bz2
f3d5c5a66275dc2d551db31239fdc7d268385fced2e8d03669eb279b4751aceb  brave-snapshot-bin-0.22.8.tar.bz2
