### ISSUE TITLE
history not always being recorded under about:history on certain websites

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13634]
### Description

On certain websites, the history isn't always being added/recorded under `about:history` when browsing within that specific website. The initial origin is logged, but anything else within that website won't be logged. However, if you open a page from that specific website in a new tab, the history will correctly be logged in `about:history`.

### Steps to Reproduce

Example 1:

  1. visit https://www.motorsport.com
  2. check `about:history` and you'll notice the entry being added correctly
  3. browse through the website by clicking on a few articles, other categories etc..
  4. visit `about:history` and you'll notice that entries haven't been added
  5. open a few articles in a new tab, and visit `about:history` (you'll notice the entries appearing)

Example 2:

  1. visit https://www.youtube.com and click through several videos
  2. check `about:history` and you'll notice that there's only one YouTube entry
  3. visit https://www.youtube.com and open several videos in new tabs
  4. visit `about:history` and you'll notice that the entries are correctly being added

**Actual result:**

![history](https://user-images.githubusercontent.com/2602313/38036713-50f2530a-3275-11e8-9bef-7c4f7d6c732c.gif)

**Expected result:**

History should always be recorded under `about:history` when browsing a website.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.8 
V8: 6.5.254.41 
rev: 3ae27f2cf188b50ff64877a0968361d625fb84ca 
libchromiumcontent: 65.0.3325.181
Muon: 5.1.2 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
```

**Reproducible on current live release:**

Yes, currently reproducible under `0.21.24` 19c78a1 which is the latest release.

### Additional Information

* Ubuntu 17.10.1 x64 - Reproduced
* macOS 10.13.3 x64 - Reproduced
* Win 10 x64 - Reproduced

@bsclifton also reproduced this on his machine using macOS.

**Comment by simon-inoc** [comment]
Hi, I would like to work on this bug as part of my college course.
I have also reproduce this error while reading some tennis news in this website: [ATP World Tour](http://www.atpworldtour.com/en)

**Comment by srirambv** [comment]
Watching YT videos in a single tab doesn't add all the video links in history. It only adds one entry for the first page visited in the tab. Subsequent page loads of same domain are not listed. However opening a new video in a new tab adds it to the history list.  #3848  fix could be the root problem here.

**Comment by kjozwiak** [comment]
We should really look into this issue and see if we can get a fix for this milestone. IMO, not correctly adding the users history into `about:history` is a pretty bad bug, especially when it affects websites like `YT` as @srirambv mentioned above. It makes it very hard for a user to go back and search for something specific in `about:history`. The only time we shouldn't be adding entries into the history is when a user users PB.

**Comment by bsclifton** [comment]
In Muon,  the `navigation_handle` (passed into the WebContent's `DidFinishNavigation` method) is returning true when `IsSameDocument()` is called. Muon then emits a `did-navigate-in-page` event which does not log a new history entry (opposed to `did-navigate` which would)

When the user is browsing, the `href` portion of the URL is the same:
`https://www.youtube.com/watch`

When the navigation type value is determined, it's not taking the `query` portion into account. Looking at Google Chrome's history, every value is always recorded. For example:
1. In tab 1, visit https://maps.google.com
2. In tab 2, open `chrome://history/` and you should see one entry for maps.google.com
3. Switch back to tab 1 and zoom out. Notice the URL change
4. Switch back to tab 2 and hit refresh. Notice there are now two entries

To fix this bug, we'd need to revert the `inPageNav` (browser-laptop) portion of https://github.com/brave/browser-laptop/pull/10005. This would basically re-open https://github.com/brave/browser-laptop/issues/3848

Will share with team and discuss which would be a better option

**Comment by bsclifton** [comment]
Discussed with team- we're not going to address this as we'll get the fix for free when moving to the direct fork of Chromium (see https://github.com/brave/brave-browser)

More details available here:
https://brave.com/development-plans-for-upcoming-release/
