### ISSUE TITLE
Extension popups empty and transparent on first click after Brave restart

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#13633]
### Description
When I open or restart Brave, then click on the Bitwarden icon, the resulting extension popup is transparent. This seems to only happen on the first click of each browser restart. A second click fixes the issue.

### Steps to Reproduce
  1. Enable Bitwarden. (You might need to actually set up the account/login. Not sure.0
  2. Restart Brave.
  3. Click on the Bitwarden icon.

**Actual result:**
![screen shot 2018-03-28 at 9 16 12 am](https://user-images.githubusercontent.com/133786/38035099-4424a22e-3269-11e8-87c8-3e1ce0319c93.png)

**Expected result:**
![screen shot 2018-03-28 at 9 19 53 am](https://user-images.githubusercontent.com/133786/38035108-4af2493a-3269-11e8-8168-870373c1b12a.png)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
```
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

**Reproducible on current live release:**
Yes

### Additional Information
I'm not sure if this affects other extensions, like LastPass.

**Comment by bsclifton** [comment]
cc: @jonathansampson

**Comment by jonathansampson** [comment]
Not limited to password managers; this repros with MetaMask and other extensions too.

**Comment by Jacalz** [comment]
Yeah I have noticed this issue as well on Bitwarden and I double checked Metamask and the same issue is there...

**Comment by LaurenWags** [comment]
+1s from community: https://community.brave.com/t/metamask-fails-to-render-contents-of-metamask-window-on-first-click/19590

**Comment by kjozwiak** [comment]
Still an issue with `0.22.669` 6cda2e84f749e66409e9e3bca63f5796422e7edf. Reproduced on Mint 18.3 x64 and macOS 10.13.3 x64.

**Comment by Jacalz** [comment]
Yeah still an issue with 0.22.669 on Windows 10

**Comment by StephenBass** [comment]
+1 from the BAT Telegram https://t.me/batproject/50473

**Comment by LaurenWags** [comment]
+1s from community: https://community.brave.com/t/lastpass-extension-window-blank-binary-version-of-extension/21490

**Comment by eljuno** [comment]
+1s from Reddit https://www.reddit.com/r/brave_browser/comments/8os0w3/lastpass_integration_a_bit_quirky_here/

**Comment by Liunkae** [comment]
This may be `fixed-with-brave-core`.

**Comment by GeetaSarvadnya** [comment]
+1 from https://community.brave.com/t/extensions-not-visible/23300/6

**Comment by davidtemkin** [comment]
Let's discuss this on Tuesday. Seems like we should prioritize. @bsclifton @kjozwiak @bbondy @diracdeltas

**Comment by rsfxiii** [comment]
Couldn't find instructions on how to report a build properly, so feel free to steer me to that for more info, but I was dealing with having MetaMask & other extensions be totally unusable and the only one (MetaMask) I cared about being broken. 

Disabling the following settings in my Mac running High Sierra 10.13.5 allowed **at least** MetaMask to render and be usable again, so I haven't done testing outside this:

- Disable Google Wildvine
- Disable Adobe Flash Support
- Disable PDF Viewer extension

I have an inkling the former two didn't matter as much as the third, but that's a hunch. Hopefully this helps in some fashion. Let me know if I can provide more detail and what.

**Comment by bridiver** [comment]
this is not a regression, is there a reason this is blocking c68? Chromium updates should normally only be blocked for regressions.

**Comment by bridiver** [comment]
fyi - this issue is as old as extension popups on Brave

**Comment by davidtemkin** [comment]
We need this for our MetaMask-integrated local ETH wallet, which is shipping in the C68 release. Can't launch with first click on MetaMask showing a blank frame when it is part of the marketing announcement.

**Comment by petemill** [comment]
WebView is correctly in the DOM with a valid src attribute. Hiding and showing via CSS is working correctly, so this may be solvable with a workaround from browser-laptop instead of muon.

**Comment by LaurenWags** [comment]
@petemill is additional testing needed other than the steps to reproduce?
