### ISSUE TITLE
Support MacBook trackpad pinch to zoom gesture

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1364]

**Comment by luixxiul** [comment]
+1 from support

**Comment by bbondy** [comment]
cc @darkdh (but treat form fill and import data as higher priority in general)

**Comment by alexwykoff** [comment]
New +1 from support (https://linkbubble.zendesk.com/agent/tickets/5149)

**Comment by jkup** [comment]
Also double-tap to zoom being requested!

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6321

**Comment by Liunkae** [comment]
Double-tap to zoom is being tracked separately at #4451.

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6406

**Comment by iandundas** [comment]
+1 (seems doing +1 is acceptable here! apologies if not.. )

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/pinch-and-spread-to-zoom/862

**Comment by jonathansampson** [comment]
+1 from community https://gab.ai/AquinasJohnPaul/posts/6373069

**Comment by jonathansampson** [comment]
+1 from Twitter user: https://twitter.com/schofeld/status/848594205463240705

> Jonathan Schofield (@schofeld)
> No pinch and zoom in @brave on iOS it seems. Please fix. #a11y

**Comment by dskrainka** [comment]
+1

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/mackbook-pro-trackpad-gestures-not-working-in-google-maps-with-brave-0-16-9/4265)

**Comment by b4rton** [comment]
+1 +1 +1  Basic browser functionality on Mac. Built into Chromium, no? Please add this.

**Comment by jandahl** [comment]
+1 - one of the most basic things for Mac users is missing.

**Comment by bsclifton** [comment]
Per discussion with @darkdh, we get this functionality with Chromium 61 😄  Let's create a new issue to track bugginess or things which could be better
