### ISSUE TITLE
crash dumps when detaching/attaching tabs

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13646]
### Description

When attaching/detaching tabs on Linux, sometimes you'll see crash dumps being listed in the terminal, example:

`Crash dump id: feb10969f7575ef9`

These crashes will also appear in `chrome://crashes`:

* https://stats.brave.com/dashboard#crash/5abc606694910b001feaeff2
* https://stats.brave.com/dashboard#crash/5abc6067b25a14001f30e2b0
* https://stats.brave.com/dashboard#crash/5abc606ab25a14001f30e2bd

These crashes don't seem to cause any data/session loss, but they definitely happen pretty frequently that I think a investigation is warranted.

### Steps to Reproduce

  1. launch brave via the terminal
  2. create a few tabs and visit several websites
  3. start detaching/attaching tabs within the original window

You'll eventually start noticing crash dumps being listed in the terminal. After about 20 minutes of going through this, I managed to log ~35 crashes into `chrome://crashes`.

**Actual result:**

![crashdumpslinux](https://user-images.githubusercontent.com/2602313/38069060-64bb087e-32e2-11e8-9d10-291524c5183b.gif)

**Expected result:**

Shouldn't be crashing and creating crash dumps when tabs are being detached/attached.

**Reproduces how often:**

It's pretty easy to reproduce using the above STR. Simply create tabs in a single window, attach/detach several times and you'll eventually get into a state where you'll receive crash dumps when attaching/detaching tabs.

### Brave Version

**about:brave info:**

```
Brave: 0.22.11 
V8: 6.5.254.41 
rev: 56de94731aa2aa9ab398ed928f68488f3ea5c11a 
libchromiumcontent: 65.0.3325.181
Muon: 5.1.2
OS Release: 4.13.0-26-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
```

**Reproducible on current live release:**

Yes, currently reproducible using `0.21.24` 19c78a1 which is the current release.

### Additional Information

Reproduced on Ubuntu 17.10 x64 & Mint 18 x64.

**Comment by bsclifton** [comment]
@kjozwiak does this still happen?

**Comment by kjozwiak** [comment]
@bsclifton I couldn't reproduce it with the `0.23.79`. I tried detaching/attaching tabs for about 10min on both Ubuntu 18.04 x64 and didn't receive any crash dumps.

**Comment by bsclifton** [comment]
I'll close this for now- but let's re-open if we experience it again. Thanks for restesting, @kjozwiak 😄
