### ISSUE TITLE
Open external application permissions list is bloated

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#13642]
### Test plan
See https://github.com/brave/browser-laptop/pull/13644

### Description

Opening external application through link like zoom will make the list growing

### Steps to Reproduce

  1. Opening several unique zoom links
  2. Go to `about:preferences#security`
  3.Check `Open external applications` and you will see the bloated list

**Actual result:**

<img width="1408" alt="screen shot 2018-03-28 at 1 01 11 pm" src="https://user-images.githubusercontent.com/11330831/38053934-4937ed5e-328a-11e8-8826-161d7e9bc46e.png">

**Expected result:**
recorded one rule per application/link

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.22.9 
V8: 6.5.254.41 
rev: e0fc1523b132cd618f95682193050103dc680c83 
Muon: 5.1.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

No

**Comment by btlechowski** [comment]
Verified on Win7 x64:
* 0.22.11: 56de94731aa2aa9ab398ed928f68488f3ea5c11a
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
