### ISSUE TITLE
Remembered permissions for Open external application are never applied

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13643]
### Test plan
See https://github.com/brave/browser-laptop/pull/13644

### Steps to Reproduce

  1. Go to google.com
  2. Open sms://test in URL field
  3. Remember this action when permissions dialog is shown and click allow
  4. Open sms://test in URL field

**Actual result:**
The permissions dialog is shown again

**Expected result:**
The permissions dialog is not shown.
The action associated with the protocol is executed.

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.9 
V8: 6.5.254.41 
rev: e0fc1523b132cd618f95682193050103dc680c83 
Muon: 5.1.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Comment by diracdeltas** [comment]
i have a fix for this that also fixes https://github.com/brave/browser-laptop/issues/13642

**Comment by btlechowski** [comment]
Verified on Win7 x64:
* 0.22.11: 56de94731aa2aa9ab398ed928f68488f3ea5c11a
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
