### ISSUE TITLE
Recover your Brave wallet dialog shown after successful recovery

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13645]
### Steps to Reproduce
1. Clean install
2. Create Wallet in about:preferences#payments
3. Exit Brave
4. Delete seed 20 and 21 in ledger-state.json
5. Run Brave again
6. Recover wallet with:
`vower obovoid menace tobogganist hoyle honoree pixel pestilently disconcertment sellable ruffing supervision zoroastrian based coparent slackened`
7. Click OK on the dialog
8. Restart Brave

**Actual result:**
about:preferences#payments?ledgerRecoveryOverlayVisible
is opened which shows the Recover your Brave wallet dialog 

**Expected result:**
about:preferences#payments is opened

### Brave Version
```
Brave: 0.22.11 
V8: 6.5.254.41 
rev: 56de94731aa2aa9ab398ed928f68488f3ea5c11a 
Muon: 5.1.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

cc @LaurenWags @kjozwiak @bsclifton @NejcZdovc

**Comment by bsclifton** [comment]
kicked this out of the 0.22.x milestone- a fix would be nice... but I don't think it's required for this release (work-around is easy- user can just close the tab)

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.703 https://github.com/brave/browser-laptop/commit/903b8d0d3703b5fdc5a719294403e7460d9b806d
* muon 6.0.8
* libchromiumcontent 66.0.3359.139

**Comment by srirambv** [comment]
Functionality works but needs to verify once https://github.com/brave/browser-laptop/issues/14063 is confirmed
