### ISSUE TITLE
Tor "new identity" button should be more user-friendly

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13658]
Currently it always appears as enabled regardless of whether there's a tor private tab open and just says "new identity" 

maybe this can be moved to the popup that appears when you click on the urlbar lock icon instead of a global menu item

**Comment by riastradh-brave** [comment]
Tor Browser puts this under the Tor onion button in the address bar, alongside 'new circuit for this site' and a few other things.

**Comment by riastradh-brave** [comment]
For posterity: We moved it under shields, and made clean reload create a new circuit too.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
