### ISSUE TITLE
Window is missing an icon from system taskbar after closing it with active private tab

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13659]
### Steps to Reproduce

1. Open two windows
2. In one window open private tab
3. Activate the private tab
4. Restart Brave

**Actual result:**
One of the windows is missing an item(icon) from system taskbar
Also it is missing from system Alt-tab list.
It seems to be a background window which cannot be focused
![missing_icon](https://user-images.githubusercontent.com/34715963/38111269-9ee26b84-339e-11e8-9ab5-04ac2a684e8f.gif)

**Expected result:**
two windows are shown

**Reproduces how often:**
100%

### Brave Version
 
```
Brave: 0.22.11 
V8: 6.5.254.41 
rev: 56de94731aa2aa9ab398ed928f68488f3ea5c11a 
Muon: 5.1.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```
Also reproduced by @kjozwiak on Win 10

**Reproducible on current live release:**
no

**Comment by petemill** [comment]
I could reproduce this whenever there is more than 1 window during startup (on Windows). Incoming fix...

**Comment by btlechowski** [comment]
The issue still persists in v 0.22.12 when there are 3 or more windows. Tested on Win7 x64.

Steps to Reproduce:
1. Open 3 or more windows
2. In any window open a private tab
3. Activate the private tab
4. Restart Brave

**Comment by btlechowski** [comment]
Verified on Win7 x64:
* 0.22.13: a8cfb160479f1d00d0769368eb440030182bb83b
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
