### ISSUE TITLE
Torrent Viewer - broken icon in about:preferences#extensions

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#13664]
### Description
The icon for **Torrent Viewer** in `about:preferences#extensions` is broken on win10 (64). 
![brave-torrentviewer-bug-03292018](https://user-images.githubusercontent.com/8979240/38124411-48864ce0-3396-11e8-83af-39067d800995.PNG)

### Steps to Reproduce

  1. Enter `about:preferences#extensions` in the URL bar.
  2. Scroll down to the **Torrent Viewer** extension. 
  3. See broken icon. 

**Actual result:**
![brave-torrentviewer-bug-03292018](https://user-images.githubusercontent.com/8979240/38124411-48864ce0-3396-11e8-83af-39067d800995.PNG)

**Expected result:**
Torrent Viewer icon (the signal that you're in the right browser) 

**Reproduces how often:**

100% on win10 x64

### Brave Version

**about:brave info:**
```
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

**Reproducible on current live release:**
yes

### Additional Information
Needs investigation to determine status on macOS, linux and win10 x32.

**Comment by vuongggggg** [comment]
I've got the same. I inspected on broken icon, it seems show the url from an old version folder
file:///C:/Users/USERNAME/AppData/Local/brave/app-0.19.123/resources/extensions/torrent/img/webtorrent-128.png

It will work with "the new":
file:///C:/Users/USERNAME/AppData/Local/brave/app-0.21.24/resources/extensions/torrent/img/webtorrent-128.png

**Comment by lukemulks** [comment]
@bsclifton can you get this in queue? noticed it was still around while doing some metamask testing this week.
