### ISSUE TITLE
implement Tor "New Identity" functionality

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13662]
we have a button in Tor MVP that just sets a new tor circuit for the current site by calling https://github.com/brave/muon/pull/473/files#diff-df5c427fd693f9ebb2e5952cf0e9c8c7R802

we should add a button that also clear cookies, localStorage, and other linkable info for the site

**Comment by diracdeltas** [comment]
renaming this now that the new identity button was taken out of the UI

**Comment by alexwykoff** [comment]
@diracdeltas could you migrate this to Brave core repos as needed please?

**Comment by tomlowenthal** [comment]
Behold, the future: brave/brave-browser#1137
