### ISSUE TITLE
Add fireball.com as search provider (region: eu, germany)

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#13669]
### Description
The founder of the German-based privacy search engine fireball.com has requested we add their search engine to our list of search engine options.  https://fireball.com

### Steps to Reproduce

  1. Na
  2.
  3.

**Actual result:**

Na

**Expected result:**
Na

**Reproduces how often:**

Na

### Brave Version
Na
**about:brave info:**

**Reproducible on current live release:**

Na

### Additional Information

Aligns with privacy position. I recommend we add them.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/feature-request-new-search-engine-or-allow-adding-search-engines/18922?u=eljuno

**Comment by jumde** [comment]
Merged - https://github.com/brave/browser-laptop/pull/13673
