### ISSUE TITLE
fill out Tor FAQ on brave wiki page

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13661]
There will be various items in the Tor UI where we should link to a page with more info for non-technical users; for instance #13658. I started https://github.com/brave/browser-laptop/wiki/Brave-Tor-Support#tor-faq as a placeholder.

**Comment by flamsmark** [comment]
Do we have other FAQ candidate questions?

**Comment by flamsmark** [comment]
Preliminarily done. If there are more FAQ questions, plz add here or to the wiki page and reopen.

**Comment by Tomatoshadow2** [comment]
@flamsmark @diracdeltas Can anyone help edit this, if more answers need to be provided?

**Comment by flamsmark** [comment]
@Tomatoshadow2 If there are other question you have, feel free to drop them here and I'll see about adding them.
