### ISSUE TITLE
Nothing but black screen after page loads

### ISSUE THREAD

**Issue by islapete** [brave/browser-laptop#1366]
Using Windows 10.  I get a black screen after pages load.  www.yahoo.com
several other pages including www.brave.com lock up.  Everything was working fine.

**Comment by bsclifton** [comment]
When building locally, I get that while it's loading... Is there any text being printed to screen? Try hitting `ctrl+a`, it should highlight. Also curious if anything shows in the console if you hit `ctrl+alt+J`?

**Comment by islapete** [comment]
If I press ctrl+alt+j I get the Dev Tool.  I see this error:
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

Keith 

    On Saturday, April 23, 2016 3:47 AM, Brian Clifton <notifications@github.com> wrote:
 

 When building locally, I get that while it's loading... Is there any text being printed to screen? Try hitting ctrl+a, it should highlight. Also curious if anything shows in the console if you hit ctrl+alt+J?—

**Comment by islapete** [comment]
I also get many many other pages that load and then freeze.  Brave is not frozen just the pages.

**Comment by bridiver** [comment]
some http and network errors don't currently provide any notification to the user and a blank screen is displayed. I'm not sure if this is what you are seeing or not. See #1611

**Comment by bridiver** [comment]
there was a bug where the renderer process would crash (the black screen) if you navigated with the dev tools open, but that bug is fixed in the latest release. Are you running the latest version and/or latest code in git?

**Comment by luixxiul** [comment]
From support /tickets/3858 
> The newest version did not work either. Once install was complete it just showed a black screen.
>
> ![](https://cloud.githubusercontent.com/assets/3362943/15466016/78e75f02-2112-11e6-9f5b-07ffd15fe85b.jpg)

**Comment by luixxiul** [comment]
Closing this in favor of #1053

**Comment by bridiver** [comment]
are we sure this is the same issue? #1053 may or may not have something to do with the profile path. @islapete can you look at #1053 and see if that also applies to you? Thanks!

**Comment by islapete** [comment]
Yes same thing here.

**Comment by luixxiul** [comment]
Reopened with a support ticket number 4387:
> I'm getting a black screen when opening the Brave browser.  I'm using the Windows 64 bit app. 
>
> I've now upgraded to Windows 10 from Windows 7.  Below is a picture of the black screen.   The top left icon works, it shows:  Restore, Move, Minimize, Maximize, Close.
>
> ![](https://cloud.githubusercontent.com/assets/3362943/16805085/a3f3c29e-4949-11e6-844d-7e95982b6e17.png)

Not sure whether this is the same issue, though.

**Comment by bsclifton** [comment]
+1 from support:
> Lenovo ThinkPad with Windows Anniversary update

When asked "Does anything show inside the window? For example, can you see the lion head and the tabs (or is the window entirely black)?"
> There is nothing in the window, just black

**Comment by bsclifton** [comment]
For folks still seeing this, can you please try the following troubleshooting steps and report back?
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

Thanks! 😄

**Comment by luixxiul** [comment]
Closing as it is stale.
