### ISSUE TITLE
Ghost Tabs in the Muon interface - On Windows

### ISSUE THREAD

**Issue by MkllTech** [brave/browser-laptop#13666]
### Description
(Windows 7)

Sometimes, when using Muon I run into ghost tabs (tabs that are closed, but are still on the tab bar, and won't go away until browser restart) this usually happens after using close other tabs, or the close tabs to the right via the context menu

### Steps to Reproduce
  1. Open up a good number of tabs - including YouTube
  2. Try using Close other tabs or Close Tabs to the right/left
  3. You should get some ghost tabs.

**Actual result:**
Ghost tabs are created that will not go away until browser restart.

**Expected result:**
All other tabs should close, and no ghost tabs should be left behind.

**Reproduces how often:**
3/6 times.
What percentage of the time does it reproduce?
50%

### Brave Version
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**
Yes

### Additional Information
None.

**Comment by Tomatoshadow2** [comment]
@MkllTech Please update to the latest version of Brave on Release channel, see if that fixes the problem. The version you are on was released Feb 23rd.

**Comment by MkllTech** [comment]
This is the latest version available to me.

**Comment by Tomatoshadow2** [comment]
The latest release version is 22.13

**Comment by bsclifton** [comment]
@MkllTech is this still an issue for you?

**Comment by MkllTech** [comment]
This is sometimes still happening.

**Comment by bsclifton** [comment]
Closing as stale - @MkllTech please re-open if you still experience this. We fixed a large number of issues related to this, so I believe it may be solved. Thanks 😄
