### ISSUE TITLE
`npm install` fails on Windows 10 w/ node v5.10.1 / npm 3.8.3

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#1367]
I forked the repo (I'd like to start contributing) and I cloned it on my local machine. I have the following versions of software:

* Windows 10 (64 bit, version 1511 OS Build 10586.218)
* GitHub shell (3.0.17.0)
* nodejs (v5.10.1)
* npm (3.8.3)
* python (2.7.10)
* Visual Studio (Community - 2015 Update 2)

Per the build section, I installed node-gyp: ```npm install -g node-gyp@3.2.1```

Here are the relevant logs when doing an npm install (full logs attached):
```bash
C:\Users\Brian\Projects\browser-laptop [master +1 ~3 -0 !]> npm install

### (warnings snipped)

> abp-filter-parser-cpp@1.1.12 preinstall C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\abp-filter-parser-cpp-ae6607e5
> npm install bloom-filter-cpp && npm install hashset-cpp


> bloom-filter-cpp@1.1.2 install C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\abp-filter-parser-cpp-ae6607e5\node_modules\bloom-filter-cpp
> node-gyp rebuild


C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\abp-filter-parser-cpp-ae6607e5\node_modules\bloom-filter-cpp>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\abp-filter-parser-cpp-ae6607e5\node_modules\bloom-filter-c
pp\build\bloom-filter-cpp.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.
Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct,
 and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\abp-filter-parser-cpp-ae6607e5\node_modules\bloom-filter-cpp
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bloom-filter-cpp"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! bloom-filter-cpp@1.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bloom-filter-cpp@1.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bloom-filter-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bloom-filter-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bloom-filter-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\abp-filter-parser-cpp-ae6607e5\npm-debug.log

> tracking-protection@1.1.2 preinstall C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\tracking-protection-587f0f54
> npm install hashset-cpp && npm install cppunitlite


> hashset-cpp@1.0.15 install C:\Users\Brian\Projects\browser-laptop\node_modules\.staging\tracking-protection-587f0f54\node_modules\hashset-cpp
> node-gyp rebuild


### (large amount of logs snipped)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! abp-filter-parser-cpp@1.1.12 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the abp-filter-parser-cpp@1.1.12 preinstall script 'npm install bloom-filter-cpp && npm install hashset-cpp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the abp-filter-parser-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install bloom-filter-cpp && npm install hashset-cpp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs abp-filter-parser-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls abp-filter-parser-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Brian\Projects\browser-laptop\npm-debug.log
```

Full logs here:
[output-full.txt](https://github.com/brave/browser-laptop/files/219392/output-full.txt)

**Comment by bsclifton** [comment]
I'm going to dig in and work on resolving this too; I just wanted to capture it in case anyone else had the same issue (give it a +1 or leave a comment if so)

I usually use Cygwin, but `npm install` [has a known issue](https://github.com/npm/npm/issues/7357)

**Comment by bbondy** [comment]
I recently setup a new windows machine and got it working.
In my situation I had VS 2013 and VS2015. For some reason I couldn't get it to work with VS2015 so I had to set an environment for:

GYP_MSVS_VERSION
and set the value to 
2013

Then it started working for me.

**Comment by bsclifton** [comment]
So I fixed the npm issue in Cygwin (and [submitted a PR](https://github.com/npm/npm/pull/12366)... after that was fixed, `npm install` worked great for me. I'm curious why it worked? Did the install default to using Cygwin's compiler instead of msbuild?

I've attached the logs:
[output-full2.txt](https://github.com/brave/browser-laptop/files/221237/output-full2.txt)

**Comment by bbondy** [comment]
I'm using mozilla-build bash shell btw.  Awesome that you fixed in that PR though!

**Comment by bsclifton** [comment]
I'll do my best to get it working in the Github shell, since a lot of folks are using that too! Hopefully, it's not hard to get to the bottom of it and then I can help jump in and start helping resolve other issues.  I confirmed I can launch the browser via `npm start` and looking forward to [grabbing this issue specifically](https://github.com/brave/browser-laptop/issues/1114) :smile:

**Comment by bsclifton** [comment]
Dug into this tonite and didn't make much progress, but I do understand the issue now. I [logged a comment with more information](https://github.com/nodejs/node-gyp/issues/679#issuecomment-210984173), will continue looking into solutions.

Like I called out above, I was able to get `npm install` working great on Cygwin after patching npm. Unfortunately, [my PR was closed](https://github.com/npm/npm/pull/12366#issuecomment-210519937), so I'd really like to help get this working in a Windows shell that is considered "supported" by npm, Inc.

**Comment by bsclifton** [comment]
My current work-around (finally did get it working!) is captured in https://github.com/nodejs/node-gyp/issues/679#issuecomment-211117703

I'm going to follow the related issues for that; hopefully documentation for node-gyp can be updated and merged

To resolve this issue, I'll find a nice way to document the workaround in the wiki :smile:

**Comment by bbondy** [comment]
interesting finds, thanks for digging intothis @bsclifton

**Comment by bsclifton** [comment]
Updated wiki with (hopefully) all the information folks would need to resolve this issue. Please see https://github.com/brave/browser-laptop/wiki/Troubleshooting
