### ISSUE TITLE
Sync inoperative

### ISSUE THREAD

**Issue by grimley** [brave/browser-laptop#13678]
Devices would appear to "connect" (display activity). No sync.
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Comment by bsclifton** [comment]
We're working on re-implementing Sync on brave-core at the moment (currently on [developer channel](https://brave.com/download-dev))
