### ISSUE TITLE
webroot flags macos installer Brave-0.21.18.dmg  as a threat

### ISSUE THREAD

**Issue by dasice** [brave/browser-laptop#13687]
### Steps to Reproduce

  1. install webroot
  2. scan brave installer
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
cc: @jonathansampson

**Comment by jonathansampson** [comment]
I was pinged today by a member of the Webroot team regarding this; from what we understand, the AV is alarmed at the presence of certain strings within the Brave application. One such string was "nicehash.com", which exists in a list of URLs as part of [our ledger/publisher code-base](https://github.com/brave/ledger-publisher/blob/9698a47ceca81c66e5f793685192ea8b0667da31/categories/150-services.js).

**Comment by Tomatoshadow2** [comment]
I have this issue as well.

**Comment by diracdeltas** [comment]
Does webroot offer a way for us to unblacklist ourselves?

**Comment by kjozwiak** [comment]
+1 from the community as well https://community.brave.com/t/pua-osx-coinminer-1-r-detection-in-the-brave-browse-for-mac/19106
