### ISSUE TITLE
clone tab isn't working properly

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13686]
### Description
Cloning a tab is not working properly. The cloned tab does not have the original tab's history, favicon, or tab name. Additionally, the url displays 'about:blank' instead of the url of the original tab.

### Steps to Reproduce

  1. Launch clean profile with 0.22.101
  2. Navigate to a site like reddit.com
  3. Click on the 'random' link at the top a few times to generate some history for the tab.
  4. Right click on tab and select 'Clone'

**Actual result:**
Tab opens but URL says 'about:blank', doesn't have the original tab favicon, tab is 'Untitled', and you cannot access the history (back arrow is grayed out):
![clone](https://user-images.githubusercontent.com/28145373/38215268-3aa0601e-3695-11e8-8d73-93f585081bdb.gif)

**Expected result:**
Cloned tab should:
- display the favicon of original tab
- have same name as original tab
- URL should show the same URL as original tab
- back arrow should be able to be used to view history

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.101
V8 | 6.5.254.41
rev | 57eaaf2
Muon | 6.0.0
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
no, does not reproduce on 0.21.24 or 0.22.13

**Comment by btlechowski** [comment]
Verified Win7 x64 v0.22.108
