### ISSUE TITLE
Brave Doesn't Offer to Save Passwords

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13680]
### Description
On some sites, Brave's built-in password manager does not offer to save passwords.

### Steps to Reproduce
1. Use the built-in Password Manager
2. Visit twitch.tv/directory, and log in

**Actual result:**
Brave does not ask to store your password.

**Expected result:**
Brave asks to store your password.

**Reproduces how often:**
Always.

### Brave Version
0.21.24

**about:brave info:**
```
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
```

**Reproducible on current live release:**
Yes

### Additional Information
I suspect the issue here is with the type of post-back to the server. A full-page post-back prompts the user to store the password, but the standard xhr-based authentication does not appear to do the same. You can test a full-page post-back on twitch.tv/about.

**Comment by Tomatoshadow2** [comment]
https://github.com/brave/browser-laptop/issues/12748 This one also deals with Twitch not saving passwords. Do you think both need to stay open or will you pick one to close over the other? The other issue is from January 19th, and looks like @darkdh was working on a fix or already had the fix ready to go, could be mistaken though.

**Comment by jonathansampson** [comment]
@Tomatoshadow2 Thank you for finding the related issue; @darkdh, thoughts on this?

**Comment by darkdh** [comment]
This will be fixed with fork. cc @bbondy

**Comment by macexpertsusa** [comment]
this also seems to be an issue on lan url's i.e. 192.168.x.x
