### ISSUE TITLE
change to Toolbar and UI elements scale doesn't take effect

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13681]
### Description
When navigated to preferences > advanced, changing the 'Toolbar and UI elements scale' does not modify the toolbar/UI elements as expected. Restart does not help.

Reported via community: https://community.brave.com/t/ui-scaling-broken/19042

### Steps to Reproduce

  1. Open about:preferences
  2. Navigate to Advanced
  3. Change the 'Toolbar and UI elements scale' option.

**Actual result:**
Toolbar and UI elements don't change size. (restart does not help)

**Expected result:**
Toolbar and UI elements should change size.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.101
V8 | 6.5.254.41
rev | 57eaaf2
Muon | 6.0.0
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
no, does not reproduce on 0.21.24 or 0.22.13

**Comment by Tomatoshadow2** [comment]
+1 from myself as well.

**Comment by petemill** [comment]
This is fixed in the latest muon feature branch, pending a build for a version bump.

**Comment by btlechowski** [comment]
Reproduced on Win7 x64 v0.22.105; Muon: 6.0.0

**Comment by btlechowski** [comment]
Verified Win7 x64 v0.22.108
