### ISSUE TITLE
Support forward and backward navigation with alternate mouse buttons.

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#1369]

**Comment by bbondy** [comment]
I think we have that, maybe your mouse is diff though?

**Comment by Raindeer44** [comment]
If this is already a feature, it doesn't work for me. I like to use the buttons on the side of my mouse for history-forward and history-back, but it doesn't seem to work. It does work on other browsers.

Platform: Linux Mint 18.1

Brave Version (revision SHA): 0.13.4 revision 71d8ffc

Steps to reproduce:
    1. Have pages in history
    2. Press mouse4 button

Expected result: go back one page in history

Actual result: nothing

**Comment by bsclifton** [comment]
I'm going to close this issue in favor of https://github.com/brave/browser-laptop/issues/3101
