### ISSUE TITLE
sometimes attach/detach of tab causes crash

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13698]
### Description
Sometimes attaching or detaching a tab causes Brave to crash.

### Steps to Reproduce

  1. Launch Brave with a clean profile using 0.22.103
  2. Open a site with links such as wikipedia.org
  3. I used middle click on a few links to open some tabs
  4. Click on one of the tabs to make it the active tab and drag it away from the window.

**Actual result:**
Sometimes Brave crashes, but not always. I also found that if it doesn't crash at this point, if you reattach and detach a couple of times that usually causes the crash as well. 

Crash Report ID: d8fe8367af726838

terminal output: https://gist.github.com/LaurenWags/08605195bfe723409b4de397452489fc#file-crash-detach-reattach-txt

**Expected result:**
Should not crash

**Reproduces how often:**
unsure

### Brave Version

**about:brave info:**
Brave | 0.22.103
V8 | 6.5.254.41
rev | 2324f55
Muon | 6.0.0
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
no

**Comment by LaurenWags** [comment]
Experienced a crash when reattaching tabs to the original window - crashID: 12850224dc5bca5a

**Comment by petemill** [comment]
This could be the "pending response" crash that @bridiver is looking in to

**Comment by bridiver** [comment]
this is likely fixed in 6.0.3
