### ISSUE TITLE
Ctrl + Enter does not complete url on latest version.

### ISSUE THREAD

**Issue by CamelCase11** [brave/browser-laptop#13701]
I love brave. But it lacks very basic functionality.
On a latest version 0.22.13 brave is unable to complete url by pressing ctrl + enter key.
Please fix this issue as it is driving me nuts.

**Comment by jonathansampson** [comment]
I am unable to reproduce the issue in 0.22.13. When I type a partial URL, and see the rest suggested in the addressbar, pressing <kbd>Ctrl</kbd>+<kbd>Enter</kbd> opens a new tab (unfocused) to the suggested site.

**Comment by CamelCase11** [comment]
It is a basic functionality which is present in internet explorer and other browsers since decade.

**Comment by jonathansampson** [comment]
@CamelCase11 I agree with you, but I am not able to reproduce the problem. When I press <kbd>Ctrl</kbd>+<kbd>Enter</kbd> it works. Can you share any further information about what you're doing, what you're expecting, and what you're seeing instead?

I think this is the logic:

https://github.com/brave/browser-laptop/blob/3dc66b0fbd45e48fd1385b50478eae0a4b30d982/app/renderer/components/navigation/urlBar.js#L142-L145
