### ISSUE TITLE
rmf24.pl crashes when PDF.js is disabled

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13705]
### Description
Brave will crash when visting rmf24.pl while pdf.js is disabled.

### Steps to Reproduce
1. Navigate to http://www.rmf24.pl/fakty/polska/news-gigantyczne-korki-na-a4-karambol-na-obwodnicy-wroclawia,nId,2564893

**Actual result:**
Brave crashes.

**Expected result:**
No crash.

**Reproduces how often:**
Always

### Brave Version
0.22.13

**about:brave info:**
``` 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Reproducible on current live release:**
Yes.

### Additional Information
Be sure to disable PDF.js and restart Brave before testing.
Impacts both Windows and macOS.

**Comment by bsclifton** [comment]
Looks like this has been resolved
