### ISSUE TITLE
re-pin of tab can take multiple tries for tab to be pinned again

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13708]
### Description
Re-pinning a tab doesn't work on the first try. Need to try at least twice (sometimes more) to get tab to pin again.

### Steps to Reproduce
  1. Launch 0.22.103 with a clean profile
  2. Open several tabs in the first window: amazon.com, brianbondy.com, clifton.io, duckduckgo.com, ecosia.org, facebook.com, google.com (this will be referred to as window 1)
  3. Drag the clifton tab out into its own window (this will be referred to as window 2)
  4. Go back to window 1 and drag another tab, ecosia, to its own window. (this will be referred to as window 3)
  5. Drag the ecosia tab from window 3 into window 2 with the clifton tab (window 2 now has 2 tabs)
  6. Go back to window 1 and pin DDG
  7. Go to window 2 and unpin DDG
  8. Right click on DDG tab and try to pin again.

**Actual result:**
DDG is not re-pinned. Need to try at least twice (sometimes more) to get tab to pin again.

https://drive.google.com/file/d/1CrhwQue8-yF8D5Rx7t7qXLXRQ1Lc0Icw/view?usp=sharing

console output: https://gist.github.com/LaurenWags/b1c7bdc2fb32400eb9ea5c87be7e0c27#file-scenario4-consoleoutput-txt
terminal output: https://gist.github.com/LaurenWags/c0bf0d1a2f4551e71df5325279263008#file-scenario4-terminaloutput-txt

**Expected result:**
Tab should re-pin without needing to try multiple times. Context menu should work in all open windows.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave | 0.22.103
V8 | 6.5.254.41
rev | 2324f55
Muon | 6.0.0
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
no

### Additional Information
Also happens if you select 'Detach' instead of drag and drop.

**Comment by petemill** [comment]
Seems resolved by object-registry WebContents ID fix in muon

**Comment by btlechowski** [comment]
Reproduced in v0.22.105 Win7 x64.
On top of that, the context menu stopped showing on one of the windows.

**Comment by LaurenWags** [comment]
@btlechowski good note about context menu - I added it to expected result so we double check that it is working in all windows.

**Comment by petemill** [comment]
Should be fixed with 0.22.108

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
