### ISSUE TITLE
Scrollbar is stuck in scrolling when context menu is shown

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13707]
### Steps to Reproduce
1. Open: about:welcome
2. Move mouse pointer over scrollbar and hold it with Left Mouse Button
3. While holding Left Mouse Button move pointer over the page
4. Press Right Mouse Button to bring context menu
5. Release Left Mouse Button

**Actual result:**
![scrollbar_context_menu](https://user-images.githubusercontent.com/34715963/38272368-4d0ea252-3789-11e8-8678-2904e9bc7ac9.gif)

**Expected result:**
Scrollbar is not stuck in scrolling

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.103 
V8: 6.5.254.41 
rev: 2324f5563110b178304d30b81f3cfae965ae4a03 
Muon: 6.0.0 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

### Important
Also reproducible for scrollbar arrows
Related issues: #13580 #13700

**Comment by MBLHarrison** [comment]
+1

To add clarification.
After step 5, it only scrolls once you move the mouse back to the scrollbar

`

Name | Version
-- | --
Brave | 0.22.13
V8 | 6.5.254.41
rev | a8cfb16
Muon | 5.1.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

`

**Comment by darkdh** [comment]
reproducible on Chrome 66.0.3359.170

**Comment by MBLHarrison** [comment]
@darkdh Chrome, or chromium?

**Comment by LaurenWags** [comment]
Community threads for scrolling issues: https://github.com/brave/browser-laptop/issues/13580#issuecomment-391075395
