### ISSUE TITLE
Scrollbar is stuck in scrolling after alt-tab

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13700]
### Steps to Reproduce

1. Open: about:welcome
2. Move mouse pointer over scrollbar and hold it with Left Mouse Button
3. While holding Left Mouse Button press alt+tab (or alt+esc)

**Actual result:**
Scrollbar is stuck in scrolling
Similar to #13580 

**Expected result:**
Scrollbar is not stuck in scrolling

**Reproduces how often:**
100%

**Important**
Also reproducible for scrollbar arrows

### Brave Version
 
```
Brave: 0.22.103 
V8: 6.5.254.41 
rev: 2324f5563110b178304d30b81f3cfae965ae4a03 
Muon: 6.0.0 
OS Release: 6.1.7601 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Comment by darkdh** [comment]
reproducible on Chrome 66.0.3359.170

**Comment by LaurenWags** [comment]
Community threads for scrolling issues: https://github.com/brave/browser-laptop/issues/13580#issuecomment-391075395

**Comment by bsclifton** [comment]
This issue was closed as `wontfix` since Brave Core does not have this issue and we'll be moving over to that soon (from our current Muon based product). More information about Brave Core available here:
https://brave.com/development-plans-for-upcoming-release/
