### ISSUE TITLE
URL-like strings can cause empty autocomplete results

### ISSUE THREAD

**Issue by rvagg** [brave/browser-laptop#13718]
### Description

`foo` and `foo.` are fine, `foo.b` and `foo.bar` is not, `foo.bar.` is fine again.

### Steps to Reproduce

  1. Slowly type in `github.com.` to the urlbar
  2. Observe autocomplete up until `github.c` when you only get the "top sites" entry for `github.com`, not from your history
  3. It works again if you add a `.` on the end, i.e. `github.com.`

### Brave Version

**about:brave info:**

Brave | 0.22.13
-- | --
V8 | 6.5.254.41
rev | a8cfb16
Muon | 5.1.2
OS Release | 17.4.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

Same on a `master` build

### Additional Information

Fixed in https://github.com/brave/browser-laptop/pull/13693 which also contains an explanation about why this happens.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.80 53a429f
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
