### ISSUE TITLE
MetaMask May Break Sites

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13711]
### Description
Enabling MetaMask may cause web compatibility issues with some websites. MetaMask performs a script-injection into the visited document, which may cause issues. One example of this is with the vote.webbyawards.com website.

![image](https://user-images.githubusercontent.com/815158/38279940-48cf76ce-3768-11e8-9d42-508572738dd1.png)

When MetaMask is disabled, the angular application works as expected.

### Steps to Reproduce
1. Enable MetaMask (no need to authenticate or unlock the extension)
2. Navigate to vote.webbyawards.com

**Actual result:**
Note presence of template strings.

**Expected result:**
Website should work as intended.

**Reproduces how often:**
100%

### Brave Version
0.22.13

**about:brave info:**
``` 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Reproducible on current live release:**
Yes

### Additional Information
MetaMask injects a script tag directly into the root element, via its manifest.json:

```
   "content_scripts": [ {
      "all_frames": true,
      "js": [ "scripts/contentscript.js" ],
      "matches": [ "file://*/*", "http://*/*", "https://*/*" ],
      "run_at": "document_start"
   } ],
```

Worth noting that the WebExtension API determines the placement of the script when using `run_at`. In the case of `document_start`, the `script` in added immediately within the rootElement.

Switching `run_at` to `document_end` resolves this problem, though it may not be a feasible solution for the MetaMask team, depending on what `scripts/contentscript.js` does.

**Comment by jonathansampson** [comment]
cc @danfinlay

**Comment by jonathansampson** [comment]
Testing this today, I am unable to repro.

**Comment by danfinlay** [comment]
Sorry for slow reply on your issue, I had the flu when this was submitted :/

We tracked with this issue:
https://github.com/MetaMask/metamask-extension/issues/3382

The ability to block sites we interfere with is here:
https://github.com/MetaMask/metamask-extension/pull/3590

And you can see we stopped injecting web3 for webby awards here:
https://github.com/MetaMask/metamask-extension/blob/master/app/scripts/contentscript.js#L137

This is just a short-term solution, long term we are going to not inject web3 on pages by default, instead requiring sites to explicitly request a sign-in:
https://github.com/MetaMask/metamask-extension/issues/714

**Comment by danfinlay** [comment]
(This should be fixed now)

**Comment by danfinlay** [comment]
@khizar-ali please post a reproduction site if possible, so that we can debug how exactly we may be breaking that site.

**Comment by bsclifton** [comment]
I don't think there's any specific action we can take, so I'm going to close this issue. For any future webcompat incidents, let's open issues here:
https://github.com/MetaMask/metamask-extension/issues
