### ISSUE TITLE
Auto-open specific file download.

### ISSUE THREAD

**Issue by patcheduppiece** [brave/browser-laptop#13714]
I regularly access an RMM (remote monitoring and management) tool as part of my job. In the course of my duties, I'm required to have regular LogMeIn client downloads which launching remote connection sessions. In Chrome, I have the ability to "always open" these files. Is this functionality in the pipeline, or no?

I would love to be able to recommend Brave to our customers, but without this feature, I know they'll be in a similar predicament. Thanks in advance,

**Comment by bsclifton** [comment]
Brave is moving from the Muon implementation to a fork of the Chromium UI, which means we have almost all of the settings that Chromium has by default (which should include this option). I took a quick glance at Chrome and wasn't able to find the option you're talking about

@patcheduppiece would you be willing to download our Developer channel release?
https://brave.com/download-dev

The settings closely match Chrome at the moment- I think you'll find this being addressed.  I'm going to close this issue out as I believe that build fixes the issue (please let me know!). Thanks

**Comment by patcheduppiece** [comment]
Sure thing.

 

I’ll take a peek when I have an opportunity. BTW, thanks for the reply.
