### ISSUE TITLE
Strict Site Isolation Breaks Embedded YouTube Videos

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13716]
### Description
When _Strict Site Isolation_ is enabled, embedded YouTube videos will not respond to clicks (and thus cannot be manually started). *No repro in Chrome with Strict Site Isolation enabled.*

### Steps to Reproduce
1. Enable _Strict Site Isolation_ in about:preferences#security
2. Navigate to [a page with embedded YouTube videos](https://www.elobservador.com.uy/una-grieta-esta-separando-africa-dos-partes-y-obliga-evacuar-un-pueblo-n1209288)
3. Click to begin playing an embedded video

**Actual result:**
Video does not begin playing.

**Expected result:**
Video begins playing.

**Reproduces how often:**
Always.

**about:brave info:**
``` 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Reproducible on current live release:**
Yes (when _Strict Site Isolation_ is enabled).

### Additional Information
This issue does not appear to repro in Google Chrome when _Strict Site Isolation_ is enabled.

**Comment by BrendanEich** [comment]
@diractdeltas @bridiver seems worth a quick look to assess. Thanks.

**Comment by newtang** [comment]
Same with Vimeo embeds FWIW.
