### ISSUE TITLE
Navigating to about:error redirects to chrome-extensions://

### ISSUE THREAD

**Issue by MBLHarrison** [brave/browser-laptop#13724]
### Description
When navigating to about:error on a fresh new tab. You are redirected to
[chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-newtab.html](url)

### Steps to Reproduce

1.  Open new tab which hasn't directed to any URL
2. In Url enter 'about:error'
3. Navigation

**Actual result:**
Redirected to chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-newtab.html

**Expected result:**
Directed to a tab focussing on the current error affecting brave.

**Reproduces how often:**
100%
10/10

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.22.13
V8 | 6.5.254.41
rev | a8cfb16
Muon | 5.1.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
Yes

**Comment by donnelt** [comment]
Same.
