### ISSUE TITLE
can't acess to preferences

### ISSUE THREAD

**Issue by Masshat** [brave/browser-laptop#1372]
HI guys, i have installed brave on archlinux, access to web-sites seems working well, but when i try to access to preferences by clicking on the menu or performing "about:preferences", a blank page appear but nothing is displayed?
![screenshot from 2016-04-14 21-44-29](https://cloud.githubusercontent.com/assets/10482907/14541394/1cc543de-028a-11e6-9df7-25630c7d09af.png)

Rgds,
MH.

**Comment by diracdeltas** [comment]
Any errors in the page console or browser console?

**Comment by Masshat** [comment]
How can i see that?
When i launch brave in the terminal, there is no errors, can you show me a way to get the lock, i can help to debug?

**Comment by Masshat** [comment]
![log](https://cloud.githubusercontent.com/assets/10482907/14574839/32bc0216-035e-11e6-9327-24846ecba40d.png)

**Comment by Masshat** [comment]
up?

**Comment by diracdeltas** [comment]
cc @bridiver

**Comment by bridiver** [comment]
Linux is a bit behind right now and won't work with browser-laptop/master, but @bbondy is working on new electron builds which should be ready this week. Latest release should work fine, but you have to go back to https://github.com/brave/browser-laptop/commit/bb8284872ce2983880636f27170fc6c9b3057e88 to run on Linux in dev

**Comment by bbondy** [comment]
Yep this is hopefuly fixed, the last couple linux builds diverged from master to exclude extensions so you'd see this problem if you were on linux.

Removing `~/.electron` and `node_modules` and reinstalling will probably already work.  I'll resolve once I verify or someone else confirms it's working now.

**Comment by Masshat** [comment]
HI guys, thank you so much for your great work, can i try to reinstall the browser or the bug was not fixed yet?

**Comment by bbondy** [comment]
It would be useful if you clear both folders and try again for the steps in my previous comment. Or if you are busy I will try before we release.

**Comment by bbondy** [comment]
Fixed and verified that it worked here:
https://github.com/brave/electron/commit/cc6e4f8f39dd49ba1d5ed52dbb278c5f2ffd03bc

**Comment by Masshat** [comment]
Thank you Guys, good job :+1:
