### ISSUE TITLE
Sort ledger table based on %

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13721]
### Test Plan
https://github.com/brave/browser-laptop/pull/13726

### Description

Ledger table should be sorted based on % in desc order.

**Comment by NejcZdovc** [comment]
@LaurenWags it's just using % nothing more 😃 so section is sorted correctly

**Comment by LaurenWags** [comment]
awesome, thanks for the clarification!

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.702 https://github.com/brave/browser-laptop/commit/e4a853d9990c62328a8a4320fec21f58c9cdc0c1
* muon 6.0.7
* libchromiumcontent 66.0.3359.139

**Comment by kjozwiak** [comment]
@srirambv @LaurenWags @GeetaSarvadnya @btlechowski please make sure we also go through the new ledger case [1] that was added into the manual test plan that involves generating 500 entries into the ledger table using `npm run add-simulated-synopsis-visits 500`.

[1] https://github.com/brave/qa-resources/blob/master/wikitemplate.md#ledger

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.712 e48c5ff
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
* tried 100, 500, 1000 visits
