### ISSUE TITLE
'when closing an active tab' setting does not work

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13733]
### Description
'When closing an active tab' setting is not respected. If you have 'Select its parent tab' (default) or 'Select the last viewed tab' as the setting, the next tab is selected. See test cases from https://github.com/brave/browser-laptop/pull/12193#issue-279587065

### Steps to Reproduce

See test cases from https://github.com/brave/browser-laptop/pull/12193#issue-279587065 - I specifically used the Parent tab and Next tab test cases but all should be checked.

**Actual result:**
Next tab is always selected, doesn't matter if you have parent tab or last viewed as the selection.

**Expected result:**
Setting should be respected.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.103

**Reproducible on current live release:**
no

### Additional Information
This was previously resolved with https://github.com/brave/browser-laptop/issues/11526

**Comment by petemill** [comment]
Great find @LaurenWags. Note for @bridiver this was because `tab-detached-at` does not fire for destroyed tab and also it fires after muon has changed active tab. Instead I have to revert back to manually calling `setActive` on `will-destroy` and before calling `move`.

**Comment by btlechowski** [comment]
Verified Win7 x64 v0.22.105
