### ISSUE TITLE
Block HTTP without HTTPS in Tor private tabs

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#13734]
Consider blocking HTTP via Tor by default, unless we already do this and I missed the part where we do.  This way, we alleviate concerns that malicious Tor exits might eavesdrop on or interfere with the HTTP streams passing through them.  (Of course, your ISP could do this in non-Tor traffic anyway...and maybe [already does](https://arstechnica.com/tech-policy/2014/09/why-comcasts-javascript-ad-injections-threaten-security-net-neutrality/), [like Comcast](https://gizmodo.com/comcast-to-customer-who-noticed-it-secretly-injecting-c-1821235362).)

[Adapted from early design notes.]

**Comment by tomlowenthal** [comment]
This issue has become brave/brave-browser#1136.
