### ISSUE TITLE
Tab Message Box does not show

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13738]
### Description
Did not move the component from frame.js to main.js

### Steps to Reproduce

  1. Visit https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_confirm
  2. Click 'try it'

**Actual result:**
Nothing happens

**Expected result:**
An alert is shown

### Brave Version

**about:brave info:**
0.22.103

**Reproducible on current live release:**
No

### Additional Information
Should be fixed in any build _after_ 0.22.105

**Comment by petemill** [comment]
Fixed with 0.22.108

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.108 https://github.com/brave/browser-laptop/commit/2ecddeb917bfae1ecbc5ed33606924628bc299d0
* libchromiumcontent: 65.0.3325.181
* muon: 6.0.2
