### ISSUE TITLE
Some scripts are broken. Mostly on login sites.

### ISSUE THREAD

**Issue by LethalManBoob** [brave/browser-laptop#13745]
For example. I cant click read more on most comment sections expect youtube and i cannot login to my ubisoft account. Ive tried changing settings. Nothing works so its not phishing protection or script remover.

**Comment by bsclifton** [comment]
Closing as there isn't enough information for us to look into it

@LethalManBoob if you're still experiencing issues, can you please open one issue per website (including steps so that we can verify the problem)? Thanks 😄

**Comment by LethalManBoob** [comment]
This was most likely the "run each tab as a separate process" As i found it
broke most things. Not sure. Its been too long.
