### ISSUE TITLE
add ability to change/remap/clear out any keyboard shortcuts using the about:config tool

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1374]

**Comment by rmoriz** [comment]
Besides custom shortcut options, Brave would benefit from locale-specific shortcuts. 

For example on OSX and German keyboard layouts, the shortcuts for "History Back/Forward" are very hard to type, they are ALT+CMD+5 or ALT+CMD+6 (we have to use ALT as modifier to get square brackets)

**Comment by dandart** [comment]
Possibly also add Mouse4/Mouse5 for back/forward like other browsers do.

**Comment by AL-JShen** [comment]
Scrolling by pressing down on the mouse wheel and dragging would also be really great (autoscrolling in Firefox).

**Comment by Bucko13** [comment]
Would be great to disable existing shortcuts too. I just ended up navigating away from a document I was editing twice because I wanted to delete some text.

**Comment by bsclifton** [comment]
@Bucko13 the good news is that our next release will get rid of the backspace button navigating :smile: I personally hate that myself and have had that happen too many times

(backspace shortcut was removed with https://github.com/brave/browser-laptop/commit/e89aa8a9bed20506a0e73fbaedd42599d4d22fce)

**Comment by Bucko13** [comment]
@bsclifton Perfect! Great news. Thanks for the quick reply.

**Comment by Jacalz** [comment]
+1 from https://community.brave.com/t/user-interface-customization/3221

**Comment by oharrison72** [comment]
+1

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/set-custom-keyboard-shortcuts/4186)

**Comment by kkomaz** [comment]
+1

**Comment by nkentNTIA** [comment]
+1

**Comment by LaurenWags** [comment]
+1 from community user who wants a different keyboard shortcut: https://community.brave.com/t/make-please-f3-search-on-page/3628

**Comment by LaurenWags** [comment]
+1 from community (various keyboard shortcut changes desired: https://community.brave.com/t/issue-small-bugs-found-in-first-couple-hours-of-using-brave/5075)

**Comment by srirambv** [comment]
+1 on disable auto scrolling. 
https://community.brave.com/t/hidden-customization-options-or-possible-suggestions/5866

**Comment by nipponaihito** [comment]
Any timeframe on this?

**Comment by frankclaassens** [comment]
Why is this taking so long? I just discovered brave and its amazing, but I simply can't live without backspace shortcut! I don't think I would be able to continue using it without the possibility of this being added, and soon.

Timeframe?

**Comment by bsclifton** [comment]
cc: @zentagonist

**Comment by frankclaassens** [comment]
Can we please get an ETA on this? I would really like to be able to use "Backspace" keyboard key to navigate back to the previous page. Based on https://github.com/brave/browser-laptop/issues/6156, it looks like you are planning on adding this support through customised shortcuts. I love Brave browser but my brain is hard-wired to constantly use this key and I find myself not able to use Brave without this feature.

Please can we get an update? @bsclifton @zentagonist

**Comment by bsclifton** [comment]
@frankclaassens it's hard to commit to a time frame- there are a lot of features fighting for priority right now.  But maybe @bradleyrichter or @jenn-rhim can help provide a mock-up?  I'd be willing to help someone if they wanted to attempt doing this 😄  Updating to add the `help wanted` tag

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/how-to-customize-keybinds/8278?u=eljuno

**Comment by Shought** [comment]
+1 from community https://community.brave.com/t/bookmark-bar-keyboard-shourtcut/8616

**Comment by blacktop** [comment]
I use Spectacle on OSX to manage my windows, but Command+Alt+Left (moves the window to the left pane) Also changes the tabs to the previous in Brave, so Brave flickers and I have to reselect the tab I was on.  So I went into OSX's keyboard shortcuts to fix it, but Brave doesn't respect the new mapping I made :cry:  I understand there is some disagreement about adding keyboard mappings to Brave, but I DO think it should at least respect the operating systems keymap??

Thanks for making an amazing browser... FIGHT THE POWER! 👊

**Comment by evvvritt** [comment]
'Pin Tab' keyboard shortcut please! 🙏

**Comment by m0se** [comment]
I found a little workaround, at least for those who just want to disable certain Shortcuts, to stop them from interfering with OS Shortcuts:

https://gist.github.com/m0se/f41ac86c623d67679e293571f3b9ca57

Configurability would of course be preferable, but this way I can finally start using Brave as main browser.

**Comment by rasdia** [comment]
I use a Swiss French keyboard on Windows 10. On this keyboard, the key combination used to add the @ sign (alt gr + 2) is the same as Brave's shortcut to opening a new tab.
(Thanks @m0se , but I'm not code-literate enough to get that workaround to work.)

**Comment by eljuno** [comment]
@rasdia that issue will be fixed in next release #12956. :)

**Comment by laurencesmithever** [comment]
https://github.com/brave/browser-laptop/issues/1374#issuecomment-346951434 - Same for me - I use Spectacle and have this issue.

**Comment by laurencesmithever** [comment]
cc: @bradleyrichter @jenn-rhim @eljuno ^

**Comment by shllg** [comment]
:+1:

**Comment by Coleej** [comment]
+1

**Comment by eljuno** [comment]
++ from community https://community.brave.com/t/requesting-input-customization/20411?u=eljuno

**Comment by Emmanux** [comment]
Much needed.

**Comment by bogdan-radocea** [comment]
I don't understand why this is such a big issue. Why can't you, the devs, add the option to customize the keyboard shortcuts? At least make the shortcuts consistent with the OS I'm running. Why is there that on linux if I press alt+1, or alt +2, etc, brave does not switch to the corresponding tab? Why do you use ctrl+1 or ctrl+2, which is the standard windows OS behaviour? and so on and so forth... I had high hopes that brave would replace firefox as my daily driver, but this is not the case.

**Comment by bsclifton** [comment]
@bogdan-radocea solving this is not a technical hurdle- it's a matter of prioritization unfortunately

I think the solution to this will come with `brave-core` (our new Chromium based UI that we're working hard on to replace the current Muon based UI). This has full extension support, meaning you could use something like [Shortkeys](https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck?hl=en) to change the shortcuts

Realistically, with our current Muon based browser (`browser-laptop`), we won't be fixing this. I'm going to mark as `wontfix` and add a label for `addressed-with-brave-core` since there would be a work-around available there (if Chromium lets you edit keyboard shortcuts, we'd get that too with `brave-core`).

**Comment by bsclifton** [comment]
Tracked in Brave Core with https://github.com/brave/brave-browser/issues/354
