### ISSUE TITLE
Switch browser certificate pinning to full cert pinning

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13752]
### Description

Switch browser certificate pinning to full cert pinning

**Comment by diracdeltas** [comment]
details? we should usually pin CAs, not full certificates

**Comment by bsclifton** [comment]
@NejcZdovc is this still needed? Not enough details here to understand the requirement, but if you would like to keep, let's please open an issue in [brave-core](https://github.com/brave/brave-browser)
