### ISSUE TITLE
When minimized window is re-opened, window state changes twice.

### ISSUE THREAD

**Issue by srcnalt** [brave/browser-laptop#13755]
**Have you searched for similar issues?**
Yes

### Description
When a maximized browser window is minimized and then clicked on it's icon to re-open again, window starts in full-screen on, then turns it off, then turns it on again, and this causes a flickering effect.

### Steps to Reproduce
  1. Launch Brave
  2. Maximize the browser window
  3. Minimize the browser window
  4. Click on Brave icon to re-open the window
  5. Observe the window buttons

**Actual result:**
Here is a video of the situation 8x slowed down, you can check the window buttons.
https://streamable.com/e6i58

**Reproduces how often:**
Every time without an exception.

### Brave Version

**about:brave info:**
Brave	0.22.13
V8	6.5.254.41
rev	a8cfb16
Muon	5.1.2
OS Release	10.0.10586
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	65.0.3325.181

**Reproducible on current live release:**
Yes

### Additional Info
This problem does not occur when the browser is full screen off then minimized and re-opened again.

**Comment by Tomatoshadow2** [comment]
I couldn't reproduce on Mac using Beta 22.106 or Release 22.16, might be a Windows only bug? cc @srirambv
