### ISSUE TITLE
Brave Shield "bug"? on DuckDuckGo

### ISSUE THREAD

**Issue by TheAresjej** [brave/browser-laptop#13757]
### Description
Brave shield blocks 2 scripts on DDG - "The search engine that doesn't track you." so either the DDG policy has changed or some new function is blocked

### Steps to Reproduce
Search for something on DDG e.g. https://duckduckgo.com/?q=Brave+download&ia=web

**Actual result:**
https://i.imgur.com/XwmAVr3.png

**Expected result:**
Zero blocked items?

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
I don't know...

**Comment by Liunkae** [comment]
Scripts blocked by the tracking blocker:
> https://duckduckgo.com/share/spice/amazon/1368/amazon.spice.js
https://duckduckgo.com/m.js?q=Brave%20download&a=ne6&l=wt-wt&cb=ddg_spice_amazon&i=B00DRDSL4Y,B00899D0HO&p=1

Looks like the search results contain a link to Amazon (result no. 12 for me). DuckDuckGo makes money with affiliate revenue from Amazon: https://duck.co/help/company/advertising-and-affiliates

A different query (e.g., https://duckduckgo.com/?q=GitHub&t=brave&ia=web) does not cause anything to be blocked. So my theory is that any search with results linked to Amazon will have these affiliate tracking scripts.
