### ISSUE TITLE
Cannot move tab between windows

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13759]
### Description

Moving tabs between windows produce unclickable tab.

### Steps to Reproduce

  1. Open new window and go to google
  2. Open second window
  3. Move the tab from first window to second window

**Actual result:**

Unclickable empty tab

**Expected result:**
Normal tab with the original website from first window

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

Yes

### Additional Information

![screen shot 2018-04-07 at 16 53 00](https://user-images.githubusercontent.com/537310/38456698-c9741c18-3a87-11e8-804f-5dca1c1e7fa2.png)

**Comment by bsclifton** [comment]
@raisty are you still experiencing this issue? We've had several related fixes
