### ISSUE TITLE
Privacy and Security risk - Downloads are logged in private tab

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13768]
### Description

If you download something in private tab, still it is logged in downloads.
Anybody can download the same data.

### Steps to Reproduce

  1. open new private tab
  2. download some data (avoid sensitive for purpose of testing)
  3. open downloads - you can find there your download even later

**Actual result:**

All downloads in private tab are logged

**Expected result:**
Not logged downloads in private tab

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162

**Reproducible on current live release:**

Yes

**Comment by a-one-d-one** [comment]
been working on this, not much progress as of yet but just leaving this as a disclaimer.

**Comment by bsclifton** [comment]
Fixed with [brave-core](https://github.com/brave/brave-browser)
