### ISSUE TITLE
Localize the AdBlock in Tamil 

### ISSUE THREAD

**Issue by ramsunvtech** [brave/browser-laptop#13766]
### Description
Tamil Locales are still in English for AdBlock.

### Steps to Reproduce
  1. Open `browser-laptop/app/extensions/brave/locales/ta/adblock.properties`

**Actual result:**
Current labels is in English.

**Expected result:**
AdBlock labels needs to localized to Tamil.

**Reproduces how often:**
NA

### Brave Version
NA

**Reproducible on current live release:**
NA

### Additional Information
I will localize one by one, once its get merged.

**Comment by bsclifton** [comment]
This can be done via signing up for the Transifex service and filling in the translations 😄 

More details here:
https://github.com/brave/browser-laptop/blob/master/docs/translations.md
