### ISSUE TITLE
Cant scroll through large folders on the bookmarks toolbar

### ISSUE THREAD

**Issue by xXZEROCSXx** [brave/browser-laptop#1377]
I exported my bookmarks from firefox if that is of any help.

**Comment by luixxiul** [comment]
Already fixed?

**Comment by cezaraugusto** [comment]
@luixxiul I tested here with v0.11.0 with both Bookmark Manager and Bookmark Toolbar and it was scrollable. Testing with OS X.

@xXZEROCSXx will close it for now. Let us know if this issue still persists with you.
