### ISSUE TITLE
Feature Request: "Always open in private tab" list in preferences.

### ISSUE THREAD

**Issue by srcnalt** [brave/browser-laptop#13770]
Right clicking on a private tab and adding the website to some always private list. So when the website is visited again via a link or directly from search bar, it opens in or switches to private tab right away.

**Comment by NumDeP** [comment]
+1 So technically bookmarked but segregated so when it is opened data doesn't reduce anonymity or mix other tabs' data. I believe this is also referenced here #12928

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/910
