### ISSUE TITLE
Request: Option to start Brave with tabs loaded

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13771]
### Feature Request
User _nishay_ on Reddit [has requested](https://www.reddit.com/r/brave_browser/comments/8are7e/unsuspend_tabs_on_browser_load/) a feature enabling the user to opt-into loading all tabs when Brave starts up. This impacts performance, but for users who don't typically have many tabs opened the impact may be minimal if even noticeable.

![image](https://user-images.githubusercontent.com/815158/38475103-194fa85e-3b6b-11e8-8eb1-0df46b3b8dba.png)

**Comment by absolux** [comment]
Or load only the active tab, the others will be reloaded when activated

**Comment by jonathansampson** [comment]
@absolux I believe you're describing the present behavior; Brave loads the active tab on startup. It subsequently loads the other tabs when they become focused.
