### ISSUE TITLE
Control+Left Arrow/Right Arrow kbd shortcuts not behaving on Windows in text fields

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1378]

**Comment by bbondy** [comment]
I just tried and it worked as expected for me going to the previous word.  Could you describe what you mean by not behaving?

**Comment by luixxiul** [comment]
Fixed already?

**Comment by bradleyrichter** [comment]
This was reported in about 3-4 zendesk tickets. If we can't reproduce, maybe it's fixed, or related to non-english language settings.

**Comment by cezaraugusto** [comment]
Related #1408
