### ISSUE TITLE
bookmark bar folder and file icons are misaligned when overflow indicator is visible

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13789]
### Test plan
See https://github.com/brave/browser-laptop/pull/13986

### Steps to Reproduce

  1. Bookmark many items and at least one folder
  2. Switch to favicons only
  3. Resize window to show overflow indicator from not showing overflow indicator

**Actual result:**
Folder and default favicon (i.e. document icon) jump a couple of pixels vertically.

**Expected result:**
Same alignment as when overflow indicator is not present

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.x single webview
0.23.x source
master

**Reproducible on current live release:**
No

### Additional Information
Caused by #13758

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
0.22.703 903b8d0d
libchromiumcontent 66.0.3359.139
muon: 6.0.8
