### ISSUE TITLE
New windows have pinned tab active, instead of New non-pinned tab

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13797]
### Steps to Reproduce

  1. Pin a tab
  2. Open a new window with cmd-n

**Actual result:**
The tab that has focus in the new window is the pinned tab

**Expected result:**
The tab that has focus in the new window is the new non-pinned tab

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.108

**Reproducible on current live release:**
No

**Comment by hugobuddel** [comment]
The same happens when a tab is dragged out of Brave, or when Brave starts: the rightmost pinned tab gets focus instead of the dragged tab or the new tab.

**Comment by petemill** [comment]
Should be fixed in 0.22.109

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.109 https://github.com/brave/browser-laptop/commit/5e4846eb66981a0b7b283ddf7d65a2721641f87d
* libchromiumcontent: 65.0.3325.181
* muon: 6.0.3
