### ISSUE TITLE
Hide mac black top bar when full screen

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1379]
Many people watch videos in FS view in their browser and we should respect "full screen view" and hide all of the UI chrome.

**Comment by bbondy** [comment]
we do hide it if you click on the full screen button on a video.

**Comment by bbondy** [comment]
Need more detail here

**Comment by bradleyrichter** [comment]
I think this was from before the youtube FS button fix. So I changed the title to address the black bar people have mentioned.

**Comment by luixxiul** [comment]
Might this be related with #1358?
