### ISSUE TITLE
Flash Plugin settings are not respected if flash is installed

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#13790]
Repro Steps:

1. Instal Flash Player.
2. Verify that flash player is disabled in `about:preferences#plugins`
3. Navigate to: https://helpx.adobe.com/flash-player.html 

Working animation in #5 indicates that flash plugin works.

<img width="967" alt="screen shot 2018-04-10 at 2 34 01 pm" src="https://user-images.githubusercontent.com/1903815/38585031-3fb7a380-3ccd-11e8-937d-e515f31c38b4.png">

<img width="922" alt="screen shot 2018-04-10 at 2 42 36 pm" src="https://user-images.githubusercontent.com/1903815/38585085-6fc2d82e-3ccd-11e8-965b-6656aed67550.png">

```
 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Comment by diracdeltas** [comment]
@jumde this is probably because we added Adobe as a flash special case exception. See `getDefaultPluginSettings`
