### ISSUE TITLE
Infinite loading spinner when detaching a loading tab (sometimes)

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13803]
### Steps to Reproduce

  1. Load a tab
  2. During load, detach the tab
  3. Tab in new window's loading animation is infinitely spinning

**Actual result:**
Load spinner of tab in new window does not stop when load is complete

**Expected result:**
Load spinner reflects current status of load

**Reproduces how often:**
~20%, depends on timing

### Brave Version

**about:brave info:**
0.22.106

**Reproducible on current live release:**
Unknown

**Comment by petemill** [comment]
Seems fixed with 0.22.700

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d* libchromiumcontent 66.0.3359.139
* muon: 6.0.7

**Comment by LaurenWags** [comment]
Reopening as I reproduced 3x using nytimes.com as the tab I tore off during loading using 0.22.702.

![13803](https://user-images.githubusercontent.com/28145373/39594754-9945ad0a-4edb-11e8-8eae-a7e1cc290f0d.gif)

**Comment by kjozwiak** [comment]
Reproduced it twice on Mint 18.3 x64 using the following STR:

* load `nytimes.com` and detach the tab into a new window via drag & drop
* load `nytimes.com` and detach the tab via right click on tab -> detach

**Comment by petemill** [comment]
I know why this is happening, and it is happening on the current release too. We are handling load 'start' and 'finish' (and 'error') in the renderer, and attaching the status property to the window frame, but if a load-finish comes to the old window (before the tab has finished moving to the new one), then the new frame object will not receive the updated load status. A solution to this would be to move load status to the browser state (tab object), or check for the current status when the frame is finally loaded in the destination window.
