### ISSUE TITLE
Make right mouse context menu customizable

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1380]
Would be great if users could add or remove certain right mouse context menu actions on their own.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-which-functions-should-right-mouse-context-menu-have/10066

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

**Comment by bulrush15** [comment]
I'm really just looking for these functions: 

## Right click on link

* Copy link. 
* Open link in new tab. 
* Open link in new window. 

## Right click on selected text

* Copy plain text. Very important not to get garbage when we copy and paste into Notepad or other text editor. 

## Right click on image

* Copy image to clipboard
* Copy image URL to clipboard
* If you right click on an image on an html page, it can open the image in a new tab. 

## Right click video or audio file

* Copy URL to clipboard
* Download media.

## Right click on web page not on any options above. 

* Copy URL to clipboard
* Screen cap whole page
* Screen cap visible portion of page. 
* Screen cap selection (user selects portion to capture to image).
