### ISSUE TITLE
Can't log into Binance.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13808]
### Description
Users report an inability to log into binance.com with Brave.

**Workaround**
Switching shields to _Allow all Cookies_ resolves the issue, suggesting this is related to cookies or localstorage.

### Reports:
- https://twitter.com/BrantBailey4/status/984149912521605120
- https://twitter.com/sci4me/status/984113669616361475
- https://twitter.com/AmarChhetri/status/983998288499281923
- https://twitter.com/Bencrypto23/status/983967626064904197
- https://twitter.com/CryptOrthoReb/status/983892573529034752
- https://twitter.com/cryptochuk/status/983823941167824907
- https://twitter.com/Cyebit/status/984447689579524096

**Comment by jonathansampson** [comment]
The issue may be with calls coming from resource.binance.com, which appears to be a CDN for the exchange.

**Comment by snyderp** [comment]
related but distinct, i'm not able to complete the registration captcha, likely b/c we block canvas readback by default

**Comment by gniezen** [comment]
FWIW, I have the same issue with logging into helpscout.net using Google SSO. Allowing all cookies works.Maybe this is expected - does SSO only work with 3rd party cookies?

**Comment by bsclifton** [comment]
Fixed in brave-core 😄 This was recently solved with https://github.com/brave/brave-browser/issues/1740
