### ISSUE TITLE
Add browser pref for "mail to:" links to open in prefered mail app or gmail, overriding system default setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1381]
Requested by a user through zendesk. Neat idea when we have time...

**Comment by patricktr** [comment]
Yes please. One time i clicked to allow inbox.google.com to handle protocol links, and now I cannot undo this. My system has Brave as the mailto handler, but within brave, it now defaults to google inbox, and I can't undo this.

**Comment by hammok** [comment]
+1 community

https://community.brave.com/t/how-do-i-link-up-my-email-so-i-can-use-the-email-links-on-web-pages/18440

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/781
