### ISSUE TITLE
c66 build crashes on launch

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13814]
### Description
When launching c66 build it crashes on launch each time.

### Steps to Reproduce

  1. Download from https://github.com/brave/browser-laptop/releases/tag/v0.22.662
  2. Attempt to launch
  3.

**Actual result:**
Brave Crashes
![screen shot 2018-04-12 at 9 43 59 am](https://user-images.githubusercontent.com/28145373/38681145-0bf63fb0-3e36-11e8-9650-39467c6205ef.png)

**Expected result:**
No Crash

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.662

**Reproducible on current live release:**
no

### Additional Information
Reproduced on MacOS, Linux, and Win by @kjozwiak

**Comment by darkdh** [comment]
fixed by muon 5.2.2

**Comment by btlechowski** [comment]
Verified Ubuntu 17.10
Version 0.22.664
Muon 5.2.4
