### ISSUE TITLE
drag and drop of a tab shows tab content as white

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13815]
### Description
Sometimes drag and drop of a tab results in the dropped tab content displaying as white. Seems fairly reproducible when using session tabs but is more intermittent when using normal tabs.

### Steps to Reproduce

  1. Launch 0.22.109 with a clean profile
  2. Close welcome tab
  3. Open a Session 1 tab and navigate to a site (I used twitter)
  4. Open a Session 2 tab and navigate to a site (I used twitter)
  5. Drag the session 2 tab from the window and drop it so a second window is created.

**Actual result:**
Window 2 tab content is white until you move the window. Clicking on the tab or tab content didn't do anything.  A reload will show the tab content.
![dnd-whitetab](https://user-images.githubusercontent.com/28145373/38691521-14453338-3e4f-11e8-9b3f-25887037390c.gif)

**Expected result:**
Tab content should be displayed.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.109
V8 | 6.5.254.41
rev | 5e4846e
Muon | 6.0.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
no

**Comment by petemill** [comment]
Should be fixed with 0.22.700

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
