### ISSUE TITLE
Dead tab - cannot get webContents by tab ID

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13810]
### Description
Found by @bsclifton 
With the below STR, a tab cannot be switched to, because we cannot retrieve the webContents by Tab ID, even though the webContents has not been destroyed.

### Steps to Reproduce from @bsclifton 
1. Visit http://www.benzworld.org/forums/17354970-post7.html
2. Click any of the Mercedes craigslist links there using middle click :smile:
2.5 Switch to that tab actually
3. You’ll be on craigslist for Seattle for a given car, URL bar will have focus
4. Click anywhere on the page to take focus out of URL bar (not sure if this matters or not)
5. Click back up in the URL bar, change to `craigslist.org` and hit enter
6. Page might load up (doesn’t always)
7. Switch tabs back to the BenzWorld one
8. Switch back to the craigslist tab

**Actual result:**
Craigslist.org tab is not displayed (still displays the previously-active BW tab)

**Expected result:**
Craigslist.org tab displays

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.109

**Reproducible on current live release:**
No

### Additional Information
`remote.getWebContents(tabId` calls (via IPC) `electron.webContents.fromTabID(tabId` which calls in c++ `return CreateFrom(isolate,
      extensions::TabHelper::GetTabById(tab_id));` which is resulting in a falsey return value.

**Comment by jonathansampson** [comment]
I think I ran into this today too:

![absent-tab-mini](https://user-images.githubusercontent.com/815158/39546459-1403a00a-4e1a-11e8-8416-32fcd403521e.gif)

``` 
Brave: 0.22.701 
V8: 6.6.346.26 
rev: 339ffd666e7c70b9b5e1b6d8b54f8b552e20f453 
Muon: 6.0.7 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Comment by bridiver** [comment]
fixed https://github.com/brave/muon/commit/1ac2b63bc26571484efe2bed0af6060f6b1a3640

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.706 e11b027
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
