### ISSUE TITLE
Scrollable Tab Previews

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13818]
### Description
A user requested the ability to scroll a previewed tab. Because you cannot leave tab (or else the tab would cease to be previewed), scrolling would likely have to take place on the tab itself. Scroll events could be intercepted, and transferred to the webview document itself.

### Additional Information
https://www.reddit.com/r/brave_browser/comments/8bgzct/scrolling_on_hover_preview_request/

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/275
