### ISSUE TITLE
automated webdriver tests for Tor tabs functionality

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13821]
we should add webdriver tests for Tor tabs

blocked on #13611

**Comment by diracdeltas** [comment]
fixed by 
bb87039

**Comment by LaurenWags** [comment]
@diracdeltas does this need a QA test plan or should it be marked `QA/no-qa-needed`?

**Comment by diracdeltas** [comment]
@LaurenWags i added no-qa-needed, thanks
