### ISSUE TITLE
Tab's first attach is not composited

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13827]
### Description
If we call `<webview>.attachGuest(guestInstanceId)` for a Tab that has never been attached / displayed before, then 50% of the time it won't be composited within the `<webview>`, even though `did-attach` will be received. If we detach and attach again, then it will be displayed correctly.

What would be great is either:
- IF this is a timing issue, know which event has to be received by the tab, before we should call `<webview>.attachGuest` with that Tab's guestInstanceId, in order to be 100% confidence that the attach will result in composition of the contents with the webview.
- Or, make sure that attachGuest will always result in composition of the contents with the webview, even if the contents has never been loaded yet.
- Or (least preferrably...) know which event, when emitted *after* did-attach is emitted, means that we should detach and attach again. This is least preferrable due to other timing issues that may occur in-between those stages, possibly greatly complicating the code (e.g. tab is moved to different window).

### Steps to Reproduce (1)

1. Start with fresh profile
2. CmdOrCtrl-click all sites on New Tab page
3. Wait for all sites to finish load
4. ctrl-tab to each site 1-by-1
5. Observe some sites do not render when switched to, but the previous Tab for that `<webview>` is shown.
_Note: the site may display after ~15 seconds_

### Steps to Reproduce (2)

1. Start with profile from STR(1)
4. ctrl-tab to each site 1-by-1
5. Observe some sites do not render when switched to, but the previous Tab for that `<webview>` is shown *and can be interacted with*.

**Reproducible on current live release:**
No

**Comment by petemill** [comment]
Another Windows issue is that when switching to a Tab, occasionaly the webview will initially display the last attached tab's contents for a couple frames before showing the newly-attached Tab, even though that last Tab has been detached for some time, and the `<webview>` was blank since detach.

**Comment by petemill** [comment]
Should be fixed via muon 6.0.5

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
