### ISSUE TITLE
Add a confirmation dialog for "Close Other Tabs" contextual menu action.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1382]
This action is not undoable and can be triggered accidentally.

**Comment by bbondy** [comment]
Users can undo closed tabs, I think a dialog would be a tad annoying here.  One other data point is that there is no confirmation in Chrome.

**Comment by bradleyrichter** [comment]
It would be useful if you had more then 20 that would be closed all at once. And a data point - we are better than chrome.  :  )

But anyway, low priority since you can reopen them one at a time.

**Comment by bbondy** [comment]
Yep agreed low priority and as long as it gives an option to not show anymore, all good with me. Thanks.

**Comment by luixxiul** [comment]
I'm trying like this:
````
  items.push({
    label: locale.translation('closeOtherTabs'),
    click: (item, focusedWindow) => {
      if (focusedWindow) {
        if (confirm(locale.translation('confirmcloseOtherTabs'))) {
          focusedWindow.webContents.send(messages.SHORTCUT_CLOSE_OTHER_FRAMES, tabKey, true, true)
        }
      }
    }
````

This surely works on Ubuntu, displaying a pop-up, but I'm getting this one to commit:
````
  /home/test/browser-laptop/js/contextMenus.js:412:13: 'confirm' is not defined.
````
Do I have to define 'confirm'? If you would you please tell me how to?

**Comment by bbondy** [comment]
I think you are looking for this:
https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowmessageboxbrowserwindow-options-callback

**Comment by luixxiul** [comment]
Nice, thanks!

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/912
