### ISSUE TITLE
Revert quarantine feature for macOS

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13826]
Companion issue to https://github.com/brave/browser-laptop/issues/13817

## Test plan
1. Download https://nodejs.org/dist/v8.9.4/node-v8.9.4.pkg
2. Open terminal and run `xattr node-v8.9.4.pkg`
3. Quarantine flag (`com.apple.quarantine`) should NOT be present

**Comment by bsclifton** [comment]
Manually created macOS build
1. `git checkout 0.22.x-promo`
2. `npm run build-package`
3. `cd Brave-darwin-x64/`
4. manually removed key `LSFileQuarantineEnabled` and value `true` from the following files using vim:
```
Brave.app/Contents/Frameworks/Brave Helper NP.app/Contents/Info.plist
Brave.app/Contents/Frameworks/Brave Helper.app/Contents/Info.plist
Brave.app/Contents/Frameworks/Brave Helper EH.app/Contents/Info.plist
Brave.app/Contents/Info.plist
```
5. Build package and passed proper signing parameters

**Comment by bsclifton** [comment]
Fixed binaries uploaded - see https://github.com/brave/browser-laptop/releases/tag/v0.22.19dev

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.20 https://github.com/brave/browser-laptop/commit/031ef465af97537ba889c91d4b35d0129e1bebbd
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.2
