### ISSUE TITLE
On macOS, switched-to tab is blank until window resize / move

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13825]
### Description
When performing `<webview>.attachGuest(guestInstanceId)` and going between different `guestInstanceId`s, very often the <webview> will finish attaching but still be white until the window is resized which forces it to paint the Tab's contents in the view. We have had success working around that with the following process:

1. call `<webview>.attachGuest(guestInstanceId)`
2. wait for `did-attach` on the requested guest's WebContents
3. nudge the `<webview>` with the following css:
    ```js
    function ensurePaintWebviewSubsequentAttach (webview, cb = () => {}) {
      webview.style.top = '1px'
      window.requestAnimationFrame(() => {
        webview.style.top = ''
        cb()
      })
    }
    ```
4. Wait 2x `requestAnimationFrame(cb)` for paint, but sometimes it takes 3x.

However, all beta users have experienced at least one time where the above is not enough, and the `<webview>` remains blank (usually white) when the tab is switched back to. It also is usually when the tab has already been displayed, and is being attached again.

We ideally require:
- A way to ensure that the `<webview>` will have the attached WebContents paint image composited with 100% confidence, instead of the <100% confidence we have with the above workaround

- An event (or similar, such as amount of frames) that will reliably let us know that the `<webview>` will be composited with the latest attached WebContents paint image.

#### Steps to Reproduce
One possible example reported in #13815

### Brave Version

**about:brave info:**

0.22.109

**Reproducible on current live release:**

No

**Comment by petemill** [comment]
Fixed with c66 / muon 6.0.5

**Comment by LaurenWags** [comment]
@petemill are there any STR other than those from https://github.com/brave/browser-laptop/issues/13815 ?

**Comment by petemill** [comment]
Just open the browser and switch to some new tabs @laurenwags

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.702 https://github.com/brave/browser-laptop/commit/e4a853d9990c62328a8a4320fec21f58c9cdc0c1
* muon 6.0.7
* libchromiumcontent 66.0.3359.139
