### ISSUE TITLE
time reporting for twitch isn't accurate

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13828]
### Description
Twitch videos/publishers used to be added to the ledger table right away with a time spent of 10s. Now they're not being added until a minute or 2 into the video/stream. This means that time reporting is no longer accurate. Also, when running LEDGER_VERBOSE=true, I'm seeing a syntax error.

### Steps to Reproduce

  1. Clean profile on 0.22.19, launch Brave with LEDGER_VERBOSE=true
  2. Enable payments.
  3. Navigate to a Twitch video/stream and start it if necessary.
  4. Switch back to ledger --> video is not listed in ledger table with time spent of 10s
  5. Look at terminal --> syntax error in terminal
  6. Continue to watch the video/stream for a few minutes

**Actual result:**
Twitch channel will eventually be added to the table, but the time on the ledger does not match the time spent on Twitch.

**Expected result:**
1. Video/stream should be added to the ledger table immediately with a time spent of 10s
2. no syntax error in terminal
3. Time spent on twitch video/stream should be accurate

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.19

**Reproducible on current live release:**
yes, reproduces on 0.22.13

### Additional Information
Syntax errors from terminal: https://gist.github.com/LaurenWags/f3c719367acc0486002995ae3ae1041c#file-twitch_syntax2-json

Time (eventually) logged by ledger was 3m 60s:
![screen shot 2018-04-13 at 10 57 44 am](https://user-images.githubusercontent.com/28145373/38742130-b5a81b9a-3f09-11e8-8acb-e8f0bde414d2.png)

But video was actually 5m 10s:
![screen shot 2018-04-13 at 10 58 12 am](https://user-images.githubusercontent.com/28145373/38742135-b930e8fa-3f09-11e8-8073-73dba47c6bf9.png)

**Comment by kjozwiak** [comment]
@NejcZdovc is this due to Twitch changing their API again? We had https://github.com/brave/browser-laptop/issues/13597 which was fixed in `0.22.13` and tested. I'm assuming we would have caught this if it was present at the time as Twitch was tested pretty well as it included several fixes.

**Comment by btlechowski** [comment]
Verified Ubuntu 17.10
Version 0.22.664
Muon 5.2.4
