### ISSUE TITLE
Bitwarden extension keeps turning off

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#13831]
### Description

Bitwarden keeps turning off so I need to go to settings and switch the extension off and then on again for it to work. I don´t know if it is the same issue with different extensions but I remember me and @jonathansampson talking about other users having the same issue on an extension update call. I could not find any issue for it so decided to create one now since it happens a lot more often now. 

### Steps to Reproduce
i have no clear steps on how to reproduce yet sadly 👎 

**Actual result:**
Extension disappears from the extension row and needs to be switched off and then on again to work. 

**Expected result:**
Should stay enabled all the time.

**Reproduces how often:**
Hard to tell but probably between 1 -3 times per week

### Brave Version

**about:brave info:**
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

Yes and has been for a couple releases

### Additional Information

cc @jonathansampson since he said a couple users on twitter had the issue

**Comment by jonathansampson** [comment]
@Jacalz Does the extension fail to work, or does the extension icon simply not render to the right of the address bar?

**Comment by Jacalz** [comment]
I believe that the extension fails to work and in the settings the switch seems to be turned on but it still says latest like it wa snot enabled 😅 @jonathansampson

**Comment by Jacalz** [comment]
![image](https://user-images.githubusercontent.com/25466657/39192355-48132902-47d9-11e8-9d40-704bde678cd8.png)

**Comment by Jacalz** [comment]
Sorry but this is starting to become very annoying 👎

**Comment by Liunkae** [comment]
I found the problem (at least for me)! Bitwarden gets disabled whenever Brave Payments is enabled. Like @Jacalz describes, it still shows the extension enabled in preferences, but the extension icon disappears. Turning the extension on and off solves the problem temporarily, but some Bitwarden functionality is still broken (like autofill).

Steps:
1. Enable Bitwarden.
2. Enable Brave Payments.
3. Restart Brave.
4. Notice that the Bitwarden icon does not appear at the top right.
5. Disable Brave Payments.
6. Restart Brave.
7. Notice that the Bitwarden icon appears as usual.

**Comment by Jacalz** [comment]
Looks like the above steps really didn't work for me sadly but I would say that I am fairly certain now that it might have something to do with payments 😕

**Comment by beardyjay** [comment]
Had this exact issues with Brave Payments and Bitwarden enabled at the same time. 

I followed what @Liunkae had done and disabled Brave Payments, this allowed Bitwarden to work as normal - the icon stayed and it would autofill again etc.
