### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by IsmailOmarGuelleh** [brave/browser-laptop#1383]
# Wikipedia bug
### Page resets sometimes...
When I open a random (larger) wikipedia page and scroll through it for a longer period of time it strangely reloads and resets me back to the top of the page. 

I think this is not intended (and it is definitely annoying)...

Brave pls fix

**Comment by luixxiul** [comment]
Please specify the URL of the page to detect if something is broken. Thanks.

**Comment by luixxiul** [comment]
Duping to #1766, closing
