### ISSUE TITLE
netflix does not work on c66 with clean profile

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13837]
### Description
Netflix does not work with a clean profile on 0.22.663. If you use an existing profile which already had Netflix installed prior to C66, it works.

### Steps to Reproduce

  1. Launch 0.22.663 with a clean profile
  2. Navigate to Netflix.
  3. Select 'Install and Allow' on the widevine prompt.
  4. Navigate to login page.
  5. You get the notification to install widevine (you should not be getting this).
  6. Select the checkbox and select Allow.
  7. Login.
  8. Try to start a show.
  9. Error is displayed.

**Actual result:**
Netflix does not work.

![c66-netflix](https://user-images.githubusercontent.com/28145373/38817758-0a8611a8-4167-11e8-8051-49dac81d25aa.gif)

![screen shot 2018-04-16 at 10 53 47 am](https://user-images.githubusercontent.com/28145373/38817761-0cb507ae-4167-11e8-9679-cc5ca95cabd1.png)

Also if you navigate to /Library/Application Support/brave/Extensions/WidevineCdm the folder is empty.

**Expected result:**
Netflix should not prompt you twice for install of widevine and you should be able to play a show.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.663
V8 | 6.6.346.23
rev | b35e0b5
Muon | 5.2.2
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.106

**Reproducible on current live release:**
No

### Additional Information
@btlechowski reproduced on Windows

**Comment by darkdh** [comment]
fixed in muon 5.2.3 by https://github.com/brave/muon/commit/d4effccfda02d2e35cd1a3d6d68a59a9e14d9a1f

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 with
0.22.664 https://github.com/brave/browser-laptop/commit/a98bd86fe2529eacd4d468d2e7d17f6d61ada608
Muon 5.2.4
libchromiumcontent 66.0.3359.117
