### ISSUE TITLE
''firewall blocked request" logged in console even though firewall is disabled

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13843]
follow up to #13119 : the firewalling filter logs blocking messages to the console even when it isn't actually blocked.  this may confuse some people.

test plan:
1. download an image and name it to rabbits.jpg
2. in the rabbits.jpg directory, start a localhost server: 'python -m SimpleHTTPServer 8000'
3. go to https://jsfiddle.net/c6y5qx5m/. you should see either 2 or
3 copies of rabbits.jpg loaded. you should not see any messages logged in the console related to firewall.
4. go to about:preferences#security and enable 'Application Firewall'
5. go to https://jsfiddle.net/c6y5qx5m/ in a new private or session tab
(to avoid loading cached files). now none of the rabbits.jpg images
should load.

**Comment by bsclifton** [comment]
@diracdeltas is this OK to remain in 0.24.x? (along with https://github.com/brave/browser-laptop/pull/13119) or should it be uplifted to 0.23.x?

**Comment by diracdeltas** [comment]
@bsclifton it should just be in the same release as #12671 since it's a follow-up
