### ISSUE TITLE
Make it easier to replace the current bookmarks toolbar with the bookmarks toolbar after importing bookmarks from another browser

### ISSUE THREAD

**Issue by jamesray1** [brave/browser-laptop#13849]
So I can import data from Firefox easily enough, but when I try to move all the data from Imported from Firefox -> Bookmarks Toolbar to Bookmarks Toolbar, all of the bookmarks inside Imported from Firefox -> Bookmarks Toolbar are cleared (the folder is empty) but the bookmarks are not visible in Bookmarks Toolbar. Restarting the browser doesn't help. Additionally the favicons don't show, you have to manually load each one in order for it to display thereafter.

I tried a couple of times, and on the third try I deleted the bookmarks toolbar contents, and selected and dragged the imported Firefox Bookmarks Toolbar folder contents to the Bookmarks Toolbar folder. This worked, however the imported contents are not the same as the latest bookmarks in Firefox.

When I exported Firefox bookmarks as an HTML and imported this file, the bookmarks were the latest and in the same order when in the Imported -> Bookmarks Toolbar folder, but when I moved them to the Bookmarks Toolbar folder, the order of the bookmarks changed.

**Comment by jamesray1** [comment]
What the bookmarks toolbar looks like after importing from Firefox and manually moving Imported from Firefox > Bookmarks Toolbar to the Bookmarks Toolbar with the latest version:

![screenshot from 2018-05-10 11-45-44](https://user-images.githubusercontent.com/16969914/39847964-b77e2b5a-5447-11e8-990b-3e1e85b31e52.png)

The favicons don't show by default, I had to enable them (this is because it's on Manjaro, previously I used Ubuntu).

![screenshot from 2018-05-10 11-46-51](https://user-images.githubusercontent.com/16969914/39848014-f553fe78-5447-11e8-8869-61f410bf1a66.png)

Still, it would be good if the favicons loaded without having to manually load each bookmark.

 
Brave: 0.22.14 
V8: 6.5.254.41 
rev: 0.22.22dev 
Muon: 5.1.2 
OS Release: 4.14.39-1-MANJARO 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Comment by rebron** [comment]
Closing. Looks like this is fixed in brave-core. https://brave.com/download-dev
