### ISSUE TITLE
chrome://crashes says crash reporting is disabled when it is not

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13842]
### Description
chrome://crashes says that crash reporting is disabled when it is actually enabled in about:preferences#advanced.

### Steps to Reproduce

  1. Launch 0.22.663 with a clean profile.
  2. Navigate to chrome://crash
  3. Navigate to chrome://crashes

**Actual result:**
chrome://crashes shows that crash reporting is disabled but if you go to about:preferences#advanced you can see that it is enabled. Also, if you navigate to brave stats the crash report will be there:

![screen shot 2018-04-16 at 3 15 34 pm](https://user-images.githubusercontent.com/28145373/38830496-877c0398-418a-11e8-96aa-ebbe4d2541f7.png)

![screen shot 2018-04-16 at 3 15 43 pm](https://user-images.githubusercontent.com/28145373/38830498-89d8bc3a-418a-11e8-9c36-42cdd5098a8c.png)

<img width="842" alt="screen shot 2018-04-16 at 3 16 19 pm" src="https://user-images.githubusercontent.com/28145373/38830501-8b9298fc-418a-11e8-873f-a41809fe141c.png">

**Expected result:**
chrome://crashes should not say crash reporting is disabled when it is enabled.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**

Brave | 0.22.663
V8 | 6.6.346.23
rev | b35e0b5
Muon | 5.2.2
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.106

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @btlechowski on Win

**Comment by darkdh** [comment]
fixed in muon 5.2.3 by https://github.com/brave/muon/pull/562/commits/9b3fa42a7d8ddf2833cad4e6644f5932273e305f

**Comment by btlechowski** [comment]
Verified Ubuntu 17.10 
Version 0.22.664
Muon 5.2.4
