### ISSUE TITLE
Messed Updater 

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#13847]
### Description
Brave prompted me with the update notification in the browser toolbar, as usual. When running the updater, I got some wrongly-encoded text and then a dialog with a strange message (see image)

![image](https://user-images.githubusercontent.com/56098/38849161-b19b7b2e-41bf-11e8-8f07-5347e34d827c.png)

**Comment by LaurenWags** [comment]
The dialog is expected (see https://github.com/brave/browser-laptop/issues/13826 and https://github.com/brave/browser-laptop/issues/13817) but the strange text is not.

**Comment by jonathansampson** [comment]
Looks like _Grab_ opened up an encoded file. After which action(s) did _Grab_ open?

**Comment by bsclifton** [comment]
Similar text showed for this user when logging into Dropbox with Google
https://github.com/brave/browser-laptop/issues/13558
