### ISSUE TITLE
Temporary extension while file is being downloaded (e.g. brdownload)

### ISSUE THREAD

**Issue by jSadoski** [brave/browser-laptop#13841]
### Description
While downloading a file, it would be helpful if a temporary extension could be applied (such as .brdownload). Once complete, the temporary extension could be removed. This would prevent accidental opening or execution of incomplete downloads. Other browsers, such as Chrome, have this type of functionality.

### Steps to Reproduce
Download any file.

**Actual result:**
While being downloaded, the file is named with its extension (eg foo.bar)

**Expected result:**
The file should have a temporary extension (for.bar.brdownload).

**Reproduces how often:**
Currently, this functionality does not exist.

### Brave Version

**about:brave info:**
Brave: 0.22.21 
V8: 6.5.254.41 
rev: 82c1e0e2617beb1de88e4195bd743b1a557b9d87 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Yes

**Comment by eljuno** [comment]
Same like #12164?
