### ISSUE TITLE
Surge of websites that promise to block/disrupt adblockers.  Some do what they say.

### ISSUE THREAD

**Issue by Blankbook2081** [brave/browser-laptop#13855]
https://blockadblock.com/  (Github: https://github.com/sitexw/BlockAdBlock )

https://getadmiral.com/

https://www.theverge.com/2016/11/2/13502458/twitch-video-ads-can-avoid-ad-blockers

https://easybib.com
(Twitch ads are still dodging Brave, I'm wondering if they got some sort of anti-adblock technology)

In order for Brave to function as normal, it is going to have to join the metaphorical space race of adblock vs anti-adblockers. blockadblock, admiral, and twitch are some websites that are fighting it. Easybib.com can also detect Brave and prevent adblocking users from using the site.

[Untested, but apparently The Zuck(Facebook) can go through your adblocker as well? https://www.theverge.com/2016/8/9/12412854/facebook-will-start-showing-ads-even-if-you-have-an-ad-blocker)
_____
https://reek.github.io/anti-adblock-killer/ 
This is an example script that allegedly prevents these sort of sites from detecting the adblocker.

**Comment by jonathansampson** [comment]
I took a look at blockadblock.com, and it appears as though they use a hefty amount of array-coercion arithmetic to fly under the radar. Their code is inline, on the home page, so it cannot be blocked by any request-filtering.

**Comment by Blankbook2081** [comment]
Yes, there is quite a ton of "[][][][][][]]]][[["s in there.

**Comment by Blankbook2081** [comment]
![image](https://user-images.githubusercontent.com/38046315/38910613-265e7c30-4298-11e8-9f51-451f111eabdb.png)

![image](https://user-images.githubusercontent.com/38046315/38910623-321541f8-4298-11e8-8776-f506250035ce.png)


In Easybib's particular case, they try and feed you 30 trackers and ads, and they can notice youre blocking ads, so they say "fine, you get one citation, but next time you aren't using our site unless you whitelist us"


The easybib (VERSION 2) update appears to be bugged in that while it knows you have an adblocker it doesn't bar you from the site as of yet. Just a note.

**Comment by bsclifton** [comment]
cc: @lukemulks

**Comment by TheRealKnurft** [comment]
I just wrote this article to discuss the whole GetAdmiral anti-adblock blocker detection thing. It appears as disabling javascript disables the detection too. If only we could inspect JavaScript and block certain scripts with specific code in it, we could block all JS that is related to any anti-adblock company. :)

[https://www.itexperience.net/2018/12/24/howto-bypass-admiral-adblock-detection/](url)

**Comment by bsclifton** [comment]
Closing as there is nothing actionable we can do (only recommendations) and also because this repo is deprecated. If someone wanted to create an issue for the new version of Brave (https://github.com/brave/brave-browser) with more actionable steps, I'd definitely encourage that
