### ISSUE TITLE
Brave does not open hyperlinks if there aren't any windows open

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13859]
### Description
When Brave is set as your default browser and it is running, but there aren't any open windows, if you click on a hyperlink the hyperlink does not open. This makes it look like Brave doesn't work. 

Reported via community: https://community.brave.com/t/updating-macos-from-0-22-13-to-0-22-21/19915/7

### Steps to Reproduce

	1.	Have Brave as your default browser.
	2.	Launch Brave but close any open windows (Brave is still running, note black dot below the icon in the dock).
	3.	Click on a hyperlink in a calendar app (or slack, etc). 

**Actual result:**
Hyperlink does not open. Workaround: Navigate to File > New Window or right click on the icon in the dock and select New Window. New window displays with two tabs: a new one and the hyperlink you selected is the 2nd tab within the new window.

**Expected result:**
Hyperlink should open.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.22

**Reproducible on current live release:**
Yes, was last working in 0.21.24 and stopped working in 0.22.13

### Additional Information
Seems like maybe it could be related to https://github.com/brave/browser-laptop/issues/13689 but the fix for this one does not resolve the reported issue (checked with 0.22.109)

After this is resolved, should also verify that this works with Brave open or closed, windows open or no windows open.

**Comment by LaurenWags** [comment]
Removed macOS label - linked test plan was recommended to be checked on all platforms.

**Comment by janpeeters70** [comment]
Thanks for fixing this!
