### ISSUE TITLE
Asking for admin password

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#13857]
### Description
Brave installed in the ~/Applications folder on MacOSX is asking for administrative permissions. If installed in that folder instead of /Applications, it's because I do not wish to give Brave (or any app for that matter), any administrative permissions.

### Steps to Reproduce
  1. Install Brave
  2. Wait for some new release
  3. Observe the popup below:

**Actual result:**
<img width="492" alt="screen shot 2018-04-18 at 11 13 15" src="https://user-images.githubusercontent.com/37633593/38947595-8193ebd2-42fa-11e8-99e5-45d24eac6446.png">

**Expected result:**
Maybe a popup that suggest manually upgrading, or better an upgrade that does not necessitate administrative privileges.

**Reproduces how often:**
Multiple times a day. I suppose installing the latest version solves the problem, until another new one is released?

### Brave Version
0.22.21

**Reproducible on current live release:**
Not sure to understand this. I suppose, yes?

### Additional Information
I love Brave.

**Comment by jonathansampson** [comment]
May be related to this issue: https://github.com/brave/browser-laptop/issues/2184
