### ISSUE TITLE
'www.' URL normalization code is not correct

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13858]
there are a bunch of places in the code that call something like `host = host.replace('www.', '')`, presumably for the purpose of considering 'www.example.com' and 'example.com' to be equal. 

this doesn't work on URLs like `wowww.com` (which turns into `wocom`).

**Comment by diracdeltas** [comment]
this is done in app/common/lib/suggestion.js and app/extensions/brave/content/scripts/adInsertion.js; the latter could be a potential security issue

**Comment by bsclifton** [comment]
@catilac @diracdeltas any manual testing required? It seems everything is covered by automated tests 😄

**Comment by diracdeltas** [comment]
@bsclifton :+1:
