### ISSUE TITLE
Brave menu items which open tabs do so in minimized window

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13865]
### Description
Brave menu items will open a tab in a minimized window, but will not show that window, making it seem like nothing has happened.

### Steps to Reproduce

  1. Minimize all Brave windows (1 window is fine)
  2. Cmd-tab to Brave (macOS)
  3. Choose a menu item which creates a tab (New Tab, About Brave, Preferences)

**Actual result:**
Nothing happens (the tabs are created in the minimized window)

**Expected result:**
The window that the tabs are created in is restored and focused

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.22

**Reproducible on current live release:**
Yes, and 0.21.x (and before most likely)

### Additional Information
This was fixed as a result of the fix for #13859 and #13860

**Comment by LaurenWags** [comment]
Removed macOS label - linked test plan was recommended to be checked on all platforms.
