### ISSUE TITLE
Duplicate bookmark folder after sync

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13869]
### Steps to Reproduce

  1. Clean install same version of browser on two different platforms(Linux and Windows)
  2. On Linux create sync group
  3. On Windows joint the sync group
  4. On Windows open youtube.com and bookmark it
  5. On Windows create bookmark folder named 'test'
  6. Move the bookmark(4.) to the bookmark folder

Note:
tested on 
P1: Linux
P2: Windows

**Actual result:**
Bookmark is duplicated. It may take some time before it happens.
![image](https://user-images.githubusercontent.com/34715963/39008725-c64e4cbc-4409-11e8-98e6-b1c6cad1abfe.png)

**Expected result:**
Only one bookmark folder

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.664 
V8: 6.6.346.24 
rev: a98bd86fe2529eacd4d468d2e7d17f6d61ada608 
Muon: 5.2.4 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```

cc @LaurenWags @kjozwiak @srirambv

**Comment by btlechowski** [comment]
Reproduced on v0.22.22

**Comment by LaurenWags** [comment]
reproduced on macOS using a macOS as p0 and Linux as p1.
