### ISSUE TITLE
unable to open new window from dock icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13860]
### Description
When Brave is running, but there aren't any open windows, you used to be able to click on the dock icon to open a new window. This no longer works.

Reported via community:
https://community.brave.com/t/browser-version-0-22-13-browser-window-not-opening-after-initial-open/19232
https://community.brave.com/t/updating-macos-from-0-22-13-to-0-22-21/19915/7

### Steps to Reproduce

  1. Launch Brave.
  2. Close any open windows (Brave is still running, note black dot below the icon in the dock).
  3. Click on the Brave icon in the dock. 

**Actual result:**
Nothing happens. It looks like Brave isn't working. Workaround: Navigate to File > New Window or right click on the icon in the dock and select New Window. New window displays.

User from community provided this video: https://www.youtube.com/watch?v=mb2ZmXpXw58&feature=youtu.be

**Expected result:**
If Brave is running but you don't have any open windows, clicking on the icon in the dock should open a new window.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.22

**Reproducible on current live release:**
Yes, was last working in 0.21.24 and stopped working in 0.22.13

### Additional Information
Seems like maybe it could be related to https://github.com/brave/browser-laptop/issues/13689 but the fix for this one does not resolve the reported issue (checked with 0.22.109)

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 with
0.22.665 https://github.com/brave/browser-laptop/commit/bc13ab63f87b22dce366175927ffef54cb5cd201
Muon 5.2.5
libchromiumcontent 66.0.3359.117

**Comment by LaurenWags** [comment]
Removed macOS label - linked test plan was recommended to be checked on all platforms.

**Comment by bsclifton** [comment]
+1 from my dad on this one. Thanks for the fix, @petemill 😄👍

**Comment by janpeeters70** [comment]
Thanks for fixing this!
