### ISSUE TITLE
URL Heart (publisher toggle) button should be able to include sites outside of minimum requirements

### ISSUE THREAD

**Issue by ryanml** [brave/browser-laptop#13879]
### Description
Previously discussed with @NejcZdovc & @bsclifton, related to: #12675 

Currently, the publisher toggle button in the navigation bar (heart) functions only as an inclusion toggle, that is:

It does not add a site to the ledger if it is not already in it, it only can pin and unpin sites that are already in the ledger.

The suggestion is that it is able to include sites from the ledger entirely. For example:

Navigating to news.ycombinator.com, with minimum inclusion times set 1 minute long with 5 visits, a user should be able after only a few seconds have passed, to click the publisher toggle and see ycombinator.com in the ledger 5 minutes total time, and 5 visits.

From that point on, the publisher toggle will then retain its current functionality of acting as a pinned state toggle. Users should navigate to about:preferences#payments if they wish to remove the site from payments.

It seems natural that this button drives control of what the user would like to see in the ledger.

### Additional Information
Currently the button has three states, the language of them here:
1. **Site not present in the ledger** -> _"Publisher is not yet added to the ledger, because it doesn't meet criteria yet"_ (No action taken on click, suggested feature would include publisher in the ledger)
2. **Site present in ledger, pinned** -> _"This publisher is enabled for payment, click to disable"_ (Site unpinned on click)
3. **Site present in ledger, unpinned** -> _"Click to enable this publisher for payments"_ (Site pinned on click)

cc: @bradleyrichter for feedback about the issue in general, as well as the new language for the hover states

**Note: This has a cross dependency with #13856**
The code for a manual addition outside of set minimum requirements will need to be leveraged for this feature

If viewing this functionality is desired, it can be viewed in [this branch](https://github.com/ryanml/browser-laptop/tree/ledger-heart-fix) (This would be rebased with #13856 once it gets merged)

**Comment by btlechowski** [comment]
The formula for time spent on the site is: minimum page time * minimum number of visits.
It seems to be done by design.

Verified on Ubuntu 17.10 x64
0.22.703 903b8d0
libchromiumcontent 66.0.3359.139
muon: 6.0.8
