### ISSUE TITLE
Brave Payments keep reseting contribution date. Also history is missing

### ISSUE THREAD

**Issue by entity279** [brave/browser-laptop#13878]
### Description

The Brave payments never happen anymore. They seem to have their date reset everytime the browser is updated. 
This used to work, namely I had a payment happen for me back in March.
Beyond the payments not happening, the history of the payment I made seems to have dissapeared.

Note that I've only updated the browser when it itself promted me to do so. I had not performed any cleanups or manual deletions (at least not intentionally)

### Steps to Reproduce

  1 Check next contribution date (say it were 10 May)
  2. Accept the promt to download a Brave updated (say the date 'today' is 20 April)
  3. Check next contribution date after this update

**Actual result:**

The contribution date is now 20 May

**Expected result:**
The contribution date should still be 10 May

**Reproduces how often:**

Everytime, after a past update

### Brave Version

**about:brave info:**

Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

...
### Additional Information

...

**Comment by NejcZdovc** [comment]
@bsclifton yes, closing as dupe
