### ISSUE TITLE
'click to inspect' button missing from devtools

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13870]
### Description
When you open devtools there should be a 'click to inspect' button, but this is missing in c66. Found by @petemill 

### Steps to Reproduce

  1. Open devtools.
  2.
  3.

**Actual result:**
Click to inspect button is missing. 
top is Brave, bottom is Chrome:
![image 1](https://user-images.githubusercontent.com/28145373/39014765-4f51391e-43e9-11e8-9e30-81469f0f37cf.png)

**Expected result:**
click to inspect button should be present.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.664

**Reproducible on current live release:**
no

**Comment by darkdh** [comment]
fixed in muon 5.2.6 by https://github.com/brave/muon/commit/c40ce82f8f5ecb82675c94af2a1351286bcc7619
