### ISSUE TITLE
'always ask' and 'always block' autoplay options broken

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13871]
### Description
Videos always autoplay even if 'always ask' or 'always block' is the global setting.

### Steps to Reproduce

Scenario 1
  1. Navigate to about:preferences#security. Set Autoplay Media to 'Always ask'.
  2. Navigate to a site with a video. (ex. cnet, youtube, etc)
  3. Verify you receive the notification banner with Allow/Deny and the 'Remember this decision' checkbox.
  4. Verify all options on the banner work as expected.

Scenario 2
  1. Navigate to about:preferences#security. Set Autoplay Media to 'Always deny'.
  2. Navigate to a site with a video.
  3. Verify you do not receive the notification banner with Allow/Deny and the 'Remember this decision' checkbox.
  4. Verify video is blocked from playing.
  5. Verify you can play the video manually.

Scenario 3
  1. Navigate to about:preferences#security. Set Autoplay Media to 'Always allow'.
  2. Navigate to a site with a video that would play automatically.
  3. Verify you do not receive the notification banner with Allow/Deny and the 'Remember this decision' checkbox.
  4. Verify video plays automatically.

**Actual result:**
Videos always autoplayed

**Expected result:**
Setting should be respected.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22x-cr66

**Reproducible on current live release:**
no

**Comment by srirambv** [comment]
Still broken on 0.22.667. Always ask setting not respected 
![13871](https://user-images.githubusercontent.com/17010094/39201063-dc8db872-47bb-11e8-958e-20acc5c56b79.gif)

**Comment by srirambv** [comment]
Working as expected. Closing the issue

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 with
0.22.667 https://github.com/brave/browser-laptop/commit/0433b26a03c8daf9b181057cd2ffa7b530496faf
Muon 5.2.6
libchromiumcontent 66.0.3359.117
