### ISSUE TITLE
sometimes sites show up twice in ledger

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13875]
### Description
Reported via community: https://community.brave.com/t/issue-with-brave-payment-menu-showing-locked-sites-twice/20205

User has some YT sites pinned with a set contribution amount. Some of these sites show up again in their table as 'unpinned' (with 0 contribution %)

### Steps to Reproduce
Unknown so far, needs additional information.

**Actual result:**
from community post:
![chugwig](https://user-images.githubusercontent.com/28145373/39053997-7eb64bc8-447e-11e8-86b1-eead8b48bf7e.png)

**Expected result:**
Sites to only display once in table

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
This happens because we have two recording in the table. One with user name `youtube#channel:MrMuselk` and one with channel ID `youtube#channel:UCd534c_ehOvrLVL2v7Nl61w`

**Comment by bsclifton** [comment]
@NejcZdovc is there a fix in place yet? Do we want to include a fix with the Single Webview milestone?

**Comment by NejcZdovc** [comment]
no fix yet, just found out what is going on few minutes ago, will work on a fix tomorrow

**Comment by NejcZdovc** [comment]
+1 from #13939

**Comment by NejcZdovc** [comment]
probably will be fixed with https://github.com/brave-intl/bat-client/pull/59
