### ISSUE TITLE
Anti-adblocking countermeasure - blocking content on windowscentral.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#13881]
### Description

 - Anti-adblocking countermeasure implemented on windowscentral.com
 - Users running ad blockers (brave included) receive a content blocking message with a disable/remove ad blocking request. 
 - Likely fixable via filter rule for blocking detection / countermeasure script. 

### Steps to Reproduce

  1. Go to https://www.windowscentral.com/uber-and-youtube-progressive-web-apps-pwa-pop-microsoft-store
  2. See blocking message. 
  3.

**Actual result:**

Blocking message.

**Expected result:**
Content.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

yes

### Additional Information

 - identify blocking detection and message script
 - test custom filter rule to block detection script (custom filter rules can be tested in `about:adblock` )
 - once test is confirmed, add custom filter to custom filter list. 
 - Needs investigation.

**Comment by lembitk** [comment]
1. Went to https://www.windowscentral.com/uber-and-youtube-progressive-web-apps-pwa-pop-microsoft-store w/ Brave v0.23.31 (rev 3148ace) on Win 10 x64.
1. Saw content.

The issue can be closed, probably.

**Comment by bsclifton** [comment]
@lembitk thanks for verifying! I believe this was fixed when we updated our ad-block definitions (also including the EasyPrivacy list for example)
