### ISSUE TITLE
Using Brave over several days with a lot of tabs can cause a freeze

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#13885]
### Description

After working with three days without restarts and with many tabs, Brave froze.

### Steps to Reproduce

  1. Work at least 3 days with Brave (youtube, web browsing), open many tabs (at least 50)
  2. Sometimes can absolutly froze
  3. Need restart of Brave

**Actual result:**

Frozen

**Expected result:**
Performance speedup / fix

**Reproduces how often:**

After 3 days, sometimes

### Brave Version

**about:brave info:**

 
Brave: 0.22.13 
V8: 6.5.254.41 
rev: a8cfb160479f1d00d0769368eb440030182bb83b 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

yes

### Additional Information

![screen shot 2018-04-21 at 16 30 19](https://user-images.githubusercontent.com/537310/39085435-7b7caccc-4582-11e8-8195-985b4529aa62.png)

**Comment by bsclifton** [comment]
May be solved with https://github.com/brave/browser-laptop/pull/13783

@raisty you're welcome to try our latest BETA release. There are other known issues, but this one in particular should be fixed (or much better)
https://github.com/brave/browser-laptop/releases/tag/v0.22.109beta

**Comment by bsclifton** [comment]
Closing as there hasn't been an update and some of our recent updates should have fixed some aspects of this behavior

Please reopen if this still happens and there are more details that would help us troubleshoot. Thanks!
