### ISSUE TITLE
credential prompt for basic authenticaion not being displayed

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13883]
### Description

When attempting to access a website/FTP server that's using basic authentication, the credentials prompt never appears.

### Steps to Reproduce

  1. Open `0.22.665` bc13ab6
  2. Load `ftp://ftp.dlptest.com` (should receive a credential prompt)
  3. u: `dlpuser@dlptest.com` p: `eiTqR7EMZD5zy7M`

You'll notice that the basic authentication credential prompt isn't being displayed.

**Actual result:**

Users aren't being prompted when visiting a website/FTP server that's using basic authentication.

**Expected result:**

When visiting a website/FTP server that's using basic authentication, users should be prompted with a credentials modal.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.665 
V8: 6.6.346.24 
rev: bc13ab63f87b22dce366175927ffef54cb5cd201 
Muon: 5.2.5 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```

**Reproducible on current live release:**

No, currently working as expected in `0.22.22` 6303310 which is the latest released version.

### Additional Information

Found and reproduced by @bridiver.

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/browser-laptop/commit/12f8efc3c8f4daed01777e3692d553a189a43ae2
