### ISSUE TITLE
Add support for Extensity browser extension

### ISSUE THREAD

**Issue by sakibarifin** [brave/browser-laptop#13886]
This is a feature request for brave browser to add support for Extensity, a chrome browser extension that can be used to enable or disable extensions very fast and have extension profiles. 

Adding support for this extension would be very helpful for people with a large number of extensions. It makes it easier to manage them. It is a very popular extension with 283,786 users [at the moment this issue was posted].

Chrome Webstore Link: https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser), (which is just around the corner), we should have full support for extensions. Stay tuned 😄
