### ISSUE TITLE
Brave new tab photography picture proposal

### ISSUE THREAD

**Issue by lefevred** [brave/browser-laptop#13899]
Hello,

as suggested by the community, I'm opening an issue (https://community.brave.com/t/suggest-background-pictures-of-new-tabs/17873)

### Description
I’ve seen beautiful photographies when opening a new tab. There is the credit for each picture, which is a really good thing.
How can we suggest some photographers, to have some new pictures in the new tabs ?

Best regards,
Doff

**Comment by bsclifton** [comment]
cc: @bradleyrichter @jenn-rhim @alexwykoff @jamesmudgett

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/935
