### ISSUE TITLE
Keyboard shortcuts doesn't work when the keyboard is not English on OSX

### ISSUE THREAD

**Issue by lonormaly** [brave/browser-laptop#13902]
### Description
Keyboard shortcuts doesn't work when the keyboard is not English on OSX

### Steps to Reproduce
1. Switch to foreign language on the keyboard.
2. Use Cmd+C to copy and Cmd+V to paste

**Actual result:**
Shortcuts doesn't work

**Expected result:**
(as in rest of the OS): Copy Paste (and rest of the shortcuts) should work.

**Reproduces how often:**
Consistently

### Brave Version

**about:brave info:**
Name | Version
Brave | 0.22.22
V8 | 6.5.254.41
rev | 6303310
Muon | 5.1.2
OS Release | 17.5.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Comment by sliday** [comment]
I can confirm the issue, unfortunately. Shortcuts (e.g. CMD+T, CMD+L. CMD+C, CMD+V) are not recognised when non-English layout is selected.

**Comment by sliday** [comment]
Still a problem. Very annoying.

**Comment by lonormaly** [comment]
Agree, really frustrating...

**Comment by DKunin** [comment]
Same here.

Not sure how to approach fixing this.

**Comment by nyngwang** [comment]
Same here. We need this. Why close it.

This make me want to change back to Safari.

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/11908
