### ISSUE TITLE
http://rabb.it says WebRTC is disabled?

### ISSUE THREAD

**Issue by DaTechnoKing** [brave/browser-laptop#1391]
Is there a way to white list this site? It's the best way to watch netflix with somebody synced up so far.

**Comment by diracdeltas** [comment]
We allow webrtc for now and it works on most sites; not sure why rabb.it is not triggering the permission prompt.

**Comment by luixxiul** [comment]
Was this fixed with #260?

**Comment by diracdeltas** [comment]
shouldn't have been affected by #260.  however, when i go to rabb.it now, it doesn't say that webrtc is disabled anymore. please reopen if you still see that issue.
