### ISSUE TITLE
Impossible to allow flash in preference

### ISSUE THREAD

**Issue by hyrule12** [brave/browser-laptop#13917]
### Description
https://imgur.com/9hEFs8r

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**https://imgur.com/9hEFs8r**

 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

**Comment by hyrule12** [comment]
https://imgur.com/XXtwaat

Crunchyroll is not working

**Comment by bsclifton** [comment]
@hyrule12 please check out our Flash troubleshooting guide here:
https://community.brave.com/t/flash-isnt-working-audio-or-video-is-not-working/14

I'll close this issue for now- please re-open or comment if you have any additional questions. Thanks 😄
