### ISSUE TITLE
Can't right-click and drag to draw arrows on lichess.org

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#13921]
### Description
The lichess.org UI supports a right-click and drag gesture to draw arrows for analysis.  This doesn't work in Brave.

### Steps to Reproduce

  1. Go to https://lichess.org/analysis
  2. Right-click and drag from one square to another
  3. Note that no arrow is drawn

**Actual result:**

No arrow is drawn, only a circle around the source square from the initial mousedown event.

**Expected result:**
The circle should go away as soon as you drag over to another square, and an arrow should follow your cursor to the other square.

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**

Yes

**Comment by snyderp** [comment]
note able to recreate in the beta
