### ISSUE TITLE
Make Brave compatible with GDocs by default (TLD+1 for HTTP Referer header to fix Google sites)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13922]
This will fix:
   - docs.google.com, documents don't load by default.
   - hangouts in mail.google doesn't send messages.
   - hangouts in inbox.google doesn't send messages.

------

get eTLD+1 of domain
get eTLD+1 of subresource
If they match exactly, then don't clear Referer header

cc: @davidtemkin @flamsmark

**Comment by bsclifton** [comment]
Possibly related issues:
Open In Google Docs Doesn't Render, File Appears #10173
Google Docs clipboard not available #5709
Ctrl-right arrow / left arrow in Google Docs navigates browser instead of moving cursor
Clicking "to get sharable link" doesn't work with Google, does with github #6373

**Comment by bsclifton** [comment]
This may have already been fixed by @diracdeltas in 0.24.x with https://github.com/brave/browser-laptop/pull/13820. Will need to confirm

**Comment by diracdeltas** [comment]
Pretty sure i already fixed this

**Comment by diracdeltas** [comment]
@bsclifton this line changed it to use eTLD+1 instead of full domain for referer block: https://github.com/brave/browser-laptop/pull/13820/files#diff-8a9bac13ef6264feb2b6da7c18d86b3cR283

**Comment by diracdeltas** [comment]
marking as dupe of https://github.com/brave/browser-laptop/issues/13779

**Comment by bsclifton** [comment]
@diracdeltas it seems this would be fairly easy to uplift to 0.23.x - are there any challenges you see in doing that?  If not, I can take care of uplifting it 😄

**Comment by diracdeltas** [comment]
@bsclifton sgtm

**Comment by edmundlaugasson** [comment]
I can confirm that Google Drive documents do not render properly.

Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71
