### ISSUE TITLE
Brave stops displaying pages after few minutes on Linux

### ISSUE THREAD

**Issue by IIIIIHIIIII** [brave/browser-laptop#1392]
After few minutes if i open a website in a new tab, it loads up however nothing is displayed.

![Screenshot](https://i.imgur.com/qEZnGp0.png)

OS: Arch.
Brave: 0.9.1

**Comment by krua** [comment]
I have same problem with IIIIIHIIIII  when open the websites with Brave browser. 

![brave1](https://cloud.githubusercontent.com/assets/11352023/14738276/d8ae55b0-08aa-11e6-85c9-d2777b8ccd2a.png)

All tabs in this picture have the same problem.

OS: Linux Mint 17.3 (64 bit)
Brave : 0.9.1

**Comment by luixxiul** [comment]
Closing for now. If you still encounter the same problem on the latest version please leave a comment to reopen the issue, thanks.

**Comment by krua** [comment]
![brave 0 9 6](https://cloud.githubusercontent.com/assets/11352023/15296733/ef17a99a-1bc0-11e6-922e-28db42128a01.png)

Unfortunately this problem still there, I have upgraded my Brave browser to version 0.9.6

OS: Linux Mint 17.3 (64 bit)

**Comment by luixxiul** [comment]
Will you please open devtool with Shift+Ctrl+I and paste the output on Console here? Thanks.

**Comment by krua** [comment]
I'm sorry for saying that I can't reproduce the problem. A few minutes after I read your reply, I tried to open several web pages and Brave can open those web pages normally, It seem problem has been fixed. Nevertheless, this is the Console output when I opened theverge.com:

https://cdn0.vox-cdn.com/javascripts/lib/advertisement.v6fdc11c.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://ad-cdn.technoratimedia.com/smartwrapper/81065/1027/sw.min.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://s.skimresources.com/js/66960X1514734.skimlinks.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://cdn.krxd.net/controltag?confid=JImcjrMY Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://tags.api.umbel.com/lrjhazrpqbgtnrij/w.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://c.amazon-adsystem.com/aax2/amzn_ads.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://plus.google.com/js/client:plusone.js?onload=chorusAuthGPlusRender Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://js.moatads.com/essencedigital34895338176918191/moatcontent.js?loyalty_bsg=1&avgsestime_bsg=0&firstimp_bsg=1&referral_bsg=www.google.com Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://cfs2.uzone.id/cfspushadsv2/request?id=1&enc=telkom2&params=4TtHaUQnU…E3Uu4zGqiTg%3d%3d&idc_r=51493132847&domain=www.theverge.com&sw=1366&sh=768 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
https://platform.twitter.com/widgets.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by luixxiul** [comment]
Don't be sorry for that. Maybe the error happens quite rarely. Please keep using Brave and wait for a moment :-)

**Comment by bsclifton** [comment]
@krua I believe those resources being blocked is intentional, right? Part of the ad blocking. They should go away if you disable ad blocking / tracking protection using the bravery menu (but I'd keep it on :smile: )

**Comment by krua** [comment]
@luixxiul I will keep using Brave and post the console output here if the problem happened.
@bsclifton I am not quite sure if those resource is intentionally blocked, but I am enable the Replace Ads on bravery menu :)

**Comment by krua** [comment]
Here we go, the problem is still persist. The console output :
```
https://cdn0.vox-cdn.com/javascripts/lib/advertisement.v6fdc11c.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://ad-cdn.technoratimedia.com/smartwrapper/81065/1027/sw.min.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://cdn.krxd.net/controltag?confid=JImcjrMY Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://tags.api.umbel.com/lrjhazrpqbgtnrij/w.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://s.skimresources.com/js/66960X1514734.skimlinks.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://c.amazon-adsystem.com/aax2/amzn_ads.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://plus.google.com/js/client:plusone.js?onload=chorusAuthGPlusRender Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
http://js.moatads.com/essencedigital34895338176918191/moatcontent.js?loyalty_bsg=1&avgsestime_bsg=3380&firstimp_bsg=2&referral_bsg=www.google.com Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://platform.twitter.com/widgets.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by luixxiul** [comment]
According to the log it's not the problem of the page, but I'm not sure what is going on

**Comment by luixxiul** [comment]
From support

> I am using mint 17.3. When I use the back arrow I lose all my graphics until I close and restart the browser. All verisions have done this including the latest update.My graphics card is an AMD HD6670. Using standard linux mesa drivers

**Comment by luixxiul** [comment]
I searched google and found:
https://github.com/electron/electron/issues/4513
> Electron is linking with freetype dynamically while with harfbuzz statically, that should be the cause of the crash. Changing Electron to link with harfbuzz dynamically should be able to fix this.

I'm not sure if this is related to brave/electron, though.

**Comment by bbondy** [comment]
we would already have that change

**Comment by luixxiul** [comment]
yeah brave does not crash on fontawesome.io

**Comment by luixxiul** [comment]
This seems to be the same error.
https://twitter.com/AlexanderEin/status/740308303792726017

**Comment by IIIIIHIIIII** [comment]
Using the latest build 0.11.5, Bug still is there.

**Comment by ConorIA** [comment]
Not sure if this is realted, or just a coincidence, but I only started to experience this bug after: 

1) Switching from catalyst to the open source radeon driver
2) Upgrading xorg from 1.17 to 1.18

I find that it most often happens after I visit a page with an embedded video (such as YouTube), then all following pages load blank.

**Comment by luixxiul** [comment]
@ConorIA would you please follow the steps to reproduce the issue described here? https://github.com/brave/browser-laptop/issues/3787#issuecomment-248615910

**Comment by ConorIA** [comment]
@luixxiul, I've visited the "trigger" page on my laptop, with no problem. I am not in my office until the afternoon, but once I'm there I'll double check on my desktop, which is the machine that has the issue.
