### ISSUE TITLE
navigator.requestMIDIAccess doesn't work

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13924]
### Description
`navigator.requestMIDIAccess` returns a Promise that never resolves.

### Steps to Reproduce
Open the Brave developer tools and run the following from Console:
```js
navigator.requestMIDIAccess().then(
    access => console.log(access)
)
```

**Actual result:**
A promise is returned, but never resolved.

**Expected result:**
The access object is returned, and logged.

**Reproduces how often:**
100%

### Brave Version
0.22.22

**about:brave info:**
``` 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181
```

**Reproducible on current live release:**
Yes

### Additional Information
Works in Google Chrome.
Works in github.com/brave/brave-browser.
Lowering shields and setting Media to _Always Allow_ doesn't resolve the issue.

**Comment by bsclifton** [comment]
As noted above, this is resolved with Brave Core 😄 Marking as `wontfix` since we won't make a fix with `browser-laptop`
