### ISSUE TITLE
error in terminal when selecting File > Open File or Open Location without any open windows

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13927]
### Description
Selecting 'File > Open File' or 'File > Open Location' from the menu bar when there aren't any open windows throws an error in the terminal but does not seem to affect the application (app doesn't hang, crash, etc).

### Steps to Reproduce

  1. Launch Brave from the terminal.
  2. Close any open windows, but ensure Brave is still running.
  3. Select File > Open File (and also try with Open Location)

**Actual result:**
Error in terminal:

```
TypeError: window can not be null
    at Object.showDialog (/Applications/Brave.app/Contents/Resources/electron.asar/browser/api/dialog.js:56:13)
    at click (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/menu.js:60:16)
    at MenuItem.click (/Applications/Brave.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Applications/Brave.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)
```

**Expected result:**
No error in terminal. 

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave | 0.22.667
V8 | 6.6.346.24
rev | 0433b26
Muon | 5.2.6
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Reproducible on current live release:**
Yes, reproduces on 0.22.22

### Additional Information
Found by @kjozwiak

**Comment by kjozwiak** [comment]
We should mirror Chrome's behavior when fixing this. Rather than doing nothing when a user selects `Open File` or `Open Location` when there's no windows opened, we should do the following:

* selecting `Open Location` opens a new window with focus on the URL
* selecting `Open File` opens a new window and then opens the `File Manager` so a user can browse through their local storage

**Comment by bsclifton** [comment]
Verified as fixed with [brave-core](https://github.com/brave/brave-browser)
