### ISSUE TITLE
hard-refresh in tor tab should create new circuit

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#13925]
test plan:
1. in tor tab, go to check.torproject.org
2. hard refresh
3. you should see a different IP after the refresh

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
