### ISSUE TITLE
Only first crash report is auto uploaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13930]
### Description
Only first crash report is auto uploaded

### Steps to Reproduce
  1. Clean install 0.22.22
  2. Visit chrome://crash to cause a webview crash 
  3. Open chrome://crashes, ,ensure the crash report is uploaded 
  4. Verify crash report is shown on stats
  5. Open a new tab and visit chrome://crash to cause a webview crash
  6. Reload the chrome://crashes page, crash from step 5 is not auto uploaded 
  7. Repeat steps  5-6 multiple times, same result

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39211387-6c421ac2-47d9-11e8-9b33-df9708c415e1.png)

**Expected result:**
Should upload all crash reports unless user has disabled sending anonymous crash reports

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.22
-- | --
V8 | 6.5.254.41
rev | 6303310
Muon | 5.1.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
Yes

### Additional Information
cc: @bridiver @aekeus 
same on macOS verified by @LaurenWags

**Comment by kjozwiak** [comment]
@bridiver should we get this into the next release?

**Comment by bsclifton** [comment]
this should be fixed now
