### ISSUE TITLE
Find results stay highlighted even after you hit escape

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#13931]
### Description
When using cmd+f (or ctrl+f) to find words on a page, the results stay highlighted even after you press escape to dismiss.

### Steps to Reproduce

  1. Go to about:brave
  2. Push Cmd + F / Ctrl + F to bring up find bar
  3. Type "Brave" and hit enter
  4. Push escape to dismiss the find

**Actual result:**
results stay highlighted

**Expected result:**
results should not be highlighted

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.22.109 
V8: 6.5.254.41 
rev: 5e4846eb66981a0b7b283ddf7d65a2721641f87d 
Muon: 6.0.3 
OS Release: 17.5.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
no

**Comment by petemill** [comment]
Should be fixed with upcoming 0.22.701

**Comment by bsclifton** [comment]
Confirmed this is fixed! 🎉

**Comment by GeetaSarvadnya** [comment]
Tested on 0.22.702 Beta version. Issue is fixed and working fine on Windows x64

**Comment by kjozwiak** [comment]
Verified on `Mint 18.3 x64` using the following build:

* `0.22.702` e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
* Muon: `6.0.7`
* libchromiumcontent: `66.0.3359.139`
