### ISSUE TITLE
Saved credentials for in-active tab pop-up on active tab

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#13936]
Could not find a similar issue.

### Description
Opening a page with saved credentials in a background tab will show the credentials-popup on the original tab.

Minor issue, mostly cosmetics.

### Steps to Reproduce
  1. Go to page with link to a login page. E.g. webmail.
  2. Middle click link, page opens in background tab.
  3. Pop-up with saved credentials appear.

**Actual result:**
![bravecredentials censor](https://user-images.githubusercontent.com/1306453/39240039-fabe4e2a-4882-11e8-80d3-9f7a21654f88.png)
The 'hugo@...' credentials are for the 'E...' tab in the background.

**Expected result:**
Credentials pop-up only shown on the actual page they belong to.

**Reproduces how often:**
100%

It has also happened that the credential-popup could not be removed at all, and would even be on top of other applications when brave was moved. But have not been able to properly reproduce that. Probably unrelated issue.

### Brave Version

**about:brave info:**
 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 3.10.0-693.21.1.el7.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Don't know.

**Comment by eljuno** [comment]
Duplicate #12595?

**Comment by hugobuddel** [comment]
Seems like a duplicate indeed. Could not find #12595 earlier. Closing this one.
