### ISSUE TITLE
Add ability to make mail.google.com be the mailto: handler

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1394]

**Comment by luixxiul** [comment]
Was this implemented with [this](https://github.com/brave/browser-laptop/commit/3aa5ce4f903de70009a7ff2b1656624cbbdffe78)?

**Comment by bbondy** [comment]
no I think for example there should be a way to have Brave open mailto links in gmail.

**Comment by cezaraugusto** [comment]
Closing in favour of #1381
