### ISSUE TITLE
Clicking external link doesn't open new window when all windows closed

### ISSUE THREAD

**Issue by joerozek** [brave/browser-laptop#13941]
Have you searched for similar issues?
Yes

### Description
Clicking external link doesn't open a new window on Mac when all previous windows have been closed but Brave is still running in background.

### Steps to Reproduce

  1. On a Mac, set Brave as default browser
  2.  Open Brave
  3. Close all windows but leave Brave running in background (you should noticed the dot under Brave in the Dock)
  4. Click an external link (link from another application)

**Actual result:**
It appears like nothing has happens,  You have to bring Brave to the foreground and manually open a new window (⌘ + N), then you will see a tab has been created with the contents of your link.

**Expected result:**
If there is no current window open, one should be created with the content of your link.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.22.22 
V8: 6.5.254.41 
rev: 63033109963be0a995b3d1ed9723870beeb191c4 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Yes

### Additional Information
OS  10.13.4 High Sierra

**Comment by eljuno** [comment]
Dupe of #13859

**Comment by joerozek** [comment]
I verified it works for me in the pre-release.  
[v0.22.667](https://github.com/brave/browser-laptop/releases/tag/v0.22.667dev)

I swear I searched for the issue before filing. 😀
