### ISSUE TITLE
Brave browser does not work with google cloud console

### ISSUE THREAD

**Issue by Hisairnessag3** [brave/browser-laptop#13949]
### Steps to Reproduce
Simply log in to google cloud console.

**Actual result:**
Buggy, unusable interface

**Expected result:**
Nice Interface
**Reproduces how often:**
100%

### Brave Version

0.22.667
**about:brave info:**

V8 | 6.6.346.24
rev | 0433b26
Muon | 5.2.6
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment]
does enabling 3rd party cookies make it work?

**Comment by bsclifton** [comment]
This seems to be working great now! I suspect this was fixed with https://github.com/brave/browser-laptop/pull/13820
