### ISSUE TITLE
Netsuite and rev. 0433b26 With Win 10 v. 1703

### ISSUE THREAD

**Issue by chloebelle600** [brave/browser-laptop#13953]
I am using the Netsuite web portal and, since updating to the latest rev of Brave this morning, when I go to save a ticket, I am automatically kicked out of Brave and the ticket does not save. I cleared the browser cache and rebooted the system, but the issue persists.  This issue does not happen with Firefox. Thanks.

Chloebelle

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by kjozwiak** [comment]
@chloebelle600 does Brave completely close/crash? If so, it's probably related to https://github.com/brave/browser-laptop/issues/13947. We're planning on pushing a hotfix out sometime today.
