### ISSUE TITLE
Live tv doesn't work on Spectrum

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13957]
### Description
>Reported via https://community.brave.com/t/video-not-playing/17851

### Steps to Reproduce
>It has nothing to do with the cable company because the video playback works perfectly fine on both Chrome and FireFox… and yes, i did click on “allow” when the Flash notification came up

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39317076-ba53540e-4948-11e8-8ed3-686b467c15ee.png)
![image](https://user-images.githubusercontent.com/17010094/39317121-d4357da2-4948-11e8-82bf-31e035df90a0.png)

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information
Added flash as enabling it doesn't load video as well
cc: @diracdeltas

**Comment by frostbytedata** [comment]
Man this is definitely still an issue even on the latest release Version 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit).

Even with all shield settings disabled, this error still prevails. Unfortunate if this cannot be addressed, I will have to switch back to Chrome sadly. I was loving the concept of Brave :(

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1737

@frostbytedata we've got your info logged in the new repository- having more information about your setup would be great. OS version. Also would be great if you tried with shields down to see if it makes a difference
