### ISSUE TITLE
Tabs become unmuted when dragged to a new window

### ISSUE THREAD

**Issue by sudomake** [brave/browser-laptop#13979]
### Description
There's a bug that causes muted tabs to become unmuted when making them their own window.

### Steps to Reproduce
  1. Open webpage with a video, such as a video on youtube.com or twitch.tv.
  2. Play the video.
  3. Click the icon on the tab to mute the tab.
  4. Drag the tab so it becomes a new window.

**Actual result:**
The video will become unmuted despite the icon showing it continuing to be muted.

**Expected result:**
The video would remain muted.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Reproducible on current live release:**
Yes

### Additional Information
Seems to be any/every video/site so far.

**Comment by catilac** [comment]
I can work on this!

**Comment by catilac** [comment]
related: #13996 , #13990

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/805698330f971c976ac64d9507e7e24abd7f0d9e which will be available in muon 6.0.8

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.703 903b8d0d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.8
