### ISSUE TITLE
Copy button is enabled when wallet  address for currencies not generated

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#13974]
### Description
Copy button is enabled when wallet address for currencies not generated

### Steps to Reproduce
1. Enable payments 
2. Ensure wallet address or QR code is not generated for currencies due to server error
3. Copy button is enabled. Clicking on it shows copied message but nothing is copied into clipboard

**Actual result:**
Copy button is enabled when wallet address for currencies not generated
![copy button issue](https://user-images.githubusercontent.com/38657976/39428729-1cf50b24-4ca6-11e8-9f58-7ece3b356aca.gif)

**Expected result:**
Copy button should be disabled if wallet address for currencies is not generated

**Reproduces how often:**
100%

### Brave Version

Brave	0.22.669
V8	6.6.346.24
rev	6cda2e8
Muon	5.2.7
OS Release	10.0.16299
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	66.0.3359.117

**Reproducible on current live release:**
Yes

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya this will be solved with #13973, where we will add overlay, so that you can't trigger this flow
