### ISSUE TITLE
Add support for BCH/BTG/DASH for funding a BAT wallet

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13977]
here is the current funding screen:
<img width="1441" alt="untitled" src="https://user-images.githubusercontent.com/400552/39452565-76ae17f6-4c87-11e8-90f6-d15910a03e19.png">
ideally all of the altcurrencies supported by uphold should be supported. when https://github.com/brave-intl/bat-ledger/pull/215 is merged into master, we can then update the `bat-client` to use the new `GET /v3/wallet` endpoint to indicate a desired altcurrency for which an addresses is needed, cf., https://github.com/brave-intl/bat-client/issues/73

**Comment by jasonrsadler** [comment]
Current supported currencies in uphold:
BitCoin
BC Cash
BC Gold
Ethereum
BAT
Litecoin
Dash
Voxel (not listed in currencies to choose from on dashboard though)

**Comment by mrose17** [comment]
thanks! sadly XRP support is only partial at present.

i don't see Voxel support on uphold, can you provide a link?

**Comment by jasonrsadler** [comment]
https://uphold.com/en/transparency%C2%A0




I think it's still in the 'up and coming', XRP does show up in the add funds dropdown on the dashboard

<img width="1915" alt="screen shot 2018-05-01 at 10 53 35 pm" src="https://user-images.githubusercontent.com/25326067/39503250-e60149a0-4d92-11e8-85ea-55ed50967c43.png">

**Comment by NejcZdovc** [comment]
@bradleyrichter can you please provide mock for this one?

**Comment by bradleyrichter** [comment]
This is all being replaced by a new iframed Uphold UI. I'm not sure it makes sense to update the existing UI.

**Comment by mrose17** [comment]
please update it... just in case. i don't think it's a lot of work.

**Comment by bradleyrichter** [comment]
@mrose17 you want to add 3 additional coins that are shown in the uphold card screen shot above?

**Comment by bradleyrichter** [comment]
@NejcZdovc Here is a new layout that allows for more coins:

![image](https://user-images.githubusercontent.com/13509546/39651068-5e971ad0-4f9f-11e8-8f6b-c973553141d0.png)

**Comment by iesta** [comment]
EOS should be added too
