### ISSUE TITLE
Convert  bn_BD localization files

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1397]
They are still l20n files, I think you had a file encoding problem.

**Comment by seeam** [comment]
It is a very common scenario that most of the desktop/web text editor can't show Bengalli language without a few troubleshooting. Even github's text editor isn't suitable too.
Anyway, it will be better if you open the bn_BD channel, I and/or we can then paste previously localized string there.

**Comment by bbondy** [comment]
@seeam I justa dded bn_BD to transifex, let me know if you can't access.

**Comment by seeam** [comment]
Yes it is accessible. I will try to paste the strings this weekend and will pass the link to our local open source community after that.

**Comment by bbondy** [comment]
ok sorry for this trouble and thanks for handling it.  CC @aekeus

**Comment by bbondy** [comment]
0.9.3 is expected to be on the 27th, any chance this can be done before then?

**Comment by aekeus** [comment]
Absolutely!

**Comment by seeam** [comment]
@bbondy, I have converted old file and added new strings except menu.properties. So hopeefully it will be completed before that.

**Comment by seeam** [comment]
Well you can close this issue as transifex is showing 100% green bar!
