### ISSUE TITLE
Display error when ledger server is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13972]
### Description

When ledger server is down, we should display notification to users that server is down, so that they know what is doing on.

### Steps to Reproduce

  1. Enable payments
  2. Turn off internet 
  3. Wait 1min and make sure that you see error in the terminal

**Actual result:**

![image](https://user-images.githubusercontent.com/9574457/39420083-366a5ce6-4c63-11e8-9867-60d33dc60154.png)

**Expected result:**
We should display notification about server down

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
![13972](https://user-images.githubusercontent.com/38657976/39585533-aa7bd7ac-4f12-11e8-94df-7a78eaced9ab.gif)

**Comment by kjozwiak** [comment]
@GeetaSarvadnya mind rechecking this? I updated the test cases above. We should check that turning the internet back on correctly dismisses the modal and that websites, YT and Twitch are correctly being added into the ledger table once the internet is turned back on.
