### ISSUE TITLE
Brave not opening new window / tab when prompted by another application (Visual Studio)

### ISSUE THREAD

**Issue by shortstuffsushi** [brave/browser-laptop#13976]
I searched and wasn't able to find any other duplicates of this, though the wording is generic enough that I may be. Sorry if so.

### Description
When you launch a web project in Visual Studio, it will by default attempt to launch you into a window in your preferred / default browser. For instance, I have a project that it tries to launch @ localhost:44302. This works fine for Chrome and the other players, but doesn't work in Brave. Brave becomes focused, but doesn't actually open a new window. Is there a setting I'm missing to allow this? Is there a security reason to prevent this? Is it just a bug?

### Steps to Reproduce

  1. Create web based project in Visual Studio (MVC template works fine)
  2. Set Brave as the target browser in the debug menu
  3. Launch the project

**Actual result:**
Brave becomes focused, but doesn't open a new tab

**Expected result:**
Brave should open a tab for the project you've launched

**Reproduces how often:**
Always

### Brave Version
This has happened ever since I've been using Brave, but I'm currently on 0.22.669

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@shortstuffsushi can you try this with our new developer channel release? I don't know if this is still an issue, but I don't think we'll be able to fix it with the `browser-laptop` code-base

**Comment by shortstuffsushi** [comment]
Whoa, the dev version of Brave is a whole new world. The tabs are really big (and on the top now?) and I can't figure out how to get LastPass set up. Is there a guide to some of the changes and how to adjust for them?

**Comment by shortstuffsushi** [comment]
This does seem to be working in the dev branch though.

**Comment by bsclifton** [comment]
@shortstuffsushi that is a good question- we don't currently have any material like that... but maybe we can prep something as we move towards Beta 😄 Thanks for the feedback
