### ISSUE TITLE
bookmarks toolbar does not reduce in height in text-only mode

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13985]
### Test plan
See https://github.com/brave/browser-laptop/pull/13986

### Description
#13758 introduced fixed height on bookmarks bar to ensure it did not wrap to two lines. Looks like (possibly intentionaly) text-only mode in current release, the bar is a couple pixels shorter.

0.22.700

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
0.22.703 903b8d0d
libchromiumcontent 66.0.3359.139
muon: 6.0.8
