### ISSUE TITLE
Cannot scroll webview contents

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13982]
### Description
Sometimes a switched-to Tab does not scroll via mouse wheel or via keyboard (arrows or page-up, etc). In this state, whilst links on the page do get the correct hover state, and text is selectable, the mouse cursor does not get pointer over links.

The only step to rectify is to re-attach (either by switching away and back again) or via `display: none` on webview.

### Steps to Reproduce
Not consistent...

  1. Open a session with > 20 tabs (sometimes happens with only 4 tabs, seems to more often happen with more tabs)
  2. Switch to a few tabs
  3. Switch back to some of the tabs and try to scroll
  4. If were able to scroll, switch to a few more unloaded tabs and try to scroll.

### Brave Version

**about:brave info:**
0.22.700

**Reproducible on current live release:**
No

**Comment by bridiver** [comment]
fixed https://github.com/brave/muon/commit/1ac2b63bc26571484efe2bed0af6060f6b1a3640

**Comment by LaurenWags** [comment]
Reproduced with 0.22.702 - had been testing the `Context menus` section of the manual test run, but couldn't get solid STR. I had been using the context menus and opening/closing several tabs.

**Comment by petemill** [comment]
This is definitely fixed. Test plan is just to switch to any tab for the first time and see if it can be scrolled.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.712 e48c5ff
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
* have not seen this for the last couple of builds and it was occurring very frequently in previous builds.

**Comment by gerbsen** [comment]
This is happening for me more often then I want now. But I can scroll with keyboard controls.
