### ISSUE TITLE
Corrupted seed doesn't show overlay but shows abandon as recovery codes

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13980]
### Description
Corrupted seed doesn't show overlay but shows abandon as recovery codes

### Steps to Reproduce
  1. Enable payments and close browser after wallet is created
  2. Edit `ledger-state.json` file and change all seed value to 0
  3. Relaunch browser, payments-> advance settings -> Backup wallet , shows abandon text , payments doesn't show corrupted overlay

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39482883-ab18f17a-4d3e-11e8-9fb1-6260ac9d2e86.png)

**Expected result:**
Should show the corrupted wallet overlay 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.669
-- | --
V8 | 6.6.346.24
rev | 6cda2e8
Muon | 5.2.7
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/39485852-1c126d9e-4d48-11e8-9d33-86f9542f426b.png)

importing this recovery key fails.

**Comment by jasonrsadler** [comment]
Same on master

 
Brave: 0.24.0 
V8: 6.5.254.41 
rev: ca83ee381e6152704c4c1793f118d89d0770e6dc 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Comment by NejcZdovc** [comment]
This regressed, when we added support for bip39

**Comment by NejcZdovc** [comment]
Closing this issue as setting seed values to 0 is not a broken seed. But I created new issue based on @LaurenWags report #14001
