### ISSUE TITLE
Toolbar back button 

### ISSUE THREAD

**Issue by bantros** [brave/browser-laptop#13988]
### Description
Did a quick search but couldn't find a similar issue.

The back button in the toolbar will be 2-3 times the usual size on some tabs. Doesn't affect all tabs. There is no consistency to the issue but it always happens if I have at least 2 tabs open.

It doesn't affect the functionality of the browser or button, everything still works but it is an annoying visual error.

### Steps to Reproduce

  1. Launch Brave
  2. Open a few tabs
  3. Go to random sites

**Actual result:**

![brave](https://user-images.githubusercontent.com/3586124/39517553-0fbc5b9e-4df8-11e8-9601-9f0216953702.jpg)

**Expected result:**
Back button should stay at usual expected size, not change.

**Reproduces how often:**

Happens every time I launch Brave without fail.

### Brave Version

**about:brave info:**

Brave | 0.22.669
V8 | 6.6.346.24
rev | 6cda2e8
Muon | 5.2.7
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Reproducible on current live release:**

Yes

### Additional Information

Running on macOS Sierra 10.12.6

**Comment by Liunkae** [comment]
The back/forward buttons grow whenever the back/forward gestures are activated. (#9617)

![](https://user-images.githubusercontent.com/11330831/27703092-2a0cfae6-5cbb-11e7-9ffe-2c01843eff3e.gif)

In the (original post's) screenshot, it appears that the back button somehow got stuck in its larger size.

**Comment by bantros** [comment]
I wasn't aware of the swipe gestures @Liunkae as I only use with mouse/keyboard on desktop so haven't seen that animation before, thanks for clarifying.

You are correct though, it appears to be stuck in the larger size constantly.

**Comment by bsclifton** [comment]
cc: @darkdh
