### ISSUE TITLE
Extension popups crash browser

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#13983]
### Description
Basic Non-tab `<webview src="x">` elements are not loading any contents. These are used in extension popups which also cause a crash.

### Steps to Reproduce

  1. Enable metamask extension
  2. Click metamask extension icon

**Actual result:**
Crash

**Expected result:**
Loads popup (invisible on first time, visible on second time, like release)

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.109

**Reproducible on current live release:**
No

**Comment by petemill** [comment]
Should be fixed with muon 6.0.6

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.702 e4a853d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
