### ISSUE TITLE
muted tab plays when you navigate back to it

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13996]
### Description
If you mute a tab (either via clicking on the speaker icon on the tab or right click and select 'Mute tab'), navigate away, and come back to the tab, audio starts playing again even though the speaker icon still shows muted.

### Steps to Reproduce

  1. Open a tab that you can mute (I used a news article with a video).
  2. Mute the tab (either via speaker icon or right click).
  3. Navigate away from tab (visit another open tab or open a new tab).
  4. Navigate back to the muted tab.

**Actual result:**
Audio plays but the speaker icon shows muted.

**Expected result:**
Audio should still be muted.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**

Brave | 0.22.701
V8 | 6.6.346.26
rev | 339ffd6
Muon | 6.0.7
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
no, does not reproduce on 0.22.669

### Additional Information
Additional STR:
  1. Open a tab that you can mute (I used a news article with a video).
  2. Mute the tab (either via speaker icon or right click).
  3. Hover over another tab so that you get the preview and then go back to the original tab.
  4. Audio starts playing and speaker icon shows muted.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/805698330f971c976ac64d9507e7e24abd7f0d9e which will be available in muon 6.0.8

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.703 903b8d0d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.8
