### ISSUE TITLE
Clicking on preferences page causes orange border around

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13992]
### Description
Clicking on preferences page causes orange border around

### Steps to Reproduce
  1. Upgrade to 0.22.701
  2. Open about:preferences#security
  3. Shows an orange border inside the frame, doesn't go away when clicked elsewhere

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39543543-85743192-4e19-11e8-8f00-939018e53f4a.png)

**Expected result:**
Should not show any frame

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.701
-- | --
V8 | 6.6.346.26
rev | 339ffd6
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
No

### Additional Information
Happens on all about pages.

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
0.22.703 903b8d0d
libchromiumcontent 66.0.3359.139
muon: 6.0.8
