### ISSUE TITLE
Include this publisher context option doesn't re-add a deleted publisher

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13994]
### Description
Include this publisher context option doesn't re-add a deleted publisher

### Steps to Reproduce
  1. Clean install 0.22.701
  2. Enable payments, visit some sites to add in ledger table
  3. Delete one of the publisher from the list
  4. Open about:history and right click on the publisher deleted and click `Include this publisher`
  5. Open payments, publisher is still under never include list, doesn't get re-added

**Actual result:**
https://youtu.be/Oysqf56XauU

**Expected result:**
1. Should either not show the include option until its removed from the never include list in payments
or
2. Auto remove the publisher from the never include list and add it back if the include this publisher is shown in history/bookmarks

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.701
-- | --
V8 | 6.6.346.26
rev | 339ffd6
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
No

### Additional Information
@ryanml 
Issue found while testing #6547
Issue reproduced on macOS by @LaurenWags

**Comment by ryanml** [comment]
@NejcZdovc what do you think given the two expected results?

**Comment by NejcZdovc** [comment]
@ryanml first scenario, so if publisher was deleted, we shouldn't display include
