### ISSUE TITLE
'Include site in Brave Payments' not available for bookmarks without http/https

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#13997]
### Description
If a bookmark doesn't have http or https in the URL (Location), then the option to 'Include Site in Brave Payments' does not appear on the context menu

### Steps to Reproduce

  1. Clean install 0.22.701
  2. Enable payments, visit a couple of sites so you have some data in your ledger table.
  3. Open about:bookmarks.
  4. Click on the star+ icon.
  5. Enter title and location (be sure to include http or https as appropriate) and save.
  6. Right click on the newly added bookmark, you will see the 'Include in Brave Payments' option.
  7. Click on the star+ icon.
  8. Enter title and location (do not include http or https this time) and save.
  9. Right click on the newly added bookmark.

**Actual result:**
'Include in Brave Payments' option does not display:
![screen shot 2018-05-02 at 4 29 12 pm](https://user-images.githubusercontent.com/28145373/39547576-fe32ba66-4e25-11e8-809d-3de483eabdaf.png)

**Expected result:**
Include in Brave Payments option should display as it does when you have http or https
![screen shot 2018-05-02 at 4 29 24 pm](https://user-images.githubusercontent.com/28145373/39547592-0749b6a4-4e26-11e8-9998-8c585e4e5219.png)

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave | 0.22.701
V8 | 6.6.346.26
rev | 339ffd6
Muon | 6.0.7
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
n/a

### Additional Information
Found while testing https://github.com/brave/browser-laptop/issues/6547
Reproduced on Win by @srirambv

**Comment by diracdeltas** [comment]
discussed with @ryanml in slack and we decided to remove the context menu item when the bookmark doesn't have a protocol because the ledger info key requires a protocol. i guess the importance of this depends on how many users enter a URL without a protocol as a bookmark.

**Comment by bsclifton** [comment]
Per comment from @diracdeltas, I'm going to remove the milestone from this issue. Unfortunately, there isn't a clean way to solve this without resolving the bookmark

**Comment by LaurenWags** [comment]
sounds good, thanks @diracdeltas and @bsclifton
