### ISSUE TITLE
Make urlbar autocomplete private tab aware

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#140]
urlbar autocomplete in non-private tabs shows results for private tabs. I don't think this is a privacy issue but it might scare/confuse users who expect non-private tabs to never show anything related to private tabs.

**Comment by luixxiul** [comment]
This had been added to the 0.8.0 milestone in #966, but remains open. Any plan or abandoned?

CC: @diracdeltas

**Comment by diracdeltas** [comment]
@luixxiul thanks for following up. IIRC this is a slightly different issue from #966 (which was for tab history). this is for when a private tab is currently open, and autocomplete in all other tabs shows the private tab's URL as long as the private tab is open.

**Comment by bsclifton** [comment]
Verified this is fixed with [brave-core](https://github.com/brave/brave-browser) 😄 Marking as `wontfix` for `browser-laptop`
