### ISSUE TITLE
Notify user why contribution is pushed back (30 minute min browsing time)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14000]
### Description

We want to display some notification on payments page, when contribution is due, but min browse time is not meet.

### Steps to Reproduce

  1. Enable payments
  2. Visit one site for few minutes
  3. Change reconcile stamp so that you trigger contribution

**Actual result:**

User contribution date was pushed back

**Expected result:**
We should notify user why contribution was pushed back for 3 days.

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by realuser** [comment]
Is it 30 minutes per site? Or 30 minutes total? 

1. If I visit one site for 31 minutes and another site for 4 minutes total, will they both receive a contribution or only site visited greater than 30 minutes?

2. If I visit one site for 16 minutes and another for 16 minutes total, will either receive a contribution?

Is this documented somewhere?

**Comment by NejcZdovc** [comment]
@realuser this is 30 minutes total. So you need to have at least 30min recorder time in you payments table

**Comment by srirambv** [comment]
Issue doesn't seem fixed. STR followed
1. Enable Payments
2. Fund wallet
3. Visit sites to add to ledger table
4. Change reconcile to older than 5 days
5. Launch browser with `LEDGER_NO_DELAY=true  LEDGER_NO_FUZZING=true` to trigger reconcile
6. Reconcile succeeds and no notification shown on UI that reconcile has been pushed back by 3 days 

Issue reproduced by @kjozwiak by setting reconcile back to 15 days and still payment went through

**Comment by NejcZdovc** [comment]
@srirambv you shouldn't use `LEDGER_NO_FUZZING` when testing this one, because you disabled this pushback. Please try it again without it.

**Comment by kjozwiak** [comment]
@NejcZdovc when @srirambv and me went through the above, we used`LEDGER_NO_FUZZING`. I'm guessing that's why the contribution went through? Fuzzing controls the push back if the 30min requirement isn't met correct? Should we run through the above case using only `LEDGER_NO_DELAY=true` and not `LEDGER_NO_FUZZING=true`?

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/39927983-0aee62fe-5502-11e8-94bf-f7ac8c8655c4.png)
