### ISSUE TITLE
prevent brave from switching to a tab which has the same url open

### ISSUE THREAD

**Issue by tommycarstensen** [brave/browser-laptop#14007]
It is really annoying that Brave switches to an already open tab, when I type in the URL and that URL is open in another tab. Sometimes the user wants to open two tabs. I think you should make it possible to disable this "feature" and not have it enabled by default. Thanks!

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/13486
