### ISSUE TITLE
Problems Installing on Windows 10 x64

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#1400]
User reported problems installing on Windows 10 x64 while having Firefox opened.

> "@mikko @brave read your tweet, was curious, downloaded. Installer crashes every time. See you in a couple of releases, Brave."
> https://twitter.com/ali_per_roma/status/721994110001881088

> "@jonathansampson @brave @mikko Windows 10 x64. After redownloading and retrying a couple of times, it succeded. I had Firefox opened...1/2"
> https://twitter.com/ali_per_roma/status/722139502580473856

> "@jonathansampson @brave @mikko 2/2 ... during installation, could that be the problem? Sadly, I did not take a screenshot of error prompt."
> https://twitter.com/ali_per_roma/status/722139738707226628

**Comment by akatechis** [comment]
I was about to confirm this as an issue for me as well, linking the following log file, but after looking through it and seeing that it was denied permission to a path, I tried running it as Administrator. It threw the same error a few times, and after opening the logfile, clearing it, saving it, it seems to have worked (the Brave browser eventually popped open).

Not sure if clearing the logfile actually fixed the issue, or it was just a coincidence.

Here's the original error log when running the installer in user mode.
[errorlog.txt](https://github.com/brave/browser-laptop/files/230338/errorlog.txt)

**Comment by bbondy** [comment]
Try clearing out your whole
C:\Users\USERNAME\AppData\Local\Brave
