### ISSUE TITLE
"match case" doesn't work under the findbar

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14019]
### Description

When searching for words via the `findbar`, `match case` doesn't work and will highlight the matching words even though the case doesn't match.

### Steps to Reproduce

  1. launch `0.22.702 ` e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
  2. visit https://en.wikipedia.org/wiki/World_War_II
  3. open the `findbar` via `CMD + F` or `CTRL + F`
  4. Search for `GeRmAnY` and click enable `Match Case`
  5. press "enter` and you'll notice that Brave keeps looking for instances of `Germany` even though the text field has `GeRmAnY` as it's search term 

**Actual result:**

![matchcase](https://user-images.githubusercontent.com/2602313/39601615-852525f2-4ef0-11e8-9f5c-565c09e73605.gif)

**Expected result:**

Using `Match Case` under the `findbar` should work as expected and correctly look for the case that's added into the text field.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.702 
V8: 6.6.346.26 
rev: e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
Muon: 6.0.7 
OS Release: 4.13.0-39-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Reproducible on current live release:**

Currently not reproducible under `0.22.669` which is the latest released version.

### Additional Information

* macOS x64 - Reproduced by @LaurenWags 
* Win 10 x64 - Reproduced by @srirambv 
* Min 18.3 x64 - Reproduced by @kjozwiak

**Comment by petemill** [comment]
Should be fixed in next build

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
0.22.703 903b8d0d
libchromiumcontent 66.0.3359.139
muon: 6.0.8
