### ISSUE TITLE
Browser tab locks up when enabling Dashlane extensions

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14013]
### Description
Browser tab locks up when enabling Dashlane extensions

### Steps to Reproduce
  1. Clean install 0.22.702
  2. Enable Dashlane and disable it
  3. Repeat the enable/disable couple of time 
  4. Tab hangs doesn't show any UI changes  of enable/disable other extensions
  5. Disable Dashlane and enable 1Password no UI indication
  6. Open a new tab shows 1Password enabled and Dashlane disabled

**Actual result:**
Browser tab locks up when enabling Dashlane extensions

**Expected result:**
Should not lock up UI

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.702
-- | --
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
Yes

### Additional Information
#14011
Reproed on mac by @LaurenWags and on Linux by @kjozwiak

**Comment by bsclifton** [comment]
Possibly related:
https://github.com/brave/browser-laptop/issues/4138
