### ISSUE TITLE
1password/LastPass extensions do not work on Beta channel for macOS

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14012]
### Description
1password extension does not work on single webview build. You can enable it in about:preferences#extensions, but clicking on the extension icon doesn't do anything.

### Steps to Reproduce

  1. Clean install of 0.22.702 (or any Beta channel build)
  2. Enable 1password in preferences
  3. Click on the 1password extension icon.

**Actual result:**
Nothing happens. No errors in terminal (if launched via CLI) or console. If you navigate to a page which requires login credentials and click on the extension icon, same result - nothing happens. 

**Expected result:**
1password menu should be displayed.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave | 0.22.702
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
No, does not reproduce on 0.22.669

### Additional Information
Reproduced on macOS by @kjozwiak 
@srirambv could not reproduce on Windows

**Comment by JamieFarrelly** [comment]
I wonder if this is related to the issue I recently created around LastPass not working either https://github.com/brave/browser-laptop/issues/14023?

**Comment by Tomatoshadow2** [comment]
+1 from myself, using Last Pass.
