### ISSUE TITLE
Global Default Zoom Setting

### ISSUE THREAD

**Issue by cwmke** [brave/browser-laptop#1401]
It would be nice to be able to set the default zoom level for every page.  For my setup, the default is always much smaller than I like.  An example of the desired behaviour,

1. Set the default zoom level to 125% in preferences.
2. Every new page you go to automatically zooms to 125%.

Thanks for the consideration!

**Comment by bbondy** [comment]
We have per site zoom remembering coming for 0.9.2.  I think each person probably only visits a handful of sites and each site has different font sizes.  So I think per site settings is probably ideal here instead as we have planned.  Do you know of other browsers that do a global default? I'm tempted to close in favour of what's coming in 0.9.2.

**Comment by cwmke** [comment]
I know Chromium has it under 'Web Content' under the advanced settings section.  Per site is definitely useful, but in some cases the default is very small as well which then requires zooming in on every new web page you view.

**Comment by bbondy** [comment]
OK I'll leave open and will accept a patch but we probably won't get to this soonish otherwise.

**Comment by cwmke** [comment]
No problem!  Thanks for leaving it open.

**Comment by bbondy** [comment]
Moving to 0.10.2.  After support triage it seems like this is a very frequent request.
