### ISSUE TITLE
Recover progress message shown before actual recovery starts

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14014]
### Description
Recover progress message shown before actual recovery starts

### Steps to Reproduce

  1. Enable payments
  2. Go to advance settings, recover your wallet
  3. Click import recovery keys , shows recovering progress message even though no recovery is happening

**Actual result:**
![11790](https://user-images.githubusercontent.com/17010094/39593895-2a7ad442-4ed9-11e8-989c-fce941b04912.gif)

**Expected result:**
Should only show the progress message when actual recovery is happening

**Reproduces how often:**
100%

### Brave Version

Brave | 0.22.702
-- | --
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**

### Additional Information
#11790

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.703 903b8d0d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.8
