### ISSUE TITLE
Extensions description change when enabled/disabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14011]
### Description
Extensions description change when enabled/disabled

### Steps to Reproduce
  1. Clean install 0.22.702, open extensions, check description for 1password/Dashlane/Bitwarden
  2. Enable 1password/Dashlane/Bitwarden
  3. Description and name gets changed
  4. Enabling Dashlane for first time causes tab to freeze (UI doesn't show other extensions being enabled/disabled but clicking them does enable/disable other extensions)

**Actual result:**
![extensions](https://user-images.githubusercontent.com/17010094/39591597-3895e94c-4ed2-11e8-9e17-60c63d028a20.gif)

**Expected result:**
Should not change name/description and not freeze up page when extension are enabled

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.702
-- | --
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
Yes

### Additional Information
Issue confirmed on Linux by @kjozwiak and on macOS by @LaurenWags

**Comment by Jacalz** [comment]
I noticed that a while ago too when doing an extension testing round with @sampson.
I believe that we came to the conclusion that it uses the description of the extension itself when you enable it and that it is the reason to it happening.

**Comment by eljuno** [comment]
Maybe also related to #9583?

**Comment by Jacalz** [comment]
I would definatley say yes to that @eljuno

**Comment by srirambv** [comment]
Agreed its the same. Thanks @eljuno
