### ISSUE TITLE
Brave picks up low-resolution favicon for WSJ.com

### ISSUE THREAD

**Issue by davidtemkin** [brave/browser-laptop#14024]
### Description

WSJ favicon in Brave is lower-resolution than the version picked up by Chrome.

### Steps to Reproduce

  1. Enable favicons in tabs and/or bookmarks bar
  2. Go to wsj.com
  3. Displayed image is blurry compared to the image picked up by Chrome in the same use case.

**Expected result:**

Image shown should be a higher-resolution version of the favicon

**Reproduces how often:**

100%

### Brave Version

0.22.669

**Reproducible on current live release:**

Yes

**Comment by bsclifton** [comment]
@davidtemkin do you have a feeling for priority on this? Maybe we can bring up in our next triage meeting

**Comment by davidtemkin** [comment]
@bsclifton sounds good, let's review in the Tuesday triage

**Comment by petemill** [comment]
I noticed the favicon event coming from chromium / muon provides multiple favicons with different resolutions (some very high-res relatively / potentially), but we only always use the first one.

**Comment by bradleyrichter** [comment]
@jamesmudgett @cezaraugusto Please check into this during the upgrade to using colors/letters for high quality fall back.
