### ISSUE TITLE
Connection log pops up in a console window when opening a private tab 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14029]
### Description
Connection log pops up in a console window when opening a private tab 

### Steps to Reproduce
  1. Install 0.23.2 developer build
  2. Open a new private tab
  3. Tor connection log pops up as a console window
  4. Close the console and visit any site in Private tab
  5. Console pops up again

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39644143-60021000-4fa4-11e8-80d0-4094ba7efcd8.png)

**Expected result:**
Should not show connection info on console 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.2
-- | --
V8 | 6.6.346.26
rev | c09cbf6
Muon | 6.1.0
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
N/A

### Additional Information
cc: @riastradh-brave @diracdeltas @jumde

**Comment by diracdeltas** [comment]
@darkdh in fixing this, can we just write Tor process logs to disk on all platforms? that would help with debugging.

**Comment by darkdh** [comment]
this popup shown is not because we launch tor. it is utility process, I'm working on this.

and I am all for writing tor log into a disk file on all platforms.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/pull/473/commits/6d6cda7792fef35502fd52b3d209b7f43c86b5aa which will be available in muon 6.1.1

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
