### ISSUE TITLE
LastPass no longer works

### ISSUE THREAD

**Issue by JamieFarrelly** [brave/browser-laptop#14023]
### Description
I used to use LastPass in Brave now and again. I noticed the icon for LastPass is no longer there and when I click on it I get a "Your file was not found error" as in the screenshot. I'm not aware of any changes that I've made to cause this, I assume it happened after an update but I'm not sure. It might be a tricky one to reproduce unfortunately.

Just creating this issue in case anyone else has any more information on it, maybe it's more widespread.

### Steps to Reproduce

  1. Enable LastPass in about:preferences#extensions
  2. When you do this, on the top right hand side of the browser space gets added where the LastPass icon should be (it's invisible though)
  3. Click on this space and you'll get the error.

**Actual result:**
You get an error pop up. The description of lastpass also doesn't appear when you enable it, but it's there when it's disabled.
![image](https://user-images.githubusercontent.com/12645106/39623173-ab8311e0-4f8c-11e8-9177-d3f5687a6277.png)

**Expected result:**
The LastPass login window opens.

**Reproduces how often:**
All the time.

### Brave Version

**about:brave info:**
Brave | 0.22.21
V8 | 6.5.254.41
rev | 82c1e0e
Muon | 5.1.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.181

**Reproducible on current live release:**
I'll check this soon.
Edit - Seems to be fixed on the newest release. 

### Additional Information
N/A

**Comment by GeetaSarvadnya** [comment]
+1 from https://community.brave.com/t/extensions-not-visible/23300/6

**Comment by bsclifton** [comment]
I believe this is due to a corrupt extension- I've had this happen a few times before

If you go to your profile directory (`%appdata%\brave\`) there should be an extensions folder. If you close Brave first and then delete the LastPass folder under here (it may be using the extension ID, which is `hdokiejnpimakedhajhdlcegeplioahd`), Brave will re-fetch the extension when you log back in
