### ISSUE TITLE
Payment button not shown in URL for included pdf pages

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14025]
### Description
Payment button not shown in URL for included pdf pages

### Steps to Reproduce

  1. Enable payments
  2. Visit any pdf link in a new tab and complete the min time check requirement
  3. Ensure domain is added to the ledger table
  4. Switch back to pdf, URL bar doesn't have payment button

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/39637143-27dd059a-4f90-11e8-9b4b-436b78ed1aef.png)

**Expected result:**
Should enable the payment include/exclude button in URL for PDF's as well 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.702
-- | --
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
N/A

### Additional Information
#12792
cc: @diracdeltas

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.703 903b8d0d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.8
