### ISSUE TITLE
Cannot manually run tests: "devTools is not defined"

### ISSUE THREAD

**Issue by NHDaly** [brave/browser-laptop#14035]
### Description
My tests all fail and print the same error: `message: 'unknown error: devTools is not defined'`. This is a brand-new installation of browser-laptop.

### Steps to Reproduce
1. Installed `node` with `homebrew`
1. Update `npm` (`npm install npm@latest -g`)
1. `cd browser-laptop`
1. `rm -rf node_modules` (Cleared node modules)
1.  Ran `npm install`
1. Finally, run `npm run test`.

**Actual result:**

Here is the complete error output, when I tried a specific single test. It fails the same even if I run all tests via `npm run test`.

```bash
$ npm run test -- --grep="should undo last closed tab"

> brave@0.24.0 test /Users/daly/src/brave-browser-laptop
> cross-env NODE_ENV=test mocha "test/**/*Test.js" "--grep=should undo last closed tab"



  tab tests
    close tab
      1) "before each" hook for "should undo last closed tab"
Quit failed:  { Error: An unknown server-side error occurred while processing the command.
    at execute(<Function>) - brave.js:677:19
  message: 'unknown error: devTools is not defined',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'unknown error: devTools is not defined\n  (Session info: chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.35 (abb5172872b726072a64dfabaf45894c6ecf7369),platform=Mac OS X 10.13.4 x86_64)' } }


  0 passing (8s)
  1 failing

  1) tab tests close tab "before each" hook for "should undo last closed tab":
     Error: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:278:32



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.24.0 test: `cross-env NODE_ENV=test mocha "test/**/*Test.js" "--grep=should undo last closed tab"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.24.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daly/.npm/_logs/2018-05-05T19_35_18_708Z-debug.log
```

**Expected result:**
Tests run correctly

**Reproduces how often:**
100% for me.

### Brave Version

My repo is checked out to the following commit:
bca6936d8a5acaaf8fa7e5803581e34d38de5e6e

**Reproducible on current live release:**
N/A

### Additional Information
This is my first time trying to run tests using `npm`. Am I supposed to install `devTools` separately? If so, perhaps that step can be added to the instructions?

**Comment by bsclifton** [comment]
@NHDaly are you running the watch process?  Basically, you'll want to have two tabs/consoles open:
1st running `npm run watch`
2nd running `npm run test`

I suspect this is the problem. Another contributor had difficulty recently, so I updated our docs here:
https://github.com/brave/browser-laptop#running-brave
