### ISSUE TITLE
Closing connection info console before connecting to tor network doesn't load page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14033]
### Description
Closing connection info console before connecting to tor network doesn't load page

### Steps to Reproduce
  1. Clean install 0.23.2
  2. Open a new private tab
  3. Connection info console opens pops up
  4. While connection is being established, close the console, page load fails
  5. Reload shows about:error. Tab becomes useless can't reload the page. Have to type in again to bring the connection info window and connect to tor network before page loads

**Actual result:**
![tor](https://user-images.githubusercontent.com/17010094/39653646-d7eb1790-4fbf-11e8-8df7-f6e36fb6915c.gif)

**Expected result:**
Should be fixed with #14029 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.2
-- | --
V8 | 6.6.346.26
rev | c09cbf6
Muon | 6.1.0
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
N/A

### Additional Information
cc: @diracdeltas @riastradh-brave

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/pull/473/commits/6d6cda7792fef35502fd52b3d209b7f43c86b5aa which will be available in muon 6.1.1

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
