### ISSUE TITLE
 "immutableFrameList had frame with invalid key" error when tearing off an unloaded tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14031]
### Description
 "immutableFrameList had frame with invalid key" error when tearing off an unloaded tab

### Steps to Reproduce
  1. Clean install 0.22.702
  2. Open 5-6 tabs and visit a site in each of them
  3. Close and relaunch browser via console
  4. Quickly drag any inactive, unloaded tab into a new window
  5. Tear off tab doesn't contain tabs bar and is unusable, console throws error  

**Actual result:**
```
[8912:8380:0504/150630.188:ERROR:CONSOLE(1)] "immutableFrameList had frame with invalid key", source: chrome://brave/C:/Users/bellurs/AppData/Local/BraveBeta/app-0.22.702/resources/app.asar/app/extensions/brave/gen/app.entry.js (1)
```
![image](https://user-images.githubusercontent.com/17010094/39648482-58f58b14-4fb0-11e8-8b25-6e58eb438f6c.png)

**Expected result:**
Tear off tab to window should work fine without complaining in console

**Reproduces how often:**
3/5 times 

### Brave Version

**about:brave info:**

Brave | 0.22.702
-- | --
V8 | 6.6.346.26
rev | e4a853d
Muon | 6.0.7
OS Release | 10.0.16299
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
No

### Additional Information
cc: @bridiver @petemill @bsclifton

**Comment by srirambv** [comment]
Another variation of the error shows up when a tab is dragged and dropped in to another window. 
```
[18664:17156:0504/152326.245:ERROR:CONSOLE(1)] "frame not found for tab inserted to tab strip", source: chrome://brave/C:/Users/bellurs/AppData/Local/BraveBeta/app-0.22.702/resources/app.asar/app/extensions/brave/gen/app.entry.js (1)
[18664:16656:0504/152527.553:ERROR:ssl_client_socket_impl.cc(1098)] handshake failed; returned -1, SSL error code 1, net_error -101
```
https://youtu.be/ei9siG76ISE

**Comment by LaurenWags** [comment]
Similar result on macOS using this STR (reproducible):
Clean profile with 0.22.702
Closed Welcome window
Cmd+click on the top tiles, chose one of them as the active one
Close/Reopen Brave using terminal.
Drag an inactive tab (quickly, so preview doesn’t show) to it’s own window
Tab content in new window is white. Reload, clean reload, window resize - nothing makes the tab content appear. Have to close/reopen Brave to get tab content to show. No errors in terminal. This is what the dropped in active tab looks like:
![screen shot 2018-05-04 at 3 12 59 pm](https://user-images.githubusercontent.com/28145373/39648809-880b487a-4fb1-11e8-8201-b1552d4dc712.png)

**Comment by srirambv** [comment]
second issue reproduces on active tab when dnd

**Comment by petemill** [comment]
The issue @LaurenWags is seeing was due to not displaying the tab until it is 'ready'. The 'ready' message was coming whilst the tab was moving between windows, so is not set on the tab in the new window. 'Preview' mode does not have this check, so the tab could still be previewed. I've removed the check as it doesn't seem neccessary anymore due to webview improvements.

**Comment by btlechowski** [comment]
I just reproduced @srirambv issue on Ubuntu 17.10, v0.22.702.

**Comment by petemill** [comment]
@srirambv @btlechowski is it possible to please get a video of the issue reported in the description?

**Comment by btlechowski** [comment]
I have tried for over 2hours to repro, but failed. Sorry. I will try tomorrow.

**Comment by kjozwiak** [comment]
I couldn't reproduce this either on my Win 10 x64 desktop. Followed the STR above without any luck. I'll try a few more times but already spent ~1hr without reproducing.

**Comment by srirambv** [comment]
Can't reproduce it on current preview build. Closing the issue for now. Will reopen if it can be reproduced consistently.

**Comment by kjozwiak** [comment]
Removed the the `release/blocking`. However, we should check this against the three platforms just to double check and ensure that it's not an issue anymore even though no one managed to reproduce.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.712 e48c5ff
* muon 6.0.9
* libchromiumcontent 66.0.3359.139

**Comment by kjozwiak** [comment]
I've managed to find a case where I can reproduce this 100% of the time on `macOS 10.13.4` using `0.22.713`. 

STR: (example: https://youtu.be/H4-M-1TS5m0)

* launch `0.22.713` fd036ae using [session-store-1.txt](https://github.com/brave/browser-laptop/files/2007148/session-store-1.txt)
*  play any of the current streams (twitch should be the active tab when you launched brave)
* once the stream is being played, click on `full screen`
* after a few seconds in `full screen` mode, press `ESC` to escape `full screen` mode
* drag and drop the twitch tab into it's own window

You'll notice that the twitch audio is still being played but the entire tab is white and non-responsive. If you do manage to close the window, the audio from the twitch stream keeps playing till you close the browser. It seems like the process didn't terminate correctly when the window becomes white/unresponsive. You'll also see the following error in the terminal as @srirambv mentioned above:

`[1549:775:0515/205823.951182:ERROR:CONSOLE(42)] "immutableFrameList had frame with invalid key", source: chrome://brave/Applications/Brave.app/Contents/Resources/app.asar/app/extensions/brave/gen/app.entry.js (42)`

**Comment by petemill** [comment]
Note that as we investigated this bug, we found that un-fullscreening a tab would cause an error for the next new window, whether that's caused by detaching current tab, or any tab, or just asking for a new window with the default New Tab.

**Comment by srirambv** [comment]
Followed steps from https://github.com/brave/browser-laptop/issues/14031#issuecomment-389362275 and issue doesn't reproduce. Looks fixed on Windows but would still keep an eye for it
Verified on Windows x64 with
* 0.22.718 11dcd19
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
