### ISSUE TITLE
Scrollbar on tabs view

### ISSUE THREAD

**Issue by babolivier** [brave/browser-laptop#1403]
Hi there,

First, congrats for making the Brave browser. I just started using it, and I'm loving it so far.

There's just one thing that bugs me right now: After a few minutes using it, I've just noticed that when I open 6 tabs, there's a scrollbar appearing on the top tabs view, as shown below:
![capture d ecran de 2016-04-19 09-02-55](https://cloud.githubusercontent.com/assets/5547783/14630460/261f2918-060e-11e6-9885-043e3fe034ee.png)

Here's the version of Brave and all of its components:
![capture d ecran de 2016-04-19 09-08-22](https://cloud.githubusercontent.com/assets/5547783/14630499/580a37ce-060e-11e6-8cab-23a7ad4dffbf.png)

If it can help, I'm running Archlinux and installed the AUR `brave-bin` package.

As for the steps to reproduce, well, I just opened 6 tabs, so...

Please let me know if you need any more info.

**Comment by luixxiul** [comment]
Would you update to the latest version and try again?

**Comment by babolivier** [comment]
Just updated, no problem anymore. Amazing job on this browser :)
