### ISSUE TITLE
UX for tor daemon status / launch progress

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14040]
There is no visual feedback for what the tor daemon is up to.  We should:

- [ ] provide a meaningful error message if you try to use Tor before the daemon is launched,
- [ ] provide some way to query the status of the tor daemon and view log files, and maybe
- [ ] provide a display of the current circuits and exits (though perhaps that should be a separate issue).

We will want both (a) tor's stderr output, and (b) events from the control socket.  I began to implement [communication with the control socket](https://github.com/riastradh-brave/browser-laptop/commit/4e1b830f475fe71a36fe34cfbb51928f68795022) in a branch a while back, but we now launch the tor daemon from C++ so that code isn't usable directly.

(This may not be worth doing at all before chromium-fork.)

**Comment by flamsmark** [comment]
→ #14043
