### ISSUE TITLE
Brave is infringing Google's trademark on Chrome

### ISSUE THREAD

**Issue by FineHub** [brave/browser-laptop#14041]
a) Brave by default lies in the user agent that it is Chrome. Chrome is a trademark of Google[1] and cannot be used without their permission, unless it is being used as an adjective. 
 
b) If this does not change, we are likely to report to Google that you are infringing their trademark.[2][3]

c) Chrome is directly associated with Google, and Brave does not have the permission to use the trademark.

d) Brave is a for profit organization building a product that directly competes with Google, many websites would not like their users to use Brave, and Brave causes financial losses to companies, which also cause a reputation damage to Google as it appears more Chrome users use adblockers but they are not. 

e) Brave affects our analytics and gets falsely identified as a product by Google. Doing this by default means that Brave is committing a fraud, as we are more likely to associate Chrome with adblocked revenue loss, even though it is not the product.[4][5]

---------------------------------------------------
Brave has 30 days before we make a direct report to Google, unless they change their fraudulent behavior.
---------------------------------------------------

Sources: 

[1] https://www.google.com/permissions/trademark/trademark-list.html
[2] https://www.google.com/permissions/trademark/rules.html
[3] https://www.google.com/permissions/trademark/brand-terms.html
[4] http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:wnyew0.2.4
[5] http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:wnyew0.2.5

**Comment by FineHub** [comment]
> We use the same user agent for reasons of web compatibility and also to avoid fingerprinting because of our relatively smaller user base.

Fingerprinting or not is not our concern. Google adds a User-Agent for Chrome, that makes Chrome unique. Brave fools us into thinking that it is a product by Google, and we were thinking that Chrome got a higher usage of adblockers, which could have cause accidental defamation of Chrome, if a malicious activity takes palace from Brave's user. What Brave essentially does is that is falsely advertises its self as a product made by Google in the User-Agent. You are not allowed falsely advertise youself as Chrome, because Brave is not Chrome! Brave is a fork of Chromium. You have to add an extra User-Agent, to allow us to identify Brave and not as a product by Google. 

We don't want Brave's visitors to visit our website. Lying in the User-Agent is a crime and is against the law. We request that some mechanism to identify Brave is given. 

>Please see the HTTP 1.1 spec here which clearly specifies that you can use multiple product tokens.

It says to USE multiple product token, not EXACT copying of a token of some other product. 

We are not interested in signing up as a publisher in a walled garden.

**Comment by thebouv** [comment]
It's like you don't even know what a User-Agent is @FineHub 

Read this article on the history of User-Agent strings -- it's pretty funny actually.  
https://webaim.org/blog/user-agent-string-history/

Brave is under no obligation as you state, and there is no infringement. Google isn't going to give a damn. Make your report to Google -- I'm sure they're really going to pay attention to you.

**Comment by bsclifton** [comment]
> Fingerprinting or not is not our concern. 
Can you clarify who `our` is?

**Comment by FineHub** [comment]
As a website, it is not our concern about what your (Brave's) intentions are. We dont fingerprint our users, nor do we allow any 3rd parties to do it. Our partners are not allowed to sell the user data either, and we have proved it by taking action against the infringers. 

But we do block adblock users, and users from browsers which block non intrusive 3rd party targeted ads which meets acceptable ads criteria, by default. The ads are targeted with standard cookies (no fingerprinting out of respect of user privacy). Brave blocks our ads by default, and block 3rd party cookies that help deliver better quality ads. We cannot/will not partner with any webbrowser/company that takes away the freedom from us as a publisher. Blocking all trackers and non Brave ads is not a good thing. If Brave is a respectable company, they'll show it up in useragent so we can block Brave visitor.  We are very clear that we dont want Brave. 

As for BAT, we dont need it. Google's micro payment system is getting ready, and will do the same thing.  By blackmailing publishers and forcing Brave's "Better, non-tracking, by default", you'll not gain our support, nor of the industries that makes the free internet possible.

**Comment by luyongxu** [comment]
@FineHub Can you elaborate on Google's micro payment system?

**Comment by bsclifton** [comment]
@FineHub leaving my personal opinion out of the picture... What is to gain for the end user by making Brave easy to detect and block? Why should any employee or community member put forth the effort to make this change?

Have you also considered that users do not want to be tracked? Sure, it might help deliver more relevant ads... because you're tracking the users activity across sites. What is your response to those users who do not wish to be tracked?

**Comment by thebouv** [comment]
This is golden.

If Brave repo maintainers are not aware, "FineHub" has been talking on Reddit and HackerNews too.  Started off discussing Firefox, but it has devolved a bit -- much like here, though here FineHub is being a lot more (amusingly) aggressive.

https://news.ycombinator.com/item?id=17012178  and  https://www.reddit.com/r/firefox/comments/8hhss1/is_it_worth_supporting_firefox/ 


I believe HN is what pointed me here and I'm glad it did for the entertaining read.

**Comment by FineHub** [comment]
> This is golden.
If Brave repo maintainers are not aware, "FineHub" has been talking on Reddit and HackerNews too. Started off discussing Firefox, but it has devolved a bit -- much like here, though here FineHub is being a lot more (amusingly) aggressive.

It is golden until you are in the same situation.

**Comment by FineHub** [comment]
Closing the issue. Brave team should look forward to the things I've said. It is better to reconsider your stance at this point. I know I've been aggressive, but maybe Brave needs to become a bit soft on adblocking and 3rd party cookies.

**Comment by BrendanEich** [comment]
Users of top browsers can configure their user agent via advanced preferences, and do. User-agent is not reliable, nor should anyone rely on it to block ad-blockers. There are much bigger ad-blocking extensions out there in terms of user populations than Brave, so I am not sure why @FineHub starts with us. But it's a free country!
