### ISSUE TITLE
command/ctrl + clicking on websites with certificate issues will result in a "The site can't be reached" page

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14044]
### Description

When opening some of the certificate errors from badssl.com via `command/ctrl` + `click`, you'll receive `The site can't be reached` error. However, when you refresh, the correct page loads. This works as expected under `0.22.669`

### Steps to Reproduce

  1. launch `0.22.702` e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
  2. load https://badssl.com/
  3. using `command/ctrl` + `click`, open the `expired` & `wrong.host` page
  4. switch over to the opened tabs and notice that the page didn't load correctly

**Actual result:**

![ssl](https://user-images.githubusercontent.com/2602313/39715377-1091e104-51fb-11e8-8d82-85f84fe96928.gif)

**Expected result:**

When opening any of the certificate issue websites via `command/ctrl` + `click`, it should load the correct page without initially loading `The site can't be reached`.

**Reproduces how often:**

100% reproducible when using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.702 
V8: 6.6.346.26 
rev: e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
Muon: 6.0.7 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Reproducible on current live release:**

No, currently not reproducible under `0.22.669` which is the latest released version.

### Additional Information

* Win 10 x64 - Reproduced by @srirambv 
* macOS x64 - Reproduced by @LaurenWags 

CCing @diracdeltas

**Comment by petemill** [comment]
I believe this is occuring because background tabs don't neccessarily have a window webContents when they begin to load. Therefore, we cannot get to the window to send the custom IPC message that we are sending on certificate error.
I have refactored this to work via redux actions in 2d5df77d97853d2a5fd4fad1d261304ccb13c5f1

**Comment by petemill** [comment]
Should be fixed in the next build

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
0.22.703 903b8d0d
libchromiumcontent 66.0.3359.139
muon: 6.0.8
