### ISSUE TITLE
Reconcile date is pushing back from last reconcileStamp rather than currentDate

### ISSUE THREAD

**Issue by jasonrsadler** [brave/browser-laptop#14042]
### Description
When Brave is started, and reconcile requirements have not been met, Brave pushes the reconcile date forward from the previous reconcileStamp rather than the current date.

### Steps to Reproduce

  1. Start Brave, enable payments, visit site to place in ledger.
  2. Exit Brave.
  3. Change reconcileStamp to 5 days before current date.
4. Start Brave
5. Next Contribution will show 'Overdue' and reconcile date will have advanced to 3 days after the reconcileStamp that was set (2 days before current date)
6. Exit Brave and restart
7. Next Contribution will show 'Overdue' and reconcile date will have advanced another 3 days after previous reconcileStamp (1 day after current date)
8. Exit and restart Brave. 
9. reconcileStamp will advance 3 more days but reconcile date in Brave will be the same as in step 7.
10. Quit and restart Brave.
11. Reconcile date will no longer be pushed out and will now match reconcileStamp 

**Actual result:**

If browser has not been used for up to 5 days past reconcile stamp and browsing requirements haven't been met, the browser will push the reconcile date forward 3 days from the last reconcile stamp. This will keep occurring every time the browser is started until the reconcile date is past 3 day pushback threshold. 

If browser has not been used for over 5 days past reconcile stamp and browsing requirements haven't been met, the browser will push the reconcile date forward 30 days from the current date.

**Expected result:**
If browser has not been used for some time past reconcile date and contribution browsing requirements have not been met, it is expected that the contribution date will be pushed out by 4 days (3 days + 1 day to give the user time to fulfill browsing requirements since a check and push is done when less than 3 days is detected)

**Reproduces how often:**

100

### Brave Version

**about:brave info:**

 
Brave: 0.24.0 
V8: 6.5.254.41 
rev: 30cc25b2bdccce2a9f38974af242e1d611a76ec2 
Muon: 5.1.2 
OS Release: 17.5.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.181

**Reproducible on current live release:**
Unknown

### Additional Information

#14006 partially addresses with push back message but reconcileStamp issue remains present.

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.706 e11b027
* libchromiumcontent 66.0.3359.139
* muon: 6.0.9 
Followed steps mention in https://github.com/brave/browser-laptop/pull/14057
