### ISSUE TITLE
TypeError: Error processing argument at index 0, conversion failure from undefined when using `Mute other tabs` with large profiles

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14058]
### Description

When attempting to `Mute other tabs` when you have a large profile, the browser will become unresponsive for ~1min and will spam the following error via the terminal:

```
TypeError: Error processing argument at index 0, conversion failure from undefined
    at Object.setAudioMuted (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/browser/tabs.js:933:11)
    at Immediate.setImmediate (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/browser/reducers/tabsReducer.js:361:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate (timers.js:617:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

However, running through the above case with `0.22.669` requires a force quit as the entire browser becomes unresponsive and never seems to recover.

### Steps to Reproduce

  1. launch `0.22.669` or `0.22.703`
  2. replace `session-store-1` with a profile from https://www.dropbox.com/sh/9sstz62vj41comg/AAD6fnZctgLlFfOXRzuQDWDla?dl=0
  3. once you've launched the profile, right click on a random tab and select `Mute other tabs`

**Actual result:**

![muteissue](https://user-images.githubusercontent.com/2602313/39775726-c1dd3e0a-52cc-11e8-9b3a-512c2204a304.gif)

**Expected result:**

It shouldn't be spamming the terminal with the above errors and Brave shouln't become unresponsive even though it ends up recovering.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.703 
V8: 6.6.346.26 
rev: 903b8d0d3703b5fdc5a719294403e7460d9b806d 
Muon: 6.0.8 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Reproducible on current live release:**

Yes, currently reproducible under `0.22.669` which is the latest released version.

### Additional Information

* macOS x64 - Reproduced by @kjozwiak & @LaurenWags 
* Win 10 x64 - Reproduced by @srirambv

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.706 e11b027
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
