### ISSUE TITLE
entire div for 'What do these policies mean?' is clickable

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14059]
### Description
On about:preferences#security there is a link below the WebRTC setting for 'What do these policies mean?' Only the link should be clickable, but the entire div is clickable.

### Steps to Reproduce

  1. Navigate to about:preferences#security
  2. Hover over 'What do these policies mean?' div and click anywhere on the div
  3. WebRTC wiki page is opened.

**Actual result:**
Entire div is clickable

**Expected result:**
Only the link should be clickable.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.703

**Reproducible on current live release:**
n/a

### Additional Information
Similar to https://github.com/brave/browser-laptop/issues/12137

**Comment by kjozwiak** [comment]
@bsclifton should we move this into `0.23.x`? I know we were moving issues out of `0.23.x` during the triage call but we already have #12137 fixed which is similar. Might as well fix all these cases if we can. Should be a trivial fix as well. Thoughts?

**Comment by bsclifton** [comment]
@kjozwiak since it's such a small one, I think we can skip on including it with 0.23.x.  However, this would be a great first bug for somebody (and we can pull into 0.23.x if it's done sooner than later)

**Comment by bsclifton** [comment]
Here's a picture showing the issue; the entire div is clickable, rather than using a span (or `inline-block`ing it, etc)
![screen shot 2018-05-08 at 4 40 22 pm](https://user-images.githubusercontent.com/4733304/39788310-b6e37714-52de-11e8-8f1d-0b47deac199f.png)

**Comment by thelostone-mc** [comment]
Hey first time contributor here! 

Had a few questions : 
- Since this is a html tag change -> I believe there aren't tests which I can write up for this 
- I added a gif to show the difference
- Whom do I reach out to add labels for my PR to state it's ready for review ?  (cause I don't have permissions)

**Comment by bsclifton** [comment]
Hi there @thelostone-mc 
- you are correct; no tests available and none required
- gif capturing it is great!
- I can help you with the review! 😄 👍
