### ISSUE TITLE
border around the recovering modal under Payments

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14055]
### Description

When recovering a wallet, the `recovering` modal has a border around it. It appears as `blue` on macOS and `orange` on Win.

### Steps to Reproduce

  1. launch `0.22.703`  903b8d0
  2. visit `about:preferences#payments` and enable `Payments`
  3. Once enabled, recover a previous wallet via `Advanced Settings`

**Actual result:**

<img width="782" alt="screen shot 2018-05-08 at 12 12 39 pm" src="https://user-images.githubusercontent.com/2602313/39772624-b6e43804-52c3-11e8-9970-f9919da788cc.png">

**Expected result:**

There shouldn't be a border around the `recovering` modal in `Payments`.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.703 
V8: 6.6.346.26 
rev: 903b8d0d3703b5fdc5a719294403e7460d9b806d 
Muon: 6.0.8 
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Reproducible on current live release:**

No, currently not reproducible under `0.22.669` which is the latest release.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.706 e11b027
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
