### ISSUE TITLE
opening extension background page from URL bar causes Brave to crash

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14079]
### Description
If you attempt to open the Sync background page (via the URL bar) Brave crashes.

### Steps to Reproduce

  1. Launch Brave with a clean profile from CLI.  (you can add some sites as bookmarks but it doesn't seem to matter)
  2. Enable Sync.
  3. Open a new tab and paste in the URL for the background page: chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/_generated_background_page.html

**Actual result:**
Brave Crashes and your recent changes are lost. Also ```Segmentation fault: 11``` displays in the terminal when Brave crashes.

**Expected result:**
Sync Background Page should be opened.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.703

**Reproducible on current live release:**
no, does not reproduce on 0.22.669

### Additional Information
Could be related to https://github.com/brave/browser-laptop/issues/14075 - if you try to open the Sync Background Page from the link on about:extensions, you get the error from this issue in the terminal.

**Comment by bsclifton** [comment]
Verified this happens in the latest release (Release channel, preview): 0.22.711

**Comment by bsclifton** [comment]
Happens on any other extension too; for example, 1Password:
chrome-extension://aomjjhallfgjeglblehebfpbcfeobpgk/_generated_background_page.html
