### ISSUE TITLE
[Question] Brave accesses Hideman Certificate

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#14077]
https://www.reddit.com/r/brave_browser/comments/8ho6b1/whats_brave_hideman_certificate/

**Comment by ckujau** [comment]
Google Translate says the screenshot says "`Brave wants to sign with the key "Hideman certificate" of your keychain`" and it was reported for `v0.22.669` on macOS and the reporter is _not_ using the [Hideman VPN service](https://www.hideman.net/). But how and when did this pop up show up? Is this reproducible? If so, how?

**Comment by tomlowenthal** [comment]
I don't think this issue is present in the new Chromium codebase.
