### ISSUE TITLE
Add a Paste and Go context menu option to the navbar.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1407]

**Comment by bbondy** [comment]
CC @bsclifton in case this would interest you.

**Comment by bsclifton** [comment]
Submitted this to get things started:
https://github.com/brave/browser-laptop/pull/1655

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/browser-laptop/pull/1670

**Comment by bbondy** [comment]
yep!
