### ISSUE TITLE
some sites aren't being added to payments after meeting minimum criteria

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14085]
### Description
Some sites aren't being added to the ledger table after the visit meets minimum criteria. An example is https://miaou.art

Reported via community: https://community.brave.com/t/publisher-is-not-yet-added-to-the-ledger-because-it-doesnt-meet-criteria-yet/21831

### Steps to Reproduce

  1. Enable Payments
  2. Navigate to https://miaou.art
  3. Wait until at least minimum criteria is met.
  4. Navigate back to Payments.

**Actual result:**
Site is not included in the ledger table. If you go back to https://miaou.art and hover over the URL icon you see this: 

![screen shot 2018-05-10 at 9 36 05 am](https://user-images.githubusercontent.com/28145373/39882653-62075704-5452-11e8-9500-6abdfcd2b5ec.png)

**Expected result:**
Site should be added to payments table after minimum criteria is met.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.669

**Reproducible on current live release:**
Yes

### Additional Information
Seems like https://github.com/brave/browser-laptop/issues/12675. See https://github.com/brave/browser-laptop/issues/14085#issuecomment-388122651.

**Comment by ryanml** [comment]
@LaurenWags curious, are you able to repro this on `0.24.0` ? I am not able to. Just want to determine if it may have been fixed recently.

**Comment by srirambv** [comment]
https://www.dbs.com.sg/treasures/aics/pdfController.page?pdfpath=/content/article/pdf/AIO/AIO_2016/SECTOR-19-001-blockchain-lowres.pdf doesn't get added even after staying on the page for 4 mins. However if i just visit the domain page it gets added to the ledger table.

**Comment by jasonrsadler** [comment]
miaou.art is using a css file from https://www.sharebutton.co/fonts/v2/entypo.min.css. The sharebutton site is using an expired certificate from a totally different site and causes resource load failures on page load. Not sure if that would contribute to the ledger add problem but an FYI.
