### ISSUE TITLE
some pinned publishers not paid

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14086]
Version: latest release, 0.22.669
OS: MacOS

I had 4 pinned publishers:
![screen shot 2018-05-10 at 9 55 37 am](https://user-images.githubusercontent.com/549654/39883368-8250a694-543b-11e8-89a0-448ef4097f63.png)

Only 2 of them were paid:
![screen shot 2018-05-10 at 9 56 00 am](https://user-images.githubusercontent.com/549654/39883388-9692ae36-543b-11e8-8a10-eba977890dda.png)

The two that weren't paid show nothing in the "Views" column; maybe related?  EDIT: nvm, this isn't the case; i misread the table

**Comment by kjozwiak** [comment]
CC'ing @NejcZdovc.

**Comment by kjozwiak** [comment]
@NejcZdovc move this into https://github.com/brave/browser-laptop/milestone/101 as #14111 is also in the same milestone?

**Comment by NejcZdovc** [comment]
@kjozwiak yeah, this two will be fixed together

**Comment by kjozwiak** [comment]
+1 from the community, seems like a similar issue.

* https://community.brave.com/t/significant-new-bug-in-payments-ui-since-recent-update/23278
