### ISSUE TITLE
WebRTC not fully disabled with Tor

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14091]
In a private tab with Tor, it doesn't look like WebRTC is fully disabled. Visiting <https://browserleaks.com/webrtc> with default shields settings caused Brave to access my webcam drivers and then expose a list of A/V devices to the site. IP address doesn't seem to have been exposed. 

![screen shot 2018-05-10 at 12 37 29 pm](https://user-images.githubusercontent.com/639937/39890422-92698b68-544f-11e8-845c-123ebf65ea68.png)

Related: #13397.

I'm using the test build with Tor available for private tabs.
 
Brave: 0.23.2 
V8: 6.6.346.26 
rev: c09cbf6ad24cabd9d4bf5a9f52ce8c3d8a04585c 
Muon: 6.1.0 
OS Release: 17.5.0 
Update Channel: Developer 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139

**Comment by riastradh-brave** [comment]
What we _automatically_ block in private tabs with Tor enabled is only the WebRTC IP leak.  We do not automatically block all (first-party) fingerprinting, but if you enable that in shields, then WebRTC is disabled altogether.  (Third-party fingerprinting is blocked by default.)

**Comment by diracdeltas** [comment]
if we turned on https://github.com/brave/browser-laptop/issues/13735, it would also block device enumerator in tor tabs

**Comment by diracdeltas** [comment]
i think this is actually fixed with #14402

**Comment by jumde** [comment]
Fixed by: https://github.com/brave/browser-laptop/pull/14402
Commit: 051109c

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
