### ISSUE TITLE
Dragging tab into empty tabsbar doesn't attach tab to window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14099]
### Description
Follow up of #14046 
Dragging tab into empty tabsbar doesn't attach tab to window

### Steps to Reproduce
  1. Create 4-5 tabs in a window 1
  2. Open a new window 2
  3. Drag a tab from window 1 into window 2 and drop in empty tabsbar
  4. Create a new window 3 instead of adding the tab to window 2

**Actual result:**
![14046_1](https://user-images.githubusercontent.com/17010094/39944737-c157700c-5535-11e8-93c8-ca92a6f1c495.gif)

**Expected result:**
Should attach tab into the window

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.709
-- | --
V8 | 6.6.346.26
rev | e043144
Muon | 6.0.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
Yes

### Additional Information
Follow up to #14046

**Comment by alexwykoff** [comment]
Fixed in Brave core
