### ISSUE TITLE
Opening a link in new private tab doesn't load over tor network

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14103]
### Description
Opening a link in new private tab doesn't load over tor network

### Steps to Reproduce
  1. Clean install 0.23.4
  2. Open a private tab and load check.torproject.org, shows `Congratulations. This browser is configured to use Tor.` Ensure IP is not your local public IP
  3. Open a normal tab, search for check tor
  4. Right click on check.torproject.org and open in a `New Private tab`
  5. Page isn't loaded over tor network, shows `Sorry. You are not using Tor.` and shows your actual public IP address

**Actual result:**
Opening a link in new private tab doesn't load over tor network

**Expected result:**
Should load all links over tor network even if link is opened via context menu from a normal/session tab

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.4
-- | --
V8 | 6.6.346.26
rev | b355561
Muon | 6.1.1
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
N/A

### Additional Information
cc: @diracdeltas @jumde @riastradh-brave @darkdh

**Comment by diracdeltas** [comment]
fixed by 5650e12

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181
