### ISSUE TITLE
Bookmark folder missing from right hand pane in Bookmark Manager

### ISSUE THREAD

**Issue by artella-coding** [brave/browser-laptop#14108]
### Description
On Brave desktop, when you click a bookmark folder in the left hand pane in the Bookmark Manager, the folders within this folder do not appear in the right hand pane (as they do in Chrome)

### Steps to Reproduce
  1.In "Other Bookmarks" creates a folder called "Test" 
  2.This folder "Test" does not appear in right hand pane (as it does in Chrome)

**Actual result:**
This is what we get in Brave. Notice the "Test" folder is **absent** in right hand pane in Brave Bookmarks Manager (see yellow circle) : 

![brave_bookmarkfoldersmissing](https://user-images.githubusercontent.com/4592812/39964921-ff67552c-5686-11e8-9a38-63866fd10a7e.JPG)

**Expected result:**
This is what we get in Chrome. Notice the "Test" folder is present in right hand pane in Chrome Bookmarks Manager (see blue circle) : 

![chrome_bookmarkfolders](https://user-images.githubusercontent.com/4592812/39964964-cb2fa452-5687-11e8-9129-8b0f55473e44.JPG)

### Brave Version
0.22.669

**Comment by srirambv** [comment]
Should be fixed in brave-core 

cc: @bsclifton
