### ISSUE TITLE
Creating new tab moves to first tab page and back again

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14101]
Reported by @alexwykoff 

### Description
When a new tab is added, the tab page briefly switches to the first one, and then back again the last one. This is because the tab is first created without an index, and put at the beginning, and then moved by muon to the last tab index.

### Steps to Reproduce

  1. Have multiple tab pages open and the last tab page active, with an active tab in that page
  2. Open a new tab (keyboard shortcut or new tab button

**Actual result:**
Tab is opened in the correct tab page but tab page switches to the first tab page and then quickly back again.

**Expected result:**
Tab page does not change

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.709

**Reproducible on current live release:**
No

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.712 e48c5ff
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
