### ISSUE TITLE
Check for Update doesn't work upon browser launch

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14119]
### Description
Check for Update doesn't work upon browser launch

### Steps to Reproduce
  1. Launch browser
  2. Check for update from kabob menu
  3. First time check for update doesn't work. Need to try again to see the notification bar

**Actual result:**
Check for Update doesn't work upon browser launch

**Expected result:**
Should work all the time

**Reproduces how often:**
Intermittent issue

### Brave Version

**about:brave info:**

Brave | 0.22.711
-- | --
V8 | 6.6.346.26
rev | 31d6bcc
Muon | 6.0.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
Yes

### Additional Information
Issue seen by @kjozwiak as well but not sure what triggers this problem. Doesn't happen all the time.

**Comment by kjozwiak** [comment]
I've definitively seen this a few times on macOS as well. Sometimes when you launch Brave and quickly check for an update via the hamburger menu, nothing happens. Clicking it again right after will display the notification bar letting you know that Brave is checking for an update.

**Comment by darkdh** [comment]
I can reproduce it all the time by
[session-store-1.zip](https://github.com/brave/browser-laptop/files/2006358/session-store-1.zip)

@bsclifton

**Comment by bsclifton** [comment]
I don't think we'll have time to address this before switching to [brave-core](https://github.com/brave/brave-browser)
