### ISSUE TITLE
Sort for visits and time spent is not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14111]
### Description

If you click on table header for time or visits on Brave Payments page table is not sorted correctly

### Steps to Reproduce

  1. Enable payments
  2. Add some publishers
  3. Close browser
  3. Pick first publisher from the synopsis and remove duration and views props
  4. Start browser again and sort via time or visit

**Actual result:**

Table is sorted strangely.

**Expected result:**
Sort should be sorted correctly.

**Reproduces how often:**

Reproduced on Cliftons profile, can't reproduce on a fresh profile

**Comment by NejcZdovc** [comment]
Why this happens is because first entry in the table has views and time empty (undefined) and because of that sorting is not working

**Comment by NejcZdovc** [comment]
related to #14086

**Comment by davidtemkin** [comment]
Let's prioritize this @NejcZdovc @bsclifton

**Comment by ryanml** [comment]
@NejcZdovc could you share a small snapshot of the synopsis that allowed you to repro this?

Removing those props all together seems to remove those publishers from showing in the ledger table, and overriding those props to `undefined` seems to produce expected sorting behavior (As if those values were 0)

**Comment by NejcZdovc** [comment]
@davidtemkin 0.23?

**Comment by davidtemkin** [comment]
Think so. We will decide in tomorrow's triage.

**Comment by mojoaxel** [comment]
Same issue here (0.22.669). 
Columns get sorted by string and not by number:
![image](https://user-images.githubusercontent.com/600565/40079215-67f8cb6e-5887-11e8-88c2-b038590e97df.png)

**Comment by mojoaxel** [comment]
I can confirm this is has been fixed :tada:
