### ISSUE TITLE
disable Tor tabs by default in 0.23.x

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14124]
since tor was switched with Sync on the roadmap, we won't have enough time for beta Tor testing to have sufficient confidence to enable it by default.

**Comment by diracdeltas** [comment]
fixed by bb28f2b954165c16f9469050f00fd24a7d438810

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 - 6565c06
* Muon - 7.1.0
* libchromiumcontent - 67.0.3396.87
