### ISSUE TITLE
I imported the search/browsing history, slowed to a crawl

### ISSUE THREAD

**Issue by ile** [brave/browser-laptop#14126]
### Description
I imported the search/browsing history from Chromium, and entering anything in the location/search bar hangs Brave for something like 10-15 seconds.

Don't know if it's reproducible (though I suppose it is), so I leave this just here.

 
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 4.4.0-124-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by bsclifton** [comment]
@ile how many bookmarks do you have? After the 10-15 seconds, are things OK?

**Comment by ile** [comment]
Things are OK after 10-15 seconds. This happens every time though so it makes it pretty much unusable as the 10-15 delay is there every time.

I don't have that many bookmarks (less than 200 maybe), but I imported also the browsing history and there may be a lot of that.

**Comment by ile** [comment]
For some reason it doesn't happen now/anymore.

I'm now running:

 
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 4.4.0-124-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by jonathansampson** [comment]
I believe another user on Twitter recently experienced the same thing. After clearing their history they reported that hang-times dropped from ~10s to ~0.5s.

https://twitter.com/napersmikekim/status/1008194324889264129

**Comment by zzamboni** [comment]
I experienced the same problem after importing my browsing history from Chrome (11,501 items, according to Chrome). Typing anything into the URL bar would cause an initial delay of up to ~10 seconds, afterwards things were OK. Removing `~/Library/Application Support/brave/History` solved the problem.

```
Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Comment by leshik** [comment]
I experience the same issue with Brave 0.23.105/macOS.

I remember several years ago Safari had the same issue if you had a lot of history (like, for a year). They fixed it somehow.

Let me know if I can help to troubleshoot this issue (which is very annoying, but I wouldn't like to clear all my history though.)

**Comment by bsclifton** [comment]
I don't think we'll be able to address this issue for the Muon based product. Instead, can folks having this problem try our [Developer channel build](https://brave.com/download-dev)?
https://brave.com/download-dev

This issue should be resolved there 😄 This build will be making its way to Beta and eventually Release channels too

**Comment by zzamboni** [comment]
@bsclifton indeed, the problem does not happen in Brave-Dev (which I've been using for the last few days as my main browser, without major issues). Thanks! 😄
