### ISSUE TITLE
redo Tor newtab UI to remove Tor logo

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14121]
also need to add '/' at the end of the url: https://torproject.org/

**Comment by diracdeltas** [comment]
fixed by a93cfd4 and 5a737889fec05569a1a22b2847f4ac5392579c9a

**Comment by kjozwiak** [comment]
@diracdeltas @bradleyrichter there isn't much information here for QA. I'm assuming the old design included the Tor logo under `about:newtab` for PT's which has been removed. Can you please confirm that this is the current design:

<img width="1459" alt="screen shot 2018-06-20 at 12 00 48 pm" src="https://user-images.githubusercontent.com/2602313/41670224-b86314a4-7481-11e8-91dc-33f8bd7ca8c0.png">

Once confirmed, I'll quickly create a test plan in the original issue and tag this issue as `QA/test-plan-specified`.

**Comment by rossmoody** [comment]
@kjozwiak I've been working on this screen quite a bit and can confirm there is no Tor branding elements anywhere except for the fav.ico in regular type reading "Tor" in the tab when it's enabled

**Comment by kjozwiak** [comment]
Verified on `macOS 10.13.4 x64` using the following build:

* `0.23.12` 88f6f0767c05ba5c4793ec2430a5cd742092fa6d 
* muon: `7.1.1`
* libchromiumcontent: `67.0.3396.87`
