### ISSUE TITLE
Clear More User Data

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1413]
**NOTE: this issue has been replaced by #2472** 

This issue decribes the UX to allow the user to clear their private data. in this first version, any selected data types will be cleared back to the install day of the browser. In a later version, we will add the ability to clear backwards for 1 hour, 1 day, 1 week, 1 month, or all data.

![screen shot 2016-04-19 at 2 02 40 pm](https://cloud.githubusercontent.com/assets/13509546/14655718/69c04268-0638-11e6-8599-92801a6f7274.png)

The images show the new prefs panel for General prefs. For this task, we will only implement the 2 new items inside the green box, and the modal DIV dialog. (modal to prefs but not the browser)

The choices for both items are:
- never
- when I close Brave
(never is the default in both items)

Selecting "Clear all browsing data now..." opens the modal DIV:

![screen shot 2016-04-19 at 2 01 22 pm](https://cloud.githubusercontent.com/assets/13509546/14655787/d6381ea2-0638-11e6-909a-ee4bcf7bb7c9.png)

The default checkboxes are indicated above. 
"Delete individual cookies..." is a placeholder for a future shortcut to the cookie manager window. Do not implement as part of this task.

When the DIV opens, the content underneath is disabled and dimmed by a 40% opacity white box.

In the top right, the X button = cancel, closing the box with no changes regardless of what the user may have changed.

@bbondy Please let me know if more detail is needed...

**Comment by diracdeltas** [comment]
should there also be a select element for `Clear my cookies and cache`? (either `never` or `when i close brave`)
