### ISSUE TITLE
Error data persist after new load

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14133]
### Description

If page is not loaded for some reason and then you fix this problem, loaded page will not be recorded, because error data is still in the state for that tab

### Steps to Reproduce

  1. enable payments
  2. go to https://www.youtube.co1m/user/radio1slovenia/videos
  3. fix url in this tab to https://www.youtube.co1m/user/radio1slovenia/videos
  4. click on one video

**Actual result:**

Publisher is not added to the table

**Expected result:**
Publisher should be added to the table

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

Yes

**Comment by bsclifton** [comment]
Closing as `wontfix`- we can address this or scenarios like this if they arise with [brave-core](https://github.com/brave/brave-browser) 😄
