### ISSUE TITLE
Scroll doesn't work on joinhoney.com

### ISSUE THREAD

**Issue by sakibarifin** [brave/browser-laptop#14138]
### Description

Mouse scroll doesn't work on joinhoney.com. Trying to scroll does nothing. I tried scrolling on at least three pages of joinhoney.com and had the same result.

### Steps to Reproduce

  1. Visit https://www.joinhoney.com/features/droplist
  2. Try to scroll down using the mouse scroll
  3. Tested on these pages as well and had the same result: https://www.joinhoney.com/trending/stores | https://www.joinhoney.com/features/honeygold

**Actual result:**
Mouse scroll doesn't work on joinhoney.com

**Expected result:**
Mouse scroll button should work on joinhoney.com

**Reproduces how often:**
100%

### Brave Version
Brave | 0.22.669
V8 | 6.6.346.24
rev | 6cda2e8
Muon | 5.2.7
OS Release | Windows 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0

**Reproducible on current live release:**
Yes.

**Comment by Tomatoshadow2** [comment]
Can't reproduce on latest beta or Release on Mac, maybe a Windows specific bug?

**Comment by btlechowski** [comment]
I could not reproduce on Windows 7 x64 v0.22.714.

**Comment by sakibarifin** [comment]
@btlechowski @Tomatoshadow2 Yes, it looks like the latest update fixed the bug.
