### ISSUE TITLE
Unable to delete multiple publishers from deleted list 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14137]
### Description
Issue reported by @kjozwiak . Unable to delete multiple publishers from deleted list 

### Steps to Reproduce
  1. Enable payments and add simulated payments 
  2. Delete a few publishers from the ledger table
  3. Click on show deleted publishers to bring up the deleted publishers list modal 
  4. Modal closes when you delete a single publisher from the list

**Actual result:**
![issue](https://user-images.githubusercontent.com/17010094/40074145-d4592dd0-5846-11e8-8314-15f8a474b82c.gif)

**Expected result:**
Add a checkbox where user can choose multiple publisher and click on delete to remove them. Something similar to the no script modal 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.712
-- | --
V8 | 6.6.346.26
rev | e48c5ff
Muon | 6.0.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
Yes

**Comment by ryanml** [comment]
Just checking in on the approach here; would we prefer:

1. A "checkbox" approach, where you can check multiple sites, then choose "Remove selected sites"
or
2. Simply keep the deleted sites modal open, and allow users to simply click to delete sites that they wish, keeping the modal open until it is dismissed.

cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
@RyanJarv I would go with the second one
