### ISSUE TITLE
Dragging a tab out and into its own window and then closing it causes all windows to close.

### ISSUE THREAD

**Issue by givanse** [brave/browser-laptop#14144]
### Steps to Reproduce

  1. Have multiple tabs open in a single window, call it `W1`.
  2. Drag one tab out of `W1` into its own new window, call it `W2`.
  3. Click either the `x` on the tab we just extracted `W2` or the `x` on the new window `W2`.
  4. The first window (`W1`) closes too.

To avoid that problem, I drag the tab back from `W2` into `W1` and then I close that tab.

This only happens when there is a single tab. Opening and closing N tabs in the second window `W2` works fine. The problem reproduces only once you close the last tab.

**Actual result:**

All windows are closed.

**Expected result:**

Only the window I clicked `x` is closed.

**Reproduces how often:**
Always.

### Brave Version

```
Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 10.0.15063 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```

It is reproducible on current live release.

**Comment by Tomatoshadow2** [comment]
Couldn't reproduce on latest Beta on Mac. Also you might want to update Brave and see if the problem is still there. 
 
Brave: 0.22.716 
V8: 6.6.346.32 
rev: 5ae68e8994b83385a75fbb5ebd4d1cd8081ad45e 
Muon: 6.0.11 
OS Release: 17.5.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by bsclifton** [comment]
@givanse we've had two releases after the report you had above- can you confirm this still happens?

**Comment by givanse** [comment]
```Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 10.0.15063 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170```

I have no repro :)
