### ISSUE TITLE
Disabling payments when backup notification is shown doesn't dismiss it automatically(Follow up to #13425 )

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14149]
### Description
Disabling payments when backup notification is shown doesn't dismiss it automatically

### Steps to Reproduce
  1. Enable payments and fund wallet
  2. Ensure you receive notification to backup wallet 
  3. Disable payments, notification persists doesn't dismiss (which is not expected)
  4. Click on `Backup now` in notification
  5. Payments page is opened in a new tab 
  6. Enabling payments shows the  backup code modal immediately (which is expected)

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/40124380-702297f6-58f6-11e8-9191-50fc18dfca23.png)

**Expected result:**
Should automatically click later in notification bar if payment is disabled 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.714
-- | --
V8 | 6.6.346.26
rev | fa2fbca
Muon | 6.0.9
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
No

**Comment by jasonrsadler** [comment]
@mandar-brave This notification is shown only after a user has added funds. If they disable payments while the notification is in the air, would we want to dismiss it automatically?

**Comment by mandar-brave** [comment]
@srirambv the backup action is to protect the wallet corruption and BAT (actual monies) left in the wallet. its not clear to me that stopping payments to publishers has anything to do with it. the entire idea if backing up is to protect the wallet  (monies can be moved in to wallet from elsewhere including future ads, tipping, etc.)

@jasonrsadler - lets DM with Sri; but to me this is functioning as desired

**Comment by srirambv** [comment]
@mandar-brave sounds good. Closing the issue as its working as expected.
