### ISSUE TITLE
Need webdriver executable to run selenium test from python

### ISSUE THREAD

**Issue by vairamsvsjdo** [brave/browser-laptop#14151]
I am looking for webdriver executable to run selenium test from python
Thanks

**Comment by Tomatoshadow2** [comment]
Are you wanting this as a feature request?

**Comment by bsclifton** [comment]
Hi there @vairamsvsjdo 

Are you wanting to test Brave using webdriver/selenium (in Python)?

It's going to be hard to test with anything other than JavaScript... the testing has layers:
- Selenium on top of Chromium
- webdriver (node.js bindings) on top of Selenium
- spectron on top of webdriver (Electron specific tweaks)

I'm going to close this issue- but would encourage you to reply back. I'd like to help understand what your question is.  Thanks!

**Comment by vairamsvsjdo** [comment]
I am looking equivalent to this: http://chromedriver.chromium.org/downloads
For brave browser where is the driver

**Comment by bsclifton** [comment]
@vairamsvsjdo here's a link to our Muon release (which is used for browser-laptop). You can download the Chromedriver there:
https://github.com/brave/muon/releases/tag/v6.0.9

Please be aware that it'll need some custom configuration. You can look at the browser-laptop testing code to see how the initialization is done

**Comment by GeetaSarvadnya** [comment]
@vairamsvsjdo : you can download latest Brave driver (Brave.exe) from Brave official website.
