### ISSUE TITLE
Fingerprinting protection breaks uphold verification process

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14152]
Reported here: https://www.reddit.com/r/BATProject/comments/8jsk19/fairly_important_bug/
> I had to verify on uphold last night due to hitting their unregistered trading limit. Brave gave me the swirling loading sign of perpetuity and would not allow me to upload my pictures on step 2 of verification. This is pretty major as uphold is supposedly one of the trading platforms we suggest new users use, and it needs to work seamlessly with Brave

## Steps to reproduce
1. Create an uphold account
2. Attempt to verify account (ensure `Fingerprinting protection` is set to `Block third party fingerprinting`
3. Get stuck on step 2 (photo upload)

**Comment by srirambv** [comment]
This only works for a clean install. Tried auto update from `0.22.710` prev beta version. Upon upgrade there is no site exception added. 

cc: @diracdeltas
