### ISSUE TITLE
New Tor circuit info link needs to be changed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14156]
### Description
New Tor circuit info link needs to be changed

### Steps to Reproduce
  1. Update to 0.23.6 
  2. Open a private tab and visit a site
  3. Click on shields, click on `New Tor circuit` info button, points to an non existing wikipage

**Actual result:**
New tor circuit info link points to an non existent wiki page

**Expected result:**
Should point to FAQ section 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.6
-- | --
V8 | 6.6.346.32
rev | c89a943
Muon | 6.1.4
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.181

**Reproducible on current live release:**
N/A

### Additional Information
cc: @diracdeltas

**Comment by diracdeltas** [comment]
fixed in 992f77d42ddd85b33184a189453fc50978096305

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.8 06c657bb7ee5530f93c37f51cc6b7bf158912d04
* Muon 6.1.5
* libchromiumcontent 66.0.3359.181

**Comment by srirambv** [comment]
Looks good followup issue #14510
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
