### ISSUE TITLE
Tabs opened via links with target attribute sometimes do not render, and open at incorrect index

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14159]
### Description
As reported by @jonathansampson, happens when clicking on a link which has `target="_blank"` or `target="foo"` but **not** `rel="opener"`. When `rel="opener"` _is_ present, the tab is opened at the correct index (opener tab index + 1), and renders correctly.

Also happens when testing cross-origin destination, blank rendering is less reproducible when pointing at a larger site destination, like brave.com | google.com. Detaching / re-attaching WebContents from <webview> does not force the contents to become composited, but a **refresh** will.

- **Does not reproduce when cmd-clicking link**

### Steps to Reproduce

  1. Open https://jonathansampson.github.io/browser-tests/brave/new-tab-location/index.html
  2. Click the 'Non-REL' link

**Actual result:**
- Tab content does not display
- Tab is opened at the end of the tab strip

**Expected result:**
- Tab content displays
- Tab index is opener-Tab-index + 1

**Reproduces how often:**
99%

### Brave Version
0.22.714
muon 6.0.9

**Comment by LaurenWags** [comment]
+1 from https://community.brave.com/t/bug-tab-opens-link-attribute-target-blank-at-right-end-of-tab-list-instead-of-next-to-tab-containing-link-and-blank-tab-instead-of-the-linked-web-page-windows-10/22169

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14177

**Comment by LaurenWags** [comment]
@petemill are there additional tests QA should run outside of the Steps to Reproduce?

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.718 11dcd19
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
