### ISSUE TITLE
Brave incorrectly blocks SproutVideo as an ad or tracker

### ISSUE THREAD

**Issue by podman** [brave/browser-laptop#14160]
### Steps to Reproduce

  1. Open Brave with "Block Ads" enabled.
  2. Go to https://podman.vids.io/videos/d49bdfbb1016e2ce5c/blade-skillet
  3. The video will not play.

**Actual result:**

The video does not play and the object URL necessary for video playback is blocked.
![default](https://user-images.githubusercontent.com/51639/40186251-a152911a-59c2-11e8-855f-68a422231d85.png)

**Expected result:**
Video should play and the object URL should not be blocked

**Reproduces how often:**
100% of the time

### Brave Version

**about:brave info:**
Brave: 0.22.714 
V8: 6.6.346.26 
rev: fa2fbcae947e001528bd3bd5b1c453805d419af6 
Muon: 6.0.9 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139

**Reproducible on current live release:**
Yes

### Additional Information
This happens for every video hosted by SproutVideo embedded on any third-party site. As the CTO of SproutVideo, I can help debug things on our end if needed.

**Comment by snyderp** [comment]
I'm not able to recreate on beta (even using the given URL in the issue)

**Comment by podman** [comment]
@snyderp I can no longer recreate this bug using the latest version of brave either:
 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 18.0.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

I guess this was resolved between then and now. I'll mark this as closed.
