### ISSUE TITLE
Disintermediate links on popular sites

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14163]
Popular sites — search engines, social networks — often rewrite outbound links for tracking purposes. We should disintermediate these links and let users just head straight to their destinations. https://www.eff.org/deeplinks/2018/05/privacy-badger-rolls-out-new-ways-fight-facebook-tracking

**Comment by BrendanEich** [comment]
@bridiver has experience with Google SERP links. I am in favor of fixing this issue to match or exceed PB.

**Comment by flamsmark** [comment]
Moving to the new codebase: brave/brave-browser#535
