### ISSUE TITLE
update tor hashes to version with libevent

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14165]
depends on https://github.com/brave/tor_build_scripts/issues/4 and @jumde uploading new builds to S3

**Comment by darkdh** [comment]
closed by https://github.com/brave/browser-laptop/pull/14164

**Comment by kjozwiak** [comment]
@diracdeltas @darkdh is there anything that QA can do here? I don't see any information/STR that we could use to check and see if this has been fixed. Seems like #14164 doesn't have much information either. If there's nothing that QA can do here, lets remove the `QA/test-plan-required` tag and replace it with `QA/no-qa-needed`.

**Comment by darkdh** [comment]
I added `QA/no-qa-needed`. as long as you can successfully launch tor in Mac, it is verified.
It used to show libevent not found error because of dynamic link and not everyone has the library installed on their Mac so we can't make that assumption. The fix is to static link libevent into tor binary.

**Comment by kjozwiak** [comment]
Thanks @darkdh, going to quickly add a test plan in the original comment and mark this as `QA/test-plan-specified` & `OS/macOS`.

**Comment by kjozwiak** [comment]
Verified on macOS `10.13.4 x64` using the following build:

* `0.23.11` 6565c0689f8bfbd6f4d03e2e8c68c9381da157f6 
* muon: 7.1.0 
* libchromiumcontent: 67.0.3396.87

Ensured that the Tor service started without any issues, example:

```
Kamils-MBP:browser-laptop kjozwiak$ /Applications/Brave-Beta.app/Contents/MacOS/Brave-Beta
Crash reporting enabled
Jun 20 12:21:28.023 [notice] Tor 0.3.3.6 (git-7dd0813e783ae16e) running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2o, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jun 20 12:21:28.024 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jun 20 12:21:28.025 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jun 20 12:21:28.033 [notice] Scheduler type KISTLite has been enabled.
Jun 20 12:21:28.033 [notice] Opening Socks listener on 127.0.0.1:9260
Jun 20 12:21:28.034 [notice] Opening Control listener on 127.0.0.1:0
Jun 20 12:21:28.034 [notice] Control listener listening on port 58338.
tor: daemon listens on 127.0.0.1:9260
tor still not ready
Tor ready!
```

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 using
* 0.23.11 6565c06
* Muon 7.1.0
* libchromiumcontent 67.0.3396.87

Laurens-MacBook-Pro:~ laurenwagner$ /Users/laurenwagner/BraveDocuments/Laptop/Brave\ Beta/Brave-Beta.app/Contents/MacOS/Brave-Beta
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
Crash reporting enabled
Jun 20 12:25:15.469 [notice] Tor 0.3.3.6 (git-7dd0813e783ae16e) running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2o, Zlib 1.2.8, Liblzma N/A, and Libzstd N/A.
Jun 20 12:25:15.469 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jun 20 12:25:15.470 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jun 20 12:25:15.484 [notice] Scheduler type KISTLite has been enabled.
Jun 20 12:25:15.485 [notice] Opening Socks listener on 127.0.0.1:9260
Jun 20 12:25:15.485 [notice] Opening Control listener on 127.0.0.1:0
Jun 20 12:25:15.485 [notice] Control listener listening on port 63595.
tor: daemon listens on 127.0.0.1:9260
tor still not ready
2018-06-20 12:25:17.609 Brave-Beta Helper[25939:1634249] Couldn't set selectedTextBackgroundColor from default ()
Tor ready!

**Comment by kjozwiak** [comment]
Verified on `macOS 10.13.4 x64` using the following build:

* `0.23.12` 88f6f0767c05ba5c4793ec2430a5cd742092fa6d 
* muon: `7.1.1`
* libchromiumcontent: `67.0.3396.87`

Ensured that the Tor service started without any issues, example:

```
Kamils-MBP:~ kjozwiak$ /Applications/Brave-Beta.app/Contents/MacOS/Brave-Beta
Crash reporting enabled
Jun 22 00:03:59.016 [notice] Tor 0.3.3.7 (git-035a35178c92da94) running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2o, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Jun 22 00:03:59.016 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Jun 22 00:03:59.016 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Jun 22 00:03:59.019 [notice] Scheduler type KISTLite has been enabled.
Jun 22 00:03:59.019 [notice] Opening Socks listener on 127.0.0.1:9260
Jun 22 00:03:59.020 [notice] Opening Control listener on 127.0.0.1:0
Jun 22 00:03:59.020 [notice] Control listener listening on port 52227.
tor: daemon listens on 127.0.0.1:9260
tor still not ready
Tor ready!
```
