### ISSUE TITLE
WebRTC block sometimes not working on private tabs running tor

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14174]
### Description
WebRTC not working on private tabs running tor

### Steps to Reproduce
  1. Clean install 0.23.7 
  2. Open a private tab and visit  https://diafygi.github.io/webrtc-ips/, no local ip address is shown
  3. Disable shields, still no local ip address shown
  4. Open a new private tab, disable Tor
  5. Visit  https://diafygi.github.io/webrtc-ips/ in the same tab from step 4, local ip address is shown
  6. Enable Block all fingerprint, local ip not shown
  7. Open a  3rd private tab and enable Tor
  8. Visit  https://diafygi.github.io/webrtc-ips/ in 3rd private tab
  9. Open shields, block all fingerprint is enabled which should not show local ip address but still shows the local IP

**Actual result:**
WebRTC block not working on private tabs running tor

**Expected result:**
Should work correctly

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.7
-- | --
V8 | 6.6.346.32
rev | f0e0dea
Muon | 6.1.5
OS Release | 10.0.16299
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.181

**Reproducible on current live release:**
N/A

**Comment by diracdeltas** [comment]
repro'ed this using simpler steps:

1. go to https://diafygi.github.io/webrtc-ips/ in tor private tab
2. disable shields
3. webrtc still blocked
4. open new tor tab, go to https://diafygi.github.io/webrtc-ips/ again
5. webrtc not blocked this time

**Comment by diracdeltas** [comment]
currently blocked on https://github.com/brave/muon/issues/602

**Comment by jumde** [comment]
Fixed by: https://github.com/brave/browser-laptop/pull/14402
