### ISSUE TITLE
add tab UI indicator of whether a private tab is running Tor

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14175]
If a user opens a bunch of private tabs and turns the tor switch off in some of them, it gets confusing to remember which tabs were Tor ones and which ones weren't. We should add some iconography to the tab to show that it's a Tor tab (similar to the icon for private tab and session tabs).

cc @bradleyrichter @rossmoody for an icon we can use

**Comment by alexwykoff** [comment]
We'll need a bit of a tighter icon for use in the tab control @rossmoody

**Comment by diracdeltas** [comment]
fixed by 6a5e8a9ced214a2d368053dab4d5391b6ef40318 for now

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
