### ISSUE TITLE
UGP captcha

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14188]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64. I needed to be pixel perfect for it to work.
* 0.22.722 1dde2a2d834ef6cdf21a04be4e9bdacac6e7324f
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
