### ISSUE TITLE
Last contribution: Currently processing, Next contribution: Overdue

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#14194]
I’ve been in this state for the last 8 days:

Last contribution: Currently processing, Next contribution: Overdue

Prior to that, I was in this state for about five weeks:

Last contribution: January 2018, Next contribution: Overdue

My ledger holds about 9 hours worth of browsing. My monthly budget matches my account balance: 15  🦇. My advanced settings: backup wallet displays a badly written poem.

Brave 0.22.714 on Fedora Linux.

**Comment by eljuno** [comment]
Related to #13156?

**Comment by da2x** [comment]
I just got a toolbar: “Hello! Your Brave Payments account is waiting for a deposit. [Turn Off] [Later] [Add Funds]”

But my account balance already satisfies the monthly budget.

**Comment by da2x** [comment]
I just had a failing payment go through. It’s in my payment history and everything. Fun fact: I had 15 BAT in this wallet. I just had a 15 BAT payment process. My wallet now contains 10 BAT. Contribution Statement shows 15 BAT. I even pulled up a backup from a few days ago to confirm that my account balance was 15 BAT.

Update. I clicked on the monthly budget dropdown and my account balance dropped to 0. When I restart Brave it goes back up to 10 BAT until I click on the budget drop down again.
