### ISSUE TITLE
Security: Brave vulnerable to socially-engineered XSS

### ISSUE THREAD

**Issue by ericlaw1979** [brave/browser-laptop#1419]
Modern browsers strip the javascript: prefix when pasting in the address bar to mitigate the (astoundingly common and successful) self-inflicted XSS attack vector.

Brave should too. 

https://blogs.msdn.microsoft.com/ieinternals/2011/05/19/socially-engineered-xss-attacks/

CTRL+L
CTRL+V
javascript:alert(document.domain);

**Comment by diracdeltas** [comment]
thanks, eric. i fixed this for all `javascript: ` strings entered in the urlbar, not just copy paste, in case people can be socially-engineered into typing `javascript: ` manually and then typing/copying-pasting the XSS vector. the one downside is that this makes it harder to search for queries like `JavaScript: The Good Parts`.
