### ISSUE TITLE
how do you merge chrome API in the electron

### ISSUE THREAD

**Issue by yyf1994gggg** [brave/browser-laptop#14195]
I am develop a browser based on eletron,I need to add a chrome extensions  ,just like chrome browser. when I read your source code. I found that there is a global   variable is  called "chrome" ,Could you tell me that where it comes from,where you define it.   Could y help me 

![eeeeeeeeeeeee](https://user-images.githubusercontent.com/31838744/40306049-bdfd8034-5d2f-11e8-98d0-f85fcbed7c0a.jpg)

**Comment by bsclifton** [comment]
@yyf1994gggg thanks for the question - you're going to want to check out the code we're using, Muon:
https://github.com/brave/muon

The extension APIs are implemented there.  In particular, you may want to check out https://github.com/brave/muon/blob/master/lib/browser/api/extensions.js
