### ISSUE TITLE
New Windows don't respond

### ISSUE THREAD

**Issue by freeman292** [brave/browser-laptop#14196]
### Description
When opening new windows, the URL field doesn't show up and none of the buttons work. You can't minimize or close or do anything with the window.

### Steps to Reproduce

  1. Settings
  2. New Window
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**
34%

### Brave Version

**about:brave info:**

Brave | 0.22.714 Windows 10

**Reproducible on current live release:**
Brave | 0.22.714 Windows 10

**Comment by TheAresjej** [comment]
+1 / Reproduces how often: 100% - Windows 10 (17134.48) & Brave 0.22.714

**Comment by bsclifton** [comment]
Closing as stale (no other comments, +1s, or updates)

Please re-open if you are still experiencing the problem and we can help troubleshoot further. Thanks! 😄
