### ISSUE TITLE
Add support for batch voting

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14190]
### Description

Currently we are sending every vote as a single request. Let's batch this requests into one.

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64. Made the contribution on staging.
* 0.22.722 1dde2a2d834ef6cdf21a04be4e9bdacac6e7324f
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
