### ISSUE TITLE
Tweak preview tabs timeout

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#142]
1) It should delay a bit more when moving from 1 tab to the other so there is no active tab in between. 
2) Play with the hover time to avoid accidental previews but also don't make it too long.
3) The time it takes to reset to the "you need to hover" seems a bit too long

**Comment by bbondy** [comment]
@BrendanEich suggest doing this based on pointer velocity instead of just timeout.  I think that's a great idea.

**Comment by luixxiul** [comment]
+1 from support
