### ISSUE TITLE
No immediate visual feedback from URL bar before page starts to load

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14207]
### Description
After typing a URL into the URL bar and hitting enter, there's no immediate visual feedback at first; then after a delay the orange peel in the tab title starts spinning.

### Steps to Reproduce

  1. Open a Brave tab (to amplify the effect: a private tab with Tor enabled).
  2. Type in a URL.
  3. Hit enter.

**Actual result:**
There is a noticeable delay before the orange peel in the tab title starts spinning, ranging from a fraction of a second to several seconds in private tabs with Tor enabled.

**Expected result:**
There should be immediate visual feedback that Brave has acknowledged the URL input and is trying to make a connection.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.7
V8 | 6.6.346.26
rev | c2b3eda
Muon | 6.0.11
OS Release | 4.13.0-41-generic
Update Channel |  
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
yes

### Additional Information
The effect is amplified in private tabs with Tor enabled.

**Comment by srirambv** [comment]
Clicking on the info button in shields opens a new tor tab but there is no visual indication that the connection is being setup before the page is loaded. Sometime it takes ~10 secs to load the page which makes it look like the page isn't loaded unless the user waits that long.

![tor1](https://user-images.githubusercontent.com/17010094/41247222-5f569078-6d7b-11e8-9860-15059274acc9.gif)
