### ISSUE TITLE
Imported bookmarks are not shown in bookmark manager - Bravebeta V0.22.718

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14208]
### Description

Imported bookmarks are not shown in bookmark manager - Bravebeta V0.22.718

### Steps to Reproduce

 1.   Launch Bravebeta with a clean profile
2.   Bookmark any website on bookmark toolbar by clicking on start button 
3.    Create multiple folders on bookmark toolbar (e.g folder 1 and 2)
4.   Add bookmarks to folders by right clicking on the each folder (e.g folder 1 contains google, folder 2 contains twitter and youtube)
5.    Go to bookmarks manager import bookmarks (brave_sorted_5000  - imported HTML file)
6.   Export the bookmarks 
7.    Open the exported file with Bravebeta

**Actual result:**

Bookmark manager is not showing bookmarks (imported + User created bookmarks)

**Expected result:**
When user navigated to Bookmark manager, bookmarks should be shown to user

**Reproduces how often:**

100%

### Brave Version

Bravebeta 0.22.718

![bookmarkexportissue](https://user-images.githubusercontent.com/38657976/40378320-d82ade7a-5e10-11e8-9728-870f6149676d.gif)

**Reproducible on current live release:**
Yes

**Comment by rebron** [comment]
Closing. Looks like this is fixed in brave-core. https://brave.com/download-dev
