### ISSUE TITLE
Brave locks up when opening

### ISSUE THREAD

**Issue by wws35801** [brave/browser-laptop#14205]
### Steps to Reproduce

  1. Open a new window and enter the following link:
"https://tv.youtube.com/watch/HZWKGZQ-Y2Q?vpp=2AEA"
  2.You will get a rotating red half circle in the tab and it will lock up such that the browser becomes unresponsive.
  3.I an not sophisticated enough to remove the default setting which I assume is in the registry.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
@wws35801 do you have more information about this?

Sounds like you're on Windows- which OS version are you on? Does the same link work fine in Chrome or Firefox? Please let us know- thanks

**Comment by wws35801** [comment]
![image](https://user-images.githubusercontent.com/39407377/42096485-136880c8-7b7b-11e8-95cb-1a44e1ca4735.png)
_mage of locked up browser_
![image](https://user-images.githubusercontent.com/39407377/42096638-7d3bf5fc-7b7b-11e8-99e5-55eafb011f1b.png)
I have never had a problem opening this page but it is shown on the Image: https://feedly.com/i/my
It appears to be the untitled tab that is causing the problem. If I quickly close the "https://feedly.com/i/my" tab I am left with About:blank in the link with the tab titled "Untitled".  I cannot close the Untitled page no matter what I do.

**Comment by wws35801** [comment]
"Does the same link work fine in Chrome or Firefox? Please let us know- thanks"  It works great on Chrome and having just installed Firefox it appears to work great there.  The lock up first started with one untitled tab when I clicked on a link such as the link on this web page "https://iotwreport.com/tom-steyer-using-convicted-russian-spy-to-promote-green-energy-campaign/from" using the "MORE HERE" link that links to : "http://www.cfact.org/2018/06/28/tom-steyer-using-convicted-russian-spy-to-promote-green-energy-campaign/"  Closing the browser and rebooting would get rid of the problem with the locked tab.  Then the whole browser started locking up and I filed the issue.  
Do you have a tool to clean the register of all entries relating to Brave so that I can start over with a clean registry?
