### ISSUE TITLE
Tab gets pinned when opening a notification or opening a file in browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14215]
### Description
Tab gets pinned when opening a notification or opening a file in browser. 

### Steps to Reproduce
Scenario 1: (reproduced on @GeetaSarvadnya machine
  1. Have brave and brave-beta open
  2. Export bookmarks from brave-beta
  3. Right click exported bookmark and open in brave-beta
  4. Opens two new window apart from the one already opened and a tab is got pinned 

Scenario 2
  1. Have brave and brave-beta open
  2. Have brave as default browser
  3. Click no any notification from other app which launches a web link ( i got a notification to install an update for pia  and opened the download link
  4. Brave opened a new window apart from the one already open and a tab was automatically pinned

**Actual result:**
Tab gets pinned when opening a notification or opening a file in browser

**Expected result:**
Tab should not get pinned 

**Reproduces how often:**
No idea

### Brave Version

**about:brave info:**

Brave | 0.22.714 | 0.22.718
-- | -- | --
V8 | 6.6.346.26 | 6.6.346.26
rev | fa2fbca | 11dcd19
Muon | 6.0.9 |6.0.12
OS Release | 10.0.17134 | 10.0.17134
Update Channel | Release| Beta
OS Architecture | x64 | x64
OS Platform | Microsoft Windows | Microsoft Windows
Node.js | 7.9.0| 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139 | 66.0.3359.170

**Reproducible on current live release:**
Yes

### Additional Information
cc: @petemill @bsclifton

**Comment by edmundlaugasson** [comment]
I can confirm that if the tab is pinned and trying to open a link in new tab - this one gets pinned as well.
Using:
Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71
