### ISSUE TITLE
eBay Picture Uploader doesn't work, neither does WooCommerce (Wordpress)

### ISSUE THREAD

**Issue by SilverPuppy** [brave/browser-laptop#14221]
Using the latest Brave version, uploading pictures to an eBay listing fails with a weird error. The progress bars all go to 100% but then they say the picture is not valid. This has forced me to go to FireFaux, which I hate to do because they treated Brendan shamefully, and it's slow as well.

I have also experienced this with the mobile version of Brave, though the version I use on mobile is out of date. It seems that something Brave does is not compatible with what eBay is attempting to do.

**Comment by SilverPuppy** [comment]
I just realized that WooCommerce, a WordPress add-in, has a very similar problem. When attempting to add pictures, they just don't get uploaded. WooCommerce just hangs.

I strongly suspect this is the same issue, and related to scripting.

**Comment by SilverPuppy** [comment]
I just thought about trying WooCommerce (Wordpress) with Bravery turned off. It does work that way. I will report back once I've tried eBay without Bravery.

**Comment by SilverPuppy** [comment]
![error ebay pictures](https://user-images.githubusercontent.com/23507077/40989983-760926fe-68bd-11e8-8768-87ce2b7df314.png)

It seems to have something to do with the size of the file. Large JPEGs from my phone universally don't work in Brave, but I was able to upload them with no issues in FireFaux. One smaller JPEG and a few small PNGs did work in Brave.

My Brave is always up to date (I take updates as soon as they're offered to me) and it is bone stock. I don't feel the need to bolt anything on; it's a great package as it is.

**Comment by SilverPuppy** [comment]
I just tried again with shields down, and all of the images which failed did succeed that way. I also double checked that indeed it is 0.22.727 and yes I am using that version.

Obviously shields down is a workaround.

**Comment by bsclifton** [comment]
I've been using the eBay picture uploader with `brave-core` and it's been working great- closing as `fixed-with-brave-core`
