### ISSUE TITLE
Fix UGP claim related text to help user understand grant may be expiring

### ISSUE THREAD

**Issue by mandar-brave** [brave/browser-laptop#14229]
Issue hasnt been filed yet
Duplicate was filed at https://github.com/brave/internal/issues/341 and recreating here and closing 341

### Steps to Reproduce
  1. Users accept grants
  2. Forget that grants have 90 days expiry
  3. During expiration or after contribute BAT to realize BAT has disappeared from balance

**Actual result:**
See user feedback from reddit
- confusing states of contribution
- confusing balances (BAT is missing but statement shows differently)

**Expected result:**
- need to explicitly ensure that users know BAT has an expiration timetable
- and adjust balance to differentiate between BAT grants and other (with expiry dates called out)

**Reproduces how often:**
100% o ftime

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

Yes

### Additional Information

Recommended fixes via attached files
![image 1](https://user-images.githubusercontent.com/35932307/40466006-7745da38-5ed8-11e8-8a2e-533b7431850a.png)

![image 2](https://user-images.githubusercontent.com/9574457/40527088-b612c632-5fea-11e8-9b0b-06fe47ec0c58.png)

@NejcZdovc @bradleyrichter @evq @davidtemkin

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.722 1dde2a2d834ef6cdf21a04be4e9bdacac6e7324f
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
