### ISSUE TITLE
Visiting Netflix in a private tab shows Widevine notification on normal tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14227]
### Description
Visiting Netflix in a private tab shows Widevine notification on normal tabs

### Steps to Reproduce

  1. Install 0.23.7
  2. Open a private tor tab
  3. Visit Netflix, no widevine plugin notification is shown to enable it
  4. Switch to a normal tab, shows the widevine plugin notification for Netflix opened in a private tab

**Actual result:**
![netflix](https://user-images.githubusercontent.com/17010094/40461282-93c1002a-5ed8-11e8-92bb-18192a7135c6.gif)

**Expected result:**
Should not show the notification in a normal tab for a site visited in private tab

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.7
-- | --
V8 | 6.6.346.32
rev | f0e0dea
Muon | 6.1.5
OS Release | 10.0.17134
Update Channel | Developer
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.181

**Reproducible on current live release:**
N/A

### Additional Information
cc: @diracdeltas @riastradh-brave

**Comment by alexwykoff** [comment]
@flamsmark who might you traffic-cop this particular issue toward as it was introduced with the new private tabs?

**Comment by diracdeltas** [comment]
are we sure this is a new issue? if so does it exist when tor is turned off?

**Comment by diracdeltas** [comment]
i guess it's probably related to the fact that the widevine notification is supposed to not appear on Tor tabs (#13626)

**Comment by srirambv** [comment]
@diracdeltas yes based on #13626  it shouldn't prompt on tor tab or normal tab when you visit Netflix on a tor tab

**Comment by diracdeltas** [comment]
assigning to myself since @flamsmark is busy with ads trial initiative

**Comment by diracdeltas** [comment]
fixed by c097adce038a749d2474c102c0c2951b95815fb3

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
* Seeing the below error similar to Tor browser
![image](https://user-images.githubusercontent.com/17010094/41856385-f15f0454-7862-11e8-932e-88d014b0dd5c.png)
