### ISSUE TITLE
partner subscription page is no longer active tab on launch

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14220]
## Test plan
1. Delete all files in the profile folder for the version of Brave being tested
2. Create a new file `promoCode` and put the referral code into that file (a partner who has a page)
3. Launch Brave
4. You should see three tabs (in this order):
    - New Tab
    - Welcome
    - Partner page 

### Description
Previously when you downloaded from a partner specific page and launched Brave (version 0.22.22) the subscription tab was the active tab as well as the 3rd tab . However, with version 0.22.669 that changed, the subscription tab is now the 2nd tab and the about:welcome tab is now the active tab (as well as 3rd tab).

### Steps to Reproduce

  1. Download and clean install of Brave (0.22.669 or higher) from a partner page.
  2. Launch Brave.
  3.

**Actual result:**
Subscription tab is 2nd tab. It is not the active tab.
![subscription-022714](https://user-images.githubusercontent.com/28145373/40428968-7a808d24-5e6f-11e8-8e9f-076f6d1bed44.gif)

**Expected result:**
Subscription tab should be 3rd tab, it should also be the active tab. 
![subscription-02222](https://user-images.githubusercontent.com/28145373/40428989-869c6e84-5e6f-11e8-9f10-bd0b34a7b0a4.gif)

**Reproduces how often:**
easly

### Brave Version

**about:brave info:**
0.22.669 and 0.22.714

**Reproducible on current live release:**
Yes

### Additional Information
screen grab of issue occurring when using 0.22.669 also:
![subscription-022669](https://user-images.githubusercontent.com/28145373/40434895-67a2146c-5e7d-11e8-9c32-762ddbc209a4.gif)

**Comment by kjozwiak** [comment]
@btlechowski @srirambv @LaurenWags and myself checked iOS & android which works as expected. Once you launch Brave, the promotional page appears in a new tab which becomes the active tab.

This only affects the desktop on macOS & Win.
