### ISSUE TITLE
captcha icon sometimes overlaps text 

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14226]
### Description

When clicking on `Claim my free tokens`, sometimes the BAT captcha icon will overlap some of the text that's being displayed in the modal as well.

### Steps to Reproduce

  1. launch brave using `LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging` (used `0.24.100` de50a5a which was provided by @NejcZdovc)
  2. go into `about:preferences#payments` and enable Brave Payments
  3. click on `Claim my free tokens`

Repeat the above and you'll eventually notice that the BAT icon will overlap text that's in the modal.

**Actual result:**

<img width="877" alt="screen shot 2018-05-23 at 6 11 18 pm" src="https://user-images.githubusercontent.com/2602313/40455046-35203578-5eb9-11e8-922d-cc123b601244.png">

<img width="828" alt="screen shot 2018-05-23 at 6 09 53 pm" src="https://user-images.githubusercontent.com/2602313/40455050-3a451000-5eb9-11e8-904d-db64bd3e9e26.png">

**Expected result:**

The captcha icon shouldn't be overlapping text on the screen.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.24.100 
V8: 6.6.346.32 
rev: de50a5a6b058be47b5cf958cd65215793c0a335b 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Nightly 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Reproducible on current live release:**

No, the captcha feature is slated to be released in this milestone.

**Comment by NejcZdovc** [comment]
fixed in #14189
