### ISSUE TITLE
Toggling shields breaks the security indicator on URLs with hash

### ISSUE THREAD

**Issue by garrettr** [brave/browser-laptop#14231]
## Test plan
See https://github.com/brave/browser-laptop/pull/14232

### Description

The security indicator in the address bar is sometimes incorrect for https://mail.google.com while the user is logged in. The icon should be a gray closed lock, indicating a secure connection, but sometimes it is a red open lock. Toggling shields on or off reliably causes the incorrect red open lock icon to be shown.

### Steps to Reproduce

1. Log in to Gmail (https://mail.google.com) in Brave
2. Observe the (correct) gray closed lock icon for the secure origin
3. Toggle shields
4. Observe the (incorrect) red open lock icon for the secure origin

<img width="823" alt="screen shot 2018-05-23 at 11 09 01 pm" src="https://user-images.githubusercontent.com/407302/40467511-147e9c8a-5edf-11e8-8e1b-ecdd20837260.png">

**Reproduces how often:** 100%

### Brave Version

Name | Version
-- | --
Brave | 0.22.714
V8 | 6.6.346.26
rev | fa2fbca
Muon | 6.0.9
OS Release | 17.5.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:** Yes

### Additional Information

Originally reported on [Twitter](https://twitter.com/huertanix/status/999501738913751041).

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.721 bfe7cdd026c68013236ebe206a33448db9370fca
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
