### ISSUE TITLE
Addressbar displays hidden extensions URL for new tab

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14239]
### Steps to Reproduce

  1. Clean profile
  2. Press + for new tab

**Actual result:**
Addressbar displays `chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-newtab.html`
![image](https://user-images.githubusercontent.com/34715963/40494475-3d3e1f56-5f75-11e8-9baf-95f93bffc1e3.png)

**Expected result:**
After new tab adressbar is empty

**Reproduces how often:**
100%

### Brave Version
 
```
Brave: 0.22.801 
V8: 6.7.288.33 
rev: 6ec9f53d0178df2d614e6d92597f1d7762d33ce6 
Muon: 7.0.0 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.48
```

~@LaurenWags and @kjozwiak reported that this is not reproducible on MacOS~

**Reproducible on current live release:**
No

cc @bsclifton @petemill @bridiver

**Comment by srirambv** [comment]
Not reproducible on Windows.

**Comment by LaurenWags** [comment]
Was able to reproduce on macOS with these STR:

**Comment by hferreiro** [comment]
The issue seems to be fixed after https://github.com/brave/muon/commit/8868bc4b70533f728aa1543db60f5100772ca2fc, which was pushed after the release.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.806 0d30970
* muon 7.0.3
* libchromiumcontent 67.0.3396.62
