### ISSUE TITLE
Look up from context menu does not work

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14247]
### Description
On macOS when you highlight and right click on text, there is an option on the right-click menu for 'Look up' which will look up your selected text. In cr67 this is not working.

### Steps to Reproduce

1. Open a webpage
2. Highlight some text
3. Right click on the text and select the ‘Look up’ option from context menu

**Actual result:**
Context menu goes away, but popup displaying information about selected text does not display. No errors in terminal either.

**Expected result:**
A popup should display, which shows information about your selected text:
![screen shot 2018-05-24 at 2 41 36 pm](https://user-images.githubusercontent.com/28145373/40504889-94f12bcc-5f60-11e8-9925-fbe9cced1fda.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.801

**Reproducible on current live release:**
No

**Comment by bridiver** [comment]
https://github.com/brave/muon/pull/604

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.806 0d30970
* Muon 7.0.3
* libchromiumcontent 67.0.3396.62
