### ISSUE TITLE
dismissing the captcha when user disables/enables Payments while captcha is visible

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14242]
### Description

When a user disables `Payments` while the captcha is still visible/active, re-enabling the wallet shouldn't show the captcha again. However, the user can click on `Claim my free tokens` once again and attempt to go through the captcha.

### Steps to Reproduce

  1. launch brave using `LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging` (used `0.24.100` de50a5a which was provided by @NejcZdovc)
  2. go into `about:preferences#payments` and enable Brave Payments
  3. click on `Claim my free tokens`
  4. Disable `Payments` via the `Off/On` switch under `about:preferences#payments`
  5. re-enable `Payments` via the `Off/On` switch under `about:preferences#payments`

**Actual result:**

![captchaissue](https://user-images.githubusercontent.com/2602313/40499172-1d440eca-5f4f-11e8-8a68-bc006f9c6801.gif)

**Expected result:**

When a user disables `Payments` while the captcha is still visible, the captcha modal shouldn't be visible when re-enabling and should be dismissed. However, the user will still be able to click on `Claim my free tokens` and get the captcha again.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.24.100 
V8: 6.6.346.32 
rev: de50a5a6b058be47b5cf958cd65215793c0a335b 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Nightly 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Reproducible on current live release:**

No, this is a new feature that's being added into `0.22.x Release 5`. It's not available in the current released version.

**Comment by NejcZdovc** [comment]
fixed in #14189
