### ISSUE TITLE
Terminal logs setTabStripWindowId

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14240]
### Steps to Reproduce

  1. Clean profile
  2. Run Brave through terminal

**Actual result:**
Terminal logs:
```
setTabStripWindowId: tab with ID 1 not found!
setTabStripWindowId: tab with ID 2 not found!
```

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.801 
V8: 6.7.288.33 
rev: 6ec9f53d0178df2d614e6d92597f1d7762d33ce6 
Muon: 7.0.0 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.48
```

Also reproduced by @LaurenWags on MacOS

**Reproducible on current live release:**
no

cc @bsclifton @kjozwiak @bridiver @srirambv @GeetaSarvadnya 

edit: there is a discussion in #chromium-upgrades regarding this issue

**Comment by srirambv** [comment]
This error is logged every time a tab is opened.

**Comment by hferreiro** [comment]
This should be fixed after https://github.com/brave/muon/commit/8868bc4b70533f728aa1543db60f5100772ca2fc.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.806 0d30970
* Muon 7.0.3
* libchromiumcontent 67.0.3396.62
