### ISSUE TITLE
Suggestion for Tab Page Template to have a preview similar to Tab Previews

### ISSUE THREAD

**Issue by fidelt** [brave/browser-laptop#1424]
![tab-page-template](https://cloud.githubusercontent.com/assets/5409093/14698977/6431a65e-07c6-11e6-9634-cd6fccbb17c9.png)

It would be nice if Tab Page Templates could display the list of tabs they contain on mouse hover. This could really help one find which page a particular tab that they are looking for is located at quickly.

**Comment by bradleyrichter** [comment]
@fidelt Glad you suggested this as we planned for it but haven't had time to implement it yet. 

The concept is to have the tabs fade in quickly over the current tabs, only while you are in mouse-over, thus providing a quick preview of the tab set.

I think this is a key missing feature that should make tab sets much more comfortable/usable.

**Comment by bradleyrichter** [comment]
CC @cezaraugusto
