### ISSUE TITLE
changing "Congrats" message when user accepts grant

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14241]
### Description

We'll need to change the "Congrats" summary that the user receives when they accept a UGP grant. The current message was for the `Million Dollar Giveaway` campaign. However, because this is a new campaign, we should look into changing the message rather than using the same one again.

### Steps to Reproduce

  1. launch brave using `LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging` (used `0.24.100` de50a5a which was provided by @NejcZdovc)
  2. go into `about:preferences#payments` and enable Brave Payments
  3. click on `Claim my free tokens`
  4. once you get the captcha, attempt to close it via `ESC` or `X`

**Actual result:**

<img width="885" alt="screen shot 2018-05-24 at 12 23 07 pm" src="https://user-images.githubusercontent.com/2602313/40498660-97230036-5f4d-11e8-98e5-19ad8bcc6270.png">

**Expected result:**

We should change the `Congrats` message to something new as the current `Million Dollar Giveaway` message is for the old campaign that has already been launched.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.24.100 
V8: 6.6.346.32 
rev: de50a5a6b058be47b5cf958cd65215793c0a335b 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Nightly 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Reproducible on current live release:**

Yes, I believe the `Congrats` message is sent via server side, so anyone accepting a UGP grant will see the `Million Dollar Giveaway` message, including users on the current release.

### Additional Information

CCing @mandar-brave @davidtemkin @bradleyrichter

**Comment by mandar-brave** [comment]
her is the final @NejcZdovc - thank you @bradleyrichter 
![image](https://user-images.githubusercontent.com/35932307/40520898-80461b98-5f7d-11e8-8d1e-6b3b126e9dc6.png)

**Comment by NejcZdovc** [comment]
cc @evq

**Comment by kjozwiak** [comment]
Any progress on this? Have we added this message into production/staging?

**Comment by NejcZdovc** [comment]
@kjozwiak I don't think so

**Comment by kjozwiak** [comment]
@evq has updated the staging server with the new text/message. Going to close this issue off but we'll also need to check this against production.

@srirambv @LaurenWags @btlechowski @GeetaSarvadnya when we do a run against production once the build is released, remember to check of we're using the new message/text when a user accepts the grant.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.725 e6dd17f
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
![image](https://user-images.githubusercontent.com/17010094/40865766-0e10de9a-65c8-11e8-98f5-ec7ef6eea1b3.png)

**Comment by kjozwiak** [comment]
@mandar-brave please take a look at the screenshot @srirambv added and confirm that this is the expected message we're going with. It differs a bit near the end compared to the spec screenshot https://github.com/brave/browser-laptop/issues/14241#issuecomment-391911229 but I think the current one sounds better.

**Comment by bradleyrichter** [comment]
@kjozwiak Thanks for the heads up. I think it sounds good as implemented in the new screen shot above.
