### ISSUE TITLE
reCAPTCHA is sometimes broken

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14256]
### Description
Sometimes when I hit a site with reCAPTCHA, such as CloudFlare-fronted sites in private tabs with Tor enabled, my attempt to check the 'I'm not a robot' box to activate the captcha has no effect.

### Steps to Reproduce

  1. Open a private tab with Tor enabled.
  2. Browse to a site with reCAPTCHA.  Random example: universalhub.com
  3. Click the 'I'm not a robot' checkbox.

**Actual result:**
No reaction.  No captcha pops up.  The site remains inaccessible.
![fail](https://user-images.githubusercontent.com/34034191/40569446-4079b3d6-6071-11e8-88fc-7a2897f73c73.png)

**Expected result:**
A captcha should pop up and grant access to the site once you have provided a modicum of help to our robot overlords in learn to pass a driving test.
![captcha](https://user-images.githubusercontent.com/34034191/40569464-59603082-6071-11e8-9177-171878256471.png)

**Reproduces how often:**
100%, so far in memory, but I got so used to clicking through the captchas that I could have done so in this browser without remembering.

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.7
V8 | 6.6.346.26
rev | 86e51d0
Muon | 6.0.11
OS Release | 4.13.0-41-generic
Update Channel |  
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.139

**Reproducible on current live release:**
Unsure.  The only test I know offhand, https://www.google.com/recaptcha/api2/demo, works anyway, and live releases don't have Tor support yet.

**Comment by riastradh-brave** [comment]
Tried with shields down, no change.

**Comment by riastradh-brave** [comment]
I tried with a fresh build and clean ~/.config/brave-development, and it worked fine.  If I come across this again, I'll try to study the circumstances under which it arises and reopen this.

**Comment by notnotbilly** [comment]
Still having this exact problem on 9/11/2018
