### ISSUE TITLE
Browser crash when opening target=_blank links

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14252]
### Description
Bravebeta is   getting crashed when user click on YouTube in embedded video

### Steps to Reproduce
1. Launch Brave with clean profile from CLI
2. Enable Payments
3. Run any embedded video
4. Verify the time capture for publishers in   Ledger
5. Click on YouTube in embedded video

**Actual result:**
Bravebeta is getting crashed

**Expected result:**
Bravebeta should  not crash video should start running in Youtube from the point where it has stopped in embedded video run

**Reproduces how often:**
100%

### Brave Version
0.22.802

**Reproducible on current live release:**
No

**Comment by LaurenWags** [comment]
Also found that I did not have to enable payments for this crash to occur. I used these STR on version 0.22.802:
Navigate to a site with an embedded YT video (like https://www.neowin.net/news/lg-g7-thinq-unboxing-and-first-impressions ) 
Start playing the YT video on the site
Click on 'YouTube' on the video
Brave-Beta crashes

**Comment by LaurenWags** [comment]
![image](https://user-images.githubusercontent.com/28145373/40559416-b0e87bf4-6024-11e8-8d69-27647fcd02c1.png)

Brave is crashing when links have target=_blank, STR in issue are an example. Other examples:
- opening an article from news.google.com
- navigate to brianbondy.com and click on the twitter icon
In both cases, as with YT, Brave crashes.

**Comment by bridiver** [comment]
@GeetaSarvadnya - please provide specific instructions for items like 3 and 5. Exact urls to use, etc...

**Comment by srirambv** [comment]
@bridiver  You can use this link https://www.neowin.net/news/dell-xps-15-2-in-1-review-i-absolutely-love-it

Scroll down and click the YT video and then clicking on the YouTube button on the embedded video causes it to crash

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/pull/601
will be available in muon 7.0.1

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.806 0d30970
* muon 7.0.3
* libchromiumcontent 67.0.3396.62
