### ISSUE TITLE
on launch all tabs load at once

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14255]
### Description
All tabs load on launch with 0.22.802.

### Steps to Reproduce

  1. Have a profile with many tabs (I was using the one with 4 windows, 150 tabs per window from @petemill for single webview testing) and some bookmarks (7k)
  2. Use this profile with current release version, 0.22.714. Note that only active tabs are loaded on launch.
  3. Now use this profile with beta 0.22.802.

**Actual result:**
All tabs load on launch, Brave becomes unresponsive while tabs attempt to load, computer sounds like a jet engine. If you click on a tab that is not the active one you will find that it is already loaded (although you may experience https://github.com/brave/browser-laptop/issues/14249#issuecomment-392091571)
Additionally, many of the tabs (about half) loaded with about:error, seems like that's related to them all trying to load at once.

**Expected result:**
Only active tabs should be loaded on launch. When you click on a tab for the first time it should load when you make it active.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.802

**Reproducible on current live release:**
no

### Additional Information
In addition to STR above, could use STR from this issue for testing as well:  https://github.com/brave/browser-laptop/issues/12976

**Comment by hferreiro** [comment]
This seems to be working ok in 7.0.1

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.806 0d30970
* Muon 7.0.3
* libchromiumcontent 67.0.3396.62
