### ISSUE TITLE
When trying to login with Patreon I get a black background with a mini broken webpage image at the center

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#14259]
### Description
When going to a site such as https://www.patreon.com/ and going to login I get a white image which looks like an image for a broken web page along with the background going black. I can't get this on all sites but Patreon > Log In is where I experience

### Steps to Reproduce

  1. Go to https://www.patreon.com/
  2. Press "Log In" at the top right
  3. Should get a white broken little image in the center with a black background

**Actual result:**
 I should be able to login to my patreon account and view patreon related things

**Expected result:**
Upon pressing "Log in" I get a white image that looks like an image that displays when a webpage broke along with a black background. 
Image: https://puu.sh/Auf89/8ab0300ea8.png

**Reproduces how often:**
100% of the time. Tried restarting the browser

### Brave Version

Name | Version
-- | --
Brave | 0.22.802
V8 | 6.7.288.33
rev | 15522aa
Muon | 7.0.0
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.48

**Reproducible on current live release:**
It is not reproducible in the version downloaded from: https://www.brave.com/
Version: 0.22.721

### Additional Information
Image: https://puu.sh/Auf89/8ab0300ea8.png

**Comment by JMccormick264** [comment]
This issue has been fixed with patreon in the latest beta release. Feel free to close the issue if you think it's ready to be closed @alexwykoff

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.806 0d30970
* Muon 7.0.3
* libchromiumcontent 67.0.3396.62
