### ISSUE TITLE
Page Contents Missing

### ISSUE THREAD

**Issue by CarolSmall** [brave/browser-laptop#1425]
I've just visited http://www.oddschecker.com/politics/british-politics/eu-referendum/referendum-on-eu-membership-result.  The page contents (bookmaker odds for the UK referendum) were missing.  Using other browswers (Safari, TOR, Chrome) they are correctly displayed.

It looks like the odds are shown very briefly and then disappear and are replaced with the banner "Faster, safer ads coming soon to this place".

I'm running:
Brave: 0.9.1
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 5.10.0
Update channel: dev

on a MAC late 2012 running OSX El Capitan.

**Comment by luixxiul** [comment]
What is replaced is an ad and that's how Brave works.
