### ISSUE TITLE
Add to Payments icon in the URL bar is not enabling or turning to orange colour even after media publishers got added to ledger

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14253]
### Description

Add to Payments   icon in the URL bar is not enabling or turning to orange colour even after   publishers got added to ledger

### Steps to Reproduce

1. Launch Brave with   clean profile from CLI
2. Enable Payments
3. Run YouTube/Twitch videos, watch videos   for more than 8 secs

**Actual result:**
Add to Payments   icon in the URL bar is not enabling or turing to orange colour even after   spending default 8sec on watching YouTube/Twitch videos

**Expected result:**
Add to Payments icon should get enabled or turn to orange colour once the publishers gets added to ledger

**Reproduces how often:**
100
### Brave Version
0.22.802

**Reproducible on current live release:**
No

### Additional Information
 It's only adding the domain and listing the publishers as included but no UI indication for it

**Comment by ryanml** [comment]
@GeetaSarvadnya can you please verify if this problem exists on `0.24.0` (master)? I am not able to repro there, this should have been fixed with #13900

**Comment by GeetaSarvadnya** [comment]
@ryanml I am able to reproduce the issue on 0.24.0 (Master) also. 
Add to Payments icon in the URL bar is not enabling or turning to orange color even after spending default 8sec on watching YouTube/Twitch videos

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya youtube and twitch videos are not reflected in the payment icon. Is this working with regular sites like clifton.io?

**Comment by GeetaSarvadnya** [comment]
@NejcZdovc Yes, its working for clifton.io website i am able to see Add to payments icon enabled for this site.
For YouTube and Twitch i am not able to see icon enabled. 
https://drive.google.com/open?id=17YN5A-RrlKu9PIz7scYIFUA9-P4kmdpi

**Comment by NejcZdovc** [comment]
@srirambv correct, because media publishers are not linked to this icon

**Comment by srirambv** [comment]
@NejcZdovc thanks but was this change for media publisher part of #13900 ? Because previously we used to see the pub icon in URL bar enable for all videos and wouldn't add only if we disabled the option in advance settings.

**Comment by NejcZdovc** [comment]
@srirambv this was changed when we stop recording pages as youtube. What you saw in the URL bar was connected to the youtube publisher. For example if you add youtube to the table, icon should be orange.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/youtube-publisher-is-not-yet-added-to-the-ledger-because-it-doesn-t-meet-criteria-yet/22922
