### ISSUE TITLE
TAB GOES BLANK/shows wrong web page

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#14258]
### Description
Sometimes the tab;s page will go blank. 

### Steps to Reproduce

  1. Load a bunch of tabs like youtube, tradingview, etc
  2. Switch between tabs often.

**Actual result:**
Sometime the page of the tab wil lbe blank. Other times, it will show the wrong web page for that tab.

**Expected result:**
Switching tabs should work.

**Reproduces how often:**
random.

### Brave Version

**about:brave info:**

Brave | 0.22.721
-- | --
V8 | 6.6.346.32
rev | bfe7cdd
Muon | 6.0.12
OS Release | 17.5.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

### Additional Information
Did not have this problm with the older version.

**Comment by Tomatoshadow2** [comment]
https://github.com/brave/browser-laptop/issues/14249 Does this issue, relate to your actual result part at all?

**Comment by GarrettS** [comment]
what result part

**Comment by GarrettS** [comment]
#14249 looks similar to my issue. I will test later…

**Comment by JMccormick264** [comment]
I am getting this but my browser crashes. Opening a hyperlink for my Final grades on my college website which opens to open a new tab but has `about:blank` in the address bar. Then after a second or two my browser crashes.

Beta version of Brave.
`about:brave` info:

Name | Version
-- | --
Brave | 0.22.802
V8 | 6.7.288.33
rev | 15522aa
Muon | 7.0.0
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.48

**Comment by GarrettS** [comment]
The wrong tab is shown. I saw the mouseover preview of the GDAX tab, then clicked the etherscan tab and saw the Etherscan tab active with the GDAX webpage loaded. 

Undo the mouseover preview feature. It was not helpful. It gets in the way using a laptop when inadvertently touching trackpad with thumb and causing the entire webpage to show differently. 

U/X avoid using mouseover to activate things, unless activation context has already been established under certain circumstances. Mouseover preview means that I can't move my mouse across the tab bar without changing up the entire view of the page. Instead, I must move the mouse up from the document, and never across the tab strip. Bevause if I do, I will be activating preview for each tab. User unintentional action being misinterpreted as an action causes distraction to the user. In this case, it is not just that I didn't need a preview; you are distracting me by showing the ENTIRE PAGE of EVERY TAB that the cursor happens to hover. That is a big distraction and i need to get shit done, not be distracted by your developers' nifty clever bad idea. I want not to see every fucking document when switching tabs.

MOuseover preview also takes processing power.  something that I wanted is not just bad idea, it introduced  instability in the browser and will cause endless frustration for developers to maintain a lousy feature that annoys users in the majority of cases. Don't do that. 

Mouseover also is buggy, as implement.  

Mouseover preview is a bad idea and is implemented it badly with bugs as displayed. IT is done at the expense of the user's attention (ironic, isn't it), CPU (ironic, isn't it), and it doesn't work.

Hire someone for U/I and U/X. The U/X for payments integration is painful and confusing. 

![image](https://user-images.githubusercontent.com/56098/40745390-33b3bc0c-640c-11e8-9460-ecd95dca91d6.png)

**Comment by bsclifton** [comment]
cc: @bridiver @petemill

**Comment by GarrettS** [comment]
LATEST UPDATE WITH THE LATEST VERSION* OF BRAVE BROWSER. WITHIN JUST A FEW MINUTES OF USING THIS BROWSER VERSION, I EXPERIENCED SO MANY PROBLEMS THAT I COULD NOT CAPTURE THEM ALL.

GMAIL TAB SHOWED GDAX, THEN WENT BLANK:— 
![image](https://user-images.githubusercontent.com/56098/41130986-15a5229c-6a6e-11e8-8383-71def6140662.png)

ARTS4ALL TAB SHOWS GDAX:—
![image](https://user-images.githubusercontent.com/56098/41130867-863ba2c0-6a6d-11e8-8fe8-497daa458e50.png)

![image](https://user-images.githubusercontent.com/56098/40889085-47e2d6ac-6715-11e8-9f5e-500be5be8e6f.png)

* 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

As @bsclifton waved in #14317, "there are some known issues with the wrong tab being displayed (as you've noted in #14258)."

Even the blind would have experienced the issue with typing described, so yeah, "known issue". Why would you ship/version? Did leadership know about this? Intriguing⸮

**Comment by bsclifton** [comment]
@GarrettS we're doing the best we can given the staff/resources/etc that we have. There's a lot of non-visible work happening right now by folks on Brave Core which is not launched yet

My best advice is: if you're getting frustrated with Brave, maybe take a break and check back on us when Brave Core launches. We had originally posted details about this here:
https://brave.com/development-plans-for-upcoming-release/
