### ISSUE TITLE
Bad display of some items with Overblog

### ISSUE THREAD

**Issue by Bathrax** [brave/browser-laptop#1426]
Hi everybody,

I have a display error with my overblog site (www.paleomania.com).
I send you a printscreen.

Best regards,

Bathrax.
![brave1](https://cloud.githubusercontent.com/assets/18592951/14705191/9e9e451c-07b8-11e6-95ee-49a04eaf01a4.jpg)

**Comment by luixxiul** [comment]
Hi, I compared how the page is displayed on Brave and Chrome, but I didn't find the difference. Would you please indicate what you think is error? Thanks.

**Comment by Bathrax** [comment]
Problem is that the black panel with "Le Vieux Fossile (PALEOMANIA)" is over another item of the page. But you're right, it's the same problem with Chrome and Firefox, so I think it's an overblog prolem. I will report it to them.

Sorry to disturb you, and thank you for your magic browser.

Yves  :o))

**Comment by luixxiul** [comment]
I see. Thanks for reporting anyway, closing.
