### ISSUE TITLE
Remove ballot delay

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14263]
### Description

We should remove ballot delay, because we have random delays from 10s to 1min for every request. If we have ballots delay we are loosing batching optimization in some cases.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.724 1f07e93
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
* Verified with PDF's, pinned pubs and media pubs. everything got listed in the payment history
