### ISSUE TITLE
Add static pins for Amazons CAs

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14267]
## Description
Added with https://github.com/brave/muon/pull/550 (not included in a release yet)

Needed so that we can migrate some of our sites off Let's Encrypt (so that renewal can be easily automated)

**Comment by jumde** [comment]
## Test Plan:

- Verify `sync.brave.com` and `sync-staging.brave.com` are using Amazon CA certs
- Verify if the sync feature works.

**Comment by bsclifton** [comment]
After this is verified and is pushed out, we can consider updating `sync.brave.com` to use an Amazon issued cert

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/muon/commit/9987d581780671c6a90c28600c71d62d0a662f24

**Comment by bsclifton** [comment]
Hang tight on testing steps; will need to coordinate this

**Comment by bsclifton** [comment]
Ready to be re-tested again 😄

**Comment by bsclifton** [comment]
Verified on macOS x64:
(from source)
Brave: 0.22.807 
rev: 2d4f6e87780d9365fbb66eacf494a83f67174fe2 
Muon: 7.0.4 
libchromiumcontent: 67.0.3396.71
![screen shot 2018-06-06 at 2 03 16 pm](https://user-images.githubusercontent.com/4733304/41065221-c85bc5b2-6992-11e8-9a08-7fd681269489.png)
