### ISSUE TITLE
Feature Request: Add the option to show the bookmark bar only in the new tab page and when user clicks on the address bar

### ISSUE THREAD

**Issue by sakibarifin** [brave/browser-laptop#14268]
### Description

The Brave bookmark bar, when enabled, takes away a lot of space from the browsing screen. But disabling it makes it hard to access. So, it would be great if Brave offered the option to show the bookmark bar only when the user is in the new tab page. It would even better if this feature also showed the bookmarks when the user clicks on the address bar but hide it when the user is browsing the page.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/show-bookmarks-toolbar-only-on-new-tab/26692

@sakibarifin Alternatively, you can use shortcut `Ctrl+Shift+B` to hide/unhide bookmark bar. This shortcut just be added to latest release 0.23.19.

**Comment by rebron** [comment]
Moving over to https://github.com/brave/browser-laptop/issues/14268
