### ISSUE TITLE
Delete wallet button color is not similar with other button colors on 'Advanced Settings for Brave payments' dialog

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14275]
### Description
Delete wallet button color is not similar with other button colors on 'Advanced Settings for Brave payments' dialog

### Steps to Reproduce
1. Launch brave 
2. Enable payments
3. Click on Advanced settings for brave payments

**Actual result:**
Delete wallet button color is not similar with other button colors on 'Advanced Settings for Brave payments' dialog
![delete wallet button color issue](https://user-images.githubusercontent.com/38657976/40723165-d9d89d30-643b-11e8-8d73-81d877259387.PNG)

**Expected result:**
Button color should be unique throughout the application.

**Reproduces how often:**
100%

### Brave Version
0.22.723
**about:brave info:**
Brave | 0.22.723
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya delete button has it's own color (red), to simulate dangerous action, so that we should be carful when clicking on it.

cc @bradleyrichter

**Comment by GeetaSarvadnya** [comment]
As per the above comments and clarification. I am going to close the issue.
