### ISSUE TITLE
Browser unstable/crashes after closing payments tab

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14280]
### Steps to Reproduce
1. Run clean profile with LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging
2. Open about:preferences#payments
3. Enable payments and wait for wallet creation
4. Go to payments Advanced Settings and click Delete Wallet(do not close the modal)
5. Close the payments tab

**Actual result:**
Crash/Freeze. 
Sometimes becomes unstable: new tab with + will open Untitled tab instead of new tab
Cannot open about pages(about:brave, about:preferences) in the Untitled tab.
![unstable_payments](https://user-images.githubusercontent.com/34715963/40739520-bfc3c28e-6446-11e8-9859-1cd5a6de936d.gif)

**Expected result:**
No crashes.

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.723 
V8: 6.6.346.32 
rev: edb3e880ba039aa41b3e032cbcf8a679ebd0ea08 
Muon: 6.0.12 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

Also reproduced on Ubuntu 17.10. v0.22.723 

**Reproducible on current live release:**
Yes. Reproduced in v0.22.721 Windows 7 x64 with Reset sync dialog

cc @kjozwiak @NejcZdovc @bsclifton @srirambv @LaurenWags @GeetaSarvadnya

**Comment by kjozwiak** [comment]
I managed to reproduce the above issue with the `Untitled` tabs on `macOS 10.13.4` using the the STR that @btlechowski added above. However, I couldn't get the browser to freeze/crash though.

However, once you go through the STR, brave will stop opening `about:newtabs` correctly. This doesn't affect Session/PB tabs.

**Comment by NejcZdovc** [comment]
This will happen every time that you have confirmation box open, not limited to delete wallet. Same thing happens with reset sync confirmation (base on @srirambv test)

**Comment by kjozwiak** [comment]
@btlechowski reproduced the issue using `0.22.721` which is the currently released version. As @NejcZdovc  mentioned above, this happens with any confirmation dialog. Seems like this has been around for sometime hence being moved into the backlog.
