### ISSUE TITLE
http link gets added as https in ledger table

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14283]
### Description
http link gets added as https in ledger table

### Steps to Reproduce
  1. Clean install 0.22.723
  2. Visit a http site (for exp: http://espn.com/)
  3. Stay on the page for min 8sec to meet min time criteria
  4. Open payments, ensure site is listed in ledger table
  5. Close tab from step 3
  6. Click on ESPN link from ledger table, opens https://espn.com/ which fails to load and only works on http

**Actual result:**
![https-http](https://user-images.githubusercontent.com/17010094/40746907-abb29ea4-6429-11e8-8945-96424c844bfb.gif)

**Expected result:**
Should not make http links as https

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.723
-- | --
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
Yes

**Comment by btlechowski** [comment]
Reproduced on Ubuntu 17.10 v 0.22.723

**Comment by bsclifton** [comment]
I don't think this was included in a build (yet)

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64 with
* 0.22.807    2d4f6e8
* muon 7.0.4
* libchromiumcontent 67.0.3396.71
