### ISSUE TITLE
Update TOR_VERSION to 0.3.3.6 for linux and darwin

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#14285]
Windows expert bundle for tor hasn't been released yet. So the version stays the same. (0.3.2.10)

**Comment by diracdeltas** [comment]
fixed by #14290

**Comment by kjozwiak** [comment]
@jumde I've added a quick test plan in the original comment, mind quickly double checking? Is this sufficient enough to call this verified? I've also marked this as `OS/macOS`  & `OS/unix-like/linux` as per the title. Please correct the labels of that's incorrect.

Will https://github.com/brave/browser-laptop/issues/14449 also apply to macOS & Linux?

**Comment by kjozwiak** [comment]
Verified with `macOS 10.13.4 x64` using the following build:

* `0.23.11` 6565c0689f8bfbd6f4d03e2e8c68c9381da157f6 
* muon: `7.1.0 `
* libchromiumcontent: `67.0.3396.87`

**Comment by kjozwiak** [comment]
Marking this as `QA/no-qa-needed` as we're now using `Tor 0.3.3.7 (git-035a35178c92da94)` on macOS & Linux.
