### ISSUE TITLE
Show less hides publishers with higher % instead of the low % publisher

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14287]
### Description
Show less hides publishers with higher % instead of the low % publisher

### Steps to Reproduce
  1. Enable payments and visit sites to add to ledger table
  2. Have enough show that `Show Less` button is shown
  3. Click on `Show Less` button, publisher with high % is hidden

**Actual result:**
![ledger table](https://user-images.githubusercontent.com/17010094/40750894-f879a928-6436-11e8-91d0-2b6b240ce278.gif)

**Expected result:**
Should hide the lower % publishers showing pubs making upto 90%

**Reproduces how often:**
Easy

### Brave Version

**about:brave info:**

Brave | 0.22.723
-- | --
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
Could be

### Additional Information
Reproduced on macOS by @LaurenWags

**Comment by GeetaSarvadnya** [comment]
Verified with Windows 10 x64 using
* 0.22.727 2c94bba
* muon 6.0.12
* libchromiumcontent 66.0.3359.170

**Comment by GeetaSarvadnya** [comment]
Verified the issue on 727 latest build. seems issue is not fixed.
![14287](https://user-images.githubusercontent.com/38657976/40914852-76b90c8c-6817-11e8-9813-e1c68d5de642.gif)

**Comment by GeetaSarvadnya** [comment]
As discussed with @NejcZdovc, Click on Show less will display Ledger sites based on % associated with sites. Above issue is fixed and working fine.

Verified with Windows 10 x64 using
* 0.22.727 2c94bba
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
