### ISSUE TITLE
Tab jumps position after opening

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14281]
### Description
Opening links inside a tab causes the new tab to open as the last index... but then quickly jumps back to the index it should have opened as

### Steps to Reproduce
  1. Open 3 new tabs and visit a site (ex: brave.com, github.com, twitter.com)
  2. Switch to the first tab
  3. Middle click (or right click context menu, open in new tab) a link to open in a new tab

**Actual result:**
Tab is put at the end of the tabs... but then it quickly jumps position to the index AFTER the tab that opened it.  In the above example, it opens as tab 4 ("Untitled") but then moves into position as tab 2 as soon as page is loaded ("Brave Software")

![tab-jumps-position](https://user-images.githubusercontent.com/4733304/40739185-560fe896-63fa-11e8-8cab-a543cd769d1f.gif)

**Expected result:**
Tab should open as tab 2 and stay in that position

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**
Yes

### Additional Information

cc: @petemill, @bridiver

**Comment by bsclifton** [comment]
Important to note: issue is present in 0.22.721 (so it's not because of Chromium 67). I wanted to put into this milestone for triage

@petemill can you help me look into this?

**Comment by NejcZdovc** [comment]
+1 from me

**Comment by petemill** [comment]
I believe muon is creating the Tab with index at -1 and then providing the actual index in a later event. We interpret '-1' as 'end of the tab strip'. We're hiding the tabs until we receive the `tab-inserted-at` tab strip event so it should have an index at that point and not flash, so I'll look in to why it's jumping around for this STR.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.724 1f07e93
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
