### ISSUE TITLE
YouTube and Twitch channel display in contribution statement 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14284]
### Description
If you have a contribution statement with YouTube and/or Twitch channels on it, and then clear your ledger table (via the 'Brave Payments attention data' toggle), your contribution statement no longer nicely displays your YT/Twitch channels on the contribution statement.

### Steps to Reproduce

  1. Launch Brave via CLI with clean profile and `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true`
  2. Enable Payments
  3. Visit some sites - a mix of YouTube videos, Twitch channels, and regular sites
  4. Add funds to the wallet.
  5. Close Brave.
  6. Update reconcile stamp to a date in the past.
  7. Launch Brave via CLI with `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true`
  8. Wait until contribution is made. Review contribution statement and ensure YT and Twitch channels display nicely (readable format).
  9. Go to Prefs > Security > Clear Browsing Data Now. Toggle 'Brave Payments attention data' on. Select the Clear button.
  10. Brave ledger table is cleared.
  11. View the same contribution statement again.

**Actual result:**
YT and Twitch channel display on contribution statement is changed:
![screen shot 2018-05-30 at 3 41 35 pm](https://user-images.githubusercontent.com/28145373/40747708-21d3a95a-642c-11e8-8771-b52d927fc922.png)

**Expected result:**
YT and Twitch channel display on contribution statement as it did prior to clearing the ledger table:
![screen shot 2018-05-30 at 3 41 08 pm](https://user-images.githubusercontent.com/28145373/40747757-40e879ba-642c-11e8-80a4-a4287f6098c4.png)

**Reproduces how often:**
easily

### Brave Version
Brave: 0.22.723 
V8: 6.6.346.32 
rev: edb3e880ba039aa41b3e032cbcf8a679ebd0ea08 
Muon: 6.0.12 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**
no, the 'Brave Payments attention data' toggle is being introduced with 0.22.x release 5

**Comment by NejcZdovc** [comment]
This problem is reproduced on current version as well.

1) do a contribution
2) delete one publisher from the table that is also in the contribution table
3) name is lost

**Comment by NejcZdovc** [comment]
Solution for this one would be to put this names into transaction object, which can be a little bit tricky

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.724 1f07e93
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
* Verified after clearing pubs list via  clear browsing history, opening payment history listed channel names correctly
