### ISSUE TITLE
Payments Table Cropped

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#14299]
### Description

Payments table on `about:preferences#payments` cropped and make some options not visible. Tested it on `id`, `my`, and `en` language.

### Steps to Reproduce

  1. Change the browser language to `id (Indonesian)` or else
  2. Enable Payments and visit some sites so it added to Payments table
  3. See the table. Some option is missing

**Actual result:**
id
![payments-id](https://user-images.githubusercontent.com/25360853/40805666-3799b0b8-6549-11e8-8f37-530a279f76ba.png)

my
![payments-my](https://user-images.githubusercontent.com/25360853/40805685-3e3c81d4-6549-11e8-856e-695b68852fa8.png)

also happen on `en` language whit pinned site
![payments-en](https://user-images.githubusercontent.com/25360853/40748711-86db3e9e-648b-11e8-9a97-8ed5bd71437f.gif)

**Expected result:**
The table should show properly

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**

Yes

**Comment by eljuno** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8qbeox/payments_bar_to_small_to_pin_anything/

**Comment by eljuno** [comment]
Unable to reproduce for `id` with latest version, 0.23.19

![payments](https://user-images.githubusercontent.com/25360853/42113973-818c1fd2-7c17-11e8-8cf4-c4a8618c80ef.png)

**Comment by bsclifton** [comment]
@eljuno is this still an issue?

**Comment by eljuno** [comment]
Nope. It's show properly now. We can close this issue. 🙂
