### ISSUE TITLE
reconcile uses user-added BAT instead of UGP BAT

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14297]
### Description
Contributions are using user-added BAT instead of UGP BAT when there is enough UGP BAT to be used.

### Steps to Reproduce

  1. Launch Brave from CLI using `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true` and enable Payments.
  2. Add some sites to ledger.
  3. Add 10 BAT to staging wallet.
  4. Accept UGP grant. You should now have 20 BAT total in your wallet.
  5. Verify monthly budget is 10BAT.
  6. Close Brave.
  7. Update reconcile stamp.
  8. Launch Brave from CLI using `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true LEDGER_NO_FUZZING=true LEDGER_NO_DELAY=true`
  9. Wait for a contribution to occur.

**Actual result:**
Contribution occurs. BAT used for contribution was user added:
![screen shot 2018-05-31 at 10 44 42 am](https://user-images.githubusercontent.com/28145373/40792831-dfbc6082-64c8-11e8-905c-60d5e81568f4.png)

**Expected result:**
BAT used for contribution should have been the UGP BAT.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.22.723

**Reproducible on current live release:**
unknown

### Additional Information
Reproduced on Win by @GeetaSarvadnya 

cc @evq

**Comment by LaurenWags** [comment]
Closing per discussion with @evq  - should be resolved on staging.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.724 1f07e93
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
