### ISSUE TITLE
Loading chrome extensions documentation is out of date

### ISSUE THREAD

**Issue by kirkins** [brave/browser-laptop#14305]
I'm trying to install a chrome extension on brave, found the following documentation

https://brave.com/loading-chrome-extensions-in-brave/

It references a file which no longer seems to exist `app/extensions/extensions.js`.

Reference is in the "Register and Load the Extension" section.

**Comment by bsclifton** [comment]
@kirkins if you're running from source, that file should be at `app/extensions.js` 😄 Hope this helps

**Comment by kirkins** [comment]
@bsclifton oops I misread the location.

I found the file and made the change but the tabby cat extension doesn't show.

![screenshot from 2018-06-01 13-04-15](https://user-images.githubusercontent.com/9503662/40853604-b31feec0-659c-11e8-8fb5-6ea03db684c2.png)

It does say that it didn't show before but PR #6581 fixed that. Can confirm the folder `app/extensions/mefhakmgclhhfbdadeojlkbllmecialg` exists.

> Disclaimer: At the time of this writing the extensions page may not display anything at all. Brave currently expects extension manifests to include an array of permissions. Tabby Cat does not contain a permissions array. This causes an error when we attempt to call the Array.prototype.join method. Pull Request #6581 will resolve this when merged. A temporary work-around is to add permissions: [] to the manifest.

**Comment by bsclifton** [comment]
@kirkins sounds like you're comfortable building from source 😄 I have a patch which you can try:
https://github.com/bsclifton/browser-laptop/commit/4079b887bcf7a01c1b53417e7c8659e0bbc22c21

Basically, you can:
1. Checkout master
2. Add my remote or just put the raw patch contents into a file
3. Cherry pick / apply patch
4. Follow instructions in the patch commit message
  - use npm to globally install `ced` (chrome extension downloader)
  - download all the extensions you want (using the extension ID) to `app/extensions/`
  - enable experimental mode
  - enjoy 😄 👍

**Comment by kirkins** [comment]
@bsclifton thanks for the patch.

1. Applied patch from master, then `npm install`
2. installed tabbycat
3. `npm run start`


Get back this:
````
> brave@0.24.0 start /home/philip/tmp/browser-laptop
> node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

ATTENTION: default value of option force_s3tc_enable overridden by environment.
[13698:13878:0601/143608.141151:ERROR:connection.cc(1888)] Web sqlite error 1, errno 0: no such table: keywords, sql: SELECT id, date_created, last_modified, last_visited FROM keywords
[13698:13878:0601/143608.142667:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 1
[13698:13698:0601/143608.152492:ERROR:brave_browser_context.cc(113)] Error initializing web data service 
[13698:13698:0601/143608.152534:ERROR:brave_browser_context.cc(113)] Error initializing web data service 
[13698:13698:0601/143608.152551:ERROR:brave_browser_context.cc(113)] Error initializing web data service 
Crash reporting enabled

(brave:13698): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
````

Application window is just a white screen.

**Comment by kirkins** [comment]
I think I normally get the `web data service` error. The `IBUS-WARNING` is a new one.

**Comment by bsclifton** [comment]
@kirkins do you have the watcher started? ex: in one console, run `npm run watch`... then run the `npm run start` above
