### ISSUE TITLE
cannot copy url from address bar

### ISSUE THREAD

**Issue by macexpertsusa** [brave/browser-laptop#14301]
you cannot copy url's from the address bar to paste elsewhere
you can highlight and copy but it doesn't go to the clipboard 
highlight and drag does work however

**Comment by kjozwiak** [comment]
@macexpertsusa sounds like issue https://github.com/brave/browser-laptop/issues/14197. I'm going to close this off and mark it as a duplicate. Please re-open if you disagree and think it's a different issue.

Thanks for filing the issue though!
