### ISSUE TITLE
Select all allows to drag all elements on the captcha overlay

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14306]
### Description
Select all allows to drag all elements on the captcha overlay

### Steps to Reproduce
Scenario 1:
  1. Enable payments and click on claim token to bring the overlay
  2. Drag on arrow and select (Doesn't highlight but selects)
  3. Drag and drop BAT logo, arrow is dragged as well 
  4. Dropping the BAT logo on target still allows you to claim token

Scenario 2:
  1. Enable payments and click on claim token to bring the overlay
  2. Press Ctrl+A to select all HTML text 
  3. Drag and drop entire page HTML is shown in drag area 

**Actual result:**
Allows all elements to drag and drop

**Expected result:**
Should only allow the BAT icon to be dnd on target

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.725
-- | --
V8 | 6.6.346.32
rev | e6dd17f
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
NA
### Additional Information
#14274

**Comment by bsclifton** [comment]
I don't think we'll be able to address this with our current Muon based product. Let's consider re-opening once Brave Rewards (and UGP grants) are enabled in [brave-core](https://github.com/brave/brave-browser) 😄
