### ISSUE TITLE
monthly budget amounts changed

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14300]
### Description
Monthly budget amounts have been updated but UGP grant is still 10 BAT. 

### Steps to Reproduce

  1.  Launch Brave from CLI with `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true`
  2. Enable Payments.
  3. Accept UGP.

**Actual result:**
Monthly Budget is 20 BAT, UGP is 10 BAT. 10 BAT is not an option in the monthly budget.
![screen shot 2018-05-31 at 5 47 51 pm](https://user-images.githubusercontent.com/28145373/40810474-e1cbb12e-64fb-11e8-9926-78b122300ae9.png)

**Expected result:**
Should be able to test just redeeming a grant without user-added BAT.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave | 0.22.724
V8 | 6.6.346.32
rev | 1f07e93
Muon | 6.0.12
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
n/a

### Additional Information
Reproduced on Win by @srirambv and Linux by @kjozwiak

**Comment by NejcZdovc** [comment]
this is both done on server side

**Comment by LaurenWags** [comment]
Option added to monthly budget for 10 BAT.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.724 1f07e93
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
