### ISSUE TITLE
Payments show mins time not met message even though ledger table contains more than 30mins of usage

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14310]
### Description
Payments show mins time not met message even though table contains more than 30mins of usage

### Steps to Reproduce
  1. Enable payments and set Budget to 100BAT
  2. View a variety of pages(Twitch/YT/Browsing) to add to ledger table
  3. Ensure its more than 30 mins
  4. Change reconcileStamp to older date to trigger payment 
  5. Relaunch browser shows min time not met message even ledger table shows more than 30 mins of usage 

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/40859263-3260eea2-65af-11e8-95e8-d55691c350a2.png)

**Expected result:**
Should not show message if min time criteria is met

**Reproduces how often:**
Unsure. @davidtemkin had seen this on his profile as well. 

### Brave Version

**about:brave info:**

Brave | 0.22.725
-- | --
V8 | 6.6.346.32
rev | e6dd17f
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
Maybe

### Additional Information
cc: @jasonrsadler @ryanml @NejcZdovc

**Comment by NejcZdovc** [comment]
Some publishers could be older then 30 days and this are excluded from this 30min monthly browsing time. Problem is that we don't update table to reflect that. So you could be seeing ledger table with a lot of publishers that are old

**Comment by GeetaSarvadnya** [comment]
Verified with Windows 10 x64 using

0.22.727 2c94bba
muon 6.0.12
libchromiumcontent 66.0.3359.170
