### ISSUE TITLE
recovery tab for a download will relaunch

### ISSUE THREAD

**Issue by bojake** [brave/browser-laptop#1431]
If you end your brave session after a successful zip file download and then restart you will see the recovery tab for the zip file download reappear and prompt you to download it again.

brave should not preserve download links that are tabbed.

**Comment by bradleyrichter** [comment]
@bbondy We should get this in soon. I just hit cancel 5 times after a restart due to empty tabs respawning downloads.

**Comment by bojake** [comment]
imagine what a malicious script might be able to do with this fun gem.

**Comment by bbondy** [comment]
@bojake If you navigate to a script it'll load the script as text, it is not run.  Also even if it was, which it isn't, if you run a malicious script once or multiple times it's still bad.  Please clarify in more detail what you mean.

**Comment by bojake** [comment]
Imagine if I am able to write to the save file used by Brave to "know" what tabs to reopen. So I just flood that save file with more tabs that download stuff. Effectively I am able to ddos on the brave browser. All I need is local file access.

**Comment by bbondy** [comment]
I don't think I understand the security threat.

**Comment by bbondy** [comment]
This will be fixed here #1219.  Duping to that.
