### ISSUE TITLE
Can't read Google Play Books

### ISSUE THREAD

**Issue by swaroopch** [brave/browser-laptop#14316]
### Description

I cannot read books via https://play.google.com/books/

### Steps to Reproduce
  1. Purchase any book in Google Play store
  2. Try reading it online

**Actual result:**

![screen shot 2018-06-02 at 6 53 03 am](https://user-images.githubusercontent.com/42988/40877205-ad0a860e-6631-11e8-8635-a3836de5039c.png)

**Expected result:**

To be able to read the book.

**Reproduces how often:**

Every time.

### Brave Version

 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**

Yes

**Comment by srirambv** [comment]
Try allowing all Cookies on the page. That should fix the issue

**Comment by swaroopch** [comment]
That fixed it. Thanks!
