### ISSUE TITLE
Brave shows empty window with newest nvidia drivers

### ISSUE THREAD

**Issue by jytou** [brave/browser-laptop#14321]
### Description
Ubuntu 16.04, installed nvidia newest drivers. Brave was working fine before.

```
$ brave
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Crash reporting enabled
ATTENTION: default value of option force_s3tc_enable overridden by environment.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[8527:8527:0604/025808.727222:ERROR:gl_context_glx.cc(227)] Couldn't make context current with X drawable.
[8527:8527:0604/025808.727266:ERROR:gpu_info_collector.cc(63)] gl::GLContext::MakeCurrent() failed
```
And from there, brave's window is simply invisible. Brave is running, but shows nothing. So far Brave is the only application that has a problem, everything else works well.

### Steps to Reproduce
Although I can't be 100% sure that this will happen on other computers, just install the newest nvidia drivers and see how it goes.

### Brave Version
v0.22.721dev installed with snap. Same thing goes with an older version from the default Ubuntu packages.

**Comment by jytou** [comment]
Note that I have just built it from source and it runs. Wild guess: some packaged node modules that has some incompatibilities with the newest nvidia drivers?

**Comment by bsclifton** [comment]
Closing as I believe a workaround is documented at https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003
