### ISSUE TITLE
brave fails to start on macOS

### ISSUE THREAD

**Issue by samuel1** [brave/browser-laptop#14322]
Previously Brave worked fine, but now bounces once when clicked and does not open. This problem remains after reboot

I enabled coredumps, but it does not give one

system.log gives: com.apple.xpc.launchd[1]: Host-level exception raised: pid = 496, thread = 0x78527, exception type = 0xd, codes = { 0 }, states = { 0 }

Version: 0.22.721

Deleting brave, and copying that same version out of a .dmg gets it working again

So I was unable to get to the about box of the version that didn't work, but maybe it is the same as the newly copied version.....

Newly copied version:
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.3.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by LaurenWags** [comment]
unsure if this is the same as https://github.com/brave/browser-laptop/issues/14202 ? note, 14202 issue is currently slated for the next version.

cc @bsclifton

**Comment by samuel1** [comment]
I've not seen their issue, so I can't comment deeply.  Though they said "Brave is unresponsive/beachballs" and "hangs/beachballs"

The issue here was not beachballs or hanging, but a single bounce (in the macOS dock), then a silent exit, with no indication to the user that it had failed to load

Note: I'd run Brave for many months without ever experiencing this 'silent failure'

**Comment by bsclifton** [comment]
@samuel1 do you have Brave Payments enabled?

**Comment by kjozwiak** [comment]
@samuel1 any updates on this? Did the `0.22.727` release fix your issue?

**Comment by samuel1** [comment]
Sorry, I am away from my computer til Saturday

A reinstall of Brave to the same version seemed to fix the issue

-- I think payments were enabled, but I can't double check that until
Saturday



On Jun 7, 2018 11:42, "Kamil Jozwiak" <notifications@github.com> wrote:

@samuel1 <https://github.com/samuel1> any updates on this? Did the 0.22.727
release fix your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brave/browser-laptop/issues/14322#issuecomment-395283023>,
or mute the thread

**Comment by NejcZdovc** [comment]
closing as it's working now. Thx for checking it out @samuel1
