### ISSUE TITLE
Slack does not work after the last brave update (osx)

### ISSUE THREAD

**Issue by MoMannn** [brave/browser-laptop#14339]
### Description
After the last update slack stopped working. Well to be more precise you can open slack and the conversation loads for the first chat you are in but if you move to another is does not work.

### Steps to Reproduce
Just try using slack.. 

### Brave Version

**about:brave info:**
 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**
yes

### Additional Information
From what I can see the browser is telling slack that there is no internet connection:
<img width="787" alt="screen shot 2018-06-06 at 10 06 13" src="https://user-images.githubusercontent.com/8865298/41025090-51535960-6971-11e8-9731-3b8ab1ec3fdb.png">

**Comment by kjozwiak** [comment]
@MoMannn can you reproduce this 100% of the time? I tried reproducing it on my `macOS 10.13.4` using `0.22.727` 2c94bba without any luck. I logged into our Slack channel using the above build and managed to move around a few different channels which all loaded without any problems.

Is there any specific STR? I also tried a few things like:

* enabling site isolation (still worked on my end)
* enabling block all fingerprinting via the brave shield (still worked on my end)
* block scripts via the brave shield (breaks as expected)
* block all cookies via the brave shield (breaks as expected)

**Comment by MoMannn** [comment]
@kjozwiak I tried replicating it today but I had no luck either. Now I'm not sure if the problem was with brave of with slack. It stopped working right after the update but now after I restarted it it works fine. 
So it is either a one time thing right after the update or it was a problem on the slack side with very coincidental timing with me doing the update.

**Comment by bsclifton** [comment]
Thanks for the quick update, @MoMannn! I'm going to close this issue, but please reopen it (including more details) if you experience it again. Thanks for taking the time to report this 😄
