### ISSUE TITLE
terminal spammed with [warn] kevent: Invalid argument

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14332]
### Description
Terminal is being spammed with `[warn] kevent: Invalid argument`.

### Steps to Reproduce

  1. Launch Brave from CLI. 
  2. Navigate to news.google.com
  3. Click on a few articles, they’re opened in new tabs as expected. 
  4. Close the article tabs, no terminal spam.
  5. Navigate to brianbondy.com
  6. Click on the twitter icon
  7. Twitter is opened in a new tab.
  8. Close twitter tab.

**Actual result:**
Terminal is spammed with `[warn] kevent: Invalid argument`

![kevent-terminal](https://user-images.githubusercontent.com/28145373/40942159-40b3f06c-681b-11e8-9917-9ca06931a2c7.gif)

**Expected result:**
No terminal spam.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.22.806
V8 | 6.7.288.42
rev | 0d30970
Muon | 7.0.3
OS Release | 16.7.0
Update Channel | Beta
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.62

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @kjozwiak on macOS
@srirambv was unable to reproduce on Win

If you attempt the STR with a large profile (4 windows, ~150 tabs per window) your CPU usage skyrockets.

**Comment by kjozwiak** [comment]
Going through @LaurenWags STR, my `iTerm` started using about `330%` of CPU causing the fans to start working double time.

<img width="617" alt="screen shot 2018-06-04 at 5 10 07 pm" src="https://user-images.githubusercontent.com/2602313/40944813-2ce53c18-6824-11e8-817f-faf219a2463f.png">

When I closed Brave and the `[warn] kevent: Invalid argument` stopped spamming `iTerm`, it dropped back down to about `3%` of CPU usage.

**Comment by srirambv** [comment]
Can't reproduce issue on Windows on a clean profile as well as on a huge profile.

**Comment by bridiver** [comment]
has this been verified as a new issue with C67?

**Comment by bridiver** [comment]
also can this be reproduced with muon 7.0.2?

**Comment by bridiver** [comment]
@kjozwiak do you see high cpu usage when launched normally?

**Comment by kjozwiak** [comment]
> has this been verified as a new issue with C67?

Couldn't reproduce the issue with `0.22.727` 2c94bbad00d70b87328f04574725979960e18f9f  after several attempts. It looks like the issue started occurring on `0.22.805`:

* `0.22.806` 0d309702587dfc3d03ace5d644b48eedd031ff5b (muon: 7.0.3 & CR: 67.0.3396.62) - Reproduced
* `0.22.805` aec6f4084fd707c3ffe41ecf5eb50151a264680b (muon: 7.0.2 & CR: 67.0.3396.62) - Reproduced
*  `0.22.804` 173a35f1ffe352a6f87c66e6c51d9d3778577019 (muon: 7.0.1 & CR: 67.0.3396.48) - Couldn't reproduce

> also can this be reproduced with muon 7.0.2?

Yup, reproduced with `0.22.805` aec6f4084fd707c3ffe41ecf5eb50151a264680b (muon: `7.0.2` & CR: `67.0.3396.62`) as mentioned in the above results.

> do you see high cpu usage when launched normally?

Yup, but it's not as drastic as the increase I noticed with `iTerm`. Once you reproduce the issue, one of the `Brave-Beta Helper` increases to about `100%` CPU. When I reproduced the issue on two different windows, I had two `Brave-Beta Helper` running at `100%` CPU which caused the PC fans to start working double time. Example:

![cpuissue](https://user-images.githubusercontent.com/2602313/40949107-66ddd04a-683a-11e8-8eea-8b9298773a71.gif)

**Comment by bridiver** [comment]
this is an upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=848210
bumping to `67.0.3396.71` to get the fix

**Comment by bridiver** [comment]
https://github.com/brave/browser-laptop-bootstrap/commit/405fb3daa9b25527ca6db6ec507d4422a70e5266

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.807 2d4f6e8
* Muon 7.0.4
* libchromiumcontent 67.0.3396.71
