### ISSUE TITLE
Brave process consumes 100% CPU

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-laptop#1433]
- open a zendesk website;
- log in to it;
- leave it till session expired(~10minutes);
- quit Brave from Brave menu;
- launch Brave.

Related: #861

**Comment by bbondy** [comment]
the 100% cpu only happens on session restore?

**Comment by SergeyZhukovsky** [comment]
Yes and the page with zendesk on restore is blank.

**Comment by kika** [comment]
Latest Brave on OS X, page http://www.fontanka.ru/2016/06/06/151/
Left for a few hours open (this one was the only page open in Brave) - -90-95% CPU and 1.2 - 2.0GB memory (few restarts different numbers).
