### ISSUE TITLE
unresponsive page 

### ISSUE THREAD

**Issue by modusops** [brave/browser-laptop#14338]
### Description

Tried loading this page on Brave, it loads, but frozen when I try to interact with it. Page works fine w/ Chrome. 

### Steps to Reproduce

http://www.town29oakland.com/town-29-oakland-ca/check-availability

  1. Load this page
  2. Load same page in Chrome
  3. Find error in console

**Actual result:**

![screen shot 2018-06-05 at 10 36 34 pm](https://user-images.githubusercontent.com/7923023/41018952-644e6ede-6911-11e8-8d17-b114a5ff3eb6.jpg)

**Expected result:**
Page loads

**Reproduces how often:**
100%

### Brave Version

0.22.727

**about:brave info:**
 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@modusops I get the error in both Chrome and Brave- the page responds the same way. Are you still having a problem with this?
