### ISSUE TITLE
renaming "Delete wallet" to something more intuitive like "Reset wallet"

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14335]
### Description

Catherine pointed out that the current `Delete wallet` could confuse some users into thinking that they're removing the entire wallet rather than just clearing it and starting from a fresh state. Catherine recommended using something more intuitive like `Reset wallet`.

### Steps to Reproduce

  1. launch `0.22.727` 2c94bbad00d70b87328f04574725979960e18f9f
  2. enable Payments via `about:preferences#payments`
  3. once enabled, click on the `Advanced Settings` icon

You'll notice the `Delete wallet` button.

**Actual result:**

<img width="706" alt="screen shot 2018-06-04 at 6 50 20 pm" src="https://user-images.githubusercontent.com/2602313/40945732-2878bfac-6828-11e8-9e47-7a65b6c0a91c.png">

**Expected result:**

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Reproducible on current live release:**

Yes, currently reproducible with `0.22.727` which is the latest released version.

### Additional Information

CCing @bradleyrichter for UI considerations.

**Comment by alexwykoff** [comment]
Won't fix in muon Brave
