### ISSUE TITLE
Images fail to display on warframe.wikia.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14347]
### Description
When ad-blocking is enabled, images are not shown on http://warframe.wikia.com/wiki/Corrupted.

**Reproduces how often:**
Always

**about:brave info:**
``` 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Reproducible on current live release:**
Yes

### Additional Information
The images are shown when scripting is disabled due to `<noscript>` tags.

**Comment by bsclifton** [comment]
Verified fixed with `brave-core`
