### ISSUE TITLE
Mojave: Checkboxes are invisible

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#14348]
1. Open https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

Expected: you should be able to see a checkbox in the demo area. This problem affects all checkboxes and not just this page.

Actual: there are no checkboxes anywhere to be seen.

Brave: 0.22.727

Environment: macOS 10.14 Mojave beta (18A293u)

**Comment by bsclifton** [comment]
@da2x how does this look in Chrome / Chromium?

**Comment by da2x** [comment]
Checkboxes are invisible in both Chrome and Vivaldi.

**Comment by Liunkae** [comment]
Possibly also affects other input elements: https://bugs.chromium.org/p/chromium/issues/detail?id=850021

**Comment by nuirattapon** [comment]
Same issue at 100% view in Chrome, try zoom in or out to get around for now.

**Comment by hansemannn** [comment]
I have made a tiny [Chrome extension](https://chrome.google.com/webstore/detail/mojave-checkbox-fix/ihlgehdlkphgngjfagonbeoepadbdaae) that workarounds this issue. It's [open source](https://github.com/hansemannn/chrome-mojave-checkbox-extension), so no bad intentions here.

**Comment by perfectusr** [comment]
Thank you @hansemannn!!!

**Comment by kshitijarade** [comment]
@hansemannn Thank you buddy. You are life saviour

**Comment by DutchmanSA** [comment]
@hansemannn Works perfectly!

**Comment by sovon** [comment]
I thought I was going crazy. Thank you @hansemannn 

@nuirattapon Thanks so much for mentioning the zoom percentage.

**Comment by Jbartsch** [comment]
✌️@hansemannn

**Comment by kunalpanchal** [comment]
@hansemannn Thanks Mahn !

**Comment by hongson47** [comment]
@hansemannn you save my life.

**Comment by anh-tuan** [comment]
thank you alot @hansemannn :D

**Comment by bsclifton** [comment]
Closing as `wontfix`; I don't think there's anything we can do directly in our code-base, if Chrome is experiencing it (since we're using Chromium- we could fix and upstream the patch, but that would happen in `brave-core`). This will likely be fixed when Chromium is updated

If folks wanted to try brave-core, you can download this new developer channel build of Brave here:
https://brave.com/download-dev
