### ISSUE TITLE
Brave won't open (Windows 10)

### ISSUE THREAD

**Issue by realuser** [brave/browser-laptop#14344]
### Description
I opened brave today and got a notification bar at the top to claim free tokens.  I click on claim tokens and was taken to the payments page.  On the payments page I clicked the claim tokens button and was given the message:

> "Uh oh. The Brave Payments server is not responding. Please try again later to claim your token grant.
> Note: This error could also be caused by a network connection problem."
> 

I tried clicking a few times and received the same message each time.  I decided to close Brave and re-open.  After closing brave I clicked on the icon to open it.  However nothing happened.  I get the hour glass mouse cursor for a second and then nothing.  After trying this a few times I reboot my computer.  Again trying to open brave by clicking on the application icon does nothing.  I go to C:\Users\myusername\AppData\Local\Brave and try to run Brave.eve from the command line and nothing happens.

The Brave.exe shows that it was modified today.

Brave Version 0.22.727

Microsoft Windows [Version 10.0.16299.461]

**Comment by realuser** [comment]
I noticed that inside `C:\Users\myusername\AppData\Local\Brave`
there are folders:
`app-0.22.721`
`app-0.22.727`

And inside each of these is a Brave.exe
Attempting to click on 
`C:\Users\myusername\AppData\Local\Brave\app-0.22.727\Brave.exe` gives same behavior
Inside the folder there is a debug.log file with the following error repeated several times:
`[0606/<somenumbers>:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.`

Attempting to click on 
`C:\Users\myusername\AppData\Local\Brave\app-0.22.721\Brave.exe` Brave actually opens

**Comment by bsclifton** [comment]
@realuser can you try uninstalling/reinstalling? I'm curious if something about the installation was corrupted. Uninstalling or installing on top of your existing files is safe- you won't lose your profile directory.  Let us know if this solves the issue

**Comment by realuser** [comment]
I uninstalled and reinstalled and that seems to have resolved the issue.  Also I was able to claim the free tokens thank you
