### ISSUE TITLE
Ledger bug: Host 1.1.1.1 recorded as 1.1

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#14345]
Brave version 0.22.727.

1. Visit https://1.1.1.1/ for 8+ seconds
2. Open about:preferences#payments

Expected: an entry for `1.1.1.1`.

Actual: an entry for ´1.1´ (expands to ´1.0.0.1`).

**Comment by RyanJarv** [comment]
Just adding some info here. Not sure this is happening but can guess this is due to the behavior of the `inet_aton` syscall, so this will happen in other programs like ping and with other odd formats (see below).

Not sure how windows handles this but at least on darwin/linux there's some info in `man 3 inet`.

```
$ for i in 1.1 0100000001 0x1000001 16777217 00100000001 0xabad1dea01000001; do python3 -c "import socket; print(socket.inet_aton('${i}'))"; done
b'\x01\x00\x00\x01'
b'\x01\x00\x00\x01'
b'\x01\x00\x00\x01'
b'\x01\x00\x00\x01'
b'\x01\x00\x00\x01'
b'\x01\x00\x00\x01'
```

**Comment by RyanJarv** [comment]
Was messing around with this and seems inet_atom accepts various strings seperated some whitespace/control characters as well. Likely not relevant to this but figured it's worth mentioning.

```
$ seq 0x9 0xd  | while read char; do echo -e "\n-------------"; char=$(printf "%%%02x" $char); python3 -c "import socket; addr='1.1${char//%/\\x}example.com'; print(addr, end=': '); print(socket.inet_aton(addr))"; done

-------------
1.1     example.com: b'\x01\x00\x00\x01'

-------------
1.1
example.com: b'\x01\x00\x00\x01'

-------------
1.1
   example.com: b'\x01\x00\x00\x01'

-------------
1.1
   example.com: b'\x01\x00\x00\x01'

-------------
example.com: b'\x01\x00\x00\x01'
```
