### ISSUE TITLE
add tab-preview timer reset when entering and exiting tab bar to remove unwanted previewing

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1434]
User returns to the URL bar constantly. This mouse travel invokes the tab preview timer because the mouse moves over the tabs on the way to the URL bar. Because the tab bar is re-entered before the timer ends, the preview is shown on the way back to the page.

**Comment by diegodoval** [comment]
Increasing the default timer would be a good idea. Mouseover happens frequently regardless of going to the address bar, and it creates a confusing experience as the previews 'flash' in and out very quickly.
