### ISSUE TITLE
YouTube channels not showing verified icon on ledger table

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14351]
### Description
YouTube channels are not showing the verified icon.

Reported via community: https://community.brave.com/t/significant-new-bug-in-payments-ui-since-recent-update-channel-names-verification/23278/2

### Steps to Reproduce

  1. Enable Payments.
  2. Visit a site like DDG (or other verified site) for a bit.
  3. Visit ledger table, DDG is listed and shows verified icon.
  4. Watch a video on a verified YT site. I used videos from: https://www.youtube.com/user/RubinReport/videos
https://www.youtube.com/user/sxephil/videos
https://www.youtube.com/user/BartBaKer/videos
  5. Visit ledger table.

**Actual result:**
YT channels are listed but no verified icons display.
![screen shot 2018-06-07 at 10 33 54 am](https://user-images.githubusercontent.com/28145373/41106866-052ab122-6a3f-11e8-821c-6fa854f30eed.png)

**Expected result:**
YT sites should show as verified.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.727

**Reproducible on current live release:**
Yes

**Comment by NejcZdovc** [comment]
looks like media publishers are not returning verified state

Bart (media publisher): https://ledger.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=youtube%23channel%3ABartBaKer *not working*

Clifton (regular site): https://ledger.mercury.basicattentiontoken.org/v3/publisher/identity?publisher=clifton.io *working*

**Comment by kjozwiak** [comment]
Any news on this? Probably should get this fixed sooner rather than later.

**Comment by evq** [comment]
We are in the process of moving this API to publishers, it is most likely a server side issue in the current implementation in ledger. We will verify that the new implementation works correctly for youtube channels such as the above and push on performing the switchover

**Comment by kjozwiak** [comment]
@evq let me know if you need any help from QA.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.14 f4da855
* Muon 7.1.1
* libchromiumcontent 67.0.3396.87
