### ISSUE TITLE
Brave Stopped playing Facebook videos

### ISSUE THREAD

**Issue by egferro** [brave/browser-laptop#14358]
Brave version 0.22.727
Windows 10
Today brave stopped playing facebook videos. 
When you click play they turn into larger version (almost full screen) but the video never starts.
Please advise
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by eljuno** [comment]
+1s from community https://community.brave.com/t/facebook-video-wont-play-with-the-shields-up-mac-os/23568?u=eljuno

Also +1 from me. cc @bsclifton

**Comment by LaurenWags** [comment]
Reproduces on 0.22.808, adjusting my cookie setting to 'Allow All Cookies' for FB seemed to fix it.

**Comment by eljuno** [comment]
+1s from Reddit https://www.reddit.com/r/brave_browser/comments/8pzoht/videos_not_playing_on_facebook/

**Comment by bsclifton** [comment]
If this requires 3rd party cookies, I'm not sure if we want to fix it. cc: @diracdeltas

**Comment by Jacalz** [comment]
+1 from DM on the community

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/videos-dont-play-on-facebook-with-brave/23788

**Comment by dgurns** [comment]
+1

using Macbook Pro, OS 10.13.3

**Comment by eszpee** [comment]
Same on OS X

**Comment by srirambv** [comment]
Updating workaround label. 3rd party cookies don't fix only shields down allows you to play video. More details on #14448

**Comment by Slava** [comment]
I tested it on Mac and for me switching from "block 3rd party cookies" to "allow all cookies" fixes the problem. Not sure yet what is going on here, for starters the Facebook player makes xhr requests to load pieces of the video and in a normal operation a request looks something like this:

<img width="828" alt="screen shot 2018-06-19 at 3 10 35 pm" src="https://user-images.githubusercontent.com/2608446/41626945-1493e8b6-73d3-11e8-9f45-23469ca9df06.png">

But when the 3rd party cookies are blocked, the response from the server is a 302 redirect which doesn't return anything else

<img width="727" alt="screen shot 2018-06-19 at 3 11 28 pm" src="https://user-images.githubusercontent.com/2608446/41626969-2caf4cec-73d3-11e8-92ed-d3c5b2aca9ea.png">

From where I stand now it is not obvious to me we can do anything besides having a work-around of allowing 3rd-party cookies to play Facebook videos.

**Comment by Slava** [comment]
Seems like a referer problem after all, see https://github.com/brave/browser-laptop/pull/14465

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
