### ISSUE TITLE
Disable  navigator.sendBeacon

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#14354]
Mostly used by trackers to send analytics and web page activities.

**Comment by diracdeltas** [comment]
was done in muon IIRC so if it is a problem, it should be marked as a regression

**Comment by jumde** [comment]
SendBeacon works:
```
>navigator.sendBeacon('https://apple.com', '');
>true
```

a ping is disabled.

**Comment by tomlowenthal** [comment]
Now at brave/brave-browser#573
