### ISSUE TITLE
YouTube only displays mobile site

### ISSUE THREAD

**Issue by heshamsalman** [brave/browser-laptop#14359]
### Description
Upon visiting YouTube, I get the mobile website.

### Steps to Reproduce
  1. Go to youtube.com

**Actual result:**
![screen shot 2018-06-07 at 2 21 49 pm](https://user-images.githubusercontent.com/3388381/41164248-b1ead508-6b08-11e8-8d15-5697b53d8860.png)

**Expected result:**
![screen shot 2018-06-08 at 10 43 30 am](https://user-images.githubusercontent.com/3388381/41164289-cd8cd6f8-6b08-11e8-980e-189c5291e793.png)

**Reproduces how often:**
100%

### Brave Version

0.22.727

**Reproducible on current live release:**
Yes

### Additional Information
I've deleted my caches, browsing history, etc. I've deleted and re-installed the app and still experience the same result.

**Comment by eljuno** [comment]
It looks like your zoom level is ++100%. You can check hamburger menu > Zoom.

**Comment by heshamsalman** [comment]
_l o l_ 

Well. 😂
