### ISSUE TITLE
quarantine cleanup issue

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14353]
### Description
Reported via community: https://community.brave.com/t/brave-on-osx-still-buggy-since-the-last-update/23123/4

### Steps to Reproduce

Unknown exactly - launching 0.22.721 is producing the error in community post for a user.

**Actual result:**
Unable to launch Brave

**Expected result:**
Should be able to launch Brave

**Reproduces how often:**
Easily for user

### Brave Version

**about:brave info:**
0.22.712

**Reproducible on current live release:**
yes

### Additional Information
cc @bsclifton

**Comment by bsclifton** [comment]
@kjozwiak no action needed - this is definitely a weird edge case (I couldn't repro the breaking case). The setup for testing this is not known, but this should be a completely valid work-around
