### ISSUE TITLE
Add too many requests overlay

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14356]
### Description

We would like to show notification to the users who tried captcha too many times.

### Steps to Reproduce

  1. Enable payments
  2. Claim grant
  3. Intentionally miss captcha 30 times 

**Actual result:**

You get general error

**Expected result:**
You should get

![image](https://user-images.githubusercontent.com/9574457/41141669-38036e18-6af3-11e8-9b04-9e3e88d0ccff.png)

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.808 2572bd3
* Muon 7.0.4
* libchromiumcontent 67.0.3396.71
