### ISSUE TITLE
Trying to Follow Instructions of Loading Chrome Extensions

### ISSUE THREAD

**Issue by besteman** [brave/browser-laptop#14360]
Hey! Love your browser! Thank you for all your hardwork on it

### Description
I am trying to follow the instructions here [Loading Chrome Extensions](https://brave.com/loading-chrome-extensions-in-brave/). 

I am up to the step of `npm run watch` and it sits like this:

![alt-text](http://besteman.io/0i0t3n2p0y25/Image%202018-06-08%20at%2011.25.13%20AM.png)

When I run `npm start` this is the log of the error:

[2018-06-08T15_08_09_022Z-debug.log](https://github.com/brave/browser-laptop/files/2084983/2018-06-08T15_08_09_022Z-debug.log)

### Steps to Reproduce

  1. git clone https://github.com/brave/browser-laptop.git  
  2. cd browser-laptop 
  3. npm i
  4. npm run watch
  5. npm start

**Actual result:**

Hangs up on the `npm run watch` and gives error on `npm start`

**Expected result:**

> Within a couple of moments, Brave should appear.

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by besteman** [comment]
@bsclifton 
Yes I am the owner of the files and tried to run with sudo just to confirm

I am running two terminals: one for the watch and the second for the start

**Comment by besteman** [comment]
Also I am getting errors on `npm install`:

[2018-06-08T18_12_08_303Z-debug.log](https://github.com/brave/browser-laptop/files/2085527/2018-06-08T18_12_08_303Z-debug.log)

![alt-text](http://besteman.io/0b263B182E41/Image%202018-06-08%20at%202.17.02%20PM.png)

![alt-text](http://besteman.io/3K2b3n313R1E/Image%202018-06-08%20at%202.17.56%20PM.png)

**Comment by besteman** [comment]
Looks like I solved the problem.
I delete the repo and did another clone but I cloned with ssh and it worked

**Comment by bsclifton** [comment]
@besteman awesome- thanks for the update! 😄 👍
