### ISSUE TITLE
UGP CAPTCHA is not compatible with Windows 10 scaling options (high-res screen support)

### ISSUE THREAD

**Issue by davidtemkin** [brave/browser-laptop#14361]
(Placeholder. Have not reproduced). 

Users report that CAPTCHA does not work correctly with some Windows 10 UI/font scaling options. Apparently when Windows is set up for high-res monitors it does not work because of use of absolute x/y coordinates.

**Comment by kjozwiak** [comment]
I believe a few of us ran into this with VM's but we figured it was a VM specific issue. Example of the issue occurring in the VM:

![captcha](https://user-images.githubusercontent.com/2602313/41169302-91f08bd6-6b16-11e8-9833-086f6df233fd.gif)

Unfortunately I didn't end up reporting this as everyone that I asked said it was working fine on Win so assumed it's probably a VM issue :/

**Comment by jonathansampson** [comment]
Confirming that this is indeed due to scaling. If you reduce device scaling to 100%, it should work.

**Comment by kjozwiak** [comment]
@srirambv @LaurenWags @btlechowski @GeetaSarvadnya Even though this was fixed for the scaling issue on Win, we should double check and make sure it still works as expected on all three platforms, hence adding this issue to all three manual passes.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.810 8f30eeb
* Muon 7.0.6
* libchromiumcontent 67.0.3396.71
* verified steps 3-6 of test plan on macOS
