### ISSUE TITLE
Brave crashes on launch for some users

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14370]
### Description
Some users are still reporting unable to use Brave after updating to 0.22.727:
https://community.brave.com/t/brave-crashes-upon-launching-on-macbook/23505
https://community.brave.com/t/browser-crashes-seconds-after-launch/22438/25
https://community.brave.com/t/brave-does-not-lauch-at-all-windows-10-latest-update/23618/1
https://community.brave.com/t/new-brave-update-v0-22-727-hangs-indefinitely-on-startup-with-or-without-any-tabs-open/23451

Was reported with earlier versions with https://github.com/brave/browser-laptop/issues/14202

### Steps to Reproduce
Unknown - users are reporting they launch and have issues. 

**Actual result:**
Brave crashes/becomes unresponsive after launch.

**Expected result:**
Brave should operate normally.

**Reproduces how often:**
Unknown.

### Brave Version

**about:brave info:**
0.22.727

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Reproduced using a user profile - looking into this now...

**Comment by ryanml** [comment]
Pending: https://github.com/brave-intl/bat-publisher/pull/35

**Comment by kjozwiak** [comment]
@bsclifton can we use the profile you mentioned in https://github.com/brave/browser-laptop/issues/14370#issuecomment-397694162 to verify this on the different platforms? Seems like there's not much QA can do here without a reproducible profile.

**Comment by bsclifton** [comment]
@kjozwiak unfortunately, I no longer have the profile. We can ask the user again, but after finding the root cause and writing the failing unit tests, I deleted all copies of the profile

Since there are unit tests covering this (and because it would need a profile that we don't have), I'll mark this as `no-qa-needed`

**Comment by kjozwiak** [comment]
Awesome, much appreciated @bsclifton 👍
