### ISSUE TITLE
Dinosaur pops up for a brief second when browsing without internet connection

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#14371]
### Description
When trying to browser without internet connection, the error page shows the google chrome dinosaur game for a brief second before it looks normal.

### Steps to Reproduce
  1. Load a site with internet for example [duckduckgo](https://start.duckduckgo.com)
  2. Disconnect internet
  3. Write "test" or anything else in the bar and press enter
  4. Look for the dinosaur 

**Actual result:**

Brave for some reason shows a friendly little dinosaur:
![brave-dinosaur-bug](https://user-images.githubusercontent.com/25466657/41239891-7dda55f2-6d99-11e8-9b4b-7bdca02ca858.gif)

**Expected result:**

Should not show the little dinosaur. 

**Reproduces how often:**
Kind of 50% of the time otherwise it just loads the error page with some strange white rectangles covering the error text. So almost 90% wrong but the dinosaur is just around 50% of the time.

### Brave Version

**about:brave info:**
 
Brave: 0.22.727 
V8: 6.6.346.32 
rev: 2c94bbad00d70b87328f04574725979960e18f9f 
Muon: 6.0.12 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**
Yes

### Additional Information
Might need to use a mac because I have not seen this on Windows.

**Comment by bsclifton** [comment]
Should be fixed with brave-core 😄 👍
