### ISSUE TITLE
Zoom - Change Webpage Sizing

### ISSUE THREAD

**Issue by rocky4-iv** [brave/browser-laptop#1438]
Can't figure out why Brave Browser won't zoom when CTRL & + is pressed on Calculator of Keyboard.

In all other major browsers this function works.

Please correct this.

**Comment by thepup** [comment]
I believe we have this feature working. What OS are you on?

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/browser-laptop/issues/1451

**Comment by rocky4-iv** [comment]
I'll provide more details -- I'm using Brave Browser: Brave: 0.9.1
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 6.0.0-pre
Update channel: dev
*************************
Operating System is Linux Manjaro Cinnamon 2.8.8
Linux Kernel 4.6.0-1
*********************************
Brave >>Page Zoom works if I use CTRL and (+ Function Key)
Brave >>Page Zoom does not work if I use CTRL and (+ Calculator Key)
Using a USB Kensington Keyboard with Integrated Calculator
As I've noted Opera, Vivaldi, Maxthon Broswers -- Zoom function works with integrated Calculator

Thanks
