### ISSUE TITLE
brave crashes after an update when strict site isolation is enabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14380]
### Description

Brave will crash when updating from `0.22.727` -> `0.22.808` while `strict site isolation` is enabled.

### Steps to Reproduce

  1. launch `0.22.727` 2c94bba
  2. enable SSI via `about:preferences#security` and restart brave
  3. close brave relaunch using `BRAVE_ENABLE_PREVIEW_UPDATES=TRUE`
  4. check for updates via `Hamburger Menu` -> `Help` -> `Check for Updates...`
  5. once you've retrieved the update, click on `Update` via the notification

After Brave is relaunched, you'll receive a `Brave quit unexpectedly`

**Actual result:**

![crashssi](https://user-images.githubusercontent.com/2602313/41259308-27c3d83e-6da1-11e8-8b77-6ee045cde85a.gif)

**Expected result:**

Brave shouldn't be crashing after an update when `strict site isolation` is enabled.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.22.808 
V8: 6.7.288.43 
rev: 2572bd3b79216358858cecf63428ef610ca0fc00 
Muon: 7.0.4 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71
```

**Reproducible on current live release:**

Yes, currently updating from `0.22.727` which is the live release to `0.22.808` reproduces the issue. Any users that have SSI enabled in `0.22.727` will run into this issue if we release `0.22.808` with this bug.

**Comment by bsclifton** [comment]
@srirambv has confirmed this doesn't happen on Windows

**Comment by bridiver** [comment]
this crash will happen anytime site isolation is enabled in c67 prior to the fix. An upgrade is not necessary for repro

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.810 8f30eeba0c2d6cccf1920a360b4774f820adbc58
* Muon 7.0.6
* libchromiumcontent 67.0.3396.71
