### ISSUE TITLE
bat-client needs updating to resolve obsolete publisher ruleset fetch errors

### ISSUE THREAD

**Issue by jasonrsadler** [brave/browser-laptop#14396]
### Description
bat-client needs updating to resolve obsolete publisher ruleset fetch errors (previously thought unreachable code). 

Possibly causing errors during contribution/reconcilation

**Comment by ryanml** [comment]
Ref: https://github.com/brave-intl/bat-client/pull/86

**Comment by jasonrsadler** [comment]
Closed in brave-intl/bat-client#86
