### ISSUE TITLE
Chromium 67 rebase for Tor Private Tabs

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#14393]
Just a tracking issue for the rebase. Needed before QA can complete runs.

**Comment by bsclifton** [comment]
- [ ] Merge https://github.com/brave/muon/pull/596 to master
- [ ] Rebase the tor Muon branch against master

**Comment by bsclifton** [comment]
C67 merge to master is complete- rebase in progress now...

**Comment by alexwykoff** [comment]
per @bsclifton  gtg!

**Comment by riastradh-brave** [comment]
https://github.com/brave/muon/commit/587eff17241783e8cfa6d1f3202eeeb21af2a8e5
