### ISSUE TITLE
network throttling can cause brave to hang?

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1439]
Eric Ferraiuolo ‏@ericf  57m57 minutes ago
@brave turning on throttling in the Dev Tools Network tab causes Brave to hang on the top-level navigation request.

**Comment by ericf** [comment]
@bbondy were you able to reproduce? If not, I can try to provide a more detailed repro case.

**Comment by bbondy** [comment]
I haven't tried yet sorry, more detail would be great if you don't mind though. Thanks!

**Comment by ericf** [comment]
@bbondy I just tried with the latest version of Brave and Dev Tools Network Throttling is working correctly. So you can close this issue.

```
Brave: 0.9.2
Electron: 0.37.6
libchromiumcontent: 49.0.2623.112
V8: 4.9.385.35
Node.js: 5.10.0
Update channel: dev
```

**Comment by bbondy** [comment]
great, thanks for checking again.
