### ISSUE TITLE
Save file/Export file renames to Downloads instead of actual file name

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14407]
### Description
Click on Save recovery file is downloading a file which has 'Downloads' name instead of brave_wallet_recovery

### Steps to Reproduce

  1. Open the Brave with clean profile
  2. Add few sites to Ledger
  3. Click on Advanced setting->Backup your wallet->Save recovery file

**Actual result:**
Click on Save recovery file is downloading a file which has 'Downloads' name instead of brave_wallet_recovery
![ledger-save recovery file](https://user-images.githubusercontent.com/38657976/41424954-08c01852-701d-11e8-91d1-71b9b7387782.gif)

**Expected result:**
Downloaded file name should be "brave_wallet_recovery.txt"

**Reproduces how often:**
Easy

### Brave Version
0.23.8
**about:brave info:**
 
Brave: 0.23.8 
V8: 6.6.346.32 
rev: 06c657bb7ee5530f93c37f51cc6b7bf158912d04 
Muon: 6.1.5 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.181

**Reproducible on current live release:**
No

**Comment by srirambv** [comment]
This is not limited to download file. Exporting bookmark also shows as Downloads.html

**Comment by srirambv** [comment]
On Linux it doesn't show any file name either while saving backup keys or while exporting bookmarks file
![14407](https://user-images.githubusercontent.com/17010094/41447938-e85616d0-7025-11e8-9aff-7c7b0484cc29.gif)

**Comment by bsclifton** [comment]
Removing OS specific labels as weird behavior happens on macOS also:
![screen shot 2018-06-19 at 4 52 34 pm](https://user-images.githubusercontent.com/4733304/41629947-33a902c8-73e1-11e8-8219-3f5656f17818.png)

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.16 2042c45
* Muon 7.1.1
* libchromiumcontent 67.0.3396.87
