### ISSUE TITLE
promotion offers should prompt for upgrade when needed

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#14401]
### Description
Sometimes we introduce changes into the grant claim protocol. When these changes are made it would be best for old versions of the browser who do not support the new protocol version to let the user know and ask them to upgrade to the latest version to complete their claim.

**Comment by mandar-brave** [comment]
@NejcZdovc -- can we get this fixed in 0.23?
@kjozwiak -- are we too late?

**Comment by kjozwiak** [comment]
@mandar-brave nope, definitely not too late. I'm not 100% sure if 0.23.x will be ready for next week but if we can get this fixed by the end of the week, we should have enough time to test it before we release 0.23.x. Still need a new build that's based off of C67.

**Comment by NejcZdovc** [comment]
@evq can you please spec how this would work? Not sure how we would have info about new protocol version on the old browser. What happened with the latest grant we did a breaking change without bumping protocol version, but if we bump it every time we should be good.

**Comment by evq** [comment]
we will start to return the protocol version in the promotion object returned by `GET /v1/grants` and `GET /v1/promotions`, e.g.
```
{
        "protocolVersion": 1,
        "active": false,
        "count": 92,
        "minimumReconcileTimestamp": 1527872243000,
        "priority": 0,
        "promotionId": "f22573ac-9574-48ed-ba13-94244faaf4d4",
        "stateWallet": {
         ...
        }
}
```

The protocol version refers specifically to the endpoints needed for successfully claiming a grant, so in this case protocol version 1 is our current flow with a request to `GET /v1/captchas/{paymentId}` and `PUT /v1/grants/{paymentId}`

We will have the existing endpoints `GET /v1/grants` and `GET /v1/promotions` filter and only return promotions for protocol version 1. We will make two new endpoints `GET /v2/grants` and `GET /v2/promotions` that will return all future versions. In this way once the v2 APIs are supported we can have browsers that do not support newer protocol versions still see that a promotion is available and ask the user to upgrade.

Does that make sense @NejcZdovc ?

**Comment by alexwykoff** [comment]
Closing in favor of server-side solution
