### ISSUE TITLE
Resize window doesn't properly align new tab elements

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14408]
### Description
Resize window doesn't properly align new tab elements

### Steps to Reproduce

  1. Open a new tab and resize
  2. See how links at bottom jump up when the window becomes smaller
  3. New tab image resizes to view but the text and tiles remain same size which looks awkward 

**Actual result:**
https://drive.google.com/file/d/1p7sivrxIgmakeJM-dfuArUQNYfMN_UXa/view?usp=sharing

**Expected result:**
All elements should auto resize based on window size

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.8
-- | --
V8 | 6.6.346.32
rev | 06c657b
Muon | 6.1.5
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.181

**Reproducible on current live release:**
Yes

### Additional Information
Happens all the way back to 0.21.18
cc: @bradleyrichter

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/349
