### ISSUE TITLE
Learn more link on Private or Tor tab opens a regular tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14400]
### Description
When you open a Private tab there is a link for 'Learn more...' below the Tor description and switch. If you click on this tab, it opens the page in a regular tab. Since I'm clicking on a link, I would expect it to open in a Private tab (or Tor tab if Tor is enabled).

### Steps to Reproduce

  1. Launch 0.23.8
  2. Open a Private tab.
  3. Scroll to the bottom of the page, there is a link for 'Learn more...'
  4. Click on the link.

**Actual result:**
Link opens in a regular tab.

**Expected result:**
Link should open in a Private tab or Tor tab if Tor is enabled.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
0.23.8

**Reproducible on current live release:**
n/a

**Comment by diracdeltas** [comment]
fixed by 5449d12cbceaaa88138dfa17b926e260e68f93dd

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.16 2042c45
* Muon 7.1.1
* libchromiumcontent 67.0.3396.87
