### ISSUE TITLE
Problem with amd.com - manually selecting driver. After filling the boxes, and clicking "display" nothing happens.

### ISSUE THREAD

**Issue by zvezdaburya** [brave/browser-laptop#1440]
Link to webpage [https://support.amd.com/en-us/download](url)

Under "manually select your driver" select stuff in the 4 boxes (doesnt seem to matter what is selected) and step 5 click "display results" 

Now you're supposed to get to the next page which lists available drivers, but nothing happens. 

I am using brave 0.9.1 on ubuntu 14.04 LTS.

**Comment by thepup** [comment]
I don't think this is a problem with Brave—I just tried it on Chrome on OSX and it didn't work either.
