### ISSUE TITLE
Prompt for upgrade to regular build if ads are off for extended period

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14414]
The ads test build isn't up to date with other security and privacy features in Brave or Muon. Nobody should use this build unless they're actively participating in the ads test. If someone uses this build for an hour without turning on the ads feature, they should be prompted to "upgrade" to the latest current release build of Brave, by way of a notification bar — just like normal software upgrades. cf., https://github.com/brave-intl/internal/issues/57

**Comment by diracdeltas** [comment]
i think this UI should also show up if the ads trial has ended (for instance a year from now when we're no longer collecting data)

**Comment by NejcZdovc** [comment]
done
