### ISSUE TITLE
Contribution notification displays 'undefined' instead of 'BAT'

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14417]
### Description
After using 0.23.8 to perform a ledger contribution, the notification banner says 'Your contribution of 10 undefined has been processed'. This should say BAT instead of undefined.

### Steps to Reproduce

  1.  Launch Brave with LEDGER_ENVIRONMENT=staging and a clean profile on 0.23.8
  2. Enable Payments
  3. Add some sites to the ledger table
  4. Add BAT to your staging wallet
  5. Close Brave.
  6. Adjust reconcile stamp in ledger-state.json file to be yesterday.
  7. Launch Brave with LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true LEDGER_NO_DELAY=true and LEDGER_NO_FUZZING=true if you do not have 30 minutes of browsing time.
  8. Wait for contribution to go through.

**Actual result:**
Notification banner displays 'undefined'
![screen shot 2018-06-14 at 3 43 02 pm](https://user-images.githubusercontent.com/28145373/41436728-86601a46-6ff0-11e8-8f2a-8358f820a55d.png)

**Expected result:**
Notification banner should display BAT as it does in 0.22.810
![screen shot 2018-06-14 at 4 05 43 pm](https://user-images.githubusercontent.com/28145373/41436735-8915bc46-6ff0-11e8-85c9-ad3d5f6b83f7.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.23.8

**Reproducible on current live release:**
no, this does not reproduce on 0.22.810 using staging

### Additional Information
Found by @GeetaSarvadnya on Windows. Reproduced on macOS.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.16 2042c4572e43fed49765fb3fc8f26d5a7293ac75
•	Muon 7.1.1
•	libchromiumcontent: 67.0.3396.87
