### ISSUE TITLE
Do not update model when ads is off

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14413]
Log/model should not be updated when the ads pref is switched off. Currently, it updates whether the ads pref is on or off. Entries should also not be added to the log before a user has switched the pref on for the first time. cf., https://github.com/brave-intl/internal/issues/57

**Comment by flamsmark** [comment]
CC: @mandar-brave

**Comment by mrose17** [comment]
Fixed by @NejcZdovc
