### ISSUE TITLE
Improve readability and UI of opt-in text

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14416]
<img width="895" alt="screen shot 2018-06-14 at 1 26 54 pm" src="https://user-images.githubusercontent.com/639937/41436499-afc23b5e-6fd6-11e8-84b3-9821bd78f502.png">

The opt-in prompt at <about:preferences#ads> is very difficult to read on an orange background. We really want every user to read every word of this notice. This pane should be changed to a more readable color scheme, like white on dark grey, rather than orange.

[Note: text for this pane is non-final. It will be updated after there's a full inventory of data collected and sent. #14424 ]

**Comment by flamsmark** [comment]
CC: @mandar-brave

**Comment by mandar-brave** [comment]
@flamsmark - can we also track updating of the user privacy page here as well? 
Thanks

**Comment by diracdeltas** [comment]
@mandar-brave isn't that tracked in https://github.com/brave/internal/issues/318 or are you referring to something else?

**Comment by mandar-brave** [comment]
Redundant change asked for in #57 tracked.

Updating issue;
Review color and background for readability
Once finalized, get the privacy text updated via @jenn-rhim for updating the messaging and opt in

**Comment by mandar-brave** [comment]
@diracdeltas seems like 318 and this issue overlap; i will leave that open till all of the issues are resolve and map PRs accordingly. 318 seems more like a master bug for all privacy topics.

**Comment by NejcZdovc** [comment]
done
