### ISSUE TITLE
Add ⚠️ to ads-test welcome screen

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14419]
<img width="1121" alt="screen shot 2018-06-14 at 1 32 37 pm" src="https://user-images.githubusercontent.com/639937/41436755-75defcfa-6fd7-11e8-8ab4-a537b8d6ed46.png">

The modified <about:welcome> for the ads test allows someone to click "Let's begin!" without having seen the warning about browsing activity. We should add an indicator that there's something unusual or scary so that folks are more likely to notice that this isn't normal. Proposal: a big ⚠️in the bottom left: below the button, and next to the "sends your browsing history to Brave" paragraph.

[Note: text for this page is non-final. It will be updated after there's a full inventory of data collected and sent. #14424 ]

**Comment by flamsmark** [comment]
CC: @mandar-brave

**Comment by mandar-brave** [comment]
thanks @flamsmark

**Comment by mandar-brave** [comment]
@jonathansampson is adding trial banners with this text and linking to the brave.com/hc-privacy from the welcome page. There will be a banner on the privacy page (Tracking on this issue) that will also have the same text but will not link to any other page (since the user is on the right page)

**Comment by NejcZdovc** [comment]
done
