### ISSUE TITLE
Brave probes on localhost?

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1441]
Maybe webpack dev server or something like that?
https://twitter.com/ericlaw/status/722831825215688705

CC @diracdeltas

**Comment by diracdeltas** [comment]
no wonder those port numbers looked familiar :). unminified `app/extensions/1password/code/global.min.js` and found:

```
var c = [6263, 10196, 14826, 24866, 25012, 38156, 46365, 49806, 55735, 59488]
var g = 0
...
    connectToNextPort = function() {
        if (!isConnected())
            if ('object' !== typeof safari && 'function' !== typeof WebSocket) console.warn("WebSocket was a '" + typeof WebSocket + "' instead of a function. Waiting 1 second before trying again."), connectToNextPortWithTimeout(1E3);
            else {
                g += 1;
                g >= c.length && (g = 0, 6E4 > e && (e += 2E3));
                var a = 'ws://127.0.0.1:' + c[g] + '/4';
                h && (h.close(), h = null);
                try {
                    (h = new WebSocket(a)) ? (h.onerror = function(a) {
                        console.error('[AGENT] socket error: ' + a + '; readyState=' + this.readyState + '. Perhaps Helper is not running on ' +
                            this.url + ' or is shutting down?')
                    }, ...
```

and if the socket is closed or the `try` block throws, it tries connecting again after a timeout on one of the ports in `c`.

**Comment by diracdeltas** [comment]
It's not really "probing" localhost, just trying the same 10 ports over and over. It would be kind of unexpected if the 1password component in Brave is actively trying to connect even if you disabled it in prefs. But I think this should be closed unless there are concerns with Brave trying to connect to these 10 ports.

cc @bridiver

**Comment by bridiver** [comment]
right now disabling 1password just disables the context menu. Not ideal of course, but it was a minimal implementation so disabling extensions was left out. It will be added soon.

**Comment by bbondy** [comment]
ok pls mark it for an upcoming milestone @bridiver thx!
