### ISSUE TITLE
How do you compile your own Brave for Windows 64bit?

### ISSUE THREAD

**Issue by duckx** [brave/browser-laptop#1442]
I want to embed my own javascript plugin, but I'm unsure of how does one compile their own Brave browser. What is needed and the steps involved to compile for Win 64bit?

**Comment by bsclifton** [comment]
Per the README.md:
* Install latest node.js (5.11.0)
* Install python 2.7
* Install Visual Studio OR the [newly released build tools](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/)
* node-gyp should be included with node.js, but in case you need to install it, just open your shell and run `npm install -g node-gyp@3.2.1`

At this point, you can now run `npm install` and it'll build the app (I highly recommend the [GitHub shell](https://desktop.github.com/)). [The README has the steps to generate an installer at the bottom](https://github.com/brave/browser-laptop#user-content-windows-7810-x64).

**Comment by asuh** [comment]
I can't find any info but will Python 3 not work with the build process? Also, does it require full Visual Studio or will the free version be just as useful?

**Comment by bsclifton** [comment]
@asuh you can use Visual Studio Community 2015 (the free version) or simply the build tools (all of the command line tools used by visual studio). Using a full or professional version is not required (in fact, I've never tested it 😛 )

Python 3 may have issues with node-gyp.  During the `npm install` process, it'll compile a few modules.  I would give it a shot- it may very well work.  Let us know (and apologies it took a while to respond)
