### ISSUE TITLE
Ads test build kill switch

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14421]
When the ads test stops running, it should no longer be possible to use ads test builds. If we release a new ads test build, the old builds should no longer work. In both cases, they should instead prompt for an upgrade to the current stable release. cf., https://github.com/brave-intl/internal/issues/57

**Comment by flamsmark** [comment]
CC: @mandar-brave

**Comment by NejcZdovc** [comment]
I am not sure if this is possible right now. Ads branch is not in any release channel https://github.com/brave/browser-laptop/wiki/Release-channels so we don't currently have mechanism to do auto-updates and everything that comes from official release channels. This builds are done completely manually and are based on the latest master (currently set to 0.25.x).

cc @bsclifton for his insides

**Comment by mrose17** [comment]
for now: it's possible to disable the browser, but not do an auto-upgrade. that's my goal for now.

**Comment by bsclifton** [comment]
@NejcZdovc I'd go with a timestamp based check. Maybe the build is good for 30 days. After that, it should expire and not work anymore

**Comment by mrose17** [comment]
@bsclifton & @mandar-brave - it was previously agreed between @aekeus and @mandar-brave & myself to let the server tell the browser when the trial is over. that has already been implemented in the current branch.
