### ISSUE TITLE
Notifications should come from "Brave Ads", not "terminal-notifier"

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14423]
<img width="703" alt="screen shot 2018-06-14 at 1 46 48 pm" src="https://user-images.githubusercontent.com/639937/41437487-7089118a-6fd9-11e8-9276-f4b7ef5d86d9.png">

On MacOS, the apparent application source for Brave Ads' notifications is labeled "terminal-notifier", it should have more descriptive name to make it easier to manage notifications. cf., https://github.com/brave-intl/internal/issues/57

**Comment by NejcZdovc** [comment]
fixed
