### ISSUE TITLE
Change chrome style for ads test builds

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14420]
Even if someone has opted into the ads test build, it should be easy for them to use another Brave release when they don't want to send us their browsing activity. Styling Brave an alarming and unusual color in the test builds should ensure that nobody accidentally uses the ads test build when they mean to browser privately.

**Comment by flamsmark** [comment]
CC: @mandar-brave

**Comment by diracdeltas** [comment]
It's possible this could be combined with https://github.com/brave/browser-laptop/issues/14414

for instance: if user has ads test build with ad trials turned off (or if enough time has passed such that the ads trial is no longer running), add an extra button to the alarming UI that says "click here to upgrade to the regular version of Brave"

**Comment by BrendanEich** [comment]
Looking for crisp decision: timebomb so user does not keep running unsafe build forever; or force upgrade. Thanks.

**Comment by NejcZdovc** [comment]
I think that this was addressed as well. We added kill switch and showing goodbye page if you turn ads off.

Closing
