### ISSUE TITLE
Address bar suggestions are not smart enough

### ISSUE THREAD

**Issue by ar-naseef** [brave/browser-laptop#14439]
### Description

When I start typing a web address in the address bar, suggestions are coming to an already visited path.
for example, if i start typing "yout...", instead of 'youtube.com' suggestions are popping up for 'youtube.com/watch?v=wFGUKSD-R60&feature=youtu.be'

### Steps to Reproduce

1. Open up the browser and visit youtube and play your favorite video.
2. Then close the tab and start typing "yo..". you will get the suggestions to the video you were watching instead of 'youtube.com', which you expected.

(sometimes it works as expected)

**Comment by bsclifton** [comment]
@ar-naseef if you're willing to try an experimental build, give our new Developer channel release a shot:
https://brave.com/download-dev

I think this issue specifically has been resolved 😄 Let us know
