### ISSUE TITLE
Mac OS right click trackpad+ctrl problem on Brave

### ISSUE THREAD

**Issue by michalstachecki** [brave/browser-laptop#14438]
### Description
I had a problem in Brave browser on Mac OS High Sierra 10.13.5. When I Click ctrl+trackpad click on element, I don't have context menu.
### Steps to Reproduce
1. Open Brave browser, any site (for example http://google.com)
2. Use ctrl+trackpad on any place on the site

**Actual result:**
Screen from Brave: 
<img width="189" alt="zrzut ekranu 2018-06-16 o 17 55 59" src="https://user-images.githubusercontent.com/12799026/41500252-9efb353c-718e-11e8-870b-9fa465347902.png">

**Expected result:**
Screen from Chrome, where it works
<img width="274" alt="zrzut ekranu 2018-06-16 o 17 55 38" src="https://user-images.githubusercontent.com/12799026/41500257-a2a3c032-718e-11e8-9983-1d16c71b13c0.png">

### Brave Version
Brave | 0.22.810

**Comment by Liunkae** [comment]
This is probably related to #14222 (see my comment https://github.com/brave/browser-laptop/issues/14222#issuecomment-397342412).
