### ISSUE TITLE
Block .onion requests or transplant them to tabs with Tor enabled

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14431]
If a user enters https://nyttips4bmquxfzw.onion/ into the URL bar of a tab without Tor, they probably actually wanted to reach it over Tor, and probably didn't want to notify their unfriendly neighbourhood DNS server that they're about to leak something in exchange for a name resolution error page.

- [ ] For .onion sites entered into the URL bar, we should consider either
  1. automatically transplanting them into a private tab with Tor enabled, or
  2. notifying them that the tab is not using Tor and can't reach onion services.
- [ ] For .onion sites retrieved during page load, we should consider blocking them immediately.
  - Consider, for example, testing a locally served version of an onion site, which has secret links to other onion sites.  (Old-style short onion names like the NYT Tips one above are not kept secret by the Tor network, but the next generation onion names are kept secret.)

**Comment by diracdeltas** [comment]
TODO in short term: block DNS onion requests in non-Tor tabs (Option 2)

**Comment by tomlowenthal** [comment]
The latter half of this issue is now to be found in brave/brave-browser#806.

**Comment by GeetaSarvadnya** [comment]
Verified on Linux x64
•	0.25.0 907c7e43c291e6aba5030261d22ee1f8748d654e
•	Muon 8.1.8
•	libchromiumcontent 69.0.3497.100
