### ISSUE TITLE
Unable to use pearsoned.ca

### ISSUE THREAD

**Issue by CamelCase11** [brave/browser-laptop#14441]
I am using pearsoned.ca for my college courses. I am able to log in but then after, I am redirected back to login page with error "Your session has been timed out".

- I am using latest version (0.22.810)
- I have tried to access site with shields on and off both.

**Comment by bsclifton** [comment]
@CamelCase11 can you please try with the new Developer release of Brave? This may be resolved:
https://brave.com/download-dev
