### ISSUE TITLE
Facebook videos fail to play due to CORS block policy

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14448]
### Description
Facebook videos fail to play due to CORS policy block

### Steps to Reproduce

  1. Login to FB and play any video with Shields up with default settings, starts and stops immediately
  2. Open console, shows error about CORS block policy
  3. Disable shields, video plays
  4. Enable Shields once video starts to play, plays till its streamed and then stops playing again ans starts throwing errors on console

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/41599582-a628222e-73a1-11e8-9556-2a23a0f1b793.png)

**Expected result:**
Should allow to play videos with shields up

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.810
-- | --
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Reproducible on current live release:**
Yes

### Additional Information
Multiple reports on community 
Assigning to 0.24.x as its a pretty big issue for users 
cc: @diracdeltas

**Comment by diracdeltas** [comment]
is this a dupe of #14358 ?

**Comment by srirambv** [comment]
Yes. I tried searching for this issue didn't find so had to log another one. CLosing as dupe #14358
