### ISSUE TITLE
Displaying twitter posts in new tab does not work

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14447]
### Description
Displaying Twitter Posts In New Tab Does Not Work

### Steps to Reproduce

  1. Login to Twitter website
  2. Ctrl + click on any tweet 
 
**Actual result:**
Ctrl+click on any tweet, opens the new tab with Blank content. Also new tab title is wrong.
![twitter feed issue](https://user-images.githubusercontent.com/38657976/41586384-4589c41c-73ca-11e8-8c9b-d2cdf8d9bd75.gif)

**Expected result:**
Post should open in new tab with post contents 

**Reproduces how often:**
Easily

### Brave Version
0.22.810

**about:brave info:**

Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**
Yes

### Additional Information
Issue is identified by community member
1+https://community.brave.com/t/displaying-twitter-posts-in-new-tab-does-not-work/24143

**Comment by oscargaytan** [comment]
This is not a solution but something important to remark: it can works if click in the date label (28m in your case) instead of the tweet itself.

**Comment by bsclifton** [comment]
@GeetaSarvadnya is this a duplicate of https://github.com/brave/browser-laptop/issues/14405 ?
