### ISSUE TITLE
Add the ability to open up non-Tor private tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#14459]
### Description

Currently there are 2 modes: 
i) Use all private tabs as Tor private tabs
ii) Use all private tabs as normal private tabs

<img width="1077" alt="screen shot 2018-06-19 at 3 10 28 pm" src="https://user-images.githubusercontent.com/831718/41619069-edeff308-73d2-11e8-8da5-8cf36aecdc65.png">

Tor private tabs is an awesome feature, but they are slow.  So the choice between them seamlessly is important for us to deliver this feature correctly without angering our user base.

Having an all or nothing private tab option covers the use case that a privacy conscious user wants to be fully private.

But there are other use cases that people use private tabs for, the main one being a user just doesn't want cookies saved for a 1 time login.  For example logging into gmail with 1 time access when you don't want cookies saved. 

Others include you don't want history stored, but you are ok that it's not fully private, but still want fast browsing speed.  A lot of our user base are advanced users so we need to still keep them in mind.

Currently you have to switch the global option on or off. 

There was also talk about removing the Tor indicator. That needs to be there as a reminder of why a tab is slow.

### Steps to Reproduce

For each case there should be separate items for private tabs and for Tor private tabs. 

Case 1:

Add an option when right clicking on a link:
<img width="276" alt="screen shot 2018-06-19 at 2 56 31 pm" src="https://user-images.githubusercontent.com/831718/41619227-6e17a49a-73d3-11e8-8138-d159d4569528.png">

Case 2:

Add an option in the hamburger menu:

<img width="226" alt="screen shot 2018-06-19 at 2 56 43 pm" src="https://user-images.githubusercontent.com/831718/41619238-7a3e8176-73d3-11e8-82db-de8086982b76.png">
 
Case 3:

Add an option to the new tab drop down ~(sorry no screenshot, but just click and hold the new tab button)~
![image](https://user-images.githubusercontent.com/17010094/41619989-464c9de6-73d6-11e8-9c85-439ca800fb8f.png)

**Actual result:**

Only 1 private tab option is available.

**Expected result:**

Options for both private tabs and Tor private tabs should be available. 
Please also fail this testing if there is no Tor indicator for the Tor tabs.

**Reproduces how often:**

Always.

### Brave Version
0.22.810

**about:brave info:**

 
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 17.4.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**

Only in Tor builds (Beta channel).

### Additional Information

None.

**Comment by diracdeltas** [comment]
needs input from @davidtemkin

**Comment by riastradh-brave** [comment]
in principle this is fine by me.  I'm taking a closer look and I will try to give this a test soon.

**Comment by diracdeltas** [comment]
after some discussion on what to do WRT the DDG switch, we decided:

* private tabs with tor will have DDG enabled by default regardless of the setting in regular private tabs, and no switch is shown on about:newtab for private tabs with tor
* there will be a pref in about:preferences to override this behavior (AKA use the normal default search engine)

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/browser-laptop/pull/14467

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.14 f4da855
* Muon 7.1.1
* libchromiumcontent 67.0.3396.87
* verified test steps and https://github.com/brave/browser-laptop/issues/14459#issuecomment-398863378
