### ISSUE TITLE
Make wide URL bar by default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14455]
### Description
Make wide URL bar by default

### Steps to Reproduce

  1. Install the latest beta on Windows
  2. Enable home button 
  3. Too many empty space on URL bar make it look ugly

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/41614285-14794e3c-73c6-11e8-8fe1-83ddc53b7317.png)

**Expected result:**
Enable wide URL bar so that it doesn't look like that 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave |   0.23.11
--|--
V8  |  6.7.288.46
rev  |  6565c06
Muon  | 7.1.0
OS Release   | 10.0.17134
Update Channel   | Beta
OS Architecture  |  x64
OS Platform |   Microsoft Windows
Node.js |   7.9.0
Brave Sync    | v1.4.2
libchromiumcontent    67.0.3396.87

**Reproducible on current live release:**
No

**Comment by petemill** [comment]
A compromise could be a breakpoint that makes the center url bar area quite a bit wider on very wide screens as shown in the above screenshot @rossmoody @bradleyrichter

**Comment by oscargaytan** [comment]
What resolution does your display has?
