### ISSUE TITLE
Bookmark modal alignment is off when home button is enabled/disabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14456]
### Description
Bookmark modal alignment is off when home button is enabled/disabled
### Test plan / Steps to Reproduce

  1. Enable home button from settings
  2. Add bookmark, modal shows under the URL bar 
  3. Disable home button from settings
  4. Add bookmark, hanger is shown

**Actual result:**
Hanger shows under bookmark icon but is off to the left
![bookmarks](https://user-images.githubusercontent.com/17010094/41618670-cf7fa932-73d1-11e8-8bb8-b7545c8bc841.gif)

**Expected result:**
Hanger/Modal should be under the bookmark icon irrespective of home button enabled/disabled

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave	0.23.11
V8	6.7.288.46
rev	6565c06
Muon	7.1.0
OS Release	10.0.17134
Update Channel	Beta
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	67.0.3396.87

**Reproducible on current live release:**
No

**Comment by kjozwiak** [comment]
Reproducible on macOS 10.13.4 x64 using `0.23.11` 6565c06, example:

<img width="443" alt="screen shot 2018-06-19 at 3 13 24 pm" src="https://user-images.githubusercontent.com/2602313/41619247-8035cbd4-73d3-11e8-8570-39fc58bf3762.png">

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.14 f4da855
* Muon 7.1.1
* libchromiumcontent 67.0.3396.87
