### ISSUE TITLE
Preferences menu icons looks smaller compared to the current icons set

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14458]
### Description
Preferences menu icons looks smaller compared to the current icons set

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/41619259-971affea-73d3-11e8-8127-de94f691884f.png)

![image](https://user-images.githubusercontent.com/17010094/41619254-93f41f0e-73d3-11e8-9460-459eee8b8555.png)

### Brave Version

**about:brave info:**

Brave |   0.23.11
--|--
V8  |  6.7.288.46
rev  |  6565c06
Muon  | 7.1.0
OS Release   | 10.0.17134
Update Channel   | Beta
OS Architecture  |  x64
OS Platform |   Microsoft Windows
Node.js |   7.9.0
Brave Sync    | v1.4.2

**Reproducible on current live release:**
N/A

### Additional Information
cc: @rossmoody

**Comment by NejcZdovc** [comment]
Pulled into 0.23.x as we introduced this new icons in 0.23

cc @bsclifton @davidtemkin

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14464

**Comment by srirambv** [comment]
Looks better 
![image](https://user-images.githubusercontent.com/17010094/41859996-7968efce-786b-11e8-8da2-40d7be33c4eb.png)
![image](https://user-images.githubusercontent.com/17010094/41860010-83068f50-786b-11e8-9b6b-98faa5b0795a.png)
![image](https://user-images.githubusercontent.com/17010094/41860053-a2981cd0-786b-11e8-9810-fb43609e9808.png)

Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
