### ISSUE TITLE
npm audit shows warnings (run npm audit fix)

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14450]
there's some packages with npm-detected security issues:

```
found 31 vulnerabilities (5 low, 19 moderate, 6 high, 1 critical) in 15716 scanned packages
  run `npm audit fix` to fix 6 of them.
  12 vulnerabilities require semver-major dependency updates.
  13 vulnerabilities require manual review. See the full report for details.
```

we should get the low-hanging fruit by running npm audit fix at the least

**Comment by NejcZdovc** [comment]
@diracdeltas I tried to do it, but some things are not fixed even with npm audit fix and manual fixes. Some packages are just vulnerable.  

https://github.com/brave/browser-laptop/pull/14192

**Comment by diracdeltas** [comment]
@NejcZdovc i remember that, but this issue is just to fix the low-hanging fruit which can be fixed automatically

**Comment by NejcZdovc** [comment]
@diracdeltas oh so not replacing it with nps and adding it to the travis, but just run fix and commit that?

**Comment by diracdeltas** [comment]
yes

**Comment by bsclifton** [comment]
PR fixing this was closed (https://github.com/brave/browser-laptop/pull/14462). Marking as `wontfix`
