### ISSUE TITLE
Error: package brave-0.9.2-1.amd64 is not installable

### ISSUE THREAD

**Issue by sombriks** [brave/browser-laptop#1445]
tried it at:

Linux sephiroth 4.4.7-300.fc23.x86_64 #1 SMP Wed Apr 13 02:52:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

command used:

sudo dnf install brave-0.9.2.amd64.rpm

output:

Error: package brave-0.9.2-1.amd64 is not installable
(tente adicionar '--allowerasing' a linha de comando para substituir pacotes conflitantes

**Comment by luixxiul** [comment]
How about the latest version?

**Comment by sombriks** [comment]
@luixxiul Hello, i've tried again, same result:

> [sombriks@sephiroth Downloads]$ sudo dnf install --verbose brave-0.9.6.amd64.rpm 
cachedir: /var/cache/dnf
Loaded plugins: playground, generate_completion_cache, download, copr, debuginfo-install, builddep, reposync, Query, noroot, config-manager, needs-restarting, protected_packages
DNF version: 1.1.8
repo: using cache for: fedora
not found deltainfo for: Fedora 23 - x86_64
not found updateinfo for: Fedora 23 - x86_64
repo: using cache for: rpmfusion-free
not found deltainfo for: RPM Fusion for Fedora 23 - Free
not found updateinfo for: RPM Fusion for Fedora 23 - Free
repo: using cache for: google-chrome
not found deltainfo for: google-chrome
not found updateinfo for: google-chrome
repo: using cache for: rpmfusion-free-updates-testing
not found deltainfo for: RPM Fusion for Fedora 23 - Free - Test Updates
not found updateinfo for: RPM Fusion for Fedora 23 - Free - Test Updates
repo: using cache for: rpmfusion-nonfree
not found deltainfo for: RPM Fusion for Fedora 23 - Nonfree
not found updateinfo for: RPM Fusion for Fedora 23 - Nonfree
repo: using cache for: rpmfusion-nonfree-updates-testing
not found deltainfo for: RPM Fusion for Fedora 23 - Nonfree - Test Updates
not found updateinfo for: RPM Fusion for Fedora 23 - Nonfree - Test Updates
repo: using cache for: updates
fedora: usando metadados a partir de Sat Oct 31 14:34:41 2015.
rpmfusion-free: usando metadados a partir de Sun Oct 11 13:43:19 2015.
google-chrome: usando metadados a partir de Thu May 12 19:22:39 2016.
rpmfusion-free-updates-testing: usando metadados a partir de Tue May 10 23:49:16 2016.
rpmfusion-nonfree: usando metadados a partir de Sun Oct 11 12:50:38 2015.
rpmfusion-nonfree-updates-testing: usando metadados a partir de Tue May 10 23:55:39 2016.
updates: usando metadados a partir de Thu May 12 17:36:23 2016.
Última verificação de data de vencimento de metadados: 0:21:42 atrás em Sat May 14 11:23:34 2016.
--> Começando resolução de dependência
--> Resolução de dependência finalizada
Error: package brave-0.9.6-1.amd64 is not installable
(tente adicionar '--allowerasing' a linha de comando para substituir pacotes conflitantes
[sombriks@sephiroth Downloads]$

**Comment by sombriks** [comment]
I've tried the --allowerasing option, with no luck.

> [sombriks@sephiroth Downloads]$ sudo dnf install --allowerasing brave-0.9.6.amd64.rpm 
Última verificação de data de vencimento de metadados: 0:23:39 atrás em Sat May 14 11:23:34 2016.
Error: package brave-0.9.6-1.amd64 is not installable
[sombriks@sephiroth Downloads]$

**Comment by luixxiul** [comment]
CC: @bbondy

**Comment by sombriks** [comment]
Hello all,

I've tried something different now:

> [sombriks@sephiroth Downloads]$ sudo rpm -ivh brave-0.9.6.amd64.rpm 
[sudo] senha para sombriks: 
Preparando...                         ################################# [100%]
Updating / installing...
   1:brave-0.9.6-1                    ################################# [100%]
[sombriks@sephiroth Downloads]$ 

It's up and running, if there is a problem it's on the dnf side, not brave.

**Comment by luixxiul** [comment]
Good to hear :-)

**Comment by sombriks** [comment]
charming browser btw :-)

**Comment by philiprhoades** [comment]
Confirming the rpm install works for me too - it is looking good!

Thanks!
