### ISSUE TITLE
Tracker for muon bi-directional wallet from Uphold

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#14454]
Just a tracker issue for this lovely feature :

**Comment by bsclifton** [comment]
+1 from @drozzy via https://github.com/brave/browser-laptop/issues/15138

@mandar-brave do you have an update on timing for this?

**Comment by bsclifton** [comment]
Closing as this isn't actionable; we should try to fit it into the roadmap here:
https://github.com/brave/brave-browser/wiki/Roadmap
