### ISSUE TITLE
Unable to dismiss TOR modal making it impossible to use other tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14460]
### Description
Unable to dismiss TOR modal making it impossible to use other tabs

### Steps to Reproduce
  1. Disconnect from internet
  2. Launch browser and open a private tab and enable TOR network
  3. Connection modal comes up which can't be dismissed. This makes all other tabs useless as you can't switch to normal tabs

**Actual result:**
With current behaviour only option is restart browser which makes all other open tabs useless.
![image](https://user-images.githubusercontent.com/17010094/41620282-37cc3eb0-73d7-11e8-96fc-04f67b1ee8f3.png)

**Expected result:**
Should be able to dismiss the modal so that user can close the current tab and go back to normal private tab and use other normal tabs. 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave |   0.23.11
--|--
V8  |  6.7.288.46
rev  |  6565c06
Muon  | 7.1.0
OS Release   | 10.0.17134
Update Channel   | Beta
OS Architecture  |  x64
OS Platform |   Microsoft Windows
Node.js |   7.9.0
Brave Sync    | v1.4.2

**Reproducible on current live release:**
N/A

### Additional Information
cc: @diracdeltas @riastradh-brave

**Comment by diracdeltas** [comment]
This is intended behavior for now; we can definitely try other UIs that make it less intrusive but we want the user to either restart or explicitly disable Tor in private tabs because navigation in private tabs is broken otherwise
