### ISSUE TITLE
Update windows tor binaries to 0.3.3.7

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#14463]
https://blog.torproject.org/tor-0337-released

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14507

**Comment by kjozwiak** [comment]
@jumde @diracdeltas is there a way to check which version is being used on Windows? It seems like running Brave through the command prompt doesn't output as much information as macOS & Linux does. Example:

<img width="698" alt="screen shot 2018-06-25 at 2 08 24 am" src="https://user-images.githubusercontent.com/2602313/41834145-1a3541d2-7821-11e8-8313-db37c2075a42.png">

**Comment by srirambv** [comment]
@kjozwiak binaries shows in tor log. Looks good on Windows 
![image](https://user-images.githubusercontent.com/17010094/41849864-816ef076-7850-11e8-97f5-f4e23eadbb18.png)

Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`

**Comment by kjozwiak** [comment]
Thanks @srirambv 👍 Probably should have checked the logs first ;)
