### ISSUE TITLE
Cannot drag window via empty tab bar space

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14469]
### Steps to Reproduce
  1. Open new window
  2. Mouse down in empty tab bar area and move mouse

**Actual result:**
Nothing happens

**Expected result:**
Window should move with mouse

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.23.11

**Reproducible on current live release:**
No

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
