### ISSUE TITLE
Publisher toggle allows adding site to ledger before time requirements have been fulfilled

### ISSUE THREAD

**Issue by jasonrsadler** [brave/browser-laptop#14471]
~The url bar publisher toggle allows adding a site to the ledger while it is grayed out (before requirements have been met)~

The publisher toggle is shown as disabled when loading a page

### Steps to Reproduce

  1. Launch Brave with clean profile
  2. Enable Payments
  3. Visit site and, notice grayed out publisher toggle, immediately click the grayed out publisher toggle. The site is added to the ledger with the time showing the value of PAYMENTS_MINIMUM_VISIT_TIME and the button goes to enabled and checked status

**Actual result:**
The publisher toggle is grayed out, but functional on page load.

**Expected result:**
~The publisher toggle should not be operational until requirements are met and the button is not grayed out.~
The publisher toggle should not be grayed out when a page is loaded

**Reproduces how often:**

Every time

### Brave Version

**about:brave info:**
 
Brave: 0.24.0 
V8: 6.6.346.32 
rev: 80dbf88993fb20f3b36a6a5af184d353ff40129d 
Muon: 6.0.12 
OS Release: 17.6.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Reproducible on current live release:**
Yes

### Additional Information
Reproduced on master as well as live release

NOTE: latest master with UI changes does not repro. If these go out for next build, then this can be closed

cc @NejcZdovc @ryanml

**Comment by LaurenWags** [comment]
Wasn't this intentional? https://github.com/brave/browser-laptop/issues/13879

**Comment by jasonrsadler** [comment]
This was resolved with Brave 0.23 release.
