### ISSUE TITLE
Tab doesn't stop loading indicator when opening a torrent in tor private tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14472]
## Test plan
See https://github.com/brave/browser-laptop/pull/14529

### Description
Tab doesn't stop loading indicator when opening a torrent in tor private tab

### Steps to Reproduce

  1. Open https://webtorrent.io/free-torrents in a private tor tab
  2. Click on magnet/torrent in the same tab, shows error message, page load indicator keeps going and URL bar progress indicator gets stuck 
  3. Open magnet/torrent link in a new tab, shows error message
  4. Dismiss error message, tab keeps trying to load, URL bar progress indicator gets stuck instead of closing the tab after dismissing the message

**Actual result:**
![14374](https://user-images.githubusercontent.com/17010094/41668334-21edbf8c-747d-11e8-8eb0-ba857cc8eb0e.gif)

**Expected result:**
Should stop loading the page when the error message is shown. Should close the tab after user dismiss the notification.

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information
#13063 #14374

**Comment by diracdeltas** [comment]
i have a quick fix for this

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14529

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.16 - 2042c4572e43fed49765fb3fc8f26d5a7293ac75
* Muon - 7.1.1 
* libchromiumcontent - 67.0.3396.87
