### ISSUE TITLE
Add window.chrome for compat parity with all blink browsers

### ISSUE THREAD

**Issue by hexalys** [brave/browser-laptop#1447]
I noticed that Brave doesn't have any `window.chrome` object exposed. It is a good idea to add it, as it is heavily used to detect chrome.

All Blink browsers have it, including Vivaldi, Opera, Epic and CocCoc. And Microsoft Edge added it specifically as Chrome camouflage for compatibility reason (for bad devs programming for Chrome only).

That makes Brave less identifiable and mainly, reduces possible compatibility issues.

**Comment by alexwykoff** [comment]
Shipped
