### ISSUE TITLE
Include EasyPrivacy by default

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#14476]
@darkdh just updated the DEPS to point to the new adblock which has EasyPrivacy by default.

CC @kjozwiak @srirambv @LaurenWags 

Testing notes:
This new version uses adblock v4 format.  The new ad-block v4 lib is not compatible with the old v3 DAT file which gets downloaded to the profile directory for regional DAT files and the default ad-block file `ABPFilterParserData.dat`.

Please make sure that profiles which already have the old v3 .dat file gets overwritten for both `ABPFilterParserData.dat` and for regional list .DAT files (which have a UUID for the filename) get upgraded. If it tries to use the old DAT file with the new library, then it will crash so this needs explicit testing.

**Comment by bbondy** [comment]
https://github.com/brave/ad-block/pull/95
https://github.com/brave/muon/pull/614/files
https://github.com/brave/muon/pull/616/files

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
