### ISSUE TITLE
Closing the last tab on full tabstrip and moving mouse away does not restore tab width

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14477]
### Description
There is a feature whereby the tab width is forced to not changed whilst closing tabs, so that the close tab icon (x) stays in the same position for each tab. The new tab width should then take effect when the mouse leaves the tab bar. However, there's a bug in 0.23.x beta currently whereby the mouseleave event is not received, due to new `display: contents` property.

### Steps to Reproduce

From @kjozwiak at https://github.com/brave/browser-laptop/issues/7001#issuecomment-398902317

STR:

* open about ~15 new tabs using `0.23.11` 6565c0689f8bfbd6f4d03e2e8c68c9381da157f6
* close the tab that's all the way at the end of the tab toolbar and drag the mouse onto the page
* notice that the animation isn't triggered
* move the mouse over one of the already created tabs and you'll notice the animation triggering.

Example of issue:

![animationexample](https://user-images.githubusercontent.com/2602313/41685009-39e6a132-74ad-11e8-83e2-70f5de4862c0.gif)

**Reproduces how often:**
100%

### Brave Version
0.23.11

**Reproducible on current live release:**
No

**Comment by bsclifton** [comment]
master c4b18cdcc159dbc5203769d3cdaa8fd7f48fd23a
0.24.x de04be9fbcd2dce5df4693f59d60729de12b7c2d
0.23.x cc62793a4fda0cfff0b79ae10fb099576d2765b7

**Comment by srirambv** [comment]
The animation looks pretty bad. The new tab buttons hides when tabs resize and then shows up.
![tabsbar](https://user-images.githubusercontent.com/17010094/41754957-e192c58c-75a2-11e8-91f2-991f0b13f920.gif)

**Comment by bsclifton** [comment]
@srirambv looks like that happens with our existing live build too (0.22.810). We can create another issue for that if you'd like

**Comment by petemill** [comment]
I think the issue @srirambv is showing is a new regression with #7001 which is a 0.23.x issue. By the way, none of it is to do with this issue which was fixing a different regression. I have addressed the problem with #14516

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.16 - 2042c4572e43fed49765fb3fc8f26d5a7293ac75
* Muon - 7.1.1 
* libchromiumcontent - 67.0.3396.87
