### ISSUE TITLE
Videos on linkedin cannot be unmuted

### ISSUE THREAD

**Issue by egferro** [brave/browser-laptop#14486]
Hi I run brave (0.22.810) on a windows 10. 
Videos on linkedin start but it is not possible to interact with them (meaning you cannot stop pause or unmute them) 
This was not a problem I encountered with previous versions of the Browser.
Thanks for your help. 
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by rebron** [comment]
Closing. Looks fixed with brave-core.
