### ISSUE TITLE
bitwarden window detach does not succeed

### ISSUE THREAD

**Issue by edmundlaugasson** [brave/browser-laptop#14481]
### Description
Have a Bitwarden credentials manager installed and try to detach its window - this just does not succeed.

### Steps to Reproduce
  1. enable Bitwarden credentials manager
  2. try to detach its window
  3. it does not succeed

**Actual result:**
Bitwarden window will not be detached.

**Expected result:**
Bitwarden window will be detached.

**Reproduces how often:**
Every time you try to detach.

### Brave Version
Name | Version
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 4.15.18-041518-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Reproducible on current live release:**
yes

**Comment by Liunkae** [comment]
Same as #11076?

**Comment by bsclifton** [comment]
@edmundlaugasson can you confirm you're having the problem when trying to detach the window with the button?
![screen shot 2017-09-21 at 2 32 39 pm](https://user-images.githubusercontent.com/28145373/30712350-bfe1a840-9ed9-11e7-9b02-8c22fb24ade1.png)

**Comment by edmundlaugasson** [comment]
Exactly, @bsclifton - nothing happens when I click on that button.
To be honest - I would like to open Bitwarden vault in a new window and as far as I understood, that button should open it in new window, not in new tab. I definitely need the vault in new window.
