### ISSUE TITLE
Allow $SITE to run flash notifications should not appear on tor tabs

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14480]
Since Flash is not runnable on Tor tabs (#13396), the "Allow SITE to run flash" notification bar should not appear on Tor tabs.

STR:
1. go to a tor tab and open http://www.ultrasounds.com/
2. notice the "Allow Flash to run" notification bar appears

Expected behavior: No notification bars should appear

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/browser-laptop/pull/14482

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
