### ISSUE TITLE
1password Win64 complains about unknown Chromium browser

### ISSUE THREAD

**Issue by hucekes** [brave/browser-laptop#1450]
and recommends to use a signed one like Safari, Chrome or Firefox. 
Can you please look into it? 1password is a must
Thank you

0.9.2 / libchromium 49.0.26.23.112
1password 4.6.604
windows 10

**Comment by bbondy** [comment]
You'd have to disable the signature checking for now:
https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-use-1password

Please do feel free to contact 1Password though, they have our signing details and we really want them to do that sooner than later.  They moved on OS X but not Windows yet.
