### ISSUE TITLE
map keyboard shortcut to new tor private tab

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14504]
## Test plan 
See https://github.com/brave/browser-laptop/pull/14711

## Original issue description
cmd/ctrl + shift + N perhaps

**Comment by bradleyrichter** [comment]
I think we should steer clear of Chrome's current shortcut for new private window but [command + Option + N] appears to be vacant on Mac OS Brave and Mac OS Chrome.

Needs a check on Windows

cc @diracdeltas @petemill

**Comment by diracdeltas** [comment]
@bradleyrichter what about cmd + option + [whatever the last key for private tab is]?  so on current browserlaptop it would be cmd+option+p and on brave-core it would be cmd+option+n

**Comment by BrendanEich** [comment]
I like @diracdeltas’ idea although it is big key chord.

Separately I’ve been advocating for N not P to match other browsers.

**Comment by bradleyrichter** [comment]
We all agree. Same suggestions for Brave-Core.  Command+Option+N

Command+Option+P is fine for Muon. TY...

**Comment by alexwykoff** [comment]
Official : 
New Private Tab becomes Command + Shift + N (on Mac)
New Private Tab with Tor becomes Command + Option + N (on Mac)

**Comment by diracdeltas** [comment]
i'm doing other release/blocking issues and this one is pretty straightforward, so someone can take it if they feel like it

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.33 f3426e8
* Muon 7.1.5
* libchromiumcontent 67.0.3396.103

**Comment by srirambv** [comment]
Failed on windows. Logged issue https://github.com/brave/browser-laptop/issues/14716

![image](https://user-images.githubusercontent.com/17010094/42596437-a3d1e8a0-8523-11e8-9c52-ec6bb22df580.png)
