### ISSUE TITLE
Controlport  blocks tor connection after browser restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14503]
### Description
Controlport  blocks tor connection after browser restart

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**
Doesn't connect to tor after browser restart
**Expected result:**
Should connect to tor after restart

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by diracdeltas** [comment]
closed by https://github.com/brave/browser-laptop/pull/14502

**Comment by kjozwiak** [comment]
@sri can you add the STR in the original issue and mark it as `QA/test-plan-specified`? I manually added this issue into our manual passes.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.14 f4da855
* Muon 7.1.1
* libchromiumcontent 67.0.3396.87
