### ISSUE TITLE
Twitch channels not showing verified icon on ledger table

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14518]
### Description
Twitch channels are not showing the verified icon. (similar to https://github.com/brave/browser-laptop/issues/14351 for YouTube)

### Steps to Reproduce

1. Enable Payments.
2. Visit a site like DDG (or other verified site) for a bit.
3. Visit ledger table, DDG is listed and shows verified icon.
4. Watch a video on a verified Twitch site.
5. Visit ledger table.

**Actual result:**
Twitch channels are listed but no verified icons display.

**Expected result:**
If verified, Twitch channels should show as verified.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.22.810

**Reproducible on current live release:**
Yes

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/green-checkmark-publisher-verification-and-payments/27375

**Comment by NejcZdovc** [comment]
@LaurenWags this was fixed in 0.23 https://github.com/brave/browser-laptop/pull/14485

**Comment by NejcZdovc** [comment]
my bad that was youtube
