### ISSUE TITLE
Browser doesn't connect to TOR on initial launch.

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14517]
### Description
Browser doesn't connect to TOR on initial launch.

### Steps to Reproduce

  1. Launch brave with clean profile from console
  2. Open new private tab
  3. Enable TOR switch
  4. Observe the pop up with Disable tor and Restart brave options
  5. Verify console - it throws an error

**Actual result:**
Browser doesn't connect to TOR on initial launch.
![tor- new profile launch from console issue](https://user-images.githubusercontent.com/38657976/41775888-61ed6fb6-7643-11e8-92ef-4fdc4406c560.gif)

**Expected result:**
Browser should connect to TOR on initial launch.

**Reproduces how often:**
100%

### Brave Version
0.23.14

**about:brave info:**
 
Brave: 0.23.14 
V8: 6.7.288.46 
rev: f4da85553f32e2c31539bab6cfbf32619ef0a936 
Muon: 7.1.1 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
No

### Additional Information
follow up to 14503 issue

**Comment by bsclifton** [comment]
I believe this is Windows only - works great on macOS and Linux.  On Windows when connecting, I get the following via stdout:
```
tor: control socket error: Error: connect ECONNREFUSED 127.0.0.1:52408
tor: control socket closed early
```

When looking at the tor logs though, version 3.3.7 is used and it appears to launch successfully

**Comment by bsclifton** [comment]
After receiving the above, I manually deleted the `C:\Users\brian\AppData\Roaming\brave-beta\tor\watch\controlport` file and relaunched. It took 2 attempts, but now Tor is being initialized properly

1st relaunch (which did not work) had the following on stdout:
```
tor: tossing stale cookie
```

2nd relaunch (which does work) has this output via stdout
```
tor: daemon listens on 127.0.0.1:9260
tor still not ready
Tor ready!
```

**Comment by riastradh-brave** [comment]
Can you share, from two consecutive runs, the following things?

1. console output
2. content of %appdata%\brave\tor\data\tor.log
3. content of %appdata%\brave\tor\data\controlport or %appdata%\brave\tor\data\controlport.ack

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14526

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.16 - `2042c45`
* Muon - `7.1.1`
* libchromiumcontent - `67.0.3396.87`
