### ISSUE TITLE
Zoom level resets when navigating a site 

### ISSUE THREAD

**Issue by caffeine74** [brave/browser-laptop#1451]
When navigating dev.mysql.com new pages load at reduced zoom level.

Brave: 0.9.2
Electron: 0.37.6
libchromiumcontent: 49.0.2623.112
V8: 4.9.385.35
Node.js: 5.10.0
Update channel: dev

on Linux Mint 17.2 w/ kernel 4.4.4-040404-generic

**Comment by msp1111111** [comment]
Same for other sites - Win 7 64 bit
But is showing a weird behavior -- as I navigate away from the page, sometimes it momentarily shows the increased zoom that it remembers from before.
