### ISSUE TITLE
Address bar shows the wrong address after closing tab

### ISSUE THREAD

**Issue by luislhl** [brave/browser-laptop#14513]
### Description
Say I have two tabs open, tab 1 and tab 2, and tab 1 is currently opened.

If I click on the address bar letting the text in it selected, and then close the tab using Command + W (I'm on a MAC), the address which was in the tab 1 address bar will now appear in the tab 2 address bar.

### Steps to Reproduce
  1. Open a new window
  2. Open some site in it, `brave.com`, for example.
  3. Open a new tab
  4. Open some other site in the new tab, `github.com`, for example.
  5. Click on the address bar to select the address
  6. Close the tab using Command + W

**Actual result:**
The address bar of the remaining tab contains `github.com`.

**Expected result:**
The address bar of remaining tab should contain `brave.com`.

**Reproduces how often:**
All the times I've tested, with any site that I open.

### Brave Version
 
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**
I'm not sure what that means. I downloaded the browser from the website, didn't build by myself.

### Additional Information
It does not happen if, in step 6, I close the tab by clicking in its `X` button.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/url-incorrect-when-previous-tab-closed/26778?u=eljuno and +1 from me.

**Comment by codeluggage** [comment]
Same happens for me. Pressing `escape` brings back the proper URL. 

**Brave version**

Brave: 0.23.77 
V8: 6.8.275.24 
rev: 0125b5f5ddc7eebc832ceeb4f4275230ec49d149 
Muon: 8.0.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Comment by eljuno** [comment]
+1 from community for blank URL https://community.brave.com/t/two-recurrent-issues-1-copy-paste-stops-working-2-the-url-line-self-erases/29917/2?u=eljuno
