### ISSUE TITLE
Show my windows/tabs from last time

### ISSUE THREAD

**Issue by djjstew** [brave/browser-laptop#1452]
Sometimes this does not work and I think I noticed why I get a blank Brave rather than my last session.  When looking at the task manager (Win 10 Build 14295.rs1 release 160318-1628) I see that there are two instances of Brave still running after closing Brave.  If i start Brave I get the blank session. If I end those task or restart my computer I get the last session.  Thank you!

**Comment by luixxiul** [comment]
Fixed with #1540
