### ISSUE TITLE
URLbar paste-and-search should be disabled till Tor connection is successfully created

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14525]
### Description
URLbar should be disabled till Tor connection is successfully created

### Test plan / Steps to Reproduce

  1. Clean install 0.23.14
  2. Launch browser and open a new tor private tab
  3. While connection is being established, right click on URL bar and paste and search
  4. Tries to load search while TOR connection is being created
  5. Connection fails, doesn't load search result and throws about:error page
  6. Open a new tor tab doesn't connect but log says `Bootstrap 100% Done`

**Actual result:**
Paste and search from context menu in URL while establishing tor connection breaks flow

https://youtu.be/RugK4-4MFVs

Tor Log shows 
```
Jun 22 16:36:49.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
```

**Expected result:**
URL bar should just show connection info and be in read only state while Tor connection is being established. If unsuccessful, clicking on `Disable Tor` button should activate URL bar 
 
**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.23.14
-- | --
V8 | 6.7.288.46
rev | f4da855
Muon | 7.1.1
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

**Reproducible on current live release:**
N/A

### Additional Information
cc: @kjozwiak @LaurenWags @btlechowski  @GeetaSarvadnya

**Comment by diracdeltas** [comment]
i think the urlbar context menu should be disabled entirely for tor tabs until tor is loaded, since the urlbar input is disabled in that state. done in https://github.com/brave/browser-laptop/pull/14527

**Comment by diracdeltas** [comment]
related issue (also applies to regular private tabs): https://github.com/brave/browser-laptop/issues/14530

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14527

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.16 2042c4572e43fed49765fb3fc8f26d5a7293ac75
•	Muon 7.1.1
•	libchromiumcontent: 67.0.3396.87
