### ISSUE TITLE
Pinned tabs shift when closing tabs (before animating)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14528]
### Description
I suspect this is related to https://github.com/brave/browser-laptop/pull/14516 (I didn't test with pinned tabs). The pinned tab locations seem to shift after closing tabs. When mouse is moved out of a tab (so that the animation fires) it goes back to looking correct

### Steps to Reproduce

  1. Have multiple pinned tabs
  2. Open 3 new tabs
  3. Close tab 1
  4. Close tab 2

**Actual result:**
Pinning looks distorted- see this image
![close-animation](https://user-images.githubusercontent.com/4733304/41802317-cfebbc16-7634-11e8-82ae-ff2c7887d11e.gif)

**Expected result:**

**Reproduces how often:**

### Brave Version
0.23.15

**about:brave info:**

**Reproducible on current live release:**
No

**Comment by petemill** [comment]
Fixed for 0.23.x via 516f536c3

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.16 - 2042c4572e43fed49765fb3fc8f26d5a7293ac75
* Muon - 7.1.1 
* libchromiumcontent - 67.0.3396.87
