### ISSUE TITLE
Private tab doesn't allow torrent download

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14524]
## Test plan
See https://github.com/brave/browser-laptop/pull/14529

### Description
Private tab allows to download torrent

### Steps to Reproduce

  1. Open a private tab in 0.22.810
  2. Load https://webtorrent.io/torrents/big-buck-bunny.torrent
  3. Torrent downloads
  4. Open a private tab in 0.23.14
  5. Load https://webtorrent.io/torrents/big-buck-bunny.torrent 
  6. Doesn't show any error that it can't download, tab becomes empty 

**Actual result:**
Private tab allows to download torrent

**Expected result:**
Should allow torrents to run in private tab or should show error similar to tor tab that it should not be allowed to run

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.22.810 and 0.23.14

**Reproducible on current live release:**
Works on release but not on beta

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14529

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.16 - 2042c4572e43fed49765fb3fc8f26d5a7293ac75
* Muon - 7.1.1 
* libchromiumcontent - 67.0.3396.87
