### ISSUE TITLE
Google Drive multiple file download fails with Shields enabled

### ISSUE THREAD

**Issue by vertigo220** [brave/browser-laptop#14534]
### Description

See title

### Steps to Reproduce

  1. Log in to Drive.
  2. Select multiple files, then download.
  3. It will pop up with an error saying zip failed.
  4. Disable Shields and try again. Now it works.

**Actual result:**

Zip fails

**Expected result:**

Zip should work

**Reproduces how often:**

100% AFAICT

### Brave Version
 
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**

?

### Additional Information

It did the same thing in Firefox until I disabled an extension that modifies referers. Not sure if that's the problem here or if it's something else.

**Comment by srirambv** [comment]
Can you check allowing all cookies fixes the issue? You can change the setting in shields for Google Drive

**Comment by vertigo220** [comment]
It does. I suspect it's googleusercontent.com.

**Comment by bsclifton** [comment]
@vertigo220 can you try this with the latest version of Brave? I believe this issue may have been fixed (even with shields up)

**Comment by vertigo220** [comment]
It works, but was it actually fixed? Because you gave it a "workaround" tag, so I'm curious if the "fix" was just, as the tag says, to allow all cookies.

**Comment by bsclifton** [comment]
@vertigo220 if it works with shields up and the default `block 3rd party cookies`, then it's definitely fixed. I have been tagging the `webcompat` issues with any known work-around until there is a definitive fix

We had a related fix for *.google.com domains, which happened in https://github.com/brave/browser-laptop/pull/13820
