### ISSUE TITLE
adding Tor version into "about:brave"

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14539]
## Test plan
See https://github.com/brave/browser-laptop/pull/14543

### Description

Maybe we won't have enough time to do this in the initial release, but I think it would be a good idea to include which Tor version Brave is using within `about:brave`. This way, users that don't know how to run Brave via a terminal/console and quickly check which version is being used.

### Steps to Reproduce

  1. launch `0.23.x` which includes Tor PT's
  2. open `about:brave`

**Actual result:**

We're not listing the Tor version within `about:brave`. Users will need to run brave through the terminal/console to see which version of Tor is being used. Windows doesn't really output this information either. See https://github.com/brave/browser-laptop/issues/14463#issuecomment-399847680

**Expected result:**

Users should be able to load `about:brave` and see which version of Tor is currently being used.

**Reproduces how often:**

100% reproducible using the latest `0.23.x` build.

### Brave Version

**about:brave info:**

```
Brave: 0.23.16 
V8: 6.7.288.46 
rev: 2042c4572e43fed49765fb3fc8f26d5a7293ac75 
Muon: 7.1.1 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87
```

**Reproducible on current live release:**

Not reproducible in the current released build as Tor is a new feature that's being released in `0.23.x`.

**Comment by LaurenWags** [comment]
+1 from me

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14543

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/41865144-3e7e8464-787a-11e8-856d-b2007a49e5cf.png)

**Comment by kjozwiak** [comment]
@riastradh-brave @bsclifton @diracdeltas thanks for getting this into `0.23.x` 👍
