### ISSUE TITLE
HTTPS site may be marked as insecure

### ISSUE THREAD

**Issue by tsekityam** [brave/browser-laptop#14533]
### Description
https://vps.sakura.ad.jp/ is marked as insecure even if it is using HTTPS scheme.

### Steps to Reproduce

  1. Go to https://vps.sakura.ad.jp/ with Brave Browser

**Actual result:**
The website is marked as insecure.
![screen shot 2018-06-24 at 11 57 01 am](https://user-images.githubusercontent.com/3814422/41815739-216958a6-77a6-11e8-97ab-35658ebd432c.png)

**Expected result:**
The website is marked as secure, as Chrome did
<img width="1440" alt="screen shot 2018-06-24 at 11 57 08 am" src="https://user-images.githubusercontent.com/3814422/41815746-2fc5fd3c-77a6-11e8-9bc5-77952615af78.png">

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**
Yes, I reproduce it with v0.22.810 

### Additional Information
https://www.ssllabs.com/ssltest/analyze.html?d=vps.sakura.ad.jp

**Comment by diracdeltas** [comment]
could not repro by simply visiting the site 
![screen shot 2018-06-25 at 5 51 57 am](https://user-images.githubusercontent.com/549654/41851190-f6eea630-783b-11e8-8b75-2d2e2b6ba2bb.png)
