### ISSUE TITLE
context-menu search items doesn't use DDG if the private tab search engine is DDG

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14530]
Repro'ed on current release (0.22.x):

## Test plan
1. open a private tab and turn on duckduckgo for private tabs
2. copy some text
3. in the private tab, right-click on the urlbar and hit 'paste and go'
4. it searches using google not ddg
5. open another private tab, right-click some text and select 'Search for ...'
6. it searches using google not ddg

expected: it searches using duckduckgo in both cases

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14531

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.16 - 2042c4572e43fed49765fb3fc8f26d5a7293ac75
* Muon - 7.1.1 
* libchromiumcontent - 67.0.3396.87
