### ISSUE TITLE
bookmark manager still uses star icons for bookmarks

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14545]
### Description
When you navigate to the bookmark manager, the old star icon is displayed instead of the new icon for import/export of bookmarks and manually adding a bookmark.

### Steps to Reproduce

  1. Launch 0.23.16
  2. Navigate to about:bookmarks

**Actual result:**
Star icon is displayed for:
- Import/Export of bookmarks
- manually adding a bookmark
![screen shot 2018-06-25 at 12 03 45 pm](https://user-images.githubusercontent.com/28145373/41862007-c6fabfce-7870-11e8-96f7-340b09454435.png)

**Expected result:**
New bookmark icon should be displayed.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.23.16

**Reproducible on current live release:**
no

**Comment by bsclifton** [comment]
Let's open an issue for this if we see it in brave-core 😄 👍
