### ISSUE TITLE
bookmark icon on top site tiles is the old star icon

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14544]
### Description
When you hover over a top site tile on the new tab dashboard the old star icon is displayed instead of the new icon.

### Steps to Reproduce

  1. Launch 0.23.16
  2. Open new tab
  3. Hover over a top site tile

**Actual result:**
Star icon is displayed. Here is what it looks like when the site is not bookmarked:
![screen shot 2018-06-25 at 12 03 09 pm](https://user-images.githubusercontent.com/28145373/41861789-36bdbe7a-7870-11e8-962f-ad3463b24656.png)

This is an example of the filled-in star for when the top site is bookmarked:
![screen shot 2018-06-25 at 12 03 34 pm](https://user-images.githubusercontent.com/28145373/41861802-414fc4e6-7870-11e8-8ef0-b0a86cd08a7b.png)

**Expected result:**
New bookmark icon should be displayed.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.23.16

**Reproducible on current live release:**
no

**Comment by bsclifton** [comment]
Let's open an issue for this if we see it in brave-core 😄 👍
