### ISSUE TITLE
Add Credit Card to Autofill Settings does not save card on Mac OS X

### ISSUE THREAD

**Issue by bartleyg** [brave/browser-laptop#14540]
### Description
In Preferences, Add Credit Card to Autofill Settings does not save the card on Mac OS X. After inputting card information and clicking Save, "No saved credit cards" is still present under Credit Cards header. Refreshing the preferences page, repeating the steps, closing and reopening browser do not work.

### Steps to Reproduce
  1. Preferences -> Security -> Autofill Settings -> Manage Autofill Data... -> Add Credit Card
  2. Type in valid credit card info and click Save

**Actual result:**
"No saved credit cards" still present under Credit Cards heading.

**Expected result:**
Newly added credit card to be populated under Credit Cards heading.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**
Yes

### Additional Information
Could be related to issues https://github.com/brave/browser-laptop/issues/3370 and https://github.com/brave/brave-browser/issues/369.
I'm using Brave Built-in password manager if that helps.

PS: Thanks for the great browser! 😄

**Comment by rebron** [comment]
Closing. Fixed with brave-core.
