### ISSUE TITLE
Entire div on Learn more is clickable 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14549]
### Description
Entire div on Learn move is clickable 
### Steps to Reproduce
  1. Open a new tor tab 
  2. Click on the div for `Learn More`
  3. Opens up a new tab 

**Actual result:**
![tordiv](https://user-images.githubusercontent.com/17010094/41866690-e7d3f61c-787e-11e8-9464-8e0ce54cc593.gif)

**Expected result:**
Only Learn more should be clickable and not the entire div

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave|0.23.17
--| --
V8|6.7.288.46
rev|bc754eb
Muon|7.1.2
OS Release|10.0.17134
Update Channel|Release
OS Architecture|x64
OS Platform|Microsoft Windows
Node.js|7.9.0
Tor|0.3.3.7 (git-035a35178c92da94)
libchromiumcontent|67.0.3396.87

**Reproducible on current live release:**
N/A

### Additional Information
Issue reported by @kjozwiak on Linux, reproduced on mac by @LaurenWags

**Comment by I3uckwheat** [comment]
I can fix this!
