### ISSUE TITLE
New icons get camouflaged on several new tab images

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14542]
### Description
New icons get camouflaged on several new tab images

### Steps to Reproduce
  1. Install 0.23.16 
  2. Open new tab 
  3. Hover over shortcuts on bottom right, icons get camouflaged on several new tab images

**Actual result:**
![newtab_settings](https://user-images.githubusercontent.com/17010094/41859544-646430b2-786a-11e8-892c-cfc441354b56.gif)

**Expected result:**
Icons should not get camouflaged when mouse over

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave	0.23.16
V8	6.7.288.46
rev	2042c45
Muon	7.1.1
OS Release	10.0.17134
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	67.0.3396.87

**Reproducible on current live release:**
N/A

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.19 178c3fbc045a0cbdbe098db08307503cce952081
•	Muon 7.1.3
•	libchromiumcontent: 67.0.3396.87
