### ISSUE TITLE
separating shield settings between Tor PT's and PT's

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14559]
### Description

We should have the discussion about possibly separating shield states between PT's and Tor PT's like we do between regular tabs and PT's. Now that the two are two different modes, I think it would be a good idea if we separated the states. This way a user can have different shield settings on specific websites using Tor PT's which will not affect PT's.

### Steps to Reproduce

  1. launch brave that includes Tor PT's
  2. open a PT, visit https://audiofingerprint.openwpm.com/ and disable the shield
  3. launch a Tor PT and visit https://audiofingerprint.openwpm.com/

Notice that the shields are now disabled for both PT's and Tor PT's.

**Actual result:**

Shield states between PT & Tor PT's are not separated and share the same settings.

**Expected result:**

Shield states between PT & Tor PT's should be separated.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.23.18 
V8: 6.7.288.46 
rev: c101002980044695e3e4291cf798e456f4d38dbf 
Muon: 7.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87
```

**Reproducible on current live release:**

Currently not reproducible on `0.22.810` which is the latest released version. The Tor PT feature is landing in `0.23.x`.

### Additional Information

CCing @diracdeltas @riastradh-brave

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1009
