### ISSUE TITLE
Shields icon needs fill color

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14551]
As requested by @bradleyrichter at https://github.com/brave/browser-laptop/issues/13981#issuecomment-400020157, the shields logo (brave logo) needs to not have a transparent face, but be filled-in for all states.

Transparent face:
![image](https://user-images.githubusercontent.com/741836/41875656-79c67666-7880-11e8-952e-6f0e4f470bc7.png)

Filled-in face:
![image](https://user-images.githubusercontent.com/741836/41875677-8a48a70c-7880-11e8-999e-daf875e48aba.png)
 
Brave: 0.23.14 
V8: 6.7.288.46 
rev: f4da85553f32e2c31539bab6cfbf32619ef0a936 
Muon: 7.1.1 
OS Release: 17.5.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.18 - c101002980044695e3e4291cf798e456f4d38dbf
* Muon - 7.1.2
* libchromiumcontent - 67.0.3396.87
