### ISSUE TITLE
session tab icons overlapping

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14553]
### Description

When opening a session tabs, you'll notice that the # icon is overlapping the session icons.

### Steps to Reproduce

  1. launch `0.23.17` bc754ebe4dd8d8f59a322660e8af1962a99753ea 
  2. open a new session tab
 
**Actual result:**

<img width="162" alt="screen shot 2018-06-22 at 12 29 24 am" src="https://user-images.githubusercontent.com/2602313/41885843-ad07da14-78c7-11e8-81e4-f3e4560394f6.png">

**Expected result:**

<img width="224" alt="screen shot 2018-06-25 at 10 12 35 pm" src="https://user-images.githubusercontent.com/2602313/41885849-b12e84f8-78c7-11e8-96c8-f47b76f69082.png">

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.23.17 
V8: 6.7.288.46 
rev: bc754ebe4dd8d8f59a322660e8af1962a99753ea 
Muon: 7.1.2 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87
```

**Reproducible on current live release:**

Currently only reproducible on `0.23.x` and not `0.22.810` which is the latest released version.

### Additional Information

* macOS 10.13.4 x64 - Reproduced (@kjozwiak)
* Win 10 x64 - Reproduced (@srirambv)

**Comment by petemill** [comment]
I believe this is a clash with this PR: https://github.com/brave/browser-laptop/pull/13785 which seems to not have a milestone but is contained within 0.23. I can fix.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.19 178c3fbc045a0cbdbe098db08307503cce952081
•	Muon 7.1.3
•	libchromiumcontent: 67.0.3396.87
