### ISSUE TITLE
Brave users can easily be identified and fingerprinted through version number and height/width "tricks"

### ISSUE THREAD

**Issue by ciampolo** [brave/browser-laptop#14550]
Seeing how you do not keep the version number in sync with Chrome ( Chrome is 67.0.3396.99  current Brave bin linux64 is 67.0.3396.71 ) makes you heavily stand out specifically if a certain subset of users have the exact same "outdated" version. Brave should just check on startup current Chrome version number (but not connect to Google servers) and then use that number.

Also users are easily and perfectly identifiable as using Brave by calculating the div.clientWidth/clientHeight and window.innerWidth/innerHeight since the topbar in Brave has a unique height. In addition it is specifically easy to fingerprint Linux users since Linux users can have a (talking about the Desktop themselves) topbar a bottom bar no bars, no window controls, 50px window controls etc. all influencing these values. 

As long as this is not addressed you can hide/fake/block everything you want it won't matter, specifically for Linux users. At least the website you are visiting still will at the very least be able to tell that you are using Brave and, if you are a Linux user will most certainly be able to uniquely identify you. 
KDE has uniquely sized bar. Gnome has a uniquely sized bar. i3 has a uniquely sized bottom bar. fvvwm has no bar. Someone else is running i3 with polybar making his bar use 5px more height etc. etc.

**Comment by srirambv** [comment]
cc: @diracdeltas @jumde

**Comment by ciampolo** [comment]
While we are at it: Setting content-language to anything else than the geo-ip local language does not provide privacy. Contrary it makes you heavily stand out. Just think about how many Germans who use stock Chrome (like you want to imitate) and have a German IP would specifically set content-language to English? And even if they do you would instantly know they are somehow worried about their privacy defeating the whole purpose of changing the language in the first place (blending in). You don't blend in if a German IP requests content in English from a purportedly "stock chrome".

If I as a German user don't specifically choose an US/UK VPN (and believe me I would rather trust a North Korean service), setting content language to en literally makes me more unique. 

I couldn't check yet whether Brave also manipulates date/tz etc. javascript objects but if so then this is another case of doing the contrary of blending; at least for anyone outside of the US. And US people, logically, wouldn't need those manipulations anyway.

**Comment by riastradh-brave** [comment]
The inner and outer dimensions, as visible to web sites, are the same in Brave right now, as demonstrated by the following web page.

```
<!DOCTYPE html>
<html>
<body>
<p id="foo">foo</p>
<p id="bar">bar</p>
<script>
width = window.innerWidth + ' ' + window.outerWidth
document.getElementById('foo').innerHTML = width
height = window.innerHeight + ' ' + window.outerHeight
document.getElementById('bar').innerHTML = height
</script>
</body>
</html>
```

(If you get into the muon developer console, which is privileged above web sites, you can see the window decorations, but that's not relevant unless you break out of the sandbox.)

There is a [regression](https://github.com/brave/brave-browser/issues/721) in the upcoming Brave 1.0 but we'll fix it before release.  I've filed a few other issues for other fingerprinting vectors in Brave 1.0.

**Comment by Atavic** [comment]
> div.clientWidth/clientHeight and window.innerWidth/innerHeight

Firefox is not different. Tor is actually using generic dimensions, as:

"privacy.window.maxInnerWidth", 1600
"privacy.window.maxInnerHeight", 900

> Setting content-language to anything else than the geo-ip local language does not provide privacy. Contrary it makes you heavily stand out.

You're right. Tor gives the option to change locale to the most used one:

"intl.accept_languages", "en-US, en"
