### ISSUE TITLE
An option for less analytics in Payments (mainly just Publishers and Percentages)

### ISSUE THREAD

**Issue by NumDeP** [brave/browser-laptop#14557]
Have you searched for similar issues? 
Yes.

### Description

Some users and arguably a lot of new privacy conscious users moving to Brave would prefer a 'less analytics, just pay' option in the payments-client-ledger system for fear of data being acquired by unnecessary parties even though it is stressed that the ledger system is anonymous.

From the client side of things I don't think many feel comfortable seeing data/information being compiled like that. I think they're afraid of how it looks similar to standard web browsing history and how it allocates historical and other kinds of analytics such as time visited as well as number of times visited.

So to avoid stressing these particular users that are concerned about the fact how it quite starkly resembles their web browsing history even though most if not all of the information pertaining to that side of the system is anonymous, I was wondering if it would be okay to allow a sort of function consoling some users by giving them an option for a 'less analytics, just pay' feature which will literally only show and record Publishers and Percentages.

### Additional Information

As about:preferences#payments is usually Off, it would be helpful when it is turned on for a series of Gifs to be presented quickly showing ways in which the ledger system can be utilized.

If the option itself isn't toggled until later-on when users become uncomfortable with the data being presented, the toggle afterwards for the 'less analytics, just pay' option would essentially just refresh the client-ledger state, excluding the publishers and the percentages designated.

FYI - I don't really test features and mostly use the features and settings naturally the way I see fit, so I couldn't stipulate that 'Brave Payments attention data' in Security-Private Data should be optimized for the option being proposed because I don't know whether users would or won't prefer it. 

If this option is taken into consideration it may be appreciated to temporarily allow the viewing of statements only and after contributions have been officially made rather than it being recorded.

**Comment by bsclifton** [comment]
Closing since we're overhauling `Brave Payments` as `Brave Rewards` 😄 Stay tuned for that release (you can refer back to this once we have something live)
