### ISSUE TITLE
Tor sometimes wedges after suspend/resume

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14567]
# TEST PLAN

start a local http server on port 9250, ex: "python3 -m http.server 9250 --bind 127.0.0.1"
start brave and open tor tab
wait for tor error to show
click 'retry' button
it should show 'connecting...' then show the error again
now kill the HTTP server from step 1
click 'retry' again. tor should connect this time.

### Description
After suspending and resuming a few minutes later, the tor daemon sometimes fails to reconnect to the network.

Candidate workaround: Allow users to forcibly restart the tor daemon.

### Steps to Reproduce
  1. Open a private tab with Tor in Brave.
  2. Suspend your machine.
  3. Wait a few minutes.
  4. Resume your machine.
  5. Wait for the 'Tor could not connect to the network' box to pop up after 20sec.
  6. Wait for the message to go away.

**Actual result:**
The message never goes away.  In tor.log, there is no indication that the tor daemon was able to reconnect to the Tor network.  It appears wedged.

**Expected result:**
The tor daemon reconnects to the Tor network and Brave continues on its merry way to let you anonymously read scandalous news stories about drama in the local crocheting circle.

**Reproduces how often:**
About 1%.  It may depend on the network you're on, and on the operating system you're using.

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.17
V8 | 6.7.288.46
rev | b79ebb2
Muon | 7.0.7
OS Release | 4.13.0-41-generic
Update Channel |  
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

or something near it.

**Reproducible on current live release:**
soon to be

### Additional Information
The drama in the local crocheting circle is NOT MY FAULT.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/14568

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.19 - 178c3fb
* Muon - `7.1.3`
* libchromiumcontent - `67.0.3396.87`
