### ISSUE TITLE
Tor daemon doesn't get notified about network status 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14577]
### Description
Tor daemon doesn't get notified about network status 

### Steps to Reproduce
  1. Clean install 0.23.x and open a Tor tab, ensure it shows Successfully connected message
  2. Disconnect device from network
  3. Open a new Tor tab, still shows Successfully connected message when system is disconnected from network

**Actual result:**
![tor network](https://user-images.githubusercontent.com/17010094/41987201-7517ef00-7a06-11e8-889f-4860d5dfb7a7.gif)

**Expected result:**
Should show error message when system goes offline and should automatically connect when system is back on network 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave |	0.23.19
--|--
V8	|6.7.288.46
rev	178c3fb
Muon|	7.1.3
OS Release	|10.0.17134
Update Channel|	Release
OS Architecture|	x64
OS Platform	|Microsoft Windows
Node.js	|7.9.0
Tor	|0.3.3.7 (git-035a35178c92da94)
Brave Sync	|v1.4.2
libchromiumcontent	|67.0.3396.87

**Reproducible on current live release:**
N/A
### Additional Information
Issue reproduced on Linux by @kjozwiak 
Only happens when the browser is already connected to Tor network and then system goes offline.

**Comment by riastradh-brave** [comment]
I'm told we should monitor the NETWORK_LIVENESS event, not CIRCUIT_ESTABLISHED/CIRCUIT_NOT_ESTABLISHED.

**Comment by alexwykoff** [comment]
per @riastradh-brave the pr above has fixed the issue.

**Comment by riastradh-brave** [comment]
It takes a minute or two for the tor daemon to recognize that it can't reach the network, if you try to load a page.  (If idle, it may take longer.)  Can you report, if you wait a couple minutes after turning the network off _and_ trying to load a new page, whether it reports failure or continues to claim success?

Note that Brave will time out waiting for the proxy to answer in much less than a minute.  That's only Brave's assessment of whether a _single attempt_ to connect through the proxy works, not tor's persistent assessment of whether we are still connected to the Tor network at all, which takes longer for tor to determine.

What the PR from two weeks ago fixes is that previously we would _never_ receive a notification from tor that we're no longer connected to the Tor network at all, unless the machine is suspended and resumed a few minutes later.

**Comment by LaurenWags** [comment]
@riastradh-brave here's what I did based on your note above:
Launched Brave
Opened a Tor Private Tab, verified successfully connected msg shows in URL bar
Disconnected from network
Waited 2 minutes (during which I bounced to other already open tabs so Brave was not idle) --> did not get any msg about unable to connect to Tor network
Opened another Tor Private Tab --> saw successfully connected msg in URL bar
Tried to load a site (DDG) --> eventually timed out but still no msg about unable to connect to Tor network
If you'd like me to try some other stuff out lmk - happy to provide whatever info you need.

**Comment by riastradh-brave** [comment]
We discussed this a bit on Slack.

Even with the change to listen for the right notifications, the tor daemon sometimes doesn't notice promptly that the network is gone and so may not promptly notify us of the fact.

But the main reason for the dialogue box that makes Brave go catatonic was to give _new users_ prompt feedback when we can't reach the Tor network the first time they try using Tor.

If, after you've been browsing and you've disconnected from the network, Brave doesn't go catatonic often enough, I don't really think that's a problem.  As you noticed, when you try to load a page, you'll still get a proxy timeout reasonably promptly.  So I'm inclined to close this issue as wontfix unless we have a particular reason to want to make sure Brave promptly goes catatonic when the network goes down.

Thoughts?

**Comment by kjozwiak** [comment]
@riastradh-brave sounds good 👍Both @srirambv and @LaurenWags also agreed with the above via Slack. As you mentioned above, I'm not sure if we want to go catatonic every time the network has been disconnected and a user has a Tor tab opened. They'll eventually get the timeout message (including regular tabs) which should be enough indication that the network has gone down. It also sounds like if we even do implement a fix, it won't always work.

Lets close this up.. We can always create a new issue or re-open if we get complaints from the community.
