### ISSUE TITLE
UX issues with password autocomplete

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1457]
- [ ] Email should not cover on top of the username field because it makes seeing what you are typing impossible if you want to enter something else.
- [x] You should be able to press escape for the password autocomplete to make it disappear.

CC @diracdeltas

**Comment by diracdeltas** [comment]
> Email should not cover on top of the username field because it makes seeing what you are typing impossible if you want to enter something else.

Do you have an example of a form where this happens?

**Comment by bbondy** [comment]
I think all forms I've used do this. docusign.com is an example though.

**Comment by bbondy** [comment]
![screenshot 2016-04-25 16 02 11](https://cloud.githubusercontent.com/assets/831718/14797137/1924ae0e-0aff-11e6-9490-172a04349f78.png)

**Comment by diracdeltas** [comment]
weird, this is what it looks like for me:
![screen shot 2016-04-25 at 1 02 35 pm](https://cloud.githubusercontent.com/assets/549654/14797166/0e6edee4-0ae6-11e6-9187-cd29d9c74eb3.png)

**Comment by diracdeltas** [comment]
nvm i think i know what the problem is
