### ISSUE TITLE
Button to restart tor that's always available

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14578]
Currently we have a button to restart the tor daemon, as a last resort, when it notifies us it can't connect to the network.  But in case anything else goes wrong, like tor gets wedged and fails to notify us for whatever reason (e.g., https://github.com/brave/browser-laptop/issues/14577), it should always be possible to give it a kick and try again.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1010
