### ISSUE TITLE
Unable to make online bus ticket payment through Brave Browser

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14572]
### Description
When user try to make online ticket payment through redbus.com, click on 'PAY INR' button is not functioning. Even after multiple clicks, button is not redirecting to payment gateway page. 

### Observations
Case 1. When 'PAY INR' button was not functioning the Shield settings are as below:
![image](https://user-images.githubusercontent.com/38657976/41972980-3542929c-7a31-11e8-856e-0d9affa74506.png)

Case 2. When i select 'Allow ads and Tracking' in shield. Click on 'PAY INR' works as expected.
![image](https://user-images.githubusercontent.com/38657976/41973093-9980abe0-7a31-11e8-8191-9f21837aa0d7.png)

In Case 1, the add which was blocked is captured as below. This might be causing the issue.
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

### Description
Unable to make online bus ticket payment through Brave Browser

### Steps to Reproduce

  1. Login to Redbus.com
  2. Make online ticket booking
  3. In payment information section, select net banking option and bank 
  4. Click on 'PAY INR'

**Actual result:**
Click on PAY INR is not functioning. Hence it's not redirecting to Payment gateway page
![unable to make online bus ticket payment through brave browser](https://user-images.githubusercontent.com/38657976/41973338-4f62a7f6-7a32-11e8-9ddb-21a8212c727b.gif)

**Expected result:**
Click on PAY INR should take user to payment gateway page

**Reproduces how often:**
100%

### Brave Version
0.23.19
**about:brave info:**
 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@GeetaSarvadnya can you check if this is resolved with [brave-core](https://github.com/brave/brave-browser)? If not, let's capture an issue there (labelled with `webcompat`) 😄
