### ISSUE TITLE
error en windos 7

### ISSUE THREAD

**Issue by javiertuerca** [brave/browser-laptop#14573]
Buenos tardes:
Estoy utilizando el navegador Brave en windows 7 Home Premium sp1,al instalar y configurar el programa funciona correctamente ,pero luego de un tiempo deja de funcionar .
El acceso directo del escritorio no funciona y no puedo abrir el navegador,descargo nuevamente los archivos de instalación ,lo ejecuto y me da error long.
intento desinstalar desde programas y características de windows y no se puede desinstalar ,intento con cmd con el comando wmic y no aparece listado,solo pude solucionarlo borrando la carpeta de brave ubicada en la subcarpeta roaming en windows c;.
vuelvo a instalar el navegador brave y se ejecuta bien nuevamente.
Si bien puedo recuperar mi wallet BAT con la copia de seguridad se borra todo mi historial de busqueda y sitios visitados , por lo tanto no puedo reclamar los token BAT.
Es la segunda vez que debo realizar todo esto y siempre el error coincide con la fecha de contribución mensual ,la próxima es el 26° de julio.
Como puedo solucionarlo?, si aun es compatible con windows 7 ya que el OS solo tendrá actualizaciones de seguridad hasta 2020.
Muchas gracias

**Comment by bsclifton** [comment]
@javiertuerca lo siento por no respondando mas rapido

Usted puede probar nuestro Developer channel build aqui:
https://brave.com/download-dev

Esto build no tiene un wallet... pero vamos a agregar este pronto

Gracias por su paciencia
