### ISSUE TITLE
Feature request: remove pages from history via the URL bar

### ISSUE THREAD

**Issue by snird** [brave/browser-laptop#1458]
**What:**
Removing a page from history by hovering (or marking with arrow keys) the page in the URL bar suggestions, and pressing the `DEL` key.

**Why:**
Sometimes, while writing in the URL bar, there is a page we want to remove from history.
This is common behavior in other browsers (Firefox, Chrome..)

I know the changes should be on the URL bar suggestions component: https://github.com/brave/browser-laptop/blob/master/js/components/urlBarSuggestions.js
But I couldn't find the code responsible for sites history, and try to make them talk. Can someone give me a pointer?

**Comment by luixxiul** [comment]
@bbondy please give him a hint :-)

**Comment by bbondy** [comment]
History items there are stored in the application state `sites` list. They are the items with no tags.
I think you'd need to implement `js/state/siteUtil`'s `removeSite` so when it is called with no tag, and it has no tags left, then it removes the site.

`appActions.removeSite` is what needs to be called.

**Comment by luixxiul** [comment]
I think this has been implemented. Correct me if I am wrong /cc: @bbondy

**Comment by bbondy** [comment]
yep we have this
