### ISSUE TITLE
setupTor should be called only once; polling for tor restart is broken

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14584]
### Test Plan
https://github.com/brave/browser-laptop/pull/14585

setupTor creates some resources (like a file system watcher) that there is no logic to destroy, and there should be no need to destroy in order to restart tor, but currently polling for tor restart is broken, so as a stop-gap measure, https://github.com/brave/browser-laptop/pull/14568 was written to call setupTor each time you ask to restart the tor daemon.

The polling logic should be fixed, obviating the need to call setupTor, and the resource leak arising from setupTor should be eliminated by not calling setupTor.

**Comment by riastradh-brave** [comment]
fixed in https://github.com/brave/browser-laptop/pull/14585

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.21 7240522
* Muon 7.1.4
* libchromiumcontent 67.0.3396.103

**Comment by srirambv** [comment]
QA blocked on windows because of  #14630

**Comment by btlechowski** [comment]
Blocked by #14630 on Linux

**Comment by riastradh-brave** [comment]
@srirambv @btlechowski #14630 might be fixed now!  Does that help?

**Comment by srirambv** [comment]
@riastradh-brave #14630 is not fixed yet. Still getting error when retry connection is clicked

**Comment by LaurenWags** [comment]
This is now broken on macOS as well - was working in a previous build.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
•	0.23.34 a47171894a26b74c84fdfc1f604c16144b36be52
•	Muon 7.1.6
•	libchromiumcontent 67.0.3396.103
