### ISSUE TITLE
CSS and font resources are shown in blocked scripts list in shields

### ISSUE THREAD

**Issue by yrliou** [brave/browser-laptop#14582]
### Description
Starting from C67.

### Steps to Reproduce
  1. Visit https://brianbondy.com/
  2. Turn on `Block Scripts` in shields

**Actual result:**
Our current result starting from C67.
<img width="503" alt="bl-c67-script-blocked-list" src="https://user-images.githubusercontent.com/4730197/41993555-bdb503ac-7a00-11e8-96c7-20a7f1579443.png">

**Expected result:**
Our result before on C66
![bl-c66-script-blocked-list](https://user-images.githubusercontent.com/4730197/41993571-c6407d8a-7a00-11e8-8b3d-72d1813a362f.png)

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
Brave: 0.22.810 
V8: 6.7.288.43 
rev: 8f30eeba0c2d6cccf1920a360b4774f820adbc58 
Muon: 7.0.6 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.71

**Reproducible on current live release:**
Yes

**Comment by BrendanEich** [comment]
Chromium upgrade changed how an API callback is invoked? Cc: @darkdh

**Comment by darkdh** [comment]
I have a fix, stay tuned. I'm going to open a PR.

**Comment by kjozwiak** [comment]
Currently not merged into `muon: 7.1.5`. Requires `muon: 7.1.6`.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
•	0.23.34 a47171894a26b74c84fdfc1f604c16144b36be52
•	Muon 7.1.6
•	libchromiumcontent 67.0.3396.103
Note: The below two scripts are blocked
https://brianbondy.com/js/bundle.js
https://brianbondy.com/js/analytics.js
