### ISSUE TITLE
Feature: Ability to change tor ports

### ISSUE THREAD

**Issue by kirkins** [brave/browser-laptop#14594]
Have a friend using Brave in Turkey. He's having problems connecting to the tor network on Brave:

![photo_2018-06-28_14-15-52](https://user-images.githubusercontent.com/9503662/42052812-d00eba24-7add-11e8-8cff-c9b8bd8c86a2.jpg)

I'm thinking maybe his ISP is blocking ports 9001 and 9030 used by tor. [Tor FAQ](https://www.torproject.org/docs/faq.html.en#FirewallPorts) offers this solution of just using standard ports 80 and 443 in that situation:

> My firewall only allows a few outgoing ports.
> If your firewall works by blocking ports, then you can tell Tor to only use the ports when you start your Tor Browser. Or you can add the ports that your firewall permits by adding "FascistFirewall 1" to your torrc configuration file. By default, when you set this Tor assumes that your firewall allows only port 80 and port 443 (HTTP and HTTPS respectively). You can select a different set of ports with the FirewallPorts torrc option.
> 
> If you want to be more fine-grained with your controls, you can also use the ReachableAddresses config options, e.g.:
> 
>   ReachableDirAddresses *:80
>   ReachableORAddresses *:443

Would it be possible to add some text boxes to input ports to be used in the advanced settings section?

**Comment by srirambv** [comment]
cc: @diracdeltas @riastradh-brave

**Comment by riastradh-brave** [comment]
Unfortunately, this is not currently possible.  In the future, we plan to support custom configuration like bridges (https://github.com/brave/browser-laptop/issues/12989) for people who are on censored networks.

It might be worthwhile in the meantime for your friend to try the Tor Browser, which does support configuring bridges and custom torrc files, and see if they can find a way to reach the Tor network with that.

**Comment by kirkins** [comment]
@riastradh-brave thanks will close since issue is already covered in #12989
