### ISSUE TITLE
localhost not defaulting to 127.0.0.1

### ISSUE THREAD

**Issue by hassanshaikley** [brave/browser-laptop#1459]

**Comment by skeep** [comment]
I also confirm it.

**Comment by hassanshaikley** [comment]
I don't mind fixing it if given advice about how to implement it. Do we want a table associated with redirects? Or a seperate entry in entry.js.

**Comment by bbondy** [comment]
localhost does resolve properly we just aren't recognizing it as a host name, if you prepend http:// it will work.  We need to fix the url handling detection

**Comment by kenorb** [comment]
Adding `/` at the end helps, e.g. typing `localhost/`.

**Comment by bridiver** [comment]
I think the actual problem here is that localhost is not being correctly interpreted as a url. When I type localhost:8080 it is incorrectly recognized as an external protocol. http://localhost:8080 works correctly.

**Comment by bridiver** [comment]
Missed @bbondy's comment that explained the same thing, but we should look at the external protocol issue with the port as well. Definitely an issue with out url detection in general
