### ISSUE TITLE
saved window state doesn't remember window size/position

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#146]
Steps to reproduce
1. Resize and move the window
2. Quit the app
3. Start the app again
Window will be restored to default size and position

**Comment by bbondy** [comment]
Also it should preserve the window state (maximized, ...)

**Comment by jmcilhargey1** [comment]
Windows 10 does not remember which monitor the application was closed on.

**Comment by luixxiul** [comment]
It seems that window size is preserved.

**Comment by jmcilhargey1** [comment]
Size yes, location no. If I move it to another monitor it does not reopen there.

James McIlhargey
IT Director
jmcilhargey@thenaz.tv | 614-875-2551

The Naz | Grove City Church of the Nazarene
4770 Hoover Road
Grove City, OH 43123
www.thenaz.tv<http://www.thenaz.tv/>
[cid:983B447C-F1C7-41D5-91F4-DB71B94E35DC]
