### ISSUE TITLE
No CSD support for Linux!

### ISSUE THREAD

**Issue by alchehabi** [brave/browser-laptop#14602]
as long as Brave has a CSD support in both windows os and mac os, it would be lovely to see this feature landing in linux world.
I really hope to take this point in consideration. Big THANKS to all of the team!

**Comment by bsclifton** [comment]
@alchehabi do you have more information about this? What exactly is CSD?

**Comment by ExitSec** [comment]
I think @alchehabi is referring to client side decorations e.g. gnome styling for the browser. It makes the user feel that the  browser is seamlessly integrated into the chosen OS.

**Comment by bsclifton** [comment]
This issue should be addressed with our new Developer channel build, available here:
https://brave.com/download-dev

If that link doesn't work on Linux, you can try downloading the rpm/deb packages from here:
https://github.com/brave/brave-browser/releases/tag/v0.55.1
