### ISSUE TITLE
Default fallback icon needs refinement

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14607]
### Description
Default fallback icon needs refinement

### Steps to Reproduce
  1. Based on conversation from https://bravesoftware.slack.com/archives/C07HD31EZ/p1529336218000679
  2. Also reported on community https://community.brave.com/t/whats-with-the-saturn-iconography-since-the-last-update/26465
  3.

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/42111644-1884d060-7bb3-11e8-847b-f812b48ac714.png)

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Closing as `wontfix`; let's re-open if needed in [brave-core](https://github.com/brave/brave-browser)
