### ISSUE TITLE
Move adblock-data s3 bucket to fastly

### ISSUE THREAD

**Issue by RyanJarv** [brave/browser-laptop#14608]
## Test plan
1. Close Brave
2. Clear out .dat files in your profile directory 
3. Start brave, make sure it grabs the new .dat files and they appear in your profile directory again.
4. Make sure regional lists still get downloaded if enabled.

## Original issue description
This was done in master with the PR at https://github.com/brave/browser-laptop/pull/14254/files, however S3 is expensive and I should have set a milestone on it to get that released sooner.

Creating this ticket to have that pulled into the next release.

**Comment by NejcZdovc** [comment]
Can this issue be closed based on https://github.com/brave/browser-laptop/pull/14254? Also here we set it to 0.23 release 2 but in PR there is 0.24?
which one should we do @petemill @RyanJarv ?

**Comment by bsclifton** [comment]
@NejcZdovc this is already merged to master / 0.24.x. I'll cherry-pick this into 0.23.x here in a moment...

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/02daa073f01c15d6981a9e84b508c431e602a7e1

@RyanJarv do you mind adding some test steps for this? ex: once we have a build ready, how can we confirm (from your side) that we're hitting the CDN?

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.21 - 7240522
* Muon - `7.1.4`
* libchromiumcontent - `67.0.3396.103`

**Comment by petemill** [comment]
Reverted via https://github.com/brave/browser-laptop/pull/14746 for reasons mentioned there.

**Comment by bbondy** [comment]
Turns out this was my bad, I thought etags weren't being returned and they are.  This is ok. 🤦‍♂️

**Comment by kjozwiak** [comment]
Re-adding the `QA/Checked` tags as per https://github.com/brave/browser-laptop/issues/14608#issuecomment-405308776. Since this has already beed tested with `0.23.37`, there's no need to re-check it.
