### ISSUE TITLE
is2.4chan.org Resources Blocked on 4chan.org

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14610]
### Description
Resources being loaded from is2.4chan.org are blocked on 4chan.org. This issue was originally [shared with us](https://twitter.com/georgiegirl1828/status/1012826524817510400) via Twitter. Upon resolution, please contact the user to inform them of the updated status.

### Steps to Reproduce
1. Navigate to https://boards.4chan.org/pol/thread/176949539 (note, content may be objectionable)
2. Click a thumbnail image to increase size

**Actual result:**
No image is shown.

**Expected result:**
Larger image should be displayed.

**Reproduces how often:**
Always.

### Brave Version (about:brave info):
```
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87
```

**Reproducible on current live release:**
Yes.

### Additional Information

![f696dcbe-a71c-4acf-8b04-de4b6f810338](https://user-images.githubusercontent.com/815158/42120781-d685e292-7be6-11e8-8fac-79b01b4a6165.gif)

**Comment by snyderp** [comment]
I'm not able to recreate, possibly b/c 4chan has centralized on i.4chan.org for images (or, at least I'm not able to find a is2.4chan.org reference on the boards i browsed through

testing on beta
