### ISSUE TITLE
stats ref codes should not be sent at startup

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#14615]
### Description

ledger.js has code for the refcodes to be sent up right away on startup.
We should be avoiding File IO and network requests at startup time in favour of waiting after some initial delay and/or by lazy loading. 

In this case, this should instead happen when normal checks happen, see 
`runtimeUpdateCheckDelay`

### Steps to Reproduce

  1. Add console.log logging to app/browser/api/ledger.js
  2.Start the browser
  3. Observe output at startup time

**Actual result:**
Network requests happens at startup

**Expected result:**
Network request shouldn't happen directly at startup.

**Reproduces how often:**
Always

### Brave Version
0.23.19 

**about:brave info:**
 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
Yes

**Comment by srirambv** [comment]
@ryanml any verification steps required for this? If not please mark it as `no-qa-needed`

**Comment by LaurenWags** [comment]
Verified with macOS 10.13 (@kjozwiak ) and 10.12.6 (@laurenwags) using
* 0.23.73 50bdb6d
* Muon 8.0.3
* libchromiumcontent 68.0.3440.75

**Comment by kjozwiak** [comment]
QA wasn't seeing the calls logged within the terminal as per the STR so @ryanml helped debug the issue and created https://github.com/brave/browser-laptop/issues/14874. The `promoCode` is correctly being removed as expected but the calls are not being logged in the terminal.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.73 50bdb6df42550dd14f5636770ec8585aa26e361b
• Muon 8.0.3
• libchromiumcontent 68.0.3440.75

Verified the promoCode file delete after startup. The above comment mentioned by @kjozwiak is applicable for Windows as well.
