### ISSUE TITLE
Select HTML element after search

### ISSUE THREAD

**Issue by raulpardo** [brave/browser-laptop#14629]
I miss the functionality from most web browsers of being able to select HTML elements by searching for them (Ctrl+f). For instance, it is quite handy being able search for "Log in" in a website and hit enter to click on the log in button, or search for the result of a search engine that you would like to open.

**Comment by bsclifton** [comment]
I've confirmed this is fixed with our [developer channel](https://brave.com/download-dev) build. Basically, after searching you have to hit ESC, but the selected item will remain highlighted and you can press enter (and it works as expected)
