### ISSUE TITLE
Potential Malware?

### ISSUE THREAD

**Issue by illuzen** [brave/browser-laptop#14622]
Unfortunately I am a little sparse on details of how this happened, but here are the essentials. A few days ago I was prompted to download a Brave update, which I did. Then yesterday I noticed that Brave was using a lot of power and I was on a plane, so I closed it. Immediately I got notifications from my firewall that Brave was trying to access a long list of IPs from tor. I also saw in Activity Monitor that the Brave process was still visible, but greyed out. I am on OSX 10.12.6 using Brave v0.23.19.  Here is the list of IPs:

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 185.100.84.212
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 185.100.84.212. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 204.13.164.118
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 204.13.164.118. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 149.56.141.138
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 149.56.141.138. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 199.58.81.140
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 199.58.81.140. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 5.189.169.190
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 5.189.169.190. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 199.249.223.74
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 199.249.223.74. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 163.172.53.84
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 163.172.53.84. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 128.31.0.39
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 128.31.0.39. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 171.25.193.78
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 171.25.193.78. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 163.172.13.165
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 163.172.13.165. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 5.39.92.199
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 5.39.92.199. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 193.23.244.244
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 193.23.244.244. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 154.35.175.225
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 154.35.175.225. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 81.7.14.253
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 81.7.14.253. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 171.25.193.9
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 171.25.193.9. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 86.59.21.38
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 86.59.21.38. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 199.249.223.69
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 199.249.223.69. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 131.188.40.189
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 131.188.40.189. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 193.11.114.43
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 193.11.114.43. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
via: /Applications/Brave.app/Contents/Resources/extensions/bin/tor
code-signature: ignore
owner: me
destination: 199.249.223.66
port: any
protocol: any
notes: On Jun 29, 2018, Brave via tor tried to establish a connection to 199.249.223.66. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
owner: me
destination: 151.101.114.49
port: any
protocol: any
notes: On Jun 26, 2018, Brave tried to establish a connection to 151.101.114.49. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
owner: me
destination: 151.101.190.49
port: any
protocol: any
notes: On Jun 19, 2018, Brave tried to establish a connection to 151.101.190.49. The request was denied via connection alert.

action: deny
direction: outgoing
priority: regular
process: /Applications/Brave.app/Contents/MacOS/Brave
owner: me
destination: 151.101.78.49
port: any
protocol: any
notes: On May 14, 2018, Brave tried to establish a connection to 151.101.78.49. The request was denied via connection alert.

**Comment by bsclifton** [comment]
cc: @riastradh-brave @diracdeltas

**Comment by riastradh-brave** [comment]
This is Brave trying to connect to the Tor network.  We will be changing it to do that only if you open a private tab with Tor in the next release:

https://github.com/brave/browser-laptop/issues/14617

**Comment by illuzen** [comment]
Ok yeah it sounds like it was a probably a false positive, then. It seemed too much like an accident to be professional malware in retrospect. Also, Brave wouldn't reopen after this happened, so I reinstalled it.

**Comment by Giacarta** [comment]
So is this really a false positive? Why it was classified as a ramsomware? Hope that the Tor network is secure.

**Comment by illuzen** [comment]
@Giacarta It probably has a rule "if something opens a tor process and starts using it, it is probably malware." Maybe it whitelists certain applications which are known to use tor and Brave isn't on that list yet. Just guessing here.

The tor network is the wild west. It is known that there are both friendly and malicious nodes on the network, but the proportions of each are not known. If your computer isn't locked down and demanding cryptocurrency, you either don't have ransomware or the ransomware is not working correctly. In any case, you should do regular backups to diminish the effect of ransomware and other disasters.

**Comment by riastradh-brave** [comment]
The Tor network is an anonymity network.  Among other things, it prevents your ISP form distinguishing whether you are a teenager looking for information about safe sex without alerting your parents, a journalist researching a subject without alerting a powerful person, an NGO researching corruption without alerting the corrupt government, a trans person purchasing hormone treatments from a pharmacy when you can't get them locally, a ransomware program talking to the control server, or a bored worker at an office reading reddit when reading reddit is against your company's policy.

We added support for using the Tor network in Brave so that private browsing mode could actually keep your browsing private from your ISP, and keep you anonymous to the web server, as an overwhelming majority of users seem to expect 'private browsing' does.  The information here is only evidence of connecting to the Tor network, which is to be expected in Brave 0.23.19, not _a priori_ evidence of ransomware or other malware.

Unfortunately, some network administrators insist on being able to monitor everyone's browsing, so Tor doesn't sit well with them.  And some ransomware may have used the Tor network out of convenience, even though ransomware operators -- being by definition willing to commit extortion, breaking laws and hurting people -- have even better options for anonymity available to them by renting stolen computer time and bandwidth on a botnet.

Since this is preventing some people from using Brave, we have decided that in the next release, we won't connect to the Tor network by default on startup unless, e.g., you ask to open a private tab with Tor: https://github.com/brave/browser-laptop/issues/14617

**Comment by bsclifton** [comment]
As @riastradh-brave mentions, we shipped the fix for https://github.com/brave/browser-laptop/issues/14617 (done with https://github.com/brave/browser-laptop/pull/14668) and now tor only loads when you open a tab explicitly with Tor 😄 

I'm going to close this issue as I believe the concern has been resolved. Please re-open if you still experience an issue 😄
