### ISSUE TITLE
Set search engine to Google, Brave keeps using DDG.

### ISSUE THREAD

**Issue by gdrdr123** [brave/browser-laptop#1462]
Hi guys!

So I just installed 0.9.2. I set my search engine to Google but Brave keeps using DDG. I noticed that my settings from previous version applies. Might have something to do with how uninstalled Brave? I'm using Linux Mint and I just right clicked on the start menu and chose uninstall. Perhaps that's not a proper way of uninstalling? 

Thanks!

**Comment by bbondy** [comment]
Are all settings not saving?

**Comment by gdrdr123** [comment]
I don't know. You just leave the settings after you configure them right? No save button to click or whatever. What I did notice was the same settings were there from the previous Brave Browser I had. I wonder if me using Linux Mint and uninstalling Brave from the menu launcher has anything to do with this issue. I think when uninstalling from the menu launcher - right-click on the app -> choose Uninstall -> it doesn't completely uninstall an app. And I think that's the problem here? I don't know. There was a pop-up that appeared though when I was uninstalling it. It could be that it was asking me if I'm sure I want to uninstall, or may be something like a reminder that I am not really completely uninstalling the app.

**Comment by bbondy** [comment]
> I don't know. You just leave the settings after you configure them right? No save button to click or whatever.

Should be auto saving (at least it does for most)

I'm wondering if the browser is not shutting down completely maybe and there's a process left behind.

**Comment by luixxiul** [comment]
Closing this for the moment. Notify us if this error still persists.
