### ISSUE TITLE
Getting Tor connection error while Brave is connected to the network

### ISSUE THREAD

**Issue by mrphs** [brave/browser-laptop#14623]
### Description
I hit this annoying issue today where I opened my laptop to resume some work and kept getting "unable to connect to Tor network" popup error on my Tor-enabled tabs. At first I figured maybe Tor hasn't had enough time to reconnect to the network, so I clicked on "disable Tor" button as it was the only way to make the pop-up stop from reappearing. Opened a new tab and enabled Tor again, watched Tor bootstrap in the URL bar and then started browsing again only to have the error pop ups return after a few.

Not sure what is triggering the error or how to debug it but the only work around seems to be quitting and re-opening the browser.

Another weird thing I noticed while writing this report is that every time I hit "retry connection" button, it does successfully bootstrap Tor. At least according to the URL bar message.

### Steps to Reproduce

  1. Open a new private tab and enable Tor.
  2. Disconnect from network while the tab is still open (ie close the laptop).
  3. Reconnect to a network after a while (>15mins)

**Actual result:**

Getting 2 con "Unable to connect to the Tor network" error every 30 seconds or so on the Tor-enabled tabs and while being able to browser over Tor.

Here you can see that I'm connected to the Tor network and browse but am still getting the error.

<img width="731" alt="screenshot" src="https://user-images.githubusercontent.com/453701/42132574-8399bbb4-7ce8-11e8-9d04-f191c2a73e62.png">

**Expected result:**

- Not getting this error while Tor is connected to the the network. 
- Be able to dismiss the warning/error.
- Have a way of accessing the Tor log to debug.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.19
V8 | 6.7.288.46
rev | 178c3fb
Muon | 7.1.3
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

**Reproducible on current live release:**

Not sure what "live build" is here, but this is reproducible on the latest stable version.

**Comment by moneykicks007** [comment]
I'm also having the same issue

**Comment by riastradh-brave** [comment]
Can you share your tor.log?

If this is macOS, it's in ~/Library/Application Support/brave/tor/data/tor.log.

**Comment by riastradh-brave** [comment]
As an aside, I opened an issue for the problem of making it more obvious how to get at tor.log: https://github.com/brave/browser-laptop/issues/14644

**Comment by moneykicks007** [comment]
[tor.log](https://github.com/brave/browser-laptop/files/2161970/tor.log)

Here it is

**Comment by riastradh-brave** [comment]
Thanks.  It is possible that https://github.com/brave/browser-laptop/pull/14599 will fix this once it is ready.

**Comment by riastradh-brave** [comment]
@mrphs Can you tell me if this is still happening?

**Comment by riastradh-brave** [comment]
A candidate fix, #14599, may fix this in the next 0.23.x release.  When that comes out, please let me know if it's still reproducible!

**Comment by alexwykoff** [comment]
@mrphs This should be fixed in the next release. Please let us know if you still see issues after updating. Thanks!

**Comment by SurenaSKQ** [comment]
This issue still happens for me on Brave 0.23.105. The option to retry connection doesnt work (the button has no effect).
