### ISSUE TITLE
Disable "Always ask me where to save files" still ask user and open Save As dialogue

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#14625]
## Test plan
See https://github.com/brave/muon/pull/630

### Description

Reported via Twitter https://twitter.com/djSTICKYBUDS/status/1013481022174818304

Disabling "Always ask me where to save files" still open Save As dialogue. When this setting disabled, it should download the files without opening Save As dialogue. Stopped working with latest release 0.23.19.

### Steps to Reproduce

  1. Disable "Always ask me where to save files" at Preferences > General
  2. Open any site, try to save or download files
  3. Brave open Save As dialogue

**Actual result:**

Brave open Save As dialogue

**Expected result:**
Brave should download the files without opening Save As dialogue. File should be downloaded to download path that set by user or to Downloads folder.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**

Yes

### Additional Information

cc @LaurenWags @srirambv

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/bad-bug-concerning-the-location-of-where-files-are-supposed-to-be-saved/26810/2

**Comment by LaurenWags** [comment]
Reproduced on macOS using 0.23.19

**Comment by Brave-Matt** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8v6wld/brave_always_asks_me_to_save_any_file_with_a/

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/voxtis/status/1014232259996422144

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/downloads-asking-location-every-time/27062/2

**Comment by eljuno** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8x4flc/turning_off_always_ask_where_to_save_files_doesnt/

**Comment by bsclifton** [comment]
@jumde @darkdh I suspect this is related to the safe browsing changes. Would either of you be able to look at this?

**Comment by bbondy** [comment]
@jumde since this won't be turned on in muon before brave-core comes out, let's just backout of muon please. Thanks!

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.70 e63c7804ea4850229904d4dc991143e1ebeabb51
• Muon 8.0.1
• libchromiumcontent: 68.0.3440.68
