### ISSUE TITLE
Brave opens as black window

### ISSUE THREAD

**Issue by GrzesiekP** [brave/browser-laptop#14639]
### Description
After updating windows to Windows 10 Fall Creators Update, Brave has stopped working. It opens, but only black windows is seen. The same happens when trying to reinstall. After brave software installing... window, black screen again

### Steps to Reproduce
  1. Open Brave Browser
  2.
  3.

**Actual result:**
Window is black with white fragments, when clicked or moved.

**Expected result:**
Window open with UI displayed.

**Reproduces how often:**
Always

### Brave Version

**about:brave info:**
unable to open about. In install directory there is app-0.23.19

**Reproducible on current live release:**
Downloaded from https://brave.com/download/

### Additional Information
Windows 1- Enterprise 64-bit
Lenovo 20EQS27Q00
Inter Core i7-6820Q

**Comment by Tomatoshadow2** [comment]
Please also post your Brave version from the about:Brave page and also what operating system you are using.

**Comment by srirambv** [comment]
@GrzesiekP please edit the issue and fill out the sections. The issue doesn't give any useful information to troubleshoot.

**Comment by GrzesiekP** [comment]
Sorry, I forgot to delete comments. Info updated.
