### ISSUE TITLE
Tor control socket error when network is disconnected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14630]
### Description
Tor control socket error when network is disconnected. Found while testing https://github.com/brave/browser-laptop/pull/14585

### Test plan / Steps to Reproduce

  1. Disconnect from network
  2. Launch brave beta from console and open a tor tab
  3. Console logs error 

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/42176910-981571a8-7df8-11e8-835d-cbb399ed005f.png)

**Expected result:**
Should not encounter socket error 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave	0.23.21
V8	6.7.288.46
rev	7240522
Muon	7.1.4
OS Release	10.0.17134
Update Channel	Beta
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Tor	0.3.3.7 (git-035a35178c92da94)
Brave Sync	v1.4.2
libchromiumcontent	67.0.3396.103

**Reproducible on current live release:**
Maybe

**Comment by riastradh-brave** [comment]
Also, can you share ${BRAVE}/tor/data/tor.log?  (~/.config/brave/tor/data/tor.log on Linux, %appdata%\brave\tor\data\tor.log on Windows, substituting brave-development or brave-beta for brave if a nonstandard channel.)

**Comment by btlechowski** [comment]
Ubuntu 17.10 x64, Brave v0.23.21
```
tor: control socket error: Error: read ECONNRESET
tor: authentication failure: Error: read ECONNRESET
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: this._control.close is not a function
    at TorDaemon.kill (/usr/lib/brave-beta/resources/app.asar/app/tor.js:164:21)
    at _control.cmd1 (/usr/lib/brave-beta/resources/app.asar/app/tor.js:512:16)
    at TorControl.destroy (/usr/lib/brave-beta/resources/app.asar/app/tor.js:897:7)
    at TorDaemon._controlError (/usr/lib/brave-beta/resources/app.asar/app/tor.js:546:19)
    at TorControl._control.on (/usr/lib/brave-beta/resources/app.asar/app/tor.js:494:47)
    at emitOne (events.js:96:13)
    at TorControl.emit (events.js:191:7)
    at TorControl._onError (/usr/lib/brave-beta/resources/app.asar/app/tor.js:1058:10)
    at emitOne (events.js:96:13)
    at LineReadable.emit (events.js:191:7)
```
[tor.log](https://github.com/brave/browser-laptop/files/2156441/tor.log)

**Comment by srirambv** [comment]
Even after connecting back to network, still doesn't connect to Tor and opening a new Tor tab doesn't show the retry/disable popup . The only option is to restart browser to connect again to Tor

**Comment by bsclifton** [comment]
re-opening so that @riastradh-brave can add additional fix per @diracdeltas feedback:
https://github.com/brave/browser-laptop/pull/14675#issuecomment-403163877

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
•	0.23.34 a47171894a26b74c84fdfc1f604c16144b36be52
•	Muon 7.1.6
•	libchromiumcontent 67.0.3396.103
