### ISSUE TITLE
Brave Browser and metamask

### ISSUE THREAD

**Issue by Bella35** [brave/browser-laptop#14635]
Brave Desktop browser. with metamask
Okay. I have been having issues with the brave browser it is uninstalled I have the apps\roaming brave folder on my desktop and deleted every instances of Brave from my computer. I also backed up the wallet on June 12,2018 it gave me 24 seed words for the backup I also, have the original seed words which are 12 I put metamask on chrome and clicked import It asked for the 12 seed words and new password well guess what no crypto in the account. so I logged out I have the file form the backup but it wont take it. Really this is B.S.! I really liked the brave browser I don't know what happen to it. It wont re-install now either I am even having the same issues with opera it opens and loads and than closes about 10-15 sec later. Can anyone tell me what is going on with these browsers even in brave it wouldn't let me sign in it just prompted me later to do the back up. And no I haven't be dabbling in places where I use a VPN and tor. Please help or send me to some one who knows.

Thanks a lot
Bella52

And yes I have sifted through the other post and issues.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by Bella35** [comment]
I didn't take a screenshot of the metamask shaking and would let me sign in. the browser was working fine on the 20th of June but not metatmask. then the browser just kept closing it would load then closed 10-15 sec later so I uninstalled it.

Tanks 
Bella35

**Comment by Tomatoshadow2** [comment]
Please also post your Brave version from the about:Brave page and also what operating system you are using.

**Comment by Bella35** [comment]
OS is windows 7 home premium 64 service pack 1 bit Os 8GB ram and 1TB.  Brave I uninstalled it and removed everything I got the fold out of the user app data roaming. I downloaded it March 14, 2018, the version I found in the folder says 1.19.1 If this is not the version I have a .PNG of the contents in the brave file I copied and moved out of roaming

![brave](https://user-images.githubusercontent.com/36716090/42232449-6fa5c8e8-7ebc-11e8-9336-94c26f9289b1.PNG)

Thanks 

Bella35
