### ISSUE TITLE
Feature request: Persistence Tor-mode option on private tabs

### ISSUE THREAD

**Issue by mrphs** [brave/browser-laptop#14637]
### Description
I've been using Brave + Tor for only a couple of days and I already find it tiring to enable Tor-mode for every time I open a new private tab. More importantly, I sometimes forget about turning it on, only to find out when it's already too late.

Having a check box under the Tor mode toggle button that remembers my choice would be super duper!

### Brave Version

Name | Version
-- | --
Brave | 0.23.19
V8 | 6.7.288.46
rev | 178c3fb
Muon | 7.1.3
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

**Comment by srirambv** [comment]
There's a context menu option to open Tor tabs directly on the new tab button. You can right click and open Tor tab. The same option is available via file menu and on kabob menu as well. Does that help?

**Comment by riastradh-brave** [comment]
Our initial draft did have a persistent Tor setting for all private tabs.  We changed it a few weeks ago so that users would have greater control over whether they would have Tor or not in each tab.  In the short term, we plan to add a keyboard shortcut: https://github.com/brave/browser-laptop/issues/14504  In the longer term, the UX desgin for all this is still in flux!

**Comment by NumDeP** [comment]
Hi @riastradh-brave don't you moving the 'Support jump lists' #6094 issue forward to include the new Tor feature would be more ideal?

In addition, this way when a user makes his/her first attempt to connecting to Tor they could do so without any leak (hopefully), where as as manually opening the browser from icon in start/desktop menu would connect to local internet not to mention waste time, however little it may be, then waiting for it to connect to Tor, slightly inefficient, isn't it. It would be brilliant if Brave were to open Tor literally from startup like the traditional Firefox-Tor.

**Comment by riastradh-brave** [comment]
Also FYI: https://github.com/brave/browser-laptop/issues/14649

**Comment by riastradh-brave** [comment]
@NumDeP As of 0.23.31, Brave makes no attempt to connect to the Tor network until you open a private tab with Tor.  https://github.com/brave/browser-laptop/issues/14617

**Comment by hugobuddel** [comment]
It would also be nice to have Ctrl-T open a Tor-tab when already on a Tor-tab. (And perhaps the same for private tabs.) Or a keyboard shortcut to open Tor-tabs directly.

**Comment by NumDeP** [comment]
@riastradh-brave I aware of 'Lazy load Tor instead...' :) which is why I thought it may be better for those some individuals that it benefits and prefer it loading on startup to still have the ability to do so from the jump-list. 
I don't know whose complaining about startup, I'm using it Linux and honestly speaking, you lot have done a brilliant job so far.

**Comment by riastradh-brave** [comment]
In the next release, we will have a keyboard shortcut for opening a tab with Tor: https://github.com/brave/browser-laptop/issues/14504.  We're also changing the shortcut for opening a private tab to be closer to Chromium: https://github.com/brave/browser-laptop/pull/14711.  Specifically:

- macOS: cmd-shift-n for private tab, cmd-opt-n for private tab with Tor
- Others: ctrl-shfit-n for private tab, ctrl-alt-n for private tab with Tor

For the longer-term, we are still exploring the design space of how Tor fits into Brave: https://github.com/brave/browser-laptop/issues/14649

@mrphs Does this help?

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/690
