### ISSUE TITLE
AMD64 deb reports version 0.8.3

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#1463]
Downloaded the deb brave_0.9.2_amd64.deb and did Help/About

Get the following

> Brave: 0.8.3
> Electron: 0.37.3
> libchromiumcontent: 49.0.2623.108
> V8: 4.9.385.33
> Node.js: 6.0.0-pre
> Update channel: dev
> 
> This software uses libraries from the FFmpeg project under the LGPLv2.1

Other indications suggest that this really is 0.9.2, just the version reported is wrong

**Comment by luixxiul** [comment]
This has been fixed on 0.9.6. Thanks for reporting.

![](http://i.imgur.com/1adeDrl.jpg)
