### ISSUE TITLE
Progress indicator should report first-time Tor startup

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14646]
The first time Tor starts up (in particular, when ~/.config/brave/tor/data is not populated with state about the Tor network -- whether it is the first time Brave is connecting, or whether someone has nuked that directory), it takes longer to connect to the network than subsequent times.  So we should give some visual indicator of that fact.

**Comment by diracdeltas** [comment]
cc @rossmoody for design feedback

**Comment by tomlowenthal** [comment]
I'm calling this one stale for now, but it'd fine to re-open it in the new codebase if first-time-start takes noticeably longer.
