### ISSUE TITLE
Provide an easy way to get at tor.log

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14644]
The tor.log file is documented at https://github.com/brave/browser-laptop/wiki/Filesystem-Hierarchy, but it is often the first thing that we want in order to diagnose problems with Tor.  We should make it easier to get at.

**Comment by diracdeltas** [comment]
cc @rossmoody for design ideas

**Comment by flamsmark** [comment]
Closing in favor of brave/brave-browser#510.
