### ISSUE TITLE
Browser display goes partially white

### ISSUE THREAD

**Issue by Tomatoshadow2** [brave/browser-laptop#14640]
https://community.brave.com/t/the-interface-goes-white-and-parts-of-the-web-view-are-whited-out-on-hover/26905

**Comment by bsclifton** [comment]
Comment left in community- since there isn't enough actionable info here to dig into, I'll close this issue out

**Comment by stephband** [comment]
Oh sorry, I didn't see these updates until now. Shortly after I filed that bug my laptop died and I now have a new one – I haven't seen this issue again and can't give more info :/ Thanks for your help, though.
