### ISSUE TITLE
Bookmarks not saving

### ISSUE THREAD

**Issue by mrkimo1998** [brave/browser-laptop#1464]
If i make a new bookmark in Brave, it is there and works fine, but if I then restart brave it's not there anymore. Importing an exported Bookmarklist from Firefox works however.

[I'm using Brave 0.9.2 from the AUR on Manjaro i3 15.12 with the latest packages as of today]

**Comment by luixxiul** [comment]
Close this for the moment. If you see this after updating to the latest version too, please tell me and I will reopen this. Thanks.
