### ISSUE TITLE
[hackerone] local files

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14642]
https://hackerone.com/bugs?subject=brave&report_id=375329

**Comment by diracdeltas** [comment]
This is a regression of https://github.com/brave/browser-laptop/issues/4906

**Comment by Metnew** [comment]
That's not a regression of #4906. #4906 relies on SOP, this bug relies on CORS.
Probably, the problem is [somewhere here](https://github.com/brave/muon/blob/master/atom/browser/net/asar/url_request_asar_job.cc) 😉 

> Not sure is it ok to provide more info in the public tracker

**Comment by diracdeltas** [comment]
@Metnew thanks for the info :)

looks like the vulnerable code is also in https://github.com/electron/electron; you might be able to get a bounty from them too

**Comment by Metnew** [comment]
Cool, but does Electron have a bug bounty? I didn't know that, thanks)

**Comment by srirambv** [comment]
@darkdh mind adding the test steps for the issue for verification

**Comment by darkdh** [comment]
Will DM you the detail since this is the security issue

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.70 e63c780
* Muon `8.0.1`
* libchromiumcontent `68.0.3440.68`

![image](https://user-images.githubusercontent.com/34715963/43151649-b91734ba-8f6c-11e8-92e3-0ebf8604bb48.png)
