### ISSUE TITLE
Incorrect rendering

### ISSUE THREAD

**Issue by kika** [brave/browser-laptop#1465]
https://vuejs.org/examples/commits.html
shows three instances of this example menu, while Chrome (and other browsers) show the list of commits as supposed. Other examples do not work the same way.
OS X 10.11.4 latest Brave

**Comment by luixxiul** [comment]
Confirmed. After allowing scripts until restart,

![](https://cloud.githubusercontent.com/assets/3362943/15271656/ae07ed6c-1a8e-11e6-9022-f4703f25937b.jpg)

CC'ing @bbondy @diracdeltas

**Comment by diracdeltas** [comment]
works after unchecking 'block 3rd party cookies'. it also works with 3p cookies blocked in chrome so i think this is a referer problem.

**Comment by luixxiul** [comment]
> i think this is a referer problem.

is this related with #902?
