### ISSUE TITLE
search icon in URLbar should be a local resource

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14653]
we discovered while running wireshark on Tor tabs that the search icon in the urlbar (google, duckduckgo) is loaded remotely when the user starts a search from the urlbar. for privacy it's best to load it as a local resource.

STR:
open browser console and inspect the urlbar icon
hit any search shortcut, ex: ':g' for google
notice that the favicon for the search engine is loaded from a remote website

**Comment by srirambv** [comment]
This is breaking the local images 

![14653](https://user-images.githubusercontent.com/17010094/42517470-c5e616ce-842d-11e8-9890-16430c136403.gif)

**Comment by diracdeltas** [comment]
i tested it on mac so may be a windows specific issue breakage

**Comment by alexwykoff** [comment]
We'll need to test this with a large profile per @kjozwiak

**Comment by LaurenWags** [comment]
Verified icons using engine go key (from about:preferences#search), all seemed to load fine except for searx (:x). Reproduced by @srirambv 
![screen shot 2018-07-11 at 3 57 37 pm](https://user-images.githubusercontent.com/28145373/42597044-81cb5f46-8525-11e8-92d4-6d2d46d9ab20.png)

**Comment by diracdeltas** [comment]
@LaurenWags also what's the error in the console?

**Comment by LaurenWags** [comment]
@diracdeltas this is on macOS but was reproduced on Win. Doesn't appear to be anything in the console:
![screen shot 2018-07-11 at 4 35 27 pm](https://user-images.githubusercontent.com/28145373/42597915-82b994c4-8528-11e8-89e5-754b672da985.png)

**Comment by diracdeltas** [comment]
@LaurenWags thanks - looked like there was a console error in your first screenshot (red x)

**Comment by LaurenWags** [comment]
so there is, interesting. the console error isn't reproducing now but will try a few more times and update here if I get something @diracdeltas

**Comment by diracdeltas** [comment]
i think i know what the issue is
