### ISSUE TITLE
iframe interactivity problem

### ISSUE THREAD

**Issue by sbm367** [brave/browser-laptop#14666]
### Description
 Content within iframe elements doesn't load and isn't interactive. I've experienced this issue twice in the context of click reCAPTCHAs and Duo Security 2fa embeds.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by jonathansampson** [comment]
Please check if _Strict Site Isolation_ is enabled in Brave, @sbm367. This is known to prevent interactions with iframes. You can check this preference in about:preferences#security.

![image](https://user-images.githubusercontent.com/815158/42413332-6630b244-81e3-11e8-9f91-12ea9651a706.png)

**Comment by casecoded** [comment]
I had a similar issue with a credit card input field. Source code showed it as an iframe and @jonathansampson 's suggestion resolved the problem.

You can replicate the issue visiting myvue dot com and placing an order as a guest. When using pay by card the input field for the card number wont be selectable.

Brave | 0.23.77
