### ISSUE TITLE
Visited links are not reset when closing Brave

### ISSUE THREAD

**Issue by warwickmm** [brave/browser-laptop#14667]
### Description
Under Preferences -> Security -> Private Data, I have selected all data to be cleared when closing Brave.  However, visited links are not reset when closing Brave.  If I explicitly go to History -> Clear Browsing Data, then the visited links are reset.

### Steps to Reproduce

  1. Under Preferences -> Security -> Private Data, set Brave to clear all data upon closing.
  2. Go to https://www.google.com/#q=test and click on the first result.
  3. Go to https://www.google.com/#q=test again, and see that the first result is rendered as a visited link.
  4. Close Brave.
  5. Launch Brave, and note that the browsing history has been cleared.
  6. Go to https://www.google.com/#q=test, and note that the first result is still rendered as a visited link.
  7. Go to History -> Clear Browsing Data, and clear all data.
  8. Go to https://www.google.com/#q=test, and note that the first result is no longer rendered as a visited link.

**Reproduces how often:**
100%

### Brave Version
|Name|Version|
|-|-|
|Brave|0.23.19|
|V8|6.7.288.46|
|rev|178c3fbc045a0cbdbe098db08307503cce952081|
|Muon|7.1.3|
|OS Release|4.17.2-1-ARCH|
|Update Channel|Release|
|OS Architecture|x64|
|OS Platform|Linux|
|Node.js|7.9.0|
|Tor|0.3.3.7 (git-035a35178c92da94)|
|Brave Sync|v1.4.2|
|libchromiumcontent|67.0.3396.87|

**Reproducible on current live release:**
This is reproducible on version 0.23.19 (178c3fbc045a0cbdbe098db08307503cce952081)
This is reproducible on version 0.23.31 (3148acef36dba0fce89108638bb27927c4937f90)
This is reproducible on version 0.23.73 (50bdb6df42550dd14f5636770ec8585aa26e361b)

### Additional Information
This is related to issue #9351.

**Comment by diracdeltas** [comment]
marking this as regression of https://github.com/brave/browser-laptop/issues/9351

**Comment by bsclifton** [comment]
Can't reproduce on macOS; will try Linux and Windows

**Comment by bsclifton** [comment]
@warwickmm are you using KDE by chance? Do you have more information about your setup? (distro, window manager version, etc)

**Comment by diracdeltas** [comment]
maybe the history delete callback is not called before the browser shuts down?

**Comment by warwickmm** [comment]
Sorry, I should have included more details about my setup in the description.  I'm running Arch Linux with the Cinnamon desktop environment.

**Comment by warwickmm** [comment]
I should perhaps mention that I also have an installation of Chromium on the machine.  Not sure if that matters?

**Comment by bsclifton** [comment]
Based on my results above, one intermittent case I didn't mention (browsing on KDE, closing Brave, opening in Gnome; links showed as visited - Ubuntu 14), and that @rebron was able to reproduce once (but not again), I think this might be exactly the case @diracdeltas is mentioning... which might be a race condition

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/browser-laptop/pull/15028
