### ISSUE TITLE
Can't play videos in Linkedin

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14663]
### Description
Can't play videos in Linkedin

### Steps to Reproduce

  1. Login to Linkedin
  2. Click on play videos
  
**Actual result:**
Can't play video's in Linkedin, even after disabling the Ad blocker in Shield settings 

**Expected result:**
Should be able to play videos in linkedin

**Reproduces how often:**
Easily

### Brave Version
0.23.21
**about:brave info:**
 
Brave: 0.23.21 
V8: 6.7.288.46 
rev: 72405224a05c5cea6c22308c3eed32e67595004b 
Muon: 7.1.4 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
cc: @bbondy 
1+https://community.brave.com/t/cant-play-videos-on-linkedin/26439

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1184
