### ISSUE TITLE
Add option to eagerly connect to the Tor network

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14670]
With https://github.com/brave/browser-laptop/pull/14668 fixing https://github.com/brave/browser-laptop/issues/14617, there is now a small delay the first time you open a private tab with Tor -- longer if it's the first time you've used private tabs with Tor at all.  We did this so that corporate users who are _not_ using Tor do not get a stern talking to from the company security team, as some did when we connected to the Tor network as soon as Brave starts in 0.23.19.  But users who _do_ use Tor may want to reduce the delay.  Some ideas for how to enable Tor users to reduce the delay:

- We could create an option to eagerly start Tor (spelled in some more obvious way).  Users who check this option will get on the Tor network sooner after launching Brave.  Once on the Tor network, there is no difference.
- We could automatically enable that option the first, or perhaps second, time you open a private tab with Tor, or if you actually navigate to Tor once or twice, or some heuristic that indicates you're actually using Tor.
- We could discard the idea altogether because more options means more complexity and the delay in Tor startup is not that bad.

**Comment by nsuchy** [comment]
Why not use OBFS4 Bridges by default so corporate IT has no reason to whine like babies?

**Comment by tomlowenthal** [comment]
If we use Tor for background tasks, we'll probably eagerly load it rather than lazy-loading it. So this issue probably becomes a part of brave/brave-browser#804

[We still shouldn't start Tor — or anything else — *right away* as part of start up. We should always wait a little while so that startup can stay fast.]
