### ISSUE TITLE
external protocol prompt does not appear on about: pages

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14679]
STR:
1. go to about:newtab (or just open a new tab)
2. enter 'mailto:test' in the url bar
3. note that the mail app opens without showing a permission prompt

whereas if you do step 2 on a page such as google.com, the permission prompt appears as expected.

EDIT: marked as tor due to https://hackerone.com/bugs?subject=brave&report_id=388494

**Comment by diracdeltas** [comment]
i thought we fixed this at some point so maybe this is a regression. can't find the original issue though.

**Comment by btlechowski** [comment]
Original issue: #13643.

**Comment by diracdeltas** [comment]
https://hackerone.com/bugs?subject=brave&report_id=388494 makes this more of a serious issue

**Comment by diracdeltas** [comment]
I don't think https://github.com/brave/browser-laptop/issues/13643 is the original issue since that STR was for URLs entered on a remote site like google.com whereas this bug only happens on about:  pages.

**Comment by riastradh-brave** [comment]
Can sites do this or do you have to type it into the URL bar?

**Comment by diracdeltas** [comment]
@riastradh-brave sites can do it via a redirect to a custom protocol (`ssh://...`) apparently

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-laptop/issues/14681 is related, probably fixed by the same muon fix

**Comment by riastradh-brave** [comment]
Immediate symptom is fixed by https://github.com/brave/browser-laptop/pull/14887, but may be other latent issues, for which see https://github.com/brave/browser-laptop/issues/14897.

**Comment by srirambv** [comment]
Verified on Windows10 x64 ysing
* 0.23.74 b508fa7
* Muon	`8.0.4`
* libchromiumcontent	`68.0.3440.84`
