### ISSUE TITLE
userguides.tritondigital.com doesn't load properly because of adblock

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14689]
### Description
Pages are blank for some sites due to Ad Blocker

### Steps to Reproduce

  1. Open the site "https://userguides.tritondigital.com/adv/a2xspecdsp/"
  
**Actual result:**
Pages are Blank due to Ad blocker, after changing the shield settings to "Allow Ads and Tracking" the pages are displayed as expected

**Expected result:**
Pages should open with default shield settings.

**Reproduces how often:**
Easily

### Brave Version
0.23.31
**about:brave info:**
 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
Issue is reported by Community.
https://community.brave.com/t/sites-not-displaying-right-for-me/27278

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1185
