### ISSUE TITLE
DTube video does not play with shields up

### ISSUE THREAD

**Issue by billstclair** [brave/browser-laptop#14684]
### Description

I have to turn the shields off to get a DTube video to play. 

### Steps to Reproduce

  1. Go to this link with shields up (or click on any video on the home page): https://d.tube/#!/v/savannahvan/dcidsjds
  2. Turn shields off to get the video to play.

**Actual result:**

Video does not play with shields up.

**Expected result:**

Video should play.

**Reproduces how often:**

100%

### Brave Version

0.23.19

**Reproducible on current live release:**

Don't know.

### Additional Information

None.

**Comment by Tomatoshadow2** [comment]
Also post what operating system you are using. I can also reproduce on Mac, using the live build. 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by billstclair** [comment]
MacOS: 10.13.5

**Comment by billstclair** [comment]
Don't know which commit fixed it, but this bug is fixed for me in 0.23.39. Closing.
