### ISSUE TITLE
Main content frame not loading (tab title does update)

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1468]
Version
```
Brave: 0.9.2
Electron: 0.37.6
libchromiumcontent: 49.0.2623.112
V8: 4.9.385.35
Node.js: 5.10.0
Update channel: dev
```

Only saw this once so far. Closing the window fixes the problem.

![brave-not-loading-bug](https://cloud.githubusercontent.com/assets/5495083/14786606/b298b99a-0acd-11e6-9c0a-bcaa9ef88794.gif)

**Comment by garvankeeley** [comment]
No steps to repro yet

**Comment by luixxiul** [comment]
How about the latest version?

**Comment by garvankeeley** [comment]
Closing, this has not happened in recent updates
