### ISSUE TITLE
window.prompt not working

### ISSUE THREAD

**Issue by bdsomer** [brave/browser-laptop#14694]
### Description

`window.prompt` does not work and returns `null`.

### Steps to Reproduce

  1. Go to a new tab
  2. Type in `window.prompt()` or `prompt()` and press enter

**Actual result:**

Nothing happens, the function returns `null`.

**Expected result:**
A prompt appears and the value entered is returned.

**Reproduces how often:**

100% of the time

### Brave Version

**about:brave info:**

 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**

idk, I think so

**Comment by eljuno** [comment]
Duplicate of #94.

**Comment by bdsomer** [comment]
@eljuno So it will be in `0.24.0`. Thank you!
