### ISSUE TITLE
Cannot print PDF anymore after last browser update to rev 3148acef36dba0fce89108638bb27927c4937f90

### ISSUE THREAD

**Issue by Nutz95** [brave/browser-laptop#14698]
After upgrading the browser to rev https://github.com/brave/browser-laptop/commit/3148acef36dba0fce89108638bb27927c4937f90 i cannot print anymore my pdf files.

- i have a webshop, so i'm printing every invoices before preparing my orders.
- i was preparing my orders as always, printing my PDF and it was working .
- i then noticed the browser's upgrade notification
- i upgraded my browser ( rev https://github.com/brave/browser-laptop/commit/3148acef36dba0fce89108638bb27927c4937f90) and for some reason my pdf prints are blocked inside my spool.

I'm using a raspberry pi + Cups server (1.5.3) as my print server.
I'm running under windows 8.1

I switched back to firefox and i can print my pdf properly.

has anyone noticed any printing issue with this last upgrade?

**Comment by btlechowski** [comment]
Thanks for reporting.

What OS are you using?

**Comment by bsclifton** [comment]
@Nutz95 we have had some changes to our PDF implementation. Can you please re-test this and let us know if it works? Thanks 😄
