### ISSUE TITLE
update to tor 0.3.3.8

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14695]
https://lists.torproject.org/pipermail/tor-announce/2018-July/000161.html

**Comment by riastradh-brave** [comment]
Not quite, still need to update the hashes in browser-laptop.

**Comment by bsclifton** [comment]
Moving to release 3

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.35 72375c0cd0334a8087423e8e530eff58c177577a
* Muon 7.1.6
* libchromiumcontent 67.0.3396.103
