### ISSUE TITLE
Publisher verification lookup should use a singe list source

### ISSUE THREAD

**Issue by ryanml** [brave/browser-laptop#14691]
### Description
Currently the publisher verification check implemented in browser-laptop does a check for each individual publisher using the `/v3/publisher/identity` route. Instead, a single list of verified publishers should be downloaded and cached periodically so that the checks can be made against that resource instead.

**Comment by LaurenWags** [comment]
@ryanml test plan in https://github.com/brave/browser-laptop/pull/14708 only mentions a clean profile. what would the tests be for an existing profile (with payments enabled)? do we just need to confirm that the ledger table/publisher list isn't lost on update or do we need to do more?

**Comment by NejcZdovc** [comment]
@LaurenWags yes, please test with the existing profile as well

**Comment by LaurenWags** [comment]
@ryanml @NejcZdovc can you guys confirm steps for an update profile testing are:
Launch 0.23.37 from terminal with ledger_verbose=true and with an updated profile where payments are enabled prior to 0.23.37
Wait 15 seconds or so for terminal log confirming the publishers file has been written. Check in the user data directory for publisher-data.json
Stop and restart Brave. Wait a bit and confirm via terminal that the publishers file hasn’t been rewritten (should occur every 48 hours)
Visit a known verified publisher, wait the minimum amount of time before logging a visit.
Confirm via the publishers toggle/ledger table that the publisher shows as verified.
Perform steps 4 and 5 for a non-verified publisher.

**Comment by ryanml** [comment]
@laurenwags this looks good to me. I assume the restart is just to confirm that the pub file doesn't get rewritten correct? No restart should be needed otherwise :)

**Comment by LaurenWags** [comment]
@ryanml yep! 😄

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.37 47b1b59
* Muon 7.1.6
* libchromiumcontent 67.0.3396.103
