### ISSUE TITLE
Need a better rez fallback favicon

### ISSUE THREAD

**Issue by jenn-rhim** [brave/browser-laptop#14707]
### Description

Fallback favicon looks over compressed, leading to a poor quality bitmap. See attached.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.23.19

**Reproducible on current live release:**

### Additional Information

![screen shot 2018-07-10 at 12 29 24 pm](https://user-images.githubusercontent.com/4369856/42532977-4f97212e-843d-11e8-9c42-2216178facea.png)

**Comment by bsclifton** [comment]
@jenn-rhim are you referring to the planet (Saturn looking) icon? or the icon on the page you're viewing? (the not found paper sad face)?

If referring to the icon, we have an issue open already (and you can close this one 😄 )
https://github.com/brave/browser-laptop/issues/14607
