### ISSUE TITLE
Make linux prompt user that there's an update available and how to manually install it

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1470]
#401 #910

**Comment by luixxiul** [comment]
ref: #401

**Comment by zmanian** [comment]
Is there a URL which provides current release version metadata for linux builds?

**Comment by bbondy** [comment]
yes `app/updater.js` uses `requestVersionInfo` already which contacts that endpoint.
You can use `BRAVE_UPDATE_VERSION=0.9.2` for example to fake your version back to an earlier version or just temporarily change the package.json file.

**Comment by Liunkae** [comment]
+1 from #6136.

**Comment by Liunkae** [comment]
+1 from #7504.

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by bsclifton** [comment]
Moving to 0.14.3
