### ISSUE TITLE
Allow users to download .torrent files through Tor

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14706]
### Description
Using BitTorrent through Tor is problematic -- the Tor Project [advises against it](https://tor.stackexchange.com/a/68), it [provides weak privacy in most implementations](https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea), and it's a big drain on the shared scarce resource that is the Tor network.  So to avoid giving users a false sense of security around it, we block webtorrent in private tabs with Tor: https://github.com/brave/browser-laptop/issues/13063

However, there's no reason users shouldn't be allowed to download the .torrent file itself, even if we refuse to load it automatically into webtorrent.  If users want to make an explicit decision to subsequently load it into a privacy-destroying BitTorrent client, that's their prerogative.

### Steps to Reproduce

  1. Open a private tab with Tor.
  2. Go to https://webtorrent.io/torrents/sintel.torrent in an attempt to download the file.

**Actual result:**
> For your privacy, torrents are blocked in private tabs when Tor is enabled.

**Expected result:**
Brave offers a button to download the file in that dialogue box.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.31
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103
Muon | 7.1.5
Node.js | 7.9.0
OS Architecture | x64
OS Platform | Linux
OS Release | 4.13.0-46-generic
rev | 3148ace
Tor | 0.3.3.7 (git-035a35178c92da94)
Update Channel | Release
V8 | 6.7.288.46

**Reproducible on current live release:**
yes

### Additional Information
https://community.brave.com/t/ublock-torrent-in-tor-tabs/27399

**Comment by flamsmark** [comment]
There's also no reason to assume that users' torrent clients are colocated with their browsing — they may want to download the `.torrent` file to use on another host. Downloading should work just like downloading any other file the browser doesn't normally handle — as if Brave didn't have a webtorrent feature at all.

**Comment by Alino** [comment]
Regarding Tor, My Brave browser is very unreliable and is flooding me with errors that it cannot connect to the Tor network when I am inside a Tor tab. So I cannot test this myself, but did you try to right click on the torrent link and choose "Save Link As..." ? I would expect that to download any file, if the link is pointing to a file.

**Comment by tomlowenthal** [comment]
This issue has made the leap to the new repo brave/brave-browser#1134.
