### ISSUE TITLE
Unable to interact with Cloudflare captcha on macOS

### ISSUE THREAD

**Issue by boistordu** [brave/browser-laptop#14714]
### Description

the captcha page in tor private tabs for http://zooqle.com and http://torrent9.me seems to not work. It's the cloudflare captcha page. It's only happening on macos, I only tried on 10.13.5 with last brave release. The problem happens whether or not the shields are activated.

### Steps to Reproduce

try to connect in a private tab with tor to zooqle.com or torrent9.me 
it does happen with every iframe from cloudlfare captcha. So if you try to connect to soundcloud and the captcha appear from cloudflare you can't interact with it.

**Actual result:**

**Expected result:**

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

```
Name | Version
-- | --
Brave | 0.23.31
V8 | 6.7.288.46
rev | 3148ace
Muon | 7.1.5
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)

```

**Reproducible on current live release:**

### Additional Information

If you open the dev tools, you'll see that several js errors pops up

**Comment by eljuno** [comment]
Did you have _Site isolation_ enabled in Preferences > Security?

**Comment by boistordu** [comment]
good catch it was the site isolation yes

**Comment by eljuno** [comment]
Maybe related to #14299

**Comment by bsclifton** [comment]
This is fixed with `brave-core`; you can download a copy of the developer channel release here:
https://brave.com/download-dev
