### ISSUE TITLE
`Alt` does not show in menu for Linux/Windows when specified in accelerator

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14710]
### Description

Specifying shortcuts with `Alt` in them ends up with the `Alt` being omitted from the menu

#### Existing problems
 1. Verify in the code that the accelerator for `View Page Source` is `CmdOrCtrl+Alt+U`
 2. Open Brave on Linux and load a page
 3. Right click the page
 4. Notice accelerator does not have the `Alt`

#### Do it yourself
  1. Find a menu item in the code
  2. Change the shortcut to something like `CmdOrCtrl+Alt+N`
  3. Run the code on Linux

**Actual result:**

**Tor shortcut should be `Ctrl+Alt+N`**
![screen shot 2018-07-10 at 1 40 28 pm](https://user-images.githubusercontent.com/4733304/42536970-70bab6b2-8448-11e8-9d3e-166917828530.png)
---------------
**View Page Source shortcut should be `Ctrl+Alt+U`**
![screen shot 2018-07-10 at 1 44 34 pm](https://user-images.githubusercontent.com/4733304/42536980-79cf5140-8448-11e8-9b5f-ab1409fedcab.png)

**Expected result:**
`Alt` should show as part of the shortcut

**Reproduces how often:**
100%

### Brave Version
master

**Reproducible on current live release:**

**Comment by riastradh-brave** [comment]
Confirmed here!

**Comment by srirambv** [comment]
It doesn't show in new tab context menu as well #14716 
![image](https://user-images.githubusercontent.com/17010094/42596646-628208fc-8524-11e8-83b2-e6cd43b5737a.png)

**Comment by srirambv** [comment]
@bsclifton should this be pulled into release 4?

**Comment by bsclifton** [comment]
@srirambv this would be a Muon fix- not sure if it's worth it. I'll tentatively assign it to release 4 so that it gets picked up by next Tuesday's Triage. My recommendation would be to not fix

**Comment by alexwykoff** [comment]
Initial fix : Retain keyboard shortcut with option on mac, on windows and linux hide it from the menu. If necessary on windows and linux, do not offer the shortcut at all.
