### ISSUE TITLE
[hackerone] consider disabling FTP

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14712]
https://hackerone.com/reports/378805

related:
https://hackerone.com/bugs?subject=brave&report_id=378809
https://hackerone.com/reports/378864

**Comment by flamsmark** [comment]
FWIW, I think that Chrome has gone back and forth on this one a bunch of times. FTP within a regular browsing context is a bit of a bugbear. On the other hand, lots of documents are only available via FTP — especially legacy government documents. Leaving FTP support in the browser really lowers the barrier to accessing those materials.

Of course, we don't need to be the only way for journalists and so on to access government documents. I'd be pretty comfortable with ripping out FTP for the medium term and building it back as an independent feature with a modern security & privacy mindset later (perhaps much later).

**Comment by diracdeltas** [comment]
i think all of these issues are specific to muon + FTP, so when FTP returns in brave-core, it will probably not cause problems like these

**Comment by bsclifton** [comment]
Pushing back to release 5; we'll want to wait until after C68 is merged before merging the Muon changes required for this (see above links to PRs)

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/muon/commit/25cf4241fffc805e1ad90d36bf8c2dfdafcc99b2

**Comment by LaurenWags** [comment]
@bsclifton to confirm, when I do those steps on macOS I get this notification banner:
![screen shot 2018-08-03 at 10 43 27 am](https://user-images.githubusercontent.com/28145373/43657610-55b00cfc-9724-11e8-97c0-b340049234dd.png)

And if I click Allow, I am prompted to enter credentials. I entered the creds from https://dlptest.com/ftp-test/ but couldn't login.
![screen shot 2018-08-03 at 10 44 03 am](https://user-images.githubusercontent.com/28145373/43657638-68366fce-9724-11e8-8a61-347a61faee0f.png)

**Comment by diracdeltas** [comment]
i think the fact that it's prompting to open an external application is correct, since we will no longer handle FTP ourselves. not sure why the credentials don't work but that doesn't seem like a Brave bug.

**Comment by LaurenWags** [comment]
@diracdeltas so since I'm being prompted via the notification banner then this one is ok as is (at least on macOS)?

cc @kjozwiak so he can check on his machine as well.

**Comment by diracdeltas** [comment]
@LaurenWags yes this seems fine

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.77 0125b5f
* Muon 8.0.6
* libchromiumcontent 68.0.3440.84

**Comment by srirambv** [comment]
@diracdeltas this is what happens on Windows with FTP linked to open in Brave. It goes on an infinite loop opening blank pages but never prompting to enter credentials.

![ftp](https://user-images.githubusercontent.com/17010094/43660872-3e69c772-972e-11e8-8e28-72fa519b7521.gif)
