### ISSUE TITLE
context menu handling

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1472]
As we bring in more extension support, we should consider changing the handling of context menus to bring it in line with how they are managed by extensions. Since we moved a lot of the page functionality to an extension already, we can manage our own context menu items the same way that extensions will manage them. 

https://developer.chrome.com/extensions/contextMenus

uses a list of context types to define when the item will appear in the menu

`"all", "page", "frame", "selection", "link", "editable", "image", "video", "audio", "launcher", "browser_action", or "page_action"`

**Comment by alexwykoff** [comment]
@jonathansampson is this still an issue? Thanks
