### ISSUE TITLE
Twitch videos doesn't play in Tor tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14724]
### Description
Twitch videos doesn't play in Tor tabs

### Steps to Reproduce

  1. Launch Brave with clean profile
  2. Open Tot tab
  3. Open Twitch.tv and play any twitch video

Note: Please note that issue persists even when we turn down the shield settings.

**Actual result:**
Twitch videos are not playing in Tor tabs
![twitch videos doesn t play in tor](https://user-images.githubusercontent.com/38657976/42645605-191bd794-861c-11e8-9d97-7241af129839.gif)

**Expected result:**
Twitch videos should play in Tor tabs

**Reproduces how often:**
Easily

### Brave Version
0.23.34
**about:brave info:**
 
Brave: 0.23.34 
V8: 6.7.288.46 
rev: a47171894a26b74c84fdfc1f604c16144b36be52 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
No

### Additional Information
On Brave version 0.23.19, 0.23.32, 0.23.33 and 0.23.34 Twitch videos are not running in Tor tabs. Only on version 0.23.31 twitch videos are running in Tor tabs.

**Comment by bsclifton** [comment]
Moving to next milestone as this is not blocking and there isn't a fix (yet)

**Comment by riastradh-brave** [comment]
Does it reproduce with shields down?

**Comment by bsclifton** [comment]
@kjozwiak to add some more notes 😄👌

**Comment by GeetaSarvadnya** [comment]
@bsclifton @kjozwiak Issue persists even when we turn down the shield settings.

**Comment by kjozwiak** [comment]
> @bsclifton @kjozwiak Issue persists even when we turn down the shield settings.

Thanks for checking @GeetaSarvadnya 👍 I'm getting the same results on `macOS 10.13.6`. When attempting to play Twitch streams, you'll see a bunch of errors in the browser console:

<img width="1216" alt="screen shot 2018-07-31 at 2 14 36 pm" src="https://user-images.githubusercontent.com/2602313/43479208-ca66f5fa-94cd-11e8-9fc9-22d5579200b9.png">

When you leave Twitch running for a few minutes within a Tor PT, you'll notice the following:

<img width="1200" alt="screen shot 2018-07-31 at 2 28 28 pm" src="https://user-images.githubusercontent.com/2602313/43479323-1dd2950a-94ce-11e8-971f-41d0d8ff738b.png">

It seems like the websocket is having issues connecting to the needed services.

Twitch also works under `TorBrowser 7.5.6 (based on Mozilla Firefox 52.9.0)` so this is definitely Brave related.

**Comment by bsclifton** [comment]
As we add Tor support to brave-core, let's keep this use-case in mind 😄

**Comment by kjozwiak** [comment]
> As we add Tor support to brave-core, let's keep this use-case in mind 😄

We'll probably use similar test cases we used for b-l [1] so we should be able to spot this under `b-c` if it's still an issue with the new implementation.

* [1] https://github.com/brave/qa-resources/blob/master/wikitemplate.md#tor-private-tabs
