### ISSUE TITLE
Site notification badges don't appear for some websites

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-laptop#14725]
**Have you searched for similar issues? We have received a lot of feedback and bug reports that we have closed as duplicates. Before submitting this issue, please visit our community site for common ones: https://community.brave.com/c/common-issues**
Yes

**Description**
_[This was submitted by a Reddit user (u/setbnys) [here](https://www.reddit.com/r/brave_browser/comments/8xxd9k/if_the_bookmarks_list_is_big_you_cant_see_the/e26ms6k) so this is my approximate translation of the issue he described]_
Notification badges/alerts for some websites don't appear on tab even though notification comes through and sound is triggered.

**Steps to Reproduce**
  1. Open Brave, navigate to [poe.trade](poe.trade)
  2. Open multiple tabs (at least 2)
  3. Wait for site to send a notification 

**Actual result:**
Notification comes through and alert sound plays but red tab badge does not display: 
https://i.imgur.com/PHxDuAH.png

**Expected result:**
Notification comes through, alert sound plays _and_ red tab badge should be present in tab, showing new/unread messages/notifications:
https://i.imgur.com/zRwhHQH.png

**Reproduces how often:**
User claims it's inconsistent but noticeable, quotes it happening "maybe 40%" of the time.

### Brave Version

**about:brave info:**
 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

**Additional Information**
This very well may be an isolated occurrence, but it's worth mentioning that he claims to have tested it on many other browsers (he claims he tested 7 of them) and he was _only_ able to produce this error in Brave.

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
