### ISSUE TITLE
Right click sometimes doesn't work

### ISSUE THREAD

**Issue by manueltorrez** [brave/browser-laptop#14739]
### Description

Sometimes right click doesn't work properly, it doesn't show the menu and it's not my touchpad nor my OS. It solves when I switch programs but it's annoying
### Steps to Reproduce

  1. Click right click
  2. Doesn't show the menu

**Actual result:**

Nothing happens

**Expected result:**

Right click menu for open link in new tab, private tab, copy, paste, etc.

### Brave Version

**about:brave info:**

 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 4.14.53-1-MANJARO 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Not enough info here to take action. We have context menus via right click as part of our test plan, so we have been testing that this works

Closing for now. Please re-open and share some more info (what distro / window manager / etc) if you still experience this
