### ISSUE TITLE
Add drag and drop to open links in new tab like Chrome

### ISSUE THREAD

**Issue by manueltorrez** [brave/browser-laptop#14738]
### Description

I'm suggesting to add drag and drop support to open links in a new tab just like Chrome. I've included a more self-explanatory gif:

![Alt Text](https://media.giphy.com/media/3M7zBtA4KplTQn4b0t/giphy.gif)

**Comment by eljuno** [comment]
Dupe of #10600?

**Comment by manueltorrez** [comment]
@eljuno indeed. I hadn't seen it, my bad
