### ISSUE TITLE
Block trackers that use unique etags and cached scripts

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1473]
Many sites work around 3rd-party cookie blocking by using unique etags, cached scripts and other methods to persist identifiers over time. Looks like a pretty good overview here
https://www.chromium.org/Home/chromium-security/client-identification-mechanisms

We should block these methods and possibly flag sites that use them

**Comment by bridiver** [comment]
possible detection methods:
Suppress or randomly alter the etag/cache headers on the second request and check the returned content/headers
Ignore long cache headers on the second request and verify content

The downside to these methods is that you potentially sacrifice latency for privacy. We could use the cached version in the page, but make a second request to verify the content. It's probably useful to make the request from an isolated "partition" anyway. 

Server-side methods could also potentially be used. It's a little tricky because content can change very quickly, but it might be useful as a method to "flag" sites and trigger the browser to check the content for other identifiers.

**Comment by luixxiul** [comment]
Maybe we can borrow some ideas from: https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

**Comment by bridiver** [comment]
sounds like they are just flushing the cache periodically. I think we'd like to have something a little more sophisticated because flushing the cache will slow down page loads

**Comment by flamsmark** [comment]
Moving to the new codebase: brave/brave-browser#536
