### ISSUE TITLE
Update tor binaries to v0.3.3.9

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#14737]

**Comment by riastradh-brave** [comment]
From the release notes:

> Tor 0.3.3.9 moves to a new bridge authority. The only people who need to upgrade are people who operate a bridge relay — so their bridge address can resume being given out to censored users, and so their stats can resume being included in the metrics pages.
> 
> Changes In Version 0.3.3.9 - 2018-07-13
> - Directory authority changes:
>   - The "Bifroest" bridge authority has been retired; the new bridge authority is "Serge", and it is operated by George from the Tor BSD Diversity project. Closes ticket 26771.

This is the only change, so I think we can skip this release.  (It's not even relevant for #12989 because it applies only to the _operators_ of bridges, not to the _users_ of bridges.)
