### ISSUE TITLE
Tor version missing from about:brave (until you launch a Tor tab)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14731]
### Description
In 0.23.19 when Tor Private tabs were introduced, the Tor version was listed in about:brave. This stopped displaying in 0.23.31 when lazy-loading was introduced. Once you open a private tab with Tor, it will show as expected

### Steps to Reproduce

  1. Launch 0.23.19
  2. Navigate to about:brave
  3. See Tor version listed.
  4. Close 0.23.19
  5. Launch 0.23.31
  6. Navigate to about:brave

**Actual result:**
Tor version is not listed:
![screen shot 2018-07-13 at 10 51 19 am](https://user-images.githubusercontent.com/28145373/42698006-b1861044-868a-11e8-906b-14bd5b7edb28.png)

![screen shot 2018-07-13 at 10 51 09 am](https://user-images.githubusercontent.com/28145373/42698008-b4618cb2-868a-11e8-82bf-66747ec2ceb1.png)

**Expected result:**
Tor version should be listed
![screen shot 2018-07-13 at 10 47 54 am](https://user-images.githubusercontent.com/28145373/42698018-b980035e-868a-11e8-9288-2c3ed9d28415.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.23.35, 0.23.31

**Reproducible on current live release:**
yes

**Comment by bsclifton** [comment]
@riastradh-brave I think it's OK to not have the Tor version immediately (I kicked it out of this release). Maybe this issue can track making it more elegant.  ex: show `(not loaded yet)` for when the daemon hasn't been loaded

**Comment by bsclifton** [comment]
Definitely something we won't fix- but something good to keep in mind when Tor is implemented in brave-core
