### ISSUE TITLE
Sessions-Store-1 stores last window position, does not update to deal with screen size change

### ISSUE THREAD

**Issue by alexanderjwoods** [brave/browser-laptop#14745]
###Have you searched for similar issues?

Yes.  Same issue as #3558

### Description
See #3558.  When a window closes, the sessions-store-1 json in appdata saves the current window position.  If that position no longer exists next time you load Brave, the window is irrecoverably off screen.  (I.e., undocking a laptop, screen size change, etc.)

### Steps to Reproduce
See #3558

**Actual result:**
Window off screen

**Expected result:**
Window resets to left 0 top 0

**Reproduces how often:**
100% of the time

### Brave Version

Brave | 0.23.31
-- | --
V8 | 6.7.288.46
rev | 3148ace
Muon | 7.1.5
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
Yes

**Comment by planux** [comment]
+1. The very first link you find when you search "how to get missing window back windows" leads here:
https://www.technipages.com/bring-off-screen-window-back-onto-screen

And the very first comment on that thread (as of Aug 12 2018) is about this behavior in... Brave!

As a workaround, you can:
1) Click on the Brave icon in your taskbar
2) Press alt+space
3) Click on Move
4) Use the arrow keys to migrate the Brave window back onto your screen. This requires you to guess correctly where, in relation to your active viewport, the Brave window is hiding.

Brave should do one or more of the following:
A) Check to make sure it's visible when its position is restored. If it's not, assume to some sane defaults for window placement
B) Respect the Shift-Right-Click affordance in Windows. This should bring up the right-click menu, from which Move can be selected and the window migrated back to the active viewport by the user.

As an FYI, Google Chrome does 'B', and also possibly 'A'. Other Electron-based apps, like Slack, fail in the same way that Brave does, so it might ultimately be an Electron issue.

**Comment by drphilgarner** [comment]
Also experienced this issue - the resolution from @planux doesn't quite work, the arrow key movement does nothing, but clicking 'Maximize' gets the window back into view and if you click and drag the main window around when maximized you'll have it back under control.

**Comment by bsclifton** [comment]
There's a good chance this is fixed with our [Developer channel release](https://brave.com/download-dev). Can you give that a shot and let us know if it works?

Closing as I believe that build fixes the reported error
