### ISSUE TITLE
Mac Switch Off

### ISSUE THREAD

**Issue by mcfly404** [brave/browser-laptop#1474]
Each time I would turn off my mac, Brave interrupts extinction.
![capture 2016-04-25 a 21 08 28](https://cloud.githubusercontent.com/assets/18666452/14795800/66adaaa6-0b2a-11e6-9cf4-ded32f87ddb5.png)

**Comment by schwartz2000** [comment]
same thing from more than a month now.   
El Capitan 10.11.4
I have to FORCEKILL every time I want to shutdown or restart my computer.

**Comment by hilohits** [comment]
I'm still having the same issue.

iMac 12.2 
Elcapitan

**Comment by bbondy** [comment]
I think this is probably fixed with 0.9.6. Please re-open if you see again on that version or later.
