### ISSUE TITLE
your beta is older release than normal install

### ISSUE THREAD

**Issue by scottstensland** [brave/browser-laptop#14741]
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-zesty-yakkety-xenial-and-trusty-amd64

on ubuntu 16.04 when I use above link to install brave beta its a previous release older not newer than normal brave 

brave beta

```
Brave	0.22.707
V8	6.6.346.26
rev	5f2fcda
Muon	6.0.9
OS Release	4.4.0-130-generic
Update Channel	Beta
OS Architecture	x64
OS Platform	Linux
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	66.0.3359.139


$ apt-cache policy brave-beta 
brave-beta:
  Installed: 0.22.707-1
  Candidate: 0.22.707-1
  Version table:
 *** 0.22.707-1 500
        500 https://s3-us-west-2.amazonaws.com/brave-apt-staging xenial/main amd64 Packages
        100 /var/lib/dpkg/status



```

whereas here is normal brave again using above URL to install

```
Brave	0.23.31
V8	6.7.288.46
rev	3148ace
Muon	7.1.5
OS Release	4.4.0-130-generic
Update Channel	Release
OS Architecture	x64
OS Platform	Linux
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	67.0.3396.103


$ apt-cache policy brave 
brave:
  Installed: 0.23.31-1
  Candidate: 0.23.31-1
  Version table:
 *** 0.23.31-1 500
        500 https://s3-us-west-2.amazonaws.com/brave-apt xenial/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by bsclifton** [comment]
I've tried pushing a newer BETA several times (for Linux), but we're having a problem with the VM that does it. Apologies that it's behind. I'll try to update in the next week or so. In the meantime, you can manually download the latest beta from the releases page
https://github.com/brave/browser-laptop/releases

**Comment by bsclifton** [comment]
Internal issue used to track the job which is blocking this:
https://github.com/brave/devops/issues/166

**Comment by bsclifton** [comment]
New beta officially pushed 😄 👍  And the underlying infrastructure is fixed now. I'll do my best to make sure this stays in sync (when we switch to brave-core, this process should be automated)
