### ISSUE TITLE
Optional 24-hour time on New Tab Clock

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14744]
### Description
The clock on the Dashboard is formatted based on the client's locale. Some users would prefer to use 24-hour formatting, in spite of their locale's insistence on 12-hour formatting. Because we use the `Intl` object, this is fairly easily accomplished by passing one additional option to `DateTimeFormat`:

Current Code:
```js
new Intl.DateTimeFormat([], {hour: '2-digit', minute: '2-digit'})
```
Suggested Change:
```js
new Intl.DateTimeFormat([], {hour12: getSetting('hour12'), hour: '2-digit', minute: '2-digit'})
```

Work would need to be done to add the _hour12_ setting, etc.

**Comment by bsclifton** [comment]
Originally opened with https://github.com/brave/browser-laptop/issues/5647 - we closed (in triage or elsewhere) because it should be respecting user's locale

Let's talk about this for our next triage meeting

**Comment by bsclifton** [comment]
Closing as `wontfix`. I don't believe we'll be able to address this
