### ISSUE TITLE
'cache read failure' console errors

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1475]
Often Github and Twitter load with missing stylesheets and messages like this in the console:
![screen shot 2016-04-25 at 1 56 39 pm](https://cloud.githubusercontent.com/assets/549654/14798733/dc7e32f6-0aed-11e6-8705-e269f2ae813e.png)

reloading fixes the problem

**Comment by bbondy** [comment]
I get this too sometimes.

**Comment by luixxiul** [comment]
Closing as stale. Let's reopen if this is still experienced 👍
