### ISSUE TITLE
Some files are not being decompressed after download.

### ISSUE THREAD

**Issue by givanse** [brave/browser-laptop#14757]
### Description

I've found one instance of a file that is not getting decompressed after download.

### Steps to Reproduce

  1. Go to https://www.virtualbox.org/wiki/Downloads
  2. Download the extensions pack (https://download.virtualbox.org/virtualbox/5.2.14/VirtualBoxSDK-5.2.14-123301.zip)

**Actual result:**

See in your downloads folder the file `Oracle_VM_VirtualBox_Extension_Pack-5.2.14.vbox-extpack.gz`

**Expected result:**

The downloaded file should have been `Oracle_VM_VirtualBox_Extension_Pack-5.2.14 (1).vbox-extpack` note no `gz` extension

**Reproduces how often:**

100% repro

### Brave Version

```
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**
Yes.

### Additional Information

OS: MacOS High Sierra 10.13.6

Same computer and link downloads the file and decompresses it correctly when using Chrome.

**Comment by bsclifton** [comment]
@givanse can you please try this with our new [Developer channel release](https://brave.com/download-dev)? This should be fixed there 😄 👍
