### ISSUE TITLE
Tor Launcher crashes on new tor tab

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14762]
### Steps to Reproduce
  1. Clean install
  2. Open a tor tab

**Actual result:**
Tor crashes
`[22916:22916:0717/175528.251901:ERROR:tor_launcher_factory.cc(101)] Tor Launcher Crashed
`

**Expected result:**
No crash, able to connect through tor

**Reproduces how often:**
always

### Brave Version
 
```
Brave: 0.23.69 
V8: 6.8.275.21 
rev: 167e67d8f110c841cc1a09bd35c6f4d867e61613 
Muon: 8.0.0 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.59
```
Also reproduced on mac and windows.

**Reproducible on current live release:**
no

cc @bsclifton @bridiver @srirambv @LaurenWags @GeetaSarvadnya @kjozwiak

**Comment by riastradh-brave** [comment]
Can you share ~/.config/brave-beta/tor/data/tor.log?

**Comment by btlechowski** [comment]
@riastradh-brave the log is no generated. Whole ~/.config/brave-beta/tor/data/ is empty.

**Comment by srirambv** [comment]
Data folder is empty for me on Windows

**Comment by riastradh-brave** [comment]
Oh, this is after the C68 merge.  Will investigate.

**Comment by kjozwiak** [comment]
When attempting to open a Tor tab on the C68 build, I also go the following message in the terminal:

`[85446:11267:0717/120215.030580:ERROR:service_manager.cc(156)] The Service Manager prevented service "content_browser" from binding interface "tor.mojom.TorLauncher" in target service "tor_launcher". You probably need to update one or more service manifests to ensure that "tor_launcher" exposes "tor.mojom.TorLauncher" through a capability and that "content_browser" requires that capability from the "tor_launcher" service.`

@riastradh-brave not sure if it's relevant but figured I would add it incase it's helpful.

**Comment by darkdh** [comment]
@riastradh-brave the message is really helpful. Thanks

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/pull/618/commits/25a4963be14ba11873c0b76582e5e721e1132c6d

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.70 e63c7804ea4850229904d4dc991143e1ebeabb51
• Muon 8.0.1
• libchromiumcontent: 68.0.3440.68
