### ISSUE TITLE
remove PIA

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14763]
we decided to not use PIA anymore

are there infrastructure changes needed for this or is it just a matter of changing the endpoints in browser-laptop? @evq @mrose17 

related: https://github.com/brave/browser-laptop/issues/12923

**Comment by alexwykoff** [comment]
We'd like to make sure this goes with C68

**Comment by evq** [comment]
no infra changes, just a matter of removing this logic - https://github.com/brave/browser-laptop/blob/d60325000ec274e13c889254034fe33abe618c2d/app/browser/api/ledger.js#L1597

**Comment by diracdeltas** [comment]
@alexwykoff so move the milestone to 0.23 with c68?

**Comment by diracdeltas** [comment]
nvm i understand

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.70 e63c780
* Muon  `8.0.1`
* libchromiumcontent	`68.0.3440.68`
