### ISSUE TITLE
Pinned tab doesn't unpin until focus is changed to other tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14764]
### Description
Pinned tab doesn't unpin until focus is changed to other tab

### Steps to Reproduce
  1. Clean install 0.23.69
  2. Open 3-4 tabs and visit sites in each and pin one of the tab
  3. Set focus to other normal tab and close and relaunch browser
  4. Set focus to pinned tab and wait till the page loads
  5. Right click and unpin, doesn't unpin, switch focus to normal tab, pinned tab becomes unpinned

**Actual result:**
![pinned tab](https://user-images.githubusercontent.com/17010094/42833068-247b0abc-89c1-11e8-803b-fe5925d80c9d.gif)

**Expected result:**
Should unpin immediately 

**Reproduces how often:**
100%

### Brave Version

Brave|0.23.69
--|--
V8|6.8.275.21
rev|167e67d
Muon|8.0.0
OS Release|10.0.17134
Update Channel|Beta
OS Architecture|x64
OS Platform|Microsoft Windows
Node.js|7.9.0
Brave Sync|v1.4.2
libchromiumcontent|68.0.3440.59

**Reproducible on current live release:**
Yes. Need to find the regression range for this

### Additional Information
Possibly related to #14341 
Issue reproduced on mac by @LaurenWags on release version

**Comment by bsclifton** [comment]
I don't think we'll be able to address before moving to [brave-core](https://github.com/brave/brave-browser)
