### ISSUE TITLE
Do not display incorrect keyboard shortcut ommitting 'Alt' for Open New Private Tab with Tor'

### ISSUE THREAD

**Issue by petemill** [brave/browser-laptop#14768]
Address #14710 with an initial workaround by not displaying menu items which incorrectly display the keyboard shortcut as Ctrl-N where it should be Ctrl-Alt-N

#### _(most important is fixing Windows and not regressing macOS)_

Windows
  1. `File... New Private Tab with Tor` main app menu should display correct shortcut
  2. Shortcut should work correctly
  3. Hamburger menu should display correct shortcut
  4. Long press '+' New Tab button should not display incorrect shortcut

Linux (16.04)
  1. `File... New Private Tab with Tor` main app menu should display no shortcut
  2. Shortcut should **not work** correctly
  3. Hamburger menu should display no shortcut
  4. Long press '+' New Tab button should display no shortcut

Mac
   1. `File... New Private Tab with Tor` main app menu should display correct shortcut
  2. Shortcut should work correctly
  3. Hamburger menu should display correct shortcut
  4. Long press '+' New Tab button should display correct shortcut

**Reproduces how often:**

### Brave Version

**about:brave info:**
0.23.37

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
 * 0.23.39 a38be75
* Muon `7.1.6`
* libchromiumcontent `67.0.3396.103`
