### ISSUE TITLE
Min browsing activity message is retained even after min criteria is met

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14767]
### Description
Min browsing activity message is retained even after min criteria is met

### Steps to Reproduce
  1. Create staging wallet using `LEDGER_ENVIRONMENT=staging`
  2. Visit a couple of sites to add to ledger entry keeping browsing time less (ex: 10 mins)
  3. Trigger reconcile by changing `reconcileStamp` in ledger-state.json
  4. Relaunch browser, ensue the min activity message is shown and recocile date is pushed ahead
  5. Complete 30 mins of browsing activity with the sites listed in ledger table
  6. Message doesn't change until a next reconcile happens

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/42839831-e592447a-89d2-11e8-9c37-5fe0746ffe98.png)

**Expected result:**
Once min browsing time is met, message should change to `Your Wallet is ready` if balance matches budget or `Your account balance is under your budget for this month. Please add funds.` if balance is less than budget 

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.37
-- | --
V8 | 6.7.288.46
rev | 47b1b59
Muon | 7.1.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
Not checked as unable to trigger reconcile with env variables

### Additional Information
cc: @jasonrsadler @NejcZdovc 
Reloading payment page, disable/enable payments, reopen payments tab doesn't refresh the message. It only dismiss when a new reconcile is triggered.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.70 e63c780
* Muon 8.0.1
* libchromiumcontent 68.0.3440.68
