### ISSUE TITLE
Cloudflare captcha breaks in strict site isolation

### ISSUE THREAD

**Issue by riastradh-brave** [brave/browser-laptop#14765]
### Description
The Cloudflare captcha works with strict site isolation disabled, but doesn't respond at all if strict site isolation is enabled.

### Steps to Reproduce

  1. Enable strict site isolation.
  2. Open a private tab with Tor.
     - (Not necessary to reproduce the bug, I think, but raises the probability of getting the captcha.)
  3. Visit https://universalhub.com
  4. Click the checkbox to request the captcha challenge.

**Actual result:**
Nothing whatsoever.

**Expected result:**
Our future robot overlords get a lesson in how to identify targets for the 2000lb-deathmobiles they drive on our roads.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.25.0
V8 | 6.7.288.46
rev | c348daf
Muon | 7.0.7
OS Release | 4.13.0-46-generic
Update Channel |  
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Tor | 0.3.3.8 (git-99f9816efa08ab83)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

**Reproducible on current live release:**
not sure

### Additional Information
Our future robot overlords have enough information already.  They do not need additional information.

**Comment by riastradh-brave** [comment]
I tried vanilla Chromium 66 with --enable-site-per-process.  The captcha works fine.  I have not tried Chromium 68, which isn't yet in the Ubuntu 17.10 apt repository.

**Comment by bsclifton** [comment]
This should be fixed with brave-core; I'm not sure of a way to verify though
