### ISSUE TITLE
not prompted to save login info

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14770]
### Description
Using c68 build you're not prompted to save passwords.

### Steps to Reproduce

  1. Navigate to https://trac.torproject.org/projects/tor/login
  2. Enter username/password

**Actual result:**
Not prompted to save login info

**Expected result:**
Should be prompted to save login info

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.23.69 
V8: 6.8.275.21 
rev: 167e67d8f110c841cc1a09bd35c6f4d867e61613 
Muon: 8.0.0 
OS Release: 16.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.59

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @srirambv on Win

**Comment by alexwykoff** [comment]
Hey @darkdh could you confirm that someone is actively investigating this? Thanks!

**Comment by darkdh** [comment]
should be fixed with muon 8.0.1 , browser laptop 0.23.70

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.72 c3b1cac
* Muon 8.0.2
* libchromiumcontent 68.0.3440.75
