### ISSUE TITLE
How to test translation?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1477]
Would someone please tell me how to test translated files? Information about what needs to be added or changed to build modified Brave locally would be helpful. I would like to check the quality and consistency of translation before sending PR.

**Comment by aekeus** [comment]
There are a couple things that need to be done to test the translation. The first is to have a directory in the locales folder in the format of xx-XX. You can see a few examples of these such as en-US or nl-NL. In that directory place each of the translated .properties files.

In the app/locale.js file is a hash containing the currently configured languages. Adding the new language and starting up the browser will allow you to select the languages from the about:preferences page.

I can do the configuration for if you would like. Please send along a pull request and add me @aekeus as a reviewer. Thanks.

**Comment by luixxiul** [comment]
I see, thanks! I will give a try.

**Comment by luixxiul** [comment]
I'm trying to test it, but due to the error I don't get the binary built yet :-(
https://github.com/bbondy/abp-filter-parser-cpp/issues/27
