### ISSUE TITLE
Rocket chat login button not appearing

### ISSUE THREAD

**Issue by egferro** [brave/browser-laptop#14775]
### Description

In brave the rocket chat login button does not appear, so it is impossible to sign in. With chrome it appears and everything runs fine.

BRAVE Version: 0.23.31
Windows 10. 

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by snyderp** [comment]
I'm not able to recreate this in the beta

Ex: https://open.rocket.chat/home
