### ISSUE TITLE
Choon.co songs not playing

### ISSUE THREAD

**Issue by songproducer** [brave/browser-laptop#14789]
https://choon.co songs don't play.

### Steps to Reproduce
  1. Goto the above link
  2. Try to play a track
  3. Enjoy the silence

**Actual result:**
No music plays

**Expected result:**
Music should play

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.39
-- | --
V8 | 6.7.288.46
rev | 3ee14b0
Muon | 7.1.6
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@songproducer works great for me... do you have fingerprinting blocked? I have the default setting of `Block 3rd Party Fingerprinting`. Here are my settings (default settings):
![screen shot 2018-07-22 at 1 29 45 am](https://user-images.githubusercontent.com/4733304/43043760-c057b814-8d4e-11e8-9e3d-34bad07379f7.png)

**Comment by bsclifton** [comment]
Closing as the work-around above fixes the issue. @songproducer I suspect you have the global setting set to `Block all fingerprinting`. You can try setting to the default of `Block 3rd Party Fingerprinting`
![screen shot 2018-07-23 at 1 09 11 pm](https://user-images.githubusercontent.com/4733304/43100275-add4520c-8e79-11e8-8dd8-778b48e8d4f3.png)

**Comment by songproducer** [comment]
Mysteriously it's working! Sorry about this.
