### ISSUE TITLE
LastPass plugin reports error contacting the server

### ISSUE THREAD

**Issue by JohnJKerr** [brave/browser-laptop#14787]
### Description
Since the latest update the LastPass plugin now reports an error connecting to the server on every other click of the icon and it also doesn't seem to be filling forms by clicking the inline matched passwords (need to click into the plugin and select autofill).

### Steps to Reproduce
  1. Click LastPass plugin icon
  2. Message "An error occurred while attempting to contact the server. Please check your Internet connection." is displayed

**Actual result:**
![image](https://user-images.githubusercontent.com/14330766/42953873-4037cfca-8b73-11e8-967f-6d5676bba512.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/14330766/42953942-63191d00-8b73-11e8-9830-8ada3412aa36.png)

**Reproduces how often:**
50% of the time - every other click of the plugin icon.

### Brave Version

**about:brave info:**
 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
I've tried logging in/out of the LastPass, restarting the browser, disabling/re-enabling the plugin and I still receive that error on every other click. The issue only started after updating to 0.23.39 this morning. LastPass plugin version is 4.13.0.0. The plugin is still usable.

**Comment by eljuno** [comment]
Hi @JohnJKerr , first lets check if you have _Site isolation_ enabled under Preferences > Security. If you have that setting enabled, it may cause an issue with some extensions #12612.

**Comment by JohnJKerr** [comment]
Hey @eljuno, thanks so much for the link - that seems to have resolved the issue. Apologies for raising an issue, I did search for existing issues but didn't realise it was related to strict site isolation so I missed the one you have linked. Thanks again.
