### ISSUE TITLE
Submenus on bookmarks toolbar can expand beyond max height

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1479]

**Comment by bbondy** [comment]
This is due to the offset specified, I think we need to adjust the max height in code to fix this.

**Comment by cezaraugusto** [comment]
@bbondy can't reproduce here. The menu stops at the same height as the top level bookmark folder. Is it still happening for you?

**Comment by bbondy** [comment]
I fixed this a while ago thx for finding.
