### ISSUE TITLE
When installing Brave on linux, you must change the mint download to xenial for it to get the repo 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14799]
When installing Brave, you must change the repo to Xenial for it to find it on Linux Mint

After it finds it, it downloads the following version:

Name | Version
-- | --
Brave | 0.23.39
V8 | 6.7.288.46
rev | 3ee14b0
Muon | 7.1.6
OS Release | 4.15.0-29-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

Cross posting from https://github.com/brave/brave-browser/issues/621 logged by @Xenios91

**Comment by bsclifton** [comment]
@Xenios91 can you please try again? I pushed the latest release on Linux again. Perhaps there was an issue when doing our last release. I verified this one looks good 😄

**Comment by dlfisher** [comment]
I got an error trying to install Brave on Linux Mint Tara with a Forbidden 403 when trying to perform apt-get update. I tried adjusting the versions of Linux mint down until I got to
brave-tara.list to
deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt serena main
and this worked.

**Comment by proea** [comment]
> I got an error trying to install Brave on Linux Mint Tara with a Forbidden 403 when trying to perform apt-get update. I tried adjusting the versions of Linux mint down until I got to
> brave-tara.list to
> deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt serena main
> and this worked.

i have the save problem!

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser

**Comment by leoossa** [comment]
@bsclifton please can you add 'tara' to  which is Mint 19 codename?
https://github.com/brave/browser-laptop/blob/13808645ef50b667bb373084c238490625925388/tools/upload_to_aptly#L10
otherwise I had to change file `/etc/apt/sources.list.d/brave-browser-release-tara.list`
and replace
`deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ tara main`
to
`deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main`

Thank you.
