### ISSUE TITLE
Permission denied on rpm repo

### ISSUE THREAD

**Issue by Tux** [brave/browser-laptop#14793]
https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/
→
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>89A273E4D40094F6</RequestId>
  <HostId>
    2l8atNWxRM4XEwAvgG4r90SZm/rhdVQjujtiqSBwHCO9URfbgHR9l51FyhCyzWeIQ6l3Yx4l0kQ=
    </HostId>
  </Error>
```

**Comment by bsclifton** [comment]
@Tux do you have more info? What distro are you running? (Fedora?)

I'm assuming you followed the steps at:
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

This is the response you're getting when doing `dnf install brave` or similar?

**Comment by Tux** [comment]
@bsclifton I run SUSE, both TumbleWeed and 42.3
```
# zypper ref
:
Repository 'Vivaldi' is up to date.
Permission to access 'https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media' denied.
Abort, retry, ignore? [a/r/i/...? shows all options] (a): i
Abort, retry, ignore? [a/r/i/...? shows all options] (a): i
Do you want to disable the repository brave-rpm-release permanently? [yes/no] (no):
Skipping repository 'brave-rpm-release' because of the above error.
Repository 'di-Leap_42.3' is up to date.
:
Some of the repositories have not been refreshed because of an error.
#
```
So, I didn't even come to trying to install. Just refreshing the repo's (or visiting the repo in a browser) already fails with not allowed.

**Comment by bstin** [comment]
For reference of anyone searching. This issue seems to happen on opensuse.  The solution seems to be to edit: `/etc/zypp/repos.d/brave-rpm-release.repo`

and change the line:
`type=rpm-md`
to 
`type=yast2`

**However**, it seems that this must be done on each reset, since it defaults back to rpm-md. Not sure why this is happening, however it is a partial solution for anyone googling this issue.

**Comment by euneuber** [comment]
OpenSuse 15 here, same error, @bstin 's sulution works but this is NO permanent solution.

Please fix this!

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
