### ISSUE TITLE
Brave thinks I don't have enough BAT in the wallet. But it's not true

### ISSUE THREAD

**Issue by Alino** [brave/browser-laptop#14792]
![image](https://user-images.githubusercontent.com/763194/43012867-88f25170-8c47-11e8-9449-675b28d50e78.png)

MacOS 10.13.6
Brave 0.23.39

**Comment by NumDeP** [comment]
In the Add funds to your Brave Wallet - My BAT shows figures but the USD is (0.00 USD)

Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 4.12.14-lp150.12.4-default 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by bsclifton** [comment]
Closing as Brave Payments is deprecated in favor of Brave Rewards

The new version of Brave is now available via https://brave.com/download
