### ISSUE TITLE
pinned tabs don't load correctly on new windows

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#148]
Ideally the pinned tab should literally move from window to window and maintain state, but that will require guest view from #137 but right now if you open a new window the page doesn't load correctly
Steps to reproduce:
1. Open cnn.com
2. Pin the tab
3. Open a new window
The pinned tab will be missing css, etc...

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by bridiver** [comment]
I still see an issue with Facebook
After pinning tab
![fb1](https://cloud.githubusercontent.com/assets/34129/15331234/3be565c4-1c15-11e6-8f63-67926942ba72.png)
Pinned tab in new window
![fb2](https://cloud.githubusercontent.com/assets/34129/15331233/3bcdd4ea-1c15-11e6-8e8a-8fd5b43e4a4b.png)

**Comment by luixxiul** [comment]
Um, on Windows 10 it cannot be reproduced. I pinned facebook.com and opened a new window, but pinned facebook was displayed correctly. OS X only bug maybe?

**Comment by bridiver** [comment]
fixed by https://github.com/brave/browser-laptop/commit/6e307bc745e308dcc70c66df068ec0d76bc12daf
