### ISSUE TITLE
nytimes short links crash in tor tabs

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14806]
### Steps to Reproduce

1. Open tor tab
2. Open https://t.co/5LI7kjOzRn
3. Wait 30 seconds

**Actual result:**
Crash
`[1:1:0100/000000.958496:ERROR:broker_posix.cc(43)] Invalid node channel message`

**Expected result:**
No crash

**Reproduces how often:**
always

### Brave Version
```
Brave: 0.23.70 
V8: 6.8.275.23 
rev: e63c7804ea4850229904d4dc991143e1ebeabb51 
Muon: 8.0.1 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.8 (git-99f9816efa08ab83) 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.68
```

Reproduced on MacOS by @LaurenWags 
Reproduced on Windows 10 by @srirambv 

**Reproducible on current live release:**

cc @riastradh-brave @darkdh @kjozwiak @bsclifton @GeetaSarvadnya

**Comment by darkdh** [comment]
fixed in https://github.com/brave/muon/commit/0cf4424105343651b994108c1e675361958739f1
muon build 8.0.2
