### ISSUE TITLE
Sync is absent when building Brave from source

### ISSUE THREAD

**Issue by alecbcs** [brave/browser-laptop#14800]
### Description
Hi everyone, I'm the package maintainer for Brave on Solus. When building the application from source it appears that sync isn't installed correctly. When launching the application Brave gives the error `"Could not load background script 'content/scripts/sync.js'"`.

### Steps to Reproduce
1. Clone the browser-laptop repository
2. `npm install`
3. `CHANNEL=dev npm run build-package`

**Actual result:**
`"Could not load background script 'content/scripts/sync.js'"`

**Expected result:**
The `sync.js` file should be present to enable Brave Sync.

### Brave Version

 Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 4.17.6-82.current 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
Are there any other steps when building Brave that we may have forgotten which are required to enable Brave Sync? [Here](https://dev.solus-project.com/file/data/ddsvbyvkv6qqrupxofro/PHID-FILE-yyheotqbtowhkuarpo2s/package.yml) is the package.yml file that is used to build Brave from source on Solus. Thanks everyone in advance for your time.

**Comment by bsclifton** [comment]
@alecbcs it may be that the post install (after running `npm install`) hook didn't fire. Can you please try running this?
```
npm run postinstall
```

This should install the tor requirements along with the sync client. If you wanted to only install the sync client, you can do so by running:
```
npm run download-sync-client
```

**Comment by alecbcs** [comment]
@bsclifton thank you very much! Running `npm run postinstall` seems to have fixed the issue.
