### ISSUE TITLE
Download Delete button click is causing the browser hang

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14805]
### Description
When user download two or more than 2 .exe files simultaneously, upon click on cancel and delete download is causing the browser hang

### Steps to Reproduce

  1. Open Brave with clean profile
  2. Open a New Private tab with Tor or any Normal tab 
  3. If its tor tab wait until tor gets connected successfully
  4. Enter the Url  "https://github.com/brave/browser-laptop/releases" in the tor tab
  5. Click on any .exe file and click on save button in the Save as dialog
  6. Repeat the step 5 again and observer that two exe files are getting downloaded
  7. When the download is in progress, click on Cancel icon and cancel the download for 1st and 2nd .exe files (step 5 and step 6 download file)
 8. Click on 'Delete Download' ->OK  button
 
**Actual result:**
Browser is getting hanged after clicking the OK button 
![download delete button click causing browser hang](https://user-images.githubusercontent.com/38657976/43071754-5ceb904a-8e91-11e8-8cde-1252c6e39bfc.gif)

**Expected result:**
The browser should not get hang

**Reproduces how often:**
100%

### Brave Version
0.23.70
**about:brave info:**
 
Brave: 0.23.70 
V8: 6.8.275.23 
rev: e63c7804ea4850229904d4dc991143e1ebeabb51 
Muon: 8.0.1 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.68

**Reproducible on current live release:**
Yes

**Comment by GeetaSarvadnya** [comment]
@bsclifton @kjozwiak @alexwykoff Tested the defect on Live Release found issue is reproducible on Live version as well.

**Comment by btlechowski** [comment]
Not reproducible on Ubuntu 17.10. Brave v0.23.72

**Comment by kjozwiak** [comment]
Removing the `release/blocking` as this isn't a new regression and is currently present in `0.23.39` which is the release that's currently live.

**Comment by jumde** [comment]
Not able to repro with: https://github.com/brave/muon/commit/4504af1ad2a704729365f0bbab821c00ea357008


![out](https://user-images.githubusercontent.com/1903815/43473575-65b96b24-94a5-11e8-9d9e-89f842d38478.gif)

**Comment by bsclifton** [comment]
Should be fixed with our next build... if not, let's push back to Release 5

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.74 b508fa7
* Muon 8.0.4
* libchromiumcontent 68.0.3440.84
