### ISSUE TITLE
Brave restarts instead of quit when there is a pending update

### ISSUE THREAD

**Issue by Jimmar** [brave/browser-laptop#14803]
### Description

If there was a pending update to be installed and you qui the browser, it'd instead apply the update and restart.

### Steps to Reproduce

  1. have a pending update ready
  2. quit the browser [Exit]
  3. wait a bit, it'll apply the update and start again

**Actual result:**

Browser restarts

**Expected result:**

Browser quits

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

0.23.39

**Reproducible on current live release:**

yes

**Comment by srirambv** [comment]
Dupe of https://github.com/brave/browser-laptop/issues/9169
