### ISSUE TITLE
ETH Wallet is hidden as an extension

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14819]
ETH Wallet shouldn't be visible in the extensions preferences panel or in the extensions area in the top right of the browser.

**Comment by flamsmark** [comment]
Done! <3

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
