### ISSUE TITLE
Fully implement UI design for ETH Wallet

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#14818]
Additional work is needed to bring the ETH Wallet UI in line with @bradleyrichter's designs.

**Comment by petemill** [comment]
## Items that appear to be remaining:
- [ ] **Fund Brave Wallet action**: not implemented yet, but decision has been made to switch to Send tab with pre-fill brave wallet address
- [ ] **New ETH wallet action:** UI for adding wallet not implemented, no concept for that as far as I can tell
- [ ] **Backup Wallet action:** not implemented, no concept as far as I can tell
- [ ] **Off / On switch:** done, overlaid on top of iframe
- [ ] **"Off" page content:** not done
- [ ] **"Enable MetaMask" button:** not implemented but could be accomplished with static-positioned overlay on top of iframe
- [ ] Icons via @rossmoody and @petemill
- [ ] Button states @petemill
- [ ] Alignment / style tidy @petemill

## Info needed:
- Backup wallet action?
- Enable MetaMask action? What does it display if already enabled? Should be toggle instead?
- New Eth wallet action - no spec

**Comment by cezaraugusto** [comment]
after https://github.com/brave/meteor-dapp-wallet/pull/1 together with previous work made by Slava these are the updated remaining items:

- [ ] "Enable MetaMask" switch

note that the PR should match the below spec:

<img width="999" alt="screen shot 2018-07-31 at 6 56 41 pm" src="https://user-images.githubusercontent.com/4672033/43489473-88288192-94f3-11e8-9b18-ab6a57cca3d3.png">

**Comment by flamsmark** [comment]
What's the plan for the MetaMask button?

**Comment by tomlowenthal** [comment]
Looks like the MetaMask button is now clickable but doesn't do anything?

**Comment by tomlowenthal** [comment]
Yes, this is the correct behavior.
