### ISSUE TITLE
We want to modify the default password manager in brave browser.

### ISSUE THREAD

**Issue by rain3k** [brave/browser-laptop#14811]
### Description
We want to modify the default password manager in brave browser.
but we can't find source.....
is it impossible???

and we saw other 3th party password manager in brave browser. (one password...)

how to make 3th party password manager....

**Comment by bsclifton** [comment]
Hi @rain3k 

The default password manager is found at `about:passwords`. The source for this is located here:
https://github.com/brave/browser-laptop/blob/87d855e100c6a8ab6e61ff0c1b7d437403572e70/js/about/passwords.js

Modifying some of the behavior though is not trivial. You'll notice the React component (which gets [bound to the html page inside the Brave extension](https://github.com/brave/browser-laptop/blob/11a2bc4849eade05eec5ba603be8298684aee64e/app/extensions/brave/about-passwords.html)) uses IPC (inter-process-communication) to handle events

The events are raised (emitted) by the underlying engine (Muon) as the user interacts with a site. You can find the source for that here:
https://github.com/brave/muon

When searching that C++ code, you'll notice events being emitted. These events get picked up in the `browser-laptop` code in the above page (`about:passwords`) but also for prompting the user, like "Would you like to save this password?". Some of that logic can be seen in the passwordManagerReducer:
https://github.com/brave/browser-laptop/blob/76de11f88abf74643112a2f6cb90baf785b087f6/app/browser/reducers/passwordManagerReducer.js

**Comment by bsclifton** [comment]
If you're wanting to have your own password manager, you might look at existing extensions which are open source... [such as bitwarden](https://github.com/bitwarden/browser). We will be moving away from the Muon codebase soon in favor of a fork of the Chromium UI (Brave Core).  When that lands (next few months), we should have full extension support. You could get started right now by making a new extension and getting it work in Chrome/Chromium. By the time you have something working, Brave Core may be released
