### ISSUE TITLE
Browser continues to crash on dailymail.co.uk site/s

### ISSUE THREAD

**Issue by NumDeP** [brave/browser-laptop#14810]
Have you searched for similar issues? Yes. It's also been reported a couple times in the past but the issue seems to have crept back. It may also be similar to this #14806

### Description
Simply opening the [dailymail.co.uk](http://www.dailymail.co.uk) website crashes the browser

### Steps to Reproduce
Clicking on any link related to the site should crash it

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
~~~
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 4.12.14-lp150.12.4-default 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
~~~

### Additional Information
Here are some links from the community from the previous occasions:

- https://community.brave.com/t/dailymail-co-uk-crashes-brave-browser/11526
- https://community.brave.com/t/dailymail-co-uk/1797
- https://community.brave.com/t/daily-mail-link-causes-browser-to-crash/2179

**Comment by bsclifton** [comment]
Closing as `wontfix`. I believe you'll have a better time with the new developer channel release (which I believe you've tried 😄)
https://brave.com/download-dev

If you still encounter the problem with the new version of Brave, please let us know / create an issue here:
https://github.com/brave/brave-browser/issues

Thanks 😄
