### ISSUE TITLE
Finalize text for ETH Wallet initial notice

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#14817]
On the ETH Wallet preferences pane, a few paragraphs & bullets should explain that ETH Wallet is separate and different from other payments/ledger systems

**Comment by tomlowenthal** [comment]
Here's the additional text that needs to go on the end:
> ETH Wallet is meant for people who are already familiar with cryptocurrencies in general, and Ethereum in particular.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
