### ISSUE TITLE
double scroll bar on about:preferences#ethwallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14828]
### Description
After adding an account a double scroll bar displays on about:preferences#ethwallet. 

### Steps to Reproduce

  1. Build and run PR for ethWallet. (I launched with ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging )
  2. Enable ethWallet and restart. (if using above env variables, close, verify geth isn't running, and launch from terminal with env variables)
  3. Add an account (I used the ETH extension icon since the UI to do this within about:preferences#ethwallet doesn't work).

**Actual result:**
After adding an account a second scroll bar appeared.
![dblscrollbar](https://user-images.githubusercontent.com/28145373/43156766-02becd36-8f49-11e8-876d-890fc6575194.gif)

**Expected result:**
At most one scrollbar should be present

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
eth-wallet PR (14734)

**Reproducible on current live release:**
n/a

**Comment by Slava** [comment]
I pushed a fix ccf0602e0b8aaa4529b1afa122dbe62c1684c737

Let's retest on different platforms with different settings (mostly concerned about windows)

**Comment by GeetaSarvadnya** [comment]
Not seeing this double scroll bar issue on Windows x 64. Seems it's only mac specific issue

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
