### ISSUE TITLE
BAT is enabled by default in ETH Wallet

### ISSUE THREAD

**Issue by flamsmark** [brave/browser-laptop#14821]

**Comment by flamsmark** [comment]
Resolved in https://github.com/brave/meteor-dapp-wallet/commit/5c0dbcc1e8b41b6d7b54c30b5600ba3e181f0e28

**Comment by kjozwiak** [comment]
@flamsmark mind adding some more information if this need verification? If you can confirm this has been fixed, lets mark this as `QA/no-qa-needed`.

**Comment by tomlowenthal** [comment]
Test plan
- Under "Contracts" tab, BAT is listed as a custom token.
- Accounts which have BAT show a BAT icon on the "Wallets" page.
