### ISSUE TITLE
Back button getting large when scrolling up when already at top of screen

### ISSUE THREAD

**Issue by joelwass** [brave/browser-laptop#14829]
I couldn't find this issue in current open issues, but it's similar to https://github.com/brave/browser-laptop/issues/14785 but only only happens when scrolling vertically when you're already at the top or bottom of the page.

### Description

It's pretty easy to describe in code. Basically, the back/forward button is growing when it shouldn't be, i.e. when i'm scrolling vertically when i'm already at the top or bottom of the page.

```
ipc.on('scroll-touch-edge', () => {
      if (trackingFingers) {
        if (!isSwipeOnRightEdge && deltaX > 0) {
          isSwipeOnRightEdge = true
          isSwipeOnLeftEdge = false
          time = 0
          deltaX = 0
        } else if (!isSwipeOnLeftEdge && deltaX < 0) {
          isSwipeOnLeftEdge = true
          isSwipeOnRightEdge = false
          time = 0
          deltaX = 0
        }
      }
    })
```
This chunk of code is the issue, it currently doesn't check to see if you're at a top or bottom edge, but rather fires this event if you're at any edge at all and scrolling. So when I'm trying to scroll up, but I'm already at the top of the page, it will inaccurately show the back button (or forward button) grow bigger or smaller. Attached is a gif

![bug1](https://user-images.githubusercontent.com/7344422/43156963-95b0c07c-8f49-11e8-9474-445434ac3ccc.gif)

### Steps to Reproduce

  1. Open a new tab in brave
  2. Navigate to a new url (so the back button is enabled)
  3. Scroll slightly as if you're trying to swipe back (on a trackpad) to a previous page (this breaks the seal of the back button growing or not)
  4. Scroll up when you're already at the top of the page

**Actual result:**

See above gif

**Expected result:**
Expected result is for the back (or forward) button to not grow when scrolling vertically at the top or bottom of a page.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**

Yes

**Comment by darkdh** [comment]
fixed by https://github.com/brave/browser-laptop/commit/69851d114a327b3bfefab0ab7ba9649b7b5a4b1a

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.203 16c2c19
* Muon 8.1.2
* libchromiumcontent 69.0.3497.72
