### ISSUE TITLE
Certain stories are getting blocked on Breitbart.com website due to Ad blocker

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14837]
### Description
Certain stories are getting blocked on Breitbart.com website due to Ad blocker

### Steps to Reproduce

  1. Open brave 
  2. Open the website "Breitbart.com"
  
**Actual result:**
Certain stories are blocked due to Ad blocker 
https://drive.google.com/open?id=1ggJtESx-ODDk7Svl8DN-jYWO4p4WldCE

**Expected result:**
Content should not be blocked

**Reproduces how often:**
Yes

### Brave Version
0.23.39
**about:brave info:**

Brave: 0.23.39 
V8: 6.7.288.46 
rev: a38be75ccb0f699f507b66c4d44b3b21d1677e25 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
Issue is reported by Community:
https://community.brave.com/t/stories-getting-blocked/28326/3

cc @bbondy

**Comment by rebron** [comment]
Closing, marking as invalid. Those stories are actually ads and not content.
