### ISSUE TITLE
Ether Text moves to next line once prod network is connected 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14832]
### Description
Ether Text moves to next line once prod network is connected 

### Steps to Reproduce

  1. Build from #14734 
  2. Enable ETHWallet
  3. Wait for network to sync, Ether text in Balance moves down to next line before it lists other currencies
 
**Actual result:**
![ehter](https://user-images.githubusercontent.com/17010094/43167996-9adcb6c6-8f69-11e8-8fd6-11501030482c.gif)

**Expected result:**
Should not change text colour from Orange to White and should remain on the same line

**Reproduces how often:**
100%

### Brave Version
#14734 

**Reproducible on current live release:**
N/A

**Comment by Slava** [comment]
The "pre-connected" UI has been removed. This seems to be fixed.
