### ISSUE TITLE
geth process doesn't quit after closing Brave

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14831]
### Description
After closing Brave I would expect that the geth process would quit, but it doesn't.

### Steps to Reproduce

  1. Build and run PR for ethWallet. (tried both with and without env var for ropsten)
  2. Enable ethWallet and select No from the restart prompt. 
  3. Close Brave. Launch again (using env variables if you did earlier).
  4. After several minutes (or hours) of attempting to sync, close Brave.
  5. Open Activity Monitor.

**Actual result:**
geth process is still running in Activity Monitor.

**Expected result:**
geth process should not be running, I closed Brave.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
eth-wallet PR

**Reproducible on current live release:**
n/a

### Additional Information
@flamsmark also experienced this issue

**Comment by kjozwiak** [comment]
You'll also noticed that `geth` will keep pulling the latest blocks when it's running after Brave has been closed/terminated. Example:

```
INFO [07-31|16:34:44.838] Imported new block headers count=2 elapsed=5.304ms number=3747415 hash=950962…2ccecf ignored=0
process exited with code 0
Kamils-MBP:browser-laptop kjozwiak$
Kamils-MBP:browser-laptop kjozwiak$
Kamils-MBP:browser-laptop kjozwiak$
Kamils-MBP:browser-laptop kjozwiak$
INFO [07-31|16:38:40.704] Imported new block headers count=2 elapsed=5.374ms number=3747425 hash=0ad0dc…0426d7 ignored=0
INFO [07-31|16:39:09.884] Imported new block headers count=2 elapsed=5.516ms number=3747427 hash=690b5c…1c9be0 ignored=0
INFO [07-31|16:39:38.013] Imported new block headers count=2 elapsed=5.043ms number=3747429 hash=670425…eececd ignored=0
INFO [07-31|16:41:32.926] Imported new block headers count=2 elapsed=5.685ms number=3747431 hash=0cad5f…3346b9 ignored=0
INFO [07-31|16:42:01.023] Imported new block headers count=2 elapsed=5.299ms number=3747433 hash=7560a5…6fe42c ignored=0
INFO [07-31|16:42:33.649] Imported new block headers count=2 elapsed=5.051ms number=3747435 hash=39d15c…35b74a ignored=0
INFO [07-31|16:43:16.149] Imported new block headers count=2 elapsed=5.332ms number=3747437 hash=c490c7…7679fd ignored=0
INFO [07-31|16:44:09.264] Imported new block headers count=2 elapsed=5.402ms number=3747439 hash=170f0b…511f46 ignored=0
INFO [07-31|16:44:57.523] Imported new block headers count=2 elapsed=5.211ms number=3747441 hash=6a5052…31d776 ignored=0
INFO [07-31|16:45:35.370] Imported new block headers count=2 elapsed=4.803ms number=3747443 hash=07ba46…df96ca ignored=0
INFO [07-31|16:46:09.463] Imported new block headers count=2 elapsed=5.595ms number=3747445 hash=3125a8…5d1344 ignored=0
```

**Comment by ryanml** [comment]
Should be fully addressed as of latest commit: https://github.com/brave/browser-laptop/pull/14734/commits/a460c9bee20b33aa6c4274fbae57d7823f09c217
