### ISSUE TITLE
Zoom resets when navigating back or forward

### ISSUE THREAD

**Issue by petru** [brave/browser-laptop#1483]
Hey.

Just installed Brave 0.9.2 on Windows 10 64-bit and it looks exciting! I have, however, noticed a bug.

So I reduce the zoom to 90% (reddit's text is huge by default) and click a link. The zoom on the newly opened page is 100% and when I navigate back, it's also 100%. However, the zoom figure under the hamburger menu is still 90%.

**Comment by bradleyrichter** [comment]
@petru this one is landing this week. Give it a try on Friday...
