### ISSUE TITLE
Brave Browser duplicating folders on the bookmarks toolbar

### ISSUE THREAD

**Issue by AgeOfMarcus** [brave/browser-laptop#14847]
### Description

When creating a new folder on the bookmarks toolbar, after opening a new tab, and browsing for a bit, brave duplicates the folder.

### Steps to Reproduce

  1. Create a new folder in the bookmarks toolbar
  2. Open a new tab / wait a bit / restart the browser
  3. Folder may be duplicated

**Actual result:**
Two of the same folders.

**Expected result:**
Only one of the folders.

**Reproduces how often:**
Not sure, happens usually when I'm not paying attention.

### Brave Version

**about:brave info:**

 
Brave: 0.23.31 
V8: 6.7.288.46 
rev: 3148acef36dba0fce89108638bb27927c4937f90 
Muon: 7.1.5 
OS Release: 4.16.0-parrot16-amd64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**

This is the most recent release for my OS, as far as I'm aware.

**Comment by bsclifton** [comment]
@AgeOfMarcus I haven't been able to reproduce this - are you able to reliably reproduce? Also, I'm curious: do you have sync enabled?

**Comment by gloc-mike** [comment]
I am having a similar issue when editing bookmarks. I add a new folder for example, then drag a previously saved bookmark into the newly created folder, and, mysteriously, an exact duplicate of the folder just created with copied links suddenly appears in the folder tree. I do not notice when it actually happens but it is happening while I am editing the bookmarks.
