### ISSUE TITLE
how to change node version

### ISSUE THREAD

**Issue by rain3k** [brave/browser-laptop#14846]
this souce is used node 7.9 version 

i can check node version when running this program 

i want to change node 10.7 version

*i already installed  node 10.7 version at my computer

plz help me.

**Comment by bsclifton** [comment]
Hi @rain3k,

As you've noticed, the version of Node.js that is used in Brave is 7.9.  However, this is the version of Node that is compiled into Muon (our fork of Electron). If you are just wanting to run scripts locally, you're fine to have a different version of Node installed (ex: I have `v8.11.2` and it works fine)

If you want to change the version of Node associated with Muon, that's going to be a lot tougher.  If you did want to attempt that, you can start by checking out [browser-laptop-bootstrap](https://github.com/brave/browser-laptop-bootstrap) ([see the wiki for build steps](https://github.com/brave/browser-laptop-bootstrap/wiki)). From there, you can attempt to update the Node dependency that shows up under the vendor folder (and then work through the compile errors)
