### ISSUE TITLE
Need option to permanently disable "Are you ready to support the sites you use most?" messages so can happily use Brave in QubesOS disposable vms without being continually harassed by these prompts.

### ISSUE THREAD

**Issue by trackroute** [brave/browser-laptop#14849]
### Description
No setting appears to exists to permanently disable "Are you ready to support the sites you use most?" prompts. This makes running brave in Qubes OS disposable VMs extremely annoying because there is a constant barrage of "Are you ready to support the sites you use most?" prompts.

### Steps to Reproduce
  1. Install Brave into a Qubes OS template (clone an existing template if necessary).
  2. Setup dispvm based upon above template. Configure initial Brave defaults in this "*-dvm".
  3. Launch brave in dispvm.. soon thereafter receive "Are you ready to support the sites you use most?" prompt. Launch brave again (starts another dispvm).. shortly thereafter receive annoying prompt again.. etc, etc .. ad infinitum. 

These "Are you ready to support the sites you use most?" prompts are REALLY annoying in a QubesOS dispvm setup (where brave is launched in a clean disposable vm every time it is started). 

**Expected result:**
In my opinion there should be some way of permanently disabling the "Are you ready to support the sites you use most?" prompts to avoid unnecessarily harassing users who use brave in QubesOS dispvms.

### Brave Version

**about:brave info:**

 Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 4.14.41-1.pvops.qubes.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by bsclifton** [comment]
cc: @NejcZdovc @jasonrsadler
