### ISSUE TITLE
Lastpass login page not shown on clean profile

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14841]
### Description
Lastpass login page not shown on clean profile

### Test plan / Steps to Reproduce

  1. Install 0.23.72
  2. Enable Lastpass from extension
  3. Click on extension icon, shows Internet error unable to connect
  4. Close extension popup, console logs error 
```[7544:8104:0725/114251.439:ERROR:extension_function_dispatcher.cc(585)] Unknown Extension API - tabs.getAllInWindow
```
  5. Click extension popup again shows load spinner but nothing opens

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/43220858-1ed7dc8a-9019-11e8-8c51-56ed62858d1f.png)
![image](https://user-images.githubusercontent.com/17010094/43220863-22cd9f78-9019-11e8-9226-1fe563f2aa7b.png)
![image](https://user-images.githubusercontent.com/17010094/43220893-38f1e3ae-9019-11e8-937b-c5b83d24246c.png)

**Expected result:**
Extension should load

**Reproduces how often:**
100% on new profile
Reproduced on mac by @LaurenWags 

### Brave Version

**about:brave info:**

Brave|
--|--0.23.72
V8|6.8.275.24
rev|c3b1cac
Muon|8.0.2
OS Release|10.0.17134
Update Channel|Release
OS Architecture|x64
OS Platform|Microsoft Windows
Node.js|7.9.0
Brave Sync|v1.4.2
libchromiumcontent|68.0.3440.75

**Reproducible on current live release:**
No

### Additional Information
When lastpass is enabled on Beta and then enabled on release channel it shows correct login popup page. Issue happens only when trying on release channel
![image](https://user-images.githubusercontent.com/17010094/43220996-7fee1340-9019-11e8-9e3e-26ac064ab097.png)

**Comment by bsclifton** [comment]
Per @darkdh 
> https://developer.chrome.com/extensions/tabs#method-getAllInWindow
> the API has been deprecated

@jonathansampson has updated the LastPass extension to `4.15.2.5` which should resolve the issue 😄 👍  It may take a while for the change to get picked up on existing installs. Please re-open if you're not seeing the new version 😄

**Comment by darkdh** [comment]
CORB error fixed by https://github.com/brave/muon/pull/618/commits/3c654ffc3ae1b3ce689c306d2b0c8d90f3d7bdc2
API error fixed by https://github.com/brave/muon/pull/618/commits/4cd780d6ec7991d0d0132010a783aef5e3be9de7

will be available in muon 8.0.3

**Comment by bsclifton** [comment]
Re-opening as issue may have been re-introduced. @darkdh can address this soon with a new Muon

**Comment by darkdh** [comment]
<img width="1065" alt="screen shot 2018-08-28 at 12 14 22" src="https://user-images.githubusercontent.com/11330831/44747371-e0b26d80-aac1-11e8-8c9e-74a9f19eb027.png">
These two commits were left over when merging C68 into master

**Comment by kjozwiak** [comment]
Received a few +1 from #15109.

**Comment by darkdh** [comment]
fixed in muon 8.0.9

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.105 9a46f8f
* Muon `8.0.9`
* libchromiumcontent `68.0.3440.84`
* Verified no errors when opening the extension popup
* Verified able to login to Lastpass account 
* Verified able to autofill credential details
* Verified background page doesn't throw any error when using the password manager to autofill

**Comment by stellar6** [comment]
FIXED: tested on Win 10 x64
 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 

Verified no errors when opening the extension popup
Verified able to login to Lastpass account

**Comment by kjozwiak** [comment]
@stellar6 thanks for double checking! Really appreciate it! 👍

**Comment by NumDeP** [comment]
@kjozwiak this was posted an hour ago - https://community.brave.com/t/lastpass-still-not-working/31111
