### ISSUE TITLE
Wallet recovery key changed w/o notification

### ISSUE THREAD

**Issue by disfit** [brave/browser-laptop#14856]
As I mentioned yesterday in a comment on #13156 I noticed that my wallet recovery key has changed. Or maybe better that the wrong recovery key is shown. I have no idea when exactly the key that is displayed has changed but it was somewhere before 2018-06-22. I am not sure why I checked it then and made a copy of it, though it might have been because of my contribution being overdue. And I just did not have the time at that moment to look into it so only made a backup for later.

The displayed recovery key is radically different from the earlier one. Yesterday I mentioned that using the new displayed one did not work, but after trying again today, it did. (BTW it gives a USD amount instead of a BAT amount, while the account balance emphasizes BAT ... a bit inconsistent.)

But the same is true when I use my previous / old recovery key. After recovering the wallet with this old previous key, the displayed recovery key does not change to the old previous one. 

This confuses me to no end. It is of course possible to have two (or more) keys for one wallet, but I cannot see the need for that in this particular use-case. And if this is correct behavior it is important to tell users that so they do not get spooked by a change in the recovery key.

It is also possible that there are now two different but synced wallets. And that would also not make a lot of sense.

Since the wallet recovery with either key seems to work, or at least both report success, I do not know if this contributes to the issue of contributions not taking place. And if the recovery key change is deliberate than this is not a technical issue but a communication issue :-)

FYI: I have had wallet problems before, but those were related to the BTC to BAT conversion.

If there is anything I can help with, please let me know.

Brave: 0.23.39 
V8: 6.7.288.46 
rev: 3ee14b026f09d7d71c1985b4a9c9a11d78ab8f49 
Muon: 7.1.6 
OS Release: 4.15.0-29-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Comment by bsclifton** [comment]
@disfit thanks for the report 😄 [A while back](https://github.com/brave/browser-laptop/issues/13313), we did change the keywords that are used... basically switching from 16 words (niceware - which included some offensive phrases) to 24 shorter words (bip39)

Both sets of phrases should work- however, the new words won't work in older versions of Brave (versions before 0.22.x)
