### ISSUE TITLE
progress bar not always updating when pulling latest blocks/state

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14855]
### Description

When ETH Wallet starts pulling the latest blocks/state, you'll notice that the progress UI doesn't always get updated. You'll have to switch to another preference page and then switch back to ETH Wallet to see how much progress was made. (See example below)

### Steps to Reproduce

  1. build brave from #14734 & launch using `ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging`
  2. enable `ETH Wallet` from `about:preferences`
  3. once enabled, you'll notice that the progress UI isn't being updated
  4. switch into the Brave Payment wallet and switch back to ETH Wallet (you'll see progress)

Once you're connected to one of our nodes, you usually pull the changes within 2-3mins. However, the first time around I waited 10min without realizing it was already synced due to the progress not being updated correctly.

**Actual result:**

![eth](https://user-images.githubusercontent.com/2602313/43298785-7a4f901e-9125-11e8-97d6-aaf289c56be7.gif)

**Expected result:**

When the user is pulling the latest state from a node, the UI should be responsive and indicate the current progress. User shouldn't be guessing on the % that has already been completed.

**Reproduces how often:**

100% reproducible on a new profile when syncing the latest ETH blocks/state.

### Brave Version

**about:brave info:**

 
```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: 266ff39e07be7fa353769bb5e021a19c18e2bb98 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**

No, ETH Wallet hasn't been released so it's not in the currently released build.

**Comment by kjozwiak** [comment]
Labelled this as `release/blocking` as the progress bar is the only indicator that we currently have. With this not working correctly, it's a real pain to figure where were you exactly stand in the syncing process.

**Comment by LaurenWags** [comment]
Noticed that even leaving the page and coming back sometimes doesn't force this to update. From my terminal I know I'm pulling blocks but the UI doesn't tell me anything. It looks like I'm waiting since I see the 'Clock' icon not the cloud w/ arrow icon.

![screen shot 2018-08-05 at 3 49 58 pm](https://user-images.githubusercontent.com/28145373/43689370-8158e578-98c7-11e8-8984-0593cf36e51d.png)

**Comment by Slava** [comment]
I implemented 2s interval polling for the progress bar. Note that if geth hasn't received any new blocks, the progress bar won't move either. So it is very dependent on the last fetched block.
