### ISSUE TITLE
Last Pass, doesn't connect on Mac (Beta channel)

### ISSUE THREAD

**Issue by Tomatoshadow2** [brave/browser-laptop#14861]
Have you searched for similar issues? Yes

[Description of the issue]
Last Pass fails to connect to the server or fails to log me in. 

 Steps to Reproduce

  1. Open Brave Beta on Mac, have the Last Pass extension enabled. 
  2.Try to sign into Last Pass, will fail to connect to the server or will say can't log you in. 
  3. Repeating, just yields one of the two messages 

**Actual result:**
Fails to log in. 

**Expected result:**
Should log you in, without an issue. 

**Reproduces how often:**
100%

### Brave Version

 Brave: 0.23.70 
V8: 6.8.275.23 
rev: e63c7804ea4850229904d4dc991143e1ebeabb51 
Muon: 8.0.1 
OS Release: 17.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.68

**Reproducible on current live release:**
No

### Additional Information
Worked as expected a few weeks ago, updating my beta build, didn't help resolve the issue.

**Comment by bsclifton** [comment]
Possibly related to https://github.com/brave/browser-laptop/issues/14012

**Comment by Tomatoshadow2** [comment]
Yeah it is, I can add to that issue and close this one.
