### ISSUE TITLE
Warning Open: .../desktop-launch: line 176: de: command not found

### ISSUE THREAD

**Issue by wellington1993** [brave/browser-laptop#14863]
### Description
When open from terminal + snap at linux i've got this message:
`/snap/brave/27/bin/desktop-launch: line 176: de: command not found`

### Steps to Reproduce
  1. Snap install 
  2. at ubuntu
  3. from terminal
  4. Just open
  5. See the message

**Actual result:**
Only the messag, maybe slow to start:
`/snap/brave/27/bin/desktop-launch: line 176: de: command not found`

**Expected result:**
No message and fast start

**Reproduces how often:**
Every open

### Brave Version

```
Name | Version
-- | --
Brave | 0.23.31
V8 | 6.7.288.46
rev | 3148ace
Muon | 7.1.5
OS Release | 4.15.0-25-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103
```

**Reproducible on current live release:**
Yes

### Additional Information
-

**Comment by bsclifton** [comment]
+1 from @jian-leopoldo via https://github.com/brave/browser-laptop/issues/14661
> Hello, i´m a Ruby On Rails developer and i have a problem when the RoR trying to open a email preview in HTML on brave. 
> 
> My console show this error:
> /snap/brave/25/bin/desktop-launch: line 174: de: command not found
> 
> Brave Version : 0.23.19
> 
> My OS Infos: 
> Distributor ID: Ubuntu
> Description:  Ubuntu 16.04.4 LTS
> Release:  16.04
> Codename: xenial
