### ISSUE TITLE
Close button ["x"] on tabs disappears on last tab when tab bar is full

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-laptop#14864]
Have you searched for similar issues? We have received a lot of feedback and bug reports that we have closed as duplicates. Before submitting this issue, please visit our community site for common ones: https://community.brave.com/c/common-issues
Yes

### Description
If you have enough tabs open to fill the tabs bar, when closing the right-most tab (using the [x] button to close), the [x] doesn't appear on the tab that takes its place (new right-most tab) right away. Requires you to move the mouse around or click somewhere off the tab in order for it to reappear.

### Steps to Reproduce
  1. In fresh Brave window, open 12 new tabs (sites doesn't need to be loaded in any of them)
  2. Move mouse to the right-most tab on tab rail and click x to close the tab and don't move cursor 

**Actual result:**
Close button [x] doesn't appear until mouse is moved around a bit (doesn't seem to be any specific movement that causes it to display again).
Gif:
![xbutton](https://user-images.githubusercontent.com/3299098/43348663-13c50302-91b0-11e8-8fbe-94db30181ad2.gif)

**Expected result:**
Close button [x] appears right away

**Reproduces how often:**
Always

### Brave Version
Brave version info:
|Brave|0.23.39|
|V8|6.7.288.46|
|rev|a38be75|
|Muon|7.1.6|
|OS Release|6.1.7601|
|Update Channel|Release|
|OS Architecture|x64|
|OS Platform|Microsoft Windows|
|Node.js|7.9.0|
|Brave Sync|v1.4.2|
|libchromiumcontent|67.0.3396.103|

**Reproducible on current live release:**
Yes

### Additional Information
This was reported by a user on Community, but I had just started seeing this behavior myself.
Original report from user: https://community.brave.com/t/closing-tabs-when-tab-bar-is-full/28513

**Comment by rebron** [comment]
Closing. Fixed with brave-core.
