### ISSUE TITLE
Clicking 'Add to Pocket' Opens Saved Articles Instead

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14875]
### Description
A user of Brave has [recently reported](https://twitter.com/stshank/status/1024064307338698752) a potential issue with the Pocket extension. Once the user has authenticated, clicking the browser icon (to the right of the address bar) should add the current page to the user's saved articles list. In this user's case, the article isn't added, but the list of saved articles is displayed.

### Steps to Reproduce
1. Visit an online article
2. Click the Pocket browser action

**Actual result:**
Saved articles are displayed

**Expected result:**
Current article is added to saved articles

**Reproduces how often:**
N/A

### about:brave info:
![image](https://user-images.githubusercontent.com/815158/43439003-d802ca28-9445-11e8-87b4-2b6d195d6504.png)

**Reproducible on current live release:**
Yes

### Additional Information
The user has reported this issue on macOS. I was _unable_ to reproduce the issue on Windows.

**Comment by stshank** [comment]
Also, right-clicking on the extension icon doesn't do anything.

**Comment by joelwass** [comment]
Additionally, nothing happens when I click on the pocket icon when on github, and the following error displays in the console

```
Refused to frame 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/' because it violates the following Content Security Policy directive: "frame-src render.githubusercontent.com".
```

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
