### ISSUE TITLE
Various Problems on MacOS Mojave beta 5

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#14876]
### Description
A Brave user has recently installed a beta release of the macOS Mojave operating system. The user has reported a couple issues with Brave on this platform; they are enumerated below.

- Attempting to download files results in a crash ([source](https://twitter.com/stshank/status/1024171837771546625))
- Text selections cannot be copied from the webview ([source](https://twitter.com/stshank/status/1024168992238329857))

During testing, the user reported that the above issues were easily reproduced 100% of the time.

**Comment by bsclifton** [comment]
First issue already captured here:
Mojave: Crash when downloading any file #14346

Also Mojave related:
Mojave: Checkboxes are invisible #14348

**Comment by stshank** [comment]
I updated Brave and updated MacOS beta since the bug report, and I'm not having the copy or paste problems anymore.

**Comment by bsclifton** [comment]
Closing this issue as @stshank reports copy/paste issues not being present and the download crash is bring tracked with https://github.com/brave/browser-laptop/issues/14346
