### ISSUE TITLE
disabling nav scroll when content is horizontally scrollable.

### ISSUE THREAD

**Issue by TeoMorabito** [brave/browser-laptop#14871]
When I scroll horizontally on a website such as a calendar, scrolling sideways makes the page go back of forward in history.

If content is scrollable horizontally, nav scroll should be disabled, or at least a setting to disable it.

Using a retina macbook pro

@joelwass thank you for suggesting to open a new issue

**Comment by TeoMorabito** [comment]
Going into System Preference > Trackpad
and unchecking swipe between pages disables the swipe right and left gesture and thus disables the navigation swipe in brave.
(I am not able to swipe horizontally on a calendar so needed a way to disable it so it wouldn't go back and forth in the history)

This bypasses the issue, but doesn't fix the issue

**Comment by darkdh** [comment]
fixed by https://github.com/brave/browser-laptop/commit/69851d114a327b3bfefab0ab7ba9649b7b5a4b1a

**Comment by LaurenWags** [comment]
@darkdh could you provide test steps for this? I tried shrinking my window so that the content within it was horizontally scrollable (gif below) but that didn't work (swiping left/right still navigates thru tab history). Unsure if I'm testing this the correct way?

![horizscroll](https://user-images.githubusercontent.com/28145373/45038363-1958c680-b02f-11e8-8f91-ceb208e0db94.gif)

**Comment by darkdh** [comment]
use page like https://github.com/orgs/brave/projects/7 with long horizontal content and shrink the window and you can swipe as hard as you can.
The gif you are showing might be different problem that is short horizontal content and swipe from edge to edge

**Comment by darkdh** [comment]
with the fix:
![untitled](https://user-images.githubusercontent.com/11330831/45049645-16140980-b034-11e8-90bc-fb455ea4659a.gif)
current release :
![untitled](https://user-images.githubusercontent.com/11330831/45049742-68edc100-b034-11e8-8869-04055954574f.gif)

**Comment by LaurenWags** [comment]
Using site from https://github.com/brave/browser-laptop/issues/14871#issuecomment-418401566 and gifs from https://github.com/brave/browser-laptop/issues/14871#issuecomment-418468362 verified scrolling is improved with 0.23.205. cc @kjozwiak for a double check on macOS.

**Comment by kjozwiak** [comment]
Went through the original case that @darkdh mentioned in https://github.com/brave/browser-laptop/issues/14871#issuecomment-418401566 and ran into the issue right away using `0.23.107` 6f2fc65b3c7db0b260ad154fbef5919902495387  which is the current live release.

Using the following build on macOS 10.13.16 x64, I ensured that the above issue wasn't occurring using while using the different swipe settings under `about:preferences#advanced`:
 
* `0.23.206` 80a5ac134e251a9cb3565023e2447d6d7b4487a7 
* Muon: `8.1.5`
* libchromiumcontent: `69.0.3497.92`
