### ISSUE TITLE
Brave crashes after enabling ETH-Wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14877]
### Description
When running the ETH-Wallet PR (#14734) Brave is crashing after you enable the ethWallet in Preferences when using this commit https://github.com/brave/browser-laptop/commit/266ff39e07be7fa353769bb5e021a19c18e2bb98

### Steps to Reproduce

  1. Start fresh, remove node_modules and brave-development profile folder.
  2. Pull and build ETH-Wallet PR `git fetch origin pull/14734/head:eth-wallet` then `git checkout eth-wallet`
  3. Then do `npm install` followed by `npm run watch` 
  4. In a new window `ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging GETH_LOG=1 npm start`
  5. Navigate to about:brave to verify you are running the commit above
  6. Enable ethWallet in preferences.
  7. Say No on the restart. Close Brave, and launch with same command from line 4.

**Actual result:**
Brave icon appears in doc, but no windows open. Also, I get this in the terminal - seems as though the ethereum folder structure isn't being created.

```
Laurens-MacBook-Pro:browser-laptop laurenwagner$ ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging GETH_LOG=1 npm start

> brave@0.25.0 start /Users/laurenwagner/BraveDocuments/Dev2/browser-laptop
> node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/laurenwagner/Library/Application Support/brave-development/ethereum/geth/static-nodes.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at Object.module.exports.init (/Users/laurenwagner/BraveDocuments/Dev2/browser-laptop/app/extensions.js:624:8)
    at perWindowStateLoaded (/Users/laurenwagner/BraveDocuments/Dev2/browser-laptop/app/index.js:205:16)
    at Immediate.setImmediate (/Users/laurenwagner/BraveDocuments/Dev2/browser-laptop/app/index.js:195:24)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds
process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! brave@0.25.0 start: `node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.25.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/laurenwagner/.npm/_logs/2018-07-31T14_54_16_017Z-debug.log
```

**Expected result:**
Brave should be launched and previously open windows should be visible. No errors in terminal should display.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
PR 14734 commit https://github.com/brave/browser-laptop/commit/266ff39e07be7fa353769bb5e021a19c18e2bb98

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @kjozwiak and @btlechowski on macOS, Win

**Comment by Slava** [comment]
I think should be fixed in https://github.com/brave/browser-laptop/pull/14734/commits/b85dfa16ae78413d47b0ef76fd2e5971b2a5f44b
