### ISSUE TITLE
Error: Could not detect abi for version 8.0.3 and runtime electron

### ISSUE THREAD

**Issue by JC-Coelho** [brave/browser-laptop#14883]
### Error: Could not detect abi for version 8.0.3 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron.

Error emitted. Bufferutil.cc module does not compile. webpack: Compiled successfully message at end. Browser can be launched on two terminals as instructed.

### Build repository on Windows 10 according to guildelines

  1. Run npm install on cloned repository according to guidelines
  2.
  3.

**Actual result:**

Error emitted. Bufferutil.cc module does not compile. webpack: Compiled successfully message at end. Browser can be launched on two terminals as instructed.

**Expected result:**

No errors.

**Reproduces how often:**

Always.

### Brave Version

**about:brave info:**

0.23.39

**Reproducible on current live release:**

Yes.

### Additional Information

I would love to find out if it's possible to build your release of Brave browser without getting the error described. I've tried everything and only seem to be able to compile on Windows 10 I think, leaving out the "Bufferutil" module that refuses to not throw errors at compilation on my humble 32-bit laptop.

**Comment by JC-Coelho** [comment]
Error emitted. Bufferutil.cc module does not compile. webpack: Compiled successfully message at end. Browser can be launched on two terminals as instructed.

**Comment by JC-Coelho** [comment]
I've tried the updated version of electron and also updated node-abi. I also get a warning `..\src\addon.cpp(49): warning C4316: 'SHA3Hash': object allocated on the heap may
not be aligned 32 [H:\brave\node_modules\sha3\build\sha3.vcxproj]`. I now speculate this might have to do with **compiling on a 32-bit machine**. Specially since the error should concern the Chromium for Windows build. 

[https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#System-requirements](url) 

> A 64-bit Intel machine with at least 8GB of RAM. More than 16GB is highly recommended.

I think the module left out is optional. 

I don't believe in magic passes here. 
It still wants to run ok. I'm leaving this. Thank you.

**Comment by jpcima** [comment]
Same error here. I want to just make minor code changes and rebuild, but can't.

I know little of javascript in general, but I noticed:
It creates `node.h` and other headers in `~/.node-gyp/` which are not fully updated and creates this build error. I guess it's a consequence of a failure to detect "node-abi".

```
In file included from ../src/bufferutil.cc:7:
../node_modules/nan/nan.h:559:9: error: ‘async_context’ in namespace ‘node’ does not name a type
   node::async_context context;
         ^~~~~~~~~~~~~
```

How to solve this problem?

`Linux quad 4.16.18-rt11-1-rt #1 SMP PREEMPT RT Sun Jul 29 15:07:45 CEST 2018 x86_64 GNU/Linux`
nodejs 10.8.0, node-gyp 3.7.0, npm 6.3.0, electron 2.0.5

**Comment by JC-Coelho** [comment]
I'm on 32-bit Windows 10 and now building to the exact spec for beta testers. I always get this build error. It also reports the dependency is optional and the build succeeds. I'll have to try the full bootstrap installation sometime. I'll be testing with the packaged version on the meantime. It still seems to have similar problems i.e. mainly that a new tab easily crashes the browser on the startup script.

**Comment by JC-Coelho** [comment]
It seems NPM always updates the Node modules used for the build. It could be that a version conflict arises from here. Else I would speculate that building only the browser portion of the source without the bootstrap project cannot be a wholly successful endeavor. This since there will be conflicts no matter what.
