### ISSUE TITLE
navigator.mediaDevices.enumerateDevices() returns too much info

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14889]
## Test plan
See https://github.com/brave/browser-laptop/pull/14970

## Original issue description
STR:
1. cd `test/fixtures` and start a local server, ex: on port 8000
2. go to localhost:PORT/enumerate_devices.html

Actual result: shows a description of every media device

Expected result: behaves the same as in Chrome (no device descriptions are shown, only an opaque ID). 

Tested on MacOS, both master and current release (0.23.x).

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.79 51b49051a779f0db94fbcfd0df5faca781299ea0
• Muon 8.0.7
• libchromiumcontent 68.0.3440.84
