### ISSUE TITLE
ETH Wallet page does not resize nicely

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14891]
### Description
If you resize your browser window with the ethWallet page in Preferences displayed, you can see that the page does not display nicely - in particular buttons get cut off from display and sometimes you don't have a bottom scroll bar visible to indicate there's UI to the right that you can't see.

### Steps to Reproduce

  1. Navigate to the ethWallet page with ETH Wallet enabled.
  2. Resize the browser window so it is smaller.

**Actual result:**
![resizewindow](https://user-images.githubusercontent.com/28145373/43611673-e5a1ccea-9677-11e8-990e-5971d3cc53a0.gif)

**Expected result:**
Page display should resize nicely/indicate there's UI to the side that you can't see.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
n/a

**Reproducible on current live release:**
no

### Additional Information
cc @kjozwiak

**Comment by btlechowski** [comment]
It seems that the behavior changed a bit. Now the page is truncated. 

This is for 1366x768 resolution, which is used the most[1]

[1] http://gs.statcounter.com/screen-resolution-stats/desktop/worldwide


![image](https://user-images.githubusercontent.com/34715963/43548402-1a3cfc6c-95de-11e8-9ed4-72b8c359368a.png)

**Comment by Slava** [comment]
I pushed a fix ccf0602e0b8aaa4529b1afa122dbe62c1684c737

Let's retest on different platforms with different settings (mostly concerned about windows)

**Comment by Slava** [comment]
I made the panel responsive. It still has a limit, but now it will be much smaller than it was.

**Comment by Slava** [comment]
Closing this
