### ISSUE TITLE
Private Windows Reopen on Reopen Last Closed Window

### ISSUE THREAD

**Issue by CraigDamlo** [brave/browser-laptop#14898]
If you are doing a private window (with or without tor) after you close the window if you do a reopen last closed window it reopens the private tabs where you were when you closed.

**Comment by bsclifton** [comment]
Thanks for the report, @CraigDamlo - this is indeed an issue. This will be fixed as we move to [Brave Core](https://github.com/brave/brave-browser) (which is coming soon)
