### ISSUE TITLE
I am also getting same problem .how to solve it

### ISSUE THREAD

**Issue by jamesbell26** [brave/browser-laptop#14895]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by kjozwiak** [comment]
@jamesbell26 I'm going to close this as there's nothing here that we can use to help you. If you're still have an issue, please create a new bug but this time around try adding as much information as possible. You can follow the outline that you'll see when you click on `New Issue`. Example:

* Description
* Steps to reproduce
* Actual Results, Expected Results

etc...
