### ISSUE TITLE
ETH address doesn't fit within the "Send" modal

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14902]
### Description

When sending ETH, you'll notice that the address doesn't fit within the `Send` modal and ends up spilling onto the screen. The `Send` modal should be large enough to hold the entire address.

### Steps to Reproduce

  1. launch a version of brave that has ETH Wallet (currently using https://github.com/brave/browser-laptop/pull/14734/)
  2. enable `ETH Wallet` using `about:preferences#ethwallet` and restart the browser
  3. create a wallet and send over some funds (use a ropsten faucet for simplicity) 
  4. once the fund appear in the wallet, click on `Send` button
  5. fill out all the appropriate fields and click on `SEND`

You'll see the `Send` modal and notice that the address is spilling out of the modal.

**Actual result:**

<img width="542" alt="screen shot 2018-08-01 at 6 09 23 pm" src="https://user-images.githubusercontent.com/2602313/43553309-5d76a66c-95bc-11e8-9c5a-29c906c36a94.png">

**Expected result:**

ETH address shouldn't be spilling over. The `send` modal should be long enough to house an entire ETH address.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: 200494df265755df5a4d391a50f9cddabd5c1b1e 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

```
**Reproducible on current live release:**

Currently not reproducible in the latest release as this feature hasn't been released.

**Comment by Slava** [comment]
Made the modal wider
