### ISSUE TITLE
adding separation between Transfer Ether & Tokens, Copy address  & Show QR Codes buttons while on Main and Ropsten

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14900]
### Description

When clicking on wallets, you'll notice that the text for `Transfer Ether & Tokens`, `Copy address` & `Show QR Codes` buttons are not separated and is really hard to read.

### Steps to Reproduce

  1. launch Brave using https://github.com/brave/browser-laptop/pull/14734
  2. once launched, enable ETH Wallet via `about:preferences#ethwallet` & restart
  3. click on `New ETH Wallet` and click on `OK` (don't have to add a password)
  4. click on the wallet and you'll notice that the button text at the bottom isn't spaced correctly

**Actual result:**

<img width="1012" alt="screen shot 2018-08-01 at 3 38 37 pm" src="https://user-images.githubusercontent.com/2602313/43545127-0574aeb4-95a3-11e8-9d17-e470938a2bd2.png">

**Expected result:**

There should be some spacing between the text for the following three buttons:

* Transfer Ether & Tokens
* Copy address
* Show QR Codes

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: 200494df265755df5a4d391a50f9cddabd5c1b1e 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**

Currently not reproducible on the latest live release as this feature hasn't been released.

**Comment by srirambv** [comment]
This looks fine when connected to main net. Also the options shown for main net is different from testnet. Here's the options for main net
![image](https://user-images.githubusercontent.com/17010094/43600735-68cc9f60-9659-11e8-97cf-fe39dce4ac36.png)

**Comment by srirambv** [comment]
Seeing the same issue on beeff64bc595df91a2800cb3fd29d0ef275bd6d1. This is for main net and not test net

![image](https://user-images.githubusercontent.com/17010094/43620102-24675df6-969f-11e8-8d30-94df98454e7c.png)

**Comment by srirambv** [comment]
Seeing similar spacing issue now on main net as well
![image](https://user-images.githubusercontent.com/17010094/43620611-a35a9982-96a1-11e8-88cc-b5c56cfb406d.png)

**Comment by LaurenWags** [comment]
Reproduced on 
Brave: 0.25.1 
V8: 6.7.288.46 
rev: 43a07aeba7a6a1989cd3139e64f495126f14ebb2 
Muon: 7.1.6 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

![screen shot 2018-08-06 at 3 46 13 pm](https://user-images.githubusercontent.com/28145373/43737759-61432ab8-9990-11e8-8e76-b56e147bc236.png)
