### ISSUE TITLE
currency drop down for "ETH Wallet Balance" seems disproportionate compared to rest of the UI

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14909]
### Description

The currency drop down for "ETH Wallet Balance" seems disproportionate compared to rest of the UI.

### Steps to Reproduce

  1. launch a version of brave that has ETH Wallet (currently using https://github.com/brave/browser-laptop/pull/14734/)
  2. enable `ETH Wallet` using `about:preferences#ethwallet` and restart the browser
  3. ensure that you have a wallet with funds (I used `main net` but I'm sure you can use ropsten and fund via a faucet)
  4. Once your "ETH Wallet Balance" has been updated, click on `ETHER` next to the current balance

**Actual result:**

<img width="1282" alt="screen shot 2018-08-02 at 12 04 25 am" src="https://user-images.githubusercontent.com/2602313/43561980-bcb67dfc-95e7-11e8-8946-70e5a8367dab.png">

**Expected result:**

The UI for the currency drop down for "ETH Wallet Balance" should be proportionate to the rest of the page.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: 200494df265755df5a4d391a50f9cddabd5c1b1e 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**

No, currently not reproducible on the live release as this feature hasn't been released.

**Comment by Slava** [comment]
Completely removed that UI element in favor of always displaying the number in the original ETH

**Comment by kjozwiak** [comment]
@tomlowenthal @Slava are we sure we want to start removing elements from the UI rather then just fixing them? Completely removing something rather than fixing it seems a bit drastic IMO, even if it's not a major component of the UI. The above functionality is working pretty well in Mist so I'm assuming we would want to be at least somewhat in parity.

**Comment by tomlowenthal** [comment]
I'm happy to remove things rather than fixing them.
