### ISSUE TITLE
PSafe Total (AntiVirus) detect trojan

### ISSUE THREAD

**Issue by danilovaz** [brave/browser-laptop#1490]
I'm trying to download Brave for Windows, but when download finish my AntiVirus [PSafe Total](http://www.psafe.com/) detect an possible trojan in BraveSetup and I can't execute brave install (only if I disable AntiVirus).

I'm using Windows 7

![brave error](http://i.imgur.com/ebTZ0Oa.jpg)

**Comment by diracdeltas** [comment]
emailed their support

**Comment by danilovaz** [comment]
Thank's @diracdeltas :smile:

**Comment by luixxiul** [comment]
Does this problem still exist?

**Comment by danilovaz** [comment]
@luixxiul Yes, this still exist. I downloaded it brave.exe and happened this:

![image](https://cloud.githubusercontent.com/assets/1218337/15451977/ccd8dd26-1fb3-11e6-96ca-d90093f47b6c.png)

**Comment by luixxiul** [comment]
OK, closing this in favor of #924.
