### ISSUE TITLE
currency drop down being cut off when viewing specific wallets

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14908]
### Description

The currency drop down is being cut off when clicking on `ETHER` when viewing a specific wallet.

### Steps to Reproduce

  1. launch a version of brave that has ETH Wallet (currently using https://github.com/brave/browser-laptop/pull/14734/)
  2. enable `ETH Wallet` using `about:preferences#ethwallet` and restart the browser
  3. ensure that you have a wallet with funds (I used `main net` but I'm sure you can use ropsten and fund via a faucet)
  4. click on the wallet that you've just created so you're viewing that specific wallets page
  5. click on `ETHER` next to the wallets balance and you'll notice that the currency drop down is being cut off

**Actual result:**

<img width="624" alt="screen shot 2018-08-01 at 11 53 52 pm" src="https://user-images.githubusercontent.com/2602313/43561759-7b271b54-95e6-11e8-9fdb-d2a75a236b40.png">

**Expected result:**

The currency drop down shouldn't be cut off when clicking on `ETHER`.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: 200494df265755df5a4d391a50f9cddabd5c1b1e 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**

No, currently not reproducible on the live release as this feature hasn't been released.

**Comment by Slava** [comment]
I removed the whole drop-down. The logic behind it was very oversimplified and did an estimated conversion. With all the UI bugs that the dropdown introduced, I believe it is easier to get rid of it entirely.
