### ISSUE TITLE
string being duplicated when renaming wallets via editable text field

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14907]
### Description

When editing the Wallet name field, sometimes the text that you've typed in will be duplicated. Returning back to the `Wallet` area of the `ETH Wallet` will show the correct string. This might confuse some users who are editing their wallet names and suddenly notice duplicates.

### Steps to Reproduce

  1. launch a version of brave that has ETH Wallet (currently using https://github.com/brave/browser-laptop/pull/14734/)
  2. enable `ETH Wallet` using `about:preferences#ethwallet` and restart the browser
  3. create a new wallet via `New ETH Wallet`
  4. once the new wallet has been created, click on the wallet
  5. click on the editable field where you can rename the wallet, select the current name and remove it via `delete` using the keyboard.
  6. type in your new name and remove the focus from the editable field by clicking anywhere on the page, you'll notice that the string as been duplicated.
  7. click on `Wallets` and you'll notice that it will use the correct string

* Example (turn on audio) - https://youtu.be/3Txr3rZOW0w

**Actual result:**

* Example (turn on audio) - https://youtu.be/3Txr3rZOW0w

<img width="551" alt="screen shot 2018-08-01 at 11 37 06 pm" src="https://user-images.githubusercontent.com/2602313/43561204-f25f4b4a-95e3-11e8-9192-06e5e8b9aa93.png">

**Expected result:**

The entered text shouldn't be duplicated as it might confuse users even though it uses the correct string once you return to the `Wallet` page.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: 200494df265755df5a4d391a50f9cddabd5c1b1e 
Muon: 7.1.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**

No, currently not reproducible on the live release as this feature hasn't been released.

**Comment by Slava** [comment]
This does not happen in the Mist version. This is surprising, seems like we broke something in our version.

**Comment by Slava** [comment]
Just reproduced it in Mist.

**Comment by srirambv** [comment]
It only stays until the focus changes.

**Comment by kjozwiak** [comment]
> Just reproduced it in Mist.

Yup, reproduced myself using `Mist 0.11.1`. We can leave this opened for now but I have no issues closing it as it seems like an issue that we've inherited from Mist.
