### ISSUE TITLE
require user to enter password twice to create ETH Wallet and have show password checkbox

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14918]
### Description
When creating an account/wallet on Mist, there is a 'Show password' checkbox and you are required to enter your password twice for confirmation. ETH Wallet should have this as well. It's too easy to mess up typing a password especially if you don't have to confirm it and can't see it.

### Steps to Reproduce

  1. Open Mist and select Add Account. 
  2. Note you have a Show password checkbox and are required to enter your password twice.
  3. Launch Brave and navigate to ETH Wallet.
  4. Select New ETH Wallet. No Show password checkbox is present.
  5. Don't enter anything, just select OK.

**Actual result:**
You have an account created, but it doesn't have a password, this is very different from Mist's implementation.

**Expected result:**
Something like what Mist has when you go to create an account:
![screen shot 2018-08-02 at 11 43 02 am](https://user-images.githubusercontent.com/28145373/43595143-eb637e0e-9649-11e8-8ac3-67f90807b8ad.png)

And this is what you get when it's time to confirm your password:
![screen shot 2018-08-02 at 11 50 27 am](https://user-images.githubusercontent.com/28145373/43595309-53723dd2-964a-11e8-94a6-9eb92e528df6.png)

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.25.0 
V8: 6.7.288.46 
rev: a4df70c37e55dd3ff519cb8ee1bafda1fdb1f935 
Muon: 7.1.6 
OS Release: 16.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
no

**Comment by Slava** [comment]
In the new password flow we do require users to enter the password twice when the new password is created
