### ISSUE TITLE
Token Contact address is truncated

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14915]
### Steps to Reproduce

1. Run Brave
2. enable ETH Wallet using about:preferences#ethwallet and restart the browser
3. Run Brave with ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging GETH_LOG=1 npm run start
4. Go to about:preferences#ethwallet and click Contracts
5. Scroll down to Custom Tokens and click BAT Ropston

**Actual result:**
two last letters are not visible is the Edit Contract Address field.
![image](https://user-images.githubusercontent.com/34715963/43585907-8cb7881a-9666-11e8-88bd-bb8869bbbdce.png)

**Expected result:**
The full address is visible.

**Reproduces how often:**
always

### Brave Version
```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: a4df70c37e55dd3ff519cb8ee1bafda1fdb1f935 
Muon: 7.1.6 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Comment by Slava** [comment]
The modal and the field are now 200px wider
