### ISSUE TITLE
ETH value doesn't show beyond 2 decimal places

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14919]
### Description
ETH value doesn't show beyond 2 decimal places

### Steps to Reproduce
  1. Build from #14734 
  2. Enable ETH-Wallet and restart the browser
  3. Create a new ETH-wallet and fund it a very small amount of ETHER
  4. Wait till the funds show up on ETH-wallet
  5. Open Wallet to see the funds value, shows `0.00 ETHER*` 
  6. Change to BTC, shows upto 8 decimal values

**Actual result:**
![eth](https://user-images.githubusercontent.com/17010094/43596676-fa47653a-964d-11e8-9267-238d144a980e.gif)

**Expected result:**
Should show full wallet balance 

**Reproduces how often:**
100%

### Brave Version
a4df70c

**Reproducible on current live release:**
N/A

### Additional Information
Issue noticed by @kjozwiak as well

**Comment by Slava** [comment]
Fixed by displaying up to 5 sig digits in total balance in abd640916c83181c413048ff47227a82718c0a96
