### ISSUE TITLE
UI - dragging bookmarks and tabs visual feedback

### ISSUE THREAD

**Issue by TeoMorabito** [brave/browser-laptop#14913]
When dragging around tabs and/or bookmarks, there is currently no UI feedback to let the user know the position of that tab or bookmark,
In a bookmark folder, its rather difficult to move an item up or down precisely.

2 options are used by softwares :
- a little line or dot appearing between the 2 elements to see where the tab of bookmark will be moved to where releasing the drag
- even better is to have the tabs and bookmarks dynamically move to show a space where the item being move will reside.

**Comment by bsclifton** [comment]
This behavior is already fixed with [brave-core](https://github.com/brave/brave-browser) 😄 We won't be fixing in `browser-laptop`
