### ISSUE TITLE
geth.pid write and delete failure

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14914]
### Steps to Reproduce

1. Run Brave
2. enable ETH Wallet using about:preferences#ethwallet and restart the browser
3. Run Brave with `ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging GETH_LOG=1 npm run start`

**Actual result:**
Terminal output shows
`Could not write geth.pid`
`Could not delete geth.pid`

**Expected result:**
Should be able to write and delete geth.pid file.

**Reproduces how often:**
always

### Brave Version
```
Brave: 0.25.0 
V8: 6.7.288.46 
rev: a4df70c37e55dd3ff519cb8ee1bafda1fdb1f935 
Muon: 7.1.6 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

```

**Comment by ryanml** [comment]
This one should be fixed as of: https://github.com/brave/browser-laptop/pull/14734/commits/e18f8f7981f71c2e5818aceb5768e2e8b39d0438
