### ISSUE TITLE
ETH Wallet attempts to complete a transaction when incorrect password was entered and eventually succeeds

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14921]
### Description
When attempting to send funds from an account in the ETH Wallet, if you enter an incorrect password, ETH Wallet seems to attempt the transaction and doesn't notify you the password is incorrect. You will get a message that the transaction couldn't be completed but if you wait a bit the transaction does eventually go through). Mist does notify you if an incorrect password is used and does not attempt the transaction.

### Steps to Reproduce

  1. Enable ETH Wallet, create an account. Fund wallet. 
  2. Launch Mist, create an account. Fund wallet.
  3. Using Mist, try to send funds to your ETH Wallet. 
  4. Enter the wrong password to complete the transaction. 
  5. Note that Mist does not accept the incorrect password. 
  6. After getting the Wrong password message close the Send Transaction screen. 
  7. You will see a message that notifies the user that the Transaction was denied.
  8. Go to ETH Wallet. Try to send funds to your Mist wallet.
  9. Enter the wrong password to complete the transaction.
  10. The 'Please unlock your account to proceed with the transaction' window is closed. No feedback to user that password was incorrect.

**Actual result:**
The transaction is attempted - it appears under your 'Latest Transactions' area of Wallets:
![screen shot 2018-08-02 at 12 54 51 pm](https://user-images.githubusercontent.com/28145373/43599312-2f957c20-9655-11e8-9c4a-c50bfb23e5c4.png)

If you click on the above, you get something like this:
![screen shot 2018-08-02 at 12 17 51 pm](https://user-images.githubusercontent.com/28145373/43600972-11bd493a-965a-11e8-84a2-e64b6bdaa8d7.png)

Eventually you will get a message like this:
![screen shot 2018-08-02 at 12 59 18 pm](https://user-images.githubusercontent.com/28145373/43599393-72f2c234-9655-11e8-8e61-7506b8d5b29b.png)

After you get the message above, the Transaction is removed from your 'Latest Transactions' section, but I saw after about 30 minutes, the transactions did go through with the wrong password:
https://etherscan.io/address/0x7d10c9d60eA5de7180AB22ecfB4D14Cd8F5a03a8
![screen shot 2018-08-02 at 1 43 09 pm](https://user-images.githubusercontent.com/28145373/43600956-08ca17e0-965a-11e8-8de5-2e0f9e744fb7.png)

**Expected result:**
Transaction should not be attempted when incorrect password is entered. User should be notified that the password was incorrect.
Mist messaging:
<img width="575" alt="screen shot 2018-08-02 at 12 20 10 pm" src="https://user-images.githubusercontent.com/28145373/43599356-57c69594-9655-11e8-9aca-e4a03fa1cbd3.png">

Then, after you close the above popup without entering the correct password, this shows in the lower right corner:
<img width="361" alt="screen shot 2018-08-02 at 12 20 23 pm" src="https://user-images.githubusercontent.com/28145373/43599373-65007e6e-9655-11e8-9cb2-2ed60157ab81.png">

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.25.0 
V8: 6.7.288.46 
rev: a4df70c37e55dd3ff519cb8ee1bafda1fdb1f935 
Muon: 7.1.6 
OS Release: 16.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @kjozwiak

**Comment by Slava** [comment]
We changed the password flow to ask for a master password when the page is first loaded
