### ISSUE TITLE
Retain ETH-wallet background instead of showing it empty white background after enabling ETHWallet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14922]
### Description
Retain ETH-wallet background instead of showing it empty after enabling ETHWallet

### Steps to Reproduce
  1. Build from #14734 
  2. Open about:preferences#ethwallet, see beautiful ETH background on the page
  3. Enable ETH-wallet, see horrible plain background and quickly click on restart so that you dont stare at white light

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/43601541-67215fc8-965b-11e8-9680-f832d19867c1.png)

**Expected result:**
Maybe something like this
![image](https://user-images.githubusercontent.com/17010094/43601635-a7f2dff4-965b-11e8-923b-1c3281991e91.png)

**Reproduces how often:**
100%

### Brave Version

a4df70c

**Reproducible on current live release:**
N/A

**Comment by Slava** [comment]
Let's close this because now we don't have this state before the restart?

**Comment by srirambv** [comment]
Yes good to close this as there is no restart required when enabled.
