### ISSUE TITLE
Duplicate entry added to Token watch when edited 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14926]
### Description
Duplicate entry added to Token watch when edited 

### Steps to Reproduce

  1. Build from #14734 
  2. Enable ETH-Wallet
  3. Switch to Contracts and scroll down to Watch Token
  4. Click on Basic Attention Token (already added) and click Ok, creates a duplicate one for the same one

**Actual result:**
https://drive.google.com/open?id=1rE2IVCPaZnXf7_T3NcthJSY-nmPYXvKD

**Expected result:**
Should not create a new one unless the contract address is changed

**Reproduces how often:**
100%

### Brave Version
a4df70c

**Reproducible on current live release:**
N/A

### Additional Information
cc: @kjozwiak @LaurenWags @btlechowski to verify behaviour on mac/Linux

**Comment by Slava** [comment]
This does not happen in Mist. Which means something broke in our version

**Comment by Slava** [comment]
I could not reproduce it on the latest commit of brave eth-wallet branch. If we gather more information on how to reproduce consistently, I might be able to figure it out or find how to reproduce it in Mist

**Comment by srirambv** [comment]
I cant reproduce this on  b4db1b2 as well. Closing the issue for now.

**Comment by srirambv** [comment]
This is being reproduced on the latest build.
![14926](https://user-images.githubusercontent.com/17010094/44061959-7da5eaae-9f28-11e8-88a6-e851f8c0aae9.gif)

**Comment by Slava** [comment]
I reproduced it on Mist
