### ISSUE TITLE
Muted video still has audio icon

### ISSUE THREAD

**Issue by Mahdyar** [brave/browser-laptop#14924]
Hey there , It's My code : 
```
<video  autoplay="" loop="" muted="">
<source src="#" type="video/mp4">
</video>
```
and brave is still showing audio icon ! It doesn't shown in firefox or chrome ..

**Comment by Mahdyar** [comment]
hey @abrarShariar , I don't think so !
It was in a first load .

**Comment by bsclifton** [comment]
@Mahdyar can you please try this in the new [Developer channel release](https://brave.com/download-dev)?

I'll close the issue out, as I believe it should be fixed. If it's not, please reply here and I'll help create an issue tracking that in the new [brave-core](https://github.com/brave/brave-browser) repo
