### ISSUE TITLE
Browser Autofill should stop showing up previously entered amount values

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14920]
### Description
Browser Autofill should stop showing up previously entered amount values

### Steps to Reproduce
  1. Build from #14734 
  2. Create ETH-Wallet and fund it 
  3. Send Funds to different address 
  4. Amount filed in send funds stores all previously entered values and shows in dropdown. If user isn't careful might end up selecting wrong value to send to an address

**Actual result:**

![image](https://user-images.githubusercontent.com/17010094/43598511-dcea38c8-9652-11e8-82bd-b024e2de3cc9.png)

**Expected result:**
Should stop showing up previously entered values

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
a4df70c

**Reproducible on current live release:**

**Comment by LaurenWags** [comment]
Also should not show previously sent 'To' fields on the Send funds screen.

**Comment by Slava** [comment]
Fixed with setting the HTML5 attribute `autocomplete="off"` which is respected by some browsers.
