### ISSUE TITLE
'Returned error' message before user attempts to enter password

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14923]
### Description
When attempting to send funds from an account in the ETH Wallet, before you even enter your password you are presented with an `Returned error: authentication needed: password or unlock` message. This seems unnecessary since you're presenting the user with the password prompt and they haven't even attempted it yet.

### Steps to Reproduce

  1. Enable ETH Wallet, create an account. Fund wallet. 
  2. Launch Mist, create an account. 
  3. Go to ETH Wallet. Try to send funds to your Mist wallet.
  4. Once the 'Please unlock your account to proceed with the transaction' popup is displayed, you will immediately see an error in the lower right before you even enter your password.

**Actual result:**
![screen shot 2018-08-02 at 12 52 25 pm](https://user-images.githubusercontent.com/28145373/43602166-2a21b3be-965d-11e8-92fa-3f3b9850263a.png)

**Expected result:**
No error before user even attempts to enter password.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.25.0 
V8: 6.7.288.46 
rev: a4df70c37e55dd3ff519cb8ee1bafda1fdb1f935 
Muon: 7.1.6 
OS Release: 16.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103

**Reproducible on current live release:**
no

### Additional Information
Reproduced by @srirambv

**Comment by Slava** [comment]
We changed our password flow to always asked for a master password when the page is first loaded
