### ISSUE TITLE
Copy address shows test network message on wallet created on main net

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14934]
### Description
Copy address shows test network message on wallet created on main net

### Steps to Reproduce

  1. Build from beeff64bc595df91a2800cb3fd29d0ef275bd6d1
  2. Enable ETH-wallet and create a new ETH-Wallet
  3. Click on newly created wallet and click on Copy Address
  4. Test net warning message is shown even though the wallet is created on main net

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/43620490-06b39462-96a1-11e8-8177-05aea0c14668.png)

**Expected result:**
Should show options similar to https://github.com/brave/browser-laptop/issues/14900#issuecomment-410008952

**Reproduces how often:**
100%

### Brave Version
beeff64bc595df91a2800cb3fd29d0ef275bd6d1

**Reproducible on current live release:**
N/A

### Additional Information
Possibly due to https://github.com/brave/browser-laptop/issues/14900#issuecomment-410120939

**Comment by srirambv** [comment]
Reproduced with `0.23.100` . Browser launched with `GETH_LOG=1 ~/appdata/local/bravebeta/bravebeta.exe --user-data-dir-name=brave-beta` but still when address is copied shows the error message. 

Wallet details from keystore 
![image](https://user-images.githubusercontent.com/17010094/44096256-dbe4ae86-9fa8-11e8-8aba-f755f5f4d1e8.png)

![ethwallet](https://user-images.githubusercontent.com/17010094/44096302-f636012c-9fa8-11e8-9a58-0072f12c1272.gif)

**Comment by srirambv** [comment]
@tomlowenthal should this issue be uplifted from P4 to a higher priority?

**Comment by Slava** [comment]
I can't reproduce it. Could you run `Session.get('network')` from the JS console *on the iframe context* and let me know what it says. Again, make sure to run this statement on the embedded iframe JS context, not the top-level page context:

<img width="396" alt="screen shot 2018-08-14 at 6 29 12 pm" src="https://user-images.githubusercontent.com/2608446/44126999-009009b4-9ff0-11e8-973a-120d6ae2d53f.png">

**Comment by Slava** [comment]
Tried again today. Could not reproduce. A thing to note: if eth-wallet is not connected to geth, it assumes it is not on any net. And if it is not on main net, it shows the popup on copy. So assuming that you were trying to copy the address before eth-wallet connected to geth, it could explain the observed behavior?
