### ISSUE TITLE
Explanatory text about how to back-up wallets

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#14933]
Should be present at the bottom of the ETH Wallet interface:
> To back up your ETH Wallet keys, make copies of the files in `/path/to/directory/`.

**Comment by Slava** [comment]
done in 2aedcd2ad6fd42adb9d8bc0aad46b283025dfe7e

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
