### ISSUE TITLE
Transaction goes through even though it shows errors and not executed message 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14935]
### Description
Transaction goes through even though it shows errors and not executed message 

### Steps to Reproduce 

  1. Build from beeff64 and start with `GETH_LOG=1 LEDGER_ENVIRONMENT=staging npm run start`
  2. Enable ETH-Wallet and create a new ETH-Wallet
  3. Fund newly created Wallet with ETH (I used 0.015 ETH)
  4. Create Brave Wallet
  5. Switch to ETH-Wallet and click on Fund Brave Wallet
  6. Enter Amount as `0.015` and retain default fee value and click on Send
  7. Enter password to complete transaction and wait for the transaction to get listed 
  8. Open transaction link which shows as success (Mine was https://etherscan.io/tx/0x4e6eeb8abccd84ce6adce333f0584d4ad4e05aa0af77b2015c9b236b05c3377e)
  9. Click on latest transaction, shows error message about not sufficient gas to execute
  ![image](https://user-images.githubusercontent.com/17010094/43621399-3232ee7c-96a5-11e8-9dfb-c83a0719c951.png)
  10. Wait for few mins, Transaction failed notifications show up in ETH-Wallet
   ![image](https://user-images.githubusercontent.com/17010094/43621421-55f9baca-96a5-11e8-9cb4-939d086c7f88.png)

**Actual result:**
Transaction goes through even though it shows errors and not executed message 

**Expected result:**
Should properly show if the transaction is done successfully or not

**Reproduces how often:**
Just tried once since its on main net

### Brave Version

**about:brave info:**
beeff64 

**Reproducible on current live release:**
N/A

### Additional Information
cc: @LaurenWags @kjozwiak @btlechowski

**Comment by Slava** [comment]
From my understanding, this is what happens on Mist too?

**Comment by kjozwiak** [comment]
@srirambv mind checking to see if you can reproduce this on Mist?
