### ISSUE TITLE
[security@brave.com] security issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#14936]
this issue intentionally left blank, ping me for details

**Comment by bsclifton** [comment]
@diracdeltas can email test plan

**Comment by kjozwiak** [comment]
I reproduced the issue using `0.23.73` on `macOS `10.13.6 x64` and verified that the issue wasn't happening with the following build:

* `0.23.77` 0125b5f5ddc7eebc832ceeb4f4275230ec49d149 
* muon: `8.0.6` 
* libchromiumcontent: `68.0.3440.84`
