### ISSUE TITLE
Eth-Wallet nodes infrastructure needs a defined QA process

### ISSUE THREAD

**Issue by Slava** [brave/browser-laptop#14931]
Specifically, we need a process to test that browser-run nodes can connect and sync with the nodes hosted by brave infra. The current way is to let the browser geth node to sync, then issue an RPC and check the peers:

```
curl -X POST -H "content-type: application/json" --data '{"jsonrpc":"2.0","method":"admin_peers","params":[],"id":23}' localhost:RPCPORT
```

Note, that now we generate the RPC port randomly, the exact port should be taken from the logs

**Comment by evq** [comment]
to tack on here - we should also QA the server nodes and ensure they are as non-discoverable as we expect. this would consist of using the admin_peers rpc to verify only internal clients are connected

cc @bkero
