### ISSUE TITLE
crash and close with specific website

### ISSUE THREAD

**Issue by saostad** [brave/browser-laptop#14942]
When I visit the link below
[wayfair.com](https://www.wayfair.com/bed-bath/sb0/bath-accessory-sets-c215360.html)
if I click on brave icon on top to see counter of blocker adds and trackers, it 's suddenly completely close the browser!
but if I don't click on brave icon it works!

**Comment by LaurenWags** [comment]
Hi @saostad - What are your OS and Brave versions? I just tried on macOS with Brave 0.23.77 and could not reproduce the issue.

**Comment by saostad** [comment]
Win 10  x64 build 1803
but after update them Brave to new version today, it works now.

**Comment by LaurenWags** [comment]
great, thanks for reporting back! going to close out this issue.
