### ISSUE TITLE
Clicking a mailto: link will enter an endless loop

### ISSUE THREAD

**Issue by hucekes** [brave/browser-laptop#1494]
Using Brave on WIndows 10. Registered as defualt for all suggested protocols, including mailto:
Clicking on an email address will open an endless number of tabs. Can only be stopped by terminating Brave.

**Comment by diracdeltas** [comment]
Are you running the latest release or from github? This may have been fixed with the fix for #1362.

**Comment by hucekes** [comment]
Brave 0.9.2
Electron 37.6
is there a newer release?

**Comment by diracdeltas** [comment]
release coming next week

**Comment by hucekes** [comment]
Confirm fixed with Brave 0.9.3 Electron 37.7. Brave now asks for permission to open an external app, as it should.

**Comment by diracdeltas** [comment]
thanks @hucekes. if you click 'allow', does it still go into an endless loop?

**Comment by hucekes** [comment]
it opens one new tab and stops

**Comment by diracdeltas** [comment]
Cool, marking this fixed for now.
