### ISSUE TITLE
Page URL is retained when visiting a site with invalid certificate

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14943]
### Description
Page URL is retained when visiting a site with invalid certificate

### Steps to Reproduce
  1. Visit https://badssl.com
  2. Click on expired in certificate list
  3. Shows cert error page but URL is retained 
  4. Click back button to navigate back 
  5. URL changes to `about:certerror`
  6. Click through cert option, page loads correctly with the URL

**Actual result:**
![cert1](https://user-images.githubusercontent.com/17010094/43650833-ce587664-970e-11e8-831c-76462f7b3677.gif)

**Expected result:**
Should show `about:certerror` instead of actual URL when the cert error page is shown

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.77
-- | --
V8 | 6.8.275.24
rev | 0125b5f
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
Yes

### Additional Information
cc: @bridiver @diracdeltas

**Comment by kjozwiak** [comment]
Seems like this as been around for a while now:

• `0.23.76` - same behaviour
• `0.23.73` - same behaviour
• `0.23.39` - same behaviour
• `0.23.31` - same behaviour
• `0.23.19` - same behaviour

**Comment by ckujau** [comment]
So, this intermittent showing of `about:certerror` is confusing, especially if one hits the `back` button, the `about:certerror` shows up for a split second in the URL bar. But I don't want to have `about:certerror` in the URL bar, ever. The URL bar should indeed show the URL of the page that generated that error, just like Firefox or Chrome is doing. Showing the `about:certerror` when showing the certificate error page doesn't tell me which site generated the error. Sure, it's in the `<body>` of the page, but who reads that? :-)
