### ISSUE TITLE
View source doesn't prefix for all pages when viewing page source

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14940]
### Description
View source doesn't prefix for all pages when viewing page source

### Steps to Reproduce
  1. Visit brave.com and press Ctrl+U, New tab opens with source but doesn't prefix it 
  2. Visit https://media.clifton.io/issue-14893.html/https://www.w3schools.com/html/html_examples.asp, view source, doesn't prefix to URL and loads source via insecure connection
  3. Visit twitter.com and view source, correctly prefix's `view-source://URL` and doesn't show connection info

**Actual result:**
![viewsource](https://user-images.githubusercontent.com/17010094/43642020-dfb7a634-96f3-11e8-99ab-3891adade4de.gif)

**Expected result:**
Should properly show the prefix for all pages

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.77
-- | --
V8 | 6.8.275.24
rev | 0125b5f
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
Yes reproduces for .html/.asp/.php pages, but doesn't reproduce on https://brave.com

### Additional Information
cc: @diracdeltas 
@LaurenWags @btlechowski to verify on other platforms

**Comment by LaurenWags** [comment]
on macOS using `0.23.77`:
1. Visit brave.com and press Cmd+Option+u, New tab opens with source and does show `view-source:https://brave.com/` in URL bar. No connection info.
![screen shot 2018-08-03 at 8 38 29 am](https://user-images.githubusercontent.com/28145373/43643237-9f2cfb64-96f8-11e8-9179-3eb492e6c08b.png)

2. Visit either https://media.clifton.io/issue-14893.html or https://www.w3schools.com/html/html_examples.asp and press Cmd+Option+u. New tab opens with source and does NOT show `view-source:` prefix to URL and loads source via insecure connection.
![screen shot 2018-08-03 at 8 41 16 am](https://user-images.githubusercontent.com/28145373/43643342-014501d4-96f9-11e8-835b-4addb4df8801.png)
![screen shot 2018-08-03 at 8 41 01 am](https://user-images.githubusercontent.com/28145373/43643346-03502684-96f9-11e8-9373-935fb44b3cb5.png)

3. Visit twitter.com and view source, correctly prefix's view-source://URL and doesn't show connection info
![screen shot 2018-08-03 at 8 41 42 am](https://user-images.githubusercontent.com/28145373/43643385-1c3bf45c-96f9-11e8-841b-b07181cf144c.png)
