### ISSUE TITLE
Opening a new tab from the URL bar of a private tab opens a non-private tab

### ISSUE THREAD

**Issue by mkhl** [brave/browser-laptop#14941]
### Opening a new tab from the URL bar of a private tab opens a non-private tab

In the URL bar, one can enter a URL and hit <kbd>Command</kbd>-<kbd>Return</kbd> (in macOS) to open the entered URL in a _new_ tab.
When doing this while a private tab is active, the new tab will still be non-private.
Some people (at least myself) use this interaction analogously to <kbd>Command</kbd>-Clicking (still on macOS) links, which also opens the link in a new tab but which makes those new tabs private when done from a private tab.

### Steps to Reproduce

  1. Go to https://duckduckgo.com/
  2. Focus the URL bar
  3. Enter https://start.duckduckgo.com/
  4. Hit <kbd>Command</kbd>-<kbd>Return</kbd> (probably <kbd>Ctrl</kbd>-<kbd>Return</kbd> on other platforms?)

**Actual result:**
https://start.duckduckgo.com/ is opened in a new non-private tab.

**Expected result:**
https://start.duckduckgo.com/ is opened in a new _private_ tab.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.23.73 
V8: 6.8.275.24 
rev: 50bdb6df42550dd14f5636770ec8585aa26e361b 
Muon: 8.0.3 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.75

**Reproducible on current live release:**
Not sure what that means, sorry.

### Additional Information

Also happens in private tabs with Tor.

**Comment by srirambv** [comment]
This only happens when a search suggestion is shown. If the entered site is not listed in site suggestions then it loads in the same tab.  Also reproduced the issue on Windows. 

cc: @bsclifton

**Comment by mkhl** [comment]
> If the entered site is not listed in site suggestions then it loads in the same tab.

I cannot confirm this part. The entered site loads in a new non-private tab for me.

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
