### ISSUE TITLE
Auto-complete Dropdown menu overlays on other tabs.

### ISSUE THREAD

**Issue by AndrewNduati** [brave/browser-laptop#14946]
### Description
I have noticed that when a dropdown menu of auto-complete content is present in one tab, it usually renders in other tabs in the same position.

For example, if I go to a login page & the dropdown is active, I will find the dropdown menu in other tabs. 

### Steps to Reproduce

  1. Head to any Sign-up or Login page 
  2. Type an already saved email or username that will activate the auto-complete dropdown
  3. Switch tabs using keyboard (Mac **CMD + alt+ arrow-keys**)

**Actual result:**

##### Login / Sign-up Page

<img width="1123" alt="screen shot 2018-08-03 at 18 38 56" src="https://user-images.githubusercontent.com/22328352/43660410-72464e56-974e-11e8-8765-6d588ca6905d.png">

##### Other tab with the same auto-complete open and active.
<img width="1677" alt="screen shot 2018-08-03 at 18 39 22" src="https://user-images.githubusercontent.com/22328352/43661139-a473ae8a-9750-11e8-92f9-d26122275b7d.png">

**Expected result:*
There should not be an overlay.

**Reproduces how often:**
As often as one switches tabs.

### Brave Version

**about:brave info:**
 
Brave: 0.23.73 
V8: 6.8.275.24 
rev: 50bdb6df42550dd14f5636770ec8585aa26e361b 
Muon: 8.0.3 
OS Release: 17.6.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.75

**Reproducible on current live release:**

### Additional Information
One can even allow Brave to remember the login credentials of that account and see whether it occurs too.

Ps. Maybe there is a setting I have that is causing this. Please let me know so as to have this issue closed early.

**Comment by bsclifton** [comment]
Thanks for the report, @AndrewNduati 😄 This is a known issue (although I didn't find a bug for it, I've seen it before). I don't think we'll be able to address this with `browser-laptop`, but this is fixed with `brave-core` (the Chromium UI that we're moving to)
