### ISSUE TITLE
3221225477 error Failed at the brave@0.23.77 start script.

### ISSUE THREAD

**Issue by JC-Coelho** [brave/browser-laptop#14954]
```
C:\brave>npm start

> brave@0.23.77 start H:\brave
> node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

ERROR getting value for field rev in sessionStore::setVersionInformation():  Error: [git-rev-sync] no git repository found
    at _getGitDirectory (H:\brave\node_modules\git-rev-sync\index.js:47:11)
    at _getGitDirectory (H:\brave\node_modules\git-rev-sync\index.js:75:10)
    at _getGitDirectory (H:\brave\node_modules\git-rev-sync\index.js:75:10)
    at _getGitDirectory (H:\brave\node_modules\git-rev-sync\index.js:75:10)
    at _getGitDirectory (H:\brave\node_modules\git-rev-sync\index.js:75:10)
    at branch (H:\brave\node_modules\git-rev-sync\index.js:79:16)
    at Object.long (H:\brave\node_modules\git-rev-sync\index.js:92:11)
    at exports.browserLaptopRev (H:\brave\app\buildConfig.js:11:29)
    at safeGetVersion (H:\brave\app\sessionStore.js:551:30)
    at versionFields.forEach (H:\brave\app\sessionStore.js:580:26)
Crash reporting enabled
Could not load background script 'content/scripts/sync.js'.
[9448:1184:0805/034156.687:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[9448:12464:0805/034156.702:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.
process exited with code 3221225477
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! brave@0.23.77 start: `node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the brave@0.23.77 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\...\AppData\Roaming\npm-cache\_logs\2018-08-05T02_42_21_602Z-debug.log
```

### Description

Brave is crashing when opening a new tab. Please note I'm compiling successfully in 32-bit except for an error and a warning I've reported in another post. 
Please also note I've disabled GPU acceleration so this might explain the GPU reporting I get in the console (i.e. `9448:1184:0805/034156.687`, `9448:1184:0805/034156.702`)

### Steps to Reproduce

  1. Launch Brave with "npm start"
  2. Add a new tab
  3.

**Actual result:**

Exits with reported error.

**Expected result:**

Allow for browsing with more than one tab.

**Reproduces how often:**

Recurring problem.

### Brave Version

Brave: 0.23.77 
V8: 6.8.275.24 
Muon: 8.0.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: ia32 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**

Yes.

### Additional Information

GPU acceleration disabled.

**Comment by JC-Coelho** [comment]
I've rebuilt to the exact beta tester instructions and am somewhat still getting the problem. It's browsing on one tab. I'll keep you posted.

**Comment by JC-Coelho** [comment]
I couldn't do the full bootstrap install. Maybe in a near future if I can borrow someone's cable. Not.

**Comment by JC-Coelho** [comment]
Maybe I should also mention that the problem is less frequent with the installer version. Also that I could be still running remnants of previous builds that were not made to exact beta tester instructions. Whichever case it seems to be wanting to run more confidently now. Maybe it doesn't like being home built?

**Comment by bsclifton** [comment]
@JC-Coelho definitely looks like your npm install is failing- because on successful finish, it should fetch the sync client (also, the git rev lookup should be passing, which hints at a failed dependency install)

Can you link to your original issue?

**Comment by JC-Coelho** [comment]
I no longer get the sync client related messages.
I only see GPU related reporting now which I would try guess must have to
do with me having disabled GPU acceleration.
I've finally built to the exact spec for beta testers and cleared out my
previous brave-development user folder.

I'm sending you a screenshot attached.


Greetings,

J.C. Coelho
jccoelho99@gmail.com
+351 91 515 8689
