### ISSUE TITLE
No CDN use for download brave packages

### ISSUE THREAD

**Issue by posix4e** [brave/browser-laptop#14956]
### Description
I noticed my upgrades go through:
Get:1 https://s3-us-west-2.amazonaws.com/brave-apt bionic/main amd64 brave amd64 0.23.77-1 [96.6 MB]
perhaps we could put this through cloudfront or cloudflare to improve performance.

### Steps to Reproduce
  1. Try to upgrade or install brave

**Actual result:**
We download directly from S3

**Expected result:**
We use some CDN to accelerate the download

**Reproduces how often:**
Always

### Brave Version
All

**Reproducible on current live release:**
Yes

**Comment by NumDeP** [comment]
Can I ask what does the team utilize Fastly for then?

**Comment by bsclifton** [comment]
@NumDeP it should be used for macOS and Windows - I guess we're not using it for Linux though

**Comment by bsclifton** [comment]
Closing- let's address this with `brave-core`. An issue can be opened here:
https://github.com/brave/brave-browser/issues

**Comment by NumDeP** [comment]
You can track it here - https://github.com/brave/brave-browser/issues/1360
