### ISSUE TITLE
Zoom in/out with numpad (calculator keys)

### ISSUE THREAD

**Issue by rocky4-iv** [brave/browser-laptop#1495]
Brave >>Page Zoom works if I use CTRL and (+ Function Key)
**Brave >>Page Zoom does not work if I use CTRL and (+ Calculator Key)**
Using a USB Kensington Keyboard **with Integrated Calculator**
With Opera, Vivaldi, Maxthon Broswers -- Zoom function works great with integrated Calculator + key
*****************************************************************************************************************
I'll provide more details -- I'm using Brave Browser on Linux: 
Brave: 0.9.3
Electron: 0.37.7
libchromiumcontent: 49.0.2623.112
V8: 4.9.385.35
Node.js: 5.10.0
Update channel: dev
****************************
Operating System is Linux Manjaro Cinnamon 2.8.8
Linux Kernel 4.6rc4-1
****************************
Thanks

**Comment by luixxiul** [comment]
@bbondy +1

**Comment by luixxiul** [comment]
Zooming out with numpad ``-`` should be added too :-)

**Comment by bbondy** [comment]
- was working for me on my keyboard when I tried btw.  Did you see that it was failing?

**Comment by luixxiul** [comment]
Yes, on Windows 10.
