### ISSUE TITLE
Loading FTP with protocol associated to Brave causes an infinite loop of loading blank tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14951]
### Description
Follow up to https://github.com/brave/browser-laptop/issues/14712#issuecomment-410347422

### Steps to Reproduce

  1. Clean install 0.23.77
  2. Visit https://dlptest.com/ftp-test/
  3. Select Remember decision and Click on Allow
  4. Select Brave from `How should this link be opened` message
  5. Brave keeps opening new tab which is blank, never prompts to login to the site

**Actual result:**
![ftp](https://user-images.githubusercontent.com/17010094/43660872-3e69c772-972e-11e8-8e28-72fa519b7521.gif)
**Expected result:**
Should prompt to login similar to Linux and Mac

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.77
-- | --
V8 | 6.8.275.24
rev |  0125b5f
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
No

**Comment by Metnew** [comment]
> I'm not familiar with the code, but maybe Brave continues being the default handler for `ftp://` on your device?

**Comment by bsclifton** [comment]
If a default handler is not associated, FTP is not handled (which is acceptable since FTP is disabled in Brave). Ultimately, this will be addressed with [brave-core](https://github.com/brave/brave-browser)
