### ISSUE TITLE
Fund Brave Wallet button doesn't work after click on Send 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14958]
### Description
Fund Brave Wallet button doesn't work after click on Send 

### Steps to Reproduce
  1. Build from #14734 
  2. Enable ETH-wallet and restart 
  3. Enable payment to create staging wallet
  4. Click on Send button in ETH wallet, shows empty from and to fields
  5. Click on Fund Brave Wallet button, doesn't auto populate to field with Brave wallet address

**Actual result:**
Fund Brave Wallet button doesn't work after click on Send 

**Expected result:**
Should auto populate Brave wallet address when Fund Brave wallet button is clicked

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
0.25.1

**Reproducible on current live release:**
N/A

**Comment by Slava** [comment]
For some reason on `LEDGER_ENVIRONMENT=staging` I can't find the appropriate eth address for funding brave wallets.

**Comment by srirambv** [comment]
This is an issue even without `LEDGER_ENVIRONMENT=staging`.

**Comment by Slava** [comment]
This will only work if the payments are enabled. Maybe we need more UI to communicate this.

**Comment by srirambv** [comment]
Doesn't work with Payments enabled first as well. The button is still clickable but doesn't auto populate the Brave wallet address
![14598](https://user-images.githubusercontent.com/17010094/43923004-76321df2-9bee-11e8-8c91-8f4b2ec96d48.gif)

**Comment by Slava** [comment]
merged to master, the expected behavior: no UI elements are shown until the password prompt comes up
