### ISSUE TITLE
Add a feature to turn off Tor completely 

### ISSUE THREAD

**Issue by SS1113** [brave/browser-laptop#14952]
I don't want to accidentally use Tor so if you could add the option to turn off Tor it would be great. I didn't know where to request new features whether in GitHub or Brave Community so I decided to write on GitHub.

**Comment by bsclifton** [comment]
@SS1113 thanks for the suggestion! 😄 We're currently tracking this feature request with https://github.com/brave/browser-laptop/issues/14603

I'll close this out as a duplicate- you can subscribe to that issue for updates. Thanks! 😄
