### ISSUE TITLE
Focus loss on hovering tabs

### ISSUE THREAD

**Issue by iMartyn** [brave/browser-laptop#14957]
### Description
Url focus is lost when hovering tabs

### Steps to Reproduce
  1. Open a few tabs
  2. Open a new tab and focus the URL box
  3. Hover over a tab and continue to type URL

**Actual result:**
Focus is gone from URL bar

**Expected result:**
Focus should not be lost

**Reproduces how often:**
100%

### Brave Version
Name | Version
-- | --
Brave | 0.23.31
V8 | 6.7.288.46
rev | 3148ace
Muon | 7.1.5
OS Release | 4.9.0-6-amd64
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
Yes

### Additional Information
Gnome on Debian fwiw

**Comment by rebron** [comment]
Closing. This looks fixed in brave-core.
