### ISSUE TITLE
sometimes there is an Unable to connect error on ETH Wallet page when using build

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14962]
### Description
Sometimes when launching a build containing ETH Wallet, you will see an 'Unable to connect. Please start geth with the following options:' message. Clicking OK on the message only makes the message go away briefly, then it comes back. You must refresh the page to make this message go away. Sometimes restarting Brave does the trick too.

### Steps to Reproduce

  1. Launch build with ETH Wallet (0.25.202) with fresh profile (can use env variables if you want)
  2. Enable ETH Wallet. Say No to restart option but stay on ETH Wallet page.
  3. Close Brave.
  4. Launch build again (with env variables if desired)
  5. Sometimes, you will get an Unable to connect error.

**Actual result:**
Sometimes you will get the msg below. Refresh of the page usually helps. Sometimes a restart of Brave does not produce this same message.

![image](https://user-images.githubusercontent.com/28145373/43779833-48ba720c-9a27-11e8-843c-7af19af2fe28.png)

**Expected result:**
No error.

**Reproduces how often:**
somewhat often, not 100%

### Brave Version

**about:brave info:**
0.25.202

**Reproducible on current live release:**
n/a

### Additional Information
Reproduced by @btlechowski on Win 7 using 0.25.202, also seen by @Slava (who mentioned in slack a potential race-like situation in this case)

**Comment by Slava** [comment]
This UI is replaced with a popup with a spinner that lasts until the connection to geth is established.
