### ISSUE TITLE
Switch tabs doesn't ask for Wallet Password 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14965]
### Description
Switch tabs doesn't ask for Wallet Password 

### Steps to Reproduce

  1. Build from 86769fec61650a55b4a88d13419b44a3c422ef44
  2. Launch browser with ` ETHEREUM_NETWORK=ropsten GETH_LOG=1 LEDGER_ENVIRONMENT=staging npm run start`
  3. Enable ETHWallet click NO in restart prompt, Manually close browser and restart with the above command with `about:preferences#ethwallet` as focused tab
  4. Quickly close the tab/ open  a new tab so focus is lost from `about:preferences#ethwallet`
  5. After couple of seconds switch back and create a new ETH Wallet, doesn't ask for password
  6. Repeat step 5 and you can create multiple wallets without password
  7. Click on other sections in Payments and switch back to ETH Wallet, asks for password 
  8. Click continue asks to enter password which you have not set, says incorrect password
  9. Click anywhere outside password prompt is dismissed. 

**Actual result:**
![wallet password](https://user-images.githubusercontent.com/17010094/43786832-97fd0202-9a37-11e8-919a-7c79882855e3.gif)

**Expected result:**
Should not allow to create wallet until password is set

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.7.288.46
rev | 86769fe
Muon | 7.1.6
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
N/A

### Additional Information
cc: @btlechowski @LaurenWags @kjozwiak @GeetaSarvadnya @ryanml @Slava

**Comment by Slava** [comment]
I will work on locking the UI before the connection to geth is established

**Comment by Slava** [comment]
As of d2f8f9baa35c5e066ca76cf16d9fd9537ae0a764 the UI elements are blocked by a spinner in a modal
