### ISSUE TITLE
password is not required

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14969]
### Description
When the password box is displayed upon opening the ETH Wallet page, clicking elsewhere on the page dismisses the password box. You can then create a wallet that I guess doesn't have a password. Not sure if this is expected as the password functionality is not yet defined in the spec.

### Steps to Reproduce

  1. Build and launch from eth-wallet PR. (
  2. Enable ETH Wallet.
  3. Close/relaunch Brave (use same parameters as step 1 if using ropsten, etc)
  4. You are prompted to enter a password on the ETH Wallet page.
  5. Click elsewhere on the page.
  6. pw box goes away. Create a wallet.
  7. Leave and come back to the ETH Wallet page.
  8. Prompted for password again, can click away. (if you enter a password here, you get notified it's wrong)
  

**Actual result:**
Able to click away and password box is no longer shown/required.
![ethwalletpw](https://user-images.githubusercontent.com/28145373/43805136-a14c9f22-9a6c-11e8-8724-e7fb35e35c15.gif)

**Expected result:**
I'd expect it to be required if we need a password to send transactions, but I'm not sure this was the intent.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.25.0 
V8: 6.8.275.24 
rev: 6d7c1f167fbd9d59bd4dff94f891b2da466c5655 
Muon: 8.0.6 
OS Release: 16.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
n/a

### Additional Information
cc @tomlowenthal to confirm what the expected result should be

**Comment by Slava** [comment]
I believe that's no longer the case on `349952280c25fb97edd3da8d1fa202f3adeccd84`. I made the modal not-dismissible.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
