### ISSUE TITLE
Need a place holder text when New ETH Wallet doesn't show the newly created wallet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14961]
### Description
Need a place holder text when New ETH Wallet doesn't show the newly created wallet

### Steps to Reproduce
  1. Build from source/ install 0.25.1/101
  2. Enable ETH-wallet and click on `New ETH Wallet button
  3. Newly created ETH-Wallet doesn't show up immediately if the geth sync is slow which may cause users to create multiple wallets 

**Actual result:**
Need a place holder text when New ETH Wallet doesn't show the newly created wallet

**Expected result:**
Should probably show some placeholder text like `Wallet being created` until the UI gets a response to show the newly created ETH wallet

**Reproduces how often:**
Good amount of time. Sometimes the wallet creation is instantaneous sometimes shows up only when tab focus is changed. Sometimes doesn't show up even after restarting the browser

### Brave Version
#14734

**Reproducible on current live release:**
N/A

### Additional Information
cc: @bradleyrichter  @ryanml

**Comment by Slava** [comment]
The wallet creation seemed instant to me so far. If we can find a good way to reproduce this, we might be able to tweak either the polling interval or the connection to geth.

**Comment by Slava** [comment]
I pushed a change that instantly creates a wallet in the UI without waiting for geth to sync

**Comment by GeetaSarvadnya** [comment]
Now we can see wallets getting created successfully before the geth sync. But after geth sync, click on New wallet create won't show wallets immediately? Also, after navigating to other places (wallets or Contracts or Fund Brave wallet) and coming back to new wallet create button doesn't show any message for the previous wallet creation and also it won't show any created wallets. 

Initially when user enable the eth wallet switch and enter new password. The wallet is getting created without clicking on New eth wallet button. From where this wallet is coming?

**Comment by Slava** [comment]
fixed on master
