### ISSUE TITLE
Able to create multiple wallets with same password

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14966]
### Description
Able to create multiple wallets with same password

### Steps to Reproduce
  1. Build from 86769fec61650a55b4a88d13419b44a3c422ef44
  2. Enable ETH Wallet, close preferences page and close the browser
  3. Restart browser and open ETH Wallet in preferences
  4. Asks for Wallet password. Enter and confirm
  5. Click on `New ETH Wallet` button, creates a new wallet
  6. Click the button again, creates a new wallet but doesn't prompt to create password for it
  7. All created wallets use the same password
  8. Switch focus to other section and back to ETH Wallet
  9. Asks to unlock wallets, enter password set in step 4, looks like all wallets are unlocked to used

**Actual result:**
![wallet password1](https://user-images.githubusercontent.com/17010094/43787379-d754a09e-9a38-11e8-946c-c9cd6c56721a.gif)

**Expected result:**
Should ask individual wallet to create its own set of password

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.7.288.46
rev | 86769fe
Muon | 7.1.6
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
N/A

### Additional Information
@Slava @ryanml @kjozwiak @btlechowski @LaurenWags @GeetaSarvadnya

**Comment by flamsmark** [comment]
This is actually the intended behavior. We're deliberately using only one password for the whole app.

**Comment by kjozwiak** [comment]
@tomlowenthal mind adding this new implementation into the spec if it's not already there?
