### ISSUE TITLE
Cannot click in modal Lastpass dialogs

### ISSUE THREAD

**Issue by acvanzant** [brave/browser-laptop#14964]
No issues found like this, at least specific to lastpass's plugin.

Lastpass itself works as does the context menu options. However, the modal dialogs that are displayed when saving a new password or when clicking on the lastpass icon in the username field on the page itself do not handle clicks or interaction, what-so-ever.

I also noticed the buttons in the username/password fields are misaligned. The hit-box is not lined up with the icon.

### Steps to Reproduce

  1. Download latest Brave release.
  2. Enable LastPass from Preferences.
  3. Attempt to use the buttons in the username or password fields to open the dialog.
  4. Notice no clicks or on-hover events are handled.

**Comment by acvanzant** [comment]
This occurs on my Windows 10 machine but not on my Windows 7 machine.

**Comment by levyomri** [comment]
On MacOS Sierra as well

**Comment by bsclifton** [comment]
This should be fixed on our Developer channel release if you wanted to give it a try:
https://brave.com/download-dev
