### ISSUE TITLE
Fix security issue

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14967]
Ask @darkdh for details

**Comment by kjozwiak** [comment]
Going to ping @darkdh for details regarding how QA can check this as per https://github.com/brave/browser-laptop/issues/14967#issue-348427107.

**Comment by azhar9607** [comment]
Unsubscribed

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.80 53a429f
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
