### ISSUE TITLE
Unable to select 'Move Tab to New Window' or 'Merge All Windows' from Window menu 

### ISSUE THREAD

**Issue by olimay** [brave/browser-laptop#1496]
'Move Tab to New Window' and 'Merge All Windows' are visible for me in the Window menu, but I can't select them.

![2016-04-27 21 45 31](https://cloud.githubusercontent.com/assets/101905/14873180/b7055c7c-0cc1-11e6-9043-208c6712d4a5.png)

This is for Brave 0.9.2 on OS X 10.11.4.

**Comment by diracdeltas** [comment]
They're disabled for everyone because those features aren't implemented yet

**Comment by alexwykoff** [comment]
@bbondy should this be scoped under tear-off-tabs?

**Comment by srirambv** [comment]
+1 for window merge from community https://community.brave.com/t/merge-all-windows/2150

**Comment by bsclifton** [comment]
seems to have been removed
