### ISSUE TITLE
Error: Returned error: The method eth_compileSolidity does not exist/is not available

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14972]
### Description
Unable to deploy smart contract 

### Steps to Reproduce
  1. Build from c254908047456b9a2b0974ceb9d9a6d7c4f07e1e
  2. Enable ETH-Wallet and create a New ETH Wallet
  3. Click Contracts -> Deploy New Contract
  4. Copy the sample contract code from https://ethereum.org/dao#the-code and paste in 

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/43841284-c581ad4a-9af0-11e8-9c4b-ab311663e3dc.png)

**Expected result:**
Should not throw the error 

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.8.275.24
rev | c254908
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
cc: @ryanml @Slava

**Comment by evq** [comment]
Looks like it isn't supposed to work - https://github.com/ethereum/go-ethereum/issues/3793

**Comment by Slava** [comment]
That's what I found too. But I am confused how does Mist make it work?

**Comment by evq** [comment]
I think they have their own implementation - https://github.com/ethereum/mist/blob/175fd643b5fee04820bcaf09a98241c19ded2f79/modules/ipc/methods/eth_compileSolidity.js

**Comment by Slava** [comment]
@tomlowenthal do you want me to look into shipping whatever extra code we need for this? Alternatively we remove the feature

**Comment by tomlowenthal** [comment]
Nah, this is a niche and confusing feature within a niche and confusing feature. Just disable it IMO.

**Comment by Slava** [comment]
done in `c229a581be7c0f4a88ac6f37e2692f95e6fe7f95`

**Comment by GeetaSarvadnya** [comment]
Deploy new contracts option is removed in 0.25.501.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
Note : Verified create contract section removed based on #14972 (comment)
