### ISSUE TITLE
password modal being prompted after already adding a password several times when initially enabling

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14981]
### Description

When you initially start Brave with `ETH Wallet`, enabling the `ETH Wallet` feature will display a required password modal. However, once you add a password and switch to another preference page and come back to the ETH Wallet, you're prompted again to `Add a new password`.

### Steps to Reproduce

  1. launch brave with the eth wallet feature (used source - f20fdca)
  2. enable the eth wallet via `about:preferences#ethwallet`
  3. once enabled, type in the mandatory password and click on `OK`
  4. switch to another preference page like `Payments` and go back to `ETH Wallet`

You'll be prompted to create another password despite already doing it.

**Actual result:**

![ethunresponsive](https://user-images.githubusercontent.com/2602313/43921735-a16e4e54-9bea-11e8-9d15-6fecb8a16103.gif)

**Expected result:**

Once I've added my `master` password, brave should remember it and not prompt me again.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

 
```
Brave: 0.25.0 
V8: 6.8.275.24 
rev: f20fdca85a585f0f3b11e5710a913b66e5798885 
Muon: 8.0.6 
OS Release: 17.7.0 
Update Channel:  
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
```

**Reproducible on current live release:**

No, this feature hasn't been release and isn't available in the latest released version.

### Additional Information

Also reproduced by @srirambv via Windows 10 x64.

**Comment by srirambv** [comment]
Doesn't repeat once you restart the browser. Only asks to unlock wallet upon focus

**Comment by Slava** [comment]
Since we do not save the password anywhere, the only way to know if there was a password is to check if there are any wallets that can be unlocked. If there are no wallets, the app treats the situation as if there was never a password. I know it seems confusing but that's what @tomlowenthal and I settled on last week. We can talk about this.

**Comment by tomlowenthal** [comment]
Let's create a wallet immediate when the first-run password prompt finishes.

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.501 775ecfac0e8562aaa3c81458a0bb55e237d9e36b
• Muon 8.0.7
• libchromiumcontent 68.0.3440.84
![14981](https://user-images.githubusercontent.com/38657976/44043502-a98a18bc-9f40-11e8-97ad-2020676eeb62.gif)

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84
