### ISSUE TITLE
Unable to add contracts to watch list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14982]
### Description
Unable to add contracts to watch list

### Steps to Reproduce

  1. Build from f20fdca85a585f0f3b11e5710a913b66e5798885
  2. Enable ETH-Wallet and go to Contracts
  3. Copy Contract code/name and address from https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef#code and past in the popup modal
  4. Click Ok, shows `Couldn't parse JSON` message, no contract added to watch list

**Actual result:**
![watch_contract](https://user-images.githubusercontent.com/17010094/43922645-5adc6388-9bed-11e8-9c3a-eaabacf811b9.gif)

**Expected result:**
Should add contract to watch list

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.8.275.24
rev | f20fdca
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
cc: @ryanml @Slava

**Comment by Slava** [comment]
done on master
