### ISSUE TITLE
Use v2 promotion endpoints

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#14980]
### Description

For the next round of UGP grants we want to use the new version of promotion and grant endpoints. These were implemented in https://github.com/brave-intl/bat-ledger/pull/341

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.102 43eb6673e6601527129f3f9f96aade08d15bc671
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.103 ae8e27774bb896ef4dd5cc928321d0eacb60ca59
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using

- 0.23.104 b454a4a
- Muon 8.0.8
- libchromiumcontent 68.0.3440.84
