### ISSUE TITLE
Creating a new ETH Wallet creates Account 2 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14989]
### Description
Creating a new ETH Wallet creates Account 2 

### Steps to Reproduce
  1. Clean profile from 0.25.401
  2. Enable ETH Wallet, wait till it prompts for creating password
  3. Enter password and then click on New ETH wallet, creates a new wallet with `Account 2`
  4. Close and restart browser (Hope it doesnt crash), still no idea where Account 1 went

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/43966194-3a13c11c-9c8f-11e8-9f81-cf4c5a902047.png)

**Expected result:**
No idea but looks like an wallet is created and should be shown. If shown should have the same password to unlock it

**Reproduces how often:**
Close to 100% if the browser doesn't crash

### Brave Version

Brave | 0.25.401
-- | --
V8 | 6.8.275.24
rev | 248c4e4
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
@LaurenWags also saw this behaviour on one of the profile she created.

**Comment by Slava** [comment]
I tweaked the logic to always count the "visible accounts" the same way they are decided when displayed at the dashboard

**Comment by GeetaSarvadnya** [comment]
After restart browser is getting crashed. Although the step 3 is creating Account 1 ( even this not stable sometimes, before clicking on New wallet create account will be created be default in fresh profile. sometimes Account 1 and Account 2 both gets created in one click on new wallet create).

Step 4 is causing the browser crash. Please find the crash id below:

1. Local Crash ID 683b1c14-9441-4758-9639-494328f39939
2. Local Crash ID 2a5c1c76-84f5-49ae-a3ad-c765d74cbe58

**Comment by Slava** [comment]
fixed on master
