### ISSUE TITLE
not always prompted for password ETH Wallet page

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14992]
### Description
Some scenarios are prompting for password to display ETH Wallet page:
- switching between Preference pages (i.e. clicking on Sync and then back on ETH Wallet)
- Close and relaunch Brave when the ETH Wallet page is the active tab

However, some scenarios are not prompting for password:
1. Switch from about:preferences#ethwallet to another open tab/open a new tab and go back to about:preferences#ethwallet --> not prompted for password
2. Switch between a window with about:preferences#ethwallet loaded and another Brave window --> not prompted for password
3. Switch between Brave with about:preferences#ethwallet as the active tab and another app on your laptop (Slack for example), and go back to Brave --> not prompted for password

### Steps to Reproduce

Scenario 1
1. Have 1 window, a few tabs open.
2. Open about:preferences#ethwallet --> prompted for password.
3. Enter correct password.
4. Switch to another open tab.
5. Switch focus back to tab displaying about:preferences#ethwallet --> not prompted for password
6. Open a new tab, navigate to a site.
7. Switch focus back to tab displaying about:preferences#ethwallet --> not prompted for password

Scenario 2
1. Have 2 windows, a few tabs open in each window.
2. Open about:preferences#ethwallet in one of the windows --> prompted for password.
3. Enter correct password.
4. Switch to another Brave window.
5. Switch focus back to window displaying about:preferences#ethwallet --> not prompted for password
6. Open a new window, navigate to a site.
7. Switch focus back to window displaying about:preferences#ethwallet --> not prompted for password

Scenario 3
1. Have at least 1 window, a few tabs open.
2. Open about:preferences#ethwallet --> prompted for password.
3. Enter correct password.
4. Switch to another app on your laptop, such as Slack.
5. Switch focus back to Brave displaying about:preferences#ethwallet --> not prompted for password

**Actual result:**
not prompted for password

**Expected result:**
should be prompted for password

**Reproduces how often:**
easily

### Brave Version

 
Brave: 0.25.401 
V8: 6.8.275.24 
rev: 248c4e4dca53045aeb94da39de4e9ccdc0a3ed23 
Muon: 8.0.6 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
n/a

### Additional Information
reproduced by @srirambv @kjozwiak

**Comment by tomlowenthal** [comment]
We discussed the heuristic for password prompts at the standup. @kjozwiak can you check that these cases are all covered by those rules?

**Comment by LaurenWags** [comment]
@tomlowenthal to confirm, @kjozwiak mentioned that the password prompt will only appear if you switch the from `about:preferences#ethwallet` to something else. If you leave that tab open and open new tabs, new windows etc... you shouldn't be prompted to enter your password. Basically, as long as `about:preferences#ethwallet` is open somewhere in your browsing session, you shouldn't be prompted when you go back to that tab.

Is the above an accurate summation of the password functionality? If so, can this be added to the spec? It doesn't seem very secure/safe - especially now that we're not required to enter a password when sending funds.
