### ISSUE TITLE
Trezor gets detected but doesn't list wallet created

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14994]
### Description
Trezor gets detected but doesn't list wallet created

### Steps to Reproduce
  1. Build 0.25.401
  2. Create ETH wallet and transfer funds
  3. Create a Test wallet on Trezor and connect device 
  4. Console shows the device being recognized but the wallet doesn't show up on UI

**Actual result:**
```
INFO [08-10|20:59:56.802] Old wallet dropped                       url=trezor://\\\\?\\hid#vid_534c&pid_0…
INFO [08-10|21:00:01.853] New wallet appeared                      url=trezor://\\\\?\\hid#vid_534c&pid_0… status="Trezor v1.6.2 'Brave' online"
WARN [08-10|21:00:02.572] USB wallet account derivation failed     url=trezor://\\\\?\\hid#vid_534c&pid_0… err="trezor: expected reply types [EthereumAddress], got Features"
```
All wallets are created in browser, with h/w Trezor connected doesn't show the wallet
![image](https://user-images.githubusercontent.com/17010094/43986579-e6309672-9ce0-11e8-968f-9def07e7bb54.png)

**Expected result:**
Should show the h/w wallet and should be allowed to transfer funds

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.401
-- | --
V8 | 6.8.275.24
rev | 248c4e4
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
@LaurenWags found similar issue on mac with following errors
```
WARN [08-10|17:42:40.680] USB wallet balance retrieval failed      url=trezor://IOService:/AppleACPIPl…                                                  err="no suitable peers available"
```

**Comment by LaurenWags** [comment]
I'm now seeing this when connecting a Trezor:

```
WARN [08-13|21:05:32.290] New wallet appeared, failed to open      url=trezor://IOService:/AppleACPIPl…                                                  err="trezor: pin needed"
```

However, Brave isn't showing me the pin pad I would expect so I could unlock my Trezor. Is there another way I'm supposed to unlock it?
