### ISSUE TITLE
able to click on ETH Wallet UI buttons before entering a password

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14990]
### Description
When you load up the ETH wallet page, you are able to quickly click on the UI buttons (Contracts, Add Wallet, etc) before you are prompted for a password. This is particularly bad in the case where you click on 'New ETH Wallet' because then you've created an account and haven't entered a password. 

### Steps to Reproduce

  1. Launch 0.25.401 with clean profile.
  2. Enable ETH Wallet
  3. Quickly click on UI buttons before you are prompted for a password (Contracts, New ETH Wallet, etc)
  4. If you clicked on New ETH Wallet, you will get prompted for 'Unlock ETH Wallet' but you haven't entered a password yet.

**Actual result:**
There is a delay before password prompt is shown, so user can click around and could potentially lock themselves out of this page
![image](https://user-images.githubusercontent.com/28145373/43967614-c7167b4c-9c92-11e8-9276-ce64fb42c00d.png)

**Expected result:**
User should not be able to click on buttons in UI prior to entering a password

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.25.401 
V8: 6.8.275.24 
rev: 248c4e4dca53045aeb94da39de4e9ccdc0a3ed23 
Muon: 8.0.6 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
n/a

### Additional Information
Reproduced by @srirambv @kjozwiak @GeetaSarvadnya

**Comment by Slava** [comment]
I build the UI for showing a spinner but for some reason that hasn't been working (but only when integrated with the browser, not in the stand-alone app).

Have you been able to actually create an account this way? I remember putting in logic to prevent any operations from happening if the password is absent.

**Comment by Slava** [comment]
I added a check that makes the button not do anything until you unlock the app

**Comment by GeetaSarvadnya** [comment]
Issue still not fixed. After enabling Eth wallet switch, user is still able to click on Contracts and Fund your wallet button. Hence reopening the issue

**Comment by tomlowenthal** [comment]
Sounds like this was re-opened after testing on an issue without the change in. Please re-open after testing on the latest build (Beta channel 0.23.100 as of right now).

**Comment by kjozwiak** [comment]
@LaurenWags @GeetaSarvadnya mind re-checking this using `0.23.100` which should include this fix as per @tomlowenthal's above comment?

**Comment by LaurenWags** [comment]
Using 0.23.100 on macOS I am seeing the same as @kjozwiak : 
- clicked on `New ETH Wallet` button several times before getting the password modal and didn't run into the issue of the wallet being created without a password being entered.
- still able to click on `Contracts`, `Send`, `Fund Brave Wallet` before getting the password modal and those pages displayed.

**Comment by kjozwiak** [comment]
Thanks @LaurenWags! @tomlowenthal can we look into locking the entire UI in the following cases:
* new user enabling the feature, shouldn't be able to use/click the UI until a password is created
* existing user shouldn't be able to use the UI until their password as been inserted which then unlocks and makes the UI usable.
