### ISSUE TITLE
New ETH wallet doesn't create new wallet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14991]
### Description
New ETH wallet doesn't create new wallet

### Steps to Reproduce
  1. Clean profile from 0.25.401
  2. Enable ETH wallet, wait till password prompt is shown
  3. Click on ETH wallet button doesn't create wallet. Click again doesn't show up or create wallet
  4. Move away from ETH wallet and switch back, asks for Unlock, but still doesn't show wallets created

**Actual result:**
![flashing wallet](https://user-images.githubusercontent.com/17010094/43970774-a62cafc8-9c9c-11e8-9657-2e03a7b8387a.gif)

**Expected result:**
Should show the wallet created and not show flashing message

**Reproduces how often:**
About 80% 

### Brave Version

Brave | 0.25.401
-- | --
V8 | 6.8.275.24
rev | 248c4e4
Muon | 8.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
#14961

**Comment by Slava** [comment]
I think I mitigated most of the problems, but this will continue being a problem if geth is unresponsive or inconsistent on different interfaces. I added logic that will *eventually* end up with the right set of wallets.

**Comment by GeetaSarvadnya** [comment]
Issue is still not fixed. After creating a password without clicking on New eth wallet button, a wallet is getting created and after sync, click on New Eth wallet is not creating any new wallet, even after unlock password is not showing created wallets.

**Comment by tomlowenthal** [comment]
The planned resolution is to show wallets as being "generating…" without showing their addresses or being interactable until we see them through the normal interface.

**Comment by Slava** [comment]
fixed on master
