### ISSUE TITLE
Fidelity "Fullview" stuck in endless loop

### ISSUE THREAD

**Issue by andschwa** [brave/browser-laptop#14993]
### Description

I cannot load Fidelity's "Full View" web app in Brave. Instead of loading and displaying (which works properly on the same machines with Firefox) it just loops in an endless cycle of reload.

### Steps to Reproduce

  1. Login to fidelity.com (sorry, this will be hard to repro because of that requirement)
  2. Go to https://scs.fidelity.com/customeronly/fullview.shtml
  3. Now it is refreshing in a loop without ever loading

**Actual result:**

![full view 8_10_2018 10_57_11 am](https://user-images.githubusercontent.com/2226434/43980521-59915572-9ca3-11e8-96d9-50888beff60c.gif)

**Expected result:**

The page to load.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

It also reproduced with the previous released version, and on a MacBook.

It reproduces with and without Shields.

**Reproducible on current live release:**

Yup.

**Comment by andschwa** [comment]
Anything I can try to fix this?

**Comment by bsclifton** [comment]
@andschwa can you please try turning the shields off? (the lion in the upper right). If that works, then it may be cookies or https upgrade causing the issue

**Comment by andschwa** [comment]
@bsclifton Yes, this was tried with shields off (see GIF).

**Comment by bsclifton** [comment]
@andschwa ah thanks- my bad on missing that 😄

**Comment by andschwa** [comment]
Well I have to close this, Fidelity actually just re-wrote the whole "Full View" app so you'll be unable to repro.
