### ISSUE TITLE
Fingerprinting attribute: navigator.deviceMemory

### ISSUE THREAD

**Issue by antoinevastel** [brave/browser-laptop#14996]
The attribute navigator.deviceMemory enables to obtain information about the device's memory (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory). I consider it could be used as a fingerprinting vector.

**Comment by bsclifton** [comment]
cc: @diracdeltas

**Comment by riastradh-brave** [comment]
What uses this?

According to the documentation at https://w3c.github.io/device-memory/#computing-device-memory-value, it is already rounded to a power of two between 1/4 and 8, inclusive, so there should be only possibilities: 1/4, 1/2, 1, 2, 4, 8.  Of course, for anonymity, it would be best to choose only one of those.  Which one?  I like the number 1.

cc @snyderp

**Comment by snyderp** [comment]
@riastradh-brave Unfortunately, this standard is more recent than the crawls I have.  We could consider spinning up more crawls for measuring WebAPI use, but we dont have any numbers on them currently.

My 2 cents is to nip it in the bud though and block it behind shields

**Comment by riastradh-brave** [comment]
How do you feel about always setting this to 1?

**Comment by bsclifton** [comment]
@jumde is there an issue tracking this in brave-core?

**Comment by jumde** [comment]
@bsclifton - https://github.com/brave/brave-browser/issues/1157

**Comment by bsclifton** [comment]
Closing as `open-in-brave-core` 👍 Let's re-open if it's a must for `browser-laptop`
