### ISSUE TITLE
Can't open ftp URLs anymore

### ISSUE THREAD

**Issue by thbtmntgn** [brave/browser-laptop#15004]
### Description

Since the last update I can't open FTP URLs anymore. I'm ask to "**Allow ftp: URLS to open an external application**"

### Steps to Reproduce

**Actual result:**

  1. Open a FTP URL and see what happens
<img width="1678" alt="screen shot 2018-08-13 at 09 40 58" src="https://user-images.githubusercontent.com/18198843/44018738-02f0935e-9edd-11e8-8f8a-ebdd4203433f.png">

**Expected result:**

Open the FTP URL like before.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**

I'm not using live build

**Comment by bsclifton** [comment]
@thbtmntgn this is intentional; we removed native FTP support with https://github.com/brave/browser-laptop/issues/14712

As you've noted, Brave will prompt you to use an external application. You can click `Allow` and it will open your default FTP application
