### ISSUE TITLE
Browser crashes when ETH wallet is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15009]
### Description
Browser crashes when ETH wallet is disabled

### Steps to Reproduce
1. Create new profile on `0.23.501`
2. Enable ETH Wallet, enter master password
3. Create New wallets ( i created about 15 of them)
4. Enable MetaMask wait for the extension to enable and opens MM tab
5. Go back to ETH and start creating a few more wallets (i did 5)
6. Disable ETH and it crashed the browser with following errors
7. Restart browser, starts fresh, ETH is disabled, Enabling ETH all wallets are still there but MM is disabled

**Actual result:**
Browser crashes when ETH wallet is disabled

**Expected result:**
Should not crash irrespective of MM status or ETH wallet enabled/disabled

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.501
-- | --
V8 | 6.8.275.24
rev | 775ecfa
Muon | 8.0.7
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
No

**Comment by tomlowenthal** [comment]
This might be fixed on the latest build. Please re-check to see if @ryanml's fixes resolve this.

**Comment by ryanml** [comment]
++ ^ A crash should no longer occur, thanks.
