### ISSUE TITLE
Replace `var` with ES6 syntax let and const

### ISSUE THREAD

**Issue by joshstevens19** [brave/browser-laptop#15008]
Would be awesome if we could remove as many instances of `var` as possible from the brave library and move over to the ES6 syntax `let` and `const`

**Comment by joshstevens19** [comment]
https://github.com/brave/browser-laptop/pull/15007

**Comment by bsclifton** [comment]
See comment https://github.com/brave/browser-laptop/pull/15007#issuecomment-413417173
