### ISSUE TITLE
Unable to view BAT balance in ETH Wallet

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15010]
### Description
I have an ETH Wallet with BAT in it. I am unable to view the BAT balance in Brave but I can view it in Mist.

### Steps to Reproduce

Prerequisite - Have Mist installed and have BAT Contract and Token set up in Mist
1. Using 0.25.501, launch, enable ETH Wallet, sync fully
2. Verify BAT Token is listed under ‘Custom Tokens’
3. Use Watch Contract feature to add BAT Contract.
4. Send some ETH.
5. Verify ETH is received and visible in ETH Wallet.
6. Send some BAT.
7. Verify BAT transaction is completed (verify on etherscan.io).
8. Go to Wallets, click on wallet with BAT --> BAT will not be shown in Brave ETH Wallet.
9. Go to Send --> BAT is not an option to send
10. Close Brave.
11. Copy your keystore file over to Mist install.
12. Launch Mist.
13. Click on the Wallet --> BAT is visible in the wallet copied over from Brave ETH Wallet.
14. Go to Send --> BAT is an option to send.

**Actual result:**
BAT balance not visible in ETH Wallet:

![screen shot 2018-08-13 at 7 54 29 pm](https://user-images.githubusercontent.com/28145373/44065533-4789194e-9f39-11e8-9595-f76f4012323d.png)

![screen shot 2018-08-13 at 7 54 41 pm](https://user-images.githubusercontent.com/28145373/44065537-4c72180c-9f39-11e8-828a-a8a9f54c5683.png)

**Expected result:**
BAT balance should be visible:

![screen shot 2018-08-13 at 7 53 29 pm](https://user-images.githubusercontent.com/28145373/44065545-5aac44ec-9f39-11e8-8abb-aab4f418ee9a.png)

![screen shot 2018-08-13 at 7 54 05 pm](https://user-images.githubusercontent.com/28145373/44065550-5f2a2584-9f39-11e8-821c-e6452f130907.png)

**Reproduces how often:**
easily

### Brave Version

0.25.501

**Reproducible on current live release:**
n/a

**Comment by LaurenWags** [comment]
BAToken Contract is set up in both ETH Wallet and Mist:
![screen shot 2018-08-13 at 8 46 45 pm](https://user-images.githubusercontent.com/28145373/44065684-2ed0bff0-9f3a-11e8-9253-c3d25f2904d4.png)
<img width="990" alt="screen shot 2018-08-13 at 8 46 53 pm" src="https://user-images.githubusercontent.com/28145373/44065686-30ca258a-9f3a-11e8-83b1-7401e352a5b5.png">

**Comment by tomlowenthal** [comment]
Please re-test on current build. Please do not add any custom contracts or tokens or anything.
