### ISSUE TITLE
ETH wallet doesn't balance correctly 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15014]
### Description
ETH wallet doesn't balance correctly 

### Steps to Reproduce

  1. Clean profile on `0.23.100` using `GETH_LOG=1 ETHEREUM_NETWORK=ropsten <path to binary>`
  2. Enable ETH, wait for wallet to be auto-generated (0x1AB00c2004B6C2D547749836167e254e93258BE7)
  3. Enable MM, create a test wallet on Ropsten and transfer 1 ETH on test network
  4. Transfer 0.5 ETH from MM wallet to ETH wallet (https://ropsten.etherscan.io/tx/0x118f9f9129b13fbbcf4f2fd5a104c4454329d0a1a196b079d74fb463073a3d1b)
  5. Transfer 1ETH to ETH wallet using the curl command (https://ropsten.etherscan.io/tx/0xa37d9e8080310fbdf9a532c17953f06c4b6b819e7b1a0a08d966b1f0b223c69d)
  6. Wallet doesn't get updated even though the transactions on etherscan show success 

**Actual result:**
Testnet ETH Transaction via curl command
![image](https://user-images.githubusercontent.com/17010094/44094791-20a11f72-9fa5-11e8-9f47-1ec60f6559a3.png)
MM-ETH wallet transfer of 0.50ETH
![image](https://user-images.githubusercontent.com/17010094/44094828-36305236-9fa5-11e8-9ff0-1c94fb384a00.png)
Actual Wallet status
![image](https://user-images.githubusercontent.com/17010094/44094856-461e2fce-9fa5-11e8-886a-98b5225ebcfc.png)

**Expected result:**
Should show correct balance in ETH Wallet based on successful transactions

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.100
-- | --
V8 | 6.8.275.24
rev | 5e197a1
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
Not sure if the block sync matters here?

**Comment by Slava** [comment]
The syncing of blocks is very important here, because the blocks contain the information about the transactions.

**Comment by tomlowenthal** [comment]
Please re-open if you still see this issue when you're in sync with the blockchain (number less than one minute since the most recent block in the top right).
