### ISSUE TITLE
use bcrypt native bindings instead of the JS-only implementation

### ISSUE THREAD

**Issue by Slava** [brave/browser-laptop#15026]
Instead of using a possibly outdated `bcryptjs` module, switch to `bcrypt` (native bindings).

**Comment by diracdeltas** [comment]
@Slava didn't we resolve this in slack? (using dcode io library) can this be closed?

**Comment by tomlowenthal** [comment]
@Slava — please close at your leisure.

**Comment by Slava** [comment]
I think we determined that `bcryptjs` is reasonably up to date and is maintained.
