### ISSUE TITLE
Merged Review Issue: unsafe eval

### ISSUE THREAD

**Issue by tomlowenthal** [brave/browser-laptop#15020]
This is one of the PR issues from https://github.com/brave/browser-laptop/pull/14734

Check this out: https://github.com/brave/browser-laptop/pull/14734#discussion_r205273837

**Comment by mrose17** [comment]
there are two illuminating posts: 

- https://github.com/MyCryptoHQ/MyCrypto/issues/2061
- https://github.com/MetaMask/metamask-extension/issues/3133

which come down to the same issue we are seeing. the latter issue is perhaps more instructive when looking at https://github.com/brave/browser-laptop/blob/master/app/extensions.js#L305

@diracdeltas - the short answer to https://github.com/brave/browser-laptop/pull/14734#discussion_r205273837 is that, at present, the answer appears to be yes ... providing that i can review the code corresponding to the two hashes.  i have asked the metamask folks for help in identifying the fragments for review.
