### ISSUE TITLE
New ETH Wallet gets stuck at Generating...

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15039]
### Description
New ETH Wallet gets stuck at Generating...

### Steps to Reproduce

  1. Build from master (6ab4f6107c849130e45815f1b58bc59c56a9ba29)
  2. Enable ETH and wait for wallet to be created
  3. Sometimes shows Generating even though wallet is created and shows `Account 1`
  4. Click on New ETH Wallet button, shows `Generating...` if blocks starts syncing it gets stuck on this
  5. Click on `Generating...` just shows spinner doesn't go back . 
  6. Click on other preferences menu option doesn't change webview

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/44208519-9549a800-a12e-11e8-88a7-1f2cd7d13c8f.png)

**Expected result:**
Should create wallet successfully, Generating message shouldn't be clickable as it casues the browser to hang. 

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.8.275.24
rev | 6ab4f61
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
cc: @bkero for sync related issue, @Slava @ryanml @mrose17 
@LaurenWags @kjozwiak to verify on macOS

**Comment by LaurenWags** [comment]
Reproduces on macOS using https://github.com/brave/browser-laptop/commit/6ab4f6107c849130e45815f1b58bc59c56a9ba29

**Comment by srirambv** [comment]
Wallets stuck in `Generating...` doesn't get created after block sync is complete.

**Comment by Slava** [comment]
After a little more research I think we are hitting the situation described in this issue: 
https://github.com/ethereum/go-ethereum/issues/17211
