### ISSUE TITLE
Report of potential accounting issue (reported time spent) in ledger.

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#15048]
### Description

We received a report in the BAT Community subreddit of a potential reporting issue for the time spent metric in the BP ledger. 

Link to original report: https://www.reddit.com/r/BATProject/comments/97y07p/possible_bat_click_fraud_found_reviewing_my/

> Checking my BAT payments before they were distributed, found this website (below) with 18 hr time spent this month. It's possible I went to this site at some point in the month (don't remember it), but definitely did not spend 18 hrs on it. If I left it open in a tab or something, I imagine this shouldn't count. Just wanted to put this out there.

Image supplied in original report for the domain in question: 
<img width="896" alt="brave-ledger-report-08162018-bitwage" src="https://user-images.githubusercontent.com/8979240/44247383-d8406580-a198-11e8-8f6e-057d8b494ef1.png">

Needs info and investigation. 
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Closing as we move to [brave-core](https://github.com/brave/brave-browser). Let's re-open if the issue occurs once Brave Rewards is finished and launches
