### ISSUE TITLE
Payments FAQ opens in the same iframe instead of opening in a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15040]
### Description
Payments FAQ opens in the same iframe instead of opening in a new tab

### Steps to Reproduce

  1. Build from master (6ab4f61)
  2. Enable ETH, Click on Fund Brave Wallet 
  3. Click on FAQ hyper link, opens in the same iframe
  4. Click browser back button, doesn't go back to ETH, have to navigate to other preferences option and back to ETH to see the ETH interface

**Actual result:**
![faq](https://user-images.githubusercontent.com/17010094/44209054-40a72c80-a130-11e8-9262-5deb5420ea1c.gif)

**Expected result:**
Should open FAQ in a new tab

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.8.275.24
rev | 6ab4f61
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
cc: @kjozwiak @LaurenWags @GeetaSarvadnya

**Comment by LaurenWags** [comment]
STR reproduce on macOS:

![15040](https://user-images.githubusercontent.com/28145373/44214745-db0e6c80-a13e-11e8-8dba-144c0d89d273.gif)

**Comment by Slava** [comment]
good catch, fixing it in the next PR
