### ISSUE TITLE
Enable Brave wallet is not enabling the payments

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#15042]
### Description
Click on 'Enable Brave Wallet' link in the Fund Brave wallet page is not enabling the brave payment. Click on link does nothing in fact. The below two scenarios behaves the same. But, Initially if you toggle the payment switch ON and OFF and then click on 'Enable Brave wallet' will make payment switch ON and it shows brave wallet address immediately.

### Description
Enable Brave wallet is not enabling the payments

### Steps to Reproduce

Scenario 1:

  1. Build from source (Master -6ab4f61)
  2. Launch browser using  ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging GETH_LOG=1 npm run start
  3. Enable Eth-wallet and click on 'Fund Brave wallet'
  4. Click on Enable Brave wallet

Scenario 2:

1. Build from source (Master -6ab4f61)
2. Launch browser using  ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging GETH_LOG=1 npm run start
3. Enable Eth-wallet
4. Enable Payment
5. Delete the wallet from payment
6. Switch to eth wallet and click on 'Fund Brave wallet'
7. Click on Enable Brave wallet

**Actual result:**
Enable Brave wallet is not enabling the payments
![enable brave wallet is not enabling payments](https://user-images.githubusercontent.com/38657976/44210594-8b529400-a184-11e8-86e4-5a649692bae0.gif)

**Expected result:**
Click on Enable Brave wallet should enable the payments and page should get refresh and display brave payment BAT address in To filed

**Reproduces how often:**
Always

### Brave Version
0.25.0
**about:brave info:**
Brave: 0.25.0
V8: 6.8.275.24
rev: 6ab4f6107c849130e45815f1b58bc59c56a9ba29
Muon: 8.0.8
OS Release: 10.0.17134
Update Channel: 
OS Architecture: x64
OS Platform: Microsoft Windows
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
NA

### Additional Information
cc: @kjozwiak @LaurenWags @srirambv

**Comment by LaurenWags** [comment]
Reproduces on macOS
