### ISSUE TITLE
Transactions are failing due to password authentication

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#15043]
### Description
Transactions are failing due to password authentication

### Steps to Reproduce

  1. Build from source (Master -6ab4f61)
  2. Launch browser using ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging 
      GETH_LOG=1 LEDGER_VERBOSE=true npm run start
  3. Enable Eth-wallet
  4. Create Eth wallet
  5. Add Funds to Eth-wallet through http://faucet.ropsten.be:3001/
  6. Enable payments
  7. Click on Fund Brave wallet and verify Brave wallet address is displayed in To filed
  8. Wait until blocks gets synced
  9. Transfer the funds from eth wallet to Brave wallet once the sync is completed

**Actual result:**
Transactions are failing due to password authentication
![transaction is failing due to password authentication](https://user-images.githubusercontent.com/38657976/44214139-0a4bca80-a18d-11e8-811b-f6f3f05e4851.gif)

**Expected result:**
Transaction should be successful without any issue

**Reproduces how often:**
100%

### Brave Version
0.25.0
**about:brave info:**
Brave: 0.25.0
V8: 6.8.275.24
rev: 6ab4f6107c849130e45815f1b58bc59c56a9ba29
Muon: 8.0.8
OS Release: 10.0.17134
Update Channel: 
OS Architecture: x64
OS Platform: Microsoft Windows
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
NA

### Additional Information
cc : @kjozwiak @LaurenWags @srirambv

**Comment by Slava** [comment]
Looking into this
