### ISSUE TITLE
Bitwarden extension icon does not move focus to 'Search vault' field when pressed.

### ISSUE THREAD

**Issue by drasbeck** [brave/browser-laptop#15049]
### Description

Bitwarden extension icon does not move focus to 'Search vault' field when pressed.

### Steps to Reproduce

  1. Be logged in to Bitwarden.
  2. Activate Bitwarden by pressing the extension icon top right.

**Actual result:**

'Search vault' field is not in focus, as it should be.

**Expected result:**
'Search vault' field is in focus and searching for passwords can immediately begin. This behavior is seen when the same actions are taken in other browsers' Bitwarden extensions.

**Reproduces how often:**

Always.

### Brave Version

**about:brave info:**

0.23.79 rev 51b4905

### OS Version
macOS 10.13.6 (17G65)

**Comment by bsclifton** [comment]
This should be fixed with our new Developer channel build. It's experimental at the moment, but if you were able to confirm that would be great 😄 
https://brave.com/download-dev

Also available at:
https://github.com/brave/brave-browser/releases/tag/v0.55.1
