### ISSUE TITLE
Brave Wallet deleted in a different tab still shows up on ETH wallet 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15041]
### Description
Brave Wallet deleted in a different tab still shows up on ETH wallet 

### Steps to Reproduce
  1. Build from master (6ab4f61), launch a clean profile
  2. Enable ETH Wallet, click on Fund Brave Wallet, shows placeholder text to enable payment
  3. In the same tab go to Payments and enable it 
  4. On the same tab go back to ETH wallet and fund brave wallet, shows brave wallet address pre-populated
  5. Go back to payments and delete wallet from advance settings
  6. Go back to ETH wallet and fund brave wallet, shows placeholder text
  7. Open preferences in a new tab and enable payments
  8. Go back to ETH wallet on previous tab(where you did steps 2-6), Fund brave wallet, shows the new wallet address
  9. Go back to second preferences tab from step 7 and delete payments wallet
 10. Switch back to first preference page with ETH Wallet, fund brave wallet retains Brave wallet address even though it was deleted in step 9 on second preferences page
 11. Click any other preferences menu and back to ETH wallet and fund brave wallet still retains the second wallet address even though the wallet is deleted

**Actual result:**
Watch full recording to see the issue
![wallet](https://user-images.githubusercontent.com/17010094/44209794-8533c780-a132-11e8-83cc-36ebcba85e7b.gif)

**Expected result:**
Should be aware of Brave wallet being deleted on other tabs

**Reproduces how often:**
100% on master

### Brave Version

Brave | 0.25.0
-- | --
V8 | 6.8.275.24
rev | 6ab4f61
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel |  
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
cc: @mrose17 @Slava @ryanml @kjozwiak @LaurenWags @GeetaSarvadnya

**Comment by LaurenWags** [comment]
reproduced on macOS usinghttps://github.com/brave/browser-laptop/commit/6ab4f6107c849130e45815f1b58bc59c56a9ba29
