### ISSUE TITLE
Account balance: 0 BAT but there is also 20 BAT in the wallet

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#15052]
![balance](https://user-images.githubusercontent.com/1102886/44313821-63c32c00-a40f-11e8-8321-8924ac74b082.png)

Brave version 0.23.79 on Fedora 28 Linux. (I’m assuming the data format means November 1st 2018, but it’s hard to tell. Could have expired on January 11th, 2018. I’ve had this profile for years now.)

**Comment by NejcZdovc** [comment]
@da2x hi, is you contribution currently in progress?

**Comment by da2x** [comment]
@NejcZdovc, yes and it’s been in progress since the first or second week of July. I’m also getting notices about having to add funds to my wallet every few days.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/account-balance-incorrectly-showing-zero/30634

**Comment by da2x** [comment]
For the record, I emailed @NejcZdovc the requested details.

**Comment by LaurenWags** [comment]
@da2x Did your contribution go through? I was told that a server-side issue was hit and resolved.

**Comment by da2x** [comment]
@LaurenWags no. I restarted Brave after I saw your notification a few hours ago, and it still haven’t gone through. It still says “Currently processing” and the balance is as shown in the above screenshot.

**Comment by LaurenWags** [comment]
Thanks for reporting back @da2x - seems as though there's another issue that needs to be resolved. cc @evq

**Comment by da2x** [comment]
Still haven’t gone through. I’ve left Brave running for over a day now. I tried restarting it again just now and it’s still the same.

**Comment by da2x** [comment]
I’ve actually got a second computer that I only use occasionally. It seems to be having the exact same problem.

**Comment by da2x** [comment]
I updated Brave, was offered more free tokens, and claimed these some three hours ago. My wallet still shows the same 20 BAT as before (no sign of the new tokens), and it’s still processing. I’ve restarted the browser twice now but still same result.

**Comment by LaurenWags** [comment]
I believe your balance will not update while in a processing state, but @NejcZdovc could correct me if I'm wrong on that.

**Comment by NejcZdovc** [comment]
@LaurenWags balance should update when you restart the browser

**Comment by da2x** [comment]
Today, the balance is correct (on both systems). However, it still says Currently processing and no ccontribution have gone through.

**Comment by da2x** [comment]
Situation is unchanged. Still currently processing.

**Comment by bsclifton** [comment]
Closing as Brave Payments is deprecated in favor of Brave Rewards. The new version of brave is now available:
https://brave.com/download
