### ISSUE TITLE
Drag and drop the triangle to wrong color will not change the new captcha immediately

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#15056]
### Description
Drag and drop the triangle to wrong color will not change the new captcha immediately

### Steps to Reproduce

  1. Launch Brave with clean profile from CLI
  2. Make the payment switch ON
  3. Click on Claim my free tokens
  4. Drag and drop the triangle to wrong color
  5. Observe that the Captch will not change immediately

**Actual result:**
Drag and drop the triangle to wrong color will not change the new captcha immediately
![capthc won t change](https://user-images.githubusercontent.com/38657976/44340579-e812bf00-a4a2-11e8-9fcd-3dc7f672f678.gif)

**Expected result:**
Drag and drop the triangle to wrong color should change the new captcha immediately

**Reproduces how often:**
Always

### Brave Version
0.23.102
**about:brave info:**
 
Brave: 0.23.102 
V8: 6.8.275.24 
rev: 43eb6673e6601527129f3f9f96aade08d15bc671 
Muon: 8.0.8 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
NA

### Additional Information
cc: @kjozwiak @LaurenWags @srirambv @btlechowski
 
 #14980

**Comment by kjozwiak** [comment]
I noticed the same thing happening on macOS. When you pick the wrong colour/location a few times, it seems like the server doesn't keep up with the requests and eventually falls behind. When this happens, you'll sometimes get a delay before the CAPCHA is updated. Sometimes it also flashes 2-3 CAPTCHA's as it's trying to catch up with the requests, Example:

![captcha](https://user-images.githubusercontent.com/2602313/44345445-651d4480-a461-11e8-8cb6-eba81a688bab.gif)

**Comment by kjozwiak** [comment]
Closing the issue. Quickly talked to @evq and confirmed this was fixed. There was a bug in the backend where it would generate one of the colours which caused the request to hang until load the balancer timed out 30 seconds later.

**Comment by kjozwiak** [comment]
Verified on `macOS 10.13.6 x64` using the following build:
 
* `0.23.104` b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
* muon: `8.0.8` 
* libchromiumcontent: `68.0.3440.84`
