### ISSUE TITLE
Drag and drop on correct colour doesn't claim grant

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15058]
### Description
Drag and drop on correct colour doesn't claim grant

### Steps to Reproduce

  1. Launch clean profile on `0.23.102` using `LEDGER_ENVIRONMENT=staging LEDGER_VERSBOE=true <binarypath>
  2. Click `Claim token` button to bring up the CAPTCHA
  3. Dnd on wrong colour, complains not quite right
  4. Repeat step 3 several times and check console, shows the following errors
```
WalletProperties refreshes payment info
<<< PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/grants/194e99c9-062e-4436-9e8f-9a9c12d8b3b1
<<< content-type: application/json; charset=utf-8
<<< user-agent: Brave/0.23.102 Chrome/68.0.3440.84 Muon/8.0.8 Microsoft Windows x64
<<< accept-encoding:
<<<
<<< {
<<<   "promotionId": "9354b7e3-eb81-40d2-a4d5-a615285082ce",
<<<   "captchaResponse": {
<<<     "x": 746,
<<<     "y": 137
<<<   }
<<< }
[ response for PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/grants/194e99c9-062e-4436-9e8f-9a9c12d8b3b1 ]
>>> HTTP/1.1 403
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 60
>>> content-type: application/json; charset=utf-8
>>> date: Mon, 20 Aug 2018 12:41:39 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>>
>>> {"statusCode":403,"error":"Forbidden","message":"Forbidden"}
Problem claiming promotion Error: HTTP response 403 for PUT /v2/grants/194e99c9-062e-4436-9e8f-9a9c12d8b3b1
<<< GET https://ledger-staging.mercury.basicattentiontoken.org/v2/captchas/194e99c9-062e-4436-9e8f-9a9c12d8b3b1
<<< content-type: application/json; charset=utf-8
<<< user-agent: Brave/0.23.102 Chrome/68.0.3440.84 Muon/8.0.8 Microsoft Windows x64
<<< accept-encoding:
```
   5. Now dnd on the actual colour mentioned in the CAPTCHA modal, still shows the same errors but doesn't claim the grant

**Actual result:**
https://drive.google.com/open?id=1VZ632KMsQZKdF3wYWefaUEeG834v6wzI

**Expected result:**
Should claim grant when dnd on the specified colour

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.102
-- | --
V8 | 6.8.275.24
rev | 43eb667
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

### Additional Information
Causes #15054  as well when dnd on wrong colour.

**Comment by srirambv** [comment]
Happy path flow works great. Dnd on the specified colour claims the grant but issue happens only when multiple times it shows failure message

**Comment by kjozwiak** [comment]
Usually run into this pretty regularly as well. Dropping the BAT icon into the correct colour just outputs the following in the terminal:

`>>> {"statusCode":403,"error":"Forbidden","message":"Forbidden"}`

Example of the issue occurring:

![captchaforbidden](https://user-images.githubusercontent.com/2602313/44414363-95d1ac80-a53b-11e8-88f8-4233d02c3d0b.gif)

**Comment by kjozwiak** [comment]
Closing. Talked to @evq and confirmed here were a few issues fixed in the backend regarding timeouts and generating the correct colours.

**Comment by kjozwiak** [comment]
Verified on `macOS 10.13.6 x64` using the following build:

 
* `0.23.104` b454a4a99934c4aa27fbe2effc5f72ce92e3266b
* muon: `8.0.8`
* libchromiumcontent: `68.0.3440.84`
