### ISSUE TITLE
Bitwarden becomes unresponsive when offering to remember password

### ISSUE THREAD

**Issue by JohnstonCode** [brave/browser-laptop#15055]
### Description
Bitwarden becomes unresponsive in tabs where "Should Bitwarden remember this password for you?"

### Steps to Reproduce

  1. Log into a website that Bitwarden doesn't have saved credentials for

**Actual result:**
Banner will show and unable to accept or dismiss
Shortcut icon also unresponsive

**Expected result:**
Should be able to accept or dismiss the banner

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 4.17.12-200.fc28.x86_64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
This should be fixed with our new Developer channel build. It's experimental at the moment, but if you were able to confirm that would be great 😄 
https://brave.com/download-dev

Also available at:
https://github.com/brave/brave-browser/releases/tag/v0.55.1

**Comment by JohnstonCode** [comment]
Yes, it works as expected in the Dev build. Love the look of the dev build!
