### ISSUE TITLE
Can't open HTML file with Brave

### ISSUE THREAD

**Issue by selectiveduplicate** [brave/browser-laptop#15051]
### Description

Brave can't seem to open any .html file. When selecting "open with" and then Brave browser, the browser just opens normally with the "dashboard" but the html file isn't showed/opened.

### Steps to Reproduce
  1. Select any .html file
  2. Open it with Brave browser

**Actual result:**
Brave opens with its Dashboard, the file isn't opened.

**Expected result:**
The local .html file should be opened.

**Reproduces how often:**
So far, every time I've tried opening an .html file.

### Brave Version
**about:brave info:**
Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 4.15.0-32-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux(Ubuntu MATE 18.04)
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
***I'm using Brave as a snap.***

If any additional info is needed, I'd be happy to provide them...

Regards,
Sakib

**Comment by bsclifton** [comment]
@selectiveduplicate you're trying to drag it into the window, right? This is definitely a known issue

Closing in favor of https://github.com/brave/brave-browser/issues/887

**Comment by bsclifton** [comment]
Disregard my last comment! Just re-read your issue

**Comment by selectiveduplicate** [comment]
I'm sorry but I don't understand what you're saying... the problem has been added to milestone...
Is there any way that I can help or contribute?

**Comment by bsclifton** [comment]
@selectiveduplicate no worries - error was on my side 😄 I need to be better at reading. Apologies

**Comment by somkun** [comment]
Additional information: If brave is already open, all windows are closed and the dashboard is opened as above.

**Comment by bsclifton** [comment]
We won't be able to address this in the current code-base (browser-laptop/Muon). For folks experiencing this, can you please try our new Beta release? (you can import your settings from existing Brave install)
https://brave.com/download-beta

**Comment by selectiveduplicate** [comment]
Will do... is the above link the ``brave-browser`` that's coming in the future? I'm using the snap version of Brave, which I think is from this ``brave-laptop``, am I correct?

**Comment by srirambv** [comment]
@selectiveduplicate that is correct. Please follow the link https://brave.com/download-beta and you will find the steps to install brave-browser-beta on Linux
