### ISSUE TITLE
I Can't get Ytel or MyCallCloud to work for work on Brave

### ISSUE THREAD

**Issue by lalascott7** [brave/browser-laptop#15069]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by srirambv** [comment]
Please fill out the issue template with details and reopen the issue. The title isn't really clear to do any kind of troubleshooting

**Comment by lalascott7** [comment]
Never mind. Thanks for the quick response. I decided to not use it. Thanks for your time. I will delete my post.
