### ISSUE TITLE
Fullscreen bug on multi-monitor setup.

### ISSUE THREAD

**Issue by Craig-segd** [brave/browser-laptop#15063]
### Description
If I maximise Brave within any of my monitors, there is a slight overlap onto the other monitor which resembles a long white line on the other monitor.

### Steps to Reproduce
  1. Open Brave 
  2. Maximise the window on a multi-monitor setup on either monitor.
  3. Look at the other monitor's edge (an issue on either monitor).

**Actual result:**
https://i.imgur.com/PCz24Wc.jpg

**Expected result:**
No overlap on other monitor.

**Reproduces how often:**
Every time I maximise the browser.

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.23.79
V8 | 6.8.275.24
rev | 51b4905
Muon | 8.0.7
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
Yes, the latest live release.

### Additional Information

My PC setup.
_Intel(R) Core(TM) i7-7700K CPU @ 4.80GHz
ASUS STRIX Z270H GAMING
2 x ASUS ROG PG248Q 24" monitors
ASUS STRIX GTX 1080 8GB
Corsair 16GB DDR4 Vengeance RAM_

**Comment by chrispickford** [comment]
This has also been a long standing issue for me. Please prioritise as it's actually quite annoying.

**Comment by Craig-segd** [comment]
I'm assuming this was a silent fix? I don't seem to be having the issue now.

**Comment by bsclifton** [comment]
@chrispickford can you please try our new [developer channel release](https://brave.com/download-dev)?
