### ISSUE TITLE
reducing time for the ref headers fetch at startup

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15067]
### Description

Because of https://github.com/brave/browser-laptop/pull/14620, we fetch the headers anywhere between 30s -1min after startup. Because of this change, users won't see the promotion tab at startup when installing either MW/Barrons (dowjones promotion). Users might not wait the 1min and just assume that the promotion is either over or broken.

### Steps to Reproduce

  1. Download one of the promotional executables from either https://brave.com/dowjones-barrons or https://brave.com/dowjones-marketwatch
  2. Once downloaded, install the build and launch Brave
  3. Wait 30s - 1min and you'll notice the promotional tab will finally appear

**Actual result:**

https://youtu.be/KhM8GmenI4k

**Expected result:**

Promotional tabs should appear a few seconds after startup and not 30s -1min after startup. Might give the users the impressing that it's either broken or the promotion has ended.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
```

**Reproducible on current live release:**

Yes, currently reproducible on `0.23.79` 51b49051a779f0db94fbcfd0df5faca781299ea0 which is the current live version.

**Comment by srirambv** [comment]
Verified on Windows 10 x64
* 0.23.104 b454a4a
* Muon `8.0.8`
*libchromiumcontent  `68.0.3440.84`
