### ISSUE TITLE
CAPTCHA targets should always have some spacing between them

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15060]
### Description
CAPTCHA targets should always have some spacing between them

**Actual result:**
![image](https://user-images.githubusercontent.com/17010094/44354571-365e9880-a478-11e8-9ce4-6cf885dcc768.png)

**Expected result:**
Should not overlap or be next to each other

**Reproduces how often:**
Can't put a number. Keep dropping on wrong target and hope you get this screen

### Brave Version

Brave | 0.23.102
-- | --
V8 | 6.8.275.24
rev | 43eb667
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
N/A

**Comment by NejcZdovc** [comment]
should be fixed

**Comment by kjozwiak** [comment]
@NejcZdovc I don't see a PR associated with this bug. Was this fixed via server side?

**Comment by NejcZdovc** [comment]
@kjozwiak yes

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.102 43eb667
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
