### ISSUE TITLE
"View Certificate" and "Open full certificate details" in the Developer Tools don't appear to work.

### ISSUE THREAD

**Issue by jsparknz** [brave/browser-laptop#15064]
### Description
When trying to view a SSL certificate for a site delivered over HTTPS, the "View Certificate" and "Open full certificate details" buttons in the Developer Tools console don't result in anything additional being displayed.

### Steps to Reproduce
  1. Browse to a website that is delivered over HTTPS (eg. https://brave.com)
  2. Press F12 to bring up the Developer Tools console.
  3. Click onto the Security tab.
  4. Click the View Certificate button (nothing happens)
  5. Click onto any of the origins (main or secure).
  6. Click the "Open full certificate details" button (nothing happens). 

**Actual result:**
Nothing happens

**Expected result:**
Display of the full security certificate.

**Reproduces how often:**
100% of the time.

### Brave Version

**about:brave info:**
0.23.79

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
@jsparknz what OS are you on? This should have been fixed with https://github.com/brave/browser-laptop/issues/2611, however this does not work on Linux (see https://github.com/brave/browser-laptop/issues/7669 which we've marked as `wontfix`)

**Comment by jsparknz** [comment]
@bsclifton I'm on Ubuntu 18.04 mostly. My apologies, I only searched open issues when checking for existing issues.

**Comment by bsclifton** [comment]
@jsparknz no worries- we should have this fixed with our upcoming [brave-core](https://github.com/brave/brave-browser) codebase 😄 👍 Thanks for hanging in there- you can try it yourself if you wanted and verify it's fixed (it's in an experimental stage at the moment)
https://github.com/brave/brave-browser/releases

**Comment by jsparknz** [comment]
@bsclifton Yip works and looks great on the new brave-core. Thanks for your help! Best wishes for the new release.
