### ISSUE TITLE
grant successful claim message doesn't always display 'Bravo!'

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15062]
### Description
Sometimes the successful claim message for a v2 UGP grant doesn't display 'Bravo!' on the first line. Noticed in a video recording by @srirambv 

### Steps to Reproduce

  1. Launch Brave with `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true`
  2. Claim a v2 UGP grant.
  3.

**Actual result:**
Bravo! is missing from the first line.
![screen shot 2018-08-20 at 2 08 18 pm](https://user-images.githubusercontent.com/28145373/44358971-7d528b00-a484-11e8-9915-8343fa09a746.png)

**Expected result:**
Same message when successfully claiming a v1 grant:
![screen shot 2018-08-20 at 2 07 37 pm](https://user-images.githubusercontent.com/28145373/44358993-922f1e80-a484-11e8-892c-fce05e2016f3.png)

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
0.23.102

**Reproducible on current live release:**
n/a

### Additional Information
cc @kjozwiak

**Comment by srirambv** [comment]
Seeing it happen only on update. I get the Bravo! message when grant is claimed in first attempt
![image](https://user-images.githubusercontent.com/17010094/44361961-8eec6080-a48d-11e8-8bf6-8b7a46574a0d.png)

**Comment by kjozwiak** [comment]
Context: These are STR re: the update case @srirambv mentioned:

* install/launch `0.23.79` using `EDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging BRAVE_ENABLE_PREVIEW_UPDATES=TRUE`
* enable payments and accept a grant (this will be a grant from v1 and NOT v2)
* once you've accepted the v1 grant, update the browser (should update as you're using `BRAVE_ENABLE_PREVIEW_UPDATES=TRUE`)
* after updating, ensure that you close brave and run it again using the above variables. When brave launches after an update, it stops using the environmental variables specified in the terminal
* after you've relaunched, you'll notice another `Claim` button that now belongs to the v2 promotion

Once you claim the v2 grant in this situation, the `Brava` text is missing.

@srirambv please correct me if the above isn't the case you ran.

**Comment by srirambv** [comment]
@kjozwiak yes the steps you mentioned is correct.

**Comment by kjozwiak** [comment]
Hmm not sure if this is a valid case as users on older versions of brave won't be getting promotions unless they update to a new version that has CAPCHA v2.

**Comment by srirambv** [comment]
Reproduced the issue when grant claimed on `0.23.79` (V1) and on `0.23.104` (v2)
![15062](https://user-images.githubusercontent.com/17010094/44546998-ade62f00-a6e7-11e8-8071-62bf8d13592d.gif)

**Comment by kjozwiak** [comment]
Moving this into the `backlog` but this might not be a valid use case for this release. @srirambv only ran into this when he accepted a grant on `0.23.79` that belonged to v1, updated to `0.23.104` and accepted a grant from v2. @evq and @davidtemkin mentioned that users on older version of Brave will not be seeing UGP promotional notifications.
