### ISSUE TITLE
block loading of chrome://brave URLs

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#15074]
talking to @bridiver and @darkdh it seems easiest to block chrome://brave loads in browser-laptop vs in muon. i believe navigation to chrome://brave is already blocked so we just need to block user-initiated loads.

this is a follow-up to https://github.com/brave/browser-laptop/issues/15045

**Comment by diracdeltas** [comment]
Will DM test plan to QA

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.104 b454a4a99934c4aa27fbe2effc5f72ce92e3266b
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
