### ISSUE TITLE
Installation Error on Windows 10

### ISSUE THREAD

**Issue by mcfaith9** [brave/browser-laptop#15079]
I download BraveSetup-x64.exe on the website and when I try to install it I got this error. 
[SquirrelSetup.log](https://github.com/brave/browser-laptop/files/2313056/SquirrelSetup.log)

**Comment by srirambv** [comment]
Delete the brave folders in `%appdata%/` and `%userprofile%/appdata/local/` and restart the machine and run the setup again. This should fix the issue. Let me know if this works.

**Comment by bsclifton** [comment]
Closing - let's re-open if issue persists after trying the suggestion by @srirambv 😄
