### ISSUE TITLE
View Page Source opens blank tab

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15075]
### Description
When selecting View Page Source from right-click menu, a blank tab is opened instead of a tab with the page source info. This does not happen in 0.23.79.

### Steps to Reproduce

  1. Navigate to a web page. (I was on https://smittenkitchen.com/2009/07/sour-cherry-slab-pie/ but any page will do)
  2. Right click somewhere on the background of the page.
  3. Select View Page Source.

**Actual result:**
Blank tab (about:blank) opens instead of a page showing the page source info.
![viewsource](https://user-images.githubusercontent.com/28145373/44426804-a561ed00-a55d-11e8-87dd-4d7b9b9fd106.gif)

**Expected result:**
New tab with page source info should be displayed as in 0.23.79.
![viewsource-02379](https://user-images.githubusercontent.com/28145373/44427116-8fa0f780-a55e-11e8-9de0-cf1b641181f3.gif)

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.23.103 
V8: 6.8.275.24 
rev: ae8e27774bb896ef4dd5cc928321d0eacb60ca59 
Muon: 8.0.8 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
no

### Additional Information
Possibly related to https://github.com/brave/browser-laptop/issues/15057 ,  https://github.com/brave/browser-laptop/issues/15045

**Comment by bsclifton** [comment]
caused by https://github.com/brave/browser-laptop/pull/15047

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.23.104 b454a4a99934c4aa27fbe2effc5f72ce92e3266b
* Muon 8.0.8
* libchromiumcontent 68.0.3440.84
