### ISSUE TITLE
unable to solve captcha

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15073]
### Description
Dropping the BAT logo onto the intended target isn't solving the captcha. Did some investigation with @evq and found that the y value is being thrown off by the BAT logo shadow.

### Steps to Reproduce

  1. Launch 0.23.102 with a clean profile and `EDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true`
  2. Enable Payments
  3. Click on Claim button
  4. Attempt to solve captcha

**Actual result:**
Unable to solve captcha unless I take the height of the logo + shadow into account:
![captcha2](https://user-images.githubusercontent.com/28145373/44420136-2663b900-a54b-11e8-991b-ff306ee935cf.gif)

**Expected result:**
BAT logo shadow should be irrelevant.

**Reproduces how often:**
easily for me on macOS, does not reproduce on macOS for @kjozwiak 

### Brave Version

**about:brave info:**
0.23.102

**Reproducible on current live release:**
n/a

**Comment by srirambv** [comment]
Happens on Windows too but after 6-7 attempts it claims the grant.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using 
* 0.23.104 b454a4a
* Muon  `8.0.8`
* libchromiumcontent `68.0.3440.84`
* Verified by dnd on wrong target 6-7 times and then on the actual target and was able to claim grant
