### ISSUE TITLE
multiple instances of pinned tab

### ISSUE THREAD

**Issue by planetcohen** [brave/browser-laptop#1508]
I have a single pinned tab. Sometimes I get multiple instances of that pinned tab. See attached screen shot.
![brave-multiple-pinned-tabs](https://cloud.githubusercontent.com/assets/265783/14921254/2277dfaa-0de6-11e6-98b0-8b7098003706.png)

**Comment by luixxiul** [comment]
Would you please provide steps to reproduce?
