### ISSUE TITLE
Youtube "dark theme" and "Theater mode" reseting to default randomly

### ISSUE THREAD

**Issue by TeoMorabito** [brave/browser-laptop#15081]
Hi,
Since using Brave on macOS, youtube.com doesn't always remember the option to keep "dark mode" as well and "Theater mode" on and reverts to default sometimes after a simple page refresh, or restart, and sometimes remembers the settings even after a restart. note the account stays logged in.
I have not been able to replicate the issue on Safari.
Any idea what could be causing this ?
duckduckgo remembers the dark mode setting (only disabled once over the past month) compared to approximately once a day with youtube.com

**Comment by thornjad** [comment]
Do you clear cookies when you exit, or do any other clearing of cookies?

**Comment by TeoMorabito** [comment]
No I do not clear the cookies, I can't pinpoint what is causing it

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
