### ISSUE TITLE
Browser allows to claim grant upon upgrade even when payment is pointing to different end point

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15088]
### Description
Browser allows to claim grant upon upgrade even when payment is pointing to different end point

### Steps to Reproduce
  1. Clean profile on 0.23.79
  2. Launch using `BRAVE_ENABLE_PREVIEW_UPDATES=true LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true` and enable payments 
  3. Click on check for updates, wait till it downloads the update
  4. Click on update button to restart the browser with the new version
  5. Shows Claim Token button on production since the browser wasn't launched using env variables
  6. Clicking Claim token button shows V2 grants to claim and dnd on correct target claims the grant when the browser is pointing to production endpoint 

**Actual result:**
https://drive.google.com/open?id=1C3hXWrVYPU7ZNeUOzkCoZglAg1jjj_JY

**Expected result:**
Should show Network error message on payments when browser restarts as its pointing to production endpoint but wallet is created on staging

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.104
-- | --
V8 | 6.8.275.24
rev | b454a4a
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Reproducible on current live release:**
No. Always shows network error message when staging wallet is launched without env variables and pointing to production

### Additional Information
@kjozwiak was also able to reproduce the issue with same steps on his Windows machine
cc: @evq

**Comment by bsclifton** [comment]
kicking out of the milestone - needs more investigation
