### ISSUE TITLE
binance.com not displaying properly due to cross-origin read blocking

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15089]
### Description
Reported via community: https://community.brave.com/t/binance-issues-w-shields/30391

Binance.com is not loading correctly. Default shields show nothing blocked (all 0's) but images and table are not displayed properly. Dev Tools show `Cross-Origin Read Blocking (CORB) blocked cross-origin response` messages. If you put shields down, this page loads correctly.

### Steps to Reproduce

  1. Open binance.com with default shields.
  2. Note table and images at top are not displayed correctly.
  3. Open shields, verify nothing is showing as blocked.

**Actual result:**
![screen shot 2018-08-24 at 5 38 03 pm](https://user-images.githubusercontent.com/28145373/44609613-67b3cd00-a7c6-11e8-892c-919a11423f22.png)

![screen shot 2018-08-24 at 5 44 26 pm](https://user-images.githubusercontent.com/28145373/44609616-6a162700-a7c6-11e8-9ca9-3e8e4928c800.png)

**Expected result:**
![screen shot 2018-08-24 at 5 53 39 pm](https://user-images.githubusercontent.com/28145373/44609672-a8134b00-a7c6-11e8-8293-d57b758ce621.png)

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.23.79

**Reproducible on current live release:**
Yes

### Additional Information
Does not reproduce in brave-core.
Maybe related to https://github.com/brave/browser-laptop/issues/14841#issuecomment-407916741 ?

**Comment by bsclifton** [comment]
Related to https://github.com/brave/browser-laptop/issues/13808 ?
