### ISSUE TITLE
high DPI issue with captcha

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15085]
### Description
Found by @jonathansampson when testing captcha changes - Seems as though he was unable to drop the logo directly onto the target, he had to drop it a little to the right in order to successfully claim.

### Steps to Reproduce

  1. Launch 0.23.104 with clean profile and `LEDGER_ENVIRONMENT=staging LEDGER_VERBOSE=true` when using a high DPI monitor (unsure of exact specs)
  2. Navigate to Payments and enable
  3. Click on button to claim tokens
  4. Attempt to claim by dropping logo directly onto target

**Actual result:**
Unable to claim by dropping logo directly onto target, had to drop a little to the right. Video by @jonathansampson is linked below.

https://drive.google.com/file/d/1Ik_o-tKRDdgRQ8Zd3bT9VraQPuebSST5/view?usp=sharing

**Expected result:**
Dropping logo directly onto target should result in successful claim.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
0.23.104

**Reproducible on current live release:**
n/a

### Additional Information
cc @kjozwiak

**Comment by kjozwiak** [comment]
Moving this into https://github.com/brave/browser-laptop/milestone/108 as https://github.com/brave/browser-laptop/issues/14391 is in the same milestone. As discussed during our triage meeting, we'll be release `0.23.x Release 5` without this issue. If a user with a high DPI monitors runs into this problem, they can always reduce the scaling, accept the grant and then go back to their preferred preferences.
