### ISSUE TITLE
charts not displaying on nasdaq

### ISSUE THREAD

**Issue by aaronovz1** [brave/browser-laptop#15090]
### Description
Charts don't display on the nasdaq website when Block Thirdparty Cookies is enabled

https://www.nasdaq.com/symbol/aapl

### Steps to Reproduce
  1. Visit https://www.nasdaq.com/symbol/aapl
  2. Intra day etc chart is not seen
  3. Open brave shield and enable cookies
  4. Charts now display

**Actual result:**
No charts

**Expected result:**
Charts display

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.23.79 
V8: 6.8.275.24 
rev: 51b49051a779f0db94fbcfd0df5faca781299ea0 
Muon: 8.0.7 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Comment by rebron** [comment]
Closing, marking wontfix here but this is fixed in brave-core https://brave.com/download-dev
