### ISSUE TITLE
Save password notification not shown for default password manager

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15106]
### Description
Save password notification not shown for default password manager

### Steps to Reproduce

  1. Clean profile on 0.23.201
  2. Login to a site
  3. No prompt shown to save password

**Actual result:**
Save password notification not shown for default password manager

**Expected result:**
Should prompt to save password for default password manager

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.201
-- | --
V8 | 6.9.427.17
rev | 17d2d17
Muon | 8.1.0
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.57

**Reproducible on current live release:**
No

### Additional Information
cc: @brave/legacy_qa

**Comment by LaurenWags** [comment]
Reproduces on macOS using 0.23.201

**Comment by btlechowski** [comment]
Reproduces on Ubuntu 17.10 using 0.23.201

**Comment by darkdh** [comment]
fixed in https://github.com/brave/muon/pull/642/commits/f4c5df1bdea10b18239c3de7d18c47ee827c58d2
muon 8.1.1

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.203 16c2c198f897b4ffbfdbd3e8f725af7d20f85e75
•	Muon 8.1.2
•	libchromiumcontent 69.0.3497.72
