### ISSUE TITLE
Look up from context menu does not work

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15108]
### Description
On macOS when you highlight and right click on text, there is an option on the right-click menu for 'Look up' which will look up your selected text. In cr69 this is not working.

### Steps to Reproduce

  1. Open a webpage
  2. Highlight some text
  3. Right click on the text and select the ‘Look up’ option from context menu

**Actual result:**
Context menu goes away, but popup displaying information about selected text does not display. No errors in terminal either.
![lookup-023201](https://user-images.githubusercontent.com/28145373/44750528-a35ed780-aae3-11e8-9af1-a4e0abb74b5c.gif)

**Expected result:**
A popup should display, which shows information about your selected text:
![lookup](https://user-images.githubusercontent.com/28145373/44750439-5ed33c00-aae3-11e8-8de5-7dc8c597501d.png)

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.23.201 
V8: 6.9.427.17 
rev: 17d2d17a64b6ea5e85ff8fbe324798447887e81b 
Muon: 8.1.0 
OS Release: 16.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.57

**Reproducible on current live release:**
no

### Additional Information
Occurred previously with cr67 which was logged as https://github.com/brave/browser-laptop/issues/14247
cc @kjozwiak

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.13.6` following the STR. Unfortunately, I didn't see any errors in the terminal/browser console.

**Comment by darkdh** [comment]
fixed in muon 8.1.1
https://github.com/brave/muon/pull/642/commits/18115e77b3a09b4800e18c7f5fe4adda44e920c4

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.203 16c2c19
* Muon 8.1.2
* libchromiumcontent 69.0.3497.72
