### ISSUE TITLE
Unable to print 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15103]
### Description
Unable to print with `0.23.201` cr69 build. Terminal displays:
`[40783:12803:0828/154053.334723:ERROR:service_manager_connection_impl.cc(317)] Can't create service pdf_compositor. No handler found.`

### Steps to Reproduce

  1. Launch 0.23.201 from terminal
  2. Navigate to a web page or PDF
  3. Attempt to print (File > Print).
  4. Print dialog is shown. Select Print button.
  5. File does not print. 

**Actual result:**
File does not print. Terminal displays `[40783:12803:0828/154053.334723:ERROR:service_manager_connection_impl.cc(317)] Can't create service pdf_compositor. No handler found.`

**Expected result:**
File should print

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave: 0.23.201 
V8: 6.9.427.17 
rev: 17d2d17a64b6ea5e85ff8fbe324798447887e81b 
Muon: 8.1.0 
OS Release: 16.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.57

**Reproducible on current live release:**
no, does not reproduce in 0.23.104

### Additional Information
Reproduced by @srirambv on Windows

Attempt to print other ways with the same result:
     - Right click on page background, select Print from context menu. Repeat steps 4-5 from STR
     - Right click on page background, select Print, Select PDF droplist and then 'Save as PDF'. Enter PDF name and then Save. When you go to view the PDF it is blank and terminal displays the same message as above.

**Comment by btlechowski** [comment]
Reproduces on Ubuntu 17.10 using 0.23.201

**Comment by darkdh** [comment]
fixed in muon 8.1.1
https://github.com/brave/muon/pull/642/commits/d926befa7391a1d622086793aa6cf3b52ad113fb

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.203 16c2c198f897b4ffbfdbd3e8f725af7d20f85e75
•	Muon 8.1.2
•	libchromiumcontent 69.0.3497.72
