### ISSUE TITLE
cr69 crashes

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15104]
### Description
I've crashed twice on 0.23.201 but haven't gotten solid steps to reproduce yet. Here are the crash report IDs in case they are helpful:
Uploaded Crash Report ID 16943061bb38059c
Uploaded Crash Report ID c72092a92665e07

### Steps to Reproduce

TBD - I was testing context menus and had encountered https://github.com/brave/browser-laptop/issues/15103 so unsure if they are related.

**Actual result:**
Brave Crashes

**Expected result:**
Brave should not crash

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**
 
Brave: 0.23.201 
V8: 6.9.427.17 
rev: 17d2d17a64b6ea5e85ff8fbe324798447887e81b 
Muon: 8.1.0 
OS Release: 16.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.57

**Reproducible on current live release:**
unknown

**Comment by darkdh** [comment]
fixed in muon 8.1.1

**Comment by GeetaSarvadnya** [comment]
No crashes on windows while verifying #15103

**Comment by LaurenWags** [comment]
@darkdh since I wasn't able to get solid STR for these crashes, do you know of any steps QA could use to test this?
