### ISSUE TITLE
Last update broke lastpass

### ISSUE THREAD

**Issue by sirjorj** [brave/browser-laptop#15109]
Just updated to this:

Name | Version
-- | --
Brave | 0.23.104
V8 | 6.8.275.24
rev | b454a4a
Muon | 8.0.8
OS Release | 4.15.0-33-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

I fired it up to see if the 'always launches on monitor 3 instead of whatever monitor it was last closed on' bug was fixed (https://github.com/brave/browser-laptop/issues/14901).  It wasnt.  Then I discovered that lastpass needed me to authenticate (i use 2 factor with a yubikey).  When i tried it wouldnt connect.  Lastpass gives this message:

An error occurred while attempting to contact the server. Please check your Internet connection.

This happens WHILE im streaming a video from the Internet, so I'm pretty sure the connection is okay.

While typing this i just noticed that the lastpass icon was red.  Okay... does it work now?  If I click on the icon, the menu pops up and the icon turns yellow.  If I click on the yellow icon, I get the above error message and then it turns red again.  I go to a page that requires me to login to test lastpass and I see that it does fill in the password.  So it kind of works, but is very quirky.

**Comment by stephenkru** [comment]
+1 Yeah I noticed this with bitwarden too. Bitwarden extension cant sync with the server, keeps failing.
 
I tried to check lastpass and after the extension downloaded I click the icon and the drop down said it failed to connect to the server.

**Comment by warwickmm** [comment]
Same issue with LastPass here:

```
An error occurred while attempting to contact the server. Please check your Internet connection.
```

| Brave | 0.23.104 |
-----------| ----------
|V8| 6.8.275.24 |
|rev| b454a4a99934c4aa27fbe2effc5f72ce92e3266b |
|Muon| 8.0.8 |
|OS Release| 4.18.3-arch1-1-ARCH |
|Update Channel| Release |
|OS Architecture| x64 |
|OS Platform| Linux |
|Node.js| 7.9.0 |
|Brave Sync| v1.4.2 |
|libchromiumcontent| 68.0.3440.84|

**Comment by kjozwiak** [comment]
Closing this in favour of https://github.com/brave/browser-laptop/issues/14841 which is addressing the issue. We'll try getting a fix out ASAP. Again, apologies for all of you guys who are affected by this!
