### ISSUE TITLE
After successful payment contribution, click on Brave_Payments history file is causing browser crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#15112]
### Description
After successful contribution, when user click on Payment History -> Brave_Payments_2018-08-29.pdf file, the browser is getting crashed.

### Description
After successful payment contribution, click on Brave_Payments history file is causing browser crash
### Steps to Reproduce

1. Launch Brave with clean profile from CLI with staging flag
2. Enable payments
3. Claim the UGP grant
4. Add few sites to ledger
5. Complete the contribution 

**Actual result:**
Crash Report ID 53d7a37631cd5ea6
After successful payment contribution, click on Brave_Payments history file is causing browser crash
![bravebeta_browsercrash](https://user-images.githubusercontent.com/38657976/44772661-12900680-ab8c-11e8-88ca-528ce181f55b.gif)

**Expected result:**
Should not be any crash

**Reproduces how often:**
Always

### Brave Version
0.23.201
**about:brave info:**
 
Brave: 0.23.201 
V8: 6.9.427.17 
rev: 17d2d17a64b6ea5e85ff8fbe324798447887e81b 
Muon: 8.1.0 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.57

**Reproducible on current live release:**
No

### Additional Information
cc: @kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by LaurenWags** [comment]
Reproduces on macOS using 0.23.201. 
Crash Report IDs:
Uploaded Crash Report ID efc275abf033cdb7
Uploaded Crash Report ID 3a4d86348af6b26b
Not sure that it's helpful, but when Brave crashed it showed `Segmentation fault: 11` in the terminal

**Comment by darkdh** [comment]
fixed in https://github.com/brave/muon/pull/642/commits/d926befa7391a1d622086793aa6cf3b52ad113fb

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.203 16c2c198f897b4ffbfdbd3e8f725af7d20f85e75
•	Muon 8.1.2
•	libchromiumcontent 69.0.3497.72
