### ISSUE TITLE
Bitwarden can't sync

### ISSUE THREAD

**Issue by stephenkru** [brave/browser-laptop#15110]
### Description
Bitwarden extension is not able to sync with the server.

### Steps to Reproduce
  1. From clean brave install enable bitwarden.
  2. Login to the extension. Click the icon.
  3. The bitwarden menu opens to the "Tab" menu, but "working" icon is endlessly going in a circle.
  4. Click the vault tab and it says there is nothing there.
  5. Click  "Settings>Sync>Sync Vault now" and get a syncing failed error message.

**Actual result:**
syncing failed error message

**Expected result:**
Vault tab populated with my logins.

**Reproduces how often:**
Always

### Brave Version

Brave | 0.23.104
-- | --
V8 | 6.8.275.24
rev | b454a4a
Muon | 8.0.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Comment by kjozwiak** [comment]
Thanks for the report @stephenkru, most likely due to https://github.com/brave/browser-laptop/issues/14841.

**Comment by stephenkru** [comment]
Yeah it was working a few days ago for me.

**Comment by darkdh** [comment]
fixed in muon 8.0.9

**Comment by LaurenWags** [comment]
Passed on macOS 10.12.6 using
* 0.23.105 9a46f8f
* Muon 8.0.9
* libchromiumcontent 68.0.3440.84
