### ISSUE TITLE
Roboform Support......

### ISSUE THREAD

**Issue by Banditz71** [brave/browser-laptop#1511]
Will Roboform support be added in the near future?  Want to use Brave fulltime, but makes it a little tough without my saved passwords......Thanks!

**Comment by wes-baker** [comment]
I second the request. I wrote earlier about getting RoboForm for Brave, but was told nothing would be done while it was in development--even though it was in release then.  I want to switch to Brave, as well, but the fact RoboForm doesn't work with it yet is holding me back.

**Comment by Banditz71** [comment]
PLEASE get Roboform added.......Thanks!!

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5827

**Comment by wes-baker** [comment]
I couldn't get into the zendesk posting.  It requires a password and when I entered my email address to request one it gave me a message that my password couldn't be reset.  Can you give us an idea what is in that support message?

**Comment by alexwykoff** [comment]
Basically they were echoing the desire for roboform support. 

We use the '+1 from support' comment as a way of marking community desire to have particular issues fixed.

**Comment by srirambv** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6527

**Comment by srirambv** [comment]
+1 from support: https://linkbubble.zendesk.com/agent/tickets/7196

**Comment by Lepraz** [comment]
+1 Add roboform support to Brave

**Comment by bsclifton** [comment]
+1 from @dochws via https://github.com/brave/browser-laptop/issues/14598

**Comment by bsclifton** [comment]
Unfortunately, we won't be able to address this in the current version of our product

However, Roboform will be available for install (just like other extensions) after we shift from Muon to [brave-core](https://github.com/brave/brave-browser) 😄
