### ISSUE TITLE
After latest release, LastPass extension can't connect to service - MacOS

### ISSUE THREAD

**Issue by Ruskicowboy** [brave/browser-laptop#15115]
### Description
After the latest release, LastPass extension can no longer reach its service, so cannot login nor fill forms.

### Steps to Reproduce

  1. Open Brave, and last pass is not logged in
  2. Click on LastPass icon
  3. Login modal appears.  Fill it in and click Login
  4. LastPass Icon turns yellow
  5. Click on LastPass Icon and you'll see the error message

**Actual result:**
![screen shot 2018-08-29 at 9 14 48 am](https://user-images.githubusercontent.com/3975970/44790116-70145b00-ab6c-11e8-8a9e-3f69f6ddbeb6.png)
![screen shot 2018-08-29 at 9 14 23 am](https://user-images.githubusercontent.com/3975970/44790121-760a3c00-ab6c-11e8-9e11-45c94f95ee18.png)
![screen shot 2018-08-29 at 9 13 41 am](https://user-images.githubusercontent.com/3975970/44790134-7c98b380-ab6c-11e8-8362-b4ca8387e055.png)
![screen shot 2018-08-29 at 9 13 53 am](https://user-images.githubusercontent.com/3975970/44790142-80c4d100-ab6c-11e8-944a-f46ff4f35d7d.png)

**Expected result:**
LastPass should be able to reach its service

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave: 0.23.104 
V8: 6.8.275.24 
rev: b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
Muon: 8.0.8 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
Yes

### Additional Information
MacOS High Sierra Version 10.13.4

**Comment by hardyjohnson** [comment]
FWIW, also seeing this in High Sierra 10.13.6

Brave: 0.23.104 
V8: 6.8.275.24 
rev: b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
Muon: 8.0.8 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Comment by MrHellsing** [comment]
Also affects Windows
<details><summary>Info</summary>

Brave: 0.23.104 
V8: 6.8.275.24 
rev: b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
Muon: 8.0.8 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

</details>

**Comment by wspurgin** [comment]
Is there a version (or a index of versions) we can downgrade to in the meantime? @Ruskicowboy did you have v0.23.79 prior to this latest version?

**Comment by Ruskicowboy** [comment]
I don't think I do.  Brave just automatically updates and then lets me know. :-)

**Comment by wspurgin** [comment]
Fun :^) This is happening to me on a clean install. Hopefully we'll hear from someone on the Brave team soon.

**Comment by flatiron32** [comment]
I am also having trouble logging into LastPass website. I think the site interacts with the extension if available.

**Comment by bsclifton** [comment]
Hi folks - thanks for the reports and apologies for the outage here

This is a known issue (tracked with https://github.com/brave/browser-laptop/issues/14841) and our QA is qualifying a hotfix right now that we hope to release today. Stay tuned

I'll close this issue as the progress is being tracked with https://github.com/brave/browser-laptop/issues/14841
