### ISSUE TITLE
Save password notification always shown for default password manager

### ISSUE THREAD

**Issue by siwan05** [brave/browser-laptop#15111]
### Description
Save password notification is always shown for the default password manager

### Steps to Reproduce
  1. Login to a site
  2. Select any option (Allow, Deny, Never For This Site)
  3. Log out of site
  4. Log into same site

**Actual result:**
Prompt appears again

**Expected result:**
Brave should respect the selected option

**Reproduces how often:**
100%

### Brave Version
Brave: 0.23.104 
V8: 6.8.275.24 
rev: b454a4a99934c4aa27fbe2effc5f72ce92e3266b 
Muon: 8.0.8 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
Yes

**Comment by rebron** [comment]
Closing. This is fixed in brave-core.
