### ISSUE TITLE
Installation for 0.9.2 fails on x64

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1512]
Hello Dev team,

i found issue on youtube while browsing and saw that brave was not blocking a huge ad in the home page so i decided to update brave and the installation for the 0.9.2 is failing as below:

![bravefailed](https://cloud.githubusercontent.com/assets/17910355/14935818/05cefa70-0ee8-11e6-8020-25cbb66c09ea.PNG)

OS : windows 7 x64 service pack 1

setup log attached

[SquirrelSetup.txt](https://github.com/brave/browser-laptop/files/243588/SquirrelSetup.txt)

**Comment by luixxiul** [comment]
@Haze-Aulaian does this still continue?

**Comment by Haze-Aulaian** [comment]
@luixxiul yes , i noticed that the reason for this is that Brave.exe remains in the background after closing it , if i terminate the process it installs fine.

**Comment by luixxiul** [comment]
If so, this issue seems to have been fixed in #1540.

**Comment by Haze-Aulaian** [comment]
@luixxiul thanks for the heads up

**Comment by luixxiul** [comment]
Please let me know if the issue persists. Thanks.
