### ISSUE TITLE
Camera/Microphone access request notification not shown on CR69

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15121]
### Description
Camera/Microphone access request notification not shown on CR69

### Steps to Reproduce

  1. Visit https://browserleaks.com/webrtc and set FP to block 3rd party
  2. Click on `Audio-Capture permission` or `Video-capture permission` button
  3. No notification bar shown requesting access

**Actual result:**
Camera/Microphone access request notification not shown on CR69

**Expected result:**
Should prompt for access to devices enumeration

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.201
-- | --
V8 | 6.9.427.17
rev | 17d2d17
Muon | 8.1.0
OS Release | 10.0.17134
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.57

**Reproducible on current live release:**
No

**Comment by darkdh** [comment]
fixed in muon 8.1.1
https://github.com/brave/muon/pull/642/commits/901e3cfdc15a9b1ddd2fc0ee46016af76435fb32

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64
•	0.23.203 16c2c198f897b4ffbfdbd3e8f725af7d20f85e75
•	Muon 8.1.2
•	libchromiumcontent 69.0.3497.72
