### ISSUE TITLE
keyboard shortcut for previous tab ctrl+shift+tab not working on cr69

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15122]
### Description
When I use the `ctrl+shift+tab` shortcut to go to the previous tab, it doesn't always work. Sometimes it goes back a tab or two, and then starts going forward. Sometimes it just goes forward. Sometimes it goes forward for several tabs and then alternates between two tabs (goes back and forth on two tabs). 
Another shortcut to navigate to previous tab `cmd+opt+<- arrow` works as expected to go to the previous tab.

### Steps to Reproduce

  1. Launch 0.23.201 with a clean profile.
  2. Open a bunch of sites in tabs.
  3. Make a tab somewhere in the middle the active tab.
  4. Use ctrl+shift+tab several times to navigate tabs --> you might go back a tab or two but eventually you start going forward or you go to the next tab (on the right) instead of the previous tab (on the left)

**Actual result:**
In the below gif I'm using `ctrl+shift+tab` to navigate between tabs at all times. Using this goes forward in the tabs for a bit and then it gets stuck and alternates between two:
![ctrl-shift-tab-023201](https://user-images.githubusercontent.com/28145373/44800943-b75b1580-ab85-11e8-931c-8e11a635623a.gif)

In the below gif I'm using `ctrl+shift+tab` to navigate between tabs at all times. Using this goes back a tab but then goes forward a tab and gets stuck alternating between the two:
![ctrl-shift-tab-023201-again2](https://user-images.githubusercontent.com/28145373/44801011-e4a7c380-ab85-11e8-8cc8-bdaff379fa43.gif)

**Expected result:**
`ctrl+shift+tab` should go to previous tab (on the left) as `cmd+opt+<- arrow` does.

**Reproduces how often:**
easily

### Brave Version
 
Brave: 0.23.201 
V8: 6.9.427.17 
rev: 17d2d17a64b6ea5e85ff8fbe324798447887e81b 
Muon: 8.1.0 
OS Release: 16.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.57

**Reproducible on current live release:**
no

### Additional Information
@srirambv and @btlechowski could not reproduce on Win/Linux, could be macOS only.
cc @kjozwiak

**Comment by darkdh** [comment]
fixed in muon 8.1.2
https://github.com/brave/muon/pull/642/commits/3f4bb593e3aef22c4197de33a81f8a6b21d08fc0
