### ISSUE TITLE
Opening local files in brave opens `about:blank`

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#15134]
From: https://www.reddit.com/r/brave_browser/comments/9bz11l/issue_opening_html_files/

### Description
Double-click on html files opens `about:blank` instead of html files in brave.

### Steps to Reproduce

  1. Double click on an html file

**Actual result:**
Opens `about:blank`

**Expected result:**
Should render the html file

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
 
```
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
```

**Reproducible on current live release:**
Yes

### Additional Information
None

**Comment by sjimw** [comment]
FYI, I use a local page as my home page and now when I start Brave it displays "about:blank". However, when I click on the "Open Homepage" button it does display my local page correctly. This problem began only after updating to Brave version 0.23.105.

**Comment by TimSoethout** [comment]
Also on 0.23.105 on OSX.
It's not perfect but my workaround is to copy/paste the file path in the address bar until it is solved.

**Comment by theunbound** [comment]
Also on Windows.

###about:brave info:
` 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 10.0.17751 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84`

**Comment by diracdeltas** [comment]
probably caused by this security fix: https://github.com/brave/browser-laptop/pull/14973

i considered the case where someone opens HTML files by clicking 'open file' in brave but not the case where they click on HTML files and have Brave set as the file type handler

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.207 281de88
* Muon 8.1.6
* libchromiumcontent 69.0.3497.100
