### ISSUE TITLE
Ads escaping the blocking option

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1513]
Hello Dev team,

as you can see below on youtube ads are escaping the block option:

![bravead](https://cloud.githubusercontent.com/assets/17910355/14935945/a77f5820-0eec-11e6-83ab-f68640325269.PNG)

![bravead](https://cloud.githubusercontent.com/assets/17910355/14935951/f9a5a686-0eec-11e6-86c2-0434d2035b9d.PNG)

![ads](https://cloud.githubusercontent.com/assets/17910355/14936414/ac0a3baa-0ef4-11e6-8946-0724d1d54863.PNG)

Is that expected ?

**Comment by diracdeltas** [comment]
Those ads should not be appearing. Which release is this?

**Comment by Haze-Aulaian** [comment]
![ads](https://cloud.githubusercontent.com/assets/17910355/15007019/f45cd5d4-11dd-11e6-9040-6b1a31fe535a.PNG)

**Comment by diracdeltas** [comment]
Thanks. Is it still happening after the 0.9.3 release today?

**Comment by Haze-Aulaian** [comment]
@diracdeltas is 0.9.3 on the official site if not where can i download it so i can test it ?

**Comment by diracdeltas** [comment]
open File > Check for updates, or download from https://github.com/brave/browser-laptop/releases

**Comment by Haze-Aulaian** [comment]
sure

**Comment by Haze-Aulaian** [comment]
@diracdeltas ads still escaping : 

![adsstill](https://cloud.githubusercontent.com/assets/17910355/15037121/a7276a36-12a0-11e6-91e5-b33fb0538702.PNG)

**Comment by bridiver** [comment]
maybe coming from a source that isn't on easylist?

**Comment by diracdeltas** [comment]
@Haze-Aulaian can you send a URL of a youtube page where you see ads?

**Comment by luixxiul** [comment]
How about using Fanboy lists too if possible? #1636 will be fixed by adding https://www.fanboy.co.nz/fanboy-japanese.txt

**Comment by Haze-Aulaian** [comment]
@diracdeltas , any youtube video will show you the problem. also its on the home page it self a big banner will appear.

**Comment by Haze-Aulaian** [comment]
@diracdeltas i have updated brave to 0.9.5 and the issue is fixed , however im wondering if we can get rid of the whole frame in future release as its leaving a huge space behind as below:

![adsgone1](https://cloud.githubusercontent.com/assets/17910355/15260342/fa4a8210-195e-11e6-9a13-ba8f8be12288.PNG)


while the ads gone perfectly on the right side while playing a video and no white frame:

![adsgone](https://cloud.githubusercontent.com/assets/17910355/15260346/ff77b9d8-195e-11e6-94a2-4ba54d0f0d0c.PNG)

**Comment by bridiver** [comment]
we are still discussing options for collapsing vs not collapsing. Sometimes collapsing causes layout issues and sometimes it doesn't. Right now we don't make any effort to do one or the other. If the ad slot is defined in the page layout as this one appears to be then the space will not collapse. If the layout is defined by the actual ad then it will collapse because the ad is never loaded

**Comment by bridiver** [comment]
afaik no existing ad blocker detects ads based on position or size. There are several lists of known ad domains and those requests are not loaded. We are looking at going beyond that to find ads based on other characteristics and probably also allowing users to manually block and report ads that make it through the filter

**Comment by bridiver** [comment]
this is always going to be an open issue as publishers try to find new ways to avoid the filters. Unless you have any objections I'm going to close this issue and we can open new ones for general purpose blocking methods rather than site specific issues. @bbondy we should probably have a single tracker for ads that are making it through our filters if we don't already.

**Comment by Haze-Aulaian** [comment]
@bridiver sure feel free to close , thanks :)

**Comment by Haze-Aulaian** [comment]
@bridiver mate , im sorry but the issue is still appearing with 0.9.6 64bit (win7 64bit sp1) brave as below:

![bugad](https://cloud.githubusercontent.com/assets/17910355/15268553/34fd7bc8-19ec-11e6-98c9-7d3bcd5e589a.png)
