### ISSUE TITLE
"support your favorite sites" banner is hard to understand

### ISSUE THREAD

**Issue by timur-friedman** [brave/browser-laptop#15146]
### Description
A banner appears at the top of window, saying: "Hello! Ready to support your favorite sites? Brave will fill your wallet with tokens to get you started!", and there are three buttons: "No Thanks", "Maybe Later", and "I'm Ready". It seems like the user is being sold something, but without a sufficient explanation of what it is. My questions were: "What's my wallet?", "What is a token?", "How does this support sites that I might visit?" Without obvious answers, my choice is necessarily "No Thanks". Oughtn't there be some obvious way the user can inform themself?

### Steps to Reproduce
  1. Start Brave 0.23.105
  2. I think I might have conducted a search from the navigation bar before the banner appeared.

**Actual result:**
Banner as described

**Expected result:**
Banner with a link to learn more or perhaps a "Learn More" button, at the risk of adding a fourth button.

**Reproduces how often:**
I haven't tried to reproduce it with a fresh install, but I imagine every user who installs Brave and starts it sees this.

### Brave Version

**about:brave info:**
 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**
Yes

### Additional Information
None

**Comment by bsclifton** [comment]
Closing as `wontfix` for this repo. We'll want to address this with Brave Rewards in [brave-core](https://github.com/brave/brave-browser)

cc: @NejcZdovc
