### ISSUE TITLE
Unable to Open the payment history pdf file from About:downloads

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#15145]
### Description
Unable to Open the payment history pdf file from About:downloads

### Steps to Reproduce

  1. Launch brave with clean profile
  2. Enable payments and add websites to ledger
  3. Complete the contribution
  4. Download the contribution statement from Payment History
  5. Go to About:Downloads and try to open the pdf file

**Note**: Please note that this issue is arising only for the payment history pdf file. I have downloaded other pdf files and tried opening them from About:Downloads and i was able to open them successfully.

**Actual result:**
Unable to Open the payment history pdf file from About:downloads
![pdf file issue](https://user-images.githubusercontent.com/38657976/44983243-2d9cb500-af96-11e8-9612-850277a47c35.gif)

**Expected result:**
User should be able to open the pdf file

**Reproduces how often:**
Always

### Brave Version
0.23.203
**about:brave info:**
 
Brave: 0.23.203 
V8: 6.9.427.18 
rev: 16c2c198f897b4ffbfdbd3e8f725af7d20f85e75 
Muon: 8.1.2 
OS Release: 10.0.17134 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.72

**Reproducible on current live release:**
No

### Additional Information
cc: @kjozwiak @LaurenWags @srirambv @btlechowski

**Comment by bsclifton** [comment]
@GeetaSarvadnya does this happen for any PDF that is downloaded?

**Comment by bsclifton** [comment]
Moving to our next milestone
