### ISSUE TITLE
Error getting a diff from latest state. param str (undefined) is not a string (AppStore.emitChanges)

### ISSUE THREAD

**Issue by Zarnaik** [brave/browser-laptop#15141]
### Description

I manually built and ran brave. Everything fine. After adding some extensions, I noticed brave was continually using 100% of a cpu-core.

### Steps to Reproduce

  1. Manually build browser-laptop following [this walkthrough](https://brave.com/loading-chrome-extensions-in-brave/).
  2. Install extensions: pccckmaobkjjboncdfnnofkonhgpceea, clngdbkpkpeebahjckkjfobafhncgmne, hdokiejnpimakedhajhdlcegeplioahd, lkcdgdbfbbnpnljlalmcjnepgjnmgigh, occjjkgifpmdgodlplnacmkejpdionan, nffaoalbilbmmfgbnbgppjihopabppdk, cjpalhdlnbpafiamejdnhcphjbkeiagm
  3. Launch brave

**Actual result:**

Heavy CPU usage causing the browser to run slowly. 

This error occurs many times:

> Crash dump id: a519729423d23567
> Error getting a diff from latest state.
> An uncaught exception occurred in the main process Uncaught Exception:
> Error: param str (undefined) is not a string
>     at AppStore.emitChanges (/home/user/TEMP/0Progams/brave-browser-laptop/js/stores/appStore.js:104:15)
>     at ontimeout (timers.js:386:14)
>     at tryOnTimeout (timers.js:250:5)
>     at Timer.listOnTimeout (timers.js:214:5)

**Expected result:**
No errors, lighter CPU use.

**Reproduces how often:**

Every time I launch the browser.

### Brave Version

**about:brave info:**

about:brave doesn't show the version. I cloned the repository today (2018-09-02)
![2018-09-02-21 59 18_427x152_selection](https://user-images.githubusercontent.com/8351931/44960266-7869ee80-aefc-11e8-99d6-b9b33a3bc976.jpg)

**Reproducible on current live release:**

No idea, I don't know how to add extensions in the main release (installed via repository).

### Additional Information

I tried disabling individual extensions in the settings to figure out if a specific one was causing the problem. Upon doing so, all custom extensions disabled/enabled, making it impossible to figure out. Errors continue after (seemingly) disabling the custom extensions.

**Comment by bsclifton** [comment]
Thanks for the report @Zarnaik 😄 That type of installation for extensions isn't really supported. Would you be able to download / install our new Developer channel release?
https://brave.com/download-dev

This should let you use any extension you want from the Chrome Web Store 😄 If you run into any issues, you can report them in the new repository:
https://github.com/brave/browser-laptop/issues

**Comment by Zarnaik** [comment]
Thanks for the info. Guess I'll be staying on the default version browser then, as my use case involves tor tabs.
