### ISSUE TITLE
Setting percentages in Payments is too buggy

### ISSUE THREAD

**Issue by NumDeP** [brave/browser-laptop#15140]
Have you searched for similar issues? 
Yes.

### Description
I've literally spent over 20 minutes trying to set percentages in Payments for eleven Sites and it's not the first time. The figures just don't stick.

### Steps to Reproduce

1. Got to Payments
2. Pin around eleven Sites
3. sort-by percentage descending 
4. Begin trying to set percentage from top to bottom

**Actual result:**
I can't be the only one facing this issue as it's pretty obvious what the problem is. Following step 4. begin changing from the top you'll notice, it'll change another you didn't want to change and changing that one changes the one you previously changed and then it scrambles to the point you can't set the correct amount you wish to set.

**Expected result:**
Setting a figure/% should make that stick instead of randomly changing the figures of other Sites (I give a good at least a temporary solution for this below)

**Reproduces how often:**
90%

**about:brave info:**
~~~
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 4.12.14-lp150.12.16-default 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Tor: 0.3.3.8 (git-99f9816efa08ab83) 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
~~~

### Additional Information
I don't mean speculate but I think most users that contribute more often than none will opt to select the 'sort-by percentage descending' in between 'Time Spent' and 'Actions' to appropriately distribute contributions, which is exactly the way I do it. I select the '%' icon and it usually sticks that way and I begin setting the highest percentage to the Site I would like to contribute the most. 

I wish you'd consider the following as a temporary fix and include it in one of the next releases. On every Site a user sets a particular percentage to, to make that stick, the ledger should display the box surrounding the percentages of the rest of the percentages that are pinned in amber, indicating they may need changing depending on if a user increased or decreased the amount of the previous Site.

E.g: I only want to change the percentage of two sites, 1. & 3.
~~~
Site ...    %
1.   ... [ 50 ] Changing this to 60 [ 60 ] but stipulates there is a 10% stretch
2.   ... [ 30 ] makes this go amber [ 30 ] 
3.   ... [ 20 ] makes this go amber [ 10 ] changing this to 10 retains 2. doesn't alter 1.
~~~
Each amber should turn off only once the figure in it has changed, the last amber should turn off shortly after the penultimate one unless the user wishes to increase the contribution, which would turn the rest amber again because of the stretch. Never does it manually automate the figures.

**Comment by bsclifton** [comment]
Thanks for the feedback, @NumDeP 😄 

I'm going to close this issue as we're in the middle of reworking the entire payments experience (which will be called Brave Rewards)

cc: @NejcZdovc
