### ISSUE TITLE
CapitalOne.com doesn't load with shields up. 

### ISSUE THREAD

**Issue by bstin** [brave/browser-laptop#15148]
### Steps to Reproduce

  1. With shields enabled, visit https://www.capitalone.com
  2. Notice totally blank screen
  3. Disabled shield, and refresh and site loads normally

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1180
