### ISSUE TITLE
swipe cannot be cancelled in a page that has horizontal scrollable content

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15150]
### Description
Per discussion with @darkdh logging an issue for swipe cannot be cancelled in a page that has horizontal scrollable content when it reaches the swipe threshold

### Steps to Reproduce

1. Got to https://github.com/brave/browser-laptop/projects/16
2. Two finger swipe right and make "<" indicator became biggest
3. Don't lift your and swipe left and notice the won't become smaller until reach the right edge 
![untitled](https://user-images.githubusercontent.com/11330831/45049233-ddbffb80-b032-11e8-841b-9dcf61c8aee2.gif)

**Actual result:**
Swipe cannot be cancelled in a page that has horizontal scrollable content.

**Expected result:**
Swipe should be able to be cancelled.
![untitled](https://user-images.githubusercontent.com/11330831/45049565-dc430300-b033-11e8-809e-1cc94dab4498.gif)

**Reproduces how often:**
unknown

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bridiver** [comment]
@LaurenWags can you add a description of the STR? It's really hard to tell what's happening in that video

**Comment by LaurenWags** [comment]
@bridiver We'll have to ask @darkdh for those, I entered this on his behalf.
