### ISSUE TITLE
Brave doesn't appear on Windows Start menu

### ISSUE THREAD

**Issue by vitoc** [brave/browser-laptop#15155]
I did a search via a popular search engine but cannot find this issue. There are seemingly related issues such as #6484 and #2061. I learnt from #2061 that Brave installs into %userprofile%\AppData\Local\. Otherwise, as a normal user, I wouldn't had been able to know where to launch Brave.

When installing Brave via BraveSetup-x64.exe downloaded from the Brave website, the completed installation launches Brave immediately. This is fine. However, Brave does not appear on the Start menu. A normal user would not be able to re-launch Brave if it isn't set as default after the first launch. I had to create a start menu shortcut manually (it still doesn't appear on the application list).

### Steps to Reproduce
  1. Install Brave
  2. Browser through Start menu applications

**Actual result:**

![brave browser](https://user-images.githubusercontent.com/558813/45083508-961e9a00-b12e-11e8-94fd-db452464178c.PNG)

**Expected result:**

That Brave will appear on the list on the left, instead of having to create a shortcut manually in the section on the right.

**Reproduces how often:**

100%

### Brave Version

Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**

Yes

### Additional Information

This may be due to corporate device policy, but I am not sure.

**Comment by bsclifton** [comment]
Thanks for the report, @vitoc 😄 Would you be able to try the install with our new [Developer channel release](https://brave.com/download-dev)? Our current Muon based product does install to this directory (mentioned in your post) which is not ideal. The dev channel build (`brave-core`) should install to a more friendly location and should hopefully be creating a shortcut (if not, I can help create an issue to track this)
