### ISSUE TITLE
Warn Before Quitting feature

### ISSUE THREAD

**Issue by LewisJEllis** [brave/browser-laptop#1515]
Sometimes my fingers are careless and hit `Cmd+Q` when I wanted to hit `Cmd+W`, and then instead of one tab going away, they all go away. Since tabs reopen automatically, this isn't a catastrophic exit, but it's still a nuisance since I rarely ever actually want to exit my browser.

Chrome has a lovely setting for avoiding this called "Warn Before Quitting". It's enabled here:
![](https://i.imgur.com/Db2HwAo.png)

When you hit `Cmd+Q` with it enabled, you get this little overlay message telling you to hold `Cmd+Q` down for a second if you really mean it:
![](https://i.imgur.com/R8xXRoe.png)

A similar option in Brave would be wonderful; it's almost the only thing I miss about Chrome.

I've not worked with Electron before, but I know my way around Node and the codebase looks pretty friendly - a couple quick searches already found most of the relevant pieces to this feature - so I'd be happy to try a PR with some guidance.

I'm specifically unsure about two things:
- whether there are other places in Brave already using this kind of overlay message which this feature should follow, and if not, how a pattern for that might be established.
- whether to put the toggle in the main menu like Chrome, or in the preferences menu instead

**Comment by diracdeltas** [comment]
Hi Lewis!

> whether there are other places in Brave already using this kind of overlay message which this feature should follow, and if not, how a pattern for that might be established.

We are not using overlay messages yet. You could either add a new React component that is absolute-positioned in the middle of the window (something like `js/components/overlayMessage.js`) and have it appear when cmd+Q is pressed, or use an existing component. `js/components/notificationBar.js` might be suitable. Or a standard HTML desktop notification: https://developer.mozilla.org/en-US/docs/Web/API/notification

> whether to put the toggle in the main menu like Chrome, or in the preferences menu instead

Note that the $APP_NAME menu doesn't exist on non-OSX systems, so it would probably go in the `File` menu for Linux / Windows. I feel like preferences is better but lack a strong opinion.

Happy to help with any further questions.

**Comment by alexwykoff** [comment]
+1 from support

**Comment by srirambv** [comment]
@bsclifton @bbondy  Could this be moved back to 1.0? This is a must have feature.

**Comment by LaurenWags** [comment]
+1 from Twitter: https://twitter.com/toddmotto/status/913508882445750272

**Comment by LaurenWags** [comment]
+1 from Twitter: https://twitter.com/bneiluj/status/931154191686479872

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/warn-before-quit/10817?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/ctrl-q-hotkey-immediately-closes-brave-without-confirmation/21505?u=eljuno

**Comment by MiLeung** [comment]
A work around for now is to reconfigure the keyboard shortcut for quitting Brave.

<img width="752" alt="screen shot 2018-06-15 at 3 44 27 pm" src="https://user-images.githubusercontent.com/9166324/41492286-089b3ab4-70b3-11e8-932f-c9b7b091f504.png">

**Comment by enthooz** [comment]
@LewisJEllis — Did you implement this feature?

**Comment by bsclifton** [comment]
I verified this feature is present in [Brave Core](https://github.com/brave/brave-browser); closing this issue as `wontfix` (with regards to fixing it in browser-laptop/Muon)
