### ISSUE TITLE
No FavIcon without WWW

### ISSUE THREAD

**Issue by OfficialEsco** [brave/browser-laptop#15156]
### Description
Some bookmark favicons don't load if it dosn't have www

### Steps to Reproduce
  1. Make a bookmark to https://facebook.com/ this will show no FavIcon
  2. Make a bookmark to https://www.facebook.com/ and it will show a FavIcon

**Actual result:**
No FavIcon.

**Expected result:**
A FavIcon.

**Reproduces how often:**
100%

### Brave Version
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Comment by bsclifton** [comment]
This issue is fixed with our [developer channel](https://brave.com/download-dev) 😄 👍
