### ISSUE TITLE
opening tabs, PT, session tabs opens `about:blank` when there's no Win/Tabs opened

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15162]
### Description

When opening any type of tabs or new windows via the `File Menu` on macOS when there's nothing else opened but Brave is still the active application, you'll get `about:blank` rather than `about:newtab` pages. Assuming it's because of either https://github.com/brave/browser-laptop/issues/15045 or https://github.com/brave/browser-laptop/pull/15047.

### Steps to Reproduce

  1. open brave via macOS and close all windows (keep brave as the active application)
  2. select `File` -> `New Tab` and you'll get `about:blank`

Can reproduce the above using:

* `File` -> `New Private Tab`
* `File` -> `New Private Tab with Tor`
* `File` -> `New Session Tab`

**Actual result:**

Opening `about:blank` pages rather than `about:newtab` pages.

**Expected result:**

Should be opening `about:newtab` and not `about:blank`

**Reproduces how often:**

100% reproducible using the above STR mentioned above.

### Brave Version

**about:brave info:**

```
Brave: 0.23.204 
V8: 6.9.427.19 
rev: a9a7e9ce52e4b35041e0245544298b7431ba7d9c 
Muon: 8.1.3 
OS Release: 17.7.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.81
```

**Reproducible on current live release:**

Yes, currently reproducible under the following build which is the current live build:

```
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
```

### Additional Information

* `0.23.105` 9a46f8f5cb22a9daf2af21989aed25911aa6f839 <-- Reproducible
* `0.23.104` b454a4a99934c4aa27fbe2effc5f72ce92e3266b <-- Reproducible
* `0.23.79` 51b49051a779f0db94fbcfd0df5faca781299ea0 <-- Couldn't reproduce

Reproduced by @LaurenWags as well.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.206 80a5ac1
* Muon 8.1.5
* libchromiumcontent 69.0.3497.92

**Comment by kjozwiak** [comment]
+1 from https://community.brave.com/t/with-no-open-window-links-from-external-apps-dont-open/32467/
