### ISSUE TITLE
Refreshing in dev console refreshes whole app rather than just the page

### ISSUE THREAD

**Issue by kanatzidis** [brave/browser-laptop#1516]
Title is hopefully self-explanatory. I had several tabs open and was focused in the dev console. I hit Cmd+R (I'm on Mac El Capitan) expecting it to refresh only the currently active tab, but instead it refreshed the entire browser and I lost all my tabs.

Let me know if you need further description.

**Comment by kanatzidis** [comment]
Just an addendum: Since the dev console belongs to the electron application and not to the tab, we don't have access to the javascript execution environment that the page is running. This is somewhat inconvenient. Let me know if there's a workaround for this.

**Comment by bbondy** [comment]
There are 2 sets of dev tools and you happened on the wrong one. The per tab page dev tools is in View | Toggle Developer tools.  We need to make the dev tools to work on the actual browser less discoverable.

**Comment by kanatzidis** [comment]
Ah yes, I didn't even think to look there. My first instinct was to hit Cmd+Opt+J from Chrome. Thanks for pointing this out!
