### ISSUE TITLE
Brave crashes when accessing details from mybrowserinfo.com

### ISSUE THREAD

**Issue by lxrocks** [brave/browser-laptop#15161]
### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Closing as I'm unable to reproduce with latest release. We'll need more info in order to diagnose

**Comment by lxrocks** [comment]
No worries Brian, you are correct, it does not occur with lates browser.
Cheers
