### ISSUE TITLE
Brave blocking dependency on Washington Post

### ISSUE THREAD

**Issue by Brave-Matt** [brave/browser-laptop#15170]
Yes
### Description
Some Washington Post articles lose functionality in Brave. Functionality is returned when ads/tracking are allowed.  cc @lukemulks  for additional info.

### Steps to Reproduce
  1. In Brave or Brave-Dev, go to [this Washington Post article](https://www.washingtonpost.com/graphics/2018/lifestyle/travel/amp-stories/2018-travel-photo-contest/?hpid=hp_no-name_no-name%3Ahomepage%2Fstory-ans&noredirect=on)
  2. Make sure Shields are on and Block Ads/Tracking is Enabled
  3. Try to navigate the article

**Actual result:**
Cannot click through slides on article. Pats of layout/elements on page do not display.
Turning Shields off fixes the issue, as does disabling Block Ads/Tracking
**Expected result:**
Normal browsing of the page

**Reproduces how often:**
100%

### Brave Version
Both live release (0.23.105) and Dev release (55.2)

### Additional Information
I've contacted the users about additional information (about:brave, OS). Will edit when user responds. His original message:
![image](https://user-images.githubusercontent.com/3299098/45250753-f4927680-b2ee-11e8-9d2d-efe795a2fd5d.png)

**Comment by lukemulks** [comment]
Looks like an `amp-story`
https://www.ampproject.org/docs/getting_started/visual_story/parts_of_story

IIRC, relatively new format for AMP. 

This feels like a bug on desktop. What I'm seeing with AMP is new. Typically, a user can remove `/amp/` from the url string, and load traditional html. 

This is not the case with these stories. Updating the URL string results in an error, even when moving up a level in the path. Interesting. 

What makes me think this is more of a bug specific to desktop, is that I can use the left and right arrow keys to navigate from image to image. 

It seems like a style set is being blocked by our filters, possibly from a dependency from the amp calls we're blocking. 

Could be a mobile-first => desktop bug.

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
