### ISSUE TITLE
Manual test run on Linux for 0.23.x w/ Chromium 69 (BETA Channel)

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15186]
## Per release specialty tests
 - [ ] Allow for different default search engines based on region. ([#14647](https://github.com/brave/browser-laptop/issues/14647))

## Installer

- [ ] Check that installer is close to the size of last release.
- [ ] Check signature: If OS Run `spctl --assess --verbose /Applications/Brave.app/` and make sure it returns `accepted`.  If Windows right click on the installer exe and go to Properties, go to the Digital Signatures tab and double click on the signature.  Make sure it says "The digital signature is OK" in the popup window.
- [ ] Check Brave, muon, and libchromiumcontent version in `about:brave` and make sure it is EXACTLY as expected.

## Update tests

- [ ] Test that updating using `BRAVE_UPDATE_VERSION=0.8.3` env variable works correctly.
- [ ] Test that using `BRAVE_ENABLE_PREVIEW_UPDATES=TRUE` env variable works and prompts for preview build updates.

**Comment by srirambv** [comment]
Closing in favour of #15189 . Issue #14647 added to #15189 for re-verification
