### ISSUE TITLE
Pinned Tabs Always Created in New Window of Brave

### ISSUE THREAD

**Issue by besteman** [brave/browser-laptop#15190]
Yes.

### Description
 
When I have tabs pinned and move a tab to make a new window, the pinned tabs following into the new window. Also, when you start a new window it will load the pinned tabs.

The new window of Brave should not duplicate the pinned tabs in the original window or new window should not load pinned tabs in original window.

### Steps to Reproduce

  1. Pin Tabs
  2. Move a tab (not pinned tab) to make a new window
  

1. Pin Tabs
2. Open new window

**Actual result:**
Pinned Tabs in original follow in every new window.

**Expected result:**

To not have the pinned tabs loaded into the new window of Brave

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

![image](https://user-images.githubusercontent.com/19551504/45436592-24d86d00-b681-11e8-99a9-b5362bffdc08.png)

### Additional Information

![gif](http://besteman.io/805bef4fa7dd/Screen%252520Recording%2525202018-09-12%252520at%25252011.45%252520AM.gif)

http://besteman.io/30842303b6b5

**Comment by srirambv** [comment]
This issue is fixed in brave-core and wont be fixed on muon
