### ISSUE TITLE
"Open in New Tab" opens in new private tab, from normal tab

### ISSUE THREAD

**Issue by ocouch** [brave/browser-laptop#15195]
### Steps to Reproduce

I'm not sure how to reproduce this issue in a new session window, but it is definitely occurring right now on my machine, including this tab which I have just opened, but wasn't occurring in this tab moments ago - could have something to do with switching between tabs?. I have had private tabs open in this window/session, and have had a lot of different tabs opened and closed.

It seems to be intermittent.
Also occurs on middle mouse click.

**Actual result:**

![image](https://user-images.githubusercontent.com/43231870/45472217-e02efd80-b776-11e8-9991-edacd6af196b.png)

**Expected result:**
Middle click and right click->Open in New Tab should open a new tab which records browsing history etc.

**Reproduces how often:**

Small? I often leave browser windows open for extended periods of time without killing the program. I'm unsure at which stage this began occurring.

### Brave Version

**about:brave info:**

 
Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Reproducible on current live release:**

Probably yes; I shall update if not. However, noting I'm not currently sure how to reproduce the bug, this may take some time.

### Additional Information

Win 7 x64

**Comment by thornjad** [comment]
@ocouch have you been able to reproduce this so far?

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
