### ISSUE TITLE
Dnd of webpage shortcut creates two error tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15208]
### Description
Dnd of webpage shortcut creates two error tabs

### Steps to Reproduce

  1. Visit a site and dnd the lock icon on to desktop to create a shortcut. Content of the shortcut should look like this 
```
[InternetShortcut]
URL=https://www.motorsport.com/
```
  2. Open a new tab, visit a different site and dnd the shortcut created on to the tab
  3. Opens two tabs trying to load http://text/uri-list  & http://text/plain

**Actual result:**
Dnd of webpage shortcut creates two error tabs

**Expected result:**
Should load the site correctly on the same tab on which the shortcut was dnd

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.207
-- | --
V8 | 6.9.427.23
rev | 281de88
Muon | 8.1.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**
Yes

### Additional Information
https://github.com/brave/browser-laptop/issues/9699
Reproduced on Windows and Linux
cc: @brave/legacy_qa

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
