### ISSUE TITLE
Pinned tabs: Command + Number out of order

### ISSUE THREAD

**Issue by rwaldron** [brave/browser-laptop#1520]
Open three tabs to any three websites. I'll use letters to represent here: A, B & C. Pin the tab for A, then pin the tab C. The tabs now display in this order: A, C, B. 

1. Command + 1 -> jumps to pinned tab for A
2. Command + 2 -> jumps to pinned tab for **B**
3. Command + 3 -> jumps to pinned tab for **C**

I would expect that the order of Command + N would always be left-to-right, in order, starting from 1.

Details: 

- OSX 10.11.4 (15E65)
- Brave: 0.9.2
- Electron: 0.37.6
- libchromiumcontent: 49.0.2623.112
- V8: 4.9.385.35
- Node.js: 5.10.0
- Update channel: dev

Let me know if anymore information is needed.

**Comment by diracdeltas** [comment]
Duplicate of #149

**Comment by bbondy** [comment]
Closing in favour of that.
