### ISSUE TITLE
Always re-creates ~/Downloads folder, no matter which download setting is chosen

### ISSUE THREAD

**Issue by hanswundersam** [brave/browser-laptop#15201]
### Description

Brave browser always defaults to the standard download folder no matter what setting I choose in the browser settings. This bug has been described in the community forum [since](https://community.brave.com/t/download-setting-not-working-correctly/26534/3) [2017](https://community.brave.com/t/downloading-recreates-the-last-downloaded-to-folder/11769) but with no repair or even reaction, so I post it here as well, hoping for it to be seen.

### Steps to Reproduce

  1. Download a file (ensure “Always ask me where to save files” is true)
  2. Save it to ~/tmp/brave/a/b/c/
  3. Delete the a folder like rm -rf ~/tmp/brave/a
  4. Click a link to download a new file

**Actual result:**

Brave recreates ~/tmp/brave/a/b/c/.

NOTE: You just click to download, you don’t actually need to save the new file. As soon as the “save file as” box has opened, the folder hierarchy has been recreated.

**Expected result:**

You should be prompted to download the file in either ~/tmp/brave or ~/Downloads.

**Reproduces how often:**

Every time.

### Brave Version

**about:brave info:**

Brave | 0.23.107
V8 | 6.8.275.24
rev | 6f2fc65
Muon | 8.0.10
OS Release | 4.15.0-34-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Comment by bsclifton** [comment]
Hi @hanswundersam - thanks for the report

This issue is resolved with our [Developer channel release](https://brave.com/download-dev) and we won't be fixing this with our current Muon based product
