### ISSUE TITLE
opening local files via DnD creates `about:blank` tabs rather than opening the file

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15203]
### Description

Opening files via dragging and dropping in the tab bar opens `about:blank` tabs rather than opening the files. We've also received similar complaints from the community:

* https://www.reddit.com/r/brave_browser/comments/9bgsot/v023105_for_desktop_has_been_released/e55r5sj

I'm assuming this is another regression from the `about:blank` security issue that we added into the `0.23.104` release which has caused several `about:blank` regressions.

### Steps to Reproduce

  1. ensure that you have a `.html` or a `.txt` file saved locally
  2. install & launch either `0.23.206` 80a5ac134e251a9cb3565023e2447d6d7b4487a7 or `0.23.107` 6f2fc65b3c7db0b260ad154fbef5919902495387.
  3. once brave has launched, load any random website in a tab
  4. drop the local file you have saved on top of the above tab and you'll notice that instead of opening the local file, it creates a `about:blank` tab

**Actual result:**

**macOS Example:**

![dndblank](https://user-images.githubusercontent.com/2602313/45575829-ec808c80-b842-11e8-8cd5-635d36fb1d7d.gif)

**Windows 10 x64 Example:**

![dndblank](https://user-images.githubusercontent.com/2602313/45575884-0e7a0f00-b843-11e8-9706-94e5d6bec87b.gif)

**Expected result:**

DnD files into the tab area should be opening the files rather than creating `about:blank` tabs.

**Reproduces how often:**

It's 100% reproducible on macOS but not always reproducible on Win.

### Brave Version

**about:brave info:**

```
Brave: 0.23.206 
V8: 6.9.427.22 
rev: 80a5ac134e251a9cb3565023e2447d6d7b4487a7 
Muon: 8.1.5 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.92
```

**Reproducible on current live release:**

Yes, currently reproducible on the following build which is the current live version:

```
Brave: 0.23.107 
V8: 6.8.275.24 
rev: 6f2fc65b3c7db0b260ad154fbef5919902495387 
Muon: 8.0.10 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
```

**Comment by bsclifton** [comment]
cc: @diracdeltas

**Comment by bsclifton** [comment]
@kjozwiak is this a duplicate of https://github.com/brave/browser-laptop/issues/15134?

**Comment by kjozwiak** [comment]
@bsclifton they're a bit different but I suspect the fix would probably cover both cases. This particular case also affects `.txt`, `.html` and others. #15134 deals with directly clicking on `.html` files and seeing the `about:blank` pages. This case deals with opening files by directly dropping them on tabs that have already been created.

Are we going to fix this in this release or should we move it to the `0.23.x Release 7`? We're going to need a `muon` build either way so it would be nice to get these fixed. If we're going to fix this in the C69 release, we should include #15134 as well.

**Comment by kjozwiak** [comment]
Thanks @diracdeltas, moved #15134  into this milestone as well 👍

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.207 281de88
* Muon 8.1.6
* libchromiumcontent 69.0.3497.100
