### ISSUE TITLE
several performance issues with muon based on C69

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15202]
### Description

There seems to be a few performance issues with muon that includes C69. So far we've noticed the following area's that seem a bit slower/jankier compared to the current `0.23.107` 6f2fc65 build which is based on `68.0.3440.84`:

* window resizing
* application launch time
* detaching tabs from a window

### Steps to Reproduce

  1. install `0.23.107` 6f2fc65 and resize the window several times (note the performance)
  2. install `0.23.206` 80a5ac1 and resize the window several times (note the performance)

You'll notice a big difference in performance between `0.23.107` and `0.23.206` when it comes to resizing windows.

**Actual result:**

Resizing windows on `0.23.206` 80a5ac1 is a lot slower/jankier compared to `0.23.107` 6f2fc65 which feels a lot more snappier. Definitely seems like the performance has decreased with `0.23.206` 80a5ac1.

**Expected result:**

Resizing windows on `0.23.206` 80a5ac1 should be as performant as `0.23.107` 6f2fc65.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

```
Brave: 0.23.206 
V8: 6.9.427.22 
rev: 80a5ac134e251a9cb3565023e2447d6d7b4487a7 
Muon: 8.1.5 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.92
```

**Reproducible on current live release:**

No, not reproducible under `0.23.107` 6f2fc65 which is currently the released version based on C68.

**Comment by LaurenWags** [comment]
Using macOS, I did some comparisons of `0.23.107` to `0.23.206` in the following areas:
1. tab resizing - verified resizing a window isn’t as smooth on 0.23.206
2. launch - tried two ways first way was with a profile with 1 window, 7 tabs. in both versions Brave took about 3 to 3.5 seconds to launch. second way tried was a profile with 4 windows, each window has 150 tabs. with `0.23.107` Brave launched in about 9.5-10s, and in `0.23.206` Brave launched in about 10-10.5s. slightly slower on 0.23.206 but not absurdly so.
3. tab detach - I’m not noticing much of a difference between the two versions in this area. 0.23.206 might be a tiny bit slower, but it’s not obvious on my machine.

**Comment by kjozwiak** [comment]
@bsclifton I went through all the C69 that were uploaded. Hopefully this helps you narrow down the issue but it seems like it's been in C69 since the start:

 
* `0.23.206` 80a5ac134e251a9cb3565023e2447d6d7b4487a7 - reproduced resizing issue (CR: 69.0.3497.92)
* `0.23.205` 81396b3a6454480382ffc476a8b8590fec73717e - reproduced resizing issue (CR: 69.0.3497.92)
* `0.23.204` b71d1706c03af4a467c1a9a03c51bd88ad523987 - reproduced resizing issue (CR: 69.0.3497.81)
* `0.23.203` 16c2c198f897b4ffbfdbd3e8f725af7d20f85e75 - reproduced resizing issue (CR: 69.0.3497.72)
* `0.23.202` bfbd176558fb249813971fcb3a6ef6957bf4f98e - reproduced resizing issue (CR: 69.0.3497.72)
* `0.23.201` 17d2d17a64b6ea5e85ff8fbe324798447887e81b - reproduced resizing issue (CR: 69.0.3497.57)

**Comment by srirambv** [comment]
App response on Windows is pretty fast same as previous versions. The new tab image load time is slow. On Linux, resizing tab is a little choppy but the new tab image load is pretty instant.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/muon/commit/6c2f2354919cac3e3f2d4030c44a1ced6a2940b9

**Comment by bridiver** [comment]
also https://github.com/brave/browser-laptop-bootstrap/commit/657c7178e81bb30ddfb687800161b4dcc9caf3e1

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.207 281de88
* Muon 8.1.6
* libchromiumcontent 69.0.3497.100

1. tab resizing - verified resizing is much smoother with `0.23.207` and works like `0.23.107`
2. launch - verified with a profile with 4 windows, each window has 150 tabs, version `0.23.207` of Brave launched in about 10-10.5s.
3. tab detach - verified tab detach appears to be the same on `0.23.107` and `0.23.207` and there is not a noticeable difference.
