### ISSUE TITLE
Brave on first launch says welcome to chrome.

### ISSUE THREAD

**Issue by vtaparia** [brave/browser-laptop#15216]
### Description
After upgrading to 24.0 when you first time launch and go to google.com Brave says "Welcome to Chrome"
### Steps to Reproduce

  1. Upgrade Chrome to 24.0 Release
  2.Go to google.com
  3.On right side of window you will see a notice as welcome to Chrome.

**Actual result:**

**Nothing should show up like this.**

**Reproduces how often:**

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.24.0
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 17.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**

Yes

**Comment by rebron** [comment]
Closing and tracked here. https://github.com/brave/brave-browser/issues/1052
but really a google.com issue.
