### ISSUE TITLE
pinch-to-zoom via the trackpad not working

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#15217]
### Description

Looks like pinch-to-zoom via the trackpad regressed with C69. Received report from the community:

* https://community.brave.com/t/trackpad-pinch-to-zoom-no-longer-working-after-0-24-0-update/32705

### Steps to Reproduce

  1. launch `0.24.0` f657f15bf7e0e0c50a2b854c6b05edb59bfc556c
  2. visit wikipedia.org/ and attempt to pinch-to-zoom via the trackpad

You'll notice that the shortcut isn't working under `0.24.0` but is working under `0.23.107` which was the previous released based on C68.

**Actual result:**

Pinch-to-zoom via the trackpad has regressed and isn't working with `0.24.0` f657f15bf7e0e0c50a2b854c6b05edb59bfc556c.

**Expected result:**

Pinch-to-zoom via the trackpad should be working as expected. This worked under `0.23.107` running C68. Seems to have regressed with `0.24.0` running C69.

**Reproduces how often:**

100% reproducible using the STR mentioned above.

### Brave Version

**about:brave info:**

```
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

**Reproducible on current live release:**

Yes, currently reproducible with `0.24.0` f657f15bf7e0e0c50a2b854c6b05edb59bfc556c which was just released. However, this issue isn't reproducible using `0.23.107` which was the last release based on C68.

**Comment by jesusmartinoza** [comment]
+1 
```
Brave | 0.24.0
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 17.3.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

```

**Comment by maxlieblich** [comment]
Same problem in Windows 10, with both trackpad and touchscreen.

```
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

**Comment by kjozwiak** [comment]
For the folks that are running into the above issue which is hindering their Brave experience, I would recommend trying our new browser which also uses Chromium’s native user interface instead of our current HTML and JavaScript muon based UI. You can download the builds from the following locations:

* https://brave.com/download-dev/
* https://brave.com/download-beta/

**Comment by bsclifton** [comment]
This issue should be fixed if you grab the new version of Brave 😄 
https://brave.com/download/
