### ISSUE TITLE
navigator.clipboard.readText() silently fails

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#15219]
### Steps to Reproduce

  1. Copy some text into clipboard
  2. Go to https://jsfiddle.net/hpy02no3/2/
  3. Press Try it

**Actual result:**
Nothing happens

**Expected result:**
A prompt is shown asking if user wants to allow clipboard usage, just like in Chrome.
The text from clipboard is shown

**Reproduces how often:**
always

### Brave Version

**about:brave info:**
 

```
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

**Reproducible on current live release:**
yes, Brave: 0.24.0.

### Additional Information
Works on Chrome 69.0.3497.100 (Official Build) (64-bit)

Reported through community:
https://community.brave.com/t/navigator-clipboard-readtext-not-working/32697/3

**Comment by kjozwiak** [comment]
@btlechowski can you check if this was working on `0.23.107` which was the release before `0.24.0`? If it's working in that version, lets stick this into https://github.com/brave/browser-laptop/milestone/124 as a C69 regression. If it's the same thing on `0.23.107`, we should check and see if it's happening under `brave-core` and create an issue there if that's the case.

If this has been broken for a while and not a regression with C69, I doubt it will get fixed before the `brave-core` migration.

**Comment by btlechowski** [comment]
This issue is not reproducible on v0.23.107. Does not reproduce in brave-core.
