### ISSUE TITLE
blocking file called miner.js

### ISSUE THREAD

**Issue by atlemagnussen** [brave/browser-laptop#15227]
I experiencing that a js file called miner.js is just never loaded with your browser, but works perfectly with Chrome and Firefox.

I have software for monitoring of miner rigs, nothing to do with malware, it contains only custom elements code. I guess you block it solely based on filename and not content.  
If so - please stop.

**Comment by bsclifton** [comment]
cc: @bbondy for visibility; this would probably require an update to the ad-block definitions?
