### ISSUE TITLE
Dapp detection is inaccurate

### ISSUE THREAD

**Issue by tmcw** [brave/browser-laptop#15221]
### Description

Our site, [Observable](https://beta.observablehq.com/) triggers a modal that says 'this site has a dapp available, do you want to install MetaMask?'

### Steps to Reproduce

  1. Open https://beta.observablehq.com/

**Actual result:**

![image](https://user-images.githubusercontent.com/32314/45852460-de27ea00-bcf4-11e8-864b-c75407eab27e.png)

**Expected result:**

There is no suggestion, because there is no dapp.

**Reproduces how often:**

Always

### Brave Version

 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**

Only relase

### Additional Information

This tracks down to the [dappListener.js](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/content/scripts/dappListener.js) file, which basically says that

1. If the content scripts declare window.web3
2. Or if they ever _access_ window.web3

Then it's a dapp. That's a very fishy way to detect a dapp. For example, our site has this code, that triggers it:

```js
const globals = new Set(
  Object.getOwnPropertyNames(window).filter(key => {
    try {
      return (
        !/^webkit/i.test(key) && // Avoid deprecation warnings.
        !blacklist.has(key) &&
        window[key] != null
      );
    } catch (e) {
      return false;
    }
  })
);
```

Minus the bulletproofing, this tiny snippet should be enough to trigger a false dapp message:

```js
Object.getOwnPropertyNames(window).forEach(key => window[key])
```

A pretty reasonable thing for a website, and which should _not_ accidentally trigger a false modal encouraging a user to install some bonus software. In our case, it's to power autocompletion and some static analysis in a code editor, but there are plenty of other cases that I can imagine that will also trigger a false message.

Hopefully there can be a better heuristic here: this one is very broad and inaccurate.

**Comment by tmcw** [comment]
Here's a one-line live testcase, if that helps: https://not-a-dapp-nfquxosbbu.now.sh/

**Comment by bsclifton** [comment]
Thanks for the feedback, @tmcw 😄 Our new version of Brave doesn't have Dapp detection (yet), but I've made note of this issue in the issue tracking its development:
https://github.com/brave/brave-browser/issues/718

Closing this issue as the `browser-laptop` (Muon) version of Brave is deprecated
