### ISSUE TITLE
Hovered-over elements are not highlighted after switching tab with keyboard

### ISSUE THREAD

**Issue by FWDekker** [brave/browser-laptop#15234]
### Description
After switching between tabs using the keyboard (using Ctrl+Page Up/Page Down), elements that happen to be underneath the cursor do not have the CSS `:hover` effect applied to them.

This causes minor confusion/uncertainty because I do not know if I will click at the intended element on the website.

### Steps to Reproduce

  1. Open [DuckDuckGo](https://duckduckgo.com/) in two different tabs.
  2. Hover the cursor over the magnifying glass so that it gets a green background.
  3. Switch to the other tab using a keyboard shortcut _without moving the cursor_.

**Actual result:**
The magnifying glass does not have a green background, as if the cursor is not hovering over it.

**Expected result:**
The magnifying glass has a green background.

**Reproduces how often:**
100% of the time.

### Brave Version

**about:brave info:**

| Name | Version |
|---|---|
| Brave | 0.24.0  |
| V8 | 6.9.427.23  |
| rev | f657f15bf7e0e0c50a2b854c6b05edb59bfc556c  |
| Muon | 8.1.6  |
| OS Release | 10.0.17134  |
| Update Channel | Release  |
| OS Architecture | x64  |
| OS Platform | Microsoft Windows  |
| Node.js | 7.9.0  |
| Brave Sync | v1.4.2  |
| libchromiumcontent | 69.0.3497.100 |

**Reproducible on current live release:**
Yes

**Comment by bsclifton** [comment]
Thanks for the report - I'd like to ask if you can try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
