### ISSUE TITLE
Individual Site Process Isolation Freezes 'about:welcome' Site.

### ISSUE THREAD

**Issue by rolandog** [brave/browser-laptop#15238]
### Description
If you enable the option `Enhance security by loading each site in its own process (experimental) *`, the `about:welcome` site becomes unresponsive (no text selection, scrolling or clicking possible) and doesn't load properly.

### Steps to Reproduce

  1. Enable the option: `Enhance security by loading each site in its own process (experimental) *`
  2. Restart
  3. Load `about:welcome`

**Actual result:**

Unresponsive site. Doesn't load properly, clicking on buttons doesn't open tabs, scrolling is not possible (via trying to drag scrollbar or mouse-wheel).

**Expected result:**

Page is loaded. Animations take place on load event. Buttons trigger actions. Scrolling enabled.

### Brave Version

**about:brave info:**

Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**
What are live releases? Betas? I don't know if I have tested it.

### Additional Information

**Current configs:**
- Block Ads
- Block 3rd Party Cookies
- Block 3rd Party Fingerprinting
- HTTPS Everywhere
- Block Scripts (will break many sites)
- Block Phishing / Malware
- Autoplay Media: Always ask
- Disable non-proxied UDP

**Comment by TjReiny** [comment]
yep currently discovered this browser and faced exact same problem, this is totaly repeat-able.

**Comment by bsclifton** [comment]
Thanks for the report, @rolandog! Unfortunately, this is not something we'll be fixing. If you wanted to grab a copy of our Beta release, we have site isolation enabled by default and there are no known issues (like there are with the `browser-laptop` code-base)

You can grab a copy here:
https://brave.com/download-beta
