### ISSUE TITLE
update to muon 8.1.7

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#15242]
## Test plan
1. Visit about:brave
2. Ensure `Muon` version is `8.1.7`

## Description
Update to https://github.com/brave/muon/releases/tag/v8.1.7

**Comment by diracdeltas** [comment]
closing in favor of https://github.com/brave/muon/releases/tag/v8.1.8

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/15265

**Comment by GeetaSarvadnya** [comment]
Verified on Linux x64
•	0.25.0 907c7e43c291e6aba5030261d22ee1f8748d654e
•	Muon 8.1.8
•	libchromiumcontent 69.0.3497.100
