### ISSUE TITLE
forget it.. doesn't work, no one helps.

### ISSUE THREAD

**Issue by Smooey** [brave/browser-laptop#15247]
forget it.. doesn't work, no one helps.

**Comment by bsclifton** [comment]
@Smooey sorry, it's the weekend and time is limited (especially with a lot of us working on the new code-base, [brave-core](https://github.com/brave/brave-browser)). Within the next 2 months, we're planning on deprecating this code-base entirely.  I'd suggest checking out that new one instead 😄

**Comment by bsclifton** [comment]
If you wanted to get this code-base working, you can follow the guide here:
https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide

By looking at your edited comment, you appear to be missing Python or you didn't have the PATH environment variable set

**Comment by Smooey** [comment]
> @Smooey sorry, it's the weekend and time is limited (especially with a lot of us working on the new code-base, [brave-core](https://github.com/brave/brave-browser)). Within the next 2 months, we're planning on deprecating this code-base entirely. I'd suggest checking out that new one instead 
> 
> You can download this new version here:
> https://brave.com/download-beta

Oh okay, thanks! And sorry, was a bit impatient at the time of writing and editing. I should have known with the weekend that most were busy with family or other things, my apologizes. So basically follow that guide you linked above there, but don't do "browser-laptop" do "brave-core" instead?

**Comment by Smooey** [comment]
alright, tried it again for that document link you gave above there and it still don't work. Lol! says there's no "start" script" nor "watch" script or whatever... after " git clone https://github.com/brave/brave-core " to documents folder...

**Comment by bsclifton** [comment]
@Smooey actually, the new code-base (brave-core) has a different setup process. You can clone this repository:
https://github.com/brave/brave-browser

And then there are setup steps here:
https://github.com/brave/brave-browser/wiki

Because this does do a full Chromium build, it can take as much as 80 GB of space to compile (and it'll take ~6 hours on a decent laptop)

**Comment by Smooey** [comment]
Oh sweet Jesus, to do all that just to be able to install extensions available from Google Chrome store? I'll pass...dunno why it takes that much space and time just to still TRY and be able to do some extension installs. Running the .exe file for Brave itself doesn't do all that stuff, doesn't need Node installed, doesn't need Python installed, doesn't need all this other bullshit installed and doesn't need 80GB of space and 6 hours of your time to install. Bottom line is this, Brave just needs to allow users to install whatever the hell extensions they want to install like normal browsers do... It's all "we" ask for ....

**Comment by srirambv** [comment]
You can install [brave-browser-beta](https://brave.com/download-beta) which allows you to install extensions of your choice. You don't need to build from source to install the extensions you want.

**Comment by bsclifton** [comment]
@Smooey yeah, no need to compile from source. I'd recommend using the link that @srirambv shared 😄👍 

Running from source is only something you need to do if you plan on jumping into the code with us and adding features or fixing bugs. If you just want to use it, there's no need at all for downloading the code (other than for auditing, if you'd like)

**Comment by Smooey** [comment]
Thanks for your replies guys... sorry for the cursing of course, just been frustrated lately. Installed that Brave Beta and that's what I want!! Thank you! I love that Brave Beta so far! :) :D Brave should have been like that from the get go lol. I didn't mind some of the prepackaged extensions before though, like LastPass, and PDF viewer... but it should have allowed users to uninstall the ones they didn't want /need. Like Honey, MetaMask, etc etc. I haven't looked too far into Brave Beta though, but from what I can tell it only comes prepackaged with PDF viewer? Which is nice and good extension to have.

**Comment by Smooey** [comment]
This is a little note/suggestion type comment. But would LOVE in general if Brave gets a built-in screen capture feature like Vivaldi has. Where it's right in bottom of browser or whatever for doing full page captures or selection captures, for jpg, png, etc. And I miss the old style Chrome bookmark manager... their new bookmark manager sucks lol. And there's no way to revert back to the old style one either, there used to be in chrome:/flags or something.

**Comment by bsclifton** [comment]
@Smooey I created an issue for that, in case you wanted to give it a thumbs up or leave a comment:
https://github.com/brave/brave-browser/issues/1374
