### ISSUE TITLE
VMware ESXI 6.5 login interface not showing field to login

### ISSUE THREAD

**Issue by jmvl** [brave/browser-laptop#15241]
### Description

When going to ESXI login page instance it fails to show the input fields.

### Steps to Reproduce

The SSL cert. of the page is invalid. Via a fqdn it works. Via direct IP it fails
  1.Go to an ESXI 6.5 login page... here is one https://188.165.197.54/ui/
  2. Username and password fields are not displayed
3. Try with another browser like Chrome or Safari and it will work 

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

version 0.24

**Reproducible on current live release:**

Live build issue

### Additional Information

<img width="363" alt="log in - vmware esxi 2018-09-28 14-17-58" src="https://user-images.githubusercontent.com/6292978/46207960-67f53a00-c329-11e8-91ad-ee5675698094.png">

**Comment by srirambv** [comment]
Does allowing All cookies from shields  fix it?

**Comment by bsclifton** [comment]
Thanks for the report - I'd like to ask if you can try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
