### ISSUE TITLE
"No Usable Sandbox" on Linux  (Solved)

### ISSUE THREAD

**Issue by jll2** [brave/browser-laptop#15245]
When installed on Debian-Stretch as per the current instructions, brave fails with the message `No usable sandbox!`

The reason is clear when one runs `strace brave`.  In the output, one finds the line:

    access("/usr/lib/brave/chrome-sandbox", F_OK) = -1 ENOENT (No such file or directory)

Under Debian Stretch, the solution is:

    apt-get install chromium
    ln -s ../chromium/chrome-sandbox /usr/lib/brave/chrome-sandbox

After this, `brave` will successfully start.

Similar issues:
1. Issue #8950 was closed with the assertion that the kernel needed to be recompiled.  Since the Debian Stretch stock kernel runs both (google-)`chrome` and `chromium` successfully, this appears not to be the case here.

2. Issue #6902 was closed with the claim that the problem would be solved in some future brave release at some future unspecified date.  That will be good when it happens but the solution/workaround here works right now.

3. Issues #11175, #9955, #6930, and #7146 are related.

**Comment by bsclifton** [comment]
Thanks for the report folks - I'd like to ask if you can try grabbing the new version of Brave?
https://brave.com/download

Install instructions should be shown in the above link. If you run into problems, you can create an issue in the new repository:
https://github.com/brave/brave-browser
