### ISSUE TITLE
Show menu by default on Windows and allow to turn it off

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1524]
A lot of times Windows users think we're missing functionality because there's no menu bar visible in Windows.  Of course like in most Windows apps you can press Alt to show it, but a lot of users don't see that.

This task is to:
i) Show the menu bar by default on Windows
ii) Add another context menu item next to the Bookmarks Toolbar one for Menu Bar. 

CC @bradleyrichter if he has objections.

Originally it was hidden by default because on Windows we have extra window chrome from the titlebar. Ideally we could get rid of that first bu this task would be a lot easier to do first.

**Comment by bbondy** [comment]
btw I'd still like us to have the on / off context menu even if we don't change the default. 
Also you can change this `autoHideMenuBar: true,` in appStore.js.
CC @bsclifton  in case he's interested in taking and typing this to a pref.

**Comment by bsclifton** [comment]
Should be a slam dunk- will check out later today

**Comment by bradleyrichter** [comment]
We need this. Too many support requests related to not finding the menu.

**Comment by bsclifton** [comment]
Started to work on this...
https://github.com/bsclifton/browser-laptop/commit/97f789898b080933ecd88c4c0763b8b082a6805b

Requires a browser restart at the moment, trying to find a clean way to hook into electron::BrowserWindow#setMenuBarVisibility(visible) when the property changes

Should this change only be visible to Windows users? Or visible to all but only defaulted to show the menu on Windows?

**Comment by SJ-Diamond** [comment]
Would make sense to make the hamburger menu disappear if the menu bar is shown. Would be nice if you would implement that.

**Comment by bradleyrichter** [comment]
I am a little concerned about things moving around when hiding the burger. 

Before we add this hiding ability, let me look at how "those other browsers" deal with this issue. 

Tx - Brad

**Comment by bbondy** [comment]
I think the hamburger menu is still useful for ease of access for common things like zoom for example.  If we're going to hide it I'd rather just have a second checkbox like the Show Home Button option.

**Comment by bsclifton** [comment]
Should be completely fixed by https://github.com/brave/browser-laptop/pull/1630

Ready for review :smile:

**Comment by luixxiul** [comment]
Closing as this was already fixed.
