### ISSUE TITLE
Question: ungoogled-chromium instead of vanilla chromium?

### ISSUE THREAD

**Issue by Nezteb** [brave/browser-laptop#15248]
There was a conversation on Reddit about Brave being insecure because of Electron/Chromium reliance: https://www.reddit.com/r/privacytoolsIO/comments/9jn3de/please_dont_recommend_use_brave/

Also see: https://github.com/Eloston/ungoogled-chromium

Does the Brave team agree with these concerns or specifically address them via muon development or Brave itself?

Also see:
* https://github.com/brave/muon/issues/650
* https://github.com/brave/brave-browser/issues/1359

**Comment by bsclifton** [comment]
Hi @Nezteb - I just left a response there in the reddit thread:
https://www.reddit.com/r/privacytoolsIO/comments/9jn3de/please_dont_recommend_use_brave/e6xxx12/

I personally don't know anything about ungoogled chromium, so I can't really respond to that question. However, removing anything that phones home is a top priority for us, and as far as I know, we've done this
