### ISSUE TITLE
Youtube wasted space recover

### ISSUE THREAD

**Issue by TjReiny** [brave/browser-laptop#15244]
hi there im also highly active on Better discord, i recently joined Brave wich is real great.
I wish an Plugin like Styles wich could easy used to fix a few things and create themes easy.

apply this CSS should fix the empty space in youtube created on absence of the ads.
 
#container.ytd-iframe-companion-renderer > *.ytd-iframe-companion-renderer:last-child:not(#google_companion_ad_div) {margin-bottom: 0px !Important;Display: none !Important}

version 0.24

**Comment by bsclifton** [comment]
Thanks for the report, @TjReiny 

Can you please grab the latest version of Brave
https://brave.com/download

With this new version, you can right-click and pick Brave > Block element via selector to do cosmetic filtering on any site
