### ISSUE TITLE
Open in new tab option appears for non links, and then doesn't open when selected

### ISSUE THREAD

**Issue by JamieFarrelly** [brave/browser-laptop#15256]
### Description
The option to "Open Link in new tab" appears when you highlight text such as this below but then a white page is loaded when selected (Note: It's not actually a link!):
![image](https://user-images.githubusercontent.com/12645106/46357079-f3d5d180-c65b-11e8-999c-8ec5ab08a8c9.png)

Here's the link to that page: https://www.tivix.com/blog/dont-forget-the-back-button-in-your-single-page-ap

### Steps to Reproduce

1. Go to https://www.tivix.com/blog/dont-forget-the-back-button-in-your-single-page-ap
2. Search for Fireworks.com
3. Highlight Fireworks.com
4. Right click and select any option such as "Open Link in new tab" or "Open Link in new private tab" etc

**Actual result:**
Empty page opens.

**Expected result:**
The link is opened just as if it would be if it was a "real" link to the site. I think that's a nice feature. If that's too much work then don't have these options when you right click the highlighted text I guess.

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**
Brave | 0.24.0
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**
I assume so but not 100%.

### Additional Information
N/A

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
