### ISSUE TITLE
Option to disable mixed content does not work for ajax requests

### ISSUE THREAD

**Issue by Bucky24** [brave/browser-laptop#15250]
This is somewhat of a followup to https://github.com/brave/browser-laptop/issues/3443. I have searched google for this issue but have not found anything, so I am opening a bug.

### Description

I currently have a site that I load via https, and makes an ajax request to another server using http. I cannot change this currently for either site. The option to "load unsafe scripts" does not seem to persist/work for ajax requests at all-when the page reloads, I still get the same error.

### Steps to Reproduce
  1. Load an https website
  2. Trigger an http ajax request
  3. Click the lock icon to the left of the URL bar, then click "load unsafe scripts"
  4. The page reloads. Try to trigger the ajax request again.

**Actual result:**

Look in console and click the lock icon again. The same "load unsafe scripts" option is available, and the same error "cannot load unsafe content" shows up in console.

**Expected result:**

I would expect the ajax request to now go through. Performing these exact same steps on Google Chrome will allow the ajax request to work.

**Reproduces how often:**

100%

### Brave Version

Brave | 0.24.0
-- | --
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**

I am on the latest release.

### Additional Information

I can put up an example page that does this if desired.

**Comment by bsclifton** [comment]
Thanks for the report - I'd like to ask if you can try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser

**Comment by Bucky24** [comment]
The bug appears to have been fixed in the latest version! Thanks!
