### ISSUE TITLE
Atlassian Cloud Not Loading 

### ISSUE THREAD

**Issue by besteman** [brave/browser-laptop#15258]
### Description

Curious what is happening here. I have shields down and Atlassian is not loading still. This is happening in Brave and Brave Beta. I want to get away from Chrome and this is the last thing that makes me go back to it.

Please help me abandon Chrome once and for all!

![image](https://user-images.githubusercontent.com/19551504/46384192-6fe31000-c682-11e8-8126-d48b98bd2808.png)

### Brave Version

Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 18.0.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by NumDeP** [comment]
Provide the same information with it not working on brave-beta and create the topic here https://github.com/brave/brave-browser/ it may get mitigated faster. 

Why are you using the Moun version still considering the new Chromium/dev/beta/core version is vastly better?

**Comment by bsclifton** [comment]
@besteman can you please try the new version of our browser? This version (`browser-laptop`) is in the process of being deprecated in favor of the new code-base (`brave-core`). You can download a copy here:
https://brave.com/download-beta

**Comment by mitchwoloschek** [comment]
> @besteman can you please try this in the new version of our browser? This version (`browser-laptop`) is in the process of being deprecated in favor of the new code-base (`brave-core`). You can download a copy here:
> https://brave.com/download-beta
> 
> If the problem continues to happen, I'll help you open an issue there so we can investigate 😄

I just downloaded the beta version and I'm still running into the same issue. Suggestions?

**Comment by bsclifton** [comment]
@mitchwoloschek we're tracking this in the new browser repo with https://github.com/brave/brave-browser/issues/1503

Please subscribe to that and you'll get notified when there are updates 😄
