### ISSUE TITLE
Address bar dropdown selects item under mouse position before mouse moves

### ISSUE THREAD

**Issue by nikolas** [brave/browser-laptop#15259]
### Description
When I start typing in the address bar, say, "github.com", my mouse cursor selects the option directly under it if my mouse is below the address bar, causing the "Enter" key to go to not github.com, but rather some random github page that I've been to before.

It took me a while to actually understand what's going on here, and my current workaround is just to move the mouse off the browser window before I use the address bar. This is frustrating.

### Steps to Reproduce
  1. In Brave, move your mouse cursor about 200 pixels below the address bar
  2. Type `github.com`

**Actual result:**
Notice that the third or fourth option of the address bar dropdown is selected. Pressing enter brings you here instead of github.com.

**Expected result:**
I would expect this item to not be selected until the mouse cursor moves.

**Reproduces how often:**
You can always reproduce this by following the above steps.

### Brave Version

**about:brave info:**
Brave | 0.24.0
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 4.19.0-rc5
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**
Yes

**Comment by thornjad** [comment]
I am not reproducing this on Mac Mojave, so the issue might be related to OS

**Comment by bsclifton** [comment]
Thanks for the report - I'd like to ask if you can try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser

**Comment by nikolas** [comment]
This problem is fixed in this new version (0.55.18). Thanks!
