### ISSUE TITLE
Npm start error

### ISSUE THREAD

**Issue by Th3-A6add0n** [brave/browser-laptop#15262]
So, I am new to compiling and tweaking. Followed a guide related “Chrome Extensions on Brave” Loading Chrome Extensions in Brave | Brave Browser
Got so many error but I troubleshooted all but in the end after launching the webpack developer server and entering the “npm start” command, I got a few errors. Uploaded SS

Yeah I know I can install beta version if I wanna use Chrome Extn. but as I said earlier, I am new to compiling and a bit curious, so I wanna do it.
Any help will be appreciated.
![error 1](https://user-images.githubusercontent.com/34588916/46431424-68e2fd00-c769-11e8-9c7f-080c9ef06071.png)
![error 2](https://user-images.githubusercontent.com/34588916/46431434-6e404780-c769-11e8-84d5-a218a4b0a48b.png)

**Comment by bsclifton** [comment]
@Th3-A6add0n did you run `npm install` before starting up? It looks like it can't find `electron-prebuilt` (which is Muon). That gets installed via `npm install`

**Comment by Th3-A6add0n** [comment]
Yes I did
Before that command was giving me errors as well but I troubleshooted that.

**Comment by Th3-A6add0n** [comment]
> @Th3-A6add0n did you run `npm install` before starting up? It looks like it can't find `electron-prebuilt` (which is Muon). That gets installed via `npm install`

Why did you close this issue? It's not resolved yet.

**Comment by Th3-A6add0n** [comment]
Yes
But if anyone has the same issue and that person try to search it, it won't
be shown without changing the filters.
