### ISSUE TITLE
Import bookmarks merges folders with same name

### ISSUE THREAD

**Issue by Drareg31** [brave/browser-laptop#15263]
I haven't found a similar issue, or I missed it.

### Description

Import an html bookmarks file created on Chrome. It has several folders with the same name (Shops for instance) but each under a different parent folder. Example (only folder names):
- Computing
- ____Windows
- ____Linux
- ____Shops
- Sports
- ____Surf
- ____Skiing
- ____Shops
- Moto
- ____Circuits
- ____Shops

All the URLs (and sub-folders if any) stored under each Shops folder will be imported under Computing/Shops, the first Shops folder in the imported file. Sports/Shops and Moto/Shops are not created at all.

### Steps to Reproduce

  1. Import the html bookmark file
  2.
  3.

**Actual result:**

Only one Shops folder is created under Computer with all the links from its original folder plus the ones from the 2 other folders.

**Expected result:**
Folder structure should be imported as in the html file

**Reproduces how often:**

Always

### Brave Version

**about:brave info:**

Brave | 0.24.0
-- | --
V8 | 6.9.427.23
rev | f657f15
Muon | 8.1.6
OS Release | 10.0.14393
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**

**Comment by srirambv** [comment]
@Drareg31 unfortunately bookmark issues on release build will not be fixed as we are moving to a new code base. The current muon browser will be replaced with [Brave Browser](https://github.com/brave/brave-browser/) in coming months. You can download the beta version of Brave Browser from [here](https://brave.com/download-beta). This is on Chromium UI so a lot of bookmarks related issues are fixed on this Brave-Browser-Beta. It also supports importing from your current 0.24.0 browser

**Comment by bsclifton** [comment]
Closing as `wontfix`- recommendation is to use the Beta version of the browser:
https://brave.com/download-beta
