### ISSUE TITLE
Linux Hide Menu Bar by Default not working

### ISSUE THREAD

**Issue by MikeStutzzzz** [brave/browser-laptop#15264]
### Description

When launching brave browser menu bar is not hidden. you can toggle it to hide by pressing alt key or clicking the setting but every time at launch it appears.

### Steps to Reproduce

  1.Open Brave Browser
  2.Verify Setting
  3.Re-launch and see the menu bar is still there

**Actual result:**

![image](https://user-images.githubusercontent.com/28896682/46482608-8ccf2e80-c7bb-11e8-83a6-6ffc99f10ed9.png)

![image](https://user-images.githubusercontent.com/28896682/46482684-af614780-c7bb-11e8-8289-8e4dd5863b3c.png)

**Expected result:**
Menu Bar is hidden.

**Reproduces how often:**

Every time

### Brave Version

**about:brave info:**

 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 4.15.0-36-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**

**Comment by srirambv** [comment]
This is known issue and wont be fixed as we are moving to [Brave-browser](https://github.com/brave/brave-browser). You can download the latest [beta](https://brave.com/download-beta) which is a new redesign which fixes this issue out of the box.
