### ISSUE TITLE
403 Forbidden Error for Helium's Brave Repository

### ISSUE THREAD

**Issue by wushroom** [brave/browser-laptop#15278]
### Description
Unable to install Brave on Bunsen Labs (Helium) as the repository comes back with a 403 Forbidden error

### Steps to Reproduce

  1. Fresh install Bunsen Labs Helium (https://www.bunsenlabs.org/installation.html)
  2. Open terminal
  3. input: "sudo echo"
  4. input: "curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -"
  5. input: "echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-`lsb_release -sc`.list"
  6. input: "sudo apt update"

**Actual result:**
i.imgur.com/30r4yYm.png

**Expected result:**
A successful installation of Brave

**Reproduces how often:**
100%

### Brave Version

**Reproducible on current live release:**
Yes

### Additional Information
I don't know too much about Linux or code, so please bear with me

**Comment by wokezombie** [comment]
I'm also having a similar problem installing on Kali.  I get a 403 forbidden error when I added the brave repo to the sources.list file (it did successfully pass the checks mentioned in the instructions install documentation, but as soon as i did apt-get update, I got a 403 forbidden error for the repo it was calling).  I did the manual .deb install instead, for now ... figured if I even tried apt install for brave that I would have issues if I had issues w/ that and kali ...

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
