### ISSUE TITLE
Preferences - My homepage

### ISSUE THREAD

**Issue by KrisDurski** [brave/browser-laptop#1527]
I tried to set up multiple homepages by putting two URLs separated with a semicolon into "My homepage is" on Preferences page. Restarting a browser resulted in a blank page with no menus so it was impossible to change the preferences to make the browser work again. All configuration files are binary so editing didn't work their either. Uninstalling the browser was not enough either. I had to remove the browser config by deleting the directories in C:\Users\XXX\AppData\Roaming\brave and doing a fresh installation again.

**Comment by bbondy** [comment]
The separator for multiple URLs is the pipe character `|`.
I fixed this issue though in case you put an unsupported URL as your homepage and you can't startup.  It'll be released with 0.9.3.  If you still have your old data you could restore it at that point.

**Comment by KrisDurski** [comment]
Thank you for your explanation. However, it would be a good idea to either prevent unwanted characters or check for them, or at least ignore the URLs if they cannot be understood and let the browser finish its initialization so the menu would be available as usual. BTW The URLs were valid.

**Comment by bbondy** [comment]
yes we fixed the problem as well.  The URL is invalid though because ; is not a separator character because it is valid for some schemes but not others per the RFC standard.  So the URL list that you had was all 1 URL.  We treat it better now, but you can use a | to combine multiple.
