### ISSUE TITLE
Brave browser won't run in sandbox mode on Debian 9 Stretch

### ISSUE THREAD

**Issue by markbradley1982** [brave/browser-laptop#15279]
### Description

If I try running Brave without the sandbox mode, I get the following error:

No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

Brave does indeed work with --no-sandbox mode albeit with a much less safe security mode. Also updating the kernel doesn't solve the problem. 

### Steps to Reproduce

  1. Open up Konsole
  2. Type "Brave"
  3.  That's it

**Actual result:**

No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

**Expected result:**

Actually being about to use this web browser

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 4.9.0-6-amd64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**

I'm not using the live build. I following the github installation instructions for Debian using the apt update and apt install commands. 

### Additional Information

No.

**Comment by Mikaela** [comment]
You might be interested in https://github.com/brave/browser-laptop/issues/15245 and linked issues.

However in my opinion the easiest workaround for now is `sudo sysctl kernel.unprivileged_userns_clone=1` and to make it permanent `echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf`

**Comment by bsclifton** [comment]
Thanks for the report folks - I'd like to ask if you can try grabbing the new version of Brave?
https://brave.com/download

Install instructions should be shown in the above link. If you run into problems, you can create an issue in the new repository:
https://github.com/brave/brave-browser

**Comment by Smooey** [comment]
> You might be interested in #15245 and linked issues.
> 
> However in my opinion the easiest workaround for now is `sudo sysctl kernel.unprivileged_userns_clone=1` and to make it permanent `echo kernel.unprivileged_userns_clone = 1 | sudo tee /etc/sysctl.d/00-local-userns.conf`

Have same issue, but doesn't work in Artix OS because it uses "runit" for init, not systemd ..  I have the namespace thing handled so far, but still get the "Trace/breakpoint trap" in terminal after typing "brave" and hitting enter. And Brave doesn't do nothing. So labeling this as "won't fix" doesn't help anyone get Brave running / working in various linux distros. 

Again, namespace thing alright, but now brave still doesn't load and I get "Trace/breakpoint trap" in terminal after typing "brave" to try and run brave from terminal. Clicking on Brave icon in menu doesn't do nothing either.
