### ISSUE TITLE
Bookmark Manager Not Listing Bookmarks

### ISSUE THREAD

**Issue by gloc-mike** [brave/browser-laptop#15285]
### Description

After successfully importing bookmarks from Firefox, they were all viable in the Bookmark Manager and I was actively re-arranging them, cleaning them up, creating new folders, deleting old folders etc., but at some point all of the bookmarks in the bookmark manager disappeared i.e. they were no longer visible (see screenshot attached).

<img width="1440" alt="screenshot 2018-10-10 11 34 48" src="https://user-images.githubusercontent.com/2324626/46706517-9e637b00-cc80-11e8-94d6-256c156c083a.png">

I opened up the Developer Tools pane and noticed the attached errors in the Console tab:

<img width="802" alt="screenshot 2018-10-10 11 38 36" src="https://user-images.githubusercontent.com/2324626/46706613-29447580-cc81-11e8-959d-0fbd960b5eaf.png">

[Developer Console Brave Bookmarks Manager Errors.txt](https://github.com/brave/browser-laptop/files/2462680/Developer.Console.Brave.Bookmarks.Manager.Errors.txt)

### Steps to Reproduce

I cannot reproduce this problem because I cannot get the browser back to the state that it was in when I first downloaded it and imported my bookmarks from Firefox. I have tried re-installing Brave browser but the issue remains.

I did have issues importing everything from Firefox and in the end I was only able to import bookmarks i.e. no history, cookies etc.. I think the issue about import failures has been raised before. I did have Sync enabled though which was mentioned elsewhere. And I was seeing duplicate folders possibly because Sync was enabled. It is now disabled.

**Actual result:**

No previously imported and saved bookmarks are visible/accessible in the Bookmark Manager.

**Expected result:**
Previously imported and saved bookmarks should be visible/accessible in the Bookmark Manager.

**Reproduces how often:**

Ongoing. Does not self-resolve. Does not reoccur because original state of Brave browser cannot be easily re-instated.

### Brave Version
**about:brave info:** 
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**

This is occurring in the live version. I updated Brave to the version above today (10 Oct 2018).

**Comment by bsclifton** [comment]
@gloc-mike thanks for the report- there are a few known issues with Bookmarks Manager unfortunately. For example, it's possible to put a folder inside of itself (which makes it not show anymore; likely what happened).

Can you please try our new Beta channel? We're moving towards a stable release within the upcoming week here- this will be replacing our current code-base.  You can download here:
https://brave.com/download-beta
