### ISSUE TITLE
How can i create .exe file from this code

### ISSUE THREAD

**Issue by VishalChauha** [brave/browser-laptop#15280]
i am new to react js and i want to create .exe from this code.

i have tried solutions like pkg and nexe but it seems no result.

Please help on how to create .exe file.

Thanks.

**Comment by bsclifton** [comment]
Hi @VishalChauha 

You can read more about the packaging process here:
https://github.com/brave/browser-laptop/wiki/Packaging-for-bundles,-installers,-and-updates

Please be aware that we have our own signing keys, certificates, etc which you will not have access to. You'd need to create your own resources for those steps

**Comment by VishalChauha** [comment]
@bsclifton thanks
