### ISSUE TITLE
Error when connecting to a VM SPICE remote console

### ISSUE THREAD

**Issue by BenjaDiaz** [brave/browser-laptop#15289]
### Description
SPICE is an open source solution for remote access to virtual machines. It is an alternative for VNC. It is used by my company as the default remote console for our OpenStack deployments. When I try to access any SPICE console through Brave browser I get an 'Unexpected mismatch protocol' error. I can connect using Google Chrome.

### Steps to Reproduce

  1. Create a VM with a SPICE remote console.
  2. Access the SPICE console through the browser.
  3. Get an 'Unexpected mismatch protocol' error.

**Actual result:**
'Unexpected mismatch protocol' error.
![screenshot from 2018-10-10 21-31-10](https://user-images.githubusercontent.com/19522964/46773691-f7f59500-ccd4-11e8-9a69-1184e51392c1.png)
![screenshot from 2018-10-10 21-31-58](https://user-images.githubusercontent.com/19522964/46773696-ff1ca300-ccd4-11e8-9254-e0a286e3572f.png)

**Expected result:**
Access to the console.
![screenshot from 2018-10-10 21-41-13](https://user-images.githubusercontent.com/19522964/46773730-3a1ed680-ccd5-11e8-87e2-e56b9bf9cece.png)

**Reproduces how often:**
Always.

### Brave Version

 
Brave: 0.24.0 
V8: 6.9.427.23 
rev: f657f15bf7e0e0c50a2b854c6b05edb59bfc556c 
Muon: 8.1.6 
OS Release: 4.17.13-041713-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
