### ISSUE TITLE
Part of the clickable area on the input UrlBar is not clickable

### ISSUE THREAD

**Issue by juan-cortes** [brave/browser-laptop#15292]
### Description
I've noticed this for a while but only decided to look into it further today. When clicking on the url bar, on the input, if you click on the top part of said bar it will not register the click. It will however work if the url is long enough and you do it on the right side of it.

### Steps to Reproduce

  1. Open a website
  2. Click on the url so that you get the input mode
  3. Double click on a work, using the top half part of the input

**Actual result:**
Click is not registered, text is not selected, cursor is not placed.
![oct-14-2018 15-22-33](https://user-images.githubusercontent.com/4631227/46917273-67190500-cfc5-11e8-8db3-a478cfd855e9.gif)

**Expected result:**
The click should register and allow the selection of the text or placement of the cursor.

**Reproduces how often:**
Always

### Brave Version
0.25.2 but also happens on a locally run version straight from a clone of the repo

**Reproducible on current live release:**
Yes

### Additional Information
I initially thought it might be a matter of an extra component being rendered on top of the bar, I'm still not sure it's not, but couldn't find anything enabling the devtools for the window. The bar seems to not be partially covered. The click events do not trigger as seen on the gif.

This is Mac Mojave since I understand the outer window is rendered differently in different OS

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser

**Comment by thornjad** [comment]
Fixed on the new version!
