### ISSUE TITLE
Npm start error

### ISSUE THREAD

**Issue by Th3-A6add0n** [brave/browser-laptop#15295]
**

- ### [@bsclifton Next time ask before you close an issue. It wasn't resolved.]

**

So, I am new to compiling and tweaking. Followed a guide related “Chrome Extensions on Brave” Loading Chrome Extensions in Brave | Brave Browser
Got so many error but I troubleshooted all but in the end after launching the webpack developer server and entering the “npm start” command, I got a few errors. Uploaded SS

Yeah I know I can install beta version if I wanna use Chrome Extn. but as I said earlier, I am new to compiling and a bit curious, so I wanna do it.
Any help will be appreciated.
![46431424-68e2fd00-c769-11e8-9c7f-080c9ef06071](https://user-images.githubusercontent.com/34588916/47044322-88d4e080-d1ad-11e8-9d08-67ab7b4797f2.png)
![2](https://user-images.githubusercontent.com/34588916/47044332-8d999480-d1ad-11e8-8bed-43ba2907efcf.png)

**Comment by bsclifton** [comment]
@Th3-A6add0n do you have more information about your setup? If you're on Windows, you're going to want to use either cmd.exe or Git Bash. If you're using the Linux subsystem for Windows, I'm afraid that is not something we would ever support intentionally

**Comment by Th3-A6add0n** [comment]
Don't worry
All npm install problems are solved
Now I'm just conna compile it for windows
The problems were dependencies. I was going through npm site and searched
for Linux dependencies, installed all. All good now.
I'll close this issue soon.
Thanks for support
