### ISSUE TITLE
Brave crashes when trying to close or open tabs for certain websites

### ISSUE THREAD

**Issue by sidroast** [brave/browser-laptop#15296]
### Description
When opening or closing tabs for certain websites Brave crashes.

### Steps to Reproduce

Certain examples (but not limited to):
  1. open browser, open several (5-6) tabs and go anywhere (let's say you go to github.com)
  2. open a new tab, go to mail.google.com, do stuff
  3. click the close tab X icon
  4. Brave crashes

  5. do the same as above only instead of going to mail.google.com go to news.google.com
  6. right click on any link to a news site away from google, click "open link in new tab"
  7. Brave crashes about 60-70% of the time

There are several other sites that cause the browser to crash, I simply can't remember them all.
  
**about:brave info:**
This started happening on the dev branch with Brave version 0.56.4
Happens on my: 
- debian sid laptop
- windows 10 laptop
- windows 2016 server VM

**Comment by bsclifton** [comment]
Hi there @sidroast - the repository you're looking for is https://github.com/brave/brave-browser

The issues you're referencing have been fixed with the release of 0.57.1 😄
