### ISSUE TITLE
Password manager autofill not always working

### ISSUE THREAD

**Issue by 7heViking** [brave/browser-laptop#15291]
### Description
I am testing Dashlane password manager and see some troubles when loggin in to some pages - not all. E.g. protonmail.com. The dashlane icons shows up in the log in form fields but they cannot be clicked. I sometimes saw the same issues on ther pages with the LastPass password manager.

**Expected result:**
You should be able to click the icons and auto fill should work (does not either)

**Reproduces how often:**
All the time.

### Brave Version

**about:brave info:**
Brave | 0.25.2
-- | --
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Comment by bsclifton** [comment]
Thanks for the report, @7heViking 😄 Would you be able to try Dashlane out on our newer Beta channel? We're moving towards a stable release (shooting for this upcoming week)
https://brave.com/download-beta

With the `browser-laptop` code-base (which uses Muon), there are some known issues with Dashlane. The Beta (link above) uses our new code-base `brave-core` which has much better extension support

Thanks 😄
