### ISSUE TITLE
Pop-ups blocked with no option to show

### ISSUE THREAD

**Issue by eamsden** [brave/browser-laptop#15294]
### Description
Pop-ups appear to be blocked by default in Brave, but there is no way to allow them. In my particular case, my credit card provider has online statements, but clicking the link to the PDF uses Javascript to open the PDF in a new window. This is obnoxious of course, but I can't change their site, and without an option to allow the pop-up in Brave I have to switch to Firefox to get my credit card statements.

### Steps to Reproduce

  1. Go to any site which shows information in a pop-up window
  2. Click the link to actuate the pop-up

**Actual result:**
The link does nothing

**Expected result:**
A dialog or information bar is shown asking if the pop-up should be shown

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.25.2
-- | --
V8 | 6.9.427.23
rev | 8ea2a9c
Muon | 8.1.8
OS Release | 4.15.0-34-generic
Update Channel | Release
OS Architecture | x64
OS Platform | Linux
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 69.0.3497.100

**Reproducible on current live release:**

**Comment by bsclifton** [comment]
Thanks for the report - this is fixed with our latest version of Brave 😄 
https://brave.com/download
