### ISSUE TITLE
Instalation is Incorrect/Obsolete

### ISSUE THREAD

**Issue by Nic-Wow1** [brave/browser-laptop#15298]
The [Github](http://archive.is/c1K5y) and [Wiki/brave.com](http://archive.is/4nJVE) install instructions are very diffrent. The Website appears to be obsolete and install an older version.

**Comment by bsclifton** [comment]
@Nic-Wow1 this repo is for the soon to be deprecated version of Brave, based on the Muon code-base. Today, we replaced download links on brave.com which now point at the new code-base, `brave-core`:
https://github.com/brave/brave-browser

This has been available on dev and beta channels for a while, but today is the launch of the release channel
