### ISSUE TITLE
It crashes when trying to open a pdf from email or website

### ISSUE THREAD

**Issue by tyaden** [brave/browser-laptop#15305]
## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [ ] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [ ] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Steps to Reproduce

  1.
  2.
  3.

### What version of Brave are you using?
- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here

**Comment by tyaden** [comment]
Version 0.55.20 Chromium: 70.0.3538.67 (Official Build) (64-bit)

It shows An error occurred while loading the PDF. It happens from website weareworship.com

**Comment by srirambv** [comment]
Please log an issue on https://github.com/brave/brave-browser/issues/ . This repo is for the older version of muon browser. You are running the new release version. Also please fill out the issue template while logging issue in the new repo. Lack of information will get the issue closed
