### ISSUE TITLE
Incomplete sentence in localization source

### ISSUE THREAD

**Issue by ordtrogen** [brave/browser-laptop#15306]
If you'd like to continue for this old version, please check the applicable items:
- [x] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [x] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Description

I haven't been able to find this string in the source, but this is what it looks like in Transifex. There must be a word missing, don't you agree?

![image](https://user-images.githubusercontent.com/15184875/47523701-f01f1e80-d898-11e8-8a9c-4a058fbed67d.png)

### Steps to Reproduce

  1.
  2.
  3.

### What version of Brave are you using?

- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here

NB: I'm reporting an incorrect string that I see in Transifex, so what Brave version I'm using isn't relevant, but here ya go:

Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 10.0.17134 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by bsclifton** [comment]
Thanks for the report; we don't have any updates planned for this version of Brave. I'd suggest downloading the new version from brave.com/download if you haven't already 😄
