### ISSUE TITLE
Spreadsheets on Google Drive appear distorted

### ISSUE THREAD

**Issue by nixonogoi** [brave/browser-laptop#15307]
## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [ x ] Yes I did try the new version
- [ x ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [ x ] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Description

Spreadsheets on Google Drive appear distorted

### Steps to Reproduce

  1. Go to Google Drive
  2. Open any spreadsheets that has data on it
  3. See how distorted it appears

### What version of Brave are you using?
- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here
  
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 18.0.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

<img width="1659" alt="screen shot 2018-10-26 at 01 42 41" src="https://user-images.githubusercontent.com/21003994/47546714-7bf87100-d8c0-11e8-8b75-65a9cdfc12dd.png">

**Comment by snowweb** [comment]
I use many Google sheets all day everyday and have not yet experienced this problem using Brave 0.25.2 even though many of my sheets are advanced (using query and/or script).

I'm using Windows 10 (unfortunately) but the OP is using MAC, so maybe this only affects the MAC version?

**Comment by bsclifton** [comment]
This is not something we'll be fixing as the reported version of the browser is deprecated (0.25.2). We'll be rolling an auto-upgrade out soon (finalizing that now), so I'd recommend either waiting until then or installing the new version of Brave from https://brave.com/download/
