### ISSUE TITLE
Can you add 'tara' to  which is Mint 19 codename?

### ISSUE THREAD

**Issue by leoossa** [brave/browser-laptop#15308]
https://github.com/brave/browser-laptop/blob/13808645ef50b667bb373084c238490625925388/tools/upload_to_aptly#L10
otherwise I had to change file `/etc/apt/sources.list.d/brave-browser-release-tara.list`
and replace
`deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ tara main`
to
`deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ bionic main`

Thank you.

_Originally posted by @leoossa in https://github.com/brave/browser-laptop/issues/14799#issuecomment-432912582_

**Comment by Jacalz** [comment]
This repo is at the edge of deprication, check out https://github.com/brave/brave-browser instead...
