### ISSUE TITLE
Duplicate letters when use an accented letter on mac

### ISSUE THREAD

**Issue by brunokhal** [brave/browser-laptop#1530]
On other browsers like Safari or Chrome, when you use an accented letter on mac (holding down the key), it shows the letter when you are holding the key and changes to the accented one once you choose it. On Brave, it doesn`t change and it shows both letters, like "eé" or "aà".

**Comment by luixxiul** [comment]
Could someone please reproduce this one? CC'ing @bbondy @bradleyrichter

**Comment by cezaraugusto** [comment]
@brunokhal no longer an issue with v0.11.0. Feel free to reopen if its still happening with you. Closing.

**Comment by frabrunelle** [comment]
I still get this issue with v0.11.1.

It works fine in the address bar, but not in <textarea> and <input type="text"> elements. For example, if I type "é" in the <textarea> of this GitHub comment, I get "eé" instead.

Is anyone else still having this issue?

**Comment by frabrunelle** [comment]
I still have this issue with Brave v0.11.2. Anyone else? 😄

Can someone please reopen this issue?

**Comment by cezaraugusto** [comment]
thanks for reporting, confirmed here with text and textarea fields. reopening.

**Comment by Liunkae** [comment]
As a workaround, you can use the option key shortcuts. option+e and e makes é, option+` and a makes à, option+i and i makes î, etc.

**Comment by Liunkae** [comment]
Still reproducible with Brave 0.12.3 on macOS 10.12.

**Comment by Liunkae** [comment]
Still reproducible with Brave 0.13.0 on macOS 10.12.x.

**Comment by Liunkae** [comment]
Still reproducible with Brave 0.14.0 (c23efa3, Muon 2.57.7, libchromiumcontent 57.0.2987.110) on macOS 10.12.x.

**Comment by Liunkae** [comment]
Still reproducible with Brave 0.15.0 (71fb730, Muon 2.58.7, libchromiumcontent 58.0.3029.81) on macOS 10.12.x.

**Comment by Liunkae** [comment]
Fixed for me with Brave 0.17.x.

**Comment by luixxiul** [comment]
Added the milestone for QA tests
