### ISSUE TITLE
Brave browser for CentOS 7.5 ?

### ISSUE THREAD

**Issue by fjld61** [brave/browser-laptop#15302]
I could not find Brave for CentOS 7 : where can I find it ? Thanks.

## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [ ] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [ ] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Steps to Reproduce

  1.
  2.
  3.

### What version of Brave are you using?
- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here

**Comment by srirambv** [comment]
You can find the `.rpm` file here https://github.com/brave/brave-browser/releases/tag/v0.55.18. That is the current release product for Brave. This repository is for muon browser which is deprecated now.
