### ISSUE TITLE
Bookmark manager lagging (jank)

### ISSUE THREAD

**Issue by orbanbalage** [brave/browser-laptop#15300]
### Description
Navigating the bookmark manager results in lags

### Steps to Reproduce

  1. Import Bookmarks from Chrome (there are about ~10K)
  2. Open Bookmark Manager
  3. Click between folders
  4. observe 1-2 second lag

**Actual result:**
clicking between folders has a lag, until folder is focused and content displayed
![brave-bookmark_lag](https://user-images.githubusercontent.com/285574/47210014-1113db00-d392-11e8-99bf-2aed71d5004f.gif)

**Expected result:**
clicking between folders is instant

**Reproduces how often:**
100% (not all clicking between folders is lagging, maybe every 2-3x time, but it can be reproduced always)

### Brave Version

**about:brave info:**
 
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by bsclifton** [comment]
Thanks for the report - this is fixed with our latest version of Brave 😄 
https://brave.com/download
