### ISSUE TITLE
Does not prompt for authentication for CUPS web GUI

### ISSUE THREAD

**Issue by trendsetter37** [brave/browser-laptop#15304]
### Description

Unable to administer printers with CUPS's web interface. Recent version of Brave, starting at version `Version 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)`, does not prompt for user authentication. Instead, it immediately loads an unauthorized user page. Note that this computer is running Ubuntu version 18.04.

On another laptop running Ubuntu 16.04.5 and `Version 0.25.2 Chromium: 69.0.3497.100` of Brave works as expected. 

### Steps to Reproduce

  1. Install version `0.55.18`
  2. Navigate to `localhost:631/admin`, while running the cups daemon.
  3. Click `Add Printers`

### What version of Brave are you using?
Version 0.55.18 Chromium: 70.0.3538.67 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
Since this bug is about the new version of Brave, I captured a bug in the proper repository:
https://github.com/brave/brave-browser/issues/2809

Closing this as `browser-laptop` is the older Muon version (which as reported above, works)
