### ISSUE TITLE
Enabling a own extension

### ISSUE THREAD

**Issue by akshay24495** [brave/browser-laptop#15316]
I created my own extension and I load it while start up and when i enable extension via enableExtension(extensionId) the extension background script does not get executed

**Comment by akshay24495** [comment]
@bsclifton

**Comment by bsclifton** [comment]
@akshay24495 can you please try the newer version of the browser?
https://brave.com/download

Once downloaded, you can navigate to chrome://extensions/, enable developer mode (switch in top right), and then use the `Load unpacked` button
