### ISSUE TITLE
The install encountered error 1073741845

### ISSUE THREAD

**Issue by avndp** [brave/browser-laptop#15313]
Operating System: Windows 8.1 Pro
System Specs: i3 Processor, 4GB Ram, 64 Bit Processor

While trying to install Brave browser, it is saying "Downloading...installing..." and after half completion it is saying "The install encountered error 1073741845" . The screenshot is:

![image](https://user-images.githubusercontent.com/32923858/48180686-a2032400-e34a-11e8-94de-f91eaff92c82.png)

**Comment by d0nYx** [comment]
I had the same problem when i was using the online installer. In case you haven't solved this yet and for the sake of those receiving the same error while installing brave. Just go here -> https://github.com/brave/brave-browser/releases/tag/v0.56.12 and download the offline installers ie. BraveBrowserStandaloneSetup.exe or BraveBrowserStandaloneSetup32.exe 

btw i'm posting this using the newly installed brave browser. Damn this is faster than chrome :)

**Comment by avndp** [comment]
I've tried that standalone setup already, but still getting the same error.

**Comment by nils-fl** [comment]
Same here. Is there a fix yet?

**Comment by bsclifton** [comment]
This repo is for the older version of the Brave browser. Closing in favor of https://github.com/brave/brave-browser/issues/2768

Please subscribe to this new issue and share information about your experience there
