### ISSUE TITLE
Checking for updates doesn't update to brave-core

### ISSUE THREAD

**Issue by nirholas** [brave/browser-laptop#15315]
I have downloaded Brave on a different computer and noticed the update. On my current browser I am on right now (

Brave | 0.25.2
-- | --
V8 | 6.9.427.23
Muon | 8.1.8
OS Release | 17.6.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2

and when I click 'Check for updates' nothing happens.

## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [ ] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [ ] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Steps to Reproduce

  1.
  2.
  3.

### What version of Brave are you using?
- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here

**Comment by draakevil** [comment]
Same happened to me. Was pretty annoying since Widevine stopped working in the old version. The two browser versions can even be installed in parallel.

**Comment by bsclifton** [comment]
We will have an upgrade coming soon- if you wanted to follow along, you can see the work here:
https://github.com/brave/browser-laptop/pull/15309

**Comment by nirholas** [comment]
Thank you for looking into this!
