### ISSUE TITLE
PDFs are still opened in-browser even though "Download PDF files instead of automatically opening them in Brave" is on

### ISSUE THREAD

**Issue by wetlikewater** [brave/browser-laptop#15321]
### Description
When I attempt to download any .pdf file, the file is opened by the built in brave PDF viewer even though "Download PDF files instead of automatically opening them in Brave" is turned on (Settings > Advanced Settings > Content Settings > PDF documents).

### Steps to Reproduce
1. Turn "Download PDF files instead of automatically opening them in Brave" on;
2. Close Browser
3. Reopen Browser
4. Open any link to a pdf
        ex: http://www.africau.edu/images/default/sample.pdf

### What version of Brave are you using?
Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)

**Comment by srirambv** [comment]
Please log the issue in https://github.com/brave/brave-browser/issues/. This repo is deprecated now.
