### ISSUE TITLE
unable to create wallet 

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#15325]
## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/ 
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [x] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [x] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Description
Using clean profile unable to create wallet in Brave Payments

### Steps to Reproduce

  1. Launch 0.25.2 with clean profile
  2. Go to Preferences > Payments
  3. Enable Payments
  4. Wallet does not get created, you will see this in UI:
![screen shot 2018-12-03 at 12 01 37 pm](https://user-images.githubusercontent.com/28145373/49392279-fe642400-f6fb-11e8-8ee3-57e79badfc0c.png)

And this displays in the terminal:
```
Laurens-MacBook-Pro:~ laurenwagner$ /Users/laurenwagner/BraveDocuments/Laptop/0.25.2/Brave.app/Contents/MacOS/Brave LEDGER_VERBOSE=true
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
Crash reporting enabled
2018-12-03 11:55:42.126 Brave Helper[70865:8687023] Couldn't set selectedTextBackgroundColor from default ()
properties error: Error: Ledger client initialization incomplete.
ledger client error(1): {}
Error: USD is not supported by the ledger
    at Object.callback (/Users/laurenwagner/BraveDocuments/Laptop/0.25.2/Brave.app/Contents/Resources/app.asar/node_modules/bat-client/index.js:788:31)
    at Worker.worker.onmessage (/Users/laurenwagner/BraveDocuments/Laptop/0.25.2/Brave.app/Contents/Resources/app.asar/node_modules/bat-client/index.js:1288:11)
    at App.app.on (/Users/laurenwagner/BraveDocuments/Laptop/0.25.2/Brave.app/Contents/Resources/electron.asar/browser/api/app.js:112:34)
    at emitThree (events.js:121:20)
    at App.emit (events.js:197:7)
getWalletProperties error: provider Brave Software International has invalid path field: '/v2/wallet/' + paymentId + '/balance'
getWalletProperties error: no providers available
```

### What version of Brave are you using?
 
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by mrose17** [comment]
i have tracked it down and am now reviewing the "fix" with @maikelmclauflin

**Comment by mrose17** [comment]
@LaurenWags - should be working for you. if so, please close issue!

**Comment by kjozwiak** [comment]
Working for me on `macOS 10.14 x64` 👍 Created a wallet and accepted a BAT grant using the following build:

```
Brave: 0.25.2 
V8: 6.9.427.23 
rev: 8ea2a9ce5ca329478186e6393e07f1cf87d34a22 
Muon: 8.1.8 
OS Release: 18.0.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100
```

**Comment by LaurenWags** [comment]
Confirmed works for me on macOS, thanks @mrose17 !

![screen shot 2018-12-04 at 12 31 38 pm](https://user-images.githubusercontent.com/28145373/49460950-90cdfb80-f7c0-11e8-8a95-b8e74ee1d395.png)
