### ISSUE TITLE
Cannot set Brave as default browser Arch Linux

### ISSUE THREAD

**Issue by Kallestofeles** [brave/browser-laptop#15323]
### Description
Cannot set Brave as the default browser in Arch linux. Set as default option does nothing.
System:
Kernel: 4.19.4-zen1-1-zen x86_64 bits: 64 
Desktop: Gnome 3.30.2
Distro: Arch Linux 

### Steps to Reproduce
  1. Install brave-bin or brave-dev-bin from the AUR
  2. Run the Brave browser
  3. Click on "Set as default" browser button
Rinse and repeat...

### What version of Brave are you using?
Brave Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) unknown (64-bit)

In case you need any further information regarding the matter or troubleshooting, let me know and I will happily help out.

**Comment by nickclasener** [comment]
This is a Linux issue not brave browser.
The arch wiki has all the answers you're looking for.
https://wiki.archlinux.org/index.php/GNOME#Default_applications

**Comment by Kallestofeles** [comment]
> This is a Linux issue not brave browser.
> The arch wiki has all the answers you're looking for.
> https://wiki.archlinux.org/index.php/GNOME#Default_applications

Incorrect. When opening up Firefox - using the set as default option in-browser sets it as default for the whole system (deals with all the mimetypes correctly), same goes for Chromium - only Brave kind of does it and kind of don't. The mimetypes seem to be registered and yes, links open in Brave, however the message pops up in the browser every time that the Brave is not the default browser.
Thanks for the wiki link, however I have already set the default applications for gnome and Brave is already set as the default browser - hence this issue was opened.

**Comment by Liunkae** [comment]
Moved to a new issue (for the new Brave repository): brave/brave-browser#2377

By the way, this repository is for the old Brave version. Please see brave/brave-browser for the new version.

**Comment by bsclifton** [comment]
Closing as we won't fix this in the old Muon version of Brave. Locking conversation too- let's take the convo over to https://github.com/brave/brave-browser/issues/2377
