### ISSUE TITLE
playing amazon or netflix video

### ISSUE THREAD

**Issue by VLT2ZADOK** [brave/browser-laptop#1532]
How can I enable video playing in Amazon and netflix?

**Comment by bradleyrichter** [comment]
We understand many users are using sites that require Flash which we aren't supporting due to the impact of malware delivered through Flash-Ads.

We are working on a solution to only allow the video players in the near future.

**Comment by Trumpy** [comment]
So put pressure on those companies to use html5?

**Comment by luixxiul** [comment]
ref: #468

**Comment by luixxiul** [comment]
This is being worked on with #1093, duping to #386. Thanks anyway.
