### ISSUE TITLE
disable websql

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#15337]
as a quick fix for https://blade.tencent.com/magellan/index_en.html, since we are not planning on doing more chromium updates to this deprecated repo

**Comment by LaurenWags** [comment]
macOS - 0.25.2 before fix:
![screen shot 2018-12-20 at 1 04 53 pm](https://user-images.githubusercontent.com/28145373/50302443-21ab0500-0458-11e9-8e91-5da6cf8e27f8.png)

macOS - 0.25.304 after fix:
![screen shot 2018-12-20 at 1 06 10 pm](https://user-images.githubusercontent.com/28145373/50302459-2a9bd680-0458-11e9-8d52-70718579c560.png)

**Comment by kjozwiak** [comment]
`Windows 10 x64` Results:

Before Fix:

![before](https://user-images.githubusercontent.com/2602313/50307973-edd7db80-0467-11e9-8e38-76e06cb49d6f.png)

After Fix:

![after](https://user-images.githubusercontent.com/2602313/50307978-f3352600-0467-11e9-87ac-0dfd0b171988.png)
