### ISSUE TITLE
Screwed Kongregate and Playfab

### ISSUE THREAD

**Issue by Vitae666** [brave/browser-laptop#15330]
Installed this new version of Brave and for some reason my Kongregate games are all screwed up. The console shows Playfab Account logged in: False
I went to Chrome, loaded a game, exported the save file, opened Brave, imported the file and it loaded up. Closed Brave, reopened it, and it was as if I did nothing. Console said it couldn't find either the offline or the online (which it can't because Playfab is screwed)

**Comment by bsclifton** [comment]
@Vitae666 I have a feeling this problem you're having is with the new version of Brave (this repo is for the older deprecated version).  Can you try turning shields off for that domain? Click the lion icon in the top right, turn off. It'll save that only for the site you're visiting. That should do the trick

If that doesn't work, let's file a report in the new repo:
https://github.com/brave/brave-browser
