### ISSUE TITLE
remember mute/play state of tabs when restarting browser

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1533]
currently, with all tabs muted, restarting brave will auto-play these tabs. (toggle their mute state)

Instead, each tab should come back in the mute state it was last left in before closing the browser.

**Comment by bbondy** [comment]
maybe unloaded tabs is a better solution for this? I'm afraid some people will think it's a bug because sound isn't playing anymore in their youtube tab.

**Comment by bradleyrichter** [comment]
ok, let me change the title to match the behavior of FX and Chrome

**Comment by bbondy** [comment]
This is mostly solved now with unloaded tabs. So de-prioritizing for now.
