### ISSUE TITLE
Return statement exiting early from usage ping call

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#15331]
The return statement at https://github.com/brave/browser-laptop/blob/master/app/updater.js#L254 is potentially causing the usage ping to not fire when the referral code confirmation happens.

This requires further investigation, but may be as simple as removing the return statement.

**Comment by bsclifton** [comment]
@aekeus I don't think we have any more updates planned? Is this something we need fixed? If so, it's going to be complex
