### ISSUE TITLE
Website can track between normal and private mode

### ISSUE THREAD

**Issue by VMBindraban** [brave/browser-laptop#15335]
### Description

Normal mode shares data with private mode that is accessible by websites (and thus tracking)

### Steps to Reproduce

  1. Go to https://www.nothingprivate.ml/
  2. Fill in random name
  3. Open https://www.nothingprivate.ml/ in private window
  4. It knows what your name is.

### What version of Brave are you using?

Version 0.57.18 Chromium: 71.0.3578.80 (Official Build) (64-bit)
(minor note, `about:brave` doesn't work anymore. see issue template)

**Comment by srirambv** [comment]
Please open the issue on https://github.com/brave/brave-browser/issues. This repo is depricated
