### ISSUE TITLE
Windows 7 - Brave (64) v71.0.57.18 - Fails to Install and Start - Blank Screen Only

### ISSUE THREAD

**Issue by MaxEntropyy** [brave/browser-laptop#15333]
Hi Devs,

I am technical. I have a relatively 'clean machine' running Windows 7. 

I downloaded and installed Brave (64) v71.0.57.18... with Administrator Permissions and after dismissing the installer dialog that says successfully installed. Brave Browser is launched... but I see only a Brave Browser 'window' that is BLANK. - there are 'brave tasks' running.
- the Brave Browser never recovers... the window stays blank forever.

I use Brave on all Windows and iOS devices... and have never seen this problem before.

Any ideas?

Max

**Comment by mlninparadise** [comment]
Similar here just now W7 64bit + admin permission got error code xxxxxxxdd - Kaspersky Antivirus flags Trojan.Win32.Generic. I guessed false flag and disabled AV made new install without admin permit and worked fine again.

**Comment by bsclifton** [comment]
Hi folks - this repo is for the OLDER Electron/Muon based version of the product

However, there is an issue tracking this in the the NEW repo, which you can subscribe to:
https://github.com/brave/brave-browser/issues/2087

Thanks! 😄
