### ISSUE TITLE
"No updates" message has negative sentiment

### ISSUE THREAD

**Issue by tagawa** [brave/browser-laptop#15347]
## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [X] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [X] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Description
Using the latest version of software is a good thing, so users should feel reassured - no need to apologise IMO.

### Steps to Reproduce

  1. Go to the "Brave" menu
  2. Click "Check for updates"
  3. Wait for message to appear in the message bar.

### What version of Brave are you using?
- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here
 
Brave: 0.25.304 
V8: 6.9.427.23 
rev: 3ecf3237e16598a70e9063ba66513f617d97603f 
Muon: 8.1.8 
OS Release: 18.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 69.0.3497.100

**Comment by petemill** [comment]
@tagawa I'm afraid you're most definitely not in fact on the latest version 😢. Your version is 0.25.304 and the latest release version is version 0.61.x.

You can download it from brave.com

The good news is that I don't believe this issue is present in the latest version.

**Comment by tagawa** [comment]
@petemill Thanks for the quick reply. Good to hear about the issue no longer being an issue.

Strange that I don't have the latest version as I went to brave.com/download before reporting, to make sure, and I also get the "no updates" message when I check in-browser. Maybe I need to be on the nightly or beta channels, so I'll try that instead.

<img width="596" alt="Screenshot 2019-04-02 at 10 15 27" src="https://user-images.githubusercontent.com/94173/55369146-d7b8cd00-54e4-11e9-944e-fb47ecbb8477.png">

**Comment by bsclifton** [comment]
@tagawa you likely have two versions of the product on your computer - we could have definitely done a better job with this upgrade experience

The version 0.25 you're using is our older Electron-fork based product. The one on brave.com is a a fork of Chromium. You can import all of your data and many of your settings from the new version

If you're using Spotlight to get to it, you can type `Brave Browser` instead and open that. You'll notice it looks a bit different. After you get your settings updated, you can remove the older `Brave.app` version. Let us know if you need any help 😄

**Comment by tagawa** [comment]
@bsclifton Oh, you're right - I do have two versions. Funny, I was looking forward to the big Chromium update and was then confused that it looked so similar to the previous versions! 🤦‍♂️ 
Thanks for the explanation. My other machine is the same (saying 0.25 is the latest) so I'll check that one too.
