### ISSUE TITLE
% search in tabs

### ISSUE THREAD

**Issue by raisty** [brave/browser-laptop#15343]
## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [x] Yes I did try the new version
- [ ] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [x] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Description

We should be able search also between opened tabs with:
```
%tabname...
```

### Steps to Reproduce

  1. Write in url input %
  2. Write after name of tab, which you have open
  3. On click/enter tab will open

### What version of Brave are you using?
- Using Brave, navigate to `about:brave`
- Under "Version information", you'll see the version (ex: 0.25.2)
- Click the clipboard icon to copy the product details and paste here

LOL
```
The web page at chrome://brave/ might be temporarily down or it may have moved permanently to a new web address.
```
chrome://settings/help
Anyway: Version 0.58.17 Chromium: 71.0.3578.98 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@raisty this repo is for the OLD version of Brave; there's a new repository for tracking issues in the live version of Brave:
https://github.com/brave/brave-browser

@raisty I created an issue on your behalf (in the new repo). Would you mind checking it out and making sure I got the details right? Thanks 😄 
https://github.com/brave/brave-browser/issues/2765
