### ISSUE TITLE
Reddit videos and spotify web player don't play when shields are up

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#15345]
## Troubleshooting checklist
There's a good chance the bug you're about to report is fixed in the new version of Brave
- Download latest version of Brave from https://brave.com/download/
- Import your data by navigating to brave://settings/importData

If you'd like to continue for this old version, please check the applicable items:
- [x] Yes I did try the new version
- [x] I believe this issue is critical for users (security issue, bug that prevents folks from using the software)
- [x] I've read the `FAQs and Common Issues` section on community.brave.com (https://community.brave.com/c/common-issues)

### Description

I can't get reddit videos and spotify web player to play. I installed Windvine and yes, I can login into spotify now, but it doesn't play the songs - they get stuck at 00:00. The same happens on reddit, because the videos won't play at all.

But if I put the shields down, all of these work. 

![image](https://user-images.githubusercontent.com/46224887/50520372-159df380-0aa7-11e9-8277-0408e3a878d2.png)

### Steps to Reproduce

  1. Go to https://www.reddit.com/r/nonononoyes/comments/9i5myc/i_think_i_can_i_think_i_can/ and try to play the video with shields up
  2. See that it won't play and disable shields
  3. See that the videos play
  4. Go to https://open.spotify.com/track/4YsFuYyDwfDrUl6bSL6g8H and try to play the song with sheidls up
  5. See that it won't play and disable shields
  6. See that the song plays now

### What version of Brave are you using?

Versão 0.58.18 Chromium: 71.0.3578.98 (Versão oficial) 64 bits

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/brave-browser/issues/1999
