### ISSUE TITLE
Brave Password manager should support kde-wallet on linux

### ISSUE THREAD

**Issue by belldandu** [brave/browser-laptop#1536]
I turned off brave's password manager because brave wasn't prompting to save a password.

It still doesn't prompt to save a password. I have kde wallet installed. I'm using arch linux rolling release.

There are NO errors. Brave just simply never prompts if i want to save a password.

**Comment by belldandu** [comment]
im not using gnome im using kde? and im pretty sure you don't install it by default. why use a gnome password storage service if its only going to conflict with kde's password storage service.

if braves pw manager is turned off it should at least default to whatever password manager is already on linux like chrome does.

**Comment by belldandu** [comment]
Anyone taken a look into this https://www.npmjs.com/package/unipassman

**Comment by diracdeltas** [comment]
I recommend bringing this up at the upstream repo that we use for keychain integration: https://github.com/atom/node-keytar
