### ISSUE TITLE
Create Ukrainian localization

### ISSUE THREAD

**Issue by stenox** [brave/browser-laptop#1538]
I'd like to make Ukrainian language available.

**Comment by bbondy** [comment]
You can request access here:
transifex.com/organization/brave

If you're contributing it cannot be any machine translations though. Thanks!

**Comment by stenox** [comment]
OK, I already have an access there :) Is that official localization resource?
It would be good to get the reviewer permissions there.

At the moment Ukrainian is fully translated on transifex. When it can be included into the application?

**Comment by bbondy** [comment]
@aekeus pls help and close this after, thx!

**Comment by aekeus** [comment]
Hi @stenox. Just gave you access on Transifex. The languages will be released in an upcoming update.
Thanks
