### ISSUE TITLE
Manual tests for 0.9.3 for OS X

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#1539]
## About pages

1. [x] Test that about:bookmarks loads bookmarks
2. [x] Test that about:downloads loads downloads
3. [x] Test that about:preferences changing a preference takes effect right away
4. [x] Test that about:preferences language change takes effect on re-start

## Site hacks

1. [x] Test twitch.tv sub-page loads a video and you can play it

## Downloads

1. [x] Test downloading a file works and that all actions on the download item works.

## Zoom

1. [X] Test OSX zoom keys
3. [X] Test Zoom saved for site

## Bookmarks

1. [x] Test that creating a bookmark on the bookmarks toolbar works
2. [x] Test that creating a bookmark folder on the bookmarks toolbar works
3. [ ] Test that moving a bookmark into a folder by drag and drop on the bookmarks folder works

## FAIL - Bookmarks Menu UI Artifact

<img width="1293" alt="screen shot 2016-05-03 at 10 58 01 am" src="https://cloud.githubusercontent.com/assets/210240/14987577/20297a98-111e-11e6-8d65-21d9016bd699.png">

## Session storage

1. [x] Temporarily move away your ~/Library/Application\ Support/Brave/session-store-1 and test that clean session storage works.
2. [X] Make sure that data from the last version appears in the new version OK.

## Bravery settings

1. [X] Check that HTTPS Everywhere works by loading http://apple.com
2. [X] Check that ad replacement works on http://slashdot.org
3. [X] Check that toggling to blocking and allow ads works as expected.

## Per release specialty tests

1. [ ] Test each item in release notes for the release that's going out.

## Content tests

1. [X] Load twitter and click on a tweet so the popup div shows.   Click to dismiss and repeat with another div. Make sure it shows.
2. [X] Go to brianbondy.com and click on the twitter icon on the top right. Test that context menus work in the new twitter tab.
3. [X] Go to http://www.bennish.net/web-notifications.html and test that clicking on 'Show' pops up a notification asking for permission. Make sure that clicking 'Deny' leads to no notifications being shown.
4. [ ] Go to https://trac.torproject.org/projects/tor/login and make sure that the password can be saved. Make sure the saved password shows up in `about:passwords`.

## about:passwords failed to load
**#4 - FAILED Refused to execute inline script because it violates the following Content Security Policy directive: "script-src**

## Update tests

1. [ ] Test that updating on Windows 32-bit works before sending the update up by using BRAVE_UPDATE_VERSION
2. [ ] Test that updating on Windows 64-bit works before sending the update up by using BRAVE_UPDATE_VERSION
3. [ ] Test that updating on OS X works before sending the update up by using BRAVE_UPDATE_VERSION
4. [ ] Test that Ubuntu .deb installs and updates
5. [ ] Test that Fedora .rpm installs and updates

# Security

1. [ ] Test that clicking through a cert error in badssl.com works.
2. [ ] Test that Safe Browsing works (excellentmovies.net)

**Comment by bbondy** [comment]
CC @bsclifton the 100% width and height is causing this.

**Comment by bbondy** [comment]
@bsclifton turns out there was a second change added by @bridiver. I think each of your changes was fine on their own, but combined it had this problem.  I'm removing @bridiver 's popupWindow style to fix it.

**Comment by aekeus** [comment]
Closing this. Moving on to RC2 checklist. https://github.com/brave/browser-laptop/issues/1541

**Comment by bsclifton** [comment]
Cool thanks :smile: The fix I had tried was to make the CSS less restrictive:
```
// This is a reasonable max height and also solves problems for bookmarks menu
// and bookmarks overflow menu reaching down too low.
width: 100%;
@usedUpChrome: @navbarHeight + @bookmarksToolbarWithFaviconsHeight;
min-height: calc(~'100% - @{usedUpChrome}');
max-height: calc(~'100% - @{usedUpChrome}');
overflow-y: auto;
```

I had trouble testing this and the fix by @bbondy works for now
