### ISSUE TITLE
Still runs in background after closing

### ISSUE THREAD

**Issue by WildPhil** [brave/browser-laptop#1540]
According to Task Manager, there are 4 Brave 'background processes' still running after closing the Brave brower.  I can go to Task Manager then close these via 'end task'.  These should close automatically (or at least give me an option under 'preferences' to have all Brave processes close/end after exiting browser).

I also noticed these Brave background processes cause errors with my homepage after reopening the Brave browser.  My homepage doesn't start when opening Brave (just a blank tab) and any new tab is also blank.  Refresing, closing an existing tab, and opening a new one, exiting Brave and relaunching, etc. all fail to start homepage on opening Brave.

This error can be fixed manually by going to Task Manager and closing the 4 Brave background processes still running.

Using: Brave 0.9.2,  Windows 10 Build 14332, Laptop Computer

**Comment by Haze-Aulaian** [comment]
have seen that while trying to update the browser too

**Comment by larfadin** [comment]
Same thing on ubuntu, there are still background processes after closing Brave

**Comment by msp1111111** [comment]
Same, 0.9.4, Win 7 pro desktop 64bit

**Comment by luixxiul** [comment]
CC @bbondy confirmed.
