### ISSUE TITLE
about:certerror button text overflows on hover

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1545]
![screen shot 2016-05-03 at 11 21 35 am](https://cloud.githubusercontent.com/assets/549654/14993771/4cdfa1b8-1121-11e6-9546-c4be54d3cc9c.png)

**Comment by diracdeltas** [comment]
@lewiscowper or @bnvk, could you take a look at this?

**Comment by luixxiul** [comment]
Adding ``height: 100%;`` under https://github.com/brave/browser-laptop/blob/master/less/button.less#L71 and https://github.com/brave/browser-laptop/blob/master/less/button.less#L83 would solve the bug, but you have to make sure it won't affect other buttons.

**Comment by bbondy** [comment]
Thanks @luixxiul  I tried that fix but it can lead t uneven button heights for both buttons.  I just did a diff fix though, will push now.

**Comment by diracdeltas** [comment]
thanks @luixxiul @bbondy !

**Comment by luixxiul** [comment]
Later I'll try to find a better solution.

**Comment by bbondy** [comment]
it's fixed already.

**Comment by luixxiul** [comment]
OK, I see
