### ISSUE TITLE
Brave ia32 won't run after installation

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1559]
Hello Dev,

so i wanted to try Brave ia32.
it said it requires .net4.5 , so i installed it.
installed brave , it said it will launch after installation but nothing happened.
when i try to run the program it gives the exe in the task manager for brief moment and then it disappears.

OS : windows 7 32bit (no service pack)
Brave version : the latest 32bit version on the official site.

![brave32bit](https://cloud.githubusercontent.com/assets/17910355/15025116/691b5ed8-1240-11e6-96c1-17b5de62dec7.png)

**Comment by bbondy** [comment]
not sure why it isn't showing up, interested to see if anyone else gets this. 
I ran through these tests on ia32 before the release:
https://github.com/brave/browser-laptop/issues/1555

Are you missing any service packs maybe?

**Comment by Haze-Aulaian** [comment]
like i mentioned i dont have a service pack installed its the base release of win 7 32 bit
to add also i just restarted my laptop, that didnt fix it.
if the service pack is required can you please make sure to put that in the minimum requirements of the installation or even to check for it before installation like it asked me to install.net4.5 ?

**Comment by Haze-Aulaian** [comment]
2016-05-04 21:28:26> Program: Starting Squirrel Updater: --updateSelf=C:\Users\Taqq\AppData\Local\SquirrelTemp\Update.exe
2016-05-04 21:28:26> Program: About to wait for parent PID 4564

**Comment by Haze-Aulaian** [comment]
[SquirrelSetup.txt](https://github.com/brave/browser-laptop/files/249399/SquirrelSetup.txt)

**Comment by HxNguye** [comment]
Same thing happened with 64 bit version for me, I'm quite stumped since it did not give any errors for me to look at.

**Comment by edwin4321** [comment]
Yes happened to me as well on 64 bit version, i have tried the compatibility troubleshooter and no joy.

**Comment by Haze-Aulaian** [comment]
@bbondy i think this is condition specific rather than OS specific. is there any way that you can give us a release with debugging enabled so we can provide you with further logs.

**Comment by SJ-Diamond** [comment]
Same problem with one of my Windows 7 installations. Was able to install Brave without problems, but browser was not able to start. Here on Windows 8 all runs fine.

**Comment by bbondy** [comment]
@bridiver maybe related to https://github.com/brave/browser-laptop/issues/1571#issuecomment-217135383 ?

**Comment by bbondy** [comment]
Does both %appdata%\Brave and %appdata%\..\local\brave exist?

**Comment by SJ-Diamond** [comment]
Interesting. Installed now the previous version which was able to run. Then the recent version over it and it works. If i do install the newest version without any userprofile existing it fails to run.

**Comment by Haze-Aulaian** [comment]
@bbondy i will check it when i go back home but i think @SJ-Diamond is making sense here as it could be problem with setting up directories ? but as far as i remember i had a local folder.

**Comment by bbondy** [comment]
I can repro if I clear out my dirs, we'll upgrade to electron 0.37.8 and then do anther release asap.

**Comment by Haze-Aulaian** [comment]
@bbondy i have checked but i didnt find a brave folder under appdata , only found it under "C:\Users\User\AppData\Local\Brave\app-0.9.3" so is there a missing directory here ?

**Comment by bbondy** [comment]
yep thanks for checking, so we're trying to get a fix out today for this (0.9.4)

**Comment by Haze-Aulaian** [comment]
you are most welcomed

**Comment by Haze-Aulaian** [comment]
can't wait to ditch firefox on my 32bit laptop

**Comment by Haze-Aulaian** [comment]
i confirm that this is resolved


![32bit](https://cloud.githubusercontent.com/assets/17910355/15084093/ec7180b0-13d9-11e6-8cef-7e5fb748b082.PNG)
