### ISSUE TITLE
set app user model ID on Windows for taskbar pinning / grouping

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#156]
The installer generated with Squirrel will create a shortcut icon with an Application User Model ID in the format of com.squirrel.PACKAGE_ID.YOUR_EXE_WITHOUT_DOT_EXE, examples are com.squirrel.slack.Slack and com.squirrel.code.Code. You have to use the same ID for your app with app.setAppUserModelId API, otherwise Windows will not be able to pin your app properly in task bar.

**Comment by luixxiul** [comment]
Isn't this bug critical?

**Comment by bbondy** [comment]
not critical but I thin it can lead to 2 taskbar icons.

**Comment by luixxiul** [comment]
So this might be related with https://github.com/brave/browser-laptop/issues/1779#issue-155007713?

**Comment by bbondy** [comment]
no related to if you have a taskbar icon, and then click that taskbar icon. And a second brave icon appears on the taskbar.

**Comment by bbondy** [comment]
CC @bsclifton this sounds like something you might like to take.

**Comment by bsclifton** [comment]
Was this already fixed?
https://github.com/brave/browser-laptop/commit/d98f76391f78ddce63fe2dd643525d54e6acaf6a#diff-98f0ed24f8f0fed04b7949391f32909e

**Comment by bbondy** [comment]
I was assuming it could lead to 2 taskbar icons because maybe the exact format mentioned in the first comment wasn't followed (uppercase /lower somewhere maybe or something? )

**Comment by bsclifton** [comment]
@bbondy after reading more in https://github.com/electron/electron/issues/1954, I think you're exactly right. Basically, it could break the already pinned Brave icon when the auto-updater runs and installs a new version.  I have seen this happen before; the old pinned icon turns into a blank document looking icon and then I need to use the desktop shortcut and re-pin the executable

**Comment by luixxiul** [comment]
Does this close #1778?

**Comment by bbondy** [comment]
yep I think so
