### ISSUE TITLE
pinned tab is incorrectly selected after closing 2nd tab of 2-tab window

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1562]
STR

open a new window 
make sure it has pinned tabs
use first normal tab
make a new tab
use the new tab (ie: google search)
close that tab with command+W

result: right-most pinned tab becomes selected instead of first tab to the left

this happens regardless of which tab was last selected before tab closure

expected: last active tab should be selected after closing newer tab

**Comment by cezaraugusto** [comment]
@bradleyrichter I think it's already fixed. Does it still happening to you?

**Comment by bradleyrichter** [comment]
@cezaraugusto  

still happens on current master branch

**Comment by bradleyrichter** [comment]
Maybe it's now a mac-only issue?

**Comment by bsclifton** [comment]
I had made a fix recently which should prevent this:
https://github.com/brave/browser-laptop/issues/2333

Self assigning- I can dig into this tonite

**Comment by bsclifton** [comment]
I believe this was fixed w/ https://github.com/brave/browser-laptop/pull/2923

I tried the steps above with the current master branch (trying the steps in my initial window, in a new window, and all kinds of variations). I'm unable to reproduce
