### ISSUE TITLE
pinned tabs should be ignored in tab-closure sequence using control+W

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1563]
current behavior works like chrome and is fine for pinned tabs that only exist in one window at a time.

The prefered behavior should mimic Safari on Mac which also has pinned tabs on every browser window. Those pins are ignored so they are not cycled when closing the window with Command+W.

**Comment by luixxiul** [comment]
kinda related? #1127

**Comment by cezaraugusto** [comment]
IIUC if user has only pinned tabs hitting <kbd>command</kbd> + <kbd>W</kbd> should close the window instead of the current pinned tab? If so, I think it's fixed already.

**Comment by bradleyrichter** [comment]
If you have 1 pinned tab and 1 other (normal) tab, viewing the normal tab and hitting command + W  should close the window. 

Currently it closes the tab and takes you to the single pinned tab.

**Comment by NHDaly** [comment]
Hi, is fixing this issue basically just this?:
https://github.com/brave/browser-laptop/pull/12963

Of course I haven't done any tests yet, but is this the basic gist of it?

**Comment by NHDaly** [comment]
---- Oh, actually, after looking at it more, I think maybe this would prevent closing a pinned tab from the file menu as well... i don't think that's what we want, is it? Perhaps there's a way to see how the `menuItem` was invoked (ie via an `accelerator` or through clicking)?

**Comment by bsclifton** [comment]
[brave-core](https://github.com/brave/brave-browser) only pins tabs to first window and is closable with cmd+W
