### ISSUE TITLE
Brave for Windows crashes when opening link from Google notifications

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-laptop#1568]
Brave v0.9.3
Windows 7 64-bit

1. Sign in with Google account
2. Open Google notifications (the bell icon on top right)
3. Click on any link, Brave immediately crashes

**Comment by bsclifton** [comment]
I was able to reproduce w/ 0.9.4 on Windows 10, 64-bit

**Comment by onmyouji** [comment]
Seems it's already fixed with 0.9.5, at least on Windows 7. Not sure about Windows 10. 

Paging @bsclifton so that I can close this.

**Comment by bsclifton** [comment]
@onmyouji confirmed on Windows 10 w/ 0.9.5- this looks good! :+1:

**Comment by onmyouji** [comment]
Can you provide the links that cause crash? I want to test it from Windows 7.

Thanks.

**Comment by luixxiul** [comment]
I can't confirm this as there is (or has been) no notifications :frowning: 

CC: @bbondy
