### ISSUE TITLE
Crash on startup after building package?

### ISSUE THREAD

**Issue by prkeshri** [brave/browser-laptop#1569]
After I have executed the command npm run build-package, it created a folder named 'Brave-linux-x64'.
Now, when I try to run ./Brave inside the Brave-linux-x64 folder. The app starts and crashes with the error Segmentation fault (core dumped).

After I started debugging with gdb, what I got is this message:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff0b1d9c8 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

After I ran backtrace:
#0  0x00007ffff0b1d9c8 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000003389b9a in atom::api::Extension::Load(v8::Isolate*, base::FilePath const&, extensions::Manifest::Location const&, int) ()
#2  0x000000000338b1fa in _ZN4base8internal7InvokerINS_13IndexSequenceIJEEENS0_9BindStateINS0_15RunnableAdapterIPFN4mate10DictionaryEPN2v87IsolateERKNS_8FilePathERKN10extensions8Manifest8LocationEiEEESJ_JEEENS0_12InvokeHelperILb0ES7_SL_EEFS7_RKSA_SD_SI_RKiEE3RunEPNS0_13BindStateBaseESQ_SD_SI_SS_ ()
#3  0x000000000338abe3 in mate::internal::Dispatcher<mate::Dictionary (v8::Isolate*, base::FilePath const&, extensions::Manifest::Location const&, int)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) ()
#4  0x00007ffff70ab001 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
   from /data/brave/working/browser-laptop/Brave-linux-x64/libnode.so
#5  0x00007ffff70dc08a in ?? ()

**Comment by bbondy** [comment]
It looks like the folder mentioned at the bottom of that script isn't getting copied maybe?

```
if (isLinux) {
  cmds.push('mv Brave-linux-x64/Brave Brave-linux-x64/brave')
  cmds.push('ncp ./app/extensions ' + path.join(buildDir, 'resources', 'extensions'))
}
```

The crash shows it can't load the extension that goes there.

**Comment by prkeshri** [comment]
The issue is still there. BTW, electron-packager makes executables that start (atleast). There are problems though after startup. One such is here:
[https://github.com/brave/browser-laptop/issues/286]

**Comment by prkeshri** [comment]
@bbondy . Please help me in this issue: [https://github.com/brave/browser-laptop/issues/269]. I have pasted my problems there.

**Comment by bbondy** [comment]
Let me know if the directory gets copied or not mentioned here, thanks! 
https://github.com/brave/browser-laptop/issues/1569#issuecomment-217134627

**Comment by prkeshri** [comment]
It was always getting copied. It's being copied now too. But the problem persists!

**Comment by bbondy** [comment]
CC'ing @bridiver who might have some ideas.

**Comment by bridiver** [comment]
could have something to do with the brave extension manifest change. I was just thinking about it over the weekend and it occurred to me that it might be a problem in the dist

**Comment by bridiver** [comment]
this should be fixed by https://github.com/brave/browser-laptop/commit/43c06960971c8c5bc6a3efc8fddba56a018174b1
