### ISSUE TITLE
Show secure icon in a better placement for title mode

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#157]

**Comment by bbondy** [comment]
@bradleyrichter please weigh in here.  Should we just glue to the left of the centered title in title mode?

**Comment by bradleyrichter** [comment]
I'll find another solution for the lock icon as I would prefer not to go left aligned. The centered title is important for the friendly simple appearance of this dual-view which harks back to the original title bar before tabs robbed us of legible titles. :   )

**Comment by bbondy** [comment]
"before tabs robbed us of legible title" - brilliant observation to me, in hindsight it's so true!

Thanks please post the design change for the security indication here, we'd love to get this in for security sensitive early adopters.

**Comment by bradleyrichter** [comment]
Placing the lock/unlock icon to the left of the title seems like a reasonable solution. Opacity can be 50% of icon color. @diracdeltas I'm not thrilled with having an unlocked icon on all instances that are not secure. As soon as you move the mouse in the area of the URL bar, you will see the icon regardless. Can we start by showing the lock icon when locked and nothing when unlocked?

**Comment by bradleyrichter** [comment]
![screen shot 2016-02-02 at 11 00 44 am](https://cloud.githubusercontent.com/assets/13509546/12761602/788895b8-c9a0-11e5-809c-0d913efa8518.png)

**Comment by diracdeltas** [comment]
left of title sounds good to me. i'm all for showing nothing when insecure for now.

**Comment by bradleyrichter** [comment]
great!

**Comment by diracdeltas** [comment]
I got the lock icon next to the title but got stuck on figuring out a way to center the title and lock icon. https://github.com/brave/browser-laptop/commit/2a2c6cd924ec4f5ebafd977900659543060a6767

any ideas?

**Comment by bbondy** [comment]
Yes I think we need to hide the url bar and instead put a div with the same class which contains the title+icon centered when in title mode.
