### ISSUE TITLE
0.9.3 does not start on Linux if ~/.config/brave is missing

### ISSUE THREAD

**Issue by totycro** [brave/browser-laptop#1570]
I just downloaded `Brave-Linux-x64.tar.bz2 ` from [here](https://github.com/brave/browser-laptop/releases/tag/v0.9.3dev). After unpacking and running `./brave`, it exits with an exit code of 0 after about half a second with no other visible action.

I noticed via `strace` that it tries to access `~/.config/brave`, which did not exist at the time. After creating that directory, brave works.

**Comment by Haze-Aulaian** [comment]
@bbondy i think this is duplicate to our issues in #1571 and #1559

**Comment by bbondy** [comment]
0.9.4 is live and this is fixed.
https://github.com/brave/browser-laptop/commit/04ade02073f1bfa7867cc862d8dd5be7131ec211
