### ISSUE TITLE
Brave does not start at all

### ISSUE THREAD

**Issue by jiri-bati-novak** [brave/browser-laptop#1571]
Downloaded latest linux build in .rpm format (openSUSE, as I am running Leap), package installed fine, but browser does not start, does not wite anything to console, nothing, exit(0)...
Same with raw binary release...
If there is any debug switch, or logffile to help in getting this isssue fixed, I am willing to help...

**Comment by bbondy** [comment]
Try creating a ~/.config/brave directry it seems like if it's msising it's not working.

**Comment by jiri-bati-novak** [comment]
well, did not suspect anything like this.. but creating the ~/.config/brave indeed helped :)

**Comment by bbondy** [comment]
ya I'm not sure why this started happening but maybe it was an upstream Electron requirement.  Upgrading to 0.37.8 might help CC @bridiver

**Comment by bbondy** [comment]
This is the fix I think will fix it in 0.37.8
https://github.com/electron/electron/commit/66853344c0fdf1c8bcea50bd58a95e4a94b63575

**Comment by bbondy** [comment]
0.9.4 is live and this is fixed.
https://github.com/brave/browser-laptop/commit/04ade02073f1bfa7867cc862d8dd5be7131ec211
