### ISSUE TITLE
Crash on "Allow Notifications"

### ISSUE THREAD

**Issue by happyjaxx** [brave/browser-laptop#1572]
Brave 0.9.3 (Windows 10 64b)

Hi, thanks you for adding the "Remember this" checkbox on the Allow Notifications bar.

Though: Hitting the Allow button crashes the browser (not always at first, but the second time at best)
Is there any log somewhere I could paste ?

**Comment by diracdeltas** [comment]
cc @aekeus re: logs. I've also run into this crash.

**Comment by bbondy** [comment]
Crash report for this, or a stack trace in your Brave user data directory would be helpful

**Comment by happyjaxx** [comment]
Sorry, very long weekend here.
Well, I'm not a Windows person (besides for some specific tools and running AoE2HD at times) but lurking around my users AppData\Roaming\brave folder didn't turn up any stacktrace. (And Windows Logs, besides the mess, doesn't seem to neither)
Should I be looking elsewhere ? Do I need to launch Brave with a specific option ?
Thanks

**Comment by luixxiul** [comment]
Does this still persist?

**Comment by happyjaxx** [comment]
After the last update, it still happened (I give it a shot after each update).
That said, without paying attention, it also accepted a new "allowance+remember" once this morning (not home, on battery, without a secondary screen, which are unusual conditions, but it would be very odd if it was due to those).
Waiting for the next occurrence to see if it persists
But again, how do I trigger a stacktrace log of crashes in general ?

**Comment by luixxiul** [comment]
You can find ``SquirrelSetup.log`` in ``C:\Users\[Your Username Here]\AppData\Local\Brave``.

**Comment by happyjaxx** [comment]
Well ! It seems it went away !
SquirrelSetup.log only contains references to packages downloads and file updates,  the only stacktrace is related to a 404 on an update attempt.
I don't recall when this behavior changed (+ I got used to clicking "deny"), maybe after an update on the 14th... I'll try to see if anything in the changelog pops up... Closing this in the meanwhile.
Regards
