### ISSUE TITLE
Look into using Electron's context-menu event

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1573]
Currently we run code in the frame to get the context menu info, but it looks like Electron exposed an event now:
https://github.com/electron/electron/pull/5379

**Comment by cezaraugusto** [comment]
Wasn't it implemented by https://github.com/brave/browser-laptop/commit/f6f1bc8#diff-b95013a7d2996f174fdafb3bb3cfd7cbR338?

**Comment by bbondy** [comment]
yep i's fixed now, thx for finding.
