### ISSUE TITLE
Zoom page bug

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1575]
Hello Dev team,

so i noticed today that after you change the zoon settings to smaller 2 things will happen.

1- if you scroll to decrease the font size the browser will decrease it twice smaller and i have to scroll back one step to increase the font properly.
2- if you refresh the page the zoom setting that you have specified is reset.

OS : Windows 7 64 bit service pack 1.
Brave : 0.9.3

This is easily reproducible , let me know if you would like me to do that.

regards,
Haze

**Comment by bridiver** [comment]
I can't replicate this in master. It's probably fixed by https://github.com/brave/browser-laptop/commit/656746a45564e08f7a7ad08bce974ac688186502. Please report back if you still see this problem after the 0.10 release. Thanks!
