### ISSUE TITLE
'Block all HTTP' mode

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1576]
HTTPS Everywhere has a global 'Block all HTTP' mode where no HTTP requests are allowed. It was pretty well-received and easy to add so we should add it

**Comment by luixxiul** [comment]
Let's set up "Block all trackings/images" mode too. cf. https://github.com/brave/browser-laptop/commit/4c30cd08af9dda75a0e3d6ef634abbbdc2a39c74

**Comment by luixxiul** [comment]
Definitely I'd like to see this implemented near in the future. Sites like http://weather.goo.ne.jp/ and http://map.goo.ne.jp/ accept ONLY plain http requests, and tons of beacons track your navigations there :astonished:

**Comment by diracdeltas** [comment]
Setting a milestone in light of recent attention on https://www.theguardian.com/technology/2017/mar/28/privacy-protection-sell-web-browsing-history-data in the US

**Comment by Liunkae** [comment]
Related: #7559 (make http links more obvious to highlight their insecurity)

**Comment by bsclifton** [comment]
Tentatively moving this to 0.14.3 but please feel free to pull back if you have a fix ready 😄

**Comment by diracdeltas** [comment]
@evq working on this

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/779
