### ISSUE TITLE
Brave 0.9.3 doesn't start on windows 8.1

### ISSUE THREAD

**Issue by chicagobuss** [brave/browser-laptop#1577]
Tried x64 installer, said it was installing then would start brave, looks like it launched then immediately closed.  No %appdata&\brave directory was ever created.

Tried installing 0.9.2 and that worked fine.

**Comment by Haze-Aulaian** [comment]
please check #1559 for details

**Comment by bbondy** [comment]
0.9.4 is live and this is fixed.
https://github.com/brave/browser-laptop/commit/04ade02073f1bfa7867cc862d8dd5be7131ec211

**Comment by chicagobuss** [comment]
That was fast, wow.  Confirmed working - thanks!
