### ISSUE TITLE
add ESC key to escape from FS view on Mac OS

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1578]

**Comment by bbondy** [comment]
I'm not sold on this idea. It seems like Safari does it but both Firefox and Chrome do not do it.

There are 2 types fo full screen, when you press full screen on an HTML element, like a video, in which case ESC does exit it already.

The other is just full screen mode of the browser, and all browser elements remain visible.  Escape is a commonly used shortcut for doing things like closing UI elements like find in page, but mainly for stopping a page from loading.   Which users often hit multiple times in a row.  I think if a user is in this mode they might accidentally and annoyingly exit it.

**Comment by bradleyrichter** [comment]
as long as it's working for YT, let's close it. I suspect some people are complaining more about how OS X has changed how FS view works than anything we are doing wrong.
