### ISSUE TITLE
navigator.registerProtocolHandler doesn't do anything

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#1583]
cf., https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-registerprotocolhandler

needed for things like the [Bitcoin URI](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki)

thanks!

/mtr

**Comment by diracdeltas** [comment]
could you explain in more detail what is needed? are you saying that any site should be able to register itself as a bitcoin handler, or just whitelisted sites, or just the background page context?

window.navigator.registerProtocolHandler is implemented already but presumably only works for same-origin registrations. i am against allowing it in general for security reasons.

**Comment by mrose17** [comment]
thanks. i don't think it works in the browset at the moment...

if you go to one of the bitcoin sites, and click on the button to setup the site to handle bitcoin payments, e.g., https://www.coinbase.com/settings/preferences (for coinbase) folks, then it's a no-op on the brave browser. 

if i do the same thing in either chrome or firefox, i get a dialog asking for permission and if i click accept, then the protocol handler is registered with that browser.

with the brave browser, i don't get either the dialog nor does is the handler registered...

**Comment by diracdeltas** [comment]
The dialog is a chrome-specific feature, so not surprising that it doesn't appear. `window.navigator.registerProtocolHandler('bitcoin', 'https://www.coinbase.com/handler?u=%s', 'coinbase')` in Brave doesn't throw any errors but it also doesn't seem to work. seems like an electron bug.

**Comment by mrose17** [comment]
i believe that chrome, firefox, and opera all support it... otherwise, i agree that it does seem like an electron issue... either that, or we aren't hooking into electron properly in terms of a callback/option enabling the feature.

**Comment by aekeus** [comment]
@diracdeltas can we confirm this is an Electron issue?

**Comment by bbondy** [comment]
I have this working but need it to persist on session restart and need to test with packaged builds and work out some other corner cases.

Attached backup WIP electron patch.

[out.patch.zip](https://github.com/brave/browser-laptop/files/353327/out.patch.zip)

**Comment by bbondy** [comment]
Implemented here:
https://github.com/brave/browser-laptop/commit/5d6584e8bfaf855457d38c9e748734fc74a8e750
https://github.com/brave/electron/commit/7d126de2bb71b73ba815c2af92761e40a655a07f

Still need to fix a crash with command+click and shift+click though.  Otherwise good to go.
Settings persist and register with OS as default as well.
