### ISSUE TITLE
NoScript usability follow-ups

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1586]
- [ ] Ability to clear once permanently accepted? Perhaps while on the page or an about page whatever is easier / better.
- [ ] Show in titlebar mode and on sites where scripts are allowed

**Comment by bbondy** [comment]
#2 on that list is more urgent to me.

**Comment by diracdeltas** [comment]
@bbondy i'm assuming you know it can be turned on/off in the Bravery menu? (like the other Bravery settings right now)

**Comment by bbondy** [comment]
Oh somehow I missed the menu item. When I was trying it out I actually changed the app config JS.  I'd be fine with dropping #2 even for now given that.

**Comment by luixxiul** [comment]
I'd like to see the notification icon displayed always.

**Comment by bbondy** [comment]
@luixxiul if there's a bug with it not sometimes showing up when enabled please post that as a new bug

**Comment by luixxiul** [comment]
Not a bug. I meant "always" as "even if not :hover on the URL bar".

**Comment by diracdeltas** [comment]
> Why don't we have an icon which also tells that scripts are allowed on that page/tab/session and is clickable to switch "deny" to "allow"?

that is what i'm working on

**Comment by diracdeltas** [comment]
i'll also add the icon to titlebar mode

**Comment by diracdeltas** [comment]
Now that https://github.com/brave/browser-laptop/pull/1810 has landed, I think it makes sense for the noscript siteInfo popup to be merged with the Bravery panel rather than be a separate panel with overlapping functionality. Perhaps as a 'Script Blocking' section of the panel that only appears when 'Block scripts' is on for the page. Closing this and opening a new issue.
