### ISSUE TITLE
renderer process crashes when navigating if dev tools are open

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1588]
Steps to reproduce:
1. Open http://slashdot.org
2. Open Dev Tools
3. Click on any link
Tab goes black and renderer process dies

**Comment by bbondy** [comment]
@bridiver pls take, possibly try upgrading to 0.37.8 first in case that just fixes it.

**Comment by fieder** [comment]
This ticket should be open again. I've experienced the same behaviour in the latest version for Mac.

1. Open https://havefunhub.com
2. Open dev tools
3. Click on About us link (top left corner drop down list)

This is what happens. Then it remains broken till I close and re open the browser.

<img width="1573" alt="screen shot 2016-05-10 at 15 19 15" src="https://cloud.githubusercontent.com/assets/1662253/15149736/99c1ceb0-16c2-11e6-9a70-69889d52212a.png">


> Brave: 0.9.4
> Electron: 0.37.7
> libchromiumcontent: 50.0.2661.94
> V8: 5.0.71.39
> Node.js: 5.10.0
> Update channel: dev
> 
> This software uses libraries from the FFmpeg project under the LGPLv2.1

**Comment by bridiver** [comment]
The fix is in our fork of Electron which is currently at 0.37.8 and I don't think that browser-laptop has been updated to use it yet. I tested havefunhub and everything works fine with electron master.

**Comment by fieder** [comment]
Thanks for the update. I'll wait for the release then. Kudos for the speed on the browser! I really like it.

**Comment by kenorb** [comment]
Similar regarding the black screen, but without DevTools: #1366.
