### ISSUE TITLE
Y position of context menu subitems is wrong when overflowed

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1589]
## Test plan
1. Launch Brave and minimize your browser window as far as possible
2. Click the kabob menu
3. Scroll the menu with your mouse and keyboard to ~1/3 from the bottom
4. Select "Bookmark" submenu
5. Items should line up. It should NOT look like this (image courtesy of @luixxiul):
![submenu](https://cloud.githubusercontent.com/assets/3362943/22851771/9af7161e-f06f-11e6-9cdd-20ac6f392125.gif)

## Original issue description
Hello Dev team,

today i saw the following bug happening on the bookmark toolbar menu.
When i open a submenu it will appear way up , you can see that in the following screen shot:

OS : windows 7 64bit SP1
Brave : 0.9.3

![bookmarkissue](https://cloud.githubusercontent.com/assets/17910355/15066065/af933870-136e-11e6-9f5d-318c3419ed93.png)

**Comment by Haze-Aulaian** [comment]
Just to add , this does not happen on all existing submenus , it will happen in a random amount , some of them may work correctly but the others no.

**Comment by luixxiul** [comment]
Still reproducible?

**Comment by Haze-Aulaian** [comment]
@luixxiul yep still reproducible , just updated to 0.10.0 64 bit

![system-template](https://cloud.githubusercontent.com/assets/17910355/15453422/1177a2ea-201e-11e6-97d6-b825e8aff0bf.png)

**Comment by luixxiul** [comment]
I'm trying but cannot reproduce it.. Would you please tell me how many bookmarks are in the pulldown?

**Comment by Haze-Aulaian** [comment]
@luixxiul i have in that folder 191 items , 29 of them are folders and they are in the middle way of the folder.
i have imported these bookmarks from firefox so maybe you can do it that way.

**Comment by Haze-Aulaian** [comment]
@luixxiul i can give you a remote access to my machine incase you want to see it for yourself , let me know if thats required.

**Comment by luixxiul** [comment]
I'll try by myself and will ask you if I need it, thanks.

**Comment by Haze-Aulaian** [comment]
@luixxiul sure

**Comment by luixxiul** [comment]
I think I can reproduce the error consistently.

STR:
1)  Minimize your browser window as far as possible
2)  Click the kabob menu
3)  Scroll the menu with your mouse and keyboard to ~1/3 from the bottom
5)  Select "Bookmark" submenu

![submenu](https://cloud.githubusercontent.com/assets/3362943/22851771/9af7161e-f06f-11e6-9cdd-20ac6f392125.gif)

@bsclifton what do you think?

**Comment by bsclifton** [comment]
@luixxiul looks like great repro steps 👍
