### ISSUE TITLE
Allowing to show the notifications for a website quits the browser

### ISSUE THREAD

**Issue by vesvis** [brave/browser-laptop#1591]
Another thing is when I restart after the browser fails, I got the tabs from long time ago instead of the tabs before fails.

**Comment by diracdeltas** [comment]
First bug is probably a duplicate of fhttps://github.com/brave/browser-laptop/issues/1572

**Comment by bsclifton** [comment]
Since it looks like this is a dupe, closing it out (please re-open if I misread or the issue happens again)
