### ISSUE TITLE
Right clicking back/forward nav buttons should bring up the history menu

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#1594]
Would be an essential feature if you could click with the right mouse buttonon the forward/backward buttons to be more easier able to switch between already visited pages in one tab.

**edit by @bsclifton**
Here's an example of the menu that should show when right clicking the nav buttons:
![screen shot 2016-11-16 at 12 01 40 am](https://cloud.githubusercontent.com/assets/4733304/20337716/074f0dd2-ab90-11e6-9350-2760178a7ce0.png)

**Comment by alexwykoff** [comment]
Shipped

**Comment by bsclifton** [comment]
@alexwykoff do we have this feature? We do have a long press button which shows the nav items, but it isn't triggered on right click

**Comment by bsclifton** [comment]
Updated the title to be descriptive, removed the milestone, and added a pic :smile: This would be a great one to have!
