### ISSUE TITLE
regression: site settings no longer shown in about:preferences

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1595]
possibly due to the siteSettings/tempSiteSettings changes from yesterday

**Comment by diracdeltas** [comment]
Can't seem to repro this anymore

**Comment by bbondy** [comment]
Possibly related to the chrome extension URLs change that was breaking dev content pages. It was backed out and then fixed and re-added.  I'll close this for now but re-open if you see it again please. Thanks.
