### ISSUE TITLE
Autocomplete URL in the URL bar

### ISSUE THREAD

**Issue by erossonero** [brave/browser-laptop#1596]
Not sure if someone has already posted/asked for these feature requests, but here are some features I'd love to see in Brave.

1. Auto complete of a search. (see screenshot)
    * When starting to type, it should automatically complete the url with the most popular url that starts with that character/string. And when I hit Enter, it should go to that link. Say I only enter "br" it should take me to Brave.com. I didn't know I used this feature a lot on other browsers until I wasn't able to do it on Brave.

![autocomplete](https://cloud.githubusercontent.com/assets/16802489/15084128/85d03854-139f-11e6-9216-9bd33b563d92.png)

2. Icons on bookmarks. Individual links and folders.
    * Individual links would grab it from that specific link
    * Folders should have an option to pick different icons, say Shopping/Sports/Work/etc.

3. Auto complete of a domain
    * ![](http://i.imgur.com/CxpDpAp.jpg)
    * Pushing right arrow here should complete the domain to continue like ``facebook.com/SomePage``

**Comment by luixxiul** [comment]
ref: #241

**Comment by bbondy** [comment]
Re 1: you can press down arrow and select an item and press enter to load but I'd also really like for the url to autocomplete in the urlbar.  Added to 0.10.1dev for now.

Re icons on bookmarks, you can enable this in preferences but the folder aspect isn't covered yet.

**Comment by bbondy** [comment]
Please move the folder request into a different issue, morphing this one to URL bar only.

**Comment by bbondy** [comment]
In addition to better handling the matching in the URL bar.  We should always show the URL as well as domain. Since we only show page title, it could make phishing scams easier. CC @diracdeltas

**Comment by bbondy** [comment]
Showing the URL in entries is posted in a follow up here:
https://github.com/brave/browser-laptop/issues/2210
