### ISSUE TITLE
Feature request : Drag tab onto bookmarks toolbar

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1597]
Hello Dev team,

i would like to request if possible to add a feature where i will be able to drag any active tab to the bookmark tool instead of using the Cntrl+D .

Regards,
Haze

**Comment by bbondy** [comment]
this might conflict with plans we have for detaching a window when you drag the tab outside of the tab bar.  Note you can currently drag the favicon to create a bookmark from the urlbar.

**Comment by Haze-Aulaian** [comment]
@bbondy tried it , didn't work with 0.9.4 and just now discovered 3 new bugs , one in the toolbar , one in what happens after you launch back the browser and one when i exit the browser :(

**Comment by bbondy** [comment]
which OS are you on? I just dragged and it created a bookmark from the urlbar.
For the other issues, you didn't say what they were but probably best to post them as separate issues. Thanks.

**Comment by Haze-Aulaian** [comment]
i did post the first one , and yes the fav icon from the url bar , i was confused thinking you meant the favicon of the tab . sorry about that

**Comment by luixxiul** [comment]
> Note you can currently drag the favicon to create a bookmark from the urlbar.

I see only the lock icon, or am I seeing something wrong, @bbondy?

**Comment by bbondy** [comment]
I meant the lock icon, we don't show the favicon in the url bar.  I think adding the ability to drag a tab's favicon would work here though.  And then leave the tab itself for the future feature of detach tab into new window.

**Comment by luixxiul** [comment]
I'm going to close the issue in favor of https://github.com/brave/browser-laptop/issues/5193.
