### ISSUE TITLE
Process not closing leading to state not saving

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1598]
Hello Dev team,

After i created 3 bookmarked sites , i quit the browser and then i reopened it again and it shows blank bookmark toolbar and nothing in the bookmark manager.

OS : windows 32bit (no SP)
Brave : 0.9.4

Even the bookmark manager says that i dont have any bookmarks.

![bookmarkbug](https://cloud.githubusercontent.com/assets/17910355/15084716/0bae4c3e-13de-11e6-924f-922f808f9346.PNG)
![bookmarkbug2](https://cloud.githubusercontent.com/assets/17910355/15084719/0ff8b93c-13de-11e6-9ce1-00f6f3ef4036.PNG)
![bookmarkbug3](https://cloud.githubusercontent.com/assets/17910355/15084726/186c3bac-13de-11e6-9ddf-4d03b13454ed.PNG)

**Comment by luixxiul** [comment]
How about with the latest version?

**Comment by Haze-Aulaian** [comment]
still the same , so i have created few bookmarks and decieded to close the browser , there is the issue of the exe remaining in the background after closing brave.
so i found out that if brave doesn't close properly the bookmarks created in the new session will be erased as below:

(this is from brave 0.9.6 /// win 7 32bit (no sp) )

![bravetoolbar](https://cloud.githubusercontent.com/assets/17910355/15275942/0affd4f0-1ae2-11e6-839f-ddf81786704c.PNG)

after i end brave from Task manager , the newly created bookmarks are removed as below:

![bravetoolbar2](https://cloud.githubusercontent.com/assets/17910355/15275955/4b3912ac-1ae2-11e6-8571-a7c2f226dac3.PNG)

i hope this helps.

**Comment by Haze-Aulaian** [comment]
and to add , it restores back the tabs from the terminated exe.

**Comment by luixxiul** [comment]
It seems to me that #1540 is not enough to fix the issue :-( CC'ing @bbondy

**Comment by bbondy** [comment]
Should be fixed by https://github.com/brave/browser-laptop/pull/1934 and some changes in electron
