### ISSUE TITLE
Bug report: If a tab crashes and it gets reloaded it gets stuck

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#1599]
When a tab crashes, either during browsing or if i kill it in the Windows task manager and reload it afterwards, the tab is frozen.

Can't scroll, can't click, reload does not change anything.

Can only be solved by closing the tab and opening last closed tab again.

System is Windows 8.1, 64 Bit

**Comment by luixxiul** [comment]
Do you remember which page you opened? I will reproduce it

**Comment by cezaraugusto** [comment]
Is it still an issue? Can't reproduce it now.

**Comment by bbondy** [comment]
I think this is fixed, please re-open if it's still a problem.
