### ISSUE TITLE
Opening page in _blank tab makes main window to go to /undefined

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1602]
Reproduction steps:

1. Go to: https://brave.com/#safer
1. Open one of GitHub links in the new tab (OS X: CMD-Click), e.g. https://github.com/brave/browser-laptop

Result: The link is open, but the main tab is redirected to: https://brave.com/undefined (which is unexpected).

This doesn't happen on other websites, so I'm not sure if it's a website issue, or the browser it-self.

**Comment by luixxiul** [comment]
Confirmed, still persists on 0.9.6. CC'ing @bbondy @bradleyrichter

**Comment by kenorb** [comment]
This happens also on Chrome, so probably it's a website issue?

**Comment by bridiver** [comment]
definitely a website issue

**Comment by luixxiul** [comment]
I'm not sure this is a website issue. Maybe not.

STR on Ubuntu 14.10

1. Enable "Block HTML canvas and WebGL fingerprinting"
2. Visit https://www.philosophyguides.org
3. Open Devtool
3. Click "About"

![](https://cloud.githubusercontent.com/assets/3362943/15472878/35b45750-2138-11e6-9731-f3dd6d4b0e1f.jpg)

If you disable it and try again, you don't get the error. I assume this is related with blocking HTML canvas elements.

cc: @diracdeltas

**Comment by diracdeltas** [comment]
@luixxiul That is ~expected behavior for sites that use canvas reads when canvas fp block is enabled.
