### ISSUE TITLE
Black page after DevTools was disconnected from the page.

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1603]
Reproducible steps:

1. Go to any page, e.g. www.brave.com
1. Open DevTools (or inspect any element), and switch to _Network_ tab.
1. Reload the page (OS X: CMD-R)

Reasult:

Website becomes black, icon shows it's loading endlessly and Developer Tools shows the following message:

> DevTools was disconnected from the page.

> Once page is reloaded, DevTools will automatically reconnect.

Refreshing page again does the same thing.

Could be related: #1053

**Comment by luixxiul** [comment]
Same here on Windows 10.

**Comment by diracdeltas** [comment]
I've noticed this too on recent OS X versions

**Comment by diracdeltas** [comment]
Closing as dupe of #1588
