### ISSUE TITLE
Opening mailto link in new tab does nothing.

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1604]
Reproducible steps:

1. Go to: about:preferences.
1. Open 'Send us feedback...' in a new tab (by holding CMD on OS X or Control on Windows).

The same happening when opening from menu _Brave -> Send us Feedback..._

Result:

New blank page with `mailto:support+laptop@brave.com` in the URL bar.

Expected behavior:

I'm not sure what would be the expected behavior. Probably opening the mail client as well.

**Comment by luixxiul** [comment]
Ref: #1768

**Comment by bbondy** [comment]
This works for me but my mailto handler is chrome.  I think this bug just needs to be re-labeled to handle mailto: links better?

**Comment by bridiver** [comment]
I'm also not able to replicate and the mailto link opens mail.app for me. Not sure exactly what fixed it, but if the problem persists for you in 0.10 please let us know. Thanks!
