### ISSUE TITLE
Load page timer doesn't stop on popup

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1607]
When I open some page with file, browser asks me to save the file.

The time of page load (in the address bar) seems to include the total time including selecting the folder by the user to save the file.

So when I'll be selecting the folder to save the file for few minutes, the load time would show few minutes.

I think the load time should be the actual time of page load, unless opening the files should be treated with no time.

**Comment by cezaraugusto** [comment]
Still valid running v1.11.1.

Steps to reproduce:

1. Go to https://www.mozilla.org/en-US/firefox/new/?scene=2
2. Notice the load time blinks (for me it was 0.27s)
3. Keep the download dialog open for a while (i.e. 30s)
4. Close the dialog
5. Notice the load time

**Comment by luixxiul** [comment]
I cannot reproduce the issue. It might have been fixed already. Let's close for now 👍
