### ISSUE TITLE
Dashlane Not Working......

### ISSUE THREAD

**Issue by Banditz71** [brave/browser-laptop#1608]
Dashlane does not appear to work......and their tech support says they don't support Brave.  Anyone else having issues with it?

**Comment by jimfr** [comment]
doesn't work at all for me either on Windows 10.  I reinstalled the Dashlane app, but still no love...

**Comment by bbondy** [comment]
Try this and let me know please, thanks!
https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-use-dashlane

**Comment by jimfr** [comment]
Thanks Brian,
  I tried that.  I do get a Dashlane entry in the right-click menu, but it
does nothing.

jim

On Sun, May 8, 2016 at 7:34 AM, Brian R. Bondy <notifications@github.com>
wrote:

> Try this and let me know please, thanks!
>
> https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-use-dashlane
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/1608#issuecomment-217723415>
>



-- 
-------------------------------------
gSent

**Comment by Banditz71** [comment]
Same here.......

**Comment by bbondy** [comment]
And you disabled the signature check in the second part f the FAQ too right?

**Comment by jimfr** [comment]
​Yes, but I hadn't yet quit both Dashlane and Brave.  I just did and now it
works.

Thanks!  I'll post to github.

Jim​

On Sun, May 8, 2016 at 7:38 AM, Brian R. Bondy <notifications@github.com>
wrote:

> And you disabled the signature check in the second part f the FAQ too
> right?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/1608#issuecomment-217723704>
>



-- 
-------------------------------------
gSent

**Comment by Banditz71** [comment]
Well, I hadn't.......I did so but still nothing.....the only thing that happened was I lost all my previously open tabs (20 or so).....not sure what sense that makes.  So, in the Dashlane prefs, you're talking about the Security tab.....then down at the bottom uncheck Verify Browser Code Sig.?

**Comment by jimfr** [comment]
Banditz, yes, that's what I did, and, after a restart of both apps, now Dashlane works great.

**Comment by Banditz71** [comment]
Hmmmmmm.......I restarted both.....guess I'll try again.  Did you lose any tabs in the process?

**Comment by jimfr** [comment]
I don't restart with tabs from last time, just with a blank tab page and my
5 pinned tabs, all of which came back.

On Sun, May 8, 2016 at 8:09 AM, Richard <notifications@github.com> wrote:

> Hmmmmmm.......I restarted both.....guess I'll try again. Did you lose any
> tabs in the process?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/1608#issuecomment-217725789>
>



-- 
-------------------------------------
gSent

**Comment by Banditz71** [comment]
OH, OK......yeah, my pinned tabs were just fine.......thanks!

**Comment by Banditz71** [comment]
OK......after having rebooted my computer, all seems to be working as advertised.......plus, all my tabs are back (very strange).  I really really hope support for Roboform is in the very new future.
