### ISSUE TITLE
Failed to load resource at chrome-extension://...

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1609]
Reproducible steps:

1. Open: https://www.youtube.com/
1. Open Toggle Browser Console.

Result:

The following error is shown in console:

> Failed to load resource: net::ERR_ADDRESS_UNREACHABLE: chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/img/favicon.ico

This doesn't happen in other browsers (Chrome or Firefox).

**Comment by luixxiul** [comment]
related #1459

**Comment by kenorb** [comment]
I can't reproduce the problem after the upgrade.

Now chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/img/favicon.ico image loads correctly.
