### ISSUE TITLE
Implement error pages

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1611]
When going to page which can't be reached, I see a blank page.

Example URL: http://localhost:1234/ or http://foobar/

Chrome shows the error:

> This site can’t be reached. localhost refused to connect. ERR_CONNECTION_REFUSED

Brave shows empty page.

I'd be expecting some error pages with the details why the page doesn't load.

**Comment by bridiver** [comment]
related https://github.com/brave/browser-laptop/pull/1194

**Comment by islapete** [comment]
Here is what is happening for me.  If I load Brave and go to www.yahoo.com I see the entire page load and then turn black.  Brave is still running.  If I try and load another page like www.facebook.com the page loads but freezes.  Even trying to load www.brave.com the page loads and freezes.  If I don't load www.yahoo.com all is well.

**Comment by bridiver** [comment]
@islapete ok, that's definitely a different problem then so let's keep it in the other ticket

**Comment by kenorb** [comment]
@islapete Your issue sounds like #1366.

**Comment by luixxiul** [comment]
Also related with #1459
