### ISSUE TITLE
FTP address opens WWW page

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1612]
In Chrome/Firefox default behavior when entering `ftp.kernel.org` address is to connect to FTP server, Brave ignores that and redirects to the main homepage instead (`www.kernel.org`).

**Comment by diracdeltas** [comment]
The chrome/FF behavior seems bizarre. Entering `ftp.kernel.org` in the URL bar should resolve to `http://ftp.kernel.org`, which indeed redirects to the kernel homepage.

**Comment by luixxiul** [comment]
related #1459

**Comment by cezaraugusto** [comment]
@diracdeltas `wontfix`?

**Comment by diracdeltas** [comment]
sure, we can leave this open for reference but mark wontfix for now
