### ISSUE TITLE
Tab preview on hover should change the URL as well

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1613]
When hovering on different tabs the page changes, but not URL which is a bit confusing. It's like you're seeing different page, but the URL in the bar is incorrect. I think both page and its URL should match when displaying preview.

**Comment by luixxiul** [comment]
Yes I thought it's confusing too.

Do you have any idea, @bbondy?

**Comment by bbondy** [comment]
CC @bradleyrichter for design thoughts on this

**Comment by bradleyrichter** [comment]
I think that would be a nice improvement. We may even want the preview to show the title instead of the URL?

**Comment by bbondy** [comment]
I'm just wondering about at some point the mind thinks you actually switched tabs and you aren't previewing.  Then people might post a bug about why are you switching tabs on preview.

**Comment by luixxiul** [comment]
> Then people might post a bug about why are you switching tabs on preview.

Definitely.

**Comment by Liunkae** [comment]
Related issue: #2844

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tab-preview-on-hover-should-change-the-url/10451

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
