### ISSUE TITLE
file:/// doesn't browse the local files

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1615]
In Chrome/Firefox when going to `file:///`, it shows list of local files. Brave shows a blank page.

**Comment by luixxiul** [comment]
related #1459

**Comment by Liunkae** [comment]
+1 from #6389 (file:// browsing should show directory content)

**Comment by Liunkae** [comment]
+1 from #8704.

**Comment by dandv** [comment]
I can open a file via Ctrl+O, but can't browse to it's directory :-/

**Comment by bsclifton** [comment]
I verified this is fixed with [brave-core](https://github.com/brave/brave-browser) 😄 We won't be fixing this in our current product (browser-laptop/Muon)
