### ISSUE TITLE
source page becomes unresponsive when using control+click to open a link in a new tab

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1619]
for whatever reason, this does not happen on every page. Just pages with a form element like the one on this page:

http://www.dwr.com/search.do?query=bertoi

additionally, Command+R is ignored in this state

![image](https://cloud.githubusercontent.com/assets/13509546/15093180/73ed3f16-1434-11e6-8a2a-6d27e4752471.png)

**Comment by cezaraugusto** [comment]
Tried to reproduce here but I think they removed this form.

**Comment by luixxiul** [comment]
Closing as stale.
