### ISSUE TITLE
Memory usage / Hang issue

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1620]
Hello Dev team,

so i have 13 tabs opened and using the browser as im using other browsers.
in the task manager i see 14 process in total of ~600 MB of memory usage.
i try to navigate between tabs and when i click on a tab it take 2-3 seconds to open the tab,
trying to scroll in the page the browser won't respond for another 2-3 seconds.
is this expected and is this part of the behavior in brave when not using other tabs for long time ?

/Haze

**Comment by cezaraugusto** [comment]
Hi @Haze-Aulaian, thanks for reporting. 

Which OS and Brave version are you using?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/consumption-of-ram-in-windows-10/1306/6

If you are still around here and see another issue discussed above, would you please open a topic there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
