### ISSUE TITLE
Proposed design for Bravery panel, and per-site settings

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1621]
**Overview:**
As we complete the plumbing for maintaining per-site settings for various blocking and cookie attributes, users need a quick-access UI to control one or more of these attributes IF the need arrises for a particular site. 

Some users may want to white-list sites for various reasons. This may include allowing one site to display normal ads and another to allow popups or 3rd party cookies if these settings are required for the purpose of browsing that site. 

Occasionally a site may refuse to load because of our agressive blocking defaults.

Brave refers to these settings as "shields".

**Plan**
Quick access to per-site shields will be available through a panel that opens via the Bravery button in the navigation bar. This panel defaults to a collapsed view, and offers an easy-switch to bring all site shields UP or DOWN with one simple switch. This allows a user to quickly fix a site that may not be loading or doesn't appear as they expected. (a double-click on the Bravery button will serve as an advanced short-cut to the shields toggle switch for the current site.)

When the user needs more granular control over a particular setting, the advanced controls can be displayed. (the viewable state is remembered so they are visible again next time the panel is opened)

![image](https://cloud.githubusercontent.com/assets/13509546/15115269/0bf9bb48-15b3-11e6-80f3-89bfb69f86cf.png)

The display area shows a readout for the currently blocked ad count and tracker count for the current page, and provides access to more detail through a secondary popup list which is toggled by clicking on the number.

![image](https://cloud.githubusercontent.com/assets/13509546/15093417/f4e4c416-143b-11e6-888f-245abe33166a.png)

If shields are down, no information is displayed in this area:
![image](https://cloud.githubusercontent.com/assets/13509546/15115317/45a897b0-15b3-11e6-9eda-fff5273618e9.png)

Also shown in the above image, the bravery button changes it's color state to represent the state of Shields for that site. 

Functionally, when shields are "down", all settings are reduced to thier minimum or off states until the shields are brought back "up". (also - this on/off state is site-wide and not just per page)

A decision to make related to this is whether these settings should simply be disabled (but viewable) while shields are down, or if they should be editable which would then create a new baseline for the site's shields settings as soon as one setting is changed from its off-state.

(the first iteration will use the disabled approach:)
![image](https://cloud.githubusercontent.com/assets/13509546/15115368/7ef373c8-15b3-11e6-8b62-92cd4cdabb01.png)

Other V1 differences are listed and shown here:
- the site icon will start by using the site favicon in it's largest available size, but 16x will be acceptable
- time-saved will require more work and will come later
- global shield setting overrides will not be available yet so the link to Prefs will be hidden

![image](https://cloud.githubusercontent.com/assets/13509546/15093480/63266964-143e-11e6-8d70-d7684ae56049.png)

Community feedback is encouraged as always!

We know that many advanced users have requested per-element/per-site blocking control. We will not have this initially but will evaluate the necessity as we move forward.

Also, not shown in this UI are future exception lists that will be accessed through the settings/prefs panels.

**Comment by SJ-Diamond** [comment]
Looks nice, can't wait for it being implemented :)

**Comment by diracdeltas** [comment]
Thanks brad! btw the spelling should be "phishing", not "fishing" in the mockups. :fish: 

One thing to note is that we will eventually want to have per-ruleset controls for HTTPS Everywhere. not sure if those should go in the bravery panel, or if we should just have buttons for each browser "extension" separately.
![screen shot 2016-05-08 at 11 57 49 pm](https://cloud.githubusercontent.com/assets/549654/15105710/b8e0e7b8-1578-11e6-8038-cf907a020f27.png)

this may also be needed for NoScript eventually

**Comment by bradleyrichter** [comment]
@diracdeltas Thanks for phinding that silly spelling error. I fhixed it!  ;   )


Regarding HTTPS, this would be a per-site exception list to connected sites within that site, correct?

**Comment by diracdeltas** [comment]
@bradleyrichter that's right

**Comment by luixxiul** [comment]
I have a question about "HTTP reroutes". Does this just display the number of reroutes or those of blocked, as an add-on like this https://addons.mozilla.org/en-GB/firefox/addon/clean-links/ does?

**Comment by diracdeltas** [comment]
it displays the number of requests sent over-the-wire that were rewritten by HTTPS Everywhere

**Comment by bbondy** [comment]
It's only wrt to http being converted to https.

**Comment by luixxiul** [comment]
yeah that will be much more understandable
