### ISSUE TITLE
Holding on back button should show the list of previous pages to choose

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1622]
When holding on Back button, I'd like to see list of previous pages, so I can choose from, without having to click Back button too many times when my history is quiet long.

Similar thing works in Chrome as shown below:

<img width="342" alt="screen shot 2016-05-08 at 00 54 59" src="https://cloud.githubusercontent.com/assets/266306/15095302/a3d00dc0-14b7-11e6-9c63-7ad7ec56b5af.png">

The same should be implemented for Forward button.

Currently when I'm holding on either Back or Forward button, the whole window moves.

This is especially trouble when the previous page is a redirect page (#1633), so you can't easily skip that page.

**Comment by luixxiul** [comment]
@bbondy Is this being worked on?

**Comment by bbondy** [comment]
not yet

**Comment by bradleyrichter** [comment]
This task was started today by @bsclifton .

Here is the UI mock for it. Looking for feedback on a feature I added at the bottom for "All the way back" which takes you to the beginning of the tab history list, whether it is visible in the list menu or not. 

![image](https://cloud.githubusercontent.com/assets/13509546/16703520/3f6bf1cc-4523-11e6-804f-8d25dee4dea2.png)



![](https://files.slack.com/files-pri/T04PX1BU8-F1Q5USLM6/pasted_image_at_2016_07_08_02_53_pm.png)

**Comment by bradleyrichter** [comment]
Feature descriptions:

- hover help balloon to remind you that mouse down has hidden functionality 

- holding down the back button should open a tab-specific list of pages ordered based on the history of page visits only for that tab

- holding down the forward button (when available) should open a list of the available forward pages in the tabs history

- each entry uses the same styling as the search results popup which includes both the page title and the URL

- This popup list window can be opened via long press with selection on mouse up, or as a right-click with selection on mouse down

- at the bottom, there are 2 choices. 
    - All the way back (skips back to the top of the history chain)
    - show all history... (link to open about:history when it becomes available)

**Comment by bsclifton** [comment]
Got a bare bones version working:
![2016-07-09](https://cloud.githubusercontent.com/assets/4733304/16709140/d2897dfa-45bc-11e6-82ed-3eeeecde21e6.png)

Will keep hacking on this and will post more updates :smile:
