### ISSUE TITLE
Zoom level should be displayed when changing

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1623]
When changing the page zoom levels (on OS X: `CMD`-`+`/`CMD`-`-`), I would like to see the current zoom level I'm currently in, so I could be aware whether I'm in 100% or how far from it.

Similar feature works in Chrome browser as shown below:

<img width="251" alt="screen shot 2016-05-08 at 01 06 32" src="https://cloud.githubusercontent.com/assets/266306/15095328/51f517fa-14b9-11e6-8ac5-4bef297d02dd.png">

**Comment by Liunkae** [comment]
+1 from #10219.
