### ISSUE TITLE
Add a "Look Up Selection" context menu item in OS X when there is a selection

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1627]
win.showDefinitionForSelection() (only for OS X)

**Comment by tsl143** [comment]
I want to take this, can anyone help me with this?

**Comment by bbondy** [comment]
@tsl143 a good starting point would be in js/contextMenu.js around `nodeProps.hasSelection`.  For your action handler you'd want something like `require('electron').remote.getCurrentWindow().showDefinitionForSelection()` but I haven't actually tried it.  You'd also want to only show the menu items when process.platform === 'darwin'

**Comment by bbondy** [comment]
@tsl143 are you still working on this?

**Comment by jmalonzo** [comment]
@bbondy Looks like this is fixed? I see a "Search for '...'" context menu item already in today's master.

**Comment by bbondy** [comment]
Search for is different, Look Up is to define the word in the dictionary lookup on OS X.

**Comment by jmalonzo** [comment]
hmm I think we might need https://github.com/electron/electron/commit/f4c1cd11a035deba30609948bc4660319f8ecc9b in brave/electron for this to work in web views.
