### ISSUE TITLE
Unnatural space next to back button (Windows 10)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1628]
On Windows 10 there is unnatural space next to the back button, under "New Tab" (title bar) 

![](http://i.imgur.com/zL4xQZN.jpg)

Intended?

**Comment by bsclifton** [comment]
I also don't like this- it would be easy to fix
cc: @bradleyrichter

**Comment by bbondy** [comment]
This is just because of the OS X controls on the left, on Windows the gap shouldn't be there.

I'd imagine adding some css class top level that's called isWindows via check for `process.platform === 'win32'` would do the trick.

**Comment by bradleyrichter** [comment]
I'd love to have this fixed.

**Comment by bsclifton** [comment]
https://github.com/brave/browser-laptop/pull/1638 ready for review :smile:

**Comment by duff2481** [comment]
@luixxiul using 0.9.5 version on Windows machine and I have the start bar on top of my screen, not the bottom.  I constantly need to readjust each time brave is loaded.

**Comment by bbondy** [comment]
What is the start bar? Do you mean the Windows task bar?

**Comment by duff2481** [comment]
yes, task bar.

**Comment by luixxiul** [comment]
Would you please take a screenshot?
2016/05/13 22:36 "duff2481" <notifications@github.com>:

**Comment by duff2481** [comment]
![brave_default_opening](https://cloud.githubusercontent.com/assets/19331241/15253922/57b62416-1902-11e6-957b-475e2a97cb4d.png)

**Comment by luixxiul** [comment]
By the way on Windows 10,

![](http://i.imgur.com/VCUjf0n.jpg)

Attention to the top right corner.

Also I opened the new issue #1727 for that issue, thanks.
