### ISSUE TITLE
Clicking on Back button while holding CMD/Ctrl should open page in a new tab.

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1632]
This is default behaviour of many web browser.

While I'm holding CMD on Mac or Control on Windows (which is general rule for opening the links in a new tab), I'm expecting that clicking on Back or Forward button will open the page in a new tab, but this not happens. Instead, I'm redirected to that page in the current tab.

This is useful when you'd like to open previous page in a new tab without losing state of the current one.

**Comment by Liunkae** [comment]
I think this has been implemented.

**Comment by bsclifton** [comment]
@Liunkae that is correct 😄  It was implemented with https://github.com/brave/browser-laptop/commit/d4b6cf586ad88b32a8c2b5243fa2043541dd4b12
