### ISSUE TITLE
Tegulu?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1634]
@aekeus Isn't it "Telugu", not "Tegulu"?

https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/en-US/preferences.properties#L57

**Comment by aekeus** [comment]
Thanks for the find. Will fix this up!

**Comment by aekeus** [comment]
Fixed with commit d54eafa9c1aba194b71d42f5967ca5ac87031c7a
