### ISSUE TITLE
The loader always spins and the webview never renders in the built package(built using electron packager)

### ISSUE THREAD

**Issue by prkeshri** [brave/browser-laptop#1637]
Hello guys,
The above was happening (only in the packaged executable. In `npm start`, everything runs fine!). 
So, I extracted the electron.asar file and wrote a couple of log statements, re-archived into  electron.asar and ran the `./brave` executable. The following is the sequence of webview events (for any url):
did-start-loading
destroyed
did-start-loading
did-get-response-details
load-commit
did-navigate
destroyed
did-start-loading
.
. and so on in the same loop

The webView always fires these in the order in a loop. I need to know why is it getting destroyed always?

Update: In the guest-view-internal.js(electron.asar/renderer/web-view/), after I logged some random shell commands, now the web page is showing. But whenever I switch to another tab, the page gets refreshed. Is it a problem from electron's side? Or some other issue?

Please note that if I run by doing `npm start`, everything works fine.

Update: The file **electron.asar** is different in packaged module than in node_modules/electron-prebuilt!

**Comment by luixxiul** [comment]
Will you please try again on the latest version?

**Comment by luixxiul** [comment]
Closing due to lack of information. Please feel free to leave a comment if you experience the issue. Thanks.
