### ISSUE TITLE
dangerous close window - no reopen last closed window - no history

### ISSUE THREAD

**Issue by jbshirk** [brave/browser-laptop#1639]
when a tab is zoomed, other tabs are not visible and if the tab is a single tab in second or third window page, it appears to be a lone window and closing it closes all pages and all their tabs! this is maddening. 

Worse, the history (ctrl-y) does not work, and there is no 'reopen last closed window' function. 

I cannot count how many times i've accidentally closed a multi-page window, losing all its tabs and no way to reconstruct it from history. it's enough to make me stop using brave.

**Comment by luixxiul** [comment]
Related? https://github.com/brave/browser-laptop/issues/854

**Comment by bradleyrichter** [comment]
@bbondy It seems that we should add a warning dialog for control+shift+W since it's hard to recover from. (impossible until we have History fully implemented.)


![image](https://cloud.githubusercontent.com/assets/13509546/15153347/c781b282-168d-11e6-8f06-39e370cb6282.png)

**Comment by bbondy** [comment]
Related to this as well... We do have an undo closed window but due to a localization bug it was wrongly double labeled as undo closed tab. It was already fixed.

**Comment by bradleyrichter** [comment]
undo closed window may solve it...

**Comment by luixxiul** [comment]
@bbondy So should this already be closed? https://github.com/brave/browser-laptop/issues/255

**Comment by bbondy** [comment]
yes and #854 is some follow up.
