### ISSUE TITLE
Window position not restored correctly on app startup

### ISSUE THREAD

**Issue by jimfr** [brave/browser-laptop#1643]
Windows 10.  Samsung ATIV Book 9 Plus (QHD screen).  This buglet is present in every version of Brave I have tried (I started with 0.8).

  Here is the upper right portion of the Samsung’s screen when correctly positioned:

 
![brave - upper right](https://cloud.githubusercontent.com/assets/5986716/15114916/228ad092-15b1-11e6-92ce-83671dd4e704.PNG)

  After exiting and restarting Brave, this is what it looks like:

 ![brave - upper right after restart](https://cloud.githubusercontent.com/assets/5986716/15114925/2c30096e-15b1-11e6-8e23-563adade02eb.PNG)

So, every time I start Brave, I have to reposition the window.  Not a big deal, but I thought you should know.

**Comment by luixxiul** [comment]
Closing in favour of #146
