### ISSUE TITLE
Wrong favicon is shown for bookmark

### ISSUE THREAD

**Issue by chitza** [brave/browser-laptop#1646]
![captura de ecran din 2016 05 09 la 18 13 07](https://cloud.githubusercontent.com/assets/1458579/15117838/228cba86-1612-11e6-9481-5f77a170297c.png)

Sometimes favicons get mixed up. In the above screenshot, the favicon for feedly was green while I was reading the RSS feeds. Then I clicked the twitter link and the feedly favicon changed to that of twitter.

**Comment by luixxiul** [comment]
May be a bug, CC'ing @bradleyrichter

**Comment by luixxiul** [comment]
I notice sometimes this too

**Comment by johnmarzan** [comment]
happens sometimes in mine

**Comment by bbondy** [comment]
steps to reproduce wanted if anyone can find them.

**Comment by dogancelik** [comment]
I can confirm, only step for me is clicking "Show favicon for items in Bookmarks Toolbar"

![icons](https://cloud.githubusercontent.com/assets/486818/16138662/81025798-3448-11e6-96ad-98b12113ef70.png)

**Comment by garvankeeley** [comment]
Is happening for me if you want me to help
<img width="270" alt="screenshot 2016-06-21 17 42 11" src="https://cloud.githubusercontent.com/assets/5495083/16247394/884c3608-37d7-11e6-85e8-f99e673dbf52.png">

**Comment by bbondy** [comment]
I think I found out how to reproduce, you need to click a bookmark item and before it is done loading click another one.

**Comment by garvankeeley** [comment]
Still on 0.10.4
<img width="267" alt="screenshot 2016-06-23 10 19 05" src="https://cloud.githubusercontent.com/assets/5495083/16306819/fec72ea4-392c-11e6-8c32-6270a1b8407b.png">

**Comment by bbondy** [comment]
there's no way to fix your previous entries.

**Comment by bbondy** [comment]
it just won't happen anymore.

**Comment by garvankeeley** [comment]
Ok, confirmed fixed

**Comment by robfla** [comment]
Still an issue, version 0.12.8.

[https://abload.de/img/redddu8uvt.jpg](url)

**Comment by bsclifton** [comment]
Re-opening as this is still happening

**Comment by bsclifton** [comment]
Looked into this briefly; I know the [favicons are now updated properly after page visit](https://github.com/brave/browser-laptop/commit/35c5b97b64eef9d87a9581c8f8c6e3f58ac05c00).  My best guess is that the favicon for site A is being updated (an event which fires after page load and sets after looking up site using index) while a site B is being added (and added to the sites array)

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7161)

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/7257)

**Comment by bsclifton** [comment]
Possibly related to https://github.com/brave/browser-laptop/issues/10176

@NejcZdovc I believe this will be fixed with your PR (https://github.com/brave/browser-laptop/pull/10136).  What do you think?

**Comment by NejcZdovc** [comment]
Yes this should be fixed with #10136
