### ISSUE TITLE
Brave does not close properly on Windows

### ISSUE THREAD

**Issue by kolipka** [brave/browser-laptop#1649]
Quite often Brave does not close properly, and leave some processes in the background. Because of that last opened tabs does not restore. 

![image](https://cloud.githubusercontent.com/assets/3721812/15125502/7696bc60-162d-11e6-9d66-8109b8f5b577.png)

Brave 0.9.4, Win 8.1 Pro 64 bit

**Comment by luixxiul** [comment]
Duping to #1540. Please update to the latest version and tell me whether this still persists.

**Comment by kolipka** [comment]
few days left and it still works OK :) Thanks!
