### ISSUE TITLE
Sound not working on HTML5 player(websites)?

### ISSUE THREAD

**Issue by briannyeko** [brave/browser-laptop#1650]
When i play videos(from youtube,cnn,cnet,the verge,viceland etc..) the html5 player sound suddenly stops working... is it any problem that you guys could fix for your next update?

I Use a macbook pro 15 inch(mid 2012) and i use Mac OSX 10.10.

Btw when will you add plugins(such as pocket, wrappanalyzer to brave)?

**Comment by luixxiul** [comment]
Does this still persist?

**Comment by briannyeko** [comment]
yes.

**Comment by luixxiul** [comment]
It would be nice if you would give us steps to reproduce the issue.

**Comment by bbondy** [comment]
@briannyeko still happening? Do you have a URL that you can reproduce on?

**Comment by briannyeko** [comment]
I fixed the problem
