### ISSUE TITLE
Preferences (and websites) do not load

### ISSUE THREAD

**Issue by mdmcginn** [brave/browser-laptop#1651]
Choosing Preferences from the hamburger menu changes the URL to about:preferences, but nothing loads. The screen remains blank.

When I enter google.com in the address bar, the URL changes to http://google.com, but nothing loads. The blue lock is unlocked, even when I type in https://google.com/

Help > About  Brave provides the following information:
Brave 0.94
Electron: 0.37.7
libchromiumcontent: 50.0.2661.94
V8: 5.0.71.39
Node.js: 5.10.0
Update channel: dev

I'm using Windows 10 Enterprise 64 bit.

**Comment by luixxiul** [comment]
Would you please update to the latest version and try again? Thanks.

**Comment by Troy-Wilson** [comment]
I have the same issue.  I have been using it for a couple of months and Brave was working for me until today. I tried uninstalling and reinstalling the software. I now have:

Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8:5.2.361.49
Node.js: 6.3.0
Update Channel: dev

I am runing windows 10 Pro.

Now websites or preferences load. When I try to access www.google.com it does nothing for a while. Eventuall the URL bar changes to about:error.

I do Have Norton Security, but it was working on friday and even when I turn all firewall settings etc off Brave still doesn't work. I can acces the web through firefox which is what I am using to write here.

**Comment by luixxiul** [comment]
Closing as stale
