### ISSUE TITLE
About page favicon

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1656]
They were originally added here:
https://github.com/brave/browser-laptop/issues/898#issuecomment-218091747

Maybe broken with extensions @bridiver

**Comment by bridiver** [comment]
not sure why it isn't loading correctly `chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/img/favicon.ico  Failed to load resource: net::ERR_ADDRESS_UNREACHABLE`. I can open it directly without a problem.
