### ISSUE TITLE
Suggestion: "show only favicon" on bookmark bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1657]
Why don't you add "show only favicon" mode like this?

![](http://i.imgur.com/TjqlDlY.jpg)

It would be nice to show the title as a tooltip.

I'd love to see this implemented, but maybe kinda personal preference.

Idea: https://addons.mozilla.org/en-US/firefox/addon/smart-bookmarks-bar/
ref: #1454

**Comment by bradleyrichter** [comment]
sounds like a good P2 item. Everyone likes to customize the favorites bar and this would be space-efficient when a user has MANY links.

**Comment by SJ-Diamond** [comment]
That idea i do like, it is also how i have customized the bookmarks bar in Vivaldi, would be great to have it in Brave too.

**Comment by bsclifton** [comment]
This wouldn't be too hard- would be a great one for someone wanting to get their feet wet :smile:

**Comment by luixxiul** [comment]
Tooltip has been already merged with #1926
