### ISSUE TITLE
Youtube ad video

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#1661]
Ad videos on youtube are catching and stoping, I need to f5 like every time..

**Comment by luixxiul** [comment]
Will you please update to the latest version and let us know if it is same? Screenshot would be appriciated.

**Comment by Kzeir** [comment]
Well, It doesn't appear any ads so if appear anything, I'll tell you

*Att: Alessandro Tetsuo More*

2016-05-13 14:47 GMT-03:00 Suguru Hirahara <notifications@github.com>:

**Comment by Kzeir** [comment]
![screenshot_20160516170634](https://cloud.githubusercontent.com/assets/17557010/15302299/ac07c3e8-1b88-11e6-9ea4-52622ff3f3f7.png)


Advertising is frozen and after a while the video begins.

**Comment by Kzeir** [comment]
In this update, I can see the ads videos now

**Comment by luixxiul** [comment]
OK, closing for now
