### ISSUE TITLE
"Remember this decision" text in notification should toggle the checkbox

### ISSUE THREAD

**Issue by AlfonsoML** [brave/browser-laptop#1663]
![brave remember](https://cloud.githubusercontent.com/assets/2482331/15160751/871d8b58-16fb-11e6-8590-c91776d1afc5.png)

Tested in Windows. 
The notification bar at the top of the browser when the page request Full screen should put a label around the "Remember this decision" to easily switch the checkbox

**Comment by diracdeltas** [comment]
This is fixed; will be going out in the next release.
