### ISSUE TITLE
Added bluetooth dongle, video plays but no sound

### ISSUE THREAD

**Issue by aarondolson** [brave/browser-laptop#1664]
Installed a GMYLE Ultra-Mini USB CSR4.0 Class 1 Bluetooth V4.0 Long Range Dongle Wireless Adapter and now sound is no longer working in browser.  

The speaker icon displays on the tab & video plays but no sound.

Videos play with sound in chome/firefox just fine.  Tried restarting PC, still did not work.

0.9.4
Windows 10

**Comment by luixxiul** [comment]
Does this still persist?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-added-bluetooth-dongle-video-plays-but-no-sound/10053

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
