### ISSUE TITLE
Use API: app.dock.downloadFinished(filePath)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1667]
Should be added in next release after 0.37.8
https://github.com/electron/electron/pull/5477

**Comment by Liunkae** [comment]
Q/A steps:
1. Navigate to https://brave.com/ .
2. Click `Get Brave` and then click `Save`.
3. As the download progress bar approaches 100%, look at the Downloads folder dock icon.
4. Make sure the dock icon "bounces" when the download finishes.

**Comment by alexwykoff** [comment]
Not seeing dock bounce in 0.15.307, was this reverted?
