### ISSUE TITLE
Leaves 1/2" gap at top of screen in full screen mode in osx

### ISSUE THREAD

**Issue by bfkelsey** [brave/browser-laptop#1668]
When in full screen mode a 1/2" gap is black along the top half of the screen.
Brave version: 0.9.4
OSX version: 10.11.4

Steps to reproduce:
1. Open browser, Click Green button at top left to go into full screen mode.
2. A half inch gap where the brower doesn't fill the screen is visable at the top.
<img width="133" alt="screen shot 2016-05-10 at 8 55 28 pm" src="https://cloud.githubusercontent.com/assets/131458/15169654/7e49ce8c-16f2-11e6-9ae0-e91c5700dfb6.png">

**Comment by duff2481** [comment]
this occurs only on Windows for me :( version Win 10

**Comment by luixxiul** [comment]
@duff2481 which version are you using? For windows the latest version has fixed this issue with #1628. 
Still maybe we have to detect full screen mode on OS X, doesn't we?

CC: @bbondy

**Comment by bbondy** [comment]
yep this is a known issue, CC @bridiver in case he has ideas.  Maybe Window size is wrong somehow?

**Comment by bridiver** [comment]
I'll take a look at this again. There are a few fullscreen issues at the moment and this one may have been caused by a fix for "draggable" regions that was implemented a while ago

**Comment by luixxiul** [comment]
Closing this as duping to #1358
