### ISSUE TITLE
tests  for new window on app icon click (macOS)

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#167]
when there are no windows open, clicking on the app icon opens a new window

**Comment by luixxiul** [comment]
Of course this can be closed, right?

**Comment by bridiver** [comment]
well, the issue was to create a test for it and looks like there still isn't one

**Comment by luixxiul** [comment]
ok, I see.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/677
