### ISSUE TITLE
Right-clicking does nothing in a data:text/html page

### ISSUE THREAD

**Issue by salty-horse** [brave/browser-laptop#1673]
Using Brave 0.9.5.

Visit the following URL: `data:text/html,hello<br><input>`

Right clicking will not work, either on the page, or inside the text box. It's impossible open a context menu (to inspect elements, or copy/paste).

Both Firefox and Chrome allow opening a context menu.

**Comment by cezaraugusto** [comment]
Hey @salty-horse, using brave 0.10.3 it works great. Is it still an issue for you?

**Comment by bbondy** [comment]
I think this works now, closing.  We'll re-open otherwise though.

**Comment by salty-horse** [comment]
I can confirm this is fixed.
