### ISSUE TITLE
Urlbar autocomplete improvement

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1674]
![](http://i.imgur.com/CxpDpAp.jpg)

Pushing right arrow here should complete the domain to continue like ``facebook.com/SomePage``

It seems like https://github.com/brave/browser-laptop/issues/891 or https://github.com/brave/browser-laptop/issues/241, but slightly different to me.

**Comment by diracdeltas** [comment]
This is pretty close to #241 so whoever takes it should take this while they're at it

**Comment by luixxiul** [comment]
related #1596

**Comment by luixxiul** [comment]
Closing in favor of #1596
