### ISSUE TITLE
Feature request : Greasemonkey

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1676]
Hello Dev team,

is there anyway to integrate Greasemonkey with brave ?

/Haze

-- 

Ed by @luixxiul

I opened a topic about Greasemonkey on our community site:

https://community.brave.com/t/extension-request-greasemonkey/10284

Please share your love to the suggestion there 😄

There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience 👍 Thanks!

**Comment by diracdeltas** [comment]
Not yet but planned; see for instance https://github.com/brave/browser-laptop/issues/527#issuecomment-211022215

**Comment by Haze-Aulaian** [comment]
@diracdeltas so this explains why the ads of youtube still appears :/

bummer , i was planning to spread the browser wide at work and replace firefox.
it seems that the browser won't be ready for office uses and merely for small user browser experience.
:(

**Comment by diracdeltas** [comment]
@Haze-Aulaian we should be blocking those youtube ads anyway; i think you're running into a different bug

**Comment by kneekoo** [comment]
Hello,

Any news about Greasemonkey support?

**Comment by arcum** [comment]
o/ Greasemonkey support! Are we there yet? 👍

**Comment by luixxiul** [comment]
Added here: https://github.com/brave/browser-laptop/projects/1#card-1356306

**Comment by fap-** [comment]
@luixxiul I'm confused by this, afaik Brave is only compatible with Chrome/Chromium extensions, but Greasemonkey is Firefox only. Compatible userscript extension for Brave would be Tampermonkey?
https://tampermonkey.net/

**Comment by kneekoo** [comment]
Well, it's expected from a Firefox user to request Greasemonkey support, just as it's expected from a Chrome/ium user to request Tampermonkey, or an Opera user to request Violentmonkey. The bottom line (and the correct title) is that we want support for user scripts in Brave.

**Comment by Gigafrost** [comment]
Is there any news on this? I noticed that this has been open for about a year now.

**Comment by jnm2** [comment]
Greasemonkey/tampermonkey is super important to me, both for things like removing large empty sidebars left by ad blocking and for simple automation tools I've written for the sites I frequent.

**Comment by jnm2** [comment]
Fyi Greasemonkey and ZenHub are the only two extensions I use that you don't already support.

**Comment by jandahl** [comment]
+1

**Comment by rtloeffler** [comment]
+1

**Comment by Ralosso** [comment]
+4 Users

**Comment by glenncarr** [comment]
+5

**Comment by bonzobudy** [comment]
Lack of userscript support is the only reason I haven't switched over to Brave as my main browser.

Would love to see this added.

**Comment by SeAlgoAsoma** [comment]
Yeah, I can't even consider using a browser that won't run my userscripts.

**Comment by luixxiul** [comment]
I opened a topic about Greasemonkey on our community site:

https://community.brave.com/t/extension-request-greasemonkey/10284

Please share your love to the suggestion there :smile:

There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

**Comment by diracdeltas** [comment]
i think we should re-open this issue since greasemonkey never got implemented in Brave

**Comment by joeytwiddle** [comment]
Greasemonkey has taken a different direction since Firefox Quantum, redefining what a userscript is.  As a result, the majority of old scripts do not run in it without modification, so I have switched to TamperMonkey for now, for practical purposes.

It's worth thinking about which direction to take, and looking at what users are currently doing.  (How many of the popular scripts on GreasyFork and OpenUserJS work in Greasemonkey/Tampermonkey now?)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/697
