### ISSUE TITLE
Cosmetic: There is always a space after the C letter in the url

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1677]
Hello Dev team,

i have noticed that there is always strange space between the C letter and the letter after it in the url bar for some reason as you can see it below:

![braveissues1](https://cloud.githubusercontent.com/assets/17910355/15180580/1a84fa90-178b-11e6-9ae5-2de3932b983d.PNG)

![braveissue2](https://cloud.githubusercontent.com/assets/17910355/15180584/20b73a7c-178b-11e6-9656-cd36fe0133e3.PNG)

OS : windows 7 64 bit (SP1)
Brave : 0.9.4

/Haze

**Comment by Superbest** [comment]
To be more precise, there is not a space (as in, a space character) - it is a kerning issue.

**Comment by Haze-Aulaian** [comment]
@Superbest ya if you want to put it that way.

**Comment by luixxiul** [comment]
since several releases the font rendering on Windows has drastically improved.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26583934/0a68e268-4582-11e7-8dd1-0f443d1fe786.jpg)

I'm going to close this issue.
