### ISSUE TITLE
Support windows store appx

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1679]
https://github.com/electron/electron/pull/5489/files#diff-1

**Comment by alexwykoff** [comment]
Prioritizing to 1.2 as it would help growth and support.

**Comment by d1vanloon** [comment]
Installation and updating from Windows Store would be great.

**Comment by Dyras** [comment]
You can sign me up on this. I would LOVE for Brave to be on the Windows Store. That way it would support Windows 10 S.

**Comment by bsclifton** [comment]
@jonathansampson put together an appx package and it went through the review process.  I don't think we've ever released an official statement but here's a summary:

- app was rejected with reason:
  > no Desktop bridge browsers are allowed

- when we asked if there are exceptions, we received the feedback:
  > Unfortunately there is no way around this because we have found Browsers to open security risks with the heightened security role and therefor are not allowed

Given this news, it appears that we won't be able to support Windows 10 S.  However, I'm curious if we'd still be allowed to have Brave added to the Windows Store

**Comment by bsclifton** [comment]
Closing per the above comments about being rejected
