### ISSUE TITLE
titlebar and bookmark toolbar should be hidden on popup window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1683]
On hulu.com,

![](http://i.imgur.com/quDeFOK.jpg)

The bookmark toolbar and tabs should be hidden.

**Comment by luixxiul** [comment]
Adding a class like ``popup`` to the opened window and styling with ``display:none`` could be a solution.

**Comment by srirambv** [comment]
Title bar region looks bad on popup windows
![image](https://cloud.githubusercontent.com/assets/17010094/18831006/4de8533e-83db-11e6-8082-fb7cc03c5ded.png)

#3032
