### ISSUE TITLE
Use greenkeeper to automatically keep npm deps up to date

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1701]
https://greenkeeper.io/

**Comment by alexwykoff** [comment]
@bbondy @diracdeltas is this still an issue or we end up switching to yarn?

**Comment by luixxiul** [comment]
Greenkeeper 2 has been released since May.

https://blog.greenkeeper.io/greenkeeper-2-0-release-da8f8f476c88

````
Feature shortlist

💰 New entry-level pricing model:
Start with Greenkeeper from $25 for 10 private repos per month on organisations or just $1.50 per private repository for personal accounts.
🤖 Uses the new GitHub Integrations API.
🔇 Less noise: Fewer GitHub notifications.
✨ Support for npm shrinkwrap.
💪 More convenient and more flexible dependency update handling.
📌 Built-in dependency pinning, for when you just don’t have time to deal with a breaking change.
🔒 Native support for scoped and private npm modules.
💳 Better payment and billing user experience.
📰 Open product roadmap.
````

**Comment by diracdeltas** [comment]
Greenkeeper is still useful in addition to yarn/package-lock for keeping dependencies up to date. right now `npm outdated` shows a lot of outdated dependencies.

**Comment by bsclifton** [comment]
Without reliable tests, upgrading should only be limited to patch and minor versions, IMO.  Even then, there would be some risk.  Personally, I don't have enough confidence in our webdriver tests- I don't think we're ready to do this yet

**Comment by diracdeltas** [comment]
I think that every N releases, we should update every dependency to latest stable version and lock that in package-lock, for some value of N. There should be enough time for manual testing to make sure things don't break in these releases.

**Comment by luixxiul** [comment]
It should be nice if we have automated test suite with setting the environment variable `process.env.NODE_ENV` to the string value `production` to avoid a nasty bug which @bsclifton, @jonathansampson, and @kevinlawler have solved on https://github.com/brave/browser-laptop/issues/10029.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/1701
