### ISSUE TITLE
OS X issues with fullscreen and keyboard commands

### ISSUE THREAD

**Issue by jkd00** [brave/browser-laptop#1702]
Hey guys,

Noticed a couple bugs on OS X El Capitan.

- Fullscreen has a huge black bar at the top of the screen

![image](https://cloud.githubusercontent.com/assets/4303497/15209743/2d58db0c-1833-11e6-938d-8004b707912f.png)

As you can see, this wastes a ton of space. 

It gets really akward when running Brave in one pane and text editor in the other for developer.

In general, as a power user I'd like to see the tool and tab bars take up less vertical real estate. Maybe a "sleek view" mode could be added to future versions?

- Keyboard commands

This just randomly stop working. Cmd-c, Cmd-w, etc., etc. Restarting the browser seems to fix.

Also, when you have tabs pinned and cycle through your unpinned tabs with Cmd-Shift-[ and ] the focused tab will randomly jump back and forth from the untabbed pins to the tabbed ones.

- Copy image

When you right click an image, there's no option to copy the actual image to the clipboard, just the url.

Not really a bug but this is very handy to have and something I use all the time in Chrome/Firefox.

---

Anyway, I'm now using Brave like 80% of the time and hope to bring it to 100%.

Cheers,
Kyle Duck

**Comment by bridiver** [comment]
related https://github.com/brave/browser-laptop/issues/1668

**Comment by bbondy** [comment]
Full screen black bar issue fixed, leaving open for the rest.

**Comment by Liunkae** [comment]
I think all (or almost all) of the issues listed here have been fixed. Feel free to reopen/create a new issue if any problems remain.
