### ISSUE TITLE
Suggestion: Show "restart" to apply language change

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1705]
In `about:preferences`. It may be a pop-up or button/link "Restart" next to languages pull down, to apply the change as soon as possible, preserving the opened windows/tabs.
#1858

**Comment by bbondy** [comment]
Or change dynamically I think would be do-able.

**Comment by luixxiul** [comment]
But what if you accidentally choose Bengali and you cannot read it...

**Comment by bbondy** [comment]
True but you can still see the drop down and change it further to change it back.   Maybe showing the language code as well next to it? Like en-US as well?

**Comment by luixxiul** [comment]
Yes that would be nice :-)
2016/05/13 20:37 "Brian R. Bondy" <notifications@github.com>:

**Comment by luixxiul** [comment]
How about implementing this? pinging.

**Comment by luixxiul** [comment]
Closing this in favor of #4777
