### ISSUE TITLE
Zoom function does not update zoom percentage in private tabs

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1706]
In 0.9.5, the zoom function doesn't change the displayed percentage value when used

**Comment by cfumante** [comment]
Cancel this - it's now working - not sure what happened, but it's a non-issue

**Comment by luixxiul** [comment]
Closing, please let us know steps to reproduce if you see it stop from working again.

**Comment by cfumante** [comment]
Happened again this am. and disappeared again.
 
Not much in the way of actions to reproduce the problem:
 
Laptop was sleeping
Woke it up
Went to first site
Clicked on the zoom icon
  - page enlarged but the displayed number stayed at it's previous value
(115%)
  - worked the same for decreasing the zoom
Went to second site - same results
 
Closed Brave and re-opened:
Went to first site
Displayed number now increments/decrements
 
Note that the first time I saw this, immediately after the release of
0.9.5, it also "fixed itself" after a few minutes and I hadn't reloaded
Brave.
 
All-in-all a pretty minor glitch - unless you all think it's symptomatic
of some larger problem, I wouldn't re-open the issue.
 
mahalo,
 
/c/

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by cfumante** [comment]
New info - the problem seems tied to the use of private tabs. After
testing the same site with both private and non-private tabs, the
private tabs do not show the number changing while the non-private do.
 
 

Carl Fumante                                                

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by luixxiul** [comment]
@bbondy how do you think?

**Comment by luixxiul** [comment]
Confirmed on both Windows 10 and Ubuntu 14.04
