### ISSUE TITLE
unable to copy from URL bar 0.9.5 dev channel

### ISSUE THREAD

**Issue by duff2481** [brave/browser-laptop#1707]
Since updating to new dev channel version today, I'm unable to right-click on URL bar and select 'copy'. 
![brave_copy](https://cloud.githubusercontent.com/assets/19331241/15222730/14723f3c-183f-11e6-8a44-2edc945542bf.png)

**Comment by bbondy** [comment]
Thanks for posting we might do a quick hotfix tomorrow for this.

**Comment by bbondy** [comment]
You can use the shortcut in the meantime Command+C to copy

**Comment by bbondy** [comment]
Control+C on Windows

**Comment by duff2481** [comment]
Yes, i have been using shortcut, but thought I would post ;-) Keep up the great work.
