### ISSUE TITLE
Selecting text on the Mac version is fubar

### ISSUE THREAD

**Issue by ballo** [brave/browser-laptop#1711]
Selecting beyond a line (or paragraph) of text causes the selection to go the opposite way (i.e. to the beginning of the line instead of where the cursor is). 

Just to be clear: selecting text on a Mac has always been different than Windows.

When selecting beyond a line (or paragraph) of text on a mac, it should NOT select the trailing linefeed (or carriage return) unless the cursor is on the opposite side of the text. This makes choosing whether to select the linefeed a simple gesture of dragging from the beginning down the left or right side of the paragraph. In windows the linefeed/return is selected regardless of the gesture and is therefore inferior by far. 

Safari demonstrates the correct behavior as does BBEdit (and I assume TextWrangler). Unfortunately, the default Cocoa behavior is wrong and Apple hasn't fixed the problem since OS X DP2.

**Comment by bbondy** [comment]
Could you give a specific link with the problem? 
Selecting the text in github in your message does not seem to reproduce.

**Comment by ballo** [comment]
Yeah, sorry, upon further inspection I think this has to do with text in
SVGs. Here's one example:

https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/DroidSerif-Regular.svg

**Comment by bbondy** [comment]
Does it work the same as Chrome? If so this should be filed for Chromium instead.

**Comment by ballo** [comment]
OK, so I think this isn't Brave-specific and has to do with the way webkit
works. I'm having the same problem in Safari. Sorry for the confusion.

I tried using NewMoon (Palemoon derivitive) and I couldn't even select the
text (or the selection was invisible).

You can close this I guess.

**Comment by bbondy** [comment]
OK thanks, no problem.  Feel free to track it upstream.
