### ISSUE TITLE
change "status bar" so that it can not be covered by downloads bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1712]

**Comment by bbondy** [comment]
We already have this don't we?

**Comment by bbondy** [comment]
@luixxiul might be a good bug if you want to try it.

**Comment by luixxiul** [comment]
Is it fine to move ``DownloadsBar`` in main.js into frame.js?

**Comment by bbondy** [comment]
No because it is related to the whole window and not to particular frames.  I think you just need to tweak the css so it has `position: absolute;` instead of fixed.

**Comment by luixxiul** [comment]
okay I'll take a look at it

**Comment by luixxiul** [comment]
It would be better if the download bar on/off can be detected
