### ISSUE TITLE
Check update function (ia32)

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1713]
Hello Dev team,

trying to check for any update on the browser.
it keept saying "checking for update" for about 15 minutes and then it found the update.
is it expected for the function to take that long ?

OS : windows 7 32 bit (no SP)
Brave :  0.9.4 (ia32)

**Comment by bbondy** [comment]
did it ever work? Please send your updateLog.log file. You can find it in %appdata%\Brave

**Comment by MacWarrior** [comment]
Hi !
As I understand the way it works, the "checking for update" process is not only checking but also downloading the update, then it show up the "update now" button to launch silent install of the upgrade or simply restart the browser (Not sure of this last point)

**Comment by luixxiul** [comment]
>  the "checking for update" process is not only checking but also downloading the update,

Maybe this should be reconsidered for mobile connections. "Check update" -> "Download update" -> "Apply update", like that.

**Comment by luixxiul** [comment]
I opened the issue for it.

**Comment by Haze-Aulaian** [comment]
@luixxiul actually im using a wimax connection with good speed , so i dont think the speed has to do anything with this.
@bbondy will update you with the logs once i go back home.

**Comment by Haze-Aulaian** [comment]
@bbondy  here you go

[updateLog.txt](https://github.com/brave/browser-laptop/files/264068/updateLog.txt)

**Comment by luixxiul** [comment]
On the log it seems to me nothing is wrong. Maybe temporary issue. How about now, @Haze-Aulaian?

**Comment by Haze-Aulaian** [comment]
i think its just slow process of reaching the server

**Comment by luixxiul** [comment]
OK, closing. If someone else encounter the same issue please leave a comment to reopen this.
