### ISSUE TITLE
Bug: Zoom does not work properly anymore

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#1715]
Zoom in/out function does not work properly anymore in latest Windows builds.

**Comment by luixxiul** [comment]
@SJ-Diamond will you please indicate where to reproduce this?

**Comment by luixxiul** [comment]
Maybe related with #1717. 
CC: @bbondy

**Comment by SJ-Diamond** [comment]
Yes, that's it.

**Comment by SJ-Diamond** [comment]
Guess the reason why zooming is not working is related to the script blocking function, have used a session file without blocking scripts, and i was able to zoom.

With blocking page scripts, i was unable to use the zoom function.

**Comment by luixxiul** [comment]
> related to the script blocking function

Any idea, @diracdeltas?

**Comment by diracdeltas** [comment]
> 1) If i allow script blocking always on that page, zoom can not be used anymore in most cases

example of a page where this happens? i have 'allow scripts always' on github and zoom seems to work

**Comment by bridiver** [comment]
fixed by https://github.com/brave/browser-laptop/commit/656746a45564e08f7a7ad08bce974ac688186502
