### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1716]
@aekeus I have renewed some strings at Transifex already, so could you please update translation before 0.9.6, if possible including #1659?

**Comment by aekeus** [comment]
Hi @luixxiul. Thanks for the translation work. It is appreciated.

We will probably get the newest translations in for our release next week. Not sure what the version number will be.

**Comment by bbondy** [comment]
#1659 is not done yet but I updated the rest of the translation files.
