### ISSUE TITLE
Zooming in and out don't seem to work when script blocking is on

### ISSUE THREAD

**Issue by silverslimer** [brave/browser-laptop#1717]
I'm on Facebook at the moment and tried zooming in and out of the page using both the keyboard combination and the options in the menu. Neither have any kind of an effect.

**Comment by luixxiul** [comment]
@silverslimer Which OS are you using?

**Comment by silverslimer** [comment]
Hi, Windows 10 64-bit. However, I just tested it now and it seems to work. I guess it was a temporary hiccup.

**Comment by luixxiul** [comment]
There might be a.thing which caused it (temp files or like that?), so I
think it is still worth digging.
2016/05/13 9:22 "silverslimer" <notifications@github.com>:

**Comment by LeMeteore** [comment]
I can confirm that on Debian 8.4, zooming works when I click on the buttons inside the menu, but doesn't work using the shortcuts Ctrl-+ / Ctrl--.  Not sure if I can help you fix this, but if yes, let me know how please.

**Comment by SJ-Diamond** [comment]
Guess the reason why zooming is not working is related to the script blocking function, have used a session file without blocking scripts, and i was able to zoom.

With blocking page scripts, i was unable to use the zoom function.

**Comment by bbondy** [comment]
I think we need an exact URL.  I turned on script blocking and then loaded slashdot.org but I was able to zoom.   Also would be useful to know, when you reproduce do context menus work in that tab or is that broken too?

**Comment by SJ-Diamond** [comment]
Try out [https://vivaldi.net/en-US/forum/vivaldi-browser](url)

Tried also with a totally fresh Brave user profile, as soon as i am using the noscript function on it (not the temporary option) i can not zoom anymore on that page.

Context menu in the tabs do work, only zoom function is totally broken.

**Comment by bbondy** [comment]
I think there must be some other combination of things because I tried that link with script blocking on and zoom is still working.

**Comment by bbondy** [comment]
Zooming with both Command+Plus and Command+Minus on OS X.  Also with hamburger menu. 0.9.6.

**Comment by SJ-Diamond** [comment]
Using Windows 8.1 here.

**Comment by SJ-Diamond** [comment]
Even more strange is that a friend is trying right now out on Windows 10, but for him it works there. I repeated trying out in Windows 8.1 with another new profile and zoom still does not work when using the script block feature

**Comment by Arandhras** [comment]
I can confirm I also that I have this issue with https://vivaldi.net/en-US/forum/vivaldi-browser .
WIndows 10, version 0.9.6, x64 build.

**Comment by bbondy** [comment]
@Arandhras also only when script blocking?

**Comment by Arandhras** [comment]
@bbondy Yes, that is correct.

**Comment by bbondy** [comment]
Can you guys check for an error in console?
Control+Alt+J for the browser level console.

**Comment by SJ-Diamond** [comment]
Not seeing anything

**Comment by bbondy** [comment]
How about in the content dev tools Control+Alt+I (popup window devtools)

**Comment by SJ-Diamond** [comment]
There i see some error messages. But i really do not know if they have to do something with this problem, anyway, still posting:

vivaldi-browser:1 (WEB_PAGE context) extensions::ipc_utils:35: Uncaught TypeError: Error processing argument at index 0, conversion failure from null{TypeError: Error processing argument at index 0, conversion failure from null
    at TypeError (native)
    at EventEmitter2.<anonymous> (extensions::ipc_utils:35:22)
    at EventEmitter2.emit (extensions::event_emitter:43:20)
    at EventEmitter2.ipcRenderer.emit (extensions::ipc_utils:31:40)}

**Comment by bbondy** [comment]
cc @bridiver since it looks like an error in extensions::ipc_util.
