### ISSUE TITLE
Make update process better for mobile connections

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1720]
https://github.com/brave/browser-laptop/issues/1713#issuecomment-218977190

>  the "checking for update" process is not only checking but also downloading the update,

Maybe this should be reconsidered for mobile connections. "Check update" -> "Download update" -> "Apply update", like that.

#10863

**Comment by bbondy** [comment]
I've suspected this for a while on Windows I think especially.  It seems like some kind of electron fix is needed for this.

**Comment by luixxiul** [comment]
+1 from support

**Comment by bbondy** [comment]
This is the upstream issue for this:
https://github.com/electron/electron/issues/5057

**Comment by luixxiul** [comment]
Recently it's been fixed. https://github.com/electron/electron/issues/5057#event-1268252022

@bbondy Is it still worth considering or wontfix maybe?

**Comment by bbondy** [comment]
seems still valid but seems easier to do now that it is available upstream
