### ISSUE TITLE
Fails to install on ubuntu 12.04

### ISSUE THREAD

**Issue by adeshpandey** [brave/browser-laptop#1721]
I can not install on ubuntu 12.04, I have tried node 5.6,5.9 but no luck whenever I try to install it says cpp-parse-filter error which looks like below:

npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.7
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 3.8.0-29-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! bloom-filter-cpp@1.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bloom-filter-cpp@1.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bloom-filter-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bloom-filter-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bloom-filter-cpp

**Comment by luixxiul** [comment]
``sudo npm i -g node-gyp@3.2.1`` already done, right?

CC: @bbondy

**Comment by adeshpandey** [comment]
Yeah,
Even I have followed the gist mentioned in the #214 but still same issue

**Comment by luixxiul** [comment]
Would you please ``npm i --loglevel verbose`` and create gist for the log in ``npm-debug.log``, so that @bbondy could check it?

**Comment by Liunkae** [comment]
Ubuntu 12.04 LTS end-of-life is April 28, 2017. ([info](https://insights.ubuntu.com/2017/03/14/introducing-ubuntu-12-04-esm-extended-security-maintenance/)) Should this be tagged `wontfix`?

**Comment by Liunkae** [comment]
No recent reports. I'll close this issue, but feel free to open a new one if this problem still happens with a supported version of Ubuntu.

**Comment by bsclifton** [comment]
Tagged with `wontfix`- thanks for closing, @Liunkae 😄
