### ISSUE TITLE
Middle click on links in bookmarks toolbar should open them in a new tab

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#1724]
Doing a middle click currently turns the curson into a scroll mode icon and does not open the link

Here's a screen cap of the bookmarks toolbar with a link highlighted that I should be able to middle click
![2016-05-13](https://cloud.githubusercontent.com/assets/4733304/15252656/ce024f92-18e3-11e6-9ca8-ccb1388b417b.png)

**Comment by bbondy** [comment]
fairly sure I added support for this a while back but I don't have a mouse connected at the moment to test. Possibly a newer issue or perhaps only with some mice?

**Comment by bsclifton** [comment]
Could very well be a newer issue, I don't remember if it used to work.  Can anyone else confirm? cc: @luixxiul

**Comment by bbondy** [comment]
just tried in a vm with a mouse attached and it's working for me.

**Comment by bsclifton** [comment]
Issue may be specific to Windows 10; will need to dig in more to understand

**Comment by luixxiul** [comment]
Yes, confirmed on Windows 10.

**Comment by bbondy** [comment]
ok this was probably always broken on windows 10 but when I fixed it only worked n pre win10 (possibly just for win7)

**Comment by luixxiul** [comment]
FYI this seems to be specific to Windows 10 as this is not producible on Ubuntu 14.04.

**Comment by bsclifton** [comment]
Checking this out now... it works fine on links, but not when they're nested in a folder
