### ISSUE TITLE
Moving mouse to other bookmarks toolbar items after click should make them expand

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#1725]
If you click a folder in the bookmarks toolbar, it expands and shows the links inside the folder. Unfortunately if you move your mouse to another folder while it's open, nothing happens- the original folder stays open.  I would expect the same behavior as Chrome/FF/etc where moving the mouse to another folder closes the original item and opens the newly selected folder

**Comment by bsclifton** [comment]
Here's a demo:

I originally clicked to open the clifton.io folder in the bookmarks toolbar. I then moved mouse over to morgopolis folder and nothing happened.  You can clearly see the hover style activated over the morgopolis icon, since the mouse is over it
![2016-05-13 1](https://cloud.githubusercontent.com/assets/4733304/15252791/6b2382d2-18e4-11e6-84dd-4f34cefc7584.png)

**Comment by luixxiul** [comment]
@bbondy confirmed on Windows 10.
