### ISSUE TITLE
Title bar under task bar on Windows 7

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1727]
https://github.com/brave/browser-laptop/issues/1628#issuecomment-219086086

> @luixxiul using 0.9.5 version on Windows machine and I have the start bar on top of my screen, not the bottom. I constantly need to readjust each time brave is loaded. 

![brave_default_opening](https://cloud.githubusercontent.com/assets/19331241/15253922/57b62416-1902-11e6-957b-475e2a97cb4d.png)

**Comment by luixxiul** [comment]
Any idea? @bbondy

**Comment by bbondy** [comment]
not off hand

**Comment by luixxiul** [comment]
Is this still reproducible? wdyt @bsclifton ?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/title-bar-under-task-bar-on-windows-7/10408

Let's reopen if we get some other information which helps us to troubleshoot 😄
