### ISSUE TITLE
Bug : Right click menu at the toolbar problem

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1736]
Hello Dev team,

i noticed that i can't copy/paste/cut from the right mouse click menu within the toolbar area and every option is appearing as greyed out.
Im not sure if anyone has reported this earlier.
below is the screen shot (sorry for the bad quality image as i had to take it with mobile camera as windows screenshot nor snipping tool is allowing me to capture it).

![rightmenu](https://cloud.githubusercontent.com/assets/17910355/15261635/630b37ac-1966-11e6-9ac1-126d6c5f3abf.jpg)

**Comment by luixxiul** [comment]
Fixed with #1707. Thanks for the screenshot.

**Comment by bbondy** [comment]
It's live now in 0.9.6
