### ISSUE TITLE
Speed comparison (Brave Vs Chrome Vs Firefox)

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1737]
Just a comparison i did on the following site :
http://www.speed-battle.com/speedtest_e.php

Firefox : 

![firefox](https://cloud.githubusercontent.com/assets/17910355/15261984/3e3e11fe-1968-11e6-90ae-52baab6c177e.PNG)

Chrome:

![chrome](https://cloud.githubusercontent.com/assets/17910355/15261987/44610b36-1968-11e6-99e5-bf39e59ace78.PNG)

Brave:

![brave](https://cloud.githubusercontent.com/assets/17910355/15261993/4c120fa6-1968-11e6-88af-f6b5a6a2c86f.PNG)

/Haze

**Comment by luixxiul** [comment]
Nice!

**Comment by kenorb** [comment]
I've 886.13 for Brave, 707.8 for Chrome (in terms of Overall Score).

**Comment by bbondy** [comment]
Since I think there are no action items here I will close this. I think between Chrome and us for these tests they should be similar, maybe different only because of variance.  If there's a particular thing we fail on consistently though then let's open an issue on it to find out why.
