### ISSUE TITLE
Bookmarks Name are changed when opened.

### ISSUE THREAD

**Issue by decode-dev** [brave/browser-laptop#1738]
Bookmarks names are changed according to the Site, which makes the bookmark's toolbar look clumsy and also unable to see the Bookmark Name except some dots in that place.
This is solved by removing the bookmark.
Attaching the Picture for more information

Brave Version :  0.9.5
OS : Win 8.1 ProWMC 64bit

![bkme](https://cloud.githubusercontent.com/assets/6382146/15262127/00b05e8a-197e-11e6-9f14-6d077ca1e128.png)

**Comment by luixxiul** [comment]
@bbondy How do you think? To make the bookmark bar scrollable could be one of the solutions.

**Comment by bbondy** [comment]
> Bookmarks names are changed according to the Site,

What do you suggest instead?

Please note I have this posted which may cover your concerns with the ... dots
https://github.com/brave/browser-laptop/issues/1743

**Comment by decode-dev** [comment]
@bbondy 
So what should be done.
Hide the Bookmarks Toolbar or any other fix for this problem?

**Comment by luixxiul** [comment]
Or set the max number of bookmarks which appear on the toolbar. In this case, if a user has more than that, the browser should group them and make a pull down automatically.

**Comment by decode-dev** [comment]
@luixxiul 
It already does the pull down when the there are more bookmarks that cannot be placed in the Toolbar.
But the problem is Names of the Bookmarks.
I guess the problem is this :

- Bookmark Names are Saved.
- Overwritten when you open the bookmark.
- Trying to Update the Name each time you open.

**Comment by luixxiul** [comment]
I believe they are not overwritten. Right click on a bookmark, select "Edit Bookmark" and check "Title".

**Comment by decode-dev** [comment]
@luixxiul 
They are over-written by the SiteName / Repository Name / anything.
Suppose I saved the Gmail Login as "GM" in the bookmark Name but when opened it changes to "Gmail".

**Comment by luixxiul** [comment]
![](http://i.imgur.com/MGzHwcE.gif)

It remains "GM".

**Comment by decode-dev** [comment]
@luixxiul 
This is a erratic behaviour sometimes it does change or it become like the problem I mentioned.
Just updated to 0.9.6 which seems to be fixed the the issue.

**Comment by luixxiul** [comment]
I see, next time please attach GIF. LICECap is easy to use. thanks

**Comment by decode-dev** [comment]
@luixxiul 
Sure. Thanks
