### ISSUE TITLE
Fatal JS error on startup 0.7.1

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#174]
After this error, I had to quit and restart to use the app, at which point it was fine.
<img width="505" alt="screen shot 2016-01-16 at 9 46 37 pm" src="https://cloud.githubusercontent.com/assets/5495083/12375659/ed4ca14a-bc9a-11e5-9bd8-f0a2ff9de1f0.png">

**Comment by bridiver** [comment]
forgot to reference this bug, but should be fixed by https://github.com/brave/browser-laptop/commit/5b61a682cbedc9ff1cddd006b8f1492c370026ce

**Comment by bbondy** [comment]
We should do a release soon for this.
