### ISSUE TITLE
Bookmarks toolbar doesn't remain after browser restart

### ISSUE THREAD

**Issue by silverslimer** [brave/browser-laptop#1740]
The bookmarks toolbar needs to be re-activated after the browser is restarted and whatever was bookmarked onto it needs to be re-added as well.

**Comment by luixxiul** [comment]
Not reproducible on Windows 10. Would you please check if the browser was updated to the latest versionn and tell us steps to reproduce?

**Comment by silverslimer** [comment]
It was Windows 10 and Brave 0.9.5. I tried it now and it works fine. The browser must have unexpectedly closed without my noticing and somehow not saved the state of the bookmarks and their bar.

**Comment by luixxiul** [comment]
Okay, thanks for reporting.
