### ISSUE TITLE
Chrome bookmark import opens portal to hell...

### ISSUE THREAD

**Issue by GreenKite** [brave/browser-laptop#1741]
Bookmarks functionality is FUBAR for me - (I've imported my bookmarks from Chrome .html)

1) Not all bookmark bar bookmarks end up in the bookmarks bar.
2) Some bookmarks end up in new folders, and those folders got new names (usually a URL, sometimes some random searches I did on Amazon...)
3) As I type, bookmarks displayed names are changing in my bookmarks bar - at random - like something out of Ghostbusters.
4) I can only delete 1 bookmark in Bookmark Manager at a time; no 'Clear All' bookmarks functionality?
5) After deleting all bookmarks in Brave one-at-a-time, I was disappointed to learn that re-importing the bookmarks file (mybookmarks.html from Chrome) results in both duplication and even further FUBAR'ing of the folder structure, bookmark names, and locations.

Running:
Brave: 0.9.5
Electron: 0.37.8
libchromiumcontent: 50.0.2661.94
V8: 5.0.71.39
Node.js: 5.10.0
Update channel: dev

On my MacBook Air:
El Capitan 10.11.4

**Comment by luixxiul** [comment]
@bbondy would you please confirm these on Mac?

**Comment by bbondy** [comment]
I definitely haven't seen this n any OS including OS X.  Could you take a video or animtated gif of #3? 
LICEcap works well for that

Maybe I need a sample bookmarks file that reproduces.

**Comment by GreenKite** [comment]
Hey Bondy,
I'd be happy to share the exact bookmarks file with you that I used - but it doesn't look like .html uploads are supported here, though.

As a follow-up: this morning, the bookmarks in Brave browser have "re-organized" themselves in a manner that is much more consistent than yesterday at first import - odd behavior, but it's better than where I was yesterday; oh, and I upgraded this morning when Brave browser prompted me.

Thanks,
Danny

**Comment by bbondy** [comment]
Maybe just open the file in an editor (notepad in Windows), copy it and paste to a new gist
https://gist.github.com/
Then give us the link of the gist.

**Comment by luixxiul** [comment]
I'm not sure if this was really fixed. There might be something which causes it sometimes.

**Comment by garvankeeley** [comment]
We have support tickets from 10 days ago reporting this.
