### ISSUE TITLE
If bookmark is 3 characters or less do not collapse to ellipsis 

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1743]
Sometimes 3 characters or less bookmarks collapse to ...

**Comment by cezaraugusto** [comment]
@bbondy with few bookmarks it doesn't collapses (I don't have many). Is it still happening?

**Comment by bbondy** [comment]
yes you need lots to repro

**Comment by kqpham** [comment]
Hi there, is this issue fixed or can I attempt to tackle this issue ?
