### ISSUE TITLE
Fanboy adblock lists?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1744]
https://github.com/brave/browser-laptop/issues/1513#issuecomment-218921968

> How about using Fanboy lists too if possible? #1636 will be fixed by adding https://www.fanboy.co.nz/fanboy-japanese.txt

Any plan to use Fanboy adblock lists besides Easylist?

Ref: #1636, #1121

**Comment by bbondy** [comment]
I think this can be closed now with regional lists.
