### ISSUE TITLE
Bookmark not appear on the bookmark toolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1745]
Bookmark is not added on the bookmark toolbar (there should be one). Not sure actually added in the background.

Ubuntu 14.04

![](http://i.imgur.com/Z6g29dG.jpg)

Latest commit: https://github.com/brave/browser-laptop/commit/d9b02538b1abac9cfdf651cae6ad09d8b7d42686

**Comment by luixxiul** [comment]
Not reproducible anymore. You would encounter this error if you tried to bookmark pinned tabs. Maybe temporary. Closing for now.

**Comment by luixxiul** [comment]
Happening again. Bookmarking ``about:preferences`` from both the menu bar and the shortcut key, the bookmark does not appear on the bar.

**Comment by bbondy** [comment]
your profile is stored in ~/.config/brave

Is this still an issue?

**Comment by bbondy** [comment]
I can't reproduce on Ubuntu moving to 0.10.2 but let me know if this is a big problem.

**Comment by luixxiul** [comment]
I can't too for now. It might be related with the profile, which I think has been corrupted. I'll report as I see that again. Closing for now.
