### ISSUE TITLE
Sort languages in preferences for non english

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1747]
The placement of the languages follow the English sorting order even for different languages.
So you can have for example Anglais in French in the middle of the list.

**Comment by luixxiul** [comment]
Or we could follow the wikipedia sorting style.

How about this? 

- Automatically apply the translation according to the system preference.
- Let users change the language setting.

This might be better for those who don't understand English at all.

**Comment by bbondy** [comment]
it should already pick the right language depending on the OS language for the default.

If you know that it doesn't do this pls post a diff bug though.

**Comment by Liunkae** [comment]
Making a note of bbondy's comment on https://github.com/brave/browser-laptop/pull/4055#issuecomment-247746311:

> I think doing a sort within the render in react would be better because it would work with all langs
