### ISSUE TITLE
Make Issue and Pull Request templates

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1748]
As issues are flooding, some of which are duping, why don't we set up our issue and PR templates?

https://github.com/blog/2111-issue-and-pull-request-templates
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

What should be included in the issue template:

````
- [ ] Searched for the similar issue before submitting this one.

- Describe the issue you encounter (please keep it short)
- What should be achieved

- Platform
  - Win7, 8, 10? OS X? Linux(distro)?
- Version number of Brave
- Steps to reproduce
    1.
    2.
    3. 
- Link to screenshot (if needed)
- # of the issue which is/might be related
````

Maybe we should ask one to update to the latest version before submitting an issue, instead of asking the version number.

And in the PR template (ref: [CONTRIBUTING](https://github.com/brave/browser-laptop/blob/master/CONTRIBUTING.md)) as a checklist:

````
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one does not already exist.
- [ ] Recommended: For changes to javascript files, installed a [Standard](http://standardjs.com/) plugin for my preferred text editor in order to ensure code style consistency.
- [ ] Made commits in logical units. Ran `git rebase -i` to squash commits if needed.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Wrote commit messsage body as descriptive as necessary ([example](https://github.com/brave/browser-laptop/blob/master/CONTRIBUTING.md))
````

**Comment by diracdeltas** [comment]
Thanks, this is a great idea.
* I don't think type of problem is necessary. Many people aren't sure, and sometimes a bug report can be combinations of bug/suggestion/etc.
* Probably okay to consider BSD a subset of Linux in this case :)
* Need to write STR in full since people don't often know what it stands for

Maybe also a note that people should search for their issue before opening a duplicate

**Comment by luixxiul** [comment]
Thanks! I updated the list.

**Comment by diracdeltas** [comment]
Cool, added this in 085b7bb41bf329a847a21baa7422d875010fe3e2. I'm worried the templates markdown syntax is going to confuse some people, but we'll see how it goes.

**Comment by luixxiul** [comment]
Thanks @diracdeltas!

**Comment by bbondy** [comment]
This template is great.  

Thoughts on this minor suggestion?

I think I'd prefer to remove the checkbox and just leave a blank statement like:
I have searched for similar issues before submitting this one.

<img width="397" alt="screenshot 2016-05-16 22 34 28" src="https://cloud.githubusercontent.com/assets/831718/15309612/6636c62e-1bb6-11e6-894e-72846549cfd6.png">

**Comment by luixxiul** [comment]
yes, I agree with you

**Comment by diracdeltas** [comment]
cool, updated issues template to put questions in bold and get rid of checkbox

**Comment by luixxiul** [comment]
Thanks! much better :)

**Comment by FagnerMartinsBrack** [comment]
I know this is closed already , but here are additional good resources in case you want to get inspiration to build templates or improve it, jquery team gathered plenty of them: https://github.com/jquery/jquery/issues/2929.

**Comment by luixxiul** [comment]
Nice, I'll take a look, thanks :-)
