### ISSUE TITLE
page-down using space bar only works after clicking page content

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#175]
STR: click a link on a page, on new page hit space bar to page down.
RESULT: no response, until the content is clicked, space bar won't page down
EXPECTED: work like Safari, Firefox, Chrome: after clicking a link, space bar works to page-down

**Comment by psimyn** [comment]
@garvankeeley I think this is resolved now

**Comment by garvankeeley** [comment]
can no longer repro, closing
