### ISSUE TITLE
Ctrl-tab to switch from most-to-least recently used tab

### ISSUE THREAD

**Issue by ibukanov** [brave/browser-laptop#1753]
Currently in Brace Ctrl-tab just cycle among open tabs in the order as they appear on the screen. It would be nice if instead Ctrl-tab/Shift-Ctrl-tab navigated from most-to-least recently used tab order or in reverse. This way switching between 2-3 tabs that are actively used will be possible just by using Ctrl-tab. This is similar to what is available with Alt-tab/Command-tab that switches between application in most-to-least recently used order.

**Comment by Haze-Aulaian** [comment]
yep i agree

**Comment by jaydson** [comment]
I really miss this in others browsers as well.
AFAIK Firefox is the only one with this feature (available via `browser.ctrlTab.previews;true`).

**Comment by luixxiul** [comment]
I think this has been implemented already. CC @NejcZdovc for confirmation

**Comment by NejcZdovc** [comment]
@luixxiul I think that we are still switching tabs by added id (number). Last accessed time is only used when you close a tab.

**Comment by CliqueBait** [comment]
I like this idea. Would be very useful for me too. One thing though, since it's unusual behavior for a browser, it should probably be on a toggle in settings.

**Comment by NejcZdovc** [comment]
cc @bradleyrichter

**Comment by srirambv** [comment]
cc: @petemill

**Comment by sogasg** [comment]
This is currently the only issue that makes it impossible to switch to the Brave browser. I am often checking back to see if it's added because I want to switch over.

I hope you will add this option in the near future. Please....

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/how-to-get-mru-tab-order/16231/2

**Comment by realuser** [comment]
+1 I was really hoping Brave would have this to give me another reason to start actually integrating it into my daily browsing (I use several browsers and this also prevents me from using chrome heavily).  It's such an obvious feature request for power users

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/913
