### ISSUE TITLE
Bug: When quitting Brave there is still the chance that processes are staying in background

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#1756]
Windows 8.1 64 Bit here, when quitting Brave i still have from time to time Brave processes running in background after i close the browser.

Related with #1540

**Comment by bbondy** [comment]
This is with 0.9.6? Could you also confirm the processes were from 0.9.6 and not from 0.9.5?

**Comment by SJ-Diamond** [comment]
It is from 0.9.6

**Comment by SJ-Diamond** [comment]
Ok, after using the recent Brave version for a while longer i can say the following:

Have earlier done some regular downloads, and right after quitting Brave i see 3 process still staying around which do not vanish.

So my guess it has something to do with downloading?

**Comment by ParrotSlave** [comment]
It has been doing this for quite some time, and one of the processes is taking an extraordinary amount of memory for a process that should not be running. This is also a Win8.1/64-bit. I have yet to find an instance in which it does not occur. I also note--a separate issue--that Brave still downloads files without adding a file extension.   
![brave still running](https://cloud.githubusercontent.com/assets/18475351/15271964/a1963dba-1a28-11e6-96bb-50db6308f39c.PNG)

**Comment by luixxiul** [comment]
I thought #1540 would have fixed this.

**Comment by ParrotSlave** [comment]
I forgot to mention the other day that it was with Brave 0.9.6 also. It still, on occasion, will close without leaving any running processes, but, most of the time, it leaves three, and that doesn't seem to be related to downloading anything. 
![brave version](https://cloud.githubusercontent.com/assets/18475351/15385163/4bcd55fe-1d65-11e6-8dd4-f32bb09cb6af.PNG)

**Comment by SJ-Diamond** [comment]
Happened also with 0.10.0 yesterday, the longer i browse the higher the chance is that if i quit Brave, 3 or 4 processes are staying in the background and not get closed properly.

System is Windows 8.1 - 64 Bit

**Comment by msp1111111** [comment]
Same with me. With versions after 0.9.6, sometimes it closed all processes properly, but sometimes not. Did some experimenting but I can't pin down what the trigger is for not closing.

Currently 0.10.0, Win 7 x64 - same behavior

**Comment by dogancelik** [comment]
I can confirm, I'm using Brave 0.10.0, Windows 8 64-bit
