### ISSUE TITLE
Option to choose fonts

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1757]
Options for displaying web pages and UI would be nice.

**Comment by BWV998** [comment]
I agree with you!

**Comment by bbondy** [comment]
How does this work with respect to HTML content? Does it only take effect when a font-size is not specified on pages?

**Comment by luixxiul** [comment]
Enabling a global option to select font-family might be enough

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5237

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5279

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5285

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5268

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5256

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5335

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5751

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5834

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5847

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6186

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6293

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6350

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6387

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6407

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6422

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6505

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6674

**Comment by Liunkae** [comment]
+1 from me. I like Firefox's font customization UI:
![image](https://cloud.githubusercontent.com/assets/19424103/23836857/ee325f0c-074c-11e7-9721-d6f5f421c11f.png)
![image](https://cloud.githubusercontent.com/assets/19424103/23836862/0138e8d2-074d-11e7-95b9-7a73c4436b6c.png)

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/change-the-default-font/3598

**Comment by eljuno** [comment]
+2 from community regarding ability to choose font type and font size https://community.brave.com/t/desperately-needs-a-minimum-font-size-feature/14983?u=eljuno

**Comment by bsclifton** [comment]
Closing as `wontfix` since we won't be able to address this with our current code-base. However, when we move to [Brave Core](), this is already fixed and working 😄 Here's a screenshot 

![screen shot 2018-08-06 at 1 58 35 pm](https://user-images.githubusercontent.com/4733304/43741343-e0836ef4-9982-11e8-8fe4-3ab9dc571bcc.png)

brave-core will ship in a few months- hang in there! 😄

**Comment by mlapoint1** [comment]
+1 for me as well!

I am 45 and have just entered the time in my life where I am needing bi-focals.  I also have another sight issue.

Thank You!

Mike LaPointe
