### ISSUE TITLE
New functions ideas (popup blocking, ad.fly bypassing, integrating keepass)

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1758]
Hi,

I am average Brave user. I love it for the speed! Can you also add
- popup blocking
- ad.fly itp. bypass
- interated keepass

Thanks!

**Comment by luixxiul** [comment]
Hi, as other password managers like 1Password and Dashlane are already supported, there could be a change for keepass too, right? @bbondy

**Comment by luixxiul** [comment]
ref: #1313

**Comment by sanecito** [comment]
+1 request for KeePass support

**Comment by bungabunga** [comment]
if you think of keepass support, please also think of supporting [passwordsafe](https://github.com/pwsafe/pwsafe), another great open source password manager, made by Bruce Schneier.

**Comment by mahescho** [comment]
+1 for KeePass integration

**Comment by luixxiul** [comment]
+1 from community

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of our community site.

https://community.brave.com/t/include-keepass-for-password-management/789

Let's continue to talk about the suggestion there 😄
