### ISSUE TITLE
Bug:problem with delete key on OSX

### ISSUE THREAD

**Issue by JohnKazz** [brave/browser-laptop#1760]
There are problems with the delete key on OSX , it is responding command like the backspace key, making it difficult to use.

**Comment by luixxiul** [comment]
CC: @bbondy Do you confirm this?

**Comment by bbondy** [comment]
On my MacBook Pro the backspace key is labeled Delete

<img width="490" alt="screenshot 2016-05-14 12 43 16" src="https://cloud.githubusercontent.com/assets/831718/15269585/72149d90-19d1-11e6-8109-6f8bf6ac5bef.png">

I assume this bug is for full sized keyboards though.

**Comment by luixxiul** [comment]
Because on my MBP in JP there is no backspace button and the delete button works as the backspace button on all of the other programms too, I think this works as it should. Closing.
