### ISSUE TITLE
remove "new tab" from history to fix back button

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1762]
This was a new tab but the back button is active. 

![image](https://cloud.githubusercontent.com/assets/13509546/15269890/0943784a-19c2-11e6-85b1-c6511558950f.png)

Another new tab, then a pasted page link:

https://linkmaker.itunes.apple.com/en-us/?country=us

Then pressing back button results in this:
![image](https://cloud.githubusercontent.com/assets/13509546/15269900/56993648-19c2-11e6-94e4-2ea9e6fc3683.png)

**Comment by bradleyrichter** [comment]
cc @bridiver

**Comment by bbondy** [comment]
I think we actually want the current behavior.

**Comment by bradleyrichter** [comment]
Chrome does have this same behavior. Firefox and Safari do not.

I prefer Firefox on this one but happy to hear a good reason to leave it as is.

**Comment by bbondy** [comment]
one good reason is because it is "as is" :)

**Comment by bbondy** [comment]
meaning let's justify the change more, because it requires a change from what we already have.

**Comment by bradleyrichter** [comment]
sure...put it on LP and see if we hear more negative feedback. I came from Firefox so it felt broken to me. In theory, we will have more chrome switchers but they may also think it was broken.  :   )

**Comment by bridiver** [comment]
had a discussion with @bbondy about which `about` pages should or should not appear in history. These are the ones we talked about leaving out: about:safebrowsing, about:error, about:certerror

**Comment by bsclifton** [comment]
Skimming through issues and saw this... per @bridiver's comment, we do want to leave out particular about pages. That issue is captured with https://github.com/brave/browser-laptop/issues/2856

I went ahead and relabelled this one as suggestion for now

**Comment by paJFJ** [comment]
i would feel strong to exclude the "new tab" page from history too (i am also a former firefox user). would also volunteer to implement, was this suggestion already rejected? @bradleyrichter

**Comment by bradleyrichter** [comment]
@paJFJ not rejected, just not high priority. You are welcome to take a swing at it. I will be happy and so will all of our FX converts. (someone should fix this "bug" on chrome too. ;  )
