### ISSUE TITLE
Tabbing (tab selection) through list of URLs rather than jumping to webpage elements

### ISSUE THREAD

**Issue by matt961** [brave/browser-laptop#1764]
| Image 1 ![is0](https://cloud.githubusercontent.com/assets/11224476/15270844/9e618b5e-19e2-11e6-84d0-c901968df547.png) |
| --- |

| Image 2 ![is1](https://cloud.githubusercontent.com/assets/11224476/15270845/9e62e562-19e2-11e6-8b85-2a94945deae5.png) |
| --- |

Rather than selecting the first document object, it would be great if it selected the top link in the suggestions box for easier keyboard navigation.

**Comment by luixxiul** [comment]
I'm not sure whether selecting autocomplete URL with ``tab`` key is normal for most people (I select one with arrow keys). How do you think @bradleyrichter ?

**Comment by matt961** [comment]
>I'm not sure whether selecting autocomplete URL with tab key is normal for most people (I select one with arrow keys). How do you think @bradleyrichter ?

Firefox allows you to do this (and has since Firefox 25, as far as I know).

**Comment by alexwykoff** [comment]
Shipped
