### ISSUE TITLE
All images on webtoons.com are blocked

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1765]
https://github.com/brave/browser-laptop/issues/984#issuecomment-191872538
> There is some bugs with image too. http://www.webtoons.com/en/ It blocks all image.

Confirmed. CC'ing @diracdeltas @bbondy

**Comment by luixxiul** [comment]
Is there other way of handling such a issue than adding domains manually? :worried:

**Comment by bbondy** [comment]
There is by not having referrer blocking but this is a nice privacy feature to have. So we enable everywhere except where it causes problems.

**Comment by diracdeltas** [comment]
we could make the list shorter by matching on parent domain instead of exact domain for the exceptions
