### ISSUE TITLE
Scroll position should be restored

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1766]
Scroll position should be restored after going back/forward.

related with #1383, #1106, #930, also #963?

**Comment by luixxiul** [comment]
This one was requested by a user from support too

**Comment by bradleyrichter** [comment]
Confirmed through dogfooding. Needs fixing.

**Comment by Liunkae** [comment]
I'm no longer seeing this issue in 0.11.1. Could someone else confirm that it's fixed and close the issue if necessary?

**Comment by luixxiul** [comment]
the new milestone was set to 1.0.0

**Comment by Liunkae** [comment]
I'm sorry if I wasn't clear. I meant that, from my testing, I think the problem has already been fixed in 0.11.1 or earlier. If someone else could confirm that the problem is fixed, this issue can be closed.

**Comment by luixxiul** [comment]
Ah sorry, I misunderstood. I think the issue still exists on duckduckgo.com, etc.

**Comment by willy-b** [comment]
FYI, I can't reproduce this on the duckduckgo.com search results page.

Tested scrolling down in the results, then navigating back a page and forward again, which returned me to the same scroll position as before.

Does anyone have a page for which this problem occurs consistently?

**Comment by luixxiul** [comment]
duckduckgo.com has replaced the infinite scroll with pages, I think that's the reason.

**Comment by Liunkae** [comment]
So this issue only occurs now with pages with infinite scrolling?

**Comment by luixxiul** [comment]
I think this issue has been fixed on duckduckgo.com and other sites.

Let's reopen if we find steps to reproduce the issue 😉
