### ISSUE TITLE
Accidentally closing out all tabs! Need warning

### ISSUE THREAD

**Issue by something99** [brave/browser-laptop#1767]
When you open more than 10 tabs the next one appears on its own rather than just moving over one so you can scroll back to the first, it's like flipping a page in a book and starting over. That confuses me to no end. I keep thinking it opened a new window instead of a tab, Xing out and losing everything I was looking at. 

Why is there no warning before Xing out all tabs? Please add this as a feature. You can make it an option in case some people don't want it but I find it necessary to prevent accidentally losing my place. Doesn't help that there's no 'reopen last closed window' command.

**Comment by luixxiul** [comment]
Reported on #854, #1639.
