### ISSUE TITLE
Feature suggestion: Power saving feature

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#1770]
Opera is at the process of adding some power saving feature which is especially important for Laptops.

As mobile usage (Laptops/Tablets) is heavy on the rise i am sure Brave would benefit a lot from such a feature too.

**Comment by jonathansampson** [comment]
We are aiming to improve power usage with each build, and will soon be keeping a running look at our relative progress over prior releases. I'm closing this issue now, however, on the basis of its age, and lack of activity. Rest assured, the sentiment here is loud and clear, and we'll do everything we can to improve.
