### ISSUE TITLE
Audio indicator on/off button

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1776]
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

![youtube](https://cloud.githubusercontent.com/assets/3362943/15279443/6b87d930-1b5f-11e6-982b-ec2ad214436c.gif)

You have to change where to click in order to mute and unmute audio

## Test plan

1. Play a youtube video
2. Click the indicator to mute
3. Click the same place to unmute

**Comment by AkshayTiwari** [comment]
I'd love to try working on this. 
Can you help me with the files for this? I'll try fixing this. @bbondy

**Comment by Liunkae** [comment]
@AkshayTiwari [browser-laptop/less/tabs.less](https://github.com/brave/browser-laptop/blob/master/less/tabs.less) is the file, and `.audioPlaybackActive` is the stylesheet element.

**Comment by luixxiul** [comment]
The latest is a correct one.

**Comment by cezaraugusto** [comment]
This was also addressed on #6900

**Comment by luixxiul** [comment]
Sweet!
