### ISSUE TITLE
Bug : new opened brave.exe process

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1777]
Hello Dev Team,

to explain in simple.

![system-template](https://cloud.githubusercontent.com/assets/17910355/15286341/182f696e-1b65-11e6-9f37-d7466f924869.png)
- i have an existing brave browser window open and like any other browser if you try to open the Exe it should generate a new browser window with 1 blank tab.
- this is not the case with brave.
  -So in the below screen shot i have 9 brave exe processes running:

![newexebug](https://cloud.githubusercontent.com/assets/17910355/15286200/464e956e-1b64-11e6-88bb-c9e32ad730eb.png)

Now i try to open a new one from the task bar or from the shortcut/start menu/etc new exes are added to the taskmanager and nothing new appears on the screen:

![newexebug2](https://cloud.githubusercontent.com/assets/17910355/15286219/63c56064-1b64-11e6-8b3b-59f13f218f88.png)

Regards
/Haze

**Comment by cezaraugusto** [comment]
@Haze-Aulaian could you confirm if it still happens with the current version?

**Comment by luixxiul** [comment]
I'm going to close this as it is stale and the issue is thought to have been fixed..
