### ISSUE TITLE
Bug : windows taskbar process capture

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1778]
Hello Dev Team,

![system-template](https://cloud.githubusercontent.com/assets/17910355/15286575/8d7221ac-1b66-11e6-8e61-802cafb44ee2.png)

-So i noticed that after i have pinned and unpinned the browser process and did what i did to repro #1777.
Now i see that a new Brave icon is appearing the taskbar.
-As part of the behavior in windows when you pin an app and its not running , an icon should appear in the taskbar.
-Now if you click on the icon windows will automatically capture that icon and replace it with active process type with expanded box as below:

-Im taking winamp as an example.
-Before running winamp:

![winamp1](https://cloud.githubusercontent.com/assets/17910355/15286714/4299e27c-1b67-11e6-9c87-7157657e7441.PNG)

-After running winamp:

![winamp2](https://cloud.githubusercontent.com/assets/17910355/15286719/44e7f712-1b67-11e6-8037-cd354b675ab6.PNG)

-but this is not the case with brave now.
-Its showing an independent taskbar process and even if i close it and open it again it will open a new one in the taskbar leaving the original brave icon untouched:

![taskbarbug](https://cloud.githubusercontent.com/assets/17910355/15286735/5970de38-1b67-11e6-8a13-8ce8459ed02b.PNG)

Regards,
/Haze

**Comment by Haze-Aulaian** [comment]
I think this is somehow related to #1540

**Comment by luixxiul** [comment]
@Haze-Aulaian, thanks for the report :-)
