### ISSUE TITLE
Switching tabs sometimes causes the browser to become completely blank

### ISSUE THREAD

**Issue by silverslimer** [brave/browser-laptop#1782]
I can't tell you what exactly causes the issue but the last time it happened, it was because I switched from a tab which contained my theoldreader.com feed onto a tab with my Facebook profile. The whole browser becomes white, blank, and nothing can be done except close it.

**Comment by Haze-Aulaian** [comment]
this has been mentioned in #1671 , i guess its the same issue 
@bbondy @diracdeltas

**Comment by diracdeltas** [comment]
may be slightly different, since @silverslimer says this was triggered by tag switch instead of drag and drop

**Comment by Liunkae** [comment]
See https://github.com/brave/browser-laptop/issues?q=is%3Aopen+is%3Aissue+label%3Abug%2Fdriver for related white screen issues.

No recent reports. Closing.
