### ISSUE TITLE
context menus break on new session tabs (0.9.6)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1785]
![image](https://cloud.githubusercontent.com/assets/13509546/15295627/3f278912-1b46-11e6-983c-cec3aa78006c.png)

@bbondy @bridiver

**Comment by luixxiul** [comment]
Not appearing on the build based on the latest commit https://github.com/brave/browser-laptop/commit/9ec8d4d1a34de6c98b63301962db9ded2006d041

**Comment by bridiver** [comment]
I'm also not about to reproduce. Is there a specific url this happens on @bradleyrichter ?

**Comment by bradleyrichter** [comment]
closing and keeping an eye on it after next release...
