### ISSUE TITLE
deleting database broken on fmphost.com

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1786]
bug reporter at support@brave says this works in chrome but not in brave.
```
The button in the service triggers a javascript function — I guess one that is defined locally: "deleteDatabase" with 2 parameters, something that looks like the service's ID for the database, and the server address.
```

I don't have an fmphost account to test this out; if anyone does, please copy any console errors.

**Comment by diracdeltas** [comment]
Appears that the problem is that `deleteDatabase` calls `window.confirm`, which only works sometimes in Brave

**Comment by diracdeltas** [comment]
got it to happen by:
1. cleaned session store. verified that going to fmphost.com and calling window.confirm worked as expected.
2. logged into fmphost and was redirected to https://my.fmphost.com/clientarea.php. window.confirm no longer works; console says `window.confirm`  is `function confirm() { [native code] }`.
3. reloaded the page. now console says `window.confirm` is `function (message, title) {
    return ipc.sendSync('window-confirm', message, title);
  }` as expected.

cc @bridiver @bbondy

**Comment by diracdeltas** [comment]
actually it just looks like `window.confirm` isn't being set correctly after navigation. ex: go to bing.com, click on any link to navigate, and window.confirm is broken.

**Comment by bridiver** [comment]
I think a change in chromium 50 broke this. The window functions won't be reloaded if a new render frame is not created

**Comment by bridiver** [comment]
fixed https://github.com/brave/electron/commit/22312fc98e546e44d522dbfc7cf4fbf759dc6264

**Comment by BrendanEich** [comment]
Any way to add a regression test for this? Thanks.

**Comment by diracdeltas** [comment]
sure i'll add a test for this
