### ISSUE TITLE
Spell check should work in languages other than English

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1788]
**Describe the issue you encountered:** Spell checking does not work on Windows 10, whose region is set to Japan and language to Japanese

**Expected behavior:** If the language setting of Brave is set to English, spell checking in English should work, regardless of OS language setting

- Platform: Windows 10
- Brave Version: 0.9.6
- Steps to reproduce
    1. Change the language setting of Windows to Japanese (if you do understand Japanese)
    2. Reboot and run Brave
    3. Go to http://www.pastebin.ca/ and type something
- Screenshot (if needed)
    - ![](https://cloud.githubusercontent.com/assets/3362943/15309413/c799cffe-1c21-11e6-9b2e-88676ff97b08.jpg)
- Any related issues: #859

**Comment by gabriellemary** [comment]
My language is set to Dutch (Nederlands) on Brave and Windows 10, but I can't work out how to get the Dutch spell check to work (extra question: sometimes I have to write in French, is it possible to have multiple dictionaries?...)
