### ISSUE TITLE
Make autocomplete use history

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#179]
Here I am typing "fin" for finance.google.ca, and the only autocomplete suggestion is huffingtonpost:

<img width="1194" alt="screenshot 2016-01-17 16 00 55" src="https://cloud.githubusercontent.com/assets/5495083/12379950/a46f373c-bd33-11e5-95fd-4c355e69d613.png">

**Comment by diracdeltas** [comment]
@bbondy are you working on autocomplete with browser history or should i take it?

**Comment by bbondy** [comment]
I'm not but I think it's worth talking about a bit design wise first. What is your plan for it? I think just storing in app state will cause lag over time due to it growing too large.  We did have it that way in the old browser repo though in app data sites. Should we have a whole different storage "store" for this and support querying subsets of it? or?

**Comment by diracdeltas** [comment]
I was thinking a separate store with entries like:
```
{
  sites: [{
    url: string,
    description: string, // the string that is searched for a match; ex: "brave.com - A faster browser"
    lastAccessed: datetime,
    partitionNumber: number
  }]
}
```

Probably only the ~500 most recent entries need to be in this store for autocomplete. `about:history` could read from disk to find older entries.

**Comment by bbondy** [comment]
I like the idea of treating this separate than history.
I think we can re-use appStore for this though if we limit to 500 entries.
I think we can optimize it as well by only sending differentials for state updates for the subparts of appState.

**Comment by bbondy** [comment]
would visit count be useful as well?

**Comment by diracdeltas** [comment]
Cool, I wasn't sure what the size limit of appStore is.

Not sure about visit count - i feel like sorting by timestamp is sufficient

**Comment by bbondy** [comment]
++ I think putting it directly into the already existing sites is fine for this.  There's a subtask fro getting partitionNumber inside sites, you could do that first as a step towards this.  (note this will have an effect on pinned tabs as well).

**Comment by bbondy** [comment]
deleting out old items that are not used would only be done for items without tags associated with it.

**Comment by bbondy** [comment]
Session store save seems like a good time to sort by last accessed date without tabs, and limit to first Config.maxSites + sites w/ tags.
