### ISSUE TITLE
content script event handlers don't work inside sandboxed iframe

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1791]
If you iframe a document with the `sandbox` attribute (not set to `allow-scripts`), event handlers registered in the Brave content script don't work. To repro:
1. go to http://web.mit.edu/zyan/Public/slashdot.html 
2. try right clicking in the iframe
3. instead of opening a context menu, the console logs an error:
```
slashdot.org/:1 Blocked script execution in 'https://slashdot.org/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set
```

Note that the content script itself will run, just not the event handlers added with `document.addEventListener`.

**Comment by diracdeltas** [comment]
this is not a security issue since #1790 has an easy workaround, but somewhat annoying because content script functionality (context menus, keybindings, password fill, ad replacement, etc.) will not work on sandboxed iframes. cc @bridiver

**Comment by bridiver** [comment]
I think we can fix this by implementing ShowContextMenu in CommonWebContentsDelegate. We can emit the context-menu-opened event from there and it appears to provide everything we need in ContextMenuParams

**Comment by bbondy** [comment]
didn't electron already add that? They expose a context-menu event now

**Comment by cmolocznik** [comment]
Here's a solution I created to workaround this issue. First determine if the content-script is being injected into an iframe. The problem is the iframe DOM element has already been initialized in the parent document. If the "sandbox" attribute has been set and "allow-scripts" isn't in it, then code injection into the "actual" document fails with the error you are running into. Remove the frame from the DOM and add "allow-scripts" to the "sandbox" attribute and put it back on the DOM.

```javascript
if (window.self !== window.top) {
    var iframe = window.frameElement;
    var parent = iframe.parentNode;

    var sandbox = iframe.getAttribute("sandbox");
    if (sandbox && sandbox.indexOf("allow-scripts") == -1) {
        // Stop iframe from loading.
        window.stop();

        // Save the nextSibling node so the iframe may be inserted back to where it originally was.
        var nextSibling = iframe.nextSibling;

        // Remove from DOM.
        parent.removeChild(iframe);

        // Add "allow-scripts" to sandbox.
        // It's important to inherit the original value so we add it onto the end.
        iframe.setAttribute("sandbox", sandbox === '' ? "allow-scripts" : sandbox + " allow-scripts");

        // Add back to DOM.
        if (nextSibling)
            parent.insertBefore(nextSibling);
        else
            parent.appendChild(iframe);

        // Revert sandbox back to original value.
        // Since it has already been added back onto the DOM, this won't change
        // the functionality. It makes it look as though nothing has changed.
        iframe.setAttribute("sandbox", sandbox);
    } else {
        document.documentElement.setAttribute('onreset', actualCode);
        document.documentElement.dispatchEvent(new CustomEvent('reset'));
        document.documentElement.removeAttribute('onreset');
    }
} else {
    document.documentElement.setAttribute('onreset', actualCode);
    document.documentElement.dispatchEvent(new CustomEvent('reset'));
    document.documentElement.removeAttribute('onreset');
}
```

**Comment by diracdeltas** [comment]
@cmolocznik thanks for the proposal. `window.frameElement` will be null for cross-origin iframes, so i think your solution won't work for those. you can get around that by having each window find all of its direct child frames and doing the sandbox modification on those, instead of having each frame try to modify its own sandbox. but then you can't call `window.stop` to stop the iframe load.

**Comment by bridiver** [comment]
looks like this works ok now. Are you still seeing it anywhere in master?

**Comment by diracdeltas** [comment]
confirmed fixed. thanks
