### ISSUE TITLE
window.confirm no longer works on about: pages

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1792]
- Describe the issue you encountered:
window.confirm works usually on regular pages but never on about: pages, it seems. this breaks clearing passwords on about:passwords.

- Platform
  - Win7, 8, 10? OS X? Linux(distro)?
osx

- Brave Version
git head, 0.9.6

- any related issues
#1786 #94

**Comment by bridiver** [comment]
fixed https://github.com/brave/electron/commit/22312fc98e546e44d522dbfc7cf4fbf759dc6264
