### ISSUE TITLE
feature suggestion: tab unloading from memory when not in use

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1796]
from #470 

> Problem is Chromium is a memory eater so it makes sense to have an option which makes tabs only loaded into memory when actually clicking on them, or the opposite when a tab is longer time not in use that it is unloaded out of memory until being reactivated again with clicking on it.

**Comment by petemill** [comment]
Superseded by https://github.com/brave/browser-laptop/issues/13210
