### ISSUE TITLE
"Error: Access is denied" on Windows 10

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1798]
From support /tickets/3896

**Describe the issue you encountered:**

> I´m having a problem to install Brave (lastest version) in windows 10 64 bits (see attached image) Any idea how to resolve it?

**Expected behavior:**
- Platform (Win7, 8, 10? OS X? Linux distro?): Windows 10
- Brave Version:
- Steps to reproduce:
- Screenshot if needed: 
  ![clipboard02](https://cloud.githubusercontent.com/assets/3362943/15364304/04895fb6-1d57-11e6-90e8-40903fcd5fba.jpg)
- Any related issues:

**Comment by luixxiul** [comment]
The reporter said he/she tried to install Brave since some month ago

**Comment by maxmaronna** [comment]
Hi Luixxiul, I tried the lastest version as well (same problem).
It looks like Brave is installed; when I tried to open, the aforementioned Screenshot came up...
thanks

**Comment by luixxiul** [comment]
OK I got it :-)

**Comment by cezaraugusto** [comment]
@luixxiul v10.2 was released with some Windows fixes. Does this problem still persists?

**Comment by bsclifton** [comment]
I got this when I tried upgrading (didn't confirm w/ latest version though). The only thing that fixed it for me was rebooting.  After that, upgrading worked fine :smile:

**Comment by luixxiul** [comment]
OK closing for now.

**Comment by maxmaronna** [comment]
In my case, I tried that option (installing latest version and rebooting) and same situation so far (I still have the error message)
![clipboard02](https://cloud.githubusercontent.com/assets/10718501/15869493/fddf8d5e-2cc2-11e6-91a7-7b766a21438d.png)
Best
max

**Comment by luixxiul** [comment]
Is this still reproducible?

**Comment by maxmaronna** [comment]
Hello
I put down that desktop, so I do not know...but in the new one is working
great
Best
max

2016-11-19 8:17 GMT-02:00 Suguru Hirahara <notifications@github.com>:
