### ISSUE TITLE
Memory Leak issue

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1799]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Memory leak
**Expected behavior:**
Nope
- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 7 32bit (no SP)
- Brave Version:
0.9.6 ia32

-Basically 17 tabs open.
-20 hours of usage.
-Brave memory usage is 1.2 Gig of ram . :/
-Getting the below error message:
![memory](https://cloud.githubusercontent.com/assets/17910355/15368126/ecf52726-1d34-11e6-88cf-081ae77e3935.PNG)

-This happened also on 0.9.6 64 bit version

**Comment by Banditz71** [comment]
Same issue here as well......except with much less time of usage prior to the problem.  ( Win 10, 64-bit, 8 GB )

**Comment by Haze-Aulaian** [comment]
btw i have never faced this with firefox , so it seems that brave consumes the memory faster.

**Comment by Banditz71** [comment]
Ditto............

**Comment by luixxiul** [comment]
@Haze-Aulaian How much does your machine have RAM?

**Comment by Banditz71** [comment]
For me,  8 GB.........

**Comment by luixxiul** [comment]
@Banditz71, And how many tabs?

**Comment by Banditz71** [comment]
16 normal.....8 pinned ( guess they're all equal? )

**Comment by luixxiul** [comment]
I think it's normal: #415

**Comment by bridiver** [comment]
I wouldn't say that it's normal, but I think this is a dup of #415
