### ISSUE TITLE
Preview of google drive file is not displayed

### ISSUE THREAD

**Issue by jrichardsz** [brave/browser-laptop#1801]
**Did you search for similar issues before submitting this one?**
Google does not show anything related to this issue
**Describe the issue you encountered:**
When I want preview a google drive file , a blank screen is displayed
**Expected behavior:**
Show a preview of file

- Platform:
Windows 7 Professional
- Brave Version: 0.9.6
- Steps to reproduce:
    1. Open a mail with a file attached
    2. Click on open
    3. Blank page is displayed

- Screenshot if needed:
Brave blank page:
![2016-05-18 17_32_30-zoomit zoom window](https://cloud.githubusercontent.com/assets/3322836/15377095/d2e447c4-1d1e-11e6-8f80-7ee6072dd42b.jpg)

Chrome Preview file
![success](https://cloud.githubusercontent.com/assets/3322836/15377138/10fe1706-1d1f-11e6-9038-0fd8b083936b.jpg)

- Any related issues:

**Comment by onmyouji** [comment]
Having the same problem with Brave 0.10.0 on Windows 7 64 bit.
