### ISSUE TITLE
fail download brave-v0.37.8-linux-ia32.zip error 404

### ISSUE THREAD

**Issue by kuboosoft** [brave/browser-laptop#1802]
I am compiling 'Brave' for 32bits in Fedora 23/24 but doesn't exist  

> "Error: GET http://brave.github.io/browser-laptop-releases/0.37.8/brave-v0.37.8-linux-ia32.zip returned 404"
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Fedora Linux 23/24 32bits
- Brave Version:
  0.9.6
- Steps to reproduce:
  1. npm install 
  2. npm run build-package
- Screenshot if needed:
  ![Image of Brave 32bits](http://s32.postimg.org/xfbcot745/error.png)

@bbondy can you help me? The problem is with https://github.com/brave/browser-laptop-releases ; or 32bits is dropped?

**Comment by posix4e** [comment]
Checkout http://storage.googleapis.com/posis-brave-mirror/ for a preview of 32 bit builds for linux
