### ISSUE TITLE
Scrolling momentum zooms page when switching tabs on OS X

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#1804]
When scrolling down or up a website, momentum means the page continues to move after being flicked. However, when switching tabs while this momentum scrolling is taking place, the tab and the next tab you switch to change zoom level.

**Expected behavior:**
The zoom level should remain constant
- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X 10.11 El Capitan

- Brave Version:
Brave: 0.9.6
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

**Comment by fiery-** [comment]
I noticed similar problem, when I click on a Google.com result, the whole page zooms out (result links become quite large), before the new page opens. 

I have the same system and version.

**Comment by bridiver** [comment]
I can't replicate in master. Probably fixed by https://github.com/brave/browser-laptop/commit/656746a45564e08f7a7ad08bce974ac688186502. Let me know if you see the problem after the next release. Thanks!
