### ISSUE TITLE
Brave (0.9.6) can't start without Internet

### ISSUE THREAD

**Issue by fiery-** [brave/browser-laptop#1805]
If you start Brave (0.9.6) on OS X (10.11.4) and there is no Internet connection (WiFi is Off), then browser shows only the Brave menu and a "Quit" command. If I connect the WiFi, Brave starts correctly (with all menus) and tries to contact amazonaws.com at each start. However, there are users that may not have Internet connection and still want to use the browser for a localhost web app.
- Brave Version (from brave.com):

```
Brave: 0.9.6
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev
```

BTW: Is contacting amazonaws.com, at each start, so important?

**Comment by diracdeltas** [comment]
I can't seem to repro this if i turn off wifi and start the browser. I don't think it's due to the aws downloads (needed to get data file updates for adblock, tracking protection, httpseverywhere, and safebrowsing), since those do not block the main process.

**Comment by bridiver** [comment]
I'm not able to replicate either

**Comment by luixxiul** [comment]
Me neither on Windwos 10.

**Comment by fiery-** [comment]
I created a [screen-recording](http://ionline.link/BraveStartProblem.mov), where I simulated the missing Internet through Little Snitch. It seems that Brave blocks the main UI thread until it receives its files from amazonaws. Actually, the initial problem appeared, without any intervention from Little Snitch. Browser was accessible, but only Brave->Quit menu was available.

I disabled all networks and Brave starts correctly, so it seems that this happens when system reports a Network interface without an Internet connection.

**Comment by fiery-** [comment]
Here is a [screen-recording](http://ionline.link/BraveMenu.mov) that shows exactly how Brave appears when started without an Internet connection. What I must add is that WiFi is off, but I have an active Ethernet connection hooked to an WiFi Extender that is not connected anywhere (router is off). This means that Brave looks for an active Network interface and then hangs on amazonaws connection. I agree, that this may not be a widespread scenario, but still may happen to some people.

The easiest way to reproduce it, is to install LittleSnitch to simulate a missing Internet connection on an active Network interface.

Here is the Brave version used in this recording:
```
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev
```

**Comment by bridiver** [comment]
I'll try later today. I started to install little snitch, but it wants me to reboot and I'm in the middle of something else.

**Comment by bridiver** [comment]
I'm not able to replicate this using little snitch either

**Comment by diracdeltas** [comment]
I can repro this by setting Tor as my system proxy. Brave runs if it's already started, but it won't start if Tor is the system proxy. However it does start if WiFi is disabled.

**Comment by diracdeltas** [comment]
I added the dev server URL (ex: localhost:8080) to my SOCKS proxy exceptions and Brave started just fine. It also always starts fine in production mode, as expected.

**Comment by bridiver** [comment]
@diracdeltas can you replicate with a release build or only in dev mode? Makes sense that it would cause a problem in dev because of the webpack dev server, but in production it's just a file

**Comment by diracdeltas** [comment]
@bridiver i could only replicate in dev mode. i don't know why it would happen in prod.

**Comment by luixxiul** [comment]
closing as this is stale
