### ISSUE TITLE
Brave (0.9.6 - OS X) doesn't save its window position

### ISSUE THREAD

**Issue by fiery-** [brave/browser-laptop#1806]
If you resize Brave (0.9.6) window on OS X (10.11.4) and align its left side to the left side of your display, then at each start Brave window aligns to the center (horizontally) of the display.

- Brave Version (from brave.com):
```
Brave: 0.9.6
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev
```

**Comment by luixxiul** [comment]
Closing in favour of #146
