### ISSUE TITLE
Back/Forward mouse buttons not working (Ubuntu)

### ISSUE THREAD

**Issue by ddaza** [brave/browser-laptop#1807]
**Describe the issue you encountered:**
Back/Forward mouse buttons not working 
**Expected behavior:**
Be able to navigate back and forward with a simple click. 
- Platform (Win7, 8, 10? OS X? Linux distro?):
Ubuntu
- Brave Version:
Brave: 0.9.6
- Steps to reproduce:
    1. Use a 5 button mouse. 
    2. Push the Back/Forward button

**Comment by luixxiul** [comment]
Not reproducible on Ubuntu. On which page do you encounter this issue?

**Comment by ddaza** [comment]
So I found a work-around for this thanks to Stackoverflow [here](https://askubuntu.com/questions/19569/how-can-i-assign-actions-to-all-my-mouse-buttons).

However the issue seems to be persistent. 

I ran my `xev` and made sure that my buttons where mapped correctly:

- Back button: 8
- Forward button: 9

The mouse button events don't create any response from the browser.

**Also**, 

This might be slightly related but when using `backspace` to go back in the history sometimes the browser history disappears. An easy way to test this is to go to a page with lots of page links (ie. wikipedia), go deep into a link chain and go back all the way to the beginning using backspace. The forward button/shortcut  is gone.

**Comment by R0binvd** [comment]
Same problem here, using xev the buttons are mapped to 8 and 9. but nothing happens in the brave browser (using the bin file or from source). 

using arch linux

**Comment by qdt2k2** [comment]
Sadly I have to confirm the issue being present over many recent revisions of Brave.
I'm on ~0.12 now and still back-forward buttons are not working (while any other browser is recognizing it). Same mouse on Windows Brave installation is recognized properly.
Distro: openSuse Leap 42.1 x86_64, DM - Plasma 5

**Comment by Liunkae** [comment]
Closing in favor of #3101, a broader issue.
