### ISSUE TITLE
"Feedback" function doesn't work

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1809]
Clicking on the menu, then Submit Feedback brings you to an empty tab with the URL
mailto:support+laptop@brave.com

Going in thru the toolbar Help tab has the same result.

**Comment by cfumante** [comment]
Dunno if this is a function of Github or Brave's process, but when I was
doing programming/data admin, an issue was not "closed" when the fix was
put into the next release. That is an intermediate step. The issue was
closed when it was released into the wild and verified to be fixed by
the reporter. 
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by diracdeltas** [comment]
@cfumante that's valid; but we close issues when fixed and verified by the code reviewer to avoid extra issue-triage work

**Comment by cfumante** [comment]
assumed, it was something like that, just disconcerting to see an issue
closed before retest.
 
Thanks for the quick response...
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
