### ISSUE TITLE
merge noscript siteinfo into the Bravery panel

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1813]
https://github.com/brave/browser-laptop/issues/1586#issuecomment-220461962

**Comment by diracdeltas** [comment]
Note that the site settings in the new Bravery panel are all persistent across restart (unless set in a private tab). NoScript is unique in that it should have options to allow for (1) the next page load only and (2) only until restart.

Though perhaps (1) is not necessary for most people; I usually only use (2).

**Comment by bradleyrichter** [comment]
@diracdeltas by chance would the site-specific nature of the panel settings also reduce the need for #2?

I would prefer to keep the panel settings limited to on/off indefinitely vs expiring. We can eventually ad 2nd level granularity but still on/off. 

If this script-blocking functionality is advanced enough and absolutely requires what you described above, maybe it deserves to be pulled out of the panel and almost treated like an extension?

**Comment by diracdeltas** [comment]
@bradleyrichter Unfortunately I think allowing non-persistently is a needed feature for noscript. It's part of what distinguishes our implementation from Chrome. https://twitter.com/bcrypt/status/728006003908714496

I was thinking the script-blocking panel could be another panel that expands from the Bravery panel; otherwise people might be confused why there's two independent panels where they can enable/disable script blocking.

**Comment by diracdeltas** [comment]
Thinking about this more, I think NoScript is a special case because people who use it will need to do lots of manual whitelisting in order to make sites usable. Maybe for now, keep the bravery panel as-is and just have the Allow Once button on the noscript icon dialog.

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-laptop/commit/ff7a4aee44aa005830bd16098ddaf786c2e4e150 addresses this in the way mentioned above, by just getting rid of the 'allow until restart' button (because there is currently no way to undo this setting except by restarting the browser).
