### ISSUE TITLE
Feature suggestion: Focus navbar input whenever 'about:newtab' frame gets active

### ISSUE THREAD

**Issue by sstefoss** [brave/browser-laptop#1814]
I usually open many tabs and i faced the problem that a new tab was active but the navbar input wasn't focused, so i had to open another new tab to have search ready. Or when i am navigating using `cmd + shift + }`/`cmd + shift + {` and face a new tab, it is quite useless without having the search input focused.

If you find it useful i can PR.

**Comment by bsclifton** [comment]
Closing as this behavior seems to have been fixed.  If you're experiencing this issue still, please re-open with steps to reproduce (so we can debug). Or submitting a broken test and PR would be very welcome :smile: Thanks!
