### ISSUE TITLE
Czech localization - review permissions

### ISSUE THREAD

**Issue by pafri** [brave/browser-laptop#1820]
Hi,

At the moment Czech language for Brave browser is fully translated on Transifex (translator: fri). It would be good to get the reviewer or coordinator permissions there for me to be able mark the strings as reviewed, when reviewed. Also I would like to ask for this: could you assign the rights of the coordinator/reviewer of Czech translation team to me?

Greetings, Pavel

**Comment by AkshayTiwari** [comment]
Hi Pavel, 
Share me your mail id, I'll give you the access to be the reviewer. :D

**Comment by pafri** [comment]
Now the GUI on Transifex is set to use the dialog for invitation of the users - via mail or their nickname, I think. Also fri or pavelfric AT seznam point cz should work.

**Comment by AkshayTiwari** [comment]
@pafri I've added you as reviewer. :D

**Comment by AkshayTiwari** [comment]
@luixxiul  You can close this now. :dancer:

**Comment by luixxiul** [comment]
OK fine :+1:
