### ISSUE TITLE
Stored passwords not saving

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#1822]
Passwords are not saving for sites.

**Expected behavior:**

Passwords should auto-populate login input controls and show in the about:passwords page

- Platform (Win7, 8, 10? OS X? Linux distro?):

OSX

- Brave Version:

master branch

**Comment by bridiver** [comment]
I'm not able to replicate this. Is there a specific site(s) you are seeing this on?

**Comment by aekeus** [comment]
https://trac.torproject.org/projects/tor/login was the page I tested on.

**Comment by bbondy** [comment]
seems to work for me too, can you check again?

**Comment by aekeus** [comment]
Yep, did. The passwords are being saved, but I am not seeing them in about:passwords. No errors in the console either.

**Comment by aekeus** [comment]
<img width="164" alt="screen shot 2016-05-20 at 12 23 20 pm" src="https://cloud.githubusercontent.com/assets/210240/15434610/ae677d7c-1e85-11e6-84e2-1ba8190ed966.png">
<img width="554" alt="screen shot 2016-05-20 at 12 23 54 pm" src="https://cloud.githubusercontent.com/assets/210240/15434622/bea343b0-1e85-11e6-8647-1cecaa39badd.png">

**Comment by bbondy** [comment]
It only happens if you press go to about:passwords directly in the url bar.
If you follow the link in preferences it works.

**Comment by aekeus** [comment]
Right, I was going directly to about:passwords from the URL bar

**Comment by aekeus** [comment]
Confirmed working in master.
