### ISSUE TITLE
Bravery defaults not carried forward from 0.9.6 to 0.10.0 

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#1823]
<img width="247" alt="screen shot 2016-05-20 at 10 06 57 am" src="https://cloud.githubusercontent.com/assets/210240/15430285/a3151a50-1e72-11e6-8d6e-79977bd7eac7.png">

<img width="472" alt="screen shot 2016-05-20 at 10 07 42 am" src="https://cloud.githubusercontent.com/assets/210240/15430302/bbc94f30-1e72-11e6-95bc-575410751ae7.png">

**Comment by bbondy** [comment]
Tested this and it was working. This was due to a testing error because we use different session store files for dev vs release.

**Comment by bbondy** [comment]
Please re-test in the RC though
