### ISSUE TITLE
Allow per site Bravery settings in private tabs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1824]
Per site Bravery settings are only available for non private tabs. This bug is to fix that.

**Comment by Haze-Aulaian** [comment]
@bbondy im not able to locate this in windows version , is this still in the upcoming release 0.10.1 or exist already ?

**Comment by decode-dev** [comment]
@Haze-Aulaian 
It exists in 0.10.0 release
![bp](https://cloud.githubusercontent.com/assets/6382146/15649218/94205c62-268d-11e6-9bb5-a110c1640134.gif)

**Comment by Haze-Aulaian** [comment]
@decode-dev  it was not obvious that the browser logo became interactive , thanks for the heads up

**Comment by bridiver** [comment]
this may "just work" now that regular and incognito contexts are properly linked. I'll take a look

**Comment by diracdeltas** [comment]
closed as part of https://github.com/brave/browser-laptop/issues/4468
