### ISSUE TITLE
Private tabs should use public per site settings but allow customization

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1825]
Private tabs should use per site settings as the default, and then allow you to customize from there. But the customizations should override the site settings.

**Comment by alexwykoff** [comment]
@srirambv could you confirm this is still an issue? Thanks!

**Comment by bsclifton** [comment]
This should have a been fixed a long time ago 😄 Private tabs inherit the public profile.  However, the customizations done are not persisted to disk (as would be expected for a private tab)
