### ISSUE TITLE
Bravery panel should show number of scripts blocked

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1833]
If noscript is on, it would be easy for the bravery panel to also show the number of scripts blocked. thoughts @bradleyrichter ?

**Comment by bradleyrichter** [comment]
Do you mean the panel should grow wider to display a readout and label when the "block scripts" switch is enabled?

**Comment by diracdeltas** [comment]
yep like what is done for Ads Blocked, Trackers Blocked, etc.

**Comment by bradleyrichter** [comment]
@diracdeltas 

![image](https://cloud.githubusercontent.com/assets/13509546/15441928/ab769348-1e92-11e6-976c-678e4e0dc032.png)

and disabled:

![image](https://cloud.githubusercontent.com/assets/13509546/15441954/d20be49a-1e92-11e6-8736-d93203b192b1.png)

**Comment by diracdeltas** [comment]
Thanks @bradleyrichter!

**Comment by luixxiul** [comment]
Closing this in favor of #1951
