### ISSUE TITLE
Search for "{{ selectedVariable }}" not working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1834]
**Describe the issue you encountered:** Search for "{{ selectedVariable }}" in the Menu does not work

**Expected behavior:** it should either work or be removed from there

- Platform (Win7, 8, 10? OS X? Linux distro?): Ubuntu 14.10

- Brave Version: Master branch (latest commit is https://github.com/brave/browser-laptop/commit/869bf25c61052f927903c1c286dc4f51566c1431)

- Steps to reproduce:
    1. Open Menu from "File" in the Menu bar

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/3362943/15437627/2fa6e77e-1f03-11e6-9419-0652b45f9e53.jpg)

- Any related issues:

**Comment by bbondy** [comment]
working for me. Is this with a dev build?

**Comment by luixxiul** [comment]
No, it was built from the source

**Comment by aekeus** [comment]
Fixed in e488ca8e64542457bcb873a5958ca6f1d9fe3258
