### ISSUE TITLE
Mouse gestures, keyboard shortcuts.

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#1835]
System: W10 x64 using Brave x86.

This is my first post on GitHub.

Feature request: I would like to have the ability to use mouse gestures just like Opera/Vivaldi, with the default gestures they have, and the ability to customize my own keyboard shortcuts just like Opera/Vivaldi can, so I can better navigate the web.

**Comment by SJ-Diamond** [comment]
Would be nice to have that features for power users, i very much agree with that idea. Hopefully you guys consider to implement that ideas.

**Comment by D0J0P** [comment]
Yes, in looking at smart design, there is software that can cater to both the power user and the average/casual user. The thing about Vivaldi is that is can do both, it looks clean and simple, but for those who want to dig in deeper and use the richer features, they are able to do so and aren't left out. That's smart design, and you could have that with Brave too. The thing I like about Brave is that it's fast and secure and private, and it's base, Electron, makes it so that it can have it's own features separate from Chromium and isn't too tied to it like Vivaldi is more or less, so if Brave could have all the features that Opera/Vivaldi have, then it would be the best of both worlds.

**Comment by luixxiul** [comment]
Duping to #1089
