### ISSUE TITLE
Addressbar autocomplete and menu bar.

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#1837]
It would be good to have an autocomplete feature in the addressbar. Also, i don't like how pressing alt + D to focus on the address bar also brings up the menu bar, which I'd like to keep more hidden unless I press alt.

**Comment by SJ-Diamond** [comment]
Auto complete.. That one is indeed a must have. Optionally of course, not by default ;)

**Comment by luixxiul** [comment]
Duping to #241, closing in favor of #1596
