### ISSUE TITLE
Downloads on os x go to ~/Library/Application Support/Brave/Downloads not ~/Downloads

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#184]
This is the incorrect default folder on OS X, downloads should default to ~/Downloads

**Comment by diracdeltas** [comment]
this is fixed by https://github.com/atom/electron/pull/4177/files, so downloads will be in the correct place once @bbondy updates electron-prebuilt to include that commit.

if it's worth it in the meantime, i can set the session download path to the user downloads folder.

**Comment by bbondy** [comment]
We'll update soon, so we can close this, or close once we upstream. @bridiver will be rebasing his window fixes on top of the coffeescript->JS conversion.

**Comment by diracdeltas** [comment]
Fixed in 0.7.10!

**Comment by bbondy** [comment]
:tada:
