### ISSUE TITLE
Speed Dial/New Tab Page

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#1846]
Something that would definitely be appreciated someday, and probably needed by many, is Brave's own Speed Dial/New Tab page. Every browser now has it, and it would be great if it generated thumbnails with the site's logo. Opera does a pretty good job of doing this. Vivaldi has some of the best SD thumbnails in it's default look. Custom background wallpapers for the SD/New Tab page would be great as well.

**Comment by luixxiul** [comment]
Closing in favor of #1363
