### ISSUE TITLE
Mouse gestures

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1847]
https://github.com/brave/browser-laptop/issues/1835#issue-156030032

> Feature request: I would like to have the ability to use mouse gestures just like Opera/Vivaldi, with the default gestures they have

+1 see also
https://community.brave.com/t/mouse-gestures-extensions/290

**Comment by alexwykoff** [comment]
Prioritizing to 1.2. We get a fair number of support questions about this and I am pretty sure we have at least 2 or 3 dupes floating around.

**Comment by filav** [comment]
dear, i also need to be able to cruise back/forward by clicking my mouse buttons. support for os x system trackpad gestures is needed too... thank you for saving our time.

**Comment by Alex0007** [comment]
Missing mouse gestures support like in FireGestures or crxMouse is the only thing, why i'm not using brave

**Comment by mvelez** [comment]
And "rocker gestures" to borrow from Opera's nomenclature, right-click/left-click goes back and left-click/right-click goes forward.

Presto era Opera was also smart enough that it would pick up that on a paginated site like a blog or a table with next/previous buttons that a mouse gesture would bring you forward to the next page.  I don't know why they haven't picked that up in the blink/chromium era.

Mouse gestures are a must have for my primary browser.

**Comment by evvvritt** [comment]
Sadly, OSX mouse gestures for history navigation are a must have for me as well. Hopefully they can be added soon, thanks

**Comment by snkoppenaal** [comment]
Would be great if an extension or something native would be added to support mouse gestures. Very popular feature for power users, also in Vivaldi.

**Comment by leighman** [comment]
This is the only thing keeping me on Opera over Brave!

**Comment by evvvritt** [comment]
Happy to discover macOS swipe gestures are now working for history navigation in `v0.19.95` :)

**Comment by srirambv** [comment]
+1 from @eiyey via https://github.com/brave/browser-laptop/issues/13009 for back/forward gestures
