### ISSUE TITLE
URL tooltip for items on bookmarks toolbar

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#1848]
Each item on the bookmarks toolbar could have a tooltip that shows the URL of the bookmark. Here is an example from Firefox:
![image](https://cloud.githubusercontent.com/assets/19424103/15446677/b1991056-1eed-11e6-9edc-aa3e593a9360.png)

**Comment by luixxiul** [comment]
On Ubuntu 14.10 the width of tooltips sometimes is not calculated correctly.

STR
1. Open some tabs and load pages
2. Hover on them very fast

![](https://cloud.githubusercontent.com/assets/3362943/15640683/8c94683e-2675-11e6-9710-8819e8f30b22.gif)
Here I got "added m..." instead of "New Tab"

**Comment by Liunkae** [comment]
How are the tooltips being rendered? (The system?) The issue likely is Ubuntu-specific.

**Comment by luixxiul** [comment]
Yes I agree. On WIndows 10 it's not reproducible. Isn't it possible to
render the tooltip after the length of URL is calculated?

On Wed, Jun 1, 2016 at 2:06 PM, Liunkae <notifications@github.com> wrote:

> How are the tooltips being rendered? (The system?) The issue likely is
> Ubuntu-specific.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/brave/browser-laptop/issues/1848#issuecomment-222893739>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADNQf8w49n0FKYSTlEvXUZq8Iw7-FQf8ks5qHRNSgaJpZM4IjtdB>
> .
>



-- 
Suguru Hirahara <luixxiul@gmail.com>

**Comment by luixxiul** [comment]
I can reproduce it on Lubuntu neither. It seems like the issue is specific to Unity.

**Comment by bbondy** [comment]
For the unity problem, I wonder if you can reproduce this with chrome with an html page? If so it should be chromium reported bug and not here.

**Comment by luixxiul** [comment]
I see, I'll try.

**Comment by luixxiul** [comment]
I noticed the issue has been fixed in Ubuntu 16.04.
