### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#1849]
I thought I wrote about this one already, but I would like it if there were a huge list of keyboard shortcuts that are customizable just like Vivaldi and old Opera/new Opera. This makes it very easy to navigate the web like I want to, and would make for fast navigation. They're really awesome once you get used to them, and when you get used to them, you do not want to go back to browsing the way you did before by clicking through everything all the time.

**Comment by luixxiul** [comment]
Hi @D0J0P, please discuss this topic on #1089, which is the oldest suggestion. Thanks :-)
