### ISSUE TITLE
Feature request : LastPass plugin

### ISSUE THREAD

**Issue by akteon** [brave/browser-laptop#1850]
Are you planning LastPass password manager integration? It's better than 1Password or Dashlane.

**Comment by dwglover55** [comment]
Having used Lastpass for several years, I would appreciate having this plugin available as well.

**Comment by akteon** [comment]
@Benjamski it's free features are the best on the market: https://lastpass.com/how-it-works/

**Comment by BCSWowbagger** [comment]
LastPass is not only planned, it's on the official calendar for near-future release, according to the Dev Timeline: https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline

If you're feeling daring, you could even take a crack at adding it yourself. From what I've read of the source code so far, Brave extensions are loaded by https://github.com/brave/browser-laptop/blob/master/app/extensions.js and housed in https://github.com/brave/browser-laptop/tree/master/app/extensions (the subdirectories there appear to be simple exact copies of the Chrome extension folders). It doesn't look terribly hard; theoretically, a hacker should just be able to replicate what the Brave team has already done with 1Pass and Dashlane, changing the relevant references as he goes.

I'm not sure, though; I am not affiliated with the team at all. Just a fan who really wants LastPass support!

**Comment by NikosEfthias** [comment]
are you planning to add externall apps or chrome extensions support in near future it would make lots of chrome users me including completely start using brave i guess. i just cannot use it entirely bevause of my chrome extensions @BCSWowbagger

**Comment by Benjamski** [comment]
@NikosEfthias You can find the development timeline [here](https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline) I think chrome extension support is in the works for all but I understand where your coming from. I've started experimenting with only using Brave for development testing and it's been great for that so far.

**Comment by Liunkae** [comment]
Added in #2316.

**Comment by luixxiul** [comment]
OK closing

**Comment by 0x80** [comment]
I'm new to Brave and I can't figure out how to get lastpass working. I've tried the lastpass universal installer for osx, but that didn't seem to tackle Brave. 

How do I enable this, or where can I find some docs?

Thanks

**Comment by dwglover55** [comment]
From the Brave browser Preferences:

Preferences > Security > Password and Forms > Password Manager

If installed, LassPast should be listed in the drop down menu. Select it and you're good to go.
