### ISSUE TITLE
Bug: Allow this time from the No-Script feature has no effect on a page

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#1852]
**Describe the issue you encountered:**
Want to whitelist a script only temporarily

**Expected behavior:**
Scripts should be activated temporarily

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 8.1, 64 Bit

- Brave Version:
0.10.0

- Steps to reproduce:
    1. Going to http://qupzilla.com/
    2. Try to use the no-script function "Allow this time"
    3. Even after countless page reloads the scripts are not whitelisted temporarily

**Comment by bbondy** [comment]
@diracdeltas btw I think this is similar to the bug I mentioned where allow once didn't load the youtube video no my site.  The generalized allow once functionality does work.  Example go to brianbondy.com, turn on script blocking from the bravery menu, and allow once. It mostly loads just not the youtube video as before.

**Comment by diracdeltas** [comment]
Sorry, that was due to faulty logic on my part. temporarily allowing scripts should work now.
