### ISSUE TITLE
Clicking "Retry [site]" on the "DNS address could not be found" error screen throws an exception

### ISSUE THREAD

**Issue by kanatzidis** [brave/browser-laptop#1853]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I tried to go to a website that could not be reached, and was taken to the "This site can’t be reached because server DNS address could not be found" page. I clicked the retry button, and the browser threw an exception (see attached screenshot).

**Expected behavior:**
The browser should retry the request.

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X 10.11.4

- Brave Version:
0.10.0

- Steps to reproduce:
    1. Navigate to a website with bad DNS (in my case http://devbug.ca/)
    2. Click "Retry [site]"
    3. Observe

- Screenshot if needed:
![screenshot 2016-05-21 09 52 16](https://cloud.githubusercontent.com/assets/806823/15449124/61d3b808-1f3a-11e6-8482-6ccc38114c2f.png)

- Any related issues:
N/A

**Comment by kanatzidis** [comment]
So this is interesting: If I try to reproduce this error using the link above, it works correctly. I was originally getting to that URL from twitter, so I thought maybe it had to do with a redirect, but if I paste the url (http://t.co/82itWplwG0) directly into Brave it still works properly. I can only reproduce the issue if I get there from the twitter page: https://twitter.com/__devbug. Hope that helps.

**Comment by hassanshaikley** [comment]
I am getting the same problem on my Mac. 

<img width="552" alt="screen shot 2016-05-28 at 12 10 51 pm" src="https://cloud.githubusercontent.com/assets/6746840/15629411/3e59521e-24cd-11e6-9dd2-a342d039aa38.png">

: /

**Comment by jkd00** [comment]
I'm also getting the same problem on OS X El Capitan.

![image](https://cloud.githubusercontent.com/assets/4303497/15773335/a9565046-2976-11e6-8f5b-f6a2b98ecae2.png)

Happens any time a site fails to load or respond.

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by kanatzidis** [comment]
Possibly. I haven't seen it in a long time.

**Comment by luixxiul** [comment]
Thanks, let me know if it starts happening again.

**Comment by visvanathan50** [comment]
This site can’t be reached
code.zafaaz.com’s server IP address could not be found.
Search Google for code zafaaz
ERR_NAME_NOT_RESOLVED
 How to solve it i tried more but didn't get  solution if anybody's knows pls let me know

**Comment by bsclifton** [comment]
@visvanathan50 please try with the new version of Brave (https://brave.com/download). If the problem still happens, let's open an issue here:
https://github.com/brave/brave-browser
