### ISSUE TITLE
Removing sites from history - `siteUtil` functionality

### ISSUE THREAD

**Issue by snird** [brave/browser-laptop#1856]
Coming to implement #1458 , I needed a way to remove a site from history.
Currently, on the `siteUtil` state, there is a function called `removeSite`, for convenience, here is it:

``` javascript
module.exports.removeSite = function (sites, siteDetail, tag) {
  const index = module.exports.getSiteIndex(sites, siteDetail, tag)
  if (index === -1) {
    return sites
  }
  const tags = sites.getIn([index, 'tags'])
  return sites.setIn([index, 'tags'], tags.toSet().remove(tag).toList())
}
```

It currently only removes tags from sites in the list (such as `bookmark` tag, which is the main thing this function is used for now, removing bookmarks).

sites without tags are sites saved in history, so there are these possibilities I had in mind, but I wanted someone who has a better grasp of the code to tell me which seems to be the best:
- Add the functionality of removing a site from history to this function, when there is not `tag` specified. This effectively makes the function have two responsibilities.
- Add a new function `removeHistorySite` that removes sites without tags from the map, but have the chance of being confusing in the future (naming)
- Refactor the current `removeSite` name to be `removeTag`, and make the `removeSite` function removes sites without tags from the map.

Sorry for being a hard to deal with contributor (:

**Comment by NejcZdovc** [comment]
This will be resolved in #9979, where we split sites object and it should be easy to manipulate history now.
