### ISSUE TITLE
Localization tracking bug

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1858]
**Describe the issue you encountered:** Although ``.properties`` files were translated on transifex and downloaded in the locale folder, some parts of the UI remain English.

**Expected behavior:** Every string which was translated should be displayed in the language, as soon as the translation files are found/renewed in the locales folder.

- Platform (Win7, 8, 10? OS X? Linux distro?): Ubuntu

- Brave Version: Master branch

- Steps to reproduce:
    1. Download ``.properties`` files of the translation from transifex
    1. Change the language setting into another language, for example Japanese
    2. Restart
    3. Download something

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/3362943/15451561/68d22b74-2004-11e6-8547-a1afa29aa324.jpg)

What remains in English:
- "New"
- "Zoom" 
- "New Tab"
- Urlbar placeholder 
- ~~"About Brave"~~

Any related issues: #1659

**Comment by luixxiul** [comment]
I found that concerning "About Brave" the string was not translated yet due to the grammatical difference. See #1659 and [menu.properties#L119](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/ja-JP/menu.properties#L119). Some work on [commonMenu.js#L297](https://github.com/brave/browser-laptop/blob/master/js/commonMenu.js#L297) is needed.

**Comment by luixxiul** [comment]
I have partly addressed the issue with #2629, #2612, #2597. Still there may be some others.

**Comment by luixxiul** [comment]
"New" and "Zoom" has been translated but not applied due to a bug #2638

**Comment by bbondy** [comment]
Would like this soon but moving to 0.11.3 for now. @luixxiul pls revolt if this was working on a previous version of Brave.

**Comment by bbondy** [comment]
I think this can be closed now, if so please re-set the milestone to nothing and close.

**Comment by luixxiul** [comment]
OK, let me check later

**Comment by luixxiul** [comment]
I confirmed #2638 was fixed, thank you @bridiver and @aekeus.

I found some untranslatable labels in contextMenus.js. WIll push a PR.
