### ISSUE TITLE
Mac: pinch-zoom zooms the chrome as well as the content

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#186]
STR: pinch zoom on a magic trackpad

<img width="635" alt="screenshot 2016-01-18 12 08 59" src="https://cloud.githubusercontent.com/assets/5495083/12397645/8180daba-bddc-11e5-99b8-dde7a8a40e49.png">

**Comment by elsehow** [comment]
sounds like that gesture is setting the [web frame zoom level](https://github.com/atom/electron/blob/master/docs/api/web-frame.md) in electron, where it should be setting the zoom level on the page only

**Comment by bbondy** [comment]
I think I can fix easily, I just need to be able to reproduce.
