### ISSUE TITLE
height of .newFrameButton

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1863]
``height`` of ``.newFrameButton`` should be set to the same value as ``font-size``. On OS X I confirmed it is ok, but on Windows 10 it should be better. Here is the demo:

![clipboard02](https://cloud.githubusercontent.com/assets/3362943/15453166/ccd3ac7e-2045-11e6-9eb8-8483ce3588dd.jpg)

**Comment by bbondy** [comment]
CC @bradleyrichter  for thoughts

**Comment by luixxiul** [comment]
I'm not sure well, but the difference of rendering of``font-family: helvetica;`` between operating systems might causes this
