### ISSUE TITLE
Store history into a separate file

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1864]
https://github.com/brave/browser-laptop/issues/1306#issuecomment-220822397

> And history, as well. Using Firefox as example, all three are in: _places.sqlite_ (bookmarks & history), _logins.json_ and _key3.db_ for the master password.
> Alternatively, a functionality like Firefox's "[Refresh Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings)".

**Comment by luixxiul** [comment]
This could let a case like #2732 not happening anymore

**Comment by luixxiul** [comment]
It's been fixed 👍

**Comment by bsclifton** [comment]
@luixxiul bookmarks and history are now split, but they aren't in different files (yet)

**Comment by luixxiul** [comment]
I thought so because I saw `History` file inside the profile folder, thanks for checking 😄
