### ISSUE TITLE
Unable to terminate brave after downloading exe file

### ISSUE THREAD

**Issue by Haze-Aulaian** [brave/browser-laptop#1865]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Trying to terminate brave but im unable.
**Expected behavior:**
Not sure
- Platform (Win7, 8, 10? OS X? Linux distro?):
- Brave Version:
![system-template](https://cloud.githubusercontent.com/assets/17910355/15453428/484968da-201e-11e6-896b-3d7642554c27.png)

- Steps to reproduce:
    1.Download brave.exe
    2.While the run prompt window appear try to close brave but im unable.
    3.Close the run prompt the brave closes by it self.

- Screenshot if needed:
![running process](https://cloud.githubusercontent.com/assets/17910355/15453434/745aa89e-201e-11e6-97d9-e4288ad17f0b.png)

- Any related issues:
Not sure.

**Comment by cezaraugusto** [comment]
Hi @Haze-Aulaian thanks for pointing. It seems to be fixed so I'm closing for now. Let me know if it persists.
