### ISSUE TITLE
Google maps interferes with the "create new private tab" key combination

### ISSUE THREAD

**Issue by kanatzidis** [brave/browser-laptop#1867]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While on Google Maps, I tried to open a new private tab using Cmd-Shift-P. Rather than open a new tab, it registered as a print command.

**Expected behavior:**
It should open a new private tab.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  OS X 10.11.4
- Brave Version:
  0.10.0
- Steps to reproduce:
  1. Navigate to https://maps.google.com
  2. Press Cmd-Shift-P
  3. Observe

**Comment by luixxiul** [comment]
Confirmed

**Comment by diracdeltas** [comment]
Similar bug in Firefox: cmd+shift+p does nothing in google maps but it opens a private window otherwise. we could switch to cmd+shift+n for private tabs like chrome does, but we were going to reserve that shortcut for new private window.

**Comment by kanatzidis** [comment]
I like Cmd-Shift-N for private window, not sure it's worth screwing around too much with UI/UX just to make one website work. It's not too difficult to work around this.

I didn't mind Cmd-Opt-T, why did you switch away from that?

Since this also happens in firefox I'd personally be inclined to say "screw it, won't fix", but I've never made anything as good as Brave so what do I know.

**Comment by diracdeltas** [comment]
> I didn't mind Cmd-Opt-T, why did you switch away from that? If that's not going to get assigned to something else it could be added back as an alternative key combo?

cmd+opt+t is used for a Romanian alphabet letter on Windows, IIRC. There is an issue for supporting keyboard shortcuts: #1374

**Comment by Liunkae** [comment]
This issue also occurs when writing a comment on a GitHub (github.com) issue.

**Comment by bsclifton** [comment]
Shortcut was changed to Cmd+Shift+N at some point
