### ISSUE TITLE
Windows 10 action center shows notifications using "BraveSoftware.Brave.browser" as the app name

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#1868]
## The issue
Per the tweet last nite by @jonathansampson
https://twitter.com/jonathansampson/status/734231207911641088

Web notifications now show in the Windows 10 action center with the name "BraveSoftware.Brave.browser".  This is done because electron uses the value set here:
https://github.com/brave/browser-laptop/blob/5278b03b33dcbad7d5098aa5011e86dc8afbbb60/app/windowsInit.js#L39

![2016-05-22](https://cloud.githubusercontent.com/assets/4733304/15455040/4681e778-1ffd-11e6-87ed-b69ae4809aa0.png)

## The proposed fix
Update the name which ends up being used for the action center to be the same as the name used for the Brave application.  Since this appears to be new behavior in Chromium (see https://bugs.chromium.org/p/chromium/issues/detail?id=516147), it's possible electron might need an update to expose a human readable application name (instead of using AppUserModelId).  The AppUserModelId used above was primarily set to make sure Windows groups the taskbar icons properly, using the same string (and we don't want to change that behavior).

**Comment by bsclifton** [comment]
Also per @jonathansampson, this is a great website to test notifications on demand:
http://www.bennish.net/web-notifications.html

**Comment by bbondy** [comment]
we use that same URL in the manual test cases we run before each release too: https://github.com/brave/browser-laptop/wiki/Manual-Tests

**Comment by jonathansampson** [comment]
That's where I got it 😊

**Comment by luixxiul** [comment]
Nice loop :-D

**Comment by bsclifton** [comment]
Looks like this is fixed! Per the [comment here](https://github.com/electron/electron/issues/5313#issuecomment-219960855) by @felixrieseberg, I believe the issue was solved with https://github.com/brave/browser-laptop/commit/82a2ac64b9897184cc01feac034c3051728a6490#diff-98f0ed24f8f0fed04b7949391f32909eL11

Like Felix says, Windows will be looking for any links (pinned or not) with the same AppUserModelId. Before, the app ID didn't match because the app gets packaged with Squirrel. Now that it does match, not only does pinning work properly (and not break on upgrade), the proper name "Brave" is associated with the link

![win10-action-center-fixed](https://cloud.githubusercontent.com/assets/4733304/16032089/72b145a2-31b7-11e6-90ca-2656107983de.png)

**Comment by felixrieseberg** [comment]
Just confirming that this is all exactly right!
