### ISSUE TITLE
Side Panel

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#1873]
One thing that I love about my favorite browsers, Vivaldi and Opera, is that they use a side panel on the left side of the screen(but it can be shifted to the right if you want), that has your bookmarks, downloads, notes, and history. It would be great to be able to have a side panel that you can toggle in and out that has all these things available. Makes it really easy to use and manage all your stuff within the browser, and given lots of options to organize, rename, edit, delete things, you could have a lot of customization possible to allow people to organize their info however they want, for easy and efficient browsing.

**Comment by Lennium** [comment]
Please implement that. As power user this is one feature i need, without that i can't make Brave my default.

**Comment by alexwykoff** [comment]
+ many from support / community

**Comment by srirambv** [comment]
+1 from communityyyyy https://community.brave.com/t/web-panel-in-brave/5710

**Comment by NumDeP** [comment]
It would be brilliant if you could improve on this - https://testpilot.firefox.com/experiments/tab-center/

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/464
