### ISSUE TITLE
HTTPS upgrades list is too complex to be user friendly

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1875]
*Steps t reproduce:*
1. Load cnn.com
2. Open the Bravery panel
3. Click on the HTTPS Upgrades number. 

Actual results:
```
Livefyre.com.xml: ["http://cdn.livefyre.com/Livefyre.js","http://cdn.livefyre.com/libs/Livefyre/v0.7.0/builds/245/Livefyre.min.js","http://cdn.livefyre.com/libs/fyre.conv/v3.0.0/livefyre.min.js"]
Facebook.net.xml: ["http://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.2","http://connect.facebook.net/en_US/sdk.js"]
Gigya.xml: ["http://cdn.gigya.com/js/gigya.js?apiKey=3_gtUbleJNtrRITgx-1mM_ci7GcIrH8xL9W_VfAbzSa4zpFrRwnpq_eYd8QTRkr7VC"]
```

Expected results:
Just a flat list of the HTTPS upgrades.

cc @diracdeltas

**Comment by diracdeltas** [comment]
The ruleset names are useful for bug reports when a site is broken due to HTTPS-E - what if I just stripped '.xml' from the end?

**Comment by bbondy** [comment]
Maybe we could just dump the more verbose info to the browser console when clicked? I think users just expect to see X simple resource locations there, where X is the number in the Bravery stat.

**Comment by diracdeltas** [comment]
sgtm
