### ISSUE TITLE
Unique Device ID's

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#1883]
please remove this

WebRTC Media Device Enumeration
 Unique Device ID's

http://www.browserleaks.com/webrtc

**Comment by luixxiul** [comment]
Duping to #260

**Comment by luixxiul** [comment]
Reopened for Unique Device ID of WebRTC Media Device Enumeration. Should we remove this? cc: @diracdeltas

**Comment by diracdeltas** [comment]
We can leave this open. Unique device IDs themselves are not a problem, but Brave does not uniquely set them between different browsing sessions, so they can be used for cross-session tracking. cf https://w3c.github.io/mediacapture-main/#def-constraint-deviceId

**Comment by diracdeltas** [comment]
Test page (try opening in different sessions in brave vs chrome): https://jsfiddle.net/22e4yfvg/

**Comment by luixxiul** [comment]
Confirmed, they are shared across sessions.

**Comment by diracdeltas** [comment]
@bridiver are you taking this? or @thealphanerd?

**Comment by diracdeltas** [comment]
ping on this

**Comment by bridiver** [comment]
yea, I can look at it. We also need to clear the device id when clearing other session data

**Comment by diracdeltas** [comment]
thx

**Comment by diracdeltas** [comment]
this seems to have been automatically fixed in the latest libchromium update. the device ids are not shared between sessions anymore, and they are reset on restart. i'll keep this open to track adding an option to clear the device ids along with other session data

**Comment by diracdeltas** [comment]
cf https://chromium.googlesource.com/chromium/src/+/4db1329e005388540eb07429ac97827ca9bc422b

**Comment by diracdeltas** [comment]
closing this and opening follow-up so QA knows this was actually fixed in 0.12.2. https://github.com/brave/browser-laptop/issues/4157

test plan: 
1. go to https://jsfiddle.net/22e4yfvg/ in regular, session, and incognito tabs. the device ids should be different in each.
2. restart browser; the device ID in the regular tab should be different from before.
