### ISSUE TITLE
AudioContext Fingerprints

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#1884]
Fingerprint Test Page
https://audiofingerprint.openwpm.com/

AudioContext Fingerprints
Canvas font detection
JS/CSS font detection
Flash font detection

**Comment by luixxiul** [comment]
Other than AudioContext Fingerprints are mentioned in #242

cc: @diracdeltas

**Comment by diracdeltas** [comment]
We could add audiocontext fingerprint blocking as a pref like canvas fingerprinting. I have not looked at it closely enough to determine severity - ex: OS fingerprinting vs unique user fingerprinting.

**Comment by diracdeltas** [comment]
Noting that this will probably be merged into #1876
