### ISSUE TITLE
Fail reloading on about:error

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1889]
**Describe the issue you encountered:** Pushing the ``Retry`` button on ``about:error`` page does not reload the page correctly. If there is a no tab except it, new tabs open as much as you push it, and if there is a tab (whether it is pinned or not), reloading process starts on that tab.

**Expected behavior:** Page reloading should be done on the same tab.

- Platform (Win7, 8, 10? OS X? Linux distro?): Windows  10

- Brave Version: 0.10.0

- Steps to reproduce:
    1. Open any page and pin it
    2. Open a new tab and load a URL like: https://labs.isecpartners.com/breadcrumbs/breadcrumbs.html
    3. Wait for ``connectionTimedOut``
    4. Click ``Retry``

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
https://github.com/brave/browser-laptop/commit/3aa5ce4f903de70009a7ff2b1656624cbbdffe78 is causing some strange behavior and if I go back to https://github.com/brave/browser-laptop/commit/061d3dffe1c349bc90e8c59309ba697f16e78848 I am not able to replicate the issue
