### ISSUE TITLE
drag-and-drop bookmarklet to navigation bar causes whitescreen

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1891]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
dragging and dropping a javascript: url to the navigation bar area (not the bookmarks toolbar) causes the browser to whitescreen. demo: open https://jsfiddle.net/r2ftho8k/ and drag the 'click me' link to the navbar.

**Expected behavior:**
nothing should happen

- Any related issues:
may be a regression of https://github.com/brave/browser-laptop/issues/259

**Comment by diracdeltas** [comment]
the top-level browser location is `about:blank` so not a security issue afaict

**Comment by diracdeltas** [comment]
I think loading `javascript:` does not fire the `will-navigate` event, so we can't filter out the URL in our `will-navigate` handler. Probably as an XSS-prevention mechanism, the browser autoredirects to `about:blank`. I have a quick workaround but would be safer to either add a custom cancelable event in Electron for all webcontent location changes, or fastidiously add drop handlers in the browser window area.

cc @bridiver @bbondy

**Comment by bridiver** [comment]
`will-navigate` is explicitly not fired for certain types of navigation, but the jsfiddle works just fine for me

**Comment by bridiver** [comment]
this is temporarily re-opened with https://github.com/brave/browser-laptop/commit/0d4098ffb8aed0d90dee60b38676b50a09739355 and will be closed again by https://github.com/brave/browser-laptop/pull/1917 when it is merged
