### ISSUE TITLE
about:error when previewing forum posts

### ISSUE THREAD

**Issue by SethClydesdale** [brave/browser-laptop#1892]
**Did you search for similar issues before submitting this one?** 
Yes, I couldn't find any that fit the problem I'm encountering.

**Describe the issue you encountered:** 
Whenever I preview messages on some forums I get an about:error page. Clicking the retry button takes me to the /post page, but doesn't resubmit the form data which causes me to lose everything I've written.

**Expected behavior:** 
I have no problems on Chrome, Firefox, etc.. When I click "preview" I preview the message without issues. If I do happen upon an error or click the "back button" on these said browsers, they allow me to resubmit the form data which prevents me from losing the content I wrote.

- Platform (Win7, 8, 10? OS X? Linux distro?): 
Win7

- Brave Version: 
I noticed this started happening on v0.10.0

- Steps to reproduce:
    1. Go to [this page](http://forumbeta.forumactif.com/post?f=5&mode=newtopic)
    2. Write something in the text editor
    3. Click the preview button ( or "prévisualiser" )

- Screenshot if needed:
The info above should be sufficient, if not let me know.

- Any related issues: 
Only seems to happen on this forum host in particular. ( forumactif ) Could be something on their side, but since it doesn't happen on any other browser I figured I'd report it to make sure, because I work on these forums a lot and like using Brave.

**Comment by luixxiul** [comment]
@SethClydesdale do you think this is related with #1889?

**Comment by SethClydesdale** [comment]
@luixxiul hmm yes, it does seem to be similar in regards to retrying. The only difference is that when I click retry it shows the page, however it doesn't resubmit my form data. I don't get "connectionTimedOut" but "an unexpected error has occurred".

Also, I figured something out ; when I block scripts, the problem I mentioned doesn't occur, so it appears to be something JavaScript related causing the about:error page to show, although I'm not sure what it is, yet.

**Comment by bridiver** [comment]
looks like a renderer process crash, but not sure why yet
