### ISSUE TITLE
update to hamburger menu

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#1893]
The Hamburger menu needs the next level of refinement, following Chrome as a guideline. 
- "New" submenu items come up to the top of the menu
- "New Session Tab changes to "New User Tab"
- Menu Bar toggle reminder (and action) is added for Windows and Linux only
- items are reordered

![image](https://cloud.githubusercontent.com/assets/13509546/15487940/320d51e2-2106-11e6-883f-387baccb5d73.png)

**Comment by bbondy** [comment]
As part of this all session tab references should also be changed to user tab.

**Comment by srirambv** [comment]
@bradleyrichter It would be nice to add the history option to list all closed tab(or at least the last 10 tabs) to the hamburger menu. Especially when the user has the hidden the toolbar and easy to go through the list rather than pressing the CTRL+SHIFT+T to get the exact closed window.

**Comment by rohanthacker** [comment]
Has this reached a stage where it can be implemented ? or is it still being spec'ed ?

**Comment by bsclifton** [comment]
@bradleyrichter anything left on this? I think we've implemented everything

**Comment by bradleyrichter** [comment]
fine to close. I'll make a new issue for @srirambv 's history request
