### ISSUE TITLE
pinned tabs are invisible if they don't have a favicon

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1894]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Inactive pinned tabs with no favicon are the same color as the tab background
 
**Expected behavior:**
Inactive pinned tabs should be visible even if there is no favicon

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X

- Brave Version:
master

- Steps to reproduce:
    1. Create an empty file `test.html`
    2. Open the file in Brave
    3. Pin the tab
    4. Select another tab

Pinned `test.html` exists, but is invisible

**Comment by luixxiul** [comment]
Confirmed on WIndows 10
