### ISSUE TITLE
better way to prevent main window navigation 

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1897]
https://github.com/brave/browser-laptop/blob/master/js/stores/appStore.js#L297 listens for the `will-navigate` event to block navigations of the main window, but there are ways to change the main window location without firing `will-navigate` (ex: #1891).

at minimum, there should be a drop handler in the main window area to prevent drag-and-drop navigation.

**Comment by bbondy** [comment]
should this be in 0.10.1?

**Comment by diracdeltas** [comment]
probably. i'll add it.

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/browser-laptop/pull/1917

**Comment by bradleyrichter** [comment]
@BrendanEich does this sound related to Catherine's blank UI issue?
