### ISSUE TITLE
1password integration does not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1901]
From support:

> I am trying to enable the 1password integration, but I keep getting this error message:
> Chrome is connected but its code signature could not be verified. 
> Filling and other features are disabled until this issue is resolved.

**Comment by bbondy** [comment]
Should be answered by this:
https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-use-1password

By the way that FAQ is useful for answering support in general and it helps to update periodically as needed or add new ones.
