### ISSUE TITLE
Retry after Connection Timeout throws error.

### ISSUE THREAD

**Issue by AkshayTiwari** [brave/browser-laptop#1906]
**Describe the issue you encountered:**
After a Website encounters Connection Timeout, When i click the retry button it throws error as shown in screenshots

**Expected behavior:**
Should refresh the page. 

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 10.
- Brave Version: 0.10.0

- Screenshot if needed:
![1](https://cloud.githubusercontent.com/assets/8322582/15515061/d2857c40-2209-11e6-8391-fc91de51a847.PNG)
![2](https://cloud.githubusercontent.com/assets/8322582/15515062/d28a0788-2209-11e6-8724-766d15046c09.PNG)

- Any related issues: #1923

**Comment by bbondy** [comment]
Retry should be fixed now, please let us know if it's still a problem. cc @bridiver
