### ISSUE TITLE
Bravery menu does not close when the urlbar is focused

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1910]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The Bravery menu does not close when the urlbar receives focus

**Expected behavior:**
The Bravery menu should close if any other component receives focus

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X + ?

- Brave Version:
master

- Steps to reproduce:
    1. Go to twitter.com
    2. Open the bravery menu
    3. Click in the urlbar

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
same as SiteInfo panel when you click the icon in the location bar.

**Comment by bbondy** [comment]
I think because it has an overlay that listens for clicks and that overlay is on top of content but not chrome.

**Comment by luixxiul** [comment]
Confirmed on Ubuntu too

**Comment by luixxiul** [comment]
The PR also fixes the issue with the siteinfo panel.
