### ISSUE TITLE
Hovering over a tab loads it immediately

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1916]
**Describe the issue you encountered:** Hovering over a tab loads it immediately changing URL on the URL bar, without previewing it. I'm not sure but I don't think it was implemented intentionally

**Expected behavior:** Only preview the tab

- Platform (Win7, 8, 10? OS X? Linux distro?): Ubuntu 14.10

- Brave Version: Master

- Steps to reproduce:
    1. Open two tabs
    2. Hover over them alternately

- Screenshot if needed:
![hover](https://cloud.githubusercontent.com/assets/3362943/15537148/b846c716-22af-11e6-8b81-eb8a223219ed.gif)

- Any related issues: Not sure. #1921?

**Comment by luixxiul** [comment]
Was this fixed with #1921, @bridiver? I cannot reproduce this one

**Comment by bridiver** [comment]
this is a temporary issue in master until the latest electron updates are pulled in. It will be fixed in the 0.10.1 release
