### ISSUE TITLE
Feature request: Open downloaded file without saving

### ISSUE THREAD

**Issue by Superbest** [brave/browser-laptop#1924]
Currently, if the user clicks on a file link, Brave downloads and saves the file to the disk.

Often a user may want to simply open the file once, look at it, and then be done with it - without going through the hassle of dealing with the save location dialog, thinking of a place to save the file, then opening this place, and remembering to delete the file after.

Internet Explorer has a download dialog that allows both saving and opening a file which takes care of this matter. Firefox used to have it, but removed it to protect careless users from themselves. An extension restores the functionality, and is fairly popular, demonstrating the demand for such a feature.

Since Brave does not fully support extensions yet, it's not really practical to make a Brave extension for this. Can the functionality be added natively (perhaps turned off by default to protect less knowledgeable users)?

**Comment by Sh1d0w** [comment]
@luixxiul This is really nice feature to have. If you do this a lot times per day, it becomes very tedious task to first download file, then it takes a few more clicks if you just want to open it.

Do you guys have any plans to implement this in the near upcoming releases?

Thanks

**Comment by Liunkae** [comment]
This would be a useful feature for users who download tons of documents/installers to read/use them once but don't want to clutter their downloads folder.

Here's how this would work (IMO):
1. Download the file to the temporary directory.
2. Allow the user to open the file.
3. Delete the temporary file(s) on browser close.

**Comment by luixxiul** [comment]
+1 from https://community.brave.com/t/download-and-run-option/7640?u=suguru

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/open-tif-file-instead-of-saving-as-download/13785/6

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/option-to-open-with-when-clicking-on-downloadable-link/17848

**Comment by eljuno** [comment]
+1s from community https://community.brave.com/t/always-open-file-type-for-downloads/415?u=eljuno
