### ISSUE TITLE
Autocomplete list for typing the address should display real addresses, not just titles.

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#1927]
I had this problem for some time since I started using Brave and it's annoying, but it was usable for most of the time. However finally I've found some example which can demonstrate it's lack of usability.

- Steps to reproduce:
    1. Open new tab and start typing some address.
    2. Suggestion list should show with meaningful text (depending on the browsing history).

This depends really what you've in the history and what are the titles of the sites you visited.

- Screenshot:

<img width="302" alt="screen shot 2016-05-26 at 10 08 43" src="https://cloud.githubusercontent.com/assets/266306/15569729/4f85328c-232a-11e6-97f2-e0f20d584218.png">

The above example shows meaningless pages such as 'Route not found' or 'Downloading a page'. This really can be any title and if this becomes more popular, website may spoof some nice title, so user will click it without knowing its address.

**Expected behavior:**

I believe the full URL should be shown next to the title (including port). This will help to identify what is the page behind the link, so there won't be any mistakes. It may be shown at the end or below the address with a smaller font. Maybe some additional info like date or relative time (e.g. Yesterday, Last Friday) when this page was last time visited.

- Platform OS X

- Brave Version: 0.10.0

--

Here is another example:

1. Google this: https://www.google.com/#q=http://127.0.0.1:8889
1. Now in the new tab type: `127.0.0.1`.

This is what is shown:

![screen shot 2016-05-26 at 10 24 14](https://cloud.githubusercontent.com/assets/266306/15570065/0c6df16c-232c-11e6-9d69-204fd4889d26.png)

Ignoring the fact it's shown twice (probably for `.co.uk` and `.com` due to redirect), it may cheat person that the link which you're accessing has different address, but in real it's just some other website (like search result page).

**Comment by luixxiul** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/1596#issuecomment-222544435
