### ISSUE TITLE
tab-specific notifications should only be shown on the active tab and be cleared on navigation

### ISSUE THREAD

**Issue by tetrode** [brave/browser-laptop#1928]
Go to a page where you can fill in a username / password and where brave offers to save the password. The yellow bar is shown at the top with choices Yes / No / Never for this site

Browse away to another site.

Expected: the bar is removed

Actual: the bar stays until the end of the browser session

- Platform Win7

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

**Comment by diracdeltas** [comment]
This was the intended behavior because I figured people might want to browse without having to deal with their browser notifications until later. (The notifications start to disappear after there's 3 of them so they won't take up the entire window.) But I think it is probably better to just clear them when their frame's location changes.

**Comment by tetrode** [comment]
Thinking about it, this could create an issue in the following situation:
1 go to a domain A, put in username, password
2 after submit, domain A does a redirect to another domain B
3 domain B does more / other validation and redirect to domain A or domain C
When clearing the message on domain change, the message is gone at 2. Perhaps insert a timer that clears the message after x sec.
Also, the Yes / No / Never for this site buttons were not 100% clear for me. Can you insert hover-over help messages? E.g. for No is this 'Not this time, but next time Brave will ask you again?'

**Comment by diracdeltas** [comment]
Hover-over tooltips are a good idea, thanks

I think we can avoid the redirect issue by only having the password notification cleared when the user manually navigates the tab or when the tab is closed

**Comment by bradleyrichter** [comment]
We decided to limit the tab-specific notifications to the tab that invoked it. It should also cancel on it's own when the page address changes or otherwise is no longer valid in that tab.

**Comment by diracdeltas** [comment]
> Thinking about it, this could create an issue in the following situation:
> 1 go to a domain A, put in username, password
> 2 after submit, domain A does a redirect to another domain B
> 3 domain B does more / other validation and redirect to domain A or domain C
> When clearing the message on domain change, the message is gone at 2. Perhaps insert a timer that clears the message after x sec.

This turns out to be a very common case and is causing a lot of support issues, so I am going to revert this change for passwords for now. https://github.com/brave/browser-laptop/issues/2957
