### ISSUE TITLE
youtube video not playing, rest of page loads ok

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#193]
![out](https://cloud.githubusercontent.com/assets/5495083/12433033/cb6c62b6-becc-11e5-92e1-856b03cbe1bf.gif)

**Comment by wblondel** [comment]
It's really weird, Youtube works perfectly on my side. It uses the HTML5 player.

**Comment by bkardell** [comment]
It's also not working for me console reports an error (a few actually, but this one is relied on by the player) 

```
Uncaught TypeError: Cannot read property 'isMinimized' of nullObject.defineProperty.get @ /Users/bkardell/projects/browser-laptop/node_modules/electron-prebuilt/dist/Electron.app/Contents/R…:81
Object.defineProperty.get @ /Users/bkardell/projects/browser-laptop/node_modules/electron-prebuilt/dist/Electron.app/Contents/R…:87
(anonymous function) @ watch?v=EPHmm8JiGbg&list=PLCGAAdUizzH0-aox_bwLBztVCUhRhR7yd&index=26:1
(anonymous function) @ watch?v=EPHmm8JiGbg&list=PLCGAAdUizzH0-aox_bwLBztVCUhRhR7yd&index=26:1
```

**Comment by wblondel** [comment]
On which OS are you running Brave @bkardell and @garvankeeley ?

**Comment by bkardell** [comment]
OSX 10.9.2 (can't upgrade for reasons)

**Comment by garvankeeley** [comment]
os x 10.10.5

**Comment by bbondy** [comment]
Please retest when you get the 0.7.10 update.  We upgraded to electron 0.36.5 and it fixes some other pages like adding github comments in a review.  Might fix this too.

**Comment by butlermatt** [comment]
I'm using 0.7.10 and still having this issue myself. My video in question is:
https://www.youtube.com/watch?v=uwV-MHaqR-Y

Mac OS 10.11.3

**Comment by onmyouji** [comment]
I'm having the same problem, but it happens randomly. Sometimes the video works just fine.

Windows 7 Home Premium 64-bit

**Comment by butlermatt** [comment]
From what I can recall, not all videos are html5. Particularly those with ads at the beginning of the Video still use a flash player.

**Comment by bagmangood** [comment]
Something I just tried (in related issue #386) is re-installing and that let me play videos that hadn't been playing before

**Comment by rob-blasetti** [comment]
@butlermatt I'm using Mac OS 10.11.3 too, but the video works fine for me with 0.7.12

**Comment by garvankeeley** [comment]
I am no longer seeing this, been using youtube without a problem. Clearly it was non-html5 videos, but I am not seeing the problem on videos that I originally reported this but with.

**Comment by diracdeltas** [comment]
Closing for now; please re-open if it keeps happening
