### ISSUE TITLE
Notification for Update and its status

### ISSUE THREAD

**Issue by decode-dev** [brave/browser-laptop#1930]
Need a notification for Update Process so that the user can know the update has been working. Because whenever it checks for Updates it shows " We're checking for Updates...".
This is sometimes annoying since the user doesn't know  update status.

**Comment by luixxiul** [comment]
There's a time lag between messages about finding an update and downloading it. This could be improved.

**Comment by decode-dev** [comment]
This can be shown by adding a "Status" UI  so that it will be much easier to see the Update Status of the browser.
