### ISSUE TITLE
Remember notification decision crash (OS X, Linux)

### ISSUE THREAD

**Issue by alecshaw** [brave/browser-laptop#1931]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

While using the browser version of Slack, when prompted to accept notifications from a tab, and then selecting that the decisions be remembered, the browser crashes. The first occurrence did not display any notification. The second occurrence displayed a notification after the browser had crashed. The third occurrence did not show any notification.

There was no issue when accepting notifications if the option to remember the decision was unselected.

**Expected behavior:**

The browser presents a notification, does not prompt again to allow notifications for that particular site, and life carries on.

- Platform (Win7, 8, 10? OS X? Linux distro?): OS X

- Brave Version: 0.10.0

- Steps to reproduce:
    1. Cause Slack to want to display a notification.
    2. Accept that notification, having also checked "Remember this decision".
    3. Browser should crash. Notification may appear.

- Screenshot if needed:

- Any related issues:

**Comment by charbelrami** [comment]
Tested on Yosemite, same issue on https://web.whatsapp.com/. It works on windows 10.

**Comment by khalidhalim** [comment]
Also on El Capitan 10.11.5

**Comment by aekeus** [comment]
Happening on Ubuntu as well

**Comment by ham1** [comment]
Reproduced with Linux Mint 17.3 and Brave 0.10.3.

**Comment by alecshaw** [comment]
Issue has now occurred without checking "remember decision". Allowing notifications crashed the browser. OSX 10.11.5 and Brave 0.10.4.
