### ISSUE TITLE
Brave dev env setup should be automated

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#1932]
@garvankeeley and I discussed a common script in every repo that would automate the setup and build process. The idea is that there should be a common entry point that allows you to quickly get up and running on any platform. The script should have 5 basic functions:
1. check - verifies that all deps and prerequisites are installed with the correct versions
2. setup - installs any deps or prerequisites that are missing from 'check'
3. build - runs a full build after ensuring that 'check/setup' has completed sucessfullly
4. run - builds and then runs the app
5. test - builds the app and runs the test suite
We may add additional parameters for version, etc... but this should be a good start

**Comment by bridiver** [comment]
'check' should fail and provide instructions to install anything that can't be installed automatically (VS on windows for instance)

**Comment by garvankeeley** [comment]
and build can take an argument for the build variant. by default it should build the non-release IMHO.
On iOS there are 2 variants, 'beta' and 'release'

**Comment by garvankeeley** [comment]
I forgot, I vote the script is always called ```bravebuild.sh```

**Comment by bridiver** [comment]
also, the script is not meant to replace any existing scripts that perform any of these functions, it's only meant to be a common interface to them and can run npm or any other command as necessary

**Comment by bridiver** [comment]
also the script should not overwrite any existing installs. If node 4.x is installed and node 5.x is required, node 5.x should be installed in a separate location. If that is not possible then the user should be prompted before install
