### ISSUE TITLE
.urlBarSuggestions not working well

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1933]
**Describe the issue you encountered:** It looks like a hidden element exists between history and domain suggestion in autocomplete

**Expected behavior:**

- Platform (Win7, 8, 10? OS X? Linux distro?): Windows 10 

- Brave Version: 0.10.0

- Steps to reproduce:
    1. Visit ``facebook.com/SomePage``
    2. Open a new tab
    3. Input ``fa`` in the URL bar to let Brave autocomplete
    3. Select two items alternately by pushing arrow keys two times each

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/3362943/15593642/3ee46b9a-23e9-11e6-8a3a-8452a7f20676.gif)

- Any related issues: #1596

**Comment by luixxiul** [comment]
Not reproducible anymore

**Comment by luixxiul** [comment]
Still reproducible. Here is the screenshot.

![](https://cloud.githubusercontent.com/assets/3362943/15798479/0d493830-2a75-11e6-8a23-1b58b5c02f32.jpg)

There should be data-index="4".

**Comment by bbondy** [comment]
Maybe you can backup your `~/Library/Application\ Support/brave/session-store-1`, then start with a fresh data set and reproduce the problem. Then attach the session-store-1 file here with the staged data which reproduces with steps to reproduce?

**Comment by luixxiul** [comment]
ok I'll try

**Comment by bbondy** [comment]
Or if you can reproduce always you can try adding a `ref={index}` to see if it fixes the problem to this element https://github.com/brave/browser-laptop/blob/master/js/components/urlBarSuggestions.js#L83

**Comment by luixxiul** [comment]
I cannot reproduce this anymore. I will reopen this when I see this again.
