### ISSUE TITLE
Brave while full screen sends Esetnod32 Antivirus into Gamer mode

### ISSUE THREAD

**Issue by fouroctets** [brave/browser-laptop#1935]
**Did you search for similar issues before submitting this one?**
Yes, I found nothing.

**Describe the issue you encountered:**
I do not know if this is an issue or not but I have never had this issue before. When I click on the Brave browser window it throws my AV into gaming mode. the browser isn't even in full screen when it happens. 
**Expected behavior:**
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Windows 10, Does the same thing on windows 7 as well.
- Brave Version:
  Brave: 0.10.0
  Electron: 0.37.8
  Lib: 50.0.2661.102
  v8: 5.0.71.48
  Node.js: 5.10.0
- Steps to reproduce:
  1. Open brave
  2. Have an AV that has "Gamer Mode"
  3. Make brave the active windows and the AV will go into gamer mode.
- Screenshot if needed:
  https://i.gyazo.com/9c3948a2bce358a3238b7ec9ba512d27.gif
- Any related issues:

**Suggestions**

I use my Yubikeys for most of my accounts and I am unable to use them on brave with Gmail. I get a notifications when I try and use my key to access my account and it says this.
https://i.gyazo.com/6cbd89ec34d6072172158c43c4129d11.png

**Comment by luixxiul** [comment]
The request for a U2F key (YubiKey Neo) for Two factor authentication has been submitted here: #518. So here let's focus on the issue with the antivirus software.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site:

https://community.brave.com/t/discussion-brave-while-full-screen-sends-esetnod32-antivirus-into-gamer-mode/10047

If you are still around here, would you please join the conversation there to talk about the issue further? :+1: There is a lot of discussions on the community, and you would be able to find solutions for other issues you might experience. Thanks!
