### ISSUE TITLE
It takes too long to load due to waits for permission of firewall

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1938]
from support (4108)

> Upgrading to the latest version of Brave, it simply takes too long for the home page (no matter what page that might be) to load. I used the Brave website as my home page and every time I start the browser, my firewall asks permission for remote address: s3-1.amazonaws.com, HTTPS (TCP:443). Even though Brave has been given Browser presets under the firewall (Agnitum Outpost Pro), I continually get requests for permission and never get to any page except after long waits and sometimes having to end Brave and restart it before any page appears.

**Comment by bbondy** [comment]
That's downloading for adblock data definition files and similar. It sounds like a problem with their firewall software if he is configuring it to allow us and it is still now allowing us.

**Comment by bridiver** [comment]
is this still an issue or was it caused by using node to download the file?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-investigation-it-takes-too-long-to-load-due-to-waits-for-permission-of-firewall/10100
