### ISSUE TITLE
VirusTotal (and Google Chrome) flags 64 bits version as malicious (detection rate: 2/56)

### ISSUE THREAD

**Issue by pedro7** [brave/browser-laptop#1939]
**Did you search for similar issues before submitting this one?**
Yes I did.

**Describe the issue you encountered:**
I downloaded 64 bits in Chrome. Since it warned very vocally that the file would harm my computer, I decided to [check with VirusTotal](https://www.virustotal.com/en/file/ee69b916b407b5596a3cf28c863ac46db277b61a0f6c23646dfaca453583e655/analysis/1464343306/)

**Expected behavior:**
VirusTotal (and Google Chrome) should have detection rate as 0/56

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows, 64 bits.

- Brave Version:
[BraveSetup-x64.exe](https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/0.10.0/winx64/BraveSetup-x64.exe)
SHA256SUM:
ee69b916b407b5596a3cf28c863ac46db277b61a0f6c23646dfaca453583e655 *BraveSetup-x64.exe

- Steps to reproduce:
    1. [Download from the site](https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/0.10.0/winx64/BraveSetup-x64.exe)
    2. Upload to VirusTotal
    3. Check the results

- Screenshot if needed:
![brave-x64-virustotal-dev-0 10](https://cloud.githubusercontent.com/assets/220099/15605211/76496d02-23fc-11e6-9be6-1487331329dc.png)

- Any related issues:
None

**Comment by neeklamy** [comment]
Someone else has flagged up something similar on another project, Whatsie [Virus scan results](https://github.com/Aluxian/Whatsie/issues/35) (and there’s links to more VirusTotal scans for Atom and Electron).

**Comment by pedro7** [comment]
**I** may know that.
The random user on the Web which currently uses Chrome and gets a insistent message in Chrome that the file may be dangerous may not know that.

**Comment by luixxiul** [comment]
Closing this in favor of #924. Thanks for the report.
