### ISSUE TITLE
Win 10 needs branding for Apps & Features

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#194]
<img width="535" alt="screenshot 2016-01-19 20 36 32" src="https://cloud.githubusercontent.com/assets/831718/12437501/62717556-beec-11e5-880e-645e38abd95c.png">

I think this will actually be solved by setting the registry's startmenuinternet uninstall icon, but posting just in case it is not.

Source of bug @SergeyZhukovsky

**Comment by luixxiul** [comment]
Changing the background color of pinned app's shortcut to Brave, too.

**Comment by bsclifton** [comment]
Closing since this appears to be fixed (see screenshot)

This may have been fixed with https://github.com/brave/browser-laptop/commit/82a2ac64b9897184cc01feac034c3051728a6490#diff-98f0ed24f8f0fed04b7949391f32909eL11 or an earlier commit

![apps-features](https://cloud.githubusercontent.com/assets/4733304/16456917/81cabdfc-3dce-11e6-9492-42792fbd0c9f.png)

**Comment by bbondy** [comment]
fixed with winstaller upgrade. thanks for closing.

**Comment by luixxiul** [comment]
As a follow-up task, how about branding the panel on the start menu?

![](https://cloud.githubusercontent.com/assets/3362943/16485558/766e5112-3efa-11e6-97b1-7cacb643adcb.jpg)

Like Foxit reader.

**Comment by bbondy** [comment]
pls post as a new issue, can a normal app to live tiles or only universal apps.

**Comment by bbondy** [comment]
The last message should have said: "I'm not sure if a normal win32 app can have live tiles, or only universal apps can. It used to be only the latter but this might have changed in Windows10.  @bsclifton might know more".

**Comment by luixxiul** [comment]
There is an instruction on Microsoft help page but I don't remember where it is. The foxit reader is not the universal application so there must be a way of configuring it.

**Comment by bsclifton** [comment]
With not a lot of work, I was able to get this customized pretty nicely :smile: Works great for non-live tile applications.  I created a new issue and put a screencap of a proposed fix there :smile: 
https://github.com/brave/browser-laptop/issues/2372
