### ISSUE TITLE
Documentation to add a new language option.

### ISSUE THREAD

**Issue by jmdh01** [brave/browser-laptop#1940]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? OS X? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by jmdh01** [comment]
Are there any guidelines/instructions on how to add support for a new language for use with any of the supported OSs? I am prepred to do some work to implement English (UK).

**Comment by bbondy** [comment]
Not sure why you closed this issue, but re-opening again.

**Comment by luixxiul** [comment]
Closing in favor of https://community.brave.com/t/can-i-have-brave-in-my-language/9993
