### ISSUE TITLE
Back in history: "Unexpected error has occured"

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1942]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Sporadically when going back in history, I get an error screen. Pressing the button on the error page to reload fixes the problem.
- Brave Version:
  Brave: 0.10.0, dev channel, OS X 
- Steps to reproduce:
  1. Browse as normal
  2. Click back button
- Screenshot if needed:

<img width="754" alt="screenshot 2016-05-27 09 58 37" src="https://cloud.githubusercontent.com/assets/5495083/15610163/df2b35ea-23f1-11e6-8941-5b0f4d88b84c.png">

**Comment by bbondy** [comment]
cc @bridiver

**Comment by bridiver** [comment]
unexpected error is always a renderer crash

**Comment by bbondy** [comment]
Modulo not having a crash server fully accessible / setup yet, this generates a crash report right? If so I think we can close this.

**Comment by bbondy** [comment]
cc @bradleyrichter maybe we should more clearly indicate it's a crash so people don't think it's just another bug.

**Comment by garvankeeley** [comment]
Yet to happen on latest RC

**Comment by bridiver** [comment]
not sure if this is fixed or not, but I'm not able to replicate after https://github.com/brave/electron/pull/21

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by luixxiul** [comment]
Closing for now as it is stale.
