### ISSUE TITLE
Plex does not log in on Brave

### ISSUE THREAD

**Issue by reallyhispanic** [brave/browser-laptop#1943]
I did not look for this prior.

When I try to log into my Plex account... it gives me an error.

I am able to log in on Safari and everything else.
- Platform (Win7, 8, 10? OS X? Linux distro?): OS X
- Brave Version: 0.10.0
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
What kind of error is it? A log/screenshot would be appreciated.

**Comment by reallyhispanic** [comment]
Sure thing…
It does not log into the server. This is the only browser that doesn’t. I am logged in with Safari at this exact time.

This is the screen shot.

Frank

**Comment by luixxiul** [comment]
Please disable both "HTTPS Everywhere" and "Block scripts" from Bravery menu (from the top right icon) and try again. That worked for me. It seems that redirections do not work well on their server. cc @diracdeltas

**Comment by diracdeltas** [comment]
sign in works now with HTTPS Everywhere enabled and scripts disabled, which is the default

**Comment by Ozzon60** [comment]
i can't login to plex...

**Comment by bsclifton** [comment]
@Ozzon60 do you have scripts disabled?  You check check by clicking the Lion icon (shields menu) in the top right

**Comment by Ozzon60** [comment]
@bsclifton No, I have tried a bunch of things including putting shields down and I still can't login (sort of), if i go to there website rather then clicking open plex (from the windows app) then login, settings and then press the home button, but even still when I press the open plex button I still can't login which is a small inconvenience.

I couldn't figured out how to reply.
When I open a link out site of the browser brave takes a bit longer then other browsers (I mean to appear at all not website load time), is this normal?

**Comment by marlon99rocks** [comment]
its does not work when i disable shield

**Comment by Xaconi** [comment]
Same problem here...
![image](https://user-images.githubusercontent.com/1944438/38192605-e80dfab8-366d-11e8-8543-a1e4995e97e4.png)

**Comment by gwenhidwy** [comment]
I am having the same issue. This is one of the things preventing me from using Brave as my main browser.

**Comment by scouturier** [comment]
To successfully use Brave with Plex, you need to authorize cookies for your **local** Plex Media Server.

Disabling shield does not always works, mostly because Plex logs in through https://app.plex.tv then transfers you to your local media server so you only have a small window of time to do so as the the login fails quickly after trying to redirect, then brings you back to app.plex.tv website with the error, so most of the time you will disable shield for app.plex.tv and not your media server.

**Comment by srirambv** [comment]
Seems fixed on brave-core
![image](https://user-images.githubusercontent.com/17010094/45267173-7f7d8900-b435-11e8-8199-57e86afb6a93.png)
