### ISSUE TITLE
Tabs are not reopened when Brave is reopened

### ISSUE THREAD

**Issue by GoGoJJTech** [brave/browser-laptop#1950]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Tabs are not reopened when Brave is reopened.

**Expected behavior:**
Once the option is enabled in the settings, upon closing Brave and reopening, the previous tabs should be reopened.

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 8 (Toshiba Laptop)

- Brave Version:
Version 0.10.0

- Steps to reproduce:
    1. Enable option to reopen tabs upon reopening Brave
    2. Close Brave
    3. Open Brave

- Any related issues:
Might be related, but Brave processes remain open even a half hour after closing Brave. Maybe the program isn't terminating correctly and as a result it thinks it was still opened (?)

**Comment by marti1125** [comment]
@GoGoJJTech that option doesn't exist. It works very well in win10

**Comment by GoGoJJTech** [comment]
Preferences -> General -> "Brave starts with" -> "Show my windows / tabs from last time"

**Comment by Leatherwing** [comment]
I see the same issue as @GoGoJJTech reported. For me, about 50% of the time the previous session opens, and the other 50% Brave opens with only a single new tab. This is the single issue that is preventing me from committing to Brave 100% as my go-to browser.

OS: Windows 10 Pro

![image](https://cloud.githubusercontent.com/assets/19720810/15766208/007f0c0e-290a-11e6-8a36-98b7d8515b4b.png)

**Comment by luixxiul** [comment]
Possibly fixed?

**Comment by bbondy** [comment]
I think probably fixed so closing, but please re-open if it's still an issue.
