### ISSUE TITLE
implement new bravery panel spec

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1951]
from @bradleyrichter: 
![pasted image at 2016_05_26 01_05 pm](https://cloud.githubusercontent.com/assets/549654/15621538/ad965daa-242f-11e6-9029-98fc92b5ecf1.png)

since we don't yet support flash, the "Block Flash Objects" switch should be un-switchable

**Comment by bradleyrichter** [comment]
@diracdeltas Let's leave the Flash switch out rather than disabled since we are including an un-switchable Block Popups switch which does block but can't be changed yet.

![image](https://cloud.githubusercontent.com/assets/13509546/15621687/83c03dd8-2417-11e6-8576-926e07510db2.png)

**Comment by diracdeltas** [comment]
@bradleyrichter did you intend to set Block Scripts to be unswitchable in the screenshot above? 

"Block Popups" and "Block Flash" are in the same boat right now (enabled but unswitchable). I'm fine with only showing "Block Popups" and not "Block Flash" though.

**Comment by bradleyrichter** [comment]
Unintended confusion. We will just remove the "unswitchable" switches and the style for OFF will be dark grey.

**Comment by diracdeltas** [comment]
++

**Comment by bradleyrichter** [comment]
so, it should look like this: (big favicon to come later)

![image](https://cloud.githubusercontent.com/assets/13509546/15622673/feed1d8e-241f-11e6-8286-60c3cf57d6a5.png)

**Comment by diracdeltas** [comment]
This is basically done except for the 'Edit Bravery Global Settings...' link which is in progress

**Comment by luixxiul** [comment]
I'm pushing a PR to make this

![](https://cloud.githubusercontent.com/assets/3362943/15629185/49d62fe2-254d-11e6-86e7-ae9fadbe1488.jpg)

into

![](https://cloud.githubusercontent.com/assets/3362943/15629188/64ff2b20-254d-11e6-872c-5ff8d48b8586.jpg)

**Comment by diracdeltas** [comment]
@luixxiul thanks. looks better, though i would prefer the question-mark to be closer to "Fingerprinting Protection". on my screen, it looks fine because everything fits in one line:
![screen shot 2016-05-28 at 4 35 29 pm](https://cloud.githubusercontent.com/assets/549654/15630492/858a7a8a-24f2-11e6-8f4c-c2f33d6d8666.png)

is it possible for you to make the panel wider so that the text fits in one line without making it wider than the minimum browser window size?

**Comment by bsclifton** [comment]
This is a great looking screen :smile:

**Comment by luixxiul** [comment]
@diracdeltas I noticed that once too. I think maybe it's not enough to solve the issue completely by changing the width of the panel due to the nature of ``display: flex``. You'll have to rewrite the divs around the question mark. I'll take a look at it again.

**Comment by luixxiul** [comment]
I noticed that the previous commit has broken the margin between the shields switch and "Up". I'll push another commit again to fix it.

**Comment by bradleyrichter** [comment]
@diracdeltas The reason for the original order of the number display was to put the least-used at the far left. (assuming blocking scripts is least-used)

Is there a reason you preferred or needed the order that was implemented?

Also - Let's add left-margin in front of the ? mark button, and make it dark grey to reduce it's visual importance. (when time permits)

**Comment by diracdeltas** [comment]
@bradleyrichter I think fingerprinting protection will be less used than script blocking actually. I ordered them so that the one most likely to be '0' is at the end.

**Comment by bbondy** [comment]
I think fingerprinting protection will be used more than script blocking but I'm fine with whatever.  Just because the most web breaking thing is script blocking.

**Comment by bradleyrichter** [comment]
This needs to turn into a popup that hides on any click outside of the popup region. I'm worried it will otherwise be confusing when users open them accidentally.
