### ISSUE TITLE
Allow microphone and Brave fails

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1954]
From support

> Whenever software requests a mic, Brave asks for permission. I allow it, then Brave fails.
> I’m using OS X 10.11.3 with a USB mic. The site requesting mic usage is Dueling.com.
> I have no problem with this on Chrome. In fact Chrome doesn’t ask for permission.

- Platform (Win7, 8, 10? OS X? Linux distro?): OS X

**Comment by luixxiul** [comment]
The link doesn't seems to be legit

**Comment by ahfmenot** [comment]
Sorry about the link. I think it was autocorrected.  The link should have been duolingo.com

**Comment by luixxiul** [comment]
Thanks, @ahfmenot!

**Comment by bridiver** [comment]
Are there some steps to reproduce this or should the crash happen by just going to that url?

**Comment by ahfmenot** [comment]
This is a language learning site. The crash occurs when you begin the study
of any language at the point where you are asked to speak into a mike. I
don't know any way to get there other than by starting the study of a
lesson that requires a mike. If there's a direct way to get there I don't
know it. You might want to contact Duolingo

**Comment by bridiver** [comment]
I believe this should also be fixed by https://github.com/brave/electron/commit/94921be41cf229dd338078da58b5588415feb19e
Please let us know if you are still able to replicate after the next release of Brave and we will re-open if necessary.
