### ISSUE TITLE
Can't Print from web page buttons or from Brave Print function. Win 10

### ISSUE THREAD

**Issue by freshcut1** [brave/browser-laptop#1959]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? OS X? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #1616
