### ISSUE TITLE
Linux Brave settings are not saved

### ISSUE THREAD

**Issue by binaryanomaly** [brave/browser-laptop#1961]
**Did you search for similar issues before submitting this one?**

Similar issue to here: https://github.com/brave/browser-laptop/issues/1462

**Describe the issue you encountered:**
Nearly all settings are not save when closing the browser. This concerns settings, as well as imported bookmarks. For an unknown reason sometimes parts seem to remembered but not consistent

**Expected behavior:**
Settings are saved.

- Platform (Win7, 8, 10? OS X? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.10.0

- Steps to reproduce:
    1. Open Brave
    2. Change settings, import bookmarks
    3. Close reopen / reboot reopen

**Comment by cezaraugusto** [comment]
Hi @binaryanomaly, could you check if this issue persists with the current version (v.0.11.0)?

**Comment by binaryanomaly** [comment]
Hi @cezaraugusto it's fixed, thx.
