### ISSUE TITLE
Error on phpmyadmin: Failed to clear temp storage

### ISSUE THREAD

**Issue by Webist** [brave/browser-laptop#1963]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

> Failed to clear temp storage  It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

**Expected behavior:**
- Platform OS X
- Brave Version:0.10.0
- Steps to reproduce:
  1. Try to open a page with https:/ .... /phpmyadmin  
  2. wait and wait
  3. or look at the console
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-info-error-on-phpmyadmin-failed-to-clear-temp-storage/10950

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
