### ISSUE TITLE
Spell check is broken.

### ISSUE THREAD

**Issue by walterallenhaxton** [brave/browser-laptop#1965]
Spell check erases everything after the word that you are correcting and it needs to be retyped. Most annoying.

**Comment by jmalonzo** [comment]
Hi @walterallenhaxton - do you have a sample case? I checked some sites and replacing the misspelled word with the proper spelling seems fine and doesn't delete the words after the corrected word.

Also, what's the version of Brave you're using and platform? Tnx.

**Comment by walterallenhaxton** [comment]
I am using Windows 10. It does it all of the time in Facebook.  Maybe that is the only place.


Walter Allen Haxton
 718 Forest St. Hagerstown Maryland 
21740 Cell: 240-291-1751

____________________________________________________________
Affordable Wireless Plans
Set up is easy. Get online in minutes.
Starting at only $9.95 per month! 
www.netzero.net?refcd=nzmem0216

**Comment by luixxiul** [comment]
How about with the latest version?

**Comment by Liunkae** [comment]
No recent reports of the issue. Closing.
