### ISSUE TITLE
Upgrade to Node 6.1

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1969]

**Comment by luixxiul** [comment]
Should this be updated?
https://github.com/brave/browser-laptop/blob/master/README.md#all-platforms
https://github.com/brave/browser-laptop/blob/master/README.md#installation

**Comment by bbondy** [comment]
Good call, updated here:
https://github.com/brave/browser-laptop/commit/9dee6539d6dc846a278ffe21a0ef86aaa664f696
