### ISSUE TITLE
Pin tabs: cannot move a pinned tab to a previous position

### ISSUE THREAD

**Issue by warpdesign** [brave/browser-laptop#1971]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When having more than one pinned tabs, it's possible to re-order the pinned tabs by drag and drop. 

If I have two pinned tabs: pin 1 & pin 2, I can drag pin 1 and drop it after pin 2: it will correctly change the order.

However, if I try to drag pin 2 and drop it before pin 1 to make it the first one from the left, it won't work. It will stay at its position.

More generally, it seems moving a pined tab before its current position doesn't work, while moving it past its position works.

**Expected behavior:**
Moving a pinned tab before its position should correctly place it there.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Windows 10
- Brave Version:
  0.10.0
- Steps to reproduce:
  1. Pin two sites
  2. Try to drag & drop the second pinned site before the first one
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
I think this has been fixed. Let's reopen if this is still an issue.
