### ISSUE TITLE
Crash when content does window.open

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1972]
I get a new crash with chromium51 anytime I click a bookmarklet which creates a new tab.  Crashes here in a release build with `
render_widget_host_view_child_frame.cc`.

I’m guessing host_ is is null but I don’t have a debug build so it’s not loading the value for me.

<img width="653" alt="screenshot 2016-05-29 20 47 31" src="https://cloud.githubusercontent.com/assets/831718/15637083/ef5b59d8-25de-11e6-90d2-9b3619c331b4.png">

You can repro with this bookmarklet or just open content dev tools and do window.open
```
javascript:(function()%7B window.open(%27http://www.cnn.com/%27)%3B %7D)()%3B
```

cc @bridiver

**Comment by bbondy** [comment]
Happen on all platforms.

**Comment by luixxiul** [comment]
I'm not sure but is this related?
Bookmark a page, click the favicon on the toolbar, but nothing is rendered. I got the error message:

``Uncaught TypeError: _this4.webview.setHidden is not a function``

**Comment by bbondy** [comment]
@bridiver can be closed?
