### ISSUE TITLE
Dragging bookmark items in the folder doesn't work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1975]
**Describe the issue you encountered:** Dragging bookmark items, deleting bookmarks/subfolder in the folder doesn't work

- Platform (Win7, 8, 10? OS X? Linux distro?): Ubuntu 14.10

- Brave Version: Master branch (the latest commit is https://github.com/brave/browser-laptop/commit/6e78d3191975122182c053dbf68a1f902b61f713)

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/3362943/15639054/19087436-2662-11e6-97b1-98ea7a4aded3.jpg)

- Any related issues: Maybe #1839

**Comment by bbondy** [comment]
both work for me

**Comment by luixxiul** [comment]
I'm trying ``npm install``.

**Comment by luixxiul** [comment]
it worked :-) README should be updated to do so.

**Comment by luixxiul** [comment]
@bbondy Would you please check #1977? Thanks.
