### ISSUE TITLE
Add an option to disable "title mode".  Always show URL bar option.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1984]

**Comment by cezaraugusto** [comment]
@bbondy kind of a challenge so I would like to do it, if possible. 

Would a checkbox inside Preferences >  General a good option for that?

**Comment by bbondy** [comment]
Yes I think that's a good spot for it. cc @bradleyrichter this is a frequently requested support issue.

**Comment by luixxiul** [comment]
Surely on Windows, the title appears three times:

![](https://cloud.githubusercontent.com/assets/3362943/15674511/1195a216-2778-11e6-9641-6abb0ee8be55.jpg)

I think it's too much.

**Comment by bbondy** [comment]
The top title bar really shouldn't be there at all. But it's an electron change that could take some time.  Brad suggested as a work around to always show the url bar on Windows.
