### ISSUE TITLE
Installation fails on Windows Vista

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1986]
From support:

> I just downloaded the 32 bit version and tried to install and it returned an error which I've attached. I'm running the 32 bit version of Vista SP2.
>
> ![brave error](https://cloud.githubusercontent.com/assets/3362943/15654765/f6291374-26d1-11e6-9452-6011f6fc16ab.jpg)

**Comment by bbondy** [comment]
We only support Windows7 and up, sorry about that.
