### ISSUE TITLE
Cookie option in bravery panel missing option "Block All"

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1987]

**Comment by alexwykoff** [comment]
Shipped

**Comment by luixxiul** [comment]
I'm just seeing Accept every cookie and Block 3p cookies, not Block every cookie

**Comment by Liunkae** [comment]
Not shipped yet, as far as I can tell.

**Comment by alexwykoff** [comment]
My mistake. Read too fast.

**Comment by diracdeltas** [comment]
+1 on this, preferably for 1.0. I think this should be done in conjunction with https://github.com/brave/browser-laptop/issues/1268 such that cookies are blocked globally and there is a prompt to whitelist cookies on a page based on origin, because very few users want to block all cookies.

**Comment by diracdeltas** [comment]
For a first-pass I'll only add a setting to allow/deny all on a site
