### ISSUE TITLE
Right-click context menu missing 'Share...' (OS X)

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1988]
Support request: Like Safari and other apps, there is no Share item in this menu

**Comment by Liunkae** [comment]
Example from Safari's File menu:
![image](https://cloud.githubusercontent.com/assets/19424103/24011912/247c5cf2-0a4a-11e7-8d22-1d8307b72d87.png)

**Comment by bsclifton** [comment]
We fixed this a while back
