### ISSUE TITLE
Inline element, copy and paste, spaces get eaten

### ISSUE THREAD

**Issue by neeklamy** [brave/browser-laptop#1992]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Copying text on an element that wraps over more than one line, where the second line begins with an inline element, the space before the inline element get eaten in the pasteboard. This only appears to affect the rich text pasteboard.

**Expected behavior:**
Copied text to appear the same as on the web page.

**Platform:**
OS X 10.11.5
(Confirmed on two Macs.)

**Brave versions:**
0.10.0 - 0.11.1

**Steps to reproduce:**
I have created a page that demonstrates the issue: [Brave bug – text wrapping](http://run.plnkr.co/plunks/BdUhGRW2wk312t3mmzpL/).

**Comment by luixxiul** [comment]
On LibreOffice I confirmed this has been fixed 😉 

![32432301-6cfa0a9a-c31a-11e7-87ca-52b4b3ea69ea](https://user-images.githubusercontent.com/3362943/32490987-6589a728-c3f8-11e7-9a6c-8d00c9fe26fc.png)
