### ISSUE TITLE
Basic auth doesn't seem to work on this page

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#1997]
It seems like basic auth to me. Chrome prompts, we just spin forever:
https://portal.adp.com/wps/employee/employee.jsp

**Comment by luixxiul** [comment]
Also this: http://browserspy.dk/password.php FF

**Comment by echosa** [comment]
I've noticed this on a couple of work-related pages I can't share. When I visit the pages, I get the HTTP auth popup, but upon supplying credentials, the page just sits, spins, and never loads. No errors in the console or anything.

**Comment by echosa** [comment]
Additionally, manually including the credentials in the URL allows the page to load. FYI

**Comment by luixxiul** [comment]
Not fixed on Windows 7

**Comment by bbondy** [comment]
cc @darkdh

**Comment by darkdh** [comment]
@luixxiul did you test it with https://portal.adp.com/wps/employee/employee.jsp ?

**Comment by luixxiul** [comment]
Yes it cannot be opened on both Windows and macOS

**Comment by luixxiul** [comment]
Still I cannot log in here: http://browserspy.dk/password.php

It works on Chrome

**Comment by darkdh** [comment]
But it works on my side. Did you turn on the script blocking?
<img width="1440" alt="screen shot 2016-07-30 at 01 02 14" src="https://cloud.githubusercontent.com/assets/11330831/17256721/4debfc2c-55f1-11e6-9b13-739c53f130aa.png">

**Comment by luixxiul** [comment]
Displaying prompt is fine. You just cannot log in with the credential (test:test). Maybe they are different issues.

**Comment by darkdh** [comment]
Oh, I know what you meant. Maybe fire another issue? 
cc @bbondy

**Comment by luixxiul** [comment]
Done -> #2807
