### ISSUE TITLE
2-finger scrolling too fast on windows

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#1998]
From support:

On my Dell XPS 15 (2015) laptop, the two-finger scrolling is simply too responsive. 
I scroll too much at any given time, no matter how gentle I am with the trackpad. 

Edge and Chrome work ok.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of our community site.

https://community.brave.com/t/2-finger-scrolling-too-fast-on-windows/10403

Let's reopen if this is an issue widely reproduced 👍

**Comment by bsclifton** [comment]
this is actually a dupe- we attempted a fix for this with https://github.com/brave/browser-laptop/issues/9615 (which is in 0.20.x)
