### ISSUE TITLE
Spaces in a URL perform a google search

### ISSUE THREAD

**Issue by SethClydesdale** [brave/browser-laptop#2002]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When a URL contains a space in the address bar and you hit the enter key, it opens a search instead of navigating to the URL.

**Expected behavior:**
You should be taken to the URL without performing a search, like other browsers.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Win7
- Brave Version:
  0.10.0
- Steps to reproduce:
  1. Type a URL in the address bar that contains a space
  2. Hit the enter key

If you need an example, here's a few URLs you can copy and paste in your address bars : 
`https://twitter.com/search?q=kitty cats`
`http://help.forumotion.com/st/ange tuteur`

You can replace the space with %20 or + and it'll navigate to the URL, but people who aren't familiar with that will have this problem. It's probably not common for someone to type the keywords in the URL, but I figured I'd report it because lazy me does that. :stuck_out_tongue_winking_eye:  
- Screenshot if needed:
  N/A
- Any related issues:
  [This](https://github.com/brave/browser-laptop/issues/519) was sorta related, but it concerned trailing and preceding white space.

**Comment by neeklamy** [comment]
This happens with files that are on your local file system too, if there’s a space in the path you’re taken to the configured search engine.

**Comment by luixxiul** [comment]
I thought @Sh1d0w has fixed the issue a couple of months ago.

**Comment by alexwykoff** [comment]
+1 from community https://community.brave.com/t/convert-spaces-in-urls/1545

still an issue in 0.19.50
