### ISSUE TITLE
Cannot view History

### ISSUE THREAD

**Issue by joe-liberty** [brave/browser-laptop#2003]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

History (CNTRL Y) is grayed out

**Expected behavior:**

Should be able to view history

- Platform (Win7, 8, 10? OS X? Linux distro?):

Linux

- Brave Version:

0.10.0

- Steps to reproduce:
    1. Go to History Menu
    2. Show All History Not Working
![screenshot from 2016-05-30 20 18 35](https://cloud.githubusercontent.com/assets/18178544/15660557/c869139a-26a3-11e6-9be5-de4a5b092de0.png)

    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #444, closing now.
