### ISSUE TITLE
Google Doc Video "Couldn't load plugin"

### ISSUE THREAD

**Issue by jayjaygithub** [brave/browser-laptop#2005]
Video fails due to plugin not loading.

Should be playing the video embedded in the webpage. It works fine in Firef*x 
I know other brave users who don't have this problem but I don't know why I have it 
- Platform: Windows 8.1
- Brave Version: Most recent
- Steps to reproduce:
  1. Play a video on Google Docs

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-discussion-which-video-on-google-drive-displays-couldnt-load-plugin/10391

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
