### ISSUE TITLE
Tweak build settings to be more secure

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2007]
Possibly with these (maybe the values need to change though)

```
'RandomizedBaseAddress': 2, # enable ASLR
'DataExecutionPrevention': 2, # enable DEP
'AllowIsolation': 'true',
```

PIE and NX also

**Comment by diracdeltas** [comment]
on osx, `otool -hv /Applications/Brave.app/Contents/MacOS/Brave` shows PIE enabled

i think this issue may be obsolete now?

**Comment by bbondy** [comment]
Seems like release builds have this, so closing.
