### ISSUE TITLE
pop-up search box doesn't work on CNET Roadshow

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2008]
**Describe the issue you encountered:**
The search function doesn't work on the CNET Roadshow site.

**Expected behavior:**
Clicking the search area (upper left of screen) should produce a pop-up field where you can type search terms.

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

- Steps to reproduce:
    1. Go to http://www.cnet.com/roadshow
    2. Click on search field

- Screenshot attached of what it *should* look like
<img width="1416" alt="screenshot 2016-05-31 11 08 20" src="https://cloud.githubusercontent.com/assets/16833251/15669336/218b5dee-2720-11e6-9100-60763c3129d3.png">

**Comment by Liunkae** [comment]
This issue is the same as #2010.

**Comment by bbondy** [comment]
I think it's fixed in 0.12.7, please re-open if not.  Update is expected to be coming tomorrow.
