### ISSUE TITLE
Address autocomplete should prioritize facebook.com over Facebook URLs from browsing history

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2009]
**Describe the issue you encountered:**

Typing "face" into the address bar presents two autocomplete options: Facebook URLs I've previously visited (14 in my case), and below that, the generic Facebook.com.

**Expected behavior:**

Brave should give top billing to the usual Facebook.com since it's a more likely destination than some previous Facebook URL -- especially one that isn't labeled or titled in any useful way.

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

- Steps to reproduce:
    1. Type "face" in address bar

- Screenshot if needed:

<img width="217" alt="screenshot 2016-05-31 10 01 28" src="https://cloud.githubusercontent.com/assets/16833251/15669630/9c835faa-2721-11e6-8d2d-be8402818dd1.png">

**Comment by luixxiul** [comment]
I think this has been addressed already.

**Comment by bbondy** [comment]
Yep it chooses the shortest one now first.
