### ISSUE TITLE
Clicking arrow button won't advance to next photo in CNET gallery

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2010]
**Describe the issue you encountered:**
Clicking gallery arrows on CNET photo galleries does nothing.

**Expected behavior:**
Clicking should advance to the next photo.

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X 10.11.6 (15G7b) beta

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

- Steps to reproduce:
    1. Load gallery, e.g. http://www.cnet.com/pictures/asus-zenbook-3-is-slim-shiny-and-powerful/ or 
http://www.cnet.com/roadshow/pictures/nissan-freshens-up-the-gt-r-nismo-for-2017-pictures/
    2. Click the right-arrow image on the photo

**Comment by Liunkae** [comment]
The problem is caused by the ad blocker and/or tracking protection. As a workaround, disable ad blocking and tracking protection for that site. Several .js files are being blocked that could be needed for the arrow button to function.

**Comment by bbondy** [comment]
I think it was fixed as part of this:
https://github.com/brave/browser-laptop/issues/5089#issuecomment-256545471

Please re-open if not.

**Comment by bbondy** [comment]
in 0.12.7
