### ISSUE TITLE
add shortcut to hide downloads bar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2012]
When you press the shortcut to go to the downloads page, it should also hide the downloads toolbar.

**Comment by iKlsR** [comment]
Hi, I'd like to take this as a first issue.

**Comment by luixxiul** [comment]
Sorry, I mistakenly closed the issue. Reopened.

**Comment by iKlsR** [comment]
I've got it working but I'm not sure if I'm editing the correct file(s), I poked around in `app.entry.js` but my changes didn't stick, grepping I found a similar block in `main.js` and a new flag `toggleFrame` could suffice to replace singleFrame for this and similar frames. Suggestions and pointers are welcome, thanks! First time using Electron. 

So we can now toggle the downloads frame with `Ctrl J`

See https://github.com/brave/browser-laptop/commit/9892029fa5123b51f97add5a2b9e02894d34bac6

**Comment by iKlsR** [comment]
Ignore that last comment if you got it by mail, that was for a separate issue.

**Comment by ludable** [comment]
@iKlsR Hi, are you still interested in doing this? Would you mind if I took a stab at it?

**Comment by iKlsR** [comment]
Aagh, forgot about this for a bit go ahead. I actually finished it, even
had a diff in a now deleted comment but I've been away from my main machine
for a long while now, sorry for not updating.
