### ISSUE TITLE
No context-menu copy and paste in "My home page is" box in Preferences/General settings.

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#2016]
(from support issue, confirmed)

**Comment by bbondy** [comment]
I think this is the same as the intermittent copy problem? You seem to be hitting it a lot though...

**Comment by bbondy** [comment]
It's working for me...

**Comment by garvankeeley** [comment]
Sorry wrong description.

**Comment by Liunkae** [comment]
The context menu does not work anywhere in Preferences (not sure if that is intended).

**Comment by luixxiul** [comment]
I think this has been fixed on the new ``about:preferences``.

**Comment by bbondy** [comment]
should be fixed, please re-open if not.
