### ISSUE TITLE
Windows touch screen, x/y coords incorrect

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#2018]
From support ticket (got no Windows touch device myself to confirm):
> The x/y co-ordinates in touch event seem to be incorrect. To reproduce this bug, open say google.com or youtube.com and in the white space there keep a finger pressed on the touchscreen to invoke right click and see where it opens the popup menu. Or in my site - www.LiveIn0.com you can start a conference, then ‘Take Stage’ and try to draw on the Whiteboard (HTML canvas) – you can draw properly using a mouse, but not using touchscreen – the y-coordinate seems a bit off. However it works well in Chrome, Firefox, Opera.

**Comment by srirambv** [comment]
Confirmed on Touch screen Lenovo tablet. Right click context menu come up at the previous touch point and not the new one. 

#2686
