### ISSUE TITLE
Videos on a lot of sites plays without image ( sound only )

### ISSUE THREAD

**Issue by Empathist** [brave/browser-laptop#2019]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:** on some sites like facebook and google drive, videos works sound only without image, turning off the shield from the icon at the top doesnt fix it,
the videos works normally on other browser, please fix this as brave is my new favorite browser but this issue will stop me from using it.
The videos works on some sites like youtube, maybe it's a problem with html5 player? i have no idea. 

**Expected behavior:** video works?
- Platform (Win7, 8, 10? OS X? Linux distro?): Win 7 Ultimate x64
- Brave Version: last
- Steps to reproduce:
  1. go to facebook and search for an uploaded video
  2. click the play button
  3. 'Hear' the video.
- Screenshot if needed:
  __
- Any related issues:
  __ It's not a related issue really, but it's another issue that i think am the only one having,
  after i add pages to bookmarks, they get removed after I restart the pc, I will try to reinstall Brave.

**#EDIT#** I reinstalled but still same problems.

**Comment by darain** [comment]
Hi,

Same issue here

**Platform** 
(Win7, 8, 10? OS X? Linux distro?): Win 7 x64

**Brave Version** 
updated today:  Brave 0.10.3 (

**Steps to reproduce:**

- go to www.clubic.com or www.jeuxvideo.com and run any video you can see.
- click the play button
- 'Hear' the video.

**Additionnal inofmation**
Same issue with previous version of Brave

**Comment by neeklamy** [comment]
Probably related to #464 

@darain, those sites seem to work fine in Brave 0.10.4:

 - AlloCiné examples: [one][allo-one] and [two][allo-two].
 - Clubic examples: [one][clubic-one] and [two][clubic-two].
 - Jeuxvideo examples: [one][jeux-one] and [two][jeux-two].

**Clubic is difficult:** Videos still use Adobe Flash Player, so if you haven’t got the Adobe Pepper Flash Player plugin, you will need that first, then it needs to be enabled in Brave’s preferences.

It looks like videos won’t play with Brave’s shields up,allowing adverts and tracking doesn’t seem to be enough.

Maddeningly, Clubic’s video adverts *don’t use* Adobe Flash, they play without the need of any plugins.

@Empathist, could you link to any example videos that show this problem?

[allo-one]: http://www.allocine.fr/video/player_gen_cmedia=19561049&cfilm=243501.html
[allo-two]: http://www.allocine.fr/video/player_gen_cmedia=19562053&cfilm=230868.html
[clubic-one]: http://www.clubic.com/video/trailers-de-jeux-video/video-a-shadow-falls-le-mode-histoire-de-street-fighter-v-480788.html
[clubic-two]: http://www.clubic.com/video/trailers-de-jeux-video/video-les-jeux-video-attendus-pour-juillet-2016-480760.html
[jeux-one]: http://www.jeuxvideo.com/videos/chroniques/510007/l-univers-du-jeu-independant-jalopy-goodbye-lenine.htm
[jeux-two]: http://www.jeuxvideo.com/videos/chroniques/509248/vgm-final-fantasy-x-la-fin-d-un-voyage.htm

**Comment by luixxiul** [comment]
Closing as stale.
