### ISSUE TITLE
Brave Not Loading Disqus Comments

### ISSUE THREAD

**Issue by joe-liberty** [brave/browser-laptop#2020]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Comments on websites not being displayed/loaded
**Expected behavior:**
Should load Comments from Disqus
- Platform (Win7, 8, 10? OS X? Linux distro?):
Linux Mint 64
- Brave Version:
0.10.0
- Steps to reproduce:
    1. Navigate to a page that uses Disqus
    2. Scroll to the bottom to see if it loads comments
    3.

- Screenshot if needed:

- Any related issues:
None

**Comment by Liunkae** [comment]
Possibly fixed by 1ff038c.
