### ISSUE TITLE
[UI Design] Bookmarks Manager menu item in too many places

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#2022]
On OS X, the bookmarks manager can be opened from three different places on the menu bar:

1. Brave > Bookmarks Manager
2. Bookmarks > Bookmarks Manager
3. Window > Bookmarks Manager

Can the number of menu items be reduced?

**Comment by bradleyrichter** [comment]
not sure how it made it into the Brave menu?

![image](https://cloud.githubusercontent.com/assets/13509546/15879414/e60aac98-2cd8-11e6-808c-19d81cec4379.png)


@bbondy  could you please remove that unless you had a reason that I am unaware of?
