### ISSUE TITLE
Show the URL in the location bar for invalid URLs (instead of about:error)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2025]
It's currently pretty annoying when you type a URL for a site but you have 1 letter that is wrong.
Normally you can go to the URL bar and change the 1 letter typo.

But for us it shows about:error.

**Comment by asbjornu** [comment]
I hope the fix for this will affect `about:error` showing for network errors and all other types of errors leading to the page not being displayed too.

**Comment by sanderaarts** [comment]
Issue seems to be back: URL is replaced with about:error again.

![screen shot 2016-12-19 at 12 13 31](https://cloud.githubusercontent.com/assets/4630244/21310893/ba8753e6-c5e4-11e6-977b-b9956a74e3e7.png)
Brave 0.12.15 on OS X Yosemite (10.10.5)

**Comment by bsclifton** [comment]
Thanks for the heads up @sanderaarts; this is definitely an issue

Reopening...

**Comment by bsclifton** [comment]
+1 from @BrendanEich via https://github.com/brave/browser-laptop/issues/2302

**Comment by bbondy** [comment]
This should actually be fixed with the 0.18.x release.
