### ISSUE TITLE
Provide remapping for possible conflicting keys

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#2026]
From support: certain Linux WMs use our change tab shortcut for changing workspace.

related with #1855 

edit (@bsclifton):
It would be great to allow for disabling the shortcut for or remapping keys which the user may have conflicts for on their system

**Comment by bsclifton** [comment]
On Linux, pressing Ctrl+Q (common for stopping console output) quits Brave.  It would be great to allow for users to disable this or remap the key.  There is an open issue for [prompting on quit](https://github.com/brave/browser-laptop/issues/1515), which may help- but I edited the title for this issue to be more generic.

cc: @posix4e

**Comment by bradleyrichter** [comment]
@posix4e 

I find this a bit strange but it is certainly in the most discoverable place:

![image](https://cloud.githubusercontent.com/assets/13509546/20549103/37ba1de2-b0de-11e6-90ee-89ca80f32fe9.png)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/354
