### ISSUE TITLE
Refocusing misspelled input controls doesn't red underline

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2027]
STR:
1. Type a word wrong in an input control (note it underlines red)
2. Focus a different element (underline goes away, all good)
3. Focus the same input control

Actual behaviour:
There is no red underline for misspelled words.

Expected behaviour:
It should show the misspelled words with a red underline.

Also note:
This doesn't seem to reproduce on text areas.

**Comment by luixxiul** [comment]
This has been fixed already 👍
