### ISSUE TITLE
please add smooth scrolling

### ISSUE THREAD

**Issue by hemedani** [brave/browser-laptop#2030]
please add the smooth scrolling feature for this awesome browser in chrome we have several option for smooth scrolling which the most beautiful way to do that is installing this [app](https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb?hl=en)

**Comment by luixxiul** [comment]
It has been added since a couple of versions.
