### ISSUE TITLE
Focus change problems

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#2033]
1. if you click on a link without specifying a new tab, then when you press the "Back" button, it returns you to the top of the original page rather than the point you were at when you left.

2. when a new item is added while you are reading a site, the focus changes to the location of the new item for a moment, then returns to the point you are reading; unfortunately, if you are in the middle of a video, it also resets the video back to the start. Happens most noticeably on https://pjmedia.com/instapundit/.

**Comment by bsclifton** [comment]
Closing this issue, as it's a duplicate of https://github.com/brave/browser-laptop/issues/1766
