### ISSUE TITLE
Input discarded while Brave is launching

### ISSUE THREAD

**Issue by Superbest** [brave/browser-laptop#2039]
When I launch Brave, it takes a few seconds to load and become fully responsive. During this time, if I try typing something like "www.wikipedia.com" the first few characters are lost, and I end up with something like "ikipedia.com" in the URL bar.

Other browsers don't do this - while in the initial launch, even though response may be laggy, all keystrokes are sent to the URL bar - so by the time you finish typing, the browser will have finished loading and your URL will be ready (and loading, if you press enter).

The problem also happens if a page is a resource hog and make the UI stutter - any keystrokes typed during the brief stutter are discarded. Similarly for typing right after switching to a very resource intensive tab.

Seems like the input logic is being blocked by other things - I believe it is common practice nowadays to have input be in its own high priority thread, so I'm assuming this is a bug and not intended behavior.

**Comment by diracdeltas** [comment]
I think I saw this recently too, seems like a regression because the input used to load fast enough that it never happened. @bridiver ?

**Comment by bridiver** [comment]
It's not a regression, it just showed up less when it loaded faster. The load event wipes out the location bar and it shouldn't if there is user input there already

**Comment by Superbest** [comment]
I agree with both of you - my first guess was also that this was never a problem back when things loaded almost instantly, but now the loading is slow enough that it cannot catch up with my impatience, so I can perceive the problem.

**Comment by diracdeltas** [comment]
the loading is slow enough right now to discard some of the urlbar input ~50% of the time

**Comment by Superbest** [comment]
Well, I suppose the severity of this issue ultimately depends on the particular machine in use. However, I have seen manifest quite obviously both on a medium-spec machine as well as a high performance one.

Incidentally, I also noticed that the issue seems also present when Brave is already running and a new window is requested. This provides an easy reproduction method:

1. Open Brave.
2. In quick (or slow, depending on what you're expecting) succession, type: `Ctrl+N`, `q`, `w`, `e`, ...
3. From the first character that shows up in the URL bar and your typing speed, you can figure out how many seconds of input have been discarded (in my case, typically 2-3 secs).

**Comment by paddor** [comment]
This also applies to newly created tabs, where it's much more frustrating. Happens to me all the time. Please fix, thanks.

**Comment by bsclifton** [comment]
Closing as stale - we've had a lot of performance improvements. Let's re-open this (or comment here) if you are still experiencing the issue 😄
