### ISSUE TITLE
https instead of git+ssh package.json dependencies

### ISSUE THREAD

**Issue by flowck** [brave/browser-laptop#204]
I had a few problems of permissions when I running: npm install.

To fix that, I had to replace every git+ssh entry to https protocol, then "npm install"  ran smoothly.

SO: Ubuntu 15.04
Nodejs: 4.2.2
npm: 2.14.7

**Comment by bbondy** [comment]
Thanks for the report, I think it's fixed here, please let me know if not though:
https://github.com/brave/browser-laptop/commit/4b497270b7c245a77771bf5986f5853fb70a7234
