### ISSUE TITLE
Current tab title changes to new tab title if using 'open in new tab'

### ISSUE THREAD

**Issue by vanhalt** [brave/browser-laptop#2040]
**Did you search for similar issues before submitting this one?**
- Yes

**Describe the issue you encountered:**

- Browsing a site if you click on `open link in new tab` it will. The current tab will get the title of the new opened tab and the new tab will get the URL as the title.

**Expected behavior:**

Click a link and opening in a new tab should not alter the current tab title. The new opened tab title should change accordingly to the pages that are being browsed in that tab.

- Platform (Win7, 8, 10? OS X? Linux distro?):

OS X

- Brave Version:

```
git log
commit bb4de1fafe1a5419f7e6d2d5c6c245afdfe0bcc1
Author: yan <yan@mit.edu>
Date:   Thu Jun 2 11:32:56 2016 -0700

    Fix ad insertion invalid URL error

    window.URL sometimes threw an error that the URL was invalid. not sure why.

    Auditors: @bbondy
```

- Steps to reproduce:
    1. go to news.ycombinator.com
    2. click on a link to `open in a new tab`
    3. See how the tab title changes

- Screenshot if needed:
<img width="1096" alt="screen shot 2016-06-02 at 3 44 45 pm" src="https://cloud.githubusercontent.com/assets/1271610/15760637/a394bb0e-28d9-11e6-8625-cbad6e889112.png">

- Any related issues:

Apparently the tab arrangement has been altered since closing a newly open tab closes the closest one on the left.

**Comment by diracdeltas** [comment]
thanks for the detailed report. I saw this too but can't repro now. Could you try doing an electron upgrade? 
```
rm -r ~/electron
rm -r node_modules/electron-prebuilt
npm install
```

**Comment by vanhalt** [comment]
Yes, reinstalling electron seemed to work. I tried several times and nothing happened.

Thank you for your suggestion, guess that I can close this one now.
