### ISSUE TITLE
Inspect Element is off by about 50px or so

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2052]
**Describe the issue you encountered:**
Right clicking on text and selecting inspect element is off on Windows 7

**Expected behavior:**
Inspects the right stuff.
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Win7 but not reproducible on OS X.
- Brave Version:
  0.10.1 (and all before)
- Steps to reproduce:
  1. Go to brianbondy.com/about
  2. Right click on General Information
  3. Go to Inspect element. 

Actual results:
It inspects the image underneath

Expected results:
It inspects the text where the right click happened.

**Comment by luixxiul** [comment]
Not reproducible on Windows 10.

**Comment by bbondy** [comment]
This was a VM as well, maybe it matters.

**Comment by Liunkae** [comment]
Is this still a problem?

**Comment by luixxiul** [comment]
Closing as stale.

Let's reopen if we still experience the issue.
