### ISSUE TITLE
Notifications consistently crashing browser in Ubuntu / OSX / Windows

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2055]
http://www.bennish.net/web-notifications.html

cc @bridiver

**Comment by luixxiul** [comment]
on Windows 10 too, #1556

**Comment by bbondy** [comment]
@luixxiul does it crash on 0.10.0 too on win10?

**Comment by luixxiul** [comment]
Yes, on build 14342 as I've already reported there. Here's my comment: https://github.com/brave/browser-laptop/issues/1556#issuecomment-220865490

**Comment by luixxiul** [comment]
Not crashing anymore, but no notifications are displayed

**Comment by bridiver** [comment]
there is another bug with notifications and they may all be related. Should be fixed in the next release

**Comment by vraj201** [comment]
still crashing after displaying notification

**Comment by bridiver** [comment]
closing this in favor of #1556
