### ISSUE TITLE
Back button enabled when _blank link target opens new tab

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#2056]
STR:
- open news.google.com
- click on any article, which will open in new tab
- see back button enabled on new tab, it should not be enabled

**Comment by bbondy** [comment]
@bridiver is revamping navigation so it is probably fixed with that. Will leave it up to @bridiver to leave open or close though.

**Comment by bridiver** [comment]
yep, all of the about pages will be interstitials so they won't show up in the history. I'll close this one with the commit.

**Comment by bridiver** [comment]
a little more explanation: renderer initiated navigations (anything opened by the page and not the urlbar, bookmarks, etc...) create an 'about:blank' and the renderer updates the url. Right now the navigation controller sees the about:blank page as a navigation so it shows up in the history.
