### ISSUE TITLE
Suggestion: Please allow custom UI element colors

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#2057]
Vivaldi has recently added a very nice theme function which includes rounding tab corners/UI elements and adding different colors to different UI elements.

This would be cool to have in Brave too.

Take a look to the way Vivaldi team has done it as inspiration ;)

https://vivaldi.net/en-US/teamblog/121-snapshot-1-3-501-6-customizable-ui-themes

**Comment by srirambv** [comment]
+1 from community on customizing UI https://community.brave.com/t/gray-is-so-depressing/2091

**Comment by NelsonTriesCoding** [comment]
Would also be really great to use something like the Chrome's Stylus extension to customise our experience (like customising CSS of our favorites websites like Github, StackOverflow). I really loved this extension and I think it would be great to have a similar tool here in Brave, I feel like this is the only thing I'm actually missing.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/themes-and-colors/3432

**Comment by srirambv** [comment]
+1 from community on persona/theme skin 
https://community.brave.com/t/persona-theme-skin/7450

**Comment by newbyca** [comment]
Could you reward theme devs with Brave Payments for theme use? :)

**Comment by bsclifton** [comment]
This is a feature we unfortunately won't be able to get to before moving our codebase over to [Brave Core](https://github.com/brave/brave-browser). I've opened an issue there to track this (and theming support should already be working)
https://github.com/brave/brave-browser/issues/689
