### ISSUE TITLE
Open bookmark folder on bookmark bar on hover

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2058]
Using onMouseEnter, onMouseLeave I think.

**Comment by bradleyrichter** [comment]
I think there may be a reason why the "other" browsers aren't doing this. Do you have any examples we can try?

**Comment by luixxiul** [comment]
Probably I just thought it would make the UI consistent between this and previewing a tab on hover. Fine to close this one.

**Comment by bsclifton** [comment]
Going to mark this one as closed for now (please reopen @luixxiul if you have an example or disagree)

We pulled in a somewhat related change with:
https://github.com/brave/browser-laptop/issues/1725

Which lets you only click once- then you can move mouse and other folders auto-expand. This helps a lot :smile:
