### ISSUE TITLE
Make installation place selectable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2059]
also option to choose where to put the app's shortcut icon or to disable it.

from support:
> The one thing that I've had issues with is that the setup/installation does not install a shortcut, nor does it let me specify an installation location.

#432

**Comment by luixxiul** [comment]
+1 from support

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5285

**Comment by luixxiul** [comment]
Duping to #432
