### ISSUE TITLE
Do we need a contributing guide?

### ISSUE THREAD

**Issue by therealklanni** [brave/browser-laptop#206]
Discuss! :mega:

**Comment by bbondy** [comment]
Thanks for posting, I believe that @ElissaBeth and @BrendanEich are working on a CONTRIBUTOR.md file for the root.

**Comment by therealklanni** [comment]
Great! :metal:

**Comment by diracdeltas** [comment]
People are asking about this at the hackathon, so I think we do need a contributing.md

**Comment by bbondy** [comment]
I think the previous work I mentioned above didn't happen so contributions are welcome here and they won't conflict with previous work.

**Comment by viswanathamsantosh** [comment]
I put my thoughts in this doc< https://docs.google.com/document/d/1OJdR2LN9BPwu_6955hVnUmglS383PhEB_EaiMyu0X2o/edit?usp=sharing > .Shared it with elissa as well. feedback is appreciated to make this better.

**Comment by diracdeltas** [comment]
@viswanathamsantosh i made a contributing.md doc with more advanced instructions, but your doc would be useful for beginners, thanks. Could you open it instead as a wiki page (titled 'Tips for new contributors' or something) and link to it from the readme?
