### ISSUE TITLE
KeyPassX Auto-type incompatibility

### ISSUE THREAD

**Issue by crazymonk** [brave/browser-laptop#2060]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

I use a fork of KeyPassX that supports Global Auto-Type to automatically copy/paste passwords into login forms, and it was working fine on Brave until I updated to the latest version of Brave today (details below).

**Expected behavior:**

When pressing the Global Auto-Type keys (in my case, Shift-Command-x), the user/password stored in KeyPassX should be auto-typed into the login form displayed in Brave.
- Platform (Win7, 8, 10? OS X? Linux distro?):

OS X (10.10.5)
- Brave Version:

Brave: 0.10.1
Electron: 1.2.0
libchromiumcontent: 51.0.2704.63
V8: 5.1.281.47
Node.js: 6.1.0
Update Channel: dev
- Steps to reproduce:
  1. You'd have to install the KeyPassX fork here: https://www.keepassx.org/forum/viewtopic.php?f=5&t=1920#p3215 or try the patch here: https://github.com/keepassx/keepassx/pull/166 and then test out the AutoType hotkey functionality on a login form on Brave (it will work on other browsers) -- but what I'm really looking for here is if there's a general reason why the latest version of Brave would be blocking a keyboard event from another open app, or a keyboard paste event.
     2.
     3.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Closing as `wontfix`; I'd recommend folks try this on the new Beta version of our browser:
https://brave.com/download-beta
