### ISSUE TITLE
windows installer places Brave in "Brave Inc" folder instead of "Brave" or "Brave Software"

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2061]
cc @aekeus @bbondy @bradleyrichter 
I think "Brave Software" makes the most sense, other opinions?

**Comment by aekeus** [comment]
I like no spaces "Brave" but not a strong opinion

**Comment by bridiver** [comment]
That's ok too, but I remember seeing some complaint about distinguishing Brave from the Brave movie app or something like that. "Brave Software" should make it clear

**Comment by aekeus** [comment]
That makes sense. "Brave Software" is more specific.

**Comment by dogancelik** [comment]
`C:\Program Files\Brave` is best

**Comment by luixxiul** [comment]
How about placing it on ``C:\Program Files\Brave Software``?

**Comment by bbondy** [comment]
Where do you see a `Brave Inc` folder? 

<img width="460" alt="screenshot 2016-06-04 07 47 01" src="https://cloud.githubusercontent.com/assets/831718/15799374/9cc5f248-2a28-11e6-837e-b07765670739.png">

<img width="538" alt="screenshot 2016-06-04 07 47 14" src="https://cloud.githubusercontent.com/assets/831718/15799375/a04febd0-2a28-11e6-8933-2d3831d9eb88.png">

Electron winstaller (the component we use) doesn't support installing in Program files right now.  Also moving it into a higher integrity folder will mean we need to have a UAC prompt on each update which we don' want.  Or install a second NT service like Mozilla has or tie into the windows task scheduler.  All probably overshadowed by other priorities right now.

**Comment by bsclifton** [comment]
@bridiver do you know if this is still an issue?

Recent installs on Windows are showing for me in:
`%userprofile%\AppData\Local\brave`

with session data stored in:
`%appdata\brave%`

**Comment by bridiver** [comment]
yea, that location has always been correct. Brave Inc was in the "start" menu

**Comment by srirambv** [comment]
Still shows Brave Inc on Windows 10 x64 https://github.com/brave/browser-laptop/pull/8060#issuecomment-293956479

**Comment by bsclifton** [comment]
@srirambv sorry I had forgotten to get you steps (the cache might be cleared by now).  I'll post issues in the comment
