### ISSUE TITLE
Windows crash when clicking on links in Gmail

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2064]
On Windows, clicking on links in Gmail crashes.

**Comment by Superbest** [comment]
+1, steps to reproduce:

1. Open Gmail
2. Compose new email:

![sup](https://cloud.githubusercontent.com/assets/124334/15794158/734c17aa-29ae-11e6-90b0-fda749debdef.png)

3. Send.
4. Open email, click link.
5. Shazam!

Also middle click to open in new tab explodes too.

**Comment by bbondy** [comment]
@bridiver fixed here https://github.com/brave/electron/commit/0d905b68ea8aa944bb6b2e2a32e31e6df885b227
