### ISSUE TITLE
crashing more frequently, and it lost bookmarks/pins/etc.

### ISSUE THREAD

**Issue by MisChef** [brave/browser-laptop#2065]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
brave crashed. it lost all my pins and my passwords & bookmarks

**Expected behavior:**
not have shit crash, not lose bookmarks & passwords.

- Platform (Win7, 8, 10? OS X? Linux distro?):
x.11.5

- Brave Version:
0.10.0

- Steps to reproduce:
    1. not sure :-(  i wouldn't have done it in the first place!

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
The crashing more frequently should be fixed in 0.10.2.
We believe the lost bookmarks should also be fixed there as we think it was related to zombie processes which should no longer happen.  Sorry to hear you encountered this :(  Let us know if you see this again after 0.10.2 though.
