### ISSUE TITLE
Save session storage file in a more safe way

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2067]
Currently we do an fs.writeFile which is not atomic.  It would be safer to do fs.writeFile to a temp file, and after it is written then rename to overwrite. We could also keep a copy of last several files perhaps.  This will avoid data loss in the future.

**Comment by bbondy** [comment]
@bridiver Should we wait on this in case we are going to chromium storage instead?

**Comment by bsclifton** [comment]
Is the Chromium storage different than a browsers local storage? Do you have more info? (curious to know more)

**Comment by bsclifton** [comment]
One thing that would be cool, maybe as a separate feature, would be if you can export your session. I often export / back up my bookmarks

The ideal situation for me would be to store my session on OneDrive (basically forcing a bookmark sync)

**Comment by bsclifton** [comment]
https://github.com/brave/browser-laptop/pull/2180 ready for review cc: @bbondy

**Comment by diracdeltas** [comment]
@bsclifton I think chromium storage is referring to https://developer.chrome.com/extensions/storage
