### ISSUE TITLE
Different settings on about:preferences are displayed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2071]
**Describe the issue you encountered:** When I click "edit global settings" from Bravery Menu, the previous/different settings are selected on about:preferences ("Bookmarks Toolbar settings" and "Advanced privacy settings"). Also no favicon is displayed on that tab.

**Expected behavior:** 

- Platform (Win7, 8, 10? OS X? Linux distro?): Windows 10, Ubuntu

- Brave Version: v0.10.2 Dev Channel, Master Branch

- Steps to reproduce:
    1. Open about:preferences
    2. Go to any URL
    3. Click Bravery Menu
    4. Select "edit global settings"

- Screenshot if needed:
![temp](https://cloud.githubusercontent.com/assets/3362943/15796533/4cada1c2-2a3a-11e6-9cd4-9c8ccb1f9bb3.gif)

- Any related issues:

**Comment by bbondy** [comment]
Nice find, cc @diracdeltas it seems like the one from edit Bravery settings is using default values.

**Comment by diracdeltas** [comment]
I saw this exact bug before 398e3ff6 fixed it; I can't repro anymore. Are there any console errors?

**Comment by diracdeltas** [comment]
Specifically, the problem was that `brave-about.js` wouldn't run on `about:` pages if there was a `#` in the URL

**Comment by luixxiul** [comment]
The only thing I see is 
````
frame.js:318 Denying load of chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/undefined. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.(anonymous function) @ frame.js:318tryOnImmediate @ timers.js:543processImmediate @ timers.js:523
frame.js:318 GET chrome-extension://invalid/ net::ERR_ADDRESS_UNREACHABLE
````

**Comment by diracdeltas** [comment]
I see those errors but the only discrepancy for me is that the `Block canvas` box isn't checked when it should be. will investigate more

**Comment by bbondy** [comment]
For me it seems to be only what I changed is different. Which is a few things on the general I use to test (home button on vs off, homepage customized vs brave.com) and block canvas.
