### ISSUE TITLE
keep URL in address field so user can edit when resolve fails

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2072]
**Did you search for similar issues before submitting this one?**
No. But its new...

**Describe the issue you encountered:**

Brave clears the URL on this alert page which then makes it much more difficult to fix the URL and try again.

**Expected behavior:**

Bad URL stays in address bar.

- Platform (Win7, 8, 10? OS X? Linux distro?):

Mac OS latest

- Brave Version:

0.10.2

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/13509546/15796930/36b7e1d4-29bd-11e6-9636-4a9f198accca.png)

**Comment by bbondy** [comment]
dupe of https://github.com/brave/browser-laptop/issues/2025 ?

**Comment by bradleyrichter** [comment]
![image](https://cloud.githubusercontent.com/assets/13509546/15797005/dbce44b4-29be-11e6-982e-a9be527ddd99.png)
