### ISSUE TITLE
bookmark is invisible if favicon.ico is not found

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2075]
**Describe the issue you encountered:** bookmark is invisible in "show only favicon mode" if favicon.ico is not found (404)

**Expected behavior:**  a class should be added so that it can be styled
- Brave Version: Master Branch
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/15798023/b8d06bac-2a65-11e6-9e73-28ba3e775db0.jpg)
- Any related issues: #1739, #2073

**Comment by bbondy** [comment]
Maybe show a generic file icon in this case?

**Comment by luixxiul** [comment]
or ``border: 1px dotted``?

**Comment by bbondy** [comment]
@bradleyrichter for final say

**Comment by bsclifton** [comment]
This is a tough one... even if you're in the regular bookmarks toolbar view, it happens (just 16 pixels of dead space). I like the idea of showing a generic icon

The hard part of this defect is... it throws a 404 at the CSS level when the background-image: url(); part evaluates. It'll show the 404 in the JavaScript console, but I'm not sure how to intercept this.  The ideal solution would be to intercept this, remove the background image CSS attribute and then add the classes "fa fa-file-o"

**Comment by bradleyrichter** [comment]
We should follow Chrome or FX lead on this one.

**Comment by cezaraugusto** [comment]
@bradleyrichter Chrome sets its own "paper" icon for bookmarks. Can we have one as well?

**Comment by bradleyrichter** [comment]
yes please. 

FA file-o

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5826#issue-191388793
