### ISSUE TITLE
When having tab previews a hibernated tab should not be fully woken up

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#2080]
**Describe the issue you encountered:**
When having tab previews activated, the tabs should not be fully woken up

**Expected behavior:**
Tabs should become hibernated again after moving away from a tab preview
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Windows 8.1, 64 Bit
- Brave Version:
  0.10.2
- Steps to reproduce:
  1. Having some tabs open
  2. Move your mouse over a tab to have a preview
  3. Tab is fully woken up

**Comment by bbondy** [comment]
I think this can be generalized into an auto unload over time task but this can be a factor in what is considered.

**Comment by SJ-Diamond** [comment]
Best option would still be if the user would be able to unload a tab manually. Would resolve that issues in an instant :)
