### ISSUE TITLE
Fingerprinting protection ignores per-site setting on link navigation

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#2082]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When navigating from a link to a site with fingerprinting protection turned off, the fingerprinting protection still works anyway. The settings are only respected when going to the site directly (i.e. typing in the site in the address bar).

**Expected behavior:**
Fingerprinting protection should respect per-site settings in all situations.

- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X

- Brave Version:
0.10.2

- Steps to reproduce:
    1. Go to a site with fingerprinting (e.g. [https://html5test.com/](https://html5test.com/))
    2. Turn off fingerprinting protection on the Bravery Panel
    3. Close the tab and open a new tab
    4. Use a search engine to find the site (e.g. [https://duckduckgo.com/?q=html5test](https://duckduckgo.com/?q=html5test)) and click on it
    5. Open the Bravery Panel again

- Screenshot if needed:
![screenshot](https://cloud.githubusercontent.com/assets/19424103/15800884/614ead68-2a4b-11e6-9f6c-80ef8e400551.png)

- Any related issues:
None

**Comment by luixxiul** [comment]
Confirmed on Windows 10 too
