### ISSUE TITLE
preferences for tabs handling

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2084]
from support:
> how I can manage my preferences for tabs? I’d like to have links open in the same tab, or choose by right-block if I wish open in the next tab. thanks

**Comment by bbondy** [comment]
do other browsers have an option which suppresses the a target and window.open to force same tab?

**Comment by luixxiul** [comment]
I don't think so.

**Comment by bbondy** [comment]
I think it can cause some problems with things like login if we allowed this and users would be in a worse state and not realize what's wrong. If you feel strongly we can re-open but will close for now.
