### ISSUE TITLE
Question: Can you keep the ability of good font rendering?

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#2089]
Google removes in Chromium 52 the better font rendering with removing support to deactivate DirectWrite on their quest to remove the last supporting code for older operating systems.

Which will leave tons of people with bad font rendering. This will also affect Brave. Any hope that you can  avoid that?

Links:

https://codereview.chromium.org/1919573002
and
https://bugs.chromium.org/p/chromium/issues/detail?id=579196

**Comment by bbondy** [comment]
I don't think we allow to deactivate DirectWrite right now so I don't think there is a benefit to differentiate here right now.

**Comment by bsclifton** [comment]
I don't believe there is anything we can do to actually "fix" this (ex: keep DirectWrite); that logic all lies in Chromium.  But removing the `enable-use-zoom-for-dsf` flag will help ensure that text is crisp and readable, especially on higher DPI machines
