### ISSUE TITLE
Javascript error after build

### ISSUE THREAD

**Issue by timothytavarez** [brave/browser-laptop#209]
<img width="428" alt="screen shot 2016-01-20 at 12 59 59 pm" src="https://cloud.githubusercontent.com/assets/16512835/12461388/d64910ea-bf75-11e5-9ab3-8ecd3151b75d.png">

OS X 10.11.1

Performed clone from repo, installed via NPM (no errors, I think), created .app and then built the .dmg - but no dice.

Do I just repeat the install/build process?

`
Uncaught Exception:
Error: Cannot find module '/Applications/Brave.app/Contents/Resources/app/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Brave.app/Contents/Resources/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)`

**Comment by bbondy** [comment]
Did you `npm install` already?  Also please ensure you have the latest node install (v5)

**Comment by brakmic** [comment]
Same here, on Win 10 x64, with **node 5.4.1**

![err](https://cloud.githubusercontent.com/assets/56779/12462593/722351e4-bfbf-11e5-85f7-00aedb338516.png)

**Comment by tomru** [comment]
Experienced the same issue on Linux with node 4.x.

After switching to node 5.4.1, removing `node_modules` folder and another `npm install` the issue was solved for me.

**Comment by bbondy** [comment]
@tomru almost definitely the issue, thanks. 

Likely people npm installed with 0.12 or similar and then upgraded. We use 3 native modules currently for fast tracking protection, adblock and https everywhere (which uses sqlite).   Those need to be built with 5.4.1.

A faster solution may be to just run the postinstall which re-builds these native modules:

> npm run postinstall

**Comment by bobpoekert** [comment]
I ran `npm run postinstall`, and it printed a bunch of stuff about sqlite3 when it was running, but after running `npm run build-darwin` and launching the .app I still got the error.

<img width="421" alt="screen shot 2016-01-20 at 2 33 42 pm" src="https://cloud.githubusercontent.com/assets/45596/12465458/fa32dfce-bf82-11e5-951c-e99c60b9ef85.png">

**Comment by bbondy** [comment]
@bobpoekert can you confirm if you're on Node 5.5? If so, please make sure you clear out your node_modules directory first and then npm install.

**Comment by qbig** [comment]
#221 seems to have the same symptom. Confirm running 5.5. tried 'rm -rf node_modules' before npm install

**Comment by epu** [comment]
Hit this on El Capitan with old node 4. Upgrading to confirm. If this is an issue, can we mention node version constraint / requirement in readme, and/or assert during build?

**Comment by bbondy** [comment]
> Hit this on El Capitan with old node 4. Upgrading to confirm. If this is an issue, can we mention node version constraint / requirement in readme, and/or assert during build?

Yep that's merged now in the README.

**Comment by epu** [comment]
For some reason, this didn't actually fix this for me. I tried also clearing out the npm cache manually. The new npm 5.5 was installed with n, and isn't first in my PATH, and it was invoked with its fq path to run the build step. I still had an sqlite v46 folder, so I symlinked it to v47, and it runs. Trying a few things to narrow this down.
