### ISSUE TITLE
Bookmarks Toolbar Spacing

### ISSUE THREAD

**Issue by Banditz71** [brave/browser-laptop#2093]
In my Bookmarks Toolbar, I have folders (on the left) as well as individual bookmarks......the way it is now, the Folder names are being squeezed down to as little as ONE letter.......I believe the folders should have priority and always show their full name.  Is this possible?  Thanks!

**Comment by luixxiul** [comment]
Closing this in favor of #1743

**Comment by Banditz71** [comment]
Thank you!
