### ISSUE TITLE
Video and script

### ISSUE THREAD

**Issue by Maxmaxextreme** [brave/browser-laptop#2097]
Before this last update Brave blocked the video on Yahoo but allowed me to use the message board. Now brave allows both and there is no way to stop the video feed without giving up my ability to use the message board. Can you install a way to block unwanted video so that it doesn't eat up my bandwidth? Sites don't care about using my MB, but I do and I don't want them owning my megabytes.

Thank you.

**Comment by luixxiul** [comment]
> Can you install a way to block unwanted video so that it doesn't eat up my bandwidth? 

Disabing Autoplay would work now.

**Comment by bsclifton** [comment]
@Maxmaxextreme if you are still using Brave, there is now a setting like @luixxiul has mentioned 😄   You can see it on the security tab in preferences:
![screen shot 2017-05-31 at 8 58 59 am](https://cloud.githubusercontent.com/assets/4733304/26641441/7868f1b0-45df-11e7-9c94-df2666315f65.png)

We default to `Always allow` (for now), but you can choose `Always ask` to get the behavior you want (stop autoplay and prompt)
