### ISSUE TITLE
Pushing ESC 2 times on devtool causes a crash

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2100]
**Describe the issue you encountered:**  Open devtool with ``F12``, push ``ESC`` 2 times, and the browser crashes

- Platform (Win7, 8, 10? OS X? Linux distro?): Windows 10 (Build 14342)

- Brave Version: 0.10.2

- Steps to reproduce:
    1. ``F12``
    2. ``ESC`` 2 times

This is not reproducible on Ubuntu with the master branch, so it might be specific to Windows 10 or has been fixed already on that branch.

**Comment by cezaraugusto** [comment]
@luixxiul couldn't reproduce this issue on OSX also. Windows specific (can't test on Windows now)?

**Comment by luixxiul** [comment]
I think so too. Confirmed on another Windows 10 machine.

**Comment by luixxiul** [comment]
Crash happens on the browser console (``alt+shift+J`` and ``ESC`` 2 times) too.

**Comment by bbondy** [comment]
Confirmed reproduces on win7x64, content dev tools 2nd Esc crashes.
Confirmed does not reproduce on OSX.
cc @bridiver

**Comment by bridiver** [comment]
haven't tested on win10 yet, but can't reproduce on win7x64

**Comment by bridiver** [comment]
since @bbondy was able to reproduce on win7x64 and I'm no longer able to reproduce I'm going to close this

**Comment by luixxiul** [comment]
@bridiver that's the error which happens only on Windows 10 I remember

**Comment by luixxiul** [comment]
I tried on Windows 10 and could not reproduce it ;-)
