### ISSUE TITLE
Google gmail chat (old style, not hangouts) doesn't work

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2101]
There was a report about Google gmail chat not working. Upon further investigation I seen this:

Console shows this error:

> 2rs=AHGWq9Bv0g-kvi7K0nSne4jfMeX5Hv4iuA:161 Uncaught CustomError: Error in protected function: window.chrome.runtime.connect is not a function

cc @bridiver

**Comment by luixxiul** [comment]
+1 from support

**Comment by bsclifton** [comment]
I had issues with both this and hangouts when I had fingerprint protection mode on.  @luixxiul, do you know if there are clear STR?

**Comment by bbondy** [comment]
@diracdeltas should we show notification bar for known sites that don't work when FP is on maybe with never show message again?

**Comment by diracdeltas** [comment]
@bbondy that's a good idea

**Comment by bsclifton** [comment]
If we do want to do that, we can spec it out with https://github.com/brave/browser-laptop/issues/2965

**Comment by cgjones** [comment]
I just upgraded to 0.11.6 and am seeing an issue with gmail chat --- it's now asking me to log in:
<img width="206" alt="screen shot 2016-09-01 at 9 13 11 am" src="https://cloud.githubusercontent.com/assets/325916/18175009/8cc6f0b2-7024-11e6-965f-f66b285c65fc.png">
I've never seen this on gmail before.

Is this a symptom of this issue or should I file a new one?  Thanks.

**Comment by jkup** [comment]
just started seeing this too

**Comment by bridiver** [comment]
I'm not seeing the js error, that issue was fixed a while ago, but I do see
Uncaught SecurityError: Blocked a frame with origin "https://hangouts.google.com" from accessing a frame with origin "https://mail.google.com". Protocols, domains, and ports must match.

**Comment by bridiver** [comment]
the cors issue isn't the problem, it appears to be an issue with blocking local storage and it works if you allow all cookies

**Comment by bbondy** [comment]
@bridiver note that there's old style chat (Google chat) and new style chat (hangouts). Both are broken but for different reasons.

Google chat / Google talk was EOL'ed in 2013 but you can still use it in Gmail if you revert to old style chat.

I filed https://github.com/brave/browser-laptop/issues/3703 to describe a hangouts problem.

**Comment by bbondy** [comment]
And actually there's there's a second bug I posted for hangouts independent of the above one.
The one I posted above is if you are already signed in from another browser and you try to send a message it fails.

The one Chris mentioned above I posted for here: #3704

**Comment by bbondy** [comment]
Both of the hangouts issues are fixed and will be in 0.12.0 for those of you following along. This issue being left open for old style gchat as the title suggests.

**Comment by srirambv** [comment]
I do not see gmail chat on Brave at all.  This is on 0.12.0 RC1 with shields turned off.

![image](https://cloud.githubusercontent.com/assets/17010094/18246419/7de34590-7363-11e6-8ef6-c36546640c1c.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18246461/b751b0d2-7363-11e6-87ee-9c09526719e8.png)

**Comment by bbondy** [comment]
I think it has to be turned on in settings.

**Comment by srirambv** [comment]
The old gmail chat has now been replaced by hangouts as default. Closing this thread as its obsolete now
