### ISSUE TITLE
General Settings: "Brave is not your default browser" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2105]
Functionality:
Button: 
For each specific OS, the button may require a different action/script.

Mac OS - Utilize available API to toggle OS level setting, and show the standard dialog.
Dialog sample:
![image](https://cloud.githubusercontent.com/assets/13509546/15841218/498ec892-2c04-11e6-93f4-461c9073b723.png)

Windows: Either toggle the default browser setting and show the Windows standard confirmation dialog, or open the windows CP if the API is not available. (Win 7 vs 8 vs 10 for example)

Linux: Same as windows.

Switch:
"Always check on startup" is on by default, but may be switched off by the user.

Item label:
"Brave is not your default browser"

Button label:
"Set as default..."

Switch label:
"Always check on startup"

Settings window:
![image](https://cloud.githubusercontent.com/assets/13509546/15841251/a548eb04-2c04-11e6-83a8-fe86f46587c0.png)

Startup Sheet Dialog: (slides down from below tabs toolbar)
![image](https://cloud.githubusercontent.com/assets/13509546/15841714/033d20a6-2c08-11e6-9a6f-f04beb2efd9b.png)

And setting toggle state: (when Brave is your default browser)

The button hides and the "startup check" switch moves up.
![image](https://cloud.githubusercontent.com/assets/13509546/15841747/60cfe1ae-2c08-11e6-8005-82b184e74cc4.png)

**Comment by darkdh** [comment]
Front end work is finished in https://github.com/brave/browser-laptop/tree/default-browser
And it works for Mac now. Working on electron API for windows and linux.
