### ISSUE TITLE
General Settings: "A new tab shows" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2106]
Functionality:
"my new tab page"
- shows the current version of a new tab page (blank white at time of writing)

"my home page"
- shows the currently defined home page

"my default search engine"
- shows the home page of the currently set default search engine

Item label:
"A new tab shows"

Menu choices:
"my new tab page"
"my home page"
"my default search engine"

menu snapshot:
![image](https://cloud.githubusercontent.com/assets/13509546/15841942/c9566968-2c09-11e6-91f4-ca7c4db0cc5b.png)

Settings panel: (item for this issue shown in blue)
![image](https://cloud.githubusercontent.com/assets/13509546/16354107/fa11c16e-3a3d-11e6-8b10-79baefa4c0ea.png)

**Comment by kingscott** [comment]
Any chance this has been taken on? I just started the early stages of writing something of this sort. Any chance I could work on it or collaborate? @bradleyrichter

**Comment by bradleyrichter** [comment]
@kingscott We'd love to have your help! 

This has not been started yet, besides what is currently implemented in today's release in the general prefs panel which is limited to startup, not a new tab view. 

For code review, we can ask @bridiver or @bbondy .

**Comment by kingscott** [comment]
Great, thanks @bradleyrichter! I was jumping into it today at the end of my work day. Is that settings panel mentioned in the above image what has been agreed upon for production?

**Comment by bradleyrichter** [comment]
Hey @kingscott - I just updated it for you. But, please don't bother with the visual elements because we are currently working on a branch which is a complete prefs makeover.

We will have to merge your new code with the new UI work. Shouldn't be a problem...

If you want to take a look at the progress on that branch, here it is:

https://github.com/brave/browser-laptop/tree/cherry-picked-ui-updates

**Comment by kingscott** [comment]
Hey @bradleyrichter, just a quick opinion question for functionality. I have had a few ideas for this new tab stuff

**Comment by bradleyrichter** [comment]
I’m all ears…

**Comment by kingscott** [comment]
Sorry about that, I had thought and didn't mean to write the comment (was trying to overcomplicate the task). 

Also, did you want (or need) the new tab page created that has the tiles of previously visited pages?

**Comment by bradleyrichter** [comment]
@kingscott We would love the help on anything you are interested in working on. Here is a screen shot of the currently proposed "Top Sites/Info Page" but I haven't finished the details in the spec. 

![image](https://cloud.githubusercontent.com/assets/13509546/16402841/88a9ac58-3ca4-11e6-9309-229fd06c76c2.png)

When you mouse-hover over the topsite thumbs, you would get the full page preview rendered behind the shadow masking:

![image](https://cloud.githubusercontent.com/assets/13509546/16402867/cc38abe0-3ca4-11e6-9f17-55ef842683fd.png)


There will be a neat UI to change the layout of the top site icons by clicking on a toggle button to change from 1, 2 or 3 rows, and a list view.


Let me know if this looks interesting to you...

Thanks!
Brad

**Comment by kingscott** [comment]
Wow, that looks really nice! Honestly - the top image looks awesome.

Is that something you (Brave) would want me to build? In terms of the background, I do have a [project](https://github.com/kingscott/newton) I worked on that pulls in nice backgrounds. I have a Chrome [extension](https://chrome.google.com/webstore/detail/newton/ogkmipmkbppmcmdgeomnhlbgijbijjpi?hl=en-GB) for it as well. If that was of interest, I can extend and/or integrate with Brave. PS. It's in React as well.

**Comment by bradleyrichter** [comment]
Hey Scott - can I invite you to join our #community slack channel?

Also - I installed the chrome extension. Looks good. I think this is right up your alley.  :  )

**Comment by kingscott** [comment]
Sure, that would be great Brad!

**Comment by bradleyrichter** [comment]
@kingscott Just invited you as a contributor...

**Comment by kingscott** [comment]
Yes @bradleyrichter, I got it - thanks!

**Comment by bsclifton** [comment]
Original work done in PR https://github.com/brave/browser-laptop/pull/3488

**Comment by 0xMF** [comment]
Please bring back the empty New Tab option (applies to v. 0.12.9; win32; x64).

**Comment by luixxiul** [comment]
#5652 addressed the issue but I would have to say I preferred the option than leaving the home page URL empty.
