### ISSUE TITLE
General Settings: "Browser data import" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2107]
Functionality:
Choosing "Import now..." opens the Import Browser Data dialog which floats above the General Settings panel. (This dialog is modal to all other functionality within the browser settings panels.)

The pull-down menu list is populated by polling the OS for installed browsers that have at least one data type that can be imported. Each browser offers a different set of importable data types. The available toggle switches change dynamically based on the selected browser, becoming disabled to indicate lack of availability.

Safari: Preferences, Bookmarks
Chrome: Cookies, Browsing History, Bookmarks
Firefox:  Browsing History, Bookmarks, Saved Passwords, Autofill form data
Superset: Browsing History, Bookmarks, Cookies, Preferences, Saved Passwords, Autofill form data

Item label:
Browser data import

Button string:
"Import now..."

Spec image: (issue item shown in blue)
![image](https://cloud.githubusercontent.com/assets/13509546/15842809/31b916de-2c11-11e6-9766-d0c0490ff443.png)

Spec image with import dialog open:
![image](https://cloud.githubusercontent.com/assets/13509546/15843030/6108f24a-2c13-11e6-9de0-4c0e65608eae.png)

**Comment by bsclifton** [comment]
Does this cover https://github.com/brave/browser-laptop/issues/1004? If so, maybe we can close that old one out :smile:

**Comment by darkdh** [comment]
We will add an option to import bookmark html in importer (handled in chromium) so we will replace the old method when importer is ready.

**Comment by darkdh** [comment]
Follow-up

- [ ] preferences
- [ ] saved passwords
- [ ] autofill form data

**Comment by bradleyrichter** [comment]
too many cobwebs on this one. closing...
