### ISSUE TITLE
General Settings: "Enable Auto Title Bar" item

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2109]
functionality:
This feature is a view toggle for the auto-change on hover title bar.

Mac: On by default
Windows: Off by default (until extra windows title bar can be removed)
Linux: Off by default

reference issue number: ?

string: 
"Enable Auto Title Bar"

Spec image: 
![image](https://cloud.githubusercontent.com/assets/13509546/15843299/04fe9038-2c16-11e6-99b4-d7ea61764063.png)

**Comment by kumarrishav** [comment]
This issue is about: changing string from "Enable Magic Title Bar" to "Enable Auto Title Bar". Am i right? or There is something i didn't understand about this issue.

**Comment by bradleyrichter** [comment]
this is old and no longer relevant. Thanks for the bubble-up!
