### ISSUE TITLE
General Settings: "Save my downloads here" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2110]
Functionality:
Providing a user-definable default downloads destination allows for a more efficient user work flow when downloading files. The default path is their downloads folder. This path can be changed by clicking on the pencil (edit) button. This opens a download location chooser dialog which is OS specific.

A toggle switch (off by default) allows the user to change the setting to ask them for the desired location upon each file download.

item label:
"Save my downloads here"

toggle switch label:
"Always ask me where to save files"

Download location sheet-dialog in Mac:
![image](https://cloud.githubusercontent.com/assets/13509546/15843435/01090886-2c17-11e6-9eca-64d0f98e30de.png)

Spec image: (this issue in blue)
![image](https://cloud.githubusercontent.com/assets/13509546/15843317/2d0cee76-2c16-11e6-8330-8f8da22c69bb.png)

**Comment by NejcZdovc** [comment]
It's really annoying not having this and select folder for every download. Will add this :smiley:

**Comment by bradleyrichter** [comment]
Yes! TY!

**Comment by Liunkae** [comment]
> A toggle switch (off by default) allows the user to change the setting to ask them for the desired location upon each file download.

This is what I get on a fresh install:
![image](https://cloud.githubusercontent.com/assets/19424103/24280708/bf5e32a0-1020-11e7-9257-f41a61f2bc45.png)
Should the switch be on or off by default?

**Comment by NejcZdovc** [comment]
I set it to on by default yes. If we go with the off by default, then I think we would need to set default path when browser is first lunched, otherwise it would be strange to have empty input and option to off

cc @bradleyrichter
