### ISSUE TITLE
General Settings: "Bookmarks Bar" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2111]
functionality:
"Text only'
- Default selection, and only shows the text from the bookmarks database. This setting is the most compact in height.

"Text and Favicons"
- This shows the associated favicon to the left of each text label. If a favicon is missing, it will display a generic file/page icon. If the bookmark item is a folder, it will show the folder icon.

"Favicons only"
- only favicons will be shown. If a favicon is missing, it will display a generic file/page icon. This is the most compact view horizontally. 

Toggle switch:
- This setting is OFF by default to save "chrome" space in the toolbar area. This toggle is attached to the context menu for show/hide of the bookmarks bar.

item label:
"Bookmarks Bar"

item list menu:
"Text only'
"Text and Favicons"
"Favicons only"

Toggle switch label:
"Always show the bookmarks bar"

![image](https://cloud.githubusercontent.com/assets/13509546/15843613/6285d1f6-2c18-11e6-81c8-b62fa489fea7.png)

**Comment by dawikur** [comment]
It would be also great to have option like 
"Show only in new tab"
So if I do ```<Ctrl> + t``` it will be visible until I go to any page.
