### ISSUE TITLE
General Settings: "Language" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2112]
This item is present but needs to be relocated according to the spec image. 

![image](https://cloud.githubusercontent.com/assets/13509546/15843738/5fef6460-2c19-11e6-99b8-ebdf684ec367.png)

**Comment by Liunkae** [comment]
I assume this issue has been abandoned…

**Comment by luixxiul** [comment]
@Liunkae I think instead this was superseded with #6782
