### ISSUE TITLE
General Settings: "Brave always stays updated" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2113]
Functionality:
Autoupdate for brave can not be disabled by the user. This is to provide the best, safest experience. The switch toggles the appearance of the Alert bar notification whenever a new browser version is detected as available. Turning this off will disable the notification but updates will still happen on restart.

item string:
"Brave always stays updated."

toggle switch string:
"Also notify me when an update is available"

Spec image:
![image](https://cloud.githubusercontent.com/assets/13509546/15843875/58ab7ddc-2c1a-11e6-90cf-dba48ed89019.png)

**Comment by johnmarzan** [comment]
i still have a slow internet connection. i prefer to update my browser when i am not busy, like in firefox.

at least give us the option to turn off autoupdate. but make the update notification persistent.

**Comment by Liunkae** [comment]
Related discussion: #1877 ("Allow user to choose when to download update")
