### ISSUE TITLE
Clear browser cache when idle

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2118]
**Expected behavior:** Clear browser cache when idle.
https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/

> Defend yourself against ETag tracking and other cache-based black-hat techniques by configuring Self-Destructing Cookies to automatically clean your cache every time you are not actively using the browser.
- Any related issues: #629

WDYT @diracdeltas? Isn't this kind of defending worth implementing?

**Comment by diracdeltas** [comment]
I don't think this should be the default policy since users will have to manually add exceptions for cookies they want to persist if any. Would be a good option to add to @bradleyrichter's cookie prefs panel though.

**Comment by luixxiul** [comment]
Sorry I only meant setting a time limit for preserving caches. Automatically removing them after a couple of idle minutes for example.

**Comment by tomlowenthal** [comment]
This issue has made the jump to brave-browser#869 .
