### ISSUE TITLE
Use of external translations under BSD 

### ISSUE THREAD

**Issue by nashe** [brave/browser-laptop#2120]
Aloha,

You recently added on Transifex some error messages from the Chromium project (`errorMessages.properties`). [They have already been translated by the French team on launchpad](https://translations.launchpad.net/chromium-browser/translations/+lang/fr) and are [licensed under BSD](https://help.launchpad.net/Translations/LicensingFAQ). 

Do you see any reason not to use it?

**Comment by bbondy** [comment]
if they are licensed under BSD that's fine. But they still need to go into Transifex.
