### ISSUE TITLE
Open bookmarked page with a single click

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2121]
**Describe the issue you encountered:** To open a bookmarked item on `about:bookmarks` you have to double click the url, which I think is annoying for some users.

**Expected behavior:** I think it should be a single click, but this would make a UI inconsistent between `about:bookmarks` and `about:downloads`.

https://github.com/brave/browser-laptop/blob/master/js/about/bookmarks.js#L64

**Comment by bradleyrichter** [comment]
agreed. thanks @luixxiul 

(BTW - the bookmarks manager will be getting an overhaul soon)

**Comment by bbondy** [comment]
The single click was going to be reserved for a selected state, so if a user wants to select multiple then move to a folder for example.

**Comment by luixxiul** [comment]
Spec images would ge appreciated @bradleyrichter :-)

**Comment by luixxiul** [comment]
I don't see any other requests and find issues with the current way, so I'm going to close this as wontfix
