### ISSUE TITLE
Search Settings Panel: Search engine table

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2123]
Functionality:
In version 1.0, we will have a non-editable list of search engines and will add more based on user demand until later when a user-definable UI is implemented.

The only UI functionality within the list panel is the "Default" column buttons. They user may define any of the search engines to be the new default by clicking in the default column to the left of the engine name. Only one X will be displayed, and the line will be highlighted in 10% opacity of Brave orange.

The list should be fixed-sorted alphabetically until we later implement multiple search engine results in the results window. (The current default search engine is Google at the time of this writing.)

Engine Go Keys serve as quick overrides to the default engine. (leading the search term with "/B" will send the search terms to Bing instead of Google - for example. This shortcut is only valid for one time, returning to default when the next search is performed without a leading shortcut. 

![image](https://cloud.githubusercontent.com/assets/13509546/15880730/e3876996-2ce4-11e6-8628-cc59c1e9ec4a.png)

**Comment by bsclifton** [comment]
Closing this issue as I believe we have all the functionality implemented (and our table looks better than spec 😄 )

cc: @bradleyrichter just in case I am missing something
