### ISSUE TITLE
Search Settings Panel: Search Bar Options

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2124]
Functionality:
These 3 options provide search term matches to the data currently in the browser. Each option can be toggled on or off.

If the user clears their history, no matches will be displayed for history even though the item is enabled in this settings panel. 

Title string:
"Search Bar Options"

Item strings:
"Show tab matches"
"Show history matches"
"Show bookmark matches"

Spec image: (issue items are in blue)
![image](https://cloud.githubusercontent.com/assets/13509546/15882213/6acf01be-2cf1-11e6-9da0-5b184ccbd3f2.png)

**Comment by Liunkae** [comment]
As of 0.11.5, the settings are already implemented. Some cosmetic changes are still needed to match the spec: the items should be reordered, and some texts should be changed.
