### ISSUE TITLE
Search Settings Panel: Search Bar Options: Autocomplete

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2125]
functionality:
As the user types their search term in the URL bar, suggested autocomplete words are suggested, allowing the user to save time when they see the result that matches their expectation.

This requires new development and possibly a service. ( @bbondy ?)

This item is off by default.

item string:
"Autocomplete search term as you type"

![image](https://cloud.githubusercontent.com/assets/13509546/16175676/1c278ba4-35ab-11e6-92a7-324563a17d8e.png)

**Comment by bbondy** [comment]
We do have the autocomplete already in code but someone removed the shortcut from the menu at some point called Open Search... which opened the URL bar in search mode.  So that code just needs to be found / refactored.

**Comment by kumarrishav** [comment]
@bradleyrichter @bbondy Can we have more input on this? As we already have this functionality in browser, what are we exactly trying to achieve here.

**Comment by bradleyrichter** [comment]
@kumarrishav you are achieving a much needed purging of non-auto-closed issues that have already been completed. Thanks!
