### ISSUE TITLE
Show All History is not Clickable

### ISSUE THREAD

**Issue by yadyadun** [brave/browser-laptop#2126]
**Did you search for similar issues before submitting this one?**
Yes and I couldn't find a similar issue.
**Describe the issue you encountered:**
I couldn't click on "Show All History".
**Expected behavior:**
It won't show.
- Platform (Win7, 8, 10? OS X? Linux distro?):
Win 10
- Brave Version:
0.10.2
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![screenshot 2](https://cloud.githubusercontent.com/assets/17423566/15887750/8713e89e-2d96-11e6-860e-89c238a999b2.png)

- Any related issues:

**Comment by luixxiul** [comment]
It has been already noted here: #444 Closing this in favor of that.
