### ISSUE TITLE
Trying to build on Windows 10. NPM is missing.

### ISSUE THREAD

**Issue by leahnnovash** [brave/browser-laptop#213]
I know this is a silly issue. I am a GIT newbie here. So bear with me. I am missing the NPM app for the 3rd step onward. Where do I get it?

**Comment by diracdeltas** [comment]
I'm not a windows user but i think NPM should come with Node if you download here: https://nodejs.org/en/download/

**Comment by leahnnovash** [comment]
Thank you. That solved the problem.
