### ISSUE TITLE
Double clicking on a file that is downloading should queue the open request

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2133]
Currently it just tries to open and fails. It should queue the request and execute it when the download is finished.

**Comment by bridiver** [comment]
On windows the file doesn't open even if the download is complete

**Comment by bbondy** [comment]
@bradleyrichter could you provide a UI mock for which message we should show when it is in a pending open state?

**Comment by bradleyrichter** [comment]
Easier solution: Change downloading text string to:

"Opening when ready..."

Keep progress bar in background.
