### ISSUE TITLE
crash when using 1Password login list in mini menu

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2134]
- open Brave on Mac OS
- confirm it is the default browser in system settings
- open 1Password
- login to 1Password using the mini menu
- select any login

Result: Brave crashes instantly

Expected: page should open with credentials in form fields, and automatically submit login form.

cc @bridiver 

![image](https://cloud.githubusercontent.com/assets/13509546/15903853/a251f17e-2d63-11e6-97ad-afa551649122.png)

**Comment by bridiver** [comment]
also crashes when selecting a login for a different page from the context menu. Normally that would open a new window
