### ISSUE TITLE
Remember full screen mode in session storage

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2135]
A user from support was asking why we didn't remember the full screen setting as he always wanted it to start on his page full screen.

**Comment by cezaraugusto** [comment]
Would like to try implementing it, can I?

**Comment by bbondy** [comment]
yes it seems similar to this one though, so take note there for review comments:
https://github.com/brave/browser-laptop/pull/2029

**Comment by bbondy** [comment]
cc @bsclifton @bridiver in case they have any comments.

**Comment by bridiver** [comment]
I think we can roll all of this into a general window size restore. Maximized and Fullscreen could be represented with -1 and -2 size or something similar

**Comment by cezaraugusto** [comment]
@bridiver Is @bsclifton PR on hold due to this? If so, think he can handle it better. Anyway waiting for his thoughts :)

**Comment by bridiver** [comment]
the PR is on hold because it will maximize every window on restore if any single window is maximized

**Comment by bridiver** [comment]
but if we're going to remember window size, we might as well handle all of them together

**Comment by bsclifton** [comment]
Will definitely adjust the code per the comments :smile: 

I think this issue is a dupe of one of the following:
https://github.com/brave/browser-laptop/issues/928
https://github.com/brave/browser-laptop/issues/146

**Comment by bsclifton** [comment]
@cezaraugusto this issue is ready if you're up for it :smile:  The PR I had open has been merged:
https://github.com/brave/browser-laptop/pull/2029

**Comment by cezaraugusto** [comment]
@bsclifton, thanks but I'm going to leave it for now, lots of work here. Feel free to keep going :+1:,  Anyway I'm following closely this issue. :eyes:

**Comment by bsclifton** [comment]
Awesome, I'll go ahead and grab this
