### ISSUE TITLE
Tab Settings Panel 

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2137]
Functionality:

The tab settings panel for 1.0 includes user definable items.
1. The choice to open new tabs to the right of the current tab or at the end of the tab sequence.
2. Changing the default setting for how many tabs are displayed in each tab set.
3. Ability to disable the tab previews feature.
4. Ability to disable the tab coloration which is based on theme or background top color.

Strings:

Title:
"Tab Settings"

Open new tabs item string:
"Open new tabs"

Option strings:
"To the right"
"At the end"

Tab set number item string:
"Number of tabs per tab-set:"

Option strings:
"6"
"8"
"10"
"20"

Tab preview switch string:
"Show tab previews on mouse-hover"

Tab color item string:
"Show tabs in page theme color"

Spec image:
![image](https://cloud.githubusercontent.com/assets/13509546/16748450/009dc4cc-4779-11e6-9e34-bd6f1958cc41.png)

**Comment by SJ-Diamond** [comment]
Would be also great if we users would be able to decide where we can have the placement of a new opened tab - at the end of all tabs, or to the right/left of the active tab. As this is also a very basic tab functionality.

**Comment by bradleyrichter** [comment]
@SJ-Diamond 

Added it into 1.0 just for you  :   )

**Comment by bradleyrichter** [comment]
CC: @BrendanEich

**Comment by srirambv** [comment]
Cycle tabs between most recently used would be a good option too.

**Comment by yannduran** [comment]
👍

**Comment by NejcZdovc** [comment]
@bradleyrichter I will implement Open new tabs and would like to know if we still use side by side positioning or is everything one after another. I also added #6553 so we will have 3 dropdowns.

**Comment by NejcZdovc** [comment]
@luixxiul you mentioned that you would like to design this panel, I am ready to implement `Open new tabs` drop down :smiley:

**Comment by NejcZdovc** [comment]
I think that when #6907 is done, this issue can be closed

**Comment by bradleyrichter** [comment]
revision to this original issue and more!

![image](https://cloud.githubusercontent.com/assets/13509546/22488797/e9eb229c-e7c8-11e6-8955-5ce385a16c59.png)

**Comment by luixxiul** [comment]
BTW @bradleyrichter have you know the sync icon on the left bar would be replaced with the pyramid ones?

**Comment by luixxiul** [comment]
@NejcZdovc if you would create a PR to add "Open new tabs" dropdown, I would like to add design commits to the PR to close the issue.

**Comment by NejcZdovc** [comment]
@luixxiul it's already here :smile: #6958

**Comment by luixxiul** [comment]
Yeah I noticed it just now. I will create a PR to polish if necessary and close the issue :-)

**Comment by luixxiul** [comment]
I reset the milestone to `0.13.3` based on the instruction by @bbondy

**Comment by luixxiul** [comment]
#6982 asks @bradleyrichter to revise the mockup again.

**Comment by NejcZdovc** [comment]
@luixxiul @bradleyrichter what is still missing here?

**Comment by luixxiul** [comment]
I've forgotten it, sorry I'm not sure.

**Comment by NejcZdovc** [comment]
I will close this one, if we are missing something, please reopen.

**Comment by brendaalicia** [comment]
Hello, I just updated my browser to the new version and I can't find the option "Number of tabs per tab-set". Can anyone help me?

**Comment by bsclifton** [comment]
Hi @brendaalicia (sorry for the late response)

That feature isn't present in the new version of Brave yet. You can track progress by subscribing to https://github.com/brave/brave-browser/issues/35 😄

**Comment by brendaalicia** [comment]
@bsclifton Thank you 😄
