### ISSUE TITLE
Typo in app.properties

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2141]
**Describe the issue you encountered:**
> You can access this site by clicking the Brave icon in the top **left** corner and temporarily disabling 'Block Phishing / Malware'. This is not recommended!

https://github.com/brave/browser-laptop/blob/6df6faca56a68acd083007d2d590d9f1b62495b5/app/extensions/brave/locales/en-US/app.properties#L33

**Expected behavior:** Isn't it top **right**, not left?

**Comment by bbondy** [comment]
yep, fixed. Thanks.
