### ISSUE TITLE
Execution renders non-usable UI

### ISSUE THREAD

**Issue by atoponce** [brave/browser-laptop#2142]
Installed the latest 0.10.3 version on my Debian Sid 64-bit laptop via the Debian package. I don't see a SHA256SUMS file for the .deb, so I don't know if I have all the bits. Downloading 3 separate times, and verying the SHA-256 of each package yields:

```
$ sha256sum brave-*.deb
129b2aff557a74af1fdf357672067927331f0750a3863d76c4fa69583c6d1578  brave-1.deb
129b2aff557a74af1fdf357672067927331f0750a3863d76c4fa69583c6d1578  brave-2.deb
129b2aff557a74af1fdf357672067927331f0750a3863d76c4fa69583c6d1578  brave-3.deb
```

Installed via:

```
$ sudo dpkg -i brave.deb
```

Executing `/usr/bin/brave` produces the following screenshot:

![brave](https://cloud.githubusercontent.com/assets/699572/15930242/0ab5e724-2e0f-11e6-969e-9bf7a012a2d9.png)

This is running in the Awesome WM, so window borders and title bars are not drawn. However, you can see there is no UI also. No address bar, forward/back buttons, etc.

**Comment by luixxiul** [comment]
I'm going to close as this stale.
