### ISSUE TITLE
Search querys containing long-width space interpreted as URL

### ISSUE THREAD

**Issue by jeifour** [brave/browser-laptop#2143]
**Did you search for similar issues before submitting this one?** #519 and #2002 might be related.

**Describe the issue you encountered:** I'm trying to search for something using the address bar but my search queary which doesn't look like a URL gets interpreted as one so I have to manually open up DDG instead to search for it.

**Expected behavior:** If I don't input something that looks like an URL then it should try to search for that term instead.

- Platform (Win7, 8, 10? OS X? Linux distro?): Linux, Manjaro

- Brave Version: 0.10.2

- Steps to reproduce:
    1. Input a string that isn't an URL, contains at least one Japanese character (Kana or Kanji) and at least one long-width space enclosed by any other characters. Examples: "あ　a", "楽譜　主よ、人の望みの喜びよ", "テスト　テスト" (I'm not sure if there are other possible combinations of characters that don't work, this is just what I could find after playing with it for some time.)
    2. Get redirected to an error page that the URL couldn't be found because it most likely doesn't exist. (Unless you go to something like はじめよう.みんな which is in fact a valid address.)
    3. That's it.

- Screenshot if needed:

- Any related issues: In general IDNs being displayed in their encoded form is not so pretty or human-readable.

**Comment by luixxiul** [comment]
Confirmed. Search strings containing an em space "テスト　テスト" caused an error as follows:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/15932770/dfc7baea-2e97-11e6-82e0-612edb16bec9.jpg)

**Comment by jeifour** [comment]
Ah well I guess the space is "responsible" here. Searching for "a　a" also doesn't work. So Japanese characters probably aren't connected to this issue then.

**Comment by luixxiul** [comment]
Thanks for the quick fix, @bbondy :-)
