### ISSUE TITLE
ExtremeTech doesn't load

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2145]
**Describe the issue you encountered:**
Went to http://www.extremetech.com/extreme/220025-comcast-begins-rolling-out-docsis-3-1-based-gigabit-home-internet

Looked like the page loaded correctly, but then it flashes to a broken version and shows error message: "The site has failed to render properly due to an issue encountered with a plugin you are using."

Maybe some ad-blocker-blocker issue? If so, the site's error message is less than helpful.

**Expected behavior:**
Shows website correctly.

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows 10

- Brave Version:
0.10.3

- Steps to reproduce:
    1. Go to http://www.extremetech.com/extreme/220025-comcast-begins-rolling-out-docsis-3-1-based-gigabit-home-internet

**Comment by cezaraugusto** [comment]
Yes, seems like the page block its content if an ad-block thing was found, purposely behaving like this.

Investigating to see how Brave can handle such cases.

**Comment by luixxiul** [comment]
To block scripts is a workaround here.

**Comment by diracdeltas** [comment]
they are using this script:
```
window._sp_=window._sp_||{},window._sp_.config=window._sp_.config||{},window._sp_.config.account_id=48,window._sp_.config.publisher_base="//sp.extremetech.com/axyz",window._sp_.config.gpt_auto_load=!1,window._sp_.config.enable_rid=!0,window._sp_.config.content_control_callback=function(){function clean(node) {for (var n = 0; n < node.childNodes.length; n++) {var child = node.childNodes[n];if (child.nodeType === 3) {node.removeChild(child);n--;} else if (child.nodeType === 1) {clean(child);}}} clean(document); document.body.innerHTML +='<div style="position:fixed;top:47%;width:100%;height:auto;z-index:9999;background:#fff;border: 1px solid #000;text-align:center;"><br><br><h3>The site has failed to render properly due to an issue encountered with a plugin you are using.</h3><br><br></div>';console.log("content control callback triggered")},document.addEventListener("sp.blocking",function(o){document.querySelector('.leaderboard').style.display = 'none';__ZDGPT.AdPackage = __EXTECH.adSlotRecovery; console.log("sp.blocking detected"),window.sourcepointTripwire=!0;try{__ZDPB.LoadandResetGpt();var n=document.getElementById("toprightrail"),e=document.getElementById("bottomrightrail");"undefined"!=typeof n&&null!=n&&"undefined"!=typeof e&&null!=e&&(n.setAttribute("id","toprightrailblocked"),e.setAttribute("id","bottomrightrailblocked"))}catch(i){console.log("Load and reset gpt ad calls - "+i)}}),window.spBootstrap("http://static.extremetech.com/etbroker/js/spt.js");
```
