### ISSUE TITLE
Retry button on about:error

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2147]
**Describe the issue you encountered:** The retry button on ``about:error`` is not well styled.
![](https://cloud.githubusercontent.com/assets/3362943/15939852/9bfaef86-2eb4-11e6-941e-e0af340b4aea.jpg)

I'm pushing a PR to fix this into:
![](https://cloud.githubusercontent.com/assets/3362943/15939874/b65e684e-2eb4-11e6-8455-29660a76b098.jpg)

**Comment by diracdeltas** [comment]
Thanks, could you also fix #1545 (similar issue) while you're at it?

Also it would be nice if the "An error occurred..." text were darker so it's easier to read.

**Comment by diracdeltas** [comment]
D'oh, didn't realize that was already fixed. Sorry.

**Comment by luixxiul** [comment]
Yeah but I think it could be improved. I'll look at it soon.
