### ISSUE TITLE
Win 10 - 'How do you want to open this file' - Brave name's is Update

### ISSUE THREAD

**Issue by ElenaZhuk** [brave/browser-laptop#2148]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
In the window 'How do you want to open this file' - Brave is displayed with 'Update' name
**Expected behavior:**
Display with correct name
- Platform (Win7, 8, 10? OS X? Linux distro?):
  Win 10
- Brave Version:
  0.10.3
- Steps to reproduce:
  There is a file without extension.
  1. Double-click on the file 

Actual result: How do you want to open this file - window appears.
Brave is displayed as Update.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/19841324/15940348/af9defe0-2e49-11e6-835b-e4de8dd03a13.png)
- Any related issues:
  Steps:
- Right-click on a html file
- Select Open with 

Actual result: there is two Brave icons with different names: Brave and Update:
![image](https://cloud.githubusercontent.com/assets/19841324/15940474/391bffd2-2e4a-11e6-94f8-79f7e53fe2c7.png)

**Comment by bsclifton** [comment]
Confirmed this is now fixed 😄 

The auto-updater (which was previously known as Update.exe) has been renamed to Brave.exe.  We got this for free when updating our muon-winstaller (our fork of electron-winstaller) which uses Squirrel

Here's a screenshot of how it looks now:
![screen shot 2017-09-09 at 9 37 57 am](https://user-images.githubusercontent.com/4733304/30241989-ba0aab7e-9542-11e7-8713-9727ca5f4afd.png)
