### ISSUE TITLE
rouge popup / new page

### ISSUE THREAD

**Issue by ads2003uk** [brave/browser-laptop#2154]
Initially opening the browser a New sportsbet.io tab on opening brave browser - despite having homepage as starting page & Block Ads.
Visiting "faucetgame.com" or any gaming site a new page after a period of more than 30mins a new tab opens for sportsbet.io, and freezes all activity on browser page including close function.
- Platform Win7 (other users of site have also experienced the use 7. 8 & 10)
- Brave Version: 0.10.3
- Steps to reproduce:
  1. New sportsbet.io tab on opening brave browser - despite having homepage as starting page
  2. New sportsbet.io tab page on visiting site. 
  3. Faucetgame.com Site owner also tested via various browsers and it is limited to chrome.
     (Site owner states for your records that it relates to "cointraffic advertising")

**Comment by bridiver** [comment]
@ads2003uk is the notification bar active when you navigate to the other url? If so this is a duplicate of https://github.com/brave/browser-laptop/issues/1726 and a temporary workaround is to close the notification bar (click allow or deny) prior to navigating.

**Comment by ads2003uk** [comment]
Hi,
No Navigation Bar to allow or deny.

Upon clicking anywhere on the page, the additional tab opens for Sportsbet.io and in the original tab the blocked sportsbet.io advert is displayed.
Trying to close the new tab results in the browser freezing.

Additional information - the sportsbet.io also contains "trafficnado.com".
I have followed instructions on how to remove trafficnado-com pop-up ads (https://malwaretips.com/blogs/remove-trafficnado-com-ads/) but still exists within Brave browser.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community 😄

https://community.brave.com/t/discussion-https-github-com-brave-browser-laptop-issues-2154/10037

Let's keep discussion on this issue if this is still an issue 👍 Thanks!

**Comment by ads2003uk** [comment]
The link to the new topic you are referring to is the actual link to my
post 2154?

**Comment by luixxiul** [comment]
Yes, let's discuss the issue on the community 😄
