### ISSUE TITLE
disable recently discovered MS telemetry code insertion in VS 2015

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2156]
VS 2015 is inserting telemetry code into all c++ binaries - https://www.infoq.com/news/2016/06/visual-cpp-telemetry 
can be disabled by adding notelemetry.obj to linker options

**Comment by bbondy** [comment]
Any idea when Update 3 comes out which should remove this?

**Comment by luixxiul** [comment]
Closing as stale. If that telemetry code is still out there, please reopen this 👍
