### ISSUE TITLE
How you guys solve "post form with "target" " problem

### ISSUE THREAD

**Issue by 0neSe7en** [brave/browser-laptop#2161]
I use electron, but encountered this problem: [Post form with “target” attribute sending GET request instead of POST](https://github.com/electron/electron/issues/2816)(https://github.com/electron/electron/issues/2816). 

I found you solved this problem very well. I don't know if convenient to tell how you solved it ? Thanks.

**Comment by bbondy** [comment]
We maintain a different fork of electron, you can find it here:
https://github.com/brave/electron/commits/master

Our opener code is rewritten by @bridiver

**Comment by jackyq2015** [comment]
@bbondy Is it possible to create a PR to merge the opener part into electron?
