### ISSUE TITLE
Disabling tab preview does not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2163]
From support:
> In "preferences when "show tab previews on hover" is unselected it does not keep. When reopening the browser it previews on hover.
>
> I rebooted and it continues to display when hovering over the tab.

**Comment by diracdeltas** [comment]
seems to work for me, though this would have happened on about pages with a URL fragment prior to https://github.com/brave/browser-laptop/commit/f88b80e601d385191707a7f7f0b98b07c93cd60c

**Comment by cezaraugusto** [comment]
Worked here too.

Based on @diracdeltas referenced commit, I'm going to close it until someone reports that it's still happening.
