### ISSUE TITLE
show some sort of UI for passive (display) mixed content

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2168]
## Test plan

https://github.com/brave/browser-laptop/pull/7571#issue-212891887

----

**Describe the issue you encountered:** I tried to add a class to `urlbarIcon` on mixed content pages, and noticed that `isMixedContent` did not seem to be ready yet though it was mentioned here: https://github.com/brave/browser-laptop/blob/master/js/components/siteInfo.js#L18

Because of it the siteInfo panel on https://mixed-script.badssl.com/ says that the site is secure where it should not, though the script is blocked.

**Comment by bbondy** [comment]
This is probably legacy from when we were based on Gecko.  cc @diracdeltas

**Comment by diracdeltas** [comment]
yup, `isMixedContent` is not hooked up to anything yet. it's fine that we show https://mixed-script.badssl.com/ as secure since the active mixed content (scripts) is blocked from running by the mixed content blocker. we should show a warning of some kind for passive mixed content though.

**Comment by luixxiul** [comment]
I see, then how about changing ``This site is secure`` to ``Secure connection`` as Firefox does?

**Comment by diracdeltas** [comment]
@luixxiul sure, i would accept that

**Comment by bridiver** [comment]
Related https://github.com/brave/browser-laptop/pull/3447
https://github.com/brave/browser-laptop/issues/3651
Wondering if we should provide a visual notification that mixed content was blocked?

**Comment by ayumi** [comment]
bump

Saw that some amazon product pages ([example](https://www.amazon.com/Fluorostore-F015031-Fractional-Tubing-Semi-Transparent/dp/B00KJDB3P4)) load some images over http. It would be sweet to allow blocking of passive mixed content or at least show an icon.

<img width="537" alt="screen shot 2016-12-03 at 20 08 34" src="https://cloud.githubusercontent.com/assets/521861/20864015/55987566-b994-11e6-8a0a-ce6c342f467c.png">
<img width="469" alt="screen shot 2016-12-03 at 20 05 51" src="https://cloud.githubusercontent.com/assets/521861/20864004/ee791b74-b993-11e6-8cfd-d9e49bc5d054.png">

Chrome – for comparison:
<img width="322" alt="screen shot 2016-12-03 at 20 08 03" src="https://cloud.githubusercontent.com/assets/521861/20864017/64c6c1f0-b994-11e6-80bc-2f6dcfbd57e0.png">
<img width="544" alt="screen shot 2016-12-03 at 20 07 54" src="https://cloud.githubusercontent.com/assets/521861/20864016/613e197a-b994-11e6-8b5d-3346250f4805.png">

**Comment by diracdeltas** [comment]
chrome shows the insecure UI for passive mixed-content pages. i propose we show the insecure (unlocked) icon but in grey instead of red so it's somewhat less scary.
