### ISSUE TITLE
Find a better data source than Alexa top 500 sites for urlbar suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2172]
https://twitter.com/brianbondy/status/742185223656509440

Some sites that don't fit come up as suggestions.

**Comment by luixxiul** [comment]
It would be nice if sources are switched based on language settings.

**Comment by bbondy** [comment]
We could have a different default list for each locale inside ` app/extensions/brave/locales/*/` and use English when no specific file exists.  This would probably be managed outside of Transifex I think though. cc @aekeus

**Comment by aekeus** [comment]
That makes sense. I wonder if there is a language / country specific topN dataset available to us.

**Comment by luixxiul** [comment]
On twitter https://twitter.com/obmarg/status/759038182029725697

**Comment by srirambv** [comment]
Surprising Gmail doesn't come up as a suggestion. 

![image](https://cloud.githubusercontent.com/assets/17010094/17286387/44d483b2-57c1-11e6-9598-0f713895ffe9.png)

**Comment by bbondy** [comment]
@srirambv I'm going to fix the one you mentioned here for gmail and mail.googlle.com, but please start to manually curate `js/data/top500.js` for things you think should be there as you discover them. And keep this issue open to track it like I do.  Just do a pull request on the code as you add them, thanks!  You might want to setup a dev environment as well to test out the changes you make.

I think the only way we will fix this one is incrementally over time as we notice things.

**Comment by luixxiul** [comment]
Here is an Alexa 500 ranking in Japanese: http://www.alexa.com/topsites/countries/JP

Is it possible to use that?

**Comment by bbondy** [comment]
Based on locale selection? Ya it should be pretty easy. Please start by leaving this open but do a pull request to add it next to the localization .properties files. Please remove any sites like porn sites or malware first though. Also if you think anything doesn't add value to be in the list remove it.

**Comment by MargarytaChepiga** [comment]
I was trying to find a file where I could check the existing data and maybe add some more, but I couldn't. `js/data/top500.js` does not exist. Am I looking in a wrong place?

**Comment by srirambv** [comment]
@MargarytaChepiga `js/data/top500.js` isn't used. Its replaced with bloodhound.
https://github.com/brave/browser-laptop/blob/9fa998955e2b38c9751b916d3bd9d3bfbad4ad16/app/common/lib/siteSuggestions.js#L5

**Comment by bsclifton** [comment]
@srirambv I don't think bloodhound handles the alexa top sites. The file with domains (which is passed as input) is found here:
https://github.com/brave/browser-laptop/blob/master/app/common/data/topSites.js

Site suggestions are optionally added when URL bar text changes:
https://github.com/brave/browser-laptop/blob/46a3b05646be013efffc8ed1eb931ebde66bda2d/app/browser/reducers/urlBarSuggestionsReducer.js#L97-L100

Bloodhound is only used for history, IIRC
