### ISSUE TITLE
Clearing cookies for a site also clears saved zoom settings

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2173]
Zoom level should be saved when clearing site data.

**Comment by bbondy** [comment]
I think that's currently meant to clear everything, but cc @diracdeltas 
This might already be covered by other UI Brad has issues for.

**Comment by diracdeltas** [comment]
there should probably be a checkbox item for 'Clear all site settings' in https://github.com/brave/browser-laptop/issues/1413

**Comment by luixxiul** [comment]
This was fixed.
