### ISSUE TITLE
Page Nav buttons allow dragging of window

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2176]
The window should not drag when user moves mouse after click.

User should be able to cancel action by releasing mouse up outside of button.

(this is certainly required for the upcoming long-press back-history popup menu)

**Comment by bbondy** [comment]
The fix for this is just to now allow dragging of the window on top of the back button. You are ok with that right?

**Comment by bradleyrichter** [comment]
@bbondy do you mean above the back button? (in the 3 pixel high area)

**Comment by bbondy** [comment]
no worries I got it.
