### ISSUE TITLE
How to tell if browser sent DNT from JavaScript?

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#2177]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Even if an experimental feature, when writing JavaScript, you cannot get the state of DNT using the ways [described on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack):
window.doNotTrack
navigator.doNotTrack
navigator.msDoNotTrack

This works great w/ Chrome.  The DNT header is indeed sent, the window or navigator element is just not set.

**Expected behavior:**
either navigator.doNotTrack or window.doNotTrack would be set to true if the user selects the "Send a Do Not Track header" in the preferences

- Platform (Win7, 8, 10? OS X? Linux distro?):
Windows

- Brave Version:
latest

- Steps to reproduce:
    1. Launch Brave, open https://clifton.io
    2. Click the bravery icon (shield settings)
    3. Notice that "Ads and Trackers Blocked" is 1

My code is checking all documented DNT settings and will not initialize Google Analytics (so the count should be 0) and will also [log a polite message to the console if DNT is sent](https://github.com/clifton-io/clifton.io/blob/master/js/app.js#L17)

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
good catch, thanks
