### ISSUE TITLE
SETTINGS: Spell-check: Languages

### ISSUE THREAD

**Issue by generic-user** [brave/browser-laptop#2183]
**Did you search for similar issues before submitting this one?**
Yes, terms: `spell check` `spell-check` `language`
**Describe the issue you encountered:**
Is it possible to change the spell-check language, similar to chrome?
**Expected behavior:**
Right click --> set language ...

**Comment by bbondy** [comment]
Setting the language in the general pane also changes the spell check language. Is there a need to set it differently from your language?

**Comment by generic-user** [comment]
### Selected language
In my **preferences**, on the **general pane**, the selected language is _Dutch_. The language that is being used for spell-checking, is _English_.

#### Here is an image of the preferences pane:
![Preferences pane](https://lh3.googleusercontent.com/-n9vtxyThlLo/V2JSvRE2OuI/AAAAAAAAGyU/enqR_cXphyg/s0/Brave_2016-06-16_09-17-41.png "Preferences pane -> GENERAL")

### Here is on image of the spell-checking in action:
![spellcheck](https://lh3.googleusercontent.com/-XIO0AEy-D3Y/V2JTwwe3q_I/AAAAAAAAGyg/ePuTVXzVaYU/s0/Brave_2016-06-16_09-22-03.png "Spell-checking in action.")

### Multi language support
I **definitely** have a need to be able to **switch between multiple languages**. My main language is dutch, but I do type a lot of English as well. So switching between spell-checking languages is a **must**.

#### How it should work:
For an example of how to implement it, one can look at how it was done in Chrome. [spell-checking in chrome](http://www.ghacks.net/2015/12/10/google-changes-multi-language-spell-checking-options-in-chrome/ "Implementation of multi language spell-checking.").

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5845

**Comment by svenl77** [comment]
+1 It's really hard to answer in different languages with brave. Multilingual support is super important. Many of us work in there default language but need english and other languages in a daily basis because the net is global!

**Comment by bbondy** [comment]
which operating system?

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/7167)

**Comment by Liunkae** [comment]
+1 from #8226

**Comment by ForumLiker** [comment]
How can I change the spell-checking?

**Comment by abakim** [comment]
@generic-user it doesn't work with Spanish language.
Definitely I can't use this browser professionally if I don't have minimally a spell-checker to write without some spelling error.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/spanish-spelling-checker/3800

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/bitdefender-addons-please-spelling-correction/3465/2

**Comment by benpro** [comment]
The priority of this issue should be bumped to maximal… This is a really important feature!

**Comment by argumento** [comment]
+1 I really need the ability to switch from english to spanish. I'm running Brave in Linux (ubuntu), I hope Brave will be compatible with some of the linux compatible dictionaries (hunspell, aspell).


Thanx for a great Browser!!

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/when-will-be-added-spelling-checker-in-other-languages-different-than-english/4957)

**Comment by Jacalz** [comment]
+1 from me

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/spell-check-doesnt-work-for-languages-other-than-english/5099?u=eljuno)

**Comment by hugobuddel** [comment]
+1 this makes brave useless for me half the time. Having the red wiggles is very annoying

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/build-in-auto-correct-only-in-english/5572)

**Comment by CapitanPlanet** [comment]
+1 extra important

**Comment by L4rryk** [comment]
+1 it is irritating me! Hope it will B fixed.

**Comment by Mibou** [comment]
+1

**Comment by polygon5** [comment]
+1

**Comment by mintho** [comment]
+1

**Comment by manuscle** [comment]
+1

**Comment by rodolfoghi** [comment]
+1

**Comment by zentagonist** [comment]
Likely solution - follow your local language / regional settings.

**Comment by Liunkae** [comment]
Related: #3691 (Spellcheck language should depend on keyboard layout)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/rechtschreibkorrektur-deutsch-duden/7227?u=eljuno

**Comment by wouthoekstra** [comment]
+1 switched back to Chrome because of this (for now). Both my windows and Brave settings are set to English, but I do need to type a lot of Dutch. Typing now is unbearable now with all the squiggly lines, which also cannot be disabled.

**Comment by generic-user** [comment]
I see a lot of people suggesting that spellcheck should follow language OS/keyb layout/...

I must say as someone who writes in _multiple languages daily_, it is **a bad idea to do that**. I **do not** switch my keyboard layout when I'm switching between languages (let alone the keyboard itself), nor do I switch my language of OS/browser. 
No everything remains the same, all I would like to change is the actual language the spell checking is done. Regardless of any other setting within my enivrement.

**The best way is like in chrome, there we can have spell check for multiple languages at once.**

**Comment by Armondz** [comment]
+1 this could be only issue, that keeps me from completely migrate to Brave.

**Comment by GGurtner** [comment]
Please, please, do not make spellcheck language follow the keyboard layout, this is going to be a nightmare for people like me constantly switching between languages and keyboards!

+1 to changing spellcheck language with a right click

**Comment by Acme908** [comment]
Waiting for spell check to Portuguese Brazil.
Brave only have Portuguese BR in interface, but not in spell check

**Comment by marcospds** [comment]
This issue has been resolved? Temporary until I can solve it, I made a backup of the file en-US-7-1.bdic and I overwritten it inside ~\AppData\Local\brave\app-0.19.53\Dictionaries by the file pt-BR-3- 0.bdic from Chrome, while retaining the name en-US-7-1.bdic.

**Comment by darkdh** [comment]
@marcospds nice hack. I'm working on it and almost finish. Please stay tune for a little while :wink:

**Comment by Acme908** [comment]
@marcospds WHOA!
I had uninstalled Brave, I'll try it now

**Comment by marcospds** [comment]
Do you use Windows?
With Brave open, open the task manager, find brave.exe under Process, click with right and go to "open file location".

**Comment by hugobuddel** [comment]
I was really excited about this fix, but now I'm disappointed. It seems that it is necessary to restart Brave when changing the spell check language?

I switch languages several times a day. My native tongue is Dutch, but about half of my communication is in English (mostly the professional part). So half of my emails are in Dutch, the other half in English. It should not be necessary to restart the browser ten times a day only to compose text in different languages.

**Comment by bbondy** [comment]
why not just add both language?

**Comment by hugobuddel** [comment]
Yeah I figured that it's possible to use multiple languages, so did that now.

I got confused because the spacing between 'language' and 'enable spellcheck' is smaller than the subsequent spacing between 'enable spellcheck' and 'spellcheck languages'. So I thought that 'enable spellcheck' referred to the 'language' just above and didn't notice the more distant 'spellcheck languages' below it. Yeah seems stupid in retrospect, but [don't make me think](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515) is a good approach to usability.

All the other switches correspond to the item above the switch (like the bookmark-bar switch); that is, the structure of the general settings page seems to be: dropdown/textfield/button optionally followed by  switches. Only the spellcheck section has the order inverted. The other settings pages have section headers and those pages are much clearer; perhaps add headers to the general settings as well?

**Comment by Darkfae** [comment]
+1 for the option to select multiple languages.

I'd also like to see more language options as well. The language settings are super limited right now, and it's driving me a bit nuts - being told my spelling is incorrect when I know it's right is a huge turn off.

**Comment by Liunkae** [comment]
@Darkfae You can use multiple languages. See Preferences > General > Spell Check Languages. Here's an example of English and Spanish:

![](https://user-images.githubusercontent.com/19424103/34922599-b48de0e8-f957-11e7-90be-e63d5411a358.png)
