### ISSUE TITLE
Per site Bravery "Block Scripts" toggle broken

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2188]
Can be reproduced on brianbondy.com

**Comment by bbondy** [comment]
cc @bridiver @diracdeltas probably something that landed recently.

**Comment by diracdeltas** [comment]
Works for me on master now. Have you git pulled recently?

**Comment by aekeus** [comment]
Yes, pulled latest from master this morning.

**Comment by aekeus** [comment]
Replicated on OSX and Ubuntu

**Comment by diracdeltas** [comment]
@aekeus what are your default bravery settings?

**Comment by aekeus** [comment]
"Block Scripts" is off in preferences panel.

**Comment by diracdeltas** [comment]
I cleaned session store and went to https://brianbondy.com/, then disallowed scripts from the Bravery panel, and it seemed to work. what exactly is broken?

**Comment by aekeus** [comment]
Confirmed in master. This must be a build issue. Closing.

**Comment by bridiver** [comment]
fyi - this was briefly broken in master yesterday
