### ISSUE TITLE
Global "Block Phishing / Malware" toggle broken

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2189]
Global preferences toggle operating correctly.

Can be reproduced at excellentmovies.net

**Comment by aekeus** [comment]
Replicated on OSX and Ubuntu

**Comment by diracdeltas** [comment]
also weird that it seems to work for me. 
1. clean session store
2. load excellentmovies.net, confirm that it's blocked
3. toggle about:preferences#privacy setting for Block Phishing Malware
4. open new tab, excellentmovies.net loads

**Comment by aekeus** [comment]
Confirmed in master. Build issue. Closing.
