### ISSUE TITLE
sqllite issue

### ISSUE THREAD

**Issue by bkardell** [brave/browser-laptop#219]
I've tried this a number of times and I'm not sure what's going wrong, all attempts to fix it lead to other disarray...  

Node v4.2.4/OSX 10.9.2 - as I said, I've tried this a number of times and the install _usually_ goes off without a hitch.  `npm run watch` also appears to startup just fine.  BUT - npm start yields:

```
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.2/docs

Error: Cannot find module '/Users/bkardell/projects/browser-laptop/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'
```

In lib I find v46 instead of v47.  Googled this and no solution I've found seems to work (granted I am only trying things I can actually understand rather than just blindly pasting solutions) - as near as I can tell it seems to be some weird oddity with node-gyp and sqlite, but I'm having no luck.  Just me?

**Comment by bbondy** [comment]
Could you try clearing out your node_modules, then doing another `npm install`?  Use the latest node, like v5.5.0.  You can Install nvm or n if you need to maintain multiple node versions.

**Comment by jaydson** [comment]
Same here.
I'm on Ubuntu 14.04 with Node.js v5.5.0.

```
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.2/docs

Error: Cannot find module '/browser-laptop/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'
```

**Comment by bbondy** [comment]
@jaydson can you confirm if you npm installed with 5.5?

**Comment by jaydson** [comment]
It seems like it's working now. I removed the `node_modules` folder and did another `npm install`.
I have a different issue related to webpack, so I'll find or create another thread.

Thanks @bbondy

**Comment by bbondy** [comment]
No problem @jaydson, thanks for reaching out!
@bkardell please re-open if you need some help getting it to work, but it should work given the above fix.
