### ISSUE TITLE
Cannot remove password in about:passwords [ubuntu only]

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2190]
Both the X icon and the delete all link not functional in Ubuntu.

**Comment by aekeus** [comment]
OSX works correctly.

**Comment by diracdeltas** [comment]
any console errors?

**Comment by bbondy** [comment]
I'm thinking this is related to the ledger-require branch and maybe you verified on master with 1.2.0 electron  and not 1.2.2.  I tried just now and it worked.  Please re-add to 0.10.4dev if it's still a problem on master with electron 1.2.2 or else close @aekeus

**Comment by aekeus** [comment]
Yes, related to the build issues in ledger-require branch. Closing.
