### ISSUE TITLE
windows are not listed in window menu

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2192]
**Expected behavior:**
List of open windows show appear in the Window menu

- Platform (Win7, 8, 10? OS X? Linux distro?):
Definitely Win and OSX, probably Linux as well
- Brave Version:
0.10.3

**Comment by bbondy** [comment]
Problem happened somewhere between these 2 versions / commits:

Working: 0.10.0
https://github.com/brave/browser-laptop/commit/24d60d92124f657c5ba57dc8e3f132a99f50a19b

Not working: 0.10.1
https://github.com/brave/browser-laptop/commit/b27cc9df8ffffcd1f561f33a1898315a21f24aba

Possibly from it being a 'role' of 'window' in Electron. Maybe something broke upstream.

**Comment by bbondy** [comment]
confirmed that going back to 0.10.0 with electron 1.2.2 reproduces, so I think that means it's an electron change.

**Comment by bbondy** [comment]
Found it was because of this BrowserWindow style:
> titleBarStyle: 'hidden-inset',

If you remove it everything works again.

**Comment by bbondy** [comment]
Problem is here:
https://github.com/electron/electron/pull/5557/files#diff-c2ca4f8ea2cbce1142ce6772061a99c6R456

I think the best way might be to just re-implement the functionality in front end code. We'd also need to re-generate or modify the menu whenever the windows change.

**Comment by BrendanEich** [comment]
I didn't read that Obj-C code, so dear lazy-github: why'd we regress? Were we fragile in some way that Electron should or does advise against?

**Comment by bridiver** [comment]
Seems like an electron bug
https://github.com/electron/electron/blob/13bfb099a2d23c302d43e26829a8fbf7a571dc2d/atom/browser/native_window_mac.mm
```
void NativeWindowMac::SetTitle(const std::string& title) {
  // We don't want the title to show in transparent or frameless window.
  if (transparent() || !has_frame())
    return;

  [window_ setTitle:base::SysUTF8ToNSString(title)];
}
```
No title, no window in the window list

**Comment by BrendanEich** [comment]
Yep -- can you link to the issue when you file it on Electron?

**Comment by bridiver** [comment]
https://github.com/electron/electron/pull/6089
