### ISSUE TITLE
Add correct shortcut for toggleFullScreenView on Mac OS X

### ISSUE THREAD

**Issue by raphaelokon** [brave/browser-laptop#2194]
**Describe the issue you encountered:**
Currently toggling the FullScreenView on Mac OS X is triggered via `⇧⌘F (Shift+Cmd+F)` or `⇧⌃F  (Shift+Ctrl+F)`. Does not correspondent with native OS behavior.
 
**Expected behavior:**
Shortcut that toggles the FullScreenView: `⌃⌘F (Ctrl+Cmd+F)`
- Platform (Win7, 8, 10? OS X? Linux distro?):
OS X 10.11.5
- Brave Version:
0.10.3

**Comment by luixxiul** [comment]
Won't this break the shortcut on Windows/Linux?

**Comment by raphaelokon** [comment]
This is a good question … I thought fullScreenView on Windows is toggle via F11.

**Comment by raphaelokon** [comment]
Adding a patch to the commit.

**Comment by luixxiul** [comment]
> fullScreenView on Windows is toggle via F11.

Yes it does too.

**Comment by raphaelokon** [comment]
I added a comment to my PR. I patched it but I had to rebase my changes. Should I force push to my fork and reopen the PR?
