### ISSUE TITLE
Page won't load: iTunes connect sales stats

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#2200]
https://reportingitc2.apple.com/
Is blank, this worked in the past, not sure what version last loaded this page.
I tried 'Shields Down' and the same result.

On OS X 10.11.5, Brave 10.3

**Comment by Liunkae** [comment]
This works for me.
Shields up (block ads, block third party cookies, HTTPSE, block fishing/malware)
Brave 0.12.1 on macOS 10.12

**Comment by Liunkae** [comment]
Still works fine for me with default shields, Brave 0.13.1 on macOS 10.12.x.

No recent reports. Closing.
