### ISSUE TITLE
Preferences, bookmarks manager, downloads manager...etc. not working

### ISSUE THREAD

**Issue by ishanspatel** [brave/browser-laptop#2204]
- Platform (Win7, 8, 10? OS X? Linux distro?): Checked this on **OS X** and **Ubuntu 16.04**
- Brave Version: Master (Latest)

Following things are not working/accessible/displayed:

- Preferences
- Bookmarks Manager
- Downloads Manager
- Find on page
- Print

This issue seems just after updating browser-laptop (master) to latest version.

**Comment by luixxiul** [comment]
Perhaps you need to do a fresh install.
````
rm -rf ~/.electron
cd browser-laptop
npm i
````
Wouldn't this work for you?

**Comment by diracdeltas** [comment]
you also probably have to do `rm -r node_modules/electron-prebuilt`

**Comment by ishanspatel** [comment]
It's started working with latest commit (branch:master).
