### ISSUE TITLE
When 'block 3rd party cookies' is on, block 3rd party referer on navigations?

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2214]
this might break some sites but seems worth trying. would have to clear both the HTTP header and document.referrer

**Comment by dogancelik** [comment]
Maybe optional "Block external referrers" option in *Preferences > Privacy*?

![block](https://cloud.githubusercontent.com/assets/486818/16138825/1537c50a-344a-11e6-9c03-be3890f83cca.png)

**Comment by bsclifton** [comment]
Love the idea of having it as an option! Only downside I see is that eventually there might be a ton of options and we'd want to consider a different way to display or manage them (would be interesting if the preferences could be taken out of the session storage and stored in a ".braverc" file)
