### ISSUE TITLE
washington post page steals browser shortcuts

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2219]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Some shortcuts don't work when the page is loaded
**Expected behavior:**
Shortcuts should work regardless of what is happening on the page
- Platform (Win7, 8, 10? OS X? Linux distro?):
  OS X
- Brave Version: 0.10.4dev
- Steps to reproduce:
  1. open https://www.washingtonpost.com/world/british-member-of-parliament-reported-to-have-been-shot/2016/06/16/a9b988de-33c4-11e6-ab9d-1da2b0f24f93_story.html
  2. press cmd-w or cmd-l
     3.

**Comment by bridiver** [comment]
this only happens when the block screen comes up asking for you email. Trying to figure out how to reliably replicate that

**Comment by neeklamy** [comment]
I’ve scrolled and scrolled on that page and another, I’ve allowed adverts and tracking, allowed all cookies, nothing.

I’ve tried viewing the site in Google Chrome, still nothing.

Is it something to do with the Washington Post paywall?

**Comment by bridiver** [comment]
It was a full page popover asking for my email address, but after I cleared it I couldn't find a way to get it back again. I really want to reproduce so I can see what is happening.

**Comment by neeklamy** [comment]
I’m wondering if it could be geographic specific, I’m in the UK, so maybe that’s why I’m not seeing it.

These are the only alerts I’ve managed to trigger, I know it isn’t the “You have just 2 free articles…”.

Just to be sure, it isn’t either of these is it?

<img title="Brave, Washington Post paywall alerts" src="https://cloud.githubusercontent.com/assets/155358/16169860/9ad49990-3535-11e6-95d8-bce55a47a0c3.jpg" width="400">
