### ISSUE TITLE
Improve ability of password manager to detect/fill/save credentials

### ISSUE THREAD

**Issue by mahosg** [brave/browser-laptop#2220]
**Did you search for similar issues before submitting this one?**
Y

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? OS X? Linux distro?):
  WIN7
- Brave Version:
  0.10.3.
- Steps to reproduce:
  1.INPORT A NEW PASS CODE.
  2.NO MENU
  3.DOES NOT SAVE PASSCODES
- Screenshot if needed:
  YES
- Any related issues:
  VERY FINE, LIGHT FAST BROWSER ! THAT;S IT !!!

**Comment by luixxiul** [comment]
I'm not sure what your point is.

**Comment by mahosg** [comment]
Dear Sir/Madam,

The issue is that pass manager, does not hadle passwords from router/s, nor
all sites.

Please feel free to question more




2016-06-18 3:15 GMT+03:00 Suguru Hirahara <notifications@github.com>:

**Comment by luixxiul** [comment]
So I think you are suggesting to implement:

- function to import/export passwords
- menu with which you can control the password manager

Am I missing something?

**Comment by bradleyrichter** [comment]
I read this as:

The brave built-in password manager is not saving the password on your router admin page?

**Comment by luixxiul** [comment]
I'm guessing the opener suggested to add a remember password feature for basic http auth.
