### ISSUE TITLE
Make silent installation package on Windows

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2222]
From support: on a medium to large scale please let users install Brave by the switches.

**Comment by tslben** [comment]
Further to this, an installer switch to disable checking for update would also be very useful.  Sys admin needs to control software installation.  Also having hundreds (or thousands) of computers on the network all downloading the same update is just a horrible idea.

We deploy with WPKG running under the system account.  No internet access is available during installation, so a fully standalone installer with no dial-home shenanigans is essential.
 
So, something like brave_installer.exe /SILENT /DISABLEUPDATES 
or,  msiexec /qn /i brave_installer.msi ALLUSERS=1 /DISABLEUPDATES

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/655
