### ISSUE TITLE
Base href not always honored

### ISSUE THREAD

**Issue by stianjensen** [brave/browser-laptop#2223]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Trying to download an image from a page, where it is defined as a relative url:
```
<img src="favicon.png">
```
and in the header of the page there is a base tag declaring where relative paths should be resolved from.

The image is loaded and displayed correctly on the page, but using context menu commands such as 'Save image...', 'Open image in new tab', and 'Copy image address' do not account for the value of the base tag's href attribute.

**Expected behavior:**

When choosing 'Save image...' on an image, the image url should be resolved according to the value of the base tag, if one is present.

- Platform (Win7, 8, 10? OS X? Linux distro?): OS X

- Brave Version: 0.10.3

- Steps to reproduce:
    1. Go to http://stianj.com/uploads/issue.html
    2. See that an image is loaded _(from a relative path, which you can see in the web inspector is resolved relative to my root domain, and not the subpath /uploads/)_
    3. Right-click and select 'Copy image address'
    4. The copied address includes '/uploads/' as part of the url, while the expected result is 'https://stianj.com/favicon.png'

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
What version are you on? i think this was fixed by f6f1bc8b5aed3858fdf618136d3821342af0a42e

**Comment by diracdeltas** [comment]
Thanks for the test page. I can confirm it works on master, probably thanks to f6f1bc8b5aed3858fdf618136d3821342af0a42e. not sure why that isn't in 0.10.3 though.
