### ISSUE TITLE
extensions are missing browser/page action icons

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2224]
Some people have difficulty figuring out how to use the password manager extensions because we don't display the browser action icons

cc @bradleyrichter

**Comment by bradleyrichter** [comment]
upcoming windows location:

![image](https://cloud.githubusercontent.com/assets/13509546/17567276/8769b3a8-5ef3-11e6-8bab-26312caaae6c.png)





upcoming mac location:

![image](https://cloud.githubusercontent.com/assets/13509546/17567386/f1802038-5ef3-11e6-8112-660f1f93a0ab.png)

**Comment by luixxiul** [comment]
Some users are saying it is hard to move the window due to the narrowness of the top bar (difficult to find where to click and drag)

**Comment by bradleyrichter** [comment]
@luixxiul We have a plan to do some smart mouse drag detection for desktop. But we will start by securing a larger empty zone between the URL box and the extension buttons. (it was removed in a PR a while back that needs to be reverted.)

**Comment by bridiver** [comment]
@bradleyrichter do you have an image or a color for the `|` that separates the the brave menu from the extensions?

**Comment by bradleyrichter** [comment]
@bridiver Try "@gray" from the variables.
