### ISSUE TITLE
unsigned updater won't run in dev 

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2225]
This makes it very hard to test and verify. There are several things we could do:
1. Locally generate and trust a fake CA that can be used for signing (would this actually work?)
2. Stub the updater to fake a run
The first option is preferable in my opinion because we can test the entire process. The second option would still be good for testing if the first option isn't possible. 

@aekeus - I know you've been down this road already, what did you try? Doesn't sound like a self-signed cert works, but did you try generating a fake CA cert and add it to the trusted system certs?

**Comment by aekeus** [comment]
If I remember correctly the self-signed cert did not work, but did not try adding to trusted certs. It is a pain to test the updater locally. I ended up having to use the prod cert with a local server over https (December) for testing.
