### ISSUE TITLE
Problem in Changing Homepage URL

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-laptop#2226]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Trying to Change Homepage URL is not working properly well in 0.10.3

**Expected behavior:**
Actually we should be able to edit the Homepage URL
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Ubuntu 14.04 x86_64
- Brave Version:
  0.10.3
- Steps to reproduce:
  1. Choose Preferences from Menu & Select General Tab
  2. In **Brave Starts with** choose _Show my home page_
  3. Try to give  new URL for **My Homepage is**, edit it by using backspace
- Screenshot if needed:
  Video in Google Drive 
  https://drive.google.com/file/d/0BynHVcltkfkwSkszck1RcUFnaDg/view?usp=sharing
- Any related issues:
  Not found

**Comment by cezaraugusto** [comment]
Thanks @iamVP7 for opening the issue and sending the video.

I found it unreproducible using OS X. Setting as `bug` until someone could test on a Linux distro.

**Comment by alexwykoff** [comment]
Pretty sure this has been fixed
