### ISSUE TITLE
Block autoplay videos

### ISSUE THREAD

**Issue by mdoniec** [brave/browser-laptop#2227]
Would be nice if You could add an option to block videos from autoplaying as it is one of the most annoying things currently.

**Comment by luixxiul** [comment]
The feature has been almost addressed with #1794, still it is worth considering for pinned tabs.

**Comment by luixxiul** [comment]
+1 from support

**Comment by luixxiul** [comment]
+1 from support

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5414

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5818

To be clear, the user would like to be able to select when the video plays, not hide the content entirely.

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6071

**Comment by cezaraugusto** [comment]
+1 from support: https://linkbubble.zendesk.com/agent/tickets/5598

**Comment by Liunkae** [comment]
#4045 would solve the problem for HTML5 videos.

**Comment by Liunkae** [comment]
+1 from #8432.
