### ISSUE TITLE
Memory usage in macOS 10.12

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2228]
From support:
> I've just noticed that Brave is now using 2 GB of memory in macOS 10.12. It was 500 MB in OS X 10.11.

Would anyone confirm this?

**Comment by ununseptium** [comment]
I just tested it. In idle mode (just started the browser) it (Brave) occupies 174 MB of RAM and each Brave Helpers does around 740 MB just like the Chrome Helper processes do on my site. 

---
Cannot confirm.

**Comment by fibric** [comment]
I can't confirm it too.
![screen shot 2016-06-21 at 06 50 00](https://cloud.githubusercontent.com/assets/623932/16218311/780ce70c-377c-11e6-8fb8-91fea145a47c.png)
Running on Mac Pro (late 2013) 10.12 Beta (16A201w)

I can only tell that some apps on app-startup cause memory panic for a while until everything normalises. Google Chrome is such an example, but this is normal for Apple's Beta OS's to gather additional metrics. Brave is very peaceful and doesn't cause memory panics - haven't tried yet with many tabs on startup yet.

**Comment by luixxiul** [comment]
Thanks guys, I think it happens on occasion (cf: #415). Please let us know if you have steps to reproduce.

**Comment by luixxiul** [comment]
I found some feedbacks on the support forum.

**Comment by bridiver** [comment]
There have been a lot of updates since this ticket was opened and I'm going to close it with https://github.com/brave/browser-laptop/issues/3314 
Please open a new issue if you see problems after the next release
