### ISSUE TITLE
Crash After Display Notification

### ISSUE THREAD

**Issue by jemspatel** [brave/browser-laptop#2230]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
When Notification permission given and notification display then immediately crash 
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux
- Brave Version:
0.10.4
- Steps to reproduce:
    1. start browser 
    2. open notification test site
    3. test notification and give permission

- Screenshot if needed:

![screenshot from 2016-06-18 10-49-21](https://cloud.githubusercontent.com/assets/19972165/16169218/a2abe49e-3543-11e6-8532-05897e809bc1.png)
![screenshot from 2016-06-18 10-50-09](https://cloud.githubusercontent.com/assets/19972165/16169222/be3a9ffc-3543-11e6-9a87-d7f84e44b00c.png)
- Any related issues: #2055 #1726

**Comment by bbondy** [comment]
I think this will be fixed once I spin new electron builds. I'm working on them now.

**Comment by bbondy** [comment]
cc @bridiver in case that's not the case.

**Comment by jems55** [comment]
when we have passed allow permission to permission callback then it's crash but in deny permission it's working fine

**Comment by luixxiul** [comment]
@jemspatel does it work well now?

**Comment by jemspatel** [comment]
@luixxiul  yes now its working fine in win, linux

**Comment by luixxiul** [comment]
@jemspatel nice to hear that ;-)
