### ISSUE TITLE
Title should be default file name when saving page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2231]
From support:

> When saving webpages, Brave prefers the .html file name and sometimes defaults to just the domain name. For instance, with this page: http://www.breitbart.com/jerusalem/2016/06/17/israeli-judge-approves-400-million-class-action-facebook-violating-privacy/
> 
> Saving it defaults to "www.breitbart.com," but this becomes a nuisance if you have more than one page from this site saved, as you have to manually adjust the name.

+1 from me too

**Comment by luixxiul** [comment]
I think this will be a security hole if someone puts a malicious file on ``maliciousfilehere.com`` because the page is saved as a ms-dos program. It should be at least like ``maliciousfilehere.com.html``.

**Comment by gulkily** [comment]
I have done some thinking about this issue, and it seems like there should be a little more logic to it. I suggest the following:

Is the file served with content-type: text/html
AND
Does the URL (before question mark) end with ".html"?
Save it as /everything-after-the-last-slash.html

Does the page have a title?
Save it as Sanitized Title.html

No title?
Take everything after the domain, sanitize, and add .html

Nothing after the domain?
Save it as domain.html
