### ISSUE TITLE
[Transifex] Request for polish l10n

### ISSUE THREAD

**Issue by maks1823** [brave/browser-laptop#2233]
Hi,

Week ago I requested adding a polish language to Brave language list. I would like to translate from English to Polish, but I am still waiting for response....

**Comment by bbondy** [comment]
@aekeus

**Comment by aekeus** [comment]
Hi maks1823. Please sign-up for an account at transfex.com. The project url is at https://www.transifex.com/brave/brave-laptop. I will confirm you as a language contributor as soon as I see the request.

**Comment by luixxiul** [comment]
I think he has requested it already.

**Comment by maks1823** [comment]
@luixxiul you are right, I am still waiting for adding Polish to list !

**Comment by aekeus** [comment]
Hi, I approved the Polish language last week I believe.

**Comment by aekeus** [comment]
Actually, I see there was a probable with the approval. Just did it again. Please let me know if you still don't have access.

**Comment by maks1823** [comment]
Hi,
Sorry for delay. I just joined thee team, awaiting for accept.
PS. Do I have to translate Polish or Polish(Poland) ?

**Comment by luixxiul** [comment]
@maks1823 Either is ok. Please select one and work on it, thanks.
