### ISSUE TITLE
Add ‘stop’ menu bar item

### ISSUE THREAD

**Issue by neeklamy** [brave/browser-laptop#2234]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
There should be a menu item (and keyboard shortcut) to stop page loading, as can be found in other web browsers (Google Chrome and Safari, Firefox doesn’t have any page navigational menu bar items).

**Comment by luixxiul** [comment]
The keyboard shortcut (ctrl + period) works on neither Firefox nor Chrome. Only for me?

**Comment by bbondy** [comment]
Command+. works on OS X.  Maybe it's an OS X only shortcut.

**Comment by neeklamy** [comment]
You’re right, @luixxiul, on [Firefox it’s <kbd>escape</kbd> to stop page loading][firefox].

I’ve changed the keyboard shortcut for Linux and Windows, #2258.

[firefox]: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
