### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by derekoppen** [brave/browser-laptop#2236]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

when i exit brave (which i have to do occasionally cos it may have a memory leak) it forgets my bookmarks. and importing bookmarks doesn't work

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
macos

- Brave Version:latest

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by cezaraugusto** [comment]
Hi @derekoppen, does it happens all the time you quit Brave?

**Comment by derekoppen** [comment]
yes

**Comment by muchavie** [comment]
I'm seeing this same behavior on Ubuntu 14.04 Linux.   I've been trying to use Brave as my default browser for a couple months and I had collected a set of 100 or so links.   Gone :(   

This bug makes Brave hard to use.

Good Luck! and Best Regards,
Peter

Also, you might pester fastly.net about the problem below ...

    2016-05-30T17:14:20.759Z - 
    https://brave-laptop-updates.global.ssl.fastly.net/1/releases/dev/0.10.0/undefined?    
   daily=false&weekly=false&monthly=false&first=false
    2016-05-30T17:14:20.945Z - Error: connect ECONNREFUSED 199.27.79.249:443

**Comment by bsclifton** [comment]
ugh, this is horrible (losing all those bookmarks) :frowning:  Long term, the bookmarks (which are currently stored in session) will be stored in Chromium.  Would be awesome to periodically back this up or split the bookmarks out

**Comment by bsclifton** [comment]
Hi @derekoppen- are you still using Brave? If so, does this happen each time you exit? Let us know either way.  Thanks :smile:

**Comment by bsclifton** [comment]
Closing due to lack of information. Please re-open and leave a comment with details if you encounter the issue again :smile:
