### ISSUE TITLE
When play video on twitch

### ISSUE THREAD

**Issue by gravitycrusher7** [brave/browser-laptop#2237]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When play video from twitch.tv sometimes bug. Audio come first and video got delay, not smooth like youtube. I have no connection problem too.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
win 7
- Brave Version:
newest build

**Comment by jeifour** [comment]
Sounds like #2119

**Comment by luixxiul** [comment]
Let's see if this will be fixed in v0.10.4

**Comment by diracdeltas** [comment]
Fixed?

**Comment by bbondy** [comment]
I think this was due to the double audio stream when we had the html5 hack and they added html5.  If there are further requests we'll re-open.
