### ISSUE TITLE
Search Settings Panel: Search Suggestions (Part 2)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2239]
Note from @bbondy:

>  I think this still needs UX revisions, in particular listing the search terms in the location bar is adding a lot of complexity, how do you select items? What if suggestions are long from Google or another engine? Also the images of the engines I'd prefer to put appended to the url suggestions box.

See https://github.com/brave/browser-laptop/issues/2694 for the first part of this work done.
# Original posted task:

Functionality:
Search suggestions appear as you type a keyword into the search bar, and update dynamically as more characters are entered which can change the resulting suggestions

String:
"Offer search suggestions"

Spec image for pref panel: (item shown in blue)
![image](https://cloud.githubusercontent.com/assets/13509546/16175684/625e35be-35ab-11e6-9cc5-d99f29df0a8a.png)

spec image for search window:

![image](https://cloud.githubusercontent.com/assets/13509546/16175779/82d30cb8-35ae-11e6-891d-baed3a13e0db.png)

**Comment by bbondy** [comment]
I put this task on hold, added my concerns as a prefix to the task and split its functionality into what is do-able for 1.0.    The split task features are being done here: https://github.com/brave/browser-laptop/issues/2694
