### ISSUE TITLE
Flux vs Redux

### ISSUE THREAD

**Issue by anvk** [brave/browser-laptop#224]
First of all this is a great idea for the project and I will try to contribute to it as well whenever I have time.

But I have a technological question - I saw that you guys use Flux as the main application architecture for communications between React components.
Why not to use Redux? It is more inline with pure JavaScript functions and (so far as I heard of) takes immutable objects into its core principles.

Just wondering.

**Comment by bbondy** [comment]
Wouldn't be against it, but yes, immutable top level data is one of our core principles in design for the code.  Code feels nice and organized and easy to maintain right now as is though.   I'll close this issue since it's just a design question but feel free to ask more.

**Comment by anvk** [comment]
Thanks for your reply. Good we closed this issue since it is not really a problem. Please do not get me wrong, I'm not hear to pop out of the blue and say "Well guys let's switch this whole project to Redux now, won't it be cool!" 

I'm just curious what was the decision not to go the Redux way while lots of people might say it is the natural evolving of Flux architecture. Or there are plans in the future to do such an update OR there are no such plans because of X and Y and Z...

**Comment by bbondy** [comment]
We're open to it, but it just came down to what was familiar already to the team from existing projects. It's possible that would have been a better solution but we're happy where we are now regardless.  Sorry I don't have a better answer for this!

**Comment by anvk** [comment]
No it is a pretty good answer and I understand. I was just curious if you guys found some reasoning of not going the Redux way and wanted to hear that.
http://stackoverflow.com/questions/33619775/redux-multiple-stores-why-not/33633850#33633850

**Comment by bbondy** [comment]
We do have 2 stores by the way, we started with one only inside each render process window.
The main reason for this is multiple processes.

Ideally we'd have a single store in the parent process but we don't have an efficient way to update immutable data across processes.   We'd love to see some kind of ImmutableJS that works efficiently from shared memory though.
