### ISSUE TITLE
https://fonts.google.com/ blocked in Brave

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2242]
It shows something went wrong, rendered in content.

**Comment by Liunkae** [comment]
This works for me.
Shields up (block ads, block third party cookies, HTTPSE, block fishing/malware)
Brave 0.12.1 on macOS 10.12

**Comment by getsetbro** [comment]
I got this:

<img width="520" alt="screen shot 2016-11-17 at 9 21 36 am" src="https://cloud.githubusercontent.com/assets/442793/20395308/0e6419f0-aca8-11e6-8f85-1f117783ef15.png">

**Comment by Liunkae** [comment]
Hmm, still works fine for me. Brave 0.12.9 with default shields on macOS 10.12.x.
![image](https://cloud.githubusercontent.com/assets/19424103/20421296/86d48fac-ad28-11e6-9337-feeda3a6c29f.png)

**Comment by luixxiul** [comment]
@Liunkae I am completely sure enabling fingerprinting protection will cause the issue.

**Comment by Liunkae** [comment]
@luixxiul You're right. I get the same error shown above when I enable fingerprinting protection.

**Comment by bsclifton** [comment]
Shared link in https://github.com/brave/browser-laptop/issues/2965

**Comment by bbondy** [comment]
cc @diracdeltas to advise.

**Comment by bsclifton** [comment]
Issue is fingerprinting; captured in #2965
