### ISSUE TITLE
Twitter-based login fails

### ISSUE THREAD

**Issue by sirjorj** [brave/browser-laptop#2247]
**Did you search for similar issues before submitting this one?**
no

**Describe the issue you encountered:**
When trying to log into "(Yet Another) X-Wing Miniatures Squad Builder" using twitter, it doesn't log in

**Expected behavior:**
After logging in, the "log in" button should say "log out" but it doesnt because it doesn't log you in.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X El Capitan and Windows 10
- Brave Version:
  .10 on OS X, .9 or .10 on Windows 10
- Steps to reproduce:
  1. go there: http://geordanr.github.io/xwing/
  2. click "Log In" and select twitter.
  3. select "authorize app"
  4. when it returns you to the original web app it should have you logged in but it doesn't.
- Screenshot if needed:
- Any related issues:
  I have seen other issues related to twitter authentication, so it may be related to those.

**Comment by luixxiul** [comment]
Would you disable Bravery shield and try again?

**Comment by jonathansampson** [comment]
I believe this was related to the Twitter authentication issues we fixed late last year. Closing, as users are able to login to Twitter today without any issue.
