### ISSUE TITLE
Brave crashes when Telegram Web and Whatsapp Web ask for notifications at the same time

### ISSUE THREAD

**Issue by yaso** [brave/browser-laptop#2248]
**Did you search for similar issues before submitting this one?**
* yes. Did not find any. 

**Describe the issue you encountered:**
brave closes when Telegram & whatsapp are open and both ask "allow notifications?"

**Expected behavior:**

Check the box for allow notifications for both apps (telegram & whatsapp)
both notify me when someone messages me
Brave is still open

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS
Debian Jessy

- Brave Version:
Brave: 0.10.3

- Steps to reproduce:
    1. Open 5 tabs, 2 of them are Telegram Web and Whatsapp Web
    2. Wait for them to ask for notifications
    3. Allow both, remembering for the session

- Screenshot if needed: 

- Any related issues: #2230  #2055 #1726 #1556

**Comment by luixxiul** [comment]
I think the issue has been fixed. cc: @bridiver in case that's not the case.

**Comment by bridiver** [comment]
I can't replicate, but I did notice that multiple notifications replace instead of appending to the list

**Comment by diracdeltas** [comment]
i think this is the notification crash issue that has been fixed

**Comment by luixxiul** [comment]
Closing this. Please let us know if this issue still exists.
