### ISSUE TITLE
Add autocomplete entries for about pages

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2252]
Add another autocomplete provider for about pages.

**Comment by bbondy** [comment]
Implementation details:
- You can get a list of the about URLs by requiring appUrlUtils via aboutUrls, all should be included except for if they are isIntermediateAboutPage. You can use Object.keys() to get an array from the aboutUrls and then use `filter` to filter out the intermediate about pages. 
- The code to add the suggestions is in `js/components/urlBarSuggestions.js` particularly in `getNewSuggestionList` and then in `render`.  You can follow along with topSites for similar code.  It should appear just after history entries in the suggestion order.

**Comment by darkdh** [comment]
Hi @bbondy,
I would like to take this issue.
