### ISSUE TITLE
Don't show an option to pin about:blank and about:newtab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2253]
Do not show an option to pin for about:blank, about:newtab and also not if `isIntermediateAboutPage` is true from `appUrlUtil`

**Comment by rifazn** [comment]
Could you tell me which file this bug relates to?
I'd just like to play around with it a bit. See if I can put a good change or two.

**Comment by darkdh** [comment]
Sorry, I didn't see @rifazn comment and I forgot to take it first.

**Comment by bbondy** [comment]
No worries and thanks for the PR @darkdh!  

@rifazn would you mind if we took @darkdh's pull request and you worked on something else?  Sorry we were slow to respond on this one on the weekend @rifazn.

**Comment by rifazn** [comment]
Hey it's no problem. ;)
