### ISSUE TITLE
Localhost name should be white listed for google searches

### ISSUE THREAD

**Issue by marceloandrader** [brave/browser-laptop#2257]
**Describe the issue you encountered:**
When I write localhost as an url address, a google search is performed.

**Expected behavior:**
Take me to the http://localhost site

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, not sure about the others.

- Brave Version:
Brave: 0.10.0
Electron: 0.37.8
libchromiumcontent: 50.0.2661.102
V8: 5.0.71.48
Node.js: 5.10.0
Update channel: dev

- Steps to reproduce:
    1. Open brave
    2. Type 'localhost' without quotes on the url bar
    3. Google search for localhost is performed

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
This was done recently, it'll be in 0.10.4 release which is very soon.
