### ISSUE TITLE
Link to Flash installer in preferences panel should redirect to correct location based on operating system

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2269]

**Comment by diracdeltas** [comment]
supposedly https://get.adobe.com/flashplayer will redirect to the correct installers for win/osx but linux users should just install the pepperflashplugin-nonfree package for now. adobe says they are working on having the linux package hosted on their site.

**Comment by aekeus** [comment]
Ok, that makes sense. I was mostly thinking about the Linux installer.
