### ISSUE TITLE
Multiple HTML web notifications overlap instead of appending to the list

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2270]
**Describe the issue you encountered:**
When a notification comes in while another one is still visible, the old notification is replaced by the new one
**Expected behavior:**
The new notifications be displayed below the older one
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
  0.10.4dev
- Steps to reproduce:
  1. go to http://www.bennish.net/web-notifications.html
  2. click authorize and remember
  3. click the show button several times

related #2248

**Comment by diracdeltas** [comment]
is this still happening? the expected behavior is that new notifications be added if they are different from the older ones. (if they have the same message string, the new one should replace the old one)

**Comment by luixxiul** [comment]
Closing as fixed.
