### ISSUE TITLE
Can't navigate away from some sites after input has been entered

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2275]
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OSX - probably all
- Brave Version:
  0.10.4
- Steps to reproduce:
  1. Go to google.com
  2. Navigate to Facebook.com and login
  3. Enter some text in the status message box
  4. Click back

The renderer refuses to navigate, but no warning is presented (as in chrome)

**Comment by bbondy** [comment]
Can also be reproduced just by clicking on a bookmark in the bookmark toolbar after going to facebook and typing text in a comment.

**Comment by bbondy** [comment]
Seems related to when there is a prompt for the beforeunload event.
