### ISSUE TITLE
Window menu on Windows should have preferences

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2277]
Preferences doesn't appear anywhere in the top level menu otherwise.
Use process.platform for the code in app/menu.js

**Comment by bsclifton** [comment]
This is already showing in the Edit menu... should it also be showing the Window menu?
![2016-06-27 1](https://cloud.githubusercontent.com/assets/4733304/16405813/4539f8d6-3cbf-11e6-9ce4-0eb7237fdbb2.png)

**Comment by cezaraugusto** [comment]
Good catch @bsclifton. I was [almost sending a PR](https://github.com/cezaraugusto/browser-laptop/blob/windows-preference-menu/app/menu.js) for this. 

Should we keep it under **Edit** or **Window** menu is better?

**Comment by bbondy** [comment]
Oh didn't notice that. Not sure which is better. @bradleyrichter ?

**Comment by bradleyrichter** [comment]
Actually, on Windows and Linux, "Preferences..." should really be "Settings..." to active Win user's muscle memory. 

Old-style windows standard for placement was in Edit. 

Today it has moved to the hamburger in most if not all Windows apps. (like onenote, money, etc.)


@bsclifton So, let's rename to "Settings...". Leave it in the burger. Add it to "Edit".

**Comment by cezaraugusto** [comment]
@bradleyrichter so it should be renamed on both Edit and burger menu?

**Comment by cezaraugusto** [comment]
Nevermind, figured out a good way to do it.

**Comment by bbondy** [comment]
Only add in english localization file btw, and yes in both places it should be called Settings on Windows.
@bradleyrichter btw Chrome calls it Settings everywhere. Firefox uses Preferences... on macOS and Options on windows. Maybe we should just use Settings everywhere to be consistent with what has the most market share?

**Comment by bbondy** [comment]
it might make it easier for documentation we write in the future to be consistent.

**Comment by bradleyrichter** [comment]
Chrome on mac actually mixes both but that doesn't surprise me.

![image](https://cloud.githubusercontent.com/assets/13509546/16461023/4e6572a2-3ddf-11e6-8ec8-1349fe849eb6.png)



I know it ads more pain but it doesn't seem right to me to break history on Mac and put "Settings..." in the App menu so let's please keep them OS specific so users can more quickly identify them when looking.

![image](https://cloud.githubusercontent.com/assets/13509546/16460961/faa646fa-3dde-11e6-9673-e02a72fe63e3.png)

**Comment by bbondy** [comment]
wow crazy!
