### ISSUE TITLE
A loading tab interferes with using tab page navigation

### ISSUE THREAD

**Issue by neeklamy** [brave/browser-laptop#2283]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Loading tabs interfere with using the **tab page** navigation element.

**Expected behavior:**
Whilst a tab is loading, we’re able to use the **tab page** navigation.

**Platform:**
OS X

**Brave Version:**
0.10.2, 0.10.3, and probably earlier.

**Steps to reproduce:**
1. Open several tabs in a window, so that the a new tab page is created (so at least 11 tabs, 10 for the first tab page, and one more tab).
2. In the 11th tab, go to a page that won’t load (it’s easier to see what’s happening then), for example: https://web.archive.org/web/20160329223756/http://www.bleem.com/
3. Click on the previous tab page.
4. Almost immediately the loading tab is brought forward.

**Notes:**
- This happens wherever the loading tab is in relation to other tabs (I tried it on the first, second, third and fourth tab pages).
- It is possible to switch to a different tab with the keyboard shortcuts and just clicking.

![Brave browser tab page and loading bug](https://cloud.githubusercontent.com/assets/155358/16305345/4de95c4a-3951-11e6-922a-a1b58567fae6.gif)

**Comment by cezaraugusto** [comment]
this was addressed in #10008 but @bbondy found a different STR which is also related to loading tabs so I'll use this as a reference:

* get 5 tab pages
* close browser
* open browser
* move to tab page 4
* hover over an unloaded tab
* as it reloads it will jump back to tab page 5.

**Comment by cezaraugusto** [comment]
This is for tracking at this moment.  I can't see the issue in 0.18.x and upwards. Please don't push back until confirmed.

**Comment by cezaraugusto** [comment]
tested again steps in https://github.com/brave/browser-laptop/issues/2283#issuecomment-317041022 on 0.18.23 and no longer an issue, closing.
