### ISSUE TITLE
Brave on Ubuntu 16.04 not saving any settings

### ISSUE THREAD

**Issue by terrannz** [brave/browser-laptop#2287]
Did you search for similar issues before submitting this one?:  Yes but found one instance on hold and the other instance linked to the instance the was on hold.

Describe the issue you encountered:  On launch the browser is blank like the first launch after install a few days ago.  This happens each time I launch the programme.
One thing is retained and that is that a logged in session of a webpage that hasn't expired will remain logged in.

Expected behavior:  Bookmarks and settings set in previous session be available on launch.
- Platform (Win7, 8, 10? macOS? Linux distro?):  Ubuntu 16.04  64bit
- Brave Version:
  Brave: 0.10.3
  Electron: 1.2.0
  libchromiumcontent: 51.0.2704.84
  V8: 5.1.281.59
  Node.js: 6.1.0
  Update Channel: dev
- Steps to reproduce:  
-  Import/set bookmarks and set preferences.  
-  Close browser and open again.
- Any related issues:  There was a broken package error on install saying that git was not installed.  I fixed the broken packages using 'Fix Broken Packages' in Synaptic Package Manager.

**Comment by terrannz** [comment]
It seems to be saving settings

**Comment by cezaraugusto** [comment]
Hi @terrannz, thanks for pointing your issue.

Did you took any additional steps after posting this issue, like upgrading? Everything working good now?

**Comment by Liunkae** [comment]
No recent reports. Closing.
