### ISSUE TITLE
Add the ability to delete individual autocomplete entries

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2288]
On OSX MBP:
Fn+Shift+Delete

Which on a normal keyboard is just Shift+Delete

**Comment by luixxiul** [comment]
It is a bit hard to push <kbd><kbd>Fn</kbd>+<kbd>Shift</kbd>+<kbd>Delete</kbd></kbd> with one hand. Is it only for me or not?

**Comment by bbondy** [comment]
I think this shortcut matches chrome/firefox. We should match those browsers for shortcut keys.

**Comment by luixxiul** [comment]
OK I see.
