### ISSUE TITLE
Per-site fingerprinting setting is not working at all

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#2300]
**Did you search for similar issues before submitting this one?**
Yes. This is a regression of #2082.

**Describe the issue you encountered:**
If you have fingerprinting protection enabled globally, you cannot disable it for a certain site. The fingerprinting protection still works regardless of per-site settings.

**Expected behavior:**
You should be able to enable/disable fingerprinting protection for each site individually from the Bravery Panel.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.10.4

- Steps to reproduce:
    1. Make sure fingerprinting protection is enabled globally at about:preferences.
    2. Go to a site with fingerprinting (e.g. [https://www.html5test.com/](https://www.html5test.com/)).
    3. Open the Bravery Panel and turn off fingerprinting protection.

- Screenshot if needed:
https://cloud.githubusercontent.com/assets/19424103/15800884/614ead68-2a4b-11e6-9f6c-80ef8e400551.png (from #2082)

- Any related issues:
#2082.

**Comment by diracdeltas** [comment]
great catch, i can verify. cc @bridiver
