### ISSUE TITLE
Using 1password in a new session tab somehow breaks 1password in normal tabs

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2303]
more research needed but my browser (with recent update) on Mac OS 10.11.5 is stuck in this state.

In order to use 1password, I need to open a new session tab. (otherwise the form fields do not fill.)

**Comment by bradleyrichter** [comment]
@bridiver

**Comment by bridiver** [comment]
do you have steps to replicate? I opened a regular tab, two session tabs and a private tab and 1password worked in all of them

**Comment by bradleyrichter** [comment]
not easily. Leave open for a bit and see if we get any more reports?
