### ISSUE TITLE
remove passwords from cleared items when using Clear all Cookies and Site Data feature

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2305]
As a user, I do not need/want my passwords cleared with cookies and history/cache as I prefer to clear them with the password manager UI.

menu item:
![image](https://cloud.githubusercontent.com/assets/13509546/16353982/536ddaf8-3a3a-11e6-99ad-6a18f4eadce2.png)

password manager:
![image](https://cloud.githubusercontent.com/assets/13509546/16354023/2c6165c8-3a3b-11e6-9a13-6d75da51f8b4.png)

@diracdeltas

**Comment by diracdeltas** [comment]
I can't repro this on OS X. Clicked the menu item but all my passwords are still there.

**Comment by bradleyrichter** [comment]
let's close it and work towards it's replacement anyway.
