### ISSUE TITLE
1password auto-fill broken by newest update

### ISSUE THREAD

**Issue by Shared-Ideas** [brave/browser-laptop#2308]
### Brief summary
The combination of 1Password and the Brave browser worked perfectly for a long time, now after the most recent update I am no longer able to use the 1Password auto-fill feature. Even after a clean reinstall of Brave I still have the issue. 

### 1Password before update
Previously when signing into [GitHub] (https://github.com/login) you could right click on the spot to enter your email, and under the back/print/inspect element/ etc. there was the option for 1Password. You could click it and then enter your 1Password master password and then another list would show up with all of the 1Password options. **(part 2)** After clicking the GitHub option (or the corresponding option for each site) the text for your username and password would be instantly entered. Then you would just have to click sign in and you would be good to go.

### Issue
After the most recent update* signing into any website 1Password acts normally as stated above, until reaching **part 2**. 1Password can correctly recognize what site you want to sign into, but after clicking the option that usually pastes in your username and password. Nothing. The 1Password options will disappear like normal but nothing will have been pasted. The 1Password extension acts like this on all websites...

### Version
I am on Windows 10 64-bit
* I believe version 0.10.dev [I am on the most recent install version, if there is a way to know for sure I would love to know :)]

### Steps to reproduce:
1. Have the 1Password manager selected in the Brave preferences
2. Go to the sign in page for any website
3. Right click on sign-in submission boxes
4. Select 1Password and enter master password if requested
5. Click the name of the site in the 1password options (As far as I know always the first option)
6. Username and password are not pasted (This is the Error)

## Thank you for the help!!!

**Comment by brettholz** [comment]
I have this exact same issue. 1Password and Brave worked flawlessly together until I installed the latest update to Brave.

**Comment by bradleyrichter** [comment]
@Shared-Ideas @brettholz 

Can you both test something for me? Try creating a new-session tab and then try using 1password again. (I have this problem as well, and this is the workaround)

This might help us fix this bug. Thanks!

cc @bridiver

**Comment by bradleyrichter** [comment]
Cancel the above ^. Already fixed by @bridiver.


Thanks...

**Comment by luixxiul** [comment]
Can this be closed?
