### ISSUE TITLE
load page should not be like a reload

### ISSUE THREAD

**Issue by ballo** [brave/browser-laptop#2309]
**Did you search for similar issues before submitting this one?**
yeah
**Describe the issue you encountered:**
Clicking the url bar and hitting enter shouldn't behave the same as a reload
**Expected behavior:**
It should load the page fresh and should be at the top of the page. Instead it behaves like a reload and scrolls down to where you were last. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Mac
- Brave Version:
  0.10.4

**Comment by i-cant-git** [comment]
Pressing Enter in Location bar resets position in every browser.
Ctrl+R / F5 reloads page but retains scroll position in every browser.

**Comment by ballo** [comment]
I don't think you caught the part where I said this was on the Mac platform.

It doesn't behave correctly.

**Comment by i-cant-git** [comment]
Sorry my bad

**Comment by bradleyrichter** [comment]
This should be fixed as we finish refining the new search bar panel. ( @bbondy )

**Comment by bbondy** [comment]
we do actually call into reload so @ballo is completely right. It is not related to search bar panel though so needs to be fixed separately.
