### ISSUE TITLE
add NoScript-like feature

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#231]
some power users have asked for the ability to block js from running except on whitelisted sites. Chrome has a feature to whitelist/blacklist scripts by hostname pattern, which may be sufficient.

**Comment by bbondy** [comment]
Do you have that list and know information on how it is maintained?  Seems like a super easy win for us to have on all platforms.

**Comment by diracdeltas** [comment]
There's no central list. the two approaches i've seen are:

1. chrome > advanced > content settings > disallow JS except on sites matching hostname patterns that you enter in
2. noscript - block js on all sites, can select "allow scripts on this site" whenever you encounter a site

**Comment by bbondy** [comment]
I guess we could support both modes. #1 seems much more useful to me though.

**Comment by diracdeltas** [comment]
agree

**Comment by Arandhras** [comment]
As a long-time user of NoScript on Firefox, I would also like something like that implemented in Brave. Both approaches mentioned by @diracdeltas to whitelist websites are good, and I can't think of a reason to implement only one instead of both.
