### ISSUE TITLE
Update notification points to wrong URL

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2313]
**Describe the issue you encountered:**

0.10.4 changelog URL in Brave info-bar update notification is password-protected 

Should point to:
https://github.com/brave/browser-laptop/releases/tag/v0.10.4dev

Does point to:
https://github.com/brave/browser-laptop/releases/edit/v0.10.4dev

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 and macOS 10.11

**Comment by luixxiul** [comment]
I cannot find the wrong link in the change log.

**Comment by bbondy** [comment]
For me it points to:
https://github.com/brave/browser-laptop/releases/v0.10.4dev

Could you link me to where you mean?  I checked in CHANGELOG.md and also did a `git grep` and didn't find it.

**Comment by stshank** [comment]
I've updated now to the latest version so it doesn't show for me anymore, but it was in the bar that pops up telling me there was an update. The wrong URL was the one supplied if you clicked the "details" button IIRC.

**Comment by bbondy** [comment]
Ah got it, fixed here just now:
https://github.com/brave/vault-updater/commit/e96cad29d15c2b1b8f927a9ac3f72b4862e477fb

I'll try to look out for this in the future. 
CC @aekeus so he can too if I make the mistake again.
