### ISSUE TITLE
1 password prompt per site at a time

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2314]
I often enter a password, have it be wrong, get a notification bar to save.  Then ignore it and put the correct password. Then I have 2 bars. And at that point I don't know which one belongs to the correct password so I want the correct password saved but can't tell which one it is.
Could we have 1 password bar per site max?  A second one would cancel the first request for that site.

cc @diracdeltas

**Comment by diracdeltas** [comment]
Are you entering different usernames the two times? It used to only show one per username (the newer one replaced the old one) but may have broken recently.

**Comment by bbondy** [comment]
sorry I don't recall, but if I see it again I'll re-open. The notifications twice will maybe solve as well.
