### ISSUE TITLE
cibc.com: can't login with "3rd party cookie block" on. Safari ok with same. 

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#2317]
On 0.10.4, OS X, trying to login here:
https://www.cibc.com/en/personal-banking/credit-cards.html
Problem: Login screen doesn't show success or error, never proceeds
Workaround: 'Allow all cookies'

Safari logs in ok without requiring 'allow all cookies', there must be some difference in Brave regarding how cookies are labelled as 3rd party or not.

**Comment by bbondy** [comment]
@diracdeltas can we special case this domain to unbreak cibc.com?

**Comment by bbondy** [comment]
Ideally we'd only do the one that is needed but this one in particular might be hard to troubleshoot so I'd be fine with just doing it for the whole cibc.com.

**Comment by diracdeltas** [comment]
If it works in Safari, it may be due to blocking referer not cookies. Are there any console errors? What 3rd party domains are being connected to for login?

**Comment by bbondy** [comment]
@garvankeeley if you can try please, I don't have a CIBC account.

**Comment by garvankeeley** [comment]
You don't need a CIBC account, just type in anything, no error shown. 
Although I mentioned Safari, that is a red herring here, CIBC is one of the largest banks in canada, their login would work on all browsers.

Not sure from skimming the thread what I am to check.

**Comment by diracdeltas** [comment]
it's indeed a referer issue, which is easy to fix. i usually compare behavior in brave vs behavior in chrome w/ 3p cookies blocked to see if the issue is actually cookies/localstorage or referer.
