### ISSUE TITLE
OS X Browser level dev tools doesn't allow copy/paste

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2318]
This is only an annoyance for us working on the browser itself. You can't use dom inspector and copy and paste. The content level dev tools does work though.

**Comment by Liunkae** [comment]
Seems fixed. I cannot reproduce with Brave 0.20.30 on macOS 10.13.x.

**Comment by bsclifton** [comment]
Confirmed fixed 😄 👍
