### ISSUE TITLE
Make Brave in the UA for the Adobe Flash site

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2319]
@diracdeltas would you mind taking?

**Comment by diracdeltas** [comment]
sure, i'll just set it on all adobe.com domains for now

**Comment by diracdeltas** [comment]
actually i'll just set it on adobe.com, get.adobe.com, www.adobe.com, and helpx.adobe.com

**Comment by diracdeltas** [comment]
fixed by 811e742b4bdb393cc9dc092d9d61af2bb879a047
