### ISSUE TITLE
Not many spots to click/hold to move the browser

### ISSUE THREAD

**Issue by AndyM-DC** [brave/browser-laptop#2321]
There seems to be few sensitive areas that can be clicked on and dragged to move browser window. There only appears to be a few near the logo and near the forward/backward buttons. Except even fewer than what appear actually work. 

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bradleyrichter** [comment]
yep...this happened recently with a PR that expanded the URL bar all the way to the Right, but too early. We will fix this soon.

**Comment by bradleyrichter** [comment]
Adding 30px to the right-margin on the bookmark button solves this one. Can be closed after next release.

**Comment by bsclifton** [comment]
Fixed w/ https://github.com/brave/browser-laptop/pull/3155
