### ISSUE TITLE
Use System default Fonts 

### ISSUE THREAD

**Issue by stanleyxu2005** [brave/browser-laptop#2324]
I'm using Brave 0.10.4 on Win7. I really love this application. I notice one optical issue: The font of Win7 is usually "Segoe UI 9pt", but I guess Brave uses "Arial" or something else overall on Tab, Menu, Adressbar and Bookmark Toolbar. 

Do you mind to use system font by default?

**Comment by bradleyrichter** [comment]
Thanks @stanleyxu2005!

@bbondy We recently talked about this but I'm not sure if we found the answer? There may be a bug if the default is not appearing.

**Comment by stanleyxu2005** [comment]
In the less folder, there is only font size definition, but no font face definition. I don't know, if you can add a font face and give a try. For windows it will be "segoe ui" (9pt), for mac and linux, the setting is different.

**Comment by bradleyrichter** [comment]
Perhaps having no definition was supposed to allow the default system font to work. 

LMK if you find a solution...

**Comment by luixxiul** [comment]
+1, on 0.10.4 the Japanese characters on tabs are poorly rendered.
![](https://cloud.githubusercontent.com/assets/3362943/16485677/2d9f6088-3efb-11e6-9cfb-0d0ed917a150.jpg)
I assume the different font sets are used at the same time.

**Comment by stanleyxu2005** [comment]
I don't know if you can change fonts when creating a `BrowserWindow`.
I see something interesting. 
```
const win = new BrowserWindow({
  webPreferences: {
    defaultFontFamily: {
      sansSerif: 'segoe ui' // can also try "'segoe ui',arial"
    }
  }
});

https://github.com/electron/electron/blob/master/docs/api/browser-window.md

**Comment by darkdh** [comment]
+1 from support
https://linkbubble.zendesk.com/agent/tickets/5727

**Comment by stanleyxu2005** [comment]
@bradleyrichter I think the recent release has changed the font settings. It looks much better for ASCII chars. But for Chinese and Japanese chars, I still think there can do some tweaks. It would be great, if there is a config file we can customize and test. I don't really have the environment to build Brave from scratch, just for some tweak font tuning. Thanks

**Comment by leavehouse** [comment]
+1 from me. Chrome and all Chrome-based alternative browsers (like Brave) have this defect, and it's quite annoying. I'm on Ubuntu and use a system font size of 14, but Brave doesn't respect this for tab titles or the address bar, so the text is unreadably small.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/696
