### ISSUE TITLE
When tab is closed, focus is set to the last pinned tab... not the tab to the left of what was closed

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#2333]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
This has been driving me nuts for a while. When you close a tab, it'll send the focus over to the LAST pinned tab that you have... ignoring the actual tabs you have open.

**Expected behavior:**
I would expect this to either give focus to the last tab that's open OR give focus to the tab to the left of what was just closed. Looking to other browsers like Chrome for guidance would be a good idea.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.10.4

- Steps to reproduce:
    1. Have at least one pinned tab (maybe github.com)
    2. Open two new tabs (maybe google.com and then bing.com)
    3. Close the bing.com tab
    4. Notice focus is now sent to the pinned tab (in this case, github.com) and not the already open tab (google.com)

- Screenshot if needed:

- Any related issues:

**Comment by bradleyrichter** [comment]
yes please! Needs to go in soon. It's driving me nuts...

(cc @bbondy )

**Comment by bsclifton** [comment]
Self assigning because I can't take it anymore :stuck_out_tongue:

**Comment by bradleyrichter** [comment]
That's the spirit! Thanks Brian...

**Comment by bradleyrichter** [comment]
BTW - As you are working it, pay close attention to how the Close Tab works. (CMD + W). There are some related problems there.

![image](https://cloud.githubusercontent.com/assets/13509546/16462506/715e7d88-3de6-11e6-8a36-5d36057a0a08.png)

**Comment by bsclifton** [comment]
@bradleyrichter the menu ends up using the same code so the potential fix *should* resolve that too :smile: (thanks for the heads up!)

There is a slight difference- I'll need to check the parameters sent. The menu version uses an IPC message SHORTCUT_CLOSE_FRAME to trigger the closeWindow() call instead of calling directly.

The code which picks the wrong tab is here:
https://github.com/brave/browser-laptop/blob/master/js/state/frameStateUtil.js#L363

The active index - 1 just happens to pick the pinned tabs (tabs restored from session have a lower index than the pinned tabs). Gonna dig in tonite on this
