### ISSUE TITLE
flash placeholder may be too small to read text

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2336]
ex, on http://www.itma.vt.edu/tech/shockwave.htm:
![screen shot 2016-06-29 at 4 15 18 pm](https://cloud.githubusercontent.com/assets/549654/16471903/e9a028c2-3e14-11e6-8e79-db69c37f3470.png)

probably good enough to just scale down the placeholder. the minimum placeholder size may also need to be increased.

**Comment by fibric** [comment]
The file to change. https://github.com/brave/browser-laptop/blob/master/less/about/flash.less

I have no Flash installed on my Mac; can't adjust the styles.

**Comment by luixxiul** [comment]
I installed Pepper plugin and confirmed it worked on some video sites, but I don't see any placeholder there. Is CtP just on master for now, @diracdeltas ?

**Comment by diracdeltas** [comment]
@luixxiul ctp is in latest release, try y8.com to see if the placeholder appears

**Comment by diracdeltas** [comment]
if you installed flash from get.adobe.com/flashplayer, enable flash in prefs, and restart, it should just work.
