### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by roscoau** [brave/browser-laptop#2341]
OSx 10.11.5
Brave: 0.10.4

When using Google Maps site only the base map loads; none of the other functionality works. No search, routing, satellite view etc. 

This began with the latest release.

**Comment by luixxiul** [comment]
Confirmed. It starts working by disabling the bravery shields.

**Comment by diracdeltas** [comment]
Not sure we should do anything about this, since fingerprinting protection is off by default with a warning that it will break some sites.

**Comment by lucidNTR** [comment]
works in the latest master for me now. maybe close
@luixxiul

**Comment by bsclifton** [comment]
Closing this issue; it's basically a duplicate of https://github.com/brave/browser-laptop/issues/2965. I made sure to add the domain to that issue
