### ISSUE TITLE
Auto removal of ~/.electron?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2344]
Is there any way of either telling users do ``rm -rf node_modules/ && rm -rf ~/.electron`` or removing them automatically if needed? 

#1098, #1550, #2140, etc.

**Comment by bbondy** [comment]
I think we can at least make sure the user has no .electron on npm install.
Set a preinstall script in npm and remove it. We might need to run a script and then do it differently per platform where rm -Rf ~/.electron doesn't work. I don't think we want to auto remove node_mododules, but maybe we can figure out some kind of messaging to tell them somehow.

**Comment by luixxiul** [comment]
Another case #4939

**Comment by bbondy** [comment]
#4939 is not a case of this. We don't re-use version numbers anymore so I don't think there is a benefit of this anymore. 
With all of npm if you npm install on top of a dependency that is already installed, it does not update the dependency.

**Comment by bbondy** [comment]
This issue was only a real problem when we tried to stay in sync with the upstream electron version numbers and re-used the same version number.

**Comment by luixxiul** [comment]
Sorry I'm a bit confused. So we don't need to delete ``~/.electron`` even if brave/electron was updated, am I right?

**Comment by bbondy** [comment]
that is right, it doesn't need to be updated because the files in that folder are named with the electron version. And for all electron changes we now update the electron version now.
