### ISSUE TITLE
Make bookmark icon more visible

### ISSUE THREAD

**Issue by dogancelik** [brave/browser-laptop#2347]
**Did you search for similar issues before submitting this one?** Yeah
**Describe the issue you encountered:** Bookmark icon near location bar is not clear
**Expected behavior:** It should be full orange star, not empty orange star.
**Version:** Windows 8, Brave 0.10.4

**Related screenshots**
- Firefox:  
  ![firefox](https://cloud.githubusercontent.com/assets/486818/16487340/f31379f4-3ed2-11e6-8da2-0d8e581550b6.png)
- Chrome:  
  ![chrome](https://cloud.githubusercontent.com/assets/486818/16487341/f409ee6a-3ed2-11e6-9db2-6535db7a2513.png)
- Vivaldi:  
  ![vivaldi](https://cloud.githubusercontent.com/assets/486818/16487539/3b6454de-3ed4-11e6-962e-94d7ad9b9de6.png)
- Brave:  
  ![brave](https://cloud.githubusercontent.com/assets/486818/16487394/491794d4-3ed3-11e6-8619-cb8e8ef69565.png)

**Comment by luixxiul** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
@dogancelik Our plan is to fix a few things by moving the bookmark button into the URL bar, and adding the filled yellow star color. LMK if you have any thoughts on this UI change:

![image](https://cloud.githubusercontent.com/assets/13509546/16601961/3ee0f65e-42c5-11e6-8b5a-6841d85f10e9.png)

**Comment by dogancelik** [comment]
@bradleyrichter Is there a reason (like UX) for moving the bookmark button to the left?

**Comment by srirambv** [comment]
Can the bookmark icon still be shown when the URL is hidden?

**Comment by bradleyrichter** [comment]
yes. with this design change (moving the BM button to the left, all of the buttons including the BM star can remain visible when the URL bar changes to the title bar on mouse-leave.

**Comment by bsclifton** [comment]
@bradleyrichter now that we've merged https://github.com/brave/browser-laptop/pull/4726, do you think this issue should be closed?

**Comment by luixxiul** [comment]
Let's close for now 😉
