### ISSUE TITLE
Make a brave/electron build on Ubuntu for x86

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#235]
Get the binary on:
https://github.com/brave/browser-laptop-releases/tree/gh-pages/0.36.3 for this version and future versions.  brave/browser-laptop-releases is just a storage repo for github pages for the electron-prebuilt forks.

Ideally we could do this via a Dockerfile so we can easily run this on consistent infrastructure in the future.

Otherwise people trying to build on x86 will get this:
https://github.com/brave/browser-laptop/commit/8d69eb13ebf8e04ed391e66aa0d7a7f2e801b687#commitcomment-15604556

**Comment by luixxiul** [comment]
Was fixed already?

**Comment by bbondy** [comment]
Not yet, we're only doing x64 ubuntu for now.

**Comment by Liunkae** [comment]
Related: #2468 (support 32-bit Linux)

**Comment by posix4e** [comment]
Closing this as a dup
