### ISSUE TITLE
downloadInProgressUnknown shows in downloads bar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2351]
When downloading a file for a filesize that is unknown downloads toolbar shows the l10n ID instead of the localized string.

An example of this is the github releases page downloading a source code bundle.

It should show the localized string there.

**Comment by ludable** [comment]
@bbondy Hi Brian,

I'm trying to get familiar with the project and lend a hand. This is my first (and quite trivial) commit. The CI tests failed but I'm almost certain it wasn't due to the changes introduced in this commit.

Cheers,
L.

**Comment by bbondy** [comment]
yep not related, thanks for doing this, merged!
