### ISSUE TITLE
windowActions docs breaking after unescaped tag

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#2360]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
windowActions documentation has an unescaped tag, breaking all text below & therefore making docs unreadable.
**Expected behavior:**
Readable document.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Not applicable
- Brave Version:
Not applicable.
- Steps to reproduce:
    1. Go to: https://github.com/brave/browser-laptop/blob/master/docs/windowActions.md#setframetitleframeprops-title

- Screenshot if needed:
![brave-docs](https://cloud.githubusercontent.com/assets/4672033/16512939/b766c8a2-3f36-11e6-8404-27dc9d75929f.png)

- Any related issues: Not applicable.

**Comment by bbondy** [comment]
No harm in keeping the commit in, but this will not be very long lived because the docs are auto generated on each commit.  See `npm run docs` from the package.json scripts section.  Any changes would need to be in the jsdoc source code comment blocks or options sent to jsdox.
