### ISSUE TITLE
Twitch two factor authentication does not work

### ISSUE THREAD

**Issue by likewei92** [brave/browser-laptop#2362]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  MacOS
- Brave Version:
  0.10.4
- Steps to reproduce:
  1. Go to twitch.tv
  2. Log out of all accounts
  3. Try to log into an account with two factor authentication enabled
  4. Page refreshes itself without reaching the page where you can enter the two factor authentication code
- Screenshot if needed:
- Any related issues:

**Comment by gravitycrusher7** [comment]
Same issue here, just test it after enable 2fa

**Comment by bbondy** [comment]
Does turning shields off work? If so would you mind figuring out which toggle is the one that helps unbreak it?

**Comment by likewei92** [comment]
Thanks for responding! Turning off shields does not work unfortunately

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/twitch-two-factor-authentication-does-not-work/10101

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
