### ISSUE TITLE
Cannot Pin Tabs to One Window

### ISSUE THREAD

**Issue by TognaBologna** [brave/browser-laptop#2363]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When using OS X 10.11.5 (15F34) with Brave 0.10.4, I cannot pin a tab to only one window. When I pin the tab on one Brave window, it appears on the other window(s) as well.

**Expected behavior:**
I should be able to pin different tabs to different windows.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X 10.11.5 (15F34)

- Brave Version:
Brave 0.10.4

- Steps to reproduce:
    1. Open two Brave windows
    2. Pin a tab to one window
    3. Notice that it appears in the other window

**Comment by luixxiul** [comment]
I think this is intended but we can reconsider it

**Comment by bbondy** [comment]
This is intended for now but we plan to make the webview follow around your active window instead, so the pinned tab would always be in the same state (even scroll position, selected text, etc) across all windows and use less resources.
