### ISSUE TITLE
HTTPS Everywhere doesn’t always force on subdomains

### ISSUE THREAD

**Issue by neeklamy** [brave/browser-laptop#2367]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Visiting a site which:

- Serves on both http and https
- Has a subdomain
- Won’t redirect to the secure protocol

**Expected behavior:**
Brave is redirected to the secure protocol.

**Platform:**
OS X 10.11.5

**Brave Version:**
0.10.4

**Steps to reproduce:**

1. Visit a site with a subdomain, that can be viewed over either http or https, for example: http://3dprinting.stackexchange.com
2. Brave **isn’t redirected** to https://3dprinting.stackexchange.com
3. This also happens if you type or paste in the URL with no protocol, `3dprinting.stackexchange.com`

**Notes:**
I don’t think this is down to HTTPS Everywhere, as the HTTPS Everywhere extensions for Chrome and Firefox work as expected.

Visiting http://stackexchange.com redirects to https://stackexchange.com in Brave, and both Google Chrome and Firefox (with extensions enabled).

**Comment by diracdeltas** [comment]
There's a bug in how we are creating hostname patterns. Thanks for catching, fixing now

**Comment by bbondy** [comment]
wont' be in 0.11.0dev since it's already out but will be 0.11.1dev.  Just tag the milestone for next time and I'll include it. Also explicit ping will help ensure it. Thx.
