### ISSUE TITLE
Some Ads are not blocked

### ISSUE THREAD

**Issue by nirnaybansal** [brave/browser-laptop#2369]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Open: http://www.desirulez.me/forums/3883-Dahleez
See the ad on the top, with girls images.
Ads are not blocked.

**Expected behavior:**
Ad should be blocked

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7 and 10

- Brave Version:
0.10.4

- Steps to reproduce:
    1. open http://www.desirulez.me/forums/3883-Dahleez
    2. Check page content with Adv on the top, with lots of girls images
    3.

- Screenshot if needed:

- Any related issues: #1744 #1513 #835

**Comment by hgareeballa** [comment]
same issue also in this website:
https://yifymovie.re/

**Comment by neeklamy** [comment]
On the Dahleez site, are you referring to the strip of adverts at the top of the page?

<img src="https://cloud.githubusercontent.com/assets/155358/16539329/b8133df6-4037-11e6-81c5-d75db224d298.jpg" width="400">

I think Brave uses [Adblock Plus](https://adblockplus.org/) for its filters, the ABP extension on Google Chrome just so happens to let the same adverts through and disallowing non-intrusive adverts didn’t change that. If it is, then you can [report it as a bug to ABP](https://adblockplus.org/en/bugs).

As for the second site, I’m not seeing any adverts (in either Brave or Google Chrome with ad blocking disabled), could you get a URL and screenshot of a page it appears on?

(Side note, I’d be wary of spending much time on YIFY Movie, I got a whole load of malware pages pop-up for “Adobe Flash” and the like, who knows what other malware they’re pushing.)

**Comment by hgareeballa** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6079147/16539476/90a6de76-4055-11e6-9a0f-1776d6cc7984.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/6079147/16539477/90b58610-4055-11e6-95b6-68a78c70cb08.jpg)

Attached screen shot,
you need to click on any of the movie link to get the popup

**Comment by neeklamy** [comment]
@hgareeballa, those aren’t exactly adverts, it would broadly come under malware. Brave uses @bbondy’s [abp-filter-parser-cpp](https://github.com/bbondy/abp-filter-parser-cpp) project (so yes, it uses Adblock Plus), which in turn uses a few [adblock lists](https://github.com/bbondy/abp-filter-parser-cpp/wiki/Adblock-lists) …

Possibly related: bbondy/abp-filter-parser-cpp#11 and bbondy/abp-filter-parser-cpp#21 (Google Chrome with Adblock Plus successfully blocks adverts on both those sites, so that suggests it’s an issue with abp-filter-parser-cpp).

**Comment by hgareeballa** [comment]
its still anoying and it would be great if Brave can somehow block them,
in Chome not all adblock can block it,, only few like "Stands"
![image](https://cloud.githubusercontent.com/assets/6079147/16539962/75a4cbb0-4064-11e6-808c-23cd6565db45.png)

so its good if Brave can do the same!

**Comment by neeklamy** [comment]
Interesting, I’d never heard of [Stands](https://www.standsapp.org/) or the Fair AdBlock, wondering if the Brave developers have seen it. Shame it’s not really open source though, makes it a bit harder to see how it blocks those pop-ups.

**Comment by myfavoriteemail** [comment]
http://oferta.senasofiaplus.edu.co/sofia-oferta/

is it possible to remove popovers/modals like the one poping out from this site? thank u!!!!!!!!!!

**Comment by luixxiul** [comment]
Closing this in favor of #344
