### ISSUE TITLE
ERROR with npm install , HELP PLEASE!

### ISSUE THREAD

**Issue by helloitu** [brave/browser-laptop#237]
when i enter npm install , its starts normal , but after 20 minuts , i see this ... help pls......

(sorry for my bad english :c)

npm ERR! Linux 3.2.0-97-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! abp-filter-parser-cpp@1.0.22 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abp-filter-parser-cpp@1.0.22 preinstall script 'npm install bloom-filter-cpp && npm install hashset-cpp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the abp-filter-parser-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install bloom-filter-cpp && npm install hashset-cpp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs abp-filter-parser-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls abp-filter-parser-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by eliperelman** [comment]
@helloitu Node.js 0.12.x is too old to run Brave, please update to the latest 5.x line.

**Comment by helloitu** [comment]
thanks

**Comment by helloitu** [comment]
so , i downloaded the zip from nodejs.org , and , now how install? :P

**Comment by eliperelman** [comment]
Honestly I find installing Node.js easier from a package manager than from a zip everytime. You could follow [1] for more info.

My preferred route though is to use the "n" package on npm, which lets you easily switch Node.js versions:

https://www.npmjs.com/package/n

[1] https://nodejs.org/en/download/package-manager/

**Comment by helloitu** [comment]
@eliperelman  a lot of thanks bro , ^^

**Comment by sidstamm** [comment]
I was struggling with node and npm versions for a while, then I installed nvm and told nvm to use node 5.5 and all my problems went away. Maybe this will help folks who have similar problems but the great advice from @eliperelman doesn't work. (http://nvm.sh)

**Comment by eliperelman** [comment]
Agreed, both "n" and "nvm" are good Node.js version managers.

**Comment by helloitu** [comment]
@eliperelman  hei man , i got another error here , a lot of errors 

gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/home/dosnut/browser-laptop/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack at emitTwo (events.js:100:13)
gyp ERR! stack at ChildProcess.emit (events.js:185:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-97-generic
gyp ERR! command "/usr/local/bin/node" "/home/dosnut/browser-laptop/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dosnut/browser-laptop/node_modules/.staging/tracking-protection-0f503ffa/node_modules/hashset-cpp
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
install ��� ��������������������������������������������������������������������������������������������������������������������������������install ��� rollbackFailedO ��� ������������������������������������������������������������������������������������������������������������������������������install ��� rollbackFailedO ��� ������������������������������������������������������������������������������������������������������������������������������runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������npm ERR! Linux 3.2.0-97-generic
npm ERR! argv "/usr/local/bin/node" "/home/dosnut/browser-laptop/node_modules/.bin/npm" "install" "hashset-cpp"
npm ERR! node v5.5.0
npm ERR! npm v3.4.1
npm ERR! code ELIFECYCLE

npm ERR! hashset-cpp@1.0.13 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashset-cpp@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashset-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls hashset-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/dosnut/browser-laptop/node_modules/.staging/tracking-protection-0f503ffa/npm-debug.log
preinstall:abp-filter-par ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall:abp-filter-par ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall:tracking-prote ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall ��� lifecycle ��� ������������������������������������������������������������������������������������������������������������������������������preinstall ��� unlock ��� ������������������������������������������������������������������������������������������������������������������������������runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������brave@0.7.7 /home/dosnut/browser-laptop
��������� electron-packager@5.2.1
��� ��������� electron-download@1.4.1
��� ��������� home-path@1.0.1 
��������� electron-prebuilt@0.36.3 (git://github.com/brave/electron-prebuilt.git#11c3984ca0e0d1188827ab1e84b25ba7435e4b6c)
��������� electron-download@1.4.1
��������� home-path@1.0.1

runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.5
runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
runTopLevelLifecycles ��� ��������������������������������������������������������������������������������������������������������������������������������npm ERR! Linux 3.2.0-97-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! abp-filter-parser-cpp@1.0.22 preinstall: npm install bloom-filter-cpp && npm install hashset-cpp
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abp-filter-parser-cpp@1.0.22 preinstall script 'npm install bloom-filter-cpp && npm install hashset-cpp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the abp-filter-parser-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm install bloom-filter-cpp && npm install hashset-cpp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs abp-filter-parser-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls abp-filter-parser-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/dosnut/browser-laptop/npm-debug.log

**Comment by diracdeltas** [comment]
I think this is a dupe of #214 as well. @sidstamm interesting that node 5.5 solved it for you

**Comment by sidstamm** [comment]
I had been using node 0.12 on Ubuntu 14.04.  I didn't try 5.4!

**Comment by bbondy** [comment]
Please use the latest Node, 5.9 at the time of this writing. Thanks!  Closing this.
