### ISSUE TITLE
Fingerprinting and "notifications showing twice" automated tests are failing

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2370]
https://travis-ci.org/brave/browser-laptop/builds/141841305

I haven't checked if it's intermittent or not.
cc @diracdeltas

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by diracdeltas** [comment]
seems these are fixed now https://travis-ci.org/brave/browser-laptop/jobs/233773486

**Comment by alexwykoff** [comment]
Yep, if it's broken we can reopen
