### ISSUE TITLE
YouTube Audio Stops After Switching Tabs

### ISSUE THREAD

**Issue by AdamBrodzinski** [brave/browser-laptop#2373]
**Did you search for similar issues before submitting this one?**
Yes, none with this issue found

**Describe the issue you encountered:**
YouTube audio stops playing when switching tabs. I can't replicate this on Vimeo.

**Expected behavior:**
Audio should continue to play after switching tabs.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS 10.11.5
- Brave Version:
  0.10.4
- Steps to reproduce:
1. play a YouTube video
2. switch tabs back and forth
3. eventually the audio stops playing
   
   Even a refresh does not bring audio back. However opening a new tab and pasting the youtube URL will make it work again.
- Screencast of reproduction: 
  https://www.dropbox.com/s/f48wm716d0azakc/youtube-bug-repro.mov?dl=1

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/youtube-audio-stops-after-switching-tabs/10453

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
