### ISSUE TITLE
Brave for Windows crashes when opening Google Docs document

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#238]
1. Opened drive.google.com
2. Double-clicked a Doc
3. App totally crashed.

The doc opened fine when I copied the URL from a different browser and pasted it into the address bar.

**Comment by diracdeltas** [comment]
My app doesn't crash, but it shows this error repeatedly and refuses to load the goog doc. @aekeus are we getting crash reports for things like this?

![screen shot 2016-01-22 at 11 06 42](https://cloud.githubusercontent.com/assets/549654/12520304/9709bc7a-c0f8-11e5-8c16-fd1092851dbe.png)

**Comment by aekeus** [comment]
I can duplicate using the steps listed above. @yan, no those are not being sent as crash reports.

**Comment by diracdeltas** [comment]
Super weirdly, I can open the doc if I copy-paste the link into a new tab, but not if i double click it from Goog drive.

**Comment by wblondel** [comment]
I have the same issue. It does the same with Sheets.

**Comment by 0chucha0** [comment]
Reproduced for Mac also (OS X El Capitan)

**Comment by stshank** [comment]
I just tested on Mac OS X El Capitan 10.11.4 beta 1 and got the same error message as @diracdeltas: "This error has been reported to Google and we'll look into it as soon as possible. Please reload this page to continue." This with Brave 0.7.9 (0.36.3).

**Comment by brettholz** [comment]
As another google drive user I can confirm having this same issue. Oddly, copy-pasting a link to the specific file has allowed me access to that file, just not through the intuitive double-clicking of it in google drive.

**Comment by bridiver** [comment]
This works for me on OSX with tip browser and electron. Maybe another change fixed it or Google changed something on their end? Is anyone else still seeing an error?

**Comment by diracdeltas** [comment]
Seems to be working now!

**Comment by stshank** [comment]
Works for me on Mac OS X El Capitan 10.11.4 beta 3 (or is it beta 4?). Haven't tried on latest Windows.

**Comment by stshank** [comment]
I just tested on Windows 10, also. It didn't crash but it put the focus on the address bar instead of the document text.

**Comment by luixxiul** [comment]
Closing as the problem reported was fixed
