### ISSUE TITLE
Flash download link is unclickable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2384]
**Describe the issue you encountered:** The link is just a text, not a link

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.10.4

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/3362943/16548709/286d6f42-41d0-11e6-89fc-4dcb59287506.jpg)

Has this been fixed on master already?

**Comment by bittoe** [comment]
ibid.

also
https://scratch.mit.edu does not function
