### ISSUE TITLE
Shockwave support

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2385]
From support /tickets/4438

**Comment by luixxiul** [comment]
+1 from support

**Comment by srirambv** [comment]
Issue on TSN.ca. Video doesn't load as it uses shockwave flash object. 
![image](https://cloud.githubusercontent.com/assets/17010094/18869280/86703a1e-84a3-11e6-925a-dcb29eacda0a.png)

**Comment by luixxiul** [comment]
For now I'm going to close this issue for this topic:

https://community.brave.com/t/shockwave-support/10195

Let's see if Shockwave is still popular ..
