### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by lednhatkhanh** [brave/browser-laptop#2386]
Do you have any plans on changing Brave's UI? The current look boring on windows compared to other browsers.

**Comment by cezaraugusto** [comment]
Hi @lednhatkhanh. Sure, there are great visual enhancements coming soon.

If you'd like a preview, [these issues](https://github.com/brave/browser-laptop/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation+label%3Asettings) often have visual information of what's going to be made.

Also [this issue](https://github.com/brave/browser-laptop/issues/886), and most specifically, [this file](https://github.com/brave/browser-laptop/files/143685/brave_laptop_settings_spec_022316.pdf), shows off some ongoing changes.

/cc @bradleyrichter if there's more info about your question.

**Comment by SJ-Diamond** [comment]
I guess the topic opener was referring to general UI design, perhaps round tabs and something like that. As he wrote about current look and not underlying features ;)

**Comment by bradleyrichter** [comment]
We will roll out of batch of UI styling refinements before 1.0 which includes some new dimensionality in various places, plus the removal of the windows titlebar which seems to be the #1 complaint about the Windows UI so far.

@lednhatkhanh Are you running Windows 10? Curious as to what you think of the Edge UI styling? I know in general Win 10 has pushed the flatness even further but I wonder if users are liking it...

**Comment by lednhatkhanh** [comment]
@bradleyrichter Current EDGE UI is good, especially the dark theme, but I prefer Chrome Material design.
But if the browser should is more colorful, not just the gray one, I think some dark color or white will be better.
Sorry for my bad English :|

**Comment by srirambv** [comment]
@bradleyrichter  Couple of things that could make the UI more interesting.
1. One the back and front button, rather than showing the round button on mouse hover it would be nice if the color of the arrow itself changes (similar to the Bravery panel icon on the rightside)
2. Option to choose images as themes for the browser

**Comment by SJ-Diamond** [comment]
The UI is also too static right now. Power uses love customization, they want to change elements, move bars to other locations (at the side, at the very bottom). Also, like mentioned theme options or options to change color of UI elements. Take a look for the nice theme options Vivaldi has lately included. It would be great to have that in Brave too.

But there are already suggestion reports for all of this. In short, the UI should allow that the user is being able to change the look, color, font size and the order of element placement should be allowed to be changed too.

This would make Brave UI the same way as awesome the same way like Vivaldis UI ;)

**Comment by maverick74** [comment]
What i would REALLY LIKE would be to be able to Customize Brave's UI like i do in Firefox!!!
E.g.: Pick the reload button and move it to the right side of the URL bar. Or do the same thing with the Reload button.

I would also like the bookmarks bar to show Favicons.

Any chance for any of this two requests?! (Customize the UI is a must-have for me!)

**Comment by Liunkae** [comment]
@maverick74 For no. 2, you can adjust the bookmarks bar in Settings > General > Bookmarks Bar. Screenshot:
![image](https://cloud.githubusercontent.com/assets/19424103/22433689/d82ee696-e6de-11e6-88af-56c50202e783.png)

**Comment by maverick74** [comment]
Ups... miss overlooked that one!!! Thanks

How about the first one?

**Comment by Liunkae** [comment]
@maverick74 I've submitted a suggestion for basic customization of UI elements: #6928.

**Comment by maverick74** [comment]
@Liunkae Great!!! #6928 and https://github.com/brave/browser-laptop/issues/246 was exactly what i meant!!! Thanks

**Comment by bsclifton** [comment]
Closing this issue in favor of https://github.com/brave/browser-laptop/issues/246 (which has more actionable comments).  Please feel free to leave feedback there 😄
