### ISSUE TITLE
Problem with installation on Ubuntu Linux

### ISSUE THREAD

**Issue by JShakespeare** [brave/browser-laptop#2387]
The output of the command for installing on Xubuntu 14.04 is below (from sudo dpkg -i ./brave.deb). The browser did install and apparently is OK, from limited testing. There is an unnecessary dependency on the git package.

Selecting previously unselected package brave.
(Reading database ... 1918696 files and directories currently installed.)
Preparing to unpack ./brave.deb ...
Unpacking brave (0.10.4-1) ...
dpkg: dependency problems prevent configuration of brave:
 brave depends on git; however:
  Package git is not installed.

dpkg: error processing package brave (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Errors were encountered while processing:
 brave

**Comment by Nathean** [comment]
I had the same problem with unmet dependencies. This happens on every fresh install of Ubuntu and can be easily fixed in the terminal:
sudo apt-get update
sudo apt-get -f install

After this, everything should be fine. It is for me.

**Comment by JShakespeare** [comment]
Hi Nathean,
Perhaps the installation instructions for Ubuntu should specify that git, git-man, and liberror-perl are required with brave.deb, and suggest including a line if they are not already installed (sudo apt-get -f install).

**Comment by Nathean** [comment]
It would also be nice if Brave had its own repository like Google Chrome or Vivaldi does. At the moment, you can't auto update each time a new version of Brave is released. You have to do it manually with wget and dpkg.

**Comment by posix4e** [comment]
For now they are still required. They will be pulled soon though!
