### ISSUE TITLE
Flash enabling messaging needs some improvements

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2389]
This doesn't suggest changing anything except for the messaging for Flash.

Currently it always says it's not installed and to install via a website.  The user has to always click website even when its' already installed, which isn't intuitive.

It would be better if we just had the notification bar tell the user from the start what the state is (installed or not) and give an appropriate message right there for the next action they need to take if they want to enable.

cc @diracdeltas

**Comment by bbondy** [comment]
The above is for the notification bar, the Click to play is also a problem. It should direct to the install page instead of still offering to click to play.  We won't block on it since it's still worded as experimental though.

**Comment by diracdeltas** [comment]
> The user has to always click website even when its' already installed, which isn't intuitive. It would be better if we just had the notification bar tell the user from the start what the state is (installed or not) and give an appropriate message right there for the next action they need to take if they want to enable.

I'm not sure what you mean here. The notification bar doesn't appear until the adobe link is clicked because we have no other way to tell if the site requires Flash. Unless it tries to load Flash objects anyway, but often sites don't.

**Comment by bbondy** [comment]
Here is an example message on my computer which does have Flash installed. The message tells me to go download Flash from Adobe's website which shouldn't be my next action.

When I click the link called "website" in the screenshot it takes me to the correct next action.  But the message that we give in the notification box is just wrong.

<img width="1403" alt="screenshot 2016-07-05 14 41 34" src="https://cloud.githubusercontent.com/assets/831718/16595712/9d37128a-42be-11e6-8c85-e63580a6fa1a.png">

**Comment by diracdeltas** [comment]
@bbondy that message is from myspace.com, not Brave.

**Comment by bbondy** [comment]
oh! sorry for the confusion 👍

**Comment by diracdeltas** [comment]
np, this is a good example of why Brave's notification bar messages appear above the tab, not in the webview area. :)
