### ISSUE TITLE
Useragent weirdness with Google new sign-in alert

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#239]
I logged into Gmail with dual-factor authentication using Brave for Windows. Google sent me an email saying there's been a new login from Chrome for Windows. Maybe this is Google's problem, maybe not.

**Comment by diracdeltas** [comment]
I think this is Google's problem; they can in theory figure out that the browser is Brave based on our UA string.

**Comment by bbondy** [comment]
Agree I'll close this for now unless we discover more proof we can do more.
