### ISSUE TITLE
Hidden menu in Windows full screen should allow Alt to unhide

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2394]
When in full screen on Windows with the always show menu option, the menu bar should revert to being able to be shown when alt is pressed.

Before we used to always show it which is wrong, and now we never show it.
Ideally it would be in between where it just functions the same as if the menu option is off when in full screen.

cc @bsclifton

**Comment by ThEMarD** [comment]
Heyyo, I would also love to see this change
