### ISSUE TITLE
Login on Kayak does not work

### ISSUE THREAD

**Issue by likewei92** [brave/browser-laptop#2396]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Login on kayak.com does not work, even with all shields down

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS (10.11)

- Brave Version:
0.10.4

- Steps to reproduce:
    1. Go to kayak.com
    2. Click on Login
    3. Nothing happens

- Screenshot if needed:

- Any related issues:

**Comment by neeklamy** [comment]
I managed to log in, although the log in process is somewhat messed up.

As you say, *nothing happens*, but if you just reload the page, you’ll see that you are in fact logged in.

I tested against Brave 0.10.4 too, I can confirm the log in process works as expected on Safari 9.1.1.

Devs: If you don’t have a [Kayak](https://www.kayak.com/) account (I’d never heard of the service) and you don’t want to be signing up just to test this out, well, there are [ways to find logins…](http://bugmenot.com/view/kayak.com) (the YOPmail one works).

**Comment by neeklamy** [comment]
I managed to log in, although the log in process is somewhat messed up. One thing to note is that if you’re not seeing the “Login” form, hit the “Sign up” button instead (top right of the page) or a prompt such as “Sign in to unlock up to 35% savings…” might appear (it doesn’t always seem to appear):

![image](https://cloud.githubusercontent.com/assets/155358/16569044/702fd79e-4229-11e6-9745-f664064d20dc.png)

As you say, *nothing happens*, hitting the “Login” button appears to do nothing, *but* if you just reload the page, you’ll see that you are in fact logged in.

I tested against Brave 0.10.4 too, I can confirm the log in process works as expected on Safari 9.1.1.

Devs: If you don’t have a [Kayak](https://www.kayak.com/) account (I’d never heard of the service) and you don’t want to be signing up just to test this out, well, there are [ways to find logins…](http://bugmenot.com/view/kayak.com) (the YOPmail one works).
