### ISSUE TITLE
Flash can't be enabled on this site

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2397]
Test site:
http://www.sheppardsoftware.com/canada_caps_L_Click.html

There should be an overlay about click to play.

**Comment by bbondy** [comment]
nevermind, that page turns out to just be a JS error on the page (probably from blocking).

So the issue here is just that if there's a page JS error, our insertion script doesn't seem to run anymore.

**Comment by bbondy** [comment]
cc @bridiver

**Comment by bridiver** [comment]
Content scripts run in a isolated world and page errors don't have any effect on them. I see "got too-small Flash element" from flashListener.js

**Comment by bbondy** [comment]
ok good, so maybe it is just a blocked flash resource? I wonder if that's how they render when they are blocked.

**Comment by bbondy** [comment]
Removing this from 0.11.1dev because it doesn't seem as bad as originally thought.  Still valid but not a priority.

**Comment by diracdeltas** [comment]
@bbondy the message isn't actually an error, I logged it only to see how many times there appear Flash elements that are smaller than the minimum CtP size. Can take it out if it's confusing. In either case, the small elements should be blocked unless Flash is allowed via user approval.

**Comment by bbondy** [comment]
The message isn't concerning to me then, I just thought it might help find the problem. 
The root problem is that flash is enabled and you can't use CtP and you don't have a bar. I guess the bar should be present here.

**Comment by bbondy** [comment]
<img width="266" alt="screenshot 2016-07-05 12 27 33" src="https://cloud.githubusercontent.com/assets/831718/16591889/10cffff8-42ac-11e6-86b8-e97b919bc824.png">
<img width="363" alt="screenshot 2016-07-05 12 27 58" src="https://cloud.githubusercontent.com/assets/831718/16591894/144cbcd4-42ac-11e6-8c9f-7d2cf98e65be.png">

**Comment by diracdeltas** [comment]
This ticket is essentially part 4 of https://github.com/brave/browser-laptop/wiki/Flash-Support-Proposal

**Comment by diracdeltas** [comment]
Fixed by 9f4dceb1ecf2fcd4486cd2a0870a56936af91fcb actually
