### ISSUE TITLE
UI tweak for storage blocking in Bravery Panel and prefs

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2398]
Currently we only say block 3rd party cookies in the bravery panel and preferences, but we actually also block other things like 3rd party storage.

Could you suggest alternate wording @bradleyrichter ? Perhaps Block 3rd party content?
And a new title instead of Cookie Control, maybe "Storage Control"?

Also can we put a new stat for that @diracdeltas or is it not as easily detectable when it blocks things?

**Comment by bradleyrichter** [comment]
@bbondy One concern would be about discoverability of cookie control choices if we removed "Cookie" from all places. Content overlaps ads, and storage may be hard to understand. 

Great puzzle to solve for sure! I'll start thinking about it...

**Comment by diracdeltas** [comment]
We can add a new stat for this but I'm guessing @bradleyrichter is not a fan of making the panel wider.

'3rd party storage' or '3rd party data' maybe

**Comment by luixxiul** [comment]
now the compact bravery panel was implemented with #8990, we could add a new row on that panel experimentally :-)

**Comment by bradleyrichter** [comment]
Are we sure this is "news worthy"?

Do we block iframed page content then?

Some examples would help me.

**Comment by diracdeltas** [comment]
we have to be careful here not to collide with the new 'block (all, 3rd party, no) fingerprinting" setting. "3rd party storage" as a replacement for "3rd party cookies" seems fine to me though.

**Comment by luixxiul** [comment]
I had a difficulty in logging in to Pocket as there was no indication that blocking 3rd party cookies prevented me from logging in.

I thought it would be nice to have another row, or an icon on URL bar like noScript one.

**Comment by srirambv** [comment]
>I thought it would be nice to have another row, or an icon on URL bar like noScript one.
+1 on the icon in URL bar
