### ISSUE TITLE
swipe back/forward doesn't respect system preferences for gestures

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2400]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Swipe back/forward is enabled even if "Swipe between pages" is disabled in System Preferences -> Trackpad -> More Gestures

**Expected behavior:**
Swipe back/forward should be disabled if the gesture is disabled in system preferences
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
  0.11.0
- Steps to reproduce:
  1. Disable "Swipe between pages"
  2. Swipe left/right on any page with forward/back history

**Comment by Liunkae** [comment]
Here are the relevant system preference files:
`~/Library/Preferences/com.apple.AppleMultitouchTrackpad.plist`
`~/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad.plist`
The key is `TrackpadThreeFingerHorizSwipeGesture`.

**Comment by darkdh** [comment]
Required change for https://github.com/brave/electron/pull/33

**Comment by luixxiul** [comment]
Still in 0.11.2?

**Comment by ENDelt260** [comment]
Brave 0.13.0 on macOS 10.12.3 does not respect the system prefs

I have "Swipe between pages" disabled on both my Trackpad and Mouse system preferences. But, swipes navigate history anyway.

**Comment by Liunkae** [comment]
Confirmed not working with Brave 0.13.0 on macOS 10.12.2. Reopening.

**Comment by darkdh** [comment]
Tracked by #5907
