### ISSUE TITLE
Failure to login at bing.com

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2403]
**Describe the issue you encountered:**

Logins fail for bing.com

**Expected behavior:**

Login should succeed and ask to save password
- Platform (Win7, 8, 10? macOS? Linux distro?):

Confirmed on macOS
- Brave Version:

Latest
- Steps to reproduce:
  1. Access bing.com
  2. Attempt to login with valid credentials

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by aekeus** [comment]
Yes. This can be closed.
