### ISSUE TITLE
Suggestion: mute/unmute audio without activating tab

### ISSUE THREAD

**Issue by aoguzhan** [brave/browser-laptop#2406]
Currently, tabs become active when click them to `mute`/`unmute`. Instead, we should be able to mute/unmute tabs `without` activating them. AFAIK, Safari handles it this way.

**Comment by bbondy** [comment]
maybe we need to `preventDefault` on the event or something. Marking as a goo bug for contributors.

**Comment by aoguzhan** [comment]
Hey @bbondy, I fixed and tested this. It is working as it should do.

**Comment by luixxiul** [comment]
Do we need a test for it?

**Comment by bbondy** [comment]
Ideally but it doesn't decrease our test coverage since this wasn't tested before. So I'll merge. Thanks!
I think the main rule of thumb will be "does it decrease our test coverage?"
