### ISSUE TITLE
Ledger: implement "add funds" alert bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2407]
For users who are contributing to the sites they visit on a monthly basis, they will need an alert when it is time to add funds to their account, before the funds need to be deducted by the Brave ledger system.

The following UI mockup shows the flow that begins with this task for the Alert Bar.

![image](https://cloud.githubusercontent.com/assets/13509546/16598697/02ac2c0a-42b4-11e6-853f-dd9858d00d00.png)

And the alert bar by itself:

![image](https://cloud.githubusercontent.com/assets/13509546/16599406/fc4ea57e-42b6-11e6-8f36-d15a45461db2.png)

The alert will be triggered by the ledger, when it is monitoring the active account balance. If the account balance reaches an amount that will not satisfy the set monthly allotment at the next time of processing, it will alert the user through this alert bar. 

If the user chooses "Add Funds", then the alert will close and the user will be redirected to the Payments prefs panel, and the Add Funds dialog will open automatically. 

If this dialog is canceled, then the Alert bar will be reset - as if "Remind me" was clicked.

Remind me will close the alert and the check time will be reset to the following day at first use. 

( @bbondy @mrose17 LMK if more detail is needed for the alert bar )

**Comment by diracdeltas** [comment]
opening follow-up for styling issue

**Comment by bradleyrichter** [comment]
![image](https://cloud.githubusercontent.com/assets/13509546/18333036/4c73c138-7520-11e6-87f0-9d9a7ab55d4c.png)

**Comment by diracdeltas** [comment]
@bradleyrichter please add to https://github.com/brave/browser-laptop/issues/3257 instead
