### ISSUE TITLE
LastPass + New Session Tab

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#2408]
Two tabs open when using lastpass trying to open a new session tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  Brave: 0.11.0
  Electron 1.2.3
  libcromiumcontent: 51.0.2704.103
  V8: 5.1.281.65
  Node.js: 6.1.0
  Update Channel: dev
- Steps to reproduce:
  1. I have logged into my Last Pass account
  2. Works flawlessly in current session
  3. Start a New Session tab, it opens the New Session Tab + New Session Tab to login to LastPass again

**Comment by bbondy** [comment]
@bridiver

**Comment by bridiver** [comment]
That is the expected behavior. The new session tab to login is automatically triggered by LastPass.

**Comment by bridiver** [comment]
actually I guess I'm not sure if you are indicating that the need to login again is a bug or that the opening of the login tab is a bug. The new session tab has it's own state by definition and LastPass is a web service so you will need to login again. There is a LastPass options page that we need to add a link to, but it doesn't appear to have any way to turn off the "create account" tab. I'll contact LastPass and maybe they can add something

**Comment by Charlie-Hustle** [comment]
Thanks for the replies, yes I was hunting around for a LastPass settings page, but it seems as mentioned not yet implemented.

I guess the issue I should have been more specific but you've also mentioned it is the new session 'create account' tab is the annoyance part of this. But I also understand that new session means LastPass cannot auto log me in to any sites, but that's fine.

Basically, I'm a front end developer, and New Session in TAB the way Brave does it is super handy, no more multiple browsers! The forced opening of a second tab asking me to create an account everytime is not so handy.

cheers.

**Comment by bridiver** [comment]
as a temporary workaround, you can get to the lastpass preferences by entering `chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html?dialog=preferences&cmd=open` in the urlbar

**Comment by bridiver** [comment]
Sorry for the delay, just reported to LastPass and waiting to hear back.

**Comment by bridiver** [comment]
I spoke with LastPass and it sounds like this will work correctly when we enable background page sharing with session tabs. Currently the extension background page is only shared with the regular and incognito tabs (just like Chrome), but sessions tabs should be included as well.

**Comment by Charlie-Hustle** [comment]
Great outcome! Many thanks for your time and responses regarding this!
