### ISSUE TITLE
top autocomplete result should appear in URL bar input 

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#241]
1. Type in a web address, e.g. cnet.com
2. Open new tab and start typing that same address
3. Sometimes I see a link to a site below the address bar, but it'd be nice to have a suggested domain autocomplete in the address bar as I type so I can hit just "enter" to navigate to that page, a la Chrome.

**Comment by asadotzler** [comment]
Sounds like #179

**Comment by bbondy** [comment]
Yep I think this is a dupe. Closing.
By the way you can also Control+K (Windows) or Command+K (OSX)  to get search autocomplete.

**Comment by stshank** [comment]
This is separate from https://github.com/brave/browser-laptop/issues/179

Maybe I didn't express it well, but what I'd like to see is that it shows the top autocomplete option in the address bar, and when you hit enter, it navigates to that site. Instead, you see autocomplete options down below, so you have to arrow around or click to activate.

**Comment by diracdeltas** [comment]
Yes, this is separate. I am going to rename and re-open.

**Comment by bbondy** [comment]
Closing in favour of #1596
