### ISSUE TITLE
Support Xmarks plugin

### ISSUE THREAD

**Issue by mjgardner** [brave/browser-laptop#2414]
Absent sync support (#1854), please add support for Xmarks or another cross-browser bookmark syncing service.
#253

**Comment by fabianTMC** [comment]
+1

**Comment by roaet** [comment]
+1

**Comment by boozedog** [comment]
+1 for Xmarks!

**Comment by luixxiul** [comment]
I'd like to recommend you guys add reactions if you are for it (there is a sort function based on the number of thumbs up).

**Comment by boozedog** [comment]
Thanks for the suggestion, have added a thumbs up!

**Comment by tanx** [comment]
Agreed. I switched to Brave as my default browser on iOS and macOS. I can live without bookmark sync for now, but it is a pretty important feature considering all major browsers offer it. An encrypted sync option via a passphrase would also be great for privacy :)

Thanks for great awesome work!

**Comment by echosa** [comment]
Hey, folks, please go :+1: this on the unified extension ticket: https://github.com/brave/browser-laptop/issues/4600#issuecomment-258179070

**Comment by srirambv** [comment]
Closing as its added in the extension list in [community](https://community.brave.com/t/the-list-of-the-requested-extensions/10278)

**Comment by JonCheuvront** [comment]
+1 this is a must for me to keep in sync across multiple platforms and multiple browsers. I will need this before I can go Brave as my default browser.

**Comment by thiagola92** [comment]
+1

**Comment by t3mujin** [comment]
Xmarks is being discontinued, so this may no longer  makes sense

**Comment by echosa** [comment]
Indeed, Xmarks is gone in less than a month. https://www.ghacks.net/2018/03/31/logmein-to-shut-down-xmarks-on-may-1-2018/

**Comment by johnmblack** [comment]
An alternative to Xmarks:
https://www.everhelper.me/synchronizer.php

as recommended by
https://www.ghacks.net/2018/03/31/logmein-to-shut-down-xmarks-on-may-1-2018/

**Comment by monkee13** [comment]
I have moved over to everhelper a while ago now.  Works well.  Wonder if we will ever see Brave support for it.
