### ISSUE TITLE
Latest browser build (0.11.0) not installable on Fedora

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#2415]
<img width="815" alt="screen shot 2016-07-06 at 11 59 40 am" src="https://cloud.githubusercontent.com/assets/210240/16625024/0163974e-4371-11e6-88d3-356fbc40e37f.png">

**Comment by luixxiul** [comment]
Is this the same issue as #2387?

**Comment by aekeus** [comment]
No, I don't think so. This is an .rpm installation issue as opposed to the .deb as noted in #2387.

**Comment by mlopezcoria** [comment]
I've got the same problem in Fedora 24. I run the commands:
```
wget -O brave.rpm https://laptop-updates.brave.com/latest/fedora64
sudo dnf install brave.rpm
```
and the output is
`Error: package brave-0.11.0-1.amd64 is not installable`

That's the exact way I've installed Brave in Fedora 23 without any issue.

**Comment by luixxiul** [comment]
Is it reproducible on the latest version?

**Comment by mlopezcoria** [comment]
Yes it is.

`Sun Aug 21 20:44:30 2016.
Error: package brave-0.11.5-1.amd64 is not installable
`

**Comment by Aeyoun** [comment]
This is a duplicate of #3774.

**Comment by luixxiul** [comment]
Closing in favor of that.
