### ISSUE TITLE
Google Authenticator tab (from LastPass) does not close after success

### ISSUE THREAD

**Issue by bcdady** [brave/browser-laptop#2419]
**Describe the issue you encountered:**
Google Authenticator tab does not close after successful 2-factor authentication with LastPass. 

**Expected behavior:**
Google Authenticator (chrome-extension://) tab should close after successful 2-factor authentication
Expected behavior is based on current functionality In Firefox, Chrome and IE browsers, with LastPass extension/plug-in.
- Platform: Win7
  (I can try a little later to repro also on my MBP)
- Brave Version: 0.11.0
- Steps to reproduce:
  1. I have an existing LastPass account with 2-factor authentication setup, via Google Authenticator
  2. Start Brave browser, and enable LastPass in Security Preferences
  3. Browse to a URL which has username/password sign-in form
  4. Right click login form field, select LastPass from popup menu, and login
  5. A new tab automatically opens (via chrome-extension:// URL) with Google Authenticator form field
  6. Enter digits into Google Authenticator form and either type [Enter] key or click on [Authenticate] button (on web page)
  7. Presuming the digits / Google Authenticator code is valid, focus promptly returns to prior Brave browser tab, to resume filling in login form using LastPass, however Google Authenticator tab does not close.

**Comment by littleStudent** [comment]
having the exact same issue on OSX 10.11.5

**Comment by luixxiul** [comment]
Closing as fixed 👍
