### ISSUE TITLE
Whereis will not load properly

### ISSUE THREAD

**Issue by putheridge** [brave/browser-laptop#2420]
**Did you search for similar issues before submitting this one?**
Yes and there is no information avail.

**Describe the issue you encountered:**
Browsing at the www.whereis.com and the content of the page does not load properly.

**Expected behavior:**
The page is suppose to load with graphical text and image, but the backset is the page does not load properly.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Mac OS 10.11.5
- Brave Version:
  Brave: 0.11.0
  Electron: 1.2.3
  libchromiumcontent: 51.0.2704.103
  V8: 5.1.281.65
  Node.js: 6.1.0
  Update Channel: dev
  This software uses libraries from the FFmpeg project under the LGPLv2.1
- Steps to reproduce:
  1. Open Brave, type www.whereis.com and hit enter
  2. The page does not load properly.
- Screencap if needed:
  There is no screencap, the page is blank white!  If you use other web browser, the page will load wonderfully.
- Any related issues:

**Comment by putheridge** [comment]
On the end of the address bar, there are two icons, Not Allowed and Star.  Click them and change the settings to enable scripting for this site you trust.

**Comment by luixxiul** [comment]
Because this script is blocked: ``GET http://api.ems.sensis.com.au/v2/web/js/ems/?token=3501560855230602240&libraries=whereisone net::ERR_BLOCKED_BY_CLIENT``

**Comment by putheridge** [comment]
in the address bar, go to the right corner, there is a Brave icon, click on it and disable the shield.  The whereis.com should load properly.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-to-load-www-whereis-com-with-shields-enabled/10117

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
