### ISSUE TITLE
maps.google.com will not load properly

### ISSUE THREAD

**Issue by putheridge** [brave/browser-laptop#2421]
Did you search for similar issues before submitting this one?
Yes and there is no information avail.

Describe the issue you encountered:
Browsing at the maps.google.com and the content of the page does not load properly.

Expected behavior:
The page is suppose to load with graphical text and image, but the backset is the page does not load properly.

Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS 10.11.5

Brave Version:
Brave: 0.11.0
Electron: 1.2.3
libchromiumcontent: 51.0.2704.103
V8: 5.1.281.65
Node.js: 6.1.0
Update Channel: dev
This software uses libraries from the FFmpeg project under the LGPLv2.1

Steps to reproduce:
1. Open Brave, type maps.google.com and hit enter
2. The page does not load properly.

Screencap if needed:
There is no screencap, the page is blank white! If you use other web browser, the page will load wonderfully.

**Comment by putheridge** [comment]
On the end of the address bar, there are two icons, Not Allowed and Star.  Click them and change the settings to enable scripting for this site you trust.

**Comment by neeklamy** [comment]
Couple of thoughts:
- Does this URL work for you https://www.google.co.uk/maps/ ?
- Is the URL you’re using really https://maps.google.com or is it https://google.com/maps ?

I’d test the .com Google Maps, but can’t (easily) stop the redirection here in the UK.

**Comment by luixxiul** [comment]
Duping to #2341
