### ISSUE TITLE
Make Windows installer configurable not to add a rule to the firewall

### ISSUE THREAD

**Issue by pete-otaqui** [brave/browser-laptop#2422]
**Did you search for similar issues before submitting this one?**

Searched for installer issues, nothing relevant found

**Describe the issue you encountered:**

When running the windows installer, the following occurs:
- Brave is installed immediately, without any opportunity to configure or even cancel the installation
- A rule is automatically added to the firewall avoiding a user-configured option to allow network connections
- The application is installed in the user's AppData directory, with no option to install it to the Program Files directory

**Expected behavior:**

The installer should instead:
- Offer a configuration / cancellation step when first run
- Offer the option to install to Program Files instead of AppData
- Offer the option _not_ to add a rule to the firewall.
- Platform: Win7
- Brave Version: Latest as of 2016-07-06
- Steps to reproduce:
  1. Download windows installer
  2. Run installer

**Comment by SJ-Diamond** [comment]
Would love to see that happening, Brave apparently tries to gather advanced users, so it indeed makes sense to add much more features advanced users do actually expect, aka advanced customizability and configuration.

Seen from a power user point, Brave has indeed many rough edges which has to be smoothened before it really fits the needs for advanced users, but i am pretty sure the devs are aware of this.

**Comment by pete-otaqui** [comment]
Thanks for the update.  For what it's worth, here is the original report from the person to whom I recommended brave

![brave_install_report](https://cloud.githubusercontent.com/assets/132719/16658213/674d40a4-445d-11e6-9fb9-24562d08374c.jpg)

**Comment by luixxiul** [comment]
Duping to #2059. Let's concentrate on the firewall thing here.
