### ISSUE TITLE
Linux version doesn't accept Japanese input from Anthy

### ISSUE THREAD

**Issue by draconite** [brave/browser-laptop#2426]
Expected behavior:
When typing any Japanese text with Anthy, Japanese characters should be entered
- Platform:
  Linux Mint Cinnamon 18
- Brave Version:
  0.10.14
- Steps to reproduce:
  1. Follow [this guide](http://www.localizingjapan.com/blog/2014/07/29/japanese-input-on-linux-mint-17-qiana-cinnamon/) to set up Anthy if it's not set up yet: 
  2. Set IBus to Anthy, make sure Hiragana or Katakana is selected
  3. Type in any text box, either on the browser itself or one provided by a website

Sorry if I'm using incorrect terms.

**Comment by luixxiul** [comment]
Setting a milestone for now

**Comment by luixxiul** [comment]
I confired it worked on Ubuntu with ``fcitx`` and ``fcitx-anthy`` (For Japanese: 入力メソッドにfcitxを設定し、fcitx-anthyをインストールして有効にすれば動きます).
