### ISSUE TITLE
PDF.js errs when opening PDFs in new tabs

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#2427]
## Issue
When I Cmd+Click a PDF link it opens in a new tab and PDF.js fails with error "Unexpected server response".

1. Find a page which links to a PDF (e.g. https://letsencrypt.org/repository/).
1. Cmd+Click a PDF link to open in a new tab
1. PDF.js starts and fails with error "Unexpected server response (0) while retrieving PDF "{PDF url}"."

### Expected behavior
- PDF.js should load the PDF.

### etc
- After getting the error, if you refresh the page it loads ok
- Clicking PDF links normally works fine, to load in the same tab

### pic
<img width="716" alt="screen shot 2016-07-08 at 20 40 41" src="https://cloud.githubusercontent.com/assets/521861/16705861/472edb08-454c-11e6-9a8f-9a5901a848c4.png">

## Env
- Platform: Mac OS X 10.11.5
- Brave: 0.11.0 (built from master @ 6bc279)
- Electron: 1.2.3
- libchromiumcontent: 51.0.2704.103
- V8: 5.1.281.65
- Node.js: 6.1.0
- Update Channel: dev
- PDF.js v1.5.294 (build: 64a409b)

**Comment by diracdeltas** [comment]
noting that opening a pdf in a new tab via target='_blank' works fine (https://jsfiddle.net/jetjchsa/)
