### ISSUE TITLE
Cannot log in hulu.jp with facebook account

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2429]
**Describe the issue you encountered:** Cannot log in to hulu.jp with a facebook account with the bravery shield enabled. You have to disable it to log in.

**Expected behavior:** I think adding `syndication.twimg.com` to `const whitelistHosts` in https://github.com/brave/browser-laptop/blob/master/app/trackingProtection.js would avoid the issue for a moment
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.11.0
- Steps to reproduce:
  1. Go to www.hulu.jp
  2. Log in to the site with your fb account
  3. Logged out in an instant
- Screenshot if needed:
- Any related issues: https://github.com/brave/browser-laptop/commit/6edf56775f25681555fb9219b86a18e15acb73f1 #2014

cc: @diracdeltas

**Comment by diracdeltas** [comment]
if `syndication.twimg.com` solves the issue, please open a PR with it and i can merge

**Comment by luixxiul** [comment]
No it does not :-)

**Comment by luixxiul** [comment]
OK I found out how. Allowing 3rd party cookie lets you logged in. Allowing ads also lets the site display your Facebook profile thumbnail.

In case someone would tackle with this, here is another issue where 3p cookies are the cause of problem: #2533

**Comment by luixxiul** [comment]
Closing this in favor of #2965
