### ISSUE TITLE
Implement support for the Do-Not-Track header

### ISSUE THREAD

**Issue by sidstamm** [brave/browser-laptop#243]
Long shot here, and perhaps not necessary in this browser, but what about implementing DNT?

**Comment by diracdeltas** [comment]
There's been an internal discussion about this; I don't think we will turn on DNT by default until we have something like Privacy Badger that whitelists sites with an acceptable DNT policy at a .well-known URL. Optional DNT header turning-on will probably come in 0.9-ish. Open to other thoughts.

cc @BrendanEich

**Comment by sidstamm** [comment]
I am not convinced you should turn on the DNT header by default (using privacy badger may change my mind), but I do think it would be awesome to support it as an option!
