### ISSUE TITLE
Request: remove Messenger advertisement banner

### ISSUE THREAD

**Issue by dogancelik** [brave/browser-laptop#2430]
Version: Brave 0.11.0, Windows 8

If you go to [messenger.com](https://www.messenger.com/), you get this annoying banner on top of the page and there is **no way to remove it** (no time-out, no close button). Because it _really_ wants me to download Messenger app on phone which I don't want for privacy reasons.

![remove](https://cloud.githubusercontent.com/assets/486818/16709358/557e7102-4617-11e6-8457-35c588aee73f.png)

``` css
._s15 { display: none !important; }
```

The CSS above should do it.

**Comment by luixxiul** [comment]
Closing in favor of #344
