### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by jfahy** [brave/browser-laptop#2431]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**Browser will not go to requested page
jumps back to previous. It's driving me back to Chrome
**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Problem on both Windows 7 and 10
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Do you have more information? It sounds like you're typing the URL and it's auto-completing (filling in a site you don't want to visit)

**Comment by jfahy** [comment]
No, I click on a favorite site from the toolbar on top and the URL I 
want appears for a second then the previous page returns. It can take as 
many as 6-10 attempts to get to the site I want.

John


On 7/9/2016 4:00 PM, Brian Clifton wrote:
>
> Do you have more information? It sounds like you're typing the URL and 
> it's auto-completing (filling in a site you don't want to visit)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/brave/browser-laptop/issues/2431#issuecomment-231552990>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATbhn2L81lRoOq4EcR-9WhxedjTvLbZcks5qT_3lgaJpZM4JIrct>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Liunkae** [comment]
No recent reports. Closing (but please reopen if needed).
