### ISSUE TITLE
Spell check in urlbar should be disabled

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2434]
**Describe the issue you encountered:** Spell check in urlbar should be disabled.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.0

- Any related issues: #859

**Comment by bbondy** [comment]
In the Brave URL bar? Could you take a screenshot?

**Comment by luixxiul** [comment]
Ok here it is:
![](https://cloud.githubusercontent.com/assets/3362943/16714309/d11f0e10-46f9-11e6-9327-93435f800a86.jpg)

**Comment by bbondy** [comment]
wow I don't think we used to have spellcheck running in the window renderers, maybe that changed recently.  Will fix.
