### ISSUE TITLE
What's amd64-ledger-6.deb?

### ISSUE THREAD

**Issue by rahilwazir** [brave/browser-laptop#2437]
How is `amd64-ledger-6.deb` different from the `amd64.deb`?

**Did you search for similar issues before submitting this one?**
Yes

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.10.3

- Any related issues:
Curious that `amd64-ledger-6.deb` would resolve the following issue https://github.com/brave/browser-laptop/issues/1471?

**Comment by bbondy** [comment]
Avoid the -ledger-* builds for now. Thanks!  It is not a standard release and is just used for testing internally for micropayments to publishers.

**Comment by luixxiul** [comment]
@rahilwazir if you still experience the issue please update to the latest version and see what happens.
