### ISSUE TITLE
Remember monitor

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2438]
From support:

> Brave remembers the size and state of the window (maximized vs. normal) but not which monitor it was on, and also not the position on the monitor. For example, even if I keep it on my primary monitor, and size it so that it occupies the upper left quadrant of the screen. When I reopen Brave, it will be ¼ of the screen, but centered.
#2135

**Comment by cmbergin** [comment]
Same here.  I'll have Brave open on my right (secondary) monitor, then minimize.  When I click on the Brave icon in the taskbar to reopen the window, it will be on my left (primary) monitor.

**Comment by luixxiul** [comment]
Per @atherts on #4552 

> **Describe the issue you encountered:**
In Windows 10, Brave always opens in the primary monitor. Even after being moved to the second monitor, minimized, maximized and closed.
>
> **Expected behavior:**
Should open in second monitor after window is moved there.

**Comment by bsclifton** [comment]
+1 from @sirjorj via https://github.com/brave/browser-laptop/issues/14901
> ### Description
> Ever since the last update (0.23.73), launching brave will make it spawn its first window on monitor 3 on my 3-monitor LInux Mint system.
>
> ### Steps to Reproduce
>  1. Launch Brave
>  2. Mutter some unkind words
>  3. Drag window from Monitor 3 to Monitor 1 (or 2)

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/brave-always-starts-on-left-monitor/30586/2

**Comment by srirambv** [comment]
Verified this is fixed in [brave-core](https://github.com/brave/brave-core/) 😄 

Closing as wont-fix on browser-laptop
