### ISSUE TITLE
Error installing Brave with npm install HELP

### ISSUE THREAD

**Issue by helloitu** [brave/browser-laptop#244]
when i enter npm install , i get this error, please help

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dosnut/browser-laptop/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-97-generic
gyp ERR! command "/usr/local/bin/node" "/home/dosnut/browser-laptop/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dosnut/browser-laptop/node_modules/.staging/tracking-protection-0f503ffa/node_modules/hashset-cpp
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
install                   ��� ��������������������������������������������������������������������������������������������������������������������������������install ��� rollbackFailedO ��� ������������������������������������������������������������������������������������������������������������������������������install ��� rollbackFailedO ��� ������������������������������������������������������������������������������������������������������������������������������runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������npm ERR! Linux 3.2.0-97-generic
npm ERR! argv "/usr/local/bin/node" "/home/dosnut/browser-laptop/node_modules/.bin/npm" "install" "hashset-cpp"
npm ERR! node v5.5.0
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE

npm ERR! hashset-cpp@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hashset-cpp@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hashset-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hashset-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dosnut/browser-laptop/node_modules/.staging/tracking-protection-0f503ffa/npm-debug.log
preinstall:abp-filter-par ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall:abp-filter-par ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall:tracking-prote ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall                ��� ��������������������������������������������������������������������������������������������������������������������������������preinstall ��� lifecycle    ��� ������������������������������������������������������������������������������������������������������������������������������preinstall ��� unlock       ��� ������������������������������������������������������������������������������������������������������������������������������runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������brave@0.7.7 /home/dosnut/browser-laptop
��������� electron-packager@5.2.1
��� ��������� electron-download@1.4.1
���   ��������� home-path@1.0.1 
��������� electron-prebuilt@0.36.3 (git://github.com/brave/electron-prebuilt.git#11c3984ca0e0d1188827ab1e84b25ba7435e4b6c)
  ��������� electron-download@1.4.1
    ��������� home-path@1.0.1 

runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.5
runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
runTopLevelLifecycles     ��� ��������������������������������������������������������������������������������������������������������������������������������npm ERR! Linux 3.2.0-97-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! abp-filter-parser-cpp@1.0.22 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the abp-filter-parser-cpp@1.0.22 preinstall script 'npm install bloom-filter-cpp && npm install hashset-cpp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the abp-filter-parser-cpp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install bloom-filter-cpp && npm install hashset-cpp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs abp-filter-parser-cpp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls abp-filter-parser-cpp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dosnut/browser-laptop/npm-debug.log

**Comment by diracdeltas** [comment]
Same issue as #214

**Comment by bbondy** [comment]
This should work now, please post a new issue with all updated deps (node 5.9) if it's still a problem.
