### ISSUE TITLE
Evercookie

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2440]
From support (tickets/4574): http://samy.pl/evercookie/

Has this been addressed already? cc: @diracdeltas

**Comment by diracdeltas** [comment]
the demo at http://samy.pl/evercookie/ fails for me after i clear cookies in the History menu, so closing

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/2513#issuecomment-233108106

On 0.11.1 Beta1 the cookie is still found on OS X after I selected "Clear All Cookies and Site Data". Here is the STR:

1. Open the demo at http://samy.pl/evercookie/
2. Create the cookie
3. Select "Clear All Cookies and Site Data" on History menu
4. Close the tab
5. Open the demo again in a new tab

However, the cookie is gone after I both selected it and "Clear Cache". Only clearing the cache does not work either.

**Comment by diracdeltas** [comment]
> However, the cookie is gone after I both selected it and "Clear Cache".

I think that's good enough - maybe we can add a button for "Clear all".

**Comment by bbondy** [comment]
maybe clear all site data should do both, and leave the option just for cache since that's useful n its own? agree?

**Comment by bbondy** [comment]
I think if you're clearing all site data you're probably also ok with clearing cache, and maybe that's even expected.

**Comment by diracdeltas** [comment]
> maybe clear all site data should do both, and leave the option just for cache since that's useful n its own? agree?

yup
