### ISSUE TITLE
Detect when not to show save password bar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2443]
It would be great if we didn't show the save password bar for wrong passwords.

I think this would work by detecting which fields you put a username and password in, and if the next page load does not have these fields again, then show the permission prompt.

cc @diracdeltas

**Comment by diracdeltas** [comment]
That's a good idea. Right now the last password save prompt replaces older ones, so as long as you click 'save' on the last one, it will save the right password.
