### ISSUE TITLE
https://www.costcotravel.com/ shows blank page

### ISSUE THREAD

**Issue by tcr** [brave/browser-laptop#2448]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
https://www.costcotravel.com/ shows a blank page (after a redirect from http://costcotravel.com/ and going there directly)

**Expected behavior:**
Page is not blank.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS 10.11.5

- Brave Version: 0.11.0dev

- Steps to reproduce:
    1. Go to https://www.costcotravel.com/
    2. See blank page

- Screenshot if needed: 
![screen shot 2016-07-11 at 12 25 27 pm](https://cloud.githubusercontent.com/assets/80639/16738176/96da594e-4762-11e6-844c-d71a5cee3111.png)

- Any related issues: None

**Comment by luixxiul** [comment]
I think the site is down. Please try again with another browser.

**Comment by neeklamy** [comment]
I’m *was* seeing the exact same thing, the website displays perfectly in Google Chrome, Safari, and Firefox (all latest versions).

I tried with shields down, and separately allowing adverts, tracking, all cookies, even phishing and malware. Nothing.

I tried relaunching Brave, still the same thing.

Strangely, no real URLs would load up anything at all (as seen in the dev tools), but going to a 404 page would load some content:

![blank website costcotravel.com](https://cloud.githubusercontent.com/assets/155358/16740957/34043d44-4799-11e6-913a-a1530d0ef8b5.png)

Now the weird thing is, I tried relaunching Brave again, and the site just works…

**Comment by tcr** [comment]
Ah, yeah, I neglected to mention that Safari works fine on my machine.

I dug into it. Apologies this isn't cURL but if I reproduce Brave's request using httpie:

```
http https://www.costcotravel.com/ \
'Host: www.costcotravel.com' \
'Connection: keep-alive' \
'Cache-Control: max-age=0' \
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
'Accept-Encoding: gzip, deflate' \
'Accept-Language: en' \
'Cookie: JSESSIONID=3676B4F5286E3FE4C0D09C8932B4CC5B; BIGipServerpool-prod-app=!HJjoOphKEqTxjBDCd3dqWKLWYEL+b50QAj/n/RDMfLdv+EJhB19b302uDPx0o5LVB5SH/J0fhf6goA==' \
'Upgrade-Insecure-Requests: 1' \
'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
```

**Fix:** Removing the `Accept-Language: en` header returns the non-blank page. I believe Safari doesn't send this header. I'm not sure what the implications are here for not sending it.

**Comment by neeklamy** [comment]
And it works equally well if you send `Accept-Language: en-gb` or even `Accept-Language: ab-cd`.

My installations of Safari and Safari Technology Preview both send `en-us`, but plain ol’ `en` is a [valid language identification code](http://www.metamodpro.com/browser-language-codes).

**Comment by luixxiul** [comment]
On Google Chrome Canary the page is not displayed.

**Comment by tcr** [comment]
Seems like a problem for the website administrator then. Thanks for your help!
