### ISSUE TITLE
"Pepper Flash"?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2449]
**Describe the issue you encountered:** Why "Pepper Flash", not "Adobe Flash" [here](https://github.com/brave/browser-laptop/blob/06a2aa180a54bc4dabafd201203dd75b8748c9f8/app/extensions/brave/locales/en-US/preferences.properties#L46)? I think It is confusing. I got the question from support.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.0

- Screenshot if needed:

- Any related issues:

**Comment by tcr** [comment]
To add to this (macOS 10.11.5 brave 0.11.0dev) the Adobe link lacks a space before it, and clicking it does nothing:

![image](https://cloud.githubusercontent.com/assets/80639/16741532/a9a1ee16-4771-11e6-8641-c477495f60b3.png)

**Comment by diracdeltas** [comment]
mostly to clarify that standard Adobe Flash will not work in Brave. Pepper is maintained by Google.

**Comment by diracdeltas** [comment]
@tcr noted; it works and looks okay on master now

**Comment by luixxiul** [comment]
If clicking works on master then it should be ok. Closing.
