### ISSUE TITLE
google news does not display pictures and you cannot open google apps -- News from google home page.

### ISSUE THREAD

**Issue by vivektaparia** [brave/browser-laptop#2451]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
When you open google News in brave most of the images on the page are not displayed.

**Expected behavior:**
All images required should be displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10

- Brave Version:
0.11.0

- Steps to reproduce:
    1. Open Google home page in Brave
    2. try clicking google apps - nothing works 
    3. Type google news and open google news page
    4. Most of the images are not displayed.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/20412938/16756091/48b0d07c-4820-11e6-967d-8ceb497e07fa.png)

- Any related issues:

**Comment by luixxiul** [comment]
Please enable scripts and try again.

**Comment by vivektaparia** [comment]
Yes it woks now, closing the issue.
