### ISSUE TITLE
data file download race condition

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2455]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If a new data file is available (either first run or file updated), https everywhere, tracking protection and ad blocking will be disabled until they are loaded, but they appear as "on" in the bravery panel. There are a few ways we can handle this:
1. Leave as-is, but notify the user that shields are down until the file is downloaded
2. Delay the loading of any pages until the files are downloaded and notify the user of the download progress

When updates are available we should also start immediately with the old files and swap when the new ones are available.

**Comment by bridiver** [comment]
if we want to be completely sure they are loaded, we could also apply this to locally read files

**Comment by diracdeltas** [comment]
I'm in favor of 1 since 2 will always make us look slow whenever there's an update

**Comment by bbondy** [comment]
Strong preferences for #1 over #2.

**Comment by bridiver** [comment]
actually there is a 3rd option which is to download the files on install

**Comment by bridiver** [comment]
cc @bradleyrichter

**Comment by BrendanEich** [comment]
Download on install == win/win, is it hard?

**Comment by diracdeltas** [comment]
Even if they are downloaded on install, we need to check for updates every ~24 hours so I don't think that solves the problem

**Comment by diracdeltas** [comment]
NVM, I forgot that the old file will be active while the update is being downloaded, so that does seem like a win win

**Comment by bridiver** [comment]
once we have a file, we can use the local file until a new file is downloaded

**Comment by bbondy** [comment]
download on install is not possible when you have no running code on install.  Only Windows has this.

**Comment by bridiver** [comment]
There are hooks available on Mac when you copy to and delete from /Applications and on Linux a deb or similar can run code

**Comment by bbondy** [comment]
This is very platform dependent though and moves the implementation to something that locks us into the way we are distributing. Longer term I think we'll end up in the mac store for example. Also we could change installers completely to be only msi based on day.

**Comment by bradleyrichter** [comment]
#1 is my pref. 

We can show the shields button as disabled and display a "please wait while shields are being updated. "
