### ISSUE TITLE
The UI should allow for advanced customization

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#246]
The concept of Brave looks like it will be a real browser for power users again. Would be nice to have advanced customization features aka a full status bar or being able to combine urlbar elements with the tabs if possible, or more advanced elements movement in the UI.

Thanks for considering :)

**Comment by diracdeltas** [comment]
This is a pretty cool idea for post-1.0. The browser UI is completely written in HTML/CSS/JS, so it makes sense for us to be the https://atom.io/ of browsers in terms of core customizability.

**Comment by SJ-Diamond** [comment]
Just take a look at Firefox version 22 (outdated, but had many interesting features loved by power users) or Vivaldi Browser - Blink engine is able to support tons of features and speed, so i really hope you are making use of that opportunity and not just plan to create another simple browser for the masses, but as Brendan Eich is founder of Brave, i guess you have anyway more higher goals for your browser than other projects :)

**Comment by Arandhras** [comment]
This would be definitely something that I would love. I miss the hackability of "old" Firefox releases in terms of UI customization, and being able to achieve that again would be fantastic!

**Comment by bsclifton** [comment]
Per https://github.com/brave/browser-laptop/issues/5683, we should allow for folks to modify:
- the size of tabs
- fonts used in the tabs

**Comment by alexwykoff** [comment]
lots of +1's from community on this

**Comment by Indyandie** [comment]
Would be great to have something similar to Atom. Have a tidy doc that you can just edit.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/774
