### ISSUE TITLE
Allow showing a list of registered protocols and allow to remove protocol handlers

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2461]
Currently the only UI we have for protocols is if you remember that a site is allowed to register protocols.  We should also have the ability to see what the registered handlers are for a site and allow to unregister it from our chrome UI.

**Comment by bbondy** [comment]
cc @mrose17

**Comment by bsclifton** [comment]
Fixed with brave-core; this should be available at chrome://settings/handlers
