### ISSUE TITLE
How to let users realize the issue can be solved by allowing scripts

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2464]
**Describe the issue you encountered:**
From support:

> Fox News pictures in lower part of website won't open, even if I click on 
> them in any manner.
> 
> www.foxnews.com

The issue was solved by allowing scripts, and I am just wondering if there is a way of letting users realize by themselves that it can be solved by doing so. Indicating blocked elements with colored borders, for example.
- Screenshot if needed:
  ![](https://cloud.githubusercontent.com/assets/3362943/16796456/ddfd2b00-491d-11e6-9993-2730146befaf.jpg)
- Any related issues: #2482

**Comment by bbondy** [comment]
we can probably find ways to improve but it won't be fully solvable. Cosmetic filters would probably clear this out so you wouldn't realize there was missing pictures.

**Comment by bbondy** [comment]
There can be for example a script that finds DOM elements and appends stuff to it, but if the script is blocked we have no access to know what it does.

**Comment by diracdeltas** [comment]
noscript "solves" this by making a very obvious notification bar that shows the scripts blocked. i am not a huge fan of this

**Comment by luixxiul** [comment]
Me neither, but the current version seems to me a little too silent.

**Comment by luixxiul** [comment]
From support:
> http://www.charismanews.com/politics/elections/58244-donald-trump-says-hillary-clinton-demonstrated-bad-judgment

![](https://cloud.githubusercontent.com/assets/3362943/16881959/9bc15e9c-4af7-11e6-93af-1bd06c5c69f9.jpg)

**Comment by luixxiul** [comment]
I'm going to close this in favor of https://github.com/brave/browser-laptop/issues/3732.
