### ISSUE TITLE
“Switch to new tabs immediately” for tabs created by middle-clicking on a bookmark

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2465]
**Describe the issue you encountered:** 
From support:

> The “Switch to new tabs immediately” preference does not work.
> 
> I just found that this still doesn’t work for tabs created by middle-clicking on a bookmark on the bookmark bar.

**Expected behavior:** The preference should be applied to these tabs too.
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1. Bookmark a page 
  2. Make “Switch to new tabs immediately” preference on
  3. Middle-click it
- Any related issues: #217

**Comment by bsclifton** [comment]
This is working great now 😄 👍
