### ISSUE TITLE
Print this PDF in Brave for Windows 

### ISSUE THREAD

**Issue by MerMan02** [brave/browser-laptop#2466]
**Did you search for similar issues before submitting this one?** yes

**Describe the issue you encountered:**
Hi. Is there a way to add a Print to PDF option for the Brave Browser in Windows 7 or 10? Thanks!

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #1616
