### ISSUE TITLE
Responding to prompt for mail.google.com to show notifications or not causes browser crash.

### ISSUE THREAD

**Issue by jnpstn** [brave/browser-laptop#2467]
**Did you search for similar issues before submitting this one?**
Yes, but the search mechanism seems to search content of issues, not titles (not helpful)

**Describe the issue you encountered:**
While using GMAIL, Brave asks in the top bar "Allow mail.google.com to show you notifications?".  Pressing ALLOW or DENY at the far right causes immediate browser crash.

**Expected behavior:**
Browser stays open with setting / option saved.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS El Cap 10.11.5

- Brave Version:
Latest available - 0.11.0 Electron 1.2.3

- Steps to reproduce:
    1. Open GMAIL
    2. Wait for toolbar prompt
    3. Press response / button

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
cc @bridiver I think this was fixed but not released yet for 0.11.1. CC'ing in case it should already be in there, I don't recall.

**Comment by jnpstn** [comment]
​I was just able to confirm I could press DENY, and it didn't crash.
Subsequently, ALLOW did work.  I am attempting to re-test the theory, as I
have no explanation for my findings thus far.​

On Wed, Jul 13, 2016 at 4:37 PM, Brian R. Bondy [Masked] <
FWD-737QTYSMENAIYCQANIQDDYDWEFMCUYBHABGACOAI5BAIM3JXEIQBGIIGSADIAXWSAGWGJLCZNQAVAL4AE5NAPTJDUEV24WJIFYSDROK57AMDISD3JO5FXKZ2MRU32ONTHBIQHLLJNRISSQBBFBUCQIDUEFTCCFRAFYQBMIJO7BLDQA7YAL4ADEZTWAE7CKIMMRAAAIAAEA======@opayq.com
> wrote:

> Preview: cc @bridiver I think this was fixed but not released yet for
> This email is forwarded from a MASKED EMAIL you created using DoNotTrackMe
> <https://dnt.abine.com/help>.
> IF THIS IS SPAM, CLICK HERE TO BLOCK.
> <https://dnt.abine.com/#/block_email/bedf8526@opayq.com/FWD-737QTYSMENAIYCQANIQDDYDWEFMCUYBHABGACOAI5BAIM3JXEIQBGIIGSADIAXWSAGWGJLCZNQAVAL4AE5NAPTJDUEV24WJIFYSDROK57AMDISD3JO5FXKZ2MRU32ONTHBIQHLLJNRISSQBBFBUCQIDUEFTCCFRAFYQBMIJO7BLDQA7YAL4ADEZTWAE7CKIMMRAAAIAAEA======@opayq.com>
>
> Want to shop safely and privately online? Get DoNotTrackMe Premium
> <https://dnt.abine.com/#premium>.
>
> cc @bridiver <https://github.com/bridiver> I think this was fixed but not
> released yet for 0.11.1. CC'ing in case it should already be in there, I
> don't recall.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/brave/browser-laptop/issues/2467#issuecomment-232479010>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHZYS0ta3uvlspkt3DeT2NZxhnxSe0j7ks5qVUx0gaJpZM4JLfE4>
> .
>



-- 

========================================
Tel / SMS:               704/360-0566
G-Hangout/Skype:  jon.e.epstein
WhatsApp:              { ask }
========================================

**Comment by bbondy** [comment]
I think it'll be fixed in 0.11.1, but please try when that build is avail.

**Comment by bridiver** [comment]
we have seen reports of intermittent crashes on macOS and when I found the problem in Linux I was surprised that we weren't seeing it on mac as well. I think you might have just been extremely unlucky and hit the intermittent crash more often. I'm going to close this for now because it's very likely the issue that we fixed in 0.11.1, but please report back if you still see it. Thanks!
