### ISSUE TITLE
Support 32-bit linux

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2468]
From support (tickets/4470)

Is it already possible to build the app on 32 bit Linux?

- Any related issues: #397 https://github.com/brave/browser-laptop/pull/10514#issuecomment-322642404

**Comment by bbondy** [comment]
we're just waiting for some build automation for this.

**Comment by bsclifton** [comment]
+1 from support
https://linkbubble.zendesk.com/agent/tickets/6655

**Comment by Liunkae** [comment]
Related: #235 (make builds for 32-bit Linux)

**Comment by posix4e** [comment]
yarr we can print these

**Comment by posix4e** [comment]
I have uploaded a 32 bit preview appimage to my personal bucket
http://storage.googleapis.com/posis-brave-mirror/

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by ariSunz** [comment]
Any updates on this?

**Comment by posix4e** [comment]
@ariSunz Sure did you see our preview?

**Comment by ariSunz** [comment]
You mean your last comment? I only see an XML document and I have no idea of what to do with it. Sorry for my ignorance. Also, I'd rather avoid any services related to Google...

**Comment by posix4e** [comment]
@ariSunz  you should be able to look at the document and tell the filenames. For instance
http://storage.googleapis.com/posis-brave-mirror/brave-0.20.0-i386.AppImage

**Comment by bsclifton** [comment]
Closing as `wontfix`. If you think this should be implemented when we move to Brave Core, please feel free to open an issue there:
https://github.com/brave/brave-browser/issues
