### ISSUE TITLE
security settings panel: clear browsing data now button

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2471]
Browsing data can be cleared immediately (vs automatically on browser close) by using the "Clear Browsing Data Now..." button.

A modal (to the page) dialog opens and provides the same switches for a batch clearing action.

The button action can be canceled if desired. (for users who are only exploring the functionality)

![image](https://cloud.githubusercontent.com/assets/13509546/16809161/d75d76ee-48e4-11e6-8beb-2a7c5d329e45.png)

**Comment by Liunkae** [comment]
Could this option also be added to the hamburger menu for easy access? Similar to Firefox's Forget button.

**Comment by bbondy** [comment]
@Liunkae pls post a separate issue for that, thanks.
