### ISSUE TITLE
security settings panel: clear browsing data

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2472]
**Note: This issue replaces #1413.**

Browsing data can be cleared automatically on browser close by toggling the desired switches in the list. (all off by default)

Mockup image with this issue's items indicated in blue rectangle.
![image](https://cloud.githubusercontent.com/assets/13509546/16809620/9815a84c-48e6-11e6-9180-b1105fffd096.png)

(note: individual cookie deletion will be described in a separate issue)

**Comment by bradleyrichter** [comment]
cc @diracdeltas

**Comment by bbondy** [comment]
Fixed by:
https://github.com/brave/browser-laptop/commit/d6335d36cf27003ef8b8baa72cbe24ebd01366d1
https://github.com/brave/browser-laptop/commit/851bfe9a82862cd64a5707f6f67bf2db84ed02cc
https://github.com/brave/browser-laptop/commit/7fea2115693a96357e734eeb8df8bbd913a3b37e
