### ISSUE TITLE
Two-finger swipe gesture on macOS should have visual indicator

### ISSUE THREAD

**Issue by tcr** [brave/browser-laptop#2477]
**Describe the issue you encountered:** The two-finger swipe gesture on macOS has no visual indication as you perform the swipe of whether it is activated (or will succeed). This may be intended but feels nonintuitive.

**Expected behavior:** Chrome has a visual arrow on the sides that appears as you swipe. Safari has a "page sliding" animation to indicate a swipe. Because Brave's swipe is calculated by velocity, a different type of indicator may be needed.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.0dev
- Steps to reproduce:
  1. Open any page with a back history.
  2. Perform a two-finger swipe backward.
  3. See no visual changes.

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6131

**Comment by ksmithut** [comment]
Along these lines, is there a way to disable swipe navigation altogether? I have disabled it in my system settings but Brave seems to be the only one that doesn't respect that setting.

**Comment by Liunkae** [comment]
@ksmithut We have an issue for that: #5907.

**Comment by alexwykoff** [comment]
+1 from support

**Comment by NejcZdovc** [comment]
Fixed by #9617

**Comment by LaurenWags** [comment]
@darkdh @NejcZdovc I'm seeing the back/forward arrows get larger when swiping up/down on a page, this this expected? cc @kjozwiak 

![swipe](https://user-images.githubusercontent.com/28145373/34056153-eb969afa-e19f-11e7-9e6a-380e4580a529.gif)

**Comment by darkdh** [comment]
Because you can't have 0 x-axis changes when you do vertical scroll. You will always have slightly horizontal movement which will be reflected onto the animation.
