### ISSUE TITLE
Two-finger swipe gesture should calculate velocity based on last finger movement, not time until release

### ISSUE THREAD

**Issue by tcr** [brave/browser-laptop#2478]
**Describe the issue you encountered:** I use two finger swipe exclusively for changing pages, but it fails often for me. I believe this has to do with how velocity is calculated: when I perform the gesture and but my fingers "rest" for a moment on the touchpad before releasing, it fails.

**Expected behavior:** A swipe is considered successful when it surpasses the correct velocity, even if fingers rest on the touchpad for a moment afterward.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.0dev

- Steps to reproduce:
    1. Swipe quickly with two fingers to go back.
    2. Rest your fingers on the trackpad for a moment without movement (using a particularly sloppy gesture angle like I do makes this easy)
    3. See it fail to succeed.

**Comment by tcr** [comment]
My proposed change calculates velocity per wheel click, not by time to release: https://github.com/tcr/browser-laptop/commit/6b7653689966849941f3ad899396a3a44a2412a5

I can make a PR for this if the proposal is worthwhile.

**Comment by diracdeltas** [comment]
yup we would take a pr for this
