### ISSUE TITLE
flash placeholder regression

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2489]
https://github.com/brave/browser-laptop/issues/2480#issuecomment-232827642

**Comment by diracdeltas** [comment]
@bbondy it appears that `chrome.ipc` in app/extensions/brave/js/about.js is undefined when the `about-flash.html` is in an iframe instead of top-level

**Comment by bbondy** [comment]
cc @bridiver can you fix this at the electron level?
Otherwise I'll have to revert the flash part of: https://github.com/brave/browser-laptop/commit/6d27a69a84c55a54d9f5e5ad4f1bdbdff677a3d8

**Comment by bridiver** [comment]
do you have an example site? It should be defined if it's still an extension url

**Comment by diracdeltas** [comment]
@bridiver http://www.y8.com/games/superfighters

**Comment by bridiver** [comment]
we should add a test for this in browser

**Comment by diracdeltas** [comment]
thanks, will do

**Comment by diracdeltas** [comment]
i'm still seeing this with the latest rc / latest electron release so reopening. test page http://www.y8.com/games/superfighters
