### ISSUE TITLE
FR: Ubuntu/Debian Linux .deb installation?

### ISSUE THREAD

**Issue by craft37** [brave/browser-laptop#249]
Could you make possible to install Brave browser on Ubuntu easier way?
Thanks!

**Comment by diracdeltas** [comment]
I think at least a dozen people have asked me this via Twitter/etc. cc @bbondy for thoughts on when we should have linux packages available.

**Comment by bbondy** [comment]
And lots in support, I think the main blocker here is to make it easy to produce lots of electron-prebuilt binaries for brave/electron for the same platforms as atom/electron has.  Maybe via Dockerfiles? See also https://github.com/brave/browser-laptop/issues/235

**Comment by PFCKrutonium** [comment]
I would love to see an arch AUR solution as well.

**Comment by ritesh-pandey** [comment]
Brave build successful.
`npm start` gives following error

> brave@0.7.12 start /home/ritesh/github/browser-laptop
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck

electron "/home/ritesh/github/browser-laptop" --debug=5858
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/ritesh/github/browser-laptop/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/ritesh/github/browser-laptop/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

**Comment by egorse** [comment]
+1

**Comment by 0x20c24** [comment]
+1

**Comment by stealson** [comment]
+1

**Comment by bbondy** [comment]
would accept patches.

**Comment by 0x20c24** [comment]
made some time to 'debugging' this issue.

"npm install electron-prebuilt --save-dev  " solved this issue, then i got an error message that tracking-protection module is missing.

"npm install tracking-protection " has the following problem:

gyp: node_modules/hashset-cpp/binding.gyp not found (cwd: ~/brave/brow
ser-laptop/node_modules/tracking-protection)

"npm install tracking-protection --unsafe-perm " solved the issue, then got another error message that sqlite3 is missing.
"npm install sqlite3 --unsafe-perm " solved that issue.

Hope this helps.

**Comment by diracdeltas** [comment]
FWIW, we no longer require sqlite3

**Comment by ivory4491** [comment]
+1

**Comment by bbondy** [comment]
You can download a 0.8.2 Debian package here:
https://laptop-updates.brave.com/latest/debian64

You can install it on Debian and Ubuntu with:
`sudo dpkg -i dist/brave_0.8.2_amd64.deb`

You can start it with:
`brave`

Package info:
```
 new debian package, version 2.0.
 size 49944830 bytes: control archive=458 bytes.
     519 bytes,    13 lines      control              
 Package: brave
 Version: 0.8.2-1
 Section: web
 Priority: optional
 Architecture: amd64
 Depends: git, gconf2, gconf-service, gvfs-bin, libc6, libcap2, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libnss3, libxtst6, python, xdg-utils
 Recommends: lsb-release
 Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0
 Installed-Size: 250500
 Maintainer: Brave Developers <support@brave.com>
 Homepage: https://www.brave.com/
 Description: Brave laptop and desktop browser
  Brave laptop and desktop browser
```

**Comment by ChristopheLux** [comment]
Working like a charm Kubuntu 15.10 Thanks
