### ISSUE TITLE
Add notification bar machinery for "Add Funds"

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#2490]
at present, the browser presents a notification bar when an update is available, and allows the user to either update (if available) or dismiss.

generalize this functionality to allow the ledger client code to remind the user that it's time to add funds to their bitcoin wallet.

(related: #2407)

**Comment by bridiver** [comment]
can we setup an auto-payment? You can create a new notification with `appActions.showMessageBox`

**Comment by mrose17** [comment]
@bridiver - i'm talking with someone about auto-payments? they have to be done consumer-side (obviously), so it will end up being a function of the wallet provider for the consumer...

**Comment by diracdeltas** [comment]
how is this issue different from #2407?

**Comment by diracdeltas** [comment]
`appActions.showMessageBox` will show a general-purpose notification bar, but it needs some CSS help in order to look the same as the update bar (which is not general-purpose yet)

**Comment by diracdeltas** [comment]
closing this since it's doable with `appActions.showMessageBox` already

**Comment by mrose17** [comment]
@bradleyrichter - could you determine rule that we should use in terms of putting up the notification for the user? cc: @diracdeltas, @mrose17
