### ISSUE TITLE
Clicking the green "Close" button in the payment modal should also close the Brave "Add Funds" pop-up

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#2491]
when the user clicks on "Add Funds" a modal window appears. if the user clicks on "Buy with Coinbase", the coinbase buy widget is populated. when that process is complete and the buy widget is dismissed, the underlying modal window should also be closed.

![1](https://cloud.githubusercontent.com/assets/400552/16860107/c04d9c26-49e9-11e6-892b-0c3ff13b0d8c.png)

**Comment by diracdeltas** [comment]
fixed in 4bd5993c5202b2a6b25b317d5dbcd8acf66b2080
