### ISSUE TITLE
Find and fix performance issues with about:preferences#publishers

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#2492]
the communications path for `LEDGER_GENERAL_COMMUNICATION` occurs **a lot**. figure out why and make it happen only when needed.

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-laptop/commit/e1efb66bbc3ba3d436da4d8d16e05e2a47c3fe98 gets rid of LEDGER_GENERAL_COMMUNICATION
