### ISSUE TITLE
Write the "Welcome screen" text for the "Payments" pane

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#2494]
for the ledger beta integration, the user is given the option to enable the ledger. until the user says "Go!", the "Payments" pane should contain useful text explaining what the beta is all about.

please write this text!

**Comment by mrose17** [comment]
some things we definitely need:

1. explain that the "Add Funds" button doesn't show up _immediately_, but that the initialization process is staged over several hours ("unpredictably" delays are introduced) in order to make it harder for third-parties and Brave Software's servers to correlate the creation of your Brave wallet with your online presence.

2. explain that the list of publishers is built dynamically based on your browsing habits, and that while it represents up to the last 30 days of browsing, when you start, there may not be a lot of data to start with.

**Comment by bradleyrichter** [comment]
DRAFT screen:

![image](https://cloud.githubusercontent.com/assets/13509546/17160975/38ddda3e-535e-11e6-8d9c-30f153d32836.png)
