### ISSUE TITLE
Portable version or start browser in non privileged mode

### ISSUE THREAD

**Issue by stanleyxu2005** [brave/browser-laptop#2498]
I installed the browser as an admin. When I logged in Windows as a normal user, I cannot use Brave anymore. It will crash and exit without any error message. I'd like to know, how to start Brave in non-privileged mode.

**Comment by SJ-Diamond** [comment]
Portable version would be great.

**Comment by stanleyxu2005** [comment]
Some more details:
1. I login in Windows as a normal user and install Brave
2. I logout and then login as admin, and see Brave has an update, so I clicked the "Upgrade" button.
3. I logout and then login as normal user, start Brave will fail.

**Comment by stanleyxu2005** [comment]
Looks fixed

**Comment by bsclifton** [comment]
@stanleyxu2005 thanks for the update :smile: Glad to hear the steps you outlined above are working now.

I'm going to rename this issue (for future reference).  The issue tracking a portable version can be found here:
https://github.com/brave/browser-laptop/issues/2953
