### ISSUE TITLE
Changing language settings is not affecting immediately

### ISSUE THREAD

**Issue by Tanvir-rahman** [brave/browser-laptop#2500]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Changing language settings is not showing any immediate effect.

**Expected behavior:** A notification should be shown to user that, "A changes have been made.You need to restart to apply the change."Because,without any notification it is not possible for new user to understand the matter.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10

- Brave Version: 0.11.0 dev

- Steps to reproduce:
    1.Open Brave browser
    2.Go to Preferences from Menu
    3.From Language option,select a Language

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #1705
