### ISSUE TITLE
Add Widevine plugin google

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2501]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 But I intend to immigrate to Linux Debian..
- Brave Version:
0.11.0 dev
- Steps to reproduce:
    1.For example I enter the Netflix site...
    2.When I try to watch a movie I can not for lack of component.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #468
