### ISSUE TITLE
Build fails on Windows 10 x64 unable to download electron-v0.36.3-win32-ia32.zip

### ISSUE THREAD

**Issue by SavageCore** [brave/browser-laptop#251]
$ npm install

> electron-prebuilt@0.36.3 postinstall C:\Brave\browser-laptop\node_modules\electron-prebuilt
> node install.js

Downloading electron-v0.36.3-win32-ia32.zip
Error: GET http://brave.github.io/browser-laptop-releases/0.36.3/electron-v0.36.3-win32-ia32.zip returned 404

C:\Brave\browser-laptop\node_modules\electron-prebuilt\install.js:22
  throw err
  ^
 Error: GET http://brave.github.io/browser-laptop-releases/0.36.3/electron-v0.36.3-win32-ia32.zip returned 404
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.5
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev5.5.0\\node.exe" "c:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\cli.js" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [C:\Brave\browser-laptop\npm-debug.log](http://pastebin.com/WQnWRs80)

**Comment by PFCKrutonium** [comment]
Gotta love how that log file doesn't exist afaik.

**Comment by PFCKrutonium** [comment]
That file doesn't seem to exist any more, but I can't seem to find the package to patch it to use a different download :/

**Comment by an-water** [comment]
Have you tried making sure you're on node 5.5.0, removing the `node_modules` folder and running `npm install` again? ref: #221 #230

**Comment by PFCKrutonium** [comment]
How can I check the version of node I have installed?

**Comment by PFCKrutonium** [comment]
Stupid Question, I am using https://nodejs.org/dist/v5.5.0/node-v5.5.0-x86.msi so 5.5.0 ofc.

**Comment by an-water** [comment]
for future reference it's `node -v`. it's also in your error log output that i should have skimmed a little harder. :) 

did you delete / reinstall?

**Comment by PFCKrutonium** [comment]
npm install is running right now, yes.

**Comment by PFCKrutonium** [comment]
```
> electron-prebuilt@0.36.3 postinstall C:\Users\pfckr\Desktop\brave\browser-laptop\node_modules\electron-prebuilt
> node install.js

Downloading electron-v0.36.3-win32-ia32.zip
Error: GET http://brave.github.io/browser-laptop-releases/0.36.3/electron-v0.36.3-win32-ia32.zip returned 404

C:\Users\pfckr\Desktop\brave\browser-laptop\node_modules\electron-prebuilt\install.js:22
  throw err
  ^
 Error: GET http://brave.github.io/browser-laptop-releases/0.36.3/electron-v0.36.3-win32-ia32.zip returned 404
brave@0.7.7 C:\Users\pfckr\Desktop\brave\browser-laptop
```
-snip of map of the npm_module folder, quite large...-

```
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\electron-rebuild\node_modules\npm\node_modules\glob with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled node_modules\electron-rebuild\node_modules\npm\node_modules\rimraf with new installed version
npm ERR! Windows_NT 10.0.11102
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pfckr\Desktop\brave\browser-laptop\npm-debug.log
```

**Comment by PFCKrutonium** [comment]
[npm-debug.txt](https://github.com/brave/browser-laptop/files/101298/npm-debug.txt)

**Comment by SavageCore** [comment]
No change after removing `node_modules` and re running `npm install`
`node -v: v5.5.0`

**Comment by PFCKrutonium** [comment]
The problem here is literally that it is trying to download a file that does not exist - I checked, it does not exist.

**Comment by SavageCore** [comment]
Correct.

**Comment by PFCKrutonium** [comment]
I can't figure out where it is requesting the file from in the file yet, but a valid download for it is https://github.com/atom/electron/releases/download/v0.36.3/electron-v0.36.3-win32-ia32.zip

**Comment by bbondy** [comment]
We aren't producing x86 builds yet to reduce overhead and testing, only x64.
We can leave this open though for when we do.

**Comment by bbondy** [comment]
Actually I see you are meaning to use x64, you just need to have your env setup for x64 building and not x86 building. 

I suggest to use the mozilla-build package. You can get it at https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe

After you do that start the script:
"C:\mozilla-build\start-shell-msvc2013-x64.bat"
or 
"C:\mozilla-build\start-shell-msvc2015-x64.bat"

Depending on which one you have installed.

**Comment by SavageCore** [comment]
Thanks, bbondy. I actually solved my issue by completely removing nodist and install latest node 5.5.0 offical package.

**Comment by bbondy** [comment]
Great I'll close this.

**Comment by PFCKrutonium** [comment]
Question, what is nodist?
