### ISSUE TITLE
Private and Session Tab title change suggestion

### ISSUE THREAD

**Issue by Tanvir-rahman** [brave/browser-laptop#2512]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Private tab title is showing "about:newtab" and Session tab title is showing "New Tab"

**Expected behavior:** Suggestion for Private Tab title: "Private Tab"
                                     Suggestion for Session Tab title: "Session Tab"
When opening these tabs a documentation/popup about their usage, will help user to understand how it works.
  
- Platform (Win7, 8, 10? macOS? Linux distro?): Win10

- Brave Version: 0.11.0

- Steps to reproduce:
    1.Open brave browser.
    2.From Menu Open "New Private Tab" and "New Session Tab"

**Comment by bsclifton** [comment]
Digging in on this.  `page-title-updated` is not getting fired for some reason...

**Comment by bsclifton** [comment]
Finally had a chance to look at this :smile: 

I think the root cause is that you can't load about pages in private tabs (and by default, it tries to load about:newtab). Will continue looking into this

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/1817
