### ISSUE TITLE
Cookies seem to be getting lost when upgrading to 0.11.1dev-beta1

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2523]

**Comment by bbondy** [comment]
I haven't been able to reproduce this at all @diracdeltas, any ideas?

**Comment by diracdeltas** [comment]
i only lost cookies on Gmail and Twitter only when upgrading to 0.11.1dev-beta1; other sites were still logged in. maybe those sites invalidate cookies when UA string changes?

**Comment by bbondy** [comment]
not sure but I went to 0.11.0 and logged into gmail, then upgraded to 0.11.1 and didn't reproduce. 
I also tried with cleared session storage so I'm not sure what's up.

Which change changed the UA string?

**Comment by diracdeltas** [comment]
wasn't sure if there was a chromium upgrade in this release

**Comment by bbondy** [comment]
nope

**Comment by bbondy** [comment]
would be worth you trying to use 0.11.0 and then upgrade to 0.11.1 by installing on top to see if it happens again if you don't mind.

**Comment by bbondy** [comment]
@luixxiul you haven't seen anything like this? I think we will remove it from this milestone because I can't seem to reproduce. It might be an unrelated random bug that happens sometimes with cookies in electron.

**Comment by luixxiul** [comment]
No I haven't. I'll keep an eye on it anyway.

**Comment by diracdeltas** [comment]
I just updated to the 0.11.1 release from 0.11.0 and it didn't happen this time. can be closed?

**Comment by bbondy** [comment]
yep let's post another if we see it.
