### ISSUE TITLE
"Add new tab" sign position

### ISSUE THREAD

**Issue by Tanvir-rahman** [brave/browser-laptop#2525]
**Did you search for similar issues before submitting this one?** Yes.

**Expected behavior:** Sign of Add new tab (" + ")  should be in middle.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win10

- Brave Version: 0.11.1

- Steps to reproduce:
    1.Open Brave browser
    2.Notice the Add new tab sign

- Screenshot if needed:
![capture2](https://cloud.githubusercontent.com/assets/15964566/16897006/80c455de-4bc6-11e6-84b7-e9849503910b.PNG)

**Comment by luixxiul** [comment]
Duping to #1863
