### ISSUE TITLE
Browsing history is not cleared for saved and restored tabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2528]
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/2513#issuecomment-233108106
I checked the Private Data options, but browsing history is not cleared when I have selected "my windows/tabs from last time" in the option of "Brave start with".

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Steps to reproduce:
    1. Select "my windows/tabs from last time" on about:preferences
    1. Open a URL in a tab
    2. Check Private Data options on about:preferences#security
    3. Restart Brave

Setting a milestone for now.

**Comment by bbondy** [comment]
I think this is working like it should. CC @diracdeltas to see what she thinks.
I don't think any of these: Browsing history, download history, cached images and files, all site cookies are for opened tabs.  

I could kind of see how Browsing history could be considered opened frames, but I think it's easy enough to discover the other option when you see tabs restored.

**Comment by diracdeltas** [comment]
i think if "my windows/tabs from last time" is the value of "Brave start with" and all data is supposed to be cleared when the browser closes, i would expect at least cookies to be cleared for the open tabs when the browser closes. Maybe cache too.

**Comment by bbondy** [comment]
those will be cleared, it's just the list of URLs will repopulate the cache when it loads then when you first focus the tab (and for the active tab)

**Comment by diracdeltas** [comment]
sgtm

**Comment by bbondy** [comment]
ok closing.
