### ISSUE TITLE
Images cannot be pasted in a local folder

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2531]
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/2513#issuecomment-233108106
While "Copy Image" on a context menu works in the browser, it does not in the outside. Image files cannot be pasted in a local folder.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Steps to reproduce:
    1. Select "Copy Image" on a context menu
    2. Go to Finder on macOS
    3. Open the context menu to paste the image

- Screenshot if needed:

- Any related issues: #1174 #2433 

Setting a milestone for now.

**Comment by bbondy** [comment]
Do other browsers allow that? Maybe there's another mime type but the primary thing this does that I know about is it puts the image data in the clipboard and programs can use it.  Like Gimp or gmail.

**Comment by luixxiul** [comment]
> Like Gimp or gmail.

Yes it works.

**Comment by luixxiul** [comment]
Sorry, let's leave this open.

**Comment by bbondy** [comment]
Unless you know of another browser that does this, I think we're working as we should.

**Comment by luixxiul** [comment]
I see, I confirmed it was invalid.
