### ISSUE TITLE
Autocomplete suggestion remains

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2532]
**Describe the issue you encountered:** Autocomplete suggestion remains after I logged in to GitHub with <kbd>Enter</kbd>.

**Expected behavior:** It should be removed.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Steps to reproduce:
    1. Log out from GitHub
    2. Select "Sign in"
    3. Fill in your mail address and password
    4. Push <kbd>Enter</kbd>

- Screenshot if needed:
<img width="377" alt="screenshot 2016-07-17 9 54 27" src="https://cloud.githubusercontent.com/assets/3362943/16898225/7b6ddd74-4c09-11e6-9b1d-269e0eeb9544.png">

- Any related issues:

**Comment by luixxiul** [comment]
I notice this still on the search field of github issues index. The suggestion pulldown does not disappear after hitting enter key.

**Comment by luixxiul** [comment]
@darkdh, will you please look at it?

**Comment by darkdh** [comment]
will do
