### ISSUE TITLE
Video on drive.google.com cannot be played when 3p cookies are blocked

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2533]
**Describe the issue you encountered:** Video on drive.google.com cannot be played when 3rd party cookies are blocked

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Screenshot if needed:
![screenshot](https://cloud.githubusercontent.com/assets/3362943/16898309/c8c5f50c-4c0e-11e6-83b8-56b68c82988e.jpg)

Perhaps a notification should be added that blocking 3rd party cookies may break some websites, like it has been added for blocking the fingerprinting methods.

**Comment by bbondy** [comment]
cc @diracdeltas

**Comment by diracdeltas** [comment]
do you have a sample video? i can't seem to play a .mov in google drive either way

**Comment by luixxiul** [comment]
I have one but it's private. Will send both of you DM with a link on Slack @diracdeltas @bbondy

**Comment by luixxiul** [comment]
Sent
