### ISSUE TITLE
prefs that require browser restart should show prompt for browser restart

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2543]
There are a bunch of prefs in `about:preferences` that require browser restart. If they are changed, Brave should show a notification bar that says, 'Do you want to restart now?' and restart when 'Yes' is clicked.

**Comment by luixxiul** [comment]
This should close #1705 as well.

**Comment by luixxiul** [comment]
I thought this also fixed #1705, but seems it didn't.

**Comment by luixxiul** [comment]
Also IMO the notification bar should be displayed only on about:preferences and closed automatically if setting is restored right away.
