### ISSUE TITLE
No urlbarIcon is specified for files opened in PDF reader

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2544]
**Describe the issue you encountered:** No `urlbarIcon` is specified for pdf files opened in the html5 pdf reader. Still clicking the place where the icon should be opens a notification.

**Expected behavior:** Some icon like `fa-file-pdf-o` should be specified.
- Brave Version: 0.11.1 Beta1
- Steps to reproduce:
  1. Open http://www.orimi.com/pdf-test.pdf
  2. Click somewhere in the PDF reader
  3. The status icon on the URL bar disappears
- Screenshot if needed:
  <img width="388" alt="screenshot 2016-07-18 0 45 56" src="https://cloud.githubusercontent.com/assets/3362943/16901560/40c4dbae-4c82-11e6-9304-333e0d15dcb4.png">
- Any related issues: #2534 #2530 

cc: @bradleyrichter

**Comment by bbondy** [comment]
@bradleyrichter could you provide something? Or there is this if you prefer:
http://fontawesome.io/icon/file-pdf-o/

**Comment by luixxiul** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
FA version is great.

**Comment by luixxiul** [comment]
The icon appears when a PDF file is opened. If you open http://www.orimi.com/pdf-test.pdf, you get the unlock icon. Is this actually what we want to have? If so, please close the issue.

**Comment by bradleyrichter** [comment]
@diracdeltas may want to chime in. 

Since the example above is an unsecure URL, we may want to keep the unsecure lock icon.

If it's a local PDF file, a file icon would be better.

**Comment by diracdeltas** [comment]
It should show whatever the icon for the protocol of the displayed URL is. ex: insecure icon for http://example.com

**Comment by luixxiul** [comment]
This has been fixed already
