### ISSUE TITLE
Add option to clear site-specific Bravery settings

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2545]
**Expected behavior:** Add option to clear site permissions of allowing/disallowing scripts

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Screenshot if needed:

For example on about:preferences#security,
<img width="393" alt="screenshot 2016-07-18 1 17 01" src="https://cloud.githubusercontent.com/assets/3362943/16901682/5d8dbf82-4c85-11e6-89d0-2d02fd5aaa38.png">

- Any related issues:

**Comment by luixxiul** [comment]
Also 3rd party cookies.

**Comment by diracdeltas** [comment]
I'm going to generalize this ticket to show all Bravery settings in the site permissions table or maybe a separate table
