### ISSUE TITLE
Session tab,New tab changing it's title several times[Bengali(Bangladesh)]

### ISSUE THREAD

**Issue by Tanvir-rahman** [brave/browser-laptop#2551]
**Did you search for similar issues before submitting this one?**Yes

**Describe the issue you encountered:**After open a new session tab,the session tab changing it's title three times.And after being fixed the title is not showing fully.After clicking somewhere, the " ু " part of the word "নতুন",will get completed.
Tab title change issue is occurring for "New tab" also.

**Expected behavior:** It should show a fixed title.And the title should be shown fully.
- Platform (Win7, 8, 10? macOS? Linux distro?): Win10
- Brave Version: 0.11.1
- Steps to reproduce:
  1.Open Brave browser and change language to Bengali(Bangladesh)
  2.Restart the browser.
  3.Open a new session tab
- Screenshot if needed:
  ![screenshot 50](https://cloud.githubusercontent.com/assets/15964566/16902588/457c94ae-4c85-11e6-8b08-6ccc201caec1.png)
  ![screenshot 51](https://cloud.githubusercontent.com/assets/15964566/16902590/4af070a4-4c85-11e6-962a-d0eb9e778eca.png)
  ![screenshot 52](https://cloud.githubusercontent.com/assets/15964566/16902591/50c6636c-4c85-11e6-99ea-7b79d3e159c5.png)
- Any related issues:

**Comment by luixxiul** [comment]
Closing as stale.
