### ISSUE TITLE
"Match case" change the focus to the next string

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2559]
**Describe the issue you encountered:** Enable and disable the option "Match case" change the focus to the next found string. Not sure if it works as it should.
- Platform (Win7, 8, 10? macOS? Linux distro?):  Windows 7
- Brave Version: 0.11.1 Beta2
- Steps to reproduce:
  1. Go to https://github.com/brave/browser-laptop/releases
  2. <kbd><kbd>CTRL</kbd>+<kbd>F</kbd></kbd>
  3. Paste `Electron 1.2.7`
  4. Enable and Disable "Match case"
- Screenshot if needed:
- Any related issues: #2556

**Comment by bbondy** [comment]
ya it should only change the current selection if the current match is a different casing, not super high priority but definitely a bug.

**Comment by luixxiul** [comment]
It seems this has been fixed recently. I confirmed it on Windows 10 and Debian.

**Comment by Liunkae** [comment]
Seems fixed on macOS too.

**Comment by luixxiul** [comment]
@Liunkae thanks for confirming :-)
