### ISSUE TITLE
WebGL fingerprinting protection

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2562]
Fingerprinting protection in about:preferences shows just 2 fingerprints blocked at https://jsfiddle.net/bkf50r8v/11/. WebRTC and Canvas only. WebGL seems to be not blocked. It works on Ubuntu 14.04 as it should.

On Windows 7
0.11.1 Beta2

#2556 

cc: @diracdeltas

**Comment by diracdeltas** [comment]
seems to work as expected on OS X. what is the output in `<div id='webrtc'></div>`?

**Comment by diracdeltas** [comment]
try https://jsfiddle.net/bkf50r8v/13/ instead

**Comment by luixxiul** [comment]
I tried and then got this:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16934327/2d296f60-4d90-11e6-8f00-845c6a90cef9.jpg)
The output is only "fingerprinting test".

**Comment by bbondy** [comment]
is there anything that blocks 0.11.1 left here?

**Comment by diracdeltas** [comment]
I think this is not a blocker; @luixxiul's output shows that webgl is blocked but not being reported in the panel.

**Comment by luixxiul** [comment]
I'm not sure whether webgl is blocked and not reported or it is not blocked.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16957574/d3cee606-4e17-11e6-9043-88c31e0171aa.jpg)

**Comment by diracdeltas** [comment]
if the output is only `fingerprinting test` and there are no console errors related to webrtc or canvas, it was blocked.

**Comment by luixxiul** [comment]
This is the output:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16957811/eed6c53a-4e18-11e6-900b-cff6505ef802.jpg)

Is it OK?

**Comment by luixxiul** [comment]
If ok I will close the issue.

**Comment by diracdeltas** [comment]
looks ok to me

**Comment by luixxiul** [comment]
got it, thanks.

**Comment by luixxiul** [comment]
I think it is still an issue; on Ubuntu 14.04 I see the 3 methods are blocked :-S

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16977228/d763d966-4e8f-11e6-9d11-52bc135092f0.jpg)

**Comment by bbondy** [comment]
Seems like at least a reporting issue?

**Comment by diracdeltas** [comment]
Yeah, feel free to open a new issue for the reporting number being wrong on Windows

**Comment by luixxiul** [comment]
OK done.
