### ISSUE TITLE
navigator.registerProtocolHandler does not work on Windows 7

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2563]
**Describe the issue you encountered:** ``mailto`` handler does not work on Windows 7

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

- Brave Version: 0.11.1 Beta2

- Steps to reproduce:
    1. Copy and paste ``mailto:example@example.com`` in URL bar
    2. Open <mailto:example@example.com>

- Screenshot if needed:

- Any related issues: #2556

**Comment by bbondy** [comment]
This is working with beta3, pls try again when it is out @luixxiul

**Comment by luixxiul** [comment]
#2583 It seems that on Win7 mailto: protocol hander is still not working. It displays the notification bar, but clicking "allow" opens an empty tab and does nothing thereafter.

Here is an example: ``mailto:?subject=%E3%83%B4%E3%82%A3%E3%83%88%E3%82%B2%E3%83%B3%E3%82%B7%E3%83%A5%E3%82%BF%E3%82%A4%E3%83%B3%E3%80%8E%E5%93%B2%E5%AD%A6%E6%8E%A2%E7%A9%B6%E3%80%8F%E3%82%92%E8%A7%A3%E8%AA%AD%E3%81%99%E3%82%8B%20%7C%20Philosophy%20Guides&body=https%3A%2F%2Fwww.philosophyguides.org%2Fdecoding%2Fdecoding-of-wittgenstein-untersuchungen%2F?utm_source=email%26utm_medium=email%26utm_campaign=social``

**Comment by bbondy** [comment]
did you register it on gmail first? I usually  just test with mailto:bbondy@gmail.com or similar.

**Comment by bbondy** [comment]
if mailto is still an issue for you with RC2 just post an issue, it worked for me though so I won't block on that for this release.

**Comment by luixxiul** [comment]
It works for me on OS X too, so this could be like #2602. In fact it works on Windows 10 32 bit in Japanese.

**Comment by luixxiul** [comment]
Deleting ``brave`` folder solved the issue.
