### ISSUE TITLE
PDF reader does not work within a new private tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2568]
**Describe the issue you encountered:** PDF reader does not work within a new session tab

- Platform (Win7, 8, 10? macOS? Linux distro?): Both Windows 7 and Ubuntu 14.04

- Brave Version: 0.11.1 Beta2

- Steps to reproduce:
    1. Open http://www.orimi.com/pdf-test.pdf in a new session tab

- Screenshot if needed:

- Any related issues: #2404 #2527 #2556 #2565 

cc: @diracdeltas 

Setting a milestone for now

**Comment by bbondy** [comment]
cc @diracdeltas

**Comment by bbondy** [comment]
Moving to 0.11.2

**Comment by luixxiul** [comment]
It does not work on a new private tab either.

**Comment by bbondy** [comment]
I don't remember is this the case for other extensions too @bridiver ?

**Comment by bridiver** [comment]
afaik all of the other extensions work in session and private tabs. Extensions can run in `split` or `spanning` mode and I've tested both types of extensions.

**Comment by diracdeltas** [comment]
it does actually load if you reload the PDF in the session tab but not in the private tab

**Comment by diracdeltas** [comment]
i see this error when trying to open pdfs in a private tab:
```
2016-07-26 15:12:36.269 Brave[5447:114231] Communications error: <OS_xpc_error: <error: 0x107900c90> { count = 1, contents =
        "XPCErrorDescription" => <string: 0x107900f78> { length = 18, contents = "Connection invalid" }
}>
```

**Comment by bbondy** [comment]
moved to 0.11.3 for now but ok with putting it in 0.11.2 if fixed before we release.

**Comment by diracdeltas** [comment]
appears that webRequest listeners are not fired for loads in private tabs

**Comment by bbondy** [comment]
In `about:extensions` chrome has an option for allow in incognito mode.  Maybe we just need to enable out extensions that we bundle there?

**Comment by diracdeltas** [comment]
the extensions do load in incognito mode, so i don't think that's the problem. just webrequest listeners don't work.

**Comment by diracdeltas** [comment]
fixed in https://github.com/brave/electron/commit/21383015964b4a693ad5b29327a1629aeaadb2b4

**Comment by luixxiul** [comment]
in 0.11.2? @bbondy

**Comment by diracdeltas** [comment]
it will be in 0.11.2
