### ISSUE TITLE
"Please add us in the adblocker's whitelist" message on JSFiddle 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2573]
**Describe the issue you encountered:**
Should we block this?

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16944221/796133aa-4dda-11e6-8969-90088f8bf05a.jpg)

- Any related issues:

**Comment by neeklamy** [comment]
Would there be an acceptable adverts policy? Something that, similar to Adblock Plus, by default is enabled and can be turned off.

Of course there’s the overhead of policing such a thing…

**Comment by diracdeltas** [comment]
i don't think we should block it

**Comment by bbondy** [comment]
I think the right place for this would be to file on EasyList which we use and update from periodically.

The resource we're blocking is:
https://cdn.carbonads.com/carbon.js?zoneid=1673&serve=C6AILKT&placement=jsfiddlenet

**Comment by BrendanEich** [comment]
Let's work the EasyList community so all blocker users benefit, if carbonads are legit. At Brave's size we are not ready to govern our own fork. Link to EasyList repo (I think this is it):

https://github.com/easylist/easylist/tree/master/easylist

Another approach would be to enable user allow-this-3rd-party-domain overrides to EasyList blocking that are customizable per each 1st party domain. @bridiver may have an issue filed on this already.

Forking EasyList and figuring out how we can possibly govern change requests to our fork is not in the cards any time soon. It could happen if Brave finds EasyList governance wanting, down the road, but so far we don't see a big problem -- and we are way too small to take it on anyway right now. Hope this helps.

**Comment by bridiver** [comment]
Agree with @BrendanEich that we shouldn't be carving out exceptions as we simple have no way to verify their ongoing compliance. Adblock Plus doesn't have an acceptable adverts policy, they have a business model that charges companies to be whitelisted. In the future we may have a mechanism to automate the compliance checking of individual ads, but right @neeklamy you can easily enable a site override for jsfiddle in the Brave menu

**Comment by bbondy** [comment]
Closing for now because this doesn't seem to be the right place, pls feel encouraged to get it fixed upstream.
