### ISSUE TITLE
Udacity not opening up

### ISSUE THREAD

**Issue by pradeepanchan** [brave/browser-laptop#2574]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Go to www.udacity.com . Click on Sign-In . Brave takes me to Sign up page instead. Also the page doesn't load.

**Expected behavior:**
Sign-in page should load.
Sign-up page did not load

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7 SP1 - 64 bit

- Brave Version:
0.11.0

- Steps to reproduce:
    1. Go to www.udacity.com
    2. Click on Sign-In 
    3. Brave takes me to Sign up page instead. 
    4. Also the page doesn't load.

- Screenshot if needed:

- Any related issues:

- Additional comments
This was working a few days back. I think some defect fix broke the working feature.

**Comment by srirambv** [comment]
Works fine for me on Windows 10. Able to login

**Comment by pradeepanchan** [comment]
Today it worked fine. I guess this issue has been resolved.
