### ISSUE TITLE
Reloading should start after Bravery panel is closed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2575]
**Describe the issue you encountered:** When changing settings on Bravery panel, reloading should not start before Bravery panel is closed. Sometimes I would like to change both cookie and ad settings at the same time.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version: 0.11.1 Beta2
- Screenshot if needed:
- Any related issues: #1621 #1951

**Comment by bbondy** [comment]
I think we considered it, but not sure if this would be an improvement or not.
Which way do you like better @bradleyrichter?

The current way has a benefit for the most used case of turning off all bravery shields and and maybe the page is already reloaded by the time you would take to click outside of the bravery panel.

**Comment by bradleyrichter** [comment]
The brave shields master switch should force a reload or it will most likely feel broken. For individual switches, we do have the reload button at the bottom of the dialog if the user wishes to see the effect of their change while the dialog is open. 

@luixxiul - In what way does it currently prevent you from making two changes? Is it just an annoyance waiting for the reload?

**Comment by luixxiul** [comment]
@bradleyrichter on a slow machine, which is a VM in my case, sometimes it seems like almost stuck when you make some changes on the panel. On a normal PC there might be no problem I think.

**Comment by bradleyrichter** [comment]
ok, that is a good argument. Does a switch change abort the reload? And force a new reload? If not, perhaps this is the change we should make first?

**Comment by diracdeltas** [comment]
any change reloads the page currently

**Comment by luixxiul** [comment]
I don't think this suggestion is right, closing.
