### ISSUE TITLE
Window title is not updated on Win7

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2576]
**Describe the issue you encountered:**
Here is a screenshot: https://github.com/brave/browser-laptop/issues/2562#issuecomment-233495632

> ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/16934327/2d296f60-4d90-11e6-8f00-845c6a90cef9.jpg)

The title says "Manual tests..." on JSFiddle.net

**Expected behavior:** It should be updated
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7
- Brave Version: 0.11.1 Beta2
- Steps to reproduce: Not sure.
- Any related issues:

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by luixxiul** [comment]
The issue has been fixed by introducing the new titlebar.
