### ISSUE TITLE
Middle clicking pinned tabs with no unpinned tabs closes browser

### ISSUE THREAD

**Issue by maddo** [brave/browser-laptop#2578]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When only pinned tabs are left in the browser window, middle clicking on a pinned tab closes the browser window.

**Expected behavior:**
I expect the pinned tab I middle click on to close, not the browser window.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X El Capitan 10.11.6
- Brave Version:
  Brave: 0.11.0
  Electron: 1.2.3
  libchromiumcontent: 51.0.2704.103
  V8: 5.1.281.65
  Node.js: 6.1.0
  Update Channel: dev
- Steps to reproduce:
  1. Have two pinned tabs and no unpinned tabs
  2. Middle click on either pinned tab
- Screenshot if needed:
  Screen recording: https://cl.ly/2M3r1h2R3B0j
- Any related issues:
  - Middle-clicking a pinned tab executes "next tab" instead fo closing the pinned tab https://github.com/brave/browser-laptop/issues/2569
  - Give a warning prompt when closing a window https://github.com/brave/browser-laptop/issues/854

**Comment by LoveIsGrief** [comment]
Happens with completely normal tabs as well.

```
[13399:13430:0629/222321.845837:ERROR:service_manager.cc(158)] Connection InterfaceProviderSpec prevented service: content_browser from binding interface: content::mojom::Child exposed by: content_renderer
[13399:13430:0629/222321.845905:ERROR:service_manager.cc(158)] Connection InterfaceProviderSpec prevented service: content_browser from binding interface: IPC::mojom::ChannelBootstrap exposed by: content_renderer
```

My scenario is:

1. Open brave
2. open a few tabs
3. close brave
4. reopen brave
5. middle click on open tab

Expected result:

Close middle clicked tab

Actual result:

Browser closes

------------------

If I load the tab left of the tab to close, I can close it. I assume opening unloaded tabs is a problem?

**Comment by bsclifton** [comment]
@LoveIsGrief what version of Brave are you using? You can try updating (our current version is 0.16.9 for Windows/macOS and 0.16.12 or 0.16.13 for Linux)

**Comment by LoveIsGrief** [comment]
@bsclifton Installed fba98fc v0.16.9 on linux only a few days ago. I'll update if possible.
