### ISSUE TITLE
Blacklist certain video cards that are known to not work

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2579]
Sometimes we get reports of people who get a black or white screen when they open.
We should ask them to open chrome and go to: `chrome://gpu/` and paste us the output.  

This task is to implement the support to block the things that users report with that.

**Comment by microchip03** [comment]
I'm running into this problem, so...

> Graphics Feature Status
> Canvas: Hardware accelerated
> Flash: Hardware accelerated
> Flash Stage3D: Hardware accelerated
> Flash Stage3D Baseline profile: Hardware accelerated
> Compositing: Hardware accelerated
> Multiple Raster Threads: Enabled
> Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
> Rasterization: Software only. Hardware acceleration disabled
> Video Decode: Hardware accelerated
> Video Encode: Hardware accelerated
> VPx Video Decode: Software only, hardware acceleration unavailable
> WebGL: Hardware accelerated
> Driver Bug Workarounds
> clear_uniforms_before_first_program_use
> disable_d3d11
> disable_direct_composition
> disable_discard_framebuffer
> disable_dxgi_zero_copy_video
> disable_nv12_dxgi_video
> disable_framebuffer_cmaa
> exit_on_context_lost
> force_cube_complete
> scalarize_vec_and_mat_constructor_args
> texsubimage_faster_than_teximage
> Problems Detected
> VPx decoding isn't supported before Windows 10 anniversary update.: 616318
> Disabled Features: accelerated_vpx_decode
> Some drivers are unable to reset the D3D device in the GPU process sandbox
> Applied Workarounds: exit_on_context_lost
> TexSubImage is faster for full uploads on ANGLE
> Applied Workarounds: texsubimage_faster_than_teximage
> Clear uniforms before first program use on all platforms: 124764, 349137
> Applied Workarounds: clear_uniforms_before_first_program_use
> Always rewrite vec/mat constructors to be consistent: 398694
> Applied Workarounds: scalarize_vec_and_mat_constructor_args
> ANGLE crash on glReadPixels from incomplete cube map texture: 518889
> Applied Workarounds: force_cube_complete
> Framebuffer discarding can hurt performance on non-tilers: 570897
> Applied Workarounds: disable_discard_framebuffer
> Crashes in D3D11 on specific AMD drivers: 517040
> Applied Workarounds: disable_d3d11
> Direct composition flashes black initially on Win <10: 588588
> Applied Workarounds: disable_direct_composition
> Zero copy DXGI video hangs on shutdown on Win < 8.1: 621190
> Applied Workarounds: disable_dxgi_zero_copy_video
> NV12 DXGI video hangs or displays incorrect colors on AMD drivers: 623029, 644293
> Applied Workarounds: disable_dxgi_zero_copy_video, disable_nv12_dxgi_video
> Limited enabling of Chromium GL_INTEL_framebuffer_CMAA: 535198
> Applied Workarounds: disable_framebuffer_cmaa
> Accelerated rasterization has been disabled, either via blacklist, about:flags or the command line.
> Disabled Features: rasterization
> Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
> Disabled Features: native_gpu_memory_buffers
> Version Information
> Data exported	1/20/2017, 8:44:33 AM
> Chrome version	Iridium/54.0
> Operating system	Windows NT 6.1.7601 SP1
> Software rendering list version	11.12
> Driver bug list version	9.00
> ANGLE commit id	905fbdea9ef0
> 2D graphics backend	Skia/54 a21f10dd8b19c6cb47d07d94d0a0525c16461969
> Command Line Args	Files\Iridium\iridium.exe" --profile-directory=Default --flag-switches-begin --flag-switches-end
> Driver Information
> Initialization time	58
> In-process GPU	false
> Sandboxed	false
> GPU0	VENDOR = 0x1002, DEVICE= 0x68b8
> Optimus	false
> AMD switchable	false
> Desktop compositing	Aero Glass
> Diagonal Monitor Size of \\.\DISPLAY1	21.5"
> Driver vendor	Advanced Micro Devices, Inc.
> Driver version	15.200.1062.1004
> Driver date	8-3-2015
> Pixel shader version	3.0
> Vertex shader version	3.0
> Max. MSAA samples	8
> Machine model name	
> Machine model version	
> GL_VENDOR	Google Inc.
> GL_RENDERER	ANGLE (AMD Radeon HD 5700 Series Direct3D9Ex vs_3_0 ps_3_0)
> GL_VERSION	OpenGL ES 2.0 (ANGLE 2.1.0.905fbdea9ef0)
> GL_EXTENSIONS	GL_OES_element_index_uint GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_OES_rgb8_rgba8 GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_EXT_color_buffer_half_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_float GL_OES_texture_float_linear GL_EXT_texture_compression_dxt1 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_OES_depth32 GL_EXT_texture_storage GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_occlusion_query_boolean GL_NV_fence GL_EXT_robustness GL_EXT_blend_minmax GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_pack_reverse_row_order GL_OES_standard_derivatives GL_EXT_shader_texture_lod GL_EXT_frag_depth GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_EXT_debug_marker GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_unpack_subimage GL_NV_pack_subimage GL_OES_vertex_array_object GL_KHR_debug GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_sync_query
> Disabled Extensions	
> Window system binding vendor	Google Inc. (adapter LUID: 0000000000006f47)
> Window system binding version	1.4 (ANGLE 2.1.0.905fbdea9ef0)
> Window system binding extensions	EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_ANGLE_flexible_surface_compatibility
> Direct rendering	Yes
> Reset notification strategy	0x8252
> GPU process crash count	0
> Compositor Information
> Tile Update Mode	One-copy
> Partial Raster	Enabled
> GpuMemoryBuffers Status
> ATC	Software only
> ATCIA	Software only
> DXT1	Software only
> DXT5	Software only
> ETC1	Software only
> R_8	Software only
> BGR_565	Software only
> RGBA_4444	Software only
> RGBX_8888	Software only
> RGBA_8888	Software only
> BGRX_8888	Software only
> BGRA_8888	Software only
> YVU_420	Software only
> YUV_420_BIPLANAR	Software only
> UYVY_422	Software only
> Diagnostics
> 0
> b3DAccelerationEnabled	true
> b3DAccelerationExists	true
> bAGPEnabled	true
> bAGPExistenceValid	true
> bAGPExists	true
> bCanRenderWindow	true
> bDDAccelerationEnabled	true
> bDriverBeta	false
> bDriverDebug	false
> bDriverSigned	false
> bDriverSignedValid	false
> bNoHardware	false
> dwBpp	32
> dwDDIVersion	11
> dwHeight	1080
> dwRefreshRate	60
> dwWHQLLevel	0
> dwWidth	1920
> iAdapter	0
> lDriverSize	1445224
> lMiniVddSize	0
> szAGPStatusEnglish	Enabled
> szAGPStatusLocalized	Enabled
> szChipType	AMD Radeon Graphics Processor (0x68B8)
> szD3DStatusEnglish	Enabled
> szD3DStatusLocalized	Enabled
> szDACType	Internal DAC(400MHz)
> szDDIVersionEnglish	11
> szDDIVersionLocalized	11
> szDDStatusEnglish	Enabled
> szDDStatusLocalized	Enabled
> szDXVAHDEnglish	Not Supported
> szDXVAModes	ModeMPEG2_A ModeMPEG2_C
> szDescription	AMD Radeon HD 5700 Series
> szDeviceId	0x68B8
> szDeviceIdentifier	{D7B71EE2-2BF8-11CF-4E70-9A09BEC2C535}
> szDeviceName	\\.\DISPLAY1
> szDisplayMemoryEnglish	2805 MB
> szDisplayMemoryLocalized	2805 MB
> szDisplayModeEnglish	1920 x 1080 (32 bit) (60Hz)
> szDisplayModeLocalized	1920 x 1080 (32 bit) (60Hz)
> szDriverAssemblyVersion	15.200.1062.1004
> szDriverAttributes	Final Retail
> szDriverDateEnglish	8/4/2015 01:28:34
> szDriverDateLocalized	04/08/2015 1:28:34 AM
> szDriverLanguageEnglish	English
> szDriverLanguageLocalized	English
> szDriverModelEnglish	WDDM 1.1
> szDriverModelLocalized	WDDM 1.1
> szDriverName	aticfx64.dll,aticfx64.dll,aticfx64.dll,aticfx32,aticfx32,aticfx32,atiumd64.dll,atidxx64.dll,atidxx64.dll,atiumdag,atidxx32,atidxx32,atiumdva,atiumd6a.cap,atitmm64.dll
> szDriverNodeStrongName	oem3.inf:ATI.Mfg.NTamd64.6.1:ati2mtag_Evergreen:15.200.1062.1004:pci\ven_1002&dev_68b8
> szDriverSignDate	
> szDriverVersion	8.17.0010.1404
> szKeyDeviceID	Enum\PCI\VEN_1002&DEV_68B8&SUBSYS_29901682&REV_00
> szKeyDeviceKey	\Registry\Machine\System\CurrentControlSet\Control\Video\{3203B3A8-2A94-4A4F-AA60-956549FF0B4E}\0000
> szManufacturer	Advanced Micro Devices, Inc.
> szMiniVdd	n/a
> szMiniVddDateEnglish	n/a
> szMiniVddDateLocalized	n/a
> szMonitorMaxRes	
> szMonitorName	Generic PnP Monitor
> szNotesEnglish	No problems found.
> szNotesLocalized	No problems found.
> szOverlayEnglish	Not Supported
> szRankOfInstalledDriver	00E62001
> szRegHelpText	
> szRevision	
> szRevisionId	0x0000
> szSubSysId	0x29901682
> szTestResultD3D7English	Not run
> szTestResultD3D7Localized	Not run
> szTestResultD3D8English	Not run
> szTestResultD3D8Localized	Not run
> szTestResultD3D9English	Not run
> szTestResultD3D9Localized	Not run
> szTestResultDDEnglish	Not run
> szTestResultDDLocalized	Not run
> szVdd	n/a
> szVendorId	0x1002
> Log Messages
> GpuProcessHostUIShim: The GPU process exited normally. Everything is okay.
