### ISSUE TITLE
Video pop out (HTML5) - similar to Opera

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2582]
Pop out video (HTML5) something similar to what is on Opera would be nice.

**Comment by Jacalz** [comment]
+1 from community: https://community.brave.com/t/video-pop-up-top/3099

**Comment by Jacalz** [comment]
Would also love to have this option :+1:

**Comment by srirambv** [comment]
+1 from community for Twitch https://community.brave.com/t/pop-out-twitch-player/6730/2

**Comment by emmanuelmanzanilla** [comment]
I'm waiting this extension, because, for me, is a very important. I like Opera for videos popup. If accept the extension, I change full to Brave!!!

**Comment by bsclifton** [comment]
For people like me that aren't familiar with this feature, he's a link showing an overview:
https://blogs.opera.com/desktop/2016/04/opera-beta-update-video-pop/

**Comment by R1552** [comment]
Came here to request this. It's one thing I really liked about Oprah.

**Comment by AimeMurenzi** [comment]
waiting for this feature too in order to fully commit to brave.

**Comment by User619** [comment]
waiting for this feature too in order to fully commit to brave.

**Comment by twinklebob** [comment]
I use Opera purely for this reason. Would love to switch to Brave full time and start using BAT to pay for the youtube content I love to watch.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/pip-picture-in-picture-which-stick-to-top-of-other-windows-youtube-windows-10/30060

**Comment by Jacalz** [comment]
I am fairly certain that this will get fixed in Brave-core. Google is workin on a picture in picture mode which can be enabled from chrome://flags. 

It will get enabled by default when it is fully ready. More info on it an be found at their site:
https://wicg.github.io/picture-in-picture/

**Comment by srirambv** [comment]
Pretty sure the flag needs to be enabled manually after full implementation. Thanks for the links 

cc: @bbondy

**Comment by Jacalz** [comment]
Yes @srirambv, that id entirely true at the moment but it is intended to be turned on by default, as far as I know, in a future update of Chromium.

**Comment by bsclifton** [comment]
Closing as `wontfix` in favor of https://github.com/brave/brave-browser/issues/824 in brave-core
