### ISSUE TITLE
Copy password should have some sort of authentication before copying to clipboard

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2589]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Copy password from the about:passwords page copies the password to clipboard. 

**Expected behavior:**
Should have some sort of authentication(system authentication) before copying the password to clipboard. This is a security risk if anyone else using the machine can get hold of stored password. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.0
- Screenshot if needed:
- Any related issues:

**Comment by diracdeltas** [comment]
btw if you lock the system keychain, it should prompt for keychain unlock before copying to clipboard

**Comment by fermulator** [comment]
Confirmed on Linux that the gnome-keyring is directly utilized for this functionality. Indeed if is locked, the user is unable to "copy to clipboard" the password without the keyring being unlocked.
