### ISSUE TITLE
Dragging a Bookmarklet to the tab-bar area causes the browser to whitescreen

### ISSUE THREAD

**Issue by AramZS** [brave/browser-laptop#259]
I don't know if there is intended to be a bookmarklet area, but attempting the drag and release causes the browser to white screen on the OSX build.

**Comment by diracdeltas** [comment]
There is no bookmarklets section yet

**Comment by diracdeltas** [comment]
I was hoping https://github.com/brave/browser-laptop/commit/7e5dba30bb9675df8b0612266e685dc82b4dec55#commitcomment-15776640 would fix this, but it doesn't. It seems that only `javascript:` URLs dragged into the tabbar cause the main BrowserWindow to navigate to `about:blank`. `http(s):`,  `data:` and `file:` don't seem to have this issue.

Test page:

**Comment by diracdeltas** [comment]
closed by https://github.com/brave/browser-laptop/commit/a4f6d0beeeffb46c0af9718440c99ffbbca0c7fa
