### ISSUE TITLE
No link to Abode flash from preferences page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2591]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clicking on Adobe doesn't open Adobe flash install page. Just highlights the text. Also the text spacing is wrong. No space between from and Adobe.

**Expected behavior:**
Should navigate to https://get.adobe.com/flashplayer/ when user clicks on Adobe.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![ezgif-2597117473](https://cloud.githubusercontent.com/assets/17010094/16964270/6e5f64a0-4df2-11e6-8726-76000ba70990.gif)
- Any related issues:

**Comment by cezaraugusto** [comment]
Confirmed. However by running the dev-build version it's unreproducible. I think it's already fixed for the next release.

/cc @luixxiul if I'm missing something.

**Comment by luixxiul** [comment]
Yes it has been fixed.
