### ISSUE TITLE
"Add Funds" modal locks up the browser when 

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#2592]
on macos, after clicking on the "Add Funds" link in the "Publishers" pane of the "Preferences" panel, the "Add funds" modal appears. if you click on "Buy with Coinbase", then the browser locks up (i.e., the Coinbase Buy Widget does not appear, the orange `X` in the upper right-hand corner does not close the modal, neither does the `Done` button in the lower right-hand corner.)

the other link to "Add Bitcoin" appears to work fine.
![1](https://cloud.githubusercontent.com/assets/400552/16964775/0dff948a-4db2-11e6-9f2d-71a47d00ef22.png)

**Comment by diracdeltas** [comment]
fixed as of 16e0aff1637b1fe549946e57610ea3f1f5b96b1c
