### ISSUE TITLE
Arch linux: Scroll bar appears over tabs when they fill the tab bar

### ISSUE THREAD

**Issue by dangerginger** [brave/browser-laptop#2599]
My search skills may have failed me, but I did not find this bug.  I apologize if this is a duplicate.

Problem:  After opening enough tabs (depends on window size) to fill the tab bar, a horizontal scroll bar appears that conceals the lower ~75% of the tabs.  I am still barely able to switch tabs by clicking on the very top of the tab, but it is difficult to see which tab is which.  The scroll bar is always "full", meaning it cannot actually scroll left or right no matter how many tabs there are.  Closing or pinning tabs until they no longer fill the available space causes the scroll bar to disappear.

Expected behavior: The scroll functionality should not conceal the tabs, and should effectively scroll to tabs or tab groups that are not currently visible.

Platform:  Arch Linux

Brave Version: v0.11.0

Steps to reproduce:
    1.  Open brave
    2. Open multiple tabs until they fill the available space in the tab bar.
    3. Observe the scroll bar covering the tabs.
    4. Close tabs until the scroll bar disappears.

![2016-07-19-212108_1148x1041_scrot](https://cloud.githubusercontent.com/assets/14853111/16975023/6f5c4062-4df7-11e6-8bef-fe8ce85bada8.png)

**Comment by bbondy** [comment]
PR wanted for this from someone who is running Arch Linux.

**Comment by bbondy** [comment]
It should be a pretty small CSS tweak maybe with `overflow-x: clip` or something like that

**Comment by babolivier** [comment]
Archlinux user here, I remember having this issue a while ago (even opened https://github.com/brave/browser-laptop/issues/1403), and didn't encountered it after that (even now, v0.11.0). I tried to reproduce it by pinning as much tabs as you have, then playing with the window's width, but couldn't.
![capture d ecran de 2016-07-20 22-08-16](https://cloud.githubusercontent.com/assets/5547783/17001247/894db986-4ec6-11e6-858c-d96320956c2a.png)

@dangerginger How did you install Brave? AUR? If so, which package? (I use the `brave-bin` one, maybe with the one you're using it behaves differently because of the install procedure)

**Comment by dangerginger** [comment]
@babolivier, I initially installed the `brave` package from the AUR.  As you suggested, I removed that and tried the `brave-bin` package but got the same behavior.  I deleted the ~/.config/brave directory and restarted the browser, but also no change.  I experience the same behavior in both i3 (tiling) and lxde.

@bbondy, I can look into fixing this but it would be my first PR.  If you give me a hint on where I should look into this it would help me get started.

Thanks

**Comment by bbondy** [comment]
You can fix this by using the built in browser level dev tools.
The shortcut of this is changing soon, so if you see it stop working just check the recent commit history.
But for now you can use Control+Alt+J. Then you can use the DOM inspector on the tab bar and try to tweak it to fix just like for a web page.

Once you find the styles that need to change just `git grep term` for where to change it.

The README has information about first time setup.

**Comment by dangerginger** [comment]
Great. I will look into this over the weekend. Thanks for pointing me in
the right direction.

**Comment by bbondy** [comment]
awesome, thanks @dangerginger!

**Comment by dangerginger** [comment]
I found the CSS selector using the method you described and sent my first ever PR.  You can tell it's the first one because I unfortunately named it 'patch-1'.  Sorry about that.  Not very descriptive.
