### ISSUE TITLE
Order of unpinned tabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2600]
**Describe the issue you encountered:** When I unpin the pinned tabs, they are opened following the order where they were pinned.

For example: 
If I have this set: [1] [2] [Unpinned] [Unpinned], where 1 and 2 are pinned.

If I unpin 1, I get this: [2] [Unpinned] [Unpinned] [1]
And if I unpin 2: [Unpinned] [Unpinned] **[1] [2]**

**Expected behavior:** I think this might be just of my preference, but I want to get this: [Unpinned] [Unpinned] **[2] [1]**
- Brave Version: 0.11.0
- Screenshot if needed:
- Any related issues:

**Comment by srirambv** [comment]
If a pinned tab is moved towards the end it becomes unpinned tab. Is this a normal behavior??

**Comment by bbondy** [comment]
you can unpin a tab by drag and drop, but it should be possible to re-order something to the end.

**Comment by srirambv** [comment]
Can't really put a pinned tab at the end. The moment the pinned tab is dragged towards the end it gets unpinned.

**Comment by luixxiul** [comment]
My point is when you have tons of opened tabs with multiple tab pages already it might be sometimes annoying to select the page where the unpinned tab should appear.
