### ISSUE TITLE
Allow flash to run alert doesn't dismiss when allow/deny selected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2603]
**Did you search for similar issues before submitting this one?** 
Yes

**Describe the issue you encountered:**
The alert for running flash player doesn't get dismissed when allow/deny is clicked

**Expected behavior:**
Should dismiss the alert based on the user selection

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.11.0

- Steps to reproduce:
    1. Open google.com
    2. Search for download adobe flash player
    3. Click on the first link 
    4. Browser alerts to run flash on google.com site
    5. Click allow/deny to dismiss the alert
    6. Doesn't dismiss on clicking either allow/deny
    7. Open a new windows the alert still shows

- Screenshot if needed:
![ezgif-3693851297](https://cloud.githubusercontent.com/assets/17010094/16976228/587c3002-4e45-11e6-8c0c-9401f45b6dfe.gif)

- Any related issues:

**Comment by bbondy** [comment]
the same steps work for me in 0.11.1.  This might be a duplicate which is already fixed. Could you retry with the release going out probably today (possibly tomorrow at worst case)

**Comment by srirambv** [comment]
@bbondy Tested with the new build 0.11.1. Seems like its still broken. 
1. Alert still comes up when remember my decision checked and clicked allow. 
2. After selecting page reloads to google site and still gives the alert.
3. After selecting allow/deny the alert disappears and when clicked on the link the tab has no history of previous pages. 
4. Open new tab and repeat the same procedure the same result. Checked in new window same result.
5. Does shows google.com under saved site permission

![ezgif-580904371](https://cloud.githubusercontent.com/assets/17010094/17000670/6a0ebeb8-4ebb-11e6-81a6-23cb9fea7a52.gif)

**Comment by diracdeltas** [comment]
The first bug is that the notification bar shouldn't appear on search engines like google.com. The second is that 'remember this decision' currently doesn't do anything.

**Comment by diracdeltas** [comment]
follow-up: https://github.com/brave/browser-laptop/issues/2639
