### ISSUE TITLE
search image on context menu

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#2606]
Add search image option to context menu on image
<img width="818" alt="screen shot 2016-07-20 at 15 54 37" src="https://cloud.githubusercontent.com/assets/11330831/16979209/73e9a886-4e92-11e6-9344-ba51843c15b2.png">
===
<img width="767" alt="screen shot 2016-07-20 at 15 54 50" src="https://cloud.githubusercontent.com/assets/11330831/16979217/7f2d399c-4e92-11e6-8fa3-4853d1fd4333.png">

**Comment by luixxiul** [comment]
FYI: if script is not enabled on Google this does not work

**Comment by bbondy** [comment]
pls post a new issue to only include that option when scripts are enabled (noscript is off) thx.

**Comment by bbondy** [comment]
(not blocking release)

**Comment by luixxiul** [comment]
Now more search options has been integrated, is it possible to include the other search engines?
