### ISSUE TITLE
Add support for Enpass password manager. 

### ISSUE THREAD

**Issue by webbson** [brave/browser-laptop#2608]
I really like your browser, the only thing I'm missing is support for Enpass password manager ([enpass.io](https://www.enpass.io)).

Is this something that might be implemented? I would like this support in Brave on Windows, iOS and Android.

**Comment by luixxiul** [comment]
+1 from support

**Comment by stefnats** [comment]
+1 would be great

**Comment by bbondy** [comment]
dupe of https://github.com/brave/browser-laptop/issues/5097 ?

**Comment by bsclifton** [comment]
Yup, https://github.com/brave/browser-laptop/issues/5097 is a dupe of this! 😄  Closing issue
