### ISSUE TITLE
Pinned tabs should be refreshed automatically

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2610]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pinned tabs doesn't refresh automatically. 

**Expected behavior:**
Automatically refresh when new content available.
- Platform (Win7, 8, 10? macOS? Linux distro?): 
  Windows 10
- Brave Version:
  0.11.0
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
I don't think we'd want to auto refresh, but maybe an option via right click context menu to enable it on a case by case basis where you want it.  Some sites already take auto refreshing their content into their own hands like Twitter, and sometimes you might for example have form data filled in.

**Comment by srirambv** [comment]
@bbondy  I agree with you on the form pages . Providing an option to enable refresh on right click context menu would be a good option which allows user to enable for specific sites rather than refreshing it manually each time.

**Comment by cjrjscgallo** [comment]
I would like this feature.
