### ISSUE TITLE
'View Certificate' non-functional

### ISSUE THREAD

**Issue by Synthetase** [brave/browser-laptop#2611]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When attempting to click the "View certificate" button in the Developer Tools Security tab, nothing happens. This occurs on all five sites loaded via HTTPS and checked for this issue, which have certificates of different types, from different CA's.
**Expected behavior:**
Display of SSL certificate details
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS X 10.11.5 (15F34)
- Brave Version:
  0.11.0
- Steps to reproduce:
  1. Load site via HTTPS
  2. Click 'View' menu --> click 'Toggle Developer Tools' --> click 'Security' tab
  3. Attempt to click 'View certificate' button
- Screenshot if needed:
  ![screen shot 2016-07-20 at 10 53 54 am](https://cloud.githubusercontent.com/assets/5875016/16993386/c9ff3d5a-4e68-11e6-99bf-4e1cfa93d0f9.png)
- Any related issues:

**Comment by Liunkae** [comment]
+1 from #6116.

**Comment by srirambv** [comment]
Its the same on Windows as well

**Comment by bbondy** [comment]
@darkdh just a heads up we'd like you to work on this before 1.0 but after your chromium upgrade work. Thanks.

**Comment by diracdeltas** [comment]
+1 from hackernews

**Comment by bsclifton** [comment]
Similar to this, we'll want to show cert when you click the padlock icon in the nav bar (per https://github.com/brave/browser-laptop/issues/6157)
