### ISSUE TITLE
Auto logout from sites

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2620]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave browser logouts from sites automatically.Checked for Facebook and Github.

**Expected behavior:**
Should not logout until user logout

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.11.1

- Steps to reproduce:
    1. Login to Facebook/Github
    2. Keep the page open for five mins
    3. Browser automatically logs out.

Turned on Clear all site cookies when closed.  Looks like cookies getting cleared automatically without closing the browser

- Screenshot if needed:
![cookie](https://cloud.githubusercontent.com/assets/17010094/17003781/6b91d6fe-4ec9-11e6-93a8-75e5219d03b9.PNG)

- Any related issues:

**Comment by bbondy** [comment]
ah I see because we save ever 5 minutes, so the shutdown save code clears it.  Just turn that option off for now is best.  We'll include a fix in 0.11.2
