### ISSUE TITLE
Save password prompt doesn't show up if user selects No.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2625]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Save password prompt doesn't show up for any site if user selects "No". Tried this on Instagram, Gmail, Facebook. 

**Expected behavior:**
Should prompt to save password each time unless user selects "Never on this site".

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.11.1

- Steps to reproduce:
    1. Open any site with login
    2. Enter Userid/password for the first time
    3. Save password prompt shows up
    4. Select No 
    5. Repeat steps 1 & 2 
    6. No save password prompt is shown. 

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Verified same on Debian as well for Brave v0.11.1

**Comment by bbondy** [comment]
cc @diracdeltas
