### ISSUE TITLE
Number of fingerprinting protection is wrongly reported

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2626]
## Test plan

1. Go to https://jsfiddle.net/bkf50r8v/13/
2. Click the shield button
3. Enable Fingerprinting Protection if not
4. Make sure it is reported that 3 elements were blocked

----

**Describe the issue you encountered:** On Windows 7 the number of fingerprinting protection is wrongly reported.

**Expected behavior:** 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7
- Brave Version:
- Steps to reproduce:
  1. Go to https://jsfiddle.net/bkf50r8v/13/
  2. You'll see 3 elements are blocked, while 2 elements are reported to be blocked
- Screenshot if needed:
- Any related issues: #2562  #2768 #2769 #2862 #2861 #2907

**Comment by luixxiul** [comment]
On Windows 10 the bravery panel says WebRTC and Canvas are blocked

**Comment by alexwykoff** [comment]
Noticed the same on Ubuntu as well. Updated the title and label.

**Comment by bbondy** [comment]
if >1 OS type (windows, linux, ubuntu we can usually assume it's cross platform)

**Comment by luixxiul** [comment]
This bug is long standing and should be fixed I think if it is easy.

**Comment by luixxiul** [comment]
It looks this has been fixed for me on
 
Brave: 0.18.30 
rev: 795cc102729fc843ea82757c9e9508242fd5830e 
Muon: 4.3.17 
libchromiumcontent: 61.0.3163.71 
V8: 6.1.534.31 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

![clipboard01](https://user-images.githubusercontent.com/3362943/30241351-bf36eeb2-95bc-11e7-8439-5bcf0b084383.png)

I suspect this issue is related with a graphic driver. See: https://github.com/brave/browser-laptop/issues/3227#issuecomment-305074974 Maybe this has been fixed with a Chromium update?

Closing the issue in case for QA. If it is not fixed globally, let's re-open.

**Comment by aekeus** [comment]
winia32 and lubuntu show 2 blocked when 3 expectedd

**Comment by bbondy** [comment]
I'm going to reset milestone for now.

**Comment by bsclifton** [comment]
@luixxiul how does this look? Is additional work needed?

**Comment by luixxiul** [comment]
I'm not quite sure but I think it is related with graphic drivers to display WebGL if that is the thing which is not blocked.

**Comment by bsclifton** [comment]
Looks like this is working great now
