### ISSUE TITLE
"New window" should be able to be opened via context menu/middle click  on task bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2627]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to launch new browser window when user right clicks on the taskbar icon and selects Brave. 

**Expected behavior:**
New window should launch when user clicks on the mouse middle button or selects Brave from the right click context menu. 
Should either open a new window or a new tab. Currently the only way to open new window is by pressing Ctrl+N
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Open Brave browser
  2. Right click on the browser icon in taskbar
  3. Select Brave from the right click context menu
  4. Alternately click on the middle button in mouse
  5. Should launch new browser window/add a new tab in the already opened window
- Screenshot if needed:
- Any related issues:

**Comment by Nokel81** [comment]
Still a problem in 0.12.1

**Comment by jevad** [comment]
And still a problem in 0.17.13.  This is probably *the* primary reason more people do not adopt Brave as their primary browser.  There is a reason all the other browsers will open a new window from their taskbar icon context menus -- that's how users use browsers.

**Comment by srirambv** [comment]
+1 from community on adding feature to launch browser using the middle click 
https://community.brave.com/t/ability-to-create-a-new-window-by-starting-new-exe-middle-clicking-taskbar/5237

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/no-new-window-when-right-click-on-taskbar-icon/19922?u=eljuno

>No new window when right-click on taskbar icon.
>Windows 7, Brave 0.22.21

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/open-new-window-options-by-right-clicking-brave-icon-in-windows-taskbar/22427?u=eljuno

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/CodeurFou/status/1022551100350779393

Also, will this feature available with brave-core?

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/698

Unfortunately, this functionality is not currently in brave-core
