### ISSUE TITLE
Explore partition tabs UI

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#263]
Regarding the partitions tabs feature:

Yan wrote:
> This is a good start. overall i think my biggest concern is that it's hard to tell what partition any tab is in. i think there needs to be UI like the "Person 1" indicator from Chrome:

> ![screen shot 2016-01-22 at 18 30 51](https://cloud.githubusercontent.com/assets/549654/12527745/4d11c1ec-c136-11e5-8528-15ce5af54347.png)

> Also, what are use cases for partitioned tabs that aren't already possible with private tabs? (Or with a fresh session per private tab)

Some kind of icon perhaps with a title attribute may be enough. You can also already click on the icon in the urlbar to get site info and it also tells you which partition the tab lives in.  

I imagine the biggest use case for this is having multiple signed in twitters and gmails etc.  I think the "Person" UI isn't an exact match for this so want to avoid that exact UI.  I do think we can expose a completely different person sign-in via this same type of code as well but that covers a different use case.

**Comment by bradleyrichter** [comment]
@bbondy Do you want to maintain x number of logins per site? And be able to switch between them? Or just show an indicator for a particular tab?

**Comment by bbondy** [comment]
I think we're good with the current icon and hover over which says which session it is.
Closing this.

**Comment by bradleyrichter** [comment]
@bbondy I think we need to find a more obvious description for the menu item. Does github have a polling feature?

**Comment by bbondy** [comment]
"New Session Tab" is what we have now, I think most people understand it. 
It's also a good item for tip of the day.  
By the way people are also asking for "New Private Session Tab" which also does make sense we just don't have it yet.

**Comment by bradleyrichter** [comment]
Ok. That is better than Partitioned Session. Let's see how that sits with users.

And with that many tab types, we may need a sub menu. It may be ok since Command+T is commonly used.

**Comment by bbondy** [comment]
Submenu seems like a good idea to me.

**Comment by bbondy** [comment]
Please post a new more specific issue for submenu if you want that btw, or whatever other changes you think.
