### ISSUE TITLE
Trigger the call of pdfjs on MIME type rather than extension

### ISSUE THREAD

**Issue by babolivier** [brave/browser-laptop#2633]
I just noticed that pdfjs was systematically called on any URL ending with `.pdf`, such as http://sdfgsdfgsd.com/test.pdf (which doesn't exist) or https://github.com/Intel-Media-SDK/samples/blob/master/samples/sample_decode/readme-decode_linux.pdf (which returns HTML content, not readable by a PDF reader). I think that pdfsj should be called regarding the response MIME type (`application/pdf` for PDF) and not how the URL is ending.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux

- Brave Version: 0.11.1

- Steps to reproduce:
    1. Open a new tab
    2. Write or paste an URL (leading to an existing resource or not) containing a domain name and a path ending in `.pdf`

![pdf](https://cloud.githubusercontent.com/assets/5547783/17022848/aa163988-4f50-11e6-9006-17272ce141e3.PNG)

**Comment by diracdeltas** [comment]
++, i think this is causing problem on PDFs that redirect to an HTML page for auth (ex: in slack)

this may be fixed by taking out the `setPDFLocation` calls in `js/stores/windowStore.js`, which are a workaround for PDFs not loading at all unless they fire an Electron navigation event

**Comment by diracdeltas** [comment]
verified that pdfjs does MIME detection in `webRequest.onHeadersReceived` so this should be fixed by reverting the workaround for the other bug

**Comment by luixxiul** [comment]
in 0.11.2?

**Comment by bbondy** [comment]
we will put all in 0.11.2 that's in master and freeze as soon as chromium 52 is avail.
