### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by keithlevine** [brave/browser-laptop#2637]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Not able to print any document from the browser. When printing a PDF doc from google drive encountered the following error msg:

PDF.js v1.5.340 (build: bc86419)
Message: Unexpected server response (0) while retrieving PDF "https://doc-00-94-apps-viewer.googleusercontent.com/viewer/secure/pdf/cttjkfbn0d5g5fjpss0mimtsqllrt0t3/o56ug97vmgd5p5gak3dmovrnods0je2r/1469113875000/drive/06526146117045481839/ACFrOgD_MNuBBpMUEg5eCPNigj59gEKAvUTDrGyMjrWUzqZukub3d3gtCvAobpiZnv45UHX6aM1MwuC8ubVWAdPt5sBY-X3IP_A3xEEeZgo_yxbChVmuXCJZ7yRiaEA=?print=true".

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Window 7
version 6.01 (build 7601: Service Pack 1)
![image](https://cloud.githubusercontent.com/assets/20581612/17028515/7ed5d058-4f2d-11e6-94a3-5c8f29eefe0d.png)

- Brave Version:
0.11.1
![image](https://cloud.githubusercontent.com/assets/20581612/17028509/78993630-4f2d-11e6-9cbd-2da4c3a8c651.png)

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/20581612/17028594/a7d67e30-4f2d-11e6-91fc-5ea81798784e.png)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #1616
