### ISSUE TITLE
downloads open a save dialog but don't end up in their destination folder.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#264]
I suspect we haven't landed downloads yet so this is a reminder for DF'ing.

**Comment by bbondy** [comment]
they go inside the profile in a Downloads folder, it's an electron build and we should get it for free on the next upgrade. Anything other than the location fix we need to do here?

**Comment by bbondy** [comment]
I'll just close this since we'll definitely get it from upstream, if we find we don't though we can open another or re-open this.
