### ISSUE TITLE
Photobucket albums don't render properly, unless AdControl is set to "Allow Ads and Tracking"

### ISSUE THREAD

**Issue by ms82494** [brave/browser-laptop#2640]
**Issue encountered**

I looked at a couple of albums on [Photobucket](http://www.photobucket.com), and none displayed any photos. I then changed the AdControl setting to "Allow Ads and Tracking", and they displayed correctly -- As did the advertising on Photobucket.
**Expected behavior:**

I expected to see the albums, but not the advertising with AdControl set to "Show Brave ads"

**Platform (Win7, 8, 10? macOS? Linux distro?):**

Windows 10 Pro
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Ensure that AdControl setting is on "Show Brave Ads" or "Block Ads"
  2. Navigate to a Photobucket album, say, [this one](http://www.photobucket.com/browse)
  3. Observe: No photos!
  4. Change AdControl setting to "Allow Ads and Tracking"
  5. Reload Photobucket page
  6. Observe: Photos have appeared!
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-photobucket/10951

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
