### ISSUE TITLE
opening pdf in same tab doesn't work if noscript is on

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2642]
instead it asks to save

**Comment by bbondy** [comment]
moving to 0.11.3 but ok to put in if we get it before 0.11.2 is released.

**Comment by diracdeltas** [comment]
i think this was fixed by https://github.com/brave/browser-laptop/commit/6b0d1448331b0a821a872b56e56fd48ecb0610dd. it's no longer  happening for me.

**Comment by bbondy** [comment]
:D
