### ISSUE TITLE
prefs sometimes not saved after restart

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2643]
https://github.com/brave/browser-laptop/pull/2546/files#r71753818

**Comment by darkdh** [comment]
That's weird. I check the value of before restart. It seems like it has been changed.
For pdf.js as an example:
`AppStore.getState().get('settings').get('advanced.pdfjs-enabled')`
The value is what I expected. But it will be set to the value before change after restart.

I will keep digging it.

**Comment by diracdeltas** [comment]
for me it only seems to happen on the Flash pref

**Comment by darkdh** [comment]
For me it happen on every options (required restart or not).
And I tried to toggle any option and do explicit restart by `alt+cmd+r` and the prefs also not been saved.
