### ISSUE TITLE
zoom button is not set default

### ISSUE THREAD

**Issue by sahasrara62** [brave/browser-laptop#2645]
after opening any website and then going to menu option to change the zooming value (say changed it from 100% to 300% ) and then closing the brave browser ,after closing , when i open the brave browser the zoom tab/website is open at the previous setup value ie 300% not 100% .

**Expected behavior :once we zoomed in or zoomed out the window in a session ,after closing the brave browser and reopening the browser  the page should show the default zoom size not the last changed one.**

- Platform (Win7, 8, 10? macOS? Linux distro?): ubuntu 14.04 LTS

- Brave Version:   0.11.1

- Steps to reproduce:
    1.  open brave browser . go to any website . say www.google.com
    2. in the same tab , go to menu option , then click on zoom in or zoom out option , adjust the zooming value accordingly to you.close the brave browser entirely.
    3.open the brave browser , now you would see the last zoomed setting for your current page not the default or original one .

**Comment by luixxiul** [comment]
This works as it should, still it might be good if we have an option for it.

**Comment by sahasrara62** [comment]
yes , an option for it  might be a good choice.

**Comment by bbondy** [comment]
I think this is wontfix but cc'ing @bradleyrichter for another opinion
