### ISSUE TITLE
Delete button doesn't delete selected url. Moves cursor to the end of the URL.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2647]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In a new tab, any URL auto loaded from history/opened tabs is selected by default. Pressing delete button doesn't delete the URL, instead moves the cursor towards the end of the existing URL.

**Expected behavior:**
Should delete the selected text

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10.

- Brave Version:
0.11.1

- Steps to reproduce:
    1. Open new tab
    2. Type a URL which is there in history or opened tabs/pinned tabs
    3. Complete URL is selected when it loads
    4. Press delete button to remove the selected URL
    5. After pressing the delete button 3-4 times the cursor jumps to the end of the URL instead of deleting it.

- Screenshot if needed:

- Any related issues: #2288

**Comment by TheFallenOneGOTH** [comment]
Confirmed for Brave 0.11.1 on Windows 10.

**Comment by bsclifton** [comment]
This is one for sure that has driven me nuts! Thanks for filing this 😄

**Comment by bsclifton** [comment]
BTW- wanted to confirm it happens on Mac also (I have a Das Keyboard, no weird mappings)

**Comment by bbondy** [comment]
On macOS MBP to reproduce you need to use Fn+Delete which is the actual keycode for delete. The Delete key on MBP is actually backspace which works fine.

**Comment by bbondy** [comment]
Would like to have this in the next hotfix if someone can grab it.

**Comment by bsclifton** [comment]
Fixed w/ https://github.com/brave/browser-laptop/pull/2720 :+1:
