### ISSUE TITLE
Optimize bookmarks search

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2651]
With a lot of bookmarks, bookmark search can sometimes lag the typing.  I think debouncing the key presses like we do for the url bar when we do xhr when the search engine suggestions option is turned on. 

similar to what's done here: `git grep this.searchXHR\ =\ debounce`

**Comment by bbondy** [comment]
This is only obvious if you have a ton of bookmarks by the way.  But since we have import that's possible / common.

**Comment by bsclifton** [comment]
A lot of this was fixed with split sites and related perf improvements we've done
