### ISSUE TITLE
Site sendo exibido incorretamente!!

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2653]
O brave está apresentando um erro em alguns sites mais precisamente na Netflix.... Alguém pode me ajudar?
![sem titulo](https://cloud.githubusercontent.com/assets/20443574/17043048/671ac21e-4f89-11e6-96dc-fe74b77b1d44.png)

**Comment by cezaraugusto** [comment]
Hi @EuNlope. please notice that not everyone here speaks Portuguese. I noticed that you also commented on #468 reporting the same issue. 

Could you open a new issue, in english, and describe it more fully, with information like Brave version you're using, your OS, current and expected result? This way we can see better what's going on and figure a way to work on it. Thanks.
