### ISSUE TITLE
Bookmark name of a file does not appear in the autocomplete list

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2655]
**Describe the issue you encountered:** If you bookmark a URL to a file and set a title to the bookmark, only the URL is displayed in the autocomplete list.

**Expected behavior:** The title also should be displayed.
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: 0.11.1
- Steps to reproduce:
  1. Bookmark http://speedtest.ftp.otenet.gr/files/test100k.db with the title `test`
  2. Enter `test`
- Screenshot if needed:
  <img width="465" alt="screenshot 2016-07-22 10 43 13" src="https://cloud.githubusercontent.com/assets/3362943/17044225/22323cc0-4ff9-11e6-931e-70e4742f58bf.png">
- Any related issues: #2271

**Comment by luixxiul** [comment]
I noticed that it's not related with the file type. Here's an example. STR unknown.
<img width="355" alt="screenshot 2016-07-22 13 25 20" src="https://cloud.githubusercontent.com/assets/3362943/17046559/c4f0f7ec-500f-11e6-936e-5b90c09cf2b4.png">

**Comment by bbondy** [comment]
it is just like that when the site that was added has no title to display from a <title> element.  Is there a better thing to display in that case? Maybe for a filename with a file:// with a file extension should show the filename? cc @bradleyrichter

**Comment by NejcZdovc** [comment]
@luixxiul is this still a problem? can you please re-test it?

**Comment by luixxiul** [comment]
It is not fixed yet.

![clipboard01](https://user-images.githubusercontent.com/3362943/28497534-bc017cb2-6fc4-11e7-80e6-b9e3b8b3dcea.jpg)
