### ISSUE TITLE
No download complete notification when download bar is closed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2658]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
No notification upon download complete when user has closed the download bar.

**Expected behavior:**
Some popup notification or icon background progress indicator(similar to chrome/firefox) should be there to let the user know download is complete.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Download a large file
  2. Close the Download bar while downloading
  3. No notification upon completion
- Screenshot if needed:
- Any related issues:

**Comment by Liunkae** [comment]
Related: #1667 (Make the Downloads folder icon "bounce" when a download is finished)

**Comment by bsclifton** [comment]
This isn't directly fixed with [brave-core](https://github.com/brave/brave-browser)... (ex: not notification is shown)... but the application's icon (for both browser-laptop and brave-core, at least on mac) now shows a progress bar (which goes away when download is completed)
