### ISSUE TITLE
Documentation missing: Flash on Linux

### ISSUE THREAD

**Issue by hron84** [brave/browser-laptop#2659]
**Describe the issue you encountered:**

There is no documentation about how to install Flash on Linux to let Brave to recognize it. 

**Expected behavior:**

I think Brave should detect if there is a Google Chrome installation and try to use the Flash plugin from it, otherwise it should pop up a message with a Wiki link about how to install and configure Flash in it.
- Platform (Win7, 8, 10? macOS? Linux distro?): Arch Linux
- Brave Version: 0.11.1

**Comment by diracdeltas** [comment]
if you go to about:preferences#security it has basic instructions on how to install Flash in linux for Brave to recognize. could be better.

**Comment by hron84** [comment]
@diracdeltas I'll check it out, but as far as I remember I did found any text about flash. But I'll re-check it anyway.

**Comment by diracdeltas** [comment]
@hron84 pull requests welcome. currently it just says `Flash support is experimental and requires the pepperflashplugin-nonfree package.` on linux

**Comment by luixxiul** [comment]
I'm going to close this in favor of this topic on our community.

https://community.brave.com/t/flash-isnt-working-audio-or-video-is-not-working/14.

If changes inside the code base is added, let's reopen this one 👍
