### ISSUE TITLE
Brave displays horizontal scrollbar at tabs.

### ISSUE THREAD

**Issue by hron84** [brave/browser-laptop#2660]
**Describe the issue you encountered:**

Tab bar shows me a scrollbar

**Expected behavior:**

Tab bar should not show me a scrollbar

- Platform (Win7, 8, 10? macOS? Linux distro?): Arch Linux

- Brave Version: 0.11.1

- Screenshot if needed:

![bravetabbug](https://cloud.githubusercontent.com/assets/88636/17052289/1ecc0440-4ffd-11e6-97d7-e16560e76091.png)

**Comment by luixxiul** [comment]
Fixed with #2650. Please reopen if not.

**Comment by hron84** [comment]
@luixxiui could you tell me which version contains or will contain this fix? I don't build Brave from source, instead I use the binary version of it.

**Comment by luixxiul** [comment]
You can see this fixed in the next release 0.11.2, which is not available yet.

**Comment by hron84** [comment]
I see. Is there any expectations when it will come out?

**Comment by luixxiul** [comment]
@hron84 In a couple of days!
