### ISSUE TITLE
MSN Pages not rendered properly.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2664]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
MSN articles for example  [Link1](http://www.msn.com/en-ie/cars/specials/can-you-guess-the-car-logo/ar-AAgjg47?li=BBr5RWG&ocid=mailsignoutmd) and [Link2](http://www.msn.com/en-ie/cars/specials/beemer-brainiac-the-bmw-quiz/ar-BBuBXOt?li=BBr5RWG&ocid=mailsignoutmd) are not rendered properly. All content below the article is not shown including leave comment section. The page itself has a interactive quiz which doesn't work. Its the same with any article on MSN site under any section. 

**Expected behavior:**
Should display the subsequent sections after the articles.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  MSN on Chrome: 
  ![msnchrome](https://cloud.githubusercontent.com/assets/17010094/17062810/6329466e-502c-11e6-8b8e-c77840bae36a.PNG)

MSN on Brave:
![msnbrave](https://cloud.githubusercontent.com/assets/17010094/17062829/70a6a660-502c-11e6-8cce-a330563e2bbf.PNG)
- Any related issues:

**Comment by TheFallenOneGOTH** [comment]
Still a problem for Windows 10 Brave v0.11.1.

**Comment by luixxiul** [comment]
Disabling the bravery shield loads the page

**Comment by luixxiul** [comment]
It seems to me that images like `https://images.taboola.com/taboola/image/fetch/f_jpg%2Cq_auto%2Ch_156%2Cw_280%2Cc_fill%2Cg_faces:auto%2Ce_sharpen/http%3A//blog.dailylifetech.com/b/lighter/0005.jpg` should not be blocked. On Chrome with Adblock Plus (only Easylist enabled) they are displayed.

**Comment by bsclifton** [comment]
Appears to be resolved
