### ISSUE TITLE
plans for "google translate" by default in brave?

### ISSUE THREAD

**Issue by miinoru** [brave/browser-laptop#2666]
sorry me english is bad, but need this tools in the navigator and brave no have this and no plugins support.   :( , any tips?
http://fotos.subefotos.com/1bfd2ed183b2e0f4d762c01b1765dbc2o.jpg

And pls Fix the language... this is span/glish. hehe :P 
http://fotos.subefotos.com/d0d6b1843ad2e5ede02061fb4fc04ebfo.jpg
http://fotos.subefotos.com/2d8fb976b42ce290078e6c44aecbb504o.jpg

**Comment by EuNlope** [comment]
Some things on the menu are not yet fully translated into Brazilian portguês, I hope the menu is fully translated to pt-BR.

**Comment by barry-johnson** [comment]
I too would love to see built in support for right-click "Translate to <your language>" such as is found in Chrome.
In fact, I would say now that LastPass support is implemented, it is probably my #1 feature request for Brave (OK, I would really like to be able to have Bing as my default search engine as well).

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/google-translate-extension/4711

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
