### ISSUE TITLE
Title of rebookmarked item is not saved

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2672]
**Describe the issue you encountered:** Title of rebookmarked item is not saved.

**Expected behavior:** The title should be saved.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1

- Steps to reproduce:
    1. Bookmark this page WITHOUT setting a title
    2. Edit the bookmark adding a title and save it
    3. Edit the bookmark again
    4. No title is saved

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul can you please re-test? This should be fixed with https://github.com/brave/browser-laptop/pull/3339

Thanks :smile:

**Comment by luixxiul** [comment]
Bookmarking requires setting a title thanks to #3347, so closing this.
