### ISSUE TITLE
HTTP status icon of pages opened from autocomplete list

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2673]
**Describe the issue you encountered:**
HTTP status icon of pages opened from the autocomplete list says "Using an insecure connection".

1. Open a new tab
2. Input "github"
3. Select a page from the autocomplete list

#2444 

cc: @diracdeltas

**Comment by diracdeltas** [comment]
shows up as secure for me

**Comment by luixxiul** [comment]
how about analytics.google.com?

**Comment by bbondy** [comment]
both show up as secure for me

**Comment by luixxiul** [comment]
weird, what do you guys think causes it?

**Comment by luixxiul** [comment]
I'm not sure at all but maybe this is related with #2708?

**Comment by luixxiul** [comment]
Possibly this was fixed with https://github.com/brave/browser-laptop/commit/cb3c161df82d3cc5813ebdbd539d4fed9edfe057, which closed #2708 and #2722. I close this for now and reopen if not.

**Comment by luixxiul** [comment]
It started happening since today.

**Comment by darkdh** [comment]
Sorry my bad due to non-discreet rebase task

**Comment by luixxiul** [comment]
I'm not quite sure that's the cause
