### ISSUE TITLE
Flash Plugin error on websites even after enabling under Security panel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2678]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Website shows error after enabling Adobe Flash under the security panel. Happens on all websites that require Flash support.

**Expected behavior:**
If Adobe Flash support is enabled should be able to browse the website.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Enable Adobe Flash support from Security panel in preferences
  2. Visit [this site](https://pixlr.com/editor/) 
  3. Error is displayed
  4. Disable and enable and restart browser still same issue
- Screenshot if needed:
  ![flashsupport](https://cloud.githubusercontent.com/assets/17010094/17077276/164c882e-50c2-11e6-94b0-3209fa4bb140.PNG)
- Any related issues:

**Comment by luixxiul** [comment]
All sites?

**Comment by luixxiul** [comment]
The former seems to be related with #2397, the latter is not reproducible for me. If I click "download adobe flash player", notification bar appears as it should. The issue on pixlr seems to be a different one.

**Comment by luixxiul** [comment]
cc: @diracdeltas

**Comment by srirambv** [comment]
If I right click on the Flash banner and select Allow for 1 week/Allow once then the flash content loads but doesn't play on this site [here] (http://www.flashgames247.com/play/17172.html). It works on the other one.

**Comment by luixxiul** [comment]
Closing as this is stale
