### ISSUE TITLE
ADD Plugins (Widevinecdm)

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2679]
What's wrong in the code?

app.commandLine.appendSwitch('widevine-cdm-path', '/AppData/brave/to/widevinecdmadapter.dll');
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.903');
let win = null;
app.on('ready', (Brave) => {
  win = new BrowserWindow({
   webPreferences: {
   Widevinecdm: true
  }
 });
});

**Comment by luixxiul** [comment]
Duping to #468
