### ISSUE TITLE
Issue: Brave was freezing while reading some random Twitter hashtags

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#2680]
**Describe the issue you encountered:**
Looked around in Twitter, suddenly browser was freezing, was unable to switch or close tabs. Got responsible again after i force quitted some processes from Brave in the Windows task manager
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 8, 64 Bit
- Brave Version:
  0.11.1 - 64 Bit

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/does-brave-freeze-while-reading-some-random-twitter-hashtags/10389

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
