### ISSUE TITLE
Reopen tab/Window from menu not disabled after Clearing History

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2681]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After clearing history Reopen Last Tab & Reopen Last Window should be disabled. It still enabled after clearing history

**Expected behavior:**
Both the buttons should get disabled when user clears history
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
js/state/frameStateUtil.js needs another function like clearClosedFrames(windowState) that will set windowState ‘closedFrames’ to an empty immutable list. It would be called from a new appAction and would be cleared in the js/stores/appStore.js

**Comment by luixxiul** [comment]
I believe this is the same as #2528

**Comment by bbondy** [comment]
I think #2528 is about session restore on startup and this is about undo closed tabs no?

**Comment by luixxiul** [comment]
Yes exactly, sorry!

**Comment by bbondy** [comment]
np mainly #2528 I think does not need to be fixed since you can adjust another option to get the desired result there, but here you cannot.

**Comment by srirambv** [comment]
Reopen last closed window is only set to 1 window deep, so after reopening closed window should also disable the Reopen Last Closed Window (or after reopening all closed windows depending on how deep the closed windows are set)

**Comment by diracdeltas** [comment]
I can no longer repro this issue. can someone confirm it's fixed?

**Comment by bsclifton** [comment]
@srirambv could you please retry this? 😄

**Comment by srirambv** [comment]
It still looks pretty enabled to me on Windows. Its even enabled when a new install is done, and is clickable which sounds like its still enabled. It should not be clickable when a new install is done or when the history is cleared.

**Comment by PatMB30** [comment]
Hi, I'd like to work on this issue.

> js/state/frameStateUtil.js needs another function like clearClosedFrames(windowState) that will set windowState ‘closedFrames’ to an empty immutable list. It would be called from a new appAction and would be cleared in the js/stores/appStore.js

I'd like to have a bit more clarification on this. I've looked at the files involved and tested multiple times and I'd like to know if I need to add a new WindowConstant variable. Additionally, I'm unsure how I can gain access to the 'closedFrames' from js/state/frameStateUtil.js so that I can assign them to an empty Immutable list.

Any more clues or hints about what needs to be done would be appreciated too, thank you.
