### ISSUE TITLE
Make getBaseDomain use LRU cache

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2682]
@diracdeltas mentions this function is slow and we call it during filtering so we should be using an LRU cache for the lookups.

**Comment by bbondy** [comment]
We use it already in other parts of the code like here:
app/trackingProtection.js:const LRUCache = require('lru_cache/core').LRUCache

**Comment by david-gang** [comment]
Hi @bbondy ,

It is not clear to me what should be done.
Should the line 198 in the commit  https://github.com/brave/browser-laptop/commit/144f78603dc6d84f55a62705de6df35dd895cabc
changed from !refererExceptions.includes(parsedUrl.hostname) to !refererExceptions.includes(getBaseName(parsedUrl.hostname)) and then in getBasName we will implement the lru cache?
