### ISSUE TITLE
Trackpad Scrolls Browser Chrome

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#2684]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Tabs and browser window itself can be scrolled using trackpad. The location bar can become very long and extend beyond, and is clipped by the scrollable window. Scrolling sideways to get to the back button results in history navigation.

**Expected behavior:**
Tabs should not scroll up. The window should not have an outer invisible scrollable area.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS

- Brave Version:

- Steps to reproduce:
I do not know what causes this bug.

- Screenshot if needed:

- Any related issues:
The "trackpad scrolls history" issue.

**Comment by bbondy** [comment]
cc @darkdh
