### ISSUE TITLE
Brave Fails BrowserScope Security Test #3

### ISSUE THREAD

**Issue by rnsjunkmail** [brave/browser-laptop#2687]
https://www.browserscope.org/security/test

**Results**
1) PASS postMessage API
2) PASS JSON.parse API
3) FAIL toStaticHTML API
4) PASS httpOnly cookie API
5) PASS X-Frame-Options
6) PASS X-Content-Type-Options
7) PASS Block reflected XSS
8) PASS Block location spoofing
9) PASS Block JSON hijacking
10) PASS Block XSS in CSS
11) PASS Sandbox attribute
12) PASS Origin header
13) PASS Strict Transport Security
14) PASS Block cross-origin CSS attacks
15) PASS Content Security Policy
16) PASS Cross Origin Resource Sharing
17) PASS Block visited link sniffing

Brave fails the 3rd test...  toStaticHTML API

Hopefully BRAVE can close this gap soon.

**Comment by bbondy** [comment]
@diracdeltas pls audit, see also: https://bugs.chromium.org/p/chromium/issues/detail?id=108159

**Comment by diracdeltas** [comment]
I don't see any significant benefit to us implementing toStaticHTML given that neither Firefox nor Chrome have plans to. Marking wontfix.

**Comment by rnsjunkmail** [comment]
I thought the point of Brave was to be MORE secure than Firefox or Chrome? As user considering a move to Brave did I miss something?

**Comment by bbondy** [comment]
This test is far from the perfect measure of security. Implementing some extra API does not make us more secure anyway and makes users more identifiable.

**Comment by diracdeltas** [comment]
@rnsjunkmail i don't believe us implementing toStaticHTML will make any meaningful difference. how often do developers make use of it, given that it's only supported in IE/Edge? if the usage stat is >1%, we may consider it.

brave is small and won't skew the usage numbers very much.

CSP is a far more effective and cross-browser compatible way to reduce XSS, and we do support it.
