### ISSUE TITLE
RAM consumption

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2689]
Normally 5 or 6 tabs open the browser is presenting a consumption slightly above the ordinary.
![memory      # #####brave](https://cloud.githubusercontent.com/assets/20443574/17081404/6c52f1f2-512d-11e6-85e4-d39377bbed97.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): WINDOWS 10 64 BITS

- Brave Version: 0.11.1 DEV

**Comment by luixxiul** [comment]
Reported at #415. Thanks.
