### ISSUE TITLE
Always reloading tab happens because sometimes did-frame-finish-load is not sent

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#269]
Or we register for it in error somehow or some other reason for it.

**Comment by bbondy** [comment]
Note always but seems to happen on twitter and Yan mentions Facebook.

**Comment by PFCKrutonium** [comment]
I have also had this happen on YouTube, see #284 (Unrelated, but it is occurring there.)

**Comment by prkeshri** [comment]
Hello guys,
Same thing happening in my side too.
When I extracted the electron.asar file and wrote a couple of log statements, the following is the output (for any url):
did-start-loading
destroyed
did-start-loading
did-get-response-details
load-commit
did-navigate
destroyed
did-start-loading
.
. and so on in the same loop

The webView always fires these in the order in a loop. I need to know why does it get destroyed always?

**Comment by luixxiul** [comment]
I'm not sure, but maybe is this related with #1862?

**Comment by luixxiul** [comment]
Was this fixed already?

**Comment by bbondy** [comment]
I think this is all worked out now
