### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2690]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Could have full compatibility with extensions google chrome.
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10-64bits

- Brave Version: 0.11.1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by willy-b** [comment]
+1, especially if it makes it easier to integrate the React DevTools.

Speaking of which, does anyone have tips on how to cleanly add the React DevTools? 
Instructions I see elsewhere for Electron are not working for me.

**Comment by luixxiul** [comment]
Duping to #253. Please make sure to search for similar issues before you submit new ones, thanks.
