### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by artukrap** [brave/browser-laptop#2692]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Just browsing trough ebay

**Expected behavior:**
Show images
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Visit page http://www.ebay.co.uk/sch/i.html?_from=R40&_sacat=0&_nkw=ANTI%20STATIC%20WRIST&rt=nc&LH_PrefLoc=3&_trksid=p2045573.m1684
- Screenshot if needed:
  http://prntscr.com/bwtmqw
- Any related issues:
  No

**Comment by luixxiul** [comment]
+1 from support

**Comment by caliston** [comment]
Noting that images appear if you go to Bravery->Bravery site settings and 'Allow ads and tracking' - seems Brave considers the ebay listing images to be ads.

**Comment by luixxiul** [comment]
currently images are loaded.
