### ISSUE TITLE
Bug: Glitches during scrolling with hardware acceleration on

### ISSUE THREAD

**Issue by Axvedma** [brave/browser-laptop#2693]
**Describe the issue you encountered:**
Having hardware acceleration of the browser activated and scrolling down a very long page creates glitches like that on different combination of hardware, like some Geforce graphic cards in combination with AMD chipsets and other minor integrated graphic chips like some Intel HD ones.

**Expected behavior:**
Brave should not create such lines while scrolling
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7 64 Bit
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. visiting http://deepskyfrontier.com/
  2. Scrolling down
  3. See glitches appear
- Screenshot if needed:
  http://i.imgur.com/DoHrmyG.png

Some last notes:

Does not happen with Chromium itself, only happens with browsers like Brave or even Vivaldi which both have a rendered ux.

**Comment by bbondy** [comment]
Could you check with `chrome://gpu` and see if you have hardware acceleration auto disabled for you in Chrome?

**Comment by AXVDM** [comment]
No, hardware acceleration in Chromium portable is possible, i am the owner of 2 laptops, one old Asus G73JH with an ATI Mobility™ Radeon graphic card where Brave or Vivaldi produces no glitches, even if hardware accelearation is on and a more recent Asus Zenbook laptop ( https://www.asus.com/Notebooks/UX32LN/ ) where hardware acceleration works also out of the box but there it produces glitches.

**Comment by CountLesnik** [comment]
@bbondy Experiencing a similar glitch now after trying out Brave 0.11.2 - as the topic opener describes it already, that glitches can be seen with hardware acceleration in activated state with a similar graphics card configuration (Intel HD Graphics).

The difference to the previous build is that this glitch is now visible too with hardware acceleration in deactivated state. I also can confirm that this happens with Vivaldi browser, but there the glitch can be avoided with deactivated smooth scrolling.

Looks like smooth scrolling creates that issue. Would be for sure interesting to see if an option to disable it would fix that issue in Brave too.

**Comment by bbondy** [comment]
Any driver updates that fix it by chance?

**Comment by AXVDM** [comment]
@bbondy Not in my case. All drivers are up to date. It just does not work with some graphic chips as it produces glitches.

If it would be driver related it would create glitches with normal Chromium too.

**Comment by luixxiul** [comment]
Does this problem happen on Chrome too?

**Comment by AXVDM** [comment]
@luixxiul No problem in unmodified Chromium or Chrome. Also no problem in Slimjet or Centbrowser. This is something Brave used technologies only as it looks like.

**Comment by bbondy** [comment]
could you try downloading beta2 from the releases page (make sure to revert back to a stable build after that) and check if it is solved by disabling `Enable smooth scrolling (requires browser restart)` in preferences advanced? 
We will disable this by default for our 0.11.2 release. 

If it is solved, we can close this.

**Comment by luixxiul** [comment]
I'm going to close this as stale.
