### ISSUE TITLE
Search Settings Panel: Search Suggestions (Part 1)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2694]
- Add Search settings to the preferences with more search engines listed:
(Qwant and Yandex are explained in separate issues - #2701, #2703)

- Add shortcut key prefix string support in the location bar so you can search specific engines at any time to override your default engine

- use favicons provided by each search engine, pointing to them so they remain current over time

- engine order is alphabetical

- default is google (regional defaults may be added later)

![image](https://cloud.githubusercontent.com/assets/13509546/17089648/ac62756e-51dd-11e6-88da-990ca46b38ee.png)

**Comment by luixxiul** [comment]
in 0.11.2 https://github.com/brave/browser-laptop/commit/4fe6075f77d8917998501c9fe4a7b3db58dc4fa9
