### ISSUE TITLE
Cache favicons (to prevent fetching each time Brave is reloaded)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2697]
**Describe the issue you encountered:** If favicons of bookmarks become 404, the favicons are also gone, which makes it difficult to notice that the bookmark is there, until #2075 is fixed. Also if a user starts Brave offline, no favicon will be displayed.

**Expected behavior:** When the user visit the site, Brave should store favicons in the Base64 format and replace them with it, and it should check if the favicon needs updating when the user revisits the site.
- Brave Version: 0.11.1

**Comment by luixxiul** [comment]
Also "clear site data" option from menubar should remove the favicon cache too.

**Comment by bsclifton** [comment]
Caching would also be good because there is a delay in the bookmarks toolbar... for example, when you open a folder that has links. The delay is might only be 200 milliseconds before the image shows but it's noticeable.

**Comment by bbondy** [comment]
@bsclifton someone complained about that on twitter recently. cc @BrendanEich

**Comment by bsclifton** [comment]
For content pages like about:bookmarks, images are cached.  However, images that are in the browser do not seem to be caching... like favicons in the bookmarks toolbar and the ones from the back/forward nav buttons (ex: stuff you can see when you load the shift+F8 dev tools).

When discussing with @bridiver, it seems that these are not using a public context when fetching, so it doesn't get cached. @bridiver did you have any info to add?

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/5840

Assigned milestone

**Comment by bridiver** [comment]
I can bring in the history component from chromium

**Comment by bsclifton** [comment]
@bridiver would this help with content loaded in a private context? ex: our main UI?

**Comment by luixxiul** [comment]
I would be banned due to potential DOS attack:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26525701/1005f85c-439b-11e7-8272-ffce63d61d98.jpg)

If it is not easy to cache favicons for now, why don't we limit the maximum number of retry to fetch them, or prevent the browser from retrying to do so if the page is reloaded automatically?

**Comment by luixxiul** [comment]
Also: requesting favicons each time on reload can be a strong indicator of the browser. It might be stronger than fingerprinting. CC @diracdeltas

**Comment by diracdeltas** [comment]
favicon cache seems useful. it should be cleared at least whenever the user clears history.

**Comment by diracdeltas** [comment]
as discussed in https://github.com/brave/browser-laptop/issues/12689, i think we can just hard-code the cache for now. later we can add cache invalidation/updating when a user visits the favicon'ed page.

**Comment by bsclifton** [comment]
Closing as `wontfix` as this will be addressed with Brave Core (coming soon). This is the new Chromium based UI which replaces the Muon based UI we use currently
