### ISSUE TITLE
Not a valid Electron app

### ISSUE THREAD

**Issue by cwramsey** [brave/browser-laptop#270]
On OSX, after building from master, I get this error when running `npm start`

<img width="436" alt="screen shot 2016-01-23 at 9 13 26 am" src="https://cloud.githubusercontent.com/assets/8377322/12530854/abc736ce-c1b1-11e5-968e-b6e79125fc82.png">

When running tests, the same error happens on every test suite. Example of result.

```
favicon
      5) "before all" hook
      6) "after all" hook
    lockIcon
      7) "before all" hook
      8) "after all" hook
    themeColor
      9) "before all" hook
      10) "after all" hook
    new window
      11) "before all" hook
      12) "after all" hook
```

**Comment by daanlenaerts** [comment]
I'm having the same issue, both on Windows as on OS X.

**Comment by rixrix** [comment]
Hi,

Got the same error but because I was on Node v4 (README), had to switch to Nodev5 and cleaned up the node_modules and did the following:

`$> npm run watch`
`$> npm run start` <-- should be run on a separate terminal

hope that helps ;)

**Comment by cwramsey** [comment]
Unfortunately it didn't @rixrix. Same exact response. Thanks for the suggestion though!

**Comment by rixrix** [comment]
oh bugger!... apology for that @cwramsey - maybe a gist of the logs ?

**Comment by daanlenaerts** [comment]
Issue #219 is about the same problem.

**Comment by bbondy** [comment]
sqlite3 is no longer a dependency so this shouldn't be a problem anymore. Closing
