### ISSUE TITLE
Add Qwant to search engine prefs and results

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2701]
Qwant offers us a bit more than a post URL.

![image](https://cloud.githubusercontent.com/assets/13509546/17089617/79338ed0-51dd-11e6-93cd-aa50eeccc7f8.png)

code for qwant:
`
<Url type="application/x-suggestions+json" method="GET" template="https://api.qwant.com/api/suggest/?q={searchTerms}&client=brave »/>
<Url type="text/html" method="GET" template="https://www.qwant.com/?q={searchTerms}&client=brave »/>`

Something important to notice is the "client=brave" parameter.

CC @bbondy (if further info is needed)

**Comment by bbondy** [comment]
mainly just make sure about the parameter pls. Thanks.
