### ISSUE TITLE
Re-open closed tabs should include history

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#2702]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I reopen the last closed tab, it opens and loads the page it was on. However, any history for that tab is lost. Once I reopen the last closed tab, I'm unable to use its back button go to back to previous pages viewed in that tab prior to closing it. Safari does this, and it is a very nice and convenient feature.

**Expected behavior:**
I expect to be able to reopen the last closed tab and not only see the page it was on when it was closed but also be able to traverse the tab's history with the back button.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.5
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Open a tab in Brave.
  2. Visit a few pages.
  3. Close the tab.
  4. Reopen the tab with the "Reopen Last Closed Tab" action.
  5. Note that you can't use the back button.

#963

**Comment by luixxiul** [comment]
Duping to #889 and #444

**Comment by bsclifton** [comment]
#444 was closed but did not include this functionality. Re-opening

**Comment by jkup** [comment]
Another request for this feature https://community.brave.com/t/maintain-tab-history-after-restore/198

**Comment by jamonholmgren** [comment]
Adding my +1 to this, and adding that this actually impacts my workflow quite a lot. Safari, Chrome, and Firefox all support restoring tab history on reopening the tab.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/ctrl-shift-t-does-not-restore-history/1342

**Comment by ayumi** [comment]
+2

**Comment by patrick99e99** [comment]
+1

**Comment by Brampyr** [comment]
+1

**Comment by hsribei** [comment]
+1

**Comment by luixxiul** [comment]
+1 from https://community.brave.com/t/all-tab-history-lost-after-brave-restarts/7840?u=suguru

CC @zentagonist for setting a milestone.

**Comment by NumDeP** [comment]
+1

**Comment by Ratselblitz** [comment]
This has happened to me repeatedly - browser updates and I lose all tabs *and* history!  One more time and I'll stop using Brave.

**Comment by luixxiul** [comment]
You mean tabs are lost or tabs' histories are lost?

**Comment by Ratselblitz** [comment]
Both…  Mac OXS if that helps…

**Comment by Alino** [comment]
why is this open for a year? :\
this is driving me crazy, every time I reopen a closed tab and want to go back, I can't

**Comment by NumDeP** [comment]
@Alino your familiar with JS, why don't you contribute?

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/back-button-functionality-upon-reopening-closed-tab-ctrl-shift-t/11985?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/reopening-closed-tab-tab-history-not-preserved/13684?u=eljuno

Brave	0.19.131
libchromiumcontent	63.0.3239.132
Muon	4.5.36
Node.js	7.9.0
OS Architecture	x64
OS Platform	macOS
OS Release	14.5.0
rev	da2f347
Update Channel	Release
V8	6.3.292.49

**Comment by srirambv** [comment]
+1 from @chrisbarber  via #12890

**Comment by vinicentus** [comment]
+1 #13095

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/re-open-last-tab-should-open-with-its-history/16332?u=eljuno

**Comment by btlechowski** [comment]
+1 #13293

**Comment by nishay77** [comment]
+1 from a random dude

**Comment by Byte-Buster** [comment]
I'm a new user of Brave and I have the same problem.
Any progress? I see that this case is open since 2016. will there be any attempts to fix this problem, or should I stop using Brave?

**Comment by bsclifton** [comment]
Hey there folks!

This is a feature that will be solved when we transition from Muon (our current architecture) to our new Chromium fork, Brave Core.  If you've got a development environment setup, you can download/build the project now (no official builds yet):
https://github.com/brave/brave-browser

You can read more about this on our blog:
https://brave.com/development-plans-for-upcoming-release/

Stay tuned 😄

**Comment by bsclifton** [comment]
Closing as `wontfix` (for `browser-laptop`) since this is fixed with [Brave Core](https://github.com/brave/brave-browser) (coming soon!)
