### ISSUE TITLE
Add Yandex to search engine prefs and results

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2703]
Yandex offers an API that will integrate deeper into search results by providing suggestions from Yandex in real time.

![image](https://cloud.githubusercontent.com/assets/13509546/17089962/adaaccca-51e0-11e6-99e2-ef4eff86bbb8.png)

Yandex API info for POST requests:

https://tech.yandex.com/xml/doc/dg/concepts/post-request-docpage/

API keys are private.

**Comment by bsclifton** [comment]
Per @aekeus's comment, this will need a fix to be able to handle POST:
https://github.com/brave/browser-laptop/blob/master/js/components/urlBarSuggestions.js#L431

**Comment by Liunkae** [comment]
Handling POST would also help #5235.

**Comment by bsclifton** [comment]
I've implemented general search and confirmed it's working well. I created a separate issue for tracking **search suggestions** by Yandex which can be found here: https://github.com/brave/browser-laptop/issues/5963

**Comment by htmathias** [comment]
Where's Ecosia?

[It was listed as number 3 here.](https://github.com/brave/browser-laptop/issues/1103)

**Comment by luixxiul** [comment]
I think it is just a suggestion and not decided to include it

**Comment by Liunkae** [comment]
Regardless, custom search engines (#3053—1.1.0 milestone) will solve the problem.

**Comment by luixxiul** [comment]
Exactly!

**Comment by Liunkae** [comment]
I posted a separate issue for Ecosia at #7158.
