### ISSUE TITLE
Browser closes without warning user about active download

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2707]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
There is no warning/alert displayed about active download when a user tries to close the browser.

**Expected behavior:**
User should have the option to leave the browser open to wait till the download is completed or just open a download popup window and allow the download to continue while the main browser window can be closed. 

Currently all browser throw an alert when closing the browser with active download
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Start downloading a file 
  2. close the browser when the download is active
  3. Browser closes without warning user about active download
- Screenshot if needed:
- Any related issues:
  #1515

**Comment by Liunkae** [comment]
Here are some examples:

Firefox:
![image](https://cloud.githubusercontent.com/assets/19424103/21860454/42036eea-d7f6-11e6-9885-1ec08e352f09.png)

Safari:
![image](https://cloud.githubusercontent.com/assets/19424103/21860461/4655fab2-d7f6-11e6-8ccb-7a84da50aa52.png)

**Comment by srirambv** [comment]
+1 from community  https://community.brave.com/t/downloads-progress-meter/4550/3

**Comment by jonathansampson** [comment]
+1 from me as well; just got bit by this.

Checked in Chrome, and they too warn you that there is an active download.

![image](https://user-images.githubusercontent.com/815158/28997534-d5f0ea46-79dc-11e7-9f12-fa3f8d7d59ed.png)

We could even consider adding a _Close on Complete_ option.

**Comment by Jacalz** [comment]
+1 for close on complete

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/warning-when-closing-browser-and-any-download-active/10958?u=eljuno

**Comment by bsclifton** [comment]
Fixed with [brave-core](https://github.com/brave/brave-browser) 😄 
![screen shot 2018-08-24 at 1 43 59 am](https://user-images.githubusercontent.com/4733304/44574788-3c39cf80-a73f-11e8-82b8-8df75743d2c5.png)
