### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON (serializer.js:14)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2708]
**Describe the issue you encountered:**
I get tons of ``Uncaught TypeError: Converting circular structure to JSON (serializer.js:14)`` error on console of browser level devtool.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 dev build

- Steps to reproduce:
    1. <kbd><kbd>Shift</kbd>+<kbd>F8</kbd></kbd>
    2. Open Console

- Screenshot if needed:
![screenshot 2016-07-25 18 00 22](https://cloud.githubusercontent.com/assets/3362943/17095927/d99e9602-5291-11e6-9658-c947d2b3588b.jpg)

- Any related issues: #2732 #2722

**Comment by bbondy** [comment]
Are you able to reproduce maybe with a trimmed down session-store-1 or session-store-1-dev file?  If so can you maybe share it here?

**Comment by luixxiul** [comment]
Yes, it happens even after deleting these files.

**Comment by bbondy** [comment]
so what is different? lots of people on 0.11.1 are not reproducing.

**Comment by luixxiul** [comment]
Ah sorry, I'm running dev build package

**Comment by luixxiul** [comment]
Here is the screenshot:
<img width="960" alt="screenshot 2016-07-26 0 27 12" src="https://cloud.githubusercontent.com/assets/3362943/17107358/ca26dca6-52c9-11e6-928f-594b25f4b8b3.png">

And when I click frame.js:434, I get ``windowActions.setFocusedFrame(this.props.frame)`` in frame.js

**Comment by luixxiul** [comment]
This is the latest error I get:
![web-view](https://cloud.githubusercontent.com/assets/3362943/17178321/f63893f2-544f-11e6-8798-ea8a96c3f1c3.png)
It says that something is wrong with ``web-view.js:216``.

Also the same error happens to me on ``ReactErrorUtils.js:52``.

**Comment by bbondy** [comment]
if you move your whole Brave profile dir out of the way, does it still happen?

**Comment by luixxiul** [comment]
OK, I moved ``Application Support/brave`` to the desktop, tried again, and ``web-view.js`` error is gone, but the error above https://github.com/brave/browser-laptop/issues/2708#issuecomment-234992548 still remains.

**Comment by bbondy** [comment]
tagging @bridiver @diracdeltas @bsclifton @darkdh in case they have ideas for what's going on here.

**Comment by bbondy** [comment]
I think @darkdh reproduced and is working on it.

**Comment by darkdh** [comment]
STR
![b3aipg2bbg](https://cloud.githubusercontent.com/assets/11330831/17198777/8ea3519a-54aa-11e6-92bc-07e763956e39.gif)
