### ISSUE TITLE
Download Manager displays error and the URL bar as well.

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2710]
I have noticed say that a delay to download, and also noticed that when accessing several different tabs saw a bug (as shown in the image below).

![taskbar error](https://cloud.githubusercontent.com/assets/20443574/17100123/f5e7a49c-5242-11e6-9b83-36abca7bbb87.png)

**Comment by luixxiul** [comment]
Do you still have the same issue?

**Comment by EuNlope** [comment]
Currently the error was not repeated.

**Comment by luixxiul** [comment]
OK closing, please reopen if the error is repeated
