### ISSUE TITLE
Why not implement the Speed Dial's work? (Suggestion)

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2711]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 

- Brave Version:0.11.0.1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Closing in favor of #1363
