### ISSUE TITLE
Search box, hamburger menu cannot be closed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2712]
I'm not sure STR, but sometimes it becomes impossible to close the search box which has been opened with the shortcut key. Also at the same time the hamburger menu cannot be closed by clicking the rest space inside webviewContainer. It is closed automatically by switching to another tab, but the search box is not.

0.11.1 dev build

**Comment by bbondy** [comment]
by search box you mean find in page?

**Comment by luixxiul** [comment]
Yes I do.

**Comment by luixxiul** [comment]
I think it's temporary issue, closing.
