### ISSUE TITLE
A second Ctrl-d should save-and-close the 'save bookmark' dialog

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#2713]
_Brave (0.11.1dev, 0.11.0dev); Ubuntu (16.04 LTS)._

Having just gone from v0.11.0 to v0.11.1, I notice that bookmarking with Ctrl-d now opens a 'save bookmark' dialog as with other browsers. The previous behaviour where bookmarks were created silently is preferred for situations where I'm skimming pages and bookmarking the ones I want to read more carefully after I've collected a dozen or two sources.

I concede that Ctrl-d should put up the dialog so as to be familiar to new users migrating from Chromium (and most other browsers I presume) but I've also found that the silent _hit-and-run_ style of bookmarking surprisingly valuable for my workflow. With the change, I could press Enter (or even Escape) to get the v0.11.0 behaviour but that would involve taking my left hand away from where it's most useful on the keyboard or taking my right hand off the mouse.

As a compromise, I suggest that _the dialog should respond to a second Ctrl-d with the previous behaviour_. In that way we get both the usability of standard browser behaviour while preserving the ergonomic efficiency of rapid bookmarking supported upto v0.11.0.

**Comment by CliqueBait** [comment]
14 days. Yay/nay? Good idea or no?

**Comment by bbondy** [comment]
cc @bradleyrichter but we're on a tight schedule for 1.0 so it wouldn't be prioritized anytime soon.

**Comment by bradleyrichter** [comment]
@CliqueBait If we allow an outside click to accept/close the dialog, would that keep things efficient for you? 

One issue with a second Control+D is that it may make sense to be used to remove the bookmark. I need to check the other browsers.

rough demo with outside click to close - if you want try it: https://projects.invisionapp.com/share/TK87TI5AM#/screens/179842308_Windows_10_UImock_Titlemode

**Comment by CliqueBait** [comment]
@bradleyrichter I'm not sure. I couldn't test bookmarking from within your demo.

But to give a little more context though, suppose I've just done a search with multiple promising results or I'm looking through a news site's latest articles. I'd Ctrl-click on each promising result to open a series of tabs. Next I'd Ctrl-Tab to each one to decide whether or not I want to bookmark it (based on a very brief glance for key topic phrases). So Ctrl-D (bookmark), Ctrl-W (close-tab), Ctrl-Tab (next-tab) after each interesting tab or just Ctrl-W (close-tab) Ctrl-Tab (next-tab) after each uninteresting tab. That eventually leaves me with only my search results tab open and a set of new bookmarks for pages I want to read more carefully and organise sometime later that day.

It's the speedy effortlessness of skimming through potentially interesting pages that I was finding very handy in v0.11.0
