### ISSUE TITLE
PDFJS returns CORS error when PDF is loaded directly

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2715]
611f61707bfdf6087c62c965db48339d55454a74 works around the fact that a PDF loaded directly in Brave via webview loadUrl causes a CORS error. reloading always fixes the error for me. seems like some kind of race condition with how the origin is being set.
![screen shot 2016-07-25 at 6 20 05 pm](https://cloud.githubusercontent.com/assets/549654/17120923/b660000c-529d-11e6-827e-07ad931421f5.png)

**Comment by Rob--W** [comment]
Why is the commit called "Fix PDFJS MIME type detection"? I tried hard, but couldn't relate that commit description to the code that had been committed.

I didn't look at Brave's source code, but I know that in Chrome there is an issue with granting host permissions (=setting up the origin whitelist in the renderer for the given frame) when an extension is being loaded in a `data:-URL`. For instance, when PDF.js is embedded as follows: `data:text/html,<iframe src="chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://bitcoin.org/bitcoin.pdf">`, then the same error as in your screenshot is shown. This is not PDF.js-specific, any extension suffers from it.

**Comment by diracdeltas** [comment]
@Rob--W originally, to work around this CORS issue, I added a shortcut in Brave to bypass PDF.JS's `onHeadersReceived` PDF mime type detection: 00a70f52302406ef862042970605b7dbc5fd7462. This turned out to be what was causing a bunch of 'Malformed PDF' bugs that we were seeing, including #2654. 

The CORS issue is still a mystery, but it seems to always go away when the viewer URL is reloaded, so that's the workaround for now.

**Comment by diracdeltas** [comment]
it's worth noting the CORS error never appears when a PDF is navigated to, such as by clicking a link in the page. it seems to only fire when <webview>.loadURL (http://electron.atom.io/docs/api/web-view-tag/) is called. calling <webview>.reload() fixes it.

**Comment by diracdeltas** [comment]
the `webview.reload()` workaround no longer works as of https://github.com/brave/electron/commit/21383015964b4a693ad5b29327a1629aea

**Comment by diracdeltas** [comment]
workaround fixed in https://github.com/brave/electron/commit/7e61ac2b79b6e5b04cd4a80f5fb231d4dd77d2ee
