### ISSUE TITLE
running tests on windows fail

### ISSUE THREAD

**Issue by david-gang** [brave/browser-laptop#2719]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**

> When running tests on windows i get the message
> "J:\webstorm\WebStorm 2016.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" test
> 
> > brave@0.11.1 test J:\webstorm_workspace\browser-laptop
> > NODE_ENV=test mocha --compilers js:babel-register --recursive $(find test -name '*Test.js')
> 
> 'NODE_ENV' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! Test failed.  See above for more details.
> 
> Process finished with exit code 1

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win7
- Brave Version:
  0.11.1
- Steps to reproduce:
  1.run npm test on windows
  2.
  3.
- Screenshot if needed:
- Any related issues:

The problem is described at http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman

In git bash the command works.

**Comment by bsclifton** [comment]
This is definitely a known issue and as a Windows user, it's been bugging me for a long time.

w/ GitHub shell, it fails like you have above.  You can doctor the command into two commands:
`set NODE_ENV=test`
`mocha --compilers js:babel-register --recursive $(find test -name '*Test.js'`

This will work and tests will start running.  The unit tests will work fine, there are problems at the moment w/ Spectron tests on Windows (the ones which pop up the window and use web driver to test).

What would be great would be to replace the npm test commands with a node.js script that we can use instead (which is multi-OS friendly).

**Comment by bsclifton** [comment]
Work is in progress here:
https://github.com/brave/browser-laptop/tree/windows-tests

**Comment by bsclifton** [comment]
I believe this is resolved now! (huge thanks to @bbondy, who knocked this out).  There are some errors still, but it's mostly working 😄
