### ISSUE TITLE
I can not open the browser

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2721]
I tried to open the browser but the browser does not respond when opened takes time to respond.

**Comment by tomByrer** [comment]
OSX, just updated to 10.11.06 yesterday.
I could open & use Brave yesterday after OS update, but today when I click on icon or use `open -a Brave`, it opens & immediately closes.

@EuNlope OS & version?

**Comment by luixxiul** [comment]
Closing this as it is not reproduced anymore
