### ISSUE TITLE
HTML5 PDF reader stopped working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2722]
**Describe the issue you encountered:** HTML5 PDF reader stopped working

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/611f61707bfdf6087c62c965db48339d55454a74

- Steps to reproduce: Open http://www.orimi.com/pdf-test.pdf

- Screenshot if needed:

- Any related issues:

Setting a milestone for now

**Comment by diracdeltas** [comment]
Works for me; any special settings?

**Comment by luixxiul** [comment]
It works if I move session-store-1 temporarily, so I think something is wrong with it.

**Comment by luixxiul** [comment]
This was the same issue as #2708 and I confirmed this was fixed with https://github.com/brave/browser-laptop/commit/cb3c161df82d3cc5813ebdbd539d4fed9edfe057 too. Closing.
