### ISSUE TITLE
Autocomplete pulldown with down arrow key

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2724]
**Describe the issue you encountered:** It is possible to choose my log in username from the autocomplete pulldown list with the mouse, but it also should be with the down arrow key.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/611f61707bfdf6087c62c965db48339d55454a74

- Steps to reproduce:
    1. Go to https://twitter.com
    2. Log out
    3. Select "Log in" from the top right link

- Screenshot if needed: 

- Any related issues: #2532

**Comment by luixxiul** [comment]
cc: @darkdh

**Comment by luixxiul** [comment]
I mean this case if it's not clear:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17455909/76642cc2-5c01-11e6-9330-f22c8e366e7b.png)
I would like to choose the username when I push the down arrow key there.

**Comment by darkdh** [comment]
duplicate #1302
