### ISSUE TITLE
Menu bar doesn't auto hide after selecting action (When activated using Alt key)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2731]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Menu bar doesn't auto hide after selecting action from menu items. Auto hides only after a mouse click.

**Expected behavior:**
Menu bar should automatically hide after selecting any option from the menu bar. 
Works as expected only print as it opens up a popup dialogue box
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Press Alt to enable Menu bar
  2. Select any option from File/Edit/View/History/Bookmark/Window/Help 
  3. Menu bar still remains active doesn't auto hide after selection
  4. Hides only after  a mouse click 
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Was fixed when we got rid of the titlebar
