### ISSUE TITLE
History cannot be cleared completely

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2732]
**Describe the issue you encountered:**
Though I cleared the history from menu, entries like these remain in ``session-store-1``, which prevents me from sharing the file here.
````
{"__altered":false,"_root":{"entries":[["title","PDFJS returns CORS error when PDF is loaded directly · Issue #2715 · brave/browser-laptop"],["lastAccessedTime",1469530573821],["location","https://github.com/brave/browser-laptop/issues/2715#issuecomment-235223027"],["tags",null]]},"size":4}
````
````
{"bitmap":134217730,"nodes":[{"entry":["http://www.hulu.jp",{"__altered":false,"_root":{"entries":[["flash",null],["noScript",false]]},"size":2}],"keyHash":-196217803},{"entry":["https://t.co",{"__altered":false,"_root":{"entries":[["noScript",false]],"ownerID":{}},"size":1}],"keyHash":542383989,"ownerID":null}]}
````

**Expected behavior:** All of them should be cleared

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 dev build

#2708

**Comment by bbondy** [comment]
This seems strange to me I have no mentioned of "bitmap" and some other strings you mentioned in my session-store-1.  @bridiver @diracdeltas thoughts?

**Comment by bbondy** [comment]
cc also @darkdh

**Comment by diracdeltas** [comment]
I can't repro this when I select 'clear all history'. looks like @luixxiul's session store is saving a serialization of the underlying Immutable object, ex: https://github.com/facebook/immutable-js/blob/38019326a8d006a45ef48d9c4644e23ea476d298/src/Map.js#L291.  maybe it was corrupted at some point?

**Comment by luixxiul** [comment]
It seems to have been fixed. I will reopen this when I see it happen again.
