### ISSUE TITLE
Gallery sometimes stops working on people.com

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2735]
Posting for my wife who was using macOS at the time.  Sometimes the next image button isn't working:

http://style.people.com/style/gallery/0,,20706112,00.html#style/2016/02/19/photo/touts-liberty-ross-jimmy-iovine-dupe-3196431

![screen shot 2016-07-26 at 10 37 18 pm](https://cloud.githubusercontent.com/assets/831718/17185956/2f0cf8ca-5401-11e6-8912-6596242797e9.png)

Reproducible after clicking next a few times, but not always reproducible.

Note from myself:
I am able to reproduce on first try after clicking next image twice.

**Comment by luixxiul** [comment]
I confirmed the button works fine 👍
