### ISSUE TITLE
Saved user credentials doesn't auto populate when trying to login

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2738]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Saved user credentials doesn't always auto populate in login page. Specifically when the login prompt is initiated on a different page than the main login page.

**Expected behavior:**
User credentials should auto populate irrespective from where the login is initiated.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Save user credentials for a site during first login
  2. Logout from the site
  3. Navigate to other pages where it initiate user login
  4. User credentials are not auto populated in the login screen
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Do you have some specific examples of this? I ask because the functionality seems to be working for me

**Comment by srirambv** [comment]
I can repro this on Coursera website even on 0.11.4 build. I have the credentials saved for the site.  If I visit the home page and click on signin the credentials are auto populated from the password manager. If I close the login prompt and try again it doesn't auto populate. If I navigate to another page say [for example this](https://www.coursera.org/specializations/python) and then click on login it still doesn't auto populate the credentials from the password manager. 

Sorry forgot to mention this is using Brave Password Manager.
