### ISSUE TITLE
double request for 'brave remembering password' after logging into google mail

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-laptop#2739]
**Did you search for similar issues before submitting this one?** 
yes

**Describe the issue you encountered:**
When logging into Google Mail for the first time I got two requests to remember credentials, each with slightly different message. 

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS 
- Brave Version:
- Steps to reproduce:
  1. This happened during the setup flow of the account, I haven't been able to reproduce it b/c even after deleting the password from Brave's password manager list, it no longer asks me if I want to save the credentials (which might be a bug in itself?)
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/420063/17191084/3b8341b2-53fd-11e6-9610-6b51a41dc95d.png)
- Any related issues:

**Comment by luixxiul** [comment]
I noticed it sometimes too

**Comment by diegodoval** [comment]
Another example, slightly different result

![image](https://cloud.githubusercontent.com/assets/420063/17302427/0b894baa-57d1-11e6-9ecf-397303370a70.png)

**Comment by luixxiul** [comment]
I remember someone has fixed this issue. I'm going to close this issue.
