### ISSUE TITLE
npm run watch error on Debian 8.2 jessie amd64

### ISSUE THREAD

**Issue by finchatticus** [brave/browser-laptop#274]
> brave@0.7.7 watch /home/cooper/braves/browser-laptop
> webpack-dev-server

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! brave@0.7.7 watch: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.7.7 watch script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cooper/braves/browser-laptop/npm-debug.log

[npm-debug.log.zip](https://github.com/brave/browser-laptop/files/101959/npm-debug.log.zip)

**Comment by luixxiul** [comment]
This should be fixed for now. Closing.
