### ISSUE TITLE
Reopening closed Window causes uncaught exception error

### ISSUE THREAD

**Issue by laurenancona** [brave/browser-laptop#2741]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Closing a window with multiple tabs open and selecting `Reopen Last Closed Window` causes an uncaught exception error. The correct number of tabs appear but fail to load.

**Expected behavior:**
Window reopens to page/tabs previously open before closing.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
  0.11.0
- Steps to reproduce:
  1. Open a Window with several tabs
  2. Close Window
  3. From `History` menu, choose `Reopen Last Closed Window`
- Screenshot if needed:
  ![screen shot 2016-07-27 at 4 32 44 pm](https://cloud.githubusercontent.com/assets/2152151/17191607/a22d14a4-5418-11e6-969c-0616fae177bc.png)

**Comment by bridiver** [comment]
I'm able to replicate when one of the tabs has an opener. Looks like we aren't clearing out the guestInstanceId before reloading the window @bbondy

**Comment by luixxiul** [comment]
I think this has been fixed.

**Comment by bbondy** [comment]
@bridiver pls confirm since you could replicate before, and if fixed, pls close. Thx!

**Comment by luixxiul** [comment]
Closing due to lack of information and inactivity.
