### ISSUE TITLE
HTML5 full screen mode is not working for 0.11.2.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2743]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
HTML5 full screen mode is not working for 0.11.2.  On YouTube, the video controls would disappear after the full screen control was selected.
**Expected behavior:**
When visiting a page which supports full screen functionality, the browser should allow the video to go full screen.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OSX
- Brave Version:
0.11.2 (07/27/2016 master)
- Steps to reproduce:
    1. Launch Brave from source (npm start)
    2. Visit youtube.com and open a video
    3. Attempt to select the full screen control

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Loading a video on youtube, and hovering over the video, it has a icon on the bottom right for me and when I click it, it goes to full screen.

**Comment by alexwykoff** [comment]
My bad. I was distracted by the controls disappearing that I did not notice the allow/deny banner at the top.
