### ISSUE TITLE
resources fail to load with net::ERR_CACHE_READ_FAILURE

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2744]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pages will sometimes load without stylesheets and other resources. Can be fixed with a reload.

**Expected behavior:**
Resources should load on the first try
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
  0.11.1
- Steps to reproduce:
  Intermittent and no reliable steps to reproduce
- Screenshot if needed:
- Any related issues:
  #2661

**Comment by bsclifton** [comment]
Haven't seen this in a long time
