### ISSUE TITLE
restore noscript 'allow once' functionality

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2745]

**Comment by luixxiul** [comment]
@diracdeltas when do you think this will be fixed?

**Comment by diracdeltas** [comment]
i think i can get this done for next release

**Comment by alexwykoff** [comment]
Is this intended to be inclusive of per-site settings?

**Comment by diracdeltas** [comment]
@alexwykoff yes, it takes the per-site settings into account. however, this feature is not available unless scripts are blocked globally
