### ISSUE TITLE
"Open Image in New Tab" in session tab 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2746]
**Describe the issue you encountered:**
Images opened with "Open Image in new tab" on a session tab seem to be not sharing the same session. I am not sure if it works as it should (maybe it does not make sense to open the image in a new session tab).

**Expected behavior:** Should we add "Open Image in New Session Tab" option?

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: https://github.com/brave/browser-laptop/tree/6b0d1448331b0a821a872b56e56fd48ecb0610dd

- Steps to reproduce:
    1. Open this page in a new session tab
    2. Right click my avatar and select "Open Image in New Tab"
    3. There is no user icon on the new tab

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
It should use the same session you are in, thanks for the report.
