### ISSUE TITLE
In some cases favicon is not displayed in history pulldown

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2747]
**Describe the issue you encountered:** Sometimes favicon is not displayed in history pulldown.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: https://github.com/brave/browser-laptop/tree/066adc48f3a1ce22940de2a6481b20023e16f7cb
- Steps to reproduce:
  1. Open a new tab
  2. Go to tokyo.cawaii.media/gisele/
  3. Go back with the backward button
  4. Press the forward button to display the pulldown
- Screenshot if needed:
  ![pulldown](https://cloud.githubusercontent.com/assets/3362943/17201305/35491576-54c8-11e6-89b2-87281c953746.png)
- Any related issues: #2737

**Comment by bsclifton** [comment]
Sorry for the long turn-around here @luixxiul :frowning: It looks like the space for the icon is there, but there just isn't an icon there... I might know why

If there isn't a favicon already loaded in the session (the URL to the favicon gets added to sites list via the Frame object, getting the icon property), the code will use the URL util methods to "guess" the default favicon URL. In this case, it would default to http://tokyo.cawaii.media/favicon.ico

When I visit that URL, it appears to be blank.  Is this expected?

**Comment by luixxiul** [comment]
They specify the favicon place with rel tags:
````
<link rel="shortcut icon" href="http://tokyo.cawaii.media/wp-content/themes/tokyo-cawaii-media-023/img/favicon.ico" type="image/vnd.microsoft.icon">
<link rel="icon" href="http://tokyo.cawaii.media/wp-content/themes/tokyo-cawaii-media-023/img/favicon.ico" type="image/vnd.microsoft.icon">
````
The solution here might be to seek link rel=icon tag and replace it with the default $ROOT/favicon.ico.
