### ISSUE TITLE
Building but failing Win 10 64bit

### ISSUE THREAD

**Issue by Ciandee** [brave/browser-laptop#275]
[npm-debug.zip](https://github.com/brave/browser-laptop/files/101975/npm-debug.zip)
1st sorry that the log is in zip but it was too big for pastebin

So I followed the instruction I downloaded every dependency I could look up but I keep getting this error, I really don't know what to do now.

**Comment by akhilcjacob** [comment]
I have a similar problem....
[npm-debug.zip](https://github.com/brave/browser-laptop/files/102022/npm-debug.zip)

**Comment by sl1ngblad3** [comment]
To build on Windows 10 x64 you need the following installed and you must run the commands in the install instructions from the Git Bash Prompt. I have successfully built on Windows 10 x64.

Git for Windows
Node.js for Windows x64
Nullsoft Scriptable Install System (NSIS)
Python 2.7 (newer versions of Python not supported)
MS Visual Studio Community 2015 (I did a custom install and ensured Git/Node plugins for VS were checked, make sure the Windows 10 SDK is selected to be installed as well)

Once you have the above installed you can build Brave and run it from the build folder. If you want to package it up in an installer and .nupkg for import back into VS 2015 you will need to use the makecert.exe and pvk2pfx.exe tools from the Windows 10 SDK to create a self signed .pfx cert and password or the package build will fail. Once you have the cert you put it in the browser-laptop folder and edit the build-win64-installer file to point to the cert and pass the password during the build.

**Comment by sl1ngblad3** [comment]
Make sure you select C++ for Visual Studio Community 2015 as I believe C# is the default and I'm pretty sure it's the C++ libraries that are needed to build on Windows.

**Comment by bbondy** [comment]
I use VS 2013 and it works but VS 2015 may work as well for you (It doesn't for me).   Closing this since it's a dev env setup problem because of installed dependencies.
