### ISSUE TITLE
Feature Request : Better integration with identity obfuscation systems

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2751]
Problem: Many sites require logins for user tracking.

Proposed Solution: Better integration with identity obfuscation systems (ex. Mailinator).

From the user:
'Perhaps you could give users the option to fill in a disposable email address (and open the page to view it in a new tab) instead of adding the user's actual address for "email" fields.'

**Comment by luixxiul** [comment]
I have seen a similar request on support desk
