### ISSUE TITLE
Preferences : Security Enable Adobe Flash support control is hot even though flash is not installed.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2756]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On the Preferences : Security page, the Enable Adobe Flash support control appears disabled, but can be clicked even though flash is not installed.

**Expected behavior:**
Since the control is appears disabled, it should do nothing when a user clicks on it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X.

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Launch Brave from the latest code. (Be certain that Flash is not installed for Brave)
    2. Navigate to about:preferences#security
    3. Click on the 'Enable Adobe Flash support' toggle

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
nice catch, fixing
