### ISSUE TITLE
Clear cache/history doesn't clear all state

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#2759]
See https://chromium.googlesource.com/chromium/src/+/master/chrome/browser/browsing_data/browsing_data_remover.cc
for the complete list. In particular we are not clearing the renderer memory cache or resetting webrtc ids. Some others are missing as well.
#2732

**Comment by dandart** [comment]
I'm noticing that changes in web pages aren't reflected when content is cleared either.

**Comment by bridiver** [comment]
do you have any specific examples? Could be related to the renderer memory cache not being cleared which is mentioned above

**Comment by dandart** [comment]
I pulled code to https://projectchaplin.com/ and Brave didn't reflect it until I had deleted the Application Cache/Cache directory contents. Something that would just appear and change in Chrome or Firefox (perhaps upon ctrl+shift+R sometimes).

**Comment by bridiver** [comment]
yea, this is almost certainly the renderer cache. The only way to force the reload on Brave is to click `disable cache` in the dev tools
