### ISSUE TITLE
Flash blocked image is not displaying

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2761]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting a site with flash (ex. http://www.homestarrunner.com/) an image is usually displayed to the user telling them that flash is blocked.

**Expected behavior:**
The image displays and the user can enable flash via the context menu.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.11.2
- Steps to reproduce:
  1. Launching from the code, visit http://www.homestarrunner.com/
  2. Notice a plain black screen with an empty box in the middle.
- Screenshot if needed:
  0.11.1 - <img width="1440" alt="screen shot 2016-07-28 at 5 19 12 pm" src="https://cloud.githubusercontent.com/assets/1434040/17231608/9f072910-54e8-11e6-9928-8c22f3641a42.png">

0.11.2 - 
![screen shot 2016-07-28 at 5 19 12 pm 2](https://cloud.githubusercontent.com/assets/1434040/17231619/acf66158-54e8-11e6-8f4c-fac33b3b8a2a.png)
- Any related issues:

**Comment by alexwykoff** [comment]
cc @diracdeltas

**Comment by diracdeltas** [comment]
It's working for me on master - which commit are you testing from?

**Comment by alexwykoff** [comment]
I first noticed it with b8f3515bc8e258a2ea1ac7d61434aa313cdc37fb and just repro'd with af7ffb146bdcdac78d477e961f6ad646eda4d451.

**Comment by diracdeltas** [comment]
any console errors?

**Comment by alexwykoff** [comment]
There is a message about 'got too-small Flash element', however when I went to repro with the built versions in /release it showed the image perfectly.

I'm going to label this info-needed (investigation) and assign it to myself. If I'm the only one seeing this and only when I launch from source, it's not a production issue.

**Comment by diracdeltas** [comment]
the too-small flash element messages are not actually an error, just info btw

**Comment by luixxiul** [comment]
I'm going to close this as stale.
