### ISSUE TITLE
Icon of installer should be different

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2763]
**Describe the issue you encountered:** Icon of installer should be different from the installed program. There are some people who confuse them and send a feedback like "I have to install Brave every time to start it".

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.11.1
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17234969/4e0046b0-5578-11e6-8bea-1a223bac0840.jpg)

On the left is the shortcut, on the right is the installer.

**Comment by bsclifton** [comment]
Closing; this was replaced in 0.12.6 by this commit:
https://github.com/brave/browser-laptop/commit/6ad5529ae3d32200f436262a93d128f9146b8219
