### ISSUE TITLE
Smoother animations tracking bug for 0.11.2

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2765]
https://github.com/brave/browser-laptop/pull/2706

**Comment by luixxiul** [comment]
Concerning tab preview/transition https://github.com/brave/browser-laptop/issues/2062 seems to happen again.

**Comment by bbondy** [comment]
just spawn a new issue for that thx.

**Comment by luixxiul** [comment]
I think @cezaraugusto is working on it already https://github.com/brave/browser-laptop/pull/2780#issuecomment-236103518
