### ISSUE TITLE
Brave crashes when opened: macOS 10.11.6

### ISSUE THREAD

**Issue by keithboone1** [brave/browser-laptop#2766]
**Describe the issue you encountered:**

I installed the new version of El Capitan this morning and now Brave will crash as soon as it opens--I see it open, but then the window instantly closes and the application quits. I uninstalled Brave, downloaded a fresh copy, and reinstalled but it didn't fix the issue. I assume the El Capitan updates are responsible, though it could be coincidence.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS 10.11.6

- Brave Version: 0.11.1

- Steps to reproduce:
    1. Open Brave through any means

- Screenshot if needed:

- Any related issues:

**Comment by neeklamy** [comment]
I’m using OS X 10.11.6 too, but with no problems. It’s likely a setting or cached file.

Try moving the `~/Library/Application Support/brave` directory aside and then launching Brave.

If that doesn’t work, there’s a number of other files and directories that it would be worth deleting:

 - ~/Library/Caches/com.electron.brave
 - ~/Library/Caches/brave
 - ~/Library/Application Support/com.electron.brave.ShipIt
 - ~/Library/Saved Application State/com.electron.brave.savedState

**Comment by keithboone1** [comment]
Thanks for the response! I actually just got back from work now and tried to open Brave and it worked just fine. Didn't change anything since before so I don't know what was going on. I'll try those if it happens again and report what worked.
