### ISSUE TITLE
Bookmark folder is created left of bookmark item, not right

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2771]
**Describe the issue you encountered:** Bookmark folder is created left of a bookmarked item. It's the same after moving `brave` folder in `AppData\Roaming`.

**Expected behavior:** It should be created right of the item
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit
- Brave Version: 0.11.2 Beta1
- Steps to reproduce:
  1. Bookmark https://github.com from the bookmark toolbar
  2. Create a bookmark folder
- Screenshot if needed:
- Any related issues: #2768

**Comment by bbondy** [comment]
Valid bug, but it won't block 0.11.2 release.  It seems to always put it at the right spot except when it is the last item it puts it second last.

**Comment by anseljh** [comment]
I noticed this too. New bookmark folders seem to always be put in the next-to-last position.

**Comment by alexwykoff** [comment]
@bradleyrichter this is worth a moment of design thought. Perhaps all folders should go to the far left of the bookmarks tray?

**Comment by bradleyrichter** [comment]
Appearing on the left is the Safari way. Appearing on the right is the Chrome/Firefox way.

On a crowded bar, the Left approach insures that it can be seen when added. But the cost is pushing things into the chevron menu.

Following the most popular browsers usually creates less user friction even when there is a slightly better way. So on this one, let's fix this bug, and follow chrome/FX.

**Comment by anseljh** [comment]
Just to make sure you guys are understanding the bug:

* I start with N items on my bookmarks bar.
* I right-click the bookmarks bar and select "Add Folder..."
* I type in a name for my new folder ("Stuff") and click "Save".
* My new "Stuff" folder is in the Nth position. The item that was previously Nth is now N+1th.

![image](https://cloud.githubusercontent.com/assets/2075772/17903068/ebbc196a-691e-11e6-9b24-4dc3640b6e6e.png)

![image](https://cloud.githubusercontent.com/assets/2075772/17903094/10f6f0ec-691f-11e6-9076-3e286ea52aa9.png)

What makes sense *to me* is to always place the new item last (N+1th), and then let the user move it somewhere else if they want to.

**Comment by bradleyrichter** [comment]
@anseljh yes, understood. 

@alexwykoff was suggesting/questioning changing the behavior which would also fix this bug. But I am suggesting that we fix it as you explained. New items should be last. Not second-last.

**Comment by alexwykoff** [comment]
Still an issue in 0.13.0

![add_bookmark_folder_left](https://cloud.githubusercontent.com/assets/1434040/21625067/7ed15904-d1cf-11e6-9c7d-c9355f8eb711.gif)

**Comment by bradleyrichter** [comment]
Nice use of my novel in-screen-shot messaging approach!

**Comment by NejcZdovc** [comment]
This should be fixed in #2771

**Comment by luixxiul** [comment]
#2771 is fixed with #2771??

**Comment by NejcZdovc** [comment]
Inception :smile: Sorry I wanted to say #9979

**Comment by srirambv** [comment]
QA blocked on #11728
