### ISSUE TITLE
Reloading view-source: page displays the page, not the source

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2772]
### Description

Reloading `view-source:` page displays the page, not the source.

### Steps to Reproduce

  1. Select `View Page Source` from context menu
  2. Reload the page

**Actual result:**

The page is not rendered.

**Expected result:**

The source code should be reloaded.

**Reproduces how often:**

### Brave Version

**about:brave info:**

0.11.2 Beta1

**Reproducible on current live release:**

Yes.

### Additional Information

#2768

**Comment by luixxiul** [comment]
not suffix, it's prefix :-D

**Comment by bbondy** [comment]
valid but doesn't need to block 0.11.2

**Comment by Aeyoun** [comment]
This problem also causes pages displayed with view-source to show the original page when reloaded.

1. Open view-source:https://www.example.com
2. Press Reload

Expected: Reload the source code view.

Actual: Loads the web page instead.

**Comment by luixxiul** [comment]
It should have been addressed #320 fyi

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/reopening-a-closed-view-source-tab-opens-up-the-page-and-not-the-source/5612

>When I click view source on a page in the context menu and close the tab with cmd+W, then reopen it with cmd+shift+T brave opens the website and not the source view.

**Comment by mlhaufe** [comment]
Still exists as an issue on version 0.19.88

**Comment by bsclifton** [comment]
This appears to have been fixed
