### ISSUE TITLE
Download history is cleared by restarting

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2773]
**Describe the issue you encountered:** Downloads history is cleared by restarting

**Expected behavior:** it should be preserved until I clear it by myself

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.2 Beta1

- Steps to reproduce:
    1. Download this page
    2. Restart
    3. Open about:downloads

- Screenshot if needed:

- Any related issues: #2768

**Comment by bbondy** [comment]
Is your option to clear downloads on close in preferences on?
For me it is off and it doesn't clear.

**Comment by luixxiul** [comment]
Yes I think it was, sorry.

**Comment by alexwykoff** [comment]
I was able to repro this on OS X with 275a3431cdbb61d5fe57fcadb08f0eeddb0c9e41. All four of my 'clear data' toggles were off.
