### ISSUE TITLE
Display menubar on hover in fullscreen mode (on Windows)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2775]
**Describe the issue you encountered:** Display menubar on hover in fullscreen mode. Unlike Mac, Windows does not show you a menubar when you hover the top part of the window. You cannot escape from fullscreen mode UNLESS either you push <kbd>F11</kbd> or kill the program.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64bit
- Brave Version: 0.11.2 Beta1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues: #2768

**Comment by bbondy** [comment]
I think that would be helpful to people. Also this related one:
https://github.com/brave/browser-laptop/issues/2394

**Comment by bsclifton** [comment]
No menu shown on Windows in [brave-core](https://github.com/brave/brave-browser)
