### ISSUE TITLE
Are default bravery settings applied to sites with no settings?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2776]
**Describe the issue you encountered:** When I was doing a test that about:preferences default Bravery settings take effect on pages with no site settings, I noticed that the sites are not reloaded after changing the settings. Is it OK?

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.2 Beta1

- Steps to reproduce:
    1. Visit https://google.fi (or anywhere you haven't been)
    2. Change Bravery defaults on about:preferences, say Cookie Control to "Allow All Cookies"
    3. On Bravery panel on google.fi the value has been changed to it, but it is not clear the change was actually applied

- Screenshot if needed:

- Any related issues: #2768

**Comment by diracdeltas** [comment]
I don't think changing about:preferences should reload every page, it would be a lot of reloads for people who have many tabs open

**Comment by luixxiul** [comment]
How about reloading only a page which is selected after that?

**Comment by bbondy** [comment]
Ya I don't think we should reload it would lead to some unexpected behaviour sometimes.  I think most people will understand that this blocking happens when a page is loading and not when already loaded.
