### ISSUE TITLE
PDF.js keeps reloading and file is not displayed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2777]
**Describe the issue you encountered:** PDF.js keeps reloading and content is not displayed.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7/10

- Brave Version: 0.11.2 Beta1

- Steps to reproduce:
    1. Open http://www.orimi.com/pdf-test.pdf
    2. PDF reader keeps reloading at the same timing
    3.

- Screenshot if needed:

- Any related issues: #2768 #2769

**Comment by diracdeltas** [comment]
pretty sure this is caused by 611f61707bfdf6087c62c965db48339d55454a74. the PDF won't load, but the redirect loop can be solved by having a counter that gives up after 1 or 2 redirects.

**Comment by luixxiul** [comment]
Not fixed for Windows 10 32 bit JP

#2769

**Comment by diracdeltas** [comment]
@luixxiul is the file reloading infinitely or just not displayed?

**Comment by luixxiul** [comment]
@diracdeltas let me check this again in beta2

**Comment by srirambv** [comment]
@diracdeltas It goes on an infinite loop. This is on Win-10 64 bit as well.

**Comment by diracdeltas** [comment]
@srirambv on beta2?

**Comment by srirambv** [comment]
No Beta1. my bad.

**Comment by luixxiul** [comment]
on macOS with the latest commit it reloads just two times and then stops reloading.

**Comment by bbondy** [comment]
I think this is fixed, we just don't have a beta2 build yet, so closing this.

**Comment by alexwykoff** [comment]
Looks good!
