### ISSUE TITLE
Start searching bookmarks as soon as characters are typed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2778]
**Describe the issue you encountered:** It should be nice if bookmark search is started when I type characters on about:bookmarks. I have to select the input field first to start searching

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows7

- Brave Version: 0.11.2 Beta1

- Steps to reproduce:
    1. Open about:bookmarks
    2. Type something
    3. Bookmark search should start

- Screenshot if needed: #2768 #2906 

- Any related issues:

**Comment by MKuenzi** [comment]
Can anyone point me to guidance on debugging the react components?

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/blob/master/docs/debugging.md

**Comment by bbondy** [comment]
You wan the shift+f8 dev tools which will allow you to set breakpoints in the code.
