### ISSUE TITLE
too much padding on nextTab button

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#278]
It looks like there is too much space between nextTab and the add tab button.

![screen shot 2016-01-23 at 12 58 10](https://cloud.githubusercontent.com/assets/549654/12532839/8ba059d6-c1d2-11e5-896b-c329d8e7f3f1.png)

the prevTab button also looks to me like it should be closer to the edge of the window.
![screen shot 2016-01-23 at 13 10 37](https://cloud.githubusercontent.com/assets/549654/12532848/cd31c89e-c1d2-11e5-8cc5-3d31b3141999.png)

**Comment by diracdeltas** [comment]
Here's what the tabbar looks like on a small screen after the latest changes. Better but I still feel like the padding on the next/prev tab buttons is too large. @bradleyrichter please advise.
![screen shot 2016-01-26 at 16 39 56](https://cloud.githubusercontent.com/assets/549654/12600070/a1533138-c44b-11e5-9f44-1eb24834fbd8.png)

**Comment by bradleyrichter** [comment]
yeah, it's too big. The padding should be just a few pixels beyond the hover state...And this will change a bit when we implement the new tab sizing approach.

Current 
![2much_padding](https://cloud.githubusercontent.com/assets/13509546/12600542/7b951afc-c44f-11e5-9db4-4fac975db578.png)

Better (with larger Add button as well)
![2much_padding_fixed](https://cloud.githubusercontent.com/assets/13509546/12600563/9967fa68-c44f-11e5-9fff-9f746150468b.png)

**Comment by luixxiul** [comment]
According to the discussion on #317 the issue was fixed already. Closing.
