### ISSUE TITLE
Bravery global/site settings on about:preferences

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2781]
**Describe the issue you encountered:** When you select Bravery global/site settings from menubar on about:preferences, a new tab is opened 

**Expected behavior:** It should open about:preferences#shields in the same tab
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7
- Brave Version: 0.11.2 Beta1
- Steps to reproduce:
  1. Open about:preferences
  2. Select bravery global or site settings from menubar
- Screenshot if needed:
- Any related issues: #2768 #2862

**Comment by bbondy** [comment]
This is related to handling with the `singleFrame: true` option I believe.  It should get the base URL without the `#shields` and consider it a same frame.

**Comment by luixxiul** [comment]
I think this is no longer valid (`Bravery global/site settings` has been removed from menubar). Closing.
