### ISSUE TITLE
Autocomplete list in URL bar on small window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2782]
**Describe the issue you encountered:** On a small window there are some issues on the autocomplete list in URL bar
- "Bookmark" label is not displayed in the autocomplete list, circulating the list with up/down keys. 
- Mouse pointer is too "responsive" to circulate them with the mouse wheel

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit
- Brave Version: 0.11.2 Beta1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17240015/7a3b3714-55a3-11e6-9751-406fda91c0ee.jpg)
- Any related issues: #2768

**Comment by luixxiul** [comment]
This still happens and is annoying when selecting an item with a mouse scroll because the pointer is always active and it interferes with items in the pulldown. STR: 1) browse and create bookmarks enough for the scroll bar to show up, 2) make the size of the browser as small as you can, 3) put a word in the URL bar to get the pulldown, 4) scroll with a mouse wheel.

**Comment by bsclifton** [comment]
Works great on [brave-core](https://github.com/brave/brave-browser) 😄 (ex: list will go outside the bounds of the window)
![screen shot 2018-08-29 at 10 36 30 pm](https://user-images.githubusercontent.com/4733304/44831582-0764c700-abdc-11e8-937e-41cab6403a2d.png)
