### ISSUE TITLE
Brave does not recognize flash on Arch-based distros

### ISSUE THREAD

**Issue by ConorIA** [brave/browser-laptop#2784]
On the Arch-based Manjaro distro, the option to enable flash is greyed-out even when the aur packages chromium-pepper-flash or chromium-pepper-flash-standalone are installed. These, along with chromium-pepper-flash-dev are the only three pepper flash packages available. 

The plugin is installed to /usr/lib/PepperFlash/libpepflashplayer.so

**Comment by luixxiul** [comment]
Flash on Linux is not yet available, if I'm not wrong

cc: @diracdeltas

**Comment by diracdeltas** [comment]
@ConorIA does something like `/usr/lib/PepperFlash/manifest.json` exist?

**Comment by diracdeltas** [comment]
but maybe it's not supported on linux anyway? https://cs.chromium.org/chromium/src/chrome/common/chrome_paths.cc?sq=package:chromium&dr=C&rcl=1469791693&l=304 cc @bbondy

**Comment by diracdeltas** [comment]
@ConorIA please test out 07cb9f4 if you can, thanks

**Comment by ConorIA** [comment]
Wow, that was fast! Thank you. :)

I am currently building the brave-git package through aur. I will report back as soon as it is compiled and installed. 

And yes, the file you mentioned is present. 

```
# pacman -Ql chromium-pepper-flash
chromium-pepper-flash /usr/
chromium-pepper-flash /usr/lib/
chromium-pepper-flash /usr/lib/PepperFlash/
chromium-pepper-flash /usr/lib/PepperFlash/libpepflashplayer.so
chromium-pepper-flash /usr/lib/PepperFlash/manifest.json
chromium-pepper-flash /usr/share/
chromium-pepper-flash /usr/share/licenses/
chromium-pepper-flash /usr/share/licenses/chromium-pepper-flash/
chromium-pepper-flash /usr/share/licenses/chromium-pepper-flash/license.html
```

**Comment by ConorIA** [comment]
Can confirm: issue resolved!

![screenshot from 2016-07-29 18-41-59](https://cloud.githubusercontent.com/assets/870746/17265356/3e8e33c4-55bc-11e6-946c-39036341f2f8.png)

**Comment by ConorIA** [comment]
Seems this is broken again as of 0.12.0.
