### ISSUE TITLE
Clone tab on different tab always clones the active tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2787]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clone tab on different tabs always clones the first cloned tab

**Expected behavior:**
Clone tab should clone the specific tab on which the option was selected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2 Dev Beta1

- Steps to reproduce:
    1. Clone from an existing tab
    2. Cloned tab opens next to the original tab
    3. Clone a new tab which is already open
    4. The same cloned tab opens again rather than the new tab on which clone was selected.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Is it the same even though you navigate to a different page on the opened tab? If so it sounds like a problem.

**Comment by srirambv** [comment]
No if navigated to different page then there is no problem. But if you clone a tab and don't navigate to any other page but try to clone a different tab then it still clones the first tab.

**Comment by srirambv** [comment]
Clone tab is working only on active tab not the other tabs. Even if you clone other tab it opens a clone tab of the active tab.

**Comment by luixxiul** [comment]
I confirmed it too. Linking to #2768

**Comment by alexwykoff** [comment]
I'm seeing some slightly unexpected behavior on this one. Tested with 275a3431cdbb61d5fe57fcadb08f0eeddb0c9e41 

![attack_of_the_clones](https://cloud.githubusercontent.com/assets/1434040/17308591/7021d8fa-5800-11e6-9c0d-92402f28f202.gif)

**Comment by luixxiul** [comment]
An inactive tab cannot be cloned actually until I select the tab and make it active.

**Comment by bbondy** [comment]
that's a valid bug and has to do with cloning unloaded tabs but is out of scope for this task, please file a new task for that. Nice find!

**Comment by bbondy** [comment]
assuming this is only for unloaded tabs like @luixxiul said? If not pls re-open.

**Comment by luixxiul** [comment]
@bbondy yes exactly :-)
