### ISSUE TITLE
Page shrinks and resizes on load

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2788]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On page load the page view shrinks and then resizes it automatically

**Expected behavior:**
Page should load normally
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.2 Dev Beta1
- Steps to reproduce:
  1. 
     2.
     3.
- Screenshot if needed:
  Shows the effect on three sites. 
  ![ezgif-4065124029](https://cloud.githubusercontent.com/assets/17010094/17241485/d10a3d0e-5569-11e6-89c8-454122a49be8.gif)
- Any related issues:

**Comment by bbondy** [comment]
@alexwykoff @luixxiul do either of you reproduce this?

**Comment by alexwykoff** [comment]
Tried af7ffb146bdcdac78d477e961f6ad646eda4d451 on OS X and Win7 x64 but could not reproduce.  Any chance that this is accidental zoom via a mouse scroll wheel or something similar?

**Comment by srirambv** [comment]
No. Happens even without mouse connected to machine.

**Comment by luixxiul** [comment]
Yes I can reproduce this on Windows 10 32 bit, on twitter.com

**Comment by luixxiul** [comment]
I cannot reproduce this on Windows 10 with 0.11.2 RC1. Will you please check it? /cc: @srirambv

**Comment by srirambv** [comment]
Still happening for me with 0.11.2 RC1 on Windows 10 machine.

**Comment by luixxiul** [comment]
Closing as stale.
