### ISSUE TITLE
[Suggestion] Browser version for distro Manjaro

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#2789]
I wish I had a version of the Brave GNU \ Linux Manjaro.

**Comment by luixxiul** [comment]
Do Brave-Linux.tar.bz2, brave-0.11.4.amd64.rpm, or brave_0.11.4_amd64.deb not work on Manjaro linux? Brave works on Arch Linux, so it should work there too. https://github.com/brave/browser-laptop/releases

**Comment by EuNlope** [comment]
Return to Windows, to return to using the Manjaro will download.
