### ISSUE TITLE
Webpack dependency

### ISSUE THREAD

**Issue by morodeer** [brave/browser-laptop#279]
I've tried to install brave with `sudo npm cache clear` and then `npm install`, and got this one. 
```
../src/statement.cc:724:5: note: in expansion of macro ‘STATEMENT_BEGIN’
     STATEMENT_BEGIN(Reset);
     ^
  SOLINK_MODULE(target) Release/obj.target/node_sqlite3.node
  COPY Release/node_sqlite3.node
  COPY ../lib/binding/node-v47-linux-x64/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Выход из каталога `/home/morodeer/BraveBrowser/node_modules/sqlite3/build'
done
sh: 1: webpack: not found
```

Installing webpack (`npm install webpack -g`) solved the problem. Maybe some dependency is missing? 
Log included. Ubuntu 14.04. 
[npm-debug-before.txt](https://github.com/brave/browser-laptop/files/102035/npm-debug-before.txt)

**Comment by bbondy** [comment]
How did you clone originally? I thought that dev-deps were always installed before deps
We do list it in our dev dependencies.

If you want to troubleshoot further, or for the next person:
Try upgrading to npm 3.5.2, node 5.5 and node-gyp 3.2.1

**Comment by yorchv** [comment]
To avoid installing packages globally you can do
```
export PATH="./node_modules/.bin:$PATH"
```

**Comment by bbondy** [comment]
by the way, I don't have webpack installed globally and it's working for me

**Comment by morodeer** [comment]
@bbondy , I've used shallow clone: 
```
# For beta testers:
git clone --depth 1 https://github.com/brave/browser-laptop
```

I'll try it with latest versions later. 

I think the problem was that webpack wasn't installed at all. It was just my choice to install it globally.

**Comment by luixxiul** [comment]
This should be fixed for now. If not please follow the latest instruction and leave a log here. Closing.
