### ISSUE TITLE
[Suggestion] Auto close download bar when the downloaded file is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2791]
Close the download bar automatically when a downloaded file is opened by double clicking on the item. If a new download is initiated the opened file should not be listed in the download bar. Should only display the new active download.

**Comment by bbondy** [comment]
I don't think we want it to auto close just by opening. Do other browsers do that?  Maybe tweaking what is shown if you do explicitly close then re-open though.

**Comment by srirambv** [comment]
Currently only chrome has the download bar feature but it doesn't hide the download bar if a file is opened

**Comment by bbondy** [comment]
I think this would maybe work if there is only exactly 1 download item on your bar.  But I often download a few files at the same time and then open one and wouldn't want it to close.

**Comment by NejcZdovc** [comment]
Can we implement it like this?

When you double click on an item, item is opened and selected item (not bar) is cleared from the download bar.

**Comment by srirambv** [comment]
>When you double click on an item, item is opened and selected item (not bar) is cleared from the download bar.Chrome has it like this and I miss it here 

+1 on this.
