### ISSUE TITLE
Bookmark icons cluttered display when Show Favicon is enabled.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2792]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling show favicon in the settings page clutters the icons in the bookmark bar. 

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.1. & 0.11.2 x64
- Screenshot if needed:
  ![bookmarkbar](https://cloud.githubusercontent.com/assets/17010094/17248896/3bec5154-5595-11e6-84e1-aeba684bd9d6.PNG)
- Any related issues:

**Comment by bbondy** [comment]
Could you do 2 bugs, one for cluttering, you can mark good first bug label and one for icons not appearing (that one might already exist).  Please modify this and create a new one accordingly, thx!

**Comment by srirambv** [comment]
@bbondy Done. But I do not have access to add labels to the threads.

**Comment by bbondy** [comment]
Fixed, see here: https://github.com/brave/browser-laptop/invitations

**Comment by bsclifton** [comment]
The clipping should have been fixed by @ayumi with https://github.com/brave/browser-laptop/pull/2980

@srirambv can you re-check and let us know what the expected behavior should be?

**Comment by srirambv** [comment]
Clippings fixed but the complete list of bookmarks are not visible.  Should have an arrow to indicate more bookmark list is available.

![image](https://cloud.githubusercontent.com/assets/17010094/17832145/d508fe0e-66f3-11e6-86d5-d4c251db28d0.png)

Also in about:bookmarks if there are too many nested folders it clips the folder names and overlaps on the bookmark entry when scrolled .
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17010094/17832236/c2374a0e-66f5-11e6-9783-9348e21c97fe.gif)

**Comment by mijiturka** [comment]
All of these seem to be fixed in Brave 0.20.42, on Linux at least.

**Comment by bsclifton** [comment]
I do believe this is fixed and will close- thanks for the update, @mijiturka 😄
