### ISSUE TITLE
Polldaddy polls not showing up

### ISSUE THREAD

**Issue by v18** [brave/browser-laptop#2794]
I noticed in previous issues that you were able to make sure that legitimate scripts were being displayed.

I saw that embedded Polldaddy polls, surveys, and ratings are not being displayed by Brave. You can try it out by adding this code to your site:

Poll

```
<script type="text/javascript" charset="utf-8" src="http://static.polldaddy.com/p/9485470.js"></script>
<noscript><a href="http://polldaddy.com/poll/9485470/">Brave poll</a></noscript>
```

Survey

```
<div class="pd-embed" id="pd_1469800913"></div>
<script type="text/javascript">
  var _polldaddy = [] || _polldaddy;
  _polldaddy.push( {
    type: "iframe",
    auto: "1",
    domain: "wpval.polldaddy.com/s/",
    id: "brave-survey",
    placeholder: "pd_1469800913"
  } );
  (function(d,c,j){if(!document.getElementById(j)){var pd=d.createElement(c),s;pd.id=j;pd.src=('https:'==document.location.protocol)?'https://polldaddy.com/survey.js':'http://i0.poll.fm/survey.js';s=document.getElementsByTagName(c)[0];s.parentNode.insertBefore(pd,s);}}(document,'script','pd-embed'));
</script>
```

Rating

```
<div id="pd_rating_holder_8424648"></div>
<script type="text/javascript">
PDRTJS_settings_8424648 = {
"id" : "8424648",
"unique_id" : "default",
"title" : "",
"permalink" : ""
};
(function(d,c,j){if(!document.getElementById(j)){var pd=d.createElement(c),s;pd.id=j;pd.src=('https:'==document.location.protocol)?'https://polldaddy.com/js/rating/rating.js':'http://i0.poll.fm/js/rating/rating.js';s=document.getElementsByTagName(c)[0];s.parentNode.insertBefore(pd,s);}}(document,'script','pd-rating-js'));
</script>
```

**Expected behavior:**

I expected to be able to see the Polldaddy content on Brave.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Mac OS X 10.11.6
- Brave Version:
  0.11.1
- Steps to reproduce:
  1. Add the code to your site
  2. View your site on Brave
  3. See that the Polldaddy code is not displayed

Let me know if you need any more info :)

**Comment by neeklamy** [comment]
@v18, I’ve put all of your code samples into a [Plunker, Testing embedding Polldaddy polls, surveys, and rating widgets](http://run.plnkr.co/plunks/dx9zcCj7CZg4xw7vxM7c/).

The embed codes work if Brave’s  Ad Control is switched to “Allow ads and Tracking”.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-polldaddy-com/10093

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

**Comment by v18** [comment]
@luixxiul thanks! I replied at https://community.brave.com/t/discussion-polldaddy-com/10093
