### ISSUE TITLE
Bug and Suggestion: Allow disabling smooth scrolling because it can create tearing in Brave

### ISSUE THREAD

**Issue by CountLesnik** [brave/browser-laptop#2795]
**Describe the issue you encountered:**
A change done by the Chromium team has broken for quite some configurations smooth scrolling, the affected users see scrolling artifacts or some kind of weird screen tearing, either with or without hardware acceleration enabled. Solution found in quite many recent postings on different sources is that deactivating smooth scrolling can remove that glitches.

**Expected behavior:**
Brave should offer the option to disable smooth scrolling, so users who are affected by screen tearing/scrolling artifacts can get rid of that visual glitches

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 8/Windows 7/Windows 10 - all 64 Bit

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Having either some Nvidia graphics cards or some integrated Intel HD which are affected
    2. Go to a web page and scroll
    3. tearing/artifacts/glitches do appear

- Screenshot if needed
https://t.co/HiVJz6uTyG

**Comment by luixxiul** [comment]
how about disabling hardware acceleration?

**Comment by CountLesnik** [comment]
Does not work. It worked until Chromium 52, before Google decided to remove the whole GDI rendering code.

**Comment by SJ-Diamond** [comment]
Having the same problem. If i open a webpage with a dark background, open a link on that tab and go back to the origin link, scrolling produces annoying white lines.

**Comment by AXVDM** [comment]
Got 2 days ago one of that nice machines here **(INTEL NUC Office SSD, HD Graphics 4400, NUC Intel Core i3-4010U, 2x 1.70GHz, Windows 7 Professional 64 Bit)**  updated all drivers and installed that new version so far not released for the general update channel.

Seeing that mentioned tearing effect appearing, quite heavy ones if i activate hardware acceleration and not so much annoying ones if i deactivate hardware acceleration.

It is definitely related to special graphic chips, especially the Intel HD integrated graphics solutions. As things are right now, it is impossible to get a glitch free experience in Brave with Chromium 52 if you have a machine with such a graphics solution.

**Comment by diracdeltas** [comment]
@CountLesnik @SJ-Diamond @Axvedma if you can, please test out https://github.com/brave/browser-laptop/pull/2846, thanks

**Comment by CountLesnik** [comment]
@diracdeltas 

Works now, no glitches without smooth scrolling. Although it would be nice to be able to use smooth scrolling again without that annoying tearing effect.

Ideas?
