### ISSUE TITLE
disabled shield switches with shields off are still causing reload/state change

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2797]
First, turn off the sub shields, then turn off the master shields switch.

![image](https://cloud.githubusercontent.com/assets/13509546/17252363/516d1baa-5561-11e6-9472-616b34f44ad6.png)

Now click "block scripts" switch. Switch is enabled (without visual indication) and page reloads with scripts blocked. (see number)

![image](https://cloud.githubusercontent.com/assets/13509546/17252474/b7da7e3c-5561-11e6-84e0-ce3308a17ada.png)

CC @bbondy 

- Any related issues:

**Comment by alexwykoff** [comment]
Looks good!
