### ISSUE TITLE
location.reload() does not reload the page title

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2798]
**Describe the issue you encountered:** ``location.reload()`` does not reload the page title.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.2 Beta1

- Steps to reproduce:
    1. Open devtool
    2. ``location.reload()``

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I think when the page has no title?

**Comment by luixxiul** [comment]
But https://github.com/notifications has the title "Notifications" and it is displayed until I click the bell.

**Comment by neeklamy** [comment]
I’ve created a Plunker to demonstrate the issue, the problem arises with links that point to the page that we are already on (anchor links are fine though), http://run.plnkr.co/hR0BbNdsABIWodEu

![Brave tab title breaks](https://cloud.githubusercontent.com/assets/155358/17269395/e9273880-563e-11e6-87e0-c051b7e17caa.gif)

**Comment by neeklamy** [comment]
I’ve created a Plunker to demonstrate the issue, the problem arises with links that point to the page that we are already on (anchor links are fine though), http://run.plnkr.co/6zO5uXU1UtrHS2fN

![Brave tab title breaks](https://cloud.githubusercontent.com/assets/155358/17269395/e9273880-563e-11e6-87e0-c051b7e17caa.gif)

**Comment by luixxiul** [comment]
FYI reloading with the button next to the URL bar does work.

**Comment by neeklamy** [comment]
@luixxiul, I’ve tried to link directly to the Plunker (but it’s being a bit of a [plonker](https://english.stackexchange.com/questions/120462/why-are-you-a-plonker), and the URL keeps changing, despite being “frozen” – *hahaaa*).

If that doesn’t work, go to the Plunker: http://plnkr.co/edit/XG9Wt19x0zvMF3WM78rR?p=preview and click the fullscreen widget on the preview pane, that will open the preview in a new window.

**Comment by bbondy** [comment]
Is this diff from 0.11.1?

**Comment by neeklamy** [comment]
>Is this diff from 0.11.1?

I’m still using 0.11.1, it’s the same.

**Comment by willy-b** [comment]
The absolute link in @neeklamy's Plunker repros the bug for me on Ubuntu 14.04 foor recent master (commit 9213bf0f356dcf0dabb3db8bc1e256a6cc9b0f10).

**Comment by luixxiul** [comment]
The easiest way to reproduce this:

1. Open devtool
2. ``location.reload()``

**Comment by luixxiul** [comment]
This seems to have been fixed with #3200. I cannot confirm this issue in 0.11.6 beta2, so closing.
