### ISSUE TITLE
Define a pattern for transitions, animations and overall input responses

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#2800]
It would be a great benefit for Brave to have a pattern for overall UI polishment.

Since the project relies on React, it's often hard to create transitions for dynamic content, where `@keyframes` came to help. It's also unclear how each interaction should behave, since every element have a different behavior, which is currently undocumented. It makes contributions arbitrary and may not fit the project expectations, which may lead to a rework for both parts (team and contributors).

I think setting variables for each used element and setting default animations for components could help current and future contributors to find gaps more easily and make contributions more solid, without a deeper review.

At the moment I think the current style sheet organization is great, but we need to set a standard for repeated values and things like `transition-duration`, `timing`, `delay`s, so on, and organize it accordingly. It can be also documented on code where variable X should be used, and plus have an overall cleanup on things that is not standardized.

This said, given the team's guidance I can work on making it real.

/cc @bbondy @bradleyrichter

**Comment by bradleyrichter** [comment]
I agree completely. This would be very useful while we refine the total UI, adding consistency and efficiency for all involved.

**Comment by bsclifton** [comment]
Closing as I think these requirements can all be captured in [Brave UI](https://github.com/brave/brave-ui) 😄
