### ISSUE TITLE
Bookmark highlight disappears when a bookmaked link is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2801]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
The bookmark icon next to URL looses its orange highlight when the link is opened.

**Expected behavior:**
Should retain the bookmark status when opened. Should loose the highlight when navigated to other link form the bookmarked page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2 Dev Beta1

- Steps to reproduce:
    1. Open any bookmarked URL 
    2. Keep the cursor on the URL 
    3. The bookmark star becomes gray doesn't retain the orange outline.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
I wonder if this was fixed? Can you please try again? I am refactoring menu code and am not able to reproduce with either 0.11.4 or building from master

**Comment by srirambv** [comment]
Works as of 0.11.5. Closing the issue
