### ISSUE TITLE
Laptop : Title Bar : Favorite star rendering is not locked in position.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2804]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
For a site which has been bookmarked, when changing the size of the window, the fa-star will eventually hover over the Brave shield. In another instance, a user found it rendered in the middle of their URL bar. 

**Expected behavior:**
This is probably more of a UX call, but I would expect that it either reserves enough space to persist nicely with other elements in the title bar or it hides itself in a nice, responsive manner.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.2 (cd3ba8654673837e60898994ee205776d0522ad3)
- Steps to reproduce:
    1. Visit a site (ex. https://brianbondy.com/)
    2. Bookmark the site
    3. Shrink the window and observe the position of the star.

- Screenshot if needed:
<img width="1440" alt="screen shot 2016-07-29 at 11 31 34 am" src="https://cloud.githubusercontent.com/assets/1434040/17255737/19e750dc-5580-11e6-841c-dff57fbfad72.png">

- Any related issues:

**Comment by bbondy** [comment]
cc @cezaraugusto

**Comment by alexwykoff** [comment]
Looks good!
