### ISSUE TITLE
Spell check stopped working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2808]
**Describe the issue you encountered:** Spell check stopped working

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32bit JP

- Brave Version: 0.11.2 Beta1

- Any related issues: #2769  #2861

**Comment by luixxiul** [comment]
It works on 0.11.2 Beta2 on Windows 7.

**Comment by bradleyrichter** [comment]
It works on 0.11.2 Beta2 on Windows 7.

[--- Commented from Asana.com
#commenter brad richter
---[aa]

**Comment by luixxiul** [comment]
Closing this in favor of #2602
