### ISSUE TITLE
Open New Session Tab does not work on Windows 10 and macOS

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2809]
**Describe the issue you encountered:** "Open New Session Tab" and "Open Link in New Session Tab" do not work on Windows 10, or just missing the icon

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32bit JP
- Brave Version: 0.11.2 Beta1
- Steps to reproduce:
  1. Open New Session Tab from menubar
  2. Open Link in New Session Tab
- Screenshot if needed: 
- Any related issues: #2769

**Comment by srirambv** [comment]
Both options works for me on Win 10 64bit EN

**Comment by luixxiul** [comment]
I can resolve this by clearing brave folder. Something must be wrong there

**Comment by luixxiul** [comment]
Fixed by closing all existing tabs and windows.

**Comment by luixxiul** [comment]
I experience this issue on macOS too.

**Comment by luixxiul** [comment]
it may be blocking, so I am setting the milestone

**Comment by bbondy** [comment]
could you provide consistent steps to reproduce this? Maybe even if they involve clearing session profile?

**Comment by bbondy** [comment]
This might depend on the link you right clicked on?

**Comment by luixxiul** [comment]
Might be so as I cannot reproduce this anymore. I will tell you if I notice it again

**Comment by luixxiul** [comment]
I closed the issue as it can no longer be reproduced
