### ISSUE TITLE
Whatever I type in URL bar immediately after creating new tab gets erased

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#2812]
**Did you search for similar issues before submitting this one?**

I did a few issue searches, hopefully this isn't a duplicate!

**Describe the issue you encountered:**

I'm pretty fast on the keyboard. If I cmd + t to open a new tab and immediately start typing, whatever I've typed gets erased about half a second after I start.

**Expected behavior:**

The URL I've started typing should persist.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version:

Brave: 0.11.1
Electron: 1.2.7
libchromiumcontent: 51.0.2704.103
V8: 5.1.281.65
Node.js: 6.1.0
Update Channel: dev

- Steps to reproduce:
    1. cmd + t to open a new tab
    2. Start typing immediately
    3. Notice after ~.5 seconds it gets deleted

- Screenshot if needed:

![brave3](https://cloud.githubusercontent.com/assets/490294/17263046/a644afa8-5593-11e6-8063-29f3234f828f.gif)

- Any related issues:

**Comment by diracdeltas** [comment]
not exactly a duplicate, but related: https://github.com/brave/browser-laptop/issues/2039

**Comment by diegodoval** [comment]
This also happens when using CMD+N to open a new window (it happens more frequently and it's easier to reproduce that way)

**Comment by bbondy** [comment]
Possibly a fix is related to if you move your mouse where the urlbar suggestions are, it changes the location to what was hovered over.

**Comment by dgarsys** [comment]
I have seen this behavior on opening a new window. Sometimes on the original window.

 If I restart brave, the first window works fine for some time but I regularly can open up a second window, enter text into the address bar, and hit "enter" - and it jsut disappears, nothing loads.

Just updated to brave 0.11.2 on OSX 10.11.6

Had not seen it before

**Comment by Liunkae** [comment]
It seems to reset the url bar when the page's title "about:newtab" changes to "New Tab", or when the "new tab page" finishes loading.

**Comment by gulkily** [comment]
There seems to be two issues going on here.

a. What Liunkae mentioned, the clearing of the typed input after the newtab finishes loading
b. Keyboard input that is lost between the user pressing C-t and the address bar gaining focus and capturing input.

On

**Comment by PatrickRyanLane** [comment]
Just wanted to share issues #2197 and #847 which referenced the same problem. It looks like it may have been solved in 0.10.4 but has now returned. @bbondy mentioned it may have been something relating to auto complete changes that fixed the issue initially.
