### ISSUE TITLE
Longer domains may break Bravery Panel UI

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#2813]
### Description: ###
When expanding the *Bravery Panel* while on a site with a very long domain name, the user may find the panel UI to be broken.

### Expected Behavior: ###
The user expects the *Bravery Panel* to be irrespective of the domain they happen to be visiting.

- Platform: Windows 10, build 10586
- Brave Version: 0.11.1
- Steps to reproduce:
    1. Navigate to [a URL with a long domain name][1]
    2. Open the *Bravery Panel*
    3. Note the ability to scroll laterally

### Screenshot: ###
Below is an animated GIF of the issue:

![brave-long-address](https://cloud.githubusercontent.com/assets/815158/17265271/729fc570-55a2-11e6-8a19-cf0ce1080462.gif)

### Related Issues: ###

A similar issue exists with Brave on iOS, however the URL is negatively impacted rather than the surrounding space.

![image](https://cloud.githubusercontent.com/assets/815158/17265323/c341d1bc-55a2-11e6-9a75-002dbcb76bb0.png)

 [1]: http://www.thelongestdomainnameintheworldandthensomeandthensomemoreandmore.com/

**Comment by cezaraugusto** [comment]
Whoa it exists! Crazy. Thanks for reporting 😺 

/cc @garvankeeley for iOS fix.

**Comment by jonathansampson** [comment]
One concern with the approach taken is that sufficiently similar URLs may be indistinguishable from eachother. Consider "bravesoftware.com" rendered as "bravesoftware...". Meanwhile, I register "bravesoftwaredownloads.com" for the purposes of distributing malware, which also gets rendered as "bravesoftware...".

Here's a really rough concept for a potential alternative approach: https://jsfiddle.net/5ur7xfzh/

Upon opening, the domain slides sideways, suggesting to the user that it is moveable. When the user hovers the domain with their mouse, any non-showing portion is scrolled into view. Removing the mouse will restore the domain to its original position.

![brave suggestion](https://cloud.githubusercontent.com/assets/815158/17272050/369acb66-5641-11e6-899a-f6e2a2cbece5.gif)

**Comment by bbondy** [comment]
A poor man's approach to this is just to add a title attribute, I'd accept a PR for the above though, it's a cool idea.

**Comment by alexwykoff** [comment]
Looks good!
