### ISSUE TITLE
Error.properties files are not properly downloaded

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2815]
**Describe the issue you encountered:** There are ``Error.properties`` files in each locale folder, but there is just one line which says ``Not Found``.

**Expected behavior:** I think something is not correctly configured at transifex.com. I cannot find ``Error.properties`` in the resource list.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version: 0.11.2 Beta1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #1858

**Comment by luixxiul** [comment]
Setting a milestone as this must be easy to fix.

**Comment by bradleyrichter** [comment]
Setting a milestone as this must be easy to fix.

[--- Commented from Asana.com
#commenter brad richter
---[aa]

**Comment by bbondy** [comment]
is this the same or different as errorMessages.properties?
