### ISSUE TITLE
Shift to zoom not functioning 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2816]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Per https://github.com/brave/browser-laptop/issues/2685 users should be able to zoom via using Shift + '+' or '-' 

**Expected behavior:**
The page should zoom according to the key combination used.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Visit a site
    2. Use the key combination of Shift + '+'
    3. The page does not zoom

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/2685

**Comment by luixxiul** [comment]
Also on Windows 7 https://github.com/brave/browser-laptop/issues/2768#issuecomment-236108368 and Windows 10.

**Comment by bbondy** [comment]
Shift+Zoom should not work, it used to be command+= and not it is command+=  or command+Shift+=

**Comment by luixxiul** [comment]
I see, I was not sure that these shortcuts exist.

**Comment by bbondy** [comment]
Closing since shift to zoom isn't a valid shortcut.
"Added optional Shift for zoom in shortcut." is meant to mean that you can add a shift to the existing zoom in shortcut which is command+=

**Comment by alexwykoff** [comment]
Not a bug, just a misunderstanding. Command/Ctrl+Shift+'-/+' works.
