### ISSUE TITLE
Tab transitions now cause flicker

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2817]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When hovering over multiple tabs, the 'peeking' functionality leaps back to the active tab causing a flickering effect.

**Expected behavior:**
This is a UX call, but my opinion would be to persist the view of the peeked tab until we're sure they are no longer scanning across tabs. Perhaps track mouse dx and infer behavior?

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Open multiple tabs for different sites
    2. Move the mouse across the tabs

- Screenshot if needed:
![tab_switching](https://cloud.githubusercontent.com/assets/1434040/17268277/e855ccf8-55eb-11e6-8c5a-c4a5135243c5.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/2765

**Comment by bbondy** [comment]
removed from 0.11.2 because I think it is an improvement from what it was in 0.11.1 but let me know if not.

CC @cezaraugusto

**Comment by cezaraugusto** [comment]
This is weird. I set non preview mode to have no delay, but fetching master branch returned the same result. I'll send a patch for it now. Thanks @alexwykoff

**Comment by alexwykoff** [comment]
I pulled this down and gave it a quick spin. This fixes the left-to-right issue.

However, I did notice that a flicker will frequently catch when coming down from the URL bar, less so when going up to the URL bar.

![cezar](https://cloud.githubusercontent.com/assets/1434040/17304334/cc3934aa-57ea-11e6-9ce9-c3e70b5b13b5.gif)

**Comment by luixxiul** [comment]
in 0.11.2?
