### ISSUE TITLE
Save password prompt appears automatically for websites

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2820]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Save password prompt appears on webpages where no action was taken. Visiting the same page second time browser automatically asks to save the user credentails

**Expected behavior:**
Save credentials prompt should appear only after a user enter it
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.2 Dev Beta1
- Steps to reproduce:
  1. Login to any page and check for the save credentials prompt
  2. Do not select any option in the prompt, logout from the website
  3. Close browser and reopen to visit the same website
  4. Save credentials prompt appears immediately after the page is loaded without user entering any details. 
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
I think I saw this on gmail
