### ISSUE TITLE
recreating webview deletes page history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2825]
**Did you search for similar issues before submitting this one?**
Yes (may be duplicate couldn't find similar)

**Describe the issue you encountered:**
Clicking on allow in the flash alert refreshes the page and the page history is gone

**Expected behavior:**
Page history should not be deleted
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.2 Dev Beta1
- Steps to reproduce:
  1.  Open http://www.miniclip.com/games/8-ball-pool-multiplayer/en/#t-w-c-H 
  2. Click allow when the flash prompt appears
  3. Page refreshes and plays flash content but the page history is gone and the back button is disabled.
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
I think this is wontfix, but pls confirm and if so close @diracdeltas

**Comment by diracdeltas** [comment]
looks like frame history state is gone every time the webview is recreated. i think that's a bug.

**Comment by bbondy** [comment]
ah I misunderstood as page state
