### ISSUE TITLE
Error tab cannot be reloaded or cloned

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2826]
**Describe the issue you encountered:** An error tab cannot be reloaded or cloned.

**Expected behavior:** It should be reloaded and cloned

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.2 beta1

- Steps to reproduce:
    1. Go to https://expired.badssl.com/
    2. Select "Reload" on the tab
    3. Select "Clone" on the tab

- Screenshot if needed:

- Any related issues:

**Comment by gulkily** [comment]
Possibly related: Changing only the anchor for the URL should not reload the page #2963

**Comment by bridiver** [comment]
reload/clone is intentionally disabled on most about/error pages. I'm not sure that disabling reload is necessary, but at the very least the options shouldn't appear in the context menu if they don't actually work. Thoughts @bbondy ?

**Comment by bbondy** [comment]
We should definitely make this work, especially for connection error pages.

**Comment by bbondy** [comment]
moving to 0.12.2

**Comment by bbondy** [comment]
@darkdh would you be able to take this one in 0.12.6 timeframe?

**Comment by darkdh** [comment]
sure thing
