### ISSUE TITLE
Deleted Bookmarks show up in address bar autocomplete

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#2827]

**Comment by bbondy** [comment]
It still considers it a history entry when you delete a bookmark.  You could clear history to get rid of those suggestions.

**Comment by TaroPuff** [comment]
@bbondy yes, I definitely Cleared History, Cleared Cache, Cleared All Cookies and Site Data via UI. On both Windows and Mac.

I just downloaded Brave 0.11.1 again, imported my Safari Bookmarks, deleted a couple of folders of bookmarks. Did all the clearing. Restarted the browser. Deleted bookmarks still show up in the Bookmarks section of the autocomplete dropdown.

-----

Note that when I removed Brave from my Mac, I also deleted anything I could find in my user's folder by searching for it in Terminal:

find . -iname "*brave*"
find . -iname "*electron*"

and deleted anything I could find via those commands (Application Support, Cache, Preferences, Saved Application State, etc.) to make sure I left nothing from my previous install while testing just now.

**Comment by TaroPuff** [comment]
So I found that the bookmarks were still stored in a file called "session-store-1" even after deleting them. Deleting that file wiped the bookmark entries showing up in Auto Complete. Also wiped all settings.

**Comment by bsclifton** [comment]
@TaroPuff like @bbondy said, the bookmarks (when deleted) are kept in session as a "history" entry.  I'm curious why clearing the history didn't work?  Your work-around did the trick though- that'll kill all the customizations and history associated with your previous browsing sessions

Internally, the bookmarks are stored in a "sites" object. Perhaps that isn't being cleared when you choose clear history?

**Comment by bsclifton** [comment]
I'm going to close this for now, but @ghost please feel free to re-open if you have more specific details / expectations.  Please try the clear history option. Thanks :smile:
