### ISSUE TITLE
Copy/Paste Dialog on the Search/URL Bar

### ISSUE THREAD

**Issue by PFCKrutonium** [brave/browser-laptop#283]
One should probably be added. Yes you can ctrl+c and ctrl+v, but far too many people do not realize this.
![screenshot 199](https://cloud.githubusercontent.com/assets/3945538/12534030/3942b04c-c215-11e5-983b-287b88c5059d.png)

**Comment by psimyn** [comment]
This looks to have been fixed by @bbondy

**Comment by bbondy** [comment]
yep this works now, closing.
