### ISSUE TITLE
Imported Bookmarks from Firefox do not appear in Bookmarks Menu

### ISSUE THREAD

**Issue by rodvanmechelen** [brave/browser-laptop#2830]
#**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Imported Bookmarks from Firefox do not appear in Bookmarks Menu. Just the folders appear in the Manage Bookmarks menu.

**Expected behavior:**
Imported bookmarks would be in the Bookmarks menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Platform: Win 7

- Brave Version:
Brave Version: 0.11.1 Electron: 1.2.7

- Steps to reproduce:
    1.  Export bookmarks from Firefox 47.01. Import Firefox bookmarks to Brave. 
    2.  Click on Bookmarks in Menu Bar. No bookmarks. Restart Brave. Still no bookmarks.
    3.  Click on Bookmarks Manager in menu bar. Folders from imported bookmarks appear, but they will not open.

- Screenshot if needed:

- Any related issues:

**Comment by neeklamy** [comment]
Just a small thing – please edit your issue to change the title, the title should just be that.

Paste in the entire content currently in the title into the body of the issue and rename this, “Imported Bookmarks from Firefox do not appear in Bookmarks Menu” (no need for a full stop at the end).

*Thanks!*

**Comment by Liunkae** [comment]
Fixed in #4049. This fix will be in 0.12.2, which will probably be released in a few days.
