### ISSUE TITLE
Cisco download software page will not load

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2834]
https://software.cisco.com/download/navigator.html

> Products -> Analytics and Automation Software -> Data and Analytics Software -> Connected Streaming Analytics

The download page will not load.

CC @srirambv to investigate a bit more and check for console / which shields blocks it.

**Comment by srirambv** [comment]
Enabling Ads and Tracker options in the shields causes the problem. Disabling it allows the download page to be loaded. When block ad/tracker enabled it fails to load [this file](https://tags.tiqcdn.com/utag/cisco/support/prod/utag.js).

When ad/tracker is enabled.
![cisconavigator](https://cloud.githubusercontent.com/assets/17010094/17284710/1b4aa974-57b5-11e6-8a9d-6ed9bf086fa9.png)

When ad/tracker is disabled.
![ciscoadenabled](https://cloud.githubusercontent.com/assets/17010094/17284778/9c27f394-57b5-11e6-94b3-d882a51f2bce.PNG)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/issue-tracking-cisco-download-software-page/10590
