### ISSUE TITLE
Brave hangs in development with red "Loading..." text (Ubuntu 14.04)

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#2835]
[x] **Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
On a fresh pull Brave hangs when run via `npm start`stuck displaying "Loading" in red on a white background.

Ran `git bisect` and it seems to be broken by a single commit: 823dbf03a07a19d99546bf8c20d75da03b217802:
```
commit 823dbf03a07a19d99546bf8c20d75da03b217802
Author: Brian R. Bondy <netzen@gmail.com>
Date:   Tue Jul 26 13:21:37 2016 -0400

    Revert "Revert "don't allow scaling or zooming of the ui""
    
    This reverts commit d4258e05bf3222bda0f5668b7246960b53221fdf.

 js/entry.js | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)
```

Brave runs fine if I revert this commit. 

Anyone else have this issue?

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04 LTS 

- Brave Version:
Fresh pull on master, commit 011ed743f82e1a22e382a99071078a7cfe203e83 

- Steps to reproduce:
    1. Switch to master branch, pull latest.
    2. Run `npm run watch`
    3. In a separate terminal, run `npm start`
    4. Observe Brave window contains only red text "Loading..." on a white background, and remains like this.

- Screenshot if needed:
![brave-stuck-loading](https://cloud.githubusercontent.com/assets/6969859/17283194/9863da1e-5762-11e6-8ea1-c96921a22f62.png)

**Comment by kingscott** [comment]
Getting this issue on MacOS as well. Followed those steps, and haven't been able to fix the error. Any thoughts?

**Comment by bbondy** [comment]
you might just need a new node_modules? Remove it then npm install again.
