### ISSUE TITLE
Block script icon overlaps on the URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2837]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Blocked scripts icon overlaps on the URL when the window size is reduced.

**Expected behavior:**
Should display next to the URL 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2 Dev Beta1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![blockscript](https://cloud.githubusercontent.com/assets/17010094/17284836/16bd67ec-57b6-11e6-8082-b632ea6f989b.png)

- Any related issues:

**Comment by bbondy** [comment]
Is this still an issue with 0.11.2?  I think it works now, please close if so.  Or comment if still an issue.

**Comment by srirambv** [comment]
Fixed in 0.11.2. Closing.
