### ISSUE TITLE
Enabling Ad/Tracking in shields breaks Alexa website

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2838]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ad/Tracking blocks most of the scripts from the site which doesn't render the website properly. Blocks everything from CSS to Image files.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64, Ubuntu 16.04 x64
- Brave Version:
  0.11.2 Dev Beta 1
- Steps to reproduce:
  1. Enable Ad/Tracking blocker in Shields
  2. Visit http://www.alexa.com/
  3. Shields shows 27 blocked items  (26 blocked scripts from Alexa including CSS and Image files)
- Screenshot if needed:
- Any related issues:

**Comment by Liunkae** [comment]
Works fine for me with Brave 0.13.1 on macOS 10.12.x.
![image](https://cloud.githubusercontent.com/assets/19424103/22582116/5c3649c0-e9aa-11e6-85e8-9464f567afea.png)

**Comment by luixxiul** [comment]
The site works for me too. I'm going to close this one.
