### ISSUE TITLE
The YouTube player should be able to be full screen

### ISSUE THREAD

**Issue by PFCKrutonium** [brave/browser-laptop#284]
Right now it does this: 

![screenshot 200](https://cloud.githubusercontent.com/assets/3945538/12534034/7db92e18-c215-11e5-9a9b-2df4ae967d68.png)

**Comment by parvez3019** [comment]
okay i'm looking into this

**Comment by bbondy** [comment]
:+1:

**Comment by TheFallenOneGOTH** [comment]
Still a concern on Windows 10 v10586.71 (Version 1511).

**Comment by PFCKrutonium** [comment]
Still Happening.
