### ISSUE TITLE
Tracking Protection blocking Kayako website trial signup

### ISSUE THREAD

**Issue by swarnava** [brave/browser-laptop#2840]
**Step to Reproduce**:

Go to https://kayako.com
Scroll down & try to signup.

**Expected behavio**r:
It should allow signup.

**Actual Behavior**:
It's not working.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-tracking-protection-blocking-kayako-website-trial-signup/10092

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
