### ISSUE TITLE
Consider connecting the title-mode to tab previews to prevent mismatch between them

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#2844]
Currently, when you mouse-over a tab (with previews enabled) the preview is shown dimmed in the page but the title bar shows the URL for the current active tab.

This may lead to some confusion and it may be better UX to also show the matching title for the tab which is being previewed.

This can be disabled when the user has disabled the tab previews in preferences. 

CC @srirambv cc @bbondy 

Ideally we could test this before commiting if the task is small.

**Comment by neeklamy** [comment]
The current preview implementation is okay, but has there been any consideration given to changing it up to look more like a preview?

Opera has a smaller preview, which if the tab is switched to, zooms in.

![Opera tab preview on hover](https://cloud.githubusercontent.com/assets/155358/17304980/2bfc3966-5820-11e6-8e3d-5cd24209e079.jpg)

I don’t have any particular ideas though…

**Comment by bradleyrichter** [comment]
The current approach doesn't require ripping preview images which can get out of date, and can show moving content since it remains as live data.

I do like the look of the Opera approach though. Maybe we can achieve the best of both worlds some how.

**Comment by bbondy** [comment]
technically we can still reformat how the preview is displayed while still using a live preview.

**Comment by bradleyrichter** [comment]
@cezaraugusto Is this a quick one for you by any chance? 

(syncing the title in title mode to the mouse hover preview)

**Comment by cezaraugusto** [comment]
@bradleyrichter have some other tasks on the way first, but can take this one after doing them. 

I'll assign myself to keep me on track but anyone willing to do it feel free to take first, and I'll revoke myself.

**Comment by Liunkae** [comment]
Related issue: #1613
