### ISSUE TITLE
Search settings enhancements

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2850]
- Display the URL that is being used for replacements in the UI
- Allow customizations of the URLs (e.g. I might want amazon.ca not amazon.com)
- Allow customization of the URL shortcuts
- Allow adding new entries.

CC @darkdh

**Comment by luixxiul** [comment]
Also please allow making the setting "undefault".

**Comment by srirambv** [comment]
Google doesn't have a check against it by default. Ideally it should have the check mark under default until user changes it.

**Comment by bsclifton** [comment]
Closing this issue as we have several others which capture the individual issues:
[Allow user to add custom search engines](https://github.com/brave/browser-laptop/issues/3053)
[Switch search engines locale based on languages](https://github.com/brave/browser-laptop/issues/5180)
[Display/hide search engines based on language](https://github.com/brave/browser-laptop/issues/5181)
