### ISSUE TITLE
Reload shortcut does not work on error pages

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2852]
i) load a page, and while it is loading turn off your wifi
ii) Use command+r to reload

Step ii) does not work, it requires you to press the reload button :S

I think we need to check for about:error and use the provisionalLocation to reload instead of the location.

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by neeklamy** [comment]
Off-topic, but a neat tip on testing different network conditions without messing around with Wi-Fi and similar settings.

In the dev tools → Network → No throttling menu, change that to whatever you’re after, including *offline*.

![in Brave’s dev tools, you can take the browser offline, cool!](https://cloud.githubusercontent.com/assets/155358/17329237/a602ff9e-58b9-11e6-9f7f-9998c1b4aee0.png)

**Comment by bbondy** [comment]
Duping to #2826
