### ISSUE TITLE
Google IME compatibility

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2854]
**Describe the issue you encountered:**
Conversion candidates in Google IME is off by far. On Chrome they are not

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: https://github.com/brave/browser-laptop/tree/96638170214cdb2245380b79ae46cd5cd29aa086
- Steps to reproduce:
  1. Install Google IME for Japanese and enable it
  2. Navigate to https://github.com/brave/browser-laptop/issues/new
  3. Make sure the input mode is set to "ひらがな" and input "bureibu" (Brave in Japanese) in the title field
- Screenshot if needed:
  ![googleime](https://cloud.githubusercontent.com/assets/3362943/17319721/9c28ba66-58ca-11e6-9648-34aa85990cb8.jpg)
- Any related issues:

**Comment by luixxiul** [comment]
Also on findbar it takes a couple of seconds appearing a character. Internal search should not start until I hit the enter key to decide conversion candidates.

#3876

**Comment by luixxiul** [comment]
STR on OS X:

1. Enable Japanese on Google IME
2. Open a new tab
3. Hit "a", which shows "あ" on the top left corner

This cannot be reproduced once any key is hit on URL bar before you enable Japanese.

**Comment by luixxiul** [comment]
pinging to @diracdeltas

**Comment by diracdeltas** [comment]
are you running in dev mode or a build? for me, IME doesn't even show up unless it's in a build.

**Comment by luixxiul** [comment]
@diracdeltas how about this?

1. Enable Japanese on Google IME
2. Select "ひらがな" with `^⇧J` 
3. Set the focus on the search bar on the top of this page
4. Hit `a` several times
5. The list of decision candidates is shown on the top right corner

**Comment by bsclifton** [comment]
I believe this was fixed by @darkdh
