### ISSUE TITLE
Error and retry are included in the history pulldown

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2856]
**Describe the issue you encountered:** Error & retry are included in the history pulldown

**Expected behavior:** I think they should not be there. Either a page only successfully loaded or a failed page should.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS, Windows 10
- Brave Version: 0.11.6
- Steps to reproduce:
  1. Go to https://akimoto.jp/japan/, which should be refused
  2. Retry the url by clicking the button on the error page
- Screenshot if needed:
  <img width="261" alt="screenshot 2016-08-02 16 23 51" src="https://cloud.githubusercontent.com/assets/3362943/17320255/8d39ba48-58cd-11e6-9f34-747c7a9d5a7d.png">
- Any related issues: #2733 #2737

**Comment by luixxiul** [comment]
WDYT? /cc: @bsclifton

**Comment by bsclifton** [comment]
Good catch- our "about:" pages are counted in history.

We could try interesting approach which I had thought about a few weeks ago:
- Creating an empty webview tag (not bound to any frame object).
- Error happens- load the about:page in that webview's webcontents object
- We could then temporarily: 
 => remove the active webview from the webviewContainer in the frame which had the error
 => add the webview which points at the about:page into the webviewContainer. React would then render that one instead.

Once the frame is "resolved" (person goes back or forward in history; clicks acknowledge on a cert error page, etc), then we'd swap it back.

I don't think this would be too bad to do, although it does add extra complexity to the code. I'm going to self-assign and give it a shot :smile: 

cc: @bridiver, @diracdeltas

**Comment by luixxiul** [comment]
It's been fixed 😄
