### ISSUE TITLE
HTTPS connection shows insecure padlock icon.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2857]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
HTTPS connections doesn't show the secured padlock next to the URL. 

**Expected behavior:**
Should display the secure connection padlock in the URL bar.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.11.2 Dev Beta 2

- Steps to reproduce:
    1. Open any secure HTTPS connection
    2. 
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/17323944/009a2658-589c-11e6-8257-62670f563957.png)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #2673
