### ISSUE TITLE
Secure connection notification remains on screen 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2858]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When a user clicks on the connection icon in the URL bar the Connection notification remains on screen until user clicks elsewhere to dismiss the notification. 

**Expected behavior:**
Notification should disappear after the mouse pointer is moved away from the URL bar. 
Suggestion: The notification can be displayed as a tool tip similar to refresh/home/bookmark icons rather than clicking on the icon to display the notification. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64 
- Brave Version:
  0.11.2 Dev Beta 2
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  Not how the URL is hidden when the mouse is moved away from the URL bar. The notification remains.
  ![image](https://cloud.githubusercontent.com/assets/17010094/17324254/88a54c3e-589d-11e6-8d05-770c4b7dfdad.png)
- Any related issues:

**Comment by jonathansampson** [comment]
The old _Secure Connection_ tooltip has been replaced by one that provides an opportunity to view further information when the user clicks _View Certificate_. For this reason, the suggestion made above is no longer feasible. Closing for this reason.

![image](https://cloud.githubusercontent.com/assets/815158/26290576/31dec9c2-3e6e-11e7-9009-697caa51b2cf.png)
