### ISSUE TITLE
loading spinner never stops spinning sometimes

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#286]
On Twitter and Facebook tabs, it just keeps spinning.

**Comment by bbondy** [comment]
Dupe of #269

**Comment by prkeshri** [comment]
Same case here. When I do `npm start`, everything runs like butter, the facebook,google everything load successfully, but after I make a package out of it, it just keeps on spinning indefinitly. The title changes, though, but the page remains blank!
