### ISSUE TITLE
Google search opened when suggested items selected for Wikipedia and Youtube

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2860]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Selecting suggested search option for Wikipedia and Youtube opens up Google Search

**Expected behavior:**
Should search on the selected site for the suggested item

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10. x64

- Brave Version:
0.11.2 Dev Beta 2

- Steps to reproduce:
    1. Enable offer search option in preferences
    2. Type yt to enable YouTube Search
    3. type to, search suggestion provides to mp3 
    4. Select the offered search item, Google search opens for the same
    5. Same issue for Wikipedia as well 

- Screenshot if needed:
![autosearch google](https://cloud.githubusercontent.com/assets/17010094/17326083/ff224cbe-58a6-11e6-8229-213ff52ca0b8.gif)

- Any related issues:

**Comment by bbondy** [comment]
This was working as originally planned but @darkdh is working on this because your suggestion is better.
