### ISSUE TITLE
Download progress bar is off on hover

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2863]
**Describe the issue you encountered:**
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17326612/67f2dc4a-58ed-11e6-81da-90e4b2e4fbc6.jpg)

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 

- Brave Version: 0.11.2 beta2

**Comment by bbondy** [comment]
anything like this is a blocker for current release so adding to 0.11.2.
