### ISSUE TITLE
Background color of disabled option toggle on Bravery panel

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2864]
**Describe the issue you encountered:**
Background color of disabled option toggle on Bravery panel needs more contrast

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

- Brave Version: 0.11.2 Beta2

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17326751/3b49d454-58ee-11e6-9964-6312b8971e56.jpg)

This could be specific to Windows.

**Comment by bbondy** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
@luixxiul Thanks. I'll fix it for the next build. 

Also, this state is off, not disabled. We may need a new style for disabled.

Do you think the prefs panel off state looks OK?

**Comment by luixxiul** [comment]
@bradleyrichter It is the same there. I think we need more contrast for those who are visually handicapped.

**Comment by bradleyrichter** [comment]
The contrast between off and on is extreme.

So are you talking about the contrast between the switch and the background it sits on? This I can try to improve but it does feel about the same as iOS.

**Comment by luixxiul** [comment]
> contrast between the switch and the background it sits on?

Yes exactly.

**Comment by bradleyrichter** [comment]
@luixxiul better?

![image](https://cloud.githubusercontent.com/assets/13509546/17345750/757d73a6-58bc-11e6-9292-4a354ff6303c.png)

**Comment by luixxiul** [comment]
I think it's better :-) Please let me confirm it in the next RC, thanks!

**Comment by luixxiul** [comment]
I confirmed it with RC1 on my machine, nice :+1:
