### ISSUE TITLE
Preferences state change not re-rendering on restart of browser until state change

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2865]
**Describe the issue you encountered:** I am not sure if "Enable smooth scrolling" can be disabled on Windows 7. I was asked to restart brave and after restarting the option was still enabled, but when I selected another tab and went back to about:preferences the toggle status was changed.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.2 Beta2

- Steps to reproduce:
    1. Open a new tab
    1. Make sure to set Brave starts with my windows / tabs from last time
    2. Disable smooth scrolling on about:preferences
    3. Restart
    4. Select the new tab
    5. Select the about:preferences tab

- Screenshot if needed:

- Any related issues: #2862

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/browser-laptop/commit/3da5c25e1ae78db0ee59eb96ca0409f368409d8b ?

**Comment by bbondy** [comment]
yep
