### ISSUE TITLE
Plugin Settings slider state change visible only when the focus is changed to other tab.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2866]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Turn off the Plugin Settings slider. Doesn't show the slider animation when turned off. State change visible only when the focus is changed to other tab

**Expected behavior:**
Slider change should be shown when user clicks on the setting.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version:

- Steps to reproduce:
    1. Open Preferences page 
    2. Turn on/off Plugin Settings slider depending on its initial state
    3. Browser restart prompt appears but the slider position remains as before
    4. Change the focus to a different tab and back to preferences page
    5. Change in the slider state visible 

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Duping to https://github.com/brave/browser-laptop/issues/2865 please retest in RC1 once it is available.
