### ISSUE TITLE
Confirmation dialog should be displayed for deleting data from menubar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2870]
**Expected behavior:** Confirm dialog should be displayed for deleting data from menubar

- Platform (Win7, 8, 10? macOS? Linux distro?): 

- Brave Version: 0.11.2 Beta2

- Screenshot if needed:

- Any related issues:

**Comment by bradleyrichter** [comment]
from downloads bar?

**Comment by luixxiul** [comment]
``Clear History`` and ``Clear All Cookies and Site Data`` from ``History`` on Menu bar. I think we don't need such a dialog for ``Clear Cache``.

**Comment by bradleyrichter** [comment]
We may want to switch over to the standard approach by changing the menu as follows:

![image](https://cloud.githubusercontent.com/assets/13509546/17353169/e6e3a9ae-58f1-11e6-8802-6c33fc24a64c.png)


...but not until we have the clear button and dialog working in prefs:
![image](https://cloud.githubusercontent.com/assets/13509546/17353568/cf2828ae-58f5-11e6-8fc7-e36e600e477d.png)


This is how it works in Chrome and seems to work fine.

**Comment by luixxiul** [comment]
Fixed by #3051
