### ISSUE TITLE
Blank window on manual restarting after restoring data from backup

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2871]
**Describe the issue you encountered:**
Sometimes a blank window is displayed, when I restore data from backup and restart Brave manually. When I re-restart, then Brave starts properly. I don't think I have seen this until this version.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 VM
- Brave Version: 0.11.2 Beta2
- Steps to reproduce:
  1. Close Brave
  2. Move `AppData\brave` to your desktop
  3. Start Brave by clicking the desktop icon
- Screenshot if needed:
- Any related issues: #2862 #2906

**Comment by bbondy** [comment]
@bridiver any thoughts? Maybe the IPC for state init doesn't reach the window in time sometimes.

**Comment by bbondy** [comment]
and the registration happens after it I mean.

**Comment by luixxiul** [comment]
This has been fixed.
