### ISSUE TITLE
Toggles on about:preferences are not changed until reselecting the tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2874]
**Describe the issue you encountered:** Status of toggles on about:preferences#shields are not changed until reselecting the tab. I did not notice this on Windows 7.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.2 Beta2

- Steps to reproduce:
    1. Open about:preferences#shields
    2. Click the toggle for HTTPS Everywhere
    3. Open a new tab
    4. Select the preference tab

- Screenshot if needed:

- Any related issues: #2861

**Comment by luixxiul** [comment]
I notice this applies to the flash toggle on about:preferences#security

**Comment by bbondy** [comment]
Fixed here
https://github.com/brave/browser-laptop/commit/4d356a7dbd8d28d0e360f80e092a9706bebca5de
