### ISSUE TITLE
Fullscreen video does not persist.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2876]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting a site which allows for fullscreen video (youtube, twitch, etc), if you view at fullscreen the system will revert after about 20 seconds.

**Expected behavior:**
The fullscreen view should persist.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.2 Beta 2

- Steps to reproduce:
    1. Visit Youtube
    2. Choose a video and view at fullscreen
    3. Wait 1 minute

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Confirmed on Windows 10. For me it persists only for ~5 seconds. #2861

**Comment by bbondy** [comment]
nice find!
