### ISSUE TITLE
Saved zoom value is not applied until there is page interaction.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2880]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I visited a site and set the zoom to 500% then quit the browser. I then reopened the browser and checked the zoom value. The page was not zoomed.

**Expected behavior:**
The page should display the page at the level of zoom set.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X.

- Brave Version:
0.11.2 beta 2

- Steps to reproduce:
    1. Visit a site (ex. reddit.com)
    2. Zoom to 500%
    3. Exit the browser
    4. Reopen the browser, do not move your mouse   

- Screenshot if needed:
Less like this: 
<img width="1440" alt="screen shot 2016-08-02 at 10 23 32 am" src="https://cloud.githubusercontent.com/assets/1434040/17334829/47af5378-589d-11e6-91f3-5d03e75ea3a4.png">

More like this:
<img width="1440" alt="screen shot 2016-08-02 at 10 23 42 am" src="https://cloud.githubusercontent.com/assets/1434040/17334839/5587a04a-589d-11e6-911a-eabe5edd2547.png">

- Any related issues:

**Comment by srirambv** [comment]
Works fine on Windows 10. Get the same zoom level after restart although it takes time till the entire page is loaded and then an additional second to apply the zoom.

**Comment by bbondy** [comment]
This should be fixed now, pls confirm.

**Comment by bbondy** [comment]
0.11.2rc2
