### ISSUE TITLE
Videos on drive.google.com cannot be played on Windows 10

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2882]
**Describe the issue you encountered:** On Windows 10 videos on drive.google.com cannot be played even if I disabled Bravery panel. I tested on Chrome and worked fine.

**Expected behavior:** 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.2 Beta2

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17335722/ecbab3b2-5915-11e6-806e-29e43247f917.jpg)

- Any related issues: #2533 #2861

**Comment by bbondy** [comment]
isn't this a duplicate of https://github.com/brave/browser-laptop/issues/2533 ?
Which is in 0.11.2?

**Comment by luixxiul** [comment]
In #2533 the videos still could be played if 3rd party cookies were allowed, while in this case they can't even if I disable the bravery panel at all.

**Comment by luixxiul** [comment]
And weirdly they can be played on Windows 7 with 0.11.2 Beta2.

**Comment by luixxiul** [comment]
I confirmed it has been fixed. Maybe due to google servers.
