### ISSUE TITLE
Uninstallation shows error message about setting as default browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2883]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When trying to uninstall Brave without admin privileges, the setup throws the same error which is displayed during installation about not having enough privileges to set the browser as default. 

**Expected behavior:**
Should not show error about not setting it as default browser. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 x64 Professional

- Brave Version:
0.11.2 Dev Beta 2

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/17337524/efd06df2-58da-11e6-991b-d6ae662743b3.png)

- Any related issues:
[#954](https://github.com/brave/browser-laptop/issues/954)

**Comment by bbondy** [comment]
this is just an error  message tweak to say it can't unset.
