### ISSUE TITLE
Back button history does not hint at options beyond a certain point.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2889]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After navigating to a lot of different pages (ex. clicking https://www.reddit.com/r/random/ a lot of times), long click on the back button displays history for the tab. If you scroll, more history is shown, but there is no UI hint that this history exists. 
 
**Expected behavior:**
If a list item is not showing all of the elements, there should be a hint that more options exist and are not displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.2 beta 2

- Steps to reproduce:
    1. Navigate to a lot of different pages.
    2. Long click on the back button.
    3. Check to see if all of the history is displayed.

- Screenshot if needed:
![history_scroll](https://cloud.githubusercontent.com/assets/1434040/17343274/69435d20-58c2-11e6-915b-5423753c4ec9.gif)

- Any related issues:

**Comment by bbondy** [comment]
I think this should probably be limited to 12

**Comment by bbondy** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
I added a note about this to the original spec'd issue in #2737. 



@bsclifton @bbondy

**Comment by luixxiul** [comment]
or scrollable?

**Comment by bradleyrichter** [comment]
I usually find scrolling menus to be a bit tricky to navigate but perhaps we can add a "more" button at the bottom which would refresh the list with the next 10? That may need to be a lower priority feature.

**Comment by bsclifton** [comment]
Will make sure to revisit this w/ the history issues I'm looking at :smile:
