### ISSUE TITLE
Advertise Brotli compression

### ISSUE THREAD

**Issue by ericlaw1979** [brave/browser-laptop#2890]
Brave should advertise its support for Brotli compression (like Firefox and Chrome) for significantly better text compression than gzip/deflate. https://textslashplain.com/2015/09/10/brotli/

Visit, e.g. https://bayden.com/ua.aspx

Observe: **Accept-Encoding** header does not contain **br**. Notably, the star images at the bottom of the page render, which indicates that Brave is successfully decompressing brotli-encoded content, it's just not advertising its support.

Windows 7. 
Brave: 0.11.1
Electron: 1.2.7
libchromiumcontent: 51.0.2704.103
V8: 5.1.281.65
Node.js: 6.1.0
Update Channel: dev

**Comment by diracdeltas** [comment]
++, this would also help with #2229

**Comment by diracdeltas** [comment]
brotli compression is actually not on right now as far as i can tell - hence the stars show up as orange instead of green

but https://github.com/brave/electron/pull/32 turns it on over HTTPS and  advertises it in the header too

**Comment by ericlaw1979** [comment]
The stars show in orange when Accept-Encoding does not include "br". They show in green when "br" is included. They fail to render entirely when brotli is not supported (as they're served with brotli compression

**Comment by ericlaw1979** [comment]
unconditionally)

**Comment by diracdeltas** [comment]
ah, thanks for the clarification
