### ISSUE TITLE
Back button history - Selection should be made on mouseup instead of second click

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2891]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When long-clicking on the back button to show history, the selection is currently made via a second click.

**Expected behavior:**
The selection should be made on mouseup.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.11.2 beta 2
- Steps to reproduce:
  1. Navigate to a few sites
  2. Long click on the back button
  3. Hover over a site in the history and release the mouse button
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by bradleyrichter** [comment]
We need to add the ability to click, drag down, and release on selection. Probably the same as above?

**Comment by bbondy** [comment]
would be nice for this release but I won't block release on it since it's obvious you need to click when it doesn't do it for you.

**Comment by bradleyrichter** [comment]
This was mentioned in #2737. We can refer back to it until it's finished and close it.

Or close it and move on with new issues. It's up to you guys.

@bsclifton @bbondy
