### ISSUE TITLE
Ctrl + Shift + '-' to zoom out does not work on Ubuntu for zoom

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2897]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ubuntu:
Shift added zoom in (+) works. Shift added zoom out (-) does not.
Ctrl + '-' zooms out as expected.

OS X:
Opposite issue.

**Expected behavior:**
Ctrl + Shift + '-' should zoom out, Ctrl + Shift + '+' should zoom in.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Ubuntu, OS X, ~~issue appears to be limited to Ubuntu.~~
- Brave Version:
  0.11.2 beta 2
- Steps to reproduce: (Ubuntu, opposite for OS X)
  1. Navigate to a site 
  2. Zoom in via Ctrl + Shift + '+'
  3. Attempt to Zoom out via Ctrl + Shift + '-'
- Screenshot if needed:
- Any related issues:

**Comment by gulkily** [comment]
On OSX, I'm seeing something different:

Cmd = works
Cmd - works
Cmd Shift = (+) does not work
Cmd Shift - (_) works

**Comment by alexwykoff** [comment]
I'll be darned, just repro'd that @gulkily . Solid catch.

**Comment by bbondy** [comment]
I didn't think chrome had the - shortcut, just added it now too.
Just to confirm shift with + already worked for you right? Some confusion on https://github.com/brave/browser-laptop/issues/2897#issuecomment-237141604 which  said the opposite

**Comment by alexwykoff** [comment]
I think the confusion is the context on which OS. 
For Ubuntu : 
👎🏻 Ctrl + Shift + '-' does not work
👍🏻 Ctrl + '-' does work
When I read 2897 quickly I got a little confused as well. My bad for the formatting. 

For OS X:
👎🏻 Ctrl + Shift + '+' does not work

However, the RC1 build seems to have fixed the OS X issue. The Ubuntu issue remains.

**Comment by bbondy** [comment]
OK I'll update title for the remaining items and re-open and move this out of the current milestone.

**Comment by bbondy** [comment]
One question though, does the shortcut work in Chrome on Ubuntu?

**Comment by alexwykoff** [comment]
Tested both Chrome and Firefox on Ubuntu.
For Chrome, all shortcuts work.
For Firefox, Ctrl + Shift + '-' is the only one which does not work.

**Comment by bbondy** [comment]
ok maybe that shortcut is reserved on Ubuntu but chrome gets around it in some way.  I'm going to treat this as not super high priority.

**Comment by gulkily** [comment]
I think the reason that Ctrl+Shift+- doesn't work is that it corresponds to the underscore character.

Ctrl+= works for convenience's sake, so that the user doesn't have to press Shift for the + symbol. But for zooming out, the minus symbol does not require the Shift key anyway (Shift is for underscore), so it is not mapped.

That is my understanding, anyway.

**Comment by Liunkae** [comment]
<kbd>Ctrl+Shift+-</kbd> (<kbd>Ctrl+_</kbd>) works fine for me with Brave 0.13.0 on Linux Ubuntu 16.04.

**Comment by Liunkae** [comment]
<kbd>Ctrl+-</kbd> is working for me also. Closing for now.
