### ISSUE TITLE
Right-clicking the address bar should select the URL text

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#2898]
Did you search for similar issues before submitting this one?
Yes

Right-clicking the address bar does not select-all the text, a fairly standard behavior. As a result, the Cut/Copy/Paste menu items don't do anything useful.
1. Open a page
2. Mouse-over the title to display the address bar
3. Right-click on the address bar

Expected: The entire text of the address bar is selected, and the context menu is displayed

Actual: The text is not selected, but the context menu is displayed

\4. Try one of the following actions: Cut, Copy, or Paste

Expected: For Cut or Copy, the entire text of the address bar should be cut or copied to the clipboard. For Paste, the contents of the address bar should be replaced with what is contained in the clipboard.

Actual: Cut or Copy: No action. Paste: Clipboard contents are inserted where the right-click happened.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS.
- Brave Version: 0.11.1

**Comment by bbondy** [comment]
It does select but the context menu is modal so blocks the selection, we should fix by making context menus not act like modals.

**Comment by bsclifton** [comment]
Happy to report this is fixed 😄
