### ISSUE TITLE
Can't Build-Package on Windows

### ISSUE THREAD

**Issue by PFCKrutonium** [brave/browser-laptop#290]
npm run build-package (see readme.md under Windows) will not work, as it uses linux commands.

**Comment by bbondy** [comment]
I don't think it does, which command are you referring to?

**Comment by PFCKrutonium** [comment]
rm -rf

The equivalent Windows command would be rd /s /q

Even with that fixed, it doesn't seem to work...

**Comment by wblondel** [comment]
It works perfectly on my system (Windows 10 64 bit), I don't have any error.

**Comment by bbondy** [comment]
Just use a shell, you can use these steps:
https://github.com/brave/browser-laptop/issues/251#issuecomment-174095031

**Comment by PFCKrutonium** [comment]
I can't get any shell other than CMD or Powershell to pick up my system path. As for the build script, does it not make sense to have it work properly in a system standard shell?

**Comment by bbondy** [comment]
No sorry, we do not support that way. You will have to use a shell if you want to run those scripts to make a package.  We'll have builds available soon and you can get on the queue (which will start opening fast) on brave.com if you just want builds though.

**Comment by PFCKrutonium** [comment]
But _why_ would you not support it? By forcing people who want to work on this to install Bash or the like, you are adding unneeded complexity. Simply properly supporting the existing toolset on the host machine as much as possible, you can make it much easier to contribute.

**Comment by bbondy** [comment]
Because every dev will have a shell, or they should get one. We want our contributors to be productive :)
Also supporting more things, adds more things we need to support. And that takes time and adds complexity.  Sorry, we will not do this issue.

**Comment by bbondy** [comment]
So a second independent person wants this and did a pull request, seems like I should re-consider.
Will be tracked here. 
https://github.com/brave/browser-laptop/pull/299

**Comment by aviolentgrace** [comment]
@PFCKrutonium you might want to pull the latest and give it another shot. My change that uses rmdir instead rm on windows is in master now.

**Comment by PFCKrutonium** [comment]
@aviolentgrace Thanks :+1:

**Comment by luixxiul** [comment]
Closing this as #299 has been merged.
