### ISSUE TITLE
Drag-focusing the address bar should not select-all

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#2900]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Attempting to select part of the URL text in the address bar results in all text being selected (select-all) if the address bar did not previously have focus.

**Expected behavior:**
Selection should happen right away, so as to not annoy the user
- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on macOS
- Brave Version: 0.11.1
- Steps to reproduce:
  1. Open a page in Brave
  2. Mouse-over the title to display the address bar (but do not click it yet)
  3. Attempt to select text from the middle of the address bar text by clicking and dragging. For example, if the URL is "http://www.example.com/foo/bar/index.html", try to select just the "foo/bar" part.

Expected: The text the mouse cursor is dragged over is selected, but not the other parts of it

Actual: It seems like mouse-down on the address bar triggers a select-all, and the entire text ends up being selected. The beginning of the selection is then in the beginning of the text, and the end of the selection moves with the mouse cursor.

At other times, seemingly after I Alt-Tab to Brave, or maybe only when Jing is running and I'm trying to make a video of this bug, the entire address bar text ends up being dragged. Once I drop it back into the address bar, the page does some kind of refresh, although form data is not lost (thank goodness)

**Comment by apphacker** [comment]
This is a really frustrating bug that's a deal killer for me. I can't even place the cursor with the mouse. I have to use arrow keys. I can't understand how this is desirable behavior. Any clicking selects all. I want to fix one character I have to click escape and then use the arrow keys to move the cursor to the character to fix. Why would you make it this way?

**Comment by jevuu** [comment]
Hello,

May I take on this issue?

**Comment by bsclifton** [comment]
Verified fixed with our [Developer channel release](https://brave.com/download-dev) 😄
