### ISSUE TITLE
Unable to sign in with LastPass 

### ISSUE THREAD

**Issue by bagmangood** [brave/browser-laptop#2901]
**Describe the issue you encountered:**
When re-launching Brave, the LastPass dialog launches as a blank tab around 75% of the time. Closing and re-launching the browser will work, though it may take a few attempts. 

**Expected behavior:**
New tab launches and you can sign in from it

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X El Capitan 10.11.5

- Brave Version:
0.11.1 (upgraded from 0.11.0)
- Steps to reproduce:
    1. Enable LastPass
    2. Close browser
    3. Try to re-sign in

**Comment by cjrjscgallo** [comment]
I have the same behaviour 100% of the time.
Win7, Brave 0.11.4

**Comment by BCSWowbagger** [comment]
Identical to #2936.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/2936
