### ISSUE TITLE
Main window(s) stop responding if help about is open

### ISSUE THREAD

**Issue by scrumit** [brave/browser-laptop#2902]
Minimised window doesn't render if opened when about dialog is open.

Window should render the window, but a blank screen is displayed. 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 Enterprise, Service Pack 1 
- Brave Version: 0.11.01
- Steps to reproduce:
  1. Open help, about, 
  2. minimise main window 
  3. click on taskbar to re-open the main window
- Screenshot if needed:
  What? You want a blank screen?
- Any related issues:
  Possibly all activity on other pages is disabled until the 'about' page is dismissed. I couldn't update this issue when I opened the about page to find out the Brave version number.

**Comment by luixxiul** [comment]
Even video streaming stops on youtube.

**Comment by luixxiul** [comment]
The issue was fixed with #5436 (about:brave).
