### ISSUE TITLE
Developer tools should respect keyboard shortcuts

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2908]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On a site, I opened the developer tools via 'Inspect Element'.  I then tried to close the developer tools via the keyboard combination of Command + W. The developer tools window remained open.

**Expected behavior:**
The developer tools window should close.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.2 RC1

- Steps to reproduce:
    1. Visit a site.
    2. Open the developer tools.
    3. Attempt to close the developer tools via Command + W

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I think this is a dupe of https://github.com/brave/browser-laptop/issues/45

**Comment by alexwykoff** [comment]
Agreed. Closing.
