### ISSUE TITLE
Context menu paste should allow for repetitive paste just like the keyboard shortcut.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2909]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When pasting a word into a text field via the context menu, it will highlight and replace the previous word. When pasting from the keyboard it will append.

**Expected behavior:**
The context menu behavior should match the keyboard behavior.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.11.2 RC1
- Steps to reproduce:
  1. Visit a site with a text input.
  2. Copy and paste some text via the context menu.
  3. Paste again.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Confirmed this is still an issue; we saw it on 0.14.0 and 0.14.1 RC1

![paste_selectall2](https://cloud.githubusercontent.com/assets/4733304/24575159/167e6112-1653-11e7-8d8d-e9ff97be2f35.gif)

**Comment by bsclifton** [comment]
This may be an electron / Muon bug... I bet we can check upstream for patches which may have this fixed

**Comment by lukemulks** [comment]
@bsclifton this is the site that our Community contributor experienced this on (macOS, reported this evening, sounds similar to what you all were working through):

URL: www.cor-mariae.com

Community thread for reference: https://community.brave.com/t/pasting-material-on-website/1972/3

**Comment by lukemulks** [comment]
@bsclifton
Just noting before my brain forgets...
The link above may actually be fixed by the update currently being pushed. 

I am going to have the contributor confirm once the push is live, and will report here. 

Most likely was a timing discrep between the 0.14.0 release and the hotfix.

**Comment by lukemulks** [comment]
@bsclifton
Confirming that the contributor mentioned above has reported that v0.14.1 has resolved their issue.

**Comment by Liunkae** [comment]
I think this problem is made worse by the fact that context menus are synchronous on macOS (#5470).
