### ISSUE TITLE
Zoom cannot be controlled on the preferences page

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#2911]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I visited the about:preferences and set the default zoom to 500%. I then tried to use the keyboard shortcuts to zoom out and undo the effect. I also tried the hamburger menu controls. 

**Expected behavior:**
I should be able to zoom out OR zooming should be disabled for about: pages.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.2 RC1

- Steps to reproduce:
    1. Visit about:preferences
    2. Set the zoom to 500%
    3. Attempt to unzoom

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I see thanks, could you check if it is the same as 0.11.1?

**Comment by Liunkae** [comment]
I can confirm it is the same as 0.11.1.

**Comment by bbondy** [comment]
I think this is fixed in 0.11.2 RC2, can you confirm @alexwykoff ?
