### ISSUE TITLE
Closing an inactive tab should not change the active tab

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#2913]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When an inactive tab is closed by clicking the X button, the active tab changes to the closed tab's opener.

**Expected behavior:**
The active tab should remain the same.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.1

- Steps to reproduce:
    1. Open a page that has 2 or more links on it
    2. Open at least 2 links, each in a new tab
    3. Switch to one of the opened tabs
    4. Close the *other* tab by hovering the tab, waiting for the X button to appear, and clicking the X button.

Expected: The active tab remains the same

Actual: The first tab becomes the active tab

**Comment by willy-b** [comment]
Adding an illustration of the original bug because the tab order matters for reproducing it:

![tabconfigurationtoreproducetabbug](https://cloud.githubusercontent.com/assets/6969859/17386026/7a25e228-599b-11e6-8821-eb2b78268e4c.png)

**Comment by willy-b** [comment]
Adding quick illustration of how to reproduce original bug, since it is sensitive to tab order:

![taberror_final](https://cloud.githubusercontent.com/assets/6969859/17386350/d68b8808-599e-11e6-94f2-3cdd318866c4.png)

**Comment by gulkily** [comment]
This is still a bug in 0.11.3. Should I be using a daily build to verify?

**Comment by luixxiul** [comment]
@gulkily yes, you need to build the binary by yourself to verify it's fixed.

**Comment by gulkily** [comment]
Verified fixed in 0.11.5!
