### ISSUE TITLE
Pressing Esc key activates the URL Bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2914]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pressing Esc key on a page changes focus to URL Bar (whether hidden or always visible)

**Expected behavior:**
Standard behavior is F6 should focus to URL. Esc is only used to stop page load.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2 Dev RC1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
escape should revert any typing, focus and select the urlbar if the urlbar is already active, but agree that it shouldn't happen at other times

**Comment by luixxiul** [comment]
it looks like this has regressed at some timing.

https://community.brave.com/t/escape-key-should-remove-focus-from-address-bar/4736?u=suguru

> Using the escape key as a means to remove focus from the address bar seems to be standard across other browsers.
>
> The full functionality is typically:
> * First press: restores the URL of the page (if modified). This is currently working in Brave.
> * Second press: restores focus to the page from the Address Bar.

**Comment by bridiver** [comment]
@luixxiul the second press would be very odd behavior imo and no browser that I tested had that behavior, but the there is a problem with the behavior. The first press should clear any autocomplete suggestions and the second should restore the original URL. In the current release the first press restores the original url which is actually very annoying behavior.
