### ISSUE TITLE
Hovering a link triggers select-all on address bar

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#2915]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While the address bar is focused, hovering a link on the page will trigger a select-all action on the address bar

**Expected behavior:**
Mouse movement over the page should not affect the address bar's cursor

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.1

- Steps to reproduce:
    1. Open a page with at least one link
    2. Focus the address bar.
    3. Click the address bar so that no text is selected, and the cursor is visible
    4. Move the mouse cursor over a link on the page

Expected: Nothing changes in the address bar

Actual: All of the text in the address bar is now selected

**Comment by gulkily** [comment]
Funny enough, this issue does not occur when I am using QuickTime Player to record the screen.

**Comment by bsclifton** [comment]
Hi @gulkily :smile: I know it's been a while since this was opened... I am not able to repro

I'm going to close it out... but if it's still happening, can you please include some more details? I'm willing to bet this behavior has been fixed with some of our omnibar (address bar) updates
