### ISSUE TITLE
Dev tools closes & bfcache lost when Allow Flash to run is clicked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2918]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Page Developer tools window closes when Allow Flash to run is clicked

**Expected behavior:**
Developer tools should not close
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.2 Dev RC1
- Steps to reproduce:
  1. Open any page that has flash content 
  2. Open the page developer tools (ctrl+shift+I)
  3. Click on Download Adobe Flash to enable flash on the page
  4. When the allow button is clicked on the prompt Developer tools window closes
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
Updated title, we also lose the back-forward cache.  It is because the webview is re-created when flash is re-created.

**Comment by bsclifton** [comment]
Closing as `wontfix`- should be resolved with [Brave Core](https://github.com/brave/brave-browser)
