### ISSUE TITLE
"Enlarge image" breaks on CNET

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#2921]
**Describe the issue you encountered:**
Clicking an image that ought to expand darkens the background but doesn't show the image enlarged. 

**Expected behavior:**
Image shows enlarged

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X 10.11.6

- Brave Version:
Brave: 0.11.1
Electron: 1.2.7
libchromiumcontent: 51.0.2704.103
V8: 5.1.281.65
Node.js: 6.1.0
Update Channel: dev

- Steps to reproduce:
    1. Go to http://www.cnet.com/news/on-the-left-past-the-goat-farm-road-trip-2016-greece-refugee-crisis/
    2. Scroll down to image of lifejackets with overlay text "enlarge image." 
    3. Click to enlarge.

- Screenshot if needed:
Screenshot (taken in Safari) of what it should look like is attached.
<img width="1369" alt="screenshot 2016-08-03 14 30 07" src="https://cloud.githubusercontent.com/assets/16833251/17382677/e61d05fc-5986-11e6-813d-259178ef6e84.png">

**Comment by bbondy** [comment]
I think this is fixed as part of https://github.com/brave/browser-laptop/issues/5089#issuecomment-256545471 please re-open if not once you are using 0.12.7.
