### ISSUE TITLE
Long load time & Formatting issues with optionshouse.com

### ISSUE THREAD

**Issue by dudewheysmehcode** [brave/browser-laptop#2922]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Just downloaded Brave.  Opened up my gmail and pinned it.  Opened up a new tab and navigated to "optionshouse.com".  It took over 150 seconds to load, and no styling or formatting was displayed.

**Expected behavior:**  It should take less than 15 seconds to load the fully formatted home page for optionshouse.
- Platform (Win7, 8, 10? macOS? Linux distro?): Win 7 64 bit
- Brave Version: 0.11.1
- Steps to reproduce:
  1.  Navigate to optionshouse.com
  2.  Wait for the page to load.
     3.
- Screenshot if needed: 
  (unable to upload screenshot)  Shows 156.24 s to load the page.
- Any related issues:
  Retried this a a second time and it took 126.56 s to load.
  Clicking the login link at the top, the page loads in under 2 s.
  Tried with the latest Chromium release (v 54.0.2817.0) and the same slow load time is experienced and the same non-formatted website is displayed.  Tried with Chrome v 51.02704.103 and it loaded perfectly.

**Comment by luixxiul** [comment]
`optionshouse.com` is redirected to another site and the issue is no longer valid.
