### ISSUE TITLE
Consider using Google Safe Browsing or PhishTank API

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#2927]
See [brave/brave-ios #309](https://github.com/brave/browser-ios/issues/309). This issue is for tracking purposes.

**Comment by neeklamy** [comment]
Dupe #226

**Comment by bsclifton** [comment]
Should be addressed with [brave-core](https://github.com/brave/brave-browser); see https://github.com/brave/brave-browser/issues/204
