### ISSUE TITLE
Font rendering and "lang" attribute

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2929]
**Describe the issue you encountered:**
Font rendering is poor in Japanese if "lang" attribute is not set properly in `html` tag.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17389783/251afaaa-5a42-11e6-9de1-81a20ca77661.jpg)

Japanese and Chinese fonts are mixed here. For example "しています" rendered in Japanese fonts, while the font for "説明" is in Chinese (Taiwan)  fonts. 

Basically this bug seems to be like https://bugs.chromium.org/p/chromium/issues/detail?id=422180 "Chinese font selected under Japanese locale on Android".

Because this bug does not occur on Chrome, we should be able to fix this.

**Expected behavior:** It should be like this:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17389808/5037f260-5a42-11e6-8f34-9ad11e275973.jpg)
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1. Open https://braveinfo.net
  2. Open Devtool
  3. Change font-family to Arial for `:root`
  4. Replace lang="ja" into lang="en"
- Screenshot if needed:
- Any related issues: #1858

**Comment by luixxiul** [comment]
This applies not only page rendering, but also frame rendering.
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17455029/a14e1832-5be6-11e6-9554-4bcd0278daae.jpg)

0. Make sure any Japanese fonts are installed on your machine
1. Open Devtool with Shift+F8
2. Change ``en-US`` of html lang into ``ja-JP en-US``

This makes it into this, which looks consistent:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17455033/d646609e-5be6-11e6-89d6-94837ec84775.jpg)

**Comment by luixxiul** [comment]
The issue seems to be specific to Windows. On macOS it looks fine. I did not test on Linux.

**Comment by luixxiul** [comment]
It seems this was fixed with the latest cr54.

@bridiver do you have any info on this?

**Comment by bridiver** [comment]
this was probably related to the general locale issues so it would have been fixed by https://github.com/brave/electron/commit/d4f451c17e8481db6e3b1857c98b266cc76a51ed

**Comment by luixxiul** [comment]
@alexwykoff this should be added to the release note too.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
