### ISSUE TITLE
adblock video prevention script on cnet

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#293]
http://www.cnet.com/news/is-the-ad-blocking-brave-browser-too-good-to-be-true/
Doesn't show video because of and adblock message

Since we'll be re-inserting ads and paying publishers, we should not get an adblock message. 

This just needs some `app/siteHacks.js` script.

**Comment by bbondy** [comment]
CC @bridiver

**Comment by luixxiul** [comment]
The video itself is gone, even though the script execution is allowed.

According to Devtool,

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-y+Sfag4+EpQGWSl5aJNh2MaSOITKkNcB+cdRcV5lhts='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by luixxiul** [comment]
Confirmed on Windows 10

**Comment by luixxiul** [comment]
From support

> It takes forever to begin loading the page, then it doesn't load all the pictures. I am specifically talking about cnet.com Sorry to say this is a terrible effort.

**Comment by srirambv** [comment]
Similar issue on CBC.ca  Video only plays when Ad/Tracker is disabled.

**Comment by bbondy** [comment]
I don't think this is valid anymore, video player should be working as o 0.12.7.
