### ISSUE TITLE
Tabs movement between two windows

### ISSUE THREAD

**Issue by Jurijus-eHex** [brave/browser-laptop#2934]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
When you are moving tabs from one window to another, firstly, it seems to be impossible, however you can move a tab on top of another tab. I thought I just need to open a new tab and move the existing on top of it. Nope, it changes the title of a tab, but does not load the same page.
**Expected behavior:**
Easily moving tabs between two Brave windows.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win 8.1
- Brave Version:
  0.11.1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
tearing off tabs function made it possible to move tabs between windows.
