### ISSUE TITLE
Lastpass Create account shows blank page when LastPass enabled in Preferences

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2936]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Lastpass create account page is blank when lastpass option enabled under preferences.

**Expected behavior:**
Should load the create account page when enabled.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 Professional,  Windows 7 x64 Professional

- Brave Version:
0.11.2 Dev RC1 

- Steps to reproduce:
    1. Enable Use Lastpass under security preferences
    2. New tab is opened for lastpass account creation which is blank page

- Screenshot if needed:

- Any related issues:

**Comment by BCSWowbagger** [comment]
I have the same issue.  Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/10441939/17784686/fd8aadd0-6542-11e6-9b3d-dfabdd1cac2a.png)

Additionally, the issue occurs sometimes when the LastPass quick login icon is used:

![image](https://cloud.githubusercontent.com/assets/10441939/17784816/8f26ff50-6543-11e6-88ea-44bb63b79732.png)

I have not been able to reproduce this consistently, nor have I detected any clear pattern to the behavior.

**Comment by teagueamania** [comment]
Similar: LastPass won't open edit input for individual sites, produces only blank tabs (sample tab label: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html?dialog=site). Also, onscreen keyboard provided by LP rarely displays, again producing only a blank tab.

Windows 7 Enterprise x64
