### ISSUE TITLE
Memory Leak warning in browser console

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2939]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After installation of RC1 build the browser console shows warning message about Memory Leak 

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64 Prof, Windows 7 x64 Prof
- Brave Version:
  0.11.2 Dev RC1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17401332/fc9e522c-5a44-11e6-9f9f-b9a0fe801a1f.png)

cc @bridiver

**Comment by luixxiul** [comment]
Any steps to reproduce the warning?

**Comment by luixxiul** [comment]
Closed as it is stale

**Comment by bsclifton** [comment]
I don't think I've seen this in a while 😄   Safe to close this one, @bridiver?
