### ISSUE TITLE
Bravery Global/Site settings opens the same Shields page.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2940]
Selecting Bravery Global/Site settings opens the same shields page. Shouldn't the site settings open the shields menu for that page rather than the preferences page? 

Build 0.11.2 Dev RC1

**Comment by luixxiul** [comment]
Duping to #2781?

**Comment by srirambv** [comment]
No not the same.  But looks like its working in the RC2 build as expected. Hence closing.
