### ISSUE TITLE
MSI installer fails to complete setup

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2948]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Windows MSI installer fails to complete the setup.

**Expected behavior:**
Should be able to complete the installation process
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.2 Dev RC2
- Steps to reproduce:
  1. 
     2.
     3.
- Screenshot if needed:
- Any related issues:

**Comment by srirambv** [comment]
Issue exists in 0.11.3 RC3 as well.

**Comment by bbondy** [comment]
The MSI file is only for system administrators and requires special steps. CC @bsclifton

**Comment by bsclifton** [comment]
I'd definitely like to make a wiki page on how to deploy this using the command line :smile: 

Self-assigning and will work towards that.  If the documentation ends up being clear enough, we can consider closing this issue

**Comment by srirambv** [comment]
Setup installs when launched from Command Prompt running as Administrator but don't see run setup as administrator in the right click context menu.

**Comment by srirambv** [comment]
When running from command line with elevated privileges setup completes but the application doesn't show up until a system reboot is done. Tried on Windows 7

**Comment by bridiver** [comment]
confirmed still broken on win7 for 0.12.2rc2

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/6484
> On a Windows 10 VM, I went to Releases page for Brave browser-laptop repo (https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-Preview7)
and downloaded the Windows installer (BraveSetup-x64.msi) for Preview7.
After running the installer, I observed that Brave was not listed as an installed application.

**Comment by willy-b** [comment]
hey @bsclifton, I want to confirm what you suggested in #6484 , using msiexec from commandline works.

Specifically, opening `cmd` as Administrator, and running `msiexec /i BraveSetup-x64.exe` will install Brave properly.

**Comment by bbondy** [comment]
Note that the MSI is not meant to be a general installer, it should be the same as Slack though and meant for network installs for admins:
https://get.slack.help/hc/en-us/articles/212475728-Deploy-Slack-via-Microsoft-Installer

**Comment by 3esmit** [comment]
I wasted 98mb of download in a MSI. Now downloading .exe. Please, fix this.

**Comment by luixxiul** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/6985#issuecomment-276760458
