### ISSUE TITLE
Provide Menu Shortcuts to open when Alt key is pressed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2949]
Menu shortcuts are missing such as 

ALT+F - File Menu
ALT+E - Edit Menu
ALT+V - View Menu
ALT+K - Bookmarks Menu  (suggested)
ALT+B - Bravery Menu (suggested)
ALT+W- Window Menu
ALT+H  - Help Menu

There are missing underlines for the items too. When menu is shown using ALT, the F in File should be underlined for example.

**Comment by hugobuddel** [comment]
The Alt-* keybord shortcuts also do not work on Linux (Brave 0.22.22).

**Comment by bsclifton** [comment]
Marking as `addressed-with-brave-core`. I believe only Linux (distros with a system menu) will visibly show the shortcuts in the menu (same as Chromium). Would be great to confirm
