### ISSUE TITLE
Give ability to change default search engine.

### ISSUE THREAD

**Issue by SKGrimes** [brave/browser-laptop#295]
There is likely a big overlap between people using an unstable, bleeding edge browser that has security built in by design, and people who don't want to use google search. To close issue please add option to change search engine.

**Comment by wklm** [comment]
I could take this ticket

**Comment by bbondy** [comment]
Contributions are definitely welcome and this is definitely wanted, let me know your plan for changing to add the ability to select a different one.  We don't have a preferences page yet but I plan on doing one for 0.8.

**Comment by diracdeltas** [comment]
note that if you change the `defaultOpenSearchPath` in `js/constants/config.js` from Google to `'./content/search/duckduckgo.xml'`, it'll search duckduckgo by default

**Comment by wklm** [comment]
hi @bbondy thanks for answer. I'm absolutely in love with this project so I want to contribute. 
"We don't have a preferences page yet but I plan on doing one for 0.8." So I will wait for 0.8, but is there anything I could help with now?

**Comment by bbondy** [comment]
@wklm we'd really love the extra help, please search the issues list for now, or dogfood for a day and I"m sure you'll have some gripes that will jump out for you. Just post new issues for those.  We want to be in a state that is fully dogfoodable as your default browser. A quick idea that comes to mind is various context menus or drag and drop work.  Another idea is a bookmarks bar.  Just assign yourself to whatever you work on though so no one else duplicates. Thanks!

**Comment by SKGrimes** [comment]
it looks like duckduckgo has been added to the search functionality. I appreciate it, and sure others do as well. +1.

**Comment by bbondy** [comment]
You can now select duck duck go in preferences 0.7.13 or higher (yet to be released), for more engines please post more specific new issues. Thanks!
