### ISSUE TITLE
Cloned tab title replaced with URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2951]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A cloned tab title is replaced with URL. Plus the URL bar doesn't auto hide on the cloned tab

**Expected behavior:**
Cloned tab should display the title correctly and URL bar should auto hide unless the mouse pointer hovers it.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.2 Dev RC2 
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:
  [2798](https://github.com/brave/browser-laptop/issues/2798)

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by luixxiul** [comment]
Closing as stale.
