### ISSUE TITLE
Pressing Enter twice after entering URL clears the URL Bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2952]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After a URL is entered or selected from the suggestion, if the enter button is pressed twice it deletes the URL from the URL bar

**Expected behavior:**
Should only capture the first enter action.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7 x32, Windows 10 x64
- Brave Version:
  o.11.2 Dev RC2
- Steps to reproduce:
  1. Enter any URL or select from the suggestion list
  2. Press enter twice 
  3. URL bar clears the entry 
- Screenshot if needed:
- Any related issues:

**Comment by willy-b** [comment]
FYI, cannot reproduce in Ubuntu 14.04 w/ Brave built from recent master (commit 9213bf0f356dcf0dabb3db8bc1e256a6cc9b0f10 )

**Comment by srirambv** [comment]
Issue still exist in 0.11.3 RC3 after clean install.

**Comment by srirambv** [comment]
Issue seems to be different now. Pressing return twice stops the page load but keeps the entered URL. This is on build 0.11.5

**Comment by srirambv** [comment]
Issue still exists as of 0.12.1 RC1

**Comment by jhreis** [comment]
I was still able to reproduce this issue on 0.12.15. Double clicking enter, brings browser back to 'new tab' page, and clears the URL bar (macOS, Sierra 10.12.1).

**Comment by cqsd** [comment]
Similar issue on 0.13.5; now, styling on the current page completely breaks [1] and attempting to load any other page in the tab (by entering the URL or clicking links) does nothing.

[1] 
![image](https://cloud.githubusercontent.com/assets/8888668/23809149/2cdc2de4-0592-11e7-9866-605ba55af239.png)

**Comment by Shnkc** [comment]
I also experience this issue on MacOsX Sierra 10.12. 

Brave version is 0.14.1

**Comment by jonathansampson** [comment]
I am no able to reproduce this issue (in https://github.com/brave/browser-laptop/commit/0067c4fdd122faeb2227753c7d14a09e168be734) by pressing twice quickly or slowly. Further, even when I rapidly press <kbd>Enter</kbd> multiple times, nothing appears to impede the page from loading.

**Comment by luixxiul** [comment]
Added the QA/required label just now for @srirambv

**Comment by jhreis** [comment]
FWIW I am no longer able to reproduce this on 0.15.2 (af7ef42).

**Comment by srirambv** [comment]
Confirmed issue not reproducible on 0067c4f
