### ISSUE TITLE
URL Bar does not work

### ISSUE THREAD

**Issue by thbtmntgn** [brave/browser-laptop#2956]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** URL Bar clears itself when I press Enter after writing a URL or a search term. 

**Expected behavior:** Go to brave.com if I write brave.com + press Enter

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X El Capitan version 10.11.6

- Brave Version: 0.11.2

- Steps to reproduce:
    1. Write a URL or a search term in URL Bar
    2. Press Enter
    3. See URL Bar clears itself and nothing happen

- Screenshot if needed:

- Any related issues: maybe issue #2952

**Comment by willy-b** [comment]
FYI, I can't reproduce this in Ubuntu 14.04 with Brave built from recent master (commit 9213bf0f356dcf0dabb3db8bc1e256a6cc9b0f10 ). 

Any tips?

**Comment by reesinkf** [comment]
Confirmed for windows 10. Unable to use the browser now except for visiting bookmarked websites :-(

**Comment by cezaraugusto** [comment]
Unreproducible running macOS 10.10 (Yosemite).

**Comment by bbondy** [comment]
Work around is to change your search engine and then change it back.  Seems like an upgrade from old search problem.

**Comment by reesinkf** [comment]
Thank you bbondy, this has fixed it for me!

**Comment by thbtmntgn** [comment]
Yes it works  for me too !

No search engine was defined by default after the last update.

I choosed one and it works !

Thanks !

**Comment by darkdh** [comment]
Test steps:
1. Open `~/Library/Application Support/brave/session-store-1` and find `search.default-search-engine`
2. Modify the value to `content/search/google.xml` or `content/search/duckduckgo.xml` which is our old value of search engine
3. Launch brave and open `about:preferences#search` to see whether `Google` or `DuckDuckGo` is selected

**Comment by zischkau** [comment]
I'm having the same problem after updating Brave on August 5, 2016, running OS X El Capitain 10.11.6.  My home page loads, but can't change the address and typing a URL in a new tab just disappears when I hit return.  The above-mentioned work-around doesn't work on my machine.  Need another fix, quick!

**Comment by pabpas** [comment]
This is still happening on 0.11.6 (Win10) but depends on what I search for. I don't know what the pattern is but the following don't work: "el", "le", "art", "li"... it doesn't matter which or how many characters come after, pressing enter will clear the URL bar.

Other search terms work fine for example: "po", "us", "yo"...
