### ISSUE TITLE
Block scripts auto disabled for Gmail for shields settings at page level

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2960]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Block Scripts gets disabled when Gmail loads when the settings is disabled at page level.

**Expected behavior:**
Block script should still be enabled when Gmail loads to inbox.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 x32 

- Brave Version:
0.11.2 Dev RC2

- Steps to reproduce:
    1. Enable Block scripts at page level for Gmail
    2. Login to Gmail. 
    3. Logs into standard view of inbox. Shields setting at page level shows Block Script disabled.

Works fine when the block script is enabled at global settings.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
> Enable Block scripts at page level for Gmail

What site did you do this on? gmail.com redirects to accounts.google.com or www.google.com pre-login.

**Comment by srirambv** [comment]
Enabled it on accounts.google.com.

**Comment by diracdeltas** [comment]
scripts are whitelisted on a per-subdomain level, so you have to whitelist on `mail.google.com` separately from `accounts.google.com`.
