### ISSUE TITLE
autocomplete JS error

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2961]
> "Uncaught TypeError: Cannot read property 'get' of null" urlBarSuggestions.js:369 and ReactErrorUtils.js:52

Looks like around this line:

` ? this.props.searchSelectEntry.autocomplete : this.props.searchDetail.get('autocompleteURL')`

https://twitter.com/2bithacker/status/761307646557196288

@darkdh could you take a look?

**Comment by 2bithacker** [comment]
Looks like the update to 0.11.2 blanked my default search engine preference, which caused the problem. Once I selected a new default search engine, the location bar started working normally again.

**Comment by bbondy** [comment]
https://twitter.com/TTallis1505/status/761306337502298113

**Comment by bbondy** [comment]
Maybe this is if duck duck go was the default then it doesn't remember and causes that problem?

**Comment by bbondy** [comment]
dupe of https://github.com/brave/browser-laptop/issues/2956#issuecomment-237682157
