### ISSUE TITLE
Changing only the anchor for the URL should not reload the page

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#2963]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I am at a URL with an anchor (#anchor) and I change the anchor text only and press Enter, the entire page reloads instead of making the appropriate changes on the page.

**Expected behavior:**
The browser should try to jump to the anchor's location on the same page instance and trigger the appropriate JS events.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.2
- Steps to reproduce:
  1. Open a page with anchors or JS events that respond to anchor changes. For example, I used the following Gmail URL, which should work for most with a Gmail account: https://mail.google.com/mail/u/0/#search/in%3Ainbox/p2
  2. Change the anchor in the URL **by typing into the address bar**. In my example, I focused the address bar and changed "p2" to "p3", which should flip to the third page of the results.

Expected: In Firefox, what happens is the same thing as if I had clicked the ">" (next page) button in the search results. It just flips to the next page.

Actual: The entire page reloads, and then goes to the appropriate page of results, since the anchor is preserved

**Comment by bridiver** [comment]
I'm not able to replicate this on 0.11.5 or 0.11.6. I tried gmail and also http://www.w3schools.com/html/tryit.asp?filename=tryhtml_links_bookmark

**Comment by gulkily** [comment]
Try going to http://www.example.com/ and then changing the URL to http://www.example.com/#test. I see the page refresh when I do this.

Here is what it looks like in Gmail: 
![2963 mov mp4 m4v](https://cloud.githubusercontent.com/assets/1530699/18184671/25a5f60a-7068-11e6-86f1-5ec2115636dd.gif)

**Comment by bridiver** [comment]
oh, you are typing the new url in the urlbar? I guess I misunderstood the replication steps. Can you clarify them in the original post? I can replicate if I type the url in the urlbar

**Comment by gulkily** [comment]
Thanks for the feedback, @bridiver. I updated the steps to reproduce to be more clear.

**Comment by MargarytaChepiga** [comment]
I tried to reproduce this on Windows 10, but it works as expected there.
