### ISSUE TITLE
Allow bulk deleting bookmarks

### ISSUE THREAD

**Issue by tschf** [brave/browser-laptop#2970]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Can not bulk delete bookmarks. If I go into the bookmark manager, I can not select multiple bookmark entries in order to delete a bunch at once.

One work around was to add them to a temporary folder, and then delete that folder - but even that can be time consuming if you want to delete a lot.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):  

Ubuntu 16.04 x64  

- Brave Version:  

Brave: 0.11.1
Electron: 1.2.7
libchromiumcontent: 51.0.2704.103
V8: 5.1.281.65
Node.js: 6.1.0

- Steps to reproduce:

Go to the bookmark manager, and attempt to select on any bookmark - in order to select a series of bookmarks. But it doesn't stay focused, so selecting multiple will not be possible. Have to drag all bookmarks you wish to delete into a folder and then delete that folder.

**Comment by tbergeron** [comment]
I was surprised to see this wasn't possible. I imported a bunch of crappy bookmarks I didn't wanted and now I'm stuck deleting them one by one, I wish I could at least "clear all bookmarks" and start fresh. I guess I could delete my profile though?

**Comment by bsclifton** [comment]
This should be fixed very soon :smile: You'll be able to shift click and/or ctrl/cmd  click to select multiple entries to delete

I'm going to close this issue since it's technically a duplicate, but you can track the progress here https://github.com/brave/browser-laptop/issues/1005
