### ISSUE TITLE
Allow empty titles on bookmarks

### ISSUE THREAD

**Issue by tschf** [brave/browser-laptop#2972]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

For some of my bookmarks, the favicon is enough. In my bookmark bar, I leave a few without titles. Others still need a title (I note the settings allow to just use favicons, just titles or both - but I don't want a blanket rule for all bookmarks, so I leave some without a title).

If I try to update the bookmark entry with no title, it will just revert to the previous value. 
Or, if I import bookmarks with no title, the URL is displayed instead of the title.

note: I'm mindful of the fact that you allow favicons to be turned off (default) may cause issues as nothing will be displayed in the default configuration when no title is there (favicons are switched off in a fresh install).

**Expected behavior:**

Removing the title property should keep it that way - blank. 
- Platform (Win7, 8, 10? macOS? Linux distro?): Linux, Ubuntu 16.04 x64
- Brave Version: Brave: 0.11.1
- Steps to reproduce:
  1. Import bookmarks
  2. Any bookmark with no title will show the URL instead of leaving it blank - falling back to the URL field

(Perhaps a solution is to show URL only when favicons are set to not display and title is blank)

One work around is to save it with a single space (to force a blank title to save).
- Screenshot if needed:

Section from Chrome:

![image](https://cloud.githubusercontent.com/assets/1747643/17425935/3176a2de-5b16-11e6-84b8-3867420ea1b1.png)

After importing into Brave

![image](https://cloud.githubusercontent.com/assets/1747643/17425942/407315c4-5b16-11e6-9812-90ca131cd0a6.png)

After specifying title with a single space

![image](https://cloud.githubusercontent.com/assets/1747643/17426108/f37bfe82-5b17-11e6-985e-c0e4a5bdfc0e.png)
- Any related issues: #2672

**Comment by bsclifton** [comment]
This would be easy to do; @bradleyrichter, what do you think? @tschf makes a great point about the bookmarks disappearing if favicons are turned off

**Comment by Liunkae** [comment]
+1 from #8957 (Impossible to add bookmark with empty name)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmark-naming-favicons/5781?u=eljuno
> Allow us to name a bookmark ‘nothing’, as in have no characters in the name. Right now at least one character is required.

**Comment by luixxiul** [comment]
Do they really want to name nothing to bookmarks or display only favicons? Some of them look that they simply do not know about that option: https://community.brave.com/t/bookmark-naming-favicons/5781/2

**Comment by Liunkae** [comment]
From the first comment in this issue (https://github.com/brave/browser-laptop/issues/2972#issue-169525969):
> For some of my bookmarks, the favicon is enough. In my bookmark bar, I leave a few without titles. Others still need a title (I note the settings allow to just use favicons, just titles or both - but I don't want a blanket rule for all bookmarks, so I leave some without a title).

So some users want to mix bookmarks with and without titles.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmarks-toolbar-cannot-just-leave-icon-removing-text/10962?u=eljuno

**Comment by ashrafhadden** [comment]
+1 For allowing import of empty titles on bookmarks leaving only the favicon. Editing the code to include a space sounds like an easy temp hack. 

I myself also enjoy using both blank (leaving just favicon) and text bookmarks (text + favicon) on Chrome. Also seeing as most users will be coming from Chrome it would be helpful if "Text and Favicons" was the default option in the Brave General>Bookmarks Bar preferences.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/allow-empty-names-in-bookmarks/14867?u=eljuno

> I know, there is the option to only show the favicons, but I’d like to be able to remove the title of specific bookmarks. The reason for that is some favicons are “unique” in my bookmarks so I know what page will be navigated to. However, for some bookmarks like youtube videos I’d like to see the title too as they all have the same favicon.

**Comment by revelt** [comment]
I was about to create an issue about this - that's a must and no-brainer. Reasons why we need this issue:

* User knows his/her most-used bookmarks anyway, title is redundant, visual picture only reduces cognitive load since there's less info surrounding the bookmark button
* Saves space
* Differentiates from folder-bookmarks - I keep my top-bookmarks on the leftmost edge and they don't have titles. Whatever has titles is a folder. This way I differentiate the two and optimise the space.

👍 👍 👍

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmarks-bar-favicons-and-text-selected-problem/17259?u=eljuno

> In other browsers if I delete the title text I can have the favicon only. I can also have text if I leave the title. In Brave if I delete the title it shows a snippet of the url instead.

**Comment by MargarytaChepiga** [comment]
What if the website doesn't have a favicon?

**Comment by bsclifton** [comment]
@MargarytaChepiga we currently default to a document icon when a favicon is not available:
![screen shot 2018-03-09 at 11 36 02 pm](https://user-images.githubusercontent.com/4733304/37239113-acb59940-23f2-11e8-9367-226f469bd51b.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/suggestion-bookmark-titles/26063?u=eljuno
