### ISSUE TITLE
v0.11.2 - not able to browse the internet at all

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#2973]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**
Just downloaded the new version of brave v0.11.2. Now when I type something in the url bar and hit Enter key, for example brave.com the input just clears and I stay on the same page, in this case my home page. This is valid for whatever I type n the URL bar, no matter if it is a website or search term that should be searched in duckduckgo. Also while I am typing I do not get any autocomplete from history or bookmarks as suggestions.

**Expected behavior:**

I can visit websites when I type their url.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Fedora 24.

- Brave Version:
v0.11.2

- Steps to reproduce:
    1. Type something in the url bar.
    2. Hit Enter
    3. Nothing happens

- Screenshot if needed:

- Any related issues:

**Comment by ayumi** [comment]
Might be related to https://github.com/brave/browser-laptop/issues/2956#issuecomment-237695115 .

Does it work if you re-set a search engine in Preferences -> Search?

**Comment by Sh1d0w** [comment]
@ayumi I guess I missed this ticket >.<

When I went to the Settings -> Search I saw there was no default search engine selected after the upgrade. After I marked duckduckgo as default everything seems to wrok as normal.

Thank you.
