### ISSUE TITLE
Delete key doesn't work on selected text in a URL prediction

### ISSUE THREAD

**Issue by tschf** [brave/browser-laptop#2974]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

When typing in a URL, Brave will predict a location on the specified site. For example, if I start typing `github.com`, the prediction will become one from my bookmarks, `https://github.com/dbr/tvnamer`. But I don't want to actually go there. At this point, to the right of my cursor is highlighted. 

If I hit the `DEL` key on my keyboard, nothing happens on first hit. Second hit, the selection switches off and places my cursor at the end of the URL.

Even if I click right to go to the end of the URL and effectively accept their suggestion, then manually highlight some text, and hit `DEL`, still, nothing happens.

(note: backspace works fine)

![screenshot from 2016-08-05 15-12-13](https://cloud.githubusercontent.com/assets/1747643/17426889/9cfd96ee-5b1f-11e6-81b5-2392b2a738b7.png)

If I click out of the address bar and back in, the whole URL is highlighted. `DEL` works here.

Side thought: I notice there's a config for location bar settings. Might be good to prioritise history over bookmarks somehow - I'd probbaly more frequently want predictions on history then bookmarks.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux, Ubuntu 16.04 x64

- Brave Version: 0.11.1

**Comment by Sh1d0w** [comment]
Did you try the new version 0.11.2 where this is marked as fixed?

https://github.com/brave/browser-laptop/releases/tag/v0.11.2dev

**Comment by tschf** [comment]
Oh no. My apologies, I thought I was on the latest as when I did `Help.. Check for updates`, it reported I'm on the latest version.
