### ISSUE TITLE
Enabling Block Script in global settings doens't apply to websites which are already opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2978]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling Block script in global settings would not apply to all the websites which are already opened before enabling it in shields settings

**Expected behavior:**
Enabling block script should apply to all sites as its  a global setting irrespective of sites which are already opened before enabling it. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2 RC2

- Steps to reproduce:
    1. Make sure block script is disabled at global settings
    2. Open couple of websites in different tabs
    3. Now enable block scripts at global settings
    4. Reopen the sites which were already opened before enabling 
    5. Block script is disabled at page level for those websites. Global settings apply only for the new ones which are being opened.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
There's no easy way to fix this other than reload all open tabs when block-script is checked. I'm inclined to mark this wontfix since this is how it works for all bravery settings.

**Comment by bbondy** [comment]
agreed
