### ISSUE TITLE
PDF structure is invalid

### ISSUE THREAD

**Issue by joost-xyz** [brave/browser-laptop#2981]
Brave 0.11.2
Mac OSX El Capitan

My mobile phone PDF invoice does not open in brave, the message is 'PDF structure is invalid'. When I open the same invoice in Chrome, it opens instantly.

**Comment by neeklamy** [comment]
Dupe? #2919

I’m guessing you’re using Chrome’s built-in PDF viewer, could you try your PDF invoice in the Google app store [PDF Viewer](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm) (it uses the same PDF.js project that Brave is using for PDF display).

If it has the same problem, then it’s upstream with the PDF.js folk. If it doesn’t repo, then it could well be a problem with Brave.

One other thing you could do, although slightly tricky considering this PDF has private information, is to run it through a PDF validator. Most of the validators are online (great!) or sold for big bucks. There is this project though, they’ve got a cross platform application, [veraPDF](http://verapdf.org/software/).

**Comment by srirambv** [comment]
@joost-xyz  is that a password protected file?

**Comment by joost-xyz** [comment]
@srirambv, no, it's not.

**Comment by joost-xyz** [comment]
@neeklamy,

Seems you are right, this is a dupe of #2919. Sorry.
