### ISSUE TITLE
Brave 0.11.2 URL Bar removes what is typed

### ISSUE THREAD

**Issue by mischapeters** [brave/browser-laptop#2982]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
As soon as I try to enter a URL or search term in the URL bar it removes what is typed and doesn't load the page.

**Expected behavior:**
It should keep the text and load the page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.11.6

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Open Brave
    2. Enter text in the URL bar

**Comment by srirambv** [comment]
same as [2956?](https://github.com/brave/browser-laptop/issues/2956)

**Comment by mischapeters** [comment]
Ah yes, was looking for open issues. Sorry. Duplicate closed.
