### ISSUE TITLE
Uncaught error for Lastpass login in browser console.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2983]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Uncaught error in browser console when clicked on the Lastpass login icon in page form

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64 
- Brave Version:
  0.11.2 Dev RC2
- Steps to reproduce:
  1. Open http://international.nytimes.com/
  2. Click on Login. 
  3. Click on the Lastpass Icon in the email field
  4. New tab opens for Lastpass login which is a blank page
  5. Browser console contains the error
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17432635/2dd9cd2c-5af8-11e6-9efe-487d4270e08e.png)
- Any related issues:

cc: @bridiver  @diracdeltas

**Comment by bridiver** [comment]
these errors have been happening since https://github.com/electron/electron/pull/5293
The don't actually appear to break anything, but I'm planning to revert to my original fix
