### ISSUE TITLE
Unable to move tabs from one tab set to the next one

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2984]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Tabs created in one tab set can only be moved across in the same tab set. 

**Expected behavior:**
Should be able to move tabs from one tab set to the other
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Guessing its on all platforms
- Brave Version:
  0.11.2 Dev RC2
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Does this issue still exist?

**Comment by srirambv** [comment]
Works only if you pull the tab on the new tabset and drop it. Just by dragging it after the last tab doesn't move to the next tabset.

**Comment by Liunkae** [comment]
Duplicate of #557.
