### ISSUE TITLE
Social media buttons not rendered when Ad/Tracking is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2985]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Social media buttons not rendered when Ad/Tracking is enabled. 

**Expected behavior:**
Should load all social media buttons when the page is loaded.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64, Windows 7 x32
- Brave Version:
  0.11.2 Dev RC2
- Steps to reproduce:
  1. Open https://thehackernews.com/
  2. The social media buttons under each article only shows Google+ and Facebook. Doesn't load the other three.
  3. Disable Ad/Tracking on the page, all social media images are loaded correctly.
  4. Popup window for ShareThis doesn't work since the script file and CSS files are blocked under Ad/Tracking
- Screenshot if needed:
  Chrome Vs Brave
  ![image](https://cloud.githubusercontent.com/assets/17010094/17438136/383873ec-5b19-11e6-9bfa-1c270318fee3.png)
- Any related issues:

**Comment by lukemulks** [comment]
FYI - I'm rolling this issue into a parent initiative that I'm working on for social media network ads (w/in networks, and in embedded widgets and SDKs in the larger Web) - Tracking that initiative here for reference: #7678

**Comment by lukemulks** [comment]
Confirming that as of v0.14.0 (potentially earlier) social media buttons are showing up with shields enabled. 

Screenshot captured below for reference. 
![brave-social-buttons-03312017-thehackernews](https://cloud.githubusercontent.com/assets/8979240/24571079/ec9d201a-1623-11e7-8f86-3e30875e3572.PNG)

I'm going to close this issue, but if it resurfaces again we can reference this issue and open a new one.
