### ISSUE TITLE
Opening a new session tab launches Lastpass account creation page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#2986]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening a new session tab by pressing Ctrl+Shift+S launches a Lastpass account creation page in a new session tab.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, Windows 7 x32

- Brave Version:
0.11.2 Dev RC2

- Steps to reproduce:
    1. Enable Lastpass under Password manager settings
    2. Open a new session tab by pressing Ctrl+Shift+S
    3. A new tab is opened with Lastpass Account creation page

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
dup #2408
