### ISSUE TITLE
Undefined error dialog caused by zoom upgrade path

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#2989]

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/4d02cb87cc19279257abb83ee4c7c0803b723e4f

**Comment by bridiver** [comment]
Steps to reproduce error:
1. Open any file url

**Comment by bbondy** [comment]
**Steps to test:**
1. Use Brave 0.11.2 and open a file URL
2. You should get an undefined error popup
3. Close
4. Install 0.11.3 and the error should be gone
