### ISSUE TITLE
Can't navigate via URL after update

### ISSUE THREAD

**Issue by marcantonio** [brave/browser-laptop#2998]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

I updated to 0.11.2 and now I can't navigate with the URL box.  When I enter a URL and press enter the URL reverts to whatever was in there before and nothing happens.

**Expected behavior:**

I expected to go to the URL I entered.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac OS X 10.11.5

- Brave Version:

0.11.2

- Steps to reproduce:
    1. Enter a URL
    2. Press enter

**Comment by Ericson578** [comment]
I'm seeing the same behavior, the browser has been rendered unusable.

**Comment by ayumi** [comment]
Could be related to https://github.com/brave/browser-laptop/issues/2956#issuecomment-237695115 .

Does it work if you re-set a search engine in Preferences -> Search?

**Comment by Sh1d0w** [comment]
This has been fixed in the latest version 0.11.3

https://github.com/brave/browser-laptop/releases/tag/v0.11.3dev
