### ISSUE TITLE
Installer problems with Windows 10 x64 and no VS2013 redist

### ISSUE THREAD

**Issue by boozedog** [brave/browser-laptop#300]
If Visual Studio 2013 redist is not installed then the installer fails.

First the splash screen appears, then after a short delay, I see the following error box:

![image](https://cloud.githubusercontent.com/assets/1410808/12537607/020c9db4-c291-11e5-94d7-453c0984946c.png)

If I click OK, then the same box appears one more time. Click OK again, and then the installer quits and nothing happens.

**Comment by bbondy** [comment]
@aekeus please investigate after the DAU stuff. Thanks.

**Comment by bbondy** [comment]
@boozedog The installer works right, just not executing the binary after installed?

**Comment by bbondy** [comment]
@boozedog also please compare to Slack because we're on the same stack as there

**Comment by boozedog** [comment]
@bbondy ahh yeah you're right. I see that the app is successfully installed to my \AppData\Local\Brave folder. So it's just not able to execute the binary.

**Comment by bbondy** [comment]
So I'm thinking we either have to change the way we're compiling electron-prebuilt or include the redist inside the installer.

**Comment by boozedog** [comment]
Correction: app is installed to my AppData\Local\Brave\app-0.7.7 folder.

**Comment by bbondy** [comment]
this is no longer a problem, closing.
