### ISSUE TITLE
Trouble using Brave to connect to public wifi

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3000]
**Did you search for similar issues before submitting this one?**
Yep.

**Describe the issue you encountered:**
I'm not really sure how this stuff works on a technical level. But when I go to a coffee shop that has one of those open wireless networks where when you try to visit a site it prompts you to log in or agree to their terms of service, I can't hit that page from Brave.

Could it be caused by the HTTPS Everywhere functionality?

**Expected behavior:**

I'd type in google.com or something and be redirected to their wifi access screen.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version:

0.11.2

- Steps to reproduce:
    1. Go to Starbucks
    2. Connect to their "Google Starbucks" wifi
    3. Open Brave and try to navigate to a site
    4. See an SSL error
    5. Open Chrome
    6. Try to navigate to a site
    7. See the starbucks page

- Screenshot if needed:

- Any related issues:

**Comment by ConorIA** [comment]
This is probably a silly workaround, but when I hit https problems on my phone, I try to visit a insecure page so that I will get redirected to the WiFi login page. Ask seems to not forward to https on Brave. http://www.ask.com/

If you try to navigate to ask.com, it might work!

**Comment by darkdh** [comment]
Hi @jkup,
Could you screenshot the certificate info by clicking `Advanced settings`=>`Show Certificate` when you are on SSL error page?

**Comment by jkup** [comment]
@darkdh Yep next time I go to a coffee shop I'll snag a screenshot and post it here (hopefully today!)

**Comment by jkup** [comment]
I may well go and close this issue. I haven't been able to reproduce recently. Anyone else?

**Comment by diracdeltas** [comment]
next time please try with HTTPS Everywhere turned off. this is a known HTTPS-Everywhere issue sometimes

**Comment by jkup** [comment]
@diracdeltas it happened again and that did the trick. Is there a bug to fix on our end or should I just close this ticket?

**Comment by diracdeltas** [comment]
let's close for now
