### ISSUE TITLE
Flash not detected on some Linux Distros

### ISSUE THREAD

**Issue by Derex-x** [brave/browser-laptop#3006]
**Did you search for similar issues before submitting this one?**
yes - seems to be a problem yet people mention only partially undetected sites.
**Describe the issue you encountered:**
pepperflashplugin-nonfree package installed but not allowing me to turn on in settings 

**Expected behavior:**
Flash to be installed and working via any browser (brave) 

(simple fix to have flash installed/incorporated into brave install)
^ best possible fix for any/all users
add info on installing flash as this is used by 90% of the web still. and it would cause less people posting about it. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
linuxmint
- Brave Version:
brave_0.11.2_amd64.deb (newest linux version via website)
- Steps to reproduce:
    1. install brave
    2. install flash
    3. watch as it didnt work

- Screenshot if needed:
no, because it would be pointless the flash "on/off" button is not even functional.
- Any related issues:
? yes. flash not working, flash not working via certain websites, flash not detected by sites, flash unable to inc. into brave

**Comment by Derex-x** [comment]
linuxmint 17.2 (i believe) but unsure now

**Comment by srirambv** [comment]
Confirmed on OpenSuse 42.1 as well. Flash detected on Firefox but not on Brave

Brave Version: 0.11.3

![image](https://cloud.githubusercontent.com/assets/17010094/17456989/90158cda-5be1-11e6-81c1-8d01cdfb67d1.png)

**Comment by Derex-x** [comment]
updated some info via post and title.

requesting that flash is installed along with brave as this would cause them to be incorporated with each other and needs to be as most web uses flash still and will till the end of the internet.

just because something is obsolete doesnt mean its not worth incorporating with your browser.

till then keep me posted as i wont use brave

**Comment by dlion** [comment]
Same on Slackware and Brave 0.11.3

**Comment by diracdeltas** [comment]
Not sure why this was labeled wontfix. @Derex-x @dlion @srirambv where is the pepperflashplugin-nonfree library installed? currently Brave only looks in `/usr/lib/{pepperflashpluigin-nonfree, PepperFlash}`.

**Comment by dlion** [comment]
@diracdeltas On Slackware current the chromium-pepperflash-plugin is in /usr/lib64/chromium/PepperFlash directory

**Comment by srirambv** [comment]
@diracdeltas On OpenSuse its under /usr/lib64/chromium/PepperFlash as well. Flash plugin is under /usr/lib64/flash-plugin/

**Comment by capouch** [comment]
I'm a Slackware user and I can tell you that this incredibly convoluted mess with respect to needing to have Flash around is a very, very stiff disincentive against using Brave.  I've been an hour here battling (Slackware), have libpepflashplayer.so in /usr/lib/pepperflashplugin-nonfree, but Brave still grays out the switch in the settings pane.  There seem to be a hundred places offering advice on how to solve this issue, none of which works.  Extremely frustrating for someone who really would like to use Brave as his primary browser.

**Comment by capouch** [comment]
OK I got this solved--gasp!--by looking at the source code.  I was leaving out step 3 below.

FWIW:

1. Create /usr/lib/pepperflashplugin-nonfree
2. In it, place libpepflashplayer.so from a working Chrome/chromium instance
3. (CRUCIAL) That directory must also contain manifest.json or Brave won't see it

I got my pepperflash library file from a Chrome 52 instance.  I notice that the library is now missing from the latest Chrome version, 54. I haven't followed up as to what that means.

**Comment by diracdeltas** [comment]
@capouch thanks for looking into it. unfortunately we cannot detect the Flash install location consistently for all linux distros, and we can't bundle Flash because of the licensing and security problems associated with it. I'll add your troubleshooting instructions to https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues

**Comment by capouch** [comment]
Thanks.  I'm using [http://www.ebizmba.com/articles/best-flash-sites](url) for testing.  Some of the sites linked aren't live anymore, but of the remaining ones, some of them work, and some do not.  

I hope eventually this will all get settled out.  I wish Flash were less common, but I still find it all over the place.
