### ISSUE TITLE
Autoscroll functionality for Linux / Mac

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#3007]
If you have the necessary time, can you add autoscroll functionality for Brave on Linux? Normally, the scroll wheel is used on Linux to paste text that has previously been selected, as an alternative to Ctrl+C - Ctrl+V.
Firefox has this already built it ("Use autoscrolling" in preferences). On Chrome, this is not available.

I found this extension that works on Chrome: https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan

Also, their GitHub page with the source code: https://github.com/Pauan/AutoScroll
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 16.04 LTS
- Brave Version: 0.11.3

**Comment by vitya1** [comment]
Why there is Mac/Linux only? Does windows have native scrolling by middle button clicking feature?

**Comment by Tehian** [comment]
Any update on this one? It become a habit to me to use autoscroll and I can't use Brave as my default browser without it.

Is there an easier way to integrate it into Brave as you already have the source code and to make a switch with off as default? It would be greatly appreciated!

**Comment by TheMarketAnarchist** [comment]
I too was hoping autoscroll could be added. Can anyone from the dev team copy how Firefox handles autoscrolling in Linux? I use Brave all the time and still try to middle-click to start scrolling quickly only to see the blue highlighter shake me back to reality! :)

In all seriousness, I get it would be difficult implementing this as Chromium does not natively support autoscroll, but I and many other users would sure appreciate any attempts!

**Comment by JaneSmith** [comment]
+1 for this. This seems like a basic usability feature to me. Not having autoscroll on Linux is absolutely horrible. This is one of the major things blocking me from using Brave as my main browser.

As mentioned above, Chromium does not have this feature on Linux, but Firefox does. In my opinion, even on Windows, Firefox's autoscroll implementation is miles better than Chromium's. It has a better UI, and much better precision regarding how the mouse position translates to scrolling speed. Chromium's Windows autoscroll always feels difficult to control to me and ends up scrolling too fast, while Firefox's cross-platform autoscroll is a joy to use.

It really would be great if Brave could handle this in a similar way to Firefox.

**Comment by bsclifton** [comment]
This will be addressed with [brave-core](https://github.com/brave/brave-browser), since you'll be able to use the mentioned AutoScroll extension:
https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan

We won't be able to fix this before moving to brave-core

**Comment by bsclifton** [comment]
@JaneSmith @necrophcodr I don't believe it'll be fixed with brave-core (without extensions), as it seems this functionality is not present in Chrome. You can try for yourself by downloading here:
https://github.com/brave/brave-browser/releases

Since the extension is poor functionality, I'll open an issue in our new repository asking for that functionality. Hold tight-

**Comment by bsclifton** [comment]
@JaneSmith @necrophcodr created https://github.com/brave/brave-browser/issues/959 to track this in [brave-core](https://github.com/brave/brave-browser)
