### ISSUE TITLE
Update loop in Brave

### ISSUE THREAD

**Issue by ianimobli** [brave/browser-laptop#3010]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Despite contacting support many times over the last few months, they fail to fix this simple issue.  I tried even removing Sparkle updater or whatever its called. 
Brave updates it relaunches but the update does not apply or it is not recognized and so when i press on update again it says update ready it applies the update and etc..

**Expected behavior:**

after update is done it is applied and done with. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
mac os 10.11.6
- Brave Version:
the one before the latest updated
- Steps to reproduce:
    1. Click on Brave
    2. Check for Update
    3. Click Update
    4. After update is done and browser restarts repeat step #1-2, you will see update is again available then click on step 3 then welcome to the loop

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #2184. Please try this: https://github.com/brave/browser-laptop/wiki/End-User-FAQ#updates-are-available-but-applying-them-doesnt-work-on-os-x
