### ISSUE TITLE
Autofill should not happen on URL bar unless item in autocomplete list is clicked

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3012]
From support:
> When I try to paste a hyperlink or type something in I need to ensure the cursor is far away from the drop-down history in the URL address bar, otherwise it auto-fills with one of those links and then starts appending what I'm typing onto it. The auto-fill shouldn't happen unless I click on the hyperlink from the history when the drop down box appears.

Sometimes I notice this too.

**Comment by willy-b** [comment]
I pushed a commit to my fork that makes sure that mousing over URL autocomplete suggestions does not disrupt the URL you are typing.

However, havnig a strange issue where clicking autocomplete suggestions after the first one occasionally updates the URL bar but does not close the autocomplete suggestions dropdown and does not load the new URL. Frustratingly, it is intermittent.

Somehow the mouseover handler generated by `navigateClickHandler` in `getNewSuggestionList()` is not always being invoked. Anyway, a commit shows up as associated with this issue but there won't be a PR from me until I fix this other problem (hopefully shortly).
