### ISSUE TITLE
Request - Add "block element"

### ISSUE THREAD

**Issue by Derex-x** [brave/browser-laptop#3015]
**Did you search for similar issues before submitting this one?**
nope. but doubt its there.
**Describe the issue you encountered:**
"unique ad" "right-click" "block element"
**Expected behavior:**
block element (and add a way to block lowest part of said element "example : block chatango room (chatango.com, room.chatango.com, room.chatango.com/pyro, ect.) and a way to remove said block
- Platform (Win7, 8, 10? macOS? Linux distro?):
Brave
- Brave Version:
11.2 linux distro
- Steps to reproduce:
none

**Comment by luixxiul** [comment]
Duping to #344
