### ISSUE TITLE
1Password error (code signature could be verified)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3017]
From support:
> <img width="719" alt="screenshot 2016-08-07 1 42 19" src="https://cloud.githubusercontent.com/assets/3362943/17457969/44012a02-5c40-11e6-9acf-46894a8f9584.png">

**Comment by bbondy** [comment]
This is covered in the FAQ until 1Password adds support for this in windows:
https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-use-1password
