### ISSUE TITLE
Entering full web address should navigate to the website instead of searching

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3020]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Entering full web address gets searched by default search engine

**Expected behavior:**
Should directly open the website rather than searching for it
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.3
- Steps to reproduce:
  1. Enter websites full address in the URL bar
  2. Full address gets listed as search item
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17459153/e5c1f2fc-5c24-11e6-869a-a5789dc8bc8b.png)
- Any related issues:

**Comment by bsclifton** [comment]
This has been fixed for a while
