### ISSUE TITLE
Menu should only be built once

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3022]
We currently build a menu from template multiple times.
We should instead only do this only once, the call to `Menu.buildFromTemplate` returns a menu object and we can use it to find items in the menu and update them as needed.

The problem that happens is when a menu is regenerated and the menu is expanded, then clicks on menu items won't work. This happens especially around when the app starts if you try to quit the menu item click doesn't work.

**Comment by bsclifton** [comment]
Checking this out now...

**Comment by bsclifton** [comment]
While not ideal, some great improvements were made with https://github.com/brave/browser-laptop/pull/3055

The dynamic menus (Bookmarks/History) which are in development presented a challenge. Electron doesn't expose a way to remove MenuItems currently ([it's definitely possible from a win32 perspective](https://msdn.microsoft.com/en-us/library/windows/desktop/ms647629(v=vs.85).aspx), I'm not sure about X11/macOS)
