### ISSUE TITLE
Support tray progress bars for downloaded items

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3023]
## Test plan
1. Go to https://brave.com/downloads.html
2. Download one of the builds
3. Notice the taskbar icon has a progress bar. If macOS, a badge is shown with # of concurrent downloads

## Original issue description
BrowserWindow has a way to set progress which shows up in the tray. This is useful for downloading items.  We should show the overall progress of all downloads in the try w/ `BrowserWindow`'s `setProgressBar`

**Comment by bbondy** [comment]
We should also set the electron.app.dock's dock.setBadge with the number of downloads that are active when > 0

**Comment by bsclifton** [comment]
Here's a great page for reference, for anyone wanting to tackle this :smile: 
http://electron.atom.io/docs/tutorial/desktop-environment-integration/

**Comment by chirag64** [comment]
Hi,

I'd like to attempt a PR for this.

I tried setting the `setProgressBar` to a hard coded value and I was able to set the progress bar of the icon in the taskbar. The place where I'm guessing we need to add this code is in [electronDownloadItem.js inside the updateElectronDownloadItem()](https://github.com/brave/browser-laptop/blob/8feebec2966f7f1240e8a7eb398962d48dd62200/app/browser/electronDownloadItem.js#L16).

But I'm unable to find the download percent at this location. I would appreciate some help with this.

Please let me know if I'm approaching this the wrong way.

**Comment by timborden** [comment]
Hey @bbondy and @bsclifton, I just submitted a PR #9864 for this

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/downloads-progress-meter/4550/3
