### ISSUE TITLE
Support dock menus

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3024]
We should show at a minimum new window, new private window, and the list of windows there.
The list of windows would show the window title (i.e. active tab title)

Edit: Use `app.dock.setMenu(menu)`

**Comment by bbondy** [comment]
I think windows will show up just by using `role: 'window'` for macOS at least.

**Comment by bsclifton** [comment]
Here's a great page for reference, for anyone wanting to tackle this :smile: 
http://electron.atom.io/docs/tutorial/desktop-environment-integration/

**Comment by bsclifton** [comment]
Windows functionality broken out to https://github.com/brave/browser-laptop/issues/6094 since a PR was submitted for this (thanks, @NejcZdovc!)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6087#issue-194308164
