### ISSUE TITLE
Is there a way to update brave offline?

### ISSUE THREAD

**Issue by johnmarzan** [brave/browser-laptop#3026]
if i downloaded a new installer of brave, should i first uninstall the old version? or i can just open the installer and it will remove the old version and install the new one?

**Comment by Liunkae** [comment]
Which platform are you on (Windows, macOS, Linux distro)?

**Comment by johnmarzan** [comment]
windows 7.

**Comment by Liunkae** [comment]
Sorry for the late reply.

I haven't tried it, but I think you can just run the installer, and it will install over the old version.

**Comment by bbondy** [comment]
yes if you have an installer you can just install on top.
