### ISSUE TITLE
Errors playing video on FoxBusiness.com

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3027]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Console errors  when trying to watch video.  Plays fine in Chrome (rolls an ad at beginning). I tried turning shields off, no difference.

In the developer console, the following is reported which may hint at the root cause:

```
loadInternal @ xhr-loader.js:104
xhr-loader.js:104 XMLHttpRequest cannot load http://foxbusiness-f.akamaihd.net/i/BrightCove/854081161001/201608/3051/854…92001_5068842750001,297001_5068842750001,.mp4.csmil/index_0_av.m3u8?null=0. Failed to start loading.loadInternal @ xhr-loader.js:104
xhr-loader.js:104 Mixed Content: The page at 'https://video.foxbusiness.com/v/5068842750001/do-the-koch-brothers-own-the-gop-elites-/?#sp=show-clips' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://foxbusiness-f.akamaihd.net/i/BrightCove/854081161001/201608/3051/854…92001_5068842750001,297001_5068842750001,.mp4.csmil/index_0_av.m3u8?null=0'. This request has been blocked; the content must be served over HTTPS.
```

**Expected behavior:**
Video loads and plays
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS (but likely on all)
- Brave Version:
- Steps to reproduce:
  1. Go to https://video.foxbusiness.com/v/5068842750001/do-the-koch-brothers-own-the-gop-elites-/?#sp=show-clips
  2. Click play on video
  3. Notice it doesn't load; open developer console and see errors
- Screenshot if needed:
- Any related issues:

**Comment by lukemulks** [comment]
Hola @bsclifton I've been running thru shield-related webcompat issues, and noticed this one. 

I found a workaround that allows for foxnews.com vids to play, after working thru a similar issue that involved user authentication on the FoxNews live stream. 

Issue is here for reference: https://github.com/brave/browser-laptop/issues/2159

**Workaround, in a nutshell:** 

- Mixed content/protocol issues, even with Shields down. 
- To workaround, disable shields (including HTTPSe), and hardcode the URL from https:// to http:// and hit enter to load the page w/the http:// URL.
- **_I've been able to play video with the steps applied above._** 

Note: this workaround also worked for this webcompat fox issue: https://github.com/brave/browser-laptop/issues/3027

Obv not ideal given what the workaround involves, but may help for short-term resolution.

**Comment by diracdeltas** [comment]
this works now when ads are allowed

**Comment by diracdeltas** [comment]
this works now when ads are allowed

**Comment by lukemulks** [comment]
thanks will take a look.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/it-would-be-nice-to-fully-switch-to-brave-but-many-videos-dont-play/26550
>Websites that I have tested and Brave doesn’t work are teletica.com, multimedios.cr / multimedios.com, and channels from rojadirecta.me, livetv.sx and other websites like that.
Many of the games or livestreams on those websites I can even watch on tv but sometimes I have to be on the computer and use websites for that even with the delay and all.
>
>But what I have noticed about Brave ads blocked log in Teletica, multimedios is that there is always a “blob:” entry on it being blocked, for example: “blob:http://mdstrm.com/9a86548b-71f4-4826-8104-8ceae0c41e46” and that should be the one that would bring the media to be played by the browser.

**Comment by Emiiiii** [comment]
I was the one on the community that reported these issues 7 days ago. Most videos seem to work fine now, and if they don't they work if i turn HTTPS everywhere off and allow cookies or something like on Repretel.com, but now it is easier to watch videos on Brave.

But I have noticed more sites where video only plays if "Allow ads and tracking" is selected. 

Someone mentioned **d.tube** today, but few days ago and still today I tried **Openload.co** and **Vidup.tv** don't work if the ads are being blocked.

Today I used a website **http://www.xtremostereo.net/espn-en-vivo/**. First, HTTPS Everywhere, has to be off for this to happen, but when you click play  http://tvcanales.cf/channels/espn.html is being blocked. turn "block ads" off and video will work. if you go to tvcanales.cf websites, and choose ESPN it would load for example **http://latino-webtv.com/ESPN-en-vivo/** (which doesn't need HTTPS Everywhere to be off) and the same address "http://tvcanales.cf/channels/espn.html" would be blocked not displaying any video. So my workaround was to use the html directly and it worked fine.

Still, I rarely use this last website(s), but it's a really good example how Brave is blocking more than it should, don't know why it has so much trouble with videos and such, but it seems, like it happens on more websites than I thought. but I trust you can fix all these issues sooner or later.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1224
