### ISSUE TITLE
History should be restored after restarting if Internet connection is not available

### ISSUE THREAD

**Issue by Tomcatt** [brave/browser-laptop#3029]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
If I have the browser open automatically look for the internet.  If it fails to find it, the app will display "about:error" and whatever was on that page before the error is gone forever.

I see there's no history also after I restart the app but I think you have a switch for that setting I've seen in your pref page.

**Expected behavior:**
To recover from an "about:error" page and continue to view your pages.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  MacOS
- Brave Version:
  Brave: 0.11.3
  Electron: 1.3.1
  libchromiumcontent: 52.0.2743.116
  V8: 5.2.361.49
  Node.js: 6.3.0
  Update Channel: dev
- Steps to reproduce:
  1. Open Brave after I connect to the internet
  2. Make sure the app doesn't open automatically after a reboot
     3.
- Screenshot if needed:
- Any related issues: 
  Only that one listed above.
#2702 #963

**Comment by luixxiul** [comment]
Does this happen if you don't close the browser? Closing it clears the history on the go/back buttons and it works as it should. Please try again by neither rebooting nor closing the browser.

**Comment by luixxiul** [comment]
I noticed this too. Was this issue fixed already?
