### ISSUE TITLE
Memory leak when turning shields on and off

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3030]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

If you use the brave icon at the top right and switch script blocking on and off or even turn off all shields and enable them after that for different websites, the brave proccess eats more and more RAM each time you turn them on or off, unless you close the browser or kill the proccess. If you do this constantly you can easily end up with 4GB + memory allocated only by Brave.

**Expected behavior:**

Memory consumed by the app should be dependant only on how much open tabs you have, not the times you turn shields down or up.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Fedora 24, but it is probably reproducible on all other platforms.

- Brave Version:
0.11.3
- Steps to reproduce:
    1. Open a single website and open the System monitor on your OS to monitor the initial memory of the app
    2. Start constantly turning shields off and then back on
    3. Observe that the RAM allocated by Brave constantly keeps increasing without descreasing.with each on/off action

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
CC @bbondy

**Comment by bbondy** [comment]
cc @bridiver

**Comment by bridiver** [comment]
fixed by https://github.com/brave/browser-laptop/commit/d9a579eb00ecb04ab691c7f47a7e64e970472605
