### ISSUE TITLE
Bookmark toolbar bookmark entries cut off text too early

### ISSUE THREAD

**Issue by tschf** [brave/browser-laptop#3033]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

I feel some bookmark entries could do with a larger width. For example, folders - Depending on the title of the bookmark folder, only one or 2 letters are displayed. My folders titles are between 3 and 6 characters long, so it's not like they are huge.

**Expected behavior:**

The minimum width should be increased to show the whole word, up to a certain limit. 

Here is an example of folder titles being trimmed:

![image](https://cloud.githubusercontent.com/assets/1747643/17466179/3a5043d6-5d4d-11e6-89c6-340641098f98.png)

and just for comparisons sakes, here is Chrome with a portion (I added one with the text "This is a really long title" to see where it gets cut off):

![screenshot from 2016-08-08 09-50-10](https://cloud.githubusercontent.com/assets/1747643/17466198/a51d77ba-5d4d-11e6-9660-e3e4e5591e18.png)

Folders also seem to have no tooltip so without opening the bookmark manager/editing the bookmark, you can't identify the folder name by hovering over the bookmark folder.

Text getting cut off early is not limited to folders. I have one book mark entry titled "Apex", but only the A is displayed.

![screenshot from 2016-08-08 09-54-11](https://cloud.githubusercontent.com/assets/1747643/17466222/132a1ae2-5d4e-11e6-96f9-43c9b0f268f9.png)

But then others with a much larger string show much more text:

![image](https://cloud.githubusercontent.com/assets/1747643/17466251/e6c7a4fa-5d4e-11e6-8da2-4b3203384e01.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux 16.04 x64

- Brave Version: 0.11.3

**Comment by luixxiul** [comment]
Closing this in favor of #1743
