### ISSUE TITLE
Desktop shortcuts to open a URL

### ISSUE THREAD

**Issue by Superbest** [brave/browser-laptop#3035]
I'd like to make desktop shortcut that when launched, opens a particular URL in Brave.

In other browsers, this is possible by simply pointing the shortcut to the executable (firefox.exe, chromium.exe, etc). However, I see that Brave has an odd system: Shortcuts point to `update.exe` which then apparently decides what version folder to go in for brave.exe.

If I point the shortcut to `~\AppData\Local\brave\app-0.11.3\brave.exe www.example.com` then double-clicking the shortcut opens example.com in Brave as expected. However I suspect that if a new version was released, this shortcut would continue to use the old one, and eventually stop working entirely if the old version is wiped.

Is there a solution to this? Perhaps an extra command line argument for `Update.exe` that forwards a URL to the executable?

**Comment by Tphelps91387** [comment]
Highlight and copy URL.
On desktop, right click>New>Shortcut, then paste the URL in the text box. It will create a shortcut to that web address in whatever your default browser is.

**Comment by niutech** [comment]
@Tphelps91387 This will open the web app in a default browser and what if Brave isn't one?
