### ISSUE TITLE
Pinned tabs duplicated then disappeared

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#3039]
**Describe the issue you encountered:**
I upgraded to 0.11.3. I got two instances of each of my two pinned tabs. I closed one duplicate fine. When I closed the second site's duplicate, all the pinned tabs disappeared.

**Expected behavior:**
No duplicate pinned tabs.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Mac OS X 10.11.6 beta
- Brave Version:
  0.11.3

**Comment by bradleyrichter** [comment]
Keepin' this one alive with a recent photo of the evil little troll:

![image](https://cloud.githubusercontent.com/assets/13509546/18459119/b64ba252-791b-11e6-974a-dc2606b59847.png)

**Comment by luixxiul** [comment]
reported here: https://community.brave.com/t/pinned-tabs-are-duplicated-after-a-restart-of-brave/440?u=suguru

**Comment by darkdh** [comment]
<img width="491" alt="screen shot 2017-02-04 at 00 07 09" src="https://cloud.githubusercontent.com/assets/11330831/22598296/e9b8bd5a-ea6d-11e6-8448-c16945ab344a.png">
still see this on 0.13.2 RC2

**Comment by bbondy** [comment]
This should be working as of 0.14.2. Closing
