### ISSUE TITLE
Install fails OSX

### ISSUE THREAD

**Issue by nselby** [brave/browser-laptop#304]
Failed at the brave@0.7.7 postinstall script 'node ./tools/rebuildNativeModules.js&&webpack'.
npm ERR! This is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/rebuildNativeModules.js&&webpack

**Comment by noscripter** [comment]
I encountered the same problem too.

**Comment by bridiver** [comment]
Brave requires node v5.x. I'll update the readme to make that more explicit

**Comment by nselby** [comment]
Thanks!

On Mon, Jan 25, 2016 at 12:43 PM, Brian Johnson <notifications@github.com>
wrote:

> Brave requires node v5.x. I'll update the readme to make that more explicit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/304#issuecomment-174599332>
> .
>



-- 

--

Nick Selby
StreetCred Software, Inchttp://streetcredsoftware.com

mob 817 203 4074
fax 817 659-2996

3901 Arlington Highlands Blvd
Arlington, TX 76018

**Comment by nselby** [comment]
SO that's fixed and then I get to the end of the install and the world hates me:

Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! path /Users/nselby/browser-laptop/node_modules/extract-zip/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/nselby/browser-laptop/node_modules/extract-zip/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by bridiver** [comment]
can you post a gist with the complete log output?

**Comment by therealklanni** [comment]
@nselby have you tried `rm -rf node_modules` and `npm install` again? Changing node versions can often do crazy things to npm/node_modules.

**Comment by conanoc** [comment]
I got the same error as @nselby and fixed by removing modules and installing again. Thanks.

**Comment by luixxiul** [comment]
@bbondy As fixed already this should be closed.
