### ISSUE TITLE
Ctrl + Numpad 0 should reset Zoom

### ISSUE THREAD

**Issue by dogancelik** [brave/browser-laptop#3040]
Brave: 0.11.3
Windows: 8 (64-bit)

In Chrome and Firefox, Ctrl + Numpad 0 resets Zoom
Brave only works with Ctrl + 0 (key near Backspace)

![numpad](https://upload.wikimedia.org/wikipedia/commons/9/99/Numpad.svg)

**Comment by bsclifton** [comment]
This would be a great one! :smile:

I'd encourage any of our users to download our code and try to get this one fixed.  You can ping me (or other contributors) anytime and we'll help you.  This would be a great one to get your feet wet and would have a huge impact, IMO

**Comment by rickycodes** [comment]
should be tagged `windows-only` (appears to work as expected in osx)

**Comment by bsclifton** [comment]
This works on mac but not on Windows... Electron has an issue with numpad.  I'm going to close this in favor of tracking the remaining work with https://github.com/brave/browser-laptop/issues/4815#issuecomment-254537416
