### ISSUE TITLE
Saving a page should default to title as filename

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3041]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When saving a page with File|Save, the default filename is part of the URL.

**Expected behavior:**
The filename should default to the page title, if there is one.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.3

- Steps to reproduce:
    1. Open a page that has a title
    2. From the menubar, select File|Save, or press Ctrl+S/Cmd+S

Expected: Filename defaults to page title

Actual: Filename defaults to the filename or domain in the URL

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1530699/17494654/ae52edb6-5d83-11e6-9668-47b607f822d3.png)

![image](https://cloud.githubusercontent.com/assets/1530699/17494666/c0546134-5d83-11e6-82cb-27db85fa2151.png)

**Comment by luixxiul** [comment]
Duping to #2231

**Comment by gulkily** [comment]
Could you please consider reopening this issue?

I know that you wrote in #2231 that it would be a security issue, but this is the standard behavior in other browsers, so there must be a way of sanitizing the page title and adding the ".html" extension before suggesting the filename.

**Comment by luixxiul** [comment]
The title of the issue #2231 "Title should be default file name when saving page" is duping, isn't it?

**Comment by luixxiul** [comment]
The issue of detecting the file extension (.html) has been reported here #1985 fyi

**Comment by gulkily** [comment]
Also, that screenshot looks to be from Windows. The issue I reported is on Mac OS X.

In the screenshot you provided, the Google home page, which has the title "Google", is being saved as "Google.html", which is exactly the behavior I am requesting.

For clarity, here is a different screenshot from Firefox. As you can see, the page title makes its way into the suggested filename field (green arrows.) This screenshot also demonstrates the filename sanitation, with the slash in the title being replaced with an underscore (blue arrows.)

![image](https://cloud.githubusercontent.com/assets/1530699/17718651/ff40e948-63e2-11e6-9713-91572e6200b1.png)

Here is another example, Chromium on Linux. In this case, the slash is replaced with a space instead of an underscore, which looks nicer in my opinion:

![image](https://cloud.githubusercontent.com/assets/1530699/17718800/f76ed92c-63e3-11e6-8131-355c0d319a15.png)

Compare to Brave:

![image](https://cloud.githubusercontent.com/assets/1530699/17718823/22c57f2c-63e4-11e6-88f9-8bc4577c29f3.png)

**Comment by gulkily** [comment]
Oops, I thought the other issue was also closed...

**Comment by luixxiul** [comment]
So doesn't we need to reopen the issue here, right?

If you think the filename sanitization should be implemented, would you please open another issue? It might be off-topic here.
