### ISSUE TITLE
Printed page should include "standard" header and footer by default

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3043]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When printing a page from Brave, there is no header or footer by default.

**Expected behavior:**
The header and footer should include the following information:
Page title (top left)
Page URL
Date and time
Page # of #
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.3
- Steps to reproduce:
  1. Open a page with some content and a title
  2. Go to File|Print or press Cmd+P/Ctrl+P
  3. Send the results to a printer (or save as PDF)
  4. Look at the printed/PDFed page

Expected: Title, URL, page #, and date/time are in the header/footer

Actual: Only the page contents are printed

**Comment by Liunkae** [comment]
I also like how Firefox allows you to customize the header and footer:
![image](https://cloud.githubusercontent.com/assets/19424103/21171279/761e1abc-c190-11e6-94ee-6f661338b869.png)
