### ISSUE TITLE
Brave|Preferences... and Cmd+, do not work if Developer Tools is open

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3044]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If Developer Tools is open, the Preferences page does not open when requested

**Expected behavior:**
Preferences page should open when requested if the menu item is enabled
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.3
- Steps to reproduce:
  1. Open a page
  2. Open Developer Tools (View menu or Cmd+Alt+I)
  3. Go to the "Brave" menu and observe that the "Preferences..." item is enabled
  4. Select the "Preferences..." menu item or press Cmd+, (comma)

Expected: Preferences page opens

Actual: No visible response

**Comment by Liunkae** [comment]
Duping to #45.
