### ISSUE TITLE
Internal error loop is not handled, browser becomes unusable

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3045]
NOTE: I found this issue in 0.11.2, and it no longer occurs in 0.11.3. The reason I am reporting it is because of the lack of error handling, not the bug itself.

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When an error occurs, the browser ends up with a looping JavaScript error message, which cannot be disabled.

**Expected behavior:**
Error is handled gracefully.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.2

- Steps to reproduce:
    1. Open a browser window
    2. Use File|Open-file to select a file -or- drag a file into the address bar (not the browser viewport)
    3. Click OK several times. The file contents should appear after the third error message is closed.

**Comment by bbondy** [comment]
That message box won't happen anymore as of 0.11.3. The error handling was fixed there.
