### ISSUE TITLE
Browser keeps trying to connect to device detection server 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3046]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Browser keeps trying to connect to device detection server after declining the consent

**Expected behavior:**
Should not attempt to connect after user disagrees to the detection prompt

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.2

- Steps to reproduce:
    1. Visit support.lenovo.com/ie/en
    2. Click on Detect my product
    3. Click on Disagree in the popup
    4. Browser continues to connect to the server even after disagreeing the request

- Screenshot if needed:
Chrome/FF/Brave
![image](https://cloud.githubusercontent.com/assets/17010094/17494895/9a2a1d84-5dae-11e6-839e-20b4258a77ac.png)

- Any related issues:

**Comment by bsclifton** [comment]
When we talked about this one, I think I misunderstood you and thought there may have been a redirect happening.  This actually issue looks to be a problem w/ the website itself.

The only thing that is suspect (to me) is that the jsonp callback seems to be firing, even after the request is failing.

**Comment by bsclifton** [comment]
Going to tag a few others here to review. If consensus is this is a problem with the site (programming error on their part), let's close it out
@diracdeltas @darkdh @alexwykoff

**Comment by diracdeltas** [comment]
what happens in chrome? seems like a site issue

**Comment by bsclifton** [comment]
@diracdeltas seems that Chrome does make the request, gets an error and doesn't try again.  Since the script is called "ping", I'm assuming the jsonp handler is just sleeping for an arbitrary amount of time and then making the same request again (which is why in the Brave example you see it continuously fetch, even after an error)

**Comment by diracdeltas** [comment]
does it work in brave w/ shields off?

**Comment by bsclifton** [comment]
The link seems to have disappeared- I could not find `detect my product` anymore. I did find `detect my serial number`, but those just linked to an EXE (even though I'm on Mac LOL)

Closing issue for now.  @srirambv please re-open if you see this again (and if so, try the shields down troubleshooting step and note findings).  Thanks :smile:
