### ISSUE TITLE
Don't save state for popup windows

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#305]
State should not be saved for popup windows because they won't be properly connected to their original openers on restore. This is the default behavior in Safari

**Comment by bbondy** [comment]
I think users may expect it sometimes and ideally they would remain connected but probably it is ok for now.  Thanks for posting, let's leave it sit for a while though to focus on higher priority stuff.

**Comment by bridiver** [comment]
We can keep track of the disposition to decide which ones to keep or delete

**Comment by bbondy** [comment]
sgtm if that gives enough info

**Comment by cezaraugusto** [comment]
Was it fixed?
