### ISSUE TITLE
Entries in Bookmarks menu and History menu don't have favicons

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3050]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Links inside the Bookmarks menu and History menu don't have favicons

Favicons are not an easy win unfortunately.  Because they go into the native menubar, they have to be loaded as a nativeImage object. This means we'd have to fetch each icon, render it using canvas, and then create a nativeImage object from the base64 (or something similar).

If we had an async favicon loader (which cached the icons) this might be easier.  Once the favicon gets loaded, it could update the application state (which would then automatically trigger the menus to re-render).

**Expected behavior:**
Links inside the Bookmarks menu and History menu should have favicons.  Here's a picture that @bradleyrichter had created for this issue:
![image](https://cloud.githubusercontent.com/assets/4733304/17501674/d65d72ec-5d95-11e6-98fc-42737e7d2aff.png)
- Any related issues:
  - List bookmarks like other browsers - https://github.com/brave/browser-laptop/issues/1993
  - Favicon cache - https://github.com/brave/browser-laptop/issues/2697
  - Favicons in bookmark list - https://github.com/brave/browser-laptop/issues/1994

**Comment by bsclifton** [comment]
+1 from support (captured in https://github.com/brave/browser-laptop/issues/5983)

**Comment by alexwykoff** [comment]
+1 from support @bradleyrichter my user in particular asked for icons on the bookmarks toolbar as well to denote folders as the '>' was too subtle.

**Comment by Liunkae** [comment]
@alexwykoff Don't we already have favicons for the bookmarks toolbar? Maybe favicons are turned off in the user's preferences.
![image](https://cloud.githubusercontent.com/assets/19424103/23931141/9a2854f8-08fe-11e7-8a8c-661f2ce82e24.png)
![image](https://cloud.githubusercontent.com/assets/19424103/23931162/c4e2a82e-08fe-11e7-82df-6bf18da926df.png)

**Comment by bradleyrichter** [comment]
@alexwykoff We can increase the visual weight of the down-carrot, and otherwise send them to prefs as @Liunkae points out.....   :   )

**Comment by Liunkae** [comment]
@bradleyrichter By the way, do you think favicons in the bookmarks bar should be turned on by default? I think the default right now is text only.

**Comment by bradleyrichter** [comment]
I was inspired by the clean look of the Safari BM bar. 

If we find out that most users prefer the clutter of favicons everywhere, we can change the default, and I will enjoy my personal preference of purity, under the tree on a grass hill, with a nice Chianti. (and maybe some fava beans)

**Comment by ColinMcKay004** [comment]
Thanks gents, Liunkae correct - Mr Luddite & new Brave user here was unaware of Preferences option for Favicons.
