### ISSUE TITLE
Allow user to add and edit custom search engines

### ISSUE THREAD

**Issue by dawikur** [brave/browser-laptop#3053]
**Did you search for similar issues before submitting this one?**
Yep, unfortunately didn't found one.

**Describe the issue you encountered:**
I use Chrome search engine to make fast searched not only in google/duckduckgo/etc but
also e.g. cpp references, like:
`cpp? vector`
takes me to

```
http://en.cppreference.com/mwiki/index.php?title=Special%3ASearch&search=vector
```

I have a lot of shorts like this, for translation, google maps, etc. It would be great to use similar mechanism (as I am quite addicted to it) for brave

**Expected behavior:**
In the Search settings page we can put 'add' button, similar as it is in chrome

![searchengines](https://cloud.githubusercontent.com/assets/11866902/17511838/1cebc7a6-5e25-11e6-9b9e-26baa642d5cf.png)
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All of them, please.
- Brave Version:
  0.11.3
- Any related issues:
  All that asks for new search engine.

**Comment by bradleyrichter** [comment]
@dawikur Thanks for the request. We have this planned for the 1.1 timeframe, starting with a sub-task to allow editing of the engine paths.

**Comment by anaelChardan** [comment]
+1 :) I want to use Qwant as search engine :)

**Comment by Aeyoun** [comment]
All search engines, and then I mean every single one of them, have OpenSearch auto-discovery on their home pages and search result pages. Safari and Edge automatically detects OpenSearch-enabled search engines and lists them as suggested search engines in their Preference panes.

This means that every user will find their favorite search engine in the list of possible search engines without having to configure it; they just need to perform one search with their favorite engine and it will then become available. I [wrote about this on my blog](https://www.slightfuture.com/blog/safari-decentralizes-search) for anyone interested in the specifics.

I think this is an elegant solution that empowers even inexperienced users to change their search engine to whichever they prefer without technical knowledge. It also exposes many more possible search engines than a browser could reasonably build-in by default. The approach sounds like a good fit for Brave.

**Comment by bridiver** [comment]
related https://github.com/brave/browser-laptop/issues/4210

**Comment by Rasmis** [comment]
Can we expand this issue / feature-request / enhancement to also cover “**editing and deleting the included search engines**”? 

Like [peterjohn on brave.com](https://community.brave.com/t/more-search-engines-customizable-search-engines-with-engine-go/672) I use websites in different languages with different *keywords*. Eg. `wde` (de.wikipedia.org), `wfr` (fr.wikipedia.org), `a` (amazon.co.uk), `ade` (amazon.de) etc.

But in Brave the american versions are *preloaded* and cannot be changed.

Also when searching the internet in different languages requires a lot of tweaking in the search queries.

Eg. a non-country specific verbatim Google search query for `brave browser`:

    https://www.google.com/webhp?gfe_rd=cr&gws_rd=cr&fg=1#q=brave+browser&tbs=li:1

It'd be nice to be able to define ones own queries, like in most other browsers, rather than depending on the developers to choose their faves.

**Comment by bsclifton** [comment]
per https://github.com/brave/browser-laptop/issues/2850, we should be able to edit the "go keywords" for search engines added

**Comment by crysman** [comment]
This is really missing... it's a pain to work without this functionality. Thank you for having this already planned to implement.

**Comment by basilweibel** [comment]
1+; only feature missing to make me switch from Chrome. Keep up the great work!

**Comment by hanswundersam** [comment]
Hi @bradleyrichter, last summer you mentioned this feature would be available "for the 1.1 timeframe". Now we're at version 0.15.3. Is it possible to estimate when 1.1 is expected to come out? Just so that people know how long they will have to wait. Thank you!

**Comment by xyzforgottenme** [comment]
Since it seems that 1.1 is going to be awhile down the road, may I ask for these sites to be added. Since that seems to be the only possibility. 

http://www.dogpile.com/
http://boardreader.com/
http://www.ask.com/
http://www.lycos.com/
http://www.excite.com/
http://www.entireweb.com/
https://search.creativecommons.org/
https://giphy.com/
https://vimeo.com/

**Comment by srirambv** [comment]
+1 for discogs.com from community https://community.brave.com/t/engine-go-key-for-discogs-com/3601

**Comment by Chen-pan** [comment]
+1 and edit search engine address :+1:

**Comment by DeviatedMind** [comment]
#790 #824 #3053 #3294 #4210

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/feedback-about-the-brave-web-browser-as-a-brand-new-user/4068/4?u=eljuno) (re: add custom search engines)

**Comment by davidpgil** [comment]
Most of all, I would like to be able to REMOVE all search engines I do not want. This unfortunately makes Brave look like Adware when it includes so many search engines that are not deletable. Would be cool if Brave could be a bit Braver ;)

**Comment by rdp-cloud** [comment]
+1

This would be a useful feature when you want to '_keyword_' links and search engines. ie. set up a search engine 'aws' that will redirect to 'aws.amazon.com'. This has become a common **workaround** for the removal of _bookmark keywords_ some time ago.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/can-goodgopher-com-be-included-in-the-search-engine-options/6060?u=eljuno)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/should-be-able-to-add-customize-search-engine/6198?u=eljuno

**Comment by bsclifton** [comment]
I created a new issue which basically details how OpenSearch works (and how we could display it in Brave) which you can find here (thanks @jonathansampson for the rundown on how this works):
https://github.com/brave/browser-laptop/issues/10868

We can keep this issue to track the ability to add new engines (button highlighted in red)
![screen shot 2017-09-08 at 4 27 39 pm](https://user-images.githubusercontent.com/4733304/30234643-f47b077a-94b3-11e7-96a7-8c4040ce2af2.png)

@bradleyrichter @jenn-rhim @alexwykoff do you all think you could propose a mockup how this would look (where would the button go?)

**Comment by bsclifton** [comment]
Updated title to also include the other options associated with this (edit / make default / remove)
![screen shot 2017-09-08 at 4 51 35 pm](https://user-images.githubusercontent.com/4733304/30234821-15f2dd22-94b6-11e7-8dbd-fd369becfec9.png)

**Comment by da2x** [comment]
OpenSearch is the right way to go here. Though please pay special notice to the drive-by search provider installation protection feature which work slightly differently in [Safari](https://ctrl.blog/entry/safari-quick-website-search) and [Edge](https://ctrl.blog/entry/edge-search-provider). Safari also has a fallback for websites that don’t have an OpenSearch Description file (described in the previous link) which can be a … good source for inspiration.

PS: Chrome’s UI is the worst out of the lot here. Look at Edge and Safari instead. Firefox is more discovererable than the rest, but requires a separate search field/icon.

**Comment by sanchez2210** [comment]
+1 I'd love to add rubygems.org and others. Thumbs up for this feature!

**Comment by bsclifton** [comment]
cc: @davidtemkin and @zentagonist for visibility (this would be a HUGE win for us)

**Comment by thynquest** [comment]
+1 for this feature

**Comment by m00nxaild** [comment]
+1 for this feature.
I use metager.de, please consider adding it to the default list (since it can help it's adoption). Although the design is not super, it is open source, focused on privacy and data protection and so far it has provided me better results than DuckDuckGo, it is closer to Google accuracy. Thanks!

**Comment by joshuadanpeterson** [comment]
The moment OpenSearch is integrated into Brave is the moment Brave becomes my default browser for good. Just wanted to put that out there.

**Comment by DeviatedMind** [comment]
Plus Stylesheet. I have put Brave aside for now.

**Comment by kartikthapar** [comment]
We use BunnyLol here at Facebook and without the custom search engine, Brave is basically unusable. This is not tracked in 1.1 anymore. Is this happening at all?

**Comment by benjibee** [comment]
I have 10+ custom searches setup in Chrome, I'm mostly using Brave now except when doing work that requires these search engines. What's the status of this? @bsclifton

**Comment by robomac** [comment]
I'm in the same state as benjibee... Brave falls too far short without allowing me to customize my own search engines.

Consider this: By default, if you search for a random phrase, you often get hits 10+ years ago.  So I set up in Chrome a set of searches that are date-limited.  Saves a LOT of time.  And I did this also for my partner on her laptop.  She's not very web-savvy, but she wouldn't want to give that up.  

And yet you won't let her have it. 

What you guys don't seem to realize is, you need the influencers.   We bring the tools to the rest of the world.  And the request is currently 16 months old.  Maybe there's a reason Brave isn't even cracking the lists yet.

I give up.

**Comment by benjibee** [comment]
@robomac I actually never thought of date-limited searches. That's brilliant for articles and tutorials for frameworks and languages that become outdated quickly. Thanks for the (non-Brave related) tip!

**Comment by crysman** [comment]
I'm glad more and more people are requesting this important feature... Maybe someone will consider implementing it soon (?) I unfortunately cannot, since my programming skills are not high enough :/

**Comment by georgemillo** [comment]
This is by far the feature I miss the most from Chrome. I have dozens of these "search shortcuts" in Chrome that I've built up slowly over the last decade; they're etched into my muscle memory and it's a PITA to not have them.

Here's one example: I speak multiple languages and I frequently need to look up the English translation of a foreign word (or visa versa), so I have keywords set up in Chrome to search a bilingual dictionary (usually WordReference.com). So e.g. `enes brave` searches WR's English-Spanish for "brave", and `espt valiente` searches the Spanish-Portuguese dictionary for "valiente", etc..

Like others I also use these keywords for searching sites in different languages, e.g I have `wiki` for the English Wikipedia, but `wifr` for the French version, `wies` for the Spanish etc.. As it is, you can only use the Brave address bar to search the *English* version of the listed search engines, which clearly isn't what a lot of people will want.

I'm not familiar with OpenSearch but bear in mind that it's not just search *engines* that people will want to attach to a keyword. Zillions of websites have a "search this site" feature even though the site itself isn't Google or Yahoo. The proliferation of suggestions in this thread shows that it's simply not practical to have a single list of search engines that ships with Brave by default and isn't customisable.... especially when you consider that the early adopters of Brave are overwhelmingly going to be nerdy power users who like tinkering with and customising these kind of settings.

Also note Chrome actually adds these custom search keywords by default every time you search a new site. E.g. if I go to example.com and use its "search this site" feature (assuming it has one), Chrome will usually figure out that this is a search, and add example.com to my list of search "engines". Then the next time I type `example.com` into the address bar I'll see the option to search the site directly, like on the right here:

<img width="883" alt="screen shot 2018-01-03 at 10 07 40" src="https://user-images.githubusercontent.com/2656485/34516219-075e01ec-f06e-11e7-8932-e3a26d312de8.png">

This is a handy default for the less technical user who doesn't think of adding these things manually. For people who like more customisation, it's now merely a matter of finding example.com in your search settings and changing the keyword from `example.com` to something more succinct like `ex`.

**Comment by benjibee** [comment]
@georgemillo I use it for exactly the same thing, _enes_, _ende_, etc. using WordReference.com!

That being said I don't think it should follow Chrome's behaviour of adding search engines to the custom list just by using them. I have my custom searches (which are very easy to add) and there's 100+ other sites I've used once or twice mixed in there, cluttering it up. If this is going to be implemented please don't auto-add anything 🙏

Perhaps that little tooltip in the address bar could ask to add them, like _Press `tab` to add this search engine to your custom list_

**Comment by georgemillo** [comment]
>  I have my custom searches (which are very easy to add) and there's 100+ other sites I've used once or twice mixed in there, cluttering it up. If this is going to be implemented please don't auto-add anything

Yeah, I have the same problem come to think of it - the auto-added searches clutter up my search settings. I still think some kind of auto-adding is a good idea though. Bear in mind most people aren't techies who comment on GitHub issues or tweak their custom search engines with fine precision. I'd bet most Chrome users don't even know that the keywords for your custom search engines can be customised.

Maybe "auto-add search engines when one is detected" could be a setting that's enabled by default?

Of course, this is all just details and isn't essential for a version 1.0 of this feature.

**Comment by georgemillo** [comment]
Another gripe: the inbuilt `:a` Amazon keyword only lets me search Amazon.com. No use to me as I use Amazon.co.uk.

**Comment by doomlaser** [comment]
I want to be able to make me own search shortcuts, and I don't want to have to type a : colon before every search shortcut. Why can't I just type ^space t whatever, to invoke a twitter search, instead of having to also make two key presses to input a redudant colon prefix?

Why can't Brave just import the custom search engine settings from Chrome, Firefox, or Safari and have the address bar behavior for custom search invocations be the same? It ould be much faster and more convenient.

**Comment by thiagola92** [comment]
My only problem is unable to uncheck search engines, i don't want to search on amazon.com by default.   
![uncheck this](https://i.imgur.com/nRpTelB.png)

**Comment by sly7-7** [comment]
Not sure if this the right place to ask, but would it be possible to add https://www.lilo.org/en/ as a search engine ?

**Comment by mehmetkz61** [comment]
+1 for this feature. It also would be great to have a remove option.

**Comment by kartikthapar** [comment]
Would love for this to be prioritized if possible. Most of my office work uses bunnylol and I just cannot use Brave for my needs because of this.

**Comment by dngen** [comment]
+1

**Comment by immanuelfodor** [comment]
+1, I need the custom search engine settings so much, both Brave desktop and Android lacks this feature :disappointed:

**Comment by cyboman** [comment]
This is one of the key features keeping me in Chrome. I've tried (again and again) to go back to Safari, Chrome, and now Brave, but my repeated, daily access of about a dozen sites is made much better with search engine keywords in Chrome.

**Comment by bsclifton** [comment]
Given the requirements for this, we won't be able to fix this with `browser-laptop` so I'm going to close as `wontfix`. 

However, we are moving to `brave-core`, a Chromium based UI which replaces the current Muon codebase. **In `brave-core`, I have verified this is fixed!** 😄 Here's a screenshot from Brave Core:
![screen shot 2018-07-10 at 11 05 42 am](https://user-images.githubusercontent.com/4733304/42528821-9827938a-8431-11e8-96fe-bd39bddf048f.png)
