### ISSUE TITLE
Renderer crashed with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#3054]
**Did you search for similar issues before submitting this one?**
Yes

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version:
brave/master: 439bb84
electron/master: https://github.com/brave/electron/commit/94921be41cf229dd338078da58b5588415feb19e
- Steps to reproduce:
    1. Open https://www.facebook.com/bclowy/posts/1163419890399903
    2. Click the link.
    3.  The facebook tab and the new tab both have`An unexpected error has occurred`

- Crash report:

[Brave Helper_2016-08-09-181858_Anthonys-MacBook-Pro.crash.zip](https://github.com/brave/browser-laptop/files/408734/Brave.Helper_2016-08-09-181858_Anthonys-MacBook-Pro.crash.zip)

**Comment by darkdh** [comment]
cc @bridiver , @bbondy

**Comment by bridiver** [comment]
strange, it appears to be the result of a binary array buffer being passed in an ipc message, but I'm not aware of anything that would cause that, but which link causes the crash?

**Comment by bridiver** [comment]
ah, there's a cert error and the data field is empty. Looking into it more...
cc @diracdeltas

**Comment by bridiver** [comment]
```[351:0810/141810:ERROR:javascript_bindings.cc(207)] message cert-error [ {
   "cert": {
      "data": ,
      "fingerprint": "sha256/cLK6yuBqbJururvUMl2odvLo/Vzyv26aJvuaJVsKjLg=",
      "issuerName": "Verizon Akamai SureServer CA G14-SHA2",
      "serialNumber": "3DB5E10B85ECBBB1F7CF61D3276A889B05A67C43",
      "subjectName": "a248.e.akamai.net",
      "validExpiry": 1472314211,
      "validStart": 1440691812
   },
   "error": "net::ERR_CERT_COMMON_NAME_INVALID",
   "tabId": 3,
   "url": "https://ad.sitemaji.com/ysm_forgetfulbc.js"
} ]
```

**Comment by bridiver** [comment]
looks like it was from this commit https://github.com/brave/electron/commit/d072e612823bdf342b519c866e09c55269b0cadf
but I don't understand why he's a base64 encoded string and converting to an array buffer. I'll ping on the commit
