### ISSUE TITLE
search suggestions fill even with all characters deleted

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3058]
Search suggestions fill even with all characters deleted if you delete them quickly but it works correctly (not showing any results) if you delete characters slowly.

**Expected behavior:**
The suggestions popup should close when all characters are deleted, and reopen as you type new characters.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  mac
- Brave Version:
  0.11.3
- Steps to reproduce:
  1. start typing a search query (a few letters)
  2. delete them all quickly with the delete or backspace key
  3. notice the popup appears after all characters are deleted
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/13509546/17529171/297f059e-5e27-11e6-9024-75438010e4c1.png)

cc @bbondy

**Comment by luixxiul** [comment]
It seems this has been fixed already. Let's reopen if we still see the issue 😄
