### ISSUE TITLE
Doesn't start properly

### ISSUE THREAD

**Issue by akhilcjacob** [brave/browser-laptop#306]
I get a message  saying "A JavaScript error occurred in the main process", I have attached the git bash output and an image of the error. However I have noticed that some of the brave process have started as they are listed in my task manager.
[Error folder.zip](https://github.com/brave/browser-laptop/files/102558/Error.folder.zip)

**Comment by luixxiul** [comment]
Closing for the moment. Please tell me if this still persists, thanks.
