### ISSUE TITLE
Pref change restart prompt doesn't restart the browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3064]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pref change restart prompt doesn't restart the browser when clicking on Yes. Neither does it dismiss when No is selected

**Expected behavior:** 
Should either restart or dismiss the prompt based on user action

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.4 Dev RC1

- Steps to reproduce:
    1. Change Pref options which initiates a browser restart
    2. Clicking Yes/No doesn't restart/dismiss the prompt
   
May be caused due to enabling two options which require restart.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Tracking here so I'll close this one.
https://github.com/brave/browser-laptop/issues/2958
