### ISSUE TITLE
running browser fails "electron: not found"; building electron fails

### ISSUE THREAD

**Issue by smcnally** [brave/browser-laptop#307]
Running Ubuntu 15.04. Successfully built with help from the [Issue 214 thread](https://github.com/brave/browser-laptop/issues/214).

Can successfully run server and tests; running browser fails with "electron: not found."

Despite [main README](https://github.com/brave/browser-laptop/blob/master/README.md) suggesting not needing to build electron, am doing so using [these instructions](https://github.com/brave/electron/blob/master/docs/development/build-instructions-linux.md). 

got through much of the build Debug target process, then failed with:

>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>ninja: build stopped: subcommand failed.

Will try again later

**Comment by Adejair** [comment]
I have same error, I solved this error installing electron-prebuilt from npm, `npm install electron-prebuilt --save`

I advise not to do it, because has [electron-prebuilt](https://github.com/brave/electron-prebuilt) prepared to use in brave, to use it is easy.
```
git clone https://github.com/brave/electron-prebuilt 
cd electron-prebuilt
./electron PATH_TO_BRAVE
```

**Comment by smcnally** [comment]
Thanks, @Adejair. npm install completed successfully with a warning:

> npm WARN ENOENT ENOENT: no such file or directory, open '~/browser-laptop/node_modules/electron-rebuild/package.json'

After cloning the repo, I've got an electron executable in

> /browser-laptop/electron-prebuilt/dist

but not in 

> /browser-laptop/electron-prebuilt/

From the latter dir, 

> ./electron ~/browser-laptop/

gives me a "command not found." From 

> /browser-laptop/electron-prebuilt/dist 

./electron ~/browser-laptop/ gives me this error:

> Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.2/docs

>Error: Cannot find module 'sqlite3'

which I've seen referenced in other tickets. Will continue digging.

**Comment by Adejair** [comment]
Try install sqlite3 manual(_in browser-laptop path_) `npm install sqlite3 --unsafe-perm`

and try command `./electron ~/browser-laptop`

**Comment by smcnally** [comment]
Thanks, @Adejair. Installed sqlite3 in 

> ~/browser-laptop/

and 

> ~/browser-laptop/electron-prebuilt/dist 

and getting new errors re abp-filter-parser-cpp. I'll review other tickets for that.

**Comment by luixxiul** [comment]
This should work.
````
rm -rf node_modules/
rm -rf ~/.electron
npm i
````
If not let me know to reopen the issue.

**Comment by renhuihhh** [comment]
[https://www.npmjs.com/package/electron-prebuilt](url) this maybe solve the  problem "electron: not found"
