### ISSUE TITLE
[SUGGESTION] brave page in Brazilian Portuguese

### ISSUE THREAD

**Issue by h3xp4n** [brave/browser-laptop#3070]
I come here to propose a 'page / wiki' all the brave Brazilian Portuguese to ease some of the lives of Brazilian developers.

**Comment by bsclifton** [comment]
I know this is an older request, but the wiki here is open and edits are very welcome 😄 

We also have notes about translations here:
https://github.com/brave/browser-laptop/blob/master/docs/translations.md
