### ISSUE TITLE
When opening 5 or 6 tabs noticed crashes and errors

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3073]

**Comment by luixxiul** [comment]
Do you have any steps to reproduce this?

**Comment by EuNlope** [comment]
I have a Print on the reported error ->https://www.flickr.com/photos/142881062@N04/28930962355/in/dateposted-public/

**Comment by luixxiul** [comment]
I think it is normal when you play a movie on your browsers.

Duping to #415.
