### ISSUE TITLE
CTRL+R not working when the page fails to load

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3079]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**
If you access a website, that for some reason fails to load you get the following page:

<img src="https://s10.postimg.org/srszku5jd/Selection_004.png">

Now if you try to hit CTRL+R to retry loading the page it won't work. It will attempt and refresh the page only if you click the button "Retry the URL".

**Expected behavior:**

Hitting CTRL+R should act the same as clicking the "Retry the URL" button.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Fedora 24, but I guess it is reproducible on all platforms

- Brave Version:

0.11.3

- Steps to reproduce:
    1. Open a page that fails to load
    2. Attempt to refresh the page with CTRL+R
    3.

- Screenshot if needed:

- Any related issues:

cc @bbondy

**Comment by luixxiul** [comment]
Do you have URLs for example?

**Comment by Sh1d0w** [comment]
@luixxiul You can simulate page that is not loading by disconnecting you from the network. Then type https://github.com . After the error page appears, connect to the network and try refreshing the page with CTRL+R.

**Comment by luixxiul** [comment]
OK thanks, I believe this is the same issue as #2826. What do you think?

**Comment by Sh1d0w** [comment]
@luixxiul Yes it is the exact same issue, sorry seems I missed this report.

Thanks for your time, closing as duplicate.
