### ISSUE TITLE
bookmark title (onhover) on bookmark bar cannot be updated

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3080]
**Describe the issue you encountered:** bookmark title (onhover) on bookmark bar cannot be updated

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.4 RC2

- Steps to reproduce:
    1. bookmark this page

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17544734/0c6738bc-5f14-11e6-8bba-edf3f83882e5.jpg)

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17544756/27719d6e-5f14-11e6-9c5b-46971b4643b9.jpg)

- Any related issues: #3075

**Comment by bsclifton** [comment]
Closing- as @BrendanEich mentioned, this is a dupe.  Issue https://github.com/brave/browser-laptop/issues/3284 was tracking this too and is referenced in the PR which fixes it:
https://github.com/brave/browser-laptop/pull/3339

**Comment by bsclifton** [comment]
Turns out this is not a dupe after digging in- reopening
