### ISSUE TITLE
Flash on http://www.y8.com/games/superfighters does not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3082]
**Describe the issue you encountered:** Flash object on http://www.y8.com/games/superfighters is not shown

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.4 RC2

- Steps to reproduce:
    1. Open http://www.y8.com/games/superfighters
    2. Allow once

- Screenshot if needed:

- Any related issues: #3075

**Comment by diracdeltas** [comment]
shows up for me in osx  0.11.4 release; any console errors?

**Comment by luixxiul** [comment]
OK here is the screenshot:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17600565/077bb7ca-603f-11e6-90fa-cac82aae9541.png)

**Comment by luixxiul** [comment]
It seems like this error is not fixed completely. Based on IP address or something I am redirected to http://ja.y8.com/games/superfighters and get the same console message on 0.11.6 Beta1 #3283

**Comment by luixxiul** [comment]
It started disappearing again, so reopening. I am trying to confirm it on the domain ``www.y8.com``, but cannot because I am redirected to ``ja.y8.com``. Disabling the shield displays the placeholder.

**Comment by luixxiul** [comment]
Maybe we need another sitehack for those domains.
