### ISSUE TITLE
UI suggestion: visual distinction between session tabs

### ISSUE THREAD

**Issue by KillianKemps** [brave/browser-laptop#3083]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When using session tabs, I can be confused in which session I'm currently in. Currently, the only way to know is to hover the session icon on the tab.

![screenshot from 2016-08-10 09-54-01](https://cloud.githubusercontent.com/assets/6884630/17546071/a70cbd58-5ee0-11e6-8fea-3daa2428f8ac.png)

**Expected behavior:**
It would be nice to distinguish session tabs from each other with colors (red, blue, green..) so I'm sure I don't mix up. As private windows are violet.

**Comment by bsclifton** [comment]
This is a great suggestion :smile: cc: @bradleyrichter

**Comment by bradleyrichter** [comment]
We will try to hit this for 1.0 but it may have to slip a bit, as part of a larger set of improvements to Session tabs which may also be renamed to User tabs.
