### ISSUE TITLE
Update adblock definition files

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3087]
From support:
> [removed per request] domain is one that I use for testing, and as far as I can tell, there is no malware at the site. I do not know on what basis Spam404 or Disconnect.me have blacklisted the site. 

WDYT? /cc: @diracdeltas

**Comment by diracdeltas** [comment]
it's on spam404 - https://github.com/Dawsey21/Lists/blob/aa8535d568707f2dad015b241b610c952dfaed80/main-blacklist.txt. not sure why but they should open an upstream issue here: http://www.spam404.com/revision-request-domain.html

**Comment by diracdeltas** [comment]
also @bbondy we should update the lists from upstream at some point

**Comment by bbondy** [comment]
Updated both malware and adblock files, I'll add a follow up to automate this

**Comment by bbondy** [comment]
As for test plan, just try loading various sites and make sure we aren't overly blocking or under blocking compared to what we did before.
