### ISSUE TITLE
Pressing esc two times to clear typing

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#3088]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
We must press esc two times to clear typing text which is the behavior of Firefox
**Expected behavior:**
We should follow the behavior of Chrome by pressing esc once
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version:
0.11.4 dev RC2
- Steps to reproduce:
    1. Click on urlbar
    2. Type any text
    3. Press esc to clear text

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/2914
Bug introduced here: https://github.com/brave/browser-laptop/commit/f551bbd3723aaafe2d9397573ac3054b631b1764
cc @bridiver

**Comment by bridiver** [comment]
actually there isn't a requirement to press escape twice, but pressing escape once will deactivate suggestions if they are present. That behavior matches safari and personally I prefer it over Chrome's behavior. There does appear to be a slight bug in the detection of suggestions though. If there are no suggestions in the list, you will still see the 'page' icon next to the url until you press escape to deactivate it. @bbondy @bradleyrichter

**Comment by bbondy** [comment]
Ya Anthony asked me this same thing and I said I think it is a bug and to post it. But I don't mind either way. I'll let @bradleyrichter decide.

**Comment by bridiver** [comment]
well, I think there is a bug, but the bug is in the detection of suggestions. `shouldRenderUrlBarSuggestions` returns true when there are no suggestions in the list

**Comment by bbondy** [comment]
Unfortunately this suggestions code is in major need of a refactor, I documented it here:
https://github.com/brave/browser-laptop/issues/3151

So the component does need to be called currently. But we can add a small check for making sure there is a size to the list for the stop thing for now and revert that later when #3151 gets fixed.
