### ISSUE TITLE
Multiple app icons on Windows

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3089]
From support (tickets/4812):
> Currently, when I open the browser, their are several 'brave icons' appearing at the bottom of my computer screen. Each 'brave icon' represents each window I have open.
> 
> ![capture](https://cloud.githubusercontent.com/assets/3362943/17562358/83ceaaa6-5f65-11e6-8b3c-33e42e1be0d7.PNG)

**Comment by bbondy** [comment]
does anyone else reproduce this?

**Comment by bbondy** [comment]
cc  @bsclifton

**Comment by bbondy** [comment]
cc @alexwykoff

**Comment by bsclifton** [comment]
Interesting- I'm trying on Windows 10 and I can't get more than 1 to show up no matter what I try.
- Holding shift and clicking Brave icon on taskbar
- Right clicking icon in taskbar and picking run as administrator
- opening up separate executables under my APPDATA folder (`C:\Users\brian\AppData\Local\brave\`). I even tried opening 0.11.3 alongside 0.11.4 and it did not work.  I'm guessing this is Windows 7

**Comment by bsclifton** [comment]
Definitely can NOT reproduce on Windows 7 either (using any of the above steps).  I'm really curious how this was done? Maybe the person has an extension installed? Can we ask about that

**Comment by bsclifton** [comment]
Closing ticket- please reopen if we get more reports.  More information would be extremely helpful :smile:
