### ISSUE TITLE
Missing dependency on npm 'request' module

### ISSUE THREAD

**Issue by PeterJensen** [brave/browser-laptop#309]
Just managed to build the laptop browser on OSX.  There were just a few hiccups:

1. It seems to be super sensitive to having the right versions of node, npm, and XCode.  I had to get the recent version of all of these.  Maybe list the minimum version requirements somewhere.
2. When running 'npm start' it failed, complaining about missing the 'request' module.  I installed that module separately, so probably a missing dependency somewhere.

Nice initiative!  Proving that web technologies can be used to create a large scale desktop app.  With all the associated benefits (common code base on all platforms)

**Comment by bbondy** [comment]
which version of Node are you running?

**Comment by PeterJensen** [comment]
v5.4.1

**Comment by luixxiul** [comment]
Fixed with #1682?
