### ISSUE TITLE
Replace Clear data menu items in History menu with new, single item

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3093]
new: 

![image](https://cloud.githubusercontent.com/assets/13509546/17565801/b664911a-5eed-11e6-89a8-1e72095e62e7.png)

old:

![image](https://cloud.githubusercontent.com/assets/13509546/17565666/2f6378a2-5eed-11e6-90fc-460e863d50f8.png)

**Comment by Duranis** [comment]
I would prefer actually having all 3 items seperate as they are now in 0.11.4.  Unless your single-item opens to an option screen where you can select which of the 3 combinations you would want to clear.  I prefer options not limits.

**Comment by bradleyrichter** [comment]
Hi @Duranis - yep. More options actually, presented in a dialog over the active page.

![image](https://cloud.githubusercontent.com/assets/13509546/17578158/8be6db4e-5f3a-11e6-970f-f08c9d40f7f9.png)

It will recall your last switch settings for faster repeated clearing.

**Comment by bsclifton** [comment]
@maaz93 that is correct- this one can be just for the menu change :smile: Thanks for taking this!
