### ISSUE TITLE
Lost all open pages

### ISSUE THREAD

**Issue by inscriere** [brave/browser-laptop#3096]
The browser became unresponsive, the tabs didn't respond, File > Quit Brave didn't work, so I closed the biggest process in Task Manager and I was not able to close or restart Brave.
I decided to restart the computer, and around 200 open tabs, which I wanted to save these links, were lost. Until now, I didn't have problems to reopen the open pages after I quit or restart the browser.
History > Reopen Last Closed Window/Tab, doesn't help.
Is it a solution to reopen these pages, or to find them in History ? 
Or the only solution is to not use Brave until the History will be implemented ? (issue #444)
- Platform:
  Windows 10
- Brave Version:
  0.11.4

**Comment by luixxiul** [comment]
I think opening such a great amount of tabs makes every browsers unstable.

**Comment by luixxiul** [comment]
you can find other issues related with performance here: https://github.com/brave/browser-laptop/labels/perf

I'm going to close the issue as it is not focused on something.

**Comment by bsclifton** [comment]
Also related: Brave should restore session gracefully after a crash #5512
