### ISSUE TITLE
After update has been a considerable increase in the consumption of RAM and CPU both high.

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3099]
Operational system Windows 10 64 bits, It is consuming a lot of RAM and consequently CPU memory. He walked occurring crashes.

**Comment by luixxiul** [comment]
Do you have steps to reproduce the issue (URLs, the number of opened tabs, etc)?

**Comment by EuNlope** [comment]
Specifically when access sites like Facebook, Instagram or Codecademy game site.

**Comment by luixxiul** [comment]
Duping to #415
