### ISSUE TITLE
My pages don't load or reload

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#3100]
My pages don't load, I re-installed the browser and still nothing
If someone knows how can I use it again. I really like this browser..

Windows 10

- Brave Version:
0.11.4

![issue](https://cloud.githubusercontent.com/assets/17557010/17577195/40a12c90-5f51-11e6-900e-9f50336f25ef.png)

**Comment by bsclifton** [comment]
@Kzeir why did you close? Were you able to solve the issue? Any info is appreciated :smile:

**Comment by Kzeir** [comment]
Don't know, just begin to work again...
Some update in the windows was crashing the browser I think

Em 11 de ago de 2016 12:29 PM, "Brian Clifton" <notifications@github.com>
escreveu:

**Comment by Kzeir** [comment]
I don't know*

Em 11 de ago de 2016 2:14 PM, "Alê MRE" <alemore67@gmail.com> escreveu:
