### ISSUE TITLE
Open specified homepage on New tab 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3103]
From support:

> New Tabs could/should open the specified Homepage ...(optional) eg google.com so you don’t need to hit the Home Button.

**Comment by bradleyrichter** [comment]
this is planned for 1.1

![image](https://cloud.githubusercontent.com/assets/13509546/17605052/64a04848-5fcd-11e6-81a3-3c575b711a6b.png)

**Comment by alexwykoff** [comment]
i think this has been implemented already 😸
