### ISSUE TITLE
Bookmarked pdf with custom title displays "undefined" on bookmark bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3104]
**Describe the issue you encountered:** Bookmarked pdf with custom title displays "undefined" on bookmark bar.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.11.4
- Steps to reproduce:
  1. Bookmark http://www.orimi.com/pdf-test.pdf from a context menu
  2. Title "orimi"
- Screenshot if needed:
  when hovered
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17578016/2f15e506-5fbf-11e6-9693-2c300bd55432.png)
- Any related issues:

**Comment by bbondy** [comment]
seems like 2 part fix here:
i) If undefined title show nothing instead of undefined for the title
ii) Determine and save pdf title better

**Comment by luixxiul** [comment]
This seems to have been fixed. Closing.
