### ISSUE TITLE
Brave crashes immediately

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3106]
From support (ticket/4948):

> The problem I keep having is that when I try to start Brave, the window 
> pops up, then immediately crashes. I've tried uninstalling and 
> reinstalling Brave, I've tried restarting my computer, and it keeps 
> happening.
> 
> I looked this error up and it seems like other people on Windows, as 
> well as Mac are also having this problem, and it seems like no one 
> really has a clear answer on how to fix it.

I am not quite sure whether Mac does have the issue as mentioned.

**Comment by EuNlope** [comment]
This happened to me a few minutes ..

**Comment by bsclifton** [comment]
One thing we can ask is for folks on Windows to try running `dxdiag` (just type that from Start -> Run).  It'll scan the display drivers, making sure they're signed, and also offers to save all info as a .txt.  That TXT might be useful to us.  I have a feeling that having hardware acceleration on by default might be causing the issue.  I had a similar problem with IE on my old Dell Latitude laptop which was only solved by installing the drivers from the Dell website

One thing that would be handy would be a way for us to be able to start Brave with acceleration disabled (like a command line switch).

**Comment by alecshaw** [comment]
I've been having this issue with Brave for the last hour. Crashed four times, once on launch. Can't pinpoint an exact cause. Multiple sites (icloud.com, toggl.com, Google Calendar), once with multiple tabs open, the next two times with a single tab.

OSX 10.11.6
Brave: 0.11.5
Electron 1.3.3
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

**Comment by akshithg** [comment]
Crashes when I click on `create wallet` on OSX

**Comment by Crash95460** [comment]
Since 3 days, my brave crash at startup. Uninstall, reinstall same...

I seen the windows 0.1s and crash like luixxiul

**Comment by luixxiul** [comment]
Closing this as this is stale

**Comment by gavinrogers** [comment]
I'm having this with the new release. I think it might have been when I started allowing  notifications from facebook
