### ISSUE TITLE
Blocking non-ad content?

### ISSUE THREAD

**Issue by PeterJensen** [brave/browser-laptop#311]
The 'watch now' section on foxnews.com seems to be missing.  See attached screenshot. Left one is Brave, right one is Chrome:
![foxnews](https://cloud.githubusercontent.com/assets/3058207/12540013/f0b264d0-c2b4-11e5-8f18-3e5e7f0094c8.jpg)

**Comment by bgiesing** [comment]
See my response in #312

**Comment by bridiver** [comment]
Thanks for the report! There are some known issues as mentioned in #312 and we will add this to the list of sites we are tracking for display issues

**Comment by luixxiul** [comment]
Closing as the question was already answered.
