### ISSUE TITLE
Multiple homepages

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3110]
From support:

> Trying to set home pages to multiple tabs but not having any success.

**Comment by bradleyrichter** [comment]
Can you clarify this with more detail or an example?

**Comment by luixxiul** [comment]
I think the feature like this on Firefox: https://blog.mozilla.org/theden/2012/06/18/firefox-tip-set-multiple-home-pages/

**Comment by srirambv** [comment]
this works for me.
gmail.com | facebook.com | twitter.com | instagram.com

**Comment by luixxiul** [comment]
Thanks, maybe we just need a documentation of it here.

**Comment by bradleyrichter** [comment]
hah! Who snuck that feature in there?

It does work without spaces. So we can add help text to use the "|" to delineate.

**Comment by bbondy** [comment]
hmmm no idea ;)

**Comment by srirambv** [comment]
Closing in favour of #7442
