### ISSUE TITLE
Tab preview only with hotkey

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3113]
From support:

> it would be nice to have an option to only preview the tab if a hotkey is held(like left alt, ctrl, or shift).

**Comment by paanvaannd** [comment]
Furthermore, this may solve the following issue: there is a shorter wait time between mouse hover over a pinned tab versus an unpinned tab for preview to pop up.

The above issue makes it disorienting whenever one wishes to click on the navigation buttons. Every time the cursor even passes over pinned tabs, the browser flashes a preview of the pinned tab moused over without an adequate delay as in the unpinned tabs.

Making a hotkey option would help fix this issue (though I will open another issue and link it here when I have done so).

**Comment by bradleyrichter** [comment]
@cezaraugusto can easily fix this by adding his recent fix for main tabs to pinned tabs as well...

**Comment by lucidNTR** [comment]
alternative to improve behaviour would be to add an initial wait time before previews are shown. vivaldi (and probably opera) have a nice behaviour for this

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tab-preview-only-with-hotkey/10448

Let's see if we see several requests there 😄
