### ISSUE TITLE
Difficult to move the browser on macOS

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3116]
From support:

> It is very difficult to move the Browser window holding the Brave tabs. The hot area that supports dragging seems unnecessarily small; particularly to the left of the address/URL field when it is displayed. It feels like it is just a few pixels wide.

**Comment by bradleyrichter** [comment]
This needs a simple fix which is to allow dragging from any disabled state button, as well as a larger forced grab area to the right of the URL box.

**Comment by Liunkae** [comment]
We've had some significant UI changes since the original report, and there's now more space on the right side of the URLbar (as @bradleyrichter mentioned). I'll close this for now.
