### ISSUE TITLE
Brave does a full page redraw (flicker) when asked to reload the page

### ISSUE THREAD

**Issue by griswolf** [brave/browser-laptop#3117]
Submitted at the suggestion of Suguru Hirahara in support

When I press command-r (Reload) while viewing a text file, somewhat more than 50% of the time there is a flicker as the screen first turns entirely white, then re-renders from the top. On my (not very new) computer, you can see the wave of redraw as it progresses down the page. I was seeing this on any kind of file prior to the most recent version of Brave that I have. However this version shows the behavior only for a text (not html) file, and that only a little more than half the time. (Note: that was this afternoon. Tonight, I'm seeing the behavior 100% of perhaps a dozen or so tries)

Other browsers do not blank the screen before re-rendering, so only whatever has changed shows as a visual motion.

Running Mac OS 10.9.5 on a Macbook Pro from "late 2013" with solid state drive, retina display
- Brave Version: 0.11.4 ("about" picture attached)
  <img width="433" alt="brave-version" src="https://cloud.githubusercontent.com/assets/3092067/17580413/4d5e01fe-5f53-11e6-9e01-120111e95712.png">

[100lines.txt](https://github.com/brave/browser-laptop/files/412654/100lines.txt)
- Steps to reproduce:
  1. View the attached file. Note: This is 100lines.txt despite containing html layout. Brave correctly sees it as a text file, and that is needed to trigger the bug
  2. Hit the hot key to cause a page reload. Do it several more times in moderately quick succession (wait at least long enough for the full redraw, not much more than that)
  3. Observe that some of the time, the screen flickers to white, then re-renders from the top

**Comment by luixxiul** [comment]
@griswolf thanks for posting it :-)
