### ISSUE TITLE
Send URL by email

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3121]
From support:

> Please add the ability to send the current page's URL via the default email client (as the Chrome browser does by default)

**Comment by darkdh** [comment]
+1 from support
https://linkbubble.zendesk.com/agent/tickets/5705

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6023

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6289

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5422

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6017

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6594

**Comment by cezaraugusto** [comment]
+1 from support: https://linkbubble.zendesk.com/agent/tickets/5934

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
++ from support (more mentions on Twitter)
