### ISSUE TITLE
Closing tab with right clicking

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3122]
From support:

> what I mean is the feature in Maxthon where you can decide in the settings that instead of the menu, you can right click anywhere on a tab to close it instantly. You then can still activate the drop down-menu by holding "Shift" and right-click.

**Comment by bsclifton** [comment]
As it stands now, you can close a tab by doing a middle click (the scroll wheel).  Maybe we can make this configurable in prefs?

What do you think @bradleyrichter?

**Comment by bradleyrichter** [comment]
Sounds like a good one for Advanced settings in the future.

**Comment by Liunkae** [comment]
Related issue: #5351

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/advanced-option-closing-tab-with-right-clicking/10447

Let's reopen if we'll decide to add the feature as the option 👍
