### ISSUE TITLE
Bug: Possible UI code bug - glitches, in relation with #2795

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#3124]
**Describe the issue you encountered:**
Some of us experiencing glitches since the Chromium 52 update with hardware acceleration on/smooth scrolling on.

Found something additional which is perhaps helpful to come to the source of the problem. Installed Brave today on an additional computer which had the same glitch/tearing issues and tried to restore my old profile. Somehow my session and bookmarks got lost.

So i just opened some sites i remembered, also some which have that scrolling glitches from #2795. To my surprise that glitches did not happen, also with hardware acceleration on and smooth scrolling on. 

Opened some more until i had a second tab page because the tab limit for the first page was reached. As soon as the second tab page was created, that glitches started to appear again during scrolling.

So, it looks somehow that if that glitches appear on affected systems only if you have more than one tab pages filled with tabs.

**Expected behavior:**
2 or more tab pages should not create glitches
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7 and Windows 8
- Brave Version:
  0.11.4
- Any related issues:
  #2795

**Comment by CountLesnik** [comment]
Can reproduce it.
