### ISSUE TITLE
Titlebar on some Linux distros has a lot of wasted space

### ISSUE THREAD

**Issue by KillianKemps** [brave/browser-laptop#3126]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave has a double titlebar on some Linux distributions (one from the desktop environment and one from Brave's Electron) which is useless and it wastes space. Some screenshots to illustrate:

Screenshot on Arch Linux with Gnome: 
![screenshot from 2016-08-10 09-38-01](https://cloud.githubusercontent.com/assets/6884630/17545571/17ac7858-5ede-11e6-920d-bcfad62ef98c.png)

Screenshot on elementaryOS (based on Ubuntu):
![screenshot](https://cloud.githubusercontent.com/assets/6884630/17545838/4ade6712-5edf-11e6-9331-7e0cb0df656d.png)

**Expected behavior:**
As written for the similar issue for Windows #3036, it would be nice to only have Brave's titlebar without the one of the desktop environment.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Arch Linux with GNOME
  elementaryOS (based on Ubuntu)
- Brave Version:
  0.11.3
- Any related issues:
  #3036

**Comment by Sh1d0w** [comment]
@KillianKemps I've quickly implemented it and rised a PR. I hope they like it. If so we will have this in the next release I hope.

Quick preview: http://webm.land/media/g4DR.webm

For more info #3036

**Comment by rscircus** [comment]
This one is hard to find.

Especially the hint to :+1: and prioritization...

**Comment by gri1n** [comment]
Shame that these changes made it into the Windows version but have been put on the backburner for Linux. The usual scenario.

**Comment by bsclifton** [comment]
@gri1n one of the challenges is that Linux can have so many different looks and feels.  For example, this can be ran with Ubuntu using Unity (which puts the menus at the top, not in the window). Also, users can customize the way the window looks (close button, maximize button, etc).

If we're OK making a generic and non-native looking UI, then this is very doable. I know @Sh1d0w would be very happy to get this in 😄 

@gri1n @Sh1d0w @rscircus are there any similar apps that you can share screenshots for which don't render native widgets? (ex: custom rendered).  For example, how does Chrome or Chromium look?  I'm also curious about Firefox (which I believe does have a titlebar- not sure if it's optional)

**Comment by Liunkae** [comment]
We could:
1. Add a preference called "Hide title bar" (disabled by default).
2. If "Hide title bar" is enabled, remove the title bar and provide custom, non-native window controls.

**Comment by bill-mavromatis** [comment]
> Add a preference called "Hide title bar" (disabled by default).
An option like that would be great. Confirming this for Ubuntu 16.04, quite a UI annoyance.

**Comment by Jacalz** [comment]
This would need client side decoration on the Linux version, related to https://github.com/brave/browser-laptop/issues/11767

Steam the game client uses non native buttons when you use it on Linux, they just use the same default that even is non native on windows. I would suggest just having the windows 10 decorations without having the close button light up red. That fits in nicely in to brave and should look good!

**Comment by WuerfelDev** [comment]
I'd love to see an implemention without using the current "Native Window". Seriously, this is the only thing that keeps me from switching the standard browser

**Comment by bsclifton** [comment]
This will finally be fixed when we move over to [Brave Core](https://github.com/brave/brave-browser) 😄 Below, check out a screenshot from our last available build (Ubuntu using Gnome). Brave Core should be available in the next few months (hang tight!) 😄 
![screen shot 2018-07-25 at 12 05 23 am](https://user-images.githubusercontent.com/4733304/43184837-c707ad48-8f9e-11e8-8116-ffb08dd3d329.png)
