### ISSUE TITLE
Error: Bad end offset on pdf.worker.js

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3127]
**Describe the issue you encountered:** [This PDF](http://www.sjsu.edu/wellness/Incoming%20Undergraduate%20Student%20Fall%202016%20Instructions%20Letter.pdf) is not displayed on Windows

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.11.4
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17599225/0f8a42ac-6039-11e6-90bc-4c8292711c05.png)
  `pdf.worker.js:2314 Uncaught (in promise) Error: Bad end offset: 400384(…)`

cc: @diracdeltas

**Comment by diracdeltas** [comment]
seeing the same error on https://static.mozilla.com/moco/en-US/pdf/firefox-4-reviewers-guide.pdf, osx

**Comment by shenbagaraj** [comment]
I am also facing the same issue. please find the screen shot. could any one please update on this. 
please find below the screen shot.
![image](https://cloud.githubusercontent.com/assets/21241471/17971681/7ca449b2-6af9-11e6-9c13-3d71b868ab09.png)

**Comment by bbondy** [comment]
Is this an issue on Chrome's pdfjs extension in Chrome? How about Firefox?

**Comment by shenbagaraj** [comment]
I have dowloaded this github project and integrated with my vs solution. 
Its working in lower environment in all the browsers.
In higher environment its not working in chrome browser. its working in firefox.
Could you please help me. it will be very much helpful for me

**Comment by luixxiul** [comment]
Stale (the PDF on the 1st post is no longer available). Closing in favor of https://github.com/brave/browser-laptop/issues/10867

**Comment by diracdeltas** [comment]
I think the next PDF.JS release (going out today) should fix all of the 'bad end offset' errors.
