### ISSUE TITLE
Pepper flash is not being recognized

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3131]
https://www.flickr.com/photos/142881062@N04/28887308016/in/dateposted-public/  and https://www.flickr.com/photos/142881062@N04/28633592800/in/dateposted-public/

**Comment by diracdeltas** [comment]
What OS?

**Comment by EuNlope** [comment]
Windows 10 64 bits

**Comment by diracdeltas** [comment]
it's broken for me on the latest release too (OS X), but works with the fixes i just made: the flash notification bar appears when the 'get flash' link on the page is clicked. so hopefully fixed in next release.
![screen shot 2016-08-11 at 2 48 44 pm](https://cloud.githubusercontent.com/assets/549654/17606285/845a5bdc-5fd3-11e6-9c48-e45543be5824.png)

do you have a specific link?

**Comment by EuNlope** [comment]
Now I understand he calls "permission" to run the plugin.

**Comment by EuNlope** [comment]
The same occurs in the famous game Habbo Hotel but did not show any dialog box asking whether or not the plugin runs. Photo on the following link -> https://www.flickr.com/photos/142881062@N04/28846267051/in/dateposted-public/

**Comment by luixxiul** [comment]
Please click the middle flash button and see what happens.

**Comment by EuNlope** [comment]
I come here report that the same mistake has occurred but again the dialog box that appeared before is not showing up. (The plugin is enabled), Follows below:
https://uploaddeimagens.com.br/imagens/pepper_flash_fail-png

**Comment by luixxiul** [comment]
Does right-clicking to run Adobe flash player not work?

**Comment by EuNlope** [comment]
No, I F5 nothing happens.

**Comment by luixxiul** [comment]
Please click the right button of your mouse on the placeholder as it says, and select either "once" or "one week".

Not F5.

**Comment by EuNlope** [comment]
I've tried this too but without success.

**Comment by luixxiul** [comment]
Please tell me the URL of the page

**Comment by EuNlope** [comment]
http://www.papalouie.com/

**Comment by EuNlope** [comment]
Did you see? It was to have this behavior..

**Comment by luixxiul** [comment]
It works for me on Windows 10 64 bit.

Have you installed Flash player?

**Comment by EuNlope** [comment]
Yes Flash is installed on my computer, following the image -> https://uploaddeimagens.com.br/imagens/sem_titulo-png--17265

**Comment by luixxiul** [comment]
OK please open ``about:preferences#security`` and enable Adobe Flash support. Then Flash works.

**Comment by luixxiul** [comment]
If not, please wait for the next version. As @diracdeltas said the issue will be fixed in the next version, thanks.

**Comment by EuNlope** [comment]
Thanks for your attention :)
