### ISSUE TITLE
Publisher settings coming soon message doesn't go away

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3132]
Publisher settings coming soon message was showing (only), then all of a sudden it updated with real data, but the publisher settings coming soon message stayed.

<img width="1386" alt="screenshot 2016-08-11 16 36 31" src="https://cloud.githubusercontent.com/assets/831718/17603978/967f990e-5fe1-11e6-9148-00ef1a1719ba.png">

**Comment by bbondy** [comment]
cc @mrose17 @diracdeltas

**Comment by diracdeltas** [comment]
was this on ledger-gamma? if not i think it was fixed during the refactor

**Comment by diracdeltas** [comment]
nvm i can repro

**Comment by diracdeltas** [comment]
fixed in 8186b2cef318031774c4e3b1489ff4e1263f9ae5
