### ISSUE TITLE
Minor refactor for state cleaning

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#314]
Currently we clear some state in both the undo closed tab and in session cleanup.
This task is to track refactoring that a bit.  Maybe at least defining the lists of things to clean in a single common file.

**Comment by cezaraugusto** [comment]
@bbondy was it fixed already?

**Comment by bbondy** [comment]
I don't think so, but cc @diracdeltas because she recently worked on moving the cleanup code to the shutdown case.

**Comment by diracdeltas** [comment]
I didn't touch the close/undo-close tab code but i'm not seeing any cleanup that is happening there
