### ISSUE TITLE
Fresh Brave install comes with url completions

### ISSUE THREAD

**Issue by codrus** [brave/browser-laptop#3141]
Noticed when giving Brave a spin that it came installed with some url completions. For example, when typing in twitter I get (everytime):
https://twitter.com/libidorush1 (naked women)
http://twister.net.co/

Under privacy I have it set to clear browsing history, but these never go away.

Win10
- Brave Version: 0.11.3

**Comment by diracdeltas** [comment]
I have no idea where these could be coming from unless you have some sort of malware.

**Comment by bbondy** [comment]
You can use shift+Delete to remove entries (If using a macbook or something add in Fn)
They should be gone from clearing history though already so I'll leave this open.
Confirming we don't have these suggestions in our packaging.

**Comment by bbondy** [comment]
Could you take a screenshot? I would like to see which grouping they show up under.

**Comment by luixxiul** [comment]
Closing the issue due to lack of necessary information

**Comment by bsclifton** [comment]
@luixxiul thanks for closing this out 😄 

The only pre-loaded sites we have are located here:
https://github.com/brave/browser-laptop/blob/master/js/data/top500.js

The entries in this list are [coming from the Alexa 500](http://www.alexa.com/topsites) and definitely do not include the entries listed above
