### ISSUE TITLE
`npm start` on Windows does not work

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3142]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
You can fetch browser-laptop and do an NPM install, following the steps in the wiki:
https://github.com/brave/browser-laptop/wiki/Configuring-Visual-Studio-2015

This setup works and the `npm install` then works. However, when you start your two command-line windows up to start things... (window1: run `npm run watch`; window2: run `npm start`) you get the following error:
```
C:\Users\brian\Documents\GitHub\browser-laptop [master ≡]> npm start

> brave@0.11.4 start C:\Users\brian\Documents\GitHub\browser-laptop
> node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

could not start electron Error: spawn electron ENOENT
```

**Expected behavior:**
The browser should launch after `npm start` is run. It was working previously with 0.11.3 :frowning: 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 and Windows 7 w/ Visual Studio 2015 SP3; configuration steps followed via the wiki

- Brave Version:
master 

- Steps to reproduce:
    1. Have an empty windows machine
    2. Follow the wiki steps, including installing newest nodejs
    3. Run `npm install`
    4. Run `npm run watch` in one window
    5. In other window, run `npm start`
    6. See the error above printed out

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Just as a note, I have tried uninstalling nodejs completely via the steps outlined here:
https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows

I rebooted after uninstall, then installed newest nodejs, and rebooted again. This makes no difference.

**Comment by bsclifton** [comment]
Building a package still seems to work fine- so worst case scenario, that can always be used for testing
```
set CHANNEL=dev
npm run build-package
```

**Comment by bsclifton** [comment]
The error that's happening is a file is not found. You can open `.\tools\start.js` and see the command that gets run which fails.

Just to share what I've tried so far:
- I've built electron locally and copied it over the electron-prebuilt package
- I've tried adding \node-modules\electron-rebuilt\ to the PATH environment variable
- There is only one error when doing `npm install`, which is that it fails to install `flow-bin`. I removed this package from the package.json and tried a fresh npm install, no luck

**Comment by bsclifton** [comment]
Finally have time to look at this again.  If I try to run the spawn command that `tools\start.js` does manually, here's what happens:

`.\node_modules\.bin\electron ./,--debug=5858,--enable-logging,--v=0,--enable-extension-activity-logging,--enable-sandbox-logging,--enable-dcheck`

Message box pops up:
Unable to find Electron app at C:\Users\brian\Documents\GitHub\browser-laptop\,--debug=5858,--enable-logging,--v=0,--enable-extension-activity-logging,--enable-sandbox-logging,--enable-dcheck

Cannot find module 'C:\Users\brian\Documents\GitHub\browser-laptop\,--debug=5858,--enable-logging,--v=0,--enable-extension-activity-logging,--enable-sandbox-logging,--enable-dcheck'

**Comment by bridiver** [comment]
I'm currently building on windows starting from libchromiumcontent and will report back any issues, but I was previously able to build using update 3 after doing a completely clean install of nodejs

**Comment by bsclifton** [comment]
Here's a work-around (thanks @bbondy!) that can be used until the root cause is discovered/fixed:

1) build Brave using `npm run build-package`
2) Move the output files (should be in a folder like `Brave-win32-x64`) on top of the existing files at `.\node_modules\electron-prebuilt\dist`
3) instead of running `npm start`, run `./node_modules/.bin/electron .`

**Comment by bsclifton** [comment]
Electron seems to be failing to build on Windows now :frowning:

**Comment by bridiver** [comment]
I just built it

**Comment by bbondy** [comment]
@bsclifton I'd suggest just using the last release tag and building from that for now.

**Comment by bsclifton** [comment]
Issue is now resolved :smile: 

`npm start` broke on Windows with (8/5):
https://github.com/brave/browser-laptop/commit/6cad2e9bdea2f02385ccdfdf840ea24f42f299f6#diff-3c56a79867d9b41d5950b61c8523f078

And was fixed with (8/26):
https://github.com/brave/browser-laptop/commit/d3c04c1ce35057f28d74c94c9afd803e6c8a9958#diff-3c56a79867d9b41d5950b61c8523f078

**Comment by bsclifton** [comment]
Per the docs, child_process.spawn called with shell:true allows for files other than EXE to be ran on Windows

https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options
