### ISSUE TITLE
Show Other bookmarks as folder in the bookmark bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3145]
Currently only Chrome has the feature of showing other bookmarks inside a folder on the right end of the bookmarks bar. This would be a nice feature to include.

**Comment by luixxiul** [comment]
@bsclifton when you have some time, could you please work on this? there are several issues which seem to occur by not handling "other bookmarks" folder as an ordinary folder.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/general-feedback-and-suggestions/28478/6?u=eljuno
