### ISSUE TITLE
Social media(G+1/FB Like) doesn't work on blogposts when Shields are up

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3147]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Google plus +1 share doesn't work when Shields are up

**Expected behavior:**
User should be able to share blogposts on Google Plus
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.4
- Steps to reproduce:
  1. Open any blogspot article/blog for example [this ](https://thecandidframe.blogspot.ie/2013/01/the-candid-frame-170-colby-brown.html)
  2. Click on the G+1 social media button at the end of the article with shields enabled on the page.
  3. Popup window flashes and closes
  4. Disable shields and click the button again post is shared on users Google Plus account
- Screenshot if needed:
  Chrome 
  ![image](https://cloud.githubusercontent.com/assets/17010094/17615833/afc1f2ea-6068-11e6-8a79-54e8e1b5912d.png)
  Brave
  ![image](https://cloud.githubusercontent.com/assets/17010094/17615834/b4d42c94-6068-11e6-8b03-ce3312a8d9dc.png)
  After clicking on the share button with shields up
  ![image](https://cloud.githubusercontent.com/assets/17010094/17615876/fcc57170-6068-11e6-8175-fa3f83879dfb.png)

Console Errors:
![image](https://cloud.githubusercontent.com/assets/17010094/17615843/c7ef2e32-6068-11e6-954f-2a53eb39d157.png)
Similar console errors shown in Chrome/FF but still able to share the content. 
- Any related issues:

**Comment by srirambv** [comment]
Same with Facebook like button. Only tweet works

**Comment by bradleyrichter** [comment]
Same with Facebook like button. Only tweet works

[--- Commented from Asana.com
#commenter brad richter
---[aa]

**Comment by srirambv** [comment]
Similar issue on Nvidia.com. When Ad/Tracker is enabled none of the social media buttons work. Have to disable ad tracker for the buttons to work.

**Comment by lukemulks** [comment]
FYI - I'm rolling this issue into a parent initiative that I'm working on for social media network ads (w/in networks, and in embedded widgets and SDKs in the larger Web) - Tracking that initiative here for reference: #7678

**Comment by lukemulks** [comment]
I've run some tests today with the v0.14.0 release, and am able to confirm that functionality is restored (likely in an earlier version). 

Twitter Share: 
![brave-social-buttons-03312017-blogger](https://cloud.githubusercontent.com/assets/8979240/24571403/c79df81e-1625-11e7-834d-4226dafd26aa.PNG)

Facebook Like: 
![brave-social-buttons-03312017-thehackernews](https://cloud.githubusercontent.com/assets/8979240/24571410/dac9e768-1625-11e7-84cd-f79af87d1443.PNG)

I also checked out Nvidia.com, and am seeing share functionality working as expected (note, Twitter opens in new tab, highlighted in the screenshot): 
![brave-social-buttons-03312017-nvidia](https://cloud.githubusercontent.com/assets/8979240/24571619/4eac50d4-1627-11e7-961d-bf297a9bfd3e.PNG)

I'm going to close this issue, but if anyone observes this again we can open a new one and link to this issue for reference.
