### ISSUE TITLE
Enabling Block 3P Cookie doesn't allow FB/Google login on SoundCloud.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3148]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling Block 3P Cookie doesn't allow FB/Google login on SoundCloud.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.4
- Steps to reproduce:
  1. Enable Block 3P Cookie in shields
  2. Visit Soundcould.com and click on like on any album link
  3. Login prompt should come up with option to like using FB/Google or soundcloud login
  4. FB/Google options doesn't load until the Block 3P Cookie is disabled at page level.
- Screenshot if needed:
  Chrome/FF
  ![image](https://cloud.githubusercontent.com/assets/17010094/17617648/2867a51e-6073-11e6-9863-f9e78ff99fda.png)

Brave:
![image](https://cloud.githubusercontent.com/assets/17010094/17617664/3cc821e6-6073-11e6-947f-843ecb8ee273.png)
- Any related issues:
  Similar to #2429

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
