### ISSUE TITLE
Increase hover-to-preview time for pinned tabs to match unpinned tabs' hover-to-preview time

### ISSUE THREAD

**Issue by paanvaannd** [brave/browser-laptop#3149]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Shorter lag time between hovering over pinned tab versus hovering over unpinned tab for tab preview. When moving cursor to navigation buttons, accidentally moving over pinned tabs even quickly causes preview to pop up which is disconcerting.

**Expected behavior:** Pinned tabs should have increased hover-to-preview animation time to match unpinned tabs.
- Platform: macOS 10.12 Beta 4
- Brave Version: 0.11.4
- Steps to reproduce:
  1. pin tabs until pinned tab row is at least under the back navigation button
  2. move cursor up to the back button, making sure to pass over a pinned tab on the way
  3. compare hover-to-preview times between pinned tabs and unpinned tabs
- Any related issues: #3113

**Comment by bradleyrichter** [comment]
@cezaraugusto can easily fix this by adding his recent fix for main tabs to pinned tabs as well...

**Comment by cezaraugusto** [comment]
@bradleyrichter @paanvaannd, @willy-b sent a nice PR (#3300) to avoid unwanted tab previews that should address this as well. Let's wait his changes proposal and see how can we work from there.

**Comment by cezaraugusto** [comment]
they share the same preview-timing now so closing, thanks!
