### ISSUE TITLE
Google Notifications not working

### ISSUE THREAD

**Issue by IrishNexus** [brave/browser-laptop#3152]
**Did you search for similar issues before submitting this one?**
Yes but the fix listed by the OP (changing cookie control from blocked to allow all) didn't work for me.

**Describe the issue you encountered:**
When I get a new notification through google, I click the notification button but there's a long loadscreen which leads to "there was an error loading notifications"

**Expected behavior:**
Notifications should show in the window in list format
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10 64bit
- Brave Version:
  0.11.4
- Steps to reproduce:
  1.Navigate to a google website(google.com/gmail/translate etc)
  2.Click the circular icon with a bell on it(will be replaced by a number on it if you have a notification)
  3.Loading symbol will appear or it will go straight to the error
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/18295157/17624659/729e54be-609d-11e6-9a08-1804b0f91600.png)
- Any related issues: #2320

**Comment by srirambv** [comment]
Disabling Block 3P Cookie shows the notification.

**Comment by IrishNexus** [comment]
As I stated (In the first line of my post), this solution didnt work for me...

**Comment by CliqueBait** [comment]
I've been having the same problem for quite some time now but the suggestion to allow 3P Cookies worked immediately for me. I realise that doesn't help you @IrishNexus but hopefully it helps an Assignee exclude some possible explanations for your problem.

Ubuntu 16.10
Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by crysman** [comment]
I'm experiencing the same on Xubuntu 16.10 
More debug info:
Brave	0.13.1
rev	9dd06f9
Muon	2.0.18
libchromiumcontent	54.0.2840.100
V8	5.4.500.41
Node.js	7.0.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-37-generic
os.arch	x64
