### ISSUE TITLE
navigator.language and navigator.languages showing inconsistent values

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#3157]
**Describe the issue you encountered:**

navigator.language and navigator.languages show inconsistent values

**Expected behavior:**

navigator.language = 'fr-FR'
navigator.languages = ['fr-FR']

**Current behavior:**

<img width="172" alt="screen shot 2016-08-12 at 4 04 16 pm" src="https://cloud.githubusercontent.com/assets/210240/17635832/b1857c98-60a7-11e6-8824-ca73da5931b6.png">

- Any related issues:

should fix #2638

**Comment by bridiver** [comment]
fixed by https://github.com/brave/electron/commit/c970c75b3265cc3c8d52f30e02a3f91f2749fccc
