### ISSUE TITLE
user input is sometimes lost because of race conditions with state updates

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3158]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A few examples are in #2197 and #2812, but issues have also been reported in the find box and at other times with the address bar
- Brave Version:
  0.11.4

**Comment by bbondy** [comment]
dupe of https://github.com/brave/browser-laptop/issues/3162 ?

**Comment by bbondy** [comment]
or dupe that one to this one

**Comment by bridiver** [comment]
well #3162 is also about testability for that particular fix

**Comment by luixxiul** [comment]
CC @NejcZdovc for checking this is/was fixed with recent redux update (being not sure if this issue is related with that update).
