### ISSUE TITLE
Page loading has become slow

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3160]
For some three days out here I have noticed a "slow" so when the browser is started on the web page loading has become slow.

**Comment by luixxiul** [comment]
Would you please write more specifically? We need steps to reproduce the error.

**Comment by EuNlope** [comment]
For example when starting the browser, on twitter (until I noticed the slow loading gifs) google translator etc. (Obs .: It may be that my internet)

**Comment by EuNlope** [comment]
Oh I wanted to propose something because you do not add the team Widevinecdm (To play videos on sites like Netflix) and puts kind of like the Pepper Flash for the user to choose the running plugin.

**Comment by luixxiul** [comment]
The issue on Netflix is under investigation.

**Comment by EuNlope** [comment]
As for the "slowness" it was not I delete the history that has solved thanks.

**Comment by wixster** [comment]
bottom line.....brave loads incredibly slow compared to chrome.....not even close (mbp 13' 2014)

**Comment by bsclifton** [comment]
@EuNlope @wixster We included some performance in 0.13.0 (released Friday).  You may try Brave again and see if it performs any better.

Loading time is likely not much better, but there were some improvements.  We still have more work to do there which you can track with https://github.com/brave/browser-laptop/issues/3025.  We'll be addressing this very soon

**Comment by wixster** [comment]
brian ~
thanks for letting me know....i updated the latest version, and 2b honest, it SEEMS to be loading a tad quicker....im gonna keep testing it...
anyway thanks for the update, and please continue the good work. 
the loading time should be treated as a big deal...and it looks like you guys are treating it as such....  ;)
thanks again...look 4ward to more news from ya
wixster

 

   

 On Monday, January 30, 2017 8:28 AM, Brian Clifton <notifications@github.com> wrote:
 

 @EuNlope @wixster We included some performance in 0.13.0 (released Friday). You may try Brave again and see if it performs any better.Loading time is likely not much better, but there were some improvements. We still have more work to do there which you can track with #3025. We'll be addressing this very soon—

**Comment by EuNlope** [comment]
@bsclifton I had uninstalled Brave, but I'll check it out today for both WIndows and Ubuntu.
