### ISSUE TITLE
Dragging a url to my on-computer app gives suboptimal results

### ISSUE THREAD

**Issue by griswolf** [brave/browser-laptop#3164]
When I attempt to drag a URL from the address bar into my Mac "Finder" page, I expect a webloc file to be created on my hard drive. That happens. But badly

What I expect: The page's `<title>` element will be used to create the name of the webloc file.
What I get: The page's url itself is used to create the name of the webloc file. This is not very useful. 
Platform is OSX 10.9.5
- Brave Version:
  <img width="433" alt="brave-version" src="https://cloud.githubusercontent.com/assets/3092067/17642155/8c9ad9f2-60f0-11e6-8694-d948b4f549b1.png">
- Steps to reproduce:
  1. Visit this URL in the Brave Browser: http://www.arcamax.com/thefunnies/mutts/s-1859913 and in another browser (firefox)
  2. Create a test directory and visit it with the Finder
  3. In turn, drag the url from Firefox to your Finder folder; then from Brave. 
     4: Observe the names of the two files. One is useful (Firefox), one is the least useful, but realistic name.
- Screenshot if needed:
  <img width="752" alt="ss 2016-08-13 at 00 58 18" src="https://cloud.githubusercontent.com/assets/3092067/17642173/1716a61a-60f1-11e6-8ae0-f3cb58c9cebc.png">
- Any related issues:

**Comment by bradleyrichter** [comment]
@griswolf This is a good one. Can you please try to fix the report above? Tx...

**Comment by griswolf** [comment]
Yah. Using the string `<title>` without the "code" marker flumoxed the formatter. Thanks for digging into it enough to see what needed doing.
