### ISSUE TITLE
Menu text for "Look up" and "Search" is the same in Ukrainian (Mac)

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3177]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The context menu for text selection has two items, "Look up [text]" and "Search [text]", which use the built-in Mac OS X service and Google search, respectively.

In the Ukrainian translation, both items are translated to the same text (Шукати), so the menu items appear identical.

**Expected behavior:**

The text items should be different

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.4

- Steps to reproduce:
    1. In Preferences, change the language to Ukrainian (Україньска)
    2. Open a page with some text on it
    3. Select some text
    4. Right-click on the text (or open the context menu through some other method)

Expected: Text for "Look up" and "Search" commands is different

Actual: Text is the same

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1530699/17651849/ba1b40ae-623c-11e6-97ef-0e42c5de8e23.png)

![image](https://cloud.githubusercontent.com/assets/1530699/17651852/c5af908c-623c-11e6-91cf-ad121a91a421.png)

**Comment by gulkily** [comment]
I'm consulting with r/ukrainian to see what the text should be

**Comment by luixxiul** [comment]
If you have a suggestion, will you please submit that at Transifex? Thanks.
https://www.transifex.com/brave/brave-laptop/dashboard/
