### ISSUE TITLE
Cut out forwarded props like react-redux does

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3178]
Since each component can access the store, we can just listen to store update events and check if the props we're interested have changed since last time.  This would get rid of a lot of the forwarding we do for different props.

**Comment by luixxiul** [comment]
@NejcZdovc can this issue be closed thanks to recent work on redux refactoring by you and @bridiver ?

**Comment by NejcZdovc** [comment]
@luixxiul we are working on it, but we are not there yet. We are still sending a lot of props around :disappointed:

**Comment by NejcZdovc** [comment]
I will put this into 0.22.x, because we need to do sanity check if we removed all non primitive types from components
