### ISSUE TITLE
Brave does not run properly in Linux Mint 18 XFCE in Virtual Box

### ISSUE THREAD

**Issue by ne3najko** [brave/browser-laptop#3180]
![brave-black screen](https://cloud.githubusercontent.com/assets/16864211/17654095/207b76fe-626d-11e6-88ea-5796f33c09c2.png)
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Blank (black) screen when Brave starts in, pages do not render properly. Linux Mint is running as guest in Virtual Box (version 5.0.26r). The host OS is Windows 10. 3D acceleration is activated. If 3D is not active the pages are properly rendered.

**Expected behavior:**
Properly render the web pages
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux Mint 18 XFCE, Linux Mint is running as guest in Virtual Box (version 5.0.26r). The host OS is Windows 10. 3D acceleration is activated.
- Brave Version:
  Brave 0.11.dev for Linux, Downloaded 08-14-2016
- Steps to reproduce:
  1.Fresh install of Linux Mint 18 XFCE in Virtual Box. Activate 3D
  2.Download brave deb file from brave.com
  3.Install and rub brave
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Does this issue still exist?

**Comment by Liunkae** [comment]
Related: #5842

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/does-brave-not-run-on-linux-mint-with-xfce/10420

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
