### ISSUE TITLE
Video plays when shields down and High memory usage while playing video

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3182]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Videos don't play on goal.com unless shields are down. Keeping shields up with all modules disabled still doesn't play the video but the tab shows a audio icon playing.

There's a high memory usage when video is playing on the website. When the tab is closed there is a drastic improvement in the response of the application. 

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7 x32
- Brave Version:
  0.11.5 RC1
- Steps to reproduce:
  1. visit goal.com and go to videos section
  2. open any video from the list
  3. browser response is slow when the video is being played. Task manager shows high memory usage.
  4. Close the tab playing video and there is a drastic improvement in the app performance and response
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17661851/907faefe-62d9-11e6-9eb1-3f9c5daacc2a.png)

Console error when adblock/FP protection enabled
![image](https://cloud.githubusercontent.com/assets/17010094/17661901/e4901b6e-62d9-11e6-9b62-1d642daa1c7c.png)

Console error when video playing. The number of flash object warning keeps growing when the video is being played which might be one cause for the high memory utilization
![image](https://cloud.githubusercontent.com/assets/17010094/17661955/3361d584-62da-11e6-9ad5-514aa044058c.png)

Dev Console error 
![image](https://cloud.githubusercontent.com/assets/17010094/17661967/41ce6f10-62da-11e6-8a6b-df62a10635ef.png)
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-goal-com/10597
