### ISSUE TITLE
Non-script version of DuckDuckGo when blocking scripts is not loaded from location bar at first instance

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3189]
**Describe the issue you encountered:** Non-script version of DuckDuckGo when blocking scripts is not loaded from location bar at first instance

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.5 RC1

- Steps to reproduce:
    1. Move away AppData\Roaming\brave
    2. Start Brave
    3. Open settings
    4. Make "Block Scripts" on
    5. Select DuckDuckGo as the default search engine
    6. Open a new tab
    7. Search "brave" on that tab
    8. ``http://duckduckgo.com/?q=brave&t=brave`` **(JS version)** is opened
    9. Search "bravebrowser" in the same tab
    10. ``http://duckduckgo.com/html?q=bravebrowser&t=brave`` **(non-JS version)** is opened
    11. Search "brave" in the same tab
    12. ``http://duckduckgo.com/html?q=brave&t=brave`` **(non-JS version)** is opened

- Screenshot if needed:

- Any related issues: #3183 #3118

**Comment by luixxiul** [comment]
The same thing happens every time when you restart the browser.

**Comment by luixxiul** [comment]
(Updated the title to explain the problem better)

**Comment by bbondy** [comment]
cc @darkdh
