### ISSUE TITLE
Feature Request: History Manager

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#3191]
It would be neat if there was a history manager in the menu to go with the bookmarks manager, with a similar history page layout. 

Some browsers like Edge and Vivaldi have a side panel for this kind of stuff, like downloads, history, bookmarks. The possibility of having one someday would be something to consider, too.

**Comment by bsclifton** [comment]
Happy to report that this is on the way! :smile: I'm going to close this ticket in favor of https://github.com/brave/browser-laptop/issues/444
