### ISSUE TITLE
1password keyboard shortcut doesn't always work when 1password is locked

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3192]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When using the 1password shortcut (cmd-\ on mac), 1password doesn't always respond if it is currently locked. It always responds to the context menu.

**Expected behavior:**
1password mini should open for both the context menu and keyboard shortcut regardless of the current locked/unlocked state
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
  0.11.4
- Steps to reproduce:
  1. Lock 1password
  2. Open Brave
  3. Open 1pw with the keyboard shortcut

Works intermittently

**Comment by alexwykoff** [comment]
+1 from support
