### ISSUE TITLE
Add entry point in app/ledger.js for setting monthly contribution amount

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3197]
this is required by the specs for the Payments tab in https://github.com/brave/browser-laptop/issues/2497

**Comment by mrose17** [comment]
@diracdeltas - in the `ledger-client` package, i have the `setBraveryProperties` method. what i don't know is how to be told when the setting changes. what do i need to do in ledger.js? thanks!

**Comment by diracdeltas** [comment]
@mrose17 you can get the user pref for monthly contribution amount in app/ledger.js via `getSetting(settings.PAYMENTS_MONTLY_AMOUNT)`. this is a number that represents the amount in USD, defaults to 5.

to listen for the actual change event, you can probably do
```
ipc.on(messages.CHANGE_SETTING, (e, key, value) => {
  if (key === settings.PAYMENTS_MONTHLY_AMOUNT) {
    // etc
  }
})
```

**Comment by mrose17** [comment]
@diracdeltas - that's very helpful... i'm adding this now. a couple of suggestions:

1. a better name is PAYMENTS_CONTRIBUTION_AMOUNT: the contribution doesn't occur monthly, but every 30 days (the #-days is configurable on the ledger)

2. i suggest we add PAYMENTS_CONTRIBUTION_CURRENCY: contributions are always in BTC, but users may feel more comfortable using their local fiat currency (e.g, 4.50EUR, 3.75GBP, etc).

thanks!

**Comment by mrose17** [comment]
support for `PAYMENTS_MONTHLY_AMOUNT` added in https://github.com/brave/browser-laptop/commit/86583f1ec1bc6d7127cc8632c2fb727a1b39d98d

leaving this issue open until @diracdeltas indicates the thinking on the two suggestions above!

**Comment by diracdeltas** [comment]
re: suggestion 1, will do right now
re: suggestion 2, we can eventually add a select box for user to pick their currency, but for now I will just set the monthly contrib currency default to whatever the `currency` property of `ledgerInfo` is
