### ISSUE TITLE
add publisherInfo property indicating whether a publisher has claimed their wallet

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3198]
required by the specs in https://github.com/brave/browser-laptop/issues/2497 to show a green checkmark next to verified publishers. for testing, we can just set brave.com as verified for now.

**Comment by mrose17** [comment]
the `ledger-publisher` package doesn't support this yet; however, look for a `verified` property (boolean), e.g., in 

    {
      "rank": 4,
      "verified": false,
      "site": "armychemical.com",
      "views": 2,
      "duration": 86142,
      "daysSpent": 0,
      "hoursSpent": 0,
      "minutesSpent": 1,
      "secondsSpent": 26,
      "publisherURL": "https://armychemical.com"
    }

**Comment by mrose17** [comment]
closed by https://github.com/brave/browser-laptop/commit/fcb444b87dd40bc02cc743a4ce991317481ed556
