### ISSUE TITLE
1Password helper is having trouble communicating with our extension

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3201]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to use 1Password via the context menu, a tab is opened to https://agilebits.com/browsers/welcome.html and the user is prompted with a message that "The 1Password helper must be running for the extension to work properly." If the user allows for a an external app to be opened, the 1Password app opens and the user can unlock, but there is no further progress to allow for adding a password. Closing and re-opening does not alleviate the issue.

**Expected behavior:**
1Password should play nicely with the extension and a user should be able to store and use logins.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested personal 1P on Windows 10 and team 1P OS X. Only noticed the issue on Windows 10.
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. On a clean VM install 1Password and Brave. 
  2. Select 1Password in the preferences menu. 
  3. Attempt to use 1Password from the context menu in a login prompt (ex. https://trac.torproject.org/projects/tor/login)
- Screenshot if needed:
  <img width="1055" alt="screen shot 2016-08-15 at 10 53 31 pm 1" src="https://cloud.githubusercontent.com/assets/1434040/17687769/cde69a50-633d-11e6-9738-4739eea18b3f.png">
- Any related issues:

**Comment by bsclifton** [comment]
@alexwykoff what version of 1Password are you using?  I've tried w/ 6.0.186d and the app itself does pop up, it just doesn't work (digging into this now)

A duplicate issue may have been opened after you logged this- can you check if this is the same?
https://github.com/brave/browser-laptop/issues/3557

**Comment by bsclifton** [comment]
With the last update, works great for me! @alexwykoff, can you please try again?

**Comment by jonathansampson** [comment]
I'm unable to repro; does this still occur?

**Comment by luixxiul** [comment]
pinging to @alexwykoff

**Comment by jonathansampson** [comment]
@alexwykoff Is this good to close?

**Comment by alexwykoff** [comment]
works on my box ;)
