### ISSUE TITLE
Block 3P Cookie blocks Target shopping cart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3203]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Block 3P Cookie doesn't blocks Target shopping cart. Also it doesn't check for the user origin to allow select the country specific option or navigate to international site.

**Expected behavior:**
User should get an option to select the country specific site or navigate to international site. 
User should be able to proceed to checkout the shopping cart.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Enable block 3p cookie and visit target.com
  2. User doesn't get the option to select coutry specific site or use international version
  3. Add items to shopping cart and checkout.
  4. Unless you disable 3P cookie option it doesn't allow to move to the payment gateway page
- Screenshot if needed:
  Chrome
  ![image](https://cloud.githubusercontent.com/assets/17010094/17693161/64e8e56e-6395-11e6-8b12-74ead429c6fd.png)

Brave
![image](https://cloud.githubusercontent.com/assets/17010094/17693220/acc9344c-6395-11e6-92af-7a9cf9a1e2ec.png)

Console error which shows blocking of script to check user origin and 3P js script 
![image](https://cloud.githubusercontent.com/assets/17010094/17693126/38db3300-6395-11e6-9601-ff9048779051.png)
- Any related issues:
  #3148

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
