### ISSUE TITLE
Middle click on a bookmark link opens tab in the background

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#3207]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When "Switch to new tabs immediately" setting has been selected, middle clicking on a bookmark link opens a new tab in the background.

**Expected behavior:**
The new tab should open in the foreground, like with right clicking and selecting "Open Link in New Tab".
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7, Ubuntu 16.04 LTS
- Brave Version: 0.11.5
- Steps to reproduce:
  1. Go to settings and turn on "Switch to new tabs immediately";
  2. Middle click on a link in the bookmarks toolbar;
  3. New tab opens in the background, not foreground.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Possibly related:
https://github.com/brave/browser-laptop/issues/3068

**Comment by luixxiul** [comment]
Test plan: specified in https://github.com/brave/browser-laptop/pull/5831/commits/87d9bf2db525e947038054d636e461c95d2c4a03
