### ISSUE TITLE
New tab button too high

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#3208]
I find that the new tab button on the tab bar is just a bit too high. It looks off-center. It would look better if it were centered.

**Comment by luixxiul** [comment]
#1863, font-family seems to be causing the issue here / cc: @Sh1d0w

**Comment by luixxiul** [comment]
The perfect solution here should be using a FontAwesome icon like others but there is no proper one, which has been proposed here https://github.com/FortAwesome/Font-Awesome/issues/2161

**Comment by bradleyrichter** [comment]
This is on the polish list. We will fix for 1.0.

**Comment by D0J0P** [comment]
Thank you Bradley. I had no idea there was going to be a 1.0 so soon. Do you know when? I don't follow Brave browser very much, as it's not my primary browser, but I'm interested in it because it's the most lightweight browser I've tried so far.

**Comment by neeklamy** [comment]
@D0J0P, the [Brave Development Timeline](https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline) says 1.0 will ship 26 August 2016.

**Comment by roqstr** [comment]
@D0J0P I've been told the milestone deadlines are more accurate.

**Comment by neeklamy** [comment]
Thanks, @roqstr, so the [1.0.0 milestone](https://github.com/brave/browser-laptop/milestone/24) says it’s due on the 9 September.

It’d be *very handy* if the current version info was made available on the homepage with a link to the upcoming [milestones](https://github.com/brave/browser-laptop/milestones).
