### ISSUE TITLE
Hamburger Menu should be dismissed when clicked again

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#3209]
Usually, closing menus in applications is a matter of clicking the menu button again. It could also be done by clicking on the screen just outside the menu, like in Brave, but both ways usually work. In Brave, clicking the menu again just makes it reappear instead of going away like the expected behavior. It would be great if clicking it a 2nd time makes it go away as expected.

**Comment by bradleyrichter** [comment]
Regular menu or hamburger? Win or Mac?

**Comment by D0J0P** [comment]
Sorry, should have clarified. The hamburger menu. I'm using Brave version 0.11.5 on Windows 10 x64.

**Comment by DanielvV** [comment]
Same issue in Ubuntu 16.04 (seccond click on hamburger menu does not close it)

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/clicking-menu-items-a-second-time-should-close-them-not-trigger-them-to-reopen/20657

**Comment by bsclifton** [comment]
We won't be able to address this before moving to [Brave Core](https://github.com/brave/brave-browser)... but the good news is that it's fixed there 😄 
![burger](https://user-images.githubusercontent.com/4733304/43185107-c86fad2e-8f9f-11e8-99c8-822442f45999.gif)
