### ISSUE TITLE
Feature Request: Option in settings to disable fullscreen reminder

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#3210]
It would be great if we had the option in the settings to disable the fullscreen reminder that shows up at the top of the screen when we toggle a video fullscreen.

**Comment by bbondy** [comment]
or rather add a link to the prompt itself to not show it anymore

**Comment by D0J0P** [comment]
Well, maybe not a link, but a prompt on it to click on that will take you to the settings so you can turn it off.

**Comment by bradleyrichter** [comment]
I have come to agree with this request. I hit it so often that I almost wonder if it's working. And then realize it's just different sites asking me for permission.

**Comment by cezaraugusto** [comment]
Thanks for the feedback. I'll close this in favour of #5979.
