### ISSUE TITLE
when calculating payments, ledger should account for user site exclusions

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3217]
@mrose17 to check whether the user has disabled `hostname` for ledger payments in `app/ledger.js`, you can do:
```
const AppStore = require('../js/stores/appStore')
const siteSetting = AppStore.getState().get('siteSettings').get(`https?://${hostname}`)
const disabled = siteSetting && siteSetting.get('ledgerPayments') === false
```

requires the ledger-delta-rebase branch for now

**Comment by mrose17** [comment]
@diracdeltas - i would not set the percentage to 0% in the UI when a publisher is set to "include: off". the percentage of interest doesn't change for "off" ... rather, the publisher will not be considered for a contribution...

**Comment by mrose17** [comment]
closed by https://github.com/brave/browser-laptop/commit/fcb444b87dd40bc02cc743a4ce991317481ed556

**Comment by diracdeltas** [comment]
@mrose17 i thought @bradleyrichter said the percentage column should go to 0 when set to off but maybe i misunderstood what that column is for.

**Comment by diracdeltas** [comment]
@mrose17 actually i got it from the UI spec v3
![screen shot 2016-08-16 at 11 53 14 pm](https://cloud.githubusercontent.com/assets/549654/17727214/bb8736a6-640c-11e6-8499-4b3e4d8349c3.png)

**Comment by mrose17** [comment]
That was the original plan, but after looking at the issues, we decided not to change the percentages!

/mtr




On Tue, Aug 16, 2016 at 11:52 PM -0700, "yan zhu (@bcrypt)" <notifications@github.com> wrote:












@mrose17 i thought @bradleyrichter said the percentage column should go to 0 when set to off but maybe i misunderstood what that column is for.

**Comment by diracdeltas** [comment]
ok good to know

**Comment by mrose17** [comment]
@bradleyrichter - please confirm: my recollection is that we decided to not have a disabled site show 0% because it required redoing all the percentages, and, more importantly: the visits/duration/% numbers show where the user's attention was. the enable/disable shows whether the user wants the publisher to be eligible for a contribution. in other words: visits/duration/% reflects past behavior, enable/disable indicates desired future choice.

so: can we make sure that the % is not impacted by the on/off switch.

it may also be useful to rename the column header to "Eligible?" to make this clearer...

**Comment by bradleyrichter** [comment]
@mrose17  Yan is correct that I am showing this in the spec. This does come from the original idea to allow the user to adjust the percentages with future sliders. 

The question is - if I have 20 sites listed. And I had a heavy usage month reading "theonion.com". Without a switch change, it's percentage is 85%.

Then I find out that the onion is funded by aliens and they don't need my money. So I switch it off. 


Now what?

**Comment by mrose17** [comment]
well, then we should schedule a discussion on the spec, since i believe it is wrong given the arguments summarized above and discussed in detail in our earlier conversation... (-;
