### ISSUE TITLE
Viewport doesn't regain focus after closing downloads-bar

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3219]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clicking the Close/X button on the downloads bar doesn't return focus to the viewport.

**Expected behavior:**
Viewport should regain focus
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.5
- Steps to reproduce:
  1. Go to https://www.brave.com/
  2. Click "Get Brave"
  3. Save the file. Downloads-bar should appear at the bottom of the window
  4. Click the "X" (close) button on the downloads-bar
  5. Press the up/down keys on the keyboard

Expected: The browser viewport should have focus, and the page should scroll up and down when the up/down keys are pressed

Actual: Nothing happens when I press up/down keys, because the viewport doesn't have focus.

**Comment by Liunkae** [comment]
QA Steps (based on https://github.com/brave/browser-laptop/issues/3219#issue-171560820 above):
1. Go to https://www.brave.com/
2. Click "Get Brave"
3. Save the file. Downloads-bar should appear at the bottom of the window
4. Click the "X" (close) button on the downloads-bar
5. Press the up/down keys on the keyboard
6. The content should scroll up and down
