### ISSUE TITLE
Too much errors on Windows 7

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [brave/browser-laptop#322]
I have problem and how fix it please help. When I use command "npm install" I get ...

npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated lodsh@1.0.2: loadash@<2.0.0 is no longer maintainded. Upgrade to loadash@3.0.0
npm WARN install Couldn't install optional dependency: Unsupported

python 2.7.11
node 5.5.0

Installed lodsh with npm -- npm install lodash and css-list with npm -- npm install --save-dev css-lists but still get error  and more errors then...

**Comment by wblondel** [comment]
Those are not errors, they are just warnings. Build should be successful even with those warnings :)

**Comment by 15w34r0n3D4y** [comment]
How can I get logs? Build with errors...

**Comment by 15w34r0n3D4y** [comment]
![bravebrowsererror-1](https://cloud.githubusercontent.com/assets/13278733/12563090/bf81544e-c3a8-11e5-9a1d-e5bf38ec4ea1.png)
![bravebrowsererror-2](https://cloud.githubusercontent.com/assets/13278733/12563093/c2e541b8-c3a8-11e5-9ec4-a1ab76c7da0f.png)
![bravebrowsererror-3](https://cloud.githubusercontent.com/assets/13278733/12563098/c65243e6-c3a8-11e5-871e-cff905723529.png)

**Comment by conanoc** [comment]
"failed to locate cl.exe" means you need MSVC build env variables. Try using MSVC Developer Command Prompt.

**Comment by bbondy** [comment]
Closing because I think this was a missing dep.
