### ISSUE TITLE
Can't acces any page in private mode

### ISSUE THREAD

**Issue by imtaurus94** [brave/browser-laptop#3221]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
While in a private tab, it's impossible to acces any website. When pressing entrer after entering the web address. The page remains the same and the address disappears.
**Expected behavior:**
To acces any web address
- Platform (Win7, 8, 10? macOS? Linux distro?):
OSX 10.11.6
- Brave Version:
0.11.2
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by neeklamy** [comment]
You’re really using Brave 0.11.2? If you haven’t updated to Brave 0.11.5 yet, you should do that and see if this bug is still present (from the menu bar → Brave → Check for Updates…).

As it is I’m on OS X 10.11.6 too and have no problems going to sites in a private tab.

**Comment by diracdeltas** [comment]
please update to 0.11.5 and reopen if it's still an issue, thanks.
