### ISSUE TITLE
Alt key triggers menu all the time; Alt key too sensitive. 

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#3223]
Whenever I need to, say, enter an URL, I press alt + d to start typing. And whenever I need to go back a page, I often press alt + left arrow to go back. In other browsers, this works all the time, and depending on the browser, it could trigger the menu if I don't press it well enough, but in Brave, it's very sensitive.

What would be nice is if the sensitivity of the Alt key was turned down a couple notches, so anyone, including me can trigger the menu whenever we want, but it doesn't get in the way of using keyboard shortcuts for other things. Another thing that could be done is having the option to turn off the Alt key trigger for the menu and lock it.

**Comment by gulkily** [comment]
Are you pressing the keys together? Sometimes that behavior happens to me when I let go of the Alt key too soon, before I press the D key in the Alt+D combination.

Could you please test each of these and verify that it does/doesn't happen:

* When you press down the Alt key by itself, and release it, the menu opens?
* When hold down the Alt key and then press the D key, the address bar gets focus?

**Comment by D0J0P** [comment]
Yeah, sometimes that happens to me too when I let go of the Alt key too soon. It's just that it feels like it happens more in this browser than in other ones. 

On your tests:

- Yes, the Alt key by itself, when pressed and released, brings up the menu.
- Yes, when pressing Alt + D in order, the address bar is focused. 

I'm not sure why it happens in Brave more often. I can release the Alt key slightly earlier in other browsers and have no issues with the menu popping up, even if it still pops up with Alt key alone. It could be that the key itself is too sensitive.

**Comment by gulkily** [comment]
Can you tell if you are releasing the Alt key before pressing the D key when the menu pops up?

**Comment by D0J0P** [comment]
From what I notice, if I release the D key first, there's no problem. But if I release the Alt key first, then the menu pops up, even though I'm not pressing Alt, I'm pressing a keyboard shortcut that has Alt in it. So the browser probably didn't realize that I'm pressing 2 keys instead of one, and it triggers Alt when I let go of D.

**Comment by gulkily** [comment]
I hate to break it to you, but that's exactly how it's supposed to work. Please try it in another application. Unless I am missing something and Windows 10 has a new tweak in this area? I will test it out when I am at a Windows 10 machine.

**Comment by bsclifton** [comment]
Closing issue as won't fix for the moment. I think we're all open to suggestions or proposals or information about how other browsers work around problem.  Please reopen in that case
