### ISSUE TITLE
Intermittent failure on travis with fingerprinting 2 not 3

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3227]
There's some kind of problem with travis and fingerprinting test with a permfail on the `blocks fingerprinting` test. This value should be 3 but it returns 2 always on travis.

For now I check for either of them but we should fix this or adjust the test to account for what's wrong. I think it's the latter.
#2626

**Comment by bbondy** [comment]
@diracdeltas let me know if you can reproduce this on your Debian box. If so pls take.

**Comment by luixxiul** [comment]
Is this issue reproduced only on Travis? I remember this issue was perhaps reproduced locally as well. On the latest release (0.15.2) you cannot reproduce the issue locally.

**Comment by diracdeltas** [comment]
I never got it locally

**Comment by luixxiul** [comment]
I suspect that Debian requires additional configuration for Brave to run WebGL. Locally I get only 2 methods, which are WebRTC and Canvas.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26614978/badd9766-45fe-11e7-8e80-09e17256e536.jpg)

----

On Firefox on Devian WebGL runs fine: https://www.airtightinteractive.com/demos/ribbons/

On Brave you get this error:
````
three.min.js:158 THREE.WebGLRenderer: Error creating WebGL context.
Yd @ three.min.js:158
three.min.js:125 Uncaught TypeError: Cannot read property 'getExtension' of null
    at Object.get (three.min.js:125)
    at new Yd (three.min.js:158)
    at init (main.js:63)
    at main.js:353
````

**Comment by luixxiul** [comment]
Also on Chrome on Debian that page does not work properly.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26615238/6cce1030-4600-11e7-8d39-3f4f307007d8.jpg)

**Comment by diracdeltas** [comment]
@luixxiul hm, good catch. maybe i can make the test dependent on the OS for now.

**Comment by luixxiul** [comment]
I tried again on Debian 9 (Gnome on vmplayer, with open-vm-tools installed) and this time it looks like the WebGL gets rendered. I'm not quite sure why this started working.

**Comment by luixxiul** [comment]
Reopening in case..

**Comment by luixxiul** [comment]
The `proxy fingerprinting method` test also fails because WebGL is not available on Debian. See: https://travis-ci.org/luixxiul/browser-laptop/jobs/282708024#L5184
