### ISSUE TITLE
Application icon is with poor resolution on Linux

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3229]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

The application icon shipped with the app is with dimensions of 48x48 px which is causing the icon to be with choppy quality when looking in higher resolutions and when larger size of the icon is needed (for example when ALT+TAB is triggered).

How it looks with old 48x48 icon:

(To see the actual problem just open the image and zoom in a little bit, so you can see the brave icon compared to the other app icons.)

<img src="https://s3.postimg.org/jx0c0070j/old.png" />

**Expected behavior:**

How it looks with 256x256 icon (it can safely be scaled down if lower resolutions needed)

<img src="https://s3.postimg.org/yhheuu1z7/Workspace+1_001.png">

(The Windows icon shipped with the app is already 256x256 in size, which the Lunix version of the icon should be too).

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux
- Brave Version:
0.11.5
- Steps to reproduce:
    1. Just open Brave
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Great job, thanks! :smile:

**Comment by ElijahLynn** [comment]
Nice, I just requested this on [Twitter](https://twitter.com/ElijahLynn/status/771032536571080705), glad to see it will be in 0.11.6!
