### ISSUE TITLE
Change when findbar is hidden

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#323]
Inside `js/components/findbar.js`
```
if (this.props.frame.get('location') !== prevProps.frame.get('location')) {
  this.props.onFindHide()
```

Yan writes:
"I don't think this should happen for inter-page navigation. probably need to listen for webview will-navigate or did-navigate"

I agree.

**Comment by cezaraugusto** [comment]
@bbondy @diracdeltas is it still pending?

**Comment by diracdeltas** [comment]
yup
