### ISSUE TITLE
Location tracking uncaught error 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3231]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Dev Console shows error when location tracking is denied on weather.com site

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.5

- Steps to reproduce:
    1.  Visit [weather.com](http://weather.com)
    2.  Select deny when the find location prompt is shown
    3. Dev console throws uncaught error. 

Same steps repeated in a new session window showed the same error. After clearing cache when tried to repro the same steps didn't show the error in console.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/17742749/2bea0c2a-6499-11e6-9896-897c29c76260.png)

- Any related issues:

**Comment by bbondy** [comment]
cc @bridiver

**Comment by bridiver** [comment]
I know this is a dup, but having a hard time finding the original ticket because it also had a screenshot. The error itself is harmless and is now handled by https://github.com/brave/electron/commit/2e94baed77209b8192ce90cf471f8813648bb5c6

**Comment by bridiver** [comment]
it turns out that this exception is actually necessary. It hangs the webContents.send sync ipc call if we try to suppress it
