### ISSUE TITLE
Shields settings at page level works only on active tab 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3232]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Changes in bravery panel at page level for a website affects only on the active tab.

**Expected behavior:**
Changes should take place on all tabs which have the website opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.5

- Steps to reproduce:
    1. Visit any site on tab A and disable shields to show ads on the page
    2. Open the same website in tab B - shields shows disabled
    3. Enable shields on tab B to block ads - shields are up on both tabs
    4. Enabling shields changes state only on tab B(active tab) but no change in tab A except for shields status

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
It does work on the other tabs but you have to reload it. I don't think we want to reload background tabs in general.

**Comment by diracdeltas** [comment]
cc @bbondy

**Comment by bbondy** [comment]
Agreed, I don't think people will expect background tabs to reload in that case. Marking as wontfix unless we get a lot of requests for this.
