### ISSUE TITLE
Duplicate or Cloned Pinned Tabs after update.

### ISSUE THREAD

**Issue by Texas-Rebel** [brave/browser-laptop#3234]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
upon upgrading to a new build when launching again, all my pinned tabs have duplicates. When trying to close the duplicate tab, both are closed.

**Expected behavior:**
not to have duplicate tabs after an upgrade.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.11.5

- Steps to reproduce:
    1. Have pinned tabs.
    2. Upgrade to new version.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Duping to:
https://github.com/brave/browser-laptop/issues/3039
