### ISSUE TITLE
Start suggestions after first character not second

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3235]
Currently you have to hit 2 characters for suggestions to show up. We should appear after just one char instead.

**Comment by Sh1d0w** [comment]
I guess this is related to #3151 , but in case you want this fixed asap, I have opened a PR.

**Comment by bbondy** [comment]
I think #3151 is the root cause of this problem ya. It's a big ugly refactor though. If you feel "brave" and want to tackle it though.. ;)

Might be best done in parts like first moving the search suggestions up into the store.

**Comment by bbondy** [comment]
Re-opening I think it's causing an issue that Brad will post an image for.  I'm leaving committed though s please just do a second PR for it if you can.

**Comment by Sh1d0w** [comment]
Sure. Just let me know what is the issue.

**Comment by bradleyrichter** [comment]
suggestions should not open when clicking on the new tab:

![weird new tab click behavior](https://cloud.githubusercontent.com/assets/13509546/19488694/dbd1fa9a-951c-11e6-943b-1357b9f01cc6.gif)

**Comment by Sh1d0w** [comment]
@bradleyrichter I can't reproduce this on latest master. Can you please provide STR? Have you typed anything in the url bar and then deleted?

**Comment by Sh1d0w** [comment]
Here is a video from latest freshly check-outed master: http://webm.land/media/rJCm.webm

**Comment by luixxiul** [comment]
Please check #4900 too, `about:newtab` in History on the autosuggest list.

**Comment by bbondy** [comment]
I could reproduce earlier today but I am no longer able to. Maybe it was fixed as part of something else since then.  If someone reproduces please re-open.
