### ISSUE TITLE
On Payments tab of Preferences, clicking 'Create Wallet' button crashes Brave

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#3236]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In Preferences, on the Payments tab, clicking the 'Create Wallet' button crashes Brave (on Ubuntu 14.04 Linux).
**Expected behavior:**
Clicking the 'Create Wallet' button should not crash the browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04 Linux

- Brave Version:
Recent checkout of ledger-delta-rebase (commit 613eef94e350390334343ac076142a3ebe01d643)

- Steps to reproduce:
(See also animated GIF below)
    1. Open Preferences (navigate to `about:preferences` in URL bar or via hamburger menu)
    2. Click the Payments tab on left hand menu
    3. Click the "Enable" switch to the right of the "Brave Payments Beta" heading in the content pane.
    4. Click the "Create Wallet" button in the center of the Payments table in the content pane.

- Screenshot if needed:
![brave_payments_create_wallet_crash_final](https://cloud.githubusercontent.com/assets/6969859/17754638/57a4a4d8-648a-11e6-9c5c-bf5b09e20293.gif)

- Error in console: `Error: missing personaId`

- Full trace below:
```
starting up ledger publisher integration
An uncaught exception occurred in the main process Uncaught Exception:
Error: missing personaId
    at new Client (/home/willy/projs/git/3rd/brave/browser-laptop/node_modules/ledger-client/index.js:15:25)
    at Client (/home/willy/projs/git/3rd/brave/browser-laptop/node_modules/ledger-client/index.js:11:41)
    at fs.access (/home/willy/projs/git/3rd/brave/browser-laptop/app/ledger.js:160:40)
    at FSReqWrap.oncomplete (fs.js:123:15)
/home/willy/projs/git/3rd/brave/browser-laptop/node_modules/node-anonize2-relic-emscripten/anonize2.js:1
(function (exports, require, module, __filename, __dirname, process, global) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NOD

Error: missing personaId
    at new Client (/home/willy/projs/git/3rd/brave/browser-laptop/node_modules/ledger-client/index.js:15:25)
    at Client (/home/willy/projs/git/3rd/brave/browser-laptop/node_modules/ledger-client/index.js:11:41)
    at fs.access (/home/willy/projs/git/3rd/brave/browser-laptop/app/ledger.js:160:40)
    at FSReqWrap.oncomplete (fs.js:123:15)
process exited with code 7
npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/home/willy/.nvm/versions/node/v6.1.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! brave@0.11.5 start: `node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the brave@0.11.5 start script 'node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/willy/projs/git/3rd/brave/browser-laptop/npm-debug.log
```

**Comment by willy-b** [comment]
(I'm working on this unless someone else is already on it)

**Comment by diracdeltas** [comment]
thanks, cc @mrose17 since this is erroring in the ledger-client package.

**Comment by diracdeltas** [comment]
@willy-b btw, i did a force-push to ledger-delta-rebase recently, so you should pull that first. i would also try deleting node-modules/ledger*, then npm install to get the latest ledger packages.

**Comment by mrose17** [comment]
@willy-b - thanks for reporting this. can you check one thing? make sure you have the current version of `ledger-client` (do an `npm install` after deleting `node_modules/ledger-client`). i believe that the current version doesn't have this issue...

and please report back!

thanks!

ps: i've been waiting to get closer to the beta release do use semantic versioning rather than URL, and we are getting very close to that point... sorry!

**Comment by mrose17** [comment]
just as an fyi: after a force-push i remove both the `node_modules` and `~/.electron` directories to ensure i'm getting the latest, freshest, most tasty version of everything (-;

**Comment by willy-b** [comment]
Thanks @mrose17, @diracdeltas!
This bug is gone after force-pulling the latest, clearing `node_modules` and `~/.electron` , and doing a fresh `npm install`.

**Comment by mrose17** [comment]
@willy-b - sorry about the confusion and many thanks for the follow-up!
