### ISSUE TITLE
macOS Sierra `kq_init` warnings

### ISSUE THREAD

**Issue by paanvaannd** [brave/browser-laptop#3237]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Upon startup of browser after running `npm run watch` and `npm start`, the following line is repeated 8 times:

> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

followed by:

> [43758:0817/180804:INFO:CONSOLE(93)] "Set up extension URL router.", source: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/extension-router.js (93)

> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

> 2016-08-17 18:08:37.947 Brave Helper[43762:848618] Couldn't set selectedTextBackgroundColor from default ()

> [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

> [43758:0817/180840:WARNING:session_storage_database.cc(381)] Failed to open leveldb in /Users/USERNAME/Library/Application Support/brave/Session Storage, error: IO error: /Users/USERNAME/Library/Application Support/brave/Session Storage/LOCK: No further details. (ChromeMethodBFE: 15::LockFile::1)
2016-08-17 18:09:00.751 Brave Helper[43776:849255] Couldn't set selectedTextBackgroundColor from default ()`

(note: generic USERNAME subbed in for my account username)

Furthermore, after every new URL opened, the 1st error reported (the `kq_init` line) is repeated, but not when navigating within a site (i.e. clicking on an NYTimes article). So, opening a new tab throws out the `kq_init` warning as does navigating to NYTimes within that tab, but the error is not thrown out when navigating within NYTimes to view an article and whatnot. The Back and Forward commands have no bearing on the behavior (the warning only gets thrown out when navigating between parent URLs, including if one goes to another parent URL using the Back or Forward commands).

**Expected behavior:** That these errors not be thrown (I have no clue what any of them mean).

- Platform: macOS Sierra Beta 5

- Brave Version: 0.11.5

- Steps to reproduce:
    1. `npm run watch`
    2. `npm start`
    3. monitor terminal output on `npm start` session

**Comment by neeklamy** [comment]
From this discussion regarding tmux, [“kq_init: detected broken kqueue”](https://github.com/tmux/tmux/issues/475), it’s not nothing to worry about, just an error message:

> kqueue is broken on OS X, but we accidentally stopped turning it off in 2.2.

**Comment by neeklamy** [comment]
From this discussion regarding tmux, [“kq_init: detected broken kqueue”](https://github.com/tmux/tmux/issues/475), it’s nothing to worry about, just an error message:

> kqueue is broken on OS X, but we accidentally stopped turning it off in 2.2.

**Comment by paanvaannd** [comment]
After reading through the tmux and Chromium issues noted in the linked issue above, it seems like this is a 3rd-party issue and not Brave's issue. Would this be a correct assessment? If so, I'll close this issue since it would not be a Brave issue.
