### ISSUE TITLE
Videos not played on Time.com unless shields are down.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3239]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Video on time.com website doesn't play until shields are turned off at page level. Doesn't play video even if the following settings is used
Shield on, Allow Ads/Tracker, Allow all Cookie, FP disabled

**Expected behavior:**
Should play the video
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Visit [time.com](http://time.com)
  2. Enable all settings in shields - Video doesn't play
  3. Disable all options but keep shields on - Video still doesn't play
  4. Disable shields at page level - Video plays
- Screenshot if needed:
  Script allowed to play video content gets blocked when shields turned on at page level. 
  ![image](https://cloud.githubusercontent.com/assets/17010094/17766923/745d610a-6525-11e6-80af-55e7cf09d2b6.png)

Shields up
![image](https://cloud.githubusercontent.com/assets/17010094/17767003/04f97ce4-6526-11e6-9bc0-e3a9677b58f7.png)

Shields down
![image](https://cloud.githubusercontent.com/assets/17010094/17767031/29c0e6a2-6526-11e6-82fa-e9fd983bfbc5.png)
- Any related issues:

**Comment by srirambv** [comment]
Flash placeholder not shown when the page loads video content automatically allows flash content to run. Chrome detects as a flash object and blocks on the same page.

cc: @diracdeltas

**Comment by diracdeltas** [comment]
> Flash placeholder not shown when the page loads video content automatically allows flash content to run. Chrome detects as a flash object and blocks on the same page.

this is because the videos are HTML5 in Brave, not Flash

**Comment by luixxiul** [comment]
I'm going to close this issue in favor of https://community.brave.com/t/tracking-time-com/10952
