### ISSUE TITLE
Enabling HTTPS everywhere breaks pagination scripts to work on Vodafone site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3240]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling HTTPS everywhere breaks pagination scripts to work on Vodafone site

**Expected behavior:**
Should allow scripts which loads paginated content to be displayed

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.5

- Steps to reproduce:
    1. Visit this Vodafone[ link](http://shop.vodafone.ie/shop/phonesAndPlans/phonesAndPlansHome.jsp?subPage=phones&planFilter=onAccount)
    2. Enable HTTPS Everywhere on the site
    3. Scroll down the page only lists the on page load content
    4. Disable HTTPS Everywhere, Page reloads and allows script to run the paginated content 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/17770466/caeff11c-6535-11e6-97f8-eaa066e80648.png)

![ezgif-1615756205](https://cloud.githubusercontent.com/assets/17010094/17770567/670dcfa6-6536-11e6-958d-d16523b06a0d.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Pushed an upstream PR to fix this: https://github.com/EFForg/https-everywhere/issues/6440
