### ISSUE TITLE
Uncaught error for URLBarSuggestion  in Dev console.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3242]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Uncaught error for URLBarSuggestion  in Dev console.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  WIndows 10 x64
- Brave Version:
  0.11.5
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17776535/eac04b08-6554-11e6-8a3a-b67264113419.png)
- Any related issues:

**Comment by luixxiul** [comment]
Fixed?

**Comment by bsclifton** [comment]
I fixed something similar to this; I'm not positive it's the same thing though:
https://github.com/brave/browser-laptop/pull/5570/files

**Comment by bbondy** [comment]
I'm pretty sure I fixed it in the past, so closing :)
