### ISSUE TITLE
Include Search with search engine list in the right click context menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3243]
## Test plan

https://github.com/brave/browser-laptop/pull/12613#issue-287901696

----

Include Search with (available search engines from the pref menu) in the right click context menu when a user select a text.

**Comment by Aeyoun** [comment]
This is an important feature for CJK and Arabic languages. (Harder to input text than users in latin script regions.)

**Comment by bsclifton** [comment]
@srirambv do you think this is closed? We do have a `Search for "term here"` in our right click menu... but it doesn't list the names of search engines (or have a submenu item which lets you choose which)

**Comment by srirambv** [comment]
It would be great if we can provide the list of search engine in a submenu (with just the favicons) but for now `Search with "term"` is fine. That would help user to search terms apart from the default search engine that is set.

**Comment by srirambv** [comment]
Adding to contributor backlog for adding the submenu with search engine list which should exclude default search engine

**Comment by sergiorojasa** [comment]
I would work on this.

**Comment by sergiorojasa** [comment]
I would work on this issue.

**Comment by sergiorojasa** [comment]
@srirambv I would like to work on this feature

**Comment by srirambv** [comment]
@sergiorojasa  Sure you can create a PR for it and submit for review

**Comment by sergiorojasa** [comment]
@srirambv Is there a specific amount of search engine that should be included?

**Comment by sergiorojasa** [comment]
I'm was only able to get the search engine name to display and not the favicons

**Comment by srirambv** [comment]
>I'm was only able to get the search engine name to display and not the favicons

cc: @bsclifton on that

I think a few of the top search engines liek Google, DDG, Wikipedia, Bing, Yahoo should be fine. @bradleyrichter thoughts?
