### ISSUE TITLE
Ctrl+Tab, then scrolling often results in zooming

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3244]
### Description

When having multiple tabs open, pressing Ctrl+Tab to shift tabs and then scrolling using the touchpad results in the page being zoomed out.

I think this is happening because Brave gets the news that Ctrl has been released before it starts receiving touchpad scrolling input.

### Steps to Reproduce

https://github.com/brave/browser-laptop/issues/3244#issuecomment-324180355

1. Open Brave
2. Open a tab
3. Load http://www.onemilescroll.com/
3. Open another tab
4. Load https://www.wikipedia.org/
4. Switch back to the http://www.onemilescroll.com tab
5. Using either a mouse/trackpad, swipe so the page starts scrolling
6. While the page is scrolling, press Control + TAB to switch over to https://www.wikipedia.org/

Another STR:

  1. Go to https://reddit.com/r/askreddit
  2. Open 10 links in new tabs.
  3. Wait for the tabs to finish loading.
  2. Press `Ctrl+Tab` to shift to a new tab.
  3. As soon as the tab is switched, but after you have released the Ctrl key, scroll down the page with the touchpad or mouse wheel.

**Actual result:**

Scrolling happens, eventually

**Expected result:**

Actual: Scrolling happens, but the page is often zoomed out to less than 100%.

**Reproduces how often:**

### Brave Version

**about:brave info:**

macOS 0.11.5

**Reproducible on current live release:**

**Comment by srirambv** [comment]
Confirmed on Windows too. Zoom level changes immediately when the Ctrl button is pressed after scroll done with touchpad. Happens on a single tab no need to open multiple tabs. Not happening with mouse wheel though.

**Comment by gulkily** [comment]
Just to be clear, Ctrl + scrolling is *supposed* to zoom. Or, at least that's how it works in some other browsers.

But if it happens without any modifier keys pressed, that is a bug.

**Comment by PerishableDave** [comment]
This also happens if you scroll first then follow up quickly by switching tabs.

**Comment by tylerl0706** [comment]
+1 I use Ctrl+Tab & Ctrl+Shift+Tab to navigate through tabs and it's frustrating when my screen zooms in when it shouldn't

**Comment by stshank** [comment]
I have this problem often, too.

**Comment by srirambv** [comment]
Adding a milestone

**Comment by kjozwiak** [comment]
+1 from the community via the `#discuss-bugs` channel under Discord. I managed to reproduce the issue while investigating using the following STR:

* Open Brave
* Open a tab and load http://www.onemilescroll.com/
* Open a tab and load https://www.wikipedia.org/
* Switch back to the http://www.onemilescroll.com tab
* Using either a mouse/trackpad, swipe so the page starts scrolling
* While the page is scrolling, press `Control + TAB` to switch over to https://www.wikipedia.org/

**Comment by fizzyfrosty** [comment]
I want to comment that the Zooming bug actually happens in reverse order: Scrolling, then ctrl+tab. I have documented steps to reproduce this (a more noticeable bug), which might help debug the case a bit more:

https://community.brave.com/t/scrolling-with-touchpad-on-macos-and-immediately-ctrl-tabbing-causes-page-to-zoom-in-out/9882

**Comment by fizzyfrosty** [comment]
Any chance this gets fixed sooner? This bug is super-evident on macs since macOS has scroll momentum on trackpad, so almost every Mac user will get resizing issues when scrolling and changing tabs.

**Comment by Brunty** [comment]
Been using bravo for a couple of days and this one's really noticeable with the scroll momentum on macOS as @fizzyfrosty mentioned.

**Comment by tylerl0706** [comment]
Just wanted to comment that this is still an issue and is super frustrating.

**Comment by kanedaniel** [comment]
Loving Brave, but this bug still exists and is incredibly frustrating.

**Comment by tylerl0706** [comment]
@bsclifton why was this closed? This is still an issue and is really frustrating

**Comment by bsclifton** [comment]
@tylerl0706 there hasn't been any action on this unfortunately- and we're also in the midst of a move to [brave-core](https://github.com/brave/brave-browser) where this might already be fixed

If you have a few minutes, can you please try installing brave-core?
https://github.com/brave/brave-browser/releases

Once installed, it would be useful to know if this bug still occurs. I have a feeling it doesn't

**Comment by tylerl0706** [comment]
That's fine. I tested Brave Core and the problem does not exist there 👍

Not-so-patiently awaiting Brave Core to be more mainstream 😊

Thanks!

**Comment by kjozwiak** [comment]
@tylerl0706 is this still happening with b-c for you? From the sounds of https://github.com/brave/brave-browser/issues/1005, it looks like you're also running the latest b-c. If you have some time, mind quickly checking and seeing if b-c as resolved this issue for you?

**Comment by tylerl0706** [comment]
@kjozwiak yeah this is fixed in Brave Core

**Comment by kjozwiak** [comment]
> @kjozwiak yeah this is fixed in Brave Core

Awesome, thanks @tylerl0706! 👍
