### ISSUE TITLE
ledger needs tests

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3249]
@mrose17 please add tests for app/ledger.js; i or someone else can add the ones for the prefs panel

**Comment by diracdeltas** [comment]
i'm tests for the ledger payments tab, @mrose17 to add tests for app/ledger.js

**Comment by mrose17** [comment]
@diracdeltas - sadly, there's more code that has to be written for the ledger, per se, and its backend, and that has to come first...

**Comment by diracdeltas** [comment]
@mrose17 yup, i figured. but better to have something in for 1.0 even if test coverage is < 100%

**Comment by mrose17** [comment]
indeed!

**Comment by mrose17** [comment]
OBE by #6890 and #6911
