### ISSUE TITLE
Please add keyboard shortcut configs (such as ^U)

### ISSUE THREAD

**Issue by dandart** [brave/browser-laptop#3251]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Ctrl+U didn't pop up the source like other browsers

**Expected behavior:**
I'd like both Ctrl+U to pop up the source and for shortcuts to be configurable, I don't see much about that.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.11.5

- Steps to reproduce:
    1. Press Ctrl+U
    2. Observe nothing happen

- Any related issues:
Not that I know of

Cheers

**Comment by luixxiul** [comment]
Closing this in favor of #1374
