### ISSUE TITLE
ledger notification should have the style of the update bar

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3257]
per https://github.com/brave/browser-laptop/issues/2407

Alert:
Hello! Your Brave Payments account is waiting for a fresh deposit.

Buttons:
[Later] [ Add funds... ]

Trigger:
1 day, and 5 days after a failed payment

____________________
Alert:
Hello! Are you ready to support the sites you use most?

Buttons:
[Not yet ]  [ Sure, I'll try... ]

Trigger:
10 days after first run of Brave, if user has not yet enabled BP.
_____________________
Alert:
Hello! Thanks for supporting your favorite websites! Your contribution of $15.00 was processed! 

Buttons:
[Ok]

Trigger:
Immediately, upon ledger confirmation of contribution processing.

visual spec:

![image](https://cloud.githubusercontent.com/assets/13509546/18334070/680effc6-7529-11e6-9273-f27fecc52423.png)

**Comment by diracdeltas** [comment]
@ayumi there is a notification bar option i added, `updateStyle`, which is supposed to indicate that the NotificationBar should be styled like an UpdateBar. currently this option does nothing

**Comment by ayumi** [comment]
I implemented custom notification styling in https://github.com/brave/browser-laptop/pull/3856.
To finish this :gift: we need to add the 3 ledger notifications.

**Comment by mrose17** [comment]
@ayumi - who needs to do the additions? is this a design thing, a coding thing, a policy thing? thanks!

**Comment by ayumi** [comment]
Just a coding thing now – adding the triggers and alerts.

**Comment by mrose17** [comment]
_excellent!_

**Comment by bbondy** [comment]
Anything else need to block 0.12.2 for this?

**Comment by ayumi** [comment]
I'm stuck on how to test the "thanks for your contribution" notification – I'm unable to trigger a ledger payment on demand. @mrose17 is there a way to try that?

Here it is implemented pending verification: https://github.com/brave/browser-laptop/compare/master...feature/ledger-notifications-more

**Comment by mrose17** [comment]
sadly, there isn't a way to force the ledger to trigger a contribution on demand, other than to edit `ledger-state*.json` and watch it go. what is the PR for this? i can take a look in about 30m. thanks!

**Comment by ayumi** [comment]
@mrose17 PR #4140
