### ISSUE TITLE
Closed frames shouldn't include newtab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3258]
It's a bit strange to see new tab showing up in the closed tab menu button a lot.  Maybe only navigatable `isNavigatableAboutPage` pages should be included when adding to closedFrames.

Steps to reproduce:
1) Open a new tab
2) Close the tab (which is still on the new tab page)
3. Check the history menu, it shows Recently Closed as New tab

cc @bsclifton

**Comment by bsclifton** [comment]
That should be an easy fix :smile: It's worth noting this is distinctly different from https://github.com/brave/browser-laptop/issues/2856 (which gets the history from Chromium via Electron's NavigationController)

**Comment by bsclifton** [comment]
This should be fixed- self assigning so I can review
