### ISSUE TITLE
Performance Improvement : Acid3

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3263]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When running the Acid3 test, a hitch occurs while rendering and a piece of text remains when it should be removed.

The text reads "YOU SHOULD NOT SEE THIS AT ALL".

**Expected behavior:**
Other browsers, Chrome, Firefox perform perfectly. We should too.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X.
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. With the browser you would like to test, visit http://acid3.acidtests.org/
  2. Run the test and compare versus the sample image. 
  3. The images should match and the score should be 100/100.
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1530699/19027369/bcb8d988-88fd-11e6-86eb-1f484219cfe8.png)
- Any related issues:

**Comment by Liunkae** [comment]
+1 from #6509.

**Comment by bsclifton** [comment]
Verified this is fixed
