### ISSUE TITLE
Cross-window JS object access via window.opener doesn't work in brave/electron

### ISSUE THREAD

**Issue by sltam** [brave/browser-laptop#3270]
This is indeed a [brave/electron](https://github.com/brave/browser) issue but that project has no issue tracker, so here I am.

I am referred to here from https://github.com/electron/electron/issues/4175 where @bridiver suggests that brave/electron has an additional patch over atom/electron that allows guest view to guest view synchronous communication. I tested but can't get it to work. Anything have I done wrong?

This is what I did in Brave browser:

first.html:
```
click here
<script>
document.onclick = () => window.open('second.html')
</script>

```
second.html:
```
<script>
try {
    document.write(window.opener.document.body.innerHTML.replace(/</g, '&lt;'))
} catch (e) {
    document.write(e)
}
</script>

```

This is how I did it with Brave's electron:

main.js:
```
const { BrowserWindow, app } = require('electron')
app.on('ready', () => new BrowserWindow().loadURL(`file://${__dirname}/first.html`))
```

`$ Brave.app/Contents/MacOS/Brave .`

I am getting `TypeError: Cannot read property 'body' of undefined` in the popup window.

**Comment by sltam** [comment]
If you suspect `file://` might have stricter permissions, so did I. I put the files at `http://localhost/{first,second}.html` and `loadURL('http://locahost/first.html')` and got the same error.

**Comment by bridiver** [comment]
window.opener support in Brave is only for webviews/guest views, not for the main windows. It would probably be possible to support using some of the same mechanisms, but we just didn't have a need for it and it doesn't work well with node enabled windows because of node environment memory leak issues. At the moment we don't really have the resources to support brave/electron issues that are not bugs in the Brave browser, but if you can replicate the issue in the browser please let us know. Thanks!

**Comment by sltam** [comment]
> window.opener support in Brave is only for webviews/guest views
I don't understand. Can you explain what situation it actually works?

**Comment by bridiver** [comment]
http://electron.atom.io/docs/api/web-view-tag/ with node disabled

**Comment by sltam** [comment]
I see. This is probably something that will work for me. I noticed  if I changed `first.html` to:
```
document.onclick = () => window.open('second.html', '_blank', 'width=800')
```
Brave browser pops up a new window that can still grab JS objects in the previous window. Now there are two new electron `BrowserWindow` and two `webview`s, right? Can you show me the code in `brave/browser-laptop` that deals with this so that I can learn from it? Thanks!

**Comment by bridiver** [comment]
most of the relevant code is https://github.com/brave/browser-laptop/blob/master/js/components/frame.js but it will only work if you create a webview inside the browser window

**Comment by bridiver** [comment]
the `guestInstanceId` is critical to making it work correctly and must be added to the webview element

**Comment by sltam** [comment]
@bridiver, thanks! Is it something like by setting the same `data-guest-instance-id` attribute to new webviews (`updateWebview` in `js/components/frame.js`) `lib/browser/guest-view-manager.js` can now put all these webviews into the same process so they can grab the JS objects of each other?

One question: how does the newly-created webview know who its parentFrame is? The `parentFrameKey` in `frameOpts` is not passed anywhere to the webview in `updateWebview`.

**Comment by bridiver** [comment]
window.open creates the new webContents and passes the guestInstanceId to the `new-window` event so you can attach a `webview` to it. `parentFrameKey` is an internal brave key and isn't required. The logic for setting the url is also important on windows. It works fine on the mac regardless of how and when you set the url, but it will crash on windows in some circumstances if you try to set the url and guestInstanceId

**Comment by sltam** [comment]
Thanks @bridiver, I got it working. Dropping the code here just in case someone needs the same in future.

frame.html
```html
<style>webview { height: 100%; }</style>                                                                                                                                                                                                                                 
<webview id="webview"></webview>
<script>
var webview = document.getElementById('webview');
webview.addEventListener('new-window', (e) => {
    let guestInstanceId = e.options && e.options.webPreferences && e.options.webPreferences.guestInstanceId
    e.preventDefault()
    require('electron').ipcRenderer.send('new-window', guestInstanceId)
  }
);
</script>
```

main.js
```javascript
const { BrowserWindow, app, ipcMain } = require('electron');

app.on('ready', () => {
  const win = new BrowserWindow()
  win.loadURL(`file://${__dirname}/frame.html`)
  win.webContents.once('did-finish-load', () => {
    win.webContents.executeJavaScript(`webview.setAttribute('src', 'first.html')`)
  })  
})

ipcMain.on('new-window', (e, guestInstanceId) => {
  const win = new BrowserWindow()
  win.loadURL(`file://${__dirname}/frame.html`)
  win.webContents.once('did-finish-load', () => {
    win.webContents.executeJavaScript(`webview.setAttribute('data-guest-instance-id', '${guestInstanceId}')`)
  })  
})
```

first.html
```html
click here
<script>
document.onclick = () => window.open('second.html', '_blank', 'width=800')
</script>
```

second.html
```html
<script>
try {
    document.write(window.opener.document.body.innerHTML.replace(/</g, '&lt;'))
} catch (e) {
    document.write(e)
}
</script>
```

**Comment by sltam** [comment]
@bridiver Turns out the above solution does not allow the webview to communicate with the outside world at all.
 1. It can't have `nodeIntegration`, so it can't access anything inside `require('electron')`.
 2. I can't put a `preload` attribute to `<webview>` (so that I can `window.electron = require('electron')` inside the preload script) otherwise all `guestInstanceId` returned are `1`.
 3. I can't call `parent.postMessage` for some unknown reasons (perhaps `atom/electron` never supported this case.
Vice versa.

I perfectly understand `browser-laptop` never needs this feature, but do you have any quick idea how to make any sort of cross-webview communication work?

**Comment by bridiver** [comment]
we added several capabilities for this. You can use the contentWindow/postMessage, chrome.runtime.sendMessage (with an extension background page) and we also added chrome.ipc which is compatible with normal electron ipc

**Comment by bridiver** [comment]
preload script functionality is replaced by extension content scripts. chrome.ipc will only work in content scripts and will not work in the page

**Comment by davidrevmakx** [comment]
Tried using this functionality - the parent page loaded when we had preload attribute set. No doc on how to inject a content script on electron? I just want to load a bunch of JS with IPC.  Any example on adding a contentscript to a webview or browserwindow?
