### ISSUE TITLE
Orange browser buttons – Make hover state nicer

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#3274]
**Describe the issue you encountered:**
In Preferences, hovering over orange buttons only changes the text to black which is a little lacking.

**Expected behavior:**
Hovering over orange buttons should look nicer and be more prominent.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS 10.11.6 (15G31)

- Brave Version:
0.11.5 built from `505914`

- Steps to reproduce:
    1. Open Preferences, go to Security
    2. Mouse over Clear Browsing Data Now... button

- Screenshot if needed:
<img width="477" alt="screen shot 2016-08-19 at 22 25 04" src="https://cloud.githubusercontent.com/assets/521861/17829205/7d15cc5a-665c-11e6-9ae5-db31ad55cb50.png">

- Any related issues:

**Comment by bbondy** [comment]
I think we don't use it in general to make things feel more native, HTML pages will have this, but native controls don't usually.  It's arguable though and maybe we should treat about pages different from the chrome.

/cc @bradleyrichter for decisions around here.

**Comment by bradleyrichter** [comment]
I think we need a nicer button hover state. (currently only the text color turns black which is not a good solution.

I don't see a cursor change in the other browsers so I tend to agree with @bbondy 's comment. It feels more app-like than site-like.

**Comment by ayumi** [comment]
I think I understand the app-like UI behavior.

I updated the issue to @bradleyrichter's idea on improving button hover state.

**Comment by ayumi** [comment]
I think the current orange button style looks satisfactory, so perhaps this task should be "make orange browser buttons consistent"

<img width="164" alt="screen shot 2016-09-21 at 21 19 50" src="https://cloud.githubusercontent.com/assets/521861/18736981/3b0fe346-8041-11e6-9f10-dbd0565fede4.png">

**Comment by ayumi** [comment]
Actually the buttons I'd been concerned about look fixed :gift:

**Comment by bbondy** [comment]
Please remove the milestone marker when closing without a commit, thanks!
