### ISSUE TITLE
Review scores not loading on Booking.com 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3276]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Review scores not loading on Booking.com when mouseover the rating.

**Expected behavior:**
Should display the review scores when mouseover the rating 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Visit booking.com (ex: [this](https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggJCAlhYSDNiBW5vcmVmaGmIAQGYATG4AQzIAQzYAQHoAQH4AQKSAgF5qAID;sid=c384593861b36f0f6db8c3f2a1168ef9;dcid=4;checkin_month=8&checkin_monthday=21&checkin_year=2016&checkout_month=8&checkout_monthday=31&checkout_year=2016&class_interval=1&dest_id=4&dest_type=airport&dtdisc=0&group_adults=2&group_children=0&hlrd=0&hyb_red=0&inac=0&label_click=undef&nha_red=0&no_rooms=1&offset=0&postcard=0&redirected_from_city=0&redirected_from_landmark=0&redirected_from_region=0&review_score_group=empty&room1=A%2CA&sb_price_type=total&sb_travel_purpose=business&score_min=0&src=index&src_elem=sb&ss=London%20Heathrow%20Airport%2C%20London%2C%20Greater%20London%2C%20United%20Kingdom&ss_all=0&ss_raw=lond&ssb=empty&sshis=0&)) 
  2. Mouse over any of the listed ratings
  3. Should show a review score for the item on which the mouse is hovered.
     Shields off at page level.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17830264/f9c7834e-66be-11e6-959e-2a882ec2d6ee.png)

![image](https://cloud.githubusercontent.com/assets/17010094/17830239/20ea53da-66be-11e6-97c7-24e3ebb698b5.png)

Inner HTML not loaded at the div element 
![image](https://cloud.githubusercontent.com/assets/17010094/17830231/e0c8419a-66bd-11e6-81d8-9eac5893f307.png)
- Any related issues:

**Comment by luixxiul** [comment]
The issue has been fixed.
