### ISSUE TITLE
Enabling Ad/Tracker fails to load Argos.co.uk

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3277]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling Ad/Tracker in page level fails to load the site http://www.argos.co.uk/static/Home.htm

**Expected behavior:**
Should load the site
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Enable Ad/Tracker in shields and visit [Argos](http://www.argos.co.uk/static/Home.htm)
  2. Website is not loaded
  3. Disable Ad/Tracker at page level, Website loads.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/17830527/f7d78370-66c5-11e6-9546-9c2078c237b7.png)

![image](https://cloud.githubusercontent.com/assets/17010094/17830520/d45e3326-66c5-11e6-85ae-4ae91149c647.png)
- Any related issues:

**Comment by luixxiul** [comment]
The issue seems to have been fixed.
