### ISSUE TITLE
As I can see, modify or add plugins to the browser?

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3279]
**Did you search for similar issues before submitting this one?**
No
**Describe the issue you encountered:**
I do not know where to check which plugins are in the browser and also do not think a way to add new plugins.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 x64
- Brave Version:
0.11.5

**Comment by luixxiul** [comment]
Duping to #253

@EuNlope, would you please make sure to search for similar issues before submitting an issue? Almost all of the issue which you opened are duping.

**Comment by luixxiul** [comment]
Also you can add reactions like "+1" to the issues.

**Comment by EuNlope** [comment]
OK, sorry.
