### ISSUE TITLE
Ideas for additional UI elements (full status bar, side bar, add-on bar)

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#328]
Since there was already the suggestion for a bookmarks toolbar - what would be nice too: an optional full status bar, an optional side bar and an optional add-on bar.

That is anyway a large problem of Chromium - Chromium devs do not understand that an optional side bar can be of great use, same like an optional bar for add-on icons, more place for them ;)

Additionally an option to autohide bars/make them visible on hovering would be a cool feature too in combination with that bar suggestions.

**Comment by bsclifton** [comment]
Closing as stale since there haven't been any additional comments
