### ISSUE TITLE
Videos stop playing when About Brave window opens up

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3280]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Video freezes up when About Brave window is opened from hamburger menu or file menu. Happens on all videos playing on any site. Audio continues to play only the video freezes up

**Expected behavior:**
Video should continue to play 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64, OpenSuse 42.1 x64
- Brave Version:
  0.11.4, 0.11.5 (Must be happening in all versions)
- Steps to reproduce:
  1. Open any video on anysite
  2. Open About Brave from HB menu/File Menu
  3. Video freezes up but audio continues to play
- Screenshot if needed:
  ![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17010094/17831088/e040f1e4-66d7-11e6-912c-ca889037a5a8.gif)
- Any related issues:

**Comment by bbondy** [comment]
The about dialog was replaced with an about:brave page in 0.12.9 so I'm closing this.
