### ISSUE TITLE
Reduced specificity of select class in css

### ISSUE THREAD

**Issue by rohanthacker** [brave/browser-laptop#3282]
**Did you search for similar issues before submitting this one?**
 Yes
**Describe the issue you encountered:**
The style of select element used is deeply nested under settings

**Expected behavior:**
Reduce code duplications by assigning classes, similar to the pattern used in other elements, For Eg :  button. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All 
- Brave Version:
11.3
- Steps to reproduce:
    1. #2894 , Required Dropdown for Bookmarks
    2.  Select Element used in Brave Menu 
<img width="476" alt="screen shot 2016-08-21 at 3 29 45 am" src="https://cloud.githubusercontent.com/assets/1190324/17834105/98eadde6-674f-11e6-83dd-30847d72523b.png">
    
3.Select Element Used in Settings, similar to bookmarks but nested under settings classes.
<img width="389" alt="screen shot 2016-08-21 at 3 29 56 am" src="https://cloud.githubusercontent.com/assets/1190324/17834106/98edc236-674f-11e6-8802-cc30a62ae336.png">

**Comment by bradleyrichter** [comment]
the brave menu should ideally use the in-page style for popup menus.
