### ISSUE TITLE
Non-script version of DuckDuckGo when blocking scripts is not loaded from context menu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3285]
**Describe the issue you encountered:** Non-script version of DuckDuckGo when blocking scripts is not loaded from context menu

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.6 Beta1

- Steps to reproduce:
    1. Select duckduckgo as default search engine
    2. Make "Block Scripts" enabled on about;preferences
    3. Search for some strings from context menu

- Screenshot if needed:

- Any related issues: #3283 #3189

**Comment by bbondy** [comment]
cc @darkdh
