### ISSUE TITLE
Filesystem API cookie not blocked

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3286]
**Describe the issue you encountered:**
Though I disable 3p cookies on https://jsfiddle.net/7ke9r14a/9/, it seems that filesystem API cookie is not blocked.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.6 Beta1

- Steps to reproduce:
    1. Navigate to https://jsfiddle.net/7ke9r14a/9/

- Screenshot if needed:

- Any related issues: #3283 

Setting a milestone for now /cc: @diracdeltas

**Comment by diracdeltas** [comment]
This depends on https://github.com/brave/electron/pull/42. @bridiver or @bbondy please merge before release if it looks okay.

**Comment by bbondy** [comment]
Closing since we'll have this in the next beta build.
