### ISSUE TITLE
Clear "Recently Closed" when clearing history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3287]
**Describe the issue you encountered:** "Recently Closed" is not cleared while "browsing history" of Private Data option is enabled.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.6 Beta1

- Steps to reproduce:
    1. Navigate to some pages
    2. Open about:preferences#security
    3. Enable the option "Browsing history"
    4. Restart the browser

- Screenshot if needed:

- Any related issues: #3283

**Comment by luixxiul** [comment]
In fact you cannot clear them except by removing either the brave folder or session-store-1 file.

**Comment by bbondy** [comment]
When testing:
Please test both the Browsing history option in preferences and the one from the history menu

**Comment by bbondy** [comment]
@bradleyrichter why did you re-open this? When things are fixed on master we should close them as usual.

**Comment by bradleyrichter** [comment]
accidental click? I have no idea...

**Comment by bbondy** [comment]
ok np, thanks! :D
