### ISSUE TITLE
Search suggestion should not list when engine go key is typed.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3294]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Typing yt and then space automatically shows search suggestion without user even entering a single character. 
(Specific to Youtube Search Engine )

**Expected behavior:**
Should show suggestion only when user enters a character
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 Dev Beta 1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:
  #3235

**Comment by bbondy** [comment]
could you write steps to reproduce please? Also how bad is this behaviour? I'm tempted to remove this from 0.11.6.

Do I need a history entry with "yt " in the title? If so can you recommend a site t get that?

**Comment by jkup** [comment]
I'm able to reproduce this but I'm not sure what the desired behavior is. I didn't need a yt history entry but what's weird is that I don't think they are Youtube search results, I think they are regular search results for phrases that start with "yt".

What should we be doing here?

Screenshots attached.
<img width="940" alt="screen shot 2016-08-23 at 8 20 10 pm" src="https://cloud.githubusercontent.com/assets/490294/17917245/5cdd4d9e-696f-11e6-88c7-6c607e6405ab.png">

**Comment by bridiver** [comment]
is there some reason why the suggestions shouldn't be active? I tend to agree with @jkup that these could be legitimate search queries

**Comment by bridiver** [comment]
I think these should probably be activated by a different method. Maybe tab?

**Comment by bbondy** [comment]
removing from 0.11.6

**Comment by srirambv** [comment]
@jkup @bridiver  Search suggestion should only come up when a user enters a character. I am assuming the search result is showing up automatically since Youtube uses two characters as the go keyword while all others only use one character.  Entering the second character could be triggering the auto search suggestions

**Comment by bridiver** [comment]
I guess what seems odd to me is that searching for "a big dog" or @jkup's example of "yt bikes" would search amazon instead of the default search engine. It's a separate issue, but if we had a different trigger it would probably be easier to decide when to show the suggestions

**Comment by darkdh** [comment]
'a' is actually an amazon search shortcut btw. So it will search amazon for "big dog".

**Comment by bridiver** [comment]
right, that's my point. Seems like we should do a better job of differentiating between regular searches and amazon/youtube/etc... searches

**Comment by bbondy** [comment]
I've wanted to do this as well, I think we should have a top level state for `searches` like we have `sites` and each search would have the search text, the engine used, the partition, lastAccessedTime, and instead of calling `appActions.addSite` we'd call a new `appActions.addSearch`

**Comment by bridiver** [comment]
we could convert the search engine go keys from 'a' -> '/a'
I think there's a lot of other cool things we could do with slash commands

**Comment by bsclifton** [comment]
This was closed when we added a : in front of the search go keys 😄  (not too long after this was filed)

**Comment by DeviatedMind** [comment]
#790 #824 #3053 #3294 #4210
