### ISSUE TITLE
Javascript prompt boxes not showing

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#3295]
No javascript prompt boxes are showing for me.
Replicate issue using demos on this page: http://www.w3schools.com/js/js_popup.asp
Alert Box demo and Confirm Box demo show a popup box as expected but Prompt Box demo does not.

Ubuntu 16.04 / Brave 0.11.5
Possibly related issues: #94 #1621 #2677

**Comment by CliqueBait** [comment]
Thanks @bsclifton.

Additional Info
I get the expected behaviour using
Chromium Version 51.0.2704.79 Ubuntu 16.04 (64-bit)

**Comment by bsclifton** [comment]
Thanks for reporting @CliqueBait :smile: 

I'm going to close this issue in favor of https://github.com/brave/browser-laptop/issues/94 (which describes a possible patch to fix the issue).
