### ISSUE TITLE
Open file action tries to search for the file in the default search engine 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3296]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Open file action tries to search for the file in the default search engine 

**Expected behavior:**
Should open the file in a new tab depending on the file format support

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, OpenSuse 42.1

- Brave Version:
0.11.6 Dev Beta 1

- Steps to reproduce:
    1. Open any file form local path
    2. File name being searched with the default search engine set in pref
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
![file_handler](https://cloud.githubusercontent.com/assets/1434040/18019523/1ae36f1a-6ba2-11e6-8264-9db498d4e461.gif)

**Comment by bridiver** [comment]
can't replicate on osx. It makes sense to me that it could be broken on win, but linux?

**Comment by bridiver** [comment]
can't replicate on windows either

**Comment by bbondy** [comment]
Could you pass the full path of the file you're opening?

**Comment by bridiver** [comment]
you can see the path in the google search bar. I tried with a gif file on the off-chance that was part of the issue

**Comment by bridiver** [comment]
I can replicate if I start on google.com
