### ISSUE TITLE
Add new tab button mouseover effect not working

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3297]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Add new tab button mouseover effect not working in 0.11.6 

**Expected behavior:**
Add new tab button color should change on mouseover

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, Ubuntu 16.01 x64

- Brave Version:
0.11.6 Dev Beta 1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
@bradleyrichter please advise on what to do

**Comment by bbondy** [comment]
n/m I'll just make it look like before but in a different way

**Comment by bradleyrichter** [comment]
Please leave open? We will be applying hover states to all buttons anyway.

**Comment by bbondy** [comment]
I just made it look like before so fixing this since it's tracked for 0.11.6 and freeze is today. Feel free to post a new bug for your work though.

**Comment by bbondy** [comment]
This is fixed, please post a more generalized bug for your revamp on hover states. Thanks!
