### ISSUE TITLE
feedly 'preview' feature broken by https everywhere even when https everywhere is disabled

### ISSUE THREAD

**Issue by dhgwilliam** [brave/browser-laptop#3298]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
when using feedly, in-tab preview is blocked by https everywhere. so i disabled https everywhere temporarily and reloaded feedly, which still claimed preview was blocked. then i took brave shields completely down and reloaded and feedly still claimed https everywhere was enabled.

**Expected behavior:**
both disabling https everywhere for feedly.com or taking down brave shields entirely should allow preview to work as expected

- Platform (Win7, 8, 10? macOS? Linux distro?):
ubuntu 16.04

- Brave Version:
0.11.5

- Steps to reproduce:
    1. open feedly.com
    2. select article
    3. hit shift+v

**Comment by luixxiul** [comment]
After disabling the HTTPS Everywhere option, please try to reload http://feedly.com. It works for me.

**Comment by dhgwilliam** [comment]
i tried it again and it's still not working. i even completely restarted the browser and feedly still sees https everywhere as enabled.

although i did misidentify my platform. i'm on ubuntu 15.10.

**Comment by diracdeltas** [comment]
@dhgwilliam did you try http://feedly.com not https://feedly.com ?

**Comment by dhgwilliam** [comment]
:expressionless:
