### ISSUE TITLE
Back/forward gesture does not respect system preferences

### ISSUE THREAD

**Issue by apfelchips** [brave/browser-laptop#3299]
**Experienced behavior:**
I've tried to use the forward and backwards swipe gesture in Brave on my Macbook Pro trackpad but it never worked for me. I was quite puzzled because I've looked up if Brave supported macOS trackpad Gestures and read that in theory it should recognize them.

I later discovered that I've diverted from the default two finger "Swipe between pages" option in the Trackpad settings to three fingers.
![screen shot 2016-08-22 at 00 10 25](https://cloud.githubusercontent.com/assets/6919384/17840220/4ba22f9c-6800-11e6-8d1b-9fc4eac82773.png)

When defaulting to the two finger option Brave oddly recognizes three finger back/forward gestures, but not the selected two finger ones, which doesn't really feel right.

**Expected behavior:**
Brave should adhere to the setting made in macOS and use two and three finger swipes according to the selected option, or at least support 3 finger swipes when they are selected in settings.
- Platform:
  macOS 10.11.6
- Brave Version:
  0.11.5
- Steps to reproduce:
  i. select "Swipe with three fingers" in Tackpad Settings->More Gestures->Swipe between pages
  ii. try to use three finger back/forward swipe gesture in brave
- Related Issue:
  Support MacBook trackpad pinch to zoom #1364
  Two-finger swipe gesture on macOS should have visual indicator #2477
  Support for three finger tap: "Look up & data detectors"
  Simulated 3 Finger Swipe Gestures not working #6587

**Comment by bradleyrichter** [comment]
adding to this: We need to base the fixes against Safari for swipe nav vs panning.

**Comment by evq** [comment]
:+1:

**Comment by lifeinchords** [comment]
+(a lot).

**Comment by srirambv** [comment]
+1 from user Jim reported swipe gestures not working on  Windows
https://community.brave.com/t/swipe-gesture-not-working/1093

**Comment by lucidNTR** [comment]
also when three finger swipe is set in osx brave still does two finger swipe navigation, which it should not.

**Comment by ENDelt260** [comment]
I commented on a similar issue which was closed, and I was directed here. So, just for completeness:
Brave also doesn't respect the settings for a mouse. I use a magic mouse, and have specifically disabled the "Swipe between pages" feature. But, Brave doesn't respect that I've disabled that. This is especially frustrating when using Trello or Google Spreadsheets, or anything else where scroll horizontally, as I find myself inadvertently navigating through my history.

![image](https://cloud.githubusercontent.com/assets/1824071/24075320/832dcbb0-0bde-11e7-9cc3-b8f45c64f76e.png)

**Comment by Liunkae** [comment]
Tagging as a serious macOS usability issue. Please re-prioritize if needed.

**Comment by thefonso** [comment]
Just adding on here. I'm on MacOS 10.10.5 and Brave 0.13.5 and Brave is not respecting my system preferences of no back/forward swipe between pages gestures.

**Comment by Liunkae** [comment]
Thanks @darkdh! I think macOS users will be much happier after these fixes.

With ecd391c, the conflict with horizontal scrolling is fixed. Brave supports two fingers or none at all, depending on the system preferences. Three finger swipe is still not supported: see follow-up issue #7905.
