### ISSUE TITLE
Google Spreadsheet unable to load

### ISSUE THREAD

**Issue by syafiqmazli** [brave/browser-laptop#3301]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Unable to open my google spreadsheet.

**Expected behavior:**

It show error "Unable to Load"

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version:
0.11.5
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

![brave error 20160822](https://cloud.githubusercontent.com/assets/1860468/17842662/ce4b94a4-6857-11e6-8982-86224f72ebda.png)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #2343
