### ISSUE TITLE
HTTPS Everywhere breaks specific sections of Tesco.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3302]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
HTTPS Everywhere breaks specific sections of Tesco.com

**Expected behavior:**
All sections of the website should be loaded normally

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 1

- Steps to reproduce:
    1. Visit [tesco.com](http://www.tesco.com/groceries/)
    2. Enabling HTTPS breaks the site as it fails to load all JS and CSS files.
    3. Other sections of the website loads normally

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/17851730/76b087aa-685b-11e6-90ca-1716ddc705cd.png)

- Any related issues:
#3240

**Comment by luixxiul** [comment]
The main reason here seems to me that the browser enables rulesets with ``platform="mixedcontent"`` by default. What do you think, @diracdeltas ? I think we should implement an option to choose whether rulesets with that flag is on or off by default.

https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Tesco.com-falsemixed.xml

**Comment by diracdeltas** [comment]
> The main reason here seems to me that the browser enables rulesets with platform="mixedcontent" by default.

That shouldn't be the case https://github.com/brave/browser-laptop/blob/master/app/httpsEverywhere.js#L77
