### ISSUE TITLE
Blocking Ad's doesn't render page properly on Daft.ie

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3304]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Blocking Ad's doesn't render page properly on Daft.ie. Empty Div elements are displayed where Ad content is placed. The main content doesn't span full width.

**Expected behavior:**
Should not display empty div elements where ad's are blocked 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 Dev Beta1
- Steps to reproduce:
  1. Visit this link on [Daft.ie](http://www.daft.ie/ireland/residential-property-for-rent/?s%5Badvanced%5D=1&searchSource=rental)
- Screenshot if needed:
  Brave
  ![image](https://cloud.githubusercontent.com/assets/17010094/17855313/02dbf340-6870-11e6-9751-d322fc30b9ea.png)

Chrome/FF
![image](https://cloud.githubusercontent.com/assets/17010094/17855360/498d6184-6870-11e6-8952-a4ed765c0b11.png)
- Any related issues:

**Comment by luixxiul** [comment]
duping to #344, https://github.com/brave/browser-laptop/issues/3387#issuecomment-242379351.
