### ISSUE TITLE
Implement option to enable HTTPS Everywhere rulesets with the flag "platform=mixedcontent" by default

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3305]
https://github.com/brave/browser-laptop/issues/3302#issuecomment-241412075

**Comment by diracdeltas** [comment]
These are already supposed to be disabled by default. https://github.com/brave/browser-laptop/blob/master/app/httpsEverywhere.js#L77

**Comment by diracdeltas** [comment]
on second thought, i think offering a switch to enable/disable mixedcontent rules wouldn't be very useful, since turning it on would break a lot of sites. closing for now.
