### ISSUE TITLE
Zoom is hitching on constant keydown.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3306]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While zooming in or out, the action is hitching at different times. If I use individual keystrokes, the zoom behaves as expected.

**Expected behavior:**
If I am zooming via keyboard, constant keydown should zoom all the way in or out.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Win7 x32
- Brave Version:
  0.11.6 pre-beta
- Steps to reproduce:
  1. On a site, zoom in or out using the keyboard combination. 
  2. Keep the keys pressed down.
  3. Observe the action.
- Screenshot if needed:
  ![zoom_hitch](https://cloud.githubusercontent.com/assets/1434040/17861450/c5bc33b2-6856-11e6-89e8-405e43eb023d.gif)
- Any related issues:

**Comment by bbondy** [comment]
Going to remove from 0.11.6 because I don't think this is a new issue, but let me know if it is otherwise.  I don't understand what hitching means either.
