### ISSUE TITLE
Cannot create wallet in packaged builds

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3308]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When on the Payments tab in Preferences, I attempted to create a wallet by clicking on the 'create wallet' button.  I attempted to click on the button numerous times, but the status never changed.

**Expected behavior:**
A wallet should be created eventually, status should update immediately.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 ia32

- Brave Version:
0.11.6 pre-beta

- Steps to reproduce:
    1. Open the Payments Preference pane.
    2. Click on 'create wallet'
    3. Observe the status

- Screenshot if needed:

- Any related issues:
No errors were found in the developer console.

**Comment by bbondy** [comment]
cc @diracdeltas @mrose17 you are probably already aware but this is a blocker for release.

**Comment by srirambv** [comment]
Browser crashes when clicked on create wallet 

0.11.6 Beta 2 on Windows 10 x64

**Comment by mrose17** [comment]
@bbondy - i hope to address this with https://github.com/brave/browser-laptop/pull/3318

**Comment by Sh1d0w** [comment]
Just to mention that create wallet button is crashing the browser under Linux as well with the following error:

```
Error: ENOENT: no such file or directory, open '/usr/share/brave/resources/app.asar.unpacked/node_modules/node-anonize2-relic-emscripten/anonize2.js.mem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:167:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:500:29)
    at Object.read (/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2.js:18:1355)
    at Object.readBinary (/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2.js:18:1623)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2.js:33:3553)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

So it is not windows only issue :)

**Comment by diracdeltas** [comment]
Fixed on OS X, has anyone confirmed for Windows/Linux?

**Comment by Sh1d0w** [comment]
Yan, I can confirm it is no longer crashing under Linux in the latest 0.11.6-beta3 build.

**Comment by bbondy** [comment]
can this be closed or still pending work?

**Comment by diracdeltas** [comment]
need confirmation that it works on windows in latest build. @srirambv or @luixxiul maybe?

**Comment by srirambv** [comment]
Confirmed working on Windows 10 as well. I am able to go till the buy bitcoin step.

**Comment by diracdeltas** [comment]
thanks all
