### ISSUE TITLE
Load adinfo file remotely so we can tweak for broken sites

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#331]
This is the file which should be removed and it should be treated like any other data file for adblock / TP / https everywhere. 
js/data/adInfo.js

**Comment by SergeyZhukovsky** [comment]
https://github.com/brave/browser-android/issues/665

**Comment by cezaraugusto** [comment]
`adInfo.js` is currently under `/content/scripts/`. So, fixed already?

**Comment by bbondy** [comment]
not done yet, this would mean not packaging adinfo file with the app.

**Comment by bsclifton** [comment]
no longer valid
