### ISSUE TITLE
Missing 'Toggle Main Menu Bar' in hamburger menu

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3311]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
As per the spec : https://github.com/brave/browser-laptop/issues/1893 a new menu item should exist on Windows and Linux which allows for the toggling of the main menu. It is not present in the current build.

**Expected behavior:**
If a user opens the hamburger menu, the menu item should exist and function appropriately.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 ia32

- Brave Version:
0.11.6 pre-beta

- Steps to reproduce:
    1. Open the hamburger menu on a Linux or Windows build of Brave.
    2. Find the 'Toggle Main Menu Bar' item in the menu.

- Screenshot if needed:
<img width="342" alt="screen shot 2016-08-22 at 2 12 27 pm" src="https://cloud.githubusercontent.com/assets/1434040/17868158/457c5f5c-6873-11e6-8101-df99d82c456d.png">

- Any related issues:
https://github.com/brave/browser-laptop/pull/3003
https://github.com/brave/browser-laptop/issues/1893

**Comment by bbondy** [comment]
was this in 0.11.5? If not let's kick this out of all milestones.

**Comment by bsclifton** [comment]
@bradleyrichter @alexwykoff where exactly should it go in the menu? We [have this menu item already coded](https://github.com/brave/browser-laptop/blob/b0ed7bab1e1e1f88de346be65d28d259161fbb15/app/common/commonMenu.js#L304) so now it's just a matter of adding it to the burger context menu

Currently, it shows when right clicking on the bookmarks toolbar. Should that one be kept the same?
https://github.com/brave/browser-laptop/blob/b0ed7bab1e1e1f88de346be65d28d259161fbb15/app/common/commonMenu.js#L304

**Comment by bsclifton** [comment]
Removed milestone, per @bbondy's comment. This was not in 0.11.5, this is a new proposal

**Comment by alexwykoff** [comment]
It was in the original specification, so it's not a matter of being in 0.11.5 or a new proposal, but rather matching the design. (https://github.com/brave/browser-laptop/issues/1893)

https://cloud.githubusercontent.com/assets/13509546/15487940/320d51e2-2106-11e6-883f-387baccb5d73.png

That said, I certainly would not call it a showstopper for 0.11.6 and it's perfectly fair to punt to a later time.

**Comment by bsclifton** [comment]
Yup, #1893 is the new proposal.  I'll close this as a dupe unless we'd like to track individual items
