### ISSUE TITLE
Modal save dialog causing lockup on macOS

### ISSUE THREAD

**Issue by jas88** [brave/browser-laptop#3313]
**Did you search for similar issues before submitting this one?**
Yes.
**Describe the issue you encountered:**
Switching tasks on OS X with save dialog open in a multi-tab window renders that window unavailable.

**Expected behavior:**
Window should remain accessible so operation can be completed or cancelled and session can be used (as does happen if only a single tab was open in that window).
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 'El Capitan' (10.11.6)
- Brave Version:
  0.11.5 (update channel: dev; checked for updates before replicating, no updates currently available)
- Steps to reproduce:
  1. Open 2+ tabs; on one of those tabs, trigger any file download from the web, so modal 'save as' dialog appears. (Doesn't seem to occur on single-tab windows.)
  2. Switch away, e.g. with command-Tab
     3.Switch back. Brave no longer operational. (Can be selected from command-tab list, but no longer shows the affected window; most menu items disabled, presumably because the no-longer-visible save dialog is still waiting for input it will never get.) Rough guess: modal message pump swallowing activation event so the main window never activates; some interaction with the tab/window association so this is multi-tab specific.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
@jas88 I tried your steps and am unable to reproduce.  Can you confirm I followed them right?

1. Open more than 2 tabs
2. Press cmd+tab, switch to finder or something that is not Brave
3. press cmd+tab and switch back to brave

Did you have to do anything while the window was backgrounded? or was it backgrounded for a while?

**Comment by jas88** [comment]
> 
> On 22 Aug 2016, at 23:38, Brian Clifton <notifications@github.com> wrote:
> 
> @jas88 I tried your steps and am unable to reproduce. Can you confirm I followed them right?
> 
> 	• Open more than 2 tabs
> 	• Press cmd+tab, switch to finder or something that is not Brave
> 	• press cmd+tab and switch back to brave
> Did you have to do anything while the window was backgrounded? or was it backgrounded for a while?

Hi Brian - you’re missing the step before switching away: start something downloading, so the Save As dialog appears on the tab, *then* switch away (with the Save dialog still active, i.e. not having picked a filename yet). The presence of that modal dialog seems to break something when multiple tabs were present.


James.

**Comment by jas88** [comment]
Hi Brian,
Reproduced on macOS Sierra (10.12) with Brave 0.12.3. In all cases, cmd-tab switches between the web browser and other applications, except for the combination of 3 circumstances: Brave, save dialog active, open full-screen. Safari and Chrome can be switched to/from with cmd-tab in all cases (including full-screen with a dialog open), Brave can be switched to/from except when it's both full-screen and has a save dialog active.

Presumably Brave should act in the same was as Safari and Chrome in this respect, shouldn't it? (I could understand if cmd-tab didn't work at all for full-screen applications - but it works fine for everything except Brave, and works fine for Brave too except when there's a dialog.)

**Comment by Liunkae** [comment]
I was also able to reproduce the problem with Brave 0.12.3 on macOS 10.12.
1. Make a new Brave window and toggle full screen (with the green full screen button or View > Toggle Full Screen View).
2. Navigate to any site.
3. Click File > Save Page As…
4. Press Command-Tab to switch to another application (e.g. Finder).
5. Press Command-Tab to switch back to Brave.
6. Click any item in the menu bar.
7. Notice that almost all menu items are disabled. With the Window menu disabled, it is hard to find the original window or switch windows.

**Comment by bsclifton** [comment]
Awesome! Thanks for digging in on this, @Liunkae :smile: And apologies for not following up again with you @jas88 

Now that we have steps to repro, we should be able to assess and fix the issue :smile:

**Comment by bsclifton** [comment]
@Liunkae are you able to reproduce on our latest version?

**Comment by Liunkae** [comment]
@bsclifton Yes, it's still reproducible on both 0.13.5 and master.

I tested the behavior of Safari and Firefox. They both bring the full screen window into focus on step 5 (above). Brave does not focus the window, even if you click the Brave dock icon.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by kjozwiak** [comment]
Verified on macOS 10.13.3 using the STR in https://github.com/brave/browser-laptop/pull/11906#issue-273121960 with the following build:

* `0.22.6`  e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: `65.0.3325.162`
* Muon: `5.1.0 `
