### ISSUE TITLE
drudgereport.com not loading correctly

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#332]

**Comment by bbondy** [comment]
Chrome left, Brave right...
![screenshot 2016-01-26 10 55 51](https://cloud.githubusercontent.com/assets/831718/12585762/72582e9a-c41b-11e5-9974-aa7e1da168e1.png)
Turns out we are actually working correctly and as expected.  It's just drudge report which has a horrible layout.

**Comment by wblondel** [comment]
Tried on IE and Edge, same "issue". I guess the issue is the website itself.

**Comment by bbondy** [comment]
Ya on firefox I don't think there's an ad there, not quite sure why they have that strangely placed ad on chromium like user agent strings.
