### ISSUE TITLE
too many redirects (casual user feedback)

### ISSUE THREAD

**Issue by idprism** [brave/browser-laptop#3322]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
go to: http://squareup.com/dashboard , "too many redirects", no way for casual user to self-remedy from base interface.

**Expected behavior:**
load
- Platform (Win7, 8, 10? macOS? Linux distro?):
  win10 x64 enterprise
- Brave Version: .11.5
- Steps to reproduce:
  1. go to website
  2. click dashboard
  3. too many redirects
  4. retry, infinitely.
  5. would be nice to see more feedback related to this error such as: try [link]"changing this setting"[/link], list of redirect attempts + [here is why we stopped following that], etc.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Currently the site is loaded properly. It looks like the issue has been fixed by their side or on HTTPS Everywhere.
