### ISSUE TITLE
On clean install, adding a bookmark via the tabs tray does not open the bookmark tray.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3331]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On a clean install, I visited a site and attempted to add a bookmark via the context menu activated on the tabs tray. 

**Expected behavior:**
The bookmark tray should open and display the new bookmark.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X, confirmed on Windows.

- Brave Version:
0.11.6 pre-beta2

- Steps to reproduce:
    1. Install the latest build.
    2. Navigate to a site.
    3. Open the context menu on the tabs tray and add a bookmark.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
@bsclifton  please take

**Comment by bsclifton** [comment]
Working on a fix now...

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/3355,  ready for review:

cc: @alexwykoff @bbondy

**Comment by alexwykoff** [comment]
Confirmed on pr branch.
