### ISSUE TITLE
Bookmarked page cannot be removed from context menu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3332]
**Describe the issue you encountered:** Bookmarked page cannot be removed from "Bookmark this page" in the context menu since the link to remove it is not displayed

**Expected behavior:** the link should be displayed

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version: 0.11.6 Beta2

- Steps to reproduce:
    1. Bookmark this page by clicking the star next to the URL bar
    2. Select "Bookmark this page" in the context menu

- Screenshot if needed:

- Any related issues: #3325

**Comment by bsclifton** [comment]
Good catch :smile: This is bringing up AddEditBookmarks modal which is expected, but not allowing for delete (modal is not aware entry is already bookmarked)
