### ISSUE TITLE
Keyboard shortcut needed for `Clear browsing data`

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3333]
Pushing Ctrl+Shift+Delete (or Cmd+Shift+Delete on Mac) should pop up the `Clear browsing data` modal

![screen shot 2016-08-23 at 8 09 38 am](https://cloud.githubusercontent.com/assets/4733304/17897419/fe89f2b2-6908-11e6-80ce-f4eb384059cc.png)

**Comment by Liunkae** [comment]
The accelerator is already set to `Shift+CmdOrCtrl+Delete` [here](https://github.com/brave/browser-laptop/blob/c82775bcf7f8478356f5b50275c8dcc2acf2f164/app/browser/menu.js#L326). I'm not sure why it isn't working.
![image](https://cloud.githubusercontent.com/assets/19424103/20454182/4d7b7e9c-adfe-11e6-8a44-0dcd84e86133.png)

**Comment by bsclifton** [comment]
Verified this works as expected
