### ISSUE TITLE
Clear Browsing Data button on about:preferences not working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3335]
**Describe the issue you encountered:** "Clear Browsing Data" button on about:preferences is not working. It is not clickable.

**Expected behavior:** It should display the modal dialog.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32bit

- Brave Version: 0.11.6 Beta2

- Steps to reproduce:
    1. Open about:preferences#security
    2. Click "Clear Browsing Data Now..." button

- Screenshot if needed:

- Any related issues: #3325

Setting a milestone for now.

**Comment by bridiver** [comment]
tests are failing here as well
