### ISSUE TITLE
developer tools toggle closes when unfocused

### ISSUE THREAD

**Issue by ducks** [brave/browser-laptop#3343]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When developer tools are not open, using Command+Option+I, developer tools open.
When developer tools are open and focused, using Command+Option+I, developer tools don't change.
When developer tools are open but unfocused or minimized, using Command+Option+I closes developer tools.

**Expected behavior:**
Command+Option+I opens developer tools if closed, otherwise, it brings it to focus.

Having developer tools close when unfocused seems very unintuitive and requires extra
steps to bring it back open.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X El Capitan 10.11.4 (15E65)
- Brave Version:
  Brave: 0.11.5
  Electron: 1.3.3
  libchromiumcontent: 52.0.2743.116
  V8: 5.2.361.49
  Node.js: 6.3.0
  Update Channel: dev
- Steps to reproduce:
  1. Use Command+Option+I to open developer tools
  2. Minimize/take developer tools out of focus
  3. Use Command+Option+I again which closes the developer tools
- Screenshot if needed:
- Any related issues:

**Comment by Liunkae** [comment]
Related to: #45

**Comment by bbondy** [comment]
Duping to #45, I have a fix for this.
