### ISSUE TITLE
If a site does not have a title, the bookmark should default to the url instead.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3344]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to bookmark http://alexwykoff.com/2/demo/ , the dialog would not allow me to continue because there was no title for the site.  

**Expected behavior:**
While we should not allow users to save blank names for bookmarks, the default should exist that if a site has no title, the url is the default value given.  0.11.5 and prior have this default.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta2

- Steps to reproduce:
    1. Open the latest build
    2. Visit a site with no title, like http://alexwykoff.com/2/demo/
    3. Attempt to bookmark the page, observe the modal.

- Screenshot if needed:
![add_bookmark_no_title](https://cloud.githubusercontent.com/assets/1434040/17906802/73540ae4-693e-11e6-8b65-880e23d111af.gif)

- Any related issues:

**Comment by bbondy** [comment]
I have no idea what's going on in that demo but it is making me non productive 😛
