### ISSUE TITLE
Clear browser history should work regardless of whether or not the page is bookmarked.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3346]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to clear browser history, I noticed that certain pages were staying in history. When I deleted the bookmark and cleared the history again, the history line item for that formerly bookmarked page disappeared.

**Expected behavior:**
All browser history should be cleared regardless of bookmark status.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta2

- Steps to reproduce:
    1. Visit and bookmark some sites.
    2. Go to about:history and clear history, notice remaining items.
    3. Delete a bookmark and clear history.

- Screenshot if needed:
![history_is_not_clearing](https://cloud.githubusercontent.com/assets/1434040/17907742/e0a1bd86-6942-11e6-80f9-9b51aae39c53.gif)

- Any related issues:

**Comment by alexwykoff** [comment]
Sorry, dup of https://github.com/brave/browser-laptop/issues/3330. My issue searching regex-fu wasn't strong enough.

**Comment by bridiver** [comment]
I don't think #3330 is the same thing. The real issue appears to be the inclusion of non-history items in the history
```
history={frame.get('location') === 'about:history'
                ? this.props.appState.get('sites') || emptyMap
                : null}
``` 
@bbondy

**Comment by bsclifton** [comment]
Definitely not the same thing- the entire sites list is being sent over, which contains bookmarks and history. That could be optimized and additionally (to fix the issue), about:history needs to hide entries which have a null timestamp

**Comment by bsclifton** [comment]
Submitted PR w/ fix :smile: 

opened a new ticket for the refactoring concerns 
https://github.com/brave/browser-laptop/issues/3502

**Comment by bsclifton** [comment]
## To verify the fix
- Install a version of Brave which has the fix
- Launch Brave and navigate to about:history
- Launch a new tab, visiting a page which has not been visited yet
- Bookmark this previously unvisited site
- Return to history tab
- Verify the site you just visited shows up
- Click the `Clear browsing history` button
- Make sure to pick `Browser history` and click OK
- Verify that the bookmarked site no longer shows up
