### ISSUE TITLE
Bookmark folder names should contain visible text

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3347]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While verifying https://github.com/brave/browser-laptop/issues/3188, I found it was possible to create folder names which are whitespace.

**Expected behavior:**
We should probably have the user input something resembling visible text.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta2

- Steps to reproduce:
    1. Select 'Add folder...' from the bookmark tray context menu.
    2. Type '<spacebar>' for the name.
    3. Save the folder.

- Screenshot if needed:
![whitespace_folders](https://cloud.githubusercontent.com/assets/1434040/17908737/3fda1092-6947-11e6-85c6-db3d5ed2c8fa.gif)

- Any related issues:

**Comment by bbondy** [comment]
let's just `trim` the input before saving it and validating it.

**Comment by luixxiul** [comment]
I'm not sure if this is related, but you cannot delete the folder created following the STR by clicking "Delete" in the dialog displayed with "Edit Bookmark". "Delete Folder" in the context menu on the folder works.

**Comment by bbondy** [comment]
It's an indepdent bug, please post that as a new bug @luixxiul, thanks!
