### ISSUE TITLE
Commonize HTTPSE leveldb code between laptop and iOS

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#3348]
iOS code is now in C++ as part of LevelDB support, and is cross-platform, we should be sharing this code:

https://github.com/brave/browser-ios/pull/378/commits/cdc9078d5c4a438fde305c96621570e5512c1a58

It may need a few ifdefs around the leveldb calls, as chromium might have a different API.

**Comment by diracdeltas** [comment]
i think this is a subticket of #3341

**Comment by diracdeltas** [comment]
i'm not sure if we should move from json to leveldb but we can at least cut down the size of the json file by a lot

**Comment by bridiver** [comment]
I agree with @garvankeeley that we should have a common lib that handles the details of the lookups (parsing, exclusions, etc...). The backing store should be hidden or pluggable imo.
