### ISSUE TITLE
implement ledger recovery keys screen

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3350]
for advanced users who want to backup their ledger recovery keys

@bradleyrichter has mockups for this

**Comment by bradleyrichter** [comment]
![image](https://cloud.githubusercontent.com/assets/13509546/17911703/e9c4639a-6943-11e6-9230-506b288388b0.png)


![image](https://cloud.githubusercontent.com/assets/13509546/17911725/130e5ee0-6944-11e6-8b79-32b758c4fd43.png)

**Comment by alexwykoff** [comment]
Please make sure to document the recovery process as part of the steps for QA. Thanks!

**Comment by ayumi** [comment]
We talked about this and decided having plain text you can copy/paste(/take a screenshot of) would be suitable for the first iteration.

**Comment by diracdeltas** [comment]
imo the 'Save' button should be replaced with a 'Show codes' button. as an advanced user, i don't have a printer or want to save the file to disk, i just want to see the code so i can copy/paste it somewhere safe.

**Comment by diracdeltas** [comment]
@bradleyrichter why is this in the 'Advanced' panel instead of the Payments panel?

**Comment by bradleyrichter** [comment]
@diracdeltas It was there because didn't have this new and improved Payments-specific settings dialog: 

![image](https://cloud.githubusercontent.com/assets/13509546/18494479/31f7374a-79cb-11e6-8464-d38ddbdafe2a.png)

(includes "later" features so please ignore those for now)

**Comment by mrose17** [comment]
@jkup - i have the wallet recovery implemented in the server. i will provide an API call to `ledger.js` that you'll be able to invoke!

**Comment by jkup** [comment]
@bradleyrichter is all the "Advanced Settings.." has for now the view/print and recover buttons? Is the rest of the dialog empty?

Also in your first mockup there are both Backup and Recover buttons but in your second one there is only a View/Print button. Which are we going with?

**Comment by bradleyrichter** [comment]
@mrose17 claims those settings are a slam-dunk to connect? So if easy, we can do them now.

The buttons are from different dialogs. Backup and Recover each have their own 2nd dialog.

**Comment by mrose17** [comment]
accidentally closed when a supporting ledger change was made!

**Comment by jkup** [comment]
Bumping this because it's surely going to slip tonight.

@mrose17 @ayumi I have the front end work complete. Is the back end work finished? i.e can I get a user's ledger keys and is there an endpoint I can hit to recover them?

Assuming this work is done, can one of you help me with how to go about implementing it in the client? Thanks!

**Comment by bbondy** [comment]
@jkup could you put up a WIP PR for this? Just want to see how close we are on it. Thanks!

**Comment by jkup** [comment]
Will do!
