### ISSUE TITLE
ledgerInfo should change to 'creating' as soon as ledger.boot() is called

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3352]
right now, there is a delay of several seconds after the `Create wallet` button is clicked before the wallet is done being created. During this period, while `ledger.boot()` is running, the status of the wallet should be `creating` so that the the user knows that something is actually happening.

**Comment by mrose17** [comment]
Closed by https://github.com/brave/browser-laptop/pull/3351
