### ISSUE TITLE
update ledger welcome page with adjusted UI layout and partner logos

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3353]
![image](https://cloud.githubusercontent.com/assets/13509546/17911566/0368b8e2-6943-11e6-9f87-e64da8abb50b.png)

showing some dims:
![image](https://cloud.githubusercontent.com/assets/13509546/17911581/17e2e590-6943-11e6-9e21-bc3489e98df0.png)

partner logos attached

[partner logos.zip](https://github.com/brave/browser-laptop/files/433649/partner.logos.zip)

**Comment by jkup** [comment]
@bradleyrichter is the orange "flip the switch" supposed to be a link?

**Comment by bradleyrichter** [comment]
no. And we can drop that color change if it feels misleading.

**Comment by jkup** [comment]
@bradleyrichter Here's how it's looking so far. I still have to do a few pixel tweaks and figure out how we're going to serve the 2x images but wanted to give you a screenshot!

![screen shot 2016-08-23 at 11 18 25 pm](https://cloud.githubusercontent.com/assets/490294/17920226/fe1c7ac8-6987-11e6-8df6-1aab39eb1509.png)

**Comment by bradleyrichter** [comment]
@jkup This looks great. Nearly polished!

Here is a 1:1 screen shot with spec image on left, code on right. Maybe the font size is referenced in other places and we need to add styles for this or fix the other placements?

![image](https://cloud.githubusercontent.com/assets/13509546/17942647/1e460570-69ed-11e6-874f-3f92ac4d0ea0.png)

**Comment by bradleyrichter** [comment]
or are the fonts drawing bigger on your laptop because they are set in px instead of EM?

**Comment by jkup** [comment]
@bradleyrichter updated! Yeah those were just the styles applied in the current production version. Want to let me know what you think of the design when the screen is made smaller?
