### ISSUE TITLE
redirect to basic auth hangs forever

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3354]
`https://www.google.com/url?hl=en&q=http://highgrowthhandbook.rangeprojects.com/&source=gmail&ust=1472080680463000&usg=AFQjCNEoxlcS0F_6V6913poBHqRZ2lu0yw` hangs indefinitely

**Comment by bbondy** [comment]
Please mark QA steps here for things to try since this is a bit of a bigger change.

**Comment by bridiver** [comment]
1. go to https://www.google.com/url?hl=en&q=http://highgrowthhandbook.rangeprojects.com/&source=gmail&ust=1472080680463000&usg=AFQjCNEoxlcS0F_6V6913poBHqRZ2lu0yw
It should either redirect to http://highgrowthhandbook.rangeprojects.com or go to the google redirect warning page. If it redirects you should get a username/password dialog
2. go to http://highgrowthhandbook.rangeprojects.com and you should get a username/password dialog
I don't have a valid username/password to use, but entering an invalid username/password should give you the dialog again and canceling out should go to the "unauthorized" page

If anyone has a basic auth site with valid username/password that would be good to test as well

**Comment by bridiver** [comment]
http://test.webdav.org/auth-basic/ can be used to test basic auth user1/user1
