### ISSUE TITLE
Toggling Bookmarks Toolbar from "Bookmarks" menu is not reliable

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3356]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If you continuously enable/disable the bookmarks toolbar via the Bookmarks menu (or via the context menu), you'll notice it doesn't always work.

**Expected behavior:**
It should always enable or disable the bookmarks toolbar

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.11.5, 0.11.6 beta 2

- Steps to reproduce:
    1. Pick "Bookmarks Toolbar" from "Bookmarks" menu
    2. See if toggling actually worked. If so, repeat step 1 until it does not work
    3. Notice that the checked state of the menu does not match the actual state. You can contrast your results against "Bookmarks" > "Bookmarks Toolbar" in the Hamburger menu (which does work properly)

- Screenshot if needed:

- Any related issues:

**Comment by bdylanwalker** [comment]
Workaround.  This isn't a fix, but might help identify the problem.  You can get the toggle to work correctly one more time by using the following steps.  Open a new tab with the plus sign.  Navigate to a url in that tab by typing into the address bar.  Then close the tab.  The Bookmarks > Bookmarks Toolbar toggle will toggle correctly one time.

**Comment by bsclifton** [comment]
Great pic by @darkdh showing the issue:
![123](https://cloud.githubusercontent.com/assets/11330831/18899553/6175c5e8-856c-11e6-8b7d-7440e231800e.gif)

**Comment by bbondy** [comment]
I don't think it has anything to do with it not being reliable, but just that once it can only be changed once and then never changes state after that.  Could you update the original message to that for QA's benefit? Thanks!

**Comment by bbondy** [comment]
QA
Steps to reproduce, start the browser with the bookmarks toolbar on:
- Turn it off from the top menu 
- Turn it on from the top menu

Actual results:
it doesn't turn back on

Expected results:
It can be toggled back and forth.

**Comment by luixxiul** [comment]
Follow-up: #4810
