### ISSUE TITLE
Autofill follow-up

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#3358]
1.   ~~Add timestamp in autofill state (#3438)~~
2.  https://github.com/brave/browser-laptop/pull/3241#r75715202
3.  ~~clear autocomplete data (#3458) (https://chromium.googlesource.com/chromium/src/+/master/chrome/browser/browsing_data/browsing_data_remover.cc#915)~~
4. integrate password manager (`components/password_manager` + `PasswordManagerClient` implementation) (https://github.com/brave/browser-laptop/issues/3530)

**Comment by luixxiul** [comment]
How about implementing an option of the master password to see sensitive data like credit card?

**Comment by darkdh** [comment]
@luixxiul all of the autofill data are already encrypted in database on electron side.

**Comment by luixxiul** [comment]
I see, that sounds great :-)

**Comment by bsclifton** [comment]
@darkdh what's left on this one? Could we capture a more descriptive title? thanks :smile:

**Comment by darkdh** [comment]
Updated the broken link. and the items without strike through is the task need to be done.
I will create separated issues for follow-up next time. thx

**Comment by luixxiul** [comment]
A request for the password importer: https://community.brave.com/t/how-to-import-password-from-firefox/897

**Comment by tomasdev** [comment]
I see one could technically do Chrome -> 1Password -> Brave, but that's not free. Given Brave open-source nature, would love to be able to import my Chrome passwords into it. 👍
