### ISSUE TITLE
Form autofill popup should appear under the focused field

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3359]
Instead it is currently showing up in the middle for me.  For @darkdh it appears at the correct location though. Maybe a DPI issue?

<img width="798" alt="screenshot 2016-08-24 02 22 36" src="https://cloud.githubusercontent.com/assets/831718/17920292/b86a92d4-69a1-11e6-97a2-ca1768142b64.png">

**Comment by luixxiul** [comment]
Same here on Windows 7 64 bit

**Comment by darkdh** [comment]
That's weird. My location is correct
<img width="408" alt="screen shot 2016-08-24 at 16 28 19" src="https://cloud.githubusercontent.com/assets/11330831/17923679/e173080c-6a17-11e6-949c-b017d88429bb.png">

**Comment by bsclifton** [comment]
I tested this too (after running `rm -rf ./node_modules/ && rm -rf ~/.electron/ && npm install`) and it looks good to me (macOS):
![screen shot 2016-08-24 at 9 00 30 am](https://cloud.githubusercontent.com/assets/4733304/17938158/a71896ba-69d9-11e6-8eaa-7030af9bcc2b.png)

**Comment by bsclifton** [comment]
doh- it happened for me on Windows :frowning: 

![image](https://cloud.githubusercontent.com/assets/4733304/17939288/d0f9f280-69de-11e6-86cb-0c91368cdfae.png)

**Comment by bsclifton** [comment]
@darkdh mentioned position is emitted from here:
https://github.com/brave/electron/blob/master/atom/browser/autofill/atom_autofill_client.cc#L166

I can help look at this issue

**Comment by bsclifton** [comment]
@bbondy did you have any specific STR? I can't repro on Mac

**Comment by bsclifton** [comment]
I'm reliably able to repro now- thanks to @bridiver for suggestion when I was talking it out

Offset appears to be adding the offset of the window in addition to the frame's x/y

**Comment by bsclifton** [comment]
PRs submitted for brave/electron and brave/browser-laptop

Root cause:
- position being sent back was the top left of the textbox
- need to add the height of the textbox, so it goes below
- @darkdh had the right idea by getting the client area; however, we didn't want the X/Y...
  - we need the client width/height
  - this can be compared against the frame's width/height
  - offset is then correct

**Comment by luixxiul** [comment]
On 0.11.6 Beta5 (Windows 7 64 bit JP)
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18028871/a4667076-6cc3-11e6-99c4-3daf8a295122.png)
Hasn't this been fixed?

**Comment by luixxiul** [comment]
Also, though I click the suggestion, it is not filled in the field.

**Comment by darkdh** [comment]
This is brave built-in password manager, I assume.

**Comment by luixxiul** [comment]
Yes it is. I just thought they were similar.

**Comment by bridiver** [comment]
autofill seems to track usernames as well, but the location is correct on mac
