### ISSUE TITLE
Alignment and padding of title on add autofill data popups should match clear browsing data

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3360]
The title for the current popups needs more padding around it and the alignment should be fixed.  Make it closer matching to the clear browsing data popup please.

Current popups:
<img width="474" alt="screenshot 2016-08-24 02 25 06" src="https://cloud.githubusercontent.com/assets/831718/17920359/15ac1c4c-69a2-11e6-8ae2-e5c259e973e1.png">

<img width="472" alt="screenshot 2016-08-24 02 25 13" src="https://cloud.githubusercontent.com/assets/831718/17920360/16c53988-69a2-11e6-8d1f-4a33a7069338.png">

Reference image:
<img width="329" alt="screenshot 2016-08-24 02 24 53" src="https://cloud.githubusercontent.com/assets/831718/17920349/0fdef302-69a2-11e6-8f5a-bd72031d64db.png">

**Comment by luixxiul** [comment]
Also will you please keep the width of labels wide enough in terms of l10n?
