### ISSUE TITLE
Bookmarked about pages appear in the history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3366]
When I bookmark about pages, they appear on ``about:history``.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.6 beta3

- Steps to reproduce:
    1. Open ``about:history`` from url bar
    2. bookmark it with CTRL+D and clicking "Save" on the dialog
    3. Open a new tab
    4. Go to github.com
    5. Select the about:history tab

The same thing happens when I open and bookmark ``about:passwords``.

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17921651/e0f1a4da-6a15-11e6-830b-20811dc404c8.png)

I am not sure if this is intended and it works as it should or not.

cc: @bsclifton 

#3362

**Comment by bbondy** [comment]
I think Chrome filters out all about pages, please verify and if so do the same here.

**Comment by bsclifton** [comment]
Fixed w/ https://github.com/brave/browser-laptop/pull/3459
