### ISSUE TITLE
Warning message is not displayed when trying to open excellentmovies.net from URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3367]
**Describe the issue you encountered:**
When I was trying to open excellentmovies.net from URL bar by hitting a enter key, it did not display the warning message. If I hit the key again, it was displayed.

**Expected behavior:** The warning message should be displayed with a single enter key

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 64 bit

- Brave Version: 0.11.6 beta3

- Steps to reproduce:
    1. Copy this url: excellentmovies.net
    2. Move away your session-store-1 file temporarily
    3. Open browser
    4. Paste the url into the URL bar
    5. Hit <kbd>Enter</kbd> -> nothing is displayed
    6. Hit it again -> warning message is displayed

- Screenshot if needed:

- Any related issues: #3362

**Comment by luixxiul** [comment]
Confirmed on Windows 10 32 bit too #3363

**Comment by luixxiul** [comment]
Setting a milestone for now

**Comment by bbondy** [comment]
cc @bridiver or @diracdeltas I reproduced this too

**Comment by bridiver** [comment]
this is similar to https://github.com/brave/browser-laptop/issues/3354
we're trying to match a url that hasn't been set yet in the frame. We somehow lost tabId in the web request, but I'm going to add it back in so we can route to the correct webContents
