### ISSUE TITLE
Minimal style changes to new light-skin

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#337]
@teemuteemu Here are some small adjustments, mostly to further refine the tab set nav buttons. We are seeing early signs of a UX problem where muscle memory for page nav creates a mis click on the tab set button instead. The original location of the button compared to the page nav buttons in Chrome and Firefox was the main cause.

The change to hiding the tab set buttons and indicator/selector has reduced this until they appear. 

These changes should further reduce the problem and refine the look/feel more.

1. change tab set nav button icons to double-chevron (to differentiate icon from page nav)

.fa-angle-left:before {
    content: "\F100";
}

.fa-angle-right:before {
    content: "\F101";
}

2. add new icons to:  (they are currently sharing the same icon def)
<span class="back fa fa-angle-left">
<span class="forward fa fa-angle-right">

icon =  content: "\F104";  (back)
icon =  content: "\F105";  (forward)

3. change prev/next tab colors (not disabled) to match tab background 

    display: inline-block !important;
    background: #dfdfdf;

   .nextTab:not([disabled]):hover {
    background: #ffffff;

4. change prev/next tab font size and position and color (this feel right to me but it may require adjustment to the New Tab button)

.prevTab {
   
    border-bottom-left-radius: 0px;
    border-top-left-radius: 4px;
    padding-left: 36px;
    text-align: left;
    transform: translateX(33px);

.prevTab, 
    display: none !important;
    color: #3B3B3B;
    font-size: 19px !important;
    height: 26px;
    line-height: 25px !important;
    vertical-align: top;
    width: 54px;

.nextTab {

    border-bottom-right-radius: 0px;
    border-top-right-radius: 4px;
    float: right;
    padding-right: 36px;
    text-align: right;
    transform: translateX(-35px);

nextTab {
    display: none !important;
    color: #3B3B3B;
    font-size: 19px !important;
    height: 26px;
    line-height: 25px !important;
    vertical-align: top;
    width: 54px;

5. change top BG color to lighter grey for more contrast in UI. (I like the contrast change but this may create a problem for app focus-nonfocus colors that still needs addressing)

.top {
    -moz-window-dragging: drag;
    padding-top: 6px;
    background: #F3F3F3;

6. change opacity of page back/forward disabled state to 0.2

.top .backforward span {
    position: absolute;
    color: #555;
    font-weight: 300;
    opacity: 0.2;

7. add separate font size class for reload and stop buttons so size can be reduced from 20 to 16 without effecting other icon sizes. (ideally, the new-tab button would also be disconnected as it should be bigger)

.fa-rotate-right:before, .fa-repeat:before {
    content: "\F01E";

8. increase tab height so 1px gap at bottom is removed

.tab {
    height: 27px;

![screen shot 2016-01-25 at 7 22 00 pm](https://cloud.githubusercontent.com/assets/13509546/12590686/0acaca82-c419-11e5-8d37-6bc460565829.png)

![screen shot 2016-01-25 at 7 22 33 pm](https://cloud.githubusercontent.com/assets/13509546/12590695/14d40728-c419-11e5-855d-991369a8770c.png)

![screen shot 2016-01-25 at 7 22 26 pm](https://cloud.githubusercontent.com/assets/13509546/12590702/1a38cea6-c419-11e5-808d-e2177b2f8dc6.png)

![screen shot 2016-01-25 at 7 22 12 pm](https://cloud.githubusercontent.com/assets/13509546/12590706/1ea3c892-c419-11e5-8cca-ab22b9c15057.png)

**Comment by bbondy** [comment]
I'll take this so we can do a quick release today.
