### ISSUE TITLE
Preferences : Payments : Add Funds modal alignment appears to be off for Brave wallet address

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3378]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When opening the Add Funds modal, it appears as though the Brave wallet address is pushed to the right by an empty div.

**Expected behavior:**
The address info should be either centered below the two prominent columns or left-aligned.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X.

- Brave Version:
0.11.6 pre-beta3

- Steps to reproduce:
    1. Enable Brave Payments.
    2. Create a wallet.
    3. Click on Add Funds.

- Screenshot if needed:
<img width="718" alt="screen shot 2016-08-24 at 10 52 49 am" src="https://cloud.githubusercontent.com/assets/1434040/17938241/ba2b899a-69ea-11e6-9152-d4980485b19d.png">

- Any related issues:

**Comment by alexwykoff** [comment]
@bradleyrichter would you have a spec handy for this?

**Comment by bradleyrichter** [comment]
The address line is breaking. If we must show the string of randomized characters, then we may  need to change this layout.

@mrose17 Is the character count fixed? Or can the string be longer? 

Can we stack it into 4 lines?

**Comment by mrose17** [comment]
a bitcoin address may be upto 35 characters. it is unwise to break it up. it should appear as one string without any whitespace. it is designed to be selected in a single click (no punctuation characters, whitespace, etc., are allowed in the address)

**Comment by diracdeltas** [comment]
i fixed this in master by making the font size smaller but no idea if it's broken on other screen resolutions

**Comment by diracdeltas** [comment]
calling this closed by https://github.com/brave/browser-laptop/commit/bbc4d9057469b0c144471870d3f0ab02f9e6ad18#diff-4b50ff14dadc9756719a577a72f520d6R581
