### ISSUE TITLE
Duping texts on ledger welcome page in other languages than English

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3379]
**Did you search for similar issues before submitting this one?** I think someone has reported this, but I cannot find it though I searched for it as much as possible.

**Describe the issue you encountered:** If I change the language setting to other languages than English, duping texts are displayed on ledger welcome page. Confirmed on the Japanese setting.

**Expected behavior:** ``paymentsWelcomeText3`` should be removed and ``paymentsWelcomeTextBold`` should be translatable.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.6 beta3

- Steps to reproduce:
    1. Change your language setting in Brave into Japanese
    2. Open about:preferences and select Payments

- Screenshot if needed:
<img width="510" alt="screenshot 2016-08-25 1 09 06" src="https://cloud.githubusercontent.com/assets/3362943/17939335/25b67c9a-6a65-11e6-9227-381f6c0b80e6.png">

- Any related issues:

**Comment by luixxiul** [comment]
Setting a milestone for now as it seems easy to fix.

**Comment by bridiver** [comment]
everything appears to be configured correctly, it's just missing the translation for `paymentsWelcomeTextBold`

**Comment by luixxiul** [comment]
Has ``paymentsWelcomeText3`` been removed or replaced with something else already?

**Comment by bridiver** [comment]
@bbondy @luixxiul says there is a transifex 502 error and I have no idea what to do about that

**Comment by luixxiul** [comment]
Updating translation should solve the issue. Let me check.

**Comment by luixxiul** [comment]
I confirmed it fixed the issue. Will push a PR for translation update.

**Comment by diracdeltas** [comment]
thanks @luixxiul
