### ISSUE TITLE
Preferences : Payments : Add Funds - Transfer BTC link goes to jsfiddle

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3380]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When clicking on the 'Transfer BTC' link in the add funds modal, a new tab is opened to jsfiddle.

**Expected behavior:**
It should probably go to a bitcoin handler.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta3

- Steps to reproduce:
    1. Enable Brave wallet, create a wallet.
    2. Click on the Add Funds control.
    3. In the add funds modal, click on 'Transfer BTC'.

- Screenshot if needed:
![transfer_btc_link](https://cloud.githubusercontent.com/assets/1434040/17939530/a8d037bc-69f0-11e6-9cf7-761076deb983.gif)

- Any related issues:

**Comment by alexwykoff** [comment]
cc: @diracdeltas

**Comment by bbondy** [comment]
was this fixed somewhere else?

**Comment by bbondy** [comment]
Caught up on #testers on Slack and it was due to registering a protocol handler on jsfiddle.

**Comment by diracdeltas** [comment]
Sorry, should have explained it here. Due to testers registering on https://jsfiddle.net/LnwtLckc/5/
