### ISSUE TITLE
Browser crashes when trying to signup on Coinbase

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3382]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Browser crashes when trying to signup on Coinbase. 

**Expected behavior:**
Should allow user to signup.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 3

- Steps to reproduce:
    1. Open [singup ](https://www.coinbase.com/signup)page on Conibase
    2. Enter fields and click on signup 
    3. Browser crashes when the clicked on signup.

Chrome blocks two flash elements on the signup page which doesn't show up 

- Screenshot if needed:

Brave console with shields down
![image](https://cloud.githubusercontent.com/assets/17010094/17942374/01585246-6a2f-11e6-84d7-c75942129451.png)

Flash element blocked by Chrome at page load
![image](https://cloud.githubusercontent.com/assets/17010094/17942382/0ce1ab3a-6a2f-11e6-8ced-da28bb60d25e.png)

- Any related issues:
#3398

**Comment by darkdh** [comment]
Sorry, I didn't notice this first. It'a the same issue of #3398

**Comment by Sh1d0w** [comment]
It should be fixed via #3398

**Comment by luixxiul** [comment]
Confirmed it was fixed on the latest beta, closing.
