### ISSUE TITLE
Can't refresh page if there's a cert error

### ISSUE THREAD

**Issue by henrikhodne** [brave/browser-laptop#3384]
**Did you search for similar issues before submitting this one?**

Yes, I wasn't able to find anything, but I'm not 100% sure that there aren't any, since there's no "easy" error message to search for.

**Describe the issue you encountered:**

I connected to a Wi-Fi with a captive portal (like most free Wi-Fis have nowadays), and opened Brave to go through the captive portal. All my existing tabs started to load, but got an error due to a certificate error. I opened a new tab to do the captive portal login, and then switched back to the tabs that got a certificate error and tried to refresh, but there's no refresh button and neither Ctrl-R nor F5 works. There's also no "retry" button on the error page like there is on connection error pages.

**Expected behavior:**

I'm able to refresh the page either with Ctrl-R or F5 or a button on the error page, and I don't have to close the tab and reopen it.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Ubuntu 16.04.1.

- Brave Version:

0.11.1

- Steps to reproduce:
    1. Open a tab with some HTTPS page on it.
    2. Connect to a network that has a captive portal that attempt to redirect HTTPS connections.
    3. Log in to the network so HTTPS connections are passed through normally.
    4. Attempt to refresh the HTTPS page from earlier.

#2826

**Comment by gulkily** [comment]
#2826

**Comment by bbondy** [comment]
This falls into the same fix as #2826 so I'll close as a dupe.
