### ISSUE TITLE
Long URLs are shortened in status bar

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3385]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I hover a link that goes to a long URL, the URL is displayed at the bottom of the viewport, but it is trimmed.

**Expected behavior:**
Chromium will do this too, but it will expand it after a second or two.
Firefox always displays the whole URL. I prefer this behavior.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.5
- Steps to reproduce:
  1. Open a page with a link that goes to a long URL.
  2. Move the mouse cursor of the link

Expected: Entire URL shown at the bottom of the viewport

Actual: The URL is trimmed
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1530699/17947028/da840afe-6a18-11e6-9bd4-8ecdfb8d977a.png)

**Comment by bsclifton** [comment]
Verified fixed with Brave core! Thanks for the great steps, @gulkily 😄
