### ISSUE TITLE
About dialog does not allow copying text to clipboard

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3386]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In the About dialog, the text can be selected, but is not copied to the clipboard when I press Cmd+C.

**Expected behavior:**
Selected text should be copied to the clipboard.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.5

- Steps to reproduce:
    1. Open the About dialog (Brave menu > About Brave)
    2. Select some or all of the text in the dialog
    3. Press Cmd+C
    4. Open something with a text field
    5. Press Cmd+V

Expected: Text is copied to the clipboard in step 3, pasted in step 5

Actual: Text is not copied to the clipboard.

**Comment by bbondy** [comment]
duping to https://github.com/brave/browser-laptop/issues/463
