### ISSUE TITLE
Adblock creates empty div element after blocking ad's

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3387]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Adblock creates empty div element after blocking ad's.   

**Expected behavior:**
Should not create a empty div elements in between the page elements. Currently Adblock blocks the ad and the div element.

This is happening on most of the sites. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 3

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:
![adblock](https://cloud.githubusercontent.com/assets/17010094/17947898/87808bf6-6a46-11e6-8d1c-d46f72a76590.gif)

- Any related issues:

**Comment by bbondy** [comment]
duping to
https://github.com/brave/browser-laptop/issues/344
