### ISSUE TITLE
Flash placeholder not displayed on Bloomberg, Auto plays flash videos

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3388]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Flash placeholder not displayed on Bloomberg, Auto plays flash videos and video controls are not displayed.

**Expected behavior:**
Should display flash placeholder when playing flash content. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 3

- Steps to reproduce:
    1. Visit [Bloomberg.com](http://www.bloomberg.com/europe)
    2. Scroll down the page to the video section
    3. Flash Video start playing automatically. 

- Screenshot if needed:

![bloomberg](https://cloud.githubusercontent.com/assets/17010094/17949685/8a5b18d4-6a4e-11e6-8e32-6c3481c126f8.gif)

![image](https://cloud.githubusercontent.com/assets/17010094/17949604/08e984f2-6a4e-11e6-95b5-162ab95c09eb.png)

Chrome Flash block
![image](https://cloud.githubusercontent.com/assets/17010094/17949971/1339f890-6a50-11e6-90b0-f308b45bc498.png)

- Any related issues:

cc: @diracdeltas

**Comment by diracdeltas** [comment]
Those are HTML5 videos in Brave, but Flash videos in Chrome. That's the beauty of triggering HTML5 fallback by pretending flash isn't installed. :)

**Comment by diracdeltas** [comment]
you can open devtools and inspect the video to make sure it's actually `<video>` elements and not flash objects
