### ISSUE TITLE
0.11.6-beta3 always wants to report a crash -- when normally exiting -- on macOS

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3394]
**Did you search for similar issues before submitting this one?**
yes.

**Describe the issue you encountered:**
on mac os, when you quit the browser (via CMD-Q, etc.), it wants to report a crash.

**Expected behavior:**
on mac os, when you quit the browser (via CMD-Q, etc.), it shouldn't want to report a crash.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.11.6-beta3

- Steps to reproduce:
    1. start on macOS
    2. type CMD-Q
    3. hilarity ensues

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
This is also happening under Linux version as well, not only under macOS.

**Comment by bridiver** [comment]
the fix will cover all of them
