### ISSUE TITLE
Brave crashes with segmentation fault when submitting a form

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3398]
**Describe the issue you encountered:**
After submitting a simple HTML form Brave crashes with segmentation fault. The same form is successfully submitted in all other major browsers.

**Expected behavior:**
Brave should not crash.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Fedora 24

- Brave Version:
0.11.6-beta3

- Steps to reproduce:
    1. Open https://jsfiddle.net/2f4e55za/
    2. Click submit
    3. ?

- Screenshot if needed:

- Any related issues:

cc @bbondy @diracdeltas

**Comment by darkdh** [comment]
The root cause is https://github.com/brave/electron/commit/1e3574bca24cdc95745d420563fd859cb3d795d2#diff-24b1343d288fbdb518df9aa7bff0f73dR99

<img width="1439" alt="screen shot 2016-08-25 at 17 28 21" src="https://cloud.githubusercontent.com/assets/11330831/17963749/955cfcd4-6ae9-11e6-9674-872e41efec95.png">

**Comment by Sh1d0w** [comment]
@darkdh Thanks. Do you think this is related as well #3401 ?

**Comment by pettys** [comment]
Auto-updated Brave today and got crashes on submitting forms. Tried the jsfiddle referenced in the OP of this issue and it crashes my browser:

Brave: 0.22.667 
V8: 6.6.346.24 
rev: 0433b26a03c8daf9b181057cd2ffa7b530496faf 
Muon: 5.2.6 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by bsclifton** [comment]
@pettys we have captured the most recent iteration of this bug with https://github.com/brave/browser-laptop/issues/13947

We have a fix and the build is running now 😄 We should be able to release a fix soon! Stay tuned

**Comment by pettys** [comment]
@bsclifton Thanks - you rock!
