### ISSUE TITLE
Properly unregister Frame webview events when components unmount

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#34]
We have some:
this.webview.addEventListener in frame.js

We could remove those as well when the component unmounts.  Not sure if this is required but @diracdeltas mentioned she sees some messages still about leaked events when there are a lot of tabs.

**Comment by jonathansampson** [comment]
Closing, as it has been well over a year with no movement on this.

If you still feel that this is an issue, please re-open.
