### ISSUE TITLE
netflix doesn't play any videos

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#340]
OS X

Always shows:

<img width="832" alt="screenshot 2016-01-26 14 35 17" src="https://cloud.githubusercontent.com/assets/5495083/12592394/3ae6ae68-c43a-11e5-8932-85f6d4ad600e.png">

**Comment by bbondy** [comment]
Looks like we can get this support via a pepper plugin here:
https://github.com/atom/electron/issues/2085

**Comment by rob-blasetti** [comment]
Works fine on my Netflix now, i'm using OS X El Capitan

**Comment by Frulko** [comment]
Could you share the part of your code that work between electron and netflix ? 
I've tried several times but i got the same error each time.. 

Thanks !

**Comment by bbondy** [comment]
Duping to #468
