### ISSUE TITLE
Brave fails with segmentation fault when closed normally

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3401]
**Describe the issue you encountered:**
After I close brave I get message that Brave not existed ok and failed with segmentation fault.

Looking in the debug output I can see:

```
Failed to get crash dump id.
Report Id: OK
[1]    3870 segmentation fault (core dumped)  brave
```

I can provide core dump if needed to someone, I just don't want to upload it here, since it has sensitive data and ledger logs.

**Expected behavior:**

Brave should exit normally.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Fedora 24
- Brave Version:
0.11.6-beta 3

- Steps to reproduce:
    1. Open Brave and browse normally
    2. Close Brave from the top right X button
    3. Shortly after you will get notice that Brave has crashed

- Screenshot if needed:

<img src="https://s15.postimg.org/g84sb8cyj/Screenshot_from_2016_08_25_11_07_10.png"/>

- Any related issues:
#3398 

cc @bbondy @diracdeltas

**Comment by darkdh** [comment]
I think this is a duplicate of https://github.com/brave/browser-laptop/issues/3394

**Comment by Sh1d0w** [comment]
Ok thanks, closing this will add comment in the other issue, that it is not only under macOS.
