### ISSUE TITLE
Unable to select autofill form suggestion by pressing down arrow key

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3402]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Autofill form suggestion not able to select by using the arrow keys

**Expected behavior:**
User should be able to select the suggestion by pressing the down arrow key.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Beta 3

- Steps to reproduce:
    1. Enable form autofill from pref menu
    2. Enter userid on a site to cache the form fill value for the field
    3. Revisit the site or any other site with the login field
    4. Click on the login field for the form fill to load the suggestion
    5. Pressing down arrow key doesn't select the form fill suggestion.

Current behaviour on all browsers is it automatically selected when the down arrow key is pressed.

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
Possible duplicate #1302 #3400

**Comment by srirambv** [comment]
Not really. I can see the suggestion right below the field but I can't select it by using the down arrow key. 
Alignment is proper but keyboard selection doesn't work. at least on Windows 10.

**Comment by darkdh** [comment]
I think it duplicates #1302

**Comment by srirambv** [comment]
Confirmed Duplicate. Closing
