### ISSUE TITLE
Manage Autofill Data should be disabled if Autofill switch is off

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3404]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Manage Autofill Data should be disabled if Autofill switch is off

**Expected behavior:**
Manage Autofill button should be enabled only when Autofill is enabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 3

- Steps to reproduce:
     1.
     2.
     3. 

- Screenshot if needed:

- Any related issues:

cc: @darkdh @bsclifton

**Comment by darkdh** [comment]
I don't think this is necessary. 
Take Chrome as an example, the option is always there no matter on or off.
<img width="459" alt="screen shot 2016-08-25 at 19 52 15" src="https://cloud.githubusercontent.com/assets/11330831/17968154/cb7042e0-6afd-11e6-97e3-67acda81f242.png">
---
<img width="454" alt="screen shot 2016-08-25 at 19 52 05" src="https://cloud.githubusercontent.com/assets/11330831/17968158/d2a7e98c-6afd-11e6-8930-5bb8cebf3fa1.png">

**Comment by bbondy** [comment]
ya it's ok to leave it as is, thanks.
