### ISSUE TITLE
Add urban dictionary as a search engine / shortcut

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3408]
Similar to our existing search engine list and shortcuts, it would be great to add support for Urban Dictionary

Proposed shortcut could be 'ud'

Search URL would be:
https://www.urbandictionary.com/define.php?term={searchTerm}

**Comment by bbondy** [comment]
I don't have objections but just passing by some more people in case there's a problem I'm not thinking of. We should get in some normal dictionaries too though first.

@bradleyrichter @BrendanEich

**Comment by bradleyrichter** [comment]
We block UD on our kids devices. I think auto-complete based on UD match could be a big problem?

**Comment by bsclifton** [comment]
Actually, that is a great point @bradleyrichter :smile:

Maybe a better solution would be user-customizable search engines. If **we** add them to Brave, it's like we're indirectly endorsing it.

If that makes more sense, I can update this ticket to capture information about that

**Comment by bradleyrichter** [comment]
@bsclifton We need 2 new issues. 

1. add the ability to edit the URL of the default engine list. (ala chrome)

2. Allow adding your own engine.


The UI will support both in terms of space but needs to be detailed out.

**Comment by bsclifton** [comment]
case 1 might be covered by https://github.com/brave/browser-laptop/issues/1103
case 2 is covered by https://github.com/brave/browser-laptop/issues/3053

Closing this issue :smile:
