### ISSUE TITLE
SiteHacks: doc needed to define task categories

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-laptop#3413]
We want Sitehacks across platforms.
iOS would need a meta-data file (JSON for instance) that describes urls and `Actions` (and actions would have action-specific properties).
`Actions` needs to be an enumeration, such as:
- inject js (before/after page load)
- modify cookie
  • redirect url

Not all of these are implementable on iOS, but most will be. Some of these actions can use js from laptop to implement, but some will have zero commonality with other platforms in terms of implementation.

see also https://github.com/brave/browser-laptop/blob/master/js/data/siteHacks.js

cc @bridiver

**Comment by bridiver** [comment]
what kinds of hooks do you have in ios? This is what we're working with on the laptop side https://developer.chrome.com/extensions/webRequest
we normally do one of the following:
1. cancel the request
2. redirect the request
3. alter the headers
4. run js on page load/end

**Comment by garvankeeley** [comment]
* webview hooks: inject JS at non-beginning (first opportunity to inject is after page has started loading, so consider the injections as at-end, but that is deceiving, webview end loading is a fuzzy concept in UIWebView public API).
* networking hooks: cancel request, redirect request, certain types of header modification (not all header key/vals are maintained when we modify, the iOS networking layer we have to use is either overwriting or selectively copying the key/value pairs in header modifications), return fake data for request

Header modifications is an area we could define more clearly for iOS use.
