### ISSUE TITLE
Redfin website doesn't work properly

### ISSUE THREAD

**Issue by xiaohanzhu** [brave/browser-laptop#3417]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Go to redfin.com website, search an area, for example Palo Alto, a list of properties come up.  If you click on any of the property to look at the details of the listing, the browser will not trigger loading that page
**Expected behavior:**
Property details page shall load
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.5
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
The issue seems to have been fixed.
