### ISSUE TITLE
Mouse-wheel-scrolling over a textarea expando corner resizes textarea

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3419]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I scroll a page using the two-finger touchpad scroll, if the cursor is over a textarea's expando corner, the textarea resizes instead of the page scrolling.

**Expected behavior:**
The scrolling action should be ignored by the textarea expando.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.11.5
- Steps to reproduce:
  1. Open a scrollable page with a textarea.
  2. Put the mouse cursor over the textarea's lower right corner that is used to resize the textarea.
  3. Scroll up and down until you see the issue.

**Comment by luixxiul** [comment]
I think this issue can no longer be reproduced. Please let me know if it is, thanks 😄
