### ISSUE TITLE
nexusmods.com ads removed, but not replaced.

### ISSUE THREAD

**Issue by Aidoboy** [brave/browser-laptop#342]
Only shows their please-don't-block-our-ads banner.
![No one likes ads.](http://staticdelivery.nexusmods.com/contents/images/pub_horizontal.png)

**Comment by Aidoboy** [comment]
Appears to be fixed in v0.7.9dev

**Comment by Aidoboy** [comment]
Wait, now it isn't working. Weird.

**Comment by diracdeltas** [comment]
I see the don't-block-ads banner too. Is that expected? @bridiver

**Comment by bridiver** [comment]
I see it in the leaderboard at the top, but not in the box at the bottom. It most likely depends on the source of the ad that would have been displayed. Slashdot also re-replaces some ads. I'll look to see what they are doing.

**Comment by bridiver** [comment]
Slashdot has something similar when they are serving "native" ads. If the ads are direct sold or come from a trusted source they can placed in a same-origin iframe that has access to the parent DOM. In this case the ad creates a hidden div in the parent body and a script right after iframe looks for that div. If it doesn't exist, the div around the ad is replaced and you get the image above.

**Comment by bridiver** [comment]
We don't want to deal with these on a case-by-case basis, but we are working on some ideas for a general solution to the problem. We could potentially tie into the javascript DOM manipulation functions and actively prevent manipulation of detected ad slots

**Comment by bridiver** [comment]
We could also potentially use mutation observers to effectively freeze portions of the DOM by automatically undoing any changes
https://addyosmani.com/blog/mutation-observers/

**Comment by luixxiul** [comment]
Confirmed nexusmods.com ads were being replaced. Closing for the moment.
