### ISSUE TITLE
Enabling HTTPS Everywhere fails to load suggested items on a product page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3422]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
a. Enabling HTTPS Everywhere fails to load suggested items on a product page 
b. Suggested Items listed inside a blown up div container

**Expected behavior:**
a. Should display the suggested items on the product page. 
b. Should show a thumbnail version of the image and no details of the product should be displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta3

- Steps to reproduce:
    1. Visit [Ebay.com](http://www.ebay.co.uk/itm/Samsung-UE40K5100-Indigo-40-Full-HD-LED-TV-Built-in-Freeview-HD-HDMI-USB-Ports-/142078975897?_trkparms=%26rpp_cid%3D5566d91fe4b079dd0797bf4b%26rpp_icid%3D57beb0cee4b06e3751ac0ff4)
    2. All images for suggested items (next to the selected product and below the product) blocked by enabling HTTPS everywhere
    3. Disable HTTPS everywhere all blocked images are loaded
    4.  

- Screenshot if needed:
a.  Brave
![image](https://cloud.githubusercontent.com/assets/17010094/17982708/0efc431c-6b01-11e6-9fbc-68e359eac39e.png)

Chrome/FF
![image](https://cloud.githubusercontent.com/assets/17010094/17982726/1cbf7686-6b01-11e6-806c-345133ab9af9.png)

b.
![image](https://cloud.githubusercontent.com/assets/17010094/17982984/3e973c02-6b02-11e6-8752-85d7d809101e.png)

![image](https://cloud.githubusercontent.com/assets/17010094/17982686/e7d49c6c-6b00-11e6-8c9b-c77d52e7592b.png)

- Any related issues: 
  #3302

**Comment by diracdeltas** [comment]
the images also show up if i set Allow Ads and leave HTTPS Everywhere on

**Comment by srirambv** [comment]
The set of blocked images are shown under both HTTPS Everywhere blocked items and Ad/Tracker. 

Under Ad/Tracker 
![image](https://cloud.githubusercontent.com/assets/17010094/18503009/92789dd4-7a52-11e6-839a-2544e9585f7b.png)

Under HTTPS Everywhere
![image](https://cloud.githubusercontent.com/assets/17010094/18503047/c3f34904-7a52-11e6-97d9-844dd537e095.png)

**Comment by luixxiul** [comment]
@srirambv will you please specify another URL? I cannot find the widget of the screenshot on the page.
