### ISSUE TITLE
Not able to copy 1password generated password with keyboard

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3425]
**Describe the issue you encountered:**

Using cmd+c does not copy my generated password from the 1password extension. 

**Expected behavior:**

After generating a password and selecting it you should be able to cmd+c to copy it.
- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS
- Brave Version:

0.11.5
- Steps to reproduce:
  1. Go to a site with a login
  2. Open 1password with cmd + \
  3. Generate a password
  4. Select the generated password and cmd+c to copy
  5. Paste it somewhere visible and notice you still have whatever you copied last in your copy buffer.
     <img width="596" alt="screen shot 2016-08-25 at 1 34 58 pm" src="https://cloud.githubusercontent.com/assets/490294/17985012/c3df2260-6ac8-11e6-9336-6f72a9eff4b9.png">

**Comment by bsclifton** [comment]
@jkup the UI that pops up is actually 1Password mini.  I'm curious why it's not able to copy (I verified also). Right clicking and picking "Copy" works as a work-around

Are we stealing the ctrl+c / cmd+c and not allowing 1Password mini to get the event?
