### ISSUE TITLE
consolidate state in app/ledger.js with appState

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3433]
there is a lot of state that is duplicated between `appState` and `ledgerInfo`/`publisherInfo` in app/index.js, which becomes confusing to keep in sync. this should be deduplicated somehow.

**Comment by bsclifton** [comment]
I'd like to propose taking this one step further: 
- creating a ledgerState
- refactoring code to be reducer friendly
- breaking up `app/ledger.js` into a utils and a state helper

I have an example that I spent maybe 20 minutes hacking on which shows some progress towards that goal.  Definitely curious what others think!
cc: @bbondy @bridiver @diracdeltas @mrose17 

https://github.com/bsclifton/browser-laptop/commit/bd9e1356a0e3c5819cad6dc88823d72a821420bc

Notice that with a reasonable amount of effort, we can pull most of the code out of `app/ledger.js` and into both a state helper (for methods manipulating state; eg: the reducers) and a utils class (business logic).  With the code broken out here, we can then begin the process of writing unit tests :smile:

**Comment by bridiver** [comment]
a separate ledger state would be going against the plan to consolidate into a single appState. We also want to move away from the json files and move things into the chromium user prefs storage which is already setup for cross-device sync. We can also bring in the history component to keep it out of the general preferences

**Comment by bsclifton** [comment]
@bridiver that makes sense- instead of ledgerState, these reducers could be manipulating appState 😄 Let me update the original post
