### ISSUE TITLE
Tab preview cancels after closing tab with close button

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3435]
Expected:

When you have located a tab you wish to close, the preview shows nicely on mouse over. As you click the close button, the next tab under the mouse cursor should be shown in preview - allowing you to confirm it is the right tab before you close it.

Current: 

Tab previews cancels when you close the first tab. The next tab is not previewed although you are hovering over the tab (and specifically the tabs close button.)

**Comment by cezaraugusto** [comment]
closing in favor of #7606
