### ISSUE TITLE
Implement cosmetic adblock filters

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#344]
This is partially implemented but we need to expose the support from the abp-filter-parser-cpp node module.

List of sites to check:
- reddit.com ads removed, but not replaced
- google search text ads neither removed nor replaced

**Comment by fitrixmobileadmin** [comment]
Ads are appearing in brave mobile.  The only way I can turn them off is to turn scripts off in the badge, which isn't a long term solution.

**Comment by jonathansampson** [comment]
@bbondy Thoughts on solving via the approach in https://github.com/brave/browser-laptop/pull/7525? This issue _feels_ like it may need a more robust solution.

**Comment by bbondy** [comment]
I think that's ok as a temporary thing but we want something different for the generalized approach and understanding / converting ABP filter syntax for css rules.  (Most of that is already supported just not used today)

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/adblock-isnt-good/1705

**Comment by jonathansampson** [comment]
One limitation in using the manifest (presently) is that we aren't checking if the user has _Replace Ads_ enabled. We'll want to check that before loading any styles to hide elements, or scripts to remove nodes.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/gmail-mail-promotion-tab-ads-not-block-by-brave-browser/7546

**Comment by quesada** [comment]
I see adword ads on google search results. The first time I see them in 15 years using an adblocker in other browsers. Considering that this is your UVP, I expected better.

**Comment by dumptyd** [comment]
This seems to be a somewhat known bug but I see empty spaces on every site where the ads would be.
This is what reddit and youtube look like on Brave.

![image](https://user-images.githubusercontent.com/16368429/34576188-3404a238-f1a3-11e7-9cda-8be537d9916e.png)

![image](https://user-images.githubusercontent.com/16368429/34576438-eb85d8f0-f1a3-11e7-9a94-69e70c1a5352.png)

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/the-boxes-dont-leave/17781

**Comment by Leon422** [comment]
Please fix this. It negates a large part of the reason to block ads in the first place :(

**Comment by mgonto** [comment]
+1

**Comment by bsclifton** [comment]
This is underway currently in Brave Core by @Snuupy! Since this won't be addressed in our current codebase (Muon), I'm going to close this issue as `wontfix`

For more info about the fix we ARE doing, subscribe to https://github.com/brave/brave-browser/issues/94 and watch for updates 😄
