### ISSUE TITLE
Existing bitcoin wallet address is not displayed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3440]
**Describe the issue you encountered:**
On Windows, existing bitcoin wallet address is not displayed on the dialog which appears by clicking "Add Funds" on about:preferences#payments. 

**Expected behavior:**
The bitcoin wallet address should be displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7 and 10

- Brave Version: 0.11.6 Beta4

- Steps to reproduce:
    1. Move your brave folder temporarily and start the browser
    2. Open Payments on about:preferences
    3. Enable the payment and click "create wallet"
    4. Click "add funds"

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/17995197/c22adf90-6b9a-11e6-886c-b01565bd3bd9.png)

The address is expected to be displayed around "copy this link".

- Any related issues:

Setting a milestone.

**Comment by alexwykoff** [comment]
Confirmed this is isolated to Windows. OS X and Ubuntu displayed the wallet address appropriately.

**Comment by diracdeltas** [comment]
https://github.com/brave/browser-laptop/commit/5e0b6793b26abb513c080fb92a9cf2f2728a4e62 changes it so that an error message is shown if there is no address available. that doesn't solve the underlying issue of why there is no `paymentURL` property on windows though.

**Comment by diracdeltas** [comment]
@mrose17 any idea why `paymentURL` would be undefined only for windows? maybe intermittent failure related to ledger server?

**Comment by diracdeltas** [comment]
@luixxiul could  you open your `session-store-1` file and copypaste the `ledgerInfo` value here? (or DM me on slack)

**Comment by luixxiul** [comment]
It seems to be undefined: ``"ledgerInfo":{}``.

**Comment by mrose17** [comment]
@luixxiul - please find the file `ledger-state.json` and DM it to @diracdeltas ... i think that @bsclifton knows where to find that on windows

**Comment by luixxiul** [comment]
@mrose17 ok, sent it to @diracdeltas and you.

**Comment by luixxiul** [comment]
Confirmed it has been fixed on 0.11.6 Beta5 :-)
