### ISSUE TITLE
about:preferences#payments should be implemented

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3441]
**Describe the issue you encountered:** I would like to see ``about:preferences#payments`` implemented like ``about:preferences#tabs``.

- Brave Version: 0.11.6 beta4

- Any related issues:

**Comment by willy-b** [comment]
Just FYI, it works right now with `about:preferences#publishers` (a holdover of old label).

**Comment by mrose17** [comment]
just fyi, i believe that it is visible as `about:preferences#publishers` ... that ought to change.

**Comment by luixxiul** [comment]
I see, is it not fixed yet?

**Comment by willy-b** [comment]
Fixed in my open PR #3446
