### ISSUE TITLE
Add an option to temporarily disable mixed content protection

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#3443]
Currently we cannot access resource like flash video of mixed content site (ex. https://forgetfulbc.blogspot.com/2016/08/lastweek-t3.html) and it will be upgraded to https by https everywhere so downgrade to http for this site is not working.

Firefox and Chrome provide an option to disable the protection temporarily
---
Firefox
<img width="345" alt="screen shot 2016-08-26 at 13 15 34" src="https://cloud.githubusercontent.com/assets/11330831/17995744/cc30fb72-6b96-11e6-840c-1a22ade7e14d.png">
<img width="334" alt="screen shot 2016-08-26 at 13 16 48" src="https://cloud.githubusercontent.com/assets/11330831/17995746/d3327220-6b96-11e6-8f9d-09eeab0c8def.png">

Chrome
<img width="264" alt="screen shot 2016-08-26 at 13 22 31" src="https://cloud.githubusercontent.com/assets/11330831/17995757/e7b1c73c-6b96-11e6-961d-dde50d94b730.png">
<img width="433" alt="screen shot 2016-08-26 at 13 31 34" src="https://cloud.githubusercontent.com/assets/11330831/17995762/edb4290e-6b96-11e6-9ec0-3ebe58452236.png">

cc @diracdeltas

**Comment by alexwykoff** [comment]
Test Plan:
Visit https://mixed-script.badssl.com/ and click the urlbar lock to
temporarily allow run insecure content and the background color will be red.

**Comment by luixxiul** [comment]
@darkdh is there any way of resetting the setting from the lock icon?

**Comment by luixxiul** [comment]
1. Open https://badssl.com
2. Click "mixed-script"
3. Allow to load unsafe scripts
3. Go back to the home page
4. Click "mixed-script" again

You'll get "secure connection" and the red background at the same time.

**Comment by darkdh** [comment]
@luixxiul , we need to restart the browser to reset the setting for now
