### ISSUE TITLE
Sponsored Ad links not blocked on PCAdvisor site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3448]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Sponsored Ad links not blocked on PCAdvisor site

**Expected behavior:**
All ad links should be blocked
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 Dev Beta 4
- Steps to reproduce:
  1. Visit [PCAdvisor site](http://www.pcadvisor.co.uk/)
  2. Scroll down to the end of page shows the sponsored ad link. 
  3. ABP currently blocks the sponsored ads on sites
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18004177/15304628-6b8a-11e6-8d0f-3b2c5b82af49.png)
- Any related issues:

**Comment by luixxiul** [comment]
The issue looks to have been fixed.
