### ISSUE TITLE
Enabling HTTPS everywhere breaks Virginmedia.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3449]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling HTTPS everywhere breaks Virginmedia.com. Throws certificate error

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 4

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18005727/b1e5b436-6b93-11e6-91a5-e831eb372002.png)

- Any related issues:

**Comment by darkdh** [comment]
This is the certificate problem of the site. You can test it with Firefox or Chrome and they will also got certificate verification error.
The subject name or subject alternative name should be `virginmedia.com` or users can only access it through `www.virginmedia.com` over https.

**Comment by srirambv** [comment]
Closing the issue.
