### ISSUE TITLE
child "platform" fails (on Ubuntu 14.04)

### ISSUE THREAD

**Issue by stuartlangridge** [brave/browser-laptop#345]
Error message output to console after `npm start`:

    { statusCode: 400,
      error: 'Bad Request',
      message: 'child "platform" fails because ["platform" must be one of [winx64, osx]]',
      validation: { source: 'params', keys: [ 'platform' ] } }

There is no indication of what caused this, afaict; it may have appeared while browsing theguardian.com.

**Comment by Tribex** [comment]
Same on Ubuntu 15.10 here.

**Comment by iamtjg** [comment]
I have not been able to tie it to anything directly either yet.  Once this error occurs new sites/pages do not render but sites already loaded continue to function.

**Comment by luixxiul** [comment]
Does this issue still exist for the latest version?

**Comment by luixxiul** [comment]
Not reproducible on Ubuntu 14.04, closing

**Comment by Tribex** [comment]
Just for the record, unable to reproduce on 16.04.
