### ISSUE TITLE
Ledger logging happens frequently and unrequested on Linux terminal.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3452]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After launching from the terminal on Ubuntu, the ledger frequently post log info on the terminal. 

**Expected behavior:**
Ledger logging should occur when the user requests it. Preferably via an environment variable. Otherwise, the terminal should be quiet.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Ubuntu

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Install the latest build on Ubuntu. (gdebi install was used during testing)
    2. Launch from the terminal.
    3. Conduct operations in the browser, occasionally view the terminal.

- Screenshot if needed:
<img width="435" alt="screen shot 2016-08-25 at 11 40 24 pm" src="https://cloud.githubusercontent.com/assets/1434040/18008450/c28eca82-6b6d-11e6-9239-34d7f4541a25.png">

- Any related issues:

**Comment by willy-b** [comment]
I can confirm I see this too. Was talking about it last night with @mrose17. It came in with the update to ledger-client v0.8.46  (#3397)

**Comment by diracdeltas** [comment]
@mrose17 fixed in 62669207af0a3fa1b8b29c1e4fa0c0e6fbe0f7b7? please use github autoclosing keywords to autoclose issues: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by mrose17** [comment]
fixed in https://github.com/brave/browser-laptop/commit/55c0e10ca3884b02a2e94d9250a5d8791f27a502 ... if not, @alexwykoff please let me know!
