### ISSUE TITLE
Bookmark folders are appearing in browser history

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3453]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When creating a bookmark folder, it appears in browser history and cannot be cleared. 

**Expected behavior:**
1. Bookmarks and folders should not appear in history.
2. If a user decides to clear history, all items should be cleared. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Open the about:history page.
    2. Create a bookmark folder.
    3. Observe the history, attempt to clear the history.

- Screenshot if needed:
![bookmark_folder_in_history](https://cloud.githubusercontent.com/assets/1434040/18008831/596c2cdc-6b6f-11e6-85e6-c0486bfff4e8.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Great catch! :smile: Working on a fix...

**Comment by bsclifton** [comment]
Fixed w/ https://github.com/brave/browser-laptop/pull/3459
