### ISSUE TITLE
Autofill - Add new entry buttons are not functional

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3455]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On about:autofill, I attempted to add new information. The buttons had no associated action.

**Expected behavior:**
The buttons should open the appropriate forms to add and edit data.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Using the latest build, and with a clean system(no prior data), open about:autofill
    2. Attempt to use either of the add buttons.

- Screenshot if needed:
![autofill_buttons](https://cloud.githubusercontent.com/assets/1434040/18009986/4380e34a-6b74-11e6-8567-6e5d9d3dd101.gif)

- Any related issues:

**Comment by bridiver** [comment]
this works fine for me in master

**Comment by alexwykoff** [comment]
After moving the Application Support/brave folder away and back, it appears to have resolved itself. Closing this since repro isn't happening.
