### ISSUE TITLE
Brave doesn't always detect when another instance is running

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3456]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
It is possible to open several instances of Brave (packaged build and dev for instance) which will cause strange behavior. This can also happen if a process fails to quit properly. 

**Expected behavior:**
We should use other methods to detect running processes (lock files on user data DBs maybe?) to prevent this from happening and notify the user

**Comment by bbondy** [comment]
we currently purposely don't enable the single instance on dev mode. 
I think the right task here is to allow it and to use different chromium profiles with different branding colors to differentiate.

**Comment by bridiver** [comment]
several files are shared across chromium profiles so we would need a different user data dir (subdirectory?), but there is also an issue when processes shutdown correctly

**Comment by bbondy** [comment]
just a new top level dir like `~/Library/Application Supportion/brave-debug`

**Comment by bridiver** [comment]
yea, but I think within each dir we should watch for multiple processes running. Some of the chrome dbs have lock files

**Comment by bbondy** [comment]
have you seen this happening outside of debug + release where we purposely allow it?

**Comment by bsclifton** [comment]
Windows for sure won't let you run more than 1 instance  other than the debug scenario :smile: (I tried REALLY hard to get more than 1 when dealing with https://github.com/brave/browser-laptop/issues/3089)

I can't seem to find how to open more than 1 version of Brave on Mac, other than the debug one too

**Comment by bridiver** [comment]
It happens when you have a process that doesn't shutdown. Hard to replicate, but I've seen it happen

**Comment by luixxiul** [comment]
Could I know what the status of this issue is?
