### ISSUE TITLE
Brave Freezes on Arch Linux when hitting 'space' or '@'

### ISSUE THREAD

**Issue by SaffronSnail** [brave/browser-laptop#3461]
**Did you search for similar issues before submitting this one?**
Yes, I did not find anything similar

**Describe the issue you encountered:**
When entering text into a text field (for example, a username box or an email message), sometimes when I hit 'space' or '@' (it's possible that other special characters will trigger it too) the tab freezes. It doesn't respond to any scrolling, clicks, etc. The rest of the tabs are unaffected, and if I close the tab and re-navigate to the page then everything works fine again. Interestingly, while the tab is open shortcuts not associated with that specific tab (such as ctrl-t to open a new one) also cease to work until I manually click on another tab or the 'x' of the frozen tab.

**Expected behavior:**
The character being entered in the text field instead of the tab freezing
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Arch Linux, [compiled from the AUR](https://aur.archlinux.org/packages/brave/).
- Brave Version:
  For some reason clicking the 'about' button in the menu doesn't work (should I file another report for that), but according to my system the version is 0.10.3-1
- Steps to reproduce:
  1. Open the browser
  2. Navigate to any web page with a text box (for example, compose an email in gmail)
  3. Hit non-letter keys and hope that it freezes (I haven't found a way to make it 100% consistent)

**Comment by Liunkae** [comment]
Is this still a problem?

**Comment by SaffronSnail** [comment]
I just did a quick check on gmail, and it seems like the issue has been resolved since I posted it.

**Comment by Liunkae** [comment]
Great! Closing.
