### ISSUE TITLE
Esc handler changes windowed / fullscreen mode depending on permissions

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3464]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When escaping from fullscreen video, the browser will return to windowed mode if the permissions have been permanently set, but will shift the browser to fullscreen mode if the permission was allowed only once.

**Expected behavior:**
If a user starts in windowed mode, they should return to windowed mode when they escape from a fullscreen video.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.11.6 pre-beta4

- Steps to reproduce:
    1. Open a video in full screen ( twitch.tv was what was used during testing), allow for permission once.
    2. Use the Esc key.
    3. Observe the window status.

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
that commit also fixes exiting webview fullscreen on tab change and https://github.com/brave/electron/commit/fd4b96735960d602719ec820ef5c81bcd0bede8c fixes exiting on tab close
