### ISSUE TITLE
display dark grey verified icon for verified publishers

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3467]
now that https://github.com/brave/browser-laptop/issues/3198 is implemented. we don't currently have any verified publishers (that i know of), but we can set brave.com as verified for testing purposes.

**Comment by mrose17** [comment]
@diracdeltas - perhaps this issue should be closed and moved over to the `ledger` repo...

we can test the code in the browser, but not until the ledger actually reports the verification status...

**Comment by diracdeltas** [comment]
@mrose17 https://github.com/brave/browser-laptop/issues/3198 is the issue for the ledger to report verification status, i thought. this is just the front-end issue.

**Comment by bsclifton** [comment]
Like @diracdeltas said, I think this could be used just to track adding a CSS class to a verified publisher (if the backend provides info that it's verified). :smile: Maybe the backend could be stubbed to always return verified for brave.com until the code is implemented

**Comment by bsclifton** [comment]
Also curious what this would look like- would it be like a Twitter verified icon? :smile: 

cc: @bradleyrichter

**Comment by bradleyrichter** [comment]
Changing it to a thumbs up to avoid confusion with shields.

![image](https://cloud.githubusercontent.com/assets/13509546/18332456/8d1c4782-751b-11e6-9105-a966439231fc.png)

**Comment by bradleyrichter** [comment]
![image](https://cloud.githubusercontent.com/assets/13509546/18332802/7283d324-751e-11e6-9e71-1900d41ebbd1.png)

**Comment by bbondy** [comment]
Could we use some kind of a verified badge kind of like twitter? Something that people are already familiar with, to me thumbs up doesn't scream verified.  I think checkmark at least. Thumbs up means more "I like this" to the world of facebook users.

**Comment by bsclifton** [comment]
Agree w/ @bbondy (note that I also thumbs uped his post :stuck_out_tongue_winking_eye: )

**Comment by bradleyrichter** [comment]
Better?

![image](https://cloud.githubusercontent.com/assets/13509546/18400172/8a62cb46-7689-11e6-8759-a70d0510810d.png)

I don't want to use a shield which feels wrong.

I don't want use a checkmark as it may be confused with a UI button element.

**Comment by bbondy** [comment]
that's better yep

**Comment by bradleyrichter** [comment]
I would like to add a white checkmark to the center of this "certificate" icon.

(when we get to it)

( @jkup has a recipe already)

**Comment by jkup** [comment]
Yep I've done one already for bitcoin.. I'll tackle this ticket if that's cool with everyone

**Comment by diracdeltas** [comment]
@jkup sgtm. since no publishers are verified currently, i think we should mock-verify brave.com for now

**Comment by jkup** [comment]
@diracdeltas sgtm how can we mock-verify brave? Can @mrose17 do it manually?

**Comment by diracdeltas** [comment]
yeah it would be better for ledger back-end to report it as verified; if that is too much work for some reason, you can just set it in the front-end

**Comment by bradleyrichter** [comment]
we can mock-verify brianbondy.com too.

**Comment by mrose17** [comment]
now that https://github.com/brave/browser-laptop/commit/ad9844254e387ea953e097abeb9685df5029686f is committed to master, who will volunteer to fix the browser CSS...
