### ISSUE TITLE
Monthly budget in payments  misaligned

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3476]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Monthly budget in payments  misaligned

**Expected behavior:**
Amount dropdown should be aligned below monthly budget label

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Beta 5

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18027973/e14ad0f4-6c69-11e6-9483-33861cc90378.png)

- Any related issues:

**Comment by diracdeltas** [comment]
fixed by e7ecd568552b47d73a0e678e1ea841b5153dab6f
