### ISSUE TITLE
too much vertical space for about:preferences#payments

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3483]
we waste a lot of screen real estate with the spacing between each row. can we tighten it up?

if not, just close this without a fix.
![1](https://cloud.githubusercontent.com/assets/400552/18029238/8ea48150-6c47-11e6-9b1e-c87ccb487a4d.png)

**Comment by bradleyrichter** [comment]
Should be an easy fix. Keep open...

**Comment by bradleyrichter** [comment]
There are some cascading issues with the way this was set up. 

(fixing the line spacing breaks other things so this needs to be split apart, and defined separately with the line-height property.)

I think we need @jkup to look at this one too.

**Comment by bradleyrichter** [comment]
@jkup @mrose17 I improved this with #3494 .
