### ISSUE TITLE
clipboard icon on add funds popover probably needs to be moved

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3484]
the clipboard icon should probably go to the left of the bitcoin address with a little extra horizontal size for the pop-over...
![2](https://cloud.githubusercontent.com/assets/400552/18029256/e68d3e2a-6c47-11e6-98b0-da8bbe6d92ba.png)

**Comment by mrose17** [comment]
related to https://github.com/brave/browser-laptop/issues/3629

**Comment by alexwykoff** [comment]
Marking this as 'no qa needed' since this particular dialog no longer exists.
