### ISSUE TITLE
Payment History popover probably needs a little more attention

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3485]
it seems sort of "drab" in comparison to the rest of the graphic treatments...

![3](https://cloud.githubusercontent.com/assets/400552/18029276/659c57c8-6c48-11e6-95bb-416d6b57533b.png)

**Comment by bbondy** [comment]
@bradleyrichter it looks like there's missing padding on the bottom of that popup

**Comment by luixxiul** [comment]
Test Plan:
1. Disable the ledger
2. run `npm run add-simulated-payment-history` some times
3. Enable the ledger
4. Click "View Payment History..."
5. Make sure the dialog like this appears:

<img width="736" alt="screenshot 2016-12-15 3 36 37" src="https://cloud.githubusercontent.com/assets/3362943/21195619/e1ad79e8-c277-11e6-8d5d-d5d428b9247e.png">
