### ISSUE TITLE
Autofill - Values are vacated

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3491]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The autofill values have suddenly and mysteriously been vacated.

**Expected behavior:**
The autofill values should persist until intentionally deleted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Ubuntu. I believe it is isolated to Linux, but not 100% sure.

- Brave Version:
0.11.6 pre-beta5

- Steps to reproduce:
    1. Create autofill values.
    2. ???

- Screenshot if needed:
<img width="1122" alt="screen shot 2016-08-27 at 4 56 07 pm" src="https://cloud.githubusercontent.com/assets/1434040/18030496/58ec782a-6c7d-11e6-8efd-529e7dc9a0f8.png">

- Any related issues:

**Comment by darkdh** [comment]
Did you remove `~/Library/Application Support/brave/Web Data` manually?
This will happen when you remove the database(Web Data) and the session data still keeps the guid of the entries.

**Comment by alexwykoff** [comment]
I was able to repro the issue that way, however, that was not the action I took originally.
 
We can move this out of the milestone / close it as DNR.

**Comment by bbondy** [comment]
Sounds like we need to find STR that doesn't involve clearing data, can you try to get them before closing this out @alexwykoff ?

**Comment by alexwykoff** [comment]
I've fiddled with this quite a bit and cannot repro. It's a mystery.

Closing DNR

**Comment by alexwykoff** [comment]
Finally found the STR:
1. Create autofill values in a prior version (ex 0.11.6 beta6)
2. Leave about:autofill open, quit Brave
3. Open a newer version (ex RC1), about:autofill should open automatically

**Comment by alexwykoff** [comment]
Actually the STR are simpler:
1. Create autofill values in a prior version (ex 0.11.6 beta6)
2. Quit and reopen Brave
3. Check about:autofill

**Comment by alexwykoff** [comment]
![autofill_vacated](https://cloud.githubusercontent.com/assets/1434040/18114573/b515471c-6efd-11e6-8848-9dfbdaf7e3de.gif)

**Comment by bbondy** [comment]
prior version also means RC1 right?

**Comment by darkdh** [comment]
STR on master with latest electron
1. rm `~/Library/Application Support/brave`
2. The database cannot be initialized error on console

**Comment by darkdh** [comment]
Thanks to @bridiver ,the database initialized problem is fixed by https://github.com/brave/electron/commit/18496a42889f895681f94516bb521a62bf15834b. 
I will add a PR for deleting non-existed entry automatically

**Comment by darkdh** [comment]
**QA verify steps**
---
-  Test folder creation

 1.  Remove `~/Library/Application Support/brave`
 2. Launch brave
 3. Add autofill data
 4. Quit brave and relaunch it
 5. The autofill data should exist

- Test automatically remove invalid data entry
 1. Add autofill data
 2. Quit brave
 2. Remove `~/Library/Application Support/brave/Web Data`
 3. Launch brave
 4. The autofill data added shouldn't exist

**Comment by bbondy** [comment]
Fix is in brave/electron 1.3.8 also make sure electron version appears as such in about when testing.  Also see Anthony's steps to test above.
