### ISSUE TITLE
Linux application name changes to a url and does not revert.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3492]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After creating a bookmark, I noticed that the application name for Brave changed to the URL which was bookmarked. 

**Expected behavior:**
The name should remain 'Brave'
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Ubuntu. 
- Brave Version:
  0.11.6 pre-beta5
- Steps to reproduce:
  1. Install the latest build on Ubuntu.
  2. Bookmark a site.
  3. Search for the Brave app via the launcher.
- Screenshot if needed:
  <img width="542" alt="screen shot 2016-08-27 at 4 12 25 pm" src="https://cloud.githubusercontent.com/assets/1434040/18030704/2db7a950-6c86-11e6-9edd-a7de06fcd854.png">
- Any related issues:

**Comment by bbondy** [comment]
I think it shows the current window title which is the title of the url, and since there is no title it shows the URL.  This is probably the same as all past issues so I don't think we have to block on it.  I'm assuming the application is open?

Could you confirm that's the case.
Also what is the expected result, and how does chrome/firefox differ?

**Comment by alexwykoff** [comment]
After further investigation, it turns out that an Ubuntu user has an 'Add to Dash' option from the context menu of the launcher. 
This creates a file .local/share/applications/brave.desktop
The content of the file is as follows:
`test@test:~/.local/share$ cat applications/brave.desktop 
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Preferences
Icon=brave
Path=/home/test/BraveQA/0.12.3/rc1
Exec=/usr/share/brave/brave
StartupNotify=false
StartupWMClass=brave
OnlyShowIn=Unity;
X-UnityGenerated=true`

The Name variable is being set to the current tab, it should be set to 'Brave'.
The Path variable is being set to the location of the .deb file which was used for installing, it probably should be set to the location of the application proper.
`test@test:~/.local/share$ which brave
/usr/bin/brave
`
