### ISSUE TITLE
Online Poll content not loaded when Ad/Tracker is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3514]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Online Poll content not loaded when Ad/Tracker is enabled

**Expected behavior:**
Should load the blocked content
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 Dev Beta 6
- Steps to reproduce:
  1. Enable Ad/Tracker and visit [B92](http://www.b92.net/eng)
  2. Poll content is blocked.
  3. Disable Ad/Tracker on the page poll content gets loaded
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18044183/6943064c-6dc4-11e6-8b87-0293178331ac.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18044189/79720572-6dc4-11e6-8533-1f24d2db443a.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18044209/90acb07a-6dc4-11e6-8f0d-ff9ac2d0d399.png)
- Any related issues:

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/2794 (polldaddy)

Also the issue is discussed here: https://community.brave.com/t/discussion-polldaddy-com/10093 ;-)
