### ISSUE TITLE
Enabling bookmarks changes page view in popup windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3515]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling bookmarks changes page view in popup windows

**Expected behavior:**
Enabling/Disabling of bookmark toolbar should not change the page view of popup window

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 6

- Steps to reproduce:
    1. Visit the [site](http://www.playradio.rs/) and click on Listen Live  
    2. Popup window appears where the page view changes if the bookmark toolbar is disabled/enabled
    3.

- Screenshot if needed:
![toolbar](https://cloud.githubusercontent.com/assets/17010094/18045333/42670b08-6dca-11e6-9ad7-11df568ebe87.gif)

- Any related issues:

**Comment by bbondy** [comment]
This is probably just because of a responsive view on the content size. Do you get the same result if you make the window smaller? If so then we should close this.

**Comment by srirambv** [comment]
Resizing the window doesn't have the same effect hence closing.

**Comment by bbondy** [comment]
Do you mean to say that resizing does have the same effect? Because that is the case under which this should be closed.

**Comment by srirambv** [comment]
Its happening only in the default size of the popup window. If the window is resized then there is no change in the page view.
