### ISSUE TITLE
Passwords are not saved using default settings

### ISSUE THREAD

**Issue by dandart** [brave/browser-laptop#3516]
**Did you search for similar issues before submitting this one?**
yes, but oddly people are suggesting this does work

**Describe the issue you encountered:**
I expected brave to save the passwords I had entered, but it isn't doing that despite having "Brave built-in" instead of "Do not manage my passwords".

**Expected behavior:**
For my passwords to be saved

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.11.5 (latest, checked no updates available)

- Steps to reproduce:
    1. go to a site that would require passwords
    2. enter credentials
    3. return later - no passwords saved

- Any related issues:
Not that I'm aware of.

**Comment by bbondy** [comment]
/cc @bsclifton @alexwykoff can you repro? If so we should block on this.
Possibly also related to an upgrade session store on an older version before the password manager drop down task, if so we should also block on this.

**Comment by bsclifton** [comment]
Checking this out now...

**Comment by bsclifton** [comment]
@dandart I'm curious- do you have any saved credentials? I know that you saved it, but I'm curious if perhaps an upgrade modified that data. Can you can pull up about:passwords to check?  Thanks 😄

**Comment by dandart** [comment]
Nope - "No passwords have been saved."
Despite me not being given an opportunity to say that I want to save any.

**Comment by bsclifton** [comment]
@dandart ah ok- so no passwords saved, but you were never given the opportunity to save any in the first place. Did you do any upgrades?

I'm on Ubuntu 16 trying to reproduce this; this is definitely an important bug to fix

**Comment by dandart** [comment]
I've done an upgrade from 0.9.x (had to do it manually as the update manager didn't spot it and there is no apt repository).
But since then I *think* I've cleared my dot files (not certain I restored the old ones).

**Comment by bsclifton** [comment]
Thanks for helping me understand more of the details- I believe I've found the issue 😄

**Comment by dandart** [comment]
Fantastic! If it won't be released for a while, I don't mind running from git.

**Comment by bsclifton** [comment]
@dandart here is a patch if you wanted to try applying manually 😄 
https://github.com/bsclifton/browser-laptop/commit/2a9fee709b407d550fa412375fdb4b1e9ae49d4e

If you get stuck or aren't sure on how to patch, let me know and I'll help get you a new executable with this patch

**Comment by dandart** [comment]
will it work if I just use your branch?

**Comment by bsclifton** [comment]
@dandart yes- you'll also get some new functionality that's pretty cool too :smile: (about:history page, form auto-fill, and more)

**Comment by bsclifton** [comment]
@dandart the issue is marked as closed, because we did implement a fix... but please let me know how it goes on your end after trying the above 😄 

When writing up a test plan, I can get the opposite case happening reliably during an upgrade (having a PW manager set, upgrading, then the built-in prompts show). However, I'm having trouble recreating your scenario

**Comment by dandart** [comment]
I haven't been able to verify just yet, as installation of the dev packages wanted me to install gnome-keyring, and even then was still looking for it, maybe I'm missing dev packages. Do you happen to know off hand which dev package I need?

**Comment by bsclifton** [comment]
@dandart yes- besides having nodejs 6.x, you'll need to run:
`apt-get install libgnome-keyring-dev build-essential`

I made sure you can build great on Ubuntu 16 w/ just having Node + those packages installed. The npm install should work great :smile:

**Comment by kathiedart** [comment]
Thanks - I was about to test but suddenly I've been prompted to save passwords

**Comment by bsclifton** [comment]
@kathiedart glad it started working again (especially since I could not find a way to reproduce your exact issue, only if you chose 1PW, etc)! Thanks again for your help finding this issue and helping provide info :smile:
