### ISSUE TITLE
Charts not loaded on AVDFN.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3518]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Charts not loaded on AVDFN.com

**Expected behavior:**
Should load charts

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, Ubuntu 16.04

- Brave Version:
0.11.6 Dev Beta 6

- Steps to reproduce:
    1. Visit [AVDFN.com ](http://uk.advfn.com/common/chart/js/DBI/DAX)and navigate to charts.
    2. HTML5 charts doesnt load if FP protection is enabled
    3. Other charts give Java Plugin error.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18050164/c6a2017e-6de4-11e6-8474-9a904ba5289c.png)

Java plugin running on Chrome/FF
![image](https://cloud.githubusercontent.com/assets/17010094/18050216/391debb4-6de5-11e6-8b11-63b9439d961b.png)

- Any related issues:
#2965(FP Protection)

**Comment by bbondy** [comment]
I don't think we're going to add support for the java plugin, so closing this as wontfix.
/cc @BrendanEich
