### ISSUE TITLE
Always delay tab preview

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#352]
Tabs appear to only preview themselves when the user has demonstrated intent by resting the cursor on the tab for a brief moment. Afterwards, anytime the cursor passes atop the tab, the preview is invoked. This causes a flashing effect that is unpleasing.

I can't imagine any harm in always requiring the initial delay to show intent.

**Comment by bbondy** [comment]
Please put comments for this in #142.  Will close this as a dupe. Thanks!
