### ISSUE TITLE
Provide a way to see cert details from the urlbar hanger

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3521]
This is how it looks currently:
<img width="436" alt="screenshot 2016-08-29 10 15 36" src="https://cloud.githubusercontent.com/assets/831718/18054418/c38c9dfe-6dd1-11e6-8b2e-c331e5463dd4.png">

Other browsers allow you to press a link that says details that shows the cert details.
We allow you to see cert details only when there's an error currently.

/cc @bradleyrichter for design, @diracdeltas for feedback, @darkdh for eventual implementation

**Comment by diracdeltas** [comment]
++. Chrome actually just opens the devtools Security panel when the link in the urlbar hanger is clicked, we could do the same if it's not too hard to hook up in Electron.

**Comment by bbondy** [comment]
I'd be ok with that route, but the dev tools popup is broken too @darkdh  tells me

**Comment by alexwykoff** [comment]
+1 from https://linkbubble.zendesk.com/agent/tickets/4993

**Comment by jonathansampson** [comment]
Resolved by #7319

![image](https://cloud.githubusercontent.com/assets/815158/26030818/6a7fc61e-3824-11e7-910e-d16efb421cbc.png)
