### ISSUE TITLE
overflowIndicator not appearing on bookmark toolbar if show only favicon option is enabled

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3525]
**Describe the issue you encountered:** ``overflowIndicator`` does not appear on the bookmark toolbar, if ``show only favicon`` option is enabled.

**Expected behavior:** ``overflowIndicator`` should appear.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version: 0.11.6 Beta6

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18058603/08f88316-6e50-11e6-9e20-44180b4c0773.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/3362943/18058605/09414a24-6e50-11e6-8e7a-265ed059b12f.jpg)

There are other favicons and folder icons next to the folder named "tempfolder" (which is omitted here).

Setting a milestone for now.

**Comment by bradleyrichter** [comment]
@bbondy can you make the folder icon smaller and dark grey while you are in there?

**Comment by bbondy** [comment]
@luixxiul you mentioned Brave Version: 0.11.5 Beta6, do you mean 0.11.6beta6?
Is this also an issue in 0.11.5?

**Comment by luixxiul** [comment]
sorry, my mistake. I mean **0.11.6** beta6.

**Comment by bbondy** [comment]
> @bbondy can you make the folder icon smaller and dark grey while you are in there? 

That should be done now too, used @darkGray

**Comment by luixxiul** [comment]
On Windows7 the indicator can be clipped.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18118404/8cb33a8a-6f8f-11e6-8d32-f47354d1b7f7.png)

**Comment by bbondy** [comment]
Should be a lot better than what it was at least, but what is the blue bar in the screenshot on the right?

I'm k with this being re-opened but I'm going to kick it out of 0.11.6 because it is not all cases and probably specific to types of bookmarks or something else.

**Comment by bbondy** [comment]
Windows border I guess? I think maybe the part that is unhandled is accounting only for the content width and not the window width..

**Comment by luixxiul** [comment]
yes it's the window border.

**Comment by bbondy** [comment]
since we're doing rc2 I'll get another fix for the border

**Comment by bbondy** [comment]
clearing testing labels so this will be re-tested.

**Comment by bbondy** [comment]
See test plan in both commits for testing.
