### ISSUE TITLE
background color of find bar is not consistent

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3526]
**Describe the issue you encountered:**
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18059029/ff4932aa-6e51-11e6-8c86-143d69a3eb69.png)
![clipboard02](https://cloud.githubusercontent.com/assets/3362943/18059096/49a44c54-6e52-11e6-879d-ea85b9b6897c.png)

**Expected behavior:** I expect the background color of the find bar to be consistent. For now it is so contrast that it looks to me like a bug.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version:  0.11.6 Beta6

- Any related issues: #3315

**Comment by bbondy** [comment]
it is supposed to be matching the themeColor per design.
/cc @bradleyrichter 

note that there should be black vs white text though depending on the contrast, please post if that's not the case.

Marking this as wontfix though.

**Comment by bradleyrichter** [comment]
it needs a bit more work to look like this:

![image](https://cloud.githubusercontent.com/assets/13509546/18062644/8bfe712c-6ddc-11e6-8c5e-e87550fb7410.png)

**Comment by bradleyrichter** [comment]
also, your white BG screen shot may be a bug. That shouldn't happen as Brian explained. The text and element colors should match the tab text color.

cc @jkup

**Comment by jkup** [comment]
That looks right to me in the sense that if the tab is white, the findbar should be white, right?

**Comment by luixxiul** [comment]
With ``border: 2px solid #ddd`` for example,
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18100404/cf7489d8-6f25-11e6-8eb1-5eb40c4b7004.png)

the input field seems to me much noticeable here.

**Comment by bsclifton** [comment]
Created https://github.com/brave/browser-laptop/issues/5319 to track the theme colored input box
