### ISSUE TITLE
Sometimes bookmarks/history submenu becomes too wide

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3527]
**Describe the issue you encountered:**
On 1024x768 monitor sometimes it becomes like this:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18059299/5dcea7e6-6e53-11e6-85f7-9273492e1253.png)

**Expected behavior:** I think max-width should be narrower.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit
- Brave Version: 0.11.6 Beta6
- Any related issues: #3055 #1993

**Comment by luixxiul** [comment]
cc: @bsclifton

**Comment by bradleyrichter** [comment]
add ellipses at 50% of this width?

**Comment by luixxiul** [comment]
This has been fixed.
