### ISSUE TITLE
Ctrl+F & Ctrl+G both opens find bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3528]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ctrl+F & Ctrl+G both opens find bar

**Expected behavior:**
Onl Ctrl+F should launch find bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Dev Beta 6

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![find](https://cloud.githubusercontent.com/assets/17010094/18059539/54babc9a-6e11-11e6-9899-9d67ee65cf1e.gif)

- Any related issues:

**Comment by bbondy** [comment]
This matches behavior on chrome, could you give a use case for why this is bad? Some might prefer it the way it is already.

**Comment by srirambv** [comment]
Oh I didn't realize Ctl+G worked on Chrome. My bad. Closing the issue.
