### ISSUE TITLE
Preferences can be hard to find

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3532]
The preference categorization is a difficult problem and it can sometimes be difficult to find preferences. Several potential solutions have been suggested including:
1. eliminating categories and putting all settings in the sidebar
2. adding category sub-headings to the sidebar
3. adding search (with tags)
4. rethinking the entire UI for preferences

**Comment by neeklamy** [comment]
Even with a radical redesign, there’s still going to be a lot of options, I would like to see a search similar to that in Google Chrome – _but better, eh!_

OS X and now macOS have a couple of great uses of search built in, the _Help → Search_ menubar item for each application, and in System Preferences. What’s especially nice is that both take you to the item searched for. System Preferences has synonyms too, so if you search for “wallpaper”, it takes you to the _Desktop & Screen Saver pane_.
