### ISSUE TITLE
Add currency symbols where appropriate

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3533]
Using a library like https://www.npmjs.com/package/currency-symbol-map it would be nice to add currency symbols on the ledger settings pages for the appropriate currency type.

It looks like "currency" is stored in state as a string (https://github.com/brave/browser-laptop/blob/master/docs/state.md#L403), so we should just be able to pipe it through a library like the one above and then prepend it to the currency number.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6249#issue-195997351

**Comment by bradleyrichter** [comment]
This needs to be changed to use ISO 4217 3-letter codes instead of symbols.

**Comment by bsclifton** [comment]
I'll get this squared away

**Comment by bsclifton** [comment]
The fix for this issue was reverted with https://github.com/brave/browser-laptop/pull/6720. Removing milestone from this issue + original PR.

cc: @luixxiul in case you needed to remove the release notes for this

**Comment by mrose17** [comment]
let's declare this done!

**Comment by luixxiul** [comment]
I added `QA/no qa needed` `release-notes/exclude` labels
