### ISSUE TITLE
Amazon domains other than .com are blocked

### ISSUE THREAD

**Issue by niseh** [brave/browser-laptop#354]
Amazon has many domains depending on the country you are shipping to (amazon.fr, .it, .de, .co.uk, etc)

Currently, I can't use brave on other than amazon.com.

Amazon.fr and amazon.com for example are completely different marketplaces, and not just Amazon doing i18n. It's important for a french user to shop at amazon.fr and not .com or .co.uk (shipping delays, costs, legal issues, etc)

**Comment by diracdeltas** [comment]
Thanks, I can confirm this.

**Comment by bbondy** [comment]
@SergeyZhukovsky please take a look, it is related to tracking protection I think, is it the same on Android?

**Comment by Oldpedro** [comment]
same on os/x; I can load amazon.com, but not my regular amazon.co.uk

**Comment by bbondy** [comment]
I think it probably has to do with how we're handling redirects and the first party url detection code in the laptop browser. Would be curious to know if this works in Android if you have a chance @SergeyZhukovsky .

**Comment by SergeyZhukovsky** [comment]
Ya just verified it and if we skip first party, it works great. We have two options:
1. Add it to the tp lib.
2. Do checks for all platforms.
What do we prefer?
