### ISSUE TITLE
Usernames are persisting in autofill despite clearing data. 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3541]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If a username and password are stored via Brave's internal password manager, the username is added to the 'autofill' table in brave/Web\ Data.  If the user visits about:password and clears the entry, it still shows the username when the user visits the originating page. 

**Expected behavior:**
The username should vacate from the 'autofill' table when the password is deleted. Alternatively, if a user visits about:autofill, they should be able to see and edit username values.  Design consideration: If a user can globally delete all other forms of data, should they not be able to clear their usernames and passwords?
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.11.6 pre-beta6
- Steps to reproduce:
  1. Visit https://trac.torproject.org/projects/tor/login
  2. Log in and save your password
  3. Visit about:password and delete the saved value
  4. Return to https://trac.torproject.org/projects/tor/login and attempt to log in
  5. Observe the username field
- Screenshot if needed:
- Any related issues:

**Comment by darkdh** [comment]
We plan to provide `clear autocomplete data` option in clear browsing data panel. And also we need to integrate the existing password manager with autofill to make the behavior normal. They've been noted in https://github.com/brave/browser-laptop/issues/3358

**Comment by luixxiul** [comment]
This has been fixed 👍 Clear autocomplete and autofill data options have also been available 😄

**Comment by luixxiul** [comment]
Still let me add the milestone for manual QA in case 😉

**Comment by LaurenWags** [comment]
blocked for testing on 0.20.x by https://github.com/brave/browser-laptop/issues/12063
