### ISSUE TITLE
Building on Windows requires tedious work-arounds

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3548]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Getting a development version of brave working requires manual work-arounds

**Expected behavior:**
We should have better documentation and work-arounds for known issues should be scripted

- Platform (Win7, 8, 10? macOS? Linux distro?):
All versions of Windows

- Brave Version:
0.11.4 and newer

- Steps to reproduce:
    1. Have a Windows machine
    2. Follow steps in the README.md
    3. Try running `npm install`
    4. Try running `npm start`

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/3142
https://github.com/brave/browser-laptop/issues/3323

**Comment by luixxiul** [comment]
I tried it on Windows 7 setting up following the instruction but `npm win-fixnpm` failed due to an unknown error (because Poweshell version is too old? /cc:@bsclifton). I'll post a log (screenshot later)

Not tested on WIn10 32bit. It might work on Win10 64bit.

**Comment by bsclifton** [comment]
ah- thanks @luixxiul, it is definitely due to not having the latest Powershell. I'll update the wiki :smile:
