### ISSUE TITLE
Linux build tricks

### ISSUE THREAD

**Issue by irongomme** [brave/browser-laptop#355]
Hi, 

With some tricks i've been able to build this project and finally test it, but i had to make some operations to achieve it. So i just want to share it.

I am on OpenSuse Tumbleweed, with fresh compiled nodejs 5.5 and npm 3.3.12

For me, build fails with this message : 

```
ENOENT: no such file or directory, chmod '/home/XXXXXX/app/browser-laptop/node_modules/extract-zip/node_modules/mkdirp/bin/cmd.js'
```

I've fixed it width : 

```
mkdir /home/XXXXXX/app/browser-laptop/node_modules/extract-zip/node_modules
ln -s /home/XXXXXX/app/browser-laptop/node_modules/mkdirp /home/jerome/app/browser-laptop/node_modules/extract-zip/node_modules/
```

Once built, the npm start gave me that error : 

```
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.2/docs

Error: Cannot find module '/home/XXXXXX/app/browser-laptop/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'
```

Which i've fixed with : 

```
ln -s /home/XXXXXX/app/browser-laptop/node_modules/sqlite3/lib/binding/node-v46-linux-x64 /home/XXXXXX/app/browser-laptop/node_modules/sqlite3/lib/binding/node-v47-linux-x64
```

And now it works !! 

I'm not an expert with nodejs and dependencies, but i think there is mistakes with some paths. I hope this helps !

**Comment by diracdeltas** [comment]
Thank you for this, I haven't had this issue on Linux but will link to it if others have it. We should probably have a troubleshooting section in the README that links to issues like this. Feel free to start it and open a pull request.

**Comment by luixxiul** [comment]
Closing for the moment. Please leave comments if the issue still exists for the latest version. Thanks.
