### ISSUE TITLE
upgrade to 0.11.6 fails

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3550]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When upgrading to 0.11.6 

```
tabState.js:31Uncaught TypeError: Cannot read property 'find' of undefined
ReactReconciler.js:64Uncaught TypeError: Cannot read property 'getHostNode' of null
```

occurs when loading the browser

**Expected behavior:**
Should load normally

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
pre-0.11.6

- Steps to reproduce:
    1. Start with a version of Brave prior to 0.11.6
    2. Upgrade to 0.11.6
    3. Launch Brave

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Attaching a nearly blank 0.11.1 session file.  To reproduce, put the session file in place and then launch 0.11.6 beta 4 or 5.

[session-store-1_bsc0.11.1.zip](https://github.com/brave/browser-laptop/files/443932/session-store-1_bsc0.11.1.zip)
