### ISSUE TITLE
Text is blurry in page content, tab labels, and URL bar

### ISSUE THREAD

**Issue by JoeArizona** [brave/browser-laptop#3556]
I waited a few months to report this one since I assumed you knew about it. Brave is always blurry on first render of a page. It usually unblurs after a few seconds, but pages can become blurry again in the same session. I think it's most common for them to become blurry again when screen context switches to another app or tab and then I return to original tab.

The tab labels are usually blurry, as is the URL display. This is frustratingly hard to get screenshots of because whenever I go to screen shot app to start a shot and then return to Brave, it unblurs before I can get a shot. But I'm able to attach a mild example of the blurriness here. Note that it can get much blurrier.

If it helps, I've been struck by the fact that Opera is having the same problem, and has been unusably blurry across versions 38 and 39, on Windows 10. Vivaldi is having similar issues, but Chrome has no such issues. There might be something common in the Chromium spinoffs that is causing this.
- Platform: Windows 10 Home, 64-bit
- Brave Version: 0.11.5
- Screenshot if needed: 
  ![2016-08-29_22-44-21](https://cloud.githubusercontent.com/assets/8071692/18077658/1260303e-6e3c-11e6-8c67-b312859a7f08.png)
- Hardware: Intel Skylake Core i5-6400T; integrated GPU is the Intel HD 530; 12 GB of DDR3

**Comment by Sh1d0w** [comment]
Hm, I have never observed such behaviour and I am using Brave on a daily basis. Can you please try to capture a video of the problem?

**Comment by Sh1d0w** [comment]
Can you please try to capture a video of the problem?

**Comment by benpoulson** [comment]
What resolution is your screen running at, and are you running multiple screens?

**Comment by JoeArizona** [comment]
No video yet. What's a good tool for that?

Resolution: 1080 x 1920, one display only. It's a Dell 24" All-In-One, [this model](http://www.dell.com/support/home/us/en/19/product-support/servicetag/F111B22/diagnose).

After your replies, I installed Brave on an Ivy Bridge laptop, a Sony VAIO, also 1080p, 15", Intel HD 4000. There is no blurriness on the Ivy Bridge. So for me it's only happening on the Skylake (and it's always been blurry on the Skylake, for several months now.) I'll think about other factors that might be unique to this machine.

**Comment by bsclifton** [comment]
@JoeArizona what is your DPI? You can find it by right clicking desktop and choosing "Display settings".  I'm guessing you're at 150% or 200%.  There are some known issues w/ electron at the larger DPI.

Please let us know and sorry for the super long turn around (I missed this issue for sure)

**Comment by JoeArizona** [comment]
@bsclifton I'm at 100% on both systems. The blurry one is the 24" Dell All-in-One. It's not blurry on the 15.4" Sony laptop. Both displays are 1080p, with Intel integrated graphics (Skylake HD 530 on the Dell, and Ivy Bridge HD 4000 on the Sony.)

**Comment by michaellmonaghan** [comment]
I'm noticing similar issues on my system running an Intel core m with an HD 5300 GPU with a dpi scale of 150%.

![image](https://cloud.githubusercontent.com/assets/4855844/19427894/c604dcd6-9414-11e6-8b6c-9bd641fcdf99.png)

I timed my screenshot above so that the tab label text is blurry. It will become blurry during page loading and become sharper after the page has loaded. The url text appears to be just as blurry at spontaneous times.

The content blur appears to persist after the page has loaded. (Chrome shown on left for comparison) Upon further inspection however, it appears that Brave is not using subpixel rendering for text. Perhaps this is the content blur you are talking about?

**Comment by michaellmonaghan** [comment]
I am also having this issue. I have an intel core m with a hd 5300 gpu just in case it is of any importance.
I however have 150% scaling which may contribute to the problem.
here's a screenshot of the blurry text. This is the only thing keeping me from using brave on my hdpi laptop at this point.

**Comment by bsclifton** [comment]
@JoeArizona we'll have a potential fix coming soon for this (sorry for the super long turnaround time; nailing this wasn't easy).  Would you be interested in testing if we had a release candidate available in the next week?

**Comment by JoeArizona** [comment]
Hi Brian, sure I'm happy to test.

**Comment by bsclifton** [comment]
@JoeArizona awesome- you can grab our latest version from https://brave.com/downloads.html or here on our GitHub releases page:
https://github.com/brave/browser-laptop/releases/tag/v0.13.1dev

Let me know if things look better 😄

**Comment by michaellmonaghan** [comment]
Everything looks fantastic. Great work guys!

**Comment by JoeArizona** [comment]
Sorry for the delay – everything looks good now. Here's a screenshot of the same tab as before. A few variables have changed since the original: mostly, GitHub and Brave have changed their designs. But you can tell that text is much crisper. (Note that the screenshot is showing the screen a bit blurrier than it actually is – I don't know why PNG screenshots do this, but I see it often.)

![2017-02-20_12-48-54](https://cloud.githubusercontent.com/assets/8071692/23139924/2a2e31d4-f76c-11e6-8283-74aaa37ef89a.png)

**Comment by bsclifton** [comment]
@JoeArizona great, thanks for trying it Joe! Glad it works 😄
