### ISSUE TITLE
1Password extension error on Windows 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3557]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Browser fails to load 1Password extension on Windows even when 1Password app is running

**Expected behavior:**
User should be able to login when 1Password is selected from the rightclick context menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
1Password v6.0.186

- Brave Version:
0.11.6 Dev Beta 6

- Steps to reproduce:
    1. Add login in 1Password app for a website
    2. Navigate to the login page of the website
    3. Keep the 1Password app active and click on 1Password from right click context menu in the login page
    4. New tab opens checking for 1Password extension. 

- Screenshot if needed:
![1pass](https://cloud.githubusercontent.com/assets/17010094/18087886/4ee3f2a2-6eaf-11e6-9775-12d3cf09fe4f.gif)

- Any related issues:

**Comment by bridiver** [comment]
we don't appear to be in the supported browser list for 1password 6 and I don't see an option to disable signature checking

**Comment by bridiver** [comment]
I actually can't replicate this problem, but when I attempt to use 1password it does nothing. I have emailed agilebits for more info

**Comment by bbondy** [comment]
Steps for disabling signature checking is here:
https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-use-1password

**Comment by bsclifton** [comment]
This may be related:
https://github.com/brave/browser-laptop/issues/3201

**Comment by bridiver** [comment]
@bbondy those steps only work on mac. 1password for windows doesn't have an option to disable it

**Comment by bsclifton** [comment]
I also can't find a way to turn off signature verification.

I went ahead and [left a message in their forum](https://discussions.agilebits.com/discussion/68562/cant-disable-verify-browser-code-signature/p1?new=1) and @bridiver has emailed the folks at AgileBits. We'll have to wait for an answer

**Comment by bbondy** [comment]
This is also an issue with 0.11.5 so not a regression, so we don't need to track for this release.

**Comment by bbondy** [comment]
The steps were written for windows originally and there were different ones for Mac. It did work in the past for Windows.  Mac doesn't need them anymore.

**Comment by bridiver** [comment]
yea, probably 1pw4 vs 1pw6 for win

**Comment by bsclifton** [comment]
1Password release an update today for Windows (version 6.0.197) and it's working great :smile: They added signature support for Brave as one of those fixes.  @srirambv and I have both tested. Closing issue
