### ISSUE TITLE
Linux only - Launching from source fails

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3559]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to launch via npm start, an error is printed to the console and a window is not generated.

> test@test:~/Development/browser-laptop$ npm start
> brave@0.11.6 start /home/test/Development/browser-laptop
> node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

> [27736:0830/095503:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[27736:0830/095506:INFO:CONSOLE(93)] "Set up extension URL router.", source: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/extension-router.js (93)`

**Expected behavior:**
The app should launch appropriately.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X, Ubuntu. Only issues found on Ubuntu.
- Brave Version:
0.11.6 pre-beta6

- Steps to reproduce:
    1. On an Ubuntu VM clone the repo.
    2. Meet the pre-requisites here: https://github.com/brave/browser-laptop
    3. In one terminal, run 'npm run watch'
    4. In another terminal, run 'npm start'

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@alexwykoff which version of Ubuntu? I did a fresh install of Ubuntu 16 yesterday while looking at password manager issues and it works great for me

**Comment by alexwykoff** [comment]
I am on 16.04 Xenial.  Did you install a build or launch from source?

**Comment by bsclifton** [comment]
Is this issue perhaps just to track the warning that is given? Or did it actually not work for you?  I installed from source:
![screen shot 2016-08-30 at 9 51 54 am](https://cloud.githubusercontent.com/assets/4733304/18098540/8184a5ac-6e97-11e6-84a1-56317f3ad1eb.png)

Did you make sure to run:
`apt-get install libgnome-keyring-dev build-essential`

Before doing the npm install? (and if you had done one previously, remove your node_modules and ~/.electron folder)

**Comment by alexwykoff** [comment]
It was actually complaining about a missing react dependency. 
Clearing away the folder and re-cloning resolved the issue.

Since there's an easy workaround and this was likely workspace corruption, I'll close it out.

**Comment by rickyrauch** [comment]
same issue ```Ricardos-MacBook:browser-laptop ricardorauch$ npm start

> brave@0.12.8 start /Users/ricardorauch/Sites/browser-laptop
> node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

Crash reporting enabled
[88262:1102/001404:INFO:CONSOLE(93)] "Set up extension URL router.", source: chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/extension-router.js (93)```

after a clean install
