### ISSUE TITLE
Browser does not copy/paste images into Whatsapp web

### ISSUE THREAD

**Issue by vqcr** [brave/browser-laptop#3560]
Right-click drop down menu option "copy image" doesn't seem to work properly. When I try to paste the copied image into Whatsapp Web it only pastes the image's URL.

Windows 10 (10.0.14393).
Brave 0.11.5
1. Right-click on an image.
2. Click on "copy image".
3. Open Whatsapp web.
4. Paste image. 

![2016-08-30](https://cloud.githubusercontent.com/assets/5630959/18094703/98e8d16a-6e91-11e6-8a97-8ccf7a511728.png)

![image](https://cloud.githubusercontent.com/assets/5630959/18094716/a32f5d9c-6e91-11e6-9313-e6957ce0e665.png)

**Comment by bbondy** [comment]
Do other browsers paste correctly there with the same steps? It might be a problem with Whatsapp web

**Comment by vqcr** [comment]
Yes, I just tried the same procedure using Chrome 53.0.2785.80 beta-m (64-bit) and it works fine

![image](https://cloud.githubusercontent.com/assets/5630959/18106177/c5db1ba0-6ebf-11e6-84ff-5db74a795ede.png)

**Comment by bbondy** [comment]
I think we might add an extra mime type to the clipboard and it probably chooses it over the other available one. I think we should just not specify as much to fix this when copying an image.

**Comment by alentor** [comment]
Experiencing the same issue, seems like the issue related to whatsapp/electron as I can't copy paste images from Firefox developer edition/chrome as well. The feature(copy paste images directly to whatsapp) used to work, after reinstalling whatsapp the issue still present.

**Comment by scottbroadway** [comment]
Still failing in 0.15.0.

**Comment by bsclifton** [comment]
This might be related to https://github.com/electron/electron/issues/8877

@scottbroadway I'm doing some work in Muon (our fork of Electron) this week... I'll see if I can pull in the upstream patch 😄

**Comment by bsclifton** [comment]
I believe this was fixed with https://github.com/brave/browser-laptop/pull/13108 

Let's reopen the issue if it's still occurring.  Thanks! 😄
