### ISSUE TITLE
update to https everywhere 5.2.4

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3561]
https://www.eff.org/files/Changelog.txt

cc: @diracdeltas

**Comment by diracdeltas** [comment]
now on 5.2.4 :)

**Comment by bbondy** [comment]
Moving to 10.12.1 and closing based on that last message.

**Comment by diracdeltas** [comment]
@bbondy actually i meant it was upstream 5.2.4 now, not that this was fixed
