### ISSUE TITLE
Entering "site:example.com" into address bar results in no action

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3562]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I enter "site:example.com" into the address bar, the address bar reverts to its previous state and nothing else happens

**Expected behavior:**
Search for "site:example.com"

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.11.6dev-beta6 (About dialog reports 0.11.5)

- Steps to reproduce:
    1. Open a browser window, either an empty tab or load a page
    2. Into the address field, enter "site:example.com" (or any other domain)

**Comment by Sh1d0w** [comment]
Hm seems I can not reproduce this on latest 0.11.6-beta6 version. See the screencast below.

http://webm.land/media/Fp8V.webm

Can you provide more details how to reproduce, e.g. what's your default engine?

**Comment by gulkily** [comment]
Confirmed fixed in 0.11.6-beta6
