### ISSUE TITLE
Found entries on about:history cannot be deleted

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3566]
**Describe the issue you encountered:** on ``about:history`` I cannot delete entries which are found via the internal search form.

**Expected behavior:** They should be deleted.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version: 0.11.6 beta6

- Steps to reproduce:
    1. Move away your brave folder temporarily
    2. Open https://badssl.com
    3. Open ``about:history``
    4. Input ``badssl`` in the internal search form
    5. Click "Delete History Entry" from the context menu
    6. The entry dated `Thursday, January 1, 1970`` appears, which cannot be deleted

If you clear the search query the entry becomes hidden, while you input it again the entry becomes visible.

#441, #444, #3320

**Comment by luixxiul** [comment]
Is this fixed with #3628? /cc: @bsclifton

**Comment by bsclifton** [comment]
Yes, it was! Thanks for catching this, I missed it when creating an issue :smile:
