### ISSUE TITLE
Right hand menu icon not working

### ISSUE THREAD

**Issue by Cromian** [brave/browser-laptop#357]
Mac OS 10.11.3 - the right hand (3 bar) menu does nothing when you click on it.

**Comment by bbondy** [comment]
Yep this is a dupe of #310 which was already implemented just not released.
I'll leave this open until it's released though to avoid dupes.

**Comment by Cromian** [comment]
Ah sorry bout that.

**Comment by bbondy** [comment]
Fixed in 0.7.10 (which is available now)
