### ISSUE TITLE
refactor about page update handling

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3570]
The update mechanism for the about pages is a big clunky and needs a refactor. Currently one or more ipc updates are sent from frames.js based on the current about page url. It would be better if we didn't have to pass all that state through the frame (triggering unnecessary re-renders along the way) and there is also a slight delay before it gets the data for the first time.

Several options that have been discussed:
1. make appState available through shared memory
2. make appState/settings available through chrome apis
3. create a store for the about pages that pulls data from the chrome.\* apis and registers onChange callbacks

**Comment by bsclifton** [comment]
As a temporary work-around, the unnecessary renders can be manually caught and prevented by saving timestamps for the data and checking against it in the about page receiving the update. Far from ideal, but it does help :smile: 

I wanted to share two examples:
- [about:newtab](https://github.com/brave/browser-laptop/blob/967362846d1a06bf8fa042fd8e0b3b85650ab57d/js/about/newtab.js#L42)
- [about:history](https://github.com/bsclifton/browser-laptop/blob/eefd4e873adbd040f208eabe05f549b62b85e8cc/js/about/history.js#L136)

**Comment by bridiver** [comment]
unnecessary renders are an orthogonal issue. The problem here is the clunky initialization and update process
