### ISSUE TITLE
"modal" dialogs for tabs aren't really modal

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3574]
some popover dialogs like basic auth appear to be modal, but will disappear and reappear if you navigate to other tabs using the keyboard shortcuts. We should either lock the browser to make them modal or attach them to the tabs somehow (watching out for potential spoofing issues)

**Comment by bsclifton** [comment]
Reworking the basic auth screen to work similar to the new alert/confirm should be pretty easy after https://github.com/brave/browser-laptop/pull/7107 is accepted 😄

**Comment by srirambv** [comment]
Windevine plugin prompt should be contained within the tab 
![netflix](https://cloud.githubusercontent.com/assets/17010094/24161805/52b655f2-0e5d-11e7-93c1-e3b20e1b5ca0.gif)
