### ISSUE TITLE
Bookmark Bar

### ISSUE THREAD

**Issue by JamesH2288** [brave/browser-laptop#3576]
**Did you search for similar issues before submitting this one?** YES

**Describe the issue you encountered:** When i edit a bookmark in the bookmark bar after i press Save nothing happens. The Bookmark is still the same. 

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.11.5

- Steps to reproduce:
    1. Add a bookmark to bar
    2. Right click on it and select "edit"
    3. Edit title and click save, 

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
This was fixed in the latest build v0.11.6dev which soon will be released.
