### ISSUE TITLE
autocomplete db initialization fails on fresh profile

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3577]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After removing the brave user data dir I receive the following messages on startup
```
[29254:0830/124921:ERROR:connection.cc(1912)] Web sqlite error 14, errno -2: unable to open database file, sql: -- sqlite3_open()
[29254:0830/124921:ERROR:web_database_backend.cc(56)] Cannot initialize the web database: 1
[29254:0830/124921:WARNING:brave_browser_context.cc(73)] initializing autocomplete database failed
```
If you attempt to save any autofill data on the first run it will be blank when you run brave again

**Expected behavior:**
autocomplete database should load on first run

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version:
0.11.6dev

- Steps to reproduce:
    1. Delete or move your brave user data dir
    2. Run Brave in dev mode (to get console output)

cc @darkdh

**Comment by bridiver** [comment]
additional testing steps:
1. delete or remove your brave user data dir
2. run brave
3. add an autofill address
4. quit brave
5. re-open brave
The autofill address should exist and have the correct values

**Comment by luixxiul** [comment]
I think this issue still exists on Windows 7 64 bit. 

1. Move your brave folder
2. Open autofill settings from ``about:preferences#security``
3. Click on ``Add Addresses``
4. Input ``temp`` in the field Name
5. Quit the browser
6. Start the browser

The name field becomes blank.

**Comment by luixxiul** [comment]
Reopening for now.

**Comment by darkdh** [comment]
Fixed in https://github.com/brave/electron/commit/18496a4
related issue: https://github.com/brave/browser-laptop/issues/3491
