### ISSUE TITLE
Unclear if new tab opened

### ISSUE THREAD

**Issue by jacobpewitt** [brave/browser-laptop#358]
I use three finger tapping on my trackpad to simulate a middle click to open a link in a new tab. It doesn't always work, which isn't Brave's fault. But when I have enough Brave tabs open that they have overflowed into a second 'page' of the tab bar, there is no visual indication of whether a link that I try to open by three finger tapping has actually opened or not unless I scroll over in the tab bar and look.

**Comment by bbondy** [comment]
Great UX point , thanks for posting. 
CCing @bradleyrichter for open background tab UX ( You can also command+click on a link to go to background tab)

**Comment by gdi2290** [comment]
I have this problem too (middle click via trackpad). In Chrome another great feature is having the new tab selection as the first option

**Comment by bridiver** [comment]
Actually I think there are two issues: 
1. We always open the new tab at the end, but Safari and Chrome open it next to the tab you are currently on which I think is better
2. The lack of indication could still happen if you cmd-click from the last tab in a set. Maybe show some kind of loading indication on the tab page button?

**Comment by unsystemizer** [comment]
@bridiver I just noticed on the current Brave version right-click & open in new tab opens the link in the middle (literally) of the screen. And this isn't consistent: 

* You're in the last tab: new tab will be the next
* You're in on right-hand side of a multi-screen tab list, say to the right on tab group 1 out of 2: new tab opens right after the tab where you open it (so "the next"), while existing tabs are pushed to the right
* This scenario that I noticed today is if you're on the left hand side of "group 1", the new tab opens in the middle of the screen (maybe 2-3 tabs to the right), although there's 2 groups (screens) of tabs

**Comment by posix4e** [comment]
Can we close this? @posix4e

**Comment by bridiver** [comment]
was there a change to fix this?

**Comment by posix4e** [comment]
@bridiver So long ago i assumed it was fixed long ago

**Comment by bradleyrichter** [comment]
We still need to add the pref to open new tabs to the right of the current tab. Or just change it.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site to receive opinions about the issue.

https://community.brave.com/t/discussion-how-to-make-it-clear-that-new-tabs-opened/10056

Let's continue the discussion there about how to make it more clear that new tabs are opened. If we will find a nice solution, we could reopen this issue 😄
