### ISSUE TITLE
Add the ability to remove and ignore a visited domain in the ledger list

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3580]
When a publisher site is visited by accident, or otherwise unwanted in the ledger list permanently, the context menu allows for removal. This removal is sticky so that it will not appear again.

The domain is added to a black list that can be edited or reset if needed.

The black list will be managed via a button in advanced prefs under a new title called "Brave Payments". (out of scope for this initial feature)

![image](https://cloud.githubusercontent.com/assets/13509546/18110928/4dd88a78-6ed0-11e6-8b46-b2d435d55302.png)

**Comment by mrose17** [comment]
@diracdeltas - can you give me an API to use for this?

i'm not really sure that we can add "Ignore this domain" to the menu list, but regardless of how it is done in the UI, please tell me how `ledger.js` gets informed that something has been added to the blacklist. thanks!

**Comment by diracdeltas** [comment]
@mrose17 there is already an example in ledger.js to check when something is already on the blacklist (look for `siteSettings`). to listen for when something new is added, listen for the ipc events `APP_CHANGE_SITE_SETTING` and `APP_CHANGE_SITE_SETTING`

**Comment by mrose17** [comment]
@diracdeltas - this is a different function. the existing function above is for include/exclude. the function that @bradleyrichter is talking about is for a blacklist that will keep the publisher from displaying at all on the preferences page.

**Comment by diracdeltas** [comment]
@mrose17 seems like the only difference between the existing functionality and what @bradleyrichter is asking for is whether the publisher is displayed on the prefs page. i'm not sure why `ledger.js` needs to know about that since that is only a UI change

**Comment by mrose17** [comment]
there is a "real" difference: `ledger.js` will not use those blacklisted domains in any of its calculations. that's the true benefit...

**Comment by diracdeltas** [comment]
> there is a "real" difference: ledger.js will not use those blacklisted domains in any of its calculations. that's the true benefit...

keep in mind that if a user disables a site via the switch now, it will stay disabled forever until it's manually re-enabled. shouldn't the ledger take that into account and ignore those domains in any of its calculations?

**Comment by mrose17** [comment]
in previous conversations, i believe that the consensus was that the use of the include switch must not affect the reality of the reporting. that is why we just grey out the entry rather than fiddle with the numbers.

what this issue is asking for is to allow the user to have a private exclusion list. which means that the site doesn't show up on the payments preferences page, nor is a part of the calculations.

it may be that having both functionalities is bad. in that case, my "vote" is to replace the include switch with an exclusion list. the key thing is to get the excluded sites off of the preferences page and out of the calculations. does that make more sense? thanks!

**Comment by diracdeltas** [comment]
> in previous conversations, i believe that the consensus was that the use of the include switch must not affect the reality of the reporting. that is why we just grey out the entry rather than fiddle with the numbers.


does the include switch do anything other than grey out the entry?

**Comment by mrose17** [comment]
yes, it prevents the publisher getting any votes. but... and this is critical, the include switch does not alter whether viewing of the site is counted...  the exclusion list will.

**Comment by diracdeltas** [comment]
my worry is that the difference will be confusing for the user. if i were the average person, i would intuitively expect turning off the 'include' switch to turn off viewing counts *and* prevent the publisher from getting votes. but i'm fine with it either way.

**Comment by bradleyrichter** [comment]
The switches should definitely stop votes for that site going forward in time. Since we don't show votes or money flow, then nothing changes visually beside the grey-out. 

The rt-click menu above is to exclude/hide/banish a site from ever appearing in your list. For example, assume an evil friend sent me a link to a porn site (somehow disguised) and I clicked on it. Then frantically clicked in the page while trying to escape. Now it hits my ledger list and it's stuck there. I want it gone visually, and of course, don't send it any contributions.

**Comment by mrose17** [comment]
@diracdeltas - i am happy to get rid of the include slider for an exclusion "trash can". i agree that having both is confusing. in this case "less is more", i guess.

**Comment by bradleyrichter** [comment]
@mrose17 We should wait for more feedback before removing the switches. The debate over whether an off switch should zero out the time and page views is interesting. 

@diracdeltas I originally thought it should zero but wouldn't it seem weird to have this info reset since it was a recording of your activity? (your activity happened and it's not a time machine since you can't effect it in reverse.)

Can we try it?

**Comment by mrose17** [comment]
this is available in the 0.12.2dev release candidates
