### ISSUE TITLE
Show a message when a page is not available

### ISSUE THREAD

**Issue by Eschon** [brave/browser-laptop#359]
I just tried to load a page and had a typo in the URL but instead of showing some message like "This webpage is not available". The page is just blank like a new tab.

**Comment by bbondy** [comment]
This is on our list for the 0.8 release, thanks for posting.

**Comment by luixxiul** [comment]
Already implemented?

**Comment by bbondy** [comment]
@bridiver is working on this now.

**Comment by bbondy** [comment]
Duping to https://github.com/brave/browser-laptop/issues/1611
