### ISSUE TITLE
add "Enable Brave Payments" to the bravery menu

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3592]
This will help some users find Brave Payments as one of several paths.

**Comment by ayumi** [comment]
Is the bravery menu the OS menu like
<img width="229" alt="screen shot 2016-09-12 at 10 45 44" src="https://cloud.githubusercontent.com/assets/521861/18446204/2594452e-78d6-11e6-99cd-f5fe34c3ca9a.png">

and if Payments is already enabled, should it become "Disable Brave Payments"?

**Comment by bradleyrichter** [comment]
@ayumi Yes. 

This is mostly for user awareness so we could use a different approach like:

If BP is OFF, then menu = "Start using Brave Payments..."

If BP is ON, then menu = "Brave Payments..."


This avoids using an actual toggle menu since we don't really want you to turn it off outside of the payments panel.
