### ISSUE TITLE
Lastpass Green Bar Issue

### ISSUE THREAD

**Issue by kyletorpey** [brave/browser-laptop#3596]
Lastpass messes up a lot and sometimes displays a green bar with no options on it at the top of a webpage. I recognize this as a broken version of the pop-up question that usually asks if I'd like to save a new login, save changes made to a login, etc.

This is especially annoying on some websites where the top menu bar is completely blocked due to this useless pop-up.

I'm running the latest version of Linux Mint.

Brave version 0.11.5

Not sure what is causing this yet as sometimes the "save these login credentials" pop-up displays correctly. Will update if I notice a trend.

I've attached a screenshot of the issue:

![screenshot_2016-08-30_23-12-25](https://cloud.githubusercontent.com/assets/6266647/18114807/32567142-6f08-11e6-91ed-2a48bcf0d8a4.png)

**Comment by DivineOmega** [comment]
Unfortunately I'm also receiving this issue. Possible related: in the few cases when the bar does render correctly, clicking the save password buttons will usally result in a blank tab being opened (the extension's page does not render).

**Comment by luixxiul** [comment]
Though I have used LastPass for a while, I have not seen that issue. For now I'm going to close this issue in favor of this topic on our community site to get more feedback on that 😄 

https://community.brave.com/t/lastpass-green-bar-issue/10422

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
