### ISSUE TITLE
Updates don't prompt for Auth

### ISSUE THREAD

**Issue by steve-obeck** [brave/browser-laptop#360]
When using Brave in a non-Admin account - the update does not succeed and never prompt for Admin privileges.  I have an "update" button that continues to show and when I click on it.. I imagine it fails in the background due to permissions.  It keeps asking me to update and failing (caught in a loop)

**Comment by bbondy** [comment]
Windows or OSX?

**Comment by steve-obeck** [comment]
OSX  10.11.3

**Comment by steve-obeck** [comment]
I'm on 0.7.8 and its the 0.7.9 update

**Comment by bbondy** [comment]
Thanks for the report. CC @aekeus

**Comment by bbondy** [comment]
can you install into a non admin location or something for now?

**Comment by steve-obeck** [comment]
You mean for testing?  I can

**Comment by bbondy** [comment]
yep just a work around for now.  Did you install originally as admin ? Or as limited and it prompt for admin password?

**Comment by steve-obeck** [comment]
Yes - works in the Admin account. Installed and Updated to 0.7.9  Orignally installed as a "user"  but it never prompted for Admin creds as you would expect

**Comment by bbondy** [comment]
Interesting. So when you installed as limited user account, where did it install to?

**Comment by luixxiul** [comment]
Closing for now. If someone know STR please leave it, thanks.
