### ISSUE TITLE
Incorrect Autofill values loaded on form

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3602]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Incorrect Autofill values loaded on form. Credit Card name is getting loaded for First Name/Last Name fields

**Expected behavior:**
Should show autofill values from addresses instead of credit card details.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 RC1 (Clean install)
- Steps to reproduce:
  1. Add Autofill details
  2. Visit [Ebay](https://guestcheckout.payments.ebay.com/ws/eBayISAPI.dll?GuestXOProcessor&sessionid=642828601&pagename=rypaddress). Select a product and checkout as guest.
  3. In the shipping address page clicking on First name shows auto fill entries from credit card. Should show entries saved under address
- Screenshot if needed:
  ![autofill](https://cloud.githubusercontent.com/assets/17010094/18121738/e88b7124-6f5d-11e6-9efd-7a3bc9f00582.gif)
- Any related issues:

cc: @darkdh

**Comment by bbondy** [comment]
This is a hard call but I'm going to move this to the next roadmap for now until we find proof it's a common problem on a lot of sites, I know it's not all sites.  @darkdh will weigh in if he finds more. I'm going to spin rc2 builds without this though because we aren't close to a fix.

**Comment by srirambv** [comment]
The same issue on [Paypal form ](https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=929E8al0JE8HYFaKgbvABXMQK2TZSJIJzPZJXlpQNowfGrrLBJoQiL3orvm&dispatch=5885d80a13c0db1f8e263663d3faee8d4fe1dd75ca3bd4f11d72275b28239088) for Minecraft donation page. First name is auto populated from the credit card data.

Autofill settings 
![image](https://cloud.githubusercontent.com/assets/17010094/18241320/529475f0-7348-11e6-9439-c49cf0634c8a.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18241332/614fbe74-7348-11e6-92c5-a381863cd34e.png)

**Comment by srirambv** [comment]
Similar issue on USPS.com account creation page

![image](https://cloud.githubusercontent.com/assets/17010094/18347219/4a02e5a4-75bc-11e6-9a12-8f27743be770.png)

**Comment by srirambv** [comment]
Same issue on Jurys Inn booking page. 

![image](https://cloud.githubusercontent.com/assets/17010094/18408647/486a2cb2-772d-11e6-8453-27c7bccbdd9b.png)

**Comment by lukemulks** [comment]
+1 from a Community Contributor for eBay.com 
Community URL: https://community.brave.com/t/brave-needs-to-be-able-to-distinguish-the-legitimate-use-of-pop-ups/2045

>_When selling an item on eBay, you start by entering a description of the item. As you type the description, a dropdown list should appear containing matches to the same or similar items that other users have already sold. This dropdown list never appears in Brave. Consequently, nothing happens when you press the "Sell" button._
