### ISSUE TITLE
Alipay loads very slow and doesn't load all web components

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3603]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Alipay loads very slow and doesn't load all web components

**Expected behavior:**
Webpage should load properly
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 RC1 
  Shields off
- Steps to reproduce:
  1. Visit [Alipay](https://www.alipay.com/)
  2. Takes awfully long time to load and doesn't load js file which breaks the web page navigation 
     3.
     Intermittent issue. Sometimes loads the script in the first try and sometime have to refresh the page couple of times to load. 
- Screenshot if needed:
  Chrome/FF
  ![image](https://cloud.githubusercontent.com/assets/17010094/18128209/97a45680-6f7c-11e6-9bca-68160ebcae9c.png)

Brave:
![image](https://cloud.githubusercontent.com/assets/17010094/18128186/77b7f2b4-6f7c-11e6-8d3b-beab0bc6c15a.png)

Console Error:
![image](https://cloud.githubusercontent.com/assets/17010094/18128344/25b393f0-6f7d-11e6-9688-8e7d320386cc.png)
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/does-alipay-loads-very-slow/10385

Let's talk about the issue there 😉
