### ISSUE TITLE
Copy to Clipboard not working on Bitly.com 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3605]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Shortened URL is not copied to clipboard when the copy button is clicked. Instead shows the `press ctrl+c to copy` message

**Expected behavior:**
Shortened URL should be copied to clipboard when the copy button is clicked
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 RC1
  Shields off 
- Steps to reproduce:
  1. Open bitly.com
  2. Enter any URL to shorten
  3. Click on the copy button to copy the link to clipboard.
  4. Shows message to copy rather than copying the link.
- Screenshot if needed:
  ![clipboard](https://cloud.githubusercontent.com/assets/17010094/18133131/4096e3b6-6f91-11e6-85fd-05d9b26a085c.gif)
- Any related issues:

**Comment by luixxiul** [comment]
Closing as fixed.
