### ISSUE TITLE
Disabling Payments doesn't retain states

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3612]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Disabling Payments doesn't retain states

**Expected behavior:**
Disabling and enabling payment should retains states

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, OpenSuse 42.1

- Brave Version:
0.11.6 RC2

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:
![paymnet](https://cloud.githubusercontent.com/assets/17010094/18138261/db537ff6-6fa3-11e6-9c1f-afe5e504e13f.gif)

- Any related issues:

**Comment by srirambv** [comment]
cc: @bbondy @diracdeltas @BrendanEich

**Comment by bbondy** [comment]
I don't think we have to block on ledger state being lost if they toggle beta on/off.

**Comment by mrose17** [comment]
@bbondy - i agree

**Comment by bbondy** [comment]
I'll most to the next hotfix

**Comment by diracdeltas** [comment]
Does the ledger synopsis come back if you open a new site like nytimes.com? For me state is retained, but the ledger doesn't see the synopsis until a new navigation event occurs.

At least in the screencap it appears the wallet state is preserved.

**Comment by srirambv** [comment]
@diracdeltas No it doesn't come back after navigating to a new site as well.

**Comment by bbondy** [comment]
ETA on this? It's possible we'll do an RC3 and if so we could include it.

**Comment by mrose17** [comment]
has anyone invoked the browser with `LEDGER_VERBOSE=true ...` to see what it thinks it is doing?

**Comment by srirambv** [comment]
Could not replicate the issue on 0.12.0
