### ISSUE TITLE
use updated ledger-publisher

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3613]
to get the latest curated list from ledger-publisher@0.8.57

cf., https://github.com/brave/ledger-publisher/issues/7

**Comment by alexwykoff** [comment]
Anything for QA to check with this update?

**Comment by mrose17** [comment]
the issue came up last week when i noticed that brendan had a `ledger-synopsis.json` file that was rather odd. the file was syntatically correct, but in a format not used  (ever) by the code, as required fields were missing.

to test, you can quit the browser, manually edit `ledger-synopsis*.json` to exclude the `window` from one or more publishers, and then start the browser.

you should see the publishers still be present in the preferences panel, and when you visit those publishers, they should start updating.

i have *no* idea how to automate this, by the way... sorry!
