### ISSUE TITLE
'Open all in tabs' does not work

### ISSUE THREAD

**Issue by charbelrami** [brave/browser-laptop#3614]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**

**Expected behavior:**

- Platform: Windows 10 64

- Brave Version: 0.11.6dev-RC2

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

![open_all_in_tabs](https://cloud.githubusercontent.com/assets/5647344/18138746/9bb438e6-6f84-11e6-86ad-5a59de70ca31.gif)

- Any related issues:

**Comment by srirambv** [comment]
An extra separator is shown in the right click context menu.
