### ISSUE TITLE
Find index order

### ISSUE THREAD

**Issue by charbelrami** [brave/browser-laptop#3615]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When switching 'match case', it goes to the last index, and then back to the first

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10

- Brave Version: 0.11.6dev-RC2

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![find_index](https://cloud.githubusercontent.com/assets/5647344/18138932/786a7d04-6f85-11e6-9794-4ed20aae23a0.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #2559
