### ISSUE TITLE
bookmarked pages not deleted from history after restarting

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3616]
**Describe the issue you encountered:** bookmarked pages are not deleted from about:history after restarting with the notification bar.

**Expected behavior:** 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32bit

- Brave Version: 0.11.6 RC2

- Steps to reproduce:
    1. Create a backup
    2. Open a page and bookmark it
    3. Enable "Browser history" of Private data options on ``about:preferences#security``
    4. Disable/enable smooth scrolling to display the notification bar
    5. Click "Yes"
    6. Open ``about:history``

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
@bridiver this sounds like we aren't saving state at all from that notification bar, could you check?

**Comment by bbondy** [comment]
is this the same as in 0.11.5?

**Comment by bridiver** [comment]
did about:history exist in 0.11.5? I get a blank page

**Comment by bridiver** [comment]
this doesn't appear to be dependent on this particular set of steps. I don't see that bookmarked pages are ever cleared from history regardless of how the browser is restarted
