### ISSUE TITLE
Some autofill automated tests are failing

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3618]
<img width="670" alt="screenshot 2016-08-31 13 46 59" src="https://cloud.githubusercontent.com/assets/831718/18139933/71a7564e-6f81-11e6-8967-c7dabcba3944.png">

/cc @darkdh

**Comment by darkdh** [comment]
If we want to run test on local for `Autofill`, we must make sure `~/Library/Application Support/brave/Web Data` is removed for now. We plan to add clear autofill and autocomplete function (https://github.com/brave/browser-laptop/issues/3358) and after that we won't need the prerequisite.

**Comment by bbondy** [comment]
@bridiver we need to use a whole different profile dir for tests for this reason too. Can we set an env var that would be used for dev and test mode to alter the profile dir?

**Comment by bbondy** [comment]
Please verify no data loss for upgrades for things like cookies and for things like bookmarks.

**Comment by bridiver** [comment]
the change has no effect on release builds
