### ISSUE TITLE
Address bar appears too slowly after opening a new window

### ISSUE THREAD

**Issue by xjru** [brave/browser-laptop#362]
This is somewhat annoying as it interrupts the workflow quite a bit. Not a huge issue though.

OS X 10.11.3

**Comment by bridiver** [comment]
Thanks @xjru . Are you seeing this running in dev mode or from a release build? We are working on improvements to the rendering speed in general.

**Comment by xjru** [comment]
I'm running the version that was linked to in the invitation email. I suppose that's a release build. The about box says 0.7.9 (0.36.3).

**Comment by diracdeltas** [comment]
Yeah, it takes about 1-2 seconds for me on OS X.

**Comment by bridiver** [comment]
Ok. I see it on dev as well, but wasn't sure if it was also slow in the release builds.

**Comment by luixxiul** [comment]
This is thought to have been fixed. Closing for now.
