### ISSUE TITLE
Show favicons applied on bookmark folders along with bookmarked items.   

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3622]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Show favicons applied on bookmark folders along with bookmarked items.   

**Expected behavior:**
Should only apply to bookmark items. Folders names should be displayed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 

- Brave Version:
0.11.6 RC2

- Steps to reproduce:
    1. Enable Favicons and Show only favicon in preferences menu 
    2. Folders also shows only icons instead of the folder name
    3. 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18145197/0cc75030-6fc2-11e6-82fe-dc1c6558f2c5.png)

- Any related issues:

**Comment by bbondy** [comment]
This is intentional, do you expect to see folder text?
We could perhaps allow for an option for that if it is common.
/cc @luixxiul

**Comment by luixxiul** [comment]
Showing a title on hover might work here.

**Comment by srirambv** [comment]
I agree with @luixxiul . Showing title on hover would be nice if not showing the folder name completely.

**Comment by bbondy** [comment]
great idea

**Comment by bbondy** [comment]
<img width="111" alt="screenshot 2016-09-01 16 28 09" src="https://cloud.githubusercontent.com/assets/831718/18183171/20a635c2-7061-11e6-8d5c-481cbc39212b.png">

It'll also cover this case of not seeing full name

**Comment by bbondy** [comment]
Moving to 0.12.1
