### ISSUE TITLE
Flash player is not working on my Win 7 PC

### ISSUE THREAD

**Issue by gracechurch99** [brave/browser-laptop#3624]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by gracechurch99** [comment]
Did you search for similar issues before submitting this one? NO

Describe the issue you encountered: Flash player not working
Platform: Win 7 Pro 64 bit
0.11.5

**Comment by luixxiul** [comment]
Which page do you experience the issue?

**Comment by Liunkae** [comment]
For any folks who are having problems with Flash, please read the [Flash troubleshooting wiki page](https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues).

No recent reports. Closing (but please reopen if needed).
