### ISSUE TITLE
ledger should check bitcoin handler for a specified session

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3625]
instead of assuming session is `''`

**Comment by bbondy** [comment]
all the sessions should be in sync as far as I recall so checking any is fine.

**Comment by bridiver** [comment]
it's an easy fix. Are you passing the partition from frames.js? If so you'll call `electron.session.fromPartition(partition).protocol.isNavigatorProtocolHandled('bitcoin')` when the fix is ready. You can't really use the sender because the ipc message is sent from the browser window

**Comment by bridiver** [comment]
@bbondy won't syncing the private partition -> regular leak data about the bitcoin handler?

**Comment by bbondy** [comment]
that comment was from aug 2016 so not related to sync, but it was just me thinking that the bitcoin handler was the same for all sessions. I don't think there's an api for web sties to see if something is registered.  Maybe that changed though since.
