### ISSUE TITLE
Right-to-left layout

### ISSUE THREAD

**Issue by Salman-Al7rbi** [brave/browser-laptop#3626]
- Linux Mint 18 64bit
- Brave Version:
  Brave: 0.11.6
- Screenshot :
  ![1](https://cloud.githubusercontent.com/assets/20955749/18147213/4deb19c4-6fdc-11e6-91df-a9a10ec52c4b.png)
  ![2](https://cloud.githubusercontent.com/assets/20955749/18147224/576cabfc-6fdc-11e6-9996-b9b61f16243c.png)
  ![3](https://cloud.githubusercontent.com/assets/20955749/18147230/5af7c7d4-6fdc-11e6-9dc0-9aaa546cf00d.png)

**Comment by luixxiul** [comment]
Setting a milestone for now.

**Comment by luixxiul** [comment]
hebrew is also right-to-left for example.

**Comment by luixxiul** [comment]
#6068 

In Hebrew (courtesy of @amire80)

<img width="1680" alt="2016 12 07 15 35 19" src="https://cloud.githubusercontent.com/assets/346271/20969689/d3f197de-bc92-11e6-88ef-625465cbc34c.png">
