### ISSUE TITLE
bitcoin wallet address overflows on some screen resolutions

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3629]
it should always be on the same line as the copy icon, not like:
 
<img width="845" alt="screen shot 2016-08-31 at 6 07 47 pm" src="https://cloud.githubusercontent.com/assets/549654/18150387/28d1d0b0-6f9b-11e6-8cef-315237222243.png">

**Comment by diracdeltas** [comment]
@jkup i think this will be irrelevant with the new ledger add funds panel design, but just keeping this open in case we do another release before that ships.

**Comment by bbondy** [comment]
Moving to 0.12.1 but please close if it's no longer applicable.

**Comment by mrose17** [comment]
related to https://github.com/brave/browser-laptop/issues/3484

**Comment by alexwykoff** [comment]
Marking this as 'no qa needed' since this particular dialog no longer exists.
