### ISSUE TITLE
Task Bar Settings (Hamburger) Icon Broken

### ISSUE THREAD

**Issue by karthicks** [brave/browser-laptop#363]
Click on the hamburger icon on the right hand side of the task bar, anytime, anywhere you're in brave. Nothing happens. I was hoping to see a settings menu or something along those lines.

**Comment by damengilland** [comment]
Duplicate of #310

**Comment by trouserless** [comment]
additionally, navigating through the menus to preferences (Brave->Preferences) is greyed out and therefore non-selectable.  Nor is the keyboard shortcut working as referenced by #366 

tldr; no way to see/edit preferences.

**Comment by diracdeltas** [comment]
As mentioned in #366, we don't have a preferences menu yet. Closing this as a dupe of #310 and #366.

**Comment by bbondy** [comment]
Fixed in 0.7.10 (which is available now)
