### ISSUE TITLE
Embedded Twitter videos not loaded on Huffingtonpost

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3633]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Embedded Twitter videos not loaded on Huffingtonpost

**Expected behavior:**
Embedded Twitter videos should be loaded.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 RC2
- Steps to reproduce:
  1. Visit [Huffingtonpost article](http://www.huffingtonpost.com/entry/mexico-trump-persona-non-grata_us_57c72e1de4b078581f10cd5f?section=&)
  2. Enabled Ad/Tracker at page level
  3. Embedded Twitter video is not loaded.
  4. Disable Ad/Tracker, twitter video loads.
- Screenshot if needed:
  Ad/Tracker Enabled
  ![image](https://cloud.githubusercontent.com/assets/17010094/18164563/78c88558-7038-11e6-903b-762413710010.png)

Ad/Tracker Disabled
![image](https://cloud.githubusercontent.com/assets/17010094/18164536/5240d1d8-7038-11e6-8fc2-4809977478a8.png)

Console
![image](https://cloud.githubusercontent.com/assets/17010094/18164592/a3630950-7038-11e6-96b3-bdc008e5d527.png)
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/embedded-twitter-videos-not-loaded-on-huffingtonpost/10104
