### ISSUE TITLE
If home page is a local file, the "Brave starts with: My Home Page" option doesn't work

### ISSUE THREAD

**Issue by mcollins451** [brave/browser-laptop#3635]
**Did you search for similar issues before submitting this one?**
Yes, I did.

**Describe the issue you encounteredl:**
I'm using Brave 0.11.6, just downloaded a few minutes agoe.  I use a local HTML file as my home page.  When I launch Brave it no longer loads the local file into the first tab. 

**Expected behavior:**
It should load the local file into the first tab.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7
- Brave Version:  0.11.6
- Steps to reproduce:
  1.  Create a local HTML file on your C: drive.
  2.  Go to Brave's Settings.
  3.  Set the "Brave starts with" setting to "My home page."
  4.  Set the "My home page is" setting to the name of a local file, such as "C:\Users\mcollins\Dashboard\index.html".
  5.  Exit Brave.
  6.  Relaunch Brave
- Screenshot if needed:
- Any related issues:

I reported this problem several versions ago, and it was fixed.  It reappeared in this latest version today.

**Comment by MKuenzi** [comment]
I can't reproduce this in latest master. The local file loads for me between browser restarts
