### ISSUE TITLE
some sites/services mis-identify brave and create confusion with their visual guides

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-laptop#3637]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
On zoom.us and other services they provide visual guides to install their web clients and the guide they show (based on user agent) does not match what is visible on the browser, which makes it confusing.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
- Steps to reproduce:
  1. Visit Zoom.us, see their plugin attempt to install (image 1)
  2. see that the message is presented by brave differently than the guide (image 2)
     3.
- Screenshot if needed:
  image 
  ![i1](https://cloud.githubusercontent.com/assets/420063/18176280/c5f0fc2a-7029-11e6-8699-72cec8a60c24.png)
  1:

image 2:
![i2](https://cloud.githubusercontent.com/assets/420063/18176283/c991a49c-7029-11e6-968d-97c485850f55.png)
- Any related issues:

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/3693
