### ISSUE TITLE
check for publisher rules update once a day

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3638]
cf., https://github.com/brave/ledger-client/issues/13

**Comment by alexwykoff** [comment]
How would QA go about testing this?

**Comment by mrose17** [comment]
in `ledger-state*.json`, the `rulesStamp` gives the timestamp of the next update.

because the rules might not change within a 24h period, it probably makes more sense to look for the stamp to update by approximately 86,400,000 after 24h.

yes, not a very easy thing to do, but there you have it.

alternately, you could modify the value to be in the past and set `ruleset` to `[]` run the browser for a couple of minutes and see if both `rulesStamp` and `rules` change (in a good way!)
