### ISSUE TITLE
Decide on strategy for conflicting CSP for safe ads

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#364]
Some iframe src will be blocked by the CSP setting.  

So safe ad insertions will be blocked.  We could perhaps use the webview's preload script to communicate in the html from a preloaded other webview.  We need this for perf anyway.

**Comment by diracdeltas** [comment]
I think the non-starters are:
* Modifying the site's CSP setting.
* Not using a sandboxed iframe.

From my reading of CSP2, I think `<iframe srcdoc = [some pre-rendered HTML] sandbox>` should not be blocked? (But note that the parent CSP policy applies to the srcdoc document)

**Comment by bsclifton** [comment]
no longer valid; we don't replace/insert ads
