### ISSUE TITLE
Wrong suggestions appear in the autocomplete list under URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3643]
**Describe the issue you encountered:** Wrong suggestions appear in the autocomplete list under URL bar. I typed "tw" and these two appear in the autocomplete list, which do not contain "tw" in the URL.
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18179231/6feffc0c-70bc-11e6-851c-90d7f254691d.png)

**Expected behavior:** They should not appear (twitter.com is not bookmarked and exists in the history)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 64 bit

- Brave Version: 0.11.6

- Steps to reproduce: not sure (I found this issue by dogfeeding)

- Screenshot if needed:

- Any related issues: #2169

Setting a milestone for now.

**Comment by bbondy** [comment]
Note this isn't fixed in 0.12.0-beta1 yet, but will be in the next build (RC1 it'll probably be called) the commit has the steps to test.
