### ISSUE TITLE
Have a way for new domains in ledger to be reviewed before being included

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3644]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Using Brave, it defaults new domains I visit to "include=true" in the ledger.  I’d hate to be on the day of reconciliation and have a bunch of the money go to sites I found Googling (or something similar), instead of my favorite content providers

**Expected behavior:**
Some ideas on how to possibly handle that:
- Setting which toggles default new domain include mode (include=true/false)
- Setting (and support for) a new "needs review" status which goes to include=true after a week (if decision to include or not is not made by user)
- More advanced criteria for adding a page to the ledger; increase the time spent?
- anything proposed below in the comment section :smile:

Maybe these could be exposed in a new "advanced" section?

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.11.6 and above

- Steps to reproduce:
    1. View Settings > Payments ; notice your current domain list
    2. Visit a website that is not in the list (and that you don't enjoy)
    3. Notice that domain now appears in Settings > Payments w/ "Include" as "on"

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/3580

**Comment by bbondy** [comment]
I was wondering if we should show more than top 20, maybe top 40 and only flip the include on the top 20 by default, at least that way you have some time t see what might slip in.

**Comment by bradleyrichter** [comment]
@mrose17 Can't we just increase the "price of admission"? This will keep out those one-hit sites that you googled past on your way to a content-filled page worth supporting.

The goal is to have "complete and decision-free" autopay to help support the sites you you most. So I think we need to keep adjusting the logic to make this happen for a wide audience 

Then we can make a few advanced settings for power users.

I think we will find out soon if we should limit the list to between 10 and 20.

**Comment by mrose17** [comment]
the minimum duration is 8s ... suggest an alternative?

**Comment by mrose17** [comment]
@bsclifton - does the notice 24h before hand satisfy this issue, cf., https://github.com/brave/browser-laptop/issues/3828  thanks!

**Comment by bsclifton** [comment]
Definitely works for me! :smile: If other readers have more input, please feel free to reopen and share your input
