### ISSUE TITLE
Please enable Flash for Geni.com

### ISSUE THREAD

**Issue by ogrgkyle** [brave/browser-laptop#3647]
This site will not function fully otherwise, even though it has a beta HTML5 version.

**Comment by luixxiul** [comment]
Will you take a screenshot of the page you experience the issue?

**Comment by ogrgkyle** [comment]
The HTML5 version looks very similar to the Flash version, but I have attached screenshots.  The first is a redirect page to HTML5, and the second is what the HTML5 version looks like.  (I erased some names.)  The HTML5 version, in my opinion, is too immature and underdeveloped to be the default.

When using Flash, the link is: https://www.geni.com/family-tree
When using HTML5, the link is: https://www.geni.com/family-tree/html5?no-flash-redirect=1

![screenshot1](https://cloud.githubusercontent.com/assets/13721084/18752974/a468d59c-80a9-11e6-9967-f3d73b53017f.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/13721084/18752975/a46fae12-80a9-11e6-804b-3229213dd394.jpg)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/does-html5-version-of-geni-com-not-work-well/10387

Let's reopen if it is confirmed that the HTML5 version does not work for many of us 😄 

@ogrgkyle If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
