### ISSUE TITLE
Favicons Only Behavior Now Leaves Blanks when there is no favicon

### ISSUE THREAD

**Issue by martyhaas** [brave/browser-laptop#3648]
I just downloaded Brave yesterday and became an instant fan. I imported my bookmarks and chose to only show favicons in the toolbar. Fortunately, those sites without a favicon displayed their title. But today it asked me to restart it to load an update. Once I had done so, those necessary titles were replaced by the blank, meaningless generic page icon. Any way we can reverse this? I really like using just the icons when they exist, but when they don't I need something to identify the icon.
This is on a Mac, OS 10.11.6.

![screenshot 2016-09-01 14 43 59](https://cloud.githubusercontent.com/assets/21693537/18181868/02f0f836-7053-11e6-8999-4fd3a9bc90e4.png)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5826#issue-191388793
