### ISSUE TITLE
Change Mac Shortcuts

### ISSUE THREAD

**Issue by damengilland** [brave/browser-laptop#365]
As a user used to Chrome, Firefox, Safari, or IE... the shortcuts in Brave feel off to me.  Would suggest the following:

* Apple + Shift + N should be New Privacy Window
* Apple + Shift + T should be re-open closed tab.
* F5 for refresh (50/50 on browsers doing this on Mac, but it's nice carry over from PCs)

Also would suggest using the convention of a "Privacy Window" instead of tabs in the same window.  Tabs in the same window just feels weird to me, I'd rather have a new window when I'm in "Privacy Mode."

**Comment by bbondy** [comment]
We'll have both private window and private tabs.
Command + Shift + T should already re-open closed tab no?

**Comment by luixxiul** [comment]
Closing for the moment. For Private window, under consideration #597
