### ISSUE TITLE
remove darkening for all non-modal dialogs

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3653]
If a dialog can be canceled by clicking outside of it's perimeter, then the browser should not be darkened.

example of improper use:
![image](https://cloud.githubusercontent.com/assets/13509546/18186585/69ff162a-7058-11e6-8947-61aad9689317.png)

**Comment by lucidNTR** [comment]
yes very annoying, will submit PR for this soon

**Comment by luixxiul** [comment]
pushed a temp fix to apply the gray background to the panel: https://github.com/brave/browser-laptop/pull/9034/commits/7527e4f6718e9056b5445a2091f2a6c9b90355bc

**Comment by luixxiul** [comment]
@bradleyrichter could you tell me what you think on that?

**Comment by bradleyrichter** [comment]
Yes please…

**Comment by luixxiul** [comment]
ok I'm going to work on that, thanks.
