### ISSUE TITLE
Ability to set monthly budget manually (not using preset options)

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#3654]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Currently you are limited to preset options for the monthly budget of Brave Payments. These are 5, 10, 15 and 20 USD.

I feel it would be beneficial to allow a custom amount to be entered. Perhaps with a minimum value to prevent very small Bitcoin transactions that incur high transcaction fees.

Personally, I do not mind setting a monthly budget of 5 or 10 USD. However, this is only a monthly budget for one browser on one computer. I frequently use Brave on 3 different computers, one of which has 2 differnet OSes. Setting the minimum 5 USD per browser in my configuration would result in an actual monthly budget of 20 USD.

If I were able to manually set the monthly budget, I would be able to accomodate for the multiple browsers I use over multiple computers and OSes.

**Expected behavior:** As described above, the ability to manually set the monthly budget with a minimum possible value.
- Platform (Win7, 8, 10? macOS? Linux distro?): n/a
- Brave Version: 0.11.6
- Steps to reproduce:
  1. Enable Brave Payments in Preferences.
  2. Note lack of manual entry under monthly budget.
- Screenshot if needed: n/a
- Any related issues: n/a

**Comment by bradleyrichter** [comment]
Hi @DivineOmega. Thanks for the suggestion. This is a great point. 

In the near future, you will be able to sync all of your Brave-enabled devices so that your contributions are combined if you choose, with the selected contribution value shared between them.

We can offer a lower value if there is enough demand but they need to remain as whole numbers to avoid the possibility of breaking anonymity. 

Do you think this solution would solve your problem? LMK if you have any further thoughts.


Thanks - Brad

**Comment by DivineOmega** [comment]
Hi Brad.

I think the synchronisation is an excellent solution. For the moment, as you suggest, adding a few lower value options would probably suffice.

Perhaps 1 USD and 2 USD options could be added?

Many thanks.

**Comment by mrose17** [comment]
For a future release!

**Comment by zentagonist** [comment]
@bradleyrichter can you please review this request?

**Comment by bradleyrichter** [comment]
@zentagonist As we move to BAT, we could consider adding a 4th (smaller) entry.

**Comment by Alino** [comment]
you should consider reversing the currencies in monthly budget dropdown and add the ability to enter custom amount of usd like mentioned in this reddit post.
https://www.reddit.com/r/BATProject/comments/7klngl/bat_monthly_budget_dropdown_should_revert_the/

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/brave-payments-smaller-monthly-pledge-options-needed/12751/4

**Comment by NumDeP** [comment]
I think as a minimum, 15.0 BAT (3.71 USD) is quite adequate for one months payment across multiple journals, channels, publishers.

However, I think there's a small bug that may allow this :) I don't know if you tried loading the browser after the initial install without WiFi but if you turn off the internet connection and turn on Payments for the first time it actually shows a list of additional options.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1055
