### ISSUE TITLE
All Safari Bookmarks Not Importing

### ISSUE THREAD

**Issue by scot30** [brave/browser-laptop#3655]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I first tried importing my bookmarks and notice the issue a few versions ago, but just now getting around to reporting it.  I searched, but didn't find this issue reported by anyone else.

In what's referred to as the "Favorites Bar" in Safari (equivalent of the "Bookmarks Toolbar" in Brave) I have several folders containing bookmarks plus a few individual bookmarks not in folders.  I also have a bunch of folders and individual bookmarks in the Safari "Bookmarks Menu".  I'm exporting the Safari bookmarks as HTML, but when I do the import not all of my bookmarks are getting imported into Brave.

Everything in the Safari "Favorites Bar" gets imported into the Brave "Bookmarks Toolbar" with absolutely no problems, but nothing at all from the Safari "Bookmarks Menu" gets imported anywhere into the Brave bookmarks - so I'm missing a big chunk of my bookmarks.

I've attached my Safari bookmarks export.

**Expected behavior:**
All bookmarks are imported.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X 10.11.6 El Capitan

- Brave Version:
0.11.6

[Safari Bookmarks.html.zip](https://github.com/brave/browser-laptop/files/451005/Safari.Bookmarks.html.zip)

**Comment by bsclifton** [comment]
cc: @darkdh (who is working on bookmark importing)

**Comment by bbondy** [comment]
This is just handled by html import which we handle by front end code, but it needs fixing.  Maybe we can move html import to what @darkdh is using too if chromium exposes an api.

**Comment by darkdh** [comment]
The importer I'm working on can cover import html file.

**Comment by darkdh** [comment]
dup #2107
