### ISSUE TITLE
Form suggestions dropdown not keyboard accessible

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3658]
**Did you search for similar issues before submitting this one?**

I searched for "dropdown" and "suggestions"

**Describe the issue you encountered:**

When entering info on a form, sometimes Brave offers up some recently used suggestions. They don't seem to be accessible without using a mouse.

**Expected behavior:**

Down arrow should move through them like a select box.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version:
0.11.6

- Steps to reproduce:
    1. Go to a site (my example is gtmetrix.com, you may need to enter a value and then refresh the page to make sure you get a suggestion)
    2. When the suggestions pop up, try to access them via the keyboard.

- Screenshot if needed:
![bug3](https://cloud.githubusercontent.com/assets/490294/18195949/7607903c-70a3-11e6-909b-6b71f250c241.gif)

- Any related issues:

**Comment by Sh1d0w** [comment]
There is already similar report dating from several months ago #1302

Unfortunately still not fixed, nor milestone set :(

**Comment by jkup** [comment]
@Sh1d0w thanks! I'll follow up on this tomorrow.

**Comment by bsclifton** [comment]
Closing as a dupe, but I shared that screenshot in the other issue :smile:
