### ISSUE TITLE
Cmd-comma on Mac should open preferences

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#366]
To fit in with Mac conventions, it's good to use Cmd-comma keyboard shortcut to open the preferences page or dialog box.

**Comment by diracdeltas** [comment]
The shortcut is hooked up, but we don't have a preferences page yet.

**Comment by bradleyrichter** [comment]
@stshank As we start implementing prefs, let us know if you have a short list of what you were hoping to find in prefs. We will try to hit the most common ones first. - Brad

**Comment by diracdeltas** [comment]
fixed thanks to @bbondy
