### ISSUE TITLE
Blank pages after using brave for some minutes

### ISSUE THREAD

**Issue by juanluperez** [brave/browser-laptop#3663]
**Did you search for similar issues before submitting this one?**
No.
**Describe the issue you encountered:**
I got blank pages every time I reload a page or open a new one after few minutes of using brave. It is happening from every version of brave I've been trying.
**Expected behavior:**
To see web pages normally
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux Mint 18 (64bits)
- Brave Version:
  Brave: 0.11.6
  Electron: 1.3.8
  libchromiumcontent: 52.0.2743.116
  V8: 5.2.361.49
  Node.js: 6.3.0
  Canal de actualización: dev
- Steps to reproduce:
  1. Open brave an browe some websites
  2. Wait some minutes
  3. Open new sites or reload previous opene ones
- Screenshot if needed:
- Any related issues: #1471

**Comment by Sh1d0w** [comment]
Can you please open the Terminal and launch brave from there by executing the `brave` command. Then when this occurs again please copy any output you get in the terminal to this issue please, so we can see if there are any errors logged.

Also is it happenng when you open some specific websites, or it is happening no matter what pages you are browsing?

**Comment by juanluperez** [comment]
Hope to have something to post here soon.

**Comment by juanluperez** [comment]
It is happening again and there is no output in terminal.
It is happening apparently no matter what pages I'm browsing.

**Comment by juanluperez** [comment]
This problem persists and it never shows anything in terminal.

**Comment by juanluperez** [comment]
This might be related to hardware graphic acceleration. I use another electron based software and they provide an option called --ignore-gpu-blacklist to workaround this...

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5059

**Comment by luixxiul** [comment]
@alexwykoff will you please ask the user if it is possible to confirm this issue persists using the test case linked in https://github.com/brave/browser-laptop/issues/1471#issuecomment-251916315 ?

**Comment by darkdh** [comment]
+1 from support
https://linkbubble.zendesk.com/agent/tickets/5725

**Comment by juanluperez** [comment]
@luixxiul I reproduced this issue using the test case linked in #1471 (comment)
Right after navigating that link every new tab opened is blank.

**Comment by luixxiul** [comment]
@juanluperez thanks! do you see the blank devtool with Shift+F8 like this? https://github.com/brave/browser-laptop/issues/1471#issuecomment-221529713

**Comment by juanluperez** [comment]
@luixxiul Yup! Also blank this devtool. And if you try go to settings, payments and try to change month payment you'll get this:
![screenshot](https://cloud.githubusercontent.com/assets/9903127/19271263/2a6384ac-8fc4-11e6-9fec-211cafbb1deb.png)

**Comment by alexwykoff** [comment]
@luixxiul waiting on their initial reply to see if they would lend a hand in the investigation. 
It does appear that @juanluperez was able to repro however.

**Comment by magoo65293** [comment]
Well I'm not a computer geek like y'all apparently are, I'm just sad that my new favorite browser is doing this now.  : /
Back to Firefox..... <sigh>

**Comment by aironou** [comment]
Using Arch Linux (64 bits) with X.org ATI video driver (xf86-video-ati), I got the same problem. But, the same happens with others softwares builded with Electron, like [Franz](http://meetfranz.com/).
Running Brave with --disable-gpu, "solved" the problem (works for Franz too).

At work, I use Arch Linux (64 bits) with X.org Intel video driver (xf86-video-intel) and Brave doesn't have this problem.

Brave: 0.12.7
Electron: 1.4.20
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0

(sorry for my English, it isn't my native language)

**Comment by bsclifton** [comment]
I've created a [brand new wiki entry](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page) which I hope helps 😄  Folks, can you please try the following steps for me?

1. Install latest version of Brave (as of now, this is 0.13.0)
2. See if you have the issue; Chromium always includes bug fixes which may resolve the issue
3. If you still have the issue, please close Brave and edit your shortcut to add the command line argument `--ignore-gpu-blacklist`. Relaunch and see if this resolves the issue
4. If this does not resolve the issue, please edit the shortcut and instead try `--disable-gpu`

Thanks in advance to anyone who can try this- your time is very much appreciated and will help other users.

cc: @aironou @magoo65293 @juanluperez

**Comment by aironou** [comment]
@bsclifton I installed latest version, but still having the issue.
Trying the arguments --ignore-gpu-blacklist or --disable-gpu didn't worked either.

I downgraded to version 0.12.15 and both arguments solved the issue.

**Comment by bsclifton** [comment]
@aironou thanks for the report! This is really good to know.  It seems we still have more troubleshooting to do

**Comment by aironou** [comment]
@bsclifton In version 0.13.1 (rev: 9dd06f9463d155291efdb419ad0df4c2df16b611) the arguments `--ignore-gpu-blacklist` and `--disable-gpu` are solving the issue again. (:

Brave: 0.13.1 
rev: 9dd06f9463d155291efdb419ad0df4c2df16b611 
Muon: 2.0.18 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.9.6-1-ARCH 
os.arch: x64

**Comment by bsclifton** [comment]
Awesome- glad to hear it is resolved using those args. Thanks for the update, @aironou 😄

**Comment by dlombardo** [comment]
I am having this same issue, I tried both `--ignore-gpu-blacklist` and `--disable-gpu' neither seem to solve the issue.

I am running version 0.14.1 (from here: https://aur.archlinux.org/packages/brave-bin/)
Arch Linux
Radeon R9 290X using `xf86-video-amdgpu`

**Comment by aironou** [comment]
@dlombardo I had the same issue, but was a problem of PKGBUILD.

If you see on line 36, there is:
```sh
exec /usr/lib/$pkgname/brave --no-sandbox -- "\$@"
```

Try write  `--ignore-gpu-blacklist` or `--disable-gpu` before `--no-sandbox` and then install the package.
This solved this issue for me.

(sorry for my English)

**Comment by dlombardo** [comment]
@aironou  Thanks, I did that with the `--ignore-gpu-blacklist` arg and it seems to be working well for now... Will report if anything changes

**Comment by luncht1me** [comment]
![image](https://user-images.githubusercontent.com/3420404/34278709-5d0d3fe8-e661-11e7-9c47-5d2f5df8b52d.png)

This is all I get running Brave on Win 10 64bit.

I'm a developer, and have Node v8.7.0 installed.

**Comment by bsclifton** [comment]
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue
