### ISSUE TITLE
Yahoo Mail Attachment is causing Brave to crash

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3667]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Reported by @paz5050 on Twitter : When attempting to add an attachment to Yahoo Mail, the Brave browser crashes.  Used on Windows 8.

Initial investigation could not reproduce the issue on a Windows 7 VM with 0.11.6.

**Expected behavior:**
The attachment should be added without issue.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 8
- Brave Version:
  Unknown.
- Steps to reproduce:
  1. Log into Yahoo mail.
  2. Compose a new message.
  3. Attempt to add an attachment.
- Screenshot if needed:
- Any related issues:
  https://github.com/brave/browser-laptop/issues/716 seems to be similar.

**Comment by bbondy** [comment]
could you ask him which version he's on? I tried to create a Yahoo account and attach a file on Windows and macOS but couldn't repro. I tried 7 but it shouldn't be diff from 10.

**Comment by luixxiul** [comment]
For now I'm going to close this issue as stale in favor of this topic on our community site.

https://community.brave.com/t/yahoo-mail-attachment-is-causing-brave-to-crash/10386

Let's reopen if we receive other reports there 😉
