### ISSUE TITLE
Enable Smooth scrolling doesn't work on Windows 10

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3669]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Smooth scrolling doesn't work on Windows 10. Works properly on Chrome.

**Expected behavior:**
Smooth scrolling should would when enabled in pref menu
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.11.6 Dev
- Steps to reproduce:
  1. Enable smooth scrolling from pref menu
  2. When trying to scroll using the touchpad/trackpad jumps down instead of scrolling as specified in windows settings.
  3. 
- Screenshot if needed:
  Chrome /Brave (notice the highlighted area on the bottom right corner which shows the two finger scroll)

![scroll](https://cloud.githubusercontent.com/assets/17010094/18215422/03109bd6-7149-11e6-9d13-42f65604a88a.gif)
- Any related issues:

### Additional Information
- Issue happens even with `Enable smooth scroll disabled` 
- Issue reproducible on multiple machines

**Comment by luixxiul** [comment]
Has this been fixed?

**Comment by srirambv** [comment]
+1 from communityhttps://community.brave.com/t/scrolling-on-a-laptop-not-smooth-using-the-trackpad/2605

**Comment by srirambv** [comment]
>Has this been fixed?

@luixxiul No this is still an issue on Windows using trackpad. Scroll jumps with two finder scroll and is not smooth.

**Comment by sknesebeck** [comment]
Same issue here. Not fixed yet. Makes scrolling websites a pain / almost unusable...

**Comment by Carbuzzer** [comment]
I'm surprised this hasn't been fixed yet. This definitely should be the top priority, because it's unusable on Windows Laptops.

**Comment by CarstenLarsen** [comment]
Brave is my favorite browser on Android, but unfortunately not on Windows because of this bug. 
I agree with previous comments, this bug should be high priority because it makes the browser experience extremely poor on laptops.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/scrolling-bug-with-laptop-use/3706/

**Comment by bhardwick** [comment]
What's the status of this? I can't really use Brave on my laptop until this is fixed.

**Comment by bsclifton** [comment]
@bhardwick no update on our side yet ☹️  I'll update the priority

**Comment by pwybman** [comment]
Extremely annoying issue, but here's a temporary remedy: when you minimize and reopen the brave window, scrolling works again. The issue only seems to arise when you first open the browser, and don't minimize. Hopefully this gets fixed soon though.

**Comment by swachtma** [comment]
The note from @freedomcoinproject about minimizing and reopening the window resolves the issue for me as well.  You just have to unfortunately do that for every new window.  I'm running Windows10 x64 like others in this thread.  

I'd also suggest that smooth-scrolling enabled should maybe be the default from install.  Without it, my first impression of Brave was that it was laggy.  Users who don't think to look for a smooth scroll feature might get turned off and quickly abandon the browser if they don't realize this is a tuneable feature.

**Comment by srirambv** [comment]
+1 from @BraveSupporter via #12759

**Comment by BraveSupporter** [comment]
Seems to be a computer to computer problem. Installed brave on another laptop. Same specs, and the scrolling issue is not there.

**Comment by YetiWilson** [comment]
Smooth scrolling works in full screen, is jumpy with 2 finger swipe in window mode.  After sleep 2 finger scrolling does not work at all.  Need to close brave and restart.

Windows 10 x64

**Comment by bsclifton** [comment]
This may or may not be fixed with our [Developer channel] release - would be great if someone can confirm. Build can be downloaded from:
https://brave.com/download-dev
