### ISSUE TITLE
New Tab context menu not needed options

### ISSUE THREAD

**Issue by charbelrami** [brave/browser-laptop#3670]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
'Reload' and 'Clone' are not useful in the context menu of a new tab

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 64

- Brave Version:
0.11.6dev

- Steps to reproduce:
    1. Click the right button on a New Tab

- Screenshot if needed:
![new_tab_context_menu](https://cloud.githubusercontent.com/assets/5647344/18215806/7d38bc9c-7129-11e6-91f1-d68cb74a189f.png)

- Any related issues:

**Comment by bradleyrichter** [comment]
@charbelrami nice catch. thanks!

**Comment by Liunkae** [comment]
If you don't mind, I already have a patch for this (#3713).

**Comment by bbondy** [comment]
Actually clone is still a valid operation as well regardless of the current page. Because it clones the full history, you might just want a copy of the history.   Reload isn't needed for now, but it should be for example an intermediate page is.  New tab should be allowed always.
