### ISSUE TITLE
passwords.properties not being loaded at app level

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3671]
Noticed this error while debugging the browser process

**Comment by alexwykoff** [comment]
Anything for QA to check with this?

**Comment by alexwykoff** [comment]
From the commit:
Test Plan: Make sure password strings can be localized, not needed once per platform just @luixxiul can verify

**Comment by luixxiul** [comment]
It seems that ``passwords.properties`` is not applied correctly.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18260194/6dc8defe-7426-11e6-8d42-d08acb48f72f.png)

**Comment by bbondy** [comment]
Actually it is just an l10n file update now, I did it on master but it didn't make this release unfortunately unless we have to respin rc2. I think it'll go out though.

**Comment by luixxiul** [comment]
It is the same on the 0.12.0.

The strings on the pop up dialog above have been translated since months, It seems that something else needs modifying too.
https://github.com/brave/browser-laptop/blame/master/app/extensions/brave/locales/ja-JP/passwords.properties#L13

**Comment by bbondy** [comment]
you'll have to try on master, the strings didn't make it in on time for 0.12.0
