### ISSUE TITLE
www.rt.com/on-air/ and http://www.dw.com/en/media-center/live-tv/s-100825 fail to play

### ISSUE THREAD

**Issue by warriormouse** [brave/browser-laptop#3674]
http://www.dw.com/en/media-center/live-tv/s-100825 and www.rt.com/on-air/ fail to load flash player 

Bravery protection is off. 
PPAPI 22 loaded, 
Brave version 0.11.6 details in attached screenshop
Windows 10 Home version details as per attached screenshot
![rt not playing](https://cloud.githubusercontent.com/assets/21962443/18220622/11be5ff4-71c8-11e6-8339-6765874e74da.jpg)
![brave version](https://cloud.githubusercontent.com/assets/21962443/18220623/1271e286-71c8-11e6-8296-d8f8ecb7a02a.jpg)
![pepper flash installed brave](https://cloud.githubusercontent.com/assets/21962443/18220627/13e40f04-71c8-11e6-8d11-66af1c62ae46.jpg)
![pepper flash installed](https://cloud.githubusercontent.com/assets/21962443/18220650/39f3e5b6-71c8-11e6-9e7f-13dc7ab96728.jpg)
![system details](https://cloud.githubusercontent.com/assets/21962443/18220699/bda0e5a8-71c8-11e6-9133-663ab641615c.jpg)

**Comment by luixxiul** [comment]
Now both sites can be loaded fine 👍
