### ISSUE TITLE
Upgrade to Chromium v54 on or around Oct 18th, 2016 (1 week before potentially)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3679]

**Comment by bbondy** [comment]
This also involves GYP -> gn

**Comment by jsnar** [comment]
Should we report this to Electron as well?

**Comment by bbondy** [comment]
they have it in progress already, but we're doing it independently

**Comment by bbondy** [comment]
Closing this since 0.13.0 will have it.

**Comment by luixxiul** [comment]
Test plan: Open `about:brave`
