### ISSUE TITLE
zoom level is not remembered

### ISSUE THREAD

**Issue by fabricedesre** [brave/browser-laptop#368]
STR:
- go to eg. http://www.nytimes.com/
- click on an article
- zoom in
- go back to http://www.nytimes.com/ using [<]
- go forward to the article using [>]

Expected:
The article is always zoomed in.

Observed:
The zoom factor is reset at every page load.

I haven't checked but it seems that Firefox is doing a per-origin zoom factor which makes sense in general.

**Comment by timcarr89** [comment]
Zoom level seems to be remembered when all but the containing directory of a URI is the same. For example, navingating on google results pages the functionality works as expected.

On the imaginary page: "example.com/site/page1.html". If a link points to any other page within the "/site/" directory (excluding its subdirectories), the zoom level is kept, otherwise it resets.

**Comment by ckknight** [comment]
My zoom isn't even remembered with the following steps:

* go to e.g. https://www.reddit.com/
* zoom in
* refresh

Expected:
Zoom level stays the same before and after refresh

Actual:
Zoom level resets to 100% after refresh

**Comment by morinted** [comment]
I'll add to this and say that on subsequent zoom ins (after the page zoom has been "forgotten") using command/control plus, command/control minus, you'll get it relative to the previous zoom level.

I'll write this in sequence, assuming that every command/control plus adds 10% to the zoom level:

1. Page load, zoom 100%
2. Press command/control plus, zoom level goes to 110%
3. Command/control R, page refreshes, is back at 100%
4. Press command/control plus, zoom level goes to 120%

So it would seem that the zoom level is just not reapplied on page load, but it is remembered.

**Comment by HoltMansfield** [comment]
Dealbreaking issue for me

**Comment by ham1** [comment]
Also, I'd expect zoom level to be remembered across tabs. e.g.
1. Open https://github.com/brave/browser-laptop/issues
2. Zoom out (pressing ctrl + -)
3. Open an issue in a new tab with Ctrl+click

Expected: New tab to be same zoom level as tab in step 1
Actual: New tab has default zoom level

Also:
4. Open a different issue in a new tab with Ctrl+click (from tab in step 1)

Expected: New tab to be same zoom level as tab in step 1
Actual: New tab has default zoom level

Finally:
1. Open https://github.com/brave/browser-laptop/issues
2. Open 2 new issues in 2 new tabs with Ctrl+click
3. Zoom in/out on the first issue (pressing ctrl +/-)

Expected: All 3 tabs to match the zoom level of the zoomed out tab.
Actual: Other 2 tabs have default zoom level
