### ISSUE TITLE
Upgrade to Chromium v56 on or around Jan 31st, 2017 (1 week before potentially)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3681]
56.0.2924.76

https://github.com/brave/browser-laptop-bootstrap/tree/chromium56
https://github.com/brave/muon/tree/chromium56
https://github.com/brave/browser-laptop/tree/chromium56

**Comment by darkdh** [comment]
Known issues:

- [ ]  Autofill not working
- [ ]  Renderer crash when navigating to the page from google search result
- [ ]  Undefined symbols of v8 inspector on windows
