### ISSUE TITLE
Dreadful payment experience for non-US citizens

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3683]
**Did you search for similar issues before submitting this one?**
Indeed.

**Describe the issue you encountered:**
I don’t live in the USA and I don’t own any BitCoin nor do I know how to get hold of any. In other words, I’m the average user coming to Brave for the first time. The [_Coinbase Buy Widget_ is only available to US citizens](https://developers.coinbase.com/docs/buy-widget). When I attempt to use it I’m rudely interrupted, and asked to review alternative methods for buying BitCoins through CoinBase. There is no obvious way for people outside the US to obtain BitCoins so they can start paying Brave. The alternatives that CoinBase have require me to purchase hundreds of dollars worth of coins, give them a photo copy of my passport (!), and submit to insane international wire transfer fees.

I’ve now spent an hour researching on the web about how to obtain a small amount of BitCoins so I can fill my Brave wallet with a couple of dollars. I’m still no closer to giving Brave my money despite my best effort. I’m also very confused as to how many BitCoins I should purchase to fill the 5 dollar minimum monthly payment.

**Expected behavior:**
A form asking for credit card information surrounded by promises about keeping my payment details safe etc. I couldn’t care one bit about the whole BitCoin thing. I _want to pay_ but the barrier to entry appears sky-high at the moment.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
All.

**Brave Version:**
0.11.6

**Steps to reproduce:**
    1. Be anywhere in the world except the United States (VPN).
    2. Open about:preferences#payments, and toggle On
    3. Click Add Funds, and then Buy With Coinbase

**Comment by mrose17** [comment]
thanks for thoughtful description! and sorry for the experience. ok, help me fix it!

please ping me at mrose@brave.com 

many thanks!

**Comment by mrose17** [comment]
marking this as closed, since it is overtaken by https://github.com/brave/browser-laptop/issues/3711
