### ISSUE TITLE
Favicons missing on ledger

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3684]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**

I think a few people are talking about this. We seem to be missing a lot of favicons from the ledger page.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version:

0.11.6

- Steps to reproduce:
    1. Go to Preferences
    2. Enable Ledger (view some sites)
    3. Check the ledgerTable

- Screenshot if needed:
<img width="855" alt="screen shot 2016-09-02 at 9 09 38 pm" src="https://cloud.githubusercontent.com/assets/490294/18222619/d9eb1d72-7151-11e6-84f7-9afabe468324.png">

- Any related issues:

**Comment by mrose17** [comment]
@jkup - thanks for reporting this. there is some kind of "timing thing" going on.

one caveat: the sharingbuttons.io site is not configured right in that it is missing the favicon.ico / favicon.png files that you see in the repo...
