### ISSUE TITLE
Spellcheck language should depend on keyboard layout

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#3691]
Current spell checking is limited to one pre-defined language (US English only?). As a bilingual user, I need to be able to set and switch between two dictionaries for spell-checking. 

Ideally, the dictionary should be tied to keyboard language and switch to English dictionary when my keyboard layout is set to US and switch on-demand to Norwegian when I switch to a Norwegian keyboard layout. This matches the user experience of iOS, Android, and Windows Mobile plus Windows 10 Store apps-type programs.

**Comment by Liunkae** [comment]
Related issue: #2183

**Comment by fabrimago** [comment]
so when is this going to be addressed? I think multi language spell check is very urgent. I like brave but if I see that spell check requests are already more then half year old and nothing happens I will think to go back to Chrome.

**Comment by luixxiul** [comment]
I think it is not planned until 1.0

**Comment by Liunkae** [comment]
#2183 covers changing the spellcheck language. I'll rename this issue to focus on changing the spellcheck language with the keyboard layout.

**Comment by luixxiul** [comment]
I'm going to close this suggestion as you can select multiple languages for checking spells.
