### ISSUE TITLE
Add automated test for making sure bookmark custom title appears on bookmark toolbar

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3694]
This test should add a bookmark with a custom title and make sure it shows that custom title.

Code to modify for the test is here:
`test/components/bookmarksTest.js`

Tests for each React component (UI element) is in `test/components` and it maps to `js/components` code.

You'll notice this test is currently split into 2 parts, bookmarking titles of pages with titles, and sites without titles. So you'll add 2 new tests in this issue, one for each.

Most of how tests work is using the DOM inspector with Shift+F8 dev tools to find what the css selector is for a certain DOM element.  You can test your CSS selector to make sure it selects the correct element just by opening the browser manually, opening browser dev tools and in the console typing document.querySelector('your-selector-here').

Always try to make sure individual `it` blocks in the test do not depend on each other.  The `describe`'s before block usually sets up the test, and then each `it` tests something about it.

The best way to figure out details of the test is just to read other tests but we have some good documentation including debugging information here: https://github.com/brave/browser-laptop/blob/master/docs/tests.md

**Comment by luixxiul** [comment]
Can this be closed with https://github.com/brave/browser-laptop/commit/bdb5f6a33b8eccd0f8f2b9177a243e3ca8053829?

**Comment by alexwykoff** [comment]
I did the first half and left the second half to @srirambv to wrap up as we were remote pair programming.  He'll be afk until 17/10/2016 so I will check with him then.

**Comment by bsclifton** [comment]
This one would be easy to add a test for now; I created a bookmarksToolbar test here:
https://github.com/brave/browser-laptop/blob/master/test/components/bookmarksToolbarTest.js

It actually already uses selectors testing against the customTitle... but it would be good to put an explicit test in place :smile: cc: @srirambv @alexwykoff

**Comment by NejcZdovc** [comment]
Custom title will be removed in #9978, so this issue is not  relevant anymore

**Comment by NejcZdovc** [comment]
Will set PR to close it :smiley:
