### ISSUE TITLE
http auth is not supported

### ISSUE THREAD

**Issue by fabricedesre** [brave/browser-laptop#370]
Well, brave displays the error page, but that doesn't help much ;)

**Comment by vekat** [comment]
Indeed, I just noticed this when I tried to access my router's web interface.
It needs to support the basic auth login prompt when unauthorized.

**Comment by diracdeltas** [comment]
Confirmed with this test case: https://www.w3.org/Member/

I wonder if this is related to popup blocking, cc'ing @bridiver

**Comment by bridiver** [comment]
Cookie based auth through popup windows works in all cases that I have seen (we added support to Electron for allowing popups with user gesture), but http auth is a known issue that we haven't looked into yet. Electron does not support "prompt" which is likely part of the problem, but there may be other changes necessary to support this. HTTP auth is not very common anymore, but we definitely want to support it. @bbondy may have more info on prioritization for this. Pull requests are always welcome of course and we are using our own fork of electron at https://github.com/brave/electron if anyone wants to take a look.

**Comment by bbondy** [comment]
We just need to handle this like so:
https://github.com/atom/electron/pull/3250

We'd set some state to indicate we should show the auth div saving the callback, and then render that and when they submit call the callback with the username and password.

**Comment by NeilMasters** [comment]
The work around(admittedly not the best) is to pass the auth details across in the url for example http://username:password@example.com

Brave remembers the user/pass for the current session anyway so no need to re-auth constantly.

**Comment by designfrontier** [comment]
This bit me with an okta SAML/Active Directory login. Completely blows up without showing a basic auth dialog for me. I can provide better repro steps and screen shots if needed.

**Comment by huuhaa** [comment]
Any estimated time when this will be fixed?

I tried to login at my Inteno DG200ALA router and got only blank page, with no errormessage at all (no login prompt etc.). But it's probably the same issue described at here earlier?  Tried also with fingerprint protection disabled but same result.

**Comment by bsclifton** [comment]
@huuhaa does anything show in console, if you open the dev tools? (ex: F12 or cmd+option+i) Any info about that is appreciated.  You can also open the network tab and see what HTTP response you are sent back (which I would assume is a 401 challenge, if you're expecting to see basic auth prompt)

**Comment by NeilMasters** [comment]
In my case this issue is now resolved for me on last release.
