### ISSUE TITLE
UI tweak: Insecure dialog has some white on the right

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3708]
<img width="425" alt="screenshot 2016-09-04 12 27 29" src="https://cloud.githubusercontent.com/assets/831718/18232312/33726202-729b-11e6-936c-5d56196a8ea4.png">

probably a div needs width: 100% or something like that.

/cc @bridiver

**Comment by bridiver** [comment]
strange, that wasn't there when I merged it
https://cloud.githubusercontent.com/assets/34129/18185814/39195a06-7054-11e6-9e1a-7fd08c90bf8c.png

**Comment by darkdh** [comment]
I just tested it with master but I didn't have the white thing on the right
<img width="627" alt="screen shot 2016-09-05 at 01 00 03" src="https://cloud.githubusercontent.com/assets/11330831/18232549/2571b176-7304-11e6-8eb1-7cc4cd093ece.png">

**Comment by srirambv** [comment]
Shows a vertical scroll bar on windows 10
![image](https://cloud.githubusercontent.com/assets/17010094/18240198/2778b012-7342-11e6-8213-eec25b91bd24.png)

**Comment by bbondy** [comment]
Thanks Sriram, that explains what I was seeing, kind of. Fix is easy now.

**Comment by bbondy** [comment]
no rogue re-opening @bradleyrichter ! 😛

**Comment by bradleyrichter** [comment]
@bbondy ghost in the system...first time seeing this one.
