### ISSUE TITLE
Autofill popup should dismiss when you tab out

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3709]
**Did you search for similar issues before submitting this one?**
Autofill popup should hide when you change focus 

**Describe the issue you encountered:**
The autofill popup stays open and is hard t dismiss.

**Expected behavior:**
The autofill popup should hide when you tab out.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS but probably all

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Make sure you have some autofill data avail
    2. Go to Go to http://www.roboform.com/filling-test-all-fields  and double click on the first name field to get a popup
    3. Press tab

- Screenshot if needed:
<img width="424" alt="screenshot 2016-09-04 12 31 49" src="https://cloud.githubusercontent.com/assets/831718/18232332/913f11aa-729b-11e6-8488-3c4ccc9714f1.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/860

**Comment by bridiver** [comment]
seems like changing tabs should always clear open popups. Do we need special handling for autofill or should we just close by default?
