### ISSUE TITLE
Reduce package and installer sizes

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#371]
Things like abp-filter-parser-cpp build files that aren't needed are included. We can slim down this installer by a lot.
#4080 #4081 #3193

**Comment by bbondy** [comment]
Windows: 130MB -> 84MB
OSX: 103MB -> 68MB
Leaving this open though because there are more ways to reduce the size by a lot.

**Comment by Hrxn** [comment]
I didn't directly ask about the size of the installer, my actual question was: Is it bundled with Node, in any form?

**Comment by bbondy** [comment]
Thanks for clarifying @Hrxn.
Electron is built using parts of Node for package loading and libchromiumcontent.
Brave is based on Electron.

**Comment by bbondy** [comment]
Independent of the previous conversation message. This ticket can be closed when we're smaller than Chrome on both platforms.

Chrome:
OSX for Chrome is 63.1MB
Windows: 49.7MB

Brave:
Windows: 84MB
OSX: 68MB

**Comment by luixxiul** [comment]
@bbondy How about now?

**Comment by bbondy** [comment]
We can still reduce more but haven't focused on it yet.

**Comment by posix4e** [comment]
Perhaps we should build a new more specific issue and close this one?
