### ISSUE TITLE
detect Brave Payments user location and display different dialog content 

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3711]
In order to prevent users who are outside of the USA from attempting to buy/transfer bitcoin using the Coinbase widget, we need to detect their location and change the visible elements of the dialog.

(see dialog spec: #3677)

USA:
![image](https://cloud.githubusercontent.com/assets/13509546/18232775/fba7f1de-728b-11e6-87e3-d1e025c04fde.png)

ROW:
![image](https://cloud.githubusercontent.com/assets/13509546/18232785/25f7ac2c-728c-11e6-9fcb-e09b7a1ca0b8.png)

**Comment by Aeyoun** [comment]
Do not recommend buybitcoinworldwide.com. They talk up their partner websites (affiliates) over other options. They also underreport on the fees at their partners’ websites. They’re not a trustworthy and critical source for financial information.

**Comment by bradleyrichter** [comment]
@Aeyoun Thanks for the info. 

@mrose17 Please source the replacement or suggest otherwise. Perhaps a "learn more..." button  linked to a specific Brave web page instead which is easier to manage/update and has more room to explain the issue for these ROW users.

**Comment by JTuwiner** [comment]
@Aeyoun @bradleyrichter Hey, I'm Jordan Tuwiner, founder of Buy Bitcoin Worldwide. 

We try to provide accurate information on fees. We also have no direct partnerships with any particular company. Could you please show me the places where we published incorrect fees? Please let me know so I can make the necessary corrections.

**Comment by Aeyoun** [comment]
> We also have no direct partnerships with any particular company.

Bull. Shit. For example, tour Coinhouse review has affiliate links which are undicsloed and they’re even masked by a redirect. You’re violating FTC’s Endorsement Guides right there. It’s hard to differentiate links that take you to pages on your site with more details, and the affiliate links that take you directly to the exchange. CEX.io fee structure is copied from their promotional pages and don’t reflect the actual fees you’re charged when using the service. Cubits isn’t mentioned on the “pay with credit card” page even thought they have the best terms and fee structure (but they don’t accept US affiliates …).

**Comment by willy-b** [comment]
@JTuwiner, could @Aeyoun just submit a PR to the BuyBitcoinWorldwide repo (https://github.com/BuyBitcoinWorldwide/buybitcoinworldwide.github.io) to add Cubits as an exchange?

The 'How Can You Help' section of the README seems to explain how to add an exchange to the site:
![buybitcoinworldwide_howcanyouhelp](https://cloud.githubusercontent.com/assets/6969859/18235397/453f6c4e-72cf-11e6-84b3-ab717af0d148.png)

I don't see anything about affiliate marketing there

**Comment by Aeyoun** [comment]
> I don't see anything about affiliate marketing there

It’s not discloused (see above). Outgoing links to the exchanges go through buybitcoinww.co which inserts affiliate codes.

**Comment by willy-b** [comment]
I think the fact that you can open an issue at https://github.com/BuyBitcoinWorldwide/buybitcoinworldwide.github.io , discuss that there, and open a pull request to fix whatever you feel is the problem actually recommends BuyBitcoinWorldwide as a good site to link to.

**Comment by JTuwiner** [comment]
You're welcome to believe whatever you'd like, but all of the affiliate programs used by us are publicly available to any other company or person who signs up. We don't receive any special bonuses from any particular company. 

> For example, tour Coinhouse review has affiliate links which are undicsloed and they’re even masked by a redirect. You’re violating FTC’s Endorsement Guides right there.

This is a common link structure used by most websites that do affiliate marketing. 

> t’s hard to differentiate links that take you to pages on your site with more details, and the affiliate links that take you directly to the exchange. 

You are definitely right about this, and I need to create a way to make these links more clear. 

> CEX.io fee structure is copied from their promotional pages and don’t reflect the actual fees you’re charged when using the service.

Unfortunately I am one man show, so keeping up with each exchange's fees is difficult. I can't always make instant updates and don't always know when fees change. I see this page on CEX.io's website: https://cex.io/fee-schedule#/tabCashInOut

On the tab for Deposit / Withdraw, the fees I have on my review are very similar, but you are right it does look like they have slightly updated their fees since I created my review. https://www.buybitcoinworldwide.com/exchanges/cex-io/

For example, my page lists the USD deposit fees at 3.9% + $0.25, while now it looks like they lowered it to 3.5% + $ 0.25. 

I'll definitely take a closer look at this and make the necessary changes. 

> Cubits isn’t mentioned on the “pay with credit card” page even thought they have the best terms and fee structure (but they don’t accept US affiliates …).

Please not that both Circle and CEX.io are also listed on the "pay with credit card" page and also have no affiliate program. https://www.buybitcoinworldwide.com/en/buy-bitcoin-credit-debit-card/

I have Cubits listed on all Europe country pages (for example:  ) and also on the main find exchange page: https://www.buybitcoinworldwide.com/find-exchange/

I have heard of Cubits, but haven't taken a close look at their fees. I'll be taking a closer look at them and if I see them as a good exchange I will definitely get them added to that page.

**Comment by JTuwiner** [comment]
@willy-b Yes, that is no problem. In fact we have Cubits listed on the main find exchange page: https://www.buybitcoinworldwide.com/find-exchange/

It's also listed on all European pages for example: https://www.buybitcoinworldwide.com/en/dk/

**Comment by JTuwiner** [comment]
>You also have to clean up the information and provide reviews for all the listed exchanges and not just those with good affiliate programs.

We have 8 exchanges reviewed, 5 have affiliate programs and 3 don't. Sorry I do not have unlimited time or money that can just churn out reviews for the hundreds of Bitcoin exchanges. https://www.buybitcoinworldwide.com/exchanges/

**Comment by JTuwiner** [comment]
>  “Purchases made via bank transfer are free.” is only stated in reviews with affiliate links.

Here are two exchange reviews for you with no affiliate links that say "free bank transfers" 

https://www.buybitcoinworldwide.com/exchanges/itbit/
https://www.buybitcoinworldwide.com/exchanges/circle/

note that most of these are US based where we do not pay fees on bank transfers

**Comment by Aeyoun** [comment]
@mrose17, if you only read one paragraph out of this discussion let it be:
> In any case, users should get direct recommendations from Brave Software and not have to rely on a third-party [that may or may not use affiliate links for all or some exchanges]. It adds friction to the user experience and seeds doubts and drop-out points in the on-boarding process.

@JTuwiner, you need to properly disclose your affiliate links and come clean about who you’ve got commercial partnerships with (this includes affiliate programs) and clean up how links works (which are reviews? which are direct liks? which are affiliates?) Your website will remain untrustworthy in my eyes until you clean it up and my recommendation to Brave on this design mockup remains unchanged.

To everyone else, I do apologize for initiating this discussion in the comments on this bug.

_My final comment_ on this discussion:
> note that most of these are US based where we do not pay fees on bank transfers

US consumers also pay fees for international bank transfers (and foreigners, you know — your target audience —, pays fees to transfer to US banks). It depends on where the exchange’s bank is located and where the user’s bank is located: unless they’re in the same country there will be fees. Money doesn’t travel from your US bank directly to the bank you wish to transfer funds to. It goes through a chain of banks, each claiming [usually high] fees on the transfer. You usually can’t tell beforehand exactly how much the fees will be as you don’t know which banks will be involved in any given transfer. Claiming that it’s free is naive at best.

**Comment by JTuwiner** [comment]
> you need to properly disclose your affiliate links and come clean about who you’ve got commercial partnerships with (this includes affiliate programs) and clean up how links works (which are reviews? which are direct liks? which are affiliates?) Your website will remain untrustworthy in my eyes until you clean it up and my recommendation to Brave on this design mockup remains unchanged.

Point taken, you are definitely correct on this in terms of UI standpoint. But know that masking affiliate links is common and okay for affiliate marketing. I do agree it could be emphasized more although we do have a disclaimer. 

> US consumers also pay fees for international bank transfers (and foreigners, you know — your target audience —, pays fees to transfer to US banks). It depends on where the exchange’s bank is located and where the user’s bank is located: unless they’re in the same country there will be fees. Money doesn’t travel from your US bank directly to the bank you wish to transfer funds to. It goes through a chain of banks, each claiming [usually high] fees on the transfer. You usually can’t tell beforehand exactly how much the fees will be as you don’t know which banks will be involved in any given transfer. Claiming that it’s free is naive at best. 

Well, as a US consumer who has purchased Bitcoin over 100 times, I can say that I have not paid a single cent for bank transfer fees. 

I do see the bank deposit method on the CEX.io page listed as free, which is more geared to international users. Will add * next to it to note that bank fees may apply, but that CEX.io the exchange does not charge fees on those deposits.

**Comment by mrose17** [comment]
hello @Aeyoun & @JTuwiner & @willy-b - sorry for getting into this conversation so late. 

i like buybitcoinworldwide.com because it shows me who is operating in a given marketplace and i can then drill-down to see which of the listings makes the most sense for what i'd like to do.  i consider it a very helpful service, and i imagine that keeping it current must be quite the challenge.

with that in mind, my thinking is to invite folks from different localities to use buybitcoinworldwide.com to see what works best for folks in their country. that involves a fair effort combined with local knowledge (that i don't have, obviously).

@Aeyoun's preliminary recommendation for:

* Cubits.com for EEA/EU, Mexico, and New Zealand

* Cex.io for the rest of the world

is a good catch-all.

best,

/mtr

**Comment by JTuwiner** [comment]
@mrose17 I'm glad you like BBWW. I hope it can be of use to Brave! 

Sorry to get off topic again, but it's important for me to show that BBWW is a trusted source for information related to buying bitcoins. I really do hope it can help people get bitcoins into Brave! 

@Aeyoun - I've done research based on your feedback. Please take another look at the site and I think you will see it gives the user a much better experience, discloses affiliate links, marks internal/external URLs. 

you can see some examples: 

review page: https://www.buybitcoinworldwide.com/exchanges/virwox/
country page: https://www.buybitcoinworldwide.com/en/us/
credit card page: https://www.buybitcoinworldwide.com/en/buy-bitcoin-credit-debit-card/
find exchange page: https://www.buybitcoinworldwide.com/find-exchange/

Next up is for wallet pages, but after a few hours work getting this done, I think that will be for tomorrow ;)

**Comment by Aeyoun** [comment]
@JTuwiner, :+1: :+1:. Your revised design no longer makes me think “affiliate scumbag” as you’re upfront about it. Mixing internal and external links in the list views still isn’t great, but it’s now at least possible to see which is which. I’d chalk that up as a definite improvement.

**Comment by alexwykoff** [comment]
Note for whomever QA's this: You will likely need a VPN or a bunch of friends in other countries.

**Comment by mrose17** [comment]
@jkup - in `ledgerInfo`, you will now find `exchangeInfo.exchangeName` and `exchangeInfo.exchangeURL` if present, please use these instead of the US-based defaults.

here's an example: `{ exchangeName: 'QuadrigaCX', exchangeURL: 'https://www.guadrigacx.com` }`  

enjoy!

**Comment by luixxiul** [comment]
Is Cubits available for Asian countries?

**Comment by Aeyoun** [comment]
> Is Cubits available for Asian countries?

https://cubits.com/assets/v2/cubits-map-43b80fc959143a6847d8deed61c7ce55.png

Any 3-D secure issued credit card from a bank outside the USA, as far as I can tell.

**Comment by luixxiul** [comment]
Nice! I wish more languages will be available.

**Comment by mrose17** [comment]
@luixxiul  - according to their website, this is the list:

             [ 'AT',
               'BA', 'BE', 'BG', 'BR',
               'CA', 'CH', 'CY', 'CZ',
               'DE', 'DK',
               'EE', 'ES',
               'FI', 'FR',
               'GB', 'GR',
               'HR', 'HU',
               'IE', 'IS', 'IT',
               'JP',
               'KR',
               'LI', 'LT', 'LU', 'LV',
               'MT', 'MX',
               'NL', 'NO', 'NZ',
               'PO', 'PT',
               'RO', 'RU',
               'SE', 'SG', 'SI', 'SK',
               'TR',
               'UA',
               'ZA' ]

**Comment by Aeyoun** [comment]
I wrote up some follow-up on the design of this dialog in #4292.
