### ISSUE TITLE
Address bar should be active for about:newtab

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3712]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Address bar is not "active" when it should be

**Expected behavior:**

Address bar "active", so user could add the web address without need to click on it.

- Platform (Win7, 8, 10? macOS? Linux distro?): 

Ubuntu

- Brave Version:  

Brave: 0.11.6

- Steps to reproduce:
    
1- Open a new tab
2- Switch to the new blank tab
3- Go back to the tab you were browsing before you opened the new tab
4- Go to the blank new tab you opened in step 1

On step 4, the address bar should be "active", so users could be able to write the web address without need to click on it.

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
Reopening since returned by QA.
