### ISSUE TITLE
3rd-party cookie policy

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3715]
Blocking all 3rd-party cookies causes problems for some websites that are not easy for users to diagnose and they shouldn't be forced to drop all protection from shields to access them. Safari's 3rd-party cookie policy allows access to any 3rd-party cookie that was set in a 1st-party context, but that allows websites to set cookies in redirects and for pages that users accidentally navigated to or otherwise would not want to be readable as a 3rd-party. As a compromise between privacy and usability we should implement the following policy:

3rd-party cookies and local storage

Cookies
If the cookie was set in a first-party context in a url that was either navigated to directly (bookmark, history or typed in urlbar) or a url where the user took some definitive action (form submission, maybe others?) it should be accessible. Otherwise the cookie should be blocked.

Local storage
If a local storage value was set in a first-party context under the conditions above it should be accessible. Reading of other values should be blocked.

This policy should be checked against gchat and other services that do not work with our current policy

**Comment by BrendanEich** [comment]
@bridiver "it should be accessible" means a set-cookie attempt from the domain in question as 3rd party should succeed? Just a wording thing, I hope -- or I'm misunderstanding.

**Comment by diracdeltas** [comment]
lgtm, except form submission can be done without user action

i'm assuming we'll keep the current block-all-3p-cookies policy as an option but set this to be the default?

**Comment by bridiver** [comment]
I was looking through our code for handling cookies and we currently only block cookies that are sent in the request headers from 3rd-party domains. Setting of cookies and reading of local cookies follows standard cookie rules. I think this is actually a big problem because it would be very easy to circumvent by reading the cookie locally and sending the value in the url. When 'block 3rd-party cookies is set on chrome attempts to read or write cookies locally will fail.

So along with the policy change we need to implement `AllowSetCookie` and `AllowGetCookie`

**Comment by bridiver** [comment]
@diracdeltas I think it might be possible to check for user gesture instead of a specific action

**Comment by bridiver** [comment]
actually I take that back, we are overriding document.cookie in a content script, but `AllowSetCookie` and `AllowGetCookie` would be a much better way to handle it

**Comment by diracdeltas** [comment]
> actually I take that back, we are overriding document.cookie in a content script, but AllowSetCookie and AllowGetCookie would be a much more reliable way to handle it

++

**Comment by bkardell** [comment]
Safari, it seems from my tests, just gives you back an empty/dummy view of localStorage in this case, if you try to read from it you'll just find nothing there.  Brave, again, from my tests throws `Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`.  I can imagine why we might like it to throw in retrospect, but if there are a wealth of existing things which had never planned for that path it very likely will lead to a bad experience.  Should it actually throw?

**Comment by bridiver** [comment]
@bkardell that's a very good point and might be a difference between blink and upstream webkit because we are now using blink's internal content controls. It does seem like silently ignoring it or providing a transient in-memory localstorage area would be better, but I think that should be a separate ticket.

**Comment by bkardell** [comment]
@bridiver I'm happy to open a separate ticket if we want, it just seems you're still figuring out what to do so I thought I'd add some feedback there.  It's weird if this error originates from blink because chrome has no issue with this - surely it's something you've added to block? or am I misunderstanding your point?

**Comment by bridiver** [comment]
@bkardell which version of Brave? Both Brave and Chrome implement https://chromium.googlesource.com/chromium/blink/+/refs/heads/master/public/web/WebContentSettingsClient.h and return false from the localstore methods when blocking 3rd-party. On older versions of Brave we used content scripts and the behavior might have been different. Please go ahead and open a new ticket and we can discuss there. Thanks!

**Comment by bridiver** [comment]
@bkardell cc me on the ticket when you create it

**Comment by x8x** [comment]
Is this issue still being investigated? We just found that running a local site with 3rd party cookies blocked doesn't work ( localStorage error ) when called with `127.0.0.1`, no problem if called with `localhost` or any domain pointing to `127.0.0.1`.

**Comment by flamsmark** [comment]
Seems similar to #10983 ?

**Comment by tomlowenthal** [comment]
I wouldn't expect to see this problem in this form, and we're working on other mitigations to make this less pressing.
