### ISSUE TITLE
Split components out of preferences.js

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3717]
This is just a nice to have, but there are like 20 components inside of the preferences.js file. It would be nice to split them out into separate files for testing / readability / making them easier to find.

**Comment by luixxiul** [comment]
Also I’m wondering if it would improve readability of preferences.less by separating it to files in a folder like this:

```
less/about/preferences/preferences.less
less/about/preferences/general.less
less/about/preferences/search.less
```
The common rules should be set in preferences.less and the other files should be imported to it.

**Comment by jkup** [comment]
@luixxiul this is definitely a good call! My only worry is spending time on LESS when we are moving to Aphrodite. Maybe it would be best to split the .js files up and then one by one move the applicable preferences.less stylings into Aphrodite objects?
