### ISSUE TITLE
Unable to call or video call in messenger.com

### ISSUE THREAD

**Issue by ShivanKaul** [brave/browser-laptop#3719]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Trying to video call (or even call) from messenger.com fails - it loads infinitely. This was after giving permissions to messenger.com to access cam and microphone.

**Expected behavior:**
Should be able to video call from messenger.com

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X

- Brave Version:
0.11.6

- Steps to reproduce:
    1. Login to messenger.com, and try to call someone. 

- Screenshot if needed:
Note: black oval my own art, for obscuration purposes.

![messenger_not_connecting](https://cloud.githubusercontent.com/assets/5284154/18237921/4bf086c8-7305-11e6-8091-a0df6b7e3a13.png)

**Comment by bsclifton** [comment]
@ShivanKaul do you have fingerprint protection on?

**Comment by ShivanKaul** [comment]
Yeah I do. Could that be why?

**Comment by bsclifton** [comment]
@ShivanKaul try clicking the lion icon in the top right and turning that feature off when you're on messenger.com. There are some known issues with fingerprint protection (particularly involving canvas). I'll update the parent issue we have with this info too

**Comment by ShivanKaul** [comment]
Yeah, fingerprinting protection was the problem - disabling it for messenger.com solved the issue.

**Comment by bsclifton** [comment]
Awesome, thanks for the report, @ShivanKaul! I've captured it in the parent issue. Closing this issue
