### ISSUE TITLE
onfocus in form doesn't remove default text when typing

### ISSUE THREAD

**Issue by pbowe** [brave/browser-laptop#372]
At intellicast.com,there is a form field to 'Enter City, State, Country or U.S. Zip Code'.  The default behavior when you select the field and start entering text is to replace the existing text.  Instead, it inserts what you type, so the search is invalid.

**Comment by psimyn** [comment]
I think this is due to scripts being blocked - works if you disable Ad blocking

Same issue as https://github.com/brave/browser-laptop/issues/624 - cc @bbondy

**Comment by luixxiul** [comment]
#624 is not the same one, which is about tracking whitelist.

If you allow scripts from Bravery menu, the placeholder text is replaced. Closing.
