### ISSUE TITLE
Can not change twitter avatar, while FP is on

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3720]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If you have enabled Fingerprint protection, you can't change your twitter avatar.

**Expected behavior:**
Twitter avatar could be changed with no problems.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux, Fedora 24
- Brave Version:
  0.12.0dev
- Steps to reproduce:
  1. Go to twitter.com
  2. Login
  3. Try to change your avatar
- Screenshot if needed:
- Any related issues:
  #2965

**Comment by bsclifton** [comment]
What happens when you try to change the avatar? Does the browser lock up? I had an issue like this with https://github.com/brave/browser-laptop/issues/3028

If it doesn't functionally work, I'd suggest leaving a comment on https://github.com/brave/browser-laptop/issues/2965 and closing this in favor

**Comment by bbondy** [comment]
Info on how to troubleshoot:
If you look in app/trackingProtection.js and app/adBlock.js you'll see registerBeforeRequestFilteringCB you can try hardcoding in a cancel: false for when it is equal to a certain URL that you see blocked in the bravery panel under the stat (click the stat to see a list of blocked URLs).  The ads and trackers combine both of those things.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-can-not-change-twitter-avatar-while-fp-is-on/10094

@Sh1d0w If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
