### ISSUE TITLE
LastPass popups have scrollbars

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#3721]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
LastPass will display a popup when you choose it from the context menu (right click on input field, pick LastPass). It shows the horizontal and vertical scroll bars on both the login prompt and once you're logged in (the vault)

**Expected behavior:**
The popup should be properly sized and not having scrollbars
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.11.6
- Steps to reproduce:
  1. Open Brave on Windows 10
  2. Settings > Security, pick LastPass
  3. Open a website which has a login form
  4. Pick LastPass from the context menu
  5. Popup should look like the attached screenshots

**NOTE**: The login form didn't show the scrollbars until after going to the password field.
- Screenshot if needed:
  ![screen shot 2016-09-04 at 11 47 45 pm](https://cloud.githubusercontent.com/assets/4733304/18239465/66ba4b98-72fa-11e6-9221-dcef00339d02.png)

![screen shot 2016-09-04 at 11 48 33 pm](https://cloud.githubusercontent.com/assets/4733304/18239469/6acb53b2-72fa-11e6-8d91-d4c8b1d69fa4.png)
- Any related issues:

**Comment by luixxiul** [comment]
I confirm this does no longer happen.
