### ISSUE TITLE
feature request: slide to navigate backwards and forwards on laptops with touchscreens

### ISSUE THREAD

**Issue by jkokorian** [brave/browser-laptop#3722]
I would like to be able to slide sideways on my touchscreen or use two-finger sideways scrolling on my touchpad to navigate backwards and forwards. Chrome and Edge have this behaviour, and I realized I've come to rely on it for casual browsing. It would be great if this feature could be added to brave!

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/feature-request-slide-to-navigate-backwards-and-forwards-on-laptops-with-touchscreens/10178

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
