### ISSUE TITLE
Show FP protection placeholder similar to Flash placeholder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3723]
It would be nice to have a FP protection placeholder similar to Flash Placeholder which will help users to disable it at page level.

**Comment by bbondy** [comment]
Do you mean TP, like in Tracking Protection? Otherwise what is FP?

**Comment by luixxiul** [comment]
FingerPrinting?

**Comment by srirambv** [comment]
> FingerPrinting?

Yes. If not a placeholder just a notification bar to warn user that enabling Fingerprinting Protection on that particular site might not load the page properly.

**Comment by bbondy** [comment]
It's not the same in terms of there bing a single element t block but more of an api that could be used that we are blocking. I think we could override the use of those methods though so that if they are used then we would show a bar.

/cc @diracdeltas

**Comment by diracdeltas** [comment]
notification bar might be a good idea here; or a symbol in the urlbar similar to noscript if we want something less intrusive.

**Comment by bbondy** [comment]
I prefer symbol like the noscript one.
