### ISSUE TITLE
Separate Name into "First Name" and "Last Name" in about:autofill

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3728]
Renaming Name to Full Name in auto fill makes it more clear for users who end up only entering only their firstname in the field instead of First name and last name.

cc: @darkdh

**Comment by luixxiul** [comment]
In terms of l10n, the input forms `Last Name` and `First Name` should be separated for those who has a name which does not include whitespaces.

STR:
1. Open about:autofill
2. Add Address
3. Input (or copy) `平原卓`(HiraharaSuguru) to `Name`
4. Save it
5. Open https://www.roboform.com/filling-test-all-fields
6. Set focus to `First Name`
7. You get `原卓`(haraSuguru) where it should be `卓`(Suguru)
<img width="346" alt="screenshot 2017-05-25 13 53 43" src="https://cloud.githubusercontent.com/assets/3362943/26436487/bdb6fbbe-4151-11e7-8952-b7f9d54b127a.png">

Obviously the number of users in CJK is relatively low, so low-priority.
