### ISSUE TITLE
Make it easier to troubleshoot website compat problems with Brave shields

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3732]
Currently you can open the Bravery Panel, and click on a stat.  It will show a list of the URLs affected. 

This task is to make it easier to troubleshoot the problems by making each of the URLs into a clickable on/off whitelist toggle.  I'm thinking we can have a list of exceptions URLs for each resourceName that we keep in the siteSettings. 

It's also useful for people that use noScript to incrementally add only the things they need. 

Main purpose though is it'll help our QA, especially @srirambv get the info they need to report a bug that is easy for us to fix, and eventually they can make those fixes themselves to a config file and PR it.

/cc @diracdeltas, this would save us a lot of time in the long run

**Comment by Aeyoun** [comment]
The information already shows up in the developer tool console like it does in every other browser. What else do you want?

**Comment by bbondy** [comment]
Browsers are used by non-developers that shouldn't need to open the developer tools.  And this task isn't a reporting task, it is about allowing partial blocking of a single URL at a time so that you can troubleshoot by bisection.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/908
