### ISSUE TITLE
DevTools slow response

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3733]
DevTools (Ctrl+Shift+I) response looks to be very slow on Windows for build 0.12.0 RC1. Is this the same on Mac/Linux?  Tends to hang momentarily when moving between different tabs on the console.

**Comment by Sh1d0w** [comment]
It is working just fine under Linux (Fedora 24).

**Comment by jonathansampson** [comment]
This appears to _still_ be an issue on Windows 10 with 0.12.10.

**Comment by Liunkae** [comment]
Is this still reproducible on Windows with Brave 0.12.15 or master?

**Comment by bsclifton** [comment]
I believe this is a huge problem still, even with the 0.13.0 builds.  Right, @jonathansampson?

**Comment by jonathansampson** [comment]
@bsclifton Indeed it is :(

**Comment by jonathansampson** [comment]
Fixed by https://github.com/brave/muon/commit/96506c4d0d1db51ea6a5ad9ecee44ebd13f71d91.
