### ISSUE TITLE
Microsoft Virtual Academy videos doesn't play when Block 3P Cookie is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3740]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Microsoft Virtual Academy videos doesn't play when Block 3P Cookie is enabled

**Expected behavior:**
HTML5 Video should play 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 RC1
- Steps to reproduce:
  1.  Visit [Microsoft Virtual Academy ](https://mva.microsoft.com) with Block 3P enabled at page level
  2. Open any course 
  3. Videos fail to play unless Allow all cookies is selected.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18254494/49cf19cc-7396-11e6-926a-5c04fc384a0f.png)
- Any related issues:
  #2533

**Comment by srirambv** [comment]
Similar issue on Repubblica.it. Video loads when 3P cookie is enabled.
![video3pc](https://cloud.githubusercontent.com/assets/17010094/21622066/aa740876-d1f3-11e6-8bf2-27e485500cc4.gif)

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
