### ISSUE TITLE
Trouble getting set up with dev version

### ISSUE THREAD

**Issue by ShivanKaul** [brave/browser-laptop#3743]
**Did you search for similar issues before submitting this one?**
Yes. 

**Describe the issue you encountered:**
I want to run a development version of Brave. I was following the instructions on the README. However, I kept getting the

> Please make sure the webpack devserver is running via:
> npm run watch

error page. 

**Expected behavior:**
New page? I'm not sure. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X

- Brave Version:

![image](https://cloud.githubusercontent.com/assets/5284154/18257388/effdbfac-7390-11e6-881a-f381c1b5a81c.png)

- Steps to reproduce:
    1. Made sure `node` was v6.3.0
    2. Made sure `node-gyp` was v3.3.1
    3. Git cloned and `npm install`ed the dependencies
    4. Opened up two terminal windows - in one, ran `npm run watch`. Seemed to be running without any problem. In other, ran `npm start`. This was output: 
![image](https://cloud.githubusercontent.com/assets/5284154/18257423/64a401e0-7391-11e6-9969-15e9459106fa.png)

    5. Brave opened up with the following screen:
![image](https://cloud.githubusercontent.com/assets/5284154/18257432/81ef777a-7391-11e6-8d64-170ea02f0686.png)

I did `rm -rf node_modules/`, `rm -rf ~/.electron`, `npm install` again as well. No luck. I read through the Troubleshooting guide and couldn't find a solution either.

**Comment by bbondy** [comment]
It seems likely that you have something else running on port 8080. You'll have to update the code to use an alt port or stop whatever else is running on 8080.

**Comment by ShivanKaul** [comment]
I'm pretty sure nothing is running on port 8080 (did a `netstat`), and also tried changing port in config in `package.json` to no avail.

**Comment by bbondy** [comment]
If you have telnet installed could you try stopping npm run watch and then running:
`telnet localhost 8080`
What is the output?

**Comment by ShivanKaul** [comment]
![image](https://cloud.githubusercontent.com/assets/5284154/18286157/9cec56fc-743f-11e6-9d2d-ee52bebda0c0.png)

**Comment by bbondy** [comment]
so that means something is running on that port. If your devserver is stopped then something else is already running on that port.
