### ISSUE TITLE
electron is missing helpful download methods

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3749]
`OpenDownload`, `IsDangerous`, `CurrentSpeed`, `PercentComplete`, `SetOpenWhenComplete` and maybe some others from `content::DownloadItem`

we should also be checking `hasUserGesture` before allowing downloads

**Comment by bbondy** [comment]
@jkup when you have some time after the immediate ledger stuff, if you wanted to get your feet wet with electron you could peel off one of these into another issue and add.

**Comment by jkup** [comment]
Awesome!
