### ISSUE TITLE
Please respect my local DNS settings.

### ISSUE THREAD

**Issue by taoeffect** [brave/browser-laptop#3750]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Brave does not respect `/etc/hosts`

**Expected behavior:**

Respect the`/etc/hosts` file like you're supposed to.
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X 10.11.
- Brave Version: 0.11.6
- Steps to reproduce:
  1. Modify my `/etc/hosts` file to redirect a domain to localhost

**Comment by taoeffect** [comment]
OK, weird, now all of a sudden it's noticed the change I made. I guess it seems rather slow on the uptake? Perhaps it caches the IP?

**Comment by bsclifton** [comment]
Brave definitely does respect local DNS settings (you may need to restart after making changes to `/etc/hosts`).  If there are steps to reproduce Brave not respecting the settings, let's re-open this issue 😄
