### ISSUE TITLE
on payments preferences page, if no favicon, the publisher link is dead

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3751]
mouse over a publisher with a favicon, you'll see the link at the bottom of the browser

mouse over a publisher without a favicon, no link is indicated

**Comment by jkup** [comment]
@mrose17 it looks like we are requesting this.synopsis.get('publisherURL') which is coming back as null for those links. I think that whatever is causing favicons not to show up is also causing the URLs not to come through. Is this coming from the ledger directly? cc @diracdeltas

**Comment by mrose17** [comment]
@jkup - well, here are two entries from what `ledger.js` gives to `appActions.updatePublisherInfo`

      {
        "rank": 31,
        "verified": false,
        "site": "tesla.com",
        "views": 8,
        "duration": 255250,
        "daysSpent": 0,
        "hoursSpent": 0,
        "minutesSpent": 4,
        "secondsSpent": 15,
        "score": 14.92523469777581,
        "publisherURL": "https://tesla.com",
        "percentage": 1,
        "faviconURL": "..."
      },
      {
        "rank": 32,
        "verified": false,
        "site": "hackertarget.com",
        "views": 8,
        "duration": 167312,
        "daysSpent": 0,
        "hoursSpent": 0,
        "minutesSpent": 3,
        "secondsSpent": 47,
        "score": 13.947358375921217,
        "publisherURL": "http://hackertarget.com",
        "percentage": 1
      },

one has a `faviconURL` and the other doesn't, but both have a `publisherURL` ...

**Comment by jkup** [comment]
@mrose17 Ok here's what I'm seeing -- maybe someone can help me track this down.

ledgerData, which comes from app state (https://github.com/brave/browser-laptop/blob/master/js/about/preferences.js#L1256) is returning undefined for both faviconURL and publisherURL.

I'm having a bit of a tough time figuring out where that data is being set in the first place. I'll keep digging into it but I wanted to mention it to you all in case you have a hunch!

**Comment by ayumi** [comment]
@mrose17 @jkup I spent time looking into this but couldn't figure it out.

If the favicon fails to load even when the website has a favicon, the corresponding ledger publisher link will be broken.

Regarding `ledgerInfo.publisherURL`, in [ledger.js `synopsisNormalizer()` line 535](https://github.com/brave/browser-laptop/blob/master/app/ledger.js#L535) I noticed `protocol` could be undefined in which case we wouldn't synthesize the publisherURL.

Adding a fallback to default protocol to `http://` "fixes" the problem, so we'd get http:// publisher links at least. I'm not a big fan of http:// but it could be a temporary solution.

**Comment by mrose17** [comment]
@ayumi - go ahead and make that change and let's see if it helps. i'm skeptical (i think the issue is elsewhere, though i'm not sure where, exactly), but no harm in testing a theory...

**Comment by jkup** [comment]
@mrose17 @ayumi cool, I have a bit of time today -- let me poke around a bit more too!

**Comment by mrose17** [comment]
@jkup - great! but one way or another, let's get these closed out by COB today.

**Comment by jkup** [comment]
@mrose17 just FYI I still haven't been able to get my dev env working this afternoon so haven't been able to take a look yet.

**Comment by mrose17** [comment]
@jkup - no worries. this isn't urgent, by any means.  on thursday, ping me when we're both in the office and we can see what issues you still have with your dev environment...

**Comment by ayumi** [comment]
With the above [default protocol](https://github.com/brave/browser-laptop/blob/2cd4b3915303ee8ca5b6f9423e13f107dfdbe7c5/app/ledger.js#L535), if favicon is missing and you revisit the publisher link, it'll fetch the favicon and correct protocol.
