### ISSUE TITLE
Enable in-browser proxy settings option

### ISSUE THREAD

**Issue by putt1ck** [brave/browser-laptop#3756]

**Comment by putt1ck** [comment]
There is no UI option to enable a proxy; using a system-wide proxy is not always the preferred option. Having a UI access to set a browser-specific proxy, or use no proxy when there is one set system-wide is literally expected behaviour for cross-platform browsers, as well as necessary in a number of use cases, including web development scenarios, IT support scenarios, parenting scenarios.

Platform: OpenSUSE Tumbleweed (assuming affects any OS)
Brave: latest (and before)

**Comment by joshuayabut** [comment]
I have some commits ready to enable session-based proxy settings. Since there are still a bunch of electron related leaks it's quite unsafe to use for those with privacy requirements though.

A couple thoughts/options:

- use chromium's behavior (point to the system-wide proxy config window)
- wait to enable this until the leaks are resolved 
- add a warning prompt when adding a session-based proxy setting

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6072

**Comment by efemernyy** [comment]
This feature is a necessity for me, would love to switch to Brave full time but no native proxy/network settings interface kills it

**Comment by dhiva** [comment]
it would be great if brave has inbuild smart proxy switcher which could allow you to configure multiple proxies for various different sites and automatically use them when the site is visited.

**Comment by SillonBono** [comment]
Having a configurable proxy option is a must. Having the possibility to configure multiple proxies and switch to them either by site list or by drop down menu would be icing on the cake.

Most organizations use a proxy for web browsing and many use multiple proxies.

**Comment by codfather** [comment]
I would like to add my support for this addition to the browser. I now use this browser for work, and it is a necessity to have a per application ability to support proxies, as system wide are just not appropriate for Devops type work. I look forward to this addition.

**Comment by bsclifton** [comment]
I'm not sure how much we've diverged from Electron, but we may be able to get this functionality by hooking into the sessions object
http://electron.atom.io/docs/api/session/#sessetproxyconfig-callback

cc: @bridiver

**Comment by mannp** [comment]
Wondered if there are any updates on this one at all? 

Seems you may have a solution? but its been pushed back to v1.1 release.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/proxy-totally-missing-or-only-ui/5943/2

**Comment by Rogerborg** [comment]
+1 for this being a show stopper for me using Brave.  It seems unbelievable that a browser with the user's interests and privacy at heart wouldn't support this.

**Comment by luixxiul** [comment]
> wouldn't

Not exactly; it's planned.

**Comment by netroby** [comment]
+1 need this

**Comment by tomonova** [comment]
+1 this truly is important feature, please deliver on this ASAP

**Comment by CapitanShinChan** [comment]
Point to the system proxy is a dirty solution that almost all modern browsers do (good job Firefox, you're one of the few who is doing it in the right way). Hope Brave will imitate the Firefox behavior.

**Comment by netroby** [comment]
or u can bundle a extension. i currently using proxy switcher.




Thanks







On Wed, Sep 27, 2017 at 10:47 PM +0800, "CapitanShinChan" <notifications@github.com> wrote:












Point to the system proxy is a dirty solution that almost all modern browsers do (good job Firefox, you're one of the few who is doing it in the right way). Hope Brave will imitate the Firefox behavior.

**Comment by JakRazzi** [comment]
+1 Absolutely necessary feature. Brave will completely replace my Firefox usage once this is implemented.

**Comment by Laomak** [comment]
+1 I also need this feature to finally get rid of Firefox and their recent introduced Cliqz support

**Comment by dannwebb** [comment]
+1 I'll also be leaving Firefox for Brave when this is implemented.

**Comment by DeesseFortuna** [comment]
Just throwing in my +1
Maybe consider a FoxyProxy style addon? I love how it's implemented in Firefox, though I'm not sure how it performs with respect to leaks.

**Comment by mingrui** [comment]
FoxyProxy style please!
Will be leaving firefox if this is planned!

**Comment by msagansk** [comment]
+1 This is a necessary feature for me.

**Comment by The1stSword** [comment]
+1  I need this to move away from Firefox.   I use a local socks proxy that tunnels traffic through ssh on a daily basis.   So this is a deal killer for me.

**Comment by bjoernbusch** [comment]
Any progress on this? I'd love to use this browser in my corporate environment, but unfortunately, the proxy settings aren't used by brave somehow. Not sure how to describe this in more detail, in Chrome it works with the system settings.

**Comment by evoerman** [comment]
Same issue with me; global proxy settings on Fedora 27 are not picked up by latest Brave release0.20.30.
Chrome and Firefox work fine with me as well.

**Comment by bjoernbusch** [comment]
ok, so my problem is actually due to this: https://github.com/brave/browser-laptop/issues/12959

When I go back to an older version, Brave works properly with my corporate proxy and I don't need to adjust settings.

**Comment by zaneschepke** [comment]
I went back to the older version and Brave is now working with my corporate proxy as well! Can we please get this fixed on the latest version?

**Comment by mplungjan** [comment]
Brave | 0.20.42
Just downloaded. Getting 
>This site can’t be reached because server DNS address could not be found
>https://community.brave.com/
everywhere.
What to do?

**Comment by zaneschepke** [comment]
I downloaded 0.20.27 and it was working until Brave auto-updated to 0.20.42. There is no way to disable these auto-updated? Now I get a connection attempt refused from all sites except my internal corporate site. New update does not work with my corporate proxy and I imagine most other corporate people have this same issue. I want to use this software but this is making it really hard..

**Comment by kamaradski** [comment]
Installs Brave,
finds out there is no proxy-setting like Firefox has it,
uninstall Brave...


I'll be back later once this got sorted. Shame really, as I was actually excited to try this browser :(

And, no, please do NOT point to the system-wide proxy, I need to be able to have at least 1 browser that is not using the system proxy, but an alternative Socks5 connection to escape the local firewall.

**Comment by blightwing** [comment]
I can't agree with Kamaradski more. This is mandatory for a daily driver for me- doubly so for my 'privacy-centric' browser,

**Comment by dougaitken** [comment]
I can use a system proxy on Chrome and Firefox but not Brave. I want to move full time to Brave but I cannot since even all pages that should load via proxy come with an external IP address. I use Private Internet Access and a company Proxy application to connect and this is a deal breaker for me to use Brave fulltime

**Comment by a7777777v** [comment]
+1

**Comment by scfcode** [comment]
+1. I want to switch full time, but this being broken is, as others have already said, a deal breaker.

**Comment by boistordu** [comment]
When does the dev will understand that you can't rely on the OS part to secure their app and you need to implement secure code and secure features direct in the application. 
We don't care about system wide proxy which is totally bullshit on a windows 10 system or a mac OS system and maybe even some linux distros too. So just implement the code about proxying.
Plus is the only way that you can do split vpn traffic like mullvad is using. 
Not everyone is using just a laptop and don't have any LAN traffic + you can't always trust your ISP, if you ever do actually. 

When are you able to delvier it?

**Comment by hieronymousch** [comment]
+1

**Comment by nielspeen** [comment]
Brave properly uses the system proxy on macOS when one is configured. However, when I then remove the system proxy, and other browsers automatically switch back to the regular connection, Brave stops working and reports: "The IP address is unreachable. This usually means that there is no route to the specified host or network."

**Comment by jSadoski** [comment]
@nielspeen That issue doesn't sound related to this feature request. You should open your own issue for that.

**Comment by charlierlee** [comment]
+1

**Comment by pepik** [comment]
+1

On a mac, while connected to corporate network using Cisco Anyconnect VPN, brave browser us usable for internal web pages only.

System wide pac-provided proxy does not work.

**Comment by motorious1** [comment]
+1 same issue as pepik here...
FF has the following which I would need coprable to in Brave to use on corporate network
==================
Options -> Advanced -> Network -> Connection -> Settings ->"Automatic proxy configuration URL:"

**Comment by Adiorz** [comment]
+1
same here - lack of proxy support discards Brave for me

**Comment by ecomaikgolf** [comment]
+1

**Comment by dimaahawk** [comment]
+1?

Is this going to happen?

**Comment by putt1ck** [comment]
Rumour has it that the rewrite underway for v1 will include this feature (via Twitter). Probably won't be independent of the system proxy though, as they'll inherit the feature from the Chromium code base (my ideal is per-browser, though only for testing "kid-quality web filtering")

**Comment by boistordu** [comment]
this is a simple problem. We don't need a vpn proxy settings. We need an extension which will do the switching. Nobody is using the in-house windows proxy settings because it works poorly.

**Comment by boistordu** [comment]
I don't understand why they can't see as a primary function with this actual historic context.

**Comment by bsclifton** [comment]
@boistordu it's not a simple problem given our current codebase (Muon, forked from Electron) and our current set of priorities (otherwise, we or a contributor would have finished it already).

If you're not using Brave, what is your solution? Are you using Chrome with an extension?

**Comment by CapitanShinChan** [comment]
Firefox

**Comment by mplungjan** [comment]
It’s such a pain - behind office firewall and cannot use Brave at all there
:(((

**Comment by beickhoff** [comment]
Currently using Firefox

**Comment by boistordu** [comment]
@bsclifton yes I'm using, depending of the machine, chromium, chrome or firefox. All with an extension which is here: https://github.com/FelisCatus/SwitchyOmega which is available on every platform and since the code is available then we can maybe translate the needed part for your browser.

**Comment by tofke** [comment]
+1

**Comment by BrendanEich** [comment]
This issue will not apply to brave-core (aka chromium-fork). Still would be good to get relief sooner but brave-core is coming up fast and we will switch desktop over to it from Muon ASAP.

**Comment by rouxianmantou** [comment]
+1
request to add in-browser proxy switcher or an extension like which named SwitchyOmega(support both chrome and firefox) mentioned above...

**Comment by tomlowenthal** [comment]
This will be available in brave-core, and won't be fixed in Muon.

**Comment by boompig** [comment]
I don't see this in the MacOS X version. Am I missing something?

**Comment by bsclifton** [comment]
@boompig have you downloaded the new Developer channel release?
https://brave.com/download-dev

Give this a try- it should be fixed there
