### ISSUE TITLE
Blocked script info dialog should be under noScript icon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3757]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Blocked script info window is off location

**Expected behavior:**
Should be below the blocked script icon
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 RC2 (Clean install)
- Steps to reproduce:
  1. Enable Block scripts in Shields
  2. Visit any site and click on the blocked script icon next to URL bar.
  3. Info window is off position.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18265931/fac37754-740f-11e6-97b0-d79398cd909a.png)
- Any related issues:

**Comment by luixxiul** [comment]
I'm guessing it should be like the bookmark hanger, which appears with the arrowUp under the bookmark star icon. 

The modal background color is going to be removed since 0.18.x (#9034).

**Comment by luixxiul** [comment]
@bradleyrichter could I know if you have a mockup of the dialog? I'm wondering if it would look nicer when `commonForm` is applied to make it like bookmark hanger:

<img width="223" alt="screenshot 2017-06-06 17 01 16" src="https://cloud.githubusercontent.com/assets/3362943/26819439/c975825e-4ad9-11e7-8a83-5499ada292c4.png">

With the arrowUp, it should appear under the noScript icon, which is 🚫 .

**Comment by luixxiul** [comment]
It would be solved like this way:

<img width="543" alt="screenshot 2017-09-16 12 04 53" src="https://user-images.githubusercontent.com/3362943/30508655-4723dadc-9ad7-11e7-9d42-d94b04e2b337.png">

**Comment by bradleyrichter** [comment]
Good solution but we should retain the normal control styles and perhaps reduce the size of the panel itself

We are looking at global style update as well but it's of course a separate project.

**Comment by luixxiul** [comment]
> we should retain the normal control styles and perhaps reduce the size of the panel itself

Replacing the checkboxes with switches? it would look fine.

I'd reduce the panel size and adjust it through l10n QA.

**Comment by luixxiul** [comment]
How about this one?

<img width="429" alt="screenshot 2017-09-23 17 04 10" src="https://user-images.githubusercontent.com/3362943/30771364-3fe5580e-a081-11e7-80f4-995f0016fa35.png">

the wording can be improved.

**Comment by bsclifton** [comment]
cc: @bradleyrichter @alexwykoff @jenn-rhim @jamesmudgett
