### ISSUE TITLE
More Bookmarks on the bar

### ISSUE THREAD

**Issue by Crocodile73** [brave/browser-laptop#3762]
Is it possible to increase the amount of bookmarks in the bookmarks bar. Larger screen systems, it only shows so many then leaves the rest of the space empty. Need to click on the arrow for more bookmarks too see them.

**Comment by bbondy** [comment]
Could you take a screenshot perhaps if the data is not sensitive?

**Comment by Crocodile73** [comment]
![dsc_0053](https://cloud.githubusercontent.com/assets/16454525/18286285/f684544c-7469-11e6-83a0-d1b730df77f2.JPG)

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/4116
