### ISSUE TITLE
Flash content not loaded on King.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3764]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Flash content not loaded on King.com. Flash placeholder is not shown. When clicked on 

**Expected behavior:**
Should display the flash placeholder. Clicking on the placeholder should show the prompt to run flash content.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.0 RC2

- Steps to reproduce:
    1. Visit King.com
    2. Open any of the games
    3. Shows message to upgrade to flash. Doesn't load the flash content when clicked on the message.

- Screenshot if needed:

- Any related issues:

cc: @diracdeltas

**Comment by diracdeltas** [comment]
works for me - the Flash notification bar appears when i click on the 'get flash' logo. then i click allow and the game loads.
![screen shot 2016-09-07 at 2 30 24 pm](https://cloud.githubusercontent.com/assets/549654/18329321/bad88e1a-7507-11e6-8318-b5f57a2cb960.png)

**Comment by srirambv** [comment]
Rechecked on 0.12.0 and seems to be working without any issue. Tried on 0.12.1 Dev Preview 3 and works as well. Closing the issue.
