### ISSUE TITLE
Pinned tabs refresh on fullscreen

### ISSUE THREAD

**Issue by elsehow** [brave/browser-laptop#377]
whenever i exit or enter fullscreen in OSX, all pinned tabs (e.g. gmail) reload

osx 10.11.2

**Comment by CAPerkins22** [comment]
I don't think entering or exiting fullscreen is the only way pinned tabs automatically reload. I was just writing an email in Gmail and both of my pinned tabs refreshed mid-keystroke.

**Comment by bbondy** [comment]
Please share a pinned tab URL that reproduces in case it's related.

**Comment by CAPerkins22** [comment]
Happens for both mail.google.com and tweetdeck.twitter.com for me

**Comment by mrandre** [comment]
I can reproduce this bug if: 
1.I have a pinned tab.
2. I navigate the pinned tab away from the original pinned url.
3. I resize the window in anyway.

The tab refreshes, and goes back to the original pinned url. Indeed, all pinned tabs with subsequently modified urls revert to the original URL. Not sure if this is the same issue.

**Comment by elsehow** [comment]
this is the issue, and i can reproduce the bug with the same steps.
this happened to me in gamil because i loaded mail.google.com, then navigated to a thread.

**Comment by mrandre** [comment]
In the latest release of Brave, I am no longer experiencing this issue.

**Comment by bbondy** [comment]
I think this is fixed already or if not will be fixed in a lot of pinned tag refactoring going into 0.7.16, marking this as closed.
