### ISSUE TITLE
Mixed-content lock control should be able to re-lock and reload the page like Firefox.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3770]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing https://github.com/brave/browser-laptop/issues/3443 it was discovered that re-locking the page exhibits counterintuitive behavior. It merely displays the unlocked status rather than re-locking.

**Expected behavior:**
If a user clicks on a closed lock, it should open. If a user clicks on an open lock, it should close. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Visit https://forgetfulbc.blogspot.com/2016/08/lastweek-t3.html
    2. Click on the blue lock in the URL bar
    3. Attempt to click on it a second time

- Screenshot if needed:
Chrome:
![mixed_content_chrome](https://cloud.githubusercontent.com/assets/1434040/18287829/479ace8c-743e-11e6-8858-86a181deddfc.gif)

Firefox:
![mixed_content_firefox](https://cloud.githubusercontent.com/assets/1434040/18287835/4fc999ee-743e-11e6-8bf3-5b358a8c5d25.gif)

Brave:
![mixed_content_brave](https://cloud.githubusercontent.com/assets/1434040/18287839/560233b6-743e-11e6-9496-58137c602623.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/3443

**Comment by diracdeltas** [comment]
changing this to higher priority because currently the only way to re-blocked mixed content is by restarting the browser
