### ISSUE TITLE
Incorrect autofill for City/Postcode on Bet-At-Home registration form.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3771]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Incorrect autofill for City/Postcode on Bet-At-Home registration form.

**Expected behavior:**
Should load the proper data into the corresponding fields.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 
- Steps to reproduce:
  1. Visit[ Bet-at-home](https://www.bet-at-home.com/en/account/registration) and click on register now to open the registration form 
  2. Click on first name for autofill suggestion to come up
  3. City/Post code gets filled in the wrong data. Works fine on Chrome.
- Screenshot if needed:
  ![autofill](https://cloud.githubusercontent.com/assets/17010094/18288472/6dc3973a-7473-11e6-8ef7-84065c99b99f.gif)
- Any related issues:
  #3602

cc: @darkdh 

Adding milestone 1.0 to go insync with #3602

**Comment by bsclifton** [comment]
Verified this is no longer an issue
