### ISSUE TITLE
Flash content doesn't load on bet-at-home.com when 3P cookie is blocked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3772]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Flash content doesn't load on bet-at-home.com

**Expected behavior:**
Notification should be shown to allow flash content to run.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 
- Steps to reproduce:
  1. Visit Bet-at-home [online game](https://www.bet-at-home.com/en/casino/game/multiplier-mayhem)  with Block 3P Cookie enabled and Fingerprint Protection disabled
  2.  Flash content doesn't load
  3.  Disable 3P Cookie, flash content opens.
- Screenshot if needed:
  With 3P Cookie enabled
  ![image](https://cloud.githubusercontent.com/assets/17010094/18289641/1ec9017e-7478-11e6-9442-95f2e45701ed.png)
  
  With 3P Cookie disabled
  ![image](https://cloud.githubusercontent.com/assets/17010094/18289661/3ab35cf4-7478-11e6-9eee-0503d8f7baaa.png)
  
  Console Error
  ![image](https://cloud.githubusercontent.com/assets/17010094/18289812/e540df98-7478-11e6-83d0-c1421cbf80a0.png)
- Any related issues:

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
