### ISSUE TITLE
Wrong architecture identifier for 64-bit RPM

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3774]
Issue #1445 shouldn’t have been closed as there is actually an issue with Brave’s RPM packages.

The RPM package’s metadata identifies the architecture as “amd64” which flags it as “not installable” when x86_64 was expected. Which results in the following error message when trying to install via the default installation tools (dnf/yum):

    Error: package brave-0.12.0-1.amd64 is not installable

The packages are built on Ubuntu, which explains where the incorrect identifier comes from. amd64 is the expected architecture name under Debian derivatives (Ubuntu, Mint, etc). However, on the RHEL side x86_64 is the expected architecture name.

Furthermore, the `Group` metadata property of the package should be set to `Applications/Internet`.

**Comment by Aeyoun** [comment]
This is also the root cause of the upgrade conflicts on RPM systems.

**Comment by darkdh** [comment]
+1 from support
https://linkbubble.zendesk.com/agent/tickets/5703

**Comment by fduraibi** [comment]
I have just downloaded brave-0.12.4 and the same problem still exist!

This should be an easy fix, no?

**Comment by bbondy** [comment]
PRs welcome

**Comment by Aeyoun** [comment]
There is no documentation on how the RPMs and DEBs are made.

**Comment by bbondy** [comment]
It uses electron-installer-debian and electron-installer-redhat inside tools/buildInstaller.js you can check out more info about those packages on github or NPM.
