### ISSUE TITLE
Feeling of panic immidiately on every start

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3778]
1. Leave about:preferences#payments open
2. Restart the browser and check the Payments page

Expected: account balance to display a cached value from the previous session until Brave has updated the currency exchange rates, etc.

Actual: account balance “0 USD” displayed for a few seconds and my heart skips a beat or two and I start thinking about whether I’ve backed up my Brave user data or not. After some seconds the correct value is displayed.

**Comment by mrose17** [comment]
just checking: is this on linux? on a mac, i get a different behavior (viz., first i see the initialization screen and then the "real" screen). i agree that we need to fix this, but want to make sure i'm on the same page...

**Comment by Aeyoun** [comment]
This is on Linux. Don’t have any funds in Brave on my MacBook.
