### ISSUE TITLE
Installer icon is default application icon (Win64)

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3779]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The icon in the taskbar is the default "application" icon instead of being a Brave icon.

**Expected behavior:**
Icon should be Brave logo or a different icon like described in #2763
- Platform (Win7, 8, 10? macOS? Linux distro?): Win7
- Brave Version: 0.12.0
- Steps to reproduce:
  1. On a clean Win7 system, download and start the Brave installer
  2. Observe the taskbar icon
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1530699/18294407/f0739b88-7466-11e6-9f64-ae7fd6f63391.png)
- Any related issues:

**Comment by luixxiul** [comment]
On Windows 10 too:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18310582/32b532e4-753a-11e6-84b4-ec61e7694c74.png)

**Comment by luixxiul** [comment]
I think the issue has been fixed since a long time
