### ISSUE TITLE
input fields have unintended side effects with CMD keyboard shortcuts

### ISSUE THREAD

**Issue by gdi2290** [brave/browser-laptop#378]
OSX Version 0.7.9 (0.36.3)
My work flow uses a lot of `CMD + left-arrow` and `CMD + right-arrow` to jump to the end-of-line or beginning-of-line. At the moment @Brave goes back or forward in history which is the effect when you're not focused on an input field. (alt+arrows works).

Also `CMD+ALT+arrows (left/right)` doesn't work to quickly switch tabs

**Comment by chtefi** [comment]
Yes, same issue on Windows with Ctrl+left/right. I would add the problem occurs also in the address bar, not only in the tabs.

**Comment by obvio171** [comment]
Still observing this behavior on Linux running master at d368f70a6c69358fc503a425985d108fa33f3292 (after the fix commit).

**Comment by bbondy** [comment]
I opened a new issue here, this bit me several times as well:
https://github.com/brave/browser-laptop/issues/723
