### ISSUE TITLE
Bookmarks menu is blank on browser start

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3780]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The Bookmarks menu is blank when I start the browser. It becomes populated only after I load the first page or switch active applications.

**Expected behavior:**
Bookmarks menu should be populated as soon as it is available to open.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.0dev

- Steps to reproduce:
    1. Close Brave.app
    2. Open Brave.app
    3. Open the Bookmarks menu. It is blank.
    4. Load any page -or- switch focus to another app and then back to Brave.
    5. Open the Bookmarks menu again. It has bookmarks.

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1530699/18294547/ee854ba4-7467-11e6-9d5c-d72bc8ff5f17.png)

![image](https://cloud.githubusercontent.com/assets/1530699/18294555/052bb8c0-7468-11e6-9e42-fee062835eeb.png)

**Comment by bsclifton** [comment]
This needs a retest against master- it may have been fixed with https://github.com/brave/browser-laptop/pull/3813

**Comment by gulkily** [comment]
Verified fixed in 0.12.3.
