### ISSUE TITLE
Updated to version Brave: 0.12.0 and my $5 is gone

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3781]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:

Updated to version Brave: 0.12.0 and my $5 is gone

**Expected behavior:**

See the $5 I added when I had Brave 0.11..

- Platform (Win7, 8, 10? macOS? Linux distro?):

Ubuntu 64

- Brave Version:

- Steps to reproduce:
1- Update Brave to 0.12.0
2- Open the browser, go to settings/payments

- Screenshot if needed:

- Any related issues:

**Comment by lucaszanella** [comment]
same here

**Comment by bitcoinuser** [comment]
When I try to add funds, I see this: Wallet information not available. :(

![captura de tela de 2016-09-06 21-34-51](https://cloud.githubusercontent.com/assets/1178856/18295680/e731d6b2-7479-11e6-9439-277272bd771b.png)

**Comment by Aeyoun** [comment]
I’ve backed up my entire Brave profile folder. I’ve got no idea whether that is enough to actually keep my funds safe. How should I back up my 40 USD worth of BitCoins locked down in my Brave wallet? I’m no longer feeling so brave after seeing these reports …

**Comment by mrose17** [comment]
oops! i haven't seen that before (and i've been using the ledger for 3 months internally!), but that's going to get stomped on very, very quickly.

@bitcoinuser & @lucaszanella - contact me directly -- mrose@brave.com -- with a BTC address and i'll reimburse you on the spot. can you also scour your system for files called `ledger*.json` and tell me where the files are. presumably, if you are both on linux, you may find one or more directories under `~/.config`

@Aeyoun - it is wise to back-up your brave config file, everything is kept there. _be brave!_ the file you want to safe-guard is `ledger-state.json`

more details soon!

**Comment by bitcoinuser** [comment]
Sent the e-mail to you @mrose17

**Comment by mrose17** [comment]
@bitcoinuser - thanks! the coin is on the way!

can you look in your `~/.config/` directory and see if there are any other directories there called `*brave*` ? thanks!

**Comment by bitcoinuser** [comment]
Just one folder called brave. See:

![captura de tela de 2016-09-07 15-46-55](https://cloud.githubusercontent.com/assets/1178856/18324343/601a591c-7512-11e6-9e72-618ddaf3def7.png)

**Comment by lucaszanella** [comment]
@mrose17 I've found the ledger file, and it has a lot of code. ALready sent you the email.

**Comment by mrose17** [comment]
@lucaszanella - thanks! the coin is on the way... just checking, only one file named `ledger-state.json` under `~/.config/brave` (no other files by that name under `~/.config/` ? thanks!

**Comment by bitcoinuser** [comment]
In my case, I opened the ledger-state file and I see this:

"days": 30,
    "wallet": {
      "paymentId": "32135380-be95-47ef-b839-6f45a7fb62e2",
      "address": "3FmjMMVvKUCezJHx6K78TvkfzY6B8vpHks",
      "keychains": {
        "user": {
          "xpub": "xpub661MyMwAqRbcGzDuYKff7ht7.................................................................

**Comment by bitcoinuser** [comment]
Hi @mrose17 

I received the bitcoins from you (more than the $5). Thanks. I would like to fund brave again but I can't because I can't see the brave address. I see this message: Wallet information not available. :( 
Same screenshot  from here: https://github.com/brave/browser-laptop/issues/3781#issuecomment-245139450

**Comment by Aeyoun** [comment]
I’ve also seen this but before I added any BitCoins. The issue went away on its own after a few hours.

**Comment by alexwykoff** [comment]
@bitcoinuser @lucaszanella could you please provide some more detail around the manner of how you updated Brave on Linux?
Thanks!

**Comment by mrose17** [comment]
@lucaszanella - do you also see "Wallet information unavailable" in the "Add Funds..." dialog?

@Aeyoun - was your issue with the balance shown or with the "Wallet information unavailable"?

**Comment by lucaszanella** [comment]
@mrose17 yes.

@alexwykoff I downloaded the new .deb from the brave.com website, and installed it. The button 'check for updates' in the brave never works.

**Comment by Aeyoun** [comment]
@mrose17, I don’t recall exactly. But the first time I went to the payment page I  wasn’t able to get a BitCoin address out of it. It said something like "Wallet information unavailable". Waited a little while and it worked itself out.

**Comment by mrose17** [comment]
got it, thanks!

**Comment by mrose17** [comment]
@ayumi - do you think that https://github.com/brave/browser-laptop/pull/3805 addresses this issue, or is there something else going on?

**Comment by ayumi** [comment]
I tried but can't repro.

It's possible there was a connection error, which could explain what @bitcoinuser's screenshot.
Previously errors would show as "0 USD", but https://github.com/brave/browser-laptop/pull/3805 fixes it to be "loading" or "can't retrieve data".

Steps I took:
1. On my Mac host with VirtualBox, start a fresh Ubuntu Desktop 16.04.1 VM
2. Install Brave 0.11.6 via .deb from Releases
3. Fund Brave Payments with 5 USD via manually sending to the addres
4. Wait for "Your wallet is ready!"
5. Close Brave
6. Upgrade Brave to 0.12.0
7. Open Brave and check Payments tab

**Comment by mrose17** [comment]
@ayumi - thanks

@bitcoinuser & @lucaszanella - we're pushing a new release "very soon", when that happens, i'll ask you to upgrade and let's see what happens. i suggest you copy `ledger-state.json` somewhere safe before upgrading.  if you get whacked again, you can replace `ledger-state.json` and i'll send more coin for your help!

thanks!

**Comment by bitcoinuser** [comment]
Ok @mrose17

**Comment by bitcoinuser** [comment]
I don't know if can help, but I opened Brave on terminal, and I see this:

 at ELECTRON_ASAR.js:492:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
getWalletProperties error: Error: HTTP response 503 for GET /v1/wallet/32135380-be95-47ef-b839-6f45a7fb62e2?balance=true&amount=5&currency=USD
response error: [object Object]
undefined

**Comment by mrose17** [comment]
Thanks!  I was doing some ledger upgrades then!

**Comment by bitcoinuser** [comment]
Other times I already had restarted the browser, but the fund was not there. Now that I closed the browser for a long period, and open it. I see the funds. 
Maybe this information can help you. Will see if @lucaszanella see the money too.

Thanks.

**Comment by lucaszanella** [comment]
Hi, my bitcoin returned from nowhere too. @mrose17 where can I send the money back to you?

**Comment by Aeyoun** [comment]
I just lost my 40 USD a few minutes ago. Took a deep breath, restarted Brave, and still gone. Waited five minutes and restarted again, and this time they were back. It’s really not a good user experience when funds go missing. Causes people to not trust the system.

**Comment by mrose17** [comment]
@bitcoinuser & @lucaszanella - i'm glad you're seeing better results. please keep the bitcoin its recompense from brave software for your help in being early beta testers (for those in the know, all the ledger code is at 0.8.x...)

@Aeyoun - i agree that the "optics are bad". we'll figure this out. i thought that we had this nailed, but apparently not. ok, here's what i'm hoping you can do, go ahead and run the browser like this:

        script ~/Desktop/typescript
        LEDGER_VERBOSE=true LEDGER_LOGGING=true brave

and when you see the issue again, please post a gist with the relevant sections from the `~/Desktop/typescript` and `~/.config/brave/ledger-log.json` files (just the relevant sections to avoid any privacy leakage) and add a comment on this issue, so @ayumi can take a look. thanks!

ps: a new preview is out: https://github.com/brave/browser-laptop/releases/tag/0.12.1dev-Preview1  -- we're doing weekly previews between now and 1.0 (and yes, that is as challenging as it sounds...)

**Comment by mrose17** [comment]
@Aeyoun - can you take a look at https://github.com/brave/browser-laptop/releases/tag/0.12.1dev and tell me how that version works for you? thanks!

**Comment by Aeyoun** [comment]
> @Aeyoun - can you take a look at https://github.com/brave/browser-laptop/releases/tag/0.12.1dev and tell me how that version works for you? thanks!

What am I looking for?

**Comment by mrose17** [comment]
sorry for the lack of context!

i want to see whether you still have the temporarily misreported zero balance wallet issue...

thanks!

**Comment by Aeyoun** [comment]
> i want to see whether you still have the temporarily misreported zero balance wallet issue...

I recorded my screen and stepped through startup frame by frame. I see the "off" screen for when Brave Payments haven’t yet been enabled for ~800 ms. But I don’t see 0 USD anymore. It’s a bit ugly that it flashes the other screen first, but the "feeling of panic" when it shows 0 USD is gone.

**Comment by mrose17** [comment]
@Aeyoun - thanks. i'm closing this issue. i'm aware of the first screen problem and will create another issue just for that... thanks for your patience!

**Comment by ayumi** [comment]
@Aeyoun @mrose17 I've created https://github.com/brave/browser-laptop/issues/4066 for the startup UI delay. Thanks for your help!

**Comment by luixxiul** [comment]
Would someone please specify STR to confirm the issue has been fixed?

**Comment by mrose17** [comment]
hi. i've marked this as `no-qu needed`. there is an STR to test it, but it is one of those very long interactions, and i'm concerned that we end up spending a lot of cycles trying and retrying to force it.  however, @ayumi is working on https://github.com/brave/browser-laptop/issues/4066 which is related, and that will have a test plan!
