### ISSUE TITLE
Cmd+T (New Tab) shortcut becomes disabled while navigation occurs

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3782]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While navigating from one GitHub page to another, the Cmd+T shortcut (New Tab) is ignored.

**Expected behavior:**
The shortcut should always be available, regardless of current state

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.0

- Steps to reproduce:
    1. Open a GitHub listing page, e.g. https://github.com/brave/browser-laptop
    2. Click one of the files, e.g. LICENSE.txt
    3. Quickly, while the loading is still happening, press Cmd+T. I can reproduce the bug consistently if I press Cmd+T as quickly as I can after clicking the link.

**Comment by bbondy** [comment]
@bridiver I think this will be fixed with your menu fix?

**Comment by bridiver** [comment]
I think so. I have seen similar issues with keyboard shortcuts and I can't replicate this one or the others with the menu fix

**Comment by bbondy** [comment]
I will mark this as fixed in 0.12.1 and it can be tested / re-opened if not.
