### ISSUE TITLE
Cannot save open page when offline

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3783]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If I load a page and then disconnect from the network, I cannot save the page even though it is already open.

**Expected behavior:**
Should be able to save from cache even if disconnected.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.0
- Steps to reproduce:
  1. Open a web page
  2. Disconnect from the network
  3. File | Save or Ctrl+S
  4. Choose a file name

Expected: Page is saved

Actual: Page is not saved, Save dialog appears again.
- Screenshot if needed:
- Any related issues:

**Comment by charbelrami** [comment]
Reproduced on Win 10 64-bit.
