### ISSUE TITLE
Save As/file selection dialog appears twice when offline

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3784]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When offline, using the Save As command results in the file selection dialog appearing twice

**Expected behavior:**
Dialog should only appear once
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.0
- Steps to reproduce:
  1. Load a page
  2. Disconnect from network
  3. File | Save As
  4. Choose a file name and press Save

Expected: Page saved, no further activity

Actual: Page is not saved (#3783) and the Save As/file-selection dialog appears again
- Screenshot if needed:
- Any related issues:

**Comment by charbelrami** [comment]
Reproduced on Win 10 64-bit

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by kjozwiak** [comment]
Verified on macOS 10.13.3 using the STR in https://github.com/brave/browser-laptop/pull/11906#issue-273121960 with the following build:

* `0.22.6`  e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: `65.0.3325.162`
* Muon: `5.1.0 `

Also went through the case mentioned in https://github.com/brave/browser-laptop/issues/3784#issuecomment-245143133
