### ISSUE TITLE
Balance of bitcoin can show a scary 0 value when no connection

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3785]
1. Close browser
2. Turn internet off
3. Open browser
4. Open prefs -> Payments

Actual result: Shows balance of 0
Expected result: Shows some kind of an error that the data could not be retrieved

Likely alternate way to reproduce, turn off remote service.

**Comment by Aeyoun** [comment]
Duplicate of ##3778.

**Comment by bbondy** [comment]
Thanks, closing as a dupe.

**Comment by bbondy** [comment]
It might have a diff fix, will re-open for now.
