### ISSUE TITLE
Bookmark not appearing in about:bookmarks appears in autocomplete pulldown

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3788]
**Describe the issue you encountered:** I noticed that a bookmark which cannot be found in `about:bookmarks` appears in the autocomplete pulldown on the URL bar. The bookmark can be removed safely by the bookmark dialog. I am not sure of steps to reproduce the issue.

**Expected behavior:** It should appear on `about:bookmarks` and the bookmark toolbar.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.0
- Any related issues:

**Comment by srirambv** [comment]
Similar to #3763?

**Comment by luixxiul** [comment]
The page is actually bookmarked, just not appearing on ``about:bookmarks`` I think.

**Comment by luixxiul** [comment]
I forgot what I meant here. I'm going to close the issue as issue might be invalid already.
