### ISSUE TITLE
Missing two-finger back/forward navigation gesture

### ISSUE THREAD

**Issue by gdi2290** [brave/browser-laptop#379]
In Safari we get an amazing slide effect when gesturing back and forth. 
![](http://cdn.osxdaily.com/wp-content/uploads/2012/10/swipe-forward-back-apps-os-x.jpg)

In chrome they were not able to recreate the animation but they had an arrow animation. It would be great to have the gesture feature again :+1:

**Comment by elsehow** [comment]
I believe this is a limitation of electron shell. See atom/electron#2683

**Comment by diracdeltas** [comment]
thanks @elsehow for linking the upstream issue. looks like ben at Nylas fixed this 4 days ago, so this should be closed in the next electron-prebuilt release: https://github.com/atom/electron/pull/4181

**Comment by gdi2290** [comment]
thanks!
