### ISSUE TITLE
about:components page which displays info about Brave's loaded components

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#3790]
**Did you search for similar issues before submitting this one?**    Yes

**Describe the issue you encountered:**       When you enter brave: // components but are asked permission after the same page does not open properly as it was meant to be, so it appears "You need a new application to run Brave"
- Platform (Win7, 8, 10? macOS? Linux distro?):     Win10 64bits
- Brave Version:     0.11.6
  :

**Comment by bsclifton** [comment]
@EuNlope I don't understand what you're finding an issue with

Are you expecting to see a components page? (like some of our about pages? full list available at about:about)  Or is this an issue with launching a file type associated with Brave (after you set the default browser in Windows)?

More info is very much appreciated :smile:

**Comment by EuNlope** [comment]
I will send a print to understand what I'm talking about.

**Comment by bsclifton** [comment]
Attaching screenshot here for reference:
![1473298984889603](https://cloud.githubusercontent.com/assets/4733304/18339817/8519f4e0-7556-11e6-945d-68a29d377b91.jpeg)

**Comment by bsclifton** [comment]
awesome, thanks for the clarification, @EuNlope :smile:

**Comment by bsclifton** [comment]
This should be resolved with https://github.com/brave/browser-laptop/commit/8bf0b0c212fe80b84547e2bcdeb8f59ef13be80d which is available as `about:extensions`.  There is also an `about:brave` page coming in the next release which displays internal components used (V8, libchromiumcontent, etc)
