### ISSUE TITLE
I can't choose a date on Destinia site.

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3791]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Go to destinia.com.br and try to choose a date

**Expected behavior:**

Show the window to choose the date
- Platform (Win7, 8, 10? macOS? Linux distro?):

Ubuntu 64
- Brave Version:

Brave: 0.12.0
- Steps to reproduce:
  1. Go to destinia.com.br
  2. Try to choose a date
- Screenshot if needed:

![captura de tela de 2016-09-07 13-36-11](https://cloud.githubusercontent.com/assets/1178856/18320531/a94d020e-7500-11e6-9ddf-94b69b2c011b.png)
- Any related issues:

**Comment by charbelrami** [comment]
Not reproducible on Win 10 64-bit

**Comment by luixxiul** [comment]
Closing as fixed.
