### ISSUE TITLE
Horizontal Scroll bar appears with just one entry in Brave Payments

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3792]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Horizontal Scroll bar appears with just one entry in Brave Payments

**Expected behavior:**
Horizontal scroll bar should appear when the list goes beyond the frame

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, OpenSuse Tumbleweed

- Brave Version:
0.12.0 

- Steps to reproduce:
    1. Enable Brave payments in about:preferences#payments
    2. Create wallet and visit any site to get listed under payments
    3. Horizontal scroll bars appear even if there is one entry

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18321514/277fe6bc-7526-11e6-88b5-00c1987c98f3.png)

- Any related issues:

**Comment by bradleyrichter** [comment]
@srirambv Have you tried rotating your laptop 90 degrees?  Doh!  ;  )

**Comment by bradleyrichter** [comment]
@diracdeltas Are we just missing some CSS for auto-scroll bars?

**Comment by diracdeltas** [comment]
cc @jkup, i think this just uses
```
 height: ~"-webkit-calc(100vh - 300px)";
 overflow-y: scroll;
```

which is fine on osx but apparently causes unnecessary scrollbars on linux/win

**Comment by jkup** [comment]
cool I'll check it out asap

**Comment by bbondy** [comment]
a value of scroll isn't fine for macOS either sometimes depending on your scrollbar setting.   It should just be a simple scroll -> auto fix.
