### ISSUE TITLE
When will I be charged?

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#3797]
The about:preferences#payments page doesn’t say when I’ll be charged. Should show me a date or maybe countdown to next charge or something.

**Comment by bsclifton** [comment]
This is a good one-
@mrose17 @bradleyrichter

**Comment by mrose17** [comment]
if you click on 'view payment history', at the bottom, you'll see "Your next payment submission is ..."

it probably should be a bit more prominent (since history implies past, not present/future...)

**Comment by bradleyrichter** [comment]
The design intent was to get this info integrated with the status message. 

I'll open a new issue.

![image](https://cloud.githubusercontent.com/assets/13509546/18328786/3c126828-7505-11e6-868d-0ab4ad86d1c1.png)

**Comment by bradleyrichter** [comment]
One small problem is that this date will change based on user behavior. Time remaining based on usage.

@mrose17 any comments to add?

**Comment by bradleyrichter** [comment]
@diracdeltas do we have plumbing for this?

**Comment by diracdeltas** [comment]
yup this can already be added

**Comment by Aeyoun** [comment]
I have no “view payment history” at the bottom of anything.

Maybe that is US/Coinbase only?

**Comment by mrose17** [comment]
sorry, i should have been more clear, look at the lower left-hand corner of the grey box:

<img width="841" alt="1" src="https://cloud.githubusercontent.com/assets/400552/18329005/7cb77aac-7506-11e6-8522-d21f8a9c0b57.png">

**Comment by Aeyoun** [comment]
I don’t have that link. I don’t have a payment history with Coinbase, though. Is that why? Or is that only a mockup? “My wallet is ready!” but it’s also full. Should I be seeing a different message in the current builds?

![screenshot-3](https://cloud.githubusercontent.com/assets/1102886/18329280/f261a4e8-7552-11e6-804d-d6576485e767.png)

**Comment by bradleyrichter** [comment]
This only appears after your first payment. Thus, we need the additional status report.

**Comment by mrose17** [comment]
that explains it, thanks @bradleyrichter ... @Aeyoun - sorry for the confusion...

**Comment by bradleyrichter** [comment]
ok, I added a new issue for this: #3801

**Comment by bradleyrichter** [comment]
closing in favor of 3801
