### ISSUE TITLE
main menu selection stopped working 

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-laptop#3798]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
clicking on main menus, then moving the mouse over to select an item made the menu go away. Issue went away after full OS restart. Will watch for a repeat ocurrence

**Expected behavior:**
that menu items can be selected :)
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS sierra (final beta) - 10.12 Beta (16A313a)
- Brave Version:
  Brave: 0.12.0
  Electron: 1.3.10
  libchromiumcontent: 52.0.2743.116
  V8: 5.2.361.49
  Node.js: 6.3.0
  Update Channel: dev
- Steps to reproduce:
  Unknown. It stopped happening after full OS restart. (Before restart all apps except Brave worked fine)
- Screenshot if needed:
  Attached video showing the behavior. Video within zipfile because github file limitations.

[brave-mac-menu-bug.zip](https://github.com/brave/browser-laptop/files/460317/brave-mac-menu-bug.zip)
- Any related issues:

**Comment by bbondy** [comment]
@alexwykoff plps triage

**Comment by bsclifton** [comment]
Potentially fixed with https://github.com/brave/browser-laptop/pull/3813

**Comment by luixxiul** [comment]
Added the latest milestone for QA.
