### ISSUE TITLE
Ad Popups aren't blocked

### ISSUE THREAD

**Issue by kathiedart** [brave/browser-laptop#3799]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I have experienced behind-loading ad popups with shields up and brave ads on.
This does not happen with chrome or firefox.
These don't sound very brave, as they are loud and behind the tab.

**Expected behavior:**
To get no pop ups
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Ubuntu 16.04
- Brave Version:
  0.11.5
- Steps to reproduce:
  1. Go to a site containing ad popups
  2. Hear annoying noises behind the tab.
- Any related issues:
  Not that I'm aware of

**Comment by bsclifton** [comment]
@kathiedart do you have an example site?

**Comment by kathiedart** [comment]
Maybe going to https://thepiratebay.org/search/xandros/0/99/0 and clicking Xandros 4 OCE will work
(or a proxy)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of a topic on our Community site:

https://community.brave.com/t/discussion-ad-popups-arent-blocked/10048

@kathiedart If you are still around here, would you please join the conversation there to talk about the issue further? 😄 There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience 👍 Thanks!
