### ISSUE TITLE
Escape key not closing add funds dialog

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#3800]
**Did you search for similar issues before submitting this one?**
Searched for "esc"

**Describe the issue you encountered:**
Once you open the "Add funds..." dialog on the Payments page you can't close it using just the keyboard. This affects Accessibility and general UI/UX. I see that the dialog component has a listener for it so I'm assuming something else is catching that keyboard event.

**Expected behavior:**

Hitting escape should close a dialog modal.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Go to preferences > payments
  2. Click on "Add Funds..."
  3. Hit the escape key
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
This was attempted with https://github.com/brave/browser-laptop/pull/6248 but had some issues (milestone removed).

If you wanted to try the patch from that PR, you can grab it here:
https://patch-diff.githubusercontent.com/raw/brave/browser-laptop/pull/6248.patch

**Comment by zentagonist** [comment]
To retest after refactor of #11037

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.700 9306021
* libchromiumcontent 66.0.3359.139
* muon: 6.0.7
