### ISSUE TITLE
Add notification under status message to inform user of their contribution day

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3801]
Our Brave Payments users need to know when their first, and next payment will post. This info can be added below the Status message as shown below.

![image](https://cloud.githubusercontent.com/assets/13509546/18331415/9b2ec6a4-7513-11e6-990f-da37d0491bdf.png)

This "next payment" status will be shown as soon as the wallet detects a balance for the first time.

The date will change based on the users usage based on the start date of first wallet funding or from the last payment date.

**Comment by ayumi** [comment]
@bradleyrichter If there are insufficient funds, should the user still see the next contribution date?

**Comment by bradleyrichter** [comment]
@ayumi yes.

They will (hopefully) see an alert message that they need to add funds.

Also, we process if the balance is above 90% of the monthly amount selected.


It would be extra-cool if the text string would turn red if their funds are below the allowed level...
