### ISSUE TITLE
Missing "Bookmark This Link" context menu item for selected text link

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#3807]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
The context menu for links does not have the "Bookmark This Link" item.

[Here is the code](https://github.com/brave/browser-laptop/blob/acee33be600902685abd8ba2a32a25900bc6dbac/js/contextMenus.js#L896) that is supposed to show the item.

**Expected behavior:**
When I right-click a link, there should be an option to bookmark it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.11.6

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Go to a page with a hyperlink (e.g., https://github.com/brave/browser-laptop)
    2. Right-click the hyperlink (e.g., browser-laptop)

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/18336860/730678ce-7550-11e6-8a63-a168d9cb4089.png)

- Any related issues:
The spec is in #1253.

**Comment by luixxiul** [comment]
This has been implemented on Windows already. Is this macOS-only?

**Comment by Liunkae** [comment]
Possibly. Can anyone else confirm on macOS or Linux?

**Comment by luixxiul** [comment]
it does not exist on macOS

**Comment by Liunkae** [comment]
That's strange. It's consistently reproducible for me with both 0.12.1 and 0.12.2-RC4. macOS 10.12.

**Comment by Liunkae** [comment]
I've discovered the problem. It only occurs when the link text is selected. "Bookmark this page" shows for non-text links (e.g. image links).

Text links are automatically selected on right-click on macOS, so I'll mark this macOS-only. I'm investigating a fix…

**Comment by Liunkae** [comment]
#4462 fixes the issue for me.
