### ISSUE TITLE
bug: modal popup won't disappear

### ISSUE THREAD

**Issue by jkokorian** [brave/browser-laptop#3815]
The website www.buienradar.nl shows a modal 'cookie-notice' popup when first loaded. It doesn't disappear when you click "Ja, ik ga akkoord".

The modal popup should disappear when you click "Ja, ik ga akkoord"
- Platform: Win 10
- Brave Version: 0.12.0
- Steps to reproduce:
  1. go to www.buienradar.nl
  2. click on "Ja, ik ga akkoord"
  3. voila
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/6113878/18346800/90fc18bc-75c2-11e6-8d2a-268c4a7e2f6b.png)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-modal-popup-wont-disappear-on-buienradar-nl/10095

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
