### ISSUE TITLE
Autofill suggestion should close when field is out of focus

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3816]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Autofill suggestion should dismiss when field is out of focus. If field is out of view it still shows on the screen in the same position where the suggestion popped up

**Expected behavior:**
Should close suggestion when the field is not in focus
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 (Clean Install)
- Steps to reproduce:
  1. Create autofill entries
  2. Open the [autofill ](http://www.roboform.com/filling-test-all-fields)form and click on the field for suggestion to popup
  3. Scroll down the page the suggestion window remains fixed on screen until a mouse click.
- Screenshot if needed:
  ![auto](https://cloud.githubusercontent.com/assets/17010094/18348040/f9be1c44-75c0-11e6-9596-6ffa802796d1.gif)
- Any related issues:

cc: @darkdh

**Comment by bsclifton** [comment]
related: https://github.com/brave/browser-laptop/issues/4540
