### ISSUE TITLE
Using a touchscreen, events not registered until "mouse cursor" won't move near the place of touch.

### ISSUE THREAD

**Issue by adamkruszewski** [brave/browser-laptop#3818]
**Did you search for similar issues before submitting this one?**
yes.

**Describe the issue you encountered:**
I think two updates before 0.12 (I might be mistaken) it worked alright. Now when I enter a link in the address bar and the page loads in most cases I can't scroll the page. But when I move my mouse pointer [1] above the page the scroll starts working. The same is for other interface elements like tabs or even back button. I have to move the mouse pointer [1] above the back button and then the touch control will work (but when I'll click on the tool bar near back button and move the mouse over the back button, I can't scroll the page). Other apps and browsers behave like I would expect them so this behavior is exclusive to Brave. I think it worked alright two or three updates before.

edit: the behavior is not consistent also, after opening a new window with only one tab everything seems to work alright (on my main windows I have 8 tabs opened and two additional pinned).

[1] using trackpad or by repeatedly 'clicking' with my finger on the touch screen on the page; one of the clicks will 'move' the mouse pointer there; can't say why or how.

**Expected behavior:**
It just should register a click/scroll when the touch point was pressed on the screen.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 (on Asus T100 HA)
- Brave Version:
0.12.0
- Steps to reproduce:
included in the description above.

- Any related issues:
The offset in right click menu behavior (other issue with touch screen controls registered) is NOT related and the context menu always opened when the mouse cursor is located and not when the long-press touch was made even when I think the touch controls worked fine and without the need to repeatedly tap with fingers till it starts registering the events on the page.

**Comment by charbelrami** [comment]
I couldn't reproduce it on Win 10 64-bit, ASUS S400CA

**Comment by adamkruszewski** [comment]
I think we can close the issue as I can't really replicate it again. Hard to say if it was caused by some resources shrinkage on OS level or something else as after restarting my tablet everything seems to work alright all the time.
