### ISSUE TITLE
installation does not Work

### ISSUE THREAD

**Issue by pdohmen91** [brave/browser-laptop#382]
Hi Guys,

i´m trying to install the browser but it does not work. Tried it severall times but it just will not work. Currently I get an Error when I want to build it: 

`
npm WARN EPACKAGEJSON electron-test@0.1.0 No description
npm WARN EPACKAGEJSON electron-test@0.1.0 No repository field.
npm WARN EPACKAGEJSON electron-test@0.1.0 No license field.
npm verb exit [ 0, true ]
npm info ok
                                                                                                                                                                                          ✔

[2016-01-28 10:25.00]  /drives/c/Brave/electron
[PeterDohmen.L-5F-PD] ➤ python script/build.py
vendor/depot_tools/ninja: line 2: $'\r': command not found
vendor/depot_tools/ninja: line 6: $'\r': command not found
vendor/depot_tools/ninja: line 9: $'\r': command not found
vendor/depot_tools/ninja: line 10: syntax error near unexpected token `$'{\r''
'endor/depot_tools/ninja: line 10: `function print_help() {
`

When I run the build script from the script folder I get another Error:
`─
[2016-01-28 10:29.14]  /drives/c/Brave/electron/script
[PeterDohmen.L-5F-PD] ➤ python build.py
Traceback (most recent call last):
  File "build.py", line 45, in <module>
    sys.exit(main())
  File "build.py", line 25, in main
    ret = subprocess.call([ninja, '-C', build_path, args.target])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

Yesterday I got once so far that the build script ran properly but then I couldn´t find an exe file in the directories.

I´m installing it like described in the following instruction:
https://github.com/brave/electron/blob/master/docs/development/build-instructions-windows.md

Installation via npm install does not work too:

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: Parse Error
gyp ERR! stack     at Error (native)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:315:20)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:147:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:111:10)
gyp ERR! stack     at TCP.onread (net.js:523:20)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Brave2\\browser-laptop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=0.36.5" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\Brave2\browser-laptop\node_modules\sqlite3
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
done

**Comment by diracdeltas** [comment]
Is this working now that sqlite3 isn't needed?

**Comment by pdohmen91** [comment]
No I just installed brave with the installer I got some days later.

**Comment by diracdeltas** [comment]
Ok, I'm closing this for now
