### ISSUE TITLE
Scripts Blocked statistic shows wrong on brianbondy.com

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-laptop#3820]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Scripts Blocked count shows wrong in Bravery Panel for brianbondy.com
It shows 3:
https://brianbondy.com/
https://brianbondy.com/js/bundle.js
https://brianbondy.com/js/analytics.js

**Expected behavior:**
2 Scripts Blocked:
https://brianbondy.com/js/bundle.js
https://brianbondy.com/js/analytics.js
- Platform (Win7, 8, 10? macOS? Linux distro?):
  masOS
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Go to brianbondy.com
  2. Turn on the switch for Block Scripts in Bravery Panel 
  3. Check the Scripts Blocked value
- Screenshot if needed:
- Any related issues:

CC @diracdeltas

**Comment by bbondy** [comment]
note the page has no inline scripts @diracdeltas

**Comment by bsclifton** [comment]
works great now
