### ISSUE TITLE
Mac menubar is inaccessible while download is in progress

### ISSUE THREAD

**Issue by gulkily** [brave/browser-laptop#3823]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While a download is in progress and visible in the downloads-bar at the bottom of the window, the menus cannot be accessed.
When I click one of the top-menus, the sub-menu appears, but when I move the mouse cursor down, the sub-menu disappears.
The menu behavior returns to normal when I cancel the download or it finishes on its own.

**Expected behavior:**
The menus should continue to be accessible while a download is in progress.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.0

- Steps to reproduce:
    1. Load a page that links to a large download
    2. Start the download. Ensure that it appears in the download bar at the bottom of the window
    3. Click one of the items in the menu-bar, e.g. "Bookmarks" or "File"
    4. Move the mouse cursor down into the menu list

**Comment by bsclifton** [comment]
May have been fixed by https://github.com/brave/browser-laptop/pull/3813; could use a retest from master

**Comment by bbondy** [comment]
should be, marking as closed.
