### ISSUE TITLE
implement 1st party storage isolation

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3826]
https://twitter.com/rlbarnes/status/773895944031076352, AKA https://www.torproject.org/projects/torbrowser/design/#identifier-linkability

**Comment by eljuno** [comment]
+2 from community https://community.brave.com/t/fpi-first-party-isolation/11117?u=eljuno

**Comment by eljuno** [comment]
+2 from community https://community.brave.com/t/fpi-first-party-isolation/11117?u=eljuno

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1053
