### ISSUE TITLE
add notification event 24h prior to reconcilation

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3828]
if the user clicks "details", please take them to the payments page

**Comment by diracdeltas** [comment]
what should the notification text be? @bradleyrichter ?

**Comment by alexwykoff** [comment]
Please add QA steps or label no-qa-needed as appropriate. Thanks!

**Comment by diracdeltas** [comment]
@alexwykoff sorry, i have been putting QA steps in the commit that fixes the issue.
https://github.com/brave/browser-laptop/commit/855ddad2bbc314a959b7fa64d2c4e1e33dc2bc95
