### ISSUE TITLE
Installation does not work on Mac EL Capitain

### ISSUE THREAD

**Issue by elhachmi** [brave/browser-laptop#383]
(+) No known vulnerabilities found
Packaging app for platform darwin x64 using electron v0.36.5
[ { [Error: ENOENT, mkdir '.../browser-laptop/electron-packager/darwin-x64/Brave-darwin-x64/Brave.app/Contents/Resources/app']
    errno: -2,
    code: 'ENOENT',
    path: '.../browser-laptop/electron-packager/darwin-x64/Brave-darwin-x64/Brave.app/Contents/Resources/app' } ] undefined
done

**Comment by luixxiul** [comment]
@bbondy Was fixed, right?

**Comment by bbondy** [comment]
Don't know what that error is but it should be working. Closing for now.
