### ISSUE TITLE
a publisher should get a visit increment only on a new tab...

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#3830]
...not when switching to an existing tab

**Comment by bradleyrichter** [comment]
@alexwykoff this is the source of the new UX issue?

**Comment by alexwykoff** [comment]
I think there's a bit of nuance here versus https://github.com/brave/browser-laptop/issues/4274 . In this case @mrose17 is stating that if there are more than one tab open and a user flips back and forth between them, that should NOT increment the visit count.
However, if the user opens a new tab and points it to a publisher already existing in the previously opened tabs, that first visit counts.
