### ISSUE TITLE
Show chrome icon / indicator when browsing sites to which you're contributing

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#3834]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
To see sites to which you're contributing, you need to visit Preferences > Payments which takes effort.

**Expected behavior:**
When visiting a website to which you'll contribute on the next Payments reconciliation date, the browser chrome should show an indicator. This will result in:
1. Repeated warm fuzzy feelings when visiting your favorite sites
2. Visual feedback of the _n_ seconds delay before contribution
3. Could also be a convenient Payments toggle switch like the "Include" toggles on Preferences > Payments

The indicator might look nice next to the address bar and bookmark star.

I'm not sure what it should look like.
Maybe a little bitcoin icon? (maybe less spiky than the Prefs>Payments bitcoin icon)

**Comment by mrose17** [comment]
_no one_ can argue with "warm fuzzy feelings". _no one!_

**Comment by bradleyrichter** [comment]
@ayumi This was the original sketch. LMK your thoughts about it's fuzzy factor.

![image](https://cloud.githubusercontent.com/assets/13509546/18400357/5ca897e8-768a-11e6-8f0d-77150e7aef64.png)

**Comment by ayumi** [comment]
I like the top right orange lion, and I feel I'd like it less if it were styled differently.
It anchors that corner, and being a toggle switch would make the corner uncomfortable.

For now it seems next to the URL bar would be a decent spot.

Bitcoin icon -- I think it looks a little awkward because the hue is an orange differing from Brave orange, it's rotated CW 15 deg, and it has pointy spikes.
Maybe a simpler bitcoin or a coin icon?

Here's a vertical [BTC SVG by Martin Allien licensed under GPL 2.0](https://allienworks.net/products/cryptocoins/).
<img width="60" alt="screen shot 2016-09-09 at 13 11 39" src="https://cloud.githubusercontent.com/assets/521861/18401668/726fbe16-7690-11e6-8775-e4fbba6aaebc.png">

**Comment by bradleyrichter** [comment]
@ayumi - see #3036 for some issues around the Lion corner that are caused by removing the title bar on Windows. The proposed solution is shown.

The official BTC brand logo is rotated but we can use vertical for clarity if needed, and ditch the color but I do think it has recognition power. (but yes, clashes with Brave Orange a bit.)

We need to add something "switchy" to the Brave Button because not all users are discovering it as a button for some time. Fully open to other ideas on how to improve on that issue.

And another concern - the URL box is not always visible due to title-mode, and I am moving the "always visible" items to the left of the URL bar.

**Comment by BrendanEich** [comment]
I agree with @ayumi on not making the lion into a slider switch.
If some beveled button-ish mounting for it were subtle yet discoverable, maayybe -- but it’s a delicate beast.

We dont’ want to make a big honking “push me” nuisance, for sure. Is what we seek just some kind of discoverability clue?

Ideas:
- onboarding guided tour (may not make 1.0)
- how about a Slack-like radar ring for first time you mouse near the lion?

**Comment by bradleyrichter** [comment]
Perhaps the proximity of the brave button to other buttons will be enough to trigger it's button-ness. I added a hint of depth as well.

Here is a different approach to the Bitcoin beacon which could either fade in, pop in, or slide from the lion when you land on a site which is marked for payment.

![image](https://cloud.githubusercontent.com/assets/13509546/18462661/30cfd382-7939-11e6-996e-df93c3380f25.png)



Here is a URL bar version:
![image](https://cloud.githubusercontent.com/assets/13509546/18462707/90c70788-7939-11e6-8a0d-336dd08d0cb0.png)

**Comment by mrose17** [comment]
OBE by #6261
