### ISSUE TITLE
noscript and flash site settings should not be shared from private browsing into regular browsing

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3835]
following up on https://github.com/brave/browser-laptop/issues/3795#issuecomment-245779637

**Comment by bbondy** [comment]
can this move to 0.12.3?

**Comment by diracdeltas** [comment]
moved

**Comment by diracdeltas** [comment]
related: https://github.com/brave/browser-laptop/issues/3998

**Comment by diracdeltas** [comment]
also related: https://github.com/brave/browser-laptop/issues/2745

this turns out to be tricky because js/state/contentSettings.js has no awareness of incognito vs regular context. an acceptable solution for now is just for Flash/NoScript settings in private browsing mode to be restricted to 'Allow Once'.
