### ISSUE TITLE
Cisco Webinars not loaded when HTTPS everywhere is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3838]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Cisco Webinars not loaded when HTTPS everywhere is enabled

**Expected behavior:**
Should load and play videos
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 
- Steps to reproduce:
  1. Visit Cisco [TechWiseTV listing](https://www.cisco.com/c/m/en_us/training-events/events-webinars/techwise-tv/listings.html)
  2. Open any of the listed article with video content
  3. Webinar not loaded. Shows an empty div in place of the player.
  4. Disable HTTPS in shields, after page reload video content is loaded.
- Screenshot if needed:
  Console Error (HTTPS Enabled)

![image](https://cloud.githubusercontent.com/assets/17010094/18385814/a50cefd4-768a-11e6-9fee-0520a3a99965.png)
- Any related issues:

**Comment by luixxiul** [comment]
It seems it's not been fixed.

**Comment by diracdeltas** [comment]
moving this out of 0.12.1

**Comment by diracdeltas** [comment]
seems to work now
