### ISSUE TITLE
Mute pinned tabs changes the size of the pinned tabs.

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3839]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Mute pinned tabs changes the size of the pinned tabs.

**Expected behavior:**
Should shrink back to the original size of the pinned tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Play audio/video on any pinned tab
  2. Mute the tab when its playing
  3. after the video/audio stops playing the tab size will remains big and doesn't shrink back to its original size.  
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18386191/31ef89b4-768d-11e6-89d4-54e81854d9fd.png)
- Any related issues:
  cc: @bradleyrichter

**Comment by bbondy** [comment]
what is the diff between this and https://github.com/brave/browser-laptop/issues/3769 ?

**Comment by srirambv** [comment]
This is with respect to the current behavior where the tabs size shrinks when audio icon is gone. #3769 is for new design to be implemented instead of the current behavior.

**Comment by bsclifton** [comment]
This behavior can cause the appearance of a flicker (more info in https://github.com/brave/browser-laptop/issues/4793)

Notice everything shift left and then back right really quickly:
![tab-blink](https://cloud.githubusercontent.com/assets/4733304/19397463/d165804a-91fc-11e6-863a-c516982c9162.gif)

**Comment by bradleyrichter** [comment]
ok, that is a problem. 

#3769 is a start but it feels a bit micro.

**Comment by lucidNTR** [comment]
@bradleyrichter can be closed due to new audio playing indicator, right? still, i notice the new one to flicker too, but will create a new ticket for that when i know the exact issue

**Comment by cezaraugusto** [comment]
@lucidNTR ya it can be closed, thanks for digging
