### ISSUE TITLE
How do you remove the browser

### ISSUE THREAD

**Issue by obannvi** [brave/browser-laptop#384]
I got everything installed, but I was wondering if there was a way to remove everything.

**Comment by gdi2290** [comment]
For mac to uninstall an app you simply drag and drop into trash. For some apps they also include an uninstaller, usually inside the installer. Otherwise installing an uninstaller helps for apps that also saves files outside of `Applications/` with http://freemacsoft.net/appcleaner/

**Comment by bbondy** [comment]
For Windows just go to Control Panel and uninstall programs from there like other programs.

**Comment by farhanghafoor** [comment]
Clicking on uninstall on windows 10 does nothing!

**Comment by bbondy** [comment]
It's working for me, are the files not being removed for you in the install dir? Or maybe just an icon is left behind? 
In any case you can just delete the files.

**Comment by safaldas** [comment]
hi how do I uninstall in Ubuntu

**Comment by luixxiul** [comment]
if you have installed via apt, you can remove it with apt remove brave.

**Comment by mikegleasonjr** [comment]
On OSX I...

1. dragged and dropped the app into the bin
2. emptied the bin
3. `rm -rf ~/Library/Application\ Support/brave/`

I don't know if there are files anywhere else..

**Comment by cesc1989** [comment]
In Ubuntu or Ubuntu based distros, it can be removed via `dpkg`:

    sudo dpkg --purge brave

**Comment by vermasaksham** [comment]
I downloaded Brave Browser via. Ubuntu Software Center. I used the command 'sudo apt remove brave', it says "Unable to locate package brave" and I also tried giving the command 'sudo dpkg --purge brave' but nothing happend. So how to remove it?

**Comment by cesc1989** [comment]
@vermasaksham can it be removed from Ubuntu Software Center?
