### ISSUE TITLE
Live video not loaded on Moneycontrol.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3840]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Live video not loaded on Moneycontrol.com

**Expected behavior:**
Should show the flash placeholder for user to decide to play or not.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 (Shields down)
- Steps to reproduce:
  1. Visit[ Moneycontrol.com](http://www.moneycontrol.com/tv/)
  2. Flash video shows error loading player.
     3.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18386960/ad61a308-7691-11e6-8ffe-980a69e18614.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18387004/eacbc28c-7691-11e6-822e-709360a551bc.png)

![image](https://cloud.githubusercontent.com/assets/17010094/18387040/187b2f6a-7692-11e6-9c42-93d7a7f09bcf.png)
- Any related issues:

**Comment by luixxiul** [comment]
I cannot load the player on Chrome either.
