### ISSUE TITLE
Directory of working extensions/add-ons?

### ISSUE THREAD

**Issue by Kinnardian** [brave/browser-laptop#3844]
Is there a listing of working Brave extensions/add-ons?

Related: https://github.com/brave/browser-laptop/issues/253

**Comment by Aerun** [comment]
I edited the source to allow me to install 'Reddit Enhancement Suite' and it works perfectly fine with Brave so far. It'd be nice if they opened up a 'developer mode' similar to Chrome for users who would like to test the extension capabilities easily and see what works so far and what doesn't.

**Comment by luixxiul** [comment]
> Is there a listing of working Brave extensions/add-ons?

Currently about:preferences#extensions displays all of the implemented extensions. https://github.com/brave/browser-laptop/projects/1 and https://community.brave.com/t/the-list-of-the-requested-extensions/10278 shows which extensions have been requested and are under consideration 😉
