### ISSUE TITLE
Location of the main .exe should not change with every single version

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3846]
From support:

> Can you please make it so the location of the main .exe doesn't change 
> with every single version? Otherwise I have to create a firewall rule 
> for every single version of the browser. 
> 
> I have seen other applications fix this by using a folder structure like: 
> AppData>Local>Brave (here the exe resides)>app-0.11.4(here all the 
> other files reside)

**Comment by bsclifton** [comment]
The shortcut (ex: the one on the desktop, or if you right click -> pin site to taskbar) should always be pointing to the update.exe, like so:
`C:\Users\brian\AppData\Local\brave\Update.exe --processStart "Brave.exe"`

**Comment by bsclifton** [comment]
Since Squirrel has a stub executable now, this should now be fixed 😄
