### ISSUE TITLE
History list shows unnecessary duplicates for same-page actions (like google maps)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3848]
![image](https://cloud.githubusercontent.com/assets/13509546/18396049/731ad69e-7676-11e6-8650-e85be1dcfc52.png)

**Comment by luixxiul** [comment]
I noticed it on Gmail too.

**Comment by bbondy** [comment]
different in-page navigation I guess?

**Comment by bsclifton** [comment]
I bet any query string params or anchor tags are counting as distinct entries- looking at what Chrome and Firefox do would be a good idea for next steps

**Comment by bbondy** [comment]
in-page navigation shouldn't add an entry I think is the main thing.  It's a different event in frame.js

**Comment by bbondy** [comment]
I think we're calling addSite in frame.js for in-page navigation 
Would still like this for 0.12.4.

**Comment by bsclifton** [comment]
Gonna have to dig a little deeper on this one... you had added this here:
https://github.com/brave/browser-laptop/commit/e44d45ee1be1b75f2dc803900b79390ba62b40e2

To avoid a regression, I'll need to test the icon loading scenarios

**Comment by bsclifton** [comment]
@bbondy can we kick this to 0.12.5?

**Comment by bbondy** [comment]
sure

**Comment by bsclifton** [comment]
Moving to 0.12.11. I think it's important enough to keep in the next milestone, but the change needs to be made carefully to avoid regressions

**Comment by bsclifton** [comment]
Moving to backlog- note to the interested person (and their reviewer): please make sure that after the potential fix does not break functionality introduced with https://github.com/brave/browser-laptop/commit/e44d45ee1be1b75f2dc803900b79390ba62b40e2

**Comment by bsclifton** [comment]
Having duplicate entries like this (for history) causes massive slowdown when typing in the URL bar (and also the process of saving the history).  This is an important issue and needs to be fixed soon

**Comment by bsclifton** [comment]
Per @bbondy, this should be fixed with https://github.com/brave/browser-laptop/pull/10005. Let's retest it 😄
