### ISSUE TITLE
1Password with a hotkey

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3849]
From support:

> The ability to summon 1Password with a hotkey (instead of using click / hover / menu commands).  I use 1Password ALL DAY and this would be such a welcome feature for power users.

**Comment by bsclifton** [comment]
You can pull up 1Password by pressing Ctrl + \ (on Windows) or Cmd + \ (on Mac).  When you do so, it'll auto fill in and even submit the form
