### ISSUE TITLE
"Save as" dialog can't be closed with ESC key

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3864]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**
When the "Save as" dialog appears asking you where to save the file you want to download, it can't be closed with the ESC key and you have to move the mouse to the Cancel button and click it in order to close the modal.

The source of the problem is that when the modal appears it does not gain focus on it, the focus is still on the webview.

**Expected behavior:**
Hitting ESC key when the Save as modal is opened should close it and the active tab should gain focus again.
- Platform (Win7, 8, 10? macOS? Linux distro?): Linux
- Brave Version:
  0.12.1
- Steps to reproduce:
  1. Try to download file
  2. When the Save as modal appears press ESC
  3. See nothing happens
- Screenshot if needed:
- Any related issues:

**Comment by ayumi** [comment]
I can't repro this. I'm running off master at a8de393d35bfd1a7aaaec9fce8c074f08561fca5 and tried to download files by left clicking links at http://www.thinkbroadband.com/download.html .

**Comment by Liunkae** [comment]
@Sh1d0w @ayumi Which platforms are you using? Works for me with Brave 0.12.9 on macOS 10.12.x.

**Comment by Sh1d0w** [comment]
@ayumi @Liunkae I am using Brave under Linux. It still does not work as expected on 0.12.9, following the steps above.

**Comment by ayumi** [comment]
It works for me on Brave 0.12.9 and Mac OS 10.11.6

**Comment by sergiorojasa** [comment]
It works for me on Brave 0.19.3 and Debian 9.

**Comment by sergiorojasa** [comment]
@ayumi I would like to work on this bug.

**Comment by sergiorojasa** [comment]
@ayumi should the save dialog be on focused by default when the user click on save as.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by kjozwiak** [comment]
Verified that the above issue has been fixed on macOS 10.13.3 x64 using the following build:
* 0.22.6 `e6ff4ea`
* libchromiumcontent: `65.0.3325.162`
* muon: `5.1.0`
