### ISSUE TITLE
Tab colors can make it difficult to tell which tab is active

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#387]
![tab_color](https://cloud.githubusercontent.com/assets/34129/12654886/71aa9778-c5b3-11e5-8de8-41e1856e152c.png)
@bradleyrichter

**Comment by bridiver** [comment]
slashdot tab is active, but the color scheme makes it appear as though the feedly tab is active

**Comment by bradleyrichter** [comment]
Switching our tab-color method to use the top pixel color of the page instead of the theme color or extraction from favicon should solve this problem. This a particularly bad example.

@bbondy We may need to increase the priority of this change if more issues are reported.

**Comment by bridiver** [comment]
in this case wouldn't that make the problem worse? The problem is that the inactive tab matches the active page background. I think it needs some other way to delineate the boundary between the inactive tabs and the content

**Comment by bradleyrichter** [comment]
we may need to add a border to go with it.

**Comment by bradleyrichter** [comment]
something like this:

![screen shot 2016-01-28 at 1 31 03 pm](https://cloud.githubusercontent.com/assets/13509546/12659406/7624d2e0-c5c3-11e5-8718-f0920dcea789.png)

**Comment by bridiver** [comment]
Yea, but I think the border needs some tweaking to make the tabs look like they are behind the content instead of in front of it.

**Comment by bradleyrichter** [comment]
you are right - it does create a weird optical illusion that's not working...

**Comment by bridiver** [comment]
there are some other border options that should produce the desired effect

**Comment by diracdeltas** [comment]
I think this would happen less often if we used the "vibrant" option from http://jariz.github.io/vibrant.js/ instead of "muted" (which is what it's set to currently). Any thoughts @bbondy ?

**Comment by diracdeltas** [comment]
slack before (muted color set):
![screen shot 2016-02-02 at 5 21 40 pm](https://cloud.githubusercontent.com/assets/549654/12770103/659cc7c6-c9d2-11e5-9166-bea70353ca62.png)

slack after (vibrant color set)
![screen shot 2016-02-02 at 5 27 40 pm](https://cloud.githubusercontent.com/assets/549654/12770104/6b4646e8-c9d2-11e5-976b-c49e31c23346.png)

**Comment by bbondy** [comment]
Great, hope this works better overall!  Would love to keep the code if we can.

**Comment by bradleyrichter** [comment]
@diracdeltas Did you happen to try brave.com? It was an unappetizing brown color before. I'm wondering what it looks like now?
I do think we should stop getting colors from the favicon. It just doesn't work reliably. So if no theme color (vibrant) exists, then use default tab color which is light grey. ( @bbondy )

**Comment by diracdeltas** [comment]
brave.com is orange

**Comment by bbondy** [comment]
I'm digging the new tab colors fwiw
