### ISSUE TITLE
Twitter videos are not playing

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3875]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
https://twitter.com/ra/status/774712408883560449 has an mp4 video in the tweet which is not playing. 

**Expected behavior:**
The browser should play the video without issue.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. https://twitter.com/ra/status/774712408883560449
  2. Attempt to play the video
- Screenshot if needed:
  <img width="632" alt="screen shot 2016-09-10 at 4 02 43 pm" src="https://cloud.githubusercontent.com/assets/1434040/18413542/781ce470-7770-11e6-92e4-50d998d7e62e.png">
- Any related issues:

**Comment by bridiver** [comment]
I'm not able to replicate on 0.12.2rc2

**Comment by luixxiul** [comment]
I cannot reproduce the issue either. Maybe it's been fixed already 😉
