### ISSUE TITLE
Regression : session.setPermissionRequestHandler callback is broken

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3877]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing http://www.bennish.net/web-notifications.html during a test run, it was noticed that the notifications were not displaying. 

**Expected behavior:**
The notifications should work.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 ia-32 and OS X

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Visit http://www.bennish.net/web-notifications.html
    2. Trigger a notification

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Notifications aren't supported in win7 since the start, so removing this from 0.12.1. The OS doesn't have them so we'd have to build something custom.

**Comment by alexwykoff** [comment]
This is also not working on Windows x64.

**Comment by bbondy** [comment]
which windows version?

**Comment by bbondy** [comment]
if windows 7 it is known and not a regression per above. Just label with Windows only and re-adjust title pls to indicate win7 only

**Comment by diracdeltas** [comment]
seems like permissions in general are  not working. geolocation str:
1. go to https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
2. click on the button in the demo
3. click 'allow' in the notification bar

it says location cannot be found

**Comment by diracdeltas** [comment]
@bbondy @bridiver i think this is an Electron issue. in `session.setPermissionRequestHandler`, the callback seems to reject the permission regardless of whether it's called with `true` or `false`.
