### ISSUE TITLE
Regression : Flash controls are not working

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3878]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing Flash controls in a test run, it was discovered that they are no longer functional.

**Expected behavior:**
Users should be able to enable Flash when they want.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested Windows 7 ia-32 and OS X

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Visit http://www.y8.com/games/superfighters
    2. Right-click on the flash cover 
    3. Observe if the game is ready to play

- Screenshot if needed:
![flash_player](https://cloud.githubusercontent.com/assets/1434040/18414413/7cd186c6-778c-11e6-93c7-5504efc60e26.gif)

- Any related issues:

**Comment by bbondy** [comment]
@diracdeltas could you take a look?

**Comment by bbondy** [comment]
@bridiver maybe because of the mutation observer removal and replacing with a timer?

**Comment by bridiver** [comment]
might be part of it, but I don't think that would cause the permission dialog to do nothing when clicked

**Comment by diracdeltas** [comment]
problem appears to be that `navigator.mimeTypes` and `navigators.plugins` is now empty regardless of the Flash controls. i.e., if i remove the `blockFlash` and `flashListener` content scripts and set the `flashActive` content setting to 'allow', Flash still doesn't work.
