### ISSUE TITLE
Suggestion: start a new tab when user start typing

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3880]
Hi, 

I know that to open a new tab is just press Ctrl + T, but I think Brave should have an option to start a new tab as user start typing. 
What do you think? Maybe an option in preferences to allow this.

**Comment by lucaszanella** [comment]
I'd use it

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/lets-discuss-start-a-new-tab-when-user-start-typing/10167

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
