### ISSUE TITLE
Search option for the sites listed in the Brave payments

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3882]
Hi, 

I have a lot of sites listed on Brave payments. I would like to disable some sites, but it's hard to find. I think a search option is necessary.

**Comment by mrose17** [comment]
just checking: i use "find" (ctrl-f or cmd-f) to search on that page page. does that work for you? thanks!

**Comment by bradleyrichter** [comment]
hello @bitcoinuser - Thanks for the feedback...

Can I ask a different question? How many sites do you want to see? 

Below the 1% threshold, the sites may not receive a payment. Do you still want to see them in your list?

Do you have sites that you would prefer to "black list" rather then toggling to "include-OFF"?



Thanks - Brad

**Comment by bitcoinuser** [comment]
Hi @bradleyrichter 

1- I want to see all sites.
2- Yes, I still want to see them
3- Not necessary to black list, just have option to turn ON or OFF like it works now.

@mrose17 Yes, Ctrl-f works, but not all people use hotkeys.

Thanks.

**Comment by bitcoinuser** [comment]
@mrose17 And what I would like is not just search but I would like to filter. (What I mean by filter is: Start typing will hide some sites of the list)
