### ISSUE TITLE
video playback lag 

### ISSUE THREAD

**Issue by thanatos7930** [brave/browser-laptop#3885]
when im playing any type of video at any website it lags randomly 
- Platform: windows 10 home 
- Brave Version: 0.12.0

**Comment by luixxiul** [comment]
Which page?

**Comment by thanatos7930** [comment]
i did say at any website but the websites i watch videos on most often would be youtube.com and chiaanime.co

**Comment by PostPollux** [comment]
Same here! I run Brave 0.13.5 under Linux Manjaro. 
It always occures about 5-10 seconds after I hit fullscreen on the youtube player. If I watch the video not int fullscreen, but in the default size, it runs without lag. When I try the same video in fullscreen with firefox, it works just fine...

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-video-playback-lag/10051

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
