### ISSUE TITLE
Brave payments: Line should always appear when user scroll down

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3888]
Hi,

I think this line on brave payments should always appear when user scroll down.

![captura de tela de 2016-09-11 09-10-53](https://cloud.githubusercontent.com/assets/1178856/18417227/5946a924-7800-11e6-8f24-f6a5be035ea3.png)

**Comment by mrose17** [comment]
@jkup - fyi: this probably should be dealt with at the same time as we deal with https://github.com/brave/browser-laptop/issues/3792

**Comment by jkup** [comment]
@bsclifton I think you had some good feedback about this table in chat somewhere but I can't find it. Was it lacking keyboard navigation or something?

**Comment by bsclifton** [comment]
Yes! the scrollbar was on the table itself, not on the window.  So it wasn't straightforward to scroll through the list (especially without a mouse)

**Comment by jkup** [comment]
@bsclifton ah yes! ok great, I'll add that work to this ticket. Thanks.

**Comment by bradleyrichter** [comment]
this solution doesn't seem to be working well enough

![image](https://cloud.githubusercontent.com/assets/13509546/19098617/8c100f6a-8a63-11e6-9f55-9caf537c5d2e.png)


@jkup  Can we instead float the entire top area including the list header row and then use the entire window for scrolling?

**Comment by jkup** [comment]
@bradleyrichter yeah I mean this is working as expected with the CSS hack I added to make the headers sticky. I agree that it would look much nicer if we didn't set a max-height on the list and just let the window scroll. Should I make a new issue for this? Either way I can get it in this week.

**Comment by bradleyrichter** [comment]
Sure. Close and make a new issue if you prefer.

**Comment by bbondy** [comment]
Reclosing but pls do a new issue since the change would be in 0.12.5 and this is in 0.12.4.
