### ISSUE TITLE
Brave payments: two popups?

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#3889]
Feedback:

I think a little strange show two popups.

![captura de tela de 2016-09-11 09-17-26](https://cloud.githubusercontent.com/assets/1178856/18417251/c2218072-7800-11e6-8807-fa6c17a38414.png)

**Comment by bitcoinuser** [comment]
Maybe should overshadow the main window, like what happens when we click on buy with coinbase:

![captura de tela de 2016-09-11 09-20-27](https://cloud.githubusercontent.com/assets/1178856/18417269/21728558-7801-11e6-983e-0a355c4e779c.png)

**Comment by luixxiul** [comment]
The issue has been fixed already.
