### ISSUE TITLE
Feature Request : Quit Brave when the last window is closed

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3896]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
https://linkbubble.zendesk.com/agent/tickets/5010 has requested to have a configuration option to quit the browser when the last window is closed.

**Comment by bbondy** [comment]
This is macOS only because that's the default behavior on all other OS I believe.

**Comment by flamsmark** [comment]
Don't the MacOS interaction guidelines contain specific admonitions about this?
