### ISSUE TITLE
1Password is not filling the form and Brave is saving the password 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3897]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to log into a website (ex: github.com) I tried to use 1Password after setting the preference in Brave. 1Password did not fill the form and after copying the password into the form, Brave offered to save it. If I chose yes, it was saved into about:passwords.

**Expected behavior:**
If I choose 1Password to manage my passwords, it should fill the login form and Brave should not offer to save the password. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Visit a site for which you have a 1Password login available
    2. Set 1Password as your password manager in Brave
    3. Attempt to log in

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
open pages must be reloaded after enabling 1password. That part is a 1password issue and it the same on Chrome and Safari. The Brave password manager save issue seems incorrect thought

**Comment by diracdeltas** [comment]
i can't repro the Brave-offering-to-save-passwords issue after enabling 1pw on OS X

**Comment by bbondy** [comment]
@alexwykoff can you confirm was this just because you needed to reload the page? If so let's kick it out of 0.12.1

**Comment by alexwykoff** [comment]
Indeed, reloading the page worked. Pushing this out to the next milestone.

**Comment by bridiver** [comment]
if it was just a reload issue I think we should close the ticket or change the fix to adding a notification that pages must be reloaded before 1pw will work

**Comment by bbondy** [comment]
Ya I'm going to mark this as wontfix, it's ok to make the user reload when changing this setting if they want to use.
