### ISSUE TITLE
Regression : Autofill modals do not open

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3903]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing 0.12.1 Preview3 the modals on about:autofill did not open. No error output appeared on the dev console.

**Expected behavior:**
The modals should open and I should be able to input values.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.1 Preview3

- Steps to reproduce:
    1. Visit about:autofill
    2. Attempt to create new records

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
which console did you use? For about pages you need to use the content dev tools with Command+Alt+I

**Comment by alexwykoff** [comment]
I tried both :)

Moving ~/Library/Application\ Support/brave seems to have alleviated the issue. 

I double-checked to see if values stored from 0.11.6 would cause an issue, they did not. Closing DNR

**Comment by bbondy** [comment]
@bradleyrichter your ghost is acting up again.
