### ISSUE TITLE
Regression : Spell check is missing

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3904]
**Did you search for similar issues before submitting this one?**
Yes 

**Describe the issue you encountered:**
When mistyping words, Brave usually underlines the word and provides alternative spellings in the context menu. 

**Expected behavior:**
The misspelled word should be highlighted and alternative spellings should be shown in the context menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Discovered on Linux, confirmed on OS X

- Brave Version:
0.12.1 Preview1 & Preview 3

- Steps to reproduce:
    1. Visit a site with a text input field (ex: https://wordcounter.net/)
    2. Misspell a word 'fead' instead of 'feed' or the like.

- Screenshot if needed:
<img width="468" alt="screen shot 2016-09-12 at 11 18 45 am" src="https://cloud.githubusercontent.com/assets/1434040/18443658/76cf29d6-78db-11e6-95ba-22ea51d49d88.png">
<img width="176" alt="screen shot 2016-09-12 at 11 18 59 am" src="https://cloud.githubusercontent.com/assets/1434040/18443659/78d8f4c8-78db-11e6-982a-4c60a48c76b7.png">

- Any related issues: #2602

**Comment by bridiver** [comment]
definitely something strange going on. Doesn't seem to work at all on the page you provided, but works on http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea for some misspellings. Could be a locale/dictionary issue

**Comment by bbondy** [comment]
There's an HTML attribute that disables it that we respect purposely.  Does Chrome show spell check there?

**Comment by bbondy** [comment]
and did it used to work (I'm assuming so because you used the word Regression)

**Comment by bridiver** [comment]
yea, spellcheck works on chrome for that page

**Comment by luixxiul** [comment]
Cannot confirm on Win10 JP due to #2602

**Comment by bridiver** [comment]
is #2602 just a missing JP dictionary? Can you check for English? I don't have a win10 vm running at the moment, but I can't start one if needed

**Comment by luixxiul** [comment]
I changed the language setting of Brave into English and tried again. Still not working.

**Comment by bridiver** [comment]
I'm not able to replicate a problem with spellcheck in general, the only problem I see is that the dictionary seems to contain some words that aren't really words, but the behavior is nearly identical on Chrome and Safari. Typing a `fdsafds` or `aas` triggers spellcheck for me. `fead` doesn't trigger spellcheck on any browser on mac

**Comment by bridiver** [comment]
![chrome](https://cloud.githubusercontent.com/assets/34129/18525758/b53cbaf6-7a72-11e6-8392-635f6806aae6.png)
![brave](https://cloud.githubusercontent.com/assets/34129/18525759/b5488ffc-7a72-11e6-8319-23ef533314ef.png)

**Comment by bridiver** [comment]
there was an issue getting the settings into the release build. @bbondy should be spinning new builds soon
