### ISSUE TITLE
Extra separator in the about:downloads right click context menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3908]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Extra separator in the about:downloads right click context menu

**Expected behavior:**
Extra separator should not be included in the context menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.1 Dev preview1, preview3

- Steps to reproduce:
    1. Download a file
    2. Open about:downloads 
    3. Right click on the downloaded item, context menu has extra separator after clear download

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18427769/19e02568-78c2-11e6-8c0a-34775029d9a9.png)

- Any related issues:
#3591

**Comment by aekeus** [comment]
++ confirmed - looks good
