### ISSUE TITLE
Brave crashes when Dashlane password manager is selected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3909]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave crashes when Dashlane password manager is selected 

**Expected behavior:**
Should not crash when password manager app is selected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.1 Dev Preview 3 (Clean install)

- Steps to reproduce:
    1. Go to preferences after clean install
    2. Select Dashlane from the password manager list
    3. Brave crashes after selection.

- Screenshot if needed:
![dashlane](https://cloud.githubusercontent.com/assets/17010094/18428106/067dde6e-78c4-11e6-9130-e2f66ee946ca.gif)

- Any related issues:

**Comment by bbondy** [comment]
@bridiver

**Comment by bridiver** [comment]
I forgot to remove the script they run on selection when I upgraded Dashlane. This likely affects all platforms.

**Comment by bridiver** [comment]
@bradleyrichter did you intentionally reopen this? The fix is only in master so you will still get the crash in RC1

**Comment by bbondy** [comment]
Re-closing, there's a ghost on Brad's machine that re-opens things.

**Comment by bradleyrichter** [comment]
@bridiver No. I have never touched this before. Weird GitHub ghost that is following me. Happens occasionally.
