### ISSUE TITLE
bookmark button color is too light on the new lighter UI

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#391]
cc @teemuteemu @bradleyrichter 

![screen shot 2016-01-28 at 13 16 18](https://cloud.githubusercontent.com/assets/549654/12659028/5d5feb66-c5c1-11e5-8b5c-b589a1cff53b.png)

**Comment by bbondy** [comment]
fwiw it was bad on old UI too :P

**Comment by bradleyrichter** [comment]
Brian picked that color...changing it to Brave-orange.

**Comment by bbondy** [comment]
...context of time is relevant here :).
Choice was made when we had a black background which was before your v1 designs.  Just never changed.

**Comment by bradleyrichter** [comment]
@bbondy Closing this as it will be solved in next round of UI improvements.

**Comment by diracdeltas** [comment]
I think this should stay open until it's actually fixed on master

**Comment by bradleyrichter** [comment]
sure. good idea.

**Comment by bradleyrichter** [comment]
Closing this as it actually is fixed. And even improved!
