### ISSUE TITLE
Brave wallet address text is not properly aligned when Transfer BTC button is enabled 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3910]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave wallet address is not properly aligned when Transfer BTC button is enabled

**Expected behavior:**
Text should be properly aligned  below the Transfer BTC button

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.1 Dev Preview 3

- Steps to reproduce:
    1. Go to https://jsfiddle.net/LnwtLckc/5/ and click the register button. 
    2. In Payments tab the text is not aligned properly next to the Transfer BTC button
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18428988/fc0d9c58-78c8-11e6-9e87-51bfb541b14f.png)

- Any related issues:
 #3677 

cc: @bradleyrichter @jkup

**Comment by bbondy** [comment]
Added in 0.12.1
