### ISSUE TITLE
Imported FireFox bookmarks are a total mess!

### ISSUE THREAD

**Issue by Kanichiro** [brave/browser-laptop#3913]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Imported links are an absolute mess
**Expected behavior:**
Links in their folders and sub-folders
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Mint 18 - Cinnamon desktop
- Brave Version:
![brave version](https://cloud.githubusercontent.com/assets/22098577/18440447/c6755558-78ce-11e6-908c-62871b74d81d.png)

- Steps to reproduce:
    1. Export FireFox bookmarks in HTML format
    2. Import these FireFox bookmarks
    3. Observe a total and complete mess

- Screenshot if needed:
![empty folders](https://cloud.githubusercontent.com/assets/22098577/18440441/bebd23ae-78ce-11e6-9acd-030de9ac5262.png)

- Any related issues:
A week ago I installed the Brave browser. I am running Linux Mint 18 with Cinnamon desktop.

About a day after testing Brave, I exported my FireFox bookmarks in HTML format. There are literally hundreds of links in my bookmarks. These links are divided into folder and sub-folders to make it easier to find the link I am seeking.

Now the problem... I've tried three times to import my bookmarks into the Brave browser. Each time I import them the results are a HUGE mess! Most of the folders and sub-folders are empty, and I suspect most of the links are not even visible. 

When viewing my bookmarks from the Bookmark Menu I only see a few dozen or so links. I am unable to scroll down what should be a long list of folders and links but I cannot.

To make matters worse, if I try to manually restore the itemized version of my bookmarks that I have in FireFox, I can expect to spend several days doing nothing else but sorting links in my bookmark folders.

Now I installed the Brave browser in the hopes of finding a browser that is faster than Firefox. Brave certainly meets that requirement. Unfortunately the bookmark issue is a real problem. Also the lack of Flash in Brave would prevent a complete browser change.

Does anyone know how to import my FireFox bookmarks without this unbelievable mess?

Thanks for any and all help...

**Comment by bradleyrichter** [comment]
@Kanichiro Sorry for the mess!

We are nearly finished with the import data tool that doesn't use HTML exports so this will be solved soon.

**Comment by Kanichiro** [comment]
Thanks, Bradley!  I'll start deleting my mess, which brings me to another issue with the bookmarks. Please allow mass deleting of links which would make my job easier.

**Comment by bradleyrichter** [comment]
@bbondy Is there a back-door way to help @Kanichiro with his mess?

**Comment by bbondy** [comment]
we're replacing with chromium HTML import, so this is actually a dupe that will be fixed there. And we have multi select management being tracked separately. @darkdh if you happen to know the dupe please close this as a dupe and link it.

**Comment by darkdh** [comment]
dup #2107

**Comment by Kanichiro** [comment]
I wanted to update my original post. While deleting my bookmark mess that was created after I imported my bookmarks from FireFox, I discovered that if I inserted a "space" into the Search box the rest of my links appeared.

After import I only saw a few dozen or so links which I deleted. I mistakenly assumed that most of my bookmarks did not get imported. However, after I entered a space in the search box I immediately saw the links that had been hidden from my view.

I am not certain if this info will be of help to your developers, but I wanted to let you know.

Please see the attached screen shots...
![before inserting a space in the search box](https://cloud.githubusercontent.com/assets/22098577/18677022/2c509db6-7f1d-11e6-9c4f-c3c7a605fb1b.png)
![after inserting a space in the search box](https://cloud.githubusercontent.com/assets/22098577/18677026/2f7f5b4e-7f1d-11e6-8252-bc899cf181f9.png)

**Comment by bradleyrichter** [comment]
Hi @Kanichiro ... Thanks for the follow up. This should be helpful...
