### ISSUE TITLE
Autocomplete pulldown on twitter log in dialog

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3915]
**Describe the issue you encountered:** The autocomplete pulldown on twitter log in dialog is off by 50px or so. 

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.1

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18441917/b9fd48aa-7949-11e6-9e24-3856b2d7f5c3.png)

- Any related issues:

**Comment by luixxiul** [comment]
It happens on roboform test page /cc: @darkdh

**Comment by luixxiul** [comment]
Setting a milestone for now.

**Comment by bbondy** [comment]
I can't seem to reproduce, it always goes to the correct location for me. Can you think of any differences?

**Comment by alexwykoff** [comment]
Cannot repro on OS X or Win7 VM.
<img width="1054" alt="screen shot 2016-09-12 at 6 21 18 pm" src="https://cloud.githubusercontent.com/assets/1434040/18456364/debfe9ce-7915-11e6-97b1-330cd7e1986a.png">

What resolution did you use for testing?

**Comment by luixxiul** [comment]
@alexwykoff the resolution is 1024x768.

**Comment by bbondy** [comment]
any ideas on this @darkdh ?

**Comment by darkdh** [comment]
I can't reproduce it even on win10 with 1024x768 resolution...
<img width="773" alt="screen shot 2016-09-17 at 21 14 10" src="https://cloud.githubusercontent.com/assets/11330831/18608440/cbd756da-7d1b-11e6-991d-a4c3963c6ae1.png">

**Comment by luixxiul** [comment]
This no longer happens to me too. I will reopen if I find a STR.
