### ISSUE TITLE
Button icons are style-wonked. Must fix.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3917]
Reload and BM at least...

![image](https://cloud.githubusercontent.com/assets/13509546/18442183/aaeb6ca0-78c4-11e6-8608-cad5efc22cbd.png)

![image](https://cloud.githubusercontent.com/assets/13509546/18442373/60bc5c1a-78c5-11e6-8dd4-63e2d3edc059.png)

also effects home, noscript per @diracdeltas 
![image](https://cloud.githubusercontent.com/assets/13509546/18454755/06344e66-78fb-11e6-9827-5795c67eb81e.png)

**Comment by bridiver** [comment]
the offset is wrong even with all extensions disabled so I think it's something else

**Comment by diracdeltas** [comment]
same for home button and noscript. https://github.com/brave/browser-laptop/issues/3934

**Comment by jkup** [comment]
Will move conversation into the PR.
