### ISSUE TITLE
`chrome.tabs.executeScript` with file parameter crashes Brave

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3919]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Dashlane runs executeScript with a file and this crashes Brave in release builds because the file location is not accessible 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.1

**Comment by bsclifton** [comment]
This extension functionality will be fixed when moving to Brave Core.  Since there hasn't been any updates, I'm going to close this as `wontfix`
