### ISSUE TITLE
Middle click tab to close tab on Windows

### ISSUE THREAD

**Issue by Fammy** [brave/browser-laptop#392]
On Windows, middle clicking a tab in other browsers typically closes that tab.

Issue #358 also discusses middle clicks and tabs, although for Mac OS.

**Comment by SamJongenelen** [comment]
When hovering with mousepointer over a tab and pressing the scroll wheel (some mouse support this), the tab under the pointer is closed. (Chrome/Edge/IE has it)

**Comment by bbondy** [comment]
Fixed, it'll be in the next version. Thanks for the feedback!
