### ISSUE TITLE
Feature Request : Add download rate and ETA to progress bar and about:downloads page.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3924]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When downloading a large file, it would be handy to know how much longer I have to wait.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.12.1 Preview1
- Steps to reproduce:
  1. Visit http://www.ubuntu.com/download/desktop/thank-you?country=US&version=16.04.1&architecture=amd64 and download the file
  2. While downloading, check the progress bar and about:downloads
- Screenshot if needed:
  <img width="687" alt="screen shot 2016-09-12 at 11 57 38 am" src="https://cloud.githubusercontent.com/assets/1434040/18444847/80475c54-78e0-11e6-9bb3-56d2e23f9f85.png">
- Any related issues:

**Comment by srirambv** [comment]
+1 from support 
> Hi guys, i was wondering why doesn't it show size of a file i download or downloading. It would be great if it showed the size of the file i will download. And also to show the speed in which its donwloading.

**Comment by alexwykoff** [comment]
+1 from me
Outside of the US, not all connections are reliable or fast.  Downloading installers repeatedly has impressed upon me the need for this feature.

cc @bbondy

**Comment by divyenduz** [comment]
+1

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/show-speed-download-size-of-file-when-downloading/3243

**Comment by philip-ulrich** [comment]
How is this still not a thing +1

**Comment by plgonzalezrx8** [comment]
Is this too hard to implement? Really?

**Comment by vanclute** [comment]
+1 big time!

**Comment by rebron** [comment]
Closing wontfix here. This is fixed in brave-core which includes download rate and eta.
