### ISSUE TITLE
Add read-only about:extensions page

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3926]
Users should be able to navigate to about:extensions to see the state of enabled / disabled extensions.  Currently how it works for now the only way to get a disabled extension is t switch to a different password manager and then back off of it.  Upon restarting the disabled extension doesn't show currently.

**Comment by bbondy** [comment]
<img width="1028" alt="screenshot 2016-09-12 16 22 53" src="https://cloud.githubusercontent.com/assets/831718/18451942/08ae284a-7907-11e6-8c22-d28632199753.png">

**Comment by bsclifton** [comment]
This is awesome, great job! :smile:

**Comment by luixxiul** [comment]
Is it ready for l10n?
