### ISSUE TITLE
Ledger does not work over Tor

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#3932]
`GET https://ledger.brave.com/v1/wallet/...` returns 403's due to Cloudflare.

QA steps:
1. set Tor as the system proxy using instructions such as https://kremalicious.com/simple-tor-setup-on-mac-os-x/
2. start Brave, go to check.torproject.org to make sure you are using Tor
3. open ledger payments panel and observe that the balance and wallet info is correctly displayed

**Comment by mrose17** [comment]
the issue was cloudflare not liking tor and putting up a captcha. as cloudflare is no longer in use, the issue is moot.
