### ISSUE TITLE
passwords.properties not loaded

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3946]
**Describe the issue you encountered:** `passwords.properties` is not applied.

**Expected behavior:** It should be loaded.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: master branch
- Screenshot if needed:

<img width="760" alt="screenshot 2016-09-13 15 07 58" src="https://cloud.githubusercontent.com/assets/3362943/18463288/ef9e65b4-79c3-11e6-9c6c-a0985b608ae6.png">
- Any related issues: #3671 #1858

**Comment by bbondy** [comment]
there is no password.properties only a passwords.properties

**Comment by bbondy** [comment]
found it we aren't using the translated string,

**Comment by bbondy** [comment]
I don't think we have a way to dynamically get strings in about: pages yet.

data-l10n-id works there, but the string that need to get the value dynamically I think don't:
https://github.com/brave/browser-laptop/blob/master/js/about/passwords.js#L137

It needs to use `confirmClearPasswords`


/cc @aekeus @bridiver
