### ISSUE TITLE
Make all properties files translatable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3947]
**Describe the issue you encountered:** Several ``.properties`` files cannot be translated.

https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/ja-JP/autofill.properties
https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/ja-JP/errorMessages.properties
https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/ja-JP/history.properties

- Brave Version: 0.12.1

- Any related issues: #1858

**Comment by luixxiul** [comment]
I think they are not set up for translation on transifex.com

**Comment by bbondy** [comment]
hah I just added those yesterday before you posted this. I will pull new translations now, and they should appear now.

**Comment by luixxiul** [comment]
Confirmed on transifex.com too, thanks :-)

**Comment by luixxiul** [comment]
Some strings are duping, eg: [app.properties#L188](https://github.com/brave/browser-laptop/blob/9bafcc2656a450bed78efbbfec5061aa89243661/app/extensions/brave/locales/ja-JP/app.properties#L188) and [autofill.properties#L11](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/ja-JP/autofill.properties#L11). We will need to organize them to avoid confusion.

**Comment by bbondy** [comment]
file issues I think when they come up, or work on one issue and put several of them in there in chunks.
