### ISSUE TITLE
App state should be saved periodically to be resistant to crashes.

### ISSUE THREAD

**Issue by Harrold** [brave/browser-laptop#395]
I added a few favorites and when the browser crashes, the favorites are all gone when I start up the browser again.

**Comment by bbondy** [comment]
So the task here is to flush out session store periodically instead of only on app load.  The crash obviously also needs to be handled but please post another issue for the crash if you have steps to reproduce it.

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/browser-laptop/commit/c6a180b2a518af758ba83c481a2fefdac8d75ab2
