### ISSUE TITLE
coinbase payment will not go through

### ISSUE THREAD

**Issue by oscarspaz** [brave/browser-laptop#3950]
Platform: Win 7
Brave Version: 0.12.0
Issue: Stuck on Coinbase Purchase confirmation. Expected payment to go through

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/1151899/18464333/01d2347c-7956-11e6-882a-0e94c0232869.png)

**Comment by mrose17** [comment]
@alexwykoff - can you see if this can be reproduced internally? i'm not able to repo it. thanks!

**Comment by alexwykoff** [comment]
i had perhaps a similar but different issue on my windows vm:

![infinite_loop](https://cloud.githubusercontent.com/assets/1434040/18852556/85a758d0-8406-11e6-9497-dcf6cba6a973.gif)

<img width="802" alt="screen shot 2016-09-26 at 4 28 59 pm" src="https://cloud.githubusercontent.com/assets/1434040/18852571/9d3a130c-8406-11e6-9aa8-badced7bc6dc.png">

**Comment by mrose17** [comment]
@alexwykoff - is it reproducible?

**Comment by alexwykoff** [comment]
I will attempt this on another windows 7 vm, an ubuntu vm, and a mac.

**Comment by alexwykoff** [comment]
Windows ia-32 - same result
<img width="1069" alt="screen shot 2016-09-27 at 1 26 39 am" src="https://cloud.githubusercontent.com/assets/1434040/18862411/8e60b318-8451-11e6-83ef-5de1ba68d9fa.png">

**Comment by alexwykoff** [comment]
Just repro'd on Ubuntu as well.  It seems like maybe the coinbase account is frozen pending some identification?

**Comment by mrose17** [comment]
@oscarspaz - thanks for reporting this. i can't reproduce it, and i suspect it's some kind of "widget error" (whatever that might be). i have alerted coinbase to the issue.

if i may impose on your patience: please try one more time and if it doesn't work, then do an "Inspect Element" and see what the console says. in particular, i'm looking to see if there are any errors such as the one that @alexwykoff posted above.

many thanks!

**Comment by DanielGuerin** [comment]
I tried to add $5 to my wallet, Coinbase msg'ed me a code and I clicked on the green bar at the bottom of their window and nothing happened:
![confirmfreeze](https://cloud.githubusercontent.com/assets/18453517/19098463/5141d7fc-8a7b-11e6-9699-87d08f903b6d.png)
here is the debug window:
![debugcbase](https://cloud.githubusercontent.com/assets/18453517/19098473/619e4bc6-8a7b-11e6-8e63-3aa4cd9101a5.png)

I'm running Brave on Windows 10.  Last month's payment went through.

**Comment by mrose17** [comment]
@DanielGuerin - thanks very much. i've passed this onto my contacts at coinbase and hope to hear back soon!

**Comment by DanielGuerin** [comment]
Just to update - I tried again this morning and the purchase went through.

**Comment by mrose17** [comment]
@DanielGuerin - thanks. the coinbase folks have updated the widget, so i'm going to mark this closed for now... thanks for your patience!

**Comment by oscarspaz** [comment]
I am going to try the payment again tonight. Thanks for looking into it. :-)

**Comment by bbondy** [comment]
Pls remove from milestone when there is one when closing w/o a commit, thanks!

**Comment by oscarspaz** [comment]
I try to go through the payment again and got stuck with a brave payment error message as described in this github issue #4920. Not a present experience just to get the payment going.
