### ISSUE TITLE
Brave Payment panel is not aligned

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3952]
**Describe the issue you encountered:** The titles and buttons are not aligned well on Brave Payment panel.
<img width="681" alt="screenshot 2016-09-13 19 49 07" src="https://cloud.githubusercontent.com/assets/3362943/18471127/549124c6-79eb-11e6-96df-ece23db34db0.png">

**Expected behavior:** Based on the spec image by @bradleyrichter (https://github.com/brave/browser-laptop/issues/3677#issue-174872992), it should be like this:
<img width="702" alt="screenshot 2016-09-13 19 53 58" src="https://cloud.githubusercontent.com/assets/3362943/18471240/df7cefde-79eb-11e6-9a24-9cf7044a267d.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.1

- Steps to reproduce:
    1. Change the language setting to Japanese
    2. Click "Add funds" button on ``about:preferences#payments``

- Screenshot if needed:

- Any related issues: #3677

**Comment by luixxiul** [comment]
Based on the latest translation I get this:
<img width="746" alt="screenshot 2016-09-14 3 09 26" src="https://cloud.githubusercontent.com/assets/3362943/18485684/d3f4406c-7a28-11e6-85cf-8715cf403bd3.png">

**Comment by bradleyrichter** [comment]
@jkup Coinbase string needs a max width?

**Comment by luixxiul** [comment]
It would be nice to include "visit" inside the button and make the place of "visit" and "Cubits" interchangeable as in Japanese it would be "Cubitsへ行く", which means "visit Cubits".

**Comment by luixxiul** [comment]
I'd like to have this:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18540036/c3538ffe-7b56-11e6-8cb5-6b37bfe86d86.png)

**Comment by bradleyrichter** [comment]
we can try this if it fits for all languages. Or we need to special-case J?

**Comment by luixxiul** [comment]
Making the site name a variable for transifex can be a solution, if it is OK to include "visit" inside the button.

**Comment by jkup** [comment]
@luixxiul it's a little tricky because the site name comes in dynamically from the ledger so I don't think we can store it in a transifex variable. We can definitely experiment with putting the word visit inside the button. I'll make that change tomorrow morning and update the PR.

**Comment by bradleyrichter** [comment]
sure. that works unless our URL is really long.

**Comment by luixxiul** [comment]
@jkup pinging for update on including text inside the button :-)

**Comment by jkup** [comment]
@luixxiul hey! can you make a separate ticket for that so it's easier to track? You can just assign it to me.
