### ISSUE TITLE
Notification bar styling

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3953]
**Describe the issue you encountered:** On facebook, the buttons are over the message on the notification bar. For me it does not happen when the language is set to English.

**Expected behavior:** The message should come first. The buttons should be on the bottom of the bar. 
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.1
- Screenshot if needed:
  <img width="505" alt="screenshot 2016-09-13 22 00 23" src="https://cloud.githubusercontent.com/assets/3362943/18474635/f72864d0-79fd-11e6-9cb9-c9bebb5923dd.png">
- Any related issues:

**Comment by bbondy** [comment]
@ayumi is this a dupe of what you worked on?

**Comment by ayumi** [comment]
@bbondy I worked on https://github.com/brave/browser-laptop/pull/3939 which upgraded buttons overflowing out of the notification / https://github.com/brave/browser-laptop/issues/3920 into this.

**Comment by luixxiul** [comment]
I have fixed the issue somewhere already.
