### ISSUE TITLE
Make sure we include all initial supported languages

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#3955]
@CCBrave got us this list of languages we'll ship 1.0 with.

@aekeus could you please verify that we include all of them, the regional codes may not be fully accurate but just fill in only the language if ones are missing.

Note this task is in 0.12.2 timeline so freeze is Friday.  We mainly want to get this moving to give localizers time.

German
Russian
Chinese
Japanese
French (France)
Bengali (Bangladesh)
Italian
Spanish
Brazilian-Portuguese
Polish
modern Malay (not Jawi)
Ukrainian
Korean
Indonesian
Tamil
Turkish
Slovenian 
Basque
Czech

**Comment by CCBrave** [comment]
The first 10 listed would be a must. If you need to drop any, the last 5
would be it (combo of lots to translate still (Tamil and Turkish), and
small markets for Slovenian/Basque/Czech).

**Comment by aekeus** [comment]
Current list running in master:

<img width="296" alt="screen shot 2016-09-13 at 3 51 49 pm" src="https://cloud.githubusercontent.com/assets/210240/18489110/32b80b60-79ca-11e6-87b5-22d1b69e1222.png">

**Comment by aekeus** [comment]
Translations for the remaining seven languages are at 81.9%. Request for info sent to Transifex, no response back yet.
