### ISSUE TITLE
Block 3P Cookie  doens't allow user login on LoneStarBall site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3956]
From Support 

> There are some websites where I sign in using my regular website login, but when the page refreshes I'm not logged in. This happens even when I turn off all ad blocking and script blocking options.

Block 3P Cookie doesn't allow user to login on http://lonestarball.com 
Disabling it works fine.
#3148

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
