### ISSUE TITLE
Organize strings in .properties files

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#3958]
https://github.com/brave/browser-laptop/issues/3947#issuecomment-246764384

> Some strings are duping, eg: [app.properties#L188](https://github.com/brave/browser-laptop/blob/9bafcc2656a450bed78efbbfec5061aa89243661/app/extensions/brave/locales/ja-JP/app.properties#L188) and [autofill.properties#L11](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/ja-JP/autofill.properties#L11). We will need to organize them to avoid confusion.

There is a lot of other duplicates too.

**Comment by bbondy** [comment]
I asked you to post an issue for this, but you already did, thanks :)

**Comment by PercussiveElbow** [comment]
Hey, interested in trying this. Is there a certain manner the strings should be organised in? :)

**Comment by bsclifton** [comment]
Reopening after reverting with https://github.com/brave/browser-laptop/commit/ab60908b80988d6c2023e59f34257be0ec04c387
