### ISSUE TITLE
SECURITY: [DID] Installer not timestamped, signed only with SHA1

### ISSUE THREAD

**Issue by ericlaw1979** [brave/browser-laptop#396]
The installer for Windows should probably be dual-signed with SHA256 and SHA1, and should be timestamped to avoid future compatibility problems.

http://textslashplain.com/2016/01/10/authenticode-in-2016/

**Comment by diracdeltas** [comment]
thanks, assigning to @aekeus

**Comment by throwaway2348** [comment]
I ran into this issues as well and it has twice stooped me from trying Brave. It doesn't give one a good feeling security-wise when software distributed for windows and endeavoring to be secure lacks a timestamp and SHA256 signature.

**Comment by aekeus** [comment]
Thanks, will work with @bbondy on this.

**Comment by diracdeltas** [comment]
@paulcbetts says this is fixed in the latest installer

**Comment by paulcbetts** [comment]
@diracdeltas This is a different bug than what I was think of at lunch, you need to pass /Fd SHA256 to the signtool parameters and make sure you have a SHA2 cert

**Comment by weems** [comment]
If Brave doesn't have access to the Verisign Utility, I think there is a open source protocol for TSA functionality here: https://www.freetsa.org/index_en.php

**Comment by paulcbetts** [comment]
You don't need any account or setup to use that URL, it's public

**Comment by weems** [comment]
@paulcbetts oh okay, cool.

**Comment by bbondy** [comment]
thanks @paulcbetts I'll take this.

**Comment by diracdeltas** [comment]
thanks @paulcbetts :+1:
