### ISSUE TITLE
Feature Request : Autofill selection should be able to be made via cursor keys

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3969]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Requested by https://linkbubble.zendesk.com/agent/tickets/5101 . A user should be able to select autofill values by pressing cursor keys (down/up).

**Expected behavior:**
After a value is selected, the form is filled.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
> 0.12.1

**Comment by darkdh** [comment]
duplicate #1302
