### ISSUE TITLE
adobe flash installer page keeps downloading flash player in a loop

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#3975]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When navigating to https://get.adobe.com/flashplayer/download/?installer=FP_23_Mac_for_Opera_and_Chromium_-_PPAPI&os=OSX&browser_type=KHTML&browser_dist=Chrome
the page keeps trying to download adobe flash player

**Expected behavior:**
It should download once and stop

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Go to https://get.adobe.com/flashplayer/download/?installer=FP_23_Mac_for_Opera_and_Chromium_-_PPAPI&os=OSX&browser_type=KHTML&browser_dist=Chrome

cc @diracdeltas

**Comment by diracdeltas** [comment]
it downloads fine for me - may be an Adobe server issue?

**Comment by bridiver** [comment]
it downloads fine and then keeps downloading over and over again. I think you can only replicate if you don't have flash installed

**Comment by bridiver** [comment]
I believe this was fixed by https://github.com/brave/browser-laptop/commit/d348ff9df08b6d50a18cab27ca5bb204d6230906
