### ISSUE TITLE
1password button does nothing after switch toggle and 3 reboots

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#3976]
mac

0.12.1

![image](https://cloud.githubusercontent.com/assets/13509546/18495097/fb0842ec-79cf-11e6-9434-58e8898df80f.png)

CC @bridiver

**Comment by bsclifton** [comment]
I can repro on Windows

**Comment by bridiver** [comment]
I can't repro on mac. @bradleyrichter can you send me your user data dir? @bsclifton what version of 1password? I have no idea if Brave is supported on 1pw6 for windows and there is no option to disable code signature checking

**Comment by bbondy** [comment]
can you guys check if it is also a problem with 0.12.0?

**Comment by bridiver** [comment]
actually I did get 1pw to work on 0.12.0, but that was a release build with code sig. I'll try it with the dev tag

**Comment by bridiver** [comment]
I think @bradleyrichter has an older preview release with a bug that broke the extension buttons. He said 1pw works from the context menu which is consistent with that theory. I need to check windows with a release build to verify that I'm seeing a code sig issue and not an actual bug

**Comment by bsclifton** [comment]
@bridiver 1PW 6 is definitely supported (as in the code signature was added) as of version 6.0197 ([release notes here](https://app-updates.agilebits.com/product_history/OPW6))

I'm on Windows 10 pro x64 and w/ 1PW, I was on version 6.0.207.  I just noticed an update is available which I downloaded and tried (6.0.214). The extension button still doesn't work... however, 1Password mini works just fine (if I hit ctrl + \)

**Comment by bridiver** [comment]
@bsclifton are you using dev or release build? Is it the most recent preview?

**Comment by bridiver** [comment]
let's check back on this tomorrow when a new build is available

**Comment by bbondy** [comment]
I'm particularly looking for people who can reproduce it on 0.12.1, @bsclifton and @bradleyrichter, can you also reproduce the problem on 0.12.0?

**Comment by srirambv** [comment]
0.12.0 - 1PW works with Ctrl+\ opens up the mini app
0.12.1(Preview Build) - 1PW works with Ctrl+\ opens up the mini app but the widget next to Shields doesn't launch the mini app
0.12.1(RC1) - 1PW works with Ctrl+\ opens up the mini app, Clicking on the widget also opens up the mini app.

**Comment by bbondy** [comment]
Thanks for clarifying, @srirambv so this can be closed then?

**Comment by bsclifton** [comment]
also confirmed!
- 0.12.0 - doesn't show the extension button (because it didn't exist yet), but 1PW works fine
- 0.12.1 RC1 - extension button works great

@bridiver suggested that it could be an issue of the code signature when running a dev build (which is how I noticed the issue)

**Comment by bridiver** [comment]
I also tested on win and mac and everything looks good. I think the previous release was missing the fix for the extension button so I'm going to go ahead and close
