### ISSUE TITLE
Mouse middle click on a target _blank crashes

### ISSUE THREAD

**Issue by chtefi** [brave/browser-laptop#398]
Hey,

I just noticed Brave crashes (close itself instantly, no message) if I click with the mouse middle button on a `<a target="_blank">`.
I'm on Windows 10.

You can give a try here : http://jsbin.com/ximobediye/1

**Comment by bbondy** [comment]
Could you check this one out? Seen a few mentions of it.

**Comment by bbondy** [comment]
Dupe of #412
