### ISSUE TITLE
Windows and tabs should recover in the case of a crash

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3981]
**Did you search for similar issues before submitting this one?**
Yes 

**Describe the issue you encountered:**
A user from support https://linkbubble.zendesk.com/agent/tickets/5178 stated that they lost about 5 minutes of browsing activity after recovering from a crash. They would prefer a tighter window (1 minute or less)

**Expected behavior:**
The browser should be able to recover gracefully from crashes.
 
- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
> 0.12.1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
tracking this here https://github.com/brave/browser-laptop/issues/4011
