### ISSUE TITLE
Feature Request : Users need other ways to provide feedback other than registered email handlers

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#3985]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When trying to submit feedback via the app, if a user does not have a registered email handler, the request goes into limbo. 
The barrier to providing feedback for issues is quite high and only the most motivated will do so. This will lead to many missed issues.

**Expected behavior:**
Users should have a simple and effective means of providing feedback and finding help for their issues which does not require resources other than the browser and a network connection.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  
  > 0.12.1
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:
  https://github.com/brave/browser-laptop/issues/2966
  https://linkbubble.zendesk.com/agent/tickets/5188

**Comment by alexwykoff** [comment]
cc @bradleyrichter

**Comment by luixxiul** [comment]
Closing as the community has replaced email support system :-)
