### ISSUE TITLE
Feature request: Allow Bookmarks sidebar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3990]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Request from Support [5474](https://linkbubble.zendesk.com/agent/tickets/5474)

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  
  > 0.12.1

+1 from me as well

cc: @bradleyrichter

**Comment by srirambv** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/6936

**Comment by bradleyrichter** [comment]
We should make this a driver for bookmarking 2.0. @alexwykoff ...

First we need proper drag-n-drop support.

**Comment by BrianDvich** [comment]
Yes please! The one issue stopping me from adopting "Brave". A "Bookmarks Sidebar" (docked left pane).

**Comment by vaulcul** [comment]
It'd also be nice to have the ability to add extra buttons to the sidebar... allow us to do things like see our downloads, history, etc. in the sidebar as well (as an option of course).

**Comment by bytepipe** [comment]
+1 on this functionality/feature. For me, every time I try to use Brave it quickly becomes a hassle for anything beyond a simple session as I cannot use my extensive bookmark library I have in Firefox (or had in old Opera).  Let folks like me have a bookmark bar and a side panel similar to Firefox and that will be a huge improvement in usability / experience allowing for adoption for primary use.  Opening the bookmark manager or combining lists into a few drop downs to see everything I need just doesn't cut it.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/464
