### ISSUE TITLE
Can't authorise to Google when signing in to draw.io

### ISSUE THREAD

**Issue by Nealsch** [brave/browser-laptop#3992]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  MacOS 10.11.6
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Open draw.io
  2. Open existing drawing on Google drive
  3. Request authentication from Google
- Get sign in page, appears to sign in successfully
- Then nothing happens
- If I again click the sign in button I get the error below
- Screenshot if needed:
  There was an error!
  Details:
  The feature you requested is currently unavailable. Please try again later.
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/cant-authorise-to-google-when-signing-in-to-draw-io/10105

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!

**Comment by IGotAHeadache** [comment]
I know I just experienced this issue, and @luixxiul added a "needs discussion" tag about a month ago. And the link listed about just leads back here.... so any new details? Pretty much the same issue, but this isn't Google Drive through personal, it is google drive through apps at work. Might make a difference though I have been able to authorize third-party applications in the past.
