### ISSUE TITLE
Enabling payments automatically creates a Brave wallet

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3993]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling payments automatically creates a Brave wallet. In previous builds the create wallet button was shown when Payments was enabled

**Expected behavior:**
Should show the create wallet button when payments is enabled.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.1 RC1 (Clean Install)

- Steps to reproduce:
    1. Do a clean install of RC1
    2. Open preferences page and enable payments
    3. Wallet is automatically created when payments is enabled.

- Screenshot if needed:
![2](https://cloud.githubusercontent.com/assets/17010094/18508538/5cd4df20-7a6c-11e6-8764-2ec66e53a906.gif)

- Any related issues:

**Comment by bbondy** [comment]
@mrose17 is this respin worthy for 0.12.1?

**Comment by mrose17** [comment]
@bbondy: no. we'll catch it next time

**Comment by diracdeltas** [comment]
This is not a bug. I was asked several times to implement this as a feature by @bradleyrichter and @mrose17. https://github.com/brave/browser-laptop/issues/3827

Granted it was marked for 0.12.2, not 0.12.1, but I don't see harm in it landing early.
