### ISSUE TITLE
close browser when use mouse right button in flash window

### ISSUE THREAD

**Issue by qwerty3131** [brave/browser-laptop#3995]
- Platform (Win7, 8, 10? macOS? Linux distro?):
  win7 x64
- Brave Version:
  0.12.1

**Comment by luixxiul** [comment]
I'm closing this issue as stale. If you are still around here, would you please join https://community.brave.com to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
