### ISSUE TITLE
ChristianForums.com won't work

### ISSUE THREAD

**Issue by bledwards1** [brave/browser-laptop#3997]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When visiting http://christianforums.com you are redirected to https://christianforums.com -- Which would normally be okay. But ... Their site will redirect you to here: https://sendy.christianforums.com/login
**Expected behavior:**
It should take you to the main page to browse their forums
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10
- Brave Version:
0.12.0
- Steps to reproduce:
    1. Please visit the above URL. That is the only repro step
    2.
    3.

- Screenshot if needed:

- Any related issues:
Hoping that there is either some outreach or something that can be done to make this site work in Brave.

**Comment by bledwards1** [comment]
This also results in links like this:
http://www.christianforums.com/threads/deism.733987/#post-8772969

Throwing 404's because it will redirect to https.  I'm trying to find a viable workaround with no success :(

**Comment by Liunkae** [comment]
Try disabling HTTPS Everywhere in the Bravery Panel. Click the Brave logo in the top right or click Bravery > Bravery site settings in the menu

**Comment by luixxiul** [comment]
It seems the ruleset has been updated and the issue cannot be reproduced.
