### ISSUE TITLE
Flash content not loaded in Private window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3998]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Visit any site which has flash content running. Flash placeholder is shown but selecting allow once/allow for 1 week doesn't load flash content in the private tab

**Expected behavior:**
Should run flash content when allow is selected

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.1 RC1

- Steps to reproduce:
    1. Visit any site with flash content in it on private tab
    2. Select Allow Once/Allow for 1 week in the placeholder
    3. Page refreshes but doesn't load the flash content. Shows could not load plugin
    4. Close the private tab and open the same site in a normal tab flash video automatically starts since its allowed in preferences.

- Screenshot if needed:
 ![2](https://cloud.githubusercontent.com/assets/17010094/18517598/c1a52658-7a94-11e6-9c6d-33ebf7b8dcd4.gif)

- Any related issues:

cc: @diracdeltas

**Comment by diracdeltas** [comment]
fixed in 45b3e64c0d912ec906c024fec12a2886ec6a1276

**Comment by alexwykoff** [comment]
This did not pass on Windows 7 x64 for 0.12.3 RC6
![private_tab_flash](https://cloud.githubusercontent.com/assets/1434040/19026338/02a48e5c-8957-11e6-9bec-e03f282e108d.gif)

**Comment by diracdeltas** [comment]
@alexwykoff that's because 45b3e64 isn't in the `dev-channel` branch

cc @bbondy; i think this is fine to release but definitely doesn't block the RC.
