### ISSUE TITLE
"Allow null to show you notifications?" appears by clicking Copy Link Location of file on download bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4003]
**Describe the issue you encountered:** "Allow null to show you notifications?" appears by clicking Copy Link Location of item on download bar.

**Expected behavior:** It should not appear.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit (Version 1511, OS Build 10586.589)

- Brave Version: 0.12.1 RC1

- Steps to reproduce:
    1. Download this page: https://github.com/brave/browser-laptop/issues/4001
    2. Click "Copy Link Location" of the file on the download bar

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18520032/12d4aa02-7ae1-11e6-9dde-23998bea9c6a.png)

- Any related issues:

Setting a milestone for now as it may be a blocker. Please remove it if not.

**Comment by diracdeltas** [comment]
i'll take the related issue https://github.com/brave/browser-laptop/issues/4006
