### ISSUE TITLE
Extra separator in new tab context menu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4004]
**Describe the issue you encountered:**

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18521757/5dbe04a8-7ae8-11e6-909e-03945fe54d25.png)

**Expected behavior:** The top separator should be removed

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.1 RC1

- Any related issues: #3670 #3908 

Setting a milestone as it seems to be easy to fix it.

**Comment by bridiver** [comment]
can we move this to 0.12.2? I know it's a small issue, but it doesn't seem like a blocker @bbondy ?

**Comment by Liunkae** [comment]
Fixed with 51f654c.

**Comment by bbondy** [comment]
@Liunkae pls email me brian @ brave thx.
