### ISSUE TITLE
New tab should not be bookmarked from bookmark menu on menubar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4005]
**Describe the issue you encountered:** https://github.com/brave/browser-laptop/pull/3813#issue-175701018

> Bookmark indicator
> 1. Open a new tab
> 2. Bookmark indicator should not be activated
> 3. Bookmarks menu "Bookmark this page" should not be checked

It can be checked on Windows 10.

**Expected behavior:** It should not be checked.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.1 RC1
- Steps to reproduce:
  1. Remove temporarily your brave folder
  2. Open Brave
  3. Follow STR above
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18522998/42399f12-7aed-11e6-9894-88a901cd19cf.png)
- Any related issues: #3813

**Comment by bsclifton** [comment]
This was fixed somewhere along the line (I believe I fixed it when doing some menu refactoring ~0.14.x?)
