### ISSUE TITLE
Block script icon is off location when URL bar is hidden

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4007]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Block script icon is off location when ULR bar is hiddren

**Expected behavior:**
Shoudl be properly aligned

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows, Ubuntu

- Brave Version:
0.12.1 RC1

- Steps to reproduce:
    1. Enable Auto hide URL
    2. Enable Block script 
    3. Visit http://brianbondy.com and move the cursor away from the URL bar to autohide
    4. Block script icon is off location.

- Screenshot if needed:
 ![image](https://cloud.githubusercontent.com/assets/17010094/18525657/4f61e9ac-7ab5-11e6-85af-660b24a75a1d.png)

- Any related issues:

**Comment by diracdeltas** [comment]
probably caused by my fix to https://github.com/brave/browser-laptop/issues/3931

**Comment by diracdeltas** [comment]
@jkup if you know an easy way to fix this on all screens, please take

**Comment by jkup** [comment]
@diracdeltas sure I'll take it!

**Comment by diracdeltas** [comment]
thanks!
