### ISSUE TITLE
Improper jQuery .val usage will crash Brave but not other browsers

### ISSUE THREAD

**Issue by bledwards1** [brave/browser-laptop#4008]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
If you throw brave a .val instead of .val(); it will crash the browser.
**Expected behavior:**
Brave should not crash - it should throw an alert like Edge and Chrome do.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win 10
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Please see this codepen for repro: https://codepen.io/bledwards1/pen/dprNZr
  2. Do not enter any data into the text input. 
  3. Click the Test Me! button. Brave will crash. Test the same link in other browsers.
- Screenshot if needed:
  N/A
- Any related issues:
  N/A

**Comment by Liunkae** [comment]
Works fine for me with Brave 0.12.9 on macOS 10.12.x.

**Comment by bledwards1** [comment]
Yep! Looks to be fixed in 0.12.9 in Win 10 too.

**Comment by bsclifton** [comment]
Closing issue for now- please reopen if it occurs again :smile:
