### ISSUE TITLE
About Brave dialog should differentiate between preview, rc and releases

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#4009]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When debugging issues on preview and rc releases, there is no way to know which preview or rc version it is or if it's the final vs a preview/rc

**Expected behavior:**
Some additional information like the preview or rc id or maybe a build number would be helpful

**Comment by Liunkae** [comment]
Related: #4386 and #5462

**Comment by bbondy** [comment]
This is a dupe of https://github.com/brave/browser-laptop/issues/5462 so I'm duping to that and I'll put you as the assignee there @bridiver since you are here.
