### ISSUE TITLE
put some "shine" on the ledger notifications

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#4019]
example 1: if the client can't retrieve the data, how does it now that the account is under balance. seems to me that the "Your account..." status shouldn't be there:

![0](https://cloud.githubusercontent.com/assets/400552/18545776/6fdb6c8c-7aef-11e6-86ad-dd75ccb51434.png)

example 2: at the top we're told we have less than 24h to review (great!), but the status gives a date for the next contribution (confusing). i suggest that when <=24h, that the status indicate how long until the contribution. (hint: use the magnificent [moment](https://github.com/moment/moment) package, e.g. `moment.fromNow(true)`):

![1](https://cloud.githubusercontent.com/assets/400552/18545851/d83663e0-7aef-11e6-9cb7-5be1bdd67c10.png)

example 3: when funds are pending, i don't think it makes sense to talk about a 'Next contribution':

![2](https://cloud.githubusercontent.com/assets/400552/18545883/f999e80e-7aef-11e6-8e4a-0229f0ba0c85.png)

example 4: if the contribution date is in the past (this screenshot was taken on 9/15), and the balance is sufficient, then instead of "Next contribution" we ought to have something like "Contribution being processed":

![3](https://cloud.githubusercontent.com/assets/400552/18545929/2c0d1504-7af0-11e6-963d-d7b2d95724df.png)

**Comment by bradleyrichter** [comment]
example 1: Agreed. Status report should switch to something like: Status update not available. Please check your internet connection and try again.

example 2: seems like P2 polish to me.

ex 3: why not? If it's tomorrow, then hurry up!

ex 4: different problem - the contribution date can never be in the past. In this case, always make it the same day?

**Comment by mrose17** [comment]
also note that in example 2, there is no "Later" button. there should be. otherwise, the only way to get the notification to go away is to click "Review your chosen sites".

**Comment by bradleyrichter** [comment]
One point I forgot to make here. Most likely, the top bar notifications will not be seen together with ledger screen until user clicks on the CTA button.

#2 needs an "Ok" button. I think 24h later is already later. No?

**Comment by mrose17** [comment]
i suspect that if the active tab is `about:preferences#payments` then notifications shouldn't be seen. i don't know whether they should be discarded or re-scheduled.

@diracdeltas & @ayumi - your thoughts?

**Comment by mrose17** [comment]
@bsclifton - can we close this issue now?

**Comment by bsclifton** [comment]
@mrose17 absolutely- @luixxiul has done a killer job with the CSS

From here on out, we can open issues as-needed :smile:

**Comment by mrose17** [comment]
groovy!

**Comment by luixxiul** [comment]
While I haven't tweaked something on the notification bar?

**Comment by mrose17** [comment]
@luixxiul - i think that as a part of some general refactoring, the notification bar issue above was polished... so, we're done with this issue!

**Comment by luixxiul** [comment]
sweet!
