### ISSUE TITLE
Copy to clipboard(Flash plugin) blocked on Reverso.net

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4020]
## Test Plan:
1. go to reverso.net with flash enabled in about:preferences and shields down
2. enter something in the box and click translate
3. you should see a flash notification bar. click 'allow'
4. click on the copy-paste icon in the results box. the page should tell you that the text was copied.

## Original issue description

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Copy to clipboard(Flash plugin) blocked on Reverso.net. 

**Expected behavior:**
Should allow the plugin to run to enable clipboard functionality
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 RC1 (Clean Install)
- Steps to reproduce:
  1. Visit http://reverso.net
  2. Type in a word in the Enter/Paste textbox
  3. Select a language to translate
  4. After page loads the clipboard function loads and then gets blocked.
- Screenshot if needed:
  Flash content on Chrome
  ![image](https://cloud.githubusercontent.com/assets/17010094/18548815/a5865862-7b42-11e6-9c90-68ff2b117eb4.png)
  
  Brave
  ![image](https://cloud.githubusercontent.com/assets/17010094/18548827/afd8ad7e-7b42-11e6-9c39-80386b0b02ac.png)
  Clipboard item blocked after page refresh
  ![1](https://cloud.githubusercontent.com/assets/17010094/18548897/13bc4878-7b43-11e6-825e-f8b05196cd17.gif)
- Any related issues:

cc: @diracdeltas

**Comment by diracdeltas** [comment]
@srirambv i don't see a 'copy' element in either Chrome or Brave.
![screen shot 2017-03-16 at 6 27 22 pm](https://cloud.githubusercontent.com/assets/549654/24012461/f2177b8a-0a75-11e7-9853-ba591df0f7f4.png)

**Comment by diracdeltas** [comment]
nvm, i found it. the issue is that the flash element is in an iframe.

**Comment by luixxiul** [comment]
Note: needs next preview to test this (it's on the master branch yet)

**Comment by srirambv** [comment]
Not working on Windows x65 0.14.0 Preivew 4 build. 
![reverso](https://cloud.githubusercontent.com/assets/17010094/24171987/8222c7e6-0e7e-11e7-8453-8fd778931584.gif)

**Comment by diracdeltas** [comment]
@srirambv as stated in the PR test plan, you have to turn shields down on reverso.net first

**Comment by srirambv** [comment]
Sorry my bad. Missed the shields down part.. Works as expected.
