### ISSUE TITLE
Regression : Users cannot allow mixed-content in a private tab

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4031]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While verifying https://github.com/brave/browser-laptop/issues/3795 it was found that I cannot allow for mixed content on the private tab. The 'secure connection' message is displayed instead.

**Expected behavior:**
I should be able to allow mixed content in a private tab and it should behave independently from the normal tabs.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Confirmed on all.

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Open a private tab.
    2. Navigate to https://mixed-script.badssl.com/
    3. Attempt to allow mixed content by clicking on the blue lock in the address bar.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
cc @diracdeltas

**Comment by diracdeltas** [comment]
This is intended

**Comment by diracdeltas** [comment]
will probably be fixed as part of https://github.com/brave/browser-laptop/issues/1824

**Comment by bbondy** [comment]
Small triage thing that can help, when closing issues without landed code, pls clear milestone. Thanks!

**Comment by diracdeltas** [comment]
@bbondy will do next time
