### ISSUE TITLE
Calling preventDefault on keyboard event doesn't stop backspace navigation

### ISSUE THREAD

**Issue by bluehexagons** [brave/browser-laptop#4033]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When listening for keyboard events, calling preventDefault (and stopPropagation, and returning false, just in case) on the KeyboardEvent object does not keep the browser from navigating back.

**Expected behavior:**
The event listener should be able to stop the navigation and keep the user on the web page.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Linux Mint 18
- Brave Version:
  0.12.0
- Steps to reproduce:
  1. Visit this fiddle in a tab with a back history: https://jsfiddle.net/96fLxrvj/2/
  2. Click in bottom-right preview area to make the iframe active
  3. Press backspace
  4. Brave will navigate back

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/6248

**Comment by mikeal** [comment]
I am also seeing this behavior. It's made worse by the fact that backspace in textarea in a shadowdom also triggers the back navigation.
