### ISSUE TITLE
Blockscript/Favourite icons look faded 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4035]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Blockscript/Favourite icons look faded 

**Expected behavior:**
Should not look faded

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, Ubuntu

- Brave Version:
0.12.1 RC2

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18564627/48026e6e-7b84-11e6-8b74-1fa641550151.png)

- Any related issues:

cc: @jkup

**Comment by bbondy** [comment]
@diracdeltas is it on purpose?

**Comment by jkup** [comment]
@bbondy yes I did that yesterday per @diracdeltas' instructions

**Comment by diracdeltas** [comment]
i may have said the wrong thing; the icons in titlemode should actually be 100% opacity all the time. in non-titlemode, they are faded out until hovered over.

**Comment by jkup** [comment]
@diracdeltas ok sweet, yeah i just asked and Brad said the same thing, I'll do that and file the PR under this issue.
