### ISSUE TITLE
Connection error tabs not showing error message

### ISSUE THREAD

**Issue by charbelrami** [brave/browser-laptop#4036]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I am offline and open a new Brave window, it shows 3 errors tabs (1 for each pinned tab probably). It doesn't show the connection error message in any of these tabs even if the tab is refreshed. The message is only shown when I clone a tab or enter a new URL

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 64-bit

- Brave Version:
0.12.1dev-RC2

- Steps to reproduce:
    1. Pin some tabs
    2. Go offline
    3. Open Brave

- Screenshot if needed:
![no-connection-error](https://cloud.githubusercontent.com/assets/5647344/18564993/6575fefe-7b64-11e6-8e5f-302bb3e66ce1.gif)

- Any related issues:

**Comment by bbondy** [comment]
@bridiver after v53 pls take a look

**Comment by bridiver** [comment]
version lists RC2, has anyone verified the problem on 0.12.1 final?

**Comment by bridiver** [comment]
now that we have network up/down notifications we should reload these tabs automatically (lazily?) when the network is restored

**Comment by bbondy** [comment]
@alexwykoff or @luixxiul could either of you verify if this needs to be in here and if it's still a problem?  Thanks. See @bridiver 's question above.

**Comment by alexwykoff** [comment]
Here is what I noticed having launched from : commit dfe352c8b491d3bf7f3b7bfbce88c901fe504a09

1. The tabs do not automatically reload once the network is restored.
2. The blank tabs only occur when the user has pinned items.
3. Quitting the app while having a pinned item causes the pin to duplicate when the app is relaunched.

**Comment by bridiver** [comment]
tabs have never automatically reloaded, but it's now possible because we added network up/down notifications. Should be filed as an issue if one doesn't already exist

Are you sure it started with https://github.com/brave/browser-laptop/commit/dfe352c8b491d3bf7f3b7bfbce88c901fe504a09 ? That only relates to cert errors

I'll take a look at the blank tab issue

**Comment by bridiver** [comment]
oh, sorry, you just meant that you tested on https://github.com/brave/browser-laptop/commit/dfe352c8b491d3bf7f3b7bfbce88c901fe504a09. I read that wrong the first time
