### ISSUE TITLE
QR Code Popup from Add funds dialog scrolls independently from its parent

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4043]
It is one of the cutest bugs I have ever seen. But a bug, none the less.

(found on a Dell XPS with touchpad scrolling)

Brave 0.12.1 release version

**Comment by luixxiul** [comment]
Is this intended?

![ledger-popup](https://cloud.githubusercontent.com/assets/3362943/18813091/1a96acde-8326-11e6-9734-7b835ed0ba96.gif)

**Comment by bbondy** [comment]
Assuming the current behavior is not horrible I'm moving it to 0.12.3, let me know if anyone disagrees.

**Comment by luixxiul** [comment]
On a small window with a vertical scroll bar it still happens.

![ledger-popup](https://cloud.githubusercontent.com/assets/3362943/18919168/1b57b460-85d8-11e6-89e6-d3b058b69ebd.gif)

wontfix?

**Comment by bradleyrichter** [comment]
needs more fixing 

@jkup Any ideas? If it's only at this small size, we can push this out to 0.12.4.

**Comment by aekeus** [comment]
Independent scroll on macOS

![qr-scroll](https://cloud.githubusercontent.com/assets/210240/18935619/40729f72-85af-11e6-9ded-d6ebe5a98915.gif)

**Comment by jkup** [comment]
I think I'm just not understanding what the desired behavior is here. Is the *bug* the fact that the background of the page like monthly budget, balance and statements is scrolling when you try to scroll the modal?

Because the modal itself should scroll right? So you can get to the bottom or top of the content?

**Comment by srirambv** [comment]
@jkup  When the window size is reduced there is horizontal shift in the position of the QA Code popup after that it starts moving independently when the main window has vertical scroll bars.

![qrcode](https://cloud.githubusercontent.com/assets/17010094/18946041/22622310-8625-11e6-8391-e497b3de70cf.gif)

**Comment by bradleyrichter** [comment]
@jkup

I think the best approach may be to restrict scrolling to the main parent window and child objects are relative to each parent. 

If the child doesn't fit, then the parent scrolls and the child moved with it. (As if the entire viewable area was a big screenshot.)

What we have now feels more like nested iframes?

**Comment by jkup** [comment]
@bradleyrichter ok I'll try that! Modals on top of modals present a lot of challenges :)

**Comment by bradleyrichter** [comment]
We may be able to use modal replacement instead of opening another. Other browsers have the same issue.  I'll try to find an example.

**Comment by jkup** [comment]
@bradleyrichter ok I'm happy to go either way, also @srirambv I'm not seeing that horizontal shift on my mac, what OS are you on there?

**Comment by srirambv** [comment]
@jkup Its on a Windows 10 machine
