### ISSUE TITLE
Drag Tab out to create a new Brave process

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#405]
A nice feature to add to Brave would be the ability to take any tab and drag it out to say a second monitor let it go and it become an independent fully functional instance of Brave.

**Comment by Tombsmen** [comment]
Also should be able to drag tabs between open instances of Brave.

**Comment by bbondy** [comment]
Related:
https://github.com/atom/electron/pull/3347

**Comment by Liunkae** [comment]
+1 from #438.

**Comment by Liunkae** [comment]
Not to be confused with #4402. This issue refers to creating a new Brave process with an existing tab.

**Comment by yannduran** [comment]
👍

**Comment by bsclifton** [comment]
@Liunkae are you sure this isn't the same as https://github.com/brave/browser-laptop/issues/4402?

Each tab should be a different process (EXE on Windows, Helper on macOS).  If so, we can close one as a dupe

cc: @bbondy

**Comment by Liunkae** [comment]
@bsclifton Yes, I think so. I'll close this as a duplicate.
