### ISSUE TITLE
Increase bookmark text size

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4050]
## Test plan

https://github.com/brave/browser-laptop/commit/6527c55caa81c4e70a222ebac9e8e961968e1ae6

----

From Support ([1](https://linkbubble.zendesk.com/agent/tickets/5500), [2](https://linkbubble.zendesk.com/agent/tickets/5489))

> Would like to increase the text size in Brave's various 'bars'. 

+1 from me

cc: @bradleyrichter 
#2324 #1937

**Comment by luixxiul** [comment]
#UIzoom

**Comment by luixxiul** [comment]
Implemented with #8419
