### ISSUE TITLE
Idle timer never stopping the ledger timer

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#4051]
Left my browser open over night. This added 7 hours to the ledger timer of the website that was left open in Brave. Apparently the idle timer isn’t triggered or is ignored.

Brave version 0.12.1dev, Fedora 24 64-bit.

**Comment by mrose17** [comment]
@bridiver - can you take a quick look at this? thanks!

**Comment by bridiver** [comment]
haven't tested it on Fedora, but I wonder if there is something else preventing the idle notification. The idle status is system-wide and not just for Brave. @mrose17 I assume he should see the timer start and stop with ledger logging enabled? It should kick in after 15 minutes of inactivity or on lock - https://developer.chrome.com/apps/idle

**Comment by mrose17** [comment]
@alexwykoff - could someone internally try to reproduce this? (i'm away from my VMs...) thanks!

**Comment by bridiver** [comment]
I can look later as well, but I need to setup a Fedora VM

**Comment by mrose17** [comment]
@Aeyoun - thanks again for reporting this. i may have found the issue. i will circle back in a bit.

**Comment by mrose17** [comment]
i'm pretty sure that https://github.com/brave/browser-laptop/pull/4186 fixes this. the idle timer is 15m.

note that a future revision may ignore the idle timer if `audioPlaybackActive: true`

**Comment by mrose17** [comment]
Fixed https://github.com/brave/browser-laptop/pull/4194
