### ISSUE TITLE
Bookmark issue

### ISSUE THREAD

**Issue by gatsb** [brave/browser-laptop#4052]
First of all I think this is much faster browser I have used so far and there are no annoying ads on pages I visit, but I am having difficulty in importing and using my bookmarks.

I have searched for a solution on your page some are pointing to the same, but I am also facing a different kind and that is after importing the html file from my other browser I can only see the folders and no bookmarks at all. The bookmarks toolbar (consisting of 15 bookmarks) I had previously added to the other browser are showing except one which is missing. If I press the folders nothing is shown and have also difficulty in deleting the new imported bookmarks, as I wanted to reimport the bookmarks in case it might help to solve my problem.

The bookmarks after import is not showing under the bookmark section, I can only get access to them if I choose Bookmark Manager which opens a new page.

I am using Win7 home premium and the laptop has no problem at all.
I have installed the latest version of Brave 0.12.1

Is there anything that can help me import my bookmarks?

Thanks in advance

**Comment by Liunkae** [comment]
This is close to being fixed with #4049.

**Comment by gatsb** [comment]
in that thread it doesn't explain how to fix it.
is it a developement job that will be added in the future update?

**Comment by bsclifton** [comment]
@gatsb the issue @Liunkae linked to is a patch which has the functionality you're wanting :smile: The work is done, it's just being reviewed.  Once it is approved and merged, we'll be able to release a fix and this issue can be updated.  Stay tuned

**Comment by Liunkae** [comment]
Fixed in #4049. This fix will be in 0.12.2, which will probably be released in a few days.
