### ISSUE TITLE
Spotify player widget doesn't work. 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4053]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Spotify player works but the widget player doesn't work. Might lead to users thinking that browser doesn't support Spotify.  Support [ticket](https://linkbubble.zendesk.com/agent/tickets/5501)

**Expected behavior:**
Should load the widget player when user clicks on a track to play
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 Dev(Clean Install)
- Steps to reproduce:
  1. Open Spotify Web player and select any artist and play track
  2. Track plays properly when flash is allowed
  3. Spotify player widget on the right side doesn't load the art work whe track is playing
  4. Play/Pause/Repeat/Shuffle button on the widget does't work
  5. Open Queue button doesnt open when queue when clicked
  6. Volume doesn't load the slider to set volume
  7. Clicking on more(...) button shows URL not found error
- Screenshot if needed:
  Console error with Shields up
  ![image](https://cloud.githubusercontent.com/assets/17010094/18582838/099aa4cc-7bff-11e6-8f99-fd9e2198674f.png)
  
  Console error with Shields down
  ![image](https://cloud.githubusercontent.com/assets/17010094/18582854/19d9b1ac-7bff-11e6-95ea-6a7a1f87a55a.png)
  
  Page not found error when more(...) is clicked in the widget
  ![image](https://cloud.githubusercontent.com/assets/17010094/18582874/33d5b826-7bff-11e6-8124-ab45511c3ffb.png)
  
  Chrome Vs Brave 
  ![image](https://cloud.githubusercontent.com/assets/17010094/18583003/02d31cc2-7c00-11e6-8d14-f3a372e1e953.png)
- Any related issues:
  #3011

cc: @diracdeltas

**Comment by lu-zero** [comment]
I confirm that it is not working on macosx with the current brave as well.

**Comment by luixxiul** [comment]
https://community.brave.com/t/spotify-web-player-not-working/9431

> I noticed that the Spotify web player is not working because of the ad blocking filters. I played a bit and found that the “audio-fa.scdn.co” filter is causing the issue. If you remove it, the player will work.

**Comment by lembitk** [comment]
This issue can probably be closed, as the Spotify web player works just fine now ([even w/o Widevine](https://github.com/brave/browser-laptop/issues/8611) :)). 

> Win 10 x64, Brave v0.23.19 (rev 178c3fb)

**Comment by bsclifton** [comment]
@lembitk thanks for confirming! 😄 If anyone encounters any problems, please re-open the issue 👍
