### ISSUE TITLE
Add funds modal - no payment icons

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4059]
**Did you search for similar issues before submitting this one?**
No.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Fedora 24

- Brave Version:
0.12.1

- Screenshot if needed:
<img src="https://s18.postimg.org/54tcd0f61/Workspace_1_012.png"/>
- Any related issues:

**Comment by bradleyrichter** [comment]
@jkup weirdness

(thanks @Sh1d0w for the alert)

**Comment by Sh1d0w** [comment]
This seems to be fixed in latest RC. Closing.
