### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token <"

### ISSUE THREAD

**Issue by rafaelcastrocouto** [brave/browser-laptop#4062]
**Describe the issue you encountered:** 
Website http://dotacard.herokuapp.com/ don't work in brave.
Console error "Uncaught SyntaxError: Unexpected token <" only in happens brave.
The site works on chrome, firefox, safari, etc. Also works in brave on a local server.
The website code is on https://github.com/rafaelcastrocouto/dotacard
I really can't tell if this is an issue on my dotacard code, heroku or brave.
Maybe it has something to do with the fact that I redirect https but that's a shot in the dark.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10

- Brave Version: Brave 0.12.1 Electron 1.3.15 Node 6.3.0

Any kind of help would be appreciated!

**Comment by bsclifton** [comment]
@rafaelcastrocouto I've seen that error before when a document is saved with unicode formatting; it puts the FEFF BOM at the beginning of the file.

As a temporary work-around, are you able to try converting the document to ASCII or UTF-8?

**Comment by rafaelcastrocouto** [comment]
I converted the html but it did not solved the issue. 

I'm converting all files now but I don't know how to do it automatically. 

I created and edited most of the files in devtools and I always thought it saved them as utf8. Is there a way to make utf8 the default encoding in devtools?

**Comment by rafaelcastrocouto** [comment]
Seems it's something about heroku since the game works fine using static files from github
http://rafaelcastrocouto.github.io/dotacard/client

Still can't tell why, but don't seem to be a dotacard encoding issue. Might have something to do with heroku's dynos and ephemeral filesystem. https://devcenter.heroku.com/articles/dynos

**Comment by bsclifton** [comment]
@rafaelcastrocouto I'll close for now, but please re-open if you have any more information :smile: Thanks for reporting and sorry for the inconvenience

**Comment by rafaelcastrocouto** [comment]
I kinda solved this and here is some info for those with similar issues.
Seems there were two main problems:

1 - CORS - Brave seem to be more restrictive about `Access-Control-Allow-Origin` policies and was blocking XHR requests. I used the '*' just to check this out and it solved most of the console error messages.

2 - HTTPS redirect - In Heroku, it's a common practice to use `request.headers['x-forwarded-proto']` to check if a request was made over 'https'.  I was redirecting all requests from 'https' to `http` and after removing the redirect everything worked fine.

Now I have to find out how to implement CORS and "http redirect" in a way that Brave will not complain.

Any help with that would be much appreciated.
