### ISSUE TITLE
Should show an option to close pinned tab

### ISSUE THREAD

**Issue by serv** [brave/browser-laptop#4063]
**Describe the issue you encountered:**
1. Pin a tab
2. Right click on the pinned tab.
3. Notice that there's no option for you to close the pinned tab

**Expected behavior:**
You should see the option to close the pinned tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Max OSX
- Brave Version:
  Brave: 0.12.1
- Steps to reproduce:
  1. Pin a tab
  2. Right click on the pinned tab in the tabs bar
  3. Notice that there's no option to close the pinned tab
- Screenshot if needed:
  Right click on unpinned tab
  ![screen shot 2016-09-16 at 1 30 54 pm](https://cloud.githubusercontent.com/assets/103456/18600313/d3a3c642-7c11-11e6-9941-d54ff5e17d3d.png)

Right click on the pinned tab
![screen shot 2016-09-16 at 1 30 48 pm](https://cloud.githubusercontent.com/assets/103456/18600314/d3a43316-7c11-11e6-871c-2bbc3cfacf65.png)

**Comment by dgennetten** [comment]
Also, this bug is worsened by the fact that you cannot unpin a tab!

**Comment by bsclifton** [comment]
@dgennetten do you have more info? You should be able to unpin it for sure

What happens if you click click on the pinned tab? (you can also try pressing Ctrl + Shift + clicking the tab)

**Comment by dgennetten** [comment]
Here's a tab with no access to close or unpin. Its an error page (which is
why I want to close!)

[image: Inline image 3]

—Douglas

**Comment by bsclifton** [comment]
@dgennetten the image you attached is not working :frowning_face: 

Are you able to log into GitHub.com and submit? I think it failed because you replied to the issue via email

**Comment by bryanj4** [comment]
I have the same issue on Windows 10. I am able to close other pinned tabs by unpinning them then closing them but I the error page pinned tab always comes back. Very annoying! 

Would have the error link be a good way to debug the issue?

**Comment by bryanj4** [comment]
Alright I fixed my issue by going into the `C:\User\ENTER_USERNAME\AppData/Roaming/brave/session-store-1` and removing the searching for the url that it would error on and finding whether the object had a property of `"tags": ["pinned"],...` included and if it did I deleted that entry. 

I found someone solved something similar in the Chrome google group [here](https://productforums.google.com/forum/#!topic/chrome/87RgMd0S7UE)

**Comment by bsclifton** [comment]
+1 from user who DMed me
>  Pinned tabs can't be closed. Can't middle click close, can't right click close, no X, etc. Can't be closed at all.

**Comment by jeffslofish** [comment]
I have investigated this issue and I did a preliminary implementation of being able to close tabs. However, it raises several issues:

1. Should "Close other tabs" or "Close tabs to the right" etc close pinned tabs?
1. What should happen if you close a pinned tab then choose to "Reopen last closed tab": should it open up pinned or unpinned?
1. Currently (with my naive implementation, if you close a pinned tab then close the window and reopen the window, the pinned tabs that you had closed will reappear. I am assuming this is not the desired behavior?

Can someone please guide me as far as how these things should work? Thanks!

**Comment by bsclifton** [comment]
@jeffslofish those are some great questions-  here's my take on it:

1. Close other tabs (and variations like "to the right") shouldn't affect pinned tabs
2. Reopen last closed tab should reopen the last closed tab (pinned or unpinned). When it opens, I don't think it should be pinned though
3. If you close the pinned tab, it should be saving this for all windows (which is a different bug altogether 😛 ). It may not reflect the tab being removed in other windows immediately, but if you create a new window OR close/reopen an existing window, that should trigger a re-render.  In that situation you are correct, I would expect to not see this tab (which was just closed)

cc: @bbondy and @bradleyrichter for visibility

**Comment by bradleyrichter** [comment]
@cezaraugusto We need to add this option very soon.  

Right-click on a pinned tab.
Choose "Close".
Pinned tab closes.

**Comment by bbondy** [comment]
@bradleyrichter what's the urgency for this vs other bugs? Pinned tabs are only used by a small percentage of users.  Getting rid of a pinned tab is a percentage of that.  There's a simple work-around to unpin and then close.  I understand it's better for UX but I don't think it should be uplifted or prioritized.

**Comment by bradleyrichter** [comment]
@bbondy I'm hearing about this a lot recently. People can't seem to find the work around easily enough. 

@alexwykoff - do you have any ideas about frequency?

**Comment by bbondy** [comment]
ok I put in 0.21.x but Michael is going to start doing triage meetings for completed things that we want to pull up higher.  Mainly we want nothing in beta and developer channel unless it's a newly introduced bug or critical blocking bug. And then pick what to uplift from completed ones.

**Comment by alexwykoff** [comment]
We don't have systems in place to measure this quantitatively yet, but out of the users who try pinned tabs, a vocal minority find it a considerable pain to two-step the removal.

**Comment by luixxiul** [comment]
The option itself is displayed but it seems to me it does not work. See: #11805.
