### ISSUE TITLE
Swipe gestures are very touchy and require a very fast movement

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4064]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to use the swipe controls on a MacBookPro, I found it required an extraordinary amount of speed and dexterity.   https://linkbubble.zendesk.com/agent/tickets/5306 agrees.

**Expected behavior:**
The swipe controls should require a reasonable amount of speed (slow to medium) and provide a visual indicator of registering the swipe toward a goal of navigating forward or backward.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X, likely an issue for all.

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Visit a bunch of sites.
    2. Attempt to swipe left or right on the trackpad using 2 fingers (make sure the gesture is set on the system level)

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/2345

**Comment by Liunkae** [comment]
Related issue: #2477.
