### ISSUE TITLE
Feature Request : Setting to block all images by default 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4065]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Requested by https://linkbubble.zendesk.com/agent/tickets/5300 . They would like to block all images by default. This also makes sense for users who are visually impaired and are trying to use Brave with a screen reader.

**Expected behavior:**
If the user toggles a setting to block images, all images will be blocked thereafter.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  
  > 0.12.2

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/5433

**Comment by Liunkae** [comment]
+1 from https://github.com/brave/browser-laptop/issues/4442#issuecomment-264718695.

**Comment by Liunkae** [comment]
+1 from #10638

**Comment by Liunkae** [comment]
Related: #6875 (block third-party images)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/image-blocker-for-metered-low-bandwidth-connections/7028?u=eljuno

**Comment by Liunkae** [comment]
This is implemented in Content Settings in brave-core:
![](https://user-images.githubusercontent.com/19424103/45311300-49501000-b4ee-11e8-88a8-c91bc0a30e62.png)

**Comment by bsclifton** [comment]
@Liunkae awesome! Thanks for sharing that this is possible (and where it is) 😄 👍
