### ISSUE TITLE
On browser startup, Preferences > Payments briefly shows off/disabled view

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#4066]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**

When the last active tab was Preferences > Payments and you restart the browser, the Payments page briefly in the Payments off state even with Payments on.

Mentioned in https://github.com/brave/browser-laptop/issues/3781#issuecomment-247658679

**Expected behavior:**

Payments page should always accurately reflect Payments on/off status.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Mac OS
- Brave Version:
  0.12.1
- Steps to reproduce:
  1. Enable Payments
  2. Open 10 tabs of stuff
  3. Open Preferences > Payments
  4. Restart browser
  5. Browser reloads Payments page in the off state

**Comment by diracdeltas** [comment]
i suspect this is a general problem with `about:preferences` not receiving the IPC messages that contain settings fast enough

**Comment by bsclifton** [comment]
@ayumi this may be fixed now... would you be able to retest? 😄

**Comment by bsclifton** [comment]
moving to 0.14.2

**Comment by bsclifton** [comment]
moving to 1.0

**Comment by zentagonist** [comment]
QA to retest after 0.20.x
