### ISSUE TITLE
Open in new tab context menu item should go to the top 

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#407]
Open in new tab in the context menu should ideally be at the top the context menu, rather than some where in the middle. Opening a link in a new tab should be a 1.18 of a second two click express process, as the other option Ctrl click requires two hands, may cause issues with those with one hand.

**Comment by bradleyrichter** [comment]
Thanks for the submission. We will be sure to take the best from the Chrome/Firefox context menus and implement your first-item suggestion for efficient access to "Open link in new tab".

**Comment by bbondy** [comment]
I think the ordering is right as suggested, will tweak in this issue.
