### ISSUE TITLE
Create a page thumbnail grabber and database for loaded pages

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4070]
As a new alternative to the current approach to previewing tabs, we will capture and store large page thumbnails that can become the replacement. This will reduce the need to spawn more browser processes in certain places, and will be useful for the top-sites previewing in the NTP. (new tab page)

The suggested plan is to capture a snapshot of the page when it finishes loading. Only the top left 1000x700 pixels will be stored. 

When displayed for tab previews and NTP top-site previews, the thumb will be masked on an angle using CSS opacity. This should eliminate a problem where the window size effects the dynamic page elements, or for narrow page designs that 

examples: 

corner peek for tab hover preview:
![image](https://cloud.githubusercontent.com/assets/13509546/18603783/4c83078c-7c29-11e6-951f-118af9560391.png)

corner peek for top-site preview in NTP:
![image](https://cloud.githubusercontent.com/assets/13509546/18603787/51d7086e-7c29-11e6-92c7-b176fea0b2ed.png)

There are some issues to be resolved. One is how to take the snapshot when the browser page is smaller than 1000x700. It may need to render off screen from loaded content for each page.

**Comment by lucidNTR** [comment]
@bradleyrichter the problem with this approach is that pages seem to jump when the 1000x700 preview is replaced by the actual rendering that is based on the current window size and the reflow happens . the experience feels a bit broken this way.i  made a tab preview that is slightly modal and zooms in when the tab is selected. this way as a side effect we can preview the tabs title and the jumping effect is not as noticable.

<img width="1253" alt="screenshot 2016-10-05 00 22 38" src="https://cloud.githubusercontent.com/assets/1176068/19094706/e41982c6-8a91-11e6-9b56-2c33d5b68094.png">

**Comment by bradleyrichter** [comment]
I'll have to prototype it. I can visualize the problem but I am not sure if the margin'd version is much better. 

Also, we could perhaps mix this with current tab previews which would reduce the amount of jumping.

**Comment by lucidNTR** [comment]
@bradleyrichter can you send me a link to your test branch when you prototyped it? if i manage to do it before you i will post links to my prototype branches here too...

**Comment by bradleyrichter** [comment]
@lucidNTR I won't have time this week. 

The idea with mixing is to only show the cached thumbnail if the tab is NOT loaded. If it is loaded, then show it like we do today, or with an additional blend to make the styles similar. 

This needs more thought but it might work well.

**Comment by bradleyrichter** [comment]
@bbondy Do you like this idea?  ^^

**Comment by lucidNTR** [comment]
ok i will prototype this behaviour and put the links here
