### ISSUE TITLE
Compact autocomplete pulldown on URL bar 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4073]
**Describe the issue you encountered:** I'd like to see more favorite/history URLs than two. It could be implemented with a compact mode, which should be optional. Here's a rough idea: 

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18605053/89586e7e-7cc2-11e6-84df-c9be9caf2ec9.png)
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.1
- Any related issues:

**Comment by zoof** [comment]
Moreover, the algorithm for selecting links should put less weight on recent sites.  I've noticed that for pages I go to all the time, if I click on just one link, it supercedes the root site all the time.
