### ISSUE TITLE
The current update being pushed is causing the return button to disable when going to a web page. Also disables media comment interaction disabling the ability to log to discus, google, etc.

### ISSUE THREAD

**Issue by liston3** [brave/browser-laptop#4078]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
@liston3 do you have an example that we can reproduce? What URL were you visiting? Any info is appreciated :smile:

**Comment by luixxiul** [comment]
Closing due to lack of information. Let's keep discussion if you experience the issue, thanks.
