### ISSUE TITLE
Window.onbeforeunload not working in Brave

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4079]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Create a webpage with the following js :

```
window.onbeforeunload = function(e) {
  var dialogText = 'Dialog text here';
  e.returnValue = dialogText;
  return dialogText;
};
```

If you try to navigate you are stuck in the page with no alert or nothing. In FF and Chrome it works ok, giving you an alert according to https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

Note that the following code does not work on jsfiddle for some reason it has to be on a regular web page.

**Expected behavior:**

Brave should show an alert.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.1
- Steps to reproduce:
  1. Open https://jsfiddle.net/L5grdj3a/
  2. Close the window
  3. You don't get alert as you should.

**Comment by willy-b** [comment]
FYI, not getting an alert from this jsfiddle in Firefox (47)  either.

**Comment by Sh1d0w** [comment]
@willy-b Hm, you are right. Strage, but it works only in Chrome, despite:

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

http://www.w3schools.com/jsref/event_onbeforeunload.asp

Will leave this open for now, if someone from Brave team decide this is not a problem, feel free to close it.

**Comment by Sh1d0w** [comment]
Edit: If you execute the following example code in FF and Chrome it will work:

```
window.onbeforeunload = function(e) {
  var dialogText = 'Dialog text here';
  e.returnValue = dialogText;
  return dialogText;
};
```
Brave does not seem to work if you execite this code in the console.

**Comment by bridiver** [comment]
looks like we need to handle `BeforeUnloadFired` in electron

**Comment by Sh1d0w** [comment]
@bridiver  Can you set a milestone for this issue, because all websites that take advantage of this callback function in order the user to confirm their navigation, are simply unusable since you can't navigate out of the page?

**Comment by bridiver** [comment]
this does seem like a pretty serious issue. I also noticed that the urlbar displays any domain you attempt to navigate to as if it was the current url which makes this a potential attack vector for urlbar spoofing @diracdeltas

**Comment by bridiver** [comment]
actually I think it might be the result of a patch that electron applies to chromium
```
@@ -4652,6 +4659,7 @@ void WebContentsImpl::RendererUnresponsive(
   // We might have been waiting for both beforeunload and unload ACK.
   // Check if tab is to be unloaded first.
   if (rfhi->IsWaitingForUnloadACK()) {
+#if 0
     // Hang occurred while firing the unload handler.
     // Pretend the handler fired so tab closing continues as if it had.
     GetRenderViewHost()->set_sudden_termination_allowed(true);
@@ -4663,6 +4671,7 @@ void WebContentsImpl::RendererUnresponsive(
     // to recover. Pretend the unload listeners have all fired and close
     // the tab.
     Close();
+#endif
     return;
   }
```

**Comment by diracdeltas** [comment]
@darkdh would you mind looking at this?

**Comment by darkdh** [comment]
sure, no problem

**Comment by bridiver** [comment]
@darkdh I haven't test it yet, but I have a potential fix in the chromium54 branch
```
void WebContents::BeforeUnloadFired(content::WebContents* tab,
                                    bool proceed,
                                    bool* proceed_to_fire_unload) {
  if (type_ == BROWSER_WINDOW)
    *proceed_to_fire_unload = proceed;
  else
    *proceed_to_fire_unload = true;
}
```

**Comment by darkdh** [comment]
fixed by https://github.com/brave/electron/commit/5f8f5a91cfd806559d6f0432ce51c0ba04a53156

**Comment by luixxiul** [comment]
Test plan:

Open https://jsfiddle.net/L5grdj3a/
Close the window
Get alerted

**Comment by luixxiul** [comment]
Please update it to a correct one if it's wrong, thanks
