### ISSUE TITLE
Add funds from Brazil

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4084]
Hi, 

i'm from Brazil and when adding funds, appear the link of cubits service, but this service is not directed to brazilians.
I think the best site to show for brazilian people is http://biscoint.io. With this service you add a fiat price and then is listed the best price of all brazilian exchangers, including fees.

**Comment by mrose17** [comment]
thanks... i'll do some research and let you know!

**Comment by mrose17** [comment]
hmmm... i asked someone from brazil to try signing up with them, and even though the person had never heard of http://biscoint.io, it claims that they already have an account. i suspect that their user registration/login/lost-password process has gone sideways. they are being contacted...

**Comment by bitcoinuser** [comment]
It's not necessary to create an account to use https://biscoint.io. The service is just: you insert the total of bitcoins you want to buy, and they list the better final price in all brazilian exchanges.

**Comment by luixxiul** [comment]
So you cannot buy bitcoins on the site

**Comment by bitcoinuser** [comment]
@luixxiul Yes, you can NOT buy bitcoins on the site. The site just list the best price/exchange to sell or buy bitcoins at real time.

**Comment by mrose17** [comment]
thanks for the clarification. sorry for the misunderstanding. if there is a site operating in BR that is better for Brazilians than what we're currently using, please let us know!

best,

/mtr

**Comment by bitcoinuser** [comment]
Hi @mrose17 

I think https://biscoint.io/bitcoin/price-comparison/buy/single-exchange is a perfect solution.

See: You can specify a value and the site will list the best place to buy or sell bitcoins in real time. On top right you can see that it's working for Brazil, Canada, Euro and USA. You can choose the language too, English or Brazilian. 

Please test it. Don't you think it's a great?

**Comment by bitcoinuser** [comment]
See this video to understand how biscoint.io works: https://www.youtube.com/watch?v=l26gavcavPE&feature=youtu.be
