### ISSUE TITLE
Can not remove entries from Brave Payments list

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#4086]
**Did you search for similar issues before submitting this one?** Yes.

**Describe the issue you encountered:** You can not entirely remove an entry from the Brave Payments section, just turn it off. Even after deleting all associated entries from the brower history, the domain remains present in the Brave Payments. 

This could be considered a privacy problem as it prevents people removing history of their actions from the browser profile selectively.

This issue is, of course, not a problem if private tabs are used.

**Expected behavior:** Either entries on the Brave Payments section could be manually removable (perhaps a deletion 'X' appears next to disabled entries?) or they could be automatically removed if all history items for the related domain are deleted.

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Linux, but I am assuming it is a platform independant issue.

- Brave Version: 0.12.1

- Steps to reproduce:
    1. Open 'Settings' from the hamburger meny.
    2. Click 'Payments'
    3. Note the inability to selectively remove entries from the list.

**Comment by mrose17** [comment]
i'm pretty sure that the functionality in question is arring in 0.12.3 ... it's in the `master` branch now, but we haven't spun up a release yet!

**Comment by luixxiul** [comment]
Note: the issue has been fixed with #4118
