### ISSUE TITLE
Bookmark import from Firefox crash

### ISSUE THREAD

**Issue by hmrodrigues** [brave/browser-laptop#4087]
After I import bookmarks from Firefox, when I try to close a tab the app crashes, even after re-open. I solved by deleting the folder in ~/.config and adding bookmarks by hand.

- Platform: Arch Linux (brave-bin from aur)

- Brave Version: 0.12.1

- Steps to reproduce:
    1. Import bookmarks from Firefox
    2. Close a tab (In my case the preferences tab)

**Comment by darkdh** [comment]
This will be fixed by #2107
https://github.com/brave/browser-laptop/issues/2107#issuecomment-246420679
