### ISSUE TITLE
Brave closes/crashes upon clicking links

### ISSUE THREAD

**Issue by stpetric** [brave/browser-laptop#4088]
- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10 (version 1607)
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Click on a hyperlink (some but not all)
  2. Brave _immediately_ closes
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Would you please give a URL for example to confirm the bug?

**Comment by luixxiul** [comment]
The issue is thought to have been fixed. If not, please leave a comment. thanks.
