### ISSUE TITLE
Crash on closing a tab or adding bookmark or clearing browsing history

### ISSUE THREAD

**Issue by mitzip** [brave/browser-laptop#4089]
**Did you search for similar issues before submitting this one?**
Yes, found another user with a new ticket for crashes when clicking on hyperlinks. This is not happening to me as far as I can tell.

**Describe the issue you encountered:**
Closing a tab or adding a bookmark causes Brave to crash. Brave will start back up as if nothing ever happened, so I can never close any of the 22 tabs I now have open.

**Expected behavior:**
the tab to close or bookmark to be added.

- Platform (Win7, 8, 10? macOS? Linux distro?):
ubuntu 15.10

- Brave Version:
Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

- Steps to reproduce:
    1. Open Brave
    2. Close a tab
    3. Crash

- Screenshot if needed:

- Any related issues:
Thinking of some things that coincidently happened around the same time... Before I started adding bookmarks I didn't have this issue. I had payments working and bitcoin added to the wallet for a good while and everything worked fine. Seemingly started right after visiting http://arstechnica.com/gadgets/2016/09/the-router-rumble-ars-diy-build-faces-better-tests-tougher-competition/ and then opening trueos.org started crashing Brave intermittently (it didn't before) and then I started noticing I couldn't bookmark or close tabs. UPDATE: Clearing browsing data also crashes Brave

**Comment by mitzip** [comment]
I deleted all my bookmarks from my session json file and I can close tabs again

**Comment by hudon** [comment]
I get crashes when closing tabs as well, but not all the time. Maybe 1 out of 10 times I close a tab, the browser crashes. This did not happen before I upgraded Brave.

OS: Mac OSX 10.11.6
Brave version:
Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

**Comment by bryanj4** [comment]
I get crashes on everytime I try to close a tab after I upgraded Brave.

OS: Arch Linux
Brave version: 0.12.1-1
Node.js: 6.3.0
Everything is up to date on my machine however I don't know where you get the versioning for Electron, V8 or libchromiumcontent.

**Comment by CliqueBait** [comment]
@bryanj4 I have the same problem. I've downgraded back to v0.12.0 until the next release which will hopefully fix it.

Ubuntu 16.04.1 LTS
Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

(from Help | About Brave)

**Comment by ayumi** [comment]
I think I've been running into the same problem, starting 1–2 weeks ago.

@mitzip I tried your suggestion and  deleted all my 100 bookmarks and bookmark folders and haven't had a crash since!
As a side effect the browser feels much snappier when switching tabs.

I'll try to look into this.

**Comment by ayumi** [comment]
I think it's happening in electron. here's info from LLDB when it crashes:

```c++
* thread #1: tid = 0x433f54, 0x0000000103318e6a Brave Framework`atom::api::Menu::MenuDestroyed(this=0x00007f91d36efab0) + 106 at atom_api_menu.cc:161, name = 'CrBrowserMain', qu
eue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000103318e6a Brave Framework`atom::api::Menu::MenuDestroyed(this=0x00007f91d36efab0) + 106 at atom_api_menu.cc:161
   158  }
   159
   160  void Menu::MenuDestroyed() {
-> 161    FOR_EACH_OBSERVER(MenuObserver, observers_, MenuDestroyed());
   162    if (!is_destroyed_) {
   163      base::MessageLoop::current()->PostTask(FROM_HERE, GetDestroyClosure());
   164    }
```

@bridiver has an idea how to fix it (thanks for your help!)

**Comment by ayumi** [comment]
@mitzip @hudon @bryanj4 @CliqueBait

We've added [a fix](https://github.com/brave/electron/commit/d9cf59b3ddaa1f5695b15e14a6afe6a82517b7c6) to 0.12.3 which has resolved my tab close crashes.
Could you try [0.12.3](https://github.com/brave/browser-laptop/releases/tag/v0.12.3dev) and let me know how it goes?

**Comment by bryanj4** [comment]
@ayumi Hey cool kid. The fix worked for me. Thanks for solution. I run on ArchLinux so I got the fix asap

**Comment by hudon** [comment]
I've been using it all day, this is resolved for me as far as I can tell. I see "double click to resize window" is working too on macOS. sweet! Thanks
