### ISSUE TITLE
Netflix doesn't allow video playback (Pluggin related) Netflix Error M7701-1003

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#409]
Likely due to Silver Light / Wildvine plugin support.

https://help.netflix.com/en/node/27451

![netflix_error_m7701-1003](https://cloud.githubusercontent.com/assets/16950007/12666876/05105b26-c602-11e5-8335-fa2d78acc960.PNG)

**Comment by bbondy** [comment]
Duping to #468
