### ISSUE TITLE
Attempting to load an URL resulted in too many redirects.

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#4091]
![untitled](https://cloud.githubusercontent.com/assets/19530450/18613686/4c835ac6-7d5e-11e6-9408-650b79fe76e1.jpg)

**Comment by luixxiul** [comment]
"Attempting to load an URL resulted in too many redirects" is not the error of the browser. It tells you that their server is not properly configured. You can load the page.

**Comment by mati865** [comment]
I agree it's the server error but Firefox is able to handle this.
Maybe some kind of workaround could be created?
