### ISSUE TITLE
Browser crashes when moving between multiple open tabs

### ISSUE THREAD

**Issue by JamesJar** [brave/browser-laptop#4094]
**Did you search for similar issues before submitting this one?**Yes

**Describe the issue you encountered:** When moving between tabs (I have 22 open) the browser crashes spontaneously. When I restart, all tabs are gone and must be reopened - which results in repeat crash

**Expected behavior:** To not crash
- Platform (Win7, 8, 10? macOS? Linux distro?): Mac OS 10.11.6
- Brave Version: 0.12.1
- Steps to reproduce:
  1. open multiple tabs
  2. close or jump between tabs
  3. crash
- Screenshot if needed:
- Any related issues: It will also happen with only two or three tabs open

**Comment by Dmeyer96** [comment]
Interesting, can't seem to recreate this while on Win10, or any of my Linux VM's, 

Potentially a memory-leak issue?

**Comment by CliqueBait** [comment]
I get this crash too frequently to be able to use the latest Brave release. It's intermittent for me and don't see how one might reproduce it reliably.

Ubuntu 16.04.1 LTS
Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev
