### ISSUE TITLE
Fido.ca displaying incorrectly

### ISSUE THREAD

**Issue by sirolf2009** [brave/browser-laptop#4095]
Fido.ca login page is supposed to have an overlay panel where you can enter you credentials. Brave doesn't show this overlay panel. I tried this on both linux and windows with the latest brave version.

Link: https://www.fido.ca/pages/#/login?m=login

Screenshot from Brave browser
![screenshot from 2016-09-18 11 50 30](https://cloud.githubusercontent.com/assets/3534736/18617131/b960585a-7d96-11e6-9885-f78351c47c21.png)

Screenshot from Google Chrome:
![screenshot from 2016-09-18 11 55 19](https://cloud.githubusercontent.com/assets/3534736/18617136/d6f038c2-7d96-11e6-9253-b6eb5007eca2.png)

**Comment by luixxiul** [comment]
For me the modal dialog is correctly displayed. Maybe it was fixed some time ago 😉
