### ISSUE TITLE
Please add F5 and CTRL+F5 as soft/hard reload options on Windows

### ISSUE THREAD

**Issue by scunliffe** [brave/browser-laptop#410]
Web users and developers are extremely used to using F5 and CTRL+F5 for soft and hard reloads in all browsers on Windows. If these key combos could also be mapped to these features it would make user migration much easier. (*cough* F12 for developer console too *cough*)

**Comment by bbondy** [comment]
Cheers! It'll be in the next version.

**Comment by scunliffe** [comment]
You rock! I've never had a browser vendor react so fast!
