### ISSUE TITLE
HTTPS everywhere unexpectedly blocks content

### ISSUE THREAD

**Issue by liamosaur** [brave/browser-laptop#4103]
**Describe the issue you encountered:**
Scenario: Site is plain HTTP, contains a block where a script source is defined as:
`<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>`
An example URL is http://www.news.com.au/entertainment/bill-murray-tended-bar-at-his-sons-restaurant-and-killed-it/news-story/51b872aba53e2074231296cbfbc6add9
Note that platform.instagram.com/en_US/embeds.js is available via both HTTP and HTTPS.
**Expected behavior:**
Either the plain HTTP or HTTPS version of the script is loaded. This is the default behaviour for the HTTPS Everywhere plugin on Chrome, however using Brave, the script seems to be blocked.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X
- Brave Version:
  0.12.1
- Steps to reproduce:
  See above
- Screenshot if needed:
  ![screen shot 2016-09-19 at 12 10 02 pm](https://cloud.githubusercontent.com/assets/2960928/18621115/2d6ced14-7e62-11e6-8ff5-56b01e15bb8f.png)

**Comment by luixxiul** [comment]
it has been fixed.
