### ISSUE TITLE
Unable to close popover div element on Patient.info site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4107]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to close popover div element on Patient.info site

**Expected behavior:**
Should be able to close the popover div element 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.1 Dev (Clean Install)
Shields down

- Steps to reproduce:
    1. Open any article on http://patient.info/
    2. Click on the Facebook share button next to the article
    3. Popover div is loaded when clicked, Unable to click on the No thanks href to close the popover div

- Screenshot if needed:
Console error (Shields down)
![image](https://cloud.githubusercontent.com/assets/17010094/18627478/011240ac-7e53-11e6-8ef0-e2a68f837d75.png)

 Brave vs Chrome
 ![image](https://cloud.githubusercontent.com/assets/17010094/18627518/45647e8c-7e53-11e6-828b-68007462f421.png)

- Any related issues:

**Comment by jonathansampson** [comment]
Issue appears to repro in Google Chrome too. Both Chrome and Brave will show the floating element on top of the content *when you're scrolled to the top*. If you scroll down beyond the top of the article container, both Google Chrome and Brave will add a `fixed-active` class, which causes the element to be rendered beneath the text (making it hard to click).

@srirambv Can you confirm?

**Comment by srirambv** [comment]
@jonathansampson There is a difference this time around on the floating element. Now the behavior is exactly like on Chrome. I am able to click the _No Thanks_ anywhere on the article no need to scroll down to the comments section as well. The first time around I was not even able to click on _No Thanks_ even when it was at the comments section. The floating element was just overlapping on the article but did nothing.(There's a clear difference in screenshots). Works fine even with Shields Up

**Comment by jonathansampson** [comment]
@srirambv  I assumed the difference between the screenshots was because you were scrolled to different locations (since some locations create the issue, while other locations resolve the issue).

So, Chrome and Brave are now behaving in the same way? No more discrepancy?

**Comment by srirambv** [comment]
Yup seems to be same behavior on Chrome and Brave. Closing the issue.
