### ISSUE TITLE
HTTPS Everywhere blocks videos on Petmd.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4109]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
HTTPS Everywhere blocks videos on Petmd.com

**Expected behavior:**
Should load flash video
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 Dev
- Steps to reproduce:
  1. Open any article with video in it on http://www.petmd.com/
  2. Clicking on allow flash to run shows the video loading icon
  3. Only after disabling HTTPS Everywhere the video loads
  4. Social Media buttons above the video are not loaded
- Screenshot if needed:
  Chrome:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18630861/c706e0f2-7e66-11e6-8f16-e3341e488641.png)
  
  Brave 
  ![petmd](https://cloud.githubusercontent.com/assets/17010094/18630678/0e9b8dce-7e66-11e6-8a63-2418d7e11f51.gif)
  
  Console Error 
  ![image](https://cloud.githubusercontent.com/assets/17010094/18631357/5e11efa8-7e69-11e6-9231-68b46307d5db.png)
- Any related issues:

**Comment by diracdeltas** [comment]
http://www.petmd.com/dog/emergency/common-emergencies/e_dg_vomiting now works with https everywhere
