### ISSUE TITLE
Feature Request : Profanity filter

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4112]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
https://linkbubble.zendesk.com/agent/tickets/5414 has requested a profanity filter.

**Expected behavior:**
The user should be able to turn on a profanity filter and have those words removed from the view.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  
  > 0.12.2

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/feature-request-profanity-filter/10179

Let's reopen if we have an idea how to implement this 😄
