### ISSUE TITLE
Query wallet balance less

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#4114]
**Issue (🎁):**
When Payments is enabled and a user wallet active, Brave queries a Bitcoin API for the wallet balance every minute.
This could be undesirable because APIs might know when browser users are online.
It is also additional load, and if we run our own blockchain API it could be intense.

**Expected (📦):**
Query balance only when necessary:
- Payments pane is open
- After reconciliation when balance drops below next reconciliation amount (? something like this)

Platform (Win7, 8, 10? macOS? Linux distro?):
all

Brave Version:
0.12.1

Steps to reproduce:
    1. In `ledger.js` line ~1062 add logging to `ledgerBalance.getBalance`
    2. Enable Payments and ensure a user wallet exists
    3. Log output shows periodic function calls

cc @bridiver @diracdeltas @mrose17

**Comment by mrose17** [comment]
@ayumi - bonus points if you can figure out which one of the *.options.*P variables should be used to enable the call to `console.log`

**Comment by bridiver** [comment]
you can get the info you need from `WindowConstants.WINDOW_SET_FOCUSED_FRAME` and check for the about:prefs page with the ledger anchor

**Comment by willy-b** [comment]
@ayumi , if you run with the env variable LEDGER_VERBOSE set to true (`LEDGER_VERBOSE=true npm start`) @mrose17 has extensive logging in place (as he is alluding to, I think).
