### ISSUE TITLE
new icons for desktop app releases

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4120]
Here are the new icons in preparation for our 1.0 release. These include the new logo updates with more ear and more nose, plus some subtle depth-shading.

![image](https://cloud.githubusercontent.com/assets/13509546/19502663/63000282-9563-11e6-888e-5eb3d5df4354.png)

4 icons each in ICNS and ICO formats for Mac and Win

The icons progress from Nightly - to - Dev - to - Beta - to - Release with progressively more orange coloration.

[installer_icons.zip](https://github.com/brave/browser-laptop/files/537765/installer_icons.zip)
[brave_app_icons_nightly.zip](https://github.com/brave/browser-laptop/files/537753/brave_app_icons_nightly.zip)
[brave_app_icons_dev.zip](https://github.com/brave/browser-laptop/files/537754/brave_app_icons_dev.zip)
[brave_app_icons_beta.zip](https://github.com/brave/browser-laptop/files/537755/brave_app_icons_beta.zip)
[brave_app_icons_release.zip](https://github.com/brave/browser-laptop/files/537756/brave_app_icons_release.zip)

(PNG 512x files for Linux)

**Comment by Sh1d0w** [comment]
@bradleyrichter as per https://github.com/brave/browser-laptop/issues/3229 can you please provide SVG icons for Linux as well :)

**Comment by bradleyrichter** [comment]
Per @Sh1d0w  - I attached a set of 512x PNGs above.

**Comment by srirambv** [comment]
brave_icon_release_mac looks to be on a darker shade than the other two. Easily noticeable when you open the above image in a mobile.

**Comment by bradleyrichter** [comment]
Thank you for noticing. It seems to be caused by a render bug in OS 10 finder for icns files. The color becomes correct when the icon is bound with the app.

**Comment by bbondy** [comment]
@bradleyrichter  we also need these updates:
![start-tile-70](https://cloud.githubusercontent.com/assets/831718/19481470/0d7398fc-951c-11e6-8d33-4a4e358b6169.png)
![start-tile-150](https://cloud.githubusercontent.com/assets/831718/19481471/0d738ed4-951c-11e6-9974-20ae881630bb.png)

**Comment by bbondy** [comment]
Also does brave_installer.icns need an update?

**Comment by bradleyrichter** [comment]
yes, yes and yes.

**Comment by bbondy** [comment]
ok please update the original message and then ping here when done, thanks!

**Comment by bradleyrichter** [comment]
new start-tile icons for Win 8/10

[brave_starttile_icons.zip](https://github.com/brave/browser-laptop/files/537410/brave_starttile_icons.zip)




@bsclifton ^

**Comment by bradleyrichter** [comment]
[brave_installer_icon.zip](https://github.com/brave/browser-laptop/files/537472/brave_installer_icon.zip)

@bbondy ^^
