### ISSUE TITLE
synopsis entry should show up in < 8s for tests

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4122]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
when `process.env.NODE_ENV === 'test'` and a page is visited, it takes 8 seconds for a page to be registered in the ledger, which makes it impossible to test because the test timeout is less than 8s. i thought this was fixed by e47c28bf91ddbe0ec117c4a20374b08d0faa51a3 but apparently not.

to repro:
1. mkdir  ~/.brave-test-ledger
2. NODE_ENV=test npm start
3. open the payments panel, visit any site, observe that it takes at least 8s for it to appear in the synopsis table

**Comment by mrose17** [comment]
@diracdeltas - still looking into this, but. if you do `NODE_ENV=test ...`, then everything in the browser EXCEPT the ledger file are in `~/Application\ Support/brave-test/` -- but the ledger files are looked for in `~/.brave-test-ledger/`, but that directory is never created automatically. i'm going to address that in the PR associated with this issue.

**Comment by diracdeltas** [comment]
@mrose17 the testing framework doesn't know where appData is so it has to use `~/`. the directory is made automatically by the test setup script, so make sure to change test/lib/brave.js accordingly if you make any changes.

**Comment by mrose17** [comment]
uh, then why does everything else go to `~/Application\ Support/brave-test/` -- having two directories for this is non-sensical. let me see if i can find where we are going off the rails on this...
