### ISSUE TITLE
Enabling HTTPSEverywhere doesn't load section previews on Vice.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4125]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling HTTPSEverywhere doesn't load section previews on Vice.com. 

**Expected behavior:**
Should load section previews
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 Dev
- Steps to reproduce:
  1. Visit http://www.vice.com
  2. Hover over different sections to bring down the section contents 
  3. Section content preview not shown. Only empty divs 
  4. Disable HTTPS Everywhere, All section content previews are loaded.
- Screenshot if needed:
  ![vice](https://cloud.githubusercontent.com/assets/17010094/18666147/279e8f1c-7f22-11e6-9179-b62d9fb347f5.gif)
- Any related issues:

**Comment by diracdeltas** [comment]
seems that Vice has fixed the issue
