### ISSUE TITLE
Block 3P Cookie doesn't allow user to select content provider

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4129]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Block 3P Cookie doesn't allow user to select content provider when live play is clicked

**Expected behavior:**
Should allow to select content provider when the live play is clicked 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.1 Dev
- Steps to reproduce:
  1. Visit http://watch.hgtv.com/live.html?ic1=tve_utility with Block 3PC enabled
  2. Click on the Live tv play icon, doesn't load the providers option popover  to select
  3. Change from Block 3PC to Allow all cookies, popover selection window appears
- Screenshot if needed:
  ![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17010094/18675547/9844f6ac-7f4a-11e6-9de6-fa44da1d1bbb.gif)
  
  Console Error 
  ![image](https://cloud.githubusercontent.com/assets/17010094/18675028/fb357252-7f48-11e6-9efc-88000997f1a1.png)
- Any related issues:

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
