### ISSUE TITLE
LastPass details are not saved across reboot/session

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4131]
From Support [ticket](https://linkbubble.zendesk.com/agent/tickets/5341)

> I am having issues with lastpass for a while. It will not give me a login. My settings under preferences/security don't stay. If I save the preferences and restart the browser it works. But with the next rebooot, all is lost again.
> 
> It doesn't seem to be any better, maybe worse. Before if I started the browser and saved my preferences I could restart the browser and it would work until the next reboot. Now if I save my preferences and restart the browser the preferences are gone and it still won't work.

Unable to repro the issue with 0.12.1 or 0.12.0

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/5055
