### ISSUE TITLE
ledger state files no longer need suffixes

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4132]
now that test, development, and production have separate appData folders, there's no need for `-development` / `-test` ledger JSON files.

ex: my dev files are now in `~/Library/Application Support/brave-development`

**Comment by luixxiul** [comment]
Will you please specify QA steps on Windows? Thanks!

**Comment by diracdeltas** [comment]
@luixxiul QA steps in https://github.com/brave/browser-laptop/commit/c6714a07cbfd353363e266d3a16d2921d6196532

**Comment by luixxiul** [comment]
How to start brave in dev mode on Windows?

**Comment by diracdeltas** [comment]
@luixxiul no need to do the dev mode step for RC builds
