### ISSUE TITLE
Dashlane is not working on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4138]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I have Dashlane installed and configured and used preferences to set Dashlane as the active password manager. The icon shows in the top right, but is not clickable. I can't find a way to get Brave to open Dashlane

Strange enough, if I hit Ctrl + \, 1Password pops up (which was enabled prior to this- I'm guessing that's a 1Password specific keyboard shortcut) 

**Expected behavior:**
The extension icon lights up green (and responds when clicked) on macOS
![screen shot 2016-09-20 at 4 41 55 pm](https://cloud.githubusercontent.com/assets/4733304/18692742/2efce7e8-7f51-11e6-99b9-e570c74a393a.png)
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 Pro, x64
- Brave Version:
  0.12.1 and also HEAD on master
- Steps to reproduce:
  1. Install / configure Dashlane
  2. Launch Brave
  3. Use preferences > security to set Dashlane as default manager
  4. notice icon in top right; should be the deer icon
  5. try interacting with extension button
- Screenshot if needed:
  ![screen shot 2016-09-20 at 4 25 20 pm](https://cloud.githubusercontent.com/assets/4733304/18692836/ee641908-7f51-11e6-8b53-517c8682263d.png)
- Any related issues:

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/dashlane-plugin-not-working/856

**Comment by srirambv** [comment]
Looks like its working on 0.13.2 build But doesn't open the site which is stored in Dashlane. Just the widget is active but doesn't show the actions available on the page.

![image](https://cloud.githubusercontent.com/assets/17010094/22693420/1b1af370-ed3b-11e6-9bb5-830de439297b.png)

**Comment by LaurenWags** [comment]
+1 from twitter: https://twitter.com/BrainInteractiv/status/934793912543338497
Win 10, Brave 0.19.95

**Comment by bsclifton** [comment]
Closing as this should work great with [brave-core](https://github.com/brave/brave-browser)
