### ISSUE TITLE
"Your ad blocker is breaking Speedtest.net"

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [brave/browser-laptop#414]
Not sure what more to say..
Using the Windows build I got in the mail last night.

![wytz6mu 1](https://cloud.githubusercontent.com/assets/5640470/12670037/66992c2a-c665-11e5-92d7-2c84ec8f5971.png)

**Comment by TheFallenOneGOTH** [comment]
Confirmed for Windows 10.

**Comment by bbondy** [comment]
Fixed here:
https://github.com/bbondy/abp-filter-parser-cpp/commit/a88aadd16b11acfa1f01bbe9448f1b380d1298dd

We check for adblock db definitions daily so you should get this fix within 24h by just restarting your browser tomorrow.
