### ISSUE TITLE
Windows 7 - selection problems with first item in custom menu 

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4142]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When opening the menu and using the mouse, the first item doesn't show as selected and isn't clickable until you move almost halfway down the HTML element (see attached screenshot for a demo).

**Expected behavior:**
Menu should be selectable as soon as cursor enters the context menu element

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 Pro x64

- Brave Version:
HEAD on master

- Steps to reproduce:
    1. Launch Brave
    2. Press ALT to show the menu
    3. Put mouse over File
    4. Move mouse slightly down into the context menu item
    5. Notice it's not selected

- Screenshot if needed:
![win7-menu](https://cloud.githubusercontent.com/assets/4733304/18700452/3473bb44-7f8c-11e6-8dd9-20c00a5550a6.gif)

- Any related issues:

**Comment by bsclifton** [comment]
This is a tough one...  Here is what I know about the issue (thanks to @bbondy to helping me troubleshoot):

- When the menu item is not selected, you can click and drag. I added the style `-webkit-app-region: no-drag;` to the element, but there is no change.
- If you edit the CSS or use the DOM inspector to find "contextMenuSingle" and give it a border-top of 0 pixels, the issue is fixed. But why? This is not an ideal solution
- In the render method for `js/controls/main.js`, there is a variable `shouldAllowWindowDrag`. I tried manually setting this to false... but there is no change.

**Comment by luixxiul** [comment]
Moving to 0.12.3?

**Comment by bsclifton** [comment]
No- will be working on solving it this morning. Stay tuned...
