### ISSUE TITLE
Printer Friendly Window Crashes Browser

### ISSUE THREAD

**Issue by findablenine** [brave/browser-laptop#4148]
**Did you search for similar issues before submitting this one?**Yes

**Describe the issue you encountered:**When clicking on printer friendly version of webpages that require an extra window to open it. It seems to try to open the new window but crashes the browser as a whole.

**Expected behavior:**It should have opened a new window with the option to be able to print the printer friendly sized version. 
- Platform (Win7, 8, 10? macOS? Linux distro?):Win10
- Brave Version:0.12.1
- Steps to reproduce:
  1. open a window that has a printer friendly version option
  2. click on printer friendly option
  3. Both browser windows close out
- Screenshot if needed:
- Any related issues:

**Comment by bridiver** [comment]
do you have a specific example?

**Comment by luixxiul** [comment]
I'm going to close this issue in favor of this topic on our community site for this issue 😄 

https://community.brave.com/t/discussion-https-github-com-brave-browser-laptop-issues-4148/10045

@findablenine if you are still around here, would you please join the conversation there to talk about the issue further? 👍 There is a lot of discussions on the community, and you would be able to find solutions for other issues you might experience. Thanks!
