### ISSUE TITLE
Excessive memory use

### ISSUE THREAD

**Issue by ChrisRfr** [brave/browser-laptop#415]
With the same tabs, it is almost double chrome known to be greedy.

**Comment by SJ-Diamond** [comment]
Also, CPU usage is massive. Hopefully you guys can do something to lower memory and cpu usage at some later point :)

**Comment by Kzeir** [comment]
Yeah, 7 tabs consuming almost 1.5 gb of RAM

**Comment by visionpoint** [comment]
Currently 5 tabs opened, on OS X (10.11.4) and the memory consumption is up to 1.66GB. In comparison, I've got Opera running with 12 tabs simultaneously consuming less than Brave.

<img width="1440" alt="screenshot 2016-04-12 16 20 26" src="https://cloud.githubusercontent.com/assets/4595734/14474358/9206506e-00ca-11e6-806a-250d84b9fd5a.png">

**Comment by bbondy** [comment]
Is this a fresh start with the 5 tabs of both browsers?  We also plan on doing something to the great suspender.

**Comment by visionpoint** [comment]
@bbondy Apologies for the late response Brian. To answer your question: yes, fresh start on both browsers. Here's another fresh start test but with Firefox this time. Same five tabs open, Brave ~1.20GB vs. Firefox ~900MB -- these numbers seems to remain more or less steady when running the same websites/amount of tabs on both browsers. Certainly not as wide a gap as my previous test with Opera. Also, Brave has much less of a memory footprint than Chrome. 

![image](https://cloud.githubusercontent.com/assets/4595734/14610967/01b286f2-055e-11e6-888c-592779594dbe.png)
_ _ _ _ _ _ _ _ _ _ _  _

![image](https://cloud.githubusercontent.com/assets/4595734/14610980/133842a4-055e-11e6-816c-66d86c654c73.png)

**Comment by visionpoint** [comment]
@bbondy Building functionality like The Great Suspender sounds awesome. If you haven't already, take a look at the [OneTab](https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall) extension in Chrome. Not only does it reduce memory consumption significantly, but it may increase productivity and reduce clutter in the amount of tabs open by providing a "workspace" where all tabs can be accessed from swiftly.

**Comment by bbondy** [comment]
Yes @BrendanEich is a fan of OneTab, we want that built in too.

**Comment by legacybass** [comment]
Looks like this is still being looked into. I thought I'd show my experience as well. 5 tabs open on version 0.11.0 and still using lots of resources. One of them is a website I'm working on so the dev tools are up. Otherwise, just regular websites.
![brave_resource_usage3](https://cloud.githubusercontent.com/assets/1490142/16700466/6d185932-4517-11e6-96af-3be8c3cd9885.PNG)

**Comment by bridiver** [comment]
Hard to tell from the windows task manager, but since there are no urls below it I'm assuming that's the main process. We just took care of a fairly large memory issue and that fix will be in the next release. I'm currently tracking down a few more smaller issues.

**Comment by bridiver** [comment]
There have been a lot of updates since this ticket was opened and I'm going to close it with https://github.com/brave/browser-laptop/issues/3314 
Please open a new issue if you see problems after the next release
