### ISSUE TITLE
System font size not respected by Brave

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4151]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
System font size not respected by Brave

**Expected behavior:**
Should inherit the system font size
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.2 RC1
- Steps to reproduce:
  1. Set System font size at 100%, check the file menu font size
  2. Set System font size at 125%, font size remains same as before
  3. Set System font size at 150%, font size remains same as before
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18723639/4955bdb4-8031-11e6-9bbe-f1b6fac39d26.png)
  
  ![image](https://cloud.githubusercontent.com/assets/17010094/18723797/f0185378-8031-11e6-84ab-15bb98ae4879.png)
- Any related issues:

cc: @bsclifton 

Setting 0.12.2 as milestone for now could be moved to 0.12.3 if required

**Comment by bridiver** [comment]
this worked in 0.12.1?

**Comment by luixxiul** [comment]
This seems to me a long persisting issue: #2324 #2469 #1937

**Comment by bridiver** [comment]
if this is not a new issue we should probably bump it
@bbondy  ?

**Comment by luixxiul** [comment]
@srirambv do you still experience the issue?

**Comment by srirambv** [comment]
No longer reproducible.. Closing the issue for now
