### ISSUE TITLE
Add styling to make "Merge Favorites" appear aligned (in Import Bookmark modal)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4152]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Merge Favourite into bookmark not properly aligned in Import Bookmark modal

**Expected behavior:**
Should be properly aligned
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.2 RC1
- Steps to reproduce:
  1. Open preferences, Click on Import Bookmarks
  2. Merge Favourite into Bookmark is not properly aligned
     3.
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18724438/5386c2ee-8034-11e6-88d1-a901103642f6.png)
- Any related issues:
  cc: @darkdh

**Comment by darkdh** [comment]
This is intended because it is the sub option of import bookmark.
Maybe we need other way to present the sub option, @bradleyrichter?

**Comment by bradleyrichter** [comment]
This will be improved soon:

![image](https://cloud.githubusercontent.com/assets/13509546/22521294/6f2de36a-e86c-11e6-8cd5-3f63dff829c1.png)

**Comment by bsclifton** [comment]
Let's reopen and use this to track the change @bradleyrichter has shown 😄

**Comment by bradleyrichter** [comment]
@cezaraugusto just made a new, smaller switch style so we only need the "L"...

**Comment by luixxiul** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/7194, https://github.com/brave/browser-laptop/commit/46e3919d5f143150735cd1f185923c0280892d48
