### ISSUE TITLE
Browser crashes when signing into Facebook

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4153]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Browser crashes when signing into FB (on both private and non-private tabs)

**Expected behavior:**
Should not crash 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 RC1

- Steps to reproduce:
    1. Open Facebook.com
    2. Type username and type @, Brave crashes
    3. Happens on both Normal tab and private tab

- Screenshot if needed:

- Any related issues:

**Comment by ayumi** [comment]
Confirmed on Mac OS X 10.11.6

**Comment by bridiver** [comment]
the problem is not limited to `@`. Any misspelled word will cause the browser to crash.
