### ISSUE TITLE
Import Bookmarks doesn't import data from other browsers

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4154]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Import Bookmarks doesn't import data from other browsers

**Expected behavior:**
Should successfully import bookmarks. Also should show a confirmation message if bookmark imported successfully

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 Dev RC1

- Steps to reproduce:
    1. Open preferences, Click on Import Bookmarks
    2. Select which ever browser you want to import from  and select what to import
    3. Click on Import bookmarks not loaded. Close and reopen window still doesn't show imported bookmarks

- Screenshot if needed:
 ![import](https://cloud.githubusercontent.com/assets/17010094/18726635/4db6bbe0-803d-11e6-85d8-158fdf4b369d.gif)

- Any related issues:

cc: @darkdh

**Comment by darkdh** [comment]
This is fixed by https://github.com/brave/electron/commit/0ac2a5ce3c9f4d8c30a4f410194e1978f2262d28.
Please re-test it on next RC
