### ISSUE TITLE
Closing a site immediately after loading shows entry in Brave payment list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4156]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Closing a site immediately after loading shows entry in Brave payment list

**Expected behavior:**
User should be active for 8s + for the website to be listed under payments
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.2 Dev RC1
- Steps to reproduce:
  1. Create Brave Wallet in payments
  2. Click on add Funds, click on visit Cubits button to launch cubits site in a new tab
  3. Close the new tab immediately, repeat step 2 again
  4. Close and reopen preferences page
  5. Cubits listed under payments with time spent 
- Screenshot if needed:
  ![pay](https://cloud.githubusercontent.com/assets/17010094/18729128/5a5c9d6e-8048-11e6-9b06-751dc90fdd58.gif)
- Any related issues:

**Comment by mrose17** [comment]
@srirambv - i can't reproduce this. seriously. could you run from the `master` branch, or wait until 0.12.2dev is RC'd and try again.  if it's still happening, i'll give you some debug options to run, thanks!

**Comment by mrose17** [comment]
@srirambv - please try this against https://github.com/brave/browser-laptop/releases/tag/0.12.2dev-RC2 and let me know what you see, thanks!

**Comment by srirambv** [comment]
@mrose17 Still happening on RC2 build. Did a clean install of the build and did the same steps , open a site wait for it to load and close it. Close and reopen preferences and you can see the site listed under payments


![paymnt](https://cloud.githubusercontent.com/assets/17010094/18777372/9fbd8570-8166-11e6-9438-1416552eeff0.gif)

**Comment by mrose17** [comment]
interesting. ok, let's try this: 

1. ask @bsclifton to tell us the command to run from a shell that is the equivalent of

    % LEDGER_PUBLISHER_VERBOSE=true /Applications/Brave/Contents/MacOS/Brave

2. delete `ledger-synopsis.json` so we get a fresh publisher synopsis

3. run your test above

4. put the output from the browser in a gist and include the URL in a comment here. thanks!

**Comment by bsclifton** [comment]
Windows is almost the same :smile: 
1. Start > Run > cmd.exe
2. set LEDGER_PUBLISHER_VERBOSE = true
3. cd %userprofile%\AppData\Local\brave
4. run .\app-0.12.2\Brave.exe

**Comment by srirambv** [comment]
@mrose17 here is the [gist ](https://gist.github.com/srirambv/a822dca363ba1acd30684110f0b92e63)file with browser output based on the steps mentioned by @bsclifton

**Comment by mrose17** [comment]
@srirambv - just fyi, you'll need to start testing in the future with another site besides "cubits.com" ... bitcoin exchange are now on the exclusion list...

**Comment by bbondy** [comment]
moving to 0.12.4

**Comment by srirambv** [comment]
@mrose17 Here is the [new gist ](https://gist.github.com/srirambv/d5335cf71751448ae2da2cc15e003a5d#gistcomment-1884467)file for 3 different sites on 0.12.3dev-RC1 Build.

**Comment by mrose17** [comment]
@srirambv - thanks!

**Comment by mrose17** [comment]
@srirambv - can you reproduce this? i can't (and haven't been able to for a while). thanks!

**Comment by srirambv** [comment]
Unable to repo the issue. Closing the issue. Will reopen if it can be repro'ed.

**Comment by bsclifton** [comment]
removing from 0.14.0 because there is no associated fix
