### ISSUE TITLE
un-ignore cert transparency errors

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4159]
see https://github.com/brave/browser-laptop/pull/4150

**Comment by bridiver** [comment]
#4158 ignoring of the transparency error should be reverted when this is fixed

**Comment by diracdeltas** [comment]
requires https://github.com/electron/brightray/issues/248

**Comment by diracdeltas** [comment]
@bridiver have we incorporated the upstream fixes?

**Comment by bridiver** [comment]
no, but I'll pull them in right now

**Comment by bbondy** [comment]
Moving to 0.12.4, please move back if it makes a respin.

**Comment by bbondy** [comment]
Included in 0.12.3rc3
