### ISSUE TITLE
Text inside the find bar should be highlighted when pressing Ctrl+F for the 2nd time

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-laptop#416]
![capture](https://cloud.githubusercontent.com/assets/8424198/12671027/7bc6413e-c69f-11e5-9bcd-29470cf3b395.PNG)

When the find bar is already opened (used before), pressing Ctrl+F doesn't highlight the text. On other browsers, pressing Ctrl+F for the 2nd time will highlight the text, so that users can resume their search and immediately type new words.

Windows 7 Home Premium 64-bit

**Comment by bbondy** [comment]
++ this is a big gripe for me too.

**Comment by psimyn** [comment]
quick n dirty fix is to hide _then_ show everytime ctrl f is pressed.

frame.js:
```
case 'show-findbar':
  WindowActions.setFindbarShown(this.props.frame, false)
  window.setTimeout(() => WindowActions.setFindbarShown(this.props.frame, true), 0)
  break
```

Nicer way is probably to add a `highlightSearchText` action or something, which would then need to be unset by the findbar for subsequent renders
