### ISSUE TITLE
Adblock count not shown for blocked items

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4160]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Adblock count not shown for blocked items

**Expected behavior:**
Should show the count of items blocked and list when clicked on the count

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 Dev RC1 (Clean Install)

- Steps to reproduce:
    1. Visit jsdiffle.net, Ad shown at the bottom left cornor, Bravery panel shows 0 count
    2. Visit slashdot.org, Bravey panel shows 0 count even though blocks ads. 
    3. Disable and enable Ad Control  on Slashdot.org still doesn't show the blocked content count/list them

- Screenshot if needed:
![1](https://cloud.githubusercontent.com/assets/17010094/18730778/06f5e6fa-8050-11e6-8bef-36b9853caf57.gif)

- Any related issues:

**Comment by bbondy** [comment]
pls confirm if fixed in rc2, I think it is.

**Comment by alexwykoff** [comment]
confirmed fixed in 0.12.2 rc2
