### ISSUE TITLE
1Password may fail to auto-fill forms

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4161]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Pressing <kbd>Ctrl</kbd>+<kbd>\\</kbd> does not always auto-fill form fields.

**Expected behavior:**

Pressing <kbd>Ctrl</kbd>+<kbd>\\</kbd> auto-fills form fields from 1Password.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.1
- 1Password Version: 4.6.0.604

- Steps to reproduce:
    1. Navigate to https://twitter.com/login
    2. Press <kbd>Ctrl</kbd>+<kbd>\\</kbd>
    3. Note that form fields are *not* auto-filled

- Screenshot if needed: N/A

- Any related issues: N/A

- Original Report: https://twitter.com/BrockLAllen/status/778717571117748224

**Comment by brockallen** [comment]
Thanks for filling this out for me @jonathansampson

**Comment by alexwykoff** [comment]
Just tried 0.12.2 on OS X and the combination of command + \ filled and submitted the login.

**Comment by brockallen** [comment]
Anything you can think of for me to either produce a log, or get you more info on what my local issue is?

**Comment by brockallen** [comment]
Oh, also I'm on Windows, FWIW.

**Comment by alexwykoff** [comment]
If you opened the developer's console (Shift + f8) then it may have some info in the console. Checking that and the content console (View -> Toggle Developer Tools), you may find some errors.

**Comment by jonathansampson** [comment]
@alexwykoff I believe @BrendanEich was running into an issue intermittently. I have not personally been able to reproduce the issue on my Windows 10, Surface Book.

**Comment by brockallen** [comment]
So more specifics: when I'm on a long screen, I hit Ctrl-\ and what happens is the 1Password menu pops up (the one I can then use to search for a website I want to visit/login to). This is the expected when I'm not on any login page. What I'd expect to happen is it recognizes that the URL i'm at is an existing well-known login page and dot he auto-fill.

![untitled](https://cloud.githubusercontent.com/assets/649492/18854983/4465eafa-841d-11e6-8d2a-001d57605d40.png)

**Comment by brockallen** [comment]
Also, no errors in the dev console.

**Comment by alexwykoff** [comment]
Perchance are you noticing a flickr when you attempt to use the ctrl + \ shortcut?

![1pass_flicker](https://cloud.githubusercontent.com/assets/1434040/18856107/c2a45bcc-841d-11e6-9b82-632690709470.gif)

**Comment by brockallen** [comment]
Nope.

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/6120)

**Comment by jonathansampson** [comment]
@brockallen Are you still seeing this issue in current builds of Brave?

**Comment by brockallen** [comment]
I'll check now...

**Comment by brockallen** [comment]
Ah, it now works. Thanks!

**Comment by jonathansampson** [comment]
This issue appears to have been resolved in recent builds. Closing, but please re-open if anybody else happens to encounter the _same_ issue.
