### ISSUE TITLE
Bookmark title in bookmark folder over the border of the browser window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4167]
**Describe the issue you encountered:** Bookmark title in bookmark folder goes over the border of the browser window.

**Expected behavior:** it should be inside the browser window and the title should be shorten with `text-ellipsis` or like that.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2 RC1 (I am not sure if this issue has existed since the latest version)
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18736574/46228d4c-80c3-11e6-83e5-350c83b65a27.png)
- Any related issues:

Setting a milestone for now.

**Comment by bsclifton** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/4745
