### ISSUE TITLE
Media queries for elements inside #urlInput need improving

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4170]
**Describe the issue you encountered:**

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18737171/38c06a88-80c9-11e6-8b8c-d080cf985e98.png)

**Expected behavior:** Media queries for elements inside #urlInput need improving. It seems to me that we do not need max-width here at all. Here is my suggestion:

- Set ``width: 135px`` to ``.WindowCaptionButtons``, which seems to be static (correct if I'm wrong)
- Set ``width: calc(100% - 135px)`` to ``.navbarMenubarFlexContainer``
- Remove ``max-width`` properties based on platforms from #urlInput

By doing these we should get this:
![menubar](https://cloud.githubusercontent.com/assets/3362943/18737302/86808a5e-80ca-11e6-9565-5b62a1275227.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 JP

- Brave Version: 0.12.2 RC1

- Any related issues: #3036

**Comment by jonathansampson** [comment]
All that is really needed is to set the `input` element's `width` to `100%`.

I have this change in a commit, and will issue a PR.

![resize-mq-fixed](https://cloud.githubusercontent.com/assets/815158/18813572/4dac7108-82b3-11e6-8ee3-fa8f1186a719.gif)

**Comment by luixxiul** [comment]
It is not completely smooth. I think that is why I thought ``width: calc(100% - 135px)`` should work here. wdyt, @jonathansampson?
