### ISSUE TITLE
Windows system context menu appears by doing a right click around windowCaptionButtons

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4171]
**Describe the issue you encountered:** Windows system context menu appears by doing a right click around ``windowCaptionButtons``

**Expected behavior:** It should appear by doing a right click only on ``windowCaptionButtons``

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Steps to reproduce:
    1. Make the browser window smallest
    2. Open as many tabs as tab set buttons appear
    3. Do a right click on the row of the tab set buttons
    4. The system context menu appears

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18737417/dbe412c6-80cb-11e6-9e93-a2f727b41b4a.png)

- Any related issues: #3036

**Comment by bsclifton** [comment]
OK i'm able to repro after a 2nd tabset is opened (clicking in that area)
