### ISSUE TITLE
Regression: Google Adsense responsive ads no longer blocked

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4172]
**Describe the issue you encountered:**
Google Adsense responsive ads are no longer either blocked or replaced.

**Expected behavior:**
It should be either blocked or replaced based on user's preference.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Steps to reproduce:
    1. Go to https://www.philosophyguides.org/shousetsu-shincho-column/
    2. Toggle your ad control settings

#3850

**Comment by luixxiul** [comment]
It seems that it is basically the same issue as #4160

**Comment by luixxiul** [comment]
Ads here are also not blocked http://www.browserleaks.com/webrtc

**Comment by bbondy** [comment]
Fixed here
https://github.com/brave/browser-laptop/commit/6aeb0eb10c2b971f83ff4fddf02af882aa96fc94
