### ISSUE TITLE
Regression: http://excellentmovies.net/ cannot be blocked (Safe Browsing does not work)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4173]
**Describe the issue you encountered:** http://excellentmovies.net/ cannot be blocked

**Expected behavior:** It should be blocked

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Steps to reproduce:
    1. Go to http://excellentmovies.net/ 
    2. Toggle "Block Phishing / Malware" switch on bravery panel

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Fixed here https://github.com/brave/browser-laptop/commit/6aeb0eb10c2b971f83ff4fddf02af882aa96fc94
