### ISSUE TITLE
Add an option to clear saved site exception in clear browsing data dialog

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4174]
Add an option to clear saved site exceptions in clear browsing data dialog.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18737696/aa1fbe94-80cf-11e6-97b1-d0f6e8065fea.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Any related issues: #4134

**Comment by diracdeltas** [comment]
++
