### ISSUE TITLE
pulldown on menubar cannot be opened until second click

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4175]
**Describe the issue you encountered:** pulldown on menubar cannot be opened until second click

**Expected behavior:** It should be opened with the first click

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Steps to reproduce:
    1. Hide the menu bar
    2. Hit <kbd>Alt</kbd>
    3. Click "File" -> nothing appears
    4. Click it again -> the pulldown appears

- Screenshot if needed:

- Any related issues: #3036

**Comment by luixxiul** [comment]
Setting a milestone as it is annoying that the pulldown does not appear with the first click.

**Comment by luixxiul** [comment]
This works for now, but I suspect it thanks to #4243, which shall be modified later. /cc: @bsclifton

**Comment by bsclifton** [comment]
@luixxiul does this issue persist? I am unsure what you mean in the previous comment

**Comment by luixxiul** [comment]
@bsclifton sorry, I mean that the issue does not exist in 0.12.2 RC3 but I'm not sure if it was fixed intentionally or not.

**Comment by bbondy** [comment]
I'll close for now but please re-open if it's still a problem.
