### ISSUE TITLE
Hitting a space after inputting a character inside input field causes a crash

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4176]
**Describe the issue you encountered:** Hitting a space key after inputting a character inside input field causes a crash. 

**Expected behavior:** It should not crash.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Steps to reproduce:
    1. Clear your brave folder temporarily and open the browser
    2. Go to https://github.com
    3. Input a character inside the input field "Pick a username"
    4. Hit a space key

- Screenshot if needed:

- Any related issues: #4169

**Comment by alexwykoff** [comment]
Confirmed on OS X

**Comment by bridiver** [comment]
dup #4153
