### ISSUE TITLE
(OS X) floating "Missing Plug-in" on some sites, page content not clickable

### ISSUE THREAD

**Issue by jsynowiec** [brave/browser-laptop#418]
On several sites there is a "Missing Plug-in" alert visible (flash adds?).

<img width="159" alt="missing plugin" src="https://cloud.githubusercontent.com/assets/1029142/12671862/ab59da50-c672-11e5-9f28-8f976ca9e694.png">

Generally it's not a problem but on some webpages this is floating over page content and nothing is clickable.

OS X El Capitan 10.11.3, no flash, silverlight or java installed.

**Comment by bbondy** [comment]
Could you give a particular site that has the floating div?  (Several if you have more than one)

**Comment by jsynowiec** [comment]
One of such sites was the news site from Poland: http://www.gazeta.pl/0,0.html

<img width="892" alt="zrzut ekranu 2016-01-29 16 52 02" src="https://cloud.githubusercontent.com/assets/1029142/12680184/a6eb5ce2-c6a8-11e5-96ef-8066617c6293.png">

**Comment by luixxiul** [comment]
Cannot be reproduced. I think this is related with #386. If not let us know to reopen this issue, thanks. Closing for now.
