### ISSUE TITLE
[Feature request] Connect to Passman extension (= password manager) of Nextcloud/ownCloud

### ISSUE THREAD

**Issue by HLFH** [brave/browser-laptop#4184]
Hi,

[Passman](https://github.com/nextcloud/passman) is an open source password manager and an extension of Nextcloud [and ownCloud](https://github.com/brantje/passman). 

Could you add a Passman connector to Brave?
![capture d ecran 2016-09-22 a 13 27 26](https://cloud.githubusercontent.com/assets/2359059/18746581/822d674e-80c8-11e6-8251-44afce7cc3a3.png)

Thanks in advance,
HLFH

**Comment by Sh1d0w** [comment]
Big thumbs up about the idea.

**Comment by mischapeters** [comment]
I guess we need to get more people behind it as it's not been done yet. Would love to see Passman in Brave. Both Firefiox and Chrome support this through their extension store.

**Comment by violoncelloch** [comment]
would like this too!

**Comment by EmilHarder** [comment]
The one thing keeping me from switching to Brave as daily driver.

**Comment by kaelte** [comment]
I am looking word to Passman for Brave.
Thanks a lot !

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/passman-password-manager-integration/2694

Let's keep the discussion about this extension there 😄

**Comment by HLFH** [comment]
So I'll use Bitwarden.

**Comment by mmaura66** [comment]
i use Passman following this tutorial: https://www.youtube.com/watch?v=B7dvJrhXIbc
