### ISSUE TITLE
System buttons on window should not be wrapped

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4185]
**Describe the issue you encountered:**

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18748648/33bd257c-810e-11e6-8ff3-4241a96fa9d8.png) ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18748683/5fcd6550-810e-11e6-9667-e3251476e037.png)

**Expected behavior:** The system buttons on window should not be wrapped.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC1

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Definitely happens when menubar is shown- good find :smile: 

@luixxiul do you have menus enabled?  I'm curious because without menus, it works perfectly for me.  If it happens when the menu is hidden, an example site is appreciated

**Comment by luixxiul** [comment]
@bsclifton yes, it happens only menus are enabled ("ヘルプ" next to the buttons means "Help")
