### ISSUE TITLE
[FR] Shortkey ALT + D to select navbar 

### ISSUE THREAD

**Issue by SamJongenelen** [brave/browser-laptop#419]
When ALT + D is pressed in Brave, the navigational bar is not selected. It does in any other explorer alike window or browser and its damned handy.

Im on Windows 10 64 bit

**Comment by nbourdais** [comment]
I am more accustomed to Ctrl+L which works.

**Comment by ChrisRfr** [comment]
I would add another keyboard shortcut,
Alt+Enter to open a search or url typed in a new tab.

**Comment by bbondy** [comment]
> I would add another keyboard shortcut,
> Alt+Enter to open a search or url typed in a new tab.

Moved that to #442.
