### ISSUE TITLE
URL in the bar is replaced during load

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4191]
**Describe the issue you encountered:** URL in the URL bar is replaced during load

**Expected behavior:** It should not be replaced

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: https://github.com/brave/browser-laptop/tree/71f4ebe80cedbd25a5fcd976a380f69de5b69d68

- Steps to reproduce:
    1. Go to http://ja.espnf1.com/f1/motorsport/team/371.html
    2. The URL is replaced with http://player.performgroup.com/eplayer/eplayer.html#, which is not the URL of the page

**Comment by luixxiul** [comment]
Please set a milestone if needed.

**Comment by bbondy** [comment]
@diracdeltas could you triage this one?

**Comment by diracdeltas** [comment]
not happening in last release but it is happening in the latest 0.12.2 RC
