### ISSUE TITLE
Ctrl+U doesn't invoke View Source

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4200]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Pressing Ctrl+U doesn't open View Source. Instead, the user must press Ctrl+Alt+U.

**Expected behavior:**

In Chrome, Edge, and Firefox, Ctrl+U opens View Source. When using the same shortcut, I expected Brave to also open View Source.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 (14393)
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Go to http://brave.com
  2. Press Ctrl+U
  3. Note that View Source _is not_ opened
- Relevant LOC: [.../app/localShortcuts.js#L25](https://github.com/brave/browser-laptop/blob/e59903714c8650896c890f05169561ffbf541c6d/app/localShortcuts.js#L25)
- Screenshot if needed: N/A
- Any related issues: N/A

**Comment by jonathansampson** [comment]
After speaking with @bbondy, the original motivation was likely to avoid confusion with underline commands. If this is a real issue, we may be able to investigate `event.target` to determine whether or not it is appropriate to invoke view-source.

**Comment by Liunkae** [comment]
Closing this in favor of #7702.
