### ISSUE TITLE
Bookmark manager columns should be resizable and horizontally scrollable

### ISSUE THREAD

**Issue by olimay** [brave/browser-laptop#4201]
In the bookmark manager, the titles of bookmarks with long URLs get squashed.

![image](https://cloud.githubusercontent.com/assets/101905/18765567/499c00b8-80e4-11e6-8421-c13afae59b35.png)

It gets especially bad if you have a folder of JS bookmarklets.

![image](https://cloud.githubusercontent.com/assets/101905/18765662/b20effa6-80e4-11e6-965d-620b82fd23a8.png)

Adding resizable columns/headers and a horizontal scroll to the bookmarks UI would fix the problem.
- Platform: OS X 10.11.6
- Brave Version: 0.12.1

**Comment by rebron** [comment]
Closing wontfix. Different ui in brave-core. Marking fixed with brave-core.
