### ISSUE TITLE
Cannot save bookmark outside of bookmarks toolbar

### ISSUE THREAD

**Issue by olimay** [brave/browser-laptop#4202]
I can't seem to save bookmarks in any folder outside the Bookmarks Toolbar folder. Saving to the Bookmarks Toolbar folder and any subfolders appear to work correctly.
- Platform: OS X 10.11.6
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Click the star next to a page's URL.
  2. Click the folder dropdown.
  3. Bookmark folders outside of the Bookmarks Toolbar folder will not be visible in the dropdown.

Here are the bookmark folders in the Bookmarks Manager.

![image](https://cloud.githubusercontent.com/assets/101905/18766102/9a322168-80e6-11e6-9716-82f86dd03198.png)

Here are the places to save the bookmark that are available in the dropdown.

![image](https://cloud.githubusercontent.com/assets/101905/18766120/ab41ff3c-80e6-11e6-999a-7ab1103c852b.png)
#1658

**Comment by lucidNTR** [comment]
+1

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/my-bookmarks-are-not-showing-up-in-the-bookmark-manager/4573/16

Specifically, user has folders under the 'Other Bookmarks' folder in Bookmark manager. However, when adding a bookmark from the star icon and choosing a folder from the bookmark hanger, the 'Other Bookmarks' and subfolders are not available for selection.

**Comment by NejcZdovc** [comment]
@LaurenWags is this dup of #10157?

**Comment by LaurenWags** [comment]
@NejcZdovc I believe https://github.com/brave/browser-laptop/issues/10157 is focused on the bookmark manager drag/drop functionality while this one is for the bookmark hanger (when you click on the star icon to create a bookmark or right click on a bookmark in the toolbar to edit and update the folder).

**Comment by NejcZdovc** [comment]
Yeah I can see it like that, but root cause is the same, Other bookmarks folder is not working. Probably I will be fixing this one, so I will close all of them related to Other bookmarks.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/other-bookmarks-not-listed/7352?u=eljuno
