### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#4210]
picking up from #3294 there are a bunch of other potential users for slash commands. 
`/watch brave.com` get notifications when brave.com changes
`/email info@brave.com` create a new email message to info@brave.com in email client/web email client
`/remind me to download brave at 10:30` create a notification in calendar app
`/prefs` shortcut for about:preferences
ifttt integration
user definable shortcuts

**Comment by bridiver** [comment]
`/burner email` creates a new burner email and copies to the clipboard or pastes in a form - also usable from inside form fields or integrated as part of autofill

**Comment by bridiver** [comment]
slash commands should appear in the autosuggestions
in contrast to #3294 I think autosuggestions should still display search results to prevent the "impossible search query"

**Comment by bridiver** [comment]
these will be `:email ...` instead to avoid conflicts with file urls

**Comment by DeviatedMind** [comment]
#790 #824 #3053 #3294 #4210
