### ISSUE TITLE
Move the word visit inside the payments button

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#4212]
This related to the work done on #3711 where we added this UI

https://cloud.githubusercontent.com/assets/13509546/18232785/25f7ac2c-728c-11e6-9fcb-e09b7a1ca0b8.png

@luixxiul and @bradleyrichter talked about moving the "visit" text inside the button.

**Comment by mrose17** [comment]
resolution: get rid of the word "Visit"

**Comment by luixxiul** [comment]
Please don't forget to address #4292 too. It does not make sense at all if it appears like "Need to buy bitcoin? Cubis!" :-D

**Comment by bradleyrichter** [comment]
^ solved with text string replacement:

![image](https://cloud.githubusercontent.com/assets/13509546/19015721/9ab7f534-87be-11e6-9bad-276ad998ed28.png)
