### ISSUE TITLE
Window corners have border radius

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4216]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Borders should be consistent, regardless of Windows version. Windows 7 typically shows rounded borders and Windows 8/10 show square edges. 

**Expected behavior:**
Border looks correct
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7
- Brave Version:
  0.12.2 RC2
- Steps to reproduce:
  1. Launch Brave
  2. look at window corners
  3. If window corners look OK, try maximizing then restoring
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/4733304/18773251/33784544-8102-11e6-865b-0960259d3ae9.png)
- Any related issues: #3036

**Comment by bridiver** [comment]
border gap is only visible against a light background

**Comment by bsclifton** [comment]
Unfortunately, not completely fixed with https://github.com/brave/browser-laptop/issues/4342

High DPI versions would always show white in the corners:
![image](https://cloud.githubusercontent.com/assets/4733304/19091991/ac270c56-8a39-11e6-903d-7e1110a59e4d.png)

Potential solution offered by @bbondy would be to fix this in electron. We should be able to hide the corner regions using win32 call [SetLayeredWindowAttributes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633540(v=vs.85).aspx)

**Comment by jonathansampson** [comment]
0.13.0 build from January 14, 2017

![image](https://cloud.githubusercontent.com/assets/815158/21953521/53961fc6-d9ff-11e6-80b5-41061510a3cd.png)

**Comment by bsclifton** [comment]
Updated notes; this was also noticed when I upstreamed recent DPI fixes:
https://github.com/electron/electron/pull/8404

I believe the problem is the approach I took for cancelling out non-client area.  Setting an inset of 0,0 might be the approach we have to take, since the styles being generated for the window are unusual.

**Comment by bsclifton** [comment]
I believe I have the fix for this

@kevinsawicki noticed this issue when I upstreamed the DPI fix to electron. I went back to the previous way I was handling non-client area and this fixed the issue. 

Fixed in electron with https://github.com/electron/electron/pull/8404/commits/9e0547b98f8b7f3a572aa1cf9770f434c8fdeed9; I'll submit a PR for muon tomorrow after testing with browser-laptop-bootstrap

**Comment by srirambv** [comment]
The blue window border is visible/not visible upon restarts. 

Outline not visible on right and bottom of the browser window
![image](https://cloud.githubusercontent.com/assets/17010094/21953969/d54b92b6-da3c-11e6-8ec8-7ea8ca7e4b80.png)

Outline not visible on the bottom but on all other sides after restart
![image](https://cloud.githubusercontent.com/assets/17010094/21953974/e7d97c90-da3c-11e6-84fc-20079935af3d.png)

**Comment by bsclifton** [comment]
We'll want to test this on Windows 7. The borders should ideally NOT be rounded there... if they are, we can open a new issue.

**Comment by srirambv** [comment]
Works fine on Windows 10 on preview 9

**Comment by bsclifton** [comment]
Unfortunately, this is still an issue on Windows 7 (I'll create a separate issue for this)
![screen shot 2017-01-17 at 12 27 43 pm](https://cloud.githubusercontent.com/assets/4733304/22036519/12bf8e24-dcb1-11e6-8143-d273ae28b07a.png)

To be clear, the behavior **hasn't changed** for Windows 7. Windows 10 was experiencing an issue which caused it to have the same problem as Windows 7 and instead of making a new ticket, we updated this one.  The issue seen in Windows 10 was introduced with 0.13.0 and was closed with brave/muon#144
