### ISSUE TITLE
Standard shortkeys are not used

### ISSUE THREAD

**Issue by LoloIrie** [brave/browser-laptop#422]
F12 for the dev console
F5 to refresh
.....

**Comment by bbondy** [comment]
This was fixed in this dupe:
https://github.com/brave/browser-laptop/issues/410

**Comment by bbondy** [comment]
It'll be released in the next update.

**Comment by LoloIrie** [comment]
So quick........ Well done :)

**Comment by LoloIrie** [comment]
F12 doesn't open (anymore ?) the dev console
F11 should open the full screen view as well (instead CTRL+Shift+F)

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
https://support.google.com/chrome/answer/157179?hl=en

Thanks :)

**Comment by bbondy** [comment]
posted here, thanks for the ping on this:
https://github.com/brave/browser-laptop/issues/1218
