### ISSUE TITLE
Navbar searches beginning with the letter 'a' search on Amazon

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#4221]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Went to search for any number of terms beginning with the letter 'a' followed by a space.  All of them search Amazon instead of the web.

**Expected behavior:**
Web search.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Slackware

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Spawn new tab
    2. Search for "A search like this will go to amazon."
    3. Wince

- Screenshot if needed:
![amazononly](https://cloud.githubusercontent.com/assets/5156230/18779155/baf33572-8145-11e6-923d-97f6855da928.png)

Browser has been launched for many hours and lots of tabs are open.  Maybe others will not be able to reproduce.

- Any related issues:

**Comment by bbondy** [comment]
we were just having a discussion about this last night. I think we'll do `:a` as the different engine prefix.
