### ISSUE TITLE
Remove duplicate import bookmark folder

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#4222]
![import_folder_duplication](https://cloud.githubusercontent.com/assets/11330831/18779999/0a725b88-81ae-11e6-8f8c-ece28c72a172.gif)

cc @alexwykoff , @bbondy

**Comment by alexwykoff** [comment]
Failed on OS X

**Comment by darkdh** [comment]
The folders created by importer before this change lack `parentFolderId: 0` due to https://github.com/brave/browser-laptop/commit/3a656bb5d87ce4d2266f43a1978cdc182a60fadc#diff-df9d21f94d0a7809f7adb8cb43a9f6aeL130.
So them cannot be deleted due to failing to satisfy the condition https://github.com/brave/browser-laptop/commit/3a656bb5d87ce4d2266f43a1978cdc182a60fadc#diff-df9d21f94d0a7809f7adb8cb43a9f6aeR115
Please remove them manually before testing it.
