### ISSUE TITLE
Regression: Unable to open bookmarks within folder when selected from menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4226]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to open bookmarks within folder when selected from menu

**Expected behavior:**
Should be able to open bookmarks stored within folders

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x32,x64

- Brave Version:
0.12.2 RC2

- Steps to reproduce:
    1. Create a two level nested folder in bookmarks bar
    2. Bookmark a page under the second level folder
    3. Try opening the bookmarked page from menu, doesnt't work

- Screenshot if needed:
![bookmarks](https://cloud.githubusercontent.com/assets/17010094/18781862/8de7a726-817b-11e6-9d4f-40baf442ea23.gif)

- Any related issues:

cc: @bsclifton

**Comment by bsclifton** [comment]
works w/ keyboard but not w/ mouse... looking into fix...

**Comment by bsclifton** [comment]
technically not a regression since we've never had custom drawn menus before :smile: fix is on the way
