### ISSUE TITLE
Bookmarks menu not updated when adding/removing bookmark folder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4227]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Deleted folders under bookmark gets removed only after browser restart

**Expected behavior:**
Deleted folders should be removed from the bookmarks menu with requiring a restart

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x32, x64

- Brave Version:
0.12.2. RC2

- Steps to reproduce:
    1. Create bookmark folders 
    2. Delete the bookmark folder from the bookmark bar
    3. Folder shows in bookmark menu, gets removed only after restarting browser

- Screenshot if needed:
![b1](https://cloud.githubusercontent.com/assets/17010094/18782008/21b558e0-817c-11e6-9e3b-daf805dbfa7b.gif)

- Any related issues:
#4124 
cc: @bsclifton

**Comment by bbondy** [comment]
I think this was around for a couple versions so moving to 0.12.3.

**Comment by bsclifton** [comment]
This specifically is an issue with the menu code- we don't send any windowActions when a bookmark folder is deleted. To confirm, you can also just add another bookmark and that will cause the menu to be rebuilt (which then has the change)
