### ISSUE TITLE
Ads should be blocked on JSfiddle.net

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4228]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ads not blocked on JSfiddle.net

**Expected behavior:**
Ad's should be blocked on all sites
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.2 RC2
- Steps to reproduce:
  1. Open jsfiddle.net
  2. Ads by carbon displayed on the bottom left corner
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18784107/c9594290-8187-11e6-9a76-0239fc365359.png)
- Any related issues:

**Comment by Jacalz** [comment]
Is this issue still relevant? I can not reproduce it...

**Comment by bsclifton** [comment]
Also unable to repro. Closing issue- let's re-open if ads show up again 😄
