### ISSUE TITLE
Css Cached files

### ISSUE THREAD

**Issue by LoloIrie** [brave/browser-laptop#423]
No way to refresh page without using the cache !?
Windows release

**Comment by bbondy** [comment]
The view menu (accessible with alt on Windows) has both Reload and Clean Reload. I think that covers what you're asking. Please re-open if not.

**Comment by LoloIrie** [comment]
Oh I was blind, sorry. It's fine :)

**Comment by luixxiul** [comment]
The thing is you cannot notice there it is, IMHO.

**Comment by LoloIrie** [comment]
Using standards shortcuts would probably help (F5 vs CTRL+F5 like Chrome)
https://support.google.com/chrome/answer/157179?hl=en

**Comment by luixxiul** [comment]
cf: #1255 cc:@bbondy
