### ISSUE TITLE
On address bar, how delete a URL suggestion? (chromebook)

### ISSUE THREAD

**Issue by pfister** [brave/browser-laptop#4230]
For the Brave browser, how does a user delete an unwanted URL suggestion from the address bar.  

Need a solution that doesn't involve the 'delete' key because I am using a chromebook running Unbuntu linux. Chromebooks do not have a 'delete' key!

- Platform (Chromebook running Ubuntu):
- Brave Version: 0.11.5

**Comment by bbondy** [comment]
You can remove things from about:history as well.
