### ISSUE TITLE
Right clicking on bookmarks toolbar gives window menu instead of bookmarks menu

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4232]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If you right click on the bookmarks toolbar in an open space (not on top of a bookmark) it shows the windows system menu instead of the bookmarks toolbar menu.

**Expected behavior:**
You should get options like add bookmark etc.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7

- Brave Version:
master tip

- Steps to reproduce:
    1. Show bookmarks toolbar
    2. Right click on an open space
    3. Notice it shows the window system menu instead of bookmarks context menu.

- Screenshot if needed:
<img width="333" alt="screenshot 2016-09-23 07 51 20" src="https://cloud.githubusercontent.com/assets/831718/18784864/dbe19e8c-8162-11e6-8aa1-ea00227a4d30.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/3036
#4171

**Comment by luixxiul** [comment]
Basically this seems to be the same issue as #4171

**Comment by bbondy** [comment]
OK I moved that into 0.12.2 too
