### ISSUE TITLE
While in fullscreen the navbar is not visible

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4234]
As discussed with @bbondy currently on Windows and Linux, while in fullscreen (F11) the navbar is not visible. This makes opening a new page or switching to a new tab a pain, because you have to go out of fullscreen, switch and then go fullscreen again.

How chrome and FF work in that case:

http://webm.land/media/fVzp.webm

I have made PR which replicates exact behaviour but @bbondy wasn't happy how it was working on Mac.

@bradleyrichter Can you please advice how you see this working on different platforms, so I can amend my PR? What do you think will be the best in term of UX?

Thanks

**Comment by bradleyrichter** [comment]
@Sh1d0w I do think the nav bars should be visible on all platforms for full screen mode. The exception is for full-screen video playing where NO nav bars should be shown. 

If you fix changed mac, then can you try to exclude mac from the change?

**Comment by Sh1d0w** [comment]
Yes Brad already did that. Can you please discuss this with Brian and you
can also test my PR which is ready now.
