### ISSUE TITLE
Min, max, and close, and 🍔 buttons don't work on Windows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4236]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Min, max, and close buttons don't work

**Expected behavior:**
Min, max and close buttons should work.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7

- Brave Version:
0.12.2RC2 

- Steps to reproduce:
    1. Open Brave on Windows 7
    2. Click the x button to close the window
    3. Nothing happens.

- Screenshot if needed:
The screenshot doesn't show it well, but this is me hitting the x button 20 times.
<img width="93" alt="screenshot 2016-09-23 07 58 28" src="https://cloud.githubusercontent.com/assets/831718/18785689/9dad2a3c-8167-11e6-9c42-d0c51797e269.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/3036

**Comment by bsclifton** [comment]
Reproduced- only happened when magnification was set to 150%
