### ISSUE TITLE
Tabs/URL font size

### ISSUE THREAD

**Issue by pdinna** [brave/browser-laptop#4237]
I would like to have the freedom to tweak the size of tab and url fonts. At the moment they appear way too small for my comfort.

- Platform: Ubuntu 16.04

- Brave Version:

Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

**Comment by luixxiul** [comment]
Duping to #2469
