### ISSUE TITLE
Bookmark import shows success even if there's nothing to import

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4242]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmark import shows success even if there's nothing to import

**Expected behavior:**
Appropriate message should be shown depending on if there are bookmarks available to import or not

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 RC2

- Steps to reproduce:
    1. Click on import browser data
    2. Select Edge make sure there are no favourites/bookmarks in edge
    3. Click on Import, Shows successfully imported even though there is nothing to import from Edge

- Screenshot if needed:
![bookmrk](https://cloud.githubusercontent.com/assets/17010094/18792105/223573a0-81ad-11e6-946f-50dcc6a9a66e.gif)

- Any related issues:

**Comment by bbondy** [comment]
I think that's ok, the operation was successful, but it operated on no data.  Marking as wontfix
