### ISSUE TITLE
Right click on draggable areas on some platforms shows system menu

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4244]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
I suspect this is a Windows only issue (no other platforms use the electron frameless style). If you right click on a draggable area, you'll get the system menu.

This is [expected behavior on some platforms per the docs](http://electron.atom.io/docs/api/frameless-window/) but it's not ideal.

**Expected behavior:**
We should be able to capture this event and show our own custom menu.

**This will require a change to electron**\- the current behavior (per the docs link above) does not have any flexibility. Draggable areas will show the system menu.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All Windows versions
- Brave Version:
  0.12.2 and newer
- Steps to reproduce:
  1. Launch Brave
  2. Right click on any draggable area
     3. Notice the system menu
- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18737417/dbe412c6-80cb-11e6-9e93-a2f727b41b4a.png)

<img width="333" alt="screenshot 2016-09-23 07 51 20" src="https://cloud.githubusercontent.com/assets/831718/18784864/dbe19e8c-8162-11e6-8aa1-ea00227a4d30.png">
- Any related issues:

**Comment by Sh1d0w** [comment]
@bsclifton I use my custom frameless build of Brave (the original one by me) on Linux and this is not reproducible, so yes it seems like windows only issue. Just to mention it if it helps :)

**Comment by alexwykoff** [comment]
closing as duplicate of https://github.com/brave/browser-laptop/issues/4171

**Comment by luixxiul** [comment]
Actually this covers both #4171 and #4232 instead of being just a dupe of the former.

**Comment by bsclifton** [comment]
Reopening- there is nothing we can do about the behavior at the moment, as it's expected and documented behavior per electron.

However, we can consider making changes to electron to override or change this behavior.  This issue is intended to track our efforts investigating that (and would likely be dependent on an electron PR being accepted before it can be closed).

**Comment by bsclifton** [comment]
The solution to this might be to intercept the `WM_SYSCOMMAND` event in Muon and look through registered menus which have an associated RECT (that is up to the user to register). If no applicable ones are found, THEN do the default behavior (showing the borderline-useless system menu)
(for more info see https://msdn.microsoft.com/en-us/library/windows/desktop/ms646360(v=vs.85).aspx)

**Comment by bsclifton** [comment]
This unfortunately is not an issue we'll be able to address before moving to [brave-core](https://github.com/brave/brave-browser). When moving to brave-core, we'll be using the Chromium UI instead of a custom HTML/JavaScript UI we maintain ourselves (via Muon), so this issue will be resolved
