### ISSUE TITLE
Ledger view counter is incrementing on 404 pages

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4246]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While verifying https://github.com/brave/browser-laptop/pull/4032 and https://github.com/brave/browser-laptop/issues/3759 it was found that the page counter was incrementing on 404 pages. 

**Expected behavior:**
If a user visits a site and receives a unacceptable status code per https://github.com/brave/browser-laptop/issues/3759, the timer AND the counter should not be effected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.2 rc2

- Steps to reproduce:
1. Visit https://clifton.io
2. Stay on page for a while
3. Confirm time spent is incremented
4. Visit https://clifton.io/404
5. Stay on page for a while
6. Confirm time spent is not incremented and that the view counter is not incremented

- Screenshot if needed:
<img width="532" alt="screen shot 2016-09-23 at 2 40 26 pm" src="https://cloud.githubusercontent.com/assets/1434040/18799152/bb3dd1ee-819b-11e6-9ce3-f1db6e9b5104.png">

- Any related issues:

**Comment by bbondy** [comment]
moving to 0.12.3

**Comment by alexwykoff** [comment]
could not reproduce, closing

**Comment by bsclifton** [comment]
May have been fixed w/ https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5
