### ISSUE TITLE
Middle and right mouse buttons stop working

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#4248]
**Did you search for similar issues before submitting this one?:** I found two previously closed issues with similar problems although I can't find any recent ones that match this. #4171 #662

**Describe the issue you encountered:** Both the middle and right mouse buttons stop interacting with web pages and the right mouse button stops working altogether and won't allow you to open the context menu for any of the toolbars.

**Expected behavior:** Right mouse should open the context menu for the web page or toolbar that you are clicking on, and middle mouse opens the selected link in a new tab.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.1
- Steps to reproduce: The issue is completely random, although it often occurs after you've been using the browser for a period of time and haven't closed the window.
- Any related issues: #4171 #662

**Comment by bsclifton** [comment]
@ghost is this still an issue?

**Comment by bsclifton** [comment]
Closing this issue for now (original poster has a deleted account, can't provide more info). If you also encounter this issue, please let some more details and re-open.  Thanks! :smile:
