### ISSUE TITLE
Middle click on web link inside a Twitter tweet causing Brave to completely close vs. open link in new tab

### ISSUE THREAD

**Issue by scunliffe** [brave/browser-laptop#425]
I'm still trying to work out the specific scenario(s) that triggers this and will update once I've run more tests.

Note this is on Windows 7 and the behavior is as if I had clicked ALT+F4 to close the browser.

On Twitter.com:

Middle click works fine on:
- trending links (left panel)
- @username links (anywhere)
- personal links (top left, tweets, followers, following)

Middle click is *closing* the browser on:
- Web links within tweets

Although I noted this as "closing" the browser... I'm suspecting this is actually a crash.

**Comment by scunliffe** [comment]
This also occurs in Gmail, when I get a Facebook notification email (e.g. about a comment to a post)... the big blue "View on Facebook" button if middle-clicked will close/crash? the browser too.
(I'm not sure if this is caused by the same issue, or unrelated)

**Comment by DocWatson** [comment]
I'm having a similar issue with links in Gmail. On Windows 10. The issue occurs if I left click on a link or middle click. However, if I right click and "open in a new tab" the link opens without issue.

**Comment by jairomtzant** [comment]
I am using GMail and I get the same but using Shift + Right Click.

**Comment by bbondy** [comment]
I think this is working in 0.7.12, can someone confirm?

**Comment by DocWatson** [comment]
Just updated. No problems on my end!

**Comment by bbondy** [comment]
Great! Closing.
