### ISSUE TITLE
feature request: support HLS and email

### ISSUE THREAD

**Issue by chovy** [brave/browser-laptop#4259]
feature request: support HLS natively (like safari) and let me configure mailto: links to goto tuta.io

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/feature-request-support-hls-and-email/10170

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
