### ISSUE TITLE
Edited information of bookmark does not appear on bookmark dialog via star icon

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4260]
**Describe the issue you encountered:** The edited information (title and URL) of bookmark does not appear on bookmark dialog opened via star icon. This issue does not happen if you click the icon on the toolbar to select Edit Bookmark.

**Expected behavior:** The edited information (title and url) of bookmark should be filled in these input fields.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2 RC3
- Steps to reproduce:
  1. Open #4255
  2. Click the star icon next to the url bar
  3. Edit Title and click Save
  4. Click the star icon again
  5. The initial title appears instead of the edited one
- Any related issues:

Please set a milestone if necessary.

**Comment by jonepatr** [comment]
I can confirm that it does the same thing on macOS. It's not only the title, but the whole add/edit bookmarks window doesn't update when opened a second time.

**Comment by bbondy** [comment]
To fix this we need to first try to find the information in appState sites, and if it is not found then use the current frame.
https://github.com/brave/browser-laptop/blob/master/js/components/navigationBar.js#L42

**Comment by jonepatr** [comment]
I'll give it a go, to try to fix this!

**Comment by NejcZdovc** [comment]
Should be fixed with #9978
