### ISSUE TITLE
Alt-menus on menu bar do not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4261]
**Describe the issue you encountered:** Alt-menus on menu bar do not work.

**Expected behavior:** They should work.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC3

- Steps to reproduce:
    1. Show the menu bar
    2. Click "File"
    3. Click "New Tab"

- Any related issues: #3036

**Comment by bsclifton** [comment]
Investigating... this was working, but broke after this commit:
https://github.com/brave/browser-laptop/commit/35de6cf76a3cf95b6c8cda5179c661242b747a01

**Comment by bsclifton** [comment]
Confirmed it works if I revert 35de6cf76a3cf95b6c8cda5179c661242b747a01. Checked with @bridiver and there wasn't any intended change. Will continue investigating tomorrow

**Comment by bridiver** [comment]
yea, not sure what the issue is, but I'm just going to revert it for now

**Comment by luixxiul** [comment]
reverting 35de6cf fixes both #4262 and #4263 too

**Comment by bbondy** [comment]
@bridiver

**Comment by bbondy** [comment]
reverted here:
https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5
