### ISSUE TITLE
Regression: Block Scripts does not work on brianbondy.com

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4262]
**Describe the issue you encountered:** Block Scripts does not work on brianbondy.com

**Expected behavior:** It should work

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC3

- Steps to reproduce:
    1. Clear your brave folder temporarily
    2. Open the browser
    3. Open about:preferences
    4. Enable "Block Scripts"
    5. Open a new tab 
    6. Go to https://brianbondy.com/

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
reverted here:
https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5
