### ISSUE TITLE
Regression: AudioContext Fingerprint protection cannot be disabled

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4263]
**Describe the issue you encountered:** AudioContext Fingerprint protection cannot be disabled from both the bravery panel and preferences

**Expected behavior:** It should be able to be disabled

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2 RC3

- Steps to reproduce:
    1. Go to https://audiofingerprint.openwpm.com/
    2. Disable fingerprinting protection from bravery panel
    3. Click "fingerprint me"
    1. Go to https://audiofingerprint.openwpm.com/
    2. Open about:preferences#shield, clear the exception, and disable fingerprinting protection
    3. Click "fingerprint me"

- Any related issues:

**Comment by bbondy** [comment]
reverted here:
https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5
