### ISSUE TITLE
Bookmarks can only be saved on Bookmarks Toolbar

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#4265]
**Describe the issue you encountered:**
Clicking the "save bookmark" icon in the URL bar saves all bookmarks to the Bookmarks Toolbar

**Expected behavior:**
Drop-down would allow choosing a folder

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Slackware

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Click "save bookmark" icon
    2. Dropdown appears with "Bookmarks Toolbar" only
    3. Bring up bookmarks manager and manually drag bookmark into proper folder

**Comment by luixxiul** [comment]
duping to #4202
