### ISSUE TITLE
Make autofill be tab modal and not window modal

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4266]
**Expected behavior:** Modal window on about:autofill should not be closed with a mouse click on the outside of the window.
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: 0.12.2 RC3
- Steps to reproduce:
  1. Click add address on about:autofill
  2. Fill some data in a modal window
  3. Click on the outside of the modal window
  4. The data is cleared
- Any related issues:

**Comment by bbondy** [comment]
I think that is expected for all of our modal windows if you click outside of them. Let me know if you strongly disagree but I'll close this as wontfix for now.

**Comment by luixxiul** [comment]
I just assume there would be some users disappointed if they filled data and saw the data lost by clicking/tapping the outside of the modal window unintentionally.

**Comment by bbondy** [comment]
I re-opened but updated to be tab modal instead of window modal. The use case is for example a user wants to lookup information to fill it in in another tab.   This isn't high prior though.
