### ISSUE TITLE
tracking issue: regressions caused by commit 35de6cf

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4267]
#4261 
#4262 
#4263 

Per @bsclifton on https://github.com/brave/browser-laptop/issues/4261#issuecomment-249353817
> Confirmed it works if I revert 35de6cf76a3cf95b6c8cda5179c661242b747a01. Checked with @bridiver and there wasn't any intended change. Will continue investigating tomorrow

https://github.com/brave/browser-laptop/commit/35de6cf76a3cf95b6c8cda5179c661242b747a01 has been reverted for a moment.

**Comment by bbondy** [comment]
was reverted here:
https://github.com/brave/browser-laptop/commit/1d65e0bc9c7f9a3e36ef33ce3ef1e793520918b5

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/pull/4250 is the PR which 35de6cf was merged.

**Comment by bsclifton** [comment]
may have also broke https://github.com/brave/browser-laptop/issues/4246 (works after revert)

**Comment by luixxiul** [comment]
#4242: I noticed later that NoScript could not be disabled not only at brianbondy.com but also all websites.
