### ISSUE TITLE
tabs not loading; about:error tabs proliferating

### ISSUE THREAD

**Issue by thefish30** [brave/browser-laptop#4268]
**Did you search for similar issues before submitting this one?**  Yes, could not make head nor tails of results.  I am afraid most of this site is greek to me, I got here via Brave's help>report an issue.

**Describe the issue you encountered:**
Upon launch, pinned tabs do not load, about:error tabs start spawning and continue doing so as long as the app is open.  All tabs are blank.  Most menu items return blank tabs or nothing.  About gets me the correct about popup.  Check for downloads gets a message that there are none currently.

**Expected behavior:**
tabs, websites should load as normal.  empty error tabs should not spawn

- Platform: Win10

- Brave Version: 0.12.1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

This issue occurred immediately following an incident wherein the keyboard got sat on, resulting in filterkeys setting being inadvertently turned on.  Not knowing why my keyboard was not responding, I tried various troubleshooting, swapping keyboards etc.  Once the problem was resolved, Brave was the only thing still misbehaving.

**Comment by Liunkae** [comment]
Hello thefish30! This issue was fixed recently (with #4036/ e33b55d) and will be released in version 0.12.2 in the next few days.
