### ISSUE TITLE
Input Element of Address Bar too Narrow

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4269]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

At some widths, the input element within the address bar is too narrow.

**Expected behavior:**

The input element of the address bar should fit nicely at all widths.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.2

- Steps to reproduce:
    1. Navigate to http://brave.com
    2. Reduce width of Brave window
    3. Note that even a short URL can be truncated unnecessarily

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/815158/18809999/06a89c78-8240-11e6-8b4f-a6c00ac16489.png)

Related Issues: #4241 

Relevant LOC: […/less/navigationBar.less#L53](https://github.com/brave/browser-laptop/blob/e36362e03dbf7fb3bc08e5c86b9b4c57afa5ffe8/less/navigationBar.less#L53)

**Comment by jonathansampson** [comment]
@bsclifton What do you think about using flexbox here? Even at its narrowest, the address bar seems large enough to accommodate a favicon, url, and page load-time.

**Comment by luixxiul** [comment]
Duping to #4170
