### ISSUE TITLE
Update favicon of imported items

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#4270]
The imported items(bookmarks, history) should have favicon

**Comment by luixxiul** [comment]
on slack
> newly fetched favicons cannot be replaced, once `bookmarkFile` class was added to `bookmarkFavicon`

**Comment by luixxiul** [comment]
refetching and replacing of favicons should be enabled. timing: on revisit, restart, hiding and showing the bookmarks toolbar

**Comment by alexwykoff** [comment]
moved to 0.12.3 this shouldn't block a release
