### ISSUE TITLE
Bookmarks toolbar render is off when '>>' expander is used.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4272]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After importing a LOT of bookmarks, an expander is added to the toolbar '>>' . When a user attempts to click on the expander, the view is rendered quite far to the left.

**Expected behavior:**
The user should be able to see the other bookmark options and navigate the view without issue.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 x64

- Brave Version:
0.12.2 RC4

- Steps to reproduce:
    1. Import a lot of bookmarks with no hierarchy. (or add a lot of bookmarks)
    2. Click on the '>>' expander when it is displayed.

- Screenshot if needed:
<img width="1006" alt="screen shot 2016-09-24 at 2 14 53 pm" src="https://cloud.githubusercontent.com/assets/1434040/18810786/56bc4006-8264-11e6-8a16-1f8ed6ee5eb6.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/3527

**Comment by bradleyrichter** [comment]
similar thing happens with BM bar folder menu:

![image](https://cloud.githubusercontent.com/assets/13509546/18844046/77594436-83d0-11e6-8cc9-c04d2ae3141f.png)

**Comment by bbondy** [comment]
@bradleyrichter I think there's another bug for that one.
@alexwykoff do you have a particularly long URL or title that's making it that long? Can you screenshot that part? Maybe we just need a max width?

**Comment by alexwykoff** [comment]
After a quick search of bookmarks, this would seem a likely culprit:
https://fundersclub.com/blog/2016/08/03/finding-your-cofounder/?utm_campaign=Mattermark+Daily+Weekend+Edition&utm_source=hs_email&utm_medium=email&utm_content=32890852&_hsenc=p2ANqtz-_aVCVozPQZiC3LoHaqCw20N0BDLvY2scuWUCGL6FxBywqPFHvvvCzJcT-fQpU-cFJwyAC0xNl8Ap0F4siam39xvfgPXA&_hsmi=32890852
