### ISSUE TITLE
Flash notification bar appears twice during loading of siriusxm.com

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4276]
**Describe the issue you encountered:** Flash notification bar appears twice during loading of siriusxm.com

**Expected behavior:** It should only appear once
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2 RC4
- Steps to reproduce:
  1. Go to https://player.siriusxm.com/#/login
  2. Flash notification bar appears
  3. Flash notification bar disappears
  4. The browser is redirected to https://player.siriusxm.com/errorpagehandler.html?type=flash
  5. Flash notification bar appears again
- Any related issues: #4195

wontfix?

**Comment by jkup** [comment]
I can see this too, but I'm not sure what we can do about it. It seems like our bug in a sense that the page redirects before the user can select yes or no from the notification bar. I'm happy to work on this if someone has an idea of how to fix it!
