### ISSUE TITLE
Drag-and-drop style clicking on submenu should be enabled again

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4277]
**Expected behavior:** Drag-and-drop style clicking on submenu should be enabled again. This has been disabled since #3854 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2 RC4
- Steps to reproduce:
  1. Click "File" on menubar
  2. Keep pushing the right or left mouse button
  3. Move your mouse cursor anywhere
  4. Stop pushing the mouse button on "New Tab" in the submenu of "File"
  5. New tab should be opened

This works until 0.12.1 where the windows native menu bar is used.
- Any related issues:

**Comment by lucidNTR** [comment]
also affects menus in other places that affect macOS too. Eg back button history menu.
- navigate to a page and click two links to build a history
-  long click back button and keep the mouse down while dragging to the history entry you want to go to.
- let the mouse button go.
- nothing happens

**Comment by bsclifton** [comment]
@lucidNTR good eye- fixing that behavior is captured with https://github.com/brave/browser-laptop/issues/2891 :smile:
