### ISSUE TITLE
LastPass : Cannot recover if main password is lost

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4278]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When trying to recover a Lastpass account, their system looks for stored values and an installed extension with the browser. Lastpass' system was unable to recognize those items existed with Brave.

**Expected behavior:**
A user should be able to recover if they lost their main password.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Discovered on OS X
- Brave Version:
  0.12.2 RC4
- Steps to reproduce:
  1. Navigate the password recovery system of Lastpass. Click on the link on the recovery page.
- Screenshot if needed:
  <img width="432" alt="screen shot 2016-09-24 at 9 52 55 pm" src="https://cloud.githubusercontent.com/assets/1434040/18812720/68c93afe-82a2-11e6-918e-109564e28a06.png">
  <img width="650" alt="screen shot 2016-09-24 at 9 53 27 pm" src="https://cloud.githubusercontent.com/assets/1434040/18812721/a5759f2e-82a2-11e6-982a-4ddb689eaa99.png">
- Any related issues:

**Comment by alexwykoff** [comment]
cc @yan @bbondy my suspicion is that this is our privacy methods biting back a bit, any suggestions on how to investigate further?

**Comment by luixxiul** [comment]
@diracdeltas
