### ISSUE TITLE
Large downloads not showing percentage 

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#4279]
Sorry for brevity I'm away from my computer but with large downloads like a google drive folder we don't show completion percent.

**Comment by Aeyoun** [comment]
You have to provide an exact URL. Without a Content-Length header in the server response, Brave wouldn’t know the total size and can’t show a completion percentage. It’s not a bug unless the header is indeed and Brave still doesn’t show a completion percentage.

**Comment by bbondy** [comment]
yep pls look in dev tools for the HTTP headers to prove this is a bug.  Otherwise we should close this, Thanks!

**Comment by jkup** [comment]
@Aeyoun I think you are right! Closing now, thanks for explaining!
