### ISSUE TITLE
Import data from other browsers

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#428]
Is the fetaure unimplemented yet or it should be working and it is a bug?

**Comment by bbondy** [comment]
Yes this is still pending implementation. Thanks for posting.

**Comment by asadotzler** [comment]
A suggestion: Implement this as a service that *syncs* to other browsers so that Brave is always the most up to date. Your users will be using multiple browsers, at least for a while, so make their other browser feel like the one that's missing recent additions by being always up to date on things like history, bookmarks, saved passwords and forms, etc.

**Comment by jcsmesquita** [comment]
+1 this would definitely encourage me to migrate to brave sooner! Great work by the way guys!

**Comment by bbondy** [comment]
Import from HTML export for bookmarks done here:
https://github.com/brave/browser-laptop/issues/940

Leaving this open though since it contains a lot of other sub-tasks.

**Comment by smithkl42** [comment]
FWIW, this is probably the main thing keeping me from using Brave as my default browser. The sync-across-devices feature in Chrome is really helpful, and (so far as I know) Brave doesn't have it yet. Other than that, Brave is so much faster and more stable that it's really what I would like to use.

**Comment by darkdh** [comment]
[PR] (#4049) is on its way. It supports importing bookmarks, history, cookies from other browsers along with new way of importing from bookmarks html.

**Comment by Kainzo** [comment]
So... is it possible to have your passwords retrieved from Chrome? cause I want to move to Brave to break up with Google...

**Comment by darkdh** [comment]
you can see the tracking ticket here
https://github.com/brave/browser-laptop/issues/7071

**Comment by fermulator** [comment]
In the "import browser data" (`v0.19.134-1`), don't see the ability to import Firefox "saved tab state", I presume that is not yet implemented? (can't find an open ticket for it either)
