### ISSUE TITLE
regression: update notification message is not localized

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4282]
**Describe the issue you encountered:** Update notification message is not localized.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18813126/aab72e0a-8327-11e6-9980-631234ea9017.png)

**Expected behavior:** 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2 RC4
- Any related issues:

**Comment by luixxiul** [comment]
It is not reproduced after doing the update test. Race condition?

**Comment by bbondy** [comment]
did it appear very close to startup or something?

**Comment by luixxiul** [comment]
Sorry, I don't remember. It can be so. I will let you know STR if I found one

**Comment by bbondy** [comment]
I removed regression label until you can confirm if it happens on each run or not. For me I just tried it with French and it was translated.

**Comment by luixxiul** [comment]
I haven't seen this for a long time. I'm going to close this. I'll reopen if I see this happening again.
