### ISSUE TITLE
Maximum width of bookmark items should be higher

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#4283]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Bookmark items in the bookmarks bar are truncated too early. The issue is especially noticeable when favicons are enabled. For example, the string "Apple Apple Apple" with a favicon is truncated in Brave but not Firefox or Safari. The maximum width of bookmarks should be higher.

The maximum width is set [here (bookmarksToolbar.less -> `--bookmark-item-max-width`)](https://github.com/brave/browser-laptop/blob/f51e1a3456bc9d468f388749ae9172e789d5c42b/less/bookmarksToolbar.less#L8).

**Expected behavior:**
Bookmark items should only be truncated if the entire bookmarks bar is filled.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS 10.12
- Brave Version:
  0.12.1
- Steps to reproduce:
  1. Create a bookmark and add it to the bookmarks bar.
  2. If necessary, edit the bookmark's title to be at least three normal sized words (e.g. Apple Apple Apple).
- Screenshot if needed:
  ![screenshot](https://cloud.githubusercontent.com/assets/19424103/18813443/afa8fc9e-82bf-11e6-8606-8030fed8f753.png)
- Any related issues:
  None.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/should-the-max-width-of-bookmark-items-should-be-larger/10180

Let's reopen after we receive enough feedback there to decide how much is best 😄
