### ISSUE TITLE
Unable to smooth scroll on sites when link opened from a different site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4285]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
~~Unable to scroll on PetaPixel.com when link opened from a different site~~ Unable to smooth scroll on sites when link opened from a different site

**Expected behavior:**
Should scroll properly irrespective of how its opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 RC4

- Steps to reproduce:
    1. ~~Visit FB page of PetaPixel, open any link posted on their timeline~~
    2. ~~Open the tab which was opened, try scrolling using mouse wheel, with just one turn jumps to the end of the page~~
    3. ~~Close the tab manually enter the site and open any article able to do smooth scrolling using mouse wheel, doesn't jump to the end of the page~~

- Screenshot if needed:
![petapixel](https://cloud.githubusercontent.com/assets/17010094/18813797/4716a0d4-82fe-11e6-9f85-d781fb9d7978.gif)

- Any related issues:

**Edit**: Issue found on any site that is opened in a new tab. Cannot scroll up using mouse wheel. When trying to scroll down jumps to the end of the page. When at the middle of page if you try scrolling up still scrolls down.

**Comment by wmeyer48** [comment]
Removing the site tracking string from the URL and hitting Enter to refresh the page will enable proper operation.

**Comment by bsclifton** [comment]
This sounds like a duplicate of https://github.com/brave/browser-laptop/issues/4472

@wmeyer48 are you on Windows? Apologies for the bug :frowning_face:

**Comment by wmeyer48** [comment]
I am. Sorry if I commented on the wrong issue. Found it, and tt fit my
observations. Windows 10 and 64 bit.

**Comment by srirambv** [comment]
@bsclifton Yes this issue was found while doing webcompat testing on Petapixel and I reported it as only on that site then realized it   was happening on all newly opened tabs and aded the details as edit. Closing in favor of #4472 as it is being used to track the issue.

**Comment by bsclifton** [comment]
@wmeyer48 thanks! and no worries- when I had asked, I was still characterizing the issue at that time (wasn't sure if it was Windows only) :smile: We're still digging in on it- it definitely appears to be Windows only.

You can follow the issue over at https://github.com/brave/browser-laptop/issues/4472 if you're not already
