### ISSUE TITLE
Brave Payments should have a dev mode using testnet Bitcoin

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#4286]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing/developing for Brave Payments, one must buy at least $5 of Bitcoin to get started. 
Every time browsing data is updated with the Ledger server, >= $5 of Bitcoin must be contributed again.

**Expected behavior:**
For development purposes, one should be able to use testnet Bitcoin, which can be obtained on demand from a testnet faucet (without signing up with Coinbase, etc), saving time and money for those who want to contribute to Brave Ledger development.

- Affects all Platforms and Brave versions

- Steps to reproduce: 
    1. Open Preferences -> Brave Payments
    2. Enable Payments and create a Wallet. 
    3. Observe minimum funding amount is $5, and real Bitcoin is required (even in development mode).

**Proposed solution:**
The current Ledger server code supports testnet if run with BITGO_ENVIRONMENT=test , with a BITGO_TOKEN obtained from test.bitgo.com . 
A second Ledger instance with these settings could be run, say on ledger-test.brave.com . (I am running such an instance privately now for my own testing.)

It then only takes a couple of tiny updates to ledger-balance, ledger-client, and browser-laptop to support an environment variable allowing testnet bitcoin to be used. 

Once this is done, here's what it looks like to setup a fresh install of Brave with a " >$3,000 " deposit in < 2min by visiting a testnet faucet webpage:
![brave_with_testnet_coin_example](https://cloud.githubusercontent.com/assets/6969859/18813854/935e4870-82bd-11e6-830a-6fedef043faf.gif)

After that you can test Brave Payments 600 times without thinking of funding again :-).

**Comment by willy-b** [comment]
FYI, there is now a WIP PR in brave/ledger which should make it much easier to run a testnet server (https://github.com/brave/ledger/pull/8)

Partial instructions for running a Ledger server in AWS using docker-machine with that branch are here:
https://github.com/willy-b/ledger/blob/d4f88a9be2735ab96069838a836aaf3a00c53ae9/docker-machine-example.md

**Comment by willy-b** [comment]
Availability is not guaranteed, but I will be running a Ledger server using **testnet** bitcoin at ledger-testnet.entropi.info most of the time, see http://ledger-testnet.entropi.info/documentation to test availability. 

#4297 shows how to point Brave at the testnet Ledger server.

**Comment by mrose17** [comment]
@willy-b - it seems to me that if the browser uses a ledger server using testnet, then that ledger server will be telling it where to get the server list for balances (GET /v1/balance/providers), and the ledger server will be talking to testnet as well.

if so, then to resolve this we really need to add an option that tells the browser what ledger server to boot from, right?

**Comment by willy-b** [comment]
@mrose17, my thoughts exactly. There's an open PR #4297 for letting an ENV variable "LEDGER_SERVER_URL" tell the browser what Ledger server to use. 

I think an ENV variable is sufficient rather than adding this to the UI since it is really is only useful for development (We don't actually want to pay Publishers testnet coin :-) ).

**Comment by willy-b** [comment]
With the resolution of https://github.com/brave/ledger-balance/issues/1 and https://github.com/brave/browser-laptop/issues/4297 I'm going to mark this closed. 

Anyone can use testnet coin to test Ledger features now by running Brave with the environment variable "LEDGER_SERVER_URL" set to point to a Ledger server running against Bitcoin testnet (e.g. "http://ledger-testnet.entropi.info" ). 

LMK if anyone has difficulty doing this. Thanks.

**Comment by luixxiul** [comment]
@willy-b thanks for your contribution! If you don't mind, would you please create [our wiki](https://github.com/brave/browser-laptop/wiki) page to explain how to use testnet faucet webpage? That would help a lot of people who have not followed this thread :-)

**Comment by willy-b** [comment]
will do @luixxiul

**Comment by willy-b** [comment]
Wiki page added here: https://github.com/brave/browser-laptop/wiki/Using-Brave-Payments-with-Testnet-Bitcoin

**Comment by luixxiul** [comment]
Lovely! thanks :+1:
