### ISSUE TITLE
Payments Ledger table row ordering is inconsistent

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#4287]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
On the Brave Payments tab, compare the ranking by time and % columns: ![paymentstable_percentagesrankdoesntmatchtimerank](https://cloud.githubusercontent.com/assets/6969859/18814056/8e65c572-82c3-11e6-9160-46987dce11fb.png)
It is counterintuitive that they do not match.

**Expected behavior:**
The ranking of a row should be consistent with ranking by time and % columns.

- Platform (Win7, 8, 10? macOS? Linux distro?):
  Ubuntu 14.04
- Brave Version:
  Recent master (f51e1a3456bc9d468f388749ae9172e789d5c42b)
- Steps to reproduce:
  1. Enable Brave Payments
  2. Browse several pages for different lengths of time, >1min
  3. Open Preferences->Payments
  4. Observe that sometimes ranking by "Time Spent" column doesn't agree with "%" column (lower time spent has higher "%" or vice versa)

**Comment by Aeyoun** [comment]
I have the same problem. Not sure if it is a problem, or just flawed design that doesn’t communicate all the information/metrics/whatever that determines the percentage.

**Comment by luixxiul** [comment]
Another example:

<img width="616" alt="screenshot 2016-09-27 2 13 41" src="https://cloud.githubusercontent.com/assets/3362943/18844391/11571338-8458-11e6-8da5-55a8c563e14f.png">

**Comment by mrose17** [comment]
the issue is that the `%`-values are rounded, obviously you didn't spend `0%` of your time on the second site, but something like `0.xxxx %`

there has been some discussion as to whether the percentage column is useful or not.

**Comment by Aeyoun** [comment]
> there has been some discussion as to whether the percentage column is useful or not.

I agree; it’s just duplicating the rank column with less precision. The only thing I would like to see to supplement the ranking is displaying approximately how many µBTC of my funds the website will receive.

**Comment by willy-b** [comment]
this issue is out of date, closing
