### ISSUE TITLE
Opening about:preferences in two windows causes graphics corruption

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#4289]
1. Open a window and open up the Preference tab
2. Open another window and do the same

Screenshots showing tabs and UI from the first window appearing instead of the preferences screen in the second window (kind of confusing). The second screenshot shows what happens if I hover the + button on the tab bar in the second window while the broken preferences screen is open.

![screenshot-1](https://cloud.githubusercontent.com/assets/1102886/18328972/c363332e-7551-11e6-869d-ab4fd22552dd.png)

![screenshot-2](https://cloud.githubusercontent.com/assets/1102886/18328783/aa278ca8-7550-11e6-8a2f-3dc8c37fb022.png)

Fedora 24, Brave 0.12.0-dev.

**Comment by Sh1d0w** [comment]
I can't reproduce this on Fedora 24 with Brave 0.12.1.

**Comment by Aeyoun** [comment]
Neither can I. I foolishly assumed the auto-update check actually did something. Closing.
