### ISSUE TITLE
Brave 0.12.2dev-RC4 crash when closing a tab

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4290]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Brave crash when I try to close a tab

**Expected behavior:**

Just close the tab

- Platform (Win7, 8, 10? macOS? Linux distro?):

Ubuntu 64

- Brave Version: 

Brave: 0.12.2 RC4

- Steps to reproduce:
  
See the video uploaded [Brave crash.ogv.zip](https://github.com/brave/browser-laptop/files/491674/Brave.crash.ogv.zip)

Obs. Brave RC3 works ok.

**Comment by bitcoinuser** [comment]
Terminal appear this: 

![captura de tela de 2016-09-25 10-35-53](https://cloud.githubusercontent.com/assets/1178856/18815558/e13316fe-830b-11e6-975d-81f519e4a4fb.png)

**Comment by bbondy** [comment]
@aekeus can you repro?

**Comment by aekeus** [comment]
I cannot recreate on RC4. This may be related to something I saw earlier though. The browser would get in a state where closing a tab would crash the browser as reported. Clearing the session fixed the problem. This was an intermittent issue and difficult to reproduce.

**Comment by bitcoinuser** [comment]
See the images:

![captura de tela de 2016-09-27 20-14-00](https://cloud.githubusercontent.com/assets/1178856/18895326/2c831ade-84ef-11e6-8838-ae236246b374.png)

![captura de tela de 2016-09-27 20-14-10](https://cloud.githubusercontent.com/assets/1178856/18895332/33edbc2a-84ef-11e6-9613-c63549f63a54.png)

![captura de tela de 2016-09-27 20-14-17](https://cloud.githubusercontent.com/assets/1178856/18895336/39c6931a-84ef-11e6-9a85-1e780e58bc6d.png)

**Comment by mariuspo** [comment]
Same bug in version 0.12.1, in Ubuntu 16.04. Brave also crashes when trying to bookmark a page.

Terminal message when crashing after closing a tab:
Failed to get crash dump id.
Report Id: OK
Segmentation fault (core dumped)

**Comment by pureooze** [comment]
Same issue for me on versions 0.12.1 - 0.12.3 on OpenSUSE Leap. It started happening after I used 0.12.3. Now even if I roll back to 0.12.1 I cannot close tabs without a crash.

Terminal message:
Failed to get crash dump id.
Report Id: OK
Segmentation fault

**Comment by bitcoinuser** [comment]
For me it's fixed on Brave 0.12.3dev-RC5

Thanks

**Comment by pureooze** [comment]
Yep it seems to work for me too in 0.12.3dev-RC5

**Comment by bitcoinuser** [comment]
Before version Brave 0.12.3dev-RC5, all times I tried to close a tab, it crashed. 
But now I reproduced the crash again. So the problem is still happening but not all time.

**Comment by bitcoinuser** [comment]
RC6 did NOT crash yet. Maybe this bug is fixed. 

If crash again, I'll post here.

Thanks.

**Comment by bbondy** [comment]
Marking as resolved for now.
