### ISSUE TITLE
UX: Strange label “Need to buy Bitcoin outside of the USA?”

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#4292]
“Need to buy Bitcoin outside the USA?” — Well, I don’t know. You tell me!

See the attached screenshot. The label on the first option makes sense to me because I know that it shows something else in the USA. To anybody else, however, the wording is very strange. It also doesn’t really explain what is going on in this dialog nor guide the user towards completing the required steps.

I suggest it be changed to something like “Start by purchasing some BitCoins from an exchange, and then transfer your BitCoins to the wallet address shown below. We recommend so-and-so.  Visit so-and-so.”

It should also mention an amount of BitCoins to purchase and how much that would cost in a local currency (or EUR?). These numbers are important to make the user feel more familiar with BitCoins and their worth in a currency they can relate to. I suggest recommending that the user start with 3 times the minimal monthly contribution so the user will be set up for the first three months. This helps reduce the transaction costs involved with currency exchanges and commits the user to three months. “We recommend you purchase 0,0009 BitCoins (15 EUR) at so-and-so, but you can get started with Brave Payments for as little as  0,0003 BitCoins (5 EUR) per month.” 

The headline is also off, but I’m not sure what can be done to clarify it. (The first option doesn’t transfer funds to Brave, and the second and third option is really the same option.) Maybe “Add BitCoins to your Brave Wallet to get started”

![screenshot](https://cloud.githubusercontent.com/assets/1102886/18816105/78dfd11e-8342-11e6-9f8e-28f3bdcc3049.png)

**Comment by luixxiul** [comment]
> “Need to buy Bitcoin outside the USA?” — Well, I don’t know. You tell me! 

That's the same feeling which I had during a localizaton on transifex.

**Comment by bradleyrichter** [comment]
Fix for this issue:

![image](https://cloud.githubusercontent.com/assets/13509546/19015731/c498c9b4-87be-11e6-9a0c-6411f3ae16a5.png)

**Comment by bradleyrichter** [comment]
Additionally we will add hiding the 3rd box for using the app when the country is not one of the supported Coinbase countries.

**Comment by Aeyoun** [comment]
The dialog needs a complete overhaul. Tell a story. Why am I asked to transfer BitCoins to Brave? What is a Brave wallet? BitCoins? btc wallet? What will all of this accomplish?

The dialog as is assumes familiarity with how Brave works, how BitCoins work, and what all of this is a bout. New users/customers wouldn’t have a clue about any of this.

Not perfect, but this should help lead the user through all the steps:

“To support your favorite websites with Brave Payments, you must first transfer BitCoins to your Brave Wallet.”

1. Purchase some BitCoins with a credit card or bank transfer at a BitCoin exchange. Brave recommends the BTCexchangeName. 
2. Transfer at least 5 USD worth of BitCoins to your Brave Wallet. Enter your Brave Wallet address when your BitCoin wallet/client or the exchange asks for a BitCoin address to transfer your funds into.

**Comment by bradleyrichter** [comment]
@Aeyoun I understood and appreciate your deeper suggestions above. :   )  We will certainly improve this over time. I just need to make a quick improvement for the next release.

As you know, bitcoin is currently used by/understood by a small subset of the world. Even if we try to explain how easy BTC can be, it's still a large jump from a users typical use of currency. Many will run out the door as soon as they think it's required.

We are trying to allow Brave Payments users to pay with credit card and basically skip the BTC process. A new approach (coming soon) will allow for this in most countries as long as their card can be processed.

Of course, we still need to let users who already have BTC and want to transfer some to Brave to do so easily. Getting both flows to work will be challenging so I will certainly need your feedback.

**Comment by jkup** [comment]
Note to self: Title needs to change and Coinbase icon needs to be removed from the footer.

**Comment by bradleyrichter** [comment]
note to @jkup :

- please change QRcode overlay shadow to 

![image](https://cloud.githubusercontent.com/assets/13509546/19137961/cb0ecb06-8b2c-11e6-8d9d-f8b1951c9153.png)

- add app store links to coinbase apps

itunes: https://itunes.apple.com/us/app/coinbase-bitcoin-wallet/id886427730?mt=8

play store: https://play.google.com/store/apps/details?id=com.coinbase.android
