### ISSUE TITLE
Process of Inserting Alt Code Reveals Toolbar

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4295]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Typing certain characters from a Windows machine sometimes requires the use of the <kbd>Alt</kbd> key. _This key is currently configured to toggle the Toolbar._ Holding <kbd>Alt</kbd> and typing <kbd>0133</kbd> on the Number Pad causes the toolbar to be revealed.

**Expected behavior:**

Inserting ALT Codes **does not** cause the toolbar to be revealed.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.2
- Steps to reproduce:
  1. Focus on an input
  2. Hold <kbd>Alt</kbd> and type <kbd>0133</kbd> into Number Pad
  3. Note that toolbar has been revealed
- Relevant LOC: [.../js/components/main.js#L133](https://github.com/brave/browser-laptop/blob/21f0409bfed3eb457d507f62d44448c8c4b51afc/js/components/main.js#L133)
- Screenshot if needed:
- Any related issues:

**Comment by willy-b** [comment]
Does fixing this bug mean pressing Alt will no longer reveal the toolbar? I really like that feature :-)

**Comment by jonathansampson** [comment]
@willy-b, no. I think we should *extend* the functionality to better accommodate the entering of alt codes.

**Comment by jonathansampson** [comment]
Another scenario where this causes issues with with per-window screenshots on Windows.

To take a screenshot of an application window on Windows, you focus that window, hold <kbd>Alt</kbd>, and press <kbd>PrtScn</kbd>. Upon doing this, the window screenshot is copied to your clipboard, and (unexpectedly) the toolbar for Brave is opened.

**Comment by srirambv** [comment]
Also happens when you press Ctrl+Alt+U to view page source and

**Comment by toxiicdev** [comment]
Yea it happens even when you're writing your email and you are going to type @ character (in IT keyboard it is ALT + ;)

**Comment by bsclifton** [comment]
This should be fixed now... one of the problems when I added this was not differentiating between the left (ALT) and right (ALTGR) keys. @toxiicdev are you using the latest Brave version, 0.12.5?  Please let me know

Thanks! :smile:

**Comment by toxiicdev** [comment]
@bsclifton Yep I'm using 0.12.5, I'll try now

**Comment by srirambv** [comment]
Closing the dev console via keyboard shortcut also shows the menu toolbar

![filemenu](https://cloud.githubusercontent.com/assets/17010094/19960187/1ec861f8-a1a3-11e6-9e2d-f8ec9446f91b.gif)

**Comment by jonathansampson** [comment]
@bsclifton For this issue, could we keep a simple record of the last key pressed (`lastKey`), and toggle the toolbar on the `keyup` event when both `lastKey` and `event.key` are both `"Alt"`?

**Comment by bsclifton** [comment]
@jonathansampson that would totally work :smile:

**Comment by jonathansampson** [comment]
This issue was called out on Twitter for being a nuisance when back-forward browsing with the <kbd>ALT</kbd> key: https://twitter.com/livebeef/status/795344401132298240
