### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by johvan** [brave/browser-laptop#430]
Crashes when you try to make a YouTube video full-screen.

**Comment by bridiver** [comment]
Thanks for submitting the issue! What OS and Brave browser version are you using?

**Comment by johvan** [comment]
Windows 7 and the first one.

**Comment by bbondy** [comment]
Please try with the latest build:
https://laptop-updates.brave.com/latest/osx
https://laptop-updates.brave.com/latest/winx64

**Comment by bbondy** [comment]
I'm pretty sure this was just due to an old bug on Windows that has since been fixed.  Closing.
