### ISSUE TITLE
HTTPS count shown even when its disabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4300]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
HTTPS count shown even when its disabled

**Expected behavior:**
Should not show any count when HTTPS is disabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 RC4

- Steps to reproduce:
    1. Visit http://travelchannel.com/video
    2. Disable HTTPS Everywhere from bravery panel
    3. HTTPS Everywhere count is still shown when its disabled.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/18832481/988742b2-83e3-11e6-872c-505f495d75ce.png)

- Any related issues:

**Comment by bbondy** [comment]
cc @diracdeltas that probably means it's not disabling.

**Comment by diracdeltas** [comment]
chromium recently changed their definition of firstPartyUrl, so it can no longer be used as the main frame URL. confirmed that this is fixed by https://github.com/brave/browser-laptop/pull/4145.
