### ISSUE TITLE
URL Bar resizes when refresh/stop button is loaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4303]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
URL Bar resizes when refresh/stop button is loaded

**Expected behavior:**
URL Bar size should remain same 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2. RC4

- Steps to reproduce:
    1. Open a new tab
    2. Type a site name and press enter
    3. When Refresh button is loaded, the size of the URL bar changes

- Screenshot if needed:
![urlbar](https://cloud.githubusercontent.com/assets/17010094/18837365/6eaa79f6-83fb-11e6-9ebf-0a7ca9dbc928.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Haven't investigated well but it may be related with this -> https://github.com/brave/browser-laptop/blob/c95cef9201ccafc233c93c47c9f940177f7eb4bb/less/navigationBar.less#L506-L518

It could be so because extension button and bravery panel button shorten the width of the url bar.

**Comment by srirambv** [comment]
Failing on Ubuntu with 0.12.3dev-RC1 build 
![url](https://cloud.githubusercontent.com/assets/17010094/18889108/4935d5be-84f3-11e6-8339-c0d6d9cab609.gif)

**Comment by bsclifton** [comment]
This happens on macOS also
