### ISSUE TITLE
Right clicking on a bookmark entry in the bookmark submenu should open it in a new tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4313]
**Expected behavior:** Right clicking on a bookmark entry in the bookmark menu should open it in a new tab.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Create a bookmark
  2. Open "Bookmark" menu
  3. Right-click on the bookmark entry
- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul can you provide an example where this is standard behavior?

You can already do this via middle click or cmd/ctrl + click. I believe deviating from the expected behavior would be a bad idea. cc: @alexwykoff @bradleyrichter

**Comment by luixxiul** [comment]
maybe when I posted this the context menu on bookmark was not available... I don't remember exactly what I experienced.
