### ISSUE TITLE
site-specific Bravery settings headers should disappear when the list is empty

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4319]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
HTTPSE is not shown under site-specific Bravery settings. Only comes up when HTTPSE is disabled on a site and when the site specific setting is deleted, HTTPSE doesn't show under the site specific settings

**Expected behavior:**
Should always shows the label under Bravery settings similar to the other ones

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.2 RC4

- Steps to reproduce:
    1. Open preferences page about:preferences#shields
    2. HTTPSE not listed under Saved Site Exceptions
    3. Visit http://travelchannel.com/video, disable HTTPSE for the site
    4. HTTPSE is now listed under saved site exceptions
    5. Delete the new exception listed under HTTPSE, HTTPSE disappears from the list

- Screenshot if needed:
![gif](https://cloud.githubusercontent.com/assets/17010094/18865314/85072b76-8492-11e6-9626-18e61c086f27.gif)

- Any related issues:
#2545 #4118

**Comment by diracdeltas** [comment]
They should actually all disappear from the list when empty

**Comment by bbondy** [comment]
Included in 0.12.3RC3
