### ISSUE TITLE
Give ability to select where to install Brave

### ISSUE THREAD

**Issue by Booteille** [brave/browser-laptop#432]
Just saw it's included in #417.

**Comment by CtrlAltDefeat94** [comment]
#417

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6356

**Comment by bsclifton** [comment]
+1 from user @Gelo3D (from https://github.com/brave/browser-laptop/issues/5871)

**Comment by luixxiul** [comment]
+1 https://community.brave.com/t/controlling-install-location/738

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/change-install-folder/945

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/lastpass-doesnt-work-sites-automatically-logged-out-after-browser-reboot/5059/4?u=eljuno)

**Comment by Jacalz** [comment]
+1 from community https://community.brave.com/t/please-install-brave-to-proper-location/5755?u=jacalz

**Comment by Nitrooo** [comment]
+1

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/install-locations-for-computers-with-nvme-drives/7988?u=eljuno

**Comment by SRyGit** [comment]
Windows workaround sugestion: redirect your folder:
You got to log in with another account (so you don't have modify problems), then move\copy your AppData\Local folder to another drive, then modify your registry for your Local AppData to the new location. Then restart and log in and all of your growing data location would be on a different drive.
This would save space on C:, in fact, you could do this for your whole Profile if you want, which I sometimes use to revert a C: drive without reverting my profile\documents\etc. changes.
I do not know yet how W10 upgrades handle this yet; not tested, but I'm assuming that Enterprise accomodation will have it covered, unless they want you on UEV or such eventually.

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/KimeraGaming/status/974044929616887808

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/how-to-change-installation-directory/22021?u=eljuno

**Comment by bsclifton** [comment]
Unfortunately, we won't be able to fix this before moving over to [Brave Core](https://github.com/brave/brave-browser). Closing as `wontfix`

This issue is captured in `brave-core` with https://github.com/brave/brave-browser/issues/598

**Comment by Neustradamus** [comment]
We need possibility to install in the good folder and for all users.
