### ISSUE TITLE
Switching between pinned tabs by the shortcut doesn't work.

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#4320]
**Describe the issue you encountered:**

Switching tabs using shortcut works for standard tabs, but not for the pinned tabs. I'm not sure if it's expected behavior.

**Expected behavior:**

Pinned tabs should react on Control-Tab. And opposite with adding Shift.
- Platform (Win7):
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Pin the tab.
  2. Try: Control-Tab (or: CMD-Tab on Mac.
  3. Nothing happens.

It seems this works when you start from the standard tab and go back (Control-Shift-Tab), and it still works between pinned tabs, apart of first one. So when I switch to the first pinned tab, I cannot switch to forward tabs anymore.

**Comment by bsclifton** [comment]
This appears to be fixed (tested with 0.20.42) 😄
