### ISSUE TITLE
Closing one tab kills the browser

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4325]
**Describe the issue you encountered:** Closing one tab kills the browser
> On the latest master closing the tab while https://jpn.privateinternetaccess.com/ is loaded closes the browser itself.

According to @alexwykoff, there are several user who experience a similar issue.

**Expected behavior:** It should not kill the browser

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.3 RC1

- Any related issues:

**Comment by bridiver** [comment]
I'm not sure I understand, can you provide specific steps to replicate?

**Comment by luixxiul** [comment]
the browser sometimes crashes by these steps.

1. Clean your brave folder temporarily
2. Open the browser
3. Open a new tab
4. Go to https://jpn.privateinternetaccess.com/
5. Log in
6. Go back to https://jpn.privateinternetaccess.com/
7. Close the tab while the page is being loaded

I cannot say the exact timing when you need to close the tab. I tried ~10 times and experienced crashes several times. I did not experience the issue until I logged into the site.

**Comment by bridiver** [comment]
pinged you on slack for a login to use

**Comment by mideava** [comment]
I have the same issue. If I open a new tab and close it before loading any page on it, it closes normally. However, if I try to do that after having loaded any page on that tab, the browser itself closes. A am running Brave on Linux Mint 18.

**Comment by bridiver** [comment]
the commit test plan has details on how to reproduce this
