### ISSUE TITLE
Fix failing automated tests

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4329]

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/d3e4401f940a25dacd14661cfa96618faf718505
https://github.com/brave/browser-laptop/commit/e611a31e0334ef63cfa11c84eba3eeb64e81f3a2

**Comment by luixxiul** [comment]
For more tickets of the automated test failures: https://github.com/brave/browser-laptop/issues/6408#issuecomment-272806388

**Comment by luixxiul** [comment]
For the disabled tests: #5389

**Comment by alexwykoff** [comment]
Rather than having a perma-issue, a divide-and-conquer strategy is more productive. Closing in favor of the existing smaller issues.
