### ISSUE TITLE
Use the latest version of ledger-* packages

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#4340]
In support of https://github.com/brave/browser-laptop/issues/3350, use the latest version of the `ledger-client` package that makes available a `client.getWalletPassphrase` method

auditor: @ayumi

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/browser-laptop/commit/5d43029308bddb7350c09dce6c561050cce75188

**Comment by bbondy** [comment]
Will not be in 0.12.3rc3
