### ISSUE TITLE
autofill popup doesn't receive down-arrow on keyboard

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4343]
On 0.12.3 RC1, Mac...

![image](https://cloud.githubusercontent.com/assets/13509546/18895466/ba787db4-84ce-11e6-9051-8e7542fe4217.png)

Popup option opens but user can not hit down arrow key to enter popup.

@darkdh

**Comment by luixxiul** [comment]
Dupe of #1302?

**Comment by darkdh** [comment]
Yes, @luixxiul . Thanks for the reference.

**Comment by bradleyrichter** [comment]
sorry, closing this one.
