### ISSUE TITLE
Show bookmarks toolbar toggle is broken

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#4344]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Showing bookmarks toolbar is not expected when I turn option on/off
**Expected behavior:**
bookmarks toolbar should show as expected according to the setting

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS 

- Brave Version: 0.12.1 and latest master

- Steps to reproduce:
![123](https://cloud.githubusercontent.com/assets/11330831/18899553/6175c5e8-856c-11e6-8b7d-7440e231800e.gif)

**Comment by bsclifton** [comment]
This may be a duplicate of https://github.com/brave/browser-laptop/issues/3356#issuecomment-249599108; can you confirm, @darkdh?

**Comment by darkdh** [comment]
@bsclifton , yeah, it's a duplicate.
