### ISSUE TITLE
Search on the findbar should not start until hitting enter key to decide conversion candidates

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4347]
**Describe the issue you encountered:**
Internal search starts as soon as you input Japanese characters in the search form. Because of this the same issue as #3876 happens.

I think this applies not only for Japanese but also other languages which require IME like Korean, Chinese, etc.

For Japanese IME, see: https://en.wikipedia.org/wiki/Japanese_input_methods#Kana_to_kanji_conversion

**Expected behavior:**
Internal search should not start until you hit the enter key to decide conversion candidates.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS, Windows
- Brave Version: 0.12.3 RC1
- Steps to reproduce:
  1. Install Google IME [here](https://www.google.co.jp/ime/) and enable it on your system
  2. Change your language setting into Japanese
  3. Open the browser and show the internal search form
  4. Open #3876 
  5. Hit "s", which displays "ｓ" in a double-byte character with a conversion candidate like this:
     <img width="352" alt="screenshot 2016-09-28 15 19 40" src="https://cloud.githubusercontent.com/assets/3362943/18902615/14d75152-858f-11e6-9840-83ad53f0078b.png">
  6. 144 results are found, while no result should be found until I hit the enter key.
- Screenshot if needed:
- Any related issues: #3876 #2854

**Comment by JLHwung** [comment]
I can reproduce on macOS,  Brave 0.13.4 using system built-in Chinese Pinyin IME.
