### ISSUE TITLE
Clean up code branches

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#4348]
Currently, this repository has roughly 60-70 stale/merged branches that can be deleted.

**Comment by luixxiul** [comment]
Stale branches: https://github.com/brave/browser-laptop/branches/stale

**Comment by Liunkae** [comment]
I'll do another clean.

**Comment by bsclifton** [comment]
I went through and deleted a ton of old branches. Down to 59 total branches now 😄
