### ISSUE TITLE
Saved address doesn't show under about:autofill but shows suggestion on forms

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4349]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Saved address doesn't show under about:autofill but shows suggestion on forms

**Expected behavior:**
Should show the saved address under about:autofill

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.3dev-RC1 (Clean install)

- Steps to reproduce:
    1. Add new address in about:autofill
    2. Click on save. Nothing happens
    3. Go to http://www.roboform.com/filling-test-all-fields, Double click on first name, autofill suggestion come. When clicked autofills all saved information
    4. Open about:autofill doesnt show the saved address
    5. Repeat steps 1-3 with new details, new details also shown in autofill suggestion
    6. ~~Close all other tabs and open about:about, click on about:autofill~~
    7. ~~Click on add address, Edit address modal doesn't show up when the page is opened from about:about. Only works when you do it from preferences page or manually open about:autofill (See screeshot gif)~~

Logged #4350 for the autofill modal issue

- Screenshot if needed:
![autofill](https://cloud.githubusercontent.com/assets/17010094/18910092/5ebd90b8-856e-11e6-885c-410ab4cea00e.gif)

- Any related issues:
#4209 

cc: @darkdh

**Comment by bbondy** [comment]
For me in step ii) when I click on save. Nothing happens.  @darkdh has the same result as me.  Can you guys think of any reason difference?   If you move away your whole brave profile directory does it still reproduce?

**Comment by luixxiul** [comment]
I got a tricky combination:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/18913911/9f6316ea-85c5-11e6-86ee-4d9d75c1a0ee.png)

if I put just ``s{2,4}`` in Name, the entry cannot be saved. otherwise the entry can be saved as above.

**Comment by darkdh** [comment]
This is mine on 0.12.3 RC1  windows 10
<img width="823" alt="screen shot 2016-09-28 at 20 54 03" src="https://cloud.githubusercontent.com/assets/11330831/18914013/d349b278-85bd-11e6-8303-def4fed07300.png">

**Comment by srirambv** [comment]
For me anything I type gets saved but just doesn't show under saved address. But lists all of them as suggestions in form (Reproduced by moving %appdata%brave folder and created a new profile)

![image](https://cloud.githubusercontent.com/assets/17010094/18914216/0bcf49bc-8584-11e6-87e9-d58eb1ca70b2.png)

**Comment by luixxiul** [comment]
why does the autofill pulldown appear there by the way?

**Comment by srirambv** [comment]
Its showing in the roboform page but I just kept the mouse cursor on Autofill page to show saved address doesn't list. Ideally it shouldn't show in tab preview isn't it?

**Comment by bridiver** [comment]
there are actually two race conditions issues here
1. After saving the state, the autofill page immediately updates and can potentially try to read an address from the autofill db that hasn't persisted yet (`OnPersonalDataChanged` has not fired). Without listening for that callback there is no way to know when the ui should actually update
2. The race condition in #1 triggers a `appActions.removeAutofillAddress(addressDetail)` because the profile data is empty. That call removes the data from the appState, but doesn't necessarily remove it from the autofill db because it hasn't been persisted there yet
