### ISSUE TITLE
Autofill Modal doesn't show when about:autofill opened from about:about

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4350]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Autofill Modal doesn't show when about:autofill opened from about:about

**Expected behavior:**
Should open autofill modal irrespective how about:autofill is opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.3dev-RC1 (Clean install)

- Steps to reproduce:
    1. Open about:about page
    2. Click on about:autofill 
    3. Click on add address doesn't show the autofill modal 

- Screenshot if needed:
![autofill1](https://cloud.githubusercontent.com/assets/17010094/18912508/a6aeea32-857a-11e6-9f2a-bd7f8e7c8856.gif)

- Any related issues:
cc: @darkdh

**Comment by luixxiul** [comment]
Confirmed on Win10 32bit
