### ISSUE TITLE
Breakpoint A breakpoint as been reached

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#4352]
I was browsing as usual and the popup has appeared saying:

> Brave.exe - EXCEPTION
> 
> Breakpoint A breakpoint as been reached.

Then after clicking OK, the web browser crashed. Unfortunately I don't have any steps to reproduce this issue.
- Platform (Win7)
- Brave Version: 0.12.1

**Comment by luixxiul** [comment]
The issue seems to have been fixed already. would you pleave give the latest release a try? thanks!
