### ISSUE TITLE
Navigation buttons that are not available should not be visible

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4353]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
visibility of disabled navigation buttons does add visual clutter and does not add information to the screen

**Expected behavior:**
i only see navigation buttons when i can navigate browser history

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
master

- Steps to reproduce:NA
    1.
    2.
    3.

- Screenshot of expected behaviour:
<img width="1283" alt="screenshot 2016-09-28 16 31 52" src="https://cloud.githubusercontent.com/assets/1176068/18917797/1997dfd6-8599-11e6-8f01-4600baecddad.png">
<img width="1285" alt="screenshot 2016-09-28 16 31 04" src="https://cloud.githubusercontent.com/assets/1176068/18917801/1ccf439c-8599-11e6-92a0-f24e25431e4a.png">

**Comment by willy-b** [comment]
A random user's opinion: this feels buggy. It's unusual (e.g. Firefox always shows the navigation button)
and some new Brave users may just assume the browser is broken. 
IMHO, the disabled button conveys information: it is generally possible to navigate backwards and forwards, _but not right now._

**Comment by lucidNTR** [comment]
@willy-b actually you are half right. and i was half right too :-)
Firefox and chrome for ios have the behaviour to hide the forward button if not available and grey out the back button when back has no history. the reasoning is that the back button is the main way to access the history page on most browsers and i could live with that behaviour. Is this good in your oppinion?

**Comment by lucidNTR** [comment]
another point to clear the interface could be to move the forward and backward buttons out of the titleMode and into the header mode with the url bar

**Comment by lucidNTR** [comment]
I made a new PR with always showing the back button
https://github.com/brave/browser-laptop/pull/4423

<img width="763" alt="screenshot 2016-10-01 12 49 30" src="https://cloud.githubusercontent.com/assets/1176068/19013597/e39181f0-87d5-11e6-823a-eb67b2b5af44.png">
<img width="835" alt="screenshot 2016-10-01 12 49 25" src="https://cloud.githubusercontent.com/assets/1176068/19013598/e757d604-87d5-11e6-8a86-9c4540ca579e.png">
<img width="646" alt="screenshot 2016-10-01 12 49 17" src="https://cloud.githubusercontent.com/assets/1176068/19013600/e9e2b664-87d5-11e6-831c-f0f70ca35635.png">

**Comment by luixxiul** [comment]
wdyt @bradleyrichter ?

**Comment by bradleyrichter** [comment]
I'm all for innovation but in this case, I am sure it will be seen as a bug when the forward button appears missing, partially because of muscle-memory standards on most browsers. I agree that on mobile, this works in some cases due to the higher value of screen real-estate. 

@lucidNTR Thanks for the parallel thinking on always showing the nav buttons. This is part of the planned improvements when we land the next set of toolbar changes.

(see win screen shots in #3036) 

Can you update your PR so that the button behavior remains for active and disabled states but stays visible in both toolbar modes as you have shown above? This will be a nice step towards the other new changes.

**Comment by lucidNTR** [comment]
@bradleyrichter sorry i dont understand completely :D wouldnt that be the exact behaviour that master currently has? could you elaborate on the new pr behaviour please?

- yes, all errors are my iPhone's fault

**Comment by paJFJ** [comment]
just to make clear the behaviour of firefox for desktop is to hide the forward button too.
I never heard it beeing perceived as a bug. Maybe this is an issue of the person switching from firefox to brave or from chrome to brave? Could everyone that thinks my suggestion is buggy if they use chrome or firefox besides/befor brave? 
![bildschirmfoto 2016-10-01 um 21 09 44](https://cloud.githubusercontent.com/assets/22565636/19016512/8d3ff132-881c-11e6-999f-fd8e76b4d8c8.png)
![bildschirmfoto 2016-10-01 um 21 10 11](https://cloud.githubusercontent.com/assets/22565636/19016513/8ee95992-881c-11e6-8cc8-133f841a2261.png)

**Comment by luixxiul** [comment]
if we would replace "<" to "<-" probably we won't regard it as a bug, but it definitely makes brave look like firefox. In any case you will need to create a spec image and give it to @bradleyrichter because he's the lead designer.

**Comment by bradleyrichter** [comment]
@paJFJ Sorry. I was thinking of something a bit different when we move the URL bar to hang left, and then the reload, bookmark, and secure icons will join the nav buttons to stay visible in title-bar mode so ignore that PR update suggestion. (now deleted)

Regarding Firefox hiding the forward button, I think it works OK in their design which is quite different from the other browsers. Our layout is similar to Safari and Chrome/Opera/Vivaldi where I think the disabled forward button works/looks better than hidden and will be expected in this layout.

I am really interested in your thoughts on my proposed updates though. Especially with teh left-side bookmark placement:

(URL mode)
![image](https://cloud.githubusercontent.com/assets/13509546/19017731/970ba1a2-87f9-11e6-92e5-ed4b78507c33.png)

(title mode)
![image](https://cloud.githubusercontent.com/assets/13509546/19017735/f0d5206e-87f9-11e6-81f3-42d82441d1fc.png)


I think it still needs some size and spacing adjustment but this shows the idea where the buttons stay visible which improves usability when heading up to the URL bar.

**Comment by lucidNTR** [comment]
closing this, due to dependency on redesign on navigation-bar to left float instead of central. minimalism has to follow usability i agree. though after the alignment change i will revisit ways to make the ui more minimal on first sight without sacrificing features...

**Comment by lucidNTR** [comment]
@bradleyrichter could you post a link to the ' we move the URL bar to hang left, and then the reload, bookmark, and secure icons will join the nav buttons to stay visible in title-bar mode ' ticket number here please for completeness?
