### ISSUE TITLE
aspect ratio of navigation button background is not a circle

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4355]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
When you hover over an active forward or backward button, the white background is not circular but slightly eliptical.

**Expected behavior:**
the button should be a nice circle

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
master

- Steps to reproduce:
    1. open page
    2. navigate to any link 
    3. hover over back button

- Screenshot if needed:
<img width="158" alt="screenshot 2016-09-28 16 45 14" src="https://cloud.githubusercontent.com/assets/1176068/18918431/13b3923e-859b-11e6-88df-3a45c0f30d93.png">
<img width="209" alt="screenshot 2016-09-28 16 45 30" src="https://cloud.githubusercontent.com/assets/1176068/18918436/173c5634-859b-11e6-83b3-bacea1bcbe28.png">

**Comment by bradleyrichter** [comment]
new rectangle style allows closing of this issue
