### ISSUE TITLE
1password not filling in after enabling/disabling manager across different brave versions

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4359]
**Describe the issue you encountered:** 1password not filling in after enabling/disabling manager across different brave versions

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.3 RC2

- Steps to reproduce:
    1. install 1pw manager
    1. install brave 0.12.1
    2. update to 0.12.3 RC2
    2. enable 1pw manager on about:preferences
    3. close the browser
    3. reinstall 0.12.1
    4. reinstall 0.12.3 RC2
    5. open preferences
    5. disable 1pw manager and enable it again (this step needs to be done several times)
    5. go to https://github.com/login
    6. click 1pw icon
    7. select your account -> **autofill does not occur**

- Any related issues: #4334

**Comment by luixxiul** [comment]
for me this does not happen without downgrading

**Comment by bridiver** [comment]
is this can't be reproduced without downgrading I'm going to go ahead and close it. Any number of things could have gone wrong when going back and forth between those two versions. 0.12.1 had extensions built-in and autofill was broken and 0.12.3 uses downloaded crx extensions loaded into the user profile directory and has working autofill. We can't worry about testing every possible downgrade/upgrade scenario, but if you can repro without downgrading please reopen
