### ISSUE TITLE
typing in urlbar fast still can be laggy

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4360]
@BrendanEich reports https://github.com/brave/browser-laptop/issues/2736 is still happening

possibly related: https://github.com/brave/browser-laptop/issues/3876

**Comment by willy-b** [comment]
I wonder if it is possible to write a test that times / catches this? 
Or is it too subtle? Can you grab a GIF or give a reproduction?

**Comment by bbondy** [comment]
++

**Comment by diracdeltas** [comment]
this was reverted so im reopening

**Comment by alexwykoff** [comment]
Still experiencing this in OS X.  Windows 7 seems ok, but the VM might be introducing just enough of a delay to make it work.
![url_bar_touchiness](https://cloud.githubusercontent.com/assets/1434040/19348669/a5b4c1b6-9181-11e6-9e75-a9ac927ca8df.gif)

**Comment by luixxiul** [comment]
@alexwykoff I opened an issue for that on #4731

**Comment by diracdeltas** [comment]
closing this because the issue in @alexwykoff's screenshot seems to be https://github.com/brave/browser-laptop/issues/4731
