### ISSUE TITLE
Flicker-Effect on Hover (Unable to Select Text Easily)

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4365]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Hovering some elements causes _sibling_ elements to believe they too are hovered. This causes a flickering effect on multiple elements.

_If I set my display scale to 100%, and restart my computer, I no longer see the issue. Returning to 200%, and restarting, causes the issue to return. **This issue does not exist in 0.12.1 builds**._

**Expected behavior:**

Only the element (and its ancestral tree) directly beneath the mouse should think they are hovered.

- Platform: Windows 10, 14393 (200% Scale, Surface Book i7)

- Brave Version: 0.12.3

- Steps to reproduce:
    1. Navigate to Brave's GitHub Issues
    2. Move mouse around atop top-most issue
    3. Note flickering on issues further down the page

- Screenshot if needed:

_In the following GIF, I am moving my mouse up to the top-most issue. As I hover/move-atop the top-most issue, other issues further down are intermittently adopting hover-styles, as though my mouse were atop them as well._

![flicker](https://cloud.githubusercontent.com/assets/815158/18929082/cd92c48c-8577-11e6-8c19-7003cc96f967.gif)

_In the following GIF, I am moving my mouse from one menu item to another. As I hover/move-across the menu items, multiple menu items are intermittently adopting hover-styles, as though my mouse were atop them all._

![flicker2](https://cloud.githubusercontent.com/assets/815158/18929086/d486f998-8577-11e6-9405-4b070017016c.gif)

**Comment by jonathansampson** [comment]
This issue appears to be even more grave than I initially thought. I also cannot select text easily. Text elsewhere is selected in parallel, and if my selection is far enough down the viewport, the page will auto-scroll.

![flicker3](https://cloud.githubusercontent.com/assets/815158/18929298/d01a8ba8-8578-11e6-8a52-5872992d49c9.gif)

**Comment by jonathansampson** [comment]
This doesn't repro for me when I test against 0.12.1, so it was likely introduced recently.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/electron/commit/182fe6df4115aa3aaa0058fa36e6366b98ca5113

**Comment by jonathansampson** [comment]
This issue doesn't appear to be fully resolved; Ana Tudor ran into flickering on her Surface Book, running at a default zoom level of 175%.

> @AnaTudor: @brianbondy @BraveSampson @brave Also flickering like crazy every time I hover a link or try to drag something - what happened? (https://twitter.com/anatudor/status/783060234990477312)

**Comment by bbondy** [comment]
@jonathansampson pls track a new bug and I'll keep this one closed in 0.12.3 because this did fix a problem that was there.
