### ISSUE TITLE
Missing Brave Icon in Task View on Windows

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4367]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Brave is displayed with Electron branding

**Expected behavior:**

Brave should be displayed with Brave branding
- Platform: Windows 10 (14393)
- Brave Version: 0.12.3
- Steps to reproduce:
  1. Open Brave
  2. Press Windows Key + Tab to enter Task View
  3. Note that Electron icon is displayed
- Screenshot if needed:

![no-icon](https://cloud.githubusercontent.com/assets/815158/18934296/beee0c50-858d-11e6-8379-b6af5338825f.png)
- Any related issues: #4021

**Comment by bsclifton** [comment]
I think this is limited to when you run in two windows, with:
`npm run watch`
`npm start`

Packaged versions shouldn't be doing this (ex: if you run the tools/buildInstaller script)

**Comment by luixxiul** [comment]
the issue has been fixed.
