### ISSUE TITLE
Feature Request : Provide a means of per-tab introspection on resource use

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4368]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
One of our users suggested that the display of CPU and memory use per tab would be quite useful to them. I would agree as this would certainly help with experienced users who are looking to constrain resource use or debug various web applications. It would certainly be a boon for web developers and QA.

**Expected behavior:**
Each tab would have some means of displaying its resource use and / or we would have a view (about: page or something similar) available to users to show a consolidated view.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  `>1.0`
#1547

**Comment by jonathansampson** [comment]
Internet Explorer had something like this&mdash;<kbd>Ctrl+Shift+U</kbd>; it's a super helpful feature.

![image](https://cloud.githubusercontent.com/assets/815158/18945847/329dd344-85e1-11e6-84ea-3ec08215024c.png)

**Comment by gojomo** [comment]
An "about:tabs" that lists tab URL, native process-ID, and a momentary snapshot of any internal resource-accounting (objects? threads? interrupts? etc) attributable to that tab would be a great help in fingering bad tabs.

**Comment by bsclifton** [comment]
This is basically implemented in [brave-core](https://github.com/brave/brave-browser) via the Task Manager
![screen shot 2018-09-02 at 10 12 14 pm](https://user-images.githubusercontent.com/4733304/44968528-515fec80-aefd-11e8-9fa9-9aca476cbc73.png)
