### ISSUE TITLE
Crash upon CTRL + Click on a link

### ISSUE THREAD

**Issue by ppetrov** [brave/browser-laptop#437]
URL : [(https://chess24.com/en/read/news/tata-steel-2016-10-caruana-closes-the-gap)]
Scroll down the page, when CTRL Click on a link ("his Q&A Session") the browser crashes. I've tried this several times and it crashed all the times.

**Comment by ppetrov** [comment]
I think it's because of the href target attribute set to _blank (target="_blank") and with the Ctrl+Click it's like open in new "double" tab.

**Comment by Tombsmen** [comment]
see ticket [#412 ](https://github.com/brave/browser-laptop/issues/412)

**Comment by bbondy** [comment]
Closing this as a dupe.
