### ISSUE TITLE
Caption buttons are not shown when in fullscreen mode (Windows)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4376]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Introduced with https://github.com/brave/browser-laptop/pull/3854, I had hidden the caption buttons based on verbal feedback from folks.

**Expected behavior:**
Caption buttons should always show when fullscreen (else, there is not an easy way to exit)

- Platform (Win7, 8, 10? macOS? Linux distro?):
All Windows

- Brave Version:
0.12.2 and newer

- Steps to reproduce:
    1. Launch Brave
    2. Hit F11 to go full screen
    3. Notice you can't exit (no caption buttons)

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I thought the max button would exit the fullscreen mode (min and exit buttons work). Should it not so?
