### ISSUE TITLE
Windows titlebar should be disabled for now

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4378]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Windows titlebar has at least two known issues which need to be fixed. In the meantime, we can disable the titlebar.

**Expected behavior:**
The new titlebar is not shown

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows

- Brave Version:
0.12.2+

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bridiver** [comment]
I don't think this is valid anymore, is it?

**Comment by bsclifton** [comment]
no- it shouldn't be :smile: I'll go ahead and close this issue and the associated PR (which has the changes to disable the functionality)

cc: @bbondy
