### ISSUE TITLE
Bookmarks toolbar and close buttons don't work when at 175% resolution

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4380]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A picture is worth 1000 words :stuck_out_tongue: 
![close - toolbars right-click](https://cloud.githubusercontent.com/assets/4733304/18963977/d60e5e50-862b-11e6-8dac-6f52d6fe1b8d.gif)

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 w/ anniversary update

 @aekeus reported the issue and can provide more details about his setup

- Brave Version:

- Steps to reproduce:

1. Right click desktop, pick Display settings
2. Crank setting up to 175%
3. log out / log back in, so it takes effect
4. Re-enable Windows titlebar if the feature is currently disabled
5. Launch Brave
6. Try to use the close button (top right)
7. Try right clicking bookmarks toolbar

**Comment by bsclifton** [comment]
After further inspection and removal/reinstall, @aekeus was unable to reproduce. We think he may have been stuck on 0.12.3 RC1 (which had some known issues)

**Comment by jonathansampson** [comment]
@bsclifton @aekeus This may be a Windows issue. I ran into something similar with Chrome back in August. Clicking the [x] did nothing: https://twitter.com/jonathansampson/status/767382031290335232
