### ISSUE TITLE
Nested bookmark folders listed beyond the toolbar is not properly shown when Window size is changed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4381]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Nested bookmark folders listed beyond the toolbar is not properly shown when Window size is changed

**Expected behavior:**
Should show the nested folder properly irrespecitve of browser window size
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.3 RC3
- Steps to reproduce:
  1. Have lots of bookmarks to overflow the bookmark toolbar.
  2. Ensure Nested bookmark folders are beyond the toolbar region
  3. Click on >> to list all bookmarks
  4. Navigate to folder to show the nested folders/bookmark items. Should show properly next to the folder
  5. Resize the window to a smaller resolution 
  6. Repeat steps 3 & 4, the nested folders/bookmark items are way off. Doesn't show next to the parent folder.
- Screenshot if needed:
  ![bookmark1](https://cloud.githubusercontent.com/assets/17010094/18964805/534b73d0-8672-11e6-849d-9fec21b25953.gif)
- Any related issues:
  #4272

**Comment by bbondy** [comment]
This has to do with the scroll offset not being taken into account.

**Comment by jkup** [comment]
Having trouble reproducing. Could it maybe be a Windows issue?

**Comment by jkup** [comment]
I can't reproduce this on Windows either. Is there a chance it was fixed by something else? @srirambv can you still repro?

**Comment by bsclifton** [comment]
This is somewhat similar to https://github.com/brave/browser-laptop/issues/1589; I wonder if it's the same issue?

**Comment by jkup** [comment]
Should we close this out if we can't reproduce it? That other issue worries me because the user says they can still repro it even though we can't. Either way I think we should bump out of 12.6 for now because I'm not sure how to get started.

**Comment by bbondy** [comment]
@srirambv please answer @jkup from last week's comment. Thanks.

**Comment by bsclifton** [comment]
@srirambv can you please try to repro this? If you're not able to, let's close it out. Thanks :smile:

**Comment by srirambv** [comment]
Issue still exist. This is on 0.12.12. Nested folder is not selectable if the browser window is small
![4381](https://cloud.githubusercontent.com/assets/17010094/20878139/01686906-bac5-11e6-9fac-72eb222a8395.gif)

**Comment by luixxiul** [comment]
I think this is a dupe of #1589
