### ISSUE TITLE
Brave will not install due to "IT Permissions" ??

### ISSUE THREAD

**Issue by fuzzylgic** [brave/browser-laptop#4382]
**Did you search for similar issues before submitting this one?**
YES
**Describe the issue you encountered:**

Brave will not install.  Current version says Can Not Execute Extracor
Previous versions say IT Permissions error
I contacted and shared screen shots below with Brave support and they had no ideas.

**Expected behavior:**
Brave Installer to Run / Extract / Install
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10 & Win 8
  ![_mypc](https://cloud.githubusercontent.com/assets/22527853/18965265/1f1c8732-8642-11e6-9559-4be9bd78301c.JPG)
- Brave Version:
  All Versions
- Steps to reproduce:
  1.Download Brave Setup to c:\users\me\downloads
  2.Run Setup
  3.
- Screenshot if needed:
  ![_brave2](https://cloud.githubusercontent.com/assets/22527853/18965415/c89840f8-8642-11e6-83a8-f50556b6b709.JPG)

This is a screen shot from a previous version of Brave.  The current version simply produces a window that says Can Not Extract Brave File

PLEASE HELP ME GET BRAVE ON THIS PC.  THIS IS THE ONLY PC I HAVE EXPEIRENCED TROUBLE INSTALLLING BRAVE ON.

Thanks

Jason
fuzzylogic

**Comment by bsclifton** [comment]
Hi Jason,

I see you're trying to install the 32 bit version but you're on 64 bit. That shouldn't be a problem, but I'm curious if you can try the 64 bit installer?

Also, can you try launching the installer via the right click -> Run as Administrator menu option?
![image](https://cloud.githubusercontent.com/assets/4733304/18974892/208537a4-865b-11e6-831b-29483d8c663e.png)

**Comment by fuzzylgic** [comment]
Thank you for the reply.  I have tried both 32 bit and 64 bit versions and I get the same message.   The last installer I tried was the 64 bit version.  

If I have tried launching the installer as administrator via right click and it will not work.  A previous version of Brave gave me the below error message and the latest build simply says "failed to extract installer".
![_brave3](https://cloud.githubusercontent.com/assets/22527853/19007271/ae70cafa-8729-11e6-8118-acb4989ef8b9.JPG)

Thank you for your time.  Please let me know what you think.  
Jason

**Comment by fuzzylgic** [comment]
Let me add this as it may help. 

A previous version of Brave (I have been at it for awhile, so forgive me for not keeping track of which version) did at least partially extract and probably generated a log file.   I actually think I had to launch in admin mode to get this far.   However, the newest version I am working with .11.6.0. simply says "Failed to Extraxt Installer".

I have tried Windows 10 Troubleshoot to see if there was a backwards compatibility solution.  No  dice.

Here is another error message generated by a previous version of Brave.  By previous I mean prior to .11.6.  I was using  64 bit installer.  
![_bravex64](https://cloud.githubusercontent.com/assets/22527853/19008132/c1387b74-872e-11e6-97d0-d86862d5472b.JPG)

Is it possible to access previous versions of Brave, determine the one that did extract (but not execute the install), and we can take a look at what the log file says?  This may be unimportant, but is just an idea.  By "extract" I mean the Brave installation files extracted and a temp folder and a Brave folder was created in program files.  The new version .11.6.0 does not get this far.

Jason

**Comment by bsclifton** [comment]
@fuzzylgic you can access previous versions here (make sure to grab the EXE version, not the MSI version):
https://github.com/brave/browser-laptop/releases

Our latest version is 0.12.1 (you'll also see some newer but unreleased executables there too).

Can you tell me a little more about your setup? Is your machine joined to a domain that is managed with Active Directory? Searching Google w/ the error you shared above, it appears there are some known issues with the Squirrel installer.  One work-around would be to [try the MSI installer, using the command line](https://msdn.microsoft.com/en-us/library/windows/desktop/aa367988(v=vs.85).aspx). Installing this would be *something* like:

1. Download the latest stable MSI release
2. Start > Run, cmd
3. cd "folder where MSI lives"
4. msiexec /i

**Comment by fuzzylgic** [comment]
By MSI, do you mean the Windows command line program?

I followed the link to the latest Brave release and downloaded BraveSetup-x64.msi v0.12.3.

I ran the command line: msiexec /i  BraveSetup-x64.msi.

The first time I did this was Friday afternnoon.  I window popped saying "Preparing to Install" followed by another menu box from Brave saying the installing could not continue.

I tried repeating this today in order to clip the menu box image for you but this time, after the first "Preparing to install" dialog box, nothing happens.  I am pretty sure this is because I ran the .msi on Friday and there is  now  data on the PC.  You may have a better idea about this.    The only difference on this PC is that Windows 10 updated two times over the weekend.  
![_msi](https://cloud.githubusercontent.com/assets/22527853/19052368/204f0fe8-897c-11e6-83f2-b31c6dd1bb13.JPG)

Any ideas?  Am I using the correct msiexec?  If I need to update it, where?   

Thank you,

Jason

**Comment by fuzzylgic** [comment]
Today, I ran MSI on the Brave-x64.exe and I get this error box:

![_bravex64](https://cloud.githubusercontent.com/assets/22527853/19093350/6296869a-8a50-11e6-82a1-889ab1844940.JPG)


What do you think?

**Comment by fuzzylgic** [comment]
Brave still not installing.  

Recently had trouble installing TeamViewer to this PC.  The install failed with the error that that temp folder could not be accesses.  This "feels" a lot like what is going on with Brave.
![_error](https://cloud.githubusercontent.com/assets/22527853/19423457/1675f29c-93e6-11e6-8e64-13f20d96fa62.JPG)

I found this link that may solve the problem.   At the very end of the page a person gives not so specific instructions for changing the installation paths and creating an alternate temp directory.  I am going to sort this out in the morning if I can.

Meanwhile, I would much appreciate it, if you would look at what the person is saying and see if his instructions are clear? http://superuser.com/questions/655630/temp-folder-is-not-writeable-for-some-applications-resulting-app-crashes

![_ans](https://cloud.githubusercontent.com/assets/22527853/19423417/cccc94b6-93e5-11e6-87b2-33c42bf9e5d8.JPG)

**Comment by fuzzylgic** [comment]
Finally have Brave running on this PC:

Permissions on this PC were inconistant.  I restored them to what looks correct. 

Ran installer in admin mode and received usual error box
The installer will only run in admin mode.

Change to \ProgramFiles68\BraveSetup\

Run 'Brave' application

Setup installed Brave.


Thank you for your time and patience.  

jms

**Comment by fuzzylgic** [comment]
.
