### ISSUE TITLE
Youtube videos don't play. 

### ISSUE THREAD

**Issue by kurutze** [brave/browser-laptop#4384]
Youtube videos don't play. The Youtube page itself opens, but videos don't upload nor play (they do in other browsers). Thanks!

My OS is Windows 7 Professional; 64 bit system. Brave 0.12.1

![youtube not playing](https://cloud.githubusercontent.com/assets/22529379/18968360/012e2ad8-865f-11e6-96aa-bc1ec822d5a3.jpg)

![image](https://cloud.githubusercontent.com/assets/22529379/18968367/0a5bf5e0-865f-11e6-80a4-3f5de1531a84.png)

**Comment by srirambv** [comment]
+1 [support](https://linkbubble.zendesk.com/agent/tickets/6802). user says video doesn't show but she is able to hear the audio and it's an intermittent issue

**Comment by kkinder** [comment]
For me, YouTube videos are displaying, and you can move around in them, they just persist in a paused/stopped state. You can't start them.

**Comment by NumDeP** [comment]
This is also still an issue but in a different forms. 

As stated in #9044 Youtube also require you to click on the platform multiple times to play content despite preferences on 'Autoplay Media' set to 'Always allow'.

I wish all referenced issues can be fixed together @luixxiul as they are similar or  exact and have been going to long enough. Thanks.

**Comment by bsclifton** [comment]
YouTube is working as expected - there may be autoplay issues still, as called out above... but youtube.com is added to Brave's `Autoplay Media` inclusion list by default
