### ISSUE TITLE
Add changesets to better identify RC builds

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4386]
Currently it's hard to tell which RC build you are using.  We should add both the browser-laptop changeset and teh brave/electron changeset into the about dialog so we can always be sure.

/cc @jonathansampson @aekeus @alexwykoff

**Comment by aekeus** [comment]
That would be great - a build time might suffice.

**Comment by luixxiul** [comment]
Recent change on versioning makes it easy to tell the version. I'm going to close this.
