### ISSUE TITLE
Clicking Brave icon does not always open a new window

### ISSUE THREAD

**Issue by Nokel81** [brave/browser-laptop#4388]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When you have multiple virtual desktops and one of them has a Brave window open and another does not, clicking on the taskbar pinned icon does not open a new window on your virtual desktop but instead takes you to the open window on a different virtual desktop

**Expected behavior:**
Opens a new browser window on the current virtual desktop

- Platform (Win7, 8, 10? macOS? Linux distro?):
Window 10

- Brave Version:
0.12.1

- Steps to reproduce:
    1. Have Brave pinned to taskbar
    2. Have more than one virtual desktops
    3. On one of those VDs have a Brave window open, but not on another
    4. Be on a VD that does not have a window open
    5. Click on the pinned icon

**Comment by srirambv** [comment]
Same as #2627 ?

**Comment by Nokel81** [comment]
Yes but I did not find that when searching
