### ISSUE TITLE
Brave ad replacement sometimes does not occur

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#439]
Image 1 of3 displace the white spcae left behind by a missing advertisement in Brave. Image 2 of three shows the white space has been aborbed when using Adblock plus and Google Chrome. Capture 3 shows the Advert in place in Google Chrome with ADblock plus turned off.
![capture_1](https://cloud.githubusercontent.com/assets/16950007/12682043/d17a6e9c-c66e-11e5-9b03-e8a8e1ed8a13.PNG)
![capture_2](https://cloud.githubusercontent.com/assets/16950007/12682158/40b8df78-c66f-11e5-9e49-5368f0f9b159.PNG)
![capture_3](https://cloud.githubusercontent.com/assets/16950007/12682159/40b8f8c8-c66f-11e5-84f3-981a6bf7c41c.PNG)

**Comment by luixxiul** [comment]
Reproducible at http://blackflag.jalopnik.com/indianapolis-motor-speedway-already-delivered-an-insane-1779238746. Is there any plan to replace such a custom ad components?

**Comment by bsclifton** [comment]
This is specific to certain sites. We can address this case with a cosmetic adblock filter. @Snuupy is working on this functionality which is tracked with https://github.com/brave/brave-browser/issues/94
