### ISSUE TITLE
Browser 0.12.3 RC3 on Windows periodically becomes unresponsive to clicks after load

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#4391]
**Did you search for similar issues before submitting this one?**

Yes, seems to be related to #3231

**Describe the issue you encountered:**

Periodically after launching the browser, the close button and right click on the Bookmarks toolbar become inoperable. The following error is in the console.

<img width="532" alt="screen shot 2016-09-29 at 6 53 26 pm" src="https://cloud.githubusercontent.com/assets/210240/18976114/5779253c-867d-11e6-917f-5e3c46b54b9c.png">

The error message is repeatedly reported on all mouse movement events in all open tabs, as well as on a close button press.

![no-close](https://cloud.githubusercontent.com/assets/210240/18976133/855bc388-867d-11e6-8819-871d3ffac1a7.gif)

- Platform (Win10):

- Brave Version: 0.12.3

- Steps to reproduce:
    1. This is reproducible on only a fraction of the launch attempts (~10%)

cc @bbondy @bridiver @bsclifton

**Comment by bridiver** [comment]
there is a good chance that error message is unrelated. It happens frequently since upstream made a change to the remote api. If you see it happen as a directly result of some action then it might be related

**Comment by bridiver** [comment]
actually in this case it might be related because line 191 is an emit for a sync ipc call

**Comment by aekeus** [comment]
The error message is triggered each time the mouse is moved over the tab when the browser is in the described state. It is not sent to the console in normal browser operation.

**Comment by bridiver** [comment]
is this windows only?

**Comment by aekeus** [comment]
Yes, I can only trigger it on Windows 10.

**Comment by bbondy** [comment]
This *could* be the cause, I'm pulling in the commits from upstream electron which has them only in 1.4.1, we're on 1.4.0 upstream.
https://github.com/electron/electron/pull/7209/commits

**Comment by bsclifton** [comment]
(just for tracking purposes) It seems issue was first seen with https://github.com/brave/browser-laptop/issues/4380#issuecomment-250545047

**Comment by alexwykoff** [comment]
Since this only happened for @aekeus and it was confirmed on his machines, I think the only steps for QA are to check that the common windows interaction items work properly.

If there are other concerns for QA, (like zoom, resolution, etc.) please be sure add a comment.
