### ISSUE TITLE
Netflix won't play media in Brave

### ISSUE THREAD

**Issue by Langrila** [brave/browser-laptop#4392]
Using Brave browser,  I signed into Netflix.  The selected movie would not play because of missing a component.  (Netflix plays on other browsers on this computer, including Firefox and Opera)

Message received from Netflix:

Whoops, something went wrong...

Missing Component

We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button.
For additional assistance resolving this issue, please visit our Help Center.
https://help.netflix.com/support/27451

**Comment by luixxiul** [comment]
Closing this as duping to #468

**Comment by bsclifton** [comment]
@Langrila we do have plans for Widevine CDM support which will get Netflix up and running. Stay tuned and subscribe to issue https://github.com/brave/browser-laptop/issues/468 so that you can be notified when we know more :smile:
