### ISSUE TITLE
Certain Flash games on Facebook doesn't load 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4397]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Certain Flash games on Facebook doesn't load. There has been several tickets in support relating to this. 

**Expected behavior:**
When flash is installed user should be able to open flash content games on Facebook
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  
  > 0.12.1 (Shields down)
- Steps to reproduce:
  1. Open [Facebook Game](https://apps.facebook.com/onthefarm/) 
  2. Message shows need to upgrade flash. Clicking on the link doesn't load the notification bar to allow/deny instead goes to Adobe page to download flash
  3. Console shows mixed content error
  4. Open a different [game](https://apps.facebook.com/warbanner/)
  5. Click on Get flash player, notification is shown to allow/deny. Allow and enjoy the game 

Looks its specific to content provided by Zynga that is getting blocked. The second game  link provided is from a different publisher and the flash content loads without any problem.
- Screenshot if needed:
  Shields down
  ![image](https://cloud.githubusercontent.com/assets/17010094/18984779/58ffde4a-86ec-11e6-8fc7-c3ea9d7991ab.png)
  
  Shields Up  
  ![image](https://cloud.githubusercontent.com/assets/17010094/18984789/6a1ffbb0-86ec-11e6-8e67-b66763be2f1a.png)
- Any related issues:

**Comment by diracdeltas** [comment]
could you try again on master? may be fixed now

**Comment by srirambv** [comment]
+1 from community. https://community.brave.com/t/flash-needed-for-games-on-face-book/3615/8
Btw this is still an issue on master

**Comment by bsclifton** [comment]
@srirambv do you know if they load with shields down?

**Comment by srirambv** [comment]
+1 from community for another game on a different domain
https://community.brave.com/t/town-of-salem-on-brave-browser/20568/2
![image](https://user-images.githubusercontent.com/17010094/39130396-f9b656de-46da-11e8-8eb6-f07485b8cbcf.png)
