### ISSUE TITLE
As a user I want to see all new tab options at one place

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4398]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
 I want to see all new tab options at one place instead of having to go to the burger menu for new private and session tabs

**Expected behavior:**
long clicking the new tab button shows me a list of other kinds of new tabs i might want
- Platform (Win7, 8, 10? macOS? Linux distro?):
  all
- Brave Version:
  latest master
- Steps to reproduce:
  1. click long on plus sign next to tabs
  2. nothing happens
- Screenshot if needed:
  <img width="620" alt="screenshot 2016-09-30 13 37 15" src="https://cloud.githubusercontent.com/assets/1176068/18990652/bd3e5928-8713-11e6-8ac2-7e6dccf45f6c.png">
- Any related issues:

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/pull/5696

**Comment by bsclifton** [comment]
and I'm an idiot and closed the issue, not the PR :stuck_out_tongue:
