### ISSUE TITLE
it is hard to see where a tab will be after dragging to new location

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4401]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
when i drag a tab to a new location it is hard to tell where it will be. The little spacing between tabs helps but is not available when reordering pinned tabs.

**Expected behavior:**
i would like to see a little caret at the position where the tab would be after the dragging completed.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macos
- Brave Version:
  current master

**Comment by luixxiul** [comment]
This has been fixed on the latest released build.
