### ISSUE TITLE
Ability to drag tab into new window ("tear off" tabs)

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4402]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
if i want to have a new window for a tab other browsers allow dragging a tab out of the window to create a new window. i expect the same behaviour in brave.

**Expected behavior:**
see above
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macos
- Brave Version:
  master

**Comment by getsetbro** [comment]
Also dragging a tab from one open window to another open window should move it to the opened window that it was dragged to. Currently it does not move it (tested on Mac El Capitan version 10.11.6).

**Comment by Liunkae** [comment]
Not to be confused with #405. This issue refers to creating a new window with an existing tab (still in the same Brave process).

**Comment by echosa** [comment]
Additionally, I would expect there to be a right-click menu option for "Move To New Window" when right-clicking tabs.

**Comment by Liunkae** [comment]
This is an essential feature every major browser has. I'll set the milestone to 1.0 for now. Please change/remove the milestone if needed.

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/7180)

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7225)

**Comment by outragedhuman** [comment]
+1 essential feature

**Comment by luixxiul** [comment]
Another request: https://community.brave.com/t/moving-tabs-from-one-browser-window-to-the-next/529?u=suguru

**Comment by yannduran** [comment]
👍

**Comment by CliqueBait** [comment]
+1 from Community: https://community.brave.com/t/second-window-for-dual-monitors/1067

**Comment by ryanleesipes** [comment]
Just adding another supporting comment for this feature. I'm excited to see this make it in. Are there any branches/anyone currently working on this?

**Comment by NejcZdovc** [comment]
You can see progress here https://github.com/brave/browser-laptop/pull/6929

**Comment by amc2002** [comment]
Deal breaker here too. I love Brave, but rearranging tabs and breaking them off to new windows is essential. Had to go back to Firefox. :(

**Comment by ivanstegic** [comment]
@echosa what are the other items? Do you have them listed somewhere, I'd love to see them!

**Comment by echosa** [comment]
Well, I did just have this as some terse notes in a private Fastmail note. Then you had to go and ask for it publicly, so I had to write out some better descriptions, and go aggregate all the links to the appropriate GitHub issues. :-P 

So, here you go: https://gist.github.com/echosa/ed4a150d74e96fc6d54b72a8ae853a61

**Comment by ivanstegic** [comment]
Thank you good sir, starred the list. Some of those are annoyances for me, but not deal breakers... like the YouTube ads one. If this was reddit, I'd gold you.

**Comment by echosa** [comment]
Indeed. There's a reason the ads issues are so far down the list. I suppose I could break the list into "must haves" and "nice to haves", but meh. It's fine as is for now.

Enough side-tracking this issue, though. :-)

**Comment by bsclifton** [comment]
Thanks for sharing the list, @echosa 😄

**Comment by echosa** [comment]
:-) I'm really trying to stay on Brave as default, but these things are making it difficult. I consider switching away, then switching back when Brave meets more of my requirements. :-P I love Brave. I love the idea of it. I enjoy using it (when it does what I need). However, if there's already a browser out there that meets my needs, it's difficult to turn it away. I'm trying, though. That's for sure.

**Comment by jonathansampson** [comment]
+1 from Twitter: https://twitter.com/Nilpferdo/status/844971940850941952

**Comment by bbondy** [comment]
Done, finally!
https://github.com/brave/browser-laptop/pull/8084

**Comment by luixxiul** [comment]
@bbondy would you mind adding QA steps if any? Thanks! :-)

**Comment by bbondy** [comment]
I edited in steps to test in the first comment @luixxiul
