### ISSUE TITLE
Enabling Block 3P Cookie doesn't load Calendar on MyITLab.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4404]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enabling Block 3P Cookie doesn't load Calendar on MyITLab.com. 
Issue reported from support.

> When I sign in at MyITLab.com which is a site I use to train students on Office 2013, the first page to appear when I click on the course displays the Assignment Calendar. 
> However, the Assignment Calendar never appears.

**Expected behavior:**
Should load the assignment calendar properly.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Windows 10 x64, User is on Windows 7
- Brave Version:
  0.12.1 Dev
- Steps to reproduce:
  1. Login to MyITLab.com
  2. Select the course listed
  3. Assignment calendar is not loaded instead shows application error
  4. Disable Block 3P Cookie, Assignment calendar is loaded.

Note: The site seem to use popups to launch content and shows a warning message about popup blocker when trying to login. 
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/17010094/18992555/dba01d90-8716-11e6-9943-effa98aeaf4d.png)
- Any related issues:

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
