### ISSUE TITLE
Blogspot blank page

### ISSUE THREAD

**Issue by ksalp** [brave/browser-laptop#4405]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

When trying to pull up this page from a link at agr.wa.gov, I just get a white screen: https://www.wastatedeptag.blogspot.com/ 

**Expected behavior:**

It should bring up the Washington State Department of Agriculture blog. 

- Platform (Win7, 8, 10? macOS? Linux distro?):

Windows 8 

- Brave Version:

Downloaded 9/29/16

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/22547299/18998018/c3a38856-86eb-11e6-8b1a-5d564b8973d2.png)

- Any related issues:

When I copied the url and pasted it into a new tab, it brought up the page but blocked it, saying there was a certificate issue. I elected to proceed anyway, and then the page came up. I did not get this message when I clicked on the link - just a blank page.

**Comment by luixxiul** [comment]
For me on 0.12.1 it gives ``net::ERR_CERT_COMMON_NAME_INVALID`` error.

**Comment by neeklamy** [comment]
The website owner should be informed that the SSL cert hasn’t been correctly set up.

Using Qualys SSL Labs server test:<br>https://www.ssllabs.com/ssltest/analyze.html?d=www.wastatedeptag.blogspot.com<br>Reports:<br>“Certificate name mismatch”

Strip out the “www” subdomain and it works just fine:<br>https://www.ssllabs.com/ssltest/analyze.html?d=wastatedeptag.blogspot.com<br>https://wastatedeptag.blogspot.com

**Comment by bsclifton** [comment]
Closing as this site definitely has a cert error.  This can be tested at anytime w/ OpenSSL:
```
echo | openssl s_client -showcerts -servername www.wastatedeptag.blogspot.com -connect www.wastatedeptag.blogspot.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

(check out the subject alternative names for hostnames covered by this UCC cert)
