### ISSUE TITLE
LastPass password box does not accept tabs

### ISSUE THREAD

**Issue by lo-co** [brave/browser-laptop#4406]
In the new LastPass access badge in the upper right corner of the browser you can not enter you email and then tab to the password field.  Tabbing from any field results in the closing of the box to enter your LastPass information.  I would expect that you could use tab and enter to change the focus within the LastPass box and enter to enter new values and close the box.

This behavior is reproducible on the latest Ubuntu LTS release, Windows 10 and Windows 7.  This is found in the latest binary release of Brave 0.12.1.

To reproduce, simply attempt to enter information in the fields and tab through them.

**Comment by srirambv** [comment]
Same as #4018. Closing as duplicate
