### ISSUE TITLE
Video on pbs.org does not play

### ISSUE THREAD

**Issue by joneschrisg** [brave/browser-laptop#4408]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

Video on pbs.org does not play 

**Expected behavior:**

Video plays
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X 10.11.6
- Brave Version: 0.12.1
- Steps to reproduce:
  1. Load http://www.pbs.org/wgbh/frontline/film/the-choice-2016/?utm_source=Second_Screen&utm_campaign=The_Choice_2016&utm_medium=Twitter
  2. Press play button on poster image
  3. Note that video doesn't play, and doesn't seem to start loading
  4. Repeat 1-3 in Chrome and note that the video plays
- Screenshot if needed:
- Any related issues:

**Comment by neeklamy** [comment]
Note, for anyone outside of (presumably) the US, this video won’t play without using a VPN or some other trickery as it’s region restricted.

The page uses an iframe, the content is from this URL: http://video.pbs.org/widget/partnerplayer/2365848966/?autoplay=true&start=0&end=0&chapterbar=false&topbar=false&endscreen=true

And it shows me this error (I’m in the UK):
> We're sorry, but this video is not available in your region due to right restrictions.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-info-does-video-on-pbs-org-not-play/10200

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
