### ISSUE TITLE
Bookmarks toolbar needs work

### ISSUE THREAD

**Issue by FringeWizard** [brave/browser-laptop#4409]
The screencap says it all. I want my bookmarks as icons along the top like in Firefox but it's not like that by default (it should be). There is also no possibility to put custom names beside each icon.

![screenshot from 2016-09-30 17-35-16](https://cloud.githubusercontent.com/assets/22552132/19007855/45db4eb4-8735-11e6-9243-1320b2d1671e.png)

**Comment by luixxiul** [comment]
Please open about:preferences and

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19010787/674d883c-87c1-11e6-8a01-3bf99d164db4.png)

and

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19010790/86881370-87c1-11e6-8366-da1471da8ebf.png)

**Comment by bsclifton** [comment]
@FringeWizard if the above settings don't work or if you have suggestions about how it could be better, please let us know :smile:
