### ISSUE TITLE
Crash: Closing an undocked chat window in Gmail crashes brave.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4415]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
When using the undocked chat window in Gmail, if you close the window, it will crash Brave.

**Expected behavior:**
The user should be able to continue using the app.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.3 RC5

- Steps to reproduce:
    1. Go to gmail
    2. Start a chat, undock it (the diagonal arrow icon)
    3. Close the window created by the chat

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
regression or also in 0.12.1?

**Comment by alexwykoff** [comment]
After moving the ~/Library/Application Support/brave folder, I've tried 0.11.6, 0.12.0, 0.12.1, 0.12.2, and 0.12.3 rc1, rc3, and rc5. 

None of them could reproduce. I am going to move my folder back and retry, then I will explore an upgrade from 0.12.1 to 0.12.3 to see if this is an electron update issue.

**Comment by alexwykoff** [comment]
Moved my folder back, could not reproduce.

Installed 0.12.1, opened google mail and then upgraded to 0.12.3 rc5, could not reproduce.

There is certainly a nuanced case, but @BrendanEich and I were able to hit it easily the first time around.

**Comment by alexwykoff** [comment]
Closing because we cannot reproduce. Will reopen if more concrete steps can be provided.
