### ISSUE TITLE
Regression: Pins without favicons are nearly invisible and indistinguishable from one another

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4418]
**Did you search for similar issues before submitting this one?**
Yes, this appears to be a regression

**Describe the issue you encountered:**
When pinning a page without a favicon the pin provided is a very close tint of the tab tray (which appears to be a shade, but it's all grey anyways). The pins are not distinguishable so it is confusing to the user as to which pin will show them the content they are looking for.

**Expected behavior:**
Pins for pages without favicons should have some unique means of identifying their contents to the user. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Win7 x64
- Brave Version:
  0.12.3 RC5
- Steps to reproduce:
  1. Visit pages without favicons (ex : alexwykoff.com , about:autofill, etc)
  2. Pin those pages
  3. Try to remember which pin leads to the site you want to visit
- Screenshot if needed:
  <img width="347" alt="screen shot 2016-10-01 at 10 27 24 am" src="https://cloud.githubusercontent.com/assets/1434040/19011206/b1d9a836-87c1-11e6-8d12-b673bd6710dd.png">
- Any related issues:
  https://github.com/brave/browser-laptop/issues/1260
  https://github.com/brave/browser-laptop/issues/1894

**Comment by alexwykoff** [comment]
@bradleyrichter I put this on 1.1 for the interest of keeping our burden light, if you have a simple solution, feel free to bump it up :)

**Comment by bradleyrichter** [comment]
when was it working?

**Comment by alexwykoff** [comment]
https://github.com/brave/browser-laptop/pull/1895 "fixes #1894"

I'm not sure if there was any OTR conversations about the design implications, but had assumed the fix would have been more robust than 'make it another grey'. :)

**Comment by bradleyrichter** [comment]
the fix would be:

if favicon = nada, then
      show default page icon instead

   ;    )

**Comment by cezaraugusto** [comment]
for now we have the default paper icon for when tabs have no favicons so seems to be fixed. Closing pls re-open if I'm mistaken
