### ISSUE TITLE
Regression: Bookmarks toolbar - Adding bookmarks to folders does not update the view

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4420]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
When adding a bookmark to a folder, it appears as though the system did nothing when in fact it moved the bookmark. 

**Expected behavior:**
When adding a bookmark to a folder, it should disappear from the toolbar view since it is now hidden in the folder.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 x64

- Brave Version:
0.12.3 RC5

- Steps to reproduce:
    1. Create some bookmarks and a folder in the bookmarks toolbar
    2. Add a bookmark to a folder

- Screenshot if needed:
![move_bookmark_into_folder](https://cloud.githubusercontent.com/assets/1434040/19011394/5e803862-87c6-11e6-9b53-ae20631948fa.gif)

- Any related issues:

**Comment by bsclifton** [comment]
@alexwykoff just to confirm, this behavior worked in 0.12.1? Curious because I can't repro w/ 0.12.3 RC5

**Comment by bbondy** [comment]
@alexwykoff ditto I can't repro. Maybe we need Steps to Reproduce that involves doing an import from chrome or bookmarks or something?   Maybe only triggered when 2 of the same imports? Need some additional steps.  If it's something strange we don't need to respin rc5.

**Comment by alexwykoff** [comment]
I moved the brave folder away and attempted to repro, also attempted to see if an upgrade scenario caused the issue. Could not reproduce for either.

**Comment by alexwykoff** [comment]
Closing this as DNR. If It is found again, I will reopen.
