### ISSUE TITLE
Brave crashes when Dashlane is selected 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4422]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave crashes when Dashlane is selected 

**Expected behavior:**
Should not crash

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.3 RC5 (Clean Install)

- Steps to reproduce:
    1. Install Brave 0.12.3 RC5
    2. Select Dashlane from Password manager
    3. Once the extension is loaded in about:extension Brave crashes
    4. Checked with 0.12.1 no crash, 0.12.3 RC3 no crash

- Screenshot if needed:

- Any related issues:

Issue not reproduced by @bbondy @bsclifton  with the same build. @alexwykoff @luixxiul  to check once on their VM boxes

**Comment by bbondy** [comment]
<img width="1140" alt="screenshot 2016-10-01 20 53 45" src="https://cloud.githubusercontent.com/assets/831718/19017967/a8eea2e6-881e-11e6-98ce-d5a2b7fb756e.png">
