### ISSUE TITLE
Make a loading spinner when extensions are being installed

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4427]
There's a short delay and people with bad connections might think it's not working currently.

**Comment by bsclifton** [comment]
[brave-core](https://github.com/brave/brave-browser) doesn't have spinners (or if it did show them, it was too brief to notice)... but users are prompted to allow the install of an extension. Afterwards, they're typically brought to an intro page (by the extension)

I think it's fair to say this workflow is completely different (than our current experience in browser-laptop), so I'll close this out as `wontfix`
