### ISSUE TITLE
No webpage loads

### ISSUE THREAD

**Issue by plieblang** [brave/browser-laptop#4428]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Visiting any webpage or any internal page results in a blank white page
**Expected behavior:**
Webpages should render
- Platform (Win7, 8, 10? macOS? Linux distro?):  Windows 10 Version 1607, Build 14393.222
- Brave Version:  12.1
- Steps to reproduce:
  1.  Open Brave 12.1
  2. Go to any webpage, or open Settings or anything else
  3. See the resulting blank white page that eventually resolves to about:error if you wait long enough
- Screenshot if needed:
- Any related issues:

**Comment by dave-hernandez** [comment]
Same here, Win10 1607 build 14393.222, I think this issue may have appeared after a reboot I performed yesterday and had some updates installed. Entirely possible a Windows update caused the issue?

**Comment by plieblang** [comment]
Definitely possible.  I installed the latest update on Thursday and noticed the behavior today.  I can't remember if I used Brave at all after installing the update.

**Comment by plieblang** [comment]
I rebooted in order to install the Windows Subsystem for Linux.  When I started Brave, it crashed, but later when I tried again it worked perfectly.

**Comment by dave-hernandez** [comment]
I can also confirm the second restart seems to have resolved the issue. Launched Brave immediately after a reboot and it seems to be working fine.

Oddly enough, Chromium was acting similarly, and it has also been resolved post reboot. Maybe they share some component that was affected (possibly) by an update.

**Comment by luixxiul** [comment]
The issue should be fixed with the latest release. Would you please give it a try again and see if it works fine? thanks!
