### ISSUE TITLE
Unexpected closure of Brave Browser

### ISSUE THREAD

**Issue by MikeHJones** [brave/browser-laptop#4430]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
1) When closing a tab via the close icon "X", Brave hangs and then closes completely
2) When clicking the star to bookmark a page, Brave hangs and then closes completely

**Expected behavior:**
1) Would expect the selected tab to close
2) Would expect the page to be bookmarked

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux.  Fedora 24

- Brave Version:
0.12.1
- Steps to reproduce:
    1. Close a tab
    2. Attempt to bookmark a page via the star icon
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bitcoinuser** [comment]
I think it's related to #4290

**Comment by diracdeltas** [comment]
closing as dupe, please reopen if it's still happening, thanks
