### ISSUE TITLE
Payment was processed but account balance was not refreshed

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4432]
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu

- Brave Version:

Dev Channel Beta 0.12.3dev-RC5

Obs: The account balance was refreshed after I turned Off and turned On Brave payments.

- Screenshot if needed:

![captura de tela de 2016-10-01 21-58-18](https://cloud.githubusercontent.com/assets/1178856/19017883/75425578-8823-11e6-990a-9633a0e8b534.png)

**Comment by mrose17** [comment]
@bitcoinuser - balances update after the blockchain says the the transfer is confirmed, and then there's a delay since the browser has to use polling to check the balance. 

i can't reproduce the problem. have you seen it again?

**Comment by mrose17** [comment]
closed due to lack of response.
