### ISSUE TITLE
Page very slow with unicode characters

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#4439]
#### Steps to reproduce:
1. Go to: https://gist.github.com/huw/8a564d1e8027294df15d

Problem: The page is loads long time, then it's very slow, and scrolling freezes. It's not possible to use this page properly.

Second problem: unicode aren't properly rendered.

The raw version of the page is at: https://gist.githubusercontent.com/huw/8a564d1e8027294df15d/raw/efee90826cadcdbf952406c4b9e2f1e30cd3c173/runes.py

When compared with Chrome, the scrolling works there, but not in Brave for the first few minutes.
#### Expected behavior

The page should work quicker. I've got MBP 2.3GHz Intel Core i7 with 16GB RAM and SSD HD.

Also unicode characters should work better as on this [page](http://puzzling.stackexchange.com/questions/37444/%E1%9A%AB%E1%9B%84-%E1%9B%9F%E1%9B%8B%E1%9A%B1-%E1%9B%97%E1%9A%A3%E1%9B%9A%E1%9A%A9%E1%9A%BB-%E1%9A%A9%E1%9A%AB-%E1%9A%B3%E1%9A%A6%E1%9A%B7%E1%9A%B9-%E1%9A%B9%E1%9B%9A%E1%9A%AB-%E1%9B%89) (consist the same unicode characters).
- Platform (macOS)
- Brave Version: 0.11.0
- Any related issues:

Chrome related bug: https://bugs.chromium.org/p/chromium/issues/detail?id=627523

Extra note: This page works without any issues in Safari.

**Comment by luixxiul** [comment]
The page loads fine on Windows 10. I confirmed it was loaded on MacBook Pro OS X quite slower than Windows 10.

**Comment by Liunkae** [comment]
The pages linked above work fine for me. Brave 0.13.5 on macOS 10.12.x.

**Comment by Liunkae** [comment]
Appears to be fixed. Closing (but please reopen if needed).

**Comment by luixxiul** [comment]
I'm not sure how slow it was for me on macOS, but it became tolerable, so +1 on closing.
