### ISSUE TITLE
Can I set cookies by site.   I have bank that requires cookies for selected areas but I do not want to globally enable cookies  Windows 10 Pro  Thank You

### ISSUE THREAD

**Issue by modelt1** [brave/browser-laptop#4441]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This is a great feature request!  An example screenshot was posted with the following issue (which you can subscribe to for updates) which proposes a allow/deny settings screen:
https://github.com/brave/browser-laptop/issues/4629

I'm going to close this issue as a duplicate.  Thanks :smile:
