### ISSUE TITLE
Add smart zoom functionality

### ISSUE THREAD

**Issue by mattbontrager** [brave/browser-laptop#4451]
The smart zoom feature (_two-finger double tap on trackpad_) in Safari is incredibly useful for those of us with less-than-great eye sight. I would use Brave a lot more if it had the same feature.

![](http://toolsdept.com/hosted-images/smart-zoom.gif)

**Comment by Liunkae** [comment]
Related: #1364 (Trackpad pinch to zoom)

**Comment by duvrai** [comment]
Actually to be more precise: 
- Trackpad: double-tap with two fingers
- Magic Mouse: double-tap with one finger

**Comment by twilsonco** [comment]
+1

**Comment by Liunkae** [comment]
Fixed in the new Chromium-based version of Brave:
![](https://user-images.githubusercontent.com/19424103/41733314-202f24f2-7549-11e8-8c91-afa9bb31cfad.gif)

**Comment by twilsonco** [comment]
Nice! Which build is that?

**Comment by Liunkae** [comment]
@twilsonco It's a development build of [brave/brave-browser](/brave/brave-browser). Still a few months away from being released to end users. See https://brave.com/development-plans-for-upcoming-release/

**Comment by bsclifton** [comment]
Closing this issue as `wontfix` since the fix won't be part of `browser-laptop`. As @Liunkae has shared, our new UI (Brave Core) has this fix by default 😄
