### ISSUE TITLE
Lock icon on the URL toolbar does not appear by reloading the same page with Paste and Go

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4456]
**Describe the issue you encountered:** The lock icon on the URL toolbar does not appear by reloading the same page with Paste and Go.

**Expected behavior:** It should appear.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.3 RC6
- Steps to reproduce:
  1. Open another github page. Make sure it is not opened on the window already. For example, https://github.com/brave/browser-laptop/projects
  2. Select the tab
  3. Copy the URL, and Paste and Go from the context menu on the URL bar

If you hit enter on the bar, the icon is replaced with the lock icon.
- Screenshot if needed:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19026221/0fb17946-895e-11e6-9f06-c979c7a76a0d.png)
- Any related issues:

**Comment by luixxiul** [comment]
Please set a milestone if necessary.

**Comment by bbondy** [comment]
cc'ing @diracdeltas for triage

**Comment by diracdeltas** [comment]
i can't repro this on the latest release. are you still seeing it?

**Comment by luixxiul** [comment]
Yes I do, on Windows 10.

**Comment by luixxiul** [comment]
This is still reproducible for me. If you switch the tab to another one, the icon is replaced with the lock icon.

**Comment by Liunkae** [comment]
I can't reproduce with 0.12.9.

**Comment by luixxiul** [comment]
this can no longer be reproduced.
