### ISSUE TITLE
Autofill data sometimes not deleted

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4457]
**Describe the issue you encountered:** The autofill data which has been deleted from about:autofill sometimes appears in the autofill pulldown. After deleting from the submenu inside history, it no longer does not appear in the pulldown, and it seems that it was cleared successfully.

**Expected behavior:** The data should be surely deleted from about:autofill.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.3 RC6
- Steps to reproduce: I am not sure.
- Screenshot if needed:
- Any related issues:

**Comment by darkdh** [comment]
this should be fixed by https://github.com/brave/browser-laptop/pull/4659
feel free to reopen it if not working
