### ISSUE TITLE
Go forward button with command key does not open the forwarded page 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4459]
**Describe the issue you encountered:** Go forward button with command key does not open the forwarded page. Go back button does work as it should.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: https://github.com/brave/browser-laptop/tree/b27f6ad47015e7f330ae3ed39e86b2c3f1061a17
- Steps to reproduce:
  1. Open https://github.com/brave/browser-laptop in a new tab
  2. Click "Issues"
  3. Go back with the button on the navigation bar
  4. Go forward with the button, pushing <kbd>command</kbd> key

Expected result: The issues page should open in a new tab with the session history
Actual result: https://github.com/brave/browser-laptop is opened 
- Any related issues:

**Comment by Liunkae** [comment]
Confirmed with Brave 0.12.3 on macOS 10.12.

**Comment by Liunkae** [comment]
I can no longer reproduce with Brave 0.13.2 on macOS 10.12.x.

**Comment by luixxiul** [comment]
Me neither.
