### ISSUE TITLE
Text rendering looks worse in macOS in Brave than Safari

### ISSUE THREAD

**Issue by rtsuk** [brave/browser-laptop#446]
The headline looks particularly worse to my eye. It looks exactly the same as Chrome on Mac.

![brave](https://cloud.githubusercontent.com/assets/314561/12684989/992bc8b2-c676-11e5-8a65-373babfe0a8a.png)
![safari](https://cloud.githubusercontent.com/assets/314561/12684990/99321f14-c676-11e5-9137-d1702252f433.png)
![chrome](https://cloud.githubusercontent.com/assets/314561/12685055/f7f2da98-c676-11e5-9294-a66f0c627941.png)

**Comment by wblondel** [comment]
I can't see any differences between the three screenshots :open_mouth:

**Comment by doriandrn** [comment]
It's all about font-smoothing rendering.

**Comment by luixxiul** [comment]
Was this fixed? CC'ing @bradleyrichter

**Comment by Liunkae** [comment]
Is this still a problem?

**Comment by Liunkae** [comment]
As of 0.13.0, the text rendering looks the same to me.

Example: https://www.apple.com/newsroom/2017/01/apple-fy-17-first-quarter-results-conference-call.html

Brave:
![image](https://cloud.githubusercontent.com/assets/19424103/22386627/9cdf989e-e49d-11e6-9591-06191351383e.png)

Safari:
![image](https://cloud.githubusercontent.com/assets/19424103/22386693/eb5e9e98-e49d-11e6-8dd6-21a2f8037168.png)

**Comment by Liunkae** [comment]
No recent reports. Closing (but please reopen if needed).
