### ISSUE TITLE
Cosmetic : Bookmarks toolbar expansion menu '>>' truncates the final bookmark title.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4460]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When expanding the bookmarks toolbar menu, it was found that the final bookmark was being truncated by the bottom of the window.

**Expected behavior:**
The bookmark should not be truncated.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 x64

- Brave Version:
0.12.3 RC6

- Steps to reproduce:
    1. On a clean install, import A LOT of bookmarks.
    2. Using the bookmarks toolbar, use the `>>` expansion.
    3. Scroll to the bottom of the list.

- Screenshot if needed:
<img width="515" alt="screen shot 2016-10-03 at 12 51 31 pm" src="https://cloud.githubusercontent.com/assets/1434040/19027931/c0dcad80-8968-11e6-9308-e63224b7bd96.png">

- Any related issues:

**Comment by bbondy** [comment]
I didn't repro this on macOS but haven't tried on windows

**Comment by jkup** [comment]
Can't repro on Windows either. Maybe it was fixed by another change?
![screen shot 2016-10-13 at 2 50 27 pm](https://cloud.githubusercontent.com/assets/490294/19368343/726b8948-9154-11e6-8e20-f39d9aae609b.png)

**Comment by bbondy** [comment]
@alexwykoff please re-open if you have STR, like maybe it is only with certain DPIs?
