### ISSUE TITLE
Regression: Brave Payments : Ledger headers should not disappear while scrolling.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4461]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Per https://github.com/brave/browser-laptop/pull/4085 the ledger headers should stay at the top while the individual publisher information should scroll for long lists.

**Expected behavior:**
If a user has many publishers in their ledger history, when they scroll, the headers should remain visible.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Win7 x64

- Brave Version:
0.12.3 RC6

- Steps to reproduce:
    1. With a clean install, enable Brave Payments and visit A LOT of sites.
    2. On the Brave Payments preference pane, scroll down.
    3. Observe that the headers remain fixed at the top of the columns and do not disappear.

- Screenshot if needed:
![ledger_headers](https://cloud.githubusercontent.com/assets/1434040/19028107/cd2eff46-896a-11e6-8d72-b513d2fc074c.gif)

- Any related issues:

**Comment by jkup** [comment]
I think this is fixed now that the sticky header patch is in. Can you verify on your end @alexwykoff?

**Comment by bbondy** [comment]
Marking as closed  since the expectation is that it's fixed. (QA will re-open if a bug).
@jkup do you have the changeset you think it was fixed in?

**Comment by jkup** [comment]
@bbondy this PR https://github.com/brave/browser-laptop/pull/4395
