### ISSUE TITLE
F6 does not jump to url / search bar

### ISSUE THREAD

**Issue by DanielvV** [brave/browser-laptop#4464]
**Did you search for similar issues before submitting this one?**
Searched 'F6'

**Describe the issue you encountered:**
F6 does not work

**Expected behavior:**
F6 changes focus textcursor to url bar
- Ubuntu 16.04
- Brave: 0.12.1
- Steps to reproduce:
  1. push F6

**Comment by bbondy** [comment]
Which browser(s) support this shortcut? Thanks

**Comment by srirambv** [comment]
@bbondy  This is the standard feature on Chrome & FF.

**Comment by bbondy** [comment]
Verified on Firefox for macOS but doesn't do anything for Chrome for macOS, I wonder why. I guess works for both on Windows / Linux?

**Comment by DanielvV** [comment]
@bbondy Yeah, on Win7 and Linux:
FF jumps to URL bar and back to body
Chrome jumps to URL bar, then to bookmarks bar and back to body
IE11 on Win7 does the same

When starting Brave (with about:blank as homepage) the URL/Search bar 
is not selected
That is also something in other browsers.

Op di, 4 okt 2016 om 4:37 , schreef Brian R. Bondy 
<notifications@github.com>:

**Comment by DanielvV** [comment]
Alt+Home ('go to home page') doesn't work either.
And Alt+Left Arrow / Alt+Right Arrow ('go to previous / next page')
That is the default behaviour for Chrome and FF on Ubuntu.
(I see that Shift+Backspace and Backspace does the same for Brave)

Do we need to create separate issues for them?
Or can we make a grand "Standard keyboard shortcuts" issue, agregating all simple shortcut ideas like this one and #1092 and others?

Would be nice to do a search on "keyboard shortcuts webrowsers":
http://www.howtogeek.com/114518/47-keyboard-shortcuts-that-work-in-all-web-browsers/
http://dmcritchie.mvps.org/firefox/keyboard.htm
