### ISSUE TITLE
Search / URL bar not working

### ISSUE THREAD

**Issue by lukemroz** [brave/browser-laptop#4466]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Search bar does not work at all.  I enter a search term or URL, press enter, and nothing happens.  After pressing enter, the search bar is cleared.  I am able to open a tab to the internet, and can follow hyperlinks after selecting 'submit feedback' from the drop down menu (since it automatically opens a tab of a URL). 

**Expected behavior:**
I expect to be able to type a URL into the search bar, press enter, and have a browser tab load the webpage served from that URL.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS Name	Microsoft Windows 8 Pro
Version	6.2.9200 Build 9200
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	LUKE-PC
System Manufacturer	ASUSTeK Computer Inc.
System Model	U43F
System Type	x64-based PC
System SKU	0
Processor	Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz, 2667 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 216, 11/12/2010
SMBIOS Version	2.6
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	PEGATRON CORPORATION
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "6.2.9200.16442"
User Name	Luke-PC\Luke
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	6.00 GB
Total Physical Memory	5.80 GB
Available Physical Memory	2.85 GB
Total Virtual Memory	11.8 GB
Available Virtual Memory	8.43 GB
Page File Space	6.00 GB
Page File	C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

- Brave Version: 0.12.1 (latest version available for download)

- Steps to reproduce:
    1.  Download latest version of Brave
    2.  Enter a URL into the search bar (it doesn't work)

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
Have you ever installed a previous version of Brave? This could be related to #3254.

**Comment by lukemroz** [comment]
Hello,

Following the instructions from that link worked.  I did not have a default
search engine enabled.  By selecting a search engine, the searchbar started
working for both searches and for full URL addresses.

I did have a previous version of Brave that had the same problem (months
ago).  I uninstalled it, installed the latest version today, and was having
the searchbar problem, so I filed the bug.  By manually selecting a default
search engine, the error was fixed.

Problem solved, thank you!

**Comment by Liunkae** [comment]
Glad to know the problem is solved!

**Comment by lukemroz** [comment]
A question worth pursuing:

If there is no default search engine selected, why doesn't brave recognize
a fully formed URL in the search bar and open a corresponding tab?

**Comment by Liunkae** [comment]
The urlbar in Brave apparently works under the assumption that there is a default search engine set. If there is no search engine set, Brave is _supposed_ to set it to Google (I think). However, there was a bug in a previous version that prevented this from happening.

I'm not sure if removing this assumption is easy to fix/worth fixing.

This is from what I understand (but I'm not a Brave developer). However, I think you bring up an interesting point.

**Comment by drozzy** [comment]
This is still happening to me occasionally. OSX.

**Comment by drozzy** [comment]
Pressing Enter doesn't do anything a lot of the time.

**Comment by UnarmedBlack** [comment]
Same problem as drozzy. Entering a url or text into the search field does nothing. Hitting enter and the search button also.
