### ISSUE TITLE
Saved Password and ID do not work

### ISSUE THREAD

**Issue by mandyloman** [brave/browser-laptop#4467]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
I clicked on my favorites bar for my email. It comes up with letters in the login all jumbled up and I cannot type in the login id bar. I click login and it says incorrect password
**Expected behavior:**
It should just log me in when I hit enter
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  unsure
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue.

If you are still around here, would you please join https://community.brave.com to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
