### ISSUE TITLE
HTML5 Player Right Click

### ISSUE THREAD

**Issue by hasanhuseyincakir** [brave/browser-laptop#447]
For instance on Youtube when you click right over an HTML5 player, it shows both browser's & player's right click options.
http://i.imgur.com/ceLxPy5.png

**Comment by TheFallenOneGOTH** [comment]
Confirmed for Windows 10 v10586.71 (Version 1511).

**Comment by luixxiul** [comment]
Confirmed, but slightly different.

1. 1st click opens the player's option
2. 2nd click opens the browser's option

How do you think, @bbondy?

**Comment by cezaraugusto** [comment]
Same as @luixxiul.

FFI both Firefox and Safari closes the custom context menu (first to open) and opens the default one in a way that both cannot be opened together.
