### ISSUE TITLE
Brave payments suggestion: ledger reset after payment

### ISSUE THREAD

**Issue by msp1111111** [brave/browser-laptop#4470]
I had my payments to my websites go out on October 1, but my ledger has not reset. It continues to add to the number of visits and times that I had before payment was made. Maybe it would be better if the ledger reset all visits/times to zero after each monthly payment? This is because I will not be visiting certain sites this month that I did last month, yet with this system, they will still get paid.

0.12.3
Windows 7

**Comment by mrose17** [comment]
that is a design intent! the ledger keeps track of the last 30 days rolling. as time goes on, the synopsis will change to reflect the last 30 days of viewing...
