### ISSUE TITLE
Mouse scrolling wheel issues

### ISSUE THREAD

**Issue by mpdonnelly** [brave/browser-laptop#4472]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
**When opening a link which causes a new tab to be opened**, your scrolling behavior can be broken

Reported behaviors include:
- Page up/ page down don't work
- Can't scroll down
- not being able to scroll at all, to the page autoscrolling to the bottom of the page upon loading, to erratic scrolling
- refuses to scroll and sometimes oddly jumps around

Work around:
- copy/paste the URL into the URL bar and hit enter

**Expected behavior:**
You should be able to scroll

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce (courtesy of @SlavikCA):
    1. Open 1st site (I open https://news.google.com/)
    2. Click on the link (any news article), which opens in new tab
    3. Try to scroll with middle mouse, page up, page down
    4. Notice that you can't scroll :disappointed: 

- Any related issues:
https://github.com/brave/browser-laptop/issues/4285 (possible dupe)
https://github.com/brave/browser-laptop/issues/4508 (closed as dupe)
https://github.com/brave/browser-laptop/issues/4515 (closed as dupe)
https://github.com/brave/browser-laptop/issues/4527 (closed as dupe)
https://github.com/brave/browser-laptop/issues/4547 (closed as dupe)
https://github.com/brave/browser-laptop/issues/4530

**Comment by silverslimer** [comment]
I can confirm that scrolling is functioning poorly. When I use it, it scrolls all the way to the bottom regardless of how slightly I slid the wheel.

**Comment by csolve** [comment]
Scrolling inoperative on some websites. Scroll wheel doesn't function, and scroll bar on right side of browser just flashes and sometimes will scroll down the page. 

Followed a link to https://www.yahoo.com/ and cannot navigate with scroll wheel or browser bar.

**Comment by AaronLenoir** [comment]
Since 0.12.3 having the same behavior on windows 10. Scrolling either puts the page at the top or at the bottom, or it does nothing sometimes.

In my case, it only seems to happen when I click through from links on twitter.com (which is currently a pinned tab, but unpinning doesn't change the behavior). Clicking through to a link on this page, for example, doesn't produce the behaviour.

On the pages where it happens, if I click through to a link using ctrl + click (open in new tab) the issue is not there in the new tab. But if I open the link in the same tab the issue is still there.

Also, when I manually paste the address in a new tab, it doesn't occur either.

**Comment by SlavikCA** [comment]
Not sure, if related.
For this site, scrolling doesn't work at all - not with mouse, not with PgUp, PgDown:
https://www.washingtonpost.com/world/russia-suspends-plutonium-deal-with-us/2016/10/03/c502e628-8980-11e6-8cdc-4fbb1973b506_story.html

home is working ok

**Comment by privatzee** [comment]
I had this same problem on a github page. The problem was confined to only that one tab. I pasted the URL into a new tab and that tab/page worked fine.

**Comment by Kzeir** [comment]
Me too: One of the Web Pages is this [http://www.gearbest.com/cell-phones/pp_363558.html](url)..

**Comment by KVtemp** [comment]
Issue seems to occur following an outbound link that opens a new tab with either left click or mouse wheel click. As far as I can tell, pages that do not open a new tab when left clicked do not have issues, even when opened with mouse wheel click.

Opening with right click & "Open Link in New Tab" does not have issues. Neither does copy-pasting link address .

**Comment by admiral142** [comment]
I've had scrolling issues since the latest update as well.

**Comment by bsclifton** [comment]
Hey there folks! I'm digging into this issue and hope to find the root cause

I was easily able to reproduce on Windows 10

**Comment by bsclifton** [comment]
If you're having this problem on Windows, give this post a big thumbs up

**Comment by bsclifton** [comment]
If you're having this problem on a Mac or Linux, give THIS post a thumbs up (icon in the top right, the plus / smiley face)

**Comment by bsclifton** [comment]
@admiral142 @KVtemp @Kzeir @SlavikCA @mpdonnelly @privatzee @AaronLenoir and others- what platform are you all on? Windows? Mac?

You can click the smiley button in one of the two posts above to let me know or just reply to this comment
![screen shot 2016-10-04 at 4 50 48 pm](https://cloud.githubusercontent.com/assets/4733304/19096628/bdb23856-8a52-11e6-8a71-0e87a7ca2f0f.png)

**Comment by bsclifton** [comment]
user @Consoledotlog reported this issue also in https://github.com/brave/browser-laptop/issues/4527 with the following setup:
- Windows 10 64bit post Anniversary Update
- Brave 0.12.3
- Sites visited include: Google Forums, Google Keep, and other Google associated sites

**Comment by privatzee** [comment]
I've got Win7 x64, as stated above. It happens anywhere that I tested with a tab opened via a target attribute in a link.

**Comment by bsclifton** [comment]
@privatzee thanks! and I believe you're correct, it seems to be related to target=_blank (I haven't proven it yet, but it seems consistent)

**Comment by Kzeir** [comment]
I've windows 10 64bit Anniversary Update  too..

*Att: Alessandro Tetsuo More*

2016-10-04 22:04 GMT-03:00 Brian Clifton <notifications@github.com>:

**Comment by bridiver** [comment]
the problem does appear to be restricted to renderer initiated new tabs which would include things like targets and window.open

**Comment by texandirt88** [comment]
One website is http://breitbart.com on windows 10 platform.

**Comment by bsclifton** [comment]
Great news folks! A work-around has been found :)

@bridiver dug deep into the Chromium code and it appears this issue was introduced in our upgrade to Chromium 53.0.2785.116.  Specifically, the problem is related to functionality introduced by this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=613414

We're working through the remaining issues and hope to have a new release soon. Please bear with us as we finish up testing- we want to make sure we're offering everybody a solid fix and not something which fixes this but introduces other issues.

Thanks :smile:

**Comment by bsclifton** [comment]
And the new version of Brave with the fix is live! Thanks for being patient, folks! Let us know how this new version looks :smile:

**Comment by bbondy** [comment]
0.12.4 fixes this problem and is available now. Thanks for your patience!

**Comment by privatzee** [comment]
Works fine now in Brave 0.12.4  Win7 x64
Thanks @bsclifton, for having posted the explanation as to why it happened.
