### ISSUE TITLE
Brave Covers Auto-Hiding Taskbar

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4473]
**Describe the issue you encountered:**

> The new @brave browser on fullscreen prevents my hidden taskbar from appearing. Can you fix it? (https://twitter.com/icecoldsquirrel/status/782996130766389248)

**Expected behavior:**

Taskbar should not be hidden by Brave.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 8.1, Windows 10
- Brave Version: 0.12.3
- Steps to reproduce:
  1. Place taskbar at top of screen, and auto-hide
  2. Maximize Brave
  3. Note that taskbar can't be revealed by mouse
- Screenshot if needed:
- Any related issues:
  - https://github.com/brave/browser-laptop/issues/4149

**Comment by icecoldsquirrel** [comment]
I found out that's only an issue if you try it on your main display. In my case it works if I maximize brave on the second display.

**Comment by lgulseth** [comment]
My taskbar is on the left side, same issue. Also, when not maximized, but filling the screen, Brave is moved off the screen when the taskbar unhides. Like Brave doesn't want to stay underneath an autohid taskbar.

**Comment by jonathansampson** [comment]
A [user on Twitter](https://twitter.com/Baspower_/status/825097792045666306) also recently ran into this issue.

**Comment by BillibongBoil** [comment]
I have same issue with Brave Browser in Win7 x64

Moving my cursor to the bottom of the page does NOT bring up my Windows Taskbar.  To get access to the Windows Taskbar I have to bring cursor over to upper right hand and click the minimize window bar to get access to the Windows Taskbar.  This is far too inefficient for me to continue using this browser.  [I require the ability to quickly move between Browser and other windows programs.  Having no quick access to the windows taskbar makes Brave Browser incompatible to my needs.]

If anyone has a solution to this problem, please let me know.  Click upper right hand window corner "maximize" or "restore down" has no effect upon my lack of quick access to my windows taskbar.

**Comment by eljuno** [comment]
+2 [from community](https://community.brave.com/t/didnt-showing-when-i-point-to-mouse-on-task-bar-after-i-open-brave/1642?u=eljuno).

**Comment by LaurenWags** [comment]
+1 from communityhttps://community.brave.com/t/maximized-window-on-top-of-taskbar/2750

**Comment by HelterBelter** [comment]
+1 
Win 8.1 on dual-screen (laptop & external LCD - - external LCD is primary screen)
And same as reported above, if I maximize on secondary screen taskbar will appear

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/windows-7-sp1-task-bar-not-accessible-when-using-brave-browser/14879?u=eljuno

>I have the task bar hidden to the right on the screen. When I pass my cursor to the right side on the screen the task bar is supposed to slide into view but with Brave the Windows task bar does not appear when I pass the cursor to the right on the screen.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1018
