### ISSUE TITLE
Microphone doesn't work properly in Duolingo

### ISSUE THREAD

**Issue by BeachLoverInNM** [brave/browser-laptop#4476]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by BeachLoverInNM** [comment]
Using Windows 10 Anniversary Update. Using Duolingo to learn Spanish. During lessons a microphone icon will appear. User is supposed to click it and speak. The program then evaluates what is said. However, in Brave when I click the icon instead of recording me and giving feedback, it immediately gives me an error message and moves on. I was initially prompted whether I wanted to enable the microphone/camera and I responded yes. I double-checked this in Settings. Microphone does not work as it is supposed to on the Duolingo page within Brave.

**Comment by stcole** [comment]
I can confirm the same problem exists on Mac OS X 10.12.2 with Brave 0.13.2.

**Comment by vito-dante** [comment]
Same problem in Ubuntu 16.04 with Brave 0.13.5

**Comment by MatthewMcguire** [comment]
Same issue on Mac 10.12.4 with Brave 0.15.2.

**Comment by datenreisender** [comment]
This problem still persists with Brave 0.20.42 on macOS 10.13.3. 😞

**Comment by eljuno** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8ui0iy/mic_input_not_working/

**Comment by The-Critic** [comment]
Still persists on Version 0.62.50 Chromium: 73.0.3683.86 (Official Build) (64-bit) Windows 10 home Version	10.0.17134 Build 17134. Shields off, microphone enabled, instantly fails as if microphone not detected. Microphone works on other websites.

**Comment by bsclifton** [comment]
@The-Critic this repository (`browser-laptop`) is deprecated and will be archived soon

You can check out the new version of this issue here (and subscribe for updates) 😄 
https://github.com/brave/brave-browser/issues/3725
