### ISSUE TITLE
Wouldn't click

### ISSUE THREAD

**Issue by the-saint** [brave/browser-laptop#4480]
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**

I was on a contest page. There was a graphic of yogurt and it said: "Click the spoon." I clicked the spoon but nothing happened. I switched over to Safari and it worked fine.

**Expected behavior:**

It should have done something when I clicked.
- Platform (Win7, 8, 10? macOS? Linux distro?):

MacOS
- Brave Version: 0.12.3
- Steps to reproduce:
  1. You'd have to buy Yoplait yogurt and sign up on their page in order to reproduce the issue.
     2.
     3.
- Screenshot if needed:
  <img width="1233" alt="screen shot 2016-10-03 at 3 44 19 pm" src="https://cloud.githubusercontent.com/assets/12885935/19056818/54ba9ff0-8980-11e6-9608-75a5faaa30cb.png">
- Any related issues:

**Comment by privatzee** [comment]
Unfortunately, the promo seems to be over; so can't do any diagnosing:
https://yoplait.promo.eprize.com/

> We can't find the page you're looking for. It has either expired or is temporarily out of commission.


@luixxiul Does this then get closed?

**Comment by luixxiul** [comment]
I'd leave this open as another issue can occur on the same domain.

**Comment by the-saint** [comment]
You have to start here, sign up or login on the right, and then enter a code from a yogurt lid. Then it takes you to the page to see if you won instantly.

https://yoplait.promo.eprize.com/flavors/

**Comment by luixxiul** [comment]
The site has been shut down. I'm going to close this one.
