### ISSUE TITLE
Aggressive notification

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#4481]
The info bar “Hello!Good news! Brave will pay your favorite publisher sites in less than 24 hours.” is way too aggressive. There is no way to dismiss the toolbar (no X). If you give in and click the one and only weirdly labeled button, the toolbar is dismissed temporarily only to reappear a short while later.

I must have dismissed the bugger ten times today.

It also appears inside tiny pop-up windows (like social logins and the like). Only site-specific toolbars should ever appear inside these small windows opened with JavaScript (see behavior in every other browser).

Once I’ve opened `about:preferences#payments` from the toolbar, don’t show me the notification again until next month.

**Comment by bbondy** [comment]
Just seconding that I also wanted to hit an X when I seen the toolbar.   Also I did see the notification twice for some reason, but I don't remember if it was with a startup in between or what else happened to give me that result.

**Comment by bsclifton** [comment]
I got hit up about this over Twitter recently
https://twitter.com/thickSLICING/status/783004708407545856
