### ISSUE TITLE
AudioContext fingerprinting Protection partly fails

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#4483]
**Did you search for similar issues before submitting this one?**
Yes, but how do I prevent an endless number of "Manual tests..." in the results? I searched for--> is:issue fingerprinting 
**Describe the issue you encountered:**
I get real output _only_ from this one test:
AudioContext properties:

{
  "ac-sampleRate": 48000,
  "ac-state": "running",
  "ac-maxChannelCount": 2,
  "ac-numberOfInputs": 1,
...

**Expected behavior:**
"The fingerprint values should be blank or all 0's." from: https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-turn-on-browser-fingerprinting-protection-and-make-sure-that-its-working

- Platform = Win7

- Brave Version: 0.12.3  (today's update) and also the previous version

- Steps to reproduce:
    0. go to about:preferences#shields and check the 'Fingerprinting Protection (may break some websites)' option
    1. start at: https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode
    2. click to go to: https://audiofingerprint.openwpm.com/
    3. click 'Fingerprint me!' button

- Screenshot if needed:

- Any related issues:

------
@diracdeltas

**Comment by diracdeltas** [comment]
Sorry if the page was unclear. The AudioContext properties are not blank, but the fingerprint values at the bottom of the test page should be 0. Is that what you're seeing?

**Comment by privatzee** [comment]
> Is that what you're seeing?
Yes, everything else is either blank or all zeros. Thanks for clearing that up..
