### ISSUE TITLE
download list is out of order

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#4484]
**Did you search for similar issues before submitting this one?**
Yep.
**Describe the issue you encountered:**
See screenshot below. The Electron setup file was the most recent file to download, but it's not on top. You can see that it's actively downloading at 13% and was started well after all other downloads were complete.
**Expected behavior:**
most recent on top
- Platform = Win7
- Brave Version: the one right before 0.12.3
- Screenshot if needed:
  ![brave downloads](https://cloud.githubusercontent.com/assets/22591438/19058731/b7e1e0ee-89a7-11e6-8fcd-90a94a0b0c54.jpg)

**Comment by unsystemizer** [comment]
Ran into this just now, with a tab full of downloads, the ongoing one was at the bottom, 

Expected: active downloads in slightly different color (and/or at the top of the list).

Brave: v0.12.7
OS: Windows 10 x64
