### ISSUE TITLE
Relaunch only relaunched the active window

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#4486]
**Did you search for similar issues before submitting this one?**
Yep.
**Describe the issue you encountered:**
Clicking to relaunch and install the latest update only relaunched the active window. A second open window was not re-opened.
**Expected behavior:**
All previously open windows should be re-opened upon relaunching to install the update.
- Platform (Win7
- Brave Version: right before the 0.12.3 update
- Steps to reproduce:
  1. wait for next update?
- Screenshot if needed:

![](https://cloud.githubusercontent.com/assets/22591438/19058731/b7e1e0ee-89a7-11e6-8fcd-90a94a0b0c54.jpg)

**Comment by luixxiul** [comment]
I think this has been fixed basically. Though sometimes windows are lost, it would be based on other causes than this issue.
