### ISSUE TITLE
Help -> Submit Feedback is not opening the mail client for certain users

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4487]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
@bbondy and myself are unable to use the Submit Feedback action on the Help menu.

**Expected behavior:**
Users should be able to easily ask for help

- Platform (Win7, 8, 10? macOS? Linux distro?):
Discovered on OS X.

- Brave Version:
0.12.3 RC6 (production)

- Steps to reproduce:
    1. Open Help -> Submit Feedback.
    2. Check to see if your mail client is opened.

#1604 #3016

**Comment by diracdeltas** [comment]
if you go to https://brave.com/ and click the support@brave.com link at the bottom of the page, what happens?

**Comment by alexwykoff** [comment]
I am asked the following:
<img width="1437" alt="screen shot 2016-10-04 at 11 02 23 am" src="https://cloud.githubusercontent.com/assets/1434040/19061295/3a4d212c-8a22-11e6-855d-781e83dfd394.png">

After clicking on 'Allow', nothing happens.

**Comment by diracdeltas** [comment]
do you by chance have gmail set as your default mail protocol handler?

**Comment by alexwykoff** [comment]
From what I searched, it would not appear to be the case. I logged into mail.google.com and observed the following:
<img width="1440" alt="screen shot 2016-10-04 at 11 30 35 am" src="https://cloud.githubusercontent.com/assets/1434040/19061771/18bf920c-8a26-11e6-99a6-c18566c60a96.png">

**Comment by Liunkae** [comment]
Related: #2966

**Comment by alexwykoff** [comment]
This is working on Ubuntu, but my mbp still exhibits the issue. Any suggestions for investigation?

**Comment by bbondy** [comment]
I'm guessing you just need to properly set your default mail client to Brave or something else and it is set to some old version of Brave currently or something else that doesn't work. 
I'd recommend using this app to sort out the defaults:
http://www.rubicode.com/Software/RCDefaultApp/

You can browser to the default for mailto: and make sure you select Other, and then go select the .app file in /Applications for Brave.
