### ISSUE TITLE
As a user, I want to be made aware that I need to enable tracking in order to use Facebook services

### ISSUE THREAD

**Issue by pcomans** [brave/browser-laptop#449]
I can only log into https://www.scribd.com/ with my Facebook account if I enable tracking.
I think breaking this "feature" is legitimate and in line with Brave's principles.
However, as a user, I would like to be made aware how I can turn off tracking in order to log in, instead of the process just failing silently.

A similar issue occurs when using Facebook messenger through messenger.com

**Comment by luixxiul** [comment]
Closing as now you don't have to enable tracking to log in. Thanks anyway.
