### ISSUE TITLE
Selecting regional adblock lists causes a crash

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4491]
**Describe the issue you encountered:** Selecting regional adblock lists causes a crash.

**Expected behavior:** It should not cause a crash.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/16cedabee2e986c11f37b9ab57f5c8861d921fe0

- Steps to reproduce:
    1. Open about:preferences#shields
    2. Click "Manager Adblock Settings..."
    3. Click the toggle of JPN: ABP Japanese filters (日本用フィルタ)

- Any related issues:

**Comment by luixxiul** [comment]
Hitting any key inside the custom filters also causes a crash.

**Comment by bbondy** [comment]
Ya this is reproducible 100% on the packaged build. You might want to test the feature on a dev-build for now until I fix this.
