### ISSUE TITLE
Need to change wording for Manager Adblock Settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4498]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Need to change wording for Manager Adblock Settings

**Expected behavior:**
Should either be Mange Adblock Settings or Adblock Settings Manager

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.4dev-Preview1

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Fixed here: https://github.com/brave/browser-laptop/commit/3f942d68fdf5136d0f30137b3d21334026515837

**Comment by bbondy** [comment]
oops didn't see this issue in time, but saw an issue on Transifex for it.  Thanks for closing.
