### ISSUE TITLE
Add the ability to close developer tools via keyboard shortcut on macOS

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#45]
After opening content dev tools, you can't use the local shortcut to close them again. 
STR:
1. Command+Option+I to open dev tools
2. Command+Option+I to close dev tools

Expected results:
It closes even though the devtools window has focus

Actual results:
You need to focus back to the parent window first.

@bridiver maybe we need to register with localShortcut the devtools window?

**Comment by LoloIrie** [comment]
BTW, shortcut for the dev tool should be F12 like other browsers

**Comment by bbondy** [comment]
@LoloIrie F12 added for 0.9.0.
Leaving this open for the original issue though.

**Comment by weems** [comment]
@bbondy maybe also tangential to this. but I have submitted a issue also regarding devtools: https://github.com/electron/electron/issues/5022. We are unable to show any SSL Connection Data in Brave due to some issue with electron. Compared with Chrome implementation which has visibility to all SSL Certificate and Connection Details. Are we seeking to patch or wait for electron to make upstream changes when we have electron concerns?

**Comment by bbondy** [comment]
Yep I'm aware of that one as well but pls ask any questions about its prioirty in the context of that bug.

**Comment by weems** [comment]
@bbondy thanks.

**Comment by alexwykoff** [comment]
Still an issue in 0.12.8. Prioritizing to 1.2

**Comment by anasant** [comment]
+1 on request for cmd+W to close dev tools window

**Comment by Liunkae** [comment]
+1 from #3044 and #6191.

**Comment by Liunkae** [comment]
Related to: #3343

**Comment by luixxiul** [comment]
On Win10 32bit:

Ctrl+Shift+I to open dev tools -> it works
Ctrl+Shift+I to close dev tools -> it does not

**Comment by luixxiul** [comment]
@bbondy would you mind providing another STR if any? thanks!

**Comment by srirambv** [comment]
Doesn't work on Win 10 x64 with 0.15.3 preview 3

**Comment by alexwykoff** [comment]
OS X : 
attempt to open developer tools via the keyboard shortcut, no window is opened
attempt to open developer tools via the menu, no window is opened

**Comment by bsclifton** [comment]
@bbondy wasn't this fixed by reverting the share functionality?

**Comment by bsclifton** [comment]
ready for re-testing

**Comment by bbondy** [comment]
This was originally implemented correctly, but broken in this commit:
https://github.com/brave/browser-laptop/commit/f4283c0053569842773d5d6aca91825b55732ba3

**Comment by luixxiul** [comment]
On debian with .304

1. Command+Option+I to open dev tools -> works
2. Command+Option+I to close dev tools -> does not work

**Comment by luixxiul** [comment]
My bad, I was on the wrong version. I confirmed it has been fixed.

**Comment by luixxiul** [comment]
Retesting on .304 by deleting the profile, I still cannot confirm the issue was fixed.

**Comment by srirambv** [comment]
Confirmed not working on Windows.

**Comment by bbondy** [comment]
@luixxiul @srirambv @alexwykoff 
Turn out the fix applied here will only work on macOS because it works via sending a Window shortcuts and only on mac is the shortcuts app level.

I renamed the title for this to be specific to mac and I posted a new issue here to track the work on the other platforms:
https://github.com/brave/browser-laptop/issues/8935

Please test this only on mac.
