### ISSUE TITLE
Consider automatically enabling regional adblock lists based on default language

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4500]
There are 2 considerations:
1) Should we automatically enable regional adblock lists based on the default language?
2)Should we automatically enable regional adblock lists based on the selected language?

**Comment by bsclifton** [comment]
+1 from @alexwykoff via https://github.com/brave/browser-laptop/issues/14209
> We'd like to have regional adblocking enabled just like Android.

The specific regional adblockers which are enabled by default in Android should be reflected in the desktop.
