### ISSUE TITLE
Sort adblock filter lists alphabetically

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4501]
## Test plan

1. Open about:adblock
2. a, b, c, d, ...

----

To sort adblock filter lists alphabetically,

> you can just modify this file for the abp-filter-parser-cpp library:
> https://github.com/bbondy/abp-filter-parser-cpp/blob/master/lib/regions.js and update the package.json version’s Z by a x.y.Z
- Any related issues: #1357

The fix is just to re-order that array of objects.

**Comment by Jacalz** [comment]
I can try to fix this but should it be aranged alphabetical with the three first letters (DEU) or the name? (Easylist Germany)

**Comment by Jacalz** [comment]
I have organized it by the first three letters but i wonder why is there a IRN adblock filter for iran that doesent show in settings?

**Comment by Jacalz** [comment]
https://github.com/Jacalz/ad-block/commit/2fab02087da2a2c1a6cb527b9b1fc96a2b3c8189

**Comment by Jacalz** [comment]
I dont understand what to do in the package.json file :disappointed:

**Comment by Jacalz** [comment]
@luixxiul

**Comment by luixxiul** [comment]
> why is there a IRN adblock filter for iran that doesent show in settings?

I'm not sure. CC @bbondy for a comment.

**Comment by Jacalz** [comment]
I would love if someone could merge my pull request in brave/ad-block and then close this issue :+1: 
Or just give me feedback on something to change if needed :smile: @luixxiul

**Comment by srirambv** [comment]
Moving to 0.19.x as the fix is only done on https://github.com/brave/ad-block/issues/66. There is no browser-laptop work done.

**Comment by srirambv** [comment]
This isnt implemented on browser-laptop yet. Should this be moved out of 0.19.x?

**Comment by srirambv** [comment]
This looks fixed on 0.19.123. Closing the issue
![image](https://user-images.githubusercontent.com/17010094/34437187-13b79b2a-ec94-11e7-9fd8-3ce27adf0b21.png)
