### ISSUE TITLE
Saved site exceptions needs padding from Manage adblock settings

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4503]
![screenshot 2016-10-04 11 06 48](https://cloud.githubusercontent.com/assets/831718/19079753/ac8dd844-8a22-11e6-9693-2e7e18e21eb6.png)

**Comment by diracdeltas** [comment]
also s/manager/manage ?

**Comment by bbondy** [comment]
already fixed on master

**Comment by bbondy** [comment]
![screenshot 2016-10-04 15 20 06](https://cloud.githubusercontent.com/assets/831718/19088890/2a33de42-8a46-11e6-8fde-abe916f15797.png)
![screenshot 2016-10-04 15 20 12](https://cloud.githubusercontent.com/assets/831718/19088891/2a41f324-8a46-11e6-832d-652e9165d076.png)
