### ISSUE TITLE
Everything is pink

### ISSUE THREAD

**Issue by erossonero** [brave/browser-laptop#451]
![brave](https://cloud.githubusercontent.com/assets/16802489/12686889/88fd2ab6-c69a-11e5-8a05-cdd1e97ae649.png)

Installed the browser on Win 10 Pro. All whites show as pink.

**Comment by bbondy** [comment]
Thanksf or the post Eros, can you right click on the icon on your desktop and go to properties. Is it 0.7.10?

**Comment by wblondel** [comment]
Hi @erossonero,

Do you have an Nvidia GPU?

**Comment by erossonero** [comment]
Hey Brian, yes im running 0.7.10 (app-0.7.10)

**Comment by erossonero** [comment]
@wblondel NVIDIA GeForce GT 530

**Comment by wblondel** [comment]
Some people [had the same bug on Chrome/Chromium](https://code.google.com/p/chromium/issues/detail?id=319115), they fixed it by upgrading their GPU drivers or by disabling Stereoscopic 3D in the Nvidia Control Panel.

**Comment by erossonero** [comment]
@wblondel updating the video card drivers worked. It shows white now.

Thanks!

**Comment by bbondy** [comment]
Sweet! Closing. Thanks guys.
