### ISSUE TITLE
Bookmarks and Folders under other bookmark not imported

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4510]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmarks and Folders under other bookmark not imported. 

**Expected behavior:**
Bookmarks and Folders under other bookmark not imported
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.3 Dev
- Steps to reproduce:
  1. Add Bookmarks and folders under other bookmarks in Chrome/FF
  2. Use Import bookmarks tool in Brave to import bookmarks 
  3. Only bookmarks under the main are imported. None of the bookmarks/folders created in step1 is imported to Brave
- Screenshot if needed:
- Any related issues:
  #3145

**Comment by gmgj** [comment]
Windows 10 x64
Brave Version 0.12.15
Steps to reproduce:
Add a large test file of Bookmarks to the Browser to import from
Setup Chrome 
Bookmarks Bar with a Level 1 folder, 
add a folder within Level 1 called Level 2, 
add a folder within Level 2 called Level 3   

Import from Chrome, chose the defaults

I do not see the Level 3 folder
