### ISSUE TITLE
Refresh buttons is not aligned with Home button

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4513]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Refresh buttons is not aligned with Home button

**Expected behavior:**
Should be properly aligned

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.4 Preview1

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19089378/a8a4f904-8a97-11e6-95f2-7a6e2ef43a47.png)

- Any related issues:

**Comment by lucidNTR** [comment]
i think this is superseded by #4400 and can be closed, can someone confirm?

**Comment by bbondy** [comment]
I think still an issue on Windows.
