### ISSUE TITLE
Unable to select text on a page opened in a new tab following a link

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4517]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Unable to select text on a page opened in a new tab following a link

**Expected behavior:**
User should be able to select text properly 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.x onwards

- Steps to reproduce:
    1. Open brianbondy.com
    2. Click on Twitter image to open the twitter page in a new tab
    3. Try selecting any text, not possible to select, text selection flickers when mouse is dragged across the text

- Screenshot if needed:
![textselection](https://cloud.githubusercontent.com/assets/17010094/19091389/08972154-8aa0-11e6-9fef-0e1cc2d6ffcb.gif)

- Any related issues:
#4502

**Comment by privatzee** [comment]
The same cause (link with target attr) as #4472
