### ISSUE TITLE
custom css resets for brave

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4519]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
a lot of style issues arise because standard css rules are not for electron applications and devs need to remember overriding bad UX standards

eg:
#4355

or 
https://github.com/brave/browser-laptop/pull/4509

recomendations:
box-sizing: border-box; (simpler box model)
-webkit-user-select: none; (non selectable text is standard outside of webviews)
*:focus {
    outline: none; (no focus outlines)
}

**Comment by luixxiul** [comment]
cc @bradleyrichter

**Comment by luixxiul** [comment]
Implement normalize.css should be the proper solution here.
