### ISSUE TITLE
Middle Click Crash

### ISSUE THREAD

**Issue by erossonero** [brave/browser-laptop#452]
When you middle click on a link, if you have only 1 tab open, it closes the browser, instead of opening a new tab.

Video in .zip file
[MiddleClickCrash.zip](https://github.com/brave/browser-laptop/files/110418/MiddleClickCrash.zip)

**Comment by ramons03** [comment]
Same Issue for me. Even if you have multiple tabs. It closes the entire browser.

**Comment by scunliffe** [comment]
Sounds like this might be similar to the issue I reported in Twitter/Gmail: https://github.com/brave/browser-laptop/issues/425

**Comment by DocWatson** [comment]
Yep, pretty sure this is a duplicate of #425. The latest update should fix this :)

**Comment by bridiver** [comment]
Is this a dup? I don't have a good way to test it right now.

**Comment by DocWatson** [comment]
Should be. #425 fixed this problem for me a week or so ago.

**Comment by erossonero** [comment]
Closing this, it seems to have been fixed!
