### ISSUE TITLE
s/next payment submission/next payment contribution/ in payment history modal

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#4521]
everywhere in the browser we say "contribution" EXCEPT for this one modal.

sorry for being inconsistent in saying (no more ledger stuff in 0.12.5dev earlier today), but could you please change /submission/ to /contribution/ here? thanks!

cc: @bradleyrichter 

![1](https://cloud.githubusercontent.com/assets/400552/19092080/fe9e5124-8a39-11e6-8b7e-14a33a3d8c44.png)

**Comment by jkup** [comment]
Seems good to me, @bradleyrichter are you ok with this change?

**Comment by bradleyrichter** [comment]
@jkup Yes, and perhaps the statements should be called "Brave_Payments_10-3-2016.csv"

**Comment by jkup** [comment]
Both changes reflected in https://github.com/brave/browser-laptop/pull/4528
