### ISSUE TITLE
non native menus behave strange

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#4525]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
menus that are not implemented with electron native menus do not allow selection in the same move as opening the menu, insted you need to click again to select a menu item.

**Expected behavior:**
you should experience as little as possible difference between native menus and reimplemented menus

- Platform (Win7, 8, 10? macOS? Linux distro?):
mac

- Brave Version:
latest master

- Steps to reproduce:
    1. navigate to a page and click two links to build a history
    2. long click back button and keep the mouse down while dragging to the history entry you want to go to.
    3. let the mouse button go.

nothing happens, but on os x the expected behaviour is to navigate to the entry that you released the button over.

**Comment by luixxiul** [comment]
Is it the same as #4277?

**Comment by lucidNTR** [comment]
yes, closing in favour.... 
#4277
