### ISSUE TITLE
Problem with scrolling on Google Sites

### ISSUE THREAD

**Issue by Consoledotlog** [brave/browser-laptop#4527]
The first couple of times I scroll on a Google associated site, such as Google Forums, and a few others, it does fine but then refuses to scroll and sometimes oddly jumps around. A perfect example is Google Keep, which seems to do it more than others, And no, my mouse isn't broken, any other site I've used Brave on hasn't had any issues.
I'm using Windows 10 64bit post Anniversary Update and if it matters any, a wireless mouse with a 2.4GHz connection with a USB chip
Brave version is: 0.12.3

Loving Brave BTW, I was just going to use it to support the devs but I'm starting to really like it! Keep adding the customization, options and such and it will be one of the best.

**Comment by admiral142** [comment]
I have been having scrolling issues since the latest update as well.

**Comment by Consoledotlog** [comment]
Just on Google sites or more? I haven't tested on Facebook, but I would assume it would since they have custom scrolling built in.

**Comment by bsclifton** [comment]
Closing this issue as a duplicate

@Consoledotlog and others - please see https://github.com/brave/browser-laptop/issues/4472 and subscribe to be notified of the latest status (and apologies for this bug :frowning_face: )
