### ISSUE TITLE
App translation

### ISSUE THREAD

**Issue by wblondel** [brave/browser-laptop#453]
Hi!

What about translating the app? :)

**Comment by cortig** [comment]
The OS X app havs a vast number of .lproj folders inside it's resources, but they're all empty. If I had to guess: it'd be coming at a later stage…

**Comment by bbondy** [comment]
You can partiticpate in translating the app here:
https://www.transifex.com/brave/brave-laptop/

**Comment by wblondel** [comment]
Thanks ! I requested to join the French language translation.

**Comment by cortig** [comment]
and so did-I :-)
