### ISSUE TITLE
Tab opened with middle click has non-functional mouse-wheel scrolling

### ISSUE THREAD

**Issue by sirhamster** [brave/browser-laptop#4530]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opened a new tab with middle (mouse-wheel) click.  Scrolling the new tab with the mouse-wheel would scroll to the bottom of the page and get stuck.  When stuck, the mouse-wheel could not scroll the page in any direction.  

Using the keyboard or manually click & dragging the scrollbar would still scroll the tab.  

The issue with mouse-wheel scrolling would disappear if the tab were closed and re-opened using Ctrl-Shift-T.

Isolated issue when I found that a tab opened using the right-click context menu did not have the scrolling problem.  Mouse-wheel scrolling problem only occurs on the particular tabs opened using a middle-click.

**Expected behavior:**
Mouse-wheel scrolling should function normally regardless of how a new tab was created.  

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version:
0.12.3

- Steps to reproduce:
    1. Open webpage with links.
    2. Open new tab from the links using a middle-click
    3. Select new tab and attempt to scroll on the new tab using the mouse-wheel

- Screenshot if needed:

- Any related issues:

**Comment by charbelrami** [comment]
Reproduced. (v0.12.4dev-Preview2, Win 10 64-bit)
When I open too many tabs, sometimes the scroll is locked at the top or the bottom of the page. It doesn't make difference if I open the tab using the mouse-wheel or not. But the page is only locked when trying to scroll with the mouse-wheel. Touch and cursor work as expected.
