### ISSUE TITLE
Lastpass: Error: Invalid Response

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4531]
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu

- Brave Version: Dev Channel Beta v0.12.4dev-Preview1

I tried to save a note on lastpass and show this message: Error: Invalid Response.

Obs. I tested on Opera Browser and works ok.

Brave screenshot:
![captura de tela de 2016-10-04 21-59-03](https://cloud.githubusercontent.com/assets/1178856/19097818/14d0f854-8a7e-11e6-839d-882a8acb305c.png)

**Comment by jonathansampson** [comment]
@bitcoinuser I was not able to repro this issue; do you still see it in more recent builds?

**Comment by bitcoinuser** [comment]
No. I don't repro the issue on last Brave version 0.12.5.

**Comment by nitinsavant** [comment]
I was seeing the same error message when trying to edit and save the URL of a site. Reinstalling the Safari extension fixed it for me.

**Comment by jonathansampson** [comment]
@nitinsavant Thanks! Sounds like it may have been an issue with an older version of the plugin itself.
