### ISSUE TITLE
Flash cover slide not shown on youku.com

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4532]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While attempting to watch videos on youku.com, the flash cover did not display. (http://v.youku.com/v_show/id_XMTc0NTM0MjI0NA==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0) 

**Expected behavior:**
The flash cover should display, warning the user to allow flash.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Discovered on OS X
- Brave Version:
  0.12.3
- Steps to reproduce:
  1. Visit http://v.youku.com/v_show/id_XMTc0NTM0MjI0NA==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0
  2. Look for the flash cover slide
- Screenshot if needed:
- Any related issues:

**Comment by diracdeltas** [comment]
it works now apparently
![screen shot 2017-03-14 at 10 05 07 pm](https://cloud.githubusercontent.com/assets/549654/23924293/060847d4-0902-11e7-8c00-d44057466001.png)
