### ISSUE TITLE
Search shortcut key for Amazon.com should be available for other Amazon sites

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4533]
**Describe the issue you encountered:** The search shortcut key for Amazon ``:a`` is reserved for Amazon.com

**Expected behavior:** It should be available for other Amazon sites over the world like amazon.ca

- Brave Version: 0.12.3

- Any related issues: #2694 #4221

**Comment by luixxiul** [comment]
I think this can be closed thanks to #2850

**Comment by bsclifton** [comment]
Agreed- should be covered by #2850 :smile:
