### ISSUE TITLE
Image is blank

### ISSUE THREAD

**Issue by nathan-osman** [brave/browser-laptop#4534]
I see a completely white page when I attempt to view this image:  https://i.stack.imgur.com/VCJt9.png

![screenshot from 2016-10-04 20-18-31](https://cloud.githubusercontent.com/assets/1253444/19099960/bcec214e-8a6f-11e6-9425-3bde661c039a.png)

I have Brave 0.12.3 running on Ubuntu 16.04 (amd64). I tested the page in both Chrome and Firefox and the image displays without any issue.

**Comment by charbelrami** [comment]
I couldn't reproduce it (v0.12.4dev-Preview2).

**Comment by nathan-osman** [comment]
Odd, I can no longer reproduce it either. It wasn't working at all yesterday and now it displays the page without any problem. Feel free to close and I can reopen if it happens again.

**Comment by charbelrami** [comment]
Thanks @nathan-osman
