### ISSUE TITLE
Empty folders in "Bookmarks" menu should show one child "(empty)" item

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4538]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmark folder created on toolbar shows as link from menu

**Expected behavior:**
Should show as an empty folder when no bookmarks inside the folder
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.4 Preview1
- Steps to reproduce:
  1. Create a folder in bookmark toolbar
  2. Go to menu, bookmark, created folder shows as a link rather than as a folder
- Screenshot if needed:
  ![4390](https://cloud.githubusercontent.com/assets/17010094/19101879/45a06d78-8ae9-11e6-8cb6-df3cc23330db.gif)
- Any related issues:
  #4390

**Comment by bsclifton** [comment]
Removed regression tag; I went back to version 0.12.1 and confirmed the behavior is the same (with the old system menu).
![bookmark-menu](https://cloud.githubusercontent.com/assets/4733304/19102588/41b715bc-8a86-11e6-93c2-c5c33575ebfd.gif)

**Comment by NejcZdovc** [comment]
This is already implemented.
