### ISSUE TITLE
titlebar disappears if the list in the autocomplete pulldown scrolled to the bottom

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4539]
**Describe the issue you encountered:** the titlebar disappears if the list in the autocomplete pulldown has scrolled to the bottom.

Also the blank bar appears on the bottom of the browser window.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19101897/ba1438e8-8b06-11e6-8dc0-8dd06d1076b3.png)

**Expected behavior:** the blank bar should not appear on the bottom of the browser window. The titlebar should not disappear (if it is not intended).

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.4 preview 1

- Any related issues:

**Comment by luixxiul** [comment]
The title bar flickers.

![flicker](https://cloud.githubusercontent.com/assets/3362943/19102190/2085ac0e-8b09-11e6-9050-0287e9ea8025.gif)

**Comment by bsclifton** [comment]
@luixxiul both scenarios are due to the window height; something about the overflow is causing an issue.  Looking into a fix...
