### ISSUE TITLE
[OS X] Version 0.7.10 won't launch

### ISSUE THREAD

**Issue by cortig** [brave/browser-laptop#454]
I used Brave under OS X 10.11.3. The app was working fine and mentioned an update was available.
I allowed the app to auto-update, but it never relaunched itself and I couldn't launch the app from the Finder either.
I redownloaded the app and reinstalled it and this version wouldn't launch either.
There seems to be an issue with the updated build.
The Console reports:
29/01/16 20:55:39.814 lsd[3804]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
29/01/16 20:55:39.817 lsd[3804]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
29/01/16 20:55:39.825 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000035.Electron[26761]) Could not find and/or execute program specified by service: 2: No such file or directory: /Users/me/Applications/Internet/HTTP/Brave.app/Contents/MacOS/Electron
29/01/16 20:55:39.825 Finder[13469]: spawn_via_launchd() failed, errno=111 label=[0x0-0x9f59f5].com.electron.brave path=/Users/me/Applications/Internet/HTTP/Brave.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
29/01/16 20:55:39.825 Finder[13469]: spawn_via_launchd() failed, errno=111 label=[0x0-0x9f59f5].com.electron.brave path=/Users/me/Applications/Internet/HTTP/Brave.app/Contents/MacOS/Electron flags=1
29/01/16 20:55:39.830 lsd[3804]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist

Corentin

**Comment by grshotton** [comment]
I found that I could not run Brave 0.7.10 if it were installed in the system Applications folder (OS X showed an error dialog saying it was damaged and could not run). But when installed in a subfolder of my (non-administrator) user's home folder, it runs and updates correctly.

**Comment by cortig** [comment]
Problem solved with 0.7.11 :-) The app is launching fine for me now.

**Comment by bbondy** [comment]
Great, I'll close this for now since problem doesn't seem to be with 0.7.11 and beyond.
