### ISSUE TITLE
downloading files from google drive

### ISSUE THREAD

**Issue by adicurta** [brave/browser-laptop#4543]
It doesn't allow me to download files from my google drive

**Comment by luixxiul** [comment]
will you please disable fingerprinting protection if you enabled it and try again?

**Comment by darkdh** [comment]
I have the same issue. 
try to select all files and download in [this link](https://drive.google.com/open?id=0B_CEID_yAVt-bGU0VWo4UEhKRDQ)

Must `allow all cookies` to download them

**Comment by pebble415** [comment]
This issue still persist. I tried downloading an image from my Google Drive and have been very unsuccessful at it. Download times take forever.

**Comment by romaswe** [comment]
i have the same problem but if i go to " docs.google.com/ " i can download but not when i go to" drive.google.com/ "

**Comment by darkdh** [comment]
There is one other thing. If you download [large file](https://drive.google.com/file/d/0B_CEID_yAVt-YmdlRk5JMEZkV2s/view?usp=sharing) from google drive, there will be no progress bar shown
<img width="224" alt="screen shot 2017-03-01 at 17 29 22" src="https://cloud.githubusercontent.com/assets/11330831/23488981/c452df78-fea4-11e6-9921-bcea9d05c8c3.png">
And it will go straight to the completed state when done
<img width="218" alt="screen shot 2017-03-01 at 17 31 47" src="https://cloud.githubusercontent.com/assets/11330831/23489015/fa46ab96-fea4-11e6-8ae6-4337e650f165.png">

**Comment by srirambv** [comment]
+1 from community on not showing the download time  estimation community.brave.com/t/download-time-estimation/1641

**Comment by bbondy** [comment]
adding STR for a friend:
STR:
- login into Gmail and open Google Drive
- right click on any backed up file within Google Drive and select "Download"
- you'll notice that rather than receiving the correct filename, you'll get random strings
    - example: 0B_lZo6xjBBJtfYkRaRUozS09XUkk (notice there's no file extension)
- select a location and select "Save" from the modal window

It will appear as "Downloading" indefinitely until you manually cancel the download. I think this should work without users having to disable the shields every time they want something downloaded.

**Comment by darkdh** [comment]
@bbondy, that requires 3rd party cookies blocking turned off.

**Comment by bsclifton** [comment]
[This came up recently and was closed](https://github.com/brave/browser-laptop/issues/9730)... should we capture the work-around (turning off 3rd party cookies) in a FAQ on community?

I don't think there's anything actionable we can do with this issue, so I'll close it

**Comment by luixxiul** [comment]
Displaying the number of the blocked resources including 3p cookies would help contributors to troubleshoot. See https://github.com/brave/browser-laptop/issues/2398
