### ISSUE TITLE
Norton blocking Brave setups

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4544]
Several users are reporting Norton is blocking Brave. Issue was reported in earlier releases also 

Support Tickets 
https://linkbubble.zendesk.com/agent/tickets/5917
https://linkbubble.zendesk.com/agent/tickets/5921

Closed Support Tickets
https://linkbubble.zendesk.com/agent/#/tickets/2049
https://linkbubble.zendesk.com/agent/#/tickets/1540
https://linkbubble.zendesk.com/agent/#/tickets/1746
https://linkbubble.zendesk.com/agent/#/tickets/2180

#924

**Comment by luixxiul** [comment]
Marking high-priority.

**Comment by bbondy** [comment]
Can you try to reach out to norton support?

**Comment by srirambv** [comment]
Update from Norton 
>it well compatible earlier and if there are issues in few cases then there might be any new patch from software end that might not get the good reputation from safe web yet. However, if we add the files of software in Norton by the option adding in firewall then it would get resolve.

Users might need to add an exception in Norton for the time being before it is done from their back end systems

**Comment by luixxiul** [comment]
@bbondy Do you have any idea about the reason of blocking (is there something suspicious in the installation program)?

**Comment by diracdeltas** [comment]
this has happened with various AV vendors. the most effective thing is to reach out to somewhere there to get them to unblock us, but i am looking into why we are blocked

**Comment by srirambv** [comment]
@diracdeltas does this info help. This one's from [support ](https://linkbubble.zendesk.com/agent/tickets/6046)again but AVG this time.
>After I updated Brave today, AVG has locked the Brave browser for the reason of detecting Win32/Heim.C

**Comment by diracdeltas** [comment]
Symantec reached out to help. In the future, if this happens, please tell users that they can upload the file to https://submit.symantec.com/false_positive/ to mark as a false positive. 

In the meantime i'll look into whitelisting us

**Comment by diracdeltas** [comment]
also it would be very helpful to know exactly which file they are trying to download, since this is the thing i need to submit for whitelisting. ex: https://github.com/brave/browser-laptop/releases/download/v0.12.3dev/BraveSetup-ia32.exe

**Comment by bsclifton** [comment]
@diracdeltas maybe we can update our wiki to have notes about how to white list our releases (once more info becomes available)?   You make a great point that we'd need to submit the executable, which should be part of the release process

**Comment by diracdeltas** [comment]
https://twitter.com/threatresearch says this is sorted out now, please re-open if not.

@bsclifton feel free to add this to the FAQ wiki page

**Comment by jstidd** [comment]
Symantec End Point Protection on Windows 10 is giving us this error as well. We didn't get the error on Mac.
