### ISSUE TITLE
Mouse scrolling wheel issues

### ISSUE THREAD

**Issue by edneri** [brave/browser-laptop#4547]
While navigating on several web pages, specially the one with pictures and windows/sections in the same page, like Verizon.com or pixel.google.com, when trying to use the mouse wheel, the page goes all the way to the bottom and not scrolling, navigated on the same pages using chrome with the same mouse and the issue is not happening.

**Comment by ahronzombi** [comment]
Me too, on Windows 10 and Mac OS

**Comment by llcljx** [comment]
Ditto, have the same problem on every web page I load.  Windows 10 as well.

**Comment by jtowry** [comment]
Same here. I haven't tried with a mouse but the track pad scroll is pretty screwy.

**Comment by privatzee** [comment]
The problem has been identified and given high priority: #4472

**Comment by texandirt88** [comment]
Having same issue on Windows 10 visiting MULTIPLE websites. Scrolls to bottom and causes browser to use more memory.

**Comment by bsclifton** [comment]
Like @privatzee pointed out, we're tracking this issue w/ https://github.com/brave/browser-laptop/issues/4472

I'm going to close this particular issue since it's technically a duplicate- please to subscribe to the other issue and stay tuned...
