### ISSUE TITLE
Brave window icons get stuck

### ISSUE THREAD

**Issue by ericlaw1979** [brave/browser-laptop#4549]
**Describe the issue you encountered:**
Hover window icons at top-right
Move mouse up

**Expected behavior:**
Icons unhighlight

Win7
- Brave Version:
  0.12.3
- Screenshot if needed:
  ![image](https://cloud.githubusercontent.com/assets/4192774/19121362/d2d7f196-8aeb-11e6-97b0-b6636a0ae57f.png)
- Any related issues:
  See https://bugs.chromium.org/p/chromium/issues/detail?id=637114 and https://codereview.chromium.org/2244263002/diff/60001/ui/views/win/hwnd_message_handler.cc

Fix is trivial, handle WM_NCMOUSELEAVE by calling DwmDefWindowProc(hwnd(), WM_NCMOUSELEAVE, 0, 0, NULL) != 0;

**Comment by bsclifton** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/7296
