### ISSUE TITLE
[OS X] Update command at the wrong location

### ISSUE THREAD

**Issue by cortig** [brave/browser-laptop#455]
Most apps under OS X have the Check for Update command right under the application name in them menu bar. Having it under File is highly unusual… It'd be nice to move it where people would expect to find it.

Corentin

**Comment by inian** [comment]
Looks like most browsers on Mac do not have a "Check for update" option in the menu bar at all..But I agree it being under File menu is unusual..probably would be a better fit under the Application menu or under the help menu..

**Comment by Oldpedro** [comment]
'Check for update' for chrome and firefox is on the  'about <application>' dialog (and in fact happens automatically when selected). Safari doesn't have one because it's updated via app store.  Makes sense to have it where the version number is displayed.

**Comment by cortig** [comment]
OmniWeb has the command, right in the OmniWeb menu and so do Camino and DEVONAgent Pro.
Firefox and Chrome are a bit different since they wanted to offer the exact same UI on all platforms.
As far as I'm concerned, I'd rather see Brave stick to the general OS X look and feel for the OS X version and the Check for Update command should then be right there in the Brave menu.
