### ISSUE TITLE
Brave positioning in dual monitor

### ISSUE THREAD

**Issue by atherts** [brave/browser-laptop#4552]
**Did you search for similar issues before submitting this one?**
Yes, but doesn't appear to be resolved and references window size and ignore positioning in second monitor issue.

**Describe the issue you encountered:**
In Windows 10, Brave always opens in the primary monitor. Even after being moved to the second monitor, minimized, maximized and closed.

**Expected behavior:**
Should open in second monitor after window is moved there.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.12.3

- Steps to reproduce:
    1. Open Brave
    2. Move from 1st monitor to 2nd monitor
    3. Minimize
    4. Restore, opens in 2nd monitor
    5. Close Brave
    6. Repopen Brave, opens in 1st monitor again

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Closing this in favor of #2438
