### ISSUE TITLE
Tabs do not become smaller when they do not fit in window

### ISSUE THREAD

**Issue by sotojuan** [brave/browser-laptop#456]
In Safari and Chrome, tabs automatically resize and become smaller the more there are. In Brave, you get another "set" of tabs you can go to.

I was curious about this design decision. Personally I prefer the way Safari and Chrome do it, and I think most people expect the same behavior. I don't really mind the way Brave does it, but was interested in why the team decided on this behavior.

**Comment by bbondy** [comment]
CC @bradleyrichter

**Comment by Sweetie-Belle** [comment]
I also prefer how Safari/Chrome do it. 5 tabs is a really strange number as well, I assumed it would be tied to window size or something.

**Comment by bradleyrichter** [comment]
@sotojuan Thanks for your feedback and explanation. We are releasing an update today that will allow you to customize how many tabs you would like in each set. If you prefer the Chrome/Safari tab organization, you can set the number to 100 and you won't see the tab sets UI until you reach 101 tabs.

Our reasoning behind the design of the tab set UI was to help users organize tabs in new ways that were not achievable with the current approach used in either Chrome (Safari) or Firefox. Our first round of UX research showed that people had a love/hate relationship with both Tab-Shrinking and Tab-scrolling. Some users used multiple windows to organize tabs into sub groups but the windows became cumbersome to manage.

Tab set's try to allow for an infinite number of tabs while remaining legible and recognizable yet still quick to navigate through, and provide a more organized approach to sub-grouping.

In the new future, we will support tab organization by dragging tabs to different sets, and manipulating entire sets of tabs.

@Sweetie-Belle With the new prefs setting, please try a larger number and let me know if you find a number that works for you. 

Thanks all for the feedback. Keep it coming!

-Brad

**Comment by bradleyrichter** [comment]
closing this since we now have user-definable tabs-per-set and much more positive feedback than negative on tab sets in general.
