### ISSUE TITLE
Touchpad sometimes overscrolls to top/bottom of page

### ISSUE THREAD

**Issue by JAffleck** [brave/browser-laptop#4568]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
On some pages when I try to use the touchpad on my computer to scroll (it's a synaptics one built into my toshiba laptop), it will jump all the way to the top or bottom of the page (like hitting home, or end keys),  It seems that it's oversensitive.

**Expected behavior:**
It just scrolls a little bit (like a line or two).
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win 7
- Brave Version:
  1.12.3
- Steps to reproduce:
  1. Navigate to https://en.wikipedia.org/wiki/Google 
  2. Scroll up and down using touchpad (scrolling is jumpy, some pages it's a lot worse than others).
     3.
- Screenshot if needed:
- Any related issues:

**Comment by charbelrami** [comment]
Related to #4472

**Comment by luixxiul** [comment]
I think this can be closed thanks to that #4472 was fixed

**Comment by luixxiul** [comment]
I'm going to close this for now. If this issue is still experienced, let's reopen this 😄
