### ISSUE TITLE
Input field Autocomplete not working

### ISSUE THREAD

**Issue by JAffleck** [brave/browser-laptop#4569]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When I go to a page with an input (like username/password), that I have previously visited in Brave, 
Like the Github sign-in page, and start entering my username, each character I type makes the stored username autocomplete entries flash for a tiny fraction of a second, so they are both unusable and annoying simultaneously.  

**Expected behavior:**
Have the autocomplete menu appear if I start typing, and disappear when escape is pressed.
If I click the mouse on the html input element, the autocomplete options appear properly.
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
  0.12.3
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by charbelrami** [comment]
Reproduced. 
![autocomplete](https://cloud.githubusercontent.com/assets/5647344/19138650/80c0736a-8b54-11e6-9e6d-7a0232356ab8.gif)

**Comment by diracdeltas** [comment]
i've also seen this. cc @darkdh

**Comment by luixxiul** [comment]
This has been fixed.
