### ISSUE TITLE
URL autocomplete makes it almost impossible to go to base domain of a site

### ISSUE THREAD

**Issue by JAffleck** [brave/browser-laptop#4570]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Say I go to youtube.com and view a video.
Then I close Brave, and sometime later open it, and in the URL bar I want to go to youtube's homepage.
When I hit alt + d to highlight the address bar, then start typing youtube, the full previous domain name appears and I have to delete the extra query parameters to just go to the homepage.
(I'm not sure if you have to go to a long url, i.e. base domain/folder/long-url-name.html?q=search%20parameters like from a google search result rather than visiting a websites base domain initially for the autocomplete to behave this way).
**Expected behavior:**
if I start typing a website, complete the domain, but don't complete more than that.
And if you want, in the URL autocomplete suggestions put the longer URLs with query parameters to the previously-visited full webpage URL.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7.
- Brave Version:
0.12.3
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
I recently noticed this as well. Solid find @charbelrami

**Comment by bradleyrichter** [comment]
@aekeus I think you are working on this already. Leave this open or do you have a new issue?

**Comment by aekeus** [comment]
This should be fixed up in the latest release.

**Comment by bradleyrichter** [comment]
So then I shouldn't be seeing this?

![image](https://cloud.githubusercontent.com/assets/13509546/19810915/3ee78f54-9cfd-11e6-80f8-afd4f5b75439.png)

**Comment by bbondy** [comment]
have you visited google.com before reproducing this? What if you go there and then close the tab and try to repro again?

**Comment by bbondy** [comment]
Only re-open when there is a backout. New issues please.
