### ISSUE TITLE
Mousewheel overscrolling in new tabs

### ISSUE THREAD

**Issue by Blondthecolorist** [brave/browser-laptop#4571]
When a new tab is opened via a link in an existing tab, scrolling the mousewheel causes the new page to scroll all the way to the bottom.

- Platform Win7
- Brave Version: 0.12.3

- Steps to reproduce:
    1. Click on a link that opens in a new tab.
    2. Go to new tab, scroll mousewheel.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Duplicate. Issue being tracked at #4472. Closing in favour of #4472
