### ISSUE TITLE
ESPN video player doesn't work when flash is installed and enabled

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4572]
reported at https://twitter.com/BryanMcMillin/status/783865324378521600

it seems that the site tries to load html5 video, but the player is broken for some reason, so perhaps we should just offer Flash

**Comment by srirambv** [comment]
@diracdeltas  Still can't load videos on ESPN.com

![image](https://cloud.githubusercontent.com/assets/17010094/19144303/55ab9804-8bc6-11e6-9321-60b6adc4958b.png)

**Comment by luixxiul** [comment]
ditto. Is there any URL available to test?

**Comment by alexwykoff** [comment]
In the happy path case this works. Happy path being that Flash was already enabled on the browser.  The user is prompted to allow Flash for the site and the video plays without issue.

There should have been a negative case check of if Flash was not enabled first. In that scenario, the user is not prompted to allow Flash, the user clicks on the interface for the video thinking it will work, and nothing happens.

**Comment by diracdeltas** [comment]
http://www.espn.com works for me. are you sure flash is enabled in about:preferences?

**Comment by diracdeltas** [comment]
to be clear, this issue is only for the happy-path case. negative checks need to be discussed before adding.

**Comment by diracdeltas** [comment]
alex says the happy-path case (which is what this issue was intended for) works for him so i'm closing for now
