### ISSUE TITLE
urlbar autocomplete suffix causing issues

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4573]
if you type in something that has an autocompleted suffix in the url bar and then keep typing, the characters don't appear. this was introduced in 57ecf927e7217e17997b60d80178a75bfbda1729

**Comment by diracdeltas** [comment]
this is also causing a sporadic problem where the urlbar gets into an unwritable state

**Comment by bbondy** [comment]
Oops just seen you reverted this, ignore my request to revert in other issues.  Thanks.
