### ISSUE TITLE
Denying fullscreen mode freezes scroll

### ISSUE THREAD

**Issue by charbelrami** [brave/browser-laptop#4574]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Tested on YouTube and Vimeo

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win 10 64-bit
- Brave Version:
  v0.12.4dev-Preview2
- Steps to reproduce:
  1. Click the fullscreen icon
  2. Click Deny button
  3. Try to scroll
- Screenshot if needed:
  ![fullscreen-freeze](https://cloud.githubusercontent.com/assets/5647344/19141340/05670064-8b6b-11e6-8b63-fb35bba0a914.gif)
- Any related issues:

**Comment by adrianfilip** [comment]
I have also noticed that scrolling doesn't work on random pages. Sometimes on youtube, sometimes on google groups pages sometimes on random websites.

**Comment by alexvhr** [comment]
Scrolling is ruined on every other page I visit. Sometimes it can be helped by turning shields down, sometimes it can't. Happened after updating to 0.12.3. Scrolling by scroll wheel / up-down keys/ handle dragging is impossible, the only way to scroll is by clicking on the scrollbar. Had to abandon Brave for now.

**Comment by PatrickWynne** [comment]
Also experiencing scrolling issues: 
https://www.washingtonpost.com
http://philadelphia.cbslocal.com
some sites, immediately scroll to the bottom

**Comment by srirambv** [comment]
Same as #3837

**Comment by srinivasreddy** [comment]
I found this happening on https://www.youtube.com/watch?v=fT29FdmHLdY
