### ISSUE TITLE
Multiple closed windows should be able to be reopened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4575]
**Describe the issue you encountered:** It is unable to reopen more than one closed windows when three windows are opened simultaneously 

**Expected behavior:** Multiple closed windows should be able to be reopened

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 x64

- Brave Version: 0.12.4 Preview 2

- Steps to reproduce:
  1. Open 3 Brave windows 
  1. Navigate to 3 different sites on all three windows
  2. Close All browser windows by clicking on the close button(x) [Do not quit Brave]
  3. Launch browser again
  3. Try reopening last closed window

- Expected result: every closed window should be restored

- Actual result: only one window is relaunched

- Any related issues:

**Comment by bbondy** [comment]
I don't think we ever added support for more than 1 window so removing milestone.

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/9422#issue-235599954

**Comment by bsclifton** [comment]
Closing as `wontfix`- this is supported in [brave-core](https://github.com/brave/brave-browser) 😄 

Windows (multiple restores work great):
![screen shot 2018-08-06 at 11 50 27 pm](https://user-images.githubusercontent.com/4733304/43759319-bd3925a0-99d3-11e8-9ad6-6bf37e80c5f8.png)

macOS (shows each window grouped by number of tabs - with a `Restore all tabs` option):
![screen shot 2018-08-06 at 11 51 03 pm](https://user-images.githubusercontent.com/4733304/43759360-d58e8208-99d3-11e8-9298-b333deec8e3f.png)
