### ISSUE TITLE
Opening new tab retains the previous active tab's URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4580]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening new tab retains the previous active tab's URL

**Expected behavior:**
Should not retain previous active tab's URL

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.4 Preview 3

- Steps to reproduce:
    1. Open a site / any about pages
    2. Press Ctrl+T to open a new tab
    3. New tab will retain the previous active tab's URL and clicking anywhere removes the URL and set focus to the URL bar

 Verified not happening on 0.12.4 Preview 2 

- Screenshot if needed:
![tabs](https://cloud.githubusercontent.com/assets/17010094/19143323/c99062b4-8bc0-11e6-8d38-d8e5f785f564.gif)

- Any related issues:

**Comment by Aeyoun** [comment]
This is a security issue and should be labeled as such.

**Comment by bbondy** [comment]
@diracdeltas maybe this one as well, but pls advise.

**Comment by bbondy** [comment]
I think it might be the unreleased urlbar optimization stuff.

**Comment by diracdeltas** [comment]
90% sure this is also due to urlbar optimization and fixed on master now.

for anyone following along, this sec issue is not high severity because it only exists in an unreleased preview build.

**Comment by diracdeltas** [comment]
closed by 9e98154
