### ISSUE TITLE
Bookmark suggestions makes it impossible to type the URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4581]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmark suggestions makes it impossible to type the URL

**Expected behavior:**
User should be able to type the URL/delete the suggestion autoloaded and complete the URL 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.4 Preview 3

- Steps to reproduce:
    1. Import bookmarks/ add sites as bookmark and ensure Bookmark suggestions is enabled in search
    2. Open a new tab and start typing
    3. Bookmark suggestion auto fills the URL bar and if user continues typing starts adding it at the end of the URL
    4. Once bookmark suggestion is loaded in URL bar it is difficult to remove the URL when full URL is selected and press delete button have to use backspace to remove the URL.

 Verified not happening on 0.12.4 Preview 2

- Screenshot if needed:
![suggestions](https://cloud.githubusercontent.com/assets/17010094/19145218/9d27491c-8bcb-11e6-9d0f-9354ee1ec31c.gif)

- Any related issues:

**Comment by bbondy** [comment]
@diracdeltas ditto also this I think is related to the optimization

**Comment by diracdeltas** [comment]
@bbondy yes and fixed in revert

**Comment by diracdeltas** [comment]
closed by 9e98154
