### ISSUE TITLE
New tab doesn't record the first typed character in a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4583]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
New tab doesn't record the first typed character in a new tab even though the focus is set to the URL bar

**Expected behavior:**
Should capture the first typed letter when a new tab is opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.4 Preview 3

- Steps to reproduce:
    1. Open a new tab
    2. New tab URL has focus but the first typed char is not recognized 
    3. Type the second time the char input is recognized

Verified not happening on 0.12.4 Preview 2

- Screenshot if needed:
![newtab](https://cloud.githubusercontent.com/assets/17010094/19146299/7edc76e4-8bd0-11e6-8175-d2cb2da6981b.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Can this be only reproduced with the on-screen keyboard?

**Comment by srirambv** [comment]
No its the default behavior. Just used the on-screen keyboard to show the key strokes.

**Comment by bbondy** [comment]
@diracdeltas I think maybe this one is related to the urlbar optimization as well

**Comment by diracdeltas** [comment]
@bbondy yes and fixed in revert

**Comment by diracdeltas** [comment]
closed by 9e98154
