### ISSUE TITLE
The urlbar is really touchy and forcing errors

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4584]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When attempting to type in an autocomplete-available url, Brave is jumping ahead and filling in the value instead of waiting for me to hit enter. This is forcing errors where I have to correct the autocomplete.

**Expected behavior:**
Autocomplete should not inject characters unless I explicitly select the suggestion.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.4 Preview3

- Steps to reproduce:
    1. Try to type in 'youtube.com' by hand in the urlbar

- Screenshot if needed:
![touchy_urlbar](https://cloud.githubusercontent.com/assets/1434040/19148182/10e38e52-8bee-11e6-81dd-a00ab69ccbd3.gif)

- Any related issues:
I believe this may be a regression introduced by https://github.com/brave/browser-laptop/issues/4573

https://github.com/brave/browser-laptop/issues/4581
https://github.com/brave/browser-laptop/pull/4563
https://github.com/brave/browser-laptop/issues/3876

**Comment by bbondy** [comment]
@diracdeltas I'm thinking this is probably related to the urlbar optimizations, I think it'd be best to move this out of 0.12.4 and back out the perf fix for now. Would you mind doing that if you confirm it's from your changset that I merged? Thanks!

**Comment by diracdeltas** [comment]
@bbondy almost certainly and it was reverted last night

**Comment by diracdeltas** [comment]
closed by 9e98154
