### ISSUE TITLE
When importing on a clean install, it appears as though nothing has happened

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4586]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When importing data to a clean install of Brave, the bookmarks toolbar does not open (https://github.com/brave/browser-laptop/issues/4507) and the bookmarks menu is not updated (https://github.com/brave/browser-laptop/issues/3968, https://github.com/brave/browser-laptop/pull/4390, https://github.com/brave/browser-laptop/issues/4227).

**Expected behavior:**
When importing data, the newly imported data should be immediately available to the user upon successful completion.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.4 Preview 3

- Steps to reproduce:
    1. With a clean install, (move away any prior /brave folders) import from another browser with bookmarks and folders.
    2. Check that the bookmarks toolbar opens and that the bookmarks menu is updated.

- Screenshot if needed:
![import_base_case](https://cloud.githubusercontent.com/assets/1434040/19149247/7bd49652-8bf3-11e6-96de-648889c4da56.gif)

- Any related issues:

**Comment by alexwykoff** [comment]
cc @bsclifton

**Comment by darkdh** [comment]
no bookmarks toolbar problem fixed in #4507
