### ISSUE TITLE
Bravery button should be inside the tabs area

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4591]
Bravery button should be moved into the tabs area.  Here are the current mockups for Windows

Win 10
![image](https://cloud.githubusercontent.com/assets/13509546/19172710/1952544e-8bd8-11e6-86db-03cfe15f718e.png)

Win 7
![image](https://cloud.githubusercontent.com/assets/13509546/19172858/f9490f48-8bd8-11e6-8727-d4821fda395a.png)

Mac
![image](https://cloud.githubusercontent.com/assets/13509546/19172736/45536f88-8bd8-11e6-85c7-9764f31093da.png)

**Comment by neeklamy** [comment]
What’s the distinction between a button living in the tabs area versus the title bar? And why does the Brave button move down, but the password manager (if it’s configured) stays in the title bar?

I’d suggest the only things that should be in the tabs area, are tab related.

It looks like anyone using Windows (and Windows 10 especially so on smaller screens) will have less space to grab and move the window around too.

This change seems arbitrary, that lovely lion logo looks great up in the top right corner, with it there, there really can’t be any question over which web browser we’re looking at.

**Comment by privatzee** [comment]
Well, I think that's a mistake. It'll tend to get lost down on the tab bar -- most especially as far as _brand new users_ go. Moving it would also make the browser less distinctive at first look. You've only got one chance to make a first impression. 

Also, the less confusion the better. So again for _brand new users_, it's very handy to say in any doc: "click the lion in the upper right" and it does stand out more where it is.

**Comment by bsclifton** [comment]
Here's a quick mock-up I did of something @bradleyrichter and I had talked about on Friday. Basically, it would be moving the lion head / extension buttons over to opposite side of the caption buttons. This is fairly close to Mac

cc: @neeklamy @privatzee

**Proposed Windows look**
![screen shot 2016-10-10 at 1 59 03 am](https://cloud.githubusercontent.com/assets/4733304/19231171/6302a050-8e8d-11e6-9917-aa2daba60f36.png)

**Current look on Mac**
![screen shot 2016-10-10 at 2 02 20 am](https://cloud.githubusercontent.com/assets/4733304/19231231/c240db9a-8e8d-11e6-8f3e-15460cd2b2ff.png)

**Comment by srirambv** [comment]
@bsclifton Personally not a big fan of having things before the back/forward buttons. But the new renders look much better than having the Lion icon in place of the hamburger menu. One alternate could be moving it next to the current bookmarks icon position(once this is moved inside the URL bar). This way the Lion doesn't move up and down when the menu is selected(current behavior) and can still be selected when mouse hovers over URL bar(irrespective of being in title mode or URL mode).

**Comment by bsclifton** [comment]
@bradleyrichter not sure if you had an update or needed more time.  I definitely won't have time before Monday to look at this though :frowning_face: Should we move this back a sprint or two?

**Comment by neeklamy** [comment]
@bsclifton, that definitely looks nicer, it’s a shame that positioning the Brave lion consistently across platforms is so difficult (impossible?). Being able to say to someone new to the browser “top right” or “top left” would be a big win.

The only cross platform example I can think of by way of comparison would be iTunes. But, as a representative set of “1” and someone who really, _really_ appreciates applications being consistent to the platform standards (OS X/macOS makes you that way), I wonder would you consider diddling with the “traffic lights” on the Mac version? Something like Apple briefly played with in iTunes:

![iTunes 9 v 10 comparison](https://cloud.githubusercontent.com/assets/155358/19381629/6dd38cfa-91f4-11e6-8faa-0d3c506f4d75.jpg)

(From: [What happened to the iTunes 10 window controls?](https://www.cooper.com/journal/2010/9/itunes_10))

Doing that would enable you to place the Brave lion up in the top left corner on all platforms.

**Comment by bradleyrichter** [comment]
closing this as we decided to leave the Brave button on the upper right. Thanks all for the input.
