### ISSUE TITLE
Wrong tab URL showing in URL bar

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#4592]
**Did you search for similar issues before submitting this one?**
Yes. There are similar issues like #4219 but I don't see this exact one.

**Describe the issue you encountered:**

Sometimes I end up with the wrong tab's URL in my URL bar

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version:

0.12.3

- Steps to reproduce:
I'm not able to 100% reproduce but at least once a day I end up with the wrong tabs URL.

- Screenshot if needed:
![screen shot 2016-10-06 at 11 18 22 am](https://cloud.githubusercontent.com/assets/490294/19165074/44b3c698-8bb7-11e6-9c64-618eb0f9d979.png)

**Comment by diracdeltas** [comment]
haven't seen this in 0.12.3; no console errors?

**Comment by jkup** [comment]
No and I haven't seen this again since. I'm going to close for now but reopen if I can figure out how to reproduce.

**Comment by bbondy** [comment]
Pls clear milestone when closing w/o a changeset. Thanks! (I got it already for this one)
