### ISSUE TITLE
Documentation - what are HTTPS upgrades?

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4593]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some users are not aware of our HTTPS Everywhere integration and what it brings to the table.

**Expected behavior:**
It would be great to have documentation (brave.com or built in) that helps describe:
- what HTTPS upgrades are
- why that is important to them
- Platform (Win7, 8, 10? macOS? Linux distro?):
  all
- Brave Version:
  all
- Steps to reproduce:
  1. Browse to a site which has http content
  2. Click on bravery button (lion head)
  3. Notice there are HTTPS upgrades with no description of what that means or why it's important
- Screenshot if needed:
- Any related issues:

**Comment by anasant** [comment]
+1 on this! Not really understanding HTTPS upgrades

**Comment by apscomp** [comment]
To the best of my knowledge: https upgrades means, sites and hyperlinks, that are linked to http:// and if a equivalent https:// site is available.... brave browser, automatically changes those links to https:// equivalents, to prevent tracking etc.,

**Comment by bsclifton** [comment]
Closing as this is more of an item for community (and not an issue with browser-laptop) 😄
