### ISSUE TITLE
Documentation - what are 3rd party cookies (and why should you care?)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4594]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some users are not aware of what cookies and especially 3rd party cookies are and they especially don't understand the impact to them. 

**Expected behavior:**
There should be a way for the user to get more information... including seeing practical examples of how cookies and 3rd party cookies are used and how it impacts them.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  all
- Brave Version:
  all
- Steps to reproduce:
  1. Load Brave and click Bravery icon (lion head)
  2. Notice the "Cookie Control" being set to "Block 3rd Party Cookies" by default
  3. Notice how there are no links to documentation / education / videos with more info
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
I'd love to see this document is available on our community FAQs category. Sometimes there is a user who is told to enable 3rd party cookie and regard it as that we were trying to hide the issue of our side (while it is not). Providing the instruction with this background explanation will help to relieve some users concerned the privacy while not knowing what the 3rd party cookie actually is.

**Comment by bsclifton** [comment]
Closing as this is more of an item for community (and not an issue with browser-laptop) 😄
