### ISSUE TITLE
Importing (Firefox) Bookmarks...folders don't open.

### ISSUE THREAD

**Issue by SixStringLee** [brave/browser-laptop#4595]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Opening imported (Firefox) bookmark folders in bookmarks menu fails. The Bookmarks don't appear in the folders, but are in the Bookmarks Manager. 
Plus, the folders are at the bottom of the Bookmarks menu without any visible way to move them to the top....above the unsorted links.
**Expected behavior:**
Expected to hover or even click on bookmark menu folders and see content. Plus be able to move the bookmark folders to the top of the bookmarks drop down menu.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7
- Brave Version:
  0.12.3
- Steps to reproduce:
  1. Click Bookmarks menu
  2. Scroll to an imported folder
  3. Hover over folder
- Screenshot if needed:
  In the screenshot you see me hovering over the "Weather" folder (no content shown). Plus, you see the folders are below the unsorted bookmarks.
  ![bravebookmarks](https://cloud.githubusercontent.com/assets/22669725/19172991/d0cafa62-8bf2-11e6-8510-4f856cfe8d82.jpg)
- Any related issues:
  No

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/bookmarks-imported-from-firefox-does-not-display-the-sub-folder/10246

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
