### ISSUE TITLE
Office 2007 will no longer allow Brave to be default browser

### ISSUE THREAD

**Issue by ktd99** [brave/browser-laptop#4596]
**Did you search for similar issues before submitting this one?**  Yes

**Describe the issue you encountered:**  My default browser has been Brave.  A few days ago I started having a problem, in that I received an error msg when clicking on a link in an Outlook 2007 message.  A search of online suggestions resulted in my making IE my new default.  And that "solved" the problem...but I still would like Brave to be the default.  And when I went back to the Internet Settings tabs, and listed all of my programs, Brave was not even on the list!  So...how do I recover a successful linkage between Outlook 2007 and Brave?

**Expected behavior:** 1.  I need to be able to set Brave as default browser.  2.  I need hyperlinks in Outlook 2007 to work.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Win7

- Brave Version: 0.12.3

- Steps to reproduce:
    1.  N/A
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by ktd99** [comment]
Firefox has an internal feature that allows us to set it as the default browser.  Brave does not seem to have this same feature.  True, or have I missed something?

**Comment by bufordliberty** [comment]
So, how do you set Brave as the default browser?

**Comment by bsclifton** [comment]
@ktd99 @bufordliberty you can try the steps in our Wiki to set Brave as the default browser:
https://github.com/brave/browser-laptop/wiki/End-User-FAQ#how-do-i-make-brave-my-default-browser

I'll mark this issue as closed for now, but please re-open if the wiki steps are not helpful or if you have any more questions :smile:

**Comment by ktd99** [comment]
I mentioned that I had already tried that approach...which is the method I'd used when I first installed Brave.

But now, Brave does not even show up on the list of installed programs.  So, yes, PLEASE reopen the issue.

**Comment by ktd99** [comment]
Any other ideas??  I'm still having to copy/paste any URLs...a real pain!

**Comment by bufordliberty** [comment]
Same here. Pasting.

**Comment by bsclifton** [comment]
issue also being tracked here:
https://github.com/brave/browser-laptop/issues/4832
