### ISSUE TITLE
Feature Request : Postman Extension

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4599]
**Did you search for similar issues before submitting this one?**
Yes

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

**What do you like about the extension?**
Postman is a very useful tool for developers and QA to test APIs and is a critical tool in my workflow.

**Comment by srirambv** [comment]
Closing as its added in the extension list in [community](https://community.brave.com/t/the-list-of-the-requested-extensions/10278)

**Comment by alexwykoff** [comment]
That was a spot early. Postman is super popular with devs and qa.

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/11952 (the issue was created via the project board).
