### ISSUE TITLE
The unified extension support tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4600]
This is a unified issue for the community to suggest and vote on extensions they would like to see implemented. 

To suggest an extension, please first create a tracking issue for that extension if none exists.(see https://github.com/brave/browser-laptop/issues/4599 as an example of what to do) That way discussions as to the merits of that extension can be discussed separately from this tracking issue and not clutter up the comments.

Please suggest only 1 extension per comment with a link to the tracking issue for that extension.

If you like a particular extension and would like to see it implemented, please use the 'Add your reaction' feature on the comment to vote.

**Comment by alexwykoff** [comment]
Please add support for Postman : https://github.com/brave/browser-laptop/issues/4599

**Comment by bsclifton** [comment]
User @rifazn would like support for Vimium

**Comment by BenLeggiero** [comment]
Please add support for crxMouse Extension: #4677

**Comment by tcr** [comment]
Pocket: https://github.com/brave/browser-laptop/issues/516

**Comment by bsclifton** [comment]
The Great Suspender: https://github.com/brave/browser-laptop/issues/4729

**Comment by luixxiul** [comment]
I think integration with Pocket is under development by @jonathansampson

**Comment by luixxiul** [comment]
#4781
> Request: ScriptSafe Extension 
> 
> https://github.com/andryou/scriptsafe

**Comment by ConorIA** [comment]
Mailvelope: #4845

**Comment by echosa** [comment]
Better Twitch.tv (BetterTTV), please: https://github.com/brave/browser-laptop/issues/4956

**Comment by slydetech** [comment]
Enpass #5097 (thanks !)

**Comment by bsclifton** [comment]
Speed Dial https://github.com/brave/browser-laptop/issues/5171

**Comment by MikeJayHarrison** [comment]
Linkclump #5277

**Comment by srirambv** [comment]
RefControl #5372

**Comment by echosa** [comment]
Xmarks https://github.com/brave/browser-laptop/issues/2414

**Comment by Liunkae** [comment]
React Dev Tools #5429

See also: #2716

**Comment by Liunkae** [comment]
For additional extension requests, see the [Extensions Project here](https://github.com/brave/browser-laptop/projects/1).

**Comment by srirambv** [comment]
Instapaper [5464](https://github.com/brave/browser-laptop/issues/5464)

**Comment by Liunkae** [comment]
Proxyswitchy Omega #5472

**Comment by alexwykoff** [comment]
Closing in favor of Extensions Project : https://github.com/brave/browser-laptop/projects/1
