### ISSUE TITLE
session tab is broken

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#4601]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
The content of session tab seems like regular session (no icon indication and it keeps my google account credential)
**Expected behavior:**
Session tab should work as expected
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.3
- Steps to reproduce:
  1. Login your google account in regular session
  2. Menu->New Session Tab
  3. Search something on new session tab
  4. The session tab act just like regular one

**Comment by darkdh** [comment]
If I move user dir away and back, the session tab behaves normal

**Comment by Liunkae** [comment]
Does this problem still exist?

**Comment by darkdh** [comment]
Yes, you can compare it to the container tab of firefox

**Comment by bsclifton** [comment]
@darkdh is this issue fixed in 0.13.0?

**Comment by darkdh** [comment]
It's been fixed in 0.13.0. Thanks for the reminding.
