### ISSUE TITLE
Yahoo mail stuck on just one of my user addresses, log-out then log-in failing to open other identity

### ISSUE THREAD

**Issue by donnyork** [brave/browser-laptop#4604]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
I cannot (although I indeed can with other browsers) log off one of my Yahoo Mail addresses and onto a different one. The different name is ignored and it re-opens the previous address inbox!
**Expected behavior:**
[well known]
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10
- Brave Version:
  0.12.3     just installed two days ago
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  Short-length screencast here: http://screencast-o-matic.com/watch/cD6ijZjwT8
- Any related issues:
  Short-length screencast here: http://screencast-o-matic.com/watch/cD6ijZjwT8

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-investigation-yahoo-mail-compatibility-issues/10386/2?u=suguru

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
