### ISSUE TITLE
Payment History modal receipt filenames should handle multiple same-day transaction edge case

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#4605]
**Did you search for similar issues before submitting this one?**

Yes. This is in response to comments from @alexwykoff and @mrose17 in #4332:
https://github.com/brave/browser-laptop/issues/4332#issuecomment-251939887

**Describe the issue you encountered:**
Quoting @alexwykoff:
"what about the edge case of multiple transactions on the same day? should there be a differentiator for the file name? otherwise the user is likely to overwrite their own file on export."

Currently, if a developer manually triggers mutliple reconciliations in a single day, the receipt CSVs will have the same suggested/displayed filename, e.g. `brave_ledger10-7-2016.csv`, as the filename is based on the date at day resolution.

**Expected behavior:**

When a given day has multiple transactions/reconciliations, the receipt filenames after the first should take on a suffix to distinguish them, e.g. `brave_ledger10-7-2016.csv` for the 1st transaction and `brave_ledger10-7-2016_2.csv` for the 2nd.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All.
- Brave Version:
0.12.3dev and onwards

- Steps to reproduce:
    1. Enable Brave Payments, create wallet, fund it
    2. Trigger reconciliation multiple times by editing /<UserDataPath>/ledger-state.json reconcileStamp to be in past (e.g. set to 100)
    3. Open Brave Payments -> Payment History
    4. Observe "Receipt Link" column with duplicate filenames for transactions on same day

- Screenshot if needed:
@mrose17 shared this one in #4332:
![mrose_4332_screenshot_cropped](https://cloud.githubusercontent.com/assets/6969859/19188310/d9ad0028-8c45-11e6-9523-cf274997bab4.png)

- Any related issues:
https://github.com/brave/browser-laptop/issues/4332

**Comment by mrose17** [comment]
@willy-b - can you submit a PR for this? thanks!

**Comment by willy-b** [comment]
you got it: #4605 fixes this.

**Comment by mrose17** [comment]
i think that's https://github.com/brave/browser-laptop/pull/4632

thanks!

@diracdeltas - could you review? thanks!
