### ISSUE TITLE
Can't enable Flash Player

### ISSUE THREAD

**Issue by stc509** [brave/browser-laptop#4608]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by stc509** [comment]
Using Win 10, just installed Brave browser

**Comment by diracdeltas** [comment]
did you try https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues

**Comment by stc509** [comment]
Thanks.  I re-installed & it worked.

 

Steve & Tammy Craft
