### ISSUE TITLE
Bookmark toolbar will not show from menu item after hiding

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#4613]
**Did you search for similar issues before submitting this one?**

Yes, this is an existing issue with previous version of the browser

**Describe the issue you encountered:**

After hiding the Bookmarks toolbar from the menu, it will no longer open via the menu item.

**Expected behavior:**

The Bookmarks toolbar should be open / closed via the Bookmarks > Bookmarks toolbar menu item

- Platform (Win7, 8, 10? macOS Linux distro?):

macOS

- Brave Version: 0.12.4 RC1

- Steps to reproduce:
    1. Open Bookmarks toolbar via right clicking on the tabs area and selecting Bookmarks toolbar
    2. Close toolbar
    3. Attempt to re-open the Bookmarks toolbar

- Screenshot if needed:

- Any related issues:

https://github.com/brave/browser-laptop/issues/4609#issuecomment-252331898

**Comment by bsclifton** [comment]
closing this as a dupe (original issue being https://github.com/brave/browser-laptop/issues/3356)

I'll assign the original issue over to 0.12.5
