### ISSUE TITLE
Bookmark text is cut off in bookmarks toolbar

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4614]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Recent (0.12.4) changes have caused the line height or another attribute with the text in the bookmarks toolbar to be off.  The bottom portion of the letter g and other letters get cut off (see screenshot)

**Expected behavior:**
This shouldn't happen

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1. Use Brave 0.12.4
    2. Visit google.com
    3. Bookmark the site and ensure it shows in bookmarks toolbar
    4. It should look like the screenshot (bottom part of the g is cut off)

- Screenshot if needed:
![screen shot 2016-10-07 at 12 52 40 pm](https://cloud.githubusercontent.com/assets/4733304/19205132/5dd62b50-8c95-11e6-93d0-c8d900b69ad9.png)

- Any related issues:
May have been caused by https://github.com/brave/browser-laptop/pull/4400 (font size changes I believe?). Needs investigation

**Comment by Liunkae** [comment]
Will be fixed with #4636
