### ISSUE TITLE
Dragging link to existing tab opens new tab

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#462]
Brave windows v 0.7.11

With both chrome and firefox, if you frag a link to an existing tab, you load that link in the tab itself. With this version of brave you get a new tab. 

(Note that this is better than the previous behavior which was to obliterate all the tabs and toolbars)

Steps to reproduce
1) open two tabs
2) load (say) https://github.com/brave/browser-laptop/  into one tab
3) drag a link (e.g. the issues link) to the other tab

Expected behavior: The second tab is loaded with https://github.com/brave/browser-laptop/issues
Actual behavior: A thrid tab is opened that contains https://github.com/brave/browser-laptop/issues

**Comment by luixxiul** [comment]
I want this implemented too

**Comment by luixxiul** [comment]
the actual behavior is no longer reproduced. See: https://github.com/brave/browser-laptop/issues/10600
