### ISSUE TITLE
titlebar became narrow a little on Windows

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4622]
**Describe the issue you encountered:**

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19209836/017c5b0e-8d4e-11e6-9de3-72f65a2c6129.png)

**Expected behavior:** I am not sure if it was intentional. @bsclifton will tell :-D

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.4

- Any related issues:

**Comment by bsclifton** [comment]
This was intentionally removed w/ https://github.com/brave/browser-laptop/commit/2f25023d533d564a41ec6a1f60bb911d51d91214 

It previously had:
- 5px padding to the left of nav buttons / File menu
- 5px on top, above menu

The padding on top was causing issues after accepting https://github.com/brave/browser-laptop/pull/4400 and also contributed to https://github.com/brave/browser-laptop/issues/4539 (making it worse).

Here's a screenshot of Firefox that I used as inspiration when testing out removing the removal of padding:
![screen shot 2016-10-08 at 12 28 36 am](https://cloud.githubusercontent.com/assets/4733304/19211317/4c499d46-8cee-11e6-8983-d40423d255c4.png)

for a side-by-side, here's a shot of Brave:
![image](https://cloud.githubusercontent.com/assets/4733304/19211333/d0355d3e-8cee-11e6-875a-87aa1dc7853c.png)

Does the change look bad? @luixxiul, @bradleyrichter, let me know what you think :smile:

**Comment by luixxiul** [comment]
I'm for it :+1:

**Comment by bigkitttty** [comment]
I'm not for it.

**Comment by bsclifton** [comment]
@bigkitttty what don't you like about it? Do you prefer having the standard Windows titlebar?

**Comment by bsclifton** [comment]
Closing this issue for now... if you'd like to see a different look, please re-open, leave a comment with your preferred look, and cc myself or Brad on it :smile: Thanks!
