### ISSUE TITLE
padding-left should be added to the back button

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4624]
**Describe the issue you encountered:** padding-left should be added to the back button.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19209945/4b4b1692-8d50-11e6-95a2-18a8d3c9d422.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.4

- Any related issues:

wdyt, @bradleyrichter ?

**Comment by bsclifton** [comment]
Related to https://github.com/brave/browser-laptop/issues/4622

The padding was to the left of both the menu and the nav buttons. We can restore the padding for just the nav buttons (would be a super easy change; it was 5px before).  Let me know :smile:

**Comment by bsclifton** [comment]
I just noticed right now (great job capturing it, @luixxiul)- the padding missing when back button is hovered definitely looks wrong

Here's a before/after of adding 5px back (this time only in front of the back/forward buttons)

**before** :cry: 
![image](https://cloud.githubusercontent.com/assets/4733304/19211631/f80ca8d8-8cf5-11e6-93ed-1a0705e5faf4.png)

**after** :smile: 
![image](https://cloud.githubusercontent.com/assets/4733304/19211651/5bf4224a-8cf6-11e6-87b9-9d1f767bf2ee.png)
