### ISSUE TITLE
I cannot log in to Twitter Mobile thru Brave desktop browser

### ISSUE THREAD

**Issue by johnmarzan** [brave/browser-laptop#4625]
i used to be able to log in to twitter mobile through brave. mobile.twitter.com 

but brave 0.12.4 (and maybe 0.12.3) i enter my username and password and nothing happens.

logging in using firefox works though. 

and logging in thru www.twitter.com works too. (i prefer using mobile.twitter.com because it is faster loading)

i'm using Win 7
- Brave Version: 0.12.4
- Steps to reproduce:
  1. go to mobile.twitter.com
  2. log in...
     3.

**Comment by johnmarzan** [comment]
i "shields down" mobile.twitter.com, still can't log in.

**Comment by bsclifton** [comment]
@johnmarzan do you have block scripts enabled?

I know we had some recent content filter changes w/ https://github.com/brave/browser-laptop/commit/74790fc129daceac20076203a487ef186a4ff569

cc: @diracdeltas

**Comment by austenlennon** [comment]
Yup.... me too... no matter what I try Twitter won't let me log in... I think that they don't like you Brave people... but I do !

**Comment by austenlennon** [comment]
Ahhh clearing cookies did it for me.....

**Comment by luixxiul** [comment]
Closing as fixed.
