### ISSUE TITLE
Menu is toggled with right alt (aka Alt Graphics aka AltGr)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4626]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The right alt key (AltGr) on Windows is not distinguished from the traditional alt key. This results in the menu being toggled when pressed. 

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:
0.12.4

- Steps to reproduce:
    1. Use Brave on Windows and visit http://fsymbols.com/keyboard/windows/alt-codes/list/
    2. Ensure hide menu by default is enabled
    3. Send focus to the demo text field, hold AltGr and then hit 1 to type a smiley face ☺
    4. Notice menu was toggled

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Pls also add issue to milestone when a PR is marked for the same milestone, thx!
