### ISSUE TITLE
Block/allow cookie based on hostname pattern

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-laptop#4629]
Is it possible to block or allow cookie based on hostname pattern? I mean something similar like this on Chrome

![blocks-site-chrome-hostname-pattern](https://cloud.githubusercontent.com/assets/8424198/19212988/dc14f916-8d89-11e6-99f2-2f5198e169e2.png)

**Comment by bsclifton** [comment]
This isn't available at the moment, but I'd love to have this.  +1 from me :smile:

**Comment by bsclifton** [comment]
Verified this is fixed in [brave-core](https://github.com/brave/brave-browser)
![screen shot 2018-09-02 at 11 36 14 pm](https://user-images.githubusercontent.com/4733304/44971063-0c41b780-af09-11e8-9199-900b257990e9.png)
