### ISSUE TITLE
Use an about: page for About instead of a Dialog so that text selection of version info is possible

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#463]
Help->About Brave pops up a dialog with version info. When reporting issues it woudl eb extremely useful to be able to select the text in that dialog to paste into the github text box

![aboutbrave](https://cloud.githubusercontent.com/assets/991242/12694352/e80b2892-c6df-11e5-9e7b-2fcd4a0b39a2.jpg)

**Comment by Oldpedro** [comment]
In osx brave you can copy this text no problem ("Version: 0.7.11
Electron: 0.36.5
libchromiumcontent: 47.0.2526.110")

**Comment by FrancisTurner** [comment]
Not in windows. Can't select the text

**Comment by bbondy** [comment]
This is just because dialog popups don't support it on Windows which that is using.
We could perhaps move it to a new about: tab

**Comment by jbmonroe** [comment]
I don't even get Help|About Brave now.

![brave-menu](https://cloud.githubusercontent.com/assets/1607804/12704267/f6ee636a-c824-11e5-9d9d-df3d7db41881.jpg)

**Comment by FrancisTurner** [comment]
Nor do I in Linux. Neither in the Help menu nor the righthand menu referenced by @jbmonroe 

In windows I'm only getting it in the Help menu

**Comment by psimyn** [comment]
@FrancisTurner iirc selecting the titlebar in Windows allows ctrl c to copy contents

**Comment by FrancisTurner** [comment]
I did not know that. But yeah it appears to work.

**Comment by jbmonroe** [comment]
That doesn't work at all for me.  "Selecting the titlebar?"  What does that mean?  Ordinarily text selection is clicking and dragging.  Clicking and dragging the title bar just moves the window.

**Comment by psimyn** [comment]
@jbmonroe by "select the titlebar" I just meant click it. In windows you can ctrl + c the active window to copy the contents (for dialogs at least)

http://www.howtogeek.com/howto/windows-vista/copy-windows-error-messages-to-the-clipboard/

**Comment by jbmonroe** [comment]
For the last two builds I can't get an "About" dialog at all, so even if 
Ctrl+c works, there's nothing to grab.

**Comment by FrancisTurner** [comment]
It works now with the current build

Hit About this. Click anywhere in the dialog that pops up. Press CTRL-C and you get the following

[Window Title]
Brave

[Content]
Version: 0.7.15
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110

[OK]

**Comment by bbondy** [comment]
I think it's more likely that we'll convert this to open an about: page with the information.
We currently use a Electron dialog for this and those work differently per platform which is not ideal.
That way it's obvious how to copy text and it's consistent between platforms.

**Comment by luixxiul** [comment]
On 0.9.6 on Windows 10 it stopped from working. CC'ing @bbondy

**Comment by luixxiul** [comment]
Confirmed this works on Ubuntu, this might be windows-only issue

**Comment by bbondy** [comment]
To fix this we just need to not use a dialog for the version info and instead use an about:brave page or similarly named.

**Comment by luixxiul** [comment]
+1 from support

**Comment by bsclifton** [comment]
I could definitely be wrong, but it might be easy to add this. We could add this information here:
https://github.com/brave/browser-laptop/blob/0218b28f8a61979997485962de557a00ca5274fb/js/about/about.js
