### ISSUE TITLE
Have to reload page to make Dashlane fill password fields

### ISSUE THREAD

**Issue by wolfhawke** [brave/browser-laptop#4630]
When Dashlane is active in Brave, the password popups and autofills do not appear as active unless the page is reloaded. This is especially true with https://microsoftonline.com logins, but has been experienced on other platforms, like live.com or email.1and1.com

When logged in, Dashlane should be active as soon as the page loads and not require a reload.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.3
- Steps to reproduce:
  1. Log into Dashlane
  2. Attempt to log in to microsoftonline.com, live.com or email.1and1.com
     3.

**Comment by jackpodsedly** [comment]
I have the same problem with windows 7. I have to reload the page to get dashlane to work
