### ISSUE TITLE
Feature Request: Easier way to set which sites to pay

### ISSUE THREAD

**Issue by osyed** [brave/browser-laptop#4634]
**Did you search for similar issues before submitting this one?**
Yes, but no one has suggested this way of doing it.

**Describe the issue you encountered:**
Under Settings-Payments there is a list of all sites visited along with a toggle button next to each site to include or exclude from receiving payments. It is very cumbersome to go through this list and set the toggle for each one. Aside from this an easier way is needed to set the include/exclude toggle as suggested below.

**Expected behavior:**
When a new site is visited that is not already in the list of visited sites, a question bar should appear at the top of the page to ask "Should this site be included to receive payments [Yes] [No]". If the question bar is closed without answering, the default should be to exclude the site from receiving payments. Also the bar can timeout after a few seconds if not answered or closed.

In addition, next to the bookmark icon (star) there should be a payment icon (maybe a dollar sign) which is filled with green if the site currently being visited is included to receive payments and unfilled if it is excluded. Clicking on this icon should toggle the payment include/exclude settings for the current site. Hovering over the icon should show what would happen if the icon is clicked.  
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  Latest
- Steps to reproduce:
  Not a bug.
- Screenshot if needed:
  Not needed
- Any related issues:
  No

**Comment by luixxiul** [comment]
cc @mrose17

**Comment by Sh1d0w** [comment]
I think it will be annoying to get a notification each time you visit a new website, as this will distract you if you are just browsing the internet daily. Maybe this has to be an optional behaviour and to be triggered only if you have enabled Brave payments.

**Comment by osyed** [comment]
Yes, it makes sense to only have the question bar triggered if you have
Brave payments enabled.

**Comment by neeklamy** [comment]
I really like the idea of having a currency icon next to the bookmark star, maybe something like:

![Brave titlebar ledger button bitcoin](https://cloud.githubusercontent.com/assets/155358/19215085/f460d902-8d8b-11e6-83b1-633ab9d9791e.png)

**Comment by mrose17** [comment]
i suspect that being asked for new sites would be far too invasive, even if limited to when brave payments is enabled. it may be worth having an option to allow this to get experience though...

@neeklamy - i agree. i believe that is what @ayumi was suggesting in https://github.com/brave/browser-laptop/issues/3834

**Comment by osyed** [comment]
@neeklamy - Showing a bitcoin icon might be a bit too early. Most people would not understand what the icon is for. I think it would be safer to start off with a dollar sign icon first and then change to a bitcoin icon after more people have learned about bitcoin. In a TechCrunch article Brendon is quoted as saying:
"We’re really only using bitcoin under the hood. We’re trying not to make users care about it or learn about it if they don’t want to, The main idea with Brave is that you don’t have to think about Bitcoin, you just have this frictionless payment system.”
So until more people associate bitcoin with money, it would be safer to use the dollar sign which is more universally associated with money.

**Comment by osyed** [comment]
@mrose17 - Perhaps on the payments page there can be a selection like:
    When I visit a new site: X Ask if I want to include it for payments,  O Always include,   O Always exclude

The default could be to ask and this selection could also be shown in the question bar that pops up when visiting a new site.

Maybe in the future there could also be an option to "Auto decide". This allows the browser to determine the default payment include/exclude setting for the site when it is first visited based on stats of what others have chosen. For example most people would not include for payments sites like Walmart or Amazon, but would include sites like XKCD or CoinDesk. The browser could query the Brave payments server to determine if a site should automatically be included or excluded from payments.

**Comment by Sh1d0w** [comment]
@osyed This "auto decide" algorithm won't be efficient, since once website for one part of the users won't be in interest for donating, but this does not mean it is the same for the other part of the users. Since this are "personal preferences" they can not be generalized, and I am not talking about lrage websites, this applies for small websites as well.

For me the best approach will be with the payment icon next to the url bar, without any annoying types of notifications.

**Comment by srirambv** [comment]
@mrose17  Here's what I think would be much neat
1. Adding the payment icon (similar to what @neeklamy  suggested above) may be similar to the widget next to Lion head. Clicking on it brings up a drop down widget which allows users to enable or disable the webpage for payments. This might clutter the space when user reduces the window size.
2. Put a small modal at the bottom of the page with the same switch to enable payments. If the user enables payment then close the modal. If the user wants to ignore then press the close button on the modal so that it does the same function as disable function on payment page.

Irrespective of what action user does using the widget or the modal the site will get added to the payments list

**Comment by neeklamy** [comment]
@osyed, I see what you and Brendon are saying about the use of “Bitcoin” and the Bitcoin logo<sup>*</sup>, I nearly mocked that up with a $ too. It’s a lot easier to think in a “real world” currency, even an international currency such as the US dollar is easier than Bitcoin.

Separate issue, but it seems like an option to display buttons and other payment indicators in a preferred currency would be the way to go.

I’m with you too on not wanting to give Amazon any more money, it should be considered, but I’m just not sure about the crowdsourcing method.

<sup>*</sup>The TechCruch article [Brave, the ad-blocking browser from former Mozilla CEO, grabs $4.5 million](https://techcrunch.com/2016/08/01/brave-the-ad-blocking-browser-from-former-mozilla-ceo-grabs-4-5-million/).

**Comment by osyed** [comment]
@Sh1d0w - You are right there is a problem with "auto decide" especially for smaller websites. It would tend to push sites with greater than 50% included for payments towards even higher percentages and push sites with less than 50% included for payments towards even lower percentages. A possible solution could be that the browser decides stochastic its choice of including or excluding the website for payments. For example the choice could made like:  include for payments if R < P; where R is a randomly chosen number between [0, 1) and P = (N*(C/100) + 10*0.5) / (N + 10); where C is the percent of people that have chosen to include the website for payments and N is the total number of people that have made a choice. The browser would have to query the Brave server to get the values of C and N for a particular site. When a user changes their setting for a website the browser would have to report it to the Brave server. The reporting should be delayed and batched so that it is done only about once every 10 minutes if there are any changes to report. Of course the reporting would have to be secured similar to how the browser is reporting the amount of time spent on each site.

**Comment by mrose17** [comment]
just to clarify: the only thing that the browser sends to brave software's servers is either a partially-signed bitcoin transaction for co-signing and then transmission into the bitcoin network -OR- an anonymized "vote" for a publisher identity. at no time does your browsing history, or any partial aggregation of your browsing history leave your browser.

the browser uses a technique called _statistical voting_ -- https://github.com/brave/ledger/blob/master/documentation/Ledger-Principles.md#ad-free-statistical-voting -- in brief, if you tend to visit site X twice as often as site Y, then site X is twice as likely to get a contribution as site Y. when large numbers of browsers do this, the percentages of contributions should tend to reflect reality without anyone having to divulge their actual percentages.

i'm not sure how one would adapt statistical voting to work with _crowdsourcing to determine which sites are actually publishers_. i'm not saying that it can't be done, but it would probably require some kind of independent calculations based on other anonymous data that gets fed back to the browser...

**Comment by bradleyrichter** [comment]
I appreciate the great discussion here but one of the premises behind Brave Payments is that we are trying to reduce or eliminate the cognitive cost of micropayments for ad revenue replacement. 

some info: http://hackingdistributed.com/2014/12/31/costs-of-micropayments/

One of our main challenges right now is to prune the list of sites on the web that make sense (by default) for receiving user contributions. Work is active on this task and will greatly alleviate user pain and cognitive costs.

cc @BrendanEich

**Comment by BrendanEich** [comment]
@aekeus is improving the global exclusion list, so cc'ing him.

@bradleyrichter makes the important highest-order point: do not bug the user or decision fatique and out right annoyance will kill the whole microdonations idea. Instead of brute force UX that puts the burden on the user, we need better exclusion defaults and algorithms that do not bother the user either way (false negatives; false positives).

I know this sounds like the much-touted magic AI. Off the shelf machine learning, even deep learning these days, is not magic, but it does need training data. We should evolve toward it in steps. For this issue we should not put any prompting, even infobar-style, into the per page user interaction design.

**Comment by osyed** [comment]
@bradleyrichter - wow that's great; I didn't know about the effort to create a global inclusion list. This will definitely reduce the cognitive cost of deciding which sites receive my contribution. In light of this, I would retract my suggestion of having a question bar appear the first time a user visits a website and  I would only suggest having an icon in the browser to let the user toggle the payment setting while viewing a page on the website. So the default behavior of the browser could be to automatically set the site to receive payments if it is in the global inclusion list, otherwise it is set to not receive payments. The user should be able to easily toggle this setting while visiting the site by simply clicking on an icon. If a website that the user cares about is not automatically set to receive payments, it would only be a one time decision for the user to turn it on. This is much less effort for the user than the browser erring on the side of turning on payments (by using a global exclusion list) and requiring the user to turn it off if they don't care about the website.

**Comment by mrose17** [comment]
@bradleyrichter - somewhat related, please take a look at https://community.brave.com/t/restrict-certain-publishers-from-receiving-contributions/95/2

**Comment by osyed** [comment]
I was really excited about using the Brave browser, but I have currently stopped using it. The default behavior of the browser automatically deciding which sites to receive payments and allowing the user to turn it off is way to cumbersome to deal with. As can be seen from the comments of users in the link of the previous post, users may have a multitude of reasons why they don't want to contribute to a site (already subscribing, don't agree with the sites views, etc) which the browser has decided is a legitimate publisher. So it doesn't matter how much AI the Brave browser puts into filtering real publisher sites into an inclusion list, I will still need to go to the payments page, find the publisher and check if the browser decided to pay this site or not. Why because most people care about which sites their payments go to and no matter how much AI you put into the browser, you won't be able to satisfy everyone. 

It would be much better if the default behavior was to automatically not pay any site and just provide an icon next to the URL bar that shows the current payment status and allow the user to turn on/off payments to the site being visited. The Brave developers may think this is too much of a cognitive cost for the user, but I don't think it is, since I really only need to think about it once per site and only for the sites I wish to pay (since the default is to not pay any site). I would switch back to using the Brave browser if it worked like this.

The developers may also think that if the default behavior was to not pay any site and allow the user to turn on payments for the sites they care about, it would result in less sites receiving payments. This may be the case, but it should not matter. The total amount of payments being made through Brave should be more important than the total number of sites being paid. In other words the total number of users using Brave to make payments to the sites they visit should be more important than the number of sites being paid. The current approach Brave is taking tries to maximize the number of sites being paid at the cost of lowering the total number of users using Brave to make payments.

**Comment by bradleyrichter** [comment]
@osyed We will build a per-site pay button and let the user decide if they want to use auto or manual. I am certain that your opinion and explanation represents a large percentage of our users. But we don't know which is larger yet. 

Regarding cognitive costs, if the cognitive cost of the tip (in the case of micro-tipping) feels larger than the tip, it becomes too cumbersome over time. 

I am willing to test the theory and consider that paying a site-per-month is a larger "tip" than giving a penny after enjoying the first 1/3 of a typical article so this could still work as you have explained.

Regardless, we certainly don't want to burden the user with the need to check all of their micro-donations at the end of each month. As the system improves, and eventually when crowd-sourced anonymous exclusion data is possible, I think we could arrive at a place where automatic becomes the preferred choice for most users.

For an opt-in(pay) approach as you described, we may find that users naturally support smaller sites that may not even have programatic advertising. This would be a great thing, and overall, the law of averages would probably work out.

Let's keep this thread open so I can provide a mockup of the per-site opt-in UX.


Thanks for your detailed feedback...

**Comment by osyed** [comment]
Thanks for considering my feedback. I'm sure the Brave team will find a way to make the tipping process much easier. That's why I still open the Brave browser every so often and let it update to see if the tipping UX got easier. Looking forward to seeing the mockup.

**Comment by bradleyrichter** [comment]
@osyed Have you tried the new override switch and new URL bar button for individually marking sites for inclusion? I'd love to get your feedback now that it's in beta...

**Comment by osyed** [comment]
Yes, I am using the Brave browser as my default browser now. I have the wallet loaded and it's great knowing that the sites I use regularly will be receiving a contribution. The icon next to the URL bar makes it so easy to check and control which sites are included. The algorithm for auto include seems to be working pretty good too. I still check the included sites list once in a while though since some sites get picked up that I don't really want to include for payments. For example my bank site got included. It would be nice if there was a way to sort the list so that recently included sites could be brought up to the top; that would make finding such sites much easier. I noticed there is an option for removing specific sites. I'm a bit confused as to why this is needed when I can just chose to not include and still have the option to include it again later if I change my mind. I find myself not using the remove option even for sites I know I will never include just because I might want to see the usage stats for the site.  But other than that I'm loving it. Thanks so much guys for all the hard work you've put into making the UI easy and intuitive.

This is a bit off topic for this thread, but I was wondering if there are plans for allowing the Brave browser to handle 402 responses such that payments could be made from the browser wallet. I was just discussing with a friend today about the possibility of the browsers doing this in the near future and what a huge impact that will have on the Internet.

**Comment by NejcZdovc** [comment]
@osyed in version 0.14.2 (next version) you will get a new pack of exciting features :smiley: more info in this issue #7347

**Comment by zentagonist** [comment]
@osyed - Can you please take a look at this again? We'd love to hear your feedback on the current state.

**Comment by osyed** [comment]
@zentagonist I've been using the Brave browser as my primary browser for many months now and using the payment feature. It's great. You guys have done a great job of making the complex payments management feature much easier to work with. I do have some minor suggestions though.

1. The heart icon on the right of the URL bar doesn't really conveying what the icon is for. It's really about including or excluding the site for payments; not how much I love the site. There are sites I love, but don't want to include them for payments since I might already be a paying member on the site. I inclined to suggest using a dollar sign, but I can see how that is not internationally the symbol for money. So I don't have a good suggestion for an alternative icon. But at the very least I would strongly suggest adding a hover message like "Include-Exclude site for payments". Hovering over the bookmark symbol gives a message, so I'm sure adding a message to this icon should not be too hard.

When payments are turned off, the icon goes away. I would suggest keeping the icon there but in orange (or some other color) as a way to remind the user that payments are turned off. Clicking on the icon when payments are turned off should open a tab with the payments settings page. Otherwise there is nothing at the top level to bring the user to the most important feature of the Brave browser (which of course is payments). Actually ad blocking is pretty important too and you have the lion icon at the top level to make the user aware of this feature. Payments deserves something like this too, especially when it is turned off.

On the payments settings page, the trash icon is a bit dangerous, since I don't see a way to bring the site back if I accidentally trashed it while trying to click on the adjacent pin icon. Maybe having a way to see the trashed sites and untrash them would make the situation better (sorted with the most recently trashed at the top).

It would be nice to sort the sites on the payments page by recently visited so one can visit the site to find it in the list of sites when the list gets very long. Another option would be to allow filtering the sites based on characters typed into a field next to the "Site" heading of the table.

**Comment by luixxiul** [comment]
@osyed thanks for your feedback. I opened suggestion issues based on that.

**Comment by osyed** [comment]
@luixxiul 

Thanks for creating those. How about also adding some issues for the following:

1. Display tool tip message like "Include/Exclude this site for payments" when hovering over the current heart icon. 
2. When payments are turned off, display the heart icon in a bright color. When the icon is clicked open a tap to the settings payment page.
3. Allow sorting the sites on the payments page by recently visited.
