### ISSUE TITLE
Nesting Tabs 

### ISSUE THREAD

**Issue by MikePadge** [brave/browser-laptop#4638]
**Expected behavior:**
_Feature Request_

Opening new tabs from the FQDN sorts tabs with the same FQDN beneath the initial tab entry point of said FQDN, and expands tab menu to reveal nested tabs when a tab with nested tabs is selected.

Instead of 

<img width="1280" alt="root before" src="https://cloud.githubusercontent.com/assets/22322602/19215237/19e728ee-8d5e-11e6-9450-62a6f1485208.png">

You have something similar to this.  

<img width="1280" alt="root after" src="https://cloud.githubusercontent.com/assets/22322602/19215251/61323d42-8d5e-11e6-8152-fa34b40e54b8.png">

This serves to keep tabs cleaner in an a.d.d. tab browsing session by confining tabs from the same site to one tab, with nested tabs.

**Comment by bigkitttty** [comment]
I'm for it.

**Comment by luixxiul** [comment]
+1 as a option

**Comment by bigkitttty** [comment]
me 2

**Comment by bbondy** [comment]
@bradleyrichter this is very cool, thoughts?
Maybe even not taking up more height by them showing up only when you hover

**Comment by bradleyrichter** [comment]
Yes. We need something like this. GitHub tab overload is driving me crazy. Let's aim for 1.2.

**Comment by MikePadge** [comment]
So I've been thinking about this. I wouldn't be opposed to having the "nested tabs" actually appear as a vertical menu that pops in when you hit one of the root tabs that are horizontal across the top. Kind of like Safari's bookmark menu.
