### ISSUE TITLE
Fullscreen video causes tab and video to disapear

### ISSUE THREAD

**Issue by Infernoman** [brave/browser-laptop#464]
Fullscreening a video on facebook specifically not sure about other websites, Causes the video and the browser to go into fullscreen. the video disappears but plays in the background and the tab in which the fullscreen video originated is no longer in the browser.

**Comment by Infernoman** [comment]
Update on that quickly. I was able to get the tab back when i pinned an existing tab. From there I was able to go onto the facebook tab and see the video playing in full screen and close the video and tab. But the browser is still in full screen with no way to remove it from that mode.

**Comment by luixxiul** [comment]
Does this still persist?

**Comment by neeklamy** [comment]
It does, I’ve seen this on Brave 0.10.0 and 0.10.2.

You can see it here: [Google DevTools Timeline](https://developers.google.com/web/updates/2015/03/devtools-timeline-now-providing-the-full-story) (scroll down to the Frame Viewer section).

When full screened:
- The page’s sidebar and top navigation remain,
- Where I’d expect the video to appear it is just black (Brave 0.10.0 just full screened the page),
- The video continues to play in the background,
- The video’s audio keeps playing.

![Brave 0.10.2, full screen video not displaying](https://cloud.githubusercontent.com/assets/155358/15817895/2e4196a0-2bd2-11e6-9dc7-5310d0d4675c.png)

**Comment by luixxiul** [comment]
It does on Chrome too

**Comment by neeklamy** [comment]
And unsurprisingly in both Opera (latest 37.0.2178.54) and Opera Beta (38.0.2220.25).

Safari (9.1.1) and Safari Technology Preview (latest version 5, 11601.6.17, 11602.1.33) have a similar problem, the video goes full screen, but the page navigation remains.

So it looks like it’s more of a WebKit bug?

I’d try an older Google Chrome, but it looks like sourcing a reliable download is a bit tricky.

(All on OS X 10.11.5)

**Comment by cezaraugusto** [comment]
Still reproducible visiting https://developers.google.com/web/updates/2015/03/devtools-timeline-now-providing-the-full-story

**Comment by neeklamy** [comment]
Well, it’s still there in the latest Google Chrome too, I’ve submitted a bug report to Google (via Chrome’s built in submission process, *Help → Report an issue…*). I will update here if I get any response.

**Comment by luixxiul** [comment]
Then it's the issue of Chromium

**Comment by neeklamy** [comment]
I’ve found another example on the Guardian website. Scroll down the page, there’s an embedded tweet which links to a YouTube video, which when made full screen, doesn’t display: [Tesla driver dies in first fatal crash while using autopilot mode](https://www.theguardian.com/technology/2016/jun/30/tesla-autopilot-death-self-driving-car-elon-musk).

This happens whether Brave’s shields are up or down, or up and allowing adverts and tracking (Brave 0.10.4).

**Reproducible** in Google Chrome (latest version, 51…, and reported to Google via the Help menu).
**Works correctly** in both the latest Safari and Safari Technology Preview 7.

Other videos on the Guardian website play just fine, scroll further down that page to see another embedded YouTube video (“Tesla Autopilot v7.0 Stop and Go Traffic”). This other Guardian video plays fine too, [Safety pins puncture racism after Brexit vote](https://www.theguardian.com/world/video/2016/jun/30/safety-pins-puncture-racism-after-brexit-vote-video).

(All on OS X 10.11.5)

**Comment by Liunkae** [comment]
No longer a problem for me with the latest version of Brave (0.17.13).
