### ISSUE TITLE
Add option to control tab close behavior 

### ISSUE THREAD

**Issue by cvanderlinden** [brave/browser-laptop#4641]
First open a new tab from a link; either right clicking and choosing the action or control + clicking the link.  When you close the newly opened tabs, the browser refocuses on the left most tab (first tab).  I believe the expected behaviour is that the next tab to the one you closed should be the newly focused tab.

This behaviour does appear to be in the browser and can be recreated by: control clicking links that are in your bookmark bar.  When closing these newly created tabs, the behaviour works as expected.  It doesn't refocus the first tab, but instead the next on in the list.

Here is a video of this issue.  The first pass through shows what happens when new tabs are opened and then closed (the issue).  The second pass through is what happens when new tabs are opened from the bookmark bar (the correct way).

https://drive.google.com/open?id=0B7566usfLEdfX25PWnYydUtfVDA

If this is the expected behaviour then please close.  It just seems counter intuitive to me.

Linux Mint - Brave 0.12.4

EDIT: I just did some more testing, and it appears that when you close a newly created tab, it goes back to the original tab where that link was originally opened from.  This makes me think that this is a feature.

In my opinion (of course just an opinion) this is not how it should work.  When I browse the web and open up multiple new tabs, it's because I want to look at them all in succession, while still keeping the original page open.  This current way would make sense if I only opened one new tab, but if I open up two or more it should flip to the other tabs instead of going back to the original page.

**Comment by bbondy** [comment]
+1 from support: https://linkbubble.zendesk.com/agent/tickets/6573

**Comment by stan-qaz** [comment]
I also find this behavior on closing a tab frustrating. I will usually visit a site, open a few to a dozen tabs for links on the site that I wish to read and then read and close the tabs. Instead of Brave showing me one of the tabs I recently opened it shows me the original page and I have to manually select one of the new tabs to view. Particularly frustrating when the original tab and new tab(s) are in different tab-groups.

**Comment by cvanderlinden** [comment]
@stan-qaz I hear you.  I feel like if we were to add an option, it should be the reverse.  The default should be the way I described it. I also think that adding an option may be unnecessary, I don't see a purpose to the original functionality.  It may just be me, but it's quite annoying.

**Comment by bsclifton** [comment]
We added this sometime in 2017
