### ISSUE TITLE
Cut and paste

### ISSUE THREAD

**Issue by cjanning** [brave/browser-laptop#4643]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
copy and paste feature doesn't work since last "update"

**Expected behavior:**
no... it worked fine until last update
- Platform (Win7, 8, 10? macOS? Linux distro?):
  win 7
- Brave Version:
  damnifino
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Same as #4490?

**Comment by bsclifton** [comment]
There's not enough info here to troubleshoot.  I'm going to close this issue for now, but please feel free to reopen with more info.

**_Note_**: I am currently fixing some copy/paste behavior I introduced with 0.14.0 (released 3/30/2017) with https://github.com/brave/browser-laptop/issues/8000
