### ISSUE TITLE
Baidu map doesn't load properly in ctrip website

### ISSUE THREAD

**Issue by xiaohanzhu** [brave/browser-laptop#4645]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
Baidu map doesn't load properly in ctrip.com website
**Expected behavior:**
map should appear
- Platform (Win7, 8, 10? macOS? Linux distro?):
  windows 10
- Brave Version:
  0.12.4
- Steps to reproduce:
  1. go to the following link
     http://english.ctrip.com/hotels/shenzhen-hotels-map-30/
     map loads properly in other browsers.  
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
If you disable HTTPS Everywhere the map appears. The ruleset named "Google Map" causes the issue / cc: @diracdeltas

**Comment by privatzee** [comment]
It's odd that maps.google.cn doesn't allow https and so the connections time out. 
https://developers.google.com/maps/faq#china_ws_access

google brags lately that they protect their users from spying by everybody (except themselves, of course). But there they seem to be allowing the Chinese government to spy on whatever their citizens are looking at on any google.cn sites. I wonder: if somebody within China goes to maps.google.com, do they get redirected to maps.google.cn?

**Comment by diracdeltas** [comment]
will bring up with google security

**Comment by diracdeltas** [comment]
It seems the issue has been fixed by Google. When I visit the site from a US IP address, the map loads. I don't know if it is blocked by Chinese ISPs for some reason.

**Comment by luixxiul** [comment]
This issue can be closed I think as I also could not see the map but now I can, from Japan.
