### ISSUE TITLE
Implement Getting started page for first time install

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4646]
Currently Brave starts immediately after installation. There is no getting started page implemented like on iOS app. This will greatly help users installing it for the first time. Several users have also reported not fining an help guide and getting started page.

**Comment by bsclifton** [comment]
Having this page discuss what shields up / shields down means would be great too (+1 from support)

**Comment by luixxiul** [comment]
`about:welcome` has been implemented 👍
