### ISSUE TITLE
caption buttons overflow the window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4647]
**Describe the issue you encountered:** the caption buttons on the titlebar overflow the window. This does not happen in English for now because of the length of strings on the menu bar. In Japanese for example you get:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19228361/6702c546-8eff-11e6-8f98-a383a2c02dc9.png)

**Expected behavior:** It should not overflow.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

- Brave Version: 0.12.4

- Any related issues:

**Comment by luixxiul** [comment]
It must be happening on other languages. Setting a milestone with not-blocking.

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
Will need more time to find a solution for this- bumping to 0.12.6

**Comment by luixxiul** [comment]
Closing this as this is a dupe of #4318
