### ISSUE TITLE
color of div#window.frameless should be lighter?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4648]
**Describe the issue you encountered:** I'm wondering if the color of ``.platform--win32 div#window.frameless`` should be lighter. Here's a comparison between the current version and the ligher version (``color: #888``).

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19228753/1cadbe98-8f03-11e6-8716-c1b180f1f9f2.png)
![clipboard02](https://cloud.githubusercontent.com/assets/3362943/19228756/1fe0772c-8f03-11e6-8054-b7321c95e80c.png)

I prefer the below. What do you think, @bradleyrichter ?

If it is ok, I think this should be enabled only for Windows 10 if possible, as the current border color on Windows7 looks like the same as the default one.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.4

- Any related issues:

**Comment by bsclifton** [comment]
We could definitely make this lighter... the problem is, the color used for the border on Windows 10 depends on your own custom theme.  By default, it's a blue color... but you can change to whatever you like (including change to match background color; and you might have your background as a slideshow)

**Comment by luixxiul** [comment]
Thanks @bsclifton! Do you think it would be possible for us to make the value to be changed automatically based on the theme? The value seems to be hard-coded for now here: https://github.com/brave/browser-laptop/blob/d895e316dd35a5a9dc5298c7846eb79c9d0792af/less/navigationBar.less#L40

**Comment by bsclifton** [comment]
Per discussion with @bradleyrichter, maybe we can do the following:
On Windows 10:
- Border color can be #2283d3 (default blue color) when window has focus
- Border color can be #aaaaaa when the window loses focus / blurred
