### ISSUE TITLE
Unable to subscribe to Brave Newsletter

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4649]
**Did you search for similar issues before submitting this one?**
Yes. 
Reported by support

**Describe the issue you encountered:**
Unable to subscribe to Brave Newsletter

**Expected behavior:**
User should be able to subscribe to newsletter. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.4

- Steps to reproduce:
    1. Visit https://www.brave.com
    2. Enter email id in the email id field
    3. Click on the subscribe button
    4. Displays the error message

- Screenshot if needed:
 ![image](https://cloud.githubusercontent.com/assets/17010094/19236972/dfb9245e-8f17-11e6-8c91-ab7caa12e6b2.png)

- Any related issues:

**Comment by bbondy** [comment]
@diracdeltas do you think this is a web bug or a brave bug?

**Comment by neeklamy** [comment]
From the console:

> Failed to load resource: the server responded with a status of 403 (Forbidden)
https://www.brave.com/api/mailchimp

But I can confirm that if the shields are dropped, the subscription goes through A-OK!

> Success!  
> Thanks for joining our email newsletter! Say hi on Twitter at @brave

And it’s the same story on Google Chrome using Adblock Plus, ABP has to be paused before the email can be submitted.

**Comment by privatzee** [comment]
Is it fixed already? That was fast. I was able to get past the error dialog and subscribe but haven't received any email confirmation after several minutes.

P.S. Nice catch, srirambv. Just imagine how many people out in the world tried and then just went away without saying anything when it didn't work.

**Comment by srirambv** [comment]
@privatzee this was reported by one the users on support. 

You get the error only on the first attempt. Subsequent tries it automatically shows the Success message.

**Comment by diracdeltas** [comment]
this is almost certainly due to a website bug in how csrf tokens are set

**Comment by diracdeltas** [comment]
fixing this on brave-website

**Comment by bbondy** [comment]
thanks!
