### ISSUE TITLE
Enable F12 to open the Developer tools

### ISSUE THREAD

**Issue by AlfonsoML** [brave/browser-laptop#465]
Just like the rest of the browsers (at least in Windows), F12 should open the Developer tools

**Comment by 16nsk** [comment]
__Ctrl + Shift + I__	/ __Cmd + Opt__ + I is actually the main shortcut keys for "Developer tools" in Chrome and Firefox (may be in Opera and some other).

__F12__ is the default for Internet Explorer and accepted by Chrome on Windows only.

Maybe like Chrome does, both shortcuts should be there for convenience and acceptance of most of us.

**Comment by bbondy** [comment]
F12 was added for Windows / Linux here:
https://github.com/brave/browser-laptop/commit/e185d6fe75a1927d45c73b00686e713a310bd0d7
It'll be in 0.9.0

**Comment by madalinignisca** [comment]
No we have to move my hand... Why not respecting what the majority supports? CMD/CTRL + Shift + I?

**Comment by bbondy** [comment]
we also have those.

**Comment by madalinignisca** [comment]
Thank you. I'll try it at home later on a personal project.
