### ISSUE TITLE
Content is being blocked due to ad tracking wrapping

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4652]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Users in support (ex: https://linkbubble.zendesk.com/agent/tickets/5824 ) are reporting that video is not working for sites when very often their video is wrapped in a tracker. Since we block trackers by default, users do not understand the connection between the two and often believe that our browser is broken.

**Expected behavior:**
Users need a better means to identify the issue and allow for content they wish to view. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X.
- Brave Version:
  0.12.4
- Steps to reproduce:
  1. Visit a site with tracked video (ex: http://northpoint.org/messages/who-needs-god/atheist-2-0/)

**Comment by alexwykoff** [comment]
cc @bradleyrichter for design
cc @diracdeltas because this very often is related to flash playback and we're getting quite a few support tickets about video 'not working'

We need a better solution than simply pointing users toward our deprecation policy.

**Comment by diracdeltas** [comment]
@alexwykoff sorry, do you have any a list of sites where this is related to flash? the video in the link above is HTML5.

related to https://github.com/brave/browser-laptop/issues/3572

**Comment by diracdeltas** [comment]
quick way to check if a video is actually flash:
1. open page console and type `document.querySelector('video')`
2. hover over the result in the console. if it highlights the video on the page, it's probably html5 video, not flash.

**Comment by privatzee** [comment]
With my Brave (without Flash installed), the video is mp4. Btw, it **breaks with Fingerprint Protection** enabled, as well as tracker-blocking. But with my PaleMoon (with Flash installed), the video is Flash. 
Win7x64

**Comment by diracdeltas** [comment]
@privatzee yeah i saw that fingerprinting protection also breaks this video but it's not default-on.

many sites load html5 video in brave but are flash in other browsers
