### ISSUE TITLE
Audio track plays twice, simultaneously, offset by 8 seconds

### ISSUE THREAD

**Issue by faragorn01** [brave/browser-laptop#4653]
I didnt find anything searching the existing tickets.

For pages with embedded video clips for Space.com, the video starts playing along with the audio, and about 8 seconds later, the audio starts playing again, so the two audio tracks are both going simultaneously but offset.
Here is a url that exhibits the problem:
http://www.space.com/34334-proxima-centauri-habitable-second-earth-interstellar-alien-life.html

**Expected behavior:**
- Platform (Win7):
- Brave Version:
  Brave 0.12.4
  Electron 1.4.12
  libchromiumcontent: 53.0.2785.143
  V8: 5.3.332.47
  Node.js: 6.5.0
- Steps to reproduce:
  1. Go to the following URL: http://www.space.com/34334-proxima-centauri-habitable-second-earth-interstellar-alien-life.html . Note other videos from the same site act the same.
  2. Wait for the video to start playing, along with audio.
  3. Approx 8 seconds later, the duplicate audio track starts up, so both are playing simultaneously.
- Screenshot if needed:
  None
- Any related issues:
  None

**Comment by neeklamy** [comment]
I can’t replicate this on OS X 10.11.6, Brave 0.12.4.

… I am seeing an awful lot of [chum](https://theawl.com/a-complete-taxonomy-of-internet-chum-de0b7a070a2d#.n2hzo2amc) getting past Brave’s adblocking though.

![brave-whats-this-chum](https://cloud.githubusercontent.com/assets/155358/19248538/9be38f42-8f28-11e6-88bf-fa8068de9570.jpg)

**Comment by luixxiul** [comment]
Closing as fixed.
