### ISSUE TITLE
Suggestion: Indicate when a link will open in a new tab

### ISSUE THREAD

**Issue by neeklamy** [brave/browser-laptop#4654]
The pop-up status bar should indicate links that are either coded to open in a new tab or will open in a new tab through use of a keyboard modifier.

```
<a href="https://eff.org/https-everywhere" target="_blank">HTTPS Everywhere</a>
```

Comparing browsers implementations:

![Comparing browser status bar implementations](https://cloud.githubusercontent.com/assets/155358/19246912/8829fcf0-8f20-11e6-9624-63d41120dcd1.png)
## Scenario: Link opens in new tab

When a link will open in a new tab:
- Neither Google Chrome or Brave gives any indication that that link will open a new tab.
- Safari, by contrast tells you it will open in a new tab:  
  `Open “https://eff.org/https-everywhere” in a new tab`  
  – When clicked on, the new tab is opens and we are switched to it.
## Scenario: Link is optionally opened in a new tab

When a keyboard modifier (⌘ on a Mac, ctrl on Windows and Linux) is used to force a link to open in a new tab:
- Neither Google Chrome or Brave show any indication that the link will open in a new tab.
- Safari changes the status bar wording:  
  `Open “https://github.com/…” in a new tab behind the current one`
## Scenario: Optionally open a link in a new tab behind the current tab

When a link that would open in a new tab, is opened using a keyboard modifier, it is opened in a new tab behind the current tab. The wording in Safari is the same as the “new tab behind current” text:  
`Open “https://github.com/…” in a new tab behind the current one`
## Suggestions
1. We copy Safari’s behaviour of spelling out exactly what will happen, it offers the least surprise.
2. I would also add that it would be nice to have an override for links that are made to open in a new tab (`target="_blank"`) to force them to open in the same tab, perhaps using a different keyboard modifier?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-how-to-make-it-clear-that-new-tabs-opened/10056/2

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
