### ISSUE TITLE
Create an additional (optionally) smaller search field for the navigation toolbar

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#466]
The reason why, more advanced users love to work efficient and sometimes use more then one search engines for various reasons.

Having a possibility to make use of a second search engine instantly would enable it to open a tab and make a search in the common address field with one search engine and opening a second tab and starting instantly a search with the second set search engine in the smaller field, without the need to be forced to change the search engine in the main field before being able to start a new search with another search engine.

If this is overkill in your opinion and not wished for brave, give us at least a function which makes it possible to switch search engines with the least possible amount of additional steps, would work the same way (search shortcuts aka g for google and so on).

**Comment by bradleyrichter** [comment]
@sj-diamond I agree the use case is warranted. It should be solved with some future additions. I'll keep this open and post a UI mockup to get your feedback.

Thanks for the detail in your request.  - Brad

**Comment by SJ-Diamond** [comment]
Nice to hear that you are open for suggestions :) One thing i forgot, if there is such a smaller field is created, there should be an option that you can set search engines in a separate way, so if you have for example Duckduckgo in the main field and Wikipedia in the small additional search field and you are switching to Google in the main, Wikipedia should still stay in the smaller field.

**Comment by Arandhras** [comment]
I like this too, being able to switch search engines would be very useful... in my workflow it's something I do very often and it would be nice to have it also in Brave!

**Comment by psimyn** [comment]
@SJ-Diamond what about being able to use the main bar as a search bar, as shown in this ultra-HD gif:

![searchwith](https://cloud.githubusercontent.com/assets/1731922/13031102/afcf8276-d313-11e5-93d5-87905582a86f.gif)

Enter a search engine name, then tab to start search. Backspace in empty field clears it. Could be made a bit more clear with some UI hints, but I think this way allows everything you want without needing multiple search bars

**Comment by SJ-Diamond** [comment]
But what is wrong with an optional search field? There are enough browsers which offer minimalism or simplicity. And with the unique structure of Brave you guys could create both a browser, which simple users and power users would love.

**Comment by Arandhras** [comment]
I am not sure I like @psimyn's suggestion. I understand the need of keeping it as simple as possible, but having to write "google.com", "wikipedia.org" or "youtube.com" before every single search in the omnibar is quite a hassle. At the very least, if only a single bar is going to be used, at least you should offer (editable) shortcuts, like what duckduckgo.com does internally (using the previous examples, !g = google, !w = wikipedia, !yt = youtube).

Anyway, as SJD said a secondary (maybe optional?) search field for using another search engine isn't such a bad idea, in my opinion it is an immediate and logical solution.

**Comment by psimyn** [comment]
@Arandhras they are editable - could be whatever you wanted. And if you just type a search it uses the default search engine (same as current)

![shortsearch](https://cloud.githubusercontent.com/assets/1731922/13033838/b5796ace-d378-11e5-851d-45a3101e8633.gif)

@SJ-Diamond that is a good point, having 2 text fields could be pretty handy

**Comment by Arandhras** [comment]
@psimyn That is awesome, thanks for the clarification!

**Comment by SJ-Diamond** [comment]
Exactly that is what i wanted to say, sorry if i made myself not clear the very first time. But it is important that you are able to "lock" the search engine, so if you switch engines in the main field or the secondary one, that your second choice is kept instead of overwritten (so you have 2 search engines in the UI active instead of one).

**Comment by bradleyrichter** [comment]
Proposed UI for managing search engines, and also quick-type shortcuts. I would like to avoid adding a second search box since we will aim to have the most powerful and easy to use combo-search bar. Please share feedback...I'm all ears.  :   )

(settings panel to manage search engines, and contextual help regarding slash commands)

![screen shot 2016-02-18 at 2 30 37 pm](https://cloud.githubusercontent.com/assets/13509546/13160433/452adeb6-d64c-11e5-9ad6-91e4bb9b377e.png)


(ignore the old UI skin, search UI is still relevant and planned for future work)
![screen shot 2016-02-18 at 2 34 48 pm](https://cloud.githubusercontent.com/assets/13509546/13160562/ebd3d63c-d64c-11e5-9c43-4a2b14b91067.png)

**Comment by SJ-Diamond** [comment]
So, even as optionally available feature a second search box is not wished? Too bad.

**Comment by bradleyrichter** [comment]
Yeah, the 2nd bar seems to have trended away in favor of more flexibility/functionality in the main bar in most browsers. I’ll keep my eye out for request volume though….thanks.

**Comment by SJ-Diamond** [comment]
That may be true, but still keep in mind that flexibility and also adding so called non famous features these days can bring you quite a lot of users when they discover Brave and find out that it supports their features.

**Comment by bradleyrichter** [comment]
I agree. And the early adopters have different requests/needs than the eventual mass market.

**Comment by SJ-Diamond** [comment]
I also would say the mass minimalism/simplicity users are not the main target group of Brave, as that kind of users would instantly label Brave as "Ads-Ware" because for that class of users ads are in general bad and they would most likely not understand the concept that there also can be more better kind of ads.

Delivering to power users instead means that they bring with them their own amount of users which help build Brave's audience, but for this you have to insert their toys. It is a simple calculation ;)

**Comment by luixxiul** [comment]
FYI: search shortcuts have been implemented with #2726, whose follow-up is #4238.

**Comment by Liunkae** [comment]
+1 from [this comment](https://github.com/brave/browser-laptop/issues/5368#issuecomment-258760365).

**Comment by bsclifton** [comment]
What functionality is not met by our current search shortcuts?  Can this issue be closed?
@bradleyrichter @luixxiul @bbondy

**Comment by bradleyrichter** [comment]
@bsclifton 

We can close but I'll monitor for requests for a second redundant search box ala Firefox style as explained by @SJ-Diamond .
