### ISSUE TITLE
You should be able to scroll while viewing a tab preview

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#4660]
- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10
  From support

```
Please make the following feature available:

Background scrolling when hovering over an inactive tab.

That way Brave is truly multi-tasking and multi-paneling.

Thank You!
```

zendesk ticket:
https://linkbubble.zendesk.com/agent/tickets/5700

**Comment by tgcandido** [comment]
I would like to take this one :smile:

**Comment by cezaraugusto** [comment]
great, thanks @tgcandido! 💥

**Comment by bsclifton** [comment]
@tgcandido let us know if you have any questions 😄

**Comment by fraed** [comment]
Just investigated the issue. For me the preview-tab works as expected. The user gets an tab preview about the current tab state including scroll position.
Allowing to scroll a preview tab requires to leave the preview open while moving the cursor over the preview tab page for scrolling. This state would be hard to exit from.
Anyway, if you have further suggestions how to solve the issue i would give it a try. Scrolling over the tab itself could work but i am not quite sure know if that is what a user expect.

**Comment by aparms** [comment]
I would like to work on this one, since it hasn't been fixed. I just need to know where to start? I was reading the source code at [apps/browser/tabs.js](https://github.com/brave/browser-laptop/blob/master/app/browser/tabs.js) And was wondering if the issue would be fixed inside there?
