### ISSUE TITLE
URL bar sometimes shows a part of domain

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4663]
**Describe the issue you encountered:** URL bar sometimes shows a part of domain in the history after the displayed URLs. I am not sure how to reproduce the issue.

![urlbar](https://cloud.githubusercontent.com/assets/3362943/19257365/f2cdfcda-8fa9-11e6-9d93-4dca543ce73c.gif)

**Expected behavior:** 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.4 while I think I've seen this since several versions

- Any related issues:

Setting a milestone for now.

**Comment by Sh1d0w** [comment]
@luixxiul I this is fixed here https://github.com/brave/browser-laptop/pull/5046

I saw this is caused when selected text is not properly cleared upon navigation or redirect.

Please test again when my PR gets merged :)
