### ISSUE TITLE
Citrix app is not working with Brave

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4664]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user in the field is having issue with Brave working with Citrix https://linkbubble.zendesk.com/agent/tickets/5314

**Expected behavior:**
If Chrome works reasonably well with Citrix, Brave should too.

**Comment by privatzee** [comment]
Hi, Alex. Is there a way that I can see those tickets? All I get is a login page with:

> Have you emailed us? Get a password
If you've communicated with our support staff through email previously, you're already registered. 
You probably don't have a password yet, though.

**Comment by alexwykoff** [comment]
We cannot provide access to zendesk as it often contains personally identifiable information.

However, this is what the user wrote which is safe to share:

> The citrix client does not load. I access the host site, click on my citrix app, and normally the citrix receiver client will load and then I can access my desired application, but the client will not load. I click on the app and nothing happens. I reinstalled the client thinking that it needed to “recognize” brave, but that didn’t work either.
> 
> I would like to migrate all our office computers to your browser. We use macs as workstations that access our remote hosted citrix server.
> 
> The above problem occurs when I access other vendors citrix servers as well.

**Comment by privatzee** [comment]
Thanks, Alex. It seems that only someone with the paid Citrix software can research this. 

Btw, I do notice that the ticket doesn't say that he deactivated the shields and tried again. It must be frustrating that users aren't told to do that before submitting a ticket or email.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/citrix-store-front-citrix-receiver/716
>For me, currently a very important issue that would help me make the move to BRAVE is that of being able to get Citrix Receiver to function properly. Within BRAVE, access to and log-onto Citrix Storefront works well. However, even with the installation of the most current Windows 10 Citrix Receiver, that "installation" is not recognized by the Citrix Storefront when running in BRAVE. No matter how many times I tell Citrix to retry or that it is already installed. Note that all works well within Firefox.
