### ISSUE TITLE
Dvorak users are having trouble with keyboard shortcuts

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4665]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has noticed problems with Cmd+C and Cmd+I on their MacBook.
https://linkbubble.zendesk.com/agent/tickets/5451

**Expected behavior:**
Shortcuts should work based on the value of the keys inputted.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Discovered on OS X
- Steps to reproduce:
  1. Switch keyboard mapping to Dvorak
  2. Attempt to copy a value with Cmd+C
  3. Check to see if the value was copied.

**Comment by Liunkae** [comment]
+1 from #7131 and #7142.

**Comment by luixxiul** [comment]
+1 https://community.brave.com/t/switch-tabs-bound-to-the-wrong-key-when-using-dvorak-layout-on-osx/2574?u=suguru

**Comment by gruen** [comment]
+1 

MacOS Dvorak (DQ-style) layout breaks some shortcuts. ⌘+C (⌘+V, +T, +W) works sometimes, but not others.

Keep up the good work!

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/dvorak-qwerty-keyboard-shortcut-support/26926/3
