### ISSUE TITLE
Pinned Tabs duplicate/clone when starting Brave

### ISSUE THREAD

**Issue by bmarz** [brave/browser-laptop#4671]
When opening Brave, the pinned tabs all have a clone or duplicate. Closing the duplicate closes both pinned tabs. Unpinning and repinning is the only remedy.

Expected behavior: pinned tabs do not multiply on their own every time Brave is restarted.

- Platform (Win7):

- Brave Version: 0.12.4

- Steps to reproduce:
    1. Pin 2 or more tabs
    2. Close Brave
    3. Open Brave

**Comment by charbelrami** [comment]
Closing as duplicated of #3039. Thanks
