### ISSUE TITLE
Not switching to new tab when mouse-wheel clicking from bookmark bar.

### ISSUE THREAD

**Issue by pgiambat** [brave/browser-laptop#4672]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Mouse wheel click button on bookmark bar opens link in new tab when 'Switch to new tabs immediately' is turned on, but, the browser doesn't switch to it. If you right-mouse-click it then select 'Open Link in New Tab' the browser does indeed switch to the newly opened tab.

**Expected behavior:**
Clicked link opening in a new tab (which it does) and the browser to switch to it.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win 7
- Brave Version:
  Brave: 0.12.4
  Electron: 1.4.12
  libchromiumcontent: 53.0.2785.143
  V8: 5.3.332.47
  Node.js: 6.5.0
- Steps to reproduce:
  With bookmark bar enabled with several bookmarks, mouse-scroll-wheel click a bookmark.
  A new tab does indeed spawn, however, the browser does not switch to it. 
  When I Left-mouse-click the newly spawned tab the browser does switch to it. 

**Note** - If I right-mouse-click the bookmark in the bookmark bar and select 'Open Link in New Tab' the browser does indeed switch to the newly opened tab.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/should-new-tab-be-switched-instantly-when-you-click-a-bookmark-on-bookmark-bar-with-the-middle-mouse-button/10116

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
