### ISSUE TITLE
Feature Request: Norton Family Extension Support

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#4675]
https://chrome.google.com/webstore/detail/norton-family/napjheenlliimoedooldaalpjfidlidp
From support

```
Do internet filters like Norton Family work with this browser?
```

https://linkbubble.zendesk.com/agent/tickets/5704

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-investigation-which-parental-control-profanity-filters-are-out-there-and-popular/10223

Let's continue to talk about the suggestions there 😄
