### ISSUE TITLE
Feature Request : Support importing bookmarks from Opera

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4676]
**Did you search for similar issues before submitting this one?**
Yes 

**Describe the issue you encountered:**
A user from support has requested support for importing from Opera : https://linkbubble.zendesk.com/agent/tickets/5839

**Expected behavior:**
We should make it as easy as possible for users to switch to Brave.
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/add-functionality-to-bookmarks/26943?u=eljuno

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/995
