### ISSUE TITLE
Feature Request : crxMouse Extension

### ISSUE THREAD

**Issue by BenLeggiero** [brave/browser-laptop#4677]
**Did you search for similar issues before submitting this one?**
Yes

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo

**What do you like about the extension?**
Navigation, control, etc. with minimal mouse movement; speeds up browsing. Pairs well with Brave's goal of a faster browsing experience.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/add-crxmouse-extension/10248

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
