### ISSUE TITLE
Bookmarks from Edge not Importing

### ISSUE THREAD

**Issue by egwusko** [brave/browser-laptop#4679]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Bookmarks from MS Edge not importing, it says imported successfully but nothing shows 
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10
- Brave Version:
Brave - 0.12.4
Electron - 1.4.12
- Steps to reproduce:
    1. Import Browser Data
    2. Import Succeeded 
    3. Nothing was imported

- Screenshot if needed:

- Any related issues:
I have reinstalled it to no avail.

**Comment by darkdh** [comment]
Chrome  53.0.2785.143 cannot import bookmarks from Edge 38.14393.0.0 either.

**Comment by jamesray1** [comment]
Yes this occurs for me as well.

**Comment by luixxiul** [comment]
@jamesray1 do you experience the issue on the latest version?

**Comment by jamesray1** [comment]
It didn't work last night, but I tried a few hours ago and it imported then. I should note that a page on Reddit on the edge browser wasn't loading last night while Brave loaded the same page, so there may have been issues with Edge at the time.

**Comment by luixxiul** [comment]
OK I see!
