### ISSUE TITLE
Support optional Widevine for the ability to use Netflix

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#468]
Netflix will play on Safari without Silverlight or Flash, but it does not appear to be working on Brave. Might be user-agent related?

**Comment by bbondy** [comment]
Seems likely it would be easy to support different user agents per domain, probably best integrated into the SiteHacks module.

**Comment by bbondy** [comment]
For a quick test:
https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md#useragent

**Comment by m14t** [comment]
Here's a screen shot of what I see when attempting to view a video in Brave (without using any SiteHacks):

<img width="926" alt="screen shot 2016-02-10 at 7 10 56 pm" src="https://cloud.githubusercontent.com/assets/207950/12968689/15d73074-d02a-11e5-9345-c04350ca28dd.png">


The help center link, [https://help.netflix.com/support/27451](https://help.netflix.com/support/27451), suggests updating the [WideVine](http://www.widevine.com/) (a Google company for DRM video) component, by going to `chrome://components/`, but that url does not work in Brave.

**Comment by bbondy** [comment]
Played with user agent strings a bit:
iPad Safari: Asks you to get the app
Chrome / Windows UA: Asks you to get silverlight plugin
Firefox / Windows: Sends you to enable DRM page on Mozilla support: https://support.mozilla.org/en-US/kb/enable-drm

**Comment by bridiver** [comment]
@bbondy did you try desktop safari? It works for me and I don't have any plugins

**Comment by bbondy** [comment]
it asks for silverlight with a simple UA change. Interesting that it works for you on safari without it though.

**Comment by bbondy** [comment]
If there is some content that is not DRM'ed the Firefox UA w/ windows would give the HTML5 player that would work in those cases.

**Comment by vurstp** [comment]
Experiencing the same issue as m141

**Comment by gmurray79315** [comment]
I've gotten it to work on os x, Widevine and Flash on everything. 

line 102 - frame.js
`this.webview.setAttribute('plugins', 'true')`
This is what i used to make the webview always have plugins, after that its just a matter of adding in the proper plugins and app.commandLine.appendSwitch.

I also for safe measures added 
`plugins: true`
to appStore.js lines 124 and 215

If you'd like to see what i did for my app.commandLine i'd be happy to share :)

**Comment by bridiver** [comment]
Thanks @MegaUber! I think the issue around Widevine is distribution. I believe it works if you already have it installed (with Chrome), but if not I think it has to be manually installed right now. I know Widevine is free to use, but we need to be sure that we won't be liable for distribution license fees (which can likely be avoided by downloading on install vs bundling). Do you want to submit a PR?

**Comment by MegaUber** [comment]
Here is a link to a gist i put together that might or might not help if i did this right lol
and I'm sorry I'm kind of new to actually well sharing on github, what is PR?

[Widevine && PepperFlash](https://gist.github.com/MegaUber/423970c2b39938dcf54037d51629d945)

**Comment by bbondy** [comment]
Very helpful, thanks @MegaUber !
Given the gist you posted I'm going to mark this as good first bug for now in case someone wants to turn it into a pull request.   We could do this task in parts.

**Comment by jneumann** [comment]
I just submitted a PR for this. [https://github.com/brave/browser-laptop/pull/1293](https://github.com/brave/browser-laptop/pull/1293)

**Comment by luixxiul** [comment]
Should this be closed or not yet?

**Comment by iangelov** [comment]
Still very much an issue. One could use the experimental Flash support, but that's clearly undesirable (I yearn for the day in which we could get rid of it for good).

**Comment by EuNlope** [comment]
I am Brazilian and I would like you to help me in this problem .. I can not in any way implement Widevine in browswer. My twitter @EuNlope

**Comment by EuNlope** [comment]
someone can send the code to add the Widevine plugin ..? I am unable to add it to your browser brave ...

**Comment by EuNlope** [comment]
What's wrong in the code?

app.commandLine.appendSwitch('widevine-cdm-path', '/AppData/brave/to/widevinecdmadapter.dll');
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.903');
let win = null;
app.on('ready', (Brave) => {
win = new BrowserWindow({
webPreferences: {
Widevinecdm: true
}
});
});

**Comment by EuNlope** [comment]
Alguém pode mandar a linha de código pra mim por gentileza? Someone can have the line of code for me please?

**Comment by mattapperson** [comment]
Still a major issue with amazon prime video too

**Comment by alexwykoff** [comment]
Netflix is #37 on Alexa's most popular site index and this is obviously a dealbreaker for many browser users.

**Comment by EuNlope** [comment]
I agree with you and further support plugin should already come by default or if it would be at the discretion of the user to choose whether or not the plugin is activated.

**Comment by EuNlope** [comment]
They decided whether or not to put the Widevine component in the next version or in future versions?

**Comment by bridiver** [comment]
there was some concern about licensing fees for distribution, but it appears that widevine is free to use without fees

**Comment by EuNlope** [comment]
Can you tell me how I can add it to the browser ..?

**Comment by bridiver** [comment]
there are some docs for electron https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md
not sure what release it's scheduled for, but we have plans for support

**Comment by EuNlope** [comment]
OK thank you.

**Comment by EuNlope** [comment]
Still do not intend to add Widevine to the browser?

**Comment by alexwykoff** [comment]
Barring some unforeseen catastrophe, it's "coming soon" :)
It's locked in I assure you, and I'll be all to happy to QA this feature!

**Comment by EuNlope** [comment]
Ok thanks, it is noteworthy that the Brave is on track, great browser ...

**Comment by bbondy** [comment]
First visit to Netflix:
<img width="785" alt="screenshot 2016-10-25 00 52 07" src="https://cloud.githubusercontent.com/assets/831718/19673419/952b1f50-9a4d-11e6-93a1-28a8fa4f6c0f.png">

After clicking on open preferences:
<img width="991" alt="screenshot 2016-10-25 00 52 36" src="https://cloud.githubusercontent.com/assets/831718/19673424/9a267ee6-9a4d-11e6-8156-7a07775314ec.png">

To install just click the switch.

Trying to view a vide on Netflix after that:
<img width="987" alt="screenshot 2016-10-25 00 53 26" src="https://cloud.githubusercontent.com/assets/831718/19673434/a739e640-9a4d-11e6-8f23-1930bd8ac9bb.png">

Working Netflix via Wideivne:
<img width="989" alt="screenshot 2016-10-25 00 53 58" src="https://cloud.githubusercontent.com/assets/831718/19673438/b01922da-9a4d-11e6-94a6-b392e75c8b7d.png">

**Comment by bbondy** [comment]
Redoing screenshot play by play w/ Windows:


**First encounter on Netflix:**
<img width="635" alt="screenshot 2016-10-25 01 02 07" src="https://cloud.githubusercontent.com/assets/831718/19673586/3bd0f518-9a4f-11e6-86cc-e3063c1a337f.png">

**After clicking on "Open Preferences":**
<img width="759" alt="screenshot 2016-10-25 01 02 34" src="https://cloud.githubusercontent.com/assets/831718/19673593/53b087ac-9a4f-11e6-9028-664032195248.png">


**After flicking the switch to on to install:**
<img width="763" alt="screenshot 2016-10-25 01 02 41" src="https://cloud.githubusercontent.com/assets/831718/19673598/5f84d5b0-9a4f-11e6-86fd-3acde37c8dfc.png">


**Next load on Netflix, per site allow:**
<img width="762" alt="screenshot 2016-10-25 01 04 08" src="https://cloud.githubusercontent.com/assets/831718/19673615/84c9a166-9a4f-11e6-9c6b-8e85e50b8068.png">


**After the per site allowed:**
<img width="760" alt="screenshot 2016-10-25 01 03 54" src="https://cloud.githubusercontent.com/assets/831718/19673622/94cfcb76-9a4f-11e6-9623-da0ef28dfb54.png">

**Comment by EuNlope** [comment]
At last brought this to the browser .. Let's see how it behaves with the adoption of this plugin.

**Comment by jaydson** [comment]
I'm running Brave 0.12.7 on Ubuntu 16.10 and I don't have the option "Enable Google Widevine support" on my Security panel.
Is Google Widevine available for Linux?
Well, as far as I can see, Linux users can't use Netflix on Brave yet.

**Comment by BrendanEich** [comment]
@jaydson we got the Google blobs for Win and Mac in time for 0.12.7 but Linux is different. @bbondy can say more, but should have it in next release.

**Comment by bbondy** [comment]
probably not next release but soon, and tracking it here:
https://github.com/brave/browser-laptop/issues/5282

**Comment by kirkins** [comment]
Any updates on this?

**Comment by bbondy** [comment]
This is working and will be shipped in the release next week.
@darkdh and @bsclifton are the heros of the work :)

**Comment by bsclifton** [comment]
@kirkins our Linux support is tracked with https://github.com/brave/browser-laptop/issues/5282 which I believe @posix4e is working on 😄
