### ISSUE TITLE
Add "hide sites if" options to Advanced Options Dialog

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4681]
As a user, I want the option to filter/minimize the amount of less important sites in my Brave Payments list. 

First option - "Hide sites with less than 1% usage"

This will reduce the total number of sites, and only show sites that have a high probability of receiving a vote on my reconciliation day.

**This option is ON by default.**

Second option - "Hide sites that I have disabled"

This will keep my list tidy by hiding each site that I have chosen not to include by flipping the include switch.

With this option enabled, the site should disappear from the list view 1 second after I flip the switch to "don't include". If I wish to change or review the sites I have disabled, I can return to advanced settings and change this option to OFF.

**This option is OFF by default.**

![image](https://cloud.githubusercontent.com/assets/13509546/19283727/cee2a3d6-8fa7-11e6-9688-9040c1eb6e5e.png)

**Comment by bradleyrichter** [comment]
CC @mrose17

**Comment by luixxiul** [comment]
Designed. How is this?

<img width="750" alt="screenshot 2016-12-11 0 21 27" src="https://cloud.githubusercontent.com/assets/3362943/21074251/cffab960-bf37-11e6-887e-5a6571b6b19f.png">

**Comment by bradleyrichter** [comment]
@luixxiul Looks good except for the drop down style needs the new style.

And, the switches at the right are implemented too?

**Comment by mrose17** [comment]
a few nits: 

- s/hide/Hide/g
- s/site that/sites that/

**Comment by bradleyrichter** [comment]
Actually, "Hide sites that I have disabled" has been moved out to the ledger list area.

![image](https://cloud.githubusercontent.com/assets/13509546/21076789/67364370-bee9-11e6-851b-31eb7bca86cc.png)

**Comment by bradleyrichter** [comment]
see https://github.com/brave/browser-laptop/pull/6101

**Comment by luixxiul** [comment]
OK, I updated.

<img width="741" alt="screenshot 2016-12-11 12 34 22" src="https://cloud.githubusercontent.com/assets/3362943/21077903/2dc3c198-bf9e-11e6-8224-f8cad68b01a5.png">

I just copied the switch as I'm not sure how to implement `prefKey` for it.

**Comment by luixxiul** [comment]
@bradleyrichter 
> Looks good except for the drop down style needs the new style.

It will be applied after #6084 is merged (the margin-bottom of the labels will be applied with https://github.com/brave/browser-laptop/pull/6047/commits/f8efaca8668bdfcff7da13f10e912b0a4b062ea4 of #6047).

**Comment by luixxiul** [comment]
Would someone help me to implement the switch?

I'm trying to hide sites with less than 1%. I added following the other switch in preferences.js:
````
<SettingCheckbox
 dataL10nId='minimumPercentage'
 prefKey={settings.MINIMUM_PERCENTAGE}
 settings={this.props.settings}
 onChangeSetting={this.props.onChangeSetting} />
````

In js/constants/appConfig:
````
advanced.minimum-percentage': false,
````

In js/constants/settings.js:
````
MINIMUM_PERCENTAGE: 'advanced.minimum-percentage',
````

**Comment by mrose17** [comment]
@luixxiul - the routine you want to look at in `app/ledger.js` is `synopsisNormalizer`.  look for this line

            if (pct[i] < 0) pct[i] = 0

underneath that line add these lines

            if (pct[i] <= minimumPercentage) {
              data = data.slice(0, i)
              break
            }

and that should do the trick... good luck!

**Comment by luixxiul** [comment]
@mrose17 thanks! I will check it out ;-)

**Comment by luixxiul** [comment]
I got `ReferenceError: minimumPercentage is not defined` error. I think it is too complex for me to solve this :-(

**Comment by luixxiul** [comment]
@mrose17 appreciated! I will create a PR for it :+1:

**Comment by luixxiul** [comment]
@mrose17 I created the PR. Would you please update the code? Thanks!

**Comment by luixxiul** [comment]
Merged in the master branch with this: https://github.com/brave/browser-laptop/commit/8ae8eb4aedfdf19936015427a4864315246c56da

**Comment by luixxiul** [comment]
not used for 0.12.15 build

**Comment by luixxiul** [comment]
Test plan:

Open about:preferences#payments
Click Advanced settings
Toggle the switch
Make sure the sites with less than 1% usage are hidden
