### ISSUE TITLE
Buttons to add bookmark / bookmark folder in about:bookmarks

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4684]
**Expected behavior:** On the left row of the restyled bookmark manager it should be possible to add a bookmark folder on the top level besides Bookmark toolbar and Other Bookmarks. For now you can just create one under Bookmark Toolbar.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/43c0100c617b289da846d218a231d7a837f35aa7

- Steps to reproduce:
    1. Open about:bookmarks
    2. Show the context menu on the left row
    3. Select "Add Folder"

- Screenshot if needed:

<img width="808" alt="screenshot 2016-10-12 5 10 38" src="https://cloud.githubusercontent.com/assets/3362943/19286849/4474fb02-903a-11e6-97cc-dafb3ac8d386.png">

- Any related issues:

**Comment by bsclifton** [comment]
From the original issue:
https://github.com/brave/browser-laptop/issues/4562

Here's the mockup image for the new about:bookmarks screen:
![image](https://cloud.githubusercontent.com/assets/13509546/19271170/3cb100ea-8f78-11e6-818a-e83e0d049c91.png)

**Comment by bsclifton** [comment]
@luixxiul I renamed the issue- did I understand it correctly? ex: having the folder with the + will solve this issue?

**Comment by luixxiul** [comment]
Also creating a folder directly from context menu like doing so on Windows Explorer would be nice;  by doing a right click a folder is created and you can change the title from "Untitled" at the same time. Is this clear?

**Comment by bsclifton** [comment]
@luixxiul great idea :smile:

**Comment by bsclifton** [comment]
Before I forget, here's the mockup (with icon) that @bradleyrichter had put together:
![image](https://cloud.githubusercontent.com/assets/13509546/19271170/3cb100ea-8f78-11e6-818a-e83e0d049c91.png)

**Comment by bsclifton** [comment]
@bradleyrichter there doesn't appear to be a font-awesome icon for new folder (they do have an open issue to add one, but it's been open for a while https://github.com/FortAwesome/Font-Awesome/issues/3752)

Do you have an SVG we can use for this? Also, I same with the star which has the + (in the title column).  Thanks :smile:

**Comment by bsclifton** [comment]
Awesome, just saw the icon as one of the SVGs in https://github.com/brave/browser-laptop/issues/4852

I'll use a temporary one for the time being
