### ISSUE TITLE
Pocket: Clicking Icon Does Nothing

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4686]
**Describe the issue you encountered:**
Clicking the Pocket Icon resulted in no login window.

**Expected behavior:**
Clicking the Pocket Icon should result in a login window, or a saved-url notification.

**Explanation:**
The [`showLoginWindow` method](https://github.com/jonathansampson/browser-laptop/blob/97642fcb92f9e48d9bce0e7b336b4c26aa44607b/app/extensions/niloccemoadcdkdjlinkgdfekeahmflj/2.1.3_0/app/scripts/background/auth.js#L14) fires a message to the extension. When the message is received, `window.open` is called. This call is suppressed.

I added a check for `isChrome()` to avoid calling `window.open`, as you'll see in the previous link.

- Platform: Windows 10
- Brave Version: 0.12.4

**Repro Steps:**
https://github.com/jonathansampson/browser-laptop/tree/ext_pocket

- Any related issues: #4687 #4689 #4692

**Comment by bridiver** [comment]
@jonathansampson are you sure it's trying to call `window.open`? If it is that's part of the problem because it should be calling `chrome.tabs.create` in the previous line

**Comment by darkdh** [comment]
I modified the auth.js to call `chrome.tabs.create` directly and it will open a login tab.

**Comment by darkdh** [comment]
isChrome requires `window.chrome` and `window.chrome.app`

**Comment by jonathansampson** [comment]
@bridiver @darkdh The method doesn't originally contain the `isChrome()` bit; I added that to avoid having to call `window.open`. Originally, the extension checks `isSafari()`, followed by `isEdge()`, followed by a fallback to `window.open`.

**Comment by bridiver** [comment]
I think Chrome must be passing that through as a user gesture somehow because it should be blocked otherwise
