### ISSUE TITLE
Extension API: chrome.tabs.remove

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4687]
https://developer.chrome.com/extensions/tabs#method-remove

Blocks #8327, #9330, #9531, #9654, #9828

**Comment by bridiver** [comment]
closed by https://github.com/brave/electron/commit/cca303487a7381c01abc29f38bab619aa07e9358

**Comment by jonathansampson** [comment]
This appears to have regressed; I'm unable to successfully close a tab in the following build:

 
Brave: 0.19.0 
rev: 2bd7726b6d6ea83f41fbebdfab6b4141f8a5a78b 
Muon: 4.2.6 
libchromiumcontent: 59.0.3071.109 
V8: 5.9.211.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.15063 
os.arch: x64

**Comment by jonathansampson** [comment]
This issue appears to impact LastPass 2FA tabs: #4687

**Comment by bridiver** [comment]
I think we stopped handling `close` in browser-laptop because nothing has changed in muon. The original change to fix the crash no longer makes sense with the changes we made in browser-laptop so I'll commit a workaround to browser-laptop and then update muon
