### ISSUE TITLE
Incompatible with IRS website

### ISSUE THREAD

**Issue by xiaohanzhu** [brave/browser-laptop#4688]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Go to 
https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online
click on apply for EIN
**Expected behavior:**
Should prompt a message about the details of the EIN requirement.  However on Brave, the sites was redirected to the following link:
https://www.irs.gov/static_assets/error/RUP404.html
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.12.4
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/incompatible-with-irs-website/10203

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
