### ISSUE TITLE
Spell checking underlines words correctly spelled in other languages than English

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4697]
**Describe the issue you encountered:** Spell checking does not work correctly for Japanese language. It underlines the words which are corrrectly spelled.

On twitter.com,

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19296538/58a6cfd2-9077-11e6-8a23-7701518e4d6b.png)

Yet the underline is gone after pasting a URL

![clipboard02](https://cloud.githubusercontent.com/assets/3362943/19296544/641bbfd0-9077-11e6-9a36-bace3fae4636.png)

**Expected behavior:** Spell checking should not underline words correctly spelled
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.4
- Any related issues:

**Comment by alexwykoff** [comment]
++ Polish https://community.brave.com/t/correcting-words/3678

Perhaps we can rename to non-English if it's all other languages @luixxiul ?

**Comment by luixxiul** [comment]
Agreed!

**Comment by luixxiul** [comment]
I haven't seen the issue for a long time.
