### ISSUE TITLE
feature suggestion: Lazy loading tabs/tab loading only when activated/previewed

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#470]
In my opinion this is also a very much needed session for advanced users who want to have open quite a lot of tabs in the browser.

Problem is Chromium is a memory eater so it makes sense to have an option which makes tabs only loaded into memory when actually clicking on them, or the opposite when a tab is longer time not in use that it is unloaded out of memory until being reactivated again with clicking on it.

Of course that makes only sense if there is some session management in the browser/tabs stay alive even if the browser was restarted.

**Comment by Arandhras** [comment]
I like the idea that the memory taken by the browser should be somehow limited in cases where the amount of total system RAM isn't that big (4 GB or less). To address this, it should be nice to specify a maximum amount of memory usable by the program.
When the user has many tabs open, the browser would "forget" about the oldest tabs open ("Most Recently Used" policy) -- this operation would only purge the HTML and media content from volatile memory, of course no session-dependent data should be destroyed.

**Comment by luixxiul** [comment]
Was fixed :-)

**Comment by bbondy** [comment]
btw @luixxiul pls attach commit if you notice this later and it's easily findable. If not that's ok :)
Also if you notice something we forget to add in the current milestone but is fixed pls add it there.   Current milestone will always be the smallest available.

**Comment by luixxiul** [comment]
I see, attached it! Please correct it if I picked up wrong one.

**Comment by bbondy** [comment]
++ thanks!
