### ISSUE TITLE
Pocket: Repair chrome.runtime.openOptionsPage

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4700]
**Describe the issue you encountered:**
Calling `chrome.runtime.openOptionsPage()` results in an exception:
```
Unchecked runtime.lastError while running runtime.openOptionsPage:
Could not create an options page.
```
See [this example](https://github.com/jonathansampson/browser-laptop/blob/16061b88391ed125154e75ef768bb2694ce2e6f0/app/extensions/niloccemoadcdkdjlinkgdfekeahmflj/2.1.3_0/app/scripts/background/background.js#L453).

**Expected behavior:**
Calling `chrome.runtime.openOptionsPage()` results in a new tab opening to the extensions options page, as provided in the manifest.json.

**Platform:** Windows 10
**Brave Version:** 0.12.4

**Any related issues:**

**Comment by darkdh** [comment]
closed by https://github.com/brave/electron/commit/00f372387e6b4602588907cdbdea6a93b77dd9bf
