### ISSUE TITLE
Monthly budget dropped from $10 to $5 without user action

### ISSUE THREAD

**Issue by Aeyoun** [brave/browser-laptop#4703]
I’ve set and left my monthly budget at $10. However, when I opened about:preferences#payments today I found that it had dropped back to the default $5 amount. My account has enough funds to continue at $10 for several months. I’ve set it back up to $10 and restarted Brave, and the option seem to stick at $10 now.

I have no idea what triggered the bug, but it should probably be investigated.

Brave v0.12.4-dev on Fedora 24, 64-bit, etc, etc.

**Comment by Aeyoun** [comment]
Oh, never mind. I haven’t restarted Brave since reporting this bug and confirming that it was $10 after restart. I just reopened about:preferences#payments now and found it was once again back at $5.

**Comment by mrose17** [comment]
@Aeyoun - sorry for the delay in getting back to you on this. is there an issue? thanks!

**Comment by mrose17** [comment]
closed due to lack of response.

**Comment by Aeyoun** [comment]
You waited two weeks to reply, but closes it after two days with no response? … right. The problem persists as described above. Changing the monthly payment to $10 reverts to $5 by itself.

**Comment by mrose17** [comment]
sorry about that. i can't reproduce it.

**Comment by mrose17** [comment]
also, sorry about the short reply. (-;

one reason for the 20 day delay is i spent 3 different attempts trying to reproduce it, thinking that if i just left the browser running and checked that page every so often, i'd see something.

no such luck.
