### ISSUE TITLE
Payment Button mouse over barely noticeable 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4708]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Payment Button mouse over barely noticeable 

**Expected behavior:**
Keep the button color same across all pages. 
- Platform (Win7, 8, 10? macOS? Linux distro?): 
  Windows 10 x64
- Brave Version:
  0.12.5 Preview 1
- Steps to reproduce:
  1. Open payments page, Advance settings button mouse over is not noticeable
  2. Open Advance settings modal. Done button mouse over is barely noticeable
- Screenshot if needed:
- Any related issues:

cc: @jkup @bradleyrichter

**Comment by bbondy** [comment]
moving to 0.12.6

**Comment by jkup** [comment]
@srirambv the mouse cursor changes to pointer on these buttons though, right? Is this issue just that there isn't a noticeable color change? If so, maybe @bradleyrichter can weigh in?

**Comment by srirambv** [comment]
@jkup  the mouse cursor changes but the on hover color change is not clearly noticeable. Keeping the all the button standardized(Orange button with on hover border) across about pages seems good to me. This way there will be uniformity across about pages.

**Comment by jkup** [comment]
@bradleyrichter do you still have your original spec for how all buttons are supposed to look? If so, could you upload it here when you get a chance? Thanks!

**Comment by bradleyrichter** [comment]
@jkup 

![image](https://cloud.githubusercontent.com/assets/13509546/19542959/f4be81fc-9627-11e6-9ecf-90809ab7c4ca.png)

**Comment by jkup** [comment]
@bradleyrichter thank you!

**Comment by luixxiul** [comment]
@bradleyrichter Aren't labels of three `*Dis` buttons too light?

**Comment by bradleyrichter** [comment]
@luixxiul We can adjust the total button opacity if legibility is a problem.

**Comment by jkup** [comment]
@bradleyrichter will https://github.com/brave/browser-laptop/pull/5916 fix this issue as well?

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5916#issue-192396427
