### ISSUE TITLE
[SUGGESTION] boot time decreased.

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#4709]
**Did you search for similar issues before submitting this one?**  No 

**Describe the issue you encountered:**   By double-clicking to open the browser then I notice a little "slow" for the same fully charge, and compare with their "competitors" it is clear that it has a "disadvantage" in this regard.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Win10 64 bits

- Brave Version:  0.12.4
- Electron Version:  1.4.12

**Comment by luixxiul** [comment]
Same as #488?

**Comment by EuNlope** [comment]
Yes, not in the same words but the same problem ..
