### ISSUE TITLE
suggestion: animate the lionhead until first clicked, present intro

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#4710]
Since the lionhead encapsulates what is different about Brave, call attention to it by making it glowing/pulsing or whatever. I mention this because apparently a lot of people submit trouble reports without first having turned off shields to see if that helps. 

It's understandable that lots of users might think that everything is automatic in Brave and they don't have to manually intervene when a website breaks. When they see the lionhead animated, think "what's that?", then click it to see what happens they can then be presented with a one time textbox that says simply: "If you encounter any problems with a website, turn the Shields down to see if that solves the problem". It's a mini-tutorial for those who will jump in without reading a readme (like me).

**Comment by jonathansampson** [comment]
This is a good suggestion, and something we considered. Ultimately we decided to bring attention to the Shields by adding the total number of resources blocked. We may adjust this further in future releases, but for the time being, we feel this addresses the root issue 🙂

![image](https://cloud.githubusercontent.com/assets/815158/26290301/240d62b0-3e6c-11e7-96c9-d792234d5040.png)
