### ISSUE TITLE
Selected text is indicated in address bar but not copyable

### ISSUE THREAD

**Issue by stevebscott** [brave/browser-laptop#4712]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Using iPad Pro Smart Keyboard, Cmd + c (copy) fails to select URL from address bar when URL is first highlighted. Only by deselecting and then reselecting is it made copyable.

**Expected behavior:**
Either the text should not be indicated as highlighted, or the text is highlighted and cmd + c keyboard shortcut copies it to the clipboard.

- Platform (Win7, 8, 10? macOS? Linux distro?): iOS 10

- Brave Version: 1.2.16 (16.09.30.10)

- Steps to reproduce:
    1. Tap on current URL in the address bar.
    2. Use keyboard shortcut (cmd + c) to try to copy the selected text.
    3. Pasting text then fails.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
You can use an iPad Pro keyboard for macOS?

**Comment by Liunkae** [comment]
@stevebscott: I assume you are using Brave for iOS. It has a separate issue tracking system here: https://github.com/brave/browser-ios/issues

**Comment by stevebscott** [comment]
@Liunkae thanks. I will repost there.
