### ISSUE TITLE
Image doesn't appear

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4716]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Image doesn't appear. It's not ads

**Expected behavior:**

See the image

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 64

- Brave Version: Dev Channel Beta v0.12.5dev-Preview1

- Steps to reproduce:
    1. Open https://blog.signatura.co/introducing-signatura-document-signing-on-the-blockchain-a662d6b4b0d8#.jxo89i57s

- Screenshot if needed:

![captura de tela de 2016-10-12 12-06-25](https://cloud.githubusercontent.com/assets/1178856/19315575/98587412-9074-11e6-846e-b5650f4268da.png)

**Comment by neeklamy** [comment]
Have you got _Fingerprinting Protection_ turned on? I see the image with shields up, showing Brave ads, and blocking 3rd-party cookies, but if I turn fingerprint protection on, it doesn’t show.

**Comment by bitcoinuser** [comment]
Hi @neeklamy 

I disabled Fingerprinting protection and now I see the image.

Thanks

**Comment by neeklamy** [comment]
Glad I could help, @bitcoinuser.

According to jkup, there used to be a warning about this:

> IIRC fingerprint protection used to warn that it may break some sites but doesn't now. Is that correct?

From #3682. Also related #2987 and #2965
