### ISSUE TITLE
WebSocket Secure (wss) bug

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#4717]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
Please see original report at #4694
- Platform (Win7 x64
- Brave Version:
  0.12.4
- Steps to reproduce:
  1. I opened a free Asana.com acct
  2. created new project, entered some dummy data
  3. all was fine until I let it sit for many minutes, 20 or so
  4. 'disconnect' errors appeared in browser window
  5. series of wss console errors ensue
  6. after more sitting, page crashes
- Screenshot if needed:

![brave asana wss](https://cloud.githubusercontent.com/assets/22591438/19316817/e9239fe2-9070-11e6-8a77-bdd34c76be84.jpg)

![brave wss errors](https://cloud.githubusercontent.com/assets/22591438/19316837/fa6b5998-9070-11e6-82e9-b71a7985735c.jpg)

![brave asana crash](https://cloud.githubusercontent.com/assets/22591438/19317547/5ed8cc42-9073-11e6-8cf9-9094b751aaf5.JPG)
- Any related issues:

the original report #4694 says that Chrome works okay there

**Comment by privatzee** [comment]
Note: the bundle.js is from utility package Lodash

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/websocket-secure-wss-bug/10114

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
