### ISSUE TITLE
Ledger recovery should be aware of network status and give appropriate errors when the connection is down.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4720]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While trying to recover a wallet, my network connection went down.  The error message from the system indicated that my keys were somehow incorrect. Once the network connection was restored, the keys worked without issue. 

**Expected behavior:**
The system should display appropriate error messages. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.12.5
- Steps to reproduce:
  1. Generate recovery keys
  2. Remove your ~brave folder and create a new wallet
  3. Open the recovery dialog, enter keys but do not submit the form
  4. Disable your network connection (or just happen to have a really poor one)
  5. Submit the form
  6. Observe the error message
- Screenshot if needed:
  <img width="712" alt="screen shot 2016-10-13 at 1 01 40 am" src="https://cloud.githubusercontent.com/assets/1434040/19320648/b55eb466-90e4-11e6-860b-75008b8d964e.png">
- Any related issues:

## Test Plan
  1. Go to Preferences > Payments
  2. Click Advanced Settings
  3. Click Recover Your Wallet
  4. Try to recover with the wrong keys
  5. You should see the "Recovery Failed" overlay
  6. Repeat steps 1-3
  7. Turn off network connection
  8. Try to recover with right or wrong keys
  9. You should see the "Network Error" overlay

**Comment by bsclifton** [comment]
Groundwork laid by @mrose17 w/ https://github.com/brave/browser-laptop/pull/5924

This is ready for the UI work.  Marking as 0.13.1 and assigning over to @jkup

**Comment by jkup** [comment]
@bsclifton did you mean to close this?

**Comment by mrose17** [comment]
it shouldn't have been closed. i did the first part, but now it's up to you!!!

**Comment by bsclifton** [comment]
Looks like the self-closing keywords from the commit unintentionally closed it :smile: 
```
...
For the person who **fixes #4720** - when...
```

**Comment by mrose17** [comment]
rather amusing...

**Comment by mrose17** [comment]
@bsclifton - can we close this one too?

**Comment by luixxiul** [comment]
@mrose17 I don't think so. #6047 focuses on the UI change.

**Comment by jkup** [comment]
@mrose17 reading through your commit I'm still not sure how I can differentiate between a network error and a failed recovery (bad keys). Can you help me understand how to do this UI work?

Thanks!!

**Comment by bsclifton** [comment]
@mrose17 looks like @jkup needs some more info (he should be back next week)

> I'm still not sure how I can differentiate between a network error and a failed recovery (bad keys). Can you help me understand how to do this UI work?

**Comment by mrose17** [comment]
here is the answer: look at `ledgerInfo.error.err` if it is a STRING, then there is a data input or server error; if it is an object, e.g., `{ errorCode: -109 }` then there is a network error.

**Comment by luixxiul** [comment]
It seems this is not fixed. I followed the same steps after restarting the browser but it did not work either

**Comment by alexwykoff** [comment]
In my case, the breakage was a bit nuanced. 
Without a network connection, the UI did nothing. No warning, no error, it just took my clicks and walked away.

When the network connection was restored, somewhere in the middle of my machine-gunning the control, the recovery keys were accepted.

cc @bsclifton

**Comment by bbondy** [comment]
Moved to 0.13.3

**Comment by bsclifton** [comment]
Removing milestone for now and putting on backlog- we're tracking in Asana. Will update once we have prioritized

**Comment by zentagonist** [comment]
Closing at @mrose17 direction.
