### ISSUE TITLE
URL suggestions put too much weight on recent clicks

### ISSUE THREAD

**Issue by zoof** [brave/browser-laptop#4725]
**Did you search for similar issues before submitting this one?**

I did but was unable to find anything similar.

**Describe the issue you encountered:**

For sites that I visit frequently, newly clicked links override the highly frequented base URL in suggestions.

**Expected behavior:**

Top suggestion should be the highly frequented base URL.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Debian Jessie

- Brave Version:

0.11.6

- Steps to reproduce:
    1. Go to a site many times.
    2. Click on a link
    3. Link is top suggestion.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I think this is a dupe of https://github.com/brave/browser-laptop/issues/3049 ? @aekeus introduced a visit count which adds some weight with decay there.

**Comment by zoof** [comment]
Yes -- thank you.
