### ISSUE TITLE
Extension request: The Great Suspender

### ISSUE THREAD

**Issue by neomodern** [brave/browser-laptop#4729]
[This addon](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) is fantastic for unloading tabs to reduce memory usage, I consider it essential to my workflow and would love to see it in Brave.

**Comment by bradleyrichter** [comment]
Thanks for the suggestion!

We are half way there and will expose more functionality similar to The Great Suspender in the near future.
