### ISSUE TITLE
Can't play back video on hulu.jp

### ISSUE THREAD

**Issue by wonderwarthog** [brave/browser-laptop#4732]
**Describe the issue you encountered:**
When trying to play back video on hulu.jp I get the error to install Flash first. In the discussions I read that Flash on Brave was click to play (?), but that option doesn't seem to be available.

**Expected behavior:**
At least offer the option to use/enable Flash on a per site basis.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  macOS Sierra (10.12)
- Brave Version:
  Brave: 0.12.4
  Electron: 1.4.12
  libchromiumcontent: 53.0.2785.143
  V8: 5.3.332.47
  Node.js: 6.5.0
  Update Channel: dev
- Steps to reproduce:
  1. Login to hulu.jp
  2. Play back any video
  3. Get an error
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
What kind of error is it? A screenshot would be appreciated.

**Comment by wonderwarthog** [comment]
Just the standard error you'd get if you hadn't Flash installed (Flash is installed on my system, btw).

![screen shot 2016-10-13 at 18 51 54](https://cloud.githubusercontent.com/assets/610340/19345887/9019b236-917b-11e6-85f6-c15efe9ba15a.png)

**Comment by luixxiul** [comment]
Please click the link "download" and see what happens. That notification message is triggered by brave intentionally

**Comment by luixxiul** [comment]
I cannot reproduce the issue (I watch videos there both on macOS and Windows)
