### ISSUE TITLE
Add multi-select deletion with arrow keys in about:history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4737]
**Describe the issue you encountered:** Add multi-select deletion with arrow keys in about:history. For now selecting with <kbd><kbd>Command</kbd> + <kbd>down</kbd></kbd> scrolls to the bottom, not selecting other entries.
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: 0.12.4
- Any related issues: #3949

**Comment by luixxiul** [comment]
You can select multiple entries with mouse pushing <kbd>Shift</kbd>, which is what should be enabled with arrow keys.

**Comment by bsclifton** [comment]
Removing this from the milestone; let's work with @bradleyrichter or @bbondy if we want to reassign it into a milestone
