### ISSUE TITLE
Long bookmark folder names should be truncated

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4739]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I realize that @srirambv's comment in https://github.com/brave/browser-laptop/pull/4690 is contrary to my opinion, but the downside of having folder names which are not truncated is that the bookmark names become oddly truncated then eventually are stacked below the folders.

**Expected behavior:**
It would seem that proportional columns make the most sense in this case if we must maintain columns. @bradleyrichter it may be worth revisiting this interaction and allow for a different method of selecting folders and shuffling bookmarks between them.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 and OS X.

- Brave Version:
0.12.5 Preview 2

- Steps to reproduce:
    1. Create a bookmark folder with an obnoxiously long name.
    2. Import a lot of bookmarks.

- Screenshot if needed:
<img width="1060" alt="screen shot 2016-10-13 at 7 33 54 pm" src="https://cloud.githubusercontent.com/assets/1434040/19347822/64368912-917d-11e6-9538-4bf71558ea9b.png">
<img width="1130" alt="screen shot 2016-10-13 at 6 58 30 pm" src="https://cloud.githubusercontent.com/assets/1434040/19347842/73e8f4c6-917d-11e6-9802-29121981242f.png">

- Any related issues:

**Comment by bradleyrichter** [comment]
Unless this will happen by accident, it's an edge case. So let's set a max width to 50% and no scrolling.
