### ISSUE TITLE
Security idea: No-Script like functionality

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#474]
As Brave is also including adblocking of annoying ads and tries to make the web that way a much more secure place, a No-Script like functionality would work in the same direction.

It would be great to be able to decide which script parts of a page are allowed to load.

**Comment by Arandhras** [comment]
I agree with this absolutely, NoScript is a must-have addon for me on Firefox, having something like it in Brave would be fantastic!

**Comment by diracdeltas** [comment]
Duplicate of #231
