### ISSUE TITLE
about:history multi-selection delete does not remove the entries selected

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4741]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Having selected multiple entries in about:history and attempting to delete them via the context menu, it appears as though other entries were deleted.

**Expected behavior:**
The selected entries should be deleted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X 

- Brave Version:
0.12.5 Preview2

- Steps to reproduce:
    1. Visit a lot of places
    2. Select a few in about:history using the multiselect feature (I also sorted the columns)
    3. Delete the selected items via the context menu 

- Screenshot if needed:
![multiselect_history](https://cloud.githubusercontent.com/assets/1434040/19350896/22967256-918c-11e6-95c2-191444d3aac2.gif)

- Any related issues:

**Comment by luixxiul** [comment]
If someone gets this please check this too: #4738 which seems to be similar with this.

**Comment by bsclifton** [comment]
@darkdh and I tried to reproduce, unsuccessfully. I wonder if this symptom is the same as https://github.com/brave/browser-laptop/issues/4224 ?
