### ISSUE TITLE
Nested bookmark folders go off screen in bookmarks toolbar

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4745]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When user has a large amount of nested bookmark folders, they'll end up going off screen instead of being able to show all the folders.

**Expected behavior:**
Folders should show (see screenshot below, with Chrome behavior)
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  All
- Steps to reproduce:
  1. Go to about:bookmarks
  2. Create 20 - 30 folders and nest them all
  3. Ensure bookmarks toolbar is being shown
  4. Open the folder using bookmarks toolbar 
- Screenshot if needed:

**screenshot from 0.12.5**
<img width="1131" alt="screen shot 2016-10-13 at 7 01 37 pm" src="https://cloud.githubusercontent.com/assets/1434040/19346887/526d1034-9178-11e6-882c-c93df85c15d1.png">

**screenshot showing Brave (top) vs Chrome (bottom) behavior** (thanks @srirambv!)
![image](https://cloud.githubusercontent.com/assets/17010094/19477650/ce7c0a1c-955c-11e6-84aa-832f52152546.png)
- Any related issues:
  https://github.com/brave/browser-laptop/issues/1187

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/8891

**Comment by srirambv** [comment]
+1 from #10388

**Comment by LaurenWags** [comment]
+1 from me

**Comment by alexwykoff** [comment]
@bsclifton what is blocking this? Does it depend on any DPI fixes?

**Comment by bsclifton** [comment]
@alexwykoff no blockers

In order to solve this, we would need to convert the menus from React controls (HTML/JavaScript) to native menu items (ex: uses win32 / gtk / cocoa). We've done this with a few menus (ex: the popup menu that shows when you right click a page), but not anything that has an icon.  We would need to convert the favicons into `NativeImage` format (something I'm not sure that we have done yet in our code)

**Comment by bsclifton** [comment]
@alexwykoff related tracking issue: Convert React ContextMenu items to native context menu #8641

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/bug-report-drop-down-menu/11781/2

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/cant-see-the-rest-of-bookmark-when-the-screen-ends/14146?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmark-displays-folder-content-off-screen/14650?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmark-bug-unseen-here/16440?u=eljuno

>The bookmarks is not showing properly on the right side

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/multi-tier-bookmarks-go-outside-browser-window-and-are-inaccessible/21852

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/irpolarbear/status/1012076883066974208

Fixed with brave-core, @bsclifton @srirambv ?

**Comment by srirambv** [comment]
@eljuno Yes this will be fixed by brave-core. @bsclifton this issue can be closed as its out-of-box fix on brave-core.

**Comment by bsclifton** [comment]
@JamborJan the solution is Brave Core which you can find here:
https://github.com/brave/brave-browser

Unfortunately, there are no public binaries currently available... but we should have some available within the next month or two. This issue is closed as `wontfix` because we will not be fixing it with our current codebase (which is based on Muon, a fork of Electron)

**Comment by bsclifton** [comment]
Here's a screenshot from the current live build of Brave Core where the issue is fixed:
![screen shot 2018-07-01 at 10 32 40 pm](https://user-images.githubusercontent.com/4733304/42146756-c2a09ce2-7d7e-11e8-88c8-8addd40b499d.png)
