### ISSUE TITLE
HackerOne report: punycode not properly displayed when setting homepage

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4747]
https://hackerone.com/reports/175286
verified on OS X 0.12.5

# Steps To Reproduce:
1. In browser preferences add homepage with IDN `http://ebаy.com/`
2. now close and open browser again
3. you can see it's redirect to http://xn--eby-7cd.com/

# Expected behavior
When you enter the browser homepage in prefs, it should be displayed as `http://xn--eby-7cd.com/` instead of `http://ebаy.com/`

**Comment by bbondy** [comment]
@diracdeltas would you mind taking?
