### ISSUE TITLE
Amazon S3 upload files causes crash

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#475]
STR:
1. log into amazon S3 console, select a bucket
2. click the "upload" button
3. click "add files"
 
Brave crashes. I made a fiddle with the S3 "add files" element but that doesn't cause a crash. https://jsfiddle.net/tu2xxc9q/

**Comment by diracdeltas** [comment]
Same thing happens on github when i try to select an image to upload in a comment

**Comment by bbondy** [comment]
All 3 of those things worked for me.

**Comment by bridiver** [comment]
https://github.com/brave/electron/commit/18b1f247d7464f9f434befe6de9244af80b71245 should fix any file picker crashes
