### ISSUE TITLE
validate that devServerPort is numeric

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4753]
in https://github.com/brave/browser-laptop/blob/aafa62a373b9bec7b669ced88dd36304410206e8/app/extensions/brave/js/about.js, devServerPort is untrusted input, so it should be validated.

ex: any page can do window.open("chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-flash.html?devServerPort=foo@test.com/")

doesn't directly cause an issue thanks to CSP, it seems

thanks to Tavis Ormandy for the report

**Comment by bridiver** [comment]
I couldn't get it to load test.com even when I altered the CSP to allow it. Adding the username password made the entry invalid and it didn't work with just test.com, but calling `parseInt` on it seems like a good idea anyway

**Comment by diracdeltas** [comment]
fixed by https://github.com/brave/browser-laptop/commit/d0a361a8edb3fe24ac0bfaabe154157f584f7f1e
