### ISSUE TITLE
Clarify enabling Flash on Brave

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#4754]
This relates a bit to #2659 but it wasn't immediately clear to me that I needed to go install something for the switch control to stop being disabled (I had to look in the code!)

Maybe we could add some text to tell the user: In order to enable Flash you must first go and install it on your computer.

I know that it says it requires Pepper Flash to be installed but it just didn't click for me that the reason I couldn't click it was because I needed to go grab something.

@bradleyrichter thoughts?

![screen shot 2016-10-13 at 2 58 28 pm](https://cloud.githubusercontent.com/assets/490294/19368650/ec1d95c8-9155-11e6-9f2f-07b4fdb82f57.png)

**Comment by bradleyrichter** [comment]
@jkup 

Perhaps we could lay out the setting differently to encourage installation=, then a restart, and then enabling the switch?

![image](https://cloud.githubusercontent.com/assets/13509546/19369450/4ee31a44-915a-11e6-89ba-951fcb7e957b.png)

**Comment by jkup** [comment]
Yeah I think something like that is way better. Just to be like click here and install a thing and *then* you can enable flash!

**Comment by bradleyrichter** [comment]
@diracdeltas was the original implementor of this in prefs.

Yan - can we change it to the approach above?

**Comment by diracdeltas** [comment]
yeah that wording is better. also, whoever takes this should also link to https://github.com/brave/browser-laptop/wiki/Flash-Support-Deprecation-Proposal#troubleshooting-flash-issues

**Comment by CliqueBait** [comment]
@diracdeltas I've been using Brave for months and had a couple of brief attempts to get Flash working for me but to no avail... until I tried the steps on the issues wiki you linked on the 14 Oct. Now it just works.

I strongly recommend that that link be displayed more prominently somewhere so that more people know about it.

Ubuntu 16.10
Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by tecromatica** [comment]
Why not check to see if flash is installed and configure it for the user?

**Comment by ZenMilan** [comment]
really the issue is annoying on Mac Sierra 10.13 I can't enable flash even after installing proper pepper version. help me out please.
