### ISSUE TITLE
Can not login to Twitter with 3rd party cookies blocked

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#4758]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** I am unable to login to Twitter at the following URL (or the Twitter homepage) with the global shield options set to block 3rd party cookies. Changing the site specific shield option has no effect.

URL: https://twitter.com/login/

**Expected behavior:** I should be able to login to Twitter without having to globally switch off global blocking of 3rd party cookies.
- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Linux (Ubuntu 16.04 LTS)
- Brave Version: 0.12.4
- Steps to reproduce:
  1. Ensure global shield settings are set to block 3rd party cookies.
  2. Attempt to login at https://twitter.com/login/ or the Twitter homepage.
  3. Note that the login fails with no validation error and you are redirected to: https://twitter.com/login/error?username_or_email=twitter_username

**Comment by charbelrami** [comment]
Reproduced on Win 10 64-bit, Brave v0.12.5dev-Preview2

**Comment by bcdady** [comment]
Symptoms reproduced on Win 7 64-bit in Brave 0.12.8

**Comment by DivineOmega** [comment]
Unfortunately, this issue is still present in Brave 0.12.14.

**Comment by jonathansampson** [comment]
Reported here as well: https://github.com/brave/browser-laptop/issues/4877

Good news is I no longer repro, as of Preview Build 7 of Brave 0.13.0. If you would like to help test Preview Builds of Brave, [please see these instructions](https://community.brave.com/t/volunteers-needed-beta-test-of-0-13-0-preview-7/459).

**Comment by DivineOmega** [comment]
I can confirm this seems to be fixed in 0.13.0. Thanks all! :)

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
