### ISSUE TITLE
Evernote: chrome.browserAction.onClicked.hasListener is not a function

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4759]
**Describe the issue you encountered:**
Evernote is unable to determine if a listener has already been registered.

**Expected behavior:**
Evernote should be able to determine if a listener has already been registered.

**Platform:** Windows 10
**Brave Version:** 0.12.5

**Any related issues:** #4755

**Comment by jonathansampson** [comment]
Currently working around this absence in Evernote by calling `chrome.browserAction.onClicked.removeListener` first, ensuring it won't be added twice.

**Comment by bsclifton** [comment]
I think it's fair to say we won't be implementing this. We'll get this for free when switching over to Brave Core. Marking as `wontfix` since the fix won't happen in browser-laptop
