### ISSUE TITLE
soundcloud doesn't load

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#476]
soundcloud.com just shows "Sorry! Something went wrong
Is your network connection unstable or browser outdated?"

**Comment by bbondy** [comment]
Do you have to be outdated? The main site logged off loads for me.
Music on that page also works for me.

**Comment by diracdeltas** [comment]
I'm on the latest release. It's weird because Soundcloud was working for me at some point.

**Comment by diracdeltas** [comment]
I just closed the tab and loaded it again, now it works. hmm

**Comment by bbondy** [comment]
Try disabling our added filters next time it happens without closing to see if that helps.

**Comment by luixxiul** [comment]
This should be fixed, closing.
