### ISSUE TITLE
Extension API: chrome.windows.onFocusChanged

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4760]
https://developer.chrome.com/extensions/windows#event-onFocusChanged

- [ ] chrome.windows.onFocusChanged.addListener(listener)

An _addListener_ method exists, but does not appear to call the handler.

- [ ] chrome.windows.onFocusChanged.removeListener(listener)
- [ ] chrome.windows.onFocusChanged.hasListener(listener)

**Comment by jonathansampson** [comment]
Blocks #8327

**Comment by kspearrin** [comment]
Any priority or timeline behind this issue being resolved?

**Comment by jonathansampson** [comment]
@kspearrin We merged a few commits that added support. Just need to build and test one last time to confirm that all is working properly.

Should be able to close in a few hours (assuming all goes as planned).

**Comment by kspearrin** [comment]
Any update @jonathansampson?

**Comment by jonathansampson** [comment]
Closed by https://github.com/brave/muon/pull/180

**Comment by jonathansampson** [comment]
Reopening as _hasListener_ and _removeListener_ should also be supported.

**Comment by bsclifton** [comment]
removing from 0.15.300

@jonathansampson @cezaraugusto does this affect the Bitwarden extension? Cezar, I saw you merged the enabling of Bitwarden in the UI today... did you get a chance to test?

**Comment by kspearrin** [comment]
@bsclifton bitwarden does not use `removeListener` or `removeListener` _directly_, so it should not be a problem unless it is indirectly invoked by something else.

**Comment by jonathansampson** [comment]
I'm going to close this for now, since our support matches the Chrome documentation. If there appears a need to re-open in the future (for hasListener, and removeListener) we can re-open.
