### ISSUE TITLE
URL containing only numbers is redirected

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4761]
**Describe the issue you encountered:** URL containing only numbers is redirected to a wrong URL. 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.4
- Steps to reproduce:
  1. Input `5.1.1` on the URL bar and hit Enter key
  2. the URL is redirected to `http://5.1.0.1/`
- Any related issues:

#3317

**Comment by Liunkae** [comment]
@luixxiul What is the expected URL in this case? It seems that Brave thinks it's an IP address.

**Comment by luixxiul** [comment]
yeah I noticed this just now, still it should be 404 error with those numbers, instead of redirecting to 5.1.0.1.

**Comment by jonathansampson** [comment]
I think 5.1.1 should result in a search with the user's search engine instead of a 404.
