### ISSUE TITLE
Some Yahoo ads not being blocked on yahoo.co.jp

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4762]
The watch, bag, ....
<img width="623" alt="screenshot 2016-10-13 20 51 07" src="https://cloud.githubusercontent.com/assets/831718/19372093/d486a4c8-9186-11e6-9dec-1dee6986acab.png">

**Comment by bbondy** [comment]
Fixed, cc @luixxiul  for testing
<img width="929" alt="screenshot 2016-10-13 20 55 33" src="https://cloud.githubusercontent.com/assets/831718/19372169/6be83138-9187-11e6-8c40-d603b47ae39e.png">

**Comment by luixxiul** [comment]
Sweet! I will check it out soon :-D

**Comment by luixxiul** [comment]
Checked ;-)
