### ISSUE TITLE
Bookmarks Manager (about:bookmarks) is not tracking window size changes well

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4763]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing 0.12.5 Preview2 and associated fixes, it was noticed that if a user compresses and expands the window while on about:bookmarks, the elements on the page do not update in a fluid fashion.

**Expected behavior:**
As a user expands or contracts a window, elements should move smoothly and be up-to-date with the current window size.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on Windows 7 and OS X
- Brave Version:
  0.12.5 Preview2
- Steps to reproduce:
  1. Visit about:bookmarks
  2. Make the window narrower then wider.
- Screenshot if needed:
  ![bookmark_squeeze](https://cloud.githubusercontent.com/assets/1434040/19373297/85a4c582-91f5-11e6-9c31-c0a40a515ec6.gif)
- Any related issues:

**Comment by cezaraugusto** [comment]
tested with 0.12.4 and 0.12.5, couldn't reproduce using Ubuntu (not on VM)
