### ISSUE TITLE
Initial window size far too small 

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#477]
On Mac, after initial install and launching brave 0.7.11 the browser window is tiny. Make the default window size bigger.

**Comment by bbondy** [comment]
Welcome, and thanks for posting Asa! 
Similar but not matching ticket for reference: https://github.com/brave/browser-laptop/issues/146

**Comment by bbondy** [comment]
Anyone know what a good default is for this?

**Comment by asadotzler** [comment]
Ideally it'd be something like: 100% of the height (minus dock space) and wide enough to accommodate your home page content without horizontal scrolling or other layout bustage.

**Comment by elsehow** [comment]
is it possible to set a relative height/width of window in electron? (e.g. 100%)?

if not, 800x600 would be a better default than the current, tiny default
