### ISSUE TITLE
3D Secure payment stage issue on www.currys.co.uk

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#4770]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** I attempted to purchase an item from www.currys.co.uk today as was continually receiving an error (a generic technical error from the bank site) during the 3D secure part of the payment process (when the site redirect to the bank website to ask for further details, such as a password). Even after disabling global shield options for ad blocking, 3rd party cookie blocking and HTTPS Everywhere, the problem persisted.

I was able to put through the payment in Google Chrome immediately afterwards without any issue.

**Expected behavior:** I should be able to proceed with payment without any errors at the 3D secure stage.
- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Linux (Ubuntu 16.04)
- Brave Version: 0.12.3
- Steps to reproduce:
  1. Visit www.currys.co.uk
  2. Navigate to a product
  3. Add product to basket for delivery
  4. Proceed with guest checkout process
  5. Make payment (tested with VISA and Mastercard)
  6. Note error reported during 3DSecure process when directed to the bank website (error message likely varies dependant on bank)

**Comment by luixxiul** [comment]
I'm going to close this in favor of https://github.com/brave/browser-laptop/issues/1268 and https://github.com/brave/browser-laptop/issues/4594.

I personally think that some indicator that the 3rd party cookie is blocked and suggests enabling it (which is not always bad in terms of privacy) might fix the issue should be implemented 🤔
