### ISSUE TITLE
Add Bitwarden Password Manager

### ISSUE THREAD

**Issue by blindly** [brave/browser-laptop#4776]
## Original issue description
Open source cross platform cloud manager. There's an available chrome extension as well. 

https://bitwarden.com

## Issue status
We've been trying to get support for this in place and we've slipped several releases (not enough resources to support / troubleshoot). This feature can now be added by reverting this change (minus the Pinterest part)
https://github.com/brave/browser-laptop/commit/4cae9819e61ad276de57a0d6b2972da5159c41ce

**Comment by kspearrin** [comment]
Available on chrome web store here: https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb

**Comment by luixxiul** [comment]
QA blocked waiting for Muon update

**Comment by luixxiul** [comment]
The icon of the extension appears, still the extension does not seem to work yet on https://trac.torproject.org/projects/tor/login.

**Comment by srirambv** [comment]
Changed to no-qa-needed as the option has been disabled in settings

**Comment by ChillyHellion** [comment]
Hello, is this feature still in development, or has it been shelved?

**Comment by bsclifton** [comment]
Hi there @ChillyHellion - sorry it's taken a while to make progress here

Our beta channel (0.18.x) should have this available... we still needs to perform manual testing, but you can [try the latest beta build here](https://github.com/brave/browser-laptop/releases/tag/v0.18.5beta). Please note that our `beta` channel won't be as stable as our main channel (which is still marked as `dev`; we need to update the name to `stable` or similar)

Definitely not shelved 😄  Apologies it's taken longer than expected

**Comment by ChillyHellion** [comment]
Thanks bsclifon, and not a problem!  I just wanted to know if this was still in the works or if there was a technological roadblock preventing the implementation.  I appreciate the timely reply and I may take you up on testing out a beta build.  Bitwarden is one of my favorite web services and Bitwarden + Brave seems like a match made in heaven.

**Comment by bsclifton** [comment]
Moving this issue to 0.18.x to ensure we perform manual QA against Bitwarden 😄

**Comment by bsclifton** [comment]
Moving to 0.18.x hotfix because we ran into an issue https://github.com/brave/browser-laptop/issues/10130

**Comment by ChillyHellion** [comment]
@bsclifton I appreciate your persistence and the special interest you've taken in implementing this feature. You're doing a great job!

**Comment by bsclifton** [comment]
Tentatively moving to 0.19.x - we've got it disabled for now because of issues we ran into. We'll continue working away at those and plan to release with 0.19.x

**Comment by bsclifton** [comment]
For the specific open issues, please see:
- bitwarden issues while testing #10202
- bitwarden: Site autofill doesn't work #10140
- bitwarden extension header buttons are not clickable #9436

@jonathansampson @kspearrin when working in dev and testing compatibility, please try the revert mentioned in the original post above

**Comment by zentagonist** [comment]
I'll follow up on this one to establish status.

**Comment by ChillyHellion** [comment]
I was still having issues using Brave's implementation of Bitwarden - I could log in correctly but trying to access my fault just left the UI loading indefinitely.  I completely uninstalled Brave, cleared its AppData, and reinstalled Brave fresh using the latest stable build and noticed that Bitwarden is now removed from the list of extensions.  

Hopefully this is just temporary while bugs are worked out; Bitwarden support is the last thing keeping me from moving over from Firefox completely.  All of my other extensions (https anywhere, uBlock, disconnect, privacy badger) are things that Brave does natively.

**Comment by bsclifton** [comment]
@kspearrin @jonathansampson if you wanted to try the latest 0.19 release which has bitwarden enabled, please check out a release I built just for you 😄 
https://github.com/brave/browser-laptop/releases/tag/v0.19.3beta

This is part of the beta channel (which is something that is still a work in progress).  I'd recommend installing this version and then (after testing is complete) reverting back to the last stable version.  Coming soon (thanks to @darkdh) we'll have multiple channels installable at the same time

**Comment by bsclifton** [comment]
cc: @ChillyHellion in case you wanted to try the beta

**Comment by ChillyHellion** [comment]
Thanks, I'll have to check this out!

**Comment by ChillyHellion** [comment]
@bsclifton No issues with this build so far, this is wonderful!

**Comment by srirambv** [comment]
@kspearrin @jonathansampson  The login popup is unusually large on 0.19.x. Is this expected?
![image](https://user-images.githubusercontent.com/17010094/29819498-ebf9519a-8cb8-11e7-95fd-7a787a65dad1.png)

**Comment by kspearrin** [comment]
@srirambv What is your screen resolution?

**Comment by srirambv** [comment]
@kspearrin Its 1920x1080  with DPI set at 125%. The browser UI scale is default.

**Comment by kspearrin** [comment]
Yea, that doesn't look right. 0.19.x did have an increase in size for the popup window, but it's height is still < 700 px. Looks like a brave issue.

**Comment by jonathansampson** [comment]
@srirambv I suspect this is the _general_ issue with scaling. If you lower your scale to 100%, does it resolve the issue?

**Comment by bsclifton** [comment]
@srirambv I captured the high DPI issue with https://github.com/brave/browser-laptop/issues/10706.  I'll go ahead and close this issue out since it's merged to 0.19.x and there haven't been any other reports of issues

**Comment by ChillyHellion** [comment]
Did Bitwarden support make it into stable?  I was using Bitwarden without issue in the Brave Beta build linked farther up in this thread, but a recent update to that build leaves me unable to sign into Trello.  If I revert back to stable will I miss out on Bitwarden?

**Comment by bsclifton** [comment]
@ChillyHellion our beta which has bitwarden is nearing completion- we expect to release it this week 😄  Our last release of 0.19.x has most of the functionality, we're just ironing out bugs at this point

**Comment by ChillyHellion** [comment]
Excellent, thank you for the status update!

**Comment by ChillyHellion** [comment]
I received the update for 0.19.53 and can confirm that Bitwarden is included and working perfectly!  Thank you so much for all of your time and effort!

**Comment by bsclifton** [comment]
@ChillyHellion this is great! Thanks for the update (and enjoy! 😄 )

**Comment by Wyvern2** [comment]
It's great to have Bitwarden back with the latest update. However, it keeps loading its welcome Tab (with the video) each time I start Brave. Is there a way to stop this? I haven't asked Brave to display previous Tabs when it opens.

**Comment by bsclifton** [comment]
@Wyvern2 great catch- we noticed this with a few other extensions... @darkdh has prepared a fix which we should be able to include in our next version 😄
