### ISSUE TITLE
Changing language should prompt to restart

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4777]
Currently when you change the language in preferences it doesn't take effect right away but also doesn't prompt to restart for the change to take effect. We should prompt like we do for the other settings. 

STR:
1. Go to about:preferences
2. Change the default language

Actual results:
No Prompt to restart

Expected results:
Notification bar to restart like the one in advanced -> hardware acceleration

**Comment by luixxiul** [comment]
Note: the fix on this should close #4749 and #1705 too.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
