### ISSUE TITLE
Request: ScriptSafe Extension

### ISSUE THREAD

**Issue by gameb0y** [brave/browser-laptop#4781]
https://github.com/andryou/scriptsafe

or

https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf

![ce25d73a-7c31-11e6-9cc3-6404379e6826](https://cloud.githubusercontent.com/assets/19530450/19390955/55899c80-91df-11e6-9691-fcaac4bff6a9.png)

**Comment by luixxiul** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/4600#issuecomment-253826382
