### ISSUE TITLE
Allow "free-scrolling" similar to the Bookmarks Menu

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#4783]
From support: https://linkbubble.zendesk.com/agent/tickets/5595

> - Bookmarks Toolbar: Please allow “free-scrolling” similar to the Bookmarks Menu so one does not have to two-finger scroll when you hit the bottom of the viewable area.

**Comment by srirambv** [comment]
+2 from community https://community.brave.com/t/cant-scroll-through-bookmarks/6037/5

**Comment by srirambv** [comment]
Adding this to 0.22.x as its quite a serious problem for people with loads of bookmarks. Please move milestone if required. 

cc: @brave/release-team
