### ISSUE TITLE
Share settings/bookmarks across devices

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#4784]
From support: https://linkbubble.zendesk.com/agent/tickets/5595

> - Synch: Perhaps a synch account so settings/bookmarks can be shared across devices. I understand this means data storage and all the potential headaches, a la Yahoo this week, so perhaps something simpler like a cache file that is accessed in a user’s existing cloud storage (Dropbox, iCloud, etc.)?

**Comment by bbondy** [comment]
Marking as a duplicate of:
https://github.com/brave/browser-laptop/issues/1854
