### ISSUE TITLE
l10n of ledger advanced settings modal window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4786]
**Describe the issue you encountered:** buttons on ledger advanced settings modal window are broken.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19393880/a37ad584-9271-11e6-9fdb-d4f88ba2bb99.png)

**Expected behavior:** Buttons should not word-wrap.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues: #2096

**Comment by bbondy** [comment]
cc @jkup pls handle for 0.12.6

**Comment by jkup** [comment]
Sorry I didn't see this one until just now! I'll have it in tomorrow.

**Comment by bbondy** [comment]
@jkup ping

**Comment by luixxiul** [comment]
On Backup your wallet you get this:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20457346/c102ffc4-aecc-11e6-8a7e-dabff9d18373.png)

The commit https://github.com/brave/browser-laptop/pull/5705/commits/3bb9b1597f5a5efda85e66db2c25b06fe3b1fe7c of #5705 fixes it too into this:

<img width="729" alt="screenshot 2016-11-20 1 52 29" src="https://cloud.githubusercontent.com/assets/3362943/20457052/26d93734-aec6-11e6-9ad4-411a80f8db17.png">

**Comment by luixxiul** [comment]
Test plan:

Modified https://github.com/brave/browser-laptop/commit/75a754a8b7ccc983acdbb8e2c3ce6dd602ebfd3a to update with the latest status:

1. Open about:preferences#payments
2. Make sure the font size of the two buttons "Add funds" and "Advanced Settings..." is equal
3. Click "Advanced Settings..."
4. Make sure each button is not wrapped

And https://github.com/brave/browser-laptop/commit/23207ed38d1423017a94285f229d8ba5dec0c8d3

1. Click the bookmark button on the URL bar
2. Make sure height of "Remove" and "Done" buttons is equal
3. Make sure "Remove" button is longer than "Done" button
4. Make sure color of "Remove" label is no longer white on hover
5. Make sure width of the row of the buttons is equal to the other rows
6. Open about:bookmarks and edit a bookmark
7. Make sure height and width of "Remove" and "Done" are equal
8. Open about:preferences#payments, click Advanced Settings and Backup your wallet
9. Make sure keys and buttons are aligned
10. Make sure font-size of the labels "Copy" is 14px

**Comment by luixxiul** [comment]
Follow-up of this: 5th commit of #6047 

<img width="730" alt="screenshot 2016-12-15 3 32 43" src="https://cloud.githubusercontent.com/assets/3362943/21195457/3429e63a-c277-11e6-9bcb-05050e504513.png">

The buttons are no longer aligned at the center.
