### ISSUE TITLE
subfolders under Other Bookmarks not appearing on pulldown on adding bookmark dialog

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4788]
**Describe the issue you encountered:** Subfolders under `Other Bookmarks` not appearing on pulldown of adding bookmark dialog

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19394802/978490d6-9275-11e6-9114-473cc7ff6075.png)

**Expected behavior:** There should be `Other Bookmarks / ff` on the pulldown
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues: #4756

**Comment by bsclifton** [comment]
Marking as duplicate- I'll make a note to include children on this issue:
https://github.com/brave/browser-laptop/issues/3145

**Comment by bsclifton** [comment]
Ignore the dupe comment I had- we don't appear to have this captured :smile: We'll need to show Other Bookmarks and also subfolders

**Comment by luixxiul** [comment]
dupling to #4202
