### ISSUE TITLE
hit target for back (and forward) button too small

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#479]
It's too easy to click *near* the back or forward button and miss it. The hit target needs to be wider than the icon.

**Comment by diracdeltas** [comment]
Agree; before changing to the lighter UI, it looked like:
![screen shot 2016-01-30 at 3 34 46 pm](https://cloud.githubusercontent.com/assets/549654/12699179/4f679372-c767-11e5-8e2e-ea9313c86e8b.png)

would be in favor of going back to that design

**Comment by bbondy** [comment]
CC'ing @bradleyrichter for comment.
We can also fix with just padding to keep the current look and still address this.

**Comment by bradleyrichter** [comment]
@asadotzler New UI additions should improve this quite a bit. LMKWYT...
(see white hover circle behind back button which also provide hit area.)

![screen shot 2016-02-01 at 5 23 18 pm](https://cloud.githubusercontent.com/assets/13509546/12736854/adb5b2d6-c908-11e5-9a1a-18ab2adc659a.png)

**Comment by bbondy** [comment]
I think this is addressed now with the new UI, but please comment and we can re-open if not.
