### ISSUE TITLE
Advanced setting button should be hidden when payments is disabled

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4790]
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**
Clicking on the "Advanced settings" button while payments are turned off produces no action. If you turn payments on then a pop up appears.

**Expected behavior:**

When payments are off, the button should be hidden, if it will not trigger any action.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version: 0.12.5-1

- Steps to reproduce:
    1. Go to payments
    2. Turn them off
    3. Click advanced settings

- Screenshot if needed:
<img src="https://s21.postimg.org/bwhf3sf3b/Preferences_017.png"/>
- Any related issues:

**Comment by luixxiul** [comment]
I cannot confirm this was fixed on 0.12.5 RC2, on Windows 10. Regression or something?

**Comment by bbondy** [comment]
This is not in 0.12.5 but it should be fixed on master 0.12.6.
By the way you can see the tags it is on by clicking on the commit, the one we do builds from is dev-channel.

**Comment by luixxiul** [comment]
I thought this is it, which has been tagged 0.12.5 RC builds: https://github.com/brave/browser-laptop/commit/7666907f578c8f746fdba40fa9adf656d1ea5568

**Comment by bsclifton** [comment]
ah- definitely my bad assuming it was pulled into 0.12.5

**Comment by luixxiul** [comment]
This is happening again on the latest master.

**Comment by bsclifton** [comment]
@luixxiul can you open a new issue w/ steps to reproduce? (and link back here) Thanks :smile:
