### ISSUE TITLE
Autocomplete - wrong website title

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4792]
**Did you search for similar issues before submitting this one?**
No.

**Describe the issue you encountered:**

Autocomplete yields wrong title for some history entries.

**Expected behavior:**

The title of the page should match the path of the page.
- Platform (Win7, 8, 10? macOS? Linux distro?): all
- Brave Version: 0.12.5-1
- Steps to reproduce:
  1. Open new blank tab.
  2. Type twitter.com hit enter
  3. Open second tab start typing twitter verify that the title is correct.
  4. Now close the second tab and in the first opened tab with twitter, click on a feed post
  5. Notice that the url and the title changes
     6 .Again open a new tab and start typing twitter
  6. Observe that the title is wrong
- Screenshot if needed:
  <img src="https://s13.postimg.org/m8cw1h3s7/Screenshot_from_2016_10_14_20_48_53.png"/>
- Any related issues:
  https://github.com/brave/browser-laptop/issues/4224
  https://github.com/brave/browser-laptop/issues/4663

**Comment by bbondy** [comment]
I assume this is a sites entry that has the wrong title, can you check in session-store-1 in your brave user profile dir? 
If that's it, do you have STR to get one oft hose site entries?

**Comment by Sh1d0w** [comment]
@bbondy This is very easy reproducible.

1. Open new blan tab.
2. Type `twitter.com` hit enter
3. Open second tab start typing `twitter` verify that the title is correct.
4. Now close the second tab and in the first opened tab with twitter, click on a feed post
5. Notice that the url and the title changes
6. Again open a new tab and start typing `twitter`
7. Observe that the title is wrong

I even know why it is happening. It is because of this line:

https://github.com/brave/browser-laptop/blob/master/js/components/frame.js#L698

**Comment by Dhanesh95** [comment]
Wasn't able to reproduce this bug on Fedora.

**Comment by bsclifton** [comment]
Removing milestone for now.  Let's chat if you'd like to see this be bumped up in priority. Thanks :smile:

**Comment by garrettr** [comment]
I can reproduce this on Mac OS 10.10.5 with Brave 0.12.15. I noticed it when auto-completing entries with fuzzy matching in the address bar. The fuzzy-match query would correctly match against the URL, but the correct title for the matched URL would not be displayed.

Here's an example screenshot—notice that the titles don't match the URLs for the first two history entries:

<img width="1280" alt="screen shot 2016-12-30 at 1 12 26 pm" src="https://cloud.githubusercontent.com/assets/407302/21570212/ef1d6ad6-ce91-11e6-8792-1fa98e5613b3.png">

**Comment by bsclifton** [comment]
This appears to have been fixed- I can't reproduce with the steps mentioned

**Comment by luixxiul** [comment]
I cannot find a proper STR but I experience the issue on Windows. I notice it on youtube especially, wondering if it could be related with youtube autoplay.
