### ISSUE TITLE
Autocomplete does not add history entries

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4794]
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**

Using autocomlete to open pages does not add entries to the history.

**Expected behavior:**

Every page should be logged in the history with its last access time.
- Platform (Win7, 8, 10? macOS? Linux distro?): Fedora 24
- Brave Version: 0.12.5-1
- Steps to reproduce:
  1. Use autocomplete to navigate to page
  2. Inspect history

http://webm.land/media/QHH0.webm
- Any related issues:

**Comment by aekeus** [comment]
I can confirm this is working in latest release. Closing now - please re-open if behaviour shows up again.

**Comment by Sh1d0w** [comment]
Sorry, it is still not working for me on the latest master https://github.com/brave/browser-laptop/commit/f37459c2a3d63b1704ba6bf7aaf305d224eb5039 on Fedora 24 . Followed the same steps from the video this morning and I can only see history entries from yesterday.

**Comment by Sh1d0w** [comment]
Here is a video from latest master https://github.com/brave/browser-laptop/commit/af38d76dced4a1124762a12377340c1a925c1989

http://webm.land/media/Kgjk.webm

**Comment by bsclifton** [comment]
Removing from 0.12.9 milestone (deadline: EOD today)

**Comment by bsclifton** [comment]
Closing as history shows great for me and this issue is likely stale.  Please do re-open if issue reoccurs

cc: @aekeus

**Comment by aekeus** [comment]
Thanks for triaging this @bsclifton
