### ISSUE TITLE
Brave fails to open from "Open with" context menu

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4795]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:**
Right-clicking a file, and selecting "Open with > Brave", results in processes, but no browser.

_After a minute, the spawned processes will disappear._

**Expected behavior:**
Right-clicking a file, and selecting "Open with > Brave", results in the file being opened in Brave.

**Platform:** Windows 10

**Brave Version:** 0.12.5

**Steps to reproduce:**
    1. Right-click an .html file on your machine
    2. Select "Open with > Brave"
    3. Note that Brave does not open
    4. Note that Brave.exe processes are running

**Comment by Sh1d0w** [comment]
I can confirm the same bug can be reproduced on Fedora 24, so it does not seem like a Windows on;y issue.

**Comment by neeklamy** [comment]
This works as expected on OS X (10.11.6, Brave 0.12.4). Just to be sure I also tried quitting out of Brave, then in Finder, right clicking on an HTML document and opening with Brave – again, no problems here.

**Comment by Sh1d0w** [comment]
@neeklamy The bug is reported and confirmed under 0.12.5

**Comment by bsclifton** [comment]
repro'ed on Windows 10

**Comment by neeklamy** [comment]
@Sh1d0w, it works under OS X with the latest RC too, v0.12.5dev-RC1.

I tried quitting Brave, double-clicking the local HTML file, quitting right-clicking and using “Open With → Brave”. Always making sure to close the window or tab with the local file in and trying with multiple HTML files. It doesn’t repo here.

_(Thanks too for editing your comment, I have to say your initial reply came across a touch snarky… Hey, I can easily move on you know…)_

**Comment by Tyler-H** [comment]
Hi, I mentioned this bug to Jonathan the other day; my tested setups were Windows 7 64-bit Ultimate and Windows 7 64-bit Enterprise, both of them on the latest version of Brave for dev update channel (0.12.1).

Here is a short (~35 seconds) video of my experiences (failure and success) on Windows 7:
https://www.youtube.com/watch?v=ELC6qgOXNFI

I don't have access to my Windows 10 laptop to test or record an experience on there currently. I will download the 0.12.5.dev-RC1 for Windows7+ and try that as well.

**Comment by bbondy** [comment]
User on Twitter mentioned this as a likely cause for opening local HTML files not working as well:
https://twitter.com/PermittedSoc/status/790809270690451456
