### ISSUE TITLE
Brave crashes if alert is called without a message

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#4798]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
from https://hackerone.com/reports/175850
`<script>alert()</script>` will crash brave on `toString`

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
master

**Comment by luixxiul** [comment]
Any page to test this?

**Comment by alexwykoff** [comment]
@luixxiul  It's pretty easy to write a local file and open it. The behavior is the the same.

**Comment by willy-b** [comment]
You can also use paste a data URL right into the URL bar: `data:text/html,<script>alert()</script>`

**Comment by willy-b** [comment]
BTW, this is still an issue if you pass a title which is a number, e.g.:
`data:text/html,<script>alert("hello", 1)</script>` will crash Brave.

I'm going to roll that fix into #4891 if you don't mind
