### ISSUE TITLE
reload menu reloads entire browser window when no frames are active

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#48]
Steps to reproduce:
1. Open the browser with a new window
2. Use the reload menu item or shortcut

Reload should be disabled and have no effect if there is no content to reload

**Comment by serv** [comment]
Just fyi, in chrome's incognito mode, you are able to reload even though there's no page to reload.

**Comment by bridiver** [comment]
This is a slightly different. The empty tab doesn't reload, the entire app window reloads. It's definitely not the behavior we want.

**Comment by bbondy** [comment]
Fixed by the frame reload fix in electron?

**Comment by bridiver** [comment]
Possibly. I noticed this after the fact, but didn't check to see if it was fixed by that change or something before it.
