### ISSUE TITLE
attempting to select text in address / search bar moves window

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#480]
On Mac, with the 0.7.11 build, drag selecting text in the address / search bar can sometimes drag the window instead of creating a selection.  This makes editing URLs very painful.  When the addressbar tells me it's focused, text selection should always beat window drag.

**Comment by asadotzler** [comment]
This is probably a duplicate of bug #118

**Comment by bbondy** [comment]
Indeed it's the same, we're going to play with moving tabs up as a quick fix to this instead of patching the electron bug.  Closing this as a duplicate but thanks for pointing it out.
