### ISSUE TITLE
Brave should detect unclean shutdown and provide better recovery options

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#4800]
If Brave crashes because of an issue with state (windows, tabs or some other serialized state issue) it can be very difficult to open again without clearing out all state, settings, etc... We should detect unclean shutdowns and provide recovery options for cleaning the state

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bsclifton** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/5512, which includes the requirements from this issue
