### ISSUE TITLE
Evernote: Fonts load very slow

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4802]
**Describe the issue you encountered:**
Fonts shipping with the Evernote extension are taking nearly 30 seconds to load.

**Expected behavior:**
Fonts load quickly, and place little burden on the UI thread.

**Platform:** Windows 10

**Brave Version:** 0.12.5

**Screenshot if needed:**
![image](https://cloud.githubusercontent.com/assets/815158/19405238/3b7eb780-922a-11e6-990b-6b53e8a742dd.png)

**Any related issues:** #4760

**Comment by jonathansampson** [comment]
I was mistaken; the fonts aren't the issue. Something is causing a long delay in loading. I'll update this issue once that bottleneck has been identified.

**Comment by luixxiul** [comment]
Closing as stale 👍

**Comment by jonathansampson** [comment]
For what it's worth, I suspect this issue may have been resolved by some performance work we did on Windows in mid-2017.
