### ISSUE TITLE
truncated bookmark folder titles should be displayed with tooltip on hover

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4804]
**Describe the issue you encountered:** if bookmark folder titles are truncated, the full titles should be displayed with tooltip on hover. Currently you cannot check them until you click Edit Folder.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC1

- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul do you have more info about this? In the bookmarks toolbar, this looks OK to me:

**bookmark which is truncated**
![image](https://cloud.githubusercontent.com/assets/4733304/19633548/dbfe8fa2-9967-11e6-8937-55a1286b228f.png)

**bookmark folder which is truncated**
![image](https://cloud.githubusercontent.com/assets/4733304/19633556/eeeffaa6-9967-11e6-9103-c2b9ac628722.png)

(using the official release of 0.12.5)

**Comment by luixxiul** [comment]
I'm not so sure what I meant, so closing for now. I will reopen this with a screenshot if I remember it :-D
