### ISSUE TITLE
Documentation - How to enable/disable shields and what does that do?

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#4805]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From support:

> Could we have a bit more information on your website as to what ‘Shields’ do please?
- Any related issues:

https://github.com/brave/browser-laptop/issues/4646

**Comment by luixxiul** [comment]
This explains a similar stuff but not exactly what "shields" are.

https://community.brave.com/t/a-site-is-not-working-not-showing-images-not-allowing-me-to-log-in/15

 It is explained that "Brave blocks ads and trackers that slow you down and invade your privacy" on `about:welcome`. If that is not enough, we could add another FAQ which simply explains what shields to.

**Comment by bsclifton** [comment]
Closing per the community article above
