### ISSUE TITLE
Import recovery keys feature

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4806]
**Describe the issue you encountered:** Now you can export your brave wallet recovery key, it would be great to have a feature of importing it on "Recover your wallet" modal window.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Steps to reproduce:
  1. Go to about:preferences#advanced
  2. Click Advanced Settings
  3. Click "backup your wallet"
  4. Click "save recovery file"
  5. Click "done"
  6. Click "recover your wallet"
  7. A button named "import recovery keys" should exist next to the button "recover"
- Any related issues:

**Comment by mrose17** [comment]
@luixxiul - i'm a bit confused, what action needs to be taken with respect to this issue?

**Comment by luixxiul** [comment]
a button to import recovery key.

**Comment by mrose17** [comment]
@luixxiul - this is what i see now, what should i also see? thanks!
![1](https://cloud.githubusercontent.com/assets/400552/19694364/dd897080-9a93-11e6-9a6a-e0dc4f9c016b.png)

**Comment by willy-b** [comment]
@mrose17, I think @luixxiul means to add the button to the 'Recover your wallet' dialog, like this:
![recover_from_file_anim](https://cloud.githubusercontent.com/assets/6969859/19706242/b7db48b8-9ac5-11e6-8069-fe6be468e9ac.gif)

**Comment by mrose17** [comment]
i see, yes, that makes sense... thanks!

**Comment by willy-b** [comment]
No problem! 
(N.B. I got the label wrong -- I put "Recover from file" where @luixxiul spec'd "Import recovery keys")

**Comment by willy-b** [comment]
FYI, I just pushed an impl of this to a branch in my fork, will open a PR once I have a test.

**Comment by luixxiul** [comment]
@willy-b "Recover from file" sounds more natural :-)

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/5809 which was merged into branch `0.13.1-branch`.
