### ISSUE TITLE
suppress (brief flash of ) tab loading indicator on new tabs 

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#481]
On the 0.7.11 build on Mac, new tabs briefly flash a loading indicator on the left side before hiding it. Makes creating new tabs feel janky. Probably also a good idea to suppress the pageload time displayed in the addressbar. This is a blank tab and it shouldn't feel or label itself as slower than "instant".

**Comment by diracdeltas** [comment]
i tried to get rid of this jank while fixing https://github.com/brave/browser-laptop/issues/373 but haven't figured out how to make 'about:blank' load in <10ms. other than not setting the `src` attribute on the webview at all, but that caused a lot more bugs.

**Comment by bbondy** [comment]
let's just not show the loading indicator for about: sourced URLs.

**Comment by psimyn** [comment]
this can be closed now
