### ISSUE TITLE
Clicking Bookmarks Toolbar from "Bookmarks" menu does not change state of check mark

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4810]
**Describe the issue you encountered:** Clicking Bookmarks Toolbar from "Bookmarks" menu does not change state of check mark. Even if you click it to hide the toolbar, the check mark still remains. This does not happen on the hamburger menu.

**Expected behavior:** It should change state of check mark.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC1

- Steps to reproduce:
    1. Clicking Bookmarks Toolbar from "Bookmarks" menu to show the toolbar
    2. Click it again to hide the toolbar -> the check mark remains

- Any related issues:

**Comment by bbondy** [comment]
This is working reliably for me on macOS (which I'd expect to be the same) but was a problem with an old build. Are you sure you  had the latest?

**Comment by bbondy** [comment]
Tested on Windows and reproduced, I guess maybe the code is different because of the titlebar removal work

**Comment by bsclifton** [comment]
Found root cause- menu status (the electron menu) is being updated, but not the version in the appState. I'll have a fix later tonite :smile:
