### ISSUE TITLE
common context menu should not appear by right-clicking entries in about:history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4811]
**Describe the issue you encountered:** if you do a right clicking of an entry in about:history, the common context menu appears. You have to select an entry and activate it at first to show the history context menu.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19406511/38617928-92c2-11e6-9563-b434a49574f0.png)

**Expected behavior:** common context menu should not appear by right-clicking entries in about:history. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC1

- Any related issues:

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/5206 :smile: Thanks for the heads up @luixxiul
