### ISSUE TITLE
windows URL bar icons and URL text are misaligned 

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4814]
![image](https://cloud.githubusercontent.com/assets/13509546/19406711/f9495e4a-923f-11e6-9d78-6b05af73c1b3.png)

(vertical center shown as thick red line)

**Comment by bbondy** [comment]
A bit risky and the same issue in the live build, I'm going to move this to 0.12.6.

**Comment by bbondy** [comment]
@bsclifton I think this is fixed right? Closing.

**Comment by bsclifton** [comment]
We still might have an issue with the URL being 1px too low (lock is OK, reload is OK).

@bradleyrichter if you have time to grab master, take a peek and re-open this issue if needed :smile:
