### ISSUE TITLE
zoom in / out / reset (with numpad) not working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4815]
**Describe the issue you encountered:** zoom in / out shortcut stopped working. Removing brave folder does not help.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5 RC1
- Any related issues:

**Comment by luixxiul** [comment]
zooming in / out with the numpad stopped working.

**Comment by bbondy** [comment]
-, +, and 0 on top of keyboard on macOS and Windows. This is only on bigger keyboards on the right? Moving to 0.12.6.

**Comment by Liunkae** [comment]
Related issue: #3040

**Comment by bbondy** [comment]
@bsclifton do you have a keyboard and could you take?

**Comment by bsclifton** [comment]
Yup- I'm on it :smile:

**Comment by bsclifton** [comment]
works great on macOS (both regular +/- and numpad)

On Windows 10, pressing either (regular or numpad) brings up the magnifier tool:
![screen shot 2016-10-18 at 1 48 45 pm](https://cloud.githubusercontent.com/assets/4733304/19495815/d09689e4-9539-11e6-946b-9d9f0769a9b6.png)

**Comment by bsclifton** [comment]
Root cause seems to be in electron (not supported yet)...
https://github.com/electron/electron/issues/3332

I'm going to remove the regression label (please add back if I am incorrect in removing)

There might be a work-around for this; I'll look at implementing that :smile:

**Comment by bsclifton** [comment]
Moving to 0.12.7 since this is marked as not-blocking

**Comment by bsclifton** [comment]
@bbondy because this is a problem upstream, I'd like to propose moving it out of 0.12.7.  It's still important, but seems it would need an electron change

**Comment by bsclifton** [comment]
On Linux, user @SamClarke2012 reports that - and + on the numpad both work great (just not reset)

**Comment by gsantner** [comment]
Tried pretty much every combination on my linux device now. `Ctrl+{`NumPadPlus, NumpadPlus,Plus,+`}. None of them are working. This is not affecting windows only.

**Comment by bsclifton** [comment]
@gsantner thanks for the feedback- I removed the Windows tag since it happens for sure on Linux (and likely macOS, if you have a full extended keyboard)

**Comment by luixxiul** [comment]
I cannot reproduce the issue on Windows 10.

**Comment by luixxiul** [comment]
Closing as stale.

**Comment by bsclifton** [comment]
Verified fixed with [brave-core](https://github.com/brave/brave-browser)
