### ISSUE TITLE
Exclude pattern to block brave ad replacement placeholder from adblock filters 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4816]
**Describe the issue you encountered:** Currently there are some regional adblock filters block brave ad replacement placeholder.

**Expected behavior:** Exclude pattern to block brave ad replacement placeholder from adblock filters.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC1

- Steps to reproduce:
    1. Open https://slashdot.org and confirm "Show Brave ads" is selected on the bravery shield
    2. Open about:adblock and enable JPN: ABP Japanese filters (日本用フィルタ)
    3. Clear cache and reload https://slashdot.org
    4. Placeholders are gone

- Any related issues:

**Comment by bbondy** [comment]
Fixed here:
https://github.com/bbondy/abp-filter-parser-cpp/commit/9d92106692309cddafa351f575156eca87fed07d
