### ISSUE TITLE
autofill entry cannot be deleted on restart with Private data option

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4818]
**Describe the issue you encountered:** autofill entry cannot be deleted on restart with Private data option. Also clicking these crosses does not remove the entries.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19406902/3900e6da-92cb-11e6-929c-ad64390a3f71.png)

**Expected behavior:** The entries should be removed on restart

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC1

- Steps to reproduce:
    1. Add address and credit card
    2. Enable "autofill data" option of Private Data on about:preferences#security
    3. Restart the browser

- Any related issues:

**Comment by darkdh** [comment]
What do you mean "Private Data"?

**Comment by luixxiul** [comment]
If you open ``about:preferences#security`` you have the options to select which data should be removed on restart, whose label is "Private Data".
