### ISSUE TITLE
Set 2 visits on minimum visit for publisher relevancy and automatically back to 5

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4822]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:**

I set 2 visits on minimum visit for publisher relevancy and automatically back to 5

**Expected behavior:**

Keep on 2
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 64
- Brave Version: Dev Channel Beta v0.12.5dev-RC1
- Steps to reproduce:
  1. Go to preferences/payment
     2.Open advanced settings
  2. Set 2 visits

Obs. See the video uploaded to understand the problem
[Brave.ogv.zip](https://github.com/brave/browser-laptop/files/531172/Brave.ogv.zip)

**Comment by jkup** [comment]
Also heard that dropping the number of visits clears out the ledger list. Going to look into both for this ticket.

**Comment by bitcoinuser** [comment]
> Also heard that dropping the number of visits clears out the ledger list

Happened with me too.

**Comment by jkup** [comment]
Looking into this now. I suspect this started happening from this commit https://github.com/brave/browser-laptop/commit/42146a32e49b97a1e35df016ea724d4dc48bad9c

**Comment by jkup** [comment]
Update: I think the clearing of the ledger list is working as designed. If you don't have any entries with 10+ visits and you change your minimum visits to 10 they *should* all disappear.

Still investigating the choice not persisting!

![ledger](https://cloud.githubusercontent.com/assets/490294/20393719/daceabca-acaa-11e6-960d-d0e9707a6b55.gif)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5824#issue-191373434
