### ISSUE TITLE
URL including "about" not loaded from URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4824]
**Describe the issue you encountered:** URL including "about" cannot be loaded from URL bar

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/7666907f578c8f746fdba40fa9adf656d1ea5568

- Steps to reproduce:
    1. Open ``philosophyguides.org/about/`` on a new tab
    1. Open ``brave.com/about.html`` on a new tab
    2. In both case Google search result is shown instead of loading the page

**Comment by bbondy** [comment]
even about.com

**Comment by bbondy** [comment]
pulling this into 0.12.5
