### ISSUE TITLE
Advanced settings button should be hidden when Brave Payments are off

### ISSUE THREAD

**Issue by charbelrami** [brave/browser-laptop#4826]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Advanced settings button doesn't do anything if the Brave Payment switch is off

**Expected behavior:**
Hide or disable the button when the switch is off

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 64-bit

- Brave Version:
v0.12.5dev-RC1

- Steps to reproduce:
    1. > Preferences
    2. Click advanced settings

- Screenshot if needed:
![advanced-settings-btn](https://cloud.githubusercontent.com/assets/5647344/19412662/1842df68-92f1-11e6-86b1-208a72740f0c.gif)

- Any related issues:

**Comment by Sh1d0w** [comment]
Duplciate of https://github.com/brave/browser-laptop/issues/4790

Already fixed.
