### ISSUE TITLE
Add a way to see which version of Brave you are running.

### ISSUE THREAD

**Issue by TheFallenOneGOTH** [brave/browser-laptop#483]
Greetings, Brave Team!
I can never find a way to find out which version of Brave I am running, or if there is I don't know where it would be. Either way, the title of the issue is self-explanatory.

Warm regards,
TheFallenOneGOTH (aka Liam)

**Comment by bbondy** [comment]
You can find this in Help | About Brave.  Although there is a known bug that it shows undefined there. That issue is fixed and will be release din the next update.  On OS X Brave | About Brave.
Thanks for posting!

**Comment by TheFallenOneGOTH** [comment]
And where exactly would "Help | About Brave" be?

**Comment by bbondy** [comment]
Sorry just hit the Alt button to show menus on Windows.
