### ISSUE TITLE
Cannot set Brave to be default browser...under Win 7.

### ISSUE THREAD

**Issue by ktd99** [brave/browser-laptop#4832]
Did you search for similar issues before submitting this one? Yes

Describe the issue you encountered: My default browser has been Brave. A couple of weeks ago I started having a problem, in that I received an error msg when clicking on a link in an Outlook 2007 message. A search of online suggestions resulted in my making IE my new default. And that "solved" the problem...but I still would like Brave to be the default. 

And when I went back to the Internet Settings tabs, and listed all of my programs, BRAVE WAS NOT ON THE LIST!  It's as if my computer doesn't realize Brave SW is installed.  So...how do I recover a successful linkage between Outlook 2007 and Brave?

Expected behavior: 
1. I need to be able to set Brave as default browser. 
2. I need hyperlinks in Outlook 2007 to work.

Platform (Win7, 8, 10? macOS? Linux distro?): Win7

Brave Version: 0.12.4

Steps to reproduce:

N/A 2. 3.
Screenshot if needed:

Any related issues:

**Comment by bsclifton** [comment]
This issue should be resolved when this issue is fixed and released: https://github.com/brave/browser-laptop/issues/2105 (scheduled for 0.12.6, not our next release, but the one after that).

**Comment by ktd99** [comment]
Alex in Support sent me this suggestion:  If you open your Control Panel, you should be able to see 'Programs'. Select that, then you should be able to see 'Default Programs'. From there you should be able to set default programs.

I tried that and it worked.  And then I took my original route, via Control Panel/Network and Internet.  When I selected the Programs tab, Brave showed up on the list...it had dropped off.  

I had not followed the original advice in the wiki, so part of this was my fault.  I didn't realize there were two paths for setting a default browser.

SO...it is working for now.  I'm not sure that it won't "go away" again...but I'll know to try the other path if it DOES happen again.  In some versions of Brave one can set it as a default within the program.   Perhaps that's what bsclifton is referring to?

**Comment by bsclifton** [comment]
@ktd99 has this been fixed for you? Our recent releases added the option to prompt you for setting default browser.  Please let us know :smile:

**Comment by ktd99** [comment]
Thank you for the question, Brian.  So far I'm still good.

 

But since I have your attention, perhaps you could field a question for me.  When I was placing an online order I could not add items to my cart.  I suspect that has to do with blocking pop-ups...or something like that.  What can I do to allow that interaction with certain sites?

 

I love the fact that I see so fewer ads under Brave!

 

Sincerely,

Karen

**Comment by bsclifton** [comment]
@ktd99 hi Karen :smile: 

You should be able to use the shields icon (the Brave lion logo in the top right) to change settings on a per-website basis.  This should allow for enabling what is needed for the site to work

Please let me know if that works :smile: For this particular issue (default browser), I'm going to go ahead and close it since you're good to go there.  Thanks!

**Comment by ktd99** [comment]
Thanks for fielding my question, Brian!  I have tried allowing all ads and all cookies...still can't get it to work right for the site.

 

It's landsend.com    I can't Add items  to the Bag.  The "button" seems to work, but the Bag remains at 0 items.

 

Thx,

Karen
