### ISSUE TITLE
Bookmark title dynamically changed

### ISSUE THREAD

**Issue by gravitycrusher7** [brave/browser-laptop#4833]
**Did you search for similar issues before submitting this one?**
No
**Describe the issue you encountered:**
Bookmark title dynamically changed when its open a new link with different title. For example in my case is twitch. I bookmark https://www.twitch.tv/directory/following its title Twitch - following and when I opened someone's stream page it also changed my bookmark title for twith. I dont know if this is actually should working like that, but if yes I would like to have some options like "Allow/disallow dynamically change on bookmark bar".

Sorry for bad grammar

**Expected behavior:**
It should be not change the title whenever we opened another link.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win 7
- Brave Version:
  Latest version
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
@bbondy could this be due to the corruption issue you recently fixed? I've seen it before too but am currently unable to repro

**Comment by bbondy** [comment]
I guess but I don't think so, I think it's maybe related to us debouncing and then the page changing underneath when the updated info is updated.

**Comment by NejcZdovc** [comment]
This should be fixed with #9979
