### ISSUE TITLE
Feature Request : Mailvelope Extension 

### ISSUE THREAD

**Issue by ConorIA** [brave/browser-laptop#4845]
**Did you search for similar issues before submitting this one?**
Yes

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/mailvelope/kajibbejlbohfaggdiogboambcijhkke

**What do you like about the extension?**
OpenPGP encryption is a desirable feature in any privacy-focused browser. Mailvelope makes OpenPGP implementation a breeze for webmail, including Gmail, Nextcloud/Owncloud mail, and many other providors.

**Comment by Liunkae** [comment]
Related issue: #4914

**Comment by CoalaJoe** [comment]
Would be one of my favorite features.
