### ISSUE TITLE
Pressing Tab, then Enter in URL bar unexpectedly minimizes window on Windows

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#4846]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When typing in the URL bar, pressing the tab key causes the focus to move to the minimize button on Windows.  The only visual indication that this has happened is that the blue border around the URL bar disappears.  The autocomplete stays visible, and any selection in the field stays highlighted.  This makes it seem as if the bar still has focus, and pressing the enter key should navigate to the currently entered address.  However, since the minimize button invisibly has focus, pressing enter minimizes the window instead.

**Expected behavior:**
On Chrome, pressing tab while typing a URL usually either cycles through autocomplete items or starts a site search.  Alternatively, on Microsoft Edge, pressing tab while typing a URL moves focus to another button, but not to the window controls, and it's visually obvious.  Either of these behaviors would be more desirable.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5

- Steps to reproduce:
    1. Focus the URL bar
    2. Start typing a URL and allow autocomplete to appear
    3. Press tab key once (or twice)
    4. Note that autocomplete stays open and autocompleted text within the text field stays highlighted.  The minimize button does not change color.  The only thing that changes onscreen is that the blue border disappears.
    5. Press the enter key.  The window minimizes (or maximizes if you pressed tab twice)

**Comment by bbondy** [comment]
@bsclifton I think maybe the window controls  are accepting tab index, should be a quick tweak to fix.

**Comment by bbondy** [comment]
I think it's just `tabindex='-1'`
