### ISSUE TITLE
Add alert dialog for wallet backup invitation

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4847]
When a user first adds funds to their auto-created Brave wallet, they should be invited to Backup their wallet. The dialog should open as a modal alert after they have completed the initial add-funds step.

![image](https://cloud.githubusercontent.com/assets/13509546/19420230/bbc7bec4-939b-11e6-80d0-2a92beaf2709.png)

cc @mrose17 @bbondy

**Comment by luixxiul** [comment]
@mrose17 if you could write the code I would like to style the modal dialog.

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by NejcZdovc** [comment]
@bradleyrichter should we use our regular alert or create a custom one?

**Comment by bradleyrichter** [comment]
Normal alert is fine. We can improve the style for all alerts later.

**Comment by NejcZdovc** [comment]
@bradleyrichter in mock user can only see backup now or remind me later, what if he doesn't want to see it at all? If we keep remind me later, when should we trigger it again? After another deposit?

**Comment by bradleyrichter** [comment]
After each deposit made until backup is created.

**Comment by NejcZdovc** [comment]
blocked by #8137

**Comment by luixxiul** [comment]
#8137 was merged.

**Comment by bsclifton** [comment]
No longer blocked- see https://github.com/bsclifton/browser-laptop/blob/d1c662e1f4ec4460ba3e808d93f7fffe5e7a583b/app/browser/api/ledger.js#L231 for an example 😄

**Comment by NejcZdovc** [comment]
@mrose17 do we have any mechanism to detect when first contribution is made?

**Comment by mrose17** [comment]
@NejcZdovc - you'd have to look at the history for the earliest entry

           transactions[...].submissionStamp

**Comment by NejcZdovc** [comment]
blocked on #13504. This PR will introduce backup flag that we can then use in this PR

**Comment by NejcZdovc** [comment]
@bradleyrichter do we still want to add this now that we added #13504

**Comment by NejcZdovc** [comment]
closing per discussion with @bradleyrichter
