### ISSUE TITLE
Brave Browser very slow to open or close tabs

### ISSUE THREAD

**Issue by jrshonka** [brave/browser-laptop#4848]
**Did you search for similar issues before submitting this one?** Yes I did.

**Describe the issue you encountered:**
I have recently (about 2 weeks ago) installed Brave browser and I am finding it very slow when I open and close tabs.  Also, it occasionally "locks up", and I have to re-start it.
**Expected behavior:**
I expected it to be as fast or faster than Chrome
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 with 64-bit
- Brave Version:
  0.12.4
- Steps to reproduce:
  1.  open browser
  2. go to Google, do a search
  3. open a couple of other tabs, like Amazon or my utility company
  4.  try to close a tab - it takes about 12-13 seconds to close.
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
let me know if this is improved with 0.12.5 when it is released please.

**Comment by Blitzkrieg77** [comment]
I also have the same problem. My computer is lightning fast, no issues with performance. There just happens to be some sort of an odd glitch where Brave is slow when closing out tabs. It gives a bit of a 'clunky' feel to the browser overall.

This has been an issue since at least October 16, 2016 and before, I see...

Please fix this!

For the record, my system is running on Windows 8, 64-bit.

I'd also like to add to this that the "forward" and "back" buttons don't always respond when hovering the mouse over them. I think this has to do with the size and area covered by the buttons, though, as opposed to a performance problem.

**Comment by bsclifton** [comment]
@Blitzkrieg77 we should have a new preview build for an upcoming release available soon (next day or so).  Would you be up for trying it to see if performance is better?

**Comment by Blitzkrieg77** [comment]
@bsclifton 

Sure. I wouldn't mind testing it out at all. I think the browser you're continuing to develop is great so far. I'll check back here and on the Brave website for the update. Looking forward to it.

Thanks.

**Comment by Renegilo** [comment]
To date the issue still has not been fixed in version 12:15

**Comment by vgturtle127** [comment]
I am still having this issue, and I am using the latest version of Brave on a fully updated Windows 10 Pro build.

**Comment by makupi** [comment]
Having similar issues here. Happens from time to time that a tab pops out as a new window and when i try to put it back in it freezes and i can't close/open tabs anymore and have to restart brave.

**Comment by iSasFTW** [comment]
Just started having similar issues after updating to the latest version of Brave. Locking up when opening/closing/switching tabs, occasionally even locks up for a few seconds during regular browsing, etc.

**Comment by naman** [comment]
v0.16.9 Still facing sluggish performance while opening/closing new tab, searching through the bar, organizing bookmarks

**Comment by bsclifton** [comment]
Hi @naman,

We should have improvements with regards to closing the tab shipped in our next version, 0.17.  We are also tracking some of the critical performance issues here:
https://github.com/brave/browser-laptop/issues/9311

**Comment by Kandwarf** [comment]
I am still having this issue running Brave on my macbook pro.  I love the browser, but this is an issue that needs SERIOUS attention.  Opening and closing tabs should feel quick!  right now it indeed feels very clunky.  even worse, when I try and do these operations very quickly sometimes the whole tab bar locks up and i cant switch/open/close ANY tabs!  This is a *critical* fault, please investigate this further!

**Comment by luixxiul** [comment]
that issue is recognized. thanks.
