### ISSUE TITLE
Only imports a few bookmarks

### ISSUE THREAD

**Issue by werchick** [brave/browser-laptop#4849]
Won't import bookmarks from Firefox.  Exported Firefox bookmarks and saved html download -- complete list visible -- and imported the html download into Brave but many empty subfiles, many missing bookmarks.  Can this be fixed?

**Comment by Liunkae** [comment]
@werchick Just to be clear, which option did you choose when you tried to import your bookmarks to Brave ("Bookmarks HTML File" or "Mozilla Firefox")?
![image](https://cloud.githubusercontent.com/assets/19424103/19426133/b13b808a-93ff-11e6-99f7-019711e6e2d1.png)
Have you tried importing the bookmarks from Firefox directly, as shown in the screenshot above?

**Comment by werchick** [comment]
I had to use HTML File because Mozilla Firefox does not appear as an 
option for me.  Only Microsoft Edge (which I don't have or use), 
Microsoft Explorer, Chrome First User and the HTML box.

**Comment by Liunkae** [comment]
That itself sounds like a bug. Brave should recognize that you have Firefox installed.

Since you mentioned Microsoft Edge, you must be on Windows 10. @werchick Could you confirm you are using the latest versions of Brave (0.12.4) and Firefox (49.0.1)?

@darkdh, any ideas?

**Comment by werchick** [comment]
Yes on W10 and yes 0.12.4 and 49.0.1.  Should I uninstall and re-install 
Brave?

**Comment by darkdh** [comment]
I can't reproduce it with the same env
![screen shot 2016-10-17 at 16 45 08](https://cloud.githubusercontent.com/assets/11330831/19454959/281d3e1c-9489-11e6-8f51-212651d304d6.png)

**Comment by luixxiul** [comment]
Closing as it is stale. Let's keep discussion if there is additional information though.
