### ISSUE TITLE
LastPass icon not consistent across the browser

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4850]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**

I have changed the default icon for LastPass extension via the extension's page. It successfully updated the extension icon next to the bravery icon on the right after restart. However the icon that appears next to login inputs is the default one.

**Expected behavior:**
LastPass icon should be consistent across the browser and show only the selected by the user icon.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version: 0.12.5-RC2

- Steps to reproduce:
    1. Go to LastPass setting page and change default icon

- Screenshot if needed:
<img src="https://s21.postimg.org/bl9ub604n/Facebook_Log_In_or_Sign_Up_018.png" />
- Any related issues:

**Comment by jonathansampson** [comment]
Presumably, this is by-design. In Chrome the experience is not consistent either.

![image](https://cloud.githubusercontent.com/assets/815158/19468612/3868b7fe-94cc-11e6-9c1e-2141eed2c5f3.png)
