### ISSUE TITLE
convert toolbar icons to SVG

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#4852]
To create a uniform icon set, we need to switch to SVG icons. (FA icons for Home and stop-loading don't work with the rest of our icon styles.)

![image](https://cloud.githubusercontent.com/assets/13509546/19426850/b8bd5ba4-93f4-11e6-814f-d7cd4c2c1643.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19426818/7508e5ae-93f4-11e6-91a8-0668e506a22c.png)

[toolbar_svgs.zip](https://github.com/brave/browser-laptop/files/534377/toolbar_svgs.zip)

@jkup Perhaps we could add this to #4829 ?

**Comment by bradleyrichter** [comment]
@bsclifton ^^

**Comment by bsclifton** [comment]
@jkup I've started to pull these in.  They're in a branch in my fork, being added to fix https://github.com/brave/browser-laptop/issues/4684

**Comment by bsclifton** [comment]
Added images for all and styles for new bookmark & new bookmark folder with https://github.com/brave/browser-laptop/pull/4878

**Comment by jkup** [comment]
I'm bumping this for now but am going to put up a WiP PR for now.

**Comment by bbondy** [comment]
Toolbar seems to be a mess so had to revert the PR:
<img width="785" alt="screenshot 2016-10-24 21 44 21" src="https://cloud.githubusercontent.com/assets/831718/19670155/0a788970-9a33-11e6-97be-30b1478cff46.png">

**Comment by bbondy** [comment]
moving to 0.12.8

**Comment by luixxiul** [comment]
Have we integrated optimization tool like https://github.com/svg/svgo already?
