### ISSUE TITLE
Add payment modal doesn't scroll horizontally when browser window size is small

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4858]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Add payment modal doesn't scroll horizontally when browser window size is small

**Expected behavior:**
Should scroll horizontally
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.5 RC3
- Steps to reproduce:
  1. Open payments and click on Add funds to open the modal
  2. Reduce the window size
  3. Vertical scrolling scrolls the modal vertically but horizontal scroll doesn't scroll the modal just scrolls the page behind
- Screenshot if needed:
  ![paymentmodal](https://cloud.githubusercontent.com/assets/17010094/19431166/ea38f0aa-9474-11e6-9aed-01866d780e9e.gif)
- Any related issues:
  cc: @jkup

**Comment by luixxiul** [comment]
@srirambv I checked it based on the master branch and it seems fixed already here: https://github.com/brave/browser-laptop/blame/master/less/modalOverlay.less#L8-L16. Will you confirm it?

**Comment by luixxiul** [comment]
Closing for now. feel free to reopen if it's not fixed in 0.13
