### ISSUE TITLE
Manually added bookmark pages doesn't create the favicons after visiting the site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4860]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Manually added bookmark pages doesn't create the favicons after vising the site

**Expected behavior:**
Standard behavior is to load the favicon to the bookmark once the page is visited
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1. Right click on the bookmarks toolbar and add a bookmark
  2. Newly added bookmark has the default blank page as favicon
  3. Visit the site the favicon still remains the same, doesn't update the favicons
- Screenshot if needed:
  Brave v/s Chrome
  ![addbookmark](https://cloud.githubusercontent.com/assets/17010094/19435516/af42c520-9488-11e6-916f-abe4d2083859.gif)
- Any related issues:

**Comment by srirambv** [comment]
Issue not fixed. Confirmed by @luixxiul . Reopening the issue 
![4860](https://cloud.githubusercontent.com/assets/17010094/19966549/24d8dc82-a1c4-11e6-96fc-f4cde4e25982.gif)


cc: @bsclifton

**Comment by bbondy** [comment]
Moivng to 0.12.9

**Comment by bsclifton** [comment]
Root cause is that the URL isn't matching. The bookmark, when visited, is updated to have a trailing slash. This ends up not matching the bookmark. The bookmark URL should be canonicalized when added/updated/searched in our sites list
