### ISSUE TITLE
Fully qualified domains entered in full should sort higher than history items with longer URL

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#4861]
If a user types a fully qualified domain name i.e. (google.com) we should not sort URLs such as google.com/info higher.

**Comment by bbondy** [comment]
would love for 0.12.6 if you have time today.

**Comment by aekeus** [comment]
Fixed in https://github.com/brave/browser-laptop/pull/4809 pull request

**Comment by alexwykoff** [comment]
This is not currently working in Preview 1.

**Comment by aekeus** [comment]
@alexwykoff any details about what you were expecting?
