### ISSUE TITLE
Favorites do not have the option 'create folder'

### ISSUE THREAD

**Issue by lccunha** [brave/browser-laptop#4862]
It is common in other browsers as an option to create folders to organize favorites according to their categories. But that does not seem to exist in about: bookmarks

Please check it.

**Comment by bsclifton** [comment]
Hi @lccunha 

I'm working on that feature now :smile: You can follow along at:
https://github.com/brave/browser-laptop/issues/4684

**Comment by lccunha** [comment]
Nice
