### ISSUE TITLE
Regression : when using cmd+l to access the urlbar, any newly typed characters should replace the existing url instead of appending

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4863]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I was trying to visit a new site by using cmd+l, I noticed that I had to use the delete key first otherwise my expected new url was just postpending to the current url.

**Expected behavior:**
Like all prior builds, the current content of the urlbar should be replaced by any newly typed or pasted characters.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X, confirmed on Windows.

- Brave Version:
0.12.3 RC3

- Steps to reproduce:
    1. Visit a site.
    2. Use cmd+l (ctrl+l for windows) to move the cursor to and highlight the contents of the urlbar.
    3. Start typing a new url.

- Any related issues:
Likely introduced by https://github.com/brave/browser-laptop/issues/4851

**Comment by diracdeltas** [comment]
your report says 0.12.3 RC3 - is that supposed to be 0.12.5 ?

**Comment by Sh1d0w** [comment]
This is caused by https://github.com/brave/browser-laptop/commit/b949a84cda403f28868f78894a9cc7c9d6a8a7c0

Reverting this will resolve the bug.

**Comment by diracdeltas** [comment]
@Sh1d0w i'm working on fixing. reverting that commit causes another bug.

**Comment by Sh1d0w** [comment]
@diracdeltas  Ok cool, I was just mentioning, because I am testing it locally on latest master. I tried to reproduce the bug you reported earlier today (and which your commit fixes) when I reverted your commit, but I wasn't able to reproduce it at least not on Linux :)
