### ISSUE TITLE
Add bookmark folder modal width changes when a long folder name is added 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4864]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Add bookmark folder modal width changes when a long folder name is added 

**Expected behavior:**
Should remain same

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.5 RC3

- Steps to reproduce:
    1. Create a bookmark folder via the bookmark toolbar
    2. Enter unusually long name for the folder and save it
    3. Try creating a new folder from bookmark toolbar, shows big modal than the standard modal 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19438686/d11aeaf0-9498-11e6-9ad5-0d37ade0ea4a.png)
 
- Any related issues:

**Comment by srirambv** [comment]
cc: @jkup

**Comment by luixxiul** [comment]
I noticed it too but not quite sure how to fix it and whether it should be fixed.

**Comment by jkup** [comment]
Yeah same, we could fix it by adding a max-width but should we? 

cc @bradleyrichter

**Comment by bradleyrichter** [comment]
Just because you "can" use 256 characters doesn't mean you should.  ;   0

Let's set it as a fixed width field in the new dialog and not spend time on the old.
