### ISSUE TITLE
Add test for Windows style updates (#4856)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4865]
According to https://github.com/brave/browser-laptop/pull/4856#issuecomment-254208404 we should have a test for style updates addressed by #4856

> Windows style updates
> - Increases padding above menu by 2px
> 
> Windows 10 specific updates:
> - window border was changed from black to the default blue accent color
> - inactive windows now have their border set to gray

**Comment by bsclifton** [comment]
Is testing CSS something that folks do? I guess we could explore screenshot testing? Genuinely curious

**Comment by bsclifton** [comment]
Test that could be done
> https://github.com/brave/browser-laptop/pull/4856#issuecomment-254208404

Depends on getting test working on Windows https://github.com/brave/browser-laptop/issues/2719

**Comment by bsclifton** [comment]
Closing as `wontfix`. Our tests are already not in good shape and I don't believe they work on Windows. We won't need to test for this with Brave Core.
