### ISSUE TITLE
View payment history link needs padding 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4867]
View payment history link may use some padding. 

![image](https://cloud.githubusercontent.com/assets/17010094/19448224/8f599c30-94be-11e6-829e-179fc35787fe.png)

**Comment by bradleyrichter** [comment]
it also needs ellipses...

**Comment by luixxiul** [comment]
Pushed a PR to fix into

<img width="855" alt="screenshot 2016-12-08 2 48 55" src="https://cloud.githubusercontent.com/assets/3362943/20979946/055c5d22-bcf2-11e6-8eda-6ef6054f35de.png">

The link position has been fixed with #6009 already

**Comment by luixxiul** [comment]
Test plan:

1 Create the fake payment history following the steps described here: https://github.com/brave/browser-laptop/pull/4656#issue-182136102
2 Open about:preferences#payments
3 Make sure the link is placed under the monthly budget
