### ISSUE TITLE
Rebookmarking from context menu does not reset bookmark title

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4868]
**Describe the issue you encountered:** Rebookmarking does not reset the modified bookmark title to the default one.

**Expected behavior:** It should reset the bookmark title.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC3

- Steps to reproduce:
  1. Clear brave folder
  2. Open http://slashdot.org in a new tab
  3. "Add Bookmark" from context menu on Bookmark Toolbar with a modified title, like `test`
  4. "Add Bookmark" from context menu on Bookmark Toolbar again with the default title, which is `Slashdot: ...`
  5. The title remains `test`

- Any related issues:

**Comment by bsclifton** [comment]
Just a note- this does work as expected if the bookmark is removed and then re-added... just not for this situation. The reason it doesn't work here is because the title is preserved when moving a bookmark

**Comment by NejcZdovc** [comment]
This should be fixed with #9979

**Comment by srirambv** [comment]
QA blocked on #11728
