### ISSUE TITLE
~1GB Memory being used with 5 Tabs Open

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#4874]
**Did you search for similar issues before submitting this one?**
Yes, I am experiencing anomole's it seems others have not experienced to this level of severity
**Describe the issue you encountered:**
Slow Performance Due to >1024MB of Memory being used by numerous forks of brave.exe
**Expected behavior:**
No more than 100-200mb at least of Memory usage, with faster performance
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 7 x64
- Brave Version:
  0.12.4
- Steps to reproduce:
  1. Open tweetdeck.twitter.com, facebook.com, lawfare.com, github.com, Brave Prefs Tab in Brave 0.12.4 on Win 7 x64 OS. 
  2. Open taskman.exe to view the Amount of RAM being used and notice the screenshot that it is >1024MB
  3. Try to input text on either facebook.com or tweetdeck and observe the slow performance of the browser. If it is of any help, performing the same actions on OSX Yosemite with the same version of Brave, results in speedy performance. 
- Screenshot if needed:
  Processes: 
  ![2016-10-17 15_44_40-tweetdeck](https://cloud.githubusercontent.com/assets/470705/19455195/dc66cb34-9481-11e6-9abf-fd633119eb10.png)
  Brave Version Info:
  ![2016-10-17 15_42_26-windows task manager](https://cloud.githubusercontent.com/assets/470705/19455194/dc639536-9481-11e6-87d7-7daebb525499.png)
  Tabs: 
  ![2016-10-17 15_57_24-new issue brave_browser-laptop](https://cloud.githubusercontent.com/assets/470705/19455379/717ba0f0-9482-11e6-9c8c-ef0de19f3f6a.png)
- Any related issues: Less RAM Used, but #3836 is similar

**Comment by alexwykoff** [comment]
I just gave it a spin on my ia-32 VM and can see how that memory use is possible with video playing in a few tabs. 

@weems if you wouldn't mind aiding in the investigation, I'd like to know a few things:
1. In about:preferences#security, clear your cache and cookies.
2. Let me know if you have any pinned tabs.
3. Try the same in Chrome and see what their memory use is for the same sites and activities.

**Comment by BrendanEich** [comment]
All H.264 video? No Flash?

**Comment by weems** [comment]
@alexwykoff 1. Done. 2. I do not. 3. Seems to be about 300-450MB less on chrome.exe 


![Chrome Processes Memory Use](https://cloud.githubusercontent.com/assets/470705/19509229/647316d2-95a3-11e6-8a35-be59f0e8adc8.png)

**Comment by weems** [comment]
@BrendanEich No Videos I am aware of.

**Comment by luixxiul** [comment]
@weems do you experience the issue yet?

**Comment by luixxiul** [comment]
I'm going to close this in favor of https://github.com/brave/browser-laptop/issues/3836.
