### ISSUE TITLE
Trouble Logging In and Out of Twitter.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#4877]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
User is not able to easily log in, and out, of twitter.com.

**Expected behavior:**
Logging in and out is as easy as entering proper credentials, and/or clicking a button.

**Platform:** Windows 10

**Brave Version:** 0.12.5

**Steps to reproduce login issue:**
1. Visit https://twitter.com/login
2. Insert your credentials
3. Press [Login]
4. Note login failure

If you repeat the above steps numerous times, you will eventually succeed. I had to try about 6 times before I was able to gain entrance.

**Steps to reproduce logout issue:**
1. Click your image in the top-right
2. Select 'Log Out' from drop-down menu
3. Note that you are not logged out

If you repeat the above steps numerous times, you will eventually succeed. I had to try about 4 times before I was able to log out entirely.

**Any related issues:** #1124, #2243, #2247

**Comment by bbondy** [comment]
seems like no clearing cookies in some case, possibly related to https://github.com/brave/browser-laptop/issues/1323

**Comment by echosa** [comment]
I'm also experiencing this issue. Is there a way to clear specific cookies for specific sites?

**Comment by echosa** [comment]
FWIW: I was able to logout through TweetDeck and log back in through Imgur (I login to imgur with my Twitter account). In case that helps anyone as a work-around. :-P

**Comment by privatzee** [comment]
> Is there a way to clear specific cookies for specific sites?

@echosa You can use Devtools/Application

![image](https://cloud.githubusercontent.com/assets/22591438/19488068/55ee3170-9533-11e6-8ae7-27a59e25c0b0.png)

**Comment by DeltaZone** [comment]
The duplicate, closed issue (#5182) has some extra info, including that this is a problem on Linux too.

**Comment by DeltaZone** [comment]
Further on this, following the tips about trying several times, I now once - after perhaps 6-7 tries (I copied my password to the clipboard, the user name is remembered in the login form), pasting the password quickly and clicking on Submit, suddenly it "took" it, and I got a 2FA verfication code sent to my mobile. But when entering that code in the form, it seemingly accepts it, but then redirects me to the same login form with the error indicated in the url, but no error message. Refreshing the twitter page or visiting tweetdeck.twitter.com which should be logged in at this moment, reveals that I am not logged in. It seems that hitting the Submit button in most cases simply does not communicate or send anything to the server, it is disrupted and the error seems to stay locally in the browser.

Afterwards, I tried almost 10 times in a row again, this time with no luck at all, so I have given up.

**Comment by DeltaZone** [comment]
(and as indicated in the related, closed issue), the only setting I have adjusted is to allow scripts from Twitter - in the upper-right side drop-down panel - where I am still requiring HTTPS, Fingerprinting protection and Malware/Phishing protection)

**Comment by NogradThGin** [comment]
I have the same issue, on Archlinux 64bits daily updated, using github version of Brave.

It's the only problem i noticed since i switched from chromium to brave. Excluding this problem, this is a very nice browser, fast, clear, and simple.

**Comment by privatzee** [comment]
@DeltaZone If you want to experiment, you can try _Allow Ads and Tracking_ in that same lionhead panel. I can't test that myself because I don't have a Twitter account. But you're right in that doing so would allow more in than you'd like.

![image](https://cloud.githubusercontent.com/assets/22591438/19768058/c76e81a0-9c23-11e6-9b46-e413c2ac6a89.png)

Or maybe login fails because a cookie is blocked, but there is only the generic login-fail routine because Twitter didn't foresee blocker use.

Btw, I also use NoScript all the time. I assume they they here will eventually have Brave setup so that users can install any compatible browser extension.

**Comment by DeltaZone** [comment]
If it is indeed a cookie issue, then this Brave browser needs an interface we can use to administrate cookies. As far as I can see there is none? How do we delete cookies in Brave?

I am not going to allow Ads/Tracking "just to see" if it helps. One reason for me being curious about Brave is exactly that I want a browser that _never_ opened up that door at all for any site.

**Comment by DeltaZone** [comment]
Checking out the DevTools feature now regarding cookies. Reporting back.

**Comment by DeltaZone** [comment]
The cookie part via the DevTools does not make sense here, only 1 cookie and it is the current session which is needed. I just did one more thing: tried several times again until I got the 2FA code to SMS, then when using it and ending up on the login page again, I clicked the back button, got back to the window with the 2FA code, code also in the field, clicked again, got the login page again, back again, Submit again, 4-5 times, and then, just like with the password, I am now logged in "successfully", also in TweetDeck. It seems that the Twitter server does not notice the several failure clicks at all, only the ones that actually goes through (which then works as expected). Does not seem to be at risk of blocking myself out with too many tries, but not 100% sure about that part. 

Anyway, if this is a solution that works every day, it is at least possible to use this browser. I need it for Twitter among other things.

**Comment by DeltaZone** [comment]
Back again today, after closing and re-opening the browser, I needed to log into Twitter/TweetDeck again. This time it took only 3 tries to get the 2FA code via SMS, and then also only 3 tries back and forth with the one-time login code to get successfully logged in. 

PS. Can someone tell me why I lost my connection with Twitter during this browser "restart", but NOT here in Github, where I am still logged in when returning today? Just for my understanding.

**Comment by NogradThGin** [comment]
I don't know either. I tried to allow ads and tracking and all cookies, but no success for connecting to Twitter. Sadly.

**Comment by DeltaZone** [comment]
Back in after another browser shutdown. Still online here in the github tab, but not in TweetDeck/Twitter. This time it took roughly 10 tries to get a 2FA code via SMS, but only 3 attempts before that code actually "got through" and let me in. Seems to work every time, only with a difference in the number of tries needed.

**Comment by jonathansampson** [comment]
Thank you all for the assistance; we're actively investigating this issue, and hope to have it resolved in a timely manner. If you come across any other information that could help us better understand the issue, or workarounds, please do share it here. Thanks!

**Comment by DeltaZone** [comment]
Good. Last post by me here in this thread, just for the variance, in case it matters: When logging in today, it took 5 attempts to get the 2FA SMS, and then I got logged in on the 2nd Submit of the 2FA code.

**Comment by bcdady** [comment]
Symptoms reproduced on Win 7 64-bit in Brave 0.12.8, even with Shields Down.

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/7238)

**Comment by bcdady** [comment]
Perhaps ironically, after some persistence and random luck permitted me to get my account logged in to twitter, I can also update that this issue also seems related to the inability to log OUT of twitter.

**Comment by outragedhuman** [comment]
@bcdady I did try it several times based on your assertions, since I figured "hey, I really only need to log into this once every few days when I decide to switch accounts".

But unfortunately even multiple attempts didn't seem to do the trick. This is one case where Brave appears to be doing its job "too well" (which is fine, don't get me wrong, let's please err on the side of caution with this project) but it's just slightly un-usable for this and a few other reasons...for me...at this point.

**Comment by jonathansampson** [comment]
This issue appears to no longer exist in Brave 0.13.0. Closing, but if anybody notices any further issues, please feel free to notify somebody on the team and we'll re-open for investigation.
