### ISSUE TITLE
startup perf is poor on Windows

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#488]
Testing 0.7.10 build on Windows, it is the slowest of all of my installed browsers to launch. (And it shouldn't be, given the mostly empty profile.) Edge is blazing fast and a target to shoot for. I don't see this on Mac.

**Comment by scunliffe** [comment]
In full fairness, I wouldn't be at all surprised if Edge has a sizable chunk of its resources pre-loaded when Windows 10 starts.  Matching the speed of Chrome or Firefox may be reasonable, but matching Edge may be near impossible.

**Comment by luixxiul** [comment]
Closing this in favor of #3025
