### ISSUE TITLE
Favicons not loaded when bookmarks imported from browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4882]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Favicons not loaded when bookmarks imported from browser

**Expected behavior:**
Should load favicons irrespective how the data is imported

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.5 RC4

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![favicon](https://cloud.githubusercontent.com/assets/17010094/19463250/1024b7f4-9510-11e6-89b6-0ce9d20df11d.gif)

- Any related issues:

**Comment by darkdh** [comment]
they do exist in Bookmarks Manager but not Bookmarks Toolbar

**Comment by darkdh** [comment]
And chrome doesn't have favicon callback, that's on me.

**Comment by darkdh** [comment]
@srirambv , did you choose the bookmarks option to
<img width="328" alt="screen shot 2016-10-18 at 23 00 07" src="https://cloud.githubusercontent.com/assets/11330831/19504238/bd06ecdc-9586-11e6-94d3-645ad06260a4.png">
?

**Comment by srirambv** [comment]
@darkdh Manually added bookmarks on Chrome which are imported is not generating the favicons

![importfavicons](https://cloud.githubusercontent.com/assets/17010094/19548285/447cdb1a-96bb-11e6-935d-23ed9689ead0.gif)
