### ISSUE TITLE
[HackerOne] about: pages may be clickjacked

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4885]
they should have the frame-ancestors header
reported at https://hackerone.com/reports/175990

**Comment by luixxiul** [comment]
This fix disables a flash placeholder on y8.com, which was confirmed by @alexwykoff and @srirambv too.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19479895/b7a5f420-9583-11e6-87a0-7c123a0cae30.png)

Please look at the 2nd line there.

**Comment by diracdeltas** [comment]
great catch, fixing

**Comment by bbondy** [comment]
no easy fix for 0.12.5 so this is being moved to 0.12.6.

**Comment by srirambv** [comment]
Shows preferences page and not blank frame

![image](https://cloud.githubusercontent.com/assets/17010094/19561546/bb91c50e-96f6-11e6-9c9c-b8f9dd4cd3e6.png)

**Comment by diracdeltas** [comment]
@bbondy did this make it into the preview build?

**Comment by diracdeltas** [comment]
looks like it didn't, but it should be fixed on master so i'm closing this
