### ISSUE TITLE
URL input field on the bookmark pulldown disappears

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4897]
**Describe the issue you encountered:** the URL input field on the bookmark pulldown disappears by adding a character

**Expected behavior:** it should not disappear

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/4a7f1ac2b38c0666aee0271a39b4899178d77dd3

- Steps to reproduce:
    1. Bookmark https://github.com
    2. "Edit Bookmark" on the bookmark toolbar
    3. Select Location and add a character

- Screenshot if needed:

![bookmark](https://cloud.githubusercontent.com/assets/3362943/19478640/5646cb8c-957e-11e6-9826-2e47e1d2efdd.gif)

- Any related issues: #4726

**Comment by jkup** [comment]
Yikes food catch. Working on this now!

**Comment by luixxiul** [comment]
Another issue appears that the bookmark title automatically changes if you open the edited URL. I will open an issue for that.

**Comment by jkup** [comment]
It should be edit if you click the star on an already bookmarked page per the spec. Is that what you're seeing?

**Comment by luixxiul** [comment]
I opened an issue for that, will you please check it @jkup ?
