### ISSUE TITLE
Update app icons for non main release channel and make them distinguishable 

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#4898]
Icon resources can be found here
https://github.com/brave/browser-laptop/issues/4120

I'm just posting this task for the follow up from #4120

**Comment by luixxiul** [comment]
There are several reports beta and release channel icons look too similar to distinguish.

https://github.com/brave/browser-laptop/issues/10189#issuecomment-342112575

> ![image](https://user-images.githubusercontent.com/17010094/32437648-ee32f986-c2df-11e7-8aa0-ec3ac8bb4e7e.png)
> Its quite impossible to distinguish on Windows

**Comment by luixxiul** [comment]
I edited the title and added the milestone in case.

**Comment by bbondy** [comment]
cc @bradleyrichter

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/4898 (where @bradleyrichter provided the icons! 😄 )
