### ISSUE TITLE
target _blank opens up in new tab instead of new window

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#49]
Default behavior on Safari, Chrome and Firefox is to open in a new window

related https://github.com/atom/electron/issues/645

**Comment by EPadronU** [comment]
Greetings. I'm experimenting this issue currently with both, window.open and an anchor with target="_blank".

*about:brave*

Brave	0.12.10
Muon	1.4.26
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.7.8-1~bpo8+1
os.arch	x64

**Comment by bsclifton** [comment]
@EPadronU what exactly are you trying to figure out? (can you please explain more?)

This issue is pretty old- if you have a specific problem, I'd encourage you to create a new issue.  Thanks! :smile:

**Comment by EPadronU** [comment]
@bsclifton Done.
