### ISSUE TITLE
about pages logged in history by bookmarking them

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4900]
**Describe the issue you encountered:** about pages are logged in the history by bookmarking them.

**Expected behavior:** They should be avoided from being logged in the history.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: master branch

- Steps to reproduce:
    1. Clear your brave folder
    2. Open a new tab
    3. Bookmark it via the star button
    4. Click "New Tab" on the bookmark toolbar
    5. Open another new tab

And you will get this:

<img width="389" alt="screenshot 2016-10-19 0 26 38" src="https://cloud.githubusercontent.com/assets/3362943/19484731/89750fb8-9593-11e6-88c2-e8622ab9ebf4.png">

The star icon is blank in the picture just because I have removed the bookmark, so please ignore it.

- Any related issues: #4726

**Comment by luixxiul** [comment]
@bsclifton would you please take this one?

**Comment by Sh1d0w** [comment]
@luixxiul I can't reproduce this on latest master: http://webm.land/media/h2QG.webm

**Comment by bbondy** [comment]
moved to 0.12.7

**Comment by bbondy** [comment]
@luixxiul can you still reproduce this?

**Comment by luixxiul** [comment]
no, it seems it has been fixed, closing.

**Comment by Sh1d0w** [comment]
Just checkouted the latest master https://github.com/brave/browser-laptop/commit/af38d76dced4a1124762a12377340c1a925c1989

Here is a video how I reproduce this. Today is 26th of October, I only see entries from yesterday 25th of October when I navigate:

http://webm.land/media/Kgjk.webm

**Comment by Sh1d0w** [comment]
Whops this is related to another ticket. Sorry.
