### ISSUE TITLE
documentation: how to use testnet faucet for Brave Payments development

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4905]
We should create a wiki page to explain how to use testnet faucet for Brave Payments development, which was posted here: https://github.com/brave/browser-laptop/pull/4297#issuecomment-250875230

> Test plan:
> 1. Clear local Ledger data
> 2. Check in browser if my unreliable testnet Ledger server is available: http://ledger-testnet.entropi.info/documentation
> 3. If it is, run Brave with `LEDGER_SERVER_URL=http://ledger-testnet.entropi.info'
> 4. Open Preferences->Payments
> 5. Confirm Wallet can be created
> 6. Grab wallet address (from Add Funds)
> 7. Visit a testnet faucet (https://testnet.manu.backend.hamburg/faucet)
> 8. Confirm testnet bitcoin can be transferred to address
> 
> for #4286

cc: @willy-b

**Comment by willy-b** [comment]
Thanks for opening this @luixxiul !

Added at https://github.com/brave/browser-laptop/wiki/Using-Brave-Payments-with-Testnet-Bitcoin .

LMK what you think, what else could / should be added, etc.

**Comment by luixxiul** [comment]
Thanks @willy-b, I have not tested yet but is it possible to set the env variables with System Property on Windows Control Panel? If so, I think it is worth mentioning ;-)

**Comment by mrose17** [comment]
@willy-b & @luixxiul - can we close this issue now? thanks!

**Comment by luixxiul** [comment]
pinging @willy-b for WIndows instruction.

**Comment by willy-b** [comment]
Hey @luixxiul, the environment variables will work the same on Windows, but let me grab a VM and go through the steps to make sure there aren't any surprises.

It'll take a little while to download the Windows VM from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines , but as soon as I have it I'll update the instructions! (I confess: I have not been testing on Windows recently >_<.)

Thanks!

**Comment by bsclifton** [comment]
Hey there @willy-b! :smile: I wanted to follow up regarding this and ask if you had an update? Anything I can help with?

**Comment by willy-b** [comment]
hey @bsclifton, I'm going to need to deprecate this wiki entry for all platforms because the ledger server has been changing and I don't think it supports testnet anymore. Also, for financial/time reasons I had to shutdown the testnet ledger server I was running in AWS.

So let me update the wiki tonight noting that this code is stale and that there's no longer a testnet server to test against (unless you guys run one).

**Comment by willy-b** [comment]
Sorry for the long delay in updating this issue. I ran the VM and then saw the Ledger code had been updated and the previous docker deployment I had written was broken. Went to play catch up and saw the testnet was no longer supported in Ledger, and so on, and then realized I can't afford to maintain the testnet compatibility and server at this time as a random outsider.

**Comment by willy-b** [comment]
Updated the wiki page to note that it is out of date:
https://github.com/brave/browser-laptop/wiki/Using-Brave-Payments-with-Testnet-Bitcoin

One needs to run their own testnet ledger server which may require some changes (client-side still works)

**Comment by bsclifton** [comment]
thanks, @willy-b :smile: I think we can close this issue then. The link you provided meets the needs; if we'd like to update it, we can do so there in the wiki
