### ISSUE TITLE
regression: double-clicking of entries on about:history opens a blank new tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4909]
**Describe the issue you encountered:** Double-clicking of entries on about:history opens a blank new tab

**Expected behavior:** it should open a page correctly

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5

- Steps to reproduce:
    1. Open about:history
    2. Double-click any entry

- Any related issues:

**Comment by bbondy** [comment]
cc @bsclifton
