### ISSUE TITLE
Additional idea to the Bravery sub menu options

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#491]
Would be good to have that in the right mouse context menu too, so if the user wants to support a page with replacement ads, it would be good if he/she could do that with a simple mouseclick without going first to the hamburger button and then to Bravery sub-menu.

Or perhaps add all those Bravery menu options into the right mouse context menu, way faster than navigating to the sub menu in my opinion.

**Comment by bradleyrichter** [comment]
Agree. Let's get them into the contextual menu for non-links and non-selection  (open page area)

**Comment by bradleyrichter** [comment]
@SJ-Diamond LMK what you think about the new Bravery panel and the removal of the Bravery menus. They introduced some plumbing headaches and latency so they are removed for now.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-additional-idea-to-the-bravery-sub-menu-options/10061

Let's keep discussion there to see what users would like to see inside the shields. Once we receive enough information and have an idea to make this suggestion realizable, let's reopen this 👍
