### ISSUE TITLE
[HackerOne] access-control-allow-origin: * set on about: pages

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4913]
## Test plan

https://github.com/brave/browser-laptop/commit/186113ea9e603c7ed9062d0b92c2285a612caaeb

----

reported along with #4885

**Comment by srirambv** [comment]
Only step1 mentioned in https://github.com/brave/browser-laptop/commit/186113ea9e603c7ed9062d0b92c2285a612caaeb passed 
#4885 steps fails

**Comment by diracdeltas** [comment]
This regressed with dbc07962d92d5bf73d5b835e0f5fe01830ff1d67. cc @bridiver

**Comment by bridiver** [comment]
if this is the issue https://github.com/brave/browser-laptop/commit/dbc07962d92d5bf73d5b835e0f5fe01830ff1d67#diff-11e9f7f953edc64ba14b0cc350ae7b9dR82 it is development only for webpack so I don't think the security issue really applies

**Comment by diracdeltas** [comment]
@bridiver the issue is https://github.com/brave/browser-laptop/commit/dbc07962d92d5bf73d5b835e0f5fe01830ff1d67#diff-a533e12744082c16911d52f54573e441R133 and it's in the released builds

**Comment by bridiver** [comment]
yea, I don't think any of those pages need to be in there
