### ISSUE TITLE
Implement Services on macOS

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4915]
Implement Services on macOS/OS X.

As an example, here's a list of Services in the pulldown menu of Sublime Text on the system toolbar.

<img width="565" alt="screenshot 2016-10-19 3 01 55" src="https://cloud.githubusercontent.com/assets/3362943/19490042/865543d8-95a8-11e6-9d67-301e0a3ee650.png">
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: 0.12.5
- Any related issues:

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6397

**Comment by jonathansampson** [comment]
+1 from Twitter: https://twitter.com/themikebwebb/status/840046952293122048
