### ISSUE TITLE
Add support to disable WebM video format

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#4916]
From support: https://linkbubble.zendesk.com/agent/tickets/5619

> If I’m watching something on youtube.com in Brave, the CPU fans will be one constantly and the video will be a slide-show. Using H.264 (Firefox, Safari) will be perfect quality 1080p at ~5% CPU load.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-does-webm-format-video-consume-much-cpu-resource/10120

Let's reopen this issue after we receive other reports there 👍
