### ISSUE TITLE
Suggestion: Add option to disable videos autoload

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#4917]
From support: https://linkbubble.zendesk.com/agent/tickets/5614

Sites like MSN autoloads videos. User suggested to have an option to disable it.

**Comment by Sh1d0w** [comment]
Do you mean autoplay or autoload? I have opened a similar issue a while ago https://github.com/brave/browser-laptop/issues/4045

**Comment by cezaraugusto** [comment]
oops yes, you're correct, thanks @Sh1d0w 

closing in favor of #4045
