### ISSUE TITLE
Account balance: error, can't retrieve data

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#4920]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Open payment window to see my account balance and I see this: error, can't retrieve data

**Expected behavior:**

See my account balance
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 64
- Brave Version: Brave: 0.12.5
- Screenshot if needed:
  ![captura de tela de 2016-10-18 20-19-29](https://cloud.githubusercontent.com/assets/1178856/19499140/9a68253c-9573-11e6-8722-e76916480bd7.png)
- Any related issues:

**Comment by bitcoinuser** [comment]
Now I see the account balance. Didn't need to restart Brave,

**Comment by luixxiul** [comment]
The message "error, can't retrieve data" is not user-friendly btw. It would be worth showing the kind of error (database corruption, network, etc). /cc: @mrose17

**Comment by oscarspaz** [comment]
I have the same error and do not know what to do next. Is there a way to reset it?

Brave 0.12.5
Electron 1.4.14
libchromiumcontent: 53.0.2785.143
v8:5.3.332.47
Nodejs 6.5.0
Update Channel dev

Win 7 64bit

**Comment by mrose17** [comment]
@ayumi - can we add some context to this, as @luixxiul suggests?
