### ISSUE TITLE
Clicking the hamburger menu a second time should close the menu

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#4921]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Clicking the hamburger menu a second time should close the menu but it re-opens it instead

**Expected behavior:** Menu should close on second click
- Platform (Win7, 8, 10? macOS? Linux distro?): WIndows 10
- Brave Version: 0.12.5
- Steps to reproduce:
  1. click the hamburger menu
  2. click the menu a second time
  3. observe the menu close and re-open
- Screenshot if needed:
- Any related issues:

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6405 which was merged into branch `0.13.1-branch`.
