### ISSUE TITLE
double click in addressbar maximizes/restores the window instead of selecting the address

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#4922]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Sometimes when I place the mouse pointer in the bottom part of the addressbar and double-click to select the address, rather than selecting the address, the window is maximized/restored. This is because the pointer tip can be several pixels into the bottom of the addressbar and still targeting the toolbar below the addressbar. 

**Expected behavior:** When the pointer is visibly inside the addressbar and clicked it should focus the addressbar or turn into an i-beam cursor for text selection. 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.5
- Steps to reproduce:
  1. with the window maximized move the mouse pointer into the bottom 20% or so of the addressbar
  2. double click
  3. see the window restored

**Comment by bbondy** [comment]
Thanks for the bug report!

@bsclifton this is windows only, probably related to the titlebar removal. Could you take?

**Comment by bsclifton** [comment]
The fix for this was included in 0.12.6... but it ended up causing a drag regression: https://github.com/brave/browser-laptop/issues/5225

Re-opening issue as it will be broken again if/when https://github.com/brave/browser-laptop/pull/5240 is accepted

**Comment by luixxiul** [comment]
@bsclifton has this issue been resolved?

**Comment by bsclifton** [comment]
@luixxiul I don't believe so, no.  This was not hitbox related, but related to how the textbox is labelled with CSS (see above PR which broke it).

**Comment by luixxiul** [comment]
yes I got it, I think I found a way of solving this. I'm working on it.
