### ISSUE TITLE
Bookmark title automatically changes on the bookmark form

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4929]
**Describe the issue you encountered:** Bookmark title automatically changes on the bookmark form, if you edit the bookmarked URL, open it, and edit the bookmark again.

**Expected behavior:** It should either preserve the original title or renew it based on the title of the page of the edited URL.
- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: https://github.com/brave/browser-laptop/tree/fc14b2ed23e23dd90d518766321324a1e79a2e90
- Steps to reproduce:
  1. Bookmark `https://github.com/notifications`
  2. Change Location via "Edit Bookmark" on the bookmark toolbar to `https://github.com/notificationsa`, which should lead to 404 error
  3. Click the bookmark
  4. "Edit Bookmark"
  5. The title was changed to `Page not found · GitHub`
- Any related issues: #4897

**Comment by luixxiul** [comment]
I'm not sure if it works right now as it should.

**Comment by NejcZdovc** [comment]
Should be fixed with #9978
