### ISSUE TITLE
Closing tabs quits the browser

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4931]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has reported that closing tabs quits the browser. I am assuming that they did not close all tabs, but rather they closed a tab and the browser quit unexpectedly.

**Expected behavior:**
If the tab is not the final tab, the browser should remain open.

- Platform (Win7, 8, 10? macOS? Linux distro?):
The user was on Ubuntu 16.04

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://linkbubble.zendesk.com/agent/tickets/5998

**Comment by bbondy** [comment]
Don't assume it was not the last one, please ask, thanks.
I don't think I've ever heard of, or seen this before.

**Comment by alexwykoff** [comment]
Did ask, turns out it was a user education issue. :)
