### ISSUE TITLE
Feature Request : more trackpad gesture features

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4933]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support is asking for more trackpad gestures (pinch to zoom, etc)

**Expected behavior:**
A user should be able to use trackpad gestures to zoom and navigate.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
`> 0.12.5`

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://linkbubble.zendesk.com/agent/tickets/6034

**Comment by alexwykoff** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/6165

**Comment by bbondy** [comment]
dupe of https://github.com/brave/browser-laptop/issues/1364 ?

**Comment by alexwykoff** [comment]
Indeed it is, closing.
