### ISSUE TITLE
fuzzy.ai listing investigation

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4938]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user in support has noted that fuzzy.ai is currently being blocked via our phishing/malware filter but believes it to be in error.

**Expected behavior:**
There should be some relatively simple means of determining why a site has been blocked and if they are the owner of the site, how to remedy the situation.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
` > 0.12.5`

- Steps to reproduce:
    1. Visit fuzzy.ai
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Fixed here:
https://github.com/bbondy/abp-filter-parser-cpp/commit/e9fbeef5a9b33e6107b6ad694e10bf550d7b49a0

Should be live within a day.
