### ISSUE TITLE
Setting Brave as default from the startup check on Linux doesn't work

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4939]
Clicking on "Use Brave" does not work at all under Linux (Fedora 24 and Ubuntu). Also if I manually set Brave as default browser the check popup still appears, despite the fact that Brave is my default browser.

In order to implement this please see the man page for `xdg-mime` https://linux.die.net/man/1/xdg-mime

To check if brave is the default browser on the system:

    xdg-mime query default text/html 
    xdg-mime query default x-scheme-handler/http
    xdg-mime query default x-scheme-handler/https

If the output of these commands is not `brave.desktop` then to set is as default scheme handle do the following:

    xdg-mime default brave.desktop text/html 
    xdg-mime default brave.desktop x-scheme-handler/http
    xdg-mime default brave.desktop x-scheme-handler/https

cc @bbondy @darkdh

**Comment by darkdh** [comment]
@Sh1d0w which electron version do you have?

**Comment by Sh1d0w** [comment]
@darkdh <img src="https://s9.postimg.org/6skypdkv3/Screenshot_from_2016_10_19_08_48_33.png"/>

**Comment by darkdh** [comment]
@Sh1d0w you should upgrade it to at least 1.4.15+ which will contain https://github.com/brave/electron/commit/016f5646b0fab8b7d68ca9aed7585f4b02e4d65d

**Comment by Sh1d0w** [comment]
@darkdh Sorry. `npm install` downloads and installs electron 1.4.14, I did not know that I need 1.4.15 in order to this to work. Closing.

**Comment by bbondy** [comment]
if you node_modules already exists and contains a ref to 1.4.14 I think it just re-installs that same version, I find just clearing node_modules before npm install works better.  You can also use npm update electron-prebuilt and it might work.

**Comment by Sh1d0w** [comment]
@bbondy Yes I learned that the hard way :D thanks
