### ISSUE TITLE
Feature Request : Open home page (in new tab) with Ctrl + Home

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4940]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has requested that we add this keyboard shortcut.

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6113

**Comment by jonathansampson** [comment]
Closing as dupe of #7718.
