### ISSUE TITLE
Selecting and Cutting the UrlBar text reverts the text back

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4941]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Selecting and cutting the whole url in the url bar restores it back.

**Expected behavior:**

The url bar should remain empty

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux

- Brave Version: https://github.com/brave/browser-laptop/commit/497ecf8679e0bc14ae7d1e05e38f3b5a00733071

- Steps to reproduce:
    1. Open a website
    2. Hit CTRL+L -> CTRL+A -> CTRL+X
    3. Observe the text you have just cut restores back.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/4219

**Comment by privatzee** [comment]
same W7x64

**Comment by diracdeltas** [comment]
can't seem repro on mac with CMD+L, CMD+A, CMD+X

**Comment by Sh1d0w** [comment]
@diracdeltas It seems it's Linux and Windows issue only then. Here is video: http://webm.land/media/4fqH.webm

**Comment by bbondy** [comment]
@alexwykoff @srirambv @luixxiul can you reproduce?

**Comment by alexwykoff** [comment]
works on os x

**Comment by alexwykoff** [comment]
works on ubuntu as well

**Comment by Sh1d0w** [comment]
@alexwykoff Are you following the STR in the video http://webm.land/media/YLmC.webm and the original issue as described? It is very strange because I updated to 0.12.6-Preview 2 this morning and I can still reproduce the problem:

1. Open a website
2. CTRL+L 
2. CTRL+A
3.CTRL+X
4. The text reverts back

**Comment by alexwykoff** [comment]
Ah, I was using the context menu. Command+L -> Command+X reproduces the issue. No need for Command+A on mac

**Comment by srirambv** [comment]
Reproducible on Windows build. Ctrl+A not required as @alexwykoff mentioned.

**Comment by Sh1d0w** [comment]
@diracdeltas @bbondy I am very sorry to reopen this, but can I ask you to revert the commit. Nice fix, but I am asking because I fixed this as well as several other bugs in general in https://github.com/brave/browser-laptop/issues/5025

@diracdeltas can you review my PR and if you decide it is not good enough please leave your commit and close mine. Otherwise please move this issue for the next milestone, when my PR can get merged.

**Comment by Sh1d0w** [comment]
@bbondy Advised me to rever the commit in another branch and to cherry-pick my PR there.

Closing.

**Comment by bbondy** [comment]
Yep I asked to please revert in another branch, apply his fix, then squash into one for 0.12.7, and then PR it and ask @diracdeltas for review. Thanks!

**Comment by Sh1d0w** [comment]
For the record here is the new PR:

https://github.com/brave/browser-laptop/pull/5046

**Comment by diracdeltas** [comment]
@Sh1d0w to avoid duplicate work in the future, please self-assign an issue when you start it. thanks

**Comment by Sh1d0w** [comment]
@diracdeltas Yes sorry. My attention wasn't to fix this issue in practicular, but it turned out after I fixed the other one this was resolved as well when I tested :)
