### ISSUE TITLE
https://weather.gc.ca/radar/index_e.html?id=wkr never finishes loading

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4945]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support alerted us to the fact that https://weather.gc.ca/radar/index_e.html?id=wkr never finishes loading in Brave. I have replicated this with shields down. Chrome works without issue.

**Expected behavior:**
The page should finish loading and display the appropriate info.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Tested on OS X
- Brave Version:
  0.12.5
- Steps to reproduce:
  1. Visit https://weather.gc.ca/radar/index_e.html?id=wkr
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6254

**Comment by willy-b** [comment]
Loads fine for me with default settings on:
-  0.12.3 prepackaged build on Linux (Ubuntu 14.04 LTS) 
-  0.12.5 dev build from Git

**Comment by privatzee** [comment]
I do get endless loading on W7x64. Also:

- can't stop it loading with the x next to location bar, nor with escape key
- can't reload with ctrl+r nor F5
- can't scroll by dragging scrollbar, but can scroll with mouse wheel
- no links are clickable

**Comment by srirambv** [comment]
I can't get the Dev tools open on this page in Windows 10. Neither by shortcut nor by menu

**Comment by privatzee** [comment]
Devtools opened on W7x64 via F12 (or ctrl+shift+i, or menu), but it was not working and did not show URL in Title Bar. But _minutes_ later this error appeared:
`Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError`

**Comment by privatzee** [comment]
`Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError `
is also here: 
#1963
#1366

**Comment by butlermatt** [comment]
For the record, I'm having the same issue with Brave 0.12.10 x64 on MacOS (10.12.1).

However unlike @privatzee, even after an hour the error does not appear in and the page remains "stuck" still trying to load, never cancelling/stopping

**Comment by luixxiul** [comment]
FYI the site is loaded for me properly.

For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-info-error-on-phpmyadmin-failed-to-clear-temp-storage/10950

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
