### ISSUE TITLE
Brave uses the wrong location for its Cache folder on macOS, bloats Time Machine backups

### ISSUE THREAD

**Issue by mikl** [brave/browser-laptop#4947]
**Did you search for similar issues before submitting this one?**

Yes, I couldn't find any.

**Describe the issue you encountered:**

Brave stores it's cached data in `~/Library/Application\ Support/brave/Cache`, which is backed up by Time Machine when it runs (by default every hour). Since the cache changes often, a new copy of one or more of its files is taken by almost every Time Machine snapshot.

In my experience, Brave cache alone adds around 200 MB to every backup, meaning that it consumes a couple of GB extra backup space every day, completely needlessly, since I'll never need to restore them from backup.

**Expected behavior:**

Caches should be stored in `~/Library/Caches/`, since this location is automatically excluded from backup.

Other browsers already do this, Firefox uses `~/Library/Caches/Firefox`, Safari uses `~/Library/Caches/com.apple.Safari`
- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS (all versions)
- Brave Version:

0.12.5
- Steps to reproduce:
  1. Use Brave
  2. Use TimeTracker or similar to see how much space each backup uses.
  3. Despair at the amount of storage Brave is consuming needlessly.
- Screenshot if needed:

Several hundred megs of cache in a single Time Machine snapshot.

![screen shot 2016-10-19 at 13 06 36](https://cloud.githubusercontent.com/assets/10263/19517136/a7fceebc-95ff-11e6-8d72-a38bb28296b4.png)

**Comment by bbondy** [comment]
nice find, thanks for the report.
