### ISSUE TITLE
UK Parliament videos are being blocked.

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#4948]
https://www.parliament.uk/about/podcasts/

From the above page, clicking through to one of the video pages (e.g. "Westminster Hall") displays the page but blocks the video:
![image](https://cloud.githubusercontent.com/assets/15019644/19517643/5cbd3b14-95fa-11e6-88a6-642400d13ff5.png)

Dropping shields did not reveal the videos. Videos showing as expected in Chromium.

Presumably this is a symptom of a more general problem possibly associated with regions.

Ubuntu 16.10
Brave: 0.12.5
Electron: 1.4.14
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by privatzee** [comment]
This is yet another "Mixed Content" error, of which there are more than a few showing up. There is seemingly something wrong with HTTPS Everywhere. 

![image](https://cloud.githubusercontent.com/assets/22591438/19522894/c6e00c60-95e6-11e6-9765-f79e3b469f26.png)

**Comment by diracdeltas** [comment]
it appears the site has fixed the issue and now https://www.parliament.uk/about/podcasts/video-tours/westminster-hall/ appears fine
