### ISSUE TITLE
CNET video blocked

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#4953]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
CNET embedded videos don't play. They have preroll ads so that could be involved.

**Expected behavior:**
Editorial video should play with preroll and midroll ads skipped

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12

- Brave Version:
0.12.5

- Steps to reproduce:
    1. load https://www.cnet.com/news/cartoon-trump-late-show-stephen-colbert/
    2. scroll down to the big black rectangle where the video is supposed to be

- Any related issues:
I think this is separate from https://github.com/brave/browser-laptop/issues/293

**Comment by luixxiul** [comment]
I think this is a dupe of #293. Would you please try again after disabling the Bravery shields? Thanks.

**Comment by stshank** [comment]
With shields down, the video and preroll ad both play.

I thought #293 was separate because it seems to be specifically about an adblock message, which I didn't see.

**Comment by luixxiul** [comment]
Ah sorry, I missed you mentioned it already..

**Comment by bbondy** [comment]
Duped to here since it was fixed there:
https://github.com/brave/browser-laptop/issues/4442
