### ISSUE TITLE
Feature Request: BetterTTV Extension for Twitch

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#4956]
**Did you search for similar issues before submitting this one?**
Yes

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/betterttv/ajopnjidmegmdimjlfnijceegpefgped
https://www.nightdev.com/betterttv/

**What do you like about the extension?**
This is a very common extension for viewing Twitch streams. It adds dark mode, better chat abilities, custom emotes, and so much more.

**Comment by bsclifton** [comment]
BetterTTV is already being tracked in https://github.com/brave/browser-laptop/projects/1

I updated notes referencing this and the PR submitted. Closing issue
