### ISSUE TITLE
hide or disable the reload and bookmark buttons on about:blank new tab

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#496]
When I open a new tab, reload and bookmark should not be active choices in the addressbar. It doesn't make sense to reload a blank tab. Hide or disable reload and bookmark buttons for a cleaner and more functional toolbar.

**Comment by bbondy** [comment]
reload / stop handled as part of https://github.com/brave/browser-laptop/commit/bb0d5ef655458c89303591ef040e7d9901c88030

Leaving this open until bookmark is also handled.
