### ISSUE TITLE
SAML/SSO logins and Redirects dont work

### ISSUE THREAD

**Issue by kumzme** [brave/browser-laptop#4961]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Some of main websites work with SAML/SSO authentication and there are automatic redirects. I am unable to login to such sites.

**Expected behavior:**
Should allow legit re directs for SSO. [Not every dev site or QA or prod site will be having same sub domain for redirected addresses.]
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/do-saml-sso-logins-and-redirects-not-work/10222

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
