### ISSUE TITLE
Brave can't get installation complete of associated tool

### ISSUE THREAD

**Issue by p-fernandez** [brave/browser-laptop#4962]
**Describe the issue you encountered:**

New update can't get totally installed.  Keeps asking for permissions to install an associated tool.
- Platform (MacOSx: v.10.11.6)
- Brave Version: 0.12.5dev

![captura de pantalla 2016-10-19 a las 21 46 40](https://cloud.githubusercontent.com/assets/18152036/19534816/ac0a50e4-9645-11e6-8137-85fd36944873.png)

**Comment by p-fernandez** [comment]
Took half an afternoon to complete installation. Haven't got the advise anymore. I close the issue.

**Comment by p-fernandez** [comment]
Happened again this morning when opening the browser again from start.

**Comment by Liunkae** [comment]
I don't think this is happening anymore. No recent reports, so I'll close for now.
