### ISSUE TITLE
Findbar clear button isn't working

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#4965]
**Did you search for similar issues before submitting this one?**
Yes. Did not find anything.

**Describe the issue you encountered:**
Clicking on the findbar clear button doesn't do anything. This worked fine through 0.12.3 but stopped working in 0.12.4. 27bd13f probably caused this issue. cc: @diracdeltas

**Expected behavior:**
The clear button clears all the text in the findbar.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12

- Brave Version:
0.12.4, 0.12.5, and 0.12.6 dev preview 1
- Steps to reproduce:
    1. Open Brave and navigate to any website.
    2. Open the findbar with Ctrl/Cmd+F.
    3. Type some text in the findbar.
    4. Click the clear ("X") button.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/19540278/d254d1e2-9623-11e6-8b9d-57cd08d126f5.png)
The "X" button in the screenshot is not working.

- Any related issues:
None.

**Comment by diracdeltas** [comment]
@jkup @bradleyrichter is this close button even necessary anymore, given that there's another close button on the findbar in the far right?

**Comment by Liunkae** [comment]
@diracdeltas The button I'm talking about is the _clear_ button, not the _close_ button. This button is _supposed_ to clear the find text so another search can be performed. The close button in the far right _closes_ the entire findbar for when you are done searching.

**Comment by diracdeltas** [comment]
@Liunkae my bad, i guess i never use either of those buttons

**Comment by alexwykoff** [comment]
moved to 0.12.7

**Comment by jkup** [comment]
@alexwykoff is it too late for this to be included in 12.6? The PR is up.

**Comment by Liunkae** [comment]
Since we already have a fix for this bug, I also request that this be included in 0.12.6.
