### ISSUE TITLE
rename "New Partitioned Session" to "New Session Tab" 

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#497]
Partitioned and Session feel redundant. A New Session is presumably partitioned and regular folks won't get the current label.  Also, it will match the other labels better :-)

**Comment by bbondy** [comment]
Good idea, will do.

**Comment by asadotzler** [comment]
Probably want this on the link context menu too.

**Comment by bbondy** [comment]
Oops, forgot we had it there. Good catch
