### ISSUE TITLE
[support] invalid homepage URL causes 'uncaught typeerror'

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#4974]
from https://linkbubble.zendesk.com/agent/tickets/6219:

1. set homepage to https://brave.com;https://google.com.vn 
2. restart browser

reporter says browser is stuck in a blank state, but i only see this error in the console:
```
urlutil.js:158Uncaught TypeError: Failed to construct 'URL': Invalid URL
```

**Comment by srirambv** [comment]
The issue is when you set the homepage as https://brave.com;https://google.com.vn and then change the setting to launch brave with homepage. 

![homepageerror](https://cloud.githubusercontent.com/assets/17010094/19560362/d31ad10c-96f1-11e6-8895-161a6018e056.gif)

**Comment by diracdeltas** [comment]
this didn't make it into the build either. we should keep issues closed when the code exists on master even if the last RC build doesn’t have the fix
