### ISSUE TITLE
Count of visits not applied to bookmarked websites

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4976]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Lately I've been testing https://github.com/brave/browser-laptop/issues/3049 . Great stuff but I've found another bug. If you visit a bookmarked website the count attribute is not applied for some reason no matter how much times you visit it.

**Expected behavior:**

Every visit to a website should properly increase the count attribute of each history entry eigther being typed by hand, visited from bookmark or from redirect.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version: 0.12.6

- Steps to reproduce:
    1. Delete session-store-1 to make sure everything is clear
    2. Open github.com and bookmark it instantly
    3. Close the browser and inspect session-store-1
    4. Open the browser again and visit github.com several times
    5. Close the browser and inspect session-store-1

- Screenshot if needed:

- Any related issues:

**Comment by aekeus** [comment]
I confirmed this, moving to next milestone.

**Comment by aekeus** [comment]
Closed via c871c542344b14813baae8bda4fe311e8496f7a9
