### ISSUE TITLE
Provide an option to disable "Top Sites" in autocomplete

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4977]
## Test plan

https://github.com/brave/browser-laptop/pull/9063#issue-231507264

----

**Expected behavior:** Provide options to disable show Top Site and Brave Pages in "Search Bar Options" on `about:preferences#search`

<img width="268" alt="screenshot 2016-10-20 13 33 39" src="https://cloud.githubusercontent.com/assets/3362943/19546337/e0c6d864-96c9-11e6-8928-d6e401527525.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X
- Brave Version: https://github.com/brave/browser-laptop/tree/8a174b537d75009585292ac4f7feb9354de3bbcc
- Any related issues:

**Comment by bsclifton** [comment]
Removing this from the milestone; let's work with @bradleyrichter or @bbondy if we want to reassign it into a milestone

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/disable-top-sites-in-url-bar/930

**Comment by bradleyrichter** [comment]
we just need to provide one more toggle here:

![image](https://cloud.githubusercontent.com/assets/13509546/22433670/0315fe96-e6ce-11e6-8d81-c910f4cb73b5.png)


"Show top site matches"

**Comment by bsclifton** [comment]
preloaded site complaints captured here with https://github.com/brave/browser-laptop/issues/7655 and https://github.com/brave/browser-laptop/issues/5892; the behavior will be resolved with https://github.com/brave/browser-laptop/issues/7717

Let's use this issue to discuss turning off the "Top Sites" feature

**Comment by ayumi** [comment]
+1
