### ISSUE TITLE
bookmark cannot be deleted from the panel if location is changed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4978]
**Describe the issue you encountered:** bookmark cannot be deleted from the panel, if location is changed at the same time.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.12.5

- Steps to reproduce:
  1. Bookmark https://github.com
  2. Edit bookmark from the bookmark toolbar
  3. Add some characters to the location like https://github.coma **(do not save)**
  4. Click `Remove`

Expected Result: The bookmark should be removed

Actual result: The bookmark is not removed

**Comment by luixxiul** [comment]
posting it being not sure if it works as it should.

**Comment by srirambv** [comment]
I can't repro the steps. However I did see that the location still shows as Bookmark folder rather than the new location.

**Comment by luixxiul** [comment]
@srirambv did you save the edited location?

**Comment by srirambv** [comment]
Yes

**Comment by luixxiul** [comment]
@srirambv will you try without saving it? I forgot to mention it.

**Comment by srirambv** [comment]
@luixxiul Yes without saving the bookmark remains in the toolbar.

**Comment by NejcZdovc** [comment]
@luixxiul @srirambv can you please retest this in version 0.19?

**Comment by NejcZdovc** [comment]
Should be fixed with #9710
