### ISSUE TITLE
Autocomplete is not very accurate and yields wrong results

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#4979]
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**

When I type in the Url bar I don't get the most relevant results that I should get.

I demonstrate this in the following video: http://webm.land/media/n5dh.webm

1. I started to type `ve` . The one and only website that I have visited and starts with `ve` is `vesti.bg` . But as you can see I get irellevant results from `developer.chrome ....` because it contains `ve` but it is in the middle of the word and I have visited it recently than `vesti.bg`.

The correct result appears if I continue to type and there are no other matches in the history, e.g. if I type `ves`.

This is probably related to https://github.com/brave/browser-laptop/issues/4955 , but I think it has to be fixed in this milestone, because the wrong behaviour is also intorduced in this milestone. If you think this is duplicate report of https://github.com/brave/browser-laptop/issues/4955 please close the issue.

**Expected behavior:**

I should get accurate results. The check for a matching and order the results by exact domain name match, rather than random occurences in the domain name.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version: 0.12.6

- Steps to reproduce:
    1. As stated above

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/3049
https://github.com/brave/browser-laptop/issues/4955

**Comment by wmeyer48** [comment]
I have noticed a great deal of difficulty manually typing the URL in the latest update (0.12.5). Turning off the history match eliminates the difficulty, so I would have to guess you need to do some serious optimization in that area. The observed behavior is dropped keystrokes, so youtube might become yotue. Not pleasant.

**Comment by Sh1d0w** [comment]
@wmeyer48 The problem with the disappearing characters is reported and fixed in v.0.12.6. Just wait a little bit more to be released :)

**Comment by aekeus** [comment]
I think this is duplicate, so closing. Please re-open if the next preview release has the same issue.
