### ISSUE TITLE
Brave crashes when Copy recovery key is clicked during wallet creation

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4980]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave crashes when Copy recovery key is clicked during wallet creation

**Expected behavior:**
Should not crash. Advance button should not be enabled until wallet is created

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 Preview 1

- Steps to reproduce:
    1. Do a clean install of the 0.12.6 Preview 1 build
    2. Enable payments 
    3. While the wallet is being created, click on advance settings and click on backup your wallet
    4. Click on either of the copy button, Brave crashes

- Screenshot if needed:
![paymenterror](https://cloud.githubusercontent.com/assets/17010094/19547988/37210d76-96b9-11e6-9c87-7cc64d2bdcc2.gif)

- Any related issues:

**Comment by bbondy** [comment]
This is P1 please

**Comment by alexwykoff** [comment]
DNR on osx and ubuntu

**Comment by mrose17** [comment]
this is a two-fer: when https://github.com/brave/browser-laptop/issues/4980 is fixed, this is also fixed.
