### ISSUE TITLE
Advance settings button should be disabled till Brave wallet is created

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4981]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Advance setting button is clickable when wallet is being created which makes no point until the wallet is actually created

**Expected behavior:**
Advance settings button should be disabled till Brave wallet is created
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.6 Preview 1
- Steps to reproduce:
  1. Do  a new install of the preview build
  2. Enable payments, Advance settings button is shown which can be clicked
  3. After wallet is created, delete all ledger.\* files from session folder, advance button is still clickable which makes no sense.
- Screenshot if needed:
- Any related issues:

**Comment by bbondy** [comment]
@mrose17 for triage but I just didn't want it in 0.12.6 so remove that.

**Comment by mrose17** [comment]
@bbondy - thanks for the heads-up

**Comment by mrose17** [comment]
@srirambv - it's kind of hard for me to think this is a problem. if someone starts deleting files underneath the browser, then i think that we can't really view that as something to guard against.

however, i'll add some bullet-proofing...

**Comment by mrose17** [comment]
it turns out that this was fixed by @jkup in 7e0d8edf
