### ISSUE TITLE
Provide an option to clear partition folders in Partitions

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4982]
**Expected behavior:** Provide an option to delete partition folders in `Partitions`, which contain different sessions info. For now the folders contain cache and cookies which cannot be deleted within Brave. Here's my idea for the auto removal setting: 

<img width="433" alt="screenshot 2016-10-20 15 30 15" src="https://cloud.githubusercontent.com/assets/3362943/19548540/2c338454-96da-11e6-86e1-e3cbe816f8e3.png">

Setting the default partition folder, some kind of ignore list could help.
- Platform (Win7, 8, 10? macOS? Linux distro?): all
- Brave Version: 0.12.5
- Any related issues: #4947

**Comment by bbondy** [comment]
@bradleyrichter maybe this should be in a select element instead and have default session selected by default?

**Comment by bbondy** [comment]
@bradleyrichter pls weigh in, moving to 0.12.9 for now.
I think select element at the top.

**Comment by bbondy** [comment]
Removing this from the milestone; please feel free to object or re-add if you strongly disagree.  I want it a lot but wouldn't block 1.0 on it.

**Comment by bradleyrichter** [comment]
@bbondy 

I don't think our current  approach to partitions is clear enough to support a list here. Can we start with a "Note: all partition data will be cleared according to the selections above."?
