### ISSUE TITLE
Bookmarks shows wrong folder name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4983]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmarks shows wrong folder name

**Expected behavior:**
Should show the correct folder name the bookmark is in
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.6 Preview 1
- Steps to reproduce:
  1. Add a bookmark, move it to a different folder
  2. Click on the bookmark icon, folder shows as bookmark toolbar and not the new folder name it is in
  3. Import boomarks from file/browser which has folders in it
  4. Open the bookmarked page and click on the bookmark icon, still shows location as bookmark toolbar rather than the folder name
- Screenshot if needed:
  ![bmklocation](https://cloud.githubusercontent.com/assets/17010094/19549792/f5efed8a-96c3-11e6-84a9-ae2232faf8f6.gif)
- Any related issues:

**Comment by bbondy** [comment]
regression?

**Comment by srirambv** [comment]
No same behavior in 0.12.5 as well

**Comment by bbondy** [comment]
ok then don't block 0.12.6 on it, thanks.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6133#issue-194802008
