### ISSUE TITLE
"Retry the URL" on cloned error tab is retried on the original tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#4984]
**Describe the issue you encountered:** "Retry the URL" on cloned error tab is retried on the original tab.

![retry](https://cloud.githubusercontent.com/assets/3362943/19550176/3b413da2-96e3-11e6-9945-37bc9d33d1a9.gif)

**Expected behavior:** It should retry on the cloned tab

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: master branch

- Steps to reproduce:
    1. Load a URL which results in connection timed out error
    2. Clone the tab
    3. Retry the URL

- Any related issues: #4881

**Comment by luixxiul** [comment]
cc: @darkdh

**Comment by bsclifton** [comment]
Similar to this complaint (opening Brave while not having internet connection; lots of the pages throw an error. hit retry):
https://github.com/brave/browser-laptop/issues/4946
