### ISSUE TITLE
Bookmark Icon position in title mode looks bad

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4985]
Bookmark Icon position in title mode looks bad 

![image](https://cloud.githubusercontent.com/assets/17010094/19551518/24d1d9b0-96c9-11e6-8585-9d5874a55774.png)

Should be more like 
![image](https://cloud.githubusercontent.com/assets/17010094/19551540/416e11d8-96c9-11e6-8a4a-a1a9c6c519ba.png)

cc: @bradleyrichter @jkup

**Comment by bradleyrichter** [comment]
@srirambv is correct. This is a visual big.

**Comment by bbondy** [comment]
regression?

**Comment by srirambv** [comment]
In 0.12.5 title mode, bookmark icon was not shown. This is new feature for showing the bookmark icon in this release

**Comment by jkup** [comment]
Yeah it's not a regression I just didn't see a spec for how it should look now that we show the icon! Fixing for 12.6.

**Comment by bradleyrichter** [comment]
I need a prototype soldier to try left-aligned elements. Until then, lets keep the star hidden in title mode.

**Comment by alexwykoff** [comment]
It would appear as though the bookmark star has disappeared.
