### ISSUE TITLE
add features

### ISSUE THREAD

**Issue by Doimatcuabautroi** [brave/browser-laptop#4987]
"submit feedback" don't active 
plz add lang: vietnam

**Comment by luixxiul** [comment]
hi, adding lang is done by volunteers on https://www.transifex.com/brave/brave-laptop/

**Comment by bsclifton** [comment]
@Doimatcuabautroi I'm going to close this issue; but like @luixxiul has said, you can sign up on transifex.com and then request that the Vietnamese language be added :smile:

Thanks!
