### ISSUE TITLE
Typing URLs is giving strange results

### ISSUE THREAD

**Issue by bastiaandb** [brave/browser-laptop#4990]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When typing a URL, characters disappear in the URL/search bar. That leads to errors and unwanted visits to scammer websites. I didn't encounter this issue in older versions of Brave.

**Expected behavior:**
Visiting the expected website.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.0

- Brave Version:
0.12.5

- Steps to reproduce:
    1. Install Breave on macOS 10.12
    2. Type a URL
    3. Repeat 2 after visiting various websites and making bookmarks. Maybe the issue is related to autocomplete of URLs.

- Screenshot if needed:
n/a

- Any related issues:
See #3 under "- Steps to reproduce:"

**Comment by Sh1d0w** [comment]
This is fixed in the upcoming version 0.12.6 https://github.com/brave/browser-laptop/issues/4731
