### ISSUE TITLE
Clicking on newtab shows insecure connection 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4991]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clicking on newtab shows insecure connection 

**Expected behavior:**
Connection message should only be shown for websites not for newtab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 Preview 1

- Steps to reproduce:
    1. Open newtab
    2. Click on the blue page icon in the URL bar
    3. Shows insecure connection message

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19557070/b6c5514a-96e1-11e6-8df1-83e6084e423d.png)

- Any related issues:

**Comment by bbondy** [comment]
cc @bradleyrichter for triage

**Comment by bradleyrichter** [comment]
this also happens on the empty icon

![insecure connection](https://cloud.githubusercontent.com/assets/13509546/19725384/384f1276-9b53-11e6-9dbb-096e4cea4236.gif)
