### ISSUE TITLE
Alert: "Your computer has been blocked" Error #S47452D

### ISSUE THREAD

**Issue by denisbeyer** [brave/browser-laptop#4992]
For the second time in just two weeks, a warning pop-up opens when browsing on websites. e.g. while browsing on website frontlineshop.com suddenly the BRAVE warning pop-up opens with the message: "YOUR COMPUTER HAS BEN BLOCKED" - Error: #S47452D. i had to force quiting BRAVE in order to be able o use the browser again. does anyone know what i did wrong or how i should handle such issues?
Thanks and all the best,
D

**Expected behavior:**
- Platform: mac OS X El Capitan V.10.11.5
- Brave Version: 0.12.5
- Steps to reproduce: browsing on website: http://www.frontlineshop.com
- Screenshot if needed:
  ![screen shot 2016-10-20 at 2 04 44 pm](https://cloud.githubusercontent.com/assets/22958459/19559409/00dbc096-96d0-11e6-866e-8856a1c5b710.png)
- Any related issues:
  ![screen shot 2016-10-12 at 4 32 07 pm](https://cloud.githubusercontent.com/assets/22958459/19559425/1351c360-96d0-11e6-803f-eee6ec925669.png)

**Comment by luixxiul** [comment]
Hello @denisbeyer. Do not worry, the first one must be phishing. You can safely ignore the both of them.

To the team: the Brave logo can be used for phishing. Just imagine a dialog which says "hello this is brave team, you violated our condition of usage, so please send us money to this bank account..."

**Comment by luixxiul** [comment]
I set both the milestone and the label release/blocking. Please reset them if needed, thanks.

**Comment by bsclifton** [comment]
Similar: https://github.com/brave/browser-laptop/issues/3794

@luixxiul great call on the logo being displayed, which may almost seem like an endorsement of the message.  cc: @diracdeltas

**Comment by denisbeyer** [comment]
@luixxiul thanks a lot for your quick feedback. thats exactly what i thought. now i can be sure i was right. great work guys. i love your browser!

**Comment by bsclifton** [comment]
Re-opening issue, in case we wanted to take action on making it clear the message is from the website (and not us or the person's operating system (Windows/macOS/Linux))

**Comment by diracdeltas** [comment]
related or duplicate of #2755

**Comment by diracdeltas** [comment]
i'm closing this as a duplicate of #2755

**Comment by diracdeltas** [comment]
someone else reported to me by email that they saw the same phishing alert as in the first screenshot on a fresh install of Brave, which is weird. i wonder if there is some OS X malware going around that pre-populates the Brave userdata directory with a phishing site?
