### ISSUE TITLE
Pressing back button autofills the URL bar with highlighted suggest link

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4998]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
While testing [3235](https://github.com/brave/browser-laptop/issues/3235) found pressing back button autofills the URL bar with highlighted suggest link

**Expected behavior:**
Should not load URL unless user has typed a character

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 Preview 1

- Steps to reproduce:
    1. Open a new tab
    2. Type a char to show the suggestions 
    3. Delete the typed character
    4. Press the left arrow key twice, the highlighted url in step 2 is auto populated

- Screenshot if needed:
Used onscreen keyboard to simulate keyboard actions

![autosugget](https://cloud.githubusercontent.com/assets/17010094/19563788/ee6fa38a-96fe-11e6-8968-af885d18e928.gif)

- Any related issues:
#3235

**Comment by bbondy** [comment]
I think this was also fixed by @Sh1d0w in:
https://github.com/brave/browser-laptop/commit/a32f94801ea51fdfc557df8847e414a5c6cc7fd1

So closing this.
