### ISSUE TITLE
Reimporting bookmarks after generating favicons still doesn't create it on Brave

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#4999]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Reimporting bookmarks after generating favicons still doesn't create it on Brave

**Expected behavior:**
Should recreate favicons after re-import

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 Preview 1

- Steps to reproduce:
    1. Manually create a bookmark on Chrome, Has a blank icon
    2. Import bookmarks from Chrome, Has the same blank icon
    3. Open the bookmarked link in step 1 on Chrome, Updates the favicon
    4. Reimport the bookmarks from Chrome, favicon doesn't update on Brave still remains blank

- Screenshot if needed:
![importfavicons](https://cloud.githubusercontent.com/assets/17010094/19564126/1c5be2f8-9700-11e6-9d67-fd5b5e7b601d.gif)

- Any related issues:
[4882](https://github.com/brave/browser-laptop/issues/4882)

cc: @darkdh

**Comment by darkdh** [comment]
@srirambv , you need to close Chrome before importing because the `Favicon` database is locked by it.
Maybe another issue to prompt a popup window telling people to close Chrome before importing.
