### ISSUE TITLE
mitigate DLL hijacking on windows.

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#500]
@ericlaw1979 reports that we use a windows installer (Squirrel, default for Electron apps) which is vulnerable to DLL hijacking. this is similar to https://github.com/OpenLiveWriter/OpenLiveWriter/issues/177.

one thing we can do to address this until fixed in the installer is to show some sort of scary UI when the user tries to download a DLL, c.f. https://github.com/OpenLiveWriter/OpenLiveWriter/issues/177#issuecomment-177621731

**Comment by bbondy** [comment]
Along these lines I was thinking about downloading executables into a different subdir.

**Comment by luixxiul** [comment]
Is this being worked on or not yet? This might be on the highest priority as labelled "security"

**Comment by bbondy** [comment]
I think with us upgrading to electron-winstaller it's now fixed. CC @paulcbetts

**Comment by paulcbetts** [comment]
Yep, if you're on the latest version, you should be mostly safe (I say 'mostly' because it is very difficult for any app to say with 100% certainty that this is solved, there are so many ways to get into that trap, many involving the internals of OS / library code)

**Comment by luixxiul** [comment]
Nice :-)

**Comment by jonathansampson** [comment]
@paulcbetts Were there any details published about how the upgrade offered more protection against this strategy? The problem is reported to exist beyond the installation process as well.

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/pull/590 and https://github.com/Squirrel/Squirrel.Windows/commit/6722c66f776c93d83cc35cd7b79ccab676eb7b2b are the relevant parts
