### ISSUE TITLE
Reopen last closed window takes users to the domain root instead of the last page they were on.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5004]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When reopening a window, the last page url flickers in the address bar, then I am directed to the domain root. 

**Expected behavior:**
The reopened window should go to the last page I visited.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12.6 Preview 1
- Steps to reproduce:
  1. Visit reddit.com
  2. Visit a subreddit
  3. Close the window
  4. Reopen the window
- Screenshot if needed:
- Any related issues:

**Comment by alexwykoff** [comment]
I had also tried visiting two domains thinking this was a history issue. The reopened window in that case stayed on the second domain.

**Comment by bbondy** [comment]
removed from 0.12.6 because I think re-opening last closed window is a thing most people don't even know exist.
