### ISSUE TITLE
tab bar and find bar unaligned

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5005]
**Describe the issue you encountered:**

<img width="63" alt="screenshot 2016-10-21 1 15 16" src="https://cloud.githubusercontent.com/assets/3362943/19568276/ef48a73e-972b-11e6-9ebc-c0a7302c8d00.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: master branch

- Any related issues:

**Comment by luixxiul** [comment]
actually this is the tab bar height issue.

<img width="677" alt="screenshot 2016-10-21 12 02 09" src="https://cloud.githubusercontent.com/assets/3362943/19585298/4c3936de-9786-11e6-9863-76b8f642fe17.png">

**Comment by bsclifton** [comment]
I'm curious if this was accidentally introduced with https://github.com/brave/browser-laptop/pull/4829?

**Comment by luixxiul** [comment]
^ also the border-bottom under the active tab should be removed.

**Comment by bradleyrichter** [comment]
@bsclifton this could have been my blunder.

It's only visible when the find bar is open. I don't have a fix. Perhaps you have an idea.

![image](https://cloud.githubusercontent.com/assets/13509546/19616184/da870322-97c1-11e6-8e2b-4324ddf491ef.png)

**Comment by bbondy** [comment]
Sorry @bradleyrichter I had to revert  this commit which was causing it.
Please feel free to re-land it once these issues are worked out.

Revert commit is here:
https://github.com/brave/browser-laptop/commit/1e0d74caff8101743b3d7c4bf33d628ea42eeecb
