### ISSUE TITLE
AdBlocking Lets some Facebook.com ADvertes pass through

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#501]
Adblocking is allowing inline feed post still face book advertisements pass thorugh being displayed to the user, I dfon't know if this is intentional or not, plesae see screen shot.

Ads are usually listed as suggested posts
![adverter_1](https://cloud.githubusercontent.com/assets/16950007/12706255/d7cf9bc0-c83d-11e5-879d-41211a9b2e79.PNG)

**Comment by bbondy** [comment]
I think this is a first party ad (served from the same host) which we usually allow but will have to check to see on Facebook.

**Comment by luixxiul** [comment]
Closing for the moment.

**Comment by luixxiul** [comment]
Also please have a look at https://github.com/brave/browser-laptop/issues/527#issuecomment-211022215
