### ISSUE TITLE
pinterest keeps being logged out

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#5018]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
brave keep logging me out of pinterest even with **shield down**
**Expected behavior:**
user can browse pinterest without being logged out
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.5
- Steps to reproduce:
  1. Log in pinterest (if you are new user, choose your pref on other browsers due to #5017)
  2. refresh the page
  3. being logout
- Any related issues: #5017 

from support
https://linkbubble.zendesk.com/agent/tickets/5906

**Comment by ianripken** [comment]
Also having this issue, same steps to reproduce. Windows 10. 
0.12.7

**Comment by teagueamania** [comment]
Pinterest will not validate, making it impossible to use for any purpose. Windows 7 & Windows 10, 0.12.8, all shields down. Worked previously (before 0.12.7)

**Comment by privatzee** [comment]
A clue is that this is one of those sites for which the workaround of _Allow all cookies_ globally (in about:preferences#shields)  lets you stay logged in. The _auth cookie will stay = 1.

![image](https://cloud.githubusercontent.com/assets/22591438/20080160/1dbdce12-a516-11e6-87e9-e9dc438dbf94.png)

 Another clue is that I stay logged in even with blocking 3rd party cookies for pinterest.com itself

![image](https://cloud.githubusercontent.com/assets/22591438/20080366/5e869d7e-a517-11e6-9b96-b5a34b15b01f.png)

**Comment by teagueamania** [comment]
Pinterest will function **only** if Default Shields: All Sites cookie control settings are set to "all cookies are accepted"; disabling shields for Pinterest site alone is **not** sufficient (Windows 7).

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7132)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-pinterest/10679
