### ISSUE TITLE
URL is not cleared on the URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5019]
**Describe the issue you encountered:** URL is not cleared on the URL bar

![url](https://cloud.githubusercontent.com/assets/3362943/19585798/7923f82e-978a-11e6-8ec5-38741ebadb55.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: https://github.com/brave/browser-laptop/tree/d92eff2bc0d9524f4b393dc834245247ab453281

- Any related issues: #4663

I think it has appeared since some versions.

**Comment by luixxiul** [comment]
cc: @diracdeltas

**Comment by bbondy** [comment]
@luixxiul could you write steps to reproduce? Thanks!
