### ISSUE TITLE
Fab&T popup blocked

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#5020]
www.firstarkansasbank.com 
## from support https://linkbubble.zendesk.com/agent/tickets/5720

On my bank's website, they have a bill paying feature.  When I click on this link, Brave blocks the new page from opening.  The bank says I may need to shut off the pop-up blocker in order to move to the bill paying feature page.  I have turned off the pop-up blocker on Brave and it will still not open the page.  How do I tell Brave to allow this new page to open?

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/3752
