### ISSUE TITLE
Add invalid certificate exception

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#5022]
## from support https://linkbubble.zendesk.com/agent/tickets/6171

Can you please tell me how to import (install) a local certificate required by US Gov? (This cert essentially breaks SSL security for user, but is nevertheless required.) Thank you.

**Comment by diracdeltas** [comment]
they have to install it in the system certificate store. for instance in OS X, you would do this in Keychain Access.

closing since we don't have plans to maintain our own cert store
