### ISSUE TITLE
Context Menus are Visible While Scrolling

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5023]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Context menus are visible while scrolling.

**Expected behavior:**
Context menus should be hidden upon scrolling.

**Screenshot:**
![contextmenuscroll](https://cloud.githubusercontent.com/assets/815158/19587408/06727b38-9713-11e6-83ef-8cf6cf1dd053.gif)

**Resolution Process:**
Originally reported to me by [@jaydson](https://twitter.com/jaydson). If/when this issue is resolved, we should notify Jaydson.

**Comment by srirambv** [comment]
It's also visible when you hover over a different tab and the tab preview is shown 

![image](https://cloud.githubusercontent.com/assets/17010094/19589454/e324ab20-9789-11e6-836c-1703832ad02d.png)

**Comment by jaydson** [comment]
UPDATE: This behaviour also happen when you are at PAGE1 with the context menu visible, then you hit enter and navigate to PAGE2.

PAGE1:  
![brave-context-1](https://cloud.githubusercontent.com/assets/72206/19628190/ec64a29a-9936-11e6-9bea-701a643bc8b8.png)

PAGE2 LOADING:  
![brave-context-2](https://cloud.githubusercontent.com/assets/72206/19628193/f0fc1a0e-9936-11e6-92c5-0317ca91938f.png)

PAGE2:  
![brave-context-3](https://cloud.githubusercontent.com/assets/72206/19628194/f48b6de6-9936-11e6-821b-b346dccdbef9.png)
