### ISSUE TITLE
Bookmarked website behaviour in autocomplete.

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5024]
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**
If you often visit a website and you bookmark it it won't appear anymore in the url bar suggestions in the History section, if you have turned off "Show bookmark suggestions" in settings.

**Expected behavior:**

Now how I understand those settings:

Since you can turn on/off each section in the url bar autocomplete - Tab matches, Bookmar matches and History matches (since it takes a lot of space if you enable them on) by turning off the "Show bookmark matches" setting, I just want the bookmarks section in url bar suggestions to be hidden. But it still have to show all matches from the History, regardless if the history entry is bookmarked or not.

Obviosly Brave don't think so and hides all history matches in the history section if the entry is bookmarked, which is very frustrating, because I am forced to enable the setting in order to see the website in the autocomplete and the "highlight" text feature.

The correct behaviour should be as follows: Do not exclude any entries from history matches if the "Show bookmarked matches" setting is turned off. If it is turned on, the logic should be as it is now. That would solve the problem.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version: 0.12.6-Preview 2

- Steps to reproduce:
    1. Visit github.com several times and confirm it appears under History section in url bar suggestions
    2. Bookmark it and confirm it properly appears under bookmarks section in url bar suggestions
    3. Now from settings disable "Show bookmarks suggestions" for the autocomplete
    4. Type github.com in the url bar and observe it does not appear under history section as it should

- Screenshot if needed:

- Any related issues:

**Comment by aekeus** [comment]
Thanks for the detailed bug report. I have a fix in progress for this issue.
