### ISSUE TITLE
CTRL+L wrong behaviour

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5025]
**Did you search for similar issues before submitting this one?**

No.

**Describe the issue you encountered:**

Hitting CTRL+L (focus url bar) selects the current url bar text (which is correct) but also renders url bar suggestions (which is wrong) thus leading to wrong url in the current window, since the first autocomplete suggestion is highlighted.

For example in Chrome if you hit CTRL+L it will correctly only highlight the text and will render suggestions only if you start typing.

**Expected behavior:**

The Brave behaviour should match Chrome's

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version: 0.12.6-Preview 2

- Steps to reproduce:
    1. Open a website
    2. CTRL+L
    3. See suggestions come in

- Screenshot if needed:

http://webm.land/media/alKl.webm

- Any related issues:

**Comment by diracdeltas** [comment]
i had assumed that ctrl+L bringing up the suggestions was intended behavior; if not, this definitely makes the logic a bit simpler. cc @bbondy

**Comment by bbondy** [comment]
I think command+L shouldn't bring up suggestions until the first char is typed.  At the point of Command+L it mostly only matches the single URL you are on anyway.

**Comment by bbondy** [comment]
that should match firefox/chrome
