### ISSUE TITLE
Clicking on Allow protocol registration opens up system settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5028]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clicking on Allow protocol registration opens up system settings

**Expected behavior:**
Should not open system settings when user clicks on allow protocol registration

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 Preview 2

- Steps to reproduce:
    1. Visit https://jsfiddle.net/LnwtLckc/5/
    2. Click on register
    3. Click on Allow in the notification bar, launches system settings 

- Screenshot if needed:
![protocol](https://cloud.githubusercontent.com/assets/17010094/19595146/0db33f2a-97a6-11e6-98d1-24a40784b980.gif)

- Any related issues:

cc: @bridiver

**Comment by darkdh** [comment]
This is related to the default browser check change
https://github.com/brave/electron/commit/016f5646b0fab8b7d68ca9aed7585f4b02e4d65d#diff-7a9e5593d6e972d1c03555df84e6412cR241

**Comment by bbondy** [comment]
this one is pretty bad and should go in 0.12.6

**Comment by bbondy** [comment]
also adding regression label

**Comment by bbondy** [comment]
Sorry RC1 didn't have the new electron, I'll do it for RC2 though.

**Comment by bbondy** [comment]
Will be in electron 1.4.19

**Comment by bbondy** [comment]
Correction, brave/electron 1.4.18
