### ISSUE TITLE
Imported bookmark doesn't show the bookmark icon when loaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5029]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Imported bookmark doesn't show the bookmark icon when loaded

**Expected behavior:**
Should show the bookmark icon when the bookmark is opened
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.6 Preview 2
- Steps to reproduce:
  1. Import Bookmark from a different browser
  2. Click on the bookmark and open the page
  3. Bookmark icon doesnt show the orange star
- Screenshot if needed:
  ![badbookmark](https://cloud.githubusercontent.com/assets/17010094/19597637/5f987dca-97b3-11e6-8805-bb3409657ee5.gif)
- Any related issues:

cc: @jkup @bsclifton

**Comment by cezaraugusto** [comment]
taking

**Comment by bbondy** [comment]
regression?

**Comment by srirambv** [comment]
No same behavior on 0.12.5 as well. Removing milestone

**Comment by bsclifton** [comment]
Closing this as a dupe of https://github.com/brave/browser-laptop/issues/4860
