### ISSUE TITLE
Can't connect to Facebook's Messenger

### ISSUE THREAD

**Issue by davegomez** [brave/browser-laptop#503]
I can't get to connect to Facebook's Messenger and keep receiving the same useless message.

<img width="193" alt="messenger-error" src="https://cloud.githubusercontent.com/assets/282903/12706758/f20a9844-c858-11e5-8627-b3dd056ee296.png">

The application works correctly in any other browser (Chrome, Firefox, and Safari).

**Comment by luixxiul** [comment]
Closing as this was a temporary problem.
