### ISSUE TITLE
Creating a bookmark in about:bookmark page creates a folder instead of bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5031]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Creating a bookmark in about:bookmark page creates a folder instead of bookmark

**Expected behavior:**
Should provide option to enter location and save as a bookmark

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 Preview 2

- Steps to reproduce:
    1. Open about:bookmarks
    2. Select a bookmark folder from left pane
    3. Click on the star+ icon to add a new bookmark
    4. Bookmark hanger shows for adding a bookmark folder and not a bookmark
    5. Clicking on done creates a bookmark folder under the folder selected in step 2

- Screenshot if needed:

- Any related issues:
#4888 

cc: @bsclifton

**Comment by bsclifton** [comment]
Working on a fix now...

**Comment by srirambv** [comment]
Works as expected but entering title doesnt work. Opened issue #5055 for the same
