### ISSUE TITLE
border-right on bookmarkFolderList shows only for the number of bookmarks that are available

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5032]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The border-right on bookmark FolderList is shown only for the number of bookmarks that are created. This looks bad when you only have one or two bookmarks

**Expected behavior:**
By default the border-right should be shown till the end of the browser window

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.6 Preview 2

- Steps to reproduce:
    1. Open about:bookmarks
    2. Have only two or three bookmarks, the border looks odd

- Screenshot if needed:
Current 
![image](https://cloud.githubusercontent.com/assets/17010094/19601304/6c14008e-97c6-11e6-9577-1eddfdcf6a71.png)

Expected 
![image](https://cloud.githubusercontent.com/assets/17010094/19601332/8ad715a6-97c6-11e6-986e-c5d2b43e5f1f.png)

- Any related issues:
#4866

cc: @bsclifton

**Comment by luixxiul** [comment]
I think that's been reverted to the above once
