### ISSUE TITLE
Feature Request: Add a password generator to built-in password manager

### ISSUE THREAD

**Issue by JamborJan** [brave/browser-laptop#5037]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
It would be cool to have a password generator included which suggest passwords when signing up for a new website like Safari on Mac does it today but it should be better in terms of:
- If a login form is not detected as such the user should be able to generate a password anyway from the context menu
- There should be settings to define patterns for passwords and passphrases e.g. like https://github.com/keepassx/keepassx/pull/181
- It should be possible to add custom word lists

**Expected behavior:**
No need to use a password generator outside brave.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  The feature should be cross plattform
- Brave Version:
  Hopefully one not so far in the future :-)

**Comment by Liunkae** [comment]
I really like how Keychain Access (on macOS) does it:
![image](https://cloud.githubusercontent.com/assets/19424103/19612882/cc76e422-97ae-11e6-93e1-607034660549.png)
![image](https://cloud.githubusercontent.com/assets/19424103/19612885/cffd1d32-97ae-11e6-9e81-f01816da2665.png)

**Comment by jonathansampson** [comment]
@JamborJan LastPass (currently supported in Brave) has password generator.

![image](https://cloud.githubusercontent.com/assets/815158/19615796/0d081d48-97ba-11e6-98fb-11c1cc12db2e.png)

**Comment by darkdh** [comment]
1 Password also got password generator
<img width="602" alt="screen shot 2016-10-22 at 12 39 24" src="https://cloud.githubusercontent.com/assets/11330831/19620910/a4ccb572-9854-11e6-9240-56234b96402b.png">

**Comment by bsclifton** [comment]
+1 from @LaurenWags via https://github.com/brave/browser-laptop/issues/10162
> Requested via community: https://community.brave.com/t/password-maker-built-in/5042
>
> I use Password Maker (see passwordmaker.org for more info) as a password generator rather than 1Pass or LastPass or any of the others. I.e.: I calculate my password every time I log in using a formula, rather than store a list of passwords some where.
>
> It would be totally awesome if Password Maker functionality was integrated directly into Brave. I think this fits really well with the mission of privacy and security. In Google Chrome there’s a few extensions that provide that functionality but it’s so simple it could be integrated.
>
> In Brave > Preferences > Security > Passwords and Forms there could be an additional choice in the drop-down for Password Maker Built-in and the Manage Passwords… link would take you a page to fill-in the parameters for the Password Maker formula.
>
> Thanks for your consideration!

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/strong-password-generator/23983?u=eljuno
