### ISSUE TITLE
increase draggable area by utilizing disabled-button states

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5044]
Disabled icons can be used as a window-drag area. This will provide more drag space overall.

(see green zone below)

![image](https://cloud.githubusercontent.com/assets/13509546/19616267/454f5b72-97c3-11e6-9ece-3a2cc3f2bb8f.png)

**Comment by bbondy** [comment]
I realized other browsers show the multiple back items when you right click but I think we need the extra drag room
