### ISSUE TITLE
Password manager is not working for lfg.com mcr.com consumerlab.com

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5047]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support is having difficulty saving passwords on these sites.

**Expected behavior:**
Brave should be able to save the passwords without issue.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
- Steps to reproduce:
  1. Visit any of these sites and attempt to have the password saved.
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6262

**Comment by rebron** [comment]
@alexwykoff I want to close this one out as wontfix here. We suspect this is fixed in brave-core.
