### ISSUE TITLE
Unable to enter title when adding bookmark from about:bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5055]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing #5031, Unable to enter title when adding bookmark from about:bookmark

**Expected behavior:**
Should be able to add title

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.6 RC1

- Steps to reproduce:
    1. Open about:bookmark
    2. Click on the Star+ to add a bookmark
    3. On the bookmark hanger window, try typing the title doesn't record the keystrokes
    4. Enter the location, last char typed in title gets recorded
    5. Click on star+ again 
    6. Type the location first 
    7. Type the title records keystrokes

- Screenshot if needed:
![bookmrktitle](https://cloud.githubusercontent.com/assets/17010094/19617445/1da4fc86-984e-11e6-8048-f4290c71de50.gif)

- Any related issues:
cc: @bsclifton

**Comment by alexwykoff** [comment]
Repro'd on OS X and Ubuntu.
