### ISSUE TITLE
Ad block is not consistent

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5059]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

There is a difference between blocked scripts for same websites in Brave desktop and Brave for Android. I don't know which one yields the correct results, as I can't inspect the blocked scripts in Android, but there is a difference:

<img src="https://s15.postimg.org/k27bucfl7/Screenshot_20161022_181547.png"/>

<img src="https://s15.postimg.org/jqpvhkz57/Screenshot_from_2016_10_22_18_13_45.png" />

**Expected behavior:**

Blocked scripts count should be same on Desktop and Android version.
- Platform (Win7, 8, 10? macOS? Linux distro?):Linux and Android
- Brave Version: 0.12.6
- Steps to reproduce:
  1. Open same website on Desktop and Android

**Comment by bbondy** [comment]
@SergeyZhukovsky @garvankeeley please update to version 2 of the data files.
It is the normal path but with /2 instead of /1

**Comment by garvankeeley** [comment]
Will do!

**Comment by bbondy** [comment]
I think this should be working consistently now, but if not please re-open.
