### ISSUE TITLE
Update Install instructions in Readme.md

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#506]
Recommend adding the following to the end after the abp-filter-parser-cpp note

	During installation you will likely see lines like the following which may be safely ignored

		npm WARN deprecated css-list@0.1.3: Deprecated.
		npm WARN install Couldn't install optional dependency: Unsupported

	If installing on a new machine with little or no node.js previously installed this can take a long time, especially if you are outside the USA and/or have limited bandwidth. In such cases you may also get github timeouts which result in failures due to ECONNRESET messages or similar. If this happens. you should simply rerun the `npm install` command until these stop

**Comment by FrancisTurner** [comment]
Adidtional text per suggestion in issue #558 

Brave uses port 8080 to communicate between its client and server sides. If you are using port 8080 for something else then you can set the environment variable `BRAVE_PORT` to make it use a different one.

e.g.
`BRAVE_PORT=9001 npm run watch`

`BRAVE_PORT=9001 npm run start`

**Comment by luixxiul** [comment]
@bbondy this should be closed as the PR was already merged.

**Comment by bbondy** [comment]
@luixxiul pls email me at brian@brave.com thx

**Comment by luixxiul** [comment]
Sent now, please check your mailbox.
