### ISSUE TITLE
Selecting cut text from context menu refills URL into URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5063]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing context menu test for Windows x64, Realized selecting cut from right click context menu pastes back the URL once the mouse is clicked elsewhere

**Expected behavior:**
Default behavior on other browsers is URL is pasted back only when tab view is changed.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.6 RC2
- Steps to reproduce:
  1. Open any URL
  2. Click on the URL bar to select the URL
  3. Right Click -> Cut, copies the URL to clipboard
  4. Click elsewhere on the browser, the URL is pasted back in the URL bar
- Screenshot if needed:
  ![contextmenu](https://cloud.githubusercontent.com/assets/17010094/19621593/bb894aec-98b2-11e6-9ea8-0bcb7be407a1.gif)
- Any related issues:

**Comment by Liunkae** [comment]
Regression of #4941?

**Comment by srirambv** [comment]
Not really. #4941 used to revert text immediately. The cut text behavior is right and it doesn't revert immediately. The only deviation from other browsers is the text is reverted when you click on the same tab and other browsers it reverts only when tab focus change

**Comment by srirambv** [comment]
Reopening the issue. URL still reverts when clicked on Bookmarks toolbar/ any where on the page. The only place where the URL doesn't reverts is clicked on the dragable area on the title bar.

![5063](https://cloud.githubusercontent.com/assets/17010094/19778633/8af915bc-9c75-11e6-9860-8f56ba15ddd4.gif)

@bbondy Your thoughts on this? Its quite different from Chrome's behavior.

**Comment by bbondy** [comment]
This is definitely still valid but not bad enough to block on.
