### ISSUE TITLE
Improve the design of the download page

### ISSUE THREAD

**Issue by h3xp4n** [brave/browser-laptop#5064]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** **Could have a more design "attractive" such as firefox or opera manager, say the Brave of Internet downloads manager is very "lean" and should be improved..**

**Expected behavior:** It should be made an improvement in the download manager.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows10 64bits
- Brave Version: 0.12.5
- Screenshot if needed:

**Comment by EuNlope** [comment]
Who can please the design suggestions ...

**Comment by bsclifton** [comment]
cc: @bradleyrichter

**Comment by srirambv** [comment]
Possible design for download page @bradleyrichter your thoughts

1. No mouse hover on downloaded entries
  ![image](https://cloud.githubusercontent.com/assets/17010094/19623926/b612a860-98fd-11e6-85df-2fd3c45b2bd2.png)

2. Mouse hover on failed entry (Change in action icon)
  ![image](https://cloud.githubusercontent.com/assets/17010094/19623927/c19b8ef4-98fd-11e6-8138-af5585a33fd4.png)

3. Mouse hover on completed entry (Change in action icon)
  ![image](https://cloud.githubusercontent.com/assets/17010094/19623930/cc5a893a-98fd-11e6-8697-b0c2b41788a5.png)

**Comment by EuNlope** [comment]
It will be like in Chrome with that low bar showing the download progress?

**Comment by EuNlope** [comment]
The layout of the page should be the same or think about any changes?
