### ISSUE TITLE
Refine the Brave button (look, positioning, feel) on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5069]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The Brave button (the lion icon) feels awkward on Windows (compared to the macOS version)
![screen shot 2016-10-23 at 12 44 31 am](https://cloud.githubusercontent.com/assets/4733304/19624752/eda3de5a-98b9-11e6-854d-0cd6ccacb619.png)

**Expected behavior:**
Solution should match this mockup by @bradleyrichter:
![image](https://cloud.githubusercontent.com/assets/4733304/19624737/6061d470-98b9-11e6-86c3-5a08cd57776b.png)

Notice:
- the caption buttons are vertically centered
- lion icon has an additional separator to the right

**Related:**
Similar to https://github.com/brave/browser-laptop/issues/4591

**Comment by bsclifton** [comment]
@bradleyrichter When implementing, I discovered an issue with this design:
![windows1](https://cloud.githubusercontent.com/assets/4733304/19625221/6f67269c-98c7-11e6-8e1a-2784a9207eec.gif)

The caption buttons have their vertical centering throw off on resize ☹️ 

For a demo, I tried putting the menu UNDER the navigation bar. This looks and feels pretty decent 😄 
![windows2](https://cloud.githubusercontent.com/assets/4733304/19625231/9dd60d72-98c7-11e6-9892-ff021d16a657.gif)

This is consistent w/ IE behavior too:
![windows1](https://cloud.githubusercontent.com/assets/4733304/19625233/abdf5b8a-98c7-11e6-8aaa-3a21febc4cfe.gif)

What do you all think? (cc: Windows users- @srirambv @jonathansampson). The styles can be updated to look halfway decent (matching Bookmarks Toolbar)

**Comment by srirambv** [comment]
@bsclifton  The file menu popping under the URL bar looks good. +1 for this to go with Windows build. 

If this behavior is implemented then I would suggest to disable Always show menu bar.

**Comment by bsclifton** [comment]
Moving this to 0.12.8; I know @bradleyrichter is still finalizing the placement- I like it under the menus too :smile: It would be good to see what the public thinks

**Comment by bsclifton** [comment]
Moving to 0.12.9.  We did talk over Slack and have worked out an ideal scenario:
- screenshots in original post is accurate
- menu will NOT move beneath the nav bar (this is not standard)
- Brave logo and extensions will go under the caption buttons if menu is being shown

**Comment by bsclifton** [comment]
Here are some WIP screenshots, cc: @bradleyrichter 

**no menu w/ magic titlebar**
![screen shot 2016-11-05 at 12 45 53 am](https://cloud.githubusercontent.com/assets/4733304/20028520/976f65bc-a2f1-11e6-803e-7bd1e9044c0a.png)

**menu w/ magic titlebar**
![screen shot 2016-11-05 at 12 46 38 am](https://cloud.githubusercontent.com/assets/4733304/20028521/9e6cdd90-a2f1-11e6-8645-cf566469d7d1.png)

**no menu w/ URL bar**
![screen shot 2016-11-05 at 12 47 35 am](https://cloud.githubusercontent.com/assets/4733304/20028523/a88dcab4-a2f1-11e6-9e9f-09671feb7360.png)

**menu w/ URL bar**
![screen shot 2016-11-05 at 12 47 14 am](https://cloud.githubusercontent.com/assets/4733304/20028524/ad910238-a2f1-11e6-99a0-74f609423d4b.png)

**Comment by bsclifton** [comment]
Re-opening after testing on Windows 7 (see screenshot)

Working on a fix now...

![screen shot 2016-11-09 at 12 12 50 pm](https://cloud.githubusercontent.com/assets/4733304/20151035/ddfd8388-a675-11e6-9fb5-ef0642bb47a2.png)
