### ISSUE TITLE
Brave resolves localhost to ::1 (IPv6)

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5071]
**Did you search for similar issues before submitting this one?**
Yes, but it's not the same as #1459
**Describe the issue you encountered:**
localhost gets resolved to `::1` (which is loopback in IPv6)

Win7 x64
Brave 0.12.5

- Steps to reproduce:
    1. go to---> http://localhost/
    2. Apache access log says:    
`::1 - - [23/Oct/2016:09:01:14 -0400] "GET / HTTP/1.1" 403 202`

- Screenshot if needed:
Palemoon works correctly:
![image](https://cloud.githubusercontent.com/assets/22591438/19626374/4e9d9932-98fe-11e6-8331-92d11ec0f360.png)

Brave:

![image](https://cloud.githubusercontent.com/assets/22591438/19626360/c980bcf2-98fd-11e6-8fa7-2b6722f5002a.png)

- Any related issues:
going to http://127.0.0.1 does work correctly

**Comment by privatzee** [comment]
well, I do get the same 403 error in Chrome

**Comment by Sh1d0w** [comment]
@privatzee This is more like your webserver/OS configuration problem rather than problem with Brave (given you can't open it in Chrome as well). I can confirm that Brave correctly resolves localhost, when I run sample `index.php` file and `php -S localhost:8000` .

**Comment by bsclifton** [comment]
this is correct- you'll want to check your hosts file:
`C:\Windows\System32\drivers\etc\hosts`

**Comment by privatzee** [comment]
okay, thanks to both of you
