### ISSUE TITLE
about:history omits recent history

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5072]
about:history only displays browsing history more than ~22h57m old. History data seems correct as missing browsing history does appear once sufficient time has passed but the display should include everything upto the most recent browsing history.

Ubuntu 16.10
Brave: 0.12.5
Electron: 1.4.14
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by privatzee** [comment]
Win7 x64
Brave 0.12.5

History is so wrong that I'd stopped using it. 

atm, my most recent entry in about:history is ~6 hours old.  What appears on the dropdown from the History menu doesn't match that and is all jumbled besides.

**Comment by Sh1d0w** [comment]
Probably related issue https://github.com/brave/browser-laptop/issues/4794

**Comment by CliqueBait** [comment]
@Sh1d0w I don't think so. My guess is that there's a timestamp-based query which doesn't correctly account for the user's timezone.

**Comment by luixxiul** [comment]
Adding the same milestone as #9979, which would possibly fix this issue.

**Comment by srirambv** [comment]
Verified by changing system time to see if the history was retained in browser
![image](https://user-images.githubusercontent.com/17010094/34294315-ccbaeefa-e6ff-11e7-968e-22767d893145.png)
