### ISSUE TITLE
urlbar autosuggestion are sometimes show in titleMode

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#5074]
i can't consistently repro, but sometimes the urlbar suggetions are shown in titlemode

1. go to a site
2. start typing something into the urlbar that has autocomplete suggestions
3. move the cursor so that the urlbar goes into titlemode

![screen shot 2016-10-23 at 9 58 02 am](https://cloud.githubusercontent.com/assets/549654/19628081/c7445c7a-990a-11e6-8ff1-023fb9a494ee.png)

cc @Sh1d0w

**Comment by Sh1d0w** [comment]
Nice catch, will fix :)
