### ISSUE TITLE
Folders and Titles lists in about:bookmarks should scroll independently

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5076]
I have several dozen bookmark folders and have several dozen boomarks in each folder. Re-organising bookmarks is impractical and clumsy without being able to scroll the two seperately as is the case in Chromium (and other browsers).

Ubuntu 16.10
Brave: 0.12.5
Electron: 1.4.14
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by CliqueBait** [comment]
Issue raised again by a user in the brave community:
https://community.brave.com/t/issue-with-bookmark-manager/530

**Comment by bsclifton** [comment]
This would be a great one to have! I personally have a large number of bookmarks and trying to organize them is painful (because of the constant need to scroll up and down)

**Comment by luixxiul** [comment]
I thought this was duping to #2076. It must have been removed at some point while the bookmark manager was updated :-)

**Comment by Liunkae** [comment]
Transferred milestone from duplicate #8441.
