### ISSUE TITLE
Feature request: bookmark tagging

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5078]
Large collections of bookmarks would be easier to manage if bookmarks could be tagged and were subsequently searchable by those tags. I have no opinions on the specifics of the implementation at this stage beyond thinking the feature worth considering.

Related to: #5076, #5077.

**Comment by CliqueBait** [comment]
For reference, the approach taken in Firefox is described here:
https://support.mozilla.org/en-US/kb/categorizing-bookmarks-make-them-easy-to-find

**Comment by luixxiul** [comment]
+1 https://community.brave.com/t/bookmark-tool-bar-tab-options/686?u=suguru

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/brave-missing-parts/4209)

> Tag for bookmark support ?

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmark-manager-is-unusable/1659/17?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmarks-tagging/22035?u=eljuno

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1057
