### ISSUE TITLE
Suggestion: de-clutter mode for reading websites

### ISSUE THREAD

**Issue by JamborJan** [brave/browser-laptop#5081]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Many webpages are not easy readable because of their structure, menus etc. Browsers use to have a "reading mode" or some de-clutter feature. Brave is missing such a feature on mobile and desktop.

**Comment by Liunkae** [comment]
Duplicate of #517 ("Add Reader view for pages").
