### ISSUE TITLE
Tests being ran for Travis CI are broken

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5082]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
You can view any build in travis-ci.org and you'll notice that only 1 test is ran, which is a find bar test.  I reproduced this on my local machine (macOS) 

Our contributor @Sh1d0w had dug in and reporting findings about when this started here:
https://github.com/brave/browser-laptop/pull/5046#issuecomment-255572470 

**Expected behavior:**
All tests should be ran

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
@bsclifton I also noticed that. It all started here

<img src="https://s21.postimg.org/v8dzr3naf/Screenshot_from_2016_10_24_07_47_16.png" />

**Comment by bsclifton** [comment]
The first commit that fails is this:
https://github.com/brave/browser-laptop/commit/08213f2aae468a31d10d6ed90c8de1c7d12ac4f6

It doesn't appear to even be running the `npm install` before (and the .travis.yml hasn't been updated in quite some time). Will continue digging...

**Comment by bsclifton** [comment]
The ones which work were checking out dev-channel:
`git clone --depth=50 --branch=dev-channel https://github.com/brave/browser-laptop.git brave/browser-laptop`

**Comment by bsclifton** [comment]
I think this might have something to do with it:
https://github.com/brave/browser-laptop/commit/e12fca0b7322c7c1ffc89b07b774123b18ddebfe#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

From the console:
```
    ERROR in aboutPages.entry.js from UglifyJs
    SyntaxError: Unexpected token: name (length) [./~/punycode/punycode.js:55,0]
```

**Comment by bsclifton** [comment]
Things I've tried (which did not work... even though it works locally on my mac w/ node v6.3)
- adding a [query section with es2015](https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-168191452)
- bumping the node version up to 6.3

**Comment by bsclifton** [comment]
I believe the tests not running is fixed with https://github.com/brave/browser-laptop/commit/79c38f58dbc22068650fcae985205061f0f4721b

Perhaps the above error is not related?  Although, I do think it's the cause of the problem @srirambv has (where about pages are not working)

**Comment by diracdeltas** [comment]
Looks like this can be closed now that tests are all running again. https://travis-ci.org/brave/browser-laptop/builds

re: the punycode module, i added it because NPM docs say that the core module is now deprecated, but it's not strictly needed for any reason yet.

**Comment by bsclifton** [comment]
@diracdeltas yup- I did see that, and it looks like you did it properly... I'm curious why the webpack uglify plugin is complaining :frowning_face:
