### ISSUE TITLE
Some images are being blocked on https://www.cnet.com

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5089]

**Comment by bbondy** [comment]
This is actually already being tracked here:
https://github.com/brave/browser-laptop/issues/4442
and
more deeply here:
https://github.com/bbondy/abp-filter-parser-cpp/issues/38

So I'm closing this one.

**Comment by luixxiul** [comment]
FYI there are 8 open tickets as I write this on CNET, which you can find here: https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20cnet

**Comment by luixxiul** [comment]
I think we should take some time to investigate the issue on CNET. I am not sure if ad blocking is too aggressive there, as they could in fact track users.
