### ISSUE TITLE
Live streaming not working on http://tv.infowars.com/  but viewing other movies on the site works

### ISSUE THREAD

**Issue by rebellion2016** [brave/browser-laptop#509]

**Comment by luixxiul** [comment]
This could be related with #1546

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/live-streaming-not-working-on-http-tv-infowars-com/10099

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
