### ISSUE TITLE
One click works as double click sometimes

### ISSUE THREAD

**Issue by CGS773** [brave/browser-laptop#5090]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Usually clicking one time works as a double click. Closing one tab close the right one, using a right click option also clicks on what's behind it, videos are paused and turned on on one click.... On other programs it works correctly so is not a personal problem.
**Expected behavior:**
Clicking one time not work as double click.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version:
0.12.06
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@CGS773 were you able to resolve the issue? I saw this was closed and wanted to follow up to make sure everything is ok :smile:
