### ISSUE TITLE
Website in new tab don't load for several seconds

### ISSUE THREAD

**Issue by plieblang** [brave/browser-laptop#5093]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Whenever I go to a website in a new tab, the address bar changes to the desired URL but the tab doesn't actually start loading until about 5 seconds later.
**Expected behavior:**
The tab should start loading immediately.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10, Version 1607, Build 14393.321
- Brave Version:
  12.6, although the problem also appeared in 12.5
- Steps to reproduce:
  1.  Open Brave to a new tab and click on a bookmark or type into the address bar.  Also happens when opening a link in a new tab.
  2.  Notice that the tab does not load for several seconds.
- Screenshot if needed:
- Any related issues:

**Comment by luixxiul** [comment]
Would you please tell me a URL which you experience the issue for example?

**Comment by plieblang** [comment]
I experience it on every URL that I've tried, including https://github.com/brave/browser-laptop/milestones and http://www.howtogeek.com/.  I have GitHub bookmarked and the issue is present when I open the bookmark; and I also can type in any URL (eg How-To Geek) and the issue is present.

**Comment by plieblang** [comment]
The issue is possibly caused by Microsoft's EMET tool.  I uninstalled EMET and now tabs load normally.
