### ISSUE TITLE
Create a tags.less file with global element styling

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5094]
This relates to the meeting @bradleyrichter and I had regarding #4884

Right now we don't have many global styles for elements which means they need specific sets of classes to work properly. We should create a new less file with just the basic Brave stylings for elements like a, button, input, etc.

Most of the CSS is done it's just buried in a class but I think it would make development a lot easier to pull it out so those elements always get some styling.

**Comment by bbondy** [comment]
Sounds great, but maybe call it global.less? Just not sure what tags means.

**Comment by jkup** [comment]
Yeah that sounds good.. I stole the tags name from bootstrap but global makes more sense.

**Comment by bsclifton** [comment]
Love this! It shouldn't be too hard to go through the styles, let me know if you all want to do a 30 min Google hangout and check it out together :smile:

**Comment by bbondy** [comment]
This should be closed right? Just making sure but I think so.  
I think commit message needs Fix #x and Fix #y explicitly to close both auto btw.

**Comment by jkup** [comment]
Sorry, yep!

**Comment by luixxiul** [comment]
Please specify QA steps if any. If not, please label `qa/no qa needed`, thanks.

**Comment by jkup** [comment]
@luixxiul QA steps are mentioned in the PR https://github.com/brave/browser-laptop/pull/5442

Am I doing this wrong? Can I make it easier?

**Comment by bsclifton** [comment]
I think putting the steps in the PR is acceptable; one thing that couldn't hurt: we can do to make it visually pop out at you by putting it inside a header tag using markdown (in the original post, which you did); something like

## testing
1. step 1 
2. step 2

**Comment by luixxiul** [comment]
@jkup my bad I just missed it as there isn't a linked commit to this issue.

**Comment by jkup** [comment]
@luixxiul no problem, what does that mean though? This commit https://github.com/brave/browser-laptop/pull/5442 links to this issue

**Comment by luixxiul** [comment]
I mean because there was no auto-closing words in the commit https://github.com/brave/browser-laptop/pull/5442/commits/72174bbbb38032babb805e4c1f2e42d2b7e0f71a, it was not referred to this issue. I've noticed the referred PR but I was looking for the commit.
