### ISSUE TITLE
Form elements are nested too deeply

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5095]
This also relates to #4884 but our form elements like input[type="text"] and general button.browserButton are nested too deeply (inside 3 classes) so that in order to get the styling you need to import settingsList and settingsListItem.

Since we want consistent form styling all throughout the settings pages we should pull those styles out into the top level of preferences.js.

**Comment by srirambv** [comment]
QA steps not mentioned

**Comment by luixxiul** [comment]
@srirambv ? -> https://github.com/brave/browser-laptop/pull/5442#issue-187621714
