### ISSUE TITLE
Finish SVG conversion

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5096]
This PR https://github.com/brave/browser-laptop/pull/4972 was merged but unfinished. This ticket is for finishing the rest of the font-awesome to SVG conversion in the URL bar.

**Comment by jkup** [comment]
PR now reverted so this ticket should track all SVG work.

**Comment by jkup** [comment]
Closing as #4852 has been re-opened and we only need 1 ticket to track the work.

**Comment by bbondy** [comment]
When closing an issue without a commit pls clear milestone, makes it easier for triage. Thanks!
