### ISSUE TITLE
Feature Request : Enpass Extension

### ISSUE THREAD

**Issue by slydetech** [brave/browser-laptop#5097]
**Did you search for similar issues before submitting this one?**
Yes

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/enpass-password-manager/kmcfomidfpdkfieipokbalgegidffkal

**What do you like about the extension?**
I know that there already is an integration of password managers like Lastpass or 1password. The added value of Enpass, beside the ergonomy, is the possibility to use webdav/owncloud to store your password database in a self hosted infrastructure.

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7096)

**Comment by bsclifton** [comment]
closed with https://github.com/brave/browser-laptop/pull/6493

**Comment by bbondy** [comment]
@diracdeltas are you ok with us including this in the next release?

**Comment by bbondy** [comment]
Yan confirmed on Slack it was ok.
vault-updater and muon support for this added in this issue.
https://github.com/brave/browser-laptop/issues/6906

**Comment by bbondy** [comment]
Seems like muon doesn't have support for this yet.

Here's steps that can be followed to ensure the extension will work: https://blog.brave.com/loading-chrome-extensions-in-brave/ 

I'll just hide the toggle for now.

**Comment by luixxiul** [comment]
Replacing the label with `release-notes/exclude` for now.

**Comment by srirambv** [comment]
Marking as `no-qa-needed` based on https://github.com/brave/browser-laptop/issues/5097#issuecomment-276764361

**Comment by luixxiul** [comment]
1 request: https://twitter.com/OsmanCayirci/status/843049126338027520

**Comment by stefandeml** [comment]
any news on Enpass Support for Brave?

**Comment by maetthew** [comment]
+1 on any news for Enpass Support? Want to start using Brave but need Enpass

**Comment by jonathancbatista** [comment]
The same for me. I can install the extension on Brave on my Mac. But it does't work. I like Enpass more than other password manager. I would be not that hard to make it work on Brave, I already works on Chrome and other chrome based browsers (like Vivaldi)

**Comment by hanscees** [comment]
enpass is my favorite choice as well. If it could be added please do. It is based on non-cloud first and thats what I prefer. No dependencies

**Comment by jonathancbatista** [comment]
> hi all, browser-laptop is being deprecated. please migrate as soon as possible to the new brave which should support all extensions including enpass: https://brave.com/download (github: https://github.com/brave/brave-browser)

I have this new brave installed on my mac. I could install the extension from chrome extension page. It is on my extensions menu. But when I click to use it, a new tab opens with a "enpass conection error" message. Then is tab goes to a new tab.

So it's working but not connecting to the app on my computer.

**Comment by bsclifton** [comment]
@jonathancbatista what version did you try? It should have been fixed with https://github.com/brave/brave-core/pull/975

If you're still seeing this problem, would you mind leaving a comment on https://github.com/brave/brave-browser/issues/1380
