### ISSUE TITLE
Fix vertical align for close button on download bar

### ISSUE THREAD

**Issue by pmkary** [brave/browser-laptop#5098]
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS Sierra
- Brave Version: 0.12.6

The bookmark start and the reload icons are so much near the bottom instead of being centered (which is the expected design). Their status makes the look very un-native and like the buggy webpages. 
![screen shot 2016-10-25 at 1 40 24 am](https://cloud.githubusercontent.com/assets/2157285/19665937/7803b016-9a54-11e6-9dd7-1c39a16f2443.png)

Also I think the blow glow must contain the whole bar including the star...
![screen shot 2016-10-25 at 1 40 31 am](https://cloud.githubusercontent.com/assets/2157285/19665938/78141cf8-9a54-11e6-84d1-a9d22195188d.png)

The problem with not being vertical center align is also true for the close button of the download bar. I think you should change the metrics there too:
![screen shot 2016-10-25 at 1 41 28 am](https://cloud.githubusercontent.com/assets/2157285/19665939/78272640-9a54-11e6-94a1-da9f63f23fed.png)

**Comment by bsclifton** [comment]
The navigation bar items have been fixed- we also have an update coming soon to convert from icons to SVGs (https://github.com/brave/browser-laptop/pull/5173)

**Comment by bsclifton** [comment]
Would be nice to fix the blue outline though cc @bradleyrichter

**Comment by pmkary** [comment]
@bsclifton 👍

**Comment by bradleyrichter** [comment]
on the list. coming soon via @jkup. I will make a separate issue for the blue outline change.

**Comment by pmkary** [comment]
@bradleyrichter again thanks a lot!

**Comment by bsclifton** [comment]
Updated issue title; I think all issues have been resolved, except for the download bar

**Comment by luixxiul** [comment]
I think this has been fixed with #6153

**Comment by luixxiul** [comment]
Test plan:

Make sure these buttons are aligned vertically:
- go back/forward button
- bookmark star button
- download bar close button
