### ISSUE TITLE
"Couldn't set selectedTextBackgroundColor from default" console message

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#51]
```
> npm start

> brave@0.0.1 start /Users/yan/repos/browser-electron
> NODE_ENV=development electron . --debug=5858

2015-12-14 12:05:53.082 Electron Helper[32946:1976162] Couldn't set selectedTextBackgroundColor from default ()
```

**Comment by serv** [comment]
Still seeing this log with brave@0.7.x as well.

```
$ npm start

> brave@0.7.7 start /Users/jasonkim/projects/node/browser-laptop
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck


electron "/Users/jasonkim/projects/node/browser-laptop" --debug=5858
2016-01-25 23:59:49.627 Electron Helper[47930:3600257] Couldn't set selectedTextBackgroundColor from default ()
{ version: '0.7.8',
  name: 'Brave 0.7.8',
  pub_date: '2016-01-26T02:51:47.572Z',
  notes: 'New UI, various features, and various fixes. Full details at https://github.com/brave/browser-laptop/releases/tag/v0.7.8',
  url: 'https://brave-download.global.ssl.fastly.net/releases/0.7.8/osx/Brave-0.7.8.zip' }
```

**Comment by natalliachu** [comment]
I gave the same error in console when I try to attach a doc to the email in Gmail but only when this Gmail account is the second-opened.

**Comment by serv** [comment]
Here is how I can reproduce this issue.

1. `npm start` to start the browser
2. Go to say, stackoverflow.com
3. Wait for it to load.
4. Click on the URL bar. This step will cause the log to print `2016-01-27 22:13:24.815 Electron Helper[41434:5026930] Couldn't set selectedTextBackgroundColor from default ()`.

**Comment by hdwong** [comment]
+1

**Comment by frenchbread** [comment]
Related issue - https://github.com/atom/electron/issues/4420

**Comment by controversial** [comment]
This is a chromium bug, I believe

**Comment by wuqunfei** [comment]
same bug like https://github.com/electron/electron/issues/4420,do you konw and idea about his https://github.com/zcbenz

**Comment by bsclifton** [comment]
This is a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=641509 and still repro's perfectly (Chromium 54) with the steps by @serv 

With our new [browser-laptop-bootstrap](https://github.com/brave/browser-laptop-bootstrap) setup, it would be pretty easy to fix this and create a patch (as well as upstream it). Definitely low priority though

**Comment by bsclifton** [comment]
Confirmed this doesn't happen with [Brave Core](https://github.com/brave/brave-browser); closing as `wontfix`
