### ISSUE TITLE
Add bookmark/folder dialog UX problems

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5103]
- [ ] Adding a folder shouldn't point to the star at all, dialog should be centered.

<img width="261" alt="screenshot 2016-10-24 19 38 24" src="https://cloud.githubusercontent.com/assets/831718/19667938/0a38e664-9a22-11e6-9bc8-c11b79b40a4e.png">

- [ ] When seeing the dialog from the about:bookmarks page, there shouldn't be a view all bookmarks button, you're already doing that.

- [ ] Editing a bookmark from about:bookmarks should be centered and shouldn't point to the star.

**Comment by bsclifton** [comment]
Grabbed this- should be able to knock this out tonite :smile:

**Comment by jkup** [comment]
@bsclifton please let me know if I can be of any help on this!
