### ISSUE TITLE
1Password 6.3.4/6.3.5 Mac update, possibly similar recent Windows update, break integration 

### ISSUE THREAD

**Issue by dgarsys** [brave/browser-laptop#5105]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

As of updating 1Password to 6.3.4 on OSX (released less than a week ago as of 10/24/16), Agilebits is implementing an extension authorization system requiring a six-number code. This does not work in teh built-in 1password mii support, and as a result the 1password icon in the toolbar is non-functional, and the mini application in the menubar does not talk to the Brave browser or know what page it is on.

Due to various issues with 6.3.4 an update for 6.3.5 was posted - and upgrading does not fix the problem, as the extension or authorization behavior was not updated.

**Expected behavior:**

Hit Command-\ or click on the 1password icon, and the mini applciation opens up to provide a list of available passwords for the current site
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OSX. Since this feature is implemented in the new Windows update as well, expect it to be cross-platform issue 
- Brave Version:
  0.12.6 - tried to update but Brave reports this is latest version
- Steps to reproduce:
  1. Open brave
     ensure 1password mini is running
     go to website
     click on 1password icon or hit Cmnd-\ on keyboard.
     observe no window opening

Open mini app in menubar
observe current website not showing
    2.
    3.
- Screenshot if needed:
- Any related issues:

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6424

**Comment by dgarsys** [comment]
Is there a way to see what's in the ticket? 

Either way - as of the latest brave update - 0.12.7 - since this was reported, it's still an issue

**Comment by bjrnqprs** [comment]
Still an issue with Brave 0.12.9 on OSX, I hope this will be fixed :-)

@alexwykoff Can you tell us what is in the ticket? A login screen appears when clicking on that link.

**Comment by dgarsys** [comment]
In my case it's been working as of one of the updates in 0.12.8 - the validation code setup suddenly worked when I restarted brave. 

That said 1password was also updated- 

1password 6.5 (650034)

**Comment by bjrnqprs** [comment]
@dgarsys Thanks for your info. I noticed I still had 1Password 6.3.4 so I tried updating it to 6.5, and then restarted Brave. But still no luck, strange.

**Comment by bjrnqprs** [comment]
Ah it seems a system restart **after** the update of 1Password has resolved the issues. Finally :-)

**Comment by bsclifton** [comment]
@bjrnqprs thanks for the update :smile:
