### ISSUE TITLE
Ledger wallet creation is failing

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5107]
Currently when you try to create a wallet the UI hangs and the console says something to the effect of:

ledger client error(1): "Error: HTTP response 503 for POST /v1/registrar/persona/bdc96f2fc5f4feaaadda0316e1680d3"

<img width="963" alt="screenshot 2016-10-24 23 30 18" src="https://cloud.githubusercontent.com/assets/490294/19672182/172b4d06-9a29-11e6-95ac-13970994c7aa.png">

**Comment by mrose17** [comment]
problem resolved on the back-end
