### ISSUE TITLE
Problems with LastPass extension

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5109]
**Did you search for similar issues before submitting this one?**

No

**Describe the issue you encountered:**

Often I find that upon first launch of Brave it does not automatically logs me in my lastpass account and the lock icon on the upper right next to the bravery panel is gray - unlocked (which means I am not logged in). Without logging in, I close Brave and start it again. After the second launch the icon becomes red and locked (which means I am logged in). From then every following launch will work correctly unless the browser is closed for some time and it breaks again.

**Expected behavior:**

Upon first launch I have to be logged in my last pass account without having to restart the browser.
- Platform (Win7, 8, 10? macOS? Linux distro?): Fedora 24
- Brave Version: 0.12.6
- Steps to reproduce:
  I don't have 100% way to reproduce each time but these are the steps under which it happens to me (I guess you have to use the extension for a while to happen):
  1. Make sure Brave has been closed for a while
  2. Open Brave
  3. See if you are logged in lastpass extension
- Screenshot if needed:
- Any related issues:

**Comment by Sh1d0w** [comment]
This can be reproduced at 100% when you launch Brave right after update from ine version to another.

**Comment by bcdady** [comment]
I had the same / similar symptom, and first changed the password manager in Settings, then restarted Brave. I'm not sure if just changing password managers (e.g. to Brave, then back to LastPass) might also resolve th symptom of this perceived bug.
