### ISSUE TITLE
Missing mouse-over visual feedback on Preferences tabs

### ISSUE THREAD

**Issue by minustime** [brave/browser-laptop#5112]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
The Preferences menu doesn't provide visual feedback on clickable tabs
**Expected behavior:**
Display pointer when rolling over the tabs with the mouse
- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X 10.11.2
- Brave Version:
0.12.7
- Steps to reproduce:
    1. Open the Preferences menu
    2. Mouse over the menu options on the left

- Screenshot if needed:
![cursor-default](https://cloud.githubusercontent.com/assets/460373/19673902/16907ffa-9a52-11e6-962f-f222bbd156e3.png)

- Expected behavior:
![cursor-pointer](https://cloud.githubusercontent.com/assets/460373/19673913/3c8d7866-9a52-11e6-9f11-d9fd1a1a1e03.png)

**Comment by minustime** [comment]
PR coming up.

**Comment by Liunkae** [comment]
CC: @bradleyrichter

**Comment by bradleyrichter** [comment]
thanks @minustime 

We should have the pointer on those as well as hyperlinks but not on other UI controls.
