### ISSUE TITLE
Delete menu item is not capitalized

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5113]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
The Delete item in the Edit menu is not capitalized. The translation was accidentally removed in 4ebfe91 [here](https://github.com/brave/browser-laptop/commit/4ebfe91124b50245a57426b0d42d7c305d5c8eca#diff-985837eca34ef94b3bc9cf3271761dcaL22).

**Expected behavior:**
The Delete menu item should be capitalized.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12

- Brave Version:
0.12.6

- Steps to reproduce:
    1. Click Edit in the menubar.
    2. Notice that Delete is not capitalized.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/19674210/1916ed46-9a4c-11e6-9cd4-663275b682b0.png)

- Any related issues:
None.

**Comment by bbondy** [comment]
cc @jkup careful to remove things used elsewhere

**Comment by jkup** [comment]
@bbondy good call! This was done before I knew we sometimes used locale.translation(). I checked and didn't see any data-l10n-id's so I thought it was safe to remove!
