### ISSUE TITLE
on webcompat and banking sites

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5120]
There have been a few webcompat issues posted lately (e.g. #5020) about banking sites. Naturally, it's very unlikely that anyone can diagnose the problem without having an account to log into.

However, most/all of non-giant banks are probably using a banking software company such as NetTeller. After or during login, the user will see the change in the url bar. So knowing a solution for one banking software company should also give the solution for any bank that uses that same company. It's not actually a problem with the bank site itself.

Note that the banking software companies might very well still be introducing spies like demdex or google.

**Comment by bsclifton** [comment]
Closing as stale- not enough information.  As noted, the popups being blocked (a very common problem) per #5020 is being tracked with https://github.com/brave/browser-laptop/issues/3752

If there are some concrete steps to reproduce or a list of sites which don't work and enough information for one of us to take action, let's re-open 😄
