### ISSUE TITLE
Add Selective Retention - Historical Tabs + Open Last tabs option

### ISSUE THREAD

**Issue by kumzme** [brave/browser-laptop#5129]
**Did you search for similar issues before submitting this one?**
Yes - So many but above intent is not clear

**Describe the issue you encountered:**
Feature / Design request 

**Expected behavior:**
Ensure That in History of tabs visited, we should be able to group the last few tabs that were open before we closed the browser.
Ensure that the above feature is only  optional. 
- When a user could set or unset this feature to be active, 
- Especially when we have selected the option to clear ALL data when we close the browser, the overall history to be not retained , but history of open tabs retained and we can have a button to open all of them.
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  ![add selective retention - historical tabs open last tabs option - now](https://cloud.githubusercontent.com/assets/13012709/19704717/bf594cf0-9ad6-11e6-8c58-5943caa8d0b3.png)
  ![add selective retention - historical tabs open last tabs option - after update](https://cloud.githubusercontent.com/assets/13012709/19704719/c2617f44-9ad6-11e6-9d13-4c94fa7019e3.png)
- Any related issues:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/add-selective-retention-historical-tabs-open-last-tabs-option/10182

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
