### ISSUE TITLE
Use a Icon for bookmarks Navigation next to Brave ICON

### ISSUE THREAD

**Issue by kumzme** [brave/browser-laptop#5130]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Design Feature Request
**Expected behavior:**
Provide a Book mark icon that we can often navigate without obtrusion or going to more steps.
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
  ![use a icon for bookmarks navigation next to brave icon](https://cloud.githubusercontent.com/assets/13012709/19705013/39a11b40-9ad8-11e6-90cb-fd070a393dc4.png)
  ![use a icon for bookmarks navigation next to brave icon after clicking icon](https://cloud.githubusercontent.com/assets/13012709/19705012/399d2b8e-9ad8-11e6-80af-2caa57fdcc02.png)
- Any related issues:

**Comment by bsclifton** [comment]
this is an interesting one; cc @bradleyrichter 

In lieu of a bookmarks toolbar, there could be a catch-all bookmarks button (as proposed in pictures above)

**Comment by rebron** [comment]
Closing wontfix here. Tracking here in brave-core. https://github.com/brave/brave-browser/issues/1069
