### ISSUE TITLE
"Never include this site" no longer refreshes about:preferences#payments

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#5134]
originally, if you were on about:preferences#payments and you right-clicked on a publisher and then selected "Never include this site", then that line would disappear as the page immediately refreshed.  this no longer happens, so it looks like "nothing has happened". however, if you go to another page (in the same page) and then come back, you'll see that it did work.

could we get the old behavior back?

@diracdeltas - who could take this one? thanks!

**Comment by diracdeltas** [comment]
i can't repro this in latest master

**Comment by mrose17** [comment]
thanks. let me build that and see what's going on.

**Comment by mrose17** [comment]
apparently, this issue is limited to just me.
