### ISSUE TITLE
Add extension for Evernote Web Clipper

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5136]
From support: https://linkbubble.zendesk.com/agent/tickets/5957

**Comment by patertmg** [comment]
I fully second your idea! However, as a workaround, I recently found ukeeper.com. There you can create a Bookmarklet (or save the resulting Javascript Code to a new bookmark in Brave browser) to have sent a clutterfree version of any website from Brave directly to your mailbox. From there I use the MailButler plugin for Mac Mail to save the message as Evernote (but you could also simply forward it to your Evernote mail adress, with tags and all the rest).

**Comment by jonathansampson** [comment]
Closing in favor of #8327
