### ISSUE TITLE
Middle-click on a browser tab (Windows) should close the tab

### ISSUE THREAD

**Issue by scunliffe** [brave/browser-laptop#514]
This is more of a feature request than a bug, but Windows users are used to this in their tabbed applications (whether browsers or document editors/IDEs)

**Comment by scunliffe** [comment]
Just got version 0.7.11 and this has been implemented (thus I'm closing this issue)

**Comment by bbondy** [comment]
This should already be working in 0.7.11.  Note there's a 0.7.12 coming out today too if you just want to wait for that. Please re-open if you see it in one of those versions though.

**Comment by bbondy** [comment]
hah yep
