### ISSUE TITLE
Offer Apple keychain for password management

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5142]
This came in from support but I'm not sure how feasible it would be. Users would like to be able to store and retrieve their passwords via Apple Keychain. As a replacement for 1password or lastpass.

Does anyone know if that's possible and if so, is it on our road map?

**Comment by bsclifton** [comment]
It's not on our roadmap, but we do have an issue tracking this (which has some more info)
https://github.com/brave/browser-laptop/issues/3226

I'll go ahead and close this issue.  Thanks :smile:
