### ISSUE TITLE
Login to Linkedin, autocomplete problem

### ISSUE THREAD

**Issue by JimSEOW** [brave/browser-laptop#5144]
When login in to linkedin, when prompted for email, when I type the first alphabet of the email, the popup menu appear to select the email, the popup closes before I have chance to select the email.

**Comment by getsetbro** [comment]
This happens to me on stackoverflow: http://quick.as/lrvkfzgwx

**Comment by Liunkae** [comment]
Duplicate of #5438. This problem is planned to be fixed by version 0.13.2.
