### ISSUE TITLE
Window buttons not properly aligned when browser is maximized

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5145]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Window buttons not properly aligned when browser is maximized

**Expected behavior:**
Should be properly aligned
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.7 Preview 1
- Steps to reproduce:
  1. Maximize the window
  2. See the buttons are not properly aligned. They seem to be top aligned
- Screenshot if needed:
  Brave vs Chrome (Restore and Maximized windows)
  ![image](https://cloud.githubusercontent.com/assets/17010094/19719321/5276e9c2-9b61-11e6-99c5-da43f4762497.png)
- Any related issues:

cc: @bsclifton

**Comment by bsclifton** [comment]
May be fixed with https://github.com/brave/browser-laptop/pull/5485
