### ISSUE TITLE
History suggestions comes up even after clearing history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5147]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
History suggestions comes up even after clearing history

**Expected behavior:**
Should not show suggestions from history when history is cleared
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.7 Preview 1
- Steps to reproduce:
  1. Open https://www. brave.com and then clear browsing history
  2. Open a new tab and type brave.com
  3. Suggestion comes up under history
- Screenshot if needed:
  ![unclearhistory](https://cloud.githubusercontent.com/assets/17010094/19722839/71c3874a-9b70-11e6-8158-f219093408cb.gif)
- Any related issues:

**Comment by Sh1d0w** [comment]
Maybe this one is related https://github.com/brave/browser-laptop/issues/4224

**Comment by diracdeltas** [comment]
can't repro on master

**Comment by bbondy** [comment]
Moving to 0.12.8

**Comment by bsclifton** [comment]
Removing milestone.  @srirambv are you able to repro (per @diracdeltas' comment above)?

**Comment by luixxiul** [comment]
closing as stale. @srirambv please reopen if you can reproduce the issue yet, thanks!
