### ISSUE TITLE
Bookmark added before webpage loaded completely doesn't show bookmark icon when visited

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5148]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmark added before webpage loaded completely doesn't show bookmark icon when visited

**Expected behavior:**
Should show the bookmark orange icon when you visit the same site after adding as a bookmark
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.7 Preview 1
- Steps to reproduce:
  1. Visit https://brave.com, add as a bookmark while page is being loaded
  2. Open new tab, type brave.com, Press Esc to clear autosuggestion and press enter to visit the site
  3. Site doesn't contain the bookmark icon
  4. Add bookmark, creates a new bookmark on toolbar
  5. Delete the bookmark created on step 5, only deletes the new bookmark and not the one created in step 1

Same behavior on 0.12.6 as well
- Screenshot if needed:
  ![bmkprob1](https://cloud.githubusercontent.com/assets/17010094/19723409/1851cfb6-9b73-11e6-91e2-24d294eaa522.gif)
- Any related issues:

**Comment by bsclifton** [comment]
This should have been fixed with https://github.com/brave/browser-laptop/pull/5285/ (I didn't see this issue at the time :smile:)
