### ISSUE TITLE
Support multi-select and drag-and-drop in about:bookmarks

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5150]
In about:bookmarks, I am unable to select multiple bookmarks and drag-and-drop to a different folder. Not sure if this is working for people on other platforms:
Ubuntu 16.10
Brave: 0.12.6
Electron: 1.4.18
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

When I'm in a rush, I file all my bookmarks into an Inbox folder and then refile them at a more convenient time. Refiling becomes cumbersome if I've neglected to clear out my Inbox folder for any length of time.

There are currently several issues with about:bookmarks which hinders convenient management of large numbers of bookmarks.
Related to: #5076, #5077, #5078

**Comment by bsclifton** [comment]
This was actually fixed in master with https://github.com/brave/browser-laptop/issues/1005 which will be shipped out with our next version (0.12.7).  Stay tuned :smile: 

Closing issue as it's fixed in master
