### ISSUE TITLE
Window border shown in fullscreen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5152]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Window border shown in fullscreen

**Expected behavior:**
Should not show any window border when in full screen

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.7 Preview 1

- Steps to reproduce:
    1. Open any video in full screen mode
    2. Shows blue window border even in full screen
    3. 0.12.6 shows a gray outline 

- Screenshot if needed:

- Any related issues:

**Comment by ETapia1** [comment]
I am also having this issue. Trying to find a solution but no luck yet.

**Comment by bsclifton** [comment]
This is a good one- thanks :smile: Looking into this now...
