### ISSUE TITLE
No hotkey exists to go to next match with `CTRL-f` text searching

### ISSUE THREAD

**Issue by dmp1ce** [brave/browser-laptop#5157]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Using the find text feature with `CRTL-f` works fine, but I would like to be able to use a hotkey to go to the next match. Chromium uses `F3` as the hotkey.

**Expected behavior:**

`CTRL-f` would open text search and then after searching `F3` or some other key would go to the next match. Perhaps `SHIFT+F3` would go to the previous match.
- Platform (Win7, 8, 10? macOS? Linux distro?):

Antergos
- Brave Version:

0.12.5
- Steps to reproduce:
  1. `CTRL-f` to search
  2. Type in text to search for
  3. `ENTER`
  4. Notice there is no hotkey to go to the next match on the page

**Comment by srirambv** [comment]
+1 from community for F3 
https://community.brave.com/t/find-next-f3-shortcut/7513/2
