### ISSUE TITLE
Latest Browser on Windows 7 does not work. Blank Screen

### ISSUE THREAD

**Issue by kumzme** [brave/browser-laptop#5158]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Justblank screen. Screenshot shows brave after update. - plain blank screen.

![brave issue1](https://cloud.githubusercontent.com/assets/13012709/19730465/519159a0-9b68-11e6-9937-bb2a68efc996.png)

![brave issue2](https://cloud.githubusercontent.com/assets/13012709/19730466/5192c8e4-9b68-11e6-9791-7ab8065e8d56.png)

**Expected behavior:**
- Platform (Win7, 8, 10? macOS? Linux distro?):
- Brave Version:
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:

**Comment by privatzee** [comment]
Well that's odd, I'm using Win 7 right now.

Win7 x64
Brave 0.12.6

**Comment by kumzme** [comment]
hmm .. it started after the latest update

**Comment by bsclifton** [comment]
@kumzme what version did you have before? You should be able to find out by navigating to:
`%userprofile%\AppData\Local\brave`

You should then see the versions.  I am curious if your previous version was older than 0.12.3 (which introduced some new code which could be causing this)

**Comment by bsclifton** [comment]
Closing as stale- we need more information to troubleshoot this.  Please re-open and include more details if you're encountering this 😄
