### ISSUE TITLE
Maximizing browser extends into second monitor

### ISSUE THREAD

**Issue by ETapia1** [brave/browser-laptop#5159]
## Test plan
1. Have a dual monitor Windows setup
2. Open Brave and maximize it on one of the windows
3. There shouldn't be any border from Brave.exe on the other monitor (see below picture)

## Original issue description
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
when I click the maximize button (by the close button not f11) the browser over-extends on to my second monitor. I can hover over the excess pixels and it gives me the option to stretch the window (double sided arrows) but it won't expand because it's already maximized on my main monitor. I've already reinstalled my OS. The issued still persists. Now there is also an issue when I go full screen on a video. It creates an annoying blue border around the video. this didn't happen before so I'm not sure if it's a related issue.
**Expected behavior:**
Maximize window without overlapping onto my second monitor.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10
- Brave Version:
  0.12.6
- Steps to reproduce:
  1. have two monitors
  2. click maximize button
     3.
- Screenshot if needed:
- Any related issues:
  Blue border around full-screen videos.
  ![monitor 2](https://cloud.githubusercontent.com/assets/23080048/19732132/c9eb9316-9b6d-11e6-860c-d1cd7d725b5f.PNG)
  ![monitor 1](https://cloud.githubusercontent.com/assets/23080048/19732135/cc8ca60a-9b6d-11e6-97cd-858d4befeaf5.PNG)
#5119

**Comment by Superbest** [comment]
I also get this with Windows 7. I believe it's been happening at least for 3 weeks now. It wasn't an issue more than 2 months ago, I think either version 0.8 or 0.9 was the last one without this issue.

**Comment by andrewcole50** [comment]
Happens to me to. Whichever side I maximize Brave on It extends ~5-10 pixels over to the next screen. Oddly enough pressing F11 produces a properly maximized window but the maximize button or dragging the window to the top of the screen produces the bug.

Windows 10 x64

**Comment by Superbest** [comment]
Some weird observations:

1. It bleeds from horizontal right monitor (main screen) to the vertical left monitor (second screen), but not from left monitor to right monitor.
2. Once it bleeds, I can minimize and restore the window and the bleed is removed.
3. When the bleed is removed, I can restore and re-maximize the window and it bleeds again.

This is on Brave 0.12.10 by the way.

**Comment by bsclifton** [comment]
With the recent updates in 0.13.0, we should retest this :smile: It may very well be fixed now (if not, I have some good ideas for fixes)

**Comment by bsclifton** [comment]
This issue is definitely Windows only; he's an article describing the history behind why Windows behaves like this for maximized:
https://blogs.msdn.microsoft.com/oldnewthing/20120326-00/?p=8003

The potential fix would be in brave/muon.  We could force the window to stay within the bounds of the monitor by handling the `WM_GETMINMAXINFO` event and changing the dimensions there.

**Comment by bsclifton** [comment]
+1 from user @benjaminsuch via https://github.com/brave/browser-laptop/issues/7997

**Comment by lukemulks** [comment]
We've had a Brave Community contributor report a ~1-3px overlap between monitors when Brave is maximized in a primary display, when there are two displays sitting side by side. 

URL to Brave Community thread: 
https://community.brave.com/t/youtube-skip-ad-button-disappeared-brave-window-overlaps-other-screen/2329/8

Browser profile for user: 
```
Brave: 0.15.0 
rev: 71fb73001617949528cc6473e288a49e76fcd4d5 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.15063 
os.arch: x64
```
Screenshots provided by our contributor: 

![brave-windows-maximized-overlap-04282017-1](https://cloud.githubusercontent.com/assets/8979240/25550636/a4544be0-2c2f-11e7-8818-6bd2cf01c4a9.png)

![brave-windows-maximized-overlap-04282017-2](https://cloud.githubusercontent.com/assets/8979240/25550645/adc83614-2c2f-11e7-82ad-c78e514dba45.png)

**Comment by bsclifton** [comment]
@alexwykoff I think you said you may have a way to test multiple monitors... this would be a great one to retest.  It may not be fixed, but worth a rest for sure

**Comment by bsclifton** [comment]
If this fails QA, let's re-open and remove the milestone 😄

**Comment by bsclifton** [comment]
Re-opening and unassigning milestone.  Per @jonathansampson:
> A maximized window on second monitor bleeds a few pixels over into the first monitor.
> Similarly, a maximized window on the first monitor bleeds a couple pixels over into the second monitor.

**Comment by jonathansampson** [comment]
@bsclifton Just downloaded https://github.com/brave/browser-laptop/commit/fc4b892f1873551e44062f0c12dd262b7c5662f6, and this issue no longer repros for me.

**Comment by bsclifton** [comment]
@jonathansampson awesome! thanks for the report 😄  In that case, I'll re-close and move back to 0.15.300
