### ISSUE TITLE
dismiss URL dropdown suggestions when I click in menu or url bar area

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5160]
**Describe the issue you encountered:**
The dropdown suggestions dismiss only from a click on the content area

Win7 x64 
Brave 0.12.6
- Steps to reproduce:
  1. get the dropdown
  2. click at either yellow X in the screencap below
  3. dropdown does not dismiss, which therefore requires a subsequent click in the partially obscured content area which might initiate some action that I don't want
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/22591438/19732265/3c7e7858-9b6e-11e6-8c5e-077d97a0b616.png)
- Any related issues:

**Comment by bsclifton** [comment]
Big ++ on this from me too, cc @bradleyrichter

**Comment by Sh1d0w** [comment]
Can't reproduce this on the latest master. See video

http://webm.land/media/lria.webm

**Comment by bradleyrichter** [comment]
Agree!

And there is a new bug lurking in here in recent releases. It seems to open prematurely.

**Comment by Sh1d0w** [comment]
@bradleyrichter Can you provide STR?
