### ISSUE TITLE
Wrong adblock count shown after visiting a new site in the same tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5161]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Wrong adblock count shown after visiting new site in the same tab

**Expected behavior:**
Should not show wrong adblock count
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.7 Preview 1
- Steps to reproduce:
  1. Visit http://twitter.com, check the adblock count
  2. In the same tab visit https://apple.com, check the adblock count shows 1 and shows twitter.com
  3. Visit https://apple.com in a new tab, adblock count shows 0
- Screenshot if needed:
  ![adblock](https://cloud.githubusercontent.com/assets/17010094/19734427/6754d29e-9b9f-11e6-8eda-6db5514f2db4.gif)
- Any related issues:

Edit: Same issue on 0.12.5 & 0.12.6

**Comment by luixxiul** [comment]
@srirambv I think this issue has been fixed already. mind confirming?

**Comment by srirambv** [comment]
I still this on the latest build. But its intermittent. 
![image](https://user-images.githubusercontent.com/17010094/32493451-ce2d815c-c3b5-11e7-8482-0d2fe92e57a5.png)
