### ISSUE TITLE
Bookmark modal polish

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5163]
For use with these components:
- addEditBookmarkHanger
- addEditBookmark

The modal should be matching these mock ups by @bradleyrichter:
notice the following:
- arrow shape under the bookmark/folder name
- blue outline around input fields

when adding a folder:
![image](https://cloud.githubusercontent.com/assets/13509546/19671255/78347a7a-9a3b-11e6-8f0f-028209bba663.png)

when adding a new BM when no URL is present to start with:
![image](https://cloud.githubusercontent.com/assets/13509546/19671279/a445bdf4-9a3b-11e6-915d-ca844a94507d.png)

**Comment by luixxiul** [comment]
@bradleyrichter are those mockups still valid?

**Comment by bradleyrichter** [comment]
let's delete these in favor of: https://github.com/brave/browser-laptop/issues/8346
