### ISSUE TITLE
Add Reader view for pages

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#517]
Maybe use this: https://github.com/mozilla/readability for reading view
Might be useful for an offline mode too and for indexing pages for better autocomplete results.

**Comment by alexwykoff** [comment]
+1 from support

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6311

**Comment by thechild** [comment]
One other option would be to just include this chrome extension (https://mercury.postlight.com/reader/) to get a great reader view.

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/reading-mode-safari-has-it-built-in/3387

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/wont-use-desktop-browser-without-reading-mode/4597)

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/omni-search-and-customizable-ui-and-bookmark-feature-request/4906)

**Comment by rdetert** [comment]
+1 Reader Mode is the one thing I miss from Safari on desktop. I can read so much faster.

**Comment by calebbarr** [comment]
+1

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/reader-view-like-in-firefox/7143

**Comment by ironfish** [comment]
+100

**Comment by stephenkilpatrick** [comment]
Add me to the +1's.

**Comment by davidhfo** [comment]
Another +1.

**Comment by iamhenry** [comment]
Looks like this isn't a priority but I'm going to +1 this as well.

**Comment by jonathansampson** [comment]
After testing Mercury Reader, I found that Brave has pretty good OOB support. I'm going to create a master issue to track any needed APIs, and progress towards supporting this as a Reader option in future builds: https://chrome.google.com/webstore/detail/mercury-reader/oknpjjbmpnndlpmnhmekjpocelpnlfdi

**Comment by Jacalz** [comment]
Intiually I hated mercury reader but it is growing on me. I have also found that using it sometimes can help you read content from websites with an adblocker blocker 👍

**Comment by patertmg** [comment]
Got  #Mercury Reader Extension (but not  #Evernote Extension)  to work following this article: https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/reader-feature-for-desktop-version/12201?u=eljuno

**Comment by blacktop** [comment]
+1

**Comment by jonathansampson** [comment]
@patertmg How was the Mercury Reader experience?

**Comment by patertmg** [comment]
@jonathansampson Great so long! There are only two minor concerns: (1) don’t know why, but Mercury doesn’t show an icon - there’s only a grey space up in the corner, so I have to click “blindly” on it (2) would be even better if i could define a shortcut to start Mercury. Thanks!

**Comment by Jacalz** [comment]
The thing is that it would be better to have an open sourced reader mode integrated in to the browser than having a closed source reader mode extension. Mercury reader is good but since Brave is a browser that cares about privacy, maby it should have mozilla readability instead 👍

**Comment by oleim** [comment]
+1

**Comment by jonathansampson** [comment]
Just ran through another test with Mercury; I noticed only the same issue(s) that @patertmg reported (missing browserAction icon). Here's the logic which shows the browserAction icon:

https://github.com/brave/browser-laptop/blob/d0c2c6c9d8744557e1d4452a386c46e1649317b6/app/common/state/extensionState.js#L90-L94

Note that Mercury doesn't provide 16 or 38 pixel icons:

```
   "icons": {
      "128": "img/icon-128.png",
      "16": "img/icon-16.png",
      "48": "img/icon-48.png"
   },
```

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/reader-view-vue-lecture/21364

**Comment by LaurenWags** [comment]
+1 from customer email

**Comment by skotzko** [comment]
+1

**Comment by mbabco** [comment]
Add me to the list of folks who would love a readability feature.

**Comment by okiess** [comment]
+1

**Comment by bigt2000** [comment]
I also would love this option.  It is one of my favorite built in features in Firefox and Vivaldi.   Honestly I really love Brave.   I am just waiting for more of these features and add on support to show up before it will be perfect.

**Comment by bsclifton** [comment]
Unfortunately, we won't be able to address this with `browser-laptop`... but we should with [Brave Core]() (even if just by having an extension available)

Closing in favor of https://github.com/brave/brave-browser/issues/679
