### ISSUE TITLE
Extension support: Speed Dial (for giving users a better look to the "new tab")

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#5171]
**Did you search for similar issues before submitting this one?** 
Yes
**Describe the issue you encountered:**
A feature that would help both the page design and comes to further facilitate the user's life. Until then I do not know any browser that has not adopted the Speed Dial. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows10 64x
- Brave Version:
0.12.6

**Comment by luixxiul** [comment]
I think the new tab feature is being under development by @cezaraugusto

**Comment by bsclifton** [comment]
New tab behavior captured here:
https://github.com/brave/browser-laptop/issues/3001

I added your suggestion for this extension here:
https://github.com/brave/browser-laptop/issues/4600

**Comment by cezaraugusto** [comment]
Yes, as @bsclifton mentioned you can see new tab's page spec on #3001. 

Also in #4600 you can upvote Speed Dial extension request and I think more upvotes means more chances to have it implemented. Thanks for your interest!
