### ISSUE TITLE
"AdReclaim" ads not blocked

### ISSUE THREAD

**Issue by anseljh** [brave/browser-laptop#5175]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Saw pretty awful ads via AdReclaim on a site where ad blocking was active.

**Expected behavior:**

Should be blocked.
- Platform (Win7, 8, 10? macOS? Linux distro?): Win7
- Brave Version: 0.12.6
- Steps to reproduce:
  1. Browse to http://littlegreenfootballs.com/article/46523_Sean_Hannity_Tweets_Image_From_4Chan-White_Supremacist_Sites
  2. See ads
- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/2075772/19750422/c9467218-9ba5-11e6-97b4-63d546e731ac.png)

![image](https://cloud.githubusercontent.com/assets/2075772/19750445/f592da1e-9ba5-11e6-828a-90c2a75b9ccc.png)
- Any related issues: Nope

**Comment by luixxiul** [comment]
The issue has been resolved.

If you are still around here, would you please join https://community.brave.com to talk about other issues you might experience? :smile: Thanks!
