### ISSUE TITLE
error page infinite loop

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#5177]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
reload error page of DNS error will cause infinite reloading
**Expected behavior:**
the error page won't reload infinitely
- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version: 0.12.6

- Steps to reproduce:
    1.  Type `brave.123` in navigation bar
    2.  After error page is presented, click refresh button next to navigation bar
    3.  Press alt + cmd + i and you can see infinite reloading

- Any related issues: #4881

**Comment by bsclifton** [comment]
I wonder if this was causing https://github.com/brave/browser-laptop/issues/4502? In that issue, folks are reporting seeing an error page and it's flickering (possibly redrawing really quickly?)

**Comment by darkdh** [comment]
I think this is introduced in 0.12.6
