### ISSUE TITLE
Switch search engines locale based on languages

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5180]
**Expected behavior:** Switch search engines locale based on languages. Japanese users generally want to use https://amazon.co.jp instead of https://amazon.com, for example.
- Brave Version: master branch
- Any related issues: #5179

**Comment by bradleyrichter** [comment]
Sure. Let's connect regional features that make sense. A user can always override the setting or even the language selection. We should add some note:text in the language area though.

**Comment by bsclifton** [comment]
This should be addressed in [brave-core](https://github.com/brave/brave-browser) with the OpenSearch functionality built in (ex: we won't be providing US specific search engines to anyone; engines they visit (which are localized) get added to aggregated list)
