### ISSUE TITLE
Imported bookmarks should set creationTime field (not lastAccessedTime)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5183]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
Deleting an imported bookmark doesn't delete the history entry. This comes up as a history suggestion

**Expected behavior:**
Deleting an imported bookmark should delete its entry from history as well
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  0.12..7 RC1
- Steps to reproduce:
  1. Import bookmarks from a file or another browser
  2. Delete the imported bookmark 
  3. Type the site name in URL, the deleted bookmark shows up as a history suggestion
- Screenshot if needed:
  ![history](https://cloud.githubusercontent.com/assets/17010094/19759958/2fd3df6c-9c27-11e6-96a6-08b19ba2f6ef.gif)
- Any related issues:
  
  cc: @bsclifton Setting milestone as 0.12.8

**Comment by bbondy** [comment]
I don't think this is right, I think deleting a bookmark should be independent of if it shows up in history, if the last access time was set from an import, it should remain there.

**Comment by bbondy** [comment]
Going to close as wontfix, but lmk if you strongly disagree.

**Comment by bsclifton** [comment]
@bbondy I know someone had opened a similar one and I felt the same way (can't find that ticket...)

This one seems to be different in the sense that it's entirely possible that the user never visited the sites they are importing. Removing a bookmark only removes the tags (not the entry- basically turning it into a history entry)... The real issue here might be that entries in sites should not be considered history items unless there is an associated timestamp

**Comment by bbondy** [comment]
I think if last access date is filled out from a history import then it should be considered a history entry as well. I think if it was never visited last access date will be 0, but I can definitely be wrong on that's how it works (I think it should work that way though).  CC @darkdh for his thoughts.

**Comment by darkdh** [comment]
Imported History and Bookmark all have `lastAccessedTime` info, I think it's my bad to [use bookmark creation time as lastAccessedTime](https://github.com/brave/browser-laptop/blob/0cf47505a11fa5236d0d8b4a913cdda0de43207b/app/importer.js#L163) when importing bookmarks.
I can definitely to make it 0, what do you think, @bbondy?

**Comment by bbondy** [comment]
is there a lastAccessTime and a creation time you can use?  If only creation time is avail maybe set a new field for that and it will be unused for now.

**Comment by darkdh** [comment]
we don't have lastAccessTime when importing bookmarks but I can add a creationTime field for later use

**Comment by bsclifton** [comment]
Updated the title to reflect the current status. Thanks, @darkdh :smile:

**Comment by alexwykoff** [comment]
Could not verify in OS X 0.12.8 RC1

<img width="821" alt="screen shot 2016-11-04 at 1 03 41 pm" src="https://cloud.githubusercontent.com/assets/1434040/20016852/3997786a-a28f-11e6-9342-296110483a5a.png">

**Comment by srirambv** [comment]
On Windows too. Entry shows up in history suggestion but not shown in about:history

![history1](https://cloud.githubusercontent.com/assets/17010094/20017451/8de5f672-a2bb-11e6-8215-2ee1acee1790.gif)

cc: @darkdh
