### ISSUE TITLE
width of input and select elements on new bookmark folder form is not equal

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5192]
**Describe the issue you encountered:** width of input and select elements on the new bookmark folder form is not equal

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/19776161/fc10fa70-9cad-11e6-98ae-5aa49d98d06d.png)

**Expected behavior:** it should be equal
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.7 RC1
- Any related issues:

cc: @jkup

**Comment by bsclifton** [comment]
Removed milestone- let's discuss if you feel strongly

**Comment by luixxiul** [comment]
Modified the milestone to the nearest one as PR was sent and it was ready for review.

**Comment by jkup** [comment]
@luixxiul I noticed this too on about:styles you can see the input type text is longer than the select boxes.

I'll assign to myself and try to get to it soon unless you want to take it?

**Comment by bsclifton** [comment]
Looks like one of our contributors knocked it out :smile: Very cool!
https://github.com/brave/browser-laptop/pull/5837

@jkup I'll assign the PR over to you for review

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6035#issue-193657652
