### ISSUE TITLE
tab is not bookmarked by dragging on the bookmark folder

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5193]
**Describe the issue you encountered:** The tab is not bookmarked by dragging it on the bookmark folder on the toolbar. For now it needs to be dragged and dropped to the pulldown. Also the color of the dragged tab remains changed.

**Expected behavior:** 
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.7 RC1
- Steps to reproduce:
  ![bookmark](https://cloud.githubusercontent.com/assets/3362943/19777092/a652a238-9cb1-11e6-90ae-5cdbc11e9bde.gif)
- Any related issues:

**Comment by bbondy** [comment]
I don't think we ever supported dragging tabs to bookmarks toolbar and actually I think tear off tabs will override this functionality, Chrome doesn't allow it but Firefox does.  It doesn't need to be prioritized in any case though.

**Comment by luixxiul** [comment]
But the tab is bookmarked by dragging it on the bookmark folder pulldown like this.

![bookmark](https://cloud.githubusercontent.com/assets/3362943/19793871/bbb59862-9d09-11e6-948b-eba48cd740ee.gif)

Doesn't it work as it should?

**Comment by bbondy** [comment]
interesting and I'm surprised :)

I think we can support it and work like firefox, but not super high priority I don't think.   After tear o tabs for sure.

**Comment by luixxiul** [comment]
FYI drag and drop to the folder still works but at the same time it detaches the tab.

**Comment by bsclifton** [comment]
Closing as `wontfix`; when moving to [brave-core](https://github.com/brave/brave-browser), this would no longer be feasible because dragging the tab detaches it immediately (into its own window)
