### ISSUE TITLE
Favicons not shown in payments list when it first gets listed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5194]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Favicons not shown in payments list when it first gets listed

**Expected behavior:**
Should show the favicons when it gets listed

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.7 RC1

- Steps to reproduce:
    1. Enable payments from settings
    2. Visit nytimes.com 
    3. Nytimes.com gets listed but doesn't have favicons
    4. Open a different link in Nytimes.com, close pref page and reopen payments page, Favicons is shown

Intermittent issue not able to reliably reproduce the issue

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19772769/27232822-9c5f-11e6-96aa-bd5ffe521d98.png)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #4178
