### ISSUE TITLE
Create about:styles page to display style guide

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5195]
This is something @bbondy, @bsclifton and I have been talking about. It would be great to have something like https://www.khanacademy.org/style for Brave. This would serve as a style guide and living documentation for working with out UI components.

The problem that Khan Academy has with theirs (https://twitter.com/jdan/status/789174664677302272) is that it gets out of date easily. Therefore I think we should make an about page within our app that serves the actual UI components so it's always up to date.

Ideally we'd create something like about:styles an display our main UI components (form elements, buttons, headers) as well as the JS code that can be used to generate them.

**Comment by bbondy** [comment]
Here's a placeholder commit for adblock, similar can probably be landed for this as a first commit even if not fully ready:
https://github.com/brave/browser-laptop/commit/255303a956f94aa46a6192f94e13d3083a0a7841
