### ISSUE TITLE
register button for ledger should remain enabled after denying handler registration

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5197]
**Describe the issue you encountered:** the register button for ledger should remain enabled after denying handler registration. For now you have to click "unregister" button to re-enable the register button
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.7 RC1
- Steps to reproduce:
  1. Open https://jsfiddle.net/LnwtLckc/5/
  2. Click "register" and "deny" on the notification bar
  3. Click "register" again -> notification bar is not displayed
  4. Click "unregister" and "register" again -> the bar is displayed
- Any related issues:

**Comment by mrose17** [comment]
@luixxiul - thanks! this is a very interesting issue

@bbondy - this is a generic problem with the protocol handler registration.

if you click the "register" button (in the lower-right quadrant) and then click "Deny" in the notification bar at the top, then clicking the "register" button again appears to be a no-op; however, if you click the "unregister" button, then clicking on the "register" button will cause the notification bar to appear as it should.

the ledger client code in the browser doesn't control any of this...
