### ISSUE TITLE
Make placeholder ad clicks go to a page explaining what they will be

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#520]
https://www.brave.com/about_ad_replacement.html

**Comment by bbondy** [comment]
Doesn't sem to be working, was this fixed somewhere? Why was it closed?

**Comment by bridiver** [comment]
I updated the campaigns at Sonobi, but I don't know how quickly that is updated on their end.

**Comment by bbondy** [comment]
Thanks

**Comment by bbondy** [comment]
This is still not working, what can we do to fix this?

**Comment by bridiver** [comment]
they appear to be working correctly now along with the sandbox change
