### ISSUE TITLE
add/edit bookmark component should not link to about:bookmarks when already there

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5201]
Related to https://github.com/brave/browser-laptop/issues/5103
<img width="261" alt="screenshot 2016-10-24 19 38 24" src="https://cloud.githubusercontent.com/assets/831718/19667938/0a38e664-9a22-11e6-9bc8-c11b79b40a4e.png">

The "View all bookmarks" link (and surrounding gray area) should not be visible when the user is already on about:bookmarks

**Comment by bbondy** [comment]
clearing milestone, we can live with it but it'd be nice to have.

**Comment by buttersnipps** [comment]
Can I work on this bug?

**Comment by bsclifton** [comment]
@buttersnipps absolutely 😄 I'll self-assign it to reserve it for you! Let me know if you have any questions
