### ISSUE TITLE
Print Preview

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5207]
This is a feature request that came in from support. It would be nice to have a print preview similar to the one Chrome offers:

<img width="1120" alt="screen shot 2016-10-27 at 4 05 42 pm" src="https://cloud.githubusercontent.com/assets/490294/19788785/471d97de-9c5f-11e6-9cd5-21d5f006db42.png">

**Comment by jonathansampson** [comment]
Relevant Electron issue: https://github.com/electron/electron/issues/4890

**Comment by roughsoft** [comment]
pls ref this：
https://github.com/bjrmatos/jsreport-electron-pdf

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/print-requests-print-preview-and-simplify-page-option-similar-to-firefox/14477?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/print-prewiew-function/16752
>print preview function @ Menu bar>File -menu.

**Comment by bsclifton** [comment]
Happy to report this will be resolved when we move to [brave-core](https://github.com/brave/brave-browser) 😄 
![screen shot 2018-08-07 at 12 07 14 am](https://user-images.githubusercontent.com/4733304/43760104-020438a8-99d6-11e8-970a-15d186d0ca6b.png)
