### ISSUE TITLE
Vertical bookmark bar

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5208]
This came in from support. Firefox allows users to have a vertical bookmark bar as well as a horizontal one. It would be cool if we allowed users the same option. Screenshot attached.
![68115](https://cloud.githubusercontent.com/assets/490294/19789183/89dd78de-9c62-11e6-921d-62e698c4c605.png)

**Comment by luixxiul** [comment]
Duping to #2185

**Comment by clopez** [comment]
@luixxiul i think this was wrongly closed as duplicated: "vertical tabs" is not the same than "vertical bookmarks"

**Comment by luixxiul** [comment]
@clopez my bad, you're right..

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/10438

**Comment by rebron** [comment]
Closing. wontfix here, opened and tracking in brave-core
https://github.com/brave/brave-browser/issues/1063
