### ISSUE TITLE
Verified publisher icon should be a hexagon

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#5210]
**Describe the issue you encountered:**
The verified icon is in the shape of a circle:
![screen shot 2016-10-27 at 16 33 15](https://cloud.githubusercontent.com/assets/521861/19789264/38c0a9ac-9c63-11e6-8749-87c0c43235b0.png)

**Expected behavior:**
The verified icon should be in the shape of a `hexagon`, which is the One True Shape and Icon.
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS
- Brave Version: 0.12.7 @463c53d566a60805ade06158433408a008d8af4c
- Steps to reproduce:
  1. Go to Brave Payments tab with a verified publisher
  2. Examine shape of verified icon

@jkup 
### Appendix A: One True Icon

![https://github.com/brave/publishers/blob/master/app/assets/images/verified-icon.png](https://github.com/brave/publishers/raw/master/app/assets/images/verified-icon.png)
https://github.com/brave/publishers/blob/master/app/assets/images/verified-icon.png

**Comment by luixxiul** [comment]
cc @bradleyrichter

**Comment by srirambv** [comment]
@bradleyrichter  Can something like this be used for verified publishers  who are included 
![image](https://cloud.githubusercontent.com/assets/17010094/19801168/fb6c6864-9cf5-11e6-98a2-a7641e5e51bb.png)

and verified publisher who's not included
![image](https://cloud.githubusercontent.com/assets/17010094/19801259/6baeb5d2-9cf6-11e6-91ad-819d3ac13a35.png)

**Comment by mrose17** [comment]
@bradleyrichter - what is the story on this?

**Comment by jkup** [comment]
This merged with https://github.com/brave/browser-laptop/pull/5173 not sure why it didn't auto close.

**Comment by mrose17** [comment]
thanks!

**Comment by privatzee** [comment]
From the perspective of being color blind (~8% of the population), my immediate reaction was to wonder what the 2nd icon means. It looks to be maybe some kind of muted plum color. I thought, why that? 

But this approach actually looks grey, being recessive and washed out, saying it's sort of _not there_

![image](https://cloud.githubusercontent.com/assets/22591438/20083428/3fd3a634-a52a-11e6-9835-77f26ce287e6.png)

It's a bit of an accessibility thing.

**Comment by privatzee** [comment]
This might give an insight into what color blind users experience - these two look identical to me:
from http://www.vischeck.com/daltonize/

![image](https://cloud.githubusercontent.com/assets/22591438/20083787/6839ba30-a52c-11e6-9c42-0b48c733008b.png) 
![image](https://cloud.githubusercontent.com/assets/22591438/20083801/7a12721a-a52c-11e6-90c7-bb97c21789cd.png)
