### ISSUE TITLE
Datalist element not supported (github drop down for releases page)

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5213]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support is having issues with the tag dropdown on the releases page.

**Expected behavior:**
The dropdown should populate appropriately.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  User is on Mac.
- Brave Version:
  0.12.6
- Steps to reproduce:
  1. Have a relatively large list of tags.
  2. Edit a release and click on the tag dropdown.
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6367

**Comment by jonathansampson** [comment]
![tag-select](https://cloud.githubusercontent.com/assets/815158/19791495/5f7b0aca-9c76-11e6-8536-ed6c756d5f07.gif)

**Comment by luixxiul** [comment]
how about will it be by disabling the shields?

**Comment by Liunkae** [comment]
Disabling shields does not help. The problem appears to be Brave's lack of complete support for `datalist` elements.

What's even worse: clicking on an invisible "item" in the list causes Brave to crash.

**Comment by bbondy** [comment]
no owner yet, moving to 0.12.10

**Comment by Liunkae** [comment]
+1 from #4597.
