### ISSUE TITLE
named target links opened as background tabs should become active if clicked again as regular links

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#522]
Steps to replicate
1. go to brianbondy.com and ctrl/cmd-click "Brendan Eich"
2. a new background tab should open
3. click the same link again

the background tabs reloads the page, but remains inactive. Safari ignores the named target and opens a new link which is poor behavior IMO, but Chrome activates the tab.

**Comment by bbondy** [comment]
Yep, activate sounds right.  Thanks.

**Comment by luixxiul** [comment]
Was this implemented or will be?

**Comment by bridiver** [comment]
I don't believe so
