### ISSUE TITLE
Navigating back doesn't revert URL to the previous site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5221]
**Did you search for similar issues before submitting this one?**
Yes, didn't find

**Describe the issue you encountered:**
Navigating back doesn't revert URL to the previous site

**Expected behavior:**
Should revert the URL back to the previous site

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.12.7 RC2 (Same on 0.12.5,0.12.6 )

- Steps to reproduce:
    1. Visit http://omomovie.com/, shows Dangerous blocked site 
    2. On the same tab open https://brave.com
    3. Click on back button, shows the Dangerous blocked site but URL still shows https://brave.com

- Screenshot if needed:
![dangersite](https://cloud.githubusercontent.com/assets/17010094/19803544/3b24b032-9d01-11e6-8e3b-339a37310dc4.gif)

- Any related issues:

 cc: @diracdeltas

**Comment by alexwykoff** [comment]
I see about:safebrowsing instead of the original url.

<img width="1134" alt="screen shot 2016-11-04 at 4 32 28 pm" src="https://cloud.githubusercontent.com/assets/1434040/20023187/6932ee70-a2ac-11e6-9eae-35fec265cd35.png">

**Comment by srirambv** [comment]
Same on Windows

**Comment by diracdeltas** [comment]
that's expected
