### ISSUE TITLE
Selected bookmark/history items doesn't clear selection when clicked outside the view

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5223]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Selected bookmark/history items doesn't clear selection when clicked outside the view

**Expected behavior:**
Should clear selection when clicked outside the view
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.7 RC2 (Same on 0.12.6)
- Steps to reproduce:
  1. Ensure you have history entries/ multiple bookmarks 
  2. Select multiple bookmarks/history entries using Ctrl/Shift
  3. Click outside the entries, selected items doesn't get cleared, Have to click on an entry to clear the multiple selection
- Screenshot if needed:
  ![multiuncheck](https://cloud.githubusercontent.com/assets/17010094/19805832/a9879302-9d0e-11e6-939a-42ed32809805.gif)
- Any related issues:
  cc: @bsclifton 
  @alexwykoff /@luixxiul To verify for same behavior on MAC

**Comment by srirambv** [comment]
@bsclifton  This is working only on bookmarks. History entries still remains selected even after clicking outside the view. Checked it on both Windows and Ubuntu.

**Comment by bsclifton** [comment]
@srirambv I updated the title (and original post) for this issue to be only for Bookmarks Manager.  I totally missed the "History" part when looking into this.

I created a follow-up issue we can use to track the issue w/ History:
https://github.com/brave/browser-laptop/issues/5458
