### ISSUE TITLE
regression: drag area above URL bar was reduced to 2px

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5225]
**Did you search for similar issues before submitting this one?**
no

**Describe the issue you encountered:**
Regression on available drag area at top of address bar.

**Expected behavior:**
Top 6 pixels should be available for dragging window. Now, back to only 2px.

- Platform (Win7, 8, 10? macOS? Linux distro?):
mac OS Sierra 10.12

- Brave Version:
0.12.7dev-RC2
- Steps to reproduce:
    1. try to drag in normal area
    2. notice available height is now very limited (and remember fixing this yourself months ago)
    3. 

- Screenshot if needed:
![address bar dragging regression](https://cloud.githubusercontent.com/assets/13509546/19808062/f06b08b2-9cf0-11e6-934f-b67f41912a03.gif)

**Comment by privatzee** [comment]
related: #5168

**Comment by bbondy** [comment]
@bsclifton seems maybe related to titlebar work

**Comment by bsclifton** [comment]
caused by this: https://github.com/brave/browser-laptop/pull/5070
