### ISSUE TITLE
Implement Macintosh "Services" menu item

### ISSUE THREAD

**Issue by billstclair** [brave/browser-laptop#5229]
I'm accustomed to using a Services AppleScript I wrote that inserts the current song playing in iTunes wherever I can type text. It works great in all my other browsers. In Brave, however, though there's a "Services" item on the "Brave" menu, it has no sub-items.

**Expected behavior:**

- Platform: macOS Sierra (10.12, 16A320)

- Brave Version: 16A320

- Steps to reproduce:

1. Click in a text input area on a web page.

2. Click on the "Brave" menu at the top the screen.

3. Note that the "Services" item has no right-pointing triangle to denote sub-menu-items.

Work-around: Run the service to paste text into another application, e.g. TextEdit, that DOES implement the Services menu item, copy from there, and paste into Brave.

**Comment by luixxiul** [comment]
Closing this in favor of #4915
