### ISSUE TITLE
Better error message needed for Windows installer when already running Brave

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#523]
Currently we show this:
<img width="362" alt="screenshot 2016-02-01 12 35 06" src="https://cloud.githubusercontent.com/assets/831718/12725337/3dfc6980-c8e0-11e5-9631-a7c34a7ea300.png">

CC @SergeyZhukovsky

**Comment by paulcbetts** [comment]
This is actually already fixed if you update to the latest Squirrel.Windows
