### ISSUE TITLE
Can't open link by dragging to address bar

### ISSUE THREAD

**Issue by billstclair** [brave/browser-laptop#5230]
In general, I don't like it when a web site uses 'target="_blank"' for its links, causing them to create a new tab when clicked. But plenty of them do, and I've come to recognize which links will behave that way (though some sort of visual clue would be great, and there's another issue for that).

The normal way I get around that is to drag the link to the address bar. This works in every other browser I use, Firefox, Safari, Chrome, Opera, but it does NOT work in Brave.

I would like to either be able to drag a link to the address bar to open it in the same tab, or have an item on the right-click menu to do so. Maybe both.

Platform: macOS 10.12 Sierra (16A320)

Brave Version: 0.12.6

Steps to reproduce:
1. Open a web page with links
2. Drag one of the links to the address bar
3. Note that nothing happens

**Comment by Liunkae** [comment]
Related issue: #4654
