### ISSUE TITLE
Keyboard shortcut to open devtools not working

### ISSUE THREAD

**Issue by skeep** [brave/browser-laptop#524]
Although the menu says `cmd+shift+i` should open devtools but it seems not working. Same with `cmd+shift+j`

**Comment by bbondy** [comment]
You see this on OS X right? It works for me.  Maybe you need to focus the web contents?

**Comment by skeep** [comment]
ahh you are right my bad.I think it open at the background and I was expecting for a docked panel.

**Comment by bbondy** [comment]
np, the `cmd+shift+j` one is for the browser level dev tools to inspect the actual browser and not the pages.  I'll close this.
