### ISSUE TITLE
AVG is deleting latest update, severity High

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5241]
I've just heard from somebody I know (that I'd persuaded to try Brave) that AVG is deleting many files.

![image](https://cloud.githubusercontent.com/assets/22591438/19824865/457453ae-9d41-11e6-8847-c286ffaf580d.png)
#924

**Comment by privatzee** [comment]
...and her Brave won't start. It's not just about temp files.

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6420

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6433

**Comment by bbondy** [comment]
seems independent of what we are doing, so I'll move to 0.12.9 but @alexwykoff can you do, or ask someone to contact AVG support about this?

**Comment by srirambv** [comment]
+1 from [support]( https://linkbubble.zendesk.com/agent/tickets/6218)

**Comment by srirambv** [comment]
+1 from [sipport](https://linkbubble.zendesk.com/agent/tickets/6301)

**Comment by srirambv** [comment]
+4 from support
https://linkbubble.zendesk.com/agent/tickets/6585
https://linkbubble.zendesk.com/agent/tickets/6586
https://linkbubble.zendesk.com/agent/tickets/6584
https://linkbubble.zendesk.com/agent/tickets/6578

**Comment by srirambv** [comment]
+1 from support 
https://linkbubble.zendesk.com/agent/tickets/6575

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6601

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6595

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6594

**Comment by alexwykoff** [comment]
https://linkbubble.zendesk.com/agent/tickets/6593

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6588

**Comment by srirambv** [comment]
+2 from support
https://linkbubble.zendesk.com/agent/tickets/6615
https://linkbubble.zendesk.com/agent/tickets/6612

**Comment by privatzee** [comment]
It seems unlikely that people had their Brave deleted by AVG many days ago but waited until recently to report that. Therefore, it seems more likely that brand new installs of Brave are being deleted.

> AVG Surpasses **200 Million Users** Worldwide - AVG Now
now.avg.com/avg-surpasses-200-million-users-worldwide/ 
Mar 4, 2015 ... AVG now has 200 million active users. ... “This is a very significant milestone for AVG and one that not many companies ever achieve

------------------------
Also:

> 96% of unhappy customers don’t complain, however 91% of those will simply leave and never come back
https://www.linkedin.com/pulse/20130604134550-284615-15-statistics-that-should-change-the-business-world-but-haven-t

So if that general figure also holds for browser users (of a dev version), then the 18 reported here so far translates into ~327 users who won't come back.  (5/91 = 18/x)

**Comment by srirambv** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/6621

**Comment by bbondy** [comment]
What's the status from AVG? Are we getting on the application whitelisting? 
cc @diracdeltas

**Comment by srirambv** [comment]
Update from user Chris Harvan,([6633](https://linkbubble.zendesk.com/agent/tickets/6633),[6584](https://linkbubble.zendesk.com/agent/tickets/6584))
>I reinstalled 0.12.7 this morning and scanned it with the latest AVG update and had no problems. I’ll let you know if that changes, Brave is currently running again on my PC.

@bbondy ^

**Comment by srirambv** [comment]
+1 from support https://linkbubble.zendesk.com/agent/tickets/6635

**Comment by bbondy** [comment]
can we close this in that case?

**Comment by srirambv** [comment]
Yes we can close this. Another user Mark Wilkins ([6585](https://linkbubble.zendesk.com/agent/tickets/6585)) has also confirmed that after updating AVG antivirus it is not blocking Brave.

Closing #5241

**Comment by diracdeltas** [comment]
i submitted a request to AVG to whitelist us this weekend
