### ISSUE TITLE
about:bookmarks multiselect should be reset following drag-and-drop

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5249]
The ability to multiselect bookmarks within about:bookmarks is a welcome addition to 0.12.7dev so work should continue on it.

I've noticed that when I multiselect a set of bookmarks and then drag-and-drop those bookmarks into a different folder the bookmarks are correctly moved to the destination folder but the pattern of selected rows is not reset/cleared in the source folder. Bookmarks remaining in the source folder which happen to move into the selected rows are now selected and subject to a drag-and-drop action but it seems unlikely that that is what a user would want to do next.

To illustrate, notice that I have selected both the bookmark for google and the bookmark for bing:
![image](https://cloud.githubusercontent.com/assets/15019644/19828048/e29b2c12-9db3-11e6-8fb3-a2d473332175.png)

Moving the two selected bookmarks to another folder keeps the selection pattern which happens to land on yahoo and startpage:
![image](https://cloud.githubusercontent.com/assets/15019644/19828056/28520eec-9db4-11e6-8e8b-ee30ddb5f77f.png)

Ubuntu 16.10
Brave: 0.12.7
Electron: 1.4.20
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by CliqueBait** [comment]
@bsclifton Can I press to have this issue labelled as "bug"? I've never seen drag-and-drop from a multiselect work in this way in a browser's bookmark manager or in any other application.

**Comment by bsclifton** [comment]
@CliqueBait done 😄 I'll work on fixing this soon- thanks for filing this
