### ISSUE TITLE
If there is audio output in a pinned tab, unpinning it should not stop the audio.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5252]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support described a slightly complex scenario where due to pin-sync between windows, we unintentionally stop audio playback by closing the pinned tab when its window-clone is unpinned.

**Expected behavior:**
If audio is playing in a pinned tab, we should not close that pin but rather unpin it when its clone is unpinned.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  All
- Brave Version:
  `> 0.12.7`
- Steps to reproduce:
- Open https://dreamcatalogue.bandcamp.com/album/--24. Let's call it the first tab. 
- Start the playback. 
- Pin the first tab. 
- Open a new window. 
- Now bandcamp pinned tabs in both windows play at the same time. 
- Unpin and close the tab in the second window. 
- Change to the first window. You'll notice that the bandcamp tab here is gone. 
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6310

**Comment by cezaraugusto** [comment]
doesn't happen anymore in the latest public build. Please re-open if I'm wrong
