### ISSUE TITLE
Feature Request : support for ixquick search engine

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5254]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has requested the addition of the ixquick search engine.
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6341

**Comment by alexwykoff** [comment]
+1 from support : https://linkbubble.zendesk.com/agent/tickets/6606

**Comment by bsclifton** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/10868
