### ISSUE TITLE
Opening local SWF files does not open them in the browser

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#5256]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** When opening a local SWF (Flash) file in Brave, using File -> Open File (or CTRL+O), Brave offers to download the file.

**Expected behavior:** I would expect Brave to open and run the SWF file in the browser.

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested in Ubuntu 16.04 LTS

- Brave Version: 0.12.6

- Steps to reproduce:
    1. Open a SWF file via File -> Open File menu item or using CTRL+O.
    2. Note that the file is not opened in the browser, and instead is offered as a download.

**Comment by luixxiul** [comment]
Closing this in favor of #2385
