### ISSUE TITLE
Double clicking on Menu bar should maximize the browser

### ISSUE THREAD

**Issue by swarnava** [brave/browser-laptop#526]
OS: Mac 10.11.2

Expected behavior:
when double clicking on white menubar, it should maximize the browser

Actual Behavior: Nothing happening

**Comment by bbondy** [comment]
I think the correct behavior on Mac is to minimize no? For Windows it's maximize.

**Comment by swarnava** [comment]
![Screenshot of the issue](https://i.gyazo.com/6bf16a5959e66ed2bf8a49740a1c2ba6.gif)

**Comment by bbondy** [comment]
Maybe a configuration or depends on OSX version, mine minimizes with the same steps. Thanks for the video.

**Comment by rob-blasetti** [comment]
I have the same issue on:
OS: Mac 10.11.2

**Comment by psantos10** [comment]
I have the sane issue too: Os X El Capitan: 10.11.3
