### ISSUE TITLE
Backspace in <textarea> in a ShadowDOM causes "Back"

### ISSUE THREAD

**Issue by mikeal** [brave/browser-laptop#5260]
I've got a custom element with a textarea in a the ShadowDOM. When typing and hitting the backspace key we trigger the browsers "Back" behavior. I tried to add listeners and `e.preventDefault()` but it doesn't do anything.  

On Chrome I see a different issue where backspace just doesn't work at all, failing to remove any content from the textarea.
- Platform (Win7, 8, 10? macOS? Linux distro?):

MacOS
- Brave Version:

0.12.7

**Comment by Liunkae** [comment]
Related issues: #1760 and #4033.

**Comment by bsclifton** [comment]
I'm going to close this as I believe it was resolved with https://github.com/brave/browser-laptop/commit/e89aa8a9bed20506a0e73fbaedd42599d4d22fce

@diracdeltas please reopen if I am mistaken.  Thanks :smile:
