### ISSUE TITLE
Netflix states 'missing component'

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#5261]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Netflix (UK) not working on Brave 0.12.7. Release notes suggest this should work. Netflix reports there is a 'missing component' with error code 'M7701-1003'.

**Expected behavior:** Netflix should stream videos without issue.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 16.04 LTS

- Brave Version: 0.12.7

- Steps to reproduce:
    1. Attempt to stream a (UK) Netflix video. In this example, I was attempting to stream Black Mirror S03E03.
    2. Note error message as described rather than streaming video

- Screenshot if needed: https://pbs.twimg.com/media/Cv9vz0UWEAARRhP.jpg:large

**Comment by DivineOmega** [comment]
Ah, just read some of the issues related to when this was implemented. According to the following comment, Linux support for the necessary component is not yet available and should be in the next version.

https://github.com/brave/browser-laptop/issues/468#issuecomment-257070643

**Comment by jonathansampson** [comment]
Closing, on account of https://github.com/brave/browser-laptop/issues/468#issuecomment-257070643.
