### ISSUE TITLE
TripAdvisor crashes Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5264]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Navigating to this page crashes Brave

**Expected behavior:** Brave does not crash
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.7
- Steps to reproduce:
  1. Navigate to https://www.tripadvisor.com/Attraction_Review-g34515-d1541172-Reviews-Florida_Dolphin_Tours-Orlando_Florida.html
  2. Note crash

**Comment by jaydson** [comment]
Confirmed, it crashes on Linux too.
I'm running Brave 0.12.7 on Ubuntu 16.10.

First, Ubuntu freezes Brave, than it crashes.

The CPU behaviour during the crash:
![screenshot from 2016-10-30 00-45-27](https://cloud.githubusercontent.com/assets/72206/19834161/377c855a-9e3b-11e6-8bfd-57977643105d.png)

Here's the log (perhaps it can help):  
`brave crashed with SIGSEGV in strlen()`  

![screenshot from 2016-10-30 00-53-58](https://cloud.githubusercontent.com/assets/72206/19834166/6940f1f2-9e3b-11e6-9761-0371a7034ef3.png)

**Comment by jonathansampson** [comment]
TripAdvisor issues an XHR to `/MetaPlacementAjax`, which passes back an HTML response. The `onSuccess` method of the XHR (uses MooTools) then inserts this HTML as the `innerHTML` of a `<div>` in the document.

Among the injected HTML is an image tag for an image on another domain: https://cache-graphicslib.viator.com. When Brave attempts to load this image, the crash occurs. You can confirm this by the following steps:

1. Navigate to https://tripadvisor.com
2. Press F12 and open Brave's console
3. `document.createElement('img').src = 'https://cache-graphicslib.viator.com/graphicslib/thumbs360x240/2855/SITours/kennedy-space-center-day-trip-with-transport-from-orlando-in-orlando-334028.jpg')`

Upon running, you'll note that Brave crashes.

**Comment by BrendanEich** [comment]
@aekeus can you find the crash report for @jonathansampson ?

/be

**Comment by privatzee** [comment]
Just going to viator.com will crash. Adblock?

**Comment by jonathansampson** [comment]
@privatzee And it appears to crash even before the request is made, judging by my Fiddler sessions.

**Comment by privatzee** [comment]
There were two webcompat cases where turning off cookie protection per the site (that zone privacy site and pinterest) didn't help, but turning off cookie protection globally was an effective workaround. But turning off ABP globally isn't a workaround here, nor turning off _everything_ globally. 

It crashes even on plain http, so an OCSP call isn't involved. 

@jonathansampson Good catch, and I don't see anything going out with Wireshark either.

**Comment by privatzee** [comment]
I turned off wifi and it still crashes.

Just got this, if it helps (w7x64):

> Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Brave.exe
  Application Version:	1.4.20.0
  Application Timestamp:	58101677
  Fault Module Name:	4FB8.tmp.node
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5812b784
  Exception Code:	c0000005
  Exception Offset:	0000000000007ba3
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	6e69
  Additional Information 2:	6e6975158d09333bc943cf4028b20019
  Additional Information 3:	c3a6
  Additional Information 4:	c3a622f8c91831a3176eb4ee8166b2cb
Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by privatzee** [comment]
Brave does not get as far as trying to resolve DNS. 

On Windows:
1.  in cmd window: ipconfig /flushdns
2. with Brave, go to http://viator.com and crash
3. ipconfig /displaydns     # no entry for viator.com appears

-------------------

And a P.S.: putting viator.com in the hosts file doesn't prevent crashing.

**Comment by privatzee** [comment]
The crashing does not happen in Brave 0.12.3

**Comment by bbondy** [comment]
Should be fixed here:
https://github.com/brave/browser-laptop/issues/5270

Data files will be updated within the day, as of 0.12.8 we are changing that frequency to every 2h btw. No need to get an updated version to get the new data file that will fix the problem.

**Comment by aekeus** [comment]
Confirmed sites no longer crashing from master after #5270
