### ISSUE TITLE
Log in link not working on Pocket Extension registration page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5266]
**Describe the issue you encountered:** the log in link is not working on Pocket Extension registration page. Nothing but a autocomplete pulldown is shown.

**Expected behavior:** It should work.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.8 Preview 1
- Steps to reproduce:
  1. Open about:preferences#advanced
  2. Enable Pocket
  3. Click the link "Log in now"
- Screenshot if needed:
  ![pocket](https://cloud.githubusercontent.com/assets/3362943/19835683/5b7408ca-9ed1-11e6-83ed-f87e004fcedf.gif)
- Any related issues: #516

**Comment by darkdh** [comment]
I can't really reproduce this one on the same env.

**Comment by bbondy** [comment]
@alexwykoff @srirambv are you able to reproduce?

**Comment by srirambv** [comment]
I can reproduce this.  The hyperlink becomes active at a specific position on the `Login in now` text. 
 
![pkt](https://cloud.githubusercontent.com/assets/17010094/19881354/e0efc2f6-9ffc-11e6-873d-355a98e80b3c.gif)

**Comment by darkdh** [comment]
because the is a hidden input field overlay so the cursor will become i-beam
<img width="369" alt="screen shot 2016-11-01 at 14 49 42" src="https://cloud.githubusercontent.com/assets/11330831/19903074/9cda9af4-a043-11e6-8103-20d0563a6b13.png">

**Comment by darkdh** [comment]
@luixxiul could you try the same steps on Chrome?

**Comment by luixxiul** [comment]
I cannot reproduce either Brave or Chrome. Maybe you need to have an E-mail autofill pulldown there like in the gif.

**Comment by darkdh** [comment]
@luixxiul I can generate the autocomplete popup from https://www.facebook.com/login.php
and make it popup when the email input field is showed but not hidden
![123](https://cloud.githubusercontent.com/assets/11330831/19942124/0473afe6-a109-11e6-9553-7022e85e51d8.gif)

**Comment by luixxiul** [comment]
Hm I cannot reproduce the issue on the latest preview. I'm guessing the issue was resolved with other commits, otherwise the issue was on their site, not the browser.

**Comment by luixxiul** [comment]
@bbondy I think it is ok to remove the label and the milestone if nobody can reproduce the issue.

**Comment by luixxiul** [comment]
It works and I cannot reproduce the issue.
