### ISSUE TITLE
Visiting http://expressjs.com/ causes Brave to crash

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5270]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has reported that attempting to visit http://expressjs.com/ via a Google search causes Brave to crash.

**Expected behavior:**
Brave should visit the site normally.

- Platform (Win7, 8, 10? macOS? Linux distro?):
0.12.7

- Brave Version:
Reproduced on my OS X machine.

- Steps to reproduce:
    1. Search Google for 'express js'.
    2. Click on the http://expressjs.com/ link.

- Screenshot if needed:

- Any related issues:
https://linkbubble.zendesk.com/agent/tickets/6414

**Comment by privatzee** [comment]
Same as: TripAdvisor crashes Brave #5264 

Brave doesn't get as far as DNS lookup on this one, either. You can crash without any internet connection, so it's not the content. Now, this case demonstrates that there's nothing about the domain name which causes the crash. What remains?

**Comment by bbondy** [comment]
http://crossreferenceradio.com/ 
http://sweclockers.com 
http://expressjs.com/

**Comment by bbondy** [comment]
I'm taking a look, it looks like a crash in adblock, probably something always there but being hit because new rules in an adblock list update. Might be solveable with a new list update without a release, will know after investigating.

**Comment by privatzee** [comment]
sweclockers.com #5273 is not the same as the others that crash instantly.

**Comment by bbondy** [comment]
fixed, bad handling for host anchored filters with no host, people will get an update for the dat file without needing to do a release within an hour. Also I’ll fix it so we handle that better without crashing separate of uploading the data files in case it happens again.

**Comment by bbondy** [comment]
General problem fixed moving forward here:
https://github.com/bbondy/abp-filter-parser-cpp/commit/c42046dccac004f2838d2591c43cdfb4a42f3fa2

Adblock data files also patched so there's no immediate need for a release.  People will get it within a day.  By the way in 0.12.8 we made the checks more frequent than every day to every 2h.
