### ISSUE TITLE
Feature Request : Brave wallet sync

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5271]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has requested the ability to sync wallets between devices.

**Expected behavior:**
A user should not have to create individual wallets on every single device they own.
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6399

**Comment by zentagonist** [comment]
Closing as dupe of #10066
