### ISSUE TITLE
Brave crashes when trying to visit www.sweclockers.com

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5273]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has encountered a new crash when visiting www.sweclockers.com. Previously, 
they were able to visit the site without issue. They cleared their cache and saved files, still no improvement.

**Expected behavior:**
The site should be able to load normally.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows ia-32
- Brave Version:
  0.12.7
- Steps to reproduce:
  1.
  2.
  3.
- Screenshot if needed:
- Any related issues:
  https://linkbubble.zendesk.com/agent/tickets/6408

**Comment by privatzee** [comment]
A clue is a workaround to prevent the crash:
1. set Brave globally to _Block Scripts_
2. open www.sweclockers.com
3. no crash
4. then use Bravery to turn _Block Scripts_ off for that page
5. Brave crashes

**Comment by privatzee** [comment]
So naybe the problem is from here:
![image](https://cloud.githubusercontent.com/assets/22591438/19838498/d54c92dc-9ea6-11e6-987d-a06552ad6b14.png)

**Comment by luixxiul** [comment]
@bbondy should this also be closed based on https://github.com/brave/browser-laptop/issues/5270#issuecomment-257193934 ?

**Comment by bbondy** [comment]
Duping to this:
https://github.com/brave/browser-laptop/issues/5270
Please re-open if it still crashes though.

**Comment by bbondy** [comment]
leaving in milestone even know it's a dupe just for testing's sake.
