### ISSUE TITLE
Feature Request : Preference toggle to never remember passwords and never ask.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5275]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has asked for a means to stop prompts to remember passwords.

**Expected behavior:**
The user should be able to visit sites and not be prompted if they so choose.

- Any related issues:
https://linkbubble.zendesk.com/agent/tickets/6422

**Comment by bsclifton** [comment]
This should already be available, as of 0.11.6 :smile (screenshot from Preferences > Security): 
![screen shot 2016-10-30 at 1 15 15 pm](https://cloud.githubusercontent.com/assets/4733304/19839654/012dacc8-9ea3-11e6-9ba5-fe98f38fc7d9.png)

Please re-open if I misunderstood the issue or the the setting is not working
