### ISSUE TITLE
Feature Request : Linkclump Extension

### ISSUE THREAD

**Issue by MikeJayHarrison** [brave/browser-laptop#5277]
**Did you search for similar issues before submitting this one?**
Yes.

**Where can we find the extension?**
https://chrome.google.com/webstore/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj

**What do you like about the extension?**
Linkclump gives you the ability to drag a selection box around links using your mouse to quickly open as new tabs, open in new window, save as bookmarks, or copy to clipboard. This is very useful for both saving and accessing information. As someone who uses lists of links as opposed to more integrated bookmarks, this is an essential feature.

**Comment by srirambv** [comment]
Closing as its added in the extension list in [community](https://community.brave.com/t/the-list-of-the-requested-extensions/10278)
