### ISSUE TITLE
tab set not displayed until the window gets focused

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5280]
### Description

If you change the number of tabs per tab set under certain conditions, a blank tab set is displayed.

### Steps to Reproduce

  1. Open about:preferences#tabs on another window
  2. Set `20` on `the number of tabs per tab set`
  3. Go back to the original window
  4. Open 11 tabs
  5. Go back to the other window
  6. Set `10`
  7. Go back to the original window
  8. Select the only tab on the tab page 2
  9. Go back to the other window
  10. Set `20`

**Actual result:**

The original window displays a blank tabs bar, until the window gets focused.

**Expected result:**

It should not display the blank tabs bar

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

 
Brave: 0.19.80 
rev: 7d07299a5d462d3c9ae32cfbfbe7296cc57c89b9 
Muon: 4.5.13 
libchromiumcontent: 62.0.3202.75 
V8: 6.2.414.36 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

Yes.

**Comment by bsclifton** [comment]
Removing this from the milestone; let's work with @bradleyrichter or @bbondy if we want to reassign it into a milestone

**Comment by bradleyrichter** [comment]
Nice find but let's keep it as LP until we hear more complaints.

**Comment by luixxiul** [comment]
Updated the 1st post to reflect the latest status.
