### ISSUE TITLE
Add widevine support for linux

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5282]
We have to implement it in a different way completely (over HTTP endpoint instead of using component updater)

**Comment by bbondy** [comment]
Removing this from the milestone for now

**Comment by BrianA-MN** [comment]
Is there a status on this request.  It still is not in the 0.12.15 release.  Running Slackware64 -current with 4.4.38 kernel.  Have installed chromium-pepperflash-plugin and can turn-on and run flash, but not any DRM Flash.  Have also installed chromium-widevine-plugin and it doesn't produce the widevine optional switch under securities.  Packages are for Slackware and available from AlienBob's repository at http://bear.alienbase.nl/mirrors/people/alien/slackbuilds/  hope this will give some developer help.  Thanks.

**Comment by sd86** [comment]
+1

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/when-widevine-will-be-suported-in-linux/4955)

**Comment by arzhed** [comment]
+1

**Comment by kirkins** [comment]
+1

**Comment by alexwykoff** [comment]
@posix4e how is this looking?

**Comment by posix4e** [comment]
Ooh still working on it sorry

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/widevine-issue-on-netflix/9279

**Comment by gantonopoulos** [comment]
+1

**Comment by posix4e** [comment]
Sorry for being lame yall

**Comment by ryanmusante** [comment]
Looking forward to the release.

**Comment by tomjshore** [comment]
+1

**Comment by posix4e** [comment]
I am curious if any of y'all want to help me get this done. We are actually kinda close.

**Comment by dl00** [comment]
what kind of help is needed?

**Comment by Eadword** [comment]
+1

**Comment by williamdaconceicao** [comment]
+1

**Comment by bsclifton** [comment]
Hi there folks- thanks for being patient. Unfortunately, we won't be addressing this with our current Muon code base.

We ARE planning to do this with Brave Core, which is replacing our current Muon based product. You can subscribe here and follow along:
https://github.com/brave/brave-browser/issues/31

Closing as `wontfix` since we won't be addressing with `browser-laptop`

**Comment by sTiKyt** [comment]
That why i stoped using of my favorite Brave browser..
