### ISSUE TITLE
Unable to access Lenovo Ix2-DL unless Cookie control is set at global

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5284]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From [support](https://linkbubble.zendesk.com/agent/tickets/6122) 
>I downloaded the new release. I still cannot access my Lenovo Ix2-DL unless I remove all security. 

**Expected behavior:**
Should be able to access the Lenovo Ix2-DL page without changing settings at global level

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 

- Brave Version:
0.12.4/0.12.5

- Steps to reproduce:
User is able to access the page only by allowing all cookies at a global setting. Setting it at page level doesn't allow user to navigate between pages

- Screenshot if needed:

- Any related issues:

 cc: @jonathansampson

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
