### ISSUE TITLE
blue artifact under hamburger menu after loading a few pages

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#529]
After loading a few pages, I see a blue line underneath the hamburger menu. 

<img width="109" alt="screen shot 2016-02-01 at 10 44 58 am" src="https://cloud.githubusercontent.com/assets/552390/12727260/016c12a4-c8d1-11e5-9341-2085b8f4bdf0.png">

**Comment by asadotzler** [comment]
Tested on 0.7.12 on OS X.

**Comment by bbondy** [comment]
Likely text selection being allowed on the UI. I need to disable I think? Clicking close might clear the selection.

**Comment by bradleyrichter** [comment]
could this be a broken progress/loading bar remnant?

**Comment by bbondy** [comment]
I'm fairly sure I've seen the blue underline thing before too.  Steps to reproduce would lead to q quick fix.

**Comment by asadotzler** [comment]
reload https://news.ycombinator.com/news a couple of times and I get it consistently. clicking the bar makes it go away.

**Comment by asadotzler** [comment]
reload using keyboard shortcut command+r reproduces it for me on just about every load or every other load. reload by clicking the reload button in the toolbar does not reproduce it for me at all.

**Comment by bbondy** [comment]
Got it with your reload steps on hackernews. Fixed. Thanks!

**Comment by bbondy** [comment]
At least I seemed to have fixed for that page but seen it again somewhere else in an about: age so re-opening this.

**Comment by luixxiul** [comment]
@bbondy Are you still seeing this?

**Comment by bbondy** [comment]
I don't think so but maybe I'm trained to overlook it.  I'll keep an eye on it.  Let's leave open for a bit longer to see if we confirm.

**Comment by bsclifton** [comment]
Closing this long-standing one. Please reopen if we see it again :smile:
