### ISSUE TITLE
Provide Password Manager/Extension icon in right click context menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5292]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
No icon shown for password manager/extensions in right click context menu

**Expected behavior:**
Provide Password Manager/Extension icon in right click context menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.8 Preview 1

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19862488/76d35122-9f88-11e6-9a48-d4a7317472ad.png)

- Any related issues:

**Comment by bbondy** [comment]
We aren't getting a new electron for this release so moving it to 0.12.10, sorry about that.

**Comment by bbondy** [comment]
We ended up doing 1.4.24 for a security issue so I included this in 0.12.9 after all.
