### ISSUE TITLE
minor: no context menu for pasting into "Find on Page..." box

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5294]
**Did you search for similar issues before submitting this one?**
y
**Describe the issue you encountered:**
you have to use CTRL-v to paste
**Expected behavior:**
should have a context menu from a right-click
- Platform (Win7, 8, 10? macOS? Linux distro?):

w7x64
- Brave Version:

- Steps to reproduce:
    1. hit CTRL-f
    2. put mouse pointer into the search box
    3. right-click to get context menu with which to paste
  4. but get no context menu

![image](https://cloud.githubusercontent.com/assets/22591438/19870816/9431fd68-9f88-11e6-8771-18f181977de5.png)

Sorry if it's too minor to bring up now, but needs to be there eventually.

**Comment by luixxiul** [comment]
Duping to #4975
