### ISSUE TITLE
preferences page tabs broken

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#5295]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
going to about:preferences and clicking on the pref tabs is sometimes broken. a lot of page errors appear in the console.

- Platform (Win7, 8, 10? macOS? Linux distro?):
os x

- Brave Version:
0.12.7

- Any related issues:
may be the same cause as https://github.com/brave/browser-laptop/issues/5134

**Comment by diracdeltas** [comment]
at least one of the errors was fixed by e882655ec8a8cb7a6c3d62b926e1364235f108cd

**Comment by privatzee** [comment]
no problems seen in w7x64, even after doing "Never include this site"

**Comment by diracdeltas** [comment]
this only occurs sporadically for me. usually the prefs page works fine and then clicking on the tabs stops working. based on https://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=GeneralTab, maybe the react component is getting unmounted too early

**Comment by diracdeltas** [comment]
actually it only occurs after switching to the payments tab, whereupon the sortableTable error occurs. assuming this is fixed by e882655.

**Comment by bsclifton** [comment]
Removed milestone since it was recorded with https://github.com/brave/browser-laptop/issues/5236 and fixed with https://github.com/brave/browser-laptop/pull/5237

**Comment by alexwykoff** [comment]
per @bsclifton's notes, this is a duplicate
