### ISSUE TITLE
Check that we're using these babel / webpack optimizations

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#53]
Check that we're using these babel / webpack optimizations:
> "optimisation.react.constantElements",
> "optimisation.react.inlineElements",

**Comment by hzoo** [comment]
In Babel 6, currently the react preset doesn't contain those plugins http://babeljs.io/docs/plugins/preset-react/.

Equivalents are:
http://babeljs.io/docs/plugins/transform-react-inline-elements/
http://babeljs.io/docs/plugins/transform-react-constant-elements/

```js
// new .babelrc
{
  "presets": ["react", "es2015"],
  "plugins": [
    "transform-react-inline-elements",
    "transform-react-constant-elements"
  ]
}
```

**Comment by bbondy** [comment]
Able to do a PR?

**Comment by hzoo** [comment]
https://github.com/brave/browser-laptop/pull/280
