### ISSUE TITLE
Lion on top right is using wrong design resource

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#530]
@bradleyrichter Can you give me the right one?

**Comment by bradleyrichter** [comment]
new lion image is shorter in aspect ratio, and we need to add something to handle retina.

**Comment by bbondy** [comment]
OK, just attach resources here when you get a chance. Thanks!

**Comment by bradleyrichter** [comment]
![bravebtn](https://cloud.githubusercontent.com/assets/13509546/12729138/1eb26b84-c8da-11e5-8078-70c064df8c6d.png)
![bravebtn2x](https://cloud.githubusercontent.com/assets/13509546/12729140/1eb84d38-c8da-11e5-9ba0-3de5df44d000.png)
![bravebtn3x](https://cloud.githubusercontent.com/assets/13509546/12729139/1eb411b4-c8da-11e5-8672-b66aca2675ce.png)

**Comment by psimyn** [comment]
could also potentially fix right alignment for https://github.com/brave/browser-laptop/issues/555
