### ISSUE TITLE
about:newtab - display local temp/weather

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5302]
The user should be able to opt-in to displaying local temperature and weather data on the new tab page

**Comment by cezaraugusto** [comment]
Where would we get that info?

**Comment by srirambv** [comment]
@cezaraugusto https://apidev.accuweather.com/developers/ would this help?

**Comment by jonathansampson** [comment]
Thoughts on resurrecting this issue? Just spoke with a user who wanted something like this on their dashboard. I love the idea :)
