### ISSUE TITLE
about:newtab - ability to customize top-sites area

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5304]
Ability for user to customize the top-sites area:
- Add new items
- show sites from a bookmark folder
- etc

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/personalizing-my-thumbnails/7169

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/win64-laptop-v0-19-95-general-feedback-minor-issues/11283?u=eljuno
