### ISSUE TITLE
about:newtab - avoid flash of unstyled content

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5309]
Because the page is loading an image remotely, opening a new tab has a very brief flash (from white, to gradient, to the image that gets loaded).

We should be fading in gradually to avoid causing a flash for the user

**Comment by bsclifton** [comment]
Reopening after @bbondy had tried it out and it's noticeably slow. Let's see what we can do to fix this

**Comment by bbondy** [comment]
moving to 0.12.10

**Comment by bsclifton** [comment]
Cache-Control header was added to all of the images (max age = 1 year) so it should always load from cache (after it does the initial load). It could still be better though

**Comment by bbondy** [comment]
I think we should share a single instance of a webview for newtab pages to make it instant, but I think the cache control improved things a lot so I'm removing the priority for now.

**Comment by bsclifton** [comment]
A really solid fix was put together by @josiah-keller in https://github.com/brave/browser-laptop/pull/6590. Setting the background to black made the flash more pronounced... the problem is definitely the default background color (white) when the webview object gets loaded.

I searched the Electron issue log and found https://github.com/electron/electron/issues/5175, which captures this exact issue. We should be able to [fix this Muon](https://github.com/brave/muon) by patching Chromium.

It's hard to determine a priority for this issue since it's not horrible... but fixing it would be a very nice touch. I'd like to give a heads up to some folks **just in case you see related code** when you're in Muon: @bridiver @bbondy @darkdh @diracdeltas 

There is a similar issue captured in Electron's issue log with https://github.com/electron/electron/issues/861 which is for the BrowserWindow object. A work-around is provided there for that case (in case we'd like to incorporate it with our main window).

**Comment by bsclifton** [comment]
+1 via https://github.com/brave/browser-laptop/issues/8128

**Comment by luixxiul** [comment]
I thought @petemill was working on this issue recently. I am sorry if I am wrong.
