### ISSUE TITLE
address / search bar focus outline is ugly

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#531]
The focused state of the addressbar / searchbar is kind of ugly with a single dark outline and then a blurred blue focus ring. It'd look a lot better as a 3px solid light blue focus ring. Proposal attached.

![address-focus](https://cloud.githubusercontent.com/assets/552390/12728044/c7156d68-c8d4-11e5-9d04-735e43caf07c.jpg)

**Comment by bbondy** [comment]
CC @bradleyrichter 
FWIW Brad, I think the proposed one looks cleaner.

**Comment by bradleyrichter** [comment]
Sure. I'll minimize it in the next batch of UI refinements. @bridiver may have some info on needing some of this for an anti-aliasing fix.

**Comment by bridiver** [comment]
The anti-aliasing was only an issue for the 1px border which is why I added the "shadow". A multi-pixel border should be fine, but stood out too much with the darker blue. I think the real issue with the current status bar is that the line is much darker than the shadow, but I think it looks good solid as well with the lighter blue

**Comment by bbondy** [comment]
@bradleyrichter I think you fixed this here:
https://github.com/brave/browser-laptop/commit/893555aa62d16a40bb8f2685706b3b0d572109df

Please close this if you agree.

**Comment by bradleyrichter** [comment]
yep...much improved. Closing this one.

**Comment by bridiver** [comment]
I haven't seen the new one yet, but just FYI you can change the box shadow color independent of the border color to match them

**Comment by bbondy** [comment]
New one looks great

**Comment by bradleyrichter** [comment]
@bridiver how would we go about extending the blend if we wanted to try something more like git's message window border? over time I will keep adding detail without giving up the clean look and this might be nice to try:

![screen shot 2016-02-02 at 9 38 13 am](https://cloud.githubusercontent.com/assets/13509546/12758430/fc184816-c990-11e5-9966-23c23dd78398.png)

**Comment by bridiver** [comment]
not sure what you mean by "extending the blend", but here are the computed border styles for github:

border-bottom-color: rgb(221, 221, 221);
border-bottom-left-radius: 0px;
border-bottom-right-radius: 0px;
border-bottom-style: dashed;
border-bottom-width: 1px;
border-image-outset: 0px;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(204, 204, 204);
border-left-style: solid;
border-left-width: 1px;
border-right-color: rgb(204, 204, 204);
border-right-style: solid;
border-right-width: 1px;
border-top-color: rgb(204, 204, 204);
border-top-left-radius: 3px;
border-top-right-radius: 3px;
border-top-style: solid;
border-top-width: 1px;
box-shadow: rgba(0, 0, 0, 0.0745098) 0px 1px 2px 0px inset;
