### ISSUE TITLE
about:newtab - favicons are not always shown

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5310]
When visiting sites, the favicon URL is being captured (thanks to https://github.com/brave/browser-laptop/pull/5285)

Not all of the sites are showing their favicon though. It seems this can be fixed by bookmarking the site.

Steps to reproduce:
1. Visit https://duckduckgo.com/about
2. Open about:newtab and you should see this site without an icon
3. Bookmark the site
4. Open about:newtab and you should see duckduckgo with the correct favicon

**Comment by srirambv** [comment]
FavIcons is inconsistent on tiles. Not all tiles have the favicon

![image](https://cloud.githubusercontent.com/assets/17010094/19921113/5576ba3a-a0d4-11e6-8d95-6b66c52ff309.png)
