### ISSUE TITLE
regression: deciding conversion candidate on URL bar searches the candidate

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5313]
**Describe the issue you encountered:** With Google IME, deciding conversion candidate on the URL bar by hitting enter key searches the candidate on the search engine

**Expected behavior:** it should just decide the candidate. It should not search the candidate until hitting enter key again. This does not happen on 0.12.7

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Install Google IME (Japanese)
    2. Hit ``a`` on the URL bar, which gives you ``あ`` as a conversion candidate
    3. Hit enter key to decide the candidate
    4. The search result of ``あ`` is displayed

- Screenshot if needed:

- Any related issues:

I'm setting a milestone as it is annoying and should be fixed asap

**Comment by bbondy** [comment]
@diracdeltas could you look on it? I'm going to move this to 0.12.9 though but let me know if there are strong objections.

**Comment by luixxiul** [comment]
FYI I cannot reproduce the issue on Windows.
