### ISSUE TITLE
deciding and searching conversion candidate not working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5315]
**Describe the issue you encountered:** Hitting enter key two times fast to decide conversion candidate does not search it on the URL

**Expected behavior:** it should work. At first hitting enter key should decide the conversion candidate, and then the candidate should be searched.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open http://ejje.weblio.jp/sentence/content/brave for example
    2. Enable Google IME (Japanese)
    3. Select the URL on the URL bar
    3. Hit ``a`` on the URL bar, which gives you ``あ`` as a conversion candidate
    4. Hit enter key **two times** fast in order to decide the candidate and search it
    5. http://ejje.weblio.jp/sentence/content/brave is still opened

- Screenshot if needed:

- Any related issues: #5313

**Comment by bbondy** [comment]
cc @diracdeltas 
=> 0.12.9

**Comment by luixxiul** [comment]
FYI I cannot reproduce the issue on Windows.
