### ISSUE TITLE
save tab-mute state when unloading so they don't start playing when reloaded

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5316]
Every day, I play a funny game called "find the noisy tab". This happens when you mouse-hover over a tab that was unloaded which had a video in it which is now reloaded, and is also set to autoplay. (all youtube pages for example)

cc @bbondy

**Comment by bbondy** [comment]
I'm afraid that the tab level mute is not commonly used by people so they won't realize why there is no sound.  I think it would be better handled by not autoplaying videos option that we'll add later. I think this would be a dupe of that.

**Comment by bradleyrichter** [comment]
@bbondy I can see that concern.

How about this option:  (Add "Mute All Windows" command with Option+M)

![image](https://cloud.githubusercontent.com/assets/13509546/20163297/318ec5e0-a6b0-11e6-8699-cd62fc407e65.png)
