### ISSUE TITLE
Findbar has style issues (alignment)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5317]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Findbar has a style issue (see screenshot)

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:
0.12.7

- Steps to reproduce:
    1. Launch Brave and open a page which sets a color for the tab
    2. Open the findbar
    3. Be sad because it looks like the screenshot :frowning_face: (notice the alignment problems)

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/4733304/19895941/eab743d2-a00f-11e6-8ff5-6c297d8a802f.png)

It should look like this:
![image](https://cloud.githubusercontent.com/assets/4733304/19896625/395548f2-a012-11e6-9e7b-0cd874df21e9.png)

- Any related issues:

**Comment by luixxiul** [comment]
I think this is duping to #3526. Though it was labelled ``wontfix``, the styling may seem to be a bug.

**Comment by bsclifton** [comment]
@luixxiul this one is actually fixing the way the tabs and findbar align :smile: I will go through the ticket you posted and create a new issue for the coloring of the actual input box
