### ISSUE TITLE
Failed at the brave@0.7.12 check-security script 'nsp check'

### ISSUE THREAD

**Issue by jacobmischka** [brave/browser-laptop#532]
I'm probably doing something wrong but I can't tell what it is, the same setup that worked with 0.7.11 no longer works with 0.7.12.

Console output: https://gist.github.com/jacobmischka/562b5fcbe755fe3cbd7d

I don't have an npm-debug.log in the directory it mentions.

**Comment by bbondy** [comment]
@aekeus is doing a push soon that gets rid of that library.

**Comment by jacobmischka** [comment]
Okay great, thank you for the update.

**Comment by bbondy** [comment]
This was merged by the way so it should work now. Closing.
