### ISSUE TITLE
Style for darker colored "Top Sites" entries is hard to see

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5324]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The gray bar has transparency and can be hard to see when you mouse over. You would want to mouse over to pin the site or bookmark/unbookmark, or remove it from the "Top Sites" list

**Expected behavior:**
Should be easier to see

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
0.12.8

- Steps to reproduce:
    1. Launch Brave and navigate to https://css-tricks.com/cascading-svg-fill-color/
    2. Bookmark this site, so it shows in the new tabs screen
    3. Hover the mouse over the entry (it should be a black box with a gray C)

- Screenshot if needed:
![screen shot 2016-11-01 at 1 31 07 pm](https://cloud.githubusercontent.com/assets/4733304/19906396/d9757062-a037-11e6-96c2-82b10398d38b.png)

- Any related issues:

**Comment by bradleyrichter** [comment]
fix for this:

![image](https://cloud.githubusercontent.com/assets/13509546/19991256/34470d88-a1f1-11e6-8337-80cff96e7cbd.png)

![image](https://cloud.githubusercontent.com/assets/13509546/19991268/42073344-a1f1-11e6-9dca-6e5a9a3beb29.png)

**Comment by bbondy** [comment]
fixed milestone to 0.12.9 since newtab isn't in 0.1.28
