### ISSUE TITLE
Scrolling doesn't feel right. Blurry, vibrating and unreadable text.

### ISSUE THREAD

**Issue by NQAT** [brave/browser-laptop#5325]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
 When scrolling long web pages the text becomes blurry and almost unreadable. It flickers and vibrates as you scroll. More so than other browsers. I have checked and unchecked smooth scrolling and it makes no difference.
**Expected behavior:**
Smoother scrolling. Text you can read as you scroll.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux ubuntu
- Brave Version:
Brave: 0.12.5
- Steps to reproduce:
    1. Open brave browser and open chrome or firefox browser side by side brave
    2. Visit a site with a lot of text or long web page in both browsers
    3. scroll web page and compare smoothness of text in each browser.

- Screenshot if needed:

- Any related issues:

**Comment by pixelass** [comment]
I also experience this "vibrating" behavior and also random flickering (white blocks appearing and disappearing for a split second). No blur though.

**Comment by pixelass** [comment]
Fior me the issue happens when I load a performance intense website. Other tabs are affected and the issue does not resolve when the hungry tab is closed. After restarting the browser everything seems fine. Maybe some kind of caching problem?

**Comment by bsclifton** [comment]
@NQAT @pixelass I'm curious if you both experience this issue still? 

If so, we have some command line arguments you can try [which are documented in our wiki](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page):
```
--ignore-gpu-blacklist
--disable-gpu
```

**Comment by pixelass** [comment]
I don't use brave anymore. I only use it for testing issues anymore. last time I checked the issue was gone. It might have been due to too many open tasks in OS X in general.
I'd have to check some intense experiments to say for sure.

**Comment by bsclifton** [comment]
@pixelass awesome, thanks for reporting back 😄
