### ISSUE TITLE
Brave does not accept Let's encrypt certificates

### ISSUE THREAD

**Issue by mbalmer** [brave/browser-laptop#5326]
Browsing a HTTPS site which uses a Let's Encrypt certificate leads to an error message.

Please include the Let's encrypt root certs in Brave.

**Comment by bbondy** [comment]
wfm on brianbondy.com

could you give us an example?

**Comment by mbalmer** [comment]
wfm on brianbondy.com

could you give us an example?




Sure.  https://www.msys.ch/ uses a certificate issued by the Let’s encrypt CA.  My
brave browser on macOS displays an error message when trying to access this
site.

**Comment by mbalmer** [comment]
fwiw, on iOS it works.

**Comment by bbondy** [comment]
@diracdeltas any ideas? For me the cert looks ok on www.msys.ch as well.

**Comment by diracdeltas** [comment]
this is a problem with the site's SSL configuration, not Brave. www.msys.ch does not serve a complete certificate chain, so the browser doesn't trust it unless it has the trust chain cached already. https://www.ssllabs.com/ssltest/analyze.html?d=www.msys.ch

 FWIW let's encrypt is not yet a root certificate in any browser or OS, it's an intermediate signed by Identrust.

**Comment by mbalmer** [comment]
this is a problem with the site's SSL configuration, not Brave. www.msys.ch does not serve a complete certificate chain, so the browser doesn't trust it unless it has the trust chain cached already. https://www.ssllabs.com/ssltest/analyze.html?d=www.msys.ch

FWIW let's encrypt is not yet a root certificate in any browser or OS, it's an intermediate signed by Identrust.

So I will reconfig all sites under my control that use letsencrypt to supply a full cert chain, and cross fingers.

Other browsers do not have this issue btw. (besides Tor browser), but your explanation makes sense.

Maybe Let's Encrypt should make their users aware of the issue.  It is getting popular...



- mb

**Comment by mbalmer** [comment]
this is a problem with the site's SSL configuration, not Brave. www.msys.ch does not serve a complete certificate chain, so the browser doesn't trust it unless it has the trust chain cached already. https://www.ssllabs.com/ssltest/analyze.html?d=www.msys.ch

FWIW let's encrypt is not yet a root certificate in any browser or OS, it's an intermediate signed by Identrust.

So I will reconfig all sites under my control that use letsencrypt to supply a full cert chain, and cross fingers.

Other browsers do not have this issue btw. (besides Tor browser), but your explanation makes sense.

Maybe Let's Encrypt should make their users aware of the issue.  It is getting popular...

I reconfigured www.msys.ch to serve the full certificate chain, and now it works as expected.  I'd say the issue can be closed.  Tor browser and Firefox Developer Edition now work as well.
