### ISSUE TITLE
Add standalone file for CSS animations

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5328]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
We should have a separate file for animations so we can DRY our `keyframes` into one file and reuse them when needed.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
n/a

- Brave Version:
n/a

- Steps to reproduce:
n/a

- Screenshot if needed:
n/a

- Any related issues:
n/a

**Comment by bbondy** [comment]
0.12.9? Marking as such for now.
