### ISSUE TITLE
Create download manager

### ISSUE THREAD

**Issue by elsehow** [brave/browser-laptop#533]
the browser prompts me for a download, but no feedback is given after i press "save", and no fie appears n the directory (not even a hidden file)

puzzlingly, after i press Save again, it tells me that the file already exists, and asks if i want to overwrite it....

**Comment by bbondy** [comment]
It downloads to your home directly in Downloads right now. We still need to create a Downloads manager to make it more visible what's happening.

**Comment by elsehow** [comment]
would that be `~/Downloads`? nothing appears in this dir for me

**Comment by elsehow** [comment]
I think this could be a permissions problem. in my experience, [creating a write stream](https://github.com/brave/browser-laptop/blob/master/app/dataFile.js#L47) requires special perms.

**Comment by SJ-Diamond** [comment]
Hopefully you plan not use the standard Chromium design for download manager and other Chromium related internal pages, because they look really ugly and are too simplistic.

**Comment by elsehow** [comment]
i say add whatever is easiest. presumably those components are built in a modular way, and can be easily re-styled

**Comment by SJ-Diamond** [comment]
Agreed, Styling would be also sufficient enough. As long as the end result looks more in line with the Brave design, as design consistency is always a good thing.

**Comment by weems** [comment]
@elsehow @bbondy As long as we have a place where you see that the file has downloaded, and can open, pause, cancel etc, I think that is likely what most users will care about.

**Comment by bbondy** [comment]
API to do this is fully available already here:
https://github.com/atom/electron/blob/master/docs/api/session.md#event-will-download

**Comment by 3esmit** [comment]
I think this is a really important feature for daily use, I just got nuts trying to make a download in Brave Browser. It does the download but silently...

**Comment by bbondy** [comment]
Implemented here, will be in 0.8.3
https://github.com/brave/browser-laptop/commit/1f949f470a98ed146868d4e08b4943322ef92458
