### ISSUE TITLE
On new tab page, sometimes a topSite doesn't even have a letter

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5332]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
On new tab page, topSites displays site's first title letter as a fallback if it couldn't find any favicon. Sometimes a letter isn't even shown. It happened [for this URL](https://linkbubble.zendesk.com/access/unauthenticated?return_to=https%3A%2F%2Flinkbubble.zendesk.com%2Fagent%2F).

**Expected behavior:**
If there's no site's favicon, letters should always appear as fallback.

- Platform (Win7, 8, 10? macOS? Linux distro?): any

- Brave Version: n/a

- Screenshot if needed:
![0eae66d6-78c8-11e6-872a-21df2a90c845](https://cloud.githubusercontent.com/assets/4672033/19910543/c8ac7ac2-a074-11e6-84ed-c90a30ef1262.png)

**Comment by bbondy** [comment]
Is there really no letter or maybe the favicon is the same color as the tile and is only 1 color?

**Comment by cezaraugusto** [comment]
Not easy to reproduce but it happened a few times. Yes, no letter and there's no favicon as well. Different from accessing like https://brianbondy.com where both themeColor and favicon share the same color.

Actually this bug was pointed by you on our old newtab's PR (#3199) and I confirmed a while after. Setting here just as a reference, can be closed if there's no new reports.

**Comment by bsclifton** [comment]
@bbondy @bradleyrichter would it be acceptable (if the title is blank) to use the first letter of the actual domain?

**Comment by bbondy** [comment]
up to @bradleyrichter maybe that would lead to a lot of W for www., if Brad wants this you could skip that prefix though.

**Comment by bradleyrichter** [comment]
sounds like a reasonable fallback

**Comment by bsclifton** [comment]
to be consistent with the history page, I was thinking we could just use the domain (not the subdomain)
