### ISSUE TITLE
about:newtabs - drag and drop not working for Top Sites items

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5336]
It seems the drag is working but not the drop :frowning_face: 

May be related to the code that needs to change with https://github.com/brave/browser-laptop/issues/5321

**Comment by bsclifton** [comment]
At first, I thought that maybe it was failing because I didn't have the npm package installed.  I cleared and re-ran npm install and still get the problem.

Opening a console shows this:
```
browser.js:40 Uncaught Invariant Violation: Cannot call hover while not dragging.invariant @ browser.js:40hover @ dragDrop.js:116(anonymous function) @ DragDropManager.js:74handleTopDrop @ HTML5Backend.js:540
```

**Comment by srirambv** [comment]
@cezaraugusto doesn't work for me on Windows

![5336_fail](https://cloud.githubusercontent.com/assets/17010094/20297884/c9496e7c-ab0a-11e6-9220-ca09290026da.gif)

**Comment by cezaraugusto** [comment]
@srirambv couldn't reproduce, drag and drop is working, also changes (switching order) are saved after closing/reopening the app. Running 0.12.9.
