### ISSUE TITLE
about:newtabs - have relevant results shown (implement frecency)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5338]
cc: @bbondy @bradleyrichter 

With some favorite sites up in the "Top Sites" area, the items are not easy to identify.
![screen shot 2016-11-01 at 5 19 07 pm](https://cloud.githubusercontent.com/assets/4733304/19912411/849dd032-a057-11e6-83ce-d8b684b9523f.png)

We need to find a better way to represent bookmarks which have the same favicon:
- having a bunch of medium.com posts pinned or in favs, which will all have the same icon
- bookmarking multiple parts of brianbondy.com :smile: 
- tweets

**Comment by luixxiul** [comment]
Eventually you will have this one..

<img width="556" alt="screenshot 2016-11-02 11 41 43" src="https://cloud.githubusercontent.com/assets/3362943/19914846/629c6b8e-a0f1-11e6-87f6-f91632949b13.png">

Is this a card game? :-D

**Comment by bsclifton** [comment]
@srirambv brought up a great concern here (similar to @luixxiul's concern) https://github.com/brave/browser-laptop/issues/5347

Multiple sites on the same origin will each take up a tile.  Is this behavior that we want?

**Comment by bradleyrichter** [comment]
We need to dedupe. The example above would simply make GitHub the top site and you would have a link to github.com on a single tile.

**Comment by bsclifton** [comment]
Requirements (please edit this post as needed):
- Only show one link per domain
- Tile can remain as the favicon with the theme color (although, folks can turn off theme color in Preferences > Tabs)
- Mousing over needs to show the title (which it does currently)

**Comment by bsclifton** [comment]
Also- if we wanted nicer high-res non-favicons, we could consider spriting up like a top 20 sheet

**Comment by bsclifton** [comment]
Moving to 0.12.10.  For 0.12.9, the ideal behavior would be to limit folks to only 1 row of icons (until we're able to resolve this issue and the other issues)

cc: @cezaraugusto

**Comment by Liunkae** [comment]
Related issue: #5482 (only one row of topSites)

**Comment by bbondy** [comment]
Moving to 0.12.10 but would consider moving back if a PR is in place.

**Comment by bbondy** [comment]
Please update to use the same algorithm with frecency as is done for urlbar suggestions.

**Comment by bsclifton** [comment]
Note per our convo: we can use the frecency algorithm from suggestions.js, but we'd need to move the code to the renderer process

**Comment by bradleyrichter** [comment]
@bsclifton Do we need a separate issue for deduping as a first pass or combine it with frecency?

**Comment by bsclifton** [comment]
@bradleyrichter deduping should be done now (the first pass that is).  If you choose to pin a site, then it won't count as a dupe (ex: you'll be shown 1 other result from that domain).

You will notice that the duping is based on hostname (which does not remove the subdomain name), which means https://blog.brave.com/ and https://brave.com/ count as two sites..  We could change this logic and instead strip off subdomain?

**Comment by bradleyrichter** [comment]
google has so many sites/tools with subs so let's go with that. (each sub counts as a sep site)

**Comment by bsclifton** [comment]
With deadline for milestone being tonite, moving to 0.12.11

**Comment by bbondy** [comment]
This would be great to get to use Aubrey's frecency, but since we only show 6 tiles currently and they are pretty accurate most of the time as is we can move to backlog for now.

The fix here is to use this sorting:
https://github.com/brave/browser-laptop/blob/master/app/renderer/lib/suggestion.js

But I think suggestion.js has to move to common.

**Comment by bsclifton** [comment]
This should be completely fixed with [brave-core](https://github.com/brave/brave-browser)
