### ISSUE TITLE
Request Kiosk mode

### ISSUE THREAD

**Issue by foafron** [brave/browser-laptop#534]
A browser like this with privacy in mind would be really great to use as a kiosk. A built-in kiosk mode would be nice that had the following features:
1. keep the address bar hidden
2. allows the admin to whitelist/blacklist sites
3. have a "Reset" button along with a timed reset that clears history and returns to default homepage
4. allows the admin to decide which plugins are allowed.

Thanks.

**Comment by bradleyrichter** [comment]
@ron-houk nice suggestion. Do you have any feeling of usage percentage? This may need to go further down the list but it sounds ideal for a customer subset.

**Comment by ron-houk** [comment]
I couldn't give you an exact percentage, but reliable, robust, open source browsers w/ kiosk mode built in aren't easy to find (especially one's that have a timed reset).  I work at a library and would have tons of use cases for something like that.

**Comment by PFCKrutonium** [comment]
I could see this being useful in retail locations as well. Up to this point the best implementation I have seen was Some custom browser running on Android connected to a 40" Touchscreen at a Canadian Tire. It was easy to break by mistake.

**Comment by luixxiul** [comment]
It is fairly easy to hide everything except the tab's content:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26521230/68b3b534-431e-11e7-9772-44c04e7036ea.jpg)

Other TODOs
- Disable shortcut keys to control outside of the tab (such as shift+f8 and ctrl+t)
- Force fullscreen
- Force private tab mode

**Comment by bsclifton** [comment]
Closing as `wontfix` since we won't be able to address before moving to [Brave Core](https://github.com/brave/brave-browser). I opened an issue capturing this functionality there:
https://github.com/brave/brave-browser/issues/665
