### ISSUE TITLE
Cannot create Brave wallet on master

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5346]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Cannot create Brave wallet on master

**Expected behavior:**
Should create Brave wallet on master

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
[master](https://github.com/brave/browser-laptop)

- Steps to reproduce:
    1. Build from [master](https://github.com/brave/browser-laptop)
    2. Enable payments from preferences
    3. Console shows Error response 433 for POST

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19919723/7bc89d14-a0cc-11e6-9e9b-3685e6422a25.png)

- Any related issues:

 cc: @mrose17

**Comment by NQAT** [comment]
I too had this same problem when I first installed brave.  I forgot about it and tried it again after a few days and it worked.

**Comment by mrose17** [comment]
@srirambv - what is the status on this? thanks!

**Comment by srirambv** [comment]
@mrose17 Just checked works now no errors on console.
