### ISSUE TITLE
Opening a video on YouTube creates new tiles

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5347]
Opening a video on YouTube creates new tiles and changes to FavIcon. 

![tilechange](https://cloud.githubusercontent.com/assets/17010094/19921519/216b797c-a0d6-11e6-9d52-c0300cd3243a.gif)

cc: @bsclifton @cezaraugusto

**Comment by cezaraugusto** [comment]
I don't know if this is a bug really, as each new accessed URL should have its own tile, no matter if they share the same origin. 

/cc @bbondy @bsclifton for better thoughts.

About favicon thing, that's a known issue #5310, where we collect this data later than expected.

**Comment by srirambv** [comment]
@cezaraugusto in that case browsing 9 different URL of the same origin fills up all the tiles. I feel each tile should be blocked for an origin and not the visited URL's. If you Google search for 10 different items then it will fill all the 9 tiles, which doesn't make sense, putting Google on one tile makes sense because the site is visited frequently(10 times). This would precisely make it as a top site and adding it as a tile makes sense.

**Comment by bsclifton** [comment]
I'm going to mark this as a dupe for now-  I think it's a great concern though.  Let's chat in https://github.com/brave/browser-laptop/issues/5338
