### ISSUE TITLE
Closing a tab and restoring it does not restore back BF history

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#5348]
**Did you search for similar issues before submitting this one?**
No.

**Describe the issue you encountered:**
When you close a tab and restore it with CTRL + SHIFT + T it does not have back/forward history.

**Expected behavior:**
Upon restoring a tab, BF hisotry should be present just like in Chrome and FF.

- Platform (Win7, 8, 10? macOS? Linux distro?): Fedora 24

- Brave Version: 0.12.8

- Steps to reproduce:
    1. Open a new tab and visit several websites
    2. Close the tab
    3. CTRL+SHIFT+T and see you can't go back.

**Comment by bsclifton** [comment]
This is definitely a known issue and would require an electron change to fix.  More info captured in https://github.com/brave/browser-laptop/issues/2702

Closing as duplicate
