### ISSUE TITLE
Installation error on windows 10

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5355]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
This came in from support. It sounds like they download Brave and install it but when it opens they only see a menu bar and "about:error"

I seem to remember someone from Coindesk reporting the same issue but we weren't able to reproduce.

**Expected behavior:**
Downloading and installing should not error.

- Platform (Win7, 8, 10? macOS? Linux distro?):
windows 10, 64 bit.

- Brave Version:
Latest (I just had them try again and they confirmed it's still a problem)

- Steps to reproduce:
    1. Download Brave from brave.com
    2. Install
    3. Open the browser

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Closing this issue as it's a bit stale and there is not enough information to act on
