### ISSUE TITLE
Scroll wheel issues

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5356]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Two different support tickets, both using Windows 10 are reporting that the scroll functionality stops working or becomes visibly janky while using Brave. Both tickets seem to think it's not site specific. Maybe it's too many tabs?

**Expected behavior:**
Scroll wheel scrolling should be smooth.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.12.6

- Any related issues:
#5325 #5257

**Comment by pixelass** [comment]
I just commented on #5325 

I am pretty sure it is related to tabs, since one slow tab will affect all others. The speed/performance does not go back to normal when that tab is closed.

Hope this helps.

**Comment by Samizdata** [comment]
I was having the problem previously (as in earlier tonight in 14.1 on Win10 x64), but I disabled both hardware acceleration and smooth scrolling and I have not seen the issue reoccur.
