### ISSUE TITLE
Tab progress indicator (spinner/throbber) should be same size / padding as favicon to prevent title shifting

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#536]
Right now, the tab spinner, progress indicator is smaller than a typical favicon (or has less padding) so when the page finishes loading, the tab title shifts a pixel or two. It's kind of distracting. To see what I mean, load a site, and reload it. Watch the title shift left and then back right again.

**Comment by bradleyrichter** [comment]
@asadotzler Great design detail to clean up. thanks!

**Comment by bbondy** [comment]
Fixed by #560
