### ISSUE TITLE
Findbar can get in state of not accepting new chars

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5363]
I'm not fully sure why it happens but I have a fix. It's something about typing fast when another tab is loading.  Also I removed the mixed input controlled type because React gives a warning about it (We still do it on the URL bar though).  I do have a test that fails consistently that works now.

**Comment by luixxiul** [comment]
I noticed it too.

**Comment by Sh1d0w** [comment]
Happened several times to me on latest master as well. Did not open a ticket because I am not sure how exactly to reproduce this.

**Comment by bbondy** [comment]
Test plan: I could reproduce this by opening the new tab page, then open 2 tabs with command+click, then find in page on the first. 
I did find a way to write an automated test that reproduces this with the old code, and it is fixed in the new code.
