### ISSUE TITLE
Regression : Brave wallet cannot be created

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5365]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On a clean install of 0.12.8 Preview 3, I was unable to create a wallet. I waited 45 minutes before quitting.  0.12.7 worked in under 30 seconds so I do not believe it to be a backend issue.

**Expected behavior:**
A user should be able to create a wallet quickly.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.8 Preview 3

- Steps to reproduce:
    1. On a clean install of 0.12.8, try to create a wallet.

- Screenshot if needed:
![wallet_slow](https://cloud.githubusercontent.com/assets/1434040/19954045/620b1408-a142-11e6-99c5-a057fbbd2f77.gif)

- Any related issues:

**Comment by srirambv** [comment]
Similar to #5346 . @alexwykoff do you see a similar console error with 422 response error?

**Comment by alexwykoff** [comment]
No, mine were all 200.

**Comment by bbondy** [comment]
It took a few seconds but it created fine for me.

**Comment by bbondy** [comment]
can you still reproduce?

**Comment by bbondy** [comment]
I think this is working now? Please confirm with build I Put in slack and verify on next test build after preview3.

**Comment by bbondy** [comment]
leaving milestone marker so it gets tested

**Comment by srirambv** [comment]
Wallet is created on both preview 3 build and RC1 build for me. No problems on Windows
