### ISSUE TITLE
Honey: Support chrome.browserAction.setBadgeText

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5366]
## Test Plan:
1. Enable the LastPass extension
2. From chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html?dialog=createAccountSimple, open Developer Tools (Ctrl+Shift+I)
3. From console, run `chrome.browserAction.setBadgeText({text:"27"})`

## Original issue description
Honey (and other extensions) may often communicate valuable information by way of small text labels on or around their badge. Honey uses this API to display the total number of deals available for the domain.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/815158/19954231/dc46778a-a133-11e6-9f61-0a09c27f0054.png)

**Documentation:** https://developer.chrome.com/extensions/browserAction#method-setBadgeText

**Related Issues:** #5362

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by jonathansampson** [comment]
Blocked #8671

**Comment by jonathansampson** [comment]
Blocks #9654
