### ISSUE TITLE
Honey: Support browserAction.setBadgeBackgroundColor

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5367]
## Test Plan:
1. Enable the LastPass extension
2. From chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/tabDialog.html?dialog=createAccountSimple, open Developer Tools (Ctrl+Shift+I)
3. From console, run `chrome.browserAction.setBadgeBackgroundColor({color:'#FF0000'})`

## Original issue description
Honey (and other extensions) may often communicate valuable information by way of badge icon background colors. Honey uses this API to indicate the presence of deals available for the domain.

**Screenshot:** (Left: Chrome, Right: Brave)
![image](https://cloud.githubusercontent.com/assets/815158/19954231/dc46778a-a133-11e6-9f61-0a09c27f0054.png)

**Documentation:** https://developer.chrome.com/extensions/browserAction#method-setBadgeBackgroundColor

**Related Issues:** #5366, #5362

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by alexwykoff** [comment]
Could not reproduce on OS X.

**Comment by jonathansampson** [comment]
Blocked #8671
