### ISSUE TITLE
Not getting Search bar in ver 0.12.7 

### ISSUE THREAD

**Issue by bhabanisb** [brave/browser-laptop#5368]
Using 0.12.7 . Not getting search bar. Clueless. Help plz.

**Comment by Liunkae** [comment]
Are you trying to use web search (Google, etc.) or find (on page)? What platform are you on (Windows, macOS, or Linux distro)? How long have you had Brave installed?

**Comment by bhabanisb** [comment]
Able to Google search on its page. Windows 7 ultimate, 32 bit. Using Brave since more than a month.

**Comment by Liunkae** [comment]
Can you please make sure your Search settings look like this? (Preferences > Search)

![image](https://cloud.githubusercontent.com/assets/19424103/20023706/df46be5e-a2af-11e6-93c7-be7e6013998c.png)

Also, it would be helpful if you could post a screenshot of the problem.

Thanks.

**Comment by bhabanisb** [comment]
Hello
Find the screen shot. Thanks 
Bhabani 

    On Saturday, November 5, 2016 3:31 AM, Liunkae <notifications@github.com> wrote:
 

 Can you please make sure your Search settings look like this? (Preferences > Search)Also, it would be helpful if you could post a screenshot of the problem.Thanks.—

**Comment by Liunkae** [comment]
@bhabanisb Sorry, I don't think the screenshot worked. Could you please try uploading it on GitHub directly? Thanks.

**Comment by bhabanisb** [comment]
@Liunkae  SS `Attached.  Thanks

![error1](https://cloud.githubusercontent.com/assets/1633003/20035694/8cac1a8e-a414-11e6-8724-80702b93b96d.png)
`

**Comment by Liunkae** [comment]
@bhabanisb Thanks for your patience! All your settings seem fine. So, if you type a search term in the url bar and press Enter, what happens?

**Comment by bhabanisb** [comment]
I am getting the search result to the query,on typing in URL bar.In fact i was assuming another search query bar,as in case of firefox,hence i never tried this one.Thanks for the help.
Thanks 
Bhabani 

    On Monday, November 7, 2016 6:18 AM, Liunkae <notifications@github.com> wrote:
 

 @bhabanisb Thanks for your patience! All your settings seem fine. So, if you type a search term in the url bar and press Enter, what happens?—

**Comment by Liunkae** [comment]
Glad to here that! FYI, there has been some discussion about having a separate search bar like Firefox (#466).

**Comment by bhabanisb** [comment]
It will be better if separate search bar is introduced along with search engine setting panel,like Firefox.Please consider this as relevant issue.

**Comment by bhabanisb** [comment]
It will be better if separate search bar is introduced along with search engine setting panel,like Firefox.Please consider this as relevant issue. 

    On Monday, November 7, 2016 12:16 PM, Liunkae <notifications@github.com> wrote:
 

 Glad to here that! FYI, there has been some discussion about having a separate search bar like Firefox (#466).—
