### ISSUE TITLE
Monthly ledger payment failed

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#5371]
My payment failed yesterday. The below is the entire contents of my *Brave_Payments_11-3-2016.csv* file:

    Publisher,Votes,Fraction,BTC,USD

(`data:text/csv;base64,UHVibGlzaGVyLFZvdGVzLEZyYWN0aW9uLEJUQyxVU0Q=`)

My ledger wasn’t wiped clean as it was last month, but still has all of the entries, visits, and time spent from October. Status now shows “Contribution due date: ⁨in a month⁩.”

Last month my Brave client was running when the payment was performed. This month, I opened up Brave some hour after the payment was expected to go through.

Version v0.12.7-dev on Fedora Linux. Possibly related to #4703. My Brave Wallet balance was about 31 USD before the due payment and is now about 29 USD. Some funds lost to transaction fees?

**Comment by mrose17** [comment]
sorry for the delay in replying. i see what's going on (finally!).

@willy-b -- what's going on here is that we're saying a report is ready *before* the voting has occurred. the entry in the transaction doesn't have any of these fields: `credential`, `surveyorIds`, `count`, `satoshis`, `votes`, or `ballots`

i suggest that if `ballets` is not present, or `ballets.length !== count`, then we don't say that a report is ready for that contribution period. your thoughts?

**Comment by da2x** [comment]
This just happen again.

Account balance hasn’t been deducted, I have an empty report/receipt for the month, ledger hasn’t been reset, and I got a toolbar notification saying my contributions have been processed. There haven’t been a release since this was fixed, but I wanted to update the record of this bug all the same.

Brave 0.12.15 on Fedora Linux.

**Comment by luixxiul** [comment]
Reopening this based on the comment above. Please close this with a new commit/PR, thanks.

**Comment by bbondy** [comment]
@luixxiul looks like this was already fixed as per the message from da2x above, just not released. He was just updating, so I'll close this again. 

The release will be out soon by the way.
