### ISSUE TITLE
[Extension Request]Provide support for RefControl 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5372]
From [support ](https://linkbubble.zendesk.com/agent/tickets/6372)
>Reference control enables you to control what website — say, the NY Times — thinks you’re coming from a particular HTTP server. What a reference control does is change what site you think you’re coming from. So rather than thinking you are coming another NY Times site, it thinks you’re coming from google. There are numerous add-ins for Firefox that do this. The one I use is called RefControl and it functions without fail. It is very useful.

**Comment by luixxiul** [comment]
Closing in favor of https://community.brave.com/t/extension-requests-refcontrol/10712

Let's reopen if the extension becomes under consideration.
