### ISSUE TITLE
Save to pocket from context menu doesn't highlight the Pocket widget

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5373]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Save to pocket from context menu doesn't highlight the Pocket widget

**Expected behavior:**
Should have the same behavior as saving from the widget.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8 Preview 3

- Steps to reproduce:
    1. Open any page
    2. Right click>Context Menu> Save to pocket, doesn't highlight the Pocket widget
    3. Click on the widget on the same page to save, the widget highlights after saving

- Screenshot if needed:
![pocketcontextsave](https://cloud.githubusercontent.com/assets/17010094/19969549/f2181b7a-a1d0-11e6-8c5a-6eb508b23d76.gif)

- Any related issues:

   cc: @jonathansampson @darkdh

**Comment by darkdh** [comment]
This is expected because pocket didn't make it illuminated. Please comparing the behavior with chrome.
