### ISSUE TITLE
Disabling adblock in private tab still shows the adblock count

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5376]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Disabling adblock in private tab still shows the adblock count

**Expected behavior:**
Should not show the adblock count when adblock is disabled in a private tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8 preview 3

- Steps to reproduce:
    1. Open any link in a private tab
    2. Check the adblock count 
    3. Disable adblock from shields, still shows the adblock count

- Screenshot if needed:
![privatewindow](https://cloud.githubusercontent.com/assets/17010094/19979949/29bd3c9a-a1f4-11e6-92b0-97085541abb3.gif)

- Any related issues:

**Comment by bbondy** [comment]
Moving to 0.12.9 but cc @darkdh seems like a bug with per site private tabs data

**Comment by bbondy** [comment]
I suspect it's not a regression btw, did you confirm it worked in 0.12.7 @srirambv ?

**Comment by srirambv** [comment]
No missed it my bad. Removing regression

**Comment by bbondy** [comment]
Moving to 0.12.10.
