### ISSUE TITLE
Menu sub items should be capitalized for uniformity

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5377]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Menu sub items are not capitalized 

**Expected behavior:**
Menu items should be capitalized to maintain uniformity

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8 Preview 3

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/19983290/5802c716-a201-11e6-9a5f-227f81652ba4.png)

- Any related issues:

**Comment by Liunkae** [comment]
I agree with the first four. Proposal for new titles:
"Bravery Global Settings…"
"Bravery Site Settings…"
"Spread the Word About Brave…"
"Paste Without Formatting"

I disagree with the last one. Since "on" is a short preposition, it shouldn't be capitalized.
