### ISSUE TITLE
[HackerOne] media permission requests in iframes show top-level origin

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#5378]
https://hackerone.com/reports/179749

Test Plan:
1. go to https://jsfiddle.net/v1dugp3y/
2. you should see a camera/microphone permission request from davidwalsh.name instead of jsfiddle.

cc @bridiver

**Comment by bbondy** [comment]
@diracdeltas is this a regression? If not I think can we move on 0.12.10 because we didn't fix in time.  Please let me know.

**Comment by diracdeltas** [comment]
i'll move it, thanks

**Comment by diracdeltas** [comment]
This is fixed by https://github.com/brave/electron/pull/93
