### ISSUE TITLE
Browser opens to empty page on first launch

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5379]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
If you launch Brave from source, the first time you run it there seems to be issues.
- about:newtab doesn't show the new tab content until after you've visited some sites
- the menus are missing options I believe 

It might be caused by the sites list (in AppStore) being empty

Hopefully, this is not the case with a built version of the product (we need to verify)

**Expected behavior:**
Everything should work on first launch. I shouldn't need to visit sites.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
HEAD from master

- Steps to reproduce:
    1. git clone the repo
    2. if you have any `brave-development` files in place, move them out of the way
    3. `npm run watch` in one window
    4. `npm start` in another window
    5. Notice browser has issues

- Screenshot if needed:

- Any related issues:

**Comment by privatzee** [comment]
If it happens sporadically, it's possibly an Electron problem. Let's say I work on an Electron app today and everything is okay. Tomorrow morning when I start it up again it _might_ be that some parts are missing. By restarting immediately without any changes made, everything is always there correctly. It shouldn't happen, but once in a great while it does happen. I've seen it and it's surprising.

But then if this issue happens every time, that's not the same.

**Comment by bsclifton** [comment]
It seems to happen every time when there is no session data.  I think there are expected values which are missing and only get loaded properly after you visit 1 site or after the session is saved (which happens when you exit).

**Comment by bsclifton** [comment]
The about:newtabs root cause has been discovered; working on a fix...
