### ISSUE TITLE
Create exception for USA clock display to have small "AM/PM" indicator text

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5381]
current:
![image](https://cloud.githubusercontent.com/assets/13509546/19991652/7ac72894-a1f4-11e6-94f4-c49f8239e4e0.png)

desired:
![image](https://cloud.githubusercontent.com/assets/13509546/19991673/a9260cf0-a1f4-11e6-884b-675357057c10.png)

**Comment by srirambv** [comment]
Can an analog clock be used giving user option to change between analog and digital?

**Comment by bsclifton** [comment]
@srirambv that's a really slick idea; that would be a really nice option, IMO.  I went ahead and broke that out into a new issue: https://github.com/brave/browser-laptop/issues/5409

@bradleyrichter if it sounds interesting to you, feel free to drop a mock up in there :smile:

**Comment by bradleyrichter** [comment]
would this slow down the browser?

http://www.javascriptkit.com/script/script2/css3analogclock.shtml
