### ISSUE TITLE
clicking entries on about:history is laggy

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5382]
**Describe the issue you encountered:** clicking entries on about:history is laggy. You have to wait ~0.5s until the entry you click is actually selected.

**Expected behavior:** it should be selected instantly

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open about:history
    2. Click an entry
    3. Wait ~0.5s until the entry is selected

- Any related issues:

**Comment by luixxiul** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
yikes- this one is pretty bad. I'm not exactly sure what we can do yet, but I'll bump back to 0.12.10 for now

**Comment by luixxiul** [comment]
@bsclifton I cannot feel the difference and it is still laggy for me. Would you please check it out?

**Comment by bsclifton** [comment]
Keeping assigned to me for now but removing milestone...

**Comment by luixxiul** [comment]
Adding the same milestone as #9979, which would possibly fix this issue.
