### ISSUE TITLE
Ledger Hardware Wallet integration

### ISSUE THREAD

**Issue by maciozo** [brave/browser-laptop#5387]
Would be nice to be able to manage a Ledger Nano S (or any other Ledger HW wallet) from Brave. 

https://www.ledgerwallet.com/
https://chrome.google.com/webstore/detail/ledger-wallet-bitcoin/kkdpmhnladdopljabkgpacgpliggeeaf
https://chrome.google.com/webstore/detail/ledger-wallet-ethereum/hmlhkialjkaldndjnlcdfdphcgeadkkm

**Comment by SilverPin** [comment]
I second this.

**Comment by tyler-morrison** [comment]
Agreed!

**Comment by luixxiul** [comment]
@mrose17 do you think it is possible to integrate it and if so when it will be? Maybe after 1.2 or so?

**Comment by mrose17** [comment]
@luixxiul - the short answer is that it depends on what "integrate" means. the ideal integration is a plugin that allows the browser to determine whether a ledger hw wallet is attached to the laptop, and if so, requests permission to fund your brave wallet when you click on 'Add Funds'. @jonathansampson is the expert on plugin integration...

**Comment by jonathansampson** [comment]
@maciozo @SilverPin @tyler-morrison, We recently published a short walk-through on how you can quickly test Chrome extensions. You can find the resource on our blog: [Loading Chrome Extensions in Brave](https://blog.brave.com/loading-chrome-extensions-in-brave/).

If one of you would be interested in following those steps, and testing these extensions, I'd gladly be available for discussion and troubleshooting. If we find little (or not) obstacles in the process, we could potentially expedite support in Brave.

**Comment by zentagonist** [comment]
Closing as out of scope
