### ISSUE TITLE
Create about:sessions for session-management

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5388]
It'd be nice to be able to see a list of partitions that are created here and the ability to delete them.  It also gives a place to add other more advanced session management features in the future.

**Comment by bsclifton** [comment]
+1 from @JIVS via [Suggestion: add a session manager](#10453)

**Comment by jkarlsso** [comment]
Yes please. This and cross-platform bookmarks/passwords/history/etc. sync is what is stopping me from switching over to Brave fully.

**Comment by bsclifton** [comment]
This should be addressable with extensions in [brave-core](https://github.com/brave/brave-browser)
