### ISSUE TITLE
Mac context menu has first item selected when it should not be

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#539]
When you context click on Mac build 0.7.12, the first item in the context menu is already selected. It shouldn't be. This doesn't show up on the Windows build 0.7.10.

**Comment by luixxiul** [comment]
Reproducible on Mac, @bbondy?

**Comment by bbondy** [comment]
Reproducible on OS X.  Maybe the fix is to change electron code to open context menus by default 1 px right more.

**Comment by bbondy** [comment]
should be fixed upstream here:
https://github.com/electron/electron/pull/6110

No need to track here.
