### ISSUE TITLE
Support Payment Widget for websites

### ISSUE THREAD

**Issue by martinheidegger** [brave/browser-laptop#5390]
**Did you search for similar issues before submitting this one?**
Yes, I found that https://github.com/brave/browser-laptop/issues/4634 talks about a similar feature. Though this a bit different...

**Describe the issue you encountered:**

As a user I have following problem: Some websites that I visit long or often are because of the medium/good information that they provide on a regular basis. Other websites I like to visit are of such high quality that even if I visit them just once a month/year they bring me great joy. Those websites would completely fall through the cracks of the current system _(if I understand the system right)_.

That is why I would love to be able to dedicatedly support websites. Not by an percentage amount but by a concrete amount: i.e. 1$/month. This, instead of the "by-view" model, would allow me to be an active donor! Which is important because its the sites with the little, but good, content that need my money often most. **I would feel in control of my donation.**

As a web developer I am intrigued by Brave in a sense that I would like to go even further: If I could - on my website - put a button that tells the user:

```html
<a href="brave://donate?suggest=1usd&suggest_period=month">Hey, don't you want to help out: Use Brave to support us!</a>
```

... that on-click shows a chrome-dialog where the user can set how he wants to donate with the preference of the website. This would point the user to Brave (and the payment concept), while at the other side it promotes the website and the use of an alternative way to browse the web.

**Comment by da2x** [comment]
Or maybe let Brave register itself as a protocol handler for the existing `bitcoin:<wallet-address>&label=Donation` URI schema.

**Comment by zentagonist** [comment]
Not going to implement this one, sorry.

**Comment by martinheidegger** [comment]
Would you mind telling why? I still would love to see this!
