### ISSUE TITLE
Default search engine 'Google' is not marked as such in the search engine preference table

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5399]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On a clean install, Google is the default search, however that is not reflected in the preference table.

**Expected behavior:**
We should display the default search to users.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.8 RC1

- Steps to reproduce:
    1. On a clean install, open about:preferences#search, observe the table.

- Screenshot if needed:
<img width="964" alt="screen shot 2016-11-04 at 11 59 35 am" src="https://cloud.githubusercontent.com/assets/1434040/20015031/8d34e762-a287-11e6-8613-ed55393645f3.png">

- Any related issues:

**Comment by Sh1d0w** [comment]
I faced the same problem when installing a build form the latest master. It seems the search engine is "marked" but the icon is not loading intitally. It takes several close/open's of the settings page in order the mark icon to load.

**Comment by bbondy** [comment]
Any help you can give me to reproduce this? I tried clearing my session-store and clearing my whole profile dir about 20 times in a row, tried loading about:preferences#search directly or going to about:preferences and then navigating to search. Tried using the menu too.
If intermittent that's ok, just wondering if there are steps or not though.

**Comment by gyandeeps** [comment]
i ws not seeing the icon before but now i can see it with 0.12.13

**Comment by srirambv** [comment]
Working as expected. Have checked in from 0.13.0 on wards. Able to see the check mark on default search engine. Closing for now. Will reopen if the issue resurfaces again.
