### ISSUE TITLE
Remove max-width for #navigator or the option to draw it more larger/smaller

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#540]
Right now there is really tons of wasted/empty space in the navigation toolbar, perhaps it could be a good idea if the address field is auto scaling to better fill the not used space, also in the case if you would add additional (removable) button elements to the navigation toolbar at some point and the user decides to not show them/remove them.

Or if that is not possible, perhaps a way that the user is able to change the length of the address field in a manual way.

**Comment by bradleyrichter** [comment]
@SJ-Diamond Several requests came in to spend more address bar area on the URL box so we made it wider. I'm trying to hang on to some "white space" to keep the open style...

See if you like it better in the next update.

**Comment by SJ-Diamond** [comment]
Thanks :D

**Comment by luixxiul** [comment]
How about removing [/less/navigationBar.less#L59](https://github.com/brave/browser-laptop/blob/master/less/navigationBar.less#L59)? I think this is better.

**Comment by luixxiul** [comment]
FYI ``max-width: 900px`` was introduced with #1193. I've never been a fan of it, if I'm honest.

**Comment by bradleyrichter** [comment]
We were hearing more complaints around not having enough grab area. I think we are at a happy place now. LMK if you all feel differently after some usage time.

(I may add 2px to the top edge soon as well)

**Comment by bsclifton** [comment]
Closing this issue as stale (and also because the grab area is important)

Let's reopen if opinions change 😄
