### ISSUE TITLE
Attaching photo to Facebook reply is broken

### ISSUE THREAD

**Issue by EnotMC2** [brave/browser-laptop#5401]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Selected photo doesn't get attached

**Expected behavior:**
The selected photo should be attached

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version:
0.12.7

- Steps to reproduce:
    1. Navigate to a Facebook "Write a Reply" dialogue box
    2. Press the camera icon where rollover shows "Attach a photo or Video"
    3. Use the dialogue to select a .jpg file
    4. Complete the Dialogue
    5. Although the attachment dialogue completed, nothing gets attached
    6. The .jpg selected should have been attached but Brave is broken and nothing gets attached

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/6810)

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/5396)

**Comment by bsclifton** [comment]
Closing as a dupe of https://github.com/brave/browser-laptop/issues/698
