### ISSUE TITLE
Views and % entries alignment are different in payments window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5402]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Views and % entries alignment are different in payments window

**Expected behavior:**
Should be either left aligned or right aligned to maintain uniformity

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.8 RC1 

- Steps to reproduce:
    1. Enable payments in pref window
    2. Visit sites so that entries are shown in payments
    3. Views and % entries alignment are different

- Screenshot if needed:
![number](https://cloud.githubusercontent.com/assets/17010094/20014871/d286dde2-a2b0-11e6-854a-55e43fe50ff4.PNG)

- Any related issues:

 cc: @jkup

**Comment by jkup** [comment]
I seem to remember this being done by design. @bradleyrichter is this the way they are supposed to look? If not can you let me know which columns should be left/right/center aligned and I'll fix?

Thanks!

**Comment by bradleyrichter** [comment]
Yes. Please change % to right-aligned.

**Comment by bradleyrichter** [comment]
(nothing get's by eagle-eyes @srirambv  !)
