### ISSUE TITLE
After importing A LOT of bookmarks, the bookmarks manager becomes unresponsive while fetching favicons.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5404]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I have a LOT of bookmarks in Chrome. When I import them to Brave then visit the Bookmarks Manager (about:bookmarks) I find that if I open a larger folder, the entire page becomes unresponsive as it fetches favicons for the links.

**Expected behavior:**
I should be able to interact with the page regardless of background actions.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.8 RC1

- Steps to reproduce:
    1. Import a huge amount of bookmarks, especially one with a huge folder of bookmarks.
    2. Visit bookmarks manager (about:bookmarks).
    3. Open the large folder of bookmarks.
    4. Attempt to interact with the page.

- Screenshot if needed:

- Any related issues: #2697

**Comment by luixxiul** [comment]
it seems the browser DDOSed itself :-o

**Comment by bsclifton** [comment]
Moving this back to 0.12.10; this is an edge case, but I can see a lot of folks hitting this. The good news is, it should be caching the icons after fetching. It should be rate limiting the # requests made. 

@bridiver does it make any sense why chromium would be hanging when requesting a large # of favicons? It should be capped at ~6 resources concurrently, right? (and with that, max 2 per domain, IIRC)

**Comment by bbondy** [comment]
I suspect the diagnosis is wrong but the bug is obviously valid, I.e. something needs to be optimized but not the favicon fetching probably.

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3
