### ISSUE TITLE
Importing bookmarks shows pinned tabs in history 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5405]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Importing bookmarks shows pinned tabs in history 

**Expected behavior:**
Should not show pinned tabs in history unless its loaded 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows

- Brave Version:
0.12.8 RC1 (yet to verify on older builds)

- Steps to reproduce:
    1. Visit a site and pin the tab
    2. Clear history and check there is no entry in about:history
    3. Import bookmark from browser/html file
    4. about:history shows entry for the pinned tab even though you have not visited/reloaded the pinned tab

- Screenshot if needed:
![pinnedhistory](https://cloud.githubusercontent.com/assets/17010094/20017714/a4172596-a2bc-11e6-978f-30e986aa90a9.gif)

- Any related issues:

  cc: @bsclifton @darkdh

**Comment by bsclifton** [comment]
Removed milestone for now; let's discuss if you feel strongly :smile:

**Comment by bsclifton** [comment]
I'm curious why it would show- is the timestamp still set during import @darkdh? (this might be fixed now, after it was switched over to creationTime)

**Comment by darkdh** [comment]
@bsclifton  no, timestamp of imported bookmarks will be 0 now since 362a8bba2530291d0dcd820e0ad005a58fe73285

**Comment by bsclifton** [comment]
@srirambv this should be fixed, since the commit @darkdh links to (above). Can we add this to the manual test plan? I'll mark it as milestone 0.12.9 and close the issue.  Thanks :smile:
