### ISSUE TITLE
Silent updates

### ISSUE THREAD

**Issue by seriema** [brave/browser-laptop#541]
I could live without this info showing up as soon as I open Brave:

<img width="1440" alt="screenshot 2016-02-01 21 54 48" src="https://cloud.githubusercontent.com/assets/693684/12731110/71173efe-c92f-11e5-973d-06b639d25b52.png">

As a dev I can appreciate release notes, but there's probably another way. At least one where I don't have to give my permission to update first. Just update it silently and if it get's seriously outdated because it couldn't update behind the scenes then just turn the lion icon into a sad panda :panda_face:

**Comment by bbondy** [comment]
If it didn't update behind the scenes that would make me a sad panda :panda_face: :)

OK yes maybe some option to toggle this UI, or a button in details maybe.

**Comment by ElissaBeth** [comment]
@bbondy - agree that silent updating is good feature. assigning to myself to mock up a UI.

**Comment by luixxiul** [comment]
@ElissaBeth Is there any progress here? :)

**Comment by luixxiul** [comment]
Silent update was already implemented?

**Comment by bbondy** [comment]
This is just to make the UI that comes up optional

**Comment by luixxiul** [comment]
I see. Closing for now.
