### ISSUE TITLE
Bookmarking a site on new tab gridSites change its position

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5413]
## Test plan
See https://github.com/brave/browser-laptop/pull/12470

## Original issue description
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
When you bookmark a tile on newtab's grid, the site jumps its position to the first position.

**Expected behavior:**
Bookmarking a site should take no action on topSites grid

- Platform (Win7, 8, 10? macOS? Linux distro?): n/a

- Brave Version: n/a

- Steps to reproduce:
    1. Go to new tab page
    2. Visit some sites
    3. Take one site on i.e. position 3
    4. Notice it 'jumps' to first position

- Screenshot if needed: n/æ

- Any related issues: n/a

**Comment by bsclifton** [comment]
Possibly related to re-ordering done here (which may not be needed, just like the sanitize in newtabs.js removed it)
https://github.com/cezaraugusto/browser-laptop/blob/669ff355c34de09bdb4bcdafd88df1c15319e97c/app/common/state/aboutNewTabState.js#L13

**Comment by cezaraugusto** [comment]
Reopening as still an issue after #5583

**Comment by bsclifton** [comment]
@cezaraugusto is this still an issue? Also, I'm curious about https://github.com/brave/browser-laptop/issues/5337

 I wasn't sure after we talked today if there were outstanding issues? The behavior may have seemed different, but it's because of how it sorts. The pinning should be working as expected

**Comment by bbondy** [comment]
Moving to 0.12.10

**Comment by bsclifton** [comment]
Moving to 0.12.11

**Comment by bsclifton** [comment]
@cezaraugusto did you ever submit a fix for this? I remember we talked about how bookmarking updates the lastAccessedTime

**Comment by cezaraugusto** [comment]
@bsclifton nope but first item of my list now

**Comment by cezaraugusto** [comment]
Self notes:

[`oldSiteDetail` is being ignored while defining `lastAccessedTime`](https://github.com/brave/browser-laptop/blob/master/js/state/siteUtil.js#L96) and [adding visit count](https://github.com/brave/browser-laptop/blob/master/js/state/siteUtil.js#L138) is not setting counter to bookmarked sites. 

Current implementation still breaks actual tests.

This issue is cross-related to #6160
