### ISSUE TITLE
No product images on www.bjs.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5415]
**Describe the issue you encountered:**
No product images are shown.

**Expected behavior:**
Product images are visible in Brave.

**Steps to Reproduce:**
1. Navigate to http://www.bjs.com
2. Note that no product images are shown

**Brave Version:** 0.12.8

**Screenshot if needed:**
![image](https://cloud.githubusercontent.com/assets/815158/20025665/e77e7a96-a2ad-11e6-8719-eb1b5af6ce35.png)

**Comment by jonathansampson** [comment]
All of bjs' images appear to be loaded from another origin: richmedia.channeladvisor.com.

Turning on _Allow Ads & Tracking_ permits requests to this origin, and results in product images being shown. We should probably consider white-listing this domain for bjs.com.

**Comment by luixxiul** [comment]
Duping to #1368

**Comment by privatzee** [comment]
channeladvisor rings a bell: #4442

**Comment by MouseZero** [comment]
https://www.shortcutfoo.com/ also fails to load all of its images because it uses another origin (https://d1fg1q4hek7kx4.cloudfront.net). I couldn't find a place to white list the other origin is there such a place or is that only for Brave developers?

**Comment by luixxiul** [comment]
I'm going to close this thread as the site has been offline for a while.
