### ISSUE TITLE
table on about:history cannot have only 1 entry for a day

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5417]
**Describe the issue you encountered:** table on about:history cannot have only one entry for a day. If you have opened some pages before today, opened 2 pages today, and delete one entry, the other entry moves to the table for the day before.

**Expected behavior:** table on about:history should be able to have 1 entry for a day

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: I think I have seen this since months.

- Screenshot if needed:

In the example below the entry on 2016/11/5 1:38:46 PM moves to the table of 2016/11/3

![history](https://cloud.githubusercontent.com/assets/3362943/20027705/75bd92f0-a35e-11e6-892d-89cb2b8aa5e0.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Removed milestone-  Let's discuss if you feel strongly / want to readd

**Comment by NejcZdovc** [comment]
@luixxiul can you please check if this is still an issue?

**Comment by luixxiul** [comment]
ok i'll try later

**Comment by luixxiul** [comment]
that error can no longer be reproduced, while another issue happens:

![bug](https://user-images.githubusercontent.com/3362943/28492685-97c17afa-6f42-11e7-8aa4-78f76efcf491.gif)
