### ISSUE TITLE
Add funds bar comes up too often and should have turn off button

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5418]
When a user has 0 funds and Brave payments turned on, which will be a lot of people that just wanted to try the experience, shouldn't be prompted so often to add funds, and they should have an option to turn it off. 

I think I had about 20 prompts for it yesterday and have had 2 already today and have only been on my computer for an hour. 

I think just disabling brave payments would stop them, so maybe just adding a Turn Off button in the notification, and also make sure it doesn't come up more than once a day if they hit Later.

**Comment by bbondy** [comment]
@ayumi pls take before starting on sync if you don't mind 
@bradleyrichter  cc'ed in case he wants to tweak the experience I suggested above.

**Comment by bbondy** [comment]
I guess instead of turning off brave payments it should set the disable notifications in advanced maybe?

**Comment by bsclifton** [comment]
@bbondy the easier to turn off the better, IMO :smile:

**Comment by bradleyrichter** [comment]
@bbondy There is obviously a bug if you are getting a notification more often than every 6 hours. 

How about this:

1st alert after 24 hours past due.
Hitting "later" mutes for 3 days.
On the 3rd day, the later button changes to "Turn off notifications".

**Comment by bbondy** [comment]
Just another button for turn off notifications please.  And also don't show this if brave payments is disabled. I got the notification much more frequent than 6 hours.  It really makes us feel like a "please purchase to stop this nag screen" app which isn't what we are.  It's a big problem.
