### ISSUE TITLE
Make update details use markdown

### ISSUE THREAD

**Issue by seriema** [brave/browser-laptop#542]
Here's a specific one, but I think it'd be easier it any and all dialog boxes assumes it can have a link and just make it clickable which opens a new tab.

<img width="416" alt="screenshot 2016-02-01 21 55 03" src="https://cloud.githubusercontent.com/assets/693684/12731672/48218736-c932-11e5-9ed2-5ef4d71ab7e5.png">

>  That Github URL isn't clickable.

**Comment by bbondy** [comment]
Yep we're planning to support markdown for these which will make life a lot easier and auto fix this. I updated the title of this task. Thanks for posting.

**Comment by luixxiul** [comment]
Closing as Markdown is already supported (with links to issues and PR if any)

**Comment by bbondy** [comment]
Re-opening because this is for the Details button in the app update toolbar.

**Comment by sanecito** [comment]
+1 for this...no clickable link still in the details bit regarding updates.
