### ISSUE TITLE
Update noScript string for Preferences page only

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5420]
re: @bradleyrichter's request the preferences page "Block Scripts" string should be changed to "Block Scripts (will break many sites)" but the shields panel should remain "Block Scripts"

**Comment by jkup** [comment]
This is now going into a ticket with a lot of other string changes.

**Comment by bsclifton** [comment]
@jkup can you link to the ticket this was added to?

**Comment by jkup** [comment]
@bradleyrichter had asked me about fixing this yesterday and then suggested that I just show him how bc he has a ticket he's working on with multiple string changes.

@bradleyrichter can you put the ticket number in here?

**Comment by bradleyrichter** [comment]
Yep. #5421
