### ISSUE TITLE
Context menu with selected text should not include irrelevant extensions

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5423]
**Describe the issue you encountered:** The context menu with a selected text should not include irrelevant extensions like Pocket. It would lead to misunderstanding that the selected text were saved on the service.

**Expected behavior:** The irrelevant extensions should not appear on the context menu items with a selected text

1 Enable Pocket extension
2 Select a text 
3 Display the context menu on the text

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20034978/840b4ae8-a415-11e6-95c7-de91c16f4138.png)

- Any related issues:

**Comment by bbondy** [comment]
Resetting milestone I don't think it's critical, but feel free to disagree
