### ISSUE TITLE
Enabling Pocket without logging and pinning Extension tab closes the browser

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5424]
**Describe the issue you encountered:** Enabling Pocket without logging and pinning Extension tab closes the browser.

**Expected behavior:** The browser should not be closed

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1

- Steps to reproduce:
    1. Clear your brave folder
    2. Open the browser
    3. Open Settings
    4. Enable Pocket from Advanced and click "View installed extensions"
    6. Close the other tabs
    5. Close Pocket log in tab as soon as possible
    6. Pin about:extensions, the only tab which is opened
    7. The browser is closed

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I assume that "Close Pocket log in tab as soon as possible" is the key step here.

**Comment by bbondy** [comment]
Is this maybe the same as the intermittent pin crash that we've had for a while?

**Comment by darkdh** [comment]
@luixxiul, No matter how quick I close the pocket login tab, I still can't reproduce it
