### ISSUE TITLE
margin-right on the folder on Bookmark Manager should be removed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5426]
**Describe the issue you encountered:** On Bookmark Manager,

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20035226/004b5e28-a41f-11e6-9e1e-815c240b5c1d.jpg)

**Expected behavior:** The margin-right should not be there

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1

- Any related issues:

**Comment by bradleyrichter** [comment]
@bsclifton I think this makes sense to remove but you may have had a reason for it?

**Comment by bsclifton** [comment]
@luixxiul do you have more info?  I'm not able to repro on either 0.12.8 RC1 or on HEAD on master

There's padding, but no margin. Doesn't matter how big or small I make the window, I can't get a margin to appear
![screen shot 2016-11-06 at 9 32 40 pm](https://cloud.githubusercontent.com/assets/4733304/20046617/df3cb070-a468-11e6-8a64-48339ea88317.png)

**Comment by bsclifton** [comment]
Closing this and removing the milestone.  @luixxiul if you have more information, please reopen and I'll check it out.  Thanks! :smile:

**Comment by luixxiul** [comment]
This seems to have been fixed / just disappeared.
