### ISSUE TITLE
Attempting to load an URL resulted in too many redirects.

### ISSUE THREAD

**Issue by bkarlan** [brave/browser-laptop#5427]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Attempting to load an URL resulted in too many redirects.
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac Sierra
- Brave Version:
0.12.7
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/2250480/20035236/374a2de8-a3aa-11e6-9be2-7ccf8ea01df5.png)

- Any related issues:

**Comment by Liunkae** [comment]
@bkarlan Does the site work correctly in other browsers?

If so, please try allowing all cookies for the site. Click the lion icon in the top right. Under Cookie Control, select Allow all cookies.

If that doesn't work, try allowing all cookies for _all_ sites. Open Preferences (Brave menu > Preferences or ⌘, ) and select Shields on the left. Under Cookie Control, select Allow all cookies.

**Comment by luixxiul** [comment]
You can open https://www.ipage.com/knowledgebase/beta/article.bml?ArticleID=1752 now, maybe there was an issue on their side.
