### ISSUE TITLE
Margins should be set around extension buttons

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5428]
**Describe the issue you encountered:**

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20035332/dd716d80-a422-11e6-93cf-73c2c1feeaf6.png)

**Expected behavior:** Margins should be set around extension buttons

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1

- Steps to reproduce:
    1. Enable Pocket, LastPass, etc.
    2. Minimize the width of the window

- Any related issues: #5383

**Comment by bsclifton** [comment]
After digging in, this is the same as https://github.com/brave/browser-laptop/issues/5383 except with extensions enabled. Closing as dupe
