### ISSUE TITLE
Fetch favicons first

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5430]
**Describe the issue you encountered:** To confirm #2747 was fixed you have to wait until the page is loaded completely, maybe onload is fired.

**Expected behavior:** Because the interface is always active whether the page is loaded completely or not, the browser should find favicons and load them as soon as possible. We should not wait until the page is loaded completely.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1

- Steps to reproduce:
    1. Clear browser's cache
    2. Open https://tokyo.cawaii.media/gisele/ and go back asap, before the favicon is fetched lastly
    3. Long click the go forward button to display the pulldown

- Any related issues: #2747 #2879 #2697

**Comment by bsclifton** [comment]
Chromium is loading the favicons and electron is firing the event which notifies us that the favicon was loaded.  For example, see https://github.com/brave/browser-laptop/blob/cea502307d99b2507a1cf420f37504fe7fa10bf9/js/components/frame.js#L806

The favicon can't be loaded before the initial page is loaded (and honestly shouldn't be loaded until all other resources are loaded). Folks could probably add the meta tags in for the favicon and I would imagine this wouldn't be detected until page ready. Closing this as won't fix.
