### ISSUE TITLE
Disable close button on tabs if tab size is too small

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5431]
## Test plan

Under "QA steps" on https://github.com/brave/browser-laptop/pull/7799#issue-215652883

----

**Describe the issue you encountered:** if you click the close button of tab whose size is too small, sometimes you click the close button accidently.

**Expected behavior:** Disable close button on tabs if tab size is too small.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1 

- Steps to reproduce:
    1. Open many tabs
    2. Minimize the width of the window
    3. Select any tab carefully not to close it...

- Screenshot if needed:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20035535/79eefc38-a42b-11e6-8309-0c01cac1e600.png)

- Any related issues:

**Comment by bradleyrichter** [comment]
This sounds like a LHF fix.  (low hanging fruit)

@bbondy Can we get this in sooner than 1.0?

**Comment by bbondy** [comment]
@cezaraugusto mind grabbing this?

**Comment by bsclifton** [comment]
Change was backed out with https://github.com/brave/browser-laptop/pull/5886 after we noticed positioning of the audio icon being wrong:
![image](https://cloud.githubusercontent.com/assets/4733304/20685266/f75d4674-b570-11e6-8ae1-ae91ea601cf8.png)

The CSS as-is (in `tabs.less`) is great and works wonderfully... until the window gets small. I think the changes that were made need to be wrapped with a media query and should only be applied if within the breakpoint that was defined (520px). :smile: Milestone has already been bumped to 0.13.1

**Comment by luixxiul** [comment]
We have to be very careful yet as the close button does work on the edge of the tab:

![closebutton](https://cloud.githubusercontent.com/assets/3362943/22851850/f1a854f8-f071-11e6-8046-d8c84fcdedf1.gif)

I think that's why I thought the button should be **disabled** as the title says.

Let me reopen the issue for another fix.

**Comment by cezaraugusto** [comment]
@bradleyrichter, I agree with @luixxiul regarding that tab size. Do you agree if we remove close icon on that point as well?

**Comment by bradleyrichter** [comment]
The close button will need to be opaque to solve the overlap issue. Regarding tab size, chrome has this nearly solved but we can be better. I guess three real point should be at 32px plus margin between favicon and close button?

**Comment by cezaraugusto** [comment]
You mean?

1. Opaque close icon (opacity: 1);
2. Remove close icon on less than 32px tab size?

**Comment by bradleyrichter** [comment]
fix for this:

1. below 48px width, only the selected tab gets a hover-close button
2. allow tab-drag in area around close button

**Comment by luixxiul** [comment]
Reopening the feedback by @srirambv and me.

https://github.com/brave/browser-laptop/pull/7799#issuecomment-288224541

> Test 1 fails as the close button is overlapped on the right side of favicon. And the click area is more than the close button causing it to close the tab when clicked on the favicon
>
> ![newtabtext](https://cloud.githubusercontent.com/assets/17010094/24171526/d12ccc9e-0e7c-11e7-88a9-295b3587cef6.gif)

Another adjustment of min-threshold for closeTab would be needed.

**Comment by luixxiul** [comment]
@cezaraugusto I like your last solution quite well :100:  The next step is to fix #2702.
