### ISSUE TITLE
Opening unicode text files in Brave does not auto detect characterset

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5432]
**Describe the issue you encountered:** If you set language setting to Japanese on Brave for example, Brave wallet recovery key is not shown on Brave in a proper chars encode. The file itself is not broken.

**Expected behavior:** The message should be displayed in proper characters encode.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1

- Steps to reproduce:
    1. Change your lang setting to Japanese on Brave
    2. "Save recovery file" on the backup your wallet dialog
    3. Click Save to display the screenshot below

- Screenshot if needed:

The below on Notepad is correctly encoded, while the above on Brave is not.

Please make sure that the 2 keys are replaced with placeholders.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20035553/0a086fc4-a42d-11e6-8975-de9f153087b7.png)

- Any related issues:

**Comment by bsclifton** [comment]
This is not a ledger bug; this is actually a bug with opening the file (not auto detecting character set).  I've updated the title and removed the ledger tag :smile:
