### ISSUE TITLE
Ubuntu: Enable not-full-size

### ISSUE THREAD

**Issue by martinheidegger** [brave/browser-laptop#5433]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

The windows are always consuming the whole desktop space

**Expected behavior:**

I am not sure if brave doesn't work correctly anymore of this is intended behaviour but the windows consume 100% of the desktop space (full-size, not full-screen) and I am not able to make them any smaller. This is sort of problematic if I want to show two browser windows side-by-side or if I want to test webdesigns for smaller spaces.

- Platform: Ubuntu 14.04
- Brave Version: 0.12.7

**Comment by bradleyrichter** [comment]
@posix4e Hey Alex - can you check on this one? Maybe a regression caused by recent windows windowing changes?

**Comment by posix4e** [comment]
Happy to help

**Comment by posix4e** [comment]
@martinheidegger are you using unity?

**Comment by posix4e** [comment]
I am able to get the browser to act normally in unity. For instance control+shift+alt + number pad 4 (with num lock on) will send the window to the left side of the screen control + shift + alt + number pad 6  the right side

**Comment by martinheidegger** [comment]
@posix4e Yes, its unity. Ctrl + Alt + 5 (System for "Toggle maximization state") does nothing. 
Note: I also have the same problem with Atom (Electron based)

Brave: 0.12.7
Electron: 1.4.20
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by posix4e** [comment]
So brave and atom will only show up full screen? Could you tell me how you installed brave and atom?
Which one did you install first?

**Comment by martinheidegger** [comment]
Seems to be an user-error. Closing it for now, sorry for the inconvenience.
