### ISSUE TITLE
Backslash cannot be searched on about:history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5435]
**Describe the issue you encountered:** Backslash cannot be searched on about:history

**Expected behavior:** It should be enabled.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.7

- Steps to reproduce:
    1. Open about:history
    2. Search `\`
    3. The placeholder remains

- Any related issues:

**Comment by bbondy** [comment]
Removing this from the milestone; please feel free to object or re-add if you strongly disagree
