### ISSUE TITLE
Autofill form option blinks and cannot be clicked

### ISSUE THREAD

**Issue by tvance929** [brave/browser-laptop#5438]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When logging into a web form for the first time, the autofill blinks and cannot be chosen

**Expected behavior:**
Autofill dropdown option does not blink and can be chosen if the user wants to use.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:
0.12.7

- Steps to reproduce:
    1.  Go to Yahoo or Particle.io
    2. Click login and begin filling in username
    3. Autofill options blinks and cannot be chosen

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
+1 from me, this is painful to observe as a user

**Comment by bradleyrichter** [comment]
I have witnessed this one...

**Comment by Liunkae** [comment]
+1 from #5265 (with GIF example)

**Comment by Liunkae** [comment]
+1 from #5856.

**Comment by darkdh** [comment]
I see the problem now.
STR:
1. You must save username/password by using built-in password manager first
2. Type username other than the username/password in step 1 to make autofill remember
3. Start typing the username in step 2 
4. Autofill and password manager popup will conflict and blink

**Comment by Liunkae** [comment]
+1 from #5144

**Comment by r3wt** [comment]
Similar issue in opensuse. They appear and are selectable, however the arrow keys do not work to select from the choices. should i open a new issue or?

**Comment by Liunkae** [comment]
@r3wt I think you are referring to #1302 (Autofill: can't select popup item using arrow keys), which has already been fixed and will be released with 0.13.1.

**Comment by bsclifton** [comment]
@darkdh was this fixed with:
- [Hide autofill popup only when webcontent is focused #170](https://github.com/brave/muon/pull/170)
- [Follow up of https://github.com/brave/muon/pull/170](https://github.com/brave/browser-laptop/pull/7777)

**Comment by darkdh** [comment]
No, it is planned in my upcoming work: autofill password manager inegration
and btw the fix you mentioned also requires https://github.com/brave/browser-laptop/commit/396cdbcaebc480e488cd3af915a2bb21552b1c2b
