### ISSUE TITLE
Ledger notifications for adding funds should only be shown if brave payments is switched on

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5441]
I noticed it said it was time to add funds but I did not have Brave Payments enabled.

**Comment by bbondy** [comment]
See also: 
https://github.com/brave/browser-laptop/issues/5418

**Comment by ayumi** [comment]
I'm not able to reproduce.

Steps I tried:
1. Fresh browser profile / user data
2. Turn on Payments, wait for wallet create to finish.
3. Turn off Payments.
4. Close browser
5. Update ledger-state.json reconcileStamp and bootStamp to in the past
6. Reopen browser

Can you provide repro steps?

**Comment by mrose17** [comment]
@bbondy - i can't reproduce this either. i found one small bit of code that was logically correct -- but redundant -- which i simplified.

can you reproduce it on the current master? thanks!

**Comment by bbondy** [comment]
I don't know how to reproduce, my wife just got the notification on her computer, and I checked preferences and the Payments master switch was turned off.  There have been fixes since then though, not sure if it would be fixed now or not.

**Comment by bbondy** [comment]
moved to backlog until someone has steps.  Feel free to close if you think it's fixed by something else.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5721
