### ISSUE TITLE
Implement about:config

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#545]
We need a way of configuring the browser at some point.  I understand this is expermiment at this point but we need a way to control proxy usage, hybernate technologies that users don't want to run as well as homepage settings.

I know this browser takes privacy seriously but their is a danger in billing this is a privacy browser if we don't yet have the features implemented to allow users control over their footprint.

**Comment by bbondy** [comment]
++ I'm working on some about pages this week, about:newtab placeholder and about:preferences. After that's done it'd be a good time to add a more dev-friendly about:config to expose advanced things.

**Comment by halo** [comment]
I would just like to mention that configuring the browser via command-line would be helpful for mass-deployment. Having multiple machines makes me not want to spend much time clicking around manually in `about:config` 10 times (though it's certainly useful if you only have one installation of Brave).

It's [tedious](https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment) to configure browsers in an automated way (except maybe Safari). Brave could stick out here as a little more developer-friendly. [Someone suggested](https://github.com/brave/browser-laptop/issues/2214#issuecomment-226672559) even a `.braverc` file that holds advanced configurations. Now, that would be innovative! :)

Looking to and fro the issues, [I found this](https://github.com/bsclifton/browser-laptop/blob/1dea5e30c8d1aca241f32c94e030e381c6ed34e1/js/constants/appConfig.js#L80) but I'm puzzled as to where exactly these are persisted on my drive (in fact, I'm not even sure whether electron is responsible for handling this or not).

**Comment by xeru** [comment]
Definitely support this concept, would be great to have more advanced config options.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/similar-about-config/5088

Specifically user would like to see these items on this page: WebRTC; webgl; Prefetch; disableIPv6; Referer Header; enable or disable 3DES cipher; HTML5 ping

**Comment by stevespringett** [comment]
For me, I need to disable webassembly for various security reasons. I have it disabled in Firefox and Chrome, but unable to disable it in Brave.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/about-config-equivalent-for-brave-to-tweak-settings-when-necessary-please/13759?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/about-config-on-brave/18539?u=eljuno

**Comment by EvilGnome6** [comment]
+1.

I would like the ability to change the following settings:

1) Don't load pinned tabs until I select them.
2) Don't replicate pinned tabs to new Windows.

**Comment by krmbzds** [comment]
+1

I agree with everything mentioned above.

In addition, I would like to **disable conflicting shortcuts**.

These shortcuts conflict with [Spectacle](https://www.spectacleapp.com/):

- ⌥ + ⌘ + →
- ⌥ + ⌘ + ←

Behavior:
- Resizing the window to the right half of the screen also switches to the next tab.
- Resizing the window to the left half of the screen also switches to the previous tab.

Same thing should apply for other conflicting shortcuts as well.

**Comment by joeparkerz** [comment]
Why has this not been implemented yet???

**Comment by stevespringett** [comment]
@joeparkerz actually, it has been implemented. The [Brave Dev](https://brave.com/download-dev/) version incorporates this. So you can now go to chrome://settings/ or chrome://flags/ for example. And of course you can go to chrome://about/ to list all the internal URLs. The Dev version is very much like Chrome though, same look, same config, etc. They no longer seem to be hiding the fact that its built on Chrome.

I haven't personally tested it, but it is there.

**Comment by joeparkerz** [comment]
You can't be serious. chrome:flags, chrome:settings are both available on Chrome!
So what kind of advantage am I getting here?

**Comment by bsclifton** [comment]
@joeparkerz you can open an issue in our new repo, https://github.com/brave/brave-browser/issues, and describe the functionality you'd like to see

As @stevespringett said, with this new code-base, all of the chrome pages are available.  That combined with no comments in a while is why I had closed this issue. This is a feature we will not be adding to the Muon version of our product (ex: `browser-laptop`)
