### ISSUE TITLE
My Homepage should be enabled only when Brave Starts with/A new tab shows has homepage set in it

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5451]
My Homepage should be enabled only when Brave Starts with/A new tab shows has homepage set in it

- Brave Version: master

**Comment by bsclifton** [comment]
I'd have to disagree with this one after working through previous (similar) example.  cc: @bradleyrichter and @bbondy.  I'm going to remove the milestone and close, but let's talk about it (and reopen if feeling strongly)

My reasoning: 
1. You can show the home button and use it without setting "Brave Starts with/A new tab shows".

2. I had done something similar which I thought made sense UX-wise and ended up reverting it after discussion (see https://github.com/brave/browser-laptop/pull/4944 for the revert).  The change I had done disabled choosing the bookmarks toolbar types you want unless you chose to enable "always show bookmarks toolbar".

**Comment by bradleyrichter** [comment]
Here is another reason to keep it separated:

![image](https://cloud.githubusercontent.com/assets/13509546/20064925/2cb4abf2-a4c1-11e6-856a-baa130111ad2.png)

If the user is not able to define their home page address, then we would need to disable this keyboard short cut. I suspect the keyboard-nav fans would disapprove.
