### ISSUE TITLE
Provide details of each stats shown on new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5452]
Would be nice to show stat details when clicked on each of them. A small drop down with the site title and the count 

![image](https://cloud.githubusercontent.com/assets/17010094/20061087/327ddc18-a4f6-11e6-9fb6-7c441f363383.png)

**Comment by bsclifton** [comment]
Closing as stale.  Also, while this is interesting, collecting this data would take up a lot of space!
