### ISSUE TITLE
Favicons need onerror handler (as seen in about:newtab)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5455]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Favicons are loaded throughout the browser.  When they are missing, it looks really bad, since there is not a fallback image.

**Expected behavior:**
For about:newtab, the tiles can fallback to the letter being used.  For other places, a default document icon can be used.

**NOTE**: _this is a great opportunity to create a new React control which loads the image using background-url... but also loads the image using a hidden <img> tag, which has the onerror handler. This functionality can be used in multiple places, including the background image that's shown in about:newtab_

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.9 and newer

- Steps to reproduce:
    1. Go to a site that has a broken favicon
    2. Go to about:newtab
    3. Notice favicon is broken

- Screenshot if needed:
**one to look for is in the top left tile**
![image](https://cloud.githubusercontent.com/assets/4733304/20064052/94a70610-a4c6-11e6-96d1-5da3b6ea97cb.png)

- Any related issues:

**Comment by luixxiul** [comment]
This should be fixed soon.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5826#issue-191388793
