### ISSUE TITLE
svg buttons alignment on tabsbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5456]
**Describe the issue you encountered:**

<img width="134" alt="screenshot 2016-11-08 0 56 15" src="https://cloud.githubusercontent.com/assets/3362943/20064510/602611d2-a54e-11e6-8916-1fa5000d4b95.png">

**Expected behavior:** They should be aligned vertically

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues: #4852

**Comment by bsclifton** [comment]
@bradleyrichter what do you think about this? Basically aligning the kabob and the +.  Sound good?

**Comment by bradleyrichter** [comment]
yikes! yes. Kabob needs to be forced down. NewTab is perfect but we may increase the size in our next live edit-session.

**Comment by bsclifton** [comment]
@jkup could you grab this one? Bonus points if you converted it to a mask and changed the background-color to @buttonColor and the hover color to black :smile:
