### ISSUE TITLE
ads on youtube slipping through adblock

### ISSUE THREAD

**Issue by thanatos7930** [brave/browser-laptop#5457]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
sometimes ads slip through adblock and still play even when i have brave block all ads

**Expected behavior:**
block all ads when i have that setting enabled 

- Platform (Win7, 8, 10? macOS? Linux distro?):windows 10

- Brave Version:0.12.7

- Steps to reproduce:
    1.go to youtube 
    2.play a video 

- Screenshot if needed: http://i.imgur.com/DSTctuv.png

**Comment by bsclifton** [comment]
Hi @thanatos7930 I'm going to close this issue in favor of https://github.com/brave/browser-laptop/issues/4693.  You can subscribe to that issue if you want to get updates.  I'll be sure to post your screenshot there :smile:
