### ISSUE TITLE
Selected history entries don't clear selection when clicked outside the view

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5458]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Selected history items doesn't clear selection when clicked outside the view

**Expected behavior:**
Should clear selection when clicked outside the view

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8 RC1

- Steps to reproduce:
    1. Launch Brave and go to about:history
    2. Select multiple items
    3. Click outside of the selection somewhere
    4. Notice that selection is not reset

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/5223

**Comment by srirambv** [comment]
@bsclifton Doesn't seem to be fixed. 

![5458](https://cloud.githubusercontent.com/assets/17010094/20215240/d4ef8f84-a80a-11e6-85d4-bc48db66aee2.gif)

**Comment by darkdh** [comment]
@srirambv did you test this with 0.12.9 preview 1?
The commit 4571607 doesn't included
Please see
https://github.com/brave/browser-laptop/compare/v0.12.9dev-Preview1...master

**Comment by srirambv** [comment]
@darkdh Yes this is on 0.12.9 Preview 1.

**Comment by bsclifton** [comment]
What @darkdh said :smile: I'll close for now and we can retest with a new build
