### ISSUE TITLE
The about screen should show the latest SHA hash

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5462]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When running Brave, it can be hard to tell what version it is. Release candidates don't distinguish themselves clearly for example.

**Expected behavior:**
Users should be able to go to `Help > About Brave` on PC or `Brave > About Brave` on Mac and not only get Chromium versions, etc.  But also get the last SHA that was included from browser-laptop.

The ideal solution would get the SHA and put it in a meaningful location during the build process (ex: when you run `npm run build-package`

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
All

- Steps to reproduce:
    1. Install a release candidate of Brave
    2. From the menu, pick `About Brave`
    3. Notice it doesn't say this is a release candidate. How would you know?
    4. Be sad

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
<img width="480" alt="screenshot 2016-12-20 17 10 21" src="https://cloud.githubusercontent.com/assets/831718/21370007/b09672ec-c6d7-11e6-803d-a1f02dde0902.png">

**Comment by srirambv** [comment]
This is on the latest master build on Windows 10 x64
![image](https://cloud.githubusercontent.com/assets/17010094/21521135/f5897582-ccf1-11e6-8f69-e83326e48d5c.png)

cc: @bbondy @bridiver

**Comment by bbondy** [comment]
@srirambv pls post a new issue in 0.13 and tag it windows only. Thanks!

**Comment by bsclifton** [comment]
This same behavior was originally reported with https://github.com/brave/browser-laptop/issues/6406

Logic was updated to get each field in a try/catch with https://github.com/brave/browser-laptop/pull/6410

@srirambv you should be able to see the error message in the console if you launch from command line.  This should help us when you create the issue and tag as 0.13 :smile:

**Comment by srirambv** [comment]
Unable to repro after restarting from console. @bsclifton  Last time it had the same console error reported in #6442.  

After relaunching shows correct info
![image](https://cloud.githubusercontent.com/assets/17010094/21529100/1703d206-cd2f-11e6-8c1d-1ece4d72d7bd.png)

**Comment by luixxiul** [comment]
Test plan:

Open about:about
