### ISSUE TITLE
Windows Defender alert after new update

### ISSUE THREAD

**Issue by robfla** [brave/browser-laptop#5467]
**Did you search for similar issues before submitting this one?**

Yes, didn't find anything similar.

**Describe the issue you encountered:**

Just updated Brave and windows defender popped up, saying there's potentially dangerous software on my computer. Three elements were found all named "BrowserModifier:Win32/SupTab!blnk". Details saying that it's google chrome having issues and I should uninstall. After uninstalling chrome it says it is Internet Explorer that is dangerous. All that happened right after I updated Brave.

**Expected behavior:**

Windows 7

- Brave Version:

0.12.8

- Steps to reproduce:
    1. Open Brave and wait till it says there's an update available.
    2. Install update.

**Comment by privatzee** [comment]
I didn't get that alert:
Win7 x64 
Brave 0.12.8

**Comment by luixxiul** [comment]
Closing as it is stale.
