### ISSUE TITLE
replacement icons for private browsing tab icon

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#547]
@bbondy These will be used in iOS. Please convert current font awesome eyeball to these sunglasses.

![privatemode_btn](https://cloud.githubusercontent.com/assets/13509546/12736210/2b53fc94-c903-11e5-866a-f543d5949d0f.png)
![privatemode_btn 2x](https://cloud.githubusercontent.com/assets/13509546/12736212/2b56e26a-c903-11e5-806f-b15e8b097bb8.png)
![privatemode_btn 3x](https://cloud.githubusercontent.com/assets/13509546/12736211/2b54eb36-c903-11e5-804f-527b0f9d702e.png)

**Comment by luixxiul** [comment]
Surely the eyeball icon makes me psychedelic feeling..

**Comment by luixxiul** [comment]
How about trying ``fa-user-secret`` as sunglasses are yet to be implemented? (https://github.com/FortAwesome/Font-Awesome/issues/2133)

![](https://cloud.githubusercontent.com/assets/3362943/15626884/f93e6bd0-250b-11e6-8a6a-05fae18a4529.jpg)

Kinda small, but not too bad. I think this is still better than the eyeball.

**Comment by alexwykoff** [comment]
Shipped

**Comment by luixxiul** [comment]
No

**Comment by alexwykoff** [comment]
Ah, quite right. My bad.

**Comment by luixxiul** [comment]
@bradleyrichter do you have any suggestion in FA?

**Comment by bradleyrichter** [comment]
Ironically I tried the little burgler today. Still needs sunglasses. Maybe @jkuo can help me use a custom favicon of the sunglasses?

Also, we should make an about page for that tab as well.

**Comment by luixxiul** [comment]
@bradleyrichter have you made the icon already?

**Comment by bradleyrichter** [comment]
@luixxiul I have it in the new sprite bitmaps but we will need to also implement the threshold color change when used in the tab.

**Comment by bbondy** [comment]
moved to 0.14.1 for this reasoning: https://github.com/brave/browser-laptop/issues/7943#issuecomment-290079763

**Comment by bradleyrichter** [comment]
New tab styles combined with purple tab color for private non-selected creates a usability issue. Can't tell which tab is active at smaller sizes. 

It would be nice to cherry pick this tab color fix.

**Comment by luixxiul** [comment]
if this is not going to be incluyded in 0.14.1, how about releasing the next build fast, as a hotfix release?
