### ISSUE TITLE
Opening a context menu freezes video (ex: Youtube)

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5470]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When watching a Youtube video, if you right click the tab it causes the video to freeze.

**Expected behavior:**

The video should continue to play while right clicking the tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version:
0.12.8

- Steps to reproduce:
    1. Start playing a Youtube video
    2. Right click the Youtube tab (screenshot attached)
    3. See if the video freezes

- Screenshot if needed:
![screen shot 2016-11-07 at 1 12 59 pm](https://cloud.githubusercontent.com/assets/490294/20076122/144f17a2-a4ec-11e6-9808-ca62bdc0ac91.png)

**Comment by srirambv** [comment]
Same as #3280 ??

**Comment by bbondy** [comment]
Similar but I closed that one since we use about pages now. Context menus are modal for some reason which is really strange currently.

**Comment by echosa** [comment]
I also recently noticed this behavior. Note that the video's audio continues to play; only the video's image pauses.

**Comment by bsclifton** [comment]
I believe this is only a problem on macOS; updating label

**Comment by luixxiul** [comment]
We've got another report: https://community.brave.com/t/issue-with-right-click-and-video/528?u=suguru

**Comment by bsclifton** [comment]
We may be able to pull this in: https://github.com/electron/electron/pull/8702

**Comment by Liunkae** [comment]
Async context menus would be excellent!

**Comment by bbondy** [comment]
Yes this is really bad right now, we should pull it in.

**Comment by echosa** [comment]
As a Brave user on Mac, please bring this in as soon as is feasible. This is one of the (currently) ten things on my personal list of "issues with Brave". I would love to see that list dwindle quickly.

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by echosa** [comment]
1.1.0? That seems really far away. When I saw this in today's Slack update, it gave me hope for Brave...

<img width="663" alt="screen shot 2017-05-04 at 5 49 51 pm" src="https://cloud.githubusercontent.com/assets/133786/25728073/75976f72-30f2-11e7-807e-f8d422adf2da.png">

**Comment by bsclifton** [comment]
@echosa tentatively for 1.1.0 😄  I pulled the patch from Electron here:
https://github.com/brave/muon/pull/161

I need some time to troubleshoot problems seen with the code
