### ISSUE TITLE
Please add proxyswitchy omega extension

### ISSUE THREAD

**Issue by netroby** [brave/browser-laptop#5472]
https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif

Please add proxyswitchy omega extension

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/proxyswitchy-omega-extension/10228

Let's see if there are some other users who request this extension as well 👍
