### ISSUE TITLE
Navigation bar no longer centered

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5476]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
The urlbar isn't centered correctly.

**Expected behavior:**
It should be evenly spaced between the back/forward buttons and the brave icon.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
master branch
![pasted image at 2016_11_07 09_51 pm](https://cloud.githubusercontent.com/assets/490294/20079617/56a4f6d6-a4fa-11e6-945a-252c26f2dab4.png)
![pasted image at 2016_11_07 09_58 pm](https://cloud.githubusercontent.com/assets/490294/20079616/56a25a48-a4fa-11e6-95f7-a3cfcd18ac24.png)

- Screenshot if needed:

**Comment by jkup** [comment]
@bradleyrichter what is the desired look here? Should the white urlbar be centered re: the browser window or equidistant from the buttons on both sides?

**Comment by bradleyrichter** [comment]
that was the goal. (unless we decided to switch over to left-aligned.)

**Comment by jkup** [comment]
@bradleyrichter haha which one was the goal?

**Comment by bradleyrichter** [comment]
actually centered...

**Comment by srirambv** [comment]
_Almost_  centered 👍 

![image](https://cloud.githubusercontent.com/assets/17010094/20484740/8ee2004c-aff0-11e6-811b-416a18420f7b.png)

**Comment by luixxiul** [comment]
@bradleyrichter how about adding ``left: calc(38px / 2);`` to #navigator, because ``margin-right: 38px;`` is set to .navigatorWrapper #navigator?

**Comment by bradleyrichter** [comment]
excellent idea…since we need that preserved grab area on the right..

**Comment by luixxiul** [comment]
OK I will check it out. the margin-right is set with the variable `@rightMargin: @navbarLeftMarginDarwin / 2;` btw.
