### ISSUE TITLE
Change Contextual menu for hyperlinked text

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#548]
@diracdeltas Please change the contextual menu to included browser-standards order of items, plus additional Brave items as shown below:

![screen shot 2016-02-01 at 5 03 00 pm](https://cloud.githubusercontent.com/assets/13509546/12736546/fadd7e5c-c905-11e5-818d-40d5dce2f416.png)

**Comment by diracdeltas** [comment]
Closing in favor of #1253
