### ISSUE TITLE
Search Ads Appear in Google Search Results

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5486]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Ads are prominently displayed at the top of Google search results.

**Expected behavior:**

Google search results should be free from noise, clutter.

**Platform:** Windows 10

**Brave Version:** 0.12.8

**Steps to reproduce:**

1. Visit google.com
2. Search for 'header bidding' (sans quotes)
3. Note presence of ads

**Screenshot if needed:**

![image](https://cloud.githubusercontent.com/assets/815158/20095326/ebde765a-a559-11e6-85bb-87d27f2f7c41.png)

**Comment by luixxiul** [comment]
Duping to #2538, therefore #344
