### ISSUE TITLE
Insecure icon briefly displayed even for https sites wrongly

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5490]
**Did you search for similar issues before submitting this one?**
- Brave Version:
0.12.9

- Steps to reproduce:
    1. Open a new tab
    2. Load https://twitter.com
    3. Notice the insecure icon comes up momentarily

I think we're just defaulting to that icon or something before proper information is determined.

**Comment by diracdeltas** [comment]
to fix https://github.com/brave/browser-laptop/issues/5238, we may have to actually wait til load success to show the secure icon

**Comment by diracdeltas** [comment]
@bsclifton i'm going to re-assign this to myself because it's closely related to https://github.com/brave/browser-laptop/issues/5238

**Comment by bsclifton** [comment]
@diracdeltas let me check in what I have- will hit you up over Slack :smile:

**Comment by bsclifton** [comment]
My part of the fix (including a small refactor) was done with https://github.com/brave/browser-laptop/commit/5837fc5e15d77fb55dd20b6c18fad2516fe38d37

@diracdeltas will take it from here :smile:

**Comment by diracdeltas** [comment]
i will do the other fix on top of @bsclifton 's work once its merged into master

**Comment by diracdeltas** [comment]
reopening per https://github.com/brave/browser-laptop/pull/5498#issuecomment-259304024

**Comment by bsclifton** [comment]
Manually marking as closed; should have been fixed with https://github.com/brave/browser-laptop/pull/5501 :smile:

**Comment by diracdeltas** [comment]
actually not closed with #5501 it turns out, though the flickering is less than it was before

**Comment by srirambv** [comment]
Icon disappears momentarily after showing the insecure icon and right before the page content is loaded
Brave	0.13.0
rev	0c7a64d
![5420](https://cloud.githubusercontent.com/assets/17010094/21592986/7f5f0a94-d10a-11e6-9ecd-7e753e5e8096.gif)

**Comment by jonathansampson** [comment]
This does not appear to repro for me in [0.15.303](https://github.com/brave/browser-laptop/commit/04ceba3e7015c46ffd54adabf93e6470951f6fb5). If anybody else sees this issue pop up, feel free to re-open.
