### ISSUE TITLE
Backpace key does not navigate back

### ISSUE THREAD

**Issue by naylorj** [brave/browser-laptop#5491]
Hopefully self-explanatory.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win7

- Brave Version: 0.12.8

- Steps to reproduce:
    1. Click a link
    2. Hit Backspace
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@naylorj this was intentionally removed with https://github.com/brave/browser-laptop/commit/e89aa8a9bed20506a0e73fbaedd42599d4d22fce

Please see (and feel free to add comments) the discussion here for more info:
https://github.com/brave/browser-laptop/pull/424#issuecomment-257682572
