### ISSUE TITLE
Selection in the address bar does not work as I expect

### ISSUE THREAD

**Issue by mlindsey58** [brave/browser-laptop#5492]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:**
The selection of the text in the address bar does not work as I expect. When I click in the address bar, the text is highlighted as if it is selected. When I type, the new text is appended to the text in the address bar instead of replacing it. Related to this, when I click in the address bar and want to return to the root page of a site, I click on the existing URL after the domain name, I select the rest of the URL and delete it. When I hit return, Brave restores the deleted text and navigates to the 
full URL instead of the just the domain name I intended by deleting the selected text.

**Expected behavior:**
Replace selected text as expected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OSX 10.11.6

- Brave Version:
0.12.8

- Steps to reproduce:
    1. See description
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I think this will be fixed with 0.12.9 which is next release:
https://github.com/brave/browser-laptop/commit/3e6d2dee9d78f982c6edc04a1fefb220c5e71a3d

If not though please re-open this, thanks!

**Comment by getsetbro** [comment]
+1
