### ISSUE TITLE
For some users, visiting Asana causes CPU spike and constant reloading

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5493]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Certain users have visited https://app.asana.com and have experienced constant reloading and high CPU use. When trying to close the window, Brave occasionally crashes.

**Expected behavior:**
The page should load without issue.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Noticed on OS X.

- Brave Version:
This appears to have started around 0.12.7

- Steps to reproduce:
    1. Visit https://app.asana.com (our users were trying a particular list but in the interest of not sharing PII, please ask if you are an internal employee)

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Have you seen this since 0.13.0?
