### ISSUE TITLE
Magnifying glass shown on about pages on Master build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5497]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Magnifying glass shown on about pages on Master build. Also the text is not center aligned

**Expected behavior:**
Should not show the magnifying glass icon for the about pages

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
master

- Screenshot if needed:
 ![image](https://cloud.githubusercontent.com/assets/17010094/20120810/40093394-a606-11e6-8c13-3aafa3234374.png)

  Icons suggested by @bradleyrichter 
  ![image](https://cloud.githubusercontent.com/assets/17010094/20120823/57f68916-a606-11e6-94bc-be3c5e44afe8.png)

  cc: @bsclifton

**Comment by srirambv** [comment]
Also shows on error pages 
![image](https://cloud.githubusercontent.com/assets/17010094/20131677/e97e09d6-a656-11e6-9246-082f0438ad33.png)

**Comment by bradleyrichter** [comment]
we could probably use stacked FA icons to replicate the icon in this error page? That would work best.

**Comment by bsclifton** [comment]
@bradleyrichter  The error page is also an about page; (even though it may not show in the URL bar).  Any preference for which of the 3 icons you shared is best?

**Comment by bradleyrichter** [comment]
FA-list
