### ISSUE TITLE
Consider moving reload and bookmark buttons inside of address field

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#550]
![brave-toolbar](https://cloud.githubusercontent.com/assets/552390/12737049/3c11ff70-c90a-11e5-9ed7-8cee00449552.jpg)

The reload and bookmark buttons feel like they're just hanging out in space. Moving them inside the address/search widget would give them a clear container.

**Comment by SJ-Diamond** [comment]
If you really think about adding that, please only as optional setting.

**Comment by bradleyrichter** [comment]
@asadotzler Thanks for the suggestion. I know that clutter balance is a personal taste. Given that there will be more things going into the URL bar, I will keep them outside. I'll tighten the padding so they are less floaty...
