### ISSUE TITLE
Feature Request: URL bar at the bottom for Brave on Android

### ISSUE THREAD

**Issue by D0J0P** [brave/browser-laptop#5505]
First of all, thank you for finally coming out with a full-blown Brave browser for Android. That was much needed. 

I would really like it if there was an option to change the URL bar to the bottom, for easier one-handed use. Chrome Dev for Android now has a chrome://flags setting to enable this in the Chrome UI. It would be great if this flag/feature were included in Brave as a feature itself.

**Comment by srirambv** [comment]
Closing this in favor of https://github.com/brave/browser-android-tabs/issues/54 

@D0J0P You can post Android related requests/issues in https://github.com/brave/browser-android-tabs/
