### ISSUE TITLE
Edited URL based on history in URL bar autocomplete list is not reflected correctly on the URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5506]
**Describe the issue you encountered:** Edited URL based on history in the URL bar autocomplete list is not reflected correctly on the URL bar. 

![urlbar](https://cloud.githubusercontent.com/assets/3362943/20134702/c3a4dfa6-a6af-11e6-8be4-5061771a6b69.gif)

**Expected behavior:** It should be correctly reflected

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open [this link](https://www.amazon.co.jp/s/ref=nb_sb_noss?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&url=search-alias%3Daps&field-keywords=%E5%85%AC%E4%BC%9A%E8%AD%B0+%E6%AD%B4%E5%8F%B2) in a new tab
    2. Open another new tab
    3. Select the URL from the autocomplete list on the URL bar
    4. Edit it to `https://www.amazon.co.jp/` and hit <kbd>enter</kbd>
    5. The same page is reloaded, not redirecting it to `https://www.amazon.co.jp/`

- Screenshot if needed:

- Any related issues:

cc: @diracdeltas

**Comment by bbondy** [comment]
I think this was fixed by:
https://github.com/brave/browser-laptop/commit/08bfc408399e8aa7966fabbdb52d644c41ef364a

Closing this but keeping the milestone set so it'll be tested.
