### ISSUE TITLE
Opening preferences page in a new tabset doesn't switch to the one already opened in another tabset

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5507]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening preferences page in a new tabset doesn't switch to the one already opened in another tabset

**Expected behavior:**
Should switch to the other tabset if its already opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
Master 

- Steps to reproduce:
    1. Open preferences page in one tab set
    2. Create a new tabset and open preferences page
    3. Opens a new preferences page in the new tab set instead of switching to the already opened one

- Screenshot if needed:
![prefences](https://cloud.githubusercontent.com/assets/17010094/20136657/e5721ca8-a66d-11e6-81b2-40371e08b7e9.gif)

- Any related issues:

**Comment by bsclifton** [comment]
For the person wanting to grab this, here's an example of how you can make it use a single tab:
https://github.com/brave/browser-laptop/blob/ce23b92df23f28d0158e81376ec456aca2172758/app/common/commonMenu.js#L304

(basically the important part being `singleFrame: true`)

**Comment by gyandeeps** [comment]
I started looking at the code, but as mentioned above the preference menu code already has `singleFrame: true` set here https://github.com/brave/browser-laptop/blob/master/app/common/commonMenu.js#L175

**Comment by srirambv** [comment]
+1 from community community.brave.com/t/activate-existing-preferences-tab-rather-than-open-a-new-one/1816/

**Comment by DavidRBailey** [comment]
This even happens in the same tabset. If the Preferences tab isn't the last one (furthest right), Brave will open a new tab.
