### ISSUE TITLE
Add bookmark from toolbar/right click context menu brings up "edit bookmark" modal

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5508]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Add bookmark form toolbar brings up edit bookmark modal

**Expected behavior:**
Should show "Bookmark added" and show the hanger, not the modal

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.9 Preview 1
0.12.8 shows bookmark added modal

- Steps to reproduce:
    1. Enable Bookmark toolbar
    2. Right click, Add boomark, shows edit bookmark modal for the current active tab instead of add new bookmark modal
    3. Click star+ icon from about:bookmark, shows create bookmark modal 

- Screenshot if needed:
![bmktoolbar](https://cloud.githubusercontent.com/assets/17010094/20143974/f65e8d9c-a692-11e6-8102-13ecadc1a0a0.gif)

- Any related issues:

  cc: @bsclifton 
  Adding 0.12.10 as milestone, please change if required

**Comment by srirambv** [comment]
Right Click add bookmark from about:bookmark also brings up the edit bookmark modal.

![addbmk](https://cloud.githubusercontent.com/assets/17010094/20152139/f49663e6-a6b4-11e6-9ec8-1d629f37981f.gif)

**Comment by bbondy** [comment]
@jkup would you mind taking this?

**Comment by jkup** [comment]
@bbondy Yep of course!

**Comment by bbondy** [comment]
Re-opened for review comment:
https://github.com/brave/browser-laptop/pull/5717#issuecomment-263178701

**Comment by jkup** [comment]
@bbondy I read your comment about desired functionality but looking at Chrome it seems like they do exactly what we do (see screenshots) unless I'm still misunderstanding you!

It seems like maybe the thing we need to fix in this ticket is that when you right click in the bookmarks menu and click add bookmark the modal title says "edit bookmark" which isn't right. So maybe the bookmark modal needs a third state which is the Add Bookmark title with the Edit Bookmark ability to change fields.

<img width="1072" alt="screen shot 2016-12-15 at 2 35 45 pm" src="https://cloud.githubusercontent.com/assets/490294/21241201/27ae4f24-c2d4-11e6-9c6d-b991b85bab92.png">
<img width="891" alt="screen shot 2016-12-15 at 2 35 55 pm" src="https://cloud.githubusercontent.com/assets/490294/21241200/27add5bc-c2d4-11e6-9799-5563f28d0cd2.png">

**Comment by bbondy** [comment]
> @bbondy I read your comment about desired functionality but looking at Chrome it seems like they do exactly what we do (see screenshots) unless I'm still misunderstanding you!

Yes but that's because I reverted it.
I think the way it was in the PR, when you right clicked on the bookmark toolbar and click on add bookmark it wouldn't let you set the location.

**Comment by bsclifton** [comment]
Moving to contributor backlog and marked as good first bug 😄

**Comment by NejcZdovc** [comment]
This should be fixed with #9710
