### ISSUE TITLE
Feature Request : Detect tabs causing crashes and present an error page instead.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5510]
**Did you search for similar issues before submitting this one?**
No.

**Describe the issue you encountered:**
When a tab gets into a bad state it can cause a consistent crash on launch for Brave.

**Expected behavior:**
We need Brave to be able to recover from such scenarios by detecting and isolating the crashing tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

**Comment by bbondy** [comment]
I think this is the same as:
https://github.com/brave/browser-laptop/issues/5512

That one is more detailed so I"m going to close this one.
