### ISSUE TITLE
Website not getting added to the top site tile upon first visit

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5511]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Website not getting added to the top site tile upon first visit

**Expected behavior:**
Should add the site to the top site tile upon first visit itself

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.9 Preview 1

- Steps to reproduce:
    1. Visit a site in a new tab, the site should is not added to the top site tile
    2. Refresh page, site gets added to the tile

- Screenshot if needed:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17010094/20148101/f97db448-a6a2-11e6-9bcd-c97e605acb7a.gif)

- Any related issues:
cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
I'll be closing it for now in favor of #5542, since this issue is app-wise (also #4794) and not specifically related to new tab page.

**Comment by luixxiul** [comment]
Removed from 0.12.10
