### ISSUE TITLE
Offer a way for users to disable hardware acceleration

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5513]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some users may have a video card which is either unsupported or has driver issues.  These folks are technically able to run Brave, since we can disable hardware acceleration, but there isn't a way for them to do this.  Currently, the only way would be to edit the `session-store-1` file directly

**Expected behavior:**
To solve this, we should have one or more of the following:
- a documented way to disable hardware acceleration
- a menu item under HELP or auto-detection of the issue and asking "Is Brave showing for you?" which lets users disable it
- a shortcut / symlink which starts Brave w/ out hardware acceleration for folks that Brave doesn't render at all

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version:
all

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/2693
https://github.com/brave/browser-laptop/issues/4113
https://github.com/brave/browser-laptop/issues/3663
https://github.com/brave/browser-laptop/issues/4928

**Comment by Liunkae** [comment]
The setting is `advanced.hardware-acceleration-enabled` or `HARDWARE_ACCELERATION_ENABLED`, added in 497d987.

**Comment by Liunkae** [comment]
More related issues: #1392, #1471, #3787

**Comment by Liunkae** [comment]
I'll mark this very high priority (per [Triage of issues](https://github.com/brave/browser-laptop/wiki/(WIP)-Triage-of-issues), next milestone). The browser is almost unusable for a large amount of users (see the issues above). Please change the milestone if necessary.

**Comment by Liunkae** [comment]
Some users are reporting that disabling hardware acceleration does not solve the blank page problem. (#6022)

**Comment by DivineOmega** [comment]
I can confirm that in Brave v0.13 Preview 7, toggling the hardware acceleration option and restarting the browser has no effect on the blank page problem (Linux ATI open source driver, Ubuntu 16.04 LTS).

**Comment by bsclifton** [comment]
@DivineOmega there are definitely a few issues; some folks aren't even able to see the UI when launching (and they may benefit from this).  The folks experiencing issues with Linux ATI drivers may be running into a different issue for which is being tracked here (and there are some proposed work-arounds):
https://github.com/brave/browser-laptop/issues/1471

**Comment by bsclifton** [comment]
We should offer a user friendly way to do this; I now know (after lots of digging in) that we already CAN do this with Chromium flags like `--disable-gpu` or `--ignore-gpu-blacklist`
(for more info, see https://github.com/brave/browser-laptop/issues/1471)

A user-friendly way might be something like creating an additional shortcut ("safe mode" version?), detecting that the feature is not working (and prompting to start with them off), or having a really well documented troubleshooting

**Comment by luixxiul** [comment]
I thought adding another setting on `about:preferences#advanced` with a link icon, which should be displayed only on the linux distros, to our FAQ page would work too. Something like `[o] Apply --disable-gpu to fix the issue (i)` wdyt @bsclifton ?

**Comment by bsclifton** [comment]
@luixxiul that is definitely an option too; although some folks with the issue only see black inside the window (preferences page won't render)

**Comment by bsclifton** [comment]
More good info about the ACTUAL root cause here (ex: why people would want to disable HW acceleration):
https://github.com/brave/browser-laptop/issues/2579

**Comment by luixxiul** [comment]
> preferences page won't render 

yeah, def that's the issue here... :-(

**Comment by bsclifton** [comment]
Very specifically, we should have a shortcut (bundled if possible) that launches with the `--disable-gpu` parameter.  We should also consider tying our hardware acceleration parameter to this too

**Comment by bsclifton** [comment]
As noted above, users can use the command line params. [brave-core](https://github.com/brave/brave-browser) should get us more robust handling for problems that we saw which caused me to open this issue
