### ISSUE TITLE
Significant time interval in browser updating the time from system time

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5514]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Significant time interval in browser updating the time from system time

**Expected behavior:**
The time interval should not be noticeably large in updating the time in the browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.9 Preview 1

- Steps to reproduce:
    1. Open Brave and keep the new tab open
    2. Change system time manually
    3. Notice the time browser takes to update the time in new tab 

- Screenshot if needed:
https://www.dropbox.com/s/doy7q1e0c3770hm/newtabtime.mp4?dl=0

- Any related issues:
cc: @cezaraugusto

**Comment by bsclifton** [comment]
@srirambv I know it's been a while (already a whole year!) but did you have more information about this issue?  If not, can we close it?  Thanks 😄 👍

**Comment by srirambv** [comment]
Can close this one. Doesn't seem to be an issue any more. Browser time updates along with system time.
