### ISSUE TITLE
Feature Request: kerberos integration

### ISSUE THREAD

**Issue by swiftcoder** [brave/browser-laptop#5515]
My corporate environment uses Kerberos to authorise access to internal web pages. To make Brave a viable choice in this environment, I would need an equivalent of Chrome's --auth-server-whitelist flag.

See the following document for detail on Chrome's behaviour in this realm:
https://dev.chromium.org/developers/design-documents/http-authentication

**Comment by kclevenger** [comment]
+1 and soon I hope. Lack of this triggers many logins for various internal services.

**Comment by jlease** [comment]
Any update on this?  This would be a huge quality of life feature.

+1

**Comment by bsclifton** [comment]
If implemented in Chrome/Chromium with `--auth-server-whitelist`, we will get this functionality after moving to [brave-core](https://github.com/brave/brave-browser) (we support all of the same flags)
