### ISSUE TITLE
Feature request: Edit as HTML in the Developer Tools

### ISSUE THREAD

**Issue by aurerua** [brave/browser-laptop#5517]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
There is no menu when right-clicking an HTML element in the Developer Tools. I am thus missing the "Edit as HTML" option available in Chrome.

**Expected behavior:**
A menu appears when  right-clicking an HTML element in the Developer Tools allowing to choose among other things "Edit as HTML".

- Platform: 
Linux Mint 17.3 Rosa

- Brave Version:
Brave: 0.12.7
Electron: 1.4.20
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

- Steps to reproduce:
    1. right click an element on the page
    2. Choose "Inspect Element"
    3. Right-click an element in the Developer Tools
    4. Nothing happens

**Comment by jonathansampson** [comment]
I believe the issue here is with the [missing context menu](https://github.com/brave/browser-laptop/issues/3832).

For now, you can **Edit as HTML by pressing F2**.
