### ISSUE TITLE
Add CSP to app/*.html

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#552]
@diracdeltas mentions:
[For the about-* pages]
> We should set a strict CSP on pages with nodeintegration to limit the runtime attack surface. At minimum:

> default-src 'self' (don't load any resources from other origins)
> form-action 'none'
> frame-ancestors 'none' (prevent clickjacking)
> plugin-types 'none'
> referrer 'no-referrer'
> sandbox 'allow-scripts'

> app/index.html and app/index-dev.html should also have this CSP; i assume it's possible to add custom 
> HTTP headers in webpack? if not, most of these (but not all) can be specified in a <meta> element.

**Comment by diracdeltas** [comment]
updating title now that privileged pages don't use nodeintegration

**Comment by bbondy** [comment]
webpack just bundles the files by the way, so it's not an http transport in production mode. The dev server is but that's not useful to us. So I think this has to be done in meta tags.

**Comment by diracdeltas** [comment]
i see; not all of these are supported as meta tags but i'll open a pull req for the ones that are

**Comment by bbondy** [comment]
we awe can maybe use webRequest to add them though.

**Comment by diracdeltas** [comment]
the ones that aren't supported via <meta> are:
* frame-ancestors
* sandbox

but those might already be covered for `file://` URLs by Electron

**Comment by diracdeltas** [comment]
Looks like http(s) page can't iframe `file:` or `about:` (but `about:` page can iframe `file:`). i am not sure `sandbox` adds much value when all the other CSP directives are set, so i will just add the meta element for now.

**Comment by diracdeltas** [comment]
also, `plugin-types 'none'` isn't a valid directive AFAICT; we can just omit plugin-types.

**Comment by diracdeltas** [comment]
Fixed on master; follow-up in https://github.com/brave/browser-laptop/issues/584
