### ISSUE TITLE
Google search uses media query

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5521]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Google search uses media query

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.9 Preview 1

- Steps to reproduce:
    1. Set Google as default search engine and search for a term
    2. In the same search window perform a new search
    3. Notice the first search term is still shown in the URL and the subsequent search terms gets appended to the end of the URL

- Screenshot if needed:
![googles_search](https://cloud.githubusercontent.com/assets/17010094/20156042/8715dbdc-a6c6-11e6-8ba6-9d3a78a80fc1.gif)

- Any related issues:

**Comment by luixxiul** [comment]
I think this is how Google works on their side.
