### ISSUE TITLE
 since the latest update, there are many websites where 1password will no longer work

### ISSUE THREAD

**Issue by JamesJar** [brave/browser-laptop#5523]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@JamesJar do you have more information? Are you on Windows? If so, what version?

Please let us know :smile: The folks at AgileBits are very responsive and the more information we have, the easier it will be to understand and (hopefully) fix the problem :smile: Please let us know

**Comment by Liunkae** [comment]
Related: #6224

**Comment by bsclifton** [comment]
Without specific sites to try, I'm afraid there isn't much we can do.  I'm going to close but please re-open if you have any specific examples.  Thanks!
