### ISSUE TITLE
Regression : autocomplete is deleting the first character typed in the url bar

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5529]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When changing tabs and wanting to visit github.com, I clicked in the url bar and found the first character was deleted.

**Expected behavior:**
Whatever I type in the url bar should be respected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.9 RC1

- Steps to reproduce:
    1. Give focus to tab A
    2. Click on tab B
    3. Click on the url bar in tab B
    4. Quickly type a url like github.com

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
this may be because the URLbar is getting selected after the first character is typed, so whatever is typed afterward overrides the initial character. just a thought.

**Comment by bbondy** [comment]
I think this might be fixed by:
https://github.com/brave/browser-laptop/commit/fcde1241a8ae0201511921100da42f04448d6254

Please test and re-open if not.
