### ISSUE TITLE
Provide keyboard shortcuts for switching tab pages

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5532]
**Expected behavior:** Provide keyboard shortcuts for switching tab sets

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues:

**Comment by bradleyrichter** [comment]
I wonder if we could use single-key shortcuts when not in a text entry field?

Like - 1 2 3 4 5 6 7 8 9

**Comment by edmundlaugasson** [comment]
Would be also interested... **Would propose CTRL+ALT+PgUp/PgDn**. As there is already CTRL+ShIFT+PgUp/PgDn which moves the tab and CTRL+PgUp/PgDn' moves between tabs then here would be reasonable to use as proposed above. Would not use Super key as some keyboards might not have it.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/35
