### ISSUE TITLE
Regression : url bar is forcing me to use history suggestion when i want a shorter path

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5533]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting a url deeper on a site (ex : https://github.com/brave/browser-laptop/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+updated%3A%3C2016-09-09&utf8=%E2%9C%93 ) and later wanting to visit a rail along that url (ex: https://github.com/brave/browser-laptop/), the history suggestion is overriding my truncated choice.

**Expected behavior:**
If history is autocompleting in the url bar, but I delete a portion, it should respect my entry over the highlighted history item.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.9 RC 1

- Steps to reproduce:
    1. On a clean install, visit https://github.com/brave/browser-laptop/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc+updated%3A%3C2016-09-09&utf8=%E2%9C%93
    2. Close the tab, open a new tab, try to visit https://github.com/brave/browser-laptop/
    3. Observe where you really land

- Screenshot if needed:
![autocomplete_forced](https://cloud.githubusercontent.com/assets/1434040/20165100/fc0978f0-a6cf-11e6-8fb6-346c0dc38750.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #5506
