### ISSUE TITLE
Pages are rendering too slowly

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5536]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When opening a new tab it takes a ... really... long... time...
It was also noticed that common pages were also rendering slowly on first visit.

**Expected behavior:**
It should be considerably faster.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.9 RC1

- Steps to reproduce:
    1. Open a new tab
    2. Open a new tab
    3. Open a new tab

- Screenshot if needed:
![slow_open_tab](https://cloud.githubusercontent.com/assets/1434040/20181863/6dc9544c-a725-11e6-9453-1f313a0d7504.gif)

- Any related issues:

**Comment by bbondy** [comment]
Could you double verify on 0.12.8 and 0.12.9 to make sure this is new? I want to make sure it's not from something like a background process running. In particular I mean for pages that are not the new tab page.

**Comment by bsclifton** [comment]
I'm not sure what kind of action to take here- I guess we can wait until the new built happens before revisiting?  Setting the cache-control headers might help, since now it shouldn't even make an external request for the images (well, once they're cached)

**Comment by bbondy** [comment]
there seems to be something weighing down the browser in general, I'm not sure what but I think we have to bisect to figure it out.  Profiling cpu showed time in ipc sync send which is normal.

**Comment by bbondy** [comment]
This seems faster with master so I'm going to close and please re-open if it's slow in the next build.

**Comment by bbondy** [comment]
nevermind I just experienced the slowness again.

**Comment by bbondy** [comment]
I had to bisect this, but found it and reverted here:
https://github.com/brave/browser-laptop/commit/037f7c057d06e7573a61d677ac3822b795d5ec9b

**Comment by bbondy** [comment]
Re-opened this issue 
https://github.com/brave/browser-laptop/issues/4274
which caused the problem after the revert, so closing this now:

**Comment by srirambv** [comment]
Looks good on Windows
![5536](https://cloud.githubusercontent.com/assets/17010094/20263171/604fcea0-aa5d-11e6-9e71-21441bb637aa.gif)

**Comment by srirambv** [comment]
Looks a little slow on Ubuntu. Could be because of VM.
