### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by r98gaskin** [brave/browser-laptop#5538]
**Did you search for similar issues before submitting this one?**  Yes.

When loading pages for our club website (http://www.lmsc.org) a connection reset error message is displayed.  The page loads after a 2nd attempt using the "Retry the URL" button, refresh icon, or similar.  This behavior is not replicated using Google Chrome or Internet Explorer.   This behavior is not replicated for other websites

The page should load immediately and require no repeat attempts to display.

Our website uses Wordpress version  4.6.1 as its content management platform.  The OS I use to add or edit content is Windows 7

- Brave Version: 0.12.8

- Steps to reproduce:
    1.  Launch Brave
    2.  Enter URL for http://www.lmsc.org

- Screenshot if needed: ![connectresetcapture](https://cloud.githubusercontent.com/assets/23383592/20184227/f2f5318a-a735-11e6-936e-21a0e91c251d.JPG)

- Any related issues:  Attempts to login using the Wordpress plugin Ajax sometimes produce a login error.  As with the page connection  reset error, a 2nd attempt at login will besuccessful

**Comment by luixxiul** [comment]
The issue cannot be reproduced.
