### ISSUE TITLE
Pressing Esc after entering in URL bar clears the complete text

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5539]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pressing Esc after entering in URL bar clears the complete text

**Expected behavior:**
Should retain the entered text, esc should only clear the suggestion pulldown

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 x64

- Brave Version: 0.12.9 Preview 1
0.12.8 doesn't clear the entered text

- Steps to reproduce:
    1. Open a new tab 
    2. Type in the URL so that auto suggestion list drops down
    3. Press Esc key, clears the entered text along with the drop down suggestion list

- Screenshot if needed:
![clearurl](https://cloud.githubusercontent.com/assets/17010094/20184318/35bd17ce-a760-11e6-9a71-8dfa53133711.gif)

- Any related issues:
#5529

**Comment by bbondy** [comment]
This changed recently to work the same as Chrome, but if you find it does not (and I'm not understanding the issue), please re-open and put back in the milestone.
