### ISSUE TITLE
History not being updated on first-time site visit

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5542]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When visiting a website, about:history should be updated with each new access, which is not happening unless you refresh the page (2nd access).

**Expected behavior:**
About:history should be updated on the first website visit.

- Platform (Win7, 8, 10? macOS? Linux distro?): n/a

- Brave Version: 0.10.9

- Steps to reproduce:
    1. Open Brave
    2. Visit a website
    3. Check about:history
    4. Visited site is not there
    5. Go back to website, refresh page
    6. Site is updated on about:history

- Screenshot if needed: n/a

- Any related issues:
Not really related to the issue but being affected: #5511

**Comment by Sh1d0w** [comment]
Possibly related issue https://github.com/brave/browser-laptop/issues/4794

**Comment by bsclifton** [comment]
Haven't had time to look at this yet :frowning_face: I'll move to 0.12.11

I'll un-assign myself for now (please feel free to grab this!).  Will check out next week

**Comment by bsclifton** [comment]
@cezaraugusto this might be a good one for you to check out- let me know if you're interested

**Comment by cezaraugusto** [comment]
Taking

**Comment by bbondy** [comment]
I think it eventually does show so moving to backlog for now, would love a fix.

**Comment by NejcZdovc** [comment]
@cezaraugusto Can you please check if this is already fixed?

**Comment by cezaraugusto** [comment]
@NejcZdovc good find, not an issue anymore.
