### ISSUE TITLE
Facebook tracking pixel needs exterminating (Flipkart) 

### ISSUE THREAD

**Issue by privatzee** [brave/browser-laptop#5545]
**Did you search for similar issues before submitting this one?**
y
**Describe the issue you encountered:**
tracking pixel isn't blocked
**Expected behavior:**
block all spies
- Platform (Win7, 8, 10? macOS? Linux distro?):
w7x64
- Brave Version:
0.12.8
- Steps to reproduce:
    1. go to https://www.flipkart.com/
    2. observe:
    

![image](https://cloud.githubusercontent.com/assets/22591438/20195568/1cfc42be-a765-11e6-9c2f-c191ebf1f9ac.png)

---
which is a 1x1 gif

![image](https://cloud.githubusercontent.com/assets/22591438/20195674/7bc878f8-a765-11e6-81c4-58a504cdbf8d.png)

---
HTTP response **tries** to set-cookie, also with always downloading and never caching the img

![image](https://cloud.githubusercontent.com/assets/22591438/20195906/51bdf2da-a766-11e6-838e-bcc8401e5b55.png)

---
which is loaded from the script:

![image](https://cloud.githubusercontent.com/assets/22591438/20196160/70ba3ee0-a767-11e6-8f0d-057d7bca87b2.png)

---

which is loaded from flixcart.com:

![image](https://cloud.githubusercontent.com/assets/22591438/20196405/9636b77e-a768-11e6-8eeb-9ad8a48c24a1.png)

#2764

**Comment by privatzee** [comment]
with settings like this:

![image](https://cloud.githubusercontent.com/assets/22591438/20196719/002e4858-a76a-11e6-8e75-d28c00fff058.png)

---

and this:

![image](https://cloud.githubusercontent.com/assets/22591438/20196750/1ac53564-a76a-11e6-8e11-6aea2c135b1c.png)

**Comment by privatzee** [comment]
note that the cookie is successfully blocked:

![image](https://cloud.githubusercontent.com/assets/22591438/20197030/61e00e1e-a76b-11e6-9326-ef063184b89b.png)


but FB still gets the user's IP, and if most users don't change the Fingerprinting protection from default off, then FB gets more than the IP

**Comment by privatzee** [comment]
and FB also gets the GET data, so they know that I (Mr. 1469476963265313) put Wayfarer sunglasses in my cart:

>id:1469476963265313
ev:cartPage
cd[pcat]:sunglasses,irayz-sunglasses
cd[pname]:IRAYZ Irz-632-Fkt Wayfarer Sunglasses
cd[value]:259
cd[brand]:IRAYZ


...and in a comment above, you can see in the screencap that there are Adobe Marketing Cloud (AMC) cookies, which means that the Brave user's data can be sold in an instant by Flipcart, then possibly traded all over the world to so-called _2nd party_ marketers via Adobe's Audience Marketplace (if Flipcart is in that program).

Note that Adobe's AMC cookies are served by Flipcart and so they are 1st party and unblocked.

----
google/doubleclick is also doing pretty much the same thing as FB, except their gif is in a data url
 ---
well, at least criteo and demdex scripts were blocked (though demdex is now owned by adobe anyway)

**Comment by privatzee** [comment]
Note: if I go to Flipkart in an Electron `<webview>`, then the cart works okay.

Naturally, Chrome works okay or they would have fixed Flipkart by now if it didn't.

Also, the renderer is constantly talking to the main in Brave, but not in Chrome.

**Comment by flamsmark** [comment]
This looks like a specific case of #2764.
