### ISSUE TITLE
Add ability to specify download directory

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5551]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
From support: users would like to be able to set the default download directory for Brave. Chrome, FF and IE all have this.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
All

**Comment by bradleyrichter** [comment]
@jkup Close this one if you are satisfied with the original issue #2110...

**Comment by jkup** [comment]
Yep, it's a dupe.
