### ISSUE TITLE
Widevine video playback occasionally stutters

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5557]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Occasionally the video playback on Netflix will stutter. The CPU and RAM usage appear to be acceptable (less than 20% CPU, 800Mb for Brave Helper, 400Mb for Brave)

**Expected behavior:**
The video playback should be smooth.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.9 Preview1

- Steps to reproduce:
    1. Go to Netflix and play a movie

- Screenshot if needed:
I have screen recording which may have a few hints at stuttering. 

- Any related issues:

**Comment by bbondy** [comment]
Please re-escalate if this is a problem w/ chromium 54.   I'll remove the milestone for now until it gets more voted up too.

**Comment by alexwykoff** [comment]
This problem has been noticed again in 0.15.313 
cc: @bbondy

**Comment by luixxiul** [comment]
+1 from me, on Windows 10.

**Comment by srirambv** [comment]
Worked fine on my Windows machine for both x64 and ia32. No issues on 0.15.313 and 0.15.314
