### ISSUE TITLE
Cannot close tabs or change tab focus 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5558]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing 0.12.9 Preview 1, I opened many tabs in window 1. I left it in the background for a considerable time. I would occasionally use one or two tabs in window 1. I later opened window 2 and watched a clip of a movie on Netflix. After closing that window, I returned to window 1 and found that I could not close the tab or change tabs. I then opened the developer console and found numerous errors. 

**Expected behavior:**
Tabs should be able to close or change focus.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.9 Preview 1

- Steps to reproduce:
    1. Please see above. It will likely be sporadic/heizenbuggy so I have saved off my data in an archive I will share with the internal team.

- Screenshot if needed:
![close_tabs](https://cloud.githubusercontent.com/assets/1434040/20204925/b85c84b0-a799-11e6-9619-945a296cffbc.gif)

- Any related issues:

**Comment by bbondy** [comment]
I think this is the same as https://github.com/brave/browser-laptop/issues/5560
So I'll close as a dupe, but keep in the milestone to make sure it goes through testing.
