### ISSUE TITLE
Uncaught exception when running on OS X

### ISSUE THREAD

**Issue by indutny** [brave/browser-laptop#556]
```
Uncaught Exception:
TypeError: Wrong number of arguments
    at TypeError (native)
    at Array.Filtering.registerFilteringCB (/Users/findutnyy/Code/brave/browser-laptop/app/trackingProtection.js:48:26)
    at Function.<anonymous> (/Users/findutnyy/Code/brave/browser-laptop/app/filtering.js:36:43)
```

**Comment by indutny** [comment]
Just in case, I just followed instructions in readme, attempting to build and run it, and got this.

**Comment by bbondy** [comment]
Thanks for posting this is related to an upgrade we're doing on one of our blocking libs for an API change and our package.json being too restrictive. Should be fixed now but you should remove and re npm install your node_modules/tracking-protection.

**Comment by indutny** [comment]
Thank you, will take a look at it today!

**Comment by indutny** [comment]
It builds and runs perfectly now, thank you!
