### ISSUE TITLE
Harry Reid URL mangled before access

### ISSUE THREAD

**Issue by allenwb** [brave/browser-laptop#5564]
**Describe the issue you encountered:**

Paste this URL into the address bar: http://www.reid.senate.gov/press_releases/2016-11-11-reid-statement-on-the-election-of-donald-trump#.WCXwFBA0BKp 
Hit enter
The URL transforms to: https://www.senate.gov/#.WCXwFBA0BKp
Page not found response from server
works in other browsers

Alternative repo:
In Brave, open https://twitter.com/rebeccawb/status/797110128663142400
click on Harry Reid article

**Expected behavior:**
Display referenced page

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12
- Brave Version:
Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

**Comment by luixxiul** [comment]
The sever has already been unavailable.

If you are still around here, would you please join https://community.brave.com? :smile: There is a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
