### ISSUE TITLE
I am trying to use WSJ.com but I get "certificate error" message

### ISSUE THREAD

**Issue by Skiiowa** [brave/browser-laptop#5569]

**Comment by privatzee** [comment]
It looks like wsj.com has not set itself to be used over https. E.g., if I go to http://www.wsj.com with PaleMoon or Firefox (with HTTPS Everywhere installed), then the connection is not upgraded to https. If I force it to https://www.wsj.com/ then I get the same cert error.

**Comment by Skiiowa** [comment]
Thanks for following up.

I am not a computer expert but I am not sure this is the issue.

The only problem with https is when it is accessed as the home page. I can access the Barron’s URL [sister site], then click on WSJ from the Barron’s site. WSJ comes up fine and then I can save it to the favorites bar. Once I am sure I have the issue I will contact the WSJ help site.

Am I missing something or am I confused?

Steve Lansing
407-234-3265

[Chi rho][american-dream[1]]
           Faith, Family, Community, and Work  =
             Ordo Amoris   /   Eudaimonia

**Comment by privatzee** [comment]
It looks like you've discovered a fault in Brave, Steve. Keep in mind that Brave is still in development, it's not at version 1.0 yet.

You're right that Brave loads pages that aren't the home page, e.g.: https://www.wsj.com/articles/obama-administration-gives-up-on-pacific-trade-deal-1478895824  But it shouldn't have, and it could not have properly loaded the page over https.

If we try the same page in Firefox, we see there is no certificate for wsj.com, only for akamai which is something like a middleman:

![image](https://cloud.githubusercontent.com/assets/22591438/20242272/cf1f9a94-a8f6-11e6-8c12-e17af208e5d4.png)

and next in Chrome, the same error that there is no certificate for wsj.com:

![image](https://cloud.githubusercontent.com/assets/22591438/20242394/5c18ddae-a8fa-11e6-82b7-69d907763dac.png)


Tomorrow if I have a time, I'll set up a proxy and see what it is that Brave is doing. But yes, it is a good idea to contact WSJ and tell them that they should be using HTTPS.

**Comment by Skiiowa** [comment]
Thank you again. Since you are very helpful and responsive, I would like to adopt you as my tour guide for Brave. ☺

I do have another issue. Some of the websites do not have favicons that appear on the favorites bar. There are just blank spaces for these sites. It seems to me Brave could make available “plug” favicons that could be used for sites that do not have their own.

Steve Lansing
407-234-3265

[Chi rho][american-dream[1]]
           Faith, Family, Community, and Work  =
             Ordo Amoris   /   Eudaimonia

**Comment by Liunkae** [comment]
Hi @Skiiowa! The problem of bookmarked sites without favicons is being tracked in issue #2075. Currently, the problem is scheduled to be fixed by version 0.12.10, which will be released about a week from today.

**Comment by Skiiowa** [comment]
Great, thanks.

Steve

Stephen J. Lansing
407-234-3265

[Chi rho][american-dream[1]]
         Faith, Family, Community, and Work  =
            Ordo Amoris  /   Eudaimonia

**Comment by MouseZero** [comment]
Thanks for the reply!! I'm interested in this issue as well. https://meetup.com/ is exhibiting similar symptoms.

**Comment by diracdeltas** [comment]
WSJ has updated their site to use valid HTTPS (https://securethe.news/sites/the-wall-street-journal) so I think this is resolved.
