### ISSUE TITLE
Brave won't open on Windows Insider Build PC but will open on anniversary update PC

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#5577]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
When I open up brave on my Windows Insider build PC, it makes processes in the task manager but the browser doesn't open. I tried it on my Windows anniversary update laptop and the browser opens up just fine
**Expected behavior:**
To open up on my Desktop
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Preview Build 14965
- Brave Version:

- Steps to reproduce:
    1. Download brave on Windows Insider Build 14965
    2.  Try to Open it
    3. Nothing opens up but there are tasks in the Task Manager

- Screenshot if needed:
http://i.imgur.com/fIDqXL8.png. The browser is not open but there are tasks running in the background
- Any related issues:

**Comment by bsclifton** [comment]
@Legitgamer264 we may have found the root cause for this issue; if you were willing to try a release candidate, we have one available here:
https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-RC5

**Comment by Legitgamer264** [comment]
@bsclifton I will try that as soon as I can. Thank you!

**Comment by JMccormick264** [comment]
trying this now. sorry for the delay

**Comment by JMccormick264** [comment]
Update. Been trying to solve the issue. The installation is seemingly stopping half way through. I have tried Clean uninstalling it with iObit Uninstaller. Restarting my computer. It is not finishing to install.

Here is what I see
After it seeming to pause, I closed it and tried to re-do the install. First error box I got was this http://i.imgur.com/O7ECWuN.png

Next after clicking "ok" I get this http://i.imgur.com/h0KA2AR.png
And here is the debug log http://pastebin.com/njTrvY6R

You may ask Why Discord and other apps are in that log? I have no clue actually. I don't want to remove parts because I don't know what I am looking at. I hope this helps. I do have node installed. I am able to run npm in command prompt to build github repos. So I am not sure why that node error is popping up. you will probably know more about what is causing all of this than I do

**Comment by bsclifton** [comment]
@JMccormick264 can you try running the installed as Administrator? I'm thinking that you must have the dependencies installed using your admin account and it's not able to escalate properly

You should be able to do this by right clicking and picking `Run as Administrator` (has the shield icon).  Let us know if this works 😄

**Comment by JMccormick264** [comment]
I tried that and it installed, but still won't open. I do get tasks in Task Manager that get opened, but no browser opening http://i.imgur.com/2T12xMU.png

**Comment by JMccormick264** [comment]
If you have any debugging tools/information gatherers, I am totally okay with running those. Whatever you think may help, I can do. I don't mind the sharing of information

**Comment by bsclifton** [comment]
@JMccormick264 awesome- glad to hear it installed 😄   Maybe you can now also try editing the shortcut.  Right click, pick properties... you should be on the shortcut tab

Now click the advanced button and check `Run as administrator` and click OK.  Give this a shot and let us know if it works 😄 
![screen shot 2017-01-30 at 9 05 17 am](https://cloud.githubusercontent.com/assets/4733304/22430383/480c2960-e6cb-11e6-8b96-3f102d02b579.png)

**Comment by JMccormick264** [comment]
I will do that when I get home. Unfortunately I had to leave for school. I will set a reminder so I don't forget!

**Comment by JMccormick264** [comment]
That did not solve the issue. Darn

**Comment by JMccormick264** [comment]
This issue is going to be closed. Just did a reset on my computer and it fixed itself. Latest commit from GitHub as well as the one on website work. It may have just been my computer.

**Comment by luixxiul** [comment]
OK thanks for the report.
