### ISSUE TITLE
brave@0.7.12 watch: `webpack-dev-server`Exit status 1

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#558]
[npm-debug.log.txt](https://github.com/brave/browser-laptop/files/113502/npm-debug.log.txt)
Console shows

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
npm ERR! Linux 3.13.0-76-generic
npm ERR! argv "/media/stuff/opt/node-v5.5.0-linux-x64/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! brave@0.7.12 watch: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the brave@0.7.12 watch script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by FrancisTurner** [comment]
This is after a git pull and npm install.

**Comment by psimyn** [comment]
do you have something else running on port 8080? 

Maybe check with: 
```
lsof -n -i4TCP:8080 | grep LISTEN
```

**Comment by FrancisTurner** [comment]
ah yes. A zombie previous version of webpack :)

Is there a godo way to kill one wihtout manually doing kill ?

**Comment by psimyn** [comment]
not an especially _good_ way, but you could chain ` | awk '{print $2}' | xargs kill` onto the previous one

**Comment by bbondy** [comment]
You can set `BRAVE_PORT=9001 npm run watch` and `BRAVE_PORT=9001 npm run start`. Would also be great to have a pull request with that info if anyone has a chance.
