### ISSUE TITLE
typing over urlbar selection, should allow your typed change

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5582]
1. Have a history with brave.com
2. In the urlbar type bra, then press down arrow to go to brave, or move mouse to highlight the suggestion
3. Press x

It should allow you to type x and it should not use the suggestion text.

**Comment by luixxiul** [comment]
1. Have a history with brave.com
2. In the urlbar type bra, then press down arrow to go to brave, or move mouse to highlight the suggestion
3. Press x

4) `bravex`
5) Open another tab and re-select the original one
6) `bravex flea and tick`, if you have enabled autocomplete of search terms
