### ISSUE TITLE
URLBar should retain focus per tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5586]
This was always a problem in Brave, but just posting it since I'm working on various URLbar problems.  

STR:
1. Open 2 tabs and navigat somewhere in each
2. Click on the urlbar in tab 2
3. Go to tab 1 and click on the webview
4. Go to tab 2

Actual results:
It should focus the urlbar

Expected results:
The webview is focused

**Comment by michalbe** [comment]
I cannot reproduce this anymore in 0.13.2

**Comment by bbondy** [comment]
I fixed this sometime in the past

**Comment by bbondy** [comment]
Thanks for the triage help too ;)
