### ISSUE TITLE
Drag and drop on bookmark manager (trying to manually sort) is broken / unintuitive

### ISSUE THREAD

**Issue by strider72** [brave/browser-laptop#5589]
I can't actually sort Bookmarks in the Bookmark Manager. If it's possible to do, the interface is **extremely** unintuitive. I try to drag and drop, and it simply doesn't work. If I move something into a folder, it's put on the bottom and can't be moved.  Very frustrating for such a basic function.

Mac OS 10.12.1
Brave 0.12.8

(also: copying the text in About Brave dialog somehow just copies the Brave.com URL!)

**Comment by bsclifton** [comment]
This is definitely frustrating; we have integration with React DnD (used for the about:newtab page) which might provide a better experience.  Besides the drag and drop library itself, we'd want to consider lots of visual cues, such as showing a horizontal line when bookmark is mid-drag, so you know where it will be dropped too, etc

**Comment by yannduran** [comment]
Even with the issue of drag and drop, I can't seem to find ANY way of sorting bookmarks in a folder. Right-clicking a folder to sort the bookmarks in that folder (like in FireFox) seems to be a very basic requirement, no?

Windows: 10 (anniversary update)
Brave: 0.12.15

**Comment by bsclifton** [comment]
@yannduran we do have an issue open tracking sortable bookmarks, if you wanted to give it a +1 :smile: 
https://github.com/brave/browser-laptop/issues/2171

**Comment by yannduran** [comment]
@bsclifton Thanks for the heads-up Brian! I have indeed given it a +1

**Comment by bsclifton** [comment]
Closing this issue in favor of https://github.com/brave/browser-laptop/issues/6246
