### ISSUE TITLE
MacOS 10.10.5: brave@0.7.12 check-security: `nsp check`; Exit status 1

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#559]
After pulling the recent changes the npm run build-package fails. It throws errors when running nsp check.

It's also showing a Regular Expression Denial of Service Vulnerability:

Name: moment
Installed: 2.11.1
Vulnerable: All
Patched: None
Patch: brave@0.7.12 > tracking-protection@1.1.0 > nsp@2.2.0 > joi@6.1…
More Info: https://nodesecurity.io/advisories/55

I'm running nvm using node v5.5.0 and npm 3.6.0.

**Comment by bbondy** [comment]
@SergeyZhukovsky can you fix this and then do an update? Thanks.

**Comment by SergeyZhukovsky** [comment]
Fixed it and updated.
Thank you @SpikeShape for the check.
