### ISSUE TITLE
newtab - Have default top sites available

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5594]
When there aren't any top sites yet (brand new session), we can pre-load Brave with a few top sites.

cc: @bradleyrichter 

[twitter (@brave)(pinned)](https://twitter.com/brave)
[facebook (brave)](https://www.facebook.com/BraveSoftware/)
[Brave.com](https://brave.com/)
[github (brave)](https://github.com/brave/browser-laptop)
youtube (brave)
playstore (brave)

**Comment by bradleyrichter** [comment]
Let's try this and see how feedback goes.

**Comment by srirambv** [comment]
This would be very similar to the speedial feature with defaults?

**Comment by bbondy** [comment]
Why youtube channel over iOS?

**Comment by bradleyrichter** [comment]
twitter (@brave)(pinned)
facebook (brave)
youtube (brave)
Brave.com
ios appstore (brave)
playstore (brave)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5623#issue-189272120
