### ISSUE TITLE
tab set focus changes by swiping desktops on macOS

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5601]
**Describe the issue you encountered:** tab set focus changes by swiping desktops on macOS

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Create another desktop
    2. Open enough tabs to create the 2nd tab set
    3. Select a tab in the 2nd tab set
    4. Select the 1st tab set
    5. Swipe desktops
    6. The 2nd tab (where the active tab exist) is selected 

- Any related issues:

**Comment by salty-horse** [comment]
I can confirm on Ubuntu 16.10 and Brave 0.12.10.

Ubuntu uses ctrl+alt+left/right arrow to switch between desktops.
Brave uses it to switch between tabs.
When Brave is open, sometimes it takes over the hotkey. When it does, the hotkeys don't switch between desktops.

It seems inconsistent: Sometimes Brave handles the hotkey and sometimes it doesn't. In some tests, the desktop switching hotkey didn't work after minimizing Brave, and even after closing it altogether.

No other browser I know of uses this shortcut to switch between tabs. Firefox uses Ctrl+pgup/down. Consider removing it altogether?
