### ISSUE TITLE
Password not saved for https://members.cdbaby.com/login with Brave password manager

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5602]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From [Support](https://linkbubble.zendesk.com/agent/tickets/6707)
User reported password is not saved for https://members.cdbaby.com/login with Brave password manager

**Expected behavior:**
Should save id/password with default builtin password manager

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8

- Steps to reproduce:
    1. Visit https://members.cdbaby.com/login 
    2. Set Brave password manager in security
    3. Login with valid credentials, Doesn't offer to store password

- Screenshot if needed:

- Any related issues:

**Comment by andrewklimek** [comment]
Funny to see this here.  I'm also having problems with cdbaby login.  They sign you out very quickly, so it's a bit tedious.

on 0.13.5

**Comment by andrewklimek** [comment]
This login form is not technically a form (no form element).  It's just 2 fields and the submit button is an <a> element with some custom action.

Looking at passwordManager.js, I'm guessing that's the problem.

FWIW I've never had a problem with other browsers on this login.

**Comment by andrewklimek** [comment]
This is fixed in 0.16.0 be76cd3
