### ISSUE TITLE
brave .12 siezed up while trying to  post bug to github.com

### ISSUE THREAD

**Issue by pleabargain** [brave/browser-laptop#5603]
**Describe the issue you encountered:**
.12 brave siezed
**Expected behavior:**
should never sieze up
- Platform (Win7, 8, 10? macOS? Linux distro?):
ubuntu 16.04
- Brave Version:
.12
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
here's the video
https://youtu.be/D-z8hOMi0pc

- Any related issues:
was trying to get https://voyant-tools.org to display graphical link frame in a diff. tab

**Comment by pleabargain** [comment]
Just happened again. Brave seized up totally trying to enter an issue (for a different project)
v.
Brave: 0.12.0
Electron: 1.3.10
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

This software uses libraries from the FFmpeg project under the LGPLv2.1

ubuntu 16.04

**Comment by bsclifton** [comment]
Hi @pleabargain (sorry for the delay in response)

Can you try clicking the lion head in the top right when you're on GitHub.com?  What features do you have enabled?  I'd encourage you to try disabling fingerprint protection (if it's enabled).  If that doesn't work, you can try turning shields off.  These changes will only be saved for GitHub.com

**Comment by pleabargain** [comment]
@bsclifton thanks but no joy

Brave: 0.12.0
Electron: 1.3.10
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev


just crashed again trying to post a different bug against brave
here are my settings
![my setting on brave screenshot from 2016-12-25 16-18-16](https://cloud.githubusercontent.com/assets/640846/21471518/663305b8-cabe-11e6-96bb-567f8c2fa613.png)


 and here is a screen grab of the lock up screen. Brave has stopped working. Restart brave after a hard xkill stop.
![bravecrashing on github again](https://cloud.githubusercontent.com/assets/640846/21471520/692a4ea2-cabe-11e6-9a45-57d4ff577635.jpg)

I have tried again on brave to use github and it crashed again. I can NOT use brave on github to post bugs. :(

OS
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by luixxiul** [comment]
For now I'm going to close this issue as stale.

If you are still around here, would you please join https://community.brave.com to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
