### ISSUE TITLE
Improve error message for payments 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5606]
![image](https://cloud.githubusercontent.com/assets/17010094/20266815/bb2bbd7c-aa6f-11e6-808a-e8495667c585.png)

`This site` Users will question **Which site??** 

Wouldn't it be simpler to just say **Brave Wallet can't be reached, Please check your Internet connection.** instead  saying an error occurred and showing DNS error message

Also monthly budget dropdown should be disabled and status shouldn't show **Your Wallet is ready!** when it can't retrieve info. Status should be hidden when the wallet balance is not shown

cc: @mrose17 @bradleyrichter @ayumi 

- Related issue
#4920

**Comment by jkup** [comment]
I agree with the "This Site" part. I think a more generic error message would be great. As for the disabled fields.. is there a situation you can get into where your wallet is ready and you already have a monthly budget set but we just can't get your balance right now?

I only worry about making the entire feature look disabled when really we're just offline so can't get a real time balance.
