### ISSUE TITLE
Add option to forward a link via email

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5607]
From support: https://linkbubble.zendesk.com/agent/tickets/5934

A nice-to-have implementation, may be similar to Safari:

![share_link](https://cloud.githubusercontent.com/assets/4672033/20269417/2781f12c-aa6a-11e6-8910-7cba2ac01a2e.jpg)

**Comment by luixxiul** [comment]
Duping to #3121?

**Comment by cezaraugusto** [comment]
Marking as so, thanks!

Closing in favor of #3121
