### ISSUE TITLE
Mouse cursor should be inactivated during typing/scrolling on autocomplete list on URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5612]
**Describe the issue you encountered:** If your mouse cursor is on the autocomplete list on the URL bar, an entry where the cursor exists keeps being selected.

**Expected behavior:** Mouse cursor should be inactivated during typing/scrolling to pause auto selection in autocomplete list on the URL bar.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version:

- Steps to reproduce:
    1. Open https://apple.com, https://audiofingerprint.openwpm.com/, and http://www.about.com/
    2. Bookmark them (to create the autosuggest list large enough)
    3. Make the height of the browser window smallest to show vertical scroll bar on the autosuggest list
    4. Open a new tab
    5. Hit ``a`` on the URL bar
    6. Do a mouse scroll with the middle button to select the 1st entry above on the list
    7. *You can't touch this!*

- Screenshot if needed:

![youcanttouchthis](https://cloud.githubusercontent.com/assets/3362943/20275442/e3c79a78-aadb-11e6-9d86-af0cfb082d3d.gif)

- Any related issues:

**Comment by bbondy** [comment]
Great steps to reproduce 👍

**Comment by luixxiul** [comment]
Still it seems that the mouse cursor is not inactivated.

![facebook](https://cloud.githubusercontent.com/assets/3362943/20464015/94ac0644-af82-11e6-97a7-2834830fe3a8.gif)

**Comment by luixxiul** [comment]
Please reopen if the issue above is the same as the first one.

**Comment by srirambv** [comment]
Still an issue on Windows. Reopening  the issue

![5612](https://cloud.githubusercontent.com/assets/17010094/20477208/79ae5230-afcc-11e6-9a3b-a18174f10329.gif)

**Comment by bbondy** [comment]
that behavior is fine, the thing that was fixed here is that before when you scrolled it would actually fill the url with one of the things you highlighted over and then the highlighting would stop.  As it works now what's under your mouse cursor just goes into the selected part which gets cleared with the next char.
