### ISSUE TITLE
Wrong favicon on bookmarks bar

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5613]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When bookmarks bar is in favicon only mode, sometimes the wrong favicon saves for a site.

**Expected behavior:**
Favicons should match bookmarked websites.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.8

- Screenshot if needed:

See the Gmail favicon pointing to Facebook

![favicon](https://cloud.githubusercontent.com/assets/490294/20275597/32c9ca30-aa67-11e6-9500-2be5ea158aa0.png)

- Any related issues:

**Comment by bsclifton** [comment]
I think this is a dupe of https://github.com/brave/browser-laptop/issues/1646

**Comment by jkup** [comment]
@bsclifton yep looks like a dupe! Also looks like it's still happening!
