### ISSUE TITLE
Restrictions of blocking ads

### ISSUE THREAD

**Issue by Corbyj1** [brave/browser-laptop#562]
So I decided to do a quick look over of a few client websites to see how they performed in Brave. A couple different scenarios I've came across which may not be an issue for Brave but could be for the client and vice versa so I thought I'd post them anyway in case others have these issues. 

1) Naming your CSS file/class something that is ad blocked (eg, "adverts.css"). Take a look at [Arco](http://www.arco.co.uk/ ) for an example. They have some anchor links at the bottom of the home page employing some style that is gathered from "adverts.css". These aren't what i'd consider ads and if anything the issue is with their own naming conventions and not Brave. However I thought it would be worth pointing it out. The issue is created when Brave blocks the entire CSS file and the styling then breaks on a webpage. In this case, removing the following code that makes the page complete - 

`#md-container a {
    display: inline-block;
}`

2) On-site related ads eg. New movie banners like on [Showcase](http://www.showcasecinemas.co.uk/) . As you can see in Brave the banners for new upcoming movies is presented as a 404. Typically this kind of ad I would deem acceptable. I know someone posted about how certain sites can be added to a "safe" ad domain list however surely this is a very tedious process and a better solution would be to have a way to circumvent the blocking of this type of ad. I'm not really sure of a solution on this use-case to be honest but also thought it was worth mentioning. 

These are both not overly pressing issues and may not be for Brave to fix but for the companies themselves or vice versa. But realistically I will need to perform full-site investigations individually to determine who is most affected when navigating to their site via Brave. 

Thanks,

**Comment by luixxiul** [comment]
How do you think, @diracdeltas ?

**Comment by diracdeltas** [comment]
re: 1, adverts.css should not be blocked on Arco because it's 1st party. this might be a regression; i'll look into it.

re: 2, looks like the same thing is going on. the banner ad is first-party and should not be blocked.

thanks
