### ISSUE TITLE
URL bar navigates to autocomplete suggestion even after manually changing it

### ISSUE THREAD

**Issue by asmiller** [brave/browser-laptop#5622]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**

Once Brave visits a URL, when you later type a URL that is a prefix of the previously visited URL, Brave autocompletes it to the previous URL. But if you manually delete the autocompletion and press enter, Brave changes it back to the previously autocompleted URL before beginning navigation, so you cannot visit the URL you intended.

**Expected behavior:**

The URL bar should autocomplete to the previously visited URL, but should not re-autocomplete after the autocompletion has been manually deleted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OSX

- Brave Version:
0.12.8

- Steps to reproduce:
    1. Visit `https://github.com/brave/browser-laptop/issues/123456` in Brave
    2. Open a new tab and type (or copy/paste) `https://github.com/brave/browser-laptop/issues/123` into URL bar. 
    3. Delete the autocompleted "456" at the end.
    4. Press enter to start navigation. Brave will load `https://github.com/brave/browser-laptop/issues/123456` instead of the URL in the bar.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
still an issue with 0.12.9 which was just released?

**Comment by asmiller** [comment]
It is no longer occurring for me in 0.12.9. Marking as closed.
