### ISSUE TITLE
add windows specific font CSS for URL text and tab text

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5624]
I found some changes needed to improve legibility and sync the styles between mac and windows.

With the changes below, we will have a match between OSs in the URL and Tab text.

![image](https://cloud.githubusercontent.com/assets/13509546/20289876/4a82ec22-aa91-11e6-989e-e224d6d5110d.png)

(note: these are for WINDOWS CSS only)

## URL

- increase font-weight to 500
- move up 1 px by reducing top margin

![image](https://cloud.githubusercontent.com/assets/13509546/20289686/0a6fe8fc-aa90-11e6-89ff-81588f08a790.png)

**_update_**: this was fixed with https://github.com/brave/browser-laptop/pull/6848

## tab font
- change font weight to 500
- change font size to 12px
- change height to 18px
- change color to match URL color

![image](https://cloud.githubusercontent.com/assets/13509546/20289749/4da9be72-aa90-11e6-8948-7df86e9acf5c.png)

![image](https://cloud.githubusercontent.com/assets/13509546/20289763/6b373e6a-aa90-11e6-89e3-e756fcecc1cd.png)

### URL bar
1. Open the browser on Windows
2. Make sure the URL bar looks like the mockup provided by @bradleyrichter
3. Open https://www.apple.com
4. Make sure the margin exists between the lock icon and the URL
5. Open http://apple.com (not HTTPS)
6. Make sure the same margin exists between the unlock icon and the URL
7. Input ":g" on the URL bar
8. Make sure the same margin exists between the Google icon and the search queries

**Comment by srirambv** [comment]
@bradleyrichter +1 from [support ](https://linkbubble.zendesk.com/agent/tickets/6769)on Windows fonts being blurry compared to Chrome

**Comment by srirambv** [comment]
URL:
Font is still set at 400 and not 500, margin is up by 1px
![image](https://cloud.githubusercontent.com/assets/17010094/21264454/4c40f5b0-c394-11e6-907a-3eeaf3b9e0b6.png)

Tab
Font weight is up to 500
Font size is up to 12px
Height changed to 18px
Tab color is not inherited from `div.tab.active`, is set to black 
![image](https://cloud.githubusercontent.com/assets/17010094/21264609/f103d73e-c394-11e6-8647-649f59db483e.png)

**Comment by luixxiul** [comment]
@srirambv See: #6149 /cc: @bradleyrichter

**Comment by luixxiul** [comment]
Test plan: make sure that UI looks like the mockup image above https://github.com/brave/browser-laptop/issues/5624#issue-189276527

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/blame/2a78248d7b3e8611d251c2ef697f309f26d3a7c3/less/navigationBar.less#L40

The needs to be `.urlbarForm input` by redoing #5752.

It is needed by this line https://github.com/brave/browser-laptop/blame/2a78248d7b3e8611d251c2ef697f309f26d3a7c3/less/navigationBar.less#L813 of my commit: https://github.com/brave/browser-laptop/commit/19360c107c21d4693b782169ec5d583e31767261

- [ ] increase font-weight to 500
- [ ] move up 1 px by reducing top margin

**Comment by luixxiul** [comment]
I reopened for the next milestone 0.13.1

**Comment by luixxiul** [comment]
By setting `font-weight: 500` and `margin: -1px 0 0 3px` (as `position: relative` is inherited) correctly you will get this:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22181189/ee0b87aa-e0c9-11e6-96d9-857808bd1fbb.png)

By replacing the margin with `margin: -1px 0 0 0` you will get this:

![0px](https://cloud.githubusercontent.com/assets/3362943/22181224/af50e84c-e0ca-11e6-97ee-d3cc31e54475.gif)

I prefer the latter. what do you think @bradleyrichter ?

**Comment by bradleyrichter** [comment]
@luixxiul looks good!

**Comment by luixxiul** [comment]
@bradleyrichter OK I'll create a PR later ..

**Comment by luixxiul** [comment]
@bsclifton would you mind taking the font color issue?

https://github.com/brave/browser-laptop/blob/4a907a8f2a3fa79cef8f32d0695ce16246183d46/js/components/tab.js#L158-L167

**Comment by bsclifton** [comment]
@luixxiul now that https://github.com/brave/browser-laptop/pull/6848 is accepted, what's left?

**Comment by bsclifton** [comment]
The remainder of the work has already been completed by @cezaraugusto (great job!) 🎉 

The weight, pulling into Aphrodite, and more was done with https://github.com/brave/browser-laptop/pull/6900/files#diff-400b4094e3a5aaea84160dcc1483b3c2R250

And then the font size was addressed for all OSes with https://github.com/brave/browser-laptop/pull/7316
