### ISSUE TITLE
Decimal cannot be searched on the URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5627]
**Describe the issue you encountered:** Decimal cannot be searched on the URL bar

**Expected behavior:** It should be able to be searched

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8

- Steps to reproduce:
    1. Copy this: ``3.2min``
    2. Paste it on the URL bar
    3. Hit <kbd>enter</kbd>

- Any related issues: #4761

**Comment by Liunkae** [comment]
Possibly related to #5083

**Comment by luixxiul** [comment]
duping to #3317
