### ISSUE TITLE
bookmark should appear soon after being added on about:bookmarks

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5628]
**Describe the issue you encountered:** Bookmark manager needs reopening to confirm that a bookmark was correctly added there. I noticed it when I was checking #5445 was merged properly

**Expected behavior:** bookmarks should appear soon after being added on about:bookmarks

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.9 RC1

- Steps to reproduce:
    1. Open about:bookmarks
    2. Bookmark https://clifton.io by clicking the star icon on the table
    3. Nothing seems to have been added
    4. Close the bookmarks manager
    5. Reopen it
    6. See the most below line

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I cannot reproduce it. There could be a race condition.

**Comment by NejcZdovc** [comment]
I think this is fixed already.
