### ISSUE TITLE
Follow-up to #5063 (URL does not appear on the URL bar)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5629]
**Describe the issue you encountered:**

  1. Open any URL
  2. Click on the URL bar to select the URL
  3. Right Click -> Cut
  4. Click elsewhere on the browser, and make sure that URL is not pasted back in the URL bar
  5. Paste and go in the same tab -> No URL is displayed there

Going back and forward shows the URL.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): 

- Brave Version: 0.12.9 RC1

- Any related issues: #5063

**Comment by bbondy** [comment]
Moving to 0.12.10

**Comment by bbondy** [comment]
Could you explain what to do after step 4.  You say paste but at that point the focus is on the webview. Do I click back in the urlbar at that point first?  When you say "and go in the same tab" did you go to a different tab in between?

Then you say "Going back and forward shows the URL." Is that an expected result or an error?

Ideally it will be in the format:
Steps to reproduce:
1. X
2. Y
...

Actual results:
describe what happens after you do those steps

Expected results:
describe what you think should happen instead

**Comment by luixxiul** [comment]
I cannot reproduce the issue

The issue seems to have been fixed

**Comment by luixxiul** [comment]
No it is still reproducible.

4 Click elsewhere on the browser, and make sure that URL is not pasted back in the URL bar
5 click the url bar
6 "Paste and go" from the context menu
