### ISSUE TITLE
Linux doesn't show AM/PM with English locale

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5631]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Linux doesn't show AM/PM with English locale

**Expected behavior:**
Should show AM/PM with English locale

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Ubuntu 16.04 LTS

- Brave Version:
0.12.9 RC1

- Steps to reproduce:
    1. Do a fresh install
    2. Open a new tab
    3. Time doesn't have AM/PM 

- Screenshot if needed:
![linux](https://cloud.githubusercontent.com/assets/17010094/20303941/af8cb7a8-ab25-11e6-95c2-c5def0eb9406.PNG)

- Any related issues:
#5520

**Comment by srirambv** [comment]
cc: @cezaraugusto @bsclifton

**Comment by bbondy** [comment]
Moving to 0.12.10

**Comment by bbondy** [comment]
Actually just moved to contributor backlog

**Comment by Liunkae** [comment]
Works for me with Brave 0.13.0 on Linux Ubuntu 16.04:
![image](https://cloud.githubusercontent.com/assets/19424103/22386262/ee9d9606-e49b-11e6-9e28-4cc50fbfd17b.png)

**Comment by Liunkae** [comment]
The problem appears to be fixed. Closing.
