### ISSUE TITLE
Bookmark icon is not properly aligned with URL Bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5632]
![url](https://cloud.githubusercontent.com/assets/17010094/20305065/80e55e90-ab2b-11e6-8cab-b39691ecdf3c.png)

cc: @jkup @bradleyrichter

**Comment by jkup** [comment]
Is this on master? And on Linux? I can't repro on my mac

**Comment by srirambv** [comment]
This is on the RC1 build and Ubuntu

**Comment by bbondy** [comment]
moving to 0.12.10

**Comment by bbondy** [comment]
Would love a fix and will put back in the milestone it's done in but want to avoid more pixel bumping.

**Comment by bsclifton** [comment]
@jkup this might be a good use-case for demo-ing a rev 1 of a "browser button" or similar type of Aphrodite control. Something simple that centers an SVG in the control.

Ultimately, this control could also be used for stop/reload and back/forward buttons (but without borders)

**Comment by luixxiul** [comment]
I think I found a solution which depends on https://github.com/brave/browser-laptop/pull/5737/commits/214ce2d8a2e19f1948cc7a4de4c4ae68c8b245da of #5737. I'm working on it.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5739#issue-190493359
