### ISSUE TITLE
About Brave doesn't show details

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5633]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
About Brave doesn't show details

**Expected behavior:**
Should show the details

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.12.9 RC1

- Steps to reproduce:
    1. Do a clean install of 0.12.9 RC1 on Ubuntu 16.04
    2. Open about:brave
    3. Shows empty table 

- Screenshot if needed:
![screenshot from 2016-11-15 12-34-31](https://cloud.githubusercontent.com/assets/17010094/20305974/193cc206-ab30-11e6-9c85-96ed2174fd23.png)

- Any related issues:
cc: @bbondy

**Comment by bbondy** [comment]
I just tried and it shows, can you give me steps to reproduce?

**Comment by srirambv** [comment]
The first install was on a snapshot on the VM where no Brave install was done so was ideally the first install on the VM. After creating a new session still didn't show. Creating a second session by moving the ./config folder the details is shown. Marking the issue as needs investigation.

**Comment by ericlaw1979** [comment]
I repro this on a clean Windows 10 installation of the latest build.

**Comment by jonathansampson** [comment]
Following @ericlaw1979's direction, I reproduced after the following steps:

1. Uninstall Brave
2. Delete Roaming/Local folders
3. Install Brave
4. View about:brave

![image](https://cloud.githubusercontent.com/assets/815158/20362930/1439cca0-abf2-11e6-9f3a-99b9818113ba.png)
