### ISSUE TITLE
about:newtab appears on the top sites list

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5638]
**Describe the issue you encountered:** about:newtab appears on the top sites list

**Expected behavior:** about pages should be excluded from the top sites list

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues:

**Comment by bbondy** [comment]
@luixxiul which top site list do you mean? Do you mean urlbar suggestions or the top sites on the new tab page? Could you give steps to reproduce please?

**Comment by bbondy** [comment]
Moving this to 0.12.11 I don't see how to repro, I opened a new tab, and then another new tab, but no tile is shown on the about:newtab page for about:newtab.

**Comment by luixxiul** [comment]
I meant one on the new tab page.

**Comment by cezaraugusto** [comment]
Reproduced after visiting twice, then bookmarking, about:history page. It shows on topSites grid.

**Comment by luixxiul** [comment]
Test plan specified here: https://github.com/brave/browser-laptop/pull/5728#issue-190405281
