### ISSUE TITLE
Session tabs grouped by color.

### ISSUE THREAD

**Issue by aniketd** [brave/browser-laptop#5643]
**Did you search for similar issues before submitting this one?**
Yes, using the issues search. Did not find similar issues.
**Describe the issue you encountered:**
It is unclear what a new session tab is exactly. If I have 3 gmail accounts, one personal, two for work for multiple roles at work, and each having its own associated twitter, facebook, google plus, invisionapp, accounts, etc., how do I, when I start a new tab, choose between the sessions to share cookies and autofills with, and how do I, in one glance over the tabs, know which tab belongs to which profile of mine? A similar feature is provided by chrome, where multiple windows are spawned for each profile, but I like this single window, multiple tabs, all grouped by profiles, much better, as I feel that switching between windows is more involved then selecting from available tabs.
**Expected behavior:**
the `new session tab` from the context menu should, on hover, show yet another list of sessions/profiles + one `new session` option to choose from for the tab to belong to. For new sessions/profiles one should be shown the option to choose the color for the 'human bust' icon that adorns session tabs. all future tabs belonging to the same session/profile will have the same color. this way multiple profiles can be maintained for one user, for separate history, autofill data and cookies.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Archlinux
- Brave Version:
Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev
- Steps to reproduce:
    1. open context menu on right top corner
    2. click on new session tab
    3. you have a new session tab with the 'human bust' icon adorning it.

- Screenshot if needed:

- Any related issues:

Note: This may be regarded as a feature enhancement request.

**Comment by Liunkae** [comment]
Related issue: #5388 (create about:sessions for session-management)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/different-colors-for-different-new-sessions-tabs/9489?u=eljuno

**Comment by eljuno** [comment]
+1 from community about ability to set color for session tab https://community.brave.com/t/session-tabs-names-and-color/11974?u=eljuno

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/34
