### ISSUE TITLE
about:newtab should offer 24-hour format option

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5647]
Support a 24-hour format option.

> Chip @2bithacker
@brave it'd be nice if it respected my system time prefs though. much prefer 24h time

and

> Chip @2bithacker
@BraveSampson ideally, it'd be nice to pull the format from SysPref's Language & Region>Advanced>Times

Source: https://twitter.com/2bithacker/status/798641388086763520

**Comment by anasant** [comment]
Was trying to add this but would only get a completely blank newtab page after setting up my dev env. Anything I might be missing in the dev setup process? :thinking: 

Also sent you an email about it @jonathansampson!

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/how-to-change-time-format/4665)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/7781; we should be respecting the preferences of the user's locale settings
