### ISSUE TITLE
JavaScript User Prompt causes tab to become unresponsive.

### ISSUE THREAD

**Issue by estradanic** [brave/browser-laptop#5648]
When I attempt to leave a page that would typically have a "Are you sure you want to leave?" Javascript dialogue, the browser doesn't show the dialogue and the tab becomes completely unresponsive. I have to close the tab and open another one to get to a different page. I have tried this on two separate pages that have similar behavior and the same exact thing happened.

I am running 0.12.9 on Ubuntu Linux.

**Comment by Liunkae** [comment]
I think this is a case of issue #94 ("prompt is not supported currently"). The problem is currently planned to be fixed by version 1.1.0.

**Comment by estradanic** [comment]
Looks like it. Thank you. I'll close this up :+1:
