### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by BigHank2016** [brave/browser-laptop#5650]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by BigHank2016** [comment]
no sound. could not find a solution

**Comment by bsclifton** [comment]
@BigHank2016 do you have more information? Are you on Windows, Linux, or Mac?

Do other browsers work OK? What are you specifically trying to use which is not playing audio?

**Comment by BigHank2016** [comment]
Windows 10, trying to use Brave for YouTube.

**Comment by Liunkae** [comment]
@BigHank2016 Does it work in other browsers? Also, are you sure the sound is not muted on the page or tab? Make sure the tab looks like this:
![image](https://cloud.githubusercontent.com/assets/19424103/20333193/9015e57e-ab76-11e6-82a3-ff4b4e3b762b.png)

**Comment by josiah-keller** [comment]
Yes, definitely double-check the tab icon.  It's easy to accidentally mute the tab by clicking the icon when you're just trying to switch tabs.

**Comment by Alex0007** [comment]
Linux 
v0.13.5

It was no sound too, but app restart helped

**Comment by luixxiul** [comment]
Closing as fixed

**Comment by caffeine-** [comment]
I have no sound in brave but do in all other browsers including chrome & chromium. 
Linux Mint 18 Cinnamon 64-bit
Cinnamon V 3.0.7
