### ISSUE TITLE
Disabled script shield in private tab is enabled again when switching to normal tab and back to private tab

### ISSUE THREAD

**Issue by aironou** [brave/browser-laptop#5651]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Disabled scripts shield in private tab is enabled again when switched to a normal tab and switched back to same private tab.
If you open Brave shields in original private tab, scripts shield keeps disabled, but scripts are blocked.

**Expected behavior:**
Disabled scripts shield in private tab should not be enabled again just switching to normal tabs.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch Linux (64 bits)

- Brave Version:
0.12.8

- Steps to reproduce:
    1. open a private tab
    2. access http://aironou.com.br
    3. if scripts shield is enabled, disable it (on reload, a alert should appears)
    4. open a normal tab
    5. goes back to same private tab
    6. reload page (on reload, this time, no alerts appears)

- Screenshot if needed:

- Any related issues:

P.S.: sorry for my English, it isn't my native language.

**Comment by alexwykoff** [comment]
@flamsmark is this really must-fix & blocking for Tor?

**Comment by flamsmark** [comment]
@alexwykoff No, it's definitely not blocking.
