### ISSUE TITLE
prefs: make empty home page address = about:blank

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5652]
![image](https://cloud.githubusercontent.com/assets/13509546/20327545/5c361fd2-ab42-11e6-896e-4a56ef8e0310.png)

Currently the above combination make a new-tab page and we need an easier way for users to return to "white-space"' if they prefer.

**Comment by luixxiul** [comment]
I would prefer the blank tab option than this because it is more explicit and you have to back up the URL for future use.

**Comment by luixxiul** [comment]
Already we got a comment that the blank tab option was gone: https://github.com/brave/browser-laptop/issues/2106#issuecomment-260951611

**Comment by bsclifton** [comment]
@luixxiul is there already an issue for adding about:blank as an option? I'd be more than happy to add it :smile: If you don't mind, please find or create an issue and assign to me.  Thanks! :smile:

**Comment by luixxiul** [comment]
My bad, I thought there must have been the option, but the new tab was just the blank one in previous versions :-(

**Comment by luixxiul** [comment]
Done! -> #5682

**Comment by bsclifton** [comment]
@luixxiul I did temporarily add about:blank as an option :smile: but I had backed out because I also set it as the default (so that new users wouldn't see the new about:newtab until they are ready). Unfortunately, I forgot that about:blank does not set the focus to the URL bar

**Comment by 0xMF** [comment]
The workaround about:blank does not work as the previous Brave version because prompt does not return to the address bar.  

I would not mind a background image if I had a way to keep an image I liked fixed instead of a new image appearing with every Empty Tab, which can be distracting. Still, Empty Tab with address bar retaining prompt as an option please.

**Comment by Liunkae** [comment]
Note: This functionality will be superseded by the "Blank Page" option in 0.13.0. (See issue #5682 and PR #5690)
