### ISSUE TITLE
New tab as home page set to about:blank doesn't focus URL bar

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#5653]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When you set new tab to home page, and home page to about:blank, new tabs will start with the document body selected rather than the URL bar. So to navigate somewhere you manually need to click the URL bar.

**Expected behavior:**
New tabs opening to about:blank should focus the URL bar.

- Platform (Win7, 8, 10? macOS? Linux distro?): Mac OS

- Brave Version: 0.12.9

- Steps to reproduce:
    1. Set new tab page to Home page
    2. Set Home page to about:blank
    3. Open a new tab

![screen shot 2016-11-15 at 14 58 15](https://cloud.githubusercontent.com/assets/521861/20327883/fe8bd1ae-ab43-11e6-983e-771aba95ed22.png)
![screen shot 2016-11-15 at 14 58 21](https://cloud.githubusercontent.com/assets/521861/20327886/ffcc06d8-ab43-11e6-9d38-eb19b3140721.png)

related kinda: #5652

**Comment by bsclifton** [comment]
We'll be adding a new "Blank page" option with https://github.com/brave/browser-laptop/pull/5690 instead of changing the behavior of about:blank

I'm going to mark this as `won't fix`, but welcome you to review the PR :smile:
