### ISSUE TITLE
New tab page shortcut buttons link tooltips are not user friendly

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5657]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Whenever I hover over a shortcut button in the new tab page, it shows a long and confusing link tooltip. It shows `chrome-extension://<many random letters>/about:<page>.html`, which appears to be some sort of internal link structure. This does not seem very user friendly.

The relevant source code is in `browser-laptop/js/about/newTabComponents/footerInfo.js`

**Expected behavior:**
The tooltip should either show the actual page link (e.g. "about:preferences") or nothing at all.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Found on macOS 10.12.x

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Open Brave and the new tab page.
    2. Hover over one of the shortcut buttons (e.g. preferences) in the bottom right corner.
    3. Look at the tooltip in the bottom left corner.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/20330376/010e8924-ab64-11e6-9ac6-9def76899171.png)

- Any related issues:
None.

**Comment by Liunkae** [comment]
Possibly similar to #5725 (urlbar is showing chrome-extension:// prefix for PDFs).

**Comment by bradleyrichter** [comment]
@cezaraugusto Any easy fixes for this?

**Comment by bsclifton** [comment]
I think this is going to be more complex than what @diracdeltas did with the above PDF change

We'd need to intercept the chrome://{extensionId} URL and then translate it to the proper about: page.  What do you think, @diracdeltas?

**Comment by cezaraugusto** [comment]
@bradleyrichter I think it's going to be a little more complicated than expected but doable for our 1.0.0 release imo.
