### ISSUE TITLE
Let site owners specify details of thumbnails on top sites list on about:newtab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5658]
Let site owners specify details of thumbnails on top sites list on about:newtab and prioritize them over the default favicon settings of the site.

````
<meta name="brave-TopSitesImage" content="/example.svg">
<meta name="brave-TopSitesGridColor" content="#fff">
````

This would make it possible to display nicer thumbnails than blurred ones based on 16x16 favicons like this:
<img width="85" alt="screenshot 2016-11-16 10 30 42" src="https://cloud.githubusercontent.com/assets/3362943/20331277/ca9b48b2-abe7-11e6-8296-a9ab49762e5e.png">

It could also be a solution of #5455.

**Comment by luixxiul** [comment]
I think it's an idea but I'm not sure how many owners care about the browser and would add those two lines.

**Comment by bbondy** [comment]
I think Windows 8 and above had meta tags to specify this, maybe we could just re-use those meta tags?
