### ISSUE TITLE
Bar appears on about pages

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5661]
**Describe the issue you encountered:** the blue bar appears on about pages

![bluebar](https://cloud.githubusercontent.com/assets/3362943/20331835/5035a9ec-abeb-11e6-9a8f-7a07e7522405.gif)

**Expected behavior:** the bar should not appear

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open about:about
    2. Open about:adblock from the list

- Any related issues:

**Comment by luixxiul** [comment]
Please set a milestone if necessary.

**Comment by Liunkae** [comment]
The blue bar is the (macOS-only) focus ring around the page's content.

**Comment by luixxiul** [comment]
On Windows 10 the golden thin bar is displayed: 
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20333183/403c22ec-abf4-11e6-9c58-3ff5b3a923e5.png)

**Comment by Liunkae** [comment]
So it's a focus ring that appears on multiple platforms, with different appearances.

**Comment by bbondy** [comment]
@Liunkae @luixxiul I've wondered what that was for so long but didn't have a good way to reproduce. And I didn't realize it was the focus ring. Great find!
