### ISSUE TITLE
Add better resolution favicon for new tab topSites

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#5663]
**Did you search for similar issues before submitting this one?**
yes 

**Describe the issue you encountered:**
Some websites (such as Youtube) doesn't display a good quality favicon by default, and appear pixelated on new tab's topSites.

Per Brad's request here (#3001) we should:

> build high-res favicon collector mechanism, pulled from page header at domain root page

**Expected behavior:**
TopSites should have an aesthetically pleasing favicon.

## My suggestion here: 

I was thinking on getting images following Apple > MS conventions on links/meta icon declarations,  then search for a given pattern for high res icons (maybe look for `size` attr, or maybe a given number). If all else fails we fallback to default `*.ico` images we already have. Like:

**1. Search for Apple name convention**
`<link rel="apple-touch-icon" href="http://example.com/apple-touch-icon.png">`

**2. Search for MS name convention (tile pictures)**
`<meta name="msapplication-TileImage" content="http://example.com/mstile-72x72.png">`

**3. Search for any name convention for high-res icons (find for NxN occurencies or `sizes` attr)**
`<link type="image/png" rel="icon" href="http://example.com/something-144x144.png"  sizes="144x144">`

**4. Fallback for default `*.ico` images**

**Comment by Liunkae** [comment]
Related: #5658

**Comment by luixxiul** [comment]
I like the suggestion, still the background color should also be configurable to avoid the issue I mentioned on #5658

**Comment by bbondy** [comment]
Could I also ask that as part o this you re-use the favicon always for the sites that have them, that way they won't get overwritten at some point.
