### ISSUE TITLE
transition of every button in #navigator

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5664]
**Describe the issue you encountered:** There is no transition of the reload button. While the URL bar is shown smoothly, the reload button instantly without transition.

![reload](https://cloud.githubusercontent.com/assets/3362943/20333016/1e188f1c-abf3-11e6-9424-d69b6e1dd97b.gif)

**Expected behavior:** The styling should be consistent.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.9

- Any related issues:

CC @bradleyrichter @cezaraugusto

**Comment by Liunkae** [comment]
Same issue with the home button (if enabled).

**Comment by Liunkae** [comment]
#5667 fixes the problem for me.

**Comment by luixxiul** [comment]
It stopped working because buttons have been changed from `<span>` to `<button>`. I will push a fix.

**Comment by bbondy** [comment]
nice find @luixxiul

**Comment by luixxiul** [comment]
Test Plan:
1. Open about:preferences
2. Disable/enable "Always show the URL bar" option
