### ISSUE TITLE
Hover background of bookmark bar items is hard to see

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5665]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When hovering over an item in the bookmarks bar, the change in background color of the item is very hard to notice.

**Expected behavior:**
The background color should be more noticeable (have better contrast).

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Open Brave and add an item to the bookmarks bar (if necessary).
    2. Move your mouse pointer over the item (hover).
    3. Notice the very slight change in background color of the bookmark item.

- Screenshot if needed:
Normal:
![image](https://cloud.githubusercontent.com/assets/19424103/20333845/36faa268-ab7b-11e6-9b9d-8b863ff961b7.png)
Hover:
![image](https://cloud.githubusercontent.com/assets/19424103/20333856/42967c0a-ab7b-11e6-8b8e-fe1e9bdeb53e.png)

- Any related issues:
None.

@bradleyrichter Thoughts? Personally, I like the hover background of the toolbar buttons (back, forward, refresh, etc.).

**Comment by Liunkae** [comment]
#5668 is my suggestion. As I said in the PR, feel free to close it if a different appearance is desired.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5668#issue-189581271
