### ISSUE TITLE
Counters should be selectable on about:newtab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5666]
The counters should be selectable on about:newtab to make it easier to share them on twitter/facebook :-)

- Brave Version: 0.12.9

- Any related issues:

**Comment by bsclifton** [comment]
This would be my fault 😄 What do you think, @bradleyrichter ? I had made them non-selectable to appear more like an app... but sharing is great 😄

**Comment by bradleyrichter** [comment]
Sounds reasonable. Share away!

**Comment by srirambv** [comment]
Dupe of #5452

**Comment by bsclifton** [comment]
@srirambv seems a little different- this is for copy/paste purposes
