### ISSUE TITLE
Slight delay until URL of about pages is replaced with the title should be removed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5669]
**Describe the issue you encountered:** There is a slight delay until the about pages URL on the tab is replaced with the title.

**Expected behavior:** The delay should be removed.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version: 0.12.9

- Steps to reproduce:
    1. Open `about:newtab`
    2. Look at the title of the tab
    3. There would be a slight delay until `about:newtab` was replaced with `New Tab`

- Any related issues:

**Comment by luixxiul** [comment]
@cezaraugusto should this issue be closed with your recent PR as well?

**Comment by cezaraugusto** [comment]
no, but we could add an animation w/ a small delay that could prevent that. I added similar styles for tab icons should not be hard to implement. let me know if you're interested and need a hand. Adding this is not hard but several test cases
