### ISSUE TITLE
Suggestion: page tiling

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5674]
Copied from https://github.com/brave/browser-laptop/issues/613#issue-131412931:

> Page tiling= Combine 1-4 pages to a group and display them at once on the screen

**Comment by luixxiul** [comment]
I'm going to close this in favor of this topic on the community: 

https://community.brave.com/t/native-support-for-tiled-tabs/9929

Let's discuss the suggestion there 😄
