### ISSUE TITLE
New private tab does not get the title replaced with "New Tab" 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5675]
**Describe the issue you encountered:** New private tab does not get the title replaced with "New Tab".

<img width="195" alt="screenshot 2016-11-16 15 56 44" src="https://cloud.githubusercontent.com/assets/3362943/20337587/5145e552-ac15-11e6-987c-1b8195131fe1.png">

**Expected behavior:** "New Tab" / "New Private Tab"

<img width="189" alt="screenshot 2016-11-16 15 58 38" src="https://cloud.githubusercontent.com/assets/3362943/20337634/9237da02-ac15-11e6-873a-6db94f765f40.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open a new private tab

- Any related issues:

**Comment by bsclifton** [comment]
this is a dupe for sure- let me find it...

**Comment by bsclifton** [comment]
Here we go: https://github.com/brave/browser-laptop/issues/1817
Closing as dupe

**Comment by bsclifton** [comment]
@luixxiul feel free to try and prioritize the original issue (see notes for history)
