### ISSUE TITLE
pinned tabs calculated as full tabs for tab set creation leading to unnecessary empty tab set

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#568]
<img width="866" alt="screen shot 2016-02-02 at 10 09 13 am" src="https://cloud.githubusercontent.com/assets/552390/12759290/156034b0-c995-11e5-80aa-2a12d336ce42.png">
If I have several pinned tabs, and several full tabs in a set, Brave seems to think I need a second tab set to fit them all when I don't. I end up with an empty tab set. Unpinning the pinned tabs shows that Brave doesn't understand pinned tabs take up less space.

**Comment by bbondy** [comment]
++ nice find.

**Comment by diracdeltas** [comment]
yep, was just about to report this
