### ISSUE TITLE
padding-left should be added to "My homepage is" input form

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5680]
**Expected behavior:** padding-left should be added to "My homepage is" input form

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Screenshot if needed:

<img width="302" alt="screenshot 2016-11-16 20 56 46" src="https://cloud.githubusercontent.com/assets/3362943/20346473/7ce5e7fa-ac3f-11e6-9716-fef3dfb575c5.png">

- Any related issues:

**Comment by Liunkae** [comment]
Looks fine in 0.12.9. Probably something in d2d7854.
