### ISSUE TITLE
Add New Search Engine

### ISSUE THREAD

**Issue by frankadomitis** [brave/browser-laptop#5681]
**Did you search for similar issues before submitting this one?**

Yes.  It appears this cannot be done. 

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

Win 10  Home Addition

- Brave Version:
0.12.9
- Steps to reproduce:
    1.
    2.
    3.
![capture](https://cloud.githubusercontent.com/assets/23479620/20352111/f254c09e-abca-11e6-925f-8730e9996d6e.PNG)

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Hello, would you please tell us what kind of issue you experience in detail? Thanks.

**Comment by frankadomitis** [comment]
when I go to the preferences page and search page, there is no way I can see to add another search engine.

**Comment by luixxiul** [comment]
That feature will be added in a future. The request has been made on #3053, so I'd like to close this in favor of it.
