### ISSUE TITLE
Warnings only visible when urlBar is visible

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5686]
The user's security is Brave's top priority. At the moment, however, users may not be aware that they are on a non-secure connection as Brave's out-of-box experience auto-hides the address-bar.

**Site appears to be harmless:**
![image](https://cloud.githubusercontent.com/assets/815158/20358204/c15389a2-abdf-11e6-818a-3b85b2f2344f.png)

**Hovering urlBar reveals a warning:**
![image](https://cloud.githubusercontent.com/assets/815158/20358232/d8499d9a-abdf-11e6-8f80-11fb5ea9ad3c.png)

Reported: https://twitter.com/ericlaw/status/798929401505140736

**Comment by Liunkae** [comment]
Duplicate of #3651.
