### ISSUE TITLE
Reopening Brave after closing it when it was maximized displays in the wrong place

### ISSUE THREAD

**Issue by mcollins451** [brave/browser-laptop#5687]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
If Brave is maximized when it is closed, then when you reopen it, it does open maximized, but it's slightly misplaced up and to the left.  See the screenshot.

**Expected behavior:**
It should open maximized and occupying the full screen in the proper place

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7

- Brave Version: 0.12.9

- Steps to reproduce:
    1.  Open Brave.
    2.  Click the maximize button.
    3.  Close Brave by clicking the X in the upper right hand corner.
    4.  Open Brave again.

- Screenshot if needed:

In the screenshot below, I have dual monitors.  Brave was maximized on the left monitor, closed, and then reopened.

![bravebug](https://cloud.githubusercontent.com/assets/21689439/20358804/32037d72-abfb-11e6-9c47-d8d20b316860.png)

- Any related issues:

**Comment by luixxiul** [comment]
Closing this in favor of #3228
