### ISSUE TITLE
thumbnail in the top sites list disappears by bookmarking the site on the new tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5689]
**Describe the issue you encountered:** thumbnail in the top sites list on `about:newtab` disappears or changes the place by bookmarking the site with the star on the thumbnail.

**Expected behavior:** The thumbnail should stay the original place

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Open the new tab
    2. Click the star on the thumbnail in the top sites list
    3. The thumbnail disappears

- Any related issues:

**Comment by bsclifton** [comment]
@cezaraugusto could you check this out?

**Comment by bbondy** [comment]
not reproducible with 1 site, could you write more exact steps @luixxiul ?

**Comment by luixxiul** [comment]
I'm not sure 100% but it seems like that you would need to have visited the pages on the same domain.

For example, if I visited `https://github.com/issues` and `https://github.com/notifications` frequently, have the former appeared on the top sites list, and bookmark it, it disappears and the latter appears instead of it.

**Comment by luixxiul** [comment]
Another example: if I bookmarked ``https://status.github.com/graphs/past_day`` from the new tab, it disappeared and ``https://status.github.com/messages`` on a different position.

**Comment by cezaraugusto** [comment]
@luixxiul is it still reproducible on master? Couldn't reproduce as well.

If you have other STR please let me know.

**Comment by luixxiul** [comment]
This is no longer reproducible.
