### ISSUE TITLE
chromium 54 upgrade

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#5691]
Current known issues:
- [x] cherry-pick recent electron commits into chromium54 branch
- [x] rebase browser-laptop into chromium54 branch
- [x] mac prebuilt @darkdh
- [x] windows build is not working @bsclifton 
- [x] windows prebuilt
- [x] linux build is not working @posix4e 
- [x] linux prebuilt
- [x] prebuilt in browser-laptop is broken without 2.0 prebuilt - comment out as workaround for now
- [x] mac - OS buttons overlap with back/forward buttons @darkdh
- [x] crash reporting is not enabled @bbondy 
- [x] updater is not enabled
- [x] some flash checks are disabled @bridiver
- [x] a new window with an empty tab is always created on startup even if there are saved windows
- [x] nativeImage.createFromDataURL is not implemented @darkdh
- [x] Restrict chrome://brave/* urls to the main window
- [x] printing api is not enabled @darkdh
- [x] widevine appears to load but netflix can't find it @bbondy 
- [x] importer not working - likely a utility client issue @darkdh 
- [ ] gpu host can't connect in Debug builds (low priority)
- [x] clone is disabled @bridiver 
- [x] webview.setUserAgent is disabled @bridiver
- [x] fix OverrideCreatePlugin @bridiver
- [x] browser-laptop tabs.create and extension tabs.create need to be updated for webview changes @bridiver
- [x] missing chromedriver @darkdh
- [x] spectron needs updated chromedriver
- [x] `require` does not work in tests
- [x] widevine is not working in packaged build @bbondy 
- [ ] respect system setting of swipe @darkdh
- [x] check zoom
- [x] check protocol handlers translateUrl @bbondy 
- [x] 1password not recognizing tab changes in 1pw mini (they are picked up when clicking on the extension action button) @bridiver
- [x] Brave password manager requests permission to store passwords in the keychain after it is disabled
- [x] Locale is not working properly @bsclifton
- [x] High DPI issues on Windows (when DPI > 100%) @bsclifton / @darkdh 
- [x] webview.executeJavaScript runs in the calling context instead of the webview context
- [x] user agent contains Brave
- [x] crash reporter is not working in renderer (mac only?)

**Comment by bridiver** [comment]
https://github.com/brave/electron/issues/95
https://github.com/brave/electron/issues/94

**Comment by alexwykoff** [comment]
Related issues:

https://github.com/brave/browser-laptop/issues/5794

**Comment by bbondy** [comment]
Closing this in favour of more specific bugs.
https://github.com/brave/browser-laptop/issues/6394

**Comment by luixxiul** [comment]
I added `QA/no qa needed` based on the conversation above.
