### ISSUE TITLE
Provide an option to take snapshot of newtab for sharing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5693]
Provide an option to take snapshot of newtab for sharing. #5676 introduces click and drag to select stats to share, providing a way to take a snapshot of the new tab with the stats and copy to clipboard would be a nice addition.

Right click on image shows Copy image, this can be a good reference 

cc: @bsclifton  @cezaraugusto

**Comment by luixxiul** [comment]
I feel this is too much, fearing to let users think the team is too desperate to make up an public image that "we are 100% committed to users".

**Comment by bsclifton** [comment]
This can simply be captured with Snipping Tool (Windows) or the Shift+Cmd+4 shortcut on macOS
