### ISSUE TITLE
Insecure connection on https://github.com

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5708]
**Describe the issue you encountered:**
<img width="495" alt="screenshot 2016-11-17 16 58 23" src="https://cloud.githubusercontent.com/assets/3362943/20380713/170a5bde-ace7-11e6-9ffc-f143d612b6a5.png">

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch, packaged build

- Steps to reproduce:
    1. Clear your brave folder
    2. ``CHANNEL=dev npm run build-package``
    3. Open the browser
    4. Open https://github.com/brave/browser-laptop/issues/new
    4. Click the icon on the URL bar

**Comment by srirambv** [comment]
I don't see the same error on Windows with master branch
![image](https://cloud.githubusercontent.com/assets/17010094/20384425/aef37f16-acab-11e6-8817-3a74b448e8c9.png)

**Comment by luixxiul** [comment]
Reproduced by clearing data folder.

**Comment by diracdeltas** [comment]
i can't repro this on master after clearing the ~/Library/Application Support/brave-development folder

**Comment by luixxiul** [comment]
Fixed by rf -rm ~/.electron, rf -rm node_modules, npm i, and CHANNEL=dev npm run build-package. Even after restoring the brave profile folder, I cannot reproduce the issue, so I believe this was related with the electron (aka muon?) or something. @bbondy please correct me if I am wrong. thanks.

**Comment by luixxiul** [comment]
@bbondy also if I'm correct, would you please close this issue? If I am wrong, let's keep this opened.

**Comment by bsclifton** [comment]
@luixxiul that would make sense; I know @diracdeltas recent changes required updates to muon

**Comment by luixxiul** [comment]
I have heard from @bbondy we don't need to do `rf -rm ~/.electron` anymore. Is it my misunderstaning?

**Comment by bbondy** [comment]
Correct ~/.electron was only needed before when we re-used the same electron version number for different code to stay in sync with Electron upstream.  That's no longer a goal of ours and we've long since diverged in version numbers.  No harm if you clear it, it clears up some disk space, but it's not needed to fix anything, so it's a no-op.
