### ISSUE TITLE
Make maximize test better

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#571]
Currently the first time run of a window puts the window to the full size. 
This makes the maximize test pointless, we need to first resize the window before the maximize.

From BrianJ:

> This needs an update to the maximize test. It will pass, but it's kind of meaningless to pass if the window is already maximized

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/9a98903a037104f0b031d681db6920b2c7deff15
