### ISSUE TITLE
Flash not working needs left padding to align with Pepper flash notification

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5710]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Flash not working needs left padding to align with Pepper flash notification

**Expected behavior:**
Text should be align properly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
Master branch

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20382675/c7498f12-aca4-11e6-9b0c-ec6f49d47a73.png)

- Any related issues:

**Comment by luixxiul** [comment]
Fixed with #6138
