### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by BattyB** [brave/browser-laptop#5714]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

Only on the latest update..
Bookmarks toolbar arrow at right does not produce dropdown menu.
Sub folders are not accessable from toolbar

Unable to type in the web address  on the top bar.  defaults to existing on pressing enter.   All versions

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): 

OS 10.10.5

- Brave Version:
Brave: 0.8.3
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 6.0.0-pre
Update channel: dev

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
Hi @BattyB! Your version appears to be several months out-of-date. 😉  (The current version is 0.12.9)

Could you please try updating Brave? Open Brave and select Menu > Help > Check for Updates. If this doesn't work, please download the latest update from [brave.com](https://www.brave.com).
