### ISSUE TITLE
UI issues in Shields menu on master

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5715]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
1. Ad Control drop down doesn't contain border and is bigger in size compared to  Cookie Control drop down
2. Fingerprint Protection is not in same line

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
master branch

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20392460/da40f1de-accf-11e6-882b-037ab9000df7.png)

- Any related issues:

**Comment by bradleyrichter** [comment]
I won't sleep until this is fixed!  : )

**Comment by luixxiul** [comment]
> 1 Ad Control drop down doesn't contain border and is bigger in size compared to Cookie Control drop down

https://github.com/brave/browser-laptop/blob/master/js/components/braveryPanel.js#L290 
https://github.com/brave/browser-laptop/blob/master/js/components/braveryPanel.js#L303
className="form-control" which was introduced with https://github.com/brave/browser-laptop/commit/72174bbbb38032babb805e4c1f2e42d2b7e0f71a

> 2 Fingerprint Protection is not in same line

See https://github.com/brave/browser-laptop/pull/1966, I was not sure of a better solution

**Comment by luixxiul** [comment]
>> 2 Fingerprint Protection is not in same line
>
> See #1966, I was not sure of a better solution

I think the panel of the brave-android version could be one here: list 4 switches vertically rather than place them in a table.

**Comment by srirambv** [comment]
Works fine for English, but still a problem for other languages. (#5726)
Portugese (Brazil)
![image](https://cloud.githubusercontent.com/assets/17010094/20477502/ccb240d0-afcd-11e6-87ab-c00f9ec35f06.png)


PS: The drop down text is not of the same font-size as the rest of them

**Comment by luixxiul** [comment]
Here's my idea on a compact bravery menu, which would be l10n-friendly.

<img width="307" alt="screenshot 2016-11-21 3 54 42" src="https://cloud.githubusercontent.com/assets/3362943/20477700/3133544e-b01a-11e6-8997-886d75e3b541.png">

**Comment by srirambv** [comment]
Can this layout be only enabled when the text overflows in other languages or when language is changed from English to others?

@bradleyrichter just realized the reload icon is not aligned with text on the current shields panel

**Comment by luixxiul** [comment]
@srirambv I think it would be possible to enable it globally via an option on the preferences page (though I am not sure how to create the option and switch the two layouts), so that we could hear feedbacks from users.

**Comment by luixxiul** [comment]
0.12.9
![clipboard02](https://cloud.githubusercontent.com/assets/3362943/20483467/84d3846e-b035-11e6-9749-5128afeb8a30.png)

0.12.10 RC1
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20483466/84a4fc84-b035-11e6-876c-e08102f345aa.png)

**Comment by srirambv** [comment]
The text is getting clipped with the bigger font size in the drop down list
![image](https://cloud.githubusercontent.com/assets/17010094/20483974/e3df7678-afec-11e6-84e3-42de60fd2510.png)

**Comment by bradleyrichter** [comment]
This must be tied to the button text size? That may be fine but it should be smaller.

**Comment by luixxiul** [comment]
@bradleyrichter ``font-size: 14.5px;`` on https://github.com/brave/browser-laptop/commit/72174bbbb38032babb805e4c1f2e42d2b7e0f71a#diff-57a5fbf005ecc202d1e7e08c11f73b93R10 how small should it be?

**Comment by bradleyrichter** [comment]
13px

**Comment by alexwykoff** [comment]
Label issues covered in https://github.com/brave/browser-laptop/issues/5726

**Comment by luixxiul** [comment]
Ok done: #5772
