### ISSUE TITLE
When attempting drag-n-drop of local image to github content area, drop is ignored and opens image instead.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#572]
drag an image from your desktop to the browser window where Git normally accepts an image for upload.

result: Window locks up as image viewer with no recover possibility. Window must be closed.
expected: image is received by drop area and image is uploaded to Git issue.

**Comment by diracdeltas** [comment]
I'm not seeing this bug. is this on the latest release?

**Comment by bradleyrichter** [comment]
Bug is now fixed in latest on Mac! But drag into page container is still ignored. Let's change the title.

**Comment by diracdeltas** [comment]
for me it actually does upload the image, but it also opens it in a new tab

**Comment by diracdeltas** [comment]
appears to be fixed now?

**Comment by bbondy** [comment]
yep it is fixed.
