### ISSUE TITLE
Test assertions are broken

### ISSUE THREAD

**Issue by dcposch** [brave/browser-laptop#5722]
While adding a new unit test, I noticed that some of the existing unit tests are not actually testing anything.

For example, in `urlutilTest.js`:
```js
  describe('getScheme', function () {
    // ...
    it('localhost: for localhost', function * () {
      assert.equal(UrlUtil.getScheme('localhost://127.0.0.1'), 'localhost:')
    })
```

...if you replace 'localhost:' with 'yolo', the tests still pass!

Looks like we can fix this by removing generator functions. In other words, turning `function *` into `function`.

**Comment by dcposch** [comment]
@bbondy

**Comment by bsclifton** [comment]
Good catch :smile: That should be easy enough to update. All of the unit tests should be using regular `function`

**Comment by bbondy** [comment]
Yikes nice find, thanks for the ping @dcposch
