### ISSUE TITLE
Add Stylish

### ISSUE THREAD

**Issue by ddaza** [brave/browser-laptop#5727]
This is related to #1122

Adding [this](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe) would be awesome.

so this: 

<img width="681" alt="screen shot 2016-11-18 at 1 02 04 pm" src="https://cloud.githubusercontent.com/assets/290254/20442719/67b4af8c-ad8f-11e6-9851-625bc6b2185c.png">

can look like this: 

<img width="659" alt="screen shot 2016-11-18 at 1 02 28 pm" src="https://cloud.githubusercontent.com/assets/290254/20442725/7241f900-ad8f-11e6-9cd6-dc0e3687f97c.png">

**Comment by Liunkae** [comment]
Added to the extensions project [here](https://github.com/brave/browser-laptop/projects/1).

**Comment by 3Lies** [comment]
It would be really nice to add it !

**Comment by GalferOP** [comment]
Stylish is so good ! :) And for my eyes it's an obligation for many websites too white :o So When Brave have Stylish, i will use Brave everytime. ;)

**Comment by JoePCool14** [comment]
Any news on this? It's been several months and no word on it.

**Comment by Mimjett** [comment]
On my previous browser, most of my websites had a "dark" theme installed because the white backgrounds were too much.  I can make do with the white backgrounds, but I'd love to see Stylish added in the future.

**Comment by Antidentity** [comment]
Definitively, it should be great having stylish! The best extension ever!
Effectivement, ce serait génial d'avoir stylish! La meilleure extension qui puisse exister!

**Comment by Alexander-DeLarge** [comment]
Keep in mind that Stylish partnered with the SimilarWeb analytics company. I would hope that since Brave is Chromium-based, we'd see Stylus implemented instead or have the add-on stripped of the analytics nonsense.
https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en

https://forum.userstyles.org/discussion/53233/announcement-to-the-community

**Comment by DatrixTHLK** [comment]
I despise a white background as much as the next person, but glad this option is being explored. I won't have to strain my eyes from the harshness of white.

**Comment by stianmandarin** [comment]
+1

**Comment by matthewbahr** [comment]
+1 here as well. Stylus/Stylish whatever: We need it.

**Comment by DVSlayer42** [comment]
Same here - Stylish is awesome!

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄

**Comment by tycho01** [comment]
Hi, while Brave supports Chrome extensions now, this particular extension appears not to actually function when you try enabling any style in it in Brave... Should we perhaps reopen this issue?

**Comment by Liunkae** [comment]
@tycho01 Please open a new issue in the new repository's issue tracker: https://github.com/brave/brave-browser/issues
