### ISSUE TITLE
when using a touchscreen, long press for context menu pops up the context menu in the wrong place

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#573]
Context menus pop up far away from the long press touch point. Let me know if you are or aren't interested in touchscreen bugs at this point.

**Comment by luixxiul** [comment]
Can this be still reproduced?

**Comment by JaneSmith** [comment]
This can still be reproduced on version 0.18.22 on Windows 10. I experience poor touch usability in general with Brave.

**Comment by srirambv** [comment]
Same as https://github.com/brave/browser-laptop/issues/2686
