### ISSUE TITLE
Add a link to brave/muon on README.md

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5731]
**Describe the issue you encountered:** Even careful users cannot know at all what "muon" is and why "brave/electron" is gone, because they have never been explained anywhere as far as I can tell, for example, in CHANGELOG.md or README.md

**Expected behavior:** Let's tell users these things on README.md or a Wiki page.
1 What "muon" is
2 Who "muon" maintains
3 Where brave/electron is gone
4 Why electron/electron had been replaced with brave/electron
5 Why brave/electron was replaced with "muon"
6 Whether there is a difference among electron/electron, brave/electron and "muon"
7 Where you can find "muon"
8 Whether "muon" is opensource (=tell users it is not proprietary)

- Brave Version: 0.12.9

- Any related issues:

I think this task should be done asap, so that no rumour would appear that brave started integrating a prorietary software. *Remember it is always those who are not willing to find an answer by themselves who tend to start that kind of rumour which seems to be ridiculous...*

**Comment by luixxiul** [comment]
@bsclifton since you have updated README.md on brave/muon with [this commit](https://github.com/brave/muon/commit/f26409dacf8ab75043734183ba7f09fb6d290815), this can be closed after adding the link to the repo on README.md of this repo :-)

**Comment by luixxiul** [comment]
Including update of https://github.com/brave/browser-laptop#running-inside-of-a-development-version-of-braves-electron-fork

**Comment by willy-b** [comment]
@luixxiul thanks for proposing an update of https://github.com/brave/browser-laptop#running-inside-of-a-development-version-of-braves-electron-fork -- I got stuck on that after the build scripts in Muon were invalidated with loss of `script/build.py` which was used by `npm run build`, `npm run browser-build` and a few others

**Comment by willy-b** [comment]
The [documentation in Muon itself](https://github.com/brave/muon/blob/master/docs/development/build-instructions-linux.md#building) still suggests running `./script/build.py` which doesn't exist anymore  (https://github.com/brave/muon/issues/132):
![muon-build-instructions-buildpy](https://cloud.githubusercontent.com/assets/6969859/21559799/df1df4c8-ce07-11e6-8983-36b6354c6920.png)
