### ISSUE TITLE
Windows 10: Application has been blocked from accessing Graphics hardware.

### ISSUE THREAD

**Issue by bgiesing** [brave/browser-laptop#5732]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Windows 10's settings app keeps showing notifications in the Action Center saying

> Application Brave.exe has been blocked from accessing Graphics hardware.

**Expected behavior:**
Shouldn't happen at all
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Home Insider Preview Build 14965.rs_prerelease.161104-1700
- Brave Version:
0.12.9
- Steps to reproduce:
Unsure what caused it.
- Screenshot if needed:
![Action center notifications](http://i.imgur.com/bYC5E1A.png)
- Any related issues:

**Comment by ngochacan2001sg** [comment]
I am getting error, but i can't fix.  

I play one game simulator, Run-8 Simulator has been blocked from accessing Graphic hardware "application has been blocked from accessing graphics hardware".

**Comment by daitrongphamhalong2007** [comment]
You can read this tutorial http://howtoinstallwindows10.com/application-has-been-blocked-from-accessing-graphics-hardware/ to fix 
This error related your graphics driver, need install newer/older driver
