### ISSUE TITLE
Localization of Pepper Flash instruction on about:preferences#security

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5733]
**Describe the issue you encountered:**

*This is essentially the same issue as #4102*

This part of Pepper Flash instruction on about:preferences#security should be localizable in languages whose grammar is different from English:
https://github.com/brave/browser-laptop/blob/de1d4e906f19817f1a83f886878b40300a508d31/js/about/preferences.js#L1586-L1589

Because the link to Flash installer cannot be moved, I had to hack the localization on Transifex against the grammar of Japanese (which does not have whitespaces and colons) to make it like this:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20452394/b959f7fe-ae4b-11e6-9cac-ab3baeae0071.png)

**Expected behavior:**

To make the sencense be globally localizable,

1) Remove `&nbsp;` on https://github.com/brave/browser-laptop/blob/de1d4e906f19817f1a83f886878b40300a508d31/js/about/preferences.js#L1586
2) Make the link to Flash installer a variable
3) Remove `.` on https://github.com/brave/browser-laptop/blob/de1d4e906f19817f1a83f886878b40300a508d31/js/about/preferences.js#L1589

and let translators on Transifex decide how to handle them.

--

- Brave Version: 0.12.9

- Steps to reproduce:
    1. Set your lang setting to lang which has different grammar than English, for example, Chinese/Korean/Japanese
    2. Restart the browser 
    3. Open about:preferences#security

- Any related issues: #4102

**Comment by Liunkae** [comment]
See https://github.com/brave/browser-laptop/issues/8162#issuecomment-295369760
