### ISSUE TITLE
Go back button is given "disabled" class after opening a page on the new tab page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5735]
**Describe the issue you encountered:** Go back button is given "disabled" class after opening a page on the new tab page.

**Expected behavior:** the class should be removed

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
 1 Clear your brave folder
 2 Start the browser, and make sure the new tab page is opened
 3 Click the URL bar
 4 Type `github`
 5 Select `github.com` from Top Site in the autocomplete list
 6 GitHub is opened
 7 Click the disabled "Go Back" button
 8 The new tab page is opened
 9 Click the enabled "Go Forward" button
 10 GitHub is reopened, and the disabled "Go Back" button is enabled this time

- Any related issues:

**Comment by bsclifton** [comment]
Yikes- this is a bad one. Glad you caught it, @luixxiul :smile: (I had sworn I saw this, but couldn't repro and thought I was going crazy)

**Comment by luixxiul** [comment]
I'm not sure if this is related with the new tab page because I can reproduce the same issue by setting a homepage and restarting the browser.

**Comment by bbondy** [comment]
Great steps to reproduce @luixxiul, thanks 👍
