### ISSUE TITLE
Tab title is not displayed when reloading the page via the anchor link to itself

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5738]
**Describe the issue you encountered:** The tab title is not properly displayed when reloading the page via the link to the same page

**Expected behavior:** It should be displayed

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Steps to reproduce:
    1. Clear your brave folder
    2. Open https://github.com from the URL bar, and make sure the title is displayed on the tab
    3. Click the top left icon which links to the same page, and make sure the tab title is ``https://github.com/``
    4. Reload the page with the reload button or hitting enter on the URL bar, and make sure the tab title is ``GitHub`` this time 

- Any related issues:

**Comment by luixxiul** [comment]
Please set a milestone if necessary.

**Comment by luixxiul** [comment]
This is reproducible on 0.12.9, Windows

**Comment by luixxiul** [comment]
This can be reproduced by opening a new tab with <kbd>command</kbd> + ``Go back`` button on the navbar.

1 Open https://github.com in a new tab
2 Click "Pull requests" next to the search input form
3 <kbd>command</kbd> + ``Go back`` button on the navbar
4 The title of the new opened tab is ``https://github.com/``

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by bbondy** [comment]
this is working now

**Comment by luixxiul** [comment]
I cannot confirm this was fixed on Windows 10 32 bit:

![github](https://cloud.githubusercontent.com/assets/3362943/22615428/fa6016ac-ead7-11e6-905c-6807023de8cf.gif)

**Comment by bbondy** [comment]
@luixxiul could you confirm which rev you have in about:brave?

**Comment by luixxiul** [comment]
@bbondy It is 1d936db.
