### ISSUE TITLE
related to #572, base problem is that opening an image via drag/drop replaces UI view instead of content area view

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#574]

**Comment by bbondy** [comment]
@diracdeltas

**Comment by bbondy** [comment]
I think we need to handle app's open-file event.

**Comment by diracdeltas** [comment]
I can't repro #572 on 0.7.12

**Comment by FrancisTurner** [comment]
Test

![app](https://cloud.githubusercontent.com/assets/991242/12769832/5e3bc3a8-ca1b-11e5-8302-9eae2ba815b3.png)

**Comment by FrancisTurner** [comment]
Based on the test above: the latest build pulled from github does drop the image correctly but ALSO opens the image in a new tab - see attached

![screenshot - 02032016 - 02 12 37 am](https://cloud.githubusercontent.com/assets/991242/12769871/b21bf1dc-ca1b-11e5-9f3e-acffb365ddaa.png)

**Comment by diracdeltas** [comment]
Yeah, that was noted in  #572. I'm going to close this as a duplicate.
