### ISSUE TITLE
Findbar text selection

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#5744]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The "Match case" label and close button text can be selected by dragging the mouse across the findbar.

**Expected behavior:**
Only the textfield in the findbar is selectable.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.10

- Steps to reproduce:
    1. Open the findbar by pressing Ctrl-F
    2. Drag your mouse cursor across the findbar
    3. Note that the text "Match case" and the rotated plus sign in the close button are highlighted and can be copied to the clipboard using Ctrl-C

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Test plan specified here: https://github.com/brave/browser-laptop/pull/5743#issue-190533449
