### ISSUE TITLE
What are you needing help with?

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#5746]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Any problems, testing things etc ...
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version:
0.12.9

**Comment by jonathansampson** [comment]
This doesn't appear to highlight a new issue, or a request.

If you would like to assist in the development of Brave, please consider reading [our README](https://github.com/brave/browser-laptop/blob/master/README.md). Feel free to file issues against the README (if anything could be stated more clearly). Additionally, please do not hesitate to reach out to the team directly if you have any questions.
