### ISSUE TITLE
Voting on Twitter with Dashlane as PW manager

### ISSUE THREAD

**Issue by stephenkru** [brave/browser-laptop#5748]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Login to twitter, with dashlane as your PW manager. Try to vote in any twitter poll. The vote is not registered and the results are not displayed.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:
0.12.9
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by DivineOmega** [comment]
I believe I'm seeing the same or a very similar issue with LastPass as my password manager.

When pressing the vote button, the results do very briefly flicker before returning to the voting options again. The vote does not appear to count, and the results are not displaying for any meaningful amount of time.

**Comment by Liunkae** [comment]
Possibly related to #4670 (Users are not able to vote on polls on Twitter).

**Comment by michaelAndersonCampingWorld** [comment]
I use 1password, and I can't vote on twitter as well.

**Comment by pixelass** [comment]
Not sure if this is related but I am not able to create polls via brave. I also use dashlane but haven't tried without it. 
My guess was that some plugin is being blocked but I haven't investigated yet. Just wanted to mention that the issue might be related to twitter polls in general.

**Comment by jonathansampson** [comment]
I believe this issue is resolved in 0.13.0. I was able to vote on a poll just now, without any issues.

**Comment by jkup** [comment]
@jonathansampson also started working for me in 0.13.0

**Comment by Liunkae** [comment]
Closing as fixed in 0.13.0.
