### ISSUE TITLE
Context menu cut and paste does not change findbar state

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5753]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
If you cut and/or paste with the findbar's context menu, the state does not change (i.e., the highlighted terms and number of matches do not change).

**Expected behavior:**
The findbar state should change whenever the findbar input changes.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All (found on macOS 10.12.x)

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Open a new Brave tab and navigate to any site.
    2. Open the findbar (Find in Page: Ctrl/Cmd+F).
    3. Copy some text from anywhere.
    4. Right-click the findbar input.
    5. Select Paste.
    6. Notice that the findbar state doesn't change.

- Screenshot if needed:
None.

- Any related issues:
None.

**Comment by Liunkae** [comment]
See PR #5786.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5786#issue-190908774
