### ISSUE TITLE
Some info buttons in preferences are missing content links

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5758]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
There are some info buttons in Preferences > Security, but only two of three are actually clickable. It is confusing because they look the same but work differently. Please see the screenshot below.

My suggestion is to make the clickable buttons actually look like buttons (and look different from the non-clickable one).

**Expected behavior:**
Clickable elements should be easily distinguishable from non-clickable elements.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All (found on macOS 10.12.x)

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Open a new Brave window and open Preferences.
    2. Open the Security section.
    3. Look at the "info" buttons (black circles with `i`) and wonder if they are clickable…

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/20472157/f75e2570-af7c-11e6-8387-ebbabfe50cd3.png)

- Any related issues:
None.

**Comment by bradleyrichter** [comment]
@Liunkae These all should have page links so I changed the title.

**Comment by bradleyrichter** [comment]
@diracdeltas  Did we ever add an info page for Flash? I think this could link to your latest helpful flash wiki page.

**Comment by bradleyrichter** [comment]
#5733

**Comment by diracdeltas** [comment]
0.12.10 has the flash wiki link already

**Comment by Liunkae** [comment]
Yes, 0.12.10 has the Flash wiki link. The two info buttons in the Plugin Settings section still don't link to anything.
![image](https://cloud.githubusercontent.com/assets/19424103/20550683/db572d54-b0fd-11e6-85fb-85bcfdae9a41.png)
