### ISSUE TITLE
Links to external URLs in the UI should have tooltips

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5759]
**Did you search for similar issues before submitting this one?**
Yes.

**Expected behavior:**
Before I click a link, I prefer to know in advance where the link will go. Throughout the Brave UI, I would like all links to external URLs to have a tooltip that indicates their URL. See the screenshot below for an example of what this would look like.

Some examples:
- Preferences > Security > Adobe (Flash download link)
- Preferences > Security > wiki (Flash troubleshooting tips)
- Preferences > Security > Google Widevine Support info buttons (DRM info and Google Widevine terms)
- Shields panel > Fingerprint Protection (info on Brave wiki)

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/20473710/124d46b2-af88-11e6-8a16-67d42943956d.png)

- Any related issues:
None.

**Comment by Liunkae** [comment]
See PR #5787.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5787#issue-190913537
