### ISSUE TITLE
slack tab loses favicon

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#576]
When I open slack and login to [team].slack.com, the favicon disappears in Brave. seems to show up in Firefox.

**Comment by dhgwilliam** [comment]
Happening for me on Linux, building brave from master 0846eb8c8a6b40ee2cb86235974c73d1db5f058a . Slack icon shows up initially but disappears after some consideration.

```
{ brave: '0.7.12',
  npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.5.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

**Comment by psimyn** [comment]
due to base64 being blocked by CSP. Can fix independently by adding `data:` to img-src CSP tag

**Comment by bbondy** [comment]
@diracdeltas please advise on CSP

**Comment by diracdeltas** [comment]
Pretty sure this is not purely a CSP issue, since I reported this bug while dogfooding a release that didn't have CSP. But if @psimyn's fix works, i'm happy to merge it for now.

**Comment by psimyn** [comment]
@diracdeltas it wasn't just csp, it was also appending`#-moz-resolution=` to the base64 image string
