### ISSUE TITLE
Plugin settings info icons are misaligned

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#5760]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
The info icons in plugin settings (in Preferences) are misaligned. See the screenshot below for details.

**Expected behavior:**
The icons should be aligned.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Found on macOS 10.12.x

- Brave Version:
0.12.10 release candidate 1

- Steps to reproduce:
    1. Open a new Brave window and open Preferences.
    2. Open the Security section.
    3. Look at the Plugin Settings section. Notice that the icons are misaligned.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/20474055/2c2e39f4-af8a-11e6-86ca-d47b76336fc5.png)

- Any related issues:
#5758 also mentions these info icons.

**Comment by luixxiul** [comment]
I'm working on it

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6138 (as PR #5783 was superseded with it)
