### ISSUE TITLE
URL selection on the URL bar conflicts with the URL autocomplete based on history

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5761]
**Describe the issue you encountered:** URL selection on the URL bar conflicts with the URL autocomplete based on history.

1 Open `https://github.com/brave/browser-laptop/issues/4852#issuecomment-261872105` in a new tab
2 Delete `#issuecomment-261872105` on the URL bar
3 Hit <kbd>Command</kbd> + a to select `https://github.com/brave/browser-laptop/issues/4852`

Then `#issuecomment-261872105` is filled automatically and selected

![url](https://cloud.githubusercontent.com/assets/3362943/20475587/fac2cbf6-b00f-11e6-8470-648454f3a94c.gif)

**Expected behavior:** `https://github.com/brave/browser-laptop/issues/4852` should be selected 

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues:

**Comment by patrick99e99** [comment]
+1, this happens to me all the time but using keyboard shortcuts:  cmd-l to select url bar, cmd-right-arrow to go to the end of the url, option-left-arrow to move back by path a few times, ctrl-k to delete from where the cursor is at...  result is new text immediately appears where I tried to delete from.

**Comment by luixxiul** [comment]
This seems to have been fixed. Closing.

**Comment by luixxiul** [comment]
Adding the most recent milestone to forward the issue to the QA work.
