### ISSUE TITLE
Dropdown not shown completely when right click/long press on newtab button

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5763]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Dropdown not shown completely when right click/long press on newtab button

**Expected behavior:**
Should show the context menu within the browser depending on the position of the newtab button

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.10 RC1

- Steps to reproduce:
    1. Set max tab limit to 10(default)
    2. Open 9/10 tabs to ensure new tab button is right next to the hamburger menu
    3.  Long press on the new tab button/right click on the new tab button to show the context menu, most of it is hidden 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20480661/5afda250-afdb-11e6-9a51-6418d94722db.png)

- Any related issues:
#5704  cc: @bsclifton

**Comment by Liunkae** [comment]
+1 from #5784.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5854#issue-191830496
