### ISSUE TITLE
about:blank shows chrome-extension in navigation button history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5764]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
about:blank shows chrome-extension in navigation button history

**Expected behavior:**
Should show about:blank similar to other about pages

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.10 RC1

- Steps to reproduce:
    1. Set new tab opens with my homepage
    2. Clear the homepage field
    3. Open a new tab which shows about:blank navigate to a site and long press the back navigation button, shows full chrome extension for about:blank

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20482323/014f33aa-afe4-11e6-9bca-13a76498096e.png)

- Any related issues:
#5654 
  cc: @cezaraugusto 
  Setting milestone as 0.12.11, please change if required

#5657

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5782#issue-190871661
