### ISSUE TITLE
Manually added bookmark doesn't show the last visited date after visiting the site post bookmark import

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5766]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Manually added bookmark doesn't show the last visited date after visiting the site post bookmark import

**Expected behavior:**
Should show the last visited date similar to all bookmarks

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1. Visit any site and add as a bookmark in a different browser
    2. Manually add a bookmark in a different browser
    3. Export bookmarks to a HTML file
    4. Import the created HTML file into Brave
    5. Open about:bookmark and double click on the site added in step1, shows last visited date 
    6. Double click to open the site added in step 2, doesn't update the last visited date even after multiple try

- Screenshot if needed:
![importbookmark](https://cloud.githubusercontent.com/assets/17010094/20482961/7f262a74-afe7-11e6-955a-7cac4a15fce3.gif)

- Any related issues:
#5621 #5699
  
  cc: @bsclifton 
  Setting milestone as 0.12.11, please change if required

**Comment by rebron** [comment]
Closing wontfix. No corresponding last visited feature in brave-core.
