### ISSUE TITLE
Visiting a new site puts the tile in between the two pinned tiles and not in first position

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5768]
## Test plan
See https://github.com/brave/browser-laptop/pull/12470

## Original issue description
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Visiting a new site puts the tile in between the two pinned tiles and not in first position

**Expected behavior:**
New site tile should be in the first position irrespective of the position of the pinned tiles

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.10 RC1

- Steps to reproduce:
    1. Visit a bunch of sites to fill the top site tiles
    2. Pin the 2nd & 4th tiles
    3. Visit a new site, the top site tile for the visited site is added in between the pinned tiles instead in the first position

- Screenshot if needed:
![ezgif com-resize](https://cloud.githubusercontent.com/assets/17010094/20487136/235509aa-affa-11e6-85d4-ed107f6b9911.gif)

- Any related issues:
#5645
  cc: @cezaraugusto

**Comment by bsclifton** [comment]
While it would be nice, I think this is lower priority.  Moving back a bit (please feel free to grab it folks 😄 )
