### ISSUE TITLE
error loses all tabs

### ISSUE THREAD

**Issue by adikira** [brave/browser-laptop#5769]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
I had a good number of tabs opened (2 "screens" and 2 tabs opened on the 3rd one). I got an error, something like "had to reopen window due to an error" and all my tabs were gone except one (probably the first tab in the window?).
**Expected behavior:**
The tabs would be restored.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7
- Brave Version:
0.12.8
- Steps to reproduce:
    1. N/A
    2.
    3.

- Screenshot if needed:
N/A
- Any related issues:
N/A

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/5512
