### ISSUE TITLE
~/.brave-gyp is used as relative path

### ISSUE THREAD

**Issue by indutny** [brave/browser-laptop#577]
Not sure if it is an issue, as everything else appears to be working fine, but anyway. During the build I have noticed that paths look like this:

```
Code/brave/browser-laptop/node_modules/tracking-protection/~/.brave-gyp/.node-gyp/0.36.7/deps/v8/include
```

It looks like `~/.brave-gyp` is used as a relative path, not absolute there.

**Comment by luixxiul** [comment]
@bbondy Was this fixed?

**Comment by bbondy** [comment]
It's not fixed yet but we just need to get the full user home directory and append brave-gyp here:
https://github.com/brave/browser-laptop/blob/master/tools/rebuildNativeModules.js#L6

Marking this as good first bug.

**Comment by rifazn** [comment]
Will changing the `~/.brave-gyp` to `$HOME/.brave-gyp` help?

**Comment by indutny** [comment]
I doubt that it will fix it. This path doesn't seem to be resolved automatically at that stage.
