### ISSUE TITLE
Buttons not aligned properly in payments advance settings in different language

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5771]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Buttons not aligned properly in payments advance settings in different language

**Expected behavior:**
All buttons should be properly aligned

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.10 RC1

- Steps to reproduce:
    1. Change language to Portugese(Brazil)
    2. Open advance settings in payment window
    3. See the buttons misaligned.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20489488/bc9b8e56-b002-11e6-909a-11ee8bf24ea8.png)

- Any related issues:
#5719 #5718

**Comment by luixxiul** [comment]
This will be fixed if #5705 is merged

**Comment by luixxiul** [comment]
Fixed for now.

**Comment by luixxiul** [comment]
Follow-up of this: 5th commit of #6047
