### ISSUE TITLE
Magnifying glass icon shown for pdf documents opened in Brave

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5774]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Magnifying glass icon shown for pdf documents opened in Brave

**Expected behavior:**
Should show the padlock symbol based on the connection type(secure/insecure) or use fa-file-pdf-o  icon for pdf documents

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.10 RC1

- Steps to reproduce:
    1. Open http://www.orimi.com/pdf-test.pdf
    2. Shows magnifying glass icon 
    3. Clicking on that shows the connection state(secure/insecure)

- Screenshot if needed:
![screenshot from 2016-11-21 16-47-55](https://cloud.githubusercontent.com/assets/17010094/20492635/639e5a12-b00d-11e6-8776-2b333f7ca1f5.png)

- Any related issues:
Please change the milestone if needed

**Comment by diracdeltas** [comment]
I think PDFs should just show up as whatever the embedded document protocol is. AKA unlocked icon for HTTP PDFs, locked icon for HTTPS. Right now there it always displays as insecure:
![screen shot 2016-11-21 at 10 08 18 am](https://cloud.githubusercontent.com/assets/549654/20500380/0aa52a94-afea-11e6-964b-98942ce2a270.png)
