### ISSUE TITLE
Newtab should not have an empty favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5776]
**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Newtab should not have an empty favicon

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.10 RC1

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20497894/d403d3f8-b022-11e6-852f-9355ba6f8575.png)

  edit: both newtab and about:blank

- Any related issues:

**Comment by bsclifton** [comment]
Thinking about this, the solution might be as easy as removing the icon from the about-blank.html / about-newtab.html :smile:

**Comment by bbondy** [comment]
@bsclifton sounds like a good plan

**Comment by luixxiul** [comment]
Test plan: automated test should pass
