### ISSUE TITLE
flash content with audio not recognized like video,  thus no UI controls present

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5779]
Ideally a flash object that contains audio would respond to the normal tab and contextual mute controls in the same way that a youtube video can be muted.

cc @diracdeltas @bbondy

**Comment by bridiver** [comment]
@bradleyrichter can you provide an example?

**Comment by bridiver** [comment]
I found one and this is fixed http://www.mcmediaplayer.com/examples/audio/index.html
