### ISSUE TITLE
Backspace key no longer loads previous web page on Windows 10

### ISSUE THREAD

**Issue by mgnewmaker** [brave/browser-laptop#5781]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
@mgnewmaker This functionality was intentionally removed. (https://github.com/brave/browser-laptop/issues/5491#issuecomment-259182736). See issue #424 for details and discussion about adding it back. 😉
