### ISSUE TITLE
Gray footer which contains nothing on the QR code overlay window on about:preferences#payments

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5785]
**Describe the issue you encountered:** If you live outside of the US you get the dark footer which contains nothing on the QR code overlay window on about:preferences#payments

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/20509413/f2695780-b0ab-11e6-91dd-5a1649df14ce.png)

**Expected behavior:** The less files for a modal overlay and preference page should be much less complex to keep the consistency, including the close button (#5719) alignment. They need refactoring.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.10

- Steps to reproduce:
    1. Modify the code to disable coinbase

- Any related issues: #5719 #5799

**Comment by srirambv** [comment]
I don't see this on my Windows 10 machine
![image](https://cloud.githubusercontent.com/assets/17010094/20517352/9a522ff4-b092-11e6-90e7-f6cba30e3cb0.png)

**Comment by luixxiul** [comment]
You get the footers because var `coinbaseCountries` in coinbaseCountries.js contains `IE`. It is expected and is working well for you.

**Comment by srirambv** [comment]
Shouldn't it not show Coinbase as well since its showing bitcoin source as Cubits for outside US??

**Comment by luixxiul** [comment]
CCing @mrose17 for thoughts

**Comment by luixxiul** [comment]
@srirambv mind opening an issue for that?

**Comment by luixxiul** [comment]
Fixed with #5797

**Comment by luixxiul** [comment]
My bad, it is not fixed

**Comment by bsclifton** [comment]
Will be fixed by https://github.com/brave/browser-laptop/pull/6009

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/commit/21ece29eab80de4af2c606a65b54c13764b04c93

> Test Plan 4:
> 1. Disable Coinbase via VPN
> 2. Make sure the grey footer no longer appears on the Add funds dialog
