### ISSUE TITLE
Coinbase should not be shown in payment modal when bitcoin source is not Coinbase

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5788]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Coinbase should not be shown in payment modal when bitcoin source is not Coinbase

**Expected behavior:**
Should show only the bitcoin source in the payment modal

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.12.10

- Steps to reproduce:
    1. Set system IP to be other than US
    2. Open payment modal 
    3. Verify Coinbase is not shown in Add funds modal and in QR Code modal

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20522820/22b48e52-b0aa-11e6-8504-92dd9be4e235.png)

- Any related issues:
#5785

**Comment by luixxiul** [comment]
Test plan: available in the 1st post
