### ISSUE TITLE
Certain emoji fonts are tofu

### ISSUE THREAD

**Issue by Suaiden** [brave/browser-laptop#5789]
**Did you search for similar issues before submitting this one?** Yes.

**Describe the issue you encountered:** When using Gab (http://gab.ai), the handy emojis used as markers for subcategories are all tofu. Though I downloaded Noto fonts to compensate, the tofu remains.

**Expected behavior:** Not to see tofu. They work fine on latest version of Firefox and I can't figure out how to get to font settings in the backend.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux Ubuntu version.

- Brave Version: Brave: 0.12.8
Electron: 1.4.23
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev

- Steps to reproduce:
    1. Download Linux version.
    2. Visit http://gab.ai
    3. Tofu appears on sidebar as well as the entry edit section. Emojis inpost not working but I assume that's a separate issue.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/23656612/20523744/8d8c55b4-b084-11e6-9717-f87e945ce44f.png)

- Any related issues: None other than mentioned. Browser works fantastic otherwise.

**Comment by privatzee** [comment]
Can you post a screenshot of any errors in the devtools' console? I tried to sign up there to test but there are ~200,000 waiting ahead of me. 

> Thank you for registering for Gab! Our mission is to put people first and promote free speech and expression. All are welcome on Gab, and always will be.
Currently Gab is in beta, it may take up to two weeks to receive your invitation due to high demand from around the world.

(Hit F12 for devtools, btw.) 

At this point, the likely cause is that the images are blocked because of one of the Brave shields.  Have you tried setting up like the following:

 ![image](https://cloud.githubusercontent.com/assets/22591438/20530390/2ee8bd78-b0a1-11e6-95f1-031d9d9977e0.png)

**Comment by Liunkae** [comment]
Note: The latest version of Firefox (50.0) did change handling of Emojis on some platforms.

From https://www.mozilla.org/en-US/firefox/50.0/releasenotes/:
> Added a built-in Emoji set for operating systems without native Emoji fonts (Windows 8.0 and lower and Linux)

Perhaps the same thing could be done for Brave.

**Comment by privatzee** [comment]
Thanks for clearing that up, Liunkae. It's apparently not at all what I was thinking. It looks like this page demonstrates the emoji problem: http://getemoji.com/    where e.g. _Pale Emojis_ only show properly on FF and not at all on my Chrome (Win7)

Though I'm not getting why any website would include fonts/characters that can't be seen on the world's most used operating system and most used browser (W7 and Chrome).

**Comment by Suaiden** [comment]
Actually, that getemoji page is very helpful. This is pale emojis. 
![image](https://cloud.githubusercontent.com/assets/23656612/20539722/130a2966-b0c4-11e6-8c86-a764ed985032.png)
With the exception of about half the smileys and the ask.fm icons... they're all tofu on my Brave browser (I'm using the Linux version).

**Comment by privatzee** [comment]
Acct approved today, all looks okay on--> w7x64
So the problem is perhaps on Linux only? Anybody with Mac can test at: http://getemoji.com/ 

![image](https://cloud.githubusercontent.com/assets/22591438/20572875/55cfe288-b17b-11e6-9b8d-ed4d89bbd534.png)

**Comment by stan-qaz** [comment]
I posted this issue as a bug to Gab, they have it on the list to be fixed.

https://gab.ai/gabot/posts/1676382  (must have a Gab account to view the topic until their next update)

Stanley P. Miller · @stan_qaz
💻 Technology · 6 days
@gabot What font are you pulling the icons for the categories from? I only see icons for Explore and Humor, the rest are just a null placeholder here. Chrome or Brave browsers running on OpenSuse 42.2 if that helps.

Gabot · @gabot
💻 Technology · 5 days
@stan_qaz Thanks for the feedback! I'll fix it in the next update

**Comment by Suaiden** [comment]
I responded on @Gab and copied @support. @Gabot is actually an unofficial Android app, but the developer may be part of the support team. 

---- On Wed, 23 Nov 2016 20:40:10 -0500 Stanley P. Miller &lt;notifications@github.com&gt; wrote ---- 

I posted this issue as a bug to Gab, they have it on the list to be fixed.
 https://gab.ai/gabot/posts/1676382 (must have a Gab account to view the topic until their next update)
 Stanley P. Miller · @stan_qaz
 💻 Technology · 6 days
 @gabot What font are you pulling the icons for the categories from? I only see icons for Explore and Humor, the rest are just a null placeholder here. Chrome or Brave browsers running on OpenSuse 42.2 if that helps.
 Gabot · @gabot
 💻 Technology · 5 days
 @stan_qaz Thanks for the feedback! I'll fix it in the next update

**Comment by stan-qaz** [comment]
I found a partial solution, it doesn't give me all the icons in the test page above but I didn't switch my default font to avoid conflicts as they suggest in the read-me as I am already using Noto and not Bitstream Vera. (scroll down) https://github.com/eosrei/emojione-color-font

Added this font: EmojiOne Color SVGinOT from here https://github.com/eosrei/emojione-color-font/releases

**Comment by Suaiden** [comment]
This fixed the issue on Gab though! Thanks!

---- On Sat, 26 Nov 2016 12:31:11 -0500 Stanley P. Miller &lt;notifications@github.com&gt; wrote ---- 

I found a partial solution, it doesn't give me all the icons in the test page above but I didn't switch my default font to avoid conflicts as they suggest in the read-me as I am already using Noto and not Bitstream Vera. (scroll down) https://github.com/eosrei/emojione-color-font
 Added this font: EmojiOne Color SVGinOT from here https://github.com/eosrei/emojione-color-font/releases
