### ISSUE TITLE
Add option "Keep local data only until I quit my browser"

### ISSUE THREAD

**Issue by anthony-redFox** [brave/browser-laptop#579]
Like Chrome - https://support.google.com/chrome/answer/95647?hl=en
For information:
https://freedom-to-tinker.com/blog/englehardt/how-cookies-can-be-used-for-global-surveillance/
https://freedom-to-tinker.com/blog/dreisman/cookies-that-give-you-away-the-surveillance-implications-of-web-tracking/

**Comment by diracdeltas** [comment]
merging this into #1413
