### ISSUE TITLE
about:brave page should have "copy to clipboard" button

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#5790]
I like the recent change to version info. It looks cleaner than presenting a dialog. One downside though is that selecting and copying the info gives me this:

Brave	0.12.10
Muon	1.4.26
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-27-generic
os.arch	x64

It might be better to add a "copy to clipboard" button which provides something slightly easier to scan when pasted into issue tickets:

Brave: 0.12.10
Muon: 1.4.26
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev
os.platform: linux
os.release: 4.8.0-27-generic
os.arch: x64

That's basically the text content format of the old dialog.

**Comment by srirambv** [comment]
#5693 should be able to cover this as well

**Comment by bsclifton** [comment]
This is a great one- we're already integrated with a clipboard library, this should be a slam dunk :smile:

**Comment by gyandeeps** [comment]
I am trying to get my feet wet with brave code. Can I work on this issue and send my first PR?

**Comment by bsclifton** [comment]
@gyandeeps that would be awesome!

@bradleyrichter do you have a recommendation of how a "copy to clipboard" button would look? (and where it may go in relation to the current about:brave screen)?

**Comment by bradleyrichter** [comment]
That FA icon is perfect.

**Comment by gyandeeps** [comment]
Thanks @bsclifton and @bradleyrichter for giving all this info. The only thing left is where shoudl this icon be placed on the about page (top, bottom , etc)?

**Comment by bradleyrichter** [comment]
@gyandeeps 

How about this?

![image](https://cloud.githubusercontent.com/assets/13509546/21025533/a44e904e-bd3d-11e6-8ffb-1312d0c1ae64.png)

**Comment by gyandeeps** [comment]
looks good to me. I will go with this design as of now unless somebody recommends something else.
Thanks @bradleyrichter

**Comment by CliqueBait** [comment]
Thanks for volunteering time to this @gyandeeps . I'll have to get my feet wet soon too.

**Comment by bsclifton** [comment]
That would be awesome, @CliqueBait :smile: Let us know if you have any questions

**Comment by bbondy** [comment]
reset milestone for now.
This issue is blocked because of:
https://github.com/brave/browser-laptop/issues/6183
And some comments in the PR.

**Comment by luixxiul** [comment]
Test plan: https://github.com/bsclifton/browser-laptop/commit/0d4eba52fcd143d28be79115ea76157f543140d7
