### ISSUE TITLE
Insecure connection icon shown on localhost

### ISSUE THREAD

**Issue by matthewp** [brave/browser-laptop#5791]
**Did you search for similar issues before submitting this one?**

Yes, I did.

**Describe the issue you encountered:**

When browsing a site on localhost the Insecure connection icon is shown.

**Expected behavior:**

localhost is usually exempt from such things, so I would expect no icon (neither secure nor insecure).

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac.

- Brave Version:

0.12.9

- Steps to reproduce:
    1. Start local web server
    2. Navigate to it.
    3.

- Screenshot if needed:

<img width="124" alt="screen shot 2016-11-22 at 8 56 22 am" src="https://cloud.githubusercontent.com/assets/361671/20526401/e33ba6f6-b091-11e6-94d1-407aa914aa6c.png">

**Comment by bbondy** [comment]
The icon changed recently but this is just the icon we use to denote secure HTTPS vs HTTP or mixed connections.

<img width="246" alt="screenshot 2016-11-22 15 16 31" src="https://cloud.githubusercontent.com/assets/831718/20540286/ac5e42b2-b0c6-11e6-9a5b-2ff6e0d06d86.png">

I understand that how can a local site be insecure, but maybe some will find it useful to know when connections to their local server is being tested through HTTPS vs HTTP.

I think this should be wontfix.
