### ISSUE TITLE
broken images in thumbnails, on the new-tab page.

### ISSUE THREAD

**Issue by getsetbro** [brave/browser-laptop#5793]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Seeing broken images in thumbnails, on the new-tab page.
**Expected behavior:**
Anything besides the broken image. Blank would be fine.
- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X El Capitan 10.11.6 (15G1108)
- Brave Version:
0.12.10
- Steps to reproduce:
    1. Browse somewhere without a favicon. //localhost will do it.
    2. Observe missing images in the new-tab page.
    3.

- Screenshot if needed:
<img width="564" alt="screen shot 2016-11-22 at 9 13 22 am" src="https://cloud.githubusercontent.com/assets/442793/20529026/2fe0acb6-b094-11e6-9232-fd4372a07489.png">

- Any related issues:

**Comment by luixxiul** [comment]
Hi, the team has noticed the bug already and working on it here: #5455. So closing this ticket in favor of that. Thanks for your report.
