### ISSUE TITLE
Chromium 54 : New tab should respect preference settings.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5794]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When opening a new tab, a blank page appears. I checked with @bridiver and he said that respecting the preference settings should be a separate issue.

**Expected behavior:**
Whatever is selected in the preferences for new tab should be what is shown.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.13.0

- Steps to reproduce:
    1. With the Chromium54 build, open a new tab.

- Screenshot if needed:

- Any related issues:

**Comment by darkdh** [comment]
It works as expected on the latest commit of chromium54. Feel free to reopen it if the newer build is not working.
