### ISSUE TITLE
Chromium54 - Keyboard shortcuts are not working on URL bar

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5795]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When selecting text in the URL bar, I then used a keyboard shortcut to copy the text.
After switching focus to another app, I pasted the text but found that the buffer had not been updated with my new selection.

**Expected behavior:**
If I select and copy text, it ought to be what is pasted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
Chromium54 build1

- Steps to reproduce:
    1. Open the Chromium54 build, find a cool link.
    2. Open the Twitter app. Start to write a new tweet. 
    3. Select the text in the URL bar (do not change focus to Brave first)
    4. Copy the highlighted text via the keyboard shortcut.
    5. Attempt to paste the text in the new tweet field.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
In Step 2 do you mean the twitter page or a macOS app?

**Comment by alexwykoff** [comment]
The macOS app.  

The central issue is that using CMD + C on the url bar when the url is highlighted is not putting the url in the clipboard (copy buffer). Right-clicking and selecting copy from the context menu does work.

**Comment by darkdh** [comment]
I just tested it with latest commit and it works. Feel free to reopen it if next build doesn't work.
