### ISSUE TITLE
Add drop down options to reload button

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5796]
<img width="465" alt="screenshot 2016-11-22 12 18 01" src="https://cloud.githubusercontent.com/assets/831718/20534073/cb846540-b0ad-11e6-8b62-5c12e5aca123.png">

/cc @bsclifton

**Comment by Liunkae** [comment]
See PR #5802.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5802#issue-191163257
