### ISSUE TITLE
Addfunds dialog needs a little margin

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#5799]
as noted in https://github.com/brave/browser-laptop/pull/5797#issuecomment-262367178

![446c2cfc-b0b5-11e6-83b1-9949cbecbcd3](https://cloud.githubusercontent.com/assets/400552/20542662/6f665688-b0b7-11e6-8f3f-ba21fc9ae7a9.png)

**Comment by luixxiul** [comment]
working on it 

<img width="711" alt="screenshot 2016-11-23 11 19 47" src="https://cloud.githubusercontent.com/assets/3362943/20549374/edc4bbf2-b16e-11e6-8cff-9dbe53d820af.png">

**Comment by bsclifton** [comment]
@luixxiul was this addressed with https://github.com/brave/browser-laptop/pull/6009?

**Comment by luixxiul** [comment]
@bsclifton No, I will fix this in the next PR (part 2).

**Comment by luixxiul** [comment]
The fix will be like these:

For US
<img width="727" alt="screenshot 2016-12-08 23 29 36" src="https://cloud.githubusercontent.com/assets/3362943/21013635/384443f6-bd9e-11e6-9472-2ad751496cae.png">

For non-US
<img width="738" alt="screenshot 2016-12-08 23 06 17" src="https://cloud.githubusercontent.com/assets/3362943/21013552/e3822496-bd9d-11e6-9212-c26406eff610.png">

With `.pull-right` the button is misaligned.
<img width="733" alt="screenshot 2016-12-08 23 34 39" src="https://cloud.githubusercontent.com/assets/3362943/21013868/ee76bdfc-bd9e-11e6-998d-338ceaf7a20f.png">

**Comment by luixxiul** [comment]
Test plan:

Open about:preferences#payments
Click "Add funds"
Make sure the buttons on the footer are aligned like this: https://github.com/brave/browser-laptop/issues/5799#issuecomment-265754254
