### ISSUE TITLE
Make button styles consistent 

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5801]
This awesome screenshot from @bsclifton shows inconsistencies in our primary and white buttons. We should make them all look identical re: font-size, color and font-weight.
![pasted image at 2016_11_22 03_29 pm](https://cloud.githubusercontent.com/assets/490294/20545088/024a72a4-b0c2-11e6-8e2e-b2ee8027d192.png)

**Comment by luixxiul** [comment]
#5705 should fix some of them.

**Comment by jkup** [comment]
It actually looks like these discrepancies are intentional. If you inspect those bold buttons or the white one with orange text you'll see custom classes like secondaryAltButton are responsible.

@bradleyrichter is it desired to have some buttons (import browser data for example) with bold white text and some white buttons with orange text or should they all look 100% consistent?
<img width="262" alt="screen shot 2016-11-27 at 1 46 57 pm" src="https://cloud.githubusercontent.com/assets/490294/20652098/ff183a0a-b4a7-11e6-8364-263c9692f965.png">

**Comment by bradleyrichter** [comment]
@jkup They should all match this pair:

![image](https://cloud.githubusercontent.com/assets/13509546/20652128/5344451a-b4a8-11e6-9668-fd806f303bf4.png)


Here is are the specs for the button styles:

![image](https://cloud.githubusercontent.com/assets/13509546/20652169/e8826dfa-b4a8-11e6-9a93-b8934e13376f.png)

**Comment by jkup** [comment]
@bradleyrichter Ok awesome! I'm going to remove all these additional classes so they all look the same!

**Comment by bradleyrichter** [comment]
Awesome. And then I can refine them like a boss. (soften up the shadows and blends)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5916#issue-192396427
