### ISSUE TITLE
Brave wallet recovery failure message should be localizable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5806]
**Describe the issue you encountered:** https://github.com/brave/browser-laptop/blob/55de60361097819fc0f0d1eeb744ddcf34543e17/js/about/preferences.js#L1131-L1132 is hardcoded and cannot be localized.

<img width="486" alt="screenshot 2016-11-23 13 38 46" src="https://cloud.githubusercontent.com/assets/3362943/20551311/3e780f50-b182-11e6-8012-3fcda7749128.png">

**Expected behavior:** It should be localizable

- Brave Version: master branch

- Any related issues:

## Test plan
https://github.com/brave/browser-laptop/issues/4720#issue-182585748

**Comment by luixxiul** [comment]
Also https://github.com/brave/browser-laptop/blob/master/js/about/preferences.js#L1125

**Comment by bsclifton** [comment]
@luixxiul this might be a good issue for you to solve, since you're already in there :smile: Please feel free to assign

**Comment by bsclifton** [comment]
Removed ledger label; see the commit in first post for the two strings which need to be localized :smile:
