### ISSUE TITLE
numerous crashes since last update (0.12.10) on Mac

### ISSUE THREAD

**Issue by dmeulemans** [brave/browser-laptop#5810]
Brave crashes several times per day.

Platform macOS El Capitan 10.11.3 (15D21)

Brave Version: 0.12.10

**Comment by luixxiul** [comment]
Which URL were you opening for example?

**Comment by dmeulemans** [comment]
Occurs not on specific URL. You want a stacktrace if it happens again?

Op 23-nov.-2016 17:49 schreef "Suguru Hirahara" <notifications@github.com>:

**Comment by Liunkae** [comment]
@dmeulemans Anything to help debug the issue would be helpful. 😉

**Comment by psmalone** [comment]
Don't know if this is the same problem, but I frequently crash 0.12.10, El Capitan 10.11.6, by opening a URL then command-tabbing to another app while the page is still loading. The crash is silent--Brave is just no longer open.

I'm new to diagnostics, but I think it might be this section of the system log. Please let me know if there's somewhere else to look.

Nov 27 09:31:11 CCFP-0201 Brave Helper[38374]: Couldn't set selectedTextBackgroundColor from default ()
Nov 27 09:31:20 CCFP-0201 UserEventAgent[50]: extension com.egnyte.DesktopSync.DesktopSyncFinderExt -> com.egnyte.EgnyteDesktopSync
Nov 27 09:31:21 CCFP-0201 kernel[0]: Google Chrome He[38383] triggered unnest of range 0x7fff88600000->0x7fff88800000 of DYLD shared region in VM map 0xd739befffa313d49. While not abnormal for debuggers, this increases system memory footprint until the target exits.
Nov 27 09:31:23 CCFP-0201 Brave Helper[38384]: CGAffineTransformInvert: singular matrix.
Nov 27 09:31:24 CCFP-0201 Brave Helper[38385]: CGAffineTransformInvert: singular matrix.
Nov 27 09:31:51 CCFP-0201 Brave Helper[38387]: CGAffineTransformInvert: singular matrix.
