### ISSUE TITLE
Cannot post update/comment to linkedin.com

### ISSUE THREAD

**Issue by mbootsman** [brave/browser-laptop#5811]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When trying to post an update/comment, the error 'There was a problem sharing your update. Please try again.' appears and the update/comment is not posted. Switching Shields off does not make a difference.

**Expected behavior:**
Update/Comment is posted to Linkedin

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux
- Brave Version:
0.12.9

- Steps to reproduce:
    1. Login to Linkedin
    2. Post an update/comment
    3. See error message

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7383)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-linkedin-com/10677

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
