### ISSUE TITLE
Load time shown in URL bar needs left padding when URL is selected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5814]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Page load time shown in URL bar needs left padding when URL is selected. 

**Expected behavior:**
Should retain the left padding when the URL text is selected

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
master

- Steps to reproduce:
    1. Open any site wait till the full page is loaded
    2. Page load time has padding when URL text is not selected
    3. On URL selection the padding is lost and the time shown is right next to the last character selected in the URL

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20566343/9c3ec08e-b18c-11e6-9507-afc525c28621.png)
![image](https://cloud.githubusercontent.com/assets/17010094/20566356/ab135868-b18c-11e6-94d1-184aa49d2aa1.png)

- Any related issues:
cc: @bradleyrichter @bsclifton

**Comment by luixxiul** [comment]
Will this be included in 0.13.0 or 0.13.1?

**Comment by bbondy** [comment]
Sorry @luixxiul there were 2 invalid RC tags made from master and not dev-channel, I removed them. So the commit now shows the correct info.  It is not in 0.13.0.
