### ISSUE TITLE
Change download icon to save after torrent is downloaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5815]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Currently torrent download shows the download button even after completing the download

**Expected behavior:**
Should change the download icon to save button upon completion 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
Master

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20566440/001922b6-b18d-11e6-912d-8536b0bd5636.png)

- Any related issues:
cc: @dcposch @feross @bradleyrichter

**Comment by dcposch** [comment]
How about just changing Download to Save File?

**Comment by luixxiul** [comment]
Would anyone please add QA steps for this issue? 0.13.0 will be the largest release ever and the QA team needs clear and simple steps! Please see #6668 for more info. Thanks in advance :pray:

**Comment by srirambv** [comment]
- QA Steps
   1. Open any magnet link
   2. Let the torrent start downloading in torrent viewer
   3. In torrent viewer tab, ensure instead of the `Download`  you have `Save File`

**This can only be tested once #5981 is fixed**

**Comment by luixxiul** [comment]
@srirambv do you have an example of the magnet link you use?

**Comment by srirambv** [comment]
@luixxiul Its mentioned in #5981. 
Also pasting it here for reference. Can use any of the magnet links mentioned here https://codepen.io/ferossity/full/qaezaB/
