### ISSUE TITLE
Too much spacing between Home button and URL bar on Master

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5816]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Too much spacing between Home button and URL bar on Master

**Expected behavior:**
Should not have too much spacing between home button and URL bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
master

- Steps to reproduce:
    1. Enable Home button in preferences, see the spacing between URL bar and home button 
    2. Reduce the size of the window horizontally, spacing remains as it is but URL right border is messed up right border gets tucked in the URL bar
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20567058/3e7323f2-b18f-11e6-945c-a02831c0bc5f.png)

![image](https://cloud.githubusercontent.com/assets/17010094/20567048/32fba1de-b18f-11e6-9e30-cf4b4f0ad23b.png)

- Any related issues: #5439 #5530 
cc: @bsclifton

**Comment by luixxiul** [comment]
This is caused by moving the star icon (`.bookmarkButton`) in `.startButtons` which is outside of `.urlbarForm` into it with CSS. We could set width:0 to `.startButtons` but it would lead unexpected regressions.

**Comment by bradleyrichter** [comment]
I'm fixing this one.

**Comment by bsclifton** [comment]
With the rollback of the blue outline PR (with https://github.com/brave/browser-laptop/commit/9aedf588300741d65bb06de4f7fb8d5c7842126a), this should be resolved, right?

**Comment by bradleyrichter** [comment]
yes
