### ISSUE TITLE
Feature Request: show QR Code of current URL

### ISSUE THREAD

**Issue by strider72** [brave/browser-laptop#5817]
This may be plugin territory, except that I know you already have a feature that uses QR codes, so I figured it might be very easy to implement:

I'd love to have a button that shows the current URL as a QR code.  Very handy for transferring the current page to a smart phone.  (Pretty much all other browsers have a plugin that does this.)

**Comment by luixxiul** [comment]
I'm going to close this issue in favor of this topic on the community:

https://community.brave.com/t/qr-code-url-generator/7609

Let's talk about the possible options there 👍
