### ISSUE TITLE
SyntaxError: Unexpected token: name (WebTorrentRemoteClient)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5818]
**Describe the issue you encountered:**

By running a build script the following error happens and the packaged build does not start.
````
ERROR in webtorrentPage.entry.js from UglifyJs
SyntaxError: Unexpected token: name (WebTorrentRemoteClient) [./~/webtorrent-remote/client.js:10,0]
````  

From Terminal when I try to open the program, I get this.
````
Brave-MacBook-Pro:browser-laptop Suguru$ open ./Brave-darwin-x64/Brave.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/Suguru/browser-laptop/Brave-darwin-x64/Brave.app.
````

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues:

**Comment by luixxiul** [comment]
ccing @feross @dcposch for thought.

**Comment by dcposch** [comment]
Just to confirm, you ran `npm install` first, right?

Do you see a `webtorrent-remote` folder under `node_modules`?

**Comment by luixxiul** [comment]
@dcposch yes I did and I see the folder. @bsclifton has noticed the error too if I remember correctly.

**Comment by luixxiul** [comment]
FYI the issue does not happen if I run the browser via `npm run watch` and `npm start`. For me it happens on the packaged build only.

**Comment by dcposch** [comment]
Reproduced the issue. Sorry about that! Trying to fix it now.

**Comment by dcposch** [comment]
Narrowed it down a bit:

#### Works
```
CHANNEL=dev ./node_modules/.bin/webpack
```

#### Doesn't work
```
NODE_ENV=production CHANNEL=dev ./node_modules/.bin/webpack
```
...& that's what the packager script does.

**Comment by dcposch** [comment]
OK, here's what might be happening:
* When `NODE_ENV=production`, we use Uglify
* Uglify doesn't like the ES6 features, specifically `class`, that we're using in `webtorrent-remote`

**Comment by dcposch** [comment]
I'm changing `webtorrent-remote` to not use `class`. Almost done

**Comment by dcposch** [comment]
I removed all ES6 from `webtorrent-remote` and the build is working for me now. See #5847

**Comment by luixxiul** [comment]
That error disappears for me too, but `LSOpenURLsWithRole() failed with error -10810` still happens. Maybe another thing is related here, cc: @bbondy

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the bug appeared and was fixed within the same milestone.
