### ISSUE TITLE
Windows task-bar(autohide) doesn't show when brave is active

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5819]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From [Support](https://linkbubble.zendesk.com/agent/tickets/6942)
>when in brave my task-bar will not unhide when hovered ever

**Expected behavior:**
Should show the task-bar when mouse is hovered at the bottom of the screen

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 

- Brave Version:
0.12.10 

- Steps to reproduce:
    1. Enable Auto-hide from system setting
    2. Make Brave as active window
    3. Move mouse pointer to the bottom of screen, doesn't show the task-bar

- Screenshot if needed:

- Any related issues:

**Comment by kefyr** [comment]
#4473
