### ISSUE TITLE
Drag drop text selection in textbox copies text

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#582]
Step to reproduce:

1. Using the comment field on this issue add some text (e.g. testing 123 456)
2. Now select 123 and drag to the middle of Testing
3. Drop

Expected result:
    test123ing  456
Actual result
    testing 123
    123 456

**Comment by Codes4Fun** [comment]
This seems to be specific to GitHub and maybe other websites, I can reproduce the bug with GitHub on Chrome and FireFox. And drag and drop text works on Brave for other sites like:
http://www.w3schools.com/css/tryit.asp?filename=trycss_background-color_body

So I think GitHub is doing some fancy scripting.

**Comment by FrancisTurner** [comment]
Agree. Further testing suggests a werid JS issue on some sites. Closing.
