### ISSUE TITLE
Register symbol should have space after the app name in Password manager list

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5821]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
There is no space between app name and register symbol on Windows. Should look like the one on Mac

**Expected behavior:**
Register symbol should have space after the app name in Password manager list

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.10

- Screenshot if needed:
Windows 
![image](https://cloud.githubusercontent.com/assets/17010094/20574000/67b07ac4-b1aa-11e6-807d-381fd20b5cc5.png)
Mac
![image](https://cloud.githubusercontent.com/assets/17010094/20574010/71933734-b1aa-11e6-9dda-c357fbfacaa1.png)

- Any related issues:

**Comment by Liunkae** [comment]
Is it just a difference of font? The superscript appearance of the symbols is more apparent on Mac than it is on Windows.

**Comment by srirambv** [comment]
Setting font at 13px also has the same effect

![image](https://cloud.githubusercontent.com/assets/17010094/20577053/82b43154-b1b8-11e6-8b5c-5ad20dd28bd1.png)

**Comment by Liunkae** [comment]
I think the difference is the `font-family`, not the `font-size`.

**Comment by srirambv** [comment]
`font-family` is Arial through out.

**Comment by Liunkae** [comment]
Hmm, you're right. Then it must be something else.
