### ISSUE TITLE
Provide paste as plain text feature in right click context menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5822]
From [support ](https://linkbubble.zendesk.com/agent/tickets/6932)
>It would be nice to have "paste as plain text" as a right-click option  when filling in forms.

+1 from me as well

**Comment by Liunkae** [comment]
See PR #6126.

**Comment by bsclifton** [comment]
Reopening after issue discovered https://github.com/brave/browser-laptop/issues/6268#issuecomment-267887757 and revert was done with https://github.com/brave/browser-laptop/commit/345233d7b39d3f82c3725dab932c199561add5fe

We'll want to make sure the proper fix doesn't affect URL bar :smile:

**Comment by Liunkae** [comment]
New PR: #6359

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6359 which was merged into branch `0.13.1-branch`.
