### ISSUE TITLE
add comma/decimals to newtab brave info tallies 

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5827]
![image](https://cloud.githubusercontent.com/assets/13509546/20582224/20b81552-b194-11e6-9a98-b4c0f919f9ac.png)

These should display as:

1,599    |    320     |   2,490    |  2 minutes

(refer to l10n standards for numeral localization differences)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5888#issue-192155208
