### ISSUE TITLE
Pages in enteliWEB app do not always render properly

### ISSUE THREAD

**Issue by austenlennon** [brave/browser-laptop#5830]
**Did you search for similar issues before submitting this one?** yes

**Describe the issue you encountered:** page wont show data

**Expected behavior:** seeing charts 

- Platform (Win7, 8, 10? macOS? Linux distro?): MAC latest

- Brave Version:  latest and same with previous

- Steps to reproduce:
    1. go to page
    2.
    3.

- Screenshot if needed:

- Any related issues: I have pasted source code

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>enteliWEB</title>    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="distribution" content="IU" />
<meta name="content-language" content="en" />
<meta name="robots" content="noindex, nofollow" />
<meta name="copyright" content="Copyright &amp;#169; 2016 Delta Controls Inc." />    <link href="/enteliweb/images/favicon.ico" rel="SHORTCUT ICON" />
<link href="/enteliweb/resources/css/ext-all.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/index.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/Delta.Notification.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/Delta.Energy.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
        <script type="text/javascript">
      var APPLICATION_URL = "/enteliweb";
      var gLocale = "en";
      var BUILD_VERSION = "4.1.738";
    </script>
    <script type="text/javascript" src="/enteliweb/javascript/ext4/ext-all.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/jquery.js?4.1.738"></script>
<script type="text/javascript">
    //<![CDATA[
    var _tokenName = "_csrfToken";
var _token     = "jRH7XnK7eYzhtSERIzLrf4SO6jL4u15UxdBnP2jPFk";
var _isPageRdy = false;
    //]]>
</script>
<script type="text/javascript" src="/enteliweb/javascript/delta/delta_override.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/jquery.ui.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/resources/Delta.ML.en.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Ext-lang.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.DateTime.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.UI.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.UI.DSTree.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.NotificationPopup.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.NotificationBar.js?4.1.738"></script>  </head>
  <body>
    <script type="text/javascript">
//<![CDATA[/*>
</script>
<div id="index_header"  style="height:48px;">
  <table style="padding:0;margin:0;width:100%;height:100%;border-collapse:collapse;border-spacing:0;">
    <tr style="text-align: center;">
      <td style="text-align:left;padding:0">
         <div style="margin:4px 0 0 15px;" class="cns">
         <img src="/enteliweb/images/enteliweb.png?4.1.738" alt="enteliweb" style="vertical-align:middle;" />
        </div>
      </td>

      <td style="text-align:right;vertical-align:bottom;padding:0">
        <div style="margin:0 15px 15px 0;">
          <span id="label_Welcome" class="welcomeText">Welcome</span>
                    <a href="/enteliweb/admin/userdetail/user/Austen" id="loggedin_user" class="toplink"
             title="Settings" target="mainFrame">
           
          Austen</a>
          <span class="divider">|</span>
          <a href="/enteliweb/index/login" id="link_logout" class="toplink" title="Log out">
          Log out
          </a>
        </div>
      </td>

            <td style="width:50px;padding:0" class="admin_link" title="Administration" >
        <a href="/enteliweb/admin/main" title="Administration" id="link_admin"
           class="toplink" target="mainFrame">
          <img src="/enteliweb/images/gear_16.png?4.1.738" alt="Administration" class="admin_link_image"
             title="Administration" style="cursor: pointer;" />
        </a>
      </td>
      
      
      
      <td style="width:45px;padding:0" class="help_link" title="Help">
         <img src="/enteliweb/images/help_24.png?4.1.738" id="link_help" alt="Help" title="Help"
              style="cursor: pointer;" class="help_link_image"/>
      </td>
    </tr>
    <tr>
      <td colspan="4" style="background:#da2238;height:4px;padding:0"></td>
    </tr>
  </table>
</div>

<div id="pinnedNotification_div" style="height:100%;min-height:65px;"></div>

<div id="notification_overlay" style="z-index:4999">
  <div id="notification_bar" style="position:fixed;bottom:0;right:7px;"></div>
  <div id="notification_popup" style="position:fixed;bottom:45px;right:15px;width:300px;"></div>
</div>

<div id="notification_status_container" style="position:fixed; bottom:0; right:25px; z-index:5000">
  <div id="notification_status">
    <div id="notification_unseen_alarms"></div>
  </div>
</div>
  </body>
</html>

**Comment by Liunkae** [comment]
@austenlennon What is the URL for page?

**Comment by bsclifton** [comment]
I checked out the names in the above, and it seems @austenlennon is having a problem loading pages either locally or on an intranet which are using this framework:
https://www.deltacontrols.com/enteliweb/

@austenlennon can you confirm?

**Comment by austenlennon** [comment]
Yes, it is intranet.... I manage the energy of several hotels through this site... it looks like it is mostly javascript.. .

**Comment by bsclifton** [comment]
@austenlennon is there a page we can visit to reproduce the problem from our side? This will help us fix the issue :smile:

**Comment by austenlennon** [comment]
sadly no there isn't because of the security issues.... It is not a huge issue as I can still use other browsers and love Brave for the majority of my work...  but if you feel it's wroth pursuing from your end I would be happy to do what I can but I there are seven hotels in our group and if anything went wrong I would be shot at dawn..... screen shots to follow only if you wish to pursue this.....

**Comment by austenlennon** [comment]
Frame code...


<!DOCTYPE html>
<html lang="en">
  <head>

    <title></title>    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />    <link href="/enteliweb/energy/Performance/Performance.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/resources/css/ext-all.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/Delta.Energy.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/jquery/jquery-ui-smoothness.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/jquery/jquery.loadmask.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
    <style type="text/css" media="all">

</style>    <script type="text/javascript">
      var APPLICATION_URL = "/enteliweb";
      var gLocale = "en";
      var BUILD_VERSION = "4.1.738";
    </script>
    <script type="text/javascript" src="/enteliweb/javascript/jquery/jquery.js?4.1.738"></script>
<script type="text/javascript">
    //<![CDATA[
    var _tokenName = "_csrfToken";
var _token     = "0NVUzPOKlRl1XA2O6m9ilXMjYAAY7XiOe7dYZ2wzXk8";
var _isPageRdy = false;
    //]]>
</script>
<script type="text/javascript" src="/enteliweb/javascript/delta/delta_override.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/ext4/ext.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/resources/Delta.ML.en.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.DateTime.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.EnergyView.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/plugins/jquery.tools.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/jquery.ui.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/plugins/jquery.loadmask.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/plugins/jquery.cookie.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/fusion/FusionCharts.js?4.1.738"></script>  </head>
  <body>
    
<script type="text/javascript">
var webPortfolio = "Portfolio";
var webTotalMeters = "Total Meters";
var localeFormat = {"DateNoYear":"M\/d","DateLong":"h:mm:ss a","TimeShort":"h a","DecimalSymbol":".","ThousandSymbol":","};
var minWindowWidthBeforeHide = 800;

function setEnergyViewParams(params)
  {
    Delta.EnergyView.setParams(params);
  }

$(window).resize(function()
  {
    var MIN_WIDTH = 900;
    var MIN_HEIGHT = 750;

    // minimum width to fit all the meter icons plus the changePeriod buttons in the same row
    var width = ($(window).width() < MIN_WIDTH) ? MIN_WIDTH : $(window).width();
    var height = ($(window).height() < MIN_HEIGHT) ? MIN_HEIGHT : $(window).height(); // minimum height
    // 10 for margin/padding; 112 == $("#headerBar").height(), this height is 83 at
    // start; will increase after ajax updates meter name; so hard-coded the value here
    height = height - 112 - $("#utilityMenuDiv").height() - 10;

    $("#scrollContainer, .energyContainer, #headerBar, #utilityMenuDiv").width(width);
    $("#scrollContainer, .energyContainer").height(height);

    $("#meterTitle, #controlContainer").width(width - 77 - 1);

    var dateControlsObj = $("#dateControls");
    dateControlsObj.width((width - 50) / 2);
    dateControlsObj.css('left', width / 2);

    if (Delta.EnergyView.getView() == "Breakdown")
      {
        $("#scrollItems").animate({left: -1 * width + 1}, 0);
      }

    // EWEB-11277: redraw clock while resize
    for (var i in Delta.EnergyView.widgetRegistry)
      {
        var thisWidget = Delta.EnergyView.widgetRegistry[i];
        if ((thisWidget.xtype == "PerformanceBreakdown") &&
            (Delta.EnergyView.params.period == Delta.EnergyView.PERIOD_DAY))
          {
            thisWidget.renderClock(thisWidget.clockFrameTarget);
            break;
          }
      }

    // determine if showing x scroll bar
    if ($(window).width() < MIN_WIDTH)
      {
        $('body').css('overflow-x', 'auto');
      }
    else
      {
        $('body').css('overflow-x', 'hidden');
      }
  });

$(document).ready(function()
  {
    // EWEB-16805 check if it is a touch screen device, do not apply CSS hover effect on touch screen devices
    if (!("ontouchstart" in document.documentElement))
      {
        $(".delta-button").addClass("notouch");
        $(".delta-button-text").addClass("notouch");
        $(".delta-text-button").addClass("notouch");
      }

    $("#compareTypeControls").hide();

    // locale language text for jquery datepicker
    // Detail: http://docs.jquery.com/UI/Datepicker/Localization
    $.datepicker.regional[gLocale] =
      {
        clearText: TXID.WEB_CLEAR,                // Clear
        clearStatus: "",                          // Erase the current date
        closeText: TXID.WEB_CLOSE,                // Close
        closeStatus: "Close without change",      // Close without change
        prevText: "<" + TXID.WEB_PREV,            // <Prev
        prevStatus: "Show the previous month",    // Show the previous month
        nextText: TXID.WEB_NEXT + ">",            // Next>
        nextStatus: "Show the next month",        // Show the next month
        currentText: TXID.WEB_TODAY,              // Today
        currentStatus: "Show the current month",  // Show the current month
        monthNames: [
          TXID.WEB_JANUARY,
          TXID.WEB_FEBRUARY,
          TXID.WEB_MARCH,
          TXID.WEB_APRIL,
          TXID.WEB_MAY,
          TXID.WEB_JUNE,
          TXID.WEB_JULY,
          TXID.WEB_AUGUST,
          TXID.WEB_SEPTEMBER,
          TXID.WEB_OCTOBER,
          TXID.WEB_NOVEMBER,
          TXID.WEB_DECEMBER
        ],
        monthNamesShort: [
          TXID.WEB_JANUARY_ABBR,
          TXID.WEB_FEBRUARY_ABBR,
          TXID.WEB_MARCH_ABBR,
          TXID.WEB_APRIL_ABBR,
          TXID.WEB_MAY_ABBR,
          TXID.WEB_JUNE_ABBR,
          TXID.WEB_JULY_ABBR,
          TXID.WEB_AUGUST_ABBR,
          TXID.WEB_SEPTEMBER_ABBR,
          TXID.WEB_OCTOBER_ABBR,
          TXID.WEB_NOVEMBER_ABBR,
          TXID.WEB_DECEMBER_ABBR
        ],
        monthStatus: "Show a different month",    // Show a different month
        yearStatus: "Show a different year",      // Show a different year
        weekHeader: "Wk",                         // Wk
        weekStatus: "",                           // Week of the year
        dayNames: [
          TXID.WEB_SUNDAY,
          TXID.WEB_MONDAY,
          TXID.WEB_TUESDAY,
          TXID.WEB_WEDNESDAY,
          TXID.WEB_THURSDAY,
          TXID.WEB_FRIDAY,
          TXID.WEB_SATURDAY
        ],
        dayNamesShort: [
          TXID.WEB_SUN,
          TXID.WEB_MON,
          TXID.WEB_TUE,
          TXID.WEB_WED,
          TXID.WEB_THU,
          TXID.WEB_FRI,
          TXID.WEB_SAT
        ],
        //dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
        dayNamesMin: [TXID.WEB_SUN, TXID.WEB_MON, TXID.WEB_TUE, TXID.WEB_WED, TXID.WEB_THU, TXID.WEB_FRI, TXID.WEB_SAT],
        dayStatus: "Set DD as first week day",    // Set DD as first week day
        dateStatus: "Select D, M d",              // Select D, M d
        dateFormat: Delta.Format.DATE_SHORT,      // dd/mm/yy
        firstDay: 0,                              // Sun = 0, Mon = 1, ...
        initStatus: "Select a date",              // Select a date
        // True if right-to-left language, false if left-to-right
        isRTL: false
      };
    $.datepicker.setDefaults($.datepicker.regional[gLocale]);

    // force fusion charts to be javascript
    FusionCharts.setCurrentRenderer('javascript');
    $( "#portfolio-title" ).text(webPortfolio);
    // initialize energy view
    Delta.EnergyView.disableRender = true;
    $(window).resize();
    Delta.EnergyView.init({view: "Performance"});
          Delta.EnergyView.params.instance = "b467471c-93b1-11e6-9102-005056a56544";
        Delta.EnergyView.reference.units = {"Apparent_Energy_Electric":"kVAh","Apparent_Power_Electric":"kVA","Currency":"\u00a3","Energy_Electric":"kWh","Energy_Gas":"MJ","Energy_Thermal":"kWh","Flow_Mass_Steam":"kg\/h","Flow_Volume_Fuel":"l\/m","Flow_Volume_Gas":"m\u00b3\/h","Flow_Volume_Water":"m\u00b3\/h","Power_Electric":"kW","Power_Gas":"MJ\/h","Power_Thermal":"kW","Temperature":"\u00b0C","Volume_Fuel":"l","Volume_Gas":"m\u00b3","Volume_Water":"m\u00b3","Weight_Carbon":"kg","Weight_Steam":"kg"};


    // add data type buttons the view knows about
    var str = '';
    var types = Delta.EnergyView.dataTypeIndex;
    for (var idx in types)
      {
        if (types[idx] !== undefined)
          {
            str += " <div class='changeType utilityButton' title='" + types[idx].text + "'";
            str += " style='display: none;' rel='" + types[idx].id + "'>";
            str += "<span class='delta-button-text' ";
            str += "style='background: url(" + types[idx].smallIcon + ") no-repeat center center; '></span></div> ";
          }
      }
    $("#typeControls").html(str);

    Delta.EnergyView.addListener('instanceLoaded', function(args)
      {
        $(".changeType").hide();
        $(".changeType.activeButton").removeClass("activeButton");
        types = Delta.EnergyView.reference.datatypes;
        for (var idx in types)
          {
            if (types[idx] !== undefined)
              {
                var changeTypeObj = $(".changeType[rel=" + types[idx] + "]");
                changeTypeObj.show();
                if (Delta.EnergyView.params.type == types[idx])
                  {
                    changeTypeObj.addClass("activeButton");
                  }
              }
          }
      });

    // set action on clicking period button
    $(".changePeriod").click(function()
      {
        Delta.EnergyView.setParams({period: $(this).attr("rel")});
      });
    $(".changePeriod[rel=" + Delta.EnergyView.params.period + "]").addClass('activeButton');
    Delta.EnergyView.addListener('paramChanged', function(args)
      {
        if (args.paramName == 'period')
          {
            $(".changePeriod.activeButton").each(function()
              {
                $(this).removeClass("activeButton");
              });
            $(".changePeriod[rel=" + args.newValue + "]").addClass('activeButton');
          }
      });

    // set action on clicking the next/prev date buttons
    $(".shiftDate").click(function()
      {
        Delta.EnergyView.incrementDate($(this).attr("rel"));
      });

    // maps view type to tab index
    var map = [];
    var controls = [];
            map["Performance"] = 0;
        controls["Performance"] = ["view","compareType","type","period","start"];
                map["Breakdown"] = 1;
        controls["Breakdown"] = ["view","type","period","start"];
        
    // set up the view scroller
    $("#scrollContainer").scrollable(
        {
          items: "#scrollItems",
          onBeforeSeek: function(event, newIndex)
            {
              if (map[Delta.EnergyView.params.view] != newIndex)
                {
                  for (var idx in map)
                    {
                      if (map[idx] !== undefined)
                        {
                          if (map[idx] == newIndex)
                            {
                              Delta.EnergyView.setParams({view: idx});
                            }
                        }
                    }
                }
            }
        });

    // set action on clicking view selection tab
    $(".changeView").click(function()
      {
        Delta.EnergyView.setParams({view: $(this).attr("rel")});
      });
    $(".changeView[rel=" + Delta.EnergyView.params.view + "]").addClass('activeButton');
    Delta.EnergyView.addListener('paramChanged', function(args)
      {
        if (args.paramName == 'view')
          {
            // update selected view button
            $(".changeView.activeButton").each(function()
              {
                $(this).removeClass("activeButton");
              });
            $(".changeView[rel=" + args.newValue + "]").addClass('activeButton');

            // scroll the view pane
            var api = $("#scrollContainer").data("scrollable");
            if (map[args.newValue] !== undefined)
              {
                var diff = Math.abs(map[args.newValue] - api.getIndex());
                api.seekTo(map[args.newValue], 400 * ((diff > 0) ? diff : 1));
              }

            // update the visible controls
            var idx;
            var search = ['view', 'compareType', 'type', 'period', 'start'];
            if (controls[args.newValue] !== undefined)
              {
                for (idx in controls[args.newValue])
                  {
                    var control = controls[args.newValue][idx];
                    if (control !== undefined)
                      {
                        var idy = $.inArray(control, search);
                        if (idy > -1)
                          {
                            search.splice(idy, 1);
                            $("#" + control + "Controls").show();
                          }
                      }
                  }
              }
            for (idx in search)
              {
                if (search[idx] !== undefined)
                  {
                    $("#" + search[idx] + "Controls").hide();
                  }
              }
          }
      });

    // set action on clicking comparison selection tab
    $(".changeCompare").click(function()
      {
        Delta.EnergyView.setParams({compareType: $(this).attr("rel")});
      });
    $(".changeCompare[rel=" + Delta.EnergyView.params.compareType + "]").addClass('activeButton');
    Delta.EnergyView.addListener('paramChanged', function(args)
      {
        if (args.paramName == 'compareType')
          {
            // update selected view button
            $(".changeCompare.activeButton").each(function()
              {
                $(this).removeClass("activeButton");
              });
            $(".changeCompare[rel=" + args.newValue + "]").addClass('activeButton');
          }
      });

    // set action on clicking type selection tab
    $(".changeType").click(function()
      {
        Delta.EnergyView.setParams({type: $(this).attr("rel")});
      });
    Delta.EnergyView.addListener('paramChanged', function(args)
      {
        if (args.paramName == 'type')
          {
            $(".changeType.activeButton").each(function()
              {
                $(this).removeClass("activeButton");
              });
            $(".changeType[rel=" + args.newValue + "]").addClass('activeButton');
          }
      });

    // render date picker input
    var datePickerObj = $("#datePicker");
    datePickerObj.datepicker(
        {
          dateFormat: 'yy-mm-dd',
          numberOfMonths: 3,
          showCurrentAtPos:2,
          onSelect: function(dateText, inst)
            {
              var newDate = dateText.split('-');
              if (newDate.length == 3)
                {
                  Delta.EnergyView.setParams({start: new Date(newDate[0], (newDate[1] - 1), newDate[2], 0, 0, 0, 0)});
                }
            }
        });
    datePickerObj.val(Delta.DateTime.formatDate(Delta.EnergyView.params.start, 'Y-MM-dd'));
    Delta.EnergyView.addListener('paramChanged', function(args)
      {
        if (args.paramName == 'start')
          {
            var currentDate = $.cookie('delta-energy-start');
            if (isNaN(currentDate))
              {
                currentDate = new Date();
              }
            else
              {
                currentDate = new Date(currentDate * 1);
              }
              $("#datePicker").val(Delta.DateTime.formatDate(currentDate, 'Y-MM-dd'));
          }
      });

    // change title/icon when instance changes, and highlight parent frame tree
    Delta.EnergyView.addListener('instanceLoaded', function(args)
      {
        $("#meterTitle").text(Delta.EnergyView.reference.instanceName);
        $("#meterIcon").attr("class", Delta.EnergyView.reference.instanceClass);
        if (typeof window.parent.refreshEnergyTree == 'function')
          {
            window.parent.refreshEnergyTree(Delta.EnergyView.params.instance);
          }
      });

    // enable UI and set the view
    Delta.EnergyView.disableRender = false;
    Delta.EnergyView.setView("Performance");
  });
</script>
<div id="energy">
  <div id="portfolio">
    <div id="portfolio-headerBar">
      <span id="portfolio-headerIcon" class="folderIcon-white-bg"></span>
      <div id="portfolio-title"></div>
    </div>
    <div id="portfolioContent"></div>
  </div>
  <div id="headerBar" style="position:relative;">
    <div id="energyTitle">
      <img id="energy_icon" src='/enteliweb/images/energy/energy_24.png?4.1.738'>
      <span id="energyTitle_Text">Energy</span>
    </div>

    <div id="meterTitle"></div>

    <div id="green-background">
      <div class="controlContainer" style="width: 100%;">
        <span id="meterIcon"></span>
        <div id="viewControls" style="float: left; clear: none;">
                      <div style="clear: none; float: left;" class='changeView delta-text-button'
                 title="Performance" rel='Performance'>
              <span class='delta-text-button-text'>Performance</span>
            </div>
                          <div id="compareTypeControls" style="clear: none; float: left;">
                <div class='changeCompare delta-text-button' title="No Comparison" rel='none'>
                  <span class='delta-text-button-text'>No Comparison</span>
                </div>
                <div class='changeCompare delta-text-button'
                     title="Baseline Comparison" rel='baseline'>
                  <span class='delta-text-button-text'>Baseline Comparison</span>
                </div>
                <div class='changeCompare delta-text-button' title="Target Comparison" rel='target'>
                  <span class='delta-text-button-text'>Target Comparison</span>
                </div>
              </div>
                                  <div style="clear: none; float: left;" class='changeView delta-text-button'
                 title="Breakdown" rel='Breakdown'>
              <span class='delta-text-button-text'>Breakdown</span>
            </div>
                              </div>
      </div>
    </div>
  </div>

  <div id="utilityMenuDiv" style="line-height:30px; position: relative; padding: 3px 0;
       background-color:#e2e2e2; border-bottom:1px solid #bdbdbd;">
    <span style="vertical-align: middle; margin:0 24px; text-align: right; font-weight: bold;">
      Utilities:
    </span>
    <div id="typeControls" style="clear: both; display:inline-block; vertical-align: middle;"></div>

    
    <div id="dateControls" style="clear: none; position:absolute; top:46px; z-index:50;">
      <div style=" float:left; margin-left: 20px;">
        <div class="shiftDate delta-button" rel="-1"><span class='delta-button-text'>&laquo;</span></div>
        <div class="date-picker-container"><input id="datePicker" type="text" readonly="readonly" /></div>
        <div class="shiftDate delta-button" rel="1"><span class='delta-button-text'>&raquo;</span></div>
      </div>
      <div style=" float:right; margin-right: 20px;">
        <div class="changePeriod delta-button" rel="Day"><span class='delta-button-text'>D</span></div>
        <div class="changePeriod delta-button" rel="Week"><span class='delta-button-text'>W</span></div>
        <div class="changePeriod delta-button" rel="Month"><span class='delta-button-text'>M</span></div>
        <div class="changePeriod delta-button" style="margin-right: 10px;" rel="Year">
          <span class='delta-button-text'>Y</span>
        </div>
      </div>
    </div>
  </div>

  <div id="scrollContainer">
    <div id="scrollItems">
              <div id="energy_container_Performance" class="energyContainer" rel="Performance"></div>
              <div id="energy_container_Breakdown" class="energyContainer" rel="Breakdown"></div>
          </div>
  </div>
</div>
  </body>
</html>

**Comment by austenlennon** [comment]
Page code...

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>enteliWEB</title>    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="distribution" content="IU" />
<meta name="content-language" content="en" />
<meta name="robots" content="noindex, nofollow" />
<meta name="copyright" content="Copyright &amp;#169; 2016 Delta Controls Inc." />    <link href="/enteliweb/images/favicon.ico" rel="SHORTCUT ICON" />
<link href="/enteliweb/resources/css/ext-all.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/index.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/Delta.Notification.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
<link href="/enteliweb/style/delta/Delta.Energy.css?4.1.738" media="all" rel="stylesheet" type="text/css" />
        <script type="text/javascript">
      var APPLICATION_URL = "/enteliweb";
      var gLocale = "en";
      var BUILD_VERSION = "4.1.738";
    </script>
    <script type="text/javascript" src="/enteliweb/javascript/ext4/ext-all.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/jquery.js?4.1.738"></script>
<script type="text/javascript">
    //<![CDATA[
    var _tokenName = "_csrfToken";
var _token     = "0NVUzPOKlRl1XA2O6m9ilXMjYAAY7XiOe7dYZ2wzXk8";
var _isPageRdy = false;
    //]]>
</script>
<script type="text/javascript" src="/enteliweb/javascript/delta/delta_override.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/jquery/jquery.ui.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/resources/Delta.ML.en.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Ext-lang.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.DateTime.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.UI.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.UI.DSTree.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.NotificationPopup.js?4.1.738"></script>
<script type="text/javascript" src="/enteliweb/javascript/delta/Delta.NotificationBar.js?4.1.738"></script>  </head>
  <body>
    <script type="text/javascript">
//<![CDATA[/*>
</script>
<div id="index_header"  style="height:48px;">
  <table style="padding:0;margin:0;width:100%;height:100%;border-collapse:collapse;border-spacing:0;">
    <tr style="text-align: center;">
      <td style="text-align:left;padding:0">
         <div style="margin:4px 0 0 15px;" class="cns">
         <img src="/enteliweb/images/enteliweb.png?4.1.738" alt="enteliweb" style="vertical-align:middle;" />
        </div>
      </td>

      <td style="text-align:right;vertical-align:bottom;padding:0">
        <div style="margin:0 15px 15px 0;">
          <span id="label_Welcome" class="welcomeText">Welcome</span>
                    <a href="/enteliweb/admin/userdetail/user/Austen" id="loggedin_user" class="toplink"
             title="Settings" target="mainFrame">
           
          Austen</a>
          <span class="divider">|</span>
          <a href="/enteliweb/index/login" id="link_logout" class="toplink" title="Log out">
          Log out
          </a>
        </div>
      </td>

            <td style="width:50px;padding:0" class="admin_link" title="Administration" >
        <a href="/enteliweb/admin/main" title="Administration" id="link_admin"
           class="toplink" target="mainFrame">
          <img src="/enteliweb/images/gear_16.png?4.1.738" alt="Administration" class="admin_link_image"
             title="Administration" style="cursor: pointer;" />
        </a>
      </td>
      
      
      
      <td style="width:45px;padding:0" class="help_link" title="Help">
         <img src="/enteliweb/images/help_24.png?4.1.738" id="link_help" alt="Help" title="Help"
              style="cursor: pointer;" class="help_link_image"/>
      </td>
    </tr>
    <tr>
      <td colspan="4" style="background:#da2238;height:4px;padding:0"></td>
    </tr>
  </table>
</div>

<div id="pinnedNotification_div" style="height:100%;min-height:65px;"></div>


<div id="notification_overlay" style="z-index:4999">
  <div id="notification_bar" style="position:fixed;bottom:0;right:7px;"></div>
  <div id="notification_popup" style="position:fixed;bottom:45px;right:15px;width:300px;"></div>
</div>


<div id="notification_status_container" style="position:fixed; bottom:0; right:25px; z-index:5000">
  <div id="notification_status">
    <div id="notification_unseen_alarms"></div>
  </div>
</div>
  </body>
</html>

**Comment by austenlennon** [comment]
screen shot of page.... 
![screen shot 2](https://cloud.githubusercontent.com/assets/23722967/20859970/6e86ed20-b965-11e6-82b0-357ee77a3d7a.png)

**Comment by austenlennon** [comment]
but really... it is not critical....

**Comment by austenlennon** [comment]
Finally.... I just tried to log in again to my page and it does everything it needs to do... it logs in fine... but it shows a blank page.... when I look at the page source everything is identical to the page source from Chrome.... so it is loading ok.... just not displaying   
![screen shot](https://cloud.githubusercontent.com/assets/23722967/20860127/b9220358-b968-11e6-96be-82f289b7449e.png)

**Comment by bsclifton** [comment]
@austenlennon thanks for the super detailed info! 😄 This is definitely useful. Please be sure to edit the pictures if any sensitive info is showing

Here's something you can try:
When you're visiting and the page is blank, please try to click the lion head in the top right. When that comes up, you can try to turn shields off. It'll only affect the current domain you're visiting, not every site. Let us know if this helps

**Comment by austenlennon** [comment]
:-) first thing I tried....

**Comment by Liunkae** [comment]
@austenlennon On pages that are blank, could you please open the web inspector (`Menu > View > Toggle Developer Tools` or  <kbd>Cmd+Shift+I</kbd>) and take a screenshot of the console? The console should show some warnings and/or errors.

**Comment by austenlennon** [comment]
Thanks  Liunkae :-) first thing I tried....

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-enteliweb-app/10678

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
