### ISSUE TITLE
AWS Registration Portal hangs

### ISSUE THREAD

**Issue by nicdoye** [brave/browser-laptop#5832]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

Tested with *both* shields up and shields down

The [contact information form](https://portal.aws.amazon.com/billing/signup?redirect_url=https%3A%2F%2Faws.amazon.com%2Fregistration-confirmation#/account), two pages after [Amazon Registration Portal](https://portal.aws.amazon.com/gp/aws/developer/registration/index.html) shows the javascript "spinner" forever.
 
**Expected behavior:**

Spinner should disappear and let me enter details.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS 10.12.1

- Brave Version:

0.12.10

- Steps to reproduce:
    1. Visit [Amazon Registration Portal](https://portal.aws.amazon.com/gp/aws/developer/registration/index.html)  and register as a new user. An example.com email address will work at this stage.
    2. Fill in Name, password etc. on the next page
    3. The third page (contact information) sits there with a JavaScript Spinner.

- Screenshot if needed:

![aws](https://cloud.githubusercontent.com/assets/59195/20603922/bad9ee90-b25b-11e6-8cc9-803f1a0a82e3.png)

- Any related issues:

**Comment by Liunkae** [comment]
I cannot reproduce with Brave 0.12.10 on macOS 10.12.x. Default shield settings, no password manager, no autofill, and no Pocket.
![image](https://cloud.githubusercontent.com/assets/19424103/20642074/aa15ee76-b3cb-11e6-8233-537871035554.png)

**Comment by nicdoye** [comment]
Thanks @liunkae - same browser and OS - I'll put it down to Amazon or a proxy.
