### ISSUE TITLE
Arithmetic division in the address bar incorrectly interpreted as an IP address

### ISSUE THREAD

**Issue by swiftcoder** [brave/browser-laptop#5834]
Typing '35*7' into the address bar is correctly translated to 'https://www.google.com/search?q=35*7', yielding the desired result.

However, typing '35/7' is incorrectly translated to 'http://0.0.0.35/7', yielding the error message "The IP address is unreachable. This usually means that there is no route to the specified host or network".

As a long time Chrome user, I'm very used to treating my browser as a calculator, and this is a repeated source of friction since using Brave.

#5627 #4761

**Comment by Liunkae** [comment]
Reproduced. There are two workarounds:
1. Put spaces around the slash. `35 / 7` works for me.
2. Add the engine go key before the query. `:g 35/7` also works for me.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bug-when-doing-math-calculations-in-address-bar/6799

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/solving-simple-equations-in-navigation-bar-automatically/16180/2

**Comment by rebron** [comment]
Closing. wontfix here but fixed with brave-core.
