### ISSUE TITLE
"npm install" fails on Fedora 25 and Rawhide

### ISSUE THREAD

**Issue by msiyer** [brave/browser-laptop#5836]
**Did you search for similar issues before submitting this one?**
Found similar issue in Windows 10 filed in April 2016

**Describe the issue you encountered:**
Cannot build brave. "npm install" falis:
```
209165 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
209166 verbose pkgid abp-filter-parser-cpp@1.2.10
209167 verbose cwd /home/msiyer/workspace/browser-laptop
209168 error Linux 4.8.8-300.fc25.x86_64
209169 error argv "/usr/bin/node" "/usr/bin/npm" "install"
209170 error node v6.9.1
209171 error npm  v3.10.8
209172 error code ELIFECYCLE
209173 error abp-filter-parser-cpp@1.2.10 preinstall: `npm install bloom-filter-cpp && npm install hashset-cpp`
209173 error Exit status 1
209174 error Failed at the abp-filter-parser-cpp@1.2.10 preinstall script 'npm install bloom-filter-cpp && npm install hashset-cpp'.
209174 error Make sure you have the latest version of node.js and npm installed.
209174 error If you do, this is most likely a problem with the abp-filter-parser-cpp package,
209174 error not with npm itself.
209174 error Tell the author that this fails on your system:
209174 error     npm install bloom-filter-cpp && npm install hashset-cpp
209174 error You can get information on how to open an issue for this project with:
209174 error     npm bugs abp-filter-parser-cpp
209174 error Or if that isn't available, you can get their info via:
209174 error     npm owner ls abp-filter-parser-cpp
209174 error There is likely additional logging output above.
209175 verbose exit [ 1, true ]
```

- Platform:
Fedora 25 and Fedora Rawhide
node v6.9.1
npm  v3.10.8

- Brave Version:
n/a

Relevant log:
[npm-debug.log.txt](https://github.com/brave/browser-laptop/files/613087/npm-debug.log.txt)

**Comment by luixxiul** [comment]
Hi, did you follow the instruction on README.md?

````
sudo npm install -g node-gyp@3.3.1
dnf install libgnome-keyring-devel rpm-build
````

**Comment by msiyer** [comment]
Thanks @luixxiul. Do not know how I missed the node-gyp instruction. Installed node-gyp and the build still failed. This time it was:

> g++ command not found

I had installed gcc via thinking this is the compiler collection and will pull in C++ compiler too:

> dnf install gcc

Apparently, this was not enough. I had to install:

> dnf install gcc-c++

The best thing to do on Fedora before compiling brave is:

> dnf group install "Development Tools" "C Development Tools and Libraries" && dnf install kernel-devel

The above will pull in everything required for C, C++ development.

**Comment by luixxiul** [comment]
Lovely! Didn't you try `dnf install libgnome-keyring-devel rpm-build`? If did, I'd edit the information on README.md based on your solution.

**Comment by msiyer** [comment]
The only instruction I missed was related to node-gyp. Everything else was done. That is, I had executed the command:
`dnf install libgnome-keyring-devel rpm-build`

**Comment by bsclifton** [comment]
@msiyer I'm going to close this issue since it sounds like you're good to go :smile: 

If you're interested, you could create a new page in our Wiki with steps / tips for setting up on Linux:
https://github.com/brave/browser-laptop/wiki

If you were up for that, you could use the Windows page as an example:
https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide
