### ISSUE TITLE
Hide the menu bar by default set true - start brave again - menu bar is visible

### ISSUE THREAD

**Issue by miami007** [brave/browser-laptop#5838]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Sh1d0w** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/5086

Unfortunately it seems won't be fixed anytime soon ...

**Comment by bsclifton** [comment]
@miami007 what OS are you on? If you are using Linux, then @Sh1d0w is correct; this is a duplicate

However, if you're on Windows or macOS, I'd love to know more please

**Comment by miami007** [comment]
Hi
i am using linux mint
