### ISSUE TITLE
Brave does not interact well with xfce window manager

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#5842]
User from support mentioned that we don't work well with xfce window manager.
https://linkbubble.zendesk.com/agent/tickets/5854

**Comment by Liunkae** [comment]
Related: #3180

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/does-brave-not-run-on-linux-mint-with-xfce/10420

Let's reopen if someone tells us that the issue is reproducible 👍
