### ISSUE TITLE
New version+Dashlane+Twitter login troubles

### ISSUE THREAD

**Issue by codrus** [brave/browser-laptop#5843]
OS: Windows 10

After upgrading to 0.12.9 I've had troubles auto-logging into twitter w/ Dashlane. Before it was smooth. Now I have to try over and over, usually closing the tab, opening a new one and trying again.

Dash submits the info into the fields but when the next page loads it is the same page. Just repeats, login goes nowhere.

**Comment by Liunkae** [comment]
Unfortunately, there are a number of issues with Twitter at the moment (#4670, #4758, #4877, #5748). Rest assured, the root problem is being investigated at #4877 and will hopefully be resolved in the next version or two.

**Comment by codrus** [comment]
UPDATE - More info on this one: It seems to occur when I click on a shared twitter post in some article or elsewhere. It then takes you to twitter and asks you to log in and that's when my issue above seems to happen.

**Comment by jonathansampson** [comment]
Possibly related to: https://github.com/brave/browser-laptop/issues/4877

@codrus Is Dashlane populating the form fields? If so, I believe this issue was with internal cache, rather than Twitter or Dashlane. Not your cache, by the way, but ours.

Twitter login issues appear to be resolved as of Preview Build 7 of Brave 0.13.0.

**Comment by mkb** [comment]
I'm seeing this in 0.12.15 with two Twitter accounts on two different Macs. I can log into those accounts with other browsers, just not Brave. Sounds like y'all are on top of this one but let me know if I can provide additional diagnostic info.

**Comment by mkb** [comment]
Fixed for me in 0.13.0. Thanks!

**Comment by Liunkae** [comment]
Closing as fixed in 0.13.0.
