### ISSUE TITLE
do not see poll results after voting in twitter

### ISSUE THREAD

**Issue by len5742** [brave/browser-laptop#5844]
**Did you search for similar issues before submitting this one?**
no, not immediately apparent how to do that from list of bug reports screen
**Describe the issue you encountered:**
Click to vote in poll, screen just flashes, no vote seems to be recorded. Normally, you see vote count status after voting.  Works fine in Chrome.
**Expected behavior:**
Should record vote, see results
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version:
0.12.10
- Steps to reproduce:
    1. find a poll in twitter
    2. vote
    3.

- Screenshot if needed:

- Any related issues:

**Comment by len5742** [comment]
OK now I see this has already been reported.

**Comment by bsclifton** [comment]
Here's the issue it was a duplicate of: https://github.com/brave/browser-laptop/issues/4670
