### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810 on the packaged build

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5849]
From Terminal when I try to open the packaged build, I get this.
````
Brave-MacBook-Pro:browser-laptop Suguru$ open ./Brave-darwin-x64/Brave.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/Suguru/browser-laptop/Brave-darwin-x64/Brave.app.
````

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues: #5818

CC @dcposch

**Comment by dcposch** [comment]
What does `LSOpenURLsWithRole` do? How does it related to #5818 ?

**Comment by dcposch** [comment]
Hmm. http://apple.stackexchange.com/questions/181026/lsopenurlswithrole-failed-with-error-10810-cant-open-install-os-x-yosemite

**Comment by luixxiul** [comment]
I haven't see the error until I packaged the build after commits related with the webtorrent were merged but I am not sure if it has nothing to do with them.

**Comment by luixxiul** [comment]
Just now I confirmed that packaged build based on 8b6dada29bd4d74f556268e18e54631d00b59c41 ran, which is right before the first commit on Webtorrent eb004bd573c8644836c315493a3a9467f2d68f5c was merged. /cc: @feross

**Comment by luixxiul** [comment]
Also I found that the packaged build based on d14c778 ran. https://github.com/brave/browser-laptop/commit/4619405accb9e49683281c1136ea6759b92c343a "move webtorrent to the browser process" seems to break the build.

**Comment by dcposch** [comment]
Thanks for bisecting. I'll experiment with it today and see if I can find out why.

**Comment by dcposch** [comment]
Still don't know why.

```
CHANNEL=dev npm run build-packgage
cd Brave-darwin-x64
open Brave.app
```

Works with https://github.com/brave/browser-laptop/commit/d14c778d6dfde2335448a50749c6923ca0c006e2

Fails on commits after that. Error message:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Users/dc/code/browser-laptop/Brave-darwin-x64/Brave.app.
```

**Comment by dcposch** [comment]
it works if is remove a few lines from `browser/webtorrent.js` so that it no longer loads `WebTorrentRemoteServer`, while leaving everything else the same

now testing what happens when I lazy load WebTorrentRemoteServer instead of `require()`ing it right away

**Comment by dcposch** [comment]
### found the crash

instead of running `open Brave.app`, go to `Brave-darwin-x64/Brave.app/Contents/MacOS` and then run `./Brave`. that way, you get console output from the browser process.

here's the crash when trying to `require('webtorrent')` in the packaged app:

```
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module 'speedometer'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/dc/code/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dc/code/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar/node_modules/webtorrent-remote/node_modules/webtorrent/index.js:19:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
/Users/dc/code/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2.js:18
if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="func

Error: Cannot find module 'speedometer'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/dc/code/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dc/code/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar/node_modules/webtorrent-remote/node_modules/webtorrent/index.js:19:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by dcposch** [comment]
so `browser-laptop/node_modules` looks normal and contains `speedometer` as expected.

`browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar.unpacked` (and probably `app.asar` as well) contains `node_modules` with just one entry: `node-anonize2-relic-emscripten`

@feross @bbondy @diracdeltas

**Comment by dcposch** [comment]
### fix

manually adding `speedometer` to `app.asar/node_modules` fixes it.

first navigate to `Brave-darwin-x64/Brave.app/Contents`, then:

```
npm install asar -g
asar e Resources/app.asar derp
cp -r cp -r ../../../node_modules/webtorrent-remote/node_modules/speedometer derp/node_modules/
asar pack derp Resources/app.asar
./MacOS/Brave
```

so we have to fix the packaging script that creates `app.asar`. my guess is that it's currently not including transitive dependencies correctly

**Comment by dcposch** [comment]
### real fix

https://github.com/brave/browser-laptop/blob/2399c725c1a344f3445d1a113841f103471f9676/tools/lib/ignoredPaths.js#L16

derp

PR coming soon

**Comment by luixxiul** [comment]
I labelled this with `QA/no qa needed` as this fixed the issue for a packaged build
