### ISSUE TITLE
if you delete the url from the address bar, you cannot reload the page

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#585]
I found myself unable to reload a page when I discovered I'd accidentally deleted the address from the address bar. I should still be able to reload a page, even if I've deleted the address from the address bar.

**Comment by psimyn** [comment]
I can't reproduce this. Do you mean you click the address bar and delete the text, then reload doesn't work?

**Comment by asadotzler** [comment]
I can no longer reproduce.
