### ISSUE TITLE
Bookmarks Completely Disappeared 

### ISSUE THREAD

**Issue by busa131300r** [brave/browser-laptop#5852]
Searched for similar issue; could not locate.

**Describe the issue you encountered:** - Complete loss of ALL bookmarks. I now have "none". 

**Expected behavior:** - All bookmarks remain...

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 / 64but

- Brave Version:

Brave	0.12.10
Muon	1.4.26
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64

- Steps to reproduce:
    1. Unknown. Brave "updated" recently, was closed yesterday, and reopened today. All bookmarks are gone...
    2.
    3.

- Screenshot if needed: Two attached...
![2016-11-26_12-53-27](https://cloud.githubusercontent.com/assets/24193173/20642269/d55da1b6-b3d8-11e6-80e0-8439b7d0be47.png)
![2016-11-26_12-53-55](https://cloud.githubusercontent.com/assets/24193173/20642270/e018faba-b3d8-11e6-8664-ef1af5286727.png)

- Any related issues:

**Comment by bsclifton** [comment]
@busa131300r can you try a few things for me?
First, quit Brave and make sure all instances of it are closed (if you know how, you can check task manager to make sure no Brave.exe are running)

Then push Windows key + R to bring up run prompt and then run:
%appdata%\brave

You should then see your local files. The session files have the format of "session-store-".  Look for others with a similar name which are bigger in size. Backups are saved every so often, including when quitting. You should be able to rename the file you want to restore as "session-store-1"

Please let me know how this works for you. I would advise not to delete files... but if needed, rename them or put into a folder

**Comment by bsclifton** [comment]
@busa131300r do you have an update? I am hoping the above steps worked for you, because there are always backup copies saved.  Please let me know!  Thanks :smile:

**Comment by bsclifton** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/5512.  If the steps above don't work, please re-open the issue and we'll figure out next steps.  Thanks! :smile:
