### ISSUE TITLE
Brave does not block "native ads" such as promoted tweets by twitter

### ISSUE THREAD

**Issue by rainulf** [brave/browser-laptop#5853]
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**

Twitter still shows ads (promoted tweets and trends). According to @BrendanEich in #527, blocking native ads are not in development yet.

> We aren't (yet) taking on "native ads" in Twitter, Facebook, or other such apps.

**Expected behavior:**

All kinds of ads should be blocked.

**Platform:**

Tested in Windows 10

**Brave Version:**

0.12.10

**Steps to reproduce:**

No steps needed. Adblock is enabled by default as of Brave 0.12.10.

**Any related issues:**

#527

**Comment by luixxiul** [comment]
Closing in favor of #527
