### ISSUE TITLE
Some favicons on new tab page look strange

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5858]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**

@bsclifton @cezaraugusto I'm not sure if you already have an issue for this, I checked but couldn't find one. On my new tab page, the Twitter favicon is blue on green instead of blue on white.

**Expected behavior:**
It should be blue on white.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.10

- Steps to reproduce:
    1. Open Brave
    2. Visit Twitter (enough times for it to show up on your new tab page)
    3. Open a new tab

- Screenshot if needed:
<img width="133" alt="screen shot 2016-11-27 at 12 03 14 am" src="https://cloud.githubusercontent.com/assets/490294/20646697/2c672610-b435-11e6-80a9-1232adf40eb5.png">

- Any related issues:

**Comment by jkup** [comment]
Is this maybe fixed on master? Now I'm seeing it correctly!
<img width="177" alt="screen shot 2016-11-27 at 1 30 34 pm" src="https://cloud.githubusercontent.com/assets/490294/20651991/c13b6e20-b4a5-11e6-889b-3668b513e562.png">

**Comment by cezaraugusto** [comment]
For tiles' background we rely on site's themeColor. I think that at some point Twitter decided to output `themeColor` based on account colors (like, mine was black, Brave was orange, etc). But it seems to be removed now.

**Comment by jkup** [comment]
@cezaraugusto ahhh that's good to know! Thanks for the follow-up, I'll close the issue!

**Comment by bradleyrichter** [comment]
Ideally we could find some good code to get a dominant color from the site favicon. This may be more reliable for the tiles. Safari uses this.

The next best thing is to make a table of favicons and tile colors for the big sites.
