### ISSUE TITLE
content doesn't fill fast enough when you resize a browser window horizontally

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#586]
Load a site like slashdot.org. Not too complex. Resize the window horizontally and notice the content doesn't fill in very quickly. It's very easy on Mac and Windows, even on relatively new equipment, to outrace the content leaving a blank area before the content races to catch up with the window edge. It feels very janky, laggy, bad. Video attached.

[refill.mov.zip](https://github.com/brave/browser-laptop/files/115136/refill.mov.zip)

also on youtube https://youtu.be/gnE1--66q-I

**Comment by bbondy** [comment]
Just noting for now, a big part of this is that there's an app state change that happens on resize here `js/stores/appStore.js`:

```javascript
  mainWindow.on('resize', function (evt) {
    // the default window size is whatever the last window resize was
    AppActions.setDefaultWindowSize(evt.sender.getSize())
  })
```

That triggers the app state to be communicated to the window over IPC.  We should look to minimize app state transfer for things that only matter to the app itself, like the default window position size.

**Comment by bbondy** [comment]
Several UI snappy fixes in 0.7.14. 
This is improved with 0.7.14 but not good enough to close this yet.

**Comment by poiru** [comment]
Much of this is probably due to `<webview>` being slow to resize. See https://bugs.chromium.org/p/chromium/issues/detail?id=639867

@bbondy @bridiver Have you considered patching libchromiumcontent to work around this?

**Comment by bridiver** [comment]
right now it's low on the priority list, but at some point after 1.0 we'll take a closer look. I dug through the code a little bit and it's certainly not a trivial fix

**Comment by poiru** [comment]
FYI, electron/electron#7658 can be used to make resizing webviews faster (cc @bridiver, @bsclifton).

**Comment by bridiver** [comment]
I'll take a look. Thanks!

**Comment by bridiver** [comment]
lgtm! I'll cherry-pick it when I'm done with the chromium 54 update

**Comment by bsclifton** [comment]
@bridiver nice :smile: I created https://github.com/brave/electron/issues/78 for ya

If you get a sec, check out the fix I did event-wise in https://github.com/brave/browser-laptop/pull/5102

**Comment by bridiver** [comment]
was #5102 supposed to close this?

**Comment by bsclifton** [comment]
@bridiver yes- the performance is noticeably better :smile:

**Comment by bridiver** [comment]
ok, but I assume we still want to pull in the upstream change?

**Comment by bsclifton** [comment]
@bridiver yup!  and that is captured with https://github.com/brave/electron/issues/78

**Comment by srirambv** [comment]
Content doesn't fill up until the window is moved to a certain length (Visible on slashdot.org site, doesn't fill until its stopped)

![586](https://cloud.githubusercontent.com/assets/17010094/19779382/c88dfcf0-9c78-11e6-82e4-375f256485e2.gif)

**Comment by bbondy** [comment]
Sorry this was mistakenly closed, it's more about content not filling in the resizing window fast enough.

**Comment by bsclifton** [comment]
With https://github.com/brave/electron/issues/78 closed, we should retest this starting with 0.13.0 :smile:

**Comment by bridiver** [comment]
it was closed because the patch no longer applied, but I have no idea if the behavior has changed or not

**Comment by bsclifton** [comment]
Gave it a go, performance didn't seem any better.  Was worth a shot :smile: Removing milestone

**Comment by bridiver** [comment]
a similar change may or may not work for the chromium webview

**Comment by bradleyrichter** [comment]
This was getting better through 0.12.5 and now became worse again with 0.13.0 based on my personal mac OS experience.

**Comment by bridiver** [comment]
@bradleyrichter in 0.13 we switched from the electron webview to the chrome webview and that may have had an impact because the resizing code is different

**Comment by bsclifton** [comment]
This issue will be solved when we move to the Chromium UI (Brave Core)
