### ISSUE TITLE
Import browser data switches misaligned

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5860]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
On the Import Browser Data dialog the switches are not left-aligned.

**Expected behavior:**
The four switches (pictured) should all be left aligned on the dialog.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
master

- Steps to reproduce:
    1. Open Brave
    2. Go to Preferences
    3. Click "Import now..."

- Screenshot if needed:
<img width="403" alt="screen shot 2016-11-27 at 1 41 06 pm" src="https://cloud.githubusercontent.com/assets/490294/20652062/63f7851c-b4a7-11e6-997e-3c139486c816.png">

- Any related issues:

**Comment by bsclifton** [comment]
There was a reason for this... but I agree, it looks weird

cc: @bradleyrichter @darkdh

**Comment by darkdh** [comment]
It was intended to indicate merge into toolbar is the sub option of bookmark. And it can only be toggled when bookmark option is active.

**Comment by bradleyrichter** [comment]
It would help to bump the slider to the right about 5px.

**Comment by jkup** [comment]
Oh I see. Yeah maybe just pushing it a bit further to the right like @bradleyrichter suggested will help? I'll give it a try and post a screenshot! :)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5863#issue-191901832
