### ISSUE TITLE
Imgur album previews on Reddit don't work

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#5861]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

When I try to preview an imgur album on Reddit, it doesn't render correctly. See attached screenshot.

**Expected behavior:**

The preview should render correctly.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Both Windows 10 and OS X 10.11.6

- Brave Version:

0.12.10

- Steps to reproduce:
    1. Go to https://www.reddit.com/r/ProgrammerHumor/comments/5f6cv9/what_is_a_breakpoint/
    2. Click the button/icon to preview the album inline.

- Screenshot if needed:

![brave-reddit-imgur-album-problem](https://cloud.githubusercontent.com/assets/133786/20652323/c1ef8c22-b4bc-11e6-9b31-dcbca6f3eceb.PNG)

#1268

**Comment by jkup** [comment]
Notes: It does load with shields down and here are the errors I see in the console with shields up.

<img width="1088" alt="screen shot 2016-11-27 at 5 34 32 pm" src="https://cloud.githubusercontent.com/assets/490294/20653816/d68c2c20-b4c7-11e6-8567-f8c48be0fb1f.png">

**Comment by jonathansampson** [comment]
Issue is alleviated by _Allow[ing] all Cookies_ on the reddit.com domain.

**Comment by bsclifton** [comment]
@bbondy @snyderp just noticed this was closed (browser-laptop) via a Brave Core commit. I'll label it with `fixed-with-brave-core`, but wanted to give a heads up in case other issues are being closed too
