### ISSUE TITLE
Favicon of trakt.tv on new tab page

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#5868]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
The favicon blends in with the red background 
**Expected behavior:**
favicon of trakt.tv should be recognizable 
- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version: 0.12.10

- Screenshot if needed:

The right most red one is trakt.tv
<img width="532" alt="screen shot 2016-11-28 at 16 03 52" src="https://cloud.githubusercontent.com/assets/11330831/20660591/71321a92-b585-11e6-803a-37f6bf1e3a88.png">

Its favicon is 
<img width="26" alt="screen shot 2016-11-28 at 16 04 32" src="https://cloud.githubusercontent.com/assets/11330831/20660614/83bf3ba4-b585-11e6-8479-29c388f07813.png">

cc @bradleyrichter , @cezaraugusto , @bsclifton

**Comment by bsclifton** [comment]
Another great example of this one- youtube:
![screen shot 2016-11-28 at 10 49 01 pm](https://cloud.githubusercontent.com/assets/4733304/20698243/ed008b5e-b5bc-11e6-831c-7211a5095708.png)

**Comment by bradleyrichter** [comment]
@cezaraugusto Is trying a 90% opacity on the BG color to keep the icon visible without changing the look too much.

**Comment by bsclifton** [comment]
Another similar issue:
https://github.com/brave/browser-laptop/issues/5858

In this case, the computed colors are different based on your login state (see pic). What's weird is that those colors may impact brand recognition

**Comment by bsclifton** [comment]
One way we could solve this would be to first look for the Microsoft attributes. On Twitter for example, they provide this:
```
<meta name="msapplication-TileImage" content="//abs.twimg.com/favicons/win8-tile-144.png"/>
<meta name="msapplication-TileColor" content="#00aced"/>
```

**Comment by Liunkae** [comment]
That's basically the suggestion in #5658.

**Comment by bsclifton** [comment]
@Liunkae yes! thanks for posting (I was searching and was unable to find that :smile: )

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5984#issue-193167093
