### ISSUE TITLE
[Request] Installator zero level customization 

### ISSUE THREAD

**Issue by Gelo3D** [brave/browser-laptop#5871]
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**

Installation of brave browser - only install this app. 
No allow path to install default : C:\Users\UserName\AppData\Local\brave\
Some options in installation like default browser, path etc.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This would be good;  We have captured this with https://github.com/brave/browser-laptop/issues/432, so I'll close this particular issue as a dupe and give the other a bump :smile:
