### ISSUE TITLE
[Bug] Crash when use close other tabs

### ISSUE THREAD

**Issue by Gelo3D** [brave/browser-laptop#5872]
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**

When I have more than 10 tabs, than I click button with option 'close ohter tabs' browser crash, without any information about it. When i start again app, i have my previous tab.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
[Device][Test Platform]
Laptop Toshiba L50-B-125
PROCESSOR : INTEL i5-4200U 2x1,6 - 2,3 GHz
RAM : 4GB DDR3 1,6GHz
SSD : 120 GB SATA3 M2 Micro Data MD500
HDD : 750 GB SATA3 TOSHIBA MQ01ABD075
GRAPHIC : AMD RADEON R7 M260 + intel hd graphic
SYSTEM : Windows 8.1 64bit

- Brave Version:

Brave	0.12.10
libchromiumcontent	53.0.2785.143
Muon	1.4.26
Node.js	6.5.0
os.arch	x64
os.platform	win32
os.release	6.3.9600
Update Channel	dev
V8	5.3.332.47

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
I think this has been fixed for 0.13.0 (#5946).

**Comment by bbondy** [comment]
I think it is closed as well once 0.13.0 is released. Please re-open after that release if it is still present though!

**Comment by luixxiul** [comment]
I added `QA/no qa needed` as there isn't a commit linked to this.
