### ISSUE TITLE
Closing last tab should open a new tab (not exit browser)

### ISSUE THREAD

**Issue by Gelo3D** [brave/browser-laptop#5873]
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**

Exit last tab do new tab not exit browser

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
+1 on this

**Comment by NejcZdovc** [comment]
Or something like this https://github.com/brave/browser-laptop/issues/1515

**Comment by srirambv** [comment]
Not exactly as #1515. That is specifically to warn when user clicks the browser close button. This is for when there is only one tab and you close the tab it should create a `about:newtab` instead of closing the browser itself.

**Comment by NejcZdovc** [comment]
you are right, not completely the same

**Comment by kumarrishav** [comment]
@NejcZdovc @srirambv should this be default (only) behaviour or  configurable from preference @bsclifton

**Comment by srirambv** [comment]
+1 for adding it as a preference under tabs and off by default.

**Comment by kumarrishav** [comment]
off by default means : closing last tab should close the browser . right? @srirambv

**Comment by srirambv** [comment]
Yup that's correct. 
Disable switch (default) - Close last tab, close browser window
Enable switch - Close last tab, create about:newtab and retain the window

**Comment by NejcZdovc** [comment]
cc @bradleyrichter for this thoughts

**Comment by luixxiul** [comment]
+1 from me based on the fact that for now BF cache is cleared when closing the browser.

the request has the common motive with https://github.com/brave/browser-laptop/issues/1382

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/is-there-a-way-to-not-close-the-browser-if-you-close-the-last-remaining-tab/4467

**Comment by Jacalz** [comment]
+1 from me

**Comment by bradleyrichter** [comment]
Agree - if the tab to be closed is the last remaining tab not including pinned tabs, then it should be replaced with a new tab and NOT close the browser. We should not need to add a preference for this.

**Comment by johnstrasser** [comment]
+1

For reference in firefox: about:config
browser.tabs.closeWindowWithLastTab setting

**Comment by RGBD** [comment]
+1

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/option-to-keep-brave-open-when-closing-last-tab/13760?u=eljuno

**Comment by promms** [comment]
+1 from me

**Comment by bradleyrichter** [comment]
@petemill is this something small you can add to a near future PR?

**Comment by AlexUhde** [comment]
+1

**Comment by nCrazed** [comment]
I keep coming back to trying Brave just to find that it's still unusable due to the application window disappearing when it shouldn't.

**Comment by Fafofu** [comment]
How long does it take to wait !? Do it faster!

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1002
