### ISSUE TITLE
[Bug] Private tab suggests my Google Account

### ISSUE THREAD

**Issue by sebagomez** [brave/browser-laptop#5874]
**Did you search for similar issues before submitting this one?**
yes, and found some issues related with Google Accounts but not with Incognito mode

**Describe the issue you encountered:**
I have a Brave session with two open tabs with two different Google account (one for work and one personal). I opened a new Private Tab to sign in to the Google Play store with a different account, but brave suggests I sign in with one of my active account. It also signs in automatically, only asking my for the password and assuming the account from one of the other not private tabs.

**Expected behavior:**
The brave should not suggest anything from non private world.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10 x64

- Brave Version:
0.12.10

- Steps to reproduce:
Already described above

**Comment by bbondy** [comment]
Hi @sebagomez can you confirm if the private tab you opened has an eye on it?
<img width="185" alt="screenshot 2016-11-28 11 31 18" src="https://cloud.githubusercontent.com/assets/831718/20676580/31c34d94-b55e-11e6-9d77-3c48854c099d.png">

I ask because I don't think what you described is possible.

**Comment by bbondy** [comment]
Also could you expand on this one:

> but brave suggests I sign in with one of my active account.

Maybe with a screenshot, is it in the autosuggest? Or do you mean in page content is showing you the info?  

Autosuggest is normal and not a bug.  The private mode is not trying to hide itself from you as the user but from other page content.

**Comment by jonathansampson** [comment]
@bbondy I'm see what I believe you are seeing. Page seems unaware of parallel sessions. Auto-suggest pop-up (from the Application) suggests email addresses used in parallel tabs.

**Comment by sebagomez** [comment]
@bbondy the tab does have the eye on it

@jonathansampson that's right, I'm opening that tab to have another account... it also was impossible to sign out out of that Tab/Account. I had to go to Chrome for that. I might be able to record a video/gif with that. But having multiple Google accounts messing up it's been something I see now and then. I had to delete browser history to get things done. (maybe not related to this issue)

**Comment by luixxiul** [comment]
was this already fixed?

**Comment by jonathansampson** [comment]
@luixxiul I am no longer able to reproduce this issue.

**Comment by jonathansampson** [comment]
@luixxiul I am no longer able to reproduce this issue. If the problem returns, we can re-open.
