### ISSUE TITLE
1Password Should Auto-Submit on Fill

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5875]
**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
> In my other browsers, when I click to fill my username and password from OnePassword, it submits the login form, too. It would be nice if Brave did that, too. [[Source](https://community.brave.com/t/onepassword-extension/33?u=sampson)]

**Platform (Win7, 8, 10? macOS? Linux distro?):** N/A

**Brave Version:** N/A

**Comment by alexwykoff** [comment]
This is a regression introduced in 0.12.10 which we missed.

**Comment by darkdh** [comment]
0.13.0 preview 3 works for me
![456](https://cloud.githubusercontent.com/assets/11330831/21125371/082bcfec-c120-11e6-8b84-c68857fc61b6.gif)

**Comment by bbondy** [comment]
Closing but please re-open if you see it on 0.13.0 preview3 or later.

**Comment by luixxiul** [comment]
Would anyone please add QA steps for this issue? 0.13.0 will be the largest release ever and the QA team needs clear and simple steps! Please see #6668 for more info. Thanks in advance :pray:

**Comment by srirambv** [comment]
QA Steps
1. Enable 1Password as password manager from settings 
2. Visit any site which is stored in the 1Password Vault
3. Press Ctrl+\ or Cmd+\ to autofill the user credentials
