### ISSUE TITLE
CMD + click on about pages are blank on new tab

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5880]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
When using cmd+click on about pages the new tab pages are blank. No errors on console.

**Expected behavior:**
The page should display the content. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 1

- Steps to reproduce:
    1. visit about:about
    2. Cmd+click on any of the about page links

Note: clicking on the link works as expected. context menu open link in new tab works as expected.

- Screenshot if needed:
<img width="1438" alt="screen shot 2016-11-28 at 1 51 17 pm" src="https://cloud.githubusercontent.com/assets/1434040/20686158/1b60aae6-b57d-11e6-9eab-34832daaaf72.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/5877

**Comment by darkdh** [comment]
This is not limited to about pages.
if you cmd+click on the link which opens a new window like this
http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open
The new open tab will also be blank.

**Comment by cezaraugusto** [comment]
Related: #6152, #6252

**Comment by luixxiul** [comment]
@bridiver the new tab opened with about:brave rev link (https://github.com/brave/browser-laptop/issues/5462#issuecomment-268374692) is also blank. Do you think it is the same issue and will be fixed in the next preview?

**Comment by bbondy** [comment]
Test plan: see steps to reproduce in the first comment.
