### ISSUE TITLE
Creating a wallet shows 'loading' for account balance without updating after 'a reasonable time'

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5882]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
When creating a new wallet, the 'loading' text is not replaced after minutes of observing the payments preference page.

**Expected behavior:**
The balance should be 0.00 for a new wallet within 2 minutes (preferably shorter).

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 preview 1

- Steps to reproduce:
    1. Remove your /brave folder
    2. Create a new wallet
    3. Wait a couple minutes

- Screenshot if needed:
<img width="899" alt="screen shot 2016-11-28 at 2 33 01 pm" src="https://cloud.githubusercontent.com/assets/1434040/20686692/4eaf01fc-b57f-11e6-9f94-7801c3e6504f.png">

- Any related issues:
https://github.com/brave/browser-laptop/issues/5877

**Comment by mrose17** [comment]
@alexwykoff - just checking: is this on the new chromium build? if so, i think it's related to https://github.com/brave/browser-laptop/issues/5930

**Comment by alexwykoff** [comment]
It's still present as of commit bd60fe996b7ea19caf55b604214a3dbe629bad58

**Comment by mrose17** [comment]
afaik, the issue isn't fixed yet... and is something introduced by the new chromium. so i'm trying to determine whether this issue and #5930 are "the same thing"...

**Comment by alexwykoff** [comment]
I was able to reproduce by launching from master (which uses the older libchromium) so I am not sure that it is introduced from the chromium54 update. The new build ( 0.13.0 Preview 2 ) cannot create a wallet at all which is a separate issue.

**Comment by luixxiul** [comment]
Any update?

**Comment by mrose17** [comment]
i am looking at it right now...

**Comment by luixxiul** [comment]
@mrose17 thanks!

**Comment by mrose17** [comment]
it turns out that a change to the caching algorithm in the ledger caused this issue. the ledger caching is fixed and the issue is now gone... _my bad, sorry!_

**Comment by luixxiul** [comment]
yes I confirmed that, thanks!
