### ISSUE TITLE
Flash controls are not working

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5883]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
When trying to enable Flash, the controls did not work.

**Expected behavior:**
After allowing Flash in the context, the content should display.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 1

- Steps to reproduce:
    1. visit homestarrunner.com
    2. enable flash
    3. right-click on control panel to 'allow once'

- Screenshot if needed:
![flash_cover](https://cloud.githubusercontent.com/assets/1434040/20687117/d1229210-b580-11e6-9019-918939a4987c.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/5877

**Comment by bradleyrichter** [comment]
@alexwykoff works for me in master:

![image](https://cloud.githubusercontent.com/assets/13509546/20940426/92f94bc8-bba7-11e6-9dbf-38f3f9401b84.png)

**Comment by bsclifton** [comment]
@bradleyrichter this is with Chromium 54; in order to test, you'd need to switch to the `chromium54` branch and redo your `npm install`. I believe @bridiver is checking this out now...

**Comment by bradleyrichter** [comment]
ahhh...sorry. missed that.

**Comment by bridiver** [comment]
there is still an open issue with flash permission settings, but flash was a known issue in preview 1 that was listed in the main chromium54 ticket. It no longer uses the about-flash placeholder and allow/allow for 1 week works correctly in preview 4 afaik

**Comment by luixxiul** [comment]
Do we need to QA for this or not?
