### ISSUE TITLE
Tab text selectable via keyboard

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#5884]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The tab label text can be selected and dragged around or copied by using Ctrl-A on the keyboard.

**Expected behavior:**
The tab label text can't be selected.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.10

- Steps to reproduce:
    1. Press Ctrl-F to open the findbar.
    2. Click an empty area of the findbar.
    3. Press Ctrl-A.  The tab text is now selected, although there is no visual indication.
    4. Position your mouse cursor within the findbar, below a tab, then click and drag.  You should faintly see the tab text moving with your cursor.
    5. Press Ctrl-C and paste into a text editor.  You will see the text of all open tabs with some leading and trailing whitespace.

- Screenshot if needed:
![tab-text-select-before](https://cloud.githubusercontent.com/assets/13000059/20687574/088b715e-b58b-11e6-845e-bdf4f7e37449.png)

- Any related issues:

**Comment by josiah-keller** [comment]
It looks like setting `-webkit-user-select: none` on the entire `.top` element fixes this.  It doesn't appear to cause any problems with the URL bar or the findbar, but I'm not familiar enough to confidently judge whether this might cause any other problems.

**Comment by bradleyrichter** [comment]
here is a recorded GIF movie from @srirambv showing mouse drag and selection of tab text:

![image](https://cloud.githubusercontent.com/assets/13509546/21372909/356681dc-c6cf-11e6-884e-dd5b6ad75f94.png)
