### ISSUE TITLE
autofill is showing password content while typing

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5885]
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
While trying to log into a site, I noticed that autofill was showing my password.

**Expected behavior:**
The password content should never be shown by autofill.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 1

- Steps to reproduce:
    1. visit a site like netflix
    2. attempt to log in
    3. observe the password entry flow

- Screenshot if needed:
![autofill_password](https://cloud.githubusercontent.com/assets/1434040/20688049/b7b0bbb4-b584-11e6-8cce-26c45bc96f27.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/5877

**Comment by bbondy** [comment]
@darkdh could you take a look?

**Comment by darkdh** [comment]
sure.

**Comment by darkdh** [comment]
That is not popup of autofill. It's the content of netflix
<img width="931" alt="screen shot 2016-11-29 at 09 29 23" src="https://cloud.githubusercontent.com/assets/11330831/20692986/5e931418-b616-11e6-8e55-5e757f53f9d9.png">
