### ISSUE TITLE
stats shown on about:newtab should use a shorthand notation when large

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5889]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The stats shown on about:newtab should use a shorthand notation when large

For example:
![screen shot 2016-11-28 at 5 19 19 pm](https://cloud.githubusercontent.com/assets/4733304/20691784/96f92ac6-b590-11e6-881d-e076a4a74599.png)

Instead of writing "35,489", this could be written as "35k".  One important aspect to consider is the localization associated with this.  We would want to use a library such as [numeral.js](http://numeraljs.com/) to make sure our supported locales have respective abbreviations

Another consideration: instead of always abbreviating, we could show the full number if there are less than X digits.  Perhaps it only starts to abbreviate when it's 7 digits.  This basically ends up delivering the same result as what the time stat does (which goes from seconds to minutes to hours to days; it doesn't yet go to months, etc).

cc: @bradleyrichter @bbondy @alexwykoff

**Comment by bradleyrichter** [comment]
I didn't want to ask for the moon. But yes, ideally it has a crossover point where it changes. We had discussed allowing 4 digits. So, switch to 10K after 9,999.

**Comment by bsclifton** [comment]
Whoops, I had already captured this with https://github.com/brave/browser-laptop/issues/5747

I'm closing that (in favor of this) but wanted to share the comment @luixxiul had, since it also mentions a good fix:


> I'd place them with display: flex, flex-flow: row wrap, justify-content:flex-start, setting max-width to the container. I think it is also l10n-friendly because the labels under the counters can be longer.

<img width="569" alt="screenshot 2016-11-20 23 02 54" src="https://cloud.githubusercontent.com/assets/3362943/20463408/7fac43ba-af75-11e6-91c3-3a39645e53a1.png">

**Comment by maaz93** [comment]
As discussed on this [PR comment](https://github.com/brave/browser-laptop/pull/7489#issuecomment-285819879), I would like to take this up. 😄  I looked at [numeral.js](http://numeraljs.com/) and it seems good for the job at hand. I needed one clarification though. When the user is using a locale which is not supported by numeral.js, we'll just fall back to _en_ ?

**Comment by bsclifton** [comment]
@maaz93 sorry it's taken me so long to respond here ☹️ 

I really like that approach! Let's try to go with a supported locale... but if it's unavailable, we'll fall back to English. I believe that's how our translations work right now (any which are missing fall back to English)
