### ISSUE TITLE
Right-click on Google+ permalink anchor text fails to find link

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#589]
(on OS X 10.11)
1. Go to https://plus.google.com/u/0/collection/s0Inv
2. Right-click on one of the post timestamps (upper right of each post) to get the permalink
3. Only option is to copy the text, not copy the link address

**Comment by psimyn** [comment]
Will be fixed by https://github.com/brave/browser-laptop/pull/566

**Comment by luixxiul** [comment]
Closed as the PR merged
