### ISSUE TITLE
Target _blank is opening a new tab instead of a new window

### ISSUE THREAD

**Issue by EPadronU** [brave/browser-laptop#5890]
**Did you search for similar issues before submitting this one?**
Yes. I found #49 but I was encouraged to open a new issue.

**Describe the issue you encountered:**

Running `window.open("<url>", "_blank")` opens a new tab. Clicking on a anchor element with target equal to `_blank` behave the same.

**Expected behavior:**

In both cases, a new window should open.

- Platform: Funtoo/Gentoo (Linux)

- Brave Version:

```
Name	Version
Brave	0.12.10
Muon	1.4.26
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.8.7-1
os.arch	x64
```

- Any related issues: #49

**Comment by bsclifton** [comment]
@EPadronU I think this behavior is expected- although we could always add a new preference letting you choose how links open (new tab versus new window).

Is there another browser which does it properly for you?

**Comment by EPadronU** [comment]
> Is there another browser which does it properly for you?

I tried Firefox and Chrome. The behave the same as Brave.

> I think this behavior is expected

You're right, I feel so embarrassed.

> we could always add a new preference letting you choose how links open (new tab versus new window)

That would be great!

The reason I brought this up is due to the fact, when I open a new window, such new window has also those tabs I have pinned previously. That doesn't happen in Firefox, for instance. And I wanted to work around said undesired (for me) behavior.

**Comment by bsclifton** [comment]
This is great info @EPadronU! :smile: So you're wanting a new window to NOT have the pinned tabs? (ex: the pinned tabs only exist in one window; 2nd, 3rd, etc windows do not have the pinned tabs)

**Comment by EPadronU** [comment]
> So you're wanting a new window to NOT have the pinned tabs? (ex: the pinned tabs only exist in one window; 2nd, 3rd, etc windows do not have the pinned tabs)

That's absolutely right.

**Comment by bsclifton** [comment]
Sorry for the delay here- after searching, we have this feature request captured and you can track it here :smile: 
https://github.com/brave/browser-laptop/issues/5800 

I'll go ahead and close this issue out as a duplicate
