### ISSUE TITLE
Default bookmarks show in history portion of autocomplete

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#5892]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Installing Brave fresh will create a new session file which will be pre-populated with 6 Brave Software related accounts.  These have lastAccessedTime set and therefore are considered history entries

autocomplete shows https://www.facebook.com/BraveSoftware/ when typing facebook.com. This is quite annoying because I want to go to the main facebook page at https://www.facebook.com/ and autocomplete forces me to delete BraveSoftware from the url to do that

**Expected behavior:**
only urls I actually enter should become part of autocomplete

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version:
0.13.0

- Steps to reproduce:
    1. Start with a fresh profile
    2. Type facebook
    3. autocompletes to https://www.facebook.com/BraveSoftware/

cc @cezaraugusto

**Comment by pixelass** [comment]
I had similar issues when I activated "tab-completion". I deactivated it since it totally messed with the address bar. 
This is especially annoying when you have pinned tabs. I was basically unable to go to the github homepage because it kept redirecting me to my profile which is the pinned tab.

**Comment by bridiver** [comment]
@pixelass the pinned tab thing is a slightly different issue. This issue is specifically targeted at urls that show up in autocomplete because they are "top sites" in the default new tab page. I believe there is a separate issue for autocomplete "overcompleting" by default which I also agree is annoying. Safari does the same thing and I think Chrome as well, but my preference would be to autocomplete the shortest match

**Comment by pixelass** [comment]
@bridiver thanks for explaining. I read this issue and thought "this sounds very familiar" ;). Thought it would help.

So I guess you are talking about the following issue (occurs with bookmarks)

The gif shows me trying to go to codepen.io but it keeps completing and even changing cursor position when I simply use the arrow keys.

![complete](https://cloud.githubusercontent.com/assets/1148334/20766600/55c11c14-b737-11e6-9f6d-4a8d06102254.gif)

**Comment by bsclifton** [comment]
@bridiver would the discussion in https://github.com/brave/browser-laptop/issues/5767 be enough to resolve this issue? Basically picking the shortest match, as you suggest above?

If so, would we be able to close this issue? I think it's OK to have the entries in history, as long as autocomplete prefers the root domain over the bookmarked URL

**Comment by bsclifton** [comment]
I'll close this for now, since elegant handling of the URL bar would fix this issue, IMO (see notes above).  @bridiver please feel free to re-open
