### ISSUE TITLE
"Remove Bookmark" button hard to read on hover

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5894]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The text on the Remove button (within the Edit Bookmark dialog) is hard to read when the user hovers the button.

**Expected behavior:**
The text is always easy to read.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version:** 0.12.10

**Screenshot if needed:**
![edit-bookmark-hover](https://cloud.githubusercontent.com/assets/815158/20716173/f3a27602-b616-11e6-8d0a-099274650335.gif)

**Comment by bsclifton** [comment]
Tentatively assigning to 0.13.1; (I know you're working on https://github.com/brave/browser-laptop/issues/5801)

**Comment by luixxiul** [comment]
I fixed the issue with #5705

**Comment by luixxiul** [comment]
Confirmed it was fixed on 0.13.0 Preview2

**Comment by luixxiul** [comment]
Test plan: based on https://github.com/brave/browser-laptop/pull/5705/commits/23207ed38d1423017a94285f229d8ba5dec0c8d3

1. Click the bookmark button on the URL bar
2. Make sure color of "Remove" label is no longer white on hover
