### ISSUE TITLE
Importing a lot of bookmarks slows down the browser

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5899]
https://linkbubble.zendesk.com/agent/tickets/6929

> I have a lot of browser bookmarks, more than loads into the program.
> 
> Occasionally the program loads slowly onto the screen.

**Comment by darkdh** [comment]
https://github.com/brave/browser-laptop/pull/5587 might solve the issue after I have time to rebase PR and get it merged

**Comment by alexwykoff** [comment]
I believe this is solved with the latest updates to importer

**Comment by darkdh** [comment]
fixed by #5587
