### ISSUE TITLE
capability to remove all thumbnails on the New Tab page with one click,

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5902]
https://linkbubble.zendesk.com/agent/tickets/6991
> I would like to have the capability to remove all thumbnails on the New Tab page with one click, rather than having to click multiple times on each of the thumbnails.

+1 from me too

**Comment by bradleyrichter** [comment]
Can we add "Reset all top-sites tiles..." to the context menu?

![image](https://cloud.githubusercontent.com/assets/13509546/20781743/356d2f5e-b73a-11e6-8f2c-d324c9ab2542.png)
