### ISSUE TITLE
unable to find a way to scroll down the list beyond the bottom of the screen

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5903]
https://linkbubble.zendesk.com/agent/tickets/7017
> I've imported the bookmarks I have from IE and they are all visible. The number of bookmarks I have is lengthy including folders. I'm unable to find a way to scroll down the list beyond the bottom of the screen. Touching any scrolling key or combination of keys causes the drop down box to disappear.

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/sroll-up-and-scroll-down-through-bookmarks-window/1665

**Comment by srirambv** [comment]
Fixed by https://github.com/brave/browser-laptop/commit/7ea7def4f631d9b51221a14b7b113fdc836d3da4?

**Comment by NejcZdovc** [comment]
Yes, it should be fixed

**Comment by bsclifton** [comment]
Assigning to 0.17.x and closing so that we can retest 😄

**Comment by srirambv** [comment]
Verified on 0.17.12 works fine
