### ISSUE TITLE
imported bookmarks do not show in the drop down menu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5904]
From support
> I've imported my bookmarks and they do not show in the drop down menu. I have to open the bookmark manager to see my bookmarks. This is just awful. So many extra clicks and menu diving to be able to navigate bookmarks compared to Firefox.

**Comment by bsclifton** [comment]
@darkdh do bookmarks automatically get put under "Other bookmarks"? I wonder if we should offer a checkbox with something like "add to bookmarks toolbar"

**Comment by darkdh** [comment]
@bsclifton , no they will be put under bookmarks toolbar.  And if you don't check "Merge into bookmark toolbar", there will be a folder called "Imported from XXX" also under the bookmarks toolbar.

**Comment by bsclifton** [comment]
@darkdh ah- ok... so this user may have been upset because we didn't check "Merge into BTB" by default. 

@bradleyrichter @bbondy would it make sense to auto-check the "Merge into bookmarks toolbar" by default?

**Comment by rebron** [comment]
Closing wontfix here but fixed in brave-core. original issue is fixed, merging imported bookmarks into bookmarks toolbar is a separate issue that needs evaluation.
