### ISSUE TITLE
Only the video actually played should be played

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5908]
From support
> On Youtube I usually load up a lot of tabs with videos (cmd+click) and then I go through them one by one. In your browser they all start playing simultaneously, unlike Chrome, where only the video you are actually watching is playing. Can you please add this to your feature request list?

**Comment by bsclifton** [comment]
Related, but not exactly the same: https://github.com/brave/browser-laptop/issues/2227

**Comment by Liunkae** [comment]
+1 from #6627. Also +1 from me.
