### ISSUE TITLE
Clicking link from email will sometimes will do a search instead of directly following

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5911]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
With the following conditions:
- Brave being default browser
- clicking email link (email marketing) in a native client such as Microsoft Outlook

Brave will sometimes launch and then immediately do a search using your default search engine.  When I dug deeper, I noticed that a period at the end of the URL was triggering this.  You could repro by pasting the full URL into the omnibox and hitting enter.  Removing that single period fixed the issue 

@bradleyrichter also saw this behavior and can provide an example. Having a different default browser open works as you'd expect.

**Expected behavior:**
Links like this should be followed, not causing a search.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.10

- Steps to reproduce:
    1. Launch Brave and open a new tab
    2. Paste in `https://e.turbotax.intuit.com/pub/cc?_ri_=3vv-8-e.` and hit enter
    3. Notice a search is done using your default search engine
    4. Paste in `https://e.turbotax.intuit.com/pub/cc?_ri_=3vv-8-e` (notice: missing the period at the end) and hit enter
    5. Notice that Brave properly follows the link (in this case, the link doesn't go anywhere; I sanitized it so that folks can't re-sign me up for emails! :smile: )

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
cc: our URL bar experts :smile: 
@aekeus @bbondy @diracdeltas

**Comment by bsclifton** [comment]
I created a PR which has a failing test:
https://github.com/brave/browser-laptop/pull/5912

If you grab this one, you can cherry-pick that commit in and run it to verify that issue is actually fixes :smile:

**Comment by Sh1d0w** [comment]
@bsclifton Possible places to check where is goes wrong:

https://github.com/brave/browser-laptop/blob/master/js/lib/urlutil.js#L110

https://github.com/brave/browser-laptop/blob/master/js/lib/urlutil.js#L78

**Comment by bsclifton** [comment]
Bumped up milestone / assignee to match https://github.com/brave/browser-laptop/issues/6058
