### ISSUE TITLE
addfunds tab not properly placed

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#5913]
when using the ADDFUNDS interface, the new tab doesn't come up with the proper parameters.

1. start with this:
![1](https://cloud.githubusercontent.com/assets/400552/20725784/d3b337bc-b627-11e6-9c8b-e38585ffc339.png)
2. click on 'Add funds...' to get this:
![2](https://cloud.githubusercontent.com/assets/400552/20725828/fb0c65cc-b627-11e6-8725-0c8d0c63ca36.png)
3. click on 'Fund with debit/credit' to get this:
![3](https://cloud.githubusercontent.com/assets/400552/20725882/36cdb7aa-b628-11e6-9337-ed9e541acbe4.png)
note how the new tab is not adjacent to the Preferences tab.
4. fill-in the form, etc., close the tab, to get this:
![1](https://cloud.githubusercontent.com/assets/400552/20725934/6c4f9fa6-b628-11e6-8a94-157c6e4313d5.png)
the desired behavior is that the new tab should be opened immediately to the right of the Preferences tab, and when the new tab is closed, the Preferences tab should be raised.

**Comment by mrose17** [comment]
@bbondy suggests we look at this https://github.com/brave/browser-laptop/blob/d86d9638f141c890276bc9d90c5a1dd01d3c6bd5/js/components/main.js#L349

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6060#issue-193942288
