### ISSUE TITLE
Create new page which shows all user owned information

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#5917]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
There should be a "about:me" page which displays all of the information about the user (which is saved on local computer) with the location on disk and possibly even links to the code (as proof).

- Any related issues:
https://github.com/brave/browser-laptop/issues/5388

**Comment by flamsmark** [comment]
@bsclifton Can you describe what you mean by "information about the user"? What sort of info are you talking about?

**Comment by bsclifton** [comment]
@flamsmark great question- some of the data I was thinking:
- all bookmarks
- all history
- autofill information that is stored
- all cookies
- payment info

Basically anything that can be used to uniquely identify a user. Kind of like a "data dashboard". The page wouldn't need to show all the info, but maybe it shows top 5 visited sites, # autofill entries, etc.  Once machine learning comes into the picture (for adtech), there may be an advertising ID or opt-in profile information that a user may want to provide

Sorry the issue is kind of vague- I'm glad you asked about it 😄 Being privacy focused, I think something that helps the user see a snapshot of themselves would be helpful

**Comment by flamsmark** [comment]
From a UX perspective, I think that a big challenge with that display is that many of these are very long lists, and some (cookies) aren't meant to be human-readable. I like the idea of a profile export, but I'm not sure about the particular value of trying to render all this info together.

**Comment by tomlowenthal** [comment]
If anyone is following, brave/brave-browser#807 touches on some similar themes.
