### ISSUE TITLE
Browser is blurry if DPI is greater than 100%

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5926]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Browser looks like its set at 200% magnification

**Expected behavior:**
Should respect the system magnification settings

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Right click desktop > Display settings
    2. Pick a DPI higher than 100% (ex: 150%) and close window
    3. Logout or restart and then log back in again
    4. Launch Brave (Chromium 54 build) and notice the problem

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20745689/493251d2-b6da-11e6-9eff-900cad67ace8.png)

- Any related issues:

**Comment by bradleyrichter** [comment]
@bsclifton Can you reproduce and check if a flag changed?

**Comment by bsclifton** [comment]
On it!

**Comment by bsclifton** [comment]
Reproduced; looks great at 100% but then gets blurry at 125%. I made sure to log out and log back in after upping my DPI to 125% too.  Here's a screenshot that (hopefully) shows how blurred things get:
![screen shot 2016-12-07 at 11 05 50 am](https://cloud.githubusercontent.com/assets/4733304/20980370/7a6806c8-bc6d-11e6-900b-53c83005901e.png)

**Comment by bsclifton** [comment]
I tried the command-line options shown as a work-around here without luck (and many variations of it):
https://bugs.chromium.org/p/chromium/issues/detail?id=395425

`app/index.js`

```
app.commandLine.appendSwitch('enable-use-zoom-for-dsf', 'false')
app.commandLine.appendSwitch('high-dpi-support', 'true')
app.commandLine.appendSwitch('force-device-scale-factor', 'true')
```

**Comment by darkdh** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=633478#c7

**Comment by darkdh** [comment]
`window.devicePixelRatio` isn't correct on my VM. In 53, it is 2 but 1 in 54.

**Comment by luixxiul** [comment]
Test plan:

Right click desktop > Display settings
Pick a DPI higher than 100% (ex: 150%) and close window
Logout or restart and then log back in again
Launch Brave

**Comment by bsclifton** [comment]
Added `release-notes/exclude`; this was introduced with 0.13.0

**Comment by srirambv** [comment]
Except Bookmark modal(#6777) and autofill modal the rest looks good.
