### ISSUE TITLE
URL bar issues on Chromium54 build(0.13.0 preview2)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5928]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
URL bar issues on Chromium54 build(0.13.0 preview2)

**Expected behavior:**
Should align properly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Reload button is not properly aligned
    2. Stop reload button is not properly aligned
    3. Bookmark icon is bottom aligned
    4. URL bar is not aligned with the bookmark icon
    5. Window buttons have extra padding on top when the browser is maximized

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20745802/d7727832-b6da-11e6-8c78-96dab260049b.png)

   ![image](https://cloud.githubusercontent.com/assets/17010094/20745810/e0decc9a-b6da-11e6-9a9b-88dde27dcdde.png)
 
   ![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17010094/20746159/8bf1aae8-b6dc-11e6-84a4-11bd6c8b67b6.gif)

- Any related issues:
cc: @bsclifton @jkup @bradleyrichter

**Comment by r3wt** [comment]
can repro in ubuntu 14.04, ubuntu 16.04, opensuse 42.2

![screenshot_20161201_000331](https://cloud.githubusercontent.com/assets/4483325/20783646/c0ff4410-b75a-11e6-948f-523e33707ee0.png)

**Comment by luixxiul** [comment]
@srirambv the windows specific styles in `navigationBar.less` causes the bug. I'm working on it.

**Comment by luixxiul** [comment]
@r3wt Are you running 0.13.0 Preview2? I cannot reproduce the bug on Ubuntu 16.04 (Ubuntu Unity). Would you please check if it is specific to openSUSE?

**Comment by luixxiul** [comment]
@srirambv actually all of the hacks in https://github.com/brave/browser-laptop/blob/master/less/navigationBar.less#L39-L57 are no longer necessary thanks to #5739 and #5750 (#5737).

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5967#issue-192887479

Also I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.
