### ISSUE TITLE
Brave doesn't create a roaming profile folder 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5929]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave session doesn't create a roaming profile folder 

**Expected behavior:**
Should create a roaming profile folder 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 2
    2. Open %appdata%, no brave profile folder is created
    3. All files are created directly under %appdata%

- Screenshot if needed:

- Any related issues:
cc: @bsclifton @bridiver

**Comment by bridiver** [comment]
fixed https://github.com/brave/electron/commit/05b368f5b572a3f5b53df18ae47680ac4d812f52

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the bug appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test plan

Do a clean install
Open %appdata%, no brave profile folder is created
Files are NOT created directly under %appdata%
