### ISSUE TITLE
Brave Wallet creation fails on Windows 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5930]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave Wallet creation fails on Windows 

**Expected behavior:**
Should create brave wallet

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preview 2
    2. Enable payments to create wallet
    3. Wait for half hour and wallet is still not created

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20747112/c487593a-b6e0-11e6-83f5-d08512837e98.png)

- Any related issues:
cc: @mrose17 @ayumi

**Comment by mrose17** [comment]
@srirambv - thanks for the report. can you run it again, but with these environment variables set?

        LEDGER_LOGGING=true LEDGER_VERBOSE=true

and then attach ledger-log.json after a few minutes of no wallet creation? thanks!

**Comment by bridiver** [comment]
@mrose17 is `webRequest.fetch()` the root of this issue?

**Comment by mrose17** [comment]
good question! i suspect so. ultimately all of the ledger client calls funnel into a routine in ledger.js called `roundtrip` which in turn calls `js/lib/request:request` which in turn calls `webRequest.fetch()`. since we wrote that ourselves a while back, that is where i think the problem lies.

**Comment by mrose17** [comment]
@srirambv - i am using win10 x86 in a VM running https://github.com/brave/browser-laptop/releases/download/v0.12.13dev/BraveSetup-x64.exe and can not reproduce. it may be @bridiver's patch -- https://github.com/brave/browser-laptop/commit/6023abd171eb0ec582eb96e71f18ad30dddba32e -- addressed this issue.

can you reproduce using "the latest"? thanks!

**Comment by srirambv** [comment]
@mrose17 It works fine on the 0.12.xx branch. I am not able to build branch https://github.com/brave/browser-laptop/commit/6023abd171eb0ec582eb96e71f18ad30dddba32e and verify if the patch fix is working for Chromium54

**Comment by mrose17** [comment]
@srirambv - i suggest closing the issue until it can be reproduced somewhere... (-;

**Comment by srirambv** [comment]
Closing the issue for now as unable to run from  https://github.com/brave/browser-laptop/commit/6023abd171eb0ec582eb96e71f18ad30dddba32e
