### ISSUE TITLE
Import Bookmark doesn't have any browsers listed except for Chrome

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5931]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Import Bookmark doesn't have any browsers listed except for Chrome

**Expected behavior:**
Should show all the available browsers and option to import from HTML file

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preview 2
    2. Click on import browser data from settings
    3. Import modal drop down only has Chrome and nothing else

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20747250/59874a2c-b6e1-11e6-9f38-d1e83b6e3967.png)

- Any related issues:
cc: @darkdh

**Comment by srirambv** [comment]
The list shows empty but selecting does import the data.

**Comment by darkdh** [comment]
I tried 54 with latest commit and it display the list properly
<img width="1432" alt="screen shot 2016-12-01 at 10 52 05" src="https://cloud.githubusercontent.com/assets/11330831/20780193/4b82d648-b7b4-11e6-9c54-c0e648425ce4.png">

**Comment by bsclifton** [comment]
Let's retest this when a new release is available :smile:

**Comment by darkdh** [comment]
feel free to reopen if new release does not work

**Comment by srirambv** [comment]
Still seeing the same issue on Windows 10 and Windows 7 
![image](https://cloud.githubusercontent.com/assets/17010094/21393618/2204bd7a-c78d-11e6-8c36-ab30882bc7a8.png)

cc: @darkdh @bsclifton

**Comment by darkdh** [comment]
This probably related to recent icu changes. I will take a look at it.

**Comment by darkdh** [comment]
revert d4f451c17e8481db6e3b1857c98b266cc76a51ed and bc050cbd1fde71cb84bae52e643e8b32cd27d981 will work again. And @bridiver is working on it.

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/fb893558261f095c695fdc43cee4a7e2239711f9

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
