### ISSUE TITLE
History entries time format is similar to newtab page time 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5932]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
History entries time format shown on newtab page

**Expected behavior:**
Should show proper date/time format

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preivew 2
    2. Browse sites, open about:history, time shows full date/time format shown in newtab dashboard   
    3. Open about:history shows the entries for default top site tiles as well
    

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20750399/86358d4c-b6ee-11e6-835e-2d0da3df6661.png)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
This is captured fairly well with https://github.com/brave/browser-laptop/issues/5879; I'll close this as a dupe and update the issue details :smile:
