### ISSUE TITLE
Enable Pocket/Password managers doesn't enable the extension

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5934]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enable Pocket doesn't enable the extension

**Expected behavior:**
Should enable the pocket extension 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preview 2
    2. Enable pocket from advance settings
    3. Pocket login tab doesn't launch, the widget is not loaded, about:extension doesn't have the entry for enabled extensions
    4. Enable 1Password/LastPass/Dashlane from the password manager, widget doesn't load, about:extension doesn't have the entry for the enabled password manager

- Screenshot if needed:

- Any related issues:
cc: @jonathansampson  @darkdh

**Comment by srirambv** [comment]
cc: @bridiver

**Comment by darkdh** [comment]
fixed by 6023abd
