### ISSUE TITLE
Opening a new tab shows Uncaught TypeError in browser console

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5935]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening a new tab shows Uncaught TypeError in browser console

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Enable browser console
    2. Open a new tab 
    3. Shows error on new tab creation.

- Screenshot if needed:
![consoleerror](https://cloud.githubusercontent.com/assets/17010094/20752406/2f7de5b6-b6f9-11e6-8e0d-2866412035c9.gif)

- Any related issues:
cc: @bridiver

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the bug appeared and was fixed within the same milestone.
