### ISSUE TITLE
Private tab/Session tab icon needs right padding before text

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5936]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Private tab/Session tab icon needs right padding before text

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20752686/7ac7af4c-b6fa-11e6-8014-88dca36d0a27.png)

- Any related issues:
cc: @bradleyrichter @jkup

**Comment by bsclifton** [comment]
@jkup would you mind grabbing this one?

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6031#issue-193632396

**Comment by luixxiul** [comment]
Will this be fixed with #5918? The buttons are not aligned quite well.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22188888/375337c2-e15c-11e6-812c-d3225a0b1927.png)

CC @cezaraugusto
