### ISSUE TITLE
Autofill suggestion doesn't complete autofill 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5939]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Autofill suggestion doesn't complete autofill 

**Expected behavior:**
Should autofill when the suggestion is selected

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0

- Steps to reproduce:
    1. Create an autofill entry
    2. Open https://www.roboform.com/filling-test-all-fields
    3. Click on the field to show autofill suggestion, doesn't fill the fields after clicking on the suggestion

- Screenshot if needed:
![autofill130](https://cloud.githubusercontent.com/assets/17010094/20754227/e14b0762-b701-11e6-82d8-99b954af9b94.gif)

- Any related issues:
cc: @darkdh

**Comment by bsclifton** [comment]
confirmed this works as expected! :smile: 

screenshot showing I'm actually on latest muon (and not using 53!)
![screen shot 2016-12-02 at 10 49 06 am](https://cloud.githubusercontent.com/assets/4733304/20844445/0edb0610-b87d-11e6-8063-7dccdc1e0e38.png)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5959#issue-192759743
