### ISSUE TITLE
menu shortcuts use iframe if focused

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#594]
Steps to reproduce
1. Go to slashdot.org
2. Click on a white brave ad
3. Go back to the slashdot.org
4. Press cmd/ctrl-r
iframe will reload instead of parent window

**Comment by diracdeltas** [comment]
pretty sure this is a bug in Electron's `<webview>.reload()`

**Comment by bridiver** [comment]
I'm pretty sure it's a focus issue
```CommonMenu.sendToFocusedWindow(focusedWindow, [messages.SHORTCUT_ACTIVE_FRAME_RELOAD])```
After you click on the ad, that is the focused window

**Comment by bbondy** [comment]
Can we get window.top equivalent to focusedWindow?

**Comment by bridiver** [comment]
There is no top access from the sandboxed frame. I think we should just use active frame instead of focused frame

**Comment by bridiver** [comment]
I clicked on an iframe ad in Safari and the keyboard shortcut still reloads the main frame

**Comment by bridiver** [comment]
you were correct @diracdeltas, it was an issue with Electron
https://github.com/brave/electron/commit/41ee85ba515443aafd9dd43af2e878190debdf1d
