### ISSUE TITLE
Closing devtools creates a white blank window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5940]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Closing devtools creates a white blank window

**Expected behavior:**
Should just close the browser console and keep the browser as it is

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preview 2
    2. Open dev console by pressing Shift+F8
    3. Close the dev console, browser becomes white blank screen, have to kill and restart the app to use

- Screenshot if needed:
![whitescreen](https://cloud.githubusercontent.com/assets/17010094/20754615/aec602fe-b703-11e6-86f0-11070e3e89d3.gif)

- Any related issues:
cc: @bridiver @bsclifton

**Comment by darkdh** [comment]
This no longer exists in latest commit

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test plan:

Do a clean install
Open dev console by pressing Shift+F8
Close the dev console
Browser should not become white blank screen
