### ISSUE TITLE
Geolocation doesn't detect user location 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5941]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Geolocation doesn't detect user location 

**Expected behavior:**
Should show the user location

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Visit https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
    2. Click on Show my location
    3. Shows error `Unable to retrieve your location`

- Screenshot if needed:

- Any related issues:
#3825

**Comment by bbondy** [comment]
QA steps: 
test that geolocations work as per the manual test sheet.
