### ISSUE TITLE
Close all tabs causes crash

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5946]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Close all tabs causes crash

**Expected behavior:**
Should just close all other tabs and not crash

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 preview 2

- Steps to reproduce:
    1. Open several tabs
    2. Right click on any tab and click on close other tabs
    3. Brave crashes

- Screenshot if needed:
![closetabcrash](https://cloud.githubusercontent.com/assets/17010094/20767215/3ea650e0-b731-11e6-91c0-9488aa5f6aad.gif)

  ![image](https://cloud.githubusercontent.com/assets/17010094/20767213/38e97574-b731-11e6-9366-90ffd36772df.png)

- Any related issues:

**Comment by bbondy** [comment]
I think this will be fixed with a fix @bridiver is doing with webview events not firing after being destroyed.

**Comment by bbondy** [comment]
Should be fixed by these:
https://github.com/brave/electron/commit/cedf4462c04a986f6e0bdf385fa94b3fd054e72b
https://github.com/brave/electron/commit/271383a194e5521dfa291ab719608f9e6b9f37ad
