### ISSUE TITLE
Regression: 1password extension does not load

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#5949]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
After selecting the 1password extension to manage my passwords, the icon was not added to the UI. Quitting and restarting did not help.

**Expected behavior:**
The extension should load and the user should be prompted to authorize if the app is installed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 2

- Steps to reproduce:
    1. Remove your /brave directory
    2. Open the Preview2 build
    3. Select 1Password on about:preferences#security
    4. Observe the UI, attempt to use the context menu on a known saved site

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
The root cause could be #5945.

**Comment by alexwykoff** [comment]
dupe of https://github.com/brave/browser-laptop/issues/5945
