### ISSUE TITLE
Issue: No Flash player recognized on Ustream or the Nasa TV website

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#595]
As the title says, Ustream or Nasa TV direct stream on the Nasa webpage are seeing Flash as "not installed"

**Comment by psimyn** [comment]
Can you please add links to this wiki page?

https://github.com/brave/browser-laptop/wiki/Non-Supported-Video-Sites

**Comment by diracdeltas** [comment]
duplicate of #386
