### ISSUE TITLE
Suggestion: setting to not autoplay videos

### ISSUE THREAD

**Issue by mykkymk** [brave/browser-laptop#5952]
I like to open several youtube videos on different tabs. can you do some upgrades so that when i open i video in new tab it doesn't  start playing until i click on that tab.

**Comment by pixelass** [comment]
I was wondering about the same thing. Most browsers don't autoplay youtube videos. When browsing youtube on brave I always manually pause the videos.

@mykkymk I suggest changing the title to "don't autoplay youtube videos"

**Comment by Superbest** [comment]
This is possible in Firefox with `about:config` by setting `media.autoplay.enabled` to `false`.

**Comment by Sh1d0w** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/4045
