### ISSUE TITLE
Edit Bookmark close icon needs hover color

### ISSUE THREAD

**Issue by getsetbro** [brave/browser-laptop#5953]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
The CLOSE icon has no hover effect.
**Expected behavior:**
"For the X, it should be @buttonColor when idle and #000 (black) when hovered."
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version:
0.12.10
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![gif](https://cloud.githubusercontent.com/assets/442793/20774247/2275b8d6-b71b-11e6-83d8-4ac8e0d9f419.gif)

- Any related issues:

**Comment by bsclifton** [comment]
closed via https://github.com/brave/browser-laptop/pull/5954

@getsetbro for future reference, you can use self-closing keywords in the commit and GitHub will auto close the issue on merge

Commit would just need to have text like "Fixes #5954" :smile:

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/5954#issue-192701276
