### ISSUE TITLE
Adding and managing client certificates (HTTPS/SSL)

### ISSUE THREAD

**Issue by thomasgrnr** [brave/browser-laptop#5955]
It's a feature but I'd love to have a way to add my own HTTPS/SSL certificate to securely connect to privately hosted webapps. Juste like Chrome and Firefox lets you save and manage external certificates.

Maybe it's already possible, but I cant find it !

Great work anyway guys :)

**Comment by bsclifton** [comment]
@thomasgrnr this is a great feature request :smile: Private apps and also APIs make good use of this.

On Mac, clicking "Manage Certificates" brings up Keychain Access.
![screen shot 2016-12-03 at 4 00 00 pm](https://cloud.githubusercontent.com/assets/4733304/20862780/97996380-b971-11e6-9ecf-6e69870b54a3.png)

I haven't used this in a browser before (only in code I've written).  Do you have more information @thomasgrnr about how this would work? Should the browser be looking at certs that are in the computers certificate store? How/when are they sent? (only when the common name or issuer matches?)

**Comment by thomasgrnr** [comment]
I am not quite sure on how it works, but on chrome I think you just have to have a cert in you "login" keychain. The browser looks for the adequate one. Possibly by checking the issuer name I guess.

I can try to look a bit further into this !

**Comment by bsclifton** [comment]
@thomasgrnr if you can, that would be amazing :smile: It would help a lot to have more concrete details about what this would look like and/or how it would work

**Comment by alexwykoff** [comment]
+1 from support (community)

**Comment by JonGal** [comment]
Another +1 here. I use private certs internally for accessing equipment, testing APIs etc.. Right now I just get an error:

This site can’t be reached

The webpage at https://192.168.124.1/ might be temporarily down or it may have moved permanently to a new web address.
ERR_INSECURE_RESPONSE

**Comment by dhaavi** [comment]
+1!

Is there any update on this?
I'd love to finally migrate to brave.

**Comment by awfki** [comment]
+1 - this is an important feature for enterprise use (and folks who tinker at home)

**Comment by JoseRivas-R** [comment]
+1 - This is a feature mandatory on today's browsers. I think this is more or less how Chrome does the "Manage certificate": https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_cert_management.md

**Comment by dkurzaj** [comment]
This is the only reason I don't use the browser, since I need the feature all day long. Maybe there will be other reasons in the future, but for now I'm blocked at this step.

**Comment by steinsiv** [comment]
Any news on this? proxy certificates would be nice to be able to add to Brave

**Comment by beemster** [comment]
Yes please, this is mandatory. I need this for work related sites and VPN. Otherwise Brave is not an option.
Thanks.

**Comment by zaphod80013** [comment]
Big +1 on this, It's stopping me adopting Brave as primary browser both at home and work and impact both my personal and work VPN.

**Comment by valnuro** [comment]
+1 Can't us Brave as primary browser because of this

**Comment by dsackin** [comment]
+1 on importing certificates

**Comment by bsclifton** [comment]
Closing this issue as `wontfix`. We'll get the same behavior as Chromium/Chrome when moving over to Brave Core (which is coming soon). More info about that release available here:
https://brave.com/development-plans-for-upcoming-release/
