### ISSUE TITLE
Allow private tabs to use different sessions (partitions)

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#597]
As i prefer private tabs, which also has the great side effect that no cache is created, it would be great to have also the option to have the "new session tab" mode also available for private tabs.

+1 from https://github.com/brave/browser-laptop/issues/6426

**Comment by luixxiul** [comment]
@bbondy Is there any plan for this?

**Comment by bbondy** [comment]
yes

**Comment by tbrn** [comment]
New private session tab combined with  #3083 would be awesome:
Different colours for different private sessions.

**Comment by bsclifton** [comment]
+1 from user on Twitter. Per discussion with @diracdeltas, we may even consider an option which the user can enable which creates a new partition for each new tab

**Comment by diracdeltas** [comment]
yeah this behavior has also surprised me before. 

when you close a private window, that session disappears forever. it’s not unreasonable for people to expect the same of tabs

i don’t use private tabs except for one-off browsing but maybe other people expect to have their logins work across private tabs. i would be in favor of the default behavior being one-partition per private tab.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/776
