### ISSUE TITLE
prevent blue select border from appearing on main content window on prefs pages

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5970]
This seems to be new as of 0.12.10?

![image](https://cloud.githubusercontent.com/assets/13509546/20804448/cf5bd7c4-b7a7-11e6-91e2-55bc0f27d26f.png)

![image](https://cloud.githubusercontent.com/assets/13509546/20804477/e867c03e-b7a7-11e6-8801-08e27c5b3df7.png)

**Comment by luixxiul** [comment]
Duping to #5661?

**Comment by bradleyrichter** [comment]
closed for stupid search skills  ;  )
