### ISSUE TITLE
Add focus ring to about page form elements

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#5971]
This came up in our most recent #design meeting but currently it is impossible for keyboard-only users to know which form element they are on because we don't display a visual change on focus state.

Some of this will be fixed by https://github.com/brave/browser-laptop/pull/5916 which switches us from span's to button tags (which have focus state!) but this ticket is for adding back the blue focus ring to select boxes, textarea's and input fields.

**Comment by jkup** [comment]
Also for this ticket we should check what Chrome does for bookmarks in the bookmarks toolbar. Specifically:

+ Are they tababble from the urlbar input?
+ Do they have focus rings?

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6037 which was merged into branch `0.13.1-branch`.

**Comment by bsclifton** [comment]
reverted here https://github.com/brave/browser-laptop/commit/2aa39bb1073fe8bb40d9fc32d18fdd2ea9cee1d5

Let's re-open the issue with a better approach if we'd like to solve something like this. Thanks 😄
