### ISSUE TITLE
CMD+Number switches Tab and Workspace Desktop

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#5973]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pressing CMD+Number to select a tab also causes the workspace desktop to change on MacOS.

**Expected behavior:**
Tabs should be selectable without any side-effects to the workspace/desktop.

**Platform (Win7, 8, 10? macOS? Linux distro?):** MacOS

**Brave Version:** 0.12.10

**Any related issues:** #5601 

Originally [reported on gab.ai](https://gab.ai/sec/posts/2221026) (currently in an invite-only beta):

![image](https://cloud.githubusercontent.com/assets/815158/20812604/c6ee5a8c-b7d7-11e6-89cd-f9a1362b4aef.png)

**Comment by Liunkae** [comment]
Related: #2026

**Comment by jonathansampson** [comment]
Mentioned [on Twitter](https://twitter.com/iammattnull/status/806187019823153152):
> Matt Null @iammattnull
.@brave Your browser hijacks a native key command for Mac. CMD + 1.
