### ISSUE TITLE
Design concepts

### ISSUE THREAD

**Issue by rickyrauch** [brave/browser-laptop#5976]
I've been working on these concepts, what do you think? We can work together.

![v6-a](https://cloud.githubusercontent.com/assets/197196/20815318/3eae6ae0-b7d2-11e6-88f4-2f2e2fc824fd.png)
![v7](https://cloud.githubusercontent.com/assets/197196/20815319/3eafc228-b7d2-11e6-826e-e4d46155f283.png)
![v5-a](https://cloud.githubusercontent.com/assets/197196/20815320/3eb0e09a-b7d2-11e6-9dd7-76ecbe649791.png)
![v4](https://cloud.githubusercontent.com/assets/197196/20815322/3eb2eaa2-b7d2-11e6-84b3-ee75a7744059.png)

### Icons
![concept icon](https://cloud.githubusercontent.com/assets/197196/20815321/3eb2a42a-b7d2-11e6-8ede-f80e4e46c73b.png)

<a href="http://twitter.com/rickyrauch">@rickyrauch</a>

**Comment by bradleyrichter** [comment]
@rickyrauch Cool stuff. Happy to have help on UI/UX contributions!

Your concepts show a variety of differences from our current UI. What things do you feel need the most improvement?

Regarding the round icons - I love the colors. A few people have suggested round app icons to go with the other browsers on their dock. And some like how we aren't round. Go figure....

**Comment by bsclifton** [comment]
I really like the round icons :smile: The logo still seems intact while having a nice clean shape.  Great job, @rickyrauch

**Comment by bsclifton** [comment]
@rickyrauch I think the various screen caps you are proposing look good... but one thing to consider (which can be a problem) is having enough space where a user and click and drag the window. We do get lots of complaints as-is about not enough draggable area in the top title bar

**Comment by rickyrauch** [comment]
@bsclifton @bradleyrichter 

Hi Brave, 

Based on the feedback I read on Twitter and asking people, we probably can work on some refinements of the UI. 

What do you think?

**Comment by bradleyrichter** [comment]
@rickyrauch Sure. What do you think we should start with? We can also jump on a g-hangout if you want to go over the twitter feedback you are receiving.

**Comment by rickyrauch** [comment]
I tried to clone the project to make some changes, but without this issue resolved https://github.com/brave/browser-laptop/issues/1171 it makes really hard to work on CSS.

**Comment by bradleyrichter** [comment]
I know we won't be able to change that behavior but editing in dev tools for live viewing and transferring over to the repo files has been workable.

**Comment by rickyrauch** [comment]
Feel free to use my icon @bsclifton, I can submit a PR.

**Comment by bradleyrichter** [comment]
@rickyrauch Can you post some 512 PNGs that I can test as an ICNS?

**Comment by bsclifton** [comment]
@rickyrauch what @bradleyrichter said :smile: He'll be able to help you the most.  Thanks!

**Comment by bradleyrichter** [comment]
preview next to the Mac OS competition:

![image](https://cloud.githubusercontent.com/assets/13509546/21754115/5a6a691a-d5ae-11e6-961b-f561fb1a1abb.png)

**Comment by rickyrauch** [comment]
It looks great, here is PNG 512.
https://www.dropbox.com/s/5dshp8nxgduk8dc/brave.png?dl=0

**Comment by Liunkae** [comment]
This would solve #5723. 😀

**Comment by rchrdnsh** [comment]
I vote for the first design in the issue, as it simplifies the UI of the omni bar and the tabs, which currently look awkward being separated. Wether or not the tabs are on top or on bottom of the omni bar i am less concerned with, although it might be a nice option to let people choose with an option. And a dark mode would be great as well, in addition to the simplification of the UI :-)
