### ISSUE TITLE
increase tabs height by 3 px

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#5978]
Currently we are winning the "browser-toolbars smallest stack height" award but recent feedback for users on high-res laptops have suggested that tabs are difficult to click on.

Usability trumps "minimal height" in most cases so adding back 3 px to the tab height will improve the click region without giving up our award completely. 

Doing this requires small changes in about 8-10 places given the current structure. 

In the future, we would be able to offer "compact mode" and "normal mode" in preferences simply by changing a variable. 

Today we just need 3 more px.

**Comment by Liunkae** [comment]
Original feedback: #5683

**Comment by Liunkae** [comment]
@bradleyrichter @bsclifton Does #6032 fix this?

**Comment by bradleyrichter** [comment]
@Liunkae it does, but solving the original feedback will probably need a lot more work to provide a large-mode for these hi-res or vision impaired situations.

**Comment by Liunkae** [comment]
OK, so how about we close this and leave #5683 open.

**Comment by bradleyrichter** [comment]
I made this issue for the sole purpose of having an issue to associate with the PR.  :   )

So, yes, closing now.
