### ISSUE TITLE
After manual check for update the hide button take multiple clicks to function

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#598]
If you manually check for update and no update is found the Hide button take about 3 clicks before it acknowledges it has been clicked and closes the notification bar.

**Comment by bbondy** [comment]
Not able to reproduce this one

**Comment by Tombsmen** [comment]
Please wait for follow up video.

**Comment by Tombsmen** [comment]
I will ahve to do a screen share sesion with something like Join.me or team viewer VLC keeps crashing when I try to record my screen, just let me know when Brian.

**Comment by bbondy** [comment]
I'll take a look at the code later to see if I can find a work around without reproducing.

**Comment by luixxiul** [comment]
Closing for now. If someone could reproduce please tell us how to.
