### ISSUE TITLE
Show bookmark favicon in bookmarks menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#5983]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From [support](https://linkbubble.zendesk.com/agent/tickets/6992)
> When using the Bookmarks Toolbar or when in the Bookmarks Manager,  favicons are present. However, when selecting a bookmarked site via  BookMarks on the Menu Bar, no favicons are shown, but need to be

**Expected behavior:**
Show bookmark favicon in bookmarks menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
>0.12.10 

- Screenshot if needed:

- Any related issues:
cc: @darkdh

**Comment by srirambv** [comment]
cc: @bsclifton

**Comment by bsclifton** [comment]
Definitely a good one- closing this one as as dupe

(original issue captured here - https://github.com/brave/browser-laptop/issues/3050)
