### ISSUE TITLE
Had to drop "Shields" to submit answers to online exam.

### ISSUE THREAD

**Issue by heb1048** [brave/browser-laptop#5985]
I got the following error when clicking "Submit" to answer exam questions for one of the Prager University short courses.  I am running Brave on Windows 7 Home Premium on a Toshiba laptop.  Here is the web site:  https://www.prageru.com/courses/political-science/do-you-understand-electoral-college to take a short course and then take the exam after listening and click "Submit".

![image](https://cloud.githubusercontent.com/assets/24320935/20842963/1c571124-b87f-11e6-8fc8-1054d58e10c8.png)

I love the new browser and am glad to see that your CEO has resurfaced after the Mozilla Injustice.

Carl

**Comment by privatzee** [comment]
Carl, somehow I got through everything okay with Shields up, Win7 x64. Have you seen that same error alert box more than once?

![image](https://cloud.githubusercontent.com/assets/22591438/20846975/23e6d53a-b89a-11e6-9d6c-c943193322f6.png)

Btw, same here regarding _Mozilla Injustice_.

**Comment by heb1048** [comment]
First time but I will try again.

Carl

**Comment by heb1048** [comment]
Well, it is working for me now.  I can’t explain why it failed the first time but I obviously can’t reproduce the failure.  Thanks for investigating and for a great new browser.

Carl

**Comment by privatzee** [comment]
Thanks for reporting it, Carl. I'll just add some keywords in case the same problem pops up anywhere in the future: error alert xhr ajax

Btw, I don't work for Brave. I just drop in sometimes to help out, initially because of that _injustice_ you spoke of.

**Comment by Liunkae** [comment]
I'll close the issue for now, but please reopen if the problem reappears.

**Comment by bsclifton** [comment]
From the look of the message box, my guess is that this issue was specific to the site.  Sometimes people will debug with alert() instead of a less invasive console.log().  Notice in the message box, it got an HTTP200 OK (which means the asynchronous call that was made loaded successfully)

**Comment by privatzee** [comment]
Aha, it's from Drupal:

![image](https://cloud.githubusercontent.com/assets/22591438/20854231/049e5894-b8c0-11e6-933f-f17f10076138.png)
