### ISSUE TITLE
[Request] add button with important options

### ISSUE THREAD

**Issue by Gelo3D** [brave/browser-laptop#5991]
**Did you search for similar issues before submitting this one?**

yes

**Describe the issue you encountered:**

If user need to go eg. settings or bookmarks, must press alt for get access to main or advanted options in browser. 
Browser in idea must be 'simple' browser. 
Don`t remove alt program menus, but create new button with options like settings, account etc. 
![screenshot_1](https://cloud.githubusercontent.com/assets/15075411/20847780/b94f8b3c-b8cf-11e6-8a28-370a5ed56151.png)

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1. First alpha / beta - create button.
    2. Second add only important items : 
settings, new windows, tab, privaty window, etc. other options still avaiable if user press alt and choose something menu.
    3. Contacts with testers for remove / add functionality dat button. 

- Screenshot if needed:

- Any related issues:

**Comment by josiah-keller** [comment]
The upper-left button with three vertical dots opens the main browser menu.  You can access settings, bookmarks, and such from there.

**Comment by Gelo3D** [comment]
Thx for information. 
But its really odd.

So i create 2 in my opinion better solutions. 
![1](https://cloud.githubusercontent.com/assets/15075411/20851596/b0900a28-b8e1-11e6-886e-17bbf3037aa7.png)

First solution is do add dot buttons to 4 other and remove it from tabs sector. 

![2](https://cloud.githubusercontent.com/assets/15075411/20851744/7f2f7e90-b8e2-11e6-9acb-9205bbf8de26.png)

**Comment by Gelo3D** [comment]
If 2nd solution, brave remove one button and marge it with shield settings. 
I thing shield settings can be smaller to more distance between options 
![2](https://cloud.githubusercontent.com/assets/15075411/20851967/a26a66da-b8e3-11e6-8e2b-962171a3f38e.png)

**Comment by Liunkae** [comment]
@Gelo3D Why do you want the menu and the Shields panel to be combined?

cc: @bradleyrichter

**Comment by josiah-keller** [comment]
How is it odd?  It's exactly the same as Chrome, which you held up as your original example.

**Comment by bradleyrichter** [comment]
@Gelo3D Can you list the important functions that you found missing from the burger menu as a new issue or by renaming this one? Chrome does not have alt-menus at all so they do need put more in the burger menu. 

Regarding the other issues and suggestions, we have not heard many complaints or received support tickets regarding the burger-menu location or the shields panel. It is located in the closest position possible to Chrome and Firefox so changing either of these would be problematic. 

Regardless, we appreciate all feedback and ideas so thanks for contributing. 

Closing this one now.
