### ISSUE TITLE
Url bar does not allow navigation

### ISSUE THREAD

**Issue by geowarin** [brave/browser-laptop#6005]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Cannot use the url bar to navigate by issuing either to a full url or a search term.
Nothing happens when you type enter or when you click on the search icon in the URL bar.

It used to happen only when opening a new window (CMD + N).
Now I cannot use the url bar even in the main window.

I also had the problem right before upgrading to the newest version of brave so I don't believe the issue has been introduced in the latest update.

**Expected behavior:**

Url bar is functional and be used to issue a search or navigate to an URL.

- Platform (Win7, 8, 10? macOS? Linux distro?):

MacOS 10.12.1 (Sierra)

- Brave Version:
0.12.11

- Steps to reproduce:
    1. Type something in the url bar
    2. Press enter or press the search icon on the left of the bar

**Comment by Liunkae** [comment]
As far as I know, the search icon does not currently do anything. However, could you please make sure your default search engine is set? See <https://github.com/brave/browser-laptop/wiki/End-User-FAQ#why-is-the-address-bar-not-working>.

**Comment by geowarin** [comment]
Yup. That works.
