### ISSUE TITLE
Refactoring #bitcoinDashboard dialog on about:preferences#payments (l10n)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6007]
**Describe the issue you encountered:**

- border-bottom on the bottom should not exist ("Done" button is not displayed if Coinbase is disabled)
- padding & margin should be refactored

<img width="722" alt="screenshot 2016-12-03 20 53 59" src="https://cloud.githubusercontent.com/assets/3362943/20859188/16384944-b99b-11e6-80e1-992b603be642.png">

**Expected behavior:**

The footer should be displayed.

<img width="736" alt="screenshot 2016-12-15 23 45 57" src="https://cloud.githubusercontent.com/assets/3362943/21228359/d5bb2bc2-c320-11e6-8b8e-d00dd30be58e.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

- Any related issues:

**Comment by luixxiul** [comment]
Reopening this as https://github.com/brave/browser-laptop/commit/21ece29eab80de4af2c606a65b54c13764b04c93 is refactored with #6047 which has a follow-up.

**Comment by bsclifton** [comment]
Closing because https://github.com/brave/browser-laptop/pull/6047 was just merged :smile:

**Comment by luixxiul** [comment]
Test Plan:
1. Disable Coinbase widget
2. Make sure every button on the dialog on about:preferences#payments works
