### ISSUE TITLE
Function addition: Highlight text and search 

### ISSUE THREAD

**Issue by Tombsmen** [brave/browser-laptop#601]
Select text and search selection using default search engine in a new tab, check chrome when you select a lince of text one of the options is Search Google for" Highlighted text" . Brave could simply use Search for "X". or you could do a nerdy Start Trek reference and use To Bravely Go " X".

**Comment by weems** [comment]
For whomever is implementing it might for security / privacy / useability reasons go with what ever search engine has been specified in Preferences as the default, so you can use DuckDuckGo and avoid any worry of stored searches / latent google tracking which in some way can't be mitigated by DoNotTrack.

**Comment by luixxiul** [comment]
Implemented #1672
