### ISSUE TITLE
Brave crashes.

### ISSUE THREAD

**Issue by quegley** [brave/browser-laptop#6010]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Randomly browsing.  Brave crashes.  Windows throws a low memory warning and asks to close Brave.  Brave displays error warning banner and attempts to restart.  Attempts to restart many times and then dies.  

**Expected behavior:**
NA

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version:0.11.5

- Steps to reproduce:
    1. NA
    2.
    3.

- Screenshot if needed:

- Any related issues: When attempting to verify github from Outlook and go to Brave (set as default) kills Windows entirely.

**Comment by Liunkae** [comment]
Could you please update to the latest version and try again? `Menu > Help > Check for Updates…` The current version is 0.12.11.

**Comment by bsclifton** [comment]
Closing- @quegley please do try a newer version and let us know how it looks :smile: If you have issues even then, please re-open this issue and be sure to share any important details
