### ISSUE TITLE
https://apple.com shows cert error for some users in Brave

### ISSUE THREAD

**Issue by swiftcoder** [brave/browser-laptop#6016]
Navigating to apple.com in the navigation bar expands the address to https://apple.com, which fails certificate validation:

<img width="578" alt="screen shot 2016-12-04 at 11 05 17 am" src="https://cloud.githubusercontent.com/assets/4706210/20868486/eb4573c0-ba11-11e6-8fbd-4c44cc3a26a4.png">

Navigating to www.apple.com expands the address to https://www.apple.com, which passes certificate validation.

Navigating to https://apple.com in Chrome works, so it appears that Crome follows the redirect before validating the cert.

**Comment by Liunkae** [comment]
I've had the same issue (Brave 0.12.11 on macOS 10.12.x). Navigating to `apple.com`, `http://apple.com`, or `https://apple.com` actually gives me a blank page. It works fine with Firefox and HTTPS Everywhere.
![image](https://cloud.githubusercontent.com/assets/19424103/20869159/054e5ffa-ba32-11e6-8a7d-0ee1046c5641.png)

**Comment by luixxiul** [comment]
On Chrome

````
Request URL:https://apple.com/
Request Method:GET
Status Code:301 MOVED PERMANENTLY
````

**Comment by da2x** [comment]
This bug is invalid!

**The certificate MUST be validated** before loading content and following redirects!

The error message says the certificate authority used by Apple is unknown. The issue you’re seeing may be triggered by a security gateway intercepting network traffic OR a system configuration error.

**Comment by swiftcoder** [comment]
That makes sense. And if we look at the certificates returned by the raw apple.com url, we can see that the intermediate CA looks somewhat funky (gists for brevity here):

https://gist.github.com/swiftcoder/052f7cce2219f1b69254ccc9b80fa975

Versus the cert chain vended by www.apple.com:

https://gist.github.com/swiftcoder/a83c2a10ed2eaec9d88eb3515437c4c8

However, I'm unclear why both Chrome and FireFox follow the redirect anyway, **even** when HTTPS Everywhere is setup. And the certificate validates just fine with curl as well:

```
$ curl -v https://apple.com                                                                                                                                                                 [15:53:50]
* Rebuilt URL to: https://apple.com/
*   Trying 17.178.96.59...
* Connected to apple.com (17.178.96.59) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: apple.com
* Server certificate: Apple IST CA 2 - G1
* Server certificate: GeoTrust Global CA
> GET / HTTP/1.1
> Host: apple.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 MOVED PERMANENTLY
< Server:
< Date:
< Referer:
< Location: https://www.apple.com/
< Content-type: text/html
< Connection: close
<
* Closing connection 0
```

Is Brave missing a required CA root?

**Comment by da2x** [comment]
> Is Brave missing a required CA root?

It could be. But it’s working for me just fine.

@swiftcoder, please provide the certificate details from inside Brave’s UI (on the error page: Advanced: Show Certificate). That should reveal exactly what is going on.

**Comment by Liunkae** [comment]
Yes, please post the certificate details. Here's what I'm getting in the web inspector (for the blank page):
![image](https://cloud.githubusercontent.com/assets/19424103/20911168/d3933710-bb2b-11e6-9d11-9df8b2ea6418.png)

**Comment by diracdeltas** [comment]
fwiw when i go to https://apple.com, the cert is valid; results may vary for different users depending if you have the intermediate certs cached, but that would be a problem on Apple's site configuration not Brave.

**Comment by swiftcoder** [comment]
I had to reinstall Brave over the weekend, and this issue no longer reproduces. I'm afraid we'll have to chalk it up to a configuration issue on my end.

**Comment by diracdeltas** [comment]
closing for now, thanks for looking into it.
