### ISSUE TITLE
Blank page when 2 tabs or more

### ISSUE THREAD

**Issue by Sileax** [brave/browser-laptop#6022]
- Platform : Linux Manjaro 16.10

- Brave Version:  0.12.11

- Steps to reproduce:
    1. Open any website as first tab
    2. Click on + fort load another tab
    3. Load a website

If it doesn't show the issue, wait 2-3 minutes and open a new tab

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/815158/21031181/c6c49c02-bd67-11e6-88a0-9ac877e749fb.png)

- Any related issues:

When 2 or more tabs are loaded, the first tab loads websites well, but any others only shows blank page.

**Comment by Liunkae** [comment]
Unfortunately, there are numerous reports of blank pages on Linux (#1392, #1471, #3787, #4928). At the moment, the only possible workaround is disabling hardware acceleration (#5513). By version 1.0.0, there should be an easier way to disable hardware acceleration.

**Comment by da2x** [comment]
@Sileax, AMD graphics?

**Comment by Sileax** [comment]
Yep AMD graphics @da2x

**Comment by Sileax** [comment]
Even when hardware acceleration is disabled, i still have the issue, it worked for 1h but after that... Bug re-appeared

**Comment by DivineOmega** [comment]
I am also experiencing this issue after switching the graphics card in my work computer to an AMD graphics card. This issue is occurring for me even with hardware acceleration disabled, as @Sileax mentioned.

**Comment by DivineOmega** [comment]
Further to this, it appears the pages are actually there, but simply not rendered. This is evident by moving the mouse pointer over the page and noticing it change from an arrow to a hand when hovering over where links should be appearing.

Also, the effect is not consitent for me. Sometimes the problem may not occur for a few hours, other times it appears after a few minutes. In almost all cases, a full restart of the browser is required to resolve the issue and merely closing and re-opening the tab (or creating a new tab to the same URL) does not seem to fix it.

**Comment by DivineOmega** [comment]
This may be related. After switching to the AMD graphics card, I'm also having an occasional issue whether the dropdown content from a dropdown box is rendered entirely black (literally a black box of the size the dropdown content should appear). I can still select items via the mouse or arrow keys, which works correctly.

**Comment by Liunkae** [comment]
@DivineOmega Like the screenshot the following comment? https://github.com/brave/browser-laptop/issues/3663#issuecomment-252910834

**Comment by DivineOmega** [comment]
@Liunkae Exactly like that.

**Comment by DivineOmega** [comment]
Unfortunately this issue is still present in Brave v0.13 Preview 7.

**Comment by Liunkae** [comment]
@DivineOmega Have you tried the `--ignore-gpu-blacklist` and `--disable-gpu` flags? They were suggested in #1471.

**Comment by bsclifton** [comment]
@DivineOmega your best bet would be updating your shortcut to launch with `--ignore-gpu-blacklist`.  We're working on a wiki entry which has more info:
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

(feel free to share steps for Linux if it works for you)

**Comment by bsclifton** [comment]
cc: @Sileax in case you wanted to try the above step too! 😄

**Comment by DivineOmega** [comment]
@bsclifton I *think* the `--ignore-gpu-blacklist` option has done the trick for me (Ubuntu 16.04 LTS, AMD/ATI graphic card). I'll set Brave back to default browser on this machine and report back if there is a problem.

I've added Linux instructions on how to change the `brave.desktop` file. https://github.com/brave/browser-laptop/wiki/Troubleshooting#linux

**Comment by bsclifton** [comment]
@DivineOmega very cool, thank you! 😄

**Comment by Sileax** [comment]
@bsclifton Sorry for not responding for a while, i switched to Nvidia gpu so the problem is not present anymore :)

**Comment by bsclifton** [comment]
Since we have a [documented workaround](https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003) and also because we're moving to [Brave Core](https://github.com/brave/brave-browser) and won't be addressing this before then, I believe it makes sense to close this issue
