### ISSUE TITLE
Close unanswered alert bar if initiating tab is closed before user makes decision

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6028]
Various alerts may open when a site asks permission. If the tab that initiates an alert is closed, then the alert(s) should also be closed as the user most likely no longer cares about making a decision about a closed tab.

![image](https://cloud.githubusercontent.com/assets/13509546/20894468/78944f0e-baca-11e6-8ce7-85a12eebd228.png)

cc @diracdeltas

**Comment by bsclifton** [comment]
moving to 0.14.3
