### ISSUE TITLE
Feature Request: instant position jump on scroll bar click

### ISSUE THREAD

**Issue by idprism** [brave/browser-laptop#6030]
In the Fedora build of firefox, it is possible to click on a position in the scroll bar and instantly jump to that location in the page. The brave behavior is to move 1 page in a direction according to whether the user clicks above or below the scroll bar.

Please allow an option for instant-jump scroll-bar clicking.

- Platform (Win7, 8, 10? macOS? Linux distro?): all platforms

- Brave Version: 0.12.9

- Steps to reproduce:
    1. go to any page with a scroll bar (much content).
    2. click near the bottom of the scroll bar.
    3. watch with frustration as the window renders 1 page down instead of several pages down.

This problem is worse on "HD" ratio (16:9) screens (which have less vertical real-estate & therefore more "pages").

- Any related issues:

**Comment by idprism** [comment]
No? I still would like this option. Is it hard to implement?

**Comment by idprism** [comment]
How do I change the config to allow this? I click in the middle of a 30 page scroll bar and I go 1 page down. 
Thanks!

**Comment by bsclifton** [comment]
@idprism I don't think this is something we have control over- the scrollbar is part of your operating system. You might be able to install an extension or change a configuration setting to get a different behavior
