### ISSUE TITLE
Clicking on Shields down on C54 crashes the browser

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6034]
STR:
1. Go to any website
2. Click lion icon
3. Click shields down

*Crash*

**Comment by darkdh** [comment]
fixed by e894132

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the bug appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
