### ISSUE TITLE
Bookmark dialog looks too skinny

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6036]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Perhaps related to the recent button refactor the bookmark dialog looks too skinny.

**Expected behavior:**
It should be wider, maybe around 300px?

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
master

- Steps to reproduce:
    1. Open Brave
    2. Click Bookmark star
    3. See how skinny it is :)

- Screenshot if needed:

What it used to look like:

<img width="428" alt="screen shot 2016-12-05 at 5 21 38 pm" src="https://cloud.githubusercontent.com/assets/490294/20909266/66fb43fc-bb0f-11e6-94da-ad8db7cbe32d.png">

What it looks like now:
<img width="353" alt="screen shot 2016-12-05 at 5 21 53 pm" src="https://cloud.githubusercontent.com/assets/490294/20909278/73245b64-bb0f-11e6-9392-6860fccb28c5.png">

- Any related issues:

@bradleyrichter assuming this is a bug I'll happily take it. Can you just decide and assign to me? Thanks!

**Comment by bradleyrichter** [comment]
I think #6000 fixes this...

**Comment by luixxiul** [comment]
Also the button alignment issue has been fixed with https://github.com/brave/browser-laptop/pull/6000/commits/1df8dc376ba08602a4394796fb91754321dca1ae of the same PR.

**Comment by bsclifton** [comment]
Confirmed this was fixed with #6000 
![screen shot 2016-12-06 at 11 15 18 pm](https://cloud.githubusercontent.com/assets/4733304/20956890/f576b4fe-bc09-11e6-8ffd-76c80d5f1368.png)

**Comment by luixxiul** [comment]
QA #6000 instead of this

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6000#issue-193263078
