### ISSUE TITLE
Unending refresh loop on asana.com

### ISSUE THREAD

**Issue by clockworkpc** [brave/browser-laptop#6038]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Unending refresh loop when I log into asana.com.  As soon as the site loads, I am taken back to the loading page.

**Expected behavior:**
1. Log in to asana.com
2. Navigate the website 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Go to asana.com
    2. Log in
    3. Attempt to navigate the site

- Screenshot if needed:
![screenshot from 2016-12-06 12-48-28](https://cloud.githubusercontent.com/assets/9858440/20909947/b6051ab0-bbb2-11e6-8f36-e81ae1017769.png)

- Any related issues:

**Comment by bsclifton** [comment]
Thanks for reporting, @clockworkpc! We have another issue tracking this if you'd like to follow it:
https://github.com/brave/browser-laptop/issues/4694

Closing this particular issue as a duplicate
