### ISSUE TITLE
Allow user to disable tiles on about:newtab and offer option to clear any associated data

### ISSUE THREAD

**Issue by 2OldMan** [brave/browser-laptop#6042]
Too difficult to keep deleting thumbs from Brave homepage.  Want to disable it.  Shows search history.  Thought Brave didn't keep search history?  Brave has the potential for being superb.  It takes a lot to get it all worked out so don't get discouraged.  I just don't want my search history recorded at all.  No thumbs, nothing.  Thank you.

**Comment by bradleyrichter** [comment]
@2OldMan Great suggestion and yes, getting it all worked out.

We'll add thumbs (tiles) to the clear-data options first, and then add a way of disabling the tiles all together.

cc @bsclifton

**Comment by bsclifton** [comment]
This is a great feature request- I'll update the title to be more specific

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/8766

**Comment by Chenthu** [comment]
+1

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/disabling-new-page-thumbs/4596)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/how-to-permanently-remove-icons-at-startup/16882/3?u=eljuno

**Comment by marvindanig** [comment]
I’d recommend brave added only neutral or nonprofit sites on its default palette. Or put BAT enabled content sites in front.

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/Smithcraft1/status/977521640312512514

**Comment by eljuno** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8fzw2p/is_there_a_way_to_disable_the_top_site_thumbnails/

**Comment by zeromus** [comment]
:+1: from right here. Need to disable tiles.

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/PayLab1224/status/1023640310251962368

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/353
