### ISSUE TITLE
Article thumbnails not loading on http://www.recode.net

### ISSUE THREAD

**Issue by muralisr** [brave/browser-laptop#6044]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On news website http://www.recode.net, thumbnails for articles do not load as expected.

**Expected behavior:**
Expected thumbnail images to load on frontpage article list.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10

- Brave Version:
0.12.12
- Steps to reproduce:
    1. Open http://www.recode.net/
    2. Scroll down below banner image to view list of articles
    3. Observe thumbnails absent

- Screenshot if needed:
Here is how it looks on Brave - 
![brave-recode](https://cloud.githubusercontent.com/assets/2168895/20926590/09b467ea-bbb5-11e6-985d-0b65a82d1f8f.png)

And here is how I expect it to look (screenshot from Chrome) -
![chrome-recode](https://cloud.githubusercontent.com/assets/2168895/20926597/140512b2-bbb5-11e6-866d-dbf4be5a054c.png)

- Any related issues:

**Comment by srirambv** [comment]
Disabling HTTPSE shows the images 
![image](https://cloud.githubusercontent.com/assets/17010094/20926666/840c35fe-bbb5-11e6-848b-24ad0e020812.png)

**Comment by diracdeltas** [comment]
it appears that Recode has fixed the issue
