### ISSUE TITLE
Webroots marks Brave as W32.Trojan.Gen 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6046]
From [support ](https://linkbubble.zendesk.com/agent/tickets/7166)
> Webroot picks up W32.Trojan.Gen in a couple of your executables. 

Screenshot available in zendesk ticket

cc: @diracdeltas

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7165)

**Comment by chadmando** [comment]
I ran into the same issue this morning.  The Webroot admin console identifies the quarantined files as:

bravedefualts.exe - %appdata%\brave\app-0.12.12\
brave.exe - %appdata%\brave\

**Comment by srirambv** [comment]
+1 from [support](https://linkbubble.zendesk.com/agent/tickets/7199)

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7194)

**Comment by bsclifton** [comment]
I wonder if this is solved by 0.12.4? (which includes certificate expiration fix)?

**Comment by bbondy** [comment]
*0.12.14

**Comment by bsclifton** [comment]
Closing as stale.  If users run into this, let's re-open and take action 😄

**Comment by luc0** [comment]
It's happening in 0.21.18

360 total security detects brave.exe as:
HEUR/QVM20.1.EE41.Malware.Gen

**Comment by dasice** [comment]
I'm seeing it in 0.21.18 and also in 0.21.24
