### ISSUE TITLE
No platform for linux

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#605]
Not quite sure when this happens because it isn't every time, probably first time after a `git pull;npm install`. But sometimes when runing `npm start` on linux to start brave and then exiting brave later I see the following message on the console

```
{ statusCode: 400,
  error: 'Bad Request',
  message: 'child "platform" fails because ["platform" must be one of [winx64, osx]]',
  validation: { source: 'params', keys: [ 'platform' ] } }

```

I think the relevant code is in app/updater.js specifically the array definition at line 30 and whetever uses it.

```
// this maps the result of a call to process.platform to an update API identifier
var platforms = {
  'darwin': 'osx',
  'win32': 'winx64'
}
```

I suspect there should be a third entry for linux

**Comment by luixxiul** [comment]
Is this not critical, @bbondy?

**Comment by bbondy** [comment]
Sounds like a valid issue but I don't think it's causing any major problems. To fix we just need to disable the updater code more on linux since there we will handle updates via repository updates.

**Comment by srirambv** [comment]
@FrancisTurner Do you still see this problem on Linux?

**Comment by bsclifton** [comment]
Closing as we removed the update functionality from Linux builds
