### ISSUE TITLE
Lower session write for dev environment

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6056]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
It would be nice if when working in dev mode the session write would be reduced from 5 minutes. That way when making changes quickly refreshes would reload your tabs with the current information.

Ideally we could check the process.env in https://github.com/brave/browser-laptop/blob/master/js/constants/appConfig.js and just set it to 30 seconds or something for dev and leave it at 5 minutes for prod.

**Expected behavior:**
Right now when you make quick changes the tabs and session state keep reverting to the way they were 5 minutes ago.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All.

- Brave Version:
All.

- Steps to reproduce:
    1. Start Brave from master
    2. Open a few new tabs
    3. Save a change that causes the browser to refresh.
    4. Notice the tabs revert

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Available as environment variable `BRAVE_SESSION_SAVE_INTERVAL` (in milliseconds)
