### ISSUE TITLE
ZenHub: "Sign in" link doesn't work

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6057]
**Describe the issue you encountered:**
The DOM-injected "Sign in now" link doesn't sign the user in; the user must instead use the browser action popup window.

**Expected behavior:**
The user can sign in via any _sign in_ link provided by the ZenHub extension.

**Brave Version:** 0.12.12

**Screenshot if needed:**

![image](https://cloud.githubusercontent.com/assets/815158/20946596/f90f2076-bbd0-11e6-85fc-5ceb9d78bdaa.png)

**Comment by martinheidegger** [comment]
Are third-party cookies activated?

**Comment by bsclifton** [comment]
@bbondy I think you're using ZenHub - can you check this on Brave Core?
