### ISSUE TITLE
Payment history footer message needs correct past/future context 

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6059]
problem: (your next contribution is 6 days ago)

![image](https://cloud.githubusercontent.com/assets/13509546/20951005/1c664b88-bbd8-11e6-906a-08cc98eaeca9.png)

code point:

https://github.com/brave/browser-laptop/blob/d86d9638f141c890276bc9d90c5a1dd01d3c6bd5/js/about/preferences.js#L963

**Comment by bkilrain** [comment]
@bsclifton Hi there - I took it upon myself to give this one a try. I've poked through the codebase and it seems that paymentHistoryFooter should always refer to an action in the past. So I just adjusted the language to reflect that. 

One potential problem: I found that NextReconcileDate status also uses the same past tense phrase that paymentHistoryFooter used from the moment.js library. I did a search on issues for this and found #4058. I guess this should be a separate issue... but just mentioning it here for posterity.

**Comment by luixxiul** [comment]
@bkardell @mrose17 Is #6628 replaced with #6766?

**Comment by mrose17** [comment]
@luixxiul - i didn't see that PR, @bkardell - sorry!

@luixxiul - the code in #6766 is what we want because it handles each of the past/present/future cases, so #6628 should be closed without being merged...

**Comment by bsclifton** [comment]
cc: the original contributor for https://github.com/brave/browser-laptop/pull/6628 @bkilrain (whose handle was accidentally typo'ed as @bkardell). Lots of Brians in here! :heart:

**Comment by luixxiul** [comment]
@bkilrain sorry for typo...
