### ISSUE TITLE
Reset Views/Time Spent on start of new period.

### ISSUE THREAD

**Issue by sanderaarts** [brave/browser-laptop#6064]
**Did you search for similar issues before submitting this one?**
Yes. Hopefully good enough ;)

**Describe the issue you encountered:**
On the Brave Payments page under Preferences the list of visited sites does not get reset after the contribution due date passes and payment is been made.

**Expected behavior:**
I'd expect Views and Time Spent (and consequently Rank and %) to be reset to 0 once a new payment period starts since the visits from previous periods have already been paid for (or not, depending on the user's setting at that time).

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X Yosemite (10.10.5)

- Brave Version:
0.12.12

**Comment by luixxiul** [comment]
CC @mrose17 for thoughts

**Comment by mrose17** [comment]
@luixxiul - thanks for the note. here's what i know:

the way "it's supposed to work" is that the synopsis keeps track of the last 30 days of activity. this is controlled by these two options in ledger-synopsis.json:

    "numFrames": 30,
    "frameSize": 86400000,

a frame is a day long (86400 seconds) and there are 30 frames that collect viewing activity.

if this isn't the behavior we're seeing, then "that's a bug".

the reason why it works this way rather than resetting everything back to zero, is to provide a better averaging of the activity for people to see. you always know what you've done over the last 30 days of real-time; however, the activity from the last contribution will be gone by the time the next contribution is made.

does that make sense?

**Comment by sanderaarts** [comment]
I believe the current implementation makes sense from a "what have I been up to last month" perspective, but from a "how will my next contribution be divided" perspective it seems rather confusing. And since the latter is the context of that list I'd say it makes more sense to start from scratch every time a new contribution period starts.

Let's say the user spends a couple of hours on a website the day before a contribution takes place, but no longer after that. The website will still show up in the list during most of the next period, perhaps even with a high rank still, only to drop off of it the day before the next contribution day.

Perhaps the list can have two views: "last 30 days" and "this contribution period" that the user can toggle between.

**Comment by mrose17** [comment]
@sanderaarts - thanks. the question i have is whether this really helps or not. over the course of the 30 days the numbers shift from where things were for the last contribution to where they'll be for the next contribution.  at the beginning of that time, the "next contribution" values will be very thin, and by the end of that time, the two sets of values will be near identical.

the "very thin" part is a concern. we've gotten some rather direct feedback that people want to know what's been going on for the last 30-days (they were unhappy when opting-in and seeing a near-empty viewing synopsis).

the issue in having a switch is that it's yet another option; however, i'm adding @bradleyrichter to this thread, to get his view on the matter...

thanks for letting me know the other side of it!

**Comment by sanderaarts** [comment]
@mrose17 - I understand that the lists will be (or should be at least) identical at the end of the period. But where one only changes when the user visits websites, which makes sense since that is what the contribution system is based on, the other changes over time though, even if the user doesn't visit any new websites, as previous visits drop off. From a paying for what you use perspective that seem weird.

That's just my opinion of course and I can imagine that when one turns the feature on that they want to get some feedback. But isn't that something that's only the case the very first time?
