### ISSUE TITLE
Selecting Indian Languages causes AM/PM to appear twice on newtab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6065]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Selecting Indian Languages causes AM/PM to appear twice on newtab

**Expected behavior:**
Should either show similar to US Time format of AM/PM or should not show similar to other Languages

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.13 RC2 (Yet to verify on older builds)

- Steps to reproduce:
    1. Set browser language to Bengali(India/Bangladesh), Hindi or Telgu
    2. Open a new tab and AM/PM is superscript of AM/PM
    3. Select Portugese(Brazil)/ Turkish/Spanish, doesn't show AM/PM next to time

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/20967752/fad46486-bc78-11e6-9aa3-dbb46c01bd90.png)

- Any related issues:
cc: @cezaraugusto @bsclifton

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3
