### ISSUE TITLE
Add about:blank to options for start page and new tabs

### ISSUE THREAD

**Issue by sanderaarts** [brave/browser-laptop#6066]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
In General Settings the select boxes for 'Brave starts with' and 'A new tab shows' don't offer the option to select an empty page. It is of course possible to select 'my home page' in both and then set the home page to about:blank, but this is not very user friendly and leaves one with new empty tabs where the location bar doesn't get focus automatically, as it does for the default new tabs page.

**Expected behavior:**
The option to select 'An empty page' (about:blank) for both the starting page and new tab page, where, once opened, the location bar has focus as there's no other way to interact with the page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X Yosemite (10.10.5)

- Brave Version:
0.12.12

**Comment by bsclifton** [comment]
I'm happy to share that this will be in our next release (0.13.0) :smile: The issue was fixed with https://github.com/brave/browser-laptop/pull/5690
