### ISSUE TITLE
Brave window title bar is messy in macOS in right-to-left languages

### ISSUE THREAD

**Issue by amire80** [brave/browser-laptop#6068]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
macOS Sierra has better support for RTL languages than the earlier macOS/OSX versions. Among other things, it automatically reorients window title bars to be right-to-left.

Brave makes some customizations to the window title bar, and these were probably only made for left-to-right languages, so some things there look incorrectly:

- The lion icon overlaps the red-yellow-green buttons.
- The back and forward buttons are not quite where they are supposed to be.

**Expected behavior:**
The lion icon should be on the other side, and the back and forward buttons should be at the same location as the back and forward button in the macOS Finder.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS Sierra 10.12.1.

- Brave Version:
0.12.12
Muon 1.4.28

- Steps to reproduce:
    1. Set macOS UI language to Hebrew and restart your computer.
    2. Open the browser and take a look at the top window title bar.

- Screenshot if needed:
<img width="1680" alt="2016 12 07 15 35 19" src="https://cloud.githubusercontent.com/assets/346271/20969689/d3f197de-bc92-11e6-88ef-625465cbc34c.png">

- Any related issues:
It would be nice to have to Browser's UI translated into Hebrew. I'll be happy to help with that—I'm experienced with software translation.

**Comment by Liunkae** [comment]
@amire80 If you would like to help translate, please see https://www.transifex.com/brave/brave-laptop/.

**Comment by amire80** [comment]
Yep, I requested my language... I hope somebody approves it :)

**Comment by bradleyrichter** [comment]
wow! I am surprised that Mac OS mirrored the controls.

@amire80 How does it feel compared to past layouts?

Fortunately we should be able to solve this easily by using the windows button positions.

@bsclifton ?

**Comment by amire80** [comment]
> wow! I am surprised that Mac OS mirrored the controls.
> @amire80 How does it feel compared to past layouts?

I'm a recent Mac user, and even more recent Brave user, so there isn't much that I can say past.

OSX El Capitan kinda supported RTL languages, too, but had a bunch of bugs in the title bar, messy back and forward in the finder, and some other problems. So if you make any changes for RTL languages, you may want to test them on older OSX versions, although working well with the newest macOS is probably the priority.

**Comment by bsclifton** [comment]
I think this should be easy to solve... but may require some interesting CSS hacks

Maybe someone can help recommend a proper way to detect RTL?  We have access to Node.js in the browser process, so we're able to query the host OS

**Comment by bsclifton** [comment]
Closing as `wontfix`... For folks that are using RTL layout, can you please try the new [Developer channel release](https://brave.com/download-dev) (`brave-core`)?  If this is still an problem, let's open an issue here:
https://github.com/brave/brave-browser/issues
