### ISSUE TITLE
Twitter pools doesn't work

### ISSUE THREAD

**Issue by jaydson** [brave/browser-laptop#6069]
**Did you search for similar issues before submitting this one?**
No.

**Describe the issue you encountered:**
Twitter pools doesn't work.

**Expected behavior:**
Vote successfully on given Twitter pool.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.10

- Brave Version:
0.12.9

- Steps to reproduce:
    1. Go to https://twitter.com/_ericelliott/status/806457787618209792
    2. Select an option
    3. Click "Vote"

- Screenshot if needed:
![screenshot from 2016-12-07 13-46-02](https://cloud.githubusercontent.com/assets/72206/20974485/8458369c-bc83-11e6-809f-fb375dc9ae4a.png)

- Any related issues:

**Comment by bsclifton** [comment]
Closing this issue, as it's a duplicate; but you can track progress at https://github.com/brave/browser-laptop/issues/4670

**Comment by jaydson** [comment]
Thank you @bsclifton .
