### ISSUE TITLE
Download - Save as - File extension gets lost in case of changing name

### ISSUE THREAD

**Issue by icecoldsquirrel** [brave/browser-laptop#6076]
**Did you search for similar issues before submitting this one?**
Y
**Describe the issue you encountered:**
If name is change in Save as Window and not written with file extension it is saved without it. 
**Expected behavior:**
renamed file should keep file extension whether you specified it or not
- Platform (Win7, 8, 10? macOS? Linux distro?):
win 8.1
- Brave Version:
all so far
- Steps to reproduce:
    1. Download File with Save as
    2. Change the name and do not keep the extension
    3. Go to your download folder

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Closing this in favor of #6076
