### ISSUE TITLE
Favicons missing from the bookmarks bar

### ISSUE THREAD

**Issue by khaosdoctor** [brave/browser-laptop#6077]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some bookmarks I imported from chrome are missing favicons, even after I open and log into them

![](https://i.imgur.com/V3q9g7w.png)

Also, some favicons are misplaced: 

![](https://i.imgur.com/rPprNK4.png)

One of those (the left one) is pinterest, the other is gmail.

**Expected behavior:**
All Favicons should be loaded and cached when I enter the website

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS Sierra

- Brave Version: 0.12.13

- Steps to reproduce:
    1. Import content from chrome
    2. Access a website (like linkedin, twitter, gmail, stackoverflow, aws)
    3. Don't see the favicons

- Screenshot if needed: Up in the description

**Comment by bradleyrichter** [comment]
@bsclifton Can we add a forced refresh at some point that makes sense?

**Comment by bsclifton** [comment]
@bradleyrichter yes- we should be able to do that.  We'd want to do something creative, like load all the icons in a hidden webview (so that it takes advantage of existing events)

**Comment by pascalwhoop** [comment]
I have observed a similar issue with my bookmark favicons having been manually loaded after import (by opening the websites a couple of times and let them sit there for a minute until the bookmark favicon was set), but now they disappeared again. Not sure why, I assume caching of some sort. 

I also noticed that the only way to get both favicons without text and folders with text is using the  "favicon and text" and then putting a space for the name of the favicon. If it doesn't have a name it defaults back to the URL which can only be prevented if the bookmarks name is !=""

**Comment by fuzzygroup** [comment]
I just installed 0.13.4 for the Mac and I never see favicons on the bookmarks toolbar even for something like Gmail which I know has them in both Chrome and FireFox.  

Thank you for a lovely browser.

**Comment by fuzzygroup** [comment]
Oh and the trick for using a space for the text as described by pascalwhoop no longer works.

**Comment by khaosdoctor** [comment]
I think this has been addressed on #6078

**Comment by jamesray1** [comment]
Similarly sometimes no favicons show, so I have to close the bookmarks toolbar and reopen it.

 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.13.0-36-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
