### ISSUE TITLE
[Feature Request] Bookmark text only for folders

### ISSUE THREAD

**Issue by khaosdoctor** [brave/browser-laptop#6078]
I think it would be an awesome feature to have the option to display only text for the folders in the bookmark bar:

![](https://i.imgur.com/T3LJBo7.png)

like this:

![](https://i.imgur.com/TwQUiBN.png)

**Comment by Liunkae** [comment]
@bradleyrichter Do you think this should be a setting, or should folder titles be shown all the time?

**Comment by bradleyrichter** [comment]
@Liunkae I think it makes sense to show folder names all the time since they are almost unusable without names as shown by @khaosdoctor ...

**Comment by Liunkae** [comment]
Great, I'll take this. 😉

**Comment by Liunkae** [comment]
See PR #6095.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6095#issue-194409719

**Comment by jamesray1** [comment]
Additionally some page bookmarks just have a generic file favicon, or there may be bookmarks that have the same favicon (e.g. Github bookmarks) so it would be good to add text for a favicon as an option (but without by default).
