### ISSUE TITLE
OSX : Error opening app , not a valid electron app

### ISSUE THREAD

**Issue by hardfire** [brave/browser-laptop#608]
On OSX,
after a `npm install` , the `npm start` command fails with the following error 

> The app provided is not a valid Electron app, please read the docs on how to write one:
> https://github.com/atom/electron/tree/vundefined/docs
> 
> Error: Cannot find module 'request'

Then I installed the request module manually and now the error is 

> The app provided is not a valid Electron app, please read the docs on how to write one:
> https://github.com/atom/electron/tree/vundefined/docs
> 
> Error: Cannot find module '/Volumes/Data/Programs/brave/browser-laptop/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'

While i try to play hoops with the errors here, would be great if someone knows the issue and has a quick fix.

**Comment by rob-blasetti** [comment]
I had this on OS X too, try this:
1. `rm -rf node_modules`
2. `sudo npm install --unsafe-perm`
3. in one tab `npm run watch`
4. in a different tab `npm start`

**Comment by hardfire** [comment]
Ok, this is possibly because of node v4, updated it to node v5 and now it atleast starts.

**Comment by hardfire** [comment]
@rob-blasetti i deleted the node_modules as well after updating the node version. Possibly there were some old node modules. Thanks !
