### ISSUE TITLE
Add 3rd Party Iframe Blocking

### ISSUE THREAD

**Issue by harshanvn** [brave/browser-laptop#609]
Would be nice to have some of the uBlock's <a href="https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode">Medium blocking</a> mode functionality here..
See the <a href="https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-Benefits-of-blocking-3rd-party-iframe-tags">benefits!!</a>

**Comment by diracdeltas** [comment]
related: #231

**Comment by luixxiul** [comment]
Script blocking was implemented with #1564
