### ISSUE TITLE
urlbar text is sometimes too high

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#6097]
I can't repro this consistently, but the URLbar text is sometimes misaligned.

1. set Preferences 'Always show the URL bar'
2. click on the link in https://twitter.com/bcrypt/status/806589197083475968
3. sometimes the urlbar text is too high:
![screen shot 2016-12-08 at 7 40 40 pm](https://cloud.githubusercontent.com/assets/549654/21025014/b6c94bf6-bd7e-11e6-9504-767107ec420d.png)

**Comment by bradleyrichter** [comment]
yikes. That looks like it's trying to vertically center a 2-line string.

**Comment by bbondy** [comment]
@diracdeltas I've never seen this, next time you see it could you try tweaking css styles? Like maybe try and see if `white-space: nowrap;` works.
