### ISSUE TITLE
Norton blocks Brave, categorizing as "medium risk"

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6100]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some users running Norton antivirus software may not be able to install Brave.

**Expected behavior:**
The user is able to run Norton antivirus security software on their machine, and not have their Brave download prevented, or interrupted.

**Screenshot if needed:**
![image](https://cloud.githubusercontent.com/assets/815158/21028435/c59ad11e-bd5a-11e6-956d-a09352a368c2.png)

**Comment by bbondy** [comment]
@jonathansampson could you reach out to norton? Usually AV companies have a form you can fill in to whitelist your product.

**Comment by jonathansampson** [comment]
@bbondy Absolutely; I'll do so immediately.

**Comment by diracdeltas** [comment]
Our contacts at Symantec says it's been resolved now; please re-open if not. Thanks.
