### ISSUE TITLE
Can't move tabs to after the last tab

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#6102]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

I'm unable to move a tab to where it is the last tab. I have to move it to be second to last, then move the last tab back, switching with the other tab. See gif link below.

**Expected behavior:**

I expect to be able to move a tab to the end of the tab list.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version:

0.12.13

- Steps to reproduce:
    1. Open multiple tabs in a window.
    2. Try to drag one of the tabs to make it the last tab.

- Screenshot if needed:

https://cl.ly/172K0J0E2u2d

**Comment by srirambv** [comment]
This actually works. You can move a tab after the last tab. The tab drag has to be beyond the favicon position of the last tab. If the tab is released before that it doesn't snap in as the last tab, but if you drag a tab beyond the favicon position of the last tab and then release it snaps in as the last tab.  

Both scenario shown here
![lasttab1](https://cloud.githubusercontent.com/assets/17010094/21067243/db64cf1a-be61-11e6-93c6-ad63a4079621.gif)


@echosa Could you try dragging the tab beyond the favicon position of the last tab and check if it snaps in as the last tab.

**Comment by echosa** [comment]
Ah, so it does work similar to what you said. It doesn't have anything to do with the favicon. It has to be dragged to more than half of the last tab. If you drag and drop onto the first half of the last tab, it doesn't work. If you drag and drop onto the last half of the last tab, it does work. However, I expected to be able to drag and drop *past* the last tab (like where the new tab `+` is, or maybe even further). That does not work, which is what I was attempting when I made this ticket. 

I guess dragging and dropping onto the second half of the last tab is a workaround for now, but the UI of it isn't great. This could be fixed by making the tabs physically move/swap places during the dragging part of the process, like browsers do. There's another issue for that: https://github.com/brave/browser-laptop/issues/6033

**Comment by bsclifton** [comment]
@echosa I agree- it feels bad; would love to see #6033 tackled :smile:
