### ISSUE TITLE
Address bar should autocomplete from custom bookmark titles

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#6104]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I sometimes bookmark URLs I'll know I'll need again. When I start typing their names (not just addresses) Brave should match it and suggest a completion.

**Expected behavior:**
Brave doesn't match anything.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac, Windows

- Brave Version:
Brave	0.12.13
Muon	1.4.30
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	darwin
os.release	16.3.0
os.arch	x64

- Steps to reproduce:
    1. Bookmark an URL with a distinctive title, e.g. "testmark"
    2. Type "testmark" into the URL bar

**Comment by Liunkae** [comment]
Firefox and Safari both have this functionality.

**Comment by bsclifton** [comment]
Bigtime +1 :smile: 

cc: @aekeus @bradleyrichter

**Comment by NejcZdovc** [comment]
Will be fixed in #10136
