### ISSUE TITLE
Consider IETab Extension to support enterprise websites on Brave

### ISSUE THREAD

**Issue by bogas04** [brave/browser-laptop#6109]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Enterprise websites built on ActiveX and other horrible IE specific APIs can't be viewed on Brave (or any other browser for that matter). Inclusion of [IE Tab](https://chrome.google.com/webstore/detail/ie-tab/hehijbfgiekmjfkfjpbkbammjbdenadd?hl=en) can help a little with this issue.

**Comment by bradleyrichter** [comment]
Definitely worth considering based on num of users:

![image](https://cloud.githubusercontent.com/assets/13509546/21076815/52089506-beea-11e6-844c-11e49d095e76.png)

**Comment by bogas04** [comment]
Any progress on this ? Can we move it to the Project Board ?

**Comment by srirambv** [comment]
@bogas04  Added [here](https://github.com/brave/browser-laptop/projects/1#card-1247247)

**Comment by srirambv** [comment]
Closing  #6109 as IETab extension added in projects.

**Comment by ScottLloyd** [comment]
The [IETab project](https://github.com/brave/browser-laptop/projects/1#card-1247247 ) 1247247 seems to be missing.  So, what's the status? Was it dropped?

BTW, I attempted to [add the Chrome Extension](https://brave.com/blog/loading-chrome-extensions-in-brave/) for IETab to Brave browser-laptop clone.  It kinda worked, but there seemed to be no way to get the extension to register as an official extension.  There is obviously more that needs to be done.  Just trying to follow the progress.

**Comment by bsclifton** [comment]
cc: @jonathansampson
