### ISSUE TITLE
Select Next Tab/Select Previous Tab

### ISSUE THREAD

**Issue by RIanDeLaCruz** [brave/browser-laptop#611]
Using the keyboard shortcut for selecting next tab `ctrl+arrow right` and select previous tab `ctrl+shft+arrow right` isn't working

I'm on an OS X 10.11.3

**Comment by psimyn** [comment]
Is it supposed to work? `ctrl+tab` / `ctrl+shift+tab` I think do what you're after

**Comment by bbondy** [comment]
Agreed with @psimyn I don't think this is a standard shortcut key for selecting next/previous tabs. Closing.
