### ISSUE TITLE
"It can remove the site" ledger test failing

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6110]
See https://github.com/brave/browser-laptop/blob/5ee0d07945675ed22c6002d9674ce339894e69a7/test/components/ledgerPanelTest.js#L199

Steps to reproduce
- Window 1: run `npm run watch-test`
- Window 2: run `npm run test -- --grep="synopsis can disable site"`

I think the root cause is that the time for a visit was bumped up and the test doesn't wait for long enough to register a visit (but not exactly sure).

**Comment by mrose17** [comment]
@bsclifton - who "owns" that test?

**Comment by bsclifton** [comment]
@mrose17 I just ran it locally and it's passing now :smile: so I don't think we need an owner.  Closing
