### ISSUE TITLE
Pressing back on error page causes infinite page reload

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6113]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Pressing back on error page causes infinite page reload

**Expected behavior:**
If tab history exists then should take back to the previous history item/page which was loaded before visiting the wrong domain. If no tab history is there then back button should be disabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.13

- Steps to reproduce:
    1. Visit a bunch of sites in a tab to have history entries
    2. Visit an invalid domain `brave.123` so that about:error is shown
    3. Press back button shown on the page, doesn't navigate back in history items
    4. Press the back navigation button, page goes into infinite loop and its impossible to visit the history items. Long press doesn't bring the history list as the page is going in an infinite loop 

- Screenshot if needed:
![errortab1](https://cloud.githubusercontent.com/assets/17010094/21052012/c36dd592-be1a-11e6-9702-d116da3df15f.gif)

- Any related issues:
#5177 and possibly #4502
  cc: @darkdh @bsclifton

**Comment by Liunkae** [comment]
I can also reproduce with Brave 0.12.13 on macOS 10.12.x.

**Comment by nycdotnet** [comment]
I am running into this on launch.  Uninstalling and reinstalling Brave did not help, so I am effectively prevented from using Brave on my Windows install now.  Windows 10 fully patched, Brave latest public release from brave.com.  Will try to uninstall and delete any registry keys next.

**Comment by Liunkae** [comment]
@nycdotnet Please try the steps listed here: https://community.brave.com/t/how-to-solve-almost-every-problem-after-install/605
