### ISSUE TITLE
Photo edit fail on photos.google.com when fingerprint detection on

### ISSUE THREAD

**Issue by getsetbro** [brave/browser-laptop#6114]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Unable to use the photo edit mode on photos.google.com - <CANVAS/> element is broken.
**Expected behavior:**
Should be able to view the photo in edit mode but it's missing.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS El Capitan 10.11.6 (15G1108)
- Brave Version:
Brave	0.12.13
- Steps to reproduce:
    1. View a pic in your account at photos.google.com
    2. Click to edit
    3. Notice the photo is not there for editing

- Screenshot if needed:

- Any related issues:
The <CANVAS/> element is broken when fingerprint detection is on.

**Comment by bsclifton** [comment]
Thanks for the report! We're tracking this particular issue (which has many Google subdomains already) here: https://github.com/brave/browser-laptop/issues/2965
