### ISSUE TITLE
Unable to view certificate details

### ISSUE THREAD

**Issue by Silverslavery** [brave/browser-laptop#6116]
Brave	0.12.13
Muon	1.4.30
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	win32
os.release	6.1.7601
os.arch	x64

Browser does not show any certificate information, not even through the developer options.
![bravesnip1](https://cloud.githubusercontent.com/assets/24474953/21050361/248fcf3c-be12-11e6-9dd6-17eef93b5ec4.JPG)
![bravesnip2](https://cloud.githubusercontent.com/assets/24474953/21051392/f217e85e-be17-11e6-89af-025ff002ff00.JPG)

Not even clicking on "View certificate" triggers anything. 

Just wanted to let you guys know.

**Comment by Liunkae** [comment]
Thanks @Silverslavery! This is definitely something that needs to be fixed. We have issues filed for viewing certificates in general (#1248) and viewing certificates in the dev tools (#2611). Closing as a duplicate.
