### ISSUE TITLE
Bring back the open tabs after update

### ISSUE THREAD

**Issue by obastemur** [brave/browser-laptop#612]
It could be really nice to have the tabs back after the software is updated.

**Comment by bradleyrichter** [comment]
++ @bbondy

**Comment by luixxiul** [comment]
+1

**Comment by luixxiul** [comment]
Already implemented, right? CC: @bbondy

**Comment by bbondy** [comment]
this should already be working, but perhaps doesn't work intermittently.

**Comment by obastemur** [comment]
Okay Thanks
