### ISSUE TITLE
webview.focus stopped working in C54

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6122]
STR:
- Load brave.com

Expected result: You can press spacebar to scroll.
Actual results: URL is still focused.

**Comment by bbondy** [comment]
This causes various tests to fail

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/electron/commit/f4e1e2ec32c08a35ac31682787f4265ba4ca7ea8

**Comment by luixxiul** [comment]
Test plan: available in the 1st post
