### ISSUE TITLE
rt-click on stats to reset values to zero

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6124]
Users would like to reset the values at any time desired.

mock:
![image](https://cloud.githubusercontent.com/assets/13509546/21068846/701d0548-be29-11e6-80a2-06e58a68b5a1.png)

**Comment by bbondy** [comment]
why 1.0? I'm not even sure we want to be able to do that.

**Comment by bradleyrichter** [comment]
@bbondy  If we implement this: #5889

...we can put resetting in the back-backlog. I think the requests are driven by our giant numbers that need to be simplified.
