### ISSUE TITLE
Productivity feature suggestions: Tab stacking/Page tiling

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#613]
Some more feature suggestions which in my opinion area also quite great for productivity:

Tab stacking= Move tabs into other tabs and a group is created. 
Page tiling= Combine 1-4 pages to a group and display them at once on the screen

Just take a look at old Opera/Vivaldi or Otter Browser. Would be nice to have such feature sets also in Brave - of course if they can be implemented without bigger problems :)

**Comment by bradleyrichter** [comment]
Thanks @SJ-Diamond. We will do both of these in the future. I'll try to run the UI by you when I have a proposal...

**Comment by SJ-Diamond** [comment]
Good, that are really useful productivity features worth to have :)

**Comment by alexwykoff** [comment]
Shipped tab feature

**Comment by luixxiul** [comment]
Page tiling not

**Comment by Liunkae** [comment]
I added a new issue for page tiling at #5674.

**Comment by luixxiul** [comment]
And not sure even tab stacking has been shipped

**Comment by exside** [comment]
yeah, how can we stack tabs? simply dragging/dropping a tab onto another one doesn't do anything, see vivaldi for how it should work...

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-tab-stacking/10057

Let's keep discussion there to understand what kind of features it should implement. After we have enough information to implement this feature, let's reopen this issue 😄
