### ISSUE TITLE
Add the release notes of the same version as the browser to about:brave

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6130]
**Expected behavior:**
Add the release notes of the same version as the browser to about:brave. The release notes and release date which are specified in updater.js could be reused in some way.

<img width="1284" alt="screenshot 2016-12-11 3 50 09" src="https://cloud.githubusercontent.com/assets/3362943/21075414/ff22a6d6-bf54-11e6-8103-ac13197cca8e.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch

**Comment by luixxiul** [comment]
CC @bradleyrichter for comments on design of the about page. Have you designed one already?

**Comment by bsclifton** [comment]
I like this; my ideal design (personal opinion) would be:
- Nice high-rest Brave logo next to the "About Brave" :lion: 
- Version information on top (below that)
- Release notes below that

Some of the other information I've considered showing here (maybe a collapsed area which is expandable):
- what command line params was Brave launched with?
- video card information
- other info that may be useful for troubleshooting

**Comment by bradleyrichter** [comment]
Logo would be nice...

**Comment by luixxiul** [comment]
I was trying to load https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/img/braveAbout.png in the brave.js and it seems that it does not let me use `<img src=''>`.. Is there any way instead of it?

**Comment by bsclifton** [comment]
@luixxiul because this image is inside the Brave extension itself, loading it is not straight-forward.  You'll want to look at an example on the Payments UI for how to load internal images (ex: the CoinBase logo)
