### ISSUE TITLE
Menu Bar Won't Hide After Enable Hide Menu Bar Option

### ISSUE THREAD

**Issue by zezuzaza** [brave/browser-laptop#6132]
**Did you search for similar issues before submitting this one?**
Yes. I didn't find any similar related to this issue. This is the latest issue of its kind.

**Describe the issue you encountered:**
Setting-General-Appearance Setting-Enable Hide The Menu Bar By Default
After launched the browser again, the menu bar won't hide and still appeared unless by clicking menu bar or unexpected movement (such as after do a print screen action) or any other action on the browser thus it will activate the enable hide menu bar.

**Expected behavior:**
The menu bar should hide by default/permanently when browser launched

- Platform (Win7, 8, 10? macOS? Linux distro?):
Deepin Linux 15.3 x64bit

- Brave Version:
Brave: 0.12.5
Electron: 1.4.14
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0
Update Channel: dev
This software uses libraries from the FFmpeg project under the LGPLv2.1

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:
![deepinscreenshot20161211052227](https://cloud.githubusercontent.com/assets/24498067/21076323/59f7ec7a-bf63-11e6-9132-f71fe4607486.png)

![deepinscreenshot20161211051506](https://cloud.githubusercontent.com/assets/24498067/21076325/71035b48-bf63-11e6-8b83-6a84839c338b.png)

- Any related issues:
None

**Comment by luixxiul** [comment]
The issue is tracked here: https://github.com/brave/browser-laptop/issues/5086
