### ISSUE TITLE
Offer option to automatically popup the findbar after user clicks in frame + types

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#614]
Firefox has this nice optional feature which i really miss in most alternative browsers so far:
-  If you are clicking with the mouse in the actual tab and start to type, search field is automatically opening so you can instantly start a search on the open tab.

Would be great if something like that also could be implemented in Brave.

**Comment by bbondy** [comment]
Could you explain this more? If you create a new tab we focus the URL bar.  
On Firefox if you click a tab, it doesn't focus the URL bar.

**Comment by SJ-Diamond** [comment]
I mean to start a search you need to press strg+F. Firefox/Seamonkey/Pale moon offerred that too of course.

But they also had an optional setting which provided the user to instantly start a search on a webpage with just typing any letter with the keyboard which automatically opens the search field when the user clicks inside the tab into the web content.

**Comment by alexwykoff** [comment]
Search enhancements and autocomplete shipped

**Comment by bsclifton** [comment]
@alexwykoff we don't have a feature like this (that I'm aware of). This is describing typing without the find box being open (not the URL bar) and having it find on page

**Comment by bsclifton** [comment]
I updated the title; @SJ-Diamond, if you're still a Brave user and are interested in this, maybe you can just reply back to let me know if I captured it properly :smile:

**Comment by bbondy** [comment]
I'd recommend if we do this to make find in page active when you type '/' on the page.
I'd like for other keys to be used for other functionality, like the Vi plugin on Chrome has a lot of different functionality which is great
