### ISSUE TITLE
Home/start URL is not according to my setting

### ISSUE THREAD

**Issue by gordonq** [brave/browser-laptop#6142]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by gordonq** [comment]
My Home/start URL is not my chosen one of: finance.yahoo.com
I can't change it. It is always this undesired URL that brings up a local directory:
file:///C:/Users/Gordon/AppData/Local/brave/app-0.12.14/Brave.exe

**Comment by bsclifton** [comment]
@gordonq sorry for the super late reply here

We just discovered the bug for why you saw Brave always try to open `Brave.exe` and we're working on a fix

You can track it with issue https://github.com/brave/browser-laptop/issues/6075 :smile:
