### ISSUE TITLE
Find in page doesn't work correctly after navigation if 0 results

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6147]
This works in 0.12.14
This fails in 0.13.0

Run this test:

```
npm run test -- --grep="findbar input remembered"
```

It fails for a legit reason. You can reproduce as follows manually:

Start an http server in the browser-laptop test dir
1. cd test/fixtures
2. python -m SimpleHTTPServer 9099
3. Load http://localhost:9099/find_in_page.html
4. Open find bar and type Brad
5. Load http://localhost:9099/find_in_page2.html
6. Open find bar and press enter

It doesn’t find the match

It should find the match

**Comment by Liunkae** [comment]
I think I can reproduce this issue on both 0.12.14 and master. The only change (in 0.13.0) I can think of is my PR #5786 (commit 29e7d53) that changed the findbar's `onKeyUp` to `onInput`.

**Comment by cezaraugusto** [comment]
@Liunkae your commit isn't added yet on the latest release (v0.13.0dev-Preview2). See [here](https://github.com/brave/browser-laptop/blob/v0.13.0dev-Preview2/js/components/findbar.js#L24).

**Comment by bbondy** [comment]
0.12.14 doesn't reproduce for me.
Latest 0.13.0dev is preview3 and it has this, although it's only built for macOS right now.
0.13.0 does reproduce.

**Comment by bbondy** [comment]
I confirmed it wasn't because of your change @Liunkae by the way by reverting it and testing.

**Comment by Liunkae** [comment]
Then could this be related to chromium54?

**Comment by bbondy** [comment]
Yep, 0.13.0 => C54

**Comment by bbondy** [comment]
I think I tested wrong before this seems to have always been a problem, or at least for the last couple releases.

**Comment by bbondy** [comment]
Disabling the test for now https://github.com/brave/browser-laptop/issues/5389
