### ISSUE TITLE
IPC is failing on C54 in renderer processes

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6151]
Running this in Shift+F8 console fails:
`chrome.ipcRenderer.emit('shortcut-focus'url')`

This also fails various parts of functionality but most visible through automated test failures.

**Comment by luixxiul** [comment]
Test plan:

Running this in Shift+F8 console should not fail:
chrome.ipcRenderer.emit('shortcut-focus'url')

**Comment by srirambv** [comment]
![6151](https://cloud.githubusercontent.com/assets/17010094/22150924/a61fbd06-df13-11e6-93dc-e46e21aa4755.gif)


cc: @bbondy this is on a clean install on 0.13.0 RC1

**Comment by luixxiul** [comment]
I confirmed this was fixed on RC5
