### ISSUE TITLE
Add a prefix/suffix for classes which are used for automated tests only

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6154]
**Expected behavior:**
Add a prefix/suffix for classes which are used for automated tests only, eg. `test__`. It would help to avoid unexpected regressions.

- Any related issues:

**Comment by michalbe** [comment]
I believe this isn't valid anymore according to [the style guide](https://github.com/brave/browser-laptop/blob/master/docs/style.md#testing) since at the end all the classes will be used just for this.

**Comment by luixxiul** [comment]
Exactly, thanks for pinging!

**Comment by bsclifton** [comment]
correct 😄  the replacement (for testing only) would be (per the style guide) to create a new attribute, `data-test-id`
