### ISSUE TITLE
Allow Backspace to go back (navigation) through configuration option

### ISSUE THREAD

**Issue by lewellyn** [brave/browser-laptop#6156]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**

Unlike in other more well-known browsers, backspace does not function as a shortcut to return to the previous page. This means more moving your hand back and forth between mouse and keyboard (because now you have to use a two-handed replacement), or having to keep a keyboard handy in addition to a presentation remote (many have a backspace button on them).

**Expected behavior:**

Pressing backspace, barring any reason it shouldn't be handled, returns to the previous history item.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.14

- Steps to reproduce:
    1. Navigate to a few pages in a tab, so you know you have a history buffer.
    2. Make sure no elements which may be listening to keyboard events are selected. Like a textarea, for example... Don't want to try this there.
    3. Hit your backspace key.
    4. Sigh and hit Alt-LeftArrow.

- Screenshot if needed:

None needed, but maybe I could attach a photo of my backspace key. It's backlit and sexy?

- Any related issues:

Perhaps related to #1302?

**Comment by luixxiul** [comment]
This functionality was intentionally removed. See https://github.com/brave/browser-laptop/issues/5781#issuecomment-262096122 for more details, thanks.

**Comment by bsclifton** [comment]
Per discussion here: https://github.com/brave/browser-laptop/pull/424#issuecomment-266468611

I wanted to re-open this issue with some extra acceptance criteria (and see what everyone thought)

@lewellyn would it be acceptable to you if there was a way in preferences to re-enable this functionality?  Just a simple toggle "Allow backspace to navigate back", but set to FALSE by default

**Comment by lewellyn** [comment]
While, as a rule, such configuration options don't really add to anything except user confusion, it seems that there are strong opinions on both sides.

I'm OK with the preference, and the default being False, as long as it's discoverable. I imagine that people expecting the behavior would look to see if there is a way to turn it on before giving up. Uninstalling is more work than opening up the Preferences.

Even the much-maligned "PowerPoint drones" with their fancy computer presentation remotes are used to having to turn on an option or two to make their remotes work well. (And I expect that those remotes use Backspace rather than Alt-Left due to long-forgotten browser issues, with the workaround becoming the de-facto standard.)

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/request-add-personalization-of-hotkeys/1198

**Comment by luixxiul** [comment]
Several other requests has been made on community: https://community.brave.com/search?q=backspace

**Comment by technout** [comment]
I also really like the option for backspace navigation: to be able to enable it in the preferences.

**Comment by Raindeer44** [comment]
Backspace for navigation is by far my most used keyboard shortcut and I sorely miss it when using Brave. It's the number 1 feature missing in my opinion

**Comment by matthew-p** [comment]
please enable this as a built in option, there have been hundreds of thousands of extension downloads _solely_ to enable this single shortcut, so there is clearly a substantial demand: 

https://chrome.google.com/webstore/search/backspace

**Comment by dandv** [comment]
Given the community backlash against Chrome removing this feature (see how many duplicate issues were merged into [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=608016)), I would highly suggest adding navigation with Backspace as an option.

I've never, *ever* had the problem that made the Chrome team drop Backspace (navigating back from forms) and the replacement, Alt+Left, poses problems for people with impaired dexterity.

Unfortunately I use a Logitech mouse, and [Brave's support for the mouse back button is broken](https://github.com/brave/browser-laptop/issues/5620). This seriously impairs the usability of Brave for me.

**Comment by aimerib** [comment]
Or even better, do something like Vivaldi does, and allow for certain shortcut customization. Backspace to navigate back is pretty standard for a lot of people, and I really miss the option to set specific shortcuts for specific actions (in my case I'd use M while outside a text box to navigate back, which I could only do natively in Vivaldi. For any other browser I'd need a plugin for that.)
If built-in options in settings are not an option, I'm sure the more entrepreneurial power-user would be ok with changing a setting file if that option was available.

**Comment by luixxiul** [comment]
keyboart shortcut customization tracked here https://github.com/brave/browser-laptop/issues/1374

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/please-bring-back-backspace-key-to-go-back-one-active-page/11927?u=eljuno

**Comment by kamleshrao** [comment]
As a heavy keyboard user, I also prefer to have the Keyboard Shortcuts for Back and Forward options (like all other popular browsers)

**Comment by acodexm** [comment]
+1

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/backspace-previous-page-feature/14851?u=eljuno

**Comment by mitchcurtis** [comment]
It's kinda odd that Alt+Left doesn't work when it does in Chrome. If we could specify shortcuts then this wouldn't be an issue (I personally never use Backspace to go back, because it requires you to not have focus in an input field, unlike Alt+Left).

**Comment by srirambv** [comment]
+1 from community
https://community.brave.com/t/back-arrow-often-not-available-within-tab/15264/3

**Comment by Molteriet** [comment]
I would like this feature to be added!
Alternatively, one could simply make an extension that did it like "Backspace to go Back" in chrome, which was created after Google removed the feature about a year ago:
https://chrome.google.com/webstore/detail/backspace-to-go-back/nlffgllnjjkheddehpolbanogdeaogbc

**Comment by geistc** [comment]
I would definitely like this added as well.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/unable-to-enter-fullscreen-when-playing-videos/16864?u=eljuno

>make backspace key go to the previous page it would be awesome

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/press-backspace-button-to-go-previous-page/18211?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/backspace-pdf-and-or-extensions/18960?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/why-doesnt-the-backspace-button-on-the-keyboard-take-you-back-one-page/26767?u=eljuno

**Comment by nigelcornelius** [comment]
Just chiming in with my support for this feature. Navigation can be contextual, say if filling a form then the backspace will only operate within the field. It should detect data in form fields.

**Comment by bsclifton** [comment]
I believe the long term fix for this will be installing an extension ([like this one](https://chrome.google.com/webstore/detail/backspace-to-go-back/nlffgllnjjkheddehpolbanogdeaogbc)) when [Brave Core](https://github.com/brave/brave-browser) is released.  This is expected to release in the next few months

Because we can fix the issue like that, I'm going to close this issue as `wontfix`

**Comment by gstammw** [comment]
I really second this wish.
backspace = back!
