### ISSUE TITLE
Dragging and dropping files while creating an issue opens the file in new tab

### ISSUE THREAD

**Issue by kazekagegaara** [brave/browser-laptop#616]
When I was adding images to #615 , dragging and dropping files opened them in new tabs. The files were added to the issue, but it was a bad user experience to have to deal with an unwanted new tab. This behavior doesn't happen in other browsers.

**Comment by psimyn** [comment]
I think this is a duplicate of https://github.com/brave/browser-laptop/issues/341

**Comment by kazekagegaara** [comment]
Yup. Should've checked. Closing.
Duplicate #341
