### ISSUE TITLE
Bookmarking a site removes entry from history

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6160]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Bookmarking a visited site removes it from about:history

**Expected behavior:**
Bookmark action should not remove its history entry

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version: master (0.13.0)

- Steps to reproduce:
    1. Visit a site
    2. Go to about:history and ensure site is there
    3. Bookmark
    4. Entry is removed

**Comment by bsclifton** [comment]
@cezaraugusto is the lastAccessTime timestamp updated when bookmark happens?

Important notes about siteDetail behavior can be found here: https://github.com/brave/browser-laptop/issues/5590

**Comment by bsclifton** [comment]
I also believe this is the same issue as https://github.com/brave/browser-laptop/issues/5413

**Comment by darkdh** [comment]
@cezaraugusto , it is the root cause.
Regarding our discussion, I believe `lastAccessedTime = newSiteDetail.get('lastAccessedTime') || oldSiteDetail.get('lastAccessedTime') || 0` will fix it

**Comment by cezaraugusto** [comment]
@darkdh correct, but it crashes Brave if you bookmark an about page (like about:history itself), so seems more complex than expected.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6211 which was merged into branch `0.13.1-branch`.
