### ISSUE TITLE
Support for FreeBSD

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6161]
From [support ](https://linkbubble.zendesk.com/agent/tickets/7169)
>I would like to know if it is possible to get support for FreeBSD, FreeBSD supports Linux library, it should not be that hard. I might be able to help a bit, but I will need guidance

cc: @posix4e

**Comment by posix4e** [comment]
I can help as well. What happens when you just try to run the unpacked
binary? Are we trying to design a port?

**Comment by ericbsd** [comment]
Basically when I have try to install it on FreeBSD 11.0 I have this.

`npm ERR! FreeBSD 11.0-RELEASE-p2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron-chromedriver@1.4.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.4.0 install script 'node ./download-chromedriver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/ericbsd/Downloads/browser-laptop-0.13.0dev-Preview2/npm-debug.log`

**Comment by posix4e** [comment]
Thanks for reporting in we will need to provide that.

**Comment by CliqueBait** [comment]
+1 from Community.
https://community.brave.com/t/please-support-freebsd-and-derivatives/867

**Comment by jakenheimer** [comment]
Are there any updates on this?

**Comment by posix4e** [comment]
Oh Damn honestly I forgot about it. Happy to start to work on this with someone.

**Comment by posix4e** [comment]
Started on https://github.com/posix4e/brave-freebsd-port

**Comment by kmoore134** [comment]
+1 from TrueOS community. Looking for good alternative to FF or Chromium.

**Comment by posix4e** [comment]
I have uploaded a freebsd preview package to my personal bucket (it will be done in 5 minutes or so)
http://storage.googleapis.com/posis-brave-mirror/

**Comment by kmoore134** [comment]
Very cool! Any chance you can update the port files in the other repo? I'll be happy to bring it into our ports tree and give it some test builds if so, since we'll need it compiled against FreeBSD HEAD.

**Comment by kmoore134** [comment]
BTW, I checked and your FreeBSD dist file looks like its only a Linux version packaged to use /opt? No way to compile native?

**Comment by posix4e** [comment]
@kmoore134 I think that's doable. I already started on a port

**Comment by q5sys** [comment]
any updated information on this?

**Comment by jakenheimer** [comment]
Not on my end.  Sorry.

**Comment by posix4e** [comment]
I pushed packages a while ago, based on the linux image of freebsd that works on freebsd under compat mode. Have y'all tried them?

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/821
