### ISSUE TITLE
Dashboard  is not loaded after reinstalling with npm

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6163]
**Describe the issue you encountered:**
Dashboard is not loaded after reinstalling the browser with `npm i`. Also Brave Payments cannot be enabled on about:preferences#payments.

**Expected behavior:** Both of them should work

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: master branch 6838776e860f6f1dcad4a63fad165ba545ca4e16

- Steps to reproduce:
    1. rm -rf node_modules
    1. rm -rf ~/.electron
    1. git checkout chromium54 && npm i
    2. git checkout origin/master 
    3. rm -rf node_modules
    4. rm -rf ~/.electron
    5. npm i
    6. npm run watch
    7. npm start

- Any related issues:

**Comment by luixxiul** [comment]
I'm not sure if from 1 to 4 is required to reproduce the error.

**Comment by mrose17** [comment]
@bbondy - should we move this issue from this milestone?

**Comment by bbondy** [comment]
master should really be C54.  Is this still needed after we merge that?

**Comment by mrose17** [comment]
@bbondy - the issue, i think is that C54 doesn't work with the ledger, cf., https://github.com/brave/browser-laptop/issues/6146
