### ISSUE TITLE
Keeps wanting to download brave.com

### ISSUE THREAD

**Issue by oohjhu** [brave/browser-laptop#6164]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
everytime i launch brave, it opens up the windows file manager download window and wants me to download brave.exe
**Expected behavior:**
should not open up the download dialog window
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 64-bit
- Brave Version:
Brave 0.12.14
- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Thanks for reporting. The issue has been reported and tracked here: #6075
