### ISSUE TITLE
Brave Startup

### ISSUE THREAD

**Issue by Jes4Kix** [brave/browser-laptop#6167]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:**
Upon start up the home tab displays the following in the address bar
file:///C:/Users/Keith/AppData/Local/Brave/app-0.12.14/Brave.exe
which opens a save as file folder for "Brave.exe"
**Expected behavior:**
See my Home Page displayed

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10
- Brave Version:
0.12.14
- Steps to reproduce:
    1.Close Brave
    2.click Brave desktop Icon
    3.Close Brave
    4.Repeat 
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/24534770/21122970/a9f6c39a-c0a3-11e6-9dc7-32152c0aefcc.png)

- Any related issues:

**Comment by Jes4Kix** [comment]
I looked at the toolbar Brave Icon properties/target field and found the following
C:\Users\Keith\AppData\Local\Brave\Brave.exe -process Brave.exe
The Desktop Brave Icon properties/target field has the following
C:\Users\Keith\AppData\Local\Brave\Brave.exe
Desktop Icon launches Brave as expected.
When "-process Brave.exe" is removed from the properties/target field Brave launches as expected. 
Guess the question is, How did "-process Brave.exe" get written to the icon properties/target field?

Thanks!

**Comment by Liunkae** [comment]
This is a known problem that is actively being investigated (issue #6075). Reinstalling Brave may help until the root cause is found.
