### ISSUE TITLE
Brave clicking launcher opens window and quickly crashes it.

### ISSUE THREAD

**Issue by hockey97** [brave/browser-laptop#6168]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
Brave  when using  launcher brave.exe it crashes. It opens up a white window
and then closes the window.
Have to use installer every time to open and run brave browser.
The installer .exe file needs to be launched in order to open and run the brave
browser.
**Expected behavior:**
when clicking launcher brave.exe suppose to open and run brave.

- Platform (Win7, 8, 10? macOS? Linux distro?):
windows 7 ultimate
- Brave Version:
0.12.14
- Steps to reproduce:
    1.click launcher brave.exe
    opens white window and the closes quickly.
  then click brave installer it will install brave again and open brave without any issue.
if you close this window and the try the launcher brave.exe it will crash the window again.
I must use the installer in order to open up brave and keep it running. The launcher always
opens a window and quickly crashes that window.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
This is a known problem that is actively being investigated (issue #6075). Completely uninstalling and reinstalling Brave may help until the root cause of the problem is found.
