### ISSUE TITLE
getUserMedia() allowed without a first prompt?

### ISSUE THREAD

**Issue by ibc** [brave/browser-laptop#617]
So first time I open Brave. Go to https://apprtc.appspot.com/ and press `Join` button.

The browser MUST prompt me about permission to use my webcam and mic. Then, if I accept, such a setting should be stored for the given domain.

But... Brave automatically opens the webcam and mic without asking me...

**Comment by psimyn** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/472 - awaiting electron update

**Comment by diracdeltas** [comment]
yep, update coming soon

**Comment by diracdeltas** [comment]
Fixed by 35efd0ecdcaf98deee1d29c1a319fbbfe04a0c59
