### ISSUE TITLE
Certificate error on most of the sites "This site cannot be loaded due to a certificate"

### ISSUE THREAD

**Issue by cypherkaka** [brave/browser-laptop#6170]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Getting certificate error on most of the sites like "amazon.com", "ebay" etc.
**Expected behavior:**
Website should open without https error

- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch linux
- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
@cypherkaka Please update to the latest version of Brave (0.12.14). It fixes a bug with websites that use Symantec HTTPS certificates (#6106).

**Comment by Liunkae** [comment]
I'll go ahead and close this as a duplicate #6106.
