### ISSUE TITLE
Block 3rd Party cookie doesn't allow user to login to https://www.usbank.com/

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6173]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From [Support ](https://linkbubble.zendesk.com/agent/tickets/7155)
>Allowing all cookies also allows the Login button to work.

**Expected behavior:**
Should be login to bank website 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows

- Brave Version:
>0.12.11

**Comment by luixxiul** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/1268
