### ISSUE TITLE
Merge 'reportAnIssue' and 'submitFeedback'

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6180]
https://github.com/brave/browser-laptop/pull/6080#issuecomment-266642253 Merge 'reportAnIssue' and 'submitFeedback'

- Brave Version: master branch

- Any related issues: #6179

**Comment by bkilrain** [comment]
I'm really interested in getting some more open source contributions under my belt and I'm especially interested in Brave. Would it be ok if I gave this one a shot? I've already checked out the codebase...

**Comment by bsclifton** [comment]
@bkilrain absolutely :smile: I'll assign it to myself, but please give it a shot.  Let us know if you have any questions

**Comment by bkilrain** [comment]
Ok - I just removed 'reportAnIssueMenuItem' from the codebase since it functioned exactly like 'submitFeedbackMenuItem'. I'm not sure if that was the order of the day. Also, I didn't write any tests since there aren't tests for the other menu items. If something else is needs doing, or I misinterpreted the issue comments, let me know. @bsclifton

**Comment by luixxiul** [comment]
@bkilrain please see: https://github.com/brave/browser-laptop/pull/6080#issuecomment-265650157

Also you would have to merge `reportAnIssue` and `submitFeedback` in `/app/locale.js` and `/app/extensions/brave/locales/en-US/menu.properties`.

**Comment by bkilrain** [comment]
Ahh - good catch @luixxiul... thanks.

Re: the comment you referenced - would you rather I added deep links to those menu items or is just linking to community.brave.com sufficient for submitFeedback?

**Comment by bkilrain** [comment]
@luixxiul @bsclifton just bumping this back on your radar. I know it's small potatoes but wondering if there is anything else I need to do to resolve this issue and get onto the next one. As I'm new-ish to open source contributions, any feedback would be greatly appreciated as well. 👍

**Comment by luixxiul** [comment]
Setting the milestone to 0.13.1 as it will be released after ~one month when the link to zendesk was replaced to that to the community.

**Comment by Liunkae** [comment]
There's a comment on the PR: https://github.com/brave/browser-laptop/pull/6499#discussion_r94906708

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6499 which was merged into branch `0.13.1-branch`.
