### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by jazbo1** [brave/browser-laptop#6182]
Brave is working well for me except at Amazon.com and eBay.com. Nothing happens. The screen stays blank. Nothing downloads.Running Linux Ubuntu 16.04 and Brave.

**Comment by martinheidegger** [comment]
If you toggle the developer tools: Does it show security errors in the console?

**Comment by jazbo1** [comment]
What were the two websites I was having a problem with? Don't remember.

thank you

john

**Comment by bsclifton** [comment]
@jazbo1 you were having problems with amazon.com + ebay.com

You should be able to show the dev console with F12. Let us know what you find! I know there are video card / driver issues on Linux, so if the page is purely white (but you can view source), it may be related to that known issue

**Comment by jazbo1** [comment]
its working now for some reason. did not do a thing.

thank you very much for the prompt attention to the matter. Consider the case closed.

john shea
