### ISSUE TITLE
Form auto-suggest text disappears and does not allow you to select it

### ISSUE THREAD

**Issue by anasant** [brave/browser-laptop#6185]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When starting to enter my email, auto-complete suggestion appears and immediately disappears; I am unable to select it.

In Brave: 
![form-autocomplete](https://cloud.githubusercontent.com/assets/5509977/21152163/1440fc5e-c11a-11e6-8356-66cbc06cf075.gif)

**Expected behavior:**
Auto-fill data appears and stays there for the user to mouse or keyboard-select. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS
- Brave Version:
0.12.13

- Steps to reproduce:
    1. Go to site with data you commonly enter
    2. Start typing email
    3. Try to select email from auto-fill suggestion - it will disappear before you have a chance to

**Comment by darkdh** [comment]
dup https://github.com/brave/browser-laptop/issues/5438
