### ISSUE TITLE
[Soundcloud] Images/album art get displayed in unexpected places

### ISSUE THREAD

**Issue by anasant** [brave/browser-laptop#6187]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Going to a soundcloud URL like: https://soundcloud.com/antiroyalty/eating-hooks-walls-83-the-buzz-we-disappear-antiroyalty-mini-mix and album art appears at the bottom of the page in large size. 

![extra album art](https://cloud.githubusercontent.com/assets/5509977/21153448/5fe11b94-c11f-11e6-8d28-e3e6a2eb6424.gif)

**Expected behavior:**
Page loads same as it does on Chrome (no album art in bottom left of page on Soundcloud)

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version: 0.12.13

- Steps to reproduce:
    1. Go to Soundcloud media link 
    2. Scroll down to bottom of page
    3. Album art gets rendered at the bottom left of the page

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
Did you try with shields down? It might be caused by ad block.

**Comment by anasant** [comment]
I did try with shields down. It looks like it's caused by Fingerprinting Protection. :thinking: @Liunkae

**Comment by anasant** [comment]
Update: Scripts don't load properly, can't find a width
<img width="912" alt="screen shot 2016-12-26 at 10 07 01 pm" src="https://cloud.githubusercontent.com/assets/5509977/21489400/47dea496-cbb8-11e6-9d16-410085e2375c.png">

**Comment by luixxiul** [comment]
Closing as stale and it's the bug of the script.
