### ISSUE TITLE
PDF loads in Firefox but not Brave

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6188]
https://www.dmv.ca.gov/portal/wcm/connect/78848945-2d42-4903-a38b-329805062c7e/reg156.pdf?MOD=AJPERES

**Comment by willy-b** [comment]
can confirm, I see this with both the URL and the downloaded file

**Comment by Liunkae** [comment]
Maybe related: #5688

**Comment by SilverPuppy** [comment]
Definitely seems related. Issue still present in latest build downloaded today.

**Comment by luixxiul** [comment]
several reports here: https://community.brave.com/t/cant-open-pdf-from-website/1243

**Comment by srirambv** [comment]
PDF opens on 0.17.3 
![image](https://user-images.githubusercontent.com/17010094/27821771-5f5998a6-609b-11e7-9ecd-9491ae27ba53.png)

**Comment by luixxiul** [comment]
There are two reports here: https://community.brave.com/t/cant-open-pdfs-in-the-browser/5029?u=suguru

**Comment by luixxiul** [comment]
For me the bug cannot be reproduced consistently. Some cases the pdf.js runs properly, others not and the download dialog is instead displayed. STR unknown.

**Comment by bsclifton** [comment]
verified fixed with [brave-core](https://github.com/brave/brave-browser)
