### ISSUE TITLE
Color Problem ( What can i do to make the browser color white? )

### ISSUE THREAD

**Issue by HridoyVaraby** [brave/browser-laptop#6190]
After Install The browser and open my browsers color is not white, its kind of yellow or dark. i don't like this color, because if i play any video its does't show the right or original color. i look for a option in settings to tarn back the color to white as the other browser. but i didn't find the change option. 

So What can i do to make the browser color white as like chrome or firefox? 
Need help asap.

**Comment by bsclifton** [comment]
@HridoyVaraby do you have more information? can you take a screenshot?  I'm curious which part of the browser you don't like.  The parts which are the light gray perhaps?  Let us know :smile:

**Comment by Zhelrethas** [comment]
I know what he is talking about, but to me the pages look a bit off white or a bit pink. Let me show you three websites on IE versus Brave. www.youtube.com www.wowhead.com and www.girlgeniusonline.com

![wowhead ie](https://cloud.githubusercontent.com/assets/24845892/21571115/9e3fa926-ce91-11e6-8e7a-1358768448f7.jpg)
![youtube ie](https://cloud.githubusercontent.com/assets/24845892/21571116/9e412e04-ce91-11e6-9836-ebec6c08c9de.jpg)
![girlgeniusonline ie](https://cloud.githubusercontent.com/assets/24845892/21571117/9e413480-ce91-11e6-9885-a3ba4d5f270c.jpg)
![wowhead brave](https://cloud.githubusercontent.com/assets/24845892/21571120/9e420b26-ce91-11e6-8859-0031519949fe.jpg)
![youtube brave](https://cloud.githubusercontent.com/assets/24845892/21571118/9e414ca4-ce91-11e6-993e-4e5a7afae9e5.jpg)
![girlgeniusonline brave](https://cloud.githubusercontent.com/assets/24845892/21571119/9e41a762-ce91-11e6-8827-ec4aa629537a.jpg)

The sites also look good in chrome and firefox. All pages look off in brave. The pictures are just three random examples. All video content on youtube also looks odd.

![video ie](https://cloud.githubusercontent.com/assets/24845892/21571305/960efc96-ce93-11e6-83cf-760bbb5f13bd.jpg)
![video brave](https://cloud.githubusercontent.com/assets/24845892/21571306/98ffe578-ce93-11e6-9814-436c3a3ed28b.jpg)


 Every page I look at including this one, look a bit off white and pinkish.

**Comment by HridoyVaraby** [comment]
Yes. That's the problem I am trying to solve.
Thanks ** @Zhelrethas ** for pointing out that.
This post is all about this color issue. How do we solve this?

**Comment by bsclifton** [comment]
@HridoyVaraby @Zhelrethas would you all be able to try out our latest preview build?  I'm curious if this fixes anything.  Give it a shot here:
https://github.com/brave/browser-laptop/releases/tag/v0.13.0dev-Preview9

**Comment by mpituley** [comment]
@bsclifton That build installs but the browser does not launch on Win8 64 machine. I have the same problem with the color being pinkish like what @Zhelrethas demonstrated.

**Comment by bsclifton** [comment]
@mpituley sorry for the late response-  can you confirm that it shows pink with the latest version? (0.13.5).  The link above is old; I'll make sure to put a note about that

**Comment by luixxiul** [comment]
related? https://community.brave.com/t/colors-are-different-compared-to-other-browsers/7943

**Comment by bsclifton** [comment]
@luixxiul no- doesn't seem related.  I'm going to close this issue as stale, as there is not enough information to reproduce. Please reopen if this is happening to you so that we can help troubleshoot 😄
