### ISSUE TITLE
Close Developer Tools with CTRL/CMD+W

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6191]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
From within the developer tools, [the user](https://twitter.com/Kent1_/status/808768609661124616) expects the CTRL/CMD+W combination to close the developer tools (not the browser tab). Presently, nothing happens.

**Steps to reproduce:**
1. Open the developer tools
2. Place focus on console input, press CTRL/CMD+W
3. Note that nothing happens

**Comment by Liunkae** [comment]
Duping to #45.

**Comment by grand-lotus-iroh** [comment]
+1

CTRL + W does not close Inspect Element > Developer Tools on Windows 10 Brave.
