### ISSUE TITLE
Wallet Lost

### ISSUE THREAD

**Issue by mideava** [brave/browser-laptop#6192]
After I updated brave to 0.12.14 from 0.12.10, my wallet was lost. Brave gave me a button to create a new wallet, but it didn't work (nothing happened when clicking on it). So I wiped out all configuration (the ~/.config/brave directory) and reinstalled Brave. Then, I tried to restore my wallet from the two keys I had backed up. Brave restored my wallet, but with a zero balance while it has a few dollars in it. I am using Linux Mint Sarah 64 bits.

**Comment by mideava** [comment]
After waiting for a while, my balance was restored.

**Comment by bsclifton** [comment]
@mideava thanks for the update- I'm not sure what happened, but more info is always appreciated.  Since your issue is resolved, I'll close this out... but please reply if you have more information
