### ISSUE TITLE
Vimium: Icon not displayed near address bar

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6193]
**Describe the issue you encountered:**
Upon loading the Vimium extension, there was no icon displayed near the address bar.

**Work-around:**
Adding the following (borrowed from `manifest.icon`) to the `manifest.browser_action` object resolves:
```js
"default_icon": {
  "19": "icons/icon16.png",
  "38": "icons/icon48.png"
}
```
**Brave Version: 0.12.15**

**Comment by luixxiul** [comment]
@jonathansampson do we need QA for this issue, or is this postponed until Vinium extension becomes ready?

**Comment by jonathansampson** [comment]
@luixxiul The root issue is resolved; this is good closed :)

**Comment by jonathansampson** [comment]
Reopening as `manifest.icons` is the wrong way to go about solving this problem. Seeing the comments on #7500 to better understand the correct approach.

**Comment by srirambv** [comment]
Added no-qa-requried as the extension is not available in packaged build for testing
