### ISSUE TITLE
Extension API: chrome.browserAction.setIcon w/ imageData

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6197]
**Describe the issue you encountered:**
Brave's implementation of `chrome.browserAction.setIcon` does not presently support *imageData* objects. As a result, the following (taken from the Vimium extension) fails:
```js
chrome.browserAction.setIcon({
  tabId: tabId,
  imageData: (function() {
    var enabledStateIcon;
    enabledStateIcon = !enabledState.isEnabledForUrl ? DISABLED_ICON : 0 < enabledState.passKeys.length ? PARTIAL_ICON : ENABLED_ICON;
    return iconImageData[enabledStateIcon];
})()
```

**Expected behavior:**
Brave should accept *imageData* objects as an argument to `chrome.browserAction.setIcon`.

Blocks #9531, #9654

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
cc @kevinlawler
