### ISSUE TITLE
Design "hide sites if" options on Advanced Options Dialog

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6201]
*This is a follow-up of #4681*

courtesy of @bradleyrichter 
![image](https://cloud.githubusercontent.com/assets/13509546/21076789/67364370-bee9-11e6-851b-31eb7bca86cc.png)

I'm creating like this (the select element styling is based on #6084):
<img width="737" alt="screenshot 2016-12-12 0 19 53" src="https://cloud.githubusercontent.com/assets/3362943/21081022/be45dc76-c000-11e6-9e15-418daec7e477.png">

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version: master branch

- Any related issues:

**Comment by bradleyrichter** [comment]
looks good!

**Comment by luixxiul** [comment]
Test plan: same as https://github.com/brave/browser-laptop/issues/6221#issuecomment-272913494
