### ISSUE TITLE
about:preferences links do not work when opened from about:about

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6205]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I noticed that links to pages from about:preferences do not work if about:preferences was opened from about:about

**Expected behavior:**
about:preferences page links should always work

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.15 RC3

- Steps to reproduce:
    1. Open about:about
    2. Click on about:preferences
    3. Click on about:preferences#security
    4. Click on 'Manage Autofill Data...'

- Screenshot if needed:

- Any related issues:

**Comment by darkdh** [comment]
This can also be reproduced on 0.12.14

**Comment by gyandeeps** [comment]
With some little investigation, any extension page opened directly has `sender.hostWebContents` but if you open an extension from another extension `sender.hostWebContents` is not set.

This is where the check happens https://github.com/brave/browser-laptop/blob/master/js/dispatcher/appDispatcher.js#L120

**Comment by bsclifton** [comment]
This was fixed quite a while ago 😄
