### ISSUE TITLE
Show the current Brave version on the Brave website

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6208]
**Did you search for similar issues before submitting this one?**
Yes. I have seen this suggestion several times (including https://github.com/brave/browser-laptop/issues/6199#issuecomment-266956777).

**Expected behavior:**
The current version number (e.g. 0.12.14) should be shown on the Brave website (brave.com). This would help users (especially Linux users) know if their version is current and update Brave if needed.

**Comment by luixxiul** [comment]
Let's keep the discussion on https://github.com/brave/brave-website/issues/154
