### ISSUE TITLE
Ubuntu update problem

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6209]
**Did you search for similar issues before submitting this one?**
Yes. None of the other Ubuntu installation issues seem the same.

**Describe the issue you encountered:**
From https://github.com/brave/browser-laptop/issues/6199#issuecomment-266956777:
>There seem to be some problems with the automatic update process. I'm getting:
>
>`W: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/trusty/InRelease Unable to find expected entry 'main/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)`
>
>even though I'm on amd64 architecture

**Expected behavior:**
Brave should install/update without error.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04.LTS

- Brave Version:
Updating from 0.12.6 to 0.12.14

- Steps to reproduce:
    1. Have an old version of Brave installed on Ubuntu.
    2. Follow the [Linux installation instructions](https://github.com/brave/browser-laptop/blob/0403102d51903bb71db3ad0a76c88bb769bd0684/docs/linuxInstall.md).

**Comment by posix4e** [comment]
We haven't release i386 yet

**Comment by Liunkae** [comment]
Has this been fixed with 24b58cd?

**Comment by Liunkae** [comment]
I think this was fixed with 24b58cd. Closing.
