### ISSUE TITLE
Pinning the last open tab moves the "new tab" button

### ISSUE THREAD

**Issue by NobleMule** [brave/browser-laptop#621]
When pinning the last open tab (i.e. there are no full tabs left, only pinned tabs) the "new tab" button moves from immediately after the rightmost tab to the right.

Whilst there are technically no proper tabs remaining, I personally would expect the "new tab" button to appear to the right of my last pinned tab. This might be a little difficult for users unfamiliar with the (admittedly now standard) ctrl+t shortcut.

**Comment by bbondy** [comment]
I think this is fixed in 0.7.13. Please re-open if not.

**Comment by bbondy** [comment]
(Not yet released but will be soon)
