### ISSUE TITLE
hcrunch.com

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6215]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version:

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
@bradleyrichter Could you please provide more details? 😉

**Comment by luixxiul** [comment]
hcrunch.com is no longer available.
