### ISSUE TITLE
After build-package, the .exe is not opening.

### ISSUE THREAD

**Issue by mmilkov** [brave/browser-laptop#6218]
**Did you search for similar issues before submitting this one?**
Yes.
**Describe the issue you encountered:**
I am trying to build the package with npm run build-package. The system variables are added.. The build is successful, but when I try to open Brave.exe, it's not opening. Any guesses?

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version:
0.12.15

`starting build...
Hash: 494f1d17930e4352974d37ce80ae29b17819e6cf
Version: webpack 1.14.0
Child app:
    Hash: 494f1d17930e4352974d
    Version: webpack 1.14.0
    Time: 85288ms
                                     Asset       Size  Chunks             Chunk Names
      38ad268f3a41dc9191cc26857537e4c1.svg  452 bytes          [emitted]
      cd1a406ba824513a8d92a2e1418a2977.svg  418 bytes          [emitted]
      b6fb7a0b51d3af832d445c02e46d434d.png    2.13 kB          [emitted]
      a34dd95ecb584ddb353a854a069d89a1.png    18.1 kB          [emitted]
      51a0855604244165c58b5867df7d5676.png    4.69 kB          [emitted]
      0c4a088449e73ec59b36bb111c7e03b5.png    5.91 kB          [emitted]
      1be94b6e3fe1720c770ab40ab0c71cbe.png    7.22 kB          [emitted]
      69e1af008c893d635dabe4b7feb5f366.png    2.39 kB          [emitted]
      c9f976eddcb35ae1436a21d946d734cf.svg  363 bytes          [emitted]
      f88876b2519c8cbda6ef6fa17e83eeff.svg  687 bytes          [emitted]
      bc90457507bcff2412ad0d500d7f92a9.svg  693 bytes          [emitted]
      ebeef3a3a7fe9d0160161847f16b1b74.svg  367 bytes          [emitted]
      a60b6ab6aaca89b5627cee5fb224ce64.svg  438 bytes          [emitted]
      8b116e3ce0b2711f8e2cc78c8b32a7c5.svg  485 bytes          [emitted]
      493bc2b131dc439f27e05c4d3f4e93e7.png    12.1 kB          [emitted]
      196262d2122e55e514d47f9e44b66520.svg  431 bytes          [emitted]
      392507919f6ec931361b489a56c65ce9.svg  816 bytes          [emitted]
      c11dbc2db4c1e34f10ac562b48e1d886.svg  289 bytes          [emitted]
      e008bf562e79f9e1fd5110df9d61627d.svg  355 bytes          [emitted]
      23b20b72da217563c4304c07c5206dd0.svg  213 bytes          [emitted]
      d5a535fdec793b2b9219ef7abfa185ce.svg  205 bytes          [emitted]
      5ccced21c6505bfab561c1e015e407e1.svg  239 bytes          [emitted]
      674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
      912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]
      b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
    af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
     fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
                              app.entry.js     778 kB       0  [emitted]  main
                          app.entry.js.map    4.81 MB       0  [emitted]  main
       [0] multi main 28 bytes {0} [built]
        + 371 hidden modules
Child about:
    Hash: 37ce80ae29b17819e6cf
    Version: webpack 1.14.0
    Time: 85704ms
                                     Asset       Size  Chunks             Chunk Names
      314e7529efec41c8867019815f4d8dad.svg  882 bytes          [emitted]
      8b116e3ce0b2711f8e2cc78c8b32a7c5.svg  485 bytes          [emitted]
      32866d29d966a861c76ef5405f99b1aa.svg    15.2 kB          [emitted]
      1b0aa5afd818eff2fcc8b4386a8bc38b.png    3.02 kB          [emitted]
      8d111e3d7631c0d7a2392817bb7c8a2d.png    5.82 kB          [emitted]
      493bc2b131dc439f27e05c4d3f4e93e7.png    12.1 kB          [emitted]
      3caa6d84e23f04adf06c13d4063cda48.png    2.83 kB          [emitted]
      07b39e4e3e43397dc7b17f507dea2408.png    5.69 kB          [emitted]
      41184b1f1df6562bc72590ed11bd818a.svg    10.8 kB          [emitted]
      4bb98a05900622845d2e66b433711e32.png    2.93 kB          [emitted]
      b6190b89305d7ca6eb2b6a84fb68d7bf.png     2.7 kB          [emitted]
      347db93e591f13ef8528c71cff1cb7b1.svg    1.88 kB          [emitted]
      8ffb3364f75bb98213f5621b0bd830a5.svg    1.74 kB          [emitted]
      e94b909b282a44471ff551d464400b72.svg  781 bytes          [emitted]
      2ad15189f9772058209b9036ebf8bda1.svg    1.34 kB          [emitted]
      54229496f987678b6649330bc2908ac5.svg  809 bytes          [emitted]
      84c866e5857ee46ac359ac3b321993c0.svg  816 bytes          [emitted]
      fd85070af5114d6ac462c466e78448e4.svg    3.75 kB          [emitted]
      cd1a406ba824513a8d92a2e1418a2977.svg  418 bytes          [emitted]
      6c337c63662ee0ba4e57f6f8156d69ce.svg    1.14 kB          [emitted]
      e0d5b857416a206ba4d7096e598ad6d1.svg    1.14 kB          [emitted]
      d8b8faf285739ea99b0469855a73fb45.svg    1.14 kB          [emitted]
      983d8695aa002ca6bd477e212eb0aa93.svg    1.14 kB          [emitted]
      18d6cfb60f5c639c743077ca15668140.svg  621 bytes          [emitted]
      6889cdc32d92680d153a2848128df12e.svg    1.35 kB          [emitted]
      28493c836b0860eb360a8323eb936b46.svg    3.03 kB          [emitted]
      f2a17c62192cc6db4fdab183672d43e4.svg  698 bytes          [emitted]
      3b58ba8a347511da261ce50b5e4d7a4a.svg  897 bytes          [emitted]
      4134ecd741d7d7b79fd1bb41ca3ad4d5.svg  472 bytes          [emitted]
      674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
      912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]
      b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
    af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
     fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
                       aboutPages.entry.js    2.45 MB       0  [emitted]  main
                   aboutPages.entry.js.map    2.98 MB       0  [emitted]  main
       [0] multi main 28 bytes {0} [built]
        + 614 hidden modules

    ERROR in aboutPages.entry.js from UglifyJs
    SyntaxError: Unexpected token: name (length) [./~/punycode/punycode.js:55,0]

> brave@0.12.15 checks C:\Users\user\Desktop\browserv\browser-laptop-0.12.15dev
> npm run check-security

> brave@0.12.15 check-security C:\Users\user\Desktop\browserv\browser-laptop-0.12.15dev
> nsp check

(+) No known vulnerabilities found
Packaging app for platform win32 x64 using electron v1.4.31
Wrote new app to C:\Users\user\Desktop\browserv\browser-laptop-0.12.15dev\Brave-win32-x64
        1 file(s) moved.
        1 file(s) copied.
        1 file(s) copied.
'makensis.exe' is not recognized as an internal or external command,
operable program or batch file.
done`

Thank you! :)

**Comment by bsclifton** [comment]
@mmilkov [per our README.md](https://github.com/brave/browser-laptop#user-content-windows-7810-x64) (and I just went through this recently):
> You must also have NSIS 3.0rc2 or later installed and makensis's folder must be in your PATH.

If you want to give that a shot, you're more than welcome to update our wiki :smile: 
https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide

**Comment by mmilkov** [comment]
Thank you @bsclifton
