### ISSUE TITLE
HTTPS certificates too restrictive

### ISSUE THREAD

**Issue by martinheidegger** [brave/browser-laptop#6226]
**Did you search for similar issues before submitting this one?**
Yes, didn't find a lot, maybe #6182 talks about a similar problem

**Describe the issue you encountered:**
Serveral pages - particularily related to AWS services (Cloudfront) don't show up because of security problems: I.e.

https://a0.awsstatic.com/main/css/1.0.278/style.css

shows

<img width="538" alt="screen shot 2016-12-15 at 14 28 22" src="https://cloud.githubusercontent.com/assets/914122/21212731/c217b8cc-c2d2-11e6-9bce-53e52724e334.png">

Which makes quite a few sites unusable. I found: AWS, CircleCi, Meetup.com

**Expected behavior:**

Accept those security certificates.

| Name	| Version |
|---------|--------|
| Brave	| 0.12.12 |
| Muon	| 1.4.28 |
| libchromiumcontent	| 53.0.2785.143 |
| V8	| 5.3.332.47 |
| Node.js	| 6.5.0 |
| Update Channel	| dev |
| os.platform	| darwin |
| os.release	| 16.1.0 |
| os.arch	| x64 |

**Comment by diracdeltas** [comment]
@martinheidegger this seems likely due to https://github.com/brave/browser-laptop/issues/6106. please try upgrading to 0.12.15.

**Comment by disfit** [comment]
@diracdeltas I can confirm the same behaviour on bandcamp.com, for instance:

https://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=b9ef86f0ea968695300b6a9fbad44620&id=4058988486&stream=1&ts=1483751575.0

Brave: 0.12.7
Electron: 1.4.20
libchromiumcontent: 53.0.2785.143
V8: 5.3.332.47
Node.js: 6.5.0

**Comment by darkdh** [comment]
@disfit, please upgrade to 0.12.15 which is our latest version now.
I can confirm 
https://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=b9ef86f0ea968695300b6a9fbad44620&id=4058988486&stream=1&ts=1483751575.0
and https://a0.awsstatic.com/main/css/1.0.278/style.css
can be loaded without transparency error
