### ISSUE TITLE
Right click in Developer Tools not working.

### ISSUE THREAD

**Issue by martinheidegger** [brave/browser-laptop#6227]
**Did you search for similar issues before submitting this one?**
Yes. Nothing found 

**Describe the issue you encountered:**

In the Developer Tools, Right click doesn't show context menu.

**Expected behavior:**

Show context menu like in Chrome

- Platform: macOS
- Brave Version: 12.1

- Steps to reproduce:
    1. Open Developer tools
    2. Try to click with right button

**Comment by srirambv** [comment]
Same as #3832. Closing #6227
