### ISSUE TITLE
Warn before Close feature

### ISSUE THREAD

**Issue by martinheidegger** [brave/browser-laptop#6228]
**Did you search for similar issues before submitting this one?**

Yes, didn't find something.

**Describe the issue you encountered:**

Sometimes I accidentally close a browser window. Chrome does have a fix for that by adding a 
"Warn before Quitting" menu item to the application menu.

<img width="278" alt="screen shot 2016-12-15 at 17 41 35" src="https://cloud.githubusercontent.com/assets/914122/21217103/d99fe5f8-c2ed-11e6-8ee3-8470dedcfde7.png">

<img width="285" alt="screen shot 2016-12-15 at 17 42 39" src="https://cloud.githubusercontent.com/assets/914122/21217127/f43365f2-c2ed-11e6-8a40-a3f29c483aaf.png">

It would be awesome to have something similar in Brave as well.

**Comment by srirambv** [comment]
Same as #1515. Closing #6228
