### ISSUE TITLE
Usability - accessing file menu

### ISSUE THREAD

**Issue by NobleMule** [brave/browser-laptop#623]
Again with the more novice user in mind, access to the file/edit/view/etc menu on Windows is not immediately obvious. Being able to access all of the features of these menus without having to manually expose the menu bar would be useful as there appears to be no other way to access items such as bookmarks or history.

**Comment by bradleyrichter** [comment]
@NobleMule Thanks for bringing this up. We will address this when we can remove the title bar and border on the Win version.

Please LMK if you see a good solution from the competition for this issue..

**Comment by bsclifton** [comment]
This is partially addressed on Windows, now that we have the slim titlebar in place. You still need to use the ALT key to show the menu, but unlike before, the menu is navigable by keyboard.

The keyboard shortcuts shown in the menu should be usable at any time, regardless of the menu showing or not.  I wonder what specific criteria would solve this issue?

**Comment by ralesk** [comment]
I think this is related: Unlike every other application with a menu bar, there seem to be no keyboard shortcuts for the main menu items (such as **F**ile, **E**dit, etc.) – on Windows (and on Linux) it is normal to access an item in the menu bar with <kbd>Alt</kbd> + the underlined character.  Tapping <kbd>Alt</kbd> on its own only seems to be a thing on Windows, to focus the menu bar (generally don't do it on Linux).

**Comment by bsclifton** [comment]
I think this issue should be resolved now 😄 

@ralesk the issue you're mentioning is captured here https://github.com/brave/browser-laptop/issues/2949
