### ISSUE TITLE
Autofill popup will not be dismissed

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#6233]
Version: https://github.com/brave/browser-laptop/commit/b9ec9a500c63b5475b7cefd9f5fc933835394037
https://github.com/brave/electron/commit/91d74aa4c2a35f1cb02264089218741251f457c7

STR:
1. Enter autofill data
2. Go to https://www.roboform.com/filling-test-all-fields
3. Double click the form and generate the popup
4. Press Esc/Tab won't make the popup disappear

**Comment by darkdh** [comment]
fixed by 3004961

**Comment by luixxiul** [comment]
Test plan:

Enter autofill data
Go to https://www.roboform.com/filling-test-all-fields
Double click the form and generate the popup
Press Esc/Tab should make the popup disappear
