### ISSUE TITLE
Menu will not disappear 

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#6236]
Brave Version: https://github.com/brave/browser-laptop/commit/814b46bad46365df523130600fa6665e03a3b997
Muon Version: https://github.com/brave/electron/commit/91d74aa4c2a35f1cb02264089218741251f457c7
![eqnwopsifu](https://cloud.githubusercontent.com/assets/11330831/21235809/4fa23d92-c333-11e6-9fc3-bf6ee3b77cb3.gif)

CC @bsclifton

**Comment by bsclifton** [comment]
I had this happen to me also, running locally... I was also unable to close tabs

**Comment by srirambv** [comment]
Settings page is unusable when opened from  hamburger menu
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17010094/21262123/795fcef2-c387-11e6-841e-a1dc7327cdad.gif)

**Comment by srirambv** [comment]
Even the menu bar pull down doesn't close when selected. 
![feedback](https://cloud.githubusercontent.com/assets/17010094/21262387/fcaab2a8-c388-11e6-8bbe-e4126c38152d.gif)
 

Browser becomes unusable when this is selected. Have to close and reopen to use

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test Plan:
1. Launch Brave and use the kabob / cheeseburger icon
2. Notice the context menu comes up
3. Click anywhere on the screen (outside of the context menu)
4. Notice context menu closes itself
