### ISSUE TITLE
Implement shortcut for dashboard (about:newtab)

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#6237]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

I don't see a way to get back to about:newtab without either manually entering that as the URL or opening a new tab. 

**Expected behavior:**

I like to use the site icons on about:newtab as quick launch buttons, similar to the iOS app where I just tap the address bar, the "quick launch" pins are shown, and I can tap on one to go there. 

Currently, the only way to get there without opening a new tab is to manually go to about:newtab or set that as home and go home. However, this is quite awkward, mostly because knowing that the URL is about:newtab is not easy to figure out unless you know what to look for. (Took me a bit to figure it out.)

Preferably, I would like to see one or more of these implemented:

1. Have a specific menu item/icon/shortcut similar to Home (cmd-shift-h) which goes to about:newtab.

2. Alternatively, or additionally, have the ability to set about:newtab as Home without having to know and manually type in "about:newtab". You have a dropdown for "open new tabs with...", so maybe something like that?

3. When the URL bar is focused, show a popup/dropdown thing with the icons for the sites that are shown on about:newtab, similar to how iOS does it.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version:

0.12.15

**Comment by echosa** [comment]
I tried making `about:newtab` my Home URL, but it doesn't seem to work. I end up at `about:blank` instead. Manually entering `about:newtab` into the URL bar works, though.

**Comment by maddo** [comment]
It does indeed seem that having `about:newtab` bookmarked will work if you wheel-click (create a new tab) but not if you left-click and expect it to reset the current page to the new tab page.

**Comment by bsclifton** [comment]
cc: @bradleyrichter

**Comment by bsclifton** [comment]
Similar to https://github.com/brave/browser-laptop/issues/8599
