### ISSUE TITLE
How to use Brave's version of Electron

### ISSUE THREAD

**Issue by prachi71** [brave/browser-laptop#6238]
Hi Folks

Trying to build a browser like app using electron and running into issues with how window open , file downloads are handle. So after reading through the forums, it appears that Brave has addressed these issues in its fork of Electron. Question I have is how can use this fork . Can I use the Brave exe in lieu of electron ? 

I am Windows 10 currently.

Thanks

**Comment by luixxiul** [comment]
Hi, you can find the repo here: https://github.com/brave/electron

Thanks.
