### ISSUE TITLE
Design of www.zend.com broken

### ISSUE THREAD

**Issue by waldenylson** [brave/browser-laptop#624]
Not correct render of some pages like www.zend.com

related #880

**Comment by psimyn** [comment]
looks like all their static assets (js/css/images) getting blocked. It'll work for now if you select 'Allow ads and tracking' from Menu > Bravery 

something about `https://static-zend.pantherssl.com/cmsdata/ `

**Comment by waldenylson** [comment]
Yes, it's now render correct.
Why does it happen?

**Comment by bbondy** [comment]
We probably need to tweak the adblock or tracking protection rules, we'll fix but leave this open for now. Thanks.

**Comment by luixxiul** [comment]
The page has been redesigned and can be loaded properly 😄
