### ISSUE TITLE
Very low audio output

### ISSUE THREAD

**Issue by h3xp4n** [brave/browser-laptop#6240]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
I usually watch many videos whether in youtube, netflix and even news media sites, when entering one of these sites **(UOL)** very well known in Brazil the audio output was very low and is not of the video because I tested in other browsers and it went normal .
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10 64bits
- Brave Version:
0.12.15

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/is-sound-too-small-on-streaming-sites/10229

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
