### ISSUE TITLE
"Advanced Settings from Brave Payments" not saved

### ISSUE THREAD

**Issue by mideava** [brave/browser-laptop#6241]
The "Minimum page time before logging a visit" and "Minimum visits for publisher relevancy" in "Advanced Settings from Brave Payments" are not saved when changed. I am using Linux Mint Sarah 64 bits.

**Comment by Liunkae** [comment]
@mideava Are you using the latest version of Brave (0.12.15)?

**Comment by da2x** [comment]
I’m using the latest version of Brave, and I’m having the exact same issue.

I made a quick video to demonstrate the issue: https://youtu.be/X6dMXcowi-g

**Comment by mrose17** [comment]
i can confirm that 0.12.15 has this issue on linux. with the help of @posix4e i'm going to take a look at 0.13.

**Comment by mrose17** [comment]
the issue is fixed in the 0.13.1-branch!

**Comment by bsclifton** [comment]
@mrose17 can you add test steps to verify the fix here?

Also was this fixed with https://github.com/brave/browser-laptop/pull/6706?  If so, could you add "Fixes #6241" to the original post of the PR

Thanks :smile:

**Comment by mrose17** [comment]
my PR didn't fix the issue... i suspect it had been fixed in 0.13.x for a while. i seem to recall @jkup looking into something similar in the last few weeks.

**Comment by mrose17** [comment]
in terms of testing this: @da2x was kind enough to include a link to a youtube video showing the problem. if you try to reproduce that by hand, you'll see the right thing happens...

**Comment by bsclifton** [comment]
## Test steps
- Watch the video by @da2x 
- Try to reproduce this
- The correct thing happens
