### ISSUE TITLE
Panopticlick score improvements

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6244]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
This came in from community.brave.com https://community.brave.com/t/eff-panopticlick-and-brave/157 but apparently the EFF offers a cool online tool to check your browsers privacy and despite having fingerprint detection turned on and Do Not Track we are "failing" those checks on the EFF's site.

**Expected behavior:**
We should pass all tests with DNT and Fingerprint Detection turned on.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.15

- Steps to reproduce:
    1. Open Brave
    2. Turn on Shields > Fingerprint Protection
    3. Go to Preferences > Security and turn on Do Not Track header
    4. Go to https://panopticlick.eff.org/
    5. See our score (screenshot below)

- Screenshot if needed:
<img width="1280" alt="screen shot 2016-12-15 at 8 05 58 pm" src="https://cloud.githubusercontent.com/assets/490294/21249182/eafbc2ae-c301-11e6-87c5-c5b5e493a0bd.png">

- Any related issues:

**Comment by jkup** [comment]
@diracdeltas just assigning to you because I figured you'd be the best person to help triage!

**Comment by Liunkae** [comment]
Related: #4106 and #6128

**Comment by bsclifton** [comment]
Regarding not being protected from fingerprinting, per https://github.com/brave/browser-laptop/issues/5975#issuecomment-264524964:
> everyone should have the same canvas hash
> 
> panopticlick is based on the number of users who visit EFF's site, so it's definitely skewed. if you visit the site over and over again in new incognito tabs, it no longer says you're fingerprintable.

**Comment by bsclifton** [comment]
Closing this issue as I believe it's working as intended.  @diracdeltas, please reopen if I'm wrong or if you think it's worth tracking how we could provide better results for this test
