### ISSUE TITLE
Improve Drag and Drop for Bookmarks Toolbar

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6245]
Same reason as #6242: take advantage of React-DnD for all our drag-n-drop.

Opening to keep track since it's a different functionality. 

Specific issues we need to solve:
- [ ] Indicator needed to show where item will be dropped (originally reported with https://github.com/brave/browser-laptop/issues/5958)
- [ ] Tabs should be able to be bookmarked by dragging them onto Bookmarks Toolbar (originally reported with https://github.com/brave/browser-laptop/issues/11618)

**Comment by Liunkae** [comment]
Specific issues: #5958 and #6033

**Comment by bsclifton** [comment]
Thanks for rounding up those issues, @Liunkae :smile:

**Comment by bsclifton** [comment]
Related https://github.com/brave/browser-laptop/issues/5193

**Comment by danielrob** [comment]
A request here (I couldn't find anything anywhere else) would be to be able to duplicate a bookmark when dragging with the option key.

**Comment by bsclifton** [comment]
+1 from @agilob via https://github.com/brave/browser-laptop/issues/11618

**Comment by hammok** [comment]
+1 from [community](https://community.brave.com/t/bookmarks-drag-drop/19076/4)
