### ISSUE TITLE
Improve Drag and Drop for Bookmarks Manager

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6246]
For the same reason as #6242 and #6245.

**Comment by Liunkae** [comment]
Specific issue: #5589

**Comment by bsclifton** [comment]
One of the major complaints: manually sorting the bookmarks (lack of indicator for where the dragged item is, etc)
https://github.com/brave/browser-laptop/issues/5589

**Comment by bsclifton** [comment]
When doing this issue, please consider handling https://github.com/brave/browser-laptop/issues/7640

**Comment by NumDeP** [comment]
+1 More often than none, dragging a bookmark even though the destination folder isn't highlighted, allows transfer to the folder but even more importantly, sometimes bookmarks go missing,

**Comment by hammok** [comment]
+1 from [community](https://community.brave.com/t/bookmarks-drag-drop/19076/4)
