### ISSUE TITLE
Buttons inside #navigator are not working

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6253]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Refresh/Home buttons are not working

**Expected behavior:**
Refresh/Home buttons should work

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Do a clean install of 0.13.0
    2. Open a newtab/visit a page
    3. Hover over Refresh/Home button, hoverbox is not shown, clicking on both button doesn't work

- Screenshot if needed:
![123 convert-video-online com](https://cloud.githubusercontent.com/assets/17010094/21263668/04c21024-c390-11e6-9316-af15a47118f7.gif)

- Any related issues:

   cc: @bsclifton

**Comment by luixxiul** [comment]
NoScript button is unclickable too

**Comment by luixxiul** [comment]
The buttons starts working **after** showing the menu pulldown on the menubar.

**Comment by srirambv** [comment]
It works only when the browser is in focus. If the focus is lost the buttons don't work again. Have to bring down th menu to enable them

**Comment by luixxiul** [comment]
>  If the focus is lost the buttons don't work again.

Though I'm not sure completely what you meant, the reload button works after the focus is lost and regained.

![reload](https://cloud.githubusercontent.com/assets/3362943/21267353/41a48f28-c3ed-11e6-815c-e8183ce5680a.gif)

**Comment by srirambv** [comment]
It works on that particular tab on when the menu is pulled down. If you switch to another tab the buttons become inactive. If you go back to the previous tab it still doesn't show the 
![6253](https://cloud.githubusercontent.com/assets/17010094/21269332/437bbc2e-c3aa-11e6-89fd-51304f347b0e.gif)

**Comment by bsclifton** [comment]
I confirmed this is 100% still an issue- excellent find

**Comment by luixxiul** [comment]
Reopening as I found the root cause of this: https://github.com/brave/browser-laptop/commit/19360c107c21d4693b782169ec5d583e31767261#diff-02c4b23ad267fe636760179e32fa29ceR842

I will create a PR to fix this and #6680

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6681#issue-201059012
