### ISSUE TITLE
Don't include pinned tabs on some popup windows depending on window options

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#626]
Some windows like the feedly login popup should just not show pinned tabs at all.  Would make for better perf for windows which have a short life.

**Comment by bbondy** [comment]
@bridiver can you suggest which window options we should check for here to determine if pinned tabs should show up on the window or not?

**Comment by bridiver** [comment]
rather than use window options I would leave them out of windows with disposition of 'new-popup'
