### ISSUE TITLE
Ubuntu updates not available for zesty

### ISSUE THREAD

**Issue by rohshall** [brave/browser-laptop#6260]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ubuntu updates not available for zesty

**Expected behavior:**
Ubuntu updates should be available for zesty, given that brave is a cutting-edge browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 17.04

- Brave Version:
NA

- Steps to reproduce:
    1. Follow instructions from https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
    2. "sudo apt-get update" and watch the update fail. 
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
@rohshall are you using the x64 or ia-32 distro?

**Comment by rohshall** [comment]
@alexwykoff , it is x64

**Comment by posix4e** [comment]
This is true we do not support ubuntu-17.0.4 yet

**Comment by ckorn** [comment]
So, zesty has been released. Any news on this?

**Comment by meepcode** [comment]
@ckorn I tried a few hours ago, and it still failed.

**Comment by bbondy** [comment]
This is working now, you can follow the steps here:
https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
