### ISSUE TITLE
Extension APIs: chrome.cookies.getAll

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6262]
https://developer.chrome.com/extensions/cookies#method-getAll

Blocks: #8327, #8118, #6366, #9330

**Comment by jonathansampson** [comment]
@darkdh I believe this is the last item blocking Honey from being fully supported. Do you have time in the immediate future to implement?

Spec: https://developer.chrome.com/extensions/cookies#method-getAll

**Comment by darkdh** [comment]
@jonathansampson , sorry I couldn't because I have [chromium56,](3681) 57, [view certificate](2611) and [password manager refactoring](3530) ahead of it. It would be better to find another owner.

**Comment by jonathansampson** [comment]
Blocks #8327

**Comment by jonathansampson** [comment]
Blocks #8118

**Comment by jonathansampson** [comment]
Blocks #6366

**Comment by diracdeltas** [comment]
is this fixed by the commits above?

**Comment by bsclifton** [comment]
cc: @hferreiro @kevinlawler

**Comment by kevinlawler** [comment]
It was fixed the last time I tried it (around the time of the commits)

**Comment by diracdeltas** [comment]
this appears to be fixed for me
