### ISSUE TITLE
Wallet Recovery success dialog should close parent dialog when hitting OK

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6263]
![image](https://cloud.githubusercontent.com/assets/13509546/21277219/11d2031a-c38a-11e6-8760-29589cf564d1.png)

Currently, it closes the overlay and leaves the user with ackward button choices.

![image](https://cloud.githubusercontent.com/assets/13509546/21277263/551db984-c38a-11e6-9572-60b788ac9bdf.png)

**Comment by willy-b** [comment]
Hey @bradleyrichter,  this is already implemented as part of PR #5809

**Comment by willy-b** [comment]
We could also grab just the fix for this specifically without the rest of that PR by cherry-picking commit https://github.com/brave/browser-laptop/pull/5809/commits/e01ad045f0c6074377c3cf471d1a4c2430ea3642

**Comment by bradleyrichter** [comment]
cool! I will leave that up to @bsclifton . I can wait if needed.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/5809 which was merged into branch `0.13.1-branch`.
