### ISSUE TITLE
Tab button not working for urlbar suggestion navigation

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6264]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
If you start typing in the urlbar until the suggestions pop up and then hit tab to cycle through them the tab key takes you to the actual document instead of allowing you to navigate through suggestions.

Our down arrow works for navigating but tab does not.

**Expected behavior:**

In Chrome and Firefox, hitting tab with urlbar suggestions open has the same functionality as hitting the down arrow.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.15

- Steps to reproduce:
    1. Open Brave
    2. Make sure search suggestions are turned on
    3. Start typing in the urlbar
    4. When suggestions appear, hit the tab key
    5. Notice that your focus leaves the suggestions area and moves to the document

- Screenshot if needed:

- Any related issues:
Related to #4218

**Comment by bsclifton** [comment]
Closing as fixed 😄
