### ISSUE TITLE
URL bar becomes unuseable when default zoom is set to 250% and beyond

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6266]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
URL bar becomes unuseable when default zoom is set to 250% and beyond

**Expected behavior:**
URL bar should still be usable irrespective of the default zoom level

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Disable Always show URL
    2. Set default zoom level to 250% and above
    3. URL bar becomes unusable

- Screenshot if needed:
![zoomlevel](https://cloud.githubusercontent.com/assets/17010094/21279316/8d9663ae-c3d7-11e6-8010-8e1c8d3237b3.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Default zoom level should not affect the UI.

**Comment by luixxiul** [comment]
I think the issue can be closed in favor of #6315, which was fixed with https://github.com/brave/muon/commit/5a9e43c990a50f1e456153aba87b13fd71d7a9ab and  https://github.com/brave/browser-laptop/commit/7978dffb82b7ba4400d83a036af6c8b8958b46ca
