### ISSUE TITLE
urlbarIcon size change with search engine selection 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6270]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Favicons size change with search engine selection 

**Expected behavior:**
All favicons in URL bar should be of the same size

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 (need to verify on older builds)

- Steps to reproduce:
    1. Open a new tab 
    2. Type any of the engine go key and press space
    3. See the change in icon size when the engine go key is selected and changed back by pressing backspace

- Screenshot if needed:
![favicons](https://cloud.githubusercontent.com/assets/17010094/21279987/35c66864-c3db-11e6-9426-0dfc9edd9466.gif)

- Any related issues:
cc: @bradleyrichter

**Comment by luixxiul** [comment]
I'm working on it

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6292#issue-196290230
