### ISSUE TITLE
lock icon is sticky in URL bar when it should display search icon

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6273]
![image](https://cloud.githubusercontent.com/assets/13509546/21280464/faabd542-c39a-11e6-91e5-64e89037f683.png)

**Comment by jkup** [comment]
Just a note:

To reproduce you have to go to google.com (which shows the lock) and then start typing a search (which shows the magnifying glass) but then click back to the google.com page. Now if you go to the URL it shows your search text but still shows the lock which it should not.

**Comment by bradleyrichter** [comment]
thanks! I was just having a hard time reproducing this one...

**Comment by bsclifton** [comment]
Closing as this was fixed with https://github.com/brave/browser-laptop/pull/6319

**Comment by luixxiul** [comment]
@bsclifton Thanks for the test plan! :+1:
