### ISSUE TITLE
Netflix extension is downloaded but still not being found by Brave

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6278]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While attempting to view a movie on Netflix, the Widevine component was not able to be found.

**Expected behavior:**
The component should work and users should be able to view the videos without issue.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Remove your /brave folder
    2. Install 0.13.0 preview 4
    3. Visit netflix.com and try to view a movie

- Screenshot if needed:
<img width="1073" alt="screen shot 2016-12-16 at 5 16 12 pm" src="https://cloud.githubusercontent.com/assets/1434040/21281835/8fb08d9e-c3b5-11e6-9265-63e05b4e30e7.png">

- Any related issues:

**Comment by bbondy** [comment]
Should be fixed by:
https://github.com/brave/electron/commit/5459884f1be55e4beabf62ed9a45c212da4fd6a7

**Comment by bbondy** [comment]
Test plan: See steps to reproduce in the first comment.
