### ISSUE TITLE
context menus are not auto-closing after change in focus or selection

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6279]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
With a clean install, I would attempt to use a context menu and found that they would not close until I quit.

**Expected behavior:**
The context menus should close whenever an item is selected or the user changes focus outside of the menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Remove /brave
    2. Open 0.13.0 Preview 4
    3. Create a bookmark folder in the bookmarks toolbar, try the kabob menu, import bookmarks and try the bookmarks navigator menu, any and all of these have caused the issue while testing.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I think this is duping to #6236 and was fixed with #6250.

**Comment by bsclifton** [comment]
@luixxiul that is correct :smile: this should be fixed

I fixed the bug and submitted the PR about 10 minutes after @bbondy announced the builds :stuck_out_tongue:
