### ISSUE TITLE
url bar not accessible on new tab for first launch

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6280]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
With a clean install, I tried to click on the url bar after opening Brave for the first time. I could click many times, tried to use command + l, nothing worked. Only after opening another new tab did the url bar become accessible.

**Expected behavior:**
The url bar should be available and it should be the default focus item on first launch.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Remove /brave
    2. Open 0.13.0 Preview 4
    3. Try to click on the url bar or use command + l

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/electron/commit/5b1de122c507afa00260d4582ddf044404ade466

**Comment by bbondy** [comment]
I reverted this comment, so I re-opened

**Comment by bbondy** [comment]
should be working on next preview.

**Comment by luixxiul** [comment]
Test plan:
