### ISSUE TITLE
about:newtab top site pins have the wrong z-index and are being hidden by top site icons

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6281]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When opening Brave for the first time, I attempted to pin the top sites on about:newtab. The pins were sometimes hidden due to the top sites icon size and the z-index of the pin.

**Expected behavior:**
The pin should be foremost to maintain access.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 4

- Steps to reproduce:
    1. Remove /brave
    2. Open 0.13.0 Preview 4
    3. Observe the pins on each of the top site tiles

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Note: most of the z-indexes are maintained in the variable.less
