### ISSUE TITLE
Idea - Option to start the browser without disk cache

### ISSUE THREAD

**Issue by CountLesnik** [brave/browser-laptop#629]
It would be great to have an option to have no disk cache, Chromium creates tons of cache every session, is also not good for SSD disks.

So, i would either have a way to limit disk cache in memory size or the option to switch it off completely.

**Comment by bbondy** [comment]
Possibly just a checkbox in preferences under privacy to use in memory sessions only.  This would be very easy to do.

**Comment by SJ-Diamond** [comment]
I like the idea too, please add such a checkbox if possible. Thanks!

**Comment by bbondy** [comment]
to be clear here, are you looking for in memory only for everything? Like a perma private windows and tabs? Or only relating to cache and not cookies?

**Comment by SJ-Diamond** [comment]
The topic says it more or less clear in my opinion, as the opener wrote the following:

"So, i would either have a way to limit disk cache in memory size or the option to switch it off completely."

So, they are looking forward for having an option to set how much the cache is allowed to grow or to deactivate it which also would be known as RAM cache. If i remember right, i have opened a while ago a similar request: #321

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/678
