### ISSUE TITLE
Installing on Ubuntu fails, libgnome-keyring.so.0

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6293]
**Describe the issue you encountered:**
A user's attempt to install Brave on Ubuntu failed.
> kudos for the attempt....but fail on use. Installed your deb on Ubuntu 16.10 (kde desktop/kubutnu) and got -- Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory your package claimed "all dependencies satisfied" ...nope.

**Expected behavior:**
Brave should support Ubuntu without issues.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Ubuntu 16.10

**Comment by posix4e** [comment]
apt-get install libgnome-keyring should be the work around for now

**Comment by posix4e** [comment]
@bbondy what's the best way to update the list of deps in our packages? can we just add to linuxPackaging.json

**Comment by posix4e** [comment]
This should be repared in the c54 release and future relases. @bbondy good to close?

**Comment by johnJD47** [comment]
i too have same issue in kali linux

**Comment by bsclifton** [comment]
@johnJD47 did you try the work-around of running `apt-get install libgnome-keyring` and then retrying the install? Please let us know if that works

**Comment by xotan135** [comment]
@bsclifton I dont think this will be a viable workaround for Kali as they have removed from kali-rolling and kali-dev. I have run into this issue as well when i ran across this.

[Source](https://pkg.kali.org/pkg/libgnome-keyring#)

**Comment by bsclifton** [comment]
@xotan135 we'll be switching over to [Brave Core](https://github.com/brave/brave-browser) soon, so this issue should go away. Until then, I think the best I can recommend would be to manually install `libgnome-keyring` (add repos or manually download/install the package)

**Comment by xotan135** [comment]
Thanks for the reply @bsclifton
