### ISSUE TITLE
Ublock Origin integration

### ISSUE THREAD

**Issue by z751** [brave/browser-laptop#6296]
Ublock has many extra blocking options that are not available in Brave such as extra filters for privacy. It is possible to have the ublock origin plugin integrated with Brave?

**Comment by bbondy** [comment]
We'll be improving our adblocking over time, but some of the options you want are in about:adblock.   I think for consistency with the other products and speed of the native library, we'll be sticking with our implementation of adblock so I'll close this.  But I'd encourage you to please post specific things you'd like to see that we add.

**Comment by joecairns** [comment]
Hi I appreciate the effort you're putting into the internal ad blocking, but currently it's just too leaky.  I'm getting a lot of ads falling through the blocker, notably: twitter, gmail, twitch.  This is just in my first few hours of trying Brave.

Hoping you'll reconsider uBlock Origin integration at least until the internal engine comes up to speed.

` 
Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64`
