### ISSUE TITLE
Clicking "copy to clipboard" buttons need an animation

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6297]
## Test Plan:
1. Visit  `about:brave`
2. Click `Copy to clipboard`
3. Verify `copy to clipboard` button now shows confirmation label when data is copied. 

## Original issue details

This is a follow up for https://github.com/brave/browser-laptop/issues/5790

![screen shot 2016-12-19 at 10 59 57 am](https://cloud.githubusercontent.com/assets/4733304/21323369/51285e36-c5da-11e6-86f8-656d35509840.png)

The copy to clipboard button works great; however, there are no UI behaviors reinforcing the fact that the button was clicked.  For example, we could show the word "copied" and fade it in and out.  Something to confirm to the user it was copied

For now, I believe this only exists here... but the behavior could be incorporated into our `about:styles` page (and it could be wrapped with a React component)

cc: @bradleyrichter

**Comment by bradleyrichter** [comment]
@bsclifton Is this reasonable to implement?

![image](https://cloud.githubusercontent.com/assets/13509546/21325114/80c6569e-c5d9-11e6-849d-73dbe3e92d9d.png)

The string would appear quickly and fade away.

**Comment by bsclifton** [comment]
@bradleyrichter that looks perfect :smile:
