### ISSUE TITLE
Changing window focus back and forth causes webview to lose focus

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#630]
@xjru  writes:
> [Edit] Maybe this should be a separate issue but I just realized that the page also loses focus whenever the window loses focus. So if you click somewhere on the page to give it focus you can scroll using the keyboard. But after switching to another window and back, the focus is lost and keyboard scrolling stops working.

**Comment by VirgilRoussos** [comment]
Also looses focus for keyboard input.

**Comment by bbondy** [comment]
This is working for me already, I think I fixed this before.

**Comment by luixxiul** [comment]
it's working for me too.
