### ISSUE TITLE
Pinned tab icon is not properly aligned

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6300]
Currently:

![before](https://cloud.githubusercontent.com/assets/4672033/21326727/0c4d4720-c613-11e6-9430-ec23825c8157.png)

Expected:

![after](https://cloud.githubusercontent.com/assets/4672033/21326734/11268734-c613-11e6-8f1c-baf6cd9b8dae.png)

**Comment by luixxiul** [comment]
Test plan:

Pinned tab should have the same appearance as screenshot in the 1st post
