### ISSUE TITLE
copy to clipboard with keyboard is broken in URL bar

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6302]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
can no longer use command+C to copy URL text to clipboard

**Expected behavior:**
should work like rt-click context menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS
- Brave Version:
13.0

- Steps to reproduce:
    1. select URL text
    2. hit command+C
    3. paste into other doc, tab, etc and notice that the clipboard contents were not correct

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I followed these steps but cannot reproduce, can you give more details @bradleyrichter ?

**Comment by bbondy** [comment]
Which preview do you have installed?

**Comment by bbondy** [comment]
issue is only with packaged builds and is because of electron.clipboard not being available.

**Comment by bbondy** [comment]
I have a fix, will push soon.

**Comment by luixxiul** [comment]
Test plan:

select URL text
hit command+C
paste into other doc, tab, etc and notice that the clipboard contents were correct

**Comment by bsclifton** [comment]
Added release notes exclude; this was introduced with 0.13.0
