### ISSUE TITLE
cloned tab is missing forward history

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6304]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
after navigating to a bunch of pages, i navigated back a few then cloned the tab. the new cloned tab had the back navigation history, but not forward

**Expected behavior:**
the cloned tab should have all of the history of the original tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
tested on os x

- Brave Version:
0.13.0 preview 5

- Steps to reproduce:
    1. visit 10 or so pages on a single tab
    2. click back a few times
    3. clone the tab

- Screenshot if needed:

- Any related issues:

**Comment by gyandeeps** [comment]
This works in 0.12.14.
regression: https://github.com/brave/browser-laptop/commit/b9ec9a500c63b5475b7cefd9f5fc933835394037

**Comment by bridiver** [comment]
fixed https://github.com/brave/electron/commit/8ada31bd5754569eeb037b1b8207b4cce3409dc6

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
