### ISSUE TITLE
mute tab is not working

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6305]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
when sound it playing in a tab, i tried to click on the speaker icon, nothing happened.

**Expected behavior:**
if i click on the speaker icon on the tab, it should be muted

- Platform (Win7, 8, 10? macOS? Linux distro?):
tested on os x

- Brave Version:
0.13.0 preview 5

- Steps to reproduce:
    1. open a tab which plays sound
    2. click on the speaker icon on the tab

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Fixed by:
https://github.com/brave/browser-laptop/commit/448604f08aa1f6d01708a4fd76aad1a807c6602b

**Comment by luixxiul** [comment]
Test plan: available in the 1st post
