### ISSUE TITLE
Missing l10n strings - Korean

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6308]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
In the latest build of 0.13.0, a significant number of missing translations were discovered for the Korean language.

**Expected behavior:**
Each language should be in parity for coverage. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1.  Open the preferences and select Korean.
    2. Restart the app.

- Screenshot if needed:
<img width="592" alt="screen shot 2016-12-19 at 8 14 32 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336393/b6ab6c94-c62a-11e6-8af2-06ff6cd29253.png">
<img width="857" alt="screen shot 2016-12-19 at 8 14 44 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336394/b6ab7d38-c62a-11e6-8984-b0e342195abc.png">
<img width="528" alt="screen shot 2016-12-19 at 8 14 56 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336392/b6ab63de-c62a-11e6-8840-3327548e9b3b.png">
<img width="1209" alt="screen shot 2016-12-19 at 8 15 08 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336395/b6abe3f4-c62a-11e6-88ab-280784b23d79.png">
<img width="534" alt="screen shot 2016-12-19 at 8 15 16 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336396/b6ac2c4c-c62a-11e6-983d-aa7b468cd408.png">
<img width="881" alt="screen shot 2016-12-19 at 8 15 21 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336397/b6ac3976-c62a-11e6-9e22-3b8fb907524c.png">
<img width="578" alt="screen shot 2016-12-19 at 8 15 32 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336401/b6b8e0fe-c62a-11e6-86d8-0089a9cae046.png">
<img width="513" alt="screen shot 2016-12-19 at 8 15 44 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336402/b6b90c28-c62a-11e6-87e1-2ece768f571d.png">
<img width="317" alt="screen shot 2016-12-19 at 8 24 50 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336399/b6b8936a-c62a-11e6-9be2-db781f4a6a92.png">
<img width="362" alt="screen shot 2016-12-19 at 8 25 02 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336398/b6b883e8-c62a-11e6-9b8c-70ef12cceca8.png">
<img width="364" alt="screen shot 2016-12-19 at 12 48 24 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336403/b6b9233e-c62a-11e6-9c82-bbf15c7c436e.png">
<img width="198" alt="screen shot 2016-12-19 at 12 48 32 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336400/b6b8c1dc-c62a-11e6-8570-b272816b7b8f.png">
<img width="234" alt="screen shot 2016-12-19 at 12 48 38 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336406/b6c91294-c62a-11e6-8dca-3f8b9bed7f44.png">
<img width="203" alt="screen shot 2016-12-19 at 12 48 43 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336404/b6c4a1e6-c62a-11e6-992f-e8c009dcb79c.png">
<img width="260" alt="screen shot 2016-12-19 at 12 48 50 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336405/b6c51afe-c62a-11e6-8995-48be4089aadf.png">

- Any related issues:

**Comment by alexwykoff** [comment]
Found a few more : 
<img width="869" alt="screen shot 2016-12-19 at 8 47 16 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336818/a3c9e9ea-c62d-11e6-96ed-d86a9deec49a.png">
<img width="171" alt="screen shot 2016-12-19 at 8 48 24 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336820/a8a9737c-c62d-11e6-8ae1-fbd11cdf54f8.png">
<img width="171" alt="screen shot 2016-12-19 at 8 48 24 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336824/abe3d33e-c62d-11e6-874f-8d7e7b48a669.png">
<img width="218" alt="screen shot 2016-12-19 at 8 48 36 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336826/b09503d0-c62d-11e6-878b-8a76951fe9e9.png">
<img width="389" alt="screen shot 2016-12-19 at 8 48 48 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336829/b417fa76-c62d-11e6-8506-69170bf347e8.png">
<img width="517" alt="screen shot 2016-12-19 at 8 49 06 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336837/ba84434c-c62d-11e6-944f-08c80ab6551e.png">
<img width="1403" alt="screen shot 2016-12-19 at 8 49 13 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336841/bfb13a14-c62d-11e6-9cf1-9bf6e7886f0e.png">
<img width="575" alt="screen shot 2016-12-19 at 8 49 55 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336846/c38385e8-c62d-11e6-82e1-083c12a23b54.png">
<img width="684" alt="screen shot 2016-12-19 at 8 50 02 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336849/c5d4a6a6-c62d-11e6-9d47-85bdc951f3d7.png">

**Comment by luixxiul** [comment]
I thought @bradleyrichter has asked us somewhere not to make "Brave Payments" be localizable.

Also I'm not sure how much about:styles should be localizable because the official language here is English ande development work is done in English too. I think we could disable its localization for now. I simply don't think it is worth for volunteer translatiors at Transifex taking time to localize them until this project gets more international developers.

**Comment by alexwykoff** [comment]
I would then ask that the Japanese translation be backed out.
<img width="1197" alt="screen shot 2016-12-20 at 11 58 23 am" src="https://cloud.githubusercontent.com/assets/1434040/21361904/ab72a0c8-c6ab-11e6-8167-8ef3771bf7d9.png">

**Comment by bradleyrichter** [comment]
Correct. "Brave Payments" should not be translated.

**Comment by luixxiul** [comment]
@alexwykoff I agree with you if I'm honest. I localized it, being not sure if it's worth translating `white button` into `白ボタン`  since we don't do like this way: `<button className='白ボタン'>`.

**Comment by bbondy** [comment]
We should only track issues with not marked up strings and missing localization strings should be handled in transifex. Is this needed to be left open?

**Comment by alexwykoff** [comment]
I would argue that our l10n issues need to remain open if there are no other issues to track l10n coverage for 1.0. This is easy polish which means a lot to users in each of the regions represented.

**Comment by bbondy** [comment]
Quality of localized builds is an issue but our developers cannot fix them, it's done by our localizers that have accounts on transifex and not here. No task by our developers can fix localized strings if the issue is a missing translation. It needs to be done in the people in that system, not this system.

 Transifex also has a little progress bar that tells you how much each language is translated.  We should put in another order there if we have missing strings. @aekeus should do it. 

Please do open issues if we have strings that cannot be localized by that system here, but if something can be managed there then we should jus pay to get them up to date.

**Comment by bbondy** [comment]
@aekeus sorry I didn't mean that to sound like I was saying you "should have" done it, but just that I'd like you to do it, and I talked to @alexwykoff via DM and we'll add an asana task as a reminder of that. 👍

**Comment by luixxiul** [comment]
> Please do open issues if we have strings that cannot be localized by that system

I'd like to see https://github.com/brave/browser-laptop/issues/5733 and https://github.com/brave/browser-laptop/issues/4102 fixed. If it is possible to set the URL anchor links as varibles, that would be perfect.

**Comment by aekeus** [comment]
@bbondy I will issue new translation requests to complete the languages we have identified as 100% completed for 1.0 release.
