### ISSUE TITLE
Missing l10n strings - Simplified Chinese

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6309]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing the application a number of missing strings were discovered.

**Expected behavior:**
Language coverage should have parity.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. Open preferences in 0.13.0, select Chinese.
    2. Restart the app.

- Screenshot if needed:
<img width="515" alt="screen shot 2016-12-19 at 8 18 26 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336475/655e373a-c62b-11e6-93ad-c4803ebaeecf.png">
<img width="442" alt="screen shot 2016-12-19 at 8 18 37 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336476/655e6214-c62b-11e6-9838-0b4b092ff5f5.png">
<img width="304" alt="screen shot 2016-12-19 at 8 18 43 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336477/655e6304-c62b-11e6-95c5-a05ccebe23a8.png">
<img width="312" alt="screen shot 2016-12-19 at 8 18 49 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336479/655f34e6-c62b-11e6-9ddc-80fc6d711df3.png">
<img width="323" alt="screen shot 2016-12-19 at 8 19 03 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336478/655e6a34-c62b-11e6-83b9-0b9533aeae57.png">
<img width="1184" alt="screen shot 2016-12-19 at 8 19 09 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336480/655f4922-c62b-11e6-9976-75a3dc66b82b.png">
<img width="433" alt="screen shot 2016-12-19 at 8 19 20 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336482/656beaa6-c62b-11e6-9825-3a9e5d3e00ef.png">
<img width="770" alt="screen shot 2016-12-19 at 8 19 37 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336481/656b3dc2-c62b-11e6-9126-df61a9dcc91b.png">
<img width="405" alt="screen shot 2016-12-19 at 8 19 43 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336483/656e0638-c62b-11e6-8eee-4c1cdf0d56f0.png">
<img width="395" alt="screen shot 2016-12-19 at 8 19 48 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336484/656e2a0a-c62b-11e6-8e79-e3a5f1880fae.png">
<img width="513" alt="screen shot 2016-12-19 at 8 19 55 pm" src="https://cloud.githubusercontent.com/assets/1434040/21336485/656ed518-c62b-11e6-8785-f23abd5758e3.png">

- Any related issues:

**Comment by bbondy** [comment]
It'd help to identify if these strings are not available yet for translation, or if they just haven't been translated. I'm assuming the former.
You can tell by cloning the repo and git grep "string to search" to see if it's in there.

**Comment by luixxiul** [comment]
I confirmed "5seconds" and "8views" on `Brave payments 的高級設置` were not localizable. the others are just missing localized strings.

**Comment by luixxiul** [comment]
I have noticed other strings on about:preferences#payments which could not localized here: https://github.com/brave/browser-laptop/issues/5806 fwiw

**Comment by alexwykoff** [comment]
0.13.5 rc 1 update, I will search the properties files to make sure the strings are accounted for and if not, open new tracking issues per feature:

<img width="601" alt="screen shot 2017-03-02 at 9 07 59 am" src="https://cloud.githubusercontent.com/assets/1434040/23513268/1081f0d0-ff29-11e6-985f-12b020bf4bac.png">
<img width="218" alt="screen shot 2017-03-02 at 9 06 52 am" src="https://cloud.githubusercontent.com/assets/1434040/23513273/1086ff62-ff29-11e6-8845-c80541afb0f9.png">
<img width="838" alt="screen shot 2017-03-02 at 9 06 42 am" src="https://cloud.githubusercontent.com/assets/1434040/23513270/1082adb8-ff29-11e6-88fa-56a9e2ecd6fd.png">
<img width="476" alt="screen shot 2017-03-02 at 9 06 36 am" src="https://cloud.githubusercontent.com/assets/1434040/23513272/10844d44-ff29-11e6-95c5-49ffc82a1947.png">
<img width="1178" alt="screen shot 2017-03-02 at 9 06 31 am" src="https://cloud.githubusercontent.com/assets/1434040/23513271/1082e5c6-ff29-11e6-9eba-4a78f3f1afa2.png">
<img width="1422" alt="screen shot 2017-03-02 at 9 06 01 am" src="https://cloud.githubusercontent.com/assets/1434040/23513269/10827bf4-ff29-11e6-96b4-d4053d1cbf3d.png">
<img width="1404" alt="screen shot 2017-03-02 at 9 05 53 am" src="https://cloud.githubusercontent.com/assets/1434040/23513279/109d4150-ff29-11e6-9974-cdc2b9499bf9.png">
<img width="889" alt="screen shot 2017-03-02 at 9 05 46 am" src="https://cloud.githubusercontent.com/assets/1434040/23513274/109122ee-ff29-11e6-8225-cec8a819c42a.png">
<img width="354" alt="screen shot 2017-03-02 at 9 05 39 am" src="https://cloud.githubusercontent.com/assets/1434040/23513280/10a27dfa-ff29-11e6-86b6-e4f9caf3ff37.png">
<img width="448" alt="screen shot 2017-03-02 at 9 08 13 am" src="https://cloud.githubusercontent.com/assets/1434040/23513277/10976c62-ff29-11e6-8563-3e668f6d61d5.png">
<img width="564" alt="screen shot 2017-03-02 at 9 05 26 am" src="https://cloud.githubusercontent.com/assets/1434040/23513278/10996d82-ff29-11e6-97b8-eddf1161759e.png">
<img width="459" alt="screen shot 2017-03-02 at 9 08 03 am" src="https://cloud.githubusercontent.com/assets/1434040/23513276/10974d36-ff29-11e6-963b-dffd454c9814.png">
