### ISSUE TITLE
.exe file on Windows is 0KB, breaking the shortcut created on the desktop

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6313]
**Describe the issue you encountered:**
.exe file on Windows is 0KB, breaking the shortcut created on the desktop
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21339761/f6acfc6e-c6c4-11e6-9e5c-0dd6075ba34a.png)

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.13.0 Preview5

- Steps to reproduce:
    1. Uninstall and install Brave

- Any related issues:

**Comment by luixxiul** [comment]
the installation also removed the browser from the default browser setting:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21339924/3f026728-c6c6-11e6-8aea-dc11087be5b1.png)

**Comment by bsclifton** [comment]
@luixxiul the default browser setting being lost is a known issue.  Unfortunately, it's been present for as long as I've been contributing to Brave (more info at https://github.com/brave/browser-laptop/issues/5246)

**Comment by luixxiul** [comment]
@bsclifton the thing is not "being lost", the browser is not even listed there :-o which I think a new issue.

**Comment by luixxiul** [comment]
Restarting via notification bar stopped working too.

**Comment by bsclifton** [comment]
@luixxiul yikes-

I'm curious... where do your shortcuts point to? (desktop shortcut and/or taskbar pinned shortcut)

**Comment by luixxiul** [comment]
@bsclifton I'm seeing the same thing as @srirambv does; https://github.com/brave/browser-laptop/issues/6322#issuecomment-268208176

**Comment by bsclifton** [comment]
It seems shortcut is pointing at the new Brave.exe... which is 0 bytes. Besides this breaking the app's icon, this may be causing the default app not showing Brave.

Great screencap, courtesy of @srirambv:
![shortcut](https://cloud.githubusercontent.com/assets/17010094/21346962/964e8f7a-c69e-11e6-87cf-95b0cf3a55e1.gif)

**Comment by bbondy** [comment]
This was previously triaged with release/blocking and also in 0.13.0, why was the milestone and label removed @luixxiul ? Thanks!

**Comment by luixxiul** [comment]
my bad, that's my mistake. sorry :-(

**Comment by bbondy** [comment]
np!

**Comment by bbondy** [comment]
There's a couple problems here, our fork doesn't have the stub executable which causes one problem. I'm reverting to electron-winstaller to fix that.  

But then that uncovers a bigger issue which is with us not having a squirrel aware application anymore.  This makes it so squirrel events aren't sent to our exe and also makes it so our main app executable points to braveDefaults.exe instead.  Squirrel has special handling if there are no squirrel aware applications to create a shortcut (by the same name apparently!) for each exe you have.

Bug was introduced here:
https://github.com/brave/muon/commit/14d85d9d64e8fa16066f0262957c8b75d52c0ca1#diff-e1251fb68363e10586ee5cfda3ee78baL83

Testing out a fix now.

**Comment by luixxiul** [comment]
It seems that the issue was not really solved.

On  `Appdata\Local\brave\`

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21559823/e615fb92-ce96-11e6-904d-8039d004c8a2.png)

The shortcut on Desktop links to `Appdata\Local\brave\BraveDefaults.exe`

**Comment by bbondy** [comment]
Are you sure this isn't left over from before? I'm sure it is solved for me.

**Comment by bbondy** [comment]
BraveDefaults.exe there isn't an issue btw, does it create shortcuts that are usable on your desktop?

**Comment by bbondy** [comment]
Also does it create default registry keys for default browser status on install? And on win7 prompt for UAC?  If so I don't think this file causes any harm.

**Comment by luixxiul** [comment]
Manually I deleted `AppData\local\brave` and reinstalled it as usual, with no UAC prompt (I've disabled it).

Need I uninstall from Control Panel and reinstall it?

**Comment by bbondy** [comment]
just make sure that with UAC on it will prompt for it on install on Win7, Win8 doesn't need to.  And that the desktop shortcut works. If so then this should be closed.

**Comment by luixxiul** [comment]
On Windows 10, after uninstalling, deleting the folder and reinstalling, the shortcut on Desktop is still broken.

I clicked `AppData\local\brave\Brave.exe`, `AppData\local\brave\app-0.13.0\Brave.exe` and `AppData\local\brave\app-0.13.0\BraveDefaults.exe` (which is not 0kb), but the browser did not start.

Is this a different issue maybe?

**Comment by bsclifton** [comment]
@luixxiul this may be a different issue; we have had reports of the app not working after launch

**Comment by luixxiul** [comment]
OK so closing it for now.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.

**Comment by bsclifton** [comment]
added `release-notes/exclude` since this was introduced w/ 0.13.0 (specifically, using the `muon-winstaller` over `electron-winstaller`)

**Comment by bbondy** [comment]
@luixxiul please retest with next preview, should be fixed for preview10.

**Comment by luixxiul** [comment]
I confirmed this was fixed on Preview10 :-)
