### ISSUE TITLE
default zoom level effects browser chrome UI and should not w/ C54

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6315]
**Describe the issue you encountered:**
I think this has been captured by @alexwykoff at first, though I cannot find the issue where he mentioned this.

Default zoom change on about:preferences zooms in/out the UI

**Expected behavior:**

It should not zoom in/out the UI itself

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.13.0 Preview5

- Steps to reproduce:
    1. Open about:prefrences
    2. Change the default zoom level to 95%
    3. Make sure the font-size on the menu bar changes to 95%

Be careful not to set it to 500% because it makes the UI completely unusable.

- Any related issues:

**Comment by darkdh** [comment]
This should be probably fixed by https://github.com/brave/electron/commit/473fcd6977ac82bb57297d82baeb311aacae7044

but I can't verify it with current commit due to other issues

**Comment by bbondy** [comment]
Is this windows only?

**Comment by darkdh** [comment]
Ah, sorry. It also happens on Mac.

**Comment by bbondy** [comment]
@darkdh can this be closed?

**Comment by darkdh** [comment]
Can't be closed now. I'm working on it

**Comment by bbondy** [comment]
Re-added 0.13.0 milestone, @luixxiul why was it removed?

**Comment by luixxiul** [comment]
as the assignment was removed I thought it was postponed to fix this.

**Comment by bbondy** [comment]
Fixed!

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
