### ISSUE TITLE
Clicking a link with right-alt key prompts download dialog

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6316]
**Describe the issue you encountered:**
Clicking a link with right-alt key prompts download dialog. 

I am not sure if this is intended or not.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.13.0 Preview5

- Steps to reproduce:
    1. Clicking a link, pushing the right-alt key

- Any related issues:

This is not a regression.

**Comment by bsclifton** [comment]
Closing.  This is expected behavior and also happens with Chrome and Safari
