### ISSUE TITLE
Safe Browsing on http://downloadme.org/ cannot be disabled

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6318]
**Describe the issue you encountered:**
Safe Browsing on http://downloadme.org/ cannot be disabled. the switch does not work.

**Expected behavior:**
it should be able to be disabled

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.13.0 Preview5

- Steps to reproduce:
    1. Open http://downloadme.org/
    2. Click the switch "block phishing / malware" from the top right icon

- Any related issues:

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.

**Comment by srirambv** [comment]
Test failing on clean install of 0.13.0 RC1
![6318](https://cloud.githubusercontent.com/assets/17010094/22149063/9c60a8c0-df09-11e6-8210-465ecb8e8598.gif)

cc: @bbondy

**Comment by bbondy** [comment]
Moving to 0.13.1
