### ISSUE TITLE
Flash cannot be enabled on myspace.com

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6320]
**Describe the issue you encountered:**
Flash cannot be enabled on myspace.com

**Expected behavior:**
It should be able to be enabled.

- Brave Version: 0.13.0 Preview5

- Steps to reproduce:
    1. Open myspace.com
    2. Click "website"

- Any related issues:

**Comment by luixxiul** [comment]
Flash placeholder does not appear on http://www.y8.com/games/superfighters either

**Comment by bridiver** [comment]
dup #6320
