### ISSUE TITLE
Delete button icons missing in about:autofill

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6325]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Delete button icons missing in about:autofill

**Expected behavior:**
Should show the delete button

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. Open about:autofill
    2. Enter an address/credit card details
    3. Delete button is not shown but the functionality work

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21349588/9a59ffee-c6aa-11e6-841e-08dc8400e82c.png)
![image](https://cloud.githubusercontent.com/assets/17010094/21349627/e063ba8e-c6aa-11e6-9bdf-61cb11047c77.png)

- Any related issues:

**Comment by bbondy** [comment]
It shows up for me in both development and in preview5. packaged build.
I suspect I need more exact steps to reproduce.

**Comment by srirambv** [comment]
Closing the issue as unable to reproduce the issue with another clean install.
