### ISSUE TITLE
Clicking a link in a private tab opens the page in a normal tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6327]
**Describe the issue you encountered:**
Clicking a link in a private tab opens the page in a normal tab

**Expected behavior:**
It should be opened in the private tab

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10, macOS

- Brave Version: 0.13.0 Preview5, master branch

- Steps to reproduce:
    1. Open https://google.com in a private tab and search something
    2. Click a link, pushing alt/command key

- Any related issues:

CC @bridiver for info (Was this already fixed in brave/electron?)

**Comment by bridiver** [comment]
I'm pretty sure it actually is a private tab and we just aren't displaying it as a private tab

**Comment by luixxiul** [comment]
@bridiver thanks for taking this!

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
