### ISSUE TITLE
PDF doesn't load when opened but work by clicking on the link

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6330]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
PDF doesn't load when opened but work by clicking on the link

**Expected behavior:**
PDF files should open when opened/clicking the link

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. Open any pdf link  http://www.php-factory.net/demo/news/news05/photo_news/upimg/1025956a18f66dddf4_0.pdf
    2. Shows error loading pdf
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21354687/f9b33024-c6c2-11e6-91ac-5372748c61ba.png)

  ![image](https://cloud.githubusercontent.com/assets/17010094/21354670/eceb687a-c6c2-11e6-8b65-3b817f74cbb6.png)

- Any related issues:
cc: @bridiver

**Comment by bridiver** [comment]
@jonathansampson @bbondy do you know if anything changed here? We have never supported sync storage

**Comment by bbondy** [comment]
We did recently upgrade the pdfjs extension. @diracdeltas did you happen to build it differently from the time before?  Maybe they just started using new apis?

**Comment by bbondy** [comment]
@srirambv can you confirm if this is happening with 0.12.15 as well? I think it probably is.

**Comment by bbondy** [comment]
@diracdeltas did you have a chance to look at this? I'm afraid some people on 0.12.15 are also affected

**Comment by srirambv** [comment]
@bbondy Opening the link works on 0.12.15.

**Comment by srirambv** [comment]
@bbondy Verified on 0.12.15 on both Windows 10 & Windows 7. Opening the link works

**Comment by diracdeltas** [comment]
i have a fix for this

**Comment by bbondy** [comment]
Yan fixed here:
https://github.com/diracdeltas/pdf.js/commit/3e4164fef21bc801e250634c18f0708e762664e9

I updated our extension update server here:
https://github.com/brave/vault-updater/commit/f805d47a01b7586ed050fbbd49a33bd6f9af2260

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
