### ISSUE TITLE
Geolocation not working 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6331]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Geolocation not working 

**Expected behavior:**
Should show location

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Windows 10 x64

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. Visit https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation
    2. Click on Locate me
    3. Shows error Unable to locate location

- Screenshot if needed:
![geolocation](https://cloud.githubusercontent.com/assets/17010094/21355491/1b0f97a0-c6c6-11e6-908d-cef6bf67d864.gif)

- Any related issues:
#5941  cc: @bridiver

**Comment by bridiver** [comment]
this is a windows-only build issue on ci and will be corrected in the next preview

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
