### ISSUE TITLE
Ctrl+Click  in about:about page shows errors in console

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6336]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ctrl+Click  in about:about page shows errors in console

**Expected behavior:**
Should not show the errors

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.13.0 Preview 5

- Steps to reproduce:
    1. Launch brave from command prompt
    2. Open about:about page
    3. Hold Control and click on the about pages, console shows error on each click

- Screenshot if needed:
![pasted image at 2016_12_20 11_36 am](https://cloud.githubusercontent.com/assets/17010094/21357284/870f0c78-c6cc-11e6-838c-c66eea6b853e.png)

- Any related issues:
cc: @bridiver

**Comment by bridiver** [comment]
@srirambv does the ctrl-click work and just display the error messages? If so I'm not concerned about the error messages and we can close this

**Comment by srirambv** [comment]
@bridiver it just shows the error messages. The page itself opens on Ctrl+Click. Will close the issue

**Comment by luixxiul** [comment]
I added `QA/no qa needed` based on the messages above.
