### ISSUE TITLE
Private tabs script block cannot be turned off if it is turned on in the same site's non private tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6339]
STR:
1. Go to brianbondy.com and turn on script block in a normal tab.
2. Open a private tab and go to brianbondy.com
3. Turn off shields.

Actual results:
- Scripts are still blocked

Expected results:
- Scripts should not be blocked.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
