### ISSUE TITLE
Going back/forward button on about:preferences does not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6343]
**Describe the issue you encountered:**
Going back/forward button on about:preferences does not work

**Expected behavior:**
It should work

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.13.0 Preview5

- Steps to reproduce:
    1. Open about:preferences
    2. Click "Search"
    3. Click go back button on the navbar

- Any related issues:

**Comment by bridiver** [comment]
I verified that this problem only exists in the "about" pages and is not a general problem with url fragment navigation

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.

**Comment by bsclifton** [comment]
Added `release-notes/exclude` since this was introduced in 0.13.0
