### ISSUE TITLE
0.13.0 Brave Payments / Ledger / Funds tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6345]
- Any related issues:
([#6152](https://github.com/brave/browser-laptop/issues/6152))
([#3533](https://github.com/brave/browser-laptop/issues/3533))
([#5441](https://github.com/brave/browser-laptop/issues/5441))
([#6235](https://github.com/brave/browser-laptop/issues/6235))
([#6229](https://github.com/brave/browser-laptop/issues/6229))
([#6225](https://github.com/brave/browser-laptop/issues/6225))
([#6007](https://github.com/brave/browser-laptop/issues/6007))
([#6230](https://github.com/brave/browser-laptop/issues/6230))
([#6231](https://github.com/brave/browser-laptop/issues/6231))
([#6232](https://github.com/brave/browser-laptop/issues/6232))
([#5799](https://github.com/brave/browser-laptop/issues/5799))
([#6223](https://github.com/brave/browser-laptop/issues/6223))
([#6083](https://github.com/brave/browser-laptop/issues/6083))
([#6219](https://github.com/brave/browser-laptop/issues/6219))
([#6216](https://github.com/brave/browser-laptop/issues/6216))
([#6081](https://github.com/brave/browser-laptop/issues/6081))
([#6220](https://github.com/brave/browser-laptop/issues/6220))
([#6202](https://github.com/brave/browser-laptop/issues/6202))
([#3485](https://github.com/brave/browser-laptop/issues/3485))
([#5371](https://github.com/brave/browser-laptop/issues/5371))
([#4274](https://github.com/brave/browser-laptop/issues/4274))
([#5771](https://github.com/brave/browser-laptop/issues/5771))
([#4807](https://github.com/brave/browser-laptop/issues/4807))
([#4822](https://github.com/brave/browser-laptop/issues/4822))
([#4769](https://github.com/brave/browser-laptop/issues/4769))
([#4114](https://github.com/brave/browser-laptop/issues/4114))
([#5788](https://github.com/brave/browser-laptop/issues/5788))
([#5785](https://github.com/brave/browser-laptop/issues/5785))
([#5951](https://github.com/brave/browser-laptop/issues/5951))
([#5962](https://github.com/brave/browser-laptop/issues/5962))
([#6061](https://github.com/brave/browser-laptop/issues/6061))
([#6048](https://github.com/brave/browser-laptop/issues/6048))
([#4867](https://github.com/brave/browser-laptop/issues/4867))
([#5913](https://github.com/brave/browser-laptop/issues/5913))
([#6050](https://github.com/brave/browser-laptop/issues/6050))

**Comment by luixxiul** [comment]
I removed #6081, #5771, #5951, #6048, and #5930
