### ISSUE TITLE
0.13.0 UI cleanup tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6346]
- Any related issues:
([#6300](https://github.com/brave/browser-laptop/issues/6300))
([#6183](https://github.com/brave/browser-laptop/issues/6183))
([#6257](https://github.com/brave/browser-laptop/issues/6257))
([#6281](https://github.com/brave/browser-laptop/issues/6281))
([#6285](https://github.com/brave/browser-laptop/issues/6285))
([#6137](https://github.com/brave/browser-laptop/issues/6137))
([#4786](https://github.com/brave/browser-laptop/issues/4786))
([#5594](https://github.com/brave/browser-laptop/issues/5594))
([#6222](https://github.com/brave/browser-laptop/issues/6222))
([#5638](https://github.com/brave/browser-laptop/issues/5638))
([#5978](https://github.com/brave/browser-laptop/issues/5978))
([#5624](https://github.com/brave/browser-laptop/issues/5624))
([#5772](https://github.com/brave/browser-laptop/issues/5772))
([#5665](https://github.com/brave/browser-laptop/issues/5665))
([#6082](https://github.com/brave/browser-laptop/issues/6082))
([#3648](https://github.com/brave/browser-laptop/issues/3648))
([#2075](https://github.com/brave/browser-laptop/issues/2075))
([#5455](https://github.com/brave/browser-laptop/issues/5455))
([#5776](https://github.com/brave/browser-laptop/issues/5776))
([#5774](https://github.com/brave/browser-laptop/issues/5774))
([#5682](https://github.com/brave/browser-laptop/issues/5682))
([#5764](https://github.com/brave/browser-laptop/issues/5764))
([#5953](https://github.com/brave/browser-laptop/issues/5953))
([#5894](https://github.com/brave/browser-laptop/issues/5894))
([#5632](https://github.com/brave/browser-laptop/issues/5632))
([#5936](https://github.com/brave/browser-laptop/issues/5936))
([#6233](https://github.com/brave/browser-laptop/issues/6233))
([#5928](https://github.com/brave/browser-laptop/issues/5928))
([#3207](https://github.com/brave/browser-laptop/issues/3207))
([#5701](https://github.com/brave/browser-laptop/issues/5701))
([#5664](https://github.com/brave/browser-laptop/issues/5664))
([#5744](https://github.com/brave/browser-laptop/issues/5744))
([#5765](https://github.com/brave/browser-laptop/issues/5765))
([#5860](https://github.com/brave/browser-laptop/issues/5860))
([#5925](https://github.com/brave/browser-laptop/issues/5925))
([#6221](https://github.com/brave/browser-laptop/issues/6221))
([#6252](https://github.com/brave/browser-laptop/issues/6252))
([#5760](https://github.com/brave/browser-laptop/issues/5760))
([#5801](https://github.com/brave/browser-laptop/issues/5801))
([#6036](https://github.com/brave/browser-laptop/issues/6036))
([#6012](https://github.com/brave/browser-laptop/issues/6012))
([#5192](https://github.com/brave/browser-laptop/issues/5192))
([#6004](https://github.com/brave/browser-laptop/issues/6004))
([#6003](https://github.com/brave/browser-laptop/issues/6003))
([#5759](https://github.com/brave/browser-laptop/issues/5759))
([#5796](https://github.com/brave/browser-laptop/issues/5796))

**Comment by luixxiul** [comment]
I removed #6300, #6257, #6281, #5936, #6233, #5928, #5925, #6252 and #6036

**Comment by luixxiul** [comment]
I removed #5624 as I reopened the issue.
