### ISSUE TITLE
0.13.0 new tab tracking issue 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6355]
- Any related issues:
([#6206](https://github.com/brave/browser-laptop/issues/6206))
([#5868](https://github.com/brave/browser-laptop/issues/5868))
([#5763](https://github.com/brave/browser-laptop/issues/5763))
([#5827](https://github.com/brave/browser-laptop/issues/5827))
([#5935](https://github.com/brave/browser-laptop/issues/5935))
([#6159](https://github.com/brave/browser-laptop/issues/6159))

**Comment by luixxiul** [comment]
I removed #5935 as the issue has been labelled with `release-note/excludes`
