### ISSUE TITLE
Make close buttons consistent

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6365]
Close button mouse over is different across components. 
![pasted image at 2016_12_21 02_13 pm](https://cloud.githubusercontent.com/assets/17010094/21395895/28767cd0-c796-11e6-92a6-77137a18d880.png)

cc: @bradleyrichter

**Comment by luixxiul** [comment]
`fa-times` are going to be replaced with SVG. It was replaced on the download bar and the modal dialog on about:preferences#payments already.

See: #6070 and https://github.com/brave/browser-laptop/pull/6009/files#diff-a12551e83f49ce14bb3d831f382ff9acR106

**Comment by luixxiul** [comment]
Also if general modal components are applied (as noticed #6040) the close button on bookmark edit dialogs will be consistent automaically.
