### ISSUE TITLE
Relaunch on Windows is flattening the array with args for relaunch

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6369]
Problem is here:
https://github.com/brave/browser-laptop/blob/master/app/index.js#L479

The value BEFORE the + operator:
`["--user-data-dir=brave-development","--enable-logging","--v=0","C:\\GitHub\\browser-laptop-bootstrap\\src\\browser-laptop"]`

The value AFTER the + operator (on Windows):
`"--user-data-dir=brave-development,--enable-logging,--v=0,C:\\GitHub\\browser-laptop-bootstrap\\src\\browser-laptop--relaunch"`

**Comment by luixxiul** [comment]
Do we need QA for this?

**Comment by bsclifton** [comment]
@luixxiul no QA needed for this fix; it can be included with testing for the parent issue, https://github.com/brave/browser-laptop/issues/5938
