### ISSUE TITLE
npm start does not open browser

### ISSUE THREAD

**Issue by ritesh-pandey** [brave/browser-laptop#637]
Ubuntu 14.04
`npm start` starts `electron` but with an empty window.
`electron .` works fine.

Environment 
NODE_ENV: 'development' is creating the problem. Once I stop passing that information in `./tools/start.,js`, everything works fine.

Note: Build notification shows `Brave-undefined: Build successful` on running `npm run postinstall`

**Comment by ritesh-pandey** [comment]
`js/stores/appStore.js`
Line number 223 is doing the trick.

`whitelistedUrl` is being set as `index-dev.html`

**Comment by luixxiul** [comment]
@ritesh-pandey Are you still seeing this? On my environment (Ubuntu 14) ``npm start`` with ``npm run watch`` works properly.

**Comment by ritesh-pandey** [comment]
No. Everything is working fine now. :+1:
