### ISSUE TITLE
Copy version information tooltip is incorrect/not localized

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6371]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
On about:brave, the button to copy the version information has an incorrect tooltip. The tooltip currently says "Copy password to clipboard".

**Expected behavior:**
The tooltip should say something like "Copy version information to clipboard".

- Platform (Win7, 8, 10? macOS? Linux distro?):
All (found on macOS 10.12.x)

- Brave Version (revision SHA):
Master (3c39b44)

- Steps to reproduce:
    1. Open a new Brave tab and navigate to about:brave
    2. Mouse over the copy to clipboard button.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/21402010/34107c90-c77c-11e6-9067-3c54954b2cba.png)

- Any related issues:
None

**Comment by Liunkae** [comment]
https://github.com/brave/browser-laptop/blob/d9824b34f0dc0d190dacf1faac88e133be7d056f/js/about/brave.js#L46

Also, it is not localized.

**Comment by Liunkae** [comment]
I can't get `copyToClipboard` to work. And `copyToClipboard` is listed in `app/locale.js`. Many other keys on that list do work, though. 😕 
````js
const locale = require('../l10n')
...
<span className='fa fa-clipboard' title={locale.translation('copyToClipboard')} onClick={this.onCopy} />
````

**Comment by luixxiul** [comment]
@bbondy do you think this is the same as #3946?

**Comment by bbondy** [comment]
yes I think so, I think we need to implement the l10n extensions API to get the localization here

**Comment by Liunkae** [comment]
I submitted PR #6392 for a temporary fix that changes the wording to "Copy to clipboard", until we get localization to work.

**Comment by bsclifton** [comment]
@Liunkae I put a note about how you can fix the issue here:
https://github.com/brave/browser-laptop/pull/6392/files#r93702690

You can see js/about/history.js for examples (except that one uses it's own file, versus using app.properties)

**Comment by Liunkae** [comment]
PR: #6414

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6414#issue-197425848
