### ISSUE TITLE
Make buttons alignment consistent across different modals

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6372]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Recovery wallet modal button position is wrong compared to other modals (existing in 0.12.xx builds)
Add Address/Credit card details modal, Save button is not aligned with the input fields  (existing in 0.12.xx builds) 
Create/Edit bookmark modal Done button is not aligned with the input fields & drop down list (existing in 0.12.xx builds)
Buttons on Edit bookmark modal from URL bar looks weird with right alignment 
Import browser data modal buttons are right aligned which is way off with the text
Advance settings modal buttons are on the right looks fine due to the size of modal itself (the only exception where it is fine)

**Expected behavior:**
Keep all buttons center aligned to keep it consistent across all modals

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Windows 10 x64

- Brave Version (revision SHA):
0.12.15 & 0.13.0 

- Steps to reproduce:
See below comparison between 0.12.15 and 0.13.0 

- Screenshot if needed:
0.13.0 vs 0.12.15
![image](https://cloud.githubusercontent.com/assets/17010094/21402045/ab441e52-c7ae-11e6-894a-d70b8640850e.png)
 ![image](https://cloud.githubusercontent.com/assets/17010094/21402279/b6003640-c7af-11e6-93a2-29d5a20f6366.png)

- Any related issues:
cc: @bradleyrichter

**Comment by luixxiul** [comment]
> Keep all buttons center aligned to keep it consistent across all modals

including the buttons on Add funds dialog?

**Comment by luixxiul** [comment]
in my opinion some of them can be aligned by changing width of elements or modifying the padding inside the dialog.

For example, we could remove `wideButton` class from the buttons on the Edit Bookmark dialog to make it into like this (which I prefer actually):
<img width="338" alt="screenshot 2016-12-22 12 03 14" src="https://cloud.githubusercontent.com/assets/3362943/21413973/bb4929c4-c83e-11e6-87e7-2118bde9407e.png">

wdyt @bradleyrichter ?

**Comment by bsclifton** [comment]
Removed some labels- this is more of an overall application look and feel issue (not specific to bookmarks or ledger).  It would be nice to resolve this as an example in our `about:styles` screen 

cc: @jkup @bradleyrichter

**Comment by luixxiul** [comment]
Lately most inconsistency have been fixed with #8443.  The remaining one is that on add funds modal dialog. I'm working on it, including the sync dialog on #8044
