### ISSUE TITLE
npm registry has 'brave' taken by another user, should use 'brave-browser' instead

### ISSUE THREAD

**Issue by anasant** [brave/browser-laptop#6378]
**Did you search for similar issues before submitting this one?**
Yes 

**Describe the issue you encountered:**
When running `npm start` to run the browser locally, and start fails with: `code ELIFECYCLE` error message is: 

```

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! brave@0.13.0 start: `node ./tools/start.js --user-data-dir=brave-development --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the brave@0.13.0 start script 'node ./tools/start.js --user-data-dir=brave-development --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/start.js --user-data-dir=brave-development --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/repos/browser-laptop/npm-debug.log
```
(among other issues). However, `npm bugs brave` opens: https://github.com/davidjamesstone/brave/issues
`npm owner ls brave` yields: davidjamesstone <davidjamesstone@gmail.com>

These are not Brave's pages. The npm registry for `brave` does not point to what you expect it to point to: https://registry.npmjs.org/brave

**Expected behavior:**
Running terminal command redirect's to one of Github's bugs pages like: https://github.com/brave/browser-laptop

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
Irrelevant

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by anasant** [comment]
recommended fix - change `package.json` to be: 
```
{
  "name": "brave-browser",
  "version": "0.13.0",
  "description": "Brave laptop and desktop browser",
  "main": "./app/index.js",
  "config": {
    "port": "8080"
  }, ... 
```

**Comment by anasant** [comment]
I tried to submit a fix myself but when I tried to push, I got: 
```
/browser-laptop$ git push --set-upstream origin issue-6378
ERROR: Permission to brave/browser-laptop.git denied to anasant.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Do I need any special permissions?

**Comment by willy-b** [comment]
(disclaimer: I'm not affiliated with Brave Software)

Hey @anasant, special permissions are required to push directly. but you can open a pull request from your own fork (what I do as an outside contributor).

What I do -- anyone else can supply their own instructions -- is fork the `brave/browser-laptop` repo (e.g. to `willy-b/browser-laptop`) and define another remote for my fork (I use `my-fork`). then I push my branches there and use the web interface to open PRs here from my fork.

commands in case they are useful:
- to add fork as remote: `git remote add my-fork git@github.com/<username>/browser-laptop`
- to push branch to your fork: `git push -u my-fork <branch-name>:<branch-name>`
- use web interface to open PR against Brave's master

for example, you can see one of my open PRs https://github.com/brave/browser-laptop/pull/5809 from my fork's branch to brave's master.

**Comment by anasant** [comment]
I think I got it! Thanks for the guidance @willy-b. 😄 Let me know if I'm missing something. Will cc you on the pull request.

**Comment by bbondy** [comment]
@bsclifton did you make sure this doesn't affect the installer and package names? Thanks!

**Comment by bbondy** [comment]
I think some of the installer creators might use the package name which we shouldn't change, they might need an additional param. It might be ok but just something to try.

**Comment by bsclifton** [comment]
@bbondy no, I didn't actually- my bad on that :frowning_face: 

I just reverted the commit until we can verify that / fix anything that relies on the old name

**Comment by bsclifton** [comment]
It seems we can't change it at this time; we experienced a problem on Windows building. Patch was reverted with https://github.com/brave/browser-laptop/pull/6432. Reopening issue

**Comment by diracdeltas** [comment]
We now own the Brave NPM organization, so i think we can use `@brave/brave`
