### ISSUE TITLE
new tab text string incorrect after opening prefs

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#638]
steps to reproduce:

- create a new tab (tab text string = "New Tab")
- open the future preferences (tab text string = "about:preferences")
- create a New Tab with Command+T (tab text string = "about:newtab")

![screen shot 2016-02-06 at 10 03 25 am](https://cloud.githubusercontent.com/assets/13509546/12868343/6b5ef42e-ccb9-11e5-9404-809fe29756cd.png)

**Comment by psimyn** [comment]
Seems to have been fixed by https://github.com/brave/browser-laptop/commit/1ed2e176309a9c00fc3c6ea79b89501ecd6b6fdf ?

**Comment by bbondy** [comment]
Yep this was just because we didn't have a newer electron prebuilt available before.  Closing.
If anyone gets this you can just `rm -Rf ~/.electron` and then `rm -Rf node_modules/electron-prebuilt` and then `npm install electron-prebuilt`
