### ISSUE TITLE
Setting min-width for buttons (l10n-friendly)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6384]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
From a perspective of localization the min-width of the buttons should be specified to avoid the case like this:

<img width="327" alt="screenshot 2016-12-22 13 53 02" src="https://cloud.githubusercontent.com/assets/3362943/21415522/ff959ff4-c84d-11e6-92a4-c3c07a776365.png">

**Expected behavior:**
CC @bradleyrichter for thought

- Brave Version (revision SHA): f27bb94

- Any related issues: #5705 

These are almost all of the buttons that should be considered (coutesy of @srirambv) #6372

Please exclude the buttons on the Add funds dialog.

> 0.13.0 vs 0.12.15
> ![image](https://cloud.githubusercontent.com/assets/17010094/21402045/ab441e52-c7ae-11e6-894a-d70b8640850e.png)
 ![image](https://cloud.githubusercontent.com/assets/17010094/21402279/b6003640-c7af-11e6-93a2-29d5a20f6366.png)

**Comment by bradleyrichter** [comment]
I think it is perfectly logical to set a min width for buttons.

5 characters plus padding is a good measurement:
![image](https://cloud.githubusercontent.com/assets/13509546/21416085/cb773072-c7c4-11e6-9705-5f156fefa186.png)

**Comment by luixxiul** [comment]
Test Plan:
1. Open about:autofill
2. Click "Add Address"
3. Make sure the width of the button "Cancel" and "Save" is equal
