### ISSUE TITLE
video won't play on CNN or CNBC with "replace ads" setting

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#639]
additionally, on CNN, the video player nav links are disabled but the menu does scroll.

Reloading with Bravery menu set to "allow ads and tracking" solves all issues.

![screen shot 2016-02-06 at 9 50 01 am](https://cloud.githubusercontent.com/assets/13509546/12868363/0a47b1a2-ccba-11e5-804c-ebfe84811503.png)

**Comment by bbondy** [comment]
https://github.com/bbondy/abp-filter-parser-cpp/commit/7b95b2f309b1107534b32bdf2baec305c87e4580
Fixed in abp-filter-parser-cpp@1.1.7
@SergeyZhukovsky @garvankeeley please update.
