### ISSUE TITLE
Title content is not aligned with Time and Domain text in about:history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6391]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Title content is not aligned with Time and Domain text in about:history

**Expected behavior:**
Text should be aligned 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.13.0 Preview 5

- Steps to reproduce:
    1. Visit any site to add an entry in about:history
    2. Title text is not aligned with time and domain
    3. Mouse over the entry becomes evident of misalignment

- Screenshot if needed:
0.13.0 vs 0.12.5
![image](https://cloud.githubusercontent.com/assets/17010094/21434779/2771d7de-c86e-11e6-98cb-138f6f2c6c4e.png)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
I believe this is a problem with the localization. This should go away when https://github.com/brave/browser-laptop/issues/5879 is fixed (HEAD on master with the macOS fix works as expected).  I'm going to close this as a dupe... but please re-open if it still occurs after https://github.com/brave/browser-laptop/issues/5879 is fixed
