### ISSUE TITLE
Problem with background-image in the "a" tag

### ISSUE THREAD

**Issue by pmkary** [brave/browser-laptop#6395]
## basic info
**Did you search for similar issues before submitting this one?** yop

- Platform (Win7, 8, 10? macOS? Linux distro?): Sierra (latest)

- Brave Version (revision SHA): 
<img width="433" alt="screen shot 2016-12-23 at 12 42 48 am" src="https://cloud.githubusercontent.com/assets/2157285/21440553/c724f11e-c8a8-11e6-8c83-222b5b88b607.png">

## Main Issue
In my website I use a background image to make the effect of underlines of the `a` tag. And somehow the new brave version doesn't show it:

<img width="1280" alt="screen shot 2016-12-23 at 12 39 43 am" src="https://cloud.githubusercontent.com/assets/2157285/21440631/2582e5ae-c8a9-11e6-8250-3c78af5d3f92.png">

To reproduce it you may take a look at [this](http://kary.us/2016/11/17/story-of-autocomplete/) link in brave and compare it to how it renders in other browsers.

**Comment by srirambv** [comment]
I can see the yellow highlight on the `<a>` tag on 0.12.15 (Win 10 x64)
![image](https://cloud.githubusercontent.com/assets/17010094/21453253/411b5ed4-c905-11e6-92af-b0e7c5bc36b0.png)

**Comment by pmkary** [comment]
@srirambv no not on hover. It must be like this when not hovered:

<img width="379" alt="screen shot 2016-12-23 at 3 56 25 pm" src="https://cloud.githubusercontent.com/assets/2157285/21453830/73d4a8d0-c928-11e6-9a0e-66b78ca49b98.png">

And the hover must be like this:

<img width="374" alt="screen shot 2016-12-23 at 3 56 37 pm" src="https://cloud.githubusercontent.com/assets/2157285/21453834/7ddbb77e-c928-11e6-9fec-54ba89e7b1c8.png">

Which is fine on my brave too. But when not hovered has problems.

**Comment by pmkary** [comment]
Turned out that this problem is shared within Electron apps as well as Opera and Vivaldi browsers (that are chromium forks) so the root must be the Chromium project itself. I have open an issue there:

[CSS backgrounds are sometimes not being rendered in chromium forks.](https://bugs.chromium.org/p/chromium/issues/detail?id=682186)

And believe that this issue is no longer within the Braver browser so I'm closing it.

**Comment by bsclifton** [comment]
@pmkary awesome, thanks for the update! :smile: (and apologies that we weren't able to help)

**Comment by luixxiul** [comment]
@pmkary so do you think #512 is also a shared issue?

**Comment by pmkary** [comment]
@bsclifton You're very welcome. Thanks a lot for taking care of other issues I opened up 👍

**Comment by pmkary** [comment]
@luixxiul I think not because I haven't seen that in Opera or Electron apps.
