### ISSUE TITLE
Regression : Pocket is not saving sites from extension badge or context menu

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6396]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing with c74ec44, muon 2.05, it was noticed that the sites would not save to Pocket using either the extension badge on the url bar or the context menu.

**Expected behavior:**
Both methods should work for saving a site to Pocket

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.0 c74ec44
- Steps to reproduce:
    1. Open a clean instance of Brave (move youre /brave folder)
    2. Enable Pocket and log in
    3. Attempt to save a site

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Reproduced on macOS w/ latest browser-laptop-bootstrap / browser-laptop

**Comment by bsclifton** [comment]
Still a problem; here's the line of code getting executed (which throws an error)
https://github.com/brave/muon/blob/master/atom/browser/extensions/atom_extension_host_delegate.cc#L60

**Comment by bsclifton** [comment]
@bridiver is looking into it; this code should never be getting called

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
