### ISSUE TITLE
Labels fail to load on whiteops.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6397]
**Describe the issue you encountered:**
Some labels on http://www.whiteops.com/products fail to load/appear

**Expected behavior:**
Crucial labels and text should be visible

**Brave Version (revision SHA):** 0.12.15

**Screenshot if needed:**
![image](https://cloud.githubusercontent.com/assets/815158/21443902/41a437aa-c86e-11e6-8e8e-e9b438a59ff3.png)

**Comment by jonathansampson** [comment]
The labels are present, but `display: none`:

```js
$('a[href="#demoModal"]').hide();

MktoForms2.whenReady(function(){
    $('a[href="#demoModal"]').show();
    …
```

The above is the _root_ of the issue. Links are hidden, and intended to be made visible again once `MktoForms2.whenReady` is fired. However, the file containing `MktoForms2` is blocked by Brave on account on it being hosted on a third-party domain (https://app-ab17.marketo.com/js/forms2/js/forms2.min.js).

**Comment by luixxiul** [comment]
I'm closing the issue as the page is 404.
