### ISSUE TITLE
Brave Password manager prompting for keychain access 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6398]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I tested the Brave Password Manager and it prompted for keychain access which it did not do in the past.

**Expected behavior:**
If the system is supposed to do this now, it should be documented. If it is not supposed to do this, we should get rid of it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.0 93b7c31
- Steps to reproduce:
    1. Open a clean instance of Brave (move /brave)
    2. Visit a site (I used https://trac.torproject.org/projects/tor) and attempt to log in.

- Screenshot if needed:
<img width="447" alt="screen shot 2016-12-22 at 5 42 41 pm" src="https://cloud.githubusercontent.com/assets/1434040/21444080/9bc64f92-c86f-11e6-8a74-d53e284d817b.png">

- Any related issues:

**Comment by bsclifton** [comment]
This is by design; it does it the first time you save a password on macOS.  We use the `keytar` package to store a password for OUR password file.

More info, including why we haven't done a full "passwords in keychain" implementation here:
https://github.com/brave/browser-laptop/issues/3226

cc: @diracdeltas

**Comment by alexwykoff** [comment]
Thanks for the info!  With regard to the authenticity message, will that go away with signed builds?

**Comment by bbondy** [comment]
yep I think it should be ok, but please re-open if you see something on preview6.

**Comment by luixxiul** [comment]
I added `QA/no qa needed` based on the conversation above.
