### ISSUE TITLE
remove wideButton class from the buttons on the Edit Bookmark dialog 

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6400]
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/6372#issuecomment-268707188
> For example, we could remove `wideButton` class from the buttons on the Edit Bookmark dialog to make it into like this (which I prefer actually):
> <img width="338" alt="screenshot 2016-12-22 12 03 14" src="https://cloud.githubusercontent.com/assets/3362943/21413973/bb4929c4-c83e-11e6-87e7-2118bde9407e.png">

**Expected behavior:**

- Brave Version (revision SHA): 93b7c31

- Any related issues:

**Comment by luixxiul** [comment]
This is a regression I introduced: https://github.com/brave/browser-laptop/commit/1df8dc376ba08602a4394796fb91754321dca1ae of #6000

wideButton is no longer necessary as the min-width of the button was set with #6387

**Comment by bbondy** [comment]
I don't think this needs to be tracked in 0.13.0 but please let me know why if so.

**Comment by luixxiul** [comment]
Fixed with #8443 (#8136)
