### ISSUE TITLE
transparent background select elements

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6401]
**Describe the issue you encountered:**

<img width="192" alt="screenshot 2016-12-23 14 36 48" src="https://cloud.githubusercontent.com/assets/3362943/21447771/540835ea-c91d-11e6-8332-b4a937f32b0b.png">

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 93b7c31

- Any related issues:

**Comment by jonathansampson** [comment]
@luixxiul Sorry, what is the bug here?

**Comment by luixxiul** [comment]
On Windows

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21469168/399f8ec4-ca80-11e6-9c3d-6a8aadaef7c1.png)

The background of the field is white. On macOS too.

**Comment by luixxiul** [comment]
I have fixed it with `commonFormDropdown`. Closing.
