### ISSUE TITLE
Selecting a link

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#6402]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When you select a link that is not linked (displayed as plain text), context menu will not show link related options.

**Expected behavior:**
Context menu shows link related options.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.12.15

- Steps to reproduce:
    1. Go to [this site](https://plnkr.co/edit/MiTAfc2blidYcFPpTkDN?p=preview)
    2. Select link `http://www.google.com`
    3. Right click with a mouse on it

**Comment by bsclifton** [comment]
Issue resolved with https://github.com/brave/browser-laptop/pull/6403; closing :smile:
