### ISSUE TITLE
Regression: about:brave doesn't show details

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6406]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
about:brave doesn't show details

**Expected behavior:**
Should show the release details

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Master

- Steps to reproduce:
    1. Remove existing Brave and deleting existing brave-development folder from `%appdata%` 
    2. Build from master
    3. Open about:brave, no details shown

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21453797/c821fa64-c90a-11e6-8a41-ecb94c38c270.png)

- Any related issues:
#5633

**Comment by bsclifton** [comment]
probably a failure in reading the new commit field

**Comment by luixxiul** [comment]
Test Plan:
1. Remove existing Brave and deleting existing brave-development folder from %appdata%
2. Build from master
3. Open about:brave, verify info is shown; rev may or may not be blank

**Comment by bsclifton** [comment]
Added release notes exclude because this was introduced with 0.13.0. Specifically, the check which reads the last known SHA was failing (which was added with https://github.com/brave/browser-laptop/commit/d9824b34f0dc0d190dacf1faac88e133be7d056f)
