### ISSUE TITLE
Automated test failures

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6408]
- [ ] Bravery Panel Stats detects blocked elements in iframe in private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getText(".braveryStat.adsBlockedStat") - braveryPanelTest.js:366:23

- [ ] Bravery Panel Stats detects blocked elements in iframe:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getText(".braveryStat.adsBlockedStat") - braveryPanelTest.js:393:23

- [x]  frame tests view source open from pinned tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:193:32

- [ ]  navigationBar tests navigation document.write spoofing updates the location in the navbar to blank:
     Error: Promise was rejected with the following reason: timeout

- [ ]  navigationBar tests change tabs "after all" hook:
     RuntimeError: unknown error: window[requireName] is not a function
      at url() - getUrl.js:29:28
      at execute(<Function>, "app", "quit", , "devTools") - api.js:265:21

- [x]  pinnedTabs Pins an existing frame creates when signaled:
     Error: element (.tab.isPinned[data-frame-key="2"]) still not existing after 5000ms

- [x]  pinnedTabs Pins an existing frame unpins and creates a non-pinned tab:
     WaitUntilTimeoutError: element (.tab:not(.isPinned)[data-frame-key="2"]) still not existing after 5000ms
      at isExisting(".tab:not(.isPinned)[data-frame-key="2"]") - waitForExist.js:37:22

- [x]  pinnedTabs Closing pinned tabs close attempt retains pinned tab and selects next active frame:
     WaitUntilTimeoutError: element (.tab.active[data-frame-key="3"]) still not existing after 5000ms
      at isExisting(".tab.active[data-frame-key="3"]") - waitForExist.js:37:22

- [x] tab tests webview background-tab events "before all" hook: _callee26:
     RuntimeError: unknown error: process.atomBinding is not a function
      at execute(<Function>, 1, "new-window", [object Object], "new-window", "http://localhost:56604/page1.html", "some-frame", "background-tab") - brave.js:537:14

- [x] tab tests webview foreground-tab events "before all" hook: _callee28:
     RuntimeError: unknown error: process.atomBinding is not a function
      at execute(<Function>, 1, "new-window", [object Object], "new-window", "http://localhost:21528/page1.html", "some-frame", "foreground-tab") - brave.js:537:14

- [x] urlBarSuggestions selection is not reset:
     Error: Promise was rejected with the following reason: timeout

- [x]  application window click link with target opens in a new tab:
     Error: Promise was rejected with the following reason: timeout

- [ ] INTERMITTENT notificationBar "before each" hook: _callee2 for "can accept permission request persistently":
     Error: element (.notificationItem) still existing after 5000ms

- [ ] with NEWTAB_MODE === NEW_TAB_PAGE
```
    1) about:newtab tests with NEWTAB_MODE === NEW_TAB_PAGE with the top sites tile area doesn't show about pages on topSites grid:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
  2) about:newtab tests with NEWTAB_MODE === NEW_TAB_PAGE with the top sites tile area "after each" hook for "doesn't show about pages on topSites grid":
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
```
- [ ] application window open and close window
```
 3) application window open and close windows with scripts can close the child window:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
  4) application window open and close windows with scripts "after all" hook:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by luixxiul** [comment]
To track other automated test failures I opened #6603, #6604, #6606, #6607, #6608, and #6609.
