### ISSUE TITLE
Do not track only works after browser restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6409]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
0.13.0 build doesn't show a requires restart message for Do not track. Without browser restart Do not track is not set to 1

**Expected behavior:**
Do not track switch should contain requires restart message

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.13.0 Preview 5

- Steps to reproduce:
    1. Disable Do not track in preferences
    2. Visit any site, open dev tools, switch to network, select the website name and click on header
    3. Under request header there is not `DNT:1` shown
    4. Enable Do not track switch
    5. Without restarting the browser, refresh the page visited in step 2, still there is no `DNT:1` under request header
    6. Restart the browser
    7. Refresh the site page visited in step 2
    8. Now `DNT:1` is shown under request headers in dev tools

- Screenshot if needed:
Screen recording: http://sendvid.com/zl5ypu9o

- Any related issues:
cc: @bbondy @diracdeltas

**Comment by diracdeltas** [comment]
not sure why the restart message was taken out; it was always needed for DNT. should be a quick fix though

**Comment by luixxiul** [comment]
Test Plan:
1. go to prefs, turn on do not track
2. restart
3. verify that requests have the DNT header

**Comment by luixxiul** [comment]
Excluded from the release notes as the error cannot be reproduced on 0.12.15
