### ISSUE TITLE
opening a link in a new tab creates the new tab at the most left

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6411]
**Describe the issue you encountered:**
opening a link in a new tab creates the new tab at the most left, not next to the tab

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): f04777e

- Steps to reproduce:
    1. Open any link by clicking it pushing the command key

- Any related issues:

**Comment by bbondy** [comment]
This is only a problem if you're using Electron 2.0.5 or lower.
I'd recommend if testing from master to do a build from brave/browser-laptop-bootstrap.
it's a long 1 time setup but you'll be up to date with electron and browser-laptop changes, which we are frequently making especially right now.

To setup just `npm install`, `npm run init`, and `npm run build`.
The init can take an hour and the build might take a couple, but incremental builds after that are fast.

**Comment by bbondy** [comment]
Please re-open if you find it's an issue on 2.0.6 or later though.

**Comment by luixxiul** [comment]
Test plan:

Open any link by clicking it pushing the command key
