### ISSUE TITLE
command+c to copy does not work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6412]
**Describe the issue you encountered:** command+c to copy does not work

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): f04777e

- Steps to reproduce:
    1. Select a word
    2. Hit command+c

- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul is this when running from source? If so, have you updated electron recently? 

Should have been fixed with:
https://github.com/brave/browser-laptop/commit/e6b855eee86a3d84639b1c8b7af2fec8d8de7771
(I can't find the Muon commit for some reason)
cc: @bbondy

**Comment by luixxiul** [comment]
I think this can be closed in favor of https://github.com/brave/browser-laptop/issues/6411#issuecomment-269040862
