### ISSUE TITLE
Make pinned tabs share the same tab content across windows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6413]
This is expected to fix pinned tab tests

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bbondy** [comment]
Most of the ground work done here https://github.com/brave/browser-laptop/pull/8084 but probably not happening before 1.0.

**Comment by hugobuddel** [comment]
This would be awesome. For most of my pinned tabs it would be fine if they share the same content across windows.

Many of my pinned tabs are chats, and some, like Whatsapp Web, will work only in a single page. So Whatsapp Web will effectively not work as a pinned tab.

Furthermore, it takes about 30 seconds for all my pinned tabs to load, making a new window effectively useless for half a minute, see #13804.

There are some tabs for which it might be useful to have different versions in different windows, e.g. task trackers or so. But I'd rather have all those tabs also share content than none of them like it is now.

**Comment by bsclifton** [comment]
Pinned tabs in [brave-core](https://github.com/brave/brave-browser) should only exist in the window they were pinned on; closing this issue as it should be addressed

**Comment by hugobuddel** [comment]
Hmm, I like the pinned tabs to be in every window. I use different windows for different 'subjects' and pin things that are always relevant. (I just don't like that it currently is very hard to use a new window until all pinned tabs have loaded.) There seem to be several pinned-tab related extensions for Chrome though, so probably one of them will allow sharing pinned tabs across windows

Is there any way we can already run brave-core? You close many issues, which to me seems a bit premature if it is not possible to run the fixed code.
