### ISSUE TITLE
Labels and buttons in notification bar behave unpredictably

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6417]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Parts of the notification bar behave unpredictably. Some elements suggest they are selectable, when they are not. Others, give no indication that that they are selectable, when in fact they are.

**Expected behavior:**
In general, text in the notification bar should not be selectable.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version (revision SHA):** 0.12.15

**Screenshot if needed:**
![buttons-and-labels](https://cloud.githubusercontent.com/assets/815158/21466126/596d5572-c983-11e6-8ba8-8111a77a45df.gif)

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
