### ISSUE TITLE
about pages pick up favicon from previous page

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#642]
Testing: 0.7.13 on Mac
Load twitter.com
In the same tab, load about:about or about:preferences
Notice twitter favicon on about page.

**Comment by psimyn** [comment]
I can also replicate this going from twitter.com to google.com (but not other way). Seems like it happened for pages that loaded too fast..

**Comment by psimyn** [comment]
Ignore that, was probably just from my messing around. It's because page-favicon-set doesn't get fired. Could maybe unset the favicon in did-navigate
