### ISSUE TITLE
Unable to run Brave nightly after pulling from master

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6420]
**Did you search for similar issues before submitting this one?**
No related issue

**Describe the issue you encountered:**
After pulling master, several features stopped working (payments, new tab DnD, webview-level devTools). Also the above errors were reported:

<img width="555" alt="screen shot 2016-12-25 at 03 00 26" src="https://cloud.githubusercontent.com/assets/4672033/21471611/b6396572-ca9e-11e6-954f-a12c4f73e79d.png">

<img width="995" alt="screen shot 2016-12-25 at 12 39 06" src="https://cloud.githubusercontent.com/assets/4672033/21471619/e4ee9b58-ca9e-11e6-9ce7-5ebe0cb91dfa.png">

- Platform (Win7, 8, 10? macOS? Linux distro?): OSX El Captain

- Brave Version (revision SHA): 7a36087260f5f6845daa5ae62a32814194439d57
- Content inside `.electron/` folder: `brave-v2.0.5-darwin-x64.zip`

- Steps to reproduce:
    1. Do a fresh clean npm and Electron installs: 
        * `rm -rf ~./electron && rm -rf node_modules` then `npm i`
    2. Start Brave

**Comment by cezaraugusto** [comment]
Running Node v7.2.1. Tried v6.9.2 as well. Node-gyp v3.4.0

as a side note, tried reverting 2157ce2288ac73d97e27b7806ce4ca866b187bd8 (downgrade Muon to v2.0.4) but that doesn't seem to be what's causing the error.

**Comment by luixxiul** [comment]
I think this is the same issue: https://github.com/brave/browser-laptop/issues/6411#issuecomment-269040862

> This is only a problem if you're using Electron 2.0.5 or lower.

**Comment by cezaraugusto** [comment]
@luixxiul yes this was my first guess. But I'm running now Muon v2.0.4, and reverting 3004b9e80e4bd5ba9fcabea53e627e3144e26dda solved the problem.

/cc @bridiver @bbondy

**Comment by cezaraugusto** [comment]
ok I'll close this after feedback from @bbondy. Per his comments:

it's best for now while we're heavily working on 0.13 with muon changes to clone from browser-laptop-bootstrap and build from there.

After cloning:

*  `npm install`
* `npm run init` (takes an hour)
* `npm run build` (takes a couple hours).  
* cd `src/browser-laptop`, `npm run watch`
* from the cloned original dir in a new terminal `npm start`.   

If work is not possible because of the setTabIndex thing:
* `git revert 901d28cf5d752d707bd6ab2cb4351547749d6096`
* `git revert 3004b9e80e4bd5ba9fcabea53e627e3144e26dda` 

It's also advised to don't push out those reverts (only locally).
