### ISSUE TITLE
Bookmark folders does not display in the bookmark icon dropdown.

### ISSUE THREAD

**Issue by dhiva** [brave/browser-laptop#6425]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
When trying to add site to bookmark using the star button in address bar. The folder drop down menu does not show already existing folder list. It displays only the default "Bookmarks toolbar" in the dropdown. It also does not have feature to add new folders on the fly.

**Expected behavior:**
When adding bookmark I expect to see the folder dropdown display all the available folders that are already created and also add new folder option.
- Platform :
Linux Ubuntu 16.04
- Brave Version (revision SHA):
Brave 0.12.15

#1658

**Comment by Liunkae** [comment]
I am able to see folders in the dropdown.
![image](https://cloud.githubusercontent.com/assets/19424103/21594542/4c770cec-d0e9-11e6-8478-6474040ae621.png)
However, I agree that there is no way to create a new folder from there.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/create-new-folder-when-adding-bookmark/10521/2?u=eljuno

>after making the new folder it doesn’t show in the drop down menu when you click the little star by the address bar.
