### ISSUE TITLE
New “Private + session tab” feature with combined functionality

### ISSUE THREAD

**Issue by dhiva** [brave/browser-laptop#6426]
At present when I create multiple private tabs it looks like all the private tabs seems to open in same session. And when I using new session tab then I see that the session is specific to that tab and it is not shared. I would like to have a feature to have new private+session tab so that all my private sessions are individual.

example Use case: trying to open muliple gmail accounts in private tab. This is not possible at the moment. I need to create a new session tab to have multiple gmail accounts open. but then it does not have the features of private tab.

**Comment by bbondy** [comment]
Agreed, I'd like this feature too, it's being tracked here though so I'll close this. Thanks for the report:
https://github.com/brave/browser-laptop/issues/597
