### ISSUE TITLE
Re-Release debian apt  repo

### ISSUE THREAD

**Issue by posix4e** [brave/browser-laptop#6427]
We misspelled the last release of debian. We need to re-release checking jessie support.

**Comment by huuhaa** [comment]
When will this get fixed? Still gives error 403.

There is also another issue, I mention it here but freel free to move that part under another topic / if it is copy of somethoing previous (did'nt find by quick search).

The another issue is that if you manually upgrade brave for Jessie Brave won't starup anymore. It gives error:
[3382:3382:0217/134018.581411:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Keskeytetty

I choose not to try without Sandbox, so I'm forced to use firefox again.

**Comment by huuhaa** [comment]
When will repo for stretch be available? Or is it just that I had to wait till tomorrow and it works like it strangely was earlier with jessie repo...

**Comment by huuhaa** [comment]
Just an update, but I leave this as new comment. Stretch repo still gives 403 (probably cause there's not repo for stretch?) and in addition apt gives following message:

`
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`
