### ISSUE TITLE
Zoom in with cmd + plus on German keyboard

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6428]
**Describe the issue you encountered:**
https://community.brave.com/t/zoom-in-with-cmd-plus-on-german-keyboard/401
> On my German keyboard, cmd+plus doesn't work to zoom in.
>
> cmd+minus works to zoom out. cmd+0 works to revert to 100% size. Only cmd+plus does not work.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.

- Any related issues:

**Comment by Zuzu-Typ** [comment]
I'm using a german keyboard too and I don't have a problem zooming with either plus / minus key (there's two of each on the standard de-DE keyboard layout)

**Comment by Jacalz** [comment]
+1 from [community](https://community.brave.com/t/zoom-in-with-cmd-plus-on-german-keyboard/401/3?u=jacalz)

**Comment by Jacalz** [comment]
I can confirm that cmd + plus does not work when using a Swedish keyboard but cmd + minus and cmd + 0 works as expected... Only reproducible on mac for me :sweat_smile:

**Comment by toruwest** [comment]
I'm using Japanese version of Macos high sierra 10.13.2 (current latest version) with mac book air.
zoom in function is assigned to command and '=' (shift+minus key in Japanese keyboard layout) but it doesn't work as expected. It works as if shift key is ignored, so, it works as command and '-' key, this means that if I want to zoom in, the window is zoom out (sigh...).

By the way, why isn't this function  assigned to command and '+' keys, like other browsers (google chrome, firefox, safari) on mac os?  Only Japanese ?

**Comment by bsclifton** [comment]
@Jacalz do you know if this works with [Brave Core](https://github.com/brave/brave-browser)?

If folks wanted to try it, you can grab the latest release here:
https://github.com/brave/brave-browser/releases

**Comment by Jacalz** [comment]
I think it does, but I will need to double check that tomorrow evening. @bsclifton

**Comment by Jacalz** [comment]
Yes, I can comfirm that this works with Brave Core. Adding the label to it. Let's close this if you think that this won't be resolved before 1.0.
