### ISSUE TITLE
Set the language setting automatically

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6435]
**Describe the issue you encountered:**

See: https://github.com/brave/muon/issues/133

For now those who do not understand English at all cannot use the browser. I believe the issue needs fixing by 1.0 if we release it globally.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version (revision SHA):

- Any related issues: #4351

**Comment by thierryOrdissimo** [comment]
Thank you, reopen a ticket. For me, actually without the automatic location, Brave is not usable by the greatest number.

**Comment by luixxiul** [comment]
+1 from https://community.brave.com/t/thanks-for-the-very-high-quality-browser/8807

**Comment by Jacalz** [comment]
+1 from me

**Comment by bsclifton** [comment]
Needs verification- but this is likely fixed with Brave Core

**Comment by bsclifton** [comment]
@Jacalz can you verify that brave-core defaults your language to Swedish?

**Comment by Jacalz** [comment]
Yes indeed, this works in brave-core 👍
