### ISSUE TITLE
ledger status needs a 'retry' button

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#6436]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
even though my internet is working, about:preferences#payments balance says 'This site can’t be reached because server DNS address could not be found'

**Expected behavior:**
there should be a 'retry' button to refresh the wallet balance and status once internet is connected

- Platform (Win7, 8, 10? macOS? Linux distro?):
os x

- Brave Version (revision SHA):
0.12.15

- Screenshot if needed:
![screen shot 2016-12-27 at 6 39 40 pm](https://cloud.githubusercontent.com/assets/549654/21505971/3b4e1354-cc64-11e6-8bdc-42151e128271.png)

**Comment by NejcZdovc** [comment]
I think that we can close this one as we have network problem overlay now, that goes away when everything is ok
