### ISSUE TITLE
Embedded links in emails treated as Search terms, not Links

### ISSUE THREAD

**Issue by ktd99** [brave/browser-laptop#6438]
**Did you search for similar issues before submitting this one?** No

**Describe the issue you encountered:**  Instead of taking me to the web site, Brave treats an embedded link (which I click on) as a search term.

**Expected behavior:**  Brave should simply take me to the web site.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Win 7

- Brave Version (revision SHA): 0.12.15

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Hi @ktd99- this has recently been fixed :smile: 

It was fixed with https://github.com/brave/browser-laptop/pull/6086 and will be in our next release (which should be coming soon with LOTS of other great fixes).  I'll close this as a duplicate
