### ISSUE TITLE
Focus ring on ledger url looks strange

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6439]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
This is a follow-up from https://github.com/brave/browser-laptop/pull/6037#issuecomment-265165002 where @luixxiul found the focus rings on our ledger items look a bit strange.

**Expected behavior:**
It would be nice to give the link some extra padding so the focus ring looked better (or make just the link clickable and not the link and the favicon!)

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.12.15

- Steps to reproduce:
    1. Go to Preferences > Payments
    2. Make sure you have a wallet created and some sites showing in your list
    3. Tab through the document until you get to the list

- Screenshot if needed:
Notice it looks like:
<img width="155" alt="ledger_link" src="https://cloud.githubusercontent.com/assets/490294/21511781/abfe44c4-cc6a-11e6-9bb4-5370812eef83.png">

- Any related issues:

**Comment by luixxiul** [comment]
Closing this for now as the original issue has been closed.
