### ISSUE TITLE
autocomplete popup hangs around too long

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#644]
Testing 0.7.13 on Mac
Type cnn.com into the addressbar. See the autocomplete popup. Hit enter. Page loads and autocomplete popup hangs around. It's not dismissed until I click the page or the toolbar.

**Comment by asadotzler** [comment]
cannot reproduce.

**Comment by bbondy** [comment]
I've seen before, not sure of exact STR yet. I'll re-open.

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/browser-laptop/commit/c52e24c4244c3be58c1652725f625e288b8c68e5
