### ISSUE TITLE
Opening new tab shows error

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6442]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening about pages/new tab shows error

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
```
Master
Brave: 0.13.0 
rev: undefined 
Muon: 2.0.5 
libchromiumcontent: 54.0.2840.59 
V8: 5.4.500.31 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Build from master
    2. Open a new tab, shows error in browser console
    3. Open about:about and click on any about page to open in new tab, shows error in console

- Screenshot if needed:
![console_error](https://cloud.githubusercontent.com/assets/17010094/21521762/c8a64dbe-ccf7-11e6-9b88-7ffca6362f2a.gif)

- Any related issues:
#5935 cc: @bridiver

**Comment by bbondy** [comment]
This is from not using the latest electron, 2.0.6 will fix this but it isn't available in prebuilt yet.
