### ISSUE TITLE
GPU-related high battery use on MacBook Pro with Touch Bar

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#6443]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I was trying to figure out who was eating my battery on new MacBook Pro with Touch Bar. Apple's Activity Monitor utility reported that Brave requires high-performance GPU, which I read as the AMD discrete chip, not the integrated Intel graphics. Activity Monitor reported this requirement down to having one last website open, pretty static (http://phx.corporate-ir.net/phoenix.zhtml?c=176060&p=irol-newsArticle&ID=2232897), and then with no windows at all, and with the new-tab page showing. I have LastPass and PDF Viewer extensions running.

Google Chrome also requires high-performance GPU (at least at the moment I checked, with light load of websites). Safari and Firefox do not.

This could be related, but it's not clear whether this is considered a problem with newer Macs.
https://bugs.chromium.org/p/chromium/issues/detail?id=479299

The gfxCardStatus (https://gfx.io/) utility reported that Brave Helper required the GPU. When I quit Brave, the Mac immediately switched to integrated Intel GPU. When I relaunched immediately afterward, Brave did *not* require the high-performance GPU (AMD Radeon Pro 460).

**Expected behavior:**
Brave shouldn't require or use the discrete GPU for ordinary websites.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12.2

- Brave Version (revision SHA):
Brave	0.12.15
Muon	1.4.31
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	darwin
os.release	16.3.0
os.arch	x64

- Steps to reproduce:
1. run Brave.
2. Open Activity Monitor

- Screenshot if needed:
Attached Activity Monitor screenshot

**Comment by bsclifton** [comment]
Related: https://github.com/electron/electron/issues/9842

As a work-around, you can pass the command line option to Brave:
`--force_discrete_gpu=0`

However, we need to understand this behavior more. The Chromium executable may have GPU detection logic that we're not using

cc: @bridiver

**Comment by bsclifton** [comment]
+1 via https://github.com/brave/browser-laptop/issues/12112

**Comment by stshank** [comment]
I filed #12112 as a separate bug because it behaved differently from the one earlier: the discrete GPU fires up on Brave launch, not just on some website that uses it. It seemed qualitatively different if related.

**Comment by dabar347** [comment]
I second this for Macbook Pro 2013 (with GT 650M)

**Comment by phitboy** [comment]
Hi everyone,

Sorry to bump an ancient thread, but how would I go about running --force_discrete_gpu=0 in my mac terminal? @bsclifton says to run it through Brave, but i am not sure how to do that

**Comment by arkag** [comment]
I'd like an update on this... This is one reason why I can't justify using Brave on my Mac when I love what they're doing with their browser. Having my discrete GPU up while I'm just browsing normal websites kills my battery.

**Comment by fatboyjim** [comment]
+1 

Macbook Pro 2014 user.  I love the browser but I can't use it as my default browser because it rinses my battery through requiring discrete GPU which has a huge impact on battery life.

**Comment by byoung0589** [comment]
I also ran into this issue and created a bug: https://community.brave.com/t/brave-energy-consumption-issues-on-mac/17035/2 

This issue is causing me to not use Brave when I am on Battery power and thus decreasing my time on the browser.

**Comment by NumDeP** [comment]
+1 https://community.brave.com/t/brave-energy-consumption-issues-on-mac/17035

**Comment by Crushhhhhhh** [comment]
+1 Macbook Pro (Retina, 2014)

Consumes all CPU / Energy; Macbook physically overheats if use 20+ Brave tabs.

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try the new Developer channel build and report back?
https://brave.com/download-dev

 I suspect this has been fixed and will close. Let's re-open if the issue still re-occurs with the new Developer channel (brave-core)
