### ISSUE TITLE
Jupyter websocket authentication failed

### ISSUE THREAD

**Issue by cemsbr** [brave/browser-laptop#6444]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Jupyter Notebook cannot connect to its kernel

Developer tools' console error:
```
kernel.js:455 WebSocket connection to 'ws://127.0.0.1:8888/api/kernels/a84bfc73-2fab-4d46-8a90-ad13bef8387c/channels?session_id=961AC3F7A891443DB3652C8748850507' failed: Error during WebSocket handshake: Unexpected response code: 403
    Kernel.start_channels @ kernel.js:455
    Kernel._kernel_created @ kernel.js:402
    on_success @ session.js:109
    (anonymous function) @ session.js:288
    l @ jquery.min.js:4
    fireWith @ jquery.min.js:4
    k @ jquery.min.js:6
    (anonymous function) @ jquery.min.js:6
kernel.js:100 Kernel: kernel_disconnected (a84bfc73-2fab-4d46-8a90-ad13bef8387c)
kernel.js:538 WebSocket connection failed:  ws://127.0.0.1:8888/api/kernels/a84bfc73-2fab-4d46-8a90-ad13bef8387c true
kernel.js:556 Connection lost, reconnecting in 1 seconds.
kernel.js:100 Kernel: kernel_reconnecting (a84bfc73-2fab-4d46-8a90-ad13bef8387c)
kernel.js:453 Starting WebSockets: ws://127.0.0.1:8888/api/kernels/a84bfc73-2fab-4d46-8a90-ad13bef8387c
```
Jupyter log:
```
[W 17:33:44.375 NotebookApp] Couldn't authenticate WebSocket connection
[W 17:33:44.377 NotebookApp] 403 GET /api/kernels/a84bfc73-2fab-4d46-8a90-ad13bef8387c/channels?session_id=961AC3F7A891443DB3652C8748850507 (127.0.0.1) 5.23ms referer=None
```

**Expected behavior:**
No permanent "Connecting to Kernel" warning, as in Firefox or Chromium.

- Platform (Win7, 8, 10? macOS? Linux distro?): Arch Linux

- Brave Version (revision SHA): 0.12.15

- Steps to reproduce:
    1. Run "jupyter notebook"
    2. Open 127.0.0.1:8888
    3. Access a notebook or create a new one

- Screenshot if needed:

- Any related issues:

**Comment by rojour** [comment]
I am having the exact same issue here.
The only thing I may be able to add is that in my case it was working fine until I ran a jupyter notebook from AWS-C2 with an insecure connection. It gave the warning, I ask to be connected any way. It work, but since then, I am having the same issue.

**Comment by cemsbr** [comment]
I haven't had this issue for a long time, fortunately.

**Comment by jonas-pettersson** [comment]
I had this issue as well with the error message "403 POST /api/sessions (127.0.0.1): '_xsrf' argument missing from POST" (connecting from a Windows machine to AWS). When I changed "127.0.0.1" in the URL for connecting to Jupyter to "localhost" it worked again. As there is no explanation here to how the ticket was closed, I just wanted to add that for anyone else landing here... :-)
