### ISSUE TITLE
Menu item's hit/clickboxes are way off when maximized

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#6445]
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
When Brave is maximized, some of the buttons' don't have the right hitboxes

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.13.0 Prev5

- Steps to reproduce:
    1. Maximize Brave
    2. (try to) click on some of the items of the Brave menu. (such as the URL-bar, the new-tab-plus or the minimize / restore buttons)
    3. be shocked

- Screenshot if needed:
Unfortunately I could only record the new-tab-plus...
![newtab](https://cloud.githubusercontent.com/assets/20467351/21532216/8654517a-cd4e-11e6-8b64-2b4b80da4649.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/4922 , https://github.com/brave/browser-laptop/issues/6258

**Comment by Zuzu-Typ** [comment]
For the minimize / restore buttons the hitbox is extended downwards once you've hovered over one of them.
Half of the URL-bar is cut off.
Some other icons are sometimes not clickable at all, such as the refresh, favorize and lock icons.

**Comment by Zuzu-Typ** [comment]
I now found out that you are able to click those formerly unclickable buttons, when opening the menu.
You can clearly see it here: [http://www.mediafire.com/file/9phwck80dm94q8i/0135.avi](url)

**Comment by bsclifton** [comment]
@Zuzu-Typ what resolution and/or DPI are you using?  When you go to display settings for example, are you at 125%?

**Comment by Zuzu-Typ** [comment]
I think I'm using 1920x1080 at 100% DPI (or whichever is the default Windows 10 setting, as I cannot access my PC for the next couple of days).
I so technically have a resolution of 3840x1080 with dual monitors, but that's just a side-note.
I wish you Lücke!

**Comment by Zuzu-Typ** [comment]
Apparently the hitboxes are also corrected once you open the dropdown menu...

**Comment by Zuzu-Typ** [comment]
Here's a gif of the other hitboxes
![honeycam 2017-01-04 17-00-47](https://cloud.githubusercontent.com/assets/20467351/21648790/7f6d612a-d29f-11e6-89a6-eafe634cc736.gif)

**Comment by bsclifton** [comment]
Possibly fixed by https://github.com/brave/muon/commit/30fd6ff5ac772cb645b0d4be78fae49d84fbbb19

We'll want to retest with next build :smile:

**Comment by luixxiul** [comment]
Labelled `QA/required`for the possibility that this has been fixed.

**Comment by bsclifton** [comment]
@luixxiul awesome, thanks for creating this tag (it should help a lot :smile: )

**Comment by bbondy** [comment]
@srirambv @luixxiul @alexwykoff could this one be retested ?

**Comment by Zuzu-Typ** [comment]
The new-tab-plus-sign seems to be fixed in Prev8 one-way at least...
On entering the hitbox, the plus changes color as intended, thow it keeps this color as long as the mouse stays on the dark-gray area of the taskbar.
This also applies for the minimize and restore icons.
Here's a visual representation:
![Taskbar](https://cloud.githubusercontent.com/assets/20467351/21965800/6a3e586a-db67-11e6-90ba-91b65387cd97.gif)

Otherwise the issue persists.

**Comment by bsclifton** [comment]
@Zuzu-Typ good finds! Just to confirm: are you on 200% DPI?

**Comment by srirambv** [comment]
![6455](https://cloud.githubusercontent.com/assets/17010094/21980665/10dba0b4-dbdc-11e6-9ad3-bbcb2b4ae31b.gif)

@bbondy This is how it looks on Win 10 with preview 8 build. The click is off only when the hamburger menu is opened and if you try to click the refresh/home/new tab buttons but it doesn't always happen( Once the hamburger menu is closed the click is recognized only in this scenario) 

The other thing that looks off to me is the new tab button on hover color remains same even if the mouse pointer it moved away from it on the tabs bar into the empty space. Is this expected??

**Comment by Zuzu-Typ** [comment]
@bbondy I guess you mean this: 
![dpi](https://cloud.githubusercontent.com/assets/20467351/21993224/0ea0af7c-dc1a-11e6-8da9-0a06419a9867.png)
As I said it is the default Windows 10 config.

**Comment by bsclifton** [comment]
@Zuzu-Typ perfect- that is exactly what I meant :smile: So you are at 100% DPI

With modern laptops having such high resolutions, many people's computers are automatically configured to be 125% or 200% stock (for example, Surface Book is 200% stock). The default option is hard to guess- thanks for clarifying :smile:

**Comment by bsclifton** [comment]
@srirambv is there any difference with Preview 9?

**Comment by srirambv** [comment]
@bsclifton Quite a lot better than preview 8. Here's the observation on preview 9
1. The new tab hit area is limited now(as expected) so is the window buttons.
2. Hamburger menu tends to be retained as long as the mouse pointer is in the tabs area. Similar to #6700 
3. Bookmark hit area seems to be only on the star, slight off click on the bookmark area is not recognized

Other than that looks good to me. Will log an issue for item 3 

Here's the recording for this on preview 9 http://sendvid.com/pyjysocm

**Comment by srirambv** [comment]
Here's how the bookmark area looks like. Its very small area around the star that is recognized and adds a bookmark. 
![bookmarkhitarea](https://cloud.githubusercontent.com/assets/17010094/22031509/b87c3de0-dcd8-11e6-9036-b6b820f37bb2.gif)

@bradleyrichter  Shouldn't the entire area the star is in be considered as hit area to add a new bookmark?

**Comment by bradleyrichter** [comment]
@srirambv yes, ideally the entire rectangle would be clickable. This is especially important in hi-def desktop views.

**Comment by bsclifton** [comment]
Closing issue as it looks like this has been resolved

@srirambv please create a new issue if there are still problems.  Thanks :smile: 

## Test plan from the original post
1. Be on Windows at 100% DPI
2. Maximize Brave
3. (try to) click on some of the items of the Brave menu. (such as the URL-bar, the new-tab-plus or the minimize / restore buttons)
4. Before, you may have been shocked because it doesn't work; however, it should work beautifully now.

**Comment by srirambv** [comment]
Preview 10 looks same as on preview 9. 👍

**Comment by Zuzu-Typ** [comment]
It seems that the issue is back.

Unfortunately I couldn't go back to version 0.13.0 preview 10 to check if the issue reoccured or wasn't fixed in it's entirety, because the browser would throw an uncaught exception and crash.

However in every version from 0.13.2 to the current git repository (03/03/17) some hitboxes are off.

This applies for most hitboxes, including the favorize button, the reload button, the new-tab button, the search icon and (especially) the url bar itself. All of their hitboxes are a little offset to the left and up.
So much so, that you can only click the upper half of the url bar.

**Comment by Zuzu-Typ** [comment]
Here's a visual representation of where the hitboxes are, when the window is maximized.
![hitboxes](https://cloud.githubusercontent.com/assets/20467351/23578419/e1ecd866-00d6-11e7-9bf5-d4e4be63c60f.png)
