### ISSUE TITLE
Unsupported apt flavors return 403

### ISSUE THREAD

**Issue by bsima** [brave/browser-laptop#6446]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

After following instructions in [`linuxInstall.md`](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-trusty-and-xenial-amd64):

```
$ sudo apt update
[...]
Err:7 https://s3-us-west-2.amazonaws.com/brave-apt stretch Release
  403  Forbidden
Reading package lists... Done
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Expected behavior:** apt should successfully pull data from the brave-apt repository

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian Squeeze
```
ben@neb ~ : uname -a && lsb_release -a
Linux neb 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
```
- Brave Version (revision SHA): n/a
- Steps to reproduce:
    1. Follow the [directions exactly](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-trusty-and-xenial-amd64)
    2. execute `sudo apt update` (`sudo apt-get update` = same error but with more detailed logging)

- Any related issues: could not find any, but SO says this is probably a [server error](https://askubuntu.com/questions/304340/apt-get-403-forbidden#308348)

**Comment by bsima** [comment]
After changing `stretch` to `jessie` in `/etc/apt/sources.list` for the brave-apt entry, it still fails:

```
Err:8 https://s3-us-west-2.amazonaws.com/brave-apt jessie/main amd64 Packages
  403  Forbidden
[...]
W: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt jessie Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/jessie/stretch/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by posix4e** [comment]
it's currently mispelled as jesse . It will be fixed in the next release (and nightly should work)

**Comment by Fromax** [comment]
"jesse" really? You could at least update your linuxInstall.md...

**Comment by bbondy** [comment]
@Fromax it was updated 14 days ago here: https://github.com/brave/browser-laptop/commits/master/docs/linuxInstall.md 

This is a work in progress repository where mistakes are made and corrected on a daily basis, Saying ""jesse" really?" is a bit rude, isn't constructive, and doesn't help.  Please keep a positive attitude, thanks.

**Comment by Kwaskoff** [comment]
forbidden yet
![screenshot from 2017-01-12 14-02-17](https://cloud.githubusercontent.com/assets/15308024/21887404/2fe9f4f2-d8d9-11e6-93f1-30ef6713a53c.png)

**Comment by Fromax** [comment]
@bbondy 

> it was updated 14 days ago here: https://github.com/brave/browser-laptop/commits/master/docs/linuxInstall.md

Yes, but it still doesn't reflect the misspelling of "jessie" as "jesse".

> This is a work in progress repository where mistakes are made and corrected on a daily basis, 

I understand that.

> Saying ""jesse" really?" is a bit rude, isn't constructive, and doesn't help. Please keep a positive attitude, thanks.

Sorry for my wording. I guess I got frustrated not being able to figure out why it didn't work...
But why not add a temporary statement to make clear of the misspelling?

Besides that, I think you should just settle to *list* the names of your repos. We know how to edit our `sources.list` by hand. Trying to guess the linux flavor by parsing the `lsb_release` in a script is basically broken: My distro would produce _"betsy"_ as a result, while my sources.list are using _"jessie"_ (I'm running LMDE, "Linux Mint **_Debian_** Edition")... Just trying to be constructive!

**Comment by posix4e** [comment]
@Fromax I'm so embarrassed. Let me fix that asap!

**Comment by posix4e** [comment]
@Fromax I noticed jessie worked just fine from my VM. We do call out what repos we support in the docs and provide specific instructions for mint

**Comment by posix4e** [comment]
@Fromax  and by fine i found https://github.com/brave/browser-laptop/pull/6622 !

**Comment by Fromax** [comment]
@posix4e 
> and provide specific instructions for mint

Yes, for "Linux Mint"... FYI, LMDE (Linux Mint _Debian_ Edition) is quite another animal! **Linux Mint** is based on _Ubuntu_. **LMDE** is based om _Debian_ ("jessie", for the time being) and is completely compatible with Debian stable.

I never actually tryied to run the script, as I knew the result would be wrong. Instead, I crafted my own `/etc/apt/sources.list.d/brave.list` with the following string:
> `deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt/ jessie main`

... which _should_ have worked, don't you agree?

**Edit**: I guess you just symlinked 
`https://s3-us-west-2.amazonaws.com/brave-apt/ jesse main` 
to 
`https://s3-us-west-2.amazonaws.com/brave-apt/ jessie main` 

... as both work now!
Good job!

**Comment by posix4e** [comment]
@Fromax it might, i would like to test it before I claim it does

**Comment by posix4e** [comment]
@Fromax we don't support precise out of the box yet, that's right

**Comment by posix4e** [comment]
ooh wait @Fromax jessie is not stable so it is supported

**Comment by crysman** [comment]
Not working on my Xubuntu yaketty either, same issue:

```
sudo apt update
Hit:1 http://cz.archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://cz.archive.ubuntu.com/ubuntu yakkety-updates InRelease        
Hit:3 http://cz.archive.ubuntu.com/ubuntu yakkety-backports InRelease                        
Hit:4 http://security.ubuntu.com/ubuntu yakkety-security InRelease                           
Ign:5 https://s3-us-west-2.amazonaws.com/brave-apt yakkety InRelease           
Err:6 https://s3-us-west-2.amazonaws.com/brave-apt yakkety Release
  403  Forbidden
Reading package lists... Done
E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt yakkety Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I've followed the official instructions here just now.
I've checked the sources.list (added some comments to it) and it seems fine:
```
tail -4 /etc/apt/sources.list

#brave browser
#https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt yakkety main

```

Importing the key also seems fine:
```
curl https://s3-us-west-2.amazonaws.com/brave-apt/keys.asc | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3165  100  3165    0     0   2150      0  0:00:01  0:00:01 --:--:--  2150
OK
````

Where might be the problem then? :/

**Comment by posix4e** [comment]
If the deb is verified we'd be happy to add it. Honestly it's just a pull request away
https://github.com/brave/browser-laptop/blob/master/tools/upload_to_aptly 
Maybe we should convert it to a single sequence!

**Comment by ahmetasabanci** [comment]
As a workaround to yakkety being not supported, I went to `/etc/apt/sources.list.d/brave-yakkety.list` in my system and changed

`deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt yakkety main`

to

`deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt xenial main`

and it installed without any problem and seems like works fine so far. Guess Xenial version doesn't have so much problem with Yakkety.

**Comment by Liunkae** [comment]
Yakkety is now supported (https://github.com/brave/browser-laptop/issues/6643#issuecomment-277091545).

**Comment by crysman** [comment]
@Liunkae OK, thanks for noticing. It works now.

I am just wondering why the installation (`sudo apt install brave`) invokes "...computer needs to restart..." ?? This is highly suspicious and non-standard, since only system packages upgrades invoke the restart prompt...

**Comment by BurkeRS** [comment]
I will post here first rather than start a new issue since my problem is closely related. I'm using latest Linux Mint, have installed brave and it is working well. But in apt-get update I get the same message as noted above:
The repository 'https://s3-us-west-2.amazonaws.com/brave-apt serena Release' does not have a Release file. 
The contents of my /etc/apt/sources.list.d/brave-serena.list are:
deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt serena main
Is this correct? If not, how can I fix it? If so, why isn't it working.
I like brave and want it to update correctly. Thanks for any help.

**Comment by posix4e** [comment]
@BurkeRS  Sorry for the delay. Not sure how I missed this. You should be able to use the ubuntu repo. Try changing to a flavour of ubuntu and see if it works for you.

**Comment by ronaldburke** [comment]
Thanks, posix4e. I removed brave-serena.list and added the brave-apt xenial main repository. It does seems that should work. If not, I'll be back again. Thanks again. I like the browser and I like the payment plan.

**Comment by JGH1000** [comment]
+1 still can't install on Ubuntu 16.04 LTS

**Comment by posix4e** [comment]
@JGH1000 give me more of an explanation. I am running brave on 16.04 LTS just fine

**Comment by JGH1000** [comment]
@posix4e 
Sorry, should have done it in the first post. I am using Elementary OS which is based on Ubuntu 16.04 LTS. This is the message I get when I try to update through apt, before even installing:

E: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt loki Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I would prefer apt as snaps for some reason never update for me.

**Comment by posix4e** [comment]
You should be able to use the linux mint install of just downloading the deb.

**Comment by JGH1000** [comment]
I did, but I don't think people get updates after installing this way. Anyway the install instructions do not work so I thought I would report. Up to you guys to decide what to do with them. Thanks!

**Comment by Raindeer44** [comment]
I got the same "403 Forbidden" coming from the AWS repo when using the instructions in linuxinstall.md from Linux Mint 18.2, however I fixed it by manually switching the .list to Xenial.

Specifically, in `/etc/apt/sources.list.d/brave-sonya.list` I changed

    deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt-staging sonya main

to

    deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt-staging xenial main

and then everything works perfectly. I don't have much experience with apt beyond basic usage, so I don't know if this has any effect on updating, but it sure works for now.

**Comment by posix4e** [comment]
@Raindeer44  I specifically have said many times we don't have a sonya repo.

**Comment by Raindeer44** [comment]
@posix4e it would definitely be nice if info like that could be included in the `linuxinstall.md`, regardless of how many times you may have said it.

**Comment by posix4e** [comment]
Haha, good point! If you add it I'll commit it :)

**Comment by Raindeer44** [comment]
Hey, good point. It's almost like this is open source software or something :) I'll try adding in a little section.

For reference, is there (or can you provide) a convenient list of flavors that _are_ supported?

**Comment by posix4e** [comment]
I test debian, ubuntu and centos currently. I think we are going to add appimage and snap soon. Also I expect to add mint and others down the line. Note we work on those platforms I just don't yet have the automation to test it.

**Comment by Raindeer44** [comment]
Just opened a PR for this. Sorry it took a while, I was waiting for Hacktoberfest to start since this isn't a critical issue.

**Comment by posix4e** [comment]
Looks good at first glance. Thanks for doing this BTW. I assume you only tested one version? It's an improvement either way

**Comment by rolandixor** [comment]
This still needs to be addressed in the documentation. I'm on cosmic, and was running into this issue trying to add the -dev repo. Manually editing the line to read bionic instead of cosmic is the fix, but there is no way to figure this out if you're not familiar with apt, and do some digging.

**Comment by thornjad** [comment]
@rolandixor this repository is being deprecated, so documentation here won't be updated. Try out [brave-browser](https://github.com/brave/brave-browser), and open an issue there if it's still causing you trouble.
