### ISSUE TITLE
Ledger recovery error if fields aren't set

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6447]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**

If you try to recover your keys with either of the fields empty it causes a JavaScript error.

**Expected behavior:**

It should not cause a JavaScript error and maybe it should give the user some feedback about needing to fill in the fields.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version (revision SHA):
master

- Steps to reproduce:
  1. Go to Preferences#payments
  2. Click Advanced Settings
  3. Click recover your wallet
  4. Click Recover
  5. Notice the Cannot read property 'FirstRecoveryKey' of null error in the console

- Screenshot if needed:
<img width="800" alt="screen shot 2016-12-28 at 7 05 44 pm" src="https://cloud.githubusercontent.com/assets/490294/21535343/de76925a-cd30-11e6-806a-021e9742da2c.png">

- Any related issues:

**Comment by willy-b** [comment]
fwiw, I believe this is fixed as part of PR #5809 , but probably simpler to do a separate fix.

**Comment by jkup** [comment]
@willy-b awesome! I think maybe for this ticket I can just set initial values for this.state.firstKey and this.state.secondKey so they don't cause JS errors because honestly it's ok if you try to recover with empty or bad data (you'll just get the regular error!)

**Comment by willy-b** [comment]
ok, I believe it fixes the JS errors too and adds tests for 1 missing key, 2 missing keys, etc, but I'll just follow whatever lead you set here. thanks

**Comment by jkup** [comment]
@willy-b no totally I think yours will fix a lot more! I just think it's best practice to set default state in components so our changes should play well together :)

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6455#issue-198102664

**Comment by luixxiul** [comment]
Added release-notes/exclude as the feature to import recovery keys has been implemented since 0.13
