### ISSUE TITLE
printToPDF isn't working

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6450]
Its callback is never called, I think the renderer needs to handle the message.

**Comment by willy-b** [comment]
are you replacing the use of printToPDF in #4769 or are you fixing printToPDF itself?

I'm asking because normally the webview.printToPDF method invokes the callback with two args (error, data)..
if the callback is never called, how do you get the PDF data in the renderer?

**Comment by bsclifton** [comment]
It may be due to this:
https://github.com/brave/muon/commit/46407b659e7513bf06a7f4f5a9b2f6627371978d#diff-a2a29fbd6a5f9747649d3c2c444dae3f

Let's try adding back in the two files that were removed

**Comment by bbondy** [comment]
I'm going to try to get webcontents.printToPDF to work

**Comment by willy-b** [comment]
woah, 63 chromium level files changed in a single patch file for this! (https://github.com/brave/muon/blob/9ea426b623d79450272736789d4e651669ad5230/patches/master_patch.patch)

is fixing this Electron-level API regression so complicated because Brave's Electron fork (Muon) is using a more recent version of Chromium (54) than upstream Electron?

**Comment by bbondy** [comment]
It isn't as impressive as it sounds because this is just a change of an existing patch file.  A diff of a patch looks pretty deceiving.  There were a bunch of changes but definitely no 63 files worth :P

**Comment by bbondy** [comment]
confirmed my patch works on macOS and linux but not Windows, will get back to this soonish.

**Comment by willy-b** [comment]
sorry to pester with a question, but when does this come into `brave/browser-laptop`?

trying to figure out if I should revert the PDF statement before next release or not

**Comment by bbondy** [comment]
It will be in Preview7 or anything after muon v2.0.8

**Comment by willy-b** [comment]
hey I can confirm this works on Linux in Preview7, but @srirambv shared a screencap of it still being broken on Windows (https://github.com/brave/browser-laptop/pull/6385#issuecomment-269774849)

**Comment by willy-b** [comment]
@bsclifton so this is only broken on Windows now.

Do you think we need to add those two files back in?

**Comment by bsclifton** [comment]
@willy-b no- I don't think it will help. @bbondy is investigating it though :smile:

**Comment by willy-b** [comment]
sweet! one last question -- do you know what tag/release for `brave/browser-laptop` will have https://github.com/brave/muon/commit/465539ead14fb035185ff6aff6492eff14420348 in it?

**Comment by bbondy** [comment]
Preview8 and 0.13 release will have it.

**Comment by luixxiul** [comment]
@willy-b @bbondy would you please specify QA steps or the commit which has them in its commit message?

**Comment by bbondy** [comment]
It passes if this passes:
https://github.com/brave/browser-laptop/issues/4769

So I'll mark this as no qa needed.

**Comment by willy-b** [comment]
Happy to help test this on Linux and Windows -- Do you know when Preview8 is coming?

**Comment by willy-b** [comment]
got `browser-laptop-bootstrap` integrated build with Muon working and can confirm #4769 is working on Linux with @bbondy's latest changes.
