### ISSUE TITLE
Linux is not using the correct userData directory for development builds

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6451]
It currently uses the CWD instead of ~/.config/

**Comment by willy-b** [comment]
fwiw, I'm on Ubuntu LTS 14.04 and Brave uses `~/.config/brave-development for development` and `~/.config/brave` for production

**Comment by Sh1d0w** [comment]
I can confirm it is using `~/.config` directory correctly under Fedora 25.

**Comment by bbondy** [comment]
This only effects development builds, updated title.

**Comment by bridiver** [comment]
@posix4e can you take a look at this?

**Comment by willy-b** [comment]
I can't reproduce this in development with yesterday's master on Linux. What Linux are you on @bbondy and what rev?

**Comment by posix4e** [comment]
@bridiver will do next! I think i told him, about it :)

**Comment by bbondy** [comment]
Already grabbed it.

**Comment by bbondy** [comment]
Test plan: npm start from Linux only and if it doesn't create a brave-development folder then it is fixed.
