### ISSUE TITLE
Opening a new about page / page linked from about pages feels laggy

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6453]
**Describe the issue you encountered:**
Opening a new about page / page linked from about pages feels laggy.

I cannot reproduce the issue after opening the page or restarting the browser.

**Expected behavior:**
The page should instantly render the page

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0c7a64d, packaged build

- Steps to reproduce:
    1. Opening a new about page which you have never opened since upgrading your packaged build, for example, Password Manager from Menu
    2. Wait for several (~5) seconds
    Then the page starts rendering finally

I've experienced the issue when I opened the Payments FAQ page by clicking the question mark on about:preferences#payments, though I can no longer reproduce it 

- Any related issues:

**Comment by luixxiul** [comment]
I labelled `chromium54` wondering if it was correct, so please feel free to remove it if I was wrong, thanks.

**Comment by bbondy** [comment]
Is it possible that your computer was building browser-laptop-bootstrap at the time? That can slow down things a lot. 

I tried to reproduce with cleared session directories and I cannot. I'm going to remove from 0.13.0 for now but please re-add if you see it a lot more or if you find consistent steps.

**Comment by luixxiul** [comment]
I haven't noticed it for a while
