### ISSUE TITLE
Clicking "Copy" buttons on "Backup your wallet" needs an animation

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6459]
**Describe the issue you encountered:**

<img width="276" alt="screenshot 2016-12-30 16 05 30" src="https://cloud.githubusercontent.com/assets/3362943/21560973/d019f650-cea9-11e6-9c31-cea809b74759.png">

**Expected behavior:** https://github.com/brave/browser-laptop/issues/6297#issuecomment-268046716

> The string would appear quickly and fade away.

- Platform (Win7, 8, 10? macOS? Linux distro?):  macOS

- Brave Version (revision SHA): 0c7a64d

- Any related issues: #6297

**Comment by arsalankhalid** [comment]
Taking this on, assigned by @NejcZdovc
