### ISSUE TITLE
IME for Japanese freezes webview inside a tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6463]
**Describe the issue you encountered:**
If you enable IME for Japanese, hit some keys inside a input form on a page and the space key to select conversion candidates, the tab (under `webview`) freezes and accepts nothing until you close the tab.

**Expected behavior:**
It should not freeze

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0c7a64d

- Steps to reproduce:
    1. Enable Japanese IME following the instruction here: http://redcocoon.org/cab/mysoft.html
    2. Open https://github.com/brave/browser-laptop in a new tab
    2. Select the search input area on that page
    3. Hit `a` to input `あ`
    4. Hit the space key
    5. Hit the enter key
    Then the tab freezes; you can neither clear the character nor click any links

- Any related issues:

This could not be confirmed on 0.12 series. I think this might be related with cr54 update.

**Comment by luixxiul** [comment]
Even pasting a Japanese character into the input area freezes tab.

**Comment by bbondy** [comment]
Perhaps it is session store related? For me it is working correctly (I think, it's the first time I tried it).  It does not freeze the tab.  Maybe you can send me your session store file?

![screenshot 2016-12-30 11 03 41](https://cloud.githubusercontent.com/assets/831718/21568112/bec8aa92-ce7f-11e6-94a2-4e9916d6e834.png)

**Comment by luixxiul** [comment]
Please open https://github.com/brave/browser-laptop in a new tab and select the search input area here:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21568504/98354bdc-cef8-11e6-8804-1495e4ee27b5.png)

**Comment by bbondy** [comment]
I wonder if this could be fixed with ICU, I think we should hold on investigating until we confirm after the ICU fix.

**Comment by bbondy** [comment]
I did reproduce successfully though, thanks for the updated steps.

**Comment by luixxiul** [comment]
I doubt if this is related with IME because the tab freezes after clicking "Edit Post" on your facebook timeline.

I'm not quite sure if this is the same issue though.

**Comment by luixxiul** [comment]
@bbondy can this be closed to based on the ICU change?

**Comment by bbondy** [comment]
It can be closed if it is working, preview 8 which is available has the fix.

**Comment by bbondy** [comment]
Seems to be working for me now, please re-open if you find it doesn't work.

**Comment by luixxiul** [comment]
It seems it has not been fixed completely.

![ime](https://cloud.githubusercontent.com/assets/3362943/21964143/e9aab18a-db89-11e6-87d0-6bab761685f1.gif)

rev	567bd73
Muon	2.0.10

**Comment by bbondy** [comment]
Could you update new steps to follow in the first comment, because the ones there that I followed worked now.

**Comment by darkdh** [comment]
@luixxiul the gif you pasted doesn't look like native macOS Japanese input source
The picture below is what I saw following the `Enable Japanese IME following the instruction here: http://redcocoon.org/cab/mysoft.html`
<img width="255" alt="screen shot 2017-01-16 at 10 46 56" src="https://cloud.githubusercontent.com/assets/11330831/21969431/38646484-dbd9-11e6-81c2-91a751cac88b.png">

**Comment by luixxiul** [comment]
@darkdh it's Google IME

**Comment by darkdh** [comment]
still can't reproduce on
 
![ynzupus0nt](https://cloud.githubusercontent.com/assets/11330831/21970014/acc91726-dbdd-11e6-9080-05023339d065.gif)

rev: 9a98903a037104f0b031d681db6920b2c7deff15 
Muon: 2.0.11

**Comment by luixxiul** [comment]
@darkdh did you hit enter? the 5th step

**Comment by luixxiul** [comment]
Ah I'm guessing the issue was resolved with Muon 2.0.11

**Comment by darkdh** [comment]
yeah, I did. updated with displaying pressed key version
![k5csgkr2vt](https://cloud.githubusercontent.com/assets/11330831/21970164/ec684be4-dbde-11e6-8226-4c42c0be1088.gif)

**Comment by luixxiul** [comment]
Sweet :-D

**Comment by luixxiul** [comment]
Test plan:

Enable Japanese IME following the instruction here: http://redcocoon.org/cab/mysoft.html
Open https://github.com/brave/browser-laptop in a new tab
Select the search input area on that page
Hit `a` to input `あ`
Hit the space key
Hit the enter key

Then the tab should NOT freezes
