### ISSUE TITLE
1Password extension authorization doesn't work, asks to install extension 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6466]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
1Password extension authorization doesn't work, asks to install extension 

**Expected behavior:**
Should show authorization code and enable extensions/widget

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.2.9200 
os.arch: x64
```
- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 7, Ensure 1Password app is running
    2. Enable 1password from preferences
    3. Authorization page opens but asks to install extension

- Screenshot if needed:
![1passwdfail](https://cloud.githubusercontent.com/assets/17010094/21563908/db3f17a2-ce7e-11e6-8d9f-2919d91849c2.gif)

- Any related issues:
#6224

**Comment by srirambv** [comment]
Dashlane widget doesn't work too even with the Windows app open.

**Comment by bridiver** [comment]
what version of 1pw are you using on windows? It definitely works correctly on mac

**Comment by bsclifton** [comment]
@srirambv Dashlane has never worked on Windows, as far back as I can remember.  See https://github.com/brave/browser-laptop/issues/4138 for more info

**Comment by jonathansampson** [comment]
One observation made is that the desktop application will report any browser as having an out of date extension if that browser has not been authorized to speak to 1Password.

![image](https://cloud.githubusercontent.com/assets/815158/21583566/d14dc480-d04c-11e6-86e2-092cd3cab0e1.png)

Once the user clicks "Authorize," this status is replaced by "paired".

![image](https://cloud.githubusercontent.com/assets/815158/21583571/0251c388-d04d-11e6-91cb-9c1fe6a20d62.png)

At the time of this writing, Chrome and Brave both report to be using 1Password 4.6.2.90.
