### ISSUE TITLE
Flash placeholder text is missing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6469]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Flash placeholder text is missing

**Expected behavior:**
Should show the placeholder text 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Enable flash from settings
    2. Visit http://www.y8.com/games/superfighters
    3. Flash place holder is shown with plugin icon but no text is shown

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21567272/ed197b42-cea2-11e6-9e7d-32325c0538f1.png)

- Any related issues:

**Comment by bbondy** [comment]
@bridiver is this the new expected behaviour?

**Comment by bridiver** [comment]
Yes, that is the flash placeholder and is identical to Chrome

**Comment by luixxiul** [comment]
@bridiver still it seems to lack the placeholder text displayed on macOS for me, "Control-click to play Shockwave Flash".

**Comment by luixxiul** [comment]
Is it what is expected?

**Comment by bridiver** [comment]
it might be related to localization on windows or maybe the placeholder is just different. What do you see on Chrome if you turn on click-to-play for Flash?

**Comment by luixxiul** [comment]
CC @srirambv

**Comment by srirambv** [comment]
@bridiver  This is what it shows on Chrome 54. Shows text below the plugin icon
![image](https://cloud.githubusercontent.com/assets/17010094/21571061/799e9686-cec3-11e6-9013-8d1ac955df85.png)

**Comment by bridiver** [comment]
maybe localization then. Let's leave this for now until that is fixed on windows and then check back

**Comment by bbondy** [comment]
Still an issue even in Preview 8 which has the ICU fix. Only in Windows.

**Comment by bbondy** [comment]
Fix will be in Preview9

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
