### ISSUE TITLE
Pinned tab height and position of new tab icon inconsistencies

### ISSUE THREAD

**Issue by rob-blasetti** [brave/browser-laptop#647]
When I have only pinned tabs in my browser the height is off.
Also when there are only pinned tabs the 'new tab' icon spontaneously moves to the far right hand side of the nav bar.

<img width="1431" alt="screen shot 2016-02-07 at 7 16 19 pm" src="https://cloud.githubusercontent.com/assets/6110952/12871437/555e9abe-cdcf-11e5-9845-91492d9f854a.png">
<img width="1427" alt="screen shot 2016-02-07 at 7 16 27 pm" src="https://cloud.githubusercontent.com/assets/6110952/12871438/55600d68-cdcf-11e5-821f-f3103ea399d3.png">

**Comment by rob-blasetti** [comment]
The height difference occurs when there are only pinned tabs in the browser.

**Comment by psimyn** [comment]
fixed the height issue for when there are no tabs. Button on the right is still an issue, can reopen https://github.com/brave/browser-laptop/issues/621 or I will have a look with this

**Comment by psimyn** [comment]
added New Tab button fix as well
