### ISSUE TITLE
Bookmark side bar resizes when navigating across subfolders

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6470]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Bookmark side bar resizes when navigating across subfolders

**Expected behavior:**
Should not resize when navigating across subfolders

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows x64

- Brave Version (revision SHA):
```
 Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Create a well nested bookmarks folder
    2. Click on different subfolders
    3. On each click of a subfolder, bookmarks side bar keeps resizing

- Screenshot if needed:
![bookmark2](https://cloud.githubusercontent.com/assets/17010094/21567341/6a6db842-cea3-11e6-966b-385debf228fa.gif)

- Any related issues:

**Comment by MargarytaChepiga** [comment]
Isn't it an expected behavior? As I understand from the code, it seems like it was wanted to behave that way.

**Comment by srirambv** [comment]
From UI perspective it shouldn't move around as you select different folders. 

cc: @bradleyrichter

**Comment by MargarytaChepiga** [comment]
I can make it static, so it can be something like this:
![bookmark_static](https://user-images.githubusercontent.com/15698572/37113567-b35c9b08-2213-11e8-8344-14b10324098e.gif)

**Comment by MargarytaChepiga** [comment]
However, in the above situation, we need to take care of edge cases like the following:
![bookmark_static_edge_case](https://user-images.githubusercontent.com/15698572/37114573-c8a82f4c-2216-11e8-98ac-4b9472c3907e.gif)

**Comment by srirambv** [comment]
@MargarytaChepiga the static version looks good but will wait for @bradleyrichter to take the call. 

I think the edge case is still fine as it would only happens for extremely long names.

**Comment by bradleyrichter** [comment]
nice improvement. thanks!
