### ISSUE TITLE
Recover Wallet modal should close after successfully recovery

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6471]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Recover Wallet modal is still shown after successfully recovered

**Expected behavior:**
Recover Wallet modal should close and go back to advanced settings modal after successfully recovery, should retain the modal only if recovery fails

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Enter recovery keys in the recover wallet modal
    2. Click on the ok button after the success message is shown
    3. Recover wallet modal is still shown

- Screenshot if needed:
![recoverwallet](https://cloud.githubusercontent.com/assets/17010094/21568193/65c7720e-ceaa-11e6-913f-9e25ebbc0662.gif)

- Any related issues:
cc: @mrose17

**Comment by mrose17** [comment]
this is by design: recovering a wallet empties the old wallet and puts the coin into your new one, which you should STILL backup.

**Comment by bsclifton** [comment]
So leaving the screen up is intentional? kind of feels weird to me
cc: @bradleyrichter
