### ISSUE TITLE
URL suggestion drop down is bigger than the URL bar itself 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6472]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
URL suggestion drop down is bigger than the URL bar itself 

**Expected behavior:**
Should be the size of the URL bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Start typing for the autosuggestion drop down to appear
    2. Suggestion dropdown is not the same size as URL bar
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21568342/9def2bbc-ceab-11e6-9303-836d76010d16.png)

- Any related issues:
cc: @bbondy

**Comment by srirambv** [comment]
Even the back/forward dropdown is big 
![image](https://cloud.githubusercontent.com/assets/17010094/21568544/6f8c3092-cead-11e6-929f-b465c9ab910b.png)
![image](https://cloud.githubusercontent.com/assets/17010094/21568553/7e5a7aac-cead-11e6-84ef-42d59a49a2b3.png)

**Comment by bbondy** [comment]
@srirambv can you confirm if this was a problem in 0.12.15 as well?

**Comment by srirambv** [comment]
This doesnt happen on 0.12.15. Here's how it looks on 0.12.15
![image](https://cloud.githubusercontent.com/assets/17010094/21572916/cb9611b8-ced6-11e6-8506-a39211f3fc33.png)

The back/forward dropdown looks pretty same but it looks odd because of the magnified look on 0.13.0
![image](https://cloud.githubusercontent.com/assets/17010094/21572935/034b6112-ced7-11e6-9cb7-c365eab70968.png)
![image](https://cloud.githubusercontent.com/assets/17010094/21572941/0b7f5f28-ced7-11e6-9f3f-161dbb17986d.png)

**Comment by bsclifton** [comment]
@cezaraugusto would you be able to help me check this out for 0.13.0?

**Comment by bsclifton** [comment]
Seems to also happen on macOS

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/issues/6485
