### ISSUE TITLE
"set homepage" text box forces text to last character

### ISSUE THREAD

**Issue by S1kBruZZ** [brave/browser-laptop#648]
After typing one character in the "set homepage" text box, typing gets forced to the last character in that box
Video example, https://gfycat.com/OptimisticNegativeEagle

**Comment by bbondy** [comment]
Noticed this too, didn't have time to post/fix though. Thanks for posting!

**Comment by psimyn** [comment]
Apparently ongoing issue for inputs - https://github.com/facebook/react/issues/955

Could store cursor position in state, or only trigger update once typing stops (on timeout/blur/close)

**Comment by bbondy** [comment]
This will just go away due to async nature of flux if we change the about preferences page rendering to use mini flux store.  Or just get rid of all setState.

**Comment by bbondy** [comment]
Did this a while ago, it's working properly now.
