### ISSUE TITLE
Close other tab causes crash

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6480]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Close other tab causes crash

**Expected behavior:**
Should close the tabs and not crash

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Have multiple tabs open
    2. Right click on a tab and select close other tabs, browser crashes

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21574840/66d0c676-cef2-11e6-94d9-2cf93fd2b4e9.png)
  ![crash](https://cloud.githubusercontent.com/assets/17010094/21574872/23972e4e-cef3-11e6-98db-9b689beeb424.gif)

- Any related issues:
#5946 cc: @bridiver @bbondy

**Comment by bridiver** [comment]
I can't replicate this. Can you provide more detailed steps to repro starting from a fresh profile?

**Comment by Liunkae** [comment]
Reoccurrence of #5946?

**Comment by srirambv** [comment]
@bridiver  I am not able to reproduce this on the same profile and new profile. @Liunkae  It looks like the same issue as #5946 but I cannot consistently reproduce it. Closing the issue. Will reopen if I am able to reproduce it consistently.

**Comment by srirambv** [comment]
Closing #6480
