### ISSUE TITLE
Building Brave on Windows causes generic Electron window to appear

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6481]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When you npm run watch && npm start on Windows it starts Brave but also opens the generic Electron window (screenshot below).

**Expected behavior:**
It should start Brave and not show the Electron window.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10

- Brave Version (revision SHA):
master

- Steps to reproduce:
    1. Build Brave on Windows
    2. npm run watch-all && npm start
    3. notice two windows open, Brave and Electron.

- Screenshot if needed:
![capture](https://cloud.githubusercontent.com/assets/490294/21574878/314610e8-ceb0-11e6-8fab-cb918fe8433f.PNG)

- Any related issues:

**Comment by bsclifton** [comment]
This appears to be fixed as of https://github.com/brave/muon/commit/30fd6ff5ac772cb645b0d4be78fae49d84fbbb19

**Comment by bsclifton** [comment]
Closing this for now; I got latest in browser-laptop-bootstrap and it's no longer happening

**Comment by luixxiul** [comment]
Please remove the milestone and add labels `QA/no qa needed` and `release-note/exclude` if this appeared and was fixed within the same milestone, thanks!

**Comment by bsclifton** [comment]
@luixxiul labels updated; keeping milestone for tracking purposes

**Comment by bsclifton** [comment]
Per @darkdh, this should have been fixed by https://github.com/brave/muon/commit/99dff2869cade76dbbec4aee51c5b68038a5622c :smile:

**Comment by luixxiul** [comment]
Sweet!
