### ISSUE TITLE
Ctrl+Mouse Wheel up/down doesnt zoom in/out 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6482]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Ctrl+Mouse Wheel up/down doesnt zoom in/out 

**Expected behavior:**
Should zoom in/out accordingly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
``` 
Brave: 0.13.0 
rev: 0c7a64d6917b6e7e72d074b05e1d7488466418a9 
Muon: 2.0.8 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:
    1. Open any site or about pages
    2. Hold the control key and mouse wheel up/down
    3. Doesn't zoom in/out

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Test plan:

Open any site or about pages
Hold the control key and mouse wheel up/down
It should zoom in/out the page
