### ISSUE TITLE
Wrong tooltip text on first hover

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#6489]
Getting the wrong tooltip text on first hover. Is corrected when I point away and then hover again.

I had noticed this for quite some time but couldn't see a reliable way of reproducing the bug until just now. The exact tooltip text itself seems significant so reproduce using the "Star" and "Fork" buttons at the top of this issue.

Hover over the "Fork" button until the tip text appears.Then (avoiding triggering any other tooltips along the way) hover over the "Star" button which will show the incorrect tooltip "Fork your own copy of brav" [sic]. Hover away and back to the "Star" button and you'll see the correct tooltip text "Star brave/browser-laptop".

At first glance, it looks like the tooltip speech bubble is being correctly sized for the expected tooltip text but the displayed text itself isn't being updated until the second hover. Several things are confusing me:

1. Why does this only seems to happen with some rather than all tooltips?
2. Why does the tooltip text influence the presence/absence of this bug?
3. Why does a second hover fix it?

Name:	Version
Brave:	0.12.15
Muon:	1.4.31
libchromiumcontent:	53.0.2785.143
V8:	5.3.332.47
Node.js:	6.5.0
Update Channel:	dev
os.platform:	linux
os.release:	4.8.0-32-generic
os.arch:	x64
Ubuntu: 16.10

**Comment by Liunkae** [comment]
I wonder if this is similar to the problem we had with tooltips on Ubuntu a while back (https://github.com/brave/browser-laptop/issues/1848#issuecomment-222416109).

**Comment by CliqueBait** [comment]
@Liunkae Yes. It seems to be the same bug. I hadn't noticed that it also affects the bookmark bar but can confirm that I can reproduce that part of the bug too.
