### ISSUE TITLE
New tabs say "about:blank" until loaded (window.opener issue in renderer)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6495]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening anything in a new tab (middle click on links, etc) shows "about:blank" for about two seconds until the page loads and then finally updates to what it should be.

**Expected behavior:**
The tab should set the title to the URL being opened (until the title is loaded). This would be consistent with other browsers.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.0 preview 7

- Steps to reproduce:
    1. Go to Brave.com
    2. Middle click or cmd+click on "faster" at the top
    3. Notice that it says "about:blank" until loaded in the new tab
    4. Close new tab go back to Brave.com
    5. Right click "faster" and pick "Open in new tab"
    6. Notice it works as expected; defaults to title as URL, then loads title when page loaded

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@bridiver is this one you can check out? I know these codepaths were all ones that were recently updated

**Comment by bbondy** [comment]
@bsclifton is this present in 0.12.15 as well?

**Comment by luixxiul** [comment]
@bsclifton do you think this is related or similar in some way with #6453?

**Comment by bbondy** [comment]
@bsclifton could you confirm what I see?
- In both .12.15 and .13 they load in the same amount of time
- In .12.15 it used to show the url of the page first
- In .13 it shows about:blank instead of the URL of the page first.

**Comment by diracdeltas** [comment]
On OS X 0.13, I only see this bug if I cmd-click to open in a new tab. If I right click to open in a new tab from the context menu, it doesn't seem to happen

**Comment by bsclifton** [comment]
@bbondy that is 100% correct; I tested again right now to verify behavior

The 0.13 build can "feel" longer, but it's roughly the same.  Like @diracdeltas mentions, it only happens with cmd+click (or in my case, middle click)

**Comment by bsclifton** [comment]
@luixxiul yes- I think that may be related.  Do you actually see a time difference? or does it just appear to be laggy (because you don't see any result until page is loaded)?

**Comment by bbondy** [comment]
this seems to be the same as what Chrome does but in the new tab Chrome displays untitled instead of about:blank, how does that sound as a fix here?

**Comment by diracdeltas** [comment]
+1 for 'untitled' as the provisional title.

**Comment by bsclifton** [comment]
also +1 for untitled :smile:

**Comment by bridiver** [comment]
this will happen for all renderer initiated navigations and that includes cmd-click. It happens because the renderer controls the actual navigation to the url and that doesn't happen until the webview is attached and we allow the webcontents to resume loading. In the past we displayed the `delayedLoadUrl`, but I believe @diracdeltas removed that because of a spoofing vulnerability
