### ISSUE TITLE
How to change the name and run successful build

### ISSUE THREAD

**Issue by mmilkov** [brave/browser-laptop#6496]
Hello guys. I am just experimenting with Brave to see how it works and I am just curious how can I change the name from Brave to something different? What files need to be edited? I changed buildPackage.js and buildInstaller.js but without success. When I change the name in buildPackage it's make the files again in 'Brave-platform-arch' folder and the output is that it can not find some files.. I think that braveDefaults file need to be changed too but somewhere I am missing something.. Thanks

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version:
0.12.5

**Comment by bsclifton** [comment]
@mmilkov are you just wanting to rename the executable? or you want to rebrand the entire thing?

**Comment by bbondy** [comment]
It's definitely possible and you're allowed if you `git grep` around enough, possibly also inside `brave/muon`. But this is not something we provide support for.  As it stands now there isn't a centralized setting for changing the name.

 Feel free to upstream though if you make things easier to change the name for and you'd like to limit the number of things you need to rebase.

**Comment by mmilkov** [comment]
@bsclifton yes, I want to rebrand it. But I want only to edit the  really necessary files like buildPackage.js, nsi file..

**Comment by bsclifton** [comment]
@mmilkov ah ok.  If you wanted to compile a list of places where "Brave" appears and then make an issue to make the product name configurable (including your findings), I think that would be reasonable :smile:

**Comment by mmilkov** [comment]
@bsclifton Okay, I am trying to do it, but without success.. I am just editing the buildPackage.js and change every "Brave" to "Brav" but when I run "npm run build-package" I got:
```
Packaging app for platform win32 x64 using electron v1.4.31
Fatal error: Unable to load file
 undefined
done
```

Can I have a little help? Thanks :)

**Comment by bsclifton** [comment]
@mmilkov if you choose to not change anything, does that happy-path work?  There are a few steps on our wiki that you'll need to follow to get it working
https://github.com/brave/browser-laptop/wiki/Packaging-for-bundles,-installers,-and-updates

**Comment by mmilkov** [comment]
@bsclifton yes without changing them is working like a charm :) Can you try it? Thanks

**Comment by bsclifton** [comment]
@mmilkov I haven't had time recently to look, but I would encourage you to make a new issue called "Make Brave re-brandable" and then put your findings (as you make them) there :smile: I've been busy with our current release and likely won't have time to help look at this until a later time

**Comment by mmilkov** [comment]
@bsclifton Thanks. New issue is here https://github.com/brave/browser-laptop/issues/6565 :)))

**Comment by mmilkov** [comment]
@bsclifton Actually nobody comes in the new issue. I want to ask few things..

Actually, when I change the name from 'Brave' to 'Brav' and delete this lines:
`cmds = cmds.concat([
  //'"./node_modules/.bin/webpack"',
  // 'npm run checks',
  'node ./node_modules/electron-packager/cli.js . Brav' +
    ' --overwrite' +
    ' --ignore="' + ignoredPaths.join('|') + '"' +
    ' --platform=win32' +
    ' --arch=x64' +
    ' --version=' + VersionInfo.electronVersion +
    // ' --icon=./res/app.ico' 
    ' --asar=true' +
    // ' --app-version=' + VersionInfo.braveVersion +
    // ' --build-version=' + VersionInfo.electronVersion 
    ' --protocol="http" --protocol-name="HTTP Handler"' +
    ' --protocol="https" --protocol-name="HTTPS Handler"' 
    // ' --version-string.CompanyName="Vica Inc."' +
    // ' --version-string.ProductName="Vica"' +
    // ' --version-string.FileDescription="Vica"'
])`
is working, but why is generating again 'brave.exe' not 'brav.exe'? When I uncomment some of this lines it throws me:
`Fatal error: Unable to load file
 undefined`

Can you help me with this? I want to change the icon on .exe file and task-bar icon..

One other issue is when I am running it in Task Manager, I am getting 'Electron'.. How can I make it 'Brav'?

Thank you :)
