### ISSUE TITLE
Enhance Privat tabs

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#650]
Any chance that you can enhance private tabs which have been opened that when you restart the browser they are also opened again?

**Comment by bradleyrichter** [comment]
I defer to @diracdeltas for comment, as our resident privacy expert. But if this is the standard approach, perhaps we could at least ad a preference in Tabs prefs.

**Comment by bbondy** [comment]
No sorry this is working as per design.  Private tabs do not store any storage and being able to restore private tabs would require some storage.  Even if we encrypted the storage it would be a surprise for most use cases.  Consider using a session tab if you'd like a separate session with persistence though.
