### ISSUE TITLE
Cannot select text from this textbook

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#6501]
I cannot select text from this textbook so that I can copy and paste text into some Anki cards.
http://cscp.cambridge.org/4eINT/book1/?p=6
(This works for Chromium Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.10 (64-bit).)

This appears to be a problem specifically with mouse selecting text since I'm able to search the textbook page (with incremental highlighting) for words using Ctrl-F as expected.

Brave	0.12.15
Muon	1.4.31
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-32-generic
os.arch	x64

**Comment by NejcZdovc** [comment]
Text selection is not working on Chrome 55.0.2883.95 (64-bit) on MacOS 10.12.2

**Comment by bsclifton** [comment]
confirmed it's still an issue in 0.14.0

**Comment by luixxiul** [comment]
`user-select: none` is set on the page globally.
