### ISSUE TITLE
the browser cannot be relaunched on Windows 7

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6504]
**Did you search for similar issues before submitting this one?** Yes, sorry if this is duping though.

**Describe the issue you encountered:**
There are several reports that the browse cannot be relaunched on Windows 7.

https://community.brave.com/t/brave-wont-open-after-december-15-windows-7-update/418
https://community.brave.com/t/browser-window-disappears-at-launch-after-latest-update/118
https://community.brave.com/t/does-not-launch/430
https://community.brave.com/t/crashes-and-needs-uninstall-reinstall-regularly/349
https://community.brave.com/t/closed-brave-starts-then-stops-on-startup/680

The common thing among them is that the browser does launch at first but it does not after closing it once.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

- Brave Version (revision SHA): 0.12.15

- Steps to reproduce:
    1. Open the browser
    2. Close it
    3. Reopen the browser
    Then the browser window appears and is closed instantly

- Any related issues:

**Comment by luixxiul** [comment]
There are several reports too in #6465

**Comment by darkdh** [comment]
I just verified both 0.13.0 preview 8 and master can successfully relaunch Brave on win 7

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.

**Comment by luixxiul** [comment]
Since I do not have Windows 7 32 bit, I cannot check if this has been fixed on that OS

**Comment by bsclifton** [comment]
I believe this problem was fixed with https://github.com/brave/browser-laptop/commit/40dffe869234d9b71fba47d3ddf2adadc6df33a4

**Comment by emackey** [comment]
That commit suggests this problem only affects machines where Flash is not installed.  I can confirm that Brave 0.13.0dev-RC5 is able to install, quit, and re-launch successfully on a Win7 x64 box without Flash.  It took a lot of searching for me to find this thread though, after experiencing the bug.  I would guess that a lot of Brave early-adopters would be the kind of people to not have Flash installed, and this bug kills the whole browser, likely including its ability to auto-update.

**Comment by luixxiul** [comment]
CC @diracdeltas @bbondy for confirming the issue

**Comment by srirambv** [comment]
To add it to record, if flash isn't installed on a x64 device, the browser startup time is very slow after install. Had mentioned this in slack conversation as well.
