### ISSUE TITLE
URL Text is low compared to other URL bar items

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6505]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
URL Text is low compared to other URL bar items

**Expected behavior:**
All URL bar/titlebar elements should be properly aligned

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d

- Steps to reproduce:
    1. Enter URL in the URL bar
    2. Entered URL is much lower aligned than connection state icon
    3. Some char looks like they are getting clipped

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21593370/2176b1b2-d10e-11e6-9203-d7aeb520ab8b.png)

- Any related issues:
#6097 #2979

  cc: @bradleyrichter

**Comment by luixxiul** [comment]
please make sure this is the same in 0.12.15

**Comment by srirambv** [comment]
@luixxiul Its pretty much same on 0.12.15 but the characters looks clipped on Windows in 0.13.0 build. This is how 0.12.15 is on windows 
![image](https://cloud.githubusercontent.com/assets/17010094/21606999/266c6246-d1ab-11e6-83ad-d376c64c1890.png)

**Comment by bradleyrichter** [comment]
windows is low. here is mac with 0.13.0 p7

![image](https://cloud.githubusercontent.com/assets/13509546/21624060/302a2c8c-d1ba-11e6-884f-5842440a5176.png)

**Comment by luixxiul** [comment]
@srirambv I'm away from Windows so I cannot confirm but it seems that the font-family applied to the area is different between 0.12.15 and 0.13.0.

**Comment by luixxiul** [comment]
`s` and `g` seem to be curved a little bit

**Comment by srirambv** [comment]
It looks bad now that the font looks more crisp than before.
![image](https://cloud.githubusercontent.com/assets/17010094/22506251/59c2aa0a-e877-11e6-8e5d-be1c53634130.png)

Although the text doesnt seem to be clipped but it visibaly clear that the text is low compared to other buttons
![image](https://cloud.githubusercontent.com/assets/17010094/22506314/a73f05f8-e877-11e6-9278-a203968aae6c.png)

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/5624#issuecomment-274317788

**Comment by luixxiul** [comment]
Closing this in favor of https://github.com/brave/browser-laptop/issues/5624#issuecomment-274317788
