### ISSUE TITLE
Spell check is not working for C54

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6507]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Spell check isn't working

**Expected behavior:**
Spell check should work

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
master tip:
https://github.com/brave/browser-laptop/commit/c2fa12f1e6ad32d7af9fc9b7f95e59e166be7a04

- Steps to reproduce:
    1. Go to https://github.com/fdafadsfdsafdsa
    2. Type a bunch of characters randomly into the input box
 
- Actual results:  No underline happens
- Expected results: underline happens

**Comment by bbondy** [comment]
This seems to be ICU related, everything seems to be working correctly except for the word iterator doesn't find any words even know there is text.    This can probably be closed when ICU is fixed.

**Comment by bbondy** [comment]
This seems to now work still even know ICU is fixed.

**Comment by bbondy** [comment]
Edited typo above, I meant to say this was not related to ICU at all, it turned out to just be a problem with our handling due to enumeration value for a word token because 0 which breaks out of the while loop and doesn't check any words. 

The fix will be available in Preview9. For testing you just need to make sure spell check works now the same as it did in 0.12.15.

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.
