### ISSUE TITLE
Session tab/private tab icon and text is too spaced out

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6511]
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Session tab/private tab icon and text is too spaced out

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d

- Screenshot if needed:
0.13.0 vs 0.12.15
![image](https://cloud.githubusercontent.com/assets/17010094/21611669/b8f760d8-d1c5-11e6-8e47-9bff255e6160.png)

- Any related issues: #5936

**Comment by luixxiul** [comment]
This should be fixed after #5918 is merged /cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
yes all content inside tab was changed there, also dynamic items such as private and play icons are now displayed on right position instead of left.

**Comment by bsclifton** [comment]
@cezaraugusto can you rebase your commit and also reference this one as one that'll be fixed using auto-closing keywords? :smile:
