### ISSUE TITLE
Opening bookmarked items in session tab doesn't show the orange star in URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6512]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Opening bookmarked items in session tab doesn't show the orange star in URL allowing to add it as a duplicate bookmark which could lead to #6510

**Expected behavior:**
Should show the orange star in URL bar when a bookmarked item is opened in session tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.12.15/0.13.0 (Mostly all previous releases)

- Steps to reproduce:
    1. Visit https://www.brave.com, bookmark the page
    2. Open new private tab, click on the bookmarked item, opens page and shows orange star in URL bar
    3. Open new session tab, click on the bookmark item, doesn't show the orange star in URL bar, allows you to add the page as bookmark allowing to duplicate the bookmark (#6510)

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
bookmarks are considered different if they exist in different sessions.  So for example you could create a bookmark when logged in with twitter user A and twitter user B and they would lead to each version of the page.  So this is by design.
