### ISSUE TITLE
About pages favicon changes when popup tabs is closed before loading

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6513]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
About pages favicon changes when popup tabs is closed before loading

**Expected behavior:**
Should not change the favicon of about pages irrespective of when the popup tabs are closed 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Have not seen this issue on 0.12.15, seen only on 
Brave	0.13.0
rev	0c7a64d

- Steps to reproduce:
    1. Keep any of the about pages open and in a new tab open a webpage which triggers popup tabs
    2. Click on page to trigger popup tab
    3. Close the tab immediately before the popup tab content loads
    4. Repeat step 2-3 three to four time s
    5. About page favicon changes from Brave logo to one of the sites which was supposed to open in the popup tabs
    6. Screenshot 1 shows the effect of closing pocket login page being closed before loading after enabling the extension

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/21617830/ec0c04a0-d1df-11e6-8441-fdc7f8abfa4e.png)
![image](https://cloud.githubusercontent.com/assets/17010094/21617861/0d6a4814-d1e0-11e6-9b3f-6cd9b1aba1be.png)
![image](https://cloud.githubusercontent.com/assets/17010094/21617866/14f20540-d1e0-11e6-9dbc-8ebd45564bd0.png)

- Any related issues:
Please change milestone if required

**Comment by bbondy** [comment]
I'll take this one, the problem is we get the event in the webview before a frame is actually created, so it puts the icon on the first frame.  The fix would be to manage the data in TabHelper and handle fro the browser process.

**Comment by bbondy** [comment]
Actually that's not needed yet, it is just because it is closed so the frame is removed.  Strange we even get that event.

**Comment by bbondy** [comment]
Test plan: Follow the steps to reproduce in comment 0.

**Comment by srirambv** [comment]
This is still happening on 0.13.0 RC1 
![image](https://cloud.githubusercontent.com/assets/17010094/22148440/00d262ca-df06-11e6-8dd4-b0b4f00f75c3.png)

**Comment by srirambv** [comment]
This is not a release blocker can be moved to 0.13.1 or 0.13.2 if required

**Comment by bbondy** [comment]
strange it was definitely working at some point, moved to 0.13.1

**Comment by bbondy** [comment]
it's much reduced from what it used to be, I could reproduce 1 in 4 times before, now only happens once in maybe 30 times for me.

**Comment by srirambv** [comment]
Still seeing this issue after a while on 0.17.6 on Debian 
![image](https://user-images.githubusercontent.com/17010094/27444323-e2c5a68a-576d-11e7-840f-184d93706a7b.png)

**Comment by kjozwiak** [comment]
I noticed this happen when going through the YT feature for `hotfix5`... Noticed that YT was using the BAT icon.... After I refreshed the page, the normal expected YT icon was displayed... Example:

<img width="371" alt="screen shot 2017-11-15 at 3 48 35 pm" src="https://user-images.githubusercontent.com/2602313/32859687-326d6138-ca1d-11e7-90e7-8dac81e6bb4c.png">

Using v0.19.93 rev: 25085d0b5a0a6cf8a740cac8b246ebf1a97146f7 via Ubuntu 16.04.3 LTS x64.
