### ISSUE TITLE
New plugins / extensions (Boomerang and Scrum for Trello)

### ISSUE THREAD

**Issue by newmanea** [brave/browser-laptop#6514]
Can you add support for Boomerang for Gmail and Scrum for Trello? I did not see those extensions added in the "project" for new extensions to support.

Thanks!

**Comment by bsclifton** [comment]
`Boomerage for Gmail` is now in there and I just added `Scrum for Trello` 😄 👍 
https://github.com/brave/browser-laptop/projects/1

cc: @jonathansampson
