### ISSUE TITLE
What about a french version?

### ISSUE THREAD

**Issue by tleger1958** [brave/browser-laptop#6516]
Hello everyone.

I don't know if the "Issues" category is appropriate, but I would like to share with you a project idea.

Would it be possible to make a French version of Brave? How could this happen in the organization of the code?

I am very motivated to translate, and I think some other people can also be. I can already translate the description.

As for the code, is it necessary to create a subfolder "fr" and put in all the code but modified so that the display is in French, or should we manage the language in the already existing files?

Thanks for reading me.

**Comment by srirambv** [comment]
Does this help. Change browser language to French 
![image](https://cloud.githubusercontent.com/assets/17010094/21623571/ea1b839e-d1fa-11e6-90aa-8d334f27144d.png)
You can contribute any missing translations [here](https://www.transifex.com/brave/brave-laptop/)

**Comment by tleger1958** [comment]
I want to commit suicide. Why I did not **even** look into the settings?! Anyway, I'm glad to see that there are many languages available, and at least, I have learned how to contribute for translations.

An awkward clumsiness on my part!

**Comment by bsclifton** [comment]
@tleger1958 no worries :smile: Super glad you found it

If you notice any issues with the French translations or would like to be involved with them, please check out our documentation on how to get setup with Transifex (which @srirambv linked you to above)
https://github.com/brave/browser-laptop/blob/master/docs/translations.md

I'll go ahead and close this issue out, but please let us know if you have any questions :smile:
