### ISSUE TITLE
Pinned tabs cause an extra empty tab grouping to open.

### ISSUE THREAD

**Issue by Sweetie-Belle** [brave/browser-laptop#652]
I have five pinned tabs, and two un-pinned tabs open.

Although the un-pinned tabs both fit into the first tab grouping (the pills above the tabs), I have a second tab grouping which only shows the pinned tabs.

**Comment by bradleyrichter** [comment]
@Sweetie-Belle Thanks for this suggestion. #651 should fix this... @bbondy  keeping open until fixed.

**Comment by Sweetie-Belle** [comment]
@bradleyrichter Looks like that build failed.

**Comment by bbondy** [comment]
#651 isn't related, it only happens when there are 0 non-pinned tabs opened. 
Although this fix should have did it:
https://github.com/brave/browser-laptop/commit/f8d9d56f6ffef6ea32599fa195ae3967275db302
Are you using 0.7.13?

**Comment by Sweetie-Belle** [comment]
@bbondy Have upgraded to 0.7.13 and can confirm this is now resolved.

**Comment by bbondy** [comment]
Great, thanks for checking!
