### ISSUE TITLE
Chromedriver is not starting on Windows for automation

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6520]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While attempting to run automation on my Windows VM, the tests all failed with a consistent issue:
"Error: ChromeDriver did not start within 5000ms"

**Expected behavior:**
ChromeDriver should start and the tests should run appropriately.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 x64

- Brave Version (revision SHA):
commit 113598fe9f8df94ce26d469d6429bf03e176abde

- Steps to reproduce:
    1. On a Windows machine, pull the latest version of browser-laptop
    2. Attempt to run a mocha test (ex: mocha --require babel-register --require babel-polyfill 'test/**/*Test.js' --grep=bookmarks )
    3. Observe the output

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
@jonathansampson I have some fixes for the test config ready to push out but I'm waiting on a new chromedriver ICU config which BrianJ is working on, we aren't getting builds for chromedriver yet for the new code.

**Comment by luixxiul** [comment]
@bbondy Do we need QA for this?
