### ISSUE TITLE
WhatsApp Web doesn't work on 0.13.0 build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6522]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
WhatsApp Web doesn't work on 0.13.0 build

**Expected behavior:**
User should be able to scan QR code and open whatsapp web

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d
Verified on 0.12.15 works fine

- Steps to reproduce:
    1. Visit https://web.whatsapp.com
    2. Page breaks immediately after showing the QR code 
    3. Same issue with shields down

- Screenshot if needed:
![whatsappweb](https://cloud.githubusercontent.com/assets/17010094/21650966/a8819d16-d29e-11e6-8be8-29e7f88c043a.gif)

- Any related issues:

  Marking as impact/high, please change if required

**Comment by darkdh** [comment]
I found out if we add `--no-sandbox` to arguments, renderer won't crash anymore
<img width="1439" alt="screen shot 2017-01-09 at 17 23 29" src="https://cloud.githubusercontent.com/assets/11330831/21761798/657d9718-d690-11e6-982d-87132286ab15.png">

**Comment by luixxiul** [comment]
I added `release-notes/exclude` as the issue appeared and was fixed within the same milestone.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
