### ISSUE TITLE
some certificate fingerprints cause decoding error

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#6524]
reported by eric lawrence:
![image uploaded from ios](https://cloud.githubusercontent.com/assets/549654/21656481/31fcded6-d2b6-11e6-8b1a-a741861a3c36.jpg)

**Comment by bsclifton** [comment]
@diracdeltas is this fixed by https://github.com/brave/browser-laptop/pull/6525?

**Comment by diracdeltas** [comment]
i'm not 100% sure due to lack of the test certificate, but we can close this and reopen if not.

**Comment by bsclifton** [comment]
Closing; if not fixed by https://github.com/brave/browser-laptop/pull/6525, let's re-open :smile:

**Comment by bsclifton** [comment]
was gonna add the new `QA/required` tag but you beat me to it, @luixxiul :smile:

**Comment by bbondy** [comment]
Test failed on macOS, I posed a follow up here:
https://github.com/brave/browser-laptop/issues/7042

@diracdeltas could you take a look?
