### ISSUE TITLE
Flash control is not displaying for VMware vSphere web client

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6526]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
A user from support has reported that despite allowing flash in preferences, they are not shown the control in the vSphere web client. 

**Expected behavior:**
The control should be readily accessible. 

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by stephenl03** [comment]
I see this was closed, but the issue still persists.

**Comment by bsclifton** [comment]
@stefankolb this is not something we'll be fixing with the current version of Brave unfortunately. You can try our new developer channel release out if you'd like (this issue may be fixed there):
https://brave.com/download-dev
