### ISSUE TITLE
Split PaymentsTab into its own component

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6528]
This relates to both https://github.com/brave/browser-laptop/issues/3717 and https://github.com/brave/browser-laptop/issues/5887. In order to unit test the changes mentioned in https://github.com/brave/browser-laptop/issues/5887 it's easiest to split it out into its own component.

**Comment by luixxiul** [comment]
Several duplicate declaration errors start appearing

**Comment by bsclifton** [comment]
@luixxiul my bad- reverted with https://github.com/brave/browser-laptop/commit/7031a2b348f2e372a905a031f3a0311b48247ac8

**Comment by bsclifton** [comment]
This was fixed after we resolved manual merge issues

See 
revert of many 0.13.1 branch changes - https://github.com/brave/browser-laptop/commit/4de7cf4d6c15cf378ac58b98b3062abb4485eb5f
proper merge of all 0.13.1 changes - https://github.com/brave/browser-laptop/commit/af368d3caaf5038bcd33252b72a3ad023dd72280
fix for this issue specifically - https://github.com/brave/browser-laptop/commit/ad2cd843a739ccf98f126b39c96711b43d2bdd33
