### ISSUE TITLE
Add extensions panel to About:Preferences

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6530]
## Test plan
See https://github.com/brave/browser-laptop/pull/8065

## Original issue description
To increase awareness of Brave's extension support, and to funnel new extension requests, a new prefs panel will be created.

features:
- all brave extensions will appear in a sortable list, sorted alphabetically by default
- each extension can be enabled/disabled with a switch at the right side
(this should toggle the presence of the extension in the point of integration)
- if an extension is available but not installed by default, the switch begins as an "install" button
- a rt-click menu is available to uninstall any extension that was once manually installed
- a notification bar is triggered when new extensions become available to alert the user of the good news (this alert may be disabled)
- a link is positioned at the bottom of the page to invite users to submit extension requests through the community portal

notes: 
- this panel is for extensions only and will not display plugins such as Flash or Widevine
- after implementation, we will add a menu item to point users to this panel
(Window>Extensions Manager...)

![pasted image at 2017_02_27 04_21 pm](https://cloud.githubusercontent.com/assets/4672033/23386095/4006dde0-fd33-11e6-9ed2-0b5ed9e94127.png)

**Comment by willy-b** [comment]
Any possibility to control other extension permissions in this or future mockups?

In Google Chrome, incognito mode / file URL permissions controls are exposed in their panel:
![extensionsoptionsingooglechrome](https://cloud.githubusercontent.com/assets/6969859/21667137/52c46acc-d2ab-11e6-9360-7d7e8f1bfd5a.png)

(you might do it in your popup menu or elsewhere, but the functionality is useful)

**Comment by bradleyrichter** [comment]
Context menu should work as weare able/need to add this type of functionality. In the future, this will change based on the ability to open the extension API.

**Comment by bsclifton** [comment]
Pulling into 0.14.1

**Comment by bsclifton** [comment]
Per discussion with @bbondy, let's
- not show the version if it's not installed (worst case scenario, we we can display "latest")
- not handle the extension updates.  I created https://github.com/brave/browser-laptop/issues/7822 to track this

**Comment by NejcZdovc** [comment]
We also need to add on this panel enable in private/session tab, same as Chrome has it "Allow in incognito"

<img width="771" alt="screen shot 2017-03-22 at 07 38 22" src="https://cloud.githubusercontent.com/assets/9574457/24185275/97849192-0ed2-11e7-8b32-325c9db26549.png">

**Comment by luixxiul** [comment]
How could I reload PDF reader which I accidentally removed?
