### ISSUE TITLE
Extension manifest may lack permissions

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6533]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Extension manifest.json files may lack a permissions property. It is not a required property. Our current handling expects this property to exist, and intends to call `Array.prototype.join` against it. In its absense, the entire _about:extensions_ page falls apart.

**Expected behavior:**
We should be ready to encounter an extension whose manifest.json lacks permissions.

**Brave Version (revision SHA):** 0.13.0

**Relevant Source:** https://github.com/brave/browser-laptop/blob/master/js/about/extensions.js#L49

**Comment by jonathansampson** [comment]
@bridiver Thoughts on this? Should I just wrap it, _a la_ `( … || [] ).join`, or should we ensure registered/loaded extensions always have a `permissions` property, if even an empty array?

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6581 which was merged into branch `0.13.1-branch`.
