### ISSUE TITLE
Selected text in text fields is missing Look Up in context menu (macOS-only)

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6536]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
When right-clicking selected text in a text field on macOS, the Look Up option (dictionary definition) is not shown. 

**Expected behavior:**
The Look Up option should be shown for selected text, as it is with normal text.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.12.15

- Steps to reproduce:
    1. Open a new Brave tab and navigate to any site with a text field.
    2. Activate the text field and type some text.
    3. Select the text.
    4. Right-click.
    5. Notice that there is no Look Up option.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/21670486/1897f416-d2da-11e6-969e-d1e3256b7dbb.png)

- Any related issues:
None.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6545 which was merged into branch `0.13.1-branch`.

**Comment by bbondy** [comment]
This isn't working consistently for me, I posted a follow up for it here:
https://github.com/brave/browser-laptop/issues/7043
