### ISSUE TITLE
URL autocomplete should offer the option of only completing the hostname

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6537]
**Describe the issue you encountered:**

https://community.brave.com/t/url-autocomplete-from-history-should-offer-the-option-of-only-completing-the-hostname/548?u=suguru

> If I wanted to visit example.com's front page, I begin typing "exam" and get the following auto-complete behavior (the space and italics demonstrate what Brave tries to auto-complete):
>
> http://exam ple.com/long/path/to/some/random/subpage/from/my/history.aspx?id=1234567890asvbhdhjfhalkkdj
> 
> I have to back out the italicized bit, because if I just keep typing and hit enter, it's going to take me to that page that I don't really want. It should give the option of completing just to the hostname.

**Expected behavior:**

> Auto-complete should begin matching with individual hostnames and give the option of selecting them first, rather than having to edit a URL to get back to a site's front page.

- Brave Version (revision SHA): master branch

- Any related issues:

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7352)

**Comment by NejcZdovc** [comment]
@luixxiul should this be closed with this PR #7534?

**Comment by luixxiul** [comment]
Yeah I agree. Let's close this.

**Comment by tbates** [comment]
This is STILL broken even in current beta builds) and should not have been closed.

completion lists in the search box can be very useful. Brave's behaves differently, and less helpfully, than Safari or Chrome.

If the user types the beginning of a site they visit often, Brave offers long, complete urls to deep pages in those sites. But the USER is most often not interested in that, but instead wants to go to the homepage. This is nearly always the case for sites like FB, but also for most other site, like ebay or AMZN, or your local newspaper.

1. Enter the beginning of a favorite site: schol for scholar.google,com
EXPECTED: Brave offers scholar.google,com as a top completion followed by the last visited specific page. etc.
OBTAINED: Brave offers nothing but deep urls like  amzn.com/12389723487er872987yw89r79834789

**Comment by luixxiul** [comment]
> This is STILL broken.

It has been fixed and it got broken recently.

**Comment by tbates** [comment]
Probably a important to have a test suite that catches regressions like this? (and the fact that cmd-C is broken at present..."

**Comment by LaurenWags** [comment]
@tbates are you using 0.19.13 beta build? Wondering if you're seeing https://github.com/brave/browser-laptop/issues/11057 resolved.

**Comment by tbates** [comment]
Ahh.. I see the beta builds here at github now (I only had preview releases on in brave).
So.. checked and  ebay, play, amazon, telegraph all popping up the base url as hit #1. Which is good. 
Some  issues.
1. maps isn't bringing up the base URL for google maps:
<img width="848" alt="maps" src="https://user-images.githubusercontent.com/736156/30774318-9ac82af2-a078-11e7-936d-e09bf83984c8.png">

2. The pruning might be too dramatic. So where there are sites like play.google.com with sub-sites like music, these are now not appearing at all in the list. They used to. e.g. this screen grab from the current release (not github) has play/music in the list (but not play.google.com
<img width="1392" alt="old play" src="https://user-images.githubusercontent.com/736156/30774351-14a6e9b2-a079-11e7-9d99-facd627536af.png">

3. Sites like Amazon have duplicates in the top hits (well, they differ by things like www and https. could prefer no www and secure over non-secure? Also should sort by usage? (.co.uk more common for me than .com)
<img width="876" alt="amazon" src="https://user-images.githubusercontent.com/736156/30774329-b857ca78-a078-11e7-9547-43aa6870acbd.png">


4. 


 
Brave: 0.19.14 
rev: b051f3dbd1be9b2e997cd585cb19eaa934006713 
Muon: 4.4.19 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 17.0.0 
OS Architecture: x64

**Comment by LaurenWags** [comment]
great feedback, thanks @tbates. going to link your comment to the issue I mentioned previously and tag you so you can get updates there too.
