### ISSUE TITLE
Ads not blocked on adf.ly links

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6539]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Ads not blocked on adf.ly links

**Expected behavior:**
Should block all ads

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 

- Brave Version (revision SHA):
0.12.15
Brave	0.13.0
rev	0c7a64d

- Steps to reproduce:
    1. Visit http://adf.ly
    2. Enter any URL to shorten it
    3. Visit the shortened URL, Ads shown on the URL

- Screenshot if needed:
0.13.0
![adfly](https://cloud.githubusercontent.com/assets/17010094/21680384/4d61ec58-d341-11e6-890a-7818308cd385.gif)
![image](https://cloud.githubusercontent.com/assets/17010094/21680382/4a6ba78c-d341-11e6-9870-a7c0a1645ac2.png)

  0.12.15
  ![image](https://cloud.githubusercontent.com/assets/17010094/21680406/8708065e-d341-11e6-8cb6-083c34d08376.png)

- Any related issues:

**Comment by luixxiul** [comment]
Ads are properly blocked 👍
