### ISSUE TITLE
Opening a link causes a crash

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6540]
**Describe the issue you encountered:**
Open http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml and the browser crashes

**Expected behavior:**
It should return `ERR_NAME_NOT_RESOLVED` like Chrome does

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.12.15

- Steps to reproduce:
    1. Open http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml

- Any related issues:

Before verifying the bug, please make sure that the session data has been safely saved.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6572 which was merged into branch `0.13.1-branch`.
