### ISSUE TITLE
Transifex de_DE: bad translations set to 'reviewed'

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#6541]
**Did you search for similar issues before submitting this one?**
no
**Describe the issue you encountered:**
The German(Germany) (de_DE) translation on Transifex contains some translations that are bad, wrong or completely out of place and still they got set to _reviewed_, meaning they can no longer be altered by the translators.
I'd like to ask you to change this **before 1.0.0**, seeing as some of those keys are crucial.
**Expected behavior:**
Those translations should not have the _reviewed_ state.

- How to fix it (possible solutions)
    1. Remove the _reviewed_ state of **all** translations in German(Germany)(de_DE)
    2. For most of those bad translations I've added an issue on Transifex - please apply the change I wrote there. Note that the other translators would be left out that way.

**Comment by Zuzu-Typ** [comment]
I've tried contacting basically all of the people responsible / in charge of the German translation, without success, that's why I opened this issue.

**Comment by luixxiul** [comment]
I think you could be a moderator there if the team adds you.

**Comment by Zuzu-Typ** [comment]
It's nice of you to say that, but I can't just walk up to bbondy and ask to be a moderator ... well at least not successfully.
It would be a good idea though, since all 3 reviewers of de_DE have been gone for 9 months or longer.

**Comment by bsclifton** [comment]
cc: @aekeus

**Comment by aekeus** [comment]
@Zuzu-Typ I would be hesitant to mark all translations as unreviewed. Thanks for the feedback on the translations. Are you interested in moderator access for the German translation?

**Comment by Zuzu-Typ** [comment]
@aekeus I do understand that - I only suggested it because I didn't know about the efforts that marking them as unreviewed one by one could have caused.

Otherwise, yes - I am very interested in becoming a reviewer (I guess that's what you meant by _moderator access_).
Thank you very much!

**Comment by luixxiul** [comment]
OK then let's close this.

**Comment by aekeus** [comment]
Thanks @Zuzu-Typ. I created a Transifex request adding you as a reviewer for the de_DE.

**Comment by Zuzu-Typ** [comment]
@aekeus my dearest thanks for your support, I'm looking forward to the next preview (that's when I can check the new translations).

Best regards,
--Zuzu_Typ--
