### ISSUE TITLE
Add a new option to right-click for history and bookmarks

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6547]
when in the "Bookmark Manager" or in "Show History", when right-clicking on a URL, add a new option: "Add to Publisher list". if selected, then the URL is given to the ledger middleware for inclusion in the "synopsis"

**Comment by ryanml** [comment]
@NejcZdovc could I grab this one? Thanks!

**Comment by NejcZdovc** [comment]
@ryanml sure

**Comment by NejcZdovc** [comment]
@ryanml just to check quickly. Are you working on this one?

**Comment by ryanml** [comment]
@NejcZdovc

I have a possible approach for this one that I used to solve another issue (the base issue being able to manually include sites that don't meet the minimum criteria in to the synopsis) so tentatively, yes. Let's discuss this one next week if possible

Cc: @mrose17

**Comment by srirambv** [comment]
Right click on some entries in `about:history` doesn't bring up the `Include in Brave payments` option. Second attempt shows up the option.  Happens on random links not specific ones. 

cc: @kjozwiak @LaurenWags @GeetaSarvadnya

**Comment by srirambv** [comment]
Also nested bookmarks inside folders don't show the option. Is this expected?  @ryanml

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.703 903b8d0d
* libchromiumcontent 66.0.3359.139
* muon: 6.0.8
