### ISSUE TITLE
add a 48-hour to review notification for the ledger

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6551]
unless disabled, 24h prior to settlement, a notification is generated for the user. add a second notification at 48h, with the same options (including "no more notifications")

**Comment by mrose17** [comment]
waiting for https://github.com/brave/browser-laptop/pull/6706 to be merged in order to close.

**Comment by bsclifton** [comment]
Closed with https://github.com/brave/browser-laptop/pull/6706

## Test Plan from PR

1. go to about:preferences#payments
2. set auto-suggest sites to off
3. go to a site in another tab
4. click on the BTC icon
5. go back to the first tab and see if the site is present

**Comment by bsclifton** [comment]
@mrose17 I just noticed the above steps are for checking that publisher was immediately added. Can you add the steps for 48 hour check? You should be able to find the original one by @ayumi (she had great steps documented)

**Comment by mrose17** [comment]
@bsclifton - done.
