### ISSUE TITLE
360 Total Security blocks installation

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6552]
**Describe the issue you encountered:**
360 Total Security blocks installation.

https://github.com/brave/browser-laptop/issues/924#issuecomment-232700721
https://community.brave.com/t/error-when-installing-brave-for-win10-x64/239/7?u=suguru

The issue has been existed and not resolved since months according to the reports.

**Expected behavior:**
It should not block installation.

- Brave Version (revision SHA): 0.12.15

- Any related issues:

**Comment by Zuzu-Typ** [comment]
It appears that Qihoo-360 (aka 360 Total Security) does no longer detect a false positive for the Brave installer (Prev7 x64). This is based on [this](https://www.virustotal.com/de/file/cdbfaf4ed2bf10ce1a622c040010b9e7503ce1f6e8644912bc6bd1094cf0d11c/analysis/1483991099/) VirusTotal scan.
An antivirus called Ikarus still seems to detect Brave setup as a false positive.

**Comment by luixxiul** [comment]
I'm closing the issue for now. Let's reopen if this false positive issue still exists.
