### ISSUE TITLE
No contributions yet!

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6555]
As suggested [here](https://community.brave.com/t/bitcoin-payments-where-did-my-money-go/526/6): to avoid confusion for new users, when no contributions have been made yet, have other text go where the "View Payment History..." link will go after the first contribution.

<img width="850" alt="0" src="https://cloud.githubusercontent.com/assets/400552/21707882/27eafd74-d388-11e6-9c3b-cac76d5d5260.png">

**Comment by bsclifton** [comment]
What text should be shown instead of "View Payment History..."?  Simply `No contributions yet!`?

**Comment by mrose17** [comment]
I would say "Your first contribution will be in ..." and then use the timestamp from "Contribute due date is in ...".

yes, it's redundant, but probably worthwhile...

**Comment by mrose17** [comment]
after hearing @bradleyrichter's thoughts, in addition to "Your first contribution will be in ..." being shown when no contribution has been made; if a contribution has been made, then before the "View Payment History..." link, it should say "Your last contribution was ..."

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6617 which was merged into branch `0.13.1-branch`.
