### ISSUE TITLE
Ledger - Funds not updating

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#6556]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

I've made 3 attempts so far to add funds to my wallet for my monthly $5 contribution. I've been making regular monthly contributions from the same linked debit card acct since 10.25.2016 w/o issue until the latest payment cycle. 

-I enter the email acct used for my Brave Wallet.
-I receive the Authy SMS
-I receive the on-screen confirmation
-Funds are not added to the wallet
-Funds are not deducted from my debit account

**Original attempt to add funds:** 12.30.2016
**Second attempt to add funds:** 01.02.2017
**Third attempt to add funds:** 01.06.2017

**Expected behavior:**
Clicking and following the debit card fund option steps adds funds.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10 64bit

- Brave Version (revision SHA):
0.12.15

- Screenshot if needed:
Confirmation screen from 01.06.2017
![brave-payment-receipt-01062017](https://cloud.githubusercontent.com/assets/8979240/21716397/218818c2-d3bf-11e6-8463-2f1f61a17681.PNG)

- Any related issues:

**Comment by mrose17** [comment]
interesting. let me suggest something:

1. try one more time. maybe it was a temporary glitch.

2. if that still fails, please go to https://www.coinbase.com/ and set-up an account with them, you'll get a BTC wallet and be able to fund it with your payment card. if it doesn't fund, please contact them and see what's going on.

the coinbase buy widget seems to work pretty well most of the time, but there are periodic stickages... sorry!
