### ISSUE TITLE
Launching web.telegram.org causes page crash

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6557]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Launching web.telegram.org causes page crash

**Expected behavior:**
Should not crash and allow users to login

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d
Works on 0.12.15

- Steps to reproduce:
    1. Visit web.telegram.org
    2. Page crashes
    3. Same with shields down

- Screenshot if needed:
![telegram](https://cloud.githubusercontent.com/assets/17010094/21719454/d823ea92-d415-11e6-80ae-250b47198875.gif)

- Any related issues:
cc: @jonathansampson

**Comment by alexwykoff** [comment]
Could not reproduce on OS X. @srirambv perhaps it was fixed by https://github.com/brave/muon/pull/146 ?

**Comment by srirambv** [comment]
@alexwykoff It does look like it fixed the issue. No crash on visiting the site.

Closing the issue for now.
