### ISSUE TITLE
Get rid of Vibrant and use computed style for background color at x,y for computedThemeColor

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#656]
Vibrant is too slow, I think something like this, possibly sampling a few locations might work just as well and be way faster.
`window.getComputedStyle(document.elementFromPoint(1,1)).backgroundColor`

Vibrant also causes some sites to infinite load.

**Comment by bbondy** [comment]
A profile showed 33% of cpu is on vibrant calculation during page load.

**Comment by bradleyrichter** [comment]
yikes! That's unfortunate. 

I am looking forward to a point sample and have the tab connect nicely to the page header with a matching color. (with pref to disable for the grey-tab purists)

**Comment by bbondy** [comment]
yep, we have the pref already.
I have some code that does a sample of the background color at a few spots. It can't reach into images efficiently though but this seems to still work very well.  The blend into a lot of page colors is nice.
There's also code to make sure it is different enough in color to the innactive tab, or else it just uses the default white.

**Comment by bbondy** [comment]
Fixed by
https://github.com/brave/browser-laptop/commit/4d9c80dbdd0db582b1159e657f7b4991877eb204
