### ISSUE TITLE
input type text and select should have separate classes

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6562]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Right now @bradleyrichter cannot design our form <select> elements from our <input type="text"> elements. He needs them to have separate classes not just form control.

**Expected behavior:**
They should have shared styles but also a separate selector to make it easier for adding unique styles.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All.

#6084 #5972

**Comment by bsclifton** [comment]
Closing this as a dupe in favor of https://github.com/brave/browser-laptop/pull/6084
