### ISSUE TITLE
Reimporting from bookmark HTML files causes folders to be placed after bookmarks

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6564]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Reimporting from bookmark HTML files causes folders to be placed after bookmarks

**Expected behavior:**
Should retain the positions of the folders and bookmarks

- Platform (Win7, 8, 10? macOS? Linux distro?): 
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d

- Steps to reproduce:
    1. Import from a bookmark HTML file
    2. Keep a track of the position of folders
    3. Reimport the same HTML file and all folders are put at the end of the bookmark items

- Screenshot if needed:
![import](https://cloud.githubusercontent.com/assets/17010094/21734997/4fa143ba-d45e-11e6-82be-8b740776bee6.gif)

- Any related issues:
cc: @darkdh

**Comment by luixxiul** [comment]
The milestone was moved to 0.13.3
