### ISSUE TITLE
Make Brave re-brandable

### ISSUE THREAD

**Issue by mmilkov** [brave/browser-laptop#6565]
Hello guys. I am just experimenting with Brave to see how it works and I am just curious how can I rebrand it from Brave to something different? What files need to be edited? I want only to change building files and nsi to make built files from Brave to Brav for example and bravDefaults.exe. 

I am just editing the buildPackage.js and change every "Brave" to "Brav" but when I run "npm run build-package" I got:

```
Packaging app for platform win32 x64 using electron v1.4.31
Fatal error: Unable to load file
 undefined
done
```
Can I have a little help? Thanks :)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version:
0.12.5

**Comment by mmilkov** [comment]
@bsclifton Actually nobody comes in the new issue. I want to ask few things..

Actually, when I change the name from 'Brave' to 'Brav' and delete this lines:


> cmds = cmds.concat([
>   //'"./node_modules/.bin/webpack"',
>   // 'npm run checks',
>   'node ./node_modules/electron-packager/cli.js . Brav' +
>     ' --overwrite' +
>     ' --ignore="' + ignoredPaths.join('|') + '"' +
>     ' --platform=win32' +
>     ' --arch=x64' +
>     ' --version=' + VersionInfo.electronVersion +
>     // ' --icon=./res/app.ico' 
>     ' --asar=true' +
>     // ' --app-version=' + VersionInfo.braveVersion +
>     // ' --build-version=' + VersionInfo.electronVersion 
>     ' --protocol="http" --protocol-name="HTTP Handler"' +
>     ' --protocol="https" --protocol-name="HTTPS Handler"' 
>     // ' --version-string.CompanyName="Vica Inc."' +
>     // ' --version-string.ProductName="Vica"' +
>     // ' --version-string.FileDescription="Vica"'
> ])


is working, but why is generating again 'brave.exe' not 'brav.exe'? When I uncomment some of this lines it throws me:
`Fatal error: Unable to load file
 undefined`

Can you help me with this? I want to change the icon on .exe file and task-bar icon..

One other issue is when I am running it in Task Manager, I am getting 'Electron'.. How can I make it 'Brav'?

Thank you :)

**Comment by bsclifton** [comment]
@mmilkov have you tried replacing the icon (overwriting the existing one with one also in ICO format with the same name)?  This should work just fine.  The `--version-string` values get translated into resources... so you should be able to set those to anything you'd like

**Comment by mmilkov** [comment]
@bsclifton Yes, the icon is the same, I am downloading the original brave 0.12.15 source code and editing buildPackage.js and replacing 'Brave' to 'Brav'. See the  commented lines.. I do not know why, but without this lines is working... when I uncomment some of this lines it throw me this error. Thanks
