### ISSUE TITLE
windowContainer is used as React root div id and Window component div id

### ISSUE THREAD

**Issue by jide** [brave/browser-laptop#6568]
React root div id is ["windowContainer"](https://github.com/jide/browser-laptop/blob/master/app/extensions/brave/index.html#L22), and is where the `<Window/>` [root component is mounted](https://github.com/jide/browser-laptop/blob/master/js/entry.js#L82) :

```js
  ReactDOM.render(
    <Window includePinnedSites={disposition !== 'new-popup'} frames={frames} initWindowState={initWindowState} />,
    document.getElementById('windowContainer'))
```

But the `<Window/>` component itself renders a `<div/>` with a ["windowContainer"](https://github.com/jide/browser-laptop/blob/master/js/components/window.js#L68) id :

```js
    return <div id='windowContainer' className={cx(classes)} >
      <Main windowState={this.state.immutableData.windowState}
        appState={this.state.immutableData.appState} />
    </div>
```

So we end up with 2 nested divs with a "windowContainer" id:

<img width="620" alt="capture d ecran 2017-01-07 a 02 15 36" src="https://cloud.githubusercontent.com/assets/333073/21737978/3bdfa9ae-d47f-11e6-9f25-05ca77bbcdd1.png">

The root div could simply be renamed "root".

**Comment by luixxiul** [comment]
Using the same identifier multiple times must be avoided. it should be fixed keeping the tests coverage.
