### ISSUE TITLE
Brave not added to App Paths on Windows

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6569]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Attempting to run 'brave' from the Run dialog fails.

**Expected behavior:**
Brave, like other browsers, is callable from the Run dialog (and present in App Paths).

> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version (revision SHA):** 0.12.5

**Comment by bbondy** [comment]
Can HKCU be used instead?
The .nsi file seems like a good place to add this

**Comment by jonathansampson** [comment]
@bbondy I suspect that would work 🙂

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1019
