### ISSUE TITLE
Brave shows blank screen when accessing certain sites

### ISSUE THREAD

**Issue by thykkutathil** [brave/browser-laptop#657]
When accessing www.newsblur.com on the MacOS build, the Browser Console shows "Inspected target disconnected." and the screen is entirely blank. I am able to open a new Window and resume normal browsing.
![screen shot 2016-02-07 at 9 57 51 am](https://cloud.githubusercontent.com/assets/143114/12873023/4a21db64-cd81-11e5-8010-38c75a3f0f47.png)

Version: 0.7.13
Electron: 0.36.7
libchromiumcontent: 47.0.2526.110

MacOS El Capitan 10.11.3

**Comment by TheFallenOneGOTH** [comment]
Partial confirmation on a Windows 10 non-touchscreen platform. Same Brave specs.

Going to NewsBlur loads for me for a few seconds before going to a black screen and becoming unresponsive.

**Comment by bbondy** [comment]
Due to vibrant.js and broken favicons.
Verified this is fixed now that we don't use vibrant.js anymore.
https://github.com/brave/browser-laptop/commit/4d9c80dbdd0db582b1159e657f7b4991877eb204
