### ISSUE TITLE
Closing an unloaded tab crashes the browser

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#6571]
**Did you search for similar issues before submitting this one?**
No similar issue found

**Describe the issue you encountered:**
When you try to close a tab that was not loaded before (when browser is reopened), browser crashes.

**Expected behavior:**
Browser does not crash

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
361e09b

- Steps to reproduce:
    1. You need to have some opened tabs from the last brave session (in my case I had two tab pages)
    2. Reopen brave
    3. Click on first tab on the second tab page
    4. Right click on this first tab
    5. Select `Close tabs to the left`
    6. Browser crashes

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/9574457/21741134/9c94c3e4-d4cd-11e6-9b16-514ff5203a31.png)

**Comment by Liunkae** [comment]
Nice find! I think this is the same crash @srirambv was having earlier (#5946 and #6480).

**Comment by Noremac201** [comment]
I was having this crash also on Arch Linux.

**Comment by NejcZdovc** [comment]
Yes, problem with this error is that tabs are not load and are null.

**Comment by jonathansampson** [comment]
@bsclifton and I were both able to repro this. Thank you for reporting, @NejcZdovc!

**Comment by bsclifton** [comment]
This is a show stopper, IMO.  Here's how to repro:

1. Launch Brave and load ~4 tabs with any web pages
2. Go to preferences > tabs and DISABLE tab preview on hover
3. Close Brave
4. Re-launch Brave and it will focus on the last tab
5. Close any of the tabs which are NOT focused
6. Crash! :fire:

**Comment by srirambv** [comment]
@bsclifton No need to disable tab preview as well. Can reproduce with these steps 
1. Launch Brave and load ~4 tabs with any webpages
2. Close and restart the browser
3. **Ensure you don't hover on other 3 inactive tabs**
4. Right click on the active tab and select close other tabs and boom it cashes
