### ISSUE TITLE
Can certain subdomains for payments be accepted?

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6576]
**Describe the issue you encountered:**

CC @mrose17 

After I visited http://www.asahi.com some times to get the site listed on the publisher table on about:preferences#payments, the domain was changed to `http://asahi.com`, which is unreachable. 

From all of the sites on the table their subdomains have been removed for a reason, which I'm not sure I actually understand. Could I know what it is, and whether it might be possible to accept/respect some subdomains often used, for example `www`?

**Expected behavior:**

- Brave Version (revision SHA): 0.12.15

- Any related issues:

**Comment by mrose17** [comment]
at present, sites such as twitter, youtube, medium, etc., are categorized as 

the https://github.com/brave/ledger-publisher repo allows us to define rules that map subdomains/paths into different publisherIDs. we haven't enabled that yet for two reasons:

1. we need to have a rule to decide for which sites it should be done.

2. we need to determine how to do the ACME roundtrip (how to know that the email-address claiming ownership of a domain is legitimate, and how to map a URL to the publisherID.

the first is a management policy, the second is technical.
