### ISSUE TITLE
Issues with <webview>s and focus

### ISSUE THREAD

**Issue by javan** [brave/browser-laptop#658]
Hello, I'm working on an Electron app that behaves similar to Brave in that it opens external URLs in a `<webview>`, and discovered that `autofocus` often doesn't work, and that the OS X emoji picker isn't positioned correctly. I checked out Brave in hopes that you'd found a solution or workaround, and see that it suffers in the same ways.

I've outlined the issue with Electron here: https://github.com/atom/electron/issues/1773#issuecomment-180898885

In short, focus doesn't seem to work correctly unless the host page is first focused, then the embedded page, then an input in the embedded page.

Here's a recording showing the problem in Brave:
![brave-focus](https://cloud.githubusercontent.com/assets/5355/12873882/b8eaf840-cd96-11e5-84ed-1ea72a6635aa.gif)

You can see the input isn't `autofocus`ed initially, and the emoji picker position is wrong until you follow the steps I described above. I'll report back if I discover any new information, and please do the same. :heart:

**Comment by javan** [comment]
FYI, tested with:
<img width="532" alt="screen shot 2016-02-07 at 12 35 32 pm" src="https://cloud.githubusercontent.com/assets/5355/12873901/4fa84b2a-cd97-11e5-8a2b-0d6e1d4d8439.png">

**Comment by psimyn** [comment]
:( that didn't actually fix it. It seems that sometimes the body element has focus rather than the webview on the app container.

New tabs are ok, but refreshing the entire app means focus is broken when it reloads

**Comment by luixxiul** [comment]
Maybe already fixed?

**Comment by bbondy** [comment]
@javan is it still a problem for you?

**Comment by javan** [comment]
Just checked using the most recent Brave build and it seems to be all good now. Did you change anything? Guessing it was fixed upstream in Chrome or Electron.

**Comment by bbondy** [comment]
not sure, thanks!
