### ISSUE TITLE
Icons in about:extensions may not be 48x48

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6580]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The about:extensions page assumes images are the size they claim to be in their extension manifest file. This is not the case with all extensions (confirmed by a recent extension I was porting).

**Expected behavior:**
The about:extensions page displays extension icons as 48 pixels wide.

**Brave Version (revision SHA):** 0.12.15

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6581 which was merged into branch `0.13.1-branch`.

**Comment by srirambv** [comment]
## Test Plan
Enable all extension from settings
Visit about:extension
Open developer tools and verify the image loaded is 48x48 images
