### ISSUE TITLE
Allow scripts doesn't show a security icon

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6584]
The icon changes for both Chrome and Firefox for:
https://very.badssl.com/

because of mixed content.
Also if you allow scripts, it then shows no lock icon at all, I think in that latter case it should show an insecure icon.

**Comment by bbondy** [comment]
I guess this is because it's an sha-256 certificate now and not because of a bug in our code.

**Comment by bbondy** [comment]
Note that originally this was posted because of a test failing, I'm going to fix the test separately , to use a site that has an sha-1.  Also this no longer blocks 0.13.0 so not a big rush for it.

**Comment by diracdeltas** [comment]
i think it shows an insecure icon in chrome because of passive mixed content (images), so this is really the same ticket as https://github.com/brave/browser-laptop/issues/2168

**Comment by diracdeltas** [comment]
> Also if you allow scripts, it then shows no lock icon at all, I think in that latter case it should show an insecure icon.

that does seem to be a regression. cc @darkdh

**Comment by luixxiul** [comment]
The issue seems to have been fixed somewhere.

**Comment by luixxiul** [comment]
It has been fixed.
