### ISSUE TITLE
Feature: lockable browser tabs

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#6588]
Feature request as per: https://community.brave.com/t/can-a-tab-be-locked/599

![image](https://cloud.githubusercontent.com/assets/15019644/21776430/504c2268-d692-11e6-8e94-21600004ae2e.png)

**Comment by srirambv** [comment]
Created issue for Android browser [here](https://github.com/brave/browser-android-tabs/issues/100)
