### ISSUE TITLE
How to install extensions on Brave...

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#6589]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
How to install extensions in the Brave?
Could you post here in this post yourself or tell me what you can do to install extensions (Ex.: Netflix, Chromer Actions For Youtube)
- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.10 64bits
- Brave Version (revision SHA):
12.15

**Comment by bsclifton** [comment]
@EuNlope we have some documentation available in our wiki, which you can see here:
https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions

We haven't opened the floodgates for extensions as we're still making sure the code needed by the extensions is in place.  You can follow our extension analysis / implementation here:
https://github.com/brave/browser-laptop/projects/1

cc: @jonathansampson 

Are there specific extensions you're wanting to install?

**Comment by EuNlope** [comment]
@bsclifton Yes, the extension of Netflix or Ghostery for example...

**Comment by jonathansampson** [comment]
@EuNlope To which Netflix extension are you referring? Brave handles tracker-blocking by default; what functionality of Ghostery do you feel Brave is lacking?
