### ISSUE TITLE
repeated exception in httpsEverywhere.js on startup

### ISSUE THREAD

**Issue by andreasgal** [brave/browser-laptop#659]
<img width="420" alt="messages image 204347106" src="https://cloud.githubusercontent.com/assets/313748/12875921/97190276-cda9-11e5-8d1f-af6a2d4cac1d.png">

**Comment by andreasgal** [comment]
This happened on my first launch of 0.7.13 on mac

**Comment by bbondy** [comment]
Please attach the files here:
`~/Library/Application\ Support/Brave/rulesets.sqlite`
`~/Library/Application\ Support/Brave/httpse-targets.json`

Then try removing them.  That will fix your startup at least for now, it'll redownload the files.
I'll push a fix to the popup error handling at least as well for now.

**Comment by andreasgal** [comment]
2nd launch this didn't happen any more

**Comment by andreasgal** [comment]
[httpse-targets.txt](https://github.com/brave/browser-laptop/files/121053/httpse-targets.txt)

**Comment by andreasgal** [comment]
[brave.zip](https://github.com/brave/browser-laptop/files/121055/brave.zip)

Hi Brian. Nice to work with you again :) Attached are the two files as requested.

**Comment by bbondy** [comment]
Thanks for posting Andreas, I was hoping the files reproduced on each launch.  

I'll leave this open until we find a good reason for what the error was.

CC @diracdeltas

**Comment by luixxiul** [comment]
Does this still persist on the latest version?

**Comment by bbondy** [comment]
We have better downloading of data files and no longer use sqlite for HTTPS Everywhere so closing this.
