### ISSUE TITLE
Sites added manually (auto-suggest sites off) don't show if adv criteria not met

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6592]
Auto-suggest sites (our current Brave Payments tab behavior for including sites) will be introduced with https://github.com/brave/browser-laptop/pull/6422

The user can choose to disable this and instead, they'll be shown the bitcoin icon in the URL bar.  Here is the exact problem:

- User clicks bitcoin icon for a site they are not yet supporting
- Icon lights up, signifying they are now supporting the site
- User goes to preferences -> Payments
- Site is NOT shown in the list, because advanced criteria is not met yet
- If page visits or time goes over threshold, site is then shown (as expected) with the correct enabled setting

**Comment by bsclifton** [comment]
cc: @mrose17 @bradleyrichter 

Maybe this behavior is OK for launch? No milestone set since it would be good to discuss

**Comment by bsclifton** [comment]
A few options to kick things off:

1. Do nothing; we can put a footnote in the Payments tab which states:
*NOTE: sites which don't match criteria shown in "Advanced Settings" are not shown

2. We could always show ALL sites and then disable some of the advanced criteria:
![image](https://cloud.githubusercontent.com/assets/4733304/21795523/b088215e-d6bf-11e6-8d9b-7a7d03f05940.png)

3. We could create and use a "tri-state" bitcoin button that the user would click
- Disabled by default (gray icon)
- Click once to add it to your supported sites (orange icon)
- Click one more time to enable an "always support" mode (new icon)

4. Make clicking the bitcoin button meet the criteria automatically.
- Site gets added to supported sites
- Minimum view count is added, to ensure it shows

**Comment by cezaraugusto** [comment]
Speaking as a user, I personally prefer to hit the bitCoin icon and just show the site I want on publisher's list immediately, thus skipping current advanced criteria. With no additional settings. 

## Supposing the below scenario: 

I am an avid reader of https://clifton.io, and I'd like to support his site. However he's not publishing much for a while, so I don't visit his website so often, BUT I like him, his blog, and I'd like to send him money anyway.

What I do is just go one time to his website and hit the enabled publisher icon, and now he's on my budget list and I can keep browsing other stuff. Otherwise, I'd have to change rules and browse randomly his blog just to make sure he's on the list, which can be annoying.

**Comment by bradleyrichter** [comment]
@cezaraugusto As a user, do you expect each site you mark for payment inclusion to share your monthly budget evenly in this case?

Do you expect to be able to set it for an X amount of monthly value?

**Comment by cezaraugusto** [comment]
yes, that's expected to me. That sites I choose to add share my monthly budget evenly.

I think setting an X amount is valid as well, and very likely to be a feature request from users in a near future.

**Comment by cezaraugusto** [comment]
Stepping back from this one and tagging @mrose17 in favour of his fix.

**Comment by mrose17** [comment]
waiting for https://github.com/brave/browser-laptop/pull/6706 to be merged in order to close.

**Comment by bsclifton** [comment]
Closed with https://github.com/brave/browser-laptop/pull/6706

**Comment by luixxiul** [comment]
The issue was reopened as the icon is not implemented yet like https://github.com/brave/browser-laptop/issues/6754#issuecomment-277421485

**Comment by cezaraugusto** [comment]
for reference: two main problems regarding this issue is that:

* sites added manually only show if you refresh payments panel
* sites added manually don't have icons

**Comment by mrose17** [comment]
@cezaraugusto - can you close this issue and open a new one with just the two bullet points above?

**Comment by cezaraugusto** [comment]
Closing in favour of #7111
