### ISSUE TITLE
implement session history context menu for back and forward buttons

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#660]
context clicking the back and forward buttons should show session history like other browsers do.

**Comment by psimyn** [comment]
I think this will need some electron changes as well: to expose history as a list, and to store title as well as url.

**Comment by luixxiul** [comment]
Which browsers do show a session history?

**Comment by bbondy** [comment]
I think this is a dupe of #1622.  Closing for that one since it has a screenshot.
