### ISSUE TITLE
Include "Other Bookmarks" folder inside Bookmark menu on the menubar and bookmark toolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6607]
**Describe the issue you encountered:**

Include "Other Bookmarks" folder inside Bookmark menu on the menubar and the bookmarks toolbar. It will let users find their bookmarks more easily than opening the bookmark manager to find them.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.12.15

- Screenshot if needed:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21849402/eee8cb62-d848-11e6-96bb-64f3320625ad.png)

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/21849466/469b0758-d849-11e6-8afc-45f78d229d48.png)

- Any related issues:

**Comment by luixxiul** [comment]
I think this suggestion is the same as "Treat 'Other Bookmarks' folder in the same way as other bookmark folders"

**Comment by srirambv** [comment]
Same as #3145?

**Comment by luixxiul** [comment]
Partially

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/other-bookmarks-not-listed/7352?u=eljuno
