### ISSUE TITLE
I can not see Netflix in the Brave for Linux

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#6616]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you **
Interesting fact happened to me that when logging into the Netflix site I ended up not being able to watch any video, stating that I had the Widevine component was not present ... Can anyone help me?
- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.10
- Brave Version (revision SHA):
12.15

**Comment by Liunkae** [comment]
Brave does not currently support Widevine on Linux. However, there are plans to support Widevine on Linux (see issue #5282).
