### ISSUE TITLE
Opening HTML file from terminal or finder searches it on google

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop#6618]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Using the `open` command from the Mac terminal on an HTML file opens it with your default browser. With Brave as my default browser it opens a search for the filename instead of opening the file with the file:// protocol.

**Expected behavior:**
It should open a blank tab and load in the file:// URL.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.0

- Steps to reproduce:
    1. Create an HTML file on your mac
    2. Open your terminal
    3. Run the command `open myFile.html` or navigate to it with Finder and right click > open with Brave
    4. See a search page load

- Screenshot if needed:

This is what I see:
<img width="1280" alt="screen shot 2017-01-11 at 10 44 18 pm" src="https://cloud.githubusercontent.com/assets/490294/21879771/cdf4fd48-d84f-11e6-98ae-2ab5c9096fb1.png">

This is what I should see:
<img width="1280" alt="screen shot 2017-01-11 at 10 47 18 pm" src="https://cloud.githubusercontent.com/assets/490294/21879820/04db3ee4-d850-11e6-8ff5-769f9c10a781.png">

- Any related issues:

**Comment by bsclifton** [comment]
This was originally captured with https://github.com/brave/browser-laptop/issues/5828 and should have been fixed with https://github.com/brave/browser-laptop/pull/6424... but it's only on the `0.13.1-branch` branch

I'll close this as a dupe, but if you wanted to try the same steps on `0.13.1-branch` and confirm the fix, that would be awesome :smile:

**Comment by jkup** [comment]
@bsclifton Oh that's good to hear. Ah, it seems like it's the space in the folder name not the process of opening a local file 👍
