### ISSUE TITLE
Right mouse button doesn't work

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#662]
For some reason my right mouse button doesn't open a context menu. It just does nothing. 

MacOS 10.10.5

**Comment by psimyn** [comment]
This fixed for me (from related issue) 

```
rm -rf ~/.electron
npm update
```

**Comment by bbondy** [comment]
Yep it required a new electron-prebuilt and it gets cached in ~/.electron, thanks for posting the fix.
