### ISSUE TITLE
We need libxss1 for debian

### ISSUE THREAD

**Issue by posix4e** [brave/browser-laptop#6621]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
We need to install libxss1 on debian for package users. It should just be a dep
**Expected behavior:**
user can install brave on linux with no deps
- Platform (Win7, 8, 10? macOS? Linux distro?):
jessie
- Brave Version (revision SHA):
12.0.5
- Steps to reproduce:
    1. Use my newly uploaded jessie vagrant
    2. Add brave apt and key
    3. Install brave and launch Brave

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Moved the labels from #6623, which is a PR.
