### ISSUE TITLE
Persist Sync credentials

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#6624]
Sync gets AWS credentials from the Sync server so it can read and write encrypted data to AWS S3.
These credentials are valid for 36 hours, and when they expire Sync auto refreshes them.

To reduce network requests, browser clients should receive credentials from the Sync library, persist credentials, and provide them to the library on init.

Depends on Sync lib: https://github.com/brave/sync/issues/30

**Comment by diracdeltas** [comment]
Maybe we should just open sync browser-laptop issues in brave/sync for now and mark which platforms they are for to avoid duplicating issues

**Comment by ayumi** [comment]
im cool with that for now.
in the future we might get more platform specific tasks.
