### ISSUE TITLE
How to add Flash and Widevine to Brave? (Ubuntu)

### ISSUE THREAD

**Issue by EuNlope** [brave/browser-laptop#6626]
**Did you search for similar issues before submitting this one?**
Yes 
**Describe the issue you encountered:**
How can I add the Flash Player Plugin and Google Widevine to Brave?
- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.10
- Brave Version (revision SHA):
12.15

**Comment by luixxiul** [comment]
Please open `about:preferences#security` and enable them.

**Comment by luixxiul** [comment]
Also please don't make the same question which has been already answered. https://github.com/brave/browser-laptop/issues/6616#issuecomment-272070854

**Comment by luixxiul** [comment]
Finally, can I ask you to make questions like this on https://community.brave.com/ from the next time?

I think you will be able to get better responses there, not here.

**Comment by EuNlope** [comment]
@luixxiul I did not know about this site .. I accessed the about: preferences # security but WIdevine is not listed in it what can it be? Is this area more for correct development? How can I help you ?

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/6616#issuecomment-272070854
> Brave does not currently support Widevine on Linux.
