### ISSUE TITLE
Videos auto-play in newly opened "background" tabs

### ISSUE THREAD

**Issue by joekaiser** [brave/browser-laptop#6627]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When you open a new tab, if that tab has a video it automatically starts to play.

**Expected behavior:**
I don't know if this a browser thing, or if Youtube does it, but when using Chrome the videos don't automatically start to play until you switch to that tab. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
I only tried on W10 so far

- Brave Version (revision SHA):
0.12.15
- Steps to reproduce:
    1. go to youtube.com
    2. open two videos; each in their own tab
    3. Notice the videos start to play in both tabs

**Comment by Liunkae** [comment]
@joekaiser: Thanks for the report! I agree that this should be addressed.

We are tracking this issue at #5908. I'll close this one as a duplicate and leave a note there.
