### ISSUE TITLE
Brave doesn't start - OS X

### ISSUE THREAD

**Issue by szpecku** [brave/browser-laptop#663]
Brave browser doesn't start on OSX. Moreover, when I clicked once on launcher, no error dialog was displayed and app stopped immediately without displaying anything - to see dialogs, which you can check in prints screen, I needed to click multiple times on launcher.
![screenshot_001](https://cloud.githubusercontent.com/assets/1184480/12881385/6f23fb70-ce41-11e5-8841-342bb7b3e1bc.png)

Simple reinstallation didn't work - I needed to remove whole brave's date from Library folder

**Comment by bbondy** [comment]
Do you still have this file? `~/Library/Application\ Support/Brave/session-store-1`, it could contain personal data like bookmarks so please take a look first, but having that could lead to an explanation. It sounds like there was a consistent problem with it not being able to read the storage or something like that.

**Comment by szpecku** [comment]
Unfortunatelly I removed everything from Application Support/Brave folder. I think something was broken after an update - yesterday evening Brave informed me about new pending update, but I postponed it.
Today morning following issue happend. I can just say it doesn't have nothing to bookmarks - I didn't use this feature at all.

**Comment by bbondy** [comment]
OK please attach the file if it happens again.

**Comment by ElissaBeth** [comment]
I am seeing multiple reports of this issue on Mac OSX - since latest update - consider this issue to be high priority.

**Comment by bbondy** [comment]
Elissa the one you mentioned on Slack seems to be a different error related to https everywhere.
Please post a new issue for that one.

**Comment by ElissaBeth** [comment]
Thanks - will do.

On Mon, Feb 8, 2016 at 6:39 PM, Brian R. Bondy <notifications@github.com>
wrote:

> Elissa the one you mentioned on Slack seems to be a different error
> related to https everywhere.
> Please post a new issue for that one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/663#issuecomment-181675640>
> .
>



-- 
Elissa Shevinsky
Twitter.com/ElissaBeth
650-380-6972

**Comment by bbondy** [comment]
Actually the HTTPS one is handled here: https://github.com/brave/browser-laptop/issues/659

**Comment by sejoker** [comment]
I experienced the same issue as @szpecku, (brave dies silently even after reinstallation), I fixed the issue by removing  `~/Library/Application\ Support/Brave/session-store-1`, will send the problematic file to a @bbondy's email.

**Comment by bbondy** [comment]
I think this will be fixed in 0.7.14, but please re-open if you see it again.  We're expecting to release it tomorrow.
