### ISSUE TITLE
Pubmed NCBI filters search broken

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#6631]
https://www.ncbi.nlm.nih.gov/account/?back_url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fsites%2Fmyncbi%2Fpubmed%2Ffilters

The "Sign in to NCBI box" (link above) is clipped by the window, off to the left. 

It's probably their fault. There are many usability problems caused by javascript on that website.

**Comment by luixxiul** [comment]
It's been fixed 👍
