### ISSUE TITLE
Blue highlight shown when navigating between pages

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6636]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Blue highlight shown when navigating between pages

**Expected behavior:**
Should not show the blue highlight between page navigation

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	dc4f0fd

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 8
    2. In new tab click on the preferences button 
    3. See the blue hightlight on the URL bar
    4. Navigate back,, shows the same blue highlight on the window buttons

- Screenshot if needed:
![blueoutline](https://cloud.githubusercontent.com/assets/17010094/21953823/faab78ae-da38-11e6-94a4-e9bb2168adcc.gif)

- Any related issues:

**Comment by srirambv** [comment]
cc: @bsclifton

**Comment by bbondy** [comment]
Was this happening with the last preview too?

**Comment by srirambv** [comment]
No this is happening on preview 8 not previous builds.

**Comment by bsclifton** [comment]
I believe this is fixed with https://github.com/brave/muon/commit/19120d30da81abb2571110920c4f06f295d251d8

**Comment by bsclifton** [comment]
I tried the above steps (in GIF that @srirambv shared above) in preview 9 and it's working great :smile: Closing issue (please do reopen if you're able to repro, @srirambv)

**Comment by luixxiul** [comment]
Test plan: available in the 1st post
