### ISSUE TITLE
Fix URL bar autocomplete flashing as you type

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6644]
Before:
![before](https://cloud.githubusercontent.com/assets/831718/21957335/01efba8e-da62-11e6-9fa2-51d090fa1ff7.gif)

After:
![after](https://cloud.githubusercontent.com/assets/831718/21957332/f8f991fc-da61-11e6-9014-2bc7cc0a3c18.gif)

**Comment by bbondy** [comment]
For testing, it shouldn't flash anymore, and also ensure that suggestions still work as it used to with 0.12.15.

**Comment by alexwykoff** [comment]
This appears to have regressed in 0.13.0 RC 1
[2017-01-20 12-16-25.mp4.zip](https://github.com/brave/browser-laptop/files/720165/2017-01-20.12-16-25.mp4.zip)

**Comment by alexwykoff** [comment]
pebkac, reclosing
