### ISSUE TITLE
sync everything with other browsers

### ISSUE THREAD

**Issue by drfunkencluck** [brave/browser-laptop#6647]
Okay someone wondering is not everyone use is is always able to install brave onto every single computer so why can't Brave say sync with chrome that way I can still continue to use Chrome on say my android phone and use brave on the laptop' much later in brave could sync settings, extensions, themes, bookmarks,history,downloads and open tabs with say Firefox and Opera rather than reinventing the wheel you actually making it compatible with other browsers.

**Comment by luixxiul** [comment]
Duping to #1854

**Comment by luixxiul** [comment]
If you have any questions or suggestions, please visit our community: https://community.brave.com/
