### ISSUE TITLE
Add AppleScript support for accessing tab URLs and names (Mac-only)

### ISSUE THREAD

**Issue by michaeljtsai** [brave/browser-laptop#665]
For example, support scripts like:

```
tell application "Safari"
    set _tabs to tabs of window 1
    repeat with _tab in _tabs
        get _tab's name
        get _tab's URL
    end repeat
end tell

tell application "Google Chrome"
    set _tabs to tabs of window 1
    repeat with _tab in _tabs
        get _tab's title
        get _tab's URL
    end repeat
end tell
```

This would allow integration with apps that care about the current page that's being viewed (e.g. EagleFiler, RescueTime) as well as enable users to write their own automation scripts.

**Comment by BrendanEich** [comment]
https://www.chromium.org/developers/design-documents/applescript

**Comment by BrendanEich** [comment]
https://github.com/electron/electron/issues/4418

**Comment by johneday** [comment]
Available properties:
`tell application "Google Chrome" to get properties of tabs of window 1`

**Comment by Nevwild** [comment]
+1 

I would love to be able to use Things 3's Autofill option,  which requires applescript support.

**Comment by twilsonco** [comment]
+1
This is a must for easily switching from safari to brave for windows that opened in safari automatically.

**Comment by bsclifton** [comment]
@twilsonco do you know if this works for you in Chrome? If so, our [new Chromium based UI](https://github.com/brave/brave-browser) may fix this problem. Would be great to verify

**Comment by twilsonco** [comment]
Yes, Chrome has a nearly complete AppleScript dictionary. I've made a set of AppleScripts for switching tabs/windows/all to/from chrome/safari.
One missing item from the dictionary is the ability to query a tab's incognito status, but you can query that from javascript so it's not a big problem, plus I figure Brave's private tabs wouldn't necessary match up with the incognito implementation.

**Comment by bsclifton** [comment]
@twilsonco awesome, thanks for confirming! This should be fixed when we release the new UI (within the next few months). I'm going to mark this particular issue as `wontfix` since the `browser-laptop` repository is for our Electron/Muon based UI.  Hang in there just a bit longer 😄

**Comment by twilsonco** [comment]
I’m almost holding my breath for iOS sync, then I can switch completely to brave. Love it so far.
