### ISSUE TITLE
"Estimated Time Saved" should take minutes into account

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6650]
## Test Plan
1. Make sure all instances of Brave are closed
2. Open your session file (`~/Libraries/Application Support/brave/session-state-1` on macOS, `%appdata%\brave\session-state-1` on Windows) in an editor such as Sublime, vim, notepad, etc.  If you have a JSON formatting plugin, you may wish to use it (so that it's easier to edit)
3. Edit the JSON for`adblock` > `count` to be `555555` (six fives)
![screen shot 2017-03-10 at 4 58 46 pm](https://cloud.githubusercontent.com/assets/4733304/23817814/4415668a-05b3-11e7-8ae5-7cfe46a75e6c.png)
4. Save the file and then launch Brave
5. Verify it shows hours with 1 decimal point of precision, like so:
![screen shot 2017-03-10 at 4 58 12 pm](https://cloud.githubusercontent.com/assets/4733304/23817831/6c5caf68-05b3-11e7-8fb0-c29ecc175243.png)
6. Close Brave and re-open your session file in your editor of choice
7. Edit the `adblock` > `count` value to be `55555555` (eight fives)
8. Save the file and then launch Brave
9. Verify it shows the days with two digits of precision, like so:
![image](https://cloud.githubusercontent.com/assets/4733304/23817875/ce6cbc98-05b3-11e7-84a0-ed1521ccb601.png)

## Original issue description

**Describe the issue you encountered:**

> The new tab page has been displaying Estimated Time Saved 2 hours for some time now.

https://community.brave.com/t/estimated-time-saved-stuck-at-2-hours/735

I noticed it as well.

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.12.15

- Any related issues:

**Comment by darkdh** [comment]
I feel the same way

**Comment by luixxiul** [comment]
I added the milestone to 0.13.1

**Comment by bbondy** [comment]
How many ads and trackers do you have?

**Comment by bbondy** [comment]
@bradleyrichter this seems like just a UX issue because the next hour limit isn't attained very easily but people still want to see progress.  Removing milestone for now though since I don't believe it to be a bug, but I'd like it to be improved though.

**Comment by bradleyrichter** [comment]
Heh. We will need add minutes.

**Comment by bsclifton** [comment]
Updated the title 😄  It would be good if (whatever the unit is), the next smallest unit could be used as a decimal.  Like 2.5 hours.  Truncating it to "2 hours" is definitely confusing and has caught me making faces like 🤔

**Comment by bbondy** [comment]
Eventually someone will hit days so I think @bsclifton's idea is best, thougths @bradleyrichter ? Just no decimal if it's minutes or smaller.

**Comment by bradleyrichter** [comment]
i think the hour truncation was just a side effect of the overall truncation and yes, we can special-case hours to use a decimal place. This should solve the problem at hand.

**Comment by maaz93** [comment]
Hi guys,

I would like to take this up. 😄  Correct me if I'm wrong about the expectation

```
if time < 1 hour
    stay with current behaviour
else if time < 1 day
    show 1 decimal place for hours
else
    show 1 decimal place for days
```

**Comment by bbondy** [comment]
sgtm, or even 2 decimal places for days. @bradleyrichter thoughts?

**Comment by bradleyrichter** [comment]
This will be fine. Thanks!

**Comment by maaz93** [comment]
Awesome! The final expectation, for future reference:

```
if time < 1 hour
    stay with current behaviour
else if time < 1 day
    show 1 decimal place for hours
else
    show 2 decimal places for days
```

**Comment by luixxiul** [comment]
I thought the fix would be ``7 hours 48 minutes `` with the test case in the 1st post.

To be honest I cannot figure out how long `0.15 day` is, if it is not converted to hours and minutes...
