### ISSUE TITLE
Wallet Currency setting. 

### ISSUE THREAD

**Issue by disruptivesocial** [brave/browser-laptop#6653]
It should be good to  have a setting for preferred currency linke:
about:preferences#payments
currency menu: (Bitcoin|Dollar|Euro)

**Comment by amitkumarj441** [comment]
@bsclifton I'm willing to take up this task, Please let me elaborate about pending task like adding menu of different currencies.
And in which folder should I initiate PRs?

**Comment by bsclifton** [comment]
@amitkumarj441 I believe we had tried to partially implement this feature (auto-detect and then showing the currency symbol), but we ended up rolling it back

pinging @mrose17 for a comment 😄

**Comment by mrose17** [comment]
@amitkumarj441 - thanks! it would be great to have this feature. here's what i suggest:

- use the `currency-codes: 1.1.2` package
- in `app/ledger.js` when the `updateLedgerInfo` function invokes `ledgerGeoIP` and a non-empty result is returned, use the `currency-code` package to determine the default currency to use

the only open issue from the server-side is advertising which currencies are allowed. let me think about that for a bit...

@amitkumarj441 - what do you think?

**Comment by luixxiul** [comment]
@zentagonist stale?
