### ISSUE TITLE
GitHub crashes the tab process

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6656]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Some pages appear to crash the browser tab process. Some do this immediately, others do it after some time. For instance, I repro this on GitHub.com, but only after switching back to Brave after some time.

**Expected behavior:**
Tab processes should not crash for common/popular sites.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version (revision SHA):** 0.13.0 Preview 8

**Steps to reproduce:**
1. Navigate to https://github.com/brave/browser-laptop/issues/6586#issuecomment-272706923
2. Switch to another application for 10 minutes
3. Switch back to Brave and attempt to scroll up/down for a few seconds

**Screenshot if needed:**

**Any related issues:** #6557

**Comment by darkdh** [comment]
quick way to reproduce:
1. open two tabs of https://github.com/brave/browser-laptop/issues/6586#issuecomment-272706923
2. keep switching tabs and make scrolling repeatedly

**Comment by darkdh** [comment]
This is huge amount of memory leak on renderer and it exceeds the limit so sandbox kill the process with `SBOX_FATAL_MEMORY_EXCEEDED (7012)`
