### ISSUE TITLE
Can't Access LastPass Account Settings on Ubuntu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6657]
**Describe the issue you encountered:**

https://community.brave.com/t/cant-access-lastpass-account-settings/731

> Looks like that tool doesn't have Ubuntu support. There's not much to record anyway - just clicking the settings creates the error. 
> 
> <img src="https://cdn-standard2.discourse.org/uploads/brave/original/1X/274e336cfc1732d1ae445daeabd372feb15b2a95.png" width="489" height="207">
>
> On a related note, if I click the "sharing center" on the left navigation bar in the vault, it just displays an error bar at the top of the screen saying "Errorsessionmsg"
>
> <img src="https://cdn-standard2.discourse.org/uploads/brave/original/1X/6db98ac54ca6e9d76ad80ba227850330a678671c.png" width="294" height="86">

**Expected behavior:** 

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu

- Brave Version (revision SHA): 

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Getting similar error on Windows 10 with Preview 8 build
![image](https://cloud.githubusercontent.com/assets/17010094/21982586/ef8b3f10-dbe4-11e6-9bad-ec603560d26e.png)

STR:

1. Login to Lastpass from the widget, color changes to red(successful login)
2. Open Lastpass Vault from widget, opens in new tab
3. Select any of the stored sites and launch, site opens in new tab 
4. Once logged in, Lastpass widget becomes yellow
5. Click on the widget shows the above error

**Comment by bbondy** [comment]
I just updated this extension, but I'm not sure if it will help.
Could you try clearing out your entire profile directly to ensure you have the latest and confirm? 
Also please try against 0.12.15 to make sure it is only 0.13.0 and that the new one works with 0.12.15. Thanks!

**Comment by luixxiul** [comment]
@bbondy I'm not sure as I have neither experienced nor tested it. I'll ask the user anyway.

**Comment by jlopp** [comment]
I'm running 0.12.15 which was the initial install of Brave on this machine. It's not clear to me how to update the LastPass extension - can you link me to documentation?

**Comment by bbondy** [comment]
it should just auto update by now, so I'm assuming it's still working :)

**Comment by jlopp** [comment]
I'm not sure how to tell myself, but I'm still experiencing the issue.

**Comment by jlopp** [comment]
After updating to 0.13.1 this issue appears to be resolved. :+1:

**Comment by luixxiul** [comment]
OK then let's close this for now
