### ISSUE TITLE
 “Brave installer for OS X has grown by 20 Mb"

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6658]
The Brave installer (0.13.0 Preview 8) for OS X has grown from approximately 80Mb to over 100Mb. 

Our MO is to investigate when installers grow by a significant amount.

**Comment by bbondy** [comment]
I looked into this but unfortunately there's not much we can do about it currently. It's just us including more of chromium. I shed off a couple MB for obvious node_module stuff we don't need at least in the context of this.

**Comment by bbondy** [comment]
Leaving this in the milestone since code landed for it.
