### ISSUE TITLE
Global zoom level affects devtools on Windows

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6659]
**Describe the issue you encountered:**

1 Open about:preferences
2 Open Devtool with Inspect Element on the context menu
3 Go back to about:preferences
4 Change the default zoom level
5 Devtool zooms in/out

**Expected behavior:** 5 should not happen

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 7

- Brave Version (revision SHA): 0.13.0 Preview 8

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Note: I will set `release-notes/exclude` if the bug is fixed by 0.13.0

**Comment by bsclifton** [comment]
@luixxiul this feature is present in Chrome... you can trigger by pressing Ctrl and + (zoom in) or Ctrl and - (zoom out). Same with macOS, except with Cmd

However, having it triggered by going to about:preferences... I cannot repro this.  Can you please try again on the latest RC? It may be Windows only

Here's a pic of Chrome. Having zoomable dev tools is important.  However, it should not be linked in any way to the preferences setting:
![screen shot 2017-01-25 at 11 07 22 pm](https://cloud.githubusercontent.com/assets/4733304/22321655/c92a58a8-e353-11e6-97ad-3978086860d9.png)

**Comment by luixxiul** [comment]
@bsclifton thanks for checking. let's close this then :-)

**Comment by bsclifton** [comment]
@luixxiul if you're able to trigger this via preferences, I think it's a legit bug; it sounds like it's:
- Windows only
- Happens when you change global zoom level (which shouldn't affect dev tools, IMO)

I'll re-open and update the issue name.  Can you try on the latest RC?

**Comment by luixxiul** [comment]
> this didn't happen with previous releases?

I'm not quite sure but I don't think so.

And with the latest release the issue cannot be reproduced.

**Comment by bsclifton** [comment]
Awesome- let's close it up 😄
