### ISSUE TITLE
Include links to the guidelines in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6660]
**Describe the issue you encountered:**

The links to guidelines for adding/changing the code need adding in README.md and CONTRIBUTING.md to avoid cases like #6084

**Expected behavior:**

- [x] In README.md, include `See docs/style.md for information on styling`

- [x] Under "Making changes" in CONTRIBUTING.md, include that on styling we only accept changes using Aphrodite, linking to `docs/style.md`

- Any related issues:

The guidelines should be explicitly shared not only among the members but also the community. I think updating the information and adding the link to it will help doing so.

**Comment by bsclifton** [comment]
partially fixed with https://github.com/brave/browser-laptop/pull/6661; updated the checkboxes above

**Comment by luixxiul** [comment]
Lovely, thanks :-D

**Comment by bsclifton** [comment]
@luixxiul were you wanting me to make the 2nd change? (to contributing.md?)

**Comment by luixxiul** [comment]
yes if you don't mind. My English sounds not so native I'm afraid. thanks in advance :pray:
