### ISSUE TITLE
Automated test failures on bookmarkToolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6663]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/192196021#L4577

- [x]  1) bookmarksToolbar when clicking a bookmark folder hides context menu when mousing over regular bookmark:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
- [x]  2) bookmarksToolbar when clicking a bookmark folder "after each" hook for "hides context menu when mousing over regular bookmark":
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

https://travis-ci.org/brave/browser-laptop/builds/197222628#L4660
https://travis-ci.org/brave/browser-laptop/builds/197213036#L4692
https://travis-ci.org/brave/browser-laptop/builds/197205697#L4647
https://travis-ci.org/brave/browser-laptop/builds/197196928#L4656

- [ ]  2) bookmarksToolbar display favicon on bookmarks toolbar display bookmark favicon for url that has it:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at execute(<Function>) - brave.js:413:19

**Expected behavior:**

- Any related issues: #6408

**Comment by luixxiul** [comment]
@bbondy will you take a look at this if you don't mind?

**Comment by bbondy** [comment]
I was just commenting that these are the most common failures in slack :)

**Comment by luixxiul** [comment]
I'm the winner!!

**Comment by bbondy** [comment]
I think these are fixed here
https://github.com/brave/browser-laptop/commit/7670206eae13f6d9c798366d5510e1045688f60f

https://github.com/brave/browser-laptop/commit/415e34324054af2a56a9521b94b8f1726ff68b05

**Comment by alexwykoff** [comment]
These are the currently failing tests: 

```
bookmark tests bookmarks pages without title "before all" hook:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at execute(<Function>) - brave.js:510:19

bookmarksToolbar display favicon on bookmarks toolbar display bookmark favicon for url that has it:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at execute(<Function>) - brave.js:510:19

```
They were ran repeatedly with a failing result.

**Comment by alexwykoff** [comment]
Double-check this @alexwykoff 😸

**Comment by luixxiul** [comment]
Closing as fixed & stale
