### ISSUE TITLE
Automated test failures on sessionStore

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6664]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/192264129#L4577

- [ ] 1) sessionStore state is preserved "before all" hook:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getUrl() - brave.js:205:40

- [ ] 2) sessionStore state is preserved "after all" hook:
     RuntimeError: Couldn't connect to selenium server
      at windowHandles() - brave.js:177:32
      at electron.remote.app.quit() - application.js:72:5

**Expected behavior:**

- Any related issues: #6663 #6408

**Comment by cezaraugusto** [comment]
Passing on https://travis-ci.org/brave/browser-laptop/builds/211610043#L3534, closing
