### ISSUE TITLE
Hover switches tab after x seconds

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6665]
**Describe the issue you encountered:**

https://community.brave.com/t/new-preference-hover-switches-tab-after----seconds/718

> [o] Hover switches tab after _2_ seconds

The number may be changed

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.12.15

- Any related issues:

**Comment by NejcZdovc** [comment]
@luixxiul is this confirmed? Should I implement it?

**Comment by luixxiul** [comment]
No, it's just a suggestion.

CC @bbondy for decision whether it should be implemented or wontfix.

**Comment by lifeinchords** [comment]
Great suggestion. Moving the cursor around the screen often triggers the preview. The preview is great, but not on all the accidental fires. A short delay 1-2 secs would fix this. 

# of secs could also be a text field option in Preferences.

**Comment by luixxiul** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/8860.
