### ISSUE TITLE
Automated test failures on navigationBar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6666]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/192432414#L4628

- [x]  1) navigationBar tests submit page that does not load "after each" hook for "sets location to new URL":
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

https://travis-ci.org/brave/browser-laptop/builds/191866157#L4656

- [x] 3) navigationBar tests submit with url input value with regards to the webview urlbar shows webview url when focused:
     Error: Promise was rejected with the following reason: timeout

https://travis-ci.org/brave/browser-laptop/builds/192264129#L4594
https://travis-ci.org/brave/browser-laptop/builds/192161572#L4590

- [x]  5) navigationBar tests lockIcon Temporarily allow/deny running insecure content:
     WaitUntilTimeoutError: element ([data-l10n-id="mixedConnection"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="mixedConnection"]") - waitForVisible.js:37:22

https://travis-ci.org/brave/browser-laptop/builds/191944045#L4584

- [x]   2) navigationBar tests lockIcon Limit effect of running insecure content in private frame:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

https://travis-ci.org/brave/browser-laptop/builds/192263964#L4580

- [x]  1) navigationBar tests auto open bookmarks toolbar for the first bookmark should remain hidden if user has bookmarks but has toolbar hidden:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

Already captured here: https://github.com/brave/browser-laptop/issues/6408#issue-197378714

- [x]  navigationBar tests navigation document.write spoofing updates the location in the navbar to blank:
     Error: Promise was rejected with the following reason: timeout

- [x]  navigationBar tests change tabs "after all" hook:
     RuntimeError: unknown error: window[requireName] is not a function
      at url() - getUrl.js:29:28
      at execute(<Function>, "app", "quit", , "devTools") - api.js:265:21

https://travis-ci.org/brave/browser-laptop/builds/197205697#L4665
https://travis-ci.org/brave/browser-laptop/builds/197213036#L4708
https://travis-ci.org/brave/browser-laptop/builds/197222628#L4664

- [x]  5) navigationBar tests navigation page without a title does not have title mode:
     Error: element (#navigator .loadTime) still not existing after 10000ms

https://travis-ci.org/brave/browser-laptop/builds/197222628#L4668
https://travis-ci.org/brave/browser-laptop/builds/197216157#L4685
https://travis-ci.org/brave/browser-laptop/builds/197213036#L4716
https://travis-ci.org/brave/browser-laptop/builds/197205697#L4669
https://travis-ci.org/brave/browser-laptop/builds/197196928#L4656

- [x]  4) navigationBar tests auto open bookmarks toolbar for the first bookmark should remain hidden if user has bookmarks but has toolbar hidden:
     WaitUntilTimeoutError: element (#navigator .removeBookmarkButton) still not existing after 10000ms
      at isExisting("#navigator .removeBookmarkButton") - waitForExist.js:37:22

**Expected behavior:**

- Any related issues: #6408 #6663 #6664

**Comment by luixxiul** [comment]
https://travis-ci.org/brave/browser-laptop/builds/193673535#L4588

````
  1) navigationBar tests themeColor Uses the default tab color when one is not specified:
      AssertionError: 'rgba(0,0,0,0)linear-gradient(white,rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box' == 'rgba(0,0,0,0)linear-gradient(rgb(255,255,255),rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box'
      + expected - actual
      -rgba(0,0,0,0)linear-gradient(white,rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box
      +rgba(0,0,0,0)linear-gradient(rgb(255,255,255),rgb(243,243,243))repeatscroll0%0%/autopadding-boxborder-box
````

**Comment by luixxiul** [comment]
https://travis-ci.org/brave/browser-laptop/builds/197205697#L4665
https://travis-ci.org/brave/browser-laptop/builds/197213036#L4708
https://travis-ci.org/brave/browser-laptop/builds/197222628#L4664

- [ ]  5) navigationBar tests navigation page without a title does not have title mode:
     Error: element (#navigator .loadTime) still not existing after 10000ms

**Comment by bsclifton** [comment]
Failing in master currently:
```
npm run test -- --grep="navigationBar tests submit page that does not load resets URL to previous location if page does not load
```

**Comment by cezaraugusto** [comment]
Missing first 3 reported. Checked all described as passing, for comments on this thread as well:

Ref: https://travis-ci.org/brave/browser-laptop/builds/211610043#L3534

**For https://github.com/brave/browser-laptop/issues/6666#issuecomment-274143342:**
https://travis-ci.org/brave/browser-laptop/builds/211610043#L3851

**For https://github.com/brave/browser-laptop/issues/6666#issuecomment-277902413**
https://travis-ci.org/brave/browser-laptop/builds/211610043#L3864

**Comment by diracdeltas** [comment]
I haven't see navigationBar test failures recently

**Comment by alexwykoff** [comment]
confirmed, no navigation bar issues remain. closing.
