### ISSUE TITLE
Automated test failures on bookmark

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6667]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/192264129#L4586

bookmark tests menu behavior 

- [ ]  3) bookmark tests menu behavior rebuilds the menu when add a list of items:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
- [ ]  4) bookmark tests menu behavior "after all" hook:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

https://travis-ci.org/brave/browser-laptop/builds/192155156#L4586

bookmark tests bookmarks pages

- [ ]  1) bookmark tests bookmarks pages with title saved with a title and then removed removes the bookmark from the toolbar:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
- [ ]  2) bookmark tests bookmarks pages with title "after all" hook:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

https://travis-ci.org/brave/browser-laptop/builds/197222628#L4656
https://travis-ci.org/brave/browser-laptop/builds/197216157#L4663
https://travis-ci.org/brave/browser-laptop/builds/197213036#L4688
https://travis-ci.org/brave/browser-laptop/builds/197205697#L4643
https://travis-ci.org/brave/browser-laptop/builds/197196928#L4652

- [ ]  1) bookmark tests bookmarks pages without title "before all" hook:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at execute(<Function>) - brave.js:413:19

**Expected behavior:**

- Any related issues: #6663 #6408

**Comment by alexwykoff** [comment]
most of these tests pass or are covered by https://github.com/brave/browser-laptop/issues/6663

closing in favor of https://github.com/brave/browser-laptop/issues/6663
