### ISSUE TITLE
Automated test failures on pinnedTabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6668]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/192101581#L4581

- [x]  3) pinnedTabs Gets pins from external windows "before all" hook:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:195:32

Already captured here: https://github.com/brave/browser-laptop/issues/6408#issue-197378714

- [x]  pinnedTabs Pins an existing frame creates when signaled:
     Error: element (.tab.isPinned[data-frame-key="2"]) still not existing after 5000ms

- [x]  pinnedTabs Pins an existing frame unpins and creates a non-pinned tab:
     WaitUntilTimeoutError: element (.tab:not(.isPinned)[data-frame-key="2"]) still not existing after 5000ms
      at isExisting(".tab:not(.isPinned)[data-frame-key="2"]") - waitForExist.js:37:22

- [x]  pinnedTabs Closing pinned tabs close attempt retains pinned tab and selects next active frame:
     WaitUntilTimeoutError: element (.tab.active[data-frame-key="3"]) still not existing after 5000ms
      at isExisting(".tab.active[data-frame-key="3"]") - waitForExist.js:37:22

**Expected behavior:**

- Any related issues: #6408

**Comment by cezaraugusto** [comment]
All tests pass on master (SHA b5eb333) so I'm going to close.

```
npm run test -- --grep="Gets pins from external windows"
```

```
      ✓ creates when signaled (159ms)
      ✓ disappears when signaled externally (146ms)
      ✓ Adding a site that already exists does not add another pinned tab (57ms)
      ✓ Adding a site with a diff session that already exists is allowed (303ms)
```
