### ISSUE TITLE
Clarify that 0.13.0 does not support torrent link files

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6672]
**Describe the issue you encountered:**

In release notes let's clarify that 0.13.0 does not support torrent link files, as "we started supporting webtorrent" sounds like that Brave started supporting them and definitely we will get false complaints on https://community.brave.com/

**Expected behavior:** 

- Any related issues: #6671 #3256 

CC @alexwykoff

**Comment by bbondy** [comment]
are you sure it doesn't? I think it does once the feature is working.

**Comment by luixxiul** [comment]
I thought so based on https://docs.google.com/document/d/1d_NXJp05gGcy8kYYDcntIRPQaDrvU3CUF-QjEpf0PLI/edit 
Has this been updated?

**Comment by bbondy** [comment]
OK I think it will be supported if it makes it in, but please keep an eye on for when the changelog is generated, it might be fully excluded completely if we don't get it in for this release. I think we can close this and track when the changelog lands.
