### ISSUE TITLE
Setting clear browser data on close doesn't clear history entry after restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6673]
**Did you search for similar issues before submitting this one?**
Yes, Didn't find similar one

**Describe the issue you encountered:**
Setting clear browser data on close doesn't clear history entry after restart

**Expected behavior:**
Should clear history entries upon restart when clear browser data switch is turned on 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	dc4f0fd
Verified on 0.12.15 works fine. Not checked on previous 0.13.0 builds

- Steps to reproduce:
    1. Clear browser history
    2. Set Browsing history. Cached images and files, All site cookies under security to clear upon closing Brave
    3. Visit any site to add a history entry in about:history
    4. Close and restart the browser
    5. History entry from step 3 is still shown even though clear browsing data is set to clear upon close

- Screenshot if needed:
![history](https://cloud.githubusercontent.com/assets/17010094/21982380/f1e28bfc-dbe3-11e6-90dd-c468a9aea16d.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6678#issue-201034052
