### ISSUE TITLE
Pressing delete/backspace in URL bar jumps cursor to the end

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6674]
**Did you search for similar issues before submitting this one?**
Yes, didnt find similar

**Describe the issue you encountered:**
Pressing delete/backspace in URL bar jumps cursor to the end

**Expected behavior:**
Should retain the cursor position

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x46

- Brave Version (revision SHA):
Brave	0.13.0
rev	dc4f0fd
Verified on 0.12.15, cursor position is retained.

- Steps to reproduce:
    1. Open a new tab
    2. Type some text in the URL bar
    3. Navigate in between or start of the typed text 
    4. Delete a character from the typed text 
    5. Cursor jumps to end of entered text

- Screenshot if needed:
![urlhome](https://cloud.githubusercontent.com/assets/17010094/21984092/2c8dae96-dbec-11e6-9d6a-20c83f3d3982.gif)

- Any related issues:

**Comment by bbondy** [comment]
This seems to be fixed already with preview 9 so closing it, please re-open if you see it in the next build though.

**Comment by luixxiul** [comment]
Test plan: available on the 1st post.
