### ISSUE TITLE
Clear data per site/domain

### ISSUE THREAD

**Issue by hmrodrigues** [brave/browser-laptop#6677]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
There's no option to delete browsing data per website.
As I work with WebApps, sometimes I need to delete cookies while I do tests, but I can't delete only the cookies I wan't. Or I delete everything or don't delete any.

**Expected behavior:**
Option to delete browsing data per site/domain

**Comment by tonsimple** [comment]
Dear Brave developers, it's doable in Chromium so please add this to brave too :(

**Comment by echosa** [comment]
I submitted this to the community forum about a month ago, as well. 

https://community.brave.com/t/clear-cookies-and-cache-for-only-one-site/1493

**Comment by dillbyrne** [comment]
It would be nice to have an automatic way to do this so I could have all site data deleted once the last tab for that site is closed and only saved when I have added an exception for a particular domain. Like the self destructing cookies addon but with all the saved data.

**Comment by bsclifton** [comment]
@eljuno #1991 would be a sub-set of this; this ticket is meaning to include any other site data (local storage, etc)

This functionality is available in Chromium and we'll be getting it when we make the switch over to Brave Core

**Comment by bsclifton** [comment]
Closing as `wontfix` since we'll get this when switching to the Chromium UI

**Comment by lrettig** [comment]
Has this switch happened? I still don't see this feature today. Thanks.

**Comment by Liunkae** [comment]
@lrettig No, the update has not been released yet. The update is currently available for testing, though: https://brave.com/download-dev
