### ISSUE TITLE
Closing any tab moves focus to last one

### ISSUE THREAD

**Issue by szpecku** [brave/browser-laptop#668]
Brave for OSX
Version: 0.7.13
Electron: 0.36.7
libchromiumcontent: 47.0.2526.110

Scenario:

1. Open few tab
2. Choose non-last tab
3. Close any tab (no matter which one)

Expected:
1. When current tab is being closed, move to previous tab or stay on the same tab, when another is being closed

Occured:
1. When any tab is being closed, focus always moves to last tab.

**Comment by bradleyrichter** [comment]
@bbondy should be fixed in latest? Right?

**Comment by bbondy** [comment]
nope this one is slightly different.
