### ISSUE TITLE
Clicking on block script icon doesn't show notification  to allow scripts to be loaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6680]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Clicking on block script icon doesn't show notification to allow loading of scripts

**Expected behavior:**
Should show the message to allow scripts to be loaded

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	dc4f0fd
Verified on 0.12.15 shows notification to allow scripts to be load

- Steps to reproduce:
    1. Visit https://brainbondy.com
    2. Enable Block scripts from shields
    3. Click on the Block script icon in URL bar, nothing happens

- Screenshot if needed:
![blockscript](https://cloud.githubusercontent.com/assets/17010094/21988755/4d54751a-dc00-11e6-8435-50dd9903ad11.gif)

- Any related issues:

**Comment by luixxiul** [comment]
I unintentionally introduced the regression here: https://github.com/brave/browser-laptop/commit/19360c107c21d4693b782169ec5d583e31767261#diff-02c4b23ad267fe636760179e32fa29ceR842

**Comment by luixxiul** [comment]
Test plan: https://github.com/brave/browser-laptop/pull/6681#issue-201059012
