### ISSUE TITLE
Deleting engine go key doesn't remove the Search engine icon from URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6683]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Deleting engine go key doesn't remove the Search engine icon from URL bar

**Expected behavior:**
Should remove the search engine icon and replace with magnifier icon

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	dc4f0fd
Verified on 0.12.15, pressing back space changes the search engine icon to magnifier icon

- Steps to reproduce:
    1. Open a new tab
    2. Type any of the search engine go key and press space to show the search engine favicon in URL bar
    3. Press back space and delete the engine go key, but icon still remains

- Screenshot if needed:
![autofillsuggestion](https://cloud.githubusercontent.com/assets/17010094/21991786/e49455b6-dc0b-11e6-9f26-19a473ddc1d1.gif)

- Any related issues:
cc: @bsclifton

**Comment by bbondy** [comment]
I'll take, probably from the refactor.
