### ISSUE TITLE
Flash content not loading on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6687]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Flash content not loaded even after enabling flash in settings

**Expected behavior:**
Should show placeholder and when right click allow should load flash content 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	dc4f0fd

- Steps to reproduce:
    1. Visit http://www.y8.com/games/superfighters
    2. Right click on the flash placeholder and select Allow/Allow for 1 week
    3. Flash content is not loaded

- QA Steps:
    1. Visit http://www.y8.com/games/superfighters
    2. Right click on the flash placeholder and select Allow/Allow for 1 week
    3. Flash content should load

- Screenshot if needed:
![flash](https://cloud.githubusercontent.com/assets/17010094/21993900/0c058ce2-dc15-11e6-83f2-eb420a2cb17f.gif)

- Any related issues:

**Comment by srirambv** [comment]
Windows specific issue. @alexwykoff  confirmed flash working on OS X

**Comment by srirambv** [comment]
Flash content loads after restart. #6774 logged for restart notification for flash

**Comment by luixxiul** [comment]
I added `QA/no qa needed` label as the test plan for this was covered by #6739
