### ISSUE TITLE
Specify QA steps as clearly and simply as possible (0.13.0)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6688]
**Describe the issue you encountered:**

Because 0.13.0 will be one of the most massive releases, I would like to ask those who have contributed to the release to add the test plan to the issues as clearly and simply as possible, in order to make the QA work easier. There are already [190 issues](https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AQA%2Fsteps-specified%20is%3Aclosed%20milestone%3A0.13.0%20) to be checked, so specifying plans clearly will help a lot.

I looked through all of the issues whose milestone is set to 0.13.0, and I added the label `QA/steps-required` to the issues where it is hard to find the plan or it seems to be unavailable:
https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AQA%2Fsteps-required%20milestone%3A0.13.0%20

If the plan is specified in a new comment on each issue, please replace `QA/steps-required` with `QA/steps-specified`.

If QA is not required at all, please replace it with `QA/no-qa-needed`.

Note: QA work will ONLY be done for issues labelled with `QA/steps-specified` (#6662). The issues labelled with `QA/steps-required` or `QA/no-qa-needed` will be ignored during QA tests.

**Expected behavior:**

The number of https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AQA%2Fsteps-required%20milestone%3A0.13.0%20 should be reduced to zero.

- Any related issues: #6662

**Comment by luixxiul** [comment]
Normally we won't have an issue like this, unless the release which is as large as 0.13.0 is released

**Comment by luixxiul** [comment]
Only 1 item lacks QA steps: https://github.com/brave/browser-laptop/issues/5974#issue-192964213

**Comment by bbondy** [comment]
released, so closing.
