### ISSUE TITLE
Feature Request: Set as default browser.

### ISSUE THREAD

**Issue by Sweetie-Belle** [brave/browser-laptop#669]
Title is self-explanatory.

Would be nice to be able to set brave as default browser without having to manually edit config.

**Comment by bbondy** [comment]
Dupe of https://github.com/brave/browser-laptop/issues/429
This is already working on OSX but pending on Windows.

**Comment by mandarvaze** [comment]
Am on OSX, Brave version 0.7.15
Can't see the option yet under preferences.
Did you mean "coding for OSX done" (But not yet released) ?

**Comment by bbondy** [comment]
You can change the default browser in the system settings. We have an issue on file here:
https://github.com/brave/browser-laptop/issues/813 to get it into preferences.  So you're right that it's not in preferences yet.
