### ISSUE TITLE
Context menu may fail to open

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6690]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Right-clicking on an input field (after logging into LastPass?) yields no context menu. An error is logged in the application console.

```
menuUtil.js:164 Uncaught TypeError: Reduce of empty array with no initial value(…)
```

Call Stack:
```
module.exports.sanitizeTemplateItems.template @ menuUtil.js:164
getEditableItems @ contextMenus.js:661
mainTemplateInit @ contextMenus.js:980
onMainContextMenu @ contextMenus.js:1230
webview.addEventListener.e @ frame.js:616
GuestViewContainer.dispatchEvent @ extensions::guestViewContainer:178
dispatchEvent @ extensions::guest-view-internal:78
(anonymous function) @ extensions::guest-view-internal:84
target.(anonymous function) @ extensions::SafeBuiltins:19
EventEmitter2.emit @ extensions::event_emitter:43
target.(anonymous function) @ extensions::SafeBuiltins:19
ipcRenderer.emit @ extensions::ipc_utils:31
```

**Expected behavior:**
The context menu should not be prevented from appearing.

**Brave Version (revision SHA):** https://github.com/brave/browser-laptop/commit/dc4f0fd4c16a71ba80687581d97f35884dfc92d4

**Steps to reproduce:** (Not reliable)
1. Enable LastPass (don't log in)
2. Navigate to https://twitter.com/login
3. Sign into LastPass
4. Right-click username field

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by bsclifton** [comment]
@jonathansampson I think this has been fixed... Can you please retest? 😄
