### ISSUE TITLE
Automated test failures on notificationBar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6694]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/192432414#L4632

- [ ]  2) notificationBar "before all" hook:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowByUrl("chrome://braveapp/extensions/brave/index.html") - brave.js:240:21

- [ ]  3) notificationBar "after all" hook:
     RuntimeError: Couldn't connect to selenium server
      at windowHandles() - brave.js:177:32
      at electron.remote.app.quit() - application.js:72:5

**Expected behavior:**

- Any related issues: #6408

**Comment by diracdeltas** [comment]
i haven't seen this lately so seems like it may be fixed

**Comment by bbondy** [comment]
I think I fixed this a while ago
