### ISSUE TITLE
Add QA steps in ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6695]
**Describe the issue you encountered:**

As the QA work starts from the issues instead of the PRs, "QA steps:" should be added under "Steps to reproduce:" in ISSUE_TEMPLATE.md

**Expected behavior:**

````
...

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.

- QA steps:
    1.
    2.
    3.

- Screenshot if needed:

...
````

- Any related issues:

**Comment by bbondy** [comment]
updated here:
https://github.com/brave/browser-laptop/commit/986387e82b8bfa59ada64b531dc06873fdbb6bda
