### ISSUE TITLE
Import bookmark causes Brave to hang momentarily before showing successful import

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6699]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Import bookmark causes Brave to hang momentarily before showing successful import

**Expected behavior:**
Should not hang when importing bookmark html file 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	105a1a7
Verified on preview 8 doesn't hang when importing bookmarks

- Steps to reproduce:
    1. Do a clean install of 0.13.0 Preview 9
    2. Import a bookmark HTML file
    3. Browser hangs and shows not responding before showing successful import message

- QA Steps
    1. Do a clean install of 0.13.0 Preview 9
    2. Import a bookmark HTML file
    3. Browser should not hang and should show not responding message on the browser window

- Screenshot if needed:
![import bookmarks](https://cloud.githubusercontent.com/assets/17010094/22021290/38157dc0-dcb4-11e6-8232-e6b97c5ffaab.gif)

- Any related issues:
cc: @darkdh

**Comment by bbondy** [comment]
This doesn't hang for me when I import all of my chrome bookmarks. My file to import's line count is 628.

**Comment by bbondy** [comment]
I'm thinking the sites refactor that @darkdh will fix this lag and I think that this is not new to 0.13.0. I'm going to remove the milestone but please chime in if you disagree.

**Comment by darkdh** [comment]
I used the same bookmark file as issue stated. can't reproduce either on preview9 or master

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
