### ISSUE TITLE
New Tab context menu is retained even after clicking one new tab button

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6700]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
New Tab context menu is retained even after clicking one new tab button

**Expected behavior:**
Context menu should get closed if the new tab button is clicked

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	105a1a7
Existing behavior since 0.12.10

- Steps to reproduce:
    1. Right click/long press on new tab button to show the context menu
    2. Click on the new tab icon, the context menu is retained and not dismissed
    3. Right click/long press on new tab button to show the context menu
    4. Click on other existing tab or anywhere else in the browser, context menu is closed

- QA Steps:
    1. Right click/long press on new tab button to show the context menu
    2. Click on the new tab icon, the context menu should be closed
    3. Right click/long press on new tab button to show the context menu
    4. Click on other existing tab or anywhere else in the browser, context menu should be closed

- Screenshot if needed:
![newtabcontext](https://cloud.githubusercontent.com/assets/17010094/22023884/f3025620-dcbf-11e6-9662-40c8ca2ad6d3.gif)

- Any related issues:
Please change milestone if required

**Comment by srirambv** [comment]
Same with hamburger menu as well. When hamburger menu is clicked and then clicked on the tabs bar the menu is not closed. Only if clicked outside tabs bar then the menu closes

**Comment by Liunkae** [comment]
I think this was fixed with #7748 (native context menu).

**Comment by bsclifton** [comment]
@Liunkae yes- you are correct 😄
