### ISSUE TITLE
Add tab dropdown cropped when + button on far righthand side

### ISSUE THREAD

**Issue by jhreis** [brave/browser-laptop#6701]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

When tab bar is full, and the add tab button (+) is on the far right, the dropdown associated with it (click and hold) still goes to the right. Since there is no additional room to the right, it ends up being cropped.

**Expected behavior:**

Dropdown would right-align with the browser, and still be entirely visible.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS Sierra (10.12.1)

- Brave Version (revision SHA):

0.12.15

- Steps to reproduce:
    1. Fill tab bar until the "+" add new tab button is to the far right
    2. Click and hold on it to view dropdown
    3. Observe that dropdown goes outside the browser bounds, and ends up being cropped

- Screenshot if needed:

<img width="296" alt="drop down cropped" src="https://cloud.githubusercontent.com/assets/2781690/22024780/1fd1405c-dc99-11e6-8a2d-af8107847df2.png">

- Any related issues:

**Comment by srirambv** [comment]
fix is part of 0.13.0 
Same as #5763

**Comment by srirambv** [comment]
Closing #6701
