### ISSUE TITLE
Top site tiles deleted when clearing browsing data 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6702]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Top site tiles deleted when clearing browsing data 

**Expected behavior:**
Should retain the top site tiles

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	105a1a7
Checked on 0.12.15, top site tiles are retained when browsing data is cleared

- Steps to reproduce:
    1. Ensure there are top site tiles on a new tab 
    2. Press Ctrl+Alt+Del to bring clear browser data modal
    3. Select Browsing history, cached data and cookies switch
    4. Top tiles disappear the moment the modal closes 

- QA Steps:
    1. Ensure there are top site tiles on a new tab 
    2. Press Ctrl+Alt+Del to bring clear browser data modal
    3. Select Browsing history, cached data and cookies switch
    4. Ensure top site tiles are retained when modal closes and after browser restart  

- Screenshot if needed:
![toptiles](https://cloud.githubusercontent.com/assets/17010094/22032788/df452e78-dcdd-11e6-87d2-e0fbb50936bc.gif)

- Any related issues:
Not exactly like #6067
cc: @cezaraugusto

**Comment by bsclifton** [comment]
Caused by https://github.com/brave/browser-laptop/commit/ef4db760a850811261a80e90330e8fddba43382f

cc: @darkdh @bbondy

**Comment by darkdh** [comment]
@bsclifton , I think it is cause by https://github.com/brave/browser-laptop/commit/daeeb2997
https://github.com/brave/browser-laptop/commit/ef4db760a850811261a80e90330e8fddba43382f must be triggered by restart
So if we want to retain it, we must change from both of them

**Comment by bsclifton** [comment]
@darkdh ah- good call! I completely missed that when reviewing :smile:

**Comment by cezaraugusto** [comment]
IMO if user resolves to clear all browser data, losing default sites' doesn't seem as an issue but expected behaviour.

**Comment by srirambv** [comment]
@cezaraugusto Isn't the idea behind top sites tiles on new tab is to show the most frequent visited sites irrespective of whether the use clears browsing data or not? Its fine to remove the tiles if something like a browser reset is done which restores defaults, but top site tiles should be retained irrespective of whether user clears browsing data or not.  Since we don't have option to clear site specific data yet, the only option is to clear complete browsing data and it removes the top site tiles which I think should be avoided.

**Comment by tallfunnyjew** [comment]
I'll give a +1 to @srirambv on this issue for two reasons:

1. Clearing a browser cache (places to which you've already surfed) and clearing a set of dashboard shortcuts (place to which you'd like to surf in the future) are not the same thing to this end user.
2. I can't find any pages on the wiki/Brave's community website that specifically calls this out.

My ask: 

Can the programmers separate those two functions? If so, can you please update the wiki and/or Brave's pref pane to make that clear? 

Alternately, if Brave's team decides to keep this setting, can you please make that clear in the wiki and in the Pref Pane that governs that behavior? 

Something along the lines, perhaps, of this:

<img width="895" alt="brave prefs upgrade" src="https://cloud.githubusercontent.com/assets/2782686/26512179/4985e074-421a-11e7-8d00-a9a7a30f1d4b.png">

Thanks for the consideration, gang. Really love the work you're doing and, as a writer and a sysadmin, I'm preaching about this browser all the time. Keep up the great work.

**Comment by LaurenWags** [comment]
+1 from community - https://community.brave.com/t/have-thumb-nails-disappeared-on-the-dashboard/6939
