### ISSUE TITLE
Make entire bookmarkButtonContainer clickable to add/edit a bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6704]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Currently only the bookmark star is clickable to add as a bookmark

**Expected behavior:**
[#6445 comment](https://github.com/brave/browser-laptop/issues/6445#issuecomment-273292636)
>ideally the entire rectangle would be clickable. This is especially important in hi-def desktop views.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Existing behavior in all release

- Steps to reproduce:
    1. Open any page
    2. Click on the bookmark star, page is added as a bookmark
    3. Click away from star but within the container, bookmark hanger is not shown to add/edit bookmark

- Screenshot if needed:
![bookmarkhitarea](https://cloud.githubusercontent.com/assets/17010094/22040030/6383ae88-dcf9-11e6-98cb-2eb31c04412b.gif)

- Any related issues:
cc: @bradleyrichter 
Please change milestone if required

## Test plan

1. Click the star icon to show "Bookmark Added"
2. Click around the icon to show "Edit Bookmark"

**Comment by cezaraugusto** [comment]
Closed with #6712

Test plan

1. Click on any part of the star icon container (bookmark button) on urlBar
2. modal should open by hitting on any part of the button container (not only star icon)
