### ISSUE TITLE
Brave Ledger tune-ups

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6707]
- ~change "URL bar include button" to a different icon~ Fixed with https://github.com/brave/browser-laptop/pull/6862

- add sliders to adjust percentages for contributions

- ~display a rounded version of account balance to avoid exchange rate "jitter" (with the term "approx.")~ Fixed with https://github.com/brave/browser-laptop/pull/6706

- when auto-include=true (the default), after 20 sites are included, present the user with  an artifact inviting them to switch to auto-include=false

**Comment by bsclifton** [comment]
Crossed out the rounding issue after merging https://github.com/brave/browser-laptop/pull/6706

We'll need to create an issue for rounding if we want QA to test it (and then in the issue, include steps to test the fix).

**Comment by bsclifton** [comment]
Also bumping back to 0.13.2; the icon change is easy and can likely be included in 0.13.1 if the assets are provided, but the other two should be broken out to separate issues (and both will likely not be able to make 0.13.1).

**Comment by mrose17** [comment]
OBE by https://github.com/brave/browser-laptop/issues/6874 and https://github.com/brave/browser-laptop/issues/6873
