### ISSUE TITLE
Auto-purging "Saved site settings" resets Payments "Include" toggles

### ISSUE THREAD

**Issue by analogist** [brave/browser-laptop#6708]
**Describe the issue you encountered:**
It seems that the "Include" toggle state in Payments for individual sites does not survive browser restarts, if "Saved site settings and permissions" is set to autopurge on closing Brave.

**Expected behavior:**
I'm actually not sure if this is a technical limitation, but to me it seems like user settings in the about:* domains should survive purge-on-close.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 (v 1607)

- Brave Version (revision SHA):
0.12.15

- Steps to reproduce:
    1. Turn on autopurge "Saved site settings and permissions" in "Security"/"Private Data"
    2. Turn on Brave Payments and form a payment ledger
    3. Toggle off some sites in the ledger with the "Include" toggle
    4. Restart Brave
    5. All sites are toggled back "on" in the "Include" list.

This issue does not seem to occur if "Saved site settings and permissions" is not set to autopurge.

**Comment by mrose17** [comment]
@bradleyrichter - is this the _intended_ behavior? my thinking is that the behavior is _consistent_, but may not be _desirable_. what's your thinking?

**Comment by bradleyrichter** [comment]
My initial thinking and current thinking is that these MUST be separated because it will always surprise people. I think you need 2 options:

The standard and Brave specific:

![image](https://cloud.githubusercontent.com/assets/13509546/22130115/12199528-de5f-11e6-96f6-bb67c71c403c.png)


(not sure if the last switch should combine those data types but it would be more usable. )

**Comment by diracdeltas** [comment]
@bradleyrichter 'brave shields' is essentially the same as 'saved site settings'

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by diracdeltas** [comment]
should the 'Brave payments data' switch clear *all* Brave payments data (resetting it to the state before you turned on Brave payments)?

**Comment by mrose17** [comment]
the only issue with that is the loss of the brave wallet, if the user didn't back up the recovery keys... i suspect it would be better to trim everything back in the synopsis file, most of the ledger state file, and then set the ledger setting to off along with deleting all the site-specific ledger settings...

**Comment by mrose17** [comment]
here is my suggestion:

1. add the additional option "Brave shields and payment data" as shown in https://cloud.githubusercontent.com/assets/13509546/22130115/12199528-de5f-11e6-96f6-bb67c71c403c.png

1. exclude any key starting with `ledger` from being deleted when "Saved site settings and permissions" is cleared.
2. when "Brave shields and payment data" is cleared, reset `ballots` and `transactions`, and remove `paymentInfo` from `ledger-state`
3. when "Brave shields and payment data" is cleared, reset `ledger-scores`, `ledger-publisher` and `ledger-log`
4. when "Brave shields and payment data" is cleared, reset `publishers` from `ledger-publishers`

tasks 2-4 can be accomplished by modifying the correct data structures in `app/ledger.js` and then calling `atomicWriter`...

**Comment by diracdeltas** [comment]
shields should not be tied to payments data IMO. if you are clearing site permissions, you are more likely to want to clear shield settings than if you are clearing payments data.

**Comment by mrose17** [comment]
@bradleyrichter - i agree with @diracdeltas comment, we probably need two more checkboxes, not just one...

**Comment by bsclifton** [comment]
Prework for this done and can be found in the `issues-6708` branch

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/included-websites-are-not-saved-correctly-in-brave-payments/10879

**Comment by NejcZdovc** [comment]
per discussion with @diracdeltas we are pushing this after 1.0
