### ISSUE TITLE
Page title is slightly not centered

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#671]
Measure the pixel count on the left and the right with Commadn+Shift+4
It is off by about 10 pixels I think because of the lock icon.

**Comment by bbondy** [comment]
Happens worse when there's no lock icon because the spacing is also taken for the lock icon but there is no icon there.

**Comment by psimyn** [comment]
conditionally removing minWidth + margin fixes it (assume you meant centered in the entire window)
