### ISSUE TITLE
build failing on macOS

### ISSUE THREAD

**Issue by bobinson** [brave/browser-laptop#6710]
**Did you search for similar issues before submitting this one?** : Yes

Build failing with the following error.

**Expected behavior:** build should pass & should be able to run brave

- Platform : macOS - with latest brew, Python, Xcode, all patches

- Brave Version (revision SHA): HEAD / git clone

- Steps to reproduce:
    1. clone repo
    2. run "npm install"
    3. the same error appears after performing all the trouble shooting tips

**- messages:**
```

> electron-chromedriver@2.0.1 install /Users/b5413b/hack/code/browser-laptop/node_modules/spectron/node_modules/electron-chromedriver
> node ./download-chromedriver.js

Downloading https://github.com/brave/electron/releases/download/v2.0.11/chromedriver-v2.23-darwin-x64.zip failed: invalid relative path: ../LICENSE
brave@0.13.0 /Users/b5413b/hack/code/browser-laptop
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open '/Users/b5413b/hack/code/browser-laptop/node_modules/electron-chromedriver/package.json'
npm WARN eslint-plugin-ava@4.0.1 requires a peer of eslint@>=3.6 but none was installed.
npm WARN tslint@4.3.0-dev.0 requires a peer of typescript@>=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev but none was installed.
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! electron-chromedriver@2.0.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@2.0.1 install script 'node ./download-chromedriver.js'.
```

**Comment by bobinson** [comment]
looks like a similar bug exists on FreeBSD #6161 

additional info:

```
node -v
v6.2.1
```

**Comment by bsclifton** [comment]
Should be fixed now! :smile: @bbondy recreated the chrome driver zip and I confirmed it works as expected

**Comment by bobinson** [comment]
QA passed.

Brave	0.13.0
rev	d7a324a
Muon	2.0.11
libchromiumcontent	54.0.2840.100
V8	5.4.500.41
Node.js	7.0.0
Update Channel	dev
os.platform	darwin
os.release	16.3.0
os.arch	x64
