### ISSUE TITLE
Keyboard input reading is delayed

### ISSUE THREAD

**Issue by michaelswe** [brave/browser-laptop#6713]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When I open a new tab and start typing directly, the first characters are not captured. I.e. I have to wait until tab is fully loaded before typing. This applies to both URL bar and input fields on a web page (for example search input at duckduckgo.com or google.com)

**Expected behavior:**
I want to be able to start typing my URL directly after pressing cmd-n without loosing characters. Chrome manages this fine.

Please make keyboard input a prioritized task and buffer the characters until the new tab is loaded.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave: 0.12.15
os.release: 16.3.0

- Steps to reproduce:
Press cmd-n and immediately start typing. Your first letters won't be captured.

**Comment by Liunkae** [comment]
This is probably the same problem as #6620 (Address field performance is really bad). Closing as a duplicate.
