### ISSUE TITLE
[low] typo error in an error message

### ISSUE THREAD

**Issue by bobinson** [brave/browser-laptop#6717]
console.warn('Could not register magnet URL handler, are oyu using the latest electron?')
oyu instead you in  browser-laptop/app/filtering.js

//cosmetic

**Comment by luixxiul** [comment]
I remember @darkdh has pointed out in an audit commit somewhere

**Comment by bobinson** [comment]
![brave1](https://cloud.githubusercontent.com/assets/18070249/22107707/5d3156b6-de75-11e6-9d3c-273d9b484361.gif)
works fine. 

//QA Done

**Comment by luixxiul** [comment]
@bsclifton I'm re-adding the label as this was actually fixed by a contributor and [0 closed](https://github.com/brave/browser-laptop/milestone/47) looks sad :sob:

**Comment by bsclifton** [comment]
@luixxiul sounds good!

Thanks for the PR, @bobinson! Definitely appreciated :smile:
