### ISSUE TITLE
content scripts should be conditionally included in the renderer process

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#672]
See discussion at https://github.com/brave/browser-laptop/commit/1ed2e176309a9c00fc3c6ea79b89501ecd6b6fdf#commitcomment-15967240

**Comment by bridiver** [comment]
https://developer.chrome.com/apps/tags/webview

**Comment by bbondy** [comment]
Just noting that this should be reverted when this lands:
https://github.com/brave/browser-laptop/commit/446dfe8c1c39203e5f41f9bb6341a2103df1248c
But also need to check that navigating to/from about:preferences to an http page works as expected and doesn't load aboutPreload.js.

**Comment by luixxiul** [comment]
Was this fixed or not?

**Comment by bridiver** [comment]
Yes, everything has been converted to extensions now
