### ISSUE TITLE
LastPass autofill non-functional in private tabs

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#6722]
**Did you search for similar issues before submitting this one?** Yes.

**Describe the issue you encountered:** When using LastPass in a private tab, username and password boxes do not contain the LastPass icons and the Auto Fill functionality does not seem to work.

**Expected behavior:** LastPass integration behaves in private tabs in the same way as normal tabs.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 16.04 LTS

- Brave Version (revision SHA): 0.13.0 (105a1a7)

- Steps to reproduce:
    1. Open private tab.
    2. Navigate to a login page for a site you have stored in LastPass.
    3. Note the lack of LastPass icons within the username/password box.
    4. Note that right-click > LastPass > AutoFill does not seem to function.

**Comment by SimonWaters** [comment]
In Chrome you must explicitly permit an extension to have access to a private tab

chrome://extensions/ "Allow in Incognito mode", is this changed with Brave?

**Comment by DivineOmega** [comment]
It's worth noting this seemed to work fine in version <= 0.12.*.

**Comment by luixxiul** [comment]
Thanks for the info. I set the milestone with the `release/not-blocking` as the number of the Ubuntu users is limited; it's the priority issue.

**Comment by DivineOmega** [comment]
For reference, this issue is still present in Brave 0.13.5.

**Comment by NejcZdovc** [comment]
related to #7080

**Comment by DivineOmega** [comment]
Just tested this issue in Brave 0.14. Still a problem unfortunately.

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/MirkoJankovic/status/939311511327166464
>the username and pass boxes don't contain the LastPass icon

OS: Win 7
Brave: 0.19.105 
rev: 51f8ba56ca1c1409ddd0620b12650bb7f81c2f79 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 6.1.7601 
OS Architecture: x64

**Comment by bbw22** [comment]
Still a problem.

Brave Version
Brave: 0.21.18
V8: 6.4.388.41
rev: 580be78
Muon: 4.8.2
OS Release: 17.4.0
Update Channel: Release
OS Architecture: x64
OS Platform: macOS
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.140

**Comment by swissdean** [comment]
This is still an issue , y'all. 


Brave: 0.22.669 
V8: 6.6.346.24 
rev: 6cda2e84f749e66409e9e3bca63f5796422e7edf 
Muon: 5.2.7 
OS Release: 10.0.14393 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117

**Comment by bsclifton** [comment]
You'll have to go to chrome://extensions and allow use in private tabs, but this is fixed with [brave-core](https://github.com/brave/brave-browser) 😄
