### ISSUE TITLE
Developer Tools lack 'Show all messages' Option

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6725]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The Console tab does not include the _Show all messages_ checkbox.

**Expected behavior:**
Developer tools are largely consistent between Chrome and Brave.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version (revision SHA):** 0.13.0

**Screenshot if needed:**

![image](https://cloud.githubusercontent.com/assets/815158/22092456/47841824-ddc3-11e6-9cd3-b32151f98edf.png)

**Comment by bsclifton** [comment]
Definitely needs some investigation (likely will be something that needs to get passed to the Chromium code); I don't see this making 0.13.1. Moving back to 1.0

**Comment by bsclifton** [comment]
Closing as `wontfix` since this is already fixed with [Brave Core](https://github.com/brave/brave-browser) (coming soon!)
