### ISSUE TITLE
Opening PDF via Wayback Machine archive.org loads different URL

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6726]
**Describe the issue you encountered:**
https://community.brave.com/t/bug-wrong-url-in-address-bar-viewing-pdfs-at-archive-org-wayback-machine/785?u=suguru

> Visiting https://web.archive.org/web/20160106152308/http://stlab.adobe.com/wiki/images/d/d3/Test.pdf in Brave (OSX/0.12.15) displays the PDF – but the address bar shows only the "http://stlab.adobe.com/wiki/images/d/d3/Test.pdf".

**Expected behavior:**
The address should not be changed or the resource should be loaded from the correct origin.

- Brave Version (revision SHA): 0.12.15

- Steps to reproduce:
    1. Open https://web.archive.org/web/20160106152308/http://stlab.adobe.com/wiki/images/d/d3/Test.pdf

- Any related issues:

**Comment by luixxiul** [comment]
@gojomo thanks for your info!

**Comment by diracdeltas** [comment]
nice catch! should be an easy regex fix in https://github.com/brave/browser-laptop/blob/master/js/lib/urlutil.js#L298. if any first-time contributors want to take this, please go ahead.
