### ISSUE TITLE
Add delay before tab resize

### ISSUE THREAD

**Issue by stan-qaz** [brave/browser-laptop#6727]
When closing multiple tabs one at a time the resize happens so quickly that you must reposition the mouse after every tab close to hit the X on  the next tab. 

Having a short delay, at least 2 seconds, after each tab close before the resize code runs would be more user friendly. Then you could position the mouse, close the tab and have the following tab appear in the same location and at the same size. That would let you look and click without having to keep moving the mouse after every tab close.

**Comment by NejcZdovc** [comment]
I think this is duplicate with #6088 and will be fixed in #6342

**Comment by stan-qaz** [comment]
Yes it looks to be the same basic issue, I missed that one in my search. Thanks!
