### ISSUE TITLE
Show Download Button When Playing Media

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6729]
**Describe the issue you encountered:**
The `<video>` (and _presumably_ `<audio>`) element does not show a download button. This realization was made following a discussion on Twitter. See the thread to which [this tweet](https://twitter.com/BrendanEich/status/821952868689190912) belongs.

**Expected behavior:**
A download button would be shown, as it is in Chrome.

**Platform (Win7, 8, 10? macOS? Linux distro?):** Windows 10

**Brave Version (revision SHA):** 0.13.0

**Steps to reproduce:**
1. Navigate to https://media.grc.com/SN/sn-594-lq.mp3
2. Note absence of download button to far-right

**Screenshot if needed:**
_Chrome on top, Brave on bottom_

![image](https://cloud.githubusercontent.com/assets/815158/22095202/9d365ca4-ddd8-11e6-940a-6bcf4e9104ac.png)

**Comment by bbondy** [comment]
I think we'll get this for free once we get to C56 (skipping over 55)

**Comment by bbondy** [comment]
If not once we're on it, pls re-add to milestone.

**Comment by thornjad** [comment]
While it probably shouldn't be a high priority, this may be a parity issue, since I do expect to be able to download media from the browser.

**Comment by jonathansampson** [comment]
This issue is resolved in brave-core:

![download-media](https://user-images.githubusercontent.com/815158/47200486-00d11100-d33c-11e8-9841-4c33285ce6e7.gif)
