### ISSUE TITLE
switch to JSON for HTTPS everywhere

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#673]
https://github.com/EFForg/https-everywhere/pull/4110/files switches upstream over to JSON; we should too when it lands in stable

**Comment by bbondy** [comment]
oh that's great to see!
CC @garvankeeley @SergeyZhukovsky. no Immediate action, but coming down the pipe.

**Comment by bbondy** [comment]
Would like to push for this sooner than later because of reported issues like this:

![screenshot 2016-02-09 12 44 44](https://cloud.githubusercontent.com/assets/831718/12925162/f0fe291a-cf2a-11e5-9b34-1d00707e2d84.png)

**Comment by diracdeltas** [comment]
@jsha says the https everywhere release with this fix is coming later this week

**Comment by diracdeltas** [comment]
if it's not out by friday (or wed?), i can build it myself. @jsha is the next release number 5.1.4?

**Comment by bbondy** [comment]
Waiting for it sounds fine to me since we have a lot of high priority stuff as well currently. Thanks.
