### ISSUE TITLE
"close tabs to the right" or left is very slow

### ISSUE THREAD

**Issue by stan-qaz** [brave/browser-laptop#6730]
With several tabs open the "close tabs to the right" or left is very slow. With 5 tabs open it can take 4-6 seconds for the unwanted tabs to close. More tabs seems to slow things even more.

**Expected behavior:**

Tabs should close, or at least disappear from the UI nearly instantly.

Linux, OpenSuse 42.2
Quad core Xeon & 16 GB of Ram
Quadro K620 video card at 1920x1080

Brave	0.12.15

- Steps to reproduce:
    1. Open a batch of tabs
    2. Select Close tabs to the right or left
    3. Wait several seconds for tabs to close

**Comment by bbondy** [comment]
I think we currently do N operations for each of the N tabs being closed and we need to change this to 1 for state updates.
