### ISSUE TITLE
Double clicking download freezes browser.

### ISSUE THREAD

**Issue by EirikSkogstad** [brave/browser-laptop#6732]
**Did you search for similar issues before submitting this one?**
Yes, did not find any.
**Describe the issue you encountered:**
Double clicking on a download makes the browser freeze.
**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):
0.12.15.0  x64
- Steps to reproduce:
    1. Download a file.
    2. Wait for it to complete
    3. Double click the "download box"

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
How big is the file that you have downloaded? Large file causes the browser to not respond as it is trying to open the file.

**Comment by EirikSkogstad** [comment]
The file i tried to open was 46 MB. I tried now with another file that was 1MB large and the application responded instantly.

**Comment by bbondy** [comment]
there should be no delay no matter how big the file is.

**Comment by luixxiul** [comment]
I think this is stale. Let's reopen the issue if we start seeing the issue again.
