### ISSUE TITLE
Buttons on Torrent viewer needs spacing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6735]
## Test plan

https://github.com/brave/browser-laptop/pull/7679#issue-213703680

----

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Buttons on Torrent viewer are stuck to each other

**Expected behavior:**
Buttons on Torrent viewer needs spacing

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	c60b783

- Steps to reproduce:
    1. Visit https://codepen.io/ferossity/full/qaezaB/
    2. Open any link in a new tab
    3. See buttons stuck to each other

- QA Steps:
    1. Visit https://codepen.io/ferossity/full/qaezaB/
    2. Open any link in a new tab
    3. Buttons should be spaced out as per design standard

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22117955/cdc17dc8-de6d-11e6-8d88-dc8070de0a45.png)

- Any related issues:

**Comment by luixxiul** [comment]
The similar fix for #6317 and #6328 will work here
