### ISSUE TITLE
Save torrent file shows .file extension instead of .torrent

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6736]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Save torrent file shows .file extension instead of .torrent

**Expected behavior:**
Should show .torrent file

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	c60b783

- Steps to reproduce:
    1. Open any magnet torrent link in a tab
    2. Click on the `Save torrent file` button
    3. In the save prompt dialog, shows file extension instead of `.torrent` 
    4. Open file browser where the file was stored, file extension shows as `.torrent` file

- QA Steps:
    1. Open any magnet torrent link in a tab
    2. Click on the `Save torrent file` button
    3. In the save prompt dialog should show `.torrent`  extension
    4. Open file browser where the file was stored, file extension should show as `.torrent` file

- Screenshot if needed:
![torrentfile](https://cloud.githubusercontent.com/assets/17010094/22118348/512ed088-de6f-11e6-944b-6fb10d40eb8e.gif)

- Any related issues:
cc: @feross @dcposch

**Comment by bbondy** [comment]
I think this is just because you have windows settings on to hide file extension for known types. 
On macOS it works by showing the full file path. I think it will work on windows as well if you turn that option off. That option is something I do on every new windows install by the way.
Please re-open if you disagree.

**Comment by feross** [comment]
Yes, @bbondy is correct. This is because the torrent's name ends in ".mp4" (which is pretty strange in practice), and your OS is hiding the .torrent.

**Comment by luixxiul** [comment]
I'm wondering if this could be similar with https://github.com/brave/browser-laptop/issues/2231#issue-161016630 in some way

**Comment by feross** [comment]
@luixxiul Doubt it. The file is correctly saved with the .torrent extension. This issue was invalid.

**Comment by srirambv** [comment]
@feross  The issue is while saving Brave doesn't show the file extension. On any file save if the filename is renamed it deletes the extension ([#1985 (comment)](https://github.com/brave/browser-laptop/issues/1985#issuecomment-250883580)). This is the reason it shows .mp4 while saving but saves the file as a torrent. Fixing #1985 should solve this as well. Because the download shows the file extension , it might confuse users whether they are saving the torrent file or the actual file. Upon save they will question I saved the actual file but why did it only saved it as torrent.

**Comment by bsclifton** [comment]
@srirambv it seems the heart of the issue is that you want it to show as .torrent. Unfortunately, it may not do that if you have extensions turned off. In this case, the only real solution would be to update the "Save As" dialog to use "*Torrent files (*.torrent)" instead of "All Files (*.*)".

**Comment by bbondy** [comment]
Windows shouldn't have such an option, let alone enable it by default, it's a general problem with Windows.
