### ISSUE TITLE
Torrent Save file gives 0 as default file name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6737]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Torrent Save file gives 0 as default file name

**Expected behavior:**
Should give the actual file name 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	c60b783

- Steps to reproduce:
    1. Download from any torrent magnet link 
    2. Click on the save file button in the torrent viewer
    3. File name is 0 in the save dialogue prompt

- QA Steps :
    1. Download from any torrent magnet link 
    2. Click on the save file button in the torrent viewer
    3. Save dialogue prompt should contain the actual filename

- Screenshot if needed:
![savetorrent](https://cloud.githubusercontent.com/assets/17010094/22118760/ee0ad04a-de70-11e6-9013-cc93df265133.gif)

- Any related issues:
cc: @bbondy

**Comment by feross** [comment]
We can fix this with a 'Content-Disposition' header in the WebTorrent server.

In the past, I've found just setting a `download` attribute on the link like `<a href='#' download='filename.mp4'>` was sufficient to control the filename in the absence of a 'Content-Disposition' header. However, Chrome stopped obeying the `download` attribute for links on other domains (CORS).

So, the 'Content-Disposition' header will work.

PR out to WebTorrent here: https://github.com/feross/webtorrent/pull/1039

**Comment by feross** [comment]
PR is merged and released to npm: https://github.com/feross/webtorrent/pull/1039

PR sent to bump webtorrent-remote: https://github.com/brave/browser-laptop/pull/7154
