### ISSUE TITLE
"New Tab" menu going off screen

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#6738]
**Did you search for similar issues before submitting this one?**

Yes, but I may have missed one.

**Describe the issue you encountered:**

When I click and hold the new tab `+` button, the new tab menu that popups up is largely off screen.

**Expected behavior:**

I expect to be able to see the full menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.12.15

- Steps to reproduce:
    1. Open Brave and open enough tabs to push the new tab `+` all the way to the right.
    2. Click and hold the `+`.

- Screenshot if needed:

<img width="145" alt="screen shot 2017-01-19 at 12 04 36 pm" src="https://cloud.githubusercontent.com/assets/133786/22119345/dd7fc878-de40-11e6-9e95-f86245adc371.png">

**Comment by srirambv** [comment]
Same as #5763
