### ISSUE TITLE
Allow flash loads flash content even when flash is not enabled in settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6739]
**Did you search for similar issues before submitting this one?**

**Describe the issue you encountered:**
Allow flash loads flash content even when flash is not enabled in settings

**Expected behavior:**
Flash should be enabled in settings to allow flash content to run

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
rev	c60b783
Muon	2.0.12

- Steps to reproduce:
    1. Disable flash in settings page under security
    2. Visit http://www.y8.com/games/superfighters
    3. Right click on the flash placeholder and select Allow/Allow for 1 week
    4. Flash content is loaded even when flash is disabled in settings 

- QA Steps:
    1. Disable flash in settings page under security
    2. Visit http://www.y8.com/games/superfighters
    3. Right click on the flash placeholder and select Allow/Allow for 1 week
    4. Should not load flash content until flash is enabled in settings page
 
- Screenshot if needed:
![flash](https://cloud.githubusercontent.com/assets/17010094/22119610/2533f2ec-de74-11e6-91e8-621da3c642be.gif)

- Any related issues:

**Comment by diracdeltas** [comment]
just to clarify, the expected behavior that brianj, brendan, and i agreed on was:

1. flash not installed, not enabled: no placeholders (therefore no way to run flash)
2. flash installed, not enabled: same as above
3. flash not installed, enabled: impossible because we don't offer the option to enable Flash until you install it
4. flash installed, enabled: placeholders that you can right-click to run flash

in all cases above, sites that are not Adobe (or other exceptions) cannot see whether flash is installed until you click-to-play on the placeholder.

**Comment by bbondy** [comment]
This is a bug and should work as you described but would you be against treating it as a bug and fixing within the context of 0.13.1? I'd rather not block on this so we can release tomorrow and the flash plugin won't actually run until you explicitly allow.

**Comment by diracdeltas** [comment]
as a hotfix i can just change the context menu to say 'enable flash in preferences' instead of 'allow flash'

**Comment by bbondy** [comment]
I don't think that would help because navigator.plugins would still advertise it. I'm looking into a fix too since I want to get builds going for rc1.

**Comment by diracdeltas** [comment]
@bbondy it doesn't appear that navigator.plugins is advertising it

**Comment by bbondy** [comment]
It's advertising it if it's installed pre the fix I'm doing. 
Note that since we aren't using our placeholders anymore there is no indication to go to preferences, @srirambv pls post a follow up to get our placeholders back in for 0.13.something. (not 0.13.1 though).

**Comment by bbondy** [comment]
window renderer at least, probably the content setting hides it.

**Comment by bbondy** [comment]
with the fix I'm doing it won't even load the plugin anymore to get the info from it.

**Comment by bbondy** [comment]
I think we'll try for an RC2 which has a less aggressive approach for better UX, so re-opening for now.

**Comment by diracdeltas** [comment]
slightly-modified QA steps in https://github.com/brave/browser-laptop/commit/aab8142ee5c7dd0a9431103b1185f3b662da95f5
