### ISSUE TITLE
blockFlash.js cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6740]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
The script in blockFlash.js assumes there is an href property on the event target.

**Expected behavior:**
The script in blockFlash.js places a non-discriminate listener on the document. Click events may not come from a source with a href property.

**Brave Version (revision SHA):** 0.13.0

**Screenshot if needed:**

![matchofundefined](https://cloud.githubusercontent.com/assets/815158/22119797/92a894ae-de42-11e6-888c-da333db8a8c5.gif)

**Comment by bbondy** [comment]
harmless fix so included it in 0.13.0.

**Comment by bbondy** [comment]
thanks!
