### ISSUE TITLE
Gmail showing red error periodically about not being logged in

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#675]
This is a problem with the cookie blocking:

urlParse(details.firstPartyUrl || '').host -> mail.google.com
urlParse(details.url || '').host ->  www.google.com
Cookie gets cleared: SID=….

Quick fix until we do proper fix would be to strip www.
I'll post another issue for the longer term fix as well

**Comment by diracdeltas** [comment]
This actually doesn't seem to fix it for my account. In addition, hangouts is blocked because hangouts.google.com is third-party to mail.google.com. Might as well just fix #676 here.
