### ISSUE TITLE
Change lang setting on about:preferences should always show the restart notification bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6750]
## Test plan
See https://github.com/brave/browser-laptop/pull/13073

## Original issue description
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Change in language doesn't always show the restart notification bar

**Expected behavior:**
Should always show the restart notification bar when a different language is selected each time

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	c60b783

- Steps to reproduce:
    1. Do a clean install of 0.13.0 preview 10
    2. Change the browser language from  English to any other language, notice the restart notification bar is shown
    3. Without closing select a different language, notice the restart notification bar is gone
    4. Without restarting change the language again, restart notification bar is shown

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![lang](https://cloud.githubusercontent.com/assets/17010094/22127744/387adcfa-de95-11e6-8b77-58387c070aa7.gif)

- Any related issues:

**Comment by srirambv** [comment]
Also **Requires restart** text is missing next to language similar to other options in settings which initiates a restart

**Comment by sergiorojasa** [comment]
I would like to work on this issue

**Comment by srirambv** [comment]
@sergiorojasa  Please submit a PR. I have self assigned the issue so that no one else takes it.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
