### ISSUE TITLE
Refinements to Add Funds URL Include Button

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#6754]
- [x] remove blue selected outline (only the URL bar should display tab-selection outline)
   - was implemented with https://github.com/brave/browser-laptop/pull/6761
- [x] replace BTC icon with new Heart icons
- [x]  fix render gap to match left-side bookmark button

![image](https://cloud.githubusercontent.com/assets/13509546/22131637/8865a2e4-de69-11e6-8beb-e5898464a67f.png)

![image](https://cloud.githubusercontent.com/assets/13509546/22131629/7adc682e-de69-11e6-96de-757c0fd53593.png)

**Comment by luixxiul** [comment]
> fix render gap to match left-side bookmark button

https://github.com/brave/browser-laptop/blob/2a78248d7b3e8611d251c2ef697f309f26d3a7c3/less/navigationBar.less#L685-L687

Change

````
border-radius: @borderRadiusURL;
border-top-left-radius: 0;
border-bottom-left-radius: 0;
````

Into

````
border-radius: 0;
````

Done! ;-)

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by bsclifton** [comment]
I believe this issue is still open and needs a resolution.  The latest solution can be found at https://github.com/brave/browser-laptop/pull/6862#issuecomment-277161747

But it's not implemented yet

**Comment by luixxiul** [comment]
the milestone was modified

**Comment by luixxiul** [comment]
Note: when you close the issue please do not forget to include #6592 too.

**Comment by bsclifton** [comment]
@luixxiul is auto-include sites is available in 0.13.2? if so, the icon used is a deal-breaker (per the notes linked to). It should be excluded from the RC

**Comment by luixxiul** [comment]
> is auto-include sites is available in 0.13.2?

I see the option on about:preferences#payments but not sure if it works as it should and how to know it.

**Comment by bsclifton** [comment]
Moving milestone back to 0.13.2 and marking this as a blocker.  We can't ship auto-include sites with the original bitcoin icon (shown above) per request by @BrendanEich. The icon which was included with https://github.com/brave/browser-laptop/pull/6862#issuecomment-277161747 has open (unaddressed) security concerns

We can either:
- Back the auto-include sites commits out from 0.13.2
- Fix the icon
- Ship with a not ideal icon

cc: @bradleyrichter @bbondy

**Comment by bbondy** [comment]
Is this really a blocker?  I don't see the linked to UI in the URL bar whether the option is on or off.  I think people will just not know what it is for and so we can just move it to the next milestone.  At this point everything else is taken care of so I don't want to respin an RC6 for only this.
