### ISSUE TITLE
0.13.1: Revert "Add currency symbols where appropriate"

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6756]
Reverts https://github.com/brave/browser-laptop/commit/004c04aec750dca79f78cb5e432655c477e57a28 in the 0.13.1-branch

Auditor: @bsclifton 

Test: go to about:preferences#payments and verify that the balance shows as

        amount currency

e.g.,

        20.0 USD

**Comment by bsclifton** [comment]
Closed with https://github.com/brave/browser-laptop/pull/6720
