### ISSUE TITLE
Remove outline from addPublisher urlbar button

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6760]
Per @bradleyrichter request, new addPublisher icon inside urlbar shouldn't have an outline.

**Comment by bsclifton** [comment]
Closed with https://github.com/brave/browser-laptop/pull/6761

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/browser-laptop/commit/07451654a72e8f6f292d5f045bd513d41a4e4ce3
