### ISSUE TITLE
there is no obvious way to stop a torrent download once it has started

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#6768]
## Test Plan

1. Click a torrent or magnet link from this list https://webtorrent.io/free-torrents
2. Click 'Start Download'. The torrent detail view should appear.
3. Wait a few seconds, click 'Stop Download'. The torrent start page with a 'Start Download' button should return, indicating the download has stopped.

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you click on a torrent link and start the download, there does not appear to be any way to stop it

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
986387e82b8bfa59ada64b531dc06873fdbb6bda

- Steps to reproduce:
    1. go to http://codepen.io/ferossity/full/qaezaB/
    2. Click on any of the torrent links
    3. Start the download
    
- Can this issue be consistently reproduced?
Yes

- Any related issues:

cc @feross

**Comment by feross** [comment]
Closing the tab will stop the download, stop all connections, and shutdown the client entirely (if there are no other torrents active).

Our thinking in leaving out a download button was to treat torrents no different than other content that the browser can render, like PDFs, images, and video files. For example, to stop an HTTP video file from downloading, you just close the tab. The only difference with torrents is that we get upfront user consent before starting the download in the first place.

Can we some folks with design/UX experience take a look at this and suggest improvements?

cc @dcposch

**Comment by feross** [comment]
This is done. PR here: https://github.com/brave/browser-laptop/pull/7863

![stop-download](https://cloud.githubusercontent.com/assets/121766/24274267/5fe96fd8-0fe4-11e7-93f5-03bc239feb68.gif)
