### ISSUE TITLE
clearing per site settings causes shields to go out of sync with content view

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6771]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
if a per-site setting exists (like block scripts) and it is cleared in preferences, the shields for the site displays the proper setting, but the content view does not update appropriately even after refresh or close/reopen of the site

- Platform (Win7, 8, 10? macOS? Linux distro?):
tested on os x

- Brave Version (revision SHA):
0.13.0 preview 10 (c60b783)

- Steps to reproduce:
    1. with a clean session, open about:preferences#shields
    2. in a new tab, visit brianbondy.com and block scripts
    3. in the preferences tab, clear the setting
    4. return to the brianbondy tab, check shield settings, reload the site, close the tab, revisit the site
    5. notice that despite the shield setting, the view still behaves as if scripts are blocked

- Actual result:
the view is not in sync with the shields

- Expected result:
the view should remain in sync with the shields

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
needs investigation

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
video in #testers 

- Any related issues:

**Comment by bbondy** [comment]
Great find, pls attach the video you did too. I'm going to move this to 0.13.1 though since it was also in 0.12.15. I just verified that it is.
