### ISSUE TITLE
Enabling flash shows restart browser notification

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6774]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Enabling flash shows restart browser notification

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	fefd17c

- Steps to reproduce:
    1. Do a clean install of 0.13.0 RC1
    2. Go to settings page and enable flash under security
    3. Shows restart notification bar on top
    
- Actual result:
Shows restart notification bar when flash is enabled

- Expected result:
Restart notification should not be shown for enabling flash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![flash](https://cloud.githubusercontent.com/assets/17010094/22142824/ac025b6c-deef-11e6-97d0-78d575b0ee80.gif)

- Any related issues:
cc: @diracdeltas

**Comment by srirambv** [comment]
@bbondy confirmed this is expected behavior. Closing the issue and removing milestone.

**Comment by bbondy** [comment]
It's no longer going to require restart by the way, with the new way it was fixed.
