### ISSUE TITLE
Payment history PDF is loaded momentarily before the save dialog box is shown

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6776]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Payment history PDF is loaded momentarily before the save dialog box is shown

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	fefd17c

- Steps to reproduce:
    1. Do a clean install of 0.13.0 RC1
    2. Enable payments from settings
    3. Add transactions entry in the `ledger-state.json` file to show the view payment history in Ledger payments
   4. Click on the view payment history to show the modal with transaction details
   5. Click on the payment pdf link
   6. A new tab opens the pdf and then closes it immediately before the save file prompt is shown
    

- Actual result:
The pdf opened in a new tab gets closed and save prompt is shown

- Expected result:
Functionality should be similar to `Save recover keys` where the text file is opened in a new tab after saving 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ledgerreport](https://cloud.githubusercontent.com/assets/17010094/22144490/d3e858d8-def5-11e6-8028-08353a382181.gif)

- Any related issues:
cc: @mrose17

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/6039#issue-193669852
