### ISSUE TITLE
Change contact info on about:safebrowsing

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6781]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
about:safebrowsing still shows as support+laptop@brave.com as contact. Since support is moved to community.brave.com, this should be changed.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
All

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22157203/9e78e684-df2e-11e6-93e3-8c81e5bebc0f.png)

- Any related issues:

**Comment by iamVP7** [comment]
Can I write to fix this issue.

**Comment by bsclifton** [comment]
@iamVP7 what do you mean? Would you like to fix the issue (if so, we can help!)?  Or are you giving a thumbs up (letting us know that as a user you'd like it fixed 😄 )

**Comment by iamVP7** [comment]
I would like to fix the issue.

**Comment by luixxiul** [comment]
@iamVP7 Sweet! Please have a look at https://github.com/brave/browser-laptop/blob/master/.github/CONTRIBUTING.md#making-changes.

The line you should edit is https://github.com/brave/browser-laptop/blob/625ecea07159b63fc431522f2821c6b89b5b2479/app/extensions/brave/locales/en-US/app.properties#L43

**Comment by iamVP7** [comment]
@luixxiul  just would like to know the replace text. Can we have _"Please report the site at  community.brave.com/c/site-feedback "_  or anything you have thought before.

**Comment by luixxiul** [comment]
I think community.brave.com/c/site-feedback is the place to discuss the community itself. Maybe we need to set up additional forum there. CC @alexwykoff

**Comment by bsclifton** [comment]
@iamVP7 I think that's fine 😄  Please continue with the change!  When it's time for a pull request, you can assign to @alexwykoff

**Comment by iamVP7** [comment]
@alexwykoff sent  a PR

**Comment by alexwykoff** [comment]
https://community.brave.com/c/site-blocking created
