### ISSUE TITLE
Change language needs require restart text similar to other pref settings

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6782]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Change language needs require `(requires browser restart)`similar to other pref settings

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.0
rev	fefd17c

- Steps to reproduce:
    1. Do a clean install of 0.13.0
    2. Open preferences page 
    3. `(requires browser restart)` message missing next to Language similar to other pref settings
    
- Screenshot if needed:

- Any related issues:
#4777

**Comment by luixxiul** [comment]
Fix here: https://github.com/brave/browser-laptop/blob/7bef7d186c5ec98d1595cfc91ec47ee8d47d758f/app/extensions/brave/locales/en-US/preferences.properties#L185
