### ISSUE TITLE
No-script notification buttons need margins

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6783]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
No-script notification buttons needs padding

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.0
rev	fefd17c

- Steps to reproduce:
    1. Visit https://twitter.com
    2. Enable block script from **preferences**
    3. Click on the no-script button in URL bar
    4. Buttons in no-script notification is all stuck to each other, needs spacing
    
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22157449/b25bfabe-df2f-11e6-8585-b242119fe16d.png)

- Any related issues: #6317 

## Test plan

1. Open about:preferences#shields
2. Enable "Block Scripts"
3. Open https://brianbondy.com/
4. Click noScript button on the navigation bar
5. Make sure there are margins among the buttons

<img width="393" alt="screenshot 2017-01-21 3 01 12" src="https://cloud.githubusercontent.com/assets/3362943/22159782/e6239086-df85-11e6-9f74-940a113a4cee.png">

**Comment by luixxiul** [comment]
The fix which is similar to #6317 should work here too

**Comment by diracdeltas** [comment]
This was incidentally fixed by https://github.com/brave/browser-laptop/pull/7272

**Comment by alexwykoff** [comment]
Agreed. No longer a bug.
