### ISSUE TITLE
Implement Flash placeholder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6784]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
With CR54 implementaion, flash place holder is not shown for flash content. Need to implement Brave's Flash placeholder for future releases.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.0
rev	fefd17c

- Screenshot if needed:
On 0.13.0 how it looks when flash is enabled in preferences
![image](https://cloud.githubusercontent.com/assets/17010094/22158709/65547d76-df35-11e6-8193-f8b3fd55d1b4.png)

  On 0.13.0 how it looks when flash is disabled 
  ![image](https://cloud.githubusercontent.com/assets/17010094/22158893/5a314950-df36-11e6-855b-cd71181fb3bf.png)

   Should look like this when flash is enabled in settings
  ![image](https://cloud.githubusercontent.com/assets/17010094/22158792/e7775a58-df35-11e6-9537-0bedd1b538f6.png)
 
    Should look like this when flash is disabled in settings
    ![image](https://cloud.githubusercontent.com/assets/17010094/22158844/2658eac0-df36-11e6-9959-0913a3d6694f.png)

- Any related issues:

**Comment by diracdeltas** [comment]
I think we are probably not going to go back to the old placeholder, at least not anytime soon.
