### ISSUE TITLE
Extension API: chrome.windows.create

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6789]
https://developer.chrome.com/extensions/windows#method-create

Any attempt to call this method today returns the following:

    ⚠ chrome.windows.create is not supported yet

Optional `createData` properties:

- [ ] url
- [ ] tabId
- [ ] left
- [ ] top
- [ ] width
- [ ] height
- [ ] focused
- [ ] incognito
- [ ] type
- [ ] state

**Comment by jonathansampson** [comment]
Blocks #8327

**Comment by jonathansampson** [comment]
Blocks #8671

**Comment by zentagonist** [comment]
After discussion of progress on metamask integration items with @jonathansampson, adding this to the 0.20.x milestone.

**Comment by jonathansampson** [comment]
@kevinlawler Code is split across Muon and Browser Laptop in branches called `chrome.windows.create`.

**Comment by kevinlawler** [comment]
Read my mind
