### ISSUE TITLE
Extension API: chrome.tabs.update

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6790]
https://developer.chrome.com/extensions/tabs#method-update

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave presently doesn't fully support the `chrome.tabs.update` API. The following properties should be supported for Brave to be *complete*:
  - [ ] url **supported**
  - [ ] active [bug?][1]
  - [ ] highlighted [bug?][1]
  - [ ] selected [bug?][1] (deprecated, use highlighted)
  - [ ] pinned
  - [ ] muted
  - [ ] openerTabId
  - [ ] autoDiscardable

Testing these APIs can be done from `about:extensions` in Brave:

```js
chrome.tabs.update(tabid, {url: 'https://brave.com'}, () => {
    chrome.runtime.lastError && console.log(chrome.runtime.lastError)
})
```

- Additional QA Steps:
Finding a `tabid` can be done via the `chrome.tabs.query` method:

```js
chrome.tabs.query({}, tabs => console.log(tabs))
```

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.13.4

### Blocked Extensions
 - Evernote Web Clipper
 - #9531 Vimium
- #9330 True Key
- #9828 OneTab

 [1]: https://github.com/brave/muon/blob/ef80be0e321a0d8b799a9cc8a577a93c0f21103d/lib/browser/api/extensions.js#L275

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bsclifton** [comment]
Moving to 0.14.3
