### ISSUE TITLE
Opening preferences from kabob puts tab in background

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6791]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Opening "Settings" (preferences on macOS) from the kabob menu will sometimes background the tab.  Here's a demo:
![prefs](https://cloud.githubusercontent.com/assets/4733304/22169639/e414391a-df32-11e6-9886-ca44945c87e5.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?):
os.platform	win32
os.release	10.0.14393
os.arch	x64

- Brave Version (revision SHA):
Brave	0.13.0 (release candidate 4)
rev	40dffe8
Muon	2.0.13
libchromiumcontent	54.0.2840.100
V8	5.4.500.41
Node.js	7.0.0
Update Channel	dev

- Steps to reproduce:
1. Launch Brave on Windows 10 x64 using the desktop shortcut
2. visit brave.com
3) close all the other tabs (especially preferences)
4) use kabob / hamburger menu to pick settings
5) make a very sad face because tab opened, but it opened like you did it with Ctrl + click or cmd+click (backgrounded it)
    
- Actual result:
Sometimes (many times), preferences will load in the background (as if you opened it with ctrl + click or cmd+click)

- Expected result:
Tab should always open in the foreground

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@aekeus was able to reproduce on macOS with the following steps:
- close Brave
- open Brave
- select Kabob > Preferences
- tab goes to background

**Comment by srirambv** [comment]
Its not just on opening preference page from kabob menu. Even opening a new tab causes it to go background 

![tabswitch](https://cloud.githubusercontent.com/assets/17010094/22170170/b39699f0-df72-11e6-9484-821f5beb8c5e.gif)

**Comment by bridiver** [comment]
reopening after reverting https://github.com/brave/browser-laptop/commit/aeab0bdf5297778b71b2f1a3bd77d1542c0873b5

**Comment by luixxiul** [comment]
@bridiver Is https://github.com/brave/muon/commit/6c18907fcb9a6da29981a1b8dce395a6f9bbbad5 included in RC7?

**Comment by bridiver** [comment]
Yep

**Comment by luixxiul** [comment]
I'm not sure if the issue was fixed:

![about](https://cloud.githubusercontent.com/assets/3362943/22358705/775a024e-e484-11e6-9490-b17b9ecc67fb.gif)

**Comment by bridiver** [comment]
this is still happening, but very infrequently. I don't think we should block on it

**Comment by luixxiul** [comment]
@bridiver thanks for taking this soon!
