### ISSUE TITLE
"Save As" dialog is displayed several times

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6795]
**Describe the issue you encountered:**
"Save As" dialog is displayed as soon as it is canceled

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC4

- Steps to reproduce:
    1. <kbd><kbd>CTRL</kbd> + <kbd>S</kbd></kbd>
    2. Click "Save"
    
- Actual result: The dialog should be closed and this page is saved

- Expected result: The same dialog appears again

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
They do not reproduce. The other info is that the CPU usage is higher than usual (~30%)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment]
Cant replicate this on Win x64 even with Pocket and password managers enabled.

**Comment by luixxiul** [comment]
@srirambv do you see the high usage of CPU when you enable those extensions?

**Comment by srirambv** [comment]
Yes there is an automatic increase in CPU & memory usage by Brave process when password manager or extension is enabled

**Comment by luixxiul** [comment]
The issue has been fixed since a long time ago.
