### ISSUE TITLE
The blocked URL is attached to "about:safebrowsing#"

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6797]
**Describe the issue you encountered:**
The blocked URL is attached to `about:safebrowsing#`

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC4

- Steps to reproduce:
    1. Open http://downloadme.org/
    
- Actual result:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22171683/96ee179c-dfd6-11e6-8f7d-4651dfeffb7c.png)

- Expected result:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22171686/ae6679b4-dfd6-11e6-92e9-3cdabab411ec.png)

- Will the steps above reproduce in a fresh profile?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #6318

https://github.com/brave/browser-laptop/commit/b3c86d8bc810cfe618292a8259b8e3dd82076c18#diff-8a9bac13ef6264feb2b6da7c18d86b3cR144

**Comment by srirambv** [comment]
I remember @diracdeltas had mentioned that it should just show as `about:safebrowsing` and not `https://downloadme.org/`.

The URL changes to `https://downloadme.org` if autohide URL bar is enabled.

**Comment by bbondy** [comment]
this is the new expected URL I think, at least it was an intentional change.
@diracdeltas please let us know if we can instead show the shortened URL in UI only, but not needed for this version so removing the milestone.

**Comment by diracdeltas** [comment]
i think we can show the original url instead of about:safebrowsing

**Comment by luixxiul** [comment]
I think the change works fine. wontfix?

**Comment by diracdeltas** [comment]
agree
