### ISSUE TITLE
Entries of the same site on different protocols (http/https) are displayed in the autocomplete list on URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6798]
**Describe the issue you encountered:**
Entries of the same site on different protocols (http/https) are displayed in the autocomplete list on URL bar.

Is this intended?

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.13.0 RC4

- Steps to reproduce:
    1. Enable HTTPS Everywhere on `about:preferences#security`
    2. Open http://www.apple.com
    3. Make sure the site is redirected to https://www.apple.com
    4. Disable HTTPS Everywhere from the top right lion icon
    5. Close the tab
    6. Open a new tab
    7. Open http://www.apple.com
    8. Open another new tab
    9. Enter `apple`
    
- Actual result:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22172306/5790d534-dfe6-11e6-8045-649755291401.png)

- Expected result:
I am not sure if that is what is actually expected.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by Liunkae** [comment]
Firefox does the same thing:
![image](https://cloud.githubusercontent.com/assets/19424103/22172444/96bd550e-df6c-11e6-859c-50013e606dfb.png)

My opinion: for better security and privacy, we should discard an HTTP history item if another HTTPS history item exists for the same exact URL.

**Comment by NejcZdovc** [comment]
@luixxiul I agreee HTTPS should have priority.

**Comment by luixxiul** [comment]
CC @diracdeltas @bbondy for thoughts

**Comment by bbondy** [comment]
I guess both addresses could serve different sites in the general case, but I think we can pretend that's not possible and discard http if there's an https available and matching otherwise.

**Comment by luixxiul** [comment]
I cannot confirm the issue anymore. For now I'm going to close the issue.
