### ISSUE TITLE
Pocket extension consumes so much CPU resource

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6799]
**Describe the issue you encountered:**
Pocket extension consumes so much CPU resource.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22172587/9be47f9e-dfee-11e6-9e04-8955bbfd40d7.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC4

- Steps to reproduce:
    1. Clear your brave folder
    2. Open the browser 
    3. Open about:preferences#advanced
    4. Enable Pocket
    5. Open Task manager of Windows
    
- Actual result:
The CPU usage goes around 30%

- Expected result:
It should be lower

- Will the steps above reproduce in a fresh profile?
Yes

- Any related issues:

**Comment by bbondy** [comment]
Does it do this on Chrome as well?

**Comment by luixxiul** [comment]
> Does it do this on Chrome as well?

No it doesn't.

**Comment by luixxiul** [comment]
This cannot be reproduced so I'm going to close this
