### ISSUE TITLE
brave/muon needs symbols uploaded on the release page from cibuilds

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6801]
Currently no symbols are being uploaded.  We'll need this to get the release out.

@bridiver would you mind checking it out?

**Comment by bridiver** [comment]
should be good, but @aekeus can reopen or create a new issue if there is still a problem with windows symbols

**Comment by luixxiul** [comment]
Do we need QA for this?

**Comment by aekeus** [comment]
Nope, no QA needed. I will make sure all platforms are working correctly as RC6 is released.
