### ISSUE TITLE
Fetching.io extension fails to add content to Fetching Native

### ISSUE THREAD

**Issue by atomicpirate** [brave/browser-laptop#6802]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Followed the excellent guide here:
https://blog.brave.com/loading-chrome-extensions-in-brave/

..and installed the Extension for fetching.io:
https://chrome.google.com/webstore/detail/nhogooppmliljkaickdcmdnmaheaicmg

However, when using the fetching.io extension with Fetching Native on Mac, I am able to see documents indexed by Fetching but when I browse to new pages, they aren't added to Fetching.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 12.2

- Brave Version (revision SHA):
d4f79bed085c7cf83645a395915c9e72d7d4eb2f

- Steps to reproduce:
    1. Run Fetching Native
    2. Install fetching.io extension
    3. Browse a website (e.g., nytime.com)
    
- Actual result:
Fetching Native shows no new pages added

- Expected result:
Pages browsed in Brave should show up in Fetching Native. Chrome with the same setup works fine.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, it should.

- Is this an issue in the currently released version?
Since it is in the current master branch, I would assume so.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. N/A
    2.
    3.

- Screenshot if needed:
N/A

- Any related issues:
N/A

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
