### ISSUE TITLE
Show Permissions when Enabling Extensions

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6803]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Users are not aware of an extension's permissions when installing/enabling.

- Brave Version (revision SHA): 0.13.0

- Is this an issue in the currently released version?
Yes

- Screenshot if needed:

In Chrome, the user is given a short summary of an extension's permissions upon installing. No such notification or message is shown when _enabling_ a previously disabled extension. Permissions can be seen when clicking _Details_ on an extension in chrome://extensions/.

![image](https://cloud.githubusercontent.com/assets/815158/22177437/1f7a598e-dfe3-11e6-9f37-81898969a0ba.png)

cc @bradleyrichter

**Comment by bsclifton** [comment]
This works as expected in brave-core 😄 
![screen shot 2018-08-24 at 12 25 36 am](https://user-images.githubusercontent.com/4733304/44570932-40acbb00-a734-11e8-9d82-178dcf897512.png)
