### ISSUE TITLE
navigator.doNotTrack is enabled on 0.13.0 RC4

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6804]
**Describe the issue you encountered:**
navigator.doNotTrack is enabled on 0.13.0 RC4, which is not on 0.12.15. Is this expected on cr54 update or something?

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC4

- Steps to reproduce:
    1. Open https://browserleaks.com/donottrack on 0.12.15
    2. Make sure that navigator.doNotTrack is set to **false (null)**
    3. Open the same page on 0.13.0 RC4
    4. Make sure that navigator.doNotTrack is set to **true (1)**
    
- Expected result: I am not sure if it is expected

- Any related issues: #6409

**Comment by bbondy** [comment]
It is `false (null)` for me on 0.13.0 and that's expected.

**Comment by bbondy** [comment]
Also I cleared out my profile before testing.

**Comment by luixxiul** [comment]
I'll check it out on my VM later

**Comment by luixxiul** [comment]
On Windows 10 32 bit
rev 5bad531

1. Clear brave folder
2. Start the browser
3. Open about:preferences#security
4. Enable DNT
5. Restart via notification
6. Open https://browserleaks.com/donottrack
7. navigator.doNotTrack is set to `true (1)`
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22183536/0a68c0ae-e104-11e6-9e72-513e06c28079.png)

Is this OK?

**Comment by bbondy** [comment]
it should not be specified at all by default. For me that is the case with a fresh profile.

**Comment by bbondy** [comment]
also off on my windows VM, are you sure your profile is being cleared correctly for the `brave` profile if you're using a packaged build or `brave-development` for a dev build?

**Comment by luixxiul** [comment]
I have enabled DNT on step 4 and restarted, then it should be enabled, right?

**Comment by bsclifton** [comment]
I did see DNT returning true for navigator.doNotTrack in RC4... but master appears correct:
![screen shot 2017-01-23 at 10 32 32 am](https://cloud.githubusercontent.com/assets/4733304/22215110/67611344-e157-11e6-83de-fd1486f054a6.png)

I'll close the issue, but please let's re-open if this occurs in the next RC
