### ISSUE TITLE
Image upload file chooser "strip location metadata" option (remove exif data)

### ISSUE THREAD

**Issue by BrendanEich** [brave/browser-laptop#6805]
@bradleyrichter design:

![image](https://cloud.githubusercontent.com/assets/313317/22178270/b188180e-dfe6-11e6-9541-d27bee2f6af5.png)

**Comment by BrendanEich** [comment]
Suggestion from https://twitter.com/stoyanstefanov/status/822869573246406656 (to use canvas toDataURL) led to http://removephotodata.com -- for lossy image formats, canvas round trip won't do, but seems like solutions abound.

**Comment by kevinlawler** [comment]
Recording some notes on general exif data, per Slack:

In the terminal I use `exiftool` which is a POSIX util one of whose intended use cases is to strip exif data from all image types. `exiftool -all= file.png`

Location is perhaps the worst offender, but the other exif attributes can still make you uniquely identifiable. Display color profile is sometimes embedded, for instance, which beyond letting you know that I used f.lux at one point, can link two screenshots to the same author. Or photos to the same photographer.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/838
