### ISSUE TITLE
Helpful Hints: "Bravery Panel" reference used in Settings 

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#6806]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Noticed that within the Helpful Hints in the Settings section that "Bravery Panel" is referenced, instead of "Shields"

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
0.12.15

- Steps to reproduce:
    1. Open the Settings section
    2. Rotate through the Helpful Hints until you see the one re: HTTPSe
    3. Note the Bravery Panel reference
    
- Actual result:
Bravery Panel
- Expected result:
Shields Settings || Shields Site Settings || Shields Panel

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="140" alt="bravery-panel-01212017" src="https://cloud.githubusercontent.com/assets/8979240/22180139/ac14456a-e01c-11e6-9823-5cddd129a917.PNG">
<img width="376" alt="siteshieldsettings-01212017" src="https://cloud.githubusercontent.com/assets/8979240/22180141/b5429aba-e01c-11e6-828d-4fedba11bbc3.PNG">

- Any related issues:
na

**Comment by Liunkae** [comment]
Text to change: https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/locales/en-US/preferences.properties#L117

**Comment by Liunkae** [comment]
Fixed with 94f8976.
