### ISSUE TITLE
Documentation: temp fix for white screen on Linux + AMD card

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6807]
**Describe the issue you encountered:**
There are several reports from Linux users who have an AMD card on their machine that the browser is not rendered properly or at all.

#1471 - Blank Page on Ubuntu
#3180 - Brave does not run properly in Linux Mint 18 XFCE in Virtual Box
#3663 - Blank pages after using brave for some minutes
#3787 - When opening new tabs web pages are not shown.
#4113 - All Pages White, Maybe Crash?
#4928 - Consistent blank pages (possible driver issue)
#6022 - Blank page when 2 tabs or more
#6861 - Blinking black and white screen

It seems OK for me to regard the users here are advanced, so I think that simple notes to workaround the issue temporarily can help them until the upstream bug (electron/electron#4380) would be fixed.

Per @bsclifton 
https://github.com/brave/browser-laptop/issues/1471#issuecomment-266158825
https://github.com/brave/browser-laptop/issues/1471#issuecomment-273991121

> When the brave executable is launched, please add the argument `--ignore-gpu-blacklist`.  There are a few others you can try too, if this doesn't work:
> ```
> --disable-gpu-rasterization
> --disable-native-gpu-memory-buffers
> --disable-accelerated-2d-canvas
> ```
>
> Another option which should work for folks:
> ````
> --disable-gpu
> ````

In some cases these flags do not work (https://github.com/brave/browser-laptop/issues/1471#issuecomment-266604953), still I think letting users try those would help them to troubleshoot.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu

- Any related issues:

**Comment by luixxiul** [comment]
There should be two tasks:

- [ ] Edit README.md
- [ ] Create a Wiki page
    - [ ] Link the page from the Wiki home page

**Comment by bbondy** [comment]
It seems like you understand the issue well @luixxiul, would you mind doing a PR for it?

**Comment by bsclifton** [comment]
@luixxiul I created a wiki entry which you could continue adding to 😄 
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

I only specified the steps for Windows. Perhaps you can find easy to follow steps for macOS and Linux?

**Comment by bsclifton** [comment]
I've updated the list of issues (captured in the original post and also in the wiki entry).  In each of those, I added the `bug/driver` label and then made sure there is documentation of the command line parameter in each. I've also asked our users to re-test using these steps and get back to us.

@luixxiul there are probably more issues open too regarding this. I'm not sure if we should close them in favor of a new issue, like "Handle GPU being on blacklist gracefully"? Whatever you think makes sense 😄

**Comment by luixxiul** [comment]
Instructions for Linux was added by @DivineOmega https://github.com/brave/browser-laptop/issues/6022#issuecomment-276670752

**Comment by Pistos** [comment]
I just want to add that I also was encountering "blank, white windows" when I had tried to set a custom watch port (other than the default 8080).  After putting the default back, my problem was solved.

**Comment by CrisBRM** [comment]
Why don't you simply disable the gpu by default until it's fixed upstream?

**Comment by bsclifton** [comment]
Closing as we have a help page available now:
https://community.brave.com/t/window-is-solid-black-or-solid-white-looks-like-a-blank-page/10003
