### ISSUE TITLE
Automated test failure on application window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6808]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/193820349#L4630
https://travis-ci.org/brave/browser-laptop/builds/193831274#L4748

- [x] application window windw.open with click without features opens in a new tab:
     WaitUntilTimeoutError: element (.frameWrapper:nth-child(2) webview) still not visible after 10000ms
      at isVisible(".frameWrapper:nth-child(2) webview") - waitForVisible.js:37:22

**Expected behavior:**

- Any related issues: #6408

**Comment by luixxiul** [comment]
Should this be fixed soon?

https://travis-ci.org/brave/browser-laptop/builds/205260809#L3825

````
Could not kill http server TypeError: this.http.kill is not a function
    at Server.stop (/home/travis/build/brave/browser-laptop/test/lib/serverChild.js:42:19)
    at process.<anonymous> (/home/travis/build/brave/browser-laptop/test/lib/serverChild.js:150:14)
````

**Comment by alexwykoff** [comment]
This test passes easily and repeatedly.
