### ISSUE TITLE
ia.ca site seems to crash renderer process

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#681]
This page seems to crash the webview renderer process, the webview loads as black
https://iac.secureweb.inalco.com/

**Comment by bridiver** [comment]
Just tested and that loads ok for me. Is there a crash report? Maybe the latest changes to Electron fixed whatever was wrong?

**Comment by bbondy** [comment]
This is how it loads for me:
![screenshot 2016-02-09 11 48 40](https://cloud.githubusercontent.com/assets/831718/12923287/2458897a-cf23-11e5-8966-91cf2842bb0e.png)

Actually I see now it's a problem with webviewPreload with getComputedStyle which landed recently. You're probably not on tip. I can fix.

**Comment by aekeus** [comment]
++ tested listed site. looks good.
