### ISSUE TITLE
cursor should be default on find bar (follow-up of #5744)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6812]
## Test plan

https://github.com/brave/browser-laptop/pull/7161#issue-206745581

----

**Describe the issue you encountered:**

[1] While you move the mouse cursor on the find bar and the notification bar, keep pushing your mouse left button, the cursor should always be `cursor:default`. This is a follow-up of #5744.

[2] Any elements on the find bar and the notification bar should not be selected. The issue will be fixed by adding `-webkit-user-select: none`

- Brave Version (revision SHA): 0.13.0 RC5

- Steps to reproduce [1]:
    1. Open the find bar by pressing Ctrl-F
    2. Move the mouse cursor on the find bar, keep pushing your mouse left button
    3. Open https://www.google.com
    4. Move the cursor on the notification bar, keep pushing your mouse left button

- Actual result [1]: ![cursor1](https://cloud.githubusercontent.com/assets/3362943/22184064/44987a58-e10e-11e6-828e-fd411a85c2a2.gif)

- Expected result [1]: ![cursor2](https://cloud.githubusercontent.com/assets/3362943/22184076/6e6ba2ce-e10e-11e6-9a73-c59ecfcff8d6.gif)

- Steps to reproduce [2]:
    1. Search something via the find bar
    2. Select the string ` x/x found` or `0 matches`

- Actual result [2]: the string can be selected with the mouse

- Expected result [2]: the string should not be selected

- Any related issues: #5744

**Comment by luixxiul** [comment]
@bbondy If +1 plz feel free to assign me

**Comment by luixxiul** [comment]
Also on `.notificationBar`:

![cursor3](https://cloud.githubusercontent.com/assets/3362943/22184260/86db95a0-e111-11e6-8532-ece99c20ff70.gif)

**Comment by bbondy** [comment]
feel free to take things @luixxiul anytime! :)

**Comment by luixxiul** [comment]
Sorry I meant something different a bit. I will open another issue to address it.

**Comment by bbondy** [comment]
It's best for the future to post a new issue for things that are different from the original issue, even if they are related. That way the thing that was valid and was fixed is properly referenced in release notes at the time it was fixed.  The goal of the fix originally was meant to fix only what was reported which didn't involve pressing the left mouse button. Thanks!

**Comment by luixxiul** [comment]
ok I see.
