### ISSUE TITLE
Clicking on urlbar autocomplete item opens in new tab

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6814]
I'll set the milestone to 0.13.0 for now, but please prioritize as needed.

- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Clicking on any suggestion provided by the urlbar autocomplete opens the URL in a new tab instead of the current tab (and <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> is not selected). Selecting the item and pressing <kbd>Enter</kbd> opens in the current tab, as expected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.13.0 RC5 (d4f79be)

- Steps to reproduce:
    1. Open a new Brave tab.
    2. Click the urlbar.
    3. Type `github`.
    4. Click the autocomplete suggestion that says "github.com".
    
- Actual result:
The URL is opened in a new tab.

- Expected result:
The URL should be opened in the current tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, with a fresh profile.

- Is this an issue in the currently released version?
No. The current release 0.12.15 works as expected.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a new Brave tab.
    2. Click the urlbar.
    3. Type `github`.
    4. Click the autocomplete suggestion that says "github.com".
    5. Make sure the URL opens in the current tab.

- Screenshot if needed:
Not applicable.

- Any related issues:
None.

**Comment by bbondy** [comment]
nice find, I'll fix.

**Comment by bbondy** [comment]
have a fix but I'll get a test for it tonight before pushing it out, have to go out for a bit.
