### ISSUE TITLE
Cannot attach files in Facebook Messenger

### ISSUE THREAD

**Issue by ktd99** [brave/browser-laptop#6816]
- Did you search for similar issues before submitting this one? No

- Describe the issue you encountered:  I can "Choose file" on my computer, but when I click "open" to attach it to the message, nothing happens.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Win 7

- Brave Version (revision SHA): 0.12.15

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/698

**Comment by bsclifton** [comment]
@ktd99 just a heads up; your report was closed as a duplicate. You can subscribe to https://github.com/brave/browser-laptop/issues/698 for updates
