### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined【electron.importer】【importer.on】win 10

### ISSUE THREAD

**Issue by leitianfu** [brave/browser-laptop#6819]
Hi: all.
        Who can help me，help me，   I am a new hand。

       It took me a week to build up;
       In order to build the environment, reinstall the system two times.
       Please help me
-------------------Runtime environment----------------------------------
Platform: Win 10 64bit
node：“7.4.0”
npm：“4.0.5”
electron ： "1.4.15"
python-2.7.13.
OpenSSL：1.0.2
----------------------Operating --steps---------------------------------------------------
In strict accordance with  (setup) Windows build guide：
https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide

npm install

npm run watch

npm  start
---------------------------------------------------------------------------------------------------------
npm run watch      ：Normal operation
-----------------------------run watch  output   start--------------------
> brave@0.13.0 watch C:\gitBrowse\browser-laptop
> webpack-dev-server --inline --hot --colors --content-base=./app/extensions/brave

 http://localhost:8080/
webpack result is served from http://localhost:8080/gen/
content is served from C:\gitBrowse\browser-laptop\app\extensions\brave
Hash: 3b10412f19cde39f94d86096a49e5a70a6c2ad8b26394f71ec97580c0712
Version: webpack 1.14.0
Child
    Hash: 3b10412f19cde39f94d8
    Version: webpack 1.14.0
    Time: 38217ms
                                     Asset       Size  Chunks             Chunk Names
      4134ecd741d7d7b79fd1bb41ca3ad4d5.svg  472 bytes          [emitted]
      8b116e3ce0b2711f8e2cc78c8b32a7c5.svg  485 bytes          [emitted]
      674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
    af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
     fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
      b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
      912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]
      284d3fe83d54015578cd4cefddee329e.svg    1.34 kB          [emitted]
      f2a17c62192cc6db4fdab183672d43e4.svg  698 bytes          [emitted]
      3b58ba8a347511da261ce50b5e4d7a4a.svg  897 bytes          [emitted]
      e8891b33008bde363a260c9b2f2537fb.svg  822 bytes          [emitted]
      d1b6d1018772c20f5b20bd46d0d1e3b6.svg    1.36 kB          [emitted]
      e16b2401b3d7db99fbb79e89cf1c59e0.svg  794 bytes          [emitted]
      31933cb144bf10bdae1f9b2647d19aaf.svg  828 bytes          [emitted]
      6bccede8353134f52db7c697abcdbab5.svg    3.07 kB          [emitted]
……………………………………
…………………………
………………
      [383] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
      [384] ./~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 84 bytes {0} [built]
      [385] ./~/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 83 bytes {0} [built]
      [386] ./~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 82 bytes {0} [built]
      [387] ./~/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 82 bytes {0} [built]
         + 4 hidden modules
webpack: bundle is now VALID.
---------------------------------run watch  output   start-----------------

Then execute the command in the new window：
npm  start
------------------------------Error:------start------------------------------------------------------------
App threw an error during load
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\gitBrowse\browser-laptop\app\importer.js:69:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\gitBrowse\browser-laptop\app\index.js:53:18)
    at Module._compile (module.js:556:32)
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\gitBrowse\browser-laptop\app\importer.js:69:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\gitBrowse\browser-laptop\app\index.js:53:18)
    at Module._compile (module.js:556:32)
Waiting 60 seconds for process to load
process exited with code null
----------------------------------Error:------end--------------------------------

-------------------------------------------------------------------------------------------------
importer.js-----source: line7 to line 95
------------------------------importer.js-source-start--------------------------------------------
const electron = require('electron')
const importer = electron.importer
const dialog = electron.dialog
const BrowserWindow = electron.BrowserWindow
const session = electron.session
const Immutable = require('immutable')
const siteUtil = require('../js/state/siteUtil')
const AppStore = require('../js/stores/appStore')
const siteTags = require('../js/constants/siteTags')
const appActions = require('../js/actions/appActions')
const messages = require('../js/constants/messages')
const settings = require('../js/constants/settings')
const getSetting = require('../js/settings').getSetting
const path = require('path')
const locale = require('./locale')

var isMergeFavorites = false
var isImportingBookmarks = false
var hasBookmarks

exports.init = () => {
  importer.initialize()
}

exports.importData = (selected) => {
  if (selected.get('mergeFavorites')) {
    isMergeFavorites = true
  }
  if (selected.get('favorites')) {
    isImportingBookmarks = true
    const sites = AppStore.getState().get('sites')
    hasBookmarks = sites.find(
      (site) => siteUtil.isBookmark(site) || siteUtil.isFolder(site)
    )
  }
  if (selected !== undefined) {
    importer.importData(selected.toJS())
  }
}

exports.importHTML = (selected) => {
  isImportingBookmarks = true
  if (selected.get('mergeFavorites')) {
    isMergeFavorites = true
  }
  const sites = AppStore.getState().get('sites')
  hasBookmarks = sites.find(
    (site) => siteUtil.isBookmark(site) || siteUtil.isFolder(site)
  )
  const files = dialog.showOpenDialog({
    properties: ['openFile'],
    filters: [{
      name: 'HTML',
      extensions: ['html', 'htm']
    }]
  })
  if (files && files.length > 0) {
    const file = files[0]
    importer.importHTML(file)
  }
}

importer.on('update-supported-browsers', (e, detail) => {
  isMergeFavorites = false
  isImportingBookmarks = false
  if (BrowserWindow.getFocusedWindow()) {
    BrowserWindow.getFocusedWindow().webContents.send(messages.IMPORTER_LIST, detail)
  }
})

importer.on('add-password-form', (e, detail) => {
})

importer.on('add-history-page', (e, history, visitSource) => {
  let sites = []
  for (let i = 0; i < history.length; ++i) {
    const site = {
      title: history[i].title,
      location: history[i].url,
      lastAccessedTime: history[i].last_visit * 1000
    }
    sites.push(site)
  }
  appActions.addSite(Immutable.fromJS(sites))
})

importer.on('add-homepage', (e, detail) => {
})

……………………………………
…………………………
………………

**Comment by bbondy** [comment]
It seems like your electron is very out of date, it should be grabbing 2.*

**Comment by bsclifton** [comment]
@leitianfu maybe you can try these steps?

```
git pull
npm run clean
npm install
```

After the install finishes, you should be in good shape 😄
