### ISSUE TITLE
Autofill suggestion is not dismissed when tabs are switched

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6820]
- Did you search for similar issues before submitting this one?
Yes, didn't find

- Describe the issue you encountered:
Autofill suggestion is not dismissed when tabs are switched

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	5bad531

- Steps to reproduce:
    1. Login to gmail.com so that autofill entry is created
    2. Logout and go back to  gmail login page
    3. Click on the input filed to show the autofill suggestion
    4. Open a new tab
    5. Autofill suggestion is still shown
This happens for all sites not just gmail
    
- Actual result:
Autofill suggestion is retained when a new tab is opened 

- Expected result:
Autofill suggestion should be dismissed when the tab focus is lost

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes existing issue

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
![autocomplete](https://cloud.githubusercontent.com/assets/17010094/22205088/3461bcee-e16d-11e6-8a4d-83775647a17f.gif)

- Any related issues:
#6233

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6854
