### ISSUE TITLE
Superhuman: Login page cannot communicate with Extension

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#6825]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The login page for the Superhuman extension is unable to call postMessage, as the two sources are different domains.

![image](https://cloud.githubusercontent.com/assets/815158/22230622/4efc2a62-e1a4-11e6-9c77-aec65e92f969.png)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
0.13.0

- Steps to reproduce:
    1. Install the Superhuman extension (need access to private beta)
    2. Attempt to login
    3. Note that login fials (aforementioned error found in console)
    
- Actual result:
Extension does not work _out of the box_ in Brave.

- Expected result:
Extension should work similarly in both Chrome and Brave.

**Comment by ConradIrwin** [comment]
Thanks for filing this @jonathansampson. Just a heads up to let you know that we may have fixed this for you as part of our work to support chrome's --isolate-extensions flag. We now post the message to `https://mail.superhuman.com/` instead.

**Comment by jonathansampson** [comment]
Closing, as this doesn't appear to be an issue any longer.

**Comment by ConradIrwin** [comment]
Thanks @jonathansampson! I was looking into this last night — looks like brave's now throwing a CSP error for us. Though I think it might be doing the right thing (it definitely seems like a bug that chrome can load iframes from extensions with no extension origin in frame-src...)

Was going to see if tweaking the config fixed it.

Out of interest, do you support developing brave on different ports? Superhuman development has to happen on :8080 and is basically impossible to change (it's hardcoded in the extension manifest, and the google oauth client stuff; both of which require manual review by Google to alter). If not, no worries I can continue launching brave, killing the dev server, launching the superhuman dev server, and loading the page

**Comment by jonathansampson** [comment]
@ConradIrwin Apologies for the delayed response. Unfortunately, I don't think it would trivial to bump Brave to another port. That being said, you make a solid argument in favor of exploring that issue. I'll file a new issue to track an effort to make it easier to test Brave on arbitrary ports.

**Comment by bridiver** [comment]
actually it is trivial to bump it to another port, just change config.port in the package.json

**Comment by jonathansampson** [comment]
@bridiver Ah, good to hear. I did a quick grep of the project directory and saw numerous hard-coded instances.
