### ISSUE TITLE
Idle timer never stopping the idle timer

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#6826]
This is the same as #4051, but I forgot to follow up on that issue.

My top three websites this month are websites I’ve visited before going to bed. I’ve lefy Brave open over night and have ~8 hours recorded for each of these sites. Timer is supposed to stop after 15 minutes, but this still isn’t working.

Tested with v0.13.0dev-RC5 on Fedora Workstation 25 with GNOME. I tested the same version under Windows 10 with an empty profile, and I see the same issue.

Test case:

0. Disapble screen saver/energy saver so screen doesn’t turn off
1. Clean Brave profile, enable payments in settings
2. Visit any domain a few times until it shows up on about:preferences#payments. Note the recorded time.
3. Open a tab with that domain and don’t touch the PC for 30 minutes.

Expected: The domain should be recorded with the noted time + 15 minutes.

Actual: The domain is recorded with the noted time + 30 minutes.

**Comment by luixxiul** [comment]
CC @mrose17 do you notice the issue?

**Comment by bsclifton** [comment]
+1 via https://github.com/brave/browser-laptop/issues/7486
> Time Spent is presently too lenient. One site, left open when I walked away from my machine for the evening, was granted a Time Spent amount of over 10 hours. Other users report similarly skewed reports for domains in their list. See https://twitter.com/givanse/status/837495337455501313.
