### ISSUE TITLE
waitForUrl doesn't take into consideration what the active tab is.

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6828]
While fixing #6814 it turned out that we had a test for it which wasn't failing. 
The reason is because we were waiting on a URL via `waitForUrl`, but the code to wait returns just as long as the browser has that tab available regardless of the current tab.

/cc @bsclifton @bridiver 

```
  it('navigates to a suggestion when clicked', function * () {
    yield this.app.client
      .setInputText(urlInput, 'Page 1')
      .waitForVisible(urlBarSuggestions + ' li.suggestionItem[data-index="0"]')
      .click(urlBarSuggestions + ' li.suggestionItem[data-index="0"]')
      .tabByIndex(1)
      .waitForUrl(this.page1Url)
  })
```

In this case it was opening a third tab with `this.page1Url` but the test was expecting it to be in the 2nd tab's position.  The test passes with that.

**Comment by bbondy** [comment]
this can probably cause some intermittent test failures.

**Comment by bridiver** [comment]
that is the expected behavior

**Comment by bridiver** [comment]
the intermittent test failures are caused because it is used incorrectly without taking that into consideration

**Comment by bridiver** [comment]
in fact I'm pretty sure other tests would break if we changed the behavior. The code calls `this.tabByUrl` and is often used when waiting for a new tab to be created. I've also seen instances where it was used to wait for a new tab that had the same url as an existing tab which will also cause test failures. We could change the name to something like `waitForUrlInAnyTab` or allow an optional id to restrict it to a particular tab

**Comment by bbondy** [comment]
Yep that sounds best, I wondered if it was expected or not, but we need to split the uses into 2 different API calls with explicit naming.

**Comment by alexwykoff** [comment]
@bbondy mentioned that we should update tests but this won't be changing :)
