### ISSUE TITLE
Unverified site content - title - shown in browser chrome area beside lock

### ISSUE THREAD

**Issue by mikemaccana** [brave/browser-laptop#683]
The title of the page - unverified site content - is shown in the browser chrome beside the lock:

![github](https://cloud.githubusercontent.com/assets/172594/12922052/dc066244-cf47-11e5-9261-91316d724925.png)

Here is a page that is not GitHub, appearing identical to the real GitHub site: 

![not github](https://cloud.githubusercontent.com/assets/172594/12922035/cd70721a-cf47-11e5-9f2c-b0af7bfbe3f6.png)

Other browsers typically only show crytpgraphically verified data in this area: either the `organization` / `jurisdictionOfIncorporationCountryName` for an EV cert or the verified SAN (domain name) for a domain validated certificate: 

![screen shot 2016-02-09 at 16 13 14](https://cloud.githubusercontent.com/assets/172594/12922188/4d6e63dc-cf48-11e5-9c9a-d470567166de.png)

![screen shot 2016-02-09 at 16 13 34](https://cloud.githubusercontent.com/assets/172594/12922199/545dd2c2-cf48-11e5-9619-a30855d69735.png)

Sites that are not verified as `GitHub, Inc [US]` would not include this information.

Browsers should not show unverified site content next to the lock. The strongest information on the sites identity should be displayed to users, to allow allow them to determine who controls the site.

**Comment by bbondy** [comment]
Just a note that we show the domain first now in the title.

![screenshot 2016-02-09 12 02 35](https://cloud.githubusercontent.com/assets/831718/12923786/0562c8bc-cf25-11e5-9d5a-22e60a103afa.png)

**Comment by mikemaccana** [comment]
That's an certainly an improvement over the current download. But displaying `www.github.com` the same as `www.github.com.mg`, when the certificate contains higher assurance identity information, doesn't help users determine who controls the site.

**Comment by bbondy** [comment]
ok thanks.

**Comment by diracdeltas** [comment]
We don't have plans to show any different UI for EV certificates [1]. If github.com.mg has a valid SSL certificate, the content on the site is verified as coming from `github.com.mg` by the regular process for SSL domain validation even if it's not an EV cert.

You could argue that the real issue is that our SSL UI is too similar to other browsers' EV-only SSL UI. But given that we show the domain name next to the lock now (not just the page title), I'm still inclined to mark this wontfix.

[1] See http://www.usablesecurity.org/papers/jackson.pdf

**Comment by mikemaccana** [comment]
@diracdeltas as discussed on Twitter - why is why I filed this and #684 - picture in picture attacks, as mentioned in the Jackson paper, affect more than just EV certificates, and are better mitigated by making the browser chrome harder to emulate,  see https://github.com/brave/browser-laptop/issues/684

You have an actual signed background checked identity. Not showing that to a user, based on an attack that affects DV and other aspects of browser identity doesn't logically follow.

**Comment by diracdeltas** [comment]
> You have an actual signed background checked identity. Not showing that to a user, based on an attack that affects DV and other aspects of browser identity doesn't logically follow.

Not sure what you mean. My assumption is that if the average user doesn't understand that a green lock icon means actual background-checked identity, it's not a high priority to show it.

**Comment by diracdeltas** [comment]
Just to be clear, I marked this wontfix based on the issue in the title. The other issue of whether to show special UI for EV certificates (like turning the lock icon from grey to green) is separate.

**Comment by mikemaccana** [comment]
Ack and thanks for clarifying Yan. It's getting late in London so will continue in another ticket.

**Comment by diracdeltas** [comment]
no worries, thanks for the input
