### ISSUE TITLE
Performance : 0.13.0 tab switching tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6835]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
performance on tab switching appears to be slower

- Platform (Win7, 8, 10? macOS? Linux distro?):
all, tests so far have focused on os x
win coverage needed

- Brave Version (revision SHA):
0.13.0 rc5

- Steps to reproduce:
Try this once with Brave and once with Chrome

Process 1. set tabs to facebook, news.ycombinator.com, github.com/brave/browser-laptop, nytimes.com

Process 2. set 1 tab to nytimes.com

Process 3. set shields default to off, set tabs to facebook, news.ycombinator.com, github.com/brave/browser-laptop, nytimes.com

Process 4. set shields default to off, set 1 tab to nytimes.com
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Work done for this, I think we can close it:
https://github.com/brave/browser-laptop/commit/6435c2e84f8d6df9121e4fb83bfac6de37d82251
https://github.com/brave/browser-laptop/commit/494b94410df2bf5c20291fc693ccd963788d8827
https://github.com/brave/browser-laptop/commit/c069eae3fe14a0916a968298cd536e388d549682
https://github.com/brave/browser-laptop/commit/658dc4388a547666ac8216c6218628bbeebf736a
https://github.com/brave/browser-laptop/commit/63edc2ee623a8850c0cda7b3c8b87ef55a65ecf0
https://github.com/brave/browser-laptop/commit/4021756af4512cf217216e572402e0dac0a13207
https://github.com/brave/browser-laptop/commit/fd811dbc1fc4f436cb1876dac03c1e27fd7f90de

**Comment by luixxiul** [comment]
@bbondy Do we need QA for this issue specifically?

**Comment by bbondy** [comment]
perf fixes often have regressions but it'll be caught by generic testing.
