### ISSUE TITLE
Performance : 0.13.0 page load tracking issue

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6836]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
page loads appear to be slower

- Platform (Win7, 8, 10? macOS? Linux distro?):
all, primary testing on os x
win coverage needed

- Brave Version (revision SHA):
0.13.0 rc5

- Steps to reproduce:
try this once with brave and once with chrome

Process 1. default shields, start timer, with one tab, open these sites in order : 
 a. facebook.com
 b. wikipedia.org
 c. amazon.com
 d. twitter.com
 e. qq.com
 f. taobao.com
 g. linkedin.com
 h. outlook.com (log into site and load inbox)

Process 2. shields down, start timer, with one tab, open these sites in order : 
 a. facebook.com
 b. wikipedia.org
 c. amazon.com
 d. twitter.com
 e. qq.com
 f. taobao.com
 g. linkedin.com
 h. outlook.com (log into site and load inbox)
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
manual runs were somewhat inconclusive. only 0.13.0 rc5 with shields down was an outlier for poor performance

automation would certainly help so that we can track values over time

**Comment by alexwykoff** [comment]
some sites which could stand to load faster : 

alipay - https://github.com/brave/browser-laptop/issues/3603
qq.com
taobao.com

**Comment by bbondy** [comment]
I did some improvements here but I want to do more, so I'll leave this open.
Work done so far:
https://github.com/brave/browser-laptop/commit/95ade416325978168a02c027e65570333db83d67
https://github.com/brave/browser-laptop/commit/6f9682ade5334d6297ef497dff2bb59ded2cbe0e
https://github.com/brave/browser-laptop/commit/e198468c47a2ee11bc24f35d79c6354358acc162

**Comment by bbondy** [comment]
moving to next milestone since no more work will be done for this one, too risky

**Comment by luixxiul** [comment]
I added `release-notes/include` as this issue will be fixed in the next milestone.

**Comment by luixxiul** [comment]
the milestone was reset to 0.13.3

**Comment by alexwykoff** [comment]
Needs breakdown to more discrete issues.

**Comment by alexwykoff** [comment]
all of the prior mentioned PRs have landed, this was only staying open as a string-on-finger reminder of automation work to be done re: page perf.
