### ISSUE TITLE
Horrible performance on SoundCloud.com with fingerprint protection on

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6840]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you try to listen to any song on [SoundCloud](https://soundcloud.com) with fingerprint protection on, the performance is horrible

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.0 RC5

- Steps to reproduce:
    1. Visit https://soundcloud.com/neilcic/mouth-moods
    2. Ensure your shield settings have:
      - HTTPS everywhere = enabled
      - fingerprint protection = enabled
      - block scripts = disabled
      - block phishing/malware = enabled
    3. Open activity monitor; it should be a low percentage
    4. Click the play button and watch the percentage go up
    5. 
    

- Actual result:
Chrome only uses around 10% - 15% CPU on my MacBook Pro. With FPP enabled, Brave is usually around 45% CPU, sometimes getting as high as 90%.  Even if you switch tabs, it's bad performance.

- Expected result:
CPU usage should never spike that much

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
@bsclifton do you experience the issue? for me the site works smoothly.

**Comment by bsclifton** [comment]
@luixxiul I just tried again (this time with https://soundcloud.com/tareq-ibrahim/osset-dayaa-hiba-tawaji) and performance seems the same with FPP on or off 😄 👍   In both cases, it was around 20%

Thanks for bringing this up!  I think we can close this issue for now as it no longer reproduces
