### ISSUE TITLE
Connection info icon changes to site favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6841]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Connection info icon changes to site favicon

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	5bad531

- Steps to reproduce:
    1. Enter any engine go key and press space
    2. Press backspace to remove the space and revert from the favicon to magnification icon
    3. Repeat the steps couple more times 
    4. Now search with the same search engine go key
    5. Connection info icon is replaced by site favicon and remains same
    
- Actual result:
Connection info icon is replaced by site favicon

- Expected result:
Should retain connection info icon irrespective of how many page load are done on a site

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not seen on stable release

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![connection_favicon](https://cloud.githubusercontent.com/assets/17010094/22271041/82fe886e-e28a-11e6-9e4c-48041141e2a3.gif)

- Any related issues:

**Comment by luixxiul** [comment]
This should have been fixed right?

![g](https://cloud.githubusercontent.com/assets/3362943/22342415/b1bf3d5c-e437-11e6-99cd-f3aaddb3e775.gif)

**Comment by bbondy** [comment]
it should be fixed yes

**Comment by srirambv** [comment]
Alternate QA steps 
1. Visit a site
2. Enter engine go key to change the favicon
3. Open a link in the site which is already opened, URL changes but the engine favicon is retained
