### ISSUE TITLE
Spellcheck can overtake the browser process

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6842]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Spellcheck is enabled and I've noticed it tank the browser process.  You can no-op the check by editing the code here and returning true instead of making the sendSync call:
https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/content/scripts/spellCheck.js#L7

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (but likely all platforms)

- Brave Version (revision SHA):
0.13.0 HEAD of master (63edc2ee623a8850c0cda7b3c8b87ef55a65ecf0)

- Steps to reproduce:
    1. Launch Brave and visit https://github.com/brave/browser-laptop/issues/new
    2. Pull up activity monitor or task manager, keep it next to the Brave window
    3. Type into the textbox (not the title, but the issue details) as fast as you possibly can
    
- Actual result:
I can easily get the browser processes CPU as high as 50%.  The renderer CPU usage is high too, but always lower.

- Expected result:
The browser process CPU usage should remain low and not cause the UI to lock up

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
No. The problem does NOT exist in 0.12.15. In this version, the renderer CPU goes up, but not the browser CPU usage (or if it does, it's negligible)

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #6799

**Comment by luixxiul** [comment]
I've felt the same thing. Thanks @bsclifton for logging the issue and @bridiver for fixing it quickly :-D
