### ISSUE TITLE
Browser crashed after pinning about 7 or 8 tabs

### ISSUE THREAD

**Issue by el-gallo-azul** [brave/browser-laptop#6844]
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
I was attempting to move to Brave as my default browser from Chromium which has been my default browser for many years.

This process required starting a number of webpages, pinning these pages, closing the pinned tabs within Chromium as I went, and then I planned to specify Brave as my default browser.

On the 7th pinned webpage/tab, the browser disappeared unexpectedly. When I restarted the application, all of the pinned tabs had gone. Luckily, I was able to recover them all in Chromium.

I'm too chicken to move to Brave now.

- Platform (Win7, 8, 10? macOS? Linux distro?):

el_gallo_azul@W2600CR-850Pro:~$ lsb_release -rd
Description:	Ubuntu 16.04.1 LTS
Release:	16.04

- Brave Version (revision SHA):

el_gallo_azul@W2600CR-850Pro:~$ apt-cache policy brave
brave:
  Installed: 0.12.8-1
  Candidate: 0.12.8-1
  Version table:
 *** 0.12.8-1 100
        100 /var/lib/dpkg/status

- Steps to reproduce:
    1. Open and pin webpage
    2. I was able to do this until I had pinned 6 tabs.
    3. The application crashed during my attempt to pin the 7th tab.
    
- Actual result:

Application crash and loss of all pinned tabs

- Expected result:

Pin tabs succesfully and then specify as default browser.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

I don't know. Please let me know if this would help to resolve the issue. I won't spend any time on it otherwise. I would very much like to make Brave my default browser.

- Is this an issue in the currently released version?

I don't know. I have the  Ubuntu repository's current version.

- Can this issue be consistently reproduced?

I don't know. I don't want to waste any more time right now.

- Extra QA steps:
    1. None
    2.
    3.

- Screenshot if needed:

NA

- Any related issues:

I updated from Ubuntu 14.04 to 16.04. I have never been able to do that successfully before, and have always had to do a fresh installation from a downloaded image. This time, it seems to have worked, but it _might_ be relevant.

**Comment by bsclifton** [comment]
Closing because this is stale and also because I can't reproduce (using the steps).  I believe the issues described have been resolved

**Comment by el-gallo-azul** [comment]
I suspect that the issue was resolved when I installed the latest version of the software rather than the version available in the Ubuntu 16.04 repository.
