### ISSUE TITLE
HTTP auth dialog has no cancel button

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#6855]
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

When I'm prompted for HTTP auth, there's no cancel button. You have to press Escape to cancel.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.12.15

- Steps to reproduce:
    1. Visit a page that asks for HTTP auth.
    
- Actual result:

No cancel button exists.

- Expected result:

A cancel button should exist.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

- Is this an issue in the currently released version?

No.

- Can this issue be consistently reproduced?

Yes.

- Screenshot if needed:

<img width="437" alt="screen shot 2017-01-25 at 10 22 54 am" src="https://cloud.githubusercontent.com/assets/133786/22299292/26205b90-e2e9-11e6-9a9d-01ca1c2aba4d.png">

**Comment by luixxiul** [comment]
Wow that's should be fixed soon

**Comment by bsclifton** [comment]
Closed with https://github.com/brave/browser-laptop/pull/6857

**Comment by bbondy** [comment]
Works on macOS but I posted a followup here for the wrong styles being used on hover:
https://github.com/brave/browser-laptop/issues/7041
