### ISSUE TITLE
Show DPI value on about:brave

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6856]
When troubleshooting issues for users, it would be extremely useful to have the DPI setting for Windows users shown in about:brave.  For example: 100%, 125%, 150%, etc

Here's an example of what the setting looks like for the user in Windows 10. The defaults are different depending on the manufacturer install. Many laptops default to 125%, the Surface Book defaults to 200%.
![screen shot 2017-01-25 at 9 28 49 am](https://cloud.githubusercontent.com/assets/4733304/22299301/c9d26af2-e2e0-11e6-95a9-bb3fd45456d2.png)

**Comment by luixxiul** [comment]
@bsclifton can this issue be closed in favor of the UI scale feature you have implemented?

**Comment by bsclifton** [comment]
@luixxiul no- the intent for this issue would be to show what scale the user is at.  Also showing what they have set for the UI scale might be a good idea too.  The intent is so that we can determine if any given bug is related to DPI setting. The user could copy/paste this screen to help give us more debugging information

**Comment by luixxiul** [comment]
It would be nice if these values could be displayed as well:

- graphic board name
- graphic board driver
- monitor resolution
- OS revision (build number) next to the OS name

Those would help to track the issue like this: https://community.brave.com/t/regular-blurring-while-loading-is-triggering/8446/5?u=suguru

**Comment by bsclifton** [comment]
@luixxiul some of those are available now via `chrome://gpu/` (starting with 0.19.x) 😄

**Comment by mfainshtein2** [comment]
I would like to give this a try. Where should I begin?

**Comment by bsclifton** [comment]
@mfainshtein2 sorry for the super long response time here- but you should be able to use `window. devicePixelRatio` to get the value. 100% is 1, 125% is 1.25, etc
