### ISSUE TITLE
Bad certificates show regular lock icon

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#686]
@diracdeltas please take a look.

![screenshot 2016-02-09 12 15 43](https://cloud.githubusercontent.com/assets/831718/12924204/f0d57992-cf26-11e5-8822-59ec34765902.png)

**Comment by diracdeltas** [comment]
Already saw it.  Note that the page is actually secure because it doesn't load any content.  The lock is somewhat misleading, I guess, because some people associate it TLS cert validity. Not sure it's worth fixing since this before #227 which will be done later this week anyway.

**Comment by bbondy** [comment]
I guess as long as we store the extra info in SiteInfo to explain the differences.  Closing in favour of #227 sounds fine to me if you think that's right.

**Comment by diracdeltas** [comment]
This was mostly fixed by 824de04a681a4570dd4e12a23736f4482aa7201d - pages with a bad cert will redirect to `about:certerror`, which doesn't show a lock icon. The lock icon might still be visible briefly before the redirect but that is much less noticeable.
