### ISSUE TITLE
URL Suggestion should match the keyed-in character rather than random suggestion

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6860]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
URL suggested sites are not matching with the typed text. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	a37f260
Existing behavior on 0.12.15 as well

- Steps to reproduce:
**Edit: Check extra QA steps for STR**
    ~~1. Do a clean install of 0.12.15/0.13.0 build~~
    ~~2. Import bookmarks of sites starting with a specific character like `times.com`, `theverge.com`, `twitch.tv`~~
    ~~3. Open a new tab and visit YouTube.com~~
    ~~4. Open a new tab and visit Twitter.com~~
    ~~5. Open a new tab and visit twitch.tv~~
    ~~6. Ensure the history contains the list of these sites in the same order~~
    ~~7. Open a new tab an type in `t` and see the suggestion list~~
    ~~8. History list is not in the same order (regression issue)~~
    ~~9. Brave pages are listed only because the letter t is there in `about:about` & `about:autofill`~~
  ~~10. Tabs listing is also not the most recent to the oldest opened link~~
   ~~11. Suggested Top site has YouTube as first suggestion instead of Twitter~~
    
- Actual result:
Suggested list is not based on the most recent opened tab/link or the site starting with the typed in character

- Expected result:
Should show appropriate suggestion based on the typed in char

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. On the clean install open a new tab and type in `b` suggested brave pages still shows `about:about `& `about:autofill`
    2. Should ideally show `about:bookmarks` & `about:brave` rather than `about:about` & `about:autofiill`
    3.

- Screenshot if needed:
0.12.15
![image](https://cloud.githubusercontent.com/assets/17010094/22309386/f9de1194-e342-11e6-9093-f02db8710216.png)
0.13.0
![image](https://cloud.githubusercontent.com/assets/17010094/22309394/fe6aecbe-e342-11e6-80b3-6fdad4c55f37.png)

- Any related issues:
Please change milestone if requried

**Comment by bbondy** [comment]
cc @aekeus if you want to own this line of work?

**Comment by aekeus** [comment]
Sure, I can take this one.

**Comment by jonathansampson** [comment]
@srirambv @aekeus Is this similar (or dupe) to #8982?

**Comment by srirambv** [comment]
@jonathansampson  #8982 covers one part of the issue mentioned here(not showing the recent visited site). The issue on a clean profile providing random suggestions instead of the keyed in character is still there.

**Comment by jonathansampson** [comment]
@srirambv Can we split these two issues out into 2 _Issues_?

**Comment by srirambv** [comment]
Sure not a problem. I will update the title and edit the steps for url suggestion for keyed in character. We can track the most recent url issue in #8982
