### ISSUE TITLE
Blinking black and white screen

### ISSUE THREAD

**Issue by swest100** [brave/browser-laptop#6861]
![brave-2017-01-25_13-38-08](https://cloud.githubusercontent.com/assets/21027496/22310371/4a3e4abe-e30c-11e6-9700-9585da18ed63.gif)

- Did you search for similar issues before submitting this one? I did not see this issue in the resolved or unresolved.

- Describe the issue you encountered: Screen blinks black and white. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Win10 64bit

- Brave Version (revision SHA): 0.12.15.0

- Steps to reproduce:
    1. Open Brave
    2.
    3.
    
- Actual result: Blinking

- Expected result: A functioning browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? Yes, Previous version started blinking. I couldn't solve it so uninstalled, went to Brave website and downloaded today. Same problem. 

- Can this issue be consistently reproduced? Happens every time I open my Brave browser.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed: Included gif above.

- Any related issues:

**Comment by luixxiul** [comment]
Which video card do you use? Is it AMD one?

**Comment by swest100** [comment]
AMD A6-5200 APU with Radeon HD
Graphics 2.00 GHz

**Comment by luixxiul** [comment]
There is a known compatibility issue between AMD card and the browser. Please have a look at https://github.com/brave/browser-laptop/issues/6807 for more info.

**Comment by swest100** [comment]
Thank you. I will try the suggested workarounds.

It still seems strange that Brave worked great for two months then got up
one day and decided to blink.

Thanks again.

**Comment by bsclifton** [comment]
@swest100 if you haven't tried it yet, the work-around should be as easy as adding `--disable-gpu` to the shortcut. Basically, you'd run the following steps:
1. Right click the Brave shortcut and pick properties
2. In the `Target` area, paste in `--disable-gpu` at the end
3. Click Apply and close the window
4. Launch the shortcut you just changed

Screenshot:
![screen shot 2017-01-29 at 10 53 40 pm](https://cloud.githubusercontent.com/assets/4733304/22413542/166aed92-e676-11e6-913a-0346704a5e6e.png)

**Comment by swest100** [comment]
It worked!

Thank you.

**Comment by bsclifton** [comment]
@swest100 I just noticed after writing this that you may want to try this option instead (since disable GPU is more extreme and may completely disable all acceleration):
`--ignore-gpu-blacklist`

**Comment by swest100** [comment]
Thanks again Brian.

Ironically I just did another Brave update and it works perfectly without
the work around.

Go figure.

Sure appreciate your help.

**Comment by bsclifton** [comment]
@swest100 my pleasure! 😄  Let us know if there's anything we could do better or if there's a feature you'd like to see.  Here on GitHub or on our community site:
https://community.brave.com/
