### ISSUE TITLE
First option in Menu/Hamburger is selected by default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6867]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
New Tab option in kabob/hamburgermenu is highlighted by default

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	ebea72a
Verified not happening on RC6 

- Steps to reproduce:
    1. Do a clean install of 0.13.0 RC7
    2. Click on the kabob/hamburger menu
    3. New Tab option is highligted by default
    
- Actual result:
New Tab option is highlighted by default

- Expected result:
None of the options should be highlighted by default and should only highlight on mouse over

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![rc7](https://cloud.githubusercontent.com/assets/17010094/22339349/93a31eac-e3e1-11e6-9b65-eb9f439a5afc.gif)

- Any related issues:

**Comment by srirambv** [comment]
Same on menu as well 
![image](https://cloud.githubusercontent.com/assets/17010094/22339677/c3a626ca-e3e2-11e6-9938-73ba18d94d7f.png)

**Comment by bbondy** [comment]
It will work by reverting this:
https://github.com/brave/browser-laptop/commit/03bf66bd81894b22ca9cc3c3ff8decf5aacede88

So I reverted it for 0.13.0 and we'll treat this as blocking for 0.13.1. Thanks.

**Comment by luixxiul** [comment]
This is not resolved yet on Windows 10 32 bit

**Comment by luixxiul** [comment]
Only menus on title bar. The issue on the kabob menu was fixed

**Comment by NejcZdovc** [comment]
I can't reproduce it. @bsclifton can you please try it out?

**Comment by bsclifton** [comment]
reproduced; the steps above aren't clear, but here they are:

Setup:
-On Windows, go to prefs and disable "hide menu by default"
-On macOS you need to edit code
  - go to main.js and set `customTitlebarEnabled` to true
  - in preferences.js, make sure the `hide menu by default` shows
  - launch and edit prefs, disable the "hide menu by default"

Now, you will always see the menu. You can then click any of the menus and besides expanding the menu, it also selects the first item

**Comment by bsclifton** [comment]
PR addressing this issue was merged after I confirmed the fix; It will be in the next RC 👍

**Comment by srirambv** [comment]
Fixed on Windows 10x64
