### ISSUE TITLE
Clicking on SHA doesn't load the github commit page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6868]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Clicking on SHA doesn't load the github commit page

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.0
rev	ebea72a
Works on 0.13.0 RC 6

- Steps to reproduce:
    1. Do a clean install of 0.13.0 RC7 
    2. Open about:brave
    3. Click on SHA link, new tab opens but doesn't load Github commit page
    
- Actual result:
Doesn't load github commit page

- Expected result:
Should load github commit page in a new tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![rc7](https://cloud.githubusercontent.com/assets/17010094/22339767/0787344c-e3e3-11e6-871e-b4911ac6565e.gif)

- Any related issues:

**Comment by bbondy** [comment]
@bridiver fixed it here
https://github.com/brave/muon/commit/5212c2119d1182f44286843c3a8c33ebfac0047c
