### ISSUE TITLE
overflow indicator on bookmarks toolbar is sometimes hidden

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6869]
**Describe the issue you encountered:**

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.0 RC6 ebea72a

- Steps to reproduce:
    1. Add bookmarks to the toolbar until it is filled.
    2. Resize the window horizontally slowly
    
- Actual result:
  ![overflow](https://cloud.githubusercontent.com/assets/3362943/22340490/f7d0ca10-e430-11e6-8418-9823cea5acbd.gif)

- Expected result:
  The overflow indicator should be displayed always

- Any related issues: #6767 #3525

**Comment by srirambv** [comment]
Overflow indicator is not shown at all when show favicon only is selected its completely hidden. Reimporting the same file puts the folders at the end which shows up the overflow indicator and then behavior changes as reported in issue

Additional QA Steps.
    1. Do a clean install of 0.13.0 RC9
    2. Import large amount of bookmarks so that overflow indicator is shown
    3. Set Text only in settings for bookmark toolbar, overflow indicator is shown
    4. Set Text and Favicon for bookmark toolbar, overflow indicator is still shown
    5. Set Favicon only for bookmark toolbar, No overflow indicator is shown

![overflow](https://cloud.githubusercontent.com/assets/17010094/22369400/90682d70-e483-11e6-9bf0-ea9de908066b.gif)

**Comment by luixxiul** [comment]
Yes I confirm it on Windows 10 64 bit

**Comment by srirambv** [comment]
@bsclifton  can this be pulled into 0.18.x? I see this happening on the latest build and its quite annoying to resize the browser everytime just to get the overflow indicator

**Comment by srirambv** [comment]
On a side note, when you have pinned tabs and then switch to one of the pinned tabs, pressing tab 3 times causes this
![image](https://user-images.githubusercontent.com/17010094/29124293-737462e4-7d10-11e7-9d39-51de28399d82.png)
The first two pinned tabs goes out of view and the only option to restore back to normal is to maximize the window and restore.

**Comment by luixxiul** [comment]
For me this issue is still not solved. @srirambv would you mind checking it on Windows?

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/11507#issuecomment-342071897

> After bookmarking other sites except about pages and editing some of them, the indicator started appearing. I'll search for concrete steps to reproduce the issue.

**Comment by srirambv** [comment]
Confirmed https://github.com/brave/browser-laptop/issues/6869#issuecomment-321258025 still happens on the latest build with a pinned tab. 

This is on the 0.19.80
![image](https://user-images.githubusercontent.com/17010094/32433041-890ac0f6-c2d1-11e7-9687-7040e36f2e61.png)

By default the overflow indicator is missing with bookmarks

**Comment by srirambv** [comment]
https://github.com/brave/browser-laptop/issues/11507#issuecomment-342071897 doesnt make a difference on Windows. No overflow indicator shown

**Comment by cezaraugusto** [comment]
I'm taking this, please ping me first before changing the assignment. The IntObs API might solve this definitely and is already introduced in this release for tabs.

**Comment by alexwykoff** [comment]
Commentary from Kamil, this is still a thing.
