### ISSUE TITLE
 1pass regression in 0.13.0 rc7

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6871]
After investigation it was found that this originated in 0.13.0 rc5

the testing protocol used:
1. rm -rf ~brave
2. launch a target version
3. open prefs and select 1pass
4. auth with app
5. open tab to github.com and go to login modal
6. select 1pass in context menu, select github

**Comment by alexwykoff** [comment]
starting with 0.13.0 rc5 and replicated in rc6, it was found that during step 3 of the protocol above, the extension would not display a validation code to auth with the local app.

**Comment by alexwykoff** [comment]
in rc7 it was discovered that step 6 of the protocol above would not yield a successful login. to the user it would appear as though nothing had happened

**Comment by bridiver** [comment]
going to revert https://github.com/brave/browser-laptop/commit/d4f79bed085c7cf83645a395915c9e72d7d4eb2f and reopen https://github.com/brave/browser-laptop/issues/6791
