### ISSUE TITLE
Extension images in context menu looks bad

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6877]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
![image](https://cloud.githubusercontent.com/assets/17010094/22350478/d10f92c8-e40b-11e6-81b0-f05b29651698.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22350524/100fc6a0-e40c-11e6-9589-1ba02697919e.png)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows x64. @alexwykoff confirmed dnr on OS X

- Brave Version (revision SHA):
Brave	0.13.0
rev	ebea72a

- Steps to reproduce:
    1. Enable Extension and password manager in settings
    2. Right click to bring context menu
    3. Extension images look horrible
    
- Any related issues:

**Comment by bbondy** [comment]
to help triage, could you indicate if this is in 0.12.15?

**Comment by Liunkae** [comment]
Looks fine with 0.12.15 on macOS 10.12.x and Linux Ubuntu 16.04:
![image](https://cloud.githubusercontent.com/assets/19424103/22363008/c2dff7c6-e42c-11e6-8ea7-034bf793de63.png)
![image](https://cloud.githubusercontent.com/assets/19424103/22363045/0a5560c8-e42d-11e6-8aa0-f014cd730a67.png)
Probably Windows-only since the Windows menu items look taller.

**Comment by luixxiul** [comment]
BTW I don't like that icons are not aligned on Ubuntu. Can we fix it? / cc: @bradleyrichter

**Comment by bbondy** [comment]
maybe due to dpi changes @bsclifton

**Comment by bsclifton** [comment]
good call on the DPI issue... since it shows in a native popup control though, I would guess it's correct. Definitely needs some investigation.

If you can estimate a release for this to go in, please assign it one (and then we'll be able to start looking at it accordingly).  Otherwise, let's add it to our backlog.  Might be handy to have a DPI tag too- I'll create one and tag this issue with it

**Comment by srirambv** [comment]
@bbondy @bsclifton The captured image is on 125% DPI. It looks proper only on 100% DPI. Anything above the image looks pixelated like in the screenshot.

**Comment by bradleyrichter** [comment]
It appears that the icons are being scaled up instead of utilizing the larger icon within the extension data file. @srirambv Can you compare this to the toolbar button behavior at the same resolutions?

**Comment by srirambv** [comment]
@bradleyrichter The toolbar button is same on all resolutions. The image set uses both 1x and 2x images and there is no change in the icon resolution(looks good on all resolution)

  
```
1Password
<button data-button-value="aomjjhallfgjeglblehebfpbcfeobpgk" class="browserButton fa extensionBrowserAction extensionButton" style="background-image: -webkit-image-set(url(";file:///C:/Users/Sriram%20BV/AppData/Roaming/brave/Extensions/aomjjhallfgjeglblehebfpbcfeobpgk/4.6.2.90/data/images/toolbar-chrome.png";) 1x, url(";file:///C:/Users/Sriram%20BV/AppData/Roaming/brave/Extensions/aomjjhallfgjeglblehebfpbcfeobpgk/4.6.2.90/data/images/toolbar-chrome@2x.png";) 2x); background-repeat: no-repeat; background-position: center center;"></button>

Pocket
<button data-button-value="niloccemoadcdkdjlinkgdfekeahmflj" class="browserButton fa extensionBrowserAction extensionButton" style="background-image: -webkit-image-set(url(";file:///C:/Users/Sriram%20BV/AppData/Roaming/brave/Extensions/niloccemoadcdkdjlinkgdfekeahmflj/2.1.17/app/images/browser-action-icon-19.png";) 1x, url(";file:///C:/Users/Sriram%20BV/AppData/Roaming/brave/Extensions/niloccemoadcdkdjlinkgdfekeahmflj/2.1.17/app/images/browser-action-icon-38.png";) 2x); background-repeat: no-repeat; background-position: center center;"></button>

LastPass
<button data-button-value="hdokiejnpimakedhajhdlcegeplioahd" class="browserButton fa extensionBrowserAction extensionButton" style="background-image: -webkit-image-set(url(";file:///C:/Users/Sriram%20BV/AppData/Roaming/brave/Extensions/hdokiejnpimakedhajhdlcegeplioahd/4.1.38.67/images/iconset2/19x19_Gray.png";) 1x, url(";file:///C:/Users/Sriram%20BV/AppData/Roaming/brave/Extensions/hdokiejnpimakedhajhdlcegeplioahd/4.1.38.67/images/iconset2/19x19_Gray_2x.png";) 2x); background-repeat: no-repeat; background-position: center center;"></button>

**Comment by bsclifton** [comment]
Awesome, thanks for confirming @srirambv!

**Comment by bsclifton** [comment]
@luixxiul anything that is a native popup we cannot change.  This is due to how the user has their OS configured (font, spacing, etc).  We only have control over our own popups (which in the code are called ContextMenuItem)

**Comment by srirambv** [comment]
This is still very bad on Windows.
