### ISSUE TITLE
include current year in PDF statement copyright footer

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6878]
Fix this:

![0](https://cloud.githubusercontent.com/assets/400552/22353403/0b7d545e-e3d5-11e6-9990-97ee46fcb00b.png)

Test plan:
1. Generate a PDF receipt
2. See that the footer says "(c)2016-YYYY ..."

**Comment by srirambv** [comment]
Extra characters shown where `YYYY` is to be replaced
![image](https://cloud.githubusercontent.com/assets/17010094/22625240/d3a05f20-eb88-11e6-93d5-f592ac34d4d7.png)

**Comment by bbondy** [comment]
moved to 0.13.3

**Comment by mrose17** [comment]
Fixed by #7887

**Comment by luixxiul** [comment]
The extra chars bug might exist with printToPDF. They does not appear if you print manually, though they does if you save the file via the prompt dialog. cf: https://github.com/brave/browser-laptop/pull/7887#issuecomment-290972828

**Comment by darkdh** [comment]
@luixxiul , this is an different issue of printToPDF. Different than you described in https://github.com/brave/browser-laptop/pull/7887#issuecomment-290972828
