### ISSUE TITLE
Add Ubuntu Unity Launcher menu shortcuts

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6887]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
There should be some custom menu shortcuts for the Launcher on Ubuntu (Unity desktop environment). This requires additions to the `brave.desktop` file and integration in Brave itself.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Ubuntu (Unity desktop environment) only

- Steps to reproduce:
    1. Right-click the Brave icon in the Launcher.

- Actual result:
There are no options besides the basic menu.

- Expected result:
There should be some custom options (Firefox has "Open a New Window" and "Open a New Private Window").

- Extra QA steps:
    1. Right-click the Brave icon in the Launcher.
    2. Make sure there are additional menu options besides the default ones.

- Screenshot if needed:
Firefox example:
![image](https://cloud.githubusercontent.com/assets/19424103/22362734/7cd56bb4-e42a-11e6-9420-f77582985b8a.png)

- Any related issues:
#5141 and #6094 (Windows), #3024 (macOS)

**Comment by NejcZdovc** [comment]
I think this can help with integration https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles#Adding_shortcuts_to_a_launcher

**Comment by Liunkae** [comment]
Should be fixed with brave-core. Ubuntu Unity is legacy anyway at this point.
