### ISSUE TITLE
automated test failure: Enpass installs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6889]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/195784610#L4323

- [ ]  1) about:extensions Enpass installs when enabled installs:
     WaitUntilTimeoutError: element (.extensionBrowserAction[data-button-value="kmcfomidfpdkfieipokbalgegidffkal"]) still not visible after 10000ms
      at isVisible(".extensionBrowserAction[data-button-value="kmcfomidfpdkfieipokbalgegidffkal"]") - waitForVisible.js:37:22

- Any related issues: #5097 #6408

**Comment by bbondy** [comment]
This will pass again as soon as electron builds are made.

**Comment by bbondy** [comment]
Disabled here:
https://github.com/brave/browser-laptop/commit/5f977f98d2b2ca7ba2bd79766583a91d56a5032d

I'll keep this open and in this milestone for tracking.  We should be able to close this and revert that commit once we have new muon builds.
