### ISSUE TITLE
remove redundant dateline in contributions PDF

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6896]
here is what we have now:

<img width="974" alt="0" src="https://cloud.githubusercontent.com/assets/400552/22389455/729d24fa-e49a-11e6-8b9f-a831ba1ff6e0.png">
the last line was intended to give a timeframe, but is redundant, so remove it!

**Comment by mrose17** [comment]
Closed in response to useful feedback!

**Comment by willy-b** [comment]
I opened a new PR for this in #6933 per discussion with @mrose17 in https://github.com/willy-b/browser-laptop/commit/a510c87d1598b6e75043bf2924e36643355e4e7e#commitcomment-20667505 and his PR #6897

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/6933
