### ISSUE TITLE
alert() popups should appear below tabs

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#6901]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
JS `alert()` messages appear above the [Line of Death](https://textslashplain.com/2017/01/14/the-line-of-death/), suggesting that alert messages are triggered by Brave the browser and not the webpage.
- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.11.6
- Brave Version (revision SHA):
0.13.0 @ 8ca0127
- Steps to reproduce:
    1. triggger a JS alert. you could open the dev console with Cmd+Alt+J then run `alert("i love pyramids")`
    
- Actual result:
<img width="785" alt="screen shot 2017-01-27 at 21 10 52" src="https://cloud.githubusercontent.com/assets/521861/22394397/245f4ca6-e4d5-11e6-9fac-971d6fe76553.png">

- Expected result:
Alert should appear entirely below browser tabs, within the webpage.
Also probably shouldn't have a Lion icon.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

- Appendix A: Chrome
<img width="663" alt="screen shot 2017-01-27 at 20 57 47" src="https://cloud.githubusercontent.com/assets/521861/22394345/5228d3b6-e4d3-11e6-8099-918f3628129b.png">

- Appendix B: Firefox
<img width="708" alt="screen shot 2017-01-27 at 21 05 11" src="https://cloud.githubusercontent.com/assets/521861/22394377/5abe4c1c-e4d4-11e6-9794-ab74eba3f7d7.png">

**Comment by bradleyrichter** [comment]
+ 1 for inter-mockup humor

**Comment by Liunkae** [comment]
Related issue: #2755 (prevent js alert spoofing attacks)

**Comment by bsclifton** [comment]
Moving to 0.13.4
