### ISSUE TITLE
Update LastPass on our extension server

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6903]
Please retest basic functionality because we pulled in the new version.

Component: LastPass (hdokiejnpimakedhajhdlcegeplioahd)
Chrome store: 4.1.38.67
Brave store: 4.1.35.54
SHA 256: 5cc976ce25cade525dba036b29fa5d6711be2df4f99744d6ac7ad3384e98ceeb

**Comment by luixxiul** [comment]
@bbondy do we need QA?

**Comment by srirambv** [comment]
1. Install 0.13.1 build
2. Enable Lastpass from settings under security
3. Open about:extension, verify Component ID and version matches
