### ISSUE TITLE
Pepper Flash Plugin no longer works after update to v0.13.0 (Linux)

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#6908]
Pepper Flash Plugin no longer works after update to v0.13.0.

I tried repeating the troubleshooting steps from the wiki but to no avail.
Reverting back to v0.12.15 works just fine.

I'm going to go back to using v0.12.15 for the time being but feel free to ask me to test any possible fixes.

Name	Version
Brave	0.12.15
Muon	1.4.31
libchromiumcontent	53.0.2785.143
V8	5.3.332.47
Node.js	6.5.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-34-generic
os.arch	x64

**Comment by luixxiul** [comment]
I notice the same thing on Windows 10 64 bit on http://hulu.jp

**Comment by srirambv** [comment]
I see allow notification on http://hulu.jp on Win 10 x64 with flash enabled (browser upgrade from 0.12.15 to 0.13.0)
![image](https://cloud.githubusercontent.com/assets/17010094/22418308/63e77bee-e6d0-11e6-871a-427e1f525b88.png)

**Comment by luixxiul** [comment]
@srirambv yes I see it too. Please continue to play a stream and see if it is played successfully

**Comment by luixxiul** [comment]
Another report here: https://community.brave.com/t/enable-software-update-in-linux/922/2?u=suguru

**Comment by rogerdc** [comment]
I'm not sure if I'm seeing the exact same thing you're seeing, but here's what I've got: 
 
```
Brave: 0.15.0 
rev: 71fb73001617949528cc6473e288a49e76fcd4d5 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.9.0-2-amd64 
os.arch: x64


roger@rogerhp:/usr/lib/pepperflashplugin-nonfree$ ls -l
total 18368
-rw-r--r-- 1 root root 18801952 Jan 17 09:41 libpepflashplayer.so
-rw-r--r-- 1 root root     2222 Jan 17 09:41 manifest.json
roger@rogerhp:/usr/lib/pepperflashplugin-nonfree$ 
```
From the console: 
```
[1:1:0427/122305.719422:ERROR:ppapi_thread.cc(333)] Failed to load Pepper module from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so (error: /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so: cannot open shared object file: Operation not permitted)
```

**Comment by geekgonecrazy** [comment]
Seems starting with `--no-sandbox` solves this.  Not ideal at all though...  From what I can tell nothing wrong with the permissions on the file

**Comment by AngryPenguinPL** [comment]
Can confirm. This bug is still present in Brave. Trying testing every new release but still is not fixed yet.
Last test made on:

```
Brave | 0.19.35
rev | eda2732
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Linux
OS Release | 4.10.0-35-generic
OS Architecture | x64
```

Flash files in /usr/lib/pepperflashplugin-nonfree/ . Flash enabled in options but sites not detect it even when I allow to use it.

Log from console:

> x@x-Aspire-7551G:~/Programy/Brave-linux-x64$ '/home/x/Programy/Brave-linux-x64/brave' 
> Error: unrecognized flag --icu_case_mapping
> Try --help for options
> Crash reporting enabled
> [10174:10174:1007/183701.734450:ERROR:CONSOLE(51587)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/home/x/Programy/Brave-linux-x64/resources/app.asar/app/extensions/brave/gen/app.entry.js (51587)
> [10174:10174:1007/183701.734668:ERROR:CONSOLE(51587)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/home/x/Programy/Brave-linux-x64/resources/app.asar/app/extensions/brave/gen/app.entry.js (51587)
> [10174:10201:1007/183837.785913:ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_plugin from binding interface: memory_instrumentation::mojom::Coordinator exposed by: content_browser
> **[1:1:1007/183837.788488:ERROR:ppapi_thread.cc(312)] Failed to load Pepper module from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so (error: /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so: cannot open shared object file: Operation not permitted)**

Look at last three lines.

Also looks like above solution from @geekgonecrazy to launch brave with --no-sandbox flags just work and flash starting work correctly.
