### ISSUE TITLE
Get Flashplayer URL not intercepted

### ISSUE THREAD

**Issue by mspaulding06** [brave/browser-laptop#6912]
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

When using VMWare VCenter the link to get flashplayer is not intercepted by Brave.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS 10.12.3

- Brave Version (revision SHA):

0.13.0 (8ca0127)

- Steps to reproduce:
    1. Go to a VCenter login page
    2. Click the link to download flashplayer
    
- Actual result:

Goes to the Adobe Flashplayer download page because the link is not intercepted by Brave.

Link used in VCenter is http://www.adobe.com/go/getflashplayer

- Expected result:

Intercepted by Brave so that Flashplayer can be enabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

- Screenshot if needed:

<img width="548" alt="screen shot 2017-01-28 at 4 11 00 pm" src="https://cloud.githubusercontent.com/assets/216318/22400918/82e06d40-e576-11e6-890c-98a8d69acc65.png">

#6908

**Comment by luixxiul** [comment]
@diracdeltas could you confirm?

**Comment by diracdeltas** [comment]
@mspaulding06 could you send a link where this is happening? also is Flash enabled in Preferences?

**Comment by mspaulding06** [comment]
Sadly, I cannot provide a link since it is an internal server for my company.  Yes, I verified that Flash was downloaded through Brave and enabled properly.  If there's any other information I can gather for you let me know.

**Comment by luixxiul** [comment]
Maybe this is the same case: https://community.brave.com/t/flash-wont-work-on-my-kids-aqworlds-game-site/916 @diracdeltas

**Comment by diracdeltas** [comment]
@mspaulding06 just to confirm, if you go to pandora.com or myspace.com and click on the 'get flash' link in the banner, does that at least work?

**Comment by mspaulding06** [comment]
Yes, using pandora.com I get prompted if I would like to allow the use of flash and everything works.  I will note that the get flash player link is different than the one used by VMWare.

Pandora.com's link: https://get.adobe.com/flashplayer/
VMWare's link: http://www.adobe.com/go/getflashplayer

Does that not make a difference?  Are both supposed to be intercepted by Brave?

According to the Brave code, I think this is what's used to determine if the link should be intercepted:

```javascript
const adobeRegex = new RegExp('//(get\\.adobe\\.com/([a-z_-]+/)*flashplayer|www\\.macromedia\\.com/go/getflash|www\\.adobe\\.com/go/getflash)', 'i')
```

I tested it with the URL I provided and appears that Brave should be catching it.  So, I have to say I am a little confused why this isn't working.

**Comment by luixxiul** [comment]
Actually clicking the latter link displays the notification bar for me on 0.13.0 on Windows 10.

**Comment by diracdeltas** [comment]
it depends on how the 'Get adobe flash player' button is. if it's an element without an `href` attribute, the interception will fail (ex if it uses window.open onclick instead of href).

**Comment by mspaulding06** [comment]
Well, it probably has something to do with the way the page is providing the link then.  If I click on the link I provided in the comment above it prompts me to run flash player like it should.  But that same link from VCenter does not work.  I noticed that there seem to be a lot of redirects happening when I click the link from VCenter.  Not sure if that matters at all.

![redirects](https://cloud.githubusercontent.com/assets/216318/22414890/20f87f84-e678-11e6-9ba1-66926ca8b46d.jpg)

And the element in the page is an `href` as shown below:

![link](https://cloud.githubusercontent.com/assets/216318/22414902/38eb1eda-e678-11e6-84fb-e295ed867167.jpg)

**Comment by srirambv** [comment]
+1 from community. https://community.brave.com/t/flash-wont-work-on-my-kids-aqworlds-game-site/916 
Page redirects to adobe page for download instead of showing allow notification.

![image](https://cloud.githubusercontent.com/assets/17010094/22420290/afc194ce-e6d9-11e6-86ac-b5b9e2eef8dc.png)
