### ISSUE TITLE
Multiple home page URLs stopped working - "Your file was not found"

### ISSUE THREAD

**Issue by JeffStarr** [brave/browser-laptop#6913]
This worked great before the last update. Here is an example of the syntax that worked before:

file:///start.html||https://start.duckduckgo.com/|https://google.com/|https://bing.com/|...

That syntax is common way to specify multiple home page tabs in browsers.

Suddenly it stopped working in version 0.13.0; no home tabs load, only an error tab that says:

Your file was not found
It may have been moved or deleted.
ERR_FILE_NOT_FOUND

Hopefully you can get this fixed soon. I want to continue using Brave, but need that multiple-tab startup or it's a deal-breaker. Thanks again for a great browser.

#3110

**Comment by JeffStarr** [comment]
Updated to add that the error is different depending on the URLs specified in the "My home page is" setting. If the setting (using vertical pipes to specify multiple URLs) begins with a local file, the "Your file was not found" error is displayed. Otherwise, if the setting begins with an HTTP address, like https://google.com, then the error isn't displayed, but only one tab loads up the entire URL, for example:

https://start.duckduckgo.com/|https://google.com/|https://bing.com/|...

..which leads to crazy undesirable results.

Either case, the setting worked great before 0.13.0.

**Comment by Liunkae** [comment]
I can reproduce with 0.13.0 on macOS 10.12.x. I think the pipe `|` is being encoded as part of the URL.

**Comment by Liunkae** [comment]
@bsclifton Could this have been caused by #6086?

Also, do we have any automated tests for multiple home pages?

**Comment by bsclifton** [comment]
@Liunkae no, I don't believe it was caused with that.  If I had to guess, I would think maybe it was caused by the encodeURI in https://github.com/brave/browser-laptop/pull/6404

cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
@bsclifton I tried locally reverting this commit and this is not a cause for this problem. This commit/function is executed only on event `drop`.

**Comment by bsclifton** [comment]
Thanks for checking that out, @NejcZdovc! 😄  

We'll need to investigate further to determine what changed.  It's important to note that we never explicitly enabled this functionality (it just "worked").  The feature itself is captured with https://github.com/brave/browser-laptop/issues/3110

**Comment by NejcZdovc** [comment]
And a side note, this is not related to the file in the url, same problem occure if you use multiple pages

**Comment by srirambv** [comment]
@bsclifton @NejcZdovc  here's what I found 
1. Multiple home pages is not recognized and opened in individual tabs only on browser launch
2. Clicking on home button (with only web links set) opens all the sites in individual tabs
3. If only a file is set as home page, clicking home button loads the file but doesn't load the file on browser launch
4. Local file and web pages set as home page(like above), clicking on home button only loads the sites and not the local file

Also https prefix is not required, I just used the domain names separated with | and it worked

**Comment by srirambv** [comment]
> "Your file was not found" error is displayed.
This shows only when the new tab is set to homepage. Like @Liunkae said | is parsed into `%7C`. But if the new tab is set to dashboard it loads the files and the sites

**Comment by NejcZdovc** [comment]
Will cover all scenarios that you listed above in #6922

**Comment by NejcZdovc** [comment]
@srirambv Can you please check out #6922 if everything is fine. The only thing missing in this PR are tests, other then that it should be done. Thank you

**Comment by srirambv** [comment]
@NejcZdovc verifed #6922  Works perfect as per the test plan mentioned. 👍
