### ISSUE TITLE
tab is scrollable to above with 2 fingers on MBP trackpad

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6914]
**Describe the issue you encountered:** tab is scrollable to above with 2 fingers on MacBook Pro trackpad.

![scroll](https://cloud.githubusercontent.com/assets/3362943/22403389/e723aa1e-e658-11e6-8f68-e67cb5ce3e33.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.13.0

- Steps to reproduce:
    1. Open a new tab
    2. Open https://github.com or any page which is not scrollable (height:100%)
    3. Scroll the page with 2 fingers on trackpad ~~as soon as the page is rendered (within 0.5 sec)~~
    
- Actual result: the page is scrolled

- Expected result: the page should not be scrolled

- Any related issues:

**Comment by luixxiul** [comment]
I found that it was not the issue how early you would scroll the page.

**Comment by Liunkae** [comment]
Actually, scroll bounce every time you scroll past the page bounds is the intended behavior on macOS (#4520; see Safari's behavior). Right now, it only works once per tab (this was introduced with 0.13.0/Chromium 54 for some reason).

**Comment by luixxiul** [comment]
> every time you scroll past the page bounds is the intended

But you should not be able to scroll the page which does not have the scroll bar right?

**Comment by luixxiul** [comment]
@bbondy so wontfix?

**Comment by bbondy** [comment]
I think it's ok, check against Chrome though.
