### ISSUE TITLE
Picking "Brave starts with 'home page'" incompatible with "a new tab shows 'Dashboard'"

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6920]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When you go to preferences, you can set the following:
-Brave starts with: "Home page"
-A new tab shows: "Dashboard"

With these set, the browser will launch with a new tab page shown, not your home page. 

![pasted image at 2017_01_30 08_07 am](https://cloud.githubusercontent.com/assets/9574457/22415282/292e6cec-e6c6-11e6-975b-2399980a56fb.png)

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Go to preferences in Brave 0.13.0
    2. Set Brave to launch with home page set to "https://brave.com"
    3. Set new tab to show "Dashboard"
    4. Quit Brave and relaunch
    5. Notice new tab shows with dashboard (not https://brave.com)
    
- Actual result:
New tab with Dashboard is shown

- Expected result:
Home page is shown

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues:

**Comment by esamson** [comment]
It seems this happens for any choice of "A new tab shows". Whatever I choose there is the one Brave starts with.

**Comment by NejcZdovc** [comment]
Yes, the problem here is that "Brave starts with" is completely ignored
