### ISSUE TITLE
stats are all 0

### ISSUE THREAD

**Issue by jorgheymans** [brave/browser-laptop#6921]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
stats are not calculated

- Platform (Win7, 8, 10? macOS? Linux distro?):
win7
- Brave Version (revision SHA):
was on latest 0.12 until today, now just upgraded to latest 8ca0127 it made no difference
- Steps to reproduce:
    1. just installed brave, used it for a couple of weeks on many sites of which i'm sure use trackers
    2.
    3.
    
- Actual result:
all stats 0
- Expected result:
correct stats
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
did not try this
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/193792/22416648/344bb62a-e6d0-11e6-8bd5-c182464a99b7.png)

![image](https://cloud.githubusercontent.com/assets/193792/22416776/db266440-e6d0-11e6-9d68-8068bb13ee7e.png)

**Comment by bsclifton** [comment]
@jorgheymans can you try a newer version of Brave and confirm if it's still happening?

**Comment by jorgheymans** [comment]
i am running the latest version since a week or so, did not make a
difference. Maybe something to do with the fact that it's a corporate
environment with strict profile management etc ? Just guessing..

**Comment by bbondy** [comment]
I think probably the .dat files which get downloaded are being blocked.  You could try starting from a command promp and I think it would display some warnings in the console.

**Comment by jorgheymans** [comment]
alright will do this and post the logs here

**Comment by jorgheymans** [comment]
also, i am behind a corporate (authenticating) proxy. Could it be that these .dat files are being downloaded during browser start, before i get a chance to put in the proxy creds ?

**Comment by jorgheymans** [comment]
Starting from the cmd line "Brave.exe" does not give any output, couldn't find any options on startup flags on the wiki.

**Comment by bsclifton** [comment]
@jorgheymans if you're still using Brave, can you please let us know if you're still experiencing this? Thanks 😄

**Comment by jorgheymans** [comment]
@bsclifton just installed version 0.18.23 , browsed a couple of sites but the stats remained zero.

**Comment by cezaraugusto** [comment]
@jorgheymans can you confirm if this still a thing or not? thanks!

**Comment by jorgheymans** [comment]
@cezaraugusto in version https://github.com/brave/browser-laptop/commit/f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac it's still present
