### ISSUE TITLE
Tab title is not updated if you switch back using back button

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6927]
- Did you search for similar issues before submitting this one?
yes 

- Describe the issue you encountered:
Tab's title is not updated using urlbar back button. It keeps last accessed tab title

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):
07451654a72e8f6f292d5f045bd513d41a4e4ce3

- Steps to reproduce:
    1. Open a new tab
    2. Go to https://brave.com
    3. Click urlbar Back button
    4. Tab is shown as "Brave Software | Building a Better Web" instead of "New Tab"
    
- Actual result:
Shows as last accessed tab title

- Expected result:
Should show current tab title

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
No. Unreproducible using 0.13.0, 8ca0127 (public release)
- Can this issue be consistently reproduced?
yes

- Extra QA steps: 
Constant fail can be reproduced running below automated test:
```npm run test -- --grep="sets correct title"``` 

> Notice that while url shows "page1", tabTitle shows "page2")

- Screenshot if needed:

- Any related issues:
#5738

**Comment by cezaraugusto** [comment]
root cause 6423cea2d29439f94979773b1b95dc48cfb1e375

/cc @bbondy

**Comment by bridiver** [comment]
I already have a fix for this

**Comment by bbondy** [comment]
wasn't this already the case as in https://github.com/brave/browser-laptop/issues/5813 ?

**Comment by bridiver** [comment]
in either case I have a fix that can go in the next release and also removes some webview events/methods

**Comment by bbondy** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/04de0b0ef7302e979dc072eb500427224893f340 but it's not in master.  Can you push this into master @bridiver and close this issue?
