### ISSUE TITLE
UI elements and their arrangement should be customizable

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#6928]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Users should be able to customize the arrangement of UI elements (reload button, bookmark button, etc.), as in Firefox.

- Screenshot if needed:
Firefox:
![image](https://cloud.githubusercontent.com/assets/19424103/22437960/c1f666cc-e6ef-11e6-8435-a51446609685.png)

- Any related issues:
#246 (advanced UI customization)

**Comment by maverick74** [comment]
This and addons are the most important features for me and the reason why i haven't left Firefox. Would be good to have them in Brave. UI customization doesn't have to be like in FF, but should be as simple as possible

**Comment by LaurenWags** [comment]
+1 from community specific to moving the scroll bar https://community.brave.com/t/movable-scrollbar/5637

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/wasted-space-near-address-bar/7246/3

User specifically mentions putting URL bar and Bookmarks bar on same row.

**Comment by luixxiul** [comment]
By adding `Toolbar` sub menu under `Display` we could hide many stuff:

![clipboard01](https://user-images.githubusercontent.com/3362943/30795460-9c478a80-a208-11e7-9dd0-f140ca0de05d.png)

It seems it is not so hard to implement that.

**Comment by bulrush15** [comment]
I would like to adjust the background colors of the active tab and inactive tabs. I'd like a different bg color for active tabs especially. Great browser! Good job! Using v0.19.105 on Win 7.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/need-to-move-home-icon/22382?u=eljuno

>  Is there any way I can move the Home icon to the right, so it’s grouped together with the Brave icon and that of my password manager?

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/774
