### ISSUE TITLE
How to support third party services such as Typekit?

### ISSUE THREAD

**Issue by adrianleb** [brave/browser-laptop#693]
Since this heavily affects the look and feel of a webpage how are developers expected to work around Brave's blockage when we need to support assets coming from third party services such as Typekit?

**Comment by bbondy** [comment]
do you mean resources being blocked or cookies being blocked?
We only block resources when they are considered to be tracking elements/ads. If you have a specific breakage in mind though, please post.

**Comment by bbondy** [comment]
Closing but please re-open if you have a link of something that is broken
