### ISSUE TITLE
getSiteKey needs field separators

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#6936]
![screen shot 2017-01-31 at 12 39 44 am](https://cloud.githubusercontent.com/assets/549654/22447991/0a8d3dd0-e74e-11e6-80ba-e08ca9916113.png)

marked as a security issue since it allows untrusted data (the site URL) to modify trusted data (the partition number)

i think it would be best for this to land before the site refactor code is released, otherwise you would have to do a siteKey migration from the old format.

**Comment by bbondy** [comment]
Security issue, but for anyone following along this isn't in a release build.
