### ISSUE TITLE
Dashboard photo size

### ISSUE THREAD

**Issue by abhibeckert** [brave/browser-laptop#6937]
Please add some way to disable downloading photos for the "dashboard" page, preferably switching to one embedded in the binary instead of being downloaded.

Based on how long it often takes to download (up to 3 seconds, and I have [100Mb/s fibre](https://www.speedtest.net/my-result/d/2047986)), it's clearly a large image and I'm often using my laptop on an LTE connection where I pay $1 per 100MB of data.

It also doesn't seem to cache reliably, since I'll often see it download an image that I have seen recently.

**Comment by gutigen** [comment]
Please do, it takes a while to load on LTE if signal is not good, quite annoying, especially when I have to restart Brave due to other issues (already tracked).

**Comment by NejcZdovc** [comment]
You can disable image in preferences.

![image](https://cloud.githubusercontent.com/assets/9574457/23091604/1078a7f0-f5ba-11e6-879d-00259d99de6a.png)

**Comment by gutigen** [comment]
I know, but I want image, just either shipped with Brave or better cached (as mentioned in first comment) or/and adjusted to screen resolution ;)

**Comment by NejcZdovc** [comment]
We have to issues for this topic already #7159 and #6503

**Comment by luixxiul** [comment]
Closing this as the questions were answered.

**Comment by bsclifton** [comment]
Thanks for closing @luixxiul!

@gutigen we should be able to address this with #6503.  I'll make sure to give that a +1 bump.  It might be easiest to have Brave download the pictures locally when backgrounds are enabled
