### ISSUE TITLE
change "Publisher Relevancy" options and default

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#6941]
change this:
![1](https://cloud.githubusercontent.com/assets/400552/22465265/b3b69520-e76f-11e6-84fa-8164a30d738e.png)
so the publisher relevancy options are 1, 5, and 10 and the default is 1.

Test plan:
1. enable ledger
2. go to advanced options
3. examine the options and the default

**Comment by bsclifton** [comment]
Moving to 0.13.3- if we have a quick fix, we can pull back to 0.13.2

**Comment by bsclifton** [comment]
Pulled back to 0.13.2- thanks for knocking this out 😄
