### ISSUE TITLE
Brave Payments via Stripe (Credit Card)

### ISSUE THREAD

**Issue by Benjamin-Dobell** [brave/browser-laptop#6942]
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

Attempting to setup a Bitcoin wallet with CoinJar was excruciating and wasted hours of my life - probably much more time than Brave Browser will ever save me.

There's a huge difference between simply not wanting to be tracked by third-parties and have advertisements slammed down our throat, and thinking we need to anonymize (really pseudo-anonymize) our monetary support of websites we've specifically chosen to receive our funds.

i.e. Not all Brave users care about whether our payments (to websites we've specifically approved) are anonymous.

Simply ask me to confirm at the end of the payment cycle which websites will receive the funds, then charge my credit card.  

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS

- Brave Version (revision SHA):

	8ca0127

- Steps to reproduce:
    1. Enable Brave Payments.
    2. Attempt to sign-up at CoinJar.
    3. Jump through hoops until you reach their broken identity verification forms (which don't always work and won't let you delete documents or add additional ones if the wrong document made it into the wrong field).
    4. Get mad.
    
- Actual result:

Mad.

- Expected result:

Happy, because I've supported content creators I value and didn't endure terrible advertisements or have my actions tracked by for-profit third-party trackers that I never consented to.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

I guess after a while getting mad will take too much energy, I suppose sad would be the eventual outcome.

- Extra QA steps:

N/A

- Screenshot if needed:

N/A

- Any related issues:

High blood pressure

**Comment by luixxiul** [comment]
CC @mrose17 for a comment

**Comment by mrose17** [comment]
@Benjamin-Dobell - it is a pain point, for which i apologize. we feel it internally at brave as well since many of our folks are outside the US and can't access the coinbase buy widget.

with that in mind, there are two parallel efforts (one internal, the other external) to resolve this for folks outside the US to provide a minimal friction solution. we will get this fixed, and hopefully soon...

**Comment by zentagonist** [comment]
Closing as will not fix.
