### ISSUE TITLE
Widevine broken in 0.13.0 on Windows

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6948]
It was found that Widevine was not included properly in the Windows build. 

QA Steps:
With a clean profile, download the build.
Visit either netflix.com to play a movie or https://shaka-player-demo.appspot.com/demo/ and select Widevine.

Video should display appropriately.

**Comment by bbondy** [comment]
muon:
https://github.com/brave/muon/commit/dbcdc1993391db38e9fc0e789c3eae0a8218d5f4
muon-winstaller:
https://github.com/brave/muon-winstaller/commit/918d9d5ae88c62aace344029cd7897e0d170fb5f
browser-laptop:
https://github.com/brave/browser-laptop/commit/3298f2a1943581b5b50c294d8eb15002dac67474
