### ISSUE TITLE
prevent browser-level self-xss

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#695]
If you open the webpage console on Facebook, it says:
![screen shot 2016-02-09 at 2 41 09 pm](https://cloud.githubusercontent.com/assets/549654/12933095/3226ea52-cf3b-11e5-9cc9-f455fd0f6890.png)

we should do the same for the browser-level console (cmd+shift+j).

**Comment by bbondy** [comment]
good idea.

**Comment by luixxiul** [comment]
+1
