### ISSUE TITLE
URL address bar adds deleted text back immediately, have to delete twice

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#6956]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

If I'm on a page with a URL like this:

https://www.amazon.com/BraceUP-Adjustable-Wrist-Support-Black/dp/B00ZMZPGMK/ref=sr_1_3_a_it?ie=UTF8&qid=1485897673&sr=8-3&keywords=wrist%2Bsupports&th=1

and I want to get rid of all the params so that the URL is just this:

https://www.amazon.com/BraceUP-Adjustable-Wrist-Support-Black/dp/B00ZMZPGMK

When I click in the address bar and delete the params, the URL immediately auto-completes and adds them back. This results in me clicking in the address bar, deleting the params, and immediately pressing enter, but ending up on the same page because the autocomplete filled the URL parameters back end before I was able to press return.

What I have to do is click in the URL bar, delete the parameters, delete the parameters again after the autocomplete kicks in (provided I remember to wait and do so), then press return. It's quite annoying, really.

I'll put a gif of it in the screenshots area below.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.13.0 (8ca0127)

- Steps to reproduce:
    1. Go to https://www.amazon.com/BraceUP-Adjustable-Wrist-Support-Black/dp/B00ZMZPGMK/ref=sr_1_3_a_it?ie=UTF8&qid=1485897673&sr=8-3&keywords=wrist%2Bsupports&th=1
    2. Click in the URL bar, and delete some part of this URL, e.g. everything after `B00ZMZPGMK`
    3. Notice that everything you deleted is back.
    
- Actual result:

The text I deleted comes back.

- Expected result:

The text I deleted should not be there anymore.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

- Screenshot if needed:

![screen recording 2017-01-31 at 03 25 pm](https://cloud.githubusercontent.com/assets/133786/22485420/48c44f08-e7cb-11e6-9e3f-50b6b774ab09.gif)

**Comment by Liunkae** [comment]
I think this would be fixed by #6537 (URL autocomplete should offer the option of only completing the hostname).

**Comment by Liunkae** [comment]
It looks like this has been fixed by PR #7534 and will be included in 0.14.0.
