### ISSUE TITLE
Shield menu drop down has scroll bars

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6959]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Shield menu drop down has scroll bars

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, @alexwykoff confirmed no scrollbars on Windows i32

- Brave Version (revision SHA):
Brave	0.13.1
rev	a44d043

- Steps to reproduce:
    1. Do a clean install of 0.13.1
    2. Visit http://slashdot.org
    3. Click on Shields menu, both drop down has scroll bars
    
- Actual result:
Both drop down has scroll bars

- Expected result:
There should not be any scroll bars in the drop down menu

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22488619/08fb9468-e80b-11e6-83c1-4ef62d35ebfc.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22488634/1546c5ee-e80b-11e6-924d-145e071375d9.png)

- Any related issues:

**Comment by srirambv** [comment]
Reload button alignment is off as well.

**Comment by bbondy** [comment]
@bsclifton putting this in 0.13.2

**Comment by luixxiul** [comment]
@bsclifton Haven't those actually been fixed with your refactoring of the dropdown form #6689 ?

**Comment by bsclifton** [comment]
@luixxiul good call- they have been fixed (BTW- you did the styles, I just did the JS) 😄  I verified on both macOS and Windows

![screen shot 2017-02-01 at 10 59 32 am](https://cloud.githubusercontent.com/assets/4733304/22519562/f3b47bf2-e86d-11e6-8889-6098e0d86ba2.png)

![screen shot 2017-02-01 at 11 01 30 am](https://cloud.githubusercontent.com/assets/4733304/22519565/f74d309c-e86d-11e6-8136-22a6913a74b3.png)
