### ISSUE TITLE
PSL-based 3rd party check is making facebook slow

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#696]
Reverting 75c20334c2b53d95a0e8b62f4e0bd33fb3c967c6 fixed it

**Comment by bbondy** [comment]
I noticed this too but didn't know it was because of this. Thanks.

**Comment by bbondy** [comment]
if we can't fix by tomorrow we should strip www. and revert.

**Comment by diracdeltas** [comment]
I have a fix, pushing soon
