### ISSUE TITLE
Update text for close tab settings

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#6960]
## Test Plan
- text's for close tab section should match this:
![image](https://cloud.githubusercontent.com/assets/9574457/22488929/15a22862-e815-11e6-9a10-32dc9b7f14e9.png)

(NOTE: this task is a sub-task of #2137)

**Comment by luixxiul** [comment]
I reset the milestone to `0.13.3` following @bbondy

**Comment by Liunkae** [comment]
"Select **it's** parent tab" should be "Select **its** parent tab".
