### ISSUE TITLE
truthkings.com - ad is blocking content (site interstitial ad overlay) 

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#6962]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Reported by @alexwykoff - there's an annoying interstitial overlay w/a facebook social button blocking the content on truthkings.com
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (reported) - windows10 reproduced

- Brave Version (revision SHA):
0.13.0
- Steps to reproduce:
    1. Go to https://truthkings.com/starbucks-stocks-plummet-company-refuses-americans/#
    2. Get annoyed by modal/interstitial ad 
    3. 
    
- Actual result:
<img width="1354" alt="truthkings com-interstitial-brave-desktop-01312017" src="https://cloud.githubusercontent.com/assets/8979240/22489939/17d505a0-e7cf-11e6-93f7-574566c39bf2.png">

- Expected result:
![truthkings com-expected-brave-desktop-01312017](https://cloud.githubusercontent.com/assets/8979240/22489984/5347a980-e7cf-11e6-9f90-9830ef894509.PNG)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

A few things going on here - need further investigation. Overlay is invoked from the page level, but blacklist attempts result in different domains being called.

**Comment by lukemulks** [comment]
1p wordpress script for the overlay, `boxzilla`
`https://truthkings.com/wp-content/plugins/boxzilla/assets/js/script.min.js?ver=3.1.10`

**Comment by Jacalz** [comment]
Easy fix is to enable fingerprinting protection
