### ISSUE TITLE
Make Brave rebrandable

### ISSUE THREAD

**Issue by michaelmilkov** [brave/browser-laptop#6963]
- Describe the issue you encountered:
Re-brand/change name from 'Brave' to 'Brav'
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):
0.13.0

Hello. I have a problem. I want to re-brand the Brave and to change it's name and successfully to build it. 
I am editing the file 'buildPackage.js' like changing every 'brave' to 'brav'. Also I am editing 'braveDefaults.nsi' and 'windowsInit.js' because I want NSIS to generate bravDefaults.exe. 

Around 2 months I am still here and I can not build it.. Here is something interesting.. When I delete electron-packager (brave version) and install official electron-packager 0.14.15 and edit the buildPackage.js like this:

> cmds = cmds.concat([
>   '"./node_modules/.bin/webpack"',
>   'npm run checks',
>   'node ./node_modules/electron-packager/cli.js . Brav' +
>     ' --overwrite' +
>     ' --ignore="' + ignoredPaths.join('|') + '"' +
>     ' --platform=' + process.platform +
>     ' --arch=' + arch +
>     ' --electron-version=1.4.15' +
>     ' --icon=' + appIcon +
>     ' --asar=true' +
>     ' --app-version=' + VersionInfo.braveVersion +
>     ' --build-version=1.4.15' + 
>     ' --protocol="http" --protocol-name="HTTP Handler"' +
>     ' --protocol="https" --protocol-name="HTTPS Handler"' +
>     ' --version-string.CompanyName="Brave Inc."' +
>     ' --version-string.ProductName="Brave"' +
>     ' --version-string.Copyright="Copyright 2016, Brave Inc."' +
>     ' --version-string.FileDescription="Brave"'
> ])

is generating all files like a charm without errors but It's not working. When I try to open it, it just not works but is opening a process in the system. 

When I try with the brave electron-packager I am getting this error:

> Fatal error: Unable to load file
> undefined
> 
>     at ChildProcess.exithandler (child_process.js:211:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:885:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
>   killed: false,
>   code: 1,
>   signal: null
>  
>   buildPackage failed

Can I get some help please? It's urgent and I'll be so thankful If someone gonna help me with this issue. Thank you!

**Comment by bbondy** [comment]
This is not something we're actively working on, but acknowledge that others might want to rebrand it. So I generalized the title to that.  We would support a patch upstream to make it more configurable but unfortunately this isn't a priority for us at this time and we don't have anyone that's not already triple booked on other priorities.
