### ISSUE TITLE
Re-add newtab background images (as an option)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6965]
## Test plan
1. Launch Brave and visit about:preferences#tabs
2. Default setting should be true
3. Open new tab; verify backgrounds are shown
4. Close new tab and change setting to false
5. Open new tab; verify gradients are shown

## Automated tests
```
npm run unittest -- --grep="NewTab component unit tests"
```

## Original issue text

Because of high memory usage bug in chromium, background images on newtab page were removed here:
https://github.com/brave/browser-laptop/commit/94a620a0af13a8656ff15e9c16bdfe0673dfe951

This task is to track re-adding it, but this time as an option, and we can enable it by default once the memory problem is fixed.

**Comment by dschwank** [comment]
+1 would be great to have this as an option!

**Comment by dschwank** [comment]
Yeah - the switch is implemented and works fine! Thanks!
