### ISSUE TITLE
UI improvements for Payments panel

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#6966]
Per @bradleyrichter request:

1. change string from `auto-include sites` to `auto-include`
![pasted image at 2017_01_31 05_25 pm](https://cloud.githubusercontent.com/assets/4672033/22492074/f9c37e9e-e80e-11e6-9c0a-b28cfc6aff76.png)

2. all strings goes grey except for active (on) switch
![pasted image at 2017_01_31 05_25 pm 1](https://cloud.githubusercontent.com/assets/4672033/22492073/f9c2e182-e80e-11e6-8d7a-c95910e06ec6.png)

3. smaller slides for "show only included sites" and publishers
![pasted image at 2017_01_31 05_26 pm](https://cloud.githubusercontent.com/assets/4672033/22492075/f9c866ac-e80e-11e6-81e8-8f38254fbf4c.png)

**Comment by luixxiul** [comment]
The milestone was moved to 0.13.3

**Comment by bradleyrichter** [comment]
looks good...
