### ISSUE TITLE
 regression: spellcheck missing since 0.13.0 for linux builds

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6967]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Spellcheck underline did not display in 0.13.1

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested all platforms, regression on Linux

- Brave Version (revision SHA):
Discovered in 0.13.1, regression started in 0.13.0

- Steps to reproduce:
    1. visit www.wordcounter.net
    2. misspell some words in the input field
    3. check for underlines
    
- Actual result:
Currently no underlines or context menu suggestions appear

- Expected result:
Misspelled words should be underlined, right-clicking on the word should give suggested alternatives.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="1308" alt="screen shot 2017-01-31 at 8 40 17 pm" src="https://cloud.githubusercontent.com/assets/1434040/22493522/4ea7aade-e7f6-11e6-9add-cb467f67581f.png">
<img width="288" alt="screen shot 2017-01-31 at 8 42 20 pm" src="https://cloud.githubusercontent.com/assets/1434040/22493527/52be292c-e7f6-11e6-84a9-e4a8771de104.png">

- Any related issues:

**Comment by bbondy** [comment]
This is actually working the same for me in 0.12.15 and 0.13.0 if you have default lang en_US configured, but for me I had en_CA and so it wasn't working in both 0.12.15 and 0.13.0.  I did a fix to always fallback to en_US. I would have thought you'd of been on en_US though.  So let's see if it fixes it for you too, but it definitely works and fixes it for me.

**Comment by bbondy** [comment]
This never worked even on 0.12.15 and before by the way. 
The original issue reported here is being fixed in
https://github.com/brave/browser-laptop/issues/7015
