### ISSUE TITLE
 regression: flash not working on linux since 0.13.0

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#6970]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Flash will not load despite user request.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows, OS X , and Linux, issue only reproduced on Linux.

- Brave Version (revision SHA):
0.13.0 (https://github.com/brave/browser-laptop/commit/8ca012746331c78c65c91cde07db4b2a6b2b97b8)

- Steps to reproduce:
    1.  Visit homestarrunner.com and attempt to play flash.
    
- Actual result:
Flash does not load.

- Expected result:
Flash should load at user request.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by CliqueBait** [comment]
Duplicate issue I think: https://github.com/brave/browser-laptop/issues/6908

**Comment by bsclifton** [comment]
Definitely a dupe; thanks, @CliqueBait 😄  Hopefully, we'll have this fixed soon
