### ISSUE TITLE
Command+Click doesn't set parent frame correctly

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6971]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
If you command+click a link it should glue it to the current tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.0 and 0.13.1 official

- Steps to reproduce:
    1. Open 2 tabs
    2. Go to the first tab and load brave.com
    3. Command + click on a link
    
- Actual result:
It opens in position 3

- Expected result:
It should open in position 2

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:

**Comment by bbondy** [comment]
doh duping to https://github.com/brave/browser-laptop/issues/6907

**Comment by bbondy** [comment]
Actually I'm going to re-open this to just fix the bug that exists and we can see what to do about the setting in general in the other issue. This is just to fix the regression.

**Comment by NejcZdovc** [comment]
Adding some additional info:

the value is not correct in `app/browser/tabs.js`
`const openerTabId = !source.isDestroyed() ? source.getId() : -1`
this line in `tabs.js` return `1`
but only for `add-new-contents`, for `open-url-from-tab` it’s returning correct number (didn’t test it but I assume so)

**Comment by NejcZdovc** [comment]
Some steps how to test it:

1. pin tab (in my case https://twitter.com/brave)
2. restart browser
3. go to the pinned tab
4. with middle mouse click on first twitter link
5. go to freshly opened tab
6. click with middle mouse button on any link in the header 
7. go to freshly opened tab

now you should have always the same number and you can reproduce it infinitely
After that you can click on new tab
open fresh page and middle mouse click on a link and value is still the same (edited)
please let me know if you can reproduce it

And some gifs (problematic is `add-new-contents`):
![untitled](https://cloud.githubusercontent.com/assets/9574457/22523130/8281759c-e8be-11e6-8ba7-ce5c07cbabbb.gif)
![untitled1](https://cloud.githubusercontent.com/assets/9574457/22523129/827cc89e-e8be-11e6-9a0b-2b3604c85dbb.gif)

In this gifs I added console log in `app/browser/tabs.js` on this lines: 
![image](https://cloud.githubusercontent.com/assets/9574457/22523195/c29f0068-e8be-11e6-9ca7-6f243a107e65.png)

**Comment by bbondy** [comment]
works now

**Comment by NejcZdovc** [comment]
I tried my scenarios and it's working. Great job all
