### ISSUE TITLE
Unable to see Brave UI with development build

### ISSUE THREAD

**Issue by mspaulding06** [brave/browser-laptop#6976]
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

I am unable to get the UI to load when running Brave from a git repository clone.

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS 10.12.3

- Brave Version (revision SHA):

296c6d6ff245600ca279334cf731529983937cc2

- Steps to reproduce:
    1. Follow the README directions to install dependencies
    2. Run `npm run watch`
    3. Run `npm start`
    
- Actual result:

Window for Brave loads with no UI visible.

- Expected result:

See the browser UI.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

- Is this an issue in the currently released version?

Not sure.

- Can this issue be consistently reproduced?

Yes.

- Screenshot if needed:

<img width="778" alt="screen shot 2017-01-31 at 10 43 53 pm" src="https://cloud.githubusercontent.com/assets/216318/22497675/2fcbb864-e808-11e6-9c37-08d0061fbe09.png">

- Any related issues:

From the screenshot above you can see that the debugging console is showing that it is unable to contact the server backend for Brave.  I'm not sure why that is.  If I curl those URLs from the command line I can retrieve them just fine.  I've also run this same process on a RHEL-flavored Linux box and was able to successfully get the UI to show up.  I think this is just a mac problem.

**Comment by Benjamin-Dobell** [comment]
I also had an issue with the browser UI never loading (also macOS). I'm not sure precisely what went wrong, however previously I was following docs/wiki directly `npm install` etc. 

Since that didn't work I reinstalled with yarn instead:

```
yarn
yarn run watch
```

New shell:

```
yarn start
```

Now everything seems to work as expected.

**Comment by mspaulding06** [comment]
Hm, well, that didn't solve the problem for me.  And just so it's clear which dependencies I used, I built Brave using Node v6.1.0 as specified in the docs.  After the above suggestion I used brew to install yarn which as a dependency pulled in Node v7.5.0 as well.  So, I ran the build with yarn and the newer version of Node with the same result as before, no difference.
