### ISSUE TITLE
Automated test failure on tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6981]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/197222628#L4668
https://travis-ci.org/brave/browser-laptop/builds/197216157#L4689
https://travis-ci.org/brave/browser-laptop/builds/197205697#L4673
https://travis-ci.org/brave/browser-laptop/builds/197196928#L4660

- [ ]  5) tab tests back forward actions sets correct title:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getText(".tab.active .tabTitle") - tabTest.js:47:23

- Any related issues: #6408

**Comment by bsclifton** [comment]
Failing in master currently:
```
npm run test -- --grep="tab pages basic tab page functionality tabs per page setting takes effect immediately"
```

**Comment by luixxiul** [comment]
Just in case I changed the milestone of the issues which have been tagged with `automated-tests`  to 0.14.0. Please close them, if they have been fixed already. 

When closing, if known, please add the commit rev or PR number for tracking. Thanks.

@NejcZdovc could I ask you to investigate the issue, if you have time? Here's the list of the issues, whose milestone is 0.14.0: https://github.com/brave/browser-laptop/issues?q=is%3Aopen+label%3Aautomated-tests+milestone%3A0.14.0

**Comment by NejcZdovc** [comment]
@luixxiul will do it tomorrow

**Comment by cezaraugusto** [comment]
Test pass on master so I'm going to close.

```
npm run test -- --grep="back forward actions sets correct title"
```
