### ISSUE TITLE
Make drop down list same size

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6982]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Drop down list in Tabs settings are of different sizes. Should be same size

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	fe018d5

- Steps to reproduce:
    1. Install 0.13.2 Preview 1 
    2. Go to settings page and select tabs
    3. First drop down which only contains numbers is bigger than the second drop down which contains text
    
- Actual result:
Drop down are of difffernt size

- Expected result:
Should be of same size

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
NA

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22504949/c4cb8224-e870-11e6-97ae-c090a3db220a.png)

- Any related issues:

**Comment by luixxiul** [comment]
I think it is intended and am even not sure if doing so would make UX better actually.

See: https://github.com/brave/browser-laptop/issues/2137#issuecomment-276525852

**Comment by luixxiul** [comment]
CC @bradleyrichter for your thought

**Comment by luixxiul** [comment]
Actually setting a fixed width isn't a good idea in terms of l10n

**Comment by srirambv** [comment]
Both the drop down can be made the size of the first drop is way it would avoid all l10n issues. The drop down which contains text should ideally be bigger for l10n values. That's the reason I said make the drop down to be of same size.

**Comment by srirambv** [comment]
Comparison of all drop down lists in settings page 
![image](https://cloud.githubusercontent.com/assets/17010094/22505298/a3aff334-e872-11e6-83ae-6ac0565260c5.png)

**Comment by NejcZdovc** [comment]
The problem is that we use different components, for numbers it's used `SettingDropdown` which has hard coded width `280px`, for tab activated we use basic `FormDropdown` which don't have fixed width.

**Comment by luixxiul** [comment]
> the drop down can be made the size of the first drop

I think we need to tackle this with JS. Sorry if I am wrong

**Comment by NejcZdovc** [comment]
I agree this should be the same, will fix it in this PR #6961

**Comment by luixxiul** [comment]
CC @bradleyrichter for a final say

**Comment by NejcZdovc** [comment]
I think this should unified. But if we would like to have dynamic `SettingDropdown` this not part of this issue and we should open another one.

**Comment by NejcZdovc** [comment]
Added fix into #6961

**Comment by luixxiul** [comment]
Let's wait for another mockup, don't be hasty

**Comment by NejcZdovc** [comment]
@luixxiul it was my mistake here, that's why I fixed it. Everywhere else (on all preference pages) we use `SettingsDropdown`, but only in this example I used `FormDropdown`. This is the reason why I added fix right away.

**Comment by luixxiul** [comment]
@NejcZdovc ok got it

**Comment by bradleyrichter** [comment]
Ideally the number drop is narrow and text drop is as wide as needed for efficient l10n. 

Since we are only using one column in prefs, the widths could somehow be dynamic based on the longest string plus a margin. But this makes the component more detailed. Hmmmm....

**Comment by srirambv** [comment]
Closing the issue as it looks fixed. All dropdowns are of same size now.
