### ISSUE TITLE
Allow users to customize User Agent string in Brave

### ISSUE THREAD

**Issue by Weej1** [brave/browser-laptop#6983]
Hi Im a very new user to Brave and I was wondering: is it possible to create your own UserAgent string? And if yes, how? I ask this because my office seems to use the UA string to determine what Web mail experience I get. Using Chromium or Firefox I get the full Outlook Web Access. using brave, I get the lite version.

- Did you search for similar issues before submitting this one?
Yes, but I couldnt find one specific. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu Gnome

- Brave Version (revision SHA): 	0.13.0 8ca0127

**Comment by bsclifton** [comment]
@Weej1 I know this is embarrassingly late, but there is no way in the UI to change your user agent. I'll update the issue to instead be worded to add that functionality

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1056
