### ISSUE TITLE
Enabling Enpass causes browser to hang

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6984]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered: 
Enabling Enpass password manager from settings causes the application to hang and close forcefully

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	fe018d5

- Steps to reproduce:
    1. Do a clean install of 0.13.2 preview 1
    2. Enable Enpass as password manager under settings
    3. Browser hangs and gets closed forcefully
    4. Running from console shows error 
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'populate' of null
    at EventEmitter.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.13.2\resources\electron.asar\browser\api\extensions.js:487:49)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.13.2\resources\electron.asar\browser\api\web-contents.js:164:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```
Enpass was not installed while testing this.
    
- Actual result:
Browser hangs 

- Expected result:
Should enable password manager if app is installed, if app is not installed should do nothing

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
NA

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![enpass1](https://cloud.githubusercontent.com/assets/17010094/22508898/e23768d8-e883-11e6-9238-d091d21706d1.gif)

- Any related issues:

**Comment by bbondy** [comment]
seems like either this never worked or the muon support changed in v54, I think we'll have to hide the option.

**Comment by bbondy** [comment]
We'll use this bug for adding that support but it isn't a priority vs other things. I'll add a new bug for tracking hiding the setting.

**Comment by luixxiul** [comment]
Enpass was hidden again with #10232. Let's revisit this one after it is shown. Tracked on https://github.com/brave/browser-laptop/issues/7778

**Comment by grand-lotus-iroh** [comment]
I too wish Enpass worked with Brave. I don't mind using Firefox but I would like to use Brave.
