### ISSUE TITLE
documentation: .MSI installer is for system admins

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6985]
**Describe the issue you encountered:**

Edit https://github.com/brave/browser-laptop#downloads on README.md based on 

https://github.com/brave/browser-laptop/issues/2948#issuecomment-238004193

> The MSI file is only for system administrators and requires special steps.

and https://github.com/brave/browser-laptop/issues/2948#issuecomment-269906538

> Note that the MSI is not meant to be a general installer, it should be the same as Slack though and meant for network installs for admins:
https://get.slack.help/hc/en-us/articles/212475728-Deploy-Slack-via-Microsoft-Installer

- Any related issues: https://github.com/brave/browser-laptop/issues/2948#issuecomment-276659756

**Comment by bbondy** [comment]
we aren't going to produce them for now
