### ISSUE TITLE
Verified publisher icon not properly aligned

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#6986]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Verified publisher icon not properly aligned

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	fe018d5

- Steps to reproduce:
    1. Install 0.13.2 and enable brave payments from settings
    2. Visit a verified publisher site to add an entry in the list
    3. Verified publisher icon is not aligned properly
    4. Rank, View, Time Spent & % values are left justified whereas Site and remove and include are center justified
    
- Actual result:
Verified publisher icon is not aligned properly

- Expected result:
Should be properly aligned

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
NA

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22514043/f73858a2-e895-11e6-96ad-c9739ce74f2b.png)

- Any related issues:
cc: @mrose17

**Comment by bsclifton** [comment]
This is intentionally spaced onto the column divider, right @bradleyrichter?  For example, you had shared this picture:
![image](https://cloud.githubusercontent.com/assets/4733304/22514803/b6fd89ac-e85d-11e6-8cbc-49a109975ecc.png)

**Comment by bradleyrichter** [comment]
we may adjust this slightly in the near future because "rank" is probably going away.
