### ISSUE TITLE
Remove MSI from releases

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6988]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
MSI is shown on each release but it currently has issues.  For example, see:
- #6985 - documentation: .MSI installer is for system admins
- #2948 - MSI installer fails to complete setup

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows

- Brave Version (revision SHA):
All releases

- Steps to reproduce:
    1. Go to https://github.com/brave/browser-laptop/releases
    2. Notice the MSI package is there
    
- Actual result:
MSI package is shown with each release

- Expected result:
MSI package should not be shown until we have fixed issues and provided documentation

**Comment by bsclifton** [comment]
@bbondy assigned you since you had mentioned it recently 😄   Let me know if I can help (I can help go through old releases to delete the MSIs)

**Comment by bbondy** [comment]
I'll just fix moving forward, I think there's an option I can use when building the installer not to include msi.

**Comment by srirambv** [comment]
Added `QA/no-qa-needed` as it not related to any environment.
