### ISSUE TITLE
windowscentral.com crashes renderer on Windows 7

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#6989]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Visiting windowscentral.com appears to cause the renderer process to crash.  After the crash, if you try to navigate anywhere else in the same tab, the page is unusable (doesn't respond to mouse, etc)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7, x64

- Brave Version (revision SHA):
0.13.1 (9dd06f9)

- Steps to reproduce:
    1. Find a machine or VM with Windows 7, x64
    2. Launch Brave and visit http://www.windowscentral.com/
    3. Notice page load... but then quickly crash
    
- Actual result:
Renderer crashes and shows the sour face
![screen shot 2017-02-01 at 11 35 27 am](https://cloud.githubusercontent.com/assets/4733304/22520685/93e27f80-e872-11e6-8302-faf8ea0c04f8.png)

If you visit other pages after this, they will render, but the page is unusable. You have to close the tab and open again.

- Expected result:
Renderer should not crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

cc: @bridiver

**Comment by ykhabins** [comment]
Just upgraded brave on Windows 10, 64-bit OS u to 0.13.1 version.
Unfortunately, the 'sour face' shows up.

**Comment by bsclifton** [comment]
cc: @jonathansampson

**Comment by jonathansampson** [comment]
Also reported [on Twitter](https://twitter.com/AdultMutiTurtle/status/829671566984126464).

For now, enabling *Block Scripts* on Windows Central will resolve the issue. We'll be working to identify the root cause in the meantime.
