### ISSUE TITLE
Hide Enpass support

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#6991]
Seems like muon doesn't support enpass properly yet:
https://github.com/brave/browser-laptop/issues/6984

So we should remove the toggle for now.  

For QA: Just make sure you can't turn on Enpass, no option exists.

**Comment by SheepDomination** [comment]
Any progress on Enpass support ? I want to begin using Brave but without Enpass support, I'm restricted.

**Comment by omarzd** [comment]
It's hidden, but can I still try it out? How can I install it?
