### ISSUE TITLE
Running with URL argument doesn't load the URL

### ISSUE THREAD

**Issue by aironou** [brave/browser-laptop#6994]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Running "brave SOME_URL" doesn't load the URL.
In version 0.12.15 that's works.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch Linux (64 bits) - 4.9.6-1-ARCH

- Brave Version (revision SHA):
Brave: 0.13.1 
rev: 9dd06f9463d155291efdb419ad0df4c2df16b611 

- Steps to reproduce:
    1. Open terminal
    2. Run "brave https://ddg.gg"

- Actual result:
Opens or focus on (if already opened) Brave, but doesn't load the URL passed

- Expected result:
Opens or focus on (if already opened) Brave and load the URL passed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Maybe, related: #3035

**Comment by luixxiul** [comment]
> Run "brave https://ddg.gg"

I didn't know we could load the URL like that way / CC: @bbondy

**Comment by Liunkae** [comment]
Related: #388

**Comment by NejcZdovc** [comment]
On mac I can do something like this: `open Brave.app -- https://www.twitter.com`

**Comment by aironou** [comment]
@NejcZdovc I created a local bin for Brave, passing `-- `  before the URL and that's works. 
Thank you!
