### ISSUE TITLE
Close button spacing incorrect on tabs without icons

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#7005]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: The close button on a tab without an icon (eg `about:newtab`) is spaced further away from the right edge of the tab due to the lack of an icon to push it over.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 9dd06f9

- Steps to reproduce:
    1. Open a tab to any page with a favicon.  Optionally, open a second tab to a page with no favicon, noting that the browser supplies a generic icon.
    2. Open a new tab.
    3. Hover your mouse cursor over each tab to reveal the close button.  Note that the spacing is inconsistent between tabs with icons and the new tab without an icon.  This is true regardless of which tab is active.
    
- Actual result: The new tab has a noticeable amount of extra space between the close button and the right edge of the tab.

- Expected result: The spacing should be the same.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Extra QA steps: None

- Screenshot if needed: 
![tab-close-spacing-before](https://cloud.githubusercontent.com/assets/13000059/22563730/d8c699e6-e94f-11e6-9fc6-a35c9aacc708.png)

- Any related issues:

**Comment by cezaraugusto** [comment]
Hi @josiah-keller thanks for reporting.

This is a known issue and fix is in #6900. There is a huge refactor regarding tab itself and all its components, which addressed this and other related issues.

I'll left open this issue until PR is merged and would love to know if you found that it was fixed. If you're curious, feel free to check PR as well and let me know what do you think. Thanks!

**Comment by josiah-keller** [comment]
@cezaraugusto Ah, now that you mention it I do remember seeing that PR awhile back.  I forgot about it and didn't think to look at it when I noticed this issue earlier today.  Thanks!

**Comment by bsclifton** [comment]
Closing for now; but let's re-open if the issue shows up after the PR is merged 😄
