### ISSUE TITLE
CNET.com autoplay video player

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7006]
- Did you search for similar issues before submitting this one?
Yes 
- Describe the issue you encountered:

CNET has an annoying autoplay video player in the lower right corner of the screen that can be loud, sharp, and has been proven to wake up napping babies. 

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac/Windows (confirmed), Linux (likely)

- Brave Version (revision SHA):
v0.13.1

- Steps to reproduce:
    1. Make sure volume is low on computer.
    2. Go to https://www.cnet.com/news/mozilla-layoff-firefox-device-relevance/. 
    3. Watch autoplay vid. 
    
- Actual result:
loud video on by default.
- Expected result:
no loud video on by default.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes 

- Can this issue be consistently reproduced?
Yes 

Related issues: https://github.com/brave/browser-laptop/issues?q=is%3Aissue+cnet

**Comment by lukemulks** [comment]
This should be resolved with the upcoming autoplay feature.

**Comment by darkdh** [comment]
It's been fixed by existing autoplay feature
