### ISSUE TITLE
Bookmarking into folders dupes or doesn't work

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#7014]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmarking into folders dupes or doesn't work.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.11.6

- Brave Version (revision SHA):
0.13.2-rc1; master @cfa3186ddc7a0631044f482fe1758d72fb84ad83

- Steps to reproduce:
    0. Open Brave and enable the bookmarks toolbar.
    1. Create a folder on the toolbar.
    2. Visit a page. Bookmark it by clicking the URL bar star, specifying the folder you created.
    3. Bookmark is duplicated to be both in the folder and on the toolbar.
    4. Visit another page. Bookmark it by dragging the padlock onto the toolbar folder.
    5. Bookmark is not in the folder; instead it's on the toolbar.
    
- Actual result:
The bookmarking common case (Click the Star / Cmd+D) duplicates when bookmarking into folders.
Drag to bookmark can't bookmark into folders.

- Expected result:
Bookmarking into folders should work normally.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Fresh– yes

- Is this an issue in the currently released version?
N (current RC)

- Can this issue be consistently reproduced?
Y

- Any related issues:
maybe #6510

**Comment by darkdh** [comment]
drag and drop problem is not regression. so I separated it from here to https://github.com/brave/browser-laptop/issues/7019

**Comment by srirambv** [comment]
Steps mentioned in the original issue. Bookmark is shown correctly under the folder and not under root folder
