### ISSUE TITLE
Imported bookmarks inside nested folder doesn't show the bookmark icon when loaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7025]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Imported bookmarks inside nested folder doesn't show the bookmark icon when loaded

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	8cdf402
Verified on 0.13.1, works fine. 

- Steps to reproduce:
    1. Do a clean install of 0.13.2 RC1 build
    2. Import bookmarks from a HTML file which contains nested folders
    3. Open the bookmark which is under a nested folder, Bookmark icon remains gray instead of orange
    4. Add a new bookmark of the same page or any other page and put it under a nested folder
    5. Open the site bookmarked in step 4, click on the star button, folder name shows as root folder instead of the actual folder under which it is bookmarked(#4983)
    
- Actual result:
Bookmark icon is not shown for bookmarks under nested folder opening it shows the root folder name instead of the actual folder it is under

- Expected result:
All bookmarks should show the bookmark icon in orange when visited and the folder name should be the actual folder under which it is bookmarked

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
No. 0.13.1 shows the folder name correctly and shows the bookmark icon for all opened bookmarks

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![123](https://cloud.githubusercontent.com/assets/17010094/22590664/21860b18-ea08-11e6-805f-907866e31aa3.gif)

- Any related issues:
cc: @bsclifton

**Comment by darkdh** [comment]
fixed by https://github.com/brave/browser-laptop/pull/7024

**Comment by bbondy** [comment]
This isn't working for me with a chromium import

**Comment by bbondy** [comment]
I was testing the bookmark favicon and not the bookmarke'd star icon, my bad.

**Comment by bbondy** [comment]
There is an actual problem here but I think it is expected / not a real bug.

My chromium import had this site bookmarked:
http://www.360totalsecurity.com/en/suspicion/

So when I load it, our https everywhere upgrades it to https automatically. 

But the https version is not bookmarked, so the bookmark icon does not load up.

**Comment by darkdh** [comment]
https://github.com/brave/browser-laptop/issues/7070 is the follow up of https://github.com/brave/browser-laptop/issues/7025#issuecomment-277454068

**Comment by srirambv** [comment]
> So when I load it, our https everywhere upgrades it to https automatically.

Yes even I see this behavior. But otherwise this looks fixed.
