### ISSUE TITLE
Bookmark hanger shows a wrong folder name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7032]
## Test plan

specified below

----

**Describe the issue you encountered:** Bookmark hanger shows a wrong folder name

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 x64

- Brave Version (revision SHA): 0.13.2 ce14f5d

----

- Steps to reproduce:
    1. Add a bookmark
    1. move it to a different folder
     2. Click on the bookmark icon
        - Make sure folder is selected as `bookmark toolbar`, instead of the new folder in which you put it 
     3. Import boomarks from file/browser which has folders in it
     4. Open the bookmarked page
    5. Click on the bookmark icon
        - `Bookmark toolbar` remains location rather than the folder name

----

- Actual result: Root folder name is displayed, even if the bookmark exists under nested folder

- Expected result: Correct folder name where the bookmark exist should be displayed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No. Shows correct folder name in 0.13.1

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #4983

**Comment by NejcZdovc** [comment]
@srirambv can you please test if this is still an issue?

**Comment by luixxiul** [comment]
it is:

![bug](https://user-images.githubusercontent.com/3362943/30096784-565d84c2-9315-11e7-8e87-abb94c31edeb.gif)

Brave: 0.18.27 
rev: eba55a17853303bfe5738af7770eb52334e3fbf7 
Muon: 4.3.16 
libchromiumcontent: 60.0.3112.113 
V8: 6.0.286.56 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Linux 
OS Release: 4.9.0-3-amd64 
OS Architecture: x64
