### ISSUE TITLE
Autofill offset is off on torproject.com

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7033]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Using a previously saved brave user/password on https://trac.torproject.org/projects/tor/login shows the drop down above the box instead of below.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.2-RC2 
https://github.com/brave/browser-laptop/commit/ce14f5dbc3beda9b287d284bcd98bef3fe4230fc

- Steps to reproduce:
    1. Go to https://trac.torproject.org/projects/tor/login 
    2. type in a username and wrong password
    3. type in username again
    
- Actual result:
context menu shows at the wrong position above the input box.

- Expected result:
context menu should show underneath the input box.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
<img width="292" alt="screenshot 2017-02-03 11 08 09" src="https://cloud.githubusercontent.com/assets/831718/22598407/6198ac58-ea01-11e6-9844-b12467a2c3d7.png">

**Comment by bbondy** [comment]
To make matters worse if you have 2 saved things, it will cover up the input:

<img width="268" alt="screenshot 2017-02-03 11 11 14" src="https://cloud.githubusercontent.com/assets/831718/22598445/81fbcf2a-ea01-11e6-93aa-8f5c74b915e6.png">

**Comment by srirambv** [comment]
On Windows 
![image](https://cloud.githubusercontent.com/assets/17010094/22599554/3d5798f8-ea2f-11e6-9ac2-9fcd85324cd8.png)

**Comment by darkdh** [comment]
<img width="521" alt="screen shot 2017-02-05 at 23 19 08" src="https://cloud.githubusercontent.com/assets/11330831/22627222/9139ddde-ebf9-11e6-829a-580426b6b7d3.png">

0.13.2 RC3

**Comment by darkdh** [comment]
Updated STR:

1.  Toggle clear download history when close Brave
2. Download something to make download tool bar shows
3. Quit Brave when downloading
4. After relaunch brave go to https://github.com/brave/browser-laptop/issues
5. Search something on filter to make autofill popup
6. The popup will be shifted

**Comment by luixxiul** [comment]
Related: #3758
