### ISSUE TITLE
Bookmarks toolbar button text letters are clipped partially

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7034]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmarks toolbar button text letters are clipped partially

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	ce14f5d
System DPI at 125%

- Steps to reproduce:
    1. Add a bookmark folder/bookmark which contains char such as `g` `y` or `p`
    2. The text looks clipped 
    3.
    
- Actual result:
Text is clipped in bookmark folder/bookmarks in the bookmark toolbar

- Expected result:
Should show the text correctly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes. Looks fine only when system DPI is set at 100% (Screenshot 1)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22598517/9bc8516a-ea2b-11e6-8f07-1d468dd93268.png)
![image](https://cloud.githubusercontent.com/assets/17010094/22598744/74ad80f4-ea2c-11e6-9504-3a5bcaf914e5.png)

- Any related issues:
#2979

**Comment by Liunkae** [comment]
Previously, this was happening with 100% DPI: #4614.

**Comment by srirambv** [comment]
![image](https://cloud.githubusercontent.com/assets/17010094/22973498/cd560b0c-f375-11e6-8661-f6c84531fb5f.png)

Adding it to milestone 0.13.5.  Please remove it if required.

**Comment by bbondy** [comment]
I noticed this happening even worse on openSUSE

**Comment by bbondy** [comment]
cc @cezaraugusto if you have time to get a PR for this pls move it back into 0.13.5.
