### ISSUE TITLE
Going direct to https://wrong.host.badssl.com/ doesn't show certificate

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7042]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing https://github.com/brave/browser-laptop/issues/6524 I noticed that if you navigate directly to https://wrong.host.badssl.com/ then you can't view the certificate.
 
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS.

- Brave Version (revision SHA):
0.13.2-rc3

- Steps to reproduce:
    1. Go to https://wrong.host.badssl.com/
    
    
- Actual result:
Notice that there is no view certificate option.

- Expected result:
There should be a view certificate option.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not sure

- Can this issue be consistently reproduced?
No but it happens frequently pretty easily.  Do a new tab and load https://wrong.host.badssl.com/, then keep repeating with new tab and loading that URL until you see it.

- Screenshot if needed:
<img width="518" alt="screenshot 2017-02-03 15 39 33" src="https://cloud.githubusercontent.com/assets/831718/22608983/2d5029a4-ea2d-11e6-9dbe-839b8228d2bf.png">

- Any related issues:

**Comment by bbondy** [comment]
Note that if you first go to badssl.com and then click through, it does work in that case.

**Comment by luixxiul** [comment]
I cannot reproduce the issue on Windows 10 32 bit. Maybe this is specific to macOS.

**Comment by Liunkae** [comment]
I cannot reproduce with a fresh profile, Brave 0.13.2 RC 3 (1d936db), macOS 10.12.x.
1. Open a new tab.
2. Paste https://wrong.host.badssl.com/ in the URLbar.
3. Press <kbd>Enter</kbd>.
![](https://cloud.githubusercontent.com/assets/19424103/22616362/542ccca0-ea71-11e6-8940-bb5f361bfdfa.png)

**Comment by luixxiul** [comment]
@bbondy do you experience the issue in the same tab as you tested #6524? Or in a new tab?

I think I noticed the same thing when I was going back and forward the error page on the same tab. But maybe this can be another issue.

**Comment by bbondy** [comment]
I updated the info in the original post.  I can reproduce every time but I didn't realize that it only happens sometimes. If you keep opening a new tab and loading https://wrong.host.badssl.com/ then you should reproduce, for me in about half of the loads.

**Comment by luixxiul** [comment]
Yes I reproduced too

**Comment by darkdh** [comment]
Updated the STR:

1. bookmark https://wrong.host.badssl.com/
2. middle click on the bookmark of step1
3. see the opened new tab

**Comment by bbondy** [comment]
Since it exists since 0.12 series I'm removing from this milestone.
