### ISSUE TITLE
"Lookup" text in input on macOS is intermittently failing

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7043]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing https://github.com/brave/browser-laptop/issues/6536 I noticed that about half the time text isn't appearing when I do a lookup.  

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.2-rc3

- Steps to reproduce:
Scenario A:
    1. Go to digg.com
    2. Type dig in the search box in the page content 
    3. Select Lookup "dig" from the right click context menu
Scenario B:
    1. Go to google.com
    2. Type hello in the search box 
    3. Select Lookup "hello" from the right click context menu
    
- Actual result:
In scenario A, intermittently the lookup window will come up but with no text.
In scenario B, intermittently nothing will happen

- Expected result:
I expect the lookup window to show up in both cases

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes, I believe so.

- Is this an issue in the currently released version?
Not yet but we're in RC testing.

- Can this issue be consistently reproduced?
Not consistently, I've seen it work but most of the time it is failing for me.

- Screenshot if needed:
Scenario A:
<img width="691" alt="screenshot 2017-02-03 16 26 44" src="https://cloud.githubusercontent.com/assets/831718/22609176/26e2c6d4-ea2e-11e6-9a7d-a566eaeaf787.png">

- Any related issues:

**Comment by Liunkae** [comment]
I've tried several different sites, but I am not able to reproduce with Brave 0.13.2 RC 3 on macOS 10.12.x.

Clicking Look Up should never open the Dictionary app directly. Normally, it shows the popover as seen below.

Scenario 2:
![](https://cloud.githubusercontent.com/assets/19424103/22616858/1d5c6752-ea7c-11e6-8599-86916bfedc04.png)

**Comment by bbondy** [comment]
wow that's strange, I am getting that now as well so I'm not sure how it was opening up the app. But things were definitely intermittent.

**Comment by bbondy** [comment]
I can't seem to reproduce so I'll just re-open if I see again, same for others please if you see strangeness like this please re-open.
