### ISSUE TITLE
Include number of visits in about:history

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7045]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Include number of visits in about:history. Number of visits available as part of ledger

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.2
rev	1d936db

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/22609649/f1cc009c-ea59-11e6-92d4-3cca31875412.png)

- Any related issues:
cc: @bsclifton @bradleyrichter

**Comment by bbondy** [comment]
Just a note about this that eventually we'll be moving from a "Set" to a "List" for ledger so there will be duplicate entries for things you visit multiple times.   So I'm not sure if Visits makes sense or not, because you didn't for example visit 6 times at 9:27 on Feb 3rd.
