### ISSUE TITLE
Bookmarks when imported are out of order and folders do not expand.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7048]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When importing bookmarks from a file, the order is not maintained and the folder representations in the bookmarks menu do not expand to show contents.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows 7 ia-32 and Windows 10 x64.

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/1d936db011b3a852327c6c551a22d695ef2e631e

- Steps to reproduce: (with a clean profile)
    1. Import a bookmark file
    2. Check the bookmarks menu
    3. Order should match between file and imported representation, folders should expand
    
- Actual result:
Order does not match and folders do not expand.

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
cc @bsclifton @darkdh

**Comment by darkdh** [comment]
@alexwykoff, I suggest we separate expanding issue from this due to different cause.
Working on the order fix and can't reproduce the expanding issue, btw
