### ISSUE TITLE
Bookmarks toolbar - when adding bookmarks to folder in toolbar, the bookmarks menu representation is not updated

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7049]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When moving a bookmark on the toolbar into a bookmark folder on the toolbar, the bookmark menu is not updated to reflect the new organization.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X, confirmed on Win 10 x64

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/1d936db011b3a852327c6c551a22d695ef2e631e

- Steps to reproduce: (with a clean profile)
    1. Create a bookmark
    2. Create a folder
    3. Check the menu (they are separate)
    4. Move bookmark into folder on toolbar
    5. Check menu (they are still separate)
    
- Actual result:
Items are separately listed

- Expected result:
Bookmark should be nested in folder

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
cc: @bsclifton @darkdh

**Comment by darkdh** [comment]
This is not regression. It happens on 0.12.15 and 0.13.1.
