### ISSUE TITLE
Autofill value selected with keyboard should not be sent with enter key

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7052]
**Describe the issue you encountered:** Autofill value selected with keyboard should not be sent with enter key

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.2 RC3

- Steps to reproduce:
    1. Search ``example`` on the search input form on this page
    2. Go back to this page
    3. Input ``exa``
    4. Select ``example`` with down key
    5. Hit enter
    
- Actual result: ``example`` is searched 

- Expected result: ``example`` should just be input in the form

- Screenshot if needed:

- Any related issues: #1302

**Comment by srirambv** [comment]
Works fine on Windows x64
