### ISSUE TITLE
Selecting subfolders on the bookmark bar which have many entries can be quite laggy

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7053]
**Describe the issue you encountered:** While doing QA for #4879 I noticed that selecting subfolders on the bookmark bar which have many bookmarks can be laggy. It sometimes takes 1 second to open subfolders.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.2 RC3

- Steps to reproduce:
    1. Import a number of bookmarks
    2. Open a folder on bookmark bar which has many entries
    3. Open subfolders by moving the mouse fast
    
- Actual result: The context menu is selected quite slowly

- Expected result: the subfolders should be selected instantly

- Screenshot if needed:
![lag](https://cloud.githubusercontent.com/assets/3362943/22615604/4da03358-eadb-11e6-86a5-cfa080c7763e.gif)

- Any related issues:

**Comment by srirambv** [comment]
This happens only when a large amount of bookmarks are loaded. With just few bookmarks there is no perf issue
![shieldsmenu](https://cloud.githubusercontent.com/assets/17010094/22617304/392a81d4-eab9-11e6-89ce-2f4a3431e3fb.gif)

**Comment by luixxiul** [comment]
@ayumi Is this issue fixed with one of the PRs you recently pushed?

**Comment by sjlehn** [comment]
Possibly related - on Mac OSX (El Capitan), when selecting a group of bookmarks and moving them to another folder there is considerable lag

**Comment by luixxiul** [comment]
@NejcZdovc do you think this was fixed with the recent split PR?

**Comment by NejcZdovc** [comment]
@luixxiul I think it will be fixed with this PR #10301

**Comment by luixxiul** [comment]
I updated the 1st post on https://github.com/brave/browser-laptop/pull/10301#issue-248119212

**Comment by luixxiul** [comment]
Closing for now to check if https://github.com/brave/browser-laptop/pull/10301#issue-248119212 really fixes the issue.
