### ISSUE TITLE
Matched bookmarked URLs are not displayed on the autocomplete pulldown on URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7054]
**Describe the issue you encountered:** Matched bookmarked URLs are not displayed on pulldown on the URL bar. I think this is a regression.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.13.3 RC3

- Steps to reproduce:
    1. Clear your brave folder
    1. Open about:preferences#search
    1. Make sure that `Show bookmark matches` is enabled
    2. Open https://github.com
    3. Bookmark the page
    4. Open https://github.com/personal in another tab
    5. Bookmark the page too
    6. Open a new tab
    6. Close the other tabs
    7. Input `git`
    
- Actual result: The matched bookmarked URLs are not displayed

- Expected result: they should be displayed

- Screenshot if needed: 
![clipboard02](https://cloud.githubusercontent.com/assets/3362943/22615986/c3c5fee0-eae6-11e6-93e7-f14a157ce408.png)

- Any related issues:

**Comment by bbondy** [comment]
This is expected, history items take precedence over bookmarked items in autocomplete matching, and they are dupes of what is shown in the screenshot.
