### ISSUE TITLE
Uncaught TypeError: cannot read property 'has' of undefined(...) : onKeyDown @ menubar.js:160

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7055]
**Describe the issue you encountered:**
When I hit the down arrow of my keyboard on URL bar, I get this error on devtool console:

````
Uncaught TypeError: cannot read property 'has' of undefined(...)
    onKeyDown @ menubar.js:160
````

I cannot reproduce the error with the fresh profile.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.2 RC3

- Steps to reproduce:
    1. Open some pages to enable URL autocompleted on the URL bar
    2. Make the URL autocompleted
    3. Hit the down arrow key on your keyboard - Note: the error does not happen when I hit any other keys than the down arrow key.
    
- Actual result: the error message appears on the console

- Expected result: the error should not happen

- Screenshot if needed:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22616163/0f7745b6-eaeb-11e6-928d-4c740137a1fc.png)

- Any related issues: I suspect this is related in a way with #1302

##  Test plan

1. Open about:preferences
2. On Windows, show the menu bar by disabling "Hide the menu bar by default"
3. Open https://trac.torproject.org/projects/tor/login 
4. Autofill for the user name
5. Select your user name with the down arrow key

**Comment by NejcZdovc** [comment]
I can't reproduce this on macOS

**Comment by luixxiul** [comment]
This can be reproduced with the input field on the page. 

1. Open https://trac.torproject.org/projects/tor/login
2. Set the focus on the username input form
3. Hit the arrow down key on your keyboard

![trac](https://cloud.githubusercontent.com/assets/3362943/22616610/65d05c9c-eaf3-11e6-8d7e-1a1ccc39e14e.gif)

**Comment by luixxiul** [comment]
I added the needs investigation label just now as this cannot be repro on a fresh profile

**Comment by NejcZdovc** [comment]
Will try to investigate, the problem is that code that is triggered is the code that is used for menu bar (alternative menu for Windows)

**Comment by jonathansampson** [comment]
@luixxiul Can you set a breakpoint on that line, and see what the `selectedIndex` is?

**Comment by luixxiul** [comment]
I am not sure if this is the expected one, but here it is:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22616781/895453ea-eaf7-11e6-8825-27bb515c9541.png)

**Comment by alexwykoff** [comment]
i could not replicate on my windows 7 ia-32 (rev 1d936db) with a clean profile.

it's obviously happening per above, but might be hyper-isolated to win10 ia-32

**Comment by luixxiul** [comment]
@alexwykoff please enable the title bar. Enabling it causes the issue for me 100%

**Comment by luixxiul** [comment]
I think the root cause of the issue is the same as #6867, which was fixed with #7059

**Comment by alexwykoff** [comment]
Got it!

Go to preferences, toggle 'hide the menu bar by default' to off.
Autofill for the user name on https://trac.torproject.org/projects/tor/login will behave incorrectly and developer console shows the error as described above.

**Comment by luixxiul** [comment]
Updated the 1st post to include the extra QA steps.

**Comment by alexwykoff** [comment]
cc @bsclifton

**Comment by srirambv** [comment]
Reproduced on Win x64 with menu enabled
![image](https://cloud.githubusercontent.com/assets/17010094/22617173/1886f564-eab6-11e6-9b39-5880efc87854.png)
