### ISSUE TITLE
Remove transparency from kabob menu

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7058]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing Brave, it was noticed that the kabob menu is transparent. I found it rather distracting, so I tracked down the transparency style and removed it for contextMenuSingle.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Reproduced on Windows and OS X

- Brave Version (revision SHA):
0.13.2

- Steps to reproduce:
    1. visit a site with quite a bit of color (newtab, github, etc)
    2. open the kabob menu
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Original transparency:
<img width="341" alt="screen shot 2017-02-03 at 11 58 11 pm" src="https://cloud.githubusercontent.com/assets/1434040/22616596/80019078-ea75-11e6-8b34-3a1fdb75b572.png">

Proposed change:
<img width="239" alt="screen shot 2017-02-04 at 1 02 48 am" src="https://cloud.githubusercontent.com/assets/1434040/22616601/8e821438-ea75-11e6-88e9-cc0829d47339.png">

- Any related issues:
https://github.com/brave/browser-laptop/pull/7060

**Comment by cezaraugusto** [comment]
Wasn't it fixed by 7c2a6061622732bd6f5485b303c1d686d5b7a5c9?

**Comment by luixxiul** [comment]
Yes I think so, closing in favor of #7060
