### ISSUE TITLE
linux ppa, public key issue

### ISSUE THREAD

**Issue by dotnetCarpenter** [brave/browser-laptop#7063]
I searched the open issues but didn't find any issues with `apt`/`apt-get`.

I'm trying to upgrade **brave** but something is wrong with the linux ppa.
When I do `sudo apt update` I get:

```
Get:25 https://s3-us-west-2.amazonaws.com/brave-apt xenial InRelease [1,969 B]                                                                
Err:25 https://s3-us-west-2.amazonaws.com/brave-apt xenial InRelease                                                                          
  The following signatures couldn't be verified because the public key is not available:
  NO_PUBKEY 6ED19DBB448EEE6C

W: An error occurred during the signature verification. The repository is not updated and
 the previous index files will be used. GPG error:
 https://s3-us-west-2.amazonaws.com/brave-apt xenial InRelease: The following signatures
 couldn't be verified because the public key is not available:
 NO_PUBKEY 6ED19DBB448EEE6C
W: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/xenial/InRelease
   The following signatures couldn't be verified because the public key is not
   available: NO_PUBKEY 6ED19DBB448EEE6C
```

I have previously seen an error message like, *i386 is not supported*. But I'm not getting that error anymore.

Doing `apt list --upgradable` shows me that there is an update for **brave**:
```
brave/xenial 0.13.0-1 amd64 [upgradable from: 0.12.15-1]
```

But upgrading doesn't work, most likely due to the public key error.
```
Err:4 https://s3-us-west-2.amazonaws.com/brave-apt xenial/main amd64 brave amd64 0.13.0-1                 
  403  Forbidden
```

`sudo apt-get --fix-missing` just gives me a 403 Forbidden.

- OS: Linux  4.4.0-59-generic Ubuntu x86_64 GNU/Linux

- Brave Version: N/A

- Steps to reproduce:
    1. `sudo apt update`
    2. `sudo apt upgrade -y`
    
- Actual result: Can not upgrade **brave** due to a 403 error, most likely because of missing public key.

- Expected result: **brave** should upgrade to the most recent version.

I'm connected via a VPN, but this has never given me any issues before.

**Comment by dotnetCarpenter** [comment]
I just tried `sudo apt update` without my VPN and I get the exact same result.

**Comment by luixxiul** [comment]
Hello, did you follow the instruction available here?

https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-trusty-and-xenial-amd64

**Comment by dotnetCarpenter** [comment]
Removing the ppa and re-adding per [the instructions](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md) seems to do the trick.

While I haven't found resolution to changing keys for PPA's, I think there most be a much smoother way to do this. And you should explore this, for future releases.

**Comment by luixxiul** [comment]
> you should explore this

CC @posix4e @bbondy

**Comment by luixxiul** [comment]
Closing as the issue was fixed
