### ISSUE TITLE
cannot using brave on ios : No Connection To Any Website

### ISSUE THREAD

**Issue by 243750496** [brave/browser-laptop#7064]
- Did you search for similar issues before submitting this one?
no
- Describe the issue you encountered:
2
- Platform (Win7, 8, 10? macOS? Linux distro?):
ios newest version
- Brave Version (revision SHA):
newest
- Steps to reproduce:
    1.download the app from app store
    2.open it
    3.try to open a page
    
- Actual result:
cant access any website
- Expected result:
working smoothly
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
dont know
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.iphone 7 plus
    2.chinese app store
    3.access from china

- Screenshot if needed:
![0204_1](https://cloud.githubusercontent.com/assets/6311930/22618990/78f0ce60-eb25-11e6-95f5-5ca83790c6e0.jpg)

- Any related issues:

**Comment by luixxiul** [comment]
This is the repo of the desktop version. Would you please reopen the issue on https://github.com/brave/browser-ios/issues ? Thanks
