### ISSUE TITLE
Upgrade brave/electron to Chrome 49

### ISSUE THREAD

**Issue by obvio171** [brave/browser-laptop#707]
Chrome 48 marks as stable the [`KeyboardEvent.code`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) and [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) APIs, which allow better handling of different keyboard devices, layouts, character sets and shortcuts.

One instance of that is support for XF86Back and XF86Forward keycodes, common in Thinkpad notebooks. These and many other keys are only exposed in this new version. XF86Back and XF86Forward in particular have been supported for navigation by Chrome itself long before they were added to the Web API. I use it from muscle memory all the time and it's always a bit frustrating when on Brave it doesn't do anything. I imagine others might feel the same. I'm not super qualified but I'm willing to work on this if it's considered useful.

**Comment by bbondy** [comment]
This should be done in atom/electron fwiw and then we can pull down the change here.

**Comment by bbondy** [comment]
This was done with 0.8.1, closing.
