### ISSUE TITLE
Implement window.prompt

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7074]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave presently doesn't have UI for `window.prompt`. This presently blocks full adoption of the Reddit Enhancement Suite extension, as well as other items (#3218).

[Prompt must live!](https://twitter.com/BrendanEich/status/821977458312298500)

**Comment by luixxiul** [comment]
Is this the same as #94?

**Comment by jonathansampson** [comment]
Closing as dupe of #94

**Comment by jonathansampson** [comment]
@luixxiul It is indeed; no sure how I didn't catch that. I searched our issues twice :)

**Comment by luixxiul** [comment]
I tried as well but I cannot find it either. I just remembered ;-)
