### ISSUE TITLE
Extension API: chrome.pageAction

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7075]
https://developer.chrome.com/extensions/pageAction#method-hide
https://developer.chrome.com/extensions/pageAction#method-show
https://developer.chrome.com/extensions/pageAction#method-setIcon

**Comment by niutech** [comment]
I second this feature request. Is there an alternative for showing page action icon in the meantime?

**Comment by jonathansampson** [comment]
@niutech I believe these are supported to a large degree already. One limitation I know of is that we don't support data URL values for icons.

**Comment by niutech** [comment]
Is it? I had to change `pageAction` to `browserAction` in order to see the icon of my extension on the toolbar.

**Comment by jonathansampson** [comment]
@niutech Ah, my apologies. _Page Actions_ are displayed within the omnibar, correct?
