### ISSUE TITLE
Need new strings to handle overdue payments

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#7078]
* “Your first contribution will be 24 days ago.”
* “Your next contribution will be 18 days ago.”

So these need to be modified to handle the correct tense when payment is overdue. I’m uncertain about any localization implications this may have or how this should be best handled. Pull request #7077 handles a related string, but not this issue.

**Comment by bsclifton** [comment]
Note to testers:

UI will change with https://github.com/brave/browser-laptop/pull/7532. See notes from discussion in the PR that fixes this issue: https://github.com/brave/browser-laptop/pull/7524#issuecomment-285634427
