### ISSUE TITLE
The arrow keys do not work when the menu bar is enabled by default

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7081]
**Describe the issue you encountered:** The arrow keys do not work in input field (both inside and outside webview) if the menu bar is enabled by default.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.2 RC4

- Steps to reproduce:
    1. Open about:preferences
    2. Disable "Hide menu bar by default"
    3. Set focus on the URL bar
    4. Input some characters
    5. Hit the arrow keys on your keyboard to move the cursor
    6. Make sure they do not work
    7. Open https://github.com
    8. Set focus on the search input field on that page
    9. Input characters
    10. Hit arrow keys
    11. Make sure they do not work
    12. Open about:preferences
    13. Enable "Hide menu bar by default"
    14. Make sure the arrow keys work in both case
    
- Can this issue be consistently reproduced? Yes

- Screenshot if needed:

- Any related issues: #7055

**Comment by srirambv** [comment]
No issue on Windows x64
![7081](https://cloud.githubusercontent.com/assets/17010094/22625083/2eaf4a5c-eb84-11e6-8dcc-2b7339cc3b32.gif)

**Comment by luixxiul** [comment]
please just use arrow keys, never delete key
