### ISSUE TITLE
Show additional info about download in download bar

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7082]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
We don't show how much time is left and the file size in the download bar.
    
- Actual result (Brave):
![image](https://cloud.githubusercontent.com/assets/9574457/22625091/ca69903a-eb8c-11e6-9dd5-a8baac56a8e7.png)

- Expected result (Chrome):
![image](https://cloud.githubusercontent.com/assets/9574457/22625090/c1173bd6-eb8c-11e6-96c4-0c81d2a2b377.png)

**Comment by luixxiul** [comment]
@bradleyrichter do you have a mockup of this?

**Comment by bbondy** [comment]
I think the original mockup had the estimated time left as well.  I think probably everything we show in the second line currently is redundant.  The percentage is visual from the blue progress bar background, and Downloading text is obvious too.  So I'd prefer we just show the same info as chromium on the second line.

**Comment by bradleyrichter** [comment]
The original mockup did not have a second line. 

I have not heard large user demand for more info but if the data that chrome displays is easy to get and display, that sounds like a good replacement for "Downloading: 10%" which redundant.

**Comment by NejcZdovc** [comment]
My use case was like this:

I was creating a windows testing environment for Brave. I went to the windows 10 page and started with a download. They don't specify the size of the iso file that you will be downloading. And when I started with a download the only thing that I saw was 1% :smiley: I wanted to know at least how much time it will take to download this file.

**Comment by Liunkae** [comment]
+1 from me. The stats are shown in all major browsers. Firefox and Safari examples:
![image](https://cloud.githubusercontent.com/assets/19424103/23931304/85a741e6-08ff-11e7-9744-6aa62c7520b9.png)
![image](https://cloud.githubusercontent.com/assets/19424103/23931338/a00881ee-08ff-11e7-9be4-5bce1be671af.png)

**Comment by srirambv** [comment]
>. And when I started with a download the only thing that I saw was 1%  I wanted to know at least how much time it will take to download this file.

This is problem on Windows(at least I hope so) when the size of the file is not mentioned, It just shows as downloading on Chrome as well and the taskbar indicator just keeps flashing until the entire file is downloaded.

**Comment by rtloeffler** [comment]
I also would like to see how many more MB or GB i have left. I do like the blue status bar and the percentage but i think "Downloading" is not needed.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/idea-progress-information-when-download/6234?u=eljuno
>  like Chrome, you can know in download information page, your download speed / remaining time / weight / progress weight download.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/download-size-in-the-download-bar/8373?u=eljuno

**Comment by czebiniak** [comment]
+1 I want to see my download speed at the very least. I would also like to see how much data still remains.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/no-download-speed-in-the-downloads-viewer-or-estimated-time/8786?u=eljuno

>I would like to see a download speed and estimated time of download

**Comment by odbaruch** [comment]
+1 I would like to see my download speed and the size of the download.

My Internet speed is inconsistent so this information is useful in determining whether my ISP or the server from which I'm downloading is causing the problem.

**Comment by philip-ulrich** [comment]
I think this is same or similar as #3924, but +1 here too....

**Comment by vanclute** [comment]
+1 for sure, especially when you have a bunch of large downloads going, it's really helpful to see stats on them.

**Comment by StephenBass** [comment]
+1 Reddit request for download speed and file size
https://www.reddit.com/r/BATProject/comments/7yda9c/is_there_a_way_in_brave_how_to_track_downloading/

**Comment by eljuno** [comment]
+1 from community for download speed https://community.brave.com/t/speed-download-in-brave/14464?u=eljuno

**Comment by bsclifton** [comment]
+1 from @CardealRusso via https://github.com/brave/browser-laptop/issues/7082
> When the download have no file size in header, Brave just say "Downloading". Could be better to show the size downloaded, something like "123 MB..."

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/Smithcraft1/status/977521640312512514

> showing the percentage and the speed of the download

**Comment by eljuno** [comment]
++ from community https://community.brave.com/t/please-add-estimated-remaining-time-for-downloads/21138?u=eljuno and https://community.brave.com/t/no-download-details-speed-and-size-of-files/21142?u=eljuno

**Comment by xaliber** [comment]
+1 more from me, found this link from this: https://community.brave.com/t/download-size-in-the-download-bar/8373/2

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/downloads-progress-bar-or-feedback/23755?u=eljuno

Also @bsclifton, should we have this for free with brave-core? :smile:

**Comment by Liunkae** [comment]
@eljuno Yes! This is what I get with `brave-browser`:
![](https://user-images.githubusercontent.com/19424103/41329474-953fc2a4-6e93-11e8-9d04-55ebd574332d.png)

**Comment by bsclifton** [comment]
Closing as `wontfix` as we'll get this with Brave Core (as shown in screen cap above 😄 )
