### ISSUE TITLE
Never included list support

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7085]
Users might need this list to revert the action like accidentally click `remove` button or regretting add a site to that list.

I have to go to `session-store-1` to set `ledgerPaymentsShown` to true to make a certain site shows on publishers list again.

cc @mrose17, @bradleyrichter , @cezaraugusto

**Comment by mrose17** [comment]
hmmm... i go to the Shields panel and look at "Saved Sites Exceptions" and they are all listed there. you can then click on the orange `x` to the left and it is removed.

am i missing something?

**Comment by darkdh** [comment]
ahh, sorry my bad. I didn't realize it will be there. Thank you

**Comment by darkdh** [comment]
or maybe we should put a button which link to this on payment page for users who might be hard to find it

**Comment by cezaraugusto** [comment]
I agree with @darkdh, UX could be better and there's should be something to guide users.

/cc @bradleyrichter for thoughts.

**Comment by bradleyrichter** [comment]
Site exceptions wasn't actually the planned place for this but it was a quick safety net.

One quick fix could be to add the ability to UNDO the accidental deletion. 

A more time consuming fix is to create a ledger-specific deletion list that the user can manage. It would be accessed through a rt-click menu and possibly through advanced settings.
