### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined(…) contextMenus.js:946 in about:extension page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7092]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing #6580 , right click on the extensions entry in `about:extension` shows 

   ```Uncaught TypeError: Cannot read property 'length' of undefined(…) contextMenus.js:946 ```

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	726b9d2

- Steps to reproduce:
    1. Do  a clean install of 0.13.2 RC6 
    2. Open `about:extension` page and open browser console
    3. Right click on the extensions entry, console shows error
    
- Actual result:
Right click on the extensions entry, console shows error

- Expected result:
Should not show error

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes. Verified in 0.13.1

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![consoleerror](https://cloud.githubusercontent.com/assets/17010094/22647588/52b6c97a-ec6a-11e6-918a-77a589ad9076.gif)

- Any related issues:
#7055

**Comment by NejcZdovc** [comment]
@srirambv I have a solution for it, but I am not sure what should be a result of contextMenu. What items should be show?

Right now is something like this, which I don't see any real value.
![image](https://cloud.githubusercontent.com/assets/9574457/22657821/2709a2a6-ec98-11e6-9a1e-f3ba16280440.png)

**Comment by srirambv** [comment]
I don't think it needs to show context menu. We are not allowing users to open the installed folder location or do anything else. I think disabling right click on that page should be fine. @bbondy thoughts?
