### ISSUE TITLE
Moving pinned tab will also move bookmarks order

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7094]
STR:
1. Open site A, B, C
2. Bookmark site A, B, C
3. Pinned site A, B, C
4. Move pinned tab A to the place between B & C
5. **Bookmark A move along with pinned tab A**

**Comment by luixxiul** [comment]
Is this bug still out there?

**Comment by darkdh** [comment]
No I think new pinned tab fixed it
