### ISSUE TITLE
More bookmarks menu item no longer appears

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7097]
For some of the custom drawn menus we support dataL10nId but due to sanitization they are removed. Since we aren't calling the menu sanitization recursively it isn't seen very often, but it does make a valid menu item disappear in the bookmark menu at least, the last one that says more menu items.

**Comment by luixxiul** [comment]
Do we need QA?

**Comment by luixxiul** [comment]
Test plan: make sure "more bookmarks" menu item appears
