### ISSUE TITLE
Horizontal scrolling with two-finger gesture is also treated as page navigation

### ISSUE THREAD

**Issue by grantwinney** [brave/browser-laptop#7100]
**Issue:**
When a particular webpage I'm using is wider than the screen and requires horizontal scrolling (such as a Trello "board"), Brave treats a two finger swipe as a horizontal scroll _AND_ as a page navigation gesture.

**Actual result:**
When I two-finger swipe a wide page, it horizontally scrolls the page a bit, but then navigates back to the previous page.

**Expected result:**
I'd expect it to eat the page navigation feature unless I'm:
- already scrolled to the left-most side of a wide page, then treat it as a page "back" navigation
- already scrolled to the right-most side of a wide page, then treat it as a page "forward" navigation

**Environment:**
Mac OSX 10.11.6
Brave 0.13.1, SHA 9dd06f9

**Any related issues:**
None that I found, although someone [commented similarly](https://github.com/brave/browser-laptop/issues/5907#issuecomment-263984289) in another issue.

**Comment by Liunkae** [comment]
I've also had this happen sometimes.

This is a regression of #2548 (Horizontal scroll with two-finger conflicts with swipe back/forward).

**Comment by bgergen** [comment]
Glad to see this is a known issue. Makes it super frustrating to try to scroll horizontally to read code snippets or PRs on Github.

**Comment by grantwinney** [comment]
@bgergen Agreed. I keep forgetting and accidentally navigating away from my page.

I really _want_ to like Brave and its security-first approach, but there's a lot of little things. This issue, sites where the WYSIWYG editor simply doesn't work (like Confluence), sites that stop loading after awhile as if they're unavailable but they continue to load fine in Firefox or Chrome...

Just a lot of bugs to work out I guess. 🙁

**Comment by Liunkae** [comment]
We've gotten a few +1's for this problem at #5907.

Can we set a milestone for this? I agree with the others that it's really annoying.

**Comment by grantwinney** [comment]
5 weeks and I still can't swipe left without navigating off the page...

**Comment by ttfkam** [comment]
I would amend the behavior to disallow navigation altogether or at least only on clear gestures. When a page loads, it's not always clear that the page can scroll horizontally. Testing this only to navigate away from the page is non-optimal. In addition, it is common to try to scroll at least once after you've reached the beginning or ending of a view, especially on a large page. The intent is to reach the beginning or end, not leave the page.

Much better to switch this to a three-finger horizontal gesture, at least on Mac. The gesture is not already overloaded/not assigned to anything. It would make the navigation intent clear while leaving scrolling fully functional.

**Comment by Liunkae** [comment]
@ttfkam Right now, the main problem with the swipe gesture (besides the horizontal scrolling mess) is that it does not respect the system preferences (issue #5907). Ultimately, I think that imitating Safari's behavior should solve most of the problems you described.

**Comment by Liunkae** [comment]
Tagging as a serious macOS usability issue. Please re-prioritize if needed.
