### ISSUE TITLE
Asana drag and drop not working

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7103]
STR:
1. Login to asana
2. Create a tasks
3. Try to order them by drag and drop

Actual results:
They stay in place.

Expected results:
They move to where you dropped them.

They don't re-re-order.

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
@bradleyrichter says this works, yo
