### ISSUE TITLE
Where is cache located on a GNU/Linux system?

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#7104]
I cannot find the cache either in `~/.local` nor in `~/.cache` on my Xubuntu Yaketty :( Where is it?

I need it because I have /tmp mounted to RAM and I put all my caches there via creating symlinks... to increase both performance and my SSD disk lifetime.

(Brave installed from the repository via `apt`)

Debug info:
Name	Version
Brave	0.13.1
rev	9dd06f9
Muon	2.0.18
libchromiumcontent	54.0.2840.100
V8	5.4.500.41
Node.js	7.0.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-37-generic
os.arch	x64

Thanks.

**Comment by luixxiul** [comment]
I think you could find them inside `./config/brave`. Please let me know if you could not.

Thanks

**Comment by crysman** [comment]
Yes, I've found it there, thank you.
Is this going to be persistent or are you planning to move it to other location (like e.g. `~/.cache`)?

**Comment by luixxiul** [comment]
CC @bbondy for a comment.

**Comment by bbondy** [comment]
for now there are no plans to change it.

**Comment by luixxiul** [comment]
Closed the question was answered
