### ISSUE TITLE
sanitizeTemplateItems should remove first item if it is a separator

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7109]
Also please add a test for it.

For example, on linux:
<img width="338" alt="screenshot 2017-02-06 15 50 16" src="https://cloud.githubusercontent.com/assets/831718/22665773/fd7a3b4e-ec83-11e6-8837-75ed7c6403f6.png">

/cc @bsclifton

**Comment by siemiatj** [comment]
Lookng at the source : https://github.com/brave/browser-laptop/blob/35944f6f1793e6e610e17dacb2518a7e35580796/app/common/lib/menuUtil.js#L178 and tests : https://github.com/brave/browser-laptop/blob/35944f6f1793e6e610e17dacb2518a7e35580796/test/unit/app/common/lib/menuUtilTest.js#L276 this should already be handled. 

Maybe it's a linux thing ? The order of the items seems different if it's the latest build.

![screen shot 2017-02-09 at 12 32 55 pm](https://cloud.githubusercontent.com/assets/513460/22781683/e0313780-eec3-11e6-9026-471999f7e92c.png)

**Comment by bbondy** [comment]
Yes I think it only happens on Linux, each platform has a slightly different menu sometimes.

**Comment by bbondy** [comment]
it does seem handled from code, interesting.  I guess I'd have to dig in deeper on Ubuntu to see why it happened.

**Comment by Liunkae** [comment]
I can reproduce with Brave 0.12.13 RC 2 on macOS 10.12.x
![image](https://cloud.githubusercontent.com/assets/19424103/22866159/1402047a-f137-11e6-9e42-4e0db6d9ece3.png)
There is an extra separator here:
https://github.com/brave/browser-laptop/blob/master/app/browser/menu.js#L430

**Comment by siemiatj** [comment]
I'm wondering if it's not caused by the `Search` bar that is added for the `Help` tab. I can't really reproduce this in tests or in any other tab. Creating a PR that removes it.
