### ISSUE TITLE
.mov URLs try to download instead of playing in the browser

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#7110]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

If I make a video recording with CloudApp, it gives me a URL like so, which works fine:

https://cl.ly/3X3N361x2h1V

However, if I get the "original file" URL, like this, I'm prompted to download the file:

https://cl.ly/3X3N361x2h1V/Screen%20Recording%202017-02-06%20at%2002.53%20PM.mov

This seems to happen in Chrome, as well. Safari and Firefox both play the video in the browser just fine.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.13.2 (e9db015)

- Steps to reproduce:
    1. Go to the URL given above (the long .mov one)
    
- Actual result:

Brave tries to download the file.

- Expected result:

The video should play in the browser.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Any related issues:

This seems to be an issue in Chrome as well.

**Comment by luixxiul** [comment]
If I understand correctly `.mov` can be played with Quicktime plugin and it will not be supported.

**Comment by echosa** [comment]
That's really unfortunate. This works in other browsers, and it's a pain to have to download and play the file, rather than just have it play in the browser tab. This will be a big detriment to Brave.

**Comment by bsclifton** [comment]
cc: @bradleyrichter @bbondy @BrendanEich for comment (of course, everyone else welcome too! 😄 )

**Comment by kjozwiak** [comment]
If we're not planning on fixing this, we should close off the issue. @bradleyrichter, @bbondy are we planning on adding quicktime support? I haven't heard/seen any plans but I might be wrong.
