### ISSUE TITLE
Sites added on add funds toggle lack instant ledger response and favicon

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7111]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
* Clicking the add funds toggle on urlbar don't instantly update ledger panel. Update only happen if you refresh page;
* After refresh, site appear, but lack favicon

- Platform (Win7, 8, 10? macOS? Linux distro?):
any

- Brave Version (revision SHA):
35d52c7

- Steps to reproduce:
    1. Open a qualified publisher (i.e. https://clifton.io)
    2. Hit addFunds button
    3. Go to ledger panel
    
- Actual result:
1. Publisher is not there unless you refresh page
2. when you update, site is there without favicon

- Expected result:
1. You shouldn't need to refresh page. Publisher should be there immediately.
2. Publisher should have favicon

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
n/a

- Screenshot if needed:
n/a

- Any related issues:
This issue is a filtered version of #6592

**Comment by cezaraugusto** [comment]
cc @mrose17

**Comment by bsclifton** [comment]
Moving to 0.14.1

**Comment by luixxiul** [comment]
duping to #4178?

**Comment by bsclifton** [comment]
Closing as dupe per issue shared by @luixxiul
