### ISSUE TITLE
Specify QA steps for 0.13.3

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7112]
**Describe the issue you encountered:**

Specify QA steps for 0.13.3 of the issues which were solved. This is the list of the issues whose QA steps are required;

https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AQA%2Fsteps-required%20milestone%3A0.13.3%20

- Any related issues: #6688 #6899

**Comment by Liunkae** [comment]
All issues have QA steps if needed.
