### ISSUE TITLE
WhatsApp web does not work

### ISSUE THREAD

**Issue by fieder** [brave/browser-laptop#7115]
- Did you search for similar issues before submitting this one?
Yes. Issue does not exist so far or has not been reported
- Describe the issue you encountered:
whatsApp web does not work. Each time you load the page, a QR code appears on the screen and by reading it from your whatsApp app on your phone so can use whatsApp on a desktop browser provided your phone is on the same Wifi. Quite useful to have it on your computer while working so you don't have to switch to your mobile to check whatsApp messages.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
0.13.2 25b1199
- Steps to reproduce:
    1. Go to https://web.whatsapp.com/
    2. At this point you should see a QR code on the screen, which is the  bit that does not work.
    
- Actual result:
Screen with broken image link
- Expected result:
QR code image on the screen
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by srirambv** [comment]
Is Fingerprinting enabled on the page? It works fine when fingerprint is disabled.

**Comment by fieder** [comment]
You are correct. When fingerprint is disabled it works. When enabled it does not work. Is that the expected behavior or should it work in both cases?

**Comment by srirambv** [comment]
That's an expected behavior.
