### ISSUE TITLE
enable Do Not Track (DNT) by default?

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7119]
according to https://www.w3.org/TR/tracking-dnt/:

> The goal of this protocol is to allow a user to express their personal preference regarding tracking to each server and web application that they communicate with via HTTP, thereby allowing recipients of that preference to adjust tracking behavior accordingly or to reach a separate agreement with the user that satisfies all parties.

> Key to that notion of expression is that the signal sent must reflect the user's preference, not the choice of some vendor, institution, site, or network-imposed mechanism outside the user's control; this applies equally to both the general preference and exceptions. The basic principle is that a tracking preference expression is only transmitted when it reflects a deliberate choice by the user. In the absence of user choice, there is no tracking preference expressed.

@pde believes that it would be standards-compliant for Brave to enable DNT=1 by default, since we are a privacy tool that does our best effort to block tracking; therefore a user who installs Brave is expressing a preference to not be tracked.

**Comment by diracdeltas** [comment]
see also comment from @pde here: https://github.com/disconnectme/disconnect-tracking-protection/issues/10#issuecomment-278116771

**Comment by luixxiul** [comment]
@diracdeltas Is this wontfix? (https://community.brave.com/t/why-is-the-do-not-track-header-checkbox-off-by-default/9987 was moved from our wiki)

**Comment by diracdeltas** [comment]
still worth considering

**Comment by NumDeP** [comment]
+1 I don't think there should even be a toggle option. Just make the feature default, remove the toggle button and re-title it in preference to "'Do Not Track' header sent with every browsing requests".

**Comment by flamsmark** [comment]
We should make DNT like a shields preference: configurable per-site and on by default.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/826
