### ISSUE TITLE
Translate Bookmarks Manager

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7130]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Title and Last visited in Bookmarks Manager are not translated.
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
f7a5e17
- Steps to reproduce:
    1. Go to Bookmarks Manager
    2. Check out Title and Last visited
    3. Go to Preferences -> General
    4. Change language
    5. Go back to Bookmarks Manager
    6. Title and Last visited are still in english
    
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by NejcZdovc** [comment]
Good place to start looking https://github.com/brave/browser-laptop/blob/master/js/about/bookmarks.js#L337

**Comment by Liunkae** [comment]
PR: #7139

**Comment by Liunkae** [comment]
@luixxiul This is a very minor change. I don't think we need QA for this (we can't even realistically verify until the texts are translated and imported), and I don't think it needs to be included in the release notes.

**Comment by luixxiul** [comment]
I could verify change by myself by doing l10n on Transifex so no worry

**Comment by luixxiul** [comment]
Also the issue can be named "more l10n done" etc on release notes if it is worth mentioning. At least this must not be excluded from the release note so Iabelled to include it

**Comment by Liunkae** [comment]
Fair enough.
