### ISSUE TITLE
Pressing tab on autocomplete suggestion doesn't fill the input field

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7132]
## Test Plan
- Ensure you have auto complete suggestion for on an input filed
- Press down on the input field to highlight the suggestion
- Once highlighted press tab, field should be filled

## original issue details
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pressing tab on autocomplete suggestion doesn't fill the input field

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.2
rev	25b1199

- Steps to reproduce:
    1. Ensure you have auto complete suggestion for on an input filed
    2. Press down on the input field to highlight the suggestion
    3. Once highlighted press tab, field is still blank doesn't autocomplete 
    
- Actual result:
Autocomplete suggestion doesn't fill in when tab is pressed

- Expected result:
Should put the auto complete suggestion in the input field when tab is pressed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tabselect](https://cloud.githubusercontent.com/assets/17010094/22739844/5c3d42b6-ee05-11e6-832a-e6ab9e909323.gif)

- Any related issues:
#1302

**Comment by NejcZdovc** [comment]
This is not a bug it's by design. You can see it [here](https://github.com/brave/browser-laptop/blob/master/js/components/contextMenu.js#L278-L293), `enter` selects the item and `esc` and `tab` closes it.

**Comment by bsclifton** [comment]
Good question-  @srirambv, @NejcZdovc what is the behavior in other browsers?  I believe tab works... so I think it would make sense to also implement that too 😄

**Comment by srirambv** [comment]
@bsclifton Other browsers all auto complete suggestion gets selected on tab. This is standard behavior for auto complete. 

Chrome behavior
![7132](https://cloud.githubusercontent.com/assets/17010094/22748835/50fa29be-ee23-11e6-854a-6da9a84cd1c6.gif)

**Comment by NejcZdovc** [comment]
Ok will fix it
