### ISSUE TITLE
set-active tracking issue to hopefully fix tab switching

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7138]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab swtiching sometimes goes a little bonkers

- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):

- Steps to reproduce:
    1. Open a lotta tabs
    2. Try switching via clicking on tabs & tabsets in UI
    3. Try switching via keyboard combos
    
- Actual result:

- Expected result:
Switching should be fast and pages should render without issue.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/pull/7137

**Comment by bbondy** [comment]
I think this can be closed now

**Comment by luixxiul** [comment]
Duping to #6895 ?
