### ISSUE TITLE
Snap Package for Brave

### ISSUE THREAD

**Issue by ryanleesipes** [brave/browser-laptop#7140]
- Did you search for similar issues before submitting this one?
**Yes**

- Describe the issue you encountered:
**Installing on Ubuntu, derivatives, and Linux in general could be much easier.**

- Platform (Win7, 8, 10? macOS? Linux distro?):
**Ubuntu and Elementary (Linux)**

### What are Snaps?
Snap packaging was developed in order to make installation of software easier on Linux, and to make targeting the platform as a whole simpler for developers. Ubuntu is currently accepting Snap packages into its app store through their [developer portal](https://myapps.developer.ubuntu.com/dev/click-apps/). This would serve as an easier way for getting Brave on Ubuntu, and if snapd is installed on other distributions the installation is very straightforward as well.  *Snaps* is a nickname for a snap package.

### How much work is it?
Electron Builder now supports the generation of a snap package. This should make it much simpler to implement into the current process fairly easily. The options are detailed on the [Electron Builder wiki](https://github.com/electron-userland/electron-builder/wiki/Options#SnapOptions).

The Ubuntu community has been amazing about helping projects get their software packaged as snaps. If this is a target the Brave community is interested in hitting, then we can tap the Ubuntu folks for help and I'm sure they will gladly lend their aide.

**Comment by develar** [comment]
electron-builder 16.1 [supports](https://github.com/electron-userland/electron-builder/issues/1394#issuecomment-288342946) muon, so, this issue is easy to fix :)

**Comment by geekgonecrazy** [comment]
This would be amazing.  Would reduce installation on ubuntu to a command like this: `sudo snap install brave` and its installed and ready to go :+1:
