### ISSUE TITLE
Browser chrome displayed while in full screen mode

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7149]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Full screen mode does not hide the address bar, bookmarks, and other Brave UI components. Originally reported to us by [a user on Twitter](https://twitter.com/jrmatheny/status/829730480702488578).

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/25b1199fb6154b089cbad37926483239495b9800

- Steps to reproduce:
    1. Navigate to https://github.com
    2. Press F11
    3. Note that browser UI components are still visible

**Comment by luixxiul** [comment]
I think this is by design and not a bug. 

We could create an option to hide it anyway.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/a-few-requests-for-extensions-that-will-make-this-my-main-browser/5638?u=eljuno

>Also, this may already be a feature but is there a way to get full fullscreen without any toolbars until you hover over the area?

And +1 from me. Since F11 in chrome is hide the toolbar, tabs, etc.

**Comment by luixxiul** [comment]
let me close the ticket in favor of https://github.com/brave/browser-laptop/issues/11463 where the discussion is active.
