### ISSUE TITLE
Add a search bar in preferences

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7150]
To make it MUCH easier to find preference items in the prefs panels, we need to add a search box which uses a similar mechanism to the browser page search, but searches across all prefs panels.

Additionally, keywords should be added to each preference item to enable better results beyond the text contained within the string of the item.

![image](https://cloud.githubusercontent.com/assets/13509546/22805195/5198b6ac-eed1-11e6-9303-96e47fcd9976.png)

The number of results should reflect the number of matches. The arrow buttons should jump to the next or previous result.

As a result is shown, the text in the item string or the entire string (in the case of an item-keyword match) should be highlighted with blue rectangle.

The results should loop in case the user passes the last match, and be returned to the first match.

#3532

**Comment by bsclifton** [comment]
+1 from @DeviatedMind via https://github.com/brave/browser-laptop/issues/11003

**Comment by bsclifton** [comment]
Fixed with [brave-core](https://github.com/brave/brave-browser) 😄 
![screen shot 2018-08-24 at 1 39 22 am](https://user-images.githubusercontent.com/4733304/44574556-92f2d980-a73e-11e8-883a-6e7865504fa4.png)
