### ISSUE TITLE
Ads on krebsonsecurity.com (site-level) 

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7151]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Krebs on Security is showing ads w/shields up. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
Full profile: 
Brave: 0.13.2 
rev: 25b1199fb6154b089cbad37926483239495b9800 
Muon: 2.0.19 
libchromiumcontent: 54.0.2840.100 
V8: 5.4.500.41 
Node.js: 7.0.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64

- Steps to reproduce:
    1. Go to: https://krebsonsecurity.com/2017/02/fast-food-chain-arbys-acknowledges-breach/
    2. See ads
    3. 
    
- Actual result:
ads

- Expected result:
no ads

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-krebsonsecurity-ads-02092017](https://cloud.githubusercontent.com/assets/8979240/22809276/fa54ea0e-eee5-11e6-8717-7a45bc13a91c.PNG)

Note: They appear to be using CSS and page-level Native JS/HTML for ads. 
Need to investigate further. 
Could be 1st party and no-issue, but filing issue since we're observing ads w/Block Ads shield enabled. 

File path for the Ads CSS:  https://krebsonsecurity.com/wp-content/themes/krebsads/krebsads/ads.css?201107

**Comment by BrendanEich** [comment]
If just his own ads, probably ok. Any tracking?

**Comment by lukemulks** [comment]
No tracking. Appears pretty harmless after checking a few pages/refreshes. Going to close this out. 

Thanks for the clarification on this @BrendanEich - definitely helps for future instances.
