### ISSUE TITLE
Bookmarks : Open all in tabs is not opening tabs in the order of folder listing

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7156]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A user in community has reported that their bookmarks are not opening in order when 'open all in tabs' is selected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 for the user, reproduced on OS X

- Brave Version (revision SHA):
b8d7358 for OS X

- Steps to reproduce:
    1. Have an install with bookmarks
    2. From the bookmarks toolbar, navigate to a bookmarks folder and with the context menu select 'open all in tabs'
    3. Observe the order of the tabs (left to right) versus the order in the folder (top to bottom)
    
- Actual result:
For my test of two bookmarks in a folder, they opened in reverse order.

- Expected result:
The topmost bookmark should be the leftmost tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/0-13-2-open-all-in-tabs-problemette/1095

**Comment by pmjones** [comment]
I have the same problem. Thanks for reporting it.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/unusual-behavior-after-opening-all-in-tabs/2417)
