### ISSUE TITLE
More dashboard configuration options (images / top sites)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7159]
This is a follow up for https://github.com/brave/browser-laptop/issues/6965

Instead of a on/off for images, we should offer:
- landscape images
- (possibly other image categories)
- color blend (gradients)
- solid color (grey)

![image](https://cloud.githubusercontent.com/assets/4733304/22819972/fba91ae6-ef31-11e6-9626-f3ea5e405539.png)

cc: @bradleyrichter 

Note: top site toggle switch was disabled with https://github.com/brave/browser-laptop/issues/5482 / https://github.com/brave/browser-laptop/commit/967362846d1a06bf8fa042fd8e0b3b85650ab57d

**Comment by bsclifton** [comment]
Also related: https://github.com/brave/browser-laptop/issues/6042

We should offer a way to turn off top sites (which also removes any session data which was stored)

**Comment by luixxiul** [comment]
+1 for Google Earth: https://community.brave.com/t/feature-request-earth-view-from-google-earth-as-alternative-to-brave-dashboard-as-a-new-empty-tab/1255?u=suguru

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/win64-laptop-v0-19-95-general-feedback-minor-issues/11283?u=eljuno

> where users could configure the time/day/date, background photo options, and number of icons showing

**Comment by buzzert** [comment]
+1

No movement on this since 2017, is this still planned at all?

**Comment by bsclifton** [comment]
@buzzert unless we get a pull request, we aren't planning to solve this with our current Muon based browser. I've created a corresponding issue for the new Brave Core UI that we're working on which you can subscribe to here: https://github.com/brave/brave-browser/issues/353

Given that, I'll close this issue as `wontfix`
