### ISSUE TITLE
Browser attachment shut down

### ISSUE THREAD

**Issue by Yurimir43** [brave/browser-laptop#716]
Hello,
Experience a problem here is how to see it
goto say indeed.com 
find a job that says easy apply click on it
asks for name go down asks to add a resume click on browse 
soon as you go to browse computer for your resume it shuts down the brave browser no idea why

tried 10 times same results

**Comment by bridiver** [comment]
any file input element causes the browser to quit, but other methods of triggering the dialog (Facebook for instance) work fine
