### ISSUE TITLE
Refactor textarea with Aphrodite into TextArea

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7163]
## Test Plan
1. Open about:adblock
2. Input some strings inside the textarea
3. Make sure the font size is set to 14.5px
4. Make sure 10px margins exist on the top and the bottom of the textarea
5. Open about:styles
6. Make sure `<TextForm>` and `<DefaultTextForm>` are correctly displayed

## Original issue details
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/6851#issuecomment-275051821

> The font-size should be `14.5px` based on https://github.com/brave/browser-laptop/pull/6689/files#diff-fa59d1e0221a5bee94fd2abd9b96dcfdR17
> 
> Also the `textarea` should be updated to an Aphrodite component. And I'm creating it.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: https://github.com/brave/browser-laptop/pull/7152/files#diff-4d41992378b9b0e8b0546117c1668299R131 of #7152

**Comment by luixxiul** [comment]
I will also create `<SyncTextArea>` based on https://github.com/brave/browser-laptop/pull/7152/files#diff-4b50ff14dadc9756719a577a72f520d6R1562 / CC: @ayumi

**Comment by luixxiul** [comment]
I added `<SyncTextArea>` with 864f5611d6f834ad78bf112b38881d844158e291. It is based on 4a8bd86 for #7165.

<img width="731" alt="screenshot 2017-02-10 23 59 56" src="https://cloud.githubusercontent.com/assets/3362943/22831266/11cd6f8c-efed-11e6-8549-42737f07d976.png">

I will create an PR for it after #7165 is merged.

**Comment by bsclifton** [comment]
Looks nice! Great work, @luixxiul 😄

**Comment by cezaraugusto** [comment]
![aphrodite_all_the_things](https://cloud.githubusercontent.com/assets/4672033/22836598/3c1494b2-efa4-11e6-9644-ecfc954e7aab.jpg)
