### ISSUE TITLE
Lookup in dictionary by context menu doesn't work

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7167]
reference to https://github.com/brave/muon/issues/156
temporarily fixed by https://github.com/brave/muon/commit/62dec3b9561bc5d35976549317c40b1b6fc46b4e

**Comment by Liunkae** [comment]
QA steps (macOS-only):

1. Navigate to any webpage with text (e.g. github.com).
2. Right-click any word on the page.
3. Click `Look Up`.
4. Make sure:
  - the word is highlighted in yellow
  - a popup appears with the definition(s) of the word
  - the popup arrow is pointing at the word. Screenshot:
![image](https://cloud.githubusercontent.com/assets/19424103/22851885/5c6d4f3c-eff5-11e6-9bda-e1b8f8b5fa43.png)
