### ISSUE TITLE
0.13.3 UI Issues Aggregation/Tracking Ticket

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7181]
([#7126](https://github.com/brave/browser-laptop/issues/7126))
([#7122](https://github.com/brave/browser-laptop/issues/7122))
([#6511](https://github.com/brave/browser-laptop/issues/6511))
([#7116](https://github.com/brave/browser-laptop/issues/7116))
([#7087](https://github.com/brave/browser-laptop/issues/7087))
([#6961](https://github.com/brave/browser-laptop/issues/6961))
([#6852](https://github.com/brave/browser-laptop/issues/6852))
([#6851](https://github.com/brave/browser-laptop/issues/6851))
([#6845](https://github.com/brave/browser-laptop/issues/6845))
([#6960](https://github.com/brave/browser-laptop/issues/6960))

**Comment by luixxiul** [comment]
@alexwykoff I think it's better to include the title of each issue next to the ticket number to make it more easy to find what was actually fixed

**Comment by alexwykoff** [comment]
For the purposes of testing I agree, but for the changelog which goes on the release page (and is more publicly consumable) most of these issues are considered trivial.

**Comment by luixxiul** [comment]
I understand, but because it is trivial I think users don't want to click each issue to find the trivial change. I'm going to add the title if you don't want to :-)
