### ISSUE TITLE
Close tab button should not appear on the title

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7183]
**Describe the issue you encountered:**
The close button appears over the title.

![closetab](https://cloud.githubusercontent.com/assets/3362943/22851596/7e02e93e-f06a-11e6-9cfe-649d4ef6edd8.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.13.3 RC1

- Steps to reproduce:
    1. Open a tab
    2. Move your mouse cursor on the tab
    
- Expected result:
1) Close tab button should not appear on the title
2) Close tab button should not appear if the mouse cursor is outside of the tab

- Any related issues: #6900 #6845 #5431

**Comment by bsclifton** [comment]
@cezaraugusto can you check this one out?
