### ISSUE TITLE
Dropdown on about:preferences has yellow borders

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7184]
**Describe the issue you encountered:**
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/22851633/c058e8b4-f06b-11e6-9136-67f7751cc1bf.png)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.13.3 RC1

- Steps to reproduce:
    1. Open about:preferences
    2. Click a dropdown
    
- Actual result: the dropdown has yellow borders 

- Expected result: the color of the borders should be the same as the `select` element, which is grey

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bbondy** [comment]
cc @bsclifton do you know what's going on here?
I also noticed devtools has a big yellow border on Windows:

<img width="685" alt="screenshot 2017-02-11 22 56 37" src="https://cloud.githubusercontent.com/assets/831718/22859624/e22c1288-f0af-11e6-9038-767337d7a5da.png">

**Comment by bsclifton** [comment]
I can't repro yellow in the dev tools... but I can easily repro yellow around the drop down.  Will be looking into this

**Comment by bsclifton** [comment]
Doesn't seem to be a CSS issue; seems to be an issue with Chromium / Muon.  Chrome is using 56.0.2924.87 (versus us using 56.0.2924.76)... I didn't [see anything important in the diffs though](https://chromium.googlesource.com/chromium/src.git/+/56.0.2924.76..56.0.2924.87/)

**Comment by bsclifton** [comment]
I have a jsbin which works well for repro'ing the issue:
http://jsbin.com/yiyibuwuzu/edit?html,output

When running from browser-laptop-bootstrap, the select box looks correct:
![screen shot 2017-02-13 at 1 43 08 pm](https://cloud.githubusercontent.com/assets/4733304/22902582/cabed6b4-f1f2-11e6-9af1-2fcb20c108b2.png)

However, if I run using 0.13.3-rc3, it has yellow borders:
![screen shot 2017-02-13 at 1 43 29 pm](https://cloud.githubusercontent.com/assets/4733304/22902601/da048cae-f1f2-11e6-9094-da2288e0ef7c.png)

Both are using Chromium 56.0.2924.76.  I'm looking at diffs now in Chromium between 54.0.2840.100 (0.13.2) and 56.0.2924.76 (HEAD)

**Comment by bsclifton** [comment]
Problem narrowed down; after running create_dist on **browser-laptop-bootstrap** and copying the binaries over the most recently browser-laptop prebuilt, it happens.  Looks like a problem w/ packaging (uglification, etc)

**Comment by bsclifton** [comment]
I believe I found the root cause: two files were not being copied over...
chrome_100_percent.pak
chrome_200_percent.pak

I copied both from src/out over to the prebuilt (C:\GitHub\browser-laptop-bootstrap\src\browser-laptop\node_modules\electron-prebuilt\dist\) and it works great 👍
