### ISSUE TITLE
Clicking middle mouse button does not open the bookmark in a new tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7185]
**Describe the issue you encountered:**
Clicking middle mouse button does not open the bookmark on the toolbar in a new tab.
It opens the link in a new tab on a web page.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.3 RC1

- Steps to reproduce:
    1. Bookmark a page
    2. Click the middle mouse button
    
- Actual result: Nothing happens

- Expected result: the bookmark should be opened in a new tab

- Any related issues:

**Comment by Liunkae** [comment]
Maybe related: #7144 (Middle mouse click doesn't close tabs)

**Comment by luixxiul** [comment]
@Liunkae I agree
