### ISSUE TITLE
Exported bookmarks are not retaining order

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7189]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When exporting and importing the exported file, it was found that order was not maintained.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.3 RC 1 https://github.com/brave/browser-laptop/commit/7024e09766a39e46f399dad2a84c40e086341b1f

- Steps to reproduce: (with a clean profile)
    1. Import a lot of bookmarks.
    2. Export bookmarks to a file. (file A)
    3.  Import File A.
    4. Export bookmarks to a file. (file B)
    5. Import File B.
    6. Repeat a few more times and then do a diff of the exported files.
    
- Actual result:
None of the files match.

- Expected result:
If the importer keeps bookmarks in order, and the exporter keeps bookmarks in order, and no new bookmarks were created, edited, or deleted, then the files should be identical.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by darkdh** [comment]
separated re-import issue to https://github.com/brave/browser-laptop/issues/7194

Updated STR:
1. Import a lot of bookmarks.
2. Export bookmarks to a file. (file A)
3. Delete all the bookmarks
4. Import from file A
5. The bookmarks order should be the same as step 1
