### ISSUE TITLE
Add inspect element

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#719]
"My biggest @brave browser desire right now is to have a Control + click "Inspect Element" option"
https://twitter.com/ianmcdonald_/status/697606889882972160

**Comment by twisterghost** [comment]
Seconded. Is this something not natively supported by electron? I dunno if this helps or not but a quick search in electron's repo came up with this:

https://github.com/atom/electron/blob/11e2058136967ba9d1b0a5e9011eb2e54c824f53/atom/browser/api/lib/browser-window.js#L191

Maybe it could be added to the context menu? Not familiar with how that data moves around but can look into it this evening.

**Comment by bbondy** [comment]
I added this before locally but it was opening the dev tools but not selecting the right element in the webview.  I think it was a bug in electron, but it could possibly have been a bug in my own code.

**Comment by bobvanluijt** [comment]
This is what I have right now in contextMenus.js

My issue currently lies in the `focusedWindow.webContents.inspectElement(x, y);` because it inspects the elements of Brave, not of the page DOM...

Any ideas?

```js
{
    label: 'Inspect Element',
    click: (item, focusedWindow) => {
      if (focusedWindow) {
        //var doc = document.documentElement;
        //var x = (window.pageXOffset || doc.scrollLeft) - (doc.clientLeft || 0);
        //var y = (window.pageYOffset || doc.scrollTop)  - (doc.clientTop || 0);
        x = 250;
        y = 250;

        // Selects the element correctly, not sure if needed though
        var selectedElement = document.elementFromPoint(x, y);

        // Toggles the dev tools correcly
        CommonMenu.sendToFocusedWindow(focusedWindow, [messages.SHORTCUT_ACTIVE_FRAME_TOGGLE_DEV_TOOLS]);

        // Does set a focus on an element, but it's not the DOM of the webpage
        focusedWindow.webContents.inspectElement(x, y);
        
      }
    }
  }
```

**Comment by bbondy** [comment]
Yes we use webviews to host actual content not directly in the BrowserWindows. You want the tab webviews.

See how `WINDOW_ZOOM_IN` works to get a message to the webview.
Make an action that changes state, and then react to the state change on the webview like `webview.setZoomLevel`

**Comment by bobvanluijt** [comment]
Hi peepz, solved it: https://github.com/brave/browser-laptop/pull/1148

**Comment by bbondy** [comment]
This is merged in, closing.
