### ISSUE TITLE
fa-search icon should not be displayed while loading unsafe scripts

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7191]
**Describe the issue you encountered:** fa-search should not be displayed while loading unsafe scripts

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.3 RC1

- Steps to reproduce:
    1. Open https://mixed-script.badssl.com
    2. Click the lock icon
    3. Select "Load Unsafe Scripts"
    
- Actual result: The fa-search icon is displayed and soon it is replaced with the unlock icon

- Expected result: There could be two results
1. the fa-lock icon should be replaced as soon as scripts are loaded and executed (before onload is fired)
2. the fa-lock icon should be replaced after all of the scripts are loaded and executed

In my humble opinion the 1st one is better because attacker could intentionaly slow down downloading the other resources . CC @diracdeltas 

Otherwise we could simply replace the icon when the buttons are pushed.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![fa-search](https://cloud.githubusercontent.com/assets/3362943/22852190/1eb923ac-f07a-11e6-854f-902780d38b31.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Similar issue: https://github.com/brave/browser-laptop/issues/5490

**Comment by srirambv** [comment]
It no longer shows fa-search icon when load unsafe script is clicked. Could this be closed?

**Comment by luixxiul** [comment]
Yes the issue has been fixed already, closing.
