### ISSUE TITLE
Re-import to bookmark toolbar will mess up the order

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7194]
## Test Plan:

a. getNextFolderName covered by unittest

b. Import bookmark:
1. Import bookmarks from other browser or html
2. There will always a folder contains the imported bookmarks
3. If the folder name already exist,
  it will be "Imported from XXX (1)", "Imported from XXX (2)" ... etc

## Original issue description
STR:
1. Re-import bookmarks twice by choosing merge into bookmark toolbar
2. The second import will overwrite the original bookmark by arbitrary order

Proposal: 
To make it simple, I suggest we follow the chrome behavior to eliminate this option

1. Only write to bookmark toolbar for the first time (No bookmarks)
2. If you have bookmarks, always create a folder for new imported bookmarks

cc @bradleyrichter , @bbondy

**Comment by darkdh** [comment]
Related #6564

**Comment by bradleyrichter** [comment]
@darkdh Your proposal sounds like the least amount of user friction. WFM.
