### ISSUE TITLE
Support multiple password managers simultaneously

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7198]
**Describe the issue you encountered:**

https://community.brave.com/t/support-for-more-than-one-password-manager/1159?u=suguru

> It would be great if Brave could support multiple password managers simultaneously. I have long used 1Password on a personal level, but for work purposes I use LastPass Enterprise. Chrome, Firefox, Safari, Vivaldi all permit me to use both. Brave makes me choose one or the other.

- Platform (Win7, 8, 10? macOS? Linux distro?): 

- Brave Version (revision SHA): 0.13.2

- Any related issues:

**Comment by justingarrett** [comment]
Yes please! I have the exact same problem... 1P for work and Last Pass for personal... would be amazing to use both like I can in Safari / Chrome. 

I am really enjoying using Brave though.... lovely browser. Let's hope it doesn't get bloated like the rest

**Comment by amandaporto** [comment]
+1 one this issue. 1password for work, and lastpass for personal purposes.

**Comment by PostPollux** [comment]
Yes, please! Make this happen! I also have to use 1password in the company where I work, but personally I use bitwarden. Now having to constantly switch the settings in Brave is very annoying! Other than that brave is just awesome!

**Comment by bsclifton** [comment]
@bradleyrichter @alexwykoff do we have any mockups of how this should look?

**Comment by delixyr** [comment]
I use both lastpass and dashlane (backup). This really did help me when lastpass failed to work with Firefox 57 (now it does with a beta version). I would like to have this feature too.

**Comment by bsclifton** [comment]
Marking as P4 - I personally don't feel this is critical, but it would be huge

cc: @davidtemkin, @bradleyrichter

**Comment by srirambv** [comment]
+1 from @Tera3yte via #12279
