### ISSUE TITLE
Refactor about:styles with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7201]
## Test Plan
make sure about:styles is as it should be

## Original issue description
Refactor `about:styles` with Aphrodite. It will let us remove less/about/styles.less, which is used only on that page.

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/blob/97503ffc172b999a1c93ab5209c0b0685983d6cb/js/about/styles.js#L90-L106 is broken because of this commit: https://github.com/brave/browser-laptop/commit/269d37bf26a3f9d5f9635533c670d3880df20aaf I will push a fix.

**Comment by srirambv** [comment]
![image](https://cloud.githubusercontent.com/assets/17010094/23363868/9eff0e60-fcf4-11e6-9cb4-434fe14421a4.png)
Small button definitely doesn't look small 😄

**Comment by luixxiul** [comment]
That's another issue which I have shared with @bradleyrichter and @bsclifton in a commit some times ago and I'm going to fix it by refactoring findBar with Aphrodite.

**Comment by bradleyrichter** [comment]
big is the new small.  😄
