### ISSUE TITLE
Edit location of bookmark discard info other than hostname

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7205]
STR:
1. Bookmark `https://www.brave.com`
2. Edit bookmark and paste `https://www.brave.com/index.html#faster`
3. Location is still `https://www.brave.com`

**Comment by luixxiul** [comment]
@darkdh I cannot confirm the fix on Windows 10 32 bit with a fresh profile.

**Comment by darkdh** [comment]
Please wait for RC3 if you are using RC build
see https://github.com/brave/browser-laptop/compare/v0.13.3dev-RC2...master

**Comment by luixxiul** [comment]
Still I cannot confirm this was fixed

**Comment by luixxiul** [comment]
STR:
1. Clear your profile
2. Open the browser
3. Click Twitter icon on the dashboard
4. Bookmark with the star icon
5. Edit bookmark via the toolbar
6. Try to make the URL into `http://twitter.com/brave/a`

Expected result:
The URL should be `http://twitter.com/brave/a`

Actual result:
The URL becomes `http://twitter.com`

**Comment by luixxiul** [comment]
Nevermind, I confirmed it just now.
