### ISSUE TITLE
Right Click Menu -- Undo Option (and others like Redo) Missing when Inputting Text

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#721]
Brave Menu: 
![2016-02-11 03_25_55-](https://cloud.githubusercontent.com/assets/470705/12973018/5e73fd2c-d06f-11e5-973b-abc793f1c6a2.png)

Chrome Menu which Includes Undo Option: 
![2016-02-11 03_26_14-](https://cloud.githubusercontent.com/assets/470705/12973045/8b04b19c-d06f-11e5-841f-26602fb9aada.png)

**Comment by psimyn** [comment]
added undo/redo in https://github.com/psimyn/browser-laptop/commit/f2938a68fbd647e9a598e169c8fa0ea98a22dfd0

They are never greyed out though (on OSX at least)

**Comment by weems** [comment]
@psimyn yet to be merged right?

**Comment by psimyn** [comment]
Not yet, wanted to get disabled state working. I'll create PR as is though
