### ISSUE TITLE
Won't build following instructions

### ISSUE THREAD

**Issue by Nobabs27** [brave/browser-laptop#7210]
Note: I'm new to building software from source, I'm trying to build this to try it as a web browser that can be used.   I'm not on OpenSUSE/Fedora/Debian.

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Followed the build instructions, got to "npm start", and I get an error.

- Platform:
Arch Linux, couldn't use the AUR packages because they simply don't work.

- Brave Version (revision SHA):
b9e4ed05830507a3f7b5dbf25af0932623a43ece if thats right?

- Steps to reproduce:
    1. Follow the instructions on the GitHub code page
   
- Actual result:
```
> brave@0.13.3 start /home/babs/Downloads/browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

[12746:12746:0212/170734.876141:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
process exited with code 0
```
- Expected result:
That it would work.

**Comment by Liunkae** [comment]
To fix the no usable sandbox error, please see the updated instructions here: https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
