### ISSUE TITLE
One pixel white line at edge of screen.

### ISSUE THREAD

**Issue by matthiaslange** [brave/browser-laptop#7211]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
I set up my taskbar so that maximized windows are over it. When I have a maximized Brave window (which covers my whole screen, since there's no taskbar visible), there's a one pixel white line at the bottom of the screen. Other windows cover the whole screen without a white line.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version (revision SHA):
0.13.2

- Steps to reproduce:
[edit: It actually happens without my tweaker nonsense, always a white line at the bottom when maximized. Maybe it's even intentional, in which case... I disapprove? ;)]

Um, been a while since I've changed the taskbar behavior. I'm using "7+ Taskbar Tweaker", and under advanced options, set disable_topmost to 2: "Not always on top, and overlapped by maximized windows".

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I just installed Brave, so i guess it's a "fresh profile".

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Wouldn't know if it happens on other PCs.

- Screenshot if needed:
Screenshot is difficult, since the line is at the bottom, so it might be hard to tell. But it's there.

![screenshot 2017-02-13 09 38 12](https://cloud.githubusercontent.com/assets/1380933/22876922/3477916a-f1d3-11e6-8439-89ce298e0f2a.png)

**Comment by siemiatj** [comment]
Can't repro on OSX 10.11.6 and Brave 0.13.3/36ee225 .

**Comment by bsclifton** [comment]
I believe this is Windows only.  It may or may not be related to https://github.com/brave/browser-laptop/issues/6698 or https://github.com/brave/browser-laptop/issues/7215

Electron has this exact issue captured with https://github.com/electron/electron/issues/8332

**Comment by bsclifton** [comment]
+1 from @srirambv via https://github.com/brave/browser-laptop/issues/14434
> ![image](https://user-images.githubusercontent.com/17010094/41485773-e30fa4cc-70af-11e8-9e99-954af87ab75e.png)
