### ISSUE TITLE
Keep reloading when open a Google Docs

### ISSUE THREAD

**Issue by ivankristianto** [brave/browser-laptop#7214]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
I open a Google document. the browser keep reloading.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
0.13.2 (25b1199)

- Steps to reproduce:
    1. I open Google Drive. drive.google.com
    2. Open a document
    3. It keep reloading the document
    
- Actual result:
It keep reloading the document

- Expected result:
The document is opened and ready to edit

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
@ivankristianto do you have fingerprint protection enabled?  We do know there are issues with Google Docs when you have that enabled. Can be disabled only got Google Docs by going to the Lion icon and toggling off

(more info available at https://github.com/brave/browser-laptop/issues/2965)

**Comment by ivankristianto** [comment]
Yes it is enabled. should i turn it off to make google doc working?

**Comment by bsclifton** [comment]
@ivankristianto yes- please do. Unfortunately, many of the Google sites do not work with fingerprint protection enabled

**Comment by bsclifton** [comment]
@ivankristianto were you able to test if it worked?  If so, maybe we can close this issue in favor of the larger parent issue, https://github.com/brave/browser-laptop/issues/2965

**Comment by ivankristianto** [comment]
Yes it does works. You can close this one

Thanks
iVan
