### ISSUE TITLE
Maximizing window puts the bottom 1px of window behind the taskbar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7215]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Maximizing window puts the bottom 1px of window behind the taskbar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.3
rev	40d9979
Existing issue verified till 0.12.15

- Steps to reproduce:
    1. Ensure task bar is placed in its default position(bottom)
    2. Install Brave
    3. Click on maximize button, 1px size of window is hidden behind the taskbar
    
- Actual result:
1px size of window is hidden behind the taskbar

- Expected result:
Complete window should be above the taskbar when maximized

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
on 0.12.15
![image](https://cloud.githubusercontent.com/assets/17010094/22879808/a59474ae-f1d7-11e6-9e9f-5688cfa23c06.png)
0.13.3 RC2 
![image](https://cloud.githubusercontent.com/assets/17010094/22879998/5c1353ee-f1d8-11e6-8b6f-b97a03b43a56.png)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
@srirambv interesting that you opened this up- I was just reviewing a similar report in Electron:
https://github.com/electron/electron/issues/4045

Basically, it's a problem upstream in Chromium.  It seems the ticket is close though- I'll see if I can give it a bump

**Comment by bsclifton** [comment]
For reference, here's the bug being tracked in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=576192

**Comment by lukemulks** [comment]
We've received a similar report from a contributor in the Brave Community: 
https://community.brave.com/t/youtube-skip-ad-button-disappeared-brave-window-overlaps-other-screen/2329/9

```
Brave: 0.15.0 
rev: 71fb73001617949528cc6473e288a49e76fcd4d5 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.15063 
os.arch: x64
```
**Contributor Feedback:**

>***Steps to reproduce:***
>*unclear - not sure, doesn't work every time*
>*1. minimze brave window*
>*2. open it up again*

![windows-brave-taskbar-overlap-04282017](https://cloud.githubusercontent.com/assets/8979240/25552965/43e9b63c-2c5c-11e7-810d-1322ab98e0cd.png)

**Comment by srirambv** [comment]
@bsclifton This works as expected but as a result when the browser is maximised and relaunched, there is a 1px gap between the browser window and the taskbar and the browser is in a maximised restore position and will have to maximised again to fit in screen correctly

**Comment by bsclifton** [comment]
@srirambv thanks for the heads up (and for creating the issue 😄  )
