### ISSUE TITLE
Tab text not properly visible  when tab theme is dark 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7216]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab text not properly visible when tab theme is dark 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.3
rev	40d9979

- Steps to reproduce:
    1. Enable `Show tabs in page theme color` under tabs in settings page
    2. Visit http://theverge.com in the new tab
    3. When tab is in focus, the tab text is not readable because of the dark tab theme colour, tab out/ on mouse over changes the color to text which makes it readable
    
- Actual result:
Tab text is not properly visible when tab theme is enabled

- Expected result:
Should be properly visible irrespective of what the tab colour is

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tabtext](https://cloud.githubusercontent.com/assets/17010094/22880253/63450080-f1d9-11e6-8765-83b6e24db4da.gif)

   ![image](https://cloud.githubusercontent.com/assets/17010094/22883164/b392a33c-f1e6-11e6-94ed-f22050a311e6.png)

- Any related issues:

**Comment by cezaraugusto** [comment]
Reproduced, Windows only. Taking.
