### ISSUE TITLE
Pinned tab animation needs to be better 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7219]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
With page theme color being shown on tabs, the pinned tab animation looks bad when a new tab is opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.3
rev	40d9979

- Steps to reproduce:
    1. Open YouTube in a new tab and pin it
    2. Open a new tab see the animation of the pinned tab
    3. Disable `Show page theme on tab` from settings under tabs
    4. Repeat the steps 1 & 2, looks much better than before but still needs to be more polished
    
- Actual result:
Pinned tab animation when closing/opening a new tab looks bad

- Expected result:
Pinned tab animation needs to be better 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![pintabsize](https://cloud.githubusercontent.com/assets/17010094/22883868/1b4e0180-f1ea-11e6-8df0-8f5370671036.gif)

- Any related issues:
Please change milestone if required

**Comment by cezaraugusto** [comment]
sorry don't get it. you mean the pinned tab background color? which animation?

**Comment by srirambv** [comment]
When tab has the page color opening a new tab causes the tab to become gray. This causes the tab look like it shrunk from the original size. Also if you observe closely when audio starts playing the size of the tab changes which causes all the tabs on right to move 
![tabshift](https://cloud.githubusercontent.com/assets/17010094/22892909/04d92f98-f20c-11e6-8b20-6fa294095755.gif)

**Comment by cezaraugusto** [comment]
I see, taking. thanks
