### ISSUE TITLE
reload should warn on form repost

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#722]
Reloading a page that was a POST request should warn the user before reposting
see NavigationControllerImpl::ReloadInternal

**Comment by luixxiul** [comment]
Was this implemented already?

**Comment by bridiver** [comment]
no, it's still an open issue afaik

**Comment by alexwykoff** [comment]
@bbondy is this still an issue? Thanks for taking a look!

**Comment by bbondy** [comment]
I think so.

**Comment by bridiver** [comment]
we've been emitting a `repost-form-warning` event for a while, but like the `new-window` event it will only work correctly if `preventDefault` is called in the browser process

**Comment by bsclifton** [comment]
Closing as `wontfix` since this is addressed with [Brave Core](https://github.com/brave/browser-laptop)
