### ISSUE TITLE
Unable to mute a pinned tab and audio indicator is not clearly visible 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7220]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Audio indicator on pinned tab is not properly visible

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.3
rev	40d9979

- Steps to reproduce:
    1. Open YouTube.com in a new tab and pin it
    2. Play an video on the pinned tab
    3. Audio indicator (blue line) is too subtle to be seen clearly 
    4. Clicking on the tab/blue line doesn't mute the tab
    
- Actual result:
Unable to mute a pinned tab and audio indicator is not clearly visible

- Expected result:
Audio indicator on a pinned tab should be visible and should be able to mute the tab when click on the audio indicator

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![pinmute](https://cloud.githubusercontent.com/assets/17010094/22885447/6dc25ae0-f1f1-11e6-914b-68dcb0b3f746.gif)

- Any related issues:
cc: @bradleyrichter 
Please change the milestone if requried

**Comment by NejcZdovc** [comment]
@srirambv I think that you paste screenshot from #7219

**Comment by srirambv** [comment]
@NejcZdovc  Thanks. Updated. Too many gifs make it difficult 😄

**Comment by cezaraugusto** [comment]
Audio is just an indicator at that point and can't think a way to make it action-ready on small sized tabs.

@bradleyrichter for thoughts. How can we make it?

**Comment by bbondy** [comment]
It is enough that the user can right click and click on mute tab in the context menu. So marking as won't fix.

**Comment by bradleyrichter** [comment]
I have an idea but let's wait for more feedback. Rt click is acceptable for now.
