### ISSUE TITLE
Can't add folder in bookmarks.

### ISSUE THREAD

**Issue by siemiatj** [brave/browser-laptop#7229]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:

Not sure if this doesn't work only when you have no additional bookmarks folders or it's some regression but I can't add  a folder in bookmarks manager. Clicking the icon pops up a modal that looks exactly like bookmark adding modal and filling name input still doesn't make the button active. Gif file attached. Is it a regression ?

- Platform (Win7, 8, 10? macOS? Linux distro?):

OSX 10.11.6

- Brave Version (revision SHA):

0.13.3.36ee225

- Steps to reproduce:
    1. Go to Bookmark Manager
    2. Try adding a new folder
    3. Fail badly
    
- Actual result:

Modal looks incorrect and doesn't allow adding bookmark.

- Expected result:

Show modal with different message and add a bookmark folder.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes, fresh profile.

- Is this an issue in the currently released version?

Not in 0.13.2.

- Can this issue be consistently reproduced?

Apparently yes.

- Extra QA steps:

- Screenshot if needed:

![bookmarks](https://cloud.githubusercontent.com/assets/513460/22907591/25711a20-f24a-11e6-9d16-8f6cc94fd61e.gif)

- Any related issues:

**Comment by michalbe** [comment]
This was probably caused by [commit 6befe33994c5](https://github.com/brave/browser-laptop/commit/6befe33994c5e2653f24eeaef2dabb6e97957e3c) since it works with the previous one ([commit b9e4ed0583](https://github.com/brave/browser-laptop/commit/b9e4ed05830507a3f7b5dbf25af0932623a43ece).

**Comment by siemiatj** [comment]
If this is confirmed I'm more than happy to fix it.

**Comment by ayumi** [comment]
can repro at bcbafeca663d07281464960723c2549a8e16168e, MacOS, fresh profile

**Comment by luixxiul** [comment]
On Windows 10 the issue cannot reproduced. It may be specific to macOS

**Comment by Liunkae** [comment]
Reproduced with latest master (bcbafec) on macOS 10.12.x with a fresh profile.

![image](https://cloud.githubusercontent.com/assets/19424103/22913779/7918a5d4-f232-11e6-9f51-cfe8c762f479.png)

`Right-click bookmarks toolbar > Add Folder` does not work either. There is apparently no way to create bookmarks folders.

Tagging this as blocking for 0.13.3. Please change if needed.
