### ISSUE TITLE
Page navigates back and forward when using command + left within an input field

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#723]

**Comment by obvio171** [comment]
Surprisingly, it seems *not* to navigate back/forward when I'm *not* within an input field. And on the urlBar it neither navigates nor moves the cursor.

**Comment by diracdeltas** [comment]
basically it checks for whether CMD+left/right was entered while an input, textarea, or contentEditable element was in focus; if so, it shouldn't go back/foward. Some sites break this if they are using custom content editable fields. If you see this again, please note which site this was on.

**Comment by diracdeltas** [comment]
The broader problem is that our page navigation shortcuts are just regular javascript keyDown handlers, which any page can override by preventing the event from reaching our handler. So this is always going to be flakey.

**Comment by bbondy** [comment]
Happens on github textarea pull request or comment fields.  The one I'm typing in now.

**Comment by diracdeltas** [comment]
ah cool, i think this is a regression. looking into it now.

**Comment by diracdeltas** [comment]
@bbondy i think this was due to you registering this shortcut as a localShortcut, which i reverted

**Comment by bbondy** [comment]
but does Command+Left still work now?

**Comment by diracdeltas** [comment]
yes, it works if you are in the webview

**Comment by bbondy** [comment]
should work from chrome focus too

**Comment by bbondy** [comment]
maybe we need a handler higher up the hierarchy instead of local-shortcuts to make both work correctly?

**Comment by diracdeltas** [comment]
It doesn't work in Chrome unless the webview-area is focused

**Comment by bbondy** [comment]
deceptive because you can't focus the title bar on Chrome.  Click on our titlebar then Command+Left and it won't work. 
Click on Chrome title bar and Command+Left and it will work.

I think we just need to mark our nav area as non focusable.
