### ISSUE TITLE
Bookmarks in Other Bookmarks should not be merged into Bookmark Toolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7231]
**Describe the issue you encountered:** By default the bookmarks in Other Bookmarks are merged into Bookmark Toolbar when you import browser data. It surely could work well in some cases (say you would find bookmarks which you think you have lost), but other cases not so well. If you for example have a number of the bookmarks in Other Bookmarks subfolder, they also will be imported on the bookmark toolbar.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.13.2

- Steps to reproduce:
    1. Bookmark URLs on Bookmark Toolbar
    1. Move some of them into Other Bookmarks on Bookmark Manager
    2. Export them 
    3. Import them, merging into Bookmark toolbar
    
- Actual result: All bookmarks are imported on the toolbar

- Expected result: Only the bookmarks which were bookmarked on the toolbar should be imported to the toolbar. The others should be imported into Other Bookmarks

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by darkdh** [comment]
This is the same behavior as Chrome except Chrome doesn't merge them into bookmarks toolbar.
But we will do the same thing in #7194

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/7194
