### ISSUE TITLE
Browser performance reduces when large amount of bookmarks are imported

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7240]
## Test plan

https://github.com/brave/browser-laptop/pull/8075#issue-219459882

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser performance reduces when large amount of bookmarks are imported

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.3
rev	27f447f
Same on 0.13.2 as well

- Steps to reproduce:
    1. Import a large bookmark HTML file 
    2. Open new tabs and open from bookmarks
    3. Open bookmark folders, response on click is too slow
    
- Actual result:
Performance is very slow after large amount of bookmarks are imported

- Expected result:
Imported bookmarks should not impact browser performance

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
0.13.2 http://sendvid.com/ekjiz2cv
0.13.3 http://sendvid.com/0q3t3iey

- Any related issues:
[Community issue](https://community.brave.com/t/system-requirements-brave-slow-sluggish-on-one-computer-but-not-on-another/1212)
cc: @darkdh 
Please change milestone if required

**Comment by CliqueBait** [comment]
Community feedback:
https://community.brave.com/t/creating-bookmarks-takes-a-long-time/1987

This performance hit is a deal breaker for some users. I'm not sure they can wait for v1.0.0 for this to be fixed. Can this issue be expedited or failing that an interim fix be included in an earlier release?

**Comment by Liunkae** [comment]
The address bar's performance is affected by many bookmarks (#6620 and #7453).

**Comment by luixxiul** [comment]
Another report here: https://community.brave.com/t/25-cpu-probably-1-core-slow-and-unstable-after/1989

**Comment by escalope** [comment]
I run a linux mint with 8GB and dual core. Brave v. 0.15.2-1

Brave run like a charm, but after importing my firefox bookmarks (200+ bookmarks) performance decreased. Google tools (drive+gmail) were very slow to the point of taking half a second to type a character. 

Could not remove bookmarks through brave (even with select + delete). So I had to delete brave folder in .config. 

After this, performance returned to normal.

**Comment by luixxiul** [comment]
that performance issue you have mentioned (importing many bookmarks makes the browser slow down) is going to be fixed with the next release.

**Comment by srirambv** [comment]
Not seeing any significance improvement on Windows with the test file.

**Comment by LaurenWags** [comment]
Confirming I saw similar results to @srirambv on MacOS after continuous use for 2-3 hours. However, after closing and coming back for approx half an hour of continuous use, did not see the same results.

**Comment by darkdh** [comment]
@srirambv , @LaurenWags did you test with `open folder on bookmark toolbar`?
If so, that is different issue haven't been solved yet.
The PR only addressed 
1. Open bookmarks of menu shouldn't affect performance
2. Open about:bookmarks shouldn't affect performance

**Comment by LaurenWags** [comment]
@darkdh - just to make sure i'm understanding correctly, you're saying that for 1, if we open a bookmark from the bookmarks toolbar, that shouldn't affect performance? and for 2, if we have about:bookmarks open that shouldn't affect performance?

**Comment by darkdh** [comment]
for 1 is opening
<img width="294" alt="screen shot 2017-06-21 at 1 55 07 pm" src="https://user-images.githubusercontent.com/11330831/27406310-5205f968-5689-11e7-865b-5d67bfba5b2c.png">
and for 2 if we open about:bookmarks and the page will not be delayed to display

cc @bsclifton for also manually applying PR to test

**Comment by srirambv** [comment]
@darkdh  This is what I followed, as per original STR which still has a very bad performance lag
1. Import large bookmarks
2. Open a new tab and visit any site/the one that is bookmarked
3. Bookmark toolbar -> Imported folder -> Open  bookmark folder
There is a very significant lag in response in opening the folder

Step 1 that you mentioned opening bookmark menu works fine, but there is a little lag when navigating inside nested folders and back from sub-folders to root folders, or scrolling inside sub-folders
Step 2 that you mentioned works fine, Opening `about:bookmarks` has no performance lag

**Comment by Grumbel** [comment]
I am on Ubuntu 17.04 with Brave 0.18.36 and the Bookmark performance is still terrible. Trying to navigate through the Bookmark menu comes with 1sec lag between mouse action and GUI response (e.g. opening a submenu, updating the highlighted item).

`about:bookmarks` doesn't feel super responsive either, opening a large folder can take around half a second or so. 

I have around 4000 bookmarks spread over numerous submenus, imported from Chrome. Chrome can handle that amount of bookmarks without any noticeable delays.

**Comment by luixxiul** [comment]
it'll be addressed on 0.19

**Comment by HamishMacEwan** [comment]
It hasn't been addressed, bookmarking a URL is excruciatingly slow.  The import from Firefox took, I don't know, I went for a walk and had lunch...

 
Brave: 0.19.147 
rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
Muon: 4.7.6 
libchromiumcontent: 64.0.3282.119 
V8: 6.4.388.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 3.16.0-4-amd64 
OS Architecture: x64

**Comment by Liunkae** [comment]
@HamishMacEwan You might want to try with the latest version of Brave that came out today, 0.20.29. It contains a number of performance fixes.

**Comment by HamishMacEwan** [comment]
Thanks @Liunkae.  It is better, still not good but much better.

Any plans to:

1. Allow folder creation in the bookmark add dialogue
2. Expand/Collapse folders in bookmark viewing

These requirements, like the performance issue, all relate to heavy bookmarking and categorising uses.

**Comment by Liunkae** [comment]
@HamishMacEwan There are plans for both of those features. See issues #8346 and #5077.

**Comment by HamishMacEwan** [comment]
Thank you.  I have subscribed to both those issues in hope of learning they're available asap.
