### ISSUE TITLE
Torrent Viewer CSP rule blocks <iframe> content

### ISSUE THREAD

**Issue by feross** [brave/browser-laptop#7243]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered:

Sometimes torrent content is rendered in an `<iframe>` instead of a `<video>` or `<audio>` tag. It's unclear why. When this occurs, CSP prevents the iframe from loading content from the webtorrent server at http://localhost:port

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS Sierra

- Brave Version (revision SHA): `master` @ 6cf4f1b0ac10e7bf36865dc47cc50146a7a231c0

- Steps to reproduce:
    1. Happens to one of the torrents here, can't remember which off the top of my head https://codepen.io/ferossity/full/qaezaB/ 
    2. Start the torrent
    3. Click on a file in the torrent to view it in Brave
    
- Actual result: File content fails to load

- Expected result: File content should load

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

**Comment by feross** [comment]
I can tackle this issue.

**Comment by feross** [comment]
> Sometimes torrent content is rendered in an `<iframe>` instead of a `<video>` or `<audio>` tag. It's unclear why.

Torrent content is rendered into `<iframe>` when it's not video or audio content. For example, a .jpg or a .pdf file. This is because we're using a viewer page that includes the content; we're not returning the content directly.

This is because the torrent may not be active and in that case, we show the "Start Download?" page. 

> When this occurs, CSP prevents the iframe from loading content from the webtorrent server at http://localhost:port

This is because we only make a CSP exception for media elements, not iframe elements. This is an easy fix.

**Comment by bsclifton** [comment]
Moving to 0.14.1

**Comment by luixxiul** [comment]
Moving back to 0.14.0?

**Comment by feross** [comment]
Oh, sorry if I merged too soon.

**Comment by luixxiul** [comment]
By following the test plan I get this error.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24056172/0631b8f4-0b86-11e7-8b4f-78ed787682c6.jpg)

**Comment by srirambv** [comment]
When torrent is opened within the the page, the file is not shown but opening the magnet link in a new tab it shows the file. Is this expected?
![7243](https://cloud.githubusercontent.com/assets/17010094/24060977/85a73458-0b4d-11e7-9523-237de4b18b0d.gif)

No errors in console, on Windows 10 x64, like @luixxiul mentioned

**Comment by feross** [comment]
All this behavior is expected.

CodePen switched to https and that prevents us framing the `magnet:` link viewer, since those are considered insecure content. Insecure content can't be framed in a secure context; that's "mixed content".

I'll add `target='_blank'` to all the links in the CodePen to make it easier to open links in a new tab.

The error spew is normal and harmless. Working as expected, though I'm working on making it more elegant in this PR: https://github.com/brave/browser-laptop/pull/7351
