### ISSUE TITLE
page-break appears to be broken inside a block element with width 100% and padding > 0

### ISSUE THREAD

**Issue by mphaney** [brave/browser-laptop#7244]
When a page-breaking block element appears inside a div with width set to 100% AND a padding specified, the page-break is rendered incorrectly according to how much padding is used. i.e. 0 padding causes no offset, 10px padding would cause a 10px offset of the page break, etc.

The issue was first discovered in Chrome 56.0.2924.87 (64-bit) on Windows 10 Pro, Insider build 15031, but has since been verified on the current public release of Windows 10, as well as OSX and, more to the point, in Brave on all three platforms.

- Brave Version (revision SHA): 	0.13.2 (25b1199)

The following HTML will produce the problem:
```
<!DOCTYPE html>
<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Page-Break Test</title>
<style>
  /* When a page-breaking block element appears inside a div with width
     set to 100% AND a padding specified, the page-break is rendered
     incorrectly according to how much padding is used.
     i.e. 0 padding causes no offset, 10px padding would cause a
     10px offset of the page break, etc. */
  #outer {
    width: 100%; /* Commenting out this line removes the issue */
    padding: 10px;
  }

  span {
    display: block;
  }

  .break {
    page-break-before: always;
  }
</style>
</head>

<body>
<div id="outer">
  <span>Heading 1</span>
  <p>Body 1</p>
  <span class="break">Heading 2</span>
  <p>Body 2</p>
  <span class="break">Heading 3</span>
  <p>Body 3</p>
</div>
</body>

</html>
```
    
- Actual result:
![actual](https://cloud.githubusercontent.com/assets/2546626/22945907/b78cfbda-f2aa-11e6-92fd-7cb29af2e930.png)

- Expected result:
![expected](https://cloud.githubusercontent.com/assets/2546626/22945918/c19096f0-f2aa-11e6-8e0e-a549771c793c.png)

The steps above do appear to reproduce in a fresh profile and, as I mentioned, in Google Chrome as well (suggesting it's probably in Chromium and not Brave?)  Thus far I have found the issue to be consistent everywhere I have looked.

**Comment by luixxiul** [comment]
@bsclifton do you think modifying Muon or libcontentchromium could fix the issue?
