### ISSUE TITLE
Tabs cannot unpinned

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7253]
**Describe the issue you encountered:** Tabs cannot unpinned. When you try to unpin the tab, you get the cloned tab which is not pinned, keeping the pinned tab.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.13.3 latest RC

- Steps to reproduce:
    1. Clear your profile
    2. Open the browser
    3. Open twitter.com via the dashboard
    4. Wait until the page is completely loaded
    5. Pin the tab
    6. Unpin the tab
    
- Actual result: You will get the unpinned tab and the pinned tab which is loaded new

- Expected result: The tab should not duped

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
sweet find!

**Comment by rob-blasetti** [comment]
I can confirm this bug is also on macOS.
