### ISSUE TITLE
Middle click on a link on a web page opens tab in the background

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#7254]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When "Switch to new tabs immediately" setting has been selected, middle clicking on a link on a web page opens a new tab in the background.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 16.10
- Brave Version (revision SHA): 0.13.3 (b4cb1f5)

**Steps to reproduce:**
    1.Go to settings and turn on "Switch to new tabs immediately";
    2.Middle click on a link on a web page;
    3.New tab opens in the background, not foreground.
    
**- Expected result:**
The new tab should open in the foreground, like with right clicking and selecting "Open Link in New Tab".

**Can this issue be consistently reproduced?**
Yes.

**Comment by bsclifton** [comment]
This has been fixed
