### ISSUE TITLE
1Password appears to be slower when Brave is open

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7257]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When Brave is open and configured to use 1Password, the 1Password desktop application appears slow to respond. It may at times take up to 5 seconds to react to user-clicks.

Original report here (scroll to top): https://twitter.com/BraveSampson/status/831852837881647105

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

**Comment by NejcZdovc** [comment]
I am using macOS and 1Password and I don't have any performance problems.
