### ISSUE TITLE
Add search shortcut for Can I use

### ISSUE THREAD

**Issue by notaurologist** [brave/browser-laptop#7261]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

It would be useful to have a "Can I use" search provider. I can submit a PR, but I'm curious if this has been considered and rejected before. I don't see an existing issue/PR, but maybe Brave doesn't want to add a search provider for a site not using SSL.

If there are requirements for adding search providers, they would useful to know. I'm guessing Brave would maybe like to hit a sweet spot between convenience and SP overload. If it ever came to that, maybe an interface through which people could add their own custom providers would be useful.

**Comment by Liunkae** [comment]
The ability to add custom search engines is currently set for version 1.1.0 (issue #3053).
