### ISSUE TITLE
about:preferences should be reponsive width

### ISSUE THREAD

**Issue by psmalone** [brave/browser-laptop#7263]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

When opening the preferences window with a non-maximized window, the contents do not arrange gracefully, requiring horizontal scrolling.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X 10.11.6

- Brave Version (revision SHA):

0.13.4 71d8ffc

- Steps to reproduce:
    1. Resize window to something narrow
    2. Open preferences
    3. Open Search or Payments tab
    
- Actual result:

Attached

- Expected result:

Gracefully wrapped to avoid horizontal scrolling

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Unknown

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

Attached (after scrolling right)

![screenshot 2017-02-15 11 01 34](https://cloud.githubusercontent.com/assets/23506653/22982987/b5e5a9ca-f36e-11e6-90cb-941f5b387736.png)

- Any related issues:

**Comment by Liunkae** [comment]
I also can reproduce with Brave 0.13.3 on macOS 10.12.x.
