### ISSUE TITLE
Right click new tab icon (+) also processes left click event

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7267]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Right clicking the new tab button (the + icon next to the row of tabs) is supposed to present a menu with: new tab / new session tab / new private tab / new window

The right / middle click behaviors were changed with Chromium 56 and I believe this behavior had an unintentional regression with https://github.com/brave/browser-laptop/commit/40d9979755cd1c377062d229058aef7ad651c78d

The menu does show, but it also sends a click.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version (revision SHA):
0.13.4

- Steps to reproduce:
    1. Launch Brave
    2. Right click on new tab icon (+)
    
- Actual result:
Menu is shown AND a new tab is opened

- Expected result:
Only menu is shown

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

**Comment by Liunkae** [comment]
Also happens with right-clicking the refresh button.
