### ISSUE TITLE
Session tab no longer works

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7268]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When trying to launch a new session tab, a new tab is opened but it appears to have the same partition ID.  The "person" icon is not shown on the tab and if I open a domain which I'm already signed into (on the same partition), ex: GitHub or Twitter, it shows me as logged in

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
Brave	0.13.4
rev	71d8ffc

- Steps to reproduce:
    1. Launch Brave and log into a site like Twitter or Facebook 
    2. Use menu to open new session tab
    3. Visit the same site as step 1
    4. Notice you're logged in
    5. Close tab
    6. Right click the new tab icon (the + next to the tabs)
    7. Pick "new session tab"
    8. Again, visit the site from step 1
    9. Notice you're still logged in
    
- Actual result:
New tabs still has the same partition

- Expected result:
It should have a different partition ID and session should not be shared

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1. Besides trying the two methods above, feel free to try the keyboard shortcut (Shift+CMD+S)
    2. any other ways new session tab can be created?
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
For me new session tab creates a new session, the person icon goes on the tab on top right. The info for the session is available in the urlbar if not on the newtab page.

**Comment by bsclifton** [comment]
@bbondy ah- you're right... with master, creating a new session tab works.  Looks like it may only be broken in 0.13.4.  I'll go ahead and close this out
