### ISSUE TITLE
blocking 3rd party cookies breaks Adobe typekit web fonts

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#727]
https://use.typekit.net

thoughts @diracdeltas ?  Safari seems to let it through with all cookies blocked.

We need to protect and still look pretty.   :   )

![screen shot 2016-02-11 at 8 46 28 am](https://cloud.githubusercontent.com/assets/13509546/12983317/a53e9dd8-d09d-11e5-85d6-a455f7f708e8.png)

**Comment by diracdeltas** [comment]
Nice catch. Turns out this is due to referer blocking, not cookie blocking. Safari doesn't do referer blocking. Not sure why typekit does referer checking at all, since that is easily spoofed. will fix by adding an exception.

**Comment by bbondy** [comment]
nice find!
