### ISSUE TITLE
False indication of Audio playback in a tab

### ISSUE THREAD

**Issue by aakashysharma** [brave/browser-laptop#7271]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
While browsing a website, I noticed the audio playback icon on the tab. The website has embedded GIF. However, there is no audio. The audio playback icon on the tab is a false indication.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7
- Brave Version (revision SHA):
	b4cb1f5
- Steps to reproduce:
    1. Go to website with embedded GIF (like http://www.theverge.com/circuitbreaker/2017/2/15/14629116/mcdonalds-shamrock-shake-straw-release )
    2. Switch to some other tab
    
- Actual result:
 The tab containing the browser tab shows audio playback indicator
- Expected result: 
There shouldn't be any indicator as the tab is not playing any audio
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Not sure if it existed earlier
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
No
- Any related issues:
No

**Comment by luixxiul** [comment]
Closing in favor of #257
