### ISSUE TITLE
LastPass requires re-login if cookies are cleared at exit

### ISSUE THREAD

**Issue by twhiting** [brave/browser-laptop#7274]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:

Since LastPass requires a cookie to save user data between sessions, if I have the option to "clear cookies when the browser is closed" selected, LastPass information is lost with every new instance launch.  Requiring a re-login.  This is bad because if I want LastPass info saved between sessions but do not want any cookies from sites saved to my machine, I'm out of luck.  A solution would be to exclude LastPass cookies from the option to clear all cookies at login.  That way I do not have to keep all cookies on my machine just to have LastPass save my information.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, probably a problem universally.

- Brave Version (revision SHA):

```
Brave	0.13.4
rev	71d8ffc
```

- Steps to reproduce:
    1. Login to LastPass > Preferences > Deselect `Automatically Log out when all browsers` options
    2. Select option to clear cookies at Exit in Brave.
    3. Exit Brave
    4. Open Brave  & a re-login to LastPass is required.
    
- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

**Comment by newm-newm** [comment]
Also having this issue on Win10
75ffa36

**Comment by whitgroves** [comment]
I have this issue on Ubuntu (Xenial) as well.

**Comment by srirambv** [comment]
Closing in favour of #13098 . Added +1 on the issue
