### ISSUE TITLE
Add a way to go back to add a sync code

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7275]
I accidentally went into create a new sync account, and then had no way to go back to sync this device to another one. Please make a way to go back to that main screen and reset sync back to initial state if the user does the wrong selection like that.

cc @diracdeltas @diracdeltas

**Comment by diracdeltas** [comment]
i'll add a button to clear sync state completely

**Comment by bbondy** [comment]
++ thanks

**Comment by ayumi** [comment]
Related: https://github.com/brave/sync/issues/51
