### ISSUE TITLE
IETab potential issues

### ISSUE THREAD

**Issue by vgturtle127** [brave/browser-laptop#7279]
I saw on the requested extensions that IETab was requested, and I thought I should bring up some points on why it might not be a good candidate.

First of all, this would only be an available feature on Windows computers running at least Windows 7. That isn't a terrible issue or anything, but it is one limitation.

Second, it requires either support of the Netscape Plugin API, or a separate executable to be downloaded and installed. If this was downloaded, I can think of that being an issue. How the executable was delivered, how to ensure it was the correct one for Brave, etc. Obviously, the NPAPI standard was depreciated in Chrome/Chromium, and therefore Brave wouldn't be able to support it that way.

Third, I saw that somebody stated that it would mainly be for "enterprise" websites. I think most are moving away from things like ActiveX, Flash, and other plugins and depreciated software. And I think browsers removing plugin support and Windows reducing the amount of ActiveX and legacy content in it's operating system and web browser are some indication of that.

Fourth, the IETab extension uses the locally installed Internet Explorer files to use the renderer to display how IE would render the website, but we should ask ourselves what that might potentially mean for Brave users (and Chrome/Chromium users as well). Are there security and privacy concerns, will this tank performance when in use, etc.

Just thought I would mention all of this, Brave being a browser focused on security, privacy, and speed.

Another note is that IETab should not be confused with IE Tab Multi, IE Tab Plus, or the original version of IETab designed for Firefox 1-3.0.

Let's discuss. :smile:

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of our community site.

https://community.brave.com/t/ietab-extension/7475/4

Let's continue to discuss the issue there 😄
