### ISSUE TITLE
url preview sometimes get "stuck"

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#728]
This one is a little tricky to reproduce reliably, but occasionally I see the url preview at the bottom of the page and I have to hover another link to get rid of it. Probably losing the mouseout event sometimes. I believe there are some workarounds to this kind of issue used by jquery
cc @psimyn

**Comment by psimyn** [comment]
any pages in particular you've seen it on @bridiver?

**Comment by bbondy** [comment]
We need more specific steps to repro if this is still an issue. Closing for now.
