### ISSUE TITLE
Invalid sync code alert needs proper heading

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7280]
## Test plan
   1. Enable sync on the device and click on `I have an existing sync code`
   2. Enter wrong text and click `Setup Sync`
   3. Alert window should now look correct (showing "Brave" instead of extension ID)

## Original issue description
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Invalid sync code alert needs proper heading

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Enable sync on the device and click on `I have an existing sync code`
    2. Enter wrong text and click `Setup Sync`
    3. Alert window doesn't show proper heading
    
- Actual result:
Alert window doesn;t show proper heading

- Expected result:
Should show `Brave Sync` as the alert box heading

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23019672/75a8f696-f43b-11e6-8361-108db95e277f.png)

- Any related issues:
cc: @ayumi

**Comment by diracdeltas** [comment]
@srirambv are you running Brave with @bsclifton's alert dialog changes? this is what i see on master:

![screen shot 2017-02-16 at 10 17 16 pm](https://cloud.githubusercontent.com/assets/549654/23044066/82bb6ce6-f496-11e6-9eaa-f2003c026515.png)

@bsclifton: maybe we can change the alert dialog to show friendly names for chrome-extension:// origins (like the name of the extension) instead of just the extension ID

**Comment by diracdeltas** [comment]
there is actually some code already in brave/browser/brave_javascript_dialog_manager.cc that is supposed to handle extension alerts but it is commented out

**Comment by srirambv** [comment]
@diracdeltas I am using 0.13.5 P1 build not master

**Comment by bsclifton** [comment]
@diracdeltas my code is still up in a PR- per your comment in the PR, I should be able to fix this up 😄  Thanks for assigning it over and providing more details

**Comment by srirambv** [comment]
Still same alert box on Preview 3. Verified on master 
![syncerror](https://cloud.githubusercontent.com/assets/17010094/23465732/0d8d7a4a-fe91-11e6-8d4c-f721b948440e.PNG)
