### ISSUE TITLE
Setup Sync button has an unwanted space 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7281]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Setup Sync button has an unwanted space 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23019896/5b88d74e-f43c-11e6-8e8a-b497cc2ee316.png)
Should be 
![image](https://cloud.githubusercontent.com/assets/17010094/23019873/49be8b94-f43c-11e6-8fee-886b52cf3e82.png)

- Any related issues:
cc: @ayumi

**Comment by luixxiul** [comment]
"Set up sync" sounds grammatically correct.
