### ISSUE TITLE
Editing/Deleting bookmark from toolbar causes the active tab to load the deleted bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7284]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Deleting bookmark from toolbar causes the active tab to load the deleted bookmark

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 

- Brave Version (revision SHA):
Brave: 0.13.5
rev: 59a41eb

- Steps to reproduce:
    1. Add a bunch of bookmarks on a clean install of 0.13.5
    2. Open a new tab and delete one of the bookmarks from toolbar
    3. Deleted bookmark page is opened in the active tab
    
- Actual result:
 Deleted bookmark page is opened in the active tab

- Expected result:
Should only remove the bookmark and not load the page in active tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes. Issue found from 0.13.3 on wards

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![deletebookmark](https://cloud.githubusercontent.com/assets/17010094/23021715/4882e550-f445-11e6-8704-adf1c8c8681b.gif)

- Any related issues:

**Comment by srirambv** [comment]
Basically right click on the bookmark item causes it to open in the current active tab

**Comment by bsclifton** [comment]
cc: @bbondy (may be related to the aux-click)

**Comment by srirambv** [comment]
User Jim has reported similar issue on community. https://community.brave.com/t/right-click-bug-opening-tabs/1313. Right click on bookmark item and select open in new tab causes the bookmark to be opened in the active tab and in a new tab.

**Comment by srirambv** [comment]
This is still an issue on preview 3 but verified and working fine on master
