### ISSUE TITLE
Uncaught Exception when updating from node v5.5 to v5.6

### ISSUE THREAD

**Issue by erossonero** [brave/browser-laptop#729]
Got the attached error when updating while brave was opened.
![braveerr](https://cloud.githubusercontent.com/assets/16802489/12983830/0f1db5de-d0b9-11e5-8083-077d64938987.png)

**Comment by bbondy** [comment]
Thanks for posting. I think it is one time and was due to the upgrade from node v5.5 to v5.6. Not sure how to handle those better for updates.

**Comment by luixxiul** [comment]
Closing as updating node inside 5.x happens rarely.
