### ISSUE TITLE
Bookmark title is missing in edit bookmark modal after it is synced

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7291]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Title missing in the bookmark on the second sync'd device 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Enable sync on Device 1 
    2. Visit any site and bookmark it
    3. Edit the bookmark verify title is shown 
    4. Enable sync on device 2 using the secret code
    5. Verify the bookmark added in step 2 is shown on device 2 as well
    6. Edit the bookmark on device 2, title is missing
    7. Edit the bookmark on device 1, title is missing there too
    
- Actual result:
Bookmark title is missing in edit bookmark modal after it is synced

- Expected result:
Title should be shown on both the devices

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @ayumi

**Comment by diracdeltas** [comment]
I can't repro this. It takes a minute, but editing the bookmark title in device 2 properly syncs the new title to device 1. @srirambv can you check again?

**Comment by diracdeltas** [comment]
i can repro this now
