### ISSUE TITLE
Bookmark folder tree structure is not properly synced between devices

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7293]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmark folder tree structure is not properly synced between devices

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Enable sync on two diff device and ensure bookmarks option is selected
    2. Import bookmark html file which has nested bookmark folders structure in pyramid 1
    3. The same folder structure is not followed in pyramid 0
    
- Actual result:
Bookmark folder tree structure is not properly synced between devices

- Expected result:
Both device should have the same folder structure

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Pyramid 0
![image](https://cloud.githubusercontent.com/assets/17010094/23034757/c0ec45de-f474-11e6-9a04-3bca94b9c757.png)
Pyramid 1
![image](https://cloud.githubusercontent.com/assets/17010094/23034619/540fb55e-f474-11e6-8af7-2625b6d38212.png)

- Any related issues:
https://github.com/brave/sync/issues/49

**Comment by srirambv** [comment]
cc: @ayumi

**Comment by diracdeltas** [comment]
i think this may be due to a race condition in `getObjectById` when calling `applySiteRecord`. if `applySiteRecord` is called for a bookmark UPDATE before the same bookmark's CREATE has propagated to appState, then `getFolderIdByObjectId` returns undefined, so the bookmark is not in any folder
