### ISSUE TITLE
Bookmark Favicons are not sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7294]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmark Favicons are not sync

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Enable Sync on two devices
    2. Import bookmarks on Pyramid 1
    3. Bookmarks synced on Pyramid 0 doesn't have favicons
    
- Actual result:
Favicons missing in pyramid 0 after bookmarks sync

- Expected result:
Favicons should be shown on both pyramid 0 and pyramid 1

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Pyramid 0
![image](https://cloud.githubusercontent.com/assets/17010094/23034757/c0ec45de-f474-11e6-9a04-3bca94b9c757.png)
Pyramid 1
![image](https://cloud.githubusercontent.com/assets/17010094/23034619/540fb55e-f474-11e6-8af7-2625b6d38212.png)

- Any related issues:
cc: @ayumi

**Comment by diracdeltas** [comment]
we took out favicon on Dec 28 because it was kind of big, but not too big, so we could add it back.

**Comment by Reardon7** [comment]
Just installed today.  I have the same problem.    I really miss my favicons!

**Comment by srirambv** [comment]
@Reardon7  Is the favicons settings set on both the machines which are synced?

**Comment by Reardon7** [comment]
Yes.  Using Windows 10.  Installed Brave and elected to import bookmarks from Chrome.  Bookmarks were imported showing long hyperlink text instead of the favicon.

It would appear to me that a convenient solution would be for the browser to always have a background task run once after each startup to go out and refresh favicon's.  That would not only solve the import of bookmarks issue, it would update changed favicon's.  Obviously, this should be a low priority task, but it is a reasonable task.

**Comment by Reardon7** [comment]
I might add, that all my Chrome bookmarks were edited to hide text and only show the favicon.  Ideally, Brave would have noticed this and shown only the favicon's when importing my bookmarks.

**Comment by diracdeltas** [comment]
> Installed Brave and elected to import bookmarks from Chrome. Bookmarks were imported showing long hyperlink text instead of the favicon.

@Reardon7 this sounds like a problem with bookmark import, not the sync feature (which is what this ticket is for)
