### ISSUE TITLE
make more links HTTPS

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7297]
ex: https://dksfoto.smugmug.com/ for the background image link supports HTTPS

**Comment by diracdeltas** [comment]
also some other HTTP urls that should be fixed

**Comment by srirambv** [comment]
Only working for PhotoSerge not on Darrell Sano's page
![7298](https://cloud.githubusercontent.com/assets/17010094/23359539/8f90b214-fcde-11e6-996d-642fb5c28679.gif)
