### ISSUE TITLE
Generate markdown inside docs/appActions.md from actions/appActions JSDoc

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#73]
Generate markdown inside docs/appActions.md from actions/appActions JSDoc.
Adding an npm command for this called "docs" I think would be good.

**Comment by bbondy** [comment]
Before we close this, was wondering if you could also do an equivalent thing for js/actions/windowActions.js  and also if we can tie this into the "pre-commit" section of the package.json file.

**Comment by serv** [comment]
@bbondy Check out the new PR above.

**Comment by bbondy** [comment]
:+1: closing this since it's merged now.
