### ISSUE TITLE
Tabs display wrong after exiting HTML5 fullscreen

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7301]
## Test plan

https://github.com/brave/browser-laptop/pull/10691#issue-253338559

----

My wife found this one...

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
When exiting html5 video full screen, tabs display wrong, see screenshot.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (probably other OS as well)

- Brave Version (revision SHA):
013.4 release

- Steps to reproduce:
    1. Go to youtube.com and play a video
    2. Click the full screen button
    3. Click escape to exit full screen
    
- Actual result:
All tabs will display wrong with a favicon centered and no text
After hovering they will display ok again

- Expected result:
Tabs should display correctly before and after the full screen event.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, but the regression was reproduced with last release.

- Can this issue be consistently reproduced?
yes

- Screenshot if needed:
<img width="449" alt="screenshot 2017-02-16 23 08 45" src="https://cloud.githubusercontent.com/assets/831718/23052207/896eed22-f49d-11e6-8fdd-cd6e00d3b29c.png">

**Comment by NejcZdovc** [comment]
If you hover over them, they render correctly. Even if you move the mouse out later they stay in the correct format.

**Comment by cezaraugusto** [comment]
re-opening after report from @BrendanEich. not always reproducible but definitely happens after some trials. Should be fixed by intersection observer api for tabs (tracked in #10509)

**Comment by cezaraugusto** [comment]
pushed to 0.20.x to match #10509
