### ISSUE TITLE
Title in tab is not centered

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7304]
## Test plan
https://github.com/brave/browser-laptop/pull/7316#issue-208752821
<hr>

- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Title is not centered in the tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOs
- Brave Version (revision SHA):
c7f3cbd
- Steps to reproduce:
    1. open new tab
    2. go to this link https://github.com/vadimdemedes/trevor
    
- Actual result:
![image](https://cloud.githubusercontent.com/assets/9574457/23056945/1d39ea66-f4ee-11e6-9123-4b1ccacfce6a.png)

- Expected result:
Title of GitHub should be in the same line as brave tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by cezaraugusto** [comment]
🚦:bug:
