### ISSUE TITLE
[Intermittent Issue] Bookmarks added before initial sync are not always copied over to pyramid 1

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7305]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Previously bookmarked items are not synced when sync is disabled and enabled in either pyramid 0 or pyramid 1[Intermittent Issue]

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Add few bookmarks on pyramid 0
    2. Enable syn after the bookmarks are added
    3. Enable sync in pyramid 1 and sync with pyramid 0
    4. Bookmarks are not syncd on pyramid 1
    5. Disable and re-enable sync on pyramid 0, doesn't loads bookmarks on pyramid 1
    6. Disable and re-enable sync on pyramid 1, still doesn't loads bookmarks on pyramid 1

- Actual result:
Bookmarks added before initial sync are not always copied over to pyramid 1

- Expected result:
All bookmarks must be synced irrespective of when it is added

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
No. Intermittent issue. Was able to verify once on a clean profile of both pyramid 0 & 1

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @diracdeltas @ayumi

**Comment by diracdeltas** [comment]
I have seen this too. As mentioned in the testers channel, I wonder if we should just not sync old bookmarks on init for 0.13.5, given that they can be exported/imported manually.

**Comment by diracdeltas** [comment]
may be addressed by https://github.com/brave/browser-laptop/issues/7308

**Comment by diracdeltas** [comment]
could you please try again on master?

**Comment by srirambv** [comment]
Working as expected

**Comment by diracdeltas** [comment]
Closing since it was probably addressed by https://github.com/brave/browser-laptop/pull/7309
