### ISSUE TITLE
Menu on macOS is unusable during sync

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7307]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When sync is happening, the menu will rebuild itself (since new items are being added).  Under the hood, it's destroying and re-creating the menu.  This is 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.5 preview 1

- Steps to reproduce:
    1. Be part of a sync group
    2. Have someone entries (one every few seconds)
    3. Try to use the menu; you'll notice you can click then the menu auto closes itself
    
- Actual result:
Menu closes itself often. You can click again, see the new items, then if another item comes in, it'll close itself.

- Expected result:
Menu should not close itself; it should at least show what was there 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
no - 0.13.5 preview 1

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
probably will be addressed by https://github.com/brave/browser-laptop/issues/7308

**Comment by alexwykoff** [comment]
I don't think we've entirely cracked the nut on this one.  I still get a lockup when joining the 'forsaken...' sync group.

[2017-03-03 01-03-01.mp4.zip](https://github.com/brave/browser-laptop/files/816021/2017-03-03.01-03-01.mp4.zip)
