### ISSUE TITLE
remember password showing on all tabs

### ISSUE THREAD

**Issue by dividinglimits** [brave/browser-laptop#7310]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
1) Navigate to any site with user login credentials (tested with amazon / netflix)
2) Open a separate window (not tab, new instance)
3) Enter login credentials and click the "sign in" button.
4) Notice on the current window -- as well as the not in focus one -- has a drop down asking if you (as the user) would like to remember the credentials (yes, no, never options). 

- Brave Version (revision SHA):
Brave	0.13.4
rev	71d8ffc
Muon	2.56.4
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	6.3.9600
os.arch	x64

- Steps to reproduce:
    1. see above
    2.
    3.
    
- Actual result:
see above

- Expected result:
only show the query on the currently in focus window.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![double-remember-pw](https://cloud.githubusercontent.com/assets/3688829/23089815/292e012a-f55e-11e6-8e5d-a77ffd8bea27.gif)

- Any related issues:

**Comment by kenorb** [comment]
Same here:

![screen shot 2017-08-15 at 13 30 53](https://user-images.githubusercontent.com/266306/29316007-161a4692-81be-11e7-967f-b0d85099bf4b.png)
 
Brave: 0.18.22 
rev: d850e287ace296e2c62e28ba2979cf172e41cc45 
Muon: 4.3.9 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64

**Comment by luixxiul** [comment]
@kenorb that issue has been reported on https://github.com/brave/browser-laptop/issues/10200

**Comment by bsclifton** [comment]
+1 from @srirambv via https://github.com/brave/browser-laptop/issues/10200

**Comment by bsclifton** [comment]
@alexwykoff mentioned this regressed with 0.13.0
