### ISSUE TITLE
can't load google account login page

### ISSUE THREAD

**Issue by Bloygan** [brave/browser-laptop#7311]
- Did you search for similar issues before submitting this one?
i have searched for 2 days and found nothing.
- Describe the issue you encountered:
When i try to launch the login page of youtube, gmail (all google websites) i have a black screen with a "pixel art" in the middle.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10, Toshiba laptop
- Brave Version (revision SHA):
0.13.4
- Steps to reproduce:
    1.go to youtube main page
    2.then click on connect
    
    
- Actual result:
I have a black tab with a litlle pixelled face in the middle
- Expected result:
The page loads normally
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
This problem exist also on google Chrome and Opera but not on Mozilla, Microsoft Edge and Internet Explorer
- Is this an issue in the currently released version?
Yes the issue is in currently released version
- Can this issue be consistently reproduced?
Yes, Every time i try to connect except one time i succeed but i couldn't see any live video.
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/25862836/23092820/9756455c-f5d3-11e6-8721-6c3a29a5d20a.png)

- Any related issues:

**Comment by luixxiul** [comment]
CC @bridiver

**Comment by Bloygan** [comment]
So you can't help me for the moment? :(

**Comment by luixxiul** [comment]
@Bloygan I myself cannot understand the issue. Either @bridiver, @bbondy, @bsclifton or @darkdh would investigate the issue instead of me.

**Comment by Bloygan** [comment]
Thank you.

**Comment by bridiver** [comment]
if you have the same problem on Chrome and Opera I would suggest reporting the issue to https://bugs.chromium.org 
All 3 of the browsers are Chromium based and I'm not sure what would affect all of them

**Comment by Bloygan** [comment]
The issue has been sent, waiting for answers.

**Comment by bsclifton** [comment]
Awesome, thanks for taking the time to do that, @Bloygan! Let us know how it goes 😄

**Comment by bridiver** [comment]
@Bloygan do you have a link for the chromium issue?

**Comment by bridiver** [comment]
I wonder if this is related to https://github.com/brave/browser-android-tabs/issues/152 
In android it affects all chromium based browsers except Chrome. Maybe it's a local cert db issue?

**Comment by Bloygan** [comment]
https://bugs.chromium.org/p/monorail/issues/detail?id=2273&can=2&start=0&num=100&q=&colspec=ID%20Type%20Status/Closed%20Priority%20Milestone%20EstDays%20Owner%20Summary&groupby=&sort=

**Comment by Bloygan** [comment]
Sorry i may bother but what i must do with all these files you redirected me,https://github.com/brave/browser-android-tabs/commit/5808e74a06595a9f82f1e38a1b177983b39a53f6   ?

**Comment by bridiver** [comment]
@Bloygan that is just for our reference because this looks like it might be similar to an issue we are seeing on android

**Comment by Bloygan** [comment]
ok

**Comment by Bloygan** [comment]
On the monrail, i had a comment saying: not a monorail issue.

**Comment by bridiver** [comment]
yep, looks like you accidentally posted it in issues for Monorail instead of Chrome. 
https://bugs.chromium.org/p/chromium/issues/list is the tracker for Chrome/Chromium issues

**Comment by Bloygan** [comment]
The issue has been sent, on the right website (i think) here is the link: https://bugs.chromium.org/p/chromium/issues/detail?id=695925
