### ISSUE TITLE
Title is cut in tab

### ISSUE THREAD

**Issue by daquinons** [brave/browser-laptop#7312]
## Test plan
https://github.com/brave/browser-laptop/pull/7316#issue-208752821
<hr>

- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: When you open a new tab, the title in tab is half cut because it's not correctly placed.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux, Elementary OS Loki (Based on Ubuntu 16.04 LTS)

- Brave Version (revision SHA): 71d8ffc (0.13.4)

- Steps to reproduce:
    1. Open tab
    
- Actual result:
![](https://i.imgur.com/pvwnTDv.png)

- Expected result:
![](https://i.imgur.com/1rCH5dt.png)

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Any related issues: https://github.com/brave/browser-laptop/issues/7304

**Comment by luixxiul** [comment]
Maybe it is because that the line-height and the font-size is not properly set. @cezaraugusto can you confirm the issue on a linux distro, which has different font sets than Windows/macOS?

**Comment by cezaraugusto** [comment]
Confirmed, thanks for reporting. 

@luixxiul yes, different OSes render fonts/line-height differently. I have a quick fix.

**Comment by luixxiul** [comment]
@cezaraugusto Sweet! I set the milestone. Please reset it if you postpone it to the next one, thanks.

**Comment by dividinglimits** [comment]
@cezaraugusto I am guessing the line height has an explicit unit with it, correct? if so, just remove that as its already relative to the font-size.

**Comment by cezaraugusto** [comment]
@dividinglimits actually issue was that it didn't have one but height was declared differently for each OS. Fix was to add an unitless line-height as default and removing specific heights.
