### ISSUE TITLE
Object expected in chrome.storage.sync.get callback

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7314]
When calling `chrome.storage.sync.get`, the user passes along a callback function. When this function is executed, the first argument is expected to be an object. Presently, it is `undefined`. This causes errors to be thrown when attempting to access any property.

As an example, the following is from the Mercury extension:

```js
chrome.storage.sync.get(null, function (items) {
    myObj = items;
    _this2.setState({
        theme: myObj.mercuryTheme || 'light',
        textSize: myObj.mercuryTextSize || 'medium',
        typography: myObj.mercuryTypography || 'serif',
        settingsLoaded: true,
        showApproveTos: myObj.mercuryApproveTos !== undefined ? myObj.mercuryApproveTos : true
    });
    chrome.runtime.sendMessage({ type: 'settingsLoaded' });
});
```

During the attempt to _setState_, the call to `myObj.mercuryTheme` will throw.

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by bridiver** [comment]
didn't we talk about making sync storage just point to regular storage?

**Comment by jonathansampson** [comment]
@bridiver We had indeed floated that idea in the past :) Feasibility?

**Comment by bridiver** [comment]
doing it right now

**Comment by bridiver** [comment]
it will actually point to a separate local storage instance

**Comment by bridiver** [comment]
fixed https://github.com/brave/muon/commit/6c89cedc6deff8317ed15be8c0853defaa5ff480

**Comment by bsclifton** [comment]
marked as no QA needed; extension compatibility tracked with https://github.com/brave/browser-laptop/projects/1
