### ISSUE TITLE
Never ending spinner on klack.de

### ISSUE THREAD

**Issue by beingalink** [brave/browser-laptop#732]
The tab spinner doesn't stop its animation on <http://www.klack.de> as if loading never ends.

**Comment by bridiver** [comment]
Thanks for the bug report! I'm not able to replicate this in master, which brave version/os are you using?

**Comment by beingalink** [comment]
Oh, you're right. It doesn't happen on the front page. Try <http://www.klack.de/fernsehprogramm/2015-im-tv/0/-1/free.html>.

I'm on Brave 0.7.14 on OS X 10.11.4beta.

**Comment by bridiver** [comment]
pretty sure this is related to #759

**Comment by beingalink** [comment]
While this seemed fixed, it is back with today's version of brave 0.7.16.

**Comment by bridiver** [comment]
It turns out there are quite a few edge cases here. I'll see if I can create a test for this one so we don't lose it again.

**Comment by luixxiul** [comment]
Does this still persists on the latest version?

**Comment by beingalink** [comment]
It's fine now. Thanks for fixing it!
