### ISSUE TITLE
LastPass doesn't store 2FA authentication across sessions

### ISSUE THREAD

**Issue by edjw** [brave/browser-laptop#7324]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Using Lastpass with Two Factor Authentication, I have to re-authenticate LastPass on Brave every time I re-open Brave even when I have previously ticked "Trust this computer for 30 days."
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.3
- Brave Version (revision SHA):
	71d8ffc
- Steps to reproduce:
    1. Enable Lastpass on Brave with an account with Two Factor Authentication turned on
    2. Log into LastPass. Authenticate using 2FA
    3. Close Brave
    4. Re-open Brave
    
- Actual result:
You have to re-authenticate LastPass on Brave every time you open Brave

- Expected result:
You only have to re-authenticate on Brave once every 30 days

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Will you make sure you does not enable the option on about:preference#security to clear data when you close the browser?

**Comment by edjw** [comment]
I'm not clearing any of the data when I close the browser

**Comment by edjw** [comment]
On further use, I've found that if I just close the tab asking me to do 2FA, the LastPass icon on the top-right shows the yellow "couldn't log in" error. But then, as long as I just enter my master password as usual, the LastPass vault is open and available.

**Comment by AnthoniG** [comment]
Just to add that I am also experiencing this problem.
Entered my master password and ticked the Remember Master Password.
Close the browser, re-open Lastpass once again asks for me to re-login.

**Comment by srirambv** [comment]
+1 from community community.brave.com/t/lastpass-authentication-issue/2072

**Comment by Struisvogel93** [comment]
I'm also getting this problem using the latest version of Brave, on Windows 10.

It keeps asking me for 2FA, when I do this the tab won't close and it will not complete. When I restart Brave, it will re-prompt the 2FA.

Lastpass doesn't seem to be working very well with Brave at this moment :(

**Comment by TheLucasMoore** [comment]
Hey, I am seeing the same issue as @Struisvogel93. I can open a new issue, since it's distinct.

When using 2FA with Lastpass, it does not complete at all. I am on Mac OS Sierra.

**Comment by j0hnm4n** [comment]
This was resolved for me after setting shields down on both lastpass.com and www.lastpass.com (which I incidentally seem to remember having to do with NoScript back in the day).  Noticed a 2 count on the Brave extension icon when logging into lastpass.com.

**Comment by brad2014** [comment]
See also this incompatibility between LastPass and HTTPS Everywhere (which is disabled when shields are down, and can be disabled alone in Brave settings).

https://github.com/EFForg/https-everywhere/issues/11853
