### ISSUE TITLE
Brave doesn't call TorrentViewer for Democracy Now torrent file

### ISSUE THREAD

**Issue by jpokeefe** [brave/browser-laptop#7325]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

Tried to download torrent file of a Democracy Now show.  Instead of calling the TorrentViewer, it prompted me to download the torrent file.  I can download the torrent via BitTorrent, so the file works.  You can find the url at:

https://ewheel.democracynow.org/dn2017-0217.mp4.torrent

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS 10.12.3

- Brave Version (revision SHA):

Brave	0.13.4
rev	71d8ffc
Muon	2.56.4
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	darwin
os.release	16.4.0
os.arch	x64

- Steps to reproduce:
    1.  Go to https://www.democracynow.org/2017/2/17/stream
    2.  Click on the MPEG-4 Video Torrent link
    
- Actual result:

Get Save As dialog

- Expected result:

See torrent file in Torrent Viewer

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes. I am using a fresh profile.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
torrent link files are yet to be supported: #6671

**Comment by jpokeefe** [comment]
Thanks. Closing as a duplicate of #6671.
