### ISSUE TITLE
Printing stopped working

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7326]
**Describe the issue you encountered:**
https://community.brave.com/t/printing-after-update/1316?u=suguru

> After Brave update, printing no longer works. Says "Spooling" and printer warms up, but never starts printing.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Several reports are following: https://community.brave.com/t/printing-after-update/1316/4?u=suguru

**Comment by wes-baker** [comment]
After Brave update, printing no longer works. Says "Spooling" and printer never starts printing.

Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 Home, Version: 1607 OS Build: 14393.693

Brave Version (revision SHA):  0.13.4  rev. 71d8ffc

Printer: HP OfficeJetPro 8600

Steps to reproduce:
1.  I either use CTRL+P or a Print icon on a webpage to attempt to print the page.
2. The printer fails to respond.  When I check the status of the job, it reports the job is "Spooling," but the page never prints.
3. I have tried this with my printer both through the USB connection and WiFi connection.  Same result.

Actual result: Nothing prints

Expected result: Page should print

Will the steps above reproduce in a fresh profile? If not what other info can be added?  Don't know

Is this an issue in the currently released version? As far as I know.

Can this issue be consistently reproduced? Yes, it happens every time.  I have had to go back to Chrome for any webpages I want to print.

Extra QA steps:
1.
2.
3.

Screenshot if needed:

Any related issues:

**Comment by pennyjw** [comment]
This is the first version of Brave I have used.

**Printing to Adobe PDF** 
Printing to a PDF file doesn't work. Pop-up dialogue says "Creating Adobe PDF" but doesn't go beyond first few bars of PDF progress.
![image](https://cloud.githubusercontent.com/assets/13402741/23361874/f22bc824-fd46-11e6-91d6-e31a250dcedd.png)

Platform : Windows 7 Enterprise, service pack 1, 64-bit 
**Brave Version information screen:**
 Brave: 0.13.4 
rev: 71d8ffc7278a90b22b8617d37880787c1781e694 
Muon: 2.56.4 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.1.7601 
os.arch: x64

**Printer: Adobe PDF converter**
Postscript printer driver version 5.2 (6.1.7601.17514)
PPD filename -ADPDF9.PPD, PPD version 1.1

**Steps to reproduce:**
On tab where I want to print, select 'Print' from More (...) menu. 
Adobe PDF converter is already set as default printer. 
Adobe PDF converter asks for file name and location for PDF to be created.
Little PDF converter dialog box opens and progress bar gets stuck at three grommets.

Expected result: Page should save as PDF file.

Will the steps above reproduce in a fresh profile? If not what other info can be added? I don't know what this question means.

Is this an issue in the currently released version? Yes.

Can this issue be consistently reproduced? Yes, Adobe PDF convertor has never completed (tried about 6 times).

**Comment by bsclifton** [comment]
@darkdh could this possibly be fixed with https://github.com/brave/muon/commit/fa3fec8b3273f84232201ce337dfad1ee13798ea and/or https://github.com/brave/muon/commit/8320fcae37e9436d8148076f07002bf8d7e9078e?

**Comment by darkdh** [comment]
But these two are already in 0.13.4. They are used for 56 upgrade.

**Comment by bsclifton** [comment]
@darkdh ah ok thanks!

**Comment by SilverPuppy** [comment]
Experiencing the same issue when printing from PDF.js in Brave on Windows 7. Happened twice just now.

**Comment by srirambv** [comment]
Working on RC3 of 0.13.5

**Comment by SilverPuppy** [comment]
Working correctly as of update yesterday, Windows 7.

**Comment by LukasGI** [comment]
Same issue as reported by wes-baker on 25 Feb 2017.
Brave Version and Platform Info: 
Brave | 0.21.24
V8 | 6.5.254.36
rev | 19c78a1
Muon | 4.9.3
OS Release | 6.1.7601
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.162
Printers: CutePDF Writer, Microsoft XPS Document Writer, Xerox WS 7120

**Comment by NejcZdovc** [comment]
@LukasGI this is tracked here https://github.com/brave/browser-laptop/issues/13546 and will be fixed in the next version. Thank you for your report
