### ISSUE TITLE
Not switching to tab when left-clicking

### ISSUE THREAD

**Issue by valtih1978** [brave/browser-laptop#7329]
- similar: https://github.com/brave/browser-laptop/issues/4672

- Clicking a tab should switch to it but it does not.

- Win7:

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Click inactive tab
    2.
    3.
    
- Actual result: Nothing happens

- Expected result: Clicked tab should activate

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- it is an issue in the currently released version

- it can be consistently reproduced

This looks like inteneded "feature" because click-switch succeeds if I click the tab with 1-second delay. Please remove it. I do not want to play games here.

**Comment by Jacalz** [comment]
It works to click on tabs and it always has...

**Comment by valtih1978** [comment]
No need to wait for 1 sec in Win 10? I wonder how does Brave immediately shows me shaded tab as soon as I hover over the tab but clicking needs the delay from user to activate the tab. This is weird.

**Comment by valtih1978** [comment]
Ok, I investigated it. It does switch, but with a delay. No delay from user is needed. It just loses some keystrokes between I click another tab and its activation takes the effect. That is the problem.

**Comment by luixxiul** [comment]
Inactive tab at first needs to be loaded via Internet. I think that is the common behavior between browsers.

If you feel slowness, please disable "Show tab previews on hover" from Edit -> Preferences ->Tabs.

**Comment by valtih1978** [comment]
The curious thing is that hover is instant. It is also curious why one needs to reload just inactive tab from the Internet? Just to make clear, I was experiencing some keystrokes lost and switch requests ignored but cannot reproduce the latter. I think we can close the issue until I make it clear.

**Comment by bsclifton** [comment]
I believe this problem was introduced recently- I know @BrendanEich has mentioned it before.  We haven't found a definitive root cause yet, but are working on fixing it
