### ISSUE TITLE
Wacom pen and links

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7331]
**Describe the issue you encountered:**
https://community.brave.com/t/wacom-pen-and-links/492?u=suguru
> I'm using a wacom tablet and clicking links with the pen is (almost) impossible. 
>
> I think the problem has to do with difference in position between mouse down and mouse up. It's hard to stay at exactly the same pixel when tapping with the pen and I think that adding a few pixels of threshold would solve the problem.
>
> I've experienced the problem with other browsers based on chromium, but not chrome or other applications.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Possibly related electron issue: https://github.com/electron/electron/issues/7815#issuecomment-281153342
