### ISSUE TITLE
"Select the last viewed tab" setting not working with pinned tabs

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#7332]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
The setting "Select the last viewed tab" only redirects you to the latest viewed tab (See extra info) and not to a pined tab. https://community.brave.com/t/tab-settings-not-working/1287/9
- Platform (Win7, 8, 10? macOS? Linux distro?):
Found it reproducible on Windows 10 Home and Pro (Will test on windows 7 Professional tomorrow on a fresh profile) I also found that it works on MacOS but there it seemed to take me to the right most tab.
- Brave Version (revision SHA):
0.13.4
- Steps to reproduce:
    1. Open 3 tabs with different websites
    2. Select tab 1 and pin it
    3. Switch to tab 3 and remove it
    4. Now you are on the last viewed tab that is not pinned
    
- Actual result:
You are on the last tab you viewed that is not a pinned tab
- Expected result:
If the pinned tab was your last viewed tab then it should put you at that tab when you close tab 3
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
We will see soon
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra info:
 Seems like different people has different results of wich tab they get after closing tab 3.
On my pc with Windows 10 Pro I get to the last viewed non pinned tab but on my mac I get to the right most tab (also not pinned) and the guy that originaly reported this on https://community.brave.com was on Windows 10 Home and he got to the right most tab sometimes and sometimes to the last viewed non pinned tab. We will see after more testing.

- Screenshot if needed:
<img src="https://cdn-standard2.discourse.org/uploads/brave/original/1X/4276d0ebc6c993f2e787d0f5e3f4b37f78cf1fb2.PNG"/>

**Comment by NejcZdovc** [comment]
@bradleyrichter Should we allow focus on pinned tabs?

**Comment by bradleyrichter** [comment]
@NejcZdovc generally, yes but there may be side effects. I agree with the use case above. It should work as expected. Especially since those tabs could have been children of the pinned tab anyway. 

Pinned tabs could potentially earn equal rights but with close functions disabled. 

(but we need to be careful to break logic that is otherwise working well after many fixed bugs.)

**Comment by Jacalz** [comment]
@bradleyrichter The fact that there is some strange behavior with wich tab you go to after closing the tab certainly needs to be fixed 😉

**Comment by Jacalz** [comment]
This works in 0.15.310 so closing...
