### ISSUE TITLE
A malicious website takes over Brave

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#7333]
Isn't this guy's problem quite a significant security concern?
https://community.brave.com/t/completely-stuck-on-a-malicious-website/1331

**Comment by bsclifton** [comment]
@CliqueBait thanks for the report 😄   This is basically a duplicate of https://github.com/brave/browser-laptop/issues/3794

I have a fix coming up soon with https://github.com/brave/browser-laptop/pull/7107
