### ISSUE TITLE
Torrent don't start downloading 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7334]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Torrent don't start downloading 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb
- Steps to reproduce:
    1. Do a clean install of 0.13.5 Preview 1
    2. Open any magnet torrent link from https://codepen.io/ferrossity/full/qaezaB/
    3. Shows only `Loading the torrent file list...` but download never starts
No Console errors 
    
- Actual result:
Download doesn't start

- Expected result:
Should start downloading/stream

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23163452/60ab7ef6-f82a-11e6-8539-c446e26aa69d.png)

- Any related issues:
cc: @feross

**Comment by feross** [comment]
This wasn't actually an issue with Brave or WebTorrent. The magnet links on the page were missing working tracker servers and DHT lookup couldn't connect to any peers . Fixed up the links and the issue is gone.
