### ISSUE TITLE
Stop page load button doesn't stop loading the page, Esc does

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7340]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported by user in community https://community.brave.com/t/brave-loading-error/1341
Stop page load button doesn't stop loading the page, Esc does

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Open any page which has lot of content in it 
    2. Click on the stop loading button in URL bar, doesn't stop loading the page
    3. Reload the same page and press <kbd> Esc </kbd>  immediately, page load stops
    
- Actual result:
Clicking on stop loading button doesn't stop the page load

- Expected result:
Should stop the page load when stop loading button is clicked, functinality should be same as pressing <kbd>Esc</kbd> button

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes same on 0.13.4

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![stopload](https://cloud.githubusercontent.com/assets/17010094/23171561/b565611c-f84a-11e6-96e9-b479322249d4.gif)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
@bbondy do you remember why the IPC calls were removed with this commit?
https://github.com/brave/browser-laptop/commit/4507f5e9ecc6df1500ef07c5740f2251ee4ae900

**Comment by bsclifton** [comment]
Hitting escape works great- the [inputHandler script](https://github.com/brave/browser-laptop/blob/master/app/extensions/brave/content/scripts/inputHandler.js#L139) will send the renderer a `stop-load` event. When the stop button is pushed, nothing is sent... in fact, it causes the frame to load again
