### ISSUE TITLE
Able to setup sync with a deleted profile

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7341]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sync profile is set when an old sync code is used

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Setup sync profile on device 1(pyramid 0)
    2. Copy the secret code generated for that profile
    3. Delete the user profile on device 1(pyramid 0)
    4. On device 2(pyramid 1) setup sync using `I have an existing sync code`
    5. Enter the secret code copied in step 2
    6. Sync profile is setup but nothing happens as pyramid 0 is deleted
    
- Actual result:
Able to sync to a deleted profile

- Expected result:
Should not be allowed to sync to a deleted profile

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @ayumi @diracdeltas

**Comment by diracdeltas** [comment]
This is expected behavior. You have to explicitly click a 'delete this sync profile' button (not yet implemented) to delete the profile.

**Comment by diracdeltas** [comment]
closing in favor of https://github.com/brave/sync/issues/51
