### ISSUE TITLE
when the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#7344]
## Test plan
- run the usual ledger tests to see if a wallet is created, a contribution is made, etc.

## Original issue description
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered: _when the browser dives into an anonize2 crypto operation, it is unresponsive for a second or so_

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version (revision SHA): all

- Steps to reproduce:
    1. turn on the ledger, wait for the contribution period to complete and for voting to begin
    2. when a vote occurs, some seriously crypto-computation will occur, during which time the browser is unresponsive.
    
- Actual result: browser briefly "locks up"

- Expected result: browser shouldn't do that

- Will the steps above reproduce in a fresh profile? see above

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none

- Screenshot if needed: n/a

- Any related issues: n/a

**Comment by bsclifton** [comment]
moving to 0.14.1

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/browser-laptop/commit/91b8ebf17443a042e82666b121ca9b1755d1c6e1 because of a Windows only bug seen with https://github.com/brave/browser-laptop/issues/8304

Reopening and moving to 0.14.3 for reattempt

**Comment by mrose17** [comment]
@bridiver - apparently the v8 workers threads is okay on mac and linux, but not windows...

**Comment by bridiver** [comment]
@mrose17 what is the issue? Is there a bug filed for it?

**Comment by bsclifton** [comment]
@bridiver you can find more info in https://github.com/brave/browser-laptop/issues/8304 (including the errors being logged)

**Comment by bsclifton** [comment]
We should be able to try this again after attempting the fix recommended by @bridiver here:
https://github.com/brave/browser-laptop/issues/8304#issuecomment-296455730

**Comment by bsclifton** [comment]
Error is happening again. This is Windows only and was reported with https://github.com/brave/browser-laptop/issues/8632:
```
! >>> worker error: Cannot find module 'node-anonize2-relic-emscripten\./anonize2-jumbo.js'
ModuleNotFoundError: Cannot find module 'node-anonize2-relic-emscripten\./anonize2-jumbo.js'
    at requireProxy (extensions::muon/module_system/commonjs:61:15)
    at fn (extensions::node-anonize2-relic-emscripten:3:16)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::node-anonize2-relic-emscripten:325:43
    at requireProxy (extensions::muon/module_system/commonjs:64:22)
    at fn (extensions::ledger-client/worker.js:4:15)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::ledger-client/worker.js:46:43
! >>> worker error: Cannot read property 'binding' of undefined
TypeError: Cannot read property 'binding' of undefined
    at requireProxy (extensions::muon/module_system/commonjs:65:20)
    at fn (extensions::ledger-client/worker.js:4:15)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::ledger-client/worker.js:46:43
```

**Comment by bsclifton** [comment]
The error does NOT happen when running from source on Windows. It only seems to happen with the packaged build.  Until we resolve this, I'll revert the changes

**Comment by bsclifton** [comment]
Reverted with https://github.com/brave/browser-laptop/commit/db26cac63126f3f7be4a171ff892fce41aeb41e9; reopening

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/muon/commit/14c0cd7b507422e5d988dca486c7a6918183fa1d

But leaving open until we have new muon builds and we revert the other revert commit.

**Comment by cezaraugusto** [comment]
reverted again in f1d79db5697cabe971a9a282f4b55463b53235bd after #8884. Reopening

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/9221
