### ISSUE TITLE
update ledger settings UI area to match 1.0 features/changes

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7348]
## Test plan
UI should match this mock up (see detailed notes below)

![image](https://cloud.githubusercontent.com/assets/13509546/23181144/ac7bf66e-f828-11e6-8cd2-fccb1ae362fb.png)

**item 1:** convert advanced settings text button into an icon button. Convert Payments History link into icon button in same location.

**item 2:** move Add funds... button to column 3.

**Item 3:** Break out and add "Last contribution" string to column 1, row 2.

**Item 4:** Break out and add "Next contribution" string to column 2, row 2.

**Item 5:** Add style for non-editable edit-box form element.

**Comment by NejcZdovc** [comment]
@bradleyrichter please add all icons that are needed

- settings
- history
- pin
- delete
- twitter

**Comment by luixxiul** [comment]
@bradleyrichter Should the color of the icon in the left column be green?

**Comment by bradleyrichter** [comment]
@luixxiul Currently the SVGs are all orange for selected state. Do you think we should do unique colors? (the green was an experiment that stayed in the mockup...)

**Comment by luixxiul** [comment]
I'm not quite sure but for me all orange looks too much monotone. Still if we would do unique colors, maybe theme colors needs picking up for each item (general/tab/search/...) and I think we don't want to do that.

**Comment by NejcZdovc** [comment]
SVG icons

[ledger_icons.zip](https://github.com/brave/browser-laptop/files/808944/ledger_icons.zip)
