### ISSUE TITLE
0.13.5 preview  builds size is more compared to normal builds

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7352]
0.13.5 preview 2 is almost 30Mb more than usual. 
![image](https://cloud.githubusercontent.com/assets/17010094/23215410/2e2ded8e-f90a-11e6-9200-a1c5e700b870.png)

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bsclifton** [comment]
duplicate of https://github.com/brave/browser-laptop/issues/7896
