### ISSUE TITLE
Page title incorrectly applied to active/previewed tab rather than responsible tab

### ISSUE THREAD

**Issue by Instinct64** [brave/browser-laptop#7354]
- Did you search for similar issues before submitting this one?
**Yes**

- Describe the issue you encountered:
When hoving on an alternate tab while loading a page, the title of the loading page is applied incorrectly to the previewed tab, rather than the tab loading the page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 64bit

- Brave Version (revision SHA):
Brave	0.13.4
rev	71d8ffc

- Steps to reproduce:
    1. Launch Brave
    2. Go to a website, e.g. google.com
    3. Open a new tab, enter a valid URL e.g. duckduckgo.com, do not press enter yet
    4. Press "Enter" and then immediately hover on your previous tab
    5. Observe the issue, page title of duckduckgo.com has been applied to google.com tab.
    
- Actual result:
Page title is applied to previewed/active tab when loading a page in another tab.

- Expected result:
Page title should be applied to the tab responsible for loading a page.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, it should.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes, 100%.

- Any related issues:
Perhaps a related issue: #2951

**Comment by Instinct64** [comment]
Related to issue: #2844

**Comment by srirambv** [comment]
Unable to reproduce the issue. Could you record a gif of this and update it in the issue?

**Comment by Instinct64** [comment]
@srirambv I can't reproduce the issue now either. I've tried a few cases to try and replicate, so no sure exactly what triggered this behaviour.
