### ISSUE TITLE
White Screen Crash on Win 8

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7355]
Reported by community user 
https://community.brave.com/t/white-screen-crash-on-win-8/1373

>The Completely Blank Window (reported on a Mac after update) also happens intermittently on Win 8, not Win 8 Pro.
>During a EXCESSIVE Brave resource response time period I used Task Manager on Win 8 Pro to dismiss (kill) some of the 14 BRAVE background processes and immediately got the Brave Browser WhiteOut or White or Blank screen.

**Comment by Brax-Me** [comment]
Here are the dump files

**Comment by Brax-Me** [comment]
Yowza, that’s a big file.  Choose Files Try again with a file smaller than 10MB?

I can share them on Brax.Me

**Comment by Brax-Me** [comment]
https://brax.me/room/braveonbraxme

487.92 MB in Room Files
E2eNerd @e2eWireless

**Comment by srirambv** [comment]
cc: @bridiver @bsclifton

**Comment by bridiver** [comment]
what version of Brave?

**Comment by Brax-Me** [comment]
13.2 to 13.4  
Was less frequent on HP Laptop Win 8 w/13.0 or 13.1

13.2 had 100% repro with moving link text out of box within Brax (same HP Win 8)

BTW Win 8 Pro on Asus Laptop never (very rarely) had any Brave Browser issues.  
FWIW Brax.Me is best/most secure and stable encrypted product freely available anywhere!

**Comment by Brax-Me** [comment]
See Brax for updated dump file from killing single background process (due to unresponsive Brave Browser State).
