### ISSUE TITLE
Pocket extension on Windows ia32 is always red 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7357]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pocket extension on Windows i32 is always red 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 ia32

- Brave Version (revision SHA):
Brave	0.13.4
rev	71d8ffc

- Steps to reproduce:
    1. Enable Pocket on a clean install of 0.13.5 preview 2
    2. After pocket widget is shown is it is always red
    3. Open any about:pages still shows red
    
- Actual result:
Shows red icon after enabled

- Expected result:
Should not show the red icon, should show red icon only when a page is saved

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
was this fixed with https://github.com/brave/browser-laptop/pull/7437?
cc: @alexwykoff

**Comment by bsclifton** [comment]
@srirambv @alexwykoff can we retest this one? if it's still an issue, maybe we can push to 0.14.3.  Thanks 😄

**Comment by srirambv** [comment]
Its quite the opposite now on ia32. It doesn't show the widget in red even after saving a page. Shows the save message only for the first link saved but not the second one. 
![8087](https://cloud.githubusercontent.com/assets/17010094/24701745/87a031f6-19f3-11e7-9449-39b1c8c198ce.gif)

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
This is expected behavior. We shouldn't show a red pocket.

**Comment by luixxiul** [comment]
I think it is somewhat confusing... since other icons around the pocket one change color based on status. LastPass changes the color into yellow when the extension has a warning notification. Shield button changes its color too.

I don't see the reason to disable color change on Pocket.

**Comment by luixxiul** [comment]
<img width="90" alt="screenshot 2017-05-29 17 14 26" src="https://cloud.githubusercontent.com/assets/3362943/26541847/6ee43210-4492-11e7-9033-14d121eebc87.png"> <img width="91" alt="screenshot 2017-05-29 17 14 48" src="https://cloud.githubusercontent.com/assets/3362943/26541848/6f05286c-4492-11e7-8253-b43c8fe75546.png">

**Comment by bsclifton** [comment]
@luixxiul do you have a way to test in Chrome using a 32 bit Windows VM? I am curious if Chrome has the same issue

**Comment by luixxiul** [comment]
ok I'll give a try.

**Comment by luixxiul** [comment]
The pocket icon seems to have the color based on the status. See: https://github.com/brave/browser-laptop/issues/9157#issuecomment-309399249.

@srirambv would you check the icon again with a fresh profile? if it is confirmed that the bug has been fixed, please re-close the issue. Thanks!

**Comment by srirambv** [comment]
Doesn't seem to be an issue for Windows ia32.  Pocket icon becomes grey when navigated to a unmarked page and shows red when opened 

Closing the issue for now

cc: @luixxiul

**Comment by LaurenWags** [comment]
confirmed pocket icon is not always red on MacOS after pocket is enabled. however, cannot confirm it becomes red due to https://github.com/brave/browser-laptop/issues/9669
