### ISSUE TITLE
Use <SettingTextbox> for the textbox on the dialog of enabling Sync

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#7360]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The Sync enable dialogs prompt for device nickname using `<input />` elements. We would prefer they used SettingText because it's cleaner. We tried to do this in https://github.com/brave/browser-laptop/pull/7164 however it regressed nicknaming of devices

Previously I tried to use a Textbox however I couldn't get the prop ref={} to work so the input didn't work[0]. I gave up and used a standard input.
This branch doesn't seem to set the device name either.
[0] Maybe this: https://facebook.github.io/react/docs/refs-and-the-dom.html

Test Plan:
1. Clear profile
2. Enable sync and name the device
3. Observe terminal for the device name– should not be "browser-laptop"

Also tested by: yarn test -- --grep='"^Sync Panel"'

cc @luixxiul @bsclifton

**Comment by luixxiul** [comment]
Closing in favor of PR #8044
