### ISSUE TITLE
Torrent name is missing once download is started

### ISSUE THREAD

**Issue by feross** [brave/browser-laptop#7362]
## Test plan
1. Click any magnet link from https://codepen.io/ferossity/full/qaezaB/
2. Click "Start Download" to start the torrent
3. Ensure that the torrent title shows up at the top of the page

## Original issue description
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: The name of the torrent shows up when asking the user to confirm whether to start the download, but it doesn't show up after the download has started, which is confusing, especially when coming back to the tab.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 71d8ffc

- Steps to reproduce:
    1. Start WIRED torrent download from https://codepen.io/ferossity/pen/qaezaB
    2. Click "start" 
    3. See that title is missing now
    
- Actual result: Title is missing

- Expected result: Title should show up

- Will the steps above reproduce in a fresh profile? If not what other info can be added? YEs.

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? Yes.

- Screenshot if needed:

Before starting, title shows:

<img width="1275" alt="screen shot 2017-02-23 at 2 21 46 pm" src="https://cloud.githubusercontent.com/assets/121766/23281916/edeb3cd4-f9d3-11e6-9a8b-9185d09727ce.png">

After starting, title is missing:

<img width="1265" alt="screen shot 2017-02-23 at 2 21 53 pm" src="https://cloud.githubusercontent.com/assets/121766/23281920/f03a877e-f9d3-11e6-9e48-a350bc9d17ff.png">

**Comment by bsclifton** [comment]
Moving to 0.14.1

**Comment by srirambv** [comment]
Tab title changes only on mouse over/away similar to #7765. But works.
