### ISSUE TITLE
Suggestion: Give power users a bit more power while not discriminating simple users of course

### ISSUE THREAD

**Issue by CountLesnik** [brave/browser-laptop#7369]
The Brave team seems also like other browser developers today to have no faith in the abilities of their users.

It would be nice if you woud offer us advanced users more power, as we are no children and know how to handle things. Brave is not only developed for simple users in mind.

I suggest you think about the following:

- let us decide when we can update the browser (If an issue appears which can't be fixed that simple we have to endure it over several versions)

- Give us more control like for example a real speed dial page with the options to let us chose our own backgrounds

- Give us optional UI elements (which simple users of course do ot have to use) like a side bar or full status bar (Blink is fast enough to handle such simple features speed-wise)

- give us access to about:flags or about:gpu

That is all for now which i have in mind, the thing is we are no little children - but that is what most developers think about their users. They have no believe in our abilities. I hope Brave team will be different.

Thanks!

**Comment by luixxiul** [comment]
Hi!

Most of the suggestions have been already suggested. Please have a look at these:
https://github.com/brave/browser-laptop/issues/1877#issuecomment-271341198
https://github.com/brave/browser-laptop/issues/5305
https://github.com/brave/browser-laptop/issues/2185
https://github.com/brave/browser-laptop/issues/5208
https://github.com/brave/browser-laptop/issues/328

I couldn't find request for about:flags or about:gpu page.

Also this is the status of extensions which have been requested and already have been implemented:
https://github.com/brave/browser-laptop/projects/1

If you have other suggestions, here are sites you would like to see at first for ones which have been already submitted: https://github.com/brave/browser-laptop/issues?q=is%3Aopen+label%3Asuggestion+sort%3Areactions-%2B1-desc and https://community.brave.com/c/feature-requests.

If you have some nice ideas which have not been suggested yet,  please do not hesitate to post it on https://community.brave.com/c/feature-requests. I'm going to close this issue. Thanks!

**Comment by bsclifton** [comment]
+1 to what @luixxiul said

As a developer on the project, I promise you that we'd love to deliver all these features- I just wish there were more hours in a day 😄   If you (or others reading) would like to help add these features, we're always available to help answer questions
