### ISSUE TITLE
Close icon on tab should not overwrap on the favicon

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7370]
**Describe the issue you encountered:** Close icon on tab should not overwrap on the favicon.

![tabicon](https://cloud.githubusercontent.com/assets/3362943/23305631/10712556-fae3-11e6-8e55-1d5df6a9d113.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.13.4

- Steps to reproduce:
    1. Make the window size small so the close icon on tab appear on the favicon
    
- Actual result: See above

- Expected result: The close button should be hidden if the tab size is enough small

- Any related issues:

**Comment by cezaraugusto** [comment]
I think it's the same as #5431

**Comment by luixxiul** [comment]
yeah I agree, let's close this in favor of that.
