### ISSUE TITLE
Calculator in the address bar

### ISSUE THREAD

**Issue by valtih1978** [brave/browser-laptop#7371]
I find it useful in Chrome and do not understand why not to have this cheap but useful thing in the Brave too. You just type =3*4 and enjoy 12 in the first entry of the drop-down hint list.

**Comment by Jacalz** [comment]
+1 from community: https://community.brave.com/t/simple-request-for-calculator-abilities-in-location-bar/3798

**Comment by DamaDamaDama** [comment]
Yes this. I love Brave for mobile but for desktop being able to quickly type a small math problems into the url without even having to change tabs or anything is too important for me. Sometimes I have to do small calculations for school work, which can be done in a single url and accurately for me. Its a huge efficiency deal for students like me for sure.

**Comment by bsclifton** [comment]
I've confirmed this is fixed in [brave-core](https://github.com/brave/brave-browser)
