### ISSUE TITLE
Refactor menubar with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7372]
## Test plan

https://github.com/brave/browser-laptop/pull/11587#issue-266365280

----

Refactor menubar.js with Aphrodite

**Comment by bsclifton** [comment]
Removing from 0.14.2 since PR was closed

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
