### ISSUE TITLE
Bookmarks toolbar is very slow after importing a lot of bookmarks

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7374]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
After importing and syncing a lot of bookmarks, toolbar nav became quite slow.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.5 branch feature/batch-sync fcb4fc57eaa884998896fa795e0bd328585f3e3f - d9234b59065113071d45e03d323f973bb242b511

- Steps to reproduce:
    1. Join the forsaken sync group
    2. Import 6000 bookmarks
    3. Attempt to use the bookmarks toolbar
    
- Actual result:
Toolbar menu rendering is really slow

- Expected result:
Toolbar menu should navigate as quickly as bookmark menu 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@alexwykoff I believe this has been an issue for a while; is this a dupe of https://github.com/brave/browser-laptop/issues/7240?

**Comment by bbondy** [comment]
do you by chance have a bookmark file with 6000 bookmarks? Is this only related to sync or slow without sync too?

**Comment by alexwykoff** [comment]
At first I had thought it was related to sync, but just completed a review of 0.13.5 preview 3 which includes the batch-sync PR, and have concluded that as the number of bookmarks increases, bookmarks toolbar performance decreases. 

Primary bookmarks menu remains snappy.

I do believe this is a dupe of 7240 though, so I will close it.
