### ISSUE TITLE
No way to open a new tab in same session as session tab 

### ISSUE THREAD

**Issue by tarasglek** [brave/browser-laptop#7376]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Brendan was talking me through using session tabs, but Brave didn't act as Brendan suggested it would :)
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
Latest/71d8ffc(linux)
- Steps to reproduce:
    1.File/New Session Tab
    2.File/New Tab
    
- Actual result:
    Step 2 opens a tab in default session
- Expected result:
    Step 2 opens another tab in same session.

- Any related issues:
Between this issue and until issue 7367 is resolved, session tabs are of limited use.

**Comment by bbondy** [comment]
@bradleyrichter I think we need click and hold on new tab button to have a submenu under session tab for the created sessions. Thoughts?  We should do this soon.

**Comment by bsclifton** [comment]
related https://github.com/brave/browser-laptop/issues/7417

**Comment by bradleyrichter** [comment]
@bbondy that should work. 

We also want to make sure that child tabs from a new session parent tab are set correctly. One request is to allow this for control + T as well.

**Comment by bsclifton** [comment]
Moving to 0.13.7
