### ISSUE TITLE
Split and refactor BitcoinDashboard

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7380]
Addresses:

* Dry and make about:preferences code easier to maintain
* Refactor component styles to Aphrodite
* Make integration tests easier to write

**Comment by mrose17** [comment]
@cezaraugusto - what is the status of this issue? should it be closed? thanks!

**Comment by cezaraugusto** [comment]
will be addressed with https://github.com/brave/browser-laptop/pull/7481 along with other Payments-related components

**Comment by NejcZdovc** [comment]
Closed with #7481
