### ISSUE TITLE
Yellow square instead of magnifying glass

### ISSUE THREAD

**Issue by gutigen** [brave/browser-laptop#7385]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Where mouse cursor is suppose to change into magnifying glass (example: magnifying an image) it changes into yellow square. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch Linux (up to date with only official repositories, Brave from `brave-git` AUR)

- Brave Version (revision SHA):
`9aff02a`

- Steps to reproduce:
    1. Go to Imgur
    2. Pick any image
    3. Try to magnify it
    
- Actual result:
Yellow square as a mouse cursor

- Expected result:
Magnifying glass as a mouse cursor

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not sure, noticed just few days ago, so it might.

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed (it doesn't show on screenshot, so had to take a pic, sorry):
![brave_yellow](https://cloud.githubusercontent.com/assets/1865041/23329345/cfe0bade-fb36-11e6-9854-9892d64e970c.jpg)

**Comment by NejcZdovc** [comment]
Some other user has already notice this, more info in #7296. We should leave this issue open (not close it as a dup, because #7296 is not the correct issue for tracking this one).

@bsclifton

**Comment by gutigen** [comment]
Issue seems to be gone in `7373a01` (built just now).

**Comment by bsclifton** [comment]
@lucaszanella would you be able to grab latest from master and try this out? Issue should be resolved, per comment by @gutigen above

If you're not able to test with the code, we'll have a release soon.  I'll close the issue for now- please reopen if the issue shows again 😄
