### ISSUE TITLE
copy image to clipboard fails on paste

### ISSUE THREAD

**Issue by larry5b6** [brave/browser-laptop#7388]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Right click and Copy Image, then attempt to paste image into Thunderbird 45.7.1 email message. No action. Paste image into windows paint, copy from there, and then past into Thunderbird works fine. Not a Thunderbird issue - this works correctly with Firefox, Chrome, and MSIE.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 home edition 64 bit, Service Pack 1

- Brave Version (revision SHA):
Brave	0.13.4
rev	71d8ffc
Muon	2.56.4
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	6.1.7601
os.arch	x64
- Steps to reproduce:
     (see above)

    
- Actual result:
Image does not paste
- Expected result:
Image pastes
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This is a good one- it would be nice to test and see what the raw clipboard contents are

@larry5b6 would you be able to download a free Windows clipboard viewer (there are tons available- any that you feel comfortable with) to try this out with?

The data is obviously there... I suspect it's a formatting issue. The metadata in the clipboard might not be understood by Thunderbird

**Comment by JamborJan** [comment]
Hey guys, I'm experiencing the same issue but with macOS. Additionally I have a lot of trouble with right click and saving images. Nearly always the result is "aborted" immediately.

Please let me know what I can do to help tracking down this issue.

**Comment by scottbroadway** [comment]
Whenever I click 'Copy Image', it pastes only the URL. I didn't click on 'Copy Image Address'.

**Comment by scottbroadway** [comment]
This issue is still present in 0.14.0...and it doesn't seem like it's scheduled to be fixed at all.

**Comment by Liunkae** [comment]
@scottbroadway Where are you trying to paste the image?

**Comment by larry5b6** [comment]
Thunderbird email. If I paste to MS paint first, and then copy from there and paste to thunderbird, it works fine

On March 31, 2017 12:20:23 PM EDT, Liunkae <notifications@github.com> wrote:
>@scottbroadway Where are you trying to paste the image?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/brave/browser-laptop/issues/7388#issuecomment-290759299

Sent from my cellphone. Please excuse my brevity and typos.

**Comment by scottbroadway** [comment]
Still failing in 0.15.0.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/copy-and-pasting-image-itself-rather-than-image-link/4225) -- it's paste image link, not the image itself.

> In Chrome it is often that I find an image on a website, right click, and select "copy image." I can then actually paste the image into a Facebook message, photo editor, etc.
>
> The current behavior in Brave "0.16.12 rev 72624a2" is to paste the image's link rather than the image itself.

**Comment by Kagetsuki** [comment]
Confirming on Ubuntu 16 and 17.

Don't mean to "me too" but this is actually the only thing preventing me from abandoning FF as my primary browser. I constantly paste images from the clipboard during my work day.

**Comment by luixxiul** [comment]
+1 from https://community.brave.com/t/copying-images-and-pasting-to-word-document-wont-work/6286?u=suguru

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/images-arent-being-saved-copy-image-isnt-working/7425?u=eljuno

**Comment by CapitanPlanet** [comment]
+1 from me. Buttons "copy image" and "copy image address" have the same result. Both coping images URL.

**Comment by jonathansampson** [comment]
+1 (I believe) from Twitter: https://twitter.com/weems/status/934965671166869504

Also, @too4words reported seeing something similar in Brave recently.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/not-able-to-copy-images-and-then-paste-without-a-link/11699?u=eljuno

**Comment by jkanchelov** [comment]
+1

**Comment by bsclifton** [comment]
+1 from @JMccormick264 via https://github.com/brave/browser-laptop/issues/12540
>   1. I am doing this from the latest commits from github.
>  2. Go to google images, or Imgur, or any image hosting site. (I only checked those two)
>  3. Find an image
>  4. Right click on it and press "Copy Image".
>  5. Go to an app that can paste images. I used Discord and Telegram
>  6. Paste the image
>  7. If you had copied something before the image, you will see that paste instead of the image you just copied.

![brave copy and paste issue](https://user-images.githubusercontent.com/8153239/34654857-2c58f2b8-f3b6-11e7-8ff0-d926c38bcf0a.gif)

Reproduces 100% of the time in the latest commits from GitHub (https://github.com/brave/browser-laptop/commit/667f95d5fea262fe4320d6578482b875f6086c75); does not reproduce in latest release channel version (0.19.123)

**Comment by vonBarbarosa** [comment]
+1

currently using latest windows x64 version downloaded from main website (0.20.29). It seems like copying image on Brave doesn't overwrite previously copied thing, because when I paste it, the previously copied thing shows up.

**Comment by Razorswiftz** [comment]
+1

Windows 7, latest brave version. Right click "copy image address" works and copying text works but not "copy image" instead it shows the last thing on the clipboard.
I can copy images fine from other browsers.

**Comment by StephenBass** [comment]
+1 from the BAT Reddit
https://www.reddit.com/r/BATProject/comments/7x0482/copy_and_pasting_images/

**Comment by bbondy** [comment]
I think we need to change the way we're copying images since one of the chromium updates.

The console error is:
```
gen/app.entry.js:39 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Image.o.onload (chrome://brave/Applications/Brave.app/Contents/Resources/app.asar/app/extensions/brave/gen/app.entry.js:39:183473)
o.onload @ gen/app.entry.js:39
```

The way we used to copy is from the Window renderer:

```
module.exports.getBase64FromImageUrl = (url) => {
  return new Promise((resolve, reject) => {
    const img = new window.Image()
    img.onerror = function () {
      reject(new Error('unable to load image'))
    }
    img.onload = function () {
      const canvas = document.createElement('canvas')
      canvas.width = this.naturalWidth
      canvas.height = this.naturalHeight
      canvas.getContext('2d')
        .drawImage(this, 0, 0)
      resolve(canvas.toDataURL('image/png'))
    }
    img.src = url
  })
}
```
 
I think it is tainted because it's cross origin from what the window renderer is.

**Comment by bbondy** [comment]
I think it should be dispatching an action to the app store and using the web-contents `copyImageAt` API instead.

**Comment by srirambv** [comment]
Copy paste works on new email using thunderbird for Windows.

**Comment by LaurenWags** [comment]
Copy/Paste of images from several sources to gmail, facebook, etc worked on MacOS

**Comment by btlechowski** [comment]
Verified
```
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 4.13.0-21-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
```
