### ISSUE TITLE
Open-in-temp in addition to save-to-open

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#7393]
User wants to able be able to open attachments in emails without having to go through save/open steps:
https://community.brave.com/t/email-attachment-open-in-temp-vs-save-toopen/1417
It's a good idea for ergonomics' sake for email attachments and download links in general.

**Comment by luixxiul** [comment]
Duping to #1924?

**Comment by CliqueBait** [comment]
Yup. Sorry. It dups #1924. Didn't see that one.

**Comment by luixxiul** [comment]
Thanks for forwarding the issue anyway :-)
