### ISSUE TITLE
loading icon in tab is sometimes sluggish (slow frame rate or jumpy)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7394]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
occasionally, when the browser is chugging on something, the loading indicator also misses a beat. It drops frames or stops turning. I have even seen it appear to spin in the wrong direction based on the random illusion that frame dropping creates.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

 
Brave: 0.13.5 
rev: 7373a0197df9fbacc0fb83c5f7494be1fe0ae879 
Muon: 2.56.7 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.3.0 
os.arch: x64

- Steps to reproduce:
    1. when a tab is having trouble loading a site, notice the loading spinner effect. It does not happen all the time.
    2.
    3.
    
- Actual result:

spinner stops rotating or has the appearance of stopping due to frame dropping in the sequence.

- Expected result:

Like chrome, the spinner is always smooth while a tab loads.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

not sure

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?

yes, with patience.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I think we have a new one now right? Is this still an issue or can we close?

**Comment by bradleyrichter** [comment]
We can close it.
