### ISSUE TITLE
50-80ms delay when closing a tab

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7395]
Adding to the appearance of sluggishness is the delay seen when closing a tab. 

Click on the close button. 

Notice how long it takes before it closes after mouse-up event. 

 
Brave: 0.13.5 
rev: 7373a0197df9fbacc0fb83c5f7494be1fe0ae879 
Muon: 2.56.7 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.3.0 
os.arch: x64

**Comment by netinhoteixeira** [comment]
I have the same issue.

**Comment by netinhoteixeira** [comment]
Brave	0.15.314
rev	75ffa36
Muon	3.0.202
libchromiumcontent	58.0.3029.110
V8	5.8.283.38
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.6.0
os.arch	x64

**Comment by bradleyrichter** [comment]
@ayumi is finishing up a fix on this. Will land very soon. See #9191.
