### ISSUE TITLE
page shortcuts should work outside of webview

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#740]
probably need to be js keydown handlers in browser `index.html`, cf https://github.com/brave/browser-laptop/commit/83f116bfa61602a0c41471635baafaab2b684233

**Comment by cezaraugusto** [comment]
@diracdeltas was it fixed?

**Comment by diracdeltas** [comment]
I don't think so but I'm not sure which page shortcuts I was referring to here. I think they can be added on a case-by-case basis when needed, so I'll close this.
