### ISSUE TITLE
Cannot resize Brave

### ISSUE THREAD

**Issue by swasical** [brave/browser-laptop#7400]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
When I open Brave, the window is maximized. Clicking the maximized button doesn't change anything. I also cannot drag the window to resize it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version (revision SHA):
0.13.2

- Steps to reproduce:
    1. Open the browser.
    
- Actual result:
No means of resizing the window

- Expected result:
Should allow me to resize the window

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Don't know.

- Is this an issue in the currently released version?
Don't know.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
@swasical Can you try updating to the latest version 0.13.4 and see if this will solve the problem?

**Comment by swasical** [comment]
I did - it didn't fix the issue.

________________________________

**Comment by bsclifton** [comment]
@swasical can you help us collect more info?  I'm curious about the two following scenarios:
- Does the mouse change to the resize handle when moving to the edges of the screen?
- Can you use shift + F8 to open the electron developer tools?  Once this is open (opens docked on the right)- you can click "Console" tab.  Once this is up, go ahead and click the maximize button.  I'm curious if any errors show up here?

**Comment by swasical** [comment]
The answer to the first question is no.

When I opened the tools and clicked on the Console tab, that made it so I could minify and maximize. I don't know why, but it must have kicked something. Now the setting is correct, so when I reopen Brave, Minimize/Maximize still works. Thanks!

________________________________

**Comment by bsclifton** [comment]
@swasical oh wow- that is weird... but glad to hear! 😄   I'll go ahead and close this issue, but if it happens again, please re-open and let us know
