### ISSUE TITLE
Reset sync on pyramid 0 and re-enabling sync doesn't sync bookmarks properly across devices

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7405]
## Test plan

https://github.com/brave/browser-laptop/pull/7420#issue-210937396

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reset sync on pyramid 0 and re-enabling sync doesn't sync bookmarks properly across devices

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10x64 - Pyramid 1
Windows 7 ia32 - Pyramid 0

- Brave Version (revision SHA):
Brave	0.13.5
rev	7373a01

- Steps to reproduce:
    1. Enable Sync on pyramid 0
    2. Sync pyramid 1 to pyramid 0 using the secret code from pyramid 0
    3. Add few bookmarks on either of the device and verify both have the all bookmarks 
    4. Create an empty bookmark folder in pyramid 1, doesn't get synced on pyramid 0
    5. Move one of the bookmarks into the folder in pyramid 1, simultaneously reset sync on pyramid 0
    6. Re-enable sync on pyramid 0 and use the secret code from pyramid 1(same as in step 2)
    7. Wait till the bookmark folder is sync'd on pyramid 0
    8. Move the bookmark from within the folder on to the toolbar in pyramid 0, doesn't sync the changes on pyramid 1, it still shows the bookmark under the folder
    
- Actual result:
Sync after reset doesn't sync correctly

- Expected result:
Sync after reset should behave the same way

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @diracdeltas

**Comment by diracdeltas** [comment]
cc @ayumi

**Comment by diracdeltas** [comment]
> Create an empty bookmark folder in pyramid 1, doesn't get synced on pyramid 0

It does get synced on pyramid 0 for me, even when empty. Sync only happens every 60s so you might have to wait.

**Comment by diracdeltas** [comment]
@srirambv i cannot repro this consistently, but please check out https://github.com/brave/browser-laptop/tree/fix/7405 and see if that resolves the issue. thanks

**Comment by srirambv** [comment]
@diracdeltas  I am able to get the empty bookmark folder sync'd but steps 6-8 still doesn't work on https://github.com/brave/browser-laptop/tree/fix/7405.

**Comment by srirambv** [comment]
Pyramid 1 
![7405](https://cloud.githubusercontent.com/assets/17010094/23406296/1f6bfea2-fdb6-11e6-9773-dc64549480cf.gif)
![image](https://cloud.githubusercontent.com/assets/17010094/23406431/dbb54316-fdb6-11e6-8e3c-6a5caeba1e80.png)

Pyramid 0
![image](https://cloud.githubusercontent.com/assets/17010094/23406090/3100e05c-fdb5-11e6-9fea-4a5cb74535c8.png)
![image](https://cloud.githubusercontent.com/assets/17010094/23406306/2ba3cf4c-fdb6-11e6-825d-8f1fb410bfa9.png)


Steps performed 
1. Created empty folder 7405 on pyramid 1, sync'd on pyramid 0 as well
2. Moved github under the folder on pyramid 1
3. Reset sync on pyramid 0
4. Re-enabled sync on pyramid 0
5. Folder and github bookmark got duplicated from pyramid 0 
6. Pyramid 1 still retains the github bookmarked moved under the folder created on that machine

Console shows pyramid 1 is still fetching and pyramid 0 is sending data even after reset. It should be the other way around after sync is reset on pyramid 0?

**Comment by diracdeltas** [comment]
@srirambv please check out https://github.com/brave/browser-laptop/tree/fix/7405 which has been updated; it fixes the issue for me.

@ayumi this issue appears to be due to the fact that objectIds are deleted when sync is reset, so old synced objects are synced as if they were new objects after sync is reset and then re-synced to the old profile. this causes sync objects to be duplicated. need your input on https://github.com/brave/browser-laptop/commit/aff4cf592bff46d43b651c075857f8ec80b90418.

**Comment by srirambv** [comment]
Still not working. https://github.com/brave/browser-laptop/pull/7420#issuecomment-286823531

**Comment by luixxiul** [comment]
Let me reopen just in case

**Comment by srirambv** [comment]
Working fine on preview 2. Good to close unless need to have it open till RC builds.

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/pull/7420#issuecomment-290026391

> the step 5 (in pyramid 1, move the bookmark into the folder. this change should sync correctly to pyramid 0) does not work between Windows 10 32 bit and macOS.
> 
> The sync itself is working between them, since another bookmark was synced successfully after moving the bookmark into the folder, which was not synced.
