### ISSUE TITLE
CTRL+0 doesn't reset zoom level as indicated.

### ISSUE THREAD

**Issue by SamClarke2012** [brave/browser-laptop#7410]
**- Did you search for similar issues before submitting this one?**
Yes

**- Describe the issue you encountered:**
Zoom in, with CTRL+=.  Can't reset zoom with CTRL+0.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**
Linux x64

**- Brave Version (revision SHA):**
71d8ffc

**- Steps to reproduce:**
    1. Zoom in using CTRL+=
    2. Attempt to reset zoom using CTRL+0 - (shortcut indicated in view menu)
    
**- Actual result:**
 Nothing happens

**- Expected result:**
Zoom should be reset to actual size

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**
Yes

**- Is this an issue in the currently released version?**
Yes

**- Can this issue be consistently reproduced?**
Yes

**Comment by bsclifton** [comment]
@SamClarke2012 are you using the 0 in the main keyboard? or from the numpad?

**Comment by SamClarke2012** [comment]
You're correct, I've just checked and it seems to only be caused by the numpad 0.

**Comment by SamClarke2012** [comment]
In regards to #4815, my + and - numpad keys operate as expected.

**Comment by bsclifton** [comment]
Awesome, thanks for confirming @SamClarke2012 😄  I captured your info in https://github.com/brave/browser-laptop/issues/4815; I'll go ahead and close this one as a dupe.  You can subscribe to the other one if you'd like updates- it's a little tricky because it requires Muon (our fork of Electron) changes

**Comment by SamClarke2012** [comment]
Excellent, thanks for the great response time and verbose feedback. I'll be sure to check for duplicates more thoroughly if there's a next time. 
😀
