### ISSUE TITLE
New tab small window

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7411]
## Test Plan
- open new tab
- resize window to 560x680
- there shouldn't be x scroll

## Original issue description
I sometimes use small music players (they are opened automatically in a new small window from their main page) like this one:

![image](https://cloud.githubusercontent.com/assets/9574457/23397676/d2b93e06-fd99-11e6-8436-1884fe075e31.png)

and if open a new tab, new tab is not adjusted for small window (window size in screen shots bellow is 560x680).

Current:
![image](https://cloud.githubusercontent.com/assets/9574457/23397788/48dbdb98-fd9a-11e6-862d-167edcbf0cd3.png)

![image](https://cloud.githubusercontent.com/assets/9574457/23403441/718a07de-fdb0-11e6-897a-f536fca82470.png)

My proposition:
![image](https://cloud.githubusercontent.com/assets/9574457/23397746/1916eaec-fd9a-11e6-9018-f3b367f03fea.png)

What do you think?

cc @bradleyrichter @luixxiul @cezaraugusto @bsclifton

**Comment by cezaraugusto** [comment]
++ super cool
