### ISSUE TITLE
Zoom pointer issue

### ISSUE THREAD

**Issue by babolivier** [brave/browser-laptop#7413]
- Did you search for similar issues before submitting this one?

Yup

- Describe the issue you encountered:

Recently re-installed Brave on a newly installed Archlinux (from the `brave-bin` AUR package) and noticed that, instead of having a zoom pointer I had a yellow square.

GIF available here (with comparison with the expected behaviour on Firefox): https://twitter.com/BrenAbolivier/status/836567651086397442

- Platform (Win7, 8, 10? macOS? Linux distro?):

Archlinux

- Brave Version (revision SHA):

0.13.4

- Steps to reproduce:
    1. Open a webpage using this cursor (such as TweetDeck)
    2. Move your pointer to any image (not GIFs)
    
- Actual result:

Pointer is replaced with a yellow block.

- Expected result:

Pointer is replaced by the zoom pointer.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yep, since I tried it in a fresh profile (AFAIK)

- Is this an issue in the currently released version?

Hadn't been using Brave for a bit, so I don't know about the older versions. But yep, that's the latest stable release.

- Can this issue be consistently reproduced?

Yes, AFAIK.

- Screenshot if needed:

Please see the tweet linked above.

- Any related issues:

Nope.

**Comment by NejcZdovc** [comment]
Here is the issue that is tracking this problem #7385. Can you try out our latest version from the master and see if problem is gone? We will also release a new 0.13.5 preview, so you can try there as well.

**Comment by bsclifton** [comment]
Closing as it's a dupe; please do try a preview build if possible- if the issue still exists, we can re-open https://github.com/brave/browser-laptop/issues/7385

Thanks 😄

**Comment by babolivier** [comment]
Hi, sorry for the delay (been quite busy). Updated to 0.13.5, works like a charm 😄
