### ISSUE TITLE
Double clicking bookmark on bookmark bar

### ISSUE THREAD

**Issue by andreogle** [brave/browser-laptop#7414]
- Did you search for similar issues before submitting this one?
**Yes. Couldn't find anything similar**

- Describe the issue you encountered:
**I open a new tab and click on a bookmark on the bookmark bar. While it's loading, I click on it again. It stops loading and the page remains blank. I can't navigate again using this tab and need to open a new tab in order to browse again**

- Platform (Win7, 8, 10? macOS? Linux distro?):
**macOS Sierra**

- Brave Version (revision SHA):
**0.13.4**

- Steps to reproduce:
    **1. Open a new tab**
    **2. Click a bookmark on the bookmark bar** 
    **3. Before the page has loaded, click on the bookmark again**
    
- Actual result:
**The tab remains blank and unusable**

- Expected result:
**The page should be reloaded or navigation should continue**

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
**I'm using a fresh profile, so they should be reproducible**

- Is this an issue in the currently released version?
**Yes, version 0.13.4**

- Can this issue be consistently reproduced?
**Yes**

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

P.S. Thanks for all of the hard work on Brave! Loving what you guys have done so far.

**Comment by bsclifton** [comment]
@andreogle I'm having a really hard time reproducing this- I'm also on 0.13.4 and macOS Sierra.  Are you double clicking fast? or just anytime before the page is loaded?  I bookmarked this page for example and can't cause the issue

**Comment by andreogle** [comment]
@bsclifton I've tried double clicking fast, as well as waiting for the page to start loading and both seem to cause the issue for me. It seems to happen consistently when trying from a new tab.

I'm getting a new Mac in the next few days so I'll have a completely clean install to try again. I'll report back and update the issue once I've had a chance to play around with that a bit. Not sure what other info I could provide right now to help replicate this

**Comment by srirambv** [comment]
@bsclifton  I am able to repro the issue. It so happens even when you double click the bookmark icon some times it captures only one click which causes it to open the bookmark in the tab. In the gif  you can see the first attempt captures the double click correctly but later on even when the bookmark item is double clicked it only registers single click causing the tab to load the bookmark item.
![7414](https://cloud.githubusercontent.com/assets/17010094/23503592/47f0d90e-ff34-11e6-88c0-0c90b8900487.gif)

**Comment by SethClydesdale** [comment]
I'm having a similar issue, although it's after the page has already loaded.

1. Open a new tab and navigate to another page
2. Wait for the page to finish loading
3. Double click an item on the bookmarks bar that's NOT the current bookmark

The result should be a broken page.
![](https://i58.servimg.com/u/f58/18/21/41/30/captur11.png)

I believe it's related to this issue.

**Comment by Attrash-Islam** [comment]
+1
Me too on Linux mint

One click on a bookmark, and `double click` on another bookmark -> caused frozen not responsive tab!

![frozen_tab](https://cloud.githubusercontent.com/assets/7091543/24657293/52c3d30c-194e-11e7-9e36-567f26f22a19.gif)

**Comment by andreogle** [comment]
Just checked now and this seems to be fixed in 0.15.1! 🎉 

Thanks guys

**Comment by bsclifton** [comment]
awesome, thanks for the report, @andreogle 😄 

@SethClydesdale, @Attrash-Islam: would you all be able to re-test?

**Comment by SethClydesdale** [comment]
Yep, it appears to be fixed for me too ! 👍
