### ISSUE TITLE
Can't view "Contribution Statement"

### ISSUE THREAD

**Issue by keverets** [brave/browser-laptop#7416]
- Did you search for similar issues before submitting this one?
Yes, none found.

- Describe the issue you encountered:
Preferences -> View Payment History... -> Receipt Link (to Brave_Payments_2017-02-21.pdf)
Opens briefly in a new tab then closes immediately.
Repeated trials will let me get a sense of what's in it (it does appear to be a correct rendering of the payments), but there's no way to capture it before the tab closes less than a second later. The link to the PDF is a "chrome-extension://" link so there appears to be no easy way to extract the info.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04.5

- Brave Version (revision SHA):
0.13.4-1
About -> Brave shows:
Brave	0.13.4
rev	71d8ffc
Muon	2.56.4
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	linux
os.release	4.5.3-040503-generic
os.arch	x64

- Steps to reproduce:
    1. Make bitcoin contribution
    2. Visit sites
    3. After a month, check Preferences -> View Payment History... -> Receipt Link
    
- Actual result:
Statement appears in a new tab for less than 1 second then closes.

- Expected result:
Statement should stay visible in the tab.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Unknown. Not going to throw more money at this until it's fixed.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

**Comment by bsclifton** [comment]
I'm also seeing this too, with 0.13.4 on macOS ☹️

**Comment by willy-b** [comment]
The `webContents.printToPDF` method in Muon which this depends on seems to have broken again (see #6450).

**Comment by bsclifton** [comment]
Not fixed by https://github.com/brave/muon/pull/166 ☹️

**Comment by diracdeltas** [comment]
+1 for fixing this

**Comment by srirambv** [comment]
Step 6 fails on Windows 10 x64
![image](https://cloud.githubusercontent.com/assets/17010094/24497314/ea33c9d8-1532-11e7-9ec4-71b90bc9b983.png)
