### ISSUE TITLE
Add JSON viewer

### ISSUE THREAD

**Issue by Dreae** [brave/browser-laptop#7418]
**- Did you search for similar issues before submitting this one?**
Yes

**- Describe the issue you encountered:**
When viewing JSON data in the browser the unformatted text is displayed instead of a formatted version. It would be nice if Brave could display a parsed and formatted version of the JSON data similar to what Firefox Developer Edition or [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) does.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**
Arch Linux

**- Brave Version (revision SHA):**
71d8ffc

**Comment by srirambv** [comment]
The support for JSON viewer is already in works. You can track it here 
https://github.com/brave/browser-laptop/projects/1#card-571072
