### ISSUE TITLE
Actual payments do not match view in browser & payment does not clear ledger

### ISSUE THREAD

**Issue by disfit** [brave/browser-laptop#7419]
As per request via email: ask @mrose17 for the screenshots for the issue(s) below.

Payment overview shows payments to 29 sites even though the payment screen in the browser 8 minutes before payment shows 26 ( ranking 1- 27, row 17 missing). 

The payment screen after payment shows correct balance for wallet, but does not clear the ledger. The same 26 sites are shown after payment as before payment. For some sites there are slight changes in the %-share and instead of row 17 missing from the list, after payment row 13 is missing.

Name | Version
-------- | ----------
Brave | 0.13.4
libchromiumcontent | 56.0.2924.87
Muon | 2.56.4
Node.js | 7.4.0
os.arch | x64
os.platform | linux
os.release | 4.8.0-36-generic
rev | 71d8ffc
Update Channel | dev
V8 | 5.6.326.50

**Comment by mrose17** [comment]
sorry for the delay in replying and thanks in reporting.

one thing to keep in mind is that the ledger synopsis shows the running 30-day total, so it's not going to "reset" after a payment. if you were to stop going to those publishers for the next 30 days you'll see the percentages start to drop and after 30 days they'll disappear.

in the case of missing row 17, give me your opinion on this: i'm pretty sure that the reason that the row is missing is because the publisher is on your "never include" list (either by clicking in the "Remove" column or by right-clicking and selecting "Never include this site"). do you think we should keep the current behavior OR should we keep the numbering contiguous?

thanks!

/mtr

**Comment by bsclifton** [comment]
Moving to 0.14.1 (aka 0.13.7)

**Comment by disfit** [comment]
Now worries about the delay ... especially since my response is also very much delayed.

### Clearing  vs. running 30-day ledger
I gave this quite a bit of thought the last days. Having the 30-day running total as the ledger synopsis does not make sense to me in the context of the payments. It does give a nice overview of most visited/used sites, but as a user that would be more interesting as a specific history view. 

However when I look at the ledger synopsis from the viewpoint as line items of an invoice / shopping cart for the current running 30 day period, it does not make sense. I just paid for my usage, so why am I still seeing it? It might cause distrust or confusion in some consumers (though probably not the early adopters). Even though a heading in the overview of "Running 30 day total" might help for some, I doubt most will understand not seeing any (or only a minute) change after payment. People will also run into situations they cannot explain or might find 'spooky'. As an example:

The last weekend I re-ripped our CD collection and made heavy use of musicbrainz.org. It now rests on top of the synopsis and will most likely remain there for somewhere between 25 and 27 days. The contribution is due in 14 days. So for about 11 to 13 days musicbrainz.org will be the top dog. (We have a lot of CD's and they were long days.) The chance of me visiting musicbrainz.org in the mean time are close to zero. So at a certain moment I will see a sudden drop from top position to a very much lower position on the ledger, or due to non-usage of Brave or looking at the ledger having the memory of musicbrainz.org being on top previously and not seeing it anywhere in the synopsis. 

In short: it might cause problems in the perception of what is happening and thus be a barrier for people to use and trust Brave payments. (I do realize that one of the reasons keeping the 30-day running total is because it might play a factor in calculating the ratio. As in: past usage evening out sudden temporary rises or falls in usage.)

### Contiguous numbering vs. gaps in numbering
This again is a possible perception problem. What I am most concerned about is the trust people will have in Brave Payments. Again, this most likely will not be a problem for early adopters (assuming they are more IT savvy, understanding and/or willing to search for answers). For the majority of people this just looks strange and might cause them to be suspicious of Brave Payments, or even worse Brave itself.

Your explanation of it being a previously excluded / removed site might very well be the case. Before the contribution date I had two or three instances where I saw gaps in the numbering. Curious as I am, I removed the exclusions under Preferences > Shields, to see if this would give me a contiguous numbering. This was the case every time, and each time I excluded the sites in question again. This would leave me with a contiguous list: no gaps where there were ones before.

This by the way might also have caused the discrepancy between the payment overview and the synopsis. As mentioned the overview shows payments to 29 sites and the synopsis showed 26.

To summarize both: you might currently not aim Brave Payments to the average user. But in my mind and experience things like this will influence how Brave Payments are perceived.

I hope I gave useful food for thought and my apologies for the length :-)

**Comment by mrose17** [comment]
thanks! i think it's clear that the non-contiguous numbering is a (perceived) bug. regardless, we're getting rid of it ... because the `Rank` column is no longer needed!

i am tending towards thinking that it is best to have the history reset after the contribution is made, and perhaps have an actual viewing history (as opposed to where contributions go) appear in another tab, as suggested here: https://github.com/brave/browser-laptop/issues/7013

what do you think?

**Comment by disfit** [comment]
That makes a lot of sense. Maybe with the possibility of entering a date range or choose prior contribution periods. This not just for geeks, like me, who find joy in data, bit maybe more important for when people feel the need to do a (global) check between their contributions and their usage.

At this moment, and probably in the future, I keep close tabs on the payment synopsis, included sites, usage and actual contributions. I would not be surprised when most future mainstream (non-geek) users will start with paying close attention, but either will loose interest or lack the time to do so every time.

What a lot of people do seem to do (out of boredom, interest or necessity) is check where their money is going. In my mind it will be beneficial if they would be able to understand or check why X amount went to site Y at a certain moment in history.

For how long a period this information should be accessible in full detail would be an open question. A month seems too short, a year maybe too long. (Unless visits to 'good causes' can be seen as a tax deductible donation, but then you run into this whole privacy problem from a different angle: I doubt people want to offer their browser history to the IRS and the foundations have no clue who made the 'donation' by visiting the site.)

**Comment by mrose17** [comment]
hi. i think it may be hard to support arbitrary ranges, given the amount of data, etc.  i'm still studying that issue (right now, the software trims everything at 30 days).

it may be possible to include more information in the PDF statement to make things more transparent and easier to track.

**Comment by disfit** [comment]
Sorry for the delayed response. I had not thought about the impact of the history on the performance. In that respect the 30-day trim is essential. For some users the 30 days of browsing might even start to tax their system. I am not sure how syncing will work in this respect, but the less history that has to be synced, the better.

So your suggestion of enriching the information in the PDF statement might be the best way to go in order to give people more insight in why a site got what share of the payments. In the end it will give people insight in their browsing behavior that they might not like. Seeing money go to a site will feel different than (unconsciously) knowing that you spent (a lot of) your time there.

This will hit a bit on things like the privacy paradox: people know that they are taken for a ride that might or will hurt their privacy with possible negative effects in the long run, but still choose to go for the short term satisfaction of receiving the service or using a website. The fact that they are thus subsidizing the website by supplying data and receiving ads might be known to them, but for most will be very difficult to visualize. Money on the other hand is easy to grok. 

In other words: if you have visited a site 100 times and spent 6 hours on it, it is difficult to visualize how much privacy you have lost and how much income you have generated for the website owner. With  Brave Payments it is immediately crystal clear what your visits to a site have cost you and have contributed to the site's revenue.

For most sites people will visit that will not be a problem, but some people will suddenly realize that they are supporting a website that they do not want to support. Active Brave users will exclude those sites. But (future) regular users might forget to do that. Having the number of visits and time spent as a reference will hopefully mitigate critique towards Brave Payments.

Undoubtedly there will still be a small group of people who will question the correctness of the usage details. Hopefully the majority of users will however see the details and decide to be more active in pruning their payment list in the future.

**Comment by mrose17** [comment]
@disfit - thanks. we are trying a few things to be both intuitive and transparent (which isn't an easy balance!)

the current model is that personal data stays on the browser and is "atomically anonymized" before hitting the network; however, we're also planning on adding a mechanism to remove the data in the browser as well. the drawback, of course, is that once someone does that, they're not going to be able to generate any statements for the periods that were removed...

**Comment by bsclifton** [comment]
pushing back to 1.0

**Comment by disfit** [comment]
@mrose17 - just had the same behavior with last payment as described earlier for this ticket. I will mail you the screenshots and payment PDF shortly.

@NejcZdovc - if needed you can of course get the screenshots and PDF as well, either from me directly or @mrose17.

**Comment by disfit** [comment]
After an update to 0.14.1 the payment screen showed more sites. By manipulating the reconcile stamp I forced an earlier reconciliation to test if the issues had been solved.

Unfortunately this was not the case. As far as I can see there were three inconsistencies:

- contributions were made to excluded sites, 
- some of the rankings / contribution shares do not match between the payment screen and the contribution overview
- there are sites on the contribution overview that are not present / shown on the payment screen.

I took the following steps in this test (screen shots & contribution overview can be requested from @mrose17) :

1. Screen shots of payment screen and shield settings (exclusions)
2. Exclude sites using the include/exclude slider for some and right-click menu > Exclude always for others.
3. Restart of Brave
4. Screen shots of payment screen and shield settings (exclusions)
5. Shutdown of Brave
6. Change of reconcile stamp to +30 minutes
7. Restart of Brave & wait patiently

**Comment by zentagonist** [comment]
Closing as stale
