### ISSUE TITLE
allmusic.com - anti-ad blocking overlay

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7421]
- Did you search for similar issues before submitting this one?
Yes 
- Describe the issue you encountered:
@srirambv reported an anti-ad blocking content overlay on allmusic.com 
I've been able to repro in Windows 10. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
All. 
- Brave Version (revision SHA):
 
```
Brave: 0.13.4 
rev: 71d8ffc7278a90b22b8617d37880787c1781e694 
Muon: 2.56.4 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```
- Steps to reproduce:
    1. Go to allmusic.com
    2. Observe content blocking overlay that prompts the user to subscribe. 
    3.
    
- Actual result:
No access to allmusic.com

- Expected result:
Access to allmusic.com 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-allmusic com-02282017-blocking](https://cloud.githubusercontent.com/assets/8979240/23441562/deeb7a7a-fdd7-11e6-8554-25be058de6a0.png)

- Any related issues:

It appears that they're using a 1p tests to see if blocking is detected, called from inline JS. 

to test they appear to use this header call: 
`http://zt.allmusic.com/allmusic/header 
`
If the test fails (blocking detected) then this call is made for the modal: 
`http://www.allmusic.com/js/common/account-expired.js?_=1488333032513
`
The modal uses inline CSS with !important overrides and a z-index:20000 to overlay. 

I've hunted anti-blocker repos and everyone is having issues with this right now. Allmusic apparently changes their anti-blocking fairly often. 

I've tested using ABP and uBO w/the latest lists, all of them are unable to get past this right now.

**Comment by Jacalz** [comment]
Can not reproduce this issue
