### ISSUE TITLE
Right+click Bookmark Bar, Open in New Tab loads in current tab AND opens a new tab. (BUG)

### ISSUE THREAD

**Issue by mil1i** [brave/browser-laptop#7422]
- Did you search for similar issues before submitting this one?
Yes, did not see this specific bug listed.

- Describe the issue you encountered:
When opening a bookmark from the Bookmarks Bar via Right Clicking and selecting Open in New Tab or Open in New Session Tab, it loads the bookmark in my current tab as well as opens a new tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro, 1607-14393.

- Brave Version (revision SHA):
0.3.14, 71d8ffc.

###################
ON A SIDE NOTE:
I have read through a couple of things and would like to see some things implemented into Brave as well!

Shortcuts for Bookmarks. Ctrl + Shift + B to show/hide the Bookmarks Toolbar is gone, but Ctrl + Shift + O is still there. Maybe add an extension that pops down a menu of your Bookmarks Bar?

The other thing would be Nightmode, or a Dark UI. As well as a built in feature, or even the addition of the extension like G.lux (f.lux) where it has the ability to dim the background and alter the color at night for brightly colored sites.

**Comment by bsclifton** [comment]
@mil1i thanks for the report 😄  this issue has been captured with https://github.com/brave/browser-laptop/issues/7284 which I fixed last nite (will be available in our next release).  I'll go ahead and close this issue as a duplicate

I'll check out the Ctrl + Shift + B missing... We do however have night mode captured with https://github.com/brave/browser-laptop/issues/1090 which you can follow 😄
