### ISSUE TITLE
Include switch is enabled by default for publishers even though auto include is turned off

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7429]
Test plan:

https://github.com/brave/browser-laptop/pull/7439#issue-211295769

<hr>

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Include switch is enabled by default for publishers even though auto include is turned off

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	7373a01

- Steps to reproduce:
    1. Enable payments in 0.13.5 Preview 3
    2. Turn off `auto include` switch in payments window
    3. Visit any site which is not on the exclude list, Site is listed and include switch is turned on by default
    
- Actual result:
Include switch is enabled by default for publishers even though auto include is turned off

- Expected result:
Should only list the publisher but not include it

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![autoinclude](https://cloud.githubusercontent.com/assets/17010094/23458626/e8fcdf70-fe74-11e6-9a84-ef148ef10a41.gif)
![autoinclude_134](https://cloud.githubusercontent.com/assets/17010094/23458497/65b66294-fe74-11e6-95d7-9c5c424c7d58.gif)

- Any related issues:
cc: @mrose17 @cezaraugusto

**Comment by cezaraugusto** [comment]
thanks for reporting. New logic for publishers sets disabled by default if auto suggest is off.

There's a fix for that but not ready for review so let's keep this open until it is
