### ISSUE TITLE
YouTube.com player - updated ad blocking evasion

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7432]
- Did you search for similar issues before submitting this one?
Yes - YT has updated the player enough times to where a fresh issue is needed. 

- Describe the issue you encountered:
YT player has updated again, this time to evade ad blocking for both authenticated and unauthenticated users. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All. 

- Brave Version (revision SHA):
 
```
Brave: 0.13.4 
rev: 71d8ffc7278a90b22b8617d37880787c1781e694 
Muon: 2.56.4 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```
- Steps to reproduce:
    1. Go to YT
    2. Click segments
    3. Get ads
    
- Actual result:
Ads
- Expected result:
No Ads
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

Opening this issue to helps clear noise and clean-slate this process. 

**Troubleshooting and issue timeline for reference:** 

**Original issue filed:**  https://github.com/brave/browser-laptop/issues/4693
- This was resolved with v0.13.0 update, which disabled QUIC protocol. 
- Clearing cookies/cache resolved for residual issues. 

**02.10.2017 YT Player Update**
- Authenticated users began seeing ads
- Users signed out of YT were not seeing ads
- Some user instances of embedded YT iframe players not working w/shields up, but did work with shields down. Only appeared to happen in certain sites. 
- Opened this issue to investigate: #7230 
- Upon investigation, moved to adblock-lists for resolution.  brave/adblock-lists#3

**02.27.2017 YT Update**
- @NejcZdovc @alexwykoff @echosa all report seeing ads in YT player regardless of authentication. 
- @srirambv files issue from other sites using embedded YT players, which only work when blocking is disabled. 

**Tracking the embedded YouTube iframe player issue here:** https://github.com/brave/browser-laptop/issues/7428

**Tracking the latest YouTube.com player issue from here** #7432 . 

_Closed the other issues, as the overlap and history for them was confusing._ All relevant issues are linked to this one I'm creating now. Let's update Youtube.com items here, and the embedded player issues on the linked issue from @srirambv above. 

**Next Steps:** 
- Thorough investigation has taken place, several rounds since 02.10.2017. 
- Working within the adblock-lists repo to resolve with blocking rule updates. 
- Based on results from blocking list testing, additional measures may be required.

**Comment by srirambv** [comment]
YouTube Ads even without logging in. After playing 4 videos ad was seen on this link https://www.youtube.com/watch?v=V76psBrEypg
![image](https://cloud.githubusercontent.com/assets/17010094/23566796/53bca2c8-004b-11e7-9df7-0e055be79f6c.png)
Ad's seem to come up when there is fingerprint script that is blocked 
![image](https://cloud.githubusercontent.com/assets/17010094/23566916/daea5bb4-004b-11e7-8774-5e1f03a3d6fa.png)

Without fingerprint 
![image](https://cloud.githubusercontent.com/assets/17010094/23566895/c3138ab0-004b-11e7-91ab-433b02c42537.png)

**Comment by quesada** [comment]
I still see ads. Linux.

**Comment by quesada** [comment]
Wow, youtube audio dies if switching tabs. Manjaro: aur/brave-bin 0.19.105-1 (92)
This is bad.
