### ISSUE TITLE
Cannot paste links into Slack (dropping shields resolves)

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7433]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
> "So irritating that pasting text (Urls) into the Slack edit input is broken on @brave (OSX)"
> &mdash; source: https://twitter.com/mitchwongho/status/836986183523655681

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (reported)

- Brave Version (revision SHA):
0.13.4

- Steps to reproduce:
    1. Copy a URL
    2. Attempt to paste into Slack's input
    3. Note that nothing is pasted
    
- Actual result:
Slack does not receive/display the pasted URL

- Expected result:
The pasted URL is displayed as part of the message

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
_None_

**Comment by jonathansampson** [comment]
Does not appear to repro on Windows.

To test, I right-clicked a link on Twitter and selected _Copy Link Address_. I then went over to my Slack tab, and right-clicked in the message input. Selecting _Paste_ resulted in the pasted URL being displayed.

I attempted other means of pasting (ctrl+v, right-click > paste without formatting); all succeeded. This appears to be the results @srirambv also found on Windows.

**Comment by jonathansampson** [comment]
The original user reported the issue no longer repros.

https://twitter.com/mitchwongho/status/837018980179128320

**Comment by thekasser** [comment]
I have the same issue on Max OSX starting yesterday

**Comment by Vishal-Joshi** [comment]
@jonathansampson  I can still see the issue. I am not able to paste links to slack message box. 
Slack version : 2.6.3
Macbook Pro: 10.12.6

**Comment by Vishal-Joshi** [comment]
Well, I restarted my macbook as I could see some of the other applications were affected to with this copy-paste issue.
I don't know why but the issue was not there after restart.

**Comment by luixxiul** [comment]
the issue that copy & paste function does not work will be fixed on 0.19. Please hang tight, thanks!

**Comment by chiragsc** [comment]
I can still see the issue. I am also not able to paste links. 
Slack version: 2.8.2 Direct Download
MacOS Sierra 10.12.6

**Comment by paragbaxi** [comment]
cannot paste into slack with clipboard manager copyq

**Comment by kalyanhr** [comment]
Today I got the same copy/paste problem and could fix by following these steps:

1. Open your application folder
2. Open the utilities subfolder
3. Open the Activity Monitor app
4. Type “pboard” into the search box at the top right
5. In the search results below, there should only be one result — a row listing the “pboard” process. Highlight it by clicking on it.
6. Click the “x” button at the top left of the window which represents ‘quit this process’

Once you’ve done that, OS X will kill the faulty PBoard process and re-establish it with a fresh one automatically. It should be back to normal.
