### ISSUE TITLE
Add new state for locationInfo

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7435]
Test plan:

https://github.com/brave/browser-laptop/pull/7439#issue-211295769

<hr>

We need a state with data such as `excluded` list and `verified` publisher list that fetchs as soon as the page is loaded.

This is needed for #7089 and #7429

**Comment by mrose17** [comment]
just checking: is this already in https://github.com/brave/browser-laptop/pull/7439 ?

**Comment by cezaraugusto** [comment]
@mrose17 yes issue was opened just for reference

**Comment by mrose17** [comment]
thanks, just checking!
