### ISSUE TITLE
Incorrect state found in tab.pinned

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7440]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When querying tab objects via the `chrome.tabs` API, the `pinned` property does not accurately communicate whether or not a tab is presently pinned.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.13.4

- Steps to reproduce:
    1. Navigate to, and pin, about:extensions
    2. Press Ctrl+Shift+I to open the developer tools, switch to Console
    3. Run `chrome.tabs.getCurrent(tab => console.log(tab.pinned))`
    
- Actual result:
The `pinned` value is `false`.

- Expected result:
The `pinned` value should be `true`.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
moving to 0.14.3

**Comment by bbondy** [comment]
This actually already works with the detachable tabs merge. Closing and marking as 0.14.2.
