### ISSUE TITLE
The chrome.tabs.update API doesn't pin tabs

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7441]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When calling `chrome.tabs.update`, the user is not able to pin (or unpin) a given tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.13.0

- Steps to reproduce:
    1. Open about:extensions
    2. Press Ctrl+Shift+I, open Console
    3. Run the following command:

```js
chrome.tabs.getCurrent(tab => {
    chrome.tabs.update(tab.id, { pinned: !tab.pinned })
})
```
    
- Actual result:
The tab is not pinned.

- Expected result:
The tab's `pinned` state should toggle.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues: #7440

**Comment by jonathansampson** [comment]
Duping to #6790

**Comment by bbondy** [comment]
when duping please remove milestone, thanks
