### ISSUE TITLE
RECAPTCHA failure

### ISSUE THREAD

**Issue by psmalone** [brave/browser-laptop#7445]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

On an e-mail list subscription page, I satisfy the ReCaptcha. Selecting "subscribe" results in "reCAPTCHA verification failed, please try again."

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X El Capitan

- Brave Version (revision SHA):

0.13.4 (71d8ffc)

- Steps to reproduce:
    1. Go to https://storybundle.com/email_subscriptions/new
    2. Enter an e-mail address
    3. Select "I'm not a robot"
    4. Complete the task
    5. Select "Subscribe"
    
- Actual result:

Alert: "reCAPTCHA verification failed, please try again."

- Expected result:

Confirmation of subscription

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Unknown. Does reproduce after a restart. Works fine in Chrome.

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

![screenshot 2017-03-02 08 39 43](https://cloud.githubusercontent.com/assets/23506653/23509451/d4627f84-ff23-11e6-85ce-ffe6427bfa5d.png)

- Any related issues:

**Comment by lukemulks** [comment]
We were able to confirm this across both Windows and MacOSX today. 

Going to bundle this issue with https://github.com/brave/browser-laptop/issues/7756 and track and investigate from there.
