### ISSUE TITLE
URL bar becomes inaccessible after enabling payments

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7447]
## Test plan

* Clear `session-store` and `ledger-synopsis` file
* Enable payments, wait till the payments menu is opened
* Open a new tab by clicking on the + button
* New tab should open immediately
* URL bar should be accessible

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
URL bar becomes inaccessible after enabling payments

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	0e68342

- Steps to reproduce:
    1. Do a clean install of 0.13.5 RC1
    2. Enable payments, wait till the payments menu is opened
    3. Open a new tab by clicking on the <kbd>+</kbd> button
    4. New tab is not immediately opened
    5. URL bar is inaccessible
    6. Close and reopen browser, becomes white screen and inaccessible 
    
- Actual result:
URL bar becomes inaccessible after enabling payments

- Expected result:
Browser functionality should be normal after enabling payments

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![missingurl](https://cloud.githubusercontent.com/assets/17010094/23511770/35cc732e-ff56-11e6-9197-f0792a94f96f.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Sounds related to https://github.com/brave/browser-laptop/pull/7439, assigning @cezaraugusto
