### ISSUE TITLE
Unable to open Browser Console (Shift+F8)

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7448]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Unable to open Browser Console (Shift+F8)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	0e68342

- Steps to reproduce:
    1. Do a clean install of 0.13.5 RC1
    2. Press <kbd>Shift</kbd>+<kbd>F8</kbd>
    3. Browser console is not opened
    
- Actual result:
Browser console is not opened

- Expected result:
Should open browser console when keyboard shorcut is pressed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![devconsole](https://cloud.githubusercontent.com/assets/17010094/23512091/5f238680-ff57-11e6-98a7-0af4d44a7fcf.gif)

- Any related issues:

**Comment by NejcZdovc** [comment]
I tried it on macOS with the latest version from the master c198994 and it's working correctly. Will try with windows now

**Comment by NejcZdovc** [comment]
Tested on a windows VM and it's working correctly

![image](https://cloud.githubusercontent.com/assets/9574457/23524513/48a8f582-ff8b-11e6-919b-8c64f1b2784e.png)

cc @bsclifton can you try it out?

**Comment by NejcZdovc** [comment]
@srirambv can you try with the current master version?

**Comment by bsclifton** [comment]
Removed blocker label, since the electron/Muon devtools aren't needed (the content dev tools still work fine, right?). Also moved to 0.13.6

**Comment by srirambv** [comment]
@NejcZdovc Works when I build off master. Not on the RC build.

**Comment by srirambv** [comment]
@bsclifton Yes dev tools works just not browser console.

**Comment by bsclifton** [comment]
was able to repro on 0.13.5, RC2

**Comment by bsclifton** [comment]
Not able to repro on completely fresh `npm install` on that same box with latest from master 🤔

**Comment by NejcZdovc** [comment]
@bsclifton @srirambv can you try it out with the latest 0.13.5 RC3?

**Comment by srirambv** [comment]
@NejcZdovc  Not working on 0.13.5 RC3 as well.

**Comment by NejcZdovc** [comment]
I think this is not working with a packaged version, it's working with a dev master.

**Comment by bsclifton** [comment]
Not a show stopper; moving to 0.13.7 (needs more investigation)

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/5a889ccd6198906537f0c29d4b28067292a4ef78
