### ISSUE TITLE
Pocket was translated when it should not.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7450]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
On the about:preferences#advanced page, it was discovered that 'Pocket' was translated.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.5 rc 1

- Steps to reproduce:
    1. Change your language to something other than English (I chose Chinese)
    2. Visit about:preferences#advanced
    3. Observe the final toggle
    
- Actual result:
Pocket is translated.

- Expected result:
As a brand, it should not, just as we do not translate Widevine or Flash.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="427" alt="screen shot 2017-03-02 at 9 08 52 am" src="https://cloud.githubusercontent.com/assets/1434040/23513456/bce1316a-ff29-11e6-85e7-801dd6ddc304.png">

- Any related issues:

**Comment by Liunkae** [comment]
It seems that this is an issue specific to Chinese.

https://github.com/brave/browser-laptop/search?l=INI&q=Pocket&utf8=%E2%9C%93

Is there a way to leave a note in Transifex to not to translate Pocket?

**Comment by luixxiul** [comment]
In Chinese a foreign product name is often translated in Chinese characters (for example Microsoft is called "微软"). Still in this case, according to [this official page](https://help.getpocket.com/article/1070-e5b8b8e8a781-pocket-e997aee9a298) the name should not be translated. 

Leaving the note would help for a while but not the perfect solution as the note can be overlooked or ignored.

**Comment by bsclifton** [comment]
Moved to 0.13.7

**Comment by srirambv** [comment]
Its an issue with many other languages not just Chinese. I see pocket is translated in Bengali

**Comment by bsclifton** [comment]
Removing milestone. If we'd like to see this done soon (and assigned a milestone), let's find an owner please 😄

**Comment by Liunkae** [comment]
What can be done in `browser-laptop` to fix this problem?

**Comment by bsclifton** [comment]
@Liunkae can we use a token like `{{NAME}}` in the middle of the string?  For example:
`Enable {{NAME}}`

**Comment by luixxiul** [comment]
`Enable {{ExtentionName}}` would be a global solution.

**Comment by Liunkae** [comment]
PR: #8110

**Comment by bsclifton** [comment]
I specified `release-notes/exclude`, but please feel free to change back if this is something we'd like to include 😄
