### ISSUE TITLE
Performance : urlbar response is slow when searching across many bookmarks

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7453]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After importing a large number of bookmarks, the urlbar response becomes considerably slow. It was found that bookmarks suggestions was the controlling factor.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.5 (https://github.com/brave/browser-laptop/commit/0e683420964546ac26a8c2903ef871a35a6e71d8)

- Steps to reproduce:
    1. With a clean session, try to visit reddit.com, add a couple bookmarks
    2. Import a large number of bookmarks
    3. With a new tab, try to visit reddit.com
    
- Actual result:
The urlbar becomes considerably laggy.

- Expected result:
The urlbar should be at least as responsive as if the bookmarks were not there. That is, a user should not be penalized for trying to visit a domain root when they have bookmarks to deeper links.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

[2017-03-02 09-52-15.mp4.zip](https://github.com/brave/browser-laptop/files/814365/2017-03-02.09-52-15.mp4.zip)

- Any related issues:

**Comment by scottbroadway** [comment]
Agree -- I'm seeing this. Painful. 

0.13.5 rev 1db81cb on Windows x64

**Comment by Liunkae** [comment]
+1 from #6620.

**Comment by ayumi** [comment]
+1 #8643

**Comment by Liunkae** [comment]
Moving assignment from #8643.
