### ISSUE TITLE
Extension API: chrome.tabs.insertCSS

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7456]
https://developer.chrome.com/extensions/tabs#method-insertCSS

Blocks #8327, #9531

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bsclifton** [comment]
moving to 0.14.3

**Comment by carsonwright** [comment]
This is an api I regularly use, would love to see it come back to muon (electron on steroids, healthfully on steroids....)

**Comment by jonathansampson** [comment]
@kevinlawler We used to support this. The original commit which added it can be found here: https://github.com/brave/muon/commit/e214ce6bc407086346c03bfd0f2da5c4c7625f97.
