### ISSUE TITLE
Extension API: chrome.tabs.duplicate

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7458]
https://developer.chrome.com/extensions/tabs#method-duplicate

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Unable to duplicate tabs with `chrome.tabs.duplicate`.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.13.0

- Steps to reproduce:
    1. Call `chrome.tabs.duplicate(tabid)`, where `tabid` is a valid ID.
    2. Note _Unchecked runtime.lastError..._ message

The callback on `chrome.tabs.duplicate` is _optional_, and therefore no exception should be thrown. Complying with our implementation, however, still does not yield the expected results:

```js
chrome.tabs.duplicate(tabid, () => console.log(chrome.runtime.lastError)
```

Instead, the user is presented with _Access to extension API denied._
    
- Actual result:
No tabs are duplicated.

- Expected result:
The tab should be duplicated, and the callback should not be required.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
moving to 0.13.7

**Comment by bsclifton** [comment]
moving to 0.14.3

**Comment by kevinlawler** [comment]
It seems like in the complete case `duplicate` should preserve:

   * location
   * history
   * scroll state
   * ...

It should drop:

   * input values (eg, user edits to textarea)
   * ...

I haven't seen the complete list specified anywhere yet. This is what I have currently.

**Comment by jonathansampson** [comment]
Blocks Vimium (#9531)

**Comment by jonathansampson** [comment]
@kevinlawler Can we, for now, simply map this to the *Clone* behavior?
