### ISSUE TITLE
Recent commit breaks HTTP auth

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#7459]
I noticed recently that a particular site I visit for work was no longer letting me in. HTTP auth wasn't working, returning a 401 instead. I build Brave myself from source, so I decided to see if it worked in the official release. Sure enough, the (current) official release has no issues. I decided to dig in a bit, to see what had changed between the commit my Brave was built from and the official one.

`git bisect` to the rescue. It seems that HTTP auth was broken in this commit:

```
b923567af4a3c9b0f975b8889f418763e523dd77 is the first bad commit
commit b923567af4a3c9b0f975b8889f418763e523dd77
Author: bridiver <github@brianjohnson.cc>
Date:   Fri Feb 24 18:38:59 2017 -0700

    always run the callback
    probable fix for https://stats.brave.com/dashboard#crash/58b0925d29f4700011a478f5
    auditors @bbondy @jonathansampson

:040000 040000 ee5dbad71b957771bd56ca82d59000eea7798738 da5ed6bf1e4e27e7359c29a05f66f28bb7986ffb M	app
```

Sure enough, if I go one commit back from the offending commit, to  `db6cf283925084106abe95ba974078cfbb04c600`, I can login to the site just fine. Starting with `b923567af4a3c9b0f975b8889f418763e523dd77`, HTTP auth fails. I'm not sure why. The offending commit is very minimal: https://github.com/brave/browser-laptop/commit/b923567af4a3c9b0f975b8889f418763e523dd77

Still, from that commit until the most recent commit (currently, `c1989949755f66c85a4b43145180d4a5ebdbf15e`) HTTP auth fails. 

@bridiver is the author of the offending commit
@bbondy and @jonathansampson were auditors

**Comment by bridiver** [comment]
this worked correctly for the site I tested, but looking more closely I'm not sure how. Fixing now

**Comment by echosa** [comment]
Pulled latest and re-built brave. Can comfirm: the issue is fixed. :+1:
