### ISSUE TITLE
switch to uglify-js-harmony

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7461]
it seems more stable than using the harmony branch of uglifyjs2. see https://github.com/mishoo/UglifyJS2/issues/448#issuecomment-283030572. 

may solve @NejcZdovc's `SyntaxError: Unexpected token: name (ImmutableComponent) [./js/components/immutableComponent.js:7,6]` issue reported in Slack

**Comment by bbondy** [comment]
At some point I think they didn't have a package or it was needed because package didn't have latest, but seems not needed anymore. This is definitely better, thanks.
