### ISSUE TITLE
downloads should show origin

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7468]
## Test plan

https://github.com/brave/browser-laptop/pull/7755#issue-214879649

----

we should show the origin that a file is about to be downloaded from, and also address https://bugzilla.mozilla.org/show_bug.cgi?id=741050.

**Comment by bbondy** [comment]
++ would be great to review open and closed security bugs from other browsers to see how we can improve.

**Comment by alexwykoff** [comment]
<img width="1233" alt="screen shot 2017-04-21 at 8 02 51 pm" src="https://cloud.githubusercontent.com/assets/1434040/25300104/928061a4-26cd-11e7-88b1-ce6fa12c60a1.png">

This did not display as described on either the Downloads page or the status bar.

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/8215
