### ISSUE TITLE
New tab context menu is below mouse not adjacent.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7472]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When opening the context menu on the + for new tab, the context menu appeared below the mouse, not next to it like other context menus.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Discovered on OS X

- Brave Version (revision SHA):
0.13.5 (https://github.com/brave/browser-laptop/commit/71d8ffc7278a90b22b8617d37880787c1781e694)

- Steps to reproduce:
    1. Right click on the + for new tab.
    2. Observe the location of the context menu.
    
- Actual result:
The menu appears below the mouse.

- Expected result:
The top menu item should appear to the right of the mouse.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![context_menu_placement](https://cloud.githubusercontent.com/assets/1434040/23539976/1c367dda-ffa4-11e6-94fc-21863847d5ab.gif)

- Any related issues:

**Comment by Liunkae** [comment]
This can be adjusted here: https://github.com/brave/browser-laptop/blob/master/js/contextMenus.js#L1304

**Comment by bsclifton** [comment]
This is different on purpose- it mimics the positioning seen in kabob (formerly known as 🍔 ).  The menu being shown is also a custom created control versus the native context menu shown.  This also happens for the back/forward nav buttons (when you do a long press or right click) and also the refresh button.

I'll close for now, but you can discuss with @bradleyrichter if you think it makes sense to reopen
