### ISSUE TITLE
Pocket Icon appears to have regressed in about:extensions

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7474]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pocket Icon appears to have regressed in about:extensions

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	1db81cb

- Steps to reproduce:
    1. Enable Pocket from advance settings
    2. Open about:extnsions after Pocket widget shows up
    3. Icon in the about page is different from the Widget 
    
- Actual result:
Pocket icon in the about page is different from the Widget 

- Expected result:
Should be same 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23548116/efa019de-fffd-11e6-8766-d451d8590af2.png)

- Any related issues:
#7436 
cc: @alexwykoff @jonathansampson

**Comment by luixxiul** [comment]
Is this in fact not intentional?
