### ISSUE TITLE
Menu bar ignors "Hide the menu bar by default"-Setting

### ISSUE THREAD

**Issue by AndHell** [brave/browser-laptop#7475]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Menu bar is shown after setting "Hide the menu bar by default" after restarting Brave
- Platform (Win7, 8, 10? macOS? Linux distro?):
tested on Ubuntu 16.10 with KDE and Ubuntu 16.04 with Xfce  
- Brave Version (revision SHA):
Brave	0.13.2
rev	25b1199
- Steps to reproduce:
    1. enable "Hide the menu bar by default"-Setting
    2. Close Brave
    3. Open Brace
    
- Actual result:
Menu bar is shown
- Expected result:
Menu bar is hidden

**Comment by srirambv** [comment]
Same a  #5086. Closing as dupe
