### ISSUE TITLE
Use 1px trasnparent image for image blocking

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#748]
macworld.com and possibly other sites don't work properly when the images are blocked.

Using a 1px transparent image is cleaner and also we can remove some preload script which hides the canceled images.   So net it should be faster.

See details here:
https://github.com/SergeyZhukovsky/tracking-protection/issues/5

This requires us to do some refactoring so that onBeforeRequest from HTTPS everywhere is moved into filtering.js.  

And then the blocking needs to be done inside onBeforeRequest instead of session.webRequest.onBeforeSendHeaders so that a redirect URL can be used.

CC @diracdeltas

**Comment by diracdeltas** [comment]
How would we know which resources to redirect to a transparent pixel? By the file extension?

**Comment by bbondy** [comment]
no webRequest tells you the resource type, so it knows when it is an image already.
