### ISSUE TITLE
CSP referrer directive is deprecated

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7483]
console in about: pages shows `Unrecognized Content-Security-Policy directive 'referrer'.`

**Comment by darkdh** [comment]
https://github.com/brave/browser-laptop/commit/8294031cdd47de975be6ac53fe6701c57da6c574

**Comment by diracdeltas** [comment]
actually this appears to be coming from the Coinbase buy widget, not us. Closing.
