### ISSUE TITLE
Update Interface is Confusing

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#749]
When Brave detects a newer available version, it reveals a bar ([updateBar.js](https://github.com/brave/browser-laptop/blob/5d8a266c1824505e5221f3aa2d7ecdf7681de6ac/js/components/updateBar.js)) at the top of the viewport:

![image](https://cloud.githubusercontent.com/assets/815158/13017423/fa0d1534-d178-11e5-8616-df49de974f46.png)

This bar *appears* responsive, in layout and content (content is being clipped; see [updateBar.less](https://github.com/brave/browser-laptop/blob/e008a788c9d6256d04897bb5725a6018e68ea493/less/updateBar.less)). As it is resized, the labels on the buttons to the far-right are adjusted. "Update Now" becomes "Update," "Update Later" becomes "Update," (though a narrowing window visually reverts the change) and "Details" remains unchanged.

![braveupdate](https://cloud.githubusercontent.com/assets/815158/13017440/107145de-d179-11e5-8cdf-283fd5c85c2a.gif)

The confusion here is in the [distinctively different behavior of the two "Update" buttons](https://github.com/brave/browser-laptop/blob/5d8a266c1824505e5221f3aa2d7ecdf7681de6ac/js/components/updateBar.js#L90). One will postpone the update, effectively doing nothing immediate (aside from hiding the bar). The other will restart the browser.

To avoid this confusion, I propose [different labels](https://github.com/brave/browser-laptop/blob/d8dd2178054a86353bbf8679663ea102cd360269/app/locales/en-US/app.l20n#L66) in the collapsed state:

- "update now" becomes "restart" and
- "update later" becomes "ignore"

These would communicate more clearly the function and immediate impact of each button.

**Comment by bradleyrichter** [comment]
thanks @jonathansampson. Excellent find...

We wanted to use update later as the equivalent of "remind me".

How about:

    "update now" stays as "update now" and should be acceptably responsive as it collapses to "update"

    "update later" becomes "later", and never collapses.



- Brad

**Comment by jonathansampson** [comment]
@bradleyrichter Those seem like fine alternatives.

**Comment by bradleyrichter** [comment]
Great...

@aekeus Let's update the updater button text as mentioned above to solve this one.



Thanks - Brad

**Comment by bbondy** [comment]
Changeset that was just landed was to rename update later to just later whether it is a big window or small, that is what was wanted right?

**Comment by aekeus** [comment]
Correct, that will allow the buttons to have different text ('later' and 'update') at a compressed window width.
