### ISSUE TITLE
Brave Payments for iOS

### ISSUE THREAD

**Issue by Dog2puppy** [brave/browser-laptop#7490]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
It isn't a issue. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
iOS
- Brave Version (revision SHA):

- Steps to reproduce:
    1.Search for the brave Payments area in settings
    2.Cant find it
    
- Actual result:
Can't find it
- Expected result:
Find it
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
@Dog2puppy: Brave for iOS has a separate repository: https://github.com/brave/browser-ios/issues. Please file the issue there. Thanks!
