### ISSUE TITLE
Keyboard Shortcuts Not Working

### ISSUE THREAD

**Issue by aptronym238** [brave/browser-laptop#7491]
- Did you search for similar issues before submitting this one?
Yes.
- Describe the issue you encountered:
After the latest update (0.13.5, Windows 7, 32-bit), several keyboard shortcuts I use regularly have stopped working.  Ctrl+PgUp/PgDwn no longer cycles tabs.  Ctrl+1/2/3/etc. no longer jumps to tabs.  Alt+Left/Right no longer steps backwards or forwards in tab history.  Most other shortcuts appear to be unaffected, including Ctrl+Tab/Ctrl+Shift+Tab.
My other computer running the previous version of Brave (0.13.4, Windows 10, 64-bit) had these shortcuts working normally.  I upgraded to 0.13.5 to check, and they stopped working, just like on my Windows 7 machine.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7, 32-bit; Windows 10, 64-bit
- Brave Version (revision SHA):
Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
- Steps to reproduce:
    1. Open Brave and multiple tabs.
    2. Try navigating between the tabs with Ctrl+PgUp/PgDwn or Ctrl+1/2/3/etc.
    3. Try stepping forwards or backwards in a tab's history with Alt+Left/Right. 
- Actual result:
Nothing happens.
- Expected result:
Previous behavior for these shortcuts: cycle active tab, jump to tab, or navigate tab history.

**Comment by EPadronU** [comment]
Same for me.

Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.15-1 
os.arch: x64

**Comment by gnchapman** [comment]
Same - just noticed this morning as I upgraded to 0.13.5:

Brave: 0.13.5
rev: 1db81cb
Muon: 2.56.8
libchromiumcontent: 56.0.2924.87
V8: 5.6.326.50
Node.js: 7.4.0
Update Channel: dev
os.platform: win32
os.release: 10.0.14393
os.arch: x64

**Comment by Liunkae** [comment]
+1 from #7509.

**Comment by MarioMaster100** [comment]
Oddly F11 and F12 are fine.

**Comment by mrpapercut** [comment]
F5 for Page Refresh also doesn't work (and Shift-F5 but not sure if that ever worked)
CTRL-U for View Page Source wasn't working for a longer time

Same versions as mentioned earlier

**Comment by scottbroadway** [comment]
Same for me. Don't want to go back to Chrome for this sort of basic feature. 

Brave	0.13.5
rev	1db81cb
Muon	2.56.8
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	10.0.10586
os.arch	x64

**Comment by bsclifton** [comment]
+1 from https://twitter.com/Dorrinal/status/840981395950383104

**Comment by luixxiul** [comment]
Also: https://twitter.com/RenanSDO/status/840976462698151936

> I can not use keyboard shortcuts to change sheets anymore, such as Ctrl+PageDown. Using the newest version, already reinstall x times

**Comment by tazcob** [comment]
Same here.

As an user that uses more keyboard than mouse, being unable to alternate tabs, scroll down using Page:Up/Down is pretty annoying.

Brave: 0.13.5
V8: 5.6.326.50
Node.js: 7.4.0
Update Channel: dev
os.platform: Windows 7
os.arch: x64

**Comment by bsclifton** [comment]
I can confirm this did work in 0.13.4 and stopped working with 0.13.5.  Narrowing down the issue right now. Stay tuned...

**Comment by Liunkae** [comment]
@bsclifton Could it be https://github.com/brave/muon/commit/fe02ce35902f7ad0799f4d3ac17e20739e3a4ee4 (debounce tab update events)?

**Comment by bsclifton** [comment]
Narrowed it down- functionality was working with https://github.com/brave/browser-laptop/commit/7373a0197df9fbacc0fb83c5f7494be1fe0ae879 but then stopped working with https://github.com/brave/browser-laptop/commit/0e683420964546ac26a8c2903ef871a35a6e71d8

**Comment by bsclifton** [comment]
[This commit](https://github.com/brave/browser-laptop/commit/6d722101025835ee4c92403901ee6d2cfe2fedde) appears to have broken it... but on Windows only

**Comment by bsclifton** [comment]
Found it! Fixed with https://github.com/brave/browser-laptop/commit/5a889ccd6198906537f0c29d4b28067292a4ef78 😄

**Comment by lXbalanque** [comment]
What can I do to fix this now?

**Comment by bsclifton** [comment]
@lXbalanque you can try one of our preview releases, available here:
https://github.com/brave/browser-laptop/releases/tag/v0.14.0dev-Preview1

I'd welcome anyone to try it 😄   You'll also notice the facelift we've given the UI (curious about your thoughts on that too).  Please let me know if this resolves your issue

**Comment by lXbalanque** [comment]
That fixed the keyboard shortcuts! Awesome. 

I just started using Brave so I will let you know my thoughts on UI/UX. One thing I noticed after importing my favorites from Chrome is that the icons didn't transfer over. It's a minor thing I'm sure is on the list of other million things to do. 

One of the bigger things I noticed right now is the inability to pull a tab out to make it it's own new window. Is that in the near future? I tend to do that a lot with Chrome and it would make the transition a bit easier. Will continue to provide feedback. Is there a thread where you would like all of the feedback to go?

**Comment by bsclifton** [comment]
@lXbalanque the favicons not loading was something we fixed in October... so if you've had it happen recently, we should re-open (or at least comment in) https://github.com/brave/browser-laptop/issues/4882 cc: @darkdh 

Being able to pull the tabs off (we call it "Tear off tabs") is being worked on right now by @bbondy 😄   He's got things mostly complete and is sorting out the final bugs (some which are complex).  We don't expect our next release to have this, but it may be available in 2 or 3 releases (0.14.1 or 0.14.2 would be the version numbers to keep an eye out for)

As for the feedback, we have a great site up that we'd love to hear from you on- https://community.brave.com.  Should be relatively easy to sign up and get started. Thanks for taking the time to try the release and also leave feedback here, I definitely appreciate your time 😄

**Comment by Liunkae** [comment]
@lXbalanque Also make sure you have favicons turned on in Preferences:
![image](https://cloud.githubusercontent.com/assets/19424103/23931162/c4e2a82e-08fe-11e7-82df-6bf18da926df.png)

**Comment by retrocausal** [comment]
```
 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.13.0-31-generic 
OS Architecture: x64```

`ctrl`+`shift`+`R` 
does nothing absolutely.
have to forcibly click the nav bar and hit `enter` for a clean reload

**Comment by kelna** [comment]
Ctrl+W sometimes works, sometimes doesn't. What I noticed is that it works after launch, then it stops working on some tabs, then on every tab.
 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by skrish13** [comment]
alt-left/right not working in linux for previous history pages

**Comment by Valkhir** [comment]
Same here: alt-left/right not working on Linux
Ubuntu 16.04 LTS
brave/xenial,now 0.22.727-1 amd64
