### ISSUE TITLE
"Language" shouldn't be localized

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#7499]
- Did you search for similar issues before submitting this one?
no

- Describe the issue you encountered:
In the preferences the "Language *" string shouldn't be localized, because once you've selected your language, you don't have to change this option ever again and more importantly, in case you have selected something like chinese by accident and want to find the language selection optionmenu, you might have a hard time.
![language](https://cloud.githubusercontent.com/assets/20467351/23581830/20a27cb4-011d-11e7-93a9-c277836264e5.png)

**Comment by luixxiul** [comment]
I think this would not longer be the issue once https://github.com/brave/muon/issues/133 is implemented.

**Comment by Zuzu-Typ** [comment]
I disagree.
I would even say that it's even more important.
Imagine your PC's language is set to a one you don't know so well, e.g. because your in Japan and didn't bring your own PC.
I do not know what language means in Japanese.

Also in which case does it make sense to have the string localized?

You could also have a little flag of the country / language instead of a word to bypass the issue - if you can see one in the upper example.

**Comment by bsclifton** [comment]
This is a great issue- I switched to Russian for testing a minute ago and had a really hard time switching back.

Here's my proposal:
We should show the language:
- as it would be translated for the current locale
- in its native form 

For example, when you are using ENGLISH locale, the drop down would look like this:

- English (English)
- German (Deutsch)
- Japanese (日本語)
- Spanish (Español)

I don't believe the country is required (ex: does it need to say U.S. next to English?)... but it doesn't hurt having it either.  In that case, an example may look like this:

- English (English, U.S.)
- German (Deutsch, Deutschland)
- Japanese (日本語)
- Spanish (Español, MEX)

**Comment by luixxiul** [comment]
I thought the style on wikipedia worked (show the name of the language in the same language); unless you know the language, you would not switch the setting to it.

**Comment by bsclifton** [comment]
@luixxiul the wikipedia style is not bad- however, that style is not currently respected by our preferences

I think there are two use-cases for showing language in its native script (like wikipedia)
- multiple people use a computer and may browse in different languages
- language may be chosen on accident

I like the approach of going a step further and also showing the language in the current locale (which is what we currently do in Brave).

Here's a screen cap from macOS where you can pick the language:
![screen shot 2017-03-12 at 10 52 57 pm](https://cloud.githubusercontent.com/assets/4733304/23843112/bbc88954-0776-11e7-9910-c9bf1e95b98b.png)

And here is Windows 10:
![screen shot 2017-03-12 at 10 54 33 pm](https://cloud.githubusercontent.com/assets/4733304/23843131/ef29b818-0776-11e7-8a8c-67930f00bf86.png)

**Comment by Liunkae** [comment]
Related: #1747 (language list sorting)
