### ISSUE TITLE
Bad phrasing around "Full Screen Content"

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#7503]
- Did you search for similar issues before submitting this one?
no

- Describe the issue you encountered:
In the _Preferences_ in _Security_ there is a rather new option entitled _Full Screen Content_, where you can select either _Always ask_ or _Always allow_.

Now while _Always allow_ makes sense, _Always ask_ doesn't.

![full screen content](https://cloud.githubusercontent.com/assets/20467351/23587460/d64a8900-01ac-11e7-9ab0-3cdc9ae7b35c.png)

Something like "Allow sites to switch to fullscreen" with the options "Yes", "Ask me first" and "No" would make far more sense.

The main reason why I'm having a problem with this is that I cannot translate it to German as it is, without it sounding weird or causing confusion.

**Comment by Liunkae** [comment]
@Zuzu-Typ: I like your suggestion to change the wording. It would make the setting easier for users to understand and easier for translators to translate!

**Comment by bsclifton** [comment]
This could be changed to a toggle switch, similar to other controls in preferences

It was left as a dropdown because we could put other options in the list

cc: @bradleyrichter, @cezaraugusto

**Comment by Zuzu-Typ** [comment]
Make sure though, that the user can understand what the setting changes, as 
  _Full Screen Content on/askme/off_
might not be self explanatory.

I would suggest something like
_Allow websites to display full screen content yes/askme/no_
or maybe
_Ask before allowing websites..._
_to display full screen content_ [ ] _never allow_
_open a new tab_ [ ] _never allow_
_[...]_

**Comment by cezaraugusto** [comment]
I don't have a strong opinion about this so if doing different helps translators/users I'm ok. 
/cc @bradleyrichter
