### ISSUE TITLE
[Linux] raw build without autoupdate?

### ISSUE THREAD

**Issue by AngryPenguinPL** [brave/browser-laptop#7504]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:

When download Raw Linux build and check if new update is available I see only "Not Yet. Sorry, there are no updates yet"

- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux raw build on both Ubuntu 16.10 x64 and Linux Mageia 5x64 (rpm based).

- Brave Version (revision SHA):

Brave	0.13.4
rev	71d8ffc

- Steps to reproduce:
    1.  Download not latest breve build for Linux from raw binary for e.g. 0.13.4
    2. Start it aand try check if is update to latest build 0.13.5.
    3. You see only "Not Yet. Sorry, there are no updates yet".
    4. Build for .deb or .rpm have autoupdate via system repository. But If we can't add this repository to system, we can't use autoupdate and in some rpm distro we have missing dependencies and only hope for running Brave is use RAW build but look like it not have autoupdate function.

Could you add autoupdate to raw build like is on Firefox?

**Comment by Liunkae** [comment]
@AngryPenguinPL: Thanks for the report. Plans to implement automatic updates on Linux are being tracked in #1470; please continue to track the progress of this improvement there. Closing as a duplicate.
