### ISSUE TITLE
[Linux] Flash player not detected

### ISSUE THREAD

**Issue by AngryPenguinPL** [brave/browser-laptop#7505]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:

When we use pepperflashplugin-nonfree, flash plugin is loaded but when we use other pack for example official Adobe build or build from ubuntu repository - brave not see flash pluing...

- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux Ubuntu 16.10 x64

- Brave Version (revision SHA):

Brave	0.13.5
rev	1db81cb

- Steps to reproduce:
    1. Download PPAPI Flash plugin from Adobe site (letest build 24.0.0.221) or download pack from Ubuntu repository or other for eg. adobe-flashplugin (it have bundled both flash - one PPAPI for Chrome based brower and second NPAPI for Firefox - both letest build 24.0.0.221).
    2. After installed it, check if Brave see this plugin. Look like brave looking only in dir /usr/lib/pepperflashplugin-nonfree/ and official adobe pack or few other "new flash pack" storage library in other dir like:
/usr/lib/adobe-flashplugin
/usr/lib/adobe-flashplugin/libflashplayer.so
/usr/lib/adobe-flashplugin/libpepflashplayer.so
/etc/chromium-browser
/usr/lib64/flash-plugin
/usr/lib64/flashplugin

and I think is also few more.
 

- Expected result:

So If you add few more dir to check by Brave, we can use other flash installer than old "pepperflashplugin". As you can see pepperflashplugin is plugin made sometimes ago and for have plugin it unpacking it from Chrome browser. Now we have fresh plugins without needed unpacking chrome. This plugins comes dircectly from Adobe site.
As you can see now adobe provides both npapi and ppapi plugin. They have archives tar,gz for npapi and ppapi and also rpm for npapi and ppapi and also YUM and APT (ubuntu) for both NPAPI and PPAPI in one installers!

So I think, you should have choise to use flash on brave. I think good options it adding new dir in brave. Brave should looking for a plug in few new locations OR you can add in about:preferences#plugins new options to manually indicate the right path for flash.

Why not?

**Comment by diracdeltas** [comment]
this is an easy bug to fix if someone wants to take it; just add more paths to https://github.com/brave/browser-laptop/blob/master/js/flash.js#L27-L41

**Comment by alexwykoff** [comment]
@diracdeltas I think the issue might be a bit more complex than that. I was able to reproduce the issue even with the files in the right place.

<img width="1712" alt="screen shot 2017-03-15 at 11 38 37 pm" src="https://cloud.githubusercontent.com/assets/1434040/23982058/ecef4a5e-09d8-11e7-9f0a-3c00caed9ed5.png">

This is currently blocking verification of https://github.com/brave/browser-laptop/issues/7523 for Linux.

**Comment by diracdeltas** [comment]
@alexwykoff did you first make sure that Flash was enabled in about:preferences?

**Comment by alexwykoff** [comment]
in the linux case, the preference could not be enabled because flash was not being detected. this was even after close, reopen and system restart & open.

**Comment by diracdeltas** [comment]
@alexwykoff you may need to change the permission on that directory so brave can read it?

**Comment by alexwykoff** [comment]
@diracdeltas It would seem to be on par with entries in /usr/lib

<img width="570" alt="screen shot 2017-03-17 at 9 47 29 am" src="https://cloud.githubusercontent.com/assets/1434040/24048409/cb827f48-0af6-11e7-8f0d-542863ae6af7.png">

**Comment by freebrowser1** [comment]
When it is just for displaying a video, Flash is not necessary anymore. Webkit browsers like Brave are able to play .mp4 (H.264) videos without plugin. The browser should ignore the request for a Flash plugin and play the video directly.

**Comment by AngryPenguinPL** [comment]
But... we still have many site with Flash. For e.g. my bank requires enabled flash in browser to work website. So without flash I can't make a transfer.

Also I know a lot of other website which still work in flash...

**Comment by bsclifton** [comment]
@freebrowser1 I believe our stance is: we want to have Flash completely disabled by default, but at least have support for it.  Similar to the Widevine CDM plugin: we don't encourage folks to enable... but offer support so that users can watch Netflix for example

I know a lot of us would be happy to completely dump Flash (for many reasons), but as @AngryPenguinPL (and other users) know, some sites haven't migrated away from Flash yet

IIRC, Brave does advertise itself as not supporting Flash... but will detect any requests and display those to the user with a notification prompt saying "This site is trying to use Flash. Allow?".  We do this so that it coaxes the site to play the video version (while still offering support for Flash)

**Comment by bbondy** [comment]
I can't get this to work on Ubuntu zesty either on http://www.homestarrunner.com/
It says could not load pepper plugin after allowing from the Flash placeholder menu.


Tried installing:
pepperflashplugin-nonfree package and enabling it in preferences.  The files it looks for seems to be there.

Also tried some alt things from @alexwykoff 
```
sudo apt-add-repository multiverse && sudo apt-get update
sudo apt-get install flashplugin-installer 
```


We might need to support his method instead? Also from @alexwykoff :
https://wiki.ubuntu.com/Chromium/Getting-Flash/
https://wiki.ubuntu.com/Chromium/Getting-Partner-Flash


CC @diracdeltas

**Comment by alexwykoff** [comment]
related issue : https://github.com/brave/browser-laptop/issues/6908

Trying this with the 0.15.0 rc6 yields the following:

```
[1:1:0426/223925.707644:ERROR:ppapi_thread.cc(333)] Failed to load Pepper module from /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so (error: /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so: cannot open shared object file: Operation not permitted)

test@test:~/BraveQA/0.15.0/rc6$ ls /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so 
/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
```

I'm inclined to believe there may be a permissions issue looming as well.

**Comment by alexwykoff** [comment]
confirmed still broken in 0.16.4 on Ubuntu

**Comment by monk-insane** [comment]
Have the same issue. 

Debian 9 Stretch X64
Brave Version 0.21.18

On flash site, getting "cannot load plugin".

Installed libpepflashplayer.so & manifest.json in /usr/lib/pepperflashplugin-nonfree/
Corrected permissions so the user the browser is running as can use the plugin, so the browser is detecting it is there since I can enable it in preferences.

Tried to watch something on crunchyroll.com, got "cannot load plugin".

**Comment by uchida** [comment]
It seems brave enables Linux sandbox before loading flash plugin shared library.
Launching brave with `LD_PRELOAD=/usr/lib/pepperflashplugin-nonfree` environment variable will work.
(`--no-sandbox` option also works, but not recommended)
