### ISSUE TITLE
a-ads.com - ads are displaying with shields up

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7507]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Community contributor reported ads on a-ads.com are getting beyond ad blocking shields. 

Community post: https://community.brave.com/t/a-ads-com-advertising-network-is-not-blocked/1529/5

Confirmed on windows10 - these ads appear to be presented as anonymous, but after looking at their privacy policy, it is noted that users could be deanonymized

https://a-ads.com/privacy_policy

Going to investigate and submit rules to block. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10 - but likely other OS's

- Brave Version (revision SHA):

Brave	0.13.5
rev	1db81cb

- Steps to reproduce:
    1. Go to a-ads.com with shields up
    2. Scroll mid-page
    3. See text or image ad
    
- Actual result:
![brave-a-ads com-blocking-03052017](https://cloud.githubusercontent.com/assets/8979240/23591895/e780b88e-01ac-11e7-9eae-bc7a645f60f2.png)

- Expected result:
No ads

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment]
Don't forget to add that I could not reproduce in Sweden 🇸🇪

**Comment by lukemulks** [comment]
I've investigated this further, and am going to close the issue. 

I've addressed and explained on the community thread: 
https://community.brave.com/t/a-ads-com-advertising-network-is-not-blocked/1529

In summary, the a-ads.com ads are displaying on the a-ads.com domain, but that is only because the a-ads.com ad network uses the same a-ads.com domain for the ads. 

We are blocking a-ads.com as a 3rd party network, so anywhere that a user places the ad tags outside of the a-ads.com domain, the ads will be blocked as expected. 

- **This is just a really rare case** of ad tags being generated from the same domain that is used for the tags that are externally placed on publisher sites, and displaying on the domain as a result: 
`1p-on-1p` =not blocked (expected behavior)

- **a-ads.com ads on other sites** are treated as `3p-on-1p` =are blocked (expected behavior)

- This is the filter rule we are using for blocking a-ads.com: `||a-ads.com^$third-party`

I've let the Community thread know that if a-ads.com ads are displayed on sites outside of the a-ads.com site, to let us know so we can re-open and investigate the issue. Going to close this issue in the meantime.

**Comment by arsenische** [comment]
Hi from a-ads!

> Confirmed on windows10 - these ads appear to be presented as anonymous, but after looking at their privacy policy, it is noted that users could be deanonymized

The mentioned Privacy policy is related to our main site, not to the ads being served. E. g. if you are a publisher and you create an ad unit and you specify your bitcoin address for withdrawals, then you (as a publisher of a-ads.com) may potentially be de-anonymized, e. g. your bitcoin address can be linked to your domain and your name. Same is true for advertisers.

But we don't spy on visitors, there is no Javascript neither cookies in our ads, you can check it yourself, e. g. https://ad.a-ads.com/1
