### ISSUE TITLE
Add support for Debian Stretch

### ISSUE THREAD

**Issue by DarkCoridor** [brave/browser-laptop#7508]
- Did you search for similar issues before submitting this one?

Yep. Didn't see anything.

- Describe the issue you encountered:

I tried to install the Linux package by adding a `deb` source via your instructions. It seems there is an error with your repo

- Platform (Debian 9 - Stretch):
- Brave Version (Brave 0.13.dev for Linux):

- Steps to reproduce:
    1. Follow [your instructions](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#debian-jessie-and-ubuntu-trusty-and-xenial-amd64)
    2. Upon running `sudo apt update` I see a warning which makes me not want to go further
    
- Actual result:

The warning

```
Reading package lists... Done
W: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/stretch/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

- Expected result:

That the Brave package is properly signed and can authenticate using your signing key.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

It should, yes.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?
 
Yes.

**Comment by epsilonPositive** [comment]
I'm also experiencing this issue. It would be nice for Stretch users to be able to automatically update Brave given the number of bugs affecting Brave on Stretch.

**Comment by nikolaiam** [comment]
Same here

**Comment by Liunkae** [comment]
Stretch is not supported (only Jessie, Trusty, Xenial, and Yakkety): https://github.com/brave/browser-laptop/blob/master/tools/upload_to_aptly See #6446 for details and a possible workaround.

**Comment by dillbyrne** [comment]
Stretch is now the stable version of debian as of the 17th of June. https://www.debian.org/releases/stretch/

**Comment by huuhaa** [comment]
@dillbyrne I hope they notice that before the end of the summer.. :/

**Comment by bsclifton** [comment]
@huuhaa @dillbyrne @DarkCoridor @nikolaiam @epsilonPositive can you all please try again? @Liunkae submitted a patch and I just ran the updated script 😄

**Comment by dillbyrne** [comment]
@bsclifton Working fine for me. Thanks to all involved :+1:

**Comment by huuhaa** [comment]
Yep working fine, thanks from me also! It happens too often that one forgets to came back and say thank you!
