### ISSUE TITLE
Save recovery file opens new tab

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7511]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you click on `Save recovery file...` in overlay `Backup your Brave wallet`, new tab is opened after save or cancel.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
72c0293
- Steps to reproduce:
    1. Go to payments and try to back your wallet
    2. Click on Save recovery file
    3. Click cancel
    4. New tab is opened with a content of the backup file
    
- Actual result:
New tab is opened
- Expected result:
New tab shouldn't be opened
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by bsclifton** [comment]
moving to 0.14.2

**Comment by alexwykoff** [comment]
Hey @bradleyrichter we need you to weigh in on this since I would say that it's fine to open a new tab. :)

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
