### ISSUE TITLE
Print recovery keys

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7512]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you click on print keys, you are redirected to new tab, but print dialog is not triggered
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
72c0293
- Steps to reproduce:
    1. Go to payments and try to back your wallet
    2. Click print keys
    3. New tab is opened, but no print dialog
    
- Actual result:
No print dialog
- Expected result:
Print dialog
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by bsclifton** [comment]
Not to be confused with the functionality which was fixed with https://github.com/brave/muon/commit/0ab197d0e587b709c79c4f27f37969a994464486; the issue being reported here is that the print dialog is never presented

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.6 https://github.com/brave/browser-laptop/commit/e6ff4ea43ed740d1449a4c72005e22ce5235447e
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
