### ISSUE TITLE
Add a "Processing" notifications when payments aren’t done

### ISSUE THREAD

**Issue by da2x** [brave/browser-laptop#7513]
I got the usual notification toolbar saying my contribution has been processed.

In about:preferences#payments my account balance hasn’t decreased at all, and my payment history doesn’t have anything for today. The status says that contribution is due in a month.

There is no trace of any contributions having being processed at all.

How about adding a “For whatever reason your payment hasn’t been fully processed or whatever so just hold your horses. We’re working on it.” message on the payment page? Ideally, my payment receipt should be ready and waiting before that toolbar notification is displayed, but a "Processing payment…" message would at least help.

Oh, it’s been **over an hour** since the notification appeared. Whatever is taking so long needs to be addressed as well. The user experience when Brave is collecting my money is pretty bad at this time.

0.13.5-dev

**Comment by da2x** [comment]
It’s almost eight hours since I got the notification about my payment being processed. Only just now was my account balance deducted. There is still no sign of a payment receipt.

**Comment by da2x** [comment]
More than a day later and no payment receipt. There really needs to be some kind of status indicator explaining what is going on when the process is this slow.

**Comment by da2x** [comment]
So that took **52 hours**.

The receipt now appears in my list, but if I click on it a new tab opens and closes immediately.

**Comment by NejcZdovc** [comment]
This problem with receipt opening should be fixed with version 0.13.6, #7416 for the reference.

**Comment by bsclifton** [comment]
moving to 0.14.2

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/12520
