### ISSUE TITLE
Brave irreponsive

### ISSUE THREAD

**Issue by khivi** [brave/browser-laptop#7516]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
After using Brave for few hours, when one opens a tab and types a new url it seems to hang.
Then brave is irresponsive and needs to be quit. (not force quit) 
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/1db81cb18b6919535792bb7e198ab87276bd67ea
- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by khivi** [comment]
[brave.txt](https://github.com/brave/browser-laptop/files/823290/brave.txt)

**Comment by aptronym238** [comment]
I just encountered the same issue on Windows 7, 32-bit with the same Brave build.  I had to restart the browser a few times and open a new tab through Help > About Brave to get it work properly again.  Now it seems to be fine.

**Comment by khivi** [comment]
On Mac if you the window and open a new window then one can continue working.
