### ISSUE TITLE
Support for HTML5 element <picture>

### ISSUE THREAD

**Issue by p-fernandez** [brave/browser-laptop#7517]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Brave it doesn't seem to render the HTML5 element picture. Found it currently developing a site with said element.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOSx 10.11.16

- Brave Version (revision SHA):
Brave	0.13.5
rev	1db81cb
Muon	2.56.8
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	darwin
os.release	15.6.0
os.arch	x64

- Steps to reproduce:
    Used this markup in React:

```
<div className={styles.image} style={this.props.customCss}>
   <a href={this.props.src} id={this.props.id} border="0" target="_blank" rel="noopener">
     <picture>
       <source srcSet={this.props.mobileImgSrc} media="(max-width: 760px)" />
       <source srcSet={this.props.imgSrc} />
       <img src={this.props.mobileImgSrc} border="0" alt="Fallback image" />
     </picture>
  </a>
</div>
```

- Can this issue be consistently reproduced?
Yes.

**Comment by jonathansampson** [comment]
@p-fernandez Can you provide a non-template example? Given that Brave is built on Blink, we should have no problem whatsoever rendering the picture element. It is, however, possible that we blocked the request(s) due to them being from a third-party. That isn't always the case though.

**Comment by p-fernandez** [comment]
I have upgraded to version 0.14.1 and I am having the same problem, being template or plain HTML.
You are right, the images are from a third-party, but I tested with another third-party images and they render properly.
Which are the conditions for requests to third-party images being blocked?

**Comment by jonathansampson** [comment]
@p-fernandez There are many factors at play; sometimes the headers being sent to/from the server may have an impact on whether or not the images are visible. Can you provide links to a working example, as well as a broken example?

**Comment by p-fernandez** [comment]
@jonathansampson the problem arose working with NSFW images provided by the company I worked with. I have set up a GitHub page with SFW images.

[https://p-fernandez.github.io/brave-html-picture-issue/](https://p-fernandez.github.io/brave-html-picture-issue/)

By setting the page up I gathered that it seems Brave is blocking it because content is not being served by https. Anyway, yesterday, replicating the problem in my localhost with http calls to files I got the same problem and no render. It makes me wonder if Brave, when rendering <picture> tag, blocks content from third-parties however it is called if third-party doesn't have proper certificates set. Also, it seems to not render the broken link icon when mixed content is blocked.

If you need more info, let me know.

**Comment by darkdh** [comment]
You can see the pic frame after allow ads and trackers. However, the source of the pic is 
https://www.hubtraffic.com/images/icons-sprite-horiz.png and it contains invalid common name in the certificate. You can directly navigate to the url and see the cert errors.
Also there was a console error related to this `icons-sprite-horiz.png Failed to load resource: net::ERR_INSECURE_RESPONSE`

cc @diracdeltas
