### ISSUE TITLE
Title loses its value when browsing a Medium article

### ISSUE THREAD

**Issue by jmalonzo** [brave/browser-laptop#752]
The title in the URL bar seems to disappear when I browse a Medium article[1]. It starts with the title populate but then it disappears after the window is ready.

[1] https://backchannel.com/our-medical-data-must-become-free-f6d533db6bed#.6akqmsnvo

**Comment by psimyn** [comment]
Looks like WINDOW_SET_LOCATION gets called multiple times

```
WindowConstants.WINDOW_SET_LOCATION
  action.location: https://backchannel.com/our-medical-data-must-become-free-f6d533db6bed#.rv8k4a7hd 
  lastLocation: https://backchannel.com/our-medical-data-must-become-free-f6d533db6bed#.6akqmsnvo
```

Might be safe to strip the # in the comparison here, I will have a test
