### ISSUE TITLE
'hide sites with <1% usage' should be default on in about:preferences#payments

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7520]
this would help make the page more manageable.

**Comment by mrose17** [comment]
oops! i thought i had it...

**Comment by alexwykoff** [comment]
While the toggle is correct, the action does not appear to manifest properly.

(See last pub % in ledger)
![categorizer_not_working](https://cloud.githubusercontent.com/assets/1434040/23982742/6e7a0948-09dd-11e7-863c-aee2dbaae71f.jpg)

**Comment by srirambv** [comment]
This is what I see when I manually edit the `ledger-synopsis.json`file. I think the condition is `hide < 1%` it should be more like `hide <=1%` that way the sites with 1% also gets hidden
![7520](https://cloud.githubusercontent.com/assets/17010094/23999437/4f8dec7a-0a50-11e7-976c-9564eab1f7ba.gif)

**Comment by diracdeltas** [comment]
the original issue was just for sites with less than 1, not less or equal to 1.
