### ISSUE TITLE
show notification for Flash elements that are too small for the placeholder

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7523]
maybe similar to the noscript icon, or just the regular notification bar

**Comment by srirambv** [comment]
I am still not able to see the small flash item mentioned in #4020.

**Comment by alexwykoff** [comment]
Currently on https://github.com/brave/browser-laptop/commit/77c562c3e8d1159e698e47a827a709939d0000b3 and was unable to get Brave to recognize Flash had been installed on Linux Mint.

Related issue : https://github.com/brave/browser-laptop/issues/7505

**Comment by diracdeltas** [comment]
@srirambv reverso.net actually has two different Flash issues, one of which is solved by #7549. when shields are down, you can actually see the Flash element which is very small

i'll fix the smallness problem but you will still need to lower shields.
