### ISSUE TITLE
onwatchseries.to - ads getting past shields

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7526]
- Did you search for similar issues before submitting this one?
Yes 
- Describe the issue you encountered:
Originally spotted by @srirambv onwatchseries.to has ads that are getting beyond shields

Example: 
![brave-onwatchseries to-ads-03072017](https://cloud.githubusercontent.com/assets/8979240/23683693/400e8abe-034f-11e7-9f63-e7c7a09dee93.PNG)

additionally - there are cases where the ads aren't displayed, but the links are active and open into new tabs 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10, but likely applies to all OS's 

- Brave Version (revision SHA):
1db81cb

- Steps to reproduce:
    1. With shields up, go to onwatchseries.to
    2. See ads (they have callouts - see screenshot above) 
    3.
    
- Actual result:
Ads
- Expected result:
No ads.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes 

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

- Needs investigation
- Needs repro on the new tab opening

**Comment by lukemulks** [comment]
cc: @srirambv

**Comment by bsclifton** [comment]
Appears to be fixed 😄
