### ISSUE TITLE
Add Vimium support

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7527]
This task is to add muon and browser-laptop support for Vimium.
This does not cover fixing missing functionality.

cc @jonathansampson

**Comment by bbondy** [comment]
https://github.com/brave/browser-laptop/commit/ce004b98024fd04e2efdc7273b302ecce87f13f4
https://github.com/brave/muon/commit/master

**Comment by bbondy** [comment]
btw the automated test will fail until we have new muon builds available.

**Comment by bsclifton** [comment]
marking as `release-notes/exclude` since it's currently disabled
