### ISSUE TITLE
Create term definitions for localization

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7531]
**Describe the issue you encountered:** Create (and maintain) a glossary on Wiki for volunteer translators to make it possible to translate the terms properly, even though they are not so familiar with the latest status of the browser and its development.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
For example, we need to give a nice definition to `Publisher` by ourselves.

**Comment by bsclifton** [comment]
@luixxiul I created a simple v1 of this page here:
https://github.com/brave/browser-laptop/wiki/Glossary

Please feel free to add more words which need defining 😄  Once we have enough content, we can update our localization docs

Marking issue as closed
