### ISSUE TITLE
When typing quickly in urlbar, keys are sometimes dropped.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7538]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This should be addressed by upcoming ReduxComponent work by @NejcZdovc and @bridiver 

moving to 0.14.3

**Comment by srirambv** [comment]
This is an issue on Windows 10 x64 for preview 3. Key press is not registered while typing URL even at normal speed

**Comment by srirambv** [comment]
Would like to move this to 0.15.3 as it would be a blocker

**Comment by bsclifton** [comment]
This should have been fixed with https://github.com/brave/browser-laptop/pull/8782
