### ISSUE TITLE
Investigation : Dev tools export network data 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7539]
Objective: Have Brave's Dev Tools export network traffic data in a `.csv` and/or `.json` format. 

_At a minimum_, we should match Chrome's `.har` export format capabilities.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All 

- Brave Version (revision SHA):
1db81cb

**Initial checklist:**
- [x] Show HAR capabilities and steps for the user in Chrome
- [x] Locate where the feature lives within the Chromium code
- [x] Link to an example of the HAR capture
- [x] Determine if HAR can be used in a similar way (import?) etc. 
- [x] Pros and cons of HAR

**Comment by lukemulks** [comment]
**Item: Show HAR capabilies and steps for user in Chrome**
Instructions to export the Network tab timeline to HAR from the Chrome Developer Tools:
- Select all the network traffic (`shift+click` with the mouse, or `cmd+a` on mac, or `ctrl+a` on PC)
- Right click on the network output and selecting `Save as HAR with Content`. 
![chrome-devtools-har-export-03072017](https://cloud.githubusercontent.com/assets/8979240/23717289/10b1cf8a-03e8-11e7-9c91-61a3b765c412.png)

**Example of HAR file** 
[chrome-dev-tools-brave.com-example-har.zip](https://github.com/brave/browser-laptop/files/828561/chrome-dev-tools-brave.com-example-har.zip)

Differences observed in Brave Dev Tools 
Select-all does not appear to work using cmd+a 
Right-click menu does not appear to work 
Both of the above work w/o issue in Chrome Dev Tools 

Enabling the right-click menu, and/or keyboard shortcut selections in dev tools in Brave may expose the options we need for the HAR export option to function as it does in Chrome.

**Comment by lukemulks** [comment]
**Item:  Locate where the feature lives within the Chromium code**

I've run a search through the Chromium code to determine where .har files are saved, and have narrowed in on the two following locations: 

**HARWriter.js**
**Chromium code search URL:** https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/network/HARWriter.js

**HAREntry.js**
**Chromium code search URL:** 
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/sdk/HAREntry.js

**Comment by lukemulks** [comment]
**Item: Link to an example of HAR file**
[chrome-dev-tools-brave.com-example-har.zip](https://github.com/brave/browser-laptop/files/829188/chrome-dev-tools-brave.com-example-har.zip)
v-tools-brave.com-example-har.zip

**Comment by lukemulks** [comment]
**Item: Determine if HAR can be used in a similar way to .csv or .json**

**I am able to:** 
- import HAR into Charles Proxy
- export a CSV file from Charles Proxy, from the HAR file that was imported

Note: If I can successfully do this from FF, it might be able to help with some recent issues with SSL traffic captures in FF that weren't previously experienced. Going to test this.  

Based on the info above, if exporting to .csv or .json was not possible or tangible, I could apply the above workaround to the same effect.

**Comment by lukemulks** [comment]
**Additional tool for importing HAR on the fly for inspection:** 

> **chromeHAR** online tool for drag/drop of HAR files 
> **GH Repo** https://github.com/ericduran/chromeHAR
> **Example of the Tool:** https://ericduran.github.io/chromeHAR/

**Comment by lukemulks** [comment]
**Item: Pros & Cons of HAR** 
**Pros:** 
HAR can import into Charles Proxy, and export to .csv, .json
HAR can export from Chrome, (brave - hopefully) and FF

**Cons:** 
- HAR files are large compared to .csv. 
For example, an HAR file generated from a page in FF was 2.6mb. The .csv file from the same session was 15kb in size. 

- For use in benchmarking, there doesn't appear to be a way to generate an HAR file from Safari. We could capture using Charles Proxy for these cases, but we will want to ensure that HTTP proxy captures from Charles Proxy align with HAR captures from dev tools in those cases. 

**Info on capturing HAR sessions from Browsers:** 
- **Chrome - Save as HAR** https://developers.google.com/web/tools/chrome-devtools/network-performance/reference
- **FF - save as HAR** https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#CopySave_All_As_HAR
- **Microsoft Edge - Generate HAR from MSFT Edge** https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/network

**Additional resources:** 
>**GSuite - HAR Analyzer** 
> https://toolbox.googleapps.com/apps/har_analyzer/
>**chromeHAR online tool for drag/drop of HAR files** 
> GH Repo https://github.com/ericduran/chromeHAR
> Example of the Tool: https://ericduran.github.io/chromeHAR/

**Comment by lukemulks** [comment]
@alexwykoff @luixxiul Key takeaways from the investigation:

**HAR - Browser Support**

- `Save as HAR` is available as a feature in Dev Tools for: Chrome, FF, Edge 
- `Save as HAR` does not appear to have native support within Safari. 

**`Save as HAR` option: Specific differences between Brave and Chrome in Dev Tools:** 
- **_Within dev tools, Chrome allows for the right click menu_** which contains the `Save as HAR` option. 
- Brave **does not allow the same right click behavior** within Dev Tools. 

- **_Chrome allows for_** the keyboard shortcut ctrl+a on PC and cmd+a on Mac OS to select all network request events in the Network tab. 
- **_Brave does not allow_** the same keyboard shortcut commands in Dev Tools

If the select all and right click options were available in Brave dev tools, this might resolve the issue. Just in case it doesn't, I've included links in the Chromium source code for HAR saving options. 

Charles Proxy supports importing HAR and exporting CSV from imported files as a workaround for a lack of .json and .csv export from the browser.

**Comment by bsclifton** [comment]
@lukemulks I'll capture your input in https://github.com/brave/browser-laptop/issues/6724 and mark this issue as closed 😄
