### ISSUE TITLE
make tab switching lightning fast

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7540]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Tab switching seems to be much better now- is this still an issue? @alexwykoff @bridiver

**Comment by bbondy** [comment]
some things we did recently will make this faster already, but things like redux components will also help.  I'll just push this along for now since it's being done incrementally.  We may just end up closing this because other issues track the work.

**Comment by bbondy** [comment]
I think this is covered with various perf work coming out in 0.15.1 (formerly called 0.14.3).  We can re-open if still an issue after that.
