### ISSUE TITLE
Remove vestigial style on empty divs

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7541]
Ad-blocking may, at times, result in empty and unsightly elements left in the user's view.

- Any related issues:
  - https://github.com/brave/browser-laptop/issues/7510 _Large translucent element obscures Washington Post content_

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by jonathansampson** [comment]
For now, we're addressing these types of issues by adding to the Brave manifest: https://github.com/brave/browser-laptop/blob/067ca562c976b3313df6ec337740e2179799c36d/app/extensions.js#L45

**Comment by bbondy** [comment]
duping to
https://github.com/brave/browser-laptop/issues/344
