### ISSUE TITLE
Header bar and tab styling.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/browser-laptop#7546]
Header styling based on:

![pasted image at 2017_02_20 02_39 pm](https://cloud.githubusercontent.com/assets/318119/23715572/fe79300c-03e1-11e7-9f9f-013a29afce7a.png)

**Comment by luixxiul** [comment]
Added `QA/no-qa-needed` as the issue was followed up with #7739, whose test plan is available in https://github.com/brave/browser-laptop/pull/7740#issue-214511262
