### ISSUE TITLE
Add sharing to social media sites (Facebook, twitter, etc.)

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7555]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
Related: #1988

**Comment by bsclifton** [comment]
Closing as a dupe of https://github.com/brave/browser-laptop/issues/1988

If I read this wrong, please re-open and add more information 😄  Thanks!

**Comment by Liunkae** [comment]
Actually, I think the sharing feature in this issue is cross-platform, like Firefox:
![image](https://cloud.githubusercontent.com/assets/19424103/24011774/b6c73272-0a49-11e7-8ef4-8c7ac851c629.png)
The share menu item in #1988 is macOS-only (see the screenshot I just posted there).
