### ISSUE TITLE
make http links more obvious to highlight their insecurity

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7559]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This functionality is really well done by [moarTLS](https://chrome.google.com/webstore/detail/moartls-analyzer/ldfbacdbackkjhclmhnjabngnppnkagh) by @ericlaw1979

Maybe we can offer this extension an option under advanced settings (similar to pocket)

cc: @bradleyrichter

**Comment by Liunkae** [comment]
Related: #1576 ("Block all HTTP" mode)

**Comment by tomlowenthal** [comment]
Perhaps it's worth thinking about HTTP/HTTPS link styling at some point down the line. brave/brave-browser#866
