### ISSUE TITLE
Right click doesn't work on Linux

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#756]
Using Brave Version: 0.7.14
Electron: 0.36.7
libchromiumcontent: 47.0.2526.110

and node 5.5.0

Right clicking on anything even the initial about:blank page doesn't produce a menu.

Win 10 equivalent version works fine.

**Comment by psimyn** [comment]
I had a similar issue raised, you can try clearing the cached version of electron-prebuilt

```
rm -rf ~/.electron
```

Related issue:
 https://github.com/brave/browser-laptop/issues/662

Hope that helps

**Comment by FrancisTurner** [comment]
@psimyn 
What version of electron-prebuilt should work? I've tried deletion at various levels of seriousness from your suggestion up to a reinstall from scratch of everything and it still doesn't work for me

**Comment by psimyn** [comment]
nvm, apparently no version will work at the moment - content scripts are broken. This means no context menus, preferences, and a bunch of other things

This should fixed when https://github.com/brave/browser-laptop/issues/743 is

**Comment by bbondy** [comment]
Content scripts are fixed now so closing this.  If you see this as a problem still please re-open though.

**Comment by atondwal** [comment]
This (and the related content scripts bug with preferences) is back for me in `0.9.0` using Arch Linux
```
Brave: 0.9.0
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 6.0.0-pre
Update channel: dev
```
This is with the `brave` package from the AUR. It works with the (older) `brave-bin` package:

```
Brave: 0.8.3
Electron: 0.37.3
libchromiumcontent: 49.0.2623.108
V8: 4.9.385.33
Node.js: 6.0.0-pre
Update channel: dev
```
