### ISSUE TITLE
Re-enable DAU and MAU stats on Linux

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7562]
## Test plan

https://github.com/brave/browser-laptop/pull/7651#issue-213478186

----

We should still do an update check, but change the messaging of the toolbar.  Since 0.12.1 we aren't getting new update pings unless the user checks manually:
https://github.com/brave/browser-laptop/commit/dcc4a8f1aa70c33313101b36b81db50cccaecf25

**Comment by bbondy** [comment]
@aekeus if you want a break from addfunds I'd appreciate the help on this one

**Comment by bbondy** [comment]
Keeping in mind if this was a crash we don't want to re-introduce it:
https://github.com/brave/browser-laptop/issues/3907

**Comment by aekeus** [comment]
Ok, thanks. Will do.

**Comment by aekeus** [comment]
I am going to break this up to two issues. The first will be re-enabling the ping to the updater service. The second will be the notification in the update bar that a new version is available.

**Comment by luixxiul** [comment]
@aekeus is it OK to close this thanks to #7651?

**Comment by aekeus** [comment]
@luixxiul yes, this issue is fixed with pull request #7651

**Comment by alexwykoff** [comment]
@aekeus I tried setting version to 0.13.3 in package.json and found the following after launch:

> brave@0.13.3 start /home/test/Development/browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

Crash reporting enabled
{ version: '0.13.5',
  name: 'Brave 0.13.5',
  pub_date: '2017-03-03T21:39:47.551Z',
  notes: 'Added sync between computers, suppressible per-tab alert and confirm message dialogs, preference page for plugins, fixed wallet recovery, and fixed various UI issues. More details: https://github.com/brave/browser-laptop/releases/tag/v0.13.5dev\n\nHotfix for a crash which could happen when loading an invalid URL. More details: https://github.com/brave/browser-laptop/releases/tag/v0.13.4dev',
  url: 'https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/0.13.5/linux64/Brave.tar.bz2' }

So it appears to be contacting the update server which the PR said should not be happening.

This was on SHA : 77c562c

**Comment by aekeus** [comment]
That is the correct behaviour. We need to contact the update server to record the statistic (the metadata is retrieved as a no-op side effect).
