### ISSUE TITLE
Alt+PrtSc key combination is not recognized by Brave

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7566]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing #7485 , it was found pressing <kbd>Alt</kbd> +<kbd>PrtSc</kbd>  and releasing the keys still enables the menu bar. <kbd>PtrSc</kbd> is not recognized by Brave which causes it to only to register pressing<kdb>Alt</kbd> which causes the menu to be shown
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/pull/7485/commits/c789de1b39f8835e110d3d111d38dd4574200137

- Steps to reproduce:
    1. Build from https://github.com/brave/browser-laptop/pull/7485/commits/c789de1b39f8835e110d3d111d38dd4574200137 branch
    2. Press  <kbd>Alt</kbd> +<kbd>PrtSc</kbd> and release the keys 
    3. Menu bar is activated
    
- Actual result:
Menu bar is activated when  <kbd>Alt</kbd> +<kbd>PrtSc</kbd> combination is pressed

- Expected result:
Should not show menu bar when  <kbd>Alt</kbd> +<kbd>PrtSc</kbd> combination is used

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#7485 
cc: @bsclifton

**Comment by luixxiul** [comment]
Note: on VirtualBox you will need to send the key combination via the main menu (input -> keyboard -> send alt printscreen).
