### ISSUE TITLE
Bug report - Tabs open from previous session get lost under certain conditions during next browser start

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#758]
1) If i have the browser open with some tabs from previous session and open a new browser window, the session is reset and next browser restart all open tabs are forgotten

2) If the browser crashes during start, all open tabs from last session are forgotten during next browser start

**Comment by bbondy** [comment]
I don't think #1 is a problem.  Could you confirm?
I think maybe because we aren't restoring the location of the last windows yet (we have a bug on file for that), it might appear that way. 

For #2 I think we can dupe to this:
https://github.com/brave/browser-laptop/issues/395


Please confirm about #1 and then we can close this if so.

**Comment by SJ-Diamond** [comment]
No, problem for 1 is exactly as i have written.

Steps to reproduce:
1) Open Browser, open a tab with example duckduckgo mainpage
2) Open additional New Window
3) Close New Window
4) Close Window with DuckduckGo Tab
5) Start Brave again
6) Tabs gone

**Comment by bbondy** [comment]
Thanks for the detailed steps. I think the way it works now is like Firefox but it seems like Chrome does as you say and keeps the tabs o the last closed window.  There's a distinction of quit (done with the whole program for now) and close window (done with the window) but probably most users would expect it to work like you said for the last window.

**Comment by riledhel** [comment]
I lost all tabs from previous session every time after browser restart. 0.7.15 on win7. I can help debugging but I don't know how to (yet).
