### ISSUE TITLE
Include a browser shield settings... option in the menu/shields sub category

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7590]

**Comment by NejcZdovc** [comment]
@jonathansampson is this the same as #6350?

**Comment by jonathansampson** [comment]
@NejcZdovc I'm not the author of the idea (I simply filed the issue), but I suspect the author would like to see a shortcut to about:preferences#shields from the Shields menu item. Presently, users only have a shortcut to their Brave Shields Panel, and the Brave Payments settings.

**Comment by luixxiul** [comment]
@jonathansampson I thought so too.

**Comment by bsclifton** [comment]
Closing as a dupe of https://github.com/brave/browser-laptop/issues/6350
