### ISSUE TITLE
Feature Request : Restore tabs

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7595]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
restoring tabs is possible already, maybe does this mean restoring *after* restarting the browser?

**Comment by bsclifton** [comment]
Closing; the feature is already there (reopen last closed tab/window).  If a scenario isn't covered or the intent was different, let's reopen and give more info 😄

**Comment by alexwykoff** [comment]
What this meant is to restore tabs in the case of a hard close / error. Similar to recovery in other browsers.

**Comment by bsclifton** [comment]
@alexwykoff ah ok- awesome

That is captured with Brave should restore session gracefully after a crash #5512 😄
