### ISSUE TITLE
Suggestion: Tab preview on hover off by default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7596]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
I love tab hover and I think most people would enjoy the default setting- I'm curious if some more people can chime in here

@bradleyrichter @bbondy @jamesmudgett @jhreis @cezaraugusto

**Comment by bradleyrichter** [comment]
It is absolutely a mostly-loved differentiator. We must be careful to not to return our special browser back to a chrome copy. 

That being said, I had an idea to add a toggle menu item to the tab context menu, at the bottom. Or add "Tab Settings..." which takes people to the tab prefs panel.

**Comment by cezaraugusto** [comment]
^^ I like Brad's idea, but something more direct like "enable/disable tab previews"

**Comment by srirambv** [comment]
I think tab hover preview should be kept on by default and once the tab set crosses 20 tabs it should turn off. Since the tab size becomes small the surface area for the mouse pointer reduces heavily which causes the pointer to be on the edge of two tabs and any slight movement might focus on the wrong tab

**Comment by jhreis** [comment]
I really like the current behavior, even with many tabs. When I go through my tabbing cleanse 😊, I love being able to just roll over each tab and hit my mouse middle button (which closes the tab). I actually use preview way more when I have tons of tabs. With more tabs you lose more context on the tab bar, so having preview is nice. If we did go this route though, I wouldn't complain though 😁

**Comment by jhreis** [comment]
As far as this general ticket. The preview behavior was a bit stark for me when I first started using Brave, but have now fell absolutely in love with it. If we had it off by default, I would probably have never enabled it, since it originally felt kind of odd. Since it was a default I figured I'd give it an honest shot, and haven't looked back.

**Comment by bsclifton** [comment]
I'm going to close this issue since we all agree it's a great default option... but I'd encourage folks to reply back / reopen and make their case 😄

**Comment by Jacalz** [comment]
I love the feature, it is a feature that puts Brave apart from other browsers so I think that it should be on by default 😄 It really saves time when doing work on multiple tabs 👍

**Comment by Boran** [comment]
FYI from my point of view, it is an amusing but confusing feature. I would suggest having it off by default.

**Comment by bsclifton** [comment]
With the new version of Brave, tab preview is no longer present. If we do eventually add it, it'll be an opt-in choice
