### ISSUE TITLE
Tab preview on hover doesn't work after closing tab until moving the mouse out of tabs bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7606]
## Test plan
See https://github.com/brave/browser-laptop/pull/8902

## Original issue description
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I noticed it as well, CC @NejcZdovc for thoughts

**Comment by NejcZdovc** [comment]
@luixxiul problem is that mouse event is not triggered when component update is done. We have two options:
* we add additional event `mouseOver` which will trigger preview as soon as you move mouse for a pixel (you don't need to move outside the tab bar, but you need to move mouse)
* we add a function that will be triggered when component updates and will check where is the pointer and if pointer is inside the component we manually trigger preview (you don't need to move mouse)

cc @bsclifton

**Comment by bbondy** [comment]
I think when a tab closes this might fire:
https://github.com/brave/browser-laptop/blob/master/js/stores/windowStore.js#L384
Making it clear the preview frame key.  I think we should just be smarter about what to show IF there is already a predview frame.
