### ISSUE TITLE
customizable pins on new tab page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7629]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/7159

**Comment by luixxiul** [comment]
There's a request on community: https://community.brave.com/t/more-control-over-top-sites-on-new-tab-homepage/429

**Comment by bsclifton** [comment]
There are a few issues which this duplicates;
- about:newtab - change view from thumbnail squares to list view #5303
- about:newtab - ability to customize top-sites area #5304
- Dashboard (about:newtab) - allow more tiles / pins #7742
