### ISSUE TITLE
with pinned tabs, new window duplicates all the pinned tabs

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7631]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
Same as #5800?

**Comment by bsclifton** [comment]
@Liunkae yup! good catch. We had punched in a pile of issues when we were all physically present at our first face to face. Many of these issues have dupes (ones we haven't looked at yet are tagged `needs-triage` if you wanted to help 😄 )
