### ISSUE TITLE
On disable switch make the text grayed out

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7634]
## Test plan
See https://github.com/brave/browser-laptop/pull/12455

## Original issue description
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Like this?

<img width="198" alt="screenshot 2017-03-08 16 41 27" src="https://cloud.githubusercontent.com/assets/3362943/23730756/1ba452d8-041e-11e7-9a85-313b0309de05.png">

**Comment by srirambv** [comment]
Yes

**Comment by luixxiul** [comment]
CC @bradleyrichter for a comment

**Comment by bradleyrichter** [comment]
yes please

**Comment by bsclifton** [comment]
Should be easy to do- here's where you'd want to edit:
https://github.com/brave/browser-laptop/blob/master/app/renderer/components/settings.js#L41

**Comment by bbondy** [comment]
When would the switch be disabled? 
This shouldn't be off state if that's what is meant.

**Comment by bsclifton** [comment]
@bradleyrichter would you want this grayed out when disabled? Or also when the switch is turned to off?

**Comment by NejcZdovc** [comment]
I would only grey out when checkbox is disabled

**Comment by bradleyrichter** [comment]
Correct. Only if a switch is disabled, not toggled off. I think we currently have few examples of this.

**Comment by bsclifton** [comment]
Moving to 0.13.7

**Comment by Liunkae** [comment]
Example in Preferences > Plugins:
![image](https://cloud.githubusercontent.com/assets/19424103/24076154/e9a97a06-0bf7-11e7-8dd6-d1d1f813f83b.png)
It looks like the shields panel already has this behavior:
![image](https://cloud.githubusercontent.com/assets/19424103/24076158/fb571100-0bf7-11e7-88ef-5ecc360b0d34.png)

**Comment by bsclifton** [comment]
Removing milestone

**Comment by chirag64** [comment]
I'd like to attempt a PR for this if no on else is working on it.

Is there any way to use the browser's Developer tools to debug the browser's UI? This would help me understand the code better and debug.

**Comment by luixxiul** [comment]
<kbd><kbd>Shift</kbd>+<kbd>F8</kbd></kbd> activates the devtool ;-)

**Comment by user512** [comment]
Attached a screenshot in the pull request as well, thank you for reviewing. 😄

**Comment by user512** [comment]
Attached a screenshot in the pull request as well, thank you for reviewing. 😄

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.11 6565c06
* Muon	7.1.0
* libchromiumcontent	67.0.3396.87
