### ISSUE TITLE
solve issue where black favicons on black tabs are invisible

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7635]
solution: use a webkit filter to add a glow around the image. (works on any shape)

![image](https://cloud.githubusercontent.com/assets/13509546/24530818/5740f66e-1569-11e7-99c6-79a260dc4b4c.png)

![image](https://cloud.githubusercontent.com/assets/13509546/24530828/631d47c6-1569-11e7-9d22-39fc9d685940.png)

![image](https://cloud.githubusercontent.com/assets/13509546/24530834/6a34a8ce-1569-11e7-9690-2c8ba9ad60f6.png)

code: -webkit-filter: drop-shadow(0px 0px 3px rgb(255, 255, 255));

**Comment by luixxiul** [comment]
I cannot remember well but @cezaraugusto has been notified this issue on github with a PR. Sorry if I'm worng

**Comment by cezaraugusto** [comment]
actually not solved yet but we can make use of CSS filters for this one

Sample: https://codepen.io/cezaraugusto/pen/QpvWzN

**Comment by bsclifton** [comment]
Moving to 0.14.3
