### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tysc** [brave/browser-laptop#764]
Windows 10 x64, installed, uninstalled, reinstalled multiple times. Still nothing.

**Comment by tysc** [comment]
Also, it just opens and I get the white window outline at the top and it kind of tints my screen black then closes. No task in taskmngr

**Comment by Charletg** [comment]
Same problem with windows 7 Entreprise SP1 x64

**Comment by tysc** [comment]
No update in 2 days ffs

**Comment by bbondy** [comment]
Could you try renaming this folder out of the way:
%appdata%\brave

and then start up again?

**Comment by Charletg** [comment]
I tried but same behaviour.

**Comment by bbondy** [comment]
@aekeus know how we can geta hold of this crash dump?

**Comment by aekeus** [comment]
I will investigate where the local crash files are stored in Windows.

**Comment by weems** [comment]
likely AppData folder, right @bbondy?

**Comment by bbondy** [comment]
I think it's likely somewhere in appdata, Aubrey will confirm where more specifically.

**Comment by tysc** [comment]
didnt work @bbondy (renaming %appdata% brave)

**Comment by bmaisonn** [comment]
Hi all,
I've encounters the same crash on windows 7 with version 0.7.16. I just see it open and close.
Tried to rename %appdata%\brave but it still crashes.
Strange because it worked fine before i close and stop my laptop.

**Comment by luixxiul** [comment]
Does this problem appear on the latest version too?

**Comment by luixxiul** [comment]
Should be fixed, closing for now. Please download the latest version and try again. If this error still exist please leave a comment to reopen this. Thanks.

**Comment by remillc** [comment]
Yes, the problem is still present on the latest version.
