### ISSUE TITLE
Allow dragging a bookmark from the bookmark manager into the toolbar

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#7640]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I was trying to reorder a bookmark and one of the methods I attempted was to drag and drop from the bookmark manager directly into the bookmarks toolbar, which works on Chrome.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS / Linux

- Brave Version (revision SHA):
7373a01

- Any related issues:
Possibly can be considered part of #6245 / #6246?

**Comment by Liunkae** [comment]
Also works with Firefox. Tagged for parity.

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/8067 (which has a much larger scope)
