### ISSUE TITLE
Add custom pinned site

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7644]
Ability to add custom pinned site. 
It's addition to the #7347 PR

When you click on Add, site is added, but dialog is not closed.
When you click on Done, dialog is closed and nothing is saved.

![pasted image at 2017_03_09 03_42 pm](https://cloud.githubusercontent.com/assets/9574457/23776176/e123c91c-052c-11e7-90b8-bfb7b561a204.png)

**Comment by mrose17** [comment]
i think this is a bad idea. when you pin a site because you've already gone there, we know (at least) that the URL is correct, etc.

second, what does it mean to pin a site that you never go to? that just seems... _odd_

@bradleyrichter - your thoughts?

**Comment by NejcZdovc** [comment]
@mrose17 This issue was created on @bradleyrichter request, he also provided mock for it

**Comment by mrose17** [comment]
@NejcZdovc - thanks. i _still_ think it's a bad idea, so i'm interested in hearing @bradleyrichter's thinking on this.

**Comment by bsclifton** [comment]
Assigning to @bradleyrichter so he can provide more info (or close issue if he agrees with @mrose17 )

**Comment by Liunkae** [comment]
What is the use case for this? We don't have this kind of functionality with bookmarks, for example.

**Comment by NejcZdovc** [comment]
@bsclifton I think this is already defined. We defined it on the last ledger call. This is how you add custom publishers to the ledger. This publishers are pinned by default.

**Comment by davidtemkin** [comment]
Where I could see this, or something similar, being very useful is if we were to provide a link to publishers/creators that, if viewed in Brave, would result in a dialog like this. Right now a publisher/creator who'd like to promote Brave (and seek contributions from Brave users) has to explain or link to an explanation of pinning (which despite our familiarity with it, is not exactly self-evident); and then instruct users to perform a set of manual steps.

**Comment by tomlowenthal** [comment]
@bsclifton Do we have this functionality in the new version, or is it "addressed" in the sense that it's probably no longer needed because other functionality covers all the applicable use cases?

**Comment by bsclifton** [comment]
@tomlowenthal I'm not sure of the specifics with Brave Rewards... but the entire system is overhauled. @NejcZdovc might know the answer offhand
