### ISSUE TITLE
Back/forward history menu not dismissed on back/forward click

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#7645]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If the back/forward history menu is visible, clicking the back or forward button does not dismiss it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (likely all)

- Brave Version (revision SHA):
0.13.5 (1db81cb)

- Steps to reproduce:
    1. Open a new tab and navigate to any page with a link.
    2. Click the link.
    3. Hold down on the back button to display the back history menu.
    4. Click the back button.
    
- Actual result:
The back history menu is not dismissed.

- Expected result:
The back history menu should be dismissed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I did not try.

- Is this an issue in the currently released version?
Yes, 0.13.5.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a new tab and navigate to any page with a link.
    2. Click the link.
    3. Hold down on the back button to display the back history menu.
    4. Click the back button.
    5. Make sure the back history menu is dismissed.

- Screenshot if needed:
Screencast:
![untitled](https://cloud.githubusercontent.com/assets/19424103/23782766/6cf58004-051c-11e7-8da8-94692c09c1f7.gif)

- Any related issues:
None.

**Comment by Liunkae** [comment]
Same thing with the refresh button and new tab button.

**Comment by bsclifton** [comment]
Fix would be similar to the one done for hamburger menu that @Hapcy implemented with https://github.com/brave/browser-laptop/pull/6405

**Comment by PatMB30** [comment]
Hi, I'd like to work on this issue. I've double checked what @bsclifton suggested looking into (#6405), and to make sure I understand i'd like to ask; should the back button's submenu disappear once the mouse moves away from the button or its submenu? Also, any hint on how to handle the mouse's position in regards to that would be appreciated.

**Comment by Liunkae** [comment]
@PatMB30
> should the back button's submenu disappear once the mouse moves away from the button or its submenu?

I haven't seen this behavior anywhere else. I just tried both Firefox and Safari, and the context menu stays visible wherever you move the mouse pointer. So I suggest that you keep the behavior consistent with other major browsers.

**Comment by PatMB30** [comment]
@Liunkae 
I've tested the behavior with Chrome and came to the same conclusion, thank you for your input though. I figure the best thing would be to have the back button's submenu disappear once the back button has been clicked once after having been long-pressed. I'm having difficulty figuring out how to close the back button's menu though.

**Comment by bsclifton** [comment]
Unless @PatMB30 wanted to fix this, I think we won't be able to address this issue.  However, it is fixed with Brave Core which is coming soon 😄 👍
