### ISSUE TITLE
Scaling issues at UHD (4K) resolution; window buttons and URL bar hitbox is too small when Brave is maximised

### ISSUE THREAD

**Issue by FauxPrada** [brave/browser-laptop#7648]
Please excuse any incorrect terminology, I'm unfamiliar with the correct words for certain items. 

- Did you search for similar issues before submitting this one?

Yes, via github and google

- Describe the issue you encountered:

Window buttons (Minimise, Maximise, Close) and URL address bar are visually out of line from the hitbox to click them when brave is maximised on a UHD display.

.   The window buttons cluster only registers if the mouse is at least halfway up the box
.   The URL bar, including Bookmark star, suffers from the same issue
.   Back/Forward buttons, Shield, Refresh and Home are all unaffected

This issue does not occur when Brave is not maximised (even if dragged to 4k).
If the button or URL bar is clicked outside of the hitbox the browser acts as if the click is on the header, double clicking will maximise or restore down the browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Windows 7, legal copy

- Brave Version (revision SHA):

0.13.5 (1db81cb)

- Steps to reproduce:

    1. Maximise Brave on a UHD native screen (3840 x 2160)
    2. Slowly move mouse over affected objects from bottom to top
    3. Click when the button is not highlighted but the mouse is over the button/bar
    
- Actual result:

Window buttons & URL bar are not registering the mouse hovering or clicking until roughly half way up the button/bar. Brave acts as if the mouse clicked the header

- Expected result:

Window buttons & URL bar to register a mouse hover and click when mouse is over the object at any point

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes, although cannot be reproduced on a <4K display (unsure about Nvidia DSR or AMD VSR)

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Screenshot if needed:

Window Buttons:
![uhdwindowsbuttons](https://cloud.githubusercontent.com/assets/25529333/23797562/5d9e4ca4-0598-11e7-921a-0bd07fb1876c.gif)

URL bar:
![uhdwindowsbuttons2](https://cloud.githubusercontent.com/assets/25529333/23797979/4ff5d976-059a-11e7-9d3b-4f3ea97bb0e7.gif)

**Comment by philkloose** [comment]
Strangely I have this exact issue with the address bar (only when running the window maximized), but the three "window buttons" in the upper right do not exhibit the symptoms.  I'm running Windows 7 (x64) and my resolution is only 1920 x 1080.

I'm running Brave version 0.13.5 rev 1db81cb.

**Comment by luixxiul** [comment]
I think this is the same as #7641.

**Comment by luixxiul** [comment]
Could I know if there would be difference between this issue and #7641? If not, I am going to close this in favor of #7641

**Comment by philkloose** [comment]
Ah, yes, in my case the I'm covered by #7641.  I seem to only be experience a subset of the issues covered in #7641, but I'd vote to close this.

**Comment by luixxiul** [comment]
OK thanks!
