### ISSUE TITLE
remember password prompt uses password as username

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7649]
Posting for a friend:
When changing a password on a website that offers three input fields (Old Password, New Password and Re-type Password), Brave seems to mistake one of the fields as a username and displays the password in the notification rather than the user name... I've seen this happen several times.

STR (attached a screenshot as an example):
login into Ebay and change your password

cc @diracdeltas would you mind taking this?

**Comment by bbondy** [comment]
![screenshot 2017-03-10 06 36 41](https://cloud.githubusercontent.com/assets/831718/23799103/2d51aff0-055c-11e7-9dbd-e7ef82d1d111.png)

**Comment by diracdeltas** [comment]
i can't repro this on https://reg.ebay.com/reg/ChangePwd so another example would be helpful if anyone has one
