### ISSUE TITLE
Add searx as Search Engine

### ISSUE THREAD

**Issue by cwmke** [brave/browser-laptop#7658]
Here are some comments discussing adding searx:
 #6295
 #790

## Q/A steps
   1. Open Preferences.
   2. Open the Search section and select 'searx' from the list.
   3. Activate the URL bar and type something (e.g. Brave).
   5. Press Enter.
   6. Make sure the searx search page appears with the specified search term(s).
   7. Activate the URL bar and try the engine go key :x.

**Comment by djmaze** [comment]
[searx.me](https://searx.me/) closed down its service for today, promoting the use of other public instances. It's really time for Brave to support custom search engines (see #3053).

**Comment by da2x** [comment]
Searx is up and running again. Yet another reason to allow custom search engines. 📦
