### ISSUE TITLE
Y position of second level (or higher) folders is wrong in Windows bookmark menu

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7662]
## Test plan
1. Launch Brave on Windows
2. Visit Preferences, disable `Hide the menu bar by default`, and confirm the menu shows up
3. Add 10 bookmark folders to your bookmarks toolbar (ex: name them `1`, `2`, `3`, etc)
4. For the very last folder (ex: 10), add a subfolder such as `1010`
5. Make the window's height small enough that it causes an overflow to happen
6. Click the bookmarks menu (or open using keyboard, either way) and use mouse hover to open the `10` folder
7. Confirm the Y position of the subitem (`1010`) matches the Y of the parent (`10`)

## Original issue description
- Did you search for similar issues before submitting this one?
similar #7403
- Describe the issue you encountered:
Second level context menu is not positioned correctly

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows, macOS (with forced windows menu)

- Brave Version (revision SHA):
3ad0f41

- Steps to reproduce:
    1. add so many items to the bookmark root folder to get scrollbar when going to the windows menu
    2. add folder to the bookmark root folder with 3 levels
    
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

- Screenshot if needed:
![5](https://cloud.githubusercontent.com/assets/9574457/23831286/8f3b76a6-071e-11e7-902a-cccf2bcaf169.gif)

**Comment by luixxiul** [comment]
@NejcZdovc does this close #1589 too?
