### ISSUE TITLE
When re-launching when maximised, window is offset by several pixels & no longer maximised

### ISSUE THREAD

**Issue by JohnLBergqvist** [brave/browser-laptop#7664]
- Description:
    When re-launching the browser (after the previous session ended with the browser maximised), instead of launching maximised again, the window is offset by several pixels vertically & horizontally, and is no longer maximised.

- Platform:
    Windows 10 64-bit
- Brave Version:
    Brave: 0.13.5 
    rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
    Muon: 2.56.8 
    libchromiumcontent: 56.0.2924.87 
    V8: 5.6.326.50 
    Node.js: 7.4.0 
    Update Channel: dev 
    os.platform: win32 
    os.release: 10.0.14393 
    os.arch: x64

- Steps to reproduce:
    1. Set the window to maximised.
    2. Close the browser entirely.
    3. Open the browser. 

- Actual result: 
 The window is offset by several pixels vertically & horizontally, and the OS no longer considers it maximised: https://i.imgur.com/rJ7VBtV.png

- Expected result:
The Window should replicate that of what it was when previously closed - i.e. maximised: https://i.imgur.com/dG3Atrp.png

**Comment by bsclifton** [comment]
Possibly related: https://github.com/brave/browser-laptop/issues/3754

**Comment by bsclifton** [comment]
found it- caused by this commit: https://github.com/brave/browser-laptop/commit/6d722101025835ee4c92403901ee6d2cfe2fedde

**Comment by ChiSeeker** [comment]
The plan to solve this (Start, maximize, exit, start) doesn't solve it for me. I hope you fix this in future versions, because this is the only big flaw when I am using it :)

**Comment by NejcZdovc** [comment]
@ChiSeeker hi, I already have a PR up (#10458) for this and it should fix all this problems. Thank you for your report :+1:

**Comment by ChiSeeker** [comment]
​Hello,

thank you, but I don't understand it. Could this be integrated into Brave
exe file or when updated?

Are you from Slovenia?

Thanks​



Damjan

**Comment by NejcZdovc** [comment]
@ChiSeeker yes this will be merged into the master branch and released with version 0.20. So you will get it as an update automatically. And yeah I am from Slovenia :smiley:
