### ISSUE TITLE
Sound icon + close button takes up too much space when tabs are small

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7665]
When both sound bar icon and tab close is available, it can be hard to figure out where to click.

<img width="77" alt="screenshot 2017-03-12 15 16 27" src="https://cloud.githubusercontent.com/assets/831718/23835062/f76dda9e-0736-11e7-89d8-fa16216e8b1c.png">

I think in this case we should use the blue bar variant of the sound indicator.

My wife hits this all the time and often mutes or closes the tab when she just wants to switch to it.

CC @bradleyrichter @cezaraugusto

**Comment by bbondy** [comment]
Here's a better example:
<img width="64" alt="screenshot 2017-03-12 15 19 26" src="https://cloud.githubusercontent.com/assets/831718/23835085/52153cbc-0737-11e7-9316-1cf86845b447.png">

**Comment by bradleyrichter** [comment]
We can adjust the min threshold for the mute and close button.
