### ISSUE TITLE
When alert() dialog is dismissed, underlying window does not regain focus

### ISSUE THREAD

**Issue by brad2014** [brave/browser-laptop#7666]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered:

If a window generates an alert popup, the window does not regain keyboard focus when the alert is dismissed.  Keyboard accelerators for the web page stop working until focus is manually restored (e.g. by clicking on the page with the mouse).

- Platform (Win7, 8, 10? macOS? Linux distro?):  MacOS 

- Brave Version (revision SHA): 1db81cb

- Steps to reproduce: 
    1.  Visit http://www.dailykillersudoku.com/main/play/14207
    2.  Click to focus on page, Hit "h" (keyboard accelerator for "help") to bring up alert(), dismiss it by clicking on OK.
    3.  Hit "h" again.  
    
- Actual result:
Nothing happens.  Second keypress is ignored.

- Expected result:
Hitting "h" should bring up the "help" alert again.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:  Perhaps #3460

**Comment by NejcZdovc** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
similar https://github.com/brave/browser-laptop/issues/8742

**Comment by Mohendran** [comment]
@brad2014  @bsclifton 
I opened the same website on chrome... It also exhibited the same behaviour.
