### ISSUE TITLE
Show Certificate detail on padlock and devtools on linux

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7669]
Follow-up of 
https://github.com/brave/browser-laptop/pull/7319
and 
https://github.com/brave/muon/pull/162

**Comment by scottbroadway** [comment]
Even if you go to F12 under Security, you still can't see the certificate. Works fine in Chrome.

**Comment by Liunkae** [comment]
@scottbroadway: View certificate in the developer tools will be fixed later (separate issue: #2611).

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/8758

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/12955

**Comment by sgnls** [comment]
Suspicious that this remains an issue... did I miss a thread elsewhere?

**Comment by srirambv** [comment]
This will be fixed in brave-core. Here's a screenshot of it.
![image](https://user-images.githubusercontent.com/17010094/42389569-2939af52-8117-11e8-84bb-86da97b964c7.png)


Closing the issue as `fixed-with-brave-core`

**Comment by bsclifton** [comment]
Verified as fixed in brave-core with https://github.com/brave/browser-laptop/issues/15064#issuecomment-415181577
