### ISSUE TITLE
Refactor about:about with Aphrodite (part 1)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7670]
## Test Plan
1. open about:about

## Original issue description
Refactor about:about with Aphrodite

**Comment by luixxiul** [comment]
Let's remove the milestone as it will take some time to refactor history.less, which is used on about:about

**Comment by luixxiul** [comment]
history.less is used widely as well as siteDetails.less and button.less etc, I would be able to tackle it later.

**Comment by bsclifton** [comment]
@luixxiul I created a part 2 follow up issue which does not have a milestone currently to track that work https://github.com/brave/browser-laptop/issues/8056 😄
