### ISSUE TITLE
Investigate & block email ads in popular webmail clients

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7676]
**- Did you search for similar issues before submitting this one?**
**Yes** - there is one issue specific to gmail: https://github.com/brave/browser-laptop/issues/3741 which I am going to bucket into a larger initiative here that covers blocking ads in popular webmail clients that serve them, with initial focus on: 

- Gmail
- Yahoo Mail
- Outlook webmail

**Objective serves to address two primary issues:** 
1. **_Enhance user privacy protection_**, by blocking ads and tracking that are served in webmail clients. 
2. **_Provide a cleaner webmail experience_** in Brave. 

**Initiative requires:** 

- Investigation, to determine which tracking and ad requests are called in webmail clients. 
- Careful testing, to ensure blocking measures honor core functionality.

**Gmail checklist:** 

- [ ] Network event traffic session capture
- [ ] Network event traffic session analysis
- [ ] Diagnose root cause
- [ ] Compose blocking strategy
- [ ] Test blocking strategy
- [ ] Create PR(s)

**Yahoo Mail checklist:** 

- [ ] Network event traffic session capture
- [ ] Network event traffic session analysis
- [ ] Diagnose root cause
- [ ] Compose blocking strategy
- [ ] Test blocking strategy
- [ ] Create PR(s)

**Outlook webmail checklist:** 

- [ ] Network event traffic session capture
- [ ] Network event traffic session analysis
- [ ] Diagnose root cause
- [ ] Compose blocking strategy
- [ ] Test blocking strategy
- [ ] Create PR(s)

**Comment by lukemulks** [comment]
Dumping notes here from some checks today. 

From Brave - catching these calls in consumer gmail: 
```
Request URL:https://clients5.google.com/ads/measurement/jn/?hd=mail.google.com
Request URL:https://clients5.google.com/ads/measurement/jn/jn.js
Request URL:https://clients5.google.com/pagead/drt/dn/dn.just

Request URL:https://www.google.com/pagead/adview?ai=C9M6ZuqbZWPLALI2VhATUm7-QAbaMheJIkabB7v0E59-8_wIQASCGj4ACYMnu2obIo6AZoAG-hsrPA8gBBqgDAaoEU0_QOLRYlBXM89fBnvEgib8DFo4k2gUVQEoVcmiwLiIP6wX06pXfAZpwOKBu3A5hfyyfkE7ghfyImdC4m8sc3j9WpwFWrBtuOMspyyB1sYDWwLILiAWIrMH3ApIFBggGEAEYB5AGAaAGN4AHqvm1MIgHAZAHAqgHpr4b2AcA0ggFCIACEALCEwYYvobKzwPYEww&sigh=olFlt5MATWM&cid=CAMSOQClSFh3ayUBhljsRvbDMGfeLS03xYFs8S_s_0mPqiijDDWlcLrn-B7c2NB9TO9zV6GBThi9VB80tA&template_id=459
```
Brave is also blocking pagead/ but could be a subdoc or other issue. 

Checked the filter lists for 1p and ELEMHIDE filters - likely going to require a mix of these to resolve: 

```
Google - GMAIL Filters 
mail.google.com##.aeF .nH[role="main"] > .mq:last-child
mail.google.com##.aeF > .nH > .nH[role="main"] > .aKB
mail.google.com##.aeF > .nH > .nH[role="main"] > .afn:first-child + .mq
mail.google.com##.aeF > .nH > .nH[role="main"] > .mq:first-child
mail.google.com##.aeF > .nH > .nH[role="main"] > .nH > .nH > .AT[style]
mail.google.com##.aeF > .nH > .nH[role="main"] > .nH > .nH > .nH > .mq:last-child
mail.google.com##.aeF > .nH > .nH[role="main"] > div + .mq

google.com,~mail.google.com##.c[style="margin: 0pt;"]

mail.google.com##.nH.PS
mail.google.com##.nH.adC > .nH > .nH > .u5 > .azN

mail.google.com##.oM

mail.google.com##.rh > #ra

google.com,~mail.google.com##.ts[style="margin:0 0 12px;height:92px;width:100%"]

mail.google.com##.u4
mail.google.com##.u9

mail.google.com##.xz
mail.google.com##.z0DeRc

google.com,~mail.google.com##[style="border: 1px solid rgb(0, 90, 136);"]
google.com,~mail.google.com##[style="border: 1px solid rgb(145, 117, 77);"]
google.com,~mail.google.com##[style="border: 1px solid rgb(241, 250, 248);"]
google.com,~mail.google.com##[style="border: 1px solid rgb(51, 102, 153);"]
google.com,~mail.google.com##[style="border: 1px solid rgb(51, 102, 204);"]
mail.google.com##a[href^="http://pagead2.googlesyndication.com/"]

Google - GMAIL Exceptions 
@@||mail.google.com^*&view=ad&$xmlhttprequest
@@||mail.google.com^*/uploaderapi*.swf
```
```
Yahoo - YahooMail Filters 
mail.yahoo.com###northbanner
mail.yahoo.com###nwPane
mail.yahoo.com###slot_LREC
mail.yahoo.com###slot_MB
mail.yahoo.com###slot_REC
mail.yahoo.com###swPane
mail.yahoo.com###tgtMNW
mail.yahoo.com##.avLogo
mail.yahoo.com##.left_mb
mail.yahoo.com##.mb > .tbl
mail.yahoo.com##div#msg-list .list-view .ml-bg:not(.list-view-item-container)
mail.yahoo.com#@#.searchad
mail.yahoo.com###MIP4
mail.yahoo.com###MNW
mail.yahoo.com,skateboardermag.com###SKY
mail.yahoo.com###modal-upsell

||mail.yahoo.com/mc/md.php?
||mail.yahoo.com/neo/mbimg?av/curveball/ds/
||beap.gemini.yahoo.com^$popup,domain=mail.yahoo.com

Yahoo exceptions
@@||adserver.yahoo.com/a?*=headr$script,domain=mail.yahoo.com
@@||mail.yahoo.com/neo/assets/swf/uploader.swf
```

**Comment by flamsmark** [comment]
I don't think we want to implement additional blocking for first-party ads. Please reopen if I've misunderstood the issue.
