### ISSUE TITLE
Dashlane Password manager shows __MSG_ExtensionName__ as extension name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7683]
## Test Plan
https://github.com/brave/browser-laptop/pull/7879#issue-216949361

1. Enable Dashlane
2. Navigate to about:extensions
3. Confirm that Dashlane's name and description are shown

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Dashlane Password manager shows __MSG_ExtensionName__ as extension name

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	1db81cb

- Steps to reproduce:
    1. Enable Dashlane as the password manager
    2. Open about:extensions
    3. Instead of `Dashlane` it shows as `__MSG_ExtensionName__ ` as the name
    
- Actual result:
Wrong name shown for Dashlane

- Expected result:
Should show proper app name

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23865327/38e738b8-080d-11e7-8ba0-dbc4e3b126ba.png)

- Any related issues:
cc: @bbondy

**Comment by bsclifton** [comment]
This should be fixed now with https://github.com/brave/browser-laptop/pull/7879 and https://github.com/brave/browser-laptop/pull/8314
