### ISSUE TITLE
Adding custom bookmark name text box not clearing when deleted

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#7691]
- Did you search for similar issues before submitting this one?
	Yes
- Describe the issue you encountered:
	When trying to clear the text box in "Bookmark Page" so I can set a custom name the original website's title keeps appearing in the text box after deleting it. As soon as I delete the first letter in the name, the original website title pops back into the box.
	
- Platform (Win7, 8, 10? macOS? Linux distro?):
	Windows 10
	
- Brave Version (revision SHA):
	[1db81cb](https://github.com/brave/browser-laptop/commit/1db81cb18b6919535792bb7e198ab87276bd67ea)

- Steps to reproduce:
    1. Go to a website
    2. click on "Bookmark page"
    3. when the box appears try and rename the name of the bookmark
    4. As soon as you delete the first letter the original text appears again.
    
	
- Actual result:
	The name of the website keeps popping back up and I can't set a custom name for it

- Expected result:
	To be able to name the bookmark what I want it to say without having the original text appear again after I delete the first letter. I think it would be better to be ab;e to have the text box completely blank when you want to name a bookmark. Yes still have the original webpage be there  at first but after everything is gone, the original text shouldn't reappear.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
	Yes they can.
  
- Is this an issue in the currently released version?
	0.13.5 in "Releases"
 
- Can this issue be consistently reproduced?
	Yes it can
  
- Extra QA steps:
    1. Go to a website
    2. Go to "Bookmarks"
    3. Press "Bomark page"
    4. Try to rename the website to a custom name for the bookmark
    5. When you try to delete all of the text that is already in the text box, the original text will reappear after you delete the first letter

- Screenshot if needed:
	[Gif of what I see](https://puu.sh/uHG1l/81fb2591e4.mp4)

- Any related issues:
	-	None that I can see

**Comment by Liunkae** [comment]
Confirmed with 0.13.5. Deleting each character individually appears to work, but deleting the entire text does not work.

**Comment by Liunkae** [comment]
This problem is caused by 57108ea. @diracdeltas

**Comment by luixxiul** [comment]
I cannot confirm this was fixed on Windows 10 32 bit

**Comment by JMccormick264** [comment]
It's been fixed for me. 64bit

**Comment by luixxiul** [comment]
Maybe am I missing something?

![bookmark](https://cloud.githubusercontent.com/assets/3362943/24055940/6494d530-0b85-11e7-87e1-e891c18ce64b.gif)

**Comment by JMccormick264** [comment]
The bug I made was when you would delete everything completely, the original text would reappear and it wouldn't go away.

**Comment by luixxiul** [comment]
Ah I read just too fast, sorry.

The input field becomes empty as the gif above shows.

**Comment by diracdeltas** [comment]
@luixxiul yep, that is the expected behavior
