### ISSUE TITLE
Handle app state that grows over time

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#77]
Some app state will grow over time and is not practical to update on every dispatch request. One way to handle it would be to update it through the actions/dispatcher, but only keep a timestamp/version number in the state itself

```
sites: version,
bookmarks: version
```

Each window can detect when its version is out-of-date and load the most recent version from async storage or similar

**Comment by lucidNTR** [comment]
what are your thoughts on moving
sites
bookmarks
into a pouchDB? we could run the pouchDB on IndexedDB. So storage and performance are taken care of...
