### ISSUE TITLE
Feature to Customize Proxy Settings / Make use of OS Proxy Settings

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#770]
Request from user (Support) that we offer a Proxy Server to be used, whether that is set within Brave or whether we use the OS Proxy Server which has just been specified.

**Comment by flyer0101** [comment]
I am unable to use the browser in my environment as it requires a proxy. I have only tested the OS X version but it doesn't support my OS proxy settings and there is no way (that I can find) to define them in the browser itself.

**Comment by ajg-B** [comment]
Likewise.
Any development to make Brave work in firewalled environments?

**Comment by bbondy** [comment]
This is planned we just haven't gotten to it yet

**Comment by diracdeltas** [comment]
@flyer0101@ajg-B  Brave uses my OS X system proxy settings afaict. could you try again with the latest release? if not, what are your proxy settings?

**Comment by zeroshirts** [comment]
@diracdeltas FWIW, latest Brave release works for me on OS X w/ SOCKS5 proxy in system preferences, except for 'Check for updates' (#1230).  ```Brave: 0.10.0, Electron: 0.37.8, libchromiumcontent: 50.0.2661.102, V8: 5.0.71.48, Node.js: 5.10.0, Update channel: dev```

**Comment by diracdeltas** [comment]
@zeroshirts excellent catch; turns out the updater uses Node's request stack instead of Chromium's so it bypasses system proxy settings. I'm going to close this since we do use OS proxy settings most of the time and open more specific issues.

**Comment by dandart** [comment]
I see this issue still exists... If I set my proxy in KDE using local/global modes, it still doesn't affect brave... is this something that can be fixed?
(Ubuntu 16.04)
And what is the workaround for now?

**Comment by diracdeltas** [comment]
@dandart are you seeing no requests go through the proxy? or only some requests?

**Comment by dandart** [comment]
None at all, I refresh a show-my-IP website and it shows my home IP.

**Comment by diracdeltas** [comment]
what happens in Chrome?

**Comment by dandart** [comment]
Chrom(e|ium) obeys the settings.

**Comment by diracdeltas** [comment]
that's definitely weird because brave uses the same network stack as chromium for most requests

**Comment by dandart** [comment]
Even on Ubuntu?

**Comment by dandart** [comment]
Then again it could be the caching issue I was having... when pages are refreshed new content isn't subbed in. I'll test again later on

**Comment by srirambv** [comment]
+1 from [support ](https://linkbubble.zendesk.com/agent/tickets/7224)
