### ISSUE TITLE
View Source shortcut should be CTRL+U, not CTRL+ALT+U

### ISSUE THREAD

**Issue by mrpapercut** [brave/browser-laptop#7702]
## Test plan
1. Launch Brave on macOS and visit brave.com
2. Verify `view source` shortcut is unchanged; it should be Cmd + Option + U
3. Launch Brave on Windows (or Linux) and visit brave.com
4. Press Ctrl + U and verify `view source` comes up as expected

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
View Source shortcut should be CTRL+U, not CTRL+ALT+U

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
1db81cb18b6919535792bb7e198ab87276bd67ea

- Steps to reproduce:
    1. Go to //brave.com
    2. Press CTRL+U (win) or CMD+U (darwin)
    
- Actual result:
Nothing happens

- Expected result:
URI view-source:https://brave.com is loaded in a new tab
The context-menu option to View Source indicates that the shortcut should be CTRL+U

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues:
Referenced in, but not related to #7491. View-Source shortcut still doesn't work even after commit 5a889ccd6198906537f0c29d4b28067292a4ef78 (but that commit is necessary for any keybindings to work)

**Comment by NejcZdovc** [comment]
Opera and Firefox is using CTRL+U, but Safari and Chrome is using CTRL+ALT+U

cc @bsclifton @bradleyrichter @bbondy

**Comment by mrpapercut** [comment]
On Windows Chrome it's Ctrl+U
On Mac Chrome it's Cmd+Alt+U
On Safari there is no View Page like in Brave, but Cmd+Alt+U opens the devtools

The contextmenu of Brave says that it's Ctrl+U on windows, and the keymapping was set to Ctrl+Alt+U

**Comment by NejcZdovc** [comment]
@mrpapercut Yeah sorry I should wrote it in the comment above that I am using macOS

**Comment by mrpapercut** [comment]
No problem, I had to check with someone else to figure out the macOS shortcuts too :)

So the difference is really windows/linux vs. macOS, as all browsers (IE & Edge as well) on Win use Ctrl+U and those on Mac use Cmd+Alt+U. 

There already is an OS condition in the same file for different keys. My suggestion is that I create a new PR that uses Cmd+Alt+U for darwin and Ctrl+U for win, as that is most widely implemented
