### ISSUE TITLE
Issues opening Browser

### ISSUE THREAD

**Issue by otakugeek81** [brave/browser-laptop#7706]
- I did search for similar issues, but it seems that they are either still ongoing or have been fixed with updates for others.

- Describe the issue you encountered: Brave does not consistently open. I will have a window open in the taskbar, but the actual window itself seems to be clear.
There are times that it will work, although it seems there is no set pattern

- Platform Win 10 x64

- Brave Version (revision SHA):
rave	0.13.5
rev	1db81cb
Muon	2.56.8
libchromiumcontent	56.0.2924.87
V8	5.6.326.50
Node.js	7.4.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64

- Steps to reproduce:
    1. open brave, browse web
    2. close brave
    3. brave opens to blank window
    
- Actual result: stated above

- Expected result: Brave opens every time without issue

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@otakugeek81 do you have payments enabled? We did have a race condition which was discovered (and fixed) but isn't released yet.  If you do have Brave Payments enabled, you can try disabling it temporarily (when the executable works for you).  Let me know 😄

**Comment by bsclifton** [comment]
Closing this issue as a duplicate in favor of https://github.com/brave/browser-laptop/issues/7619 which you may want to subscribe to

Let me know if the above tip (disabling payments) works for you.  Thanks 😄
