### ISSUE TITLE
Partition text for session tab is overlapping on the tab title

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7716]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Partition text for session tab is overlapping on the tab title

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	7dfeeb0

- Steps to reproduce:
    1. Do a clean install of 0.14.0 
    2. Visit a site in a new session tab
    3. Open a link in new tab from the session tab
    4. The text `partition` is overlapping on the tab title (see screenshot)
    
- Actual result:
Partition text for session tab is overlapping on the tab title

- Expected result:
Should not over lap on tab title

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/23925807/dda30b38-0908-11e7-959d-bcf15ba236db.png)

- Any related issues:

**Comment by alexwykoff** [comment]
<img width="1269" alt="screen shot 2017-03-29 at 8 14 19 pm" src="https://cloud.githubusercontent.com/assets/1434040/24484257/e2510700-14c2-11e7-8429-1fc3dbd55652.png">

This is the current expectation, where purple only shows for the active private tab. Future design will have a purple hint for inactive tabs.
