### ISSUE TITLE
Add "Command+Click" to home button (opens home in a new background tab)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7718]
## Test Plan
1. Turn on the Home button
2. Ctrl+Click or Cmd+Click the Home button to open home page in a new tab 

## Original issue description
request from Twitter:

"My pet @brave peeve: command clicking on the home icon does not open a new tab.  :("

Source: https://twitter.com/SambodhiPrem/status/841761765973086208

See chrome on Mac OS for reference)

**Comment by luixxiul** [comment]
Clicking the home button with the ctrl key opens the home page on the active tab.

Shouldn't it be opened on the background tab?

**Comment by jonathansampson** [comment]
@luixxiul You're correct. We differ with Chrome in that the new tab will immediately be focused in Brave, whereas _it will not_ be focused in Chrome. @bsclifton, should we change?

**Comment by bsclifton** [comment]
I support changing to match the Chrome behavior

@bradleyrichter what do you think? 😄

**Comment by bradleyrichter** [comment]
I support BS from Clifton.

**Comment by bsclifton** [comment]
@luixxiul @jonathansampson @bradleyrichter updated! I also updated the test plan
