### ISSUE TITLE
NewTab retains about:newtab text until mouse pointer is moved away from tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7724]
## Test plan

https://github.com/brave/browser-laptop/pull/7754#issue-214866954

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
NewTab retains about:newtab text until mouse pointer is moved away from tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	7dfeeb0

- Steps to reproduce:
    1. Do a clean install of 0.14.0
    2. Set new tab opens to blank page in settings
    3. Use mouse/trackpad to click on the new tab button so that the pointer is over the new tab
    4. Tab text remains `about:newtab` until the mouse pointer is moved away from newly created tab
It is the same with opening a new tab/private tab/session tab using keyboard shortcut with the pointer right next to the <kbd>+</kbd> button
    
- Actual result:
New tabs text doesn't change until mouse pointer is moved away from the newly created tab

- Expected result:
Should should New Tab like before

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![7624](https://cloud.githubusercontent.com/assets/17010094/23942706/118bd91e-0965-11e7-9090-611fc35a0423.gif)

- Any related issues:
cc: @cezaraugusto @bsclifton

**Comment by luixxiul** [comment]
I think this has been the same issue which I pinged @NejcZdovc somewhere. @NejcZdovc do you remember?

**Comment by NejcZdovc** [comment]
@luixxiul is this issue, but I think it's not the same #7606
