### ISSUE TITLE
New bookmark in a folder on bookmark toolbar is not included in the folder on the main menu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7725]
**Describe the issue you encountered:**

1. Bookmark a new page
2. Create a new bookmark folder
3. On the bookmark toolbar, move the bookmark into the folder
4. Hit alt
5. Select "Bookmark"

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.14.0 Preview 1
  
- Actual result: the bookmark is not included in the bookmark folder

- Expected result: It should be included

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes

- Is this an issue in the currently released version? Yes, the bug exists on 0.13.5

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
@luixxiul dupe of #7049?

**Comment by luixxiul** [comment]
Nice find!
