### ISSUE TITLE
Dead tab when enter is pressed twice after typing in URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7727]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab becomes dead when enter is pressed twice after typing in URL

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	7dfeeb0

- Steps to reproduce:
    1. Open a new tab and type any text/url
    2. Press <kbd>Enter</kbd> twice in quick succession
    3. URL bar becomes empty as #2952 
    4. Enter a different URL in the same tab and press enter
    5. Page loads but is not displayed, Tab title still remains as NewTab
    
- Actual result:
Dead tab when enter is pressed twice

- Expected result:
Should load the page in the second instance after pressing enter in quick succession

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![deadtab](https://cloud.githubusercontent.com/assets/17010094/23947547/1129deaa-0977-11e7-9259-51ec45bdbc0c.gif)

- Any related issues:
#2952 
cc: @bsclifton 
Please change milestone if required

**Comment by Shnkc** [comment]
I also experience this issue on MacOsX Sierra 10.12.
Brave version is 0.14.1

**Comment by bsclifton** [comment]
Our most recent version (0.14.2- still in preview stage, but likely to release this week) fixes this. Unfortunately, we didn't narrow down to find a root cause, but it doesn't seem to be possible to reproduce.

I'll mark this issue as closed- let's re-open if we see the issue again in 0.14.2 or later 😄
