### ISSUE TITLE
Linux Arm - electron-prebuilt download is broken (404)

### ISSUE THREAD

**Issue by fczuardi** [brave/browser-laptop#773]
### Steps to reproduce:

On an Arm Linux try to go trough Brave's npm installation, or try to install this particular dependency with:

```
npm install brave/electron-prebuilt
```
### Expected result:

The proper zip release is downloaded and the electron binary copied.
### Actual results:

The installation fails because of a not found URL:

```
Downloading brave-v0.36.7-linux-arm.zip
Error: GET http://brave.github.io/browser-laptop-releases/0.36.7/brave-v0.36.7-linux-arm.zip returned 404
```
### Workaoround
- manually download an electron build from https://github.com/atom/electron/releases
- extract the binary to some folder
- edit the **tools/start.js** file replacing electron with the path of where the binary you downloaded is, for example:

``` diff
-execute('electron "' + path.join(__dirname, '..') + '" ' + process.argv[2], env)
+execute('/usr/local/bin/electron "' + path.join(__dirname, '..') + '" ' + process.argv[2], env)

```

**Comment by luixxiul** [comment]
Has this been fixed? If not let's get it over with :-)
