### ISSUE TITLE
Cannot unpin an about:error page

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7733]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When a _pinned_ tab is pointing to about:error or about:blank, the user cannot unpin the tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.14.0

- Steps to reproduce:
    1. Open a tab to https://brave.com
    2. Pin the tab
    3. Navigate to about:error
    4. Attempt to unpin
    
- Actual result:
The context menu shows no options to either pin or unpin the tab.

- Expected result:
The user should be able to unpin a tab, regardless where it is presently pointing.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/815158/23960888/9719c270-097f-11e7-8473-49710cbd08ae.png)

**Comment by bsclifton** [comment]
moving to 0.14.3

**Comment by bsclifton** [comment]
Similar to https://github.com/brave/browser-laptop/issues/4063
