### ISSUE TITLE
Full Screen mode fails on Linux Version

### ISSUE THREAD

**Issue by Seferi** [brave/browser-laptop#7734]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When i switch to full screen mode, the top bar is always shown. It's not really full screen...
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Ubuntu Mate 16.04
- Brave Version (revision SHA):
0.13.5 (rev 1db81cb)
- Steps to reproduce:
    1.Open Brave Browser
    2. press F11
    3.
    
- Actual result:
Top bar, address bar always shown
- Expected result:
Full Screen without the topbar, top bar is shown only on mouse hover
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screenshot at 2017-03-15 18 22 41](https://cloud.githubusercontent.com/assets/2592842/23962052/2538c330-09ad-11e7-83a6-f33a5a76ceb2.png)

**Comment by srirambv** [comment]
This is the expected behavior on all platforms for full screen. Auto hide of top bar was removed. https://github.com/brave/browser-laptop/issues/4371#issuecomment-250488866

**Comment by Seferi** [comment]
When will it be implemented back? I think full screen is a very important feature especially for smaller screens. It should be a priority..
