### ISSUE TITLE
Last contribution date shows Your  first contribution will be {{reconcileDate}}

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7735]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Last contribution date shows Your  first contribution will be {{reconcileDate}}

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.14.0 Preview 1

- Steps to reproduce:
    1. Change Language to Russian, restart the browser
    2. Enable Payments
    3. Last contribution read `Your  first contribution will be {{reconcileDate}}`
    
- Actual result:
Last contribution read `Your  first contribution will be {{reconcileDate}}`

- Expected result:
Should show translated version of `No previous contributions`

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Russian
![image](https://cloud.githubusercontent.com/assets/17010094/23964212/a7cfb90e-09ab-11e7-8ad1-d19e5fef7622.png)
English
![image](https://cloud.githubusercontent.com/assets/17010094/23964229/b24355e4-09ab-11e7-9bb8-dc0cbf703bbd.png)

- Any related issues:
#6309

**Comment by luixxiul** [comment]
This is thought to have been fixed.

**Comment by bsclifton** [comment]
@luixxiul @srirambv can we retest this with our most recent build? I also believe it's fixed (although, I can't find the related PRs)

**Comment by srirambv** [comment]
Tested this on 0.16.100 and text is properly translated. Can't test it on 0.16.2 as its blocked on #9269 . Will give it a test once 0.16.2 build is fixed. 

Closing the issue for now
