### ISSUE TITLE
change tab-initiated alerts to be tab specific and not window specific

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7737]
A tab should be the parent container of its own alert bar/message.

2 alert bars from different tabs should never be shown in the same browser window at the same time.

Each window may have it's own tab-specific alert bar.

Only one alert bar should be shown at a time. Alert bars should stack with the newest alert on top. Confirming the choice on the top bar will close the bar and reveal the next bar underneath. 

They should not both be visible at the same time.

**Comment by bradleyrichter** [comment]
closing because it was actually fixed already and I was being a numb nut.

**Comment by bsclifton** [comment]
removing milestone as issue is closed without any code changes. If there's still work to be done, let's re-open 😄
