### ISSUE TITLE
Unable to add annotations to YouTube videos - youtube.com

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7738]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Users are not able to add annotations to YouTube videos.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.14.0 https://github.com/brave/browser-laptop/commit/7dfeeb03e606d625fd53b3c219a2f3e3380ab3d0

- Steps to reproduce:
    1.  Choose to add annotations to a YouTube video
    2. Note that you cannot
    
- Actual result:
*Annotations don’t work on mobile. Try Cards or the new End screen tool instead.*

- Expected result:
The user should not be presented with any error message, but should instead be permitted to add annotations.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/815158/23968086/dbb2966a-0997-11e7-934a-c08decfc1200.png)

**Comment by jonathansampson** [comment]
I believe this issue is related to Flash support. Chrome shows the same experience, but informs the user that a plugin has been blocked. Adding _*.youtube.com_ to the exceptions list results in a revealed editor.

**Comment by diracdeltas** [comment]
This may be addressed by #7549 if you have Flash installed and enabled and then turn shields down on the page.

**Comment by Liunkae** [comment]
The annotation editor will be discontinued on May 2 ([see this](https://support.google.com/youtube/answer/7342737)). This will only be a problem for one more month.

**Comment by diracdeltas** [comment]
@Liunkae nice find! i think this is not worth fixing

**Comment by bsclifton** [comment]
Closing issue as `wontfix`
