### ISSUE TITLE
v0.7.14 Installation Failure

### ISSUE THREAD

**Issue by Ken-Saunders** [brave/browser-laptop#774]
See the attachments.
I can provide the SquirrelSetup.log if necessary.

Is v0.7.14 (from https://github.com/brave/browser-laptop/releases) 32, or 64-bit.
I need 32-bit if it's 64.
Also, and I understand that it's early, when will there be more control over the installation like the option to cancel it, change it's directory, etc?

![brave-1](https://cloud.githubusercontent.com/assets/1267130/13044660/5a225d0a-d39d-11e5-802a-9f62f12c3c17.png)
![brave-2](https://cloud.githubusercontent.com/assets/1267130/13044662/5a281772-d39d-11e5-9279-b756d74fefdd.png)
![brave-3](https://cloud.githubusercontent.com/assets/1267130/13044661/5a25eae2-d39d-11e5-97df-f19659f2f6e8.png)
![brave-4](https://cloud.githubusercontent.com/assets/1267130/13044663/5a29ec0a-d39d-11e5-8f04-bfef0a26fea4.png)

**Comment by weems** [comment]
@Ken-Saunders Please check https://github.com/brave/browser-laptop/issues/397

**Comment by bbondy** [comment]
Closing this as a dupe for the 32-bit aspect.
Please feel free to spin off another issue posted though about installation options. Thanks!
