### ISSUE TITLE
Dashboard (about:newtab) - allow more tiles / pins

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7742]
We had a row control originally available that would let you toggle between 1, 2, and 3 rows of tiles / icons on the new tab page.  This was removed with https://github.com/brave/browser-laptop/commit/967362846d1a06bf8fa042fd8e0b3b85650ab57d#diff-dbb992f7cd2508b46d5cd98e609be5a5

We should consider either re-adding that functionality OR finding another way to add icons to the new tab page.  Multiple rows was originally removed because there are some dupes of entries (ex: subdomains show, etc) which we plan to solve with https://github.com/brave/browser-laptop/issues/5338

cc: @bradleyrichter @cezaraugusto

**Comment by cezaraugusto** [comment]
I agree.

For reference if we go this way, additional rows were removed by this commit: https://github.com/brave/browser-laptop/pull/5483/commits/967362846d1a06bf8fa042fd8e0b3b85650ab57d

**Comment by bradleyrichter** [comment]
was there any deduping work done? I'd like to enable the rows soon...

**Comment by bsclifton** [comment]
@bradleyrichter we never did decide what to do. Right now, subdomains are considered different... so let's say you have `gmail.google.com` and `hangouts.google.com`, those would be two different items.  

We could just allow one per domain and then pick the subdomain with the highest visit count or "frecency" (see https://github.com/brave/browser-laptop/issues/5338 for the full scoop).  This might be a good first step

**Comment by srirambv** [comment]
@bsclifton @bradleyrichter  @cezaraugusto  Instead of having the topsite tiles preloaded (as complained) , we can use a <kbd>+</kbd> button to add top sites allowing users to enter the site name and add it as top tile. The <kbd>+</kbd> can be hidden when the max tiles are reached.

Rough (bad) mockup 
![image](https://cloud.githubusercontent.com/assets/17010094/23995869/5f5e23ca-0a43-11e7-9c9a-ff35d5a69a20.png)

**Comment by bsclifton** [comment]
@srirambv I like that 😄

**Comment by bradleyrichter** [comment]
@bsclifton I think we need to allow subdomains so you can have gmail, g-photos, g-hangouts, gthis and gthat.

@srirambv this could work nicely...but I am now thinking we should have the tiles right-aligned because this looks strange with only one tile.

(still working on what to show by default. I think we need tiles there for users to understand how they work.)

**Comment by srirambv** [comment]
@bradleyrichter  may be we can just leave one tile pinned  and then a `+` button to add. Serves both the purpose of tile and pinned tile. What do you think?

**Comment by bradleyrichter** [comment]
First. let's put a plus button in a dotted square. I think this will be cleaner and a bit more intuitive. If needed, we can have 1 tile and 5 squares. 

But I think we can pick some sites that most people will be fine with like wikipedia, DDG, twitter, etc....

something like this:

![image](https://cloud.githubusercontent.com/assets/13509546/24022356/3bf94908-0a63-11e7-9a85-2bc51c3e4a50.png)




thoughts?

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/dashboard-enhancement/2967/6

**Comment by cezaraugusto** [comment]
what happens when user hit the plus button? Modal with url input like Opera?

**Comment by srirambv** [comment]
Yes. Modal to enter URL and once click done display the favicon

**Comment by cezaraugusto** [comment]
super cool idea ++

**Comment by Mevrael** [comment]
Is there a way to have more then 6 top sites in dashboard right now?

**Comment by cezaraugusto** [comment]
@Mevrael it was possible when new tab was implemented but not at this moment.

**Comment by bsclifton** [comment]
Would be nice to be able to just drag the items out from bookmarks toolbar to the tile area

cc: @cezaraugusto, @bradleyrichter

**Comment by cezaraugusto** [comment]
@bsclifton +1 from me. 

I'd like to propose a different approach to top sites too. Current isn't working fine IMO. What if we let top sites be a user-decision only? like a kind of "bookmarks for new tab" with model @bradleyrichter mentioned https://github.com/brave/browser-laptop/issues/7742#issuecomment-287220279.

For me collecting data from most accessed sites is only useful when user has no choice (aka Chrome). But we are too cool for that 😛 just my two cents

**Comment by bsclifton** [comment]
I love the idea of having it as another launch-pad, similar to the bookmarks toolbar (except with high res shots)

cc: @jenn-rhim for thoughts 😄

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/win64-laptop-v0-19-95-general-feedback-minor-issues/11283?u=eljuno

**Comment by DesertDwarf** [comment]
I like this idea. What happened to it?

**Comment by allstate17** [comment]
Is this still being worked on?  I recently installed Brave and this is something I immediately noticed that will stop me from using it very much.

**Comment by bsclifton** [comment]
@allstate17 nobody is actively working the issue unfortunately. But improvements to this would be fairly easy and we'd welcome a PR. Since we're not working on it, I unassigned @cezaraugusto

**Comment by bigt2000** [comment]
Is there any way to get this added back to the list of things to work on?  I would really love to be able to customize the dashboard with specific links instead of how it currently lists them.

**Comment by bsclifton** [comment]
@bigt2000 unfortunately, we won't be able to complete this before we transition over to our new platform, Brave Core. I have an issue created there which you can use to track this functionality
https://github.com/brave/brave-browser/issues/353

For now, I'm going to close this as `wontfix` since we won't fix it with our current (Muon) codebase
