### ISSUE TITLE
Enable device emulation

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#7745]
I can't find a way to enable device emulation in the developer tools. The menu icon in the top left corner of the console doesn't either.

MacOS Yosemite 10.10.5

**Comment by luixxiul** [comment]
duping to #7386

**Comment by SpikeShape** [comment]
Oh sorry about that. I tried finding a similar issue to avoid duplication.

Thanks for the update.

**Comment by luixxiul** [comment]
Don't be sorry, I know very well that search function on GitHub is much poor than the search engines...

Please feel free to leave feedbacks when you have them. Thanks!
