### ISSUE TITLE
Ctrl-right arrow / left arrow in Google Docs navigates browser instead of moving cursor

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#775]
In Google Docs on Windows, Ctrl-right arrow and Ctrl-left arrow should move the cursor forward and backward one word. With Brave, it moves the browser through that tab's website history.

**Comment by diracdeltas** [comment]
Can you confirm this is still happening as of 83f116bfa61602a0c41471635baafaab2b684233? I just verified on OS X that cmd+left/right doesn't navigate in goog docs any more, I don't have a windows machine handy right now.

**Comment by bsclifton** [comment]
This appears to have been fixed 😄👍 

I know it's been a long time, but if you wanted to confirm @stshank that would be great
