### ISSUE TITLE
The ID of new sesion tabs opened with cmd+shift+s more than 9 should be null or actual number

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7762]
**Describe the issue you encountered:** The ID of new sesion tabs opened with cmd+shift+s more than 9 should be null or actual number. It is unclear to which session the tabs actually belong.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24057520/fc7b19c2-0b8a-11e7-9c3e-d8e72b910a4f.jpg)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.14.0 Preview3

- Steps to reproduce:
    1. Hit <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>s</kbd> more than 9 times.
    
- Actual result:

- Expected result:

- Any related issues: #7684 #7376

**Comment by bbondy** [comment]
I think right now it just locks you into session 9 always at that point.

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/7783.
