### ISSUE TITLE
autofill session/private tab tests are failing

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7763]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
travis and local autofill tests are failing permanently for private and session tabs: https://travis-ci.org/brave/browser-laptop/builds/212020825#L5650

**Comment by diracdeltas** [comment]
looks like in the private/session tabs, the autofill menu appears briefly and disappears before it can be clicked. i am actually seeing this behavior in all tabs when i run `npm start`. for every keystroke in a form field, i see 'show-autofill-popup' emitted once followed immediately by 'hide-autofill-popup' emitted twice.

cc @darkdh

**Comment by bsclifton** [comment]
Great find, @diracdeltas 😄  [The real thing is breaking too](https://github.com/brave/browser-laptop/issues/7768) (just reported by @srirambv).  I'll go back and see which are the last passing tests

**Comment by bsclifton** [comment]
Last successful run appears to be right before we upgraded Muon to 2.56.9:
https://travis-ci.org/brave/browser-laptop/builds/211549904

**Comment by darkdh** [comment]
This commit broke the popup
(https://github.com/brave/muon/commit/fcaecc2f6230e700b858153c768fbe725027d1d7)
It will call https://chromium.googlesource.com/chromium/src.git/+/56.0.2924.87/components/autofill/content/browser/content_autofill_driver_factory.cc#127
then 
https://github.com/brave/muon/blob/29ab58342ec11a37d55f2f2ad7e32c89238b7976/atom/browser/autofill/atom_autofill_client.cc#L198

**Comment by bsclifton** [comment]
Will be fixed when https://github.com/brave/muon/pull/170 is accepted a new prebuilt is built. Closing this issue and removing milestone (as there is no testing needed)
