### ISSUE TITLE
Downloading the same name file disabling the save file dialog should change the filename

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7764]
## Test plan

https://github.com/brave/browser-laptop/pull/9867#issue-240628027

----

**Describe the issue you encountered:**
Downloading the same name file disabling the save file dialog should change the filename, like Edge does. For now the file is overwritten, which users do not always want to see.

- Platform (Win7, 8, 10? macOS? Linux distro?): 

- Brave Version (revision SHA): 0.14.0 Preview

- Steps to reproduce:
    1. Open about:preferences
    1. Specify a download path
    2. Disable "Always ask me where to save files"
    1. Download a file of a release from https://github.com/brave/browser-laptop/releases (eg RELEASES-ia32 of the Preview3)
    2. Wait until the download ends
    3. Download another file which has the same name of a **different version**  (eg RELEASES-ia32 of the **Preview2**)
    
- Actual result: the file is overwritten

- Expected result: the file should be saved with the filename changed, eg RELEASES-ia32(1)

- Any related issues: #2110

Marking this with impact/high as the users could lose their files by accident because of this setting, which behaves slightly different than the other browsers.

**Comment by NejcZdovc** [comment]
I think that this should be handled on Muon part

cc @bridiver

**Comment by kosta** [comment]
I ran into this today. Please fix! This bug scares me.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/downloaded-file-replaced-existing-file-of-same-name-without-warning/4176/)

**Comment by timborden** [comment]
Hey @NejcZdovc, I just submitted a PR (#9867) for this issue

**Comment by timborden** [comment]
Hey @luixxiul & @NejcZdovc, I've updated the PR based on the feedback from @bridiver and added some tests as well....FYI
