### ISSUE TITLE
 Always ask me where to save files should be disabled if user selects the file save location

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7767]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
 Always ask me where to save files should be disabled if user selects the file save location

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.0
rev	903cfea

- Steps to reproduce:
    1. Do a clean install of 0.14.0 Preview 3
    2. Select a folder to save downloads
    3. `Always ask me where to save files` switch is still enabled which doesn't make sense when user has selected the location to save the file
    
- Actual result:
 Always ask me where to save files should be disabled if user selects the file save location

- Expected result:
Switch should get disabled when user selects the default file save location

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24060235/43c56ba2-0b4a-11e7-8b29-02adfdfeef22.png)

- Any related issues:
cc: @NejcZdovc

**Comment by bsclifton** [comment]
@srirambv I disagree... there isn't a way to clear this field.  Our behavior matches Chrome

I'm going to remove milestone and close, but please re-open / assign milestone if you disagree strongly and we'll revisit
