### ISSUE TITLE
1Password gets into a state where it no longer works

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7769]
## Issue description
There have been a few occasions where the 1Password extension seems to be broken

### Symptoms:
- Visiting https://agilebits.com/browsers/auth.html does not work. It should be showing a screen like the one below... but instead says that extension is not found.
![screen shot 2017-09-11 at 10 15 31 am](https://user-images.githubusercontent.com/4733304/30287505-3e69540e-96da-11e7-827a-6a108b3ed538.png)

- Extension is clearly installed and shows up fine in `about:preferences#extensions` and `about:extensions`

- Cmd + \ does nothing when pressed while inside a login form field (should be triggering the 1Password mini helper which would either fill in form or open to show possible matches)

### Work-arounds:
Issue seen was resolved in the past by running these steps:
- disable 1Password (pick another manager, etc)
- exit Brave
- move/rename the folder containing the extension, which on macOS is stored at `~/Library/Application Support/brave/Extensions/aomjjhallfgjeglblehebfpbcfeobpgk/`
- re-enable 1Password (this should force re-install of the extension)

The above work-around recently (Sep 11, 2017) **did not work**. Re-enabling 1Password did **not** trigger the component updater (which then reinstalls the extension). User waited over an hour with Brave open and nothing happened in that time.

Issue was fixed by renaming the file at `~/Library/Application Support/brave/Extensions/aomjjhallfgjeglblehebfpbcfeobpgk/` back to it's original name and relaunching Brave.

## Originally reported issue

- Describe the issue you encountered:
When attempting to use 1Password, the browser opened a new tab and had a peculiar error where it seemed to be looking for a specific IP.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.0 Preview 3 (https://github.com/brave/browser-laptop/commit/903cfeade7d4393c4225eaec9f308e62a41357b9)

- Steps to reproduce:
    1. Using 0.14.0 preview 3 on OS X, enable 1Password.
    2. Attempt to log into github using stored credentials.
    3. On the first try, an error will occur, subsequent tries fail quietly.
    
- Actual result:
I am not logged into github.

- Expected result:
I should be logged into github.

**Comment by bsclifton** [comment]
@alexwykoff I'm thinking this is related to the signature not matching.  Can you try disabling that check in options and seeing if it makes a difference?

@bbondy I can verify the signing of the build by running `spctl --assess --verbose /Applications/Brave.app/` and it looks correct. Is there anything about preview builds which may prevent this from working properly?

**Comment by bsclifton** [comment]
After trying some more, I can't repro.  My GitHub didn't autopopulate because I didn't have the URL set properly.  After fixing that, it works great.  Other sites I have work great too.  Will try a clean session

**Comment by bsclifton** [comment]
Closing as I can't reproduce. My best guess would be that the `website` field of your 1Password entry doesn't have the proper login URL set.  Here's a GIF of me launching with a fresh session (showing the version being preview 3) and it works great:
![1pw-mac-preview3](https://cloud.githubusercontent.com/assets/4733304/24063462/fa8e6a88-0b1c-11e7-94ae-8cabc77a7eee.gif)

**Comment by bsclifton** [comment]
Another possibility: if you opened github.com and THEN set the PW manager... you would need to reload the page in order for it to work.  This is a known issue

**Comment by bsclifton** [comment]
@bradleyrichter I know you saw this too- could you document your steps?  I'll reopen

**Comment by bradleyrichter** [comment]
It works but instead of recognizing the page URL matches the stored URL and just filling the fields, it instead opens a new tab of the same URL and then fills the fields. 

This is reproducible every time on any form.

**Comment by alexwykoff** [comment]
i think i found the root cause.  using 1pw with chrome added an app handler website link to the top of the link list (logins can have multiple associated links) and brave selects the first link by default rather than evaluating to see if it’s appropriate

removing the app handler link (app://com.Google.Chrome) causes 1PW to work fine

so i am unsure if we can do much about this or if we should punt to 1PW extension team to behave better in a multi-browser environment

**Comment by bsclifton** [comment]
Issue seen by @BrendanEich was resolved by the following:
- disable 1Password (pick another manager, etc)
- exit Brave
- rename the folder containing the extension, which on macOS is stored at `~/Library/Application Support/brave/Extensions/aomjjhallfgjeglblehebfpbcfeobpgk/`
- re-enable 1Password (this forces re-install of the extension)

**Comment by BrendanEich** [comment]
[for-clifton.tar.gz](https://github.com/brave/browser-laptop/files/873671/for-clifton.tar.gz)

Per @bridiver disabling, removing (moving Extensions subdir aside to this .backup directory name), quitting, restarting, re-auth'ing via six-digit TAN to 1pw upon re-enabling via Preferences / Security, reloading the page I was testing, and all is well. Whew! @bsclifton asked for the saved extension directory. Thanks.

**Comment by bsclifton** [comment]
Removed milestone since this is not something we'll be able to resolve with 0.14.0

**Comment by bsclifton** [comment]
Happened again today; notes in original post updated

**Comment by bsclifton** [comment]
cc: @bridiver 
Could local storage by the extension be causing an issue? Maybe we should be clearing local storage (for a given extension) when an extension is disabled?
