### ISSUE TITLE
Undo/redo menu items in context menu should be disable-able

### ISSUE THREAD

**Issue by psimyn** [brave/browser-laptop#777]
Need to implement canUndo / canRedo to electron 

then update menu items in https://github.com/brave/browser-laptop/pull/762

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/undo-redo-menu-items-in-context-menu-should-be-disable-able/10245

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
