### ISSUE TITLE
Bookmark does not allow empty title

### ISSUE THREAD

**Issue by isaacg1** [brave/browser-laptop#7774]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: If I create or edit a bookmark and empty to remove all of the text of the title, the original title of the webpage is substituted instead. It is impossible to have no text.

- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu Linux, 14.04.5 LTS.

- Brave Version (revision SHA): 1db81cb18b6919535792bb7e198ab87276bd67ea

- Steps to reproduce:
    1. Open brave
    2. Optional: Navigate to a website
    2. Press Ctrl + D
    3. Title field of the bookmark will be highlighted. Press backspace. Text will not be deleted.
    4. Press backspace some more until the last letter should be deleted
    
- Actual result: Original page title (e.g. New Tab) will refill in the Title field.

- Expected result: Empty Title field.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes.

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? Yes.

**Comment by luixxiul** [comment]
> It is impossible to have no text.

That is the expected behavior: https://github.com/brave/browser-laptop/issues/7691#issuecomment-287440809

**Comment by Liunkae** [comment]
@isaacg1: Thanks for the report! Fortunately, this bug has already been fixed (#7691). The next Brave update (0.14.0) will include this fix.
