### ISSUE TITLE
Browser Action Path May Not Exist

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7775]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When loading an extension, Brave attempts to locate an icon from the manifest file. It looks to `browserAction.default_icon` (See [muon/extensions.js](https://github.com/brave/muon/blob/ef80be0e321a0d8b799a9cc8a577a93c0f21103d/lib/browser/api/extensions.js#L42)). This property may not exist for some extensions.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.14.0 https://github.com/brave/browser-laptop/commit/903cfeade7d4393c4225eaec9f308e62a41357b9

- Steps to reproduce:
    1. Load any extension that lacks a `browser_action.default_icon` property.
    2. Note that Brave fails to load properly
    
- Actual result:
Brave will not fully load. A white window is all the user will see.

- Expected result:
Brave should be able to handle extensions that lack a default icon.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes (provided you install an appropriate extension)

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
@jonathansampson does this require QA? Any steps we should manually perform?

**Comment by jonathansampson** [comment]
@bsclifton Tough call; manually, we'd have to locate and install an extension that lacks the property in the manifest. We could, however, make a dummy extension (used only in tests) that lacks the property.

**Comment by bsclifton** [comment]
@jonathansampson ah ok- I'll mark this as no QA needed for now 😄  (especially since you've already tested)
