### ISSUE TITLE
smooth scolling should be enabled as default

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#7780]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
new brave profiles start with disabled smooth scrolling
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
latest master 6f9a4f2397c620012603c49635f846c9280926e2
- Steps to reproduce:
    1. delete all brave settings
    2. start brave
    3. scroll on any large page 
    
- Actual result:
 scrolling is bumpy and feels bad
- Expected result:
smooth scrolling as default
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

i wonder why anyone would want to have not smooth scrolling and if more than 1 % of users have gpus that hickup with that feature enabled

**Comment by Liunkae** [comment]
@lucidNTR What type of mouse or trackpad are you using? My Mac trackpad works fine even with smooth scrolling disabled.

**Comment by lucidNTR** [comment]
@Liunkae I am not talking about a bug or unexpected behaviour, i am just arguing that a setting called 'smooth scrolling' should be enabled by default if it is stable enough not needed to be called 'smooth scrolling, experimental!!! use at your own risk!!!'
The fps difference is still visible and annoys me so i always turn on the smooth scrolling (macbook standard trackpad)

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/should-smooth-scrolling-be-enabled-by-default/10192

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
