### ISSUE TITLE
dashboard time display should respect local time format

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#7781]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
 dashboard shows PM/AM time which is not used in germany, even though system time settings are set to 24h format
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
6f9a4f2397c620012603c49635f846c9280926e2 latest master
- Steps to reproduce:
    1. open brave
    2. select 'Dashboard' as new tab option from settings
    3. open new tab
    
- Actual result:
time is displayed in PM/AM format
- Expected result:
time is displayed in localized format according to system settings
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by bsclifton** [comment]
Similar to https://github.com/brave/browser-laptop/issues/5647 (ideal solution would close both issues)
