### ISSUE TITLE
display flicker on tile hover in dashboard

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#7782]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
hovering a link tile in the dashboard has a white overlay flicker
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
6f9a4f2397c620012603c49635f846c9280926e2
- Steps to reproduce:
    1. open dashboard
    2. add a link tile
    3. hover on empty space in dashboard
   4. hover obove link tile
    
- Actual result:
there is a white overlay flicker above the background image
- Expected result:
no flicker effect should be present
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by cezaraugusto** [comment]
I guess this is fixed already let me know otherwise and we'll re-open. thanks!
