### ISSUE TITLE
the interface for session tabs is awkward

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#7783]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
it feels awkward to have pre-created session tabs numbered 1 -9
instead, the options should just include already used sessions and allow to add extra session. maybe with optional session name.
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
6f9a4f2397c620012603c49635f846c9280926e2
- Steps to reproduce:
    1. open brave
    2. long click new tab + button
    3. open session tab menu
    
- Actual result:
i always see prefcreated 1-9 session numbers
- Expected result:
see screenshot
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
current:
<img width="1312" alt="screenshot 2017-03-18 15 54 31" src="https://cloud.githubusercontent.com/assets/1176068/24073269/29e56da8-0bf5-11e7-9e9b-749f8f2d70d1.png">

example behaviour:
<img width="1680" alt="screenshot 2017-03-18 16 08 00" src="https://cloud.githubusercontent.com/assets/1176068/24073271/3dadc682-0bf5-11e7-8c20-0db41003f905.png">

**Comment by cezaraugusto** [comment]
I like it

/cc @bbondy @bradleyrichter

**Comment by lucidNTR** [comment]
@cezaraugusto the old interface or the proposal? :-D

**Comment by cezaraugusto** [comment]
sorry I meant the proposal :)

**Comment by bradleyrichter** [comment]
Ha! The suggestion is what I had in my head. Not offering all 9 as was implemented. Ok, sorry. This was lacking in the spec department.  :  )

**Comment by alexwykoff** [comment]
Hey @bradleyrichter can we triage this out past 1.0 ?

**Comment by bradleyrichter** [comment]
@alexwykoff I'd prefer not to...needs a dev time estimate first.

**Comment by bsclifton** [comment]
I don't think this would be terribly difficult to do and would provide a nicer experience.  Good bang for the buck 😄

**Comment by midi** [comment]
Firefox has implemented sessions with pretty good UI/UX:
https://testpilot.firefox.com/experiments/containers

I prefer this over Brave's approach.
The ability to set names, icons allows me to easily keep track of my sessions.
Also the fact that I can just pick a session upon hovering over the new tab button is awesome.
Maybe consider this implementation.

**Comment by twisterghost** [comment]
Definitely would like to be able to name the sessions. Helps to identify which one to use when splitting across several.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/34
