### ISSUE TITLE
OSX 10.11, node 5.6 Build Error related to cppunitlite

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#779]
1. npm install fails when trying to build cppunitlight on https://github.com/brave/browser-laptop/commit/d14adf9adaec0d759084ad5b59535f3ca5c4088e Log Attached to this Issue.
2. Issue  Also Opened at maintainer [cppuitlite github](https://github.com/smikes/CppUnitLite/issues/5)
OSX 10.11, Node 5.6, npm 3.6.0
3. Log: [log.txt](https://github.com/brave/browser-laptop/files/131281/log.txt)

I also noticed that for whatever reason code for this build on TravisCI has zero errors when a build was attempted: https://travis-ci.org/brave/browser-laptop/builds/109349643#L79

**Comment by weems** [comment]
@bbondy does this happen for you on npm install in git:master? still happening to me

**Comment by bbondy** [comment]
Are you using node 5.6?

**Comment by weems** [comment]
@bbondy # weems on git:master o [20:17:52]
$ node -v
v5.6.0

**Comment by bbondy** [comment]
Did you have that the first time you did npm install? If not please clear the node_modules dir and then try again. Lots of people are building without issues and use npminstall so I'm not sure what it is off hand.  The log doesn't give a lot of detail that I can see.

**Comment by weems** [comment]
"make: *** [Release/obj.target/CppUnitLite/src/Failure.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/weems/code/brave/browser-laptop/node_modules/cppunitlite
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok" // Something in my XCode Toolchain may be amiss..

**Comment by weems** [comment]
@bbondy cleared node_modules. Still seeing:

Build errors with cppunitlite
Errors: [error.txt](https://github.com/brave/browser-laptop/files/133622/error.txt)

**Comment by weems** [comment]
@bbondy More Verbose Log
```
176927 verbose lifecycle cppunitlite@1.0.0~install: CWD: /Users/weems/code/brave/browser-laptop/node_modules/cppunitlite
176928 silly lifecycle cppunitlite@1.0.0~install: Args: [ '-c', 'node-gyp rebuild' ]
176929 silly lifecycle cppunitlite@1.0.0~install: Returned: code: 1  signal: null
176930 info lifecycle cppunitlite@1.0.0~install: Failed to exec install script
176931 verbose unlock done using /Users/weems/.npm/_locks/staging-dae34d1ec9187275.lock for /Users/weems/code/brave/browser-laptop/node_modules/.staging
176932 silly rollbackFailedOptional Starting
176933 silly rollbackFailedOptional Finishing
176934 silly runTopLevelLifecycles Starting
176935 silly runTopLevelLifecycles Finishing
176936 silly install printInstalled
176937 verbose stack Error: cppunitlite@1.0.0 install: `node-gyp rebuild`
176937 verbose stack Exit status 1
176937 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
176937 verbose stack     at emitTwo (events.js:100:13)
176937 verbose stack     at EventEmitter.emit (events.js:185:7)
176937 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
176937 verbose stack     at emitTwo (events.js:100:13)
176937 verbose stack     at ChildProcess.emit (events.js:185:7)
176937 verbose stack     at maybeClose (internal/child_process.js:827:16)
176937 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
176938 verbose pkgid cppunitlite@1.0.0
176939 verbose cwd /Users/weems/code/brave/browser-laptop
176940 error Darwin 15.2.0
```

**Comment by weems** [comment]
Go to https://developer.apple.com/downloads/ and download the latest Command Line Tools by Searching there. Look for the one for your Version of OSX, in my case OSX 10.11 (Dec 2015 or Newest). Closing, a future user may benefit from this solution.

**Comment by GeneGenie** [comment]
This didn't help me.
