### ISSUE TITLE
Unfocused URLbar text selection behavior is incorrect

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#7792]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If the URLbar is not focused, selecting part of URL text results in incorrect behavior. See the screencast below. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.13.5 (1db81cb)

- Steps to reproduce:
    1. Open a new tab and navigate to any site.
    2. Click anywhere besides the URLbar to make sure the URLbar is not focused.
    3. Start dragging in the middle of the URLbar's text to select a part of the URL.
    
- Actual result:
The selection starts at the beginning of the URL.

- Expected result:
The selection should start where mouse drag began.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Likely.

- Is this an issue in the currently released version?
Yes, 0.13.5.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a new tab and navigate to any site.
    2. Click anywhere besides the URLbar to make sure the URLbar is not focused.
    3. Start dragging in the middle of the URLbar's text to select a part of the URL.
    4. Make sure the text selection begins where the mouse drag started.

- Screenshot if needed:
Screencast:
![](https://cloud.githubusercontent.com/assets/19424103/24074420/2894993e-0bd6-11e7-8477-127a7f897d27.gif)

- Any related issues:
None.

**Comment by bsclifton** [comment]
Unable to reproduce this one- I believe it was fixed (if DPI related, possibly by my last set of changes ~0.15.x-ish?)

**Comment by bsclifton** [comment]
I close prematurely- I'm able to clearly reproduce this now.  I didn't properly unfocus the URL bar
