### ISSUE TITLE
Ubuntu: Brave doesn't know that it's the default browser.

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#7800]
Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.0-42-generic 
os.arch: x64

I recently switched from using Ubuntu/Unity to Ubuntu/XFCE. I have Brave set as the default browser but Brave doesn't seem able to recognise this on startup so I get prompted about that every single startup. However, other applications do start Brave or use an existing instance when opening urls.

![image](https://cloud.githubusercontent.com/assets/15019644/24139232/3c0a8e6c-0e13-11e7-9073-263b38dfeadc.png)

**Comment by jonathansampson** [comment]
Confirmed.

![ubuntu-default](https://cloud.githubusercontent.com/assets/815158/24584296/d37a37f6-172e-11e7-91e9-da2bb4f3d948.gif)

**Comment by Liunkae** [comment]
Based on @jonathansampson's screencast (Unity), this may be a problem with any desktop environment on Ubuntu.

**Comment by jonathansampson** [comment]
@bbondy Reported seeing this as well. @darkdh was able to repro with a fresh install.

**Comment by CliqueBait** [comment]
I don't think this is fixed. Also, is step 1 of the Test Plan really asking me to uninstall `gawk` (a core utility in linux systems) ?

**Comment by darkdh** [comment]
Sorry, the test steps is a little confusing.
Step 1 is make sure you don't have gawk in your system. When you install Brave, it will show you that you need to install gawk as dependency.
Before this, we didn't ask user to install gawk. So it will fail to set as default silently.
