### ISSUE TITLE
Add bookmark context menu

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7801]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Add bookmark is not working in the context menu on a Bookmarks manager page
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
44d8279
- Steps to reproduce:
    1. go to about:bookmarks
    2. right click in a bookmarks area (right side)
    3. select Add bookmark
    
- Actual result:
Noting happens
- Expected result:
Add bookmark dialog should be opened
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by NejcZdovc** [comment]
@bsclifton should we add this to 0.14.0?

**Comment by bsclifton** [comment]
@NejcZdovc yes- great catch (and thanks for the quick fix 😄 )
