### ISSUE TITLE
Blank tabs bar appears after increasing the number of tabs per tab set

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7806]
## Test plan

https://github.com/brave/browser-laptop/pull/9773#issue-239452018

----

**Describe the issue you encountered:**
the tabs bar becomes blank after increasing the number of tabs per tab set under a condition. I believe the same kind of issue had been fixed once and then regressed, recently or not.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): 64b381a

- Steps to reproduce:
    1. Open about:preferences#tabs
    2. Set the number of tabs per tab set to 6
    3. Open new tabs to create a new tab set, which has just **2** tabs
    4. Increase the number to 8
    
- Actual result: the blank tabs bar which has zero tabs appears
<img width="90" alt="screenshot 2017-03-21 23 07 46" src="https://cloud.githubusercontent.com/assets/3362943/24151157/4578e2a0-0e8b-11e7-905a-82000c058287.png">

- Expected result: the 2nd tab set should be closed

- Any related issues:

**Comment by cezaraugusto** [comment]
can't repro per str, can you confirm?

**Comment by bsclifton** [comment]
@luixxiul is this still an issue? I'll close and assign to 0.17.x so we can retest

**Comment by srirambv** [comment]
This is still reproducible if the 8th tab opened is preferences and change the tabset count to 8 then you get the empty tabs bar
![7806](https://user-images.githubusercontent.com/17010094/27676754-138e2074-5ca7-11e7-97e0-5384a8367b06.gif)

This is been a known issue when you have tabsets and if you close the single tab in a new set it shows empty tabs bar. And the behavior is still same even if you have pinned tabs

**Comment by NejcZdovc** [comment]
@bsclifton I created a fix for this one, so if we want to pull this into 0.18, please change milestone for this issue and connected PR

**Comment by luixxiul** [comment]
should we pull the issue to 0.18 if the fix works?

**Comment by bsclifton** [comment]
Pulling into 0.18.x sounds great (if the fix works and there are sufficient tests) 😄

**Comment by NejcZdovc** [comment]
I am trying to add test, but context is messing with me :smile:
