### ISSUE TITLE
Specify Zoom Level in UI

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#781]
1. Command / Control ++ increases Font Size
2. A User has Sent a Support Req Asking Like Chrome if Brave can show you in a UI Control what Zoom Percentage Level You are Currently at and ability to Zoom in or Out using the Mouse.

**Comment by bbondy** [comment]
@bridiver this seemed to have regressed, command+= used to work.

**Comment by weems** [comment]
@bbondy if my version is the latest and I think it is, you can zoom with the keyboard shortcut but you cant then scroll in and out using UI control.

**Comment by bridiver** [comment]
```const Config = require('../constants/config').default``` previously required ```.default``` to work, but now for some reason it has to be removed. navigationBarTest.js also has ```.default```, but nothing else does

**Comment by bbondy** [comment]
The shortcut was actually only broken on master and not a released build. This issue is about adding UI for zoom.

**Comment by bridiver** [comment]
oops, sorry. Didn't look closely enough at the issue

**Comment by bradleyrichter** [comment]
The request is to add this feedback/toolbar UI element from Chrome. Let's put it in the P2 or 3 column until we hear more requests. I may use a different approach.

![screen shot 2016-02-18 at 2 19 15 pm](https://cloud.githubusercontent.com/assets/13509546/13160230/0437fa8e-d64b-11e5-950a-091131ccc891.png)

**Comment by bbondy** [comment]
It's added to the hamburger menu for now, which is good enough for now.  So closing this.

<img width="170" alt="screenshot 2016-04-20 17 21 40" src="https://cloud.githubusercontent.com/assets/831718/14690898/69da63d4-071c-11e6-8561-376c0e3efd89.png">
