### ISSUE TITLE
Support Extension Option Pages

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7812]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave does not fully support Chrome-style option page settings.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/8b8cf36ead29358988fa834fe3c79cdc346705ab

### Needed Manifest Support:
- [ ] `manifest.options_ui` If not present, we should look for `manifest.options_page`.
- [ ] `manifest.options_ui.page` Required if `options_ui` is present.
- [ ] `manifest.options_ui.chrome_style` Recommended. Adds a user agent stylesheet to the content for consistent styling with the Browser itself.
- [ ] `manifest.options_ui.open_in_tab` Discouraged. Causes the options page to open in the deprecated manner.

### Needed API Support:
- [ ] [`chrome.storage.sync`](https://developer.chrome.com/extensions/storage#property-sync) Persists option settings across devices.
- [ ] [`chrome.runtime.openOptionsPage`](https://developer.chrome.com/extensions/runtime#method-openOptionsPage) Navigates to `manifest.options_ui.page || manifest.options_page`. If the _Options_ page is already opened, this will cause it to be re-focused.

### Other Needed Support:
- [ ] Option pages should be accessible from within _about:extensions_.

- Any related documentation: https://developer.chrome.com/extensions/optionsV2

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
cc: @kevinlawler
