### ISSUE TITLE
Audio indicator has extra bottom padding compared to favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7815]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Audio indicator has extra bottom padding compared to favicon

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	64b381a

- Steps to reproduce:
    1. Open any audio/video site and play to show the audio indicator
    2. Position of the icon is off compared to favicon
    @cezaraugusto confirmed its fine on macOS and Linux. Issue on Windows only

- Actual result:
Audio indicator has extra bottom padding compared to favicon

- Expected result:
Should be at same level as favicon

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24165343/0405db70-0e68-11e7-801b-536084f55518.png)

- Any related issues:
cc: @cezaraugusto

**Comment by bsclifton** [comment]
@cezaraugusto can you check this out?
