### ISSUE TITLE
Bookmark submenu in kabob menu is not dismissed when moved away 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7816]
## Test plan
1. Click on Kabob menu 
2. Mouse over bookmarks to bring up the submenu
3. Move mouse over to Zoom, sub menu is no longer shown

(see below GIF for how it behaves before this patch)

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmark submenu under kabob menu is not dismissed when moved away 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x65

- Brave Version (revision SHA):
Brave	0.14.0
rev	64b381a

- Steps to reproduce:
    1. Click on Kabob menu 
    2. Mouse over bookmarks to bring up the submenu
    3. Move mouse over to Zoom, sub menu is still shown
    4. Mouse over to Shields, sub menu is dismissed
    
- Actual result:
Bookmark submenu under kabob menu is not dismissed when moved away 

- Expected result:
Submenu should be dismissed when moved away from bookmark option

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![kabob_bookmark](https://cloud.githubusercontent.com/assets/17010094/24166334/ceda72c8-0e6a-11e7-9b9c-8857a249ac47.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Removing milestone and tagging with `good-first-bug` 😄
