### ISSUE TITLE
Twitch.tv support

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#782]
Findings: 
- iPad  UA doesn't work and annoyingly asks you to download the app with alerts.
- Safari UA doesn't load anything but doesn't show video

**Comment by weems** [comment]
@bbondy is this due to flash plugin incompatibility? or does twitch use HTML5 <video> and this is another issue entirely?

**Comment by bbondy** [comment]
yes due to flash. It seems like we can support Twitch.tv though by appending `&html5` to the iframes.
https://www.reddit.com/r/Twitch/comments/3pip76/userscript_to_use_full_html5_on_twitchtv/

**Comment by bbondy** [comment]
Verified and that does work.  This requires some https refactoring to use filtering.js first and then we can do it.

**Comment by bbondy** [comment]
I emailed Twitch support as well to ask if they can just always serve us html5 based on our user agent. If I don't get a response we can move forward with this fix.

**Comment by bbondy** [comment]
This was released with 0.8.1
