### ISSUE TITLE
Add update status to extensions panel

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7822]
Extensions panel is being added to About:preferences with https://github.com/brave/browser-laptop/issues/6530

This issue would be a follow up to that. We want to allow the user to be notified when there are new extensions. See the toggle here at the top of this mockup:
![pasted image at 2017_02_27 04_21 pm](https://cloud.githubusercontent.com/assets/4672033/23386095/4006dde0-fd33-11e6-9ed2-0b5ed9e94127.png)

If this is true, we'll want to capture events and show the notifications to the user.

@bradleyrichter did you have any mockups for how the notifications should look? Or would we want to use our existing notification bar?

**Comment by bradleyrichter** [comment]
Existing is fine…

**Comment by bsclifton** [comment]
Issue is to track when updated happened (via component updater).  Would be cool to have a similar notification for when new extensions are added to the store
