### ISSUE TITLE
bitwarden: unknown title and description on about:extensions

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7826]
**Describe the issue you encountered:**

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24185475/b2b44040-0f16-11e7-8179-0a6f6cbbf420.jpg)

CC @kspearrin

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.0 Preview 4

- Steps to reproduce:
    1. Enable bitwarden
    2. Open about:extensions
 
- Expected result: the title and description should be specified

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #4776

**Comment by bsclifton** [comment]
related https://github.com/brave/browser-laptop/issues/7683

@jonathansampson is there something we're doing wrong?

**Comment by kspearrin** [comment]
https://developer.chrome.com/extensions/i18n

>In manifest.json and CSS files, refer to a string named messagename like this:
>
>__MSG_messagename__

**Comment by bsclifton** [comment]
Kicking this out of 0.14.0 since this is also a problem with Dashlane (see https://github.com/brave/browser-laptop/issues/7683)

**Comment by jonathansampson** [comment]
@bsclifton I'll check both Dashlane and bitwarden in parallel while addressing this. Thanks!

**Comment by bsclifton** [comment]
Marking as `release-notes/exclude` and `QA/no-qa-needed` because bitwarden is currently disabled
