### ISSUE TITLE
Add an about:contributors page

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7828]
Brave is a really unique project and we have a lot of great folks contributing to this project 🦁 

We should be offering an about page (ex: about:contributors) to honor and give credit to all the folks who have contributed time and effort to the project.  It's important to call out folks that helped with any aspect of the project:
- Community management
- Issue triage
- Code
- Testing
- Translations
- other

Code or project contribution information can be pulled from GitHub fairly easy, while other information (translations, triage, etc) is doesn't have a rock solid way to characterize or collect stats for. Some of the information may need to be manually collected

**Comment by srirambv** [comment]
+1

**Comment by kumarrishav** [comment]
@bsclifton Is there any plan How we should go for this?

**Comment by bsclifton** [comment]
@kumarrishav no plan (yet)... Do you have a proposal?

Here are a few sub-tasks we can do:

- [ ] Create a skeleton `about:contributors` page (it can be empty)

- [ ] Write a util module which queries GitHub for `brave/browser-laptop` and pulls contributor stats.  We'd want to exclude `Members` of the Brave organization since this issue is focused on our awesome contributors and community 😄 

- [ ] Once we have some basic stats being fetched, I don't think it would be hard to wire that up to the about:contributors page. I'd suggest starting off by randomizing the names of the contributors and displaying them in a UL block with a format like <a href="github home page">Name shown on GitHub</a>

**Comment by kumarrishav** [comment]
@bsclifton sure, let me do some research and brainstorming on this. For now we will start with empty `about:contributors` page.

**Comment by Jacalz** [comment]
Should there be both code contributors and other contributors or just code contributors? Also displaying a short text of what they are doing might be one thing to add 😉

**Comment by kumarrishav** [comment]
It should be (and will be) for all type of contributors. It's just it's easy to fetch data from github and populate but for others, we are still thinking how to get their contributions. One way is manual, any ideas @Jacalz  ?

**Comment by NejcZdovc** [comment]
I would first add github and then in next iterations add additional services.

**Comment by srirambv** [comment]
@bsclifton @NejcZdovc rough mockup for about:contributor 
![image](https://cloud.githubusercontent.com/assets/17010094/25800823/cbe6f1c0-33e2-11e7-85d0-a1fd23b39082.png)

cc: @bradleyrichter for thoughts

**Comment by luixxiul** [comment]
Also https://www.libreoffice.org/about-us/credits/ for reference

**Comment by bsclifton** [comment]
@Jacalz +1 on what @NejcZdovc said 😄  

To get started, getting the code contributors would be a first great step.  The next step (which we can do concurrently, if you're interested) would be to query `community.brave.com` and get some of the contributor stats there.

Moving into more difficult areas:

We'll also need to find a reliable way to get the list of folks...
- providing translations
- helping with issue triage
- who help with testing and quality assurance

It would be ideal if this was calculated programmatically, so that we don't have to roll up the data by hand.  Any suggestions appreciated 😄 

- We might be able to gets stats on issue triage by looking at who adds labels to issues and also who closes issues (for example as dupes)
- transifex should have an owning author for each string in our translations by language
- QA runs all use similar titles; we could search / detect these on GitHub and look at the creator

**Comment by Jacalz** [comment]
The last three looks really promising and the community stuff would be good but it is hard updating the about:community every time somebody makes a contribution to the community if we should include stats one how has done the most 😬 I know @alex showed a picture of the community statistics but I don't know where to find it my self on the community itself 😅 Qa should be easy and it also might be possible to create a script that looks for the test label but I don't quote me in that 😉

**Comment by srirambv** [comment]
I think fetching data from community would require admin access. Not sure how easy it is to pull data into `about:contributor`. 

cc: @alexwykoff

**Comment by bsclifton** [comment]
@srirambv even if it does require admin access, once we have a Jenkins instance setup, we can pull the stats once a week and commit into the `browser-laptop` repo as JSON (or similar) 😄

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/836
