### ISSUE TITLE
Upload photo in linkedin issue

### ISSUE THREAD

**Issue by xixoft** [brave/browser-laptop#783]
I have an issue when uploading photo to linkedin suddenly the browser has stopped working.

**Comment by diracdeltas** [comment]
which version are you on? worked fine for me just now.

possibly same underlying issue as #784

**Comment by diracdeltas** [comment]
marking this as dupe of https://github.com/brave/browser-laptop/issues/475

**Comment by bbondy** [comment]
Closing
