### ISSUE TITLE
Zoom is not saved when you close the browser and restore on a single site

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7832]
**Describe the issue you encountered:**
Zoom is not saved when you close the browser and restore on a single site.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): 0.14.0 Preview 4

- Steps to reproduce:
    1. Test zoom saved when you close the browser and restore on a single site.
    
- Expected result: Zoom should be saved when you close the browser and restore on a single site

- Will the steps above reproduce in a fresh profile? Yes

- Any related issues:

**Comment by bsclifton** [comment]
Closing issue as it was fixed with 5f39fbf; next Muon build will include it
