### ISSUE TITLE
autofill dialog appears in a moment and disappears after saving and deleting password

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7835]
**Describe the issue you encountered:**
autofill dialog appears in a moment and disappears after saving and deleting password.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.0 Preview 4

- Steps to reproduce:
    1. Go to https://trac.torproject.org/projects/tor/login
    2. Log in and save your password can be saved.
    3. Open about:passwords
    4. Delete the password
    5. Reload https://trac.torproject.org/projects/tor/login
    6. Input your username
    
- Actual result: autofill dialog appears in a moment and disappears

- Expected result: the dialog should not disappear

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
This affects autofill on http://www.roboform.com/filling-test-all-fields

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/7768?

**Comment by srirambv** [comment]
Yes its the same  for saved credentials and autofill suggestion.

**Comment by srirambv** [comment]
Closing in favor of #7768
