### ISSUE TITLE
Crash every time I tried to upload file

### ISSUE THREAD

**Issue by vikingkarwur** [brave/browser-laptop#784]
When using Brave for Mac, it Crash every time I tried to upload file.

**Comment by weems** [comment]
What website does this happen on?

**Comment by vikingkarwur** [comment]
- last time crashed : ultrapress.com
Before that it happen' when I tried to upload photos in facebook

**Comment by stephanebachelier** [comment]
I confirm the same issue on brave for Mac.
I was uploading a zip on ghost.io to change the theme. Each time I've tried Brave crashed.

**Comment by diracdeltas** [comment]
What versions are you on? I think I previously saw the crash on fb photo upload but not when I tried just now.

**Comment by diracdeltas** [comment]
I'm guessing this is a duplicate of https://github.com/brave/browser-laptop/issues/475. If you upgrade to the latest electron-prebuilt (`rm -r ~/.electron`, `rm -r node_modules/electron-prebuilt`, `npm install`), it should be fixed.

**Comment by bbondy** [comment]
Closing since no response for 5 days and likely a dupe.
