### ISSUE TITLE
Add support for LessPass (stateless open source password manager)

### ISSUE THREAD

**Issue by edouard-lopez** [brave/browser-laptop#7846]
LessPass focus on privacy and manage your passwords directly from your browser, they never leave your device and [passwords are never stored](https://github.com/lesspass/lesspass/wiki/FAQ). We use a `site`, a `login` and a` master password` to generate a unique password. So no need to sync your password vault across every device. [Learn more](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4).

All our supported platform are build around a core `NPM` module with a clean api used to create passwords that should be easy to port to Brave (as we already support [Android](https://github.com/lesspass/cordova), [Chrome and Firefox](https://github.com/lesspass/webextension), [Cozy Cloud](https://github.com/lesspass/cozy), [Linux distros](https://github.com/lesspass/snap), [Terminal](https://github.com/lesspass/cli)).

### Screenshot

In current supported browser, we integrate as a pop-up extension.
![demo-2 3 x](https://cloud.githubusercontent.com/assets/1212392/24217179/44f573ac-0f3f-11e7-9a22-58318ee97dea.gif)

## 

### Related issues

* brave/browser-laptop#253 - Is there any plans for enabling easy addons like Chrome or Firefox? Does this functionality already exist? #253
* lesspass/lesspass#176: Add extension support to Brave browser #176

**Comment by edouard-lopez** [comment]
I managed to run the extension in `brave` following [Developer-Notes-on-Installing-or-Updating-Extensions](/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions).

### Install

    sudo apt-get install libgnome-keyring-dev
    git clone --depth 1 git@github.com:brave/browser-laptop.git
    cd browser-laptop
    yarn install    

### Add extension 

Copy it from **Chromium** extensions' directory: 

    $HOME/.config/chromium/Profile 1/Extensions/lcmbpoclaodbgkbjafnkbbinogcbnjih

to **Brave** extensions' directory:

    browser-laptop/app/extensions/

### Load the extension

Edit _browser-laptop/app/extension.js_ to add the following lines:

```
// lesspass
config.myExtensionId = 'lcmbpoclaodbgkbjafnkbbinogcbnjih';
config.myExtensionPathToManifest = 'lcmbpoclaodbgkbjafnkbbinogcbnjih/2.3.5_0';
extensionInfo.setState(config.myExtensionId, extensionStates.REGISTERED)
loadExtension(config.myExtensionId, getExtensionsPath(config.myExtensionPathToManifest))
```

### Run

On one terminal

    yarn watch

On a second terminal

    yarn install

### Demo time :tada: 
![brave lesspass-extension](https://cloud.githubusercontent.com/assets/1212392/24226035/66514f4c-0f64-11e7-9ea2-df14e5e3cab0.gif)

**Comment by bsclifton** [comment]
cc: @jonathansampson

**Comment by edouard-lopez** [comment]
Should I submit a pull with my modification of _extensions.js_? It seems a bit rough as the extension will always be shown in the toolbar.
Where is the doc if I want to integrate in the same way as 1Password/Dashlane/LastPass?

**Comment by bsclifton** [comment]
@edouard-lopez there isn't a doc showing how to integrate like 1Password/Dashlane/LastPass... yet

I created a stub here which I'll be updating here over the next few minutes 😄 
https://github.com/brave/browser-laptop/wiki/Password-manager-support

**Comment by bsclifton** [comment]
@edouard-lopez I just finished updating the doc above; please let me know if the information is useful 😄  There should be enough info there for you to generate PRs against the 3 repos we have

**Comment by edouard-lopez** [comment]
Thanks @bsclifton, after some discussion we are limiting our project's scope to focus on some feature.
I'm closing this, as the extension is functional, we will wait for Brave to enable web extension.

**Comment by edouard-lopez** [comment]
[Extension preferences has landed](https://github.com/brave/browser-laptop/issues/6530), hopefully it will be possible to install LessPass extension soon

**Comment by jonathansampson** [comment]
@edouard-lopez Thank you for the update!

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/add-lesspass-password-manager-extension-to-brave/6667?u=eljuno

**Comment by jonathansampson** [comment]
@edouard-lopez When you tested this, were all primary user-scenarios covered, or did you run into issues (other than the broken keyboard command) that weren't working entirely?

I'd love to see LessPass move forward :)

**Comment by edouard-lopez** [comment]
Everything was working fine

**Comment by jonathansampson** [comment]
@edouard-lopez This is great to hear. I'll speak with some of the team about adding support for LessPass!

**Comment by edouard-lopez** [comment]
Thanks @jonathansampson this will help speed up process and streamline update of the extension.

If you need information feel free to ping [me](https://mobile.twitter.com/edouard_lopez) or [guillaume](https://mobile.twitter.com/guillaume20100) on twitter or [submit issue](https://github.com/lesspass/lesspass/issues/new).

**Comment by edouard-lopez** [comment]
Can I be of some help to push this forward?

**Comment by bsclifton** [comment]
This is something we won't be able to get to- closing as `wontfix`

However, with [brave-core](https://github.com/brave/brave-browser), potentially anything in the Chrome Web Store would be available (so this is resolved with brave-core)
