### ISSUE TITLE
outdated npm dependencies 

### ISSUE THREAD

**Issue by ShalokShalom** [brave/browser-laptop#7855]
- Describe the issue you encountered:
I compile brave with npm and get messages about outdated versions. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
KaOS
- Brave Version (revision SHA):
13.5
- Actual result:
npm complains about outdated depends
- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
Yes.
- Screenshot if needed:
![screenshot_20170323_114633](https://cloud.githubusercontent.com/assets/6344099/24244252/60e1b0ec-0fbe-11e7-961a-14a8f6db7bef.png)

**Comment by develar** [comment]
Relates to #7857 (new version of electron-builder will reduce number of warnings due to updated and reduced set of dependencies).

**Comment by diracdeltas** [comment]
related: https://github.com/brave/browser-laptop/issues/1701#issuecomment-335205225

**Comment by ShalokShalom** [comment]
How critical is this, in security terms?

**Comment by diracdeltas** [comment]
probably low or medium? we use NSP to scan for modules with known vulnerabilities

**Comment by ShalokShalom** [comment]
Aha, ok. Thanks a lot
