### ISSUE TITLE
Migrate to electron-builder since it has muon support now

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7857]
electron-builder now supports muonVersion so I think we can use that directly now.
https://github.com/electron-userland/electron-builder/issues/1394#issuecomment-288341537

**Comment by luixxiul** [comment]
Related: should we change `electron` on this line to `Muon`?
https://github.com/electron-userland/electron-packager/blob/53e4606388829299d89c344a55e830d73324be93/index.js#L66

**Comment by develar** [comment]
@luixxiul Thanks, fixed (https://github.com/electron-userland/electron-builder/commit/42415214ee28a0dff2cf22a3e3af792acb672208).

**Comment by luixxiul** [comment]
@develar thanks!!

**Comment by posix4e** [comment]
https://github.com/brave/browser-laptop/pull/10633 <- Is pretty close it still needs

- [ ] To fix the icon
- [ ] To fix the sandbox in some platforms (although this can be a later issue i think)
- [ ] To fix the homepage
