### ISSUE TITLE
Lion icon badge

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7859]
We would like to add badge to the lion icon in the top right. Badge will display how many ads and  trackers were blocked on a current site

![8f0fe246-ed3a-11e6-9e97-92e1cfcaa539](https://cloud.githubusercontent.com/assets/9574457/24265656/8870d9bc-1004-11e7-881e-bea0356431b8.png)

**Comment by NejcZdovc** [comment]
Suggestion by @jonathansampson:

1. Counter-tab is visible once page begins loading.
2. As resources are blocked, the number increments out in the open.
3. Once the page is done loading, the Counter-tab slides in behind the Icon.
4. The Counter-tab is revealed on hover.

Demo: https://jsfiddle.net/eh6rmLy6/3/

**Comment by luixxiul** [comment]
Adding min-width:7px makes the badge square.

<img width="34" alt="screenshot 2017-03-24 11 00 58" src="https://cloud.githubusercontent.com/assets/3362943/24277562/2fa95df4-1081-11e7-9acc-637efcf3c3ab.png">

I think this is better. what do you think?
