### ISSUE TITLE
Create a new about:flags (similar to chrome://flags)

### ISSUE THREAD

**Issue by freebrowser1** [brave/browser-laptop#7860]
- Describe the issue you encountered: 
chrome:flags as in Chrome (or Brave on Android where it does work) does not work.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.5 (Chromium 56)

- Steps to reproduce:
1. Type chrome:flags in the URL and it does not work.
    
- Actual result:
Search engine result.

- Expected result:
The same extended settings as in Chrome or in the Android version of Brave.
- Can this issue be consistently reproduced?
Yes

**Comment by Liunkae** [comment]
Same as #545 (Implement about:config)?

**Comment by freebrowser1** [comment]
Not exactly as that issue was closed without action, hence I add a new one.

**Comment by jonathansampson** [comment]
+1 from a prominent developer in the community. I have to agree too; there are a lot of great features in experimental flags that should be exposed to super-users and developers.

**Comment by srirambv** [comment]
This will be out-of-box feature in brave-core, c 😄 

Closing the issue as fixed-with-brave-core
