### ISSUE TITLE
Brave needs an IRC channel 

### ISSUE THREAD

**Issue by oscalation** [brave/browser-laptop#7862]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: Upon experiencing some troubles with Brave, I immediately headed to IRC, freenode specifically, only to find out that Brave is not present on IRC. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Every 

- Brave Version (revision SHA): Any

- Steps to reproduce:
    1. Fire up your IRC client
    2. Join freenode
    3. search for Brave
    4.  Be sad

**Comment by bsclifton** [comment]
@oscalation we do have a Slack channel which we invite contributors to (no automation around getting access yet though).  Would this be something you're interested in?

**Comment by jonathansampson** [comment]
Also worth noting that you can engage with us over at https://community.brave.com as well 🙂

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/how-many-of-you-would-you-want-to-use-irc-channel-for-brave/10193

If you are still around here, would you please join the conversation there to talk about the suggestion further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
