### ISSUE TITLE
Brave cannot whitelist local self-signed https:// websites

### ISSUE THREAD

**Issue by freebrowser1** [brave/browser-laptop#7868]
- Describe the issue you encountered:
When entering a https://localhost (or any other internal address), it issues a certificate error, just as it were an internet website with an invalid certificate.
After ignoring this (i.e. say it is safe) it does not retain its exception.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13,5

- Steps to reproduce:
    1. Go to https://localhost (or any other local non-internet domain) assuming a local webserver is running on that server with a self-signed certificate.
    2. Click on 'Advanced settings' => Ignore and you see the website
    3. Here it goes wrong: Open a new tab with the same https URL and the problem repeats, it is not saved.
    
- Actual result:
This site cannot be loaded due to a certificate error: https://www.bing.com/search?q=vmkladm
net::ERR_CERT_COMMON_NAME_INVALID

- Expected result:
After the steps 'Advanced settings' => Ignore the URL should be whitelisted for subsequent uses. For developing sites in a local envrironment this is very useful. Safari and Firefox are able to whitelist such sites.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

**Comment by luixxiul** [comment]
CC @diracdeltas

**Comment by freebrowser1** [comment]
Added screenshot.

![screen shot 2017-03-26 at 10 52 36](https://cloud.githubusercontent.com/assets/26625141/24329854/6dd35296-1212-11e7-8fa0-b358ebadca35.png)

**Comment by diracdeltas** [comment]
When I click 'allow' on https://localhost with a self-signed cert, it remembers the decision until I close Brave. Also on mac os 0.13.5.

The cert exception domains are saved in-memory at https://github.com/brave/browser-laptop/blob/master/app/index.js#L90, in case you want to try debugging this.

**Comment by byroniac** [comment]
We use Quest Rapid Recovery at work for our backup solution, and it uses web-based management for all the backup cores which use self-signed certificates and generate this error when trying to browse them with Google or Brave. So it is a real-world problem for what it is worth. I even tried importing the certificate in Windows to various stores and have not been able to resolve the error (apparently Brave bypasses what you do with certmgr.msc but Edge accepts the new certificate).
