### ISSUE TITLE
Element inspector only in separate window

### ISSUE THREAD

**Issue by freebrowser1** [brave/browser-laptop#7869]
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
The Element Inspector can only be a popup window which is very annoying as it requires repeatedly switching between the browser tab and the inspector. Not very intuitive.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.13.5

- Steps to reproduce:
    1. Open 'Inspect Element'
    
- Actual result:
  A popup appears

- Expected result:
  An option to show the inspector in the right or bottom part of the screen like Firefox, Chrome, Opera, Safari which works more conveniently.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes 

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
Duping to #3555
