### ISSUE TITLE
visiting wikpedia home pages results in "dead" tab on El Capitain

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#787]
visit https://www.wikipedia.org ... the resulting tab does not respond to input, neither in the wikipedia search form (it won't grab the focus), and you can type whatever you want into the URL bar, but the tab won't load/reload. the tab appears "dead" and must be closed.

oddly, `kernel_task` (PID 0) went sideways in terms of load. i believe this is related as it is reproducible.

**Comment by bridiver** [comment]
Appears to be an issue with the input "results" attribute. It's currently only supported in Safari and likely something we need to disable. This page also fails to load
http://www.wufoo.com/html5/types/5-search.html

**Comment by bridiver** [comment]
this css seems to fix the issue
`
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration {
  display: none;
}
`
