### ISSUE TITLE
When fullscreen (on macOS), move the nav controls left

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7872]
Screenshot of user fullscreen:
![image](https://cloud.githubusercontent.com/assets/4733304/24314977/a9849736-10a1-11e7-824e-a1d259d122fc.png)

Notice in the top left there is a blank area where the traffic lights used to be (red / yellow / green buttons).  This area should disappear

**Comment by freebrowser1** [comment]
And the title bar and tabs bar should disappear as well to become 'full screen' (and obviously reappear when mouse is moved to top).

**Comment by luixxiul** [comment]
> But the top-left stoplight buttons do appear in the titlebar.

Because the window is not in the fullscreen mode, which is different from the maxmized window.

**Comment by kumarrishav** [comment]
I would like to a shot to this one :)

**Comment by bsclifton** [comment]
@kumarrishav go for it 😄  Let me know if you have any questions
