### ISSUE TITLE
Inspect Extension Background Page

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#7880]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I would like to open an instance of the developer tools, and have it be connected the the background page of a particular extension.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Is this an issue in the currently released version?
Yes

- Screenshot if needed:
From chrome's about:extensions page:

![image](https://cloud.githubusercontent.com/assets/815158/24319584/08e16168-10ee-11e7-998d-06f33839461a.png)

**Comment by luixxiul** [comment]
QA is blocked on https://github.com/brave/browser-laptop/issues/7894. Cf: https://github.com/brave/browser-laptop/pull/7895#issue-217000286

**Comment by bridiver** [comment]
@luixxiul I don't understand what you are blocked on. This doesn't have any dependencies on #7894

**Comment by luixxiul** [comment]
"url will not properly reset" issue is not critial? if it does not have influence on UX, I'll change the label.

**Comment by bridiver** [comment]
I removed that because I found another way to make it work, but either way it isn't a blocker for this, just a note
