### ISSUE TITLE
Pref change restart doesn't launch the browser again

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7882]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pref change restart doesn't launch the browser again

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	ffa6f8f

- Steps to reproduce:
    1. Do a clean install/upgrade to 0.14.0 Preview 5
    2. Change pref options which require browser restart
    3. All process gets killed and browser doesn't restart, have to manually restart it
    
- Actual result:
Pref change restart doesn't launch the browser again

- Expected result:
Should restart the browser when user clicks yes to restart browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![pref](https://cloud.githubusercontent.com/assets/17010094/24320930/0eb83888-1138-11e7-949a-d463eeb6c31a.gif)

- Any related issues:
#5938

**Comment by bsclifton** [comment]
confirmed on Windows and macOS

**Comment by bsclifton** [comment]
Assigned to @bridiver as he is fixing some issues related to relauncher
