### ISSUE TITLE
Webview crash when visiting https://jsfiddle.net/bkf50r8v/13/

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7885]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Webview crash when visiting https://jsfiddle.net/bkf50r8v/13/

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	ffa6f8f

- Steps to reproduce:
    1. Do a clean install of 0.14.0 Preview 5
    2. Visit  https://jsfiddle.net/bkf50r8v/13/
    3. Web view crashes with frown face 
    
- Actual result:
Web view crashes with frown face 

- Expected result:
Web view should not crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![webrender crash](https://cloud.githubusercontent.com/assets/17010094/24321457/0abaf36c-1145-11e7-983e-cf430f682a8d.gif)

- Any related issues:
cc: @darkdh @bridiver

**Comment by bridiver** [comment]
is this a regression? If it's not I'm not sure that I would label it high impact.

**Comment by darkdh** [comment]
exactly save behavior as https://github.com/brave/browser-laptop/issues/6522 but different dll

**Comment by srirambv** [comment]
>is this a regression?

Yes it is. Worked fine in previous releases. Missed adding the label, update now. I have seen this sad face crash on some video streaming sites as well. Not consistently but one or two out of ten attempts.
