### ISSUE TITLE
Lion badge should show count for fingerprint block as well

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7886]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Lion badge should show count for fingerprint block as well

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.0
rev	ffa6f8f

- Steps to reproduce:
    1. Visit icloud.com with fingerprint enabled
    2. 1 fingerprint method is blocked but badge shows count as 0
    3.
    
- Actual result:
No count shown when only fingerprint method is blocked

- Expected result:
Should show count for blocked fingerprint method as well along with adblock and script block

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![fpcount](https://cloud.githubusercontent.com/assets/17010094/24321489/f1c3ddfa-1145-11e7-9cc4-06de42644b04.gif)

- Any related issues:
cc: @NejcZdovc

**Comment by NejcZdovc** [comment]
This is by design. @bradleyrichter should we include fingerprint as well?

**Comment by bradleyrichter** [comment]
Actually, if the display is 0, then the badge should be hidden. 

Same for shields down.

**Comment by NejcZdovc** [comment]
@bradleyrichter Not sure that I follow. I already created PR that hides badge if count is 0 https://github.com/brave/browser-laptop/pull/7877. What we are talking here is if we should display only "Ad or Tracker Blocked" (this is how we display it now) or we should add "Fingerprinting Method Blocked" to this count as well.

**Comment by Jacalz** [comment]
In my opinion it should display fingerprinting too but it's your choice👍

**Comment by bradleyrichter** [comment]
Sorry. The screen shot threw me off since it had a zero. 

Let's show a sum of all shield types. It will be helpful to know when at least 1 item is blocked.

**Comment by NejcZdovc** [comment]
@bradleyrichter so sum all 4 of them, even HTTPS upgrades?

**Comment by srirambv** [comment]
I feel it should be only for
1. Ad and Tracker Blocked
2. Scripts Blocked
3. Fingerprint Methods Blocked

**Comment by NejcZdovc** [comment]
@srirambv I agree

**Comment by bradleyrichter** [comment]
Oops. Sorry. Yea, ignore https upgrades in the sum.

**Comment by bsclifton** [comment]
marked as `release notes exclude` since this can be captured with the original issue for Lion badge (https://github.com/brave/browser-laptop/issues/7859)
