### ISSUE TITLE
First time wallet creation needs a better UI

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7889]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
First time wallet creation causes some of the UI elements to be not shown until the wallet is created. This looks very unpolished(see screenshot)

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.0
rev	ffa6f8f

- Steps to reproduce:
    1. Clear profile and create a new one
    2. Enable payments in the new profile
    3. UI looks bad 
    
- Actual result:
First time wallet creation UI looks bad

- Expected result:
Should be more polished

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No since UI is different form 0.13.5

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![wallet_creation](https://cloud.githubusercontent.com/assets/17010094/24321662/b2133a44-1149-11e7-846e-de66995cc5de.gif)

- Any related issues:
cc: @mrose17 @bradleyrichter @NejcZdovc

**Comment by bradleyrichter** [comment]
ok, the desired fix here is to show all elements when the screen redraws, but any elements that are not clickable should be disabled. (instead of hidden)
