### ISSUE TITLE
Spell check should have an option to be disabled

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7898]
**Describe the issue you encountered:** Spell check should have a global option to be disabled.

This is the issue because sometimes words corrrectly spelled are judged as misspelled: #4697

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 JP

- Brave Version (revision SHA): 0.13.5

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result: Spell check cannot be diabled

- Expected result: Spell check should be able to be disabled

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #4697 https://github.com/brave/browser-laptop/pull/11710 https://github.com/brave/browser-laptop/issues/2183

**Comment by freebrowser1** [comment]
I agree completely. The red waves under the text are very annoying.
Chrome, FF, Opera and Safari allow disabling it.

**Comment by Liunkae** [comment]
+1 from #8226

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/tabs-go-inactive-and-spellchecker-on-linux/3194

**Comment by hachre** [comment]
+1 from me. I write a lot in German and the constant red wiggles make it very hard to read multi-paragraph texts for mistakes.

**Comment by hugobuddel** [comment]
+1 having the red wiggles is so annoying that I consider dropping Brave after a single day
or maybe I should type all my non-English text somewhere else and copy paste it in Brave

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/spell-check-not-working/7407?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/how-to-disable-spelling/8409?u=eljuno

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/pull/11710

@darkdh Even no language is set, the spell check cannot be disabled. mind checking the issue? thanks!

STR:
1. Clear the browser profile
2. Start the browser
3. Open about:preferences#general
4. Remove `English`
5. Restart the browser
6. Open about:styles
7. Enter some random words on a text box

Expected result:
The words should not be underlined

Actual result:
The words are underlined, suggesting the correct spells in English

**Comment by luixxiul** [comment]
The option was added, so I'm going to close the issue. I'm opening another issue as a follow-up.
