### ISSUE TITLE
Support for Subgraph OS

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7899]
It was reported to me that Brave does not run on Subgraph OS because they do not support user namespaces in their kernel for security reasons. Chromium gets around this somehow, probably through use of the almost-deprecated setuid sandbox (https://bugs.chromium.org/p/chromium/issues/detail?id=312380).

**Comment by diracdeltas** [comment]
maybe this would Just Work if we took out https://github.com/brave/muon/blob/3571a34c91ca0d1e1c25837cd6e550b63a1eeb9a/atom/app/atom_main_delegate.cc#L307 ? cc @bridiver

**Comment by bridiver** [comment]
that  line was added by @posix4e to fix add sandbox support - https://github.com/brave/muon/pull/119
if you remove it, it would attempt to use the setuid sandbox and we don't support that

**Comment by xSmurf** [comment]
Without setuid mechanism Brave won't work in Arch either as userns is disabled following numerous privilege escalations. The Chromium ticket dates back to 2013 and hasn't seen activity since early 2016 - seems it'll stick around for the foreseeable future.

**Comment by bridiver** [comment]
@xSmurf see https://bugs.chromium.org/p/chromium/issues/detail?id=598454
the setuid sandbox is almost dead and we have no plans to support it. In the meantime we can support Subgraph and other distros by disabling the sandbox. Not a great solution from a security perspective, but we don't have the resources to focus on a small number of distros right now. We would be happy to accept a PR though!
