### ISSUE TITLE
Add support for additional search engines

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#790]
for "parity' with the mobile browsers, we should add: Bing, Yahoo, Amazon.com, Twitter, and Wikipedia.

#3053

**Comment by psimyn** [comment]
I was working on this for https://github.com/brave/browser-laptop/issues/466 (example near the bottom)

Still needs UI fixes and preferences page added though

**Comment by mrose17** [comment]
most excellent!

**Comment by thbtm** [comment]
Is it possible to add qwant.com too ?

**Comment by LoloIrie** [comment]
Qwant would be nice +1

**Comment by luixxiul** [comment]
ref: #824

**Comment by Superbest** [comment]
I would also suggest:

* A searx instance such as searx.me 
* startpage.com and/or ixquick

**Comment by luixxiul** [comment]
@bbondy is it worth considering or under consideration to implement OpenSearch?

**Comment by bbondy** [comment]
we do parse OpenSearch for Google and DuckDuck go. I think we can just do a simple big list like this in preferences though, I think there's a mockup in one of the preferences issues.

**Comment by bsclifton** [comment]
+1 from support for IxQuick/StartPage

**Comment by kskarthik** [comment]
Please also add searx.me meta search engine. cc: @asciimoo

**Comment by mrose17** [comment]
OBE

**Comment by DeviatedMind** [comment]
#790 #824 #3053 #3294 #4210

**Comment by jeroen7s** [comment]
please add search.gibberfish.org as searx.me alternative, it's hosted by a non polrofit organization, searx.me seems to be overloaded, not to mention gets it's results from.german versions of.search engines, gibberfish gets.them from american versions
