### ISSUE TITLE
Regression: isPotentialPhishingUrl is not defined

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7903]
## Test plan

https://github.com/brave/browser-laptop/pull/7904#issue-217073396

----

**Describe the issue you encountered:**
Regression: `isPotentialPhishingUrl` is not defined.

This is the cause: https://github.com/brave/browser-laptop/commit/17b7cbe4c4bba688cb066cb69f692416462544ad#diff-a680fa16146451835432a63cc9d196b8L9

- Any related issues: #7895 #7865 #4899

**Comment by NejcZdovc** [comment]
@luixxiul  This is a rebase issue, will you fix it?

**Comment by luixxiul** [comment]
@NejcZdovc done, will you review the PR?
