### ISSUE TITLE
Back/forward gesture should support three finger swipe

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#7905]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
As of 0.14.0, Brave supports a two finger swipe or none at all, depending on the user's system preferences. It should also support the three finger swipe if enabled in preferences.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
master (9ef7817)

- Steps to reproduce:
    1. Open `System Preferences > Trackpad/Mouse > More Gestures`.
    2. Change `Swipe between pages` to `Swipe with three fingers`.
    3. Open a new Brave tab and navigate to any site.
    4. Try to swipe backward with three fingers.
    
- Actual result:
Nothing happens.

- Expected result:
The browser should navigate back.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes, 0.13.5 has the same issue.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open `System Preferences > Trackpad/Mouse > More Gestures`.
    2. Change `Swipe between pages` to `Swipe with three fingers`.
    3. Open a new Brave tab and navigate to any site.
    4. Try to swipe backward with three fingers.
    5. Make sure the page navigates back.

- Screenshot if needed:
![](https://cloud.githubusercontent.com/assets/6919384/17840220/4ba22f9c-6800-11e6-8d1b-9fc4eac82773.png)

- Any related issues:
This is a follow-up to issue #3299.

**Comment by lucidNTR** [comment]
updated the PR. let me know if any more changes are needed.

**Comment by darkdh** [comment]
fixed by 7786
