### ISSUE TITLE
Shortcut F6 to focus address bar is missing

### ISSUE THREAD

**Issue by technout** [brave/browser-laptop#7906]
Brave browser version: 0.13.5 (rev 1db81cb)
OS version: Linux Ubuntu 16.04 x64

What steps will reproduce the problem?
1. Open Brave browser
2. Press F6 or Alt + d or Ctrl + i
3. Look at the address bar

What is the expected result?
  That all of the text in the address bar is selected.

What happens instead?
  Nothing happens. No focus, no address bar text selected.

Additional Info:
  This is really annoying since I usually use the address bar to perform searches (press F6, begin typing search words and press enter)

**Comment by bsclifton** [comment]
@technout we recently fixed this issue (it was originally tracked with https://github.com/brave/browser-laptop/issues/7491).  We should have a release out soon (within the next week) which fixes the issue 😄  

Thanks for reporting and apologies that we unintentionally broke this functionality

**Comment by technout** [comment]
Thanks! It is now working in:
Brave browser version: 0.14.1 (rev 3de60d5)
OS version: Linux Ubuntu 16.04 x64
