### ISSUE TITLE
Flash is not working in 0.14.0 Preview 6

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7910]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
With a clean profile (moved ~/Library/Application Support/brave) it was discovered that Flash is not working, even for rather commonly tested sites like homestarrunner.com.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.0 Preview 6 (b4289c0)

- Steps to reproduce:
    1. Move your ~/Library/Application Support/brave folder
    2. Install 0.14.0 Preview 6
    3. Visit homestarrunner.com
    4. Attempt to enable Flash and watch the animation.
    
- Actual result:
Flash will not work. A message is displayed on the cover slide. "Plugin not supported."

- Expected result:
Flash should work if the user allows it.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="1919" alt="screen shot 2017-03-26 at 11 45 48 pm" src="https://cloud.githubusercontent.com/assets/1434040/24341658/d5d2022a-1280-11e7-8080-739e0ff10af1.png">
<img width="1920" alt="screen shot 2017-03-26 at 11 45 29 pm" src="https://cloud.githubusercontent.com/assets/1434040/24341659/d5d2a0f4-1280-11e7-93ef-381ac27ae8c7.png">

- Any related issues:
https://github.com/brave/browser-laptop/pull/7563#issue-212819400

**Comment by bsclifton** [comment]
Fixed w/ preview 7 👍
