### ISSUE TITLE
Ctrl-Shift T with history

### ISSUE THREAD

**Issue by CliqueBait** [brave/browser-laptop#7913]
Currently, the keyboard shortcut Ctrl-Shift T recovers the last closed tab. It does not recover the browsing history of that tab. I would like to be able to hit Ctrl-Shift T and then use "Go back" to find earlier stages of the browsing I did on that tab.

Brave: 0.13.5 
rev: 1db81cb18b6919535792bb7e198ab87276bd67ea 
Muon: 2.56.8 
libchromiumcontent: 56.0.2924.87 
V8: 5.6.326.50 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.0-42-generic 
os.arch: x64

**Comment by srirambv** [comment]
Closing in favour of #2702.
