### ISSUE TITLE
bitwarden: App login screen only shown on newtab/aboutpages ?

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7914]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
bitwarden: App login screen only shown on newtab/aboutpages ?

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	61b6b6b

- Steps to reproduce:
    1. Enable bitwarden from settings under security 
    2. Open github.com in a new tab, click on the bitwarden icon, widget login not shown
    3. Open any about page/newtab, click on the bitwarden icon, widget login is shown
    
- Actual result:
App login screen is not shown on webpage

- Expected result:
Widget login screen should not be dependent on any page

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![bitwardenwidget](https://cloud.githubusercontent.com/assets/17010094/24352383/4adc89ea-12e1-11e7-9a2c-c32941ca36a5.gif)

- Any related issues:
cc: @kspearrin

**Comment by kspearrin** [comment]
Seems like something brave specific here.

**Comment by jonathansampson** [comment]
Fixed by https://github.com/brave/muon/commit/f2ca2f256d777dbb7b9cdd2f9b0aaa158cb1678c
