### ISSUE TITLE
NewTab should be replaced by any new URL bar search query when in same newtab

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#7918]
- Did you search for similar issues before submitting this one?

yes

- Describe the issue you encountered:

when you have a fresh newtab, and then perform a search query, the query opens in another new tab instead of replacing the current new tab

- Platform (Win7, 8, 10? macOS? Linux distro?):

mac OS

- Brave Version (revision SHA):

Brave	0.14.0
rev	61b6b6b

- Steps to reproduce:
    1. make a new tab with + button
    2. enter a search in the URL bar
    3. hit enter/return
    
- Actual result:

the newtab page is retained and the search result opens in yet another new tab

- Expected result:

result should replace current new tab you were viewing already

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

no

- Is this an issue in the currently released version?

yes

- Can this issue be consistently reproduced?

yes

**Comment by bsclifton** [comment]
I've tried and I can't reproduce this issue (I've tried both the current release and master)

I'm going to close for now, but @bradleyrichter please re-open if you still see this happen (with more details- what is your new tab page set to, etc). Thanks 😄
