### ISSUE TITLE
Unhide bitwarden password manager

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7921]
## Test plan

https://github.com/brave/browser-laptop/pull/8829#issue-227873469
https://github.com/brave/browser-laptop/pull/6918#issue-203925870

----

Once https://github.com/brave/browser-laptop/issues/7830 is supported, we can revert https://github.com/brave/browser-laptop/commit/0744193d30c4b765f9709c66e0bb3e9d73a6a246

#7919 #4776

**Comment by kspearrin** [comment]
Can we unhide now that #7830 is closed?

**Comment by bsclifton** [comment]
@kspearrin absolutely- we'll need a new version of Muon.  I'll set a milestone for the release after the current one. If you'd like, you could submit a revert of the above as a PR 😄

**Comment by kspearrin** [comment]
@bsclifton Done. https://github.com/brave/browser-laptop/pull/8776

**Comment by kspearrin** [comment]
I somehow screwed up #8776 into a state that I didn't know how to recover from, so I started over with #8829. Sorry :-/

**Comment by kspearrin** [comment]
@bsclifton Just trying to get an idea here. We'd like to prepare some announcement material to inform our users. What version of brave is slated to have bitwarden available in it?

**Comment by bsclifton** [comment]
@kspearrin comment left here:
https://github.com/brave/browser-laptop/pull/6918#issuecomment-308276441

Basically, it's in our 0.17.x releases. Here's a link to the latest, if you wanted to test it out 😄 
https://github.com/brave/browser-laptop/releases/tag/v0.17.1dev

We should be able to ship within 1-2 weeks 😄

**Comment by kspearrin** [comment]
@bsclifton How do extension updates work in brave? I'm testing with 0.17.1 and am getting a very outdated version of bitwarden (1.10.0) that is full of issues because it's using server APIs that are not backwards compat anymore.

**Comment by bsclifton** [comment]
@kspearrin right now, it's a manual process we have to run (I'm looking at automating the update process).  I should be able to safely bump bitwarden without an issue.  Hang tight...

**Comment by kspearrin** [comment]
@bsclifton Ok, no worries.  We do have a somewhat critical update coming out today or tomorrow that I would like to ensure brave gets updated to before the release.

**Comment by kspearrin** [comment]
@bsclifton Issue created #9479

**Comment by luixxiul** [comment]
The bitwarden icon is not displayed on a web page, while it is on an about page such as about:preferences.

![a](https://user-images.githubusercontent.com/3362943/27315921-8805a8c4-55b7-11e7-9413-7063dcd7fbee.gif)

**Comment by bsclifton** [comment]
Moving to 0.18.x hotfix because we ran into an issue https://github.com/brave/browser-laptop/issues/10130

**Comment by luixxiul** [comment]
This should be fixed after https://github.com/brave/browser-laptop/commit/38f46189571710189a3702926d8d40b465fc953a

**Comment by kspearrin** [comment]
Was this unhidden for the 0.18.x hotfix? I can't find a branch for that.

**Comment by jonathansampson** [comment]
@kspearrin I'm about to take a closer look at this issue. Aiming to resolve asap, and ship.

**Comment by kspearrin** [comment]
@jonathansampson ok. Please let me know if/when there is a branch I can look at/test.  

Also, we just pushed a new version, 1.14.2 , to the chrome store today. It would be nice if that update made it in as well since I know auto updates is a missing feature at the moment.

**Comment by bsclifton** [comment]
@kspearrin good call- we do need to unhide it. This issue was closed prematurely when a different commit / issue was resolved.  I'll re-open and unhide it shortly

**Comment by bsclifton** [comment]
Issue is now resolved after committing https://github.com/brave/browser-laptop/commit/2c2e19afb5b2ae33a2567d85704aa9dfb86fca2d 😄 

cc: @kspearrin, @jonathansampson, @luixxiul

**Comment by bsclifton** [comment]
@kspearrin you can try it out using the `0.18.x` branch OR if you wait until we have a new build on the `dev` channel (if you have preview releases enabled- see advanced tab of preferences). We may have a new packaged build tonite or tomorrow

**Comment by kspearrin** [comment]
@bsclifton I will wait for the new dev build.

**Comment by bsclifton** [comment]
Tentatively moving to 0.19.x - we've got it disabled for now because of issues we ran into. We'll continue working away at those and plan to release with 0.19.x

**Comment by bsclifton** [comment]
Let's track this with https://github.com/brave/browser-laptop/issues/4776 instead
