### ISSUE TITLE
Private session on about:newtab shows blank page

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7922]
STR:
* Clear session
* Open a new tab on private mode by either menu or long-press newtab menu
* Result: page is blank

Reproducible on master (0744193) as well on 0.14.0 Preview 7. Running Muon v2.57.5

Plus notes:
* After refresh (<kbd>cmd</kbd>+<kbd>r</kbd>) page is redirected to about:error (also blank)
* Browser-level console throws: `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`.
* I wasn't able to reproduce running Muon v2.56.9.

Related (root cause for): #7912 

/cc @bsclifton @darkdh @bridiver

**Comment by bsclifton** [comment]
Private tabs aren't able to load about pages because of content security policy issues

Duping this to https://github.com/brave/browser-laptop/issues/1817
