### ISSUE TITLE
Throttling between window resize cause tabContent to pop

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7925]
Per @bradleyrichter screenshot:

![poppicons_redraw_lag](https://cloud.githubusercontent.com/assets/4672033/24384789/c2ae9ba6-133c-11e7-83b2-b58cf17116db.gif)

My guess is that at some point tab size is undefined making icons to pop to the minimum possible (_smallest_ breakpoint), making UI look weird. Should also be related to how we throttle window resize.

Alternatively we can also store last breakpoint state until it finds the next one.

**Comment by bsclifton** [comment]
@cezaraugusto it looks like they're about to explode! 😛
