### ISSUE TITLE
Update muon to 2.57.6

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7939]
## Test plan
1. Launch Brave and visit about:brave
2. Confirm that `2.57.6` shows for `Muon` under version information

## Original issue description
We need to update to Muon version 2.57.6 (which includes Chromium 57)

**Comment by bsclifton** [comment]
Completed with https://github.com/brave/browser-laptop/commit/25b91dfbb83d31a1f11939eb4a41a0cb00557a1a

**Comment by srirambv** [comment]
Muon is	2.57.7

**Comment by bsclifton** [comment]
@srirambv that is correct- thanks 😄  I updated title + original post
