### ISSUE TITLE
properly reset ruleset

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#7940]
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered: if a publisher site is added to the exclusion list (by accident) and then removed, it doesn't properly propagate to the browser

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version (revision SHA): all

- Steps to reproduce:
    1. accidentally add a news site to the exclusion list
    2. wait for a browser to get the incremental update
    3. remove the news site
    
- Actual result: the publisher site is not removed from the browser's copy of the exclusion list

- Expected result: the publisher site should be removed from the browser's copy of the exclusion list

- Will the steps above reproduce in a fresh profile? If not what other info can be added? yes

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none

- Screenshot if needed: none

- Any related issues: none

**Comment by bsclifton** [comment]
@mrose17 can you add test steps for this?

**Comment by bsclifton** [comment]
Also, I'm curious if you can update the title to be more "release notes" friendly (maybe something like Fix issues with exclusion list for Brave payments")
