### ISSUE TITLE
Update UI spec for private tabs

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#7943]
Per @bradleyrichter request:

1. Private tabs should have its color (purple) only when active, no hoverState
2. Private tabs color should override themeColor
2. Replace 👁 icon with 🕶  

<img width="595" alt="screen shot 2017-03-28 at 11 43 32 pm" src="https://cloud.githubusercontent.com/assets/4672033/24438442/dbae7fea-141d-11e7-88f8-7b7effd67670.png">

**Comment by bbondy** [comment]
No new UI changes pls once we're in RC for that milestone.  Unless it's a regression or big problem.  I think it's neither of those so I updated to 0.14.1
