### ISSUE TITLE
Enable Vimium support

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7946]
Since it is currently disabled for now: #7527

**Comment by bsclifton** [comment]
@luixxiul thanks for capturing this 😄 

Enabling should be as easy as reverting https://github.com/brave/browser-laptop/commit/39e7bc6d4c7dd1db556cc35670b83c0cfed2cdeb

**Comment by davegson** [comment]
are there any updates on this issue? Eagerly awaiting this to make the switch :)

**Comment by luixxiul** [comment]
CC @jonathansampson

**Comment by jonathansampson** [comment]
@davegson We are adding implementations for a couple tab-related methods, and will soon be able to support. Thanks for hanging in there 🙂

**Comment by tjim** [comment]
How's this coming?

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/9531
