### ISSUE TITLE
Disable the hover over tabs effect

### ISSUE THREAD

**Issue by Attrash-Islam** [brave/browser-laptop#7947]
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

I've moved to brave browser to support this great open source project (Even invited my wife to join!), and whenever the mouse is on some tab accidentally the tab will be hovered with opacity. This is annoying and is against the User Experience (My wife studied Graphic Design and Visual communication, she this is not regards our personal experience).

- Platform (Win7, 8, 10? macOS? Linux distro?):

Win8 + Linux Mint

- Brave Version (revision SHA):

Latest Version
 
- Steps to reproduce:
    1. open two tabs
    2. hover on tab accidentally (Happens often)
    
- Actual result:

The tab is hovering automatically 

- Expected result:

The tab shouldn't be hovering at all

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes. Always

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Absolutely 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Attrash-Islam** [comment]
I can prepare a Pull-Request if needed (But don't know if it preferred to remove all the feature or to provide configuration to enable/disable)

**Comment by NejcZdovc** [comment]
@Attrash-Islam You can disable this in `about:preferences` -> Tabs -> Show tab previews on hover

![image](https://cloud.githubusercontent.com/assets/9574457/24443416/d4608284-1462-11e7-97dd-ef5907a08fd0.png)

**Comment by srirambv** [comment]
You can disable it from settings. 
![image](https://cloud.githubusercontent.com/assets/17010094/24443433/85e4f57a-145a-11e7-8a50-8c7da33490c9.png)

**Comment by Attrash-Islam** [comment]
Ah-ha! Thanks! I'll the issue hoping you redefine the defaults to false :wink:

**Comment by bsclifton** [comment]
@Attrash-Islam we already closed an issue suggesting this off by default, but please feel free to comment in https://github.com/brave/browser-laptop/issues/7596

**Comment by mralexho** [comment]
I really like the preview-on-hover feature but I thought the hover delay is too short. Is there any way we can set delays?

Thanks for amazing work!

**Comment by luixxiul** [comment]
> Is there any way we can set delays?

Doable, though I think it would only be implemented as an option. See: https://github.com/brave/browser-laptop/pull/848#issuecomment-187960938

CC @bbondy for confirmation.
