### ISSUE TITLE
Wallet creation fail on RC build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7948]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Wallet creation fail on RC build

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	e6fba42

- Steps to reproduce:
    1. Do  a clean install of 0.14.0 RC1
    2. Enable payments, nothing happens, wallet is not created
    3. Click on the create wallet button, nothing happens, console doesn't record logs
    
- Actual result:
Wallet creation fails

- Expected result:
Should create wallet after enabling payments

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ledger](https://cloud.githubusercontent.com/assets/17010094/24444249/a5241562-145d-11e7-9ad2-c1537d38380c.gif)

- Any related issues:
cc: @mrose17

**Comment by NejcZdovc** [comment]
It's working on the latest master fd6763e

**Comment by luixxiul** [comment]
I experience the issue on the latest RC, on Windows 10.

**Comment by bbondy** [comment]
Seems to also be because of the packaging excluding node_modules subdirs of node_modules. 
We'll have to come back to this one at a later date, I'll file it as an issue but reverted it here.
https://github.com/brave/browser-laptop/commit/c2c0149040fe7bc5e7c66268003000191e7d6fa6

**Comment by luixxiul** [comment]
the files which c220149 reverted had been reverted multiple times. The first commit was to fix #7896.
