### ISSUE TITLE
Close tab button color on private tab should be something different

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7952]
**Describe the issue you encountered:**
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24444696/43e0b3a6-14a2-11e7-86d4-c7da40b33ff6.jpg)

How about making it ``#fff`` or dark purple?

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.0 RC1

- Steps to reproduce:
    1. Open a private tab
    2. Hover on the tab

- Actual result: see above

- Expected result: CC @bradleyrichter 

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #7851 #5431

**Comment by NejcZdovc** [comment]
@luixxiul will #7943 solve this problem?

**Comment by luixxiul** [comment]
It is not suggested there, and it is just my idea. I would like to hear @bradleyrichter 's insight at first.

**Comment by srirambv** [comment]
I think making it white would be good. Would be a good contrast on the dark tab color

**Comment by NejcZdovc** [comment]
@luixxiul why I asked about relevance to the issue #7943 is because this issue will remove purple background

**Comment by luixxiul** [comment]
I thought there was not suggested to remove the background color. Isn't It just the matter of when to have its color?

> Private tabs should have its color (purple) only ...

**Comment by NejcZdovc** [comment]
Yeah, but when it's not active, private tab has no background

**Comment by bradleyrichter** [comment]
@luixxiul @NejcZdovc The reason is that the non-active purple tab is very confusing when determining which tab is actually selected.

The icon should be enough to remind you that it is private when not selected. Purple adds to recognition when it is selected.

**Comment by luixxiul** [comment]
Closing as stale (and invalid)
