### ISSUE TITLE
Dark UI ASAP - Accessibility Issue -> My Eyesight Problems

### ISSUE THREAD

**Issue by AnthoniG** [brave/browser-laptop#7953]
Hello,

An issue was opened to add Dark UI theme located here https://github.com/brave/browser-laptop/issues/271

In that bradleyrichter said at May 23, 2016 that it would be coming soon.
So it's been nearly a year now and it's still not in.

I have a serious eyesight problem and can not use Brave for long period (like 10 minutes max) because it's too bright and it really, really hurts my eyes. All the browsers I have (Firefox, Chrome, etc) have dark themes that you can add (which I naturally have done). Yet Brave has nothing like that.

Can you PLEASE add some facility to make the theme dark (even it's a temporary work around) so that I can use Brave as my main browser for development on C9.io.

Please, please,, please,, please,, please,, please, lol :D

Regards
Anthoni

**Comment by luixxiul** [comment]
If you need the solution really right now, here is a temporary and very dirty solution in 1 minute.

1. Create a back up of your profile
1. Download the latest RC1 release from https://github.com/brave/browser-laptop/releases
2. Open Devtool by Shift+F8
3. Click the plus button on the right side
4. Hit `*`
5. Hit <kbd>tab</kbd>
6. Input `background: #333`

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24447117/e1566b78-14aa-11e7-847d-7b389a7e375c.jpg)

If you know CSS, you could adjust it as you like.

**Comment by luixxiul** [comment]
+1 for @freebrowser1. I have used the software and it is nice :-)

**Comment by AnthoniG** [comment]
@freebrowser1 What is f.lux and where do I get it please ?
@luixxiul Sorry for a newbie style question, but I have downloaded the release as per suggestion but do I need to uninstall my current Brave and the install new one, or can I install over the top of it ?

Reason I ask is because some programs behave differently depending on what you are doing.

Cheers for the help thus far.

**Comment by luixxiul** [comment]
Instead of installing the new build, I will recommend f.lux. Here you can get a copy: https://justgetflux.com/

I think the software would help you not only on Brave but also on other programs which you feel unconfortable.

**Comment by AnthoniG** [comment]
@freebrowser1 f.lux FTW!!!
Thank you SOOOO much.
You have no idea how much help that has given me.
EVERY single window is now dimmed and I love it :D

@luixxiul Yep just installed and set it to 2700K (Incandescant brightness). So much more comfortable, in fact I am now typing this on the other version of Brave. Not the one you suggested to download. Now just have to get around the annoying Lastpass not remembering my master password every time I restart the browser.

**Comment by AnthoniG** [comment]
Cheers for the help both of you and I will close this as resolved now.
Will open another ticket about Lastpass etc :)
