### ISSUE TITLE
Fix tab title display when opening about pages from about:about pages

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7957]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Fix tab title display when opening about pages from about:about pages

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.0
rev	e6fba42

- Steps to reproduce:
    1. Do a clean install of 0.14.0 RC1
    2. Open about:about page in a new tab
    3. Click on the about pages, each about page opened either has `Untitled` or `about:<pagename` until mouse over the tab
    4. Open about:hisotry in a new tab, open about:styles in the same tab, title is not changed until mouse over/away from the tab
    
- Actual result:
Tab title not shown until mouse over

- Expected result:
Should show the tab title immediatly after opening

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#7724 
cc: @cezaraugusto

**Comment by bbondy** [comment]
Definitely a bug but doesn't need to be in 0.14.0 so removing. Thanks.

**Comment by cezaraugusto** [comment]
closing in favor of #7765
