### ISSUE TITLE
Delete confirmation message ("Delete?") should be able to be localizable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7958]
**Describe the issue you encountered:** Delete confirmation message ("Delete?") should be able to be localizable.

https://github.com/brave/browser-laptop/commit/c5026e58fff408a5bdf831d6c32fad39531260ef#diff-f544daf754a6ad72801af50dbb179b6eR94

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA): 0.14.0 RC1

- Steps to reproduce:
    1. Download a file
    2. Click the bin icon on the download item
    
- Extra QA steps:
    1. Localize the string on Transifex
    2. Update localization files 
    3. Change the language setting
    4. Download a file
    5. Click the bin icon
    6. Make sure the message is successfully displayed in the same language

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
PR: #7988

**Comment by luixxiul** [comment]
Tested on Japanese.
