### ISSUE TITLE
modal dialog in child tab blocks the parent tab

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7961]
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): e6fba42

- Steps to reproduce:
    1. go to https://ithildin.com/tests/same-site-modals/
    2. click 'open popup'
    3. in the popup tab, click 'run modal'. do not dismiss the alert.
    4. go back to the opener tab
    
- Actual result:
none of the links in the opener tab are clickable while the alert is open.

- Expected result:
the modal in the child tab should not block the opener tab.

cc @bsclifton

**Comment by bridiver** [comment]
I think this actually might be the correct behavior. If the child tab is scriptable it would have to block the parent or the parent would be able to run JS code on the child while it should be blocked
