### ISSUE TITLE
ADDFUNDS_URL env var is not correctly displaying Add Funds button in dashboard

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#7962]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The ADDFUNDS_URL is not being used correctly to display the Add Funds button

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
All

- Steps to reproduce:
    1. Launch browser with ADDFUNDS_URL=http://somelocation.net npm start
    2. Open preferences / payments / Add Funds ...
    
- Actual result:
No button will be shown

- Expected result:
Button should be shown

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
moving to 0.14.3

**Comment by aekeus** [comment]
This was pulled into a previous release.
