### ISSUE TITLE
Spell check not working with Swedish as system language

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#7967]
Spell checking is not working for me on any version of Brave on Windows 10 Pro x64 and it doesent matter if I remove my whole session under %appdata% it just doesent work, but it works on MacOS Sierra. This is annoying because checking if spell checking is working is part of my Manual tests. :disappointed:  

## Original Description
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Spell check is not working in 0.14.0 RC2
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro  x64
- Brave Version (revision SHA):
0.14.0 RC2
- Steps to reproduce:
 Open a github issue and type some misspellings, make sure they are underlined. (Copyed from manual tests template)
- Actual result:
No indication of miss spelling
- Expected result:
Spell check sould uderline that you have spelled that word wrong
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
YES
- Is this an issue in the currently released version?
Not really
- Can this issue be consistently reproduced?
Yes, I tested in gmail also to see if it was a site specific thing but it isnt :-1:

**Comment by luixxiul** [comment]
Are you testing by setting the language to English?

**Comment by Jacalz** [comment]
I have Brave set to English and I was writing in English...

**Comment by alexwykoff** [comment]
I could not reproduce that on OS X with 0.14.0 RC2 
@srirambv could you give it a try?

**Comment by srirambv** [comment]
Works for me
![7967](https://cloud.githubusercontent.com/assets/17010094/24490610/30be3694-151b-11e7-90a2-14726d730f4c.gif)

**Comment by Jacalz** [comment]
I will see if it is possible with a fresh profile later today 👍

**Comment by Jacalz** [comment]
Still doesent work for me even on a new profile 👎

**Comment by luixxiul** [comment]
It does work on github, while it does not on the search form on mail.google.com. I am not sure this has been worked so far.

**Comment by bsclifton** [comment]
@Jacalz can you try on a different site? maybe just any site which has a textbox, type into it (like @luixxiul suggests, maybe GitHub... for example, this page)

**Comment by Jacalz** [comment]
I did test in github the first time, and then I tested on gmail... @bsclifton

**Comment by Jacalz** [comment]
Could I clean cookies and history and then send the session to you for closer inspection? :see_no_evil:

**Comment by Jacalz** [comment]
Still not working on 0.14.1, works on my Mac...

**Comment by Jacalz** [comment]
![image](https://cloud.githubusercontent.com/assets/25466657/24850353/f8985f3e-1dcf-11e7-9e72-63825f0541fc.png)
Can there be a problem when having windows set to Swedish because this comfirmation dialog says "Github Säger" and that is the equivilant of "Github Says". It says it regordles of what language brave is set to so I might be on to something :+1:

**Comment by Jacalz** [comment]
Wtf, Found the solution :+1: 
I changed windows to English and then Back to Swedish and now it works :confused:
Closing this since the issue is resolved but you can keep writing here if you have some useful info to say :smile:

**Comment by Jacalz** [comment]
The issue is back again after these 3 days, seems like brave has a problem with Windows set to Swedish :confused:

**Comment by Jacalz** [comment]
Fixed by #9951

**Comment by Jacalz** [comment]
Assigned to 0.18.x milestone because it got fixed in 0.18.x :+1:  Really happy :slightly_smiling_face:
