### ISSUE TITLE
Duplication when trying to close the source of the first pinned page

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#797]
I replicated the bug multiple times in this video:
https://youtu.be/MtFZPJOwkIs

Procedure:
- pin a page 
- right click on page
- choose "View Page Source"
- look at the fireworks when trying to close window

**Comment by psimyn** [comment]
This is an excellent bug - have a fix that opens view-source in new tab (currently it tries to open in same so fails on pinned)

**Comment by weems** [comment]
@psimyn  though ideally wouldn't we want in dev view on the same page? perhaps that is a new enhancement issue.

**Comment by psimyn** [comment]
yeah, that is up for debate. All other browsers (that I know of) open in a new tab

**Comment by weems** [comment]
@psimyn chrome opens view source in a new tab.  apologies, I confused this with right click + inspect element.
