### ISSUE TITLE
Sync does not appear to recover from network outage

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7972]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If the network is disconnected and Brave is left open, sync will not reconnect and update appropriately.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.0 RC2 (b00c5d9)

- Steps to reproduce:
    1. Use a clean profile on two machines
    2. Create a new sync group on machine1
    3. Join the sync group on machine2
    4. Turn off the network for machine2
    5. Add a bookmark and a bookmark folder on machine1
    6. Turn on the network for machine2
    7. Wait a reasonable amount of time (5 minutes I believe was the schedule, but I did 20 for good measure)
    
- Actual result:
The bookmark, bookmark folder, and history are not synced, even if history sync is turned on later

- Expected result:
Sync should retry periodically and when the network is available, resume sync functionality.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not sure

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
how long did you wait between steps 3 and 4?
