### ISSUE TITLE
JS iloop policing needs to be enhanced

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7973]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When visiting https://www.extremetech.com/internet/220696-forbes-forces-readers-to-turn-off-ad-blockers-promptly-serves-malware the CPU spikes and holds for a considerably long period of time.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.0 RC2 (https://github.com/brave/browser-laptop/commit/b00c5d969fd07fc5cf9fccc2563c3de0f7465f3c)

- Steps to reproduce:
    1. Visit https://github.com/brave/browser-laptop/commit/b00c5d969fd07fc5cf9fccc2563c3de0f7465f3c
    2. Check CPU usage
    
- Actual result:
The page should load quickly and CPU usage should be nominal (certainly not 100% for more than a couple seconds)

- Expected result:
The CPU usage stays above 100% (for multicore systems) for a considerably long time

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
0.13.5 appears to behave better

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
Can't reproduce on latest, but if we see it again, we can pull it into a near milestone
