### ISSUE TITLE
Extremereach.com - ads displaying on macOS w/Shields Up

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#7976]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Ads are being observed on Extremereach.com on macOS, have been unable to repro on Windows10, but we should have some additional testers run some Windows10 checks to confirm. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.14.0 RC
b00c5d9

- Steps to reproduce:
    1. Go to https://www.extremetech.com/internet/220696-forbes-forces-readers-to-turn-off-ad-blockers-promptly-serves-malware
    2. See ads
    3.
    
- Actual result:
Ads: screenshot from @alexwykoff 
<img width="1039" alt="screen shot 2017-03-29 at 5 31 30 pm-macos" src="https://cloud.githubusercontent.com/assets/8979240/24480584/17267b1e-149a-11e7-8562-21fdd82544bb.png">

Unable to repro in Windows10 in Chrome w/ABP or Brave 

Brave - win10
![brave-abp-noads-03292017](https://cloud.githubusercontent.com/assets/8979240/24480597/2cd7e196-149a-11e7-80d1-6949c73dee4e.PNG)

Chrome - win10 
![chrome-abp-noads-03292017](https://cloud.githubusercontent.com/assets/8979240/24480604/336699ee-149a-11e7-931d-6cd6eb6aefad.PNG)

- Expected result:
No Ads. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Should. 

- Is this an issue in the currently released version?
Soon-to-be (RC2 v0.14.0) 

- Can this issue be consistently reproduced?
On macOS, yes ( both @alexwykoff & @bridiver confirmed viewing ads bypassing blocking) 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
see above
- Any related issues:

Note, InstartLogic is in use for anti-adblocking, but is using a different variation in the source code implementation than boston.com was using in #7363

Need additional windows10 tests to confirm this is only occurring on macOS. Appears so, but needs more testing.

**Comment by Jacalz** [comment]
Can not see any ads on the page at all
