### ISSUE TITLE
Implement a status bar which can hold shortcuts to settings 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7986]
- Describe the issue you encountered:
Currently there is no status bar implemented. This should be implemented so that some features shortcuts can be made as part of it so that user need not open preferences page or use keyboard shortcuts and has easy access.

   Options on status bar can be
   Enable/disable Sync,
   Enable/disable Plugins,
   Open History/Downloads,
   Zoom slider with reset,
   Change Password Managers, 
   Change Number of tabs and more

  Status bar should have an option to enable/disable from settings

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

cc: @bradleyrichter

**Comment by bsclifton** [comment]
Feature request for a status bar at the bottom of the window (kind of like the downloads bar) which would have icons/buttons for the options you called out (enable/disable).  Vilvaldi has a similar status bar for comparison
