### ISSUE TITLE
toggle excluding a site from ledger sometimes removes it from the list

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#7987]
mac os 0.14 and latest master

steps to repro (starting from a clean profile):
1. enable payments
2. visit nytimes.com for at least 8 seconds or until it appears in the synopsis table
3. set minimum visits to 5 instead of 1
4. exclude nytimes.com by toggling the switch

result:
nytimes.com suddenly disappears from the list when the switch is toggled

expected result:
when minimum visits is set to N, all sites with less than N visits should disappear immediately. the current behavior is very confusing because toggling the exclude switch should not remove the site from the list.

a similar issue exists for increasing the minimum time. if i increase it from 8 seconds to 1 minute, a site with 9 seconds remains in the ledger table. however if i then toggle the include switch on that site, it doesn’t disappear from the list, so the problem isn't as bad.

**Comment by diracdeltas** [comment]
cannot repro on master

**Comment by diracdeltas** [comment]
ok, i can repro this on master if i copy all my ledger and session store files from brave to brave-development and then restart

**Comment by diracdeltas** [comment]
from slack:
> just noticed a more general problem, which is that the ledger table is adding sites that have less than the required number of views. i set the minimum to 5 visits, went to https://www.kefairport.is/, and it showed up on the list after only 1 view

**Comment by bsclifton** [comment]
Assigning @NejcZdovc as he has looked into this issue the most
