### ISSUE TITLE
Typing an address then going back before typing same address

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#799]
Bug replication procedure : 
- Type address or website name (www.youtube.com)
- Go to website
- Use the back button
- Type same address

Will not go to the address in question

**Comment by weems** [comment]
Secondarily Tested and verified @VirgilRoussos Steps to Recreate.

**Comment by twisterghost** [comment]
I think I've found the issue. When entering a new location, `windowStore` checks to see if it is different from the last location entered before navigating. Going back doesn't update the location properly. I'll see if I can get a fix for it.

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by bsclifton** [comment]
Unable to repro- this seems to have been fixed.  Closing :smile:
