### ISSUE TITLE
Generate release notes for 0.15.0

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7999]
Generated 03/30:
 - Update ledger list control to support new features for 1.0. ([#7347](https://github.com/brave/browser-laptop/issues/7347))
 - Asana drag and drop not working. ([#7103](https://github.com/brave/browser-laptop/issues/7103))
 - Include current year in PDF statement copyright footer. ([#6878](https://github.com/brave/browser-laptop/issues/6878))
 - Auto-purging "Saved site settings" resets Payments "Include" toggles. ([#6708](https://github.com/brave/browser-laptop/issues/6708))
 - Some info buttons in preferences are missing content links. ([#5758](https://github.com/brave/browser-laptop/issues/5758))
 - Ledger recovery should be aware of network status and give appropriate errors when the connection is down.. ([#4720](https://github.com/brave/browser-laptop/issues/4720))
 - Favicons on brave payments list are not displayed until switching the tab. ([#4178](https://github.com/brave/browser-laptop/issues/4178))

**Comment by luixxiul** [comment]
@alexwykoff would you please config your script to include the issues which were closed? There are several issues which has been labelled with `release-notes/include` while they are not fixed yet or reopened as the fix was reverted or ineffective, eg. #6878.

**Comment by alexwykoff** [comment]
@luixxiul with our typical scenario, we move fast enough that issues close by the time anyone is available to test. 0.15.0 is a bit exceptional (I hope!) in that we had a significant number of  issues revert or reopen.  If you like, you can always clone the changelog generator and change state=all to state=closed (line 24) https://github.com/alexwykoff/changelog-generator/blob/master/autogen.py

**Comment by alexwykoff** [comment]
Updated 04/24/2017:

Release Notes:
 - Bookmarks are re-synced (uploaded) on every load. ([#8408](https://github.com/brave/browser-laptop/issues/8408))
 - Opening pdf in new tab fails to load. ([#8364](https://github.com/brave/browser-laptop/issues/8364))
 - Upgrade to Chromium58. ([#8353](https://github.com/brave/browser-laptop/issues/8353))
 - All Predefined Messages Should Be Replaced. ([#8318](https://github.com/brave/browser-laptop/issues/8318))
 - Sort extensions alphabetically. ([#8315](https://github.com/brave/browser-laptop/issues/8315))
 - Tab drag and drop can be jumpy. ([#8288](https://github.com/brave/browser-laptop/issues/8288))
 - Homepage preference isn't being respected. ([#8278](https://github.com/brave/browser-laptop/issues/8278))
 - Screen Reader Can't Identify Extension Button. ([#8269](https://github.com/brave/browser-laptop/issues/8269))
 - Increase the tabs bar by another 2 px based on increased user feedback. ([#8263](https://github.com/brave/browser-laptop/issues/8263))
 - Change about:preferences#extensions link to go to the extension request category. ([#8252](https://github.com/brave/browser-laptop/issues/8252))
 - Leak in app state change listener in frame. ([#8244](https://github.com/brave/browser-laptop/issues/8244))
 - Remove old extensions settings area from Advanced prefs panel. ([#8230](https://github.com/brave/browser-laptop/issues/8230))
 - Follow-ups for showing origin of downloads. ([#8215](https://github.com/brave/browser-laptop/issues/8215))
 - Update webtorrent description on extensions page. ([#8208](https://github.com/brave/browser-laptop/issues/8208))
 - Add "Extensions..." to window menu. ([#8203](https://github.com/brave/browser-laptop/issues/8203))
 - Wallet creation fails . ([#8195](https://github.com/brave/browser-laptop/issues/8195))
 - Invisible pinned tab after upgrade. ([#8190](https://github.com/brave/browser-laptop/issues/8190))
 - URL bar shape is different with payments enabled/disabled when visiting a site. ([#8170](https://github.com/brave/browser-laptop/issues/8170))
 - Update to muon 2.58.4. ([#8161](https://github.com/brave/browser-laptop/issues/8161))
 - Url bar icon bookmark save is not working. ([#8151](https://github.com/brave/browser-laptop/issues/8151))
 - Torrent file names should be selectable. ([#8148](https://github.com/brave/browser-laptop/issues/8148))
 - Clicking Save Torrent File button does not save .torrent file. ([#8146](https://github.com/brave/browser-laptop/issues/8146))
 - Download item styling is broken when clicking trash bin icon. ([#8143](https://github.com/brave/browser-laptop/issues/8143))
 - Add temporary notice to sync prefs page regarding mobile sync, + Beta label. ([#8121](https://github.com/brave/browser-laptop/issues/8121))
 - Fix image title. ([#8116](https://github.com/brave/browser-laptop/issues/8116))
 - White tab text on dark tab background is difficult to read. ([#8115](https://github.com/brave/browser-laptop/issues/8115))
 - Javascript: bookmarks cause connection info box to appear. ([#8087](https://github.com/brave/browser-laptop/issues/8087))
 - Fix radii, colors, focused state styles in URL bar related to new add-funds button. ([#8058](https://github.com/brave/browser-laptop/issues/8058))
 - Polishing audio icon in tabs. ([#8041](https://github.com/brave/browser-laptop/issues/8041))
 - LastPass opens in wrong position when activated by keyboard. ([#8034](https://github.com/brave/browser-laptop/issues/8034))
 - Use PseudoElement for Narrow-Tab Audio Indicator. ([#8033](https://github.com/brave/browser-laptop/issues/8033))
 - About pages cannot be synced because data is too big (favicon is encoded in Base64 format). ([#8023](https://github.com/brave/browser-laptop/issues/8023))
 - Brave crashed when visiting Brave Twitter page. ([#8004](https://github.com/brave/browser-laptop/issues/8004))
 - Create commonForm.js and redesigned importBrowserDataPanel.js with it. ([#7996](https://github.com/brave/browser-laptop/issues/7996))
 - Toggle excluding a site from ledger sometimes removes it from the list. ([#7987](https://github.com/brave/browser-laptop/issues/7987))
 - Fixed - Sync does not appear to recover from network outage. ([#7972](https://github.com/brave/browser-laptop/issues/7972))
 - Fixed - Sync is losing hierarchy when adding bookmarks to new sync members. ([#7971](https://github.com/brave/browser-laptop/issues/7971))
 - Delete confirmation message ("Delete?") should be able to be localizable. ([#7958](https://github.com/brave/browser-laptop/issues/7958))
 - Refactor siteInfo.js with Aphrodite. ([#7949](https://github.com/brave/browser-laptop/issues/7949))
 - Add a new tab page for private tabs. ([#7934](https://github.com/brave/browser-laptop/issues/7934))
 - Refactor bookmarksToolbar.js with Aphrodite. ([#7920](https://github.com/brave/browser-laptop/issues/7920))
 - Back/forward gesture should support three finger swipe. ([#7905](https://github.com/brave/browser-laptop/issues/7905))
 - First time wallet creation needs a better UI. ([#7889](https://github.com/brave/browser-laptop/issues/7889))
 - Modified contributionStatement.js with Aphrodite. ([#7883](https://github.com/brave/browser-laptop/issues/7883))
 - Ubuntu: Brave doesn't know that it's the default browser.. ([#7800](https://github.com/brave/browser-laptop/issues/7800))
 - As a user i want to see modern looking spinner animation on tab loads. ([#7779](https://github.com/brave/browser-laptop/issues/7779))
 - Change "Save Torrent File" button to "Copy Magnet Link" for magnet links. ([#7772](https://github.com/brave/browser-laptop/issues/7772))
 - Dead tab when enter is pressed twice after typing in URL. ([#7727](https://github.com/brave/browser-laptop/issues/7727))
 - Add "Command+Click" to home button (opens home in a new background tab). ([#7718](https://github.com/brave/browser-laptop/issues/7718))
 - View Source shortcut should be CTRL+U, not CTRL+ALT+U. ([#7702](https://github.com/brave/browser-laptop/issues/7702))
 - Refactor about:about with Aphrodite (part 1). ([#7670](https://github.com/brave/browser-laptop/issues/7670))
 - Fixed wrong Y position in second level (or higher) folders in bookmark menu (when having many entries). ([#7662](https://github.com/brave/browser-laptop/issues/7662))
 - Downloads should show origin. ([#7468](https://github.com/brave/browser-laptop/issues/7468))
 - Remove label from MultiMedia devices when fingerprinting protection is on.. ([#7462](https://github.com/brave/browser-laptop/issues/7462))
 - Right click not dismissing / hiding an open menu  (Windows only). ([#7403](https://github.com/brave/browser-laptop/issues/7403))
 - Allow user to pin their favorite sites in Brave Payments (and other UI tweaks). ([#7347](https://github.com/brave/browser-laptop/issues/7347))
 - Tab loading icon is too subtle to notice. ([#7265](https://github.com/brave/browser-laptop/issues/7265))
 - Pin tabs which are loaded causes a crash. ([#7187](https://github.com/brave/browser-laptop/issues/7187))
 - Dragging bookmark into a folder (on bookmarks toolbar) doesn't work; puts at root of toolbar. ([#7019](https://github.com/brave/browser-laptop/issues/7019))
 - Spotify no longer plays music. ([#6881](https://github.com/brave/browser-laptop/issues/6881))
 - There is no obvious way to stop a torrent download once it has started. ([#6768](https://github.com/brave/browser-laptop/issues/6768))
 - Support torrent link files. ([#6671](https://github.com/brave/browser-laptop/issues/6671))
 - Add extensions panel to About:Preferences. ([#6530](https://github.com/brave/browser-laptop/issues/6530))
 - Add the release notes of the same version as the browser to about:brave. ([#6130](https://github.com/brave/browser-laptop/issues/6130))
 - Move noscript into the URL bar. ([#5792](https://github.com/brave/browser-laptop/issues/5792))
 - Some info buttons in preferences are missing content links. ([#5758](https://github.com/brave/browser-laptop/issues/5758))
 - Add context-menu option to close tabs in tab page. ([#5489](https://github.com/brave/browser-laptop/issues/5489))
 - Added extension badge colors. ([#5367](https://github.com/brave/browser-laptop/issues/5367))
 - Honey: Support chrome.browserAction.setBadgeText. ([#5366](https://github.com/brave/browser-laptop/issues/5366))
 - Default browser setting gets reset after upgrade. ([#5246](https://github.com/brave/browser-laptop/issues/5246))
 - Added Widevine support for Amazon Prime Video. ([#5233](https://github.com/brave/browser-laptop/issues/5233))
 - Added tear off tabs - Ability to drag tab into new window. ([#4402](https://github.com/brave/browser-laptop/issues/4402))
 - Fixed display of favicons on brave payments list. ([#4178](https://github.com/brave/browser-laptop/issues/4178))
 - Fixed context menu subitems display when the window is small. ([#1589](https://github.com/brave/browser-laptop/issues/1589))
