### ISSUE TITLE
Add an on-demand unload tab feature

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#800]
Some requests for it for lower memory use. Some people dislike the feature though so we should be careful about how we implelment and do it as an option.

**Comment by SJ-Diamond** [comment]
The best idea. Make things optional, so it does not get in the users way. People who want that feature can activate it, the ones who do not want it leave it alone.

**Comment by bridiver** [comment]
Sharing the tab between windows will also cut down on memory. Right now we have a process/tab/window for pinned tabs.

**Comment by luixxiul** [comment]
Fully implemented with #1795 or is there anything which #1795 does not cover?

**Comment by bbondy** [comment]
I think a right click context menu to unload tab would remain here.

**Comment by bbondy** [comment]
Here is how it works on Vivaldi, there are 2 items, one for active tab and one for all tabs except this one.
<img width="446" alt="screenshot 2016-08-11 17 02 56" src="https://cloud.githubusercontent.com/assets/831718/17604857/9810ee90-5fe5-11e6-9ed3-6899f985b8ed.png">

Also added this at the page tab level would be good for the tab page context menu.

**Comment by Liunkae** [comment]
+1 from #6251 (Tab suspend)

**Comment by petemill** [comment]
We have in #13118  a tab context menu item now named 'Discard Tab' which allows a user to manually destroy the tab's contents and reload it when the tab is made active again. However, Brave has to be running with the Debug menu on to allow this option currently.

**Comment by bsclifton** [comment]
Closing as `wontfix` since we won't be able to address this with browser-laptop. However, with [Brave Core](https://github.com/brave/brave-browser/), an extension such as [The Great Suspender](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) could be used
