### ISSUE TITLE
Copy paste issues - MacOS & Windows 10

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8000]
- Did you search for similar issues before submitting this one?

Yes, there is an old issue similar to this, specific to Windows (Oct 2016 - will locate and add here), but this appears to be happening frequently since the 0.14.0 update landed today for both macOS and Windows10.

- Describe the issue you encountered:

**Copy paste functionality issues - reported from Community users following v0.14.0 release today**

- @darkdh and I are both unable to reproduce. Awaiting info from all contributors to attempt to repro under the same system configuration. 

- Needs investigation.  

- Community Thread: https://community.brave.com/t/cant-copy-and-paste/1930/8

- Each incident as reported on the community thread are included below.

- Still receiving info from contributors, so will update this original post as more info comes in. 

**Contributor: deeds6969 (OP)**
>_i cant seem to copy and paste since update.what do i need to do_
**_awaiting additional system info_**

**Contributor: Veiss**
```Name    Version
Brave    0.14.0
rev    c23efa3
Muon    2.57.7
libchromiumcontent    57.0.2987.110
V8    5.7.492.65
Node.js    7.4.0
Update Channel    dev
os.platform    darwin
os.release    14.5.0
os.arch    x64
```
**Initial report:**
>_For me at least - I can copy and past but it doesn't show the menubar highlight when you use a keyboard command like in other applications or when you CMD+W to close a tab for example. OSX 10.10_

**Additional/New info:**
>_So to reiterate:
>-There is a copy option int he contextual menu when right clicking but no paste option
>-You can still use CMD+C and CMD+V fine however there is no visual feedback in the menubar to let you know the key command operated._

**Contributor: RodR**
**Initial report:**
>_I have the same problem in Windows 10 since the update. If I high-lite something, I used to be able to right-click and copy then Paste. Now the Paste option does not appear._
**_awaiting additional system info_**

**Contributor: PMBasse**
**Initial report:**
>_Same here happened after update,,, only says undo, redo and inspect element ...whats up with this ?!!_
**_awaiting additional system info_**

**Contributor: Krove**
**Initial report:**
>_can copy, but cannot paste._

```Brave    0.14.0
rev    c23efa3
Muon    2.57.7
libchromiumcontent    57.0.2987.110
V8    5.7.492.65
Node.js    7.4.0
Update Channel    dev
os.platform    win32
os.release    6.1.7600
os.arch    ia32
```
**Additional Info:**
>_i can right click paste on the URL bar though_

- Platform (Win7, 8, 10? macOS? Linux distro?):

macOS & Windows 10

- Brave Version (revision SHA):
0.14.0 - see above

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://github.com/brave/browser-laptop/issues/4643 (potentially related) 
https://github.com/brave/browser-laptop/issues/4490 (also sounds potentially related)

**Comment by jonathansampson** [comment]
I also had a user report this issue to me just now. In fact, I'm able to reproduce the issue here on GitHub.

![no-copy-paste](https://cloud.githubusercontent.com/assets/815158/24540104/5586972c-15b7-11e7-8b9c-c68b22bb4851.gif)

**Comment by srirambv** [comment]
Confirmed. Context menu missing on windows inside input field. Keyboard shortcuts work.

**Comment by lukemulks** [comment]
Confirmed here as well. 

- Outside of the input field, I get expected behavior. 
- Within the input field, I reproduce the issue. 

OS: Windows 10 (64bit)
Brave: c23efa3

Thanks @srirambv @jonathansampson - the note re: the input field appears to have been the missing link. 

cc: @darkdh are you able to repro what Sampson displayed above?

**Comment by alexwykoff** [comment]
I was able to isolate the issue. When the input field is empty, the copy and paste items are missing from the context menu.

<img width="358" alt="screen shot 2017-03-31 at 10 05 24 am" src="https://cloud.githubusercontent.com/assets/1434040/24556406/d66e3e2a-15f9-11e7-92b9-b1de0c02d2f0.png">
<img width="251" alt="screen shot 2017-03-31 at 10 04 38 am" src="https://cloud.githubusercontent.com/assets/1434040/24556430/f29548dc-15f9-11e7-8697-8a5c3999709e.png">


When text exists in the field, the context menu items fill appropriately.

<img width="393" alt="screen shot 2017-03-31 at 10 05 07 am" src="https://cloud.githubusercontent.com/assets/1434040/24556426/ebc4c4d8-15f9-11e7-8e9e-1b4688f56007.png">
<img width="181" alt="screen shot 2017-03-31 at 10 04 05 am" src="https://cloud.githubusercontent.com/assets/1434040/24556452/03455a1e-15fa-11e7-9c69-b803289efe0d.png">

**Comment by bsclifton** [comment]
Caused by https://github.com/brave/browser-laptop/commit/40fc1079258fe7e8cf41bcdee663c2b7b6c84e59

**Comment by Jacalz** [comment]
+1 from the community 😑
https://community.brave.com/t/can-not-copy-and-paste-on-google-maps/1954

**Comment by jordancclive** [comment]
I haven't been able to copy paste in my brave browser all day. I could before, though.

**Comment by ea42gh** [comment]
Trying to copy/paste from a docs.google.com presentation results in
a message offering to install a Docs Offline extension.

e.g.,
https://docs.google.com/presentation/d/1iO_bBL_5REuDQ7RJ2F35vH2BxAiGMocLC6t_N-6eXaE/edit#slide=id.g1df700e686_0_138

**Comment by alexchee** [comment]
I'm running into this issue but I have more information. I think it's involves multiple tabs with different sessions. It seems to work again for the first window opened and 6 tabs after moving a tab to the first position. 

I am able to right click to copy & paste in the first 5 tabs on the first window. But any other tabs (i.e. session 2, session 3, default) or windows, right click to Copy does not copy the text. I am able to Copy with hotkeys `cmd`+`C` in any tabs.

Steps to Reproduce:
1. Open a tab by clicking on `+`, visit a site (window 1)
2. Open "New Session Tab 2", visit a site (ex. https://github.com/brave/browser-laptop/issues/8000)
3. Open "New Session Tab 3", visit a site
4. Open "New Session Tab 4", visit a site
5. Open "New Session Tab 1", visit a site
6. Open 3 more new tabs with `+` , visit a site
7. Drag out a tab into a new Window (window 2)
8. Select text in new Window tab (window 2)
9. Right click and select "Copy" in context menu
10. Paste into URL bar or text editor
11. Repeat steps 9-10 on different tabs and windows

Actual result:
The pasted text does not match the intended selected copied text.

Expected result:
The pasted text should match the selected and copied text.

I haven't found a way to reproduce it consistently, maybe it's an issue with electron-clipboard. I'll update if I can find a way to consistently reproduce.

Additional Info:
```
Brave	0.22.714
V8	6.6.346.26
rev	fa2fbca
Muon	6.0.9
OS Release	10.0.17134
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	66.0.3359.139
```
