### ISSUE TITLE
Add extension inspectors

### ISSUE THREAD

**Issue by flyswatter** [brave/browser-laptop#8012]
- Did you search for similar issues before submitting this one?

yes

- Describe the issue you encountered:

As an extension developer, I often inspect my extension in one of two major contexts:

- When clicking on the extension icon in the menu, I right-click that interface and select `Inspect Element` to get a Chrome inspector for that view.
- In the extensions list, I am used to having a `background console` link, to open a full Chrome inspector for the extension background process.

Neither of these inspectors seem to exist in Brave today.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac OS 10.12.4

- Brave Version (revision SHA):

Brave	0.14.0
rev	215cba3

- Steps to reproduce:

1. Click on the extension icon in the menu, 
2. Right-click that interface.
3. Notice no contextual menu, even though this is a web view.

1. Visit `about:extensions`.
2. Notice there are no links to open background inspectors.
    
- Actual result:

There seem to be no ways to inspect extensions and their behaviors.

- Expected result:

Extension developers need dev tools to debug their extensions.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

I believe so.

- Can this issue be consistently reproduced?

Yes

- Extra QA steps:
    1.
    2.
    3.

**Comment by jonathansampson** [comment]
@flyswatter I believe we have what you're seeking, only it's not as easy to get to (not yet; I have a PR in the works to reduce friction). Go to _about:extensions_ and get the extension ID. Next, navigate to the background page via _chrome-extension://<extension-id>/backroundpage.html_. If no explicit background page is provided, the location will be _generated_background_page.html_, IIRC.

**Comment by flyswatter** [comment]
Oh great, thanks for the tip!  I'll continue debugging this soon!

**Comment by jonathansampson** [comment]
@flyswatter Please confirm whether or not this is what you needed. We'll be making it easier to reach in future builds :)

**Comment by flyswatter** [comment]
Will verify soon, still 1 day left in the Internet Identity workshop (you'd probably fit in nicely here...)
