### ISSUE TITLE
Can't have two instances at the same time

### ISSUE THREAD

**Issue by Kasmetski** [brave/browser-laptop#8019]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Can't have two instances of Brave at the same time. With another words - If Brave is open I cannot open another window with Brave - to have 2-3 or more, like Chromium,Firefox and every other browser.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu KDE
- Brave Version (revision SHA):
13.0
- Steps to reproduce:
    1. Open Brave
    2. Try to open another window/instance with Brave

**Comment by Liunkae** [comment]
Does this not work for you?
kabob menu > New Window
![image](https://cloud.githubusercontent.com/assets/19424103/24584033/a0548e58-1724-11e7-885b-054b0e605929.png)

**Comment by Kasmetski** [comment]
If I right click with mouse on tabs I see this - no new window button (like Firefox, Chromium & etc..)
[![Screenshot_20170402_150155.png](https://s10.postimg.org/h5b49w9zd/Screenshot_20170402_150155.png)](https://postimg.org/image/6v8pank3p/)

If I try to click in the KDE Menu, I have a start new instance button, but it doesn't work
[![Screenshot_20170402_150534.png](https://s18.postimg.org/mnmdj9lc9/Screenshot_20170402_150534.png)](https://postimg.org/image/xn7kuvbr9/)

I had this problem with Fedora + KDE too, with older versions of Brave

**Comment by Liunkae** [comment]
The `New Window` item is in two places. Please see the screenshot below:
![image](https://cloud.githubusercontent.com/assets/19424103/24594274/1e81305c-17f1-11e7-939e-11ffe60149bf.png)

**Comment by Kasmetski** [comment]
wow I never clicked on that '+' with right click, who would suggest there are these options. That way it's working. Could you add the other buttons too like in Chromium?
Let say I have opened a tab and I want it in a new window. There is no way to click 'move the tab in new window'. The only option is to click that '+' and copy/paste the address. Also the new window button in taskbar would be very useful.

**Comment by Liunkae** [comment]
> Let say I have opened a tab and I want it in a new window. There is no way to click 'move the tab in new window'. The only option is to click that '+' and copy/paste the address.

The "Move to tab to new window" functionality is planned to be implemented by version 1.0.0 (#4402).

> Also the new window button in taskbar would be very useful.

 I'm not sure how this would work with KDE, but there are issues for Windows (#6094) and Unity (#6887).

> Also a button when right click on a bookmark toolbar.

Could you please clarify what you mean? I'm not aware of any options missing in the bookmarks toolbar. Screenshots of the current options:

![image](https://cloud.githubusercontent.com/assets/19424103/24619883/36c43c66-1861-11e7-9381-a2b84e260dbe.png)
![image](https://cloud.githubusercontent.com/assets/19424103/24619887/3bf4f838-1861-11e7-9722-67d324636b97.png)

**Comment by Kasmetski** [comment]
I mean "Open Link in New Window' - that one is missing when right click on the bookmarks.
Screenshot from Firefox
[![Screenshot_20170404_124527.png](https://s2.postimg.org/vdaoi90tl/Screenshot_20170404_124527.png)](https://postimg.org/image/q1vrxjeqt/)

**Comment by Liunkae** [comment]
Great catch! I filed issue #8063 for that option.

**Comment by Kasmetski** [comment]
I'm closing the issue. Thanks
