### ISSUE TITLE
Video Full Screen Glitch

### ISSUE THREAD

**Issue by Cre8iveCat** [brave/browser-laptop#802]
Hi. I have recently discovered that if you open up a video and put it in full screen and close the tab without exiting full screen mode on the video, the browser will stay in full screen mode. That means you can't access the task bar or the minimize, restore down or exit buttons. The only way to fix this is to go to another window and exit out of Brave. Please fix this bug soon. Thank you.
[Example.docx](https://github.com/brave/browser-laptop/files/133679/Example.docx)

**Comment by weems** [comment]
Please see https://github.com/brave/browser-laptop/issues/726 @bbondy

**Comment by Chewy1297** [comment]
Press alt to get you menu up, then under View, at the bottom of the drop down, you can toggle Fullscreen mode. The shortcut is f11.
