### ISSUE TITLE
Bookmark moved to a folder on the toolbar cannot be removed via the star button

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8022]
**Describe the issue you encountered:** Bookmark in a folder on the toolbar cannot be removed via the star button, unless you select the bookmark folder into which you moved the bookmark. By default it is set to "bookmark toolbar" and not overwritten.

I am not sure if this is a regression.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.14.1 RC1

- Steps to reproduce:
    1. Open a page
    2. Bookmark it 
    3. Add a bookmark folder
    4. Move the bookmark into the folder
    5. Click the star button on the URL bar
    6. Click "Remove" -> bookmark is not removed
    7. Click the star
    8. **Choose the folder** and click "Remove" -> bookmark is removed
    
- Actual result: the bookmark folder is not overwritten after moving the bookmark to another folder from "bookmark toolbar"

- Expected result: it should be overwritten

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Moving to 0.14.3- without an owner, this is at risk

**Comment by bsclifton** [comment]
site entries have folder as the key- we'll need to consider this when removing

**Comment by NejcZdovc** [comment]
Should be fixed with #9979
