### ISSUE TITLE
Bookmarks in Other Bookmarks folder is synced to the bookmark toolbar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8024]
## Test plan

https://github.com/brave/browser-laptop/pull/9216#issue-233323604

----

**Describe the issue you encountered:** Bookmarks in Other Bookmarks folder is synced to the bookmark toolbar

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.1 RC1

- Steps to reproduce:
    1. Bookmark a page
    2. Open about:bookmarks
    3. Drag the bookmark to Other Bookmarks
    4. Set up sync
    5. Sync with another machine
    
- Actual result: On the another machine, the bookmark appears on the bookmark toolbar

- Expected result: it should be synced into Other Bookmarks folder and should not appear on the bookmark toolbar

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
seems this is due to parentFolderId being `-1` for 'Other Bookmarks', which sync does not recognize as a valid value

**Comment by luixxiul** [comment]
it is not possible to confirm the bug was fixed as you cannot drag and drop the bookmark to `Other Bookmarks`.

**Comment by diracdeltas** [comment]
@luixxiul per test plan in https://github.com/brave/browser-laptop/pull/9216#issue-233323604, you can right-click on "other bookmarks" to add a folder (not a bookmark though)
