### ISSUE TITLE
Tabs can be pinned / unpinned by dragging them

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8027]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you have a few pinned tabs, you're able to change regular tabs into pinned (and vice versa) by dragging them. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (but probably on all)

- Brave Version (revision SHA):
0.14.0 but has been around for quite a while (I keep forgetting to log)

- Steps to reproduce:
Steps via GIF
![whoops](https://cloud.githubusercontent.com/assets/4733304/24576080/0baa9654-166a-11e7-9556-6799be2ad8e6.gif)

cc: @cezaraugusto

**Comment by darkdh** [comment]
I thought this is the expected behavior. cc @bbondy

**Comment by bbondy** [comment]
that's a feature not a bug :P

**Comment by bsclifton** [comment]
OK great! 😄  Thanks for confirming
