### ISSUE TITLE
Refactor widevinePanel.js and widevineInfo.js with Aphrodite and commonForm

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8028]
## Test plan

https://github.com/brave/browser-laptop/pull/8032#issue-218718533

----

**Describe the issue you encountered:**
Refactor widevinePanel.js and widevineInfo.js with Aphrodite and commonForm

<img width="611" alt="screenshot 2017-04-01 15 34 44" src="https://cloud.githubusercontent.com/assets/3362943/24576140/454d74b2-16f1-11e7-99fd-3703a585212b.png">
<img width="610" alt="screenshot 2017-04-01 15 43 40" src="https://cloud.githubusercontent.com/assets/3362943/24576176/0995b0b4-16f2-11e7-8795-6ba62fc640b2.png">

- Any related issues: #7990 #7989 #8009

**Comment by cezaraugusto** [comment]
closed by c1894b1

**Comment by luixxiul** [comment]
May I reopen this, as this is not ready yet on master and I have set to close this automatically when it is merged to master with a new PR, after every PR I have created which is related to commonForm is merged to `refactor-aphrodite`. I'm taking care of every issue which I assinged myself, thanks!

**Comment by luixxiul** [comment]
FYI there are 4 other PRs under WIP/ready-for-review before I am going to create that PR at last.

**Comment by luixxiul** [comment]
note: widevine plugin is not available for linux distros
