### ISSUE TITLE
Unable to open new private tab by using keyboard shortcut while writing in a markdown box on Github

### ISSUE THREAD

**Issue by Shnkc** [brave/browser-laptop#8030]
- Did you search for similar issues before submitting this one?
yes.
- Describe the issue you encountered:
On `github`, while I am writing in a markdown box, if I try to open a new private tab by hitting `cmd+shift+p`, the markdown turns to `preview` mode.
- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOsX Sierra 10.12
- Brave Version (revision SHA):
0.14.1 - 3de60d5
- Steps to reproduce:
    1. I write in a markdown box on `Github` (e.g. the markdown box of new issue page)
    2. I hit `cmd+shift+p`
    
- Actual result:
The markdown box turns to `preview` mode
- Expected result:
Brave opens a new private tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.
- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
Yes.

- Screenshot if needed:

- Any related issues:
#4024

https://github.com/brave/browser-laptop/issues/2219

**Comment by Liunkae** [comment]
Related: #1867 

A workaround is to unfocus the text field before pressing <kbd>Cmd+Shift+P</kbd>.

**Comment by luixxiul** [comment]
duping to #1867
