### ISSUE TITLE
LastPass opens in wrong position when activated by keyboard

### ISSUE THREAD

**Issue by josiah-keller** [brave/browser-laptop#8034]
## Test Plan
1. Use Preferences > Security to change password manager to LastPass
2. Tab focus from address-bar to LastPass icon
3. Press Enter
4. Popup should open beneath extension icon

## Original issue description
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: If you tab over to LastPass from the URL bar and press Enter, the popup appears in the wrong location on the screen.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 3de60d5

- Steps to reproduce:
    1. Enable & configure LastPass
    2. Focus URL Bar
    3. Press tab once
    4. Press enter
    
- Actual result: LastPass popup appears at the left of the window.

- Expected result: LastPass popup should appear beneath the LastPass icon on the right.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Any related issues:

**Comment by josiah-keller** [comment]
The problem is the event coords that are IPC'd in `browserActionButton.js` are all 0 when the event comes from the keyboard.

**Comment by jonathansampson** [comment]
Thanks, Josiah! I was able to repro.

**Comment by luixxiul** [comment]
@bsclifton would you mind picking this up on the next release? It is not available yet on 0.14.1 Preview1. / CC: @alexwykoff @srirambv @Jacalz

**Comment by Jacalz** [comment]
Sorry but what am I supposed to do? @luixxiul Also would be great to to know exactly what cc means 😂 We swedes don't use many abbreviations 🇸🇪😬

**Comment by luixxiul** [comment]
@Jacalz I mentioned you because I thought you would be going to do QA work on this release too. Please ignore my comment if you would not.  "CC" is the same as you would use on email -> To, CC, BCC. just fyi :-)

**Comment by Jacalz** [comment]
Okay, now I get it 😅 Thanks, for the heads up 😉 Off course I will do my tests on this, will add this as a test 😉 @luixxiul

**Comment by Jacalz** [comment]
Will ad it to my tests, will do these tests when I have some time over 👍

**Comment by bsclifton** [comment]
This should be included with Preview 2 👍
