### ISSUE TITLE
Refactor payment/history.js

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8037]
## Test plan 

https://github.com/brave/browser-laptop/pull/8038#issue-218756988

----

**Describe the issue you encountered:**
Refactor payment/history.js

The payment history should be styled like this based on https://github.com/brave/browser-laptop/pull/6047#issue-193827878:

> <img width="736" alt="screenshot 2016-12-15 3 36 37" src="https://cloud.githubusercontent.com/assets/3362943/21195619/e1ad79e8-c277-11e6-8d5d-d5d428b9247e.png">

The original mockup provided by @bradleyrichter is available here: https://github.com/brave/browser-laptop/issues/6202

Currently:
<img width="715" alt="screenshot 2017-04-02 18 13 47" src="https://cloud.githubusercontent.com/assets/3362943/24585897/24a3fe18-17d0-11e7-9af2-5155e8223bf3.png">

- Any related issues: #7381 #7423

**Comment by DivineOmega** [comment]
Would it make sense to right align the monetary values in the second column? This would ensure the decimal points line up and possibly make it easier to skim read the values.

**Comment by luixxiul** [comment]
I could try like this:

<img width="728" alt="screenshot 2017-04-03 13 26 21" src="https://cloud.githubusercontent.com/assets/3362943/24595400/31874ac6-1871-11e7-8a38-6d0e7abf75a2.png">

Yet it seems difficult to align the columns to the label (Total Amount), in terms of localization. I don't have a good idea for that

**Comment by bbondy** [comment]
btw for refactors please always mark as release-notes/exclude
