### ISSUE TITLE
To conserve bandwidth do not preload pinned tabs until they are selected on launch

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#804]
A user brought up that preloading the pins on launch could be bad for those without unlimited bandwidth.

I add that it might be also a security issue when connected on some less secured networks.

**Comment by psimyn** [comment]
related / duplicate of https://github.com/brave/browser-laptop/issues/800 ?

**Comment by VirgilRoussos** [comment]
I do not think so. It is not a delay, but simply a "do not load until called". However if you feel the two issues can be merged since a single options menu can solve "delay/do not load"

**Comment by psimyn** [comment]
ah, I thought delay was "on-demand load tabs"

**Comment by luixxiul** [comment]
Fixed with #1795

**Comment by luixxiul** [comment]
Not only on launch but also on detach a tab.

**Comment by bsclifton** [comment]
I believe this will be solved with https://github.com/brave/browser-laptop/issues/13216
cc: @petemill

**Comment by petemill** [comment]
I don't think #13216 will fix bandwidth per-say, as we are not creating pinned tabs as lazy-loaded (discarded), so muon will still be fetching the content on startup. #13216 should make sure we're not using the window's resources to display the content, however. This could be a simple change to the following, though not sure if it's there for a particular reason - worth testing:

https://github.com/brave/browser-laptop/blob/4ae1b6d88be54824a91e12749c2f0d0477ca877d/app/browser/tabs.js#L970-L977

**Comment by bradleyrichter** [comment]
The original plan for pinned tabs was that they were to bereferenced across windows and not duplicated. If we can not get to this enhancement, perhaps we should remove the feature of populating pins on all windows - changing it to window-specific pins.  

@petemill @bsclifton ?

**Comment by bsclifton** [comment]
@bradleyrichter w/ regard to multiple pins using same web contents, @bbondy did start work on that type of enhancement when implementing tab detaching... but it wasn't finished

**Comment by srirambv** [comment]
@bbondy i think this will be fixed in brave-core correct? 

cc: @bsclifton

**Comment by NumDeP** [comment]
+1 On Chromium if you were to open a dozen bookmarks from a folder in one go, they would all load in task manager wouldn't they, if so, I doubt brave-core fixes this unless you've made changes to this affect.

**Comment by bsclifton** [comment]
Should be fixed with brave-core
