### ISSUE TITLE
No shortcut key for active tab on Bravo OSX?

### ISSUE THREAD

**Issue by johnsn0w101** [brave/browser-laptop#8040]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
No shortcut key for active tab on Bravo OSX, is there one or am I missing it ?

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS
- Brave Version (revision SHA):
Brave	0.14.1
rev	3de60d5

- Steps to reproduce:
    1. Open tab
    2. Close current active tab with shortcut key
    3.
    
- Actual result:
Nothing
- Expected result:
Tab is closed
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
> Close current active tab with shortcut key

<kbd>Cmd+W</kbd> works for me. It's the standard shortcut used by all other major browsers.

**Comment by Liunkae** [comment]
> Close current active tab with shortcut key

Brave uses <kbd>Cmd+W</kbd>, the standard shortcut used by all other major browsers.

**Comment by bsclifton** [comment]
Closing issue as you can use <kbd>Cmd+W</kbd> as @Liunkae has pointed out (this is standard on macOS)
