### ISSUE TITLE
Polishing audio icon in tabs

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8041]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Audio icon is jumping when you toggle it
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
6c4d8a5
- Steps to reproduce:
    1. go to youtube
    2. play a video
    3. toggle audio icon
    
- Actual result:
![10](https://cloud.githubusercontent.com/assets/9574457/24589263/070e3514-17d8-11e7-8b22-af65a3757aed.gif)

- Expected result:
Audio icon should always stay in the same place
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by luixxiul** [comment]
Please have a look at this: https://github.com/brave/browser-laptop/issues/1776
