### ISSUE TITLE
Dead tab when loading large content

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8045]
Browser UI elements (home button, reload button) are blocked and unresponsive when page is loading a large amount of content

I know this has happened to @BrendanEich recently. Repro steps by @NejcZdovc:

1. Go to https://github.com/brave/browser-laptop/pull/7795/files
2. `npm-shrinkwrap.json` is not expanded by default
3. Click `Load diff` and wait a few seconds
4. Click the reload button (next to the URL bar) a few times
5. Notice nothing happens

**Comment by luixxiul** [comment]
I have noticed it as well when I load large pictures on a slow connection. I thought back/forward/reload button was not available until onload event was fired.

**Comment by bsclifton** [comment]
@luixxiul great find! I believe this can be the problem.  We are likely having cases where the onload never fires because of a network error, etc.  We should look at changing this behavior or possibly adding a timeout

**Comment by bsclifton** [comment]
This appears to be fixed 😄 

@luixxiul @srirambv @LaurenWags could you try the steps listed here and confirm it's fixed? (to help make sure I'm not crazy?).  Thanks 😄

**Comment by LaurenWags** [comment]
@bsclifton - looked ok to me (MacOS)

**Comment by srirambv** [comment]
@bsclifton Looks good on Windows 10 x64, although the onclick response  is a little delayed and not instant as for normal page content

**Comment by bsclifton** [comment]
awesome! I'll mark this as closed. I think the slowness is captured pretty well with our [perf tracking issue](https://github.com/brave/browser-laptop/issues/9311)
