### ISSUE TITLE
User whitelisting for tracking/ads

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#805]
Some websites such as http://www.bild.de/ actually agressively block people with adblocking mechanisms to access.

Could an user maintain a whitelist for tracking/ads/both in order to make them work without needing to go into bravery options?

**Comment by weems** [comment]
@VirgilRoussos https://brave.com/dev_timeline.html may be useful to users requesting

**Comment by weems** [comment]
It is in the plans @VirgilRoussos

**Comment by VirgilRoussos** [comment]
Thanks!

**Comment by cezaraugusto** [comment]
For legacy purposes, the current link for Brave timeline is https://github.com/brave/browser-laptop/wiki/Brave-Development-Timeline
