### ISSUE TITLE
Mouse displayed during fullscreen

### ISSUE THREAD

**Issue by DevShekhawat7** [brave/browser-laptop#8050]
while playing youtube or any player in fullscreen, mouse pointer does not hide itself

**Comment by jonathansampson** [comment]
I think this is a bug. Thank you for filing!

Browser | Behavior
-|-
Chrome | Hides mouse
Firefox | Hides mouse
Edge | Hides mouse
Brave | Displays mouse

**Comment by jonathansampson** [comment]
Due of https://github.com/brave/browser-laptop/issues/7966
