### ISSUE TITLE
Clicking the trash bin icon on the download bar sometimes does not display the confirmation

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8052]
**Describe the issue you encountered:**

sometimes it works, sometimes it doesn't. It is hard for me to tell what the cause of it is and how to reproduce the issue constantly.

![delete](https://cloud.githubusercontent.com/assets/3362943/24616382/eb1123b8-18cb-11e7-83a8-0a2ed7d35cb1.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.14.1

- Steps to reproduce:
    1. Download a file
    2. Click the trash bin icon
    
- Actual result:

- Expected result: it should always display the confirmation dialog

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Moving to 0.14.3

**Comment by alexwykoff** [comment]
Let's see if we can't reduce this a bit to more specific steps.

**Comment by luixxiul** [comment]
On the latest RC I don't see the issue yet. I'm going to see if it was fixed.

**Comment by alexwykoff** [comment]
@NejcZdovc please see if redux component fixes this

**Comment by luixxiul** [comment]
I can no longer reproduce the issue. Closing.
