### ISSUE TITLE
Refactor modalOverlay with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8054]
Refactor modalOverlay with Aphrodite

- Any related issues:

**Comment by luixxiul** [comment]
TODO: Move styles from commonStyles.js to modalOverlay.js, which are defined here: https://github.com/brave/browser-laptop/pull/8044/commits/20d703180c83c1fdd8edf7b30c01ffe56394e7c9#diff-fa59d1e0221a5bee94fd2abd9b96dcfdR62 of #8044

**Comment by NejcZdovc** [comment]
@luixxiul do you have maybe an eta about this one?

**Comment by luixxiul** [comment]
0.14.3 or so, not the next one.
