### ISSUE TITLE
Startup issue on MacOS

### ISSUE THREAD

**Issue by too4words** [brave/browser-laptop#8055]
After building on MacOS, I get the following node.js mismatch:

An uncaught exception occurred in the main process Uncaught Exception:
Error: The module '/Users/livshits/Code/browser-laptop/node_modules/ad-block/build/Release/ad-block.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/livshits/Code/browser-laptop/app/adBlock.js:8:25
    at Object.<anonymous> (/Users/livshits/Code/browser-laptop/app/adBlock.js:120:2)
Waiting 60 seconds for process to load

Node is up to date. No amount of rebuilding makes this go away.

**Comment by bsclifton** [comment]
@too4words what version of Node do you have?

**Comment by too4words** [comment]
7.8.0

**Comment by willy-b** [comment]
I'm not on MacOS, but `npm install --build-from-source` may help

**Comment by too4words** [comment]
I tried --build-from-source and get the exact same error

**Comment by willy-b** [comment]
Shoot, clearing `node_modules` and running `npm install --build-from-source` is what fixed this particular error (NODE_MODULE_VERSION) mismatch for me.
I mostly run out of  browser-laptop-bootstrap (https://github.com/brave/browser-laptop-bootstrap) as it tends to work even if the build breaks here. But it takes much longer to build.

**Comment by too4words** [comment]
fixed now

**Comment by Liunkae** [comment]
Closing as fixed.
