### ISSUE TITLE
Fix Standard.js lint errors

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8061]
**Describe the issue you encountered:** Fix Standard.js lint errors.

Adding the priority/high label as the errors appear everytime on commit and makes it difficult to detect if errors are related with the commit which you are going to create.

- Any related issues:

**Comment by NejcZdovc** [comment]
@luixxiul I already fix this in #7951

**Comment by luixxiul** [comment]
Sweet. Would you please merge this into the master asap? 

If you will continue to work on that PR, I would like to ask you to cherry-pick the commit and create another PR which has the commit only, since it seems that it would take some time to review all of the commits there. Thanks!

**Comment by NejcZdovc** [comment]
This PR is done and just needs to be reviewed
