### ISSUE TITLE
Revert the inlined files on contributionStatement.js (follow up to #7887)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8062]
## Test plan
See https://github.com/brave/browser-laptop/pull/8107

## Original issue description
**Describe the issue you encountered:**
Revert the inlined files on contributionStatement.js (follow up to #7887) after making it possible to use the external image files.

- Any related issues: https://github.com/brave/browser-laptop/pull/7887#issuecomment-291491654 #7883

**Comment by cezaraugusto** [comment]
Reopening. We still can't use external images but I have a fix to avoid hard-coding base64
