### ISSUE TITLE
Change color of the lock/cert modal on https websites

### ISSUE THREAD

**Issue by jfgoncalves** [brave/browser-laptop#8064]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered: The lock indicating https secured connections is grey. This color does not give a feeling of security/trust, and force the user to check the shape of the lock or check the start of the address bar.

- Platform (Win7, 8, 10? macOS? Linux distro?): MacOS El Capitan 10.11.6

- Brave Version (revision SHA): 0.14.1

- Steps to reproduce:
    1. Open Brave
    2. Access any https-enabled website
    
- Actual result: Lock in the address bar and certificate modal are grey and does not give a feeling of trust/security nor is clearly distinctive to the user if the connection is secured without taking extra subconscious steps.

- Expected result: Lock should be green to help user subconsciously verify if the connection is secured without resorting to analyzing the shape of the lock nor the text in the address bar. Certificate modal could also be themed with a shade of green to reinforce the trust/secure feeling. Green or blue are usually good colors to give this feeling of trust/security, green is more common in browsers though.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
CC @bradleyrichter and @diracdeltas for comments.

**Comment by diracdeltas** [comment]
Our long-term goal is to show HTTPS as normal and HTTP as insecure, similar to Chrome: https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html
