### ISSUE TITLE
Favicon change to other site favicon

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#8068]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Randomly, the favicon in non-active tab/pinned tab change to other favicon from other site

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 8.1

- Brave Version (revision SHA):
0.14.1 (3de60d5)

- Steps to reproduce:
    1. Open twitter.com in new tab
    2. Close tab
    3. Favicon in non-active tab/pinned tab changed
    
- Actual result:
Favicon in non-active tab/pinned tab change to favicon from other site which recently closed.

- Expected result:
Favicon not changed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![favicon-bug](https://cloud.githubusercontent.com/assets/25360853/24679747/6dd2c468-19b8-11e7-8bcd-3a1e893da8c4.png)

- Any related issues:
#1646

**Comment by dominykas** [comment]
I have this issue too. Reloading the tab usually fixes it for the tabs. Not sure why it happens though. Right now I had a favicon of a tab that was possibly the last one closed before computer went to sleep.

I also have the wrong favicon in the bookmarks bar for a site that has no favicon.

**Comment by cezaraugusto** [comment]
closing as fixed, please re-open if issue re-appears
