### ISSUE TITLE
bookmarklets should not be able to run on `about:` pages

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#808]
https://github.com/brave/browser-laptop/commit/a4f6d0beeeffb46c0af9718440c99ffbbca0c7fa introduced support for bookmarklets (bookmarked `javascript:` URLs). these should probably be prevented from running on `about:` pages, otherwise a user can be tricked into installing a bookmarklet that messes with their browser settings or does other privileged actions.

**Comment by bbondy** [comment]
I think the javascript:alert('hi') actually runs on the browser level currently (which is a bigger problem)

**Comment by diracdeltas** [comment]
I did check that the JS didn't have access to node functions (`process.env`, `require('fs')`, etc) and also that `documentElement.style='display:none'` hid the page contents; so i think it's running in the page level

**Comment by bbondy** [comment]
Ya I'm seeing kind of mixed results here. What I'm seeing is the same as you except for alerts.

bookmarklet with: javascript:alert('hi')
Seems like it puts the alert at the browser level.  

For example open browser console vs webview console with an alert and see the visual difference. 

I think also the src="" shoudn't change but we should route it to webview.loadUrl  maybe

**Comment by diracdeltas** [comment]
Yeah, it does look like the alert is at the browser level, even if the javascript: url is opening in a new tab. I think that is not too surprising - in the console case, the alert is a script running on the page. In the `javascript:` case, it's the top-level URL of the webview frame. I guess Electron UI handles the two cases differently.

**Comment by bbondy** [comment]
Is this currently a problem? The javascript: url currently changes the src and then a new webview is created at that point because of the contentScript changes.  I couldn't reproduce getting the $HOME surprise file with your bookmarklets at https://zyan.scripts.mit.edu/node_test/test.html

**Comment by weems** [comment]
I think it's to prevent a problem from occurring as more functionality is added.

**Comment by diracdeltas** [comment]
> Is the original issue you posted here currently a problem? The javascript: url currently changes the src and then a new webview is created at that point because of the contentScript changes.

Not quite, actually. If you bookmark the bookmarklet at https://jsfiddle.net/vrb36jb9/ and then click it, it looks like what happens is that the js runs in the current page, and then the webview tries to navigate to the js URL. So I'm still not sure why the alert appears at the browser level.

**Comment by bbondy** [comment]
Ya I can't explain that either.  Just checking this is not a blocker for release of 0.7.15 right?

**Comment by diracdeltas** [comment]
Not a blocker

**Comment by luixxiul** [comment]
How about the situation?
