### ISSUE TITLE
Add an optional Bookmarks Menu Icon 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8080]
From community https://community.brave.com/t/add-an-optional-bookmarks-menu-icon/2062
>Please add an optional bookmarks menu icon to the main navigation bar next to the back/forward/reload buttons. A single button you can click to open a drop down menu to select bookmarks from.
>
>I find the bookmarks toolbar extremely limited for large numbers of bookmarks, I have over 250 bookmarks sorted into 17 major folders each with subfolders. The toolbar approach is inadequate for this, a dropdown menu is more efficient.

Could be an option to be implemented with #7986

**Comment by JGH1000** [comment]
+1, bookmark toolbar takes too much space without being any more useful than additional menu.
