### ISSUE TITLE
Different profile folder with --user-data-dir= (Windows)?

### ISSUE THREAD

**Issue by highend** [brave/browser-laptop#8093]
Hi,

by default Brave puts it's user files in %APPDATA%\brave

To use it in a portable fashion you can normally use
--user-data-dir=

on chrome/chromium based browsers

But invoking brave from a dos prompt with
brave.exe --user-data-dir=.\profile

where the profile folder already exists, Brave still uses the %APPDATA%\brave
folder...

Is there anything planned to support that?

Latest windows release version of Brave

**Comment by bsclifton** [comment]
@highend I just tested and verified this does work as expected- I think I see the problem (apologies it's taken this long to respond)

The param you have is correct, but the `.\` part is messing it up I think.  I tried launching Brave like so:
`Brave.exe --user-data-dir=brave-testing123`

And this created a new directory `brave-testing123` for me inside `%APPDATA%`.  If you're still using Brave, please try again and let me know.  Thanks 😄
