### ISSUE TITLE
Extension: React Developer Tools

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8095]
Extension: [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)

## Needed APIs:
**chrome.devtools**
- chrome.devtools.inspectedWindow.eval ([docs](https://developer.chrome.com/extensions/devtools_inspectedWindow#method-eval))
- chrome.devtools.inspectedWindow.tabId ([docs](https://developer.chrome.com/extensions/devtools_inspectedWindow#property-tabId))
- chrome.devtools.network.onNavigated.addListener ([docs](https://developer.chrome.com/extensions/devtools_network#event-onNavigated))
- chrome.devtools.network.onNavigated.removeListener ([docs](https://developer.chrome.com/extensions/devtools_network#event-onNavigated))
- chrome.devtools.panels.create ([docs](https://developer.chrome.com/extensions/devtools_panels#method-create))

**chrome.runtime**
- chrome.runtime.connect ([docs](https://developer.chrome.com/extensions/runtime#method-connect))
- chrome.runtime.getURL ([docs](https://developer.chrome.com/extensions/runtime#method-getURL))
- chrome.runtime.onConnect.addListener ([docs](https://developer.chrome.com/extensions/runtime#event-onConnect))

**chrome.tabs**
- chrome.tabs.executeScript ([docs](https://developer.chrome.com/extensions/tabs#method-executeScript))

**Comment by jeroenvisser101** [comment]
Until this issue is resolved, [these docs regarding using electron-devtools-installer](https://github.com/brave/muon/blob/master/docs/tutorial/devtools-extension.md) are incorrect and confusing.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/add-extension-react-dev-tools-to-use-brave-as-browser-to-test-and-analize-components-of-react-technologies/21877/2

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
