### ISSUE TITLE
Set the file type filter when presenting a save dialog

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8096]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When saving an image, Brave does not populate the _Save as type_ value in the dialog.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/3de60d52df3ef48d12d9696a076b72079beb9658

- Steps to reproduce:
    1. Navigate to https://i.imgur.com/3w0l0MM.png
    2. Right click, and select _Save Image_
    3. Note that _Save as type_ is "All Files (\*.\*)" rather than "PNG Image"
    
- Actual result:

![image](https://cloud.githubusercontent.com/assets/815158/24735475/b702d322-1a48-11e7-9b4e-a4fb6ea897f2.png)

- Expected result:

![image](https://cloud.githubusercontent.com/assets/815158/24735495/cf7b8cdc-1a48-11e7-8835-a398c33af033.png)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
duping to https://github.com/brave/browser-laptop/issues/1985 and https://github.com/brave/browser-laptop/issues/2554 ?

**Comment by bsclifton** [comment]
@luixxiul this is a little different (but related). The "Save as type" box should be set based on the file name. This change will be a Muon/electron change

**Comment by bsclifton** [comment]
@jonathansampson should this be in 0.14.2? We're closing up dev on this soon and without an owner, it's at risk

**Comment by jonathansampson** [comment]
@bsclifton It _should not_. I've punted to *1.0.0*.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Verified on muon 5.1.0 built from source rev aa9db3c

**Comment by kjozwiak** [comment]
Verified the above issue using macOS 10.13.3 using the following build:
* `0.22.6` e6ff4ea
* libchromiumcontent: `65.0.3325.162`
* muon: `5.1.0`
