### ISSUE TITLE
View Source + Clicking Back Breaks View Source

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#810]
1. Go to google.com
2. right click and click view source
3. click the back button to return to google.com
4. click view source again
5. notice view source fails to appear

I am using https://github.com/brave/browser-laptop/commit/fb06bed63e4757fe376b478ff2b3864abef5f506 on winx64

**Comment by psimyn** [comment]
This is duplicate of
https://github.com/brave/browser-laptop/issues/798

I'm 90% sure it's the same as https://github.com/brave/browser-laptop/issues/799 as well - location and src properties get set when url changes but not when clicking back/forward

**Comment by weems** [comment]
@psimyn Thanks Closing.
