### ISSUE TITLE
Ledger calculation when 0 eligible unpinned sites

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8102]
## Test Plan
- Go to payments and add two publishers
- Pin one and exclude the second one
- Set 60 % for a pinned publisher
- Value should be adjusted to 100%

## Automated test plan
`npm run test -- --grep="check pinned sites amount, when you have 0 eligible unpinned sites"`

- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Calculation in the ledger table is wrong when you don't have any eligible unpinned sites and you set custom % for a pinned site that is bellow 100%.

- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
7080042
- Steps to reproduce:
    1. Go to payments and add two publishers
    2. Pin one and exclude the second one
    3. Set 60 % for a pinned publisher
    
- Actual result:
Value stays the same, 60%

- Expected result:
Value should be changed to 100%
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes

- Screenshot if needed:
![pasted image at 2017_04_05 01_02 pm](https://cloud.githubusercontent.com/assets/9574457/24741855/fdb91d4e-1aa7-11e7-90f9-cd0700c67b66.png)

- Any related issues:
#7347

**Comment by luixxiul** [comment]
To QA testers: https://github.com/brave/browser-laptop/commit/077a60c93b4a3ef4c327a043900f6ea12ee6c53c of #8103 is not yet available on 0.14.1 Preview 1
