### ISSUE TITLE
Remove searx search engine

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8113]
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/7658#issuecomment-292484966

> [searx.me](https://searx.me/) closed down its service for today, promoting the use of other public instances. 

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by cwmke** [comment]
I think instead of removal we should switch to another public instance such as search.gibberfish.org.

**Comment by luixxiul** [comment]
the site is online again
