### ISSUE TITLE
Fix image title

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8116]
Per https://community.brave.com/t/background-image-title-incorrect/2106

![image](https://cloud.githubusercontent.com/assets/4733304/24812495/20179faa-1b7f-11e7-94e8-c0f3c16843cb.png)
> This is an extremely minor issue, I almost hesitate to bring it up, but this beautiful image is "Griffith Park Observatory in Downtown Los Angeles," not "Downtown Griffith." Lived in LA for many years and I LOL'd when I saw the caption.

**Comment by bsclifton** [comment]
Official page link:
http://www.sergeramelliphotos.net/fullscreen-page/comp-iscf4kfn/33878ee5-d6b6-42dc-b4d5-4c01e312de50/15/%3Fi%3D15%26p%3Dtbded%26s%3Dstyle-iscf4kfo1

**Comment by luixxiul** [comment]
By loading 30 times :sweat_smile: finally:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24861341/6747ae9a-1e33-11e7-9381-f9c8074e6a8a.jpg)
