### ISSUE TITLE
Disabling Widevine preference should either work immediately or require a restart.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8117]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After disabling Widevine in preferences, I was still able to use it in tabs. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Discovered on OS X

- Brave Version (revision SHA):
0.14.1 (3de60d5)

- Steps to reproduce:
    1. Turn on Widevine
    2. Visit a Widevine-using site like the Spotify web player
    3. Turn off Widevine
    4. Try playing a song with the web player
    
- Actual result:
The songs play without issue.

- Expected result:
Since I disabled Widevine, songs should no longer play.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
This is the same with flash as well. Enable flash and visit a page with flash content and then disable flash, would still load the flash content on the page.   I remember @diracdeltas mentioned to me that the content will load until the page is refreshed for it to be not detected. Its what expected!

**Comment by alexwykoff** [comment]
Nah, this shouldn't be expected. If I turn a light switch off, does the room stay lit? 😸

**Comment by diracdeltas** [comment]
to fix this we would probably need to reload all of the tabs running widevine

**Comment by diracdeltas** [comment]
closing in favor of https://github.com/brave/browser-laptop/issues/13574
