### ISSUE TITLE
Close Tab 'X' Not Visible

### ISSUE THREAD

**Issue by philkloose** [brave/browser-laptop#8119]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
The 'X' to close a tab is occasionally rendered below the tab bar and thus hidden. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7 SP1 (x64)
- Brave Version (revision SHA):
Brave: 0.14.1 
rev: 3de60d52df3ef48d12d9696a076b72079beb9658 
Muon: 2.57.8 
libchromiumcontent: 57.0.2987.133 
V8: 5.7.492.71 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.1.7601 
os.arch: x64
- Steps to reproduce:
I haven't been able to reproduce it easily. :( When I saw the issue it was occurring on a couple of tabs out of 8 -- not all of them.
    
- Actual result:
![image](https://cloud.githubusercontent.com/assets/5502734/24820152/45289e88-1bad-11e7-80c9-720113fa0939.png)
![image](https://cloud.githubusercontent.com/assets/5502734/24820211/865157ba-1bad-11e7-807c-beb4b6541e45.png)
As you can see the close tab 'X' is rendered on a second line and barely visible.
- Expected result:
The 'X' should should be rendered at the far right of the tab on the same line as the page title.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Not that I've been able to figure out.

**Comment by bsclifton** [comment]
cc: @cezaraugusto

**Comment by alexwykoff** [comment]
@luixxiul could you please try to replicate it? 

If you cannot, feel free to close as DNR, thanks.

**Comment by cezaraugusto** [comment]
I wasn't able to repro even removing elements to force overflow, using Ubuntu and macOS, so tagging as Win-specific, feel free to change if not

**Comment by cezaraugusto** [comment]
@luixxiul are you able to repro that on Win?

**Comment by philkloose** [comment]
I myself haven't really been able to reproduce this myself ever since I initially filed it.

**Comment by alexwykoff** [comment]
Closing DNR
