### ISSUE TITLE
add option to allow ALT instead of CTL for arrow keyboard shortcuts

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#812]
If possible, could the keyboard shortcut for back and forward be alt + arrow key rather than ctrl + arrow key. When typing I sometimes use ctrl + arrow key to quickly move between words when making edits.

**Comment by bbondy** [comment]
are you on Windows or OSX?  On OSX alt + arrow key goes to previous word.

**Comment by luixxiul** [comment]
On Windows 10 too, closing for now.
