### ISSUE TITLE
Add temporary notice to sync prefs page regarding mobile sync, + Beta label

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8121]
## Test plan

https://github.com/brave/browser-laptop/pull/8131#issue-220415095

----

![image](https://cloud.githubusercontent.com/assets/13509546/24820765/a4e4977c-1b9f-11e7-8d85-88cfdeb2d944.png)

string text:

Note: Sync for iOS and Android is still being completed and will be released soon.

(Beta label can be copied from Brave Payments label.)

**Comment by luixxiul** [comment]
There is no beta label above the Sync.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24860657/a5d62d38-1e30-11e7-9160-85846fcced3e.jpg)

**Comment by diracdeltas** [comment]
The mockup is inconsistent with the Brave Payments beta logo.
![screen shot 2017-04-10 at 5 36 58 pm](https://cloud.githubusercontent.com/assets/549654/24874518/79a8ba76-1e14-11e7-9960-2b073e4055ff.png)

**Comment by bradleyrichter** [comment]
doh! my bad...sorry. just copy BP Beta...

**Comment by diracdeltas** [comment]
the payments logo alignment seems wrong. i'll fix that too

**Comment by bradleyrichter** [comment]
@diracdeltas thanks!
