### ISSUE TITLE
add preference option to change default browser to brave!

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#813]
perhaps something like https://support.mozilla.org/en-US/kb/how-change-your-default-browser-windows-10

**Comment by bradleyrichter** [comment]
it's on deck:

![screen shot 2016-02-18 at 2 08 30 pm](https://cloud.githubusercontent.com/assets/13509546/13159884/27bf8384-d649-11e5-9a0d-40383d725b53.png)

**Comment by Fil** [comment]
About the mockup: it's crazy how each browser now gives a "use ME as default browser" button, and not a full menu of open choices. This looks like a trap because it is a trap. I hope Brave can be brave about this and restore user freedoms.

**Comment by bradleyrichter** [comment]
@Fil We would still honor the OS level control panel dialog which has the open list. Would you prefer to only link to that CP from our settings panel?

**Comment by Fil** [comment]
I don't mind if the link is small below the button, but it would make a positive point, yes absolutely.

**Comment by luixxiul** [comment]
This was implemented with #4872
