### ISSUE TITLE
 Allow the user to rearrange context menu items

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8135]
Request from Twitter:

> **Johnny Appleseed‏  @r2d2johnny**
> @brave please allow the user to add to or edit the order of the context menu sooooon! Default is driving me nuts

Source: https://twitter.com/r2d2johnny/status/850840631186309120

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/change-re-order-right-click-context-menu/5672?u=eljuno

>When right-clicking selected text in Brave, the first option is "Search for “your selected text,” the second option is “Copy.”
>
>Is there a way to reverse their order, with Copy being the first option, and “Search for xxx” the second?
