### ISSUE TITLE
Regression: changing default zoom level affects UI

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8144]
**Describe the issue you encountered:**
Regression: changing default zoom level affects UI.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 Preview 1

- Steps to reproduce:
    1. Clear your profile
    2. Open about:preferences
    3. Change default zoom level to 25%
    4. Shutdown and restart the browser
    
- Actual result:
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24837200/4815d576-1d69-11e7-8b0b-858a439a6126.jpg)

- Expected result: UI size should not change

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
This is working as expected in preview 2. Closing issue
