### ISSUE TITLE
Reloading about:preferences returns unrecognized CSP directive 'refererrer'

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8145]
**Describe the issue you encountered:** Reloading about:preferences returns unrecognized CSP directive 'refererrer'. CC: @diracdeltas 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.1 Preview 1

- Steps to reproduce:
    1. Open about:preferences
    2. Open devtool
    3. Reload about:preferences
    
- Actual result: Unrecognized CSP directive 'refererrer'.

- Expected result:

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by diracdeltas** [comment]
i think this is from the coinbase widget so we have no direct control over it. see #7483
