### ISSUE TITLE
Clicking Save Torrent File button does not save .torrent file

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8146]
## Test plan
https://github.com/brave/browser-laptop/pull/8567#issue-225225178
- Visit https://webtorrent.io/free-torrents/
- Click "Big Buck Bunny (torrent file)"
- Click "Save Torrent File..."
- File is saved

## Original issue description
**Describe the issue you encountered:** Clicking Save Torrent File button does not save .torrent file. Instead it displays a prompt to save `webtorrent.html`. Also the CSP error which is same as #8145 is returned on devtool.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 Preview 1

- Steps to reproduce:
    1. Visit https://webtorrent.io/free-torrents/
    2. Click "Big Buck Bunny (torrent file)"
    3. Click "Save Torrent File..."
    
- Actual result: `webtorrent.html` is prompted

- Expected result:  the torrent file should be prompted

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul let's retest with Preview 2 😄  https://github.com/brave/browser-laptop/releases/tag/v0.14.2dev-Preview2

**Comment by luixxiul** [comment]
On Preview 2 still the same error happens.

**Comment by luixxiul** [comment]
The fix does not work on Windows 10 32 bit

**Comment by cezaraugusto** [comment]
doesn't work on Ubuntu. It saves the page instead as described on STR. Reopening

**Comment by cezaraugusto** [comment]
Tested on v0.15.0-RC3

**Comment by alexwykoff** [comment]
Confirmed not working for OS X 0.15.0 RC3 cc @feross

**Comment by NejcZdovc** [comment]
@alexwykoff I was fixing this error, so I can see that some merge conflicts were added, that's why it's not working. Let me do a followup

**Comment by srirambv** [comment]
Works fine on 0.15.0 RC4

**Comment by feross** [comment]
This generally looks good to me, but it would be better to actually add the querystring with `url.parse` and `url.format` since blindly tacking on a `?download=true` can lead to invalid URLs.

A couple examples:

- `magnet:?a=b&c=d?download=true` should use `&download=true` instead
- `https://example.com/file.torrent#ix=1?download=true` should not add a query param after a hash

Will send a PR to fix this.

**Comment by feross** [comment]
PR sent: https://github.com/brave/browser-laptop/pull/8567
