### ISSUE TITLE
torrent file names should be selectable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8148]
**Describe the issue you encountered:** torrent file names on sortableTable should be selectable.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.1 Preview 1

- Steps to reproduce:
    1. Open https://webtorrent.io/free-torrents/
    2. Click any torrent
    3. Start downloading
    
- Actual result: The title and the file names on the table cannot be selected

- Expected result: they should be selectable

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment]
Save file icon is also selectable. 
https://github.com/brave/browser-laptop/pull/8150#issuecomment-296695399

**Comment by luixxiul** [comment]
Please open another issue to track it. thanks.
