### ISSUE TITLE
npm run build-package uses wrong electron URL for brave/electron fork

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#815]
Error[s]: ```Error: GET https://github.com/atom/electron/releases/download/v0.36.7/brave-v0.36.7-darwin-x64.zip returned 404```
```[ [Error: GET https://github.com/atom/electron/releases/download/v0.36.7/brave-v0.36.7-darwin-x64.zip returned 404] ] undefine```

The Proper URL is [https://github.com/brave/electron/releases/download/v0.36.7R3/brave-v0.36.7-darwin-x64.zip](https://github.com/brave/electron/releases/download/v0.36.7R3/brave-v0.36.7-darwin-x64.zip) in the [brave fork](https://github.com/brave/electron).

**Comment by psimyn** [comment]
I think this is the same issue as https://github.com/brave/browser-laptop/issues/773 

Does the same workaround work for `build-package`?

**Comment by weems** [comment]
@psimyn No. Running ``` open /Users/weems/code/electron/Electron.app``` opens up the GUI for Electron from https://github.com/atom/electron. 
I put both path variations ```/Users/weems/code/electron/Electron.app``` and ```/Users/weems/code/electron/electron``` in tests/start.js as suggested: ```execute('/usr/local/bin/electron "' + path.join(__dirname, '..') + '" ' + process.argv[2], env)```.

And the following error still appears for either ```.../electron``` and ```Electron.app``` path[s]:

```Downloading brave-v0.36.7-darwin-x64.zip
Error: GET https://github.com/atom/electron/releases/download/v0.36.7/brave-v0.36.7-darwin-x64.zip returned 404
[ [Error: GET https://github.com/atom/electron/releases/download/v0.36.7/brave-v0.36.7-darwin-x64.zip returned 404] ] undefined
done```.

**Comment by bbondy** [comment]
npm run build-package is only for making packaged builds and not for getting a dev environment setup by the way.

Since it's trying to download from:
 Error: GET https://github.com/atom/electron/releases/download/v0.36.7/brave-v0.36.7-darwin-x64.zip returned 404

I'm confused because this `https://github.com/atom/electron/releases/download/v0.36.7/` shouldn't be used at all with the normal dependencies.

**Comment by weems** [comment]
Then I guess the URL requires modification.

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by bbondy** [comment]
I think this is due to bad env or bad setup. Going to close.
