### ISSUE TITLE
openSUSE repo is misconfigured

### ISSUE THREAD

**Issue by mati865** [brave/browser-laptop#8156]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
```
sudo zypper ref
Permission to access 'https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media' denied.
```
Adding repo or updating with `--force` works. That's because `zypper` expects return code 404 if directory is not found but AWS is configured to return 403.

- Platform (Win7, 8, 10? macOS? Linux distro?):
openSUSE Linux

- Brave Version (revision SHA):
Not related.

- Steps to reproduce:
    1. Follow openSUSE guide
    2. exec `sudo zypper ref`
    3. do step 2 again
    
- Actual result:
`Permission to access 'https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media' denied`

- Expected result:
Successful download.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not related.

- Is this an issue in the currently released version?
Not related.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:

- Screenshot if needed:

- Any related issues:
different project: https://forums.insynchq.com/t/repository-for-opensuse/954/60

**Comment by Liunkae** [comment]
Related: #6946

**Comment by apinter** [comment]
Moving from #6946 
```
Permission to access 'https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media' denied.

Abort, retry, ignore? [a/r/i/...? shows all options] (a): 
```
   
Kinda frustrating. Might just fix this and the GConf2 dep error and put it up on OBS in abin repo if I have the time. 
Maybe you guys want to look into OBS too instead of running the repo on aws. Supports I think every large distro so would save you the hassle I guess.

**Comment by mati865** [comment]
Fixing this one is trivial but it has to be done on AWS.

I'm going to set up unofficial OBS repo when I'll have more time.

**Comment by apinter** [comment]
That would be great. Another option could be using flatpak probably as it is gaining more and more attention and very easy to use.

**Comment by Garbee** [comment]
Flatpak and Snap doesn't work well on OpenSUSE. So that wouldn't really help for this distro. Flatpak stuff is just landing and still pretty early on.

**Comment by cvvs** [comment]
Why wontfix?

**Comment by Garbee** [comment]
The laptop repo is being deprecated. The custom React UX is going away. The core repo is the new mainline which is a Chromium based UX allowing for a faster turn-around time upgrading to new versions and less buggy.

Either this issue is "just resolved" in the infrastructure move to that. Or people using OpenSUSE will figure out it is broken and need to file new issues against the new infrastructure.
