### ISSUE TITLE
 issue-ads bypassing Shields on popsci.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8159]
Report via Community contributor:
https://community.brave.com/t/popsci-com-terrible-on-brave/2154

Needs investigation
Need to reproduce

> _Popsci.com's ads are getting through on Brave. So are unwanted videos. Scrolling is jerky. I have to block both fingerprinting and scripts to get rid of them, and this leaves me unable to navigate through the website. I am using IOS 10.11.6, and Braves's latest update._

Correction: user experienced on OSX El Capitan, not iOS.

**Comment by lukemulks** [comment]
Tested on desktop: 
**Windows10, 64bit**

- Unable to reproduce.
- Ads are blocked as expected. 
- Tracking blocked as expected. 
- No visual on ads. 

Screenshot below: 
![brave-popsci-04092017-desktop-win10](https://cloud.githubusercontent.com/assets/8979240/24843793/ff227832-1d5a-11e7-9972-b8596a29d1e3.PNG)

Original feedback was that iOS was not blocking as expected. 
Confident that desktop shields are working properly 
(will get a confirmation on macOS prior to closing this issue). 

- [ ] Check Android tablet, confirm status.
- [ ] Check Android phone, confirm status. 
- [ ] Check iPad Pro, confirm status.
- [ ] Check iPhone, confirm status. 
- [ ] Check macOSX, confirm status. 

Issue will be routed to the appropriate repository once confirmations above are completed.

**Comment by lukemulks** [comment]
Android Phone (Nexus 5)
Page appears to load fine at first, but if the user lets the page sit, an interstitial is invoked for the following 

redirect URL:
```
http://tu9srvbirvvtosricy5zzxj2aw5nlxn5cy5jb200.g00.popsci.com/g00/2_d3d3LnBvcHNjaS5jb20%3D_/TU9SRVBIRVVTOSRodHRwczovL2JzLnNlcnZpbmctc3lzLmNvbS9TZXJ2aW5nL2FkU2VydmVyLmJzP2NuPWJyZCZQYWdlPSZQbHVJRD0wJlBvcz0yMzMzMDY4MTk2MTU1OTcxOCZFeWVibGFzdGVySUQ9MTA3NDMxOTg4OCZjbGs9MSZzY3Q9MSZkZz0xMDczODM5MTE1JmRnbz0xMDczODM5MTE1JmRpPTAmcGM9JnNlc3Npb25pZD03NDc2ODMzNjMyMDE3MjA3MTgxJnVzZXJjb29raWU9dTI9MmFhMGQ1ZmYtMGM2OC00NWE3LTk0NjItYzkyNDZlN2ZjMTdiJk9wdE91dD0wJm5jdT1odHRwJTNBJTJGJTJGaW5zaWdodC5hZHNydnIub3JnJTJGdHJhY2slMkZjbGslM0ZpbXAlM0RiYzlkMWRiMS00ZjliLTQzMjEtOWZiZi05Nzk4ZDNmODYyNzYlMjZhZyUzRG5vamh2cDAlMjZzZmUlM0RiMjI3NmVhJTI2c2lnJTNEVjVDX2hXd0JxcG95SnFZOEZFT3EtOTBFQmNac1ZfS3JaWEdyWDA1ZjZKOC4lMjZjcmlkJTNEcTkxc3hta3QlMjZjZiUzRDI4NDQ0JTI2ZnElM0QwJTI2dGRfcyUzRHd3dy5wb3BzY2kuY29tJTI2cmNhdHMlM0R5MjklMjZtY2F0JTNEJTI2bXN0ZSUzRCUyNm1mbGQlM0QyJTI2bXNzaSUzRCUyNm1mc2klM0RhdXc3ajh0b2tyJTI2c3YlM0RjYXNhbGUlMjZ1aG93JTNEMjAlMjZhZ3NhJTNEJTI2cmdjbyUzRFVuaXRlZCUyNTIwU3RhdGVzJTI2cmdyZSUzRENhbGlmb3JuaWElMjZyZ21lJTNEODA3JTI2cmdjaSUzRFNhbiUyNTIwSm9zZSUyNnJneiUzRDk1MTQxJTI2ZHQlM0RNb2JpbGUlMjZvc2YlM0RBbmRyb2lkJTI2b3MlM0RPdGhlciUyNmJyJTNEQ2hyb21lJTI2c3ZwaWQlM0QxODM3NTMlMjZybGFuZ3MlM0QwMSUyNm1sYW5nJTNEJTI2ZGlkJTNEMzE3MjAxNzUlMjZyY3h0JTNET3RoZXIlMjZ0bXBjJTNEMTMuMiUyNnZydGQlM0QlMjZvc2klM0QlMjZvc3YlM0QlMjZkYWlkJTNEJTI2ZG5yJTNEMCUyNnZwYiUzRCUyNnN2c2MlM0QlMjZkdXIlM0QlMjZjcnJlbHIlM0QlMjZucHQlM0QlMjZzdnNjaWQlM0QxNzI5OTglMjZyJTNEaHR0cCUzQSUyRiUyRnd3dy5sZy5jb20lMkYmZWJSZWZlcnJlcj1odHRwJTNBJTJGJTJGd3d3LnBvcHNjaS5jb20lMkYmaTEwYy5tYXJrLmlmcmFtZS50eXBl_$/$/$
```
This reeks of IL...

**Comment by lukemulks** [comment]
cc: @Jacalz for visibility. :-)

**Comment by Jacalz** [comment]
Can not see any ads, lets open if problems arise
