### ISSUE TITLE
Update header style on about:preferences pages

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8165]
When reviewing the Extensions page, I noticed that the header style didn't match the other pages:
![prefs-top](https://cloud.githubusercontent.com/assets/4733304/24847007/0f9f0d16-1d73-11e7-933a-328448784608.gif)

The orange style looks great though- we should consider putting this style on the top of each page (possibly with a description of what the page has).  

Here's the page where I noticed the new style (which looks great)
![screen shot 2017-04-09 at 10 21 57 pm](https://cloud.githubusercontent.com/assets/4733304/24847005/0bc387c6-1d73-11e7-8769-e26bff9645c0.png)

cc: @bradleyrichter @cezaraugusto @luixxiul

**Comment by luixxiul** [comment]
IMO creating custom elements as I did for `customForm` would solve the inconsistency issue like this.

**Comment by cezaraugusto** [comment]
@luixxiul mind grabbing this?

**Comment by luixxiul** [comment]
@cezaraugusto no problem, I'm taking it.

**Comment by luixxiul** [comment]
To change the "extensions" header into the orange one, we would at first need to add the same type of header to other tabs such as `about:preferences#search`and `about:preferences#plugins`. Otherwise it would lead additional style inconsistency.
