### ISSUE TITLE
Block automatic video play

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8167]
- Did you search for similar issues before submitting this one?
Didn't find any but sure its a dupe of an existing one

- Describe the issue you encountered:
From community 
>Would love a feature to block embedded video. Often ads and almost always unnecessary.
Maybe not a huge security issue in this example, but definitely improves user experience!

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.14.2 Preview 1

**Comment by luixxiul** [comment]
#2227?

**Comment by srirambv** [comment]
@luixxiul  Thats the one. Thanks. Closing in favor of #2227
