### ISSUE TITLE
Browser doesn't launch on Preview 2 build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8169]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser doesn't launch on Preview 2 build

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.14.2 Preivew 2

- Steps to reproduce:
    1. Install 0.14.2 preivew 2 upgrade/new install
    2. Start from console shows error
    3. Two background process launches, browser window doesn;t load 
    
- Actual result:
Browser doesn't launch on Preview 2 build
- Expected result:
Browser should launch

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![p2launch](https://cloud.githubusercontent.com/assets/17010094/24852362/1caa19cc-1dcf-11e7-96b5-133a5a05b40f.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/1a5b8eccfdbd9b3fd4b8cefebd5296daf2504d02

**Comment by srirambv** [comment]
Closing the issue. Fixed with the new preview 2 build.
