### ISSUE TITLE
401 Unauthorized with websites using .htaccess for authentication

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#817]
From support:

Not sure if this is considered a bug, but when trying to access a site secured using .htaccess on an Apache server you are not presented with a window to enter credentials. The page automatically reverts to a "401 Unauthorized" error.

Here is the link generating the error:  http://www.pcdoctoronline.com/administrator

**Comment by bbondy** [comment]
closing as a dupe of https://github.com/brave/browser-laptop/issues/370
