### ISSUE TITLE
URL bar shape is different with payments enabled/disabled when visiting a site

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8170]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
URL bar shape is different with payments enabled/disabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.14.1 Preivew 1

- Steps to reproduce:
    1. Open a new tab and see the URL bar has rounded corners on all sides
    2. Visit a site in the new tab, the right corners change from rounded to sharp edge
    3. Enable payments and visit  a new site in a new tab
    4. The inclusion of the verified publisher button causes the edge to be rounded but the URL bar inside still has sharp edges
    
- Actual result:
URL bar shape is different with payments enabled/disabled when visiting a site

- Expected result:
Corners should be same irrespective of payments enabled/disabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Mostly need to verify with an older build

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![urlshape](https://cloud.githubusercontent.com/assets/17010094/24853527/4bb80fcc-1dd3-11e7-8103-73e48d4bcef2.gif)

- Any related issues:
cc: @bradleyrichter  @cezaraugusto

**Comment by NejcZdovc** [comment]
@srirambv This is something for me, because I was making changes to URL bar lately in #8059
