### ISSUE TITLE
Delete and Re-enabling extension shows broken image and generic extension name

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8171]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Delete and Re-enabling extension shows broken image and generic extension name

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7
- Steps to reproduce:
    1. Install 0.14.2 preview 2, open extensions tab in preferences
    2. Delete PDFJS extension, re-enable it from advance settings, shows broken image
    3. Enable Pocket and delete it, re-enable from advance settings, shows generic name
    
- Actual result:
Delete and Re-enabling extension shows broken image and generic extension name

- Expected result:
Extension image should be shown and the proper name should be shown

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ext](https://cloud.githubusercontent.com/assets/17010094/24856619/484ce600-1ddd-11e7-8549-8a876abd32a5.gif)

- Any related issues:

**Comment by cezaraugusto** [comment]
removing from 0.14.2, added #8259 to remove that option for now until we can properly react to excluding->reenabling extensions.

adding to 0.14.3 to keep track, feel free to change as needed

**Comment by bsclifton** [comment]
Closing as the delete functionality was reverted
