### ISSUE TITLE
Deleting and re-enabling password managers doesn't show the widget icon in URL bar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8172]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Deleting and re-enabling password managers doesn't show the widget icon in URL bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Enable password managers from extensions page
    2. Delete the password manager in extension page once installed
    3. Re-enable password manager from security, widget icon is missing
    
- Actual result:
Deleting and re-enabling password managers doesn't show the widget icon in URL bar

- Expected result:
Should show the widget after re-enabling the password manager

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24856872/20c06e26-1dde-11e7-8533-f0bc649f48ff.png)

- Any related issues:

**Comment by cezaraugusto** [comment]
removing from 0.14.2, added #8259 to remove that option for now until we can properly react to excluding->reenabling extensions.

adding to 0.14.3 to keep track, feel free to change as needed
