### ISSUE TITLE
Tear off tab - cursor is confusing while tearing off

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8174]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tear off Tab needs better UI

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Open multiple tabs 
    2. Select one tab and tear off
    3. Shows wrong icon when tab is being teared off which might suggest that its not supposed to be done or not possible 
    
- Actual result:
Shows wrong UI when tearing off tab

- Expected result:
Should show normal tab drag UI

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tearoff](https://cloud.githubusercontent.com/assets/17010094/24857201/5c3f5664-1ddf-11e7-8324-ffa110ad5c2d.gif)

- Any related issues:
cc: @bbondy @bradleyrichter

**Comment by luixxiul** [comment]
Should the issue be "Render UI at the same time when the tab is teared off" ?

**Comment by bsclifton** [comment]
@bradleyrichter is the current behavior acceptable for 0.14.2? Or would we want to block on showing a ghost of the window?

I'm going to tentatively assign this to 0.14.3 where we can add more polish.  If we'd like to block on this, please move back to 0.14.2. Thanks 😄

**Comment by bradleyrichter** [comment]
A bird in the hand is better than two in the bush.

Land and refine in 14.3…..

**Comment by bbondy** [comment]
> A bird in the hand is better than two in the bush.

Thank god you followed that up with an explanation 😛
