### ISSUE TITLE
Tearing off tab shows - Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error -

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8175]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tearing off tab shows - Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error -

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Open two tabs, Open dev console
    2. Tear off one of the tabs to make a new window
    3. Console shows error 
    
- Actual result:
Console error when tearing off tabs

- Expected result:
Should not show errors

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tearofferror](https://cloud.githubusercontent.com/assets/17010094/24857432/30e7165e-1de0-11e7-8571-1af16555dd30.gif)

- Any related issues:
cc: @bbondy

**Comment by bbondy** [comment]
Fixed by the 2.57.10 update with this commit
https://github.com/brave/muon/commit/3ce8375382dd18d2963d4385260f244f8d4ea077
