### ISSUE TITLE
Unable to focus on address bar properly

### ISSUE THREAD

**Issue by ChubbyNinja** [brave/browser-laptop#8176]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered:
When clicking on the address bar, if i click the bottom half of it the address cannot be selected or edited, i must click the top half of the allocated space

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7

- Brave Version (revision SHA):

 Name | Version 
 --- | --- 
 Brave | 0.14.1 
 rev | 3de60d5 

- Steps to reproduce:
    1. Go to a website
    2. Hover over address bar and try click the lower half of the white bar
    
- Actual result:
Nothing is selected, and if you double click it toggles full screen/windowed mode

- Expected result:
Select URL

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screencast 2017-04-10 at 11 42 43 am](https://cloud.githubusercontent.com/assets/6347946/24858348/e7cffe32-1de3-11e7-8eea-ca9ae6769781.gif)

- Any related issues:
It feels like there is a transparent part of the UI overlapping the address bar box

This only happens for me when Maximized, when "windowed / restored down" it does not happen.

My screen res is 1920x1200, but also the same issue happens on my other monitor which is  1280x1024 so i think it's a maximized / full screen issue

**Comment by hexigen** [comment]
Hi, I'm here to report same problem. Overall the top navigation bar has this problem - The Search, The new tab button, and the plugin buttons are not clicking from the first try.

Thank you.

**Comment by bsclifton** [comment]
@ChubbyNinja @hexigen do you know offhand what your DPI / scaling is set to? like 100% or 125%?

@hexigen does it only happen when you're maximized?

**Comment by bsclifton** [comment]
I'm going to close this issue in favor of https://github.com/brave/browser-laptop/issues/7641 (which also has reports the same).  Feel free to respond there (or here too).  And thanks BTW for reporting this- I have a hunch where the problem might be 😄

**Comment by hexigen** [comment]
My DPI is 166 also at 100% scaling.
Yes I just tested again it seems to be happening only in maximized mode.
