### ISSUE TITLE
Transifex "release notes" in about:brave

### ISSUE THREAD

**Issue by Zuzu-Typ** [brave/browser-laptop#8177]
- Did you search for similar issues before submitting this one?
no

- Describe the issue you encountered:
In Transifex the string `Click here to view the release notes.` is divided into 3 parts.
`Click`, `here` and `to view the release notes.`.
In German this Sentence would naturally be translated to `Hier klicken, um die Versionshighlights anzuzeigen`,
alternatively it could be translated to `Klicken Sie hier, um die Versionshighlights anzuzeigen`.
Neither of those would work because of the way the string is split.
Thechnically there is a workaround with `Wenn Sie hier klicken, werden die Versionshighlights angezeigt` (`When you klick here, the release notes will be shown`), but I bet this isn't possible in many other languages.

 So my point is, the string shouldn't be split, because oftentimes grammar differs too much between languages for that to work.

- Brave Version (revision SHA):
0.14.2dev Preview 1

- Steps to reproduce:
    1. Go to about:brave
    2. Look at strings 1083, 1084 and 1086 at Transifex

**Comment by luixxiul** [comment]
Hi, I have also noticed the same issue and reported here: #8162. I'm going to close the issue in favor of that, thanks.

**Comment by luixxiul** [comment]
Until the issue will be solved, I would let the strings unlocalized, which I do for Japanese language.
