### ISSUE TITLE
URL bar on new tab displays the URL of the next pinned tab

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8178]
**Describe the issue you encountered:** URL bar on new tab displays the URL of the next pinned tab

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 Preview 2

- Steps to reproduce:
    1. Open a new tab
    2. Click twitter icon on the dashboard
    2. Pin the tab
    3. Open a new tab
    4. Close the 2 tabs with shortcut key
    5. Restart the browser
    
- Actual result: the URL of the pinned tab is filled on the new tab's URL bar

- Expected result: it should be the placeholder

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  ![urlbar](https://cloud.githubusercontent.com/assets/3362943/24861038/3572f77c-1e32-11e7-919d-14c0999b0fb2.gif)

- Any related issues:

**Comment by bbondy** [comment]
I think this is fixed by this change:
https://github.com/brave/browser-laptop/commit/fa7b57ffcd1273b47d55fcd4d0e9cf12a1b69769

This is different steps to reproduce than the commit fixed, but I think the fix is the same. Please re-test with the next preview or master.
