### ISSUE TITLE
downloadItem Animation is Broken

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8179]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The progress bar background does not cover the full downloadItem.

- Platform/Brave Version:
 
Brave|0.14.2
-|- 
rev|10539c2316a1b9a8011aa5fab742957d8a0b509e 
Muon|2.57.8 
libchromiumcontent|57.0.2987.133 
V8|5.7.492.71 
Node.js|7.4.0 
Update Channel|dev 
os.platform|win32 
os.release|10.0.15063 
os.arch|x64

- Steps to reproduce:
    1. Download a file
    2. Note issues with downloadItem presentation
    
- Actual result:
Progress-bar background only partially fills the element.

- Expected result:
Progress-bar background should fill the full element.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/815158/24862494/6c681f2a-1dc2-11e7-9c8c-7dd9832c9aa1.png)

- Any related issues:

**Comment by NejcZdovc** [comment]
@jonathansampson I would push this into 0.14.2, because we can't ship it like this in my opinion. What do you think?
