### ISSUE TITLE
Crash reporting disabled message shown on Windows when launching from console

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8183]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Crash reporting disabled message on Windows when launching from console

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Install/upgrade to 0.14.2 preview 2 
    2. Launch brave from git console
    3. Shows `Crash reporting disabled` messsage 
    
- Actual result:
Crash reporting disabled message on Windows when launching from console
- Expected result:
Crash reporting should be enabled and shown when launching from console
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24866326/b51b41fe-1e01-11e7-847f-3c4c4c58e589.png)

- Any related issues:
#7917 cc: @bsclifton

**Comment by aekeus** [comment]
This is controlled via a preference option that should default to enabled. Is this from a clean profile?

**Comment by aekeus** [comment]
This is operating correctly on Windows. The toggle is enabling and disabling the crash reporting on startup.
<img width="914" alt="screen shot 2017-04-11 at 11 23 51 am" src="https://cloud.githubusercontent.com/assets/210240/24916891/7aafeb7a-1ea9-11e7-9eaa-43aab3ee66f8.png">
