### ISSUE TITLE
Badge designs are inconsistent

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8185]
## Test plan
1. Set LastPass as your active password manager in Preferences > Security
2. Add a login/password for GitHub
3. Go to https://github.com/login and the LastPass icon with badge should show in the top right corner
4. Confirm it matches this new spec (consistent with Lion):
![image](https://cloud.githubusercontent.com/assets/815158/24871528/79c05904-1ddf-11e7-827a-15e97e2313d6.png)

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Badge designs are not consistent. Proposed solution is to adopt the Lion badge style for extensions.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/815158/24867017/89347572-1dd1-11e7-8c3d-7cd8a495b619.png)

**Comment by bsclifton** [comment]
marked as `release-notes/exclude` since the badge was added with this release (wasn't in prior releases)
