### ISSUE TITLE
Badge count animation between lion head and password manager needs to synchronize

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8186]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Badge count animation between lion head and password manager needs to synchronize

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Enable LastPass with a stored credentials
    2. Visit the site for which the credentials is saved
    3. Hover over the next tab, LastPass badge is hidden, lion head badge still retained
    4. Switch back to the tab for which LastPass badge count is still not shown but lion head badge shows the badge
    5. Switch to the new tab, LastPass badge is still shown, lion head badge is hidden
- Actual result:
Badge count animation between lion head and password manager needs to synchronize
- Expected result:
Badge count should be shown properly on tabs
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![badgecount](https://cloud.githubusercontent.com/assets/17010094/24867124/2562d59c-1e04-11e7-900c-96f9619269e5.gif)

- Any related issues:

**Comment by cezaraugusto** [comment]
@srirambv could you describe more fully what's the expected result here?

**Comment by cezaraugusto** [comment]
we could have an animation to smooth transitions but not sure if that's what you mean

**Comment by srirambv** [comment]
@cezaraugusto Yes there is no smooth transition in the counts. The badge count on lion head appears first and then for LastPass. Also when tab switches Lastpass retains badge and Lion head doesn't retain. On hover LastPass badge is lost but Lion head retians the badge

**Comment by cezaraugusto** [comment]
after a while animating badges I started to like them as-is if a subtle transition is included:

![badge_animation_delay](https://cloud.githubusercontent.com/assets/4672033/26365483/28d59134-3fbe-11e7-8d13-437e0b86dc6e.gif)

cc @srirambv @bradleyrichter what you both think?

**Comment by luixxiul** [comment]
CC @bradleyrichter for design review

**Comment by srirambv** [comment]
Fade in effect on LastPass is a little slower compared to Honey. But much better than the initial transition 👍 
![8186_1](https://user-images.githubusercontent.com/17010094/27348029-9b438946-55ea-11e7-8d21-cd78c219775f.gif)
