### ISSUE TITLE
Don't change src for bookmarklets so they can be used multiple times

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#819]
I think the src of the iframe shouldn't actually change for bookmarklets and we should instead route to webview.loadURL.

@diracdeltas thoughts?

Currently the src prop changes and you can only execute a bookmarklet once.

**Comment by bbondy** [comment]
window.location should also not change after a bookmarklet is executed

**Comment by diracdeltas** [comment]
I was just about to point this out. Agree that the src shouldn't change.

**Comment by riledhel** [comment]
Tab title also changes after bookmarklet click
