### ISSUE TITLE
Invisible pinned tab after upgrade

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#8190]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Pinned tabs 
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
0.14.2 Preview 2
- Steps to reproduce:
    1. Pin 4 tabs in 0.14.1
    2. Quit Brave
    3. Launch 0.14.2 preview 2
    
- Actual result:
We can only see one pined tab
- Expected result:
There should be 4 visible pinned tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

[Kapture 2017-04-10 at 8.37.40.mp4.zip](https://github.com/brave/browser-laptop/files/910590/Kapture.2017-04-10.at.8.37.40.mp4.zip)

- Any related issues:

**Comment by bsclifton** [comment]
++ on this; I can re-add items back, but after quitting and re-launching Brave, all but one of the pinned tabs are removed

**Comment by bsclifton** [comment]
They site entries still have the appropriate tags (ex: `"tags": ["pinned"],`), but just aren't being displayed
