### ISSUE TITLE
 issue investigate ads displaying on forums.gardenweb (desktop and mobile)

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8193]
Report from Twitter of ads showing up on forums.gardenweb.com
- [ ] needs investigation on desktop and mobile
- [ ] confirm if ads are native 3rd party or 1st party native
- [ ] reported from iOS, but should investigate desktop and Android as there is a good chance of countermeasures being applied globally. 

Link to original tweet reporting the issue: https://twitter.com/SlexAxton/status/851464609139707905

This is just a stub - more info will be added as the issue is investigated

**Comment by Jacalz** [comment]
I see this ad:
![image](https://cloud.githubusercontent.com/assets/25466657/26818566/6f8ada3e-4a9b-11e7-9e9e-58e947ad2a13.png)
It seems to be loaded form these scripts:
![image](https://cloud.githubusercontent.com/assets/25466657/26818588/87473db6-4a9b-11e7-9222-fd765dccc641.png)

**Comment by Jacalz** [comment]
Here is the div it is loaded from:
![image](https://cloud.githubusercontent.com/assets/25466657/26818769/4ebafdd8-4a9c-11e7-8346-0ec9e3ea84d1.png)

**Comment by Jacalz** [comment]
Can not see any ads on desktop nor on mobile
