### ISSUE TITLE
Wallet creation fails 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8195]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Wallet creation fails 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All, @bsclifton confirmed on macOS

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Launch brave from console
    2. Enable payments
    3. Wallet creation fails, console shows error 
    
- Actual result:
Wallet creation fails 
- Expected result:
Wallet should be created
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24873081/813c10be-1e17-11e7-958d-b440a29066a1.png)

- Any related issues:
#7992

**Comment by bbondy** [comment]
Fix is here:
https://github.com/brave/muon/pull/182

If accepted, we'll need new muon builds.
