### ISSUE TITLE
Empty bookmark folder doesn't show overflow indicator in bookmarks menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8196]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Empty bookmark folder doesn't show overflow indicator in bookmarks menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7

- Steps to reproduce:
    1. Create two bookmark folder, folder1, folder2
    2. Visit a site and add it as bookmark under folder1
    3. View bookmarks from menu, folder1 has overflow indicator, folder2 doesn't have overflow indicator
    
- Actual result:
Empty bookmark folder doesn't show overflow indicator in bookmarks menu

- Expected result:
Should show the overflow indicator even for empty bookmarks folder
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![emptyfolder](https://cloud.githubusercontent.com/assets/17010094/24874486/bd978674-1e1c-11e7-8494-2fc5f91356dd.gif)

- Any related issues:

**Comment by bsclifton** [comment]
This has been a problem since menus were implemented with custom titlebar (0.12.3). Removing milestone
