### ISSUE TITLE
Sort indicator is not shown next to the table heading in about:preferences#extensions

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8197]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sort indicator is not shown next to the table heading in about:preferences#extensions
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
Brave	0.14.2
rev	61ae1a7
- Steps to reproduce:
    1. Open about:preferences#extension
    2. Click on the table heading to sort the list
    3. Sort indicator is shown below the text which looks awkward 
    
- Actual result:
Sort indicator is not shown next to the table heading in about:preferences#extensions
- Expected result:
Should show the sort indicator next to the table heading
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/24874984/6bace97e-1e1e-11e7-8960-f0db12200982.png)

- Any related issues:
cc: @cezaraugusto

**Comment by jonathansampson** [comment]
@cezaraugusto Just got back to a computer; I'll take it! :)
