### ISSUE TITLE
Going back 2 spots in history and then forward won't work for the second forward

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#82]
This is probably an electron level fix.

**Comment by serv** [comment]
Can you still repro this bug? I don't think I can repro this. Maybe my repro steps are wrong. Can you review if this is the right repro steps?

1. Went to reddit.com
2. Click on random link.
3. Click on another random link.
4. Click back
5. Click back
6. Click forward. Works
7. Click forward. Works

**Comment by obvio171** [comment]
Also tried to reproduce it but couldn't.

**Comment by bbondy** [comment]
I think this got fixed at some point, not sure when. Closing.
