### ISSUE TITLE
Add common menu for extensionsTab page

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8202]
<img width="458" alt="screen shot 2017-04-10 at 3 07 57 pm" src="https://cloud.githubusercontent.com/assets/4672033/24876097/cc389bbc-1e00-11e7-9640-786b1d2bd7c9.png">

Should also include "extensions" on that list and point to preferences#extensions.

/cc @bradleyrichter

**Comment by NejcZdovc** [comment]
Closing as a dupe of #8203
