### ISSUE TITLE
Remove deprecated react-addons-test-utils from Enzyme

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8206]
Enzyme uses `react-addons-test-utils` who is now deprecated per https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html.

Test utils was moved from `react-addons-test-utils` to `react-dom/test-utils`. Warning message is shown on console while running unit tests:

<img width="857" alt="screen shot 2017-04-10 at 4 19 07 pm" src="https://cloud.githubusercontent.com/assets/4672033/24878424/740e1c10-1e09-11e7-9497-34f6ff5dfe8e.png">

Needs resolution of https://github.com/airbnb/enzyme/issues/875

**Comment by cezaraugusto** [comment]
solved by 84f610ba7f94e064c90a5e1b20f927d071a7f992

**Comment by bsclifton** [comment]
great, thanks @cezaraugusto! 😄
