### ISSUE TITLE
Allow the blocking of arbitrary divs

### ISSUE THREAD

**Issue by SwartzCr** [brave/browser-laptop#8210]
This relates to #6296 where uBlock Origin support is requested, and rebuffed with the suggestion to request specific functionality.
One thing that uBlock does is that it allows the blocking of arbitrary divs on a website, I use this to do things like remove the moments tab from twitter or the public wall from facebook. Brave lacks this functionality, and should implement it if you don't want to support uBlock integration

**Comment by Liunkae** [comment]
@SwartzCr Is this what you want: #7521 (Provide right click context menu option for users to block 1st party Ads)

**Comment by SwartzCr** [comment]
Yes, I think that would suit my purpose

**Comment by Liunkae** [comment]
That feature (#7521) and the custom filters functionality in about:adblock should cover it. Closing.
