### ISSUE TITLE
Brave fails to block promoted tweets

### ISSUE THREAD

**Issue by SwartzCr** [brave/browser-laptop#8211]
This related to #6296
uBlock manages to hide promoted tweets from the twitter stream, Brave does not. It'd be nice if this could be implemented

**Comment by Liunkae** [comment]
@SwartzCr Thanks! Blocking native ads (including promoted tweets) is being tracked in #527. It does not have a milestone yet, but you can subscribe to the issue for any further updates. Closing this one as a duplicate.
