### ISSUE TITLE
Twitter causes brave to become inactive

### ISSUE THREAD

**Issue by SwartzCr** [brave/browser-laptop#8212]
- Did you search for similar issues before submitting this one?
yes - #8004 is not exactly the same, but the closest I could find
- Describe the issue you encountered:
When loading my twitter timeline, after a short amount of time the tab becomes unresponsive. I cannot scroll (either with pgup or pgdown, or with the scrollbar) and ctrl+w won't close the tab. Manually clicking the x in the tab does close it. This repeatedly happens within 30 seconds of opening a twitter tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux
- Brave Version (revision SHA):
0.14.1 3de60d5
- Steps to reproduce:
    1. Go to twitter while logged in
    2. scroll down
    3. observe unresponsiveness
    
- Actual result:
I can no longer interact with the tab
- Expected result:
I should be able to continue to scroll through my timeline
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
It seems to only happen when a video is loading - the video fails to load and then the tab promptly becomes unresponsive

**Comment by jonathansampson** [comment]
Have you noticed these types of delays in previous versions of Brave? Do you notice them on any other sites besides Twitter?

**Comment by SwartzCr** [comment]
I am recent to brave - so I have not noticed it on other versions. Also Twitter is the only site I've seen this on (though plausibly it might happen with facebook video?)
Brave now is refusing to start on my computer so I can't helpfully do more debugging

**Comment by jonathansampson** [comment]
@SwartzCr Oh no; refusing to start? Do you get a white window, or does nothing at all appear?

If you see a white window, you can try press Shift+F8. This will open up an instance of developer tools on the Brave application itself. There may be some helpful information in the Console (please share).

If you don't see anything at all, I'd check for an orphan process that needs to be terminated before another can operate in its place. This happens with apps on Windows (taking a wild guess that it can happen on Linux too).
