### ISSUE TITLE
Autocomplete no longer suggests the shortest match

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8219]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Autocomplete no longer suggests the shortest match. For example, see this image which should be suggesting amazon.com with autocomplete (instead of defaulting to a longer URL)
![image](https://cloud.githubusercontent.com/assets/4733304/24888549/1bf2e816-1e19-11e7-9970-44e51af2d883.png)

This is working as expected in 0.14.1

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

cc: @aekeus

**Comment by aekeus** [comment]
This is operating correctly. The amazon.com entry is shown in top sites. The duplicate virtual history item was removed.

**Comment by bsclifton** [comment]
@aekeus it does show in top sites, but why is `amazon.com` not put into the URL bar? (versus the rest of the URL)

Here's a demo on my box with github:
![autocomplete](https://cloud.githubusercontent.com/assets/4733304/24895255/3eedd90e-1e44-11e7-98d6-566f06a2f812.gif)

**Comment by aekeus** [comment]
In the example above with github, the deep linked pages have been accessed both more frequently and most recently than the base domain.

In Brad's example, he has not access amazon.com directly, so that entries is not in his history. We create a virtual history item (amazon.com) and insert it into the suggestions. It is being de-duplicated out because amazon.com is a top site.

**Comment by bsclifton** [comment]
@aekeus ah ok- thanks for the clarification 😄   Very nice!
