### ISSUE TITLE
about:preferences is not functional when accessing it from about:about. (0.7.14)

### ISSUE THREAD

**Issue by wizgothic** [brave/browser-laptop#822]
Similar to #666. Works properly when it is accessed from the url bar. The page loads, yet the checkboxes are broken. 
Perhaps I should also link this:
![Well](http://i.imgur.com/hBweLCh.png)
Occured just once. 
Off-topic: mailto:name@domain.com, about:config are not working as well. Tested on multiple devices.

**Comment by weems** [comment]
you cannot recreate?

**Comment by wizgothic** [comment]
Oh, my bad- when I have said "once" I was referring to the uncaught exception. 
http://recordit.co/vlVpkIHBJf

**Comment by luixxiul** [comment]
Closing for now. Please leave a comment if you still encounter this error to reopen the issue, thanks.
