### ISSUE TITLE
Some way to clear previous downloaded files easily

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#8221]
- Did you search for similar issues before submitting this one?
 Yes
- Describe the issue you encountered:
 The downloaded files do not reset in the downloads bar even after closing the bar

- Platform (Win7, 8, 10? macOS? Linux distro?):
 Windows 10
- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/61ae1a70cf2c4e592b76500a9c9fd8278bc60905
- Steps to reproduce:
    1. Download some files (or previously downloaded ones)
    2. When you go to download again, the previous downloads still appear
    3.  Could there be a way to clear the download history?
    
- Actual result:
 I have https://puu.sh/vgmPX/9494cd8c1d.png many downloads always there
- Expected result:
 When I click the "x", or some other button to have the previous files downloaded not show up 
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
 Yes
- Can this issue be consistently reproduced?

- Extra QA steps:
    1. Download some files
    2. Press the X at the end of the bar
    3. Go to download another file
    4. The previous ones will still show up

- Screenshot if needed:
 https://puu.sh/vgmPX/9494cd8c1d.png
- Any related issues:
 Not that I can find

**Comment by jonathansampson** [comment]
You can right-click on the downloads bar, and select "_Clear completed downloads."

Does that help?

**Comment by hunterhacker** [comment]
What you actually do:

- Try everything you can think of
- Google around for an answer
- Find this page

Just saying, it's not the most intuitive.

**Comment by bsclifton** [comment]
I think this could definitely be more intuitive. Re-opening so we can comment

cc: @bradleyrichter @jenn-rhim @alexwykoff
