### ISSUE TITLE
Onion sites

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#8224]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Not able to visit .onion addresses when using Tor.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Connect to Tor
    2. Go to .onion site
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
did you try commenting out entries in /etc/resolv.conf to prevent the browser from using regular DNS servers?

**Comment by diracdeltas** [comment]
WIP tor tabs implementation now supports onion sites

**Comment by riastradh-brave** [comment]
We should either (a) block attempts to load .onion sites in tabs without Tor enabled, or (b) automatically transplant such requests to private tabs with Tor enabled so that Tor can handle them.

We should definitely _not_ leak to your DNS server which onion services you're trying to use.

**Comment by riastradh-brave** [comment]
As soon as the Tor branches are merged (https://github.com/brave/muon/pull/473, https://github.com/brave/browser-laptop/pull/14143), navigating to .onion sites will be supported in private tabs with Tor enabled.

Separate issue for how to deal with .onion sites in tabs without Tor enabled: https://github.com/brave/browser-laptop/issues/14431
