### ISSUE TITLE
allow changing of input language independent of browser language, option to disable spell check

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#8226]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
inputting in text fields uses uses spellcheck in the browser language, right clicking inside the text field does not allow disabling the spell check or changing the language as is possible in chrome or ff
- Platform (Win7, 8, 10? macOS? Linux distro?):
macos
- Brave Version (revision SHA):
Brave	0.14.1
rev	1a5b8ec
- Steps to reproduce:
    1. open brave and go eg. inbox.google.com and start writing an email
    2. write wrong words or words in different language as is browser language
    3. you see red underlines 
    4. right click inside text box
   
    
- Actual result:
 5. no options to disable spell check or changing language are visible
- Expected result:
spell check language selection and option to disabling spell check
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by Liunkae** [comment]
#2183 covers changing the spellcheck language.
#7898 covers disabling spellcheck.
Closing as a duplicate.

**Comment by lucidNTR** [comment]
ups sorry @Liunkae no idea why i didn't find the existing tickets...

**Comment by luixxiul** [comment]
> why i didn't find the existing tickets

Because github search filter is so poor, which is not your fault.
