### ISSUE TITLE
remove old extensions settings area from Advanced prefs panel

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8230]
remove all of this because it is now redundant and probably confusing:

![image](https://cloud.githubusercontent.com/assets/13509546/24917379/d7bdbecc-1e91-11e7-92c7-90eb3eeed1db.png)

**Comment by cezaraugusto** [comment]
should we consider something related for password managers?

**Comment by bradleyrichter** [comment]
@cezaraugusto yes!

#8253
