### ISSUE TITLE
Add the ability to add custom search engines

### ISSUE THREAD

**Issue by 0x20c24** [brave/browser-laptop#824]
Hi!

I would like to suggest that a searx instance could be in the search engine list.
e.g:
https://searx.me/
https://searx.laquadrature.net/
https://search.blackit.de/
etc.

https://github.com/asciimoo/searx

Regards,
Peter

**Comment by luixxiul** [comment]
See #790

**Comment by bbondy** [comment]
Closing as a dupe.

**Comment by DeviatedMind** [comment]
#790 #824 #3053 #3294 #4210

**Comment by iMartyn** [comment]
@bbondy This is not a dupe.  All the other bugs are "pls to add my favorite search engine".  This specifically asks to allow adding custom search engines.  E.g. company confluence or jira or other knowledge bases have search functions, I don't want everyone to have them but I want to be able to add them as options in brave.

**Comment by bsclifton** [comment]
@iMartyn this is a dupe very specifically of https://github.com/brave/browser-laptop/issues/3053 (Allow user to add and edit custom search engines)

However, if you grab the newest version of brave at https://brave.com/download, you'll notice you can visit your favorite search and it'll be auto-discovered. You can then navigate to brave://settings/searchEngines and make anything your new default. You can also remove all of the pre-loaded ones and manage other auto-discovered engines
