### ISSUE TITLE
Leak in app state change listener in frame

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8244]
If you open 12 tabs without closing there's a warning in the window console dev tools about a possible leak (Shift+F8).  This isn't a leak and is ok.

If you open and close 12 tabs in a row, open, close, open, close .... there is the same leak message.
This is actually a leak and should be fixed.

**Comment by srirambv** [comment]
Still see this error message on Win x64 clean install. 
![image](https://cloud.githubusercontent.com/assets/17010094/25332117/4fa218ca-28dd-11e7-9109-585ef4d7e334.png)
![image](https://cloud.githubusercontent.com/assets/17010094/25332198/7fef6640-28dd-11e7-9adc-7c50c05e1c90.png)

**Comment by luixxiul** [comment]
Are you sure that you did follow the 2nd one? ie.

> If you open and close 12 tabs in a row, open, close, open, close .... there is the same leak message.
This is actually a leak and should be fixed.

**Comment by srirambv** [comment]
Will retest once more and confirm
