### ISSUE TITLE
Tab title is not shown on mouse hover after relaunching browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8247]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab title is not shown on mouse hover after relaunching browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Install 0.14.0 P3 or upgrade from existing build
    2. Open a bunch of tabs and visit site in them
    3. Close and reopen the browser
    4.Hover over other inactive tabs, page reloads, indicator is shown but tab title is missing only favicon is shown
    5. Rehover over the tabs and the page title is shown 
- Actual result:
Tab title is not shown on mouse hover after relaunching browser
- Expected result:
Should show tab title and reload properly
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tabtitle2](https://cloud.githubusercontent.com/assets/17010094/24962946/3963640c-1f95-11e7-883a-c851c65b09e7.gif)

- Any related issues:
Please move it to 0.14.3 if required

**Comment by bsclifton** [comment]
Seems to work as expected on macOS with Preview 3... Will try Windows here shortly

**Comment by bsclifton** [comment]
Works as expected on Windows with Preview 3. Just to make sure, I cleared my profile and tried again- it still works great.  Closing issue and removing milestone. Please re-open / assign milestone if there are more specific STR. Thanks 😄
