### ISSUE TITLE
Change password manager prefs UI to simple slider for Brave passwords

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8253]
Now that we have an extensions manager, we no longer need to pre-list password managers in the password section of the privacy prefs panel. 

This will allow users to combine multiple managers if desired, however complex that may be. It's up to them. (rather than limiting it to one manager at a time)

![image](https://cloud.githubusercontent.com/assets/13509546/24967403/d2e83896-1f5e-11e7-9857-6ebc2a37ebfb.png)

cc @cezaraugusto

**Comment by bsclifton** [comment]
I think this is too big for 0.14.2- moving to 0.14.3

**Comment by rebron** [comment]
Closing wontfix. Tracking overal pref changes in brave-core https://github.com/brave/brave-browser/issues/955
