### ISSUE TITLE
Provide option to mute tabs by default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8254]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Provide option to mute tabs by default 
Also suggested from community https://community.brave.com/t/mute-tab-on-any-tab/2205

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Latest

- Screenshot if needed:
Chrome
![image](https://cloud.githubusercontent.com/assets/17010094/24968197/6dc13f76-1fa4-11e7-8b0b-cb8f792c8bd0.png)
FireFox
![image](https://cloud.githubusercontent.com/assets/17010094/24968230/88e33214-1fa4-11e7-9a52-72776fba18b8.png)

- Any related issues:
Please change milestone if required
cc: @bradleyrichter @bsclifton

**Comment by Miyayes** [comment]
+1 from community here: https://www.reddit.com/r/BATProject/comments/7ug72z/how_can_i_mute_a_tab/

Seems quick and easy to implement (since the functionality is already there but simply conditional upon audio already playing).
