### ISSUE TITLE
Source Maps in Releases

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8255]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Releases of Brave have developer resources that aren't useful to users, and take up a great amount of space. These should be removed, and only generated when the user is developing Brave locally.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/f07c1421b982ef66e4cd369e8d928a3f9b19ffd5

- Steps to reproduce:
    1. Navigate to `%appdata%/../local/brave`
    2. Search all nested directories for `*.map`
    3. Note more than 10MB of results
    
- Actual result:
Brave ships development resources to end-users

- Expected result:
Brave is lean, and ships only that which is needed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/815158/24968101/c123e854-1f71-11e7-9582-a6551237b20e.png)

**Comment by bsclifton** [comment]
Moving to backlog.  This is a good change but needs some more research before we pull it in
