### ISSUE TITLE
Add OneTab Extension Support

### ISSUE THREAD

**Issue by philkloose** [brave/browser-laptop#8261]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
I added the extension but the OneTab icon in the toolbar doesn't register clicks -- button is completely dead.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7
- Brave Version (revision SHA):
 
Brave: 0.14.1 
rev: 387738af1cfe3c9c961c42a9ab49269ad87bb182 
Muon: 2.57.8 
libchromiumcontent: 57.0.2987.133 
V8: 5.7.492.71 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.1.7601 
os.arch: x64

- Steps to reproduce:
    1. Added OneTab using instructions outlined here -- https://blog.brave.com/loading-chrome-extensions-in-brave/
    2. Icon shows up next to the Brave icon in topmost toolbar.
    3. OneTab icon does not register any clicks at all.
    
- Actual result: Extension doesn't work because it doesn't register any mouse clicks.

- Expected result: Extension would work.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by jonathansampson** [comment]
Closing in favor of #9828
