### ISSUE TITLE
increase the tabs bar by another 2 px based on increased user feedback

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8263]
## Test plan
( should be tested on macOS, Linux, and Windows)
1. Ensure themed tab option is turned on
2. Visit some sites which have various coloring for tabs
- github.com
- facebook.com
- about:preferences
3. Make sure the tab looks good (text is readable, etc)
4. Ensure drag and drop still works good for moving tabs around
5. Ensure other features still look good; for example, bookmarks toolbar

## Original issue description
Honestly, we have been increasing the tabs bar height by about 2 pixels every month or so, trying to keep the chrome footprint to a minimum stack height. 

I believe higher-res laptops are creating taller toolbar requirements today than what was desired only a few years back. 

Well, users want more tab height for usability. So, here you are users - another 2px. Enjoy.  ;  )

**Comment by luixxiul** [comment]
The fix will be like this, reserving the 7px margin between the top edge and the URL bar:

![tab](https://cloud.githubusercontent.com/assets/3362943/25012223/cbdb04fa-20aa-11e7-92db-fc4b1428304d.gif)
