### ISSUE TITLE
Update text for new privateTab

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8267]
@bradleyrichter suggested that:

> Private tabs are not logged in page history or counted in Brave Payments calculations. Cookies from a private tab will vanish when the browser is closed, together will all your private tabs.
>
> File downloads, new bookmarks, and passwords can still be saved while using a private tab and will not be removed when the private tab is closed.
> 
> _Please note: Even though sites you visit in private tabs are not saved locally, they do not make you anonymous or invisible to your ISP, your employer, or to the sites you are visiting._

**Comment by luixxiul** [comment]
It will require another merge from Transifex before 0.14.2 is released.
