### ISSUE TITLE
Avoid having undefined props on tab audio indicator

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8270]
Some props on audio indicator (AudioTabIcon component) are `undefined` at some points possibly leading to unexpected behavior when the tab is idle (see #8249).

* We should coerce all truthy/falsy values to boolean;
* Since spec for tabs are now well defined, we should add a new breakpoint value for icon to be visible (it currently shows only when no breakpoint matches).

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/8273
