### ISSUE TITLE
Videos Blocked on CNBC.com

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-laptop#828]
When ad blocking is on, videos will not play.  When ad blocking is turned off, the videos will play fine.

Example (see video 1/2 way down page)
http://www.cnbc.com/2016/02/19/philadelphias-57-billion-quiet-crisis.html

More people writing into support about other websites with the same issue.  CNN.com and CNET.com as well.

**Comment by Codes4Fun** [comment]
I could reproduce this issue with FireFox and AdBlock Plus, if I whitelist this single file:
http://adm.fwmrm.net/p/nbcu_live_jsam/AdManager.js

I am able to watch the video without advertisement. I am not sure how you could whitelist the file in Brave though.

**Comment by bbondy** [comment]
Fixed: https://github.com/bbondy/abp-filter-parser-cpp/commit/d95b52db3969c05ccea2e5d36f1ed9c86b539f31
