### ISSUE TITLE
Autofill should automatically move cursor to first entry when adding a new record

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8280]
## Test Plan:
1. Open browser and type about:autofill
2. Click on Add Address or Add Credit Card
2. Cursor will focus on first input field

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When adding a record, I found that I had to click in the modal first to edit values.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.2 (f07c142)

- Steps to reproduce:
    1.  visit about:autofill
    2. add a record
    3.
    
- Actual result:
The cursor is not in any available field

- Expected result:
The cursor should move to the first field and save the user a click

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by kumarrishav** [comment]
I will be happy to take this bug. This will be my first contribution to brave. Currently i am setting up the env and building brave from source. It will be great to have some pointer to start with.
