### ISSUE TITLE
Lock npm versions

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8283]
**Describe the issue you encountered:**
Lock all npm packages to the specific version, so that we are all working on the same dependencies. 

In this issue I am **NOT** updating anything to the mayor version, just settings values that we get now if we run `npm i`

We should update all dependencies with every release.
cc @bbondy @alexwykoff @bsclifton

**Comment by luixxiul** [comment]
> We should update all dependencies with every release.

Let's consider using greenkeeper #1701

**Comment by NejcZdovc** [comment]
@luixxiul I like it, let me try it out

**Comment by bsclifton** [comment]
an Alternative we can consider too: shrinkwrap

@diracdeltas put together this PR which I didn't feel comfortable accepting because I'm unfamiliar with shrinkwrap / am not sure how the update process would look like:
https://github.com/brave/browser-laptop/pull/7795

**Comment by NejcZdovc** [comment]
@bsclifton personally I prefer automated things, so this greenkeeper will force us to be up to date :smiley:

**Comment by alexwykoff** [comment]
Greenkeeper will only make sense after we have a consistently passing CI otherwise things will 'magically break' and you will be hunting for a long time to figure out why.

**Comment by diracdeltas** [comment]
I think we should lock NPM versions, but I don't think we should be updating the lock to the latest version of every package with every commit/PR. We tried doing that for brave/sync (which has far fewer dependencies) and it soon became difficult to track down what bugs were due to a dependency update. 

It might be ok updating the lockfile once per release, as long as there is enough time for testers to catch bugs that are due to dependency updates.

If we lock down versions with shrinkwrap or Yarn, I can re-enable Travis dependency caching.

**Comment by luixxiul** [comment]
> It might be ok updating the lockfile once per release, as long as there is enough time for testers to catch bugs that are due to dependency updates.

I'm thinking about the possibility of updating packages based on the release channels.

eg
- Nightly/Alpha -> `major.minor.maintenance`
- Beta -> `minor.maintenance`
- Release -> only `.maintenance`

It could only cause chaos, though. Just my idea.

**Comment by luixxiul** [comment]
otherwise we could update deprecated packages at least.

**Comment by bsclifton** [comment]
@NejcZdovc what do you think about accepting https://github.com/brave/browser-laptop/pull/7795 in lieu of this PR?

**Comment by NejcZdovc** [comment]
@bsclifton @diracdeltas correct me if I am wrong, but doesn't this only apply when travis or our build pipe is using npm. When I as developer clone `browser-laptop` and run `npm i` shrinkwrap is not used and we will have different versions of packages. I think that we need to use both PR's. My is meant for developers, so that we have all exactly the same versions and shrinkwrap is needed for travis. If I misunderstood shrinkwrap and when you run `npm i` shrinkwrap will be used and not `package.json` then my PR is not needed.

cc @bbondy

**Comment by diracdeltas** [comment]
@NejcZdovc my understanding based on https://docs.npmjs.com/cli/shrinkwrap is that shrinkwrap is used for npm install.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/pull/7795

**Comment by bsclifton** [comment]
@diracdeltas that is correct- `npm install` will respect shrinkwrap 😄

**Comment by luixxiul** [comment]
On the latest `npm`, the file `package-lock.json` is produced after `npm i`. Should we add the file to `.gitignore`?

**Comment by NejcZdovc** [comment]
We can for now, but as soon travis supports npm 5 we will use it for caching

**Comment by bbondy** [comment]
Re-opening for npm5

**Comment by luixxiul** [comment]
Updating npm to the current stable version, you get npm5 and `package-lock.json`. Should we add it to `.gitignore` temporarily since #9691 was closed?

**Comment by bsclifton** [comment]
We've been using the lock files and these have worked out great 😄 👍
