### ISSUE TITLE
Re-attaching the tab is not easiest thing to do

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8289]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Re-attaching the tab is not easiest thing to do

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.2
rev	f07c142

- Steps to reproduce:
    1. Have a pin tab in the browser window and open multiple tabs
    2. Tear off one of the tab to create a new window
    3. Try to reattach the tab back into the original window by dragging it on to the tabs bar, need to give it couple of tries before it gets re-attached to the main window but ends up creating lot of tear off windows in the process
    
- Actual result:
Difficult to reattach the teared off tab

- Expected result:
Should be simple enough to reattach the tab to the main window

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![attach-detach 1](https://cloud.githubusercontent.com/assets/17010094/25002929/dc5fe252-2044-11e7-9475-94f011c73367.gif)

- Any related issues: #8288 #6863
cc: @bbondy

**Comment by luixxiul** [comment]
Does this not block 0.14.3? For me this seems to be a quite annoying issue.

**Comment by srirambv** [comment]
Sorry meant to add release blocking. It is actually very annoying because tabs can tear off pretty easily if the tab drag is not properly handled.

**Comment by luixxiul** [comment]
I think the issue has been fixed and can be closed.

**Comment by bsclifton** [comment]
@srirambv as the original opener of the issue, can you please re-test and close if you feel the issue has been fixed? Thanks! 😄

**Comment by srirambv** [comment]
Yes this is fixed. Its much easier now to tear off and attach back the tabs. Will remove the milestone as its fixed. @bsclifton does this need to be included for 0.15.3?

**Comment by bsclifton** [comment]
@srirambv thanks for removing milestone 😄  Only needs to be included if we wanted to share the fix in the release notes and it was a problem last release (0.15.2) and it was fixed this release (0.15.3)
