### ISSUE TITLE
Replace apple.com with another http site on the test plan

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8290]
# Manual tests
We need to change from www.apple.com to zyan.scripts.mit.edu/public

 Check that HTTPS Everywhere works by loading http://zyan.scripts.mit.edu/public
 Turning HTTPS Everywhere off and shields off both disable the redirect to https://zyan.scripts.mit.edu/public

## Original Description (Not relevant anymore)

- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
http sites load to https even when having https everywhere off and shields off
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Pro
- Brave Version (revision SHA):
0.14.2 preview 2
- Steps to reproduce:
    1. load http://apple.com
    2. disable https everywhere and shields
    3. load http://apple.com
    4. https://apple.com is loaded
    
- Actual result:
Loads with https even with https everywhere off
- Expected result:
Should load with http
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. load http://apple.com
    2. disable https everywhere and shields
    3. load http://apple.com
    4. See that http://apple.com is loaded

**Comment by srirambv** [comment]
That's expected as part of the HTTPS Everywhere test. 
``` Turning HTTPS Everywhere off and shields off both disable the redirect to https://www.apple.com```

**Comment by Jacalz** [comment]
But disable the shields should disable the redirect to https but it loads https @srirambv

**Comment by luixxiul** [comment]
It works at it should as Apple has by themselves set up to convert http traffic into https (Open devtool and look for the 301 status on network tab). You can verify it on Chrome as well

We need to find out another which is not encripted.

**Comment by luixxiul** [comment]
Setting the milestone and the label as it must be easy to fix..

**Comment by Jacalz** [comment]
thanks @luixxiul This worked for me 3 days ago, apple must have changed their ssl certificate or something just a couple days ago :wink:

**Comment by diracdeltas** [comment]
http://zyan.scripts.mit.edu/public should work as a test URL

**Comment by Jacalz** [comment]
That will be great 👍

**Comment by Jacalz** [comment]
I updated the description, we can close this when everyone has it written down 👍 cc @alexwykoff

**Comment by luixxiul** [comment]
Updated: https://github.com/brave/browser-laptop/wiki/Manual-Tests/_compare/90fe69631bd3a7fb788e295a7ad8ccef26b5ce9c...28d67ffe96020a911418434c17de893e00e8055e

**Comment by srirambv** [comment]
http://zyan.scripts.mit.edu/public shows 404 error but it still redirects to https. Just FYI
