### ISSUE TITLE
Widevine warning dialog does not consistently pop on Amazon

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8297]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
As per title ^

I'm adding this now because it will invariably come up in support and elsewhere.
as described in the Amazon Widevine Issue (https://github.com/brave/browser-laptop/issues/5233) there is no universally good heuristic for determining Widevine playback pages.

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
can you give me a URL example?  I thought this wasn't an issue anymore because videos are on primevideo.com
