### ISSUE TITLE
Always show URL bar when the siteinfo modal is displayed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8298]
## Test plan

https://github.com/brave/browser-laptop/pull/11245#issue-262440667

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
URL bar goes back to title mode when mouse is not over the tabs bar making the dialog persistant

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.2
rev	f07c142

- Steps to reproduce:
    1. Do not turn off Always show URL bar from settings
    2. Visit any site and click on the padlock icon to display the connection info
    3. Move away from the tabs bar, URL bar goes back to title mode but the connection info modal is still shown
    
- Actual result:
 connection info modal is still shown when URL bar goes to titel mode

- Expected result:
Should not change to title mode until the connection info modal is closed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25012154/88757756-2067-11e7-87b8-3fc75b3bbc43.png)

- Any related issues:
cc: @bradleyrichter  
Please change milestone if required

**Comment by luixxiul** [comment]
I think this has been captured as an issue because that dialog has the dark background whle it is not really modal. If so, removing darkening for all non-modal dialogs (#9034) is a fix for that.

**Comment by luixxiul** [comment]
On https://jsfiddle.net/6zj4sjxr/ the issue can be reproduced. It could be fixed this way.

<img width="891" alt="screenshot 2017-09-22 17 07 38" src="https://user-images.githubusercontent.com/3362943/30735055-935c45fc-9fb8-11e7-9f67-b0be07ea08f8.png">

Above the same opacity is set to the navigation bar.

@bradleyrichter could I know what you would think about that? For me it could also work with `opacity: 0.4` or so.
