### ISSUE TITLE
View Page source tab doesn't show any tab title 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8301]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
View Page source tab doesn't show any tab title 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	f07c142

- Steps to reproduce:
    1. Visit any page in a new tab
    2. View page source using keyboard shortcut/right click context menu
    3. Page source opened in a new tab has no title just favicon
    
- Actual result:
View source tab doesn't show tab title
- Expected result:
Should show `view-source:<URL>`
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Not checked but previous releases showed the site name which caused reloading the view source tab to load the actual page
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![viewsource](https://cloud.githubusercontent.com/assets/17010094/25013302/fee584d2-206a-11e7-8d16-64c5895446a1.gif)

- Any related issues:
#4096

**Comment by bsclifton** [comment]
This has been fixed (title is now just `view-source://url-goes-here`)
