### ISSUE TITLE
mac os spinning wheel often appearing

### ISSUE THREAD

**Issue by jorgheymans** [brave/browser-laptop#8302]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
as of a couple of days ago brave has become really sluggish, often displaying the color pizza wheel (even getting it several times as i am typing this text). I have checked on chrome and firefox there i don't have it. Activity monitor is showing almost no cpu usage.
- Platform (Win7, 8, 10? macOS? Linux distro?):
mac os sierra 10.12.4, mac book air 1,7 GHz Intel Core i5
- Brave Version (revision SHA):
3de60d5
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
EDIT: with a fresh profile brave is up to its normal performance again!
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by sanderaarts** [comment]
Startup seems to take forever in OSX Yosemite (10.10.5) now.

**Comment by jorgheymans** [comment]
@sanderaarts do you know how to start with a fresh profile ? I would like to test if it makes a difference. 

I have to say though it's a problem that seems to come and go, for example today performance was much better and i did not get the spinning wheel once.

**Comment by Liunkae** [comment]
@jorgheymans To make a fresh profile:
1. Quit Brave.
2. Look for a folder at the following location: `~/Library/Application Support/brave`. You may use Finder menu > Go > Go to Folder and paste the URL.
3. Rename the folder to something else (e.g. brave2).
4. Open Brave again. It will automatically recreate the profile folder.

**Comment by jorgheymans** [comment]
alright thanks, next time it starts being sluggish again i'll create an empty profile to see if it makes a difference.

**Comment by jorgheymans** [comment]
so indeed i just tried starting with a clean profile and brave was a lot snappier ! But it's not really a solution as you can understand :-)

**Comment by Liunkae** [comment]
@jorgheymans Did you have a lot of bookmarks, tabs, etc. when it was slow?

**Comment by jorgheymans** [comment]
I don't have any bookmarks, and in this particular case had maybe 3-4 tabs
open.

**Comment by Liunkae** [comment]
@jorgheymans Did you have Brave Payments or Brave Sync enabled?

**Comment by jorgheymans** [comment]
No they are not enabled.

**Comment by jorgheymans** [comment]
latest release not really making a difference, reverting back to chrome until this is fixed sorry guys.

**Comment by bsclifton** [comment]
@jorgheymans it's understandable- thanks for the report. We're always looking to improve 😄  Stay subscribed and you should be notified of updated

**Comment by jorgheymans** [comment]
Thanks, i will. Am going to keep using brave on mobile, there it really
rocks !

**Comment by Jacalz** [comment]
+1 from community

**Comment by Jacalz** [comment]
+1 from community https://community.brave.com/t/command-delay-and-the-spinning-beach-ball-on-mac/3549

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/macos-periodic-beach-ball/3476/2

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/delayed-functions-help-needed/3547

**Comment by bsclifton** [comment]
I'd like to close this issue in favor of something more trackable... please see https://github.com/brave/browser-laptop/issues/9311 for a large list of performance issues we're tracking 😄
