### ISSUE TITLE
Wallet creation fails on 0.14.2 RC build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8304]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Wallet creation fails on 0.14.2 RC build

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	d4cad89

- Steps to reproduce:
    1. Do a clean install of 0.14.2 RC1 build
    2. Launch browser from git console
    3. Enable payments, console shows error, wallet creation fails
    
- Actual result:
Wallet creation fails

- Expected result:
Should create wallet

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ledger](https://cloud.githubusercontent.com/assets/17010094/25020290/9bbdb0b2-2085-11e7-9725-1fe76c682a9d.gif)
```
! >>> worker error: Cannot find module 'node-anonize2-relic-emscriptenindex.js\./anonize2-jumbo.js'
ModuleNotFoundError: Cannot find module 'node-anonize2-relic-emscriptenindex.js\./anonize2-jumbo.js'
    at requireProxy (extensions::muon/module_system/commonjs:61:15)
    at fn (extensions::node-anonize2-relic-emscripten/index.js:3:16)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::node-anonize2-relic-emscripten/index.js:325:43
    at requireProxy (extensions::muon/module_system/commonjs:64:22)
    at fn (extensions::ledger-client/worker.js:4:15)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::ledger-client/worker.js:46:43
! >>> worker error: Cannot read property 'binding' of undefined
TypeError: Cannot read property 'binding' of undefined
    at requireProxy (extensions::muon/module_system/commonjs:65:20)
    at fn (extensions::ledger-client/worker.js:4:15)
    at define (extensions::muon/module_system/commonjs:69:10)
    at Object.commonjs [as require] (extensions::muon/module_system/commonjs:54:3)
    at extensions::ledger-client/worker.js:46:43
```

- Any related issues:
#8195

**Comment by lukemulks** [comment]
@srirambv confirming wallet creation hang on my Win10 64b install. 

Enabling and disabling the Payments switch causes the `Creating Wallet...` message to hang, including on refresh. 

Screencap below to illustrate: 

![brave-wallet-issue-rc-04132017-creatingwallethang](https://cloud.githubusercontent.com/assets/8979240/25021289/875b1270-2046-11e7-9520-dc506f043c64.PNG)

Profile info for ref: 

``` 
Brave: 0.14.2 
rev: d4cad892de4c8da087c4efee2e8955caa630675c 
Muon: 2.57.10 
libchromiumcontent: 57.0.2987.133 
V8: 5.7.492.71 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64

```

**Comment by jonathansampson** [comment]
Same here, only mine locked up entirely.

![image](https://cloud.githubusercontent.com/assets/815158/25028297/dd69558c-2078-11e7-817f-11a917fc85a9.png)

**Comment by bsclifton** [comment]
Fixed by reverting https://github.com/brave/browser-laptop/commit/91b8ebf17443a042e82666b121ca9b1755d1c6e1

**Comment by bridiver** [comment]
I'm pretty sure this is the issue https://github.com/brave/ledger-client/blob/master/worker.js#L4
in general `require` shouldn't use `.js` extensions. `require('node-anonize2-relic-emscripten')` is sufficient and should fix the downstream path issue
