### ISSUE TITLE
Not all info buttons have tool tip shown

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8305]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Not all info buttons have tool tip shown

- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
Brave	0.14.2
rev	d4cad89
- Steps to reproduce:
    1. Open about:preferences#general, my homepage info has tool tip 
    2. Open about:preferences#sync, doesn't have tooltip but shows link at the bottom of page which persists even if navigated to other sections in the same tab after opening the link. Have to rehover over the info button for the link to be dismissed 
    3. Open about:preferences#extensions info button is not clickable and neither does the community link shows the link as tool tip
    4. Open about:preferences#plugins info buttons for flash doesn't show tool tip but info buttons for Widevine shows 

- Screenshot if needed:

- Any related issues:
#5758
cc: @diracdeltas @bradleyrichter

**Comment by alexwykoff** [comment]
@srirambv could you re-check this cause i think we just fixed it

**Comment by srirambv** [comment]
Verified on 0.15.0 RC5. Still no tool tip for info buttons on about:preferences#plugins and info button on about:preferences#extensions is not clickable.

**Comment by kumarrishav** [comment]
@srirambv where tool tip info button should come in about:preferences#plugins case? Next to `Plugins Settings` header?

**Comment by kumarrishav** [comment]
Also, the tool tip icon used in about:preferences#extension is light in color (rgb(101, 101, 101)), while tool tip at other are more black. Is this expected? @bradleyrichter @srirambv

**Comment by kumarrishav** [comment]
I would like to give this a shot

**Comment by kumarrishav** [comment]
@srirambv can i get info on this? Thanks

**Comment by srirambv** [comment]
@kumarrishav  Flash Plugin info buttons don't have tooltip. Only shown for Google Widewine in plugin page
![image](https://cloud.githubusercontent.com/assets/17010094/25899825/4433df92-3589-11e7-9f67-d60496025948.png)

Same with Sync info button no tooltip shown. 

First should show tooltip `Get Adobe Player`
![image](https://cloud.githubusercontent.com/assets/17010094/25900034/f33c4452-3589-11e7-8a5a-fb5754ab3f2d.png)

Second should show `Troubleshooting Flash`
![image](https://cloud.githubusercontent.com/assets/17010094/25900068/16601c06-358a-11e7-9c36-372f793839ac.png)

Sync should show `Learn more about Brave Sync`
![image](https://cloud.githubusercontent.com/assets/17010094/25900170/68841370-358a-11e7-94ab-2ca4bc086ae6.png)


Regarding info button on extensions pages, I believe its on purpose as there the link to community is given separately at the end. @cezaraugusto or @bradleyrichter can confirm on this for extension page.

**Comment by bradleyrichter** [comment]
@nickapuzzo Can you review the above and see if it matches your pending doc of string changes?

**Comment by kumarrishav** [comment]
any update on this one?

**Comment by ntmbayfield** [comment]
Hi, i would like to have this issue assigned to me if possible? I am a student in the Web devlopment Immersive at Galvanize and am looking to contribute to my first open-source project?

**Comment by NejcZdovc** [comment]
@ntmbayfield Welcome, very happy that you want to contribute to our project. Sadly this issue is already fixed with https://github.com/brave/browser-laptop/pull/13376, but we have a lot of other good stuff.

You can check labels `help wanted` https://github.com/brave/browser-laptop/labels/help%20wanted and `good first bug` https://github.com/brave/browser-laptop/labels/bug%2Fgood-first-bug.

If you have any more questions or you need some help with the issues just let me know.

**Comment by jasonrsadler** [comment]
Closing as this should be addressed in `Brave-Core`
