### ISSUE TITLE
URL is not changing in Address bar

### ISSUE THREAD

**Issue by iamVP7** [brave/browser-laptop#8306]
- Did you search for similar issues before submitting this one?
Yes. Discussed in Slack 
- Describe the issue you encountered:

I am trying to edit a link and open a tab. when i type openai in my brave i got three suggestions in the order give below. I try to move my selection using down arrow button and trying to select third link. My expectation is as i move my arrow the link should get changed so just in case if I have to edit i can do it

1. openai.com/
2. https://blog.openai.com/
3. twitter.com/openAI

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 14.04 64 bit

- Brave Version (revision SHA):
0.14.2

- Steps to reproduce:
    1. Visit all the above links given above.
    2. now type openai in the address bar
    3. you will get drop down try to move the arrow down in drop down and see the URL wont get reflected in address bar and  you select different choice.
    
- Actual result:
URL in address bar is not changing as the selection changes.

- Expected result:
The URL should get changed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
No. it is in RC version.

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![img_20170412_165724](https://cloud.githubusercontent.com/assets/3106852/25021156/bbceb978-2080-11e7-9107-d5cd2a84839c.jpg)

- Any related issues:

**Comment by bsclifton** [comment]
@aekeus is this one you could look at?

**Comment by bsclifton** [comment]
Closing as this is expected (cc: @bbondy)

I found this out while reviewing https://github.com/brave/browser-laptop/pull/8824.  In the above screenshot, notice:
- openai is what is typed into the URL bar
- the selected item (twitter.com/OpenAI) doesn't match (ex: doesn't start with `openai`), so the URL is not injected into the URL bar
