### ISSUE TITLE
Extensions still show __MSG__ under description  after enabling

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8307]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Extensions still show __MSG__ under description  

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	d4cad89

- Steps to reproduce:
    1. Do a clean install of 0.14.2 RC1
    2. Enable Pocket, wait for the tab to load, extension description shows __MSG__
    3. Same issue for Dashlane, Lastpass
    

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25021649/d9211926-208a-11e7-988e-172d0db38c2b.png)

- Any related issues:
#7683 #7826
cc: @jonathansampson @cezaraugusto

**Comment by cezaraugusto** [comment]
@jonathansampson is it possible that https://github.com/brave/browser-laptop/commit/d4cad892de4c8da087c4efee2e8955caa630675c reintroduced it?

**Comment by jonathansampson** [comment]
@cezaraugusto It is; I see the problem now. I'll issue a fix immediately.
