### ISSUE TITLE
Torrent Viewer should be recommended along with external protocol handler when magnet/torrent link is clicked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8308]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Torrent Viewer should be recommended along with external protocol handler when magnet/torrent link is clicked

- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
Brave	0.14.2
rev	d4cad89
- Steps to reproduce:
    1. Disable Torrent viewer in about:preference#extensions and restart browser 
    2. Visit https://webtorrent.io/free-torrents/ and click on any link (torrent/magnet)
    3. Protocol handler notification is shown to launch external app. This should also suggest to enable builtin torrent viewer as well
    
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25021870/976ae10a-208b-11e7-9edc-057a6305aedf.png)

- Any related issues:
cc; @feross @bradleyrichter @diracdeltas 
Please change milestone if required

**Comment by feross** [comment]
@srirambv Isn't the Torrent Viewer extension enabled by default? So, this issue is about showing a message to users who have intentionally disabled the Torrent Viewer extension. Wouldn't these users already be aware of the extension since they had already manually disabled it?

**Comment by feross** [comment]
For what it's worth, this is what currently happens when you click a PDF link and the PDF Viewer extension is disabled:

![screen shot 2017-04-13 at 1 18 27 pm](https://cloud.githubusercontent.com/assets/121766/25022700/be0f3382-204b-11e7-8882-31e02163414f.png)

There is no message about enabling the built-in PDF viewer.

**Comment by bradleyrichter** [comment]
PDF viewer is enabled by default. (or is supposed to be)


But a button for “Enable PDF Viewer” would be nice here….
