### ISSUE TITLE
sync device list sort by ID order is wrong

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8311]
if you sort by ID, it sorts lexicographically instead of numerically:
![screen shot 2017-04-13 at 8 31 54 pm](https://cloud.githubusercontent.com/assets/549654/25023185/646efdac-2088-11e7-9de9-c48174bec439.png)

**Comment by kumarrishav** [comment]
@diracdeltas Also, Only clicking on header (say, id), results in showing up and down arrow? By default arrow is hidden. Is it expected behaviour? @srirambv

**Comment by NejcZdovc** [comment]
@kumarrishav yes this is expected

**Comment by kumarrishav** [comment]
@diracdeltas Can you tell how to reproduce this issue? As i have only one laptop and sync is not yet arrived in iOS or android.

**Comment by ayumi** [comment]
@kumarrishav You can:

1. Start Brave and enable Sync (new profile).
2. Save the Sync profile code words.
3. Delete user profile e.g. `rm ~/Library/Application\ Support/brave-development`
4. Start Brave and enable Sync, joining the existing Sync profile.
5. Repeat steps 3–4 until you have 10 devices total.

**Comment by ayumi** [comment]
WIP at https://github.com/brave/browser-laptop/commit/8d8b6e440cc800e468189bef0d70f36b722090f5 which needs tests.

**Comment by teh-f00l** [comment]
Can I take up this as a first issue?
