### ISSUE TITLE
current master has regression bugs for tabs and navigation

### ISSUE THREAD

**Issue by lucidNTR** [brave/browser-laptop#8313]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
the current master e74f0e5cc962a9a9b8fabaf4632177218530de1e 
has loads of regressions, in order to quickly get to know what to do next i created this envelope ticket, please give feedback how to continue:

- [x] new tabs show non selected about:blank text instead of an empty box ready to typye box 
  - **captured with https://github.com/brave/browser-laptop/issues/8378 and https://github.com/brave/browser-laptop/issues/8525**
- [x] swipe navigation as well as the history menu back and forward actions are broken
  - **fixed with https://github.com/brave/browser-laptop/pull/8642**
- [ ] tabs open randomly without close button, closing them with right click menu completely crashes the browser process
  - **need more information / retest to see if this is still an issue**
- [x] opening new tabs and entering url sometimes loads the url in a completely different tab
   - **this should now be fixed after recent reduxComponent commits**

- Platform (Win7, 8, 10? macOS? Linux distro?): macos
- Brave Version (revision SHA): e74f0e5cc962a9a9b8fabaf4632177218530de1e

**Comment by Liunkae** [comment]
Swipe navigation is broken for me with the current master (91b8ebf). I cannot reproduce the any of other problems.

**Comment by Liunkae** [comment]
It works fine in 0.14.2 RC 2, which is based of the dev-channel branch.

**Comment by bsclifton** [comment]
@lucidNTR I believe all of these issues have been addressed (either fixed or captured in a different issue).  Can you please retry master and let us know how it looks?  If you experience issues, report here and we can help either find an existing issue or create a new issue to track / prioritize
