### ISSUE TITLE
Remove ref dependency from Frame

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8322]
**Describe the issue you encountered:**
Because Frame will now be a stateless component, we need to remove dependency on refs from a Frame

**Comment by luixxiul** [comment]
@NejcZdovc if you think this is worth mentining in relase notes, would you mind removing the label that I have added in case? CC @alexwykoff

**Comment by NejcZdovc** [comment]
Yeah I think that we can remove it from release notes
