### ISSUE TITLE
fingerprinting brave via extension resources

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8323]
## Test plan

https://github.com/brave/browser-laptop/pull/8325#issue-221868705

----

https://extensions.inrialpes.fr/

seems like it should be blockable

**Comment by luixxiul** [comment]
CC @diracdeltas 

1. Enable LastPass
2. Open https://extensions.inrialpes.fr/ and run test
3. `lastpass-free-password-ma` is detected

If it is expected, please just reclose the issue.

**Comment by diracdeltas** [comment]
@luixxiul that is expected, we don't prevent fingerprinting all extensions, only the Brave-maintained ones.
