### ISSUE TITLE
 Rogue Tooltip Appears, Refuses to Clear

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8324]
A tooltip often appears on Windows 10, and persists even when Brave isn't focused.

![tooltip](https://cloud.githubusercontent.com/assets/815158/25051189/fe50551e-2110-11e7-9972-28972ef4c485.gif)

@bradleyrichter reports seeing this (or something very similar) on macOS as well.

**Comment by jonathansampson** [comment]
Closing, as this appears to be an issue with [Visual Studio Code](https://github.com/Microsoft/vscode).

**Comment by bbondy** [comment]
Best to remove from milestone so it doesn't have to go through QA / release notes triage. I did this one.  Thanks!

**Comment by jonathansampson** [comment]
@bbondy Thanks!
