### ISSUE TITLE
Extension: Evernote Web Clipper

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8327]
Extension: [Evernote Web Clipper](https://chrome.google.com/webstore/detail/evernote-web-clipper/pioclpoplcdbaefihamjohnefbikjilc)
Background Page: chrome-extension://hgallicindpgpekhmjmkjhneagiopfem/background.html

## Needed APIs:

**chrome.browserAction**
- #8329 chrome.browserAction.onClicked ([docs](https://developer.chrome.com/extensions/browserAction#event-onClicked))
- #8344 chrome.browserAction.setIcon ([docs](https://developer.chrome.com/extensions/browserAction#method-setIcon))
- #8788 chrome.browserAction.setTitle ([docs](https://developer.chrome.com/extensions/browserAction#method-setTitle))

**chrome.contextMenus**
- #8331 chrome.contextMenus.create / createProperties.documentUrlPatterns ([docs](https://developer.chrome.com/extensions/contextMenus#method-create))
- #8332 chrome.contextMenus.update ([docs](https://developer.chrome.com/extensions/contextMenus#method-update))
- #8789 chrome.contextMenus.remove ([docs](https://developer.chrome.com/extensions/contextMenus#method-remove))

**chrome.cookies**

- #6262 chrome.cookies.getAll ([docs](https://developer.chrome.com/extensions/cookies#method-getAll))

**chrome.extension**

- #8688 chrome.extension.getURL ([docs](https://developer.chrome.com/extensions/extension#method-getURL), _deprecated_)
- #8790 chrome.extension.onMessage (_deprecated_)
- #8792 chrome.extension.sendMessage (_deprecated_)

**chrome.i18n**
- #8326 chrome.i18n.getAcceptLanguages ([docs](https://developer.chrome.com/extensions/i18n#method-getAcceptLanguages))
- #4755 chrome.i18n.getMessage ([docs](https://developer.chrome.com/extensions/i18n#method-getMessage))
- #8793 chrome.i18n.getUILanguage ([docs](https://developer.chrome.com/extensions/i18n#method-getUILanguage))

**chrome.notifications**

- #8795 chrome.notifications.clear ([docs](https://developer.chrome.com/extensions/notifications#method-clear))
- #8796 chrome.notifications.create ([docs](https://developer.chrome.com/extensions/notifications#method-create))
- #8797 chrome.notifications.getAll ([docs](https://developer.chrome.com/extensions/notifications#method-getAll))

**chrome.runtime**

- #8683 chrome.runtime.getManifest
- #8798 chrome.runtime.id
- #8799 chrome.runtime.lastError
- #8791 chrome.runtime.onMessage ([docs](https://developer.chrome.com/extensions/runtime#event-onMessage))
- #8801 chrome.runtime.onMessageExternal
- #8802 chrome.runtime.sendMessage

**chrome.storage**

- #8806 chrome.storage.local.clear ([docs](https://developer.chrome.com/extensions/storage#method-StorageArea-clear))
- #8803 chrome.storage.local.get ([docs](https://developer.chrome.com/extensions/storage#method-StorageArea-get))
- #8805 chrome.storage.local.remove ([docs](https://developer.chrome.com/extensions/storage#method-StorageArea-remove))
- #8804 chrome.storage.local.set ([docs](https://developer.chrome.com/extensions/storage#method-StorageArea-set))

**chrome.tabs**

- #8807 chrome.tabs.captureVisibleTab ([docs](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab))
- #8680 chrome.tabs.create ([docs](https://developer.chrome.com/extensions/tabs#method-create))
- #8808 chrome.tabs.executeScript ([docs](https://developer.chrome.com/extensions/tabs#method-executeScript))
- #7456 chrome.tabs.insertCSS ([docs](https://developer.chrome.com/extensions/tabs#method-insertCSS))
- #8809 chrome.tabs.onRemoved ([docs](https://developer.chrome.com/extensions/tabs#method-onRemoved))
- #8810 chrome.tabs.onUpdated ([docs](https://developer.chrome.com/extensions/tabs#method-onUpdated))
- #8811 chrome.tabs.query ([docs](https://developer.chrome.com/extensions/tabs#method-query))
- #4687 chrome.tabs.remove ([docs](https://developer.chrome.com/extensions/tabs#method-remove))
- #8812 chrome.tabs.sendMessage ([docs](https://developer.chrome.com/extensions/tabs#method-sendMessage))
- #6790 chrome.tabs.update ([docs](https://developer.chrome.com/extensions/tabs#method-update))

**chrome.windows**
- #6789 chrome.windows.create ([docs](https://developer.chrome.com/extensions/windows#method-create))
- #4760 chrome.windows.onFocusChanged ([docs](https://developer.chrome.com/extensions/windows#event-onFocusChanged))
- #8330 chrome.windows.onRemoved ([docs](https://developer.chrome.com/extensions/windows#event-onRemoved))
- #8678 chrome.windows.remove ([docs](https://developer.chrome.com/extensions/windows#method-remove))
- #8679 chrome.windows.update ([docs](https://developer.chrome.com/extensions/windows#method-update))

**Comment by DavidRBailey** [comment]
See also op/issues/5136

**Comment by calebbarr** [comment]
+1

**Comment by luixxiul** [comment]
several +1s from https://community.brave.com/t/when-will-the-evernote-extension-be-included/2255

**Comment by davidhfo** [comment]
Another +1.

**Comment by jstrupp** [comment]
+1

**Comment by Najwalaylah** [comment]
+1

**Comment by christensen143** [comment]
+1

**Comment by anne-urai** [comment]
+1

**Comment by surelyourejoking** [comment]
+1

**Comment by tedhogan** [comment]
+1

**Comment by Noxvayl** [comment]
How is work towards adding this coming along? Last entry is quite old... 

I'm looking to make Brave my default browser but can't until I can effectively store research using Evernote.

**Comment by jrredhorse** [comment]
+1

**Comment by hashtaginfosec** [comment]
+1

**Comment by phainline** [comment]
+1   (also looking to change browser.  Use Evernote heavily for research about 50% of the time)

It looks like the project is waiting on many Chrome APIs to be implemented.  A pointer to other projects or at least a quarterly update (summary) would be nice.   

I could live with a workaround if EverNote would let one create _and populate_ a page from a pasted URL.  Can't figure out how to do that (on Mac version).  Also tend to guess, whatever timetable this extension is on... will be faster than Evernote adding that simple feature.

**Comment by HLFH** [comment]
With the next-generation Brave, https://github.com/brave/brave-browser, these kind of issues may be solved in an easier manner.

**Comment by skotzko** [comment]
+1

**Comment by galactusss** [comment]
+1 would be great!!

**Comment by leburges** [comment]
I have switched to Brave twice. Each time I am driven back to Chrome because of the lack of Evernote integration. I love brave, but I need Evernote. +1

**Comment by bsclifton** [comment]
@leburges just hang in there a little bit longer! (a few months - beta available earlier)

I'm going to close this issue as `wont-fix` and `fixed-with-brave-core` since we won't be addressing in Muon (`browser-laptop`; the JavaScript UI on top of Muon)

We WILL be getting **full extension support** when we switch over to the [Chromium based UI we're working on](https://github.com/brave/brave-browser) (repository names are `brave-browser` and `brave-core`). Trying to implement full extension support in Muon ended up being a massive effort ☹️
