### ISSUE TITLE
wiki: Brave Windows build guide: Updates for new Visual Studio install process

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8328]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

I am having to reinstall the Brave dev prereqs after a fresh Windows 10 re-install. 

- Our directions in the [Brave Windows build guide](https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide) have saved me countless times, but I noticed that the latest version of Visual Studio now has different installation options than it has had in the past, which no longer match our instructions from our build guide. 

- I would update this myself, but I'm not exactly sure which options we need to have users select from. In my case, I still have an older installer that I can temporarily use, but new users will have issues with this. 

@jonathansampson & @bsclifton - is there any chance either of you could take a look at the latest way the install options are presented, and update our build guide? I'm not exactly sure, and I have a feeling if I tinker with this it's going to burn a lot of time in trial/error. 

I'm going to include screenshots below that I've captured from the new UI. 

Visual Studio now has an option to select **Workloads** or **Individual Components** 

**Workloads options**
![vs-install-new-workloads-0-04142017](https://cloud.githubusercontent.com/assets/8979240/25054151/5f1e3c0e-2110-11e7-8537-d34f1c188c21.PNG)

![vs-install-new-workloads-1-04142017](https://cloud.githubusercontent.com/assets/8979240/25054163/72c93d1c-2110-11e7-88a5-bc282cc8515c.PNG)

**Individual Components options**
![vs-install-new-indcomponents-0-04142017](https://cloud.githubusercontent.com/assets/8979240/25054178/84244822-2110-11e7-8d67-e3226f0224d8.PNG)

![vs-install-new-indcomponents-1-04142017](https://cloud.githubusercontent.com/assets/8979240/25054184/8c711fb4-2110-11e7-9d0a-284bc390eb22.PNG)

![vs-install-new-indcomponents-2-04142017](https://cloud.githubusercontent.com/assets/8979240/25054190/9386c736-2110-11e7-9b40-4c493ac33855.PNG)

**Comment by luixxiul** [comment]
Isn't it possible to set up VM image where Visual Studio is installed? That would be a perfect solution :-D

**Comment by bsclifton** [comment]
@luixxiul this would be perfect... but there are licensing issues.  The easier solution would be to pre-compile and package the dependencies that are being compiled from source

If you all wanted to give a +1, check this issue out 😄 
https://github.com/brave/browser-laptop/issues/5685

**Comment by srirambv** [comment]
@lukemulks  This is what I selected from the installer and it worked fine for me.
@bsclifton can confirm if this is right?
![image](https://cloud.githubusercontent.com/assets/17010094/25177270/2c706196-24f9-11e7-870b-45bab33379be.png)

**Comment by bbondy** [comment]
As far as WIn10 SDK goes, only 14393 SDK.  Having win10 SDKs installed might even use the wrong one and cause problems.

From the chromium docs:

> Visual Studio
> 
> As of December 8, 2016 Chromium requires Visual Studio 2015, with the 14393 Windows SDK to build.
> 
> Install Visual Studio 2015 Update 3 or later - Community Edition should work if its license is appropriate for you. Use the Custom Install option and select:
> 
> Visual C++, which will select three sub-categories including MFC
> Universal Windows Apps Development Tools > Tools (1.4.1) and Windows 10 SDK (10.0.14393)
> You must have the 14393 SDK installed or else you will hit compile errors such as undefined or redefined macros.
> 
> Install the Windows SDK 10, and choose Debugging Tools For Windows when you install this in order to get windbg and cdb. The latter is required for the build to succeed as some tests use it for symbolizing crash dumps.

**Comment by bs** [comment]
None of the above worked for me. Eventually, I got it to build via:

`npm install --global --production windows-build-tools`

from the [https://github.com/nodejs/node-gyp](node-gpg) build instructions.
Can someone else confirm?

**Comment by Romvik** [comment]
Maybe will help https://github.com/Romvik/guide-brave-browser-build-windows/tree/master

**Comment by Jacalz** [comment]
I fixed this in the wiki by adding the info on how to install with windows-build-tools from npm. This is the way I have been using c++ build tools and it works correctly as far as i know...

The revision changes can be found [here](https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide/_compare/c4eae30fdae10c3d37126942d48508b7d5e5507c)

**Comment by bsclifton** [comment]
Great, thanks @Jacalz! 😄
