### ISSUE TITLE
About dialog icon got low quality somehow

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#833]
@aekeus mind taking a look?

**Comment by aekeus** [comment]
Sure, it looks ok on Windows. Will check the Mac build.

**Comment by bradleyrichter** [comment]
mac indeed got all mushy like:

![screen shot 2016-02-19 at 6 00 09 pm](https://cloud.githubusercontent.com/assets/13509546/13193747/dcb338c8-d732-11e5-8883-951512112688.png)
