### ISSUE TITLE
Extension API: chrome.contextMenus.create

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8331]
https://developer.chrome.com/extensions/contextMenus#method-create

## Known Limitations
- `createProperties.enabled of contextMenus.create is not supported yet`
- `createProperties.documentUrlPatterns of contextMenus.create is not supported yet`
- Instances of `%s` should be replaced/removed from `createProperties.title`

Blocks #8327, #6366, #9828

**Comment by diracdeltas** [comment]
wasn't this partially done by https://github.com/brave/browser-laptop/commit/d602b3c4c6aafa76fcfe2b21d2c86990b2f562e5 ?

**Comment by jonathansampson** [comment]
@diracdeltas `chrome.contextMenus.create` is supported, but only partially. The `documentUrlPatterns` portion isn't supported, which is what Evernote requires to contextually leverage `contextMenus.create`.

**Comment by jonathansampson** [comment]
Blocks #8327
