### ISSUE TITLE
tv.youtube videos result in unsupported video format

### ISSUE THREAD

**Issue by sshum00** [brave/browser-laptop#8335]
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
Videos/Streams do not play on tv.youtube (see screenshot)

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
3de60d52df3ef48d12d9696a076b72079beb9658

- Steps to reproduce:
    1. Visit a tv.youtube video/channel: https://tv.youtube.com/live?v=61oinY_sRqo  
    2. Wait for page to load
    3. Receive error
    
- Actual result:
Video does not load and you see this error: Your browser does not currently recognize any of the video formats available.

- Expected result:
Video should load and play

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, I've tried this on several machines.

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/3541579/25060475/424f7bcc-216c-11e7-89e6-897eae6a469e.png)

- Any related issues:

**Comment by singhnp** [comment]
+1

I experienced this same issue:

- Did you search for similar issues before submitting this one?
No - tweeted @bravelaurenwags (https://twitter.com/nps255/status/1039236377731203072)

- Describe the issue you encountered:
Videos do not play on tv.youtube.com. Live streams only give me a black screen. Videos give me an error message stating that the video format is not supported (https://pbs.twimg.com/media/DmwPmbuUcAAeGwb.jpg:large)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 Home

- Brave Version (revision SHA):
Brave 0.23.105 rev 9a46f8f
AND
Developer Release of Brave-core Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1239
