### ISSUE TITLE
Improvements to cert error clickthrough

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#834]
1. make it more difficult to click through a certificate error
2. show a broken lock icon for pages where a cert error has been clicked through

**Comment by Professor-plum** [comment]
Could this also provide the user the option to view the certificate

**Comment by diracdeltas** [comment]
@Professor-plum yes, thanks for adding that. I tried to add a view-cert option but it kept causing the page to crash. will investigate later.

**Comment by diracdeltas** [comment]
1 is done. moving 2 to 0.8.1

**Comment by bbondy** [comment]
Move to 0.8.2?

**Comment by diracdeltas** [comment]
Good point, I think I can get this in well before end of today though. If not, will move

**Comment by bbondy** [comment]
ok np, I'm still fighting with v49
