### ISSUE TITLE
MacOS tab close cross icon should be on left side

### ISSUE THREAD

**Issue by adambowles** [brave/browser-laptop#8341]

**Comment by bsclifton** [comment]
It would be nice if Brave offered a config option for this- the favicon could then also double as the close tab icon (as seen in Opera)

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/10993

**Comment by boxofdeath** [comment]
This drives me crazy!

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1003
