### ISSUE TITLE
cert validation fails for punycode domain

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8342]
Brave 0.14.1, mac

- Steps to reproduce:
    1. go to https://xn--e1awd7f.com/
    2. see a cert error
 
- Expected result: there is no cert error

cc @darkdh

**Comment by darkdh** [comment]
I see chrome 57.0.2987.133 do this
```
Redirecting navigation xn--e1awd7f.com -> www.xn--e1awd7f.com because the server presented a certificate valid for www.xn--e1awd7f.com but not for xn--e1awd7f.com. To disable such redirects launch Chrome with the following flag: --disable-features=SSLCommonNameMismatchHandling
```
and firefox 55.0a1  will also have common name mismatch error
```
xn--e1awd7f.com uses an invalid security certificate. The certificate is only valid for www.xn--e1awd7f.com Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
And this certificate have server alternative name only for `www.xn--e1awd7f.com`
So I think this error is reasonable.

**Comment by diracdeltas** [comment]
@darkdh thanks for looking at it. It is strange that chrome does the redirection even though the cert is not valid. I guess our behavior is okay.
