### ISSUE TITLE
Unable to run Enzyme tests

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8345]
Running Enzyme tests locally throws the following message:

```
react-test-renderer is an implicit dependency in order to support react@15.5+. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
Cannot find module 'react-test-renderer/shallow'
```

This is not a problem with `react-test-renderer` itself but due to lack of `react-dom` module that's needed for Enzyme

**Comment by cezaraugusto** [comment]
STR: try running `npm run test -- --grep="NewTab component unit tests"`

**Comment by bsclifton** [comment]
cc: @NejcZdovc
