### ISSUE TITLE
Add ability to create a new bookmark folder in BM hanger flow

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8346]
Often, a new bookmark creates a need for a new folder to store said bookmark. Currently it is required to break the BM flow and exit the BM window in order to make a new folder - which adds several steps to the process which is most desired at the time of making the new bookmark. 

A "Create New Folder..." item should be added to the folder menu in the new-bookmark door hanger.

![image](https://cloud.githubusercontent.com/assets/13509546/25069443/536bcbc6-2235-11e7-953b-5a8cdd17645e.png)

This opens the current New Folder dialog.
![image](https://cloud.githubusercontent.com/assets/13509546/25069445/5b3e9ad6-2235-11e7-9c3d-5586ee753988.png)

Upon creation, the user is returned to the BM door hanger with the new folder already chosen.
![image](https://cloud.githubusercontent.com/assets/13509546/25069447/6013d21a-2235-11e7-8617-b18c18db2837.png)

**Comment by luixxiul** [comment]
fyi the bookmark hanger is under development, waiting for review: https://github.com/brave/browser-laptop/pull/8136#issuecomment-292765203

**Comment by luixxiul** [comment]
same as #1658

**Comment by eljuno** [comment]
+2 from community https://community.brave.com/t/create-new-folder-when-adding-bookmark/10521?u=eljuno

**Comment by rebron** [comment]
Closing. wontfix here, fixed with brave-core.
