### ISSUE TITLE
Not Blocked Ad Network (propellerads.com)

### ISSUE THREAD

**Issue by hasanhuseyincakir** [brave/browser-laptop#835]
https://propellerads.com/
http://i.imgur.com/ZvDaoQV.png

**Comment by luixxiul** [comment]
ref: #1513

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/need-investigation-ads-by-propellerads-com-not-blocked/10398

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
