### ISSUE TITLE
Startup Performance decrease when sync is turned on

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8354]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After enabling sync, a multi-second slowdown was noticed for startup.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X

- Brave Version (revision SHA):
0.14.1 vs 0.14.2 ( https://github.com/brave/browser-laptop/commit/632a9bc130e5d452493e4aa20632bf691f1ababd )

- Steps to reproduce:
    1. With a clean profile, launch 0.14.1 with sync turned off, check the time.
    2. Turn on sync, quit and launch 0.14.1, check the time, measure the delta vs previous run. (take average of 3 runs minimum)
    3. With a clean profile, launch 0.14.2 with sync turned off, check the time. 
    4. Turn on sync, quit launch 0.14.2, check the time, measure the delta vs previous run. (take average of 3 runs minimum)
    
- Actual result:
0.14.2 exhibited a 2-3 second slowdown on startup 

- Expected result:
Startup speed should remain near constant.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, however 0.14.2 rc2 has shown worse performance.

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
https://www.youtube.com/watch?v=vScmYPa8FU4

- Any related issues:

**Comment by bbondy** [comment]
did this regress since 0.14.1?

**Comment by alexwykoff** [comment]
ticket update in progress

**Comment by srirambv** [comment]
Run on new Windows installation 

| 0.14.1 Sync Off  | 0.14.1 Sync On  | 0.14.2 Sync Off    | 0.14.2 Sync On |
| ---- | --- | --- | --- |
| 05.55s | 5.25s | 6.85s | 6.25s | 
| 05.15s | 5.11s | 6.44s | 7.77s |
| 05.02s | 5.01s | 6.47s | 6.35s |

**Comment by ayumi** [comment]
Merged #8408 which addresses one possible sync slowdown.

**Comment by bsclifton** [comment]
The remaining issue (https://github.com/brave/browser-laptop/issues/8367) will be fixed when the next build is done (which installs the new version of the client)
