### ISSUE TITLE
Startup performance decrease when ledger is turned on

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8355]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After enabling payments, a 1 second slowdown was noticed for startup.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X

- Brave Version (revision SHA):
0.14.1 vs 0.14.2 ( https://github.com/brave/browser-laptop/commit/632a9bc130e5d452493e4aa20632bf691f1ababd )

- Steps to reproduce:
    1. With a clean profile, launch 0.14.1 with payments turned off, check the time.
    2. Turn on payments, quit and launch 0.14.1, check the time, measure the delta vs previous run. (take average of 3 runs minimum)
    3. With a clean profile, launch 0.14.2 with payments turned off, check the time. 
    4. Turn on payments, quit and launch 0.14.2, check the time, measure the delta vs previous run. (take average of 3 runs minimum)
    
- Actual result:
0.14.2 exhibited a 1 second slowdown on startup 

- Expected result:
Startup speed should remain near constant.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
0.14.1 did not exhibit a 1 second slowdown when payments were enabled.

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
https://www.youtube.com/watch?v=vScmYPa8FU4

- Any related issues:

**Comment by srirambv** [comment]
Run on clean Windows installation

| 0.14.1 Ledger Off  | 0.14.1 Ledger On  | 0.14.2 Ledger Off    | 0.14.2 Ledger On |
| ---- | --- | --- | --- |
| 05.55s | 7.91s | 6.85s | 8.72s | 
| 05.15s | 6.67s | 6.44s | 6.78s |
| 05.02s | 7.13s | 6.47s | 7.45s |

**Comment by zentagonist** [comment]
Closing as stale
