### ISSUE TITLE
Tab title often isn't updated until the cursor is moved over it (l10n)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8358]
Describe the issue you encountered: This is a follow up to #7765

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.2 RC2

- Steps to reproduce:
    1. Change language setting (eg to German)
    2. Restart the browser
    3. Open about:preferences ("Einstellungen") from the kabob menu 
    4. The tab title is set to "Preferences"
    5. Hover on the tab
    6. The title is changed to "Einstellungen"    

- Expected result: "Einstellungen" should be displayed instead of "Preferences" on the 4th step

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #7765

**Comment by bsclifton** [comment]
Closing in favor of the original issue (which is not actually fixed):
https://github.com/brave/browser-laptop/issues/7765
