### ISSUE TITLE
opening pdf in new tab fails to load

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8364]
## Test plan:
1. go to https://letsencrypt.org/repository/
2. right click on any of the PDF links to open in a new tab. it should work.
3. right click on any of the PDF links to open in a new private tab. it should work.

## Original issue description
- Did you search for similar issues before submitting this one?
yes 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.14.1 / pdfjs 1.7.428

- Steps to reproduce:
    1. right-click to open a pdf file in a new tab with pdf.js enabled
    2. the pdf does not load

**Comment by cezaraugusto** [comment]
doesn't work on Ubuntu. "Save as" dialog opens while opening on the same page but not for new tab/new private tab. Reopening

**Comment by bsclifton** [comment]
This works great for me on Ubuntu 14.04 using 0.15.0 RC3

Can you retest this, @cezaraugusto?

**Comment by bsclifton** [comment]
Also confirmed it works great on Ubuntu 16.04

**Comment by cezaraugusto** [comment]
I'm still not able to open PDF running the executable, but I did a new shot checking out RC3 tag branch and it worked. I can't say why as both are running muon 2.58.4. 

This is labeled as working on macOS and tested on two diff Ubuntu versions working good, so I'll close and keep an eye on RC4. @bsclifton thanks for tracking 🥇
