### ISSUE TITLE
Unable to select urlbar suggestion with keyboard

### ISSUE THREAD

**Issue by psimyn** [brave/browser-laptop#837]
Type 'google' in urlbar
Press down arrow until google.com is selected
Press enter
Nothing happens

**Comment by SJ-Diamond** [comment]
Agree, unable to pick suggestions with the keyboard, does not work.

**Comment by bbondy** [comment]
This is fixed here:
https://github.com/brave/browser-laptop/commit/668292ca853b0006d2cfdf3010bf8a072094402a

Unfortunately it didn't make it into the release in time but we're shooting again for this Wednesday coming up.
