### ISSUE TITLE
"Mute other Tabs" limited to active window

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8384]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The _Mute other Tabs_ option only applies to tabs _in the same window_. This feature should, perhaps, apply to all tabs, across all windows. Or, there should be an additional option for universal mute.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/632a9bc130e5d452493e4aa20632bf691f1ababd

- Steps to reproduce:
    1. Open two Windows
    2. Play a YouTube video in each
    3. In the first window, select _Mute other Tabs_ from the tab context menu
    
- Actual result:
Audio from the second window continues to play.

- Expected result:
All tabs, from all windows, will be muted.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bbondy** [comment]
this should dispatch with an app action to the browser process and then handle it in tabs reducer across all windows.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/883
