### ISSUE TITLE
set blank bookmark titles to [space] on import

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8385]
When users have specifically edited chrome bookmarks to have NO title so they are displaying only FAVICONs, they would like the same appearance after importing into Brave.

Mission: retain blank name for a nameless bookmark during import process.

**Comment by jonathansampson** [comment]
Related to this is the inability for users to remove their bookmark title. Instead, they must edit and replace the title to a space. Deleting the title entirely results in no change to the bookmark itself.

Source: https://twitter.com/somenteangus/status/855114312536424448

**Comment by bradleyrichter** [comment]
The space was a temp hack to allow no title. Needs a clean fix.

**Comment by bsclifton** [comment]
@darkdh how easy/difficult do you think this change would this be? (You're have a lot more experience w/ the import code than me 😄 ).  This may involve an electron change from what I understand (since the importer lives there, right? We re-use the Chromium importer)

**Comment by darkdh** [comment]
We can use easy workaround before custom title being obsoleted.
In `importer.on('add-bookmarks'...` of `app/importer.js`,
we can set `customTitle` of site to space if we detect that bookmarks[i].title is empty

**Comment by jonathansampson** [comment]
@darkdh We should use a zero-width space, to avoid adding gaps between icons.

**Comment by bsclifton** [comment]
Fixing this issue (and allowing for a blank title) may properly fix the issue:
https://github.com/brave/browser-laptop/issues/6585

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/suggestion-bookmark-titles/26063?u=eljuno
