### ISSUE TITLE
Allow PDF.js access to filesystem

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8386]
The chromium extension `PDF.js` exposes a config option "Allow access to filesystem", which is defaulted to false.  This prevents us from being able to open local PDFs

This issue would be either:
- defaulting the option to true
OR
- exposing a way in the UI to toggle and defaulting to false

**Comment by diracdeltas** [comment]
duplicate of https://github.com/brave/browser-laptop/issues/2714

IIRC @willy-b looked into this and found it may not only be an issue of setting the permission

**Comment by diracdeltas** [comment]
i would suggest working on this after https://github.com/brave/pdf.js/pull/2 is merged, since that PR does a lot of cleanup and removal of code that isn't needed in brave

**Comment by bsclifton** [comment]
@diracdeltas good catch :) I'll close this as a dupe During our triage meeting, @bbondy volunteered to look at it for our next release
