### ISSUE TITLE
Pinned tab showed as unpinned when discarded

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8388]
On 0.14.2 RC2 (macOS), I noticed that one of my pinned tabs which I had used quite a bit became unpinned after I stopped using it for 20+ minutes.  When I moved the mouse to the tab (which triggered a tab preview), the tab loaded and then put itself back over in the pinned tabs

**Comment by alexwykoff** [comment]
@luixxiul could you investigate this when you have time?

**Comment by eljuno** [comment]
I think I experience this on 0.15.0.

Pinned tab unpinned itself, but when I click that tab -- I'm disabling tab preview -- the tab back to pinned tab and reload.

![brave-pinned-tab-bug](https://cloud.githubusercontent.com/assets/25360853/25559412/9bd3ccf4-2d63-11e7-8939-aa1c6fec4e0b.gif)

**Comment by bsclifton** [comment]
@eljuno thanks for capturing that! glad to know I'm not crazy 😄

**Comment by NejcZdovc** [comment]
based on a conversation with @bbondy we need to use tabs from appState for this to work correctly.
