### ISSUE TITLE
Redux component - Frame

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8392]
**Describe the issue you encountered:**
Transform Frame into Redux component.

**Comment by luixxiul** [comment]
Is this issue not related with the recent bugs which blocks the release?

Also: https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=label%3Arefactoring%2FreduxComponent%20

**Comment by luixxiul** [comment]
well essentially all of them linked there, if the bugs are not related with Muon.

**Comment by NejcZdovc** [comment]
so far I couldn't confirm that this is related to redux. I think that the problem is somewhere else. Still didn't find the root cause, so for now I wouldn't cross out redux yet.
