### ISSUE TITLE
various issues with noscript icon

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8403]
1. disable scripts on a page then click the noscript icon, there is a console error:

```
"Refused to send form data to 'chrome://brave/Users/yan/repos/browser-laptop/app/extensions/brave/index-dev.html#' because it violates the following Content Security Policy directive: "form-action http://localhost:*".
```

2. click the noscript icon repeatedly and the popup doesn't show up after the first time.

3.  when noscript is enabled, twitter.com is missing the lock icon:
![screen shot 2017-04-19 at 22 03 29](https://cloud.githubusercontent.com/assets/549654/25204381/d35f7ade-254c-11e7-8a93-651d222b33da.png)

4. the clickable area should be increased

**Comment by diracdeltas** [comment]
cc @bsclifton. this should block release if it's in 0.15.0 and other people also have this bug.

**Comment by diracdeltas** [comment]
also after the error is thrown, the urlbar security icon is gone:
![screen shot 2017-04-19 at 22 03 29](https://cloud.githubusercontent.com/assets/549654/25204260/17c0d822-254c-11e7-9c4d-3353c7dbd2ed.png)

**Comment by bsclifton** [comment]
The popup works as expected, however the browser dev tools do log a CSP error:
<img width="515" alt="screen shot 2017-04-19 at 3 16 43 pm" src="https://cloud.githubusercontent.com/assets/4733304/25204658/7dd67f60-2513-11e7-8ed9-ec471da8981f.png">

**Comment by diracdeltas** [comment]
if i click on the noscript icon 3 times in a row, it stops toggling the popup after the 2nd click

**Comment by bsclifton** [comment]
@diracdeltas I can't repro that in `dev-channel`:
![noscript](https://cloud.githubusercontent.com/assets/4733304/25205186/244ee358-2516-11e7-8579-623f09dbd9e6.gif)

**Comment by diracdeltas** [comment]
@bsclifton pretty sure that issue was due to redux refactoring and i have  a fix

**Comment by diracdeltas** [comment]
is anyone seeing the lock icon issue on a site other than twitter.com? i think it's due to the noscript twitter siteHack actually

**Comment by bsclifton** [comment]
@diracdeltas I tried a few sites, can't repro-
facebook.com, google.com, wikipedia.org

**Comment by cezaraugusto** [comment]
not only twitter but google as well

**Comment by bsclifton** [comment]
@cezaraugusto you can reproduce the CSP error, but does the lock icon disappear?

**Comment by cezaraugusto** [comment]
yep, but for twitter only:
 
<img width="992" alt="screen shot 2017-04-20 at 4 40 20 am" src="https://cloud.githubusercontent.com/assets/4672033/25219081/9050fdbc-2583-11e7-8b08-efb5b5478641.png">
