### ISSUE TITLE
Settings v Preferences mismatch

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8405]
- Did you search for similar issues before submitting this one?
Yes 

- Describe the issue you encountered:
I was opening an issue for Sync, and noticed that we use _Settings_ from the top menu: 
**_Edit > Settings_** for the `about:preferences` page. 

Sync issue opened for reference: https://github.com/brave/sync/issues/79

- Platform (Win7, 8, 10? macOS? Linux distro?):

All (suspected) - need confirmation for macOS. 

- Brave Version (revision SHA):
``` 
Brave: 0.14.2 
rev: d4cad892de4c8da087c4efee2e8955caa630675c 
Muon: 2.57.10 
libchromiumcontent: 57.0.2987.133 
V8: 5.7.492.71 
Node.js: 7.4.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```

- Steps to reproduce:

Captured in this screenshot: 

![brave-android-sync-preferences-v-settings-04192017](https://cloud.githubusercontent.com/assets/8979240/25205268/854321f6-2516-11e7-8940-abe9194a3f54.PNG)

Within the Android browser, this is also referred to as Settings instead of Preferences. I'm not sure how much we can control for naming within the Android Brave browser, but I wanted to match if we're looking to have cross-platform consistency. 

We're going to want to make sure we have consistency so the Sync instructions match across platforms. 

@bradleyrichter I'm going to assign you on this once since we're talking about UI across platforms. Let me know if there's anything else I can assist with for this.

**Comment by Liunkae** [comment]
This is due to differing OS naming conventions (see #2277).
Windows and Linux use "Settings".
macOS uses "Preferences".

The mismatch in UI instructions is a problem, though.
