### ISSUE TITLE
The only missing feature preventing me to use it is `drag & release link/text` to open and search

### ISSUE THREAD

**Issue by laishulu** [brave/browser-laptop#8407]
The only missing feature preventing me to use it is `drag & release link/text` to open and search

I can't find the following features in brave or any extensions:

- drag a **link** away from the original place and release the mouse button to **open** the link, without the need to drag the link to address bar or tab bar.
- drag a **text** away from the original place and release the mouse button to **search** the text, without the need to drag the text to address bar or tab bar.

**Comment by Liunkae** [comment]
Great suggestion! I think this would be a great setting.

**Comment by chenhouwu** [comment]
this feature is usually provided by third-party extensions for other browser, e.g. `quick drag` for firefox

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/right-mouse-button-menu-add-block-element/5893/2
