### ISSUE TITLE
Report: Ulterius Crashes Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8412]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A user has reported that https://ulterius.io/ crashes Brave.

> Andrew Sampson : https://twitter.com/Andrewmd5/status/854918101611229184
> @BrendanEich where do I submit bug reports for @brave because @UlteriusApp crashes it outright. client.ulterius.io

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):

- Steps to reproduce:
Presumably, just using the service will crash Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Presumably.

**Comment by aekeus** [comment]
I cannot directly replicate this crash at the above mentioned URL. It may be related to websockets as that is evident in the console.
<img width="384" alt="screen shot 2017-04-20 at 2 18 10 pm" src="https://cloud.githubusercontent.com/assets/210240/25246006/544eec88-25d4-11e7-9b0a-bf530aca7654.png">

**Comment by jonathansampson** [comment]
@aekeus I'm assuming we have to install the desktop utility first, and attempt to use the service via Brave.

**Comment by Codeusa** [comment]
To provide some helpful input, the issue occurs when trying to initiate screen sharing which is a mixture of websocket/canvas.

**Comment by jonathansampson** [comment]
@Codeusa Does the issue exist if you drop your shields before making the connection?

**Comment by Codeusa** [comment]
I've tried both with and without shields.

**Comment by jonathansampson** [comment]
@Codeusa Am I correct to assume that these issues don't repro in Chrome?

**Comment by Codeusa** [comment]
Correct, it works fine in Chrome, Firefox and Vivaldi.
