### ISSUE TITLE
Tabs No Longer Show Full-Color Emoji

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8414]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tabs used to show full-color emoji; now they are rendered as solid shapes. It is reported that Brave used to render these as full-color in recent history (a month or so ago).

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/632a9bc130e5d452493e4aa20632bf691f1ababd

- Steps to reproduce:
    1. Navigate to https://codepen.io/thebabydino/pen/Wxpzdy
    2. Check tab contents for full-color emoji
    
- Actual result:
Solid circles are rendered

- Expected result:
Full-color emoji are rendered

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/815158/25246312/e078a6f2-25cc-11e7-8f75-fef5e8132cd2.png)

**Comment by jonathansampson** [comment]
@cezaraugusto Might we have lost support when we refactored the tab UI at the all-hands?

**Comment by Liunkae** [comment]
That explains the white blobs I've been seeing in 0.14.1!

**Comment by cezaraugusto** [comment]
yep, that's related to gradient opacity for tab titles introduced there. 

Color is set to `transparent` to make use of `background-clip` and bg gradient. A good alternative would be moving that gradient somewhere else or just add another layer for that.

**Comment by jonathansampson** [comment]
@cezaraugusto Awesome. I'm happy to take this and work on a PR if you like.

**Comment by cezaraugusto** [comment]
🎉  awesome, thanks!

**Comment by luixxiul** [comment]
does this issue cover the issue on https://spoofed-favicon.badssl.com/ or do we track that on another issue?

**Comment by cezaraugusto** [comment]
@luixxiul I think that's a different one.

**Comment by jonathansampson** [comment]
@luixxiul Is there an issue for that? Curious what @diracdeltas thinks about sites showing a lock as their favicon.
