### ISSUE TITLE
sync should only upload records when important fields are changed

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8415]
at minimum it should not be sending an update every time that `lastAccessedTime` or `creationTime` in a site record is changed.

cc @SergeyZhukovsky @jhreis - this should also be implemented on mobile if not already. it does not require any changes to brave/sync.

**Comment by alexwykoff** [comment]
I didn't see the log messages expected.

<img width="1738" alt="screen shot 2017-05-24 at 5 05 11 pm" src="https://cloud.githubusercontent.com/assets/1434040/26427652/52e19d98-40a3-11e7-972e-fdedd1b48e7b.png">
