### ISSUE TITLE
 Ads reported on Chicago Tribune with Shields Up

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8416]
Ads observed on ChicagoTribune.com with Shields Up

![brave-chicagotribune-ads-04202017](https://cloud.githubusercontent.com/assets/8979240/25254618/545683a6-25db-11e7-932e-74e2ed8ddad3.png)

- Reported by @bradleyrichter 
- Brave v0.14.2
- https://github.com/brave/browser-laptop/commit/d4cad892de4c8da087c4efee2e8955caa630675c
- macOS, likely global 
- Check against LATimes in case it's familiar. 

- [ ] Repro
- [ ] Attempt to repro on mobile, confirm status. 
- [ ] Investigate, determine root cause
- [ ] map strategy for resolution

**Comment by jspenguin2017** [comment]
This is `g00` (again). The solution in uBO-extra still works. 
https://github.com/gorhill/uBO-Extra/blob/master/contentscript.js#L234
The solution is quite aggressive, you may want to add some more conditions.

**Comment by lukemulks** [comment]
Thanks @jspenguin2017 - `g00` is certainly annoying. 

I'm going to link to this issue as well, which has some context: 
https://github.com/jspenguin2017/uBlockProtector/issues/95#issuecomment-289219950

cc: @too4words - this is another Instart item.
