### ISSUE TITLE
somehow created a ghost-looking pinned tab

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8417]
os x, brave 0.14.1

i accidentally dragged one of my normal tabs in such a way that it ended up being a faded-out "pinned" tab in between the regular pinned tabs and the regular tabs:

![screen shot 2017-04-20 at 22 54 38](https://cloud.githubusercontent.com/assets/549654/25255864/b05dd140-261c-11e7-8a07-bd8b2979ab44.png)

It was stuck like this until I started dragging another tab, at which point it snapped into being a regular pinned tab.

**Comment by jonathansampson** [comment]
@diracdeltas Do you still have it? Can you copypasta some of the computed state (styles, classes)?

**Comment by diracdeltas** [comment]
@jonathansampson unfortunately not. I will do that if i get it again

**Comment by bbondy** [comment]
seems like draggingOverLeft or draggingOverRight not getting cleared in some case.

**Comment by diracdeltas** [comment]
closing since i haven't seen this in a long time
