### ISSUE TITLE
Login problem on facebook and yahoo

### ISSUE THREAD

**Issue by Hall900** [brave/browser-laptop#8420]
- Did you search for similar issues before submitting this one?
Not exacly the same
- Describe the issue you encountered:
I can't login with my password to facebook or yahoo on Browser while with firefox works fine. When i use different users id and password works ok. 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 7
- Brave Version (revision SHA):
0.14.1 (3de60d5)
- Steps to reproduce:
    1. Open facebook page use the same password you have to login with firefox
    2. Facebook reports wrong password
    3. Try a different user id and password with Brave and everything works fine
    
- Actual result: Cant login 

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by Liunkae** [comment]
@Hall900 Are you using any password managers?

**Comment by Hall900** [comment]
No not at all...

**Comment by bsclifton** [comment]
@Hall900 if you're still using Brave (or if you're up for trying it again), can you please try a newer version? We've fixed several issues with login and it would be great to confirm this works for you 😄

**Comment by Hall900** [comment]
Yes i am still using Brave as my main browser (accept when i have to use Authy plugin). Currently i am on 0.17.13 version in Ubunty Linux and i don't see any problem .

**Comment by bsclifton** [comment]
@Hall900 awesome, thanks for the update! 😄  I'll go ahead and close this issue- please reopen if you experience this again. We'd be glad to help with anything else that comes up too! Thanks for hanging in there with us 😄
