### ISSUE TITLE
Offer option to have URL bar fill empty space ("wide URL bar")

### ISSUE THREAD

**Issue by ShalokShalom** [brave/browser-laptop#8421]
## Test plan

https://github.com/brave/browser-laptop/pull/8714#issue-226475313

----

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:

![screenshot_20170421_144620](https://cloud.githubusercontent.com/assets/6344099/25278665/5b55bfe0-26a4-11e7-9d12-e00334691a93.png)

- Platform
KaOS, self build with this setup: https://gist.github.com/ShalokShalom/faf765bb82b3363a2215567523cd3ae6

- Brave Version (revision SHA):
3de60d52df3ef48d12d9696a076b72079beb9658

This here is the build log: 

https://gist.github.com/ShalokShalom/86e51be92dca5ec979445c695d56f95a

**Comment by Liunkae** [comment]
@ShalokShalom Which icons are missing?

**Comment by ShalokShalom** [comment]
See by yourself? I dont know yet, which icons should be placed there, you see the empty places in my screenshot?

**Comment by NejcZdovc** [comment]
@ShalokShalom I don't see any icon that is missing, can you please point us in a right direction/area? Thank you

**Comment by ShalokShalom** [comment]
Do you see the screenshot?

With this large, grey empty space on both sides?

**Comment by NejcZdovc** [comment]
Yes I can see the empty space. There aren't any icons there, this is not a bug. What icons would you expect to be there?

**Comment by ShalokShalom** [comment]
Ahm, for what is this space then?

**Comment by NejcZdovc** [comment]
URL bar is aligned to the center of the window and max width of it it's 900px, so you see a white space because your screen is bigger and limit has kicked in.

**Comment by luixxiul** [comment]
@ShalokShalom maybe you are expecting this kind of width?

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/25314319/8c896e7a-287c-11e7-8ba2-b3d0ce080931.jpg)

**Comment by bsclifton** [comment]
The other use for that area is so that you can easily grab and drag the window

**Comment by ShalokShalom** [comment]
@luixxiul Yes

Is there a way to set this to the look and feel i am used to?

**Comment by luixxiul** [comment]
I would prefer having it as an option, "Use wide URL bar" or like that.

**Comment by ShalokShalom** [comment]
Thanks :+1:

**Comment by bradleyrichter** [comment]
yes, default should be as is to allow for easier window dragging so please add a pref in about:preferences#advanced.

**Comment by ShalokShalom** [comment]
So long as i can recompile..

**Comment by luixxiul** [comment]
@ShalokShalom the wide URL bar will be added to the browser after two updates, 0.15.400. Please wait for a moment, thanks.

**Comment by ShalokShalom** [comment]
Thanks a lot ^-^
