### ISSUE TITLE
Navigating to a PDF may crash the tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8422]
- Describe the issue you encountered:
Navigating to a PDF may crash the active tab. It matters _how_ you navigate to the PDF too; right-clicking the link and selecting _Open in New Tab_ will not crash. A simple click of the link (to navigate within the active tab window) will cause the crash. PDF Viewer must be enabled.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/71fb73001617949528cc6473e288a49e76fcd4d5

- Steps to reproduce:
1. Click this link, https://pdfs.semanticscholar.org/2a01/e1f14172a91215931ed787d97dee1301fe7d.pdf
    
- Actual result:
Sad tab face

- Expected result:
Loads PDF

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bbondy** [comment]
updated, this is just a particular PDF problem and not all PDFs on lniux problem.

**Comment by lukemulks** [comment]
Two additional data points: 

1. I was able to repro, windows 10, 64bit. 

2. We received a report from a contributor from the Brave Community today that also experienced the issue on macOS: https://community.brave.com/t/cannot-open-view-pdfs-after-latest-update-strange-error-screen-results/2444/1

**Comment by lukemulks** [comment]
We received an additional report from the Brave Community. Details and link included below for reference. 

Community URL: https://community.brave.com/t/cannot-open-view-pdf-s-after-latest-update-strange-error-screen-results-help-me-apr-28-1-3-apr-28-1h-ago-herewego3h-i-have-macos-sierra-10-12-3-and-upgraded-to-brave-0-15-0-earlier-today-since-the-upgrade-when-i-click-to-download-or-view-a-pd/2450

Feedback:

>Cannot open / view PDF’s after latest update - strange error screen results
>
>Windows 7 64-bit user, and upgraded to Brave 0.15.0 earlier today. Since the upgrade, when I click to download or view a PDF, I will get a brief flash of the normal page structure for showing a PDF before the tab goes all black with the error image in the center, as in the attached screenshot

**Comment by Liunkae** [comment]
I myself have seen this problem in 0.15.0. Thanks @darkdh!
