### ISSUE TITLE
wallet creation fails on linux

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8423]
cf., https://github.com/brave/browser-laptop/issues/8372#issuecomment-296249559

**Comment by bbondy** [comment]
still failing

steps to reproduce:
1. clear profile
2. enable brave payments

Creating wallet hangs

This is using a build with tip:
https://github.com/brave/browser-laptop/commit/0e64cb363304c320082eaa8fe8f015196fb80886

**Comment by bbondy** [comment]
aka 0.15.0rc2

**Comment by NejcZdovc** [comment]
tried on master as well and it's failing (tested on macOS)

**Comment by cezaraugusto** [comment]
Still falling on RC2. Confirm bug happens on MacOS

STR:

* With a fresh probile, go to payments
* Enable payments
* Loading state remains as-is forever (tested up to 7min)
* Restart Brave
* Go to payments
* Click Create wallet button 
* Nothing happens
