### ISSUE TITLE
about:brave takes *longer than expected* time to fetch version data

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8426]
Tested using [v0.15.0dev-RC2](https://github.com/brave/browser-laptop/releases/tag/v0.15.0dev-RC2) executable

STR:

* Clear profile
* Go to about:brave
* Screen has no info
* Keep refreshing page, log time while refreshing
* At ~1.5min, information shows

<img width="446" alt="screen shot 2017-04-21 at 5 26 31 pm" src="https://cloud.githubusercontent.com/assets/4672033/25296193/669e1050-26bd-11e7-9156-3d42f2cd4ae6.png">

Tested on macOS and labelling so until confirmed on other OSes

**Comment by bsclifton** [comment]
Confirmed

**Comment by bsclifton** [comment]
Built versions should be using the version from the config, not actually calling out (that should only happen is environment is `development`)

**Comment by bsclifton** [comment]
I can't reproduce in latest (RC3). This may have been because caused because of another bug

**Comment by cezaraugusto** [comment]
also confirm that's not an issue with RC3. Tested on Ubuntu. 

Will take an eye on it when RC4 is out but closing for now
