### ISSUE TITLE
Enabling pocket crashes Brave

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8427]
STR:

* Checkout v0.15.0dev-RC2: `git checkout tags/v0.15.0dev-RC2`
* Clear session-store
* Go to extensionsTab
* Enable pocket
* Pocket will open tab with login page and then crash

Reproducible running macOS Sierra

**Comment by cezaraugusto** [comment]
worth mentioning that other extensions don't seem to crash application. This is specific to Pocket

**Comment by bsclifton** [comment]
Can't reproduce on Windows x64 with binary for RC2

**Comment by bsclifton** [comment]
unable to repro on `dev-channel` on macOS too

**Comment by cezaraugusto** [comment]
did a clean npm install and worked ok, also unable to repro with executable so that's definitely a fault from my side. thanks for checking sir. Labelling as invalid
