### ISSUE TITLE
tab page selection reverts to previous tab page on its own

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8429]
v0.15.0dev-RC2

Also exists in 0.15.314.

My experience is that the set changes even during tab-previewing while hunting for a tab.

1. start in the last set.
2. click on the 2nd set button.
3. start hovering over tabs to hunt for a tab.
4. see tab set selection revert back to last, and likewise, tab previews are now changed to last set.

easier to show than explain:

![tabset_bounceout](https://cloud.githubusercontent.com/assets/13509546/25298328/cc1d3808-26a8-11e7-974b-2f7f0f731cd7.gif)

**Comment by jonathansampson** [comment]
Doesn't appear to repro for me:

Brave Version: https://github.com/brave/browser-laptop/commit/958aab0b1bcd460e9ffdfb7b1fc55d6d9a204b62
Operating System: Windows 10 (15063)

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/815158/25397228/2fc64f28-29ad-11e7-8bf6-719cd1529a30.gif)

**Comment by cezaraugusto** [comment]
* issue happens when page a is still loading when you switch tab pages. 
* once page is loaded it focus on the loaded tab and set it as active, instead of keeping user choice. * Not always the loaded tab is set as active visually but tab page is always set.

**Comment by bradleyrichter** [comment]
I had to switch to 100 tabs per page yesterday because otherwise can’t get work done with this bug.

**Comment by cezaraugusto** [comment]
closed by https://github.com/brave/browser-laptop/commit/b397e9d592a1c7db77470afd0fdf96bc9f56d130 in #9809. I referenced the wrong commit by mistake.
