### ISSUE TITLE
Restructure directory hierarchy based on process

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#843]
Ideally there would be:
- browser: For the main process code (Most of this code is inside ./app right now)
  - stores
  - ...
- renderer: For the renderer process code (Most of this code is inside of ./js right now)
  - components
  - stores
  - ...
- common: Code used by both processes
  - constants
  - ...

**Comment by bbondy** [comment]
cc @pfraze

**Comment by bridiver** [comment]
probably want to add extensions to this list. Definitely makes sense to mimic the chromium code structure

**Comment by bbondy** [comment]
We should probably untangle this soon before we have more hands on the project full time.

**Comment by bridiver** [comment]
yep, moving code around is tough when you have a lot of commits coming in

**Comment by bbondy** [comment]
I guess it doesn't all have to be done in one chunk, we could move some things over incrementally with the correct directory structure.

**Comment by bridiver** [comment]
we could start with some placeholder directories and README files to explain them. Once we have them in place we can require all new files to use them and incrementally migrate the old files

**Comment by bbondy** [comment]
ok deal, we already have a doc that describes the directory hierarchy but it is very out of date.  I'll start to do this soon.

**Comment by bridiver** [comment]
I'll have a PR ready in a few minutes
