### ISSUE TITLE
Accessing SWF Causes Immediate Crash

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8437]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When a particular `<embed>` element is added to the WSHH site, Brave immediately crashes the associated tab.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
0.15.0

- Steps to reproduce:
    1. Navigate to http://www.worldstarhiphop.com
    2. Open the Developer Tools (Ctrl+Shift+I)
    3. Paste and run the following: 

```
document.body.appendChild(
  document.createElement('div')
).innerHTML = '<embed src="http://cache.worldstarhiphop.com/videos/js/ZeroClipboard.swf" />'
```

Alternatively, open a tab and navigate to `http://cache.worldstarhiphop.com/videos/js/ZeroClipboard.swf`.
    
- Actual result:
The tab crashes.

- Expected result:
Brave should not crash.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not sure.

- Is this an issue in the currently released version?
No.

- Can this issue be consistently reproduced?
Yes.

- Screenshot if needed:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/815158/25302173/a16c14ee-26fd-11e7-9be6-e28faef83e50.gif)

**Comment by jonathansampson** [comment]
After double-checking, this issue *DOES NOT* repro in 0.14.1, or 0.14.2 RC2. It appears to have been introduced with C58 in 0.15.0.

**Comment by bsclifton** [comment]
Not able to repro with 0.15.0 RC3 on Windows 10 x64 ☹️   (I tried both ways- following steps and just opening a new tab w/ that address)

I'm going to move this back to 0.15.1- please feel free to reprioritize if there is an update to steps to reproduce or if this is a blocker

**Comment by Jacalz** [comment]
I can comform that I couldn't repro on 0.15.0 RC3 too @bsclifton

**Comment by alexwykoff** [comment]
Working on mac and win64, @jonathansampson can we close this DNR as likely fixed by other changes?

**Comment by jonathansampson** [comment]
Closing as DNR.

**Comment by bsclifton** [comment]
@jonathansampson yes- it was fixed with https://github.com/brave/muon/commit/ee77b72f264d3a32886a7b516c5089f06a797534 😄
