### ISSUE TITLE
Zoom shortcut not working in 0.15.0 RC3

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8438]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When pressing ctrl and scrolling with scroll wheel nothing happends 👎 
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windwos x64 Windows 10, I could not reproduce it on mac os 
- Brave Version (revision SHA):
0.15.0 RC3
- Steps to reproduce:
    1. Open any site
    2. Hold down ctrl and scroll at the same time
  
- Actual result:
Nothing happends
- Expected result:
Should zoom
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Nope
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. Open any site
    2. Hold down ctrl and scroll at the same time
    3. Should zoom

**Comment by jonathansampson** [comment]
Did just a bit of digging, and found that the `mousewheel` event isn't being fired on Frame instances when the _Control Key_ is pressed. Handler bound here: https://github.com/brave/browser-laptop/blob/428d0c660b8a96cec6d31927c3e0211f9c10cb29/js/components/frame.js#L905

**Comment by bbondy** [comment]
@Jacalz nice find!
I'm experiencing slightly different event firing @jonathansampson but thanks for the initial work in any case to find the spot in code. I think it's a muon problem and I think I either have a fix or am close, I just need a build on win to test it.  Doing overnight.   For e it always gets fired but ctrlKey is never set.

**Comment by jonathansampson** [comment]
@bbondy Glad you were able to find the issue. This is what I was seeing in my cursory check:

![ctrl-scrolling](https://cloud.githubusercontent.com/assets/815158/25316008/c09edefa-2824-11e7-9172-8fff5ec459f6.gif)

**Comment by bbondy** [comment]
that's not the correct fix by the way, still working on a fix.

**Comment by bbondy** [comment]
I get the same as you @jonathansampson on win10 but different on win7

**Comment by alexwykoff** [comment]
Tried this with 0.15.0 RC4 (muon 2.58.5) and it wasn't working with a trackpad on my VM (win7 ia-32).  I could scroll zoom my desktop icons though so it seemed as though the gesture was recognized.

**Comment by alexwykoff** [comment]
@luixxiul @srirambv please grab this as soon as you can ^

**Comment by srirambv** [comment]
Still an issue on Win x64. Wheel up/down performs the scroll as expected but Ctrl+Wheel scroll doesn't zoom in/out. Reopening the issue as its not fixed on RC4 as well

**Comment by bbondy** [comment]
it needs new muon builds which aren't available yet. Next build will have it.

**Comment by bbondy** [comment]
will be fixed in 2.58.6 muon
