### ISSUE TITLE
Add the ability to customize adblock network filters

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#844]
Both for cosmetic and network filters

**Comment by SJ-Diamond** [comment]
It would also be really great if the user would be able to insert additional blocking lists like it is possible in other adblock variants.

**Comment by Codes4Fun** [comment]
I'm not sure how this is planned to work but it would also be nice to have it like the AdBlock Plus plugin's 'Blockable items' panel where it allows you to see individual files that have been blocked and add a file as an exception to filtering. That was how I was able to determine which script file to make an exception that works around issue #828

**Comment by luixxiul** [comment]
On the cosmetic fillter, see #344

**Comment by bsclifton** [comment]
Cosmetic filters were completed (in brave-core) with https://github.com/brave/brave-browser/issues/94; Adblock UI is captured with https://github.com/brave/brave-browser/issues/403
