### ISSUE TITLE
movement of the bars (bookmark bar) is nauseating 

### ISSUE THREAD

**Issue by oscalation** [brave/browser-laptop#8440]
The bookmark bar and open tabs menu bars move when notifications are given in the UI. The bars move up and down. 

For example, when you receive the notification saying "would you like to remember this password", or would you like to allow this site to send you notifications, all of the bars shift. 

I find this movement very annoying and nauseating. Is there any plans to change the functionality of those notifications ?

**Comment by cezaraugusto** [comment]
Yes, we did notice that effect and changed how we deal with the notification bar. For reference, it's now moved below tabs. The change will be shipped with 0.15.1. If you have any feedback let us know your thoughts. 

<img src="https://cloud.githubusercontent.com/assets/4672033/25213207/602a5048-2565-11e7-887f-e5e7aa1b0f15.png">

I guess it answers your question so I'll close this issue. Feel free to reopen if you have anything else. Thanks for your feedback :)
