### ISSUE TITLE
Turning off shields and/or HTTPS Everywhere won't turn website to HTTP again

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8442]
I found this issue while running manual tests for Linux
Version: v0.15.0-RC3
Platform: Ubuntu 16.04

STR: 
1. Have shields and HTTPS Everywhere enabled
2. Go to http://zyan.scripts.mit.edu/public
3. Check that protocol is HTTPS
4. Turn off shields and/or HTTPS Everywhere
5. Refresh the page
6. Page is still indicating HTTPS

/cc @diracdeltas

**Comment by cezaraugusto** [comment]
Issue was reported and labeled as blocking from my understanding. If just a page refresh shouldn't turn URL to HTTP again with disabled shields please close this issue.

**Comment by darkdh** [comment]
I think you need to re-navigate the url (ex. paste it directly). refresh will just navigate to the url shown on navigation bar again. You can compare the behavior to Chrome/Firefox with https everywhere.

**Comment by cezaraugusto** [comment]
cool thanks for clarifying
