### ISSUE TITLE
Clean install fails

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8444]
**Describe the issue you encountered:** Clean install fails.

See: https://travis-ci.org/brave/browser-laptop/jobs/224821395#L644

> npm ERR! ENOTEMPTY: directory not empty, rename '/home/travis/build/brave/browser-laptop/node_modules/.ad-block.DELETE/node_modules/bloom-filter-cpp' -> > '/home/travis/build/brave/browser-laptop/node_modules/ad-block/node_modules/bloom-filter-cpp'

This is reproduced on my local machine.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
Should be working now.

**Comment by bbondy** [comment]
It was a problem with shrinkwrap. 

Solved by doing these steps:
Removed the shrinkwrap file on the root, run `npm install`, `npm prune`, `npm dedupe`, and then `npm shrinkwrap` and then it produces something valid.  Committed and pushed.
