### ISSUE TITLE
Update to v2.58.5 muon

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8445]

**Comment by bsclifton** [comment]
Updated with https://github.com/brave/browser-laptop/commit/7452b7ec81f8b501a0b747829fa81090a67becee

**Comment by bsclifton** [comment]
Updated to 3.0.201 with https://github.com/brave/browser-laptop/commit/e94dc6d1a8a1c3513536f1a68e907901ddee4f69
