### ISSUE TITLE
Refactor https everywhere to use filtering.js

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#845]
In order to do https://github.com/brave/browser-laptop/issues/748 we need some refactoring so that we can use `onBeforeRequest` for adblock & tracking protection.

Electron only allows you to have one handler for these webRequest methods.

@diracdeltas would you mind taking this? I'll then take #748.

**Comment by bbondy** [comment]
Would like to have this and #748 (which depends on this being done first) in Wednesday's release.

**Comment by diracdeltas** [comment]
sure
