### ISSUE TITLE
Download torrent file

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8452]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you disable Torrent Viewer, torrent download is still routed through it

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
b2e4b71
- Steps to reproduce:
    1. disable Torrent Viewer in preferences
    2. go to https://webtorrent.io/free-torrents/
    3. download Big Buck Bunny torrent file
    
- Actual result:
![image](https://cloud.githubusercontent.com/assets/9574457/25317815/d8f99a4c-2880-11e7-808b-6a6569bb3985.png)

- Expected result:
torrent is downloaded

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes
- Any related issues:
#7351

**Comment by bsclifton** [comment]
Updated to be `not-blocking` because WebTorrent has to be disabled in order to get error.  Happy path works fine

This does need to be fixed though- but I don't believe it should block the release

**Comment by NejcZdovc** [comment]
@bsclifton why I think it should be blocking is if you don't want to use torrent viewer because of X reason, you can't use torrent files at all.

**Comment by bsclifton** [comment]
@NejcZdovc Good point- are you able to right click and choose "Save Link As..."? I believe this should work

The fix for this issue may be easy... WebTorrent logic (filtering, etc) should be ignored if the extension is disabled. For example, the code in https://github.com/brave/browser-laptop/blob/master/app/browser/webtorrent.js

**Comment by NejcZdovc** [comment]
@bsclifton "Save Link As..." is not working, because we get the same error as we did before I implemented this one #8246. So we need to fix this scenario as well

**Comment by NejcZdovc** [comment]
Created a new issue for it #8463
