### ISSUE TITLE
Tab drag and drop mouse cursor

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8459]
**Describe the issue you encountered:**
When you drag the tab to another window's tabs bar, the mouse cursor should change properly.

![tab](https://cloud.githubusercontent.com/assets/3362943/25320001/fbe1adc6-28dd-11e7-82d0-8e71996bc9c5.gif)

1st try - the mouse cursor should be 🚫 where the tab cannot be dropped.
2nd try - the mouse cursor should be back to the initial one from 🚫 if the tab is dragged out of the tabs bar and back to the tabs bar.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.15.0 RC3

- Steps to reproduce: see the gif animation

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #6242 #4402

**Comment by bsclifton** [comment]
Marking as `wontfix` since we'll get this for free with Brave Core
