### ISSUE TITLE
chrome's default error page is displayed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8462]
**Describe the issue you encountered:**
Chromium's default error page is displayed instead of ours. I think this is the reason of a failing test error: https://travis-ci.org/brave/browser-laptop/jobs/225094766#L1794

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open a URL with invalid domains
    
- Actual result: f63f733

  <img width="687" alt="screenshot 2017-04-24 17 07 54" src="https://cloud.githubusercontent.com/assets/3362943/25327835/97869d18-2910-11e7-8905-f5f48333d066.png">

- Expected result: 3de60d5

  <img width="540" alt="screenshot 2017-04-24 17 07 10" src="https://cloud.githubusercontent.com/assets/3362943/25327797/80ac1898-2910-11e7-9b34-dc925d97ad64.png">

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
cc @bbondy

**Comment by jasonrsadler** [comment]
On Win 10 entering google.comm gives me the brave error, clicking retry then gives me the chrome error and the browser no longer functions. UI hovers work but nothing responds to clicks. 

Exception in console:
"Uncaught TypeError: Cannot read property 'filterNot' of undefined", source: http://localhost:8080/gen/app.entry.js (29697)

**Comment by bsclifton** [comment]
@jasonrsadler the issue you mentioned will be fixed with https://github.com/brave/browser-laptop/pull/13265
