### ISSUE TITLE
Android device name is not shown upon sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8464]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Android device name is not shown upon sync
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64, 
Brave Android 1.0.20 
Android OS v5.0.1
- Brave Version (revision SHA):
Brave	0.15.0
rev	8e63cc0
- Steps to reproduce:
    1. Enable Sync on laptop 
    2. Sync an Android device using the QR Code
    3. Device gets listed but no name shown
    4. Restart browser, still no name
    5. Turn off and turn on Sync, still no name
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.
    
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25330547/e5987514-28d7-11e7-8fda-df80179d455f.png)

- Any related issues:
cc: @SergeyZhukovsky

**Comment by bbondy** [comment]
This is a bug with android, please post that repo if it's not already there. Thanks.
