### ISSUE TITLE
1Password description shows as extension for Google Chrome

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8465]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
1Password description shows as extension for Google Chrome
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
Brave	0.15.0
rev	8e63cc0
- Steps to reproduce:
    1. Clean install 0.15.0 RC3
    2. Enable 1Password extension
    3. Go to about:extensions, 1Password extension description says `1Password extension for Google Chrome.`
    
- Actual result:
1Password description shows as extension for Google Chrome
- Expected result:
Should be `1Password description shows as extension for Brave`
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Not checked but should not be same
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25331606/94856aca-28db-11e7-9b09-8dd7fc8f526b.png)

- Any related issues:
cc: @jonathansampson

**Comment by jonathansampson** [comment]
Looks like we need to _bravify_ that. I'll take a look!
