### ISSUE TITLE
Contribution statement page break needs extra padding

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8467]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Contribution statement page break needs extra padding
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
Brave	0.15.0
rev	8e63cc0
- Steps to reproduce:
    1. Ensure you have a lot ledger entries 
    2. Open  contribution statement 
    3. Page break needs padding.
    
- Actual result:
No padding after page break in contribution statement
- Expected result:
Contribution statement page break needs extra padding
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Not checked
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25334788/1355c71c-28e8-11e7-851a-f752c3759c94.png)

- Any related issues:
#7883
cc: @luixxiul @cezaraugusto  @willy-b

**Comment by cezaraugusto** [comment]
@luixxiul mind taking this one?

**Comment by luixxiul** [comment]
I don't have the long list of the sites: I will take it if I have the list
