### ISSUE TITLE
Delay when opening new tab

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#847]
There is some quite big delay when opening a new tab, you have quite to wait some bit before you are able to type in the url of the page you want to visit.

**Comment by bbondy** [comment]
via Command+T? It seems immediate to me.

**Comment by SJ-Diamond** [comment]
Sure, the tab opens in an instant. But if i write here after opening an url, it gets either fully or partly deleted, so i have to wait a bit after opening the tab before i can write the url.

System here is Windows 8

**Comment by diracdeltas** [comment]
I've seen 100ms+ delays when opening a new tab via Cmd+T; it's not too annoying except text in the URL bar gets deleted. i thought i fixed it in 134aeae6e2b8245e4b95c987fb25111e28c09a48.

**Comment by psimyn** [comment]
@diracdeltas was the disabled change what should have fixed it?

I don't it ever gets disabled, the only time loadTime is empty, location is already set to about:newtab. Could change what disabled checks for, but then time-to-type is still blocked by loading about:newtab.

Maybe about:newtab should be treated as a special case, and check for current input value in ComponentDidMount of frame

**Comment by diracdeltas** [comment]
> was the disabled change what should have fixed it?

yeah, it was working at one point. loadTime was empty until the page is loaded, so the input was disabled until about:newtab load had finished. feel free to change it

**Comment by bridiver** [comment]
What does the load time show for the new empty tab? https://github.com/brave/browser-laptop/commit/df596983cb3e9a1c8d998ce31b31b9aeb8a78ebf brought the time down from several hundred milliseconds to about 30 and I haven't seen the problem since then

**Comment by bridiver** [comment]
@diracdeltas your change was probably affected by the about "entry" that was added

**Comment by diracdeltas** [comment]
@bridiver i saw the problem today on a 64ms load

**Comment by bridiver** [comment]
I temporarily reverted my change to decrease the newtab load time and the typing wasn't cleared with the locationChanged check enabled
