### ISSUE TITLE
Webview crash when visiting http://homestarrunner.com

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8474]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Webview crash when visiting http://homestarrunner.com
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
Brave	0.15.0
rev	8e63cc0
- Steps to reproduce:
    1. Clean install 0.15.3 / Create a new profile and launch from console
    2. Open  http://homestarrunner.com in a new tab, webview crash 
    3. Open a new tab and close the homestarrunner tab, console shows error
    
- Actual result:
Webview crash when opened http://homestarrunner.com
- Expected result:
Web view should not crash
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![homestarrunner](https://cloud.githubusercontent.com/assets/17010094/25348053/ddf06898-2914-11e7-8818-5599ddd49b04.gif)

- Any related issues:
cc: @bsclifton @bridiver

**Comment by srirambv** [comment]
Added release blocking since this is part of the regression list for each release

**Comment by bsclifton** [comment]
Appears to be Windows only and only happens if Flash is installed.

**Comment by luixxiul** [comment]
On Windows 10 32 bit the issue cannot be reproduced with the latest build: 958aab0. maybe fixed?

**Comment by srirambv** [comment]
Still happens on Win x64 with build https://github.com/brave/browser-laptop/commit/958aab0b1bcd460e9ffdfb7b1fc55d6d9a204b62

**Comment by srirambv** [comment]
+1 on signin.ebay.de. Reported on community  https://community.brave.com/t/ebay-consistently-crashes-brave/2350
Happens on 0.15.0 RC4. Same frown face when page loads.

**Comment by darkdh** [comment]
fixed in https://github.com/brave/muon/commit/ee77b72f264d3a32886a7b516c5089f06a797534
please wait for muon v2.58.7
