### ISSUE TITLE
Upgrade to Node v7.9.0

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8483]
https://github.com/brave/muon/commit/6ac3fa8be47bca5ffa0a0fd848e7051dae1ecbd6

**Comment by luixxiul** [comment]
does this change require update of readme.md?

**Comment by bbondy** [comment]
I think that only lists the minimum version required. I'm not sure if we still work with that minimum or not.  If someone has time to QA it then that'd be great and update as necessary.
