### ISSUE TITLE
Command-W does not close Web Inspector window

### ISSUE THREAD

**Issue by flyswatter** [brave/browser-laptop#8484]
- Describe the issue you encountered:

When I press command-option-J to get the developer tools, I cannot then press command-W to close them.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Mac OS

- Brave Version (revision SHA):

	3de60d5

- Steps to reproduce:
    1. Press command-option-J to get the developer tools.
    2. Press command-W to close them.
    
- Actual result:

The window does not close.

- Expected result:

The window should close.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

I believe so.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

**Comment by Liunkae** [comment]
Root problem: #45

**Comment by Liunkae** [comment]
I think this will be fixed with #45. Closing as a duplicate.
