### ISSUE TITLE
Browser is crashing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8486]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you double click on a item on bookmarks page browser crashes.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
ad18376 crashing on dev-channel as well
- Steps to reproduce:
    1. Open https://brianbondy.com/ and bookmark it
    2. Open about:bookmarks
    3. Double click on bookmarked items
    
- Actual result:
Browser crashes
- Expected result:
Page is opened
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes

## Test was done with a fresh profile and fresh npm install

**Comment by NejcZdovc** [comment]
Now I can't even load a single page

![13](https://cloud.githubusercontent.com/assets/9574457/25396715/e6df148c-29e5-11e7-9f3e-f3b7413f0ec0.gif)

**Comment by NejcZdovc** [comment]
If I clean node_modules again and try npm install it works. Will try to break it again :smile:

**Comment by bsclifton** [comment]
Closing issue for now and removing milestone- please move back into 0.15.0 and re-open if you find steps to cause the crash.  Also- clicking report can be helpful.  @mrose17 saw a crash recently also, which was reported with https://github.com/brave/browser-laptop/issues/8489
