### ISSUE TITLE
Improve handling of switching dat file versions

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8489]
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered: go to a site from the about:preference# payments page

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): [6638b91](https://github.com/brave/browser-laptop/commit/6638b9160590d11deb8d8f57f838a2f4510519dd)

- Steps to reproduce:
    1. run `npm run watch` & `npm start`
    2. go to about:preferences#payments
    3. click on site, e.g., coindesk.com
    4. BOOM
    
- Actual result: crash

- Expected result: new tab with website

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? it's in master & dev-channel

- Can this issue be consistently reproduced? yes

- Extra QA steps: none

- Screenshot if needed:
![0](https://cloud.githubusercontent.com/assets/400552/25402707/6aaf8e0a-29ae-11e7-966e-945e00bd2c69.png)

- Any related issues: none

**Comment by bbondy** [comment]
@mrose17 try clearing your .dat files. I think this is a symptom of switching between dev-channel and master frequently. Let's leave this open though so I can improve that use case.   Basically though your session stores the downloaded adblock version and then it's not actually that version.

**Comment by mrose17** [comment]
deleting the `.dat` files didn't help. i also removed the entire `brave-development/` directory, started the browser, quit the browser, and put my ledger files back, and got a crash... _wow!_

**Comment by NejcZdovc** [comment]
@mrose17  I had the same problem in #8486. What I did:

```
npm clean cache
rm -rf ~/.node-gyp
rm -rf ~/.electron
rm -rf node_modules
```
Cleared `brave-development`, `git pull` and then `npm i`.

Now it's working

**Comment by mrose17** [comment]
_what?!? i don't have to reinstall either node or the OS?..._ (-;

the only step i was missing was the `npm cache clean` and getting rid of `.node-gyp` ... thanks!

**Comment by bbondy** [comment]
actually I just thought of the reason I think you guys got this.

i) install node_modules on master you get ad-block library which expects data files in format v3.
ii) switch to dev-channel, but don't re-install node-modules.  You have front end that looks for data format v2. 

The opposite can happen too if you got he other way.


The way to fix this is to have the library specify the dat file version instead of having it separately defined in front end code.

**Comment by mrose17** [comment]
that makes sense. in this case, the culprit was `.node_gyp` which cached the ad-block library (i delete `node_modules/` often...)

**Comment by bbondy** [comment]
https://github.com/brave/ad-block/commit/85e6b3592f8956b8babb57c2d42a5ad67d88d6cc
