### ISSUE TITLE
Crash (?) on update to Brave 0.7.15 dev

### ISSUE THREAD

**Issue by danielvoicu** [brave/browser-laptop#849]
The browser has updated from 0.7.14 dev, but when it was restarting this error message appeared. Everything seems to be working fine, though, but hopefully this error message can provide some insight into possible crashes or errors that might appear.

**I'm running Brave 0.7.15-dev on Windows 8.1.**

![brave-error](https://cloud.githubusercontent.com/assets/7198550/13201637/36f40c9e-d883-11e5-80b7-21415e08cc0e.png)

**Comment by bbondy** [comment]
I don't think this will happen anymore, so closing this.
