### ISSUE TITLE
If ledger not enabled, honor settings for clearing history

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8495]
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered: if the ledger isn't enabled, then the user's settings for clearing history should be honored

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version (revision SHA): n/a

- Steps to reproduce:
    1. do *not* enable the ledger
    2. visit various sites
    3. go to about:preferences#security and under "Private Data" enable "Browsing history" to be cleared and then quit the browser
    4. *or* go to about:preferences#security and click "Clear Browsing Data Now...", enable "Browsing history" to be cleared
    
- Actual result: ledger-synopsis files are not removed

- Expected result: ledger-files files are not removed

- Will the steps above reproduce in a fresh profile? If not what other info can be added? no, you need to visit some 

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none
 
- Screenshot if needed: none

- Any related issues: #6708 deals with moving ledger-specific settings for sites from site settings to the `ledger-synopsis` file

**Comment by bsclifton** [comment]
Pulling into 0.15.0 since this can speed up load times. PR submitted with https://github.com/brave/browser-laptop/pull/8496

**Comment by mrose17** [comment]
hooray!
