### ISSUE TITLE
Brave 0.7.15 - OS X - Problem with adress bar to go on a website when press "enter" key

### ISSUE THREAD

**Issue by thbtm** [brave/browser-laptop#850]
For exemple, when I write _twitter_, Brave propose me _twitter.com_.

But when I press the "down" key then the "enter" key, nothing is happening instead of going to _twitter.com_

![screen shot 2016-02-21 at 13 38 00](https://cloud.githubusercontent.com/assets/12370868/13202599/a8e2448e-d8a0-11e5-8be7-37be6c0e400b.png)

**Comment by bbondy** [comment]
Thanks for the report, this is fixed here:
https://github.com/brave/browser-laptop/issues/836 
And it'll get it in for Wednesday's release. 

Clicking on the item works for now.
