### ISSUE TITLE
Test are failing on linux

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8506]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Tests are not working on linux
- Platform (Win7, 8, 10? macOS? Linux distro?):
linux, ubuntu 16.04 LTS
![pasted image at 2017_04_26 10_15 am](https://cloud.githubusercontent.com/assets/9574457/25435855/d4297dbc-2a91-11e7-9119-351a6e9f1920.png)

- Brave Version (revision SHA):
8da5411
- Steps to reproduce:
    1.  create a fresh linux VM
    2. install everything needed for running our development (check out versions in the print screen)
    3. run `npm run watch-test` and then in new terminal `npm run test`
    
- Actual result:
![pasted image at 2017_04_26 10_48 am](https://cloud.githubusercontent.com/assets/9574457/25435925/01e96ee2-2a92-11e7-9b37-2d23e4aea737.png)

- Expected result:
Test starts working
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes

**Similar scenario**
When you run `TEST_DIR=about npm run testsuite` you get failing tests which can be find in the first print screen.

**Comment by bbondy** [comment]
@bsclifton this is because  test/taxonomy/exclusionListTest.js uses levelup for taxonomy.  What does this actually test? I don't see it using any module in particular except for levelup.  Maybe we can create a different repo for this? I'll skip it for now and commit.

**Comment by bbondy** [comment]
I think it should either test a module we have or we should just remove the file completely.  If it's just testing leveldown then that should be in a leveldown repo.

**Comment by NejcZdovc** [comment]
@bbondy I deleted the whole `taxonomy` folder and the error is gone, but test's are still failing. Note taxonomy folder is not used in travis.

![image](https://cloud.githubusercontent.com/assets/9574457/25437789/d61a7ba2-2a97-11e7-86f9-a8f01d6f8164.png)

**Comment by bsclifton** [comment]
Thanks for disabling! This is one just to perform quick sanity checks against what is returned when querying leveldb.  We have made mistakes in the past with rules which caused some problems (which then required cleanup).

It would be much better if we had a way to test against the DB directly... but this test is interesting because it'll force the data to get pulled down and then run the test, same as running in-browser would

**Comment by bsclifton** [comment]
More info can be found in https://github.com/brave/browser-laptop/commit/09690a8c08f54f4406559be32749d08582e069f3

**Comment by NejcZdovc** [comment]
this was fixed so closing it
