### ISSUE TITLE
Import data gets duplicated after sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8508]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Import data gets duplicated after sync
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
0.15.0 RC5
6638b91
- Steps to reproduce:
    ~~1. Enable sync on pyramid 0~~
    ~~2. Sync pyramid 1 with pyramid 0 using secret code~~
    ~~3. Import browser data from Firefox and uncheck merge data into toolbar on pyramid 1~~
    ~~4. Wait for the sycn to happen and data is sync'd on pyramid 0~~
    ~~5. Pyramid 1 has two sets of imported data~~

    Edit: Updated the steps
     1. Import chrome data on machine
     2. Enable sync on machine
     3. Import Firefox data, do not merge data
     4. Wait for 3-4 mins firfox folder gets duplicated

- Actual result:
Pyramid 1 gets duplicate data after sync 
- Expected result:
Data should not be duplicated upon Sync
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No. Not checked. Could be a regression issue
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Shared on slack

- Any related issues:
cc: @diracdeltas @ayumi

**Comment by srirambv** [comment]
Actually this doesn't require sync to be done with other system. Just enabling sync causes the import data to be duplicated. gif is a bit long need to watch completely.
![8508](https://cloud.githubusercontent.com/assets/17010094/25447285/7b3c98c2-2aac-11e7-8700-20d2ce0db43f.gif)

**Comment by diracdeltas** [comment]
good catch; i think we just need to set the skipSync flag on imported bookmarks

**Comment by bsclifton** [comment]
Updated to `impact/medium`. I don't believe this was introduced by 0.15.0 and it only affects folks who use sync and import together (which is a much smaller subset than something affecting all users)

I'm going to push to 0.15.1

**Comment by diracdeltas** [comment]
someone should check whether this was addressed by https://github.com/brave/browser-laptop/pull/9187

**Comment by alexwykoff** [comment]
@srirambv if you could ^

**Comment by diracdeltas** [comment]
it may also be fixed by #9406

**Comment by alexwykoff** [comment]
Confirmed fixed. Moving up to 0.17.x
