### ISSUE TITLE
digital rights error

### ISSUE THREAD

**Issue by ddmcnair** [brave/browser-laptop#851]
I was trying to watch something on Amazon Prime.  Two problems occured.  The first is Amazon's site reported the browser as Chrome.  The second is it said there was a Digital Rights Error.

**Comment by Codes4Fun** [comment]
It looks like the widevine cdm plugin needs to be installed, but Chromium, Electron don't have it by default (Brave being based on Electron). It looks like there is a way for Electron to use the Chrome version of the plugin here:
https://github.com/atom/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md
But it looks like they need to be based on the same version which I'm not sure what version Brave is based on.

**Comment by diracdeltas** [comment]
Widevine is being discussed here: https://github.com/brave/browser-laptop/issues/386

**Comment by luixxiul** [comment]
Closing for now.
