### ISSUE TITLE
Error: Setting cookie failed on importing Firefox Data

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8512]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Error: Setting cookie failed on importing Firefox Data

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.0
rev	6638b91
- Steps to reproduce:
    1. Launch browser from console
    2. Import data from Firefox
    3. Console shows `Error: Setting cookie failed `
    
- Actual result:
Error: Setting cookie failed on importing Firefox Data
- Expected result:
Should not show error
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Not checked
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![ffimport](https://cloud.githubusercontent.com/assets/17010094/25449333/637bbe3c-2ab3-11e7-8470-c996d14e2165.gif)

- Any related issues:
cc: @darkdh

**Comment by darkdh** [comment]
Cannot reproduce on 
```
 
Brave: 0.15.0 
rev: 79b14259e3bd27d7ce2f54406c7799bf166b8867 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.14393 
os.arch: x64
```
And cookie is successfully imported from firefox
<img width="1680" alt="screen shot 2017-04-27 at 1 53 03 pm" src="https://cloud.githubusercontent.com/assets/11330831/25497015/1fd05f5a-2b51-11e7-9ddf-58f47355783d.png">
