### ISSUE TITLE
Sync code modal is not dismissed when trying to enable sync offline

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8513]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Sync code modal is not dismissed when trying to enable sync offline
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows x 64
- Brave Version (revision SHA):
Brave	0.15.0
rev	6638b91
- Steps to reproduce:
    1. Open about:preferences#sync
    2. Click on `I have a existing code` to bring the modal 
    3. Enter the sync code
    4. Disconnect system from network
    5. Click on `Setup Sync`
    6. Sync fails but the modal still shows up
    
- Actual result:
Sync code modal is not dismissed when trying to enable sync offline
- Expected result:
Modal should not be shown 
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Not tested
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25450783/eb5d5316-2ab7-11e7-8057-40cc9df87c8a.png)

- Any related issues:
Please change milestone if required

**Comment by diracdeltas** [comment]
kicking to a later milestone since it is an edge case for the network to disconnect while the modal is open

**Comment by alexwykoff** [comment]
migrated to https://github.com/brave/sync/issues/115
