### ISSUE TITLE
Linux version does not handle web push notifications

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#8515]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Linux laptop version does not handle server push notifications
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Slackware 14.current
- Brave Version (revision SHA):
6638b91 (and many previous)

- Steps to reproduce:
    1. Go to https://serviceworke.rs/push-payload_demo.html
    2. Attempt to send notification
    3. Devtools says "Uncaught (in promise) DOMException: Registration failed - push service not available"
    
- Actual result:
No response to push notifications.
- Expected result:
Receipt of push notifications.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by capouch** [comment]
I can confirm that push notifications work properly in brave-core.  Thanks!!

**Comment by bsclifton** [comment]
Awesome, thanks for confirming, @capouch 😄
