### ISSUE TITLE
 imdb.com video player only loads with blocking disabled

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8521]
@darkdh reported that imdb.com was not loading the video player: 

![image](https://cloud.githubusercontent.com/assets/8979240/25467324/47c5f0ea-2ac2-11e7-97f5-f6d2b40aba19.png)

- I've been able to repro on win10. 
- imdb appears to be loading the video player, only if the ad call is allowed to be made. 
- Blocking ads prevents the player from loading. 
- Disabling blocking allows for the player load as expected. 

- [ ] Confirm that this code is blocking the player: 

```
doWithAds(function(){
if ('injected_slot' == 'injected_slot') {
ad_utils.inject_ad.register('injected_billboard');
} else {
ad_utils.gpt.render_ad('injected_billboard');
}
}, "ad_utils not defined, unable to render client-side GPT ad or injected ad.");
```
- [ ] Locate corresponding ad call in network traffic. 
- [ ] Find appropriate exception
- [ ] Apply Solution
- [ ] Confirm fix
- [ ] Close issue

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/902
