### ISSUE TITLE
uitest script is not available in package.json, but it's mentioned in tests.md

### ISSUE THREAD

**Issue by kumarrishav** [brave/browser-laptop#8523]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
https://github.com/brave/browser-laptop/blob/master/docs/tests.md say, to run uitest, use : `npm run uitest` but there is no script available regarding uitest in package.json

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS (probably All)
- Brave Version (revision SHA):
Brave 0.15.0 (revision `d1fc13c`)

- Steps to reproduce:
    1. execute `npm run uitest`
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
@kumarrishav nice find :-)
