### ISSUE TITLE
About history failing tests

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8524]
**Describe the issue you encountered:**

This tests are failing for me locally.

Steps:
1) `npm run watch-test`
2) `TEST_DIR=about npm run testsuite`

1) about:history page content does NOT use customTitle when displaying entries:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) about:history page content defaults to sorting table by time DESC:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) about:history page content "after all" hook:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) about:history multi-select behavior selects multiple rows when clicked with cmd/control:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  5) about:history multi-select behavior selects multiple contiguous rows when shift clicked:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  6) about:history multi-select behavior deselects everything if something other than the table is clicked:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  7) about:history multi-select behavior does not lose selection if table is sorted:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  8) about:history multi-select behavior "after all" hook:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

**Additional info**
We notice some lag as well on ledger. I am thinking that about pages has some lag. Maybe related to  this commit https://github.com/brave/browser-laptop/commit/7168987205d567c297470a175038af4e03cc1ded. I notice that when opening history tab CPU spikes and interaction is laggy (hover has a big delay, click as well). @bridiver what do you think?

![13](https://cloud.githubusercontent.com/assets/9574457/25479006/a697a3d0-2b43-11e7-9af6-a50afa51d981.gif)

**Comment by NejcZdovc** [comment]
@luixxiul @srirambv do you see this lag as well on the latest master?

**Comment by alexwykoff** [comment]
I think these will be covered by our new intermittent retest CI

**Comment by alexwykoff** [comment]
we have this tracked in source control and in chat
