### ISSUE TITLE
Strange cursor behaviour when hovering over searchbar

### ISSUE THREAD

**Issue by Skayo** [brave/browser-laptop#8536]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When hovering from top to bottom of the searchbar, the cursor changes to the input cursor then to the normal cursor and then to the input cursor again:
![](https://i.imgur.com/KBvXDR7.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Creators Update

- Brave Version (revision SHA):
Brave: 0.15.0 
rev: 71fb73001617949528cc6473e288a49e76fcd4d5 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.15063 
os.arch: x64

- Steps to reproduce:
(Do it like in the GIF above)

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
I don't exactly know...

- Screenshot if needed:
Above.

**Comment by bsclifton** [comment]
@Skayo are you using a laptop? if so, do you have trackpad input enabled? Almost looks like a problem with the trackpad or mouse

**Comment by Skayo** [comment]
@bsclifton Yes, I am using a laptop and trackpad input is enabled. Doesn't happen in Chrome nor Edge. (I don't have Firefox)
I don't think I have a problem with my trackpad or mouse but I will check tomorrow.

**Comment by josiah-keller** [comment]
@bsclifton I've noticed this for some time.  I think it's the same issue as #7641.  It doesn't happen when the window is not maximized.

**Comment by jonathansampson** [comment]
@bsclifton I agree with @josiah-keller here; looks like the same issue I see on my hi-res Surface Book.
