### ISSUE TITLE
Add "Clear Data / Reset Ledger" option to about:preferences#payments and 'Clear browsing data...' panel

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8537]
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered: about:preferences#sync has an option to let the user completely erase the sync data; we need a similar option for the ledger

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version (revision SHA): n/a

- Steps to reproduce:
    1. go to about:preferences#payments
    2. look for a "Reset Ledger" option
    3. look in about:preferences#security and in History > 'Clear Browsing Data...' for a 'Clear payments' option
    
- Actual result: you won't find it

- Expected result:
  * clicking on the button in 'about:preferences#payments' will result in one of two popups:
  1. if the balance of the wallet is zero, then it should look like the popup for "Reset Sync"
  2. otherwise, the user should be given the option of "Yes", "Keep wallet", or "Cancel"
  * clicking on the switch in the Clear Browsing Data panel will clear the ledger synopsis (and payment history?)

- Will the steps above reproduce in a fresh profile? no, If not what other info can be added? you have to enable the ledger first

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none

- Screenshot if needed: n/a

- Any related issues: tangentially related to #6708

Note to @bsclifton and @NejcZdovc:
  1. to do a complete reset, set `settings.PAYMENTS_ENABLED` to false and then call `reset`
  2. a partial reset ("Keep wallet") is actually pretty easy to do, let me know when we're ready to implement that, thanks!

**Comment by diracdeltas** [comment]
I have personally gotten 2 reports from people who think that payments should be cleared when 'Clear History' is clicked. I'd also expect this behavior. Is there a reason not to do that?

**Comment by diracdeltas** [comment]
Alternatively, it might be good enough to just have a 'Clear payments data' switch in about:preferences#security and in History > 'Clear Browsing Data...'

**Comment by mrose17** [comment]
that works for me.

**Comment by diracdeltas** [comment]
Specifically i think the switch in the Clear Browsing Data panel should only be for clearing synopsis, not resetting the wallet. The button in 'about:preferences#payments' should offer the option to reset the wallet, however.

**Comment by bradleyrichter** [comment]
Here is the proposed switch position and string:

![image](https://user-images.githubusercontent.com/13509546/29423327-282bc7ca-8330-11e7-819c-48dee7c415d6.png)

The switch follows the normal switch implementation but adds the (?) button at the end which will lead to a git hub wiki page that explains how the data is recorded separately from history as needed by the ledger system.

cc: @mrose17 cc: @diracdeltas

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.22.723 edb3e88
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
* Verified publisher removed via the clear history is getting re-added
* Verified the settings is disabled when contribution is  in progress
