### ISSUE TITLE
Can not delete/moving/edit bookmark with chrome-extension:// in the URL location

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#8538]
- Did you search for similar issues before submitting this one?
No

- Describe the issue you encountered:
I accidently have two bookmarks with `chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/` added in the url location -- the url in the location looks like `chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/http://your-site.com/your_file.pdf.` And now I can not delete those bookmarks or moving the bookmarks to other folder. Also, If I edit the bookmarks and erase the `chrome-extension://` from the location, it will create new bookmark instead of updating the old one.

- Platform (Win7, 8, 10? macOS? Linux distro?):
win8.1

- Brave Version (revision SHA):
0.15.0 (71fb730)

- Steps to reproduce:
    1. Open pdf file from any site
    2. Bookmark the pdf file
    3. Make sure `chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/` added in the url
    4. Try to delete, moving, or edit bookmark
    
- Actual result:
Can not edit nor delete the bookmarks

- Expected result:
User can edit/delete the bookmarks

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes, but I noticed this in the older version (0.14.1dev) too

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-bookmark-bug](https://cloud.githubusercontent.com/assets/25360853/25506092/2149c636-2bcf-11e7-8290-2338e5c17b4e.gif)

- Any related issues:

**Comment by Liunkae** [comment]
I cannot reproduce with Brave 0.15.0 on macOS 10.12.x because it won't let me manually add `chrome-extension://` to the bookmark's URL. When I bookmark a PDF, it does not start with `chrome-extension://`.

**Comment by eljuno** [comment]
Well, I'm not sure why I can do that. It seems I bookmark the pdf before it loaded completely -- slow connection -- and ended up with `chrome-extension://` in the bookmark URL. It's OK if there's not solution for me to delete those bookmark. I can live with it. :)

**Comment by Liunkae** [comment]
@eljuno It's still a bug. 😉

**Comment by eljuno** [comment]
@Liunkae all I know so far:
Brave load pdf as `chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/` before the URL change to `http://your-site.com/your_file.pdf`. And I bookmark the pdf when still load and ended up with what I said ealier.

![brave-bookmark-pdf-bug](https://cloud.githubusercontent.com/assets/25360853/25559140/9d4ae972-2d5f-11e7-9530-c2d5b4fad9fd.gif)
