### ISSUE TITLE
Give a warning prompt when closing a window 

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#854]
Requested from twitter:
https://twitter.com/Ed_Realist/status/701614421672525824

Would you like to close all tabs? 
[ ] do not show this again

**Comment by luixxiul** [comment]
Similar request: Alert when close a Specific Tab
https://community.brave.com/t/alert-when-close-a-specific-tab/267?u=suguru

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/775
