### ISSUE TITLE
When Brave Payment is enabled, accessing Shield Settings on a blank page will crash the browser

### ISSUE THREAD

**Issue by onmyouji** [brave/browser-laptop#8545]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When Brave Payment is enabled, accessing Site Shield Settings on a blank page will crash the browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7

- Brave Version (revision SHA):
0.15.0

- Steps to reproduce:
    1. Enable "Brave Payments"
    2. Open a blank page (about:blank)
    3. Open "Site Shield Settings" from the menu
    
- Actual result:
Brave crash

- Expected result:
Shouldn't crash the browser. I've tested the above scenario with "Brave Payment" disabled, it doesn't crash.

- Will the steps above reproduce in a fresh profile? 
Yes, I've uninstalled and reinstalled Brave.

- Is this an issue in the currently released version?
Yes, the latest one, 0.15.0

- Can this issue be consistently reproduced?
Yes

**Comment by alexwykoff** [comment]
about:blank simply shows a spinner on the tab and never completes, thus the shields menu is inaccessible.
