### ISSUE TITLE
Force Close in Some websites

### ISSUE THREAD

**Issue by iowbeoibewio** [brave/browser-laptop#8549]
- Did you search for similar issues before submitting this one?
Yes, I did

- Describe the issue you encountered:
Brave Force Close immediately in some websites and I don't know why.
And here one website an example that makes Brave FC
https://www.aliexpress.com

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.4

- Brave Version (revision SHA):
 
Brave: 0.15.0 
rev: 71fb73001617949528cc6473e288a49e76fcd4d5 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.5.0 
os.arch: x64

- Steps to reproduce:
    1. I tried to disable Brave Shields.
    
- Actual result:
Force Close

- Expected result:

- Is this an issue in the currently released version?
Yes, I Start using Brave since 0.13.5 and through 0.15.0, and the problem still exist.

- Can this issue be consistently reproduced?
Not that I've been able to figure out.

- Screenshot if needed:
<img width="435" alt="screen shot 2017-04-28 at 3 05 23 pm" src="https://cloud.githubusercontent.com/assets/23007602/25528106/bbe510d8-2c24-11e7-97d3-467bb31febc6.png">

- Any related issues:
No

**Comment by bsclifton** [comment]
@iowbeoibewio I'm having a hard time trying to reproduce this... it seems to work everytime for me

It seems you've had this problem for a while?  Next time you get the problem, can you hit the report button? It should show a VERY detailed report.  You can copy/paste those details to here:
https://gist.github.com/

And then share a link with us 😄  This should help us narrow it down.  Thanks! 😄

**Comment by iowbeoibewio** [comment]
Here link for report :smile: 
https://gist.github.com/iowbeoibewio/10b7eec545317eab04c1334068ed6a8b

**Comment by bsclifton** [comment]
@iowbeoibewio this is great!

cc: @darkdh @bbondy @bridiver 

Is this squirrel related? See https://gist.github.com/iowbeoibewio/10b7eec545317eab04c1334068ed6a8b#file-force-close-report-L1742

**Comment by iowbeoibewio** [comment]
Any new?

I tried in Windows 7 64 bit, Brave Version 0.17.13
and the problem still exist

An example:
if you check this link and below video click Openload button, the browser will be close immediately.
https://ww2.animelek.com/anime/watch-online/yu-gi-oh-vrains-8-100774.html

**Comment by iowbeoibewio** [comment]
I tried to figure the problem by my self

and I figure the problem in "PDF Viewer" extension, if you DISABLE this extension you will had Force Close in some websites!

If you ENABLE "PDF Viewer extension, you will not have any Force Close!!

An example:
Disable "PDF Viewer", in link below click Openload button, the browser will be close immediately.
https://ww2.animelek.com/anime/watch-online/yu-gi-oh-vrains-8-100774.html

try again with "PDF Viewer" Enabled, NO FORCE CLOSE

++
Outside topic, in MacOS Brave 0.17.3 >> PDF Viewer version is 1.6.387
in Windows Brave 0.17.3 >> PDF Viewer version is 1.8.252

**Comment by iowbeoibewio** [comment]
PDF Viewer extension update automatically in macOS to version 1.8.252

and the problem still happening, unless you Enabled PDF Viewer extension

**Comment by luixxiul** [comment]
Closing in favor of https://community.brave.com/t/discussion-brave-force-quits-on-osx-on-aliexpress-com/10052
