### ISSUE TITLE
No progress indicator when reloading page

### ISSUE THREAD

**Issue by jpretori** [brave/browser-laptop#8550]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
It's a User Experience issue:  I don't see any indication that a page is loading, while it's loading.  I'm sure there's supposed to be a progress indication someplace, but it's either not working or escaping my attention.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac OS X 10.11.6

- Brave Version (revision SHA):
71fb730

- Steps to reproduce:
    1. Open browser (I've been using it for a number of days, and usually just close the laptop's lid as opposed to shutting down)
    2. Open some website.  
    3. Hit Cmd+r.  Multiple times fi you want.  
    
- Actual result:
I NEVER get a progress indication anywhere.

- Expected result:
Visible indication that the browser has received and understood my keystroke, and that it's now performing some progress - i.e. I can wait for it to complete as opposed to repeating my keystroke.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I'm not sure I know what this question means.  I've only been using Brave for a week or so, but don't remember this being an issue before - if that helps.

- Is this an issue in the currently released version?
Yes, I updated recently (yesterday?  I can't remember exactly)

- Can this issue be consistently reproduced?
On _my_ machine... every time.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@cezaraugusto can you check this one out? Def seems like a regression

**Comment by jaredbeck** [comment]
I've noticed that the circular arrow changes to an X, indicating that the browser is waiting for an HTTP response, but I agree that's not much of a visual indication of loading. I would also prefer a more obvious visual indication.
