### ISSUE TITLE
Tear off tabs: Early reports re: unintentional tab tear off, and responsiveness

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8553]
Received a report from a Community contributor that tabs are tearing off 50% of the time when they attempt to click to make the tab active. 

Gathering additional info, but it sounds like it could be that the click and drag to tear off might be a little too sensitive for the user's browsing profile. 

**Brave Community URL:**
https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/1

**Community contributor feedback:**

**Contributor 1**
**Browser Profile: **
```
Name: Version
Brave: 0.15.0
rev: 71fb730
Muon: 2.58.7
libchromiumcontent: 58.0.3029.81
V8: 5.8.283.32
Node.js: 7.9.0
Update Channel: dev
os.platform: win32
os.release: 10.0.15063
os.arch: x64
```

**Feedback**
>*So ever since the latest update (maybe two days ago?), when I click an already open tab I have about a 50/50 chance of that tab moving to its own window. I cannot find a way to disable this. I don't want multiple windows, that's why tabs are a thing.*
>
>*It is very annoying, and very new.*
>
>*I'm not double clicking, my mouse button isn't sticky, this only happens in brave. Click on a tab to switch to it and it magically poofs into a new window.*
>
>*I'm not sure if this is an isolated issue or a bug since the update. But if its a bug, you guys should know.*
>
>*It happens no matter where I click in the tab. I'm not clicking and dragging, and it doesn't happen when I double click. Sometimes I'll just single click a tab and it will tear off.*

**Contributor 2**
**Browser Profile**
```
awaiting profile data
```

**Feedback**
>*I've also noticed that it's not very responsive. When using a trackpad to click on the close button of windows, I often accidentally drag down a bit. 
>On Chrome, it would stick to the tab bar for a bit, and would only tear off once pulled a bit further down. 
>
>On Brave it tears off almost immediately, which makes closing tabs quite annoying.*

**Comment by lukemulks** [comment]
cc: @bbondy for visibility

**Comment by lukemulks** [comment]
@bbondy, 
I've attempted to reproduce from Win10 (64bit) with the v0.15.1 update, and have been unable to repro the issue. 

To cover off, I've gone back to the Community thread where this was originally reported, and have checked to see if the contributors that reported the issue can test in 0.15.1 and report the results. 

**Community post (jumps to the latest request):**
https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/9

There were also two reports on the same thread regarding the order of pinned tabs, which I've requested the contributors test with v0.15.1. (issue https://github.com/brave/browser-laptop/issues/8543)

I'll report back with an update here once I receive a response from the Community.

**Comment by lukemulks** [comment]
@bbondy I received feedback from the contributors in the Brave Community that I asked to re-test with v0.15.1. 

Community URL: https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/12

Confirming that:
- Tearoff sensitivity has been reported as greatly improved with 0.15.1
- Unintentional Tearoff on click has been reported as resolved with 0.15.1

One contributor also replied with the following suggestion, in addition to confirming that the issue is resolved:

>*Tear off sensitivity is way better, thanks for that! Reordering tabs seems a bit better, but now when dragging tabs to the right, (past the + button) it tears off. What I was trying to say previously, is that if you drag too far right, it should become the rightmost tab, instead of doing nothing (or now tearing into a new window).*
>
>*Some kind of smooth tab reordering like on Chrome or Firefox would be nice, even if it's an optional setting.*

Since I have been unable to reproduce, and we have had positive confirmation following testing with 0.15.1, I am going to close out this issue. Thanks!

**Comment by srirambv** [comment]
@lukemulks  I have experienced this issue couple of times but it is not very easy to reproduce. I believe its due to the click not being recognised and recorded as drag. This issue of click not being recognised is found on another issue with bookmarks as well. Mentioned here https://github.com/brave/browser-laptop/issues/7414#issuecomment-283618306. (see the gif which records the click event). I experienced this on 0.15.1 as well. Can continue discussion on the closed out issue itself.

**Comment by lukemulks** [comment]
Interesting, thanks. I have not been able to reproduce, and the other two
contributors that originally reported the issue had confirmed that the
v0.15.1 update resolved the issue for them.

Will take a look at the issue you mentioned and see if I can repro. Thanks!

**Comment by IPmev12** [comment]
I have this issue all the time, I am constantly accidently seperating a tab into a new window and then when I attach that tab back to the original window two things may happen.

1. I can click on and use the other tabs but not the one I just reattached

2. I can no longer click any of the tabs and have to end task

Brave	0.17.13
rev	f7242c7
Muon	4.1.7
libchromiumcontent	59.0.3071.109
V8	5.9.211.38
Node.js	7.9.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64
