### ISSUE TITLE
Show definition popup is misaligned

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#8554]
## Test plan
 1. Ensure Bookmarks Toolbar is hidden
 2. Select a word on a webpage.
 3. Right-click > Look Up or use the three finger tap gesture (trackpad).
 4. Make sure the popup is just below the word that was selected
 5. Repeat steps 2 - 4 with Bookmarks Toolbar being visible

## Original issue description
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If you click Look Up or use the three finger gesture to show the dictionary definition of a word, the popup is misaligned.

The location of the popup depends on:
1. The method used to show the definition: Look Up menu item or three finger gesture.
2. Whether the bookmarks toolbar is visible.

This leads me to believe it's a screen coordinate issue introduced with the switch to Chromium 58.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x (macOS only)

- Brave Version (revision SHA):
0.15.0 (71fb730)

- Steps to reproduce:
    1. Select a word on a webpage.
    2. Right-click > Look Up or use the three finger (trackpad) gesture.
    
- Actual result:
The popup is misaligned (see screenshots).

- Expected result:
The popup should appear below the word.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Probably, but I haven't tested.

- Is this an issue in the currently released version?
Yes, 0.15.0.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Select a word on a webpage.
    2. Right-click > Look Up or use the  three finger tap gesture (trackpad).
    3. Make sure the popup is just below the word.

- Screenshot if needed:
# With three finger gesture
Without bookmarks toolbar (hidden):
![](https://cloud.githubusercontent.com/assets/19424103/25540383/78bb78ba-2c10-11e7-9720-c78359ea0ba5.png)
With bookmarks toolbar visible:
![](https://cloud.githubusercontent.com/assets/19424103/25540433/96149608-2c10-11e7-94c9-02c6b13b7f14.png)

- Any related issues:
None.

**Comment by luixxiul** [comment]
+1 from #10728

**Comment by luixxiul** [comment]
Closing for QA.

**Comment by Liunkae** [comment]
FYI, I think it was fixed with Chromium 64, so it might be fixed in the 0.19.x hotfix 13 soon to be released.

**Comment by bsclifton** [comment]
I suspect that the underlying fix for this also caused this issue:
https://github.com/brave/browser-laptop/issues/12652

**Comment by LaurenWags** [comment]
Still doesn't seem quite right:
![8554](https://user-images.githubusercontent.com/28145373/35069824-5b20b45a-fba9-11e7-8a07-10670963cf02.gif)

**Comment by bsclifton** [comment]
@LaurenWags I think the issue you found is different- it looks to have unintentionally selected the wrong words? The actual alignment seems to be fine.  Seems to be when you click and drag (to create a selection) versus double clicking a word

Closing this issue as the alignment is fixed- would you mind creating a new issue for that? 😄

**Comment by LaurenWags** [comment]
Opened https://github.com/brave/browser-laptop/issues/12695 for https://github.com/brave/browser-laptop/issues/8554#issuecomment-358465530
