### ISSUE TITLE
No History option?

### ISSUE THREAD

**Issue by EdRealist** [brave/browser-laptop#856]
In twitter, Brendan mentioned that I should do a recover previous whatever, and said I could "See History / Reopen Last Closed Tab and History / Reopen Last Closed Window. All undoable."

I don' have any of those options in the right hand bars option at top. If they're elsewhere, I don't see it. Sorry if this is stupid.

**Comment by diracdeltas** [comment]
We are working on adding history options. Reopen Last Closed Tab exists already though - go to the History menu at the top or press Cmd + Shift + T

**Comment by EdRealist** [comment]
That's what I'm saying--I don't have the history menu--or if I do, I can't
see I t.

On Mon, Feb 22, 2016 at 5:56 PM, yan zhu (@bcrypt) <notifications@github.com

**Comment by diracdeltas** [comment]
I meant the menu at the top of the window, not the menu in the right hand side of the browser. Do you see something like this?

![screen shot 2016-02-22 at 7 10 50 pm](https://cloud.githubusercontent.com/assets/549654/13240526/0b946d94-d998-11e5-8528-0f73512021e9.png)

**Comment by EdRealist** [comment]
No. Here's what my top looks like
[image: Inline image 1]

On Mon, Feb 22, 2016 at 7:11 PM, yan zhu (@bcrypt) <notifications@github.com

**Comment by EdRealist** [comment]
Here's what preferences looks like

[image: Inline image 1]

**Comment by EdRealist** [comment]
No rush on any of this; sorry if I'm being stupid. But I don't have
anything cross the top. Windows.

**Comment by diracdeltas** [comment]
Those images aren't showing up I think; could you please attach them in a github comment? Thanks

**Comment by bbondy** [comment]
To get the top level menu in windows programs just hit the `Alt` key.

**Comment by bbondy** [comment]
Closing for now since this was just a question, if it's not resolved pls reopen.

**Comment by EdRealist** [comment]
Very sorry for not getting back sooner. Thanks for the Alt tip--I didn't
know about that!
