### ISSUE TITLE
Missing link on About Brave page

### ISSUE THREAD

**Issue by tjayrush** [brave/browser-laptop#8561]
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

There is a broken link on the About Brave page.

**- Steps to reproduce:**
    1. Click on the link in the about brave page

**- Actual result:**

No Page

**- Expected result:**

Page

**- Can this issue be consistently reproduced?**

Yes

**Comment by Liunkae** [comment]
@tjayrush Which link? The `here` and `71fb730` links are working for me.

**Comment by luixxiul** [comment]
I could reproduce the issue. If I click "here", the page https://github.com/brave/browser-laptop/releases/tag/vundefineddev is opened, which is 404.

**Comment by Liunkae** [comment]
@luixxiul Which platform? I cannot reproduce on my personal instance or a new profile on macOS 10.12.x, or my test instance on Linux Ubuntu 16.04.x.

**Comment by luixxiul** [comment]
on Windows 10 64 bit.

You would need to change the language setting to other than English.

**Comment by Liunkae** [comment]
Hmm, still can't reproduce even if I set the language to something other than English.

**Comment by luixxiul** [comment]
I could no longer reproduce the issue.

**Comment by bsclifton** [comment]
@luixxiul can you try setting `NODE_ENV=development` and running? I have a feeling that maybe when you ran it, that was set.  When that happens, it will try to do a lookup (which might fail)- then the page may be blank or have a broken link

**Comment by luixxiul** [comment]
Closing as stale. let's reopen this if we see the issue again.
