### ISSUE TITLE
Add BrowserButton component

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8568]
Doing #7168 (refactor of Button component) I had to refactor +30 files and some of them found to be near impossible without breaking things or refactoring the whole component.

The idea with this new component is to avoid breaking changes and refactor buttons that already have Aphrodite embedded, and let the road open for future refactoring, since it mimics `<Button>` component.

Added some new spec for better developer experience:

* White button name was replaced with `secondaryColor`, this way we make colors future-friendly with upcoming dark mode and theming options since not necessarily it will be white.
* Buttons are now made by using `<BrowserButton primaryColor />` instead of manually adding a class
* Custom classes are labelled as `custom`, and only accept Aphrodite classes, and only as plain objects (no need for `css()`):
```jsx
<BrowserButton custom={styles.something} />
// or
<BrowserButton custom={[styles.something, styles.anotherSomething]} />
```

**Comment by luixxiul** [comment]
LGTM though not every possible case is not covered
