### ISSUE TITLE
Panopticlick Brave Fingerprint 

### ISSUE THREAD

**Issue by rnsjunkmail** [brave/browser-laptop#8577]
- Did you search for similar issues before submitting this one? Yes
- Describe the issue you encountered: Panopticlick rates Brave with a VERY unique Fingerprint!!!
- Platform (Win7, 8, 10? macOS? Linux distro?):   MacOS X El Capitan 10.11.6
- Brave Version (revision SHA): 0.15.0 rev 71fb730

- Steps to reproduce:
    1. Go to Panopticlick website
    2. Run the test
    3.
    
- Actual result: 

Does your browser protect from fingerprinting?	✗ , NO!!! your browser has a unique fingerprint

Your browser fingerprint appears to be unique among the 218,805 tested so far.

Currently, we estimate that your browser has a fingerprint that conveys at least 17.74 bits of identifying information.

Browser                    bits of identifying            one in x browsers 
Characteristic		      information	           have this value                          value
Limited                                                                                                     DOM localStorage: Yes, 
supercookie                        0.37                               1.29                        DOM sessionStorage: Yes, 
test	                                                                                                          IE userData: No

Hash of canvas              7.11                                137.96
fingerprint	

Screen Size                       5.28                            38.95
and Color Depth	

Browser Plugin                 1.53                             2.89                       undefined
Details	

Time Zone	                3.55                              11.69

etc...

- Expected result: That Brave Protects from Fingerprinting better than other browsers

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/5975#issuecomment-264524964
> panopticlick is based on the number of users who visit EFF's site, so it's definitely skewed. if you visit the site over and over again in new incognito tabs, it no longer says you're fingerprintable.
