### ISSUE TITLE
Clicking PDF link crashes tabs dramatically

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#8579]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Lately, clicking some PDF links crashes both the tab attempting to render the PDF as well as the tab(s) that spawned it.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Slackware 14 x64
- Brave Version (revision SHA):
0.15.0 	71fb730
- Steps to reproduce:
    1.Click this link: https://electron.atom.io/apps/
    2.Scroll to listing for "Cove PDF" and click link
    3.On CovePDF page, scroll to bottom
    4. Click "Product Overview" crashes both tabs
    
- Actual result:
Cascading crash
- Expected result:
Rendering of PDF document
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes.  I can provide other workflows with the same result.
- Screenshot if needed:

- Any related issues:
I try to run latest releases; this began about 2 weeks ago.  Some PDFs render fine but others cause this behavior.
![covepre-crash](https://cloud.githubusercontent.com/assets/5156230/25558533/db4dbeb6-2cf6-11e7-801c-64f2a3dd0bdc.png)
![covecrash2](https://cloud.githubusercontent.com/assets/5156230/25558536/e7c36dc6-2cf6-11e7-946a-fd67e088943b.png)

**Comment by bbondy** [comment]
Verified fixed by this:
https://github.com/brave/browser-laptop/issues/8422
