### ISSUE TITLE
In page translation using MS Translator

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#858]

**Comment by alexwykoff** [comment]
Prioritizing to 1.2 so it is not forgotten. If we can't implement ANY translator by then, we should assign to a future milestone, but this is a feature which will be missed by a fair percentage of users.

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/possibility-to-recognize-and-send-non-english-text-to-translate/6106

**Comment by srirambv** [comment]
+1 from community for non-Google translator
https://community.brave.com/t/non-google-translator/7435/2

**Comment by bsclifton** [comment]
+1 from @briannyeko via https://github.com/brave/browser-laptop/issues/10949

**Comment by solarjakee** [comment]
Any news of this? This would really make Brave much more viable for me as my main browser if you were able to implement it.

Sorry if I'm posting in the wrong place!

**Comment by unknownids** [comment]
Any news on this?

**Comment by srirambv** [comment]
Is this going to be fixed by fork? @bbondy @bsclifton

**Comment by bsclifton** [comment]
@srirambv Brave Core won't fix this immediately- we'd need to do some additional integration. I think it's safe to say that any development would happen in Brave Core and not browser-laptop

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/208
