### ISSUE TITLE
Unable to view HBOGO video

### ISSUE THREAD

**Issue by Samizdata** [brave/browser-laptop#8581]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Unable to use HBOGO viewer.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10.
- Brave Version (revision SHA):
0.15.0, 71fb730
- Steps to reproduce:
    1. Try loading a video with shields up.
    2. Try loading a video with shields down.
    
- Actual result:
1. Be informed Flash is not installed.
2. Be informed there is an HDCP issue exists.
 
- Expected result:
Watch a video.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
None

- Screenshot if needed:
http://imgur.com/ddKEaWf

**Comment by darkdh** [comment]
for me it is a flash issue


[Kapture 2017-05-03 at 12.55.00.mp4.zip](https://github.com/brave/browser-laptop/files/974552/Kapture.2017-05-03.at.12.55.00.mp4.zip)

**Comment by luixxiul** [comment]
@alexwykoff @LaurenWags would you please confirm this has been fixed as you can access the site only from US. thanks!

**Comment by Samizdata** [comment]
Well, FWIW, I can confirm it is NOT fixed as when I visit the site and try to load a video, it tells me "Can't play video.  The latest Flash needs to be installed and enabled in your browser" and never offers me an option to start it.  Neither can I get any response on homestarrunner.com.

So I am going to put that down as a NOT WORKING AT ALL.  In fact, at this point I am not even able to get the previous error about DRM failure, so it is looking like a step backwards at this point.
On 6/21/2017 1:11:09 AM, Suguru Hirahara <notifications@github.com> wrote:
@alexwykoff [https://github.com/alexwykoff] @LaurenWags [https://github.com/laurenwags] would you please confirm this has been fixed as you can access the site only from US. thanks!

**Comment by luixxiul** [comment]
maybe this is a silly question but do you try that on the latest preview, 0.17.4?

**Comment by Samizdata** [comment]
Mkay, will be willing to try, but I am not sure how to change to that channel for updates.
On 6/21/2017 3:50:04 AM, Suguru Hirahara <notifications@github.com> wrote:
maybe this is a silly question but do you try that on the latest preview, 0.17.4?

**Comment by LaurenWags** [comment]
Checked using http://www.hbo.com/watch-free-episodes as I don't have HBOGo credentials.

**Comment by Samizdata** [comment]
Well, I can now get as far as trying to start a video, but we are right back at the HDCP error I originally reported.  I don't see this error anywhere but Brave.

**Comment by Samizdata** [comment]
Tried again tonight.

No go.

Any suggestions?

Screenshot: http://i.imgur.com/JJ0jSSD.png

**Comment by Samizdata** [comment]
Brave	0.18.14
rev	ad92d02
Muon	4.3.6
libchromiumcontent	60.0.3112.78
V8	6.0.286.44
Node.js	7.9.0
Update Channel	dev
OS Platform	Microsoft Windows
OS Release	10.0.10586
OS Architecture	x64

Tested tonight after upgrade.  Still stuck on the HDCP error as listed on previous screen shots.  As I mentioned previously, the issue does not happen in Firefox (which I REALLY want to get rid of at some point) so I am pretty sure it is not my hardware.

**Comment by darkdh** [comment]
@Samizdata , did you try Chrome to see if the HDCP error occurs?

**Comment by Samizdata** [comment]
@darkdh Admittedly I hadn't tried it for a while, but I just tested and it worked without a hitch.

**Comment by Samizdata** [comment]
Also, FWIW, it has always worked in Firefox.

**Comment by bsclifton** [comment]
@Samizdata it's working in Chrome or Brave?

**Comment by Samizdata** [comment]
@bsclifton Sorry.  It is working in Chrome and Firefox, but **NOT** in Brave, nor has it ever.

**Comment by Prodicy** [comment]
Has anyone had any improvements on this issue? Having the same situation where HBO plays correctly on chrome with no errors, but gives the HDCP error on brave...

**Comment by Samizdata** [comment]
Not that I have seen.  And I need to look to see if it is already submitted, but Netflix has started throwing playback errors.  Don't remember the error right now, but it seems linked to issues with WideVine.

**Comment by NejcZdovc** [comment]
@Samizdata you can read more about it here #10449. We are working hard to fix this

**Comment by Samizdata** [comment]
Thanks for the heads up!

**Comment by Brave-Matt** [comment]
+1 from reddit: https://www.reddit.com/r/brave_browser/comments/93jiac/hbo_website_still_wont_play_video/
