### ISSUE TITLE
about:blank loads indefinitely

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8584]
Seems to have started with 0.15.0... @alexwykoff reports it worked fine with 0.14.2 (should help narrow down the cause)

Loading about:blank (either typing and hitting enter or setting about:blank as your home page and then setting new tab to open home page) causes the spinner to keep going

The page seems to have loaded fine; it just thinks it hasn't finished

**Comment by bbondy** [comment]
cc @bridiver in case this is fixed with new event handling he's working on.

**Comment by bsclifton** [comment]
This appears to be fixed now 😄  (I don't know which commit fixed it; cc: @bridiver)
