### ISSUE TITLE
Fix tests for Sync

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8585]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
According to https://github.com/brave/browser-laptop/pull/8556 the release criterion is that tests should pass. Currently they consistently fail on two particular tests:

```
   1) Syncing then turning it off stops syncing "before all" hook:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getUrl() - brave.js:266:40

  2) Syncing then turning it off stops syncing "after all" hook:
     undefined: Cannot read property 'startsWith' of null
      at getUrl() - brave.js:241:40
```

The brave.com page doesn't fully load and the test fails to connect to the selenium server. 

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
i think @ayumi is already working on this

**Comment by diracdeltas** [comment]
^ https://github.com/brave/browser-laptop/pull/8539
