### ISSUE TITLE
"Recently closed tabs" disappeared from the menu

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8586]
**Describe the issue you encountered:**
1. Click the History menu
2. There is no item named "Recently closed"

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10, confirmed on Debian

- Brave Version (revision SHA): 0.15.1

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
I'm seeing this in master- not sure what's different. It doesn't show in 0.15.2 preview 2

**Comment by luixxiul** [comment]
This works fine on Debian now. CC @srirambv for confirmation

**Comment by srirambv** [comment]
I don't see `Recently closed` under History even on previous builds. I just see these two options
![image](https://cloud.githubusercontent.com/assets/17010094/25774690/61da725e-328c-11e7-9421-cad484f107f3.png)

**Comment by luixxiul** [comment]
yeah I don't see the items again. the issue seems to be intermittent. I'm trying to find the consistent STR.

**Comment by alexwykoff** [comment]
Closing DNR

**Comment by luixxiul** [comment]
> Closing DNR

Really?

**Comment by luixxiul** [comment]
![dr](https://cloud.githubusercontent.com/assets/3362943/26368841/ccc36db0-402d-11e7-8d33-807beb6f7db6.gif)

**Comment by alexwykoff** [comment]
@luixxiul We closed it per triage meeting, however I can see that I misread your comment on 'don't see items'.

**Comment by bsclifton** [comment]
@luixxiul I have not been able to reproduce this.  I'll have to try on Linux specifically w/ Gnome.  I'll put into the next milestone

**Comment by luixxiul** [comment]
yeah, I experience the issue intermittently. I'll look for a consistent STR for the next milestone, thanks.

**Comment by bsclifton** [comment]
Removing milestone since we need accurate steps

**Comment by luixxiul** [comment]
I don't see the issue recently. maybe fixed?

**Comment by bsclifton** [comment]
Closing as fixed since I haven't been able to repro.  Let's re-open if there are solid steps 😄
