### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#859]

**Comment by tetrode** [comment]
this would be something I would Brave want to have...

**Comment by dschneiderch** [comment]
+1

**Comment by lesserwhirls** [comment]
:clap: :thumbsup:

**Comment by luixxiul** [comment]
It seems that it stopped working on Windows 10, version 0.9.6

**Comment by bbondy** [comment]
This seems to be a regional problem, please open a new issue to track. I tried on Windows 10 x64 0.9.6 here and it worked.   I have some ideas of things for you to check.
