### ISSUE TITLE
Underline shortcut (Ctrl+U) conflict with View Page Source shortcut

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#8591]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
User reported that underline shortcut `Ctrl+U` in Yahoo mail didn't work. Instead of underlining, it open Page Source -- that have same shortcut.

https://community.brave.com/t/underline-does-not-work-in-yahoo-mail-under-brave-0-15-1/2542

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 Pro 

- Brave Version (revision SHA):
0.15.1

- Steps to reproduce:
    1. Open Yahoo mail
    2. Write new email
    3. Highlight text and use `Ctrl+U` for underlining text
    
- Actual result:
Brave open page source

- Expected result:
User can underline highlighted text or to type new text underlined

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

https://github.com/brave/browser-laptop/issues/2219

**Comment by dandv** [comment]
Also conflicts in Hangouts, Google Docs, Gmail etc.

**Comment by johnlm1** [comment]
This also is a problem in Word Online (on PC).

Obviously it is hard-coded into our minds to use CTRL+U for underlining.  CTRL+B and CTRL+I work in Word Online, GDocs, etc. for bold and underlining, and then when you go to do underline it opens a "View Source" page instead.

It seems as though "View Source" could be mapped to just about anything else and this problem would evaporate :)

**Comment by advaithasabnis** [comment]
same problem a few months in.

**Comment by Liunkae** [comment]
Chrome and Firefox also use Ctrl/Cmd+U, but they apparently disable the shortcut inside text fields. I think Brave should do the same. If this is not easily doable, we could switch to the shortcut Safari uses, Cmd+Option+U (which would be Ctrl+Alt+U on other platforms).

**Comment by advaithasabnis** [comment]
Still a problem in google docs.

**Comment by chrishobcroft** [comment]
Also happening on Ubuntu 16.04 LTS with Brave 0.19.95

I support the work to find alternative ways to "view source" :)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/ctrl-u-sends-me-to-source-page/26761?u=eljuno

**Comment by bsclifton** [comment]
For folks experiencing this, can you please try grabbing the new version of Brave?
https://brave.com/download

If you run still run into problems, let's create an issue in the new repository:
https://github.com/brave/brave-browser
