### ISSUE TITLE
Brave randomly changed language on launch

### ISSUE THREAD

**Issue by ProPuke** [brave/browser-laptop#8592]
- Describe the issue you encountered:
Upon starting Brave today it had randomly changed to some Indian script with a prompting notification of some kind which I cannot read. I have no other locales installed on this computer, besides English (UK), and use no other languages. Annoyingly, when navigating to settings to change language, I find the language names are also all localised, so I cannot read which one says "English"

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA):  0.15.0 (71fb73001617949528cc6473e288a49e76fcd4d5)

- Expected result:
English (UK). I have no other locales installed on this computer, nor do I use any other languages.
The language options should not be localised to the current language, but should instead be written in _their_ languages. Currently this makes it very awkward to switch back to a known language.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/105934/25569221/c7140170-2e0a-11e7-96c3-07db44eae0fe.png)

**Comment by Liunkae** [comment]
Related: #7499 (localization of the language list)

**Comment by alexwykoff** [comment]
@luixxiul can you repro?
