### ISSUE TITLE
Session migration doesn't properly handle extensions

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8595]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Session migration needs to handle extensions properly
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10x64
- Brave Version (revision SHA):
Brave	0.15.1
rev	ea5024d
- Steps to reproduce:
    1. Clean install an older version of brave
    2. Enable Pocket and a password manager
    3. Close the browser to save changes in `session-store-1` file, make a copy of the file
    4. Move/remove the brave folder in `%appdata% 
    5. Launch browser again to create a new profile, close the browser to generate `session-store-1` file
    6. Close browser and copy the `session-store-1` file from step 3 and replace in the new profile
    7. Launch browser, enabled extensions are not shown on the window, `about:extensions` has broken images for enabled extensions
    8. Tear off tab to create new window / use keyboard shortcuts to create new window, enabled extensions widget appears, `about:extensions` shows proper image
    
- Actual result:
Session migration doesn't properly handle extensions
- Expected result:
Session migration should properly handle extensions 
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Pretty sure its the same
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![extension](https://cloud.githubusercontent.com/assets/17010094/25576055/23483364-2e54-11e7-80b3-597917f6e50e.gif)

- Any related issues:
cc: @bbondy @bradleyrichter @bsclifton

**Comment by alexwykoff** [comment]
@srirambv could you clarify, do the extensions not work at all or is it only the images?

**Comment by srirambv** [comment]
Extensions work. But the widget is not shown. It gets instsalled again when the session is migrated. But the initial window doesn't show the widget which might cause lead to confusion weather the session is migrated properly or not.
