### ISSUE TITLE
Sync alert needs refactoring followup to #8044

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8598]
## Test plan

https://github.com/brave/browser-laptop/pull/8622#issue-225711299

----

- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Sync alert needs refactoring. While testing #8044 found sync reset alert code buttons were not aligned properly. Needs refactoring to match existing behavior

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
b098619e34708a7926334048e7a31a8e3b275bd7 @luixxiul confirmed same on master branch as well
- Steps to reproduce:
    1. Enable sync on laptop
    2. Click on reset Sync, cancel -> close modal 
    3. Click on reset sync again -> alert box buttons aligned next to text
    
-- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25578852/75d7a2e8-2e6a-11e7-80b1-2d2410f6e327.png)

- Any related issues: #7930

**Comment by luixxiul** [comment]
The suppress message and the button is aligned to the same line on this issue: #7930

The fix works fine only if there is one button, which is "OK" button. With other buttons it does not work as expected, as the screenshot on the 1st post shows.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/25647554/f4282d0e-2ffd-11e7-9077-e459f457d7f6.jpg)

The block for buttons and the other stuff should be separated to avoid such a case, which is a strategy I took when I refactored commonForm components (See: `commonFormButtonWrapper` on about:styles )
