### ISSUE TITLE
Implement home page keyboard shortcut

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8599]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Implement home page keyboard shortcut as suggested from community user https://community.brave.com/t/homepage-shortcut/2524/3

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.1
rev	ea5024d

- Actual result:
No shortcut key to load home page

- Expected result:
Implement shortcut key for opening home page in a new tab irrespective of what is set

- Screenshot if needed:

- Any related issues:
Please change milestone if required

**Comment by bsclifton** [comment]
Similar to https://github.com/brave/browser-laptop/issues/6237

**Comment by bsclifton** [comment]
Verified fixed in brave-core
`⌘ + Shift + h` on macOS
`Alt + Home` on Windows/Linux
