### ISSUE TITLE
"Folder Upload" feature in Google Drive Broken

### ISSUE THREAD

**Issue by KevDoy** [brave/browser-laptop#8601]
- Did you search for similar issues before submitting this one?
Sure did.

- Describe the issue you encountered:
When choosing New, then Folder upload on Google Drive, I am able to find the folder in Finder. Let's say I chose a folder called "Files" inside of "Documents". Instead of creating and uploading the folder called "Files" it creates a folder named "Documents" and gives me an error message.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
ea5024d

- Steps to reproduce:
    1. Open Google Drive & log in
    2. Press "New" Button
    3. Select "Folder Upload"
    4. Select a Folder to upload

    
- Actual result:
Error, wrong folder created

- Expected result:
Folder selected is uploaded to Google Drive

- Is this an issue in the currently released version?
Yes, and previous versions.

- Can this issue be consistently reproduced?
Yes it can.

- Screenshot if needed:
![logos_-_google_drive](https://cloud.githubusercontent.com/assets/11251011/25586868/2ab23d82-2e56-11e7-9ef2-5563147efb24.png)

- Any related issues:
Not sure if this is opened, but Brave also has an issue download zipped files from Google Drive.

**Comment by bsclifton** [comment]
I believe this requires the Google Drive extension to be installed

@jonathansampson do you know offhand?

**Comment by darkdh** [comment]
Will be fixed by https://github.com/brave/muon/issues/242

**Comment by luixxiul** [comment]
On which build will https://github.com/brave/muon/pull/361 be available? On 0.19.x?

**Comment by darkdh** [comment]
muon 4.6.0. Any branches upgrade to muon 4.6.0 will have the fix

**Comment by luixxiul** [comment]
thanks!

**Comment by srirambv** [comment]
Moving to 0.21.x since we aren't using Muon 4.6.x yet

**Comment by srirambv** [comment]
Verified. Works on Windows with both Fingerprint enabled and disabled.
