### ISSUE TITLE
Cleanup share l10n strings to re-use the same string

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8604]
## Test plan

https://github.com/brave/browser-laptop/pull/12445#issue-285184656

----

See review comment here:
https://github.com/brave/browser-laptop/pull/8517/files/9ce64841f10aa46dcad512307af68966057bca49#diff-985837eca34ef94b3bc9cf3271761dca

It would be cleaner to use the same string for each of these menu items.

**Comment by sergiorojasa** [comment]
I would like to work on this.

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
