### ISSUE TITLE
Make bookmarks items' list fixed

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8607]
PR #8532 addressed some issues regarding bookmarks but fixed header for item's list was left. That's because list uses SortableTable, and per spec tables aren't supposed to have `overflow`.

Screenshot credits of @jonathansampson:
![34e194a0-2c1d-11e7-8075-698d262c317c](https://cloud.githubusercontent.com/assets/4672033/25589971/00ab925c-2e85-11e7-9489-57f46d38faba.gif)

Ideally, items' header (right-hand side) should be fixed.

In order to fix that, SortableTable should be either fully refactored to make use of CSS grid or flagged at some point that other element than `<table>` (and its children) should be used.

Labelled as `backlog` feel free to remove if needed

**Comment by cezaraugusto** [comment]
Removing good-first-bug since refactoring SortableTable can be tricky. Feel free to ping me anyone willing to take it.

**Comment by luixxiul** [comment]
fyi there is an upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=702927 "position: sticky does not work on <thead> or <tr>". Since sortableTable will be deprecated with another component, it'll be not an issue for us.

**Comment by rebron** [comment]
Removing from backlog. Not an issue in brave-core.
