### ISSUE TITLE
Brave Crashes in certain conditions

### ISSUE THREAD

**Issue by ryazo** [brave/browser-laptop#8610]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered: 

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 8

- Brave Version (revision SHA): 	ea5024d

- Steps to reproduce: Went to 4chan.com
    
- Actual result: Crashed and closed with no bug reporter.

- Expected result: Not crashing.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? Yes.

**Comment by bsclifton** [comment]
@ryazo do you have more specific steps?

Also, do you have more information about your setup? ex: do you have Flash installed? Which PW manager do you have enabled?

**Comment by ryazo** [comment]
Go to 4chan.com

I am not using a PW manager.
I haven't changed my version of flash.

**Comment by bsclifton** [comment]
Closing as there is not enough information to reproduce.  I tried the steps above, unable to cause a crash.
