### ISSUE TITLE
when opening html files on local disk the url still contains http://

### ISSUE THREAD

**Issue by ghinks** [brave/browser-laptop#862]
Firstly fantastic job, I'm using this on mobile and laptop. Good Job.
Glenn

Environment OSX, El Capitan
Brave Version 0.7.14

command-O opens a local file as 
http://users/developer/dev/some-path/docs/index.html rather than
file:///users/developer/dev/some-path/docs/index.html

editing the http to file in the url resolves the issue.

**Comment by dhocker** [comment]
I've encountered this problem, too, However, changing http:// to file:// does not work around the problem. The file does not appear to be renedered at all.

Version: 0.7.15
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110

**Comment by psimyn** [comment]
it is always prepending 'http://' to paths that don't have a scheme. Also happens if you type a file path (e.g. `/users/blah/some/file`)

I'll create a PR once I add some tests

**Comment by diracdeltas** [comment]
@psimyn ++
