### ISSUE TITLE
Unable to find Electron app

### ISSUE THREAD

**Issue by Mrostgaard** [brave/browser-laptop#8624]
- Describe the issue you encountered:
Running npm start while running npm running watch will result in the error 'Unable to find Electron app'
- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS
- Brave Version (revision SHA):

- Steps to reproduce:
    1. git clone https://github.com/brave/browser-laptop.git 
    2. cd browser-laptop  
    3. npm install  
    4. npm run watch 
    5. npm start

https://blog.brave.com/loading-chrome-extensions-in-brave/
    
- Actual result:
> brave@0.15.1 start /*location*/browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

IOVARendererID property not found
process exited with code 1

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! brave@0.15.1 start: `node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brave@0.15.1 start script 'node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck'.
npm ERR! This is most likely a problem with the brave package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs brave
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls brave
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /*location*/browser-laptop/npm-debug.log
- Expected result:
Success
- Is this an issue in the currently released version?
Yes newest version from git
- Can this issue be consistently reproduced?
I think... I've done it a few times

- Screenshot if needed:
https://imgur.com/a/xFqSr
- Any related issues:
https://github.com/brave/browser-laptop/issues/8596#event-1064740834
Earlier error, got fixed, when getting to next step i get this error.

**Comment by Liunkae** [comment]
> npm ERR! node v4.4.4

@Mrostgaard You have nodejs 4.4.4, but Brave requires nodejs 6.1 or later (according to [ReadMe.md](https://github.com/brave/browser-laptop/blob/master/README.md)). Please download the latest nodejs version: https://nodejs.org.
