### ISSUE TITLE
One-time tab-remembrance for Upgrade

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8625]
**Did you search for similar issues before submitting this one?**

Yes

**Describe the issue you encountered:**

For users who have _Brave starts with: a new tab_ configured, the Upgrade process will forget all opened tabs. The user intends to continue browsing (pausing only to upgrade), but can no longer do so due to all tabs being lost.

Community: [Have a specific session restore setting for upgrade-relaunches](https://community.brave.com/t/have-a-specific-session-restore-setting-for-upgrade-relaunches/2611)

**Platform (Win7, 8, 10? macOS? Linux distro?):**

Desktop

**Brave Version (revision SHA):**

0.15.1

**Steps to reproduce:**

1. Select _a new tab_ for _Brave starts with_ in Settings
2. Open a few sites
3. When prompted, apply Browser update(s)
    
**Actual result:**

Brave restarts with only _a new tab_ open

**Expected result:**

Brave handles the Upgrade process as a special case, and restores the user's working tabs in spite of their general setting to _open a new tab_ when Brave launches.

**Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**Is this an issue in the currently released version?**

Yes

**Can this issue be consistently reproduced?**

Yes

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/update-closes-tabs/5073/3?u=eljuno)

>To be clear, I don’t want Brave to remember my session each time. I’m wanting it to only remember my session when there’s an update.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/remember-my-tabs-when-doing-an-update-relaunch/10692?u=eljuno

>Brave regularly requests to relaunch to load a new version. I usually have many tabs open. If I relaunch I lose all my tabs. I would like Brave to remember my tabs and reload them when it relaunches.

**Comment by jonathansampson** [comment]
+1 from Twitter: https://twitter.com/Perolus/status/947526017341640704

![image](https://user-images.githubusercontent.com/815158/34463443-b48166e2-ee21-11e7-800d-ea47190029ae.png)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/restart-after-update-looses-all-tabs/17272?u=eljuno

User set Brave starts with “Home page” and looses their tabs on every update.

Brave: 0.20.46
V8: 6.4.388.41
rev: 5eb035c2d68225994a572a1d62861cf961355ab2
Muon: 4.8.2
OS Release: 16.7.0
Update Channel: Release
OS Architecture: x64
OS Platform: macOS
Node.js: 7.9.0
Brave Sync: v1.4.2
libchromiumcontent: 64.0.3282.140
