### ISSUE TITLE
Back/Forward buttons state will be stole by preview pages

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#8628]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Can't click the back/forward buttons until I click on the target page. And have to avoid cursor the hover on other pages for preview.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
0.15.2 preview 2
- Steps to reproduce:
    1. Open a page in tab A and make sure it doesn't contain back/forward state
    2. Search things and click the result in tab B
    3. Hover cursor to tab A and leave preview
    
- Actual result:
back/forward button is still in tab A's state

- Expected result:
When leaving preview, it should restore tab B's back/forward button state. However, we have to click on tab B to regain the state.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

[Kapture 2017-05-02 at 10.21.24.mp4.zip](https://github.com/brave/browser-laptop/files/971446/Kapture.2017-05-02.at.10.21.24.mp4.zip)

- Any related issues:

**Comment by NejcZdovc** [comment]
closing in favor of #8640
