### ISSUE TITLE
Wallet creation fails due to worker error 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8632]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Wallet creation fails due to worker error 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.2
rev	71f7dfd

- Steps to reproduce:
    1. Clean install 0.15.2 Preview 2
    2. Launch from console
    3. Enable payments, wallet creation fails, console shows worker error
    
- Actual result:
Wallet creation fails due to worker error 

- Expected result:
Wallet should be created

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25635373/d184828a-2f75-11e7-9510-402d052e8d9a.png)

- Any related issues:
cc: @mrose17 @bsclifton

**Comment by bsclifton** [comment]
Fixed by reverting the feature which caused this (see more notes in https://github.com/brave/browser-laptop/issues/7344)

**Comment by bbondy** [comment]
Fixed with https://github.com/brave/muon/commit/14c0cd7b507422e5d988dca486c7a6918183fa1d we can revert the revert in https://github.com/brave/browser-laptop/commit/db26cac63126f3f7be4a171ff892fce41aeb41e9 once we are on new muon builds.
