### ISSUE TITLE
Edit bookmark modal needs refactoring for UI scale 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8634]
## Test plan

https://github.com/brave/browser-laptop/pull/8646#issue-225871555

----

- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Set UI scale to supersize
    2. Edit a bookmark from URL 
    3. Bookmark modal is not properly refactored
    

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25635681/e8f38da2-2f76-11e7-93e3-b5b2d85d3050.png)

- Any related issues:

**Comment by luixxiul** [comment]
CC @bsclifton; in case you'd need help on modifying commonForm please ping me.
