### ISSUE TITLE
Error message in pinned tab will not be in the same tab

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#8639]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
There will be a new tab showing error message for pinned tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version (revision SHA):
0.15.2 Preview 2
- Steps to reproduce:
    1. Pin badssl.com
    2. Click on "expired" or other red examples
    
- Actual result:
There will be a new tab of error page
- Expected result:
Error page should be in a same pinned tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

**Comment by bsclifton** [comment]
Per @darkdh, this still happens in 0.17.15
