### ISSUE TITLE
URL bar input lag with 1000+ bookmarks

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#8643]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When the browser has many bookmarks, the URL bar lags between typing and displaying input.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
master @ db26cac63126f3f7be4a171ff892fce41aeb41e9

- Steps to reproduce:
    0. Instrument `onKeyUp()` in `app/renderer/components/navigation/urlBar.js` by adding console.log(`${new Date().getTime()} onKeyUp >`) at the beginning and console.log(`${new Date().getTime()} onKeyUp <`) at the end of the function.
  1. Open Brave and import 1000+ bookmarks.
  2. Toggle browser debug console and open the JS console.
  3. Focus the URL bar and press the "A" key repeatedly.
  4. Observe browser debug JS console for onKeyUp() latency.
    
- Actual result:
Latency is ~200ms.

- Expected result:
<10ms (On a fresh profile, it takes ~3ms).

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Requires 1000+ bookmarks.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by Liunkae** [comment]
Related to/duplicate of #7453 (Performance : urlbar response is slow when searching across many bookmarks).

**Comment by ayumi** [comment]
@Liunkae thanks! closing in favor of that
