### ISSUE TITLE
Another context menu appears after displaying an context menu on new tab button

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8647]
**Describe the issue you encountered:** Another context menu appears after displaying an context menu on new tab button

- Platform (Win7, 8, 10? macOS? Linux distro?): debian

- Brave Version (revision SHA): 0.15.2 preview 2

- Steps to reproduce:
    1. Right click on the new tab button
    2. Left click on the existing tab (or anywhere elese)

- Actual result:
    ![nativemenu](https://cloud.githubusercontent.com/assets/3362943/25647122/282e546a-2ffa-11e7-81d7-4ff41a5b50f3.gif)

- Expected result: the 2nd context menu should not appear

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #6700 #8303

**Comment by Liunkae** [comment]
Also reproducible with Brave 0.15.2 preview 2 and the latest master (8745bd5) on macOS 10.12.x.

Introduced when the menu was made native (PR #8397). There's already a `e.stopPropagation()` in [longPressButton.js](https://github.com/brave/browser-laptop/blob/master/js/components/longPressButton.js), so I'm not sure what's causing this behavior.

**Comment by bsclifton** [comment]
@Liunkae I believe this is related to https://github.com/brave/browser-laptop/pull/8320

Once the native menu shows, we should stop propagation.  Do you think you can check it out? 😄

**Comment by srirambv** [comment]
Not reproducible on Windows 10 x64 preview 2 build.

**Comment by srirambv** [comment]
@bsclifton @luixxiul Isn't it correct it showing the tab context menu when it is clicked on it irrespective of the newtab context menu being shown when clicked on new tab?
