### ISSUE TITLE
Saving a page/torrent file crashes browser

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8648]
**Describe the issue you encountered:** Saving a page/torrent file crashes the browser

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian (confirmed on Windows 10 32 bit)

- Brave Version (revision SHA): 0.15.2 preview 2

- Steps to reproduce:
    1. Save a page via shortcut key
    2. Click "Save" on save dialog
    
- Actual result: the browser crashes

- Expected result: the browser should not crash

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
The browser crashes when you save torrent files via "save torrent file" button.

**Comment by NejcZdovc** [comment]
@luixxiul is this working correctly on 0.15.1?

**Comment by luixxiul** [comment]
yes

**Comment by NejcZdovc** [comment]
Probablu related to #8567

cc @feross

**Comment by luixxiul** [comment]
> Probably related to #8567

I don't think so because the browser crashes when saving a web page as I reported.

**Comment by luixxiul** [comment]
I think this has been fixed with the latest build. CC @srirambv for confirmation.

**Comment by alexwykoff** [comment]
pretty sure this works
