### ISSUE TITLE
wrong alert response from update server when checking for updates when on latest version.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#865]
When a user's version is the latest available, it should say: 
"Sorry, there are no updates yet. Please check back soon."

wrong response:
![image](https://cloud.githubusercontent.com/assets/13509546/13237726/f18d5ce0-d982-11e5-800b-1b20caf5c6ee.png)

**Comment by bbondy** [comment]
I think this is because of a server side change. Or configuration change with fastly.

> HTTP request sent, awaiting response... 204 No Content

Before we used to send 200 and we do an explicit check for 200 in the updater code.
Please have the server return 200.

**Comment by bbondy** [comment]
Fixed by: https://github.com/brave/browser-laptop/commit/7687632ee18628fb80c0ec798d594866f21e0a09
