### ISSUE TITLE
Redux component - Navigator

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8651]
## Test plan

https://github.com/brave/browser-laptop/pull/8658#issue-226004200

----

**Describe the issue you encountered:**
Refactor component `Navigator` into redux component.

**Comment by bsclifton** [comment]
Do we think this will be finished by Friday? If not, maybe we should push to 0.15.3 (or later)

**Comment by NejcZdovc** [comment]
This refactor will fix #8640, so I will push as hard as possible to finish everything.
