### ISSUE TITLE
Redux component - Menubar

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8652]
## Test plan

https://github.com/brave/browser-laptop/pull/8656#issue-225938453

----

**Describe the issue you encountered:**
Refactor `Menubar` into redux component.

**Comment by bsclifton** [comment]
I would vote to push this past 1.0 because it's very limited (only used on Windows; even then, only when menu is visible). I don't think we'd get much by reworking it

**Comment by NejcZdovc** [comment]
Sadly I need to refactor this, so that I can refactor #8651 and then when #8651 is refactored, #8640 will be fixed :smiley:

**Comment by bridiver** [comment]
sorry, but we need to revert this for now. It stores methods in the state and we can't do that because they are not serializable

**Comment by bridiver** [comment]
I guess the menu template thing has been there for a long time so I'll leave this for now, but we need to fix that so I'll open a ticket

**Comment by NejcZdovc** [comment]
@bridiver yeah I listed this problem here #8528, because it would be overkill to refactor it in this PR. Problem is that the whole context menu is problematic and we need to find a better way to handle it.

**Comment by luixxiul** [comment]
@bridiver @NejcZdovc so does this issue have to be reopened? I'm asking it for QA work.

**Comment by NejcZdovc** [comment]
@luixxiul no need to be reopened, if you are talking about  context menu, we will address this issue later on.
