### ISSUE TITLE
Brave force quits on OSX on aliexpress.com

### ISSUE THREAD

**Issue by mikegleasonjr** [brave/browser-laptop#8657]
EDIT:

```
Brave	0.15.1
rev	ea5024d
Muon	2.58.8
libchromiumcontent	58.0.3029.81
V8	5.8.283.32
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.5.0
os.arch	x64
```

**Comment by kumarrishav** [comment]
Working fine on my brave browser on OSX

**Comment by bsclifton** [comment]
hi @mikegleasonjr what version do you have?

We did have a few problems, but with our latest release (0.15.1) those should be fixed.  Please let us know 😄

**Comment by mikegleasonjr** [comment]
Sorry I just posted the version I'm using. Only thing I changed is that I enabled the fingerprint blocking.

**Comment by bsclifton** [comment]
@mikegleasonjr great- thanks for adding that 😄  Does the site still crash if you disable fingerprint protection (you can disable only for that site using the lion icon)?

**Comment by mikegleasonjr** [comment]
Yep still crashes :(

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-brave-force-quits-on-osx-on-aliexpress-com/10052

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
