### ISSUE TITLE
Browser crash with payment enabled when clearing browsing data

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8659]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser crash with payment enabled when clearing browsing data

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.2
rev	71f7dfd

- Steps to reproduce:
    1. Clean install 0.15.2 preview 2 and launch from console
    2. Clear browsing data, console shows error  (screenshot 1)
    3. Enable payments, doesn't work(#8632) 
    4. Kill the app and copy an old `ledger-synopsis` file and paste it in `%appadata%`
    5. Relaunch the app from console
    6. Enable payments, should work
    7. Clear browsing data, browser crahses (screenshot 2)
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![error](https://cloud.githubusercontent.com/assets/17010094/25665197/c3ceaafe-3014-11e7-919b-e96f39081297.gif)
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17010094/25665338/384b579c-3015-11e7-9e04-7044b57d77c7.gif)

- Any related issues:
cc: @mrose17 @bsclifton

**Comment by bsclifton** [comment]
@srirambv the GIF moves too quick; can you please share the error message that is being seen?

Without being able to read the error, I am guessing this is related to the worker code and may be invalid with our next build

**Comment by srirambv** [comment]
@bsclifton here is the error. Sorry forgot to add it in the initial post

**Clear private data error**
```Sriram BV@DESKTOP-97HVIA8 MINGW64 ~
$ Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Insufficient number of arguments.
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Insufficient number of arguments.
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate (timers.js:617:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Crash error**
```
$ Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Insufficient number of arguments.
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
C:\Users\Sriram BV\AppData\Local\brave\app-0.15.2\resources\app.asar\node_modules\node-anonize2-relic-emscripten\anonize2-jumbo.js:67
            throw ex
            ^

TypeError: Insufficient number of arguments.
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
~/AppData/Local/brave/Brave.exe
```

**Comment by darkdh** [comment]
only need to clear "all sites cookies" or "cached images and files"

**Comment by mrose17** [comment]
an observation: whenever i quit master on mac os, i see the same errors. the pointer into `...anonize2-jumbo.js:67` is misleading. that gets stuck on the stack regardless of whatever is going on...

**Comment by mrose17** [comment]
@darkdh - very helpful, thanks!

**Comment by mrose17** [comment]
update: it appears to be related to https://github.com/brave/browser-laptop/commit/40abc0c780050eb0b8dd42c15065d1c784268b47

**Comment by bridiver** [comment]
there is an issue with the call to clearCache, but did this actually cause a crash? I saw the error on the console, but because it is called in `setImmediate` it didn't actually hurt anything other than not doing what it was supposed to do

**Comment by darkdh** [comment]
I can reproduce the crash in package build but not in dev environment.
