### ISSUE TITLE
everything reset?

### ISSUE THREAD

**Issue by msp1111111** [brave/browser-laptop#866]
When I opened Brave tonight after getting home, I found all my preferences reset and bookmarks gone. 0.7.15 - Windows

**Comment by bbondy** [comment]
It sounds like you lost your `session-store-1` file, can you recall any specific steps which could have caused this?

**Comment by bbondy** [comment]
Also how long have you been using things? Have you been opening / closing the program a lot? Or all within one application instance?

**Comment by msp1111111** [comment]
I can't think of anything I did differently. I put my computer to sleep before going out at 1:30 and then when I returned at 9 pm I noticed my bookmarks gone. Any logs I should check?

I have been using/opening/closing a lot since I updated to 0.7.15.

**Comment by bbondy** [comment]
Should be fixed by:
https://github.com/brave/browser-laptop/commit/c6a180b2a518af758ba83c481a2fefdac8d75ab2
