### ISSUE TITLE
cVim keep being disabled

### ISSUE THREAD

**Issue by Kudlaty01** [brave/browser-laptop#8664]
- Did you search for similar issues before submitting this one?
Yes, tried the chrome extension import [turorial](https://blog.brave.com/loading-chrome-extensions-in-brave/) and checked problems with other extensions being solved

- Describe the issue you encountered:
after registering the Surfkeys cVim extensions they keep being disabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Debian Jessie

- Brave Version (revision SHA):
c559e77755da041f4693b27a3c1b66825adbfa7b

- Steps to reproduce:
    1. install the extension according to tutorial 
    2. enabling it in the preferences
    3. open a new tab and return back to the preferences after some time
    
- Actual result:
the extensions are disabled

- Expected result:
the extensions are still enabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes, as I keep removing and reinstalling the brave cloned app

- Is this an issue in the currently released version?
From the master branch

- Can this issue be consistently reproduced?
Yes

I also get the following terminal output after `npm start`:

> [589:615:0503/190619.374308:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
Crash reporting enabled
[589:589:0503/190621.158517:ERROR:extension_function_dispatcher.cc(585)] Unknown Extension API - history.search
[589:589:0503/190621.228694:ERROR:extension_function_dispatcher.cc(585)] Unknown Extension API - sessions.getRecentlyClosed

And after enabling e.g. cVim extension I get also many:
> An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined

**Comment by bsclifton** [comment]
@jonathansampson could you help on this one? 😄

**Comment by Kudlaty01** [comment]
Wow, what a quick reaction :)
Also if both installed they get enabled/disabled at the same time, none could be enabled/disabled separately.

**Comment by jonathansampson** [comment]
@bsclifton I can indeed. @Kudlaty01, I'll take a look here in the next few minutes :)

**Comment by Kudlaty01** [comment]
@bsclifton please forgive me my terrible mistake. The first extension was [surfingkeys](https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc)
I do confirm the second extension though ;)

**Comment by Kudlaty01** [comment]
@jonathansampson Is this issue also automatically an extension request?

**Comment by duranivan** [comment]
cVim is working for me following @jonathansampson [tutorial](https://medium.com/@jonathansampson/testing-chrome-extensions-in-brave-8e25d1f7386d).

**Comment by duranivan** [comment]
After trying `cVim` for awhile, I did notice that some keyboard commands are broken in some websites, for example `t`, `/` or `?` in `github`, which makes the extension unresponsive. Reloading the website is needed to make the basic `cVim`'s commands (`jkhl, G, gg`) responsive again.

**Comment by jonathansampson** [comment]
Thank you for the feedback, @duranivan! Are you able to identify any  errors on either the page devtools, or on the background page devtools for the extension?

**Comment by duranivan** [comment]
Sure, here it's what I got:

While in `github.com`, the page devtools shows this error:

```
Refused to frame 'chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/cmdline_frame.html' because it violates the following Content Security Policy directive: "child-src render.githubusercontent.com". Note that 'frame-src' was not explicitly set, so 'child-src' is used as a fallback.

Command.onDOMLoad @ command.js:1032
```

Command.onDOMLoad @ command.js:1032 is the following:

```
Command.onDOMLoad = function() {
  this.onDOMLoadAll();
  if (window.self === window.top) {
    Command.frame = document.createElement('iframe');
    Command.frame.src = chrome.runtime.getURL('cmdline_frame.html');
    Command.frame.id = 'cVim-command-frame';
    document.lastElementChild.appendChild(Command.frame);
  }
};
```

Line 1032 is:

```
document.lastElementChild.appendChild(Command.frame);
```

Hope it helps.

**Comment by bsclifton** [comment]
Proper extension support will be available in [brave-core](https://github.com/brave/brave-browser) 😄
