### ISSUE TITLE
Extension API: chrome.runtime.onInstalled.addListener

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8685]
https://developer.chrome.com/extensions/runtime#event-onInstalled

Blocks #8671

**Comment by zentagonist** [comment]
After discussion of progress on metamask integration items with @jonathansampson, adding this to the 0.20.x milestone.

**Comment by jonathansampson** [comment]
@kevinlawler Thoughts on this one? Do we presently have an event to hook-into?

**Comment by kevinlawler** [comment]
The `chrome.runtime.*` libraries do not follow the same pattern for support that the previous libraries I've enabled have. I have spoken with @bridiver a little bit about this, and it seems like this logic will need to live in C++. For `chrome.runtime.*`, it looks like roughly half of the calls are currently enabled, some of them with exposed hooks through the JS. Many of the enabled `chrome.runtime` events live here

    $BLB/src/extensions/renderer/resources/messaging.js

Unfortunately, if you search in that file there are no hits for `onInstalled`, which means it probably doesn't live there. Running `chrome.runtime.onInstalled.addListener` inside the console for an extension returns without error, but I have yet to verify that the functions passed to it are triggered at the correct time later on.

There are some hits for `onInstalled` here

    $BLB/src/extensions/browser/api/runtime/runtime_api.cc

and this is probably a good place to begin looking to see how much of the code is live or dark.
