### ISSUE TITLE
Extension API: chrome.runtime.reload

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8686]
https://developer.chrome.com/extensions/runtime#method-reload

Blocks #8671

**Comment by zentagonist** [comment]
After discussion of progress on metamask integration items with @jonathansampson, adding this to the 0.20.x milestone.

**Comment by jonathansampson** [comment]
@kevinlawler Okay if I assign this to you?

**Comment by kevinlawler** [comment]
Yes, but see #8685

**Comment by luixxiul** [comment]
Was this implemented, since Metamask was added?
