### ISSUE TITLE
PDFs aren't recognized unless the url ends in .pdf

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8687]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
attempting to view http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.105.6357&rep=rep1&type=pdf in Brave fails, other browsers can view the pdf without issue

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X

- Brave Version (revision SHA):
0.15.2 (af7ef42)

- Steps to reproduce:
    1. visit http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.105.6357&rep=rep1&type=pdf pdf should be readable
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/884
