### ISSUE TITLE
Make Brave portable ?

### ISSUE THREAD

**Issue by crazy-max** [brave/browser-laptop#8691]
Hi,

I've created a small wrapper named [brave-portable](https://github.com/crazy-max/brave-portable) but i was wondering if you had planned to do one day a portable version of Brave?

Thanks

**Comment by Jacalz** [comment]
I will take a look at it today if I get some time over 👌

**Comment by luixxiul** [comment]
@crazy-max I'm going try. Could I know how to use it? thanks!

**Comment by crazy-max** [comment]
@luixxiul All instructions are available in the [README.md](https://github.com/crazy-max/brave-portable/blob/master/README.md) of [brave-portable](https://github.com/crazy-max/brave-portable) repository.

**Comment by luixxiul** [comment]
I see, I wanted to know how to build the binary from the source code.

Also is it OK to include the binary downloaded from Brave website, without including source code? CC @bbondy

**Comment by crazy-max** [comment]
Indeed i use the binaries from the official website  :

* https://laptop-updates.brave.com/latest/winia32
* https://laptop-updates.brave.com/latest/winx64

Then i extract the setup and read the nupkg file instructions and make a self extraction and i copy the app-* folder and the execution stub to the root folder.

`brave-portable.exe` seek if the data folder located in `%APPDATA%\brave` exists and copy the folder in `brave-portable\data` and make / update the symlink between`%APPDATA%\brave <=> brave-portable\data`, that's it.

Then i package everything as 7z, zip and a simple InnoSetup like you can see in the latest release : https://github.com/crazy-max/brave-portable/releases

But like you said it would be better to create the binaries from source first.

**Comment by msiyer** [comment]
@crazy-max This is good. Compilation on Linux is straightforward. I have not had the time to compile on Windows. For people like us, we can have a git clone on our system which can be updated and built weekly using a cron job. A good solution for auto-update :), I think.
 
However, for mass consumption two problems still remain unaddressed:

- The "executable signing" without which distributing the package may not be proper
- The auto-update feature

**Comment by bsclifton** [comment]
I'm going to close this issue in favor of https://github.com/brave/browser-laptop/issues/2953

Let's continue the conversation there though 😄
