### ISSUE TITLE
Device Name is missing when you create new sync

### ISSUE THREAD

**Issue by kumarrishav** [brave/browser-laptop#8696]
- Describe the issue you encountered:
Device Name is missing when you create new sync
- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on macOS (not sure about other platform)
- Brave Version (revision SHA):
Brave	0.15.1
rev	ea5024d
- Steps to reproduce:
    1.  check screnshot.
<img width="955" alt="screen shot 2017-05-04 at 8 37 26 pm" src="https://cloud.githubusercontent.com/assets/4078325/25710893/3c6dfb6c-310b-11e7-8d08-4656fbd1d02f.png">
<img width="790" alt="screen shot 2017-05-04 at 8 37 34 pm" src="https://cloud.githubusercontent.com/assets/4078325/25710894/3c6ea4cc-310b-11e7-9c8b-aada7eb69379.png">

    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I also notice the issue intermittenly.

**Comment by srirambv** [comment]
I noticed this when I do reset sync and then enable sync again

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/sync-issues-across-devices/3613

**Comment by srirambv** [comment]
https://github.com/brave/sync/issues/183
