### ISSUE TITLE
Saving a document doesn't show correct origin 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8698]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Saving a document doesn't show correct origin 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Alll

- Brave Version (revision SHA):
Brave	0.15.1
rev	ea5024d

- Steps to reproduce:
    1. Enable payments 
    2. Click on advance settings
    3. Save recovery file, download bar shows origin as f`ile:///`
    4. Similar issue when saving pdf file shows as `blob:chrome-extension`
    
- Actual result:
Saving a document doesn't show correct origin 

- Expected result:
Should show the correct origin for files

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes but since origin was not shown before had gone unnoticed 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25714652/9ad5fe2c-30f0-11e7-899a-046bf59ee215.png)
![image](https://cloud.githubusercontent.com/assets/17010094/25714656/9db2e970-30f0-11e7-9db1-39d06cc77862.png)

- Any related issues:
Please change milestone if requried

**Comment by kumarrishav** [comment]
@srirambv So, what should be expected behaviour? whole path of the file ? like `file:///Users/krishav/Library/Application%20Support/brave/brave_wallet_recovery.txt` instead of `brave_wallet_recovery.txt`

**Comment by kumarrishav** [comment]
i think you are talking about `origin` here. But why do need to show origin to user? Isn't name is enough? @srirambv

**Comment by srirambv** [comment]
>So, what should be expected behaviour? whole path of the file ? like file:///Users/krishav/Library/Application%20Support/brave/brave_wallet_recovery.txt instead of brave_wallet_recovery.txt

It should show path like this to keeping it in line for all downloads. 
![image](https://cloud.githubusercontent.com/assets/17010094/25748474/166e5202-31a3-11e7-9841-38015137c19d.png)

But for files downloaded from within the app we could skip it over. cc: @bbondy @bsclifton for thoughts

**Comment by kumarrishav** [comment]
Or can we have this in preference to disable the origin? Though it's good show the origin but as a user it doesn't much value (i think). @bbondy @bsclifton

**Comment by Jacalz** [comment]
I am with you on disabling it since it doesn't have much value to me 😉 @kumarrishav
My suggestion is having it in the generals tab right under default download path if so 👌

**Comment by bsclifton** [comment]
@kumarrishav I can't think of any good reason we'd want to hide this.  Because downloads can't always be trusted, showing the origin and download method (HTTP/HTTPS) is very important, IMO.  Otherwise, all you know was that a download happened

For local files, we could choose to show something different... like "Local file" or show the folder it was downloaded to

cc: @diracdeltas for comment

**Comment by kumarrishav** [comment]
@bsclifton agree with you. So, question is what content we should show for local files (file:/// , blob:chrome-extension)

**Comment by diracdeltas** [comment]
FWIW, #8645 will allow us to load the PDF file directly instead of via a blob: URL, so that would partly solve the issue.

**Comment by diracdeltas** [comment]
we could just replace local URL origins (file:, blob:, data:, chrome-extension:) with `Local file` instead of the full origin.
