### ISSUE TITLE
Windows Dev Environment Setup npm Failure

### ISSUE THREAD

**Issue by philkloose** [brave/browser-laptop#8700]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered: The instructions posted [here](https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide) for configuring a Windows development environment do not work for me.  The `npm install` fails due to a preinstall script for ad-block@3.0.3 on the `npm install bloom-filter-cpp && npm install hashset-cpp` command.  It appears as though someone has taken a stab at resolving this [here](https://github.com/brave/ad-block/pull/57), but I haven't had a chance to test it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 (x64)

- Brave Version (revision SHA):

- Steps to reproduce:
    1. create fresh dev environment per steps in Windows wiki
    2. run `npm-install` on browser-laptop
    
- Actual result:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! ad-block@3.0.3 preinstall: `npm install bloom-filter-cpp && npm install
 hashset-cpp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ad-block@3.0.3 preinstall script 'npm install bloom-filte
r-cpp && npm install hashset-cpp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ad-block package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install bloom-filter-cpp && npm install hashset-cpp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ad-block
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ad-block
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jdoe\AppData\Roaming\npm-cache\_logs\2017-05-04T19_08_46
_665Z-debug.log
```
- Can this issue be consistently reproduced?  Yes.  I had same issue on Windows 10 laptop at home.

**Comment by NejcZdovc** [comment]
@philkloose do you have python 2.7 installed and set. This was why it wasn't working for me the last time I was setting up windows machine

**Comment by philkloose** [comment]
@NejcZdovc I do indeed.  And as far as I can tell I have all my other variables set properly per the Wiki instructions.

**Comment by philkloose** [comment]
I replaced the preinstall line for the ad-block package to this
`git clone --depth=1 https://github.com/bbondy/hashset-cpp node_modules/hashset-cpp && git clone --depth=1 https://github.com/bbondy/bloom-filter-cpp node_modules/bloom-filter-cpp`
as the PR suggested and sure enough everything worked.

**Comment by Jacalz** [comment]
Do you have windows build tools installed?

**Comment by philkloose** [comment]
Yes, Microsoft Build Tools 2015 (v17.0.23107.10).
