### ISSUE TITLE
PDFs fail to load if behind basic auth

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8702]
If a pdf file is behind basic auth, then it fails to display with our pdfjs extension.

Steps to reproduce: 
1. Download this script and extract it to your home directory
[SimpleHTTPAuth.py.zip](https://github.com/brave/browser-laptop/files/977487/SimpleHTTPAuth.py.zip)

2. Start it `python SimpleHTTPAuth.py 9001 u:p`
3. Navigate to `http://localhost:9001/type.pdf`

Note it works in Chrome with pdfjs but not in Brave built in.

CC @diracdeltas

**Comment by tpeacock19** [comment]
Has this issue been addressed? I'm still seeing it with the most recent release (0.55). I can't view any pdfs that are within my school's login portal, I only see the following error:

>Invalid or corrupted PDF file.
>PDF.js v2.0.673 (build: 31012570)
>Message: Invalid PDF structure

This works in in chrome, and in my nextcloud instance where the pdf is displayed using pdf.js within an iframe.

**Comment by mwdiers** [comment]
I have the same problem. This is preventing me from using Brave with my company's ERP system, and many other places, such as Lulu.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1788 (which is the repo for our new code-base, brave-core 😄). If you get a chance, please give it a +1

**Comment by diracdeltas** [comment]
commented here: https://github.com/brave/brave-browser/issues/1788
