### ISSUE TITLE
URL bar, on every keystroke the browser re-checks if the current location is bookmarked

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#8703]
With 10,000 bookmarks, this adds 80ms to every keystroke.

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Instrument `siteUtil.isSiteBookmarked()` by adding to the beginning `const startTime = new Date().getTime()` and to the end console.log(`isSiteBookmarked() ${new Date().getTime() - startTime}`).
    2. Start a new profile and import 10,000 bookmarks.
    3. Type in the URL bar and observe logs.
    
- Actual result:
2 calls for 40 ms / keystroke

- Expected result:
No calls. (It should only check if the location changes.)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. The "forsaken" sync group has a lot of bookmarks. It might help you if you're testing.

- Any related issues:
#7453

**Comment by bbondy** [comment]
A couple days ago you mentioned there was a little bug in this, is it still happening or is this ready to be reviewed?

**Comment by bbondy** [comment]
a faster way to fix this would be to move the component into it's own React component and only pass in the location and not the state about url input to that control.  Then it would only check when the actual page url changes. 

@ayumi that might be a .300 fix to do instead if you think yours is too risky this late in the game. And keep the current fix you have for .400.
