### ISSUE TITLE
brave won't open on win10, won't uninstall either

### ISSUE THREAD

**Issue by jkplanb** [brave/browser-laptop#8705]
A couple of months ago Brave stopped opening in Windows 10. Well that's not quite true; it opened into the tray but wouldn't maximise no matter what. I have just moved to another browser but I want my Brave. So I tried to uninstall it so as to reinstall but it won't using control panel.

**Comment by bsclifton** [comment]
@jkplanb not sure if you're still using Brave... but you can always try out latest release. I know we've fixed a lot of issues with hung processes 😄
