### ISSUE TITLE
Add our own extensions easily?

### ISSUE THREAD

**Issue by JMccormick264** [brave/browser-laptop#8706]
- Did you search for similar issues before submitting this one?
Yes

When will we get the ability to add custom extensions? I really want to use Reddit Enhancement Suite, I currently build it from the source for Edge, but I don't see any easy way of doing without having to build the Brave source too. Is there an ETA for being able to like in Reddit-Enahncement-Suite's case, git pull the latest code, build it and then put that into Brave without having to build the brave source along with the Extension?

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10

- Any related issues:
https://github.com/brave/browser-laptop/issues/253

**Comment by edouard-lopez** [comment]
You can [read my comment](https://github.com/brave/browser-laptop/issues/7846#issuecomment-288578739) to Install [LessPass extension](http://lesspass.com/). Remember it's an hackish solution.

**Comment by JMccormick264** [comment]
LastPass is already supported though. I was meaning like custom extensions. Reddit-Enhancement-Suite and others like that. Open source ones that can be built manually. Since there is no Brave Extension store, compiling them yourself and adding them in yourself is what I am looking for and hoping that there is a plan on a way to do this.

**Comment by luixxiul** [comment]
just fyi It's not LastPass that @edouard-lopez mentioned, it's *Less*Pass. @edouard-lopez explains there how to install an extention by yourself.

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/253
