### ISSUE TITLE
Address bar keyboard navigation on enter keydown

### ISSUE THREAD

**Issue by iH8** [brave/browser-laptop#871]
On W10, when typing the first letters of an address i visited before then cursor down to the result and press enter, it doesn't select the address. Mouseclick works. An animated gif says it all:
![brave](https://cloud.githubusercontent.com/assets/692063/13255092/baab01ce-da44-11e5-843e-c91117fcce88.gif)

**Comment by bbondy** [comment]
This is fixed here:
https://github.com/brave/browser-laptop/issues/836

And will be in the next release.

**Comment by iH8** [comment]
Ok, great work, sorry for the dupe, forgot to remove the `is:closed` while searching
