### ISSUE TITLE
Latest Dashlane extension (4.6.6) disappeared from context menu

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8718]
The latest version of Dashlane has disappeared from the context menu and is not functioning properly.

Please revert until we can confirm the issue is resolved.

**Comment by luixxiul** [comment]
similar issue? https://community.brave.com/t/hushmail-not-logging-in/4417

**Comment by srirambv** [comment]
Dashlane has never showed up on Context menu. Same behavior on Chrome.

**Comment by luixxiul** [comment]
Closing as stale.
