### ISSUE TITLE
Memory leak for cert-error listeners

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#872]
![screenshot 2016-02-23 10 22 55](https://cloud.githubusercontent.com/assets/831718/13256182/a89c0ea6-da17-11e5-85f2-a7e78e847dfe.png)

Pls fix, I had to move the similar ones into windowStore for shortcut listeners.

**Comment by bbondy** [comment]
I do have exactly 11 tabs open btw.  I think ideally we'd have 1 and then route it to the right frame if that's possible.

**Comment by diracdeltas** [comment]
sgtm will do
