### ISSUE TITLE
Add Bookmark doesn't work from context menu

### ISSUE THREAD

**Issue by seeam** [brave/browser-laptop#873]
The option is disabled, I'm using it on windows 8.1. See the picture:
![screenshot_9](https://cloud.githubusercontent.com/assets/7550283/13259169/66458a8c-da80-11e5-8c94-1d29b04fc4b5.png)

**Comment by bbondy** [comment]
This is fixed in the current version 0.7.16 (not yet released).  I can't remember if we had it in for 0.7.15 but in any case it will be working on this next release.   Thanks for posting!
