### ISSUE TITLE
Video doesn't play when opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8738]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Video doesn't play when opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.3
rev	1c04c53

- Steps to reproduce:
    1. Clean install 0.15.3 Preview 3
    2. Open a new tab and click on the YouTube tile
    3. Video buffers and after a min shows message `If playback doesn't start, try restarting your device` instead of playing the video immediately after loading the page
    
- Actual result:
Video doesn't autoplay

- Expected result:
Should play video when the link is opened

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![youtube](https://cloud.githubusercontent.com/assets/17010094/25773363/0619e2a0-3274-11e7-8d13-dc1c2cd8337d.gif)

- Any related issues:
#2227 #4045 #7663
cc: @jonathansampson @darkdh @bridiver

**Comment by luixxiul** [comment]
It seems that it is because "allow autoplay media" is enabled by default.

Some kind of layer/popup/placeholder (with dark transparent background like modal dialog) definitely should be there in terms of UX. otherwise people would complain, "why did you guys stop autoplaying youtube video?"

**Comment by luixxiul** [comment]
I added my own first impression with a couple of suggestions: #8739

**Comment by darkdh** [comment]
I will apply 1. and 3. suggestions from #8739
