### ISSUE TITLE
enable linux sandbox

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#874]
The sandbox is currently disabled on linux 
see #715

**Comment by luixxiul** [comment]
Is this still ongoing?

**Comment by posix4e** [comment]
Fixed in c54 good to close?

**Comment by luixxiul** [comment]
Do we need QA for this?

**Comment by posix4e** [comment]
You'll needf to test it on the chromium 13 build. Love to have a testy.

**Comment by bbondy** [comment]
@posix4e could you suggest how QA can verify that the sandbox is active? After please update the label to qa steps specified.

**Comment by posix4e** [comment]
Will do
