### ISSUE TITLE
Ctrl+W does not close a tab until another tab is hovered

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8740]
**Describe the issue you encountered:** Ctrl+W does not close a tab.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 1c04c53

- Any related issues:

**Comment by luixxiul** [comment]
File -> Close on the main menu does not close tabs either

**Comment by luixxiul** [comment]
`History -> Home` also seem to be corrupted.

**Comment by NejcZdovc** [comment]
Is this limited to debian only?

**Comment by darkdh** [comment]
@NejcZdovc it happens on Mac too

**Comment by bsclifton** [comment]
@luixxiul do you have more info?  There is a bad bug which may be masking this behavior:
https://github.com/brave/browser-laptop/issues/8640

Basically, if you mouse over any other tab... the Ctrl + W goes to that window instead.  So it can appear that it's not working when it really does

**Comment by luixxiul** [comment]
@bsclifton yeah after I move mouse over other tabs the shortcut/menu started working.

**Comment by bsclifton** [comment]
@luixxiul hovering over another tab (because of the bug) should be causing that tab to closed or given input from the URL bar. Basically, once a tab is focused, it's as if you switched to it (even if you didn't).  This is the bug that's captured

Do you think this issue here is a duplicate?

**Comment by luixxiul** [comment]
I could reproduce the bug you found, though I cannot tell if they have the same cause (surely they are related)

**Comment by NejcZdovc** [comment]
@bsclifton @luixxiul I am right now trying to find out why #8640 is happening. I have some leads, but nothing concrete yet.

**Comment by NejcZdovc** [comment]
@luixxiul can you try it again with the latest master? I think this should be fixed now.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/8782
