### ISSUE TITLE
Add sufficient test plans to issues for 0.15.3

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8743]
**Describe the issue you encountered:** Add sufficient test plans to issues for 0.15.3

https://github.com/brave/browser-laptop/issues?q=is%3Aissue+label%3AQA%2Fsteps-required+is%3Aclosed+milestone%3A0.15.300

Please make sure that if test plans are not speficied issues will not be tested by QA team or confirmed that commits for the issues should work as expected. I am emphasizing it as we are getting severe bugs that should block the release. Thanks for understanding 🦁 

- Any related issues:

**Comment by luixxiul** [comment]
If the change is so wide that you cannot specify what should be tested, please have a look at https://github.com/brave/browser-laptop/wiki/Manual-Tests and ask reviewers to run the tests to avoid general regressions. 

Even though the amount of the tests would be huge, they would definitely reduce chances of regressions and the works which might have been unnecessary if the change would be tested well.

**Comment by alexwykoff** [comment]
I almost wish we could add this to the PR template 😸 

Since there aren't any direct action items for this issue, should we not close it?
