### ISSUE TITLE
On tab hover causes current tab history to disappear

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8745]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
On tab hover causes current tab history to disappear

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.3
rev	1c04c53

- Steps to reproduce:
    1. Clean install 0.15.3 Preview 3
    2. Open a tab and visit a site and navigate few pages to generate history and back view 
    3. Open a second tab and repeat the same to generate tab history and keep focus on the second tab
    4. Hover over the first tab from step 2 to generate tab preview
    5. Focus back to second tab, back/forward button gets disabled
    6. Click on first tab and switch back to second tab, back/forward button magically comes back and able to click and navigate back/forward tab history
    
- Actual result:
On tab hover causes current tab history to disappear

- Expected result:
On tab hover should not cause any change to current tab behavior

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @bsclifton @NejcZdovc 
May be #8731

**Comment by luixxiul** [comment]
Also maybe: #8740 #8640

**Comment by NejcZdovc** [comment]
yeah this is a dup of #8640
