### ISSUE TITLE
PDF failed to load

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#8748]
- Did you search for similar issues before submitting this one?

No

- Describe the issue you encountered:

I tried to load a pdf file, but appear this message: 
PDF.js v1.7.428 (compilação: db86bc1d)
Mensagem: stream must have data

- Platform (Win7, 8, 10? macOS? Linux distro?):

Ubuntu 64

- Brave Version (revision SHA):

Brave 0.15.2

- Steps to reproduce:
    1. Tried to load a pdf file on intermedium.com.br site. To reproduce the problem is necessary to have a bank account on intermedium

- Actual result: 

See the screenshot

- Expected result:

Load the pdf file. All other browsers,  Google Chrome, Opera, I can see the pdf content.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

Yes

- Screenshot if needed: 
![captura de tela de 2017-05-07 13-22-56](https://cloud.githubusercontent.com/assets/1178856/25782903/1b483b3a-3329-11e7-99aa-59539fe28c91.png)

**Comment by bitcoinuser** [comment]
Still not working on Brave 0.16.9

**Comment by bsclifton** [comment]
+1 from myself and @bridiver 

This is happening to us when we're logged into the Prism HR software and try to open something that triggers the download / opening of a PDF (viewing paystub, etc)

![screen shot 2017-08-16 at 8 44 04 am](https://user-images.githubusercontent.com/4733304/29372227-5ed009d4-825f-11e7-9933-7576bc0b68a9.png)

**Comment by bsclifton** [comment]
Should be retested after the next pdf.js release

**Comment by bsclifton** [comment]
UPDATE: I retested and this is not fixed by https://github.com/brave/pdf.js/pull/3

**Comment by bitcoinuser** [comment]
Hi, why this was not fixed? I see the same problem on Brave Browser 0.55.18.
See: https://github.com/brave/brave-browser/issues/1757

**Comment by bsclifton** [comment]
Tracked in brave-browser with https://github.com/brave/brave-browser/issues/1287

Appears to have been fixed with https://github.com/brave/brave-core/pull/780
