### ISSUE TITLE
Suspended tabs reload when restoring the browser window

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8749]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When having unloaded tabs in the tabsbar and then minimizing the browser loads them again.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10
- Brave Version (revision SHA):
0.15.2
- Steps to reproduce:
    1. Go to youtube and right click a couple of videos to open in a new tab
    2. Minimize the browser
    3. Open it up again
    
- Actual result:
Tabs are loaded
- Expected result:
Tabs should stay unloaded
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
Yes

**Comment by TheHaricover** [comment]
Same issue here. Happens all the time, and I couldn't find a way to avoid it. Just leave the browser maximized and use other applications in front of the browser is the only solution but it prevent from going to the desktop.

**Comment by Jacalz** [comment]
+1 from https://github.com/brave/browser-laptop/issues/11990

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/restored-minimized-brave-starts-loading-all-tabs/12261?u=eljuno

>- Open the Brave explorer with lots of open tabs - just 1 selected tab loads;
>- Minimize Brave explorer and after restore it from Taskbar, all tabs start loading - that’s the buggy part.

Windows 8.1, 64 bit.
Brave 0.19.117
rev 90a5b22

**Comment by riuytro** [comment]
I deal with this everyday.  I just restart the browser every time.  How has this still not been fixed.  Please provide options to make rules on when tabs can load or unload, maybe even unload on command.

**Comment by jonathansampson** [comment]
I just hit this as well in 0.20.30.

### Repro Steps:
1. Load Brave with several unloaded tabs
2. Minimize Brave
3. Immediately restore Brave from the taskbar

``` 
Brave: 0.20.30 
V8: 6.4.388.40 
rev: 8b78402e7b3b91d44d8146cbe4dc8013592c33fd 
Muon: 4.7.9 
OS Release: 10.0.16299 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.119
```

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/when-going-with-mouse-over-a-tab/17970?u=eljuno

**Comment by bsclifton** [comment]
+1 from @BXVIII via https://github.com/brave/browser-laptop/issues/13066
> **_Detailed method_**
>   1. Open browser application  
>   Find a default autoplay video (Youtube video)
>   Clone the tab, keeping one pinned. 
>   Pause both videos so they aren't playing 
>   Open a new tab, remain on that tab. 
>   Close application 
> 
>   2. Open application 
>   Do not click on any of the tabs which have videos in it 
>   Minimize application 
>   Open application
>   Pinned tab begins autoplaying
> 
>   3. Minimize application
>   Open application
>   Other video tab begins autoplaying
> 
> 
> 
> **_Quick method_**
> 1. Head over to Youtube.com 
> 2. Find a video middle click > creating new tab (using a mouse).  
> Don't click on the new tab remain on current tab
> 3. Minimize application
> Open application 
> Video begins autoplaying without viewing the tab.
