### ISSUE TITLE
Dropping a URL onto URL bar regressed creating a new tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8750]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you drop a file onto the URL bar it should load a new tab with the URL.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
latest

- Steps to reproduce:
    1. Drop a file onto the urlbar
    
- Actual result:
Uncaught TypeError: windowActions.newFrame

- Expected result:
Creates a new tab with the url

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

Introduced here, probably a rebase problem:
https://github.com/brave/browser-laptop/commit/1cdaaf3e0a6adf7960c922cba819715def37ead5#commitcomment-22049535

**Comment by srirambv** [comment]
Dropping a file on URL bar doesn't load the file on Windows with 0.15.301
![8750](https://cloud.githubusercontent.com/assets/17010094/25962693/a041afa6-3676-11e7-828d-a167af2f8b70.gif)

Little confused with the title and the STR. Guessing it is about dropping a file on URL bar

**Comment by NejcZdovc** [comment]
@srirambv can you please try again. I can't reproduce this on a latest master (macOS).

**Comment by luixxiul** [comment]
maybe then it's a windows specific issue.

**Comment by bbondy** [comment]
There was a second independent but from the first fix which was only present on Windows. Where we'd encode file drops' backslashes causes the file URL path to be invalid.
