### ISSUE TITLE
Bookmarks Manager folder area has scrollbar in wrong position

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8753]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When visiting about:bookmarks, if the window is large, the scrollbars are put into the wrong place

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.15.3 preview 3

- Steps to reproduce:
    1. Visit about:bookmarks
    2. Have enough folders that it causes scrolling (make window less tall if needed)
    3. Make the screen very wide. Scrollbars will eventually go in wrong place
    
- Actual result:
See screenshot

- Expected result:
Scrollbar should line up w/ edge

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![screen shot 2017-05-07 at 11 07 12 pm](https://cloud.githubusercontent.com/assets/4733304/25792327/d3b7ebf6-337a-11e7-9414-73a4bc2c3501.png)

- Any related issues:

**Comment by bsclifton** [comment]
@cezaraugusto I believe this is happening after https://github.com/brave/browser-laptop/pull/8532

I assigned 0.15.3 in case you had time. If not, it's all good- this is low priority and you can remove the milestone.  Thanks 😄

**Comment by drcayman** [comment]
@bsclifton   Create a new Brave browser release windows CERT_PASSWORD=‘password-here’ What is password-here?

**Comment by bsclifton** [comment]
@drcayman where did you see that?

**Comment by Liunkae** [comment]
@drcayman @bsclifton Probably the "building releases" documentation: https://github.com/brave/browser-laptop/blob/c868874c13ca8e3f3ba4b5d50fc177bf5596bbf3/docs/buildingReleases.md#create-a-new-brave-browser-release
