### ISSUE TITLE
Create a new Brave browser release   CERT_PASSWORD=‘password-here’      What is password-here?

### ISSUE THREAD

**Issue by drcayman** [brave/browser-laptop#8757]
Create a new Brave browser release   windows   CERT_PASSWORD=‘password-here’      What is password-here?

**Comment by bsclifton** [comment]
@drcayman you are referring to these documents, right?
https://github.com/brave/browser-laptop/blob/master/docs/buildingReleases.md

Building a release is something we do at Brave Software. We have the process documented for ourselves but it involves steps that must be done by employees.  For example, there is an authenticode certificate on Windows for signing (and a similar cert on macOS)

The password value for the field above is private and along with our certificates, it won't be shared
