### ISSUE TITLE
Unable to view HTTPS certificate (0.15.2, FC25 Gnome)

### ISSUE THREAD

**Issue by chotaire** [brave/browser-laptop#8758]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
When trying to view a certificate (CTRL+SHIFT+I), then click on "View certificate", no window opens. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Fedora 25, Gnome

- Brave Version (revision SHA):
0.15.2

- Steps to reproduce:
    1. Go to  a HTTPS website
    2. Hit CTRL+SHIFT+I
    3. Click on "view certificate"
    
- Actual result:
Nothing happens

- Expected result:
Open a Popup and show certificate

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
When we implemented show certificate, we only did so for macOS and Windows.  You can track the status for Linux with https://github.com/brave/browser-laptop/issues/7669
