### ISSUE TITLE
 bookmarks bar should show a folder icon for each folder

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8759]

**Comment by bsclifton** [comment]
@alexwykoff do you have more details about this? I can't recall a situation where the folder didn't show an icon

**Comment by Liunkae** [comment]
Even when favicons are disabled? Current behavior for text-only:
![](https://cloud.githubusercontent.com/assets/19424103/25812670/a6eebf34-33dc-11e7-804e-06d3c4bc24f5.png)
This matches Safari's behavior:
![](https://cloud.githubusercontent.com/assets/19424103/25812727/d1825684-33dc-11e7-8bb4-e47966b18629.png)

**Comment by alexwykoff** [comment]
@bradleyrichter and i were discussing a prior comment from a reviewer. apparently they expected to see a folder. no rush.
