### ISSUE TITLE
Replace slashdot in braveryTestPanel.js with our own iframe to fix travis error

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8760]
## Test plan
https://github.com/brave/browser-laptop/pull/9148#issue-232353963

`npm run test -- --grep="Adblock stats iframe tests"`

----

**Describe the issue you encountered:** It seems that the travis tests which display `slashdot.org` in an iframe fail a lot of times (or always):

https://travis-ci.org/brave/browser-laptop/jobs/229862037#L4225
https://travis-ci.org/brave/browser-laptop/jobs/229553024#L4252
https://travis-ci.org/brave/browser-laptop/jobs/229253934#L4111

Locally the tests fail intermittently.

The tests are described here: https://github.com/brave/browser-laptop/blob/deddb5a017544cd701ad07e36c03dfcc3652967e/test/bravery-components/braveryPanelTest.js#L239-L292

We would have to create our own iframe to fix the error. I'm assigning the task with @bridiver for now per https://github.com/brave/browser-laptop/commit/f78430c6e9eed74d4f6c42a2fbed9bb97900de04#diff-c98f35b50afd3f874bd2cf4a51548112R215, though someone else could take it I think.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
I replaced `slashdot` with `msnbc` and ran travis tests on my own forked repo, and still got the same timeout errors, not only on travis but locally. Probably the errors are not related with sites but with our own codes. When I manually ran the test only, the 

On error, the test process is stuck at `tabHandles()` as follows:

````
waitForDataFile("adblock")
getAppState()
waitForDataFile("adblock") => {"count":0,"etag":"\"e99b13e2c8d64c2a8828dc3f71e187e9\"","lastCheckDate":1494608690770,"lastCheckVersion":3}
tabByIndex(0)
tabHandles()
tabHandles() => handles.length = 1; handles[0] = "CDwindow-3e61e959-1b5f-4a11-828b-a08b79d6b735";
loadUrl("http://localhost:60269/msnbc.html")
loadUrl.url() => {"sessionId":"9618dcae14fc2519499504c8555bfaf4","status":0,"value":null}
waitForUrl("http://localhost:60269/msnbc.html")
tabByUrl("http://localhost:60269/msnbc.html")
tabHandles()
tabByUrl("http://localhost:60269/msnbc.html") => {"sessionId":"9618dcae14fc2519499504c8555bfaf4","status":0,"value":null}
openBraveMenu()
waitForBrowserWindow()
windowByUrl("chrome://brave/Users/Suguru/browser-laptop/app/extensions/brave/index.html")
windowByUrl("chrome://brave/Users/Suguru/browser-laptop/app/extensions/brave/index.html") => ["chrome://brave/Users/Suguru/browser-laptop/app/extensions/brave/index.html"]
waitForBrowserWindow() => {"sessionId":"9618dcae14fc2519499504c8555bfaf4","status":0,"value":null}
waitForSelectedText(".braveryStat.adsBlockedStat", "0")
waitForTextValue(".braveryStat.adsBlockedStat", 0) => 0
waitForTabCount(2)
getTabCount()
tabHandles()
      2) detects blocked elements in iframe
waitForBrowserWindow()
windowByUrl("chrome://brave/Users/Suguru/browser-laptop/app/extensions/brave/index.html")


  0 passing (1m)
  2 failing

  1) Bravery Panel Adblock stats iframe tests detects blocked elements in iframe in private tab:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Bravery Panel Adblock stats iframe tests detects blocked elements in iframe:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
````

I notice that sometimes running `Bravery Panel` test locally, the blank tab (default/private) appears and stuck without loading a dashboard. I think that kind of issues happens there.

**Comment by luixxiul** [comment]
looks the tests are passing:

https://travis-ci.org/brave/browser-laptop/jobs/240232452#L3023
https://travis-ci.org/brave/browser-laptop/jobs/240232452#L3024

**Comment by bridiver** [comment]
we should avoid using external URLs for testing unless there is no way to simulate locally
