### ISSUE TITLE
History entries often cannot be deleted

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#8761]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Often when using `Delete History Entry`, the history entry's timestamp is removed but the item is not deleted.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Found on macOS 10.12.x.

- Brave Version (revision SHA):
0.15.2 (af7ef42)

- Steps to reproduce:
    1. Open a new Brave tab and visit github.com (make sure you are logged out).
    2. Visit each of the options at the top (Features, Business, Explore, and Pricing).
    3. Open about:history.
    4. Right-click one of the entries (e.g., Pricing) and click Delete History Entry.
    
- Actual result:
The history entry is moved to a section with no timestamp and is not deleted (see screenshot).

- Expected result:
The history entry should be completely deleted.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not sure.

- Is this an issue in the currently released version?
Yes, 0.15.2.

- Can this issue be consistently reproduced?
Yes, with the steps above. It doesn't happen with every single time, though.

- Extra QA steps:
    1. Open a new Brave tab and visit github.com (make sure you are logged out).
    2. Visit each of the options at the top (Features, Business, Explore, and Pricing).
    3. Open about:history.
    4. Right-click one of the entries (e.g., Pricing) and click Delete History Entry.
    5. Make sure the history item is deleted.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/19424103/25813437/2c04d968-33df-11e7-85d5-d7e20e21680b.png)

- Any related issues:
None.

**Comment by eljuno** [comment]
It happens to me, too, 0.15.2 (af7ef42).
I reported in community few days ago. https://community.brave.com/t/long-history-list-with-no-time-and-can-not-be-deleted/2693?u=eljuno

For now, I can delete it by clearing browsing data (`Ctrl+Shift+Del`). The history completly vanish. But when I manualy delete the entry, it repeat again.

Here's an additional record:
![brave-history-bug](https://cloud.githubusercontent.com/assets/25360853/25823233/9c607290-3465-11e7-8014-417d982d70b7.gif)

**Comment by Liunkae** [comment]
@eljuno Thanks for the screen recording! Looks like it's happening on Windows too.

**Comment by eljuno** [comment]
@Liunkae ah, yes. I'm on Windows 8.1.

**Comment by zolk3ri** [comment]
I experience the same issue on Arch Linux, 0.15.2.

**Comment by Liunkae** [comment]
Still a problem with 0.15.3xx. @bsclifton Any ideas?

**Comment by Liunkae** [comment]
Still happening with Brave 0.16.6 (51de9af).

**Comment by iSasFTW** [comment]
Still happening on Brave 0.17.13, Windows 10.

**Comment by diracdeltas** [comment]
bumping milestone to 0.19.x since https://github.com/brave/browser-laptop/issues/9715 was set to that

**Comment by diracdeltas** [comment]
similar issue: if you right click to delete a history entry, it still shows up in the History menu
