### ISSUE TITLE
 extensions need a way to check for updates out of band from browser releases

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8762]
currently when testing extension updates, the only method possible is to delete the currently installed extension and look to see that the new version is downloaded. 

what needs to be possible is : 

1.  a means of triggering a check for updates
1. if a new extension version is available, download it
1. when the new extension is downloaded, replace the currently installed extension, restart if needed

**Comment by diracdeltas** [comment]
@alexwykoff i think the title is referring to an issue that is already solved. the browser checks for extension updates periodically, it doesn't require a new browser release.

**Comment by alexwykoff** [comment]
while the browser does check for extension updates periodically, there needs to be a means to manually trigger the check instead of waiting for an indeterminate period of time. 

i agree it doesn't require a new browser release, but i was unaware of the actual length of the period.

**Comment by alexwykoff** [comment]
Users can force a check by toggling the extension on about:extensions. All other questions are covered here (mostly in footnotes) : https://github.com/brave/browser-laptop/wiki/Developer-Notes-on-Installing-or-Updating-Extensions
