### ISSUE TITLE
Google images is not dragable between tabs

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#8763]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
From community:
There's this unique feature in Google Images where by it allows users to drag and drop images into the search bar and Brave doesn't allow users to move images from a tab into another tab.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Probably on every but confirmed win 10!
- Brave Version (revision SHA):
0.15.2
- Steps to reproduce:
    1.  Open two tabs with google images
    2.   Try draging a picture from tab two to tab 1
    3.   Note that it doesnent work

Alternative steps:

   1. Open two tabs with google images
    2. Drag a picture and press ctrl +1 on the keyboard
    3. Try dropping the picture in the search bar
    
- Actual result:
Nothing really happends
- Expected result:
Should switch to tab 1 when draging the picture over that tab and then let you
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes and probably in every version
- Can this issue be consistently reproduced?
Yes

**Comment by WausauBill** [comment]
I can confirm that this description is correct for the beta on Linux as well.  The behavior does work as the OP states in Chrome on Linux.

 
Brave: 0.20.15 
V8: 6.3.292.48 
rev: 6fd801b0cb23c8d22c2653f66fd61ed6b813ce79 
Muon: 4.5.33 
OS Release: 4.8.0-53-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 63.0.3239.108

**Comment by Jacalz** [comment]
This is going to be fixed with Brave-core
