### ISSUE TITLE
Do not show thumbnails on tab

### ISSUE THREAD

**Issue by datelligence** [brave/browser-laptop#8766]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by datelligence** [comment]
How can thumbnails be disabled by default?

**Comment by bsclifton** [comment]
@datelligence do you mean the thumbnails on the new tab screen?  If you'd like to disable these, we do have an issue tracking it which you can find here: https://github.com/brave/browser-laptop/issues/6042

Feel free to give that one a +1 (by leaving a comment or adding a thumbs up to the original post) and we can close this one as a duplicate

**Comment by bsclifton** [comment]
Marking as dupe and closing
