### ISSUE TITLE
Add ability to update to preview releases (with advanced option)

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#8769]
This issue tracks the upgradeable preview browser project. A separate issue will track the server side requirements.

**Comment by Jacalz** [comment]
This will be great 👍Will this also fix that it asks you to update to the stable channel when using the preview version? @aukeus

**Comment by luixxiul** [comment]
How about letting users manage profiles or creating a incremental backup of the profile per each preview for users to restore it in case the browser preview crashes suddenly and the data is lost?

Users would like to test previews and send a bug report, as long as they know data would be kept safe... I feel it is a bit harsh to say "you should test on your own responsibility."

**Comment by alexwykoff** [comment]
Test Plan : 
We should be able to update to preview builds from here on.

**Comment by bsclifton** [comment]
@aekeus to add steps 😄
