### ISSUE TITLE
Speedtest fails when adblock is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8772]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported on community https://community.brave.com/t/speedtest-net-beta-not-working-properly/2325/2

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 8.1

- Brave Version (revision SHA):
>Brave: 0.14.1 
rev: 3de60d52 
Same on 0.15.2 as well

- Steps to reproduce:
    1. Disable FP protection and visit beta.speedtest.net
    2. Enable ad block, fails to load test
    3. Disable adblock able to perform speedtest
    
- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25849054/d02828ee-34b4-11e7-8e8d-a2a253483122.png)

- Any related issues:

**Comment by luixxiul** [comment]
same as #979? even if not we could reopen it to work on fix

**Comment by srirambv** [comment]
Same as #979 but something else is changed this time. Before it would work when Fingerprint protection was disabled. Now it only works when adblock is disabled. We can reopen it not an issue. Will close this
