### ISSUE TITLE
Browser crashes randomly on the latest build

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8773]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser crashes randomly on the latest build

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.300
rev	4e322d6

- Steps to reproduce:
    1. Do a clean install of 0.15.300
    2. Open few tabs and keep browsing or change setting in preference which doesn't require restart
    3. Hope that it doesnt crash 
    
- Actual result:
Browser crashes randomly on the latest build

- Expected result:
Should not crash the browser

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
No error relating to crash on console but the below log is shown on launch or opening a new tab
```$ Crash reporting enabled
[12484:780:0509/181751.698:ERROR:connection.cc(1954)] Web sqlite error 5, errno 33: database is locked, sql: COMMIT
[12484:780:0509/181751.698:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 1
```

- Any related issues:
cc: @bsclifton

**Comment by twitchard** [comment]
This happened to me as well using 0.15.2-1. Archlinux x64
Any tips on how I get rid of the sqlite locks so I can use my browser again?

**Comment by darkdh** [comment]
@twitchard , I believe the crash introduced by muon 3.0.1 which is not in 0.15.2.
It should be only affect Windows and sqlite lock seems different issues.
