### ISSUE TITLE
download activity spinner in new tab keeps spinning after download complete

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8775]
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?): macos

- Brave Version (revision SHA):

- Steps to reproduce:
    1. try downloading a file in a new tab
    2. activity spinner spins as you'd expect
   
- Actual result: when download complete, activity spinner keeps spinning

- Expected result: activity spinner stops spinning when download complete

- Will the steps above reproduce in a fresh profile? yes

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: n/a

- Screenshot if needed: see below

- Any related issues: n/a
![1](https://cloud.githubusercontent.com/assets/400552/25866423/49ebb182-34ab-11e7-9a0f-0b727acbe550.png)

**Comment by bsclifton** [comment]
I believe this is the same issue as https://github.com/brave/browser-laptop/issues/8584

@mrose17 do you have new tabs set to open `about:blank`?

**Comment by mrose17** [comment]
yes, so this one is a dup... thanks!
