### ISSUE TITLE
Windows no longer have proper border when focused/unfocused 

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8778]
Windows will usually have the blue border when a window is focused which turns into a gray border when the window loses focus.  This functionality was broken with https://github.com/brave/browser-laptop/commit/901d5dba082a5e5d5213d726337a532b95b269d6 and was never restored.  The single window action `onFocusChanged` was split out into `onFocus` and `onBlur`, but nothing calls them

**Comment by srirambv** [comment]
Still right bluish border is missing  on 0.15.301. @bsclifton  is this still expected behavior on Windows?

**Comment by bsclifton** [comment]
@srirambv yes- this is captured with https://github.com/brave/browser-laptop/issues/6698
