### ISSUE TITLE
Launching browser in maximised position causes a 1px gap between browser window and the taskbar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8784]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Launching browser in maximised position causes a 1px gap between browser window and the taskbar

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.2
rev	af7ef42

- Steps to reproduce:
    1. Set browser to maximised position
    2. Close and relaunch the browser
    3. Browser launches in maximised position but is actually in restore position
    4. There is a 1px gap between browser window and taskbar
    5. CLick on maximise button, fits the browser window correctly on top of the taskbar
    
- Actual result:
Launching browser in maximised position causes a 1px gap between browser window and the taskbar

- Expected result:
Should launch in a maximised state and should properly fit on screen above the task bar

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#7215 
Marking it as 0.15.400. Feel free to pull it back in to 0.15.300 if required

**Comment by srirambv** [comment]
+1 from comminity https://community.brave.com/t/does-not-re-maximize-properly/3225/

**Comment by bsclifton** [comment]
This is upstream from us (Chromium). More info here:
https://github.com/electron/electron/issues/8332

**Comment by Struisvogel93** [comment]
I got the exact same issue, specs here:
 
Brave: 0.18.23 
rev: 36ae2ec06efed0057ae16351108bf4d4c10a7ab4 
Muon: 4.3.10 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by Struisvogel93** [comment]
If I could fix this myself, I would've done it (unskilled in any form of programming). But can someone please look at this? I love the Brave Browser, but this is my Nr. 1 annoyance with Brave, has been for months lol :)

**Comment by NejcZdovc** [comment]
@Struisvogel93 there are some fixes in 0.20 version for maximize/fullscreen, so please check out 0.20.x when it will be in the beta channel

**Comment by Struisvogel93** [comment]
@NejcZdovc Thanks for your response, I will, as soon as it hits :)
