### ISSUE TITLE
Email Page Link shortcut doesn't work on Windows when protocol handler is linked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8787]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Email Page Link shortcut doesn't work on Windows when protocol handler is linked

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.300
rev	4e322d6

- Steps to reproduce:
    1. Register email protocol handler
    2. Click on Menu -> Share -> Email Page Link, opens a new tab with the registered protocol handler site
    3. Press shortcut Ctrl+Shift+I  shortcut as mentioned, opens page tools
    
- Actual result:
Email Page Link shortcut doesn't work on Windows when protocol handler is linked

- Expected result:
Should work as expected

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25901897/fe3fba4a-358f-11e7-81bc-547f033c135c.png)

- Any related issues:
#8517

**Comment by NejcZdovc** [comment]
I think this was fixed with cb3399aab1f95041868ab12a5e384af019b8b9a5, @bbondy removed shortcut for email share.
