### ISSUE TITLE
action chaining

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#88]
We often call several actions in a row that change state. This seems rather inefficient and we should be able to chain them together to update several values in a single dispatcher call

**Comment by bbondy** [comment]
- Blocked resources sends 1 per blocked resource, we could simply debounce this.
- Page load sends lots of different events, we can combine those in a better way.
- To find more we can also timestamp doAction in the window and app stores to find more ideas.

**Comment by bbondy** [comment]
Along these lines I was thinking we could do a performActions which takes an array of actions.

**Comment by bbondy** [comment]
Fixed the core problem here which bypasses this kind of worry:
https://github.com/brave/browser-laptop/commit/a314f241c2a8bedeacb1053aa0f10945c284598c
