### ISSUE TITLE
Extension API: chrome.tabs.onCreated

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8820]
https://developer.chrome.com/extensions/tabs#event-onCreated

- [x] chrome.tabs.onCreated.addListener(listener)
- [ ] chrome.tabs.onCreated.removeListener(listener)
- [ ] chrome.tabs.onCreated.hasListener(listener)

Blocks #6366, #9330, #9828

**Comment by jonathansampson** [comment]
This appears to be supported already.

**Comment by nobledemon** [comment]
When trying to use chrome.tabs.onCreated.addListener(callback) on the console of the chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/_generated_background_page.html it seems to work correctly. At least at first glance. New tabs fire the event just fine.

However, I tried using it in a custom background page and the event seems to be ignored. The extension has enabled tabs and activeTab on its manifest.

Brave: 0.18.36 
rev: 7ab85e97318fef041433b0c3d73b457205fae805 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 
V8: 6.1.534.32 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Comment by jonathansampson** [comment]
@nobledemon Is `bmnlcjabgnpnenekpadlanbbkooimhnj` your extension? If so, how was it loaded?

**Comment by nobledemon** [comment]
used about:preferences#extensions to enable Honey extension. Then navigated to %appdata%/brave/Extensions and just edited the extension.

**Comment by jonathansampson** [comment]
@nobledemon Can you also confirm for me that you have the "tabs" permission in your manifest?

**Comment by nobledemon** [comment]
both tabs and active tabs on the manifest. 
```
{
   "author": "NobleDemon",
   "background": {
      "page": "background.html"
   },
   "browser_action": {
      "default_icon": "icon.png",
      "default_title": "tab-tree"
   },
   "description": "this is a test test test test",
   "key": "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC79mayLyuCYY/dyT7Ycr1sVBp9yHrY4mnogVEgu+sDT6+/A121Na+aTw6mFLD6LHgbgHt4fnQ2V/QwcfBSXRTSkGpgNsZAjnYs4/XzZQYKGltWT93EP9zXN1kGbtzfkPGzTakquCfOjbKtbAQKWh8ppzqLhWcRUn9g/PhU99F29QIDAQAB",
   "manifest_version": 2,
   "name": "tab-tree",
   "permissions": [ "tabs", "activeTab" ],
   "version": "0.1"
}

```

**Comment by jonathansampson** [comment]
@nobledemon I just tried this in 0.19.16, and it appears to be working as expected. I navigated to my extension's _generated_ background page, and ran the following:

```js
chrome.tabs.onCreated.addListener(function () {
  console.log(arguments)
  console.log('Tab Created')
})
```

Then, I created a tab via the following:

```js
chrome.tabs.create({ url: 'https://bing.com' })
```

If you are still encountering issues, perhaps we can jump on a Hangout or Skype call and troubleshoot the extension together?
