### ISSUE TITLE
Menu not working as expected on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8821]
When I’m on Windows, press ALT, and I move the mouse over the menu, it auto expands
it doesn’t if I hover over File… but any other one it does

Clicking File doesn’t work- have to click it twice

Seen with 0.15.301

**Comment by NejcZdovc** [comment]
Also one more thing. You can't select first item with arrow keys. 

STR
1) click right arrow twice
2) click left arrow twice
3) you are stuck on `Edit`

**Comment by bsclifton** [comment]
I reproduced as far back as 0.13.5 (didn't check prior).  Since it's been an issue for a while (and definitely wasn't introduced with recent changes), I'm going to remove the milestone 😄
