### ISSUE TITLE
thisdot.co - email signup not working with Shields Up

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#8825]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Originally posted on Twitter: https://twitter.com/amadurell/status/862355511395614720

The email signup form on https://www.thisdot.co/javascript/05-2017 does not appear to work when shields are up. 

- Cookie controls do not appear to make a difference. 
- Disabling shields resolves the issue. 

Confirmed that this is an issue on Windows and macOS. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/af7ef42ad622f899312a38bdd0e2138154393627

- Steps to reproduce:
    1. Go to https://www.thisdot.co/javascript/05-2017
    2. Attempt to sign up (with default shield settings) 
    3. Get `enter a valid email address` response. 
    
- Actual result:

![brave-thisdotjs-compat-05102017](https://cloud.githubusercontent.com/assets/8979240/25922558/82892b76-358e-11e7-8d40-0757aa45e433.PNG)

- Expected result:

Successful signup. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

**Investigation:**
- [x] Confirm shield settings
- [x] Identify blocked requests
- [x] Confirm cookie controls
- [ ] Identify potential filter exceptions 
- [ ] Test potential exceptions 
- [ ] Migrate solution to appropriate destination for resolution.

**Comment by lukemulks** [comment]
Requests blocked by Shields: 
```
https://widget.intercom.io/widget/o8q1jqm4  

https://www.google-analytics.com/analytics.js  

https://thisdot.us12.list-manage.com/subscribe/post-json?u=81e8e3fa2a6f79fe97467029a&amp;id=762b8e8020&c=jQuery321042018364277670517_1494450145196&FNAME=some&LNAME=one&EMAIL=someone%40somewhere.com&_=1494450145197  

https://thisdot.us12.list-manage.com/subscribe/post-json?u=81e8e3fa2a6f79fe97467029a&amp;id=762b8e8020&c=jQuery321042018364277670517_1494450145196&FNAME=some&LNAME=one&EMAIL=someone%40somewhere.com&_=1494450145198
```

Testing filters now.

**Comment by taras** [comment]
Thank you for bringing this to my attention. I'm looking into this today.

**Comment by taras** [comment]
This issue should now be resolved.

**Comment by lukemulks** [comment]
@taras confirmed! Thank you very much for your help with this! :-)
