### ISSUE TITLE
Allow <site> to <action>?

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8826]
originally this was about flash, but #8828 fixes that.

however,  i am pretty sure than whenever someone answers "No" to an "Allow to " and selects "Remember this decision", then it is never remembered regardless of the choice. i know this is also the case with autoplay.

can we please have a systematic search of the code for all cases and ensure it works right?

## Test plan

https://github.com/brave/browser-laptop/pull/8828#issue-227841979

----

- Did you search for similar issues before submitting this one? yes.

- Describe the issue you encountered: "Allow ... to run Flash Player?" with "Remember this decision" doesn't seem

- Platform (Win7, 8, 10? macOS? Linux distro?): MacOS

- Brave Version (revision SHA): 4e86cab

- Steps to reproduce:
    1. go to a site that will cause the "Allow ... to run Flash Player?" notification
    2. click on "Remember this decision"
    3. click on "Deny"
    
- Actual result: the setting is *not* remembered

- Expected result: the setting is remembered

- Will the steps above reproduce in a fresh profile? yes

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none

- Screenshot if needed: see below

- Any related issues: none

![1](https://cloud.githubusercontent.com/assets/400552/25923728/bc426f58-3593-11e7-8943-0f884b4e402e.png)
![2](https://cloud.githubusercontent.com/assets/400552/25923729/bc43b106-3593-11e7-9a90-60c2fcfad520.png)

**Comment by mrose17** [comment]
@bsclifton - here is the first issue we discussed.

**Comment by diracdeltas** [comment]
pretty sure that 'remember this decision' + 'deny' never worked (only 'remember' + 'allow') so this isn't a regression

**Comment by mrose17** [comment]
@diracdeltas - ok, but we can agree that this is a bug, right?

@bsclifton - your thoughts? thanks!

**Comment by diracdeltas** [comment]
@mrose17 did you see the above? i already opened a PR for this

**Comment by mrose17** [comment]
yes, but i thought your PR was newer. never mind then.
