### ISSUE TITLE
Color in YouTube Video is so different in Brave VS Others!

### ISSUE THREAD

**Issue by iowbeoibewio** [brave/browser-laptop#8836]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Color  YouTube Video is so different in Brave vs all other browsers

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.4

- Brave Version (revision SHA):
Brave: 0.15.2 
rev: af7ef42ad622f899312a38bdd0e2138154393627 
Muon: 2.58.9 
libchromiumcontent: 58.0.3029.96 
V8: 5.8.283.37 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.5.0 
os.arch: x64

- Steps to reproduce:
    1. Open YouTube Video in Brave and in any other browser FF or GC, Safari etc...
    2. Set Video to HD (to make the problem more clearly) and pause the video in same moment in both browsers
    3. Check color different!!
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
The problem ONLY shown in YouTube, I tried with dailymotion and viemo and doesn't appear, and in images isn't appear too, so the problem is in YouTube ONLY.

This Different between Brave and Chromium

Brave
<img width="853" alt="screen shot 2017-05-11 at 6 40 16 pm" src="https://cloud.githubusercontent.com/assets/23007602/25958948/dfeb9f46-367a-11e7-8a99-e8f59b58fd5a.png">

Chromium, and mostly other Browsers
<img width="854" alt="screen shot 2017-05-11 at 6 40 08 pm" src="https://cloud.githubusercontent.com/assets/23007602/25958947/dfea3926-367a-11e7-9a00-38fc6dd64a42.png">

**Comment by t-logix** [comment]
![image](https://user-images.githubusercontent.com/31883029/32545956-a95b075a-c47d-11e7-81d0-721c0bbea4be.png)
Same difference with other elements (not just video) ,like this button^  
See discussion here https://community.brave.com/t/colors-are-different-compared-to-other-browsers/7943/4

Brave 0.18.36
ubuntu 16.04

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/something-is-wrong-with-color-in-brave-browser/10754/

**Comment by bsclifton** [comment]
@iowbeoibewio @diregro if you're still using Brave, can either of you try adding the following argument to the shortcut or when launching via command line?
`--force-color-profile=srgb`

I'll close this issue as I believe this should fix it. If you're still using Brave and this does not fix it, please let me know and I'll reopen this issue 😄 Thanks!

**Comment by bsclifton** [comment]
Related: https://github.com/brave/browser-laptop/issues/14688, https://github.com/brave/browser-laptop/issues/12059

**Comment by FeedTheWeb** [comment]
that does make it better,
But will that be a default setting for next releases?
