### ISSUE TITLE
Hiding menu shows empty white space

### ISSUE THREAD

**Issue by sorin-davidoi** [brave/browser-laptop#8839]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

Hiding the menu by pressing the alt key shows an empty space instead of hiding it.

- Platform (Win7, 8, 10? macOS? Linux distro?):

ArchLinux

- Brave Version (revision SHA):

0.15.301 (4e86cab)

- Steps to reproduce:
    1. Press Alt to hide the menu bar
    
- Actual result:

The menu bar is hidden, but an empty white container is shown instead.

- Expected result:

The menu bar is hidden, saving vertical space.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

- Screenshot if needed:
![brave-menu-hide](https://cloud.githubusercontent.com/assets/2109702/25960633/c7c0a9be-3677-11e7-8309-480f8a69ac18.gif)

**Comment by luixxiul** [comment]
I remember I noticed that kind of white space on Debian.

**Comment by sorin-davidoi** [comment]
I think it was introduced with 0.15.3 (did not noticed it with 0.15.2).

**Comment by admshao** [comment]
I have the same problem on Archlinux, 0.15.2 was fine

**Comment by bsclifton** [comment]
I think this problem is related to the changes I recently made in Muon with https://github.com/brave/muon/commit/5012b72485fbed0f4693bf9eb74c6d0ca40fb054

Linux has an open issue (captured in https://github.com/brave/browser-laptop/issues/5086) which I believe is the root cause for this

**Comment by sorin-davidoi** [comment]
Also noticed that the menu / white container does not disappear when a video is full-screen.

**Comment by admshao** [comment]
It does appear for me while in Video fullscreen. 
GNOME Shell 3.24.2 / XServer 1.19.3

**Comment by bsclifton** [comment]
Looking into this now...

**Comment by bsclifton** [comment]
Found the root cause and fixed 😄
