### ISSUE TITLE
Tab preview causes the tab content to be still shown as a preview rather than loading the content

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8842]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab preview causes the tab content to be still shown as a preview rather than loading the content

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.302
rev	81fd962

- Steps to reproduce:
    1. Open couple of tabs with an about page 
    2. Hove over the tab title to show preview
    3. Click on the hovered tab, content still shows as preivew. Hover back and click on the active tab shows the content properly
   4. About pages still remains as tab preview even after clicking on next tab 
    
- Actual result:
Tab preview causes the tab content to be still shown as a preview rather than loading the content

- Expected result:
Tab preview and tab content should be properly shown

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/25967881/7ecde842-3687-11e7-865b-b40640a0430d.png)
![tabpreview](https://cloud.githubusercontent.com/assets/17010094/25967896/8f7a28fe-3687-11e7-8680-ee64bee630c9.gif)
![image](https://cloud.githubusercontent.com/assets/17010094/25968201/8a33b13e-3688-11e7-91d1-8d31b5d0c500.png)
Console Log 
```[10732:4108:0511/200310.976:ERROR:CONSOLE(19773)] "Uncaught AssertionError: state must contain an Immutable.List of tabs", source: chrome://brave/C:/Users/Sriram%20BV/AppData/Local/brave/app-0.15.302/resources/app.asar/app/extensions/brave/gen/app.entry.js (19773)
[10732:4108:0511/200400.598:ERROR:CONSOLE(19773)] "Uncaught AssertionError: Could not find tab for 26", source: chrome://brave/C:/Users/Sriram%20BV/AppData/Local/brave/app-0.15.302/resources/app.asar/app/extensions/brave/gen/app.entry.js (19773)
[10732:4108:0511/200400.775:ERROR:CONSOLE(19773)] "Uncaught AssertionError: Could not find tab for 26", source: chrome://brave/C:/Users/Sriram%20BV/AppData/Local/brave/app-0.15.302/resources/app.asar/app/extensions/brave/gen/app.entry.js (19773)```

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
This was fixed this morning with https://github.com/brave/browser-laptop/commit/4211ee58a517c1a5e7e026f17dd5d9418b7c3b3e
