### ISSUE TITLE
Importer warning doesn't work

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#8846]
## Test plan

https://github.com/brave/browser-laptop/pull/8864#issue-228447209

----

STR:
1. Open firefox
2. Open Brave and import from firefox
3. There should be a warning dialog

Caused by https://github.com/brave/muon/commit/d534ffd919bc117ae527a60b747db41fff547f78

CC @bridiver

**Comment by bridiver** [comment]
you're working on this, right? Ticket is just for tracking?

**Comment by darkdh** [comment]
Yes, for tracking
