### ISSUE TITLE
 Regression - importing cookies not working

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8849]
STR: 
1. with a clean profile, launch the latest build of Brave 0.15.303
2. attempt to only import cookies from chrome / firefox

**Comment by darkdh** [comment]
It is not unresponsive of long running. The function on muon doesn't work due to https://github.com/brave/muon/commit/d534ffd919bc117ae527a60b747db41fff547f78.
Functions of importing cookies from both Firefox and Chrome is broken.

**Comment by bridiver** [comment]
Import runs in a service worker so shouldn't make the browser unresponsive. The code is mostly just moved to accommodate the removal of patches, can you look into this @darkdh?

**Comment by bridiver** [comment]
along with process singleton this was a known possible regression with the patch cleanup

**Comment by darkdh** [comment]
I've already looked into it. almost done.

**Comment by luixxiul** [comment]
I'm not sure if this was really fixed.

STR: 
1. Open chrome
2. Visit http://www.whatarecookies.com/cookietest.asp
3. Close chrome
4. Import cookie on Brave
5. Visit http://www.html-kit.com/tools/cookietester

Actual result: `no existing cookie was found for this website`

**Comment by darkdh** [comment]
It is expected. We can only import unencrypted cookies from Chrome. Unfortunately, the cookies we test are encrypted.
You can see the same behavior on Firefox. But you can try importing cookies from Firefox and see the cookie.

**Comment by srirambv** [comment]
>You can see the same behavior on Firefox. But you can try importing cookies from Firefox and see the cookie.

@darkdh importing cookie from Firefox still doesn't show up on Brave
![cookieimport](https://cloud.githubusercontent.com/assets/17010094/26398903/f07d6afe-4072-11e7-83b0-36e90b7e662c.gif)

**Comment by darkdh** [comment]
@srirambv, you did clear cookies before importing so there is nothing to import. you must have cookies set in firefox first
try this http://www.html-kit.com/tools/cookietester
