### ISSUE TITLE
new tab always shows about:blank

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8850]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
opening a new tab (via cmd+t) shows 'about:blank' instead of blank in the URL bar. I have the 'always show url bar' preference set.

OS X, 0.15.303
![screen shot 2017-05-12 at 05 36 38](https://cloud.githubusercontent.com/assets/549654/25983587/488d6840-36d5-11e7-9735-ddb9f4e59523.png)

**Comment by bsclifton** [comment]
@diracdeltas is this the same as https://github.com/brave/browser-laptop/issues/8525 and/or https://github.com/brave/browser-laptop/issues/8378?

**Comment by diracdeltas** [comment]
I don't think it's the same as https://github.com/brave/browser-laptop/issues/8525 because it happens when i hit cmd+t regardless of whether i have an about: tab open. It may be the same as https://github.com/brave/browser-laptop/issues/8378 except it happens all the time, not sporadically.

**Comment by alexwykoff** [comment]
Initial launch with a clean profile shows the appropriate message of 'Enter a URL or search term' in the urlbar. Subsequent openings of new tabs are as described above.

This would also explain why it's missing a favicon when I open a lot of tabs. 😸
