### ISSUE TITLE
Links Should Open Focused Tabs

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8851]
## Test plan

https://github.com/brave/browser-laptop/pull/8863#issue-228445027

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Links designed to open in a new tab do so without taking focus.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/04ceba3e7015c46ffd54adabf93e6470951f6fb5

- Steps to reproduce:
1. Go to https://twitter.com/brave/status/794221010484502528
2. Click brave.com/donloads.html link
    
- Actual result:
Tab opens without taking focus.

- Expected result:
New will be given focus.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
The issue can still be reproduced.

![link](https://cloud.githubusercontent.com/assets/3362943/26137937/95418caa-3b00-11e7-84e3-d8630284a1b6.gif)
