### ISSUE TITLE
 Regression - Performance - tab switching is slower in 0.15.3xx

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8853]
STR: 
1. with a clean profile, set number of tabs per pane to 100
2. open 100 tabs ( I set homepage to reddit.com/r/random to give different pages)
3. attempt to switch tabs
4. close and reopen browser, attempt to switch tabs
5. after all tabs have been properly reloaded and rendered, attempt to switch tabs
6. quit and open with a prior build of brave (0.15.2) and compare perfomance

**Comment by luixxiul** [comment]
actually opening 100 tabs at the same time with `ctrl+t` almost freezes the browser ... which is already known I believe. :-p

**Comment by bridiver** [comment]
It should be slightly better now because of the webview event changes, but still a problem
