### ISSUE TITLE
 The Linux/Gtk File Uploader Dialog does not show any image preview on the side.

### ISSUE THREAD

**Issue by 9898287** [brave/browser-laptop#8854]
> Platform and version:

Linux (Gtk) - Xubuntu 16.04
Brave: 0.15.2 
rev: af7ef42ad622f899312a38bdd0e2138154393627 
Muon: 2.58.9 
libchromiumcontent: 58.0.3029.96 
V8: 5.8.283.37 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.0-49-generic 
os.arch: x64

> - Steps to reproduce:
   
    1. Open any image sharing site, upload image/picture
    2. The file chooser dialog pops up; however unlike firefox/chromium, the side preview is not visible
 
Chromium currently uses gtk2, however it has side preview too. 
![problem](https://cloud.githubusercontent.com/assets/25705710/25986286/8e16c39a-3732-11e7-8226-b379cfc0017c.png)

**Comment by bsclifton** [comment]
I believe this would be a change to [Muon](https://github.com/brave/muon).

If electron now supports this functionality, we can look at pulling in patches to resolve this 😄

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by btlechowski** [comment]
Verified on Ubuntu 10.10 x64 
* 0.22.7  8bb7e77f
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1
