### ISSUE TITLE
Refactor window actions, remove the whole frame prop (related to tabs)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8857]
## Test plan

https://github.com/brave/browser-laptop/pull/8858#issue-228241072

----

**Describe the issue you encountered:**
Refactor following window actions, remove the whole frame prop. This will address only actions related to tabs.
- [x] closeFrame
- [x] setTabHoverState
- [x] setTabBreakpoint
- [x] moveTab 
- [x] setPreviewFrame

**Comment by bsclifton** [comment]
Moving to 0.15.3xx; I don't feel confident about reverting in dev-channel
