### ISSUE TITLE
new spec for Laptop Settings panels (being built gradually)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#886]
Hello Community,

We are requesting your feedback on the following design spec that we are starting to build towards for the laptop settings panels. 

This will change as we develop the feature set, but gives you an idea of what Settings will look like, and what features are planned that are user-configurable. 

Thanks again for all of your contributions thus far!

[brave_laptop_settings_spec_022316.pdf](https://github.com/brave/browser-laptop/files/143685/brave_laptop_settings_spec_022316.pdf)

**Comment by PFCKrutonium** [comment]
It reminds me of Firefox's settings panel, I like it. My only thought though is perhaps allow locking the settings panel with a password? If it's there then I missed it, but you get it.

**Comment by SJ-Diamond** [comment]
I like it, please implement it like that, looks cool, especially the implied customization options :)

**Comment by luixxiul** [comment]
How about making ``fa-not`` (Bravery icon) gray like the other fa icons?

**Comment by maverick74** [comment]
What i would REALLY LIKE would be to be able to Customize Brave's UI like i do in Firefox!!!
E.g.: Pick the reload button and move it to the right side of the URL bar. Or do the same thing with the Reload button.

I would also like the bookmarks bar to show Favicons.

Any chance for any of this two requests?! (Customize the UI is a must-have for me!)

**Comment by bradleyrichter** [comment]
closing for being WAY out of date...
