### ISSUE TITLE
Make tab preview based on mouse idle time

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8860]
## Test plan
See https://github.com/brave/browser-laptop/pull/9887

After #12823 please add the NO DELAY (current name) as a check too for undelayed tab previews. Thanks!!

<hr>

## Original issue description
Sometimes tab preview happen unintentionally if you go from urlbar to webview. Tab previews are based on RegExp that checks which element has hovered before current tab preview. 

After taking #3271 this still seems to be the best approach currently but we need to cover other elements that were missing on initial implementation.

**Comment by srirambv** [comment]
Could the preview be only shown after  `x`  seconds of the mouse pointer being held over the tab itself. This way it would solve the unintentional preview while moving the cursor over tabs?

**Comment by cezaraugusto** [comment]
I tried that but doing so undercovered the flickering tab issue we had a while ago. The new method is the same we had but covering more cases. Reviews more than welcome ;)

**Comment by ivanstegic** [comment]
I'm sorry that this is not completely related, but is it possible to switch tab preview off completely? If not, I would like to suggest that as a feature and am happy to create the issue. Any knowledge about this?

**Comment by srirambv** [comment]
>I'm sorry that this is not completely related, but is it possible to switch tab preview off completely? I 

@ivanstegic  there is an option under tabs in settings page to turn off tab preview. Just disable the switch and you won't see tab preivew

**Comment by ivanstegic** [comment]
@srirambv Oh!!!!! Thanks, I really appreciate it. :)

**Comment by cezaraugusto** [comment]
moving to 0.18.x as per last weekly triage meeting. Pls ask before moving out, thanks

**Comment by LaurenWags** [comment]
+1 community (see # 13 in this post: https://community.brave.com/t/issue-small-bugs-found-in-first-couple-hours-of-using-brave/5075)

**Comment by cezaraugusto** [comment]
Heads-up QA I'm re-opening after #12823. This will add a "no delay" (current name). Checked features aren't affected as we're only adding a new option.
