### ISSUE TITLE
Weird flash effect when opening a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8862]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Weird flash effect when opening a new tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.303
rev	04ceba3

- Steps to reproduce:
    1. Clean install 0.15.303
    2. Open new tab using the + button
    3. Tab switches to active tab and shows a blank tab and then loads the dashboard
    
- Actual result:
Weird flash effect when opening a new tab

- Expected result:
Should not have that weird flash effect when opening a new tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![newtabflash](https://cloud.githubusercontent.com/assets/17010094/26009152/718a2e8a-373f-11e7-825f-4a2316edce29.gif)

- Any related issues:
cc: @NejcZdovc @bsclifton

**Comment by NejcZdovc** [comment]
Problem is that flash is from a previous tab. So when you open a new tab, new tab is shown, then old one and new one again. If you open one site and then new tab, you will see that site will be shown again.

**Comment by srirambv** [comment]
The same effect is on when a link opens up due to target=_blank. There is a very fast momentary switch between the two tabs and the focus is retained on the original tab. From a useability perspective this is quite annoying both opening a new tab using keyboard shortcut and opening link in a new tab. Right click open in a new tab has no such effect.

**Comment by NejcZdovc** [comment]
This will be fixed in #8863

**Comment by alexwykoff** [comment]
@srirambv let's test this again after the new builds

**Comment by srirambv** [comment]
Looks good on rev	b872523,  Muon 3.0.103. 

Closing #8862

**Comment by Jacalz** [comment]
I still see it on  fc4b892 using windows x64:
