### ISSUE TITLE
Browser freezes/lags with every page load (+ sometimes randomly), CPU pegged at 100%

### ISSUE THREAD

**Issue by crypdick** [brave/browser-laptop#8867]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Every time I open a new tab or nav to a new page, the browser becomes momentarily unresponsive : no scrolling, typing, or clicking. The freeze typically starts immediately after the page is fully loaded, but it froze ~5 times as I was writing this report (minutes after it had finished loading). Freezing even happens when I open a new tab (to the default dashboard) or when opening the Brave preferences window!

I have a system resource monitor on my panel and every single time this happens I see exactly one of my CPU cores get pegged at 100%. I have plenty of RAM. There are various brave-related processes (`brave`, `brave --type=renderer [...]`) but there doesn't seem to be a single one which gets pegged; they take turns going to 100% when I open a page.

I tried running `brave --v` in terminal and checked `dmesg`, nothing interesting.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux mint 4.4.0-77-generic 64-bit

- Brave Version (revision SHA):
Unsure about the SHA, I just downloaded brave_0.15.2_amd64.deb from the website an hour ago (4/14/17).

- Steps to reproduce:
    1. Load any website or open any tab
    2. wait for it to load
    
- Actual result:
Browser lags for 1-1.5 seconds

- Expected result:
No CPUs pegged, or at least distribute the load across multiple cores so that that the browser does not become unresponsive.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
All shields are up, all "advanced" shields are enabled, ads and 3rd party cookies are blocked.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Every time.

**Comment by andutoo** [comment]
Does the freeze/lag happen when you move around on google maps?

**Comment by crypdick** [comment]
@andutoo Clearing my browser data fixed the problem. Thanks! The browser was unusable before.

**Comment by bsclifton** [comment]
Duplicate history can cause a lot of problems- for example, using Google Maps (notice the URL changes a lot).  We have an issue captured to fix that with https://github.com/brave/browser-laptop/issues/3848
