### ISSUE TITLE
Pinned tab shows blank white page when relaunching the browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8873]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pinned tab shows blank white page when relaunching the browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.303
rev	04ceba3

- Steps to reproduce:
    1. Have a site pinned 
    2. Set focus to the pinned tab and close the browser
    3. Relaunch the browser, pinned tab doesn't show the site but its blank page, 
    4. Switch focus to other tab and go back to pinned tab, page is loaded properly
    
- Actual result:
Pinned tab shows blank white page when relaunching the browser

- Expected result:
Should load the page properly after relaunch

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Setting milestone 0.15.400. Please push it back to 0.15.300 if required 
cc: @bsclifton

**Comment by bsclifton** [comment]
I've retested and this appears to be fixed.  May have been fixed with https://github.com/brave/browser-laptop/pull/8863
