### ISSUE TITLE
APP_TAB_CLOSE_REQUESTED needs tests

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8875]
See here:
https://github.com/brave/browser-laptop/pull/8782#issuecomment-301549373

We had test coverage for the reducer there before, but we don't anymore with the new action.  Please ensure all new reducer actions that are handled have tests.

**Comment by bridiver** [comment]
actually it was mostly just a name change. I must have deleted the tests by accident when I was cleaning up instances of `APP_ACTIVE_WEB_CONTENTS_CLOSED`

**Comment by bbondy** [comment]
Could you re-add? thanks.

**Comment by bbondy** [comment]
n/m I got it
