### ISSUE TITLE
macOS copy issue is back

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#8876]
The macOS copy issue is back and we aren't sure why. 
Both Clifton and I seen it independently.

I'm going to try reverting this old fix to see if it helps with the next packaged build:
https://github.com/brave/browser-laptop/commit/6485cc59f027a9809c88d597f0b506e15fdbdcc7

Test Plan:

It's really hard to reproduce, but just be on the lookout on macOS for copy problems with keyboard shortcuts. It works via menu before and after this fix, but this is attempting to fix a command+C issue where text is inside a webview.

**Comment by bbondy** [comment]
cc @diracdeltas  FYI, please be on the lookout on the next preview. If you still see it, then we will revert the fix I do here, and then we'll have to search more for a different fix and re-open this.

**Comment by alexwykoff** [comment]
@srirambv i have those 4 labels added because that is how our current test run generator works. until we have time to modify it, this is the proper practice 😄

**Comment by srirambv** [comment]
Sorry my bad. Since it was OS specific just added as QA Checked.
