### ISSUE TITLE
Window is closed after a tear off

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8878]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
If you tear off a tab from a window that have only two tabs, window is closed.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
26afbd5
- Steps to reproduce:
    1. open two tabs
    2. tear off one tab into new window
    
- Actual result:
window 1 is closed

- Expected result:
window 1 should remain
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes
- Screenshot if needed:
![13 2 1](https://cloud.githubusercontent.com/assets/9574457/26082187/ee590418-39ce-11e7-806d-ae0472973a45.gif)

**Comment by alexwykoff** [comment]
Fixed by 8863
