### ISSUE TITLE
close tab icon only shows for the last tab

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#8883]
Opening more than one tab only shows close tab icon for the last tab. Commit issue was found going back in git history and resetting merge commit 1d5ba3f1b29d3cd45c344444d81e0876055a9fc9, (PR #8863).

- Platform (Win7, 8, 10? macOS? Linux distro?):
any

- Brave Version (revision SHA): 
3e3464e  

- Steps to reproduce:
    1. Open two tabs
    2. Make second active
    3. Hover over the first
    
- Actual result: 
no close tab icon

- Expected result: 
close tab icon should show for each tab preview at that tab size

- Screenshot if needed:
mouse wasn't recorded but preview indicates that it is over the first tab
![closetab_icon](https://cloud.githubusercontent.com/assets/4672033/26096950/4a5ef2fc-39f9-11e7-9c24-bce6b469fbc7.gif)

cc @bridiver

**Comment by bridiver** [comment]
looks like another rebase/merge conflict issue, pushing a fix now
