### ISSUE TITLE
Kabob zoom buttons only work once

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8885]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Kabob zoom buttons only work once

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.303
rev	04ceba3

- Steps to reproduce:
    1. Clean install/upgrade to 0.15.303
    2. Click on the kabob menu and click on the Zoom +/- button
    3. Only works once, either increase of decrese
    
- Actual result:
Kabob zoom buttons only work once

- Expected result:
Should work properly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![kabobzoom](https://cloud.githubusercontent.com/assets/17010094/26106927/8cc16328-3a3f-11e7-81fa-2b5b2691f808.gif)

- Any related issues:

**Comment by bsclifton** [comment]
@NejcZdovc can you check this issue out? 😄

**Comment by NejcZdovc** [comment]
@bsclifton I can't reproduce this on the latest master and dev-channel and I can't reproduce.

![image](https://cloud.githubusercontent.com/assets/9574457/26149005/dbd5e1aa-3af8-11e7-82bf-a2b694227c6a.png)

**Comment by NejcZdovc** [comment]
@srirambv can you try it on 0.15.304?

**Comment by srirambv** [comment]
Looks like fixed on 0.15.304. Closing #8885

**Comment by alexwykoff** [comment]
oh wow, this seems to have also fixed the key-repeat hitching for zoom as well!
