### ISSUE TITLE
Reopening a previously closed tab lacks history.

### ISSUE THREAD

**Issue by Codes4Fun** [brave/browser-laptop#889]
I saw in another issue history options are being worked on but I don't know if this is included in that.

Anyway, reopening a previously closed tab doesn't restore the history of that tab. I usually open links in new tabs to preserve the previous page, but occasionally I forget or choose not to do that and close the new tab thinking I have the previous page in its own tab and end up having to reopen the previous tab to go back to the previous page. Of course this happened in Brave and I found out Brave does not restore the history so I end up losing that previous page.

**Comment by luixxiul** [comment]
Ref: #444

**Comment by cezaraugusto** [comment]
Since it's related to history management, going to close in favor of #444.
