### ISSUE TITLE
Sites needs to be added to the allow autoplay defaults

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8890]

**Comment by darkdh** [comment]
I wanna make this ticket more general and add more sites to it.
Netflix is one of them

**Comment by darkdh** [comment]
and www.amazon.com, vimeo.com?

**Comment by Jacalz** [comment]
I would suggest adding svtplay.se also to the defaults 😉

**Comment by Jacalz** [comment]
And also tv4play.se

**Comment by srirambv** [comment]
@darkdh  can we make it as an input field where user can add which ever sites they frequently use to add it to autoplay list apart from the ones we allow by default

**Comment by darkdh** [comment]
@sriambv, I think notification bar covers it. Users can allow and remember the decision. I believe this is easier for users.

**Comment by darkdh** [comment]
calendar.google.com +1
CC @lukemulks

**Comment by lukemulks** [comment]
+1 calendar.google.com

**Comment by luixxiul** [comment]
my opinion on adding exceptions: https://github.com/brave/browser-laptop/pull/8922#issuecomment-302611646

**Comment by alexwykoff** [comment]
https://github.com/brave/muon/pull/264 has been merged, we should revisit this after some testing @luixxiul @darkdh 😸

**Comment by darkdh** [comment]
we can reference safari's whitelist
![screen shot 2017-11-30 at 3 38 49 pm](https://user-images.githubusercontent.com/11330831/33465161-11154688-d5fb-11e7-852a-39a29eff363a.png)
as you can see vimeo and youtube are allow even if global setting set to block
but you can overwrite it like this
![screen shot 2017-11-30 at 3 49 29 pm](https://user-images.githubusercontent.com/11330831/33465150-017f46ce-d5fb-11e7-8a82-9d1fa5877614.png)
