### ISSUE TITLE
importing bookmarks after sync causes loss of hierarchy

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8892]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I installed 0.15.304 on two different OS X laptops

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.15.304 (b872523)

- Steps to reproduce:
    1. with a clean profile for each, enable a new sync group on one device
    2. join the sync group with the other device
    3. import bookmarks on the primary device
    
- Actual result:
the folder hierarchy is lost versus if an import occurs without sync.

- Expected result:
the folder hierarchy should be maintained and the name should match the pattern 'imported from <browser name>'

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
likely

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="1918" alt="screen shot 2017-05-16 at 3 15 39 pm" src="https://cloud.githubusercontent.com/assets/1434040/26126265/928aa7e6-3a4a-11e7-9cd3-83b538eb3aaa.png">

- Any related issues:

**Comment by benmordecai** [comment]
I have experienced this same problem in Windows 10 x64, 0.15.314

**Comment by alexwykoff** [comment]
Confimed this is still an issue with 0.16.3: 
laptop - laptop
laptop - iOS sync beta
laptop - android sync beta

**Comment by alexwykoff** [comment]
This is a pretty serious blocker for mobile implementations of sync as they don't have easy ways to organize mass amounts of bookmarks.

**Comment by bsclifton** [comment]
@diracdeltas do you think this can be solved for the 0.17.x release?

**Comment by diracdeltas** [comment]
@bsclifton probably

**Comment by benmordecai** [comment]
There is also a coincident bug where you cannot reliably drag and drop bookmarks in the manager so if sync fails you have to manually move bookmarks from the bookmark toolbar. This makes a sync failure basically unworkable on desktop/laptop also.

**Comment by diracdeltas** [comment]
the issue is that under certain timing conditions, an objectId can be set twice for a bookmarks folder, once in `findOrCreateFolderObjectId` when one of its children is being sent and once in `createSiteData` when it itself is being sent. the child ends up having an obsolete `parentFolderObjectId` so it shows up at the top level.
