### ISSUE TITLE
copying URLbar text opens the autosuggest dialog

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8896]
cmd+c in the url bar on mac opens the autosuggest dialog.

STR:
1. click on urlbar and highlight the text
2. hit cmd+c to copy
3. observe the autosuggest dialog pops up

The same issue exists with cmd+x, which was fixed previously: https://github.com/brave/browser-laptop/commit/394d1e315e716fb7a03d843c0ddc91df15115147

**Comment by bsclifton** [comment]
Marked as `release-notes/exclude` since it was introduced with this version too
