### ISSUE TITLE
about:safebrowsing shows shows a blank page

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8905]
**Describe the issue you encountered:** about:safebrowsing shows shows a blank page

- Platform (Win7, 8, 10? macOS? Linux distro?): debian

- Brave Version (revision SHA): 0.15.304

- Steps to reproduce:
    1. Open downloadme.org
    2. blank
    3. Set focus to the URL bar (`about:safebrowsing#http://downloadme.org`)
    4. Hit Enter key
    5. loading is blocked
    
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26150995/e8f8c044-3b3b-11e7-97f3-f322267a52f6.jpg)
  ````
  l20n.min.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
  aboutPages.entry.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
  ````

- Any related issues:

**Comment by diracdeltas** [comment]
on mac i see `l120n.min.js` blocked; the safebrowsing page shows up but not the text. it works if i reload the safebrowsing page.

**Comment by diracdeltas** [comment]
^ that was on latest master. on 15.304 i get the same thing as @luixxiul

**Comment by alexwykoff** [comment]
This appears to have regressed in 308

STR:
1. With a clean profile go to http://alexwykoff.com/tests/testlinks.html
2. Use cmd + click to open the http://downloadme.org/ link in another tab

Expected result : about:safebrowsing is displayed appropriately

Actual result : a blank page is displayed

**Comment by srirambv** [comment]
Works fine on Windows on a clean profile when opening with Ctrl+Click from http://alexwykoff.com/tests/testlinks.html

**Comment by diracdeltas** [comment]
@alexwykoff i think it's actually a separate issue, not a regression. the original issue was for links entered directly, not via cmd-click

**Comment by alexwykoff** [comment]
Since other cmd-click pages are working, is it reasonable to believe it is related?

Clicks and cmd-clicks should be part of the test for this issue as well as simply entering download.me into the urlbar.

**Comment by alexwykoff** [comment]
![safebrowsing_click](https://cloud.githubusercontent.com/assets/1434040/26468884/a61465ee-415d-11e7-925a-8ceaa1705c72.gif)

**Comment by diracdeltas** [comment]
i agree the functionality should be tested; however @luixxiul's original issue showed that about:safebrowsing loaded but without text (due to the l10n library being blocked). the cmd+click issue shows nothing loaded at all

**Comment by alexwykoff** [comment]
k https://github.com/brave/browser-laptop/issues/9056
