### ISSUE TITLE
Extra padding for Widevine info text

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8907]
- Brave Version (revision SHA):
Brave	0.15.304
rev	b872523
Muon	3.0.103 

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/26152247/0edcaaca-3afe-11e7-975e-c76d2fd301fa.png)

**Comment by luixxiul** [comment]
That's the regression I introduced when I refactored widevineInfo.js with commonForm. Will fix soon.
