### ISSUE TITLE
With pinned tabs, creating enough tabs causes tabs set shift

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8909]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
With pinned tabs, creating enough tabs causes tabs set shift

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.304
rev	b872523
Muon	3.0.103

- Steps to reproduce:
    1. Have 5-6 pinned tabs
    2. Set tabset to have 20 tabs (default value)
    3. Create around  12 tabs including the pinned ones
    4. Click on new tab, creates a new tab. all tabs are hidden and the arrow indicator is shown like when its shown for tabsets
    
- Actual result:
With pinned tabs, creating enough tabs causes tabs set shift

- Expected result:
Should not change focus to new tabset 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Not checked 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![newtab](https://cloud.githubusercontent.com/assets/17010094/26158149/e06df224-3b12-11e7-90f2-87e168be72c3.gif)

- Any related issues:

**Comment by srirambv** [comment]
cc: @NejcZdovc @bsclifton

**Comment by NejcZdovc** [comment]
@srirambv can you reproduce this problem in 0.15.2?

**Comment by srirambv** [comment]
@NejcZdovc No not reproducible on 0.15.2
