### ISSUE TITLE
URL bar auto-suggestion improvment

### ISSUE THREAD

**Issue by seeam** [brave/browser-laptop#891]
On Firefox or Chrome, we can navigate throw suggestion with arrow key. They not only highlights the suggestion but also put the suggestion or url on the urlbar. If we press enter button, it takes to the highlighted link.
But Brave only highlights the suggestion. If we press enter after highlighting any url it doesn't do anything. (see the attachment)
In this state this suppose to take us into http://uol.com.br/ after pressing enter but it just closes the suggestion menu.
![screenshot_12](https://cloud.githubusercontent.com/assets/7550283/13276746/a0c866ea-daec-11e5-9c7d-bb9dc863dd88.png)

By the way, I'm using 0.7.15 and Windows 8.1

**Comment by bbondy** [comment]
For the Enter on active URL this is already fixed, leaving open for the other feedback though.

**Comment by bradleyrichter** [comment]
@bbondy I agree 100% with @seeam. User expectation is to see URL dynamically completed based on list choice.

Let's add this as we fill in other functionality in the URL bar.

**Comment by diracdeltas** [comment]
URL autocomplete is issue #241.

**Comment by seeam** [comment]
It worked on 0.7.16 build.
