### ISSUE TITLE
Bookmarking page without title

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#8912]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you bookmark page that don't have a title, bookmark name is empty
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
ced8add
- Steps to reproduce:
    1. go to page without title (test/fixtures/page_no_title.html)
    2. click on star icon (bookmark)
    
- Actual result:
Bookmark name is empty
- Expected result:
Bookmark name should be url without http/s. If tab is a local file we should display file name.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

#2972

**Comment by NejcZdovc** [comment]
@kumarrishav I am already working on this one, sorry :smiley:

**Comment by luixxiul** [comment]
Something might have regressed after https://github.com/brave/browser-laptop/issues/3442 was fixed.

**Comment by kumarrishav** [comment]
@NejcZdovc sure. Actually, i assigned myself to track this issue. There are so many issues that selected issues get lost generally. Assigning is a good way to track though 
Thanks

**Comment by bsclifton** [comment]
@kumarrishav you might consider the notifications (whether you use them in GitHub or via email).  I find those super useful to track issues.  I'm subscripted to the whole repo though and I have various email filters

**Comment by NejcZdovc** [comment]
I notice that this is related to this bug #8908, so will be closing this one for now.
