### ISSUE TITLE
build hangs in tmux on macOS

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#8916]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:

when running `npm install`, the build eventually hangs after webpack. if I take a look at what processes are running there are three instances of `terminal-notifier`; killing these processes allows the build to continue. seems to only happen in tmux so it is likely this issue:
https://github.com/julienXX/terminal-notifier/issues/115

unfortunately the work-around listed there isn't working for me, but honestly I would rather not have to maintain a single platform hack in my dotfiles anyway. I don't even want the notifications in the first place.

it doesn't seem like `webpack-notifier` or `terminal-notifier` have an option to disable sending notifications, so maybe an option to disable `webpack-notifier` via an env var can be added to the Brave build?

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Is this an issue in the currently released version?
no, not a browser issue

Where in the build it hangs:
```
Child webtorrent:
    Hash: 7c0dbdb8553ed2f47308
    Version: webpack 1.15.0
    Time: 25028ms
                                     Asset       Size  Chunks             Chunk Names
      2ad15189f9772058209b9036ebf8bda1.svg    1.34 kB          [emitted]
      8b116e3ce0b2711f8e2cc78c8b32a7c5.svg  485 bytes          [emitted]
      674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
    af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
     fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
      b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
      912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]
                   webtorrentPage.entry.js    1.39 MB       0  [emitted]  main
               webtorrentPage.entry.js.map     1.7 MB       0  [emitted]  main
       [0] multi main 28 bytes {0} [built]
        + 313 hidden modules
<hangs>
```

**Comment by diracdeltas** [comment]
++ i have this too
