### ISSUE TITLE
Bookmarks menu enhancement : allow for independent scrolling of columns

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#8918]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
user2 from community writes 

> It would be great if the right column that shows the bookmarks was independently scrollable from the left column that ha the bookmark hierarchy organization. As is, when there is a lot of content in the left column and the user scrolls to the bottom of the left column then the content in the right column also scrolls. This is a problem because the content in the right column is no longer visible because the user has scrolled to the bottom of the left column.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.15.3

- Steps to reproduce:
    1. Have bookmark folders with a deep amount of links and subfolders.
    2. Attempt to scroll down either independently as you traverse the structure.

    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
@alexwykoff isn't this dup of #5076 which was done in 0.15.300?

**Comment by bsclifton** [comment]
@NejcZdovc yup- this has to be a dupe.  Closing 😄
