### ISSUE TITLE
Preference to disable menu

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8924]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Suggested in https://github.com/brave/browser-laptop/issues/5540, it would be nice to have an option to completely disable the menu that shows up.  This is something which would affect users on Windows and Linux users without a system menu (ex: you're using Gnome and not Unity)

This could get tricky as we'd need a way (on Linux) to detect if the user has a system menu showing or not.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows / Linux

- Brave Version (revision SHA):
All

- Steps to reproduce:
    1. Press ALT
    2. Notice menu shows or hides (it toggles)
    
- Actual result:
There is an option to hide the menu by default... but not one to disable menus

- Expected result:
There should be a way to disable the menu

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by EPadronU** [comment]
With this I could avoid a bug I'm getting with 15.301dev and above. The menu is hidden but an empty space remains after that. Staying in 15.02dev for now :c

**Comment by bsclifton** [comment]
@EPadronU if you try out the newly released 15.305 dev, I fixed that 😄  we're getting close, thanks for hanging in there

**Comment by EPadronU** [comment]
@bsclifton That's awesome news! Thanks :)

**Comment by bsclifton** [comment]
Closing as `wontfix` for browser-laptop since [Brave Core](https://github.com/brave/brave-browser) does not have a menu built into the window for Windows / Linux (Linux may show a system menu, like macOS, based on the window manager)
