### ISSUE TITLE
"open in new window" should cascade instead of layering at same x/y

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8925]
## Test plan
1. Open Brave
2. Use the menu and pick `File` > `New Window`
3. A new window should appear and be offset (see example pics below). Offset should be ~20px

## Original issue description
Cascade amount should be (x20px, y20px).

firefox example:

![image](https://cloud.githubusercontent.com/assets/13509546/26181922/d151802e-3b28-11e7-9d69-32b15b880150.png)

chrome example:
![image](https://cloud.githubusercontent.com/assets/13509546/26181938/e655525c-3b28-11e7-807d-c833c6eff6e3.png)

**Comment by alexwykoff** [comment]
similarly if you close and reopen brave, it would be wise to make sure we cascade.

**Comment by NejcZdovc** [comment]
Current findings:
We need to add some logic here https://github.com/brave/browser-laptop/blob/master/js/stores/appStore.js#L149

We need to check if user don't pass in any params about width/heigh we should cascade it.

Note that we also need to to change position when new position of cascaded is out of scope. We would like to do the same behavior as mac OS has. Move a finder window near to the window edge and create a new window. You will see that window is moved to another side where you have enough space. Same goes if you move it to the bottom it will be moved to the top if new window would be out site the scope.

**Comment by bradleyrichter** [comment]
I thought I was witness to seeing the correct behavior in @NejcZdovc code. So it must be a new bug.

**Comment by LaurenWags** [comment]
Thanks @bradleyrichter - opened new issue for https://github.com/brave/browser-laptop/issues/8925#issuecomment-352093685 which is https://github.com/brave/browser-laptop/issues/12315
