### ISSUE TITLE
Opening bookmark suggestion with Return/Enter

### ISSUE THREAD

**Issue by butlermatt** [brave/browser-laptop#893]
I have pages bookmarked. When I start typing in the address bar, the bookmark will appear as a suggestion.

If I use the down arrow it will highlight the bookmark (give it blue text instead of gray/black).

If I hit enter once it's highlighted... nothing happens.
Expected behaviour would be to open the bookmark.

If I click on the highlighted bookmark instead, it opens as expected.

MacOS X 10.11.3
Brave: 0.7.15

**Comment by garvankeeley** [comment]
Appears fixed in 0.7.16, yay, this was quite annoying
