### ISSUE TITLE
about:brave shows win32 for all Windows platforms (even x64)

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#8933]
If you look at about:brave on 64 bit Windows, you'll notice it reports `win32` as the platform.  [This value is coming from node.js](https://nodejs.org/api/os.html#os_os_platform)
![screen shot 2017-05-18 at 9 31 28 am](https://cloud.githubusercontent.com/assets/4733304/26213152/d0e3e922-3bac-11e7-8be7-bdd216273bba.png)

This is confusing because it looks like something is 32 bit, even though we are clearly running the 64 bit version of the software and Windows is 64 bit.

The solution would be to do a string replacement. When `win32` is returned, we can substitute in a string like "Microsoft Windows".  We could put this logic into the [platformUtil module](https://github.com/brave/browser-laptop/blob/7452b7ec81f8b501a0b747829fa81090a67becee/app/common/lib/platformUtil.js) and update the part of the code which currently updates the values on about:brave:
https://github.com/brave/browser-laptop/blob/7452b7ec81f8b501a0b747829fa81090a67becee/app/sessionStore.js#L417

**Comment by bbondy** [comment]
Confusingly enough most people still refer even to the 64-bit Windows API as Win32 API. Microsoft started calling it Windows API (WinAPI) though but most people still call it win32 independent of arch.  That being said friendlier names sound good.
