### ISSUE TITLE
wrong alert bar used for app-level alerts:

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#8934]
![image](https://cloud.githubusercontent.com/assets/13509546/26216318/7b482daa-3bb8-11e7-8650-e33a77a3dc4f.png)
The original alert bar should be used. (the one which is located above the tabs bar, and does not include the orange bottom border.

**Comment by luixxiul** [comment]
adding the milestone just in case.

**Comment by diracdeltas** [comment]
This isn't a problem for all app alerts - for instance the update alert bar appears in the right place. 

https://github.com/brave/browser-laptop/issues/11256 is probably a duplicate of this

**Comment by bsclifton** [comment]
Closing this issue as a duplicate of https://github.com/brave/browser-laptop/issues/11256 (the issue you created @diracdeltas has much better info / requirements 😄 )
