### ISSUE TITLE
Clicking on maximize button has a weird flash effect

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8937]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicking on maximize button has a weird flash effect

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.305
rev	2186b3f
Muon	3.0.104

- Steps to reproduce:
    1. Clean install .305 
    2. Click on maximize button, doesn't flash just maximzes
    3. Click on restore button, doesn't flash just restores
    4. Click on maximize button again, window flashes and then maximizes
    5. Click on restore button again, window flashes but not as much when clicked on the maximized button
    
- Actual result:
Clicking on maximize button has a weird flash effect

- Expected result:
Should not flash window when maximized or restored down.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![maximize](https://cloud.githubusercontent.com/assets/17010094/26220551/fafa7d9e-3c0a-11e7-9022-42ffef31e7ec.gif)

- Any related issues:
cc: @bsclifton

**Comment by bsclifton** [comment]
repro'd

**Comment by bsclifton** [comment]
It definitely happens to me on 0.15.2 too.  I went as far back as 0.12.13 and saw this happening

Removing milestone
