### ISSUE TITLE
Bookmarks manager: no scrollbar, can no longer drag-and-drop into folders

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#8946]
## Test plan

https://github.com/brave/browser-laptop/pull/9199#issue-232986488

## Original issue description
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
I can no longer drag and drop saved bookmarks into folders, and the bookmarks manager window does not have a scrollbar--some bookmarks are invisible off the bottom of the screen.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Slackware 14-current
- Brave Version (revision SHA):
0.15.305 2186b3f
- Steps to reproduce:
    1. Bookmarks -> Bookmarks
    2. Tap saved bookmark and drag into folder
    3. Nothing happens
    
- Actual result:
All saved bookmarks remain on bookmarks toolbar, which does not scroll
- Expected result:
Like until recently, bookmarks are moved into folders
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

** Worked fine until one of the recent releases in the last week or so.
![nobookmarkscroll](https://cloud.githubusercontent.com/assets/5156230/26234658/3a2aef7a-3c34-11e7-892a-35b472c24785.png)

**Comment by bsclifton** [comment]
cc: @cezaraugusto
