### ISSUE TITLE
Empty list appears by clicking adsBlockedStat when the stat is 0

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8950]
**Describe the issue you encountered:** Empty list appears by clicking adsBlockedStat when the stat is 0.

![count](https://cloud.githubusercontent.com/assets/3362943/26239970/4b7f069a-3cba-11e7-9d28-f9bf8fa90c71.gif)

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment]
Dupe of https://github.com/brave/browser-laptop/issues/7026
