### ISSUE TITLE
Add compact bravery panel with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8954]
**Describe the issue you encountered:** Add compact bravery panel with Aphrodite. The panel should be  l10n-friendly as well.

<img width="305" alt="screenshot 2017-05-19 17 55 13" src="https://cloud.githubusercontent.com/assets/3362943/26240546/57d60fea-3cbc-11e7-9c8c-a93d000270e2.png">

<img width="420" alt="screenshot 2017-05-19 17 55 47" src="https://cloud.githubusercontent.com/assets/3362943/26240564/69a94840-3cbc-11e7-91a1-a35dba07232c.png">

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
What happens when domain is really long?

**Comment by luixxiul** [comment]
![long](https://cloud.githubusercontent.com/assets/3362943/26241987/bc58e06e-3cc1-11e7-8517-a155609684e4.gif)

**Comment by NejcZdovc** [comment]
I like it :+1:

**Comment by bsclifton** [comment]
I'm running the latest preview and it's not going compact for me (even when I resize the window to be small)

Is there anything special that needs to be done?

**Comment by bsclifton** [comment]
A: after reading the test plan, yes- gotta enable the option 😛

**Comment by luixxiul** [comment]
yes, it's disabled by default.
