### ISSUE TITLE
Clicking on web notification doesn't switch to the tab/window 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8955]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicking on web notification doesn't switch to the tab/window 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.305
rev	2186b3f
Muon	3.0.104

- Steps to reproduce:
    1. Enable web notification on any site
    2. Set focus to a different application and brave is backgrounded
    3. When clicked on notification focus isn't set to brave, still on different application
    4. Set focus to brave and switch to a different tab
    5. Click on web notification, focus doesn't change to the source tab 
    
- Actual result:
Clicking on web notification doesn't switch to the tab/window 

- Expected result:
Clicking on notification should change the focus to brave if the focus is on a different application and if brave is active window then focus should be on the source tab which triggered the web notification

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked but guessing same behavior in previous releases as well

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @bbondy @bsclifton

**Comment by bsclifton** [comment]
This should be fixed now- I've tried this recently and it's worked as expected
