### ISSUE TITLE
Impossible to add bookmark with empty name

### ISSUE THREAD

**Issue by frenchbread** [brave/browser-laptop#8957]
### Feature request

> It's impossible to add a bookmark without name, so that only bookmark icon is visible in the bookmarks bar, like in Google Crome.

Would like to see that feature in Brave for laptop (macOS) browser.

**Comment by bradleyrichter** [comment]
@frenchbread for now, you can add a space to act as the empty name...

**Comment by sjlehn** [comment]
Possible duplicate of #2972

**Comment by Liunkae** [comment]
Thanks @sjlehn! Closing as duplicate of #2972.

**Comment by frenchbread** [comment]
Thanks
