### ISSUE TITLE
Anonymous Payment Options

### ISSUE THREAD

**Issue by indolering** [brave/browser-laptop#8973]
I prefer my cryptocurrency payments to be like my browsing habits: anonymous.  Bitcoin network analysis makes payment tracking trivial, I would prefer to use ZCash.

**Comment by bsclifton** [comment]
@indolering for now, we're live with Bitcoin and we'll be taking steps to implement the Basic Attention Token (see https://basicattentiontoken.org/ for more info)

I'm going to close this, but thanks for the suggestion
cc: @mrose17
