### ISSUE TITLE
"WebGL is not supported" on browserleaks.com

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8975]
**Describe the issue you encountered:** "WebGL is not supported" message appears on https://browserleaks.com/webgl

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Debian

- Brave Version (revision SHA): 0.15.306

- Steps to reproduce:
    1. Clear the browser's profile
    1. Visit https://browserleaks.com/webgl and turn on fingerprinting protection

- Actual result: 
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26275551/a16f3342-3d9e-11e7-8c91-963ea977392a.jpg)

- Expected result: it should be supported

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #8448

**Comment by diracdeltas** [comment]
Cannot repro in OS X with fingerprinting protection enabled. It says webgl is supported like before.

I'm not sure if this is needed for 0.15.300. It is partly true that webgl is 'disabled in browser settings' when fp is enabled, so the site seems accurate.

**Comment by luixxiul** [comment]
> webgl is 'disabled in browser settings' when fp is enabled

Sorry I forgot to mention that Fingerprinting Protection was not enabled.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26280616/74d8d950-3e16-11e7-9498-4db9aaafa3f0.jpg)

**Comment by diracdeltas** [comment]
does webgl work though? ex: if you go to http://alteredqualia.com/three/examples/webgl_pasta.html, does it show falling pasta?

**Comment by luixxiul** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26285411/46c314e4-3e8a-11e7-9114-1627291afe48.jpg)

Tested with 0.15.2 on Debian, it's the same result.
