### ISSUE TITLE
Loading about:safebrowsing after blocking phishing site displays the original URL of the tab for an instant

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8978]
**Describe the issue you encountered:** Loading about:safebrowsing after blocking a phishing site displays the original URL of the tab for an instant.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26275959/c22ae51e-3da7-11e7-8ffb-b9c32eaab572.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Debian

- Brave Version (revision SHA): 0.15.306

- Steps to reproduce:
    1. Load downloadme.org on a GitHub page
    
- Actual result: The GitHub page's URL is displayed for an instant

- Expected result: It should not be displayed.

- Is this an issue in the currently released version?
  No.
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26275974/302ad100-3da8-11e7-94f4-6687cee60751.gif)

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by diracdeltas** [comment]
i think this is not a blocker but will look at it

**Comment by diracdeltas** [comment]
this is tricky to fix. i think it is best to just wait until the workaround in ea4f72a1edbfb35512d8338ba689ad97933065ed is no longer needed, then this issue will automatically go away.

**Comment by luixxiul** [comment]
This can no longer be reproduced :-)
