### ISSUE TITLE
add favicon to "about:page" pages so small tabs or pinned tabs are not blank

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#898]
![image](https://cloud.githubusercontent.com/assets/13509546/13300862/eeafc9de-daf6-11e5-84da-64ba208566ad.png)

**Comment by bbondy** [comment]
please attach favicon

**Comment by bbondy** [comment]
or just the brave logo?

**Comment by bbondy** [comment]
Added the same favicon that brave.com uses to preferences, bookmarks, about:about. 
about:blank needs to remain blank
about:newtab looks a bit strange with a brave icon.

<img width="206" alt="screenshot 2016-02-24 22 34 26" src="https://cloud.githubusercontent.com/assets/831718/13309018/d6106abe-db46-11e5-9990-fb5c5885e905.png">

**Comment by bradleyrichter** [comment]
I'll make something different for this. Potentially unique favs for each about:page in the future.

**Comment by bbondy** [comment]
np will just be a simple drop in, attach if you want updates, or do later.

**Comment by luixxiul** [comment]
Was this already merged? It looks the same on Windows 10.

![](http://i.imgur.com/rRZPe8w.jpg)

Or is it being worked on?

**Comment by bbondy** [comment]
Nice fine, I posted this issue to track: #1656
