### ISSUE TITLE
[Question] brave and the tor broject

### ISSUE THREAD

**Issue by SSoulaimane** [brave/browser-laptop#8983]
The tor project has historically [struggled with chromium to make a tor mode for it, a quote from a blog post](https://blog.torproject.org/blog/google-chrome-incognito-mode-tor-and-fingerprinting):
>Google Chrome is a very fine-tuned high performance browser, and keeping it this way is priority #1 for Google. At the present time, all of the extension APIs are asynchronous, and delivery is optimized so that increasing the number of installed extensions listening for events has negligible to absolutely zero effect on page load time.

>However, security and privacy enhancing extensions will need the ability to actually block and modify requests with certainty. This means that fully asynchronous notification and response is not a viable option for some events.

[they eventually gave up on chromium](https://www.torproject.org/docs/faq.html.en#TBBOtherBrowser)
>Our efforts to work with the Chrome team to add missing APIs were unsuccessful, unfortunately. Currently, it is impossible to use other browsers and get the same level of protections as when using Tor Browser. 

How does your browser play with the tor project? is a tor mode doable? is there enough control available to do that?

https://github.com/brave/browser-laptop/issues/1185

**Comment by diracdeltas** [comment]
see https://github.com/brave/browser-laptop/wiki/Brave-Tor-Support

we do not yet include Tor

in theory we can prevent the proxy leaks that caused TBB to give up on Chromium but it is a lot of work

**Comment by diracdeltas** [comment]
Closing this in favor of #1185 and other specific issues related to Tor implementation, now that we have a roadmap for Tor private tabs
