### ISSUE TITLE
Password manager fails to recall stored password for https://payment.schibsted.no

### ISSUE THREAD

**Issue by toreanderson** [brave/browser-laptop#8987]
- Did you search for similar issues before submitting this one?

Yes.

- Describe the issue you encountered:

The browser fails to recall the stored password for https://payment.schibsted.no, instead offering to save it again - resulting in duplicate entries in the list of stored passwords.

- Platform (Win7, 8, 10? macOS? Linux distro?):

Fedora 25 x86_64.

- Brave Version (revision SHA):

af7ef42

- Steps to reproduce:
    1. Go to https://payment.schibsted.no
    2. Log in (or attempt to do so with bogus credentials, Brave will offer to save password in any case)
    3. Accept having Brave save the credentials
    4. If logged in, log back out
    5. Again go to https://payment.schibsted.no
    6. Observe how the username and password input fields do not get filled in
    7. Log in again (or attempt to do so with bogus credentials)
    8. Accept having brave save the credentials again
    9. Head to `about:passwords`
    10. Observe how there are now two duplicate entries for https://payment.schibsted.no in the list
    
- Actual result:

Should be obvious from the _Steps to reproduce_ list above.

- Expected result:

At step 5/6 in the list above, the stored password should have been recalled from the credentials storage. It should not offer to store it again.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes, it reproduces in a fresh profile.

https://payment.schibsted.no redirects the browser to a session-specific URL which is different on each login attempt, e.g. https://payment.schibsted.no/flow/login/5291648e32282. If Brave stores and looks up the credentials using the entire URL rather than just the domain name, that would explain the issue. However, in `about:passwords` only the domain name is shown.

Firefox and Chrome has no problems storing and recalling the password on this site.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

- Screenshot if needed:

This shows the duplicated entries in the `about:passwords`:

![screenshot from 2017-05-21 12-18-04](https://cloud.githubusercontent.com/assets/4557060/26283038/c4576538-3e1f-11e7-86c2-5d2d2645ab68.png)

- Any related issues:

There are several other _does not store/recall passwords on site X_ issues for various values of _X_, but I have no idea whether or not they share the root cause with this one.

**Comment by bsclifton** [comment]
cc: @darkdh
