### ISSUE TITLE
clicking "back to safety" from the cert warning page always goes to about:blank

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#899]
Steps to reproduce:
1. go to badssl.com
2. click on "expired"
3. click "back to safety"
Expected:
Return to badssl.com home page
Actual:
about:blank

**Comment by diracdeltas** [comment]
@bridiver are you working on enabling back/forward state navigation to/from about: pages from/to regular pages? This is easily fixed if/when that is landed.

In the meantime, I could store the last non-error'ed page in window `securityState` and load it when `Back to Safety` is clicked.

**Comment by bridiver** [comment]
I'm working on extensions right now
