### ISSUE TITLE
When launching while offline, pinned tabs cause empty `about:error` page to be loaded

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8996]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tabs duplicate when browser is launched offline

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.306
rev	0067c4f
Muon	3.0.200

- Steps to reproduce:
    1. Clean install 0.15.306
    2. Set tab count to 100 
    3. Pin few tabs and have normal tabs and session tabs opened
    4. Disconnect internet and close and restart the browser, normal tabs and session tabs gets duplicated
    
- Actual result:
Tabs duplicate when browser is launched offline

- Expected result:
Should not duplicate when launched offline

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
No

- Extra QA steps:
    1. Not sure if downloading a file and closing before its completed makes a difference
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
This may have been fixed with https://github.com/brave/browser-laptop/pull/9328... retesting now...

**Comment by bsclifton** [comment]
Verified this is still a problem. When launching while offline, I get one `about:error` page for each pinned tab it seems. When network is back up, I can relaunch Brave and the pages reload themselves properly... but the extra `about:error` tab (which is empty) is still there.
