### ISSUE TITLE
Multiple windows memory leak when playing games

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8997]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From support https://community.brave.com/t/multiple-windows-memory-leak-when-playing-games/3087
>I've noticed when I have more than one Brave window open at a time, and then I launch a game (in Windows 10 Creators Update), the game will force close due to "not enough memory" (when in fact I still have at least 6 out of 16 GB of RAM free).

- Brave Version (revision SHA):
Brave	0.15.2
rev	af7ef42
Muon	2.58.9

- Steps to reproduce:
    1.
    2.
    3.
 
- Screenshot if needed:

- Any related issues:
cc: @bridiver @darkdh

**Comment by Jacalz** [comment]
I get this:
![image](https://cloud.githubusercontent.com/assets/25466657/26319848/ede199da-3f20-11e7-99b7-cd7810096547.png)

**Comment by bridiver** [comment]
This doesn't really provide enough information to label it as a Brave issue. The failure to launch another app is a problem with that app, not Brave. The game probably needs more than 6GB to start. If Brave is using an excessive amount of memory or the memory usage is growing without bounds then we can open a Brave issue, but we need more info from the user about Brave memory usage.
