### ISSUE TITLE
Switching tabs to browser about pages is slow (e.g. new tab about:blank)

### ISSUE THREAD

**Issue by ayumi** [brave/browser-laptop#9004]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
With 10K bookmarks loaded, I found that switching to browser about pages is noticeably slower than webpages.
I tried:
  - New tab: Dashboard
  - New tab: Blank
  - Preferences
  - History
  - About Brave

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
c36af01fc17c4194562372680c014a727a3c5e57

- Steps to reproduce:
    1. Load 10K bookmarks into Brave.
    2. Set Preferences > New tab page to Blank.
    2. Go to github.com.
    3. Open a new tab and go to archive.org.
    4. Open a new tab.
    5. Switch between tab 0, 1, and 2 using Ctrl+Tab while observing switching latency.
    
- Actual result:
Switching to tab 0 and 1 (real webpages) is fast.
Switching to tab 2 (about blank) is slow.

- Expected result:
Switching to about pages should be fast.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Kind of– switching to the new tab dashboard is slightly slower.
However the lag is most noticeable with 10K bookmarks.

- Is this an issue in the currently released version?
Yes

**Comment by srirambv** [comment]
Note: Considerable performance improvement on Windows but the lag in switching to new tab(about:blank/dashboard) or about pages is still noticeable
