### ISSUE TITLE
Playing media on a site adds it to the autoplay site permission list (even when defaulted to "always allow")

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9008]
## Test plan
1. Clean install Brave
2. Ensure the default autoplay media is set to always allow
3. Visit any site and play audio/video
4. Verify site is NOT added to the site permission list as allow (Preferences > Security)

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Playing media on a site adds it to the site permission list even with default permission is set to always allow

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.306
rev	0067c4f
Muon	3.0.200

- Steps to reproduce:
    1. Clean install 0.15.306
    2. Ensure the default autoplay media is set to always allow
    3. Visit any site and play audio/video, site gets added to the site permission list as allow
    
- Actual result:
Playing media on a site adds it to the site permission list even with default permission is set to always allow

- Expected result:
Should only add when permission is set different from the default setting

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Marking as 0.16.100 as its not a release blocker. Please pull it back to 0.15.3xx if requried

**Comment by kjozwiak** [comment]
Clearing flags as this was tested against `0.20.x`, needs to be re-tested against `0.19.x`.

**Comment by srirambv** [comment]
Verified on 0.19.126. No site setting added when setting is set to `Always allow`
