### ISSUE TITLE
support for basic auth

### ISSUE THREAD

**Issue by artc** [brave/browser-laptop#901]
I'm not seeing a way to turn off popup blocking -- it's active,  but greyed out.
Need to turn it off so I can log in to some sites (that use a login in a popup).

Thanks,
Art

**Comment by bbondy** [comment]
CC @bridiver for triage, we don't have the ability to turn off popup blocking yet unfrotunately

**Comment by bridiver** [comment]
@artc what sites are not working for you? Popups should only be blocked if they are not user initiated (opened by clicking a link or similar action)

**Comment by artc** [comment]
Hey Brian,

I do some development work, and the sites-under-development are protected
by a popup that asks for a UID/Password before people can see them.
http://publicdocs2.wpengine.com , for instance.

It is a corner case, I admit, but I suspect there are a fair number of
sites out there that do this.

Cheers,
Art

P.S. Big thumbs up for you guys getting back so quickly!


Art Campbell
                                      artc@artc.net
    "... In my opinion, there's nothing in this world that beats a '52
Vincent and a redheaded girl." -- Richard Thompson
    No disclaimers apply.
  DoD 358

I support Community Supported Journalism at www.TheGrotonLine.com

**Comment by bridiver** [comment]
@artc take a look at #370 for a workaround for http auth. I'll leave this ticket open because we do need a method to turn off popup blocking, but that particular site is using http auth

**Comment by mlogic** [comment]
Many business websites rely on popup windows. For instance, Thomson Reuters' online journal publication website (https://mc.manuscriptcentral.com/) relies heavily on popup windows, and I haven't yet found a way to make it work under Brave. It would be great if the popup window blocker can be disabled on a per-website basis. Even a global switch is good to begin with.

**Comment by bridiver** [comment]
I think the terminology has been confused a little bit in this ticket so I want to make sure it is clear. Popups are new browser windows with content and they are currently allowed by default if they are user initiated (click on a link, etc..). This ticket was actually referencing the lack of a dialog box for http basic auth username/password. The only popups that are currently being blocked are windows that open automatically without any user interaction and the vast majority of the time those are ads or other unwanted content. Disabling popup blocking globally or on a per-site basis will almost certainly be implemented, but I want to make sure we are all talking about the same thing when we use the term "popup window" vs "dialog boxe"

**Comment by mlogic** [comment]
If that's what the OP wants, the subject of this ticket should be edited to something like "Add support for http basic auth dialog".

**Comment by bridiver** [comment]
closed by #370
