### ISSUE TITLE
IME does not work properly on input form

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9017]
## Test plan

1. Enable IME (Japanese/Chinese/Korean/...) on your system
2. Open about:autofill
3. Select 'Add address'
4. Hit some keys
5. Make sure you are seeing the pulldown
6. Hit <kbd>Tab</kbd>
7. Make sure a conversion candidate is selected
8. Hit <kbd>Enter</kbd>
9. Make sure the candidate is decided

----

**Describe the issue you encountered:** IME does not work properly on input form. You cannot select a conversion candidate. 

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): https://github.com/brave/browser-laptop/compare/v0.15.303dev...v0.15.304dev

- Steps to reproduce:
    1. Enable Japanese lang input system
    2. Open about:autofill
    3. Select 'Add address'
    4. Hit some keys
- Actual result:

   ![autofill](https://cloud.githubusercontent.com/assets/3362943/26372992/d32887a0-403a-11e7-82fd-7568ecc15575.gif)
  The form is not properly styled as I tried that by reverting it to https://github.com/brave/browser-laptop/blob/c719806d2265434b7e74fce0ef9a7bd061ddcc64/js/components/autofillCreditCardPanel.js to make sure CommonForm is not causing the issue.

  You could confirm the issue on Bookmark Hanger, which appears by clicking the star icon.
  Yet the issue cannot be reproduced on about:preferences#sync.

  ![autofill3](https://cloud.githubusercontent.com/assets/3362943/26373538/d9d8ece6-403c-11e7-8335-bd032d7ea848.gif)

- Expected result: on 0.15.2

  ![autofill2](https://cloud.githubusercontent.com/assets/3362943/26373228/a9d63644-403b-11e7-9285-74753cc846cf.gif)

- Is this an issue in the currently released version?
  No.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #

**Comment by bsclifton** [comment]
@luixxiul is this on master? or the last release? because they are very different at the moment.  If this is on master only, please remove from this milestone.  Thanks 😄

**Comment by darkdh** [comment]
confirm it occurs on autofill and bookmark dialog of 0.15.307

**Comment by luixxiul** [comment]
@bsclifton I'm trying to find out since which release it is broken.

**Comment by luixxiul** [comment]
@bsclifton @darkdh there should be the cause in here: https://github.com/brave/browser-laptop/compare/v0.15.303dev...v0.15.304dev

**Comment by bsclifton** [comment]
@luixxiul nice find! 😄 Thanks for narrowing it down

**Comment by luixxiul** [comment]
confirmed it works on devian with ibus-mozc
