### ISSUE TITLE
Button not disabled on add new bookmark modal by default

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9019]
## Test plan
https://github.com/brave/browser-laptop/pull/9321#issue-234342649
<hr>

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Button not disabled on add new bookmark modal by default

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.307
rev	97fb76e
Muon	3.0.200

- Steps to reproduce:
    1. Clean install 0.15.307 packaged build
    2. Click on bookmark toolbar and click on add bookmark folder
    3. Done button is not disabled by default. Clicking on it does nothing
    
- Actual result:
Button not disabled on add new bookmark modal by default

- Expected result:
Button should become active only when folder name is entered

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://cloud.githubusercontent.com/assets/17010094/26408951/13955ac8-4097-11e7-9601-6bf7016801d6.png)

- Any related issues:

**Comment by luixxiul** [comment]
Isn't it just the same issue as 'you cannot create empty title bookmark'?

**Comment by srirambv** [comment]
No. Adding a bookmark by removing the title sill adds the page title to it while you cannot create a empty bookmark folder. The button was disabled by default until the folder name was specified in 0.15.2

**Comment by luixxiul** [comment]
I see, the done button should be disabled at first until a character is input on the box.
