### ISSUE TITLE
autofill pulldown should consider downloadBar height

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9020]
**Describe the issue you encountered:** autofill pulldown should consider downloadBar height.

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Debian

- Brave Version (revision SHA): 0.15.307 / this cannot be reproduced on 0.15.2

- Steps to reproduce:
    1. Open about:autofill
    2. Create an entry
    3. Open www.roboform.com/filling-test-all-fields
    4. Download that page
    5. Trigger the autofill pulldown
    
- Actual result:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26409908/cdad5c90-40dc-11e7-8672-7a47183ddc34.jpg)

- Expected result:
  After dismissing the download bar:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26409956/e95b0fc8-40dc-11e7-9e76-ec6f14e7a292.jpg)

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
@darkdh can you help with this?

**Comment by darkdh** [comment]
sure
