### ISSUE TITLE
Upgrade Node

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9022]

**Comment by bbondy** [comment]
@hferreiro could you guys take this one?

**Comment by bridiver** [comment]
this is going to be a much more complicated upgrade than usual because of changes to the apis that the asar file uses

**Comment by hferreiro** [comment]
@bbondy sure, how should we prioritize this?

**Comment by bbondy** [comment]
Since 61 is on beta channel now I'd say that first, but there are 2 devs on this so maybe you can parallelize with this.  Not at the expense of 61 though please, thanks.

**Comment by zentagonist** [comment]
@bridiver do you have an update for this?
