### ISSUE TITLE
Lazy load pinned tabs after tear off tab-to-window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9024]
- Did you search for similar issues before submitting this one?
yes, but might be a dupe of existing one

- Describe the issue you encountered:
Tear off window should not load pinned tabs

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.307
rev	97fb76e
Muon	3.0.200

- Steps to reproduce:
    1. Have 10-12 pinned tabs and have two normal tabs
    2. Tear off one the normal tab into a new window
    3. Browser performance slows down as the pinned tabs in the teared off window are also getting loaded while the normal tab is also getting loaded
    
- Screenshot if needed:

- Any related issues:
#6413 
cc: @bsclifton @bbondy @bridiver

**Comment by luixxiul** [comment]
#7631 and #5800?

**Comment by srirambv** [comment]
Its similar to #5800 but that is specific to saying pinned tabs not to be shown in a new window. This is more on retaining the pinned tabs across all windows but not load(or lazy load) on new windows until the pinned is focused.

**Comment by bsclifton** [comment]
@srirambv The way it was worded in the title, it sounded covered by #5800.  But the real concern is covered by #804 and I believe this is a dupe (ex: #804 would solve this issue too, IMO)
