### ISSUE TITLE
Refactor safebrowsing.js with Aphrodite

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9025]
**Describe the issue you encountered:** Refactor safebrowsing.js with Aphrodite.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
closed with #13592

**Comment by bsclifton** [comment]
@jasonrsadler can you please add some testing steps for this? Or if you and @cezaraugusto agree it doesn't need manual testing, let's mark as `no-qa-needed`

**Comment by jasonrsadler** [comment]
@bsclifton I'll put some placeholder steps until I confer with @cezaraugusto on what the appropriate testing steps should be.

**Comment by cezaraugusto** [comment]
Labeling as `no-qa-needed` as no functionality was added and no design was changed.

**Comment by bsclifton** [comment]
@kjozwiak we're good to keep this in 😄 Safe browsing should still be present in Brave

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.17 bc754eb
* Muon 7.1.2
* libchromiumcontent 67.0.3396.87
