### ISSUE TITLE
Fingerprinting protection should distinguish between first and third party

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9029]
Fingerprinting protection should have 3 options: block all, block third-party, and none. In the future, we should enable 'block third party' by default for all users. Users who currently have FP set to 'on' will be transitioned to 'block all'. 

This supercedes https://github.com/brave/browser-laptop/issues/8142 and is related to https://github.com/brave/browser-laptop/issues/4621 / https://github.com/brave/browser-laptop/issues/2965.

cc @bradleyrichter on design for the Shields panel

**Comment by diracdeltas** [comment]
mockup https://github.com/brave/browser-laptop/issues/9016#issuecomment-303855033

**Comment by diracdeltas** [comment]
@bradleyrichter thoughts on what this should look like in the non-compact version?

**Comment by bradleyrichter** [comment]
@diracdeltas The compact version will most likely becomes the new version as it solves some l10n problems that are occurring in the 2-column layout.

It is also easier to add or change shields.

**Comment by luixxiul** [comment]
I assume many webcompat issues can be closed thanks to this implementation :-D

**Comment by Jacalz** [comment]
Great, Wouldn’t it be good to remove all site specific fingerprinting fixes that can be solved by third party fingerprinting?
That will make first party more secure since many sites technically has fingerprinting disabled 😉
