### ISSUE TITLE
Refactor sortableTable to make use of CSS Grid

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9032]
Making use of grid property will let us stick headers which are often suggested in places such as bookmarks and history pages, also at some point extensions and payments tab can also benefit. 

CSS grid shares almost the same goodies of` <table>` but more flexible and less verbose.

Refactor should take advantage of changes and occur together with Aphrodite refactoring.

I will self-assign this one to keep track, please jump in if you'd like to do as well. /cc @luixxiul

**Comment by luixxiul** [comment]
> CSS grid shares almost the same goodies of `<table>` but more flexible and less verbose.

+💯

**Comment by luixxiul** [comment]
I guess components such as `<GridItem row=1 column=1>` would reduce possibility of style inconsistency. you also would not have to define `gridStyles` to set up a grid layout.

**Comment by cezaraugusto** [comment]
what do you think of creating a new component (similar to what we've done w/ browserButton) making use of grid and gradually replace the old table?

**Comment by cezaraugusto** [comment]
it uses `tableSort` component but ours have so many custom methods that maybe it's better to just create a new one/fork. Food for thought I'd like to see something like that. Lmk if you're interested we can make it together soon

**Comment by bsclifton** [comment]
+1 on this approach @cezaraugusto 

Refactoring the existing one is too risky.  I'd like to propose closing this issue and open an issue in the repo where the work is being done on a common components lib 😄
