### ISSUE TITLE
Allow user to turn off location access globally in Setting

### ISSUE THREAD

**Issue by hook54321** [brave/browser-laptop#9033]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I can't turn off location access completely.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Manjaro (However platform is probably irrelevant)

- Brave Version (revision SHA):
b872523
    
- Actual result:
Settings page doesn't have ability to turn off location access.

- Expected result:
Users should be able to turn off location access.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
I'm technically not on the latest version, but I assume it is the same in the latest version. I am on 0.15.304.

- Can this issue be consistently reproduced?
Yes.

**Comment by bsclifton** [comment]
@hook54321a you can clear any existing settings by going to `Preferences` > `Security` and then clicking `Clear all` next to `Location access`

![screen shot 2017-06-09 at 12 18 38 am](https://user-images.githubusercontent.com/4733304/26965156-602bcaac-4ca9-11e7-899a-6c9927379002.png)

It would be good though to have a setting for always deny location (so it won't prompt you)

What do you think, @bradleyrichter?

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/934
