### ISSUE TITLE
Bookmark suggestions not listed when history suggestion is enabled under search

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9039]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmark suggestions not listed when history suggestion is enabled under search

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.308
rev	fc4b892
Muon	3.0.200

- Steps to reproduce:
    1. Enable history/bookmark suggestions under search
    2. Visit bookmarked sites to add in history
    3. Open a new tab, type in the site name, shows only under history and not under bookmark
    4. Disable history suggestion in search 
    5. Type in again the site name, shows up under bookmark
    
- Actual result:
Bookmark suggestions not listed when history suggestion is enabled under search

- Expected result:
Bookmark suggestion should come up along with history and tab 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![bloodhound](https://cloud.githubusercontent.com/assets/17010094/26192179/97515982-3ba8-11e7-8172-00881d9c2f57.gif)
- Any related issues:
https://github.com/brave/browser-laptop/pull/8824

**Comment by luixxiul** [comment]
#8976?

**Comment by srirambv** [comment]
Closing based on slack conversation with @bbondy @NejcZdovc
