### ISSUE TITLE
Add IME automated tests

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9045]
**Describe the issue you encountered:** Per https://github.com/brave/browser-laptop/pull/9031#pullrequestreview-40217278

> It would be interesting to think about (in the future) a way to have an integration test that uses IME... for autofill or typing in the URL bar. We couldn't include it as part of the standard tests since not everybody has their system/locale setup in a way that enables IME, but we could have a dedicated machine for setting the locale / running the tests

- Any related issues:

**Comment by luixxiul** [comment]
To enable IME (Japanese) on Debian, there's an IME which looks like Google IME, called `ibus-mozc`.

`apt-get install ibus-mozc` should install the Japanese IME on your linux. I'm wondering if this could be integrated with travis.

**Comment by bsclifton** [comment]
thanks for capturing this, @luixxiul 😄 

We have a private Jenkins instance which has Ubuntu 14 which we have full control over.  I can install / configure it for Japanese if you had some steps.  Enabling the input method editor is usually easy, but I'm curious about other concerns too (setting locale / region on top of language... recommended default settings for Japanese, etc...).

**Comment by luixxiul** [comment]
Later I'll install Ubuntu (en-US) afresh and log the steps to enable IME :-)

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1050
