### ISSUE TITLE
bookmarked about pages do not have the filled star icon

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9047]
**Describe the issue you encountered:** bookmarked about pages do not have the filled star icon.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26458878/8e7b004e-41af-11e7-95f1-04d04fae1d62.jpg)

![clipboard02](https://cloud.githubusercontent.com/assets/3362943/26458879/8e7c620e-41af-11e7-869d-258430369c98.jpg)

- Platform (Win7, 8, 10? macOS? Linux distro?): tested on debian

- Brave Version (revision SHA): 0.15.308

- Steps to reproduce:
    1. Open about:adblock
    2. Click the star icon

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment]
Confirmed on Windows

**Comment by bsclifton** [comment]
Moving to next release

**Comment by cezaraugusto** [comment]
taking

**Comment by NejcZdovc** [comment]
I think this should be put in 0.16.200, because 0.16.100 is in code freeze

**Comment by cezaraugusto** [comment]
this is a regression and was discussed in today's triage meeting as in .100 series so moving back to now 0.17.xx thanks for checking

**Comment by cezaraugusto** [comment]
@ayumi seems that regression happened after 980a85543d9e3bc8c468621564afee0f47f21d6d, mind taking a look?
