### ISSUE TITLE
Moving a dashboard tab to a bookmark folder destroys the current session

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9048]
**Describe the issue you encountered:** Moving a dashboard tab to a bookmark folder destroys the current session

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on debian

- Brave Version (revision SHA): 0.15.308

- Steps to reproduce:
    1. Open the browser
    2. Open a tab (which must be a dashboard)
    3. Create a bookmark folder
    4. Drag the tab and drop it onto that folder
    
- Actual result: the session is destroyed, discarding all opened tabs

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I added needs-triage label, wondering if this should be a blocker or not.

**Comment by srirambv** [comment]
Not able to repro on Windows with a clean profile

**Comment by luixxiul** [comment]
Me neither. closing
