### ISSUE TITLE
about:safebrowsing should work regardless of how you got there

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9056]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
when reviewing https://github.com/brave/browser-laptop/issues/8905 it was discovered that cmd+click opening a link to downloadme.org resulted in a blank page

- Platform (Win7, 8, 10? macOS? Linux distro?):
os x

- Brave Version (revision SHA):
0.15.3xx

- Steps to reproduce:
    1. visit http://alexwykoff.com/tests/testlinks.html
    2. cmd+click on the downloadme.org link

    
- Actual result:
a blank page is displayed

- Expected result:
All manner of display for about:safebrowsing should work. This includes but is not limited to:
Clicking on the link
Cmd+clicking on the link
Directly typing into the urlbar
Bookmarks

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by diracdeltas** [comment]
checked that all of those methods worked except cmd-click/rightclick to open in new tab
