### ISSUE TITLE
More suggestion fixes #9046 tracking ticket

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9062]
## Test plan
https://github.com/brave/browser-laptop/pull/9046#issue-231378955
- Test that matches against top500 matches sorts to prefix matches first.
- Test that only prefix matches on the url highlight the first item
- Type something that isn't a prefix of the first item and try to hover on top of the first item, it should highlight it. 
- Test all url suggestions matching and sorting works as expected

----

- Any related issues:

**Comment by alexwykoff** [comment]
lgtm
