### ISSUE TITLE
Control+W does not work after closing about:preferences

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9065]
**Describe the issue you encountered:** Control+W does not work after closing about:preferences. This is a follow-up to #8974

1. Open about:preferences#tabs
2. Change "When closing an active tab" setting to `Select the last viewed tab`
3. Open a new tab
4. Visit https://github.com on the tab
5. Click 'Features' on the menu
6. Click Go back button **two times** with the middle mouse button on the navigation bar
7. Select the last tab
8. <kbd><kbd>Control</kbd> + <kbd>W</kbd></kbd>
9. Repeat ^ until about:preferences#tabs is closed

Actual result: A blank github.com tab is left, which cannot be closed with <kbd><kbd>Control</kbd> + <kbd>W</kbd></kbd>

Expected result: the tab should be rendered and be able to be closed with the shortcut keys.

----

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Debian

- Brave Version (revision SHA): 0.15.309

- Steps to reproduce: See above

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #8974

**Comment by luixxiul** [comment]
By opening a new tab, the blank tab gets rendered fine.

**Comment by Liunkae** [comment]
Possibly related: #9083.

**Comment by alexwykoff** [comment]
@srirambv & @luixxiul can you repro on 0.17.x?

**Comment by luixxiul** [comment]
no it seems the issue has been fixed. it selects correctly the last viewed tab, which is not the tab opened first with the middle mouse button.

**Comment by luixxiul** [comment]
I'm wondering which PR has fixed the issue - @bsclifton do you have an idea?
