### ISSUE TITLE
Package Decentraleyes

### ISSUE THREAD

**Issue by JGH1000** [brave/browser-laptop#9066]
Great package for emulating Content Delivery Networks. Available for both Chrome and Firefox so should be easy to add.

https://github.com/Synzvato/decentraleyes

"Protects you against tracking through "free", centralized, content delivery. It prevents a lot of requests from reaching networks like Google Hosted Libraries, and serves local files to keep sites from breaking. Complements regular content blockers."

**Comment by bsclifton** [comment]
@JGH1000 great suggestion 😄 

We are tracking that on our extension page here:
https://github.com/brave/browser-laptop/projects/1#card-2140891

**Comment by JGH1000** [comment]
Fantastic, many thanks. It's a very good privacy one so hope it will get priority. Keep up the good work! :)

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/12836
