### ISSUE TITLE
Is it possible to disable new update check permanently?

### ISSUE THREAD

**Issue by stanleyxu2005** [brave/browser-laptop#9069]
- Yes. Not found any discussion before.

- I open Fiddler and see new version check requests send to server periodically. 

- Platform: Win7

- Brave Version (revision SHA): 0.15.2

- Steps to reproduce:
    1. Open Brave Laptop
    2. Open Fiddler to capture all HTTP requests
    
- Actual result:
After couple of minutes maybe hours, you will see requests sent to brave service.

- Expected result:
Need a way to turn it off

**Comment by luixxiul** [comment]
dup #1877
