### ISSUE TITLE
Not able to open / load URLs

### ISSUE THREAD

**Issue by anandbagmar** [brave/browser-laptop#907]
I am not able to load some urls - can you please help?
Example: 
https://www.thoughtworks.com/insights/blog/performance-testing-nutshell

**Comment by bbondy** [comment]
This loads for me, could you give me more information?  Does it not load at all? Or some specific function for you?

**Comment by anandbagmar** [comment]
for some reason it just did not work for me earlier, but is working now ... I guess we can close this for now. I will let you know with more specifics if it happens again. Thanks

**Comment by bbondy** [comment]
Please take a screenshot of it next time. Also in the console if you Command+Shift+I for errors (Or Control+Shift+I if on Windows)
