### ISSUE TITLE
Linux - rapid closing all but the last tab causes Brave to lose track of it

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9070]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
On Ubuntu, I opened a number of tabs then used ctrl+w to rapidly close them. The final tab appears blank but hovering over the tab reveals the contents.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux

- Brave Version (revision SHA):
0.15.309

- Steps to reproduce:
    1. Open a number of distinct tabs
    2. Rapidly close the tabs except for 1
    3. Observe the status of that tab
    
- Actual result:
The last tab content is obscured and appears blank until you hover on the tab control.

- Expected result:
The last tab's content should display normally.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
cc: @bbondy @bridiver

**Comment by bridiver** [comment]
I didn't intend for that commit to close it because I can't verify 100%

**Comment by bbondy** [comment]
@alexwykoff I just cherry-picked this in to `dev-channel`, can you verify if it is working?

**Comment by alexwykoff** [comment]
Fixed in master.

**Comment by alexwykoff** [comment]
Looks good on OS X, Windows, and Linux
