### ISSUE TITLE
Brave Fails to "Remember this decision"

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9076]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave fails to _remember this decision_ when _denying_ the use of _flash_ on a page. Each visit to that same page will prompt the user again to _allow_ or _deny_ flash. Clicking the _remember this decision_ label appears to have no effect.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
Desktop

**Brave Version (revision SHA):**
https://github.com/brave/browser-laptop/commit/fc4b892f1873551e44062f0c12dd262b7c5662f6

**Steps to reproduce:**
1. Navigate to https://get.adobe.com/flashplayer/about/
2. Select _Remember this decision_ and _Deny_
3. Refresh the page
    
**Actual result:**
User is prompted again to _Allow_ or _Deny_ flash.

**Expected result:**
Brave remembers to _Deny_ flash.

**Will the steps above reproduce in a fresh profile? If not what other info can be added?**
Yes

**Is this an issue in the currently released version?**
Yes

**Can this issue be consistently reproduced?**
Yes

**Comment by diracdeltas** [comment]
This was already fixed by https://github.com/brave/browser-laptop/pull/8828 i think

**Comment by alexwykoff** [comment]
While this appears to work for the adobe site, it doesn't work for homestarrunner.com. 
[2017-07-27 08-49-40.mp4.zip](https://github.com/brave/browser-laptop/files/1180150/2017-07-27.08-49-40.mp4.zip)
