### ISSUE TITLE
Polish compact bravery panel

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9077]
**Describe the issue you encountered:** Polish compact bravery panel based on @bradleyrichter 's spec on https://github.com/brave/browser-laptop/issues/9016#issuecomment-303855033.

> ![image](https://cloud.githubusercontent.com/assets/13509546/26425931/7838cf2a-408b-11e7-907f-ea312332ddec.png)
>
> - I added a close button as I have witnessed some user delay for initial closing.
> - I rearranged the top area to make room for the long URL
> - I adjusted the number area to allow for 1 or 2 numbers. I think this will look cleanest and not matter if digits are updating when the panel is open.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9016

**Comment by luixxiul** [comment]
I think this would satisfy @bradleyrichter:

<img width="293" alt="screenshot 2017-05-27 2 13 08" src="https://cloud.githubusercontent.com/assets/3362943/26505071/36efb508-4282-11e7-9a89-8a52095da3b5.png">

With a screen ruler:

<img width="318" alt="screenshot 2017-05-27 2 14 08" src="https://cloud.githubusercontent.com/assets/3362943/26505072/36f462ec-4282-11e7-9412-9c028db3c772.png">

**Comment by bradleyrichter** [comment]
woah...the only way I could tell it was not a mockup was the switch order. Amazing job @luixxiul !

**Comment by cezaraugusto** [comment]
moving to 0.18.x, pls see https://github.com/brave/browser-laptop/pull/9078#issuecomment-306673414

**Comment by bsclifton** [comment]
moving back to 0.17.x after merge issue was fixed 😄 👍

**Comment by alexwykoff** [comment]
Polish tasks shouldn't be included in release notes in general.
