### ISSUE TITLE
Boston Globe detects Private Tabs

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9082]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The Boston Globe detects Private tabs, and raises a paywall.

```js
window.webkitRequestFileSystem(0, 1, function() {
  // User is assumed to be in a normal tab
}, function(n) {
 // User is assumed to be in a private/incognito tab
});
```

When the user is thought to be in a Private tab, the `<body>` is given `overflow: hidden` to prevent scrolling, and a `div.gip__modal` element is appended to the body.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):

- Steps to reproduce:
1. Open a private tab
2. Navigate to https://www.bostonglobe.com/metro/2017/05/26/catie-copley-fairmount-copley-dog-ambassador-has-died/32xl2pgnPh8BbK8rO9YwBP/story.html
    
- Actual result:
Note paywall

- Expected result:
No paywall

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by anisse** [comment]
Supposedly this is the Chrome bug, but I can't access it:
https://bugs.chromium.org/p/chromium/issues/detail?id=93417
(Source: https://bugs.chromium.org/p/chromium/issues/detail?id=663727 )

**Comment by luixxiul** [comment]
Related with https://github.com/brave/browser-laptop/issues/10269 ?

**Comment by jonathansampson** [comment]
@luixxiul I don't think this is related to #10269. That issue is more about fingerprinting, while this one is merely identifying whether the user is in a Private tab, and then blocking them from certain content.

**Comment by bsclifton** [comment]
cc: @lukemulks in case he may know what to look for when investigating

**Comment by jonathansampson** [comment]
@bsclifton At the time, they were using the following to detect private tabs:

```js
window.webkitRequestFileSystem(0, 1, function() {
  // User is assumed to be in a normal tab
}, function(n) {
 // User is assumed to be in a private/incognito tab
});
```

**Comment by bsclifton** [comment]
@jonathansampson ah thanks- I totally missed that in the original post 😄
