### ISSUE TITLE
Windows only - Bookmarks toolbar - Bookmark hover targets are pushed down if there are no tabs below the folder

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9088]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A user from support reported that the highlight effect did not work as expected if there wasn't a tab underneath the bookmark folder.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Window

- Brave Version (revision SHA):
0.15.310

- Steps to reproduce:
    1. Create quite a few bookmark folders and add bookmarks
    2. Check bookmark folders above a tab vs those which exist over no tab.
    3. Slowly hover over each option
    
- Actual result:
The bookmark or sub-folder did not highlight for folders without tabs beneath them. (It was later discovered the targets were pushed down to the last couple pixels of each first bookmark entry in the expansion menu.

- Expected result:
The bookmark or sub-folder should have a highlight style applied 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by xjmzx** [comment]
Have a somewhat similar problem since last update to 0.15.310 on MacOS.

Bookmarks can no longer be dragged, dropped. Only created or delated.

OS: Sierra 10.12.5 (16F73)

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/first-entry-in-folder-on-bookmarks-toolbar-not-clickable/3459)

**Comment by bsclifton** [comment]
@xjmzx we have a fix for that which should be accepted soon 😄 
https://github.com/brave/browser-laptop/pull/9199

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/bug-report-bookmark-folder-top-item-bug/3572)

**Comment by alexwykoff** [comment]
@alexwykoff try to repro this plz 😸

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/unable-to-click-first-bookmark-in-a-folder-via-bookmark-bar/5803?u=eljuno

**Comment by NejcZdovc** [comment]
+3 from #10323

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/favorite-bar-issue/5900?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bug-report-bookmarks-not-being-selected/8656?u=eljuno

**Comment by luixxiul** [comment]
I suspect it is due to that the area is reserved for system context menu on Windows. @bsclifton might know well about that.

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/12097#issuecomment-348804531

**Comment by jonathansampson** [comment]
This does appear to rely on the mouse being within the region of the tab/new-tab elements below:

![hit-regions](https://user-images.githubusercontent.com/815158/33564238-a6fa79fc-d8df-11e7-8d98-fe33713253b7.gif)
![hit-regions-border](https://user-images.githubusercontent.com/815158/33564239-a711945c-d8df-11e7-8ef9-022941c33427.gif)

**Comment by jonathansampson** [comment]
The problem here is collision with _drag regions_. These do not respect `z-index`, and thus take-over the mouse anytime you enter a the coordinates of a drag-region. In the above example, the entire tabStrip is draggable. The tabs and new-tab button are not, which allows you to hover bookmarks while in their drag region.

One solution is to temporarily remove the `.allowDragging` class from `.tabStripContainer` when a bookmark menu is opened, and restore the class once the bookmark menu has closed.

```html
<span class="tabStripContainer allowDragging">...</span>
```

**Comment by LaurenWags** [comment]
+1 from twitter: https://twitter.com/wwwmarty/status/944245295927394304

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/first-favourite-website-in-a-folder-is-clickable-only-on-a-first-pixel/13328?u=eljuno

**Comment by srirambv** [comment]
+2 from community https://community.brave.com/t/bookmark-bug-unable-to-click-the-first-bookmark/13996/2

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bug-report-bookmark-bar-problem/13981?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmark-folder/14350?u=eljuno

**Comment by NejcZdovc** [comment]
I think that we need to bump priority on this one @bsclifton

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/unclickable-bookmark-area/14652?u=eljuno

**Comment by NejcZdovc** [comment]
pulled into 0.21

**Comment by eljuno** [comment]
Can't reproduced on latest stable version 0.20.30

Record:
![first-bookmark-20-30](https://user-images.githubusercontent.com/25360853/36000532-d533ad02-0d55-11e8-8920-3669ec2c43c1.gif)

**Comment by jonathansampson** [comment]
@elia The dropdown needs to overlap the tab and new-tab button.

**Comment by NejcZdovc** [comment]
pushing back to 0.22

**Comment by eljuno** [comment]
@jonathansampson Still can't reproduce this on latest stable. 😄 

![first-bookmark-20-30-overlap](https://user-images.githubusercontent.com/25360853/36225032-fd3bdfc2-11fb-11e8-9f7e-2dd65f5ba9e1.gif)

**Comment by alexwykoff** [comment]
@bsclifton @jonathansampson feel free to close if no repro thx

**Comment by bsclifton** [comment]
Confirmed this works great using `0.21.18` on Windows 10 x64 😄 👍
