### ISSUE TITLE
Bookmark title is not selected automatically

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9091]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Bookmark title is not selected automatically. This bug was introduces in this PR #9031.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
1da2c27
- Steps to reproduce:
    1. Go to some page
    2. Click bookmark star
    
- Actual result:
![image](https://cloud.githubusercontent.com/assets/9574457/26519883/54864f1e-42c8-11e7-9f27-7bed600c0edd.png)

- Expected result:
![image](https://cloud.githubusercontent.com/assets/9574457/26519881/50f353b0-42c8-11e7-8e7e-5467b827f3b2.png)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

**Comment by bsclifton** [comment]
marked as `automated-tests` and `QA/no-qa-needed` since this should be covered by tests (per comment in https://github.com/brave/browser-laptop/pull/9092)
