### ISSUE TITLE
Unable to remove single item from URL bar autocomplete list

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9094]
**Describe the issue you encountered:** Unable to remove history from URL bar autocomplete list.

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Input `github` on URL bar
    2. Select any item
    3. Try to remove it as you would do on Chrome/Firefox
    
- Actual result: It cannot be removed

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
+5 from @shortstuffsushi via https://github.com/brave/browser-laptop/issues/11398 (including the 👍  the top post has)

> The URL suggestion bar sometimes picks up specific site links I don't want. In my case, I have some "newson6.com" link -- not even sure where it's from, and I don't want it to be suggested when I start a search term "news." Similar things seem to happen where I get results with specific query strings appended that aren't relevant, or URL paths instead of root... the list goes on.
>
> Ultimately, I would like a function allowing me to clear individual suggestions, either via a keyboard shortcut (delete, shift delete, ctrl delete, etc) or via right-click + delete option.

**Comment by bsclifton** [comment]
@bbondy @bradleyrichter is there a keyboard shortcut to manually remove entries? I swear there used to be one, like shift + delete?

**Comment by bbondy** [comment]
Yes I think it was shift+delete, and I thought @NejcZdovc recently fixed that

**Comment by bsclifton** [comment]
hmm... definitely doesn't work in 0.19.x.  @NejcZdovc do you know if this was fixed in 0.20.x or newer?

**Comment by NejcZdovc** [comment]
I don't remember that worked on anything like this. I only worked on possibility to remove items from autosuggestion. And this was then connected to the clear history action.

**Comment by bsclifton** [comment]
+1 from https://github.com/brave/browser-laptop/issues/12157

**Comment by WalkThePath42** [comment]
It's really frustrating to not be able to correct a once-off mistake easily.

As a Windows user, it's natural for me to type something in, and if auto prompt shows something I don't want, or want more info on, then I right-click my mouse on that entry to interact with it.

My expectation would be to have the following options:
1.)  Delete entry from auto-prompt and delete it's associated caching (clear history this item)
2.) Add to Bookmarks
3.) Make 1st prompt (like a star for favorites that will put it to the top earlier, i can un-star it as a toggle)
4.) copy url to clipboard
5.) Open in private tab (tor)
6.) Open in new private window
7.)  Detailed Analysis (dig into the cache to explore what is there, i.e., size, date, pictures)
etc.

Anyways, at _least_ being able to easily clear a single item is NEEDED, and super-frustrating to not have.

**Comment by shortstuffsushi** [comment]
Hey... what's up with the wontfix @bsclifton? This seems like a relevant and desired feature?

**Comment by bsclifton** [comment]
@shortstuffsushi apologies if that's confusing; we've wound down development on the `browser-laptop` product in favor of the new code-base, brave-core. This may very well be fixed already, if you wanted to confirm

You can download the developer channel release here:
https://brave.com/download-dev

**Comment by shortstuffsushi** [comment]
Oh, ok. I haven't been closing following the repos aside from my issues, so I didn't realize development was migrating. I'll take a look over there and then potential raise this there if the problem still exists if that's cool.

**Comment by shortstuffsushi** [comment]
This does seem to be fixed in the dev version.
