### ISSUE TITLE
"Select the last viewed tab" switches tabs when it shouldn´t

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9096]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
If you have "Select the last viewed tab" enabled and you close a nother tab then the one you are mon you swith tabs
- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 x64
- Brave Version (revision SHA):
0.15.310
- Steps to reproduce:
    1. Open 3 tabs with different pages
    2. Change to tab 2
    3. Hold over the first tab and remove it
    4. See that the tab switches to the third tab
    
- Actual result:
You switch from tab 2 to tab 3
- Expected result:
You should be left on tab 2
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Screenshot if needed:
![last viewed tab](https://cloud.githubusercontent.com/assets/25466657/26527016/eb5a44e6-438a-11e7-9930-0ea7ccf19e14.gif)

**Comment by bsclifton** [comment]
This may be fixed with our latest release... @Jacalz can you please retest?

**Comment by Jacalz** [comment]
Not fixed and this is getting really annoying :sweat_smile:

**Comment by Liunkae** [comment]
This problem is annoying me too. IMO, the active tab should never switch on a tab close unless the active tab itself is closed.

**Comment by Jacalz** [comment]
Can we assign a milestone please it is extremely annoying I would like to get it in 0.17.14 but probably won't happen 😅

**Comment by Jacalz** [comment]
Still able to repro on 0.18.9 :-1:

**Comment by bsclifton** [comment]
@Jacalz does this still happen? I know there have been recent fixes

**Comment by Jacalz** [comment]
Looks to be fixed 👍
