### ISSUE TITLE
about pages appear two times under History on URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9097]
**Describe the issue you encountered:** about pages should not listed under `History` section after bookmarking the about pages

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian and Windows 10

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Clear the browser's profile
    2. Open the browser
    3. Bookmark a new tab 
    4. Input `about`
    
- Actual result:

  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26527045/63caeabc-43c6-11e7-8bd1-104eb6406f29.jpg)
  
  

- Expected result: about pages should not be under `History` section

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I do not remember well but this might be a regression after bloodhound update.

At least I have not seen the two slashes on about pages' URL.

**Comment by NejcZdovc** [comment]
@luixxiul this was done intentionally. More info here https://github.com/brave/browser-laptop/issues/8976#issuecomment-302981585

**Comment by luixxiul** [comment]
Is having `about://newtab` and `about:newtab`, which is on the 1st shot, intentional?

If so, that should not.

**Comment by luixxiul** [comment]
I changed the title to avoid confusion.

**Comment by NejcZdovc** [comment]
Ok, so the problem is not with history+bookmarks, but with double entry?

**Comment by bsclifton** [comment]
IMO, we should not be handling `about://page-name-here`.  I don't think we should treat it like a protocol.  If we wanted to offer something comparable to chrome, we can consider redirecting `chrome://` pages to `about:`.  For example, `chrome://settings/` => `about:preferences`

**Comment by bsclifton** [comment]
@luixxiul I can't reproduce this. Additionally, going to `about://newtab` does nothing on my machine (which is expected IMO, since it's invalid. I don't have a protocol handler for `about://` configured (to my knowledge).  Even after trying to visit the page, it does not show up in history.

I'm on 0.15.314.  If this is still an issue, let's try to reproduce on a fresh profile and then create steps.  `about://newtab` should not be navigable (and should be going to an error page after it times out)

**Comment by luixxiul** [comment]
I'll try to reproduce the error and polish up the STR later.

**Comment by luixxiul** [comment]
With the same STR on the 1st post I still see the issue:

<img width="441" alt="screenshot 2017-06-09 0 55 05" src="https://user-images.githubusercontent.com/3362943/26938135-50e94894-4cae-11e7-95b6-32b7c968b88c.png">

**Comment by luixxiul** [comment]
I'm not sure why I get `Brave: 0.15.312` on the master branch :-?

**Comment by bsclifton** [comment]
@luixxiul we were just late to update.  You can try again, but it seems like this is still an issue
