### ISSUE TITLE
How to install brave browser on Linux? Help improve the doc

### ISSUE THREAD

**Issue by edouard-lopez** [brave/browser-laptop#910]
I'm starting a wiki page so various Linux distros can [document how to install `brave`](https://github.com/brave/browser-laptop/wiki/Install-on-Linux) in their ecosystem.

The idea is:
- README page is already confusing and should not document various install methods.
- to **evolve toward automation scripts**.

Help massively welcome.

**Comment by bbondy** [comment]
Thanks could you also mention the x64 binaries we're providing as of this version on the release page?
https://github.com/brave/browser-laptop/releases

**Comment by FrancisTurner** [comment]
YOu should probably link to the Troubleshooting page. The two pages are probably complementary.

Defintiely need to note that for dev use you HAVE to get the right versions of node etc.

**Comment by edouard-lopez** [comment]
@FrancisTurner I'm not targeting dev here but end-users

I didn't manage to run brave using the step I documented. If you have advice, I'll gladly document but not sure what I'm missing. 

I was not aware of the Linux `tar.gz` since it new. I'll give it a go.

**Comment by luixxiul** [comment]
It should be much easier to install Brave when apt #1759 and #1170 are implemented. For Fedora/Red Hat, #1162 has been done.

Still you can update the document to tell end users how to install Brave.

**Comment by bsclifton** [comment]
+1 from support; customer could have benefited from instructions or an easier install process
> After the dpkg for it failed, I had to 
install the needed git package, and surprisingly, the broken Brave 
became fixed. (BTW, I'm running Linux Mint Debian x64 in a core-i5 
tower with 13 GB and three HDDs.)

**Comment by posix4e** [comment]
Seems good to go!
