### ISSUE TITLE
Can not move bookmarks/folders to other folders in Bookmark Manager

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#9101]
## Test plan

https://github.com/brave/browser-laptop/pull/9199#issue-232986488

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I would like to re-arrange my bookmark(s) via Bookmark Manager. Drag and drop bookmark(s) to other folder don't move the bookmark(s).
Update: Can't re-arrange folders and bookmarks order, too.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win8.1

- Brave Version (revision SHA):
0.15.310 (6b5e4e2)

- Steps to reproduce:
    1. Create/have a bookmark(s) and folder
    2. Open Bookmark Manager
    3. Drag and drop bookmark(s) to other folders
    
- Actual result:
Bookmark(s) still in previous folder, not move to destination folder

- Expected result:
Bookmark(s) move to destination folder

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-bookmark-manager-bug-cant move-bookmarks](https://cloud.githubusercontent.com/assets/25360853/26532071/020183ca-4422-11e7-94a1-52865907e864.gif)

- Any related issues:

**Comment by oharrison72** [comment]
+1

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/bookmark-manager-is-unusable/1659/4?u=eljuno).
User use mac air with 10.12.5 os.

**Comment by bijeebuss** [comment]
+1

**Comment by cezaraugusto** [comment]
related #8946, taking

**Comment by bsclifton** [comment]
Moving to `0.16.x` since this is a pretty bad

cc: @bbondy
