### ISSUE TITLE
Spell check not working with C59

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9102]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Spell check isn't working with the C59 upgrade

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on Windows, but probably all.

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/be76cd3043e61f363cd3f196075e9923cfaab866

- Steps to reproduce:
    1. Navigate to https://github.com/fdafdasfasdfdsafasdfds
    2. Type the following text in the textbox: `Hallo werld `
     
- Actual result:
No underlines

- Expected result:
Red underlines

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

**Comment by srirambv** [comment]
Spell check works but underline is retained. #9324 logged for the same
