### ISSUE TITLE
Create npm scripts to set up a number of bookmarks, sync groups, and ledger sites

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9111]
**Describe the issue you encountered:**
Create npm scripts to set up a number of bookmarks, sync groups, and ledger sites, to make it easy to conduct performance tests.

It is no easy to create 1000 bookmarks by hand. Even though you have done, the session file could get corrupted sometimes, and you would never create them again.

A bookmark file example: https://gist.github.com/jgarber623/cdc8e2fa1cbcb6889872

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Unassigning milestone because there isn't an owner set. If we'd like to bump up priority on this, let's talk on Slack

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/1058
