### ISSUE TITLE
Log in pop-up window / tab should be closed on Pocket

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9113]
**Describe the issue you encountered:** Log in pop-up window should be closed on Pocket. 

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Enable Pocket extension
    2. "Log in with Google account"
    3. the pop up remains with a blank tab with this URL: `https://apis.google.com/_/history/otaappinstalldone?clientId=XXXXXXXXXX-oek12ddu7d36lbnpquv9dr8rs6ijcer0.apps.googleusercontent.com&appId=com.ideashower.readitlater.pro&projectId=173409440056&outcome=nothanks`
    
- Expected result: The pop up window should be closed. I am not sure if this is a regression.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Also the log-in tab with URL `https://getpocket.com/extension_login_success` should be closed after you've logged in successfully.

**Comment by jonathansampson** [comment]
Tracking at #4687

**Comment by luixxiul** [comment]
Duplicate of #9132
