### ISSUE TITLE
PDF file cannot be saved on Pocket

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9115]
**Describe the issue you encountered:** PDF file cannot be saved on Pocket. You can save a PDF file with Pocket on Firefox.

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Enable Pocket
    2. Open http://www.orimi.com/pdf-test.pdf
    3. Click Pocket button
    
- Actual result: the URL is not saved on Pocket

- Expected result: It should be.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
CC @jonathansampson for investigation.

**Comment by jonathansampson** [comment]
@luixxiul What happens instead?

**Comment by luixxiul** [comment]
Nothing happens; the color of the icon does not change, and the PDF file is not saved.
