### ISSUE TITLE
Autofill popup should consider docked browser tools height

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9118]
**Describe the issue you encountered:** Autofill popup should consider docked browser tools height

- Brave Version (revision SHA): 0.16.0 be76cd3 (Muon 3.2.101)

- Steps to reproduce:
    1. Open about:autofill
    2. Create an entry to Name
    3. Open www.roboform.com/filling-test-all-fields
    4. Open browser console (Shift+f8) and dock it to the bottom of the window
    4. Minimize the height of the devtool
    5. Trigger the autofill pulldown

- Actual result: the autofill list appears under `Title`

- Expected result: the autofill list should be under `First Name`

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  With download bar
  ![image](https://cloud.githubusercontent.com/assets/17010094/26542932/c1b0df00-4453-11e7-894d-f92fc6af31bc.png)

  With browser console docked at bottom
  ![image](https://cloud.githubusercontent.com/assets/17010094/26542976/f0071054-4453-11e7-922a-51a05bb54f59.png)

- Any related issues: #9020

**Comment by luixxiul** [comment]
I edited the 1st post to make it clear what the issue here is.
