### ISSUE TITLE
Spell check fails on Windows

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9119]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Spell check fails on Windows

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Clean install 0.16.0
    2. Open about:style and enter wrong text in text field
    3. Wrong text doesn't have red underline to indicate misspelling 
    
- Actual result:
Wrong text is not showing misspelling indicator

- Expected result:
Should underline misspelt words

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![spellcheck](https://cloud.githubusercontent.com/assets/17010094/26544212/da30022c-4458-11e7-8b97-c1e6bbc1fe2e.gif)

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #9102? ref https://github.com/brave/browser-laptop/labels/cr59

**Comment by srirambv** [comment]
Closing as dupe
