### ISSUE TITLE
View log shows console errors when checking for update

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9122]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
View log shows console errors when checking for update

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Set brave to an older version in system variables
    2. Launch browser and click on check for update
    3. Open browser console and click on view log button, shows console error, doesn't open the log file
    
- Actual result:
View log shows console errors when checking for update

- Expected result:
Should open the log file

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![viewlog](https://cloud.githubusercontent.com/assets/17010094/26545898/4d038b10-445f-11e7-82f1-21e19741c68e.gif)

- Any related issues:
cc: @bbondy

**Comment by bbondy** [comment]
This one has been there for a long time, since we removed node from renderers. I agree we should fix now though.

**Comment by srirambv** [comment]
Still an issue on Windows. Reopening the issue
![1](https://user-images.githubusercontent.com/17010094/26903518-7e1710b4-4bd5-11e7-9727-eef266337659.gif)

**Comment by alexwykoff** [comment]
confirmed not working on os x as well

**Comment by bbondy** [comment]
re-added to milestone 0.16.x, looks like it just doesn't exist on that branch when it should have at merge time.

**Comment by bbondy** [comment]
cherry-picked it into 0.16.x now, it'll be in rc2.
