### ISSUE TITLE
Tab focus is set to URL bar even when URL is autopopulated

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9123]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab focus is set to URL bar even when URL is autopopulated
Reported on [community](https://community.brave.com/t/is-it-possible-to-not-automatically-select-the-address-bar-on-a-new-tab/3211)

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Right click on a link and open in a new tab/ Control click a bookmark to open in a new tab
    2. Focus is set to URL bar, Should be set on the webview 
    3. Focus should be on URL bar only when a new tab is opened and not when a link is opened in a new tab
    
- Actual result:
Tab focus is set to URL bar even when URL is autopopulated

- Expected result:
Focus should be on webview and not URL bar when URL is populated, similar to chrome

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
@srirambv can you repro, @bbondy and I tried, but works fine on 0.17.x

**Comment by srirambv** [comment]
@bbondy  @alexwykoff  Still reproducible on Windows for 0.17.x upgrade from 0.16.9

**Comment by svenified** [comment]
In order to reproduce this, the following setting must be turned off:
Tabs -> Switch to new tabs immediately.
If it is turned on, the tab select correctly goes to the webview.

**Comment by Liunkae** [comment]
Still reproducible with Brave 0.18.21.

**Comment by juil** [comment]
Still reproducible in `Brave 0.23.19`
`MacOS 10.13`
