### ISSUE TITLE
"cast_sender.js net::ERR_FAILED" on Favorites on Youtube

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9124]
**Describe the issue you encountered:** There are "cast_sender.js net::ERR_FAILED" on Favorites on Youtube. I am not sure what the errors mean (the page works as it should) or we should fix them.

````
common.js:297 GET chrome-extension://fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js net::ERR_FAILED
np @ common.js:297
op @ common.js:296
(anonymous) @ common.js:296
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js:1 GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js:1 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js:1 GET chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js:1 GET chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js net::ERR_FAILED
````

I don't see the error on Firefox.

- Platform (Win7, 8, 10? macOS? Linux distro?): On Windows 10

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Open https://youtube.com
    2. Log in
    3. Click "Favorites"
    4. Toggle the developers tool
    
- Actual result: See the above

- Expected result: Not sure

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
+1 from [community ](https://community.brave.com/t/chrome-extension-err-failed/3198)
>All extensions are disabled however i get a GET chrome-extension net::ERR_FAILED on youtube.com

**Comment by bsclifton** [comment]
This is happening because it's trying to use Chrome Cast (which isn't present in Brave). Closing as `wontfix`
