### ISSUE TITLE
Browser console shows Whats new tab in console

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9125]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser console shows Whats new tab in console

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Clean install 0.16.0 build
    2. Open browser console (Shift+F8)
    3. Shows `Whats new ` tab section
    
- Screenshot if needed:
![pasted image at 2017_05_29 08_59 am](https://cloud.githubusercontent.com/assets/17010094/26554707/8b27253a-4489-11e7-8572-e5419d3c37a8.png)

- Any related issues:

**Comment by bsclifton** [comment]
Do we not want this behavior @bbondy?

@srirambv does it show for content level dev tools also? (F12)

**Comment by srirambv** [comment]
@bsclifton  Yes it shoes on content level dev tools as well!

**Comment by Jacalz** [comment]
I don't see any bad in having this, it is great to see what's new but maby it should be renamed to new in chromium 59 instead to not confuse with chrome👌😎

**Comment by aliakyurek** [comment]
It's getting bigger and bigger
![image](https://user-images.githubusercontent.com/5635699/35794343-6fe4c72a-0a66-11e8-81a4-3fa73bc1387e.png)

**Comment by bsclifton** [comment]
Closing as I think this is a great feature 😄 👍 I do understand that this is intended to track this showing on Browser tools (vs page tools)... but it should still save the preference if you close the "What's new" box
