### ISSUE TITLE
Blank screen when playing video in full screen mode

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9126]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported on [community ](https://community.brave.com/t/blank-videos-when-in-fullscreen-mode/3067/2)
>Im not sure what is occurring, as I am getting blank black screen when fullscreening videos whether on Youtube, or any movie site.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows x64

- Brave Version (revision SHA):
>Brave: 0.15.310 
rev: 6b5e4e2d300959848e0e848817aa40385447f2eb 
Muon: 3.0.201 
libchromiumcontent: 58.0.3029.110 
V8: 5.8.283.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 10.0.15063 
os.arch: x64

- Steps to reproduce:
    1.
    2.
    3.
    
- Extra QA steps:
    1. User says hardware acceleration is truned off and flash is disabled
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
@srirambv can we have the user try these steps? (I can't unlock/edit the Community issue)
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

**Comment by srirambv** [comment]
User confirmation as resolved
>It's the GPU. Nvidia marked it as run with the dedicated high performance gpu (970m GTX). Instead of default which was my integrated GPU.

**Comment by Rafi993** [comment]
In some sites this issue appeared even when playing video without full screen. Even though the above fix works for now this should be opened so that future version of brave works without this flag out of the box.
