### ISSUE TITLE
Feature request: Add dropdown menu for bookmarks

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9127]
From community:
https://community.brave.com/t/user-interface-customization/3221
Add a quick and easy bookmarks drop down menu like the one found here:
https://chrome.google.com/webstore/detail/bookmarks-menu/ffmdedmghpoipeldijkdlcckdpempkdi

**Comment by oharrison72** [comment]
+1

**Comment by rebron** [comment]
Closing wontfix here and tracking in brave-core https://github.com/brave/brave-browser/issues/1069
