### ISSUE TITLE
Entering about://newtab loads indefinitely

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9130]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Entering about://newtab loads indefinitely

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Install/Upgrade to 0.16.0
    2. Open new tab and type `about://newtab`
    3. Loads `about:blank` and keeps loading indefinitely
    
- Actual result:
Tabs load indefinitely

- Expected result:
Should load  `about:newtab`

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#8584 
cc: @bridiver

**Comment by bridiver** [comment]
Is that a typo? about://newtab is not valid. It should be about:newtab. We should probably handle with or without //, but handling // would be a new feature afaik

**Comment by luixxiul** [comment]
@bridiver actually you would get both:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26527045/63caeabc-43c6-11e7-8bd1-104eb6406f29.jpg)

https://github.com/brave/browser-laptop/issues/9097#issue-231853472

**Comment by bridiver** [comment]
not sure where `about://newtab` is coming from because that has never been a valid url for us. If it worked in the past it was a fluke

**Comment by bridiver** [comment]
some parts of the code will handle that and some parts won't, so the results you get for it will be unpredictable at best

**Comment by srirambv** [comment]
`about://newtab` doesn't show up in the URL bar suggestions on the previous build but it does have the same effect when I type in.

**Comment by bridiver** [comment]
it is showing up with a fresh install or only after you entered it once?

**Comment by srirambv** [comment]
Opened about pages shows up with `about://<pagename>` under history suggestions on 0.15.312 packaged build
![image](https://cloud.githubusercontent.com/assets/17010094/26619429/572d6d18-45d6-11e7-8f79-c2932715a61c.png)

**Comment by Jacalz** [comment]
+1 from me on 0.17.13 and also on latest master
