### ISSUE TITLE
Extension tabs not auto closing when finished

### ISSUE THREAD

**Issue by mouse-man** [brave/browser-laptop#9132]
**Describe the issue you encountered:** Tested with both LastPass and Pocket.

Log in via pocket, tab doesn't close once authenticated.
2FA in LastPass, tab doesn't close once button clicked to submit code.

Both show they actually authenticated the extension as I can then interact with the extension (i.e. add articles to Pocket or log in via LastPass filled credentials.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win8.1 Pro and Win10 Pro Fast ring.

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Open browser, LastPass asks for 2FA code
    2. Enter code and press button
    3. Extension authenticates, however tab is not closed
    
- Actual result: Tab not closed

- Expected result: Tab closed

- Will the steps above reproduce in a fresh profile? If not what other info can be added? Yes

- Is this an issue in the currently released version?
Yes, only occurred after latest update on both machines.

- Can this issue be consistently reproduced? Yes

#9113

**Comment by jonathansampson** [comment]
Tracking at #4687

**Comment by luixxiul** [comment]
adding the labels as #4687 has been labelled with no-qa-needed
