### ISSUE TITLE
0.16.0dev won't launch on Linux - illegal instruction

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#9133]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Brave 0.16.0dev crashes at launch
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Slackware-current
- Brave Version (revision SHA):
0.16.0dev
- Steps to reproduce:
    1. Invoke Brave
    2.Window frame appears and then disappears
    3. Console shows: Failed to generate minidump.Illegal instruction
    4. Kernel ring buffer log shows: traps: brave[1522] trap invalid opcode ip:18d2f06 sp:7ffcb00359d0
    
- Actual result:
No launch
- Expected result:
Browser launch
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

Reversion to 0.15.310 launches fine.

**Comment by luixxiul** [comment]
thanks, that bug has been captured already: #9112
