### ISSUE TITLE
Pinned tab shows blank white page when relaunching the browser 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9134]
## Test plan

https://github.com/brave/browser-laptop/pull/9219#issue-233332969

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pinned tab shows blank white page when relaunching the browser. It is exactly #8873

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Have a few pinned tabs
    2. **Set focus to the last pinned tab** and close the browser
    3. **_Wait for a while before relaunching_** the browser (important step)
    4. After relaunch, the last pinned tab is white blank page
    5. Hover over the last tab reveals the page content, Only after clicking the page it  shows the page content correctly
    
- Actual result:
Pinned tab shows blank white page when relaunching the browser 

- Expected result:
All tabs should be loaded properly and page content should be shown correctly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Found on previous build but closed as it might have been fixed by  #8863 

- Can this issue be consistently reproduced?
Yes. 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#8873 
cc: @bridiver

**Comment by bsclifton** [comment]
appears to be 0.16.0 specific; unable to repro on 0.15.310.  Moving back to 0.16.0

**Comment by bridiver** [comment]
Step 3 seems very odd to me. Absolutely nothing happens between the time that the browser shuts down and the time that it starts back up again. If there is a timing issue after shutdown the problem may be related to shutdown not completing in a normal time

**Comment by bridiver** [comment]
I see a completely different issue in master which is that it reopens with the first normal tab active instead of the pinned tab

**Comment by bridiver** [comment]
this must be windows only. On mac I also get the first normal tab instead of the pinned tab

**Comment by bridiver** [comment]
didn't notice it was windows only, but mac also has the wrong behavior. Not sure why they would be different

**Comment by bsclifton** [comment]
Will be ready to retest with the next build. Stay tuned...

**Comment by bbondy** [comment]
I think this is fixed, please re-open if it doesn't pass.

**Comment by bsclifton** [comment]
Confirmed fixed on Windows 10 x64 😄
