### ISSUE TITLE
Credential Server Response 400 error while enabling sync 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9135]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Credential Server Response 400 error while enabling sync  reported by user on community  https://community.brave.com/t/i-cant-turn-on-brave-sync/3242/

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 

- Brave Version (revision SHA):
Brave: 0.15.310 
rev: 6b5e4e2d300959848e0e848817aa40385447f2eb 
Muon: 3.0.201 

- Steps to reproduce:
    1. Enable sync on a new profile
    2. Shows `Credentail server response 400` 
    3.
    

- Screenshot if needed:
https://imgur.com/a/G5Mz2

- Any related issues:

**Comment by piiiggg** [comment]
I still got this problem after update on Release channel

**Comment by alexwykoff** [comment]
migrated to https://github.com/brave/sync/issues/114
