### ISSUE TITLE
Closing tab gives you 'Unchecked runtime.lastError'

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9136]
**Describe the issue you encountered:** Closing tab gives you `Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error.`

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. <kbd>Shift + F8</kbd>
    1. Open a tab
    2. Close it
    
- Actual result: `Unchecked runtime.lastError while running guestViewInternal.destroyGuest: Unknown error.`

- Expected result: that error should not happen

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: https://github.com/brave/browser-laptop/issues/8175

**Comment by bsclifton** [comment]
This is a known issue. @bridiver can give a specific explanation, but this has no negative impact. Preventing the error from being logged might be more work than its worth
