### ISSUE TITLE
When using IME results are shown before selection is made

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9139]
## Test plan

https://github.com/brave/browser-laptop/pull/12172#issue-279183334

----

**Describe the issue you encountered:** 
Some search queries in URL bar autocomplete suggestion are tofu. I susupect this is related with bloodhound upgrade as I have not seen this in previous versions.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Have IME setup for Chinese / Japanese / other language
    2. Open about:preferences#search
    3. Enable google.com as default search
    4. Enable the last option on the preference page
    5. Set you brave's lang setting to Japanese
    6. Open a tab
    7. Input a few characters
    8. Search terms show even though IME selection not made (notice underline in URL bar)
    
    ![screen shot 2018-02-08 at 10 21 01 pm](https://user-images.githubusercontent.com/4733304/36013058-4353085a-0d1f-11e8-8da6-e93a51d32752.png)

**Comment by alexwykoff** [comment]
@luixxiul can you try vs 0.14 and update with more specific steps?

**Comment by darkdh** [comment]
In Traditional Chinese,
Brave
<img width="795" alt="screen shot 2017-06-13 at 10 49 22 am" src="https://user-images.githubusercontent.com/11330831/27097015-c3361c20-5027-11e7-9f12-22601e8b58d5.png">
Chrome
<img width="422" alt="screen shot 2017-06-13 at 10 50 00 am" src="https://user-images.githubusercontent.com/11330831/27097019-c808c388-5027-11e7-8c78-58811538bf78.png">

**Comment by luixxiul** [comment]
The issue cannot be reproduced with 0.15.2, on Windows 10.

**Comment by luixxiul** [comment]
![clipboard01](https://user-images.githubusercontent.com/3362943/27113961-46f4fc60-50fb-11e7-8517-c935100d5a32.jpg)

with af7ef42.

**Comment by luixxiul** [comment]
On 0.19.7

![clipboard01](https://user-images.githubusercontent.com/3362943/30646049-9de27026-9e52-11e7-86ce-e730e084a50d.png)

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 x64 using the following build:
* 0.22.7 https://github.com/brave/browser-laptop/commit/8bb7e77f69bca186429aafda4bc6ba4d82a5de47
* libchromiumcontent: 65.0.3325.181
* muon: 5.1.1

**Comment by kjozwiak** [comment]
Went through the above STR with both @darkdh and @bsclifton using Ubuntu & Windows. Noticed that the autocomplete results are not being displayed once text via IME has been entered into the URL bar. Created #13639 to address the issue.

We'll release what we have now but will make a note in the release notes indicating that this fix only works on macOS.
