### ISSUE TITLE
OSX "New Session Tab" and "New Private Tab" does nothing unless window already open

### ISSUE THREAD

**Issue by francois** [brave/browser-laptop#914]
# Steps to reproduce

* Open Brave
* Close down *all* windows
* Using the mouse, click File, then "New Private Tab" or "New Session Tab"
* Watch as nothing happens
* Do File, New Tab, watch as new window + tab appears

# What I expected to happen:

* A new window with a private or session tab open

Platform: OS X 10.11.2 (15C50)
Brave Version: 0.7.16
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110

**Comment by bbondy** [comment]
++ nice find
