### ISSUE TITLE
'autocomplete search term' results are not filtering out 'http...' results

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9141]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Selecting suggested FQDN causes search instead of opening the site

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Install/Upgrade to 0.15.310
    2. Disable all options except `Autocomplete search term` under search in preferences
    2. Type bug in the URL to show up the search suggestions
    3. Select www.bugatti.com from suggested items, searches instead of opening the site
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#8824 
cc: @bbondy

**Comment by diracdeltas** [comment]
what was the behavior in previous releases?

**Comment by diracdeltas** [comment]
so in 0.15.2, `http://www.bugatti.com` doesn't show up in the results at all. however, if you type `http` and click on the `http://yahoo.com` result, it does search instead of going to the FQDN. so i'm not sure this behavior is a bug.

**Comment by luixxiul** [comment]
Is this the issue which is discussed?

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26606895/c4e0847e-45ce-11e7-92fb-674d1b77248c.jpg)

Hitting <kbd>Enter</kbd> then returns a search result on Google instead of opening it directly.

**Comment by diracdeltas** [comment]
@luixxiul i clicked instead of hitting enter but yeah i think it is the issue. the same thing happened in 0.15.2 if you selected an entry starting with 'http'

**Comment by diracdeltas** [comment]
it seems the underlying issue is that 'http...' entries should not be showing up in search results all the time, since it is pretty rare that they are common search terms.

**Comment by diracdeltas** [comment]
confirmed that the 'http' results were being filtered out in 0.15.2. that seems to be the actual regression here.
