### ISSUE TITLE
Brave Browser doesn't block trackers/ads on brave.com that Ublock Origin blocks

### ISSUE THREAD

**Issue by hook54321a** [brave/browser-laptop#9142]
![screenshot_2017-05-30_09-42-22](https://cloud.githubusercontent.com/assets/7744057/26594475/9d18963c-451c-11e7-9613-b96cc8be3274.png)
![screenshot_2017-05-30_09-41-05](https://cloud.githubusercontent.com/assets/7744057/26594481/a4e7b1fe-451c-11e7-88ce-15ef163ad936.png)

**Comment by bridiver** [comment]
There are no ads/trackers on brave.com so I'm not sure what ublock is blocking. We use a self-hosted website analytics tool called piwik, but all cookies are in the brave.com domain and cannot be used for cross-site tracking

**Comment by hook54321a** [comment]
Just checked, does the same thing on mozilla.org

**Comment by bridiver** [comment]
I can't speak for mozilla.org as we are not affiliated with them, but there are no 3rd-party trackers on brave.com afaik. Does ublock tell you what exactly it blocked?

**Comment by hook54321a** [comment]
Yeah, you were correct. Couldn't web analytics also be used for tracking though?

![screenshot_2017-05-30_11-20-33](https://cloud.githubusercontent.com/assets/7744057/26601632/70fcdaea-4535-11e7-997c-5e9c236319cd.png)

**Comment by bridiver** [comment]
Absolutely if you use a 3rd-party service like Google Analytics, but our web analytics only uses first-party cookies in the brave.com domain.

**Comment by bridiver** [comment]
we don't have any special exceptions for brave.com and as a general rule we don't block first-party traffic (with some exceptions like when first-party domains are used to display 3rd-party ads) so I'm going to close this as won't fix, but feel free to ask questions. Thanks!

**Comment by the-c0d3r** [comment]
![screenshot 2018-09-25 at 6 30 12 pm](https://user-images.githubusercontent.com/4526565/46009099-119db680-c0f1-11e8-87c4-6dcc930034e5.png)

I just downloaded the latest version just now, installed brave. Not sure if it's related to this issue. Just an FYI.
