### ISSUE TITLE
Autoplay notification should be dismissed if user ignores notification and continues stream

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9143]
## Test plan
1. Set Auto play to `Always Ask`
2. Visit http://vimeo.com and play a video, notification bar should be shown
3. Click on play button to continue media stream
4. Autoplay notification bar is dismissed

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Autoplay notification should be dismissed if user ignores and choose to play 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.0
rev	be76cd3
Muon	3.2.101

- Steps to reproduce:
    1. Set Auto play to `Always Ask`
    2. Visit http://vimeo.com and play a video, notification bar should be shown
    3. Click on play button to continue media stream, autoplay notification bar is not dismissed
    
- Actual result:
Autoplay notification is not dismissed when user ignores and clicks play

- Expected result:
Should dismiss notification bar for that video stream when user ignores it

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by kjozwiak** [comment]
Clearing flags as this was tested against `0.20.x`, needs to be re-tested against `0.19.x`.

**Comment by srirambv** [comment]
Verified on 0.19.126. Clicking play though notification works and video playback starts.
