### ISSUE TITLE
Production release should ignore NODE_ENV environment variable

### ISSUE THREAD

**Issue by johanalkstal** [brave/browser-laptop#915]
Having just downloaded the Win 64 installer and finished installing, this is what I'm greeted with.

![brave_install](https://cloud.githubusercontent.com/assets/1790333/13323245/cfb59a3a-dbd8-11e5-8b99-de0681d4aebb.JPG)

**Comment by bbondy** [comment]
where did you download from?

**Comment by johanalkstal** [comment]
I tried both from the in-mail link and from brave.com front page link.

**Comment by bbondy** [comment]
have you ever had the development version installed?

**Comment by johanalkstal** [comment]
No first time installing Brave on Windows.

**Comment by bbondy** [comment]
Do you have NOD_ENV set globally as an environment variable?

**Comment by johanalkstal** [comment]
That I do.

**Comment by bbondy** [comment]
bingo! OK we should change this, thanks for the post.  For now you can set it not globally only on your project that needs it.

**Comment by johanalkstal** [comment]
Indeed. I think that is good advice overall. :)

**Comment by bbondy** [comment]
haven't had time to do this yet, moving to 0.8.1

**Comment by luixxiul** [comment]
Does we need to work on this at all?

**Comment by bbondy** [comment]
yes we should still fix, I haven't heard of more people affected yet though so not the highest priority.

**Comment by bsclifton** [comment]
Reworded issue-
Our production builds should not be considering the NODE_ENV environment variable

**Comment by jonathansampson** [comment]
@bbondy @bsclifton I just got off a call with a user who ran into this; removing the `node_env` value resolved the issue for them.

**Comment by bsclifton** [comment]
@jonathansampson this could be a tricky one to solve properly... I think it's safe to say this wouldn't affect most users. Maybe we could describe the symptoms and share the fix on community.brave.com?

**Comment by jonathansampson** [comment]
@bsclifton Yeah, I suspect this is only going to impact developers (unless some software sets the same environment variable). One developer with whom I spoke wasn't familiar with env-variables, and still had this one set (which makes me wonder if some software may have set it).

**Comment by NejcZdovc** [comment]
@jonathansampson @bsclifton because this behaviour is meant for developers only, we can detect if you set it and display notification on lunch with steps how to remove it. wdyt?

**Comment by bsclifton** [comment]
I think if a contributor wanted to grab this, we can help them come up with messaging... but I think it's fairly low priority. Definitely won't be a problem with Brave Core

**Comment by bsclifton** [comment]
This will no longer be an issue once we move to [brave-core](https://github.com/brave/brave-browser)
