### ISSUE TITLE
LastPass dialog moves after changing window size

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9153]
**Describe the issue you encountered:** LastPass dialog moves after changing window size. 

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Decrease the height of the browser so small for the LastPass dialog to overflow the window
    2. Enable LastPass
    4. Display LastPass widget
    3. Change the window's height 

- Actual result:

  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26609718/af90e23a-45dd-11e7-9090-8ee3cac6d429.gif)

- Expected result: the dialog should appear under the icon and not move

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul does this happen on macOS? I'm seeing a different issue when I'm just trying to enable on mac (which prevents me from trying to repro)

**Comment by luixxiul** [comment]
@bsclifton I think my previous STR was not right one. would you mind retry again? thanks!
