### ISSUE TITLE
Pocket icon should change its color based on status

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9157]
**Describe the issue you encountered:** https://github.com/brave/browser-laptop/issues/7357#issuecomment-304601039
> since other icons around the pocket one change color based on status. LastPass changes the color into yellow when the extension has a warning notification. Shield button changes its color too.
>
> <img width="90" alt="screenshot 2017-05-29 17 14 26" src="https://cloud.githubusercontent.com/assets/3362943/26541847/6ee43210-4492-11e7-9033-14d121eebc87.png"> <img width="91" alt="screenshot 2017-05-29 17 14 48" src="https://cloud.githubusercontent.com/assets/3362943/26541848/6f05286c-4492-11e7-8253-b43c8fe75546.png">

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Enable Pocket
    2. Click the icon to save the page
    
- Actual result: the color does not change.

- Expected result: the icon color should change like other icons do.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
We're just displaying what the extension it telling us to- I don't think there's anything we can do (other than to ask the maintainers for the Pocket extension).  @jonathansampson can you confirm?

**Comment by luixxiul** [comment]
lately you get the red icon on macOS:

<img width="101" alt="screenshot 2017-06-19 19 16 50" src="https://user-images.githubusercontent.com/3362943/27280742-069cbc7a-5524-11e7-92a6-3126929aef3b.png">
