### ISSUE TITLE
fa un/lock icon is not displayed for PDF file

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9162]
**Describe the issue you encountered:** fa un/lock icon is not displayed for PDF file.

- Brave Version (revision SHA): 0.15.310

- Steps to reproduce:
    1. Open http://www.orimi.com/pdf-test.pdf
    
- Actual result:

  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26615438/c2f641fc-4601-11e7-9f21-837b0b574869.jpg)

- Expected result: It should display fa-unlock icon

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9172

**Comment by luixxiul** [comment]
The issue seem to happen only on that file. I tried other files and couldn't reproduce the issue.

**Comment by luixxiul** [comment]
OK I think I found a consistent STR:

1. Open http://www.orimi.com/pdf-test.pdf
2. Set focus to the URL bar to select the URL
3. Clear the focus from the URL bar

**Comment by srirambv** [comment]
Regression of #5774

**Comment by luixxiul** [comment]
It seems this has been fixed until c5968c5.

**Comment by NejcZdovc** [comment]
Just tried on master branch (ddc30fda6fd4596d48f63d154f4dee10014f55d0) is working correctly for me on macOS.

![image](https://user-images.githubusercontent.com/9574457/27280811-985e7094-54e9-11e7-8ff0-7dc98252eb43.png)

**Comment by luixxiul** [comment]
It's not working yet on 0.17.3

**Comment by NejcZdovc** [comment]
is it working for you on 0.19?

**Comment by luixxiul** [comment]
@NejcZdovc yes it does.
