### ISSUE TITLE
Tab is not selectable, tear off said tab is blank.

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9165]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When having multiple tabs open, it is discovered that at times one of the tabs is overable, but not selectable. When that tab is torn off, it is blank.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Discovered on OS X

- Brave Version (revision SHA):
0.15.311

- Steps to reproduce:
    1. Open a couple tabs
    2. Try to tear off the inactive tab
    
- Actual result:
Tab in new window is blank

- Expected result:
Tab should have content

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
This appears to have been mended.

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/browser-laptop/pull/9182. Please re-test / reopen if still an issue

**Comment by srirambv** [comment]
I still see an intermittent issue on a clean profile where in I cant switch to a tab which was dragged out and reattached. Everytime I record it doesn't happen

**Comment by srirambv** [comment]
Adding Win-32 as I was not able to repro the issue on multiple new profiles.
