### ISSUE TITLE
Browser relaunches itself when closed, after downloading an update

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9169]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser relaunches itself when closed, after downloading an update

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
0.15.310 and all versions before

- Steps to reproduce:
    1. Install a older build of Brave and launch
    2. Wait for the update to be found and downloaded
    3. Click <kbd>Later</kbd> in the notification bar
    4. Close the browser window, browser updates and relaunches immediately
    
- Actual result:
Browser closes and restart even after selecting <kbd>Later</kbd> in the update notification bar

- Expected result:
Should only restart the browser if the user clicks <kbd>Update</kbd>. If user clicks <kbd>Later</kbd> and closes the window, browser should remain closed and update in the next launch

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![updaterelaunch](https://cloud.githubusercontent.com/assets/17010094/26621462/cbd4bf24-45de-11e7-84e9-f4f9d8e8ad32.gif)

- Any related issues:
cc: @bbondy @bsclifton

**Comment by luixxiul** [comment]
@srirambv is this still reproduced?

**Comment by srirambv** [comment]
This is still reproducible on the latest stable release. Also reports from community for macOS
https://community.brave.com/t/mac-os-x-upgrade-is-never-deferrable-quit-and-later-do-not-work/10042

**Comment by srirambv** [comment]
+1 from @Jimmar  via #14803

**Comment by bsclifton** [comment]
This shouldn't happen anymore with brave-core
