### ISSUE TITLE
Notification bar - buttons not responding

### ISSUE THREAD

**Issue by Swader** [brave/browser-laptop#9171]
## Test plan
1. Turn on autoplay to `always ask` and make sure there is no any allow
autoplay permissions (Preferences > Security tab)
2. Go to https://youtu.be/g_6yBZKj-eo and don't click on notification
bar
3. Open another tab and go to
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_autoplay
and still don't click on notification bar
4. Go back the youtube tab you will find out the notification bar is now
clickable (before fix, it was non clickable)
5. Go to the w3schools tab and it will also be clickable (before fix, it was non clickable)

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
On some pages / popups, clicks don't work:

- The autoplay permission bar on messenger.com didn't register my clicks, but started working after a browser restart. On other sites it worked. 

![brave](https://cloud.githubusercontent.com/assets/1430603/26626562/e63d3d82-45f7-11e7-90ac-298b04740ac8.gif)

- I've noticed clicks stop working from time to time on various pages and windows, in particular in popups: when developer tools are opened, right click doesn't work. On popups opened by OAuth pages, for example, the lastpass popup for selecting accounts with which to populate fields won't be able to spawn.

- Platform (Win7, 8, 10? macOS? Linux distro?):

OS X

- Brave Version (revision SHA):

6b5e4e2d300959848e0e848817aa40385447f2eb

- Steps to reproduce:
    1. Use Brave
    2. Trigger autoplay question on as many sites as possible
    3. Click any of the buttons
    
- Actual result:
Eventually, the click will no longer register

- Expected result:
Clicks shouldn't be a luxury or a lottery and should register every time.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not sure, doubt it. I think it has to stay open for a while to accumulate the typical NodeJS memleak lake.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
No

- Any related issues:
Possibly, I've been told there have been reports of non working context menus and clicks, but cannot find them.

**Comment by bsclifton** [comment]
@darkdh @bradleyrichter didn't one of you have this issue recently?

**Comment by darkdh** [comment]
dup https://github.com/brave/browser-laptop/issues/9780

**Comment by darkdh** [comment]
Specific STR:
1. Turn on autoplay to `always ask` and make sure there is no any allow autoplay permissions
2. Go to https://youtu.be/g_6yBZKj-eo and don't click on notification bar
3. Open another tab and go to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_autoplay and still don't click on notification bar
4. Go back the youtube tab you will find out the notification bar is non clickable
5. Go to the w3schools tab and it will also be non clickable

**Comment by kjozwiak** [comment]
Clearing flags as this was tested against `0.20.x`, needs to be re-tested against `0.19.x`.

**Comment by srirambv** [comment]
Verified on 0.19.126 build. Test plan works
