### ISSUE TITLE
Able to view certificate even after the URL is removed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9172]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Able to view certificate even after the URL is removed

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.312
rev	cc653ff
Muon	3.0.202

- Steps to reproduce:
    1. Visit any site in a new tab
    2. Click and press Ctrl+X to cut the URL
    3. Click on the magnififer icon, shows the connection info modal and still able to view the certificate
    
- Actual result:
Able to view certificate even after the URL is removed

- Expected result:
Once URL is removed connection info modal should not be shown when clicked on the magnifier glass

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
~~Not verified but should be an existing bug~~ 
Verified existing issue on stable release build

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![connection info](https://cloud.githubusercontent.com/assets/17010094/26628792/5e022acc-45f7-11e7-8f2f-ae9734dc72a9.gif)

- Any related issues:
cc: @bbondy  @diracdeltas

**Comment by bsclifton** [comment]
Good catch- this is not possible in Chrome
