### ISSUE TITLE
Sync input fields should have focus when clicked

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9175]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sync input fields should have focus when enabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.312
rev	cc653ff
Muon	3.0.202

- Steps to reproduce:
    1. Open about:preferences#sync
    2. Click on `I am new to Sync` or `I have an existing Sync code`
    3. Focus is not on the input field, user has to click and then start typing 
    
- Actual result:
Sync input fields should have focus when clicked

- Expected result:
Behavior should be similar to autofill modal. Focus should be set on the first input field when clicked

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#8280 
cc: @kumarrishav

**Comment by lzmartinico** [comment]
I will take this bug as my first contribution to Brave!

**Comment by luixxiul** [comment]
@lzmartinico thanks! If you have finished the work on your PR, would you mind tagging a reviewer, following the instruction available here? https://github.com/brave/browser-laptop/wiki/Pull-request-process

**Comment by lzmartinico** [comment]
@luixxiul Thanks for tagging some reviewers yourself, I don't think I had the right permission

**Comment by luixxiul** [comment]
> I don't think I had the right permission

CC @diracdeltas for investigation.
