### ISSUE TITLE
Can't close pinned tabs

### ISSUE THREAD

**Issue by muhang** [brave/browser-laptop#918]
This may be by design, pinned tabs can't be closed. I could see it making sense, since it may be annoying to accidentally ⌘-w and close something that's pinned. Using that shortcut cycles through to the next pinned tab, though, which seems odd (possibly separate issue). Only tested on OSX.

**Comment by bbondy** [comment]
This is intentional, I don't think we want pinned tabs closable. You can right click to unpin though.  One option would be to prompt the user if would like to close

**Comment by bradleyrichter** [comment]
Chrome and FX include pins in the control+Tab cycle, as well as in the Command+n number sequence. 

Chrome Closes Pins with Command+W. FX does not. Let's try to be best, but err on the side of familiarity. 

@muhang Are you finding a Brave bug? We do have a bug open somewhere regarding a pin getting selected when you close the last tab in a set. Perhaps there is a relation.

**Comment by diracdeltas** [comment]
Pins are included in the tab shortcut cycle and number sequence but it's buggy (see #968). `cmd+w` cycling to the next tab seems like it might be a bug though. i would expect nothing to happen on a pinned tab.

**Comment by muhang** [comment]
That issue seems like it could be related, since both that and the `cmd+w` thing I'm seeing involve cycling through tabs. I just tested on Arch Linux and `ctrl+w` still cycles through pinned tabs (until it goes through all of them, after which it closes the browser), so it may not be OS specific. I'd be happy to take a crack at fixing this bug if that's alright?

**Comment by luixxiul** [comment]
Closing for now. Regarding cycling through pinned tab, #1563.
