### ISSUE TITLE
create a custom eslint rule for styles

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9181]
it would be great if we have a kind of standardjs for styles. More info pls follow convo here: https://github.com/brave/browser-laptop/pull/9177#issuecomment-305298515

ESLint has an extensive documentation and we can make use of a tool like http://astexplorer.net/. Our own rules for styles are defined in style.md document.

Labeling as backlog for now until we have more time to take this. Self-assigning for tracking purposes feel free to take if you want to do it as well.

**Comment by luixxiul** [comment]
It would be very helpful to integrate a tool like [CSScomb](https://github.com/csscomb/csscomb.js) to force the style format (a plug-in for an IDE such as Sublime Text to combine CSScomb with Aphrodite would work as well).

By enabling this, it would make the code look consistent. Also it would be easy for us to search and replace code with regex.
