### ISSUE TITLE
Sometimes a website is completely unresponsive

### ISSUE THREAD

**Issue by rasnauf** [brave/browser-laptop#919]
As the title says. I do not know what initiates this bug, but it has happened to me multiple times. I do not know how this affects multimedia output. When this error occurs, I am not able to select text, execute a hyperlink, or interact with the website in any way. Also, this seems not to affect other tabs, and it is still possible to switch to other tabs. Closing the tab and opening it again by hitting Ctrl-Shift-T fixes the error for an indefinite period of time. This error is not specific to any one website.

**Comment by bbondy** [comment]
I need more info on this, hopefully someone else can reproduce as well.  You mentioned it's not specific to any one site but maybe it is more common for some specific sites.

**Comment by luixxiul** [comment]
Closing for now. Please mention URL to reopen this issue, thanks.
