### ISSUE TITLE
View certificate option not shown on all insecure connections

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9194]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
View certificate option not shown on all insecure connections

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.15.314
rev	75ffa36
Muon	3.0.202

- Steps to reproduce:
    1. Visit https://mixed-scripts.badssl.com
    2. Click on connection info button and click on `Load unsafe scripts`, ensure page shows red
    3. Click on connection info, shows `View certificate` option
    4. Open http://cnn.com
    5. Click on connection info, no option for `View Certificate` is shown, only connection information is displayed
    
- Actual result:
View certificate option not shown on all insecure connections

- Expected result:
Should show view certificate option for all insecure conections

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![insecure connection](https://cloud.githubusercontent.com/assets/17010094/26678764/ee7b18a2-46c9-11e7-9e93-7adf7b572dea.gif)

- Any related issues:
#8530
cc: @diracdeltas @darkdh

**Comment by darkdh** [comment]
http protocol doesn't have any certificates
