### ISSUE TITLE
Add option to use a blank page as home page

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9198]
From community: https://community.brave.com/t/option-for-new-tab-opening-as-blank/3309
Please add an option to control what content appears when creating a new tab. I'd like to be able to choose between the Brave web page, a BLANK web page or a web page that I choose.

**Comment by lzmartinico** [comment]
I believe this was solved in #5690

**Comment by luixxiul** [comment]
On about:preferences#general you have those options already:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26752302/cacd05cc-4887-11e7-8932-d86723426a08.jpg)
