### ISSUE TITLE
Add support for Flow type-checker

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9202]
From [their website](https://flow.org/):

> Tired of having to run your code to find bugs? Flow identifies problems as you code. Stop wasting your time guessing and checking.

looks good to add support since we already include it in our package.json

**Comment by diracdeltas** [comment]
we used to use it. a few files may still be flow-typed. see https://github.com/brave/browser-laptop/pull/1350.

**Comment by cezaraugusto** [comment]
seems like a heavy task to cover our code 100% but I often see bugs that would be prevented by just type-checking so it is worth doing. 

thanks for the link and feel free to take this one as well. As things get done this is likely to become a tracking issue rather than a proposal.

**Comment by luixxiul** [comment]
So the document [here](https://github.com/brave/browser-laptop/blame/c3c00c314c9c02df71b5426078c3ffc4d73c9739/.github/CONTRIBUTING.md#L26) on CONTRIBUTING.md is updated or needs being commented out?

**Comment by diracdeltas** [comment]
@luixxiul i believe that comment is still relevant since any flow-typed files should not regress

**Comment by bsclifton** [comment]
Brave Core (brave-core, brave-extension, etc) are using typescript, which should do the job 😄👍
