### ISSUE TITLE
Automatically skip advertisement links

### ISSUE THREAD

**Issue by TrademarkTM** [brave/browser-laptop#9204]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
This is not an issue, but a suggestion.

**Platform (Win7, 8, 10? macOS? Linux distro?):**
Windows 10.

**Actual result:**
Advertisement links like adf.ly or adfoc.us have their adds hidden, but you still have to wait 5 seconds to be redirected and click the link.

**Expected result:**
As you won't see any ads, there's no point on waiting 5 seconds. It'd be nice to have a feature to automatically skip these links and redirect you instantly to the page you want to visit.

Example Chrome extension: http://safebrowse.co/

**Why?**
Browsing will be much smoother without having to wait every time you are redirected to these links.

Thanks!

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/automatically-skip-advertisement-links/10733

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
