### ISSUE TITLE
Building brave fails on "npm install" with "Package gnome-keyring-1 was not found in the pkg-config search path"

### ISSUE THREAD

**Issue by atomopawn** [brave/browser-laptop#9205]
I am experiencing an error almost identical to issue #1172 (which was closed as fixed), but with the latest git master and during an initial install.  Sorry if opening a new report is the wrong approach here.

When building Brave (for the first time) I experience the following error when running "npm install":

> keytar@3.0.2 install /home/robert/browser-laptop/node_modules/keytar
> node-gyp rebuild

Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gnome-keyring-1', required by 'world', not found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.4.0-78-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/robert/browser-laptop/node_modules/keytar
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I am using Linux Mint 18 Sarah and am trying to build brave from the latest "browser-laptop" trunk.

- Steps to reproduce:
    1. Install nodejs v8 from the NodeSource repository (would v6 be better?)
    2. Install node-gyp (I initially installed using apt, then using the npm command from the README)
    3. Install libgnome-keyring-dev, build-essential, rpm and ninja-build using apt.
    4.  In the "browser-lapop" directory, run "npm install".   
    
- Actual result:

Brave fails to build with errors.

- Expected result:

Brave builds successfully.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

I have tried removing node_modules and running "npm install" again.  It fails at the same place.  I have also tried:

sudo npm config set python /usr/bin/python2 -g

which was suggested in a bug report for atom (https://github.com/atom/node-keytar/issues/18) which seemed similar.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

**Comment by kartojal** [comment]
Installing the dependencies fixed that issue, but i found another error, doing `npm start`.

To install the missing depedency and fix the build error in a Debian/Ubuntu system:
`sudo apt-get install libgnome-keyring-de`

Error when doing `npm start`, maybe i should open another issue.

```
user@dev:~/Repos/browser-laptop$ npm start

> brave@0.15.312 start /home/user/Repos/browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/user/Repos/browser-laptop/node_modules/electron-prebuilt/path.txt'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/home/user/Repos/browser-laptop/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
process exited with code 1
```

**Comment by luixxiul** [comment]
not sure how critical this issue is so I added needs-triage label at the same time. thanks.

**Comment by atomopawn** [comment]
I have all the dependencies installed, including libgnome-keyring-dev, but npm install still fails with the same error.

**Comment by atomopawn** [comment]
I'll note that installation worked fine on my Fedora 25 system.  Let me try installing node v6 instead of node v8 on the Mint box and see if that makes a difference.

**Comment by NejcZdovc** [comment]
@luixxiul removed this from 0.16.x because this is related to development and 0.16 and 0.17 are in freeze already.

**Comment by atomopawn** [comment]
Thanks!

**Comment by atomopawn** [comment]
Even with node v6, building fails on my Mint system.  After installing v6, removing node_modules, and rebuilding, it fails with pretty much the same error:

npm ERR! Failed at the keytar@3.0.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robert/browser-laptop/npm-debug.log

I've posted the log file on my [web server.](http://marmorstein.org/~robert/npm-debug.log) 

Looks like maybe this is an upstream issue?

**Comment by atomopawn** [comment]
So in Mint, /usr/lib/x86_64-linux-gnu/pkgconfig is not in the default PKG_CONFIG_PATH, which causes this behavior.  Adding it with export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig before building fixes the issue.  I've opened a report upstream asking that the default path be changed, but this report can be marked closed.
