### ISSUE TITLE
After update, only one window restored (had 2 open windows)

### ISSUE THREAD

**Issue by pkoleary** [brave/browser-laptop#9210]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Had 2 browser windows open. Updated Brave and only one window was restored.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS Sierra

- Brave Version (revision SHA):
updated to 0.15.314

Tried 'Reopen Last Closed Window'.

Preferences are set to: brave starts with my windows/tabs from last time

Thank you in advance for any assistance.

**Comment by bsclifton** [comment]
@pkoleary we had some issues where windows were being lost (while restoring) because of a spell check bug which we fixed in the 0.16.x series. I'm going to mark this issue as closed, but please re-open if you experience the issue again (and apologies that it happened in the first place)
