### ISSUE TITLE
Improve tab tear-off sensitivity

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9211]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Users in community are reporting that the vertical sensitivity is too tight which is causing accidental tear-offs when they aren't wanted.
https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/22

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.15.314 

- Steps to reproduce:
    1. attempt to close or move tabs rapidly
    
- Actual result:
For some folks, a new window is created because of a small vertical movement

- Expected result:
The tab should either move or close as desired by the user.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues:
https://github.com/brave/browser-laptop/issues/8174
https://github.com/brave/browser-laptop/issues/6242

**Comment by srirambv** [comment]
+1 from community https://github.com/brave/browser-laptop/issues/9211

**Comment by LaurenWags** [comment]
+1 community https://community.brave.com/t/help-me-it-is-so-annoying-deal-about-tab-deal/4748

**Comment by Liunkae** [comment]
+1 from #9992

**Comment by bsclifton** [comment]
related: improve tab drag and drop: https://github.com/brave/browser-laptop/issues/6242

**Comment by Liunkae** [comment]
I think this should be reopened since it's a sub-task of #6242.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/brave-is-too-sensitive-to-moving-tabs-into-new-windows/4875)

**Comment by bsclifton** [comment]
+1 via https://github.com/brave/browser-laptop/issues/10007

Here's an animation showing the problem. The user is trying to drag a tab into a bookmark folder. It shouldn't be creating a new window
![brave-drag-tab-to-folder-bug](https://user-images.githubusercontent.com/25360853/28251474-e61079e4-6aa7-11e7-884a-c7ad2904c457.gif)

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/browser-tabs-open-up-in-a-new-window-far-too-easily/5850

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/randomly-opening-new-instance-of-brave-just-for-clicking-on-tab/6644?u=eljuno)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/clicking-on-a-tab-gets-registered-as-a-click-drag/7599?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/tabs-too-sensitive-to-dragging/7959?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/tabs-getting-dragged-when-switching-tabs-with-mouse-clicks-also-alt-d-opens-up-the-menu-after-going-to-the-address-bar/8151?u=eljuno

> when I am switching tabs with mouse clicks, it somehow undocks/drags itself out of the tabs area (try switching tabs with mouse clicks you might replicate the problem)

**Comment by spidawebs** [comment]
Is there any update on this? My tabs detach far too easily. They accidentally open in new windows about 10 times I day when I click on them and there is no way to attach them again to the original window. It's really annoying. I have to close the new window and open a new tab again in my original window.

**Comment by gnarlyman** [comment]
+1

**Comment by UppaJung** [comment]
Shocked this bug has been sitting unfixed for half a year.  I also run into this constantly.  Perhaps it's a pixel-based threshold and those not using 4k monitors don't feel the pain of this constantly?

**Comment by spidawebs** [comment]
Me too. I've had to stop using it and go back to Opera as it was driving me crazy.

**Comment by TheMilesLong** [comment]
This bug is really difficult from a user's productivity viewpoint.

Every time I try to click into a different open tab, it creates a new window... Then the new window jumps to the bottom right of my display, locating more than half the window out of the view of my monitor.

I really want to get behind Brave and share it with my audience, but this bug is just too frustrating, still.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/too-sensitive-to-dragging-tabs/18647?u=eljuno

> Every tab repeatedly gets detached into a new window when I try to click on it but unintentionally drag it because my hand wasn’t perfectly still.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/accidental-dragging-of-tabs-too-easy/19227?u=eljuno

**Comment by laradevitt** [comment]
I don't have particularly shaky hands or anything, but this happened to me three times in the last half hour. Not a deal breaker, but annoying sometimes.

**Comment by bsclifton** [comment]
Marking as `wontfix` since we'll get this for free with Brave Core

**Comment by bryanne99** [comment]
OMG - I tried Brave again a WHOLE year later!!! - just to see if the "tab tear-off issue has been fixed. Incredibly it hasn't. I will not waste my time trying to use itr again. I guess there's a reason why Chrome works - and that is because they just know how to make things work - as much as I would prefer NOT to use Google. This tabs issue is so incredibly frustrating that I just cannot use a browser that does that ...and no one seems to care???

**Comment by bsclifton** [comment]
@bryanne99 we do care- enough that we're working on a replacement UI for what we have (based entirely on Chromium, versus what we have now which uses Muon, a fork of Electron). You can read more about it here:
https://brave.com/development-plans-for-upcoming-release/

Or you can check out / build the code yourself (we don't have any official releases yet):
https://github.com/brave/brave-browser

Besides having proper tear-off behavior, it has full extension support. If you're still willing to give us a shot, please check back in a few months

**Comment by sredenz** [comment]
I just signed up to GitHub to +1 for this request to change the sensitivity of undocking tabs (or give us an option to simply switch it off).

**Comment by jbcullis** [comment]
Yep, this one is pretty frustrating. I'm happy asides from this issue.
