### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by louisvillasan** [brave/browser-laptop#9213]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
The page charge but only show a page white
ubuntu 16.04
- Steps to reproduce:
    1. Open some video on youtube
    2.Open other video on youtube (When you do this the error appears)
    3.And if you try to open any page the page doesn't show the content
    
- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? it's the third time and i just install hour ago

**Comment by louisvillasan** [comment]
And the browser must start with the last tabs open, i change to start with a new tab and i don't have the problem anymore

**Comment by luixxiul** [comment]
@louisvillasan if you could attatch screenshot (GIF image with [LICECap](http://www.cockos.com/licecap/)) that would make it easy to troubleshoot. thanks!

**Comment by bsclifton** [comment]
@louisvillasan can you please try the steps captured here? Thanks 😄 
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

**Comment by louisvillasan** [comment]
The problem is gone thanks bsclifton, and before that i made a video, luxxiul, in this link you can watch the problem that i had   
https://drive.google.com/open?id=0BwhynCSkAO77QlplRm5pOGt6bTA

PD BRAVE IS ASOME

**Comment by bsclifton** [comment]
awesome, thanks for the update @louisvillasan!! 😄 👍
