### ISSUE TITLE
button style inconsistency on about:preferences (button normalization)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9223]
**Describe the issue you encountered:** the button style on `about:preferences#sync` is different with that on the other tabs of `about:preferences` such as `about:preferences#payments` 

<img width="260" alt="screenshot 2017-06-03 14 17 26" src="https://cloud.githubusercontent.com/assets/3362943/26750885/736a34d2-4867-11e7-9bf4-25e0903c9d7d.png"> <img width="299" alt="screenshot 2017-06-03 14 17 34" src="https://cloud.githubusercontent.com/assets/3362943/26750884/7367a88e-4867-11e7-9591-52d1fb8c07c3.png">

The button on the left looks thinner and the font-size looks smaller than the button on the right.

See: https://github.com/brave/browser-laptop/blob/548e11b1c889332fadb379237555625ad2a3c845/less/button.less#L160

Also the styles of buttons on browser's UI such as bookmark hanger dialog is different with them.

<img width="320" alt="screenshot 2017-06-03 14 19 24" src="https://cloud.githubusercontent.com/assets/3362943/26750895/b5c6a46e-4867-11e7-875c-d797b4279ec4.png">

See: https://github.com/brave/browser-laptop/blob/734cefcc993fdd73c7b8266d90a8dd7aba9fbcdf/less/window.less#L9

You would see the different font-family is specified to each of them.

We are on the way of normalizing the buttons by converting `buttton` component with `browserButton` component. We would have to investigate which `font-size`, `font-family`, and `line-height` (the properties which can/must be specified with `font` property) should be applied as to `browserButton` inside `browserButton.js`.

- Brave Version (revision SHA): 0.15.314

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
Another thing we have to decide: should we revert `font-size` and `padding` of the buttons on about:preferences#sync same as it has been, by creating `preferenceItem` and apply [these](https://github.com/brave/browser-laptop/blob/548e11b1c889332fadb379237555625ad2a3c845/less/button.less#L162-L163) to it? 

That would make the size of the buttons on about:preferences#sync same as the other buttons on other preference tabs.

@cezaraugusto I noticed that [font-weight: 500](https://github.com/brave/browser-laptop/blob/548e11b1c889332fadb379237555625ad2a3c845/less/button.less#L115) has not been specified to `browserButton_primaryColor`. I'm going to add it to make the font-weight like this:

<img width="270" alt="screenshot 2017-06-03 14 50 04" src="https://cloud.githubusercontent.com/assets/3362943/26751067/f28e26b6-486b-11e7-8a69-0621fc6aa234.png">

The reason why "Done" button on bookmark hanger looks bold is due to font-family; the font-family specified for the button is itself bolder than the font-family for the buttons on preferences, so the effect is not intentional but coincidental.

<img width="320" alt="screenshot 2017-06-03 14 19 24" src="https://cloud.githubusercontent.com/assets/3362943/26750895/b5c6a46e-4867-11e7-875c-d797b4279ec4.png">

**Comment by cezaraugusto** [comment]
cc @bradleyrichter

**Comment by bradleyrichter** [comment]
we need to get them all referencing the same style definition so we can easily refine it collectively. I want to flatten them out a bit and reduce the shadows.

So in this case, sync is "out of sync".  :   )

**Comment by luixxiul** [comment]
After https://github.com/brave/browser-laptop/pull/10951 is merged and `<Button>` is replaced with `<BrowserButton>`, let's try to set the font-family to `<BrowserButton>` and see if it will make the buttons look consistent on about pages and browser level dialog.

https://github.com/brave/browser-laptop/blob/734cefcc993fdd73c7b8266d90a8dd7aba9fbcdf/less/window.less#L9

**Comment by luixxiul** [comment]
The cause of the difference is that, while on about pages `-webkit-font-smoothing: antialiased` is set with common.less, on the commonForm it is not. With the commit above I reset the value and that should make the buttons look consistent.
