### ISSUE TITLE
Make permission and password prompts testable and base page interactive

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#923]
https://github.com/brave/browser-laptop/commit/35efd0ecdcaf98deee1d29c1a319fbbfe04a0c59#commitcomment-16356058

**Comment by diracdeltas** [comment]
Pretty sure this would require the page to be reloaded after the user answers the permission prompt. Not a blocker but may be annoying.

**Comment by bbondy** [comment]
I don't think a reload would be required, at least it shouldn't be.

**Comment by diracdeltas** [comment]
The Electron permission handler API requires the allow/deny callback to be called synchronously (see https://github.com/brave/browser-laptop/blob/master/app/filtering.js#L191). I guess we could wait a fixed amount of time for the user to make a decision and then deny the initial permission request by default if they don't.

**Comment by bbondy** [comment]
> The Electron permission handler API requires the allow/deny callback to be called synchronously

Let's fix that for this bug, (no rush)

**Comment by diracdeltas** [comment]
Also could be useful for https://github.com/atom/electron/blob/777ff450cf4a0722d29bce44c29fe02470952823/docs/api/app.md#event-certificate-error

**Comment by diracdeltas** [comment]
@bbondy did basically this in https://github.com/brave/browser-laptop/commit/bb27ec23021680ecb314e33fa24b7a3dfd8a2d33, so i take back what i said about this issue requiring changes to Electron

**Comment by diracdeltas** [comment]
same thing needs to be done for password save prompts. https://github.com/brave/browser-laptop/pull/1051

**Comment by diracdeltas** [comment]
any thoughts about whether these prompts should be popup windows or a notification bar at the top of the frame?

**Comment by bbondy** [comment]
mainly comes down to if you want to be able to have have a password prompt in one tab and then you can switch tab to a different tab that has a password prompt.  And then you can go back to the first password prompt tab.  My guess is per frame is desirable.

**Comment by bbondy** [comment]
Moving to 0.9.1
