### ISSUE TITLE
Bookmarks are not being created

### ISSUE THREAD

**Issue by joelwallis** [brave/browser-laptop#9231]
**Did you search for similar issues before submitting this one?**

Yep

**Describe the issue you encountered:**

While using the Brave browser, I was unable to add bookmarks by following the most simple flows: accessing a website and adding it as bookmark, as well as going to the bookmark page and adding it directly.

**Platform (Win7, 8, 10? macOS? Linux distro?):**

OS X El Capitan

**Brave Version (revision SHA):**

Installed via Caskroom `brew cask install brave`: https://github.com/brave/browser-laptop/commit/75ffa36130b1ad33c6f311e5e16ed7838b0b50a0

**Steps to reproduce (1):**

1. Browse to any website;
1. Add it as bookmark.

**Steps to reproduce (2):**

1. Go to the Bookmarks section (the one you manage your actual bookmarks);
1. Add any website as bookmark.

**Actual result:**

The bookmark is not created.

**Expected result:**

The correct creation of the bookmark.

**Will the steps above reproduce in a fresh profile? If not what other info can be added?**

I'm not sure what you mean with _fresh profile_.

**Is this an issue in the currently released version?**

Yep. I'm using the latest version.

**Can this issue be consistently reproduced?**

https://youtu.be/j6dmZvqHLuY

**Extra QA steps:**

1. https://youtu.be/j6dmZvqHLuY

**Screenshot if needed:**

https://youtu.be/j6dmZvqHLuY

**Any related issues:**

I couldn't find any related issue (I searched in issue tracker for both open and closed ones).

**Comment by NejcZdovc** [comment]
@joelwallis can you please try again with the latest version 0.17.x? I couldn't reproduce this in 0.17. Thank you

**Comment by joelwallis** [comment]
Hey @NejcZdovc,

I've just downloaded the last update (Brave 0.17.19 - 4e46480) to retry it. Then... https://youtu.be/k60EVNsBCBs

**Comment by NejcZdovc** [comment]
@joelwallis thank you this video, it's strange why it's not working. Can you please open developer tools and check if you see any errors in the console log. You can open it via shortcut shift+F8. Maybe this will tell us more, why it's not working

**Comment by luixxiul** [comment]
it seems that the database is corrupted.

**Comment by joelwallis** [comment]
@NejcZdovc it seems now that Brave does not work at all anymore. I'll try to uninstall it, delete config files, etc., and installing again

**Comment by joelwallis** [comment]
it's working now. seems that something was really corrupted, just like @luixxiul suggested.

btw, which database does Brave use?
