### ISSUE TITLE
Norton antivirus triggers "WS.Reputation.1" quarantine error (false positive)

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#924]
Here will be listed instances when the installer (regardless of OS) trips antivirus detection.

7.16 Installer Virustotal links:
- [Windows](https://www.virustotal.com/en/file/b894af998fcc480cf01b07c43a633a56b73629ec27390696f165f9aa6cb084bf/analysis/) (0/55)
- [OS/X](https://www.virustotal.com/en/file/76c401072c769ea11d8e3673d9089a92bb743f7f8bf432927463f9c46b28d366/analysis/1456506397/) (0/55)

**Comment by VirgilRoussos** [comment]
From support:
**Vendor:** Symantec
**Product:** Norton
**Threat detected:** WS.Reputation.1 [link](http://fr.community.norton.com/en/forums/clarification-wsreputation1-detection)

![image](https://cloud.githubusercontent.com/assets/17283040/13359158/0240ecc2-dcb3-11e5-9274-0274f5e3156b.png)

**Comment by bbondy** [comment]
@VirgilRoussos could you submit a dispute here for this? 
https://submit.symantec.com/false_positive/

**Comment by VirgilRoussos** [comment]
I'm on it. 

Virgil 

On 28 February 2016 18:01:36 CET, "Brian R. Bondy" <notifications@github.com> wrote:
>@VirgilRoussos could you submit a dispute here for this? 
>https://submit.symantec.com/false_positive/
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/brave/browser-laptop/issues/924#issuecomment-189905943

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by VirgilRoussos** [comment]
Response by Symantec:

"We have been unable to reproduce the detection issue described in your submission. Our investigation shows that the software you submitted is known-good and as such does not trigger any detections.

A possible reason for this could be that the status of your software changed automatically between the time of your submission and now.

Please see details of the whitelisted file below:
File name:	BraveSetup.exe
MD5:	0b1c1c66fc5d6cf6ede96dbc24740ee8
SHA256:	b894af998fcc480cf01b07c43a633a56b73629ec27390696f165f9aa6cb084bf

Please note that whitelisting can take up to 24 hours to take effect."

**Comment by bbondy** [comment]
Please try to find out which version the user was using and if it was an old one ask them to try the newest one.  I assume they tried the newest one at Symantec right?

**Comment by VirgilRoussos** [comment]
The user (at my request) was trying with the latest version. Same as the one Symantec did. I'll reconnect with the user for new test.

**Comment by bbondy** [comment]
maybe send them a link to the screenshot as well

**Comment by VirgilRoussos** [comment]
From support: (Ticket 2367)
**Vendor:** McAffee
**Product:** TBD
**Threat detected:** TBD

Will update as soon as have more informations from user.

**Comment by VirgilRoussos** [comment]
From support: (Ticket 2256)
**Vendor:** Kaspersky
**Product:** Endpoint Security
**Threat detected:** TBD

**Comment by bbondy** [comment]
@VirgilRoussos  Great progress on this, did you submit to Qihoo 360, that's the only one I detect we hit very often from https://www.virustotal.com/en/ scans.

**Comment by luixxiul** [comment]
Was this fixed already?

**Comment by luixxiul** [comment]
Not yet: #1490 
> I'm trying to download Brave for Windows, but when download finish my AntiVirus [PSafe Total](http://www.psafe.com/) detect an possible trojan in BraveSetup and I can't execute brave install (only if I disable AntiVirus).

**Comment by luixxiul** [comment]
From support: I can install brave and run the previously installed brave browser only with deactivating my antivirus, Norton Security, up to date

**Comment by myfavoriteemail** [comment]
Im running windows 8.1, I have Norton security up to date, running Chrome to download brave, I saw the downloads folder and brave is there, then I tried to execute it, but Norton tell me that brave is not safe and has been removed.

i had to restore it from norton and then it worked --- the latest brave x64 installer

**Comment by luixxiul** [comment]
From support:
>Detected and intercepted Trojan attacks.
> Program: C:\Users\ACER\AppData\Local\brave\app-0.10.4\resources\BraveDefaults.exe
>
> 360 total security.

**Comment by pedro7** [comment]
>  luixxiul commented an hour ago 
That one is _not_ the installer, it's from the unpacked browser :( VirusTotal:[1 in 53 detection rate](https://www.virustotal.com/en/file/50993f8e819b59f6ecee935fdad656e694c0bea9dcf117478ed05af6d3235d99/analysis/1468513822/)

**Comment by luixxiul** [comment]
From support:
> Every time when there is an update for the brave browser, ZoneAlarm treats the update process as an intruding process and stops it in the middle of installation.

**Comment by bsclifton** [comment]
+1 from my friend:
![image](https://cloud.githubusercontent.com/assets/4733304/19712259/2ee7186c-9af1-11e6-878c-7dfeb1e5742a.png)

**Comment by alexwykoff** [comment]
@diracdeltas could you confirm this can be closed? Thanks!
