### ISSUE TITLE
Feature Request: Allow to collapse/expand bookmark folders

### ISSUE THREAD

**Issue by jansensan** [brave/browser-laptop#9241]
Feature Request: Allow to collapse/expand bookmark folders. In the bookmark manager, it is actually impossible to manage years of bookmarks if it is not possible to collapse/expand folders. An OS-like (Finder/Windows Explorer) or VSCode-like functionality would help greatly.

- Platform: macOS

- Brave Version:
Brave: 0.15.314
rev: 75ffa36
Muon: 3.0.202
libchromiumcontent: 58.0.3029.110
V8: 5.8.283.38
Node.js: 7.9.0
Update Channel: dev
os.platform: darwin
os.release: 14.5.0
os.arch: x64

- Steps to reproduce:
    1. Import a bookmarks *.html file
    2. Go to Bookmarks menu > Bookmarks
    3. See Folders column on the left
    
- Actual result: Impossible to collapse folders

- Expected result: It should be possible to collapse (and expand as well) folders.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Just need to add bookmarks with folders.

- Is this an issue in the currently released version?
Yes, downloaded latest to test

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![image](https://cloud.githubusercontent.com/assets/1410355/26756069/a6a6d278-4868-11e7-8161-13d0f0c3ebe0.png)

**Comment by bsclifton** [comment]
Thanks for the report, @jansensan 😄   We are tracking this with https://github.com/brave/browser-laptop/issues/5077 (which you can subscribe to for updates).  Since we already have it captured, I'll close this issue as a duplicate
