### ISSUE TITLE
Unable to click on anything, appears to happen randomly.

### ISSUE THREAD

**Issue by bensicuch** [brave/browser-laptop#9242]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
I have no idea what causes it, but randomly the browser won't let me click on anything. It doesn't freeze, as any video playing still plays normally, however when I try to click on a tab it won't do anything. It shows the preview, but I can't click on it, nor any other UI element for that matter. I have to go to my taskbar and close it from there.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7

- Brave Version (revision SHA):
0.15.314

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
No.

**Comment by luixxiul** [comment]
would you please provide us steps to reproduce the issue consistently, if you have ones? thanks!

**Comment by GrayEye** [comment]
I am having this same exact issue.

Did you search for similar issues before submitting this one?
Yes

Describe the issue you encountered:
The browser becomes completely unresponsive to mouse and keyboard input. I am unable to close the browser by anything short of ending the task from task manager. However, video and music streaming continues unaffected. 

Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
Brave Version (revision SHA):
Latest circa June 6th 2016

Is this an issue in the currently released version?
Yes

Can this issue be consistently reproduced?
Yes

I have run into the issue while streaming music from soundcloud with notifications turned on. It seems like it will tend to freeze once a new song has started and a notification pops up. It only freezes when a new notification is pushed to me it seems. It does not happen every time a new notification is pushed, but it only seems to happen when one is pushed.

**Comment by bsclifton** [comment]
@GrayEye @bensicuch could you all please try adding `--disable-gpu` to your shortcut when launching Brave, per the documentation at https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page?

I'm curious if this is a driver issue or something similar.  Please let us know 😄

**Comment by GrayEye** [comment]
I tried adding the disable GPU command. It still froze on me. Though I was
streaming music while using the browser, with notifications turned on. It
froze, it seems, when it switched songs automatically and the notification
popped up. Though after letting the program sit for a minute or two it
unfroze. It does this cycle every time a notification pops up, and I let
the notification timeout.

**Comment by RenataBoodram** [comment]
- Did you search for similar issues before submitting this one?
Yes, hence why I am responding to this.

- Describe the issue you encountered:
  - The entire browser becomes almost completely unresponsive.
  - The only clickable elements are the URL bar and the Brave logo to view (but not edit) Site shield settings. 
  - I can type in the URL bar but I cannot use it to navigate to other websites.
  - No tab is "highlighted" to indicate I am viewing it.
  - I can only end the browser session by going to Windows Task Manager
  - I have a 160p Twitch stream running in the background and I'm watching a HD YouTube video when the freezing occurred.
  - Memory usage at the time of the crash was 323.2 MB for Brave, listed under "Apps".

Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

Brave Version (revision SHA):
0.17.13

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
No.

**Comment by kjozwiak** [comment]
@benmosher, @GrayEye, @RenataBoodram does #10436 look like the issue you were experiencing where the entire Brave UI becomes unresponsive?

**Comment by GrayEye** [comment]
No, it doesn't sound similar. The issue I experienced could be reproduced
by enabling browser notifications, then streaming a song from SoundCloud.
Once the first song from the list finishes the browser becomes unresponsive
while the rest of the buffered songs from SoundCloud plays until the buffer
is empty. If left alone for 10-15 min the browser becomes responsive again.

**Comment by RenataBoodram** [comment]
@kjozwiak no, this doesn't sound like the same issue. My Brave browser was not a fresh install or update and ended up bricking after some usage. Based on my earlier comment:
> I have a 160p Twitch stream running in the background and I'm watching a HD YouTube video 

and @GrayEye above comment, it seems like it could be related to streaming? It took some time before I could actually see the entire browser freeze. I did not wait to see if it would unfreeze.

I did still try to reproduce that issue on my browser that was just updated to 0.18.22 (not a fresh install). I only saw the "about:preferences" tab stop working. I could no longer view it or see a tab close button for it but everything else worked fine:

![ezgif-1-a36e8bf819](https://user-images.githubusercontent.com/10997256/29237913-3eeefd9e-7ef6-11e7-8b83-6c9aacaecc38.gif)

**Comment by kenorb** [comment]
Same here. It happens very often on GitHub for me. E.g. I do [search for some issue](https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=freezing) then I can't click anything on the page. Cloning the tab works for another clicks, then freeze again. Once I requested GitHub 2FA, couldn't type in the code. The page is just frozen, despite other tabs are working, like some kind of invisible obstacle is in the front, so the mouse icon doesn't changing into clickable one. Cloning that tabs continue to work.

----

```
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64
```

----
Here are few pics of such tabs:

![img_2957](https://user-images.githubusercontent.com/266306/33072971-4e52a7a0-ceb9-11e7-868c-e741e01e129a.JPG)
![img_2956](https://user-images.githubusercontent.com/266306/33072972-4e66f6ec-ceb9-11e7-910b-a1db54a9413d.JPG)

**Comment by kjozwiak** [comment]
@kenorb, when you run into the above issue, do you happen to see errors in the browser console?

**Comment by Lythimus** [comment]
I have had this issue maybe 7 times. I just restart the browser, but it seems to be happening more frequently. This has also occurred across updates. I generally have roughly 10 tabs open (5 pinned, 5 unpinned) and only 1 browser window. I think this has only happened once while the browser was active. The rest of the time, I switch focus to the browser, and clicking the tabs is simply unresponsive. I'm running the latest version:

```
Brave | 0.20.30
V8 | 6.4.388.40
rev | 8b78402
Muon | 4.7.9
OS Release | 17.4.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119
```

Please resolve. I'll try to pay attention to the cause and share and maybe try to submit a bug report while in a frozen state as well as test out if new windows function, etc.

**Comment by MoMannn** [comment]
I have similar issue. Tab just freezes and you can't close it or open it. It happens really randomly but most common situation in which this happens to me is: 
- Have a few tabs open. 
- Close brave.
- Reopen with tab history.
- Don't click on the tab for a while (so it is unloaded).
- Then you can't open it/close it anymore. 

This is just one situation which I was able to reproduce a few time otherwise it was just random(or no pattern that I could recognize).

Browser info:
 
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by aliddell** [comment]
I'm having a similar issue. Usually seems to happen immediately after I open a new tab (I usually have ~10-15 tabs open at any time, sometimes over multiple windows), but there's no one thing I can point to that triggers it. It's happened 3 or 4 times in the last couple of days.

Browser info (lots in common with the previous guy):

Brave | 0.21.18
V8 | 6.4.388.41
rev | 580be78
Muon | 4.8.2
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Comment by KarmaMonk** [comment]
Same issue here

Browser info:
Brave: 0.21.18 
V8: 6.4.388.41 
rev: 580be782bc37ed8580dd22f79e1d2d355fddfb89 
Muon: 4.8.2 
OS Release: 4.14.0-041400-generic 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Comment by bsclifton** [comment]
For folks encountering this issue:
Can you please try opening the browser developer tools? This should be Shift + F8 (on a macOS laptop, it'll be Fn + Shift + F8).  Once that is up, you can go to the "Console" tab.  There should be an error showing- screenshot that and attach here 😄

**Comment by KarmaMonk** [comment]
![console-error](https://user-images.githubusercontent.com/25179545/37567249-86e552e0-2ac4-11e8-9180-d08896854024.png)

**Comment by KarmaMonk** [comment]
![error](https://user-images.githubusercontent.com/25179545/37570691-40cef2a0-2af3-11e8-98b8-6d37b0b492f8.png)

**Comment by bsclifton** [comment]
+1 from @puzzledbytheweb via https://github.com/brave/browser-laptop/issues/13286
> Every time I use Brave after some time, one or more opened tabs stops responding and when hovered displays a gray background instead of the respective page contents. On top of that it also does not respond when I try to close it by clicking and just stays there for ever until that browser window is closed. 
> ### Steps to Reproduce
>
> 1. Open browser
> 2. Use it for normal activity for some time (can't precise exactly)
> 3. Try to open a tab and find it unresponsive
