### ISSUE TITLE
Pause is not working correctly for downloads

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9244]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Pause/Resume is not working correctly for download items.
- Platform (Win7, 8, 10? macOS? Linux distro?):
mac
- Brave Version (revision SHA):
d4f169a
- Steps to reproduce:
    1. Download an item
    2. Click on pause
    3. Click on Resume
    
- Actual result:

- Expected result:
Pause and resume should work normally. When you click on a pause, download is paused. When you click on resume, download is resumed.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes

- Screenshot if needed:
![2](https://cloud.githubusercontent.com/assets/9574457/26758354/60363cac-4890-11e7-9d61-f9e5863da632.gif)

**Comment by luixxiul** [comment]
I remember @srirambv has logged that issue somewhere.
