### ISSUE TITLE
On Windows 7/10 JP, bookmark manager is not opened via Window -> Bookmark

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9248]
**Describe the issue you encountered:** Bookmark manager is not opened via Window -> Bookmark (and Bookmark -> Bookmark) on main menu.

The shortcut key combination works.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 and Windows 7. The issue cannot be reproduced on macOS.

- Brave Version (revision SHA): 0.15.314

- Steps to reproduce:
    1. Create a backup of your browser's profile 
    2. Open the browser
    3. Set the lang setting to `Japanese` (not other languages)
    4. Restart the browser
    5. Click `ウィンドウ` (Window) on the menu bar
    6. Select `ブックマーク` (Bookmark)
    
- Actual result: the bookmark manager is not opened

- Expected result: It should be opened

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
It's working for me on macOS

**Comment by bsclifton** [comment]
Also works for me on 0.15.314 on Windows 10 x64

@luixxiul can you please retest?

**Comment by luixxiul** [comment]
Hm... I couldn't reporudce the issue with a fresh profile.

**Comment by luixxiul** [comment]
I can reproduce the issue by changing the lang setting to Japanese. On the other languages it seems to work, while it doesn't on Japanese.

**Comment by luixxiul** [comment]
Updated the STR on the 1st post.

**Comment by luixxiul** [comment]
Please feel free to revert the milestone to 0.18.x based on priority.

**Comment by bbondy** [comment]
@luixxiul I spent some time on this and tried the following:
OS: Ubuntu 17.04
Build: 0.16.9 release

I followed the STR exactly with the Japanese language and when I clicked the menu item it opened the bookmarks tab like it should have.

Could you check in your shift+f8 console for errors? Also please try from a dev build so you can see if there's anything in the terminal that logs any errors. 

I suspect something else is going on in your session store.  Please try with a fresh profile to refine the steps.  If you can reproduce even with a fresh profile I suspect something else with the environment is going on.

**Comment by bbondy** [comment]
I'll also remove the milestone for now but please re-add it back to the latest milestone (currently 0.17.x) if you can refine the STR to better reproduce. Thanks!

**Comment by luixxiul** [comment]
I could not reproduce the issue on macOS but Windows 

Windows 10 JP VM, 0.15.2, w/o fresh profile -> reproduced
Windows 10 JP VM, 0.15.2, w fresh profile -> reproduced
Windows 7 JP VM, 0.15.312, w/o fresh profile -> reproduced
Windows 7 JP VM, 0.15.312, w/ fresh profile -> reproduced
Windows 10 JP, 0.16.9, w/o fresh profile -> reproduced
Windows 10 JP, 0.16.9, w/ fresh profile -> reproduced

macOS JP, 0.19.0, w/ fresh profile -> not reproduced
macOS JP, 0.15.314, w/ fresh profile -> not reproduced

**Comment by luixxiul** [comment]
I updated the title to reflect the investigation above.

**Comment by luixxiul** [comment]
@bbondy also I opened devtool on the browser level, still I find nothing there. Just the usual errors and warning messages have been logged.

**Comment by luixxiul** [comment]
I still experience the issue on:

 
Brave: 0.18.22 
rev: d850e287ace296e2c62e28ba2979cf172e41cc45 
Muon: 4.3.9 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

Maybe due to misconfiguration of keymap or something?
