### ISSUE TITLE
Custom bookmark titles aren't being searched for suggestions

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9249]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you create a custom bookmark title, the text in that custom title won't be searched.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.15.x and beyond.

- Steps to reproduce:
    1. Create a bookmark
    2. Edit the bookmark title to zzz and save
    3. Type zzz in the urlbar
    
- Actual result:
It won't find any suggestions.
- Expected result:
It should find the suggestions.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

**Comment by alexwykoff** [comment]
What's slightly confusing about this is that the custom title isn't displayed in the results with the url. Rather the original title is displayed.

<img width="936" alt="screen shot 2017-06-07 at 5 01 35 pm" src="https://user-images.githubusercontent.com/1434040/26903470-00abf93c-4ba3-11e7-846e-ba5a2ceeca47.png">
