### ISSUE TITLE
Give a option to stick menu bar on Windows

### ISSUE THREAD

**Issue by seeam** [brave/browser-laptop#925]
On windows I'm not seeing any way to stick the menu bar. Every time it requires to press alt key. If not yet implemented, please implement this.

**Comment by bbondy** [comment]
is there usually an always show menu option somewhere? It's possible for us to do it just wondering how that's normally done in Windows.

**Comment by bbondy** [comment]
maybe right click on one of the toolbars?

**Comment by seeam** [comment]
Usually it's under view menu on Firefox. See this image, though it's a pretty old screenshot, the method is still in use. Also they have put this option inside customize panel but as Brave doesn't have customize panel, you can put it into view menu. 
Screenshot: http://tothepc.com/img/2010/07/firefox-menu-bar-21.png

**Comment by bbondy** [comment]
++ thanks

**Comment by luixxiul** [comment]
Closing for now, see related: #1699
