### ISSUE TITLE
Accesing address bar with Alt+D causing menu to appear and stay (resulting in unability to write address)

### ISSUE THREAD

**Issue by stmr** [brave/browser-laptop#9253]
- Did you search for similar issues before submitting this one?
I've tried.

- Describe the issue you encountered:
When I press Alt+D to access address bar, Brave changes focus but in the same time it opens menu bar, rendering typing in address bar unavailable until Alt is pressed one more time or address bar is clicked

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10

- Brave Version (revision SHA):
All versions until now

- Steps to reproduce:
    1. Browse as normal, when you want to change website address, instead of clicking the adress bar, 
        press ALT+D
    2. Try to type address
    3. See?
    
- Actual result:
On top of focusing the address bar it also opens menu bar.

- Expected result:
Only access address bar so I can type the address right away.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

It would be super awesome to have this in 0.16.x, since I guess it's a minor bug. Keep up the great work!

**Comment by luixxiul** [comment]
duping to #5775
