### ISSUE TITLE
Remove sync devices feature - Sync'd device manager

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9254]
**Describe the issue you encountered:** Feature to remove devices synchronized with the same passphrase should be added.

- Brave Version (revision SHA): 0.15.314

- Steps to reproduce:
    1. Sync more than 2 profiles with the same sync passphrase
    
- Actual result: You cannot remove sync'd profile.

- Expected result: It would be nice if it would be possible to 
  1. Have a sync'd devices manager
  2. With the maneger, select whether you would just remove the profile, or delete it once the browser is opened and connected to the sync server (anti-theft). To prevent the bad guy from clearing the other profiles on the stolen laptio, that feature should be enabled with either passcode or 2fa.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by gruvin** [comment]
+1 for being able to revoke sync passwords. Computer get stolen, all the time. This is a VITAL feature. Drop everything and do this first, please. Absolutely CRITICAL. Deal breaker for me. Not using Brave until this is sorted out. Thanks.

**Comment by bsclifton** [comment]
Closing as `wontfix` since we're going to switch gears and focus more on Brave Core. This is captured there with https://github.com/brave/brave-browser/issues/356
