### ISSUE TITLE
Resetting sync passphrase feature

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9255]
**Describe the issue you encountered:** Resetting sync passphrase feature would be nice in case where the passphrase is leaked by any chance.

Yet, as the leaked passphrase would be changed by the attacker, the passphrase itself would then have to be protected some way.

- Brave Version (revision SHA): 0.15.314

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #9254

**Comment by diracdeltas** [comment]
The passphrase encodes your sync identity. There is no way to change the passphrase except to reset sync completely.
