### ISSUE TITLE
Linux Keyboard navigation still not working

### ISSUE THREAD

**Issue by morganrallen** [brave/browser-laptop#9257]
- Did you search for similar issues before submitting this one?
Yes. Similar to  #7491 but persisting.

- Describe the issue you encountered:
Alt-(Left/Right) Keybaord navigation doesn't work

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Ubutnu 17.04
- Brave Version (revision SHA):
0.15.314  75ffa36

- Steps to reproduce:
    1. Open multiple tabs
    2. Use Alt-left to navigate.
    3. 
    
- Actual result:
Nothing

- Expected result:
Navigating 1 tab left.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Unknown

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues:
https://github.com/brave/browser-laptop/issues/7491

**Comment by luixxiul** [comment]
#7491 looks like not tested on Linux, so I'm not sure if this is a regression or just persisting issue.

**Comment by bsclifton** [comment]
@luixxiul were you able to reproduce this?

**Comment by luixxiul** [comment]
I'm going to test this later :-)

**Comment by morganrallen** [comment]
I made some recent changes to my system and noticed this doesn't affect Gnome but did affect Unity/Compiz.

**Comment by skrish13** [comment]
alt-left/right still not working in linux for previous history pages

**Comment by nikolas** [comment]
Alt-left and right works for me, I'm on Debian testing/buster, brave 0.23.79.

**Comment by skrish13** [comment]
yup looks like it works fine now. please close it.
