### ISSUE TITLE
Extension: goo.gl URL Shortener

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9258]
Extension: goo.gl URL Shortener
Web Store: [chrome.google.com/webstore/detail/googl-url-shortener/iblijlcdoidgdpfknkckljiocdbnlagk](https://chrome.google.com/webstore/detail/googl-url-shortener/iblijlcdoidgdpfknkckljiocdbnlagk?hl=en)

## Known Issues:

- JSON.parse fails to parse _messages.json_ due to BOM at start of file.

## Needed APIs:

**chrome.contextMenus**
- chrome.contextMenus.create
- chrome.contextMenus.removeAll

**chrome.extension**
- chrome.extension.getBackgroundPage
- chrome.extension.onMessage
- chrome.extension.sendMessage

**chrome.i18n**
- chrome.i18n.getMessage

**chrome.identity**
- chrome.identity.getAuthToken
- chrome.identity.removeCachedAuthToken

**chrome.tabs**
- chrome.tabs.create
- chrome.tabs.getSelected
- chrome.tabs.update

**Comment by Samuelvey** [comment]
How to connect metamask.io from my etherwallet.com?

**Comment by jrdnrocks** [comment]
[Service being discontinued in May; they are moving onto FireBase Dynamic Links](https://www.msn.com/en-us/news/technology/google-to-end-googl-link-shortener-service/ar-AAvqmJx)

**Comment by bsclifton** [comment]
Closing as this service will be EOLed
