### ISSUE TITLE
LastPass won't stop asking for 2FA code

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#9259]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
LastPass periodically requires me to reauthenticate with its second factor (in my case, a 6-digit code from Google Authenticator). Sometimes in Brave a new tab opens with a LastPass dialog box up asking me to authenticate again, but no amount of entering new codes makes the dialog. However, the LastPass icon turns from gray to red (or maybe it was red all along?), indicating the authentication was successful or unnecessary. The problem is sporadic. I'm not sure if it comes more frequently than the 30-day period that an authentication should last.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12.6 beta (but this issue has been around for a few months for me)

- Brave Version (revision SHA):
Brave	0.15.314
rev	75ffa36
Muon	3.0.202
libchromiumcontent	58.0.3029.110
V8	5.8.283.38
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.7.0
os.arch	x64

- Steps to reproduce:
    1. Install LastPass with dual-factor authentication
    2. Wait
    
- Actual result:
LastPass 2FA authentication dialog box doesn't go away

- Expected result:
LastPass 2FA authentication works (or isn't triggered when it's not needed)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
unclear

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
unclear but it's happened to me several times.

- Screenshot if needed:

<img width="728" alt="screenshot 2017-06-04 18 47 44" src="https://cloud.githubusercontent.com/assets/16833251/26768295/c0f7b6b2-495b-11e7-8900-2da5ac2f4b35.png">

**Comment by jonathansampson** [comment]
I've setup Google Authenticator on my end, and will proceed to use it with LastPass. Thank you for the heads-up; we'll see to it that any issues are given appropriate consideration, and are resolved a.s.a.p.!

**Comment by luixxiul** [comment]
As #4687 was fixed for 0.18, let's confirm this issue was also fixed.
