### ISSUE TITLE
CTRL+ALT+B does not work

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-laptop#926]
Windows 10 the shortcut (CTRL+ALT+B) does not work

**Comment by twisterghost** [comment]
Can you give some information on whatt this shortcut is supposed to do?

**Comment by bbondy** [comment]
bookmarks manager I believe.

**Comment by bbondy** [comment]
See `app/localShortcuts.js` if you want to take, it should be for all platforms not just windows, but on OS X it's Command and not Control.
`CmdOrCtrl+Alt+B`

**Comment by twisterghost** [comment]
I can give it a shot so long as I understand what its supposed to do. To be clear, it just needs to open Brave's bookmarks manager? I'm running chrome and IE and neither seem to respond to ctrl+alt+b, but I'm happy to add it.

**Comment by twisterghost** [comment]
Yeah I see the hotkey labelled on the bookmarks manager. I'll see if I can get it working.

**Comment by bbondy** [comment]
Actually just the accelerator in js/commonMenu.js should be needed.  It does seem to work on OS X.

**Comment by twisterghost** [comment]
Ah, I got it working in localShortcuts, but it looks like the accelerator already exists for it. Wonder why its borked.

**Comment by twisterghost** [comment]
This issue might be of use: https://github.com/atom/atom/issues/3930

Looks like its a common issue for `ctrl+alt+b` to be hijacked on windows. Changing the accelerator to just `alt-b` on my local windows machine makes it work fine, though I don't know how into the idea of changing the hotkey you guys are.

Maybe fork the hotkey per-OS? Or perhaps an FAQ point would be better for the sake of standardization.

**Comment by twisterghost** [comment]
This has been fixed by #948

**Comment by bbondy** [comment]
Thanks @twisterghost !
