### ISSUE TITLE
Tab titles not updating correctly with google docs

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#927]
From support.
As in the picture provided.
Reproduced with Windows 10 7.16 version.

![image](https://cloud.githubusercontent.com/assets/17283040/13360902/dc250d94-dcbb-11e5-9eaa-a87689924afc.png)

**Comment by adam-lynch** [comment]
The same happens with my app. The `<title>` has content initially and is updated via JS. Is this a bug or  something we're doing wrong?

Note: when you change view in our app, the `<title>` is updated. When this happens, the tab title flashes to the correct values and very quickly back to the URL. This is barely noticeable but it does happen.

**Comment by stshank** [comment]
I'm also noticing this issue (which curiously also afflicts in Microsoft Edge) on OS X 10.11 El Capitan.

**Comment by bbondy** [comment]
This should be fixed with 0.10.1.
