### ISSUE TITLE
Ecosia Favicon not displaying

### ISSUE THREAD

**Issue by newm-newm** [brave/browser-laptop#9289]
- Describe the issue you encountered:
On the preferences page for Search the favicon for Ecosia does not display correctly.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10, though as it is a 404 error it should be across all platforms

Will be submitting a pull request fix.

**Comment by newm-newm** [comment]
Pull Request:
https://github.com/brave/browser-laptop/pull/9290

**Comment by newm-newm** [comment]
Pull Request:
#9291

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/9291
