### ISSUE TITLE
Suggestion: Hardware acceleration on/off switch in settings

### ISSUE THREAD

**Issue by SJ-Diamond** [brave/browser-laptop#929]
As some users have problems with hardware acceleration, which i also have already experienced with various browsers, it would be good to have a checkbox in the options to be able to deactivate hardware acceleration.

Thanks!

**Comment by bbondy** [comment]
As of  electron v1.2.2, just released, we now have support for `app.disableHardwareAcceleration()`

**Comment by luixxiul** [comment]
Hopefully it might solve #1392 and #1471...

**Comment by SJ-Diamond** [comment]
Wow, thanks :) Looking forward for a glitch free Brave experience :D
