### ISSUE TITLE
Import passwords from Firefox

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#9292]
including passwords list and never saved list

**Comment by kjozwiak** [comment]
@darkdh, is the following test case sufficient enough to test this feature?

**Test Case:**

* login into several different websites using the latest version of firefox and save the passwords
* launch Brave and visit about:preferences
* under "Import Browser Data", click on the "Import Now..." button
* select firefox from the dropdown menu and ensure "Saved passwords" is being selected
* Click on "Import"
* Once you've received the "Your data has been imported to Brave successfully.", click on "Ok"
* visit about:passwords and ensure that there's passwords being listed
* load of the same websites as before and ensure that the passwords are being filled out

**Comment by darkdh** [comment]
yes, but missing never saved list.
make sure you have this in Firefox
<img width="672" alt="screen shot 2017-09-26 at 9 09 20 pm" src="https://user-images.githubusercontent.com/11330831/30895423-015bf4c8-a2ff-11e7-9165-bdaa5ed202bb.png">
and the site will be imported to our never saved list.
When you type username/passwords on the site, we will not prompt you to save password.

**Comment by kjozwiak** [comment]
Thanks @darkdh, updated the above test case!
