### ISSUE TITLE
automated test "Autoplay test always allow" is failing on Travis

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9298]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/jobs/240232452#L3112
````
  2) Autoplay test always allow:
     Promise was rejected with the following reason: timeout
  Error
````

The test is ~~always~~often failing.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by alexwykoff** [comment]
Should be covered by intermittent retry system
