### ISSUE TITLE
Tabs on reopened closed window is not usable

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9300]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported by @BrendanEich , Tabs on reopened closed window is not usable

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.3
rev	9f7c3b7
Muon	3.2.102

- Steps to reproduce:
    1. Open multiple tabs in windows 1
    2. Open a new window with one tab
    3. Close Window 1. From window 2 reopen closed window, none of the tabs are usable
    4. Try visiting any site in the active tab on the reopened widow, nothing loads, Console shows error(screenshot)
    
- Actual result:
Tabs on reopened closed window is not usable

- Expected result:
Window should be usable

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/26877098-bb9c5002-4b80-11e7-873c-dca6675761ac.png)

- Any related issues:
cc: @BrendanEich @bsclifton @bbondy

**Comment by LaurenWags** [comment]
Confirmed same behavior on MacOS 10.11.1.

**Comment by bridiver** [comment]
looks like maybe we're not clearing guestInstanceId so the re-opened tab tries to use the old value? guestInstanceId and tabId should never be persisted

**Comment by bbondy** [comment]
Is this an issue in the currently released version?

**Comment by LaurenWags** [comment]
I just checked 0.15.314 on mac and saw the same results.

**Comment by srirambv** [comment]
Verified on 0.16.5. Works fine
