### ISSUE TITLE
Changing bookmark location causes duplicate bookmarks

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9301]
- Did you search for similar issues before submitting this one?
Yes, didnt find any issues with bookmark tag

- Describe the issue you encountered:
Changing bookmark location causes duplicate bookmarks

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.3
rev	9f7c3b7
Muon	3.2.102

- Steps to reproduce:
    1. Create a bookmark folder 
    2. Add a bookmark and add under the created folder
    3. Visit the site by clicking on the bookmark
    4. Edit the bookmark in the URL and change the location to `Bookmark Toolbar` 
    5. Bookmark is duplicated under the folder and the toolbar
    
- Actual result:
Changing bookmark location causes duplicate bookmarks

- Expected result:
Should only have one bookmark and not duplicate. Behaviour is different from Chrome

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, 
Edit: Have checked it from 0.14.1 and its the same issue

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![duplicatebookmarks](https://user-images.githubusercontent.com/17010094/26880055-257c0300-4b8b-11e7-9733-5a7caa8b1569.gif)

- Any related issues:

**Comment by NejcZdovc** [comment]
Should be fixed in #9979
