### ISSUE TITLE
Browser History not fully synced between OSX and Linux

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9303]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When Browsing History is enabled under Preferences > Sync > Sync Data, Browsing History is not fully sync-ed between my laptop (mac) and linux vm.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Device 0 is MacBook running 10.11.1
Device 1 is Linux VM running Ubuntu 17.04

- Brave Version (revision SHA):
Device 0/Mac:
Brave	0.16.3
rev	9f7c3b7
Muon	3.2.102
libchromiumcontent	59.0.3071.71

Device 1/LinuxVM:
 Brave	0.15.310
rev	6b5e4e2
Muon	3.0.201
libchromiumcontent	58.0.3029.110

- Steps to reproduce:
1. Enable Sync (no changes to settings) on Device 0/Mac.
2. Enable Sync (no changes to settings) on Device 1/Linux VM.
3. Bookmarks/site settings were synced as expected.
4. On Device 0/Mac enable Browsing History Sync.
5. On Device 1/LinuxVM enable Browsing History Sync.

    
- Actual result:
Browsing history was not synced. 

- Expected result:
Browsing History would be synced. When I opened the Linux VM the next morning I saw that some of the browsing history was synced, but not all.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Device 0/Mac has beta version

- Can this issue be consistently reproduced?

- Extra QA steps:
n/a

- Screenshot if needed:
Device 0/Mac History:
<img width="1248" alt="screen shot 2017-06-07 at 10 35 44 am" src="https://user-images.githubusercontent.com/28145373/26886173-bc085ac6-4b72-11e7-97b2-8709c3af7fec.png">

Device 1/Linux VM (note missing & out of order entries)
![screen shot 2017-06-07 at 10 37 59 am](https://user-images.githubusercontent.com/28145373/26886287-f5b78c92-4b72-11e7-8f1f-dee1c5237ee7.png)

- Any related issues:

**Comment by diracdeltas** [comment]
fyi sync only syncs browser history going forward in time, not browser history from before sync was enabled. this was a design choice to limit bandwidth. see https://github.com/brave/browser-laptop/issues/8488

**Comment by alexwykoff** [comment]
migrated to https://github.com/brave/sync/issues/113
