### ISSUE TITLE
Closing Tabs Results in White Page

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9306]
## Test plan
See https://github.com/brave/browser-laptop/pull/9539

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Upon closing 2 tabs, the user may be presented with a white page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/75ffa36130b1ad33c6f311e5e16ed7838b0b50a0

- Steps to reproduce:
    1. Open 7 tabs (7th tab selected)
    2. Click x on 6th tab (don't move mouse)
    3. Click x on 7th tab (should move under your mouse)
    
- Actual result:
Focused tab is white.

- Expected result:
Focused tab is visible to the user.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

![white-tab](https://user-images.githubusercontent.com/815158/26891366-9e849c02-4b69-11e7-8a79-8ff012152697.gif)

**Comment by bridiver** [comment]
`may` means it is intermittent? Or can you reliably repro?

**Comment by jonathansampson** [comment]
@bridiver I was able to reproduce it 100% of the time (as was @NejcZdovc I believe) when I carefully followed the steps above.

**Comment by cezaraugusto** [comment]
so issue happens for any prefs config for "When closing an active tab" option

issue reported above (https://github.com/brave/browser-laptop/issues/9306#issuecomment-308908661) is different than the main issue. I created a new one for that #9536 with fix under #9537. /cc @jonathansampson 

Seems that issue happened after 039109635a173acddc326dce45916ef00d738409. For me, following the STR it is always falling in under this conditional https://github.com/brave/browser-laptop/commit/039109635a173acddc326dce45916ef00d738409#diff-585bc5df4db53a44a36b51f6bd4e0bc3R36. Given next frame is a user decision, I'm not sure what is expected in this case.

@bridiver do you mind jumping in to see what's going wrong? I created a failing test case in #9539.

**Comment by bridiver** [comment]
thanks for the test case @cezaraugusto ! I have an idea of what the issue might be and should be able to track it down pretty quickly

**Comment by bridiver** [comment]
Haven't checked the test run yet and probably needs a unit test update, but the new test passes
