### ISSUE TITLE
Switching to new URL wihtin the same tab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

### ISSUE THREAD

**Issue by llspence** [brave/browser-laptop#931]
When I type a url from an existing tab with a different url, it won't allow me to get to the new url I typed. It does not happen every time, but it happens frequently. I would have open up another tab to get to the new url I want.

**Comment by psimyn** [comment]
Not sure I quite understand the issue. Maybe the same as this one: https://github.com/brave/browser-laptop/issues/799 ?

Example:
1. go to google.com
1. click back button
1. try to go to google.com again

**Comment by luixxiul** [comment]
Closing for now
