### ISSUE TITLE
Tab update events happen when there are no tab updates

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9313]
Because of an equality check that always differs for deep objects, we were wrongly thinking there were tab updates causing an event storm if the user had a lot of tabs. 

The fix is actually in muon but I'm tracking here.

**Comment by bsclifton** [comment]
@bbondy @bridiver @ayumi was this fixed in Muon 4.0.1? If so, we can bump milestone to 0.16.x

**Comment by bbondy** [comment]
Yes it is in 4.0.1 and we want to upgrade to that for the next RC.  Moving this to 0.16.x
