### ISSUE TITLE
Pause download doesn't immediately stop the download indicator

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9320]
## Test plan

https://github.com/brave/browser-laptop/pull/11547#issue-265603202

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pause download doesn't stop the download indicator

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.4
rev	15d8d36
Muon	4.0.0

- Steps to reproduce:
    1. Start a download
    2. Click on pause button
    3. Download stops but the progress indicator still progress and then stops
    
- Actual result:
Pause download doesn't stop the download indicator

- Expected result:
Progress indicator should stop along with the download

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![9244](https://user-images.githubusercontent.com/17010094/26900792-4c68d322-4bcb-11e7-976d-f769dfe908fe.gif)

- Any related issues:
#9244

**Comment by NejcZdovc** [comment]
I am pushing this back because this is not a new bug and this issue didn't have milestone before #10148 was created
