### ISSUE TITLE
Editing autocompleted URL deletes autocompleted URL with typed in key

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9322]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Editing autocompleted URL deletes a portion of the URL text

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows x64

- Brave Version (revision SHA):
Brave	0.16.4
rev	15d8d36
Muon	4.0.0

- Steps to reproduce:
    1. Visit https://github.com/brave/browser-laptop/issues/ in a tab
    2. Open new tab and type in git for history to come up 
    3. Select the suggested history item and select laptop and type <kbd>i</kbd>. entire text is replaced and retains giti
    
- Actual result:
Editing autocompleted URL deletes a portion of the URL text

- Expected result:
Should only replace text and not remove entire URL

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes from 0.15.310 onwards(post bloodhound URL PR #8824 )

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![urlsuggestions](https://user-images.githubusercontent.com/17010094/26901452-d7800f0a-4bcd-11e7-97db-cc35e3d8e42e.gif)

- Any related issues:
cc: @bbondy

**Comment by bsclifton** [comment]
Automated test covers this very well (as long as we check results before deploying); marking as `no-qa-needed`
