### ISSUE TITLE
Spell Check corrected word still retains the red underline

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9324]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Spell Check corrected word still retains the red underline

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.4
rev	15d8d36
Muon	4.0.0

- Steps to reproduce:
    1. Open about:styles
    2. Type in `fead` , ensure red under line is shown
    3.  Right click, select correct text, still retains the red underline, is dismissed after mouse click
    
- Actual result:
Spell Check corrected word still retains the red underline

- Expected result:
Should dismiss the red underline after text is corrected

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#9102

**Comment by bbondy** [comment]
@alexwykoff @srirambv could you compare against Chrome spell check?  Is the issue also there?

**Comment by srirambv** [comment]
@bbondy Yes its the same behaviour on Chrome also

**Comment by darkdh** [comment]
![kapture 2017-06-12 at 11 37 39](https://user-images.githubusercontent.com/11330831/27049272-a8ddba78-4f63-11e7-82fa-19dac2e498c3.gif)

**Comment by bbondy** [comment]
I think we should probably sit on this until C60 and retest in both Chrome and Brave.

**Comment by darkdh** [comment]
Just verified Chrome  61.0.3128.0 has fixed this problem

**Comment by luixxiul** [comment]
Accoding to https://github.com/brave/browser-laptop/issues/9324#issuecomment-308009051 I'm going to close this issue, and adding it to the latest milestone to make sure this would be tested by QA. thanks.
