### ISSUE TITLE
 investigate anti-ad blocker on washingtonpost.com

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#9325]
Anti-ad blocker in place on the Washington Post. 
Confirmed on desktop: PC (Win10) and MacOS

Brave version: https://github.com/brave/browser-laptop/commit/75ffa36130b1ad33c6f311e5e16ed7838b0b50a0

Steps to repro: 
- Go to: https://www.washingtonpost.com/news/dr-gridlock/wp/2017/06/06/an-airline-tried-to-get-a-musician-to-check-her-17th-century-violin-a-wrestling-match-ensued/
- Get anti-ad blocker: 
![brave-washingtonpost-06072017-antiadblocker](https://user-images.githubusercontent.com/8979240/26904694-05502234-4b98-11e7-8af8-3cc63c4f38f4.PNG)

Workarounds: 
- Disabling scripts in the Shields menu works. 
- Disabling cache in dev tools also works.

**Comment by jspenguin2017** [comment]
I think [this script](https://www.washingtonpost.com/pb/gr/c/default/rjtNa11X65zHlq/load_immediately/4697e08d36.js?_=ffbe4) is responsible for it. [Here](https://pastebin.com/vsAmqDjd) is a mirror. 

I think these rules in uBO filter fixes it (didn't test, maybe not): 
```
washingtonpost.com###bottom-furniture
washingtonpost.com##html:style(height: initial !important; overflow: auto !important;)
```

**Comment by lukemulks** [comment]
+1 from Twitter https://twitter.com/Music_Journeys/status/882112999955320833

**Comment by valianliu** [comment]
+1 
I got anti-ad blocker in this page:

https://www.washingtonpost.com/news/post-nation/wp/2017/08/06/a-cop-stopped-a-car-for-speeding-then-pointed-a-gun-at-a-passenger-for-more-than-9-minutes/
![snap170807_195528](https://user-images.githubusercontent.com/9492905/29025776-05724f92-7bab-11e7-8c07-9adb5835f3d8.jpg)

Confirmed on desktop: PC (Win10) 

I think rules should update. Thx for owner's effort.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/they-force-you-to-turn-off-the-brave-blocking/5412
Brave 0.18.17
MacOS 10.12.5

**Comment by srirambv** [comment]
This happens even with adblock turned off, once the anti adblock is shown 
![washington post](https://user-images.githubusercontent.com/17010094/29493276-f059f242-858a-11e7-986e-2974c11f5e67.PNG)

**Comment by luixxiul** [comment]
@lukemulks here's the error messages on the console.

````
mux.js:8 [mux] A monitor for `powa-player-bc40bb0e-1e00-11e7-bb59-a74ccaf1d02f` has not been initialized.
mux.js:8 [mux] A monitor for `powa-player-bc40bb0e-1e00-11e7-bb59-a74ccaf1d02f` has not been initialized.
chartbeat.js:8 Uncaught TypeError: Cannot read property 'type' of undefined
    at chartbeat.js:8
    at q (chartbeat.js:11)
    at ma (chartbeat.js:8)
    at xb (chartbeat.js:42)
    at W.l.B (chartbeat.js:35)
    at W.l.B (chartbeat.js:49)
    at chartbeat.js:8
    at cb (chartbeat.js:23)
    at W.T [as constructor] (chartbeat.js:34)
    at new W (chartbeat.js:48)
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://s.effectivemeasure.net') does not match the recipient window's origin ('https://www.washingtonpost.com').
````

**Comment by luixxiul** [comment]
You need to allow the 3rd party cookie as well as ads/trackers and reload the page to prevent that from being displayed.

**Comment by lukemulks** [comment]
+1 from a macOS user.  Will work on resolving. So far, appears only limited to desktop.

**Comment by tbates** [comment]
Can confirm on desktop site is blocked for brave, even with shields down.
 
Brave: 0.19.45 
rev: cddf9a560535f889201fc0157ebf0b982ea19c00 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 17.2.0 
OS Architecture: x64

**Comment by adzsafe** [comment]
Hey!!!  Adblocking has been growing and growing, showing no signs of letting down. As a publisher, I also face adblocking issues. It intrrupts my ads to load safely on sites. Out of your two tactics, Blockadblock seems effective. Until now, I have used <A herf=" https://www.adzsafe.com/ ">Adzsafe</A> that disables adblockers instantly from user's browser and supports ads to load safely. But I would definitely try this. Thanks!
