### ISSUE TITLE
Custom bookmark title is not being displayed in suggestions

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9326]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While verifying another issue, it was discovered that custom bookmark titles aren't being displayed in the urlbar suggestions menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Discovered on OS X

- Brave Version (revision SHA):
0.16.4

- Steps to reproduce:
    0. Make sure 'Show bookmark matches' is enabled on about:preferences#search
    1. Create a bookmark with a custom title
    2. Open a new tab and type in the custom title.
    3. Check the suggestion content
    
- Actual result:
The suggestions do not display the custom title

- Expected result:
The suggestions should display custom titles if they exist

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
Should be fixed with #9979, because we removed custom title
