### ISSUE TITLE
temporarily disable the "Fund with debit/credit card" button until we have clarity on miner fees.

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#9327]
## Test plan
See https://github.com/brave/browser-laptop/pull/9331

## Original issue description
![0_720_480](https://user-images.githubusercontent.com/400552/26904626-a20877da-4b97-11e7-89e3-8e16d83a8f4f.png)
![1_720_480](https://user-images.githubusercontent.com/400552/26904627-a377f2a8-4b97-11e7-8f1d-c4cbcb3685bd.png)

1. disable the "Fund with debit/credit card" button
2. replace the "Transfer may take up to 40 minutes" text with text/link from @bradleyrichter

- Did you search for similar issues before submitting this one? no.

- Describe the issue you encountered: *res ipsa loquitur*

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version (revision SHA): n/a

- Steps to reproduce: *res ipsa loquitur*

- Actual result: *res ipsa loquitur*

- Expected result: *res ipsa loquitur*

- Will the steps above reproduce in a fresh profile? yes

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none

- Screenshot if needed: see below

- Any related issues: none

**Comment by bradleyrichter** [comment]
mockup:

![image](https://user-images.githubusercontent.com/13509546/26904864-f4f1a204-4b98-11e7-8eb3-8fd507c4ef54.png)

**Comment by bradleyrichter** [comment]
text:

Card funding is temporarily unavailable. 
We apologize for the inconvenience. Learn more...

**Comment by luixxiul** [comment]
Let's use `browserButton` on https://github.com/brave/browser-laptop/blob/master/app/renderer/components/common/browserButton.js#L31 for the button.
