### ISSUE TITLE
Pinning a normal tab causes browser crash but retains the pinned tabs upon restart

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9333]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pinning a tab causes browser crash but retains the pinned tabs upon restart

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.4
rev	15d8d36
Muon	4.0.0

- Steps to reproduce:
    1. Clean install 0.16.4 and launch with a new tab, do not close the new tab
    2. Open a `session 1 tab` and visit a site and pin it
    3. Open second `session 1 tab` and visit a different site and pin it
    4. Open third `session 1 tab` and visit a third site and pin it, move the third pinned tab to first position
    5. Visit a different site on the normal tab and pin it, browser crashes
    6. Relaunch the browser all pinned tabs are retained
    
- Actual result:
Pinning a normal tab causes browser crash but retains the pinned tabs upon restart

- Expected result:
Position of the session pinned tabs and pinning normal tabs should not cause any crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes verified same behaviour on 0.15.314 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Happens only when the same session tab is pinned. Checked with different session tabs doesn't crash
    2.
    3.

- Screenshot if needed:
![pintab](https://user-images.githubusercontent.com/17010094/26918629-bc0969b2-4c2a-11e7-80a7-25d5943d4b05.gif)

- Any related issues:
cc: @bbondy @bridiver

**Comment by srirambv** [comment]
Crash also happens when trying to login to Github pinned in `session 1 tab` . This is similar to #9138.
cc: @darkdh 
![pintab1](https://user-images.githubusercontent.com/17010094/26919514-ee4fc986-4c2d-11e7-985a-853a09121cb1.gif)

**Comment by bridiver** [comment]
windows only?

**Comment by srirambv** [comment]
Guess so. @alexwykoff @LaurenWags  could confirm if for macOS

**Comment by alexwykoff** [comment]
confirmed OS X

**Comment by wickdninja** [comment]
I am having a similar issue on windows when pinning multiple tabs. I was in the process of converting over from Chrome and I keep approx 13 tabs pinned at all times for work related tasks. While adding these tabs to Brave 1 at a time the browser started to crash when pinning a new tab after I had 6 tabs already pinned, but only sporadically (crashed 3 times while adding the 13 pinned tabs). I also noticed that sometimes the pinned tab positions itself to be the leftmost tab while other times it positions itself as the rightmost tab upon being pinned.

**Comment by alexwykoff** [comment]
@wickdninja i was unable to reproduce with pinning 14 tabs on 0.16.4, but it's also a different STR than having mixed sessions pinned. If you could, please open a new issue if it persists for you. Thanks!

**Comment by wickdninja** [comment]
Ok. I'll try to reproduce again, and I'll open a new issue if the issue persists.

**Comment by bsclifton** [comment]
@srirambv the logging into GitHub part (as you know) was fixed with the 0.16.9 hotfix 😄 

I tried the original steps on Windows 10 x64 and was unable to repro the issue. Can you please try again and close (if everything works)? Thanks 😄

**Comment by srirambv** [comment]
Verified on 0.16.9, issue fixed. marking as closed.

**Comment by LaurenWags** [comment]
Still observing crash at step 5 on MacOS. Will circle back.

**Comment by alexwykoff** [comment]
Not observing a crash, but pins 1-3 on session 1 disappeared after creating a 'normal' pinned tab. Opening a new window restored tabs.

**Comment by LaurenWags** [comment]
Still observing crash on 0.17.9 with MacOS, however @alexwykoff is not experiencing this same crash. Per discussion will investigate further.

**Comment by bsclifton** [comment]
I'm curious if this bug is the same as https://github.com/brave/browser-laptop/issues/9506...

**Comment by bsclifton** [comment]
follow up: I am not able to repro on macOS w/ 0.17.10

**Comment by alexwykoff** [comment]
Not able to repro on win32 0.17.11, still seeing https://github.com/brave/browser-laptop/issues/9333#issuecomment-310141793 though

**Comment by LaurenWags** [comment]
Still seeing issue as originally described while using 0.17.11 cc: @alexwykoff @bsclifton

**Comment by bsclifton** [comment]
@LaurenWags is this only happening for you on macOS? @alexwykoff should we create a macOS specific issue to track this? (since QA checked is on for Linux/Windows)

**Comment by LaurenWags** [comment]
Entered https://github.com/brave/browser-laptop/issues/9763 as MacOS specific and assigned to myself so I can further investigate. cc: @bsclifton @alexwykoff
