### ISSUE TITLE
Hovering the mouse over tiles on dashboard flickers the tab slightly

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9335]
**Describe the issue you encountered:** Hovering the mouse over tiles on dashboard flickers the tab slightly.

![dashboard](https://user-images.githubusercontent.com/3362943/26924207-c2b1ac98-4c7f-11e7-8e0e-ca241ced11b8.gif)

(Please open the gif in a new tab to confirm the flash)

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS (MBP)

- Brave Version (revision SHA): 0.15.312

- Steps to reproduce:
    1. Open a new tab
    2. Hover the mouse over the tiles
    
- Actual result: the content of the tab flickers/flashes slightly

- Expected result: It should not

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by cezaraugusto** [comment]
dupe of #7782 and seems fixed too so closing
