### ISSUE TITLE
Noob here: Unable to locate Transaction entry

### ISSUE THREAD

**Issue by sharbel92** [brave/browser-laptop#9343]
Used MetaMask to send Ether to an ETH adres. MetaMask says transaction failed and ETH is not anymore in my wallet and is not received on the recipient adres. Is there any way to get my Ether back?

I also see the following message: Unable to locate Transaction entry

**Comment by bsclifton** [comment]
@sharbel12g I know you had already closed the issue, but I would recommend reaching out to MetaMask support if you haven't already 😄
