### ISSUE TITLE
Visited links are not reset when history is cleared

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#9351]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
After visiting a link, it changes color. But when the history is cleared (with History > Clear Browsing Data > Browser history), visited links are not reset. Refreshing the page or closing and reopening the page does not make a difference.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, but likely all platforms.

- Brave Version (revision SHA):
0.16.6 (51de9af)

- Steps to reproduce:
    1. Visit any website with a plain link.
    2. Click the link.
    3. Navigate back.
    4. Notice that the link is now visited (and is colored differently).
    5. Select Menu > History > Clear Browsing Data or Preferences > Security > Clear Browsing Data Now. Select Browsing history and click Clear.
    
- Actual result:
The link remains colored as if it's visited.

- Expected result:
The link should be "unvisited" and changed to its original color.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Not sure.

- Is this an issue in the currently released version?
Yes, 0.16.6.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
None.

- Any related issues:
#512

**Comment by diracdeltas** [comment]
confirmed that with https://github.com/brave/muon/pull/217, the behavior is the same in Chrome and Brave
