### ISSUE TITLE
Add "iconOnly" property for browserButton

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9353]
## Test plan

https://github.com/brave/browser-laptop/pull/9236#issue-233376294

----

- Any related issues: #9232

**Comment by luixxiul** [comment]
Closed with #9236

**Comment by luixxiul** [comment]
Added `release-notes/include` to let (potential) contributors on UI know about the change.

**Comment by cezaraugusto** [comment]
thanks!
