### ISSUE TITLE
Focus is not set to minimized Dev Tools when a different element is inspected to Focus is not set to Dev Tools when a different element is inspected

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9359]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Focus is not set to minimized Dev Tools when a different element is inspected

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
All

- Steps to reproduce:
    1. Open a page and inspect an element
    2. Minimize the dev tools popup window
    3. Inspect a different element on the same page, Dev tools is not brought to front to show the element details
    
- Actual result:
Focus is not set to minimized Dev Tools when a different element is inspected

- Expected result:
Inspect element should bring dev tools to front and focus the element

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/developer-tools-not-embedded/3672/2
cc: @bbondy

**Comment by sly7-7** [comment]
Hello, do you have any idea on the ETA on this ? I try brave, and I really like it for normal use, but when it comes to develop, for me the fact I can't dock the dev tools is kind of a blocker.
