### ISSUE TITLE
Context menu doesn't respect overrides (in Google Docs)

### ISSUE THREAD

**Issue by twisterghost** [brave/browser-laptop#936]
Google docs provides its own context menu, but Brave's context menu is still appearing upon right clicking:

![Double context menu](https://s3-us-west-2.amazonaws.com/mjb-personal/brave-rightclick-google-docs-error.png)

This doesn't seem to be the case everywhere. S3 console's custom context menu seems to prevent the standard menu from being activated.

**Comment by psimyn** [comment]
To detect if there is an existing contextmenu listener, could either use [getListeners](https://developer.chrome.com/devtools/docs/commandline-api#geteventlistenersobject) (if available) or something like [this SO suggestion](http://stackoverflow.com/a/35235801/4423351)

**Comment by bbondy** [comment]
`event.isDefaultPrevented()`  doesn't help at all I guess?

**Comment by psimyn** [comment]
in my quick test it didn't work, it might need a setTimeout or some other consideration. Good thinking :+1:
