### ISSUE TITLE
Cannot zoom or scale with Macbook pro touchpad gestures in Brave

### ISSUE THREAD

**Issue by Miyayes** [brave/browser-laptop#9365]
- Describe the issue you encountered:

When looking at graphs, for example, (see: https://liqui.io/#/exchange/BAT_ETH), you cannot zoom in or out using the usual touchpad gestures on Macbook Pro. You can zoom in or out of this graph on Chrome.

- Platform (Win7, 8, 10? macOS? Linux distro?):

MacOS

- Brave Version (revision SHA):

Latest version at time of writing.

- Steps to reproduce:
    1. Go to https://liqui.io/#/exchange/BAT_ETH
    2. Try to use zoom in/zoom out gestures with cursor over the body of the graph
    3. If it does not react, then problem has been reproduced. Compare to behavior in Chrome, which does react.
    
- Actual result:

Graph does not move -- no reaction.

- Expected result:

Graph should zoom in and out on different timescales.

- Is this an issue in the currently released version?

Yes.

- Can this issue be consistently reproduced?

Yes.

**Comment by Liunkae** [comment]
Seems fixed. I cannot reproduce with Brave 0.20.30 on macOS 10.13.x. This may have been fixed at the same time as #1364.
