### ISSUE TITLE
Brave crashing when pressing login on xero.com and primepay.com

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9366]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
from community:
https://community.brave.com/t/issues-with-logging-into-websites-after-most-current-update/3719
I am running the Mac version of 0.16.6. I was trying to login to xero.com and primepay.com, which I have done before with no issues, but the browser crashes whenever I hit login after entering my credentials. I tried turning the login shield off for those sites as well, with no change in the behavior.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac 
- Brave Version (revision SHA):
Brave: 0.16.6 
rev: 51de9af083a50b9d5ceaec34af35ea3c1c9696fc 
Muon: 4.0.1 
libchromiumcontent: 59.0.3071.86 
V8: 5.9.211.31 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.5.0 
os.arch: x64

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:
Crahes
- Expected result:
Should be able to log in
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Similar to https://github.com/brave/browser-laptop/issues/9356 & #9138

**Comment by alexwykoff** [comment]
Closing this issue as all reports thus far have shown the crash to be gone.
