### ISSUE TITLE
Update muon to 4.0.2

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9369]
Tracking issue for muon

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/01c7b69113c2f2c6ae20dfc774e9b91fa7f1d5a1

**Comment by bsclifton** [comment]
Updated again with https://github.com/brave/browser-laptop/commit/fba98fcb091b3abfa18aba7c6c0db0c7aa343589
