### ISSUE TITLE
Url loading indicator (w/ theme color too)

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#937]
Would be a great idea for consistency reasons as Brave already has an option to have the tabs colored, if there would be also during page load an url progress indicator with the same color like the one of the loading tab.

**Comment by bbondy** [comment]
The color is only determined after but we could cache it.  That's be cool.

Here is how the URL loading should look:
<img width="763" alt="screenshot 2016-02-27 16 05 45" src="https://cloud.githubusercontent.com/assets/831718/13375396/0a22fcdc-dd6c-11e5-851a-b907a8a07208.png">

**Comment by SJ-Diamond** [comment]
Exactly what i meant, perfect.

Perhaps you could make as a bonus option also the color optionally user controlled, so the user could pick also some fixed color as url loading indicator?
