### ISSUE TITLE
Brave update bar is misaligned

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9370]
noticed this on OSX when updating from 0.15.x release to 0.16.6:
![screen shot 2017-06-09 at 8 34 01 am](https://user-images.githubusercontent.com/549654/26994670-5de5c7a6-4d1d-11e7-922e-57cee0330821.png)

**Comment by luixxiul** [comment]
@cezaraugusto Adding margin-bottom: @navbarMenubarMargin to `navigationWrapper` *only when the update bar is displayed* should be the solution as I tried. Adding margin-top to the update bar is not the proper way as there is applied `no-drag`.

**Comment by luixxiul** [comment]
Test plan (proposal)
- Try to update via menu
- Make sure the area around the update bar can be grabbed [1]
- DIsplay the bookmark toolbar
- [1]
- Hide the bookmark toolbar
- Open enough tabs to display the tab pages
- [1]

referring the test plan described on https://github.com/brave/browser-laptop/pull/7740#issue-214511262.

**Comment by cezaraugusto** [comment]
@luixxiul assigned you as well. I think you found the solution already so pls feel free to jump in

**Comment by luixxiul** [comment]
I'm not quite sure of the logic of the notification bar, so wondering if you would implement that ;-)

**Comment by luixxiul** [comment]
@petemill if you have some time would you mind addressing this issue??
