### ISSUE TITLE
With multiple windows open, upgrading to new build manually causes window loss

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9372]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
With multiple windows open, upgrading to new build manually causes window loss

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.6
rev	51de9af
Muon	4.0.1

- Steps to reproduce:
    1. Install an older build 
    2. Have 2 or more windows open 
    3. Run the beta build manually when the browser windows are still open
    4. After upgrade all browser windows are lost and creates a new session
    
- Actual result:
With multiple windows open, upgrading to new build manually causes window loss

- Expected result:
Upgrade should not cause window loss

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Quit browser and upgrade to new build doesnt causes window loss
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Closing in favour of #9373

**Comment by bsclifton** [comment]
@srirambv you beat me by 1 minute! 😛
