### ISSUE TITLE
Provide option to specify download default location for torrent download

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9382]
## Where is the default location?
Windows - `%APPDATA%\Local\Temp\webtorrent`
macOS, Linux - `/tmp/webtorrent`

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
>The default location for webtorrent downloads is /tmp/webtorrent.
>
>This can create problems. On my (linux) computer, /tmp is a mounted ramdisk (tmpfs) that maximizes to half of my ram. If the computer reboots, this space is wiped.
>
>Since I have 6 GB ram, this means it is limited to 3 GB.
>
>Yesterday I tried to download a 4.3 GB torrent file. No errors were reported, but obviously not all fit on the tmpfs, and when I tired to use the files, they were corrupted.
>
>Another effect was that it entirely filled the /tmp device, so many other applications began malfuctionining because they could not create temporary files.
>
>I believe webtorrent allows you to specify a different download location, but I cannot figure out how to do that when using Brave.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/provide-a-way-of-setting-webtorrent-download-location/3754

**Comment by cbj4074** [comment]
Should "on Linux" should be removed from the subject? This seems to be a cross-platform issue.

I'm trying to figure out how to specify the target download location on Windows and can't find any means by which to do so.

In fact, I'm unable to determine where on disk the downloaded files reside, which seems worse. :)

What is the default download destination for files downloaded via the BitTorrent client, on Windows?

**Comment by bsclifton** [comment]
@cbj4074 I had the same experience; we need to provide a way to change this default (and to make it more obvious).  I'm on macOS FWIW

**Comment by bsclifton** [comment]
cc: @bradleyrichter @alexwykoff @jenn-rhim
