### ISSUE TITLE
The brave update to 0.16.9 doesn't install on my imac using OSX yosemite 10.10.5

### ISSUE THREAD

**Issue by modeniro** [brave/browser-laptop#9383]
It always asks for the new update to install, i click okay, the browser gets closed, but no update gets installed. 5 minutes later it asks for the update to install again.

**Comment by Liunkae** [comment]
@modeniro Thanks for the report! This problem is similar to issue #2184, so I'll close this one as a duplicate. Please try the steps in this FAQ: https://github.com/brave/browser-laptop/wiki/End-User-FAQ#updates-are-available-but-applying-them-doesnt-work-on-macos
