### ISSUE TITLE
0.16.9 Release deletes all bookmarks from Bookmark Manager?!

### ISSUE THREAD

**Issue by DJBigCheese** [brave/browser-laptop#9386]
All the Tabbed bookmarks in the normal tabbed view are intact & functional, but 'about:bookmarks' view are all gone!!!

**Comment by bsclifton** [comment]
@DJBigCheese do you have more info?  Can you take a screenshot of your `about:bookmarks` screen?  You should see all of your bookmarks (and folders) under the `Bookmarks Toolbar` top level folder

**Comment by DJBigCheese** [comment]
We can disregard. Everything is there now. It was strange because I went to check my Bookmark Manager scrolling capabilities right after the update & everything was gone! Everything is back to normal & functional :)

Steve

**Comment by bsclifton** [comment]
Awesome, thanks for the update Steve! :) I'll go ahead and close this out
