### ISSUE TITLE
Blank screen in new tab after searching a query

### ISSUE THREAD

**Issue by shubhamy** [brave/browser-laptop#9387]
Hi, I have been repeating the following steps:
1. Open the Brave browser and search for a website. It works well.
2. I open a new tab and see the homepage.
3. I search for something in the search bar, it loads and show a blank white screen (see the attachment)

I have also disabled ''Use hardware acceleration when available" in case it was causing the issue but it did not work.

My OS configuration: Ubuntu 16.04.2
Brave version: 0.15.314

![bug](https://user-images.githubusercontent.com/6676622/27006467-103317e4-4e52-11e7-89b8-01dd5def5766.png)

**Comment by bsclifton** [comment]
Hi @shubhamy 

Can you try the steps here please? I am hoping this helps:
https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page

**Comment by shubhamy** [comment]
It worked. Thanks @bsclifton .

**Comment by bsclifton** [comment]
@shubhamy awesome! thanks for the response, super glad its working for you 🎉
