### ISSUE TITLE
"Hide the menubar by default" ignored on restart in 0.16.9

### ISSUE THREAD

**Issue by arxo** [brave/browser-laptop#9391]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Since the update of Brave to 0.16.9 the "Hide the menubar by default" is ignored on every (re-)start.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu MATE 16.04.2 (Ambiant MATE theme)

- Brave Version (revision SHA):
fba98fcb091b3abfa18aba7c6c0db0c7aa343589

- Steps to reproduce:
    1. install Brave from official repo on Ubuntu MATE 16.04.2 with all updates and default theme
    2. start Brave
    3. check settings "Hide the menubar by default" (it is enabled)
    
- Actual result:
Menubar is shown, despite "Hide the menubar by default" being enabled

- Expected result:
Menubar is not shown

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes, a fresh profile suffices

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Screenshot if needed:

- Any related issues:
5086

**Comment by bsclifton** [comment]
@arxo thanks for reporting! This is a known issue and has been recorded with https://github.com/brave/browser-laptop/issues/5086 (which you can subscribe to that issue for updates)
