### ISSUE TITLE
"Select its parent tab" setting not working as expected

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9395]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Picking `Select its parent tab` for the `When closing an active tab` setting does not always behave as expected.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.16.9 (fba98fc)

- Steps to reproduce:
    1. Open https://twitter.com/ (tab 1)
    2. Middle two links on the page, which causes two new tabs to open (tabs 2 and 3)
    3. Switch focus to tab 3
    4. Switch focus to tab 2 and then close it

- Actual result:
Focus is given to tab 3 (NOT tab 1, which is the parent)

- Expected result:
Focus is given to tab 1 (the parent, aka the opener)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Showing selection is parent
![image](https://user-images.githubusercontent.com/4733304/27019696-963f7c04-4eef-11e7-8430-6d76c8533e87.png)

- Any related issues:

**Comment by bsclifton** [comment]
cc: @BrendanEich

**Comment by bsclifton** [comment]
[Here's the line w/ the problem](https://github.com/brave/browser-laptop/blob/3d0917c85a81c52d88384e086551978d2532df91/app/browser/reducers/tabsReducer.js#L55)
Parent only goes back to the parent if it was the last active tab

**Comment by bsclifton** [comment]
## Original behavior
**NEXT** - If you [look at older versions of the code](https://github.com/brave/browser-laptop/blob/0.13.0/js/state/frameStateUtil.js#L392),
you'll notice that we originally used this method.  This also seems to be the default behavior for Chrome.

## Introducing two new options
The **LAST_ACTIVE** and **PARENT** options were introduced when @NejcZdovc fixed https://github.com/brave/browser-laptop/issues/6553 with PR
https://github.com/brave/browser-laptop/pull/6573 ([implementation can be seen here](https://github.com/brave/browser-laptop/blob/af7ef42ad622f899312a38bdd0e2138154393627/js/state/frameStateUtil.js#L555)).
With these new options, it's important to note the default is now **PARENT** and is being stored in the preferences.

## Changing the default behavior
This logic was moved from frameStateUtil (renderer process) to the tabsReducer (browser process) with PR https://github.com/brave/browser-laptop/pull/9023.
When this was done, the **PARENT** option has its behavior changed. Instead of always jumping back to the parent frame, it's now only only going to the parent IF the parent was the last active tab. Otherwise, it would default to the next tab.

## Proposed fix
To fix this I'd like to restore the **PARENT** option to always open the parent tab ID, like it used to.  I have made the change needed and the tests work as expected. (side note: I'm not always seeing openerTabId be set)

**Comment by bsclifton** [comment]
BTW - If we'd like to change the default behavior (which is currently **PARENT**), let's open up a new issue 😄

**Comment by luixxiul** [comment]
The fix does not work when you open tabs with different domains. Please open the gif below and reload the tab to repeat it.

![a](https://user-images.githubusercontent.com/3362943/27371977-d91ba8bc-569d-11e7-8889-aa9865914184.gif)

If the opened tab has the same domain as the parent tab does, the setting works. See:

![a](https://user-images.githubusercontent.com/3362943/27372064-3367db06-569e-11e7-9b0a-31271ba4a136.gif)

**Comment by srirambv** [comment]
Verified same behavior on Windows as @luixxiul mentioned

**Comment by bridiver** [comment]
this needs the exact URLs/links to replicate. Links that appear to work the same may actually take completely different paths inside chromium

**Comment by luixxiul** [comment]
This is the first one: https://twitter.com/CryptoPressNews/status/877422990140424192
This is the second one: https://twitter.com/TheEconomist/status/877422283966615552

**Comment by LaurenWags** [comment]
Verified same behavior as reported by @luixxiul on MacOS
