### ISSUE TITLE
Surfingkeys extension problems

### ISSUE THREAD

**Issue by Kudlaty01** [brave/browser-laptop#9396]
- Did you search for similar issues before submitting this one?
Yes, but still not working
- Describe the issue you encountered:
When trying to run the extension, it enables with other ones installed by me (e.g. cVim)
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Debian 8
- Brave Version (revision SHA):
7b76b6afcbe980ba5f02a5f31ffbe173ec4ee6d9
- Steps to reproduce:
As in the blog tutorial:
    1. npm install
    2. ced gfbliohnnapiefjpjlpjnehglfpaknnc
    3. extensions.js modification
    4. npm run watch && npm start
    
- Actual result:
new tab is constantly reloading, extension shortcuts do nothing, no extenion button in the menu bar next to the address bar
- Expected result:
exactly the opposite
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
previously didn't delete the `.config/brave-development`, but this time did it
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
I think so
- Extra QA steps: 
    none
- Extra info:
  The terminal output is as follows:
> TypeError: Cannot read property 'formatForDisplay' of undefined
    at fixDisplayURL (/home/<user>/Pobrane/Software/browser/brave/browser-laptop/app/browser/tabs.js:311:40)
    at createNavigationState (/home/<user>/Pobrane/Software/browser/brave/browser-laptop/app/browser/tabs.js:324:18)
    at WebContents.tab.on (/home/<user>/Pobrane/Software/browser/brave/browser-laptop/app/browser/tabs.js:447:51)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

**Comment by Kudlaty01** [comment]
On a totally fresh installation (removed directory and cloned again and removed `.config/brave-development`):
> [24596:24622:0612/122836.899665:ERROR:service_manager.cc(158)] Connection InterfaceProviderSpec prevented service: content_browser from binding interface: IPC::mojom::ChannelBootstrap exposed by: content_renderer

**Comment by bsclifton** [comment]
When we officially move to [brave-core](https://github.com/brave/brave-browser), we should have on-par extension support with Chromium
