### ISSUE TITLE
Closing a new tab opened from a pinned tab sets focus on wrong tab and shows blank page

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9397]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Closing a new tab opened from a pinned tab sets focus on wrong tab and shows blank page

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
Muon	4.0.3

- Steps to reproduce:
    1. Have 3 pinned tabs
    2. Open a link by clicking on the mouse wheel button from the first pinned tab
    3. Close the new tab, focus is set to the third pinned tab and it shows blank, hover over that shows the page content
    4. Switch to first pinned tab, right click on any link and open in a new tab
    5. Close the new tab, focus is again set to the third pinned tab and still shows blank screen, hover over the tab shows the page content 
    
- Actual result:
Closing a new tab opened from a pinned tab sets focus on wrong tab and shows blank page

- Expected result:
Should switch to original parent tab and show the content properly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
~~Not checked~~
Edit: its the same issue on 0.15.314 (CR58) as well

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![blanktab](https://user-images.githubusercontent.com/17010094/27031762-86464d6c-4f69-11e7-9761-bb9b4c51ac0a.gif)

- Any related issues:
#9395

**Comment by bsclifton** [comment]
This was likely fixed with https://github.com/brave/browser-laptop/issues/9506
