### ISSUE TITLE
Tab Label Rendering Issue

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9398]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab labels have an issue with rendering where previous values may not be cleared properly. As a result, this can paint two labels in the place of one.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop (Windows?)

- Brave Version (revision SHA):
0.16.9

- Steps to reproduce:
_TBD_
    
- Actual result:
Labels become unreadable.

- Expected result:
Labels remain legible and clear.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![image](https://user-images.githubusercontent.com/815158/27039144-b327122e-4f52-11e7-8ef0-cd9f69798908.png)

**Comment by bsclifton** [comment]
cc: @cezaraugusto @luixxiul

**Comment by jonathansampson** [comment]
I believe this is related to the general tab-rendering issue where labels are made up of transparent text, masking a gradient background. We need to move to using a pseudo-element to achieve the fade effect. This requires a little work considering we need to accomodate hoverd, non-hovered, theme colors, non-theme colors, private tabs, and public tabs.

**Comment by bsclifton** [comment]
@jonathansampson IIRC, these issues would also be resolved with that same fix:
Tabs No Longer Show Full-Color Emoji #8414
Tab title often isn't updated until the cursor is moved over it or tab focus is changed #7765

**Comment by jonathansampson** [comment]
@bsclifton I believe that is correct.

**Comment by cezaraugusto** [comment]
@jonathansampson isn't this related to the improvement we talked last Sunday? if so I think you are very close btw.

++ for @bsclifton findings. If above is true I agree they'll be fixed by too.

**Comment by jonathansampson** [comment]
@cezaraugusto It is. I should have that wrapped up very soon.
