### ISSUE TITLE
IMGUR Images on Reddit

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9402]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Images on Reddit are prevented from loading. As an example, visit [this post](https://www.reddit.com/r/BATProject/comments/6gu64r/president_brendan_eich_june_13_nyc_conference/) and note the lack of an IMGUR image. Open the same page in another browser to see the image.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.16.9

- Steps to reproduce:
1. Navigate to [https://www.reddit.com/r/BATProject…brendan_eich_june_13_nyc_conference/](https://www.reddit.com/r/BATProject/comments/6gu64r/president_brendan_eich_june_13_nyc_conference/)
    
- Actual result:
Image is prevented from loading.

- Expected result:
Image loads.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

**Comment by luixxiul** [comment]
By enabling 3rd party cookie the picture is displayed.

**Comment by DivineOmega** [comment]
I can confirm I've been seeing this issue for a while and can confirm that @luixxiul's work around does the trick.

**Comment by jonathansampson** [comment]
Nice find, @luixxiul! For a more permanent solution, we may want to add a specific exception for the Reddit->IMGUR relationship, rather than allowing all third party cookies.

**Comment by jonathansampson** [comment]
Duping to #5861
