### ISSUE TITLE
sync objectsById should be cleared when browser quits

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9405]
since the cache gets rebuilt when sync starts, there is no need to write it to disk

test plan:
1. start pyramid 0, enable sync
2. bookmark some sites
3. close the browser
4. you should not see 'objectsById' in the session-store-1 file

**Comment by luixxiul** [comment]
@diracdeltas is this what is expected?

![clipboard01](https://user-images.githubusercontent.com/3362943/28628030-6e82238c-725e-11e7-82a6-7dcbece07c50.jpg)

**Comment by diracdeltas** [comment]
@luixxiul yup!
