### ISSUE TITLE
File picker does not function on Windows Server Core

### ISSUE THREAD

**Issue by lewellyn** [brave/browser-laptop#9409]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
File upload buttons do not open a file selector.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows Server 2016 Core (specifically, Windows Hyper-V Server 2016)

- Brave Version (revision SHA):
fba98fc

- Steps to reproduce:
    1. Visit a page with a file upload field.
    2. Click the "Choose File" button.
    
- Actual result:
No user-visible action. No ability to select a file.

- Expected result:
File Open dialog or similar file picker should appear to allow the user to select a file.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
N/A

- Any related issues:
None found.

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
