### ISSUE TITLE
pinned audio tab keeps reopening itself

### ISSUE THREAD

**Issue by mokele** [brave/browser-laptop#941]
I have a tab where I was listening to a podcast audio file randomly and periodically reopening itself. It takes maybe half an hour or so, but it always comes back, and starts playing the file. I originally unpinned it, then closed it. Everything time it shows up again it comes back pinned, and I have to again unpin it to close it.

The favicon when listening to an audio file is also non-existent so looks very strange as an invisible pinned tab (http://cl.ly/3u1S3f1U2a0T)

Unfortunately due to the annoyance of it playing audio every time it comes back, I have to stop using brave for the time being :(

`Version: 0.7.16
Electron: 0.36.8
libchromiumcontent: 47.0.2526.110`

**Comment by bbondy** [comment]
Would you be able to send me your `session-store-1` file from `%appdata%\Brave` on Windows or from  `~/Library/Application Support/Brave/` on OSX? It'll contain a list of your bookmarks and other data at `https://github.com/brave/browser-laptop/blob/master/docs/state.md` but having that will allow me to reproduce your problem and fix it.  It's probably best if you email it to `brian@brave.com`.

**Comment by twisterghost** [comment]
I don't have any data to add, but can say I was seeing this too with Google Music on OSX. When I have access to that machine again I can try to get a store file dump.

**Comment by twisterghost** [comment]
Just checked my `session-store-1` file, don't want to post it/mail it (without at least scrubbing urls), but can say that the previously pinned tab in question still was tagged as "pinned" in the data file. Manually deleting that and restarting the browser seems to have fixed it so far. Perhaps there is an issue with unpinning tabs not persisting their new state?

**Comment by mokele** [comment]
I had to sift through session-store-1 to find the items associated with the associated tab and emailed it over. It didn't look like anything there immediately jumped out as relevant to a bug. Seems maybe audio media specific since @twisterghost mentioned google music and I was listening to an mp3

**Comment by butlermatt** [comment]
I'm having the same issue, specifically same as @twisterghost. Mac OS X, Brave 0.8, and a Pinned Google Music tab keeps re-opening itself. I unpin, close the tab. It will randomly (often within a minute) reopen itself as a pinned tab. Trying to unpin, close the window and then relaunch the browser it remains in the pinned tabs as well.

**Comment by luixxiul** [comment]
Does this still persist?

**Comment by butlermatt** [comment]
Sorry for the lack of follow up. I have not seen this issue persist in a number of recent releases. Unfortunately I can't specifically call which release had resolved it.

**Comment by luixxiul** [comment]
I see. If someone encounter this again in the latest version please leave comments. Closing for now.

**Comment by mokele** [comment]
I also did not see this behaviour the last time I used Brave
