### ISSUE TITLE
titleMode does not activate reliably

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9410]
Aside from edge cases like new tab page, title mode once activated should always be shown when mouse is not over navigation chrome, and be hidden (visible urlbar) when mouse is over it.

Given the above rule, at this moment we have two issues with titleMode:

**on macOS**
1. Have the window not maximized
2. Move mouse over navigation content.
3. urlbar is active, that's ok
4. Move mouse out of window

**Result:** 
urlBar is still active

**Expected**
Given the mouse is not over navigation content, titleMode should be active (urlbar should be hidden)

**on Windows**
1. Have the window not maximized
2. Move mouse over navigation content.
3. urlbar is active, that's ok
4. Move mouse out of window
5. titleMode is active, that's ok 
6. Move mouse from top of the window up to website's title

**Result:** 
titleMode is still there, you can't hit urlbar

**Expected**
Given the mouse is over navigation content, titleMode should be removed (urlbar should be active)

**Comment by srirambv** [comment]
![autohideurl](https://user-images.githubusercontent.com/17010094/30648144-fa2abaf4-9e3a-11e7-90d5-6d73632b2ea8.gif)
@cezaraugusto  This doesnt seem right yet on Windows.

**Comment by srirambv** [comment]
@cezaraugusto This is still an issue on Windows. Mouse over tabs bar reveals URL bar but when moved quickly goes back to title mode. With mouse outside the window hover back on browser doesn't switch to URL mode and remains in title mode

**Comment by Jacalz** [comment]
Yeah huge issue using windows 10 on my computer

**Comment by bsclifton** [comment]
@srirambv IIRC, because of this issue we set title mode as OFF by default (for new installs).  Can you confirm this?

**Comment by srirambv** [comment]
@bsclifton Yes this is an annoying issue on Windows when title mode is enabled. Both on new profile or on update.  In fact it is quite impossible to click in URL when title mode is enabled as the URL mode only comes when the mouse is on tabs bar. Once it moves out of URL bar it switches back to title mode. Only shows for new tabs, existing tabs with pages loaded its impossible to click in URL bar using mouse. Have to use keyboard shortcut.

**Comment by bsclifton** [comment]
Removing milestone as this issue is not release blocking. See above input @cezaraugusto

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/bug-report-always-show-the-url-bar-function/13984

**Comment by cezaraugusto** [comment]
I don't have time to look at this so I'm un-assigning me, leaving it open for grabs.

For the people interested in solving this bug:

We have a CSS property called `-webkit-app-region: drag;` (`navigationBar.less` is the go-to file to find it) which allows the window chrome (the gray area) to be draggable. While this works fine, the property cancels all mouse events in the area it covers, which is why the `onMouseEnter` event is never fired (and the titleMode never disappears).

This is a known bug both in Chromium and Electron but hopefully, some tweaks in urlbar/titemode sizing and elements rearrangements might fix this.

The plan is to:

- Keep the window draggable as it is now;
- Re-organize the drag property so we could access via mouse events the urlbar.

**Comment by cezaraugusto** [comment]
also note that this is a Windows-only bug.

**Comment by MargarytaChepiga** [comment]
I was trying to take a look at this, but I am not able to reproduce it. I am using Windows 10 x64.
