### ISSUE TITLE
Place the URL in the omnibar during incremental search

### ISSUE THREAD

**Issue by dandv** [brave/browser-laptop#9418]
Use case: I want to search in my URL history for a URL, then quickly copy it to the clipboard (for pasting in a form, in another application etc.) Brave makes this impossible - I have to actually open a new tab, then open URL in the new tab. Chrome makes it easy: when I press up/down arrow, the URL is placed in the omnibar, ready to be copied:

![omnibar incremental search should place the url in the omnibar](https://user-images.githubusercontent.com/33569/27071010-1c26837c-4fd0-11e7-87af-8e69bab661b1.gif)

In Brave, this doesn't work:

![brave omnibar incremental search](https://user-images.githubusercontent.com/33569/27071122-81c0f852-4fd0-11e7-9cd5-e69ca39219c0.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04.2

- Brave Version (revision SHA):
fba98fcb091b3abfa18aba7c6c0db0c7aa343589

- Steps to reproduce:
    1. Type part of a URL in the omnibar
    2. Try to copy the URL you're looking for to the clipboard without actually nagivating to it
    
- Actual result:
Brave shows the URL in the dropdown, but only the typed portion of it in the omnibar

- Expected result:
The browser should place the entire URL in the omnibar for easy copy/paste

- Will the steps above reproduce in a fresh profile?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
I think this is the same issue as https://github.com/brave/browser-laptop/issues/7088.

- Steps to reproduce:
    1. Open some pages on https://twitter.com, including https://twitter.com/i/notifications
    2. Open new tab
    3. Hit `tt` (NOT `tw`, `twi`, etc)
    4. Make sure https://twitter.com appears in the suggestions list
    5. Select it with the down arrow key on your keyboard
    6. Hit the right arrow key to autocomplete the URL
    
- Actual result: Nothing happens

**Comment by dandv** [comment]
I support #7088 and I think my issue is different - for feature parity with the Chrome UX, the URL should be copied to the omnibar when pressing up/down arrow, even before pressing the right arrow.

**Comment by luixxiul** [comment]
sorry I meant to say the issue seems to have the common root cause.

**Comment by stripedpajamas** [comment]
In trying to reproduce this I found that Brave does update the omnibar if only the suffix needs updating... that is (building off the gif example), if `github` was typed instead of `buzzf`, hovering and moving down fills in the omnibar with that link (so it can be copied or edited). 

It's only when the prefix of a url would need to be updated that Brave doesn't update the omnibar. 

It's coded like this (https://github.com/brave/browser-laptop/blob/master/app/renderer/reducers/urlBarReducer.js#L226 I think). Parity with Chrome UX would be to set the omnibar to whatever is selected in the suggestions box.

**Comment by stripedpajamas** [comment]
Actually I think it's https://github.com/brave/browser-laptop/blob/master/app/renderer/reducers/urlBarReducer.js#L286 and https://github.com/brave/browser-laptop/blob/master/app/renderer/reducers/urlBarReducer.js#L271 that we're talkign about, not 226.

**Comment by joelwass** [comment]
PR open https://github.com/brave/browser-laptop/pull/14406
