### ISSUE TITLE
XE.com not rendered properly 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9419]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
XE.com not rendered properly due to CSS file being blocked by HTTPSE

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
Muon	4.0.3

- Steps to reproduce:
    1. Visit http://xe.com, page nor rendered properly
    2. Disable HTTPSE, page loads properly
    3.
    
- Actual result:
XE.com not rendered properly 

- Expected result:
Should load properly

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/brave-not-rendering-currency-exchange-website-xe-com-correctly/3863

**Comment by diracdeltas** [comment]
subticket of #9649

**Comment by diracdeltas** [comment]
fixed by latest https://github.com/brave/https-everywhere-builder, update will be pushed shortly
