### ISSUE TITLE
Redux component - BookmarksToolbar and BookmarkToolbarButton

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9421]
**Describe the issue you encountered:**
Converts `bookmarksToolbar` and `bookmarkToolbarButton` into redux.

**Comment by kjozwiak** [comment]
@NejcZdovc is there a test case/test plan that can be used to test this particular fix? If there's no way to test this, please add the `QA/no-qa-needed` label.

**Comment by NejcZdovc** [comment]
@kjozwiak done
