### ISSUE TITLE
Can't reopen windows after closing browser

### ISSUE THREAD

**Issue by Raindeer44** [brave/browser-laptop#9422]
- Did you search for similar issues before submitting this one? 
    Yes, didn't see any.

- Describe the issue you encountered:

    After closing the browser with Alt+Q or the X close button, then reopening the browser, Ctrl+Shift+T doesn't reopen the last closed window or even the last tab like I would expect from other browsers. This is very annoying when I had an important tab open that is buried in my history to go and find.

- Platform (Win7, 8, 10? macOS? Linux distro?): 
    Windows 7

- Brave Version (revision SHA): 
    0.16.9 fba98fc

- Steps to reproduce:
    1. Have tabs open
    2. Close browser
    3. Reopen Browser
    4. Press Ctrl+Shift+T
    
- Actual result:
    Nothing

- Expected result:
    Reopen last-closed window

- Will the steps above reproduce in a fresh profile? If not what other info can be added? yes, just installed fresh in a VM.

- Is this an issue in the currently released version? Yes

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
    I do notice that tabs which are reopened do so without the history attached. By this I mean if I close a tab, then reopen it with Ctrl+Shift+T, there's no history that the back button can access. It seems to dissociate.

**Comment by luixxiul** [comment]
The issue is tracked here: https://github.com/brave/browser-laptop/issues/4575

thanks for your report!
