### ISSUE TITLE
Browser tab hangs when attempting to log into Zillow via Google OAuth

### ISSUE THREAD

**Issue by dmonay** [brave/browser-laptop#9424]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Browser fails to log into Zillow using Google credentials.

- Platform (Win7, 8, 10? macOS? Linux distro?):
`macOS Sierra version 10.12.5`
- Brave Version (revision SHA):
 ```
Brave: 0.16.6 
rev: 51de9af083a50b9d5ceaec34af35ea3c1c9696fc 
Muon: 4.0.1 
libchromiumcontent: 59.0.3071.86 
V8: 5.9.211.31 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 16.6.0 
os.arch: x64
```
- Steps to reproduce:
    1. Go to zillow.com
    2. Click "Sign in"
    3. Click the Google icon
    4. A new tab will open. This tab will hang on the auth redirect, with the url:
`https://accounts.google.com/o/oauth2/auth?redirect_uri=xxxx`
    
- Actual result:
Fails to log in and hangs.
- Expected result:
The redirect happens instantly and allows me to authorize Zillow and log in.
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

- Any related issues:
Related to https://github.com/brave/browser-laptop/issues/6811 and https://github.com/brave/browser-laptop/issues/9356

**Comment by Yuripetusko** [comment]
I am wondering if I have similar issue. This might be due to the fact that google auth needs to be opened in popup but Brave opens it in new tab instead. It is the issue if you use firebase `signInWithPopup` method

**Comment by dmonay** [comment]
That would make sense. @luixxiul is there an update on this?

**Comment by luixxiul** [comment]
there are some issues which seems to be related / share the root cause, such as https://github.com/brave/browser-laptop/issues/9610.
