### ISSUE TITLE
File downloads crash Brave on Windows Server Core

### ISSUE THREAD

**Issue by lewellyn** [brave/browser-laptop#9435]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
File downloads crash the browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows Server 2016 Core (specifically, Windows Hyper-V Server 2016)

- Brave Version (revision SHA):
fba98fc

- Steps to reproduce:
    1. Visit a page with a file download link.
    2. Click the download link.
    
- Actual result:
Browser crashes without any dialog or other grace.

- Expected result:
File should download

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
N/A

- Any related issues:
Potentially #9409

**Comment by srirambv** [comment]
Verified on Windows 10 but not on Windows Server

**Comment by bsclifton** [comment]
Moving to `0.22.x`; we're going to have `0.21.x-C65` only contain the Chromium upgrade 😄 👍

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0

**Comment by kjozwiak** [comment]
This issue will appear in the release notes via #10653 which has the same fix.
