### ISSUE TITLE
Honey widget dropdown only closes on second click on the widget

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9438]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Honey widget dropdown only closes on second click on the widget

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.1
rev	84dbc8e
Muon	4.0.3

- Steps to reproduce:
    1. Clean install 0.17.1
    2. Enable Honey and LastPass from `about:preferences#extensions`
    3. Visit http://www.udemy.com and click on Honey, ensure the widget dropdown is shown
    4. Click on Lastpass, widget dropdown is not closed, Lastpass widget is shown on top of honey dropdown
    5. Click on Shields menu, LastPass widget window is closed, honey is still retained 
    
- Actual result:
Honey widget dropdown only closes on second click on the widget

- Expected result:
Should close when clicked outside or when clicked on a different UI element 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![honey](https://user-images.githubusercontent.com/17010094/27122897-081ada3a-50e4-11e7-827a-28abd735e1cf.gif)

- Any related issues:
cc: @kevinlawler

**Comment by bbondy** [comment]
Removing milestone, we can live with that until someone fixes.
