### ISSUE TITLE
Turn off shields on about:safebrowsing shows about:error page instead of loading the actual site and shields become inactive

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9441]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Turn off shields on about:safebrowsing shows about:error page instead of loading the actual site and shields become inactive

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.1
rev	84dbc8e
Muon	4.0.3

- Steps to reproduce:
    1. Clean install 0.17.1
    2. Visit http://downloadme.org, ensure `about:safebrowsing#http://downloadme.org/` window is shown
    3. Disable Shields, `about:error` page is shown, but URL is still showing `about:safebrowsing#http://downloadme.org/`, Due to `about:error` shields menu is disabled
    4. Open a new page in the previous tab or a new tab, shields for that page is opened 
    
- Actual result:
Turn off shields on `about:safebrowsing ` shows `about:error` page instead of loading the actual site and shields become inactive

- Expected result:
Should just load the site and not `about:error` when shields is turned off

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![safebrowsing](https://user-images.githubusercontent.com/17010094/27124581-74fc157e-50e9-11e7-8e69-4be6571bd847.gif)

- Any related issues:
cc: @diracdeltas

**Comment by diracdeltas** [comment]
note that this works on master

**Comment by diracdeltas** [comment]
it shows about:error because downloadme.org doesn't exist anymore, not because of Brave

**Comment by bbondy** [comment]
Moving to 0.18.x, lmk if that's a problem @diracdeltas  thx.

**Comment by luixxiul** [comment]
I think we would display then 404 error page.

**Comment by bbondy** [comment]
should be working in 0.18.x so marking as closed in this milestone.
