### ISSUE TITLE
Redux component - Main

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9452]
**Describe the issue you encountered:**
Convert `Main` into redux component.

**Comment by luixxiul** [comment]
QA/steps-required

**Comment by kjozwiak** [comment]
@NejcZdovc is there a test case/test plan that can be used to test this particular fix? If there's no way to test this, please add the `QA/no-qa-needed` label.

**Comment by NejcZdovc** [comment]
@kjozwiak this is mani component and I think that don't need QA
