### ISSUE TITLE
Right click copy image in Slack doesn't copy into clipboard 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9459]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Right click copy image in Slack doesn't copy into clipboard 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Found on Windows 10 x64, Confirmed on macOS by @LaurenWags 

- Brave Version (revision SHA):
Brave	0.17.1
rev	84dbc8e
Muon	4.0.3

- Steps to reproduce:
    1. Login to Slack 
    2. Right Click on any image and select copy image
    3. Open new github issue and right click paste, nothing happens
    
- Actual result:
Right click copy image in Slack doesn't copy into clipboard 

- Expected result:
Should copy paste properly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by eljuno** [comment]
Related to #7388?

**Comment by srirambv** [comment]
Closing as dupe of #7388 and adding it to milestone as copy paste is a pretty basic functionality that is broken

**Comment by LaurenWags** [comment]
removing milestone as this is a duplicate of https://github.com/brave/browser-laptop/issues/7388 which is still open and does not currently have a milestone assigned.
