### ISSUE TITLE
clicking menu bar items in 0.16.x and 0.17.1 does nothing

### ISSUE THREAD

**Issue by dillbyrne** [brave/browser-laptop#9470]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Clicking on menu items does nothing.

- Platform (Win7, 8, 10? macOS? Linux distro?):
kde 4.14.2 on debian 8 x64

- Brave Version (revision SHA):

   Name	Version
Brave	0.16.9
rev	fba98fc
Muon	4.0.2
libchromiumcontent	59.0.3071.86
V8	5.9.211.31
Node.js	7.9.0
Update Channel	dev
os.platform	linux
os.release	4.9.0-0.bpo.1-amd64
os.arch	x64

- Steps to reproduce:
    1. Start browser
    2. click on a menu item or show the menu and click on a menu item
    

- Actual result:
Nothing happens

- Expected result:
The menu item should show the relevant drop down menu.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
 Yes. I tried several versions of the browser  each time deleting ~/.config/brave . 

  It was present in 0.16.x  and  in 0.17.1 releases that I tested. 
 However the menu works as expected in the following release.

    Name	Version
 Brave	0.15.314
 libchromiumcontent	58.0.3029.110
 Muon	3.0.202
 Node.js	7.9.0
 os.arch	x64
 os.platform	linux
 os.release	4.9.0-0.bpo.1-amd64
 rev	75ffa36
 Update Channel	dev
 V8	5.8.283.38

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes in my case

- Any related issues:
#5086 may be related as I am also experiencing that with the current version on kde4 in debian 8

- Additional Information
I do not have any global menu kde widgets in use.
I have tested it with both the oxygen and qtcurve widget styles to be sure and it made no difference. It appears the regression may have been introduced in the 0.16.x releases.

**Comment by luixxiul** [comment]
I confirmed the issue on Debian (MATE).

**Comment by bsclifton** [comment]
Related to https://github.com/brave/muon/pull/161 and Chromium 59 update... Looking into this

**Comment by oddballhero** [comment]
Confirmed this issue on Debian Mate and Fluxbox (multiple different machines).

**Comment by eljuno** [comment]
+4 [from community](https://community.brave.com/t/linux-mint-17-2-brave-version-0-16-6-0-16-9-and-main-menu-doesnt-work/3727)

**Comment by bsclifton** [comment]
For some reason, `Release()` is being called on the MenuRunner object. Chromium 59 introduced async menus, which may have made the problem obvious.  We might need to capture an instance of the MenuRunner so that it doesn't call destructor when it goes out of scope. Will continue digging...

**Comment by bsclifton** [comment]
Heads up folks!  The fix for this issue has been pushed.  Please use your package manager of choice to update to the latest release, which should be `0.16.11` 😄 👍 

Please let me know if you are having trouble updating

**Comment by oddballhero** [comment]
Works in Debian Fluxbox, does not work with Debian Mate, at least for me.

**Comment by Liunkae** [comment]
Users are still having issues. Tracking in #9606.

**Comment by luixxiul** [comment]
> updated it to 0.16.12 and menu bar not working again

Confirmed on Debian on Gnome

with 0.16.12, 72624a2

**Comment by luixxiul** [comment]
Fixed on 0.17.4 :-)

**Comment by dillbyrne** [comment]
Fixed on Debian 8 KDE with 0.17.4. :+1:

**Comment by oddballhero** [comment]
Works in Debian Stable Fluxbox and Debian Stable Mate with Brave 0.16.13 without different issue seen in 0.16.11.
