### ISSUE TITLE
"History" disappeared from menu

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#9471]
- Did you search for similar issues before submitting this one?
Yes. But maybe I missed the existing issue.

- Describe the issue you encountered:
History not shown in menu. Can not click on it.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 8.1

- Brave Version (revision SHA):
0.17.1 (6482f15)

- Steps to reproduce:
    1. Show menu by click `Alt` on keyboard.
    2. Noticed that `History` is not there.
    
- Actual result:
There's no `History`. Only empty space.

- Expected result:
`History` and its sub-menu is shown.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-history-menu-missing](https://user-images.githubusercontent.com/25360853/27152749-130da4f0-5179-11e7-9653-017f2ec90daa.png)

- Any related issues:

**Comment by bsclifton** [comment]
cc: @ayumi 
Could this be related to https://github.com/brave/browser-laptop/pull/9191?

**Comment by ayumi** [comment]
@eljuno thanks for finding this! I've repro'd on Windows 10, Brave 0.17.2 839e68b
STR:
- Fresh Brave; activate system app menu with Alt; looks normal
- Open webpage in new tab
- Close the tab
- Alt; system app app menu is missing History

@bsclifton likely related to #9191. I developed on MacOS and the windows code path is slightly different.

**Comment by bsclifton** [comment]
Marking as `release-notes/exclude` since this was introduced (and then fixed) in the same release 😄
