### ISSUE TITLE
Empty Menu Item

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9478]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
There appears to be an empty menu item.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.17.1

- Steps to reproduce:
    1. Reveal menu (press alt)
    
- Actual result:
Empty item between _View_ and _Bookmarks_.

- Expected result:
No empty item.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Preview

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![extra-menu-item](https://user-images.githubusercontent.com/815158/27161490-592f2d88-5141-11e7-8407-e70818cf8692.gif)

_Generated Markup_:

```html
<div class="menubar">
    <span class="menubarItem" data-index="0">File</span>
    <span class="menubarItem" data-index="1">Edit</span>
    <span class="menubarItem" data-index="2">View</span>
    <span class="menubarItem selected" data-index="3"></span>
    <span class="menubarItem" data-index="4">Bookmarks</span>
    <span class="menubarItem" data-index="5">Shields</span>
    <span class="menubarItem" data-index="6">Window</span>
    <span class="menubarItem" data-index="7">Help</span>
</div>
```

**Comment by darkdh** [comment]
dup #9471
