### ISSUE TITLE
Update bitwarden to latest from chrome web store

### ISSUE THREAD

**Issue by kspearrin** [brave/browser-laptop#9479]
- Did you search for similar issues before submitting this one? Yes

- Describe the issue you encountered:
bitwarden is out of date. Update to version 1.13.x from chrome web store.

- Platform (Win7, 8, 10? macOS? Linux distro?): Win 10

- Brave Version (revision SHA): 0.17.1dev

- Steps to reproduce:
    1. Enable bitwarden.
    2. Check version
    
- Actual result:
See version 1.10.0

- Expected result:
See version 1.13.x

- Will the steps above reproduce in a fresh profile? If not what other info can be added? n/a

- Is this an issue in the currently released version? no

- Can this issue be consistently reproduced? yes

cc @bsclifton 

ref: https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=en

**Comment by kspearrin** [comment]
I can do future PRs for this after I see how you do it this time.

**Comment by bsclifton** [comment]
Assigning @jonathansampson per our convo on Slack 😄  (several extensions need updating)

**Comment by bsclifton** [comment]
@kspearrin I'm going to close this issue (sorry for the inactivity)

We have a separate repository, vault-updater (which you've already committed to).  There is an npm task there which needs to be ran on our servers which downloads the latest manifest and uploads it to our AWS.  This is something only employees have access to (and we're still working on automating it)

**Comment by kspearrin** [comment]
@bsclifton I see bitwarden finally made it into the production build of brave! Great news, however, it doesn't work because it's still using a nearly 5 month old version (v1.10.0) that is no longer compatible with our API servers.

This is why I opened this issue. It looks like it was never updated. :(

**Comment by kspearrin** [comment]
Opened https://github.com/brave/vault-updater/issues/46

**Comment by jonathansampson** [comment]
@kspearrin I started using the Chrome Store version yesterday while working on the _case of the missing icon_. So far, it seems to be working well. Would you be available to assist with testing to ensure I am not missing anything?

**Comment by kspearrin** [comment]
@jonathansampson I'd love to test things out. I am running latest brave on macOS using the "preview releases" setting. Is there something I can get through that channel or do I have to load a local branch build?

**Comment by jonathansampson** [comment]
@kspearrin You can definitely test with that release. Do you have Skype? If so, we could hop on there and run through the process of testing the latest bits in your instance of Brave (no need to run a local branch).

**Comment by kspearrin** [comment]
Please send me your skype username. You can direct message me on twitter @kylespearrin

**Comment by jonathansampson** [comment]
@kspearrin Incoming :)
