### ISSUE TITLE
replace list icon with Brave logo in urlbar for about pages

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9483]
like our Opera friends:

<img width="350" alt="screen shot 2017-06-15 at 4 40 10 am" src="https://user-images.githubusercontent.com/4672033/27170584-cd723eae-5184-11e7-924c-4e31dfcce3b7.png">

/cc @bradleyrichter

**Comment by kjozwiak** [comment]
Closing as `muon` is being deprecated and this has already been solved under `b-c`. Example:

![screen shot 2018-11-04 at 6 50 08 pm](https://user-images.githubusercontent.com/2602313/47971772-9372ef00-e062-11e8-9a4f-f222197560d0.png)
