### ISSUE TITLE
Drag and add as bookmark inside a folder doesn't list the bookmark immediately

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9495]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Drag connection info button  to add as bookmark inside a folder doesn't list the bookmark immediately

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Create a bookmark folder
    2. Visit a site in a new tab
    3. Drag the connection info icon into the folder created in step 1 until the folder dropdown is shown
    4. Folder dropdown is  retained and shows empty, but bookmark star is added
    5. Close and reopen the folder, bookmark is shown
    
- Actual result:
Drag and add as bookmark inside a folder doesn't list the bookmark immediately

- Expected result:
Should list the bookmark immediately in the drop down or close the dropdown which is the current behaviour in the prod build

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No, Verified from 0.15.2 and the dropdown is closed once the bookmark is dragged and added into the folder

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![bookmark_folder](https://user-images.githubusercontent.com/17010094/27185370-0215d532-51dd-11e7-9032-da1528b0e503.gif)

- Any related issues:
cc: @bsclifton

**Comment by NejcZdovc** [comment]
@srirambv is this reproduce only on Windows?

**Comment by NejcZdovc** [comment]
It's working for me on macOS. Can you please try it again with the latest 0.17.x branch please?

**Comment by bbondy** [comment]
Still reproduces for me on macOS @NejcZdovc and it's consistent. To reproduce make sure folder stays open and drag on folder name.  Drag the little lock next to a site that you're on into the blank folder. 

Closing and opening the folder will then show it though, so this isn't a blocker. Moving it to 0.17.x.
It's just a refresh problem.

**Comment by pedrotp** [comment]
@NejcZdovc I'd be happy to tackle this one if any folks who know the codebase well can point me in the right direction and give me a bit of coaching/mentorship as I work through it

**Comment by KingAkeem** [comment]
Has this issue been resolved?

**Comment by bsclifton** [comment]
This is fixed with [brave-core](https://github.com/brave/browser-laptop)
