### ISSUE TITLE
Suggestions made, lost, and made again

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9498]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When typing "face" into the URL bar, a suggestion is made. Unfortunately, the suggestion doesn't match the `/^face/` pattern. The visual queue of a highlighted item however often results in me pressing <kbd>enter</kbd>, and thus going to an undesired website.

The initial false-suggestion is promptly lost (if I didn't press <kbd>enter</kbd>). Immediately thereafter, the proper suggestion is made.

The entire process takes less than a second. See below for a GIF, and individual frames.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.17.1

- Steps to reproduce:
    1. Type "face" into your URL bar
    
- Actual result:
Suggestions are made, lost, and made again.

- Expected result:
Suggestions should be made only once; facebook.com should be top suggestion (generally speaking)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
This wouldn't always repro for me; I would at times need to wait 10-15 minutes before trying again. I suspect we hold suggestions in memory, and they are at times garbage collected. Only then will the issue reproduce.

- Screenshot if needed:

![face-suggest](https://user-images.githubusercontent.com/815158/27194892-03a288c2-51ca-11e7-884d-dc9833743185.gif)

- Individual Frames

![01 9](https://user-images.githubusercontent.com/815158/27194912-138fd820-51ca-11e7-805c-9afe9fead664.png)
![02 10](https://user-images.githubusercontent.com/815158/27194915-13955c28-51ca-11e7-9393-2cf23d6e3a65.png)
![03 18](https://user-images.githubusercontent.com/815158/27194913-1393b2a6-51ca-11e7-8749-7e483bb98f55.png)
![04 21](https://user-images.githubusercontent.com/815158/27194914-139430aa-51ca-11e7-8800-ec16d6fbae33.png)

- Any related issues:

**Comment by diracdeltas** [comment]
i have also experienced this

**Comment by jonathansampson** [comment]
@diracdeltas This seems related to https://github.com/brave/browser-laptop/pull/13693, no?
