### ISSUE TITLE
incorrect hostname shown in titlemode when host is very long

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9500]
issue exists in 0.17.x but is fixed in 0.18.x by https://github.com/brave/browser-laptop/pull/9154

1. go to https://longextendedsubdomainnamewithoutdashesinordertotestwordwrapping.badssl.com/
2. mouse away from the urlbar to enter title mode
3. the origin is shown as 'longextendedsubdomainnamewithoutdashesinordertotestwordwrapping' instead of 'longextendedsubdomainnamewithoutdashesinordertotestwordwrapping.badssl.com'

**Comment by diracdeltas** [comment]
i verified that this is fixed by using node's url.parse instead of https://github.com/petkaantonov/urlparser/blob/master/src/urlparser.js, which we shouldn't use anyway because it appears to no longer be maintained

**Comment by luixxiul** [comment]
@cezaraugusto haven't you pushed a PR to fix that issue?
