### ISSUE TITLE
noscript allowing selective sites once doesn't invalidate the exceptions

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9505]
tested on master

1. disable scripts globally and go to https://jsfiddle.net/
2. click noscript icon. unselect all except jsfiddle.net and hit 'allow once'
3. close tab then open jsfiddle.net again
4. click noscript icon. it appears jsfiddle.net is still allowed.

**Comment by luixxiul** [comment]
dup #9150 ?

**Comment by diracdeltas** [comment]
@luixxiul i think it is the same issue, but the title of the other issue should say 'keeps allowing scripts' instead of 'keeps blocking scripts'?

**Comment by luixxiul** [comment]
Yes you are correct. I have misunderstood the dialog.

**Comment by diracdeltas** [comment]
closing as dupe of #9150
