### ISSUE TITLE
Closing the first tab of a window when restoring closes the entire window

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#9506]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When restoring a window on startup, closing the first tab while the other tabs are still loading will close the entire window

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/bf34c40b307528d9cf7f49fe0742f8955efb6000

- Steps to reproduce:
    1. Open Brave with a fresh profile
    2. Open 10 tabs with twitter.com
    3. Close Brave
    4. Re-open Brave and press cmd/ctrl-w as soon as the first tab appears
    
- Actual result:
Window closes

- Expected result:
Only the tab should close

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Verified on 0.17.11

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/closing-top-open-tab-shuts-down-brave/4359
