### ISSUE TITLE
cnet.com blocks Brave (laptop and iOS) from watching video content with ad blocking on.

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#951]
http://www.cnet.com/videos/apple-strikes-again-at-fbi-whats-next-in-the-iphone-hack-battle/

**Comment by bbondy** [comment]
Fixed, a new data file should be downloaded within a day. No code changes needed.

**Comment by bbondy** [comment]
The fix was just to update to new adblock definitions files.

**Comment by bbondy** [comment]
CC @garvankeeley @SergeyZhukovsky FYI this was a very big update with hundreds of rule changes, so be on the lookout for any new breakage.  Hopefully it's all better / newer / more accurate stuff though.

**Comment by garvankeeley** [comment]
was this an etag change, or a new version num for the file?

**Comment by bbondy** [comment]
new data file, so etag change.  You'll get it auto within a day (or sooner if you clean earlier).    Just making extra people aware in case you see fallout.
