### ISSUE TITLE
host is not parsed correctly in titleMode

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9510]
![pasted image at 2017_06_15 08_56 pm](https://user-images.githubusercontent.com/4672033/27209051-e00dad00-521f-11e7-9123-c14386bceb13.png)

Issues:

1. no host defined for about pages
2. Trailling colon for all urls

Issue found in 0.18.x sha 3535c8da0af977ffda9ddc974e9318c217cf5d74

Given this is related with security matters I'm labeling to 0.18.x itself given it is not reproducible in 0.17.x

/cc @diracdeltas 
/cc @srirambv for triage

**Comment by diracdeltas** [comment]
duplicate of #9503
