### ISSUE TITLE
Move bookmark text calculation into the state

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9517]
## Test plan

https://github.com/brave/browser-laptop/pull/10325#issue-248455456

----

**Describe the issue you encountered:**
Move calculation of bookmark width into state and calculate it only when bookmark is added/edited or favicon setting for bookmark toolbar is changes

#9030

**Comment by LaurenWags** [comment]
Bookmark overflow indicator is not always displayed:
![9517](https://user-images.githubusercontent.com/28145373/34541354-d6d304fe-f0a5-11e7-960a-7579b239f631.gif)

**Comment by NejcZdovc** [comment]
@LaurenWags I tried it with a fresh profile and imported bookmarks, but I can't reproduce it.

![jan-09-2018 12-23-54](https://user-images.githubusercontent.com/9574457/34718718-1167b510-f538-11e7-9846-a52fb2249ebb.gif)

**Comment by NejcZdovc** [comment]
ok I think that I found the problem. It's not working with the existing profile.
