### ISSUE TITLE
Support private tab bookmarks 

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#952]
Command + click on a bookmark remembers the session. I think it should also remember if the site was private.  There is a use case where private tab bookmarks are useful. And that's in cases that you don't want to remember anything in your session but you don't care about hiding that you go to the site.

@diracdeltas thoughts?

**Comment by diracdeltas** [comment]
This isn't any worse than the current behavior (in brave and other browsers), right? That is, when a site in private mode is bookmarked, it gets added to the regular bookmarks list. So probably +1.

**Comment by bbondy** [comment]
yep

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/910
