### ISSUE TITLE
Context menu not working for tabs toolbar

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9524]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Context menu not working for tabs toolbar
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
1007e8c
- Steps to reproduce:
    1. Right click on tabs toolbar (on empty space)
    
- Actual result:
You get an error
- Expected result:
Context menu opens
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
We may want to close this in favor of https://github.com/brave/browser-laptop/issues/8303

**Comment by NejcZdovc** [comment]
This are not the same, so we can't close this one. Comment left here https://github.com/brave/browser-laptop/pull/9525#issuecomment-309345570

**Comment by srirambv** [comment]
Works fine but need confirmation for https://github.com/brave/browser-laptop/pull/9525#issuecomment-309995764 if that the expected behavoir
