### ISSUE TITLE
Sync : missing bookmarks from import on other machine

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9529]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When importing a reasonably large number of bookmarks (>6000) the other machine which receives the sync does not have many of the bookmarks even after waiting for 20 minutes or so.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, Windows 10

- Brave Version (revision SHA):
0.17.3 (02a7878)

- Steps to reproduce:
    1. with clean profiles, sync two laptops with 0.17.3
    2. import a large number of bookmarks with nested upon nested folders
    3. check bookmarks in nested folders on device 2, notice they are missing in many cases
    
- Actual result:
Bookmark order is scrambled in places an many are missing.
Numerous (thousands) of similar errors appeared on the console indicating some sort of failure with AWS.

- Expected result:
the structure and contents of the first laptop should be matched by the second laptop

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Unsure due to prior hierarchy bug.

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="1858" alt="screen shot 2017-06-16 at 1 56 30 pm" src="https://user-images.githubusercontent.com/1434040/27240807-dcb89d64-529b-11e7-8b7c-579e142f04b3.png">
<img width="1146" alt="screen shot 2017-06-16 at 12 05 10 pm" src="https://user-images.githubusercontent.com/1434040/27240823-e694f9b8-529b-11e7-881b-0b45c22403df.png">

- Any related issues:

**Comment by LaurenWags** [comment]
Just experienced this with import on laptop and then laptop (MacOS) to Android sync. I had approximately 1200 bookmarks and not all of them made it to Android.

**Comment by diracdeltas** [comment]
may be worth trying this on master to see if it was fixed by some of the recent sync changes that are not in 0.17.x

**Comment by alexwykoff** [comment]
@diracdeltas  identical conditions for 0.19.0 (1007e8c)

**Comment by diracdeltas** [comment]
on master, i tried syncing ~6200 bookmarks. around 6100 of them were synced. it's not always the same bookmarks that are lost.

**Comment by alexwykoff** [comment]
correction to my prior post, the posts to aws have shown identical errors in the console and the same bookmarks in a certain folder i checked while testing were missing in both cases. 

upon inspection of the exported html files, indeed it was shown that different bookmarks had survived the sync.  😄

**Comment by alexwykoff** [comment]
migrated to https://github.com/brave/sync/issues/112
