### ISSUE TITLE
iheart.com website radios do not play

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#953]
From support:

http://www.iheart.com

**Comment by luixxiul** [comment]
Confirmed. This seems to be due to blocking some scripts which violate the CSP directive. Open Devtool and reload,

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-Dfz9LHfiGbhbi5p8YLt4zjwhoWGJzCyCzMeBNplMnRE='), or a nonce ('nonce-...') is required to enable inline execution.

and so on.

CC: @bbondy

**Comment by diracdeltas** [comment]
@luixxiul that's because you have noscript enabled, please turn it off before testing

**Comment by diracdeltas** [comment]
in Chrome, this requires flash to work. so i think it won't work in Brave until we support Flash

**Comment by luixxiul** [comment]
Closing for now
