### ISSUE TITLE
moving bookmark to a different folder on laptop is not synced to mobile devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9530]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When bookmark is moved from one folder to another on the laptop, the change is not synced to Android or iOS.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 

- Brave Version (revision SHA):
Brave	0.17.3
rev	02a7878
Muon	4.0.3

- Steps to reproduce:
    1. Create folders and bookmarks on laptop.
    2. Create folders and bookmarks on another device (I used Android and iOS devices)
    3. Create sync group on laptop and join on other devices.
    4. On laptop, navigate to a site that is not already bookmarked.
    5. Select the star in the URL bar.
    6. On the popup, select Done. You will see the bookmark added to the Bookmarks Toolbar. Wait and verify this is synced to Android and iOS devices.
    7. Drag and drop the just added bookmark from the Bookmarks Toolbar to a folder on Bookmarks Toolbar. Wait and verify this is synced to Android and iOS devices.
    8. Drag and drop the same bookmark to a different folder on the Bookmarks Toolbar. This action is not synced to either Android or iOS.
    9. From the Bookmarks Toolbar, right click on the Bookmark and select Edit. Change the folder and select Done. This action was also not synced to Android or iOS.
    
- Actual result:
Bookmark on synced devices still shows in original folder, not in updated folder.

- Expected result:
Bookmark should be displayed in updated folder on the synced devices.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
mobile sync not available in released version

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

Here's what was displayed in the dev tools console log while performing the steps to reproduce -
fetching BOOKMARKS,PREFERENCES records after 1497639813
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497639813
sync.js:2 got 0 decrypted records in PREFERENCES after 1497639813
sync.js:2 sending record: {"action":1,"bookmark":{"hideInToolbar":false,"isFolder":false,"site":{"creationTime":0,"customTitle":"","favicon":"https://www.fsu.edu/favicon.ico","lastAccessedTime":1497639621943,"location":"https://www.fsu.edu/","title":"Florida State University"}},"deviceId":{"0":0},"objectId":{"0":13,"1":125,"2":221,"3":119,"4":245,"5":137,"6":243,"7":112,"8":126,"9":232,"10":189,"11":108,"12":108,"13":21,"14":248,"15":193}}
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497639873
sync.js:2 got 1 decrypted records in BOOKMARKS after 1497639873
sync.js:1 Ignoring UPDATE of object 13,125,221,119,245,137,243,112,126,232,189,108,108,21,248,193.
sync.js:2 resolved 1 BOOKMARKS -> 0
sync.js:2 got 0 decrypted records in PREFERENCES after 1497639873
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497639933
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497639933
sync.js:2 got 0 decrypted records in PREFERENCES after 1497639933
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497639993
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497639993
sync.js:2 got 0 decrypted records in PREFERENCES after 1497639993
sync.js:2 sending record: {"action":0,"bookmark":{"hideInToolbar":false,"isFolder":false,"parentFolderObjectId":{"0":108,"1":158,"2":128,"3":120,"4":198,"5":251,"6":55,"7":182,"8":5,"9":197,"10":73,"11":195,"12":176,"13":107,"14":102,"15":240},"site":{"creationTime":0,"customTitle":"","favicon":"https://www.fsu.edu/favicon.ico","lastAccessedTime":1497639621943,"location":"https://www.fsu.edu/","title":"Florida State University"}},"deviceId":{"0":0},"objectId":{"0":13,"1":125,"2":221,"3":119,"4":245,"5":137,"6":243,"7":112,"8":126,"9":232,"10":189,"11":108,"12":108,"13":21,"14":248,"15":193}}
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640053
sync.js:2 got 1 decrypted records in BOOKMARKS after 1497640053
sync.js:2 resolved 1 BOOKMARKS -> 1
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640053
sync.js:2 sending record: {"action":1,"bookmark":{"hideInToolbar":false,"isFolder":false,"parentFolderObjectId":{"0":108,"1":158,"2":128,"3":120,"4":198,"5":251,"6":55,"7":182,"8":5,"9":197,"10":73,"11":195,"12":176,"13":107,"14":102,"15":240},"site":{"creationTime":0,"customTitle":"","favicon":"https://www.fsu.edu/favicon.ico","lastAccessedTime":1497639621943,"location":"https://www.fsu.edu/","title":"Florida State University"}},"deviceId":{"0":0},"objectId":{"0":13,"1":125,"2":221,"3":119,"4":245,"5":137,"6":243,"7":112,"8":126,"9":232,"10":189,"11":108,"12":108,"13":21,"14":248,"15":193}}
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640113
sync.js:2 got 1 decrypted records in BOOKMARKS after 1497640113
sync.js:1 Ignoring UPDATE of object 13,125,221,119,245,137,243,112,126,232,189,108,108,21,248,193.
sync.js:2 resolved 1 BOOKMARKS -> 0
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640113
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640173
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640173
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497640173
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640233
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640233
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497640233
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640293
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497640293
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640293
sync.js:2 sending record: {"action":0,"bookmark":{"hideInToolbar":false,"isFolder":false,"parentFolderObjectId":{"0":165,"1":201,"2":4,"3":209,"4":62,"5":33,"6":78,"7":142,"8":174,"9":240,"10":178,"11":139,"12":150,"13":136,"14":41,"15":39},"site":{"creationTime":0,"customTitle":"","favicon":"https://www.fsu.edu/favicon.ico","lastAccessedTime":1497639621943,"location":"https://www.fsu.edu/","title":"Florida State University"}},"deviceId":{"0":0},"objectId":{"0":13,"1":125,"2":221,"3":119,"4":245,"5":137,"6":243,"7":112,"8":126,"9":232,"10":189,"11":108,"12":108,"13":21,"14":248,"15":193}}
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640353
sync.js:2 got 1 decrypted records in BOOKMARKS after 1497640353
sync.js:1 Ignoring CREATE of object 13,125,221,119,245,137,243,112,126,232,189,108,108,21,248,193.
sync.js:2 resolved 1 BOOKMARKS -> 0
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640353
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640413
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497640413
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640413
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640473
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497640473
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640473
sync.js:2 fetching BOOKMARKS,PREFERENCES records after 1497640533
sync.js:2 got 0 decrypted records in BOOKMARKS after 1497640533
sync.js:2 got 0 decrypted records in PREFERENCES after 1497640533

- Any related issues:

**Comment by alexwykoff** [comment]
migrated to https://github.com/brave/sync/issues/111
