### ISSUE TITLE
Extension Request : Always on top

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9532]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A community member requested the firefox addon : Always on Top 
https://community.brave.com/t/pin-the-browser-always-on-top-keeps-the-window-in-front-even-when-you-click-work-on-other-applications/3836

**Comment by hawkeye116477** [comment]
Please add DownThemAll! (or Turbo Download Manager), Bulk Media Downloader and Violentmonkey or Tampermonkey. It would also be useful something like All in One Sidebar or sidebar like that is on Vivaldi.

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
