### ISSUE TITLE
tab preview after closing a tab doesn't respect tab preview config

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9536]
Bug happens in 0.17.x given #8902 was added for that milestone.

Issue first reported in https://github.com/brave/browser-laptop/issues/9306#issuecomment-308908661.

STR:

1. Disable tab previews
2. Open three tabs
3. Set first as active
4. Hover over second, close

Result:
Third tab is previewed

Expected:
tab preview is disabled it should not previe

Given trigger preview after close was [introduced](https://github.com/brave/browser-laptop/commit/cb23596c9bf56077dfa88316e687b3e605aa0e22) in 0.17.x in moving this to the same milestone as well.

**Comment by srirambv** [comment]
When verifying twice I didn't see the preview of the third tab after the second tab was closed and after the tab was closed the close button of third tab(now second) didn't show up until the cursor moved a little
