### ISSUE TITLE
Huge Download Panel

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#9538]
Not sure if this is due to HiDPI screen or not but the bottom download panel is huge. Any chance of sliming it down? Perhaps removing which website the download is from?

![screenshot from 2017-06-18 04-02-22](https://user-images.githubusercontent.com/27884805/27255569-1407a478-53db-11e7-8878-83ab3186d997.png)

**Comment by srirambv** [comment]
+1 on slimming down the panel. 

cc: @bradleyrichter

**Comment by luixxiul** [comment]
Compact download panel option could be an option.

**Comment by Jacalz** [comment]
Also redoing the download panel with a more flat look and less gap on to and bottom, like the remake of the tabs bars 👍

**Comment by NejcZdovc** [comment]
I think that we need to redo the whole download panel, some more info here #7082. Personally I wouldn't go with option for compact, but would just make it compact with all the missing data.

**Comment by srirambv** [comment]
> Personally I wouldn't go with option for compact, but would just make it compact with all the missing data. 

Have a compact panel with just File name, Size(completed/Total) and time remaining similar to chrome but then on mouse hover on download item, can show the source URL as well. (Considering if users still want to know where they are downloading it from)

**Comment by bsclifton** [comment]
@JGH1000 do you have the option enabled (it's under Preferences > Advanced) for Toolbar and UI elements scale?  This will make the user interface (not the web pages) bigger, which is great for reading... but horrible when the download bar takes up half the screen

It would be nice to offer a compact download bar as an option (perhaps disabled by default)

**Comment by JGH1000** [comment]
@bsclifton Nope, the screenshot is with 'Normal' scale. I also tried to change to 'Smaller' but the panel is still very large. Perhaps having a Downloads icon at the top bar like in Firefox would be the cleanest solution.

**Comment by bradleyrichter** [comment]
DL panel needs a design refactor after some recents adds. 

Adding it to the short list...

**Comment by jonathansampson** [comment]
+1 from a Twitter user: https://twitter.com/Sulcobruchus/status/1008638406891589635

![image](https://user-images.githubusercontent.com/815158/41544687-f458cc46-72de-11e8-8971-15bebd107a80.png)

**Comment by srirambv** [comment]
This should be fixed on brave-core. Download bar isn't huge like the current muon browser-laptop. Even hide download bar during download is going to be fixed on brave-core

cc: @bsclifton ok to close this?

**Comment by bsclifton** [comment]
@srirambv yup - this will be fixed with Brave Core. Closing issue as `wontfix` since the fix won't be in `browser-laptop`. Stay tuned for Brave Core (coming in a few months!)
