### ISSUE TITLE
Developer tools not re-opening maximized when closed as maximized.

### ISSUE THREAD

**Issue by kroppt** [brave/browser-laptop#9540]
- **Did you search for similar issues before submitting this one?** Yes

- **Describe the issue you encountered:** Developer tools not re-opening maximized when closed as maximized.

- **Platform (Win7, 8, 10? macOS? Linux distro?):** Win10

- **Brave Version (revision SHA):** 0.16.9

- **Steps to reproduce:**
    1. Open developer tools (right click > inspect element)
    2. Maximize developer tools
    3. Close developer tools
    4. Open developer tools
    
- **Actual result:** Developer tools open in non-maximized window.

- **Expected result:** Developer tools open maximized.

- **Is this an issue in the currently released version?** Yes

- **Can this issue be consistently reproduced?** Every time

- **Screenshot if needed:**
![image](https://user-images.githubusercontent.com/14015672/27255662-a2bdda52-5368-11e7-9413-2d20177b378b.png)

**Comment by CamJohnson26** [comment]
This has been happening in the Brave browser too, not just the developer tools. Keeps me from using the browser.

**Comment by kroppt** [comment]
@CamJohnson26  Ya, I stopped using it also because of this reason. I guess it's being replicated to at least a few PCs.

**Comment by NejcZdovc** [comment]
@CamJohnson26 @kroppt regarding browser, we have a fix in place for this kind of scenarios https://github.com/brave/browser-laptop/pull/10458. It will be shipped with 0.20.x release.
