### ISSUE TITLE
Sort top sites more deterministically

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9541]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Auto-suggestions cycle through every google domain imaginable.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/c5968c5ea2a8eaab1834d638aa4ead5af5d517e2

- Steps to reproduce:
    1. Slowly type "google.com" into the address bar
    
- Actual result:
Note that the active suggestion cycles through numerous variants of this domain.

- Expected result:
I should only be suggested the variant of google that matches my language/region.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![this-google-that-google](https://user-images.githubusercontent.com/815158/27257667-a950c4b0-53a4-11e7-8129-558261207937.gif)

- Any related issues:

**Comment by bsclifton** [comment]
Marked with `needs-triage` and assigned to 0.17.x for now. Will review with others on Tuesday to determine priority

**Comment by srirambv** [comment]
@jonathansampson Is this expected?  
![image](https://user-images.githubusercontent.com/17010094/27372932-2b5d9be8-565e-11e7-9ed5-b213f1e6b6a7.png)
![image](https://user-images.githubusercontent.com/17010094/27372920-21f78546-565e-11e7-94d7-5c6a0bab7526.png)


>Expected result:
I should only be suggested the variant of google that matches my language/region.

I have the region set as Ireland but I see Google suggestion for India and Germany along with US when I type in `google.c` and I see suggestions for India and UK along with US when I just type `goog`

**Comment by bsclifton** [comment]
@srirambv the top sites are just Alexa top sites; no criteria (such as location) is removing entries, so they will show all entries
