### ISSUE TITLE
Need animated transition for tabs on first "new set" instance (tab #7)

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#955]
Attached is a quicktime to show what should be a good solution to help initial users better understand how tab sets work. 

Feedback welcome! PR to implement highly desired. (fun stuff  :    )

Brad

@bridiver

**Comment by bradleyrichter** [comment]
GH won't accept my QT or zip'd QT. Hmmm...

**Comment by bbondy** [comment]
animated gif if you can, the frame rate isn't very good but a good program for this is licecap

**Comment by bradleyrichter** [comment]
should should work:

![tabs2set_animation_mockup](https://cloud.githubusercontent.com/assets/13509546/13410204/4297290a-deeb-11e5-9ae0-bcf346359806.gif)

**Comment by bbondy** [comment]
:clap:

**Comment by aekeus** [comment]
Agreed :clap:

**Comment by bradleyrichter** [comment]
thank you. thank you. I'll be here all week.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/35
