### ISSUE TITLE
Closing the only tab in second tabset shows wrong number of tabs

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9561]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Closing the only tab in second tabset causes ugly transition when moving back to existing tabs

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.3
rev	02a7878
Muon	4.0.3

- Steps to reproduce:
    1. Clean install  0.17.3
    2. Open 20 tabs (default tabset count) ensure the tabs are properly set
    3. Open 21st tab, ensure the tab focus is set to the second set
    4. Close 21st tab, focus shifts back to the previous tabset but only 6-7 tabs are shown
    5. Hover over the tabs bar, all remaining tabs are pulled back into view 
    
- Actual result:
Closing the only tab in second tabset causes ugly transition when moving back to existing tabs

- Expected result:
Should focus all 20 tabs from the previous tabset

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tabset](https://user-images.githubusercontent.com/17010094/27272636-18b1065c-54c3-11e7-91fd-900c43bebaf4.gif)

- Any related issues:
#8909

**Comment by luixxiul** [comment]
reproduced on macOS too

**Comment by bbondy** [comment]
I'll grab this, I have a fix, just working on a test. Will submit it soon.
