### ISSUE TITLE
Middle click is not working on Home button

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9562]
## Test plan
See https://github.com/brave/browser-laptop/pull/9672#issue-237979273

## Original issue description
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Middle click is not working on Home button. This regressed when we needed introduce aux event for chromium 54.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
fab48e2
- Steps to reproduce:
    1. Middle click on Home button
    
- Actual result:
Nothing happens
- Expected result:
Tab with home page is opened in a new tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment]
Still seeing the issue as reported on 0.17.6

**Comment by NejcZdovc** [comment]
Which OS?

**Comment by LaurenWags** [comment]
sorry, left that important detail out. MacOS 10.12.5.

**Comment by srirambv** [comment]
@NejcZdovc  I am not able to middle click on the home button on clean install. But it did work on the upgrade from 0.17.4

**Comment by srirambv** [comment]
Need to double check on Linux  as it fails on Windows and macOS, hence removing the tag

**Comment by NejcZdovc** [comment]
Yeah sometimes it's working, sometimes is not, will check out what is going on.
