### ISSUE TITLE
Add option to send language value different from UI language

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9565]
**Describe the issue you encountered:** Add an option to send language value than UI language (since language is one of the decisive factors on Panopticlick).

![clipboard01](https://user-images.githubusercontent.com/3362943/27274344-d8acd16c-550d-11e7-9057-46eb451385d6.jpg)

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.16.9

- Steps to reproduce:
    1. Set lang setting to something other than English
    2. Open https://panopticlick.eff.org
    3. Test the browser
    
- Actual result: the same value as the UI lang setting is sent

- Expected result: the value should be selectable. It will also make it possible to open foreign google sites directly, such as google.co.jp.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
This is an interesting one, since many sites use that and react to the value (it's sent in the HTTP header when page is fetched)

cc: @diracdeltas
