### ISSUE TITLE
Window menu doesn't open in Gnome 3 on Arch Linux

### ISSUE THREAD

**Issue by RGBD** [brave/browser-laptop#9567]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Window menu doesn't open. Clicking does nothing.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch Linux
Gnome Shell 3.24.2

**about:brave** says: Node.js	7.9.0
but
```
$ node -v
v8.1.2
```

- Brave Version (revision SHA):
0.19.0 (ddc30fda6fd4596d48f63d154f4dee10014f55d0)

- Steps to reproduce:
    1. Start browser
    2. Click any window menu item
    3. Nothing happens
    
- Actual result: Nothing happens

- Expected result: Menu should open

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
the issue was fixed on #9470

**Comment by luixxiul** [comment]
the fix will be available on 0.17 series. thanks for report!

**Comment by bsclifton** [comment]
@RGBD the fix for this is now available 😄 You can grab the binaries from https://github.com/brave/browser-laptop/releases/tag/v0.16.11dev

Please let us know if this fixes the issue.  Thanks!
