### ISSUE TITLE
Bookmarking top tiles doesn't show default favicon

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9568]
## Test plan

https://github.com/brave/browser-laptop/pull/13107#issue-168648474

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmarking top tiles doens't show default favicon

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.3
rev	02a7878
Muon	4.0.3

- Steps to reproduce:
    1. Clean install 0.17.3 and set bookmarks to show text and favicon
    2. Bookmark top tiles, no favicon/default favicon is shown
    3. Manually add a bookmark, default page icon is shown until page visit
    
- Actual result:
Bookmarking top tiles doens't show default favicon

- Expected result:
Should add the default favicon shown on toptiles

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Must be an existing issue on previous builds

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27287186-caea6a66-54fa-11e7-9ea7-5950cf9408ed.png)

- Any related issues:
cc: @cezaraugusto

**Comment by sergiorojasa** [comment]
I would like to work on this issue.

**Comment by srirambv** [comment]
@sergiorojasa self assigned for you to work on it. Please open up a PR with the fix

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
