### ISSUE TITLE
Improve Bookmark Import - request from community

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9569]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From Community: (https://community.brave.com/t/first-use-and-import-favs-from-any-browser/3593)

Please create a better way to import bookmarks. User requests that they not all be in an 'Imported' folder, but rather the imported bookmarks have the same structure as the browser that they came from. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Import bookmarks.
    2. Bookmarks are found under an 'Imported' folder, instead of having the same structure that they do from their source.

    
- Actual result:
Bookmarks are found under an 'Imported' folder.

- Expected result:
Bookmarks would not be under an 'Imported' folder, they would have the same structure as their source.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by benmordecai** [comment]
Most people importing bookmarks to Brave are attempting to migrate browsers, so the intuitive behavior would be for the imported results to mirror the appearance of the browser of origin.

**Comment by luixxiul** [comment]
iirc that was introduced intentionally, cc @darkdh

**Comment by darkdh** [comment]
The issue which remove the function is here https://github.com/brave/browser-laptop/issues/7194
firefox and chrome both put imported bookmarks into a separate folder which will be easier for users to organize their bookmarks by their own way
@bsclifton , @bradleyrichter

**Comment by luixxiul** [comment]
wontfix?

**Comment by bsclifton** [comment]
++ on `wontfix` for me 👍

**Comment by darkdh** [comment]
I prefer wonfix
