### ISSUE TITLE
0.17.x release notes

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9579]
Generated 06/17/2017
 - Incorrect hostname shown in titlemode when host is very long. ([#9500](https://github.com/brave/browser-laptop/issues/9500))
 - Upgrade to Chromium 59.0.3071.104. ([#9499](https://github.com/brave/browser-laptop/issues/9499))
 - Middle click on pinned tab causes all opened tabs to show as pinned tabs. ([#9492](https://github.com/brave/browser-laptop/issues/9492))
 - Clicking menu bar items in 0.16.x and 0.17.1 does nothing. ([#9470](https://github.com/brave/browser-laptop/issues/9470))
 - Tab title isn't hidden for session tabs after the tab threshold is reached. ([#9466](https://github.com/brave/browser-laptop/issues/9466))
 - AppState.sites sort takes a long time (Every navigation +200 ms [w/ 10K bookmarks]). ([#9427](https://github.com/brave/browser-laptop/issues/9427))
 - "Select its parent tab" setting not working as expected. ([#9395](https://github.com/brave/browser-laptop/issues/9395))
 - Bookmark title is not selected automatically. ([#9091](https://github.com/brave/browser-laptop/issues/9091))
 - Improve RPM packaging. ([#9074](https://github.com/brave/browser-laptop/issues/9074))
 - Button not disabled on add new bookmark modal by default. ([#9019](https://github.com/brave/browser-laptop/issues/9019))
 - Add compact bravery panel with Aphrodite. ([#8954](https://github.com/brave/browser-laptop/issues/8954))
 - CSP referrer errors. ([#8920](https://github.com/brave/browser-laptop/issues/8920))
 - Build hangs in tmux on macOS. ([#8916](https://github.com/brave/browser-laptop/issues/8916))
 - Importing bookmarks after sync causes loss of hierarchy. ([#8892](https://github.com/brave/browser-laptop/issues/8892))
 - Show all button overlaps on ledger table entry. ([#8869](https://github.com/brave/browser-laptop/issues/8869))
 - Allow <site> to <action>?. ([#8826](https://github.com/brave/browser-laptop/issues/8826))
 - Noscript approvals from private tabs apply to regular tabs. ([#8779](https://github.com/brave/browser-laptop/issues/8779))
 - Saving a document doesn't show correct origin. ([#8698](https://github.com/brave/browser-laptop/issues/8698))
 - Pinned tab notification doesn't have the caret and shown across all tabs. ([#8626](https://github.com/brave/browser-laptop/issues/8626))
 - Unable to view HBOGO video. ([#8581](https://github.com/brave/browser-laptop/issues/8581))
 - Import data gets duplicated after sync. ([#8508](https://github.com/brave/browser-laptop/issues/8508))
 - Offer option to have URL bar fill empty space ("wide URL bar"). ([#8421](https://github.com/brave/browser-laptop/issues/8421))
 - Extension: Honey. ([#8118](https://github.com/brave/browser-laptop/issues/8118))
 - Unhide bitwarden password manager. ([#7921](https://github.com/brave/browser-laptop/issues/7921))
 - Integrate the new welcome screen. ([#7821](https://github.com/brave/browser-laptop/issues/7821))
 - Tab preview on hover doesn't work after closing tab until moving the mouse out of tabs bar. ([#7606](https://github.com/brave/browser-laptop/issues/7606))
 - 50-80ms delay when closing a tab. ([#7395](https://github.com/brave/browser-laptop/issues/7395))
 - Right clicking tab being previewed causes focus to change. ([#7327](https://github.com/brave/browser-laptop/issues/7327))
 - Browser performance reduces when large amount of bookmarks are imported. ([#7240](https://github.com/brave/browser-laptop/issues/7240))
 - Clicking on disabled Ad/Tracker count enables the <li> element under braveryPanelBody. ([#7026](https://github.com/brave/browser-laptop/issues/7026))
 - Autofill form option blinks and cannot be clicked. ([#5438](https://github.com/brave/browser-laptop/issues/5438))
 - Brave Browser very slow to open or close tabs. ([#4848](https://github.com/brave/browser-laptop/issues/4848))
 - Sort adblock filter lists alphabetically. ([#4501](https://github.com/brave/browser-laptop/issues/4501))
 - CSS for visited links ( A:Visited ) does not work. ([#512](https://github.com/brave/browser-laptop/issues/512))

**Comment by alexwykoff** [comment]
Generated 06/21/2017

 - Download leaves about:blank page loading. ([#9620](https://github.com/brave/browser-laptop/issues/9620))
 - Add support for Linux Mint - Serena . ([#9590](https://github.com/brave/browser-laptop/issues/9590))
 - Middle click is not working on Home button. ([#9562](https://github.com/brave/browser-laptop/issues/9562))
 - Closing the only tab in second tabset shows wrong number of tabs. ([#9561](https://github.com/brave/browser-laptop/issues/9561))
 - Unable to switch to any tab on load when reloading windows from last time . ([#9502](https://github.com/brave/browser-laptop/issues/9502))
 - Incorrect hostname shown in titlemode when host is very long. ([#9500](https://github.com/brave/browser-laptop/issues/9500))
 - Upgrade to Chromium 59.0.3071.104. ([#9499](https://github.com/brave/browser-laptop/issues/9499))
 - Middle click on pinned tab causes all opened tabs to show as pinned tabs. ([#9492](https://github.com/brave/browser-laptop/issues/9492))
 - Tab title isn't hidden for session tabs after the tab threshold is reached. ([#9466](https://github.com/brave/browser-laptop/issues/9466))
 - AppState.sites sort takes a long time (Every navigation +200 ms [w/ 10K bookmarks]). ([#9427](https://github.com/brave/browser-laptop/issues/9427))
 - "Select its parent tab" setting not working as expected. ([#9395](https://github.com/brave/browser-laptop/issues/9395))
 - Closing Tabs Results in White Page. ([#9306](https://github.com/brave/browser-laptop/issues/9306))
 - Bookmark title is not selected automatically. ([#9091](https://github.com/brave/browser-laptop/issues/9091))
 - Improve RPM packaging. ([#9074](https://github.com/brave/browser-laptop/issues/9074))
 - Button not disabled on add new bookmark modal by default. ([#9019](https://github.com/brave/browser-laptop/issues/9019))
 - Add compact bravery panel with Aphrodite. ([#8954](https://github.com/brave/browser-laptop/issues/8954))
 - CSP referrer errors. ([#8920](https://github.com/brave/browser-laptop/issues/8920))
 - Build hangs in tmux on macOS. ([#8916](https://github.com/brave/browser-laptop/issues/8916))
 - Importing bookmarks after sync causes loss of hierarchy. ([#8892](https://github.com/brave/browser-laptop/issues/8892))
 - Show all button overlaps on ledger table entry. ([#8869](https://github.com/brave/browser-laptop/issues/8869))
 - Allow <site> to <action>?. ([#8826](https://github.com/brave/browser-laptop/issues/8826))
 - Noscript approvals from private tabs apply to regular tabs. ([#8779](https://github.com/brave/browser-laptop/issues/8779))
 - Saving a document doesn't show correct origin. ([#8698](https://github.com/brave/browser-laptop/issues/8698))
 - Pinned tab notification doesn't have the caret and shown across all tabs. ([#8626](https://github.com/brave/browser-laptop/issues/8626))
 - Unable to view HBOGO video. ([#8581](https://github.com/brave/browser-laptop/issues/8581))
 - Import data gets duplicated after sync. ([#8508](https://github.com/brave/browser-laptop/issues/8508))
 - Offer option to have URL bar fill empty space ("wide URL bar"). ([#8421](https://github.com/brave/browser-laptop/issues/8421))
 - Extension: Honey. ([#8118](https://github.com/brave/browser-laptop/issues/8118))
 - Integrate the new welcome screen. ([#7821](https://github.com/brave/browser-laptop/issues/7821))
 - Tab preview on hover doesn't work after closing tab until moving the mouse out of tabs bar. ([#7606](https://github.com/brave/browser-laptop/issues/7606))
 - 50-80ms delay when closing a tab. ([#7395](https://github.com/brave/browser-laptop/issues/7395))
 - Right clicking tab being previewed causes focus to change. ([#7327](https://github.com/brave/browser-laptop/issues/7327))
 - Browser performance reduces when large amount of bookmarks are imported. ([#7240](https://github.com/brave/browser-laptop/issues/7240))
 - Clicking on disabled Ad/Tracker count enables the <li> element under braveryPanelBody. ([#7026](https://github.com/brave/browser-laptop/issues/7026))
 - Autofill form option blinks and cannot be clicked. ([#5438](https://github.com/brave/browser-laptop/issues/5438))
 - Brave Browser very slow to open or close tabs. ([#4848](https://github.com/brave/browser-laptop/issues/4848))
 - CSS for visited links ( A:Visited ) does not work. ([#512](https://github.com/brave/browser-laptop/issues/512))

**Comment by luixxiul** [comment]
`Allow to ?.` ?
