### ISSUE TITLE
Bugs reendering Gifs and videos on Facebook

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#958]
The first few seconds of a GIF or a video appear all black and then return to normal.

**Comment by luixxiul** [comment]
Can this still be reproduced?

**Comment by Kzeir** [comment]
It seems to have been corrected after upgrading brave

*Att: Alessandro Tetsuo More*

2016-05-16 11:02 GMT-03:00 Suguru Hirahara <notifications@github.com>:
