### ISSUE TITLE
Brave crashes after login to Roundcube Webmail

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9580]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Reported by Community user: (https://community.brave.com/t/0-13-0-crashes-os-x/914)
Crashes when I sign in to Roundcube Webmail. Displays the login page OK, then after successful login displays the main interface briefly, then crashes with this report (much abbreviated because of 32k limits). Unfortunately I cannot provide a link which demonstrates the problem because it is after my login. Also, works fine on Chrome (Version 58.0.3029.110 (64-bit))

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Name	Version
Brave	0.16.9
rev	fba98fc
Muon	4.0.3
libchromiumcontent	59.0.3071.86
V8	5.9.211.31
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.5.0
os.arch	x64

- Steps to reproduce:
Displays the login page OK, then after successful login displays the main interface briefly, then crashes.
    
- Actual result:
Brave crashes.

- Expected result:
Brave should not crash.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes. User originally reported issue with 0.13.0 and confirmed it is still an issue in 0.16.9. User also reported that 0.12.15 did not have this issue.

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
This was included in the community post from user:

Process: Brave [45892]
Path: /Applications/Brave.app/Contents/MacOS/Brave
Identifier: com.electron.brave
Version: 0.16.9 (4.0.3)
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: Brave [45892]
User ID: 502

Date/Time: 2017-06-20 02:59:12.445 +1000
OS Version: Mac OS X 10.12.4 (16E195)
Report Version: 12
Anonymous UUID: 3A333C86-C9EA-DE06-D0E6-4F9791662469

Time Awake Since Boot: 130000 seconds

System Integrity Protection: enabled

Crashed Thread: 0 CrBrowserMain Dispatch queue: com.apple.main-thread

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]

VM Regions Near 0:
--> 
__TEXT 0000000109672000-0000000109673000 [ 4K] r-x/rwx SM=COW /Applications/Brave.app/Contents/MacOS/Brave

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0 org.brave.Brave.framework 0x000000011002f291 0x10eb1c000 + 22098577
1 org.brave.Brave.framework 0x000000011002f71b 0x10eb1c000 + 22099739
2 org.brave.Brave.framework 0x000000011002f82f 0x10eb1c000 + 22100015
3 org.brave.Brave.framework 0x0000000110151469 0x10eb1c000 + 23286889
4 org.brave.Brave.framework 0x00000001100e3f51 0x10eb1c000 + 22839121
5 org.brave.Brave.framework 0x0000000110109deb 0x10eb1c000 + 22994411
6 org.brave.Brave.framework 0x000000011010a13c 0x10eb1c000 + 22995260
7 org.brave.Brave.framework 0x000000011010a4f3 0x10eb1c000 + 22996211
8 org.brave.Brave.framework 0x000000011010d90a 0x10eb1c000 + 23009546
9 org.brave.Brave.framework 0x00000001100ff08a 0x10eb1c000 + 22950026
10 org.brave.Brave.framework 0x000000011010d32f 0x10eb1c000 + 23008047
11 com.apple.CoreFoundation 0x00007fffd381d3b1 CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION + 17
12 com.apple.CoreFoundation 0x00007fffd37fe63c __CFRunLoopDoSources0 + 556
13 com.apple.CoreFoundation 0x00007fffd37fdb26 __CFRunLoopRun + 934
14 com.apple.CoreFoundation 0x00007fffd37fd524 CFRunLoopRunSpecific + 420
15 com.apple.HIToolbox 0x00007fffd2d5debc RunCurrentEventLoopInMode + 240
16 com.apple.HIToolbox 0x00007fffd2d5dcf1 ReceiveNextEventCommon + 432
17 com.apple.HIToolbox 0x00007fffd2d5db26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
18 com.apple.AppKit 0x00007fffd12f8e24 _DPSNextEvent + 1120
19 com.apple.AppKit 0x00007fffd1a7485e -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
20 com.apple.AppKit 0x00007fffd12ed7ab -[NSApplication run] + 926
21 org.brave.Brave.framework 0x000000011010e14e 0x10eb1c000 + 23011662
22 org.brave.Brave.framework 0x000000011010d76c 0x10eb1c000 + 23009132
23 org.brave.Brave.framework 0x0000000110127923 0x10eb1c000 + 23116067
24 org.brave.Brave.framework 0x000000010ef2706f 0x10eb1c000 + 4239471
25 org.brave.Brave.framework 0x000000010ef26e90 0x10eb1c000 + 4238992
26 org.brave.Brave.framework 0x000000010ef296d2 0x10eb1c000 + 4249298
27 org.brave.Brave.framework 0x000000010ef22d3c 0x10eb1c000 + 4222268
28 org.brave.Brave.framework 0x00000001100dd14b 0x10eb1c000 + 22810955
29 org.brave.Brave.framework 0x000000011133a21c 0x10eb1c000 + 42066460
30 org.brave.Brave.framework 0x00000001100dc524 0x10eb1c000 + 22807844
31 org.brave.Brave.framework 0x000000010eb1e74d ChromeMain + 141
32 com.electron.brave 0x0000000109672dba main + 522
33 libdyld.dylib 0x00007fffe93a4235 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
rax: 0x0000600000094808 rbx: 0x00007fff5658bb38 rcx: 0x0000000000000029 rdx: 0x0000000000000000
rdi: 0x00007fff5658bb38 rsi: 0x0000000000000000 rbp: 0x00007fff5658bb20 rsp: 0x00007fff5658bb10
r8: 0x0000000000000001 r9: 0x000000000012becd r10: 0x00007fdb9dc0b398 r11: 0xffffffff00000000
r12: 0x000000011002f6f0 r13: 0x00000001141913b0 r14: 0x000060000021fe00 r15: 0x00007fff5658bb60
rip: 0x000000011002f291 rfl: 0x0000000000010202 cr2: 0x0000000000000000

Logical CPU: 3
Error Code: 0x00000004
Trap Number: 14

Model: iMac12,1, BootROM IM121.0047.B29, 2 processors, Intel Core i3, 3.1 GHz, 12 GB, SMC 1.71f21
Graphics: AMD Radeon HD 6750M, AMD Radeon HD 6750M, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
Memory Module: BANK 0/DIMM1, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
Memory Module: BANK 1/DIMM1, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 4.0.74.0-P2P
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: WDC WD2500AAKS-402AA0, 250.06 GB
Serial ATA Device: HL-DT-STDVDRW GA32N
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Keyboard Hub
USB Device: USB Optical Mouse
USB Device: Apple Keyboard
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: CanoScan
USB Device: Card Reader
Thunderbolt Bus:

- Any related issues:

**Comment by bbondy** [comment]
@darkdh could you take a look?

**Comment by darkdh** [comment]
sure thing

**Comment by LaurenWags** [comment]
We're received notification from the user that this is no longer occurring.
https://community.brave.com/t/0-13-0-crashes-os-x/914/10

**Comment by bsclifton** [comment]
Closing and removing milestone- if we find out more info and need to take action, let's reopen 😄

**Comment by bsclifton** [comment]
+1 from @clockworkpc via https://github.com/brave/browser-laptop/issues/13948
> @bsclifton I upgraded to Brave 0.22.667 from the PPA but it still crashes:
>
> https://youtu.be/rjzgGnhRBBE
>
> Running Ubuntu 16.04
>
> ![Uploading Screenshot from 2018-04-28 07-14-47.png…]()

**Comment by bsclifton** [comment]
+1 from @rotational467 via https://github.com/brave/browser-laptop/issues/13948#issuecomment-384962585
