### ISSUE TITLE
Extension description changed in non English language.

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#9583]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
Trying to enable some extension in `about:preferences#extensions` (to test the l10n). Before enable extension, it show description in Bahasa Indonesia. But when enable the extension, description change to English. Disable it, will change it back.

Some description also shown in English even already translated in Transifex.

- Platform (Win7, 8, 10? macOS? Linux distro?):
win 8.1

- Brave Version (revision SHA):
0.17.1 (6482f15)

- Steps to reproduce:
    1. Set Brave to `Indonesian` in `about:preferences#general > Language`
    2. Go to `about:preferences#extensions`
    3. Enable/disable some extension(s) like bitwarden and Dashlane.
    
- Actual result:
The description change from Bahasa Indonesia to English

- Expected result:
Description should not change

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-extensions-non-english-bug](https://user-images.githubusercontent.com/25360853/27308377-6d3e1b6e-5578-11e7-931e-a7ce48f1371a.gif)

- Any related issues:

**Comment by bsclifton** [comment]
cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
@jonathansampson are extensions supposed to change language once installed? I did so for dummy data but if not the l10n strings should be removed from there

**Comment by cezaraugusto** [comment]
for context what happens is that disabled extensions data collect strings from `extensions.properties` as part of dummy data. So if there is a translation of that file from Transifex it will be translated. This only happens for uninstalled/disabled (not cached) extensions.

It changes to English again because once activated the extension is fetched from vault-updater so the dummy resource is not consulted anymore.

**Comment by srirambv** [comment]
This is an issue on English locale as well not just for other languages. Issue #14011 captures it

**Comment by jonathansampson** [comment]
Some high-level coverage here: initial names and descriptions are loaded from our local _dummyData_ object. When the extension is successfully downloaded, we switch to using the information found within the extensions manifest (or localization files).

English _may_ be a fallback if the expected language isn't found. I'll check into this.
