### ISSUE TITLE
move most extension registration from muon into browser-laptop 

### ISSUE THREAD

**Issue by kevinlawler** [brave/browser-laptop#9584]

**Comment by bsclifton** [comment]
@kevinlawler was this issue supposed to be closed after https://github.com/brave/browser-laptop/pull/9585? or is there more to do?

**Comment by kevinlawler** [comment]
Now that brave/browser-laptop#9585 and brave/muon#223 have both landed, we can close this issue. I should've noted this originally...

**Comment by bsclifton** [comment]
manually cherry picked to 0.18.x with https://github.com/brave/browser-laptop/commit/40101090a7995fb7ebf9ab7a855bd5eefdd86c5d. Required since we're using a newer Muon (4.3.1)
