### ISSUE TITLE
Block ads doesn't work properly

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#959]
Many sites still show the ads including Facebook and many others appear pop-ups or redirectioning for 
advertising pages It is really annoying.

**Comment by bbondy** [comment]
please provide specific links other than facebook, also screenshots help. Thanks.

**Comment by Kzeir** [comment]
A really poor website just for example, when I click on download open other
pages with ads or virus/fake sites, and then in the site some ads buttons
are still apearing. Screenshots are here.

*Att: Alessandro Tetsuo More*

2016-02-29 20:37 GMT-03:00 Brian R. Bondy <notifications@github.com>:

**Comment by bbondy** [comment]
Sorry I still see neither specific links nor images.

**Comment by Kzeir** [comment]
LOL, I sent 2 images in the email

*Att: Alessandro Tetsuo More*

2016-02-29 23:43 GMT-03:00 Brian R. Bondy <notifications@github.com>:

**Comment by bbondy** [comment]
I guess email reply to github issue does post but does not attach images?

**Comment by Kzeir** [comment]
http://www.baixaki.com.br/download/declaracao-do-irpf-2016.htm

The really big red banner is a ads...

*Att: Alessandro Tetsuo More*

2016-02-29 23:44 GMT-03:00 Alê MRE <alemore67@gmail.com>:

**Comment by Kzeir** [comment]
http://thestir.cafemom.com/entertainment/158359/glee_changes_already_under_way?utm_medium=sem2&utm_campaign=prism&utm_source=outbrain&utm_content=0

When I open one site like this, it pop-up a window to subscribe it can be
erased like the others ads right?

*Att: Alessandro Tetsuo More*

2016-02-29 23:52 GMT-03:00 Alê MRE <alemore67@gmail.com>:

**Comment by bbondy** [comment]
thanks, keep posting annoyances :)

**Comment by FrancisTurner** [comment]
Kind of the opposite, but related. Amazon links in this post don't display unless you enable ads in bravery.

http://madgeniusclub.com/2016/03/01/if-its-tuesday-2/

Wondering if it would be possible to enable ads on a site by site basis (either the ad source or the parent page (or both))

**Comment by diracdeltas** [comment]
@FrancisTurner yep, we are planning to have the Bravery menu items turned into site-specific settings

**Comment by Kzeir** [comment]
http://megafilmestorrent.org This site is so annoying, I can't even click that open another window...

**Comment by luixxiul** [comment]
Closing for now as the topic became too wide.
