### ISSUE TITLE
can't remove bookmark or change its location

### ISSUE THREAD

**Issue by len5742** [brave/browser-laptop#9593]
- Did you search for similar issues before submitting this one? to the best of my extremely meager ability

- Describe the issue you encountered:

1. Can't remove bookmark:  Clicking on 'remove' - bookmark window closes, but star remains orange. Note that the 'remove' button does not get the 'selected' outline when I click on it, but window still closes as if selected.

2.Can't change bookmark location:  after updating bookmark folder and clicking on 'done', kicked out to new tab displaying bookmark manager.

I tried closing and reopening tab in question, prior to attempted removal, did not fix problem.

I tried cloning the tab and could not deleted/ change location in cloned tab either

- Platform (Win7, 8, 10? macOS? Linux distro?): win7

- Brave Version (revision SHA):

Name	Version
Brave	0.17.1
rev	84dbc8e
Muon	4.0.3
libchromiumcontent	59.0.3071.86
V8	5.9.211.31
Node.js	7.9.0
Update Channel	dev
os.platform	win32
os.release	6.1.7601
os.arch	x64
![capture](https://user-images.githubusercontent.com/23743718/27315962-b4dc681e-5531-11e7-80a4-ece9622a5664.JPG)

- Steps to reproduce:  ****--->>Can't reproduce on different urls open in tabs in same browser window. Can bookmark and then deleted bookmark with no problem
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced? No

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Attached shot of problem bookmark.

- Any related issues:
Response time is terrible for all the bookmarking commands I tried - several seconds.

**Comment by luixxiul** [comment]
which url is this?

**Comment by len5742** [comment]
the one for which I can't remove the bookmark?

http://www.thedailybeast.com/how-rachel-carson-cost-millions-of-people-their-lives

**Comment by rebron** [comment]
Closing. Fixed in brave-core.
