### ISSUE TITLE
Brave on Mac takes long to load

### ISSUE THREAD

**Issue by Miyurz** [brave/browser-laptop#9596]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Brave 0.16.9 takes almost 10 seconds to load. This started happening after my recent upgrade.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Mac Sierra

- Brave Version (revision SHA):
	fba98fc

- Steps to reproduce:
    1. Open Brave on the Mac after a recent reboot 
    
- Actual result:
Browser takes quite long to open even when the machine has enough memory and cpu is free.

- Expected result:
Browser should open instantly.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes,

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
Thanks for reporting @Miyurz! We have an issue already tracking startup time, captured with https://github.com/brave/browser-laptop/issues/9596 (in case you wanted to subscribe for updates). I'll close this issue as a duplicate

**Comment by NejcZdovc** [comment]
@bsclifton you probably meant #3025?

**Comment by bsclifton** [comment]
@NejcZdovc yes, thanks 😄  #3025
