### ISSUE TITLE
Wordpress authorization doesn't work on non-wordpress domain blogs

### ISSUE THREAD

**Issue by FrancisTurner** [brave/browser-laptop#960]
I'm not sure that this is entirely a brave issue, but I think it is more a brave problem than a wordpress one.

I have a wordpress account which I can use to comment on blogs hosted by wordpress, even ones where the domain isn't something.wordpress.com (e.g. I'd liek to comment on  http://blog.threatstop.com/2016/02/24/locky-not-to-be-confused-with-lucky/ ) . [ I recently enabled 2FA on my WP.com account, not sure if this is relevant. ]

When I click on the WP logo to log in for this blog a popup window comes up and the closes and the comment form changes to indicate that I am logged in, however when I want to post my comment I am required to login again. After entering my WP username and password and 2FA number I get to a blank page with a url like http://blog.threatstop.com/wp-comments-post.php 

Note that log in to wordpress.com itself works fine and it is possible to comment on blogs that are part of wordpress.com

**Comment by diracdeltas** [comment]
Does it work if you go to the Bravery menu and de-select "Block third party cookies"?

**Comment by diracdeltas** [comment]
What about setting "Allow ads and tracking" in the Bravery menu? Thanks for testing.

**Comment by FrancisTurner** [comment]
A combination of unchecking block 3rd party cookies and setting "allow ads and tracking" worked. No need to login a second time and the comment is posted. I think you need to whitelist wordpress.com somehow as this will affect a LOT of people/sites

**Comment by diracdeltas** [comment]
I went through the process of posting a comment on http://blog.threatstop.com/2016/02/24/locky-not-to-be-confused-with-lucky/#comment-12931 with the brave default settings (replace ads, block 3rd party cookies). It seemed to work fine except the comment wasn't visible until I reloaded a few times. Do you have another test case?

**Comment by FrancisTurner** [comment]
two other blogs that work the same way that I know of are http://accordingtohoyt.com/ and http://madgeniusclub.com/

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/discussion-wordpress-authorization-doesnt-work-on-non-wordpress-domain-blogs/10063

If you are still around here, would you please join the conversation there to talk about the issue further? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
