### ISSUE TITLE
Edit bookmark closes the folder dropdown and typing in edit mode jumps the cursor to the end after one character entry

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9602]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Edit bookmark closes the folder dropdown and typing in edit mode jumps the cursor to the end after one character entry

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
Muon	4.0.3

- Steps to reproduce:
    1. Open a bookmark folder from toolbar and right click on any bookmark to edit
    2. Folder drop down is closed and only shows the context menu
    3. Place the cursor in the middle of the URL and type in a character, cursor jumps to the end of the URL, have to move back after each character entry
    
- Actual result:
Edit bookmark closes the folder dropdown and typing in edit mode jumps the cursor to the end after one character entry

- Expected result:
Should retain the the folder dropdown when right click edit on a bookmark and cursor should not jump to end of the URL after typing in between the URL

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Recording provided by user 
http://screencast-o-matic.com/watch/cb1IeYXPrd

- Any related issues:
https://community.brave.com/t/minor-but-annoying-bug-with-editing-bookmarks/3857

**Comment by bsclifton** [comment]
I believe I saw this, but wasn't able to repro. When I did edit for a bookmark (to edit the title)... every character typed forced the cursor to go to the end ☹️

**Comment by bsclifton** [comment]
@NejcZdovc was this fixed with your recent improvements? 😄

**Comment by NejcZdovc** [comment]
@bsclifton I think so. @srirambv can you please re-test it in version 0.19.x?

**Comment by NejcZdovc** [comment]
Could be potentially resolved with #9710 PR

**Comment by srirambv** [comment]
@NejcZdovc  @bsclifton  I verified it on 676ab6a. When right click on folder, the folder dropdown disappears, On edit, found an issue where the cursor is not shown but the cursor doesn't jump to the end after individual character entry.  
![9602](https://user-images.githubusercontent.com/17010094/28514667-c9cccf34-7052-11e7-8b52-5a29a3ddbe61.gif)

**Comment by NejcZdovc** [comment]
@srirambv for dropdown we already have an issue #9362. I see that you already created an issue for the cursor problem. I would guess that this issue can be closed then
