### ISSUE TITLE
IME conversion candidate remains in text field, including URL bar

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9604]
**Describe the issue you encountered:** https://github.com/brave/browser-laptop/pull/9490#issuecomment-309816719

> STR:
> 1. Enable the Japanese IME
> 2. Input `brave`
> 3. Make sure you get `ｂらう゛ぇ`
> 4. Hit backspace 3 times
> 5. Make sure you only have `ｂ`
> 6. Hit that one more time to delete `ｂ`
>
> Actual result: just conversion candidate pulldown disappears and `ｂ` is still there
>
> Expected result: `ｂ` should be removed

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master 

- Steps to reproduce: See above

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
We also need to add IME support to all redux components that have inputs

**Comment by NejcZdovc** [comment]
@luixxiul can you please provide all inputs that are problematic? Thank you

**Comment by luixxiul** [comment]
sorry but I'm not sure what you mean with 'all inputs'.

**Comment by bsclifton** [comment]
@luixxiul I think @NejcZdovc is asking: Do other input fields have this problem too? Or does it appear limited to the autofill screen?
![bbb](https://user-images.githubusercontent.com/3362943/27293711-2d0d74d4-5552-11e7-9487-c9c8609ef930.gif)

**Comment by luixxiul** [comment]
ah, right I experience the issue on all of the fields.

**Comment by pullingour** [comment]
![output](https://user-images.githubusercontent.com/7346730/29350510-d31d1b76-8299-11e7-9f58-396a39c00bde.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?):  
OS X 10.11.6 (El Capitan)  
- Brave Version (revision SHA):  
https://github.com/brave/browser-laptop/commit/ad92d029e184c4cff01b2e9f4916725ba675e3c8
- Can this issue be consistently reproduced?
yes

@luixxiul Thank you for create this issue. I'm always in trouble this :-(

**Comment by luixxiul** [comment]
It looks like this issue is not limited to autofill then.

**Comment by pullingour** [comment]
@dev Thank you guys this problem is solved :-D  
I don't know where to write thanks message for developers.

**Comment by bsclifton** [comment]
title updated per above notes

**Comment by luixxiul** [comment]
It is not limited to about pages. See: https://github.com/brave/browser-laptop/issues/9604#issuecomment-322682310

**Comment by luixxiul** [comment]
https://community.brave.com/t/its-not-friendly-to-type-chinese-in-location-bar/3740

> I got a problem when I was trying to input Chinese in location bar.
> <img src="https://discourse-cdn-sjc1.com/standard2/uploads/brave/original/2X/2/2e81f35997a9367b38524bccbf75ec37dda54cc8.gif" width="318" height="36">
> There is a process to choose correct characters before then put in box.
> But it directly gets the first few letters in. Because the autocomplete mechanism.
> So far, I have to type a space first. Then type the Chinese characters for search.

**Comment by bsclifton** [comment]
yikes- thanks for clarifying, @luixxiul- I think we should bump it up in priority

**Comment by bsclifton** [comment]
@darkdh you fixed this one, right?

**Comment by darkdh** [comment]
Yes
