### ISSUE TITLE
Cannot View Certificate with PDFs

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#9607]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
If you are viewing a PDF over HTTPS, clicking View Certificate does nothing.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.16.9 (fba98fc)

- Steps to reproduce:
    1. Open a PDF over HTTPS (e.g. https://letsencrypt.org/documents/LE_WebTrustforCA.pdf).
    2. Click the "lock" icon to show security details.
    3. Click View Certificate.
    
- Actual result:
Nothing happens.

- Expected result:
The certificate info panel should open.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Probably.

- Is this an issue in the currently released version?
Yes, 0.16.9.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open a PDF over HTTPS (e.g. https://letsencrypt.org/documents/LE_WebTrustforCA.pdf).
    2. Click the "lock" icon to show security details.
    3. Click View Certificate.
    4. Make sure the certificate info panel is shown.

- Screenshot if needed:
None.

- Any related issues:
None.

**Comment by Jacalz** [comment]
I was able to reproduce on windows 10 too

**Comment by Liunkae** [comment]
Still broken in 0.18.29.
