### ISSUE TITLE
Unpinning tab intermittently does not display the title on tabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9608]
**Describe the issue you encountered:** Unpinning does not display the title on tabs.

![clipboard01](https://user-images.githubusercontent.com/3362943/27348483-2d34b674-562f-11e7-801a-fbc90358e23e.jpg)

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 02a7878

- Steps to reproduce:
    1. Open a dashboard
    2. Open some pages via the tiles
    3. Pin them
    4. Unpin one of them
    
- Actual result: See above. The title got displayed by opening a new tab.

- Expected result: the title should be displayed. 

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by cezaraugusto** [comment]
- hovering over element does not change state
- switching element does change state
- pinning one tab is not reproducible
- pinning 2+ tabs is easily reproducible

**Comment by srirambv** [comment]
Tried 4 times on different tile items. Issue seems fixed 👍
