### ISSUE TITLE
"Close tab page" does not close the tab page with only new tabs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9609]
**Describe the issue you encountered:** "Close tab page" does not close the tab page with only (a) new tab(s).

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.3

- Steps to reproduce:
    1. Set the max tabs number of 1 tab page to `6`
    2. Open an external site in the 1st tab
    3. Open 6 blank tabs
    4. Open the 2nd tab page (with one new tab)
    5. "Close tab page" on the active indicator on tabs bar
    
- Actual result: it does not close the tab page. 

    vi. Select the 1st tab page
    vii. "Close tab page"
    viii. the only 1st tab is closed and you get 6 new tabs unclosed

- Expected result: it should close the tab page

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
dup of #9420
