### ISSUE TITLE
gmail pop-out window does not close when selecting pop-in button/option

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9610]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When composing an email on mail.google.com and trying to 'pop-in' a new message which I had already chosen the 'pop-out' option for, the extra popup window does not close automatically.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):

Name	Version
Brave	0.17.3
rev	02a7878
Muon	4.0.3

- Steps to reproduce:
    1. Open mail.google.com and login.
    2. Select the 'Compose' button. New message is displayed within the browser.
    3. Locate the double arrow (upper right corner of the new message).
    4. Shift + click on this icon.
    5. New Message is opened in a popup window as expected.
    6. Locate the arrow pointing down and to the right (upper right corner of the new message).
    7. Click on this icon. 
    8. New message window stays open as well as opens up back in the browser. 
    
- Actual result:
New message window stayed open in a separate popup in addition to opening back in the first window.

- Expected result:
In step 8 the new message window should have closed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Possibly related: https://github.com/brave/browser-laptop/issues/9420

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/13370
