### ISSUE TITLE
Swipe Navigation Sensitivity Setting

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#9615]
## Test plan

https://github.com/brave/browser-laptop/pull/9617#issue-237356717

----

<img width="138" alt="screen shot 2017-06-20 at 10 42 46 am" src="https://user-images.githubusercontent.com/11330831/27356725-7bc96570-55c4-11e7-99a4-37511e5f06b4.png">
similar to system setting

**Comment by LaurenWags** [comment]
All settings are working except the shortest one. Repro'd by @kjozwiak on MacOS as well.  cc @darkdh
