### ISSUE TITLE
child window doesn't close

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#9622]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Feedly login window doesn't close after login

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.16.9

- Steps to reproduce:
    1. Go to feedly.com
    2. Click on "Existing User"
    3. Login with Google
    
- Actual result:
Feedly logs in correctly, but login window stays open

- Expected result:
Login window should close

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues: #9610 #9424 #9697 #9669 #9117

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/not-closing-authentication-window/8374?u=eljuno

Authentication window is not closed after login.
- Go to a site like theverge where you can login using credentials from google/facebook/twitter.
authenticate

Expected: after login, the authentication window closes
Actual Result: The authentication window remains open 

Brave: 0.19.23
rev: 7941690ada962e67f7881c442ca4fec533a9f699
Muon: 4.4.25
libchromiumcontent: 61.0.3163.100
V8: 6.1.534.41
Node.js: 7.9.0
Update Channel: Beta
OS Platform: macOS
OS Release: 17.0.0
OS Architecture: x64

**Comment by sushantkumr** [comment]
facing a similar behavior on saavn.com, when logging in using facebook

**Comment by eljuno** [comment]
Similar to #13370?

**Comment by bsclifton** [comment]
@eljuno great catch- that's it 😄 Closing as a dupe
