### ISSUE TITLE
Copy text keyboard combo does not create top level menu flash like other keyboard combos

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9624]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While testing various keyboard combos, I discovered that cmd+c on os x was not flashing the top level menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.16.9

- Steps to reproduce:
    1. highlight some text
    2. use cmd + c any number of times
    3. observe 'Edit' top level menu
    
- Actual result:
No visual indication is given that copy has occurred leading to doubt in the user as to whether they combo was recognized.

- Expected result:
The top level menu should flash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bbondy** [comment]
I think this is due to a hack we have in place for copy intermittently not working on mac.

**Comment by Liunkae** [comment]
This is working correctly now. Not sure when it changed. Tested with Brave 0.19.131 on macOS 10.13.

**Comment by bsclifton** [comment]
@Liunkae awesome! thanks for the report. I'll close and move to 0.19.x hotfix 13 so we can confirm
