### ISSUE TITLE
Make session restore remember frame bfcache / history

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#963]

**Comment by bridiver** [comment]
`NavigationController` has several methods to facilitate this. `GetEntryAtIndex`, `GetCurrentEntryIndex` and `Restore`. We can add methods to the electron webcontents api to dump and restore the `NavigationEntry`s. I would recommend writing a v8 converter for `NavigationEntryImpl` that converts it to a `DictionaryValue` similar to `HttpResponseHeaders` and we can serialize the resulting javascript objects in the session store.

**Comment by bbondy** [comment]
cc @bsclifton

**Comment by bsclifton** [comment]
This would be a great one :smile: I'd love to check this out

**Comment by bridiver** [comment]
we should bring in the chrome TabRestoreService for this from `component/sessions`

**Comment by bsclifton** [comment]
I'm assigned to this, but anyone who was wanting to get their feet wet w/ our electron fork (or if you had free cycles @bridiver) please feel free to grab this :smile:

**Comment by bsclifton** [comment]
This is resolved with [brave-core](https://github.com/brave/brave-browser)
