### ISSUE TITLE
Extension Request : Patricott

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9630]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A user from community would like support for https://chrome.google.com/webstore/detail/patricott-enabling-the-pa/bjomalfbejdddhihiacedoekfbdkhoea

**Comment by bsclifton** [comment]
When we move to [brave-core](https://github.com/brave/brave-browser) (which is just around the corner), we should have full support for extensions. Stay tuned 😄
