### ISSUE TITLE
Browser crashes by pinning sites, reordering them, and visiting a site via dashboard

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9635]
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

Also make sure that the STR below does no longer crash the browser

----

**Describe the issue you encountered:** Browser crashes by pinning sites, reordering them, and visiting a site via dashboard.

![a](https://user-images.githubusercontent.com/3362943/27373626-fd84447e-56a3-11e7-9e13-e779e3484bfc.gif)

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Clear the browser profile
    1. Open https://badssl.com
    2. Open 5 domains from `https-everywhere` to `longextended...`
    3. Pin all of them, including the parent tab
    4. Reorder them randomely
    5. Open a dashboard
    6. Click the twitter tile
    7. Pin the twitter tab
    8. Crash!
    9. Restart the browser
    10. Confirm you have the pinned twitter page at the front of the pinned tabs row

- Actual result: the browser crashes

- Expected result: it should not

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9333

**Comment by benpro** [comment]
For me it is even more rapid to crash.
Just pin a tab and sometimes it will crash the browser... No need to move the pinned tabs.
```
Brave: 0.17.13 
rev: f7242c7ae683191b59388f567ccbd13d938b23d4 
Muon: 4.1.7 
libchromiumcontent: 59.0.3071.109 
V8: 5.9.211.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.9.0-3-amd64 
os.arch: x64
```

**Comment by LaurenWags** [comment]
@petemill I'm seeing twitter tab pinned in step 8 at the end of the pinned tabs, not front (per last step). it remains in the same spot after restarting the browser. Is this expected? 
![screen shot 2017-12-20 at 5 24 40 pm](https://user-images.githubusercontent.com/28145373/34231603-b8291a6c-e5aa-11e7-9176-a178fe9f29c2.png)

**Comment by srirambv** [comment]
Same behaviour on Windows also what @LaurenWags mentioned
