### ISSUE TITLE
No label on the Publisher Toggle button in URL bar

### ISSUE THREAD

**Issue by lol-russo** [brave/browser-laptop#9640]
- Did you search for similar issues before submitting this one?

Yes

- Describe the issue you encountered:

When hovering on the enable/disable publisher toggle button that sits to the right of the url bar, it doesn't show a label/tooltip which is the expected behavior, especially for a feature that is unique to Brave and needs more explaining/affordances. See screenshots below - expected behavior is what happens on the Forward/Back/Bookmark buttons (title attribute shows a label on mouse hover)

I've had a look and it seems like this is the desired title text but for some reason it isn't showing:
```
disabledPublisher.title=Click to enable this publisher for payments
enabledPublisher.title=This publisher is enabled for payments. Click to disable
```

**macOS 10.12.5**

**Brave v 0.16.9**

- Steps to reproduce:
  
1. Turn on Brave Payments
2. Hover mouse over Payments button on right side of the URL bar
    
- Actual result:
![image](https://user-images.githubusercontent.com/19835679/27382143-f2f902cc-56c8-11e7-80b9-7f0f1f79c43f.png)
There is no label on hover

- Expected result:
<img width="176" alt="screen shot 2017-06-21 at 8 47 27 pm" src="https://user-images.githubusercontent.com/19835679/27381173-26452d4e-56c5-11e7-8b90-039daa0e5de2.png">
Label should appear on hover, like it does for other buttons

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

- Any related issues:

**Comment by luixxiul** [comment]
I confirmed the issue on Windows 10, 0.16.9

**Comment by luixxiul** [comment]
Also I noticed that the icon slightly fades in/out, which should be removed because bookmark star icon doesn't do.
