### ISSUE TITLE
"possible EventEmitter memory leak detected"

### ISSUE THREAD

**Issue by crysman** [brave/browser-laptop#9643]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:

> ❱ brave
> Crash reporting enabled
> [4680:4680:0621/142320.244339:ERROR:CONSOLE(33239)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/usr/share/brave/resources/app.asar/app/extensions/brave/gen/app.entry.js (33239)
> [4680:4680:0621/142320.250645:ERROR:CONSOLE(33239)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/usr/share/brave/resources/app.asar/app/extensions/brave/gen/app.entry.js (33239)

- Platform (Win7, 8, 10? macOS? Linux distro?):
GNU/Linux Xubuntu 16.10

- Brave Version (revision SHA):
Brave	0.16.12
rev	72624a2

- Steps to reproduce:
    1. open terminal
    2. run brave

**Comment by bsclifton** [comment]
I don't believe this is serious (it's actually mostly a false positive)- we had fixed the real cases, IIRC

cc: @bbondy and @bridiver who are more familiar with this

**Comment by srirambv** [comment]
Has been verified here https://github.com/brave/browser-laptop/issues/8244

**Comment by bbondy** [comment]
It is just because each redux component registers for an event now and it passes the constant threshold for that warning. Let's leave this open just to track removing that warning.

**Comment by kenorb** [comment]
Btw. `%d listeners added` should be populated with the number I guess.
