### ISSUE TITLE
Difficult to return from TOO_MANY_REDIRECTS endpoint

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9648]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If/when the browser encounters 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.17.3

- Steps to reproduce:
    1. Navigate to a page that causes _too many redirects_ (may tough to find one)
    2. Press mouse's back button (or browser's back button)
    
- Actual result:
URL changes to the previous URL, but page does not.

- Expected result:
Browser navigates backwards to the last working page.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1. Press the Back button on the _TOO_MANY_REDIRECTS_ page works.

- Screenshot if needed:

![no-return](https://user-images.githubusercontent.com/815158/27404481-d794fd18-5693-11e7-98d1-8c139dac2068.gif)

**Comment by ryanml** [comment]
@bsclifton @jonathansampson I am not able to reproduce this off of master or the current release

I set up a testing URL that will throw the too many redirects error [here:](http://ryanlane.se/too-many-redirects)

Screencast:
![redirect-example](https://user-images.githubusercontent.com/8732757/36393638-a5562fae-156d-11e8-9e2f-65a4cedaedb0.gif)

I'll take this one on if there are STR in the end that produce this :) thanks

**Comment by ryanml** [comment]
(Sorry for the huge screencast)
