### ISSUE TITLE
update to HTTPS Everywhere 5.2.19

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9649]
https://www.eff.org/files/https-everywhere-5.2.19-eff.xpi

**Comment by diracdeltas** [comment]
subtickets: https://github.com/brave/browser-laptop/issues/5634, #9419,

**Comment by diracdeltas** [comment]
https://github.com/brave/https-everywhere-builder has been updated to 5.2.19 so this just needs @bsclifton to verify that the uploader is working

**Comment by bsclifton** [comment]
Uploader should be working great- (it's only pushed to staging at the moment)

@diracdeltas let me know how the testing goes and we can push to prod when ready 😄  (IIRC, we just needed to try Android?)

**Comment by diracdeltas** [comment]
thumbs up from iOS, laptop, and android
