### ISSUE TITLE
Google One Tap form authentication

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9657]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
Reported on community 
>Google's One Tap form authentication doesn't seem to work properly. I receive the message on my phone via Google app to authenticate my login but the page when I'm on Brave doesn't recognize it. Or at least there is some kind of time out message.
>
>Also, "remember me" is checked on the form but it still asks me to login whenever I visit the page (youtube.com in particular).

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/google-one-tap-form-authentication/3796

**Comment by AdamBrodzinski** [comment]
I'm also having issues with this. To work around i'm using the alternate SMS pin to log in.

**Comment by luixxiul** [comment]
duping to #7866
