### ISSUE TITLE
private tab history shouldn't appear in autocomplete

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#966]
If you open a private tab and visit a site, the site will appear in the urlbar autocomplete in non-private tabs as well. It also appears in the autocomplete if you restart the browser, which suggests the private tab URL is getting written to disk.

**Comment by bbondy** [comment]
marked for 0.8

**Comment by diracdeltas** [comment]
:+1:

**Comment by diracdeltas** [comment]
I can't seem to repro getting a private tab URL in the autocomplete after browser restart, so I think that was a fluke.

**Comment by bbondy** [comment]
Surprised because of this check
https://github.com/brave/browser-laptop/blob/05a31e6386f2cea921a978cf557e9771f9af62f7/js/components/frame.js#L275

**Comment by diracdeltas** [comment]
My bad, it looks like it was appearing in autocomplete because it was a currently open tab, not because of history.

**Comment by diracdeltas** [comment]
dupe of #140
