### ISSUE TITLE
Webview crash on YouTube after a while of inactivity 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9663]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Webview crash on YouTube after a while of inactivity 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.6 upgraded from 0.17.4
rev	30a3eee
Muon	4.1.2

- Steps to reproduce:
    1. Open any YouTube video
    2. Pause the video and background the tab for a while
    3. Switch to the tab to continue playing, Web view crash on the tab,  Trying to type in URL causes #8574
    
- Actual result:
Webview crash on YouTube after a while of inactivity 

- Expected result:
Should not crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Found on upgrade from previous build

- Is this an issue in the currently released version?
Not sure

- Can this issue be consistently reproduced?
Not sure 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
Console Error 
![image](https://user-images.githubusercontent.com/17010094/27441589-e93e7b8e-5765-11e7-9614-aa6311434820.png)

- Any related issues:

**Comment by srirambv** [comment]
Still seeing webview crash on pages after some inactivity for a while, but no error in console
![image](https://user-images.githubusercontent.com/17010094/27482019-8c59bad4-5817-11e7-8e9e-afcd1a0eb5b2.png)

cc: @bsclifton @NejcZdovc

**Comment by NejcZdovc** [comment]
Yeah this is something that I was talking about. I only added null checkers so that we don't get in to the state where you have `null` for the frame. But I don't know (didn't do any research) why is youtube crashing.

**Comment by bsclifton** [comment]
I've been unable to repro this on macOS; will try on Windows next

**Comment by bsclifton** [comment]
I'm going to close this issue as the original reported issue is indeed fixed (ex: no errors showing in the browser console).

I've spent about 20 minutes trying to repro the dead tab issue (which should be logged as a separate issue) on both macOS and Windows and have not been successful

**Comment by srirambv** [comment]
Not seeing any webview crash on YouTube on 0.17.9
