### ISSUE TITLE
Toggling Search match case in quick succession fails to perform search

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9666]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Toggling Search match case in quick succession fails to perform search

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.6
rev	30a3eee
Muon	4.1.2

- Steps to reproduce:
    1. Clean Install 0.17.6
    2. Open any site and perform a search in page
    3. Change the text and toggle Match case
    4. Press enter in quick succession and toggle the match case switch again 
    5. Perform a new search, nothing happens, console shows error
    
- Actual result:
Toggling Search match case in quick succession fails to perform search

- Expected result:
Should not show error and perform search

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Not sure

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27447799-59e23c0e-577a-11e7-91a2-0963b68c5cd6.png)

- Any related issues:
cc: @NejcZdovc @bsclifton

**Comment by bsclifton** [comment]
@srirambv is this a duplicate of https://github.com/brave/browser-laptop/issues/4211?

**Comment by srirambv** [comment]
@bsclifton No this is a different issue where it doesn't perform search at all. Btw #4211 seems fixed for me on Windows with the 0.17.19 build.
![4206](https://user-images.githubusercontent.com/17010094/28403570-320de526-6d1d-11e7-82a9-1e6f44ce25ec.gif)
