### ISSUE TITLE
Web notification bar doesn't always show the carat symbol pointing to the source tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9668]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Web notification bar doesn't always show the carat symbol pointing to the source tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.17.6
rev	30a3eee
Muon	4.1.2

- Steps to reproduce:
    1. Open google.com in a tab, see notification bar has a carat symbol to show which tab set it
    2. Visit http://www.bennish.net/web-notifications.html , click on show notification
    3. No carat shown on the notification bar to indicate the source tab
    
- Actual result:
Web notification bar doesn't always show the carat symbol pointing to the source tab

- Expected result:
All notification should show the carat to show source tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
May be

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27448647-6ebbd24a-577d-11e7-99da-901bb66e9aec.png)

- Any related issues:
cc: @jonathansampson

**Comment by jonathansampson** [comment]
Another repro of this is to run the following from any tab:

```js
new Notification('hello', { body: 'world' })
```

The difference between the two notification bars is simple:

```diff
<div class="tabArea">
+     <div class="caretWrapper_1tga0yq">
+         <div class="caretWrapper__caret_1q8em8n"></div>
+     </div>
    <div class="tab_1cvhmm-o_O-tabForWindows_1uuan5a-o_O-active_gqpfkf-o_O-themeColor_abero2" data-test-id="tab" data-test-active-tab="true" data-test-pinned-tab="false" data-test-private-tab="false" data-frame-key="6" draggable="true" title="Google">
        <div class="tabId_15plfjq">
            <div class="icon_12ftjtl-o_O-favicon_1t9f66i" data-test-favicon="https://www.google.com/images/branding/product/ico/googleg_lodp.ico" data-test-id="defaultIcon"></div>
            <div data-test-id="tabTitle" class="tabTitle_174f4a0-o_O-gradientText_tik5oy-o_O-tabTitleForWindows_1eydwe9">Google</div>
        </div>
        <div class="" draggable="true" data-test-id="closeTabIcon" data-test2-id="close-icon-off"></div>
    </div>
</div>
```
