### ISSUE TITLE
Store lastDataFileSize and do comparison 

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#967]
Android had a problem where data files weren't always the full file.  This is probably because the process was killed while it was being downloaded or written.  
We should also store the content length from the content length http header and do a comparison.  If it changed then re-download.
The read size must match the header to use it.

CC @garvankeeley would be good to have this on all platforms.

**Comment by bbondy** [comment]
CC @diracdeltas I think this is where the sqlite surplus of crashes was routing from as well.

**Comment by garvankeeley** [comment]
interesting! I was wondering how you were getting a corrupt file. iOS has 'atomic' flags on the operations I use (which means things happen to a temp file first) and then 'atomically' move to their final destination, which is done as a single filesystem rename call. It is considered failsafe to do this.

**Comment by bbondy** [comment]
ok great, so no change needed on iOS, I think this is possibly a bug on laptop though.
