### ISSUE TITLE
Deleting extension folder and re-enabling it shows __MSG__

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9670]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Deleting extension folder and re-enabling it shows __MSG__

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.6
rev	30a3eee
Muon	4.1.2

- Steps to reproduce:
    1. Enable Pocket, on a clean install 
    2. Close browser and delete pocket extension folder from `%appdata%\brave\extensions`
    3. Launch browser and re-enable extension , Extension icon is broken and name shows `__MSG__`
    
- Actual result:
Deleting extension folder and re-enabling it shows __MSG__

- Expected result:
Should show proper name and icon

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27455233-81aecef4-5794-11e7-9db5-57ab4822500b.png)

- Any related issues:
#8307
cc: @jonathansampson

**Comment by srirambv** [comment]
Update: Restarting browser shows the broken image and `__MSG__` name, reloading the page shows the correct icon and extension name

**Comment by jonathansampson** [comment]
@srirambv Is this something the average user would ever need to do?

**Comment by srirambv** [comment]
That's a trick question to answer.  :smile:  

May be an average user might never do but anyone who know where extensions are installed would want to delete the installed extension and try reinstalling it fresh would run into this problem
