### ISSUE TITLE
Tear off last tab to window causes original windows last tab to be shown in white

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9671]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tear off last tab to window causes original windows last tab to be shown in white

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.6
rev	30a3eee
Muon	4.1.2

- Steps to reproduce:
    1. Clean install 0.17.6
    2. Open a bunch of tabs and load pages in them
    3. Tear off the last tab into a window, on first window the last tab is white, clicking on the tab shows the webview again
    
- Actual result:
Tear off last tab to window causes original windows last tab to be shown in white

- Expected result:
Should not show white blank page in original window

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Not checked

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tear_off](https://user-images.githubusercontent.com/17010094/27455791-697779ce-5796-11e7-94a9-676acb52e594.gif)

- Any related issues:
#4113 #8128 
cc: @bridiver @bbondy

**Comment by iSasFTW** [comment]
I'd like to add that this also happens to me when closing a tab. The tab it automatically jumps to will be white. I can fix it by opening a new tab, going back to the white tab, and closing the new tab I just created.

**Comment by bsclifton** [comment]
Still an issue on 0.17.11 (thanks @srirambv for confirming)

**Comment by Liunkae** [comment]
+1 from me. Still a problem in 0.18.22 (d850e28).

**Comment by jonathansampson** [comment]
+1 Repros for me in 0.19.1 (https://github.com/brave/browser-laptop/commit/2ee7a49a3ba67de3aae28504ae9cd6a13c99dffa)
