### ISSUE TITLE
Editing a bookmark (or folder) locks up the browser

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9674]
## Test plan

https://github.com/brave/browser-laptop/pull/9710#issue-238468771

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bringing up the modal used to add/edit bookmarks/folders is horribly slow

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.17.6

- Steps to reproduce:
    1. Have a decent number of bookmarks (maybe 500 - 1,000) and a good amount of history
    2. Right click on bookmarks toolbar, pick `Add folder`
    3. Browser is frozen
    4. Wait 4 seconds or more for the modal to show up
    5. Try typing into the textbox (giving a name to the folder)
    6. Notice that typing is extremely lagged. It's unusable
    
- Actual result:
The browser freezes up and visibly shows the lag (often turning mouse into beach ball icon)

- Expected result:
The UI should be responsive and snappy

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Assigning to @NejcZdovc; this may be improved by some of the upcoming redux component work / optimizations

**Comment by NejcZdovc** [comment]
Ok found one real bottle necks.

First: https://github.com/brave/browser-laptop/blob/master/app/renderer/components/bookmarks/addEditBookmarkHanger.js#L181

If I disabled this line I get computed time for merge props:
![image](https://user-images.githubusercontent.com/9574457/27527097-3c667eec-5a4a-11e7-952b-ae2403ac80ee.png)

If I enabled the first one:
![image](https://user-images.githubusercontent.com/9574457/27527178-9add25ca-5a4a-11e7-9c70-735a601367e4.png)

(this one can be improved, but it's not a bottle neck) Second: https://github.com/brave/browser-laptop/blob/master/app/renderer/components/bookmarks/addEditBookmarkHanger.js#L187

Test was done with bookmark export provided by @bsclifton (it has lizard people in and some other bookmarks cca 10k)

**Comment by bigkahuna1uk** [comment]
This is still happening for the latest Brave release. Browser is completely locked up and has to be killed. 


Name | Version
-- | --
Brave | 0.18.14
rev | ad92d02
Muon | 4.3.6
libchromiumcontent | 60.0.3112.78
V8 | 6.0.286.44
Node.js | 7.9.0
Update Channel | dev
OS Platform | macOS
OS Release | 16.7.0
OS Architecture | x64

**Comment by NejcZdovc** [comment]
@bigkahuna1uk this will be fixed in 0.19.x version. Coming really soon
