### ISSUE TITLE
Saving wallet backup keys is not loading  the page

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9677]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
files are not opened correctly
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
705b4e4
- Steps to reproduce:
    1. Go to payment and enable it
    2. Click on gear icon
    3. Click backup ledger keys
    4. Download keys
    5. New tab is opened
    
- Actual result:
Infinite loading
- Expected result:
File is loaded
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
ye
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/9574457/27493464-3838096e-584a-11e7-9ea0-561730a19ce4.png)

- Any related issues:

**Comment by NejcZdovc** [comment]
I think this is a problem with muon, because this logic was not changed and we are calling `webContents` directly https://github.com/brave/browser-laptop/blob/master/app/ledger.js#L376. On this line we get correct file url.

**Comment by bridiver** [comment]
that method should be checking to see if `webContents` is null. Without that check (and the second `error` param) it's hard to know what the problem is

**Comment by bridiver** [comment]
actually the usage there doesn't make sense. If we are opening the tab with the file url there is no reason to call `downloadURL` and it might be breaking now because the download behavior was fixed here https://github.com/brave/browser-laptop/commit/f86a8a40700ba9177a37fa72a5ed12728583f9b1

**Comment by NejcZdovc** [comment]
yeah this could be the case, nice find

**Comment by NejcZdovc** [comment]
Ok, we need to rework it then

**Comment by NejcZdovc** [comment]
Revert #10167 when this is fixed

**Comment by luixxiul** [comment]
@davidtemkin is this blocking 0.19?

**Comment by alexwykoff** [comment]
@NejcZdovc when you have a moment please give this another spin

**Comment by NejcZdovc** [comment]
this is still a problem, we get crashed tab, so you can't close it or select it

**Comment by NejcZdovc** [comment]
+1 from #12221

**Comment by NejcZdovc** [comment]
fixed with #13279

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
