### ISSUE TITLE
Can't properly cycle through pinned tabs using Cmd+[number]

### ISSUE THREAD

**Issue by tarciosaraiva** [brave/browser-laptop#968]
I usually leave 3 pinned tabs open and then other tabs after that. I cycle through them using `Cmd+[number]` or `Cmd+Shift+[curly braces]`

Basically the order is all messed up:
- `Cmd + 1` takes me to the first unpinned tab
- `Cmd + 2` takes me to the second unpinned tab
- `Cmd + 3` takes me to the first pinned tab

I opened the 3rd (pinned) tab before I opened the first (pinned) tab. The order above doesn't make much sense.

Would love to be able to navigate through my tabs using numbers / curly braces in the order I see them.

**Comment by cwmke** [comment]
I would also like to add that I think the pinned tabs should automatically be Ctrl+1, Ctrl+2... in the order they appear in the bar.  Right now I have one pinned tab with several other tabs open but my pinned tab is is Ctrl+6.

**Comment by diracdeltas** [comment]
I think this is a dupe of #149. Seems like everyone agrees the expected numbering is the order they appear in the tab bar.

**Comment by tarciosaraiva** [comment]
I'm happy to close it, since it's mapped somewhere else! Thanks for the good work guys!
