### ISSUE TITLE
Individual bookmarks not synced from laptop after Payments are switched off

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9684]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Toggling Payments on --> off appears to break sync.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave	0.17.7
rev	21cf3d1
Muon	4.1.3

- Steps to reproduce (two ways)
One
    1.  Switch payments on in Preferences. (I waited until my wallet was created)
    2. Switch payments off in Preferences. 
    3. Set up folders and bookmarks on laptop.
    4. Set up folders and bookmarks on another device (I used Android and iOS).
    5. Set up sync group on laptop. Open sync background page.
    6. Join sync group on Android and iOS. All devices are synced as expected.
    7. I did an import, this also synced as expected.
    8. Add a bookmark on laptop to bookmarks bar. 
    9. This bookmark does not get synced. 

Two:
1. Sync devices (ex. laptop and Android)
2. Perform simple sync test (add bookmark to bookmarks bar on laptop), sync is working as expected.
3. Switch on payments.
4. Add bookmark to bookmarks bar on laptop. Sync is working as expected.
5. Turn off payments.
6. Again, add bookmark to bookmarks bar on laptop. This bookmark will not be synced.
    
- Actual result:
Bookmark added to bookmarks bar is not synced.

- Expected result:
Bookmark should be synced.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Add bookmark on Android. Bookmark is synced to laptop and iOS.
    2. Add bookmark on iOS. Bookmark is synced to laptop and Android.
    3.

- Screenshot if needed:
Covers steps 8 and 9 from the first scenario (it's a long recording)- 
![111_01](https://user-images.githubusercontent.com/28145373/27496360-9ff57324-5823-11e7-8e96-b0946cce78ce.gif)

- Any related issues:

**Comment by LaurenWags** [comment]
Moved to https://github.com/brave/browser-laptop/issues/9684

**Comment by alexwykoff** [comment]
I couldn't replicate this 0.17.7

**Comment by Jacalz** [comment]
Can not repro on 0.17.9 with 17.06.21.14 on iOS, maby this should be moved to android?

**Comment by bbondy** [comment]
Please re-open if you see this problem again.
