### ISSUE TITLE
Sometimes no active tab is selected after closing a tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9686]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Closing a tab can sometimes lead to no active tab being set. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, but probably all.

- Brave Version (revision SHA):
0.17.7

- Steps to reproduce:
    1. Open a bunch of tabs, make a google docs spreadsheet the active one.
    2. Command+W
     
- Actual result:
You may find that there's no active tab set after the tab close.
Shift+F8 gives console error pointing to frame.get where frame is undefined in AudioTabIcon component.

- Expected result:
Should close and select a new tab as active.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I don't think it's more or less likely on a new profile.

- Is this an issue in the currently released version?
I don't think so.

- Can this issue be consistently reproduced?
No.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/9687
