### ISSUE TITLE
Sync options should be synced

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9695]
**Describe the issue you encountered:** sync setting should be synced. If you are sync'ing another profile with ones where browsing history has been sync'd, the new one should sync the history as well. Prompting a dialog for setting would work.

I'm suggesting it because I couldn't find if browsing history was actually sync'd after switching the setting since there was no indication of that.

- Brave Version (revision SHA): 0.16.9

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #7315

**Comment by NejcZdovc** [comment]
I am not sure if I like this and it should be opt in (like we have now) and not opt out. Because when we sync to mobile I personally wouldn't like to have same sync options that I have for desktop. And when you are syncing between 3 desktops, on one I would only like to sync data from others, but not syncing out of this computer.

**Comment by bsclifton** [comment]
I renamed the issue to be more clear- this issue is proposing syncing the options chosen for sync

I agree with @NejcZdovc; if this is implemented, it should be an opt-in (a checkbox with "use these sync options across all devices")

cc: @bradleyrichter @ayumi @diracdeltas

**Comment by luixxiul** [comment]
Is it possible that the browsing history gets deleted, if you have used Sync only with one machine to create backup, create a new profile folder (as the current profile was corrupted for example) and then sync the new profile with the passphrase for the Sync account, because `browsing data` is disabled by default on the new profile folder?

That idea occurred to me as I saw many `DELETE` commands have been fired on the background page.

I reproduced the issue both on macOS and Windows. Nothing except bookmarked pages are listed on `about:history`.

Here is the STR:
1. save your passphrase
2. close the browser
3. move the profile folder to another place
4. start the browser
5. enable sync
6. enable `browsing history`
7. open background page `chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/_generated_background_page.html`
8. wait until sync is finished
9. open `about:history` (edited)

Actual result: there are only bookmarked pages

Expected result: history should be restored
