### ISSUE TITLE
Fix strange color of brave menu button when alert is displayed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9696]
## Test plan

See the 3rd commit of https://github.com/brave/browser-laptop/pull/10951#issue-257657727

----

**Describe the issue you encountered:** Fix strange color of brave menu button when alert is displayed.

See: https://github.com/brave/browser-laptop/issues/9285#issue-233868886

- Platform (Win7, 8, 10? macOS? Linux distro?): 0.16.9

- Actual result:
  ![clipboard02](https://user-images.githubusercontent.com/3362943/27508209-11b2412a-591b-11e7-930a-c8e4bfa681ad.jpg)

- Expected result: instead of applying opacity, change the color to grey, with the counter.
  <img width="34" alt="screenshot 2017-09-22 16 20 15" src="https://user-images.githubusercontent.com/3362943/30733758-550b55d6-9fb3-11e7-8816-232b41110eea.png">

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: https://github.com/brave/browser-laptop/issues/9285#issuecomment-310832912

**Comment by alexwykoff** [comment]
@luixxiul is this still a bug? What are the actual STR?

**Comment by bsclifton** [comment]
@alexwykoff you can repro by running the following:
https://jsfiddle.net/6zj4sjxr/

I don't think it's a bug- I actually prefer how it looks (since grayed out looks like nothing is blocked).  But I think it's a good one to talk about 😄

**Comment by bsclifton** [comment]
cc: @bradleyrichter @jenn-rhim

**Comment by luixxiul** [comment]
I felt it was weird as the counter block background color was not changed.

**Comment by bradleyrichter** [comment]
If this state seems correct, then we need to add a disabled style for the counter block so it doesn't look broken.

**Comment by luixxiul** [comment]
The same opacity value applied to the disabled button will be applied to the counter block as well.

<img width="34" alt="screenshot 2017-09-22 16 20 15" src="https://user-images.githubusercontent.com/3362943/30733758-550b55d6-9fb3-11e7-8816-232b41110eea.png">

**Comment by srirambv** [comment]
Verified on Windows x64 using
* 0.23.8 06c657b
* muon 6.1.5
* libchromiumcontent 66.0.3359.181
