### ISSUE TITLE
LastPass widget does not open window

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9697]
**Describe the issue you encountered:** LastPass widget does not open a window.

This bug is annoying as it does not let you edit passwords, open My Vault, preferences page, etc. 

Because you can clear the extensions setting only by clearing your profile, you will never be able to edit anything from the widget until the bug is fixed.

~~I assume this is the same issue as #9669 or related with it some way.~~

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. **Create a back up of profile (especially if you use LastPass on your default profile)**
    2. Open `about:preferences#extensions`
    3. Enable LastPass
    4. Log in
    5. Close the tabs
    6. Click LastPass extension icon
    7. Click `Preferences`
    8. Select `Windows` from `Open New Pages in`
    9. Save
    10. Repeat the step 6 and 7
    
- Actual result: Nothing is opened

- Expected result: A preference window should be opened

- Is this an issue in the currently released version?
  Yes.

- Can this issue be consistently reproduced?
  Yes.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
While I believe this has high impact and personally I would like to get this fixed asap, please triage its milestone based on priority. thanks!

**Comment by luixxiul** [comment]
added the nearest milestone in case

**Comment by alexwykoff** [comment]
This behaves the same in 0.16.9 so it's not a regression per se. I do agree it should be fixed soon.
