### ISSUE TITLE
install preview releases via apt

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9698]
**Describe the issue you encountered:**
Is it impossible to install preview releases via apt like `apt-get install brave-beta`, creating a separated profile folder `~/.config/brave-beta`?

Currently you have to uninstall the nightly to test developer and beta. Also they share the same profile, which seems to me to make it hard to detect which channel causes which issues.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
@luixxiul unfortunately when creating the previews, I have not been pushing the deb/rpm packages ☹️  There is a separate repo I believe for nightly?
