### ISSUE TITLE
Dragging and dropping a file onto the browser does not work

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9699]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Drag and drop is not working, because path is not in drop event.
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
435fa34
- Steps to reproduce:
    1. dnd one file to tabs toolbar
    
- Actual result:
White tab with infinite loader
- Expected result:
File is displayed
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
Problem is that drop event don't have path property and that's why it's not working

![image](https://user-images.githubusercontent.com/9574457/27509090-e0ebdbe4-58f4-11e7-9946-041c551e1ad5.png)

Image is from this LOC https://github.com/brave/browser-laptop/blob/b53a9c2bca8f7c8430576e0d445ded1f5576278a/js/components/tabs.js#L86

**Comment by bsclifton** [comment]
Fixed with these commits (Muon)
https://github.com/brave/muon/commit/d05505d68a5c89e031358fb63af57fc31d50a844
https://github.com/brave/muon/commit/c7ac9373783a6df769e91521ccbb46260bddc9bb

**Comment by bsclifton** [comment]
Moving to 0.18.x after experiencing issues trying to test it

**Comment by bridiver** [comment]
@bsclifton did you pull in the browser-laptop commit?

**Comment by bsclifton** [comment]
@bridiver no- but we can do that in 0.18 😄

**Comment by bsclifton** [comment]
pulling into 0.17.x since we need a new Muon 4.1.x version RE: extensions
