### ISSUE TITLE
Extensions request

### ISSUE THREAD

**Issue by hawkeye116477** [brave/browser-laptop#9707]
- Did you search for similar issues before submitting this one?
Yes

Please add DownThemAll! (or Turbo Download Manager and Turbo Download Manager Helper), Bulk Media Downloader, Flashgot, uBlock Protector Extension and Violentmonkey.

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of our community site.

https://community.brave.com/c/feature-requests/extension-requests

Let's talk about the suggestions there 😄
