### ISSUE TITLE
Restoring session after re-opening windows does not restore position

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9709]
## Test plan
1. Open preferences > general
2. Set `Brave starts with` to `My windows / tabs from last time`
3. Open a few windows- move them around and resize them
4. Exit Brave and reopen
5. Ensure window position was saved properly

## Original issue description
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Open multiple windows; move them into unique positions
    2. Close Brave
    3. Re-open Brave
    
- Actual result:
Window positions are stacked on top of each other (see screenshot)

- Expected result:
Window position should be saved

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/4733304/27526023-ac927412-59f7-11e7-984e-3b1642d95e7d.png)

- Any related issues:

**Comment by srirambv** [comment]
Need not be closed. Resizing the window and opening multiple windows causes it to stack on each other instead of cascading windows

**Comment by bsclifton** [comment]
@srirambv true- opening new windows does this too, but that is tracked with https://github.com/brave/browser-laptop/issues/8925 😄
