### ISSUE TITLE
urlbar suggestions linger after deleting input quickly

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#971]
1. focus urlbar, type 'goo' to bring up autosuggest
2. press and hold the delete key

expected result: when the input is fully deleted, the autosuggest box should disappear
actual result: the autosuggest box lingers

**Comment by luixxiul** [comment]
rel #241

**Comment by cezaraugusto** [comment]
Slightly different, but related to #1596 also.

**Comment by bsclifton** [comment]
@diracdeltas since you've been in the code recently, I wanted to ping you to see if this is still an issue

**Comment by diracdeltas** [comment]
@bsclifton thanks for the reminder. it hasn't happened in a while, so i'll close this.
