### ISSUE TITLE
Adding external filters lists by manual for Adblock

### ISSUE THREAD

**Issue by hawkeye116477** [brave/browser-laptop#9711]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Can you add adding external filters lists to Adblock by manual, because I want to add manually some additional filter lists, that are not present in additional filter lists in Adblock ?

**Comment by srirambv** [comment]
You can add manually adblock rules in `about:adblock` after the list. 

cc: @lukemulks

**Comment by hawkeye116477** [comment]
I know, but I would like to have ability to add/subscribe filter lists from URL's too.

**Comment by lukemulks** [comment]
This would be a good feature to add, imo.  

@hawkeye116477 let me know if this covers what you're thinking with this request.

**For example, if a user wanted to add a list from one of the lists on https://filterlists.com/ - let's say the `NoTrack Blocklist` :** 

- They could navigate to `about:adblock`
- `about:adblock` would have a form field available with a submit button to paste the URL.  
- They could drop the following URL in for the .txt file that points to the list: 
```
https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt
```
- They would click Submit to submit the filter list. 
- The custom filter list would be added among the other existing custom filter lists, which could then be toggled `on || off` , and have an `X` to remove from the custom filter lists if the user chooses.

Having this feature would allow us to give users that inquire about list-adds an option to add their own, in addition to our core-setlist of filters. 

**In combination with existing features, users would ultimately be able to exercise these controls:** 

1. add a custom filter (singular)
2. enable a regional filter list (from our existing set) 
3. add an additional filter list (proposed here) 

Seems pretty solid to me. 

cc: @bbondy & @bradleyrichter for feature visibility.

**Comment by hawkeye116477** [comment]
Yes, that was what I meant

**Comment by Sh1d0w** [comment]
+1 for adding support for enabling filters by url

Currently I can see the difference between Brave and Safari with uBlock origin. Safari blocks way more trackers and urls, than Brave, because I have enabled some additional filter lists from uBlock origin with just a single click.

Where with Brave, I not only have a visibility of the current blocked lists, nor I can add new ones easily.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/403
