### ISSUE TITLE
Only primitives in BookmarksToolbar and BookmarkToolbarButton

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9712]
## Test plan

https://github.com/brave/browser-laptop/pull/9713#issue-238516609

----

**Describe the issue you encountered:**
Only primitives in merge props. Because of that we need to move context menu functions into the reducer.

**Comment by LaurenWags** [comment]
@NejcZdovc in the test plan under '7 DND test' the second item (try to add a bookmark into a folder) is failing for me. It is logged here https://github.com/brave/browser-laptop/issues/11040#issuecomment-330866399
