### ISSUE TITLE
Closing all loaded tabs (leaving unloaded tabs) causes crash

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9717]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Closing all loaded tabs, which leaves the rest of your tabs being unloaded, causes Brave to crash

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows

- Brave Version (revision SHA):

- Steps to reproduce:
  1. Open 6 tabs, to 6 different sites
  2. Quite Brave, then Start again
  3. Close active tab
    
- Actual result:
Crash happens

- Expected result:
Focus should switch to one of the unloaded tabs; it should then load the tab

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
You can also repro by closing all _loaded_ tabs. When the only tabs left are _unloaded_, the crash occurs.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Repro'd on macOS; It's important to not have any pinned tabs.

I didn't see any error messages logged to stdout and the crash screen wasn't shown... it appears to have simply closed the window

**Comment by alexwykoff** [comment]
Confirmed on 0.17.9, checking 0.16.x to see if we've already shipped this or if it's a new regression.

**Comment by alexwykoff** [comment]
Confirmed this on 0.16.9 as well, all tabs lost on subsequent restart.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/ce8e85393982637e142e783bfee8efab9b78719d (which is in 0.18.x).  This issue is also a duplicate of https://github.com/brave/browser-laptop/issues/9506

**Comment by LaurenWags** [comment]
+1 from community https://community.brave.com/t/brave-browser-closes-when-closing-a-tab/4179

**Comment by bu5hm4nn** [comment]
+1 Happens on macOS 10.12.5 and on Windows 10 for me.

**Comment by jamesray1** [comment]
Another +1 from community:
https://community.brave.com/t/brave-browser-closes-when-closing-a-tab/4179/3?u=jamesray
