### ISSUE TITLE
LastPass white tab after adding Credit Card for Form Fill

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9723]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Adding a Credit Card in Last Pass extension (Form Fills > Add Credit Card) causes white tab to display. 
Originally reported by community (https://community.brave.com/t/lastpass-form-fills-often-fail/4243) and reproduced.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave	0.17.9
rev	2606974
Muon	4.1.4

- Steps to reproduce:
    1. Click on LastPass icon and select Form Fills > Add Credit Card.
    2. Fill out Credit Card information.
    3. Select Save.

    
- Actual result:
White tab is displayed.

- Expected result: 
Tab closes.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

cc: @jonathansampson @kevinlawler

**Comment by vanclute** [comment]
As an addition, I'm also having an issue right now where I can't add a credit card at all.  Selecting the Add Credit Card option from the LP menu, does nothing.  No window of any kind, no prompt, nothing.

**Comment by srirambv** [comment]
This is not specific to Autofill form. All preferences page for Lastpass has this issue when any setting is changed.
