### ISSUE TITLE
 Investigate: BusinessInsider (UK) blocking detection

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#9725]
Business Insider UK edition is prompting an anti-ad blocker when ad blocking is detected. 

Example URL:  http://uk.businessinsider.com/browser-privacy-bill-in-congress-faces-opposition-from-ad-industry-2017-6?r=US&IR=T

Confirmed on Mac OSX and Windows 10
Rev SHA	fba98fc

The following is displayed with ad blocking enabled: 

![brave-businessinsider-uk-prompt-06262017](https://user-images.githubusercontent.com/8979240/27563994-a278bd1e-5a89-11e7-90f1-d25c024049a0.PNG)

The button displayed for "Purchase Ad Pass" redirects the user to the Google Contributor page to sign up for an ad pass/micropayment subscription: 
https://contributor.google.com/v/intro?websiteid=5b33919a4cdd6ebb&refererurl=http%3A%2F%2Fuk.businessinsider.com%2Fbrowser-privacy-bill-in-congress-faces-opposition-from-ad-industry-2017-6%3Fr%3DUS%26IR%3DT

**Noteworthy**
- Business Insider UK is a Google Contributor partner. 
- Business Insider US is not, and does not produce the same issue (see: http://www.businessinsider.com/mark-zuckerberg-presidential-trip-every-state-product-focused-ceo-2017-6 ) 

Initial run through and experiment with the requests in-page: 

Google Contributor Script: 
```
https://contributor.google.com/scripts/5b33919a4cdd6ebb/loader.js
```
Attempting to block that request results in additional calls from these two domains: 

```
p.w.em0n.com
```
```
p.w.m80fg.com
```
```
Request URL:https://p.w.m80fg.com/_/scs/mss-static/_/js/k=boq-content-ads-contributor.ContributorAdWallUi.en_US.mLT1UVaf5o8.O/ck=boq-content-ads-contributor.ContributorAdWallUi.7wv7hah7acv5.L.W.O/m=ws9Tlc/rt=j/d=0/excm=bundlefailview,_b,_tp/ed=1/rs=AJlcJMzdrPFliQwfG0fu4isOVUg2blH4xA
```
Blocking all 3 of the domains above resulted in a gray window that had stronger messaging about ad blocking. 

Needs additional investigation and testing.

**Comment by NumDeP** [comment]
+1

**Comment by jonathansampson** [comment]
The following CSS appears to be sufficient to eliminate the modal:

```css
body.tp-modal-open {
    overflow: scroll !important;
}

[data-bi-ad],
div.tp-modal,
div.tp-backdrop.tp-active {
    display: none !important;
}
```
