### ISSUE TITLE
Add an option for tabs on top

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#973]
Some people just like it that way better, it would be nice to have an option to keep everyone happy.

**Comment by kbenzle** [comment]
"Infinite" tab space on top is incredibly useful, it was on Hacker News comment months ago, seems important enough to me.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/tabs-on-top-please/3063?u=eljuno)

**Comment by eljuno** [comment]
+2 from community https://community.brave.com/t/changing-tabs-position-to-what-im-used-to/5438

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/bookmarks-toolbar-placement/5464/3

>Also, I like moving my mouse to the very top of the screen and hitting the top limit, which makes clicking on a tab easier. Both Firefox and Chrome have tabs at the very top, so I don’t think there’s a monopoly on that design.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/move-tabs-to-top-of-browser/5511?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/make-tabs-faster-to-click-by-humans/5857?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/on-tab-design-too-sharp/2678/4?u=eljuno
>Please consider implementing a toggle for the “standard” address bar location (tabs on top)

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/plz-make-tabs-like-chromium-based-browsers-or-make-this-option-so-that-the-tabs-are-at-the-top/7453?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/win64-laptop-v0-19-95-general-feedback-minor-issues/11283?u=eljuno

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/ui-change-desktop/16792?u=eljuno

>tabs appear above the URL bar like in most other Browsers (firefox, opera, chromium, tor, etc) on desktop?

**Comment by baretomas** [comment]
When is this coming? The only thing blocking me from using Brave! Please help me get rid of Opera/chrome!

**Comment by bsclifton** [comment]
@baretomas we are currently working on a replacement for the Muon (electron fork) based Brave which is a direct fork of Chromium. This does feature tabs on top 😄 More info can be found in the blog post we shared late last month:
https://brave.com/development-plans-for-upcoming-release/

**Comment by bsclifton** [comment]
Closing as `wontfix` since this is already fixed (by default) with [Brave Core](https://github.com/brave/brave-browser) (coming soon!)

Since many folks may prefer the tabs UNDER the address bar (ex: the current behavior in the live version of Brave), we have captured https://github.com/brave/brave-browser/issues/181
