### ISSUE TITLE
Cannot download anything from google drive.

### ISSUE THREAD

**Issue by 16kuokhc1** [brave/browser-laptop#9730]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When I try to download something from Google drive, the file is saved as a weird name and takes forever to download.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 8
- Brave Version (revision SHA):
0.16.9
- Steps to reproduce:
    1. Download something from google drive (eg. Rider of the Sky.flac)
    2. Save in desired folder
    
- Actual result:
File is saved as 0B0AG0IEZlUbdUWNsVTE4b0p5SUU and is still not finished downloading after an hour.

- Expected result:
File is saved as "Rider of the Sky.flac" and takes under a minute to download

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by luixxiul** [comment]
Is fingerprinting protection enabled?

**Comment by srirambv** [comment]
Need to enable 3rd party cookie for the download to complete.

**Comment by 16kuokhc1** [comment]
Thanks, problem solved.
