### ISSUE TITLE
tab page only with new tabs cannot be closed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9734]
**Describe the issue you encountered:** tab page only with new tabs cannot be closed.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA):0.17.10

- Steps to reproduce:
    1. Open new tabs until you have the second tab page
    2. Right click the tab page
    3. Select `Close tab page`
    4. Make sure the tab page is not closed
    5. Open twitter.com on the last tab
    6. Make sure it is the only tab on the second tab page
    7. Repeat 2 & 3
    
- Actual result: Tab page is closed finally

- Expected result: tab page only with new tabs should be able to be closed

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by NejcZdovc** [comment]
Dup of #9420
