### ISSUE TITLE
History inside autocomplete suggestions cannot be cleared until the browser is closed

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9736]
**Describe the issue you encountered:** History inside autocomplete suggestions cannot be cleared until the browser is closed.

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.10

- Steps to reproduce:
    1. Clear the browser's profile
    2. Go to `:g brave`
    3. Clear the data via `Clear browsing data` inside `History`
    4. Enter `brave` to the URL bar
    
- Actual result:

  ![clipboard01](https://user-images.githubusercontent.com/3362943/27576912-ac4c5b22-5b59-11e7-9c7e-82a5b52b4044.jpg)

- Expected result: the history should be cleared before you restart the browser

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
cc: @bbondy who was in this code recently (w/ bloodhound improvements)

**Comment by bsclifton** [comment]
Is this a dupe of https://github.com/brave/browser-laptop/issues/9715?

**Comment by luixxiul** [comment]
I don't think so as you get the error without enabling Sync.

**Comment by bsclifton** [comment]
@luixxiul correct- see [@diracdeltas comment](https://github.com/brave/browser-laptop/issues/9715#issuecomment-314608911):
> I see the same bug on a fresh profile without sync enabled. If you click 'delete history entry', the history entry just gets added back at the bottom of the list.

**Comment by srirambv** [comment]
+2 from community https://community.brave.com/t/anyone-have-random-history-entries-that-still-come-up-even-with-all-history-deleted/4594/

**Comment by bsclifton** [comment]
+1 from user @patrick99e99 (reported with https://github.com/brave/browser-laptop/issues/9884)

**Comment by Liunkae** [comment]
This seems separate but related to #8761/#9715.

**Comment by Liunkae** [comment]
+1 from me (#10421)

**Comment by Liunkae** [comment]
Regression of #5147

**Comment by bsclifton** [comment]
@Liunkae I don't think it's a regression- it was never fixed. https://github.com/brave/browser-laptop/issues/5147 was closed as stale

**Comment by hackobi** [comment]
I have the same problem but when I quit and relaunch the URL addresses are still there.
