### ISSUE TITLE
Bookmark submenu shows horizontal scrollbar, empty folder shows single entry with transparent section

### ISSUE THREAD

**Issue by aekeus** [brave/browser-laptop#974]
<img width="314" alt="screen shot 2016-03-02 at 4 14 43 pm" src="https://cloud.githubusercontent.com/assets/210240/13475723/73da5a8e-e092-11e5-954a-3a65c07a94d6.png">
<img width="146" alt="screen shot 2016-03-02 at 4 16 22 pm" src="https://cloud.githubusercontent.com/assets/210240/13475783/a75547de-e092-11e5-9ee2-dcef2edf0522.png">

**Comment by bbondy** [comment]
any easy way to get that artifact? Does ti happen everytime for you or randomly? Maybe just on a specific site in the background?

**Comment by aekeus** [comment]
The empty folder happens each time an empty folder is opened. The horizontal scrollbar show for all opened folders (and sub folders).
<img width="320" alt="screen shot 2016-03-02 at 4 24 01 pm" src="https://cloud.githubusercontent.com/assets/210240/13475915/5e38603a-e093-11e5-8e47-bd6c62d6d39b.png">

**Comment by aekeus** [comment]
Here is another example for empty subfolders
<img width="199" alt="screen shot 2016-03-03 at 9 09 08 am" src="https://cloud.githubusercontent.com/assets/210240/13496701/bd5e879c-e11f-11e5-830c-a3852d987256.png">

**Comment by aekeus** [comment]
Last commit fixed
<img width="424" alt="screen shot 2016-03-03 at 3 29 19 pm" src="https://cloud.githubusercontent.com/assets/210240/13508388/cb83ceb0-e154-11e5-9347-95498bb8f287.png">
