### ISSUE TITLE
Context Menu Not Working After Tear Off Tab

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#9741]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
[From community](https://community.brave.com/t/right-click-problem-when-tab-exported-to-new-window/3674/5?u=eljuno)
> if you export a tab (to have the tab 
to a new window) the right click menu does not work, no more right 
click menu

Context menu not working after tear off tab. And it seem the context menu not working only for that tab. Moving back tab to original windows make context menu work again.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win10, reproduced in Win8.1

- Brave Version (revision SHA):
0.16.9

- Steps to reproduce:
    1. Start Brave, open DDG or Google Search.
    2. Right click any link in search result, it open context menu.
    3. Right click anywhere, in blank space, it also open context menu.
    4. Tear-off tab to create a new window.
    5. Right click no longer work for that tab. Moving back tab to original windows make context menu work again.
    
- Actual result:
Context menu not working/no context menu.

- Expected result:
Context menu appear as usual

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-context-menu-tear-off-tab-bug](https://user-images.githubusercontent.com/25360853/27610371-431e0a7e-5bb8-11e7-95d5-52c4e48f4cb7.gif)

- Any related issues:

**Comment by srirambv** [comment]
If there are pinned tabs, then the context menu works.

**Comment by eljuno** [comment]
Context menu in pinned tab (in new window): Yes, its work.
Context menu in tab that tear off: No. See the previous record.

Here's additional record for _not have pinned tab_:
![brave-context-menu-tear-off-tab-bug-no-pinned-tab](https://user-images.githubusercontent.com/25360853/27707707-7e23bf22-5d40-11e7-9423-1a664c739b11.gif)

**Comment by eljuno** [comment]
Still happen in latest release 0.17.13

Also +1 [from community](https://community.brave.com/t/right-click-problem-when-tab-exported-to-new-window/3674/10?u=eljuno)

> I was able to recreate this in Brave 0.17.13. When right clicking in the torn-off tab, the context menu appears for a split second and then disappears. Well, really only the outline of the menu is visible for that short period of time.

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/right-click-does-not-work/3941/3?u=eljuno)

**Comment by LaurenWags** [comment]
+2 from community https://community.brave.com/t/right-click-on-brave-dosent-work-at-times/6358

**Comment by LaurenWags** [comment]
+1 from community - https://community.brave.com/t/cannot-right-click-with-0-18-23-on-windows/6206

**Comment by LaurenWags** [comment]
Assigning milestone as this continues to come up and is becoming a pain point for users.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/right-click-menu-not-working-on-separated-tabs/8000?u=eljuno

>Every time I separate a tab to a new window the right click menu on that tab does not open. If I open new tabs in the new window the right click menu works but it does not work on the original separated tab that was used to create a new browser window.

Brave 0.18.36

**Comment by DerekL** [comment]
+1 from community. [Me, here, now.](https://github.com/brave/browser-laptop/issues/9741)
