### ISSUE TITLE
Duckduckgo as default search engine (instead of google)

### ISSUE THREAD

**Issue by LoveIsGrief** [brave/browser-laptop#9748]
- Did you search for similar issues before submitting this one?

Found #295, but that's just for giving the possibility to change the default search engine after installation.

- Describe the issue you encountered:

Google is the default search engine

- Platform (Win7, 8, 10? macOS? Linux distro?):

Kubuntu 16.04 

- Brave Version (revision SHA):

fba98fc

- Steps to reproduce:
    1. Download Brave
    2. Open brave
    3. Type search text into URL bar and hit enter
    
- Actual result:

Google search results

- Expected result:

Duckduckgo search results

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

Yes

- Is this an issue in the currently released version?

Yes

- Can this issue be consistently reproduced?

Yes

# Why

Isn't brave about privacy and letting in the right ads ? If not, then this issue can be safely ignored. Otherwise, I'd argue that duckduckgo protects (or at least claims to) our privacy more than google does.

**Comment by crysman** [comment]
I believe this is related to this request:
https://github.com/brave/browser-laptop/issues/3053
which, once implemented, solves this, too

**Comment by luixxiul** [comment]
I agree with @crysman. Still, we could add another section to `about:welcome` (which will be added in the next version) that you could change your default search engine on `about:preferences#search`.

**Comment by Jacalz** [comment]
+1 on creating a search engine selection in the welcome screen and also making DuckDuckGo default 👍 🦁+🦆

**Comment by luixxiul** [comment]
CC @cezaraugusto and @bradleyrichter for thoughts

**Comment by cezaraugusto** [comment]
+1 from me. @bradleyrichter wdyt?

**Comment by Liunkae** [comment]
+1 for search engine selection on welcome screen, with DuckDuckGo selected by default.

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/make-default-search-engine-one-that-respects-your-privacy/5465/

and +1 from me. :smile:

**Comment by doc-E-brown** [comment]
Love for duckduckgo! +1

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/isnt-brave-meant-to-be-more-private-if-so-why-use-google-as-the-default-search-engine/11157?u=eljuno

**Comment by armaccloud** [comment]
Yes, duckduckgo as the default!
+1

**Comment by bradleyrichter** [comment]
DDG is great and we hope to have a tighter integration in the future. 

We will be doing a v2 redesign on the welcome page and will absolutely add a search engine default section. This is a great place to present it to the new user.

**Comment by fermulator** [comment]
Agreed (+1); new user making the switch, first time walking through the configurations/preferences on a Linux system - was jaw-dropping to see Google as the default.

What is the ETA/plan?

@bradleyrichter noted above there is maybe a roadmap to present the user to choose it on welcome screen? - that's great and all ... first time open presenting the user with a choice!

_however_, I still think this request is still applicable in that the _default default_ should be DuckDuckGo.

**Comment by KidPluto** [comment]
> was jaw-dropping to see Google as the default.
Exactly my reaction.

**Comment by arsalankhalid** [comment]
It seems like this issue should be closed since this now a useable feature as seen with:
![settingduckduckgo](https://user-images.githubusercontent.com/5307218/39099194-56431186-4644-11e8-8b80-8647e1c826fe.gif)

Can we close this? @bradleyrichter

**Comment by Liunkae** [comment]
@arsalankhalid No, Google is still the default search engine when Brave is first installed.

**Comment by KidPluto** [comment]
Wow.  Over a year later and Google is still the default browser.  This shows a massive disconnect between the stated goals of this project, and the people working on it.

**Comment by LoveIsGrief** [comment]
@arsalankhalid I disagree. Google is still the default after installing the browser. Sure, changing it is easy, but that's not the target of this issue.

**Comment by LoveIsGrief** [comment]
The relevant line should be https://github.com/brave/browser-laptop/blob/0640d1e879c9848d52f263ba69e46cb0ac653e0b/js/constants/appConfig.js#L153

And the text should be https://github.com/brave/browser-laptop/blob/273749d212f996e400c6b543a46200bd647c854e/js/data/searchProviders.js#L37

Seems easy enough. I'll see if that does it, locally.

**Comment by bsclifton** [comment]
DuckDuckGo is a great search engine (my personal favorite) but at this time we aren't prepared to enable this for all users. Talking with other team members, most users expect Google by default. Changing the preference is easy of course

We may very well address this in the future, but for now (April 2018), I'm going to close as `wontfix`. Apologies for any disappointment

**Comment by Liunkae** [comment]
Just a reminder that #13651 covers the ability to select the default search engine on the welcome screen, which would be an alternative solution to this feature request.

**Comment by LoveIsGrief** [comment]
I'm not sure what to say. The home page has messages like: "Protect your privacy" and "Privacy by default", which seem to convey that this browser is privacy focused. However a concession of this kind is made.

It leads me to wonder what other kind of concessions have been made and why.

Anyway, thanks for the definitive response.
