### ISSUE TITLE
Rename Yes/No buttons to Allow/Deny for easier understanding

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9750]
## Test plan

https://github.com/brave/browser-laptop/pull/10180#issue-246192245

----

- Did you search for similar issues before submitting this one
Yes?

- Describe the issue you encountered:
>making the controls "Deny" and "Allow" (again, as for Flash) instead of "No" and "Yes" would be more clear to me. More than once, I've nearly clicked "Yes" with the feeling that I was confirming the "remember for this site" checkbox.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.16.9

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/requests-re-block-autoplay-controls/4324

**Comment by bsclifton** [comment]
This is a nice polishing step IMO

WDYT, @bradleyrichter @alexwykoff ?

**Comment by bradleyrichter** [comment]
I agree. But I would like to see a table of all alert messages and refine them all in one go if possible.

@cezaraugusto @bsclifton Can we generate this table? Or is it a matter of cherry picking strings?

**Comment by cezaraugusto** [comment]
only way is manually I think, I'll take care of that

**Comment by Liunkae** [comment]
+1 from me.

**Comment by srirambv** [comment]
Reopening issue based on https://github.com/brave/browser-laptop/pull/10180#issuecomment-353425693

**Comment by srirambv** [comment]
@cezaraugusto @bradleyrichter  Should the order be Allow/Deny/Never remember or Deny/Allow/Never Remember to keep consitency 
![image](https://user-images.githubusercontent.com/17010094/34535278-68e0ca30-f0b9-11e7-8cf7-0bce9dc04c61.png)

**Comment by cezaraugusto** [comment]
deferring to @bradleyrichter

**Comment by bradleyrichter** [comment]
"Would you like Brave to save this password"  = No/Yes

"Allow Brave to save this password" = Deny/Allow 

So I think our strings are currently phrased for No/Yes.



Also, we need to follow the style for "Continue-Yes on the Right side". This is the internet standard and only Windows still uses the inverse approach.

Our new approach should follow this mockup:

![image](https://user-images.githubusercontent.com/13509546/34596476-e2131aa8-f194-11e7-9fa5-a38d60992c13.png)
