### ISSUE TITLE
Add 'always block' option to autoplay

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9755]
## Test plan

https://github.com/brave/browser-laptop/pull/12159#issue-278602847

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Users in community are asking for the option to always block autoplay and do not ask/show a notification per each domain.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.18.x

**Comment by alexwykoff** [comment]
![screen shot 2017-09-08 at 12 28 33 pm](https://user-images.githubusercontent.com/1434040/30228146-4fe13e90-9491-11e7-843e-45fe66800ae4.png)

**Comment by srirambv** [comment]
+1 from community https://community.brave.com/t/add-autoplay-request/7663

**Comment by LaurenWags** [comment]
@darkdh on MacOS video plays but is muted with 'Always Deny' as the option:
![9755-019126](https://user-images.githubusercontent.com/28145373/34613797-18da76f4-f1fd-11e7-896b-b790b35ebe6a.gif)

**Comment by darkdh** [comment]
fixed in muon 4.6.7

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0
