### ISSUE TITLE
Only primitives in Frame

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9760]
**Describe the issue you encountered:**
Remove `allSiteSettings` from mergeProps.

**Comment by NejcZdovc** [comment]
Mostly done in #9475, some more work in here #9899

**Comment by luixxiul** [comment]
no-qa-needed?

**Comment by NejcZdovc** [comment]
no QA needed, because this issue was fixed with other PR's that has their own tests
