### ISSUE TITLE
profile folder should be locked as long as the browser process runs

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9761]
**Describe the issue you encountered:** profile folder should be locked as long as the browser process runs, if possible.

The folder is locked on Windows, while it is not on macOS. I lost my main session file because of that.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Steps to reproduce:
    1. Close the browser window, leaving the browser processes
    2. Try to rename the browser's profile folder
    
- Actual result: the folder is renamed

- Expected result: the folder should not be renamed

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by bsclifton** [comment]
This is going to need to be a Muon specific change IMO and we may even have to patch Chromium in order to achieve it

Basically, we'd have to put a process lock on the folder (using `fcntl()` or `flock()`) on the profile directory

cc: @bridiver @darkdh

**Comment by bridiver** [comment]
I don't think this is the right thing nor do I think it's even possible on mac or linux. Windows is the only OS that I am aware of that locks files for reading. This is not something a normal user would do and if you are renaming your profile directory you had better know what you are doing.

**Comment by luixxiul** [comment]
I see, I'd create backup folders to avoid that accident

**Comment by bridiver** [comment]
why are you renaming while it is running anyway?

**Comment by luixxiul** [comment]
I thought the browser process has been killed, yet it was the only browser windows that have been closed.
