### ISSUE TITLE
MacOS Specific - Pinning a normal tab causes browser crash but retains the pinned tabs upon restart

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9763]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pinning a tab causes browser crash but retains the pinned tabs upon restart.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave	0.17.12
rev	0095c35
Muon	4.1.6

Also 0.18.22 packaged build.

- Steps to reproduce:
	i.	Clean install launches with a new tab and welcome tab. Close the about:welcome tab but leave the new tab alone for now, you will use it in step 4.
	ii.	Open a new tab and visit a site and pin it
	iii.	Open second tab and visit a site and pin it, move the second pinned tab to first position
	iv.	Visit a different site on the tab the browser opened with and pin it, browser crashes
	v.	Relaunch the browser all pinned tabs are retained
    
- Actual result:
Pinning a tab after moving a pinned tab causes browser crash but retains the pinned tabs upon restart

- Expected result:
Position of the pinned tabs and pinning normal tabs should not cause any crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:

- Screenshot if needed:
![9673](https://user-images.githubusercontent.com/28145373/29330274-b8323c02-81c6-11e7-9872-3af9d499db58.gif)

- Any related issues:
https://github.com/brave/browser-laptop/issues/9333 - see commentary on this issue

**Comment by bbondy** [comment]
Is this only related to session tabs?

**Comment by LaurenWags** [comment]
@bbondy updated and simplified steps. Not specific to session tabs. Still occurs in 0.17.15 with clean profile.

**Comment by bbondy** [comment]
@LaurenWags could you retest this?

**Comment by LaurenWags** [comment]
Using 0.18.22 packaged build, I can repro. (note, since 0.18.14 introduced displaying the about:welcome page on clean profiles, I tweaked the steps to account for this). added gif too.

**Comment by NejcZdovc** [comment]
@petemill will this issue be solved by your PR #10531?

**Comment by bsclifton** [comment]
This should be solved with https://github.com/brave/browser-laptop/pull/10531; moving to 0.21.x

**Comment by luixxiul** [comment]
add the duplicate label according to https://github.com/brave/browser-laptop/pull/10531#issuecomment-324490141
