### ISSUE TITLE
URL bar text not selected when in titlemode + F6 keyboard shortcut used

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9764]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
While testing https://github.com/brave/browser-laptop/pull/9411, I noticed that when the magic titlebar is enabled (ex: always show URL bar is disabled), the text in the URL bar is not selected when bar is focused via keyboard.  If the mouse is in the top area (and URL bar is shown), the keyboard shortcuts work as expected

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
HEAD on master

- Steps to reproduce:
    1. In `Preferences` > `Advanced`, make sure `Always show the URL bar` is disabled
    2. Load https://brave.com
    3. Move your mouse to the content area of the screen (ex: not the URL bar or titlebar area) and confirm title mode is shown
    4. Press F6 (cmd+L / ctrl+L do work, this issue is only present when using the F6 keyboard shortcut) which should show and focus the URL bar
    (new notes - as of 0.18.x releases)
    5. The URL bar may focus correctly. If so, click back onto the webpage (brave.com) and select some text
    6. Press F6 again which should show and focus the URL bar
    
- Actual result:
The text is not highlighted (ex: you can't type to replace it)

- Expected result:
The text should be highlighted.  You can get a feel for this by pushing F6 twice

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Possibly related (ex: may possibly fix):
https://github.com/brave/browser-laptop/issues/7358

cc: @cezaraugusto

**Comment by cezaraugusto** [comment]
@bsclifton can you confirm if still an issue? can't repro in 0.18.19

**Comment by bsclifton** [comment]
@cezaraugusto yes- I can still repro ☹️  I updated the steps.  Can you confirm you get the same behavior?

**Comment by zentagonist** [comment]
I'm not able to reproduce this or #7358. @bsclifton can you please confirm this is still an issue. (again, sorry)

**Comment by bsclifton** [comment]
works every time for me with Cmd + L- however, F6 does not seem to work as expected

**Comment by zentagonist** [comment]
Updated description after honing in on this being reproducible only with F6 shortcut and not cmd+L.

**Comment by cezaraugusto** [comment]
self notes: typing `document.activeElement.nodeName` to check who's in focus shows that once you select the text and hit F6 focus is persisted in `'WEBVIEW'`.
