### ISSUE TITLE
Open and Fill from 1Password opens site in Chrome

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9765]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
While in Brave, if I select the 1Password extension and navigate to a saved site/search for a site, when selecting the 'Open and Fill' option, the site is being opened in Chrome.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave	0.17.12
rev	0095c35
Muon	4.1.6

- Steps to reproduce:
    1. Enable 1Password in Extensions.
    2. Connect to 1Password.
    3. Select the 1Password extension icon.
    4. Search for a site or navigate to one (i.e. hover over Passwords > site > look at the 'website' area)
    5. In the 'website' area, select Open and Fill.
    
    
- Actual result:
Site is opened in Chrome.

- Expected result:
Site should be opened in Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes (0.16.9)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
<img width="343" alt="screen shot 2017-06-28 at 3 42 07 pm" src="https://user-images.githubusercontent.com/28145373/27657061-5c6472d2-5c19-11e7-9538-103c244b10c4.png">

- Any related issues:

**Comment by srirambv** [comment]
Click on widget-> Search for the login -> Click on login entry opens the site in the current active tab and auto logins on Windows

**Comment by jxpx777** [comment]
Is Chrome your default browser? The open and fill button next to the website listings in items' details will always use your default browser right now. Try this:

1. In Brave, click the 1Password toolbar button
2. Search for the Login you want to open and fill
3. Highlight it and press return

This uses a slightly different code path than the button next to the website address and takes into account the browser that is active.

We have internal issues open to streamline these code paths to make this less confusing.

--
Jamie Phelps  
Code Wrangler @ AgileBits  
Fort Worth, Texas

**Comment by alexwykoff** [comment]
@LaurenWags please investigate and re-add to .20 if Chrome isn't your default browser.

**Comment by LaurenWags** [comment]
When Brave is default browser this is not an issue, closing this item.
