### ISSUE TITLE
Box.com legitimate content blocked with adblock enabled

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#9766]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
With adblock enabled, the box.com main page does not appear correctly. Turning off adblock fixes the problem.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.17.12 (0095c35)

- Steps to reproduce:
    1. Make sure you have adblock on by default.
    2. Visit https://www.box.com
    
- Actual result:
Many legitimate page elements are blocked.

- Expected result:
All legitimate page elements should be visible.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Probably.

- Is this an issue in the currently released version?
Probably with 0.16.9 also.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Make sure you have adblock on by default.
    2. Visit https://www.box.com
    3. All legitimate page elements should be visible.

- Screenshot if needed:

With adblock **disabled**:
![image](https://user-images.githubusercontent.com/19424103/27659212-42dbc7d0-5c18-11e7-803e-50f625ee5077.png)

With adblock **enabled**:
![image](https://user-images.githubusercontent.com/19424103/27659178-2ca35186-5c18-11e7-8cdc-9ba4e48d6617.png)

- Any related issues:
None.

**Comment by Liunkae** [comment]
Seems OK in 0.18.22. Probably fixed sometime in 0.18.x.

**Comment by luixxiul** [comment]
it might be thanks to a change on their side. Adding the milestone for QA tests.
