### ISSUE TITLE
Give credit to original projects

### ISSUE THREAD

**Issue by ghostwords** [brave/browser-laptop#9767]
Hi, I noticed some of the code in [blockCanvasFingerprinting.js](https://github.com/brave/browser-laptop/blob/c575303be1495d85367873b92aedc58f9d94618c/app/extensions/brave/content/scripts/blockCanvasFingerprinting.js) is based on [code in Privacy Badger](https://github.com/EFForg/privacybadger/blob/7d13b5dd8892d30e65485f9c9cac7ca79149932f/src/js/contentscripts/fingerprinting.js), which in turn is based on [code from my Chameleon project](https://github.com/ghostwords/chameleon/blob/a1a6c20616a56b4896240536aafef76cd6cde0ca/src/js/injected.js). Could you please give credit to the original projects your work is built on top of? This wouldn't be exclusive to my work, of course, just bringing up what I am familiar with.

**Comment by luixxiul** [comment]
If MPL requires doing so, why don't we?

I'm not familiar with license attribution, so CC @diracdeltas for comments who also contributes to Privacy Badger.

**Comment by Jacalz** [comment]
Maby having a link in the bottom of about:Brave that takes you to a site which has all open source projects that Brave uses?

**Comment by diracdeltas** [comment]
@ghostwords hi! thanks for pointing this out - seems to have been an oversight on my part.

What form do you prefer attribution? I noticed Privacy Badger credits you in the comments of relevant files and also in https://github.com/EFForg/privacybadger/blob/38489d9c178a7437aa03ca79fd60c37cabe775fe/LICENSE. I could do either/both.

**Comment by ghostwords** [comment]
Hello! File headers and LICENSE file sound good to me.

**Comment by ghostwords** [comment]
Thank you!
