### ISSUE TITLE
syncing test failures on master

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9768]
https://travis-ci.org/brave/browser-laptop/jobs/248122627#L3451 < may be intermittent, but does not happen on 0.17.x or 0.18.x

(EDIT) i found STR for one of the test failure cases:
1. in pyramid 0, bookmark example.com. notice the bookmark title appears as 'Example Domain'.
2. enable sync in pyramid 0
3. sync pyramid 1 to pyramid 0
4. notice the bookmark title appears as 'http://...'

**Comment by bsclifton** [comment]
pulling back to 0.18.x because it's needed by https://github.com/brave/browser-laptop/pull/9968
