### ISSUE TITLE
Brave for Mac crashes on opening spotal.bg

### ISSUE THREAD

**Issue by ipeychev** [brave/browser-laptop#9775]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Brave for Mac crashes on opening spotal.bg
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
Brave	0.16.9
rev	fba98fc
- Steps to reproduce:
    1. Open Brave
    2. Visit sportal.bg
    
- Actual result:
Brave crashes
- Expected result:
Brave doesn't crash
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
No idea
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

**Comment by alexwykoff** [comment]
It appears to be working for 0.17.x 

<img width="1677" alt="screen shot 2017-06-30 at 9 33 19 am" src="https://user-images.githubusercontent.com/1434040/27737765-5f7a6634-5d77-11e7-9c7b-1813ef4116ef.png">

**Comment by ipeychev** [comment]
Okay then, will wait for the update.

**Comment by Jacalz** [comment]
Can´t reproduce on 0.16.9
![sportal bg](https://user-images.githubusercontent.com/25466657/27740248-a3ea32e2-5db1-11e7-8b39-40f4bb9e550f.jpeg)

**Comment by ipeychev** [comment]
Hey, Brave updated yesterday, but this still happens, please check the following screencast:

![bug](https://user-images.githubusercontent.com/78014/27761974-2e851a50-5e68-11e7-8927-66cd9b2e3afd.gif)

**Comment by luixxiul** [comment]
please post the crash log for investigation, thanks!

**Comment by ipeychev** [comment]
Here it is:

[brave.txt](https://github.com/brave/browser-laptop/files/1117111/brave.txt)
