### ISSUE TITLE
Can't open video

### ISSUE THREAD

**Issue by Kzeir** [brave/browser-laptop#978]
I can't open this video, I don't know why... 
I click and doesn't  start.

http://www.adorocinema.com/noticias/series/noticia-119775/

**Comment by luixxiul** [comment]
> Refused to load the script 'http://www.adorocinema.com/js635978562239089833/aspx/js_v7/src/assets/resources.js' because it violates the following Content Security Policy directive: "script-src 'none'".

CC: @diracdeltas

**Comment by diracdeltas** [comment]
video works on http://www.adorocinema.com/noticias/series/noticia-119775/ once i allow scripts, maybe fixed now? @luixxiul try it with a noscript exception for the site.

**Comment by luixxiul** [comment]
Yes, I confirmed
