### ISSUE TITLE
Autoplay notification doesn't close on the first attempt

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9780]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Autoplay notification doesn't close

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.12
rev	0095c35
Muon	4.1.6

- Steps to reproduce:
    1. Disable autoplay media under security 
    2. Login to slack, wait for notification to show up for autoplay media 
    3. Click on Yes/No, nothing happens
    4. Wait for a while and then click on Yes/No, option get set
    
- Actual result:
Autoplay notification doesn't close on the first attempt

- Expected result:
Should select the user option to allow/disallow

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
No, intermittent

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![slack_notification](https://user-images.githubusercontent.com/17010094/27698666-ad5386ac-5cef-11e7-8b80-7d5947dbeeec.gif)
![image](https://user-images.githubusercontent.com/17010094/27698675-b50c6b5c-5cef-11e7-9219-28c8490417a1.png)

- Any related issues:

**Comment by cezaraugusto** [comment]
deferring to @darkdh I think he has a plan for that, lmk if there's anything I can do to help :)

**Comment by darkdh** [comment]
dup #9171
