### ISSUE TITLE
tab icons doesn't properly update after max tabs per page config is changed

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9781]
STR in: https://github.com/brave/browser-laptop/issues/9735#issuecomment-311998316

cc @srirambv I don't know if we have an issue for that already if so please close this one and assign me to that. thanks!

release team: moving this to 0.18.x please change if needed.

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/browser-laptop/issues/9779
