### ISSUE TITLE
Feature request : create a zk-proof system that a human is using the browser so we can get rid of captchas

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9782]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A user from community has requested that we try to get rid of captchas. https://community.brave.com/t/captcha-requests/4200/3

- Platform (Win7, 8, 10? macOS? Linux distro?):
all

- Brave Version (revision SHA):
> 1.0

**Comment by bsclifton** [comment]
Closing as the execution of this could be a project/repo of it's own (one does not simply grab and execute this issue 😛 )
