### ISSUE TITLE
Update Payments UI to show different text if ADDFUNDS_URL is set

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9786]
If `ADDFUNDS_URL` is set, you currently still see the "Card funding is temporarily unavailable." on the "Add Funds..." popup; however, the button still works. 

It would be nice if we modify the code so that if the `ADDFUNDS_URL` code is going, we have the new text and a button that isn't greyed out.

cc: @bradleyrichter @mrose17 for text to display

**Comment by mrose17** [comment]
![0](https://user-images.githubusercontent.com/400552/27718575-9a0c0580-5d01-11e7-8b83-e5470531248e.png)

i think there are three changes:

1. remove the grayed-out effect on the button

2. restore the text under the button that was there before

3. replace the coinbase logo and text with the stripe logo and "debit/credit funding provided by Stripe"
