### ISSUE TITLE
Close tabs to the left/right (tab page)

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9789]
## Test plan

https://github.com/brave/browser-laptop/pull/9790#issue-239711691

----

- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you try to close all tabs except selected one and you have open tab pages, tabPage index is not updated. Found this bug when working on #7806
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
4cc1273
- Steps to reproduce:
    1. open so many tabs that you have at least two tab pages
    2. right click on the last tab
    3. select "Close tabs to the left"
    
- Actual result:
![image](https://user-images.githubusercontent.com/9574457/27727311-4754e370-5d7e-11e7-8200-2b3265dd9e15.png)

- Expected result:
We should see our last tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by NejcZdovc** [comment]
@bsclifton same as for #7806, if you want to pull this one into 0.18

**Comment by NejcZdovc** [comment]
This PR is blocked on #9678

**Comment by bbondy** [comment]
Doesn't apply without redux to 0.18.x so we're moving this to 0.19.x
