### ISSUE TITLE
Update minimum Node version on README.md

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9797]
**Describe the issue you encountered:** Update minimum Node version on README.md.

With `v7.3.0` I got an unit test error, which is:

````
  1444 passing (17s)
  47 pending
  1 failing

  1) downloadsBar component very narrow downloads bar with items renders no downloads:

      AssertionError: 3 == 0
      + expected - actual

      -3
      +0
      
      at Context.<anonymous> (test/unit/app/renderer/components/download/downloadBarTest.js:118:14)
````

The error was fixed by updating Node to `v7.9.0`.

We could update it to 8 instead of it, though I am not sure if the browser is fully compatible with that newer version.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master

- Steps to reproduce:
    1. git push

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
Let's decide the version number soon, since there might be a chance where other contributors also experience the bug.

**Comment by bsclifton** [comment]
I think it's safe to recommend 7.9.0 👍 

We can now also remove this part:
```
node-gyp 3.3.1

 sudo npm install -g node-gyp@3.3.1
```

and update
`Install the Node (v5+) dependencies:`
to
`Install the Node dependencies:`

**Comment by luixxiul** [comment]
It is ok to remove node-gyp though there are several files where `node-gyp` seems to be called?

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/search?utf8=%E2%9C%93&q=node-gyp&type=

**Comment by bsclifton** [comment]
@luixxiul correct, you can remove the global instance... because we already include it as a module in our package.json:
https://github.com/brave/browser-laptop/blob/ed199519045fb1e233b6549416cc3ca0084439e9/package.json#L176

I don't think it was ever needed to be installed globally. I haven't had it installed in over a year

**Comment by luixxiul** [comment]
I see. I'm going to create a PR.
