### ISSUE TITLE
Brave doesn't auto-relaunch after updating correctly

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#9804]
similar and possibly related to #2184 but the update happens, just fails to relaunch.

**Comment by Jacalz** [comment]
Happened for me once on 0.13.x on mac but have not seen it since 🙂

**Comment by LaurenWags** [comment]
I didn't experience this with the update to 0.17.13, but there is a +1 from community

**Comment by kevinlawler** [comment]
Happened to me on macOS on the latest update

**Comment by jonathansampson** [comment]
I believe I ran into this with the most recent update on Windows 10. Had to manually start the browser after applying the update.

**Comment by Liunkae** [comment]
I think this happened to me when updating to 0.17.13 on macOS.

**Comment by Jacalz** [comment]
Did not happen to me when updating to 0.17.13 on macOS

**Comment by Jacalz** [comment]
It happened on MacOS Sierra for me when updating to 0.18.14 :sweat_smile:

**Comment by Jacalz** [comment]
This just happened to me when I updated my MacBook Pro from 0.18.36 to 0.19.53
