### ISSUE TITLE
Losing tabs when updating

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9805]
We have several reports about losing tabs when updating.

**Comment by bsclifton** [comment]
This may be a hung window not being saved during exit

**Comment by bbondy** [comment]
I think there's a good chance this is fixed by:
https://github.com/brave/browser-laptop/commit/9296f7fc3754f9394b3f3080623fb3ff42edc8fa

If users put the setting to have a clear session on each startup though it'll still happen. I'm going to close this since it's for the former problem though. We can re-open if we still get reports of the bug.
