### ISSUE TITLE
Downloading from Google Drive appears to become stuck

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9810]
## Test Plan:
1. Go to google drive
2. Make sure block 3rd party cookies
3. You should be able to download file

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
From a user in support : 
"Some feedback om Google Drive/Doc file downloads: When downloading content from the Drive,  (e.g. MacOS native file types incl. .numbers .keynote) download gets stuck. 

Process  
1. Google Drive Virus Scanning 
2. Mac OS Native Select Folder window where you choose the down location 
3. Bottom Download bar in Brave pops-up with the downloadable file notification in it saying "Downloading..." and it's stuck there. 

On the other hand I have not issues with Safari here. Not sure if it's a write permission thing or something else. "

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Attempt to download a file from Google Drive
    
- Actual result:
The download becomes frozen.

- Expected result:
The download should complete.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Need to set **_`Allow all cookies`_** for Google Drive to download any file. Blocking it causes the file name to show junk characters and doesn't complete download.

**Comment by darkdh** [comment]
Test plan:

1. Clear your session data
2. Open Brave
3. Go to Google drive
4. The shield should show allow all cookies
5. You should be able to download file

Respect users setting:
1. Make 3rd party cookie block on facebook/google drive
2. Upgrade Brave
3. Go to facebook/google drive
4. The shield should show block 3rd party cookies
