### ISSUE TITLE
Brave — Totally Broken?

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#9815]
- Did you search for similar issues before submitting this one?
No.

- Describe the issue you encountered:
Can't interact wit hthe document at all. Clicking does nothing. Sometimes when this happesn I get "pointer" cursor (the hand) over window. 

- Apple Macbook Pro

- Brave Version (revision SHA):
f7242c7

- Steps to reproduce:
    1. Use Brave.
    2. 
    3.
    
- Actual result:
Unresponsive browser

- Expected result:
Works like normal browsers

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Probably

- Is this an issue in the currently released version?
I again updated today.

- Can this issdue be consistently reproduced?
No

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/56098/27758272-1a563832-5dc5-11e7-876e-3355c9672c21.png)

- Any related issues:
Brave doesn't work on iOS either. Crashes all the time (20 x per day)

**Comment by rudynunez** [comment]
I have the same problem. Reinstalling has no effect. Haven't been able to use Brave for 3 weeks.

**Comment by luixxiul** [comment]
it might be that the profile is corrupted, unfortunately. It would help quite well to fix the issue if you would share the profile file. (If the profile contains credentials, of course you would not need to do so 😉)

**Comment by GarrettS** [comment]
![image](https://user-images.githubusercontent.com/56098/27996979-e1aed5ea-64a2-11e7-8c24-c2629edc8cf7.png)

How to check my profile?

Brave on iOS also crashes often. It's neat that there's no ads, but it is very unstable and crashes often. If it is not a profile issue, maybe the browser chrome has issues.

**Comment by bsclifton** [comment]
We'll need more information before we can look into this (and prioritize this by assigning a milestone)

@GarrettS you can backup your session / profile by copying your `~/Library/Application Support/brave` folder.  I'd recommend moving this out of the way and see if the browser works.  If it does, the `session-store-1` file may be corrupt as @luixxiul mentioned

@GarrettS do you have any steps which you would recommend us to try if we'd like to reproduce? If so, please include and reopen 😄
