### ISSUE TITLE
"sqlite error 2067" on Linux

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9820]
**Describe the issue you encountered:** https://community.brave.com/t/sqlite-error-2067-linux-0-16-9/4387?u=suguru
> I was running 0.15.something on Linux Mint 17.3, today manually downloaded 0.16.9 deb package and installed overtop. I cannot open Brave, receiving the below error, so completely removed brave using "sudo apt-get remove brave", reinstalled, same problem.
>
> Error reads:
> 
> [4379:4398:0630/131820.034438:ERROR:connection.cc(1954)] Passwords sqlite error 2067, errno 0: UNIQUE constraint failed: logins.origin_url, logins.username_element, logins.username_value, logins.password_element, logins.signon_realm, sql: INSERT INTO logins (origin_url, action_url, username_element, username_value, password_element, password_value, submit_element, signon_realm, preferred, date_created, blacklisted_by_user, scheme, password_type, times_used, form_data, date_synced, display_name, icon_url, federation_url, skip_zero_click, generation_upload_status, possible_username_pairs) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
Failed to get crash dump id.
Report Id: OK
Segmentation fault
Note that the first line is repeated many times with slightly different numbers at the start, I have copied only one instance of it to make this easier to read as I suspect all repetitions will add little value.
>
> I have been unable to get the apt repository to work (that's another story), hence my use of manually downloaded .deb files.

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux Mint

- Brave Version (revision SHA): 0.16.9

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by cvanderlinden** [comment]
I have the exact same problem (including not being able to get the apt repo to work)

**Comment by bsclifton** [comment]
cc: @darkdh 

I know we have recently fixed passwords (so that they should no longer be stored in sqlite).  This hasn't been released yet though

**Comment by darkdh** [comment]
@bsclifton yes, they will be stored in libsecret or kwallet
