### ISSUE TITLE
Ecosia icon not shown in 0.17.x

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-laptop#9823]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
The Ecosia icon is not shown
- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12.5 and Windows 10
- Brave Version (revision SHA):
0.17.13
- Steps to reproduce:
    1. Open about:preferences#search
    2. Look at Ecosia
 
    
- Actual result:
Icon not shown
- Expected result:
Icon should show
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/25466657/27761936-7b4313ac-5e67-11e7-94ff-61a1aabc4d26.png)
![image](https://user-images.githubusercontent.com/25466657/27761942-8e3df7b0-5e67-11e7-8f6d-e3609256794f.png)
- Any related issues:

**Comment by luixxiul** [comment]
the favicon address has been moved to `https://cdn.ecosia.org/assets/images/ico/favicon.ico`

**Comment by Jacalz** [comment]
The thing is that it is only a problem in 0.17.x because that branch was created before https://github.com/brave/browser-laptop/pull/9291 was merged to master 😉 This only needs to be merged into 0.17.x 🤗

**Comment by Jacalz** [comment]
Closed by https://github.com/brave/browser-laptop/pull/9825/commits/4944c2c6c1843f73e009d7ce960502d3fd9e64dc
