### ISSUE TITLE
When Browser level console is open, window can't be dragged (OS X only)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#983]

**Comment by luixxiul** [comment]
I can drag the window. Was this fixed maybe?

**Comment by bbondy** [comment]
this is still a problem, you have to have the dev tools open which are attached to the window.

**Comment by luixxiul** [comment]
Selecting ``View`` and ``Toggle Browser Console``, devtools opened right side of the browser, attached to the window, I can drag the window without a problem. Might be specific to OS X, or am I doing something wrong?

**Comment by bbondy** [comment]
Yes this is only with OS X.

**Comment by bsclifton** [comment]
This was fixed a while back
