### ISSUE TITLE
Block ad, popup manually

### ISSUE THREAD

**Issue by cataza** [brave/browser-laptop#984]
Brave adblock/popup is good but not enough. But there are some popup/ads it cant block automatically.
I use firefox with ABP and Element helper. Select elements with W and N is op. I always block manually because uBlock or other adblock always leave some ads or popup open.

**Comment by cataza** [comment]
There is some bugs with image too. http://www.webtoons.com/en/ It blocks all image.

**Comment by cataza** [comment]
It does not block ads which have close X button. When i click close button, its popup new tab. 
http://blogtruyen.com/truyen/ballroom-e-youkoso/chap-041

**Comment by cataza** [comment]
It not block banners at all

**Comment by luixxiul** [comment]
It seems to be fixed, closing
