### ISSUE TITLE
Cannot logout of twitter

### ISSUE THREAD

**Issue by Michaelocalypse** [brave/browser-laptop#9844]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
When I try to logout of twitter, the page reloads to me feed.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Lunux Ubuntu 16.04 LTS
- Brave Version (revision SHA):
0.12.4
- Steps to reproduce:
    1. Login to twitter
    2. click upper right avatar
    3. click log out
    
- Actual result:
twitter feed page reloads
- Expected result:
twitter login page loads
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Is this issue still reproducible?

**Comment by nufrifin** [comment]
Not sure how useful it would be to say this here, but I'm on 0.18.14 and I can log out of twitter.

**Comment by luixxiul** [comment]
thanks, so closing for now. let's reopen if the issue can be reproduced yet.

**Comment by Michaelocalypse** [comment]
Brave said it had no updates to run. I had some troubles but finally got it to update to 0.18.14 and now I can log out.
