### ISSUE TITLE
Macbook trackpad gestures not working. 

### ISSUE THREAD

**Issue by MoMannn** [brave/browser-laptop#9845]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Macbook pro trackpad gestures not working. Especially swipe with three fingers to go to the previous/next page.  

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
Brave	0.17.13
rev	f7242c7
Muon	4.1.7
libchromiumcontent	59.0.3071.109
V8	5.9.211.38
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.5.0
os.arch	x64

**Comment by Liunkae** [comment]
Swipe with three fingers is working correctly for me with Brave 0.17.13 on macOS 10.12.x.

Just to confirm, is this what your trackpad setting looks like?

![image](https://user-images.githubusercontent.com/19424103/27874717-2083f1ae-6176-11e7-859f-4fbd16352270.png)
![image](https://user-images.githubusercontent.com/19424103/27874782-59c3ca34-6176-11e7-8cc0-7fa49581e935.png)

Either of these settings work for me. However, I agree that it's hard to activate the three finger gesture. There are some improvements coming in 0.20.x (#9615).

**Comment by MoMannn** [comment]
I have mac version 10.12.4, brave version 0.17.13
this are my settings: 
<img width="668" alt="screen shot 2017-07-05 at 20 14 36" src="https://user-images.githubusercontent.com/8865298/27878498-b26fbb5a-61be-11e7-940b-5a4bf80fbf3b.png">

and swipe is not working at all.. it works normally on google chrome.

**Comment by MoMannn** [comment]
Ok, i changed swipe to two fingers and then back to three and now it works :/

**Comment by arpe** [comment]
Same issue here; initially, 'back' did not work, but after changing the settings (and back), it works.

**Comment by MoMannn** [comment]
And now after a few days (8 days judging from my previous comment) the 3 finger swipe gesture stopped working again and I had to go to system settings and disable and enable again for it to start working.

**Comment by arpe** [comment]
Reset through system settings must be repeated after every restart of Brave.

**Comment by Liunkae** [comment]
@MoMannn @arpe Thanks for the info! Now that I think about it, I remember seeing similar behavior a few months ago.

**Comment by bsclifton** [comment]
This behavior should be fixed in our [developer channel release](https://brave.com/download-dev) (brave-core). I'd encourage folks experiencing this to give that a shot and let us know if it's still an issue 😄 Issues for the new version of the product can be reported here:
https://github.com/brave/brave-browser/issues
