### ISSUE TITLE
[features] [suggestion] Language Translation option

### ISSUE THREAD

**Issue by varadgunjal** [brave/browser-laptop#9847]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I've been using Brave as my primary browser for over 2 months now and the only thing I miss from Chrome is the page translate option. As an expat in Japan, I almost always need to use this for local business websites. Are there any plans of adding a page translation mechanism? If yes, can someone please direct me to the same so I can contribute?

**Comment by srirambv** [comment]
In page translation(https://github.com/brave/browser-laptop/issues/858) is on the roadmap.  You can have look at the contributing guidelines [here](https://github.com/brave/browser-laptop/blob/master/.github/CONTRIBUTING.md)

**Comment by srirambv** [comment]
Closing #9847 in favour or #858
