### ISSUE TITLE
Report: minimized tabs reload when reactivated

### ISSUE THREAD

**Issue by lukemulks** [brave/browser-laptop#9855]
- Did you search for similar issues before submitting this one?
Yes, could potentially be included in the issue for this work: 
https://github.com/brave/browser-laptop/issues/9080

If so, we can close. 

Issue reported from Twitter: 
https://twitter.com/Music_Journeys/status/882115365815422976

> *Tabs reload when the browser window has been minimized for a while*

**Browser profile:**

```
Brave0.17.13
revf7242c7
Muon4.1.7
libchromiumcontent59.0.3071.109
V85.9.211.38
Node.js7.9.0
```

- Steps to reproduce:
    1. Load sites in several tabs in a new window. 
    2. Minimize window. Leave minimized for 30-60min 
    3. Open new windows and browse normally. 
4. Once the timer has completed, restore the minimized window with the tabs, and watch for a reload once they become active. 
    
- Actual result:
Tabs reload after being minimized for a while. 

- Expected result:
Smooth transition from minimized session to restored active session after a long duration. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
TBD, should. 
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
TBD
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
Potentially. 

Needs investigation (issues and in practice). 

Cc: @cezaraugusto - if this is included in the polish work referenced at the top of the issue, LMK or feel free to close this issue as a dupe. Thanks!

**Comment by eljuno** [comment]
Similar to #8749?
