### ISSUE TITLE
Multiple tabs freeze brave

### ISSUE THREAD

**Issue by Miyurz** [brave/browser-laptop#9863]
- Did you search for similar issues before submitting this one?
Not really

- Describe the issue you encountered:
I opened almost 25 tabs and then as I was closing some of them, the browser froze and won't let me do anything. It was a complete halt and I had to quit the browser for it to work again.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
f7242c7

- Steps to reproduce:
    1. Open around 25 tabs and then try closing them
   
- Actual result:
tabs were not getting closed.

- Expected result:
It should close the opened tabs smoothly.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes, I tried this umpteenth times.

**Comment by Miyurz** [comment]
cc @srirambv

**Comment by srirambv** [comment]
Thanks for reporting @Miyurz . This is similar to #9385. Will close this thread as the discussion is already there on #9385.

**Comment by srirambv** [comment]
Closing #9863
