### ISSUE TITLE
Fingerprinting - panopticlick

### ISSUE THREAD

**Issue by paranoicogm** [brave/browser-laptop#9869]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Brave with "Fingerprinting Protection" enabled and "Block Scripts" disabled fails panopticlick.eff.org test

- Platform:
KDE Neon 5.10.3 (Ubuntu 16.04)
LineageOS 14.1

- Brave Version (revision SHA):
Brave	0.17.13 - rev	f7242c7
Brave (Android)      1.0.23

- Steps to reproduce:
    1. Open "Brave" set all the shields except for "Block Scripts"
    2. Go to https://panopticlick.eff.org/
    3. Click "Test"
    
- Actual result:
Does your browser protect from fingerprinting?	✗ your browser has a unique fingerprint

- Expected result:
Does your browser protect from fingerprinting? 	✓ yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1. Is it normal?

**Comment by Jacalz** [comment]
https://github.com/brave/browser-laptop/issues/5975#issuecomment-264524964
> panopticlick is based on the number of users who visit EFF's site, so it's definitely skewed. if you visit the site over and over again in new incognito tabs, it no longer says you're fingerprintable.
