### ISSUE TITLE
Brave version - Ubuntu Snap

### ISSUE THREAD

**Issue by ghost** [brave/browser-laptop#9870]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Old Brave version on snap system

- Platform (Win7, 8, 10? macOS? Linux distro?):
KDE Neon 5.10.3 (Ubuntu 16.04)

- Brave Version (revision SHA):
latest/beta: 0.15.1 (2) 149MB -
latest/edge: 0.15.1 (2) 149MB -

- Steps to reproduce:
    1. Open Terminal
    2. Send "Sudo snap install Brave"
    3. Check the version (Help - About Brave)
    
- Actual result:
0.15.1

- Expected result:
>= 0.17.13

**Comment by Liunkae** [comment]
@bsclifton Is there some kind of script that needs to be run to fix this?

**Comment by bsclifton** [comment]
@Liunkae good question, I'm not sure... cc: @flexiondotorg

**Comment by posix4e** [comment]
I have uploaded a snap preview package to my personal bucket (it will be done in 5 minutes or so)
http://storage.googleapis.com/posis-brave-mirror/

**Comment by posix4e** [comment]
On my preview i am getting
```
[29613:29613:0823/112423.250494:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```
Might be a snap dealbreaker

**Comment by posix4e** [comment]
I was able to install in devmode and it worked though

**Comment by retrocausal** [comment]
@posix4e  Hey! the snap for ubuntu like systems, needs a version bump.
current dev release is `0.18.x` and the release on the snap is pointing to `0.17.x`
I see that you are just using `dump` plugin on `snpcraft`. may be it is just the `source` you need to change and point it to `0.18.x` `tar.gz` on this repo?

**Comment by Ads20000** [comment]
@posix4e Us folks over on the [snapcraft forum](https://forum.snapcraft.io/t/brave-version-update-required/1976/) may be able to help out a little? But I can't see the `snapcraft.yaml` in the repo...how are you building this or can you somehow make that `snapcraft.yaml` available? :)

**Comment by posix4e** [comment]
@retrocausal  you talking about the preview?

**Comment by retrocausal** [comment]
Nah. I meant, when we currently install brave as a snap, it installs v0.17.x
And if you have access to the snapcrafters file (yaml) , 

you could possibly bump the version up?

```
plugin: dump
    source: https://github.com/brave/browser-laptop/releases/download/v<current>dev/brave_<current>_amd64.deb
source-type: deb
```

should be just a change of a line if I am not wrong.

w.r.t automation, 

I don't know who from brave is in touch with Martin/somebody  from snapcraft,
but we could possibly attach the snapcraft.yaml file to the current release branch and mirror the build on launchpad every time a commit is made into the release branch

launchpad will build brave and release it to the desired channel on the snap store automatically then.

**Comment by Ads20000** [comment]
I noticed Martin linked [this bug](https://github.com/canonical-websites/build.snapcraft.io/issues/843) in [the snapcrafters repo for the Brave snap](https://github.com/snapcrafters/brave) which might be the blocker (using build.snapcraft.io would be easier than Launchpad for the Brave devs).

Sorry to bother you devs btw, just that we would love to see Brave released as a snap, up-to-date, and in the `stable` channel, but clearly there's stuff that needs to happen for that to happen! We should probably leave Martin and you guys to it :P

**Comment by posix4e** [comment]
@Ads20000  no bother at all.

**Comment by TheMarketAnarchist** [comment]
@posix4e No hurry or anything, but is there an update on the status of this? I'm on Solus which has native Snap support and doing "refresh" on Brave hasn't updated the package. I see [here](https://github.com/snapcrafters/brave) that the version was bumped 8 days ago, but was this deployed?

I love Brave so much and would love to be running the latest versions!

**Comment by Ads20000** [comment]
@TheMarketAnarchist We can wait and I'm sure @posix4e will resolve it eventually but if you want to do something yourself I'm guessing taking the `snapcraft.yaml` from [here](https://github.com/snapcrafters/brave/issues/1#issuecomment-328092344) and trying to work out a working one would be good. You'd need to learn some stuff about snapcraft and `electron-builder` though :)

**Comment by Ads20000** [comment]
Oh, as for the version bump, I'll file an issue and ask why Martin hasn't released it...I can see that's not autobuilding on the snapcraft build service...

**Comment by posix4e** [comment]
If there's a patch in the meantime you'd like to see..

**Comment by TheMarketAnarchist** [comment]
While an update was released 6 days ago, I was wondering if the Brave Snap Team is considering an auto-build and auto-update solution so that the Snap is kept up-to-date with the other versions. For instance, the Stable channel would be synced to the stable releases, edge to the master branch, etc.

If this is being discussed, could someone update me on the status? I'm just not sure what the plan is with the Snap version. Thanks!

**Comment by hugobuddel** [comment]
The beta version should be 0.19 according to [Release-channels](Release-channels), but installing Brave with `snap install brave --beta` gives 0.18.36.

**Comment by LaosPL** [comment]
So it havn't been fix yet? Snap for Brave is only beta ? I am on 0.19.66

**Comment by LaosPL** [comment]
So it hasn't been fix yet ? Is there only beta channel for snap ?

**Comment by posix4e** [comment]
@LaosPL Sorry I have been distracted on other things. If you wanna help we can push this forward quickly.

**Comment by LaosPL** [comment]
@posix4e How can I help ?

**Comment by posix4e** [comment]
@LaosPL for now email me at posix4e at gmail .com and we can discuss snap.

**Comment by bsclifton** [comment]
Closing as this has been fixed. Our snaps should be up to date
