### ISSUE TITLE
Gitlab not loading correctly within brave

### ISSUE THREAD

**Issue by mohanidragel** [brave/browser-laptop#9873]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Specifically when using GitLab, after submitting a new merge request, there are 3 pages - Discussions | Commits | Changes. When I'm on the discussions page, I can view the comments made however, I can't load the commits page or the changes page on Brave browser. Works ok in Chrome and FF. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 

- Brave Version (revision SHA):
0.17.13
- Steps to reproduce:
    1. Create a merge request on GitLab 
    2. On the merge request page navigate to the commits / changes sub page
    
- Actual result:
Page does not load with the commit history or the changes on selecting either subpage. 

- Expected result:
Pages load as per chrome . 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes. Unfortunately. 

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Works fine for me on Linux and Windows with shields up and Fingerprint protection turned on
![git lab](https://user-images.githubusercontent.com/17010094/27883413-49d35458-61c8-11e7-88a7-46eb9a22aceb.png)

**Comment by mohanidragel** [comment]
Cool. Let me double check tomorrow morning when I'm back online (on my computer). I'll clear down my cache and check again. Will post screenshot or vid if still an issue.

**Comment by mohanidragel** [comment]
See screenshots below. First one from brave and the next from chrome. I cleared down the cache etc. I've also added some console errors from brave on clicking on commit.  

![merge1](https://user-images.githubusercontent.com/23719891/27903426-2b5f9342-6231-11e7-8993-7f93ee51382f.PNG)

Chrome: 
![merge2](https://user-images.githubusercontent.com/23719891/27903435-3400406e-6231-11e7-8eee-2ed27715916c.PNG)

![consolemerge](https://user-images.githubusercontent.com/23719891/27903495-74fe7644-6231-11e7-8f75-60816a508d0c.PNG)

**Comment by mohanidragel** [comment]
Same error on clicking commit or changes.

**Comment by srirambv** [comment]
Could you try setting `Allow all cookies` in the shields and check if it resolves the issues. 

This is the setting on my machine for gitlab
![image](https://user-images.githubusercontent.com/17010094/27904166-ac136cbe-6233-11e7-9bb3-20ced7ea735b.png)

**Comment by mohanidragel** [comment]
So I did that and it didn't resolve the issue. 

However, I then put the shields down and refreshed. Loaded the content correctly. I put the shields back up then and refreshed, and it was loading the content correctly this time so switching on and off the shield seemed to have resolved it. (",)

**Comment by srirambv** [comment]
cc: @bsclifton

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community site.

https://community.brave.com/t/tracking-gitlab/10670

There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
