### ISSUE TITLE
Avast flagging brave.com

### ISSUE THREAD

**Issue by evq** [brave/browser-laptop#9874]
From discord we received a report of brave.com being flagged by avast. I reached out to them via their false positive form shortly after, but still have not received a response.

![url](https://user-images.githubusercontent.com/8796196/27876023-f1cfdd58-61a4-11e7-8e9a-b5498e8f35e5.png)

**Comment by luixxiul** [comment]
I have experienced the issue on my own site several years ago and for me the issue was related with DNS setting. IIRC sites are flagged manually so the company will hopefully reply soon with the reason of fragging.

**Comment by diracdeltas** [comment]
supposedly fixed now https://twitter.com/AugiCZ/status/882692371229667328
