### ISSUE TITLE
Reopen last closed tab does not maintain previous history?

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9875]
If I perform a google search (page A), click a link that takes me to a new page (page B), then click another link and arrive at yet a new page (page C).  If I close that tab, I have no way to easily get back to page B (other than going into the actual history page)

Chrome handles this by having two lists under the history tab:  recently closed and recently visited.

I recognize that Brave does not offer that feature, so I was just thinking that It would be nice if when preforming the "reopen a last closed tab" fuction, that it remembered the previous http push states, so that the back button could be used to get back to in my original example, page B.

Personally, I think it would be more useful to have "recently visited" than "recently closed".  Quite often, I go under the history tab to quickly get to a page I was at earlier, and it's not there.. So I have to open the actual history page which is less convenient.

**Comment by eljuno** [comment]
Related to #2702?

**Comment by patrick99e99** [comment]
oops..  Yes, I searched for this before making the issue but did not seem to find it.

**Comment by luixxiul** [comment]
@patrick99e99 it is known that github search is so poor that you would like to use google, which is by far better.
