### ISSUE TITLE
Windows Performance Issues

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#9878]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
0.17.13 on Windows 7 (VM) has several issues:
- intermittent freezing (originally reported via twitter)
- slowness/sluggish performance 
- YouTube videos freezing

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 (32bit)

- Brave Version (revision SHA):
Brave 0.17.13
rev f7242c7
Muon 4.1.7

- Steps to reproduce:
    1. Clean install of 0.17.13. 
    2. Open Brave. 
    3. Open a site like nytimes.com and open an article in a new tab. 
    4. Open a new tab and open a youtube video.
    5. Try to navigate between the open tabs.
    6. Try to open a new tab. 
    
- Actual result:
From opening Brave to navigating between tabs each click seems to take 5-7 seconds to register. Also, sometimes it's not clear that your click did register so it appears as though Brave is frozen. Additionally, youtube video stutters and freezes frequently. 

- Expected result:
Should be able to move between tabs with ease, no freezing should occur.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Repeating steps with Chrome does not produce a performance problem.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by srirambv** [comment]
Confirmed slowness on Windows 7 VM with 2GB RAM and no other process running on host machine(Windows 10 x64).

**Comment by NejcZdovc** [comment]
If I use only 2gb of RAM for my VM, I notice lags as well.

![image](https://user-images.githubusercontent.com/9574457/28006591-42393902-6550-11e7-9c17-a47ce7b3a358.png)

![image](https://user-images.githubusercontent.com/9574457/28006602-509fae40-6550-11e7-8449-ed2985361840.png)

**Comment by bsclifton** [comment]
Is this specific to Windows? @LaurenWags could it be related to the VM settings?  Let's try at least 4GB of RAM and more than 1 CPU / core.  I don't think this is Windows specific

**Comment by bsclifton** [comment]
Removing milestone until we have more info

**Comment by LaurenWags** [comment]
@bsclifton vm is using 8gb ram and 1cpu/core the slowness on Brave is painful. Chrome (with same 8gb and 1cpu/core) does not have the slowness. Also, yes, if I keep my 8gb ram and change to 2 cpu/core, the slowness in Brave goes away.

**Comment by bsclifton** [comment]
@LaurenWags just to confirm: the issue doesn't happen w/ Windows 10?

**Comment by LaurenWags** [comment]
@bsclifton with Windows 10 VM using 8gb ram and 1cpu/core there is some slowness but Windows 7 is worse.

**Comment by mightypenguin** [comment]
I see a similar problem on Mac OS X 10.11.6 (not in a VM) with at least the last 4 versions of Brave.
I usually have less than 2gb Ram free. I also see intermittent pausing while scrolling through long pages. It's fairly common.

**Comment by LaurenWags** [comment]
@bsclifton received a report of perf issues with Windows 10 via Twitter: https://twitter.com/joesales/status/901170717538045952
