### ISSUE TITLE
Pinned tabs triplicated

### ISSUE THREAD

**Issue by tarciosaraiva** [brave/browser-laptop#988]
OK this is what happened to me today... I don't know how to explain. Just opened Brave... 

![screen shot 2016-03-04 at 8 29 59 am](https://cloud.githubusercontent.com/assets/893428/13510171/7b7340c4-e1e3-11e5-9a5b-6e45deac0afa.png)

**Comment by tarciosaraiva** [comment]
Quitting Brave and opening again got rid of the triplicated tabs.

**Comment by bbondy** [comment]
I believe this is a 1 time upgrade problem for some users. Removing the pinned duplicates should go away from now on.  Please let me know if they continue to double or something though.

**Comment by tarciosaraiva** [comment]
All good. I tried a couple of other times and all is well, didn't happen again so far. Will keep and eye out, if it happens again, I will let you know.
