### ISSUE TITLE
Use Chromium spell checker

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#9880]
## Test plan
See https://github.com/brave/browser-laptop/pull/9951

## Original issue description
deprecate electron spell checker

**Comment by Liunkae** [comment]
Let's recheck the [spellcheck issues](https://github.com/brave/browser-laptop/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20spell%20check%20) after this is implemented.

**Comment by Jacalz** [comment]
Hope that this closes https://github.com/brave/browser-laptop/issues/7967

**Comment by Jacalz** [comment]
I don´t seem to be able to forget spelling in ia32 :confused:
