### ISSUE TITLE
UNDO in url bar has funky behavior

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9881]
1. I click on the url bar
2. I type in 'http://foo/bar'
3. I press backspace multiple times to remove '/bar' from my url.  My url bar now shows 'http://foo'
4. I press cmd-Z for undo, '/bar' reappears giving me 'http://foo/bar' (this is expected behavior)
5. I press cmd-A and backspace to remove my search
6. I press 'f', and autocomplete shows a site I have visited, for example 'famouspunks.com/'
7. I press cmd-Z for undo

result in url bar: 'famouspunks.com/http://foo/bar'

I would expect either:

A) my url bar to be 'http://foo/bar' again

or

B) cmd-A and backspace to have wiped out my url bar's undo history so that nothing happened when pressing cmd-Z after 'famouspunks.com' showed up when typing 'f'.

**Comment by bsclifton** [comment]
Confirmed this is still an issue with our latest release

This particular behavior doesn't happen in Brave Core... but it has a different experience worth noting (which is identical to Chrome/Chromium). Undo in URL bar for Chromium triggers autocomplete for sites that match F (ex: foxnews.com)

**Comment by bsclifton** [comment]
Fixed with [brave-core](https://github.com/brave/brave-browser)
