### ISSUE TITLE
Cannot copy desired markup in web inspector

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9883]
1. I visit a webpage.
2. I open the web inspector
3. I look at the HTML markup of the page
4. I see an HTML tag that I want to copy
5. I click the HTML tag, it highlights
6. I press cmd-C
7. I observe that the Edit menu bar highlights, indicating that it did copy my selection
8. I paste in another window and see the text pasted is whatever was previously in my clipboard buffer

Right clicking also offers no options, which I would expect it to-- Chrome for example opens up a menu with options like "add attribute", "edit attribute", "edit as HTML", "copy", etc.

As a web developer, these functions are incredibly helpful and without them, I am again forced to still use Chrome for some of my work.

**Comment by luixxiul** [comment]
closing in favor of #6724

**Comment by bsclifton** [comment]
Thanks for the report @patrick99e99- as stated above, we're tracking these issues with https://github.com/brave/browser-laptop/issues/6724; I gave that issue a +1 on your behalf 😄 Hoping we can get to these soon
