### ISSUE TITLE
browser crash followed by a restart doesn't open old tabs

### ISSUE THREAD

**Issue by Miyurz** [brave/browser-laptop#9885]
- Describe the issue you encountered:
Brave crashed due to #9385 . Now when I restart the browser, it doesn't even the old tabs. This is frustrating because there were almost important 20-30 tabs and now I have no idea how to get those back.
 
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
f7242c7

- Steps to reproduce:
    1. Try to repro #9385 
    2. Then kill your browser from command line 
     3. Try opening the browser and all the previous opened tabs are gone :(
    
- Actual result:
Browser starts with a  fresh profile, All previously opened tabs are gone.

- Expected result:
It should restore all old tabs if the browser crashed for any reason or of it was force killed. 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Not sure but I could reproduce it this morning.

**Comment by Miyurz** [comment]
@srirambv do you know who can look into this ?

**Comment by Liunkae** [comment]
This problem is being tracked here: #5512. Closing as a duplicate.
