### ISSUE TITLE
Two-finger trackpad scrolling on Surface is laggy

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#9888]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
On Microsoft Surface Pro 4, there is a distractingly long lag before two-finger trackpad scrolling gesture starts scrolling the screen.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10

- Brave Version (revision SHA):
Brave	0.17.13
rev	f7242c7
Muon	4.1.7
libchromiumcontent	59.0.3071.109
V8	5.9.211.38
Node.js	7.9.0
Update Channel	dev
os.platform	win32
os.release	10.0.14393
os.arch	x64

- Steps to reproduce:
    1. Open a website
    2. Drag two fingers up or down the trackpad
   
    
- Actual result:
website scrolls immediately (as it does using touchscreen for example)

- Expected result:
lag of perhaps 500 ms, plus jerky scrolling after that 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
unknown

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
for me, yes

- Any related issues:
Not a problem with Firefox or Chrome on my machine

**Comment by srirambv** [comment]
@stshank  Do you see this issue even after enabling smooth scroll in advance settings?

**Comment by stshank** [comment]
@srirambv Nope, I'm still seeing a lot of pauses and stuttering.

**Comment by tylo** [comment]
I also have this problem on my Surface Book. Enabling or disabling smooth scrolling does not address the problem.

 
Brave: 0.19.95 
rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
Muon: 4.5.16 
libchromiumcontent: 62.0.3202.94 
V8: 6.2.414.42 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.17025 
OS Architecture: x64

**Comment by JaC0C0** [comment]
I am currently having this issue on my Dell XPS 13 9360. Occurred during use after switching from on application back to Brave. Problem is exactly as previously described, two finger scrolling lags behind the physical action approximately 500 - 1000 ms. The problem is not replicated by mouse however, simply 2-finger scrolling.

 
Brave: 0.19.122 
rev: 009e79278cba9e3e0e5498d64739b0cb0a5b4696 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.16299 
OS Architecture: x64

**Comment by massung** [comment]
Just noting I have the same issue on my Lenovo Yoga (Windows 10):


Brave | 0.19.134
rev | 316cfa5
Muon | 4.5.38
libchromiumcontent | 63.0.3239.132
V8 | 6.3.292.49
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.16299
OS Architecture | x64

Side note: I didn't notice the problem on initial install (a previous version), but I enabled smooth scrolling, and started noticed the issue after an update. I disabled smooth scrolling, but the problem persisted regardless of the setting from then on. Probably has nothing to do with smooth scrolling, but did want to note that originally the problem did not exist.

**Comment by bsclifton** [comment]
@stshank @tylo @JaC0C0 @massung this issue may have been solved with our latest release (0.20.30).  In the preferences window (under advanced), you'll see a new slider for adjusting sensitivity.  Give that a shot and see if it helps 😄 (please let us know)

![screen shot 2018-02-13 at 11 34 52 pm](https://user-images.githubusercontent.com/4733304/36190648-9d609b8c-1116-11e8-8880-90da4d3339b1.png)
