### ISSUE TITLE
Unable to fire devTools via shortcut

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9889]
STR:

1. open any website
2. Right click, inspect element
3. Works fine
4. Close devtools
5. Try cmd+option+i on mac
6. doesn't work

Issue happens due to state passed down to `tabState.getActiveTab()` which includes an empty list, so the result who is looking for the active tab returns undefined. 

Err log (following STR will lead you here):
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of undefined
    at click (/Users/cezaraugusto/dev/browser-laptop/app/browser/menu.js:273:44)
```

seems related to https://github.com/brave/browser-laptop/commit/735037e342603ae1354b949d1ce7eca57dc5e820#diff-e39b9756f3113b75562a5aa516c1a31cR269. Labeling to 0.19.x to match the change.

@NejcZdovc mind taking a look at this one?

**Comment by NejcZdovc** [comment]
Thanks for creating issue for it. I notice this as well, but didn't have time to create an issue for it.
