### ISSUE TITLE
Javascript  window.open()

### ISSUE THREAD

**Issue by VirgilRoussos** [brave/browser-laptop#989]
From support: 

When a new window is opened using the JS function/method **window.open()**, parameters to the function are not respected. 

Also it is not possible to change the size of the window afterwards using for example the method **window.resizeTo()**.

**Comment by luixxiul** [comment]
@bbondy Would you please have a look at this? Thanks.

**Comment by bbondy** [comment]
This would be for @bridiver but it's not super high priority compared to some other things.

**Comment by bridiver** [comment]
which parameters are not respected? We have tests that cover window size and position for window.open. We don't currently support hiding of scrollbars, titlebar, etc... Fullscreen is also not supported, but I don't know if we want to support it. There are malicious sites that use some of these features to trick users into thinking that there is a problem with their computer. I saw an example of a particularly nasty one recently that actually made it impossible to close the window in all browsers that I tested. 

If we decide to support window.resizeTo, it's availability should be limited. See https://bugzilla.mozilla.org/show_bug.cgi?id=565541#c24
cc @diracdeltas

**Comment by diracdeltas** [comment]
Fullscreen is supported (via webkitRequestFullScreen()) but requires user permission, as expected. Agree that resizeTo should generally not be supported.

**Comment by bridiver** [comment]
@diracdeltas I don't see that we are currently passing through fullscreen for window.open, but I could add it. Seems ok if we have a permission dialog for it.

**Comment by diracdeltas** [comment]
@bridiver i don't see a need to support fullscreen on window.open since the page can just do `webkitRequestFullScreen` if it wants fullscreen

**Comment by jonathansampson** [comment]
Closing this as it has been over a year with no further information.
