### ISSUE TITLE
urlbar suggestion error happening since redux causing the need for a browser restart

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9891]
This error sometimes happens:
<img width="1603" alt="screen shot 2017-07-06 at 1 32 24 pm" src="https://user-images.githubusercontent.com/831718/27935014-8a978fe6-6276-11e7-87c3-c06d383d24fe.png">

It corresponds to the forEach here. 
<img width="486" alt="screen shot 2017-07-06 at 6 11 55 pm" src="https://user-images.githubusercontent.com/831718/27935044-b36da270-6276-11e7-8b35-2ea1c10bcf0c.png">

I've had it happen 2-3 times and my wife also hit it.  We should hotfix for it.

**Comment by bsclifton** [comment]
Already done 😄 see https://github.com/brave/browser-laptop/commit/97adc1e5bdeadd6f4cd657063303cf3fce5d6d3e

**Comment by bbondy** [comment]
👍
