### ISSUE TITLE
URL bar suggestions stop user from going where they actually really want to go

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9892]
1.  I perform a google search, and the results reveal a page with the url: "https://www.reddit.com/r/Augur/comments/4fd27b/augur_markets_as_an_oracle_for_accurate_external/"
2.  I click the link and visit the page
3.  I realize this page is not really what I want so I close the window and open a new tab
4.  I type into the url bar 'reddit.com/r/augur' and press return
5.  by pressing return, I was actually confirming to take me to the previous history link instead of where I really wanted to go, so I am taken back to "https://www.reddit.com/r/Augur/comments/4fd27b/augur_markets_as_an_oracle_for_accurate_external/"
6.  I close the window and open a new tab
7.  I type "reddit.com/r/augur" and when the search history options pre-selecting "https://www.reddit.com/r/Augur/comments/4fd27b/augur_markets_as_an_oracle_for_accurate_external/" appear, I press esc to close the suggestion box..  
8.  The url I typed has now been erased.

...

The only way I can actually get where I want to go is if I type "reddit.com/r/augur " (with a trailing space)..  Then that stops the autocomplete box from showing up and I can actually get where I want to go.

**Comment by Miyayes** [comment]
+1 from community: https://www.reddit.com/r/BATProject/comments/8pmkk3/this_needs_to_stop_after_dealing_with_brave/

This user writes: "This needs to stop. After dealing with Brave Browser for 6+ months, this is one of the most annoying features out there, surpassing all the most tedious bugs I've dealt with in my time."

**Comment by dginovker** [comment]
Still happens.. Very, very, very annoying.

**Comment by bsclifton** [comment]
For folks experiencing this, I'd encourage you to try our developer channel release:
https://brave.com/download-dev

With the current code-base (Muon), we won't be able to address this. However, I believe this is fixed in our developer channel (which will be making its way to beta and then release)
