### ISSUE TITLE
Split pinned sites and bookmarks

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#990]
Use common siteUtil functions but just store them differently in storage. 
Even maintain the same actions.

**Comment by bsclifton** [comment]
Related:
https://github.com/brave/browser-laptop/issues/1306
https://github.com/brave/browser-laptop/issues/1856
https://github.com/brave/browser-laptop/issues/1864

**Comment by NejcZdovc** [comment]
closing in favor of #9978
