### ISSUE TITLE
Use fullscreen permission buttons are out of order

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#9909]
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
The "use fullscreen" permission buttons seem out of order compared to other permissions. Use fullscreen has the `Deny` button first, but other permissions (e.g. autoplay video) have `Yes` first. For consistency, I think all "affirmative" buttons should be first (leftmost).

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS 10.12.x

- Brave Version (revision SHA):
0.17.13 ()

- Steps to reproduce:
    1. Go to any site with a fullscreen video (e.g. YouTube). Make sure use fullscreen is turned off by default for the site in settings.
    2. Click the fullscreen button.
    
- Actual result:
The `Deny` button is first.

- Expected result:
The `Allow` button should be first.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes, 0.17.13.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![](https://user-images.githubusercontent.com/19424103/27976851-e2ddc316-632d-11e7-9a47-1c9bdccd3f82.png)

- Any related issues:
None.

**Comment by NejcZdovc** [comment]
is this dupe of #8956? We also want to unify confirm/deny values, issue #9750

**Comment by Liunkae** [comment]
@NejcZdovc Yes, thanks!
