### ISSUE TITLE
URL bar does not autosuggest when subdomains are missing

### ISSUE THREAD

**Issue by patrick99e99** [brave/browser-laptop#9910]
1. I visit mail.google.com
2. I close the browser tab and open a new tab
3. I type "mail." and notice the url bar has auto suggested appending ".google.com" to what I type.
4. I can press return and be taken back to gmail.

...

5. I visit mail.yahoo.com
6. I see that yahoo redirected to "https://mg.mail.yahoo.com/d/folders/1"
7. I close the tab and open a new one
8. I type in "mail.y" and notice that the url bar does NOT auto suggest mail.yahoo.com

It would be nice if Brave makes suggestions based off of what you type as well as what you type ends up getting resolved to via redirecting.

**Comment by bsclifton** [comment]
@diracdeltas confirmed it's fixed 👍
