### ISSUE TITLE
Command+L when in url bar with URL bar suggestion should select full URL

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9914]
## Test plan
See https://github.com/brave/browser-laptop/pull/9928

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you are typing a URL and auto suggest is filling in another URL for you, hitting command+L doesn't select the URL.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.17.14

- Steps to reproduce:
    1. Make you have a couple of sub-urls in your history for github.com
    2. Type git, notice it autocompletes to something like github.com...
    3. press command + L (or ctrl+l on win/linux)
    
- Actual result:
Removes the selection

- Expected result:
Selects the URL

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

**Comment by bbondy** [comment]
I'd like to get this in 0.7.14 but it would need us to merge
https://github.com/brave/browser-laptop/commit/7588a3c4854938b034812b900ae034e666067056
And I'm not sure how safe that is.  CC @NejcZdovc

**Comment by bbondy** [comment]
I'll put this in 0.19.x until we figure that out.

**Comment by NejcZdovc** [comment]
My PR is not directly mergeable, we would need to update some properties in `app/renderer/components/navigation/urlBar.js`, but other then that I don't see any conflicts

**Comment by bbondy** [comment]
ok let's just wait for this issue then until 0.19.x
