### ISSUE TITLE
Comments section can't load on national news site due to https promotion

### ISSUE THREAD

**Issue by tenleftfingers** [brave/browser-laptop#9915]
- Did you search for similar issues? Yes
- Describe the issue you encountered: The comments section can't load on thejournal.ie
![image](https://user-images.githubusercontent.com/1757768/27986227-554e0c50-63f4-11e7-99e8-fa7cdf000147.png)
- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04 64-bit, running Brave snap from the beta channel.
- Brave Version (revision SHA):f7242c7

- Steps to reproduce:
    1. Visit thejournal.ie article, eg https://www.thejournal.ie/department-of-arts-heritage-gaeltacht-3486348-Jul2017/#comments
    2. Notice that the comments section never loads
    3. This doesn't happen with http
    
- Actual result:
the comments section never loads
- Expected result:
comments section would load under http
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes, it will work for anyone.
- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
See above

**Comment by Liunkae** [comment]
The site appears to have mixed content (notice the HTTPS but the lock icon is "broken").

You can try enabling insecure content by clicking the lock icon.
![](https://user-images.githubusercontent.com/19424103/27991234-cb0ec718-6435-11e7-9832-29eecf5d03f4.png)

Or, you can use HTTP (and disable HTTPSEverywhere for that site, if necessary).

Neither workaround is completely secure, and this is a site bug that really should be fixed by the website.

**Comment by tenleftfingers** [comment]
I'll get in touch with them. Thanks for the info. 

On Sunday, 9 July 2017 05:36:46 IST, Liunkae <notifications@github.com> 
wrote:
> The site appears to have mixed content (notice the HTTPS but 
> the lock icon is "broken").
> 
> You can try enabling insecure content by clicking the lock icon.
> ![](https://user-images.githubusercontent.com/19424103/27991234-cb0ec718-6435-11e7-9832-29eecf5d03f4.png)
> 
> Or, you can use HTTP (and disable HTTPSEverywhere for that 
> site, if necessary).
> 
> Neither workaround is completely secure, and this is a site bug 
> that really should be fixed by the website.
> 



-- 
Sent using Dekko from my Ubuntu device
