### ISSUE TITLE
missing rimraf dep makes build unable to launch

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#9918]
Rimraf was used as a dep to exclude an extension. Extension exclusion is not possible anymore but still host some of its code. At some point we removed rimraf from package.json and that is throwing an error in extensions regarding missing dep.

This happens in 0.17.x up to master. Seems that error in dist builds is silent.

STR:

1. Have a clean install
2. Start Brave (npm run watch/npm start)
3. Can't launch Brave

**Comment by bbondy** [comment]
Which platform are you on? Win, linux, mac?
What is your node version?

This works for me with a clean npm install and then watch and start.
I'm thinking this should be removed from the milestone and maybe it's a local only issue?

```
Brians-MacBook-Pro:browser-laptop bbondy$ npm --version
5.1.0
Brians-MacBook-Pro:browser-laptop bbondy$ node --version
v8.1.1
```

Plus 0.17.14 preview builds were actually built.

**Comment by NejcZdovc** [comment]
for me clean install on 0.17 is working correctly. I have problems with 0.18 branch, but problem different.

**Comment by cezaraugusto** [comment]
ok moving out of 0.17. I did another clean install to fix a diff bug for 0.17.14 and couldn't repro again. Seems like other dep has rimraf as a dep so bug is silent but we are still requiring a module that is not declared in package.json. I think it's still valid to fix soon so I'm pushing back to 0.18.x.

Please let me know if you disagree and prefer to land that in master instead and I'll move again. Thanks.

**Comment by bbondy** [comment]
Do we have to land anywhere?

**Comment by cezaraugusto** [comment]
fix is just a comment on the missing dep. I've set for 0.18.x just for future-friendliness as I could repro at some point but not anymore, so it is just to avoid that someone can repro again in the future.
