### ISSUE TITLE
Add test that checks wasted render counts

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9926]
**Describe the issue you encountered:**
Create a test that will check wasted render number.

Step:
1) open 4 tabs
2) preview them
3) switch between them
4) hover over them
5) bookmark all of them
6) edit all of them
7) delete all bookmarks
8) open so many tabs that you trigger new tab page
9) preview first tab page)
10) close all tabs, except the first one

**Comment by bsclifton** [comment]
Closing as `wontfix`
