### ISSUE TITLE
Local file download leaves blank tab continously loading

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9927]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Local file download leaves blank tab continously loading

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

1 | 2
-- | --
Brave | 0.17.14
rev | a8631c6
Muon | 4.1.8

- Steps to reproduce:
    1. Enable Payments
    2. Go to advance -> backup wallet -> save file
    3. Blank tab opens and doesn't close, spinner keeps on going
    4. Try closing the `about:blank` tab opened, doesn't close and can't switch to the tab
    
- Actual result:
Local file download leaves blank tab continously loading

- Expected result:
Should close the tab when download is completed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes on 0.17.13

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#9620 
cc: @bridiver

**Comment by NejcZdovc** [comment]
is this dupe of #9677?

**Comment by srirambv** [comment]
Yup dupe of #9677
