### ISSUE TITLE
Preview does not reset if you click a tab until you mouse out of tab

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9929]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you have 2 tabs, and you use your mouse to change to the second tab, the preview sticks around until you move your mouse out.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Probably all, but I tested on macOS

- Brave Version (revision SHA):
0.7.14.

- Steps to reproduce:
    1. Click on the twitter icon on the new tab page
    2. Open a second tab, wait for the new tab to open.  Which becomes active.
    3. Hover over the twitter page, and then click it
    
- Actual result:
The preview faded look remains

- Expected result:
The preview faded look should go away after active is set.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No, but on the latest preview release.

- Can this issue be consistently reproduced?
Yes

**Comment by bsclifton** [comment]
+1!

**Comment by srirambv** [comment]
Confirmed on Windows as well.
