### ISSUE TITLE
Console warning when two tabs are open with the same location

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#993]
this appears when i have two tabs open that are set to badssl.com:

```
Warning: flattenChildren(...): Encountered two children with the same key, `.$badssl=1com`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by cezaraugusto** [comment]
Hi Yan, this is not an issue currently. Using v0.11.0. Closing.

**Comment by bbondy** [comment]
Did you try with a debug build? This is probably only related to React warnings that happen when using a development environment.  I think it should be reopened if you tried with a release build.

**Comment by cezaraugusto** [comment]
@bbondy yep, I looked at it while working on a PR. Both DevTools and Terminal doesn't return this error.

**Comment by luixxiul** [comment]
This seems to have been fixed.
