### ISSUE TITLE
Provide option to disable pinned tabs in new window

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9932]
Based on too many requests from community 
https://community.brave.com/t/pinned-tabs-should-stay-in-the-window-they-were-pinned-in/1143/9

Based on https://github.com/brave/browser-laptop/issues/5800#issuecomment-286968492 there should be an option added in preference to enable/disable pinned tabs in new window.

**Comment by eoyount** [comment]
Yes, please. This is the only thing about the Brave browser I don't like.
For my use case, I basically keep email and rss feeds in pinned tabs and I don't want or need them to follow me and take up more resources when I open a new window. The new window is almost always for some separate task. For example, I might want to open a video in a new tab and put it on my second screen while I continue to use the main browser for other things.

**Comment by luixxiul** [comment]
duplicate of #5800
