### ISSUE TITLE
Session tab tooltip has extra text 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9933]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Session tab tooltip has extra text 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 (should be on all)

- Brave Version (revision SHA):

1 | 2
-- | --
Brave | 0.17.14
rev | a8631c6
Muon | 4.1.8

- Steps to reproduce:
    1. Open a new session tab
    2. Mouse over the session icon
    3. Tool tip has extra text and doesn't show the session ID instead shows `{{partitionNumber}}`
    
- Actual result:
Session tab tooltip has extra text 

- Expected result:
Should show as `This is a session X tab` 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Need to verify

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28018784-7b6fa99c-6576-11e7-8b82-c7ae1ae65610.png)

- Any related issues:
#9011 
cc: @jonathansampson @cezaraugusto

**Comment by jonathansampson** [comment]
Same issue as https://github.com/brave/browser-laptop/issues/9011#issuecomment-303589749
