### ISSUE TITLE
Extension: 1Password 4.6.7.90

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#9946]
### A Note on Development Testing

1Password expects Brave to be signed. This is the case with general releases, but is not presently the case with _electron-prebuilt_ releases of Muon. For this reason, 1Password may refuse to communicate when the user is testing from a local clone of the _browser-laptop_ project.

### Testing 4.6.7.90 on a General Release

In order to test a newer version of 1Password, the user can enable 4.6.3 (current offered version in Brave), which results in the creation of `%appdata%/brave/Extensions/aomjjhallfgjeglblehebfpbcfeobpgk/4.6.3.90/`. The contents of this directory can be replaced with an unpacked 4.6.7.90, downloaded from the Chrome webstore.

On macOS, the user may need to copy the `Chrome/NativeMessagingHosts` directory over to `Brave/NativeMessagingHosts` to give Brave access to the 1Password manifest. Ideally, Brave would read from any pre-existing `Chrome/NativeMessagingHosts` directory.

### General Issues

- [ ] Context menu lacks interactive icons

_Explanation: This is due to the background script not reaching the contextMenu logic. The lack of support for chrome.browserAction.enable causes a throw to occur._

- [x] `chrome.browserAction.enable is not a function` from _setToolbarEnabled_

_Explanation: This issue has been addressed in part. It is important to achieve a full implementation (which allows for disabling and enabling the browserAction button. This button prevents the user from spinning up a new 1Password process during updates, etc._

- [x] Clicking the browser-action icon raises the following:
```
Uncaught (in promise) Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:79:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:149:26)
    at C.send.send (chrome-extension://bbfiipknkgjieboiachfddfkeagnkllg/global.min.js:166:24)
    at E.<anonymous> (chrome-extension://bbfiipknkgjieboiachfddfkeagnkllg/global.min.js:216:322)
    at E.connectionWillEstablishConnection.vb (chrome-extension://bbfiipknkgjieboiachfddfkeagnkllg/global.min.js:228:382)
    at C.<anonymous> (chrome-extension://bbfiipknkgjieboiachfddfkeagnkllg/global.min.js:192:323)
    at <anonymous>
```

_Explanation: When testing locally, 1Password doesn't permit Brave to communicate with the Native application. This can be avoided by following the *General Release* testing steps at the top of this issue._

- [ ] Upon launch, 1Password attempts to connect to the Native Message Host _2bua8c4s2c.com.agilebits.1password_, but fails (after adding the local extension ID to the receiving native-messaging manifest on Windows):

![image](https://user-images.githubusercontent.com/815158/28079258-2c06a948-662d-11e7-93ae-b6c68fdc6b89.png)

- [ ] Brave on macOS does not check `Chrome/NativeMessagingHosts` for manifests.

### Related Issues

- #8717 Latest 1password extension (4.6.5.90) disappeared from context menu

**Comment by rudyrichter** [comment]
let me know if you need any assistance with the Native Host has exited, are you testing with 6.8.BETA-8?

**Comment by jonathansampson** [comment]
@rudyrichter Thank you for the generous offer. We're testing 4.6.7.90 (current latest in Chrome webstore). We are running into an issue with native messaging though, and the minified source is making things tougher to troubleshoot. Would it be possible to get a build of the extension that isn't minified?

**Comment by rudyrichter** [comment]
"after adding the local extension ID to the receiving native-messaging manifest"

what exactly does this mean? I suspect that's the problem, we only allow a fixed set of origins in both the Mac and Windows versions.

**Comment by jonathansampson** [comment]
@rudyrichter When we load an unpacked extension (which we need to do for testing), the extension ID is generated from the filesystem path. As a result, it won't be the expected ID. I took the generated ID and added it as an _allowed_origin_ in the ChromeManifest.json file (located via the Registry).

**Comment by rudyrichter** [comment]
@jonathansampson I'm pretty sure that's not going to work, 1Password for Mac and Windows have a baked in set of origins they accept NM connections from. Anything other than that is rejected outright.

**Comment by jonathansampson** [comment]
@rudyrichter Understood. This is the manifest that comes with 1Password:

```
{
	"name": "2bua8c4s2c.com.agilebits.1password",
	"description": "1Password",
	"path": "\\1Password.NativeMessagingHost.exe",
	"type": "stdio",
	"allowed_origins": [
		"chrome-extension://jcjaoeifeheahnjbolddgagkiahngegm/",
		"chrome-extension://aomjjhallfgjeglblehebfpbcfeobpgk/",
		"chrome-extension://phicbbndgmmpogmijjkbmdhpioaieaha/",
		"chrome-extension://fpnbobholfpcolmkinlokiaaanjilcop/",
		"chrome-extension://ffgeebhnlfcekjbfekfppddlklaopmok/"
	]
}
```

For testing purposes, I added another origin to reflect the extensions ID in Brave.

Is there something additional that needs to be done?

**Comment by rudyrichter** [comment]
that manifest file is only used by the browser to decide if the extension itself should use this particular manifest in figuring out if there is a NM manifest.

you're probably seeing the 1Password NM process launch and do nothing, this is how it reacts when a origin other than the ones it has baked into it tries to connect.

**Comment by jonathansampson** [comment]
@rudyrichter I appreciate the prompt response. I was able to load the same source files as an _unpacked extension_ in Chrome, and run without any issue. Chrome had the same ID as Brave, since both were loading the unpacked extension from the same directory. This suggested there may be something within Brave that needs to be adjusted.

I tested Chrome a couple of days ago in this manner, and will do it again here momentarily to be certain of these results. I'll update this issue shortly with my findings.

**Comment by jonathansampson** [comment]
Just ran through the following scenario and found success in Chrome, failure in Brave:

1. ced aomjjhallfgjeglblehebfpbcfeobpgk
2. configure in app\extensions.js
3. npm run watch && npm run start
4. Navigate to chrome-extension://`<extension-id>`/_generated_background_page.html (extension-id found in about:extensions)
5. Rename _metadata to x_metadata in order to load as "unpacked extension" in Chrome
6. Both Brave and Chrome show "Access to the specified native messaging host is forbidden". Both also have identical `<extension-id>` values.
7. Modified ChromeManifest.json to add chrome-extension://bbfiipknkgjieboiachfddfkeagnkllg/ as an allowed origin.
8. On next attempt to connect, Chrome is "Showing AS" while Brave is "Native Host has Exited" (see http://imgur.com/c9br3BF)

**Comment by jonathansampson** [comment]
Closed in part by https://github.com/brave/muon/pull/259
