### ISSUE TITLE
Upgrade to Chromium 60

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9947]

**Comment by bridiver** [comment]
patches were removed that covered the following electron issues. Both appear to be working correctly, but should get QA attention
mac-only
https://github.com/electron/electron/issues/995 
https://github.com/electron/electron/issues/212

**Comment by bridiver** [comment]
also
https://github.com/electron/electron/issues/170
the keyboard shortcuts won't match of course, but any shortcuts with `shift` seem to have been affected. I'm unable to repro any of these issues

**Comment by bsclifton** [comment]
Closed with https://github.com/brave/browser-laptop/commit/92016c5eb0f5328ca675aa000abf40306da8c735

**Comment by bsclifton** [comment]
Updated to 60.0.3112.78 with https://github.com/brave/browser-laptop/commit/c7aafe23db2fdc95ad4b3139699e2e97d3e41a84
