### ISSUE TITLE
Add a search box on the about:bookmarks page

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#995]
It should filter as you type.
It should search across all folders.

**Comment by marti1125** [comment]
Hi @bbondy how to I can help with this?

**Comment by bbondy** [comment]
Hi @marti1125 if you'd like to work on this a god starting point would be in `js/about/bookmarks.js` which is the about:bookmarks page itself.  It would have an input and as you typed it would only include a subset of the bookmarks.
