### ISSUE TITLE
Google Search "Suspicious"

### ISSUE THREAD

**Issue by GarrettS** [brave/browser-laptop#9950]
Only get this issue using Brave. 

https://ipv6.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dd …

![image](https://user-images.githubusercontent.com/56098/28048937-e92621dc-65a8-11e7-86ac-8b029427080e.png)

**Comment by bsclifton** [comment]
@GarrettS do you have more specific steps I can try?  https://ipv6.google.com is not resolving for me... do you have a host file in place?

**Comment by luixxiul** [comment]
For now I'm going to close this issue in favor of this topic on our community 😄

https://community.brave.com/t/discussion-https-github-com-brave-browser-laptop-issues-9950/10038

Let's keep discussion on this issue if this is still an issue 👍 Thanks!
