### ISSUE TITLE
Double click/DND of SVG doesn't open the file in browser

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9953]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Double click/DND of SVG doesn't open the file in browser

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.17.15
-- | --
rev | 39009b8
Muon | 4.1.8

- Steps to reproduce:
    1. Visit https://w3c.github.io/svgwg/specs/svg-authoring/examples/clock-animate-1.svg and save the page
    2. Change file to open with Brave
    3. Double click the file, nothing happens
    4. DND the file on the browser, nothing happens
    5. File ->Open -> locate the file and click open, opens in a tab
    
- Actual result:
Double click/DND of SVG doesn't open the file in browser

- Expected result:
Should open the files when double clicked/dnd on browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
https://community.brave.com/t/cant-open-svg-files-but-i-can-in-three-other-browsers/4669

**Comment by Liunkae** [comment]
Works for me with Brave 0.17.15 on macOS 10.12.x. Could it be Windows-only?

**Comment by srirambv** [comment]
Thanks for the confirmation @Liunkae. Added the Windows tag. Issue reported on community was also on Windows. Does both DND and double click work with mac?

**Comment by Liunkae** [comment]
Yes, both work. However, I just noticed that DND does not work if you drag onto the dashboard page.

**Comment by bsclifton** [comment]
@Liunkae good find! @srirambv did you try dragging into an `about:blank` page? (versus the dashboard)

**Comment by srirambv** [comment]
@bsclifton  it works on `about:blank` page.
