### ISSUE TITLE
Tab color can change on page reload instead of retaining correct initial color

### ISSUE THREAD

**Issue by bradleyrichter** [brave/browser-laptop#9959]
The tab color is determined at the point of page loading based on the center of the page, at the top pixel regardless of scroll point. 

examples:

git page forced to yellow:
![image](https://user-images.githubusercontent.com/13509546/28081922-c305d9e8-6625-11e7-927f-85f9ea1914b0.png)

same page forced back to black:
![image](https://user-images.githubusercontent.com/13509546/28081942-db9ff718-6625-11e7-8d47-d9eeee4de3a8.png)

The color should be sticky to black based on top row of pixels RGB value as shown:
![image](https://user-images.githubusercontent.com/13509546/28082011-181285b2-6626-11e7-9e7d-1a2c1519733c.png)

cc: @darkdh

**Comment by darkdh** [comment]
add a significant screenshot
<img width="398" alt="screen shot 2017-07-11 at 11 20 12 am" src="https://user-images.githubusercontent.com/11330831/28083677-ff394832-662a-11e7-964b-4b12f0e93125.png">

**Comment by luixxiul** [comment]
duping to https://github.com/brave/browser-laptop/issues/932
