### ISSUE TITLE
Enhancement : Visual indicator of extension download and installation status

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#9960]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When enabling extensions on a slow network connection (< 400Kbps for example) other than the toggle, there is no indicator to the user that anything has happened.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
> 0.20.x

**Comment by bsclifton** [comment]
Related https://github.com/brave/browser-laptop/issues/7822
