### ISSUE TITLE
Web view crash when tearing/attaching the tabs back

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9972]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Web view crash when tearing/attaching the tabs back

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Originally found on

Brave | 0.17.15
-- | --
rev | 39009b8
Muon | 4.1.8

Confirmed happening on while testing for (#9865)

Brave | 0.17.9
-- | --
rev | 2606974
Muon | 4.1.4

- Steps to reproduce:
    1. Clean install the 0.17.x build
    2. Visit a site in multiple tabs
    3. Tear off one of them, new window has webview crash (0.17.15)
    4. Tear off one of the tab into window, reattach it to the parent window, webview crashes (0.17.9)
    
- Actual result:
Web view crash when tearing/attaching the tabs back

- Expected result:
Should not crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Possibly yes

- Can this issue be consistently reproduced?
No happens at random times. Following the same steps as mentioned in other builds doesn't cause the crash

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
0.17.9
![image](https://user-images.githubusercontent.com/17010094/28104008-ceeb70b4-66d0-11e7-8535-d3a5e2b0a7ba.png)
0.17.15
![image](https://user-images.githubusercontent.com/17010094/28104013-d722a6ee-66d0-11e7-8057-782125a7027b.png)

- Any related issues:
cc: @bridiver

**Comment by srirambv** [comment]
Still happening on a clean profile on 0.18;24. Found while testing tab page
![pin](https://user-images.githubusercontent.com/17010094/29920194-42d31c80-8e44-11e7-992e-80ec71d7b9cd.gif)

**Comment by srirambv** [comment]
cc: @bbondy @bsclifton

**Comment by bsclifton** [comment]
@srirambv is this still an issue? I know @bbondy had a lot of recent fixes with tear off tabs (which should have landed in 0.18.25)

**Comment by srirambv** [comment]
Verified from 0.18.29-0.18.32 with steps mention in https://github.com/brave/browser-laptop/issues/9972#issuecomment-326262995,  no crash when tearing off tabs.
