### ISSUE TITLE
Typekit and Google fonts

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#998]
https://twitter.com/krystynheide/status/705752122046939136

@bradleyrichter do you know any sites that can demonstrate the difference in missing support that he's talking about?

**Comment by bradleyrichter** [comment]
@bbondy certainly!

https://www.typetester.org/

Initially I had to unblock 3rd party cookies for typekit fonts to appear. Give it a try...we may need to add whitelisting for Adobe TypeKit Fonts.

**Comment by diracdeltas** [comment]
For some reason, a bunch of font sites need 3rd party referer (not cookie, but it's grouped in the same setting) in order to work. I'll whitelist it.

**Comment by diracdeltas** [comment]
typekit was already whitelisted but it needs the real referer in some cases, not just a spoofed referer.

**Comment by tomByrer** [comment]
Is this because of [Webfont Loader](https://github.com/typekit/webfontloader), or just referrals in general?
Can this affect other font-ish CDNs, like [jsDelivr](http://www.jsdelivr.com/)?
