### ISSUE TITLE
Sites visited before payment enabling is shown as 0 views

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9980]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sites visited before payment enabling is shown as 0 views

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Found on 0.17.16

- Steps to reproduce:
    1. Clean install 0.17.16
    2. Visit Netflix and view  a video
    3. Enable payments
    4. Visit other sites and visit Netflix 
    5. Netflix shows as views 0 and % 0
    
- Actual result:
Sites visited before payment enabling is shown as 0 views

- Expected result:
Calculation should be done properly 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Could be checked from 0.16.9 but was not able to reproduce it

- Can this issue be consistently reproduced?
No

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/28134809-0006b90e-673c-11e7-9b97-13ea33ab8d62.png)

- Any related issues:
cc: @cezaraugusto

**Comment by srirambv** [comment]
Seeing this issue on visiting sites after payment is enabled. This is seen on 0.17.17 RC
![image](https://user-images.githubusercontent.com/17010094/28323132-dcb4e46a-6bcf-11e7-9aa1-1e81779f0c2e.png)

**Comment by NejcZdovc** [comment]
this was broken with #9952
