### ISSUE TITLE
Is --proxy-server in 0.17.13 and 0.20.0 as well no longer working?

### ISSUE THREAD

**Issue by module0x90** [brave/browser-laptop#9993]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Version (0.12.15-1) gave me the option with

brave --proxy-server="socks://localhost:5000"
to run brave through a local SOCKS proxy via SSH.

I just updated to (0.17.13-1) and it seems this option is gone. I always my real public IP, that that one from the SOCKS tunnel.
- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch Linux

- Brave Version (revision SHA):
f7242c7

- Steps to reproduce:
    1. Use SSH to establish SOCKS tunnel on port 5000
       ssh -f -N -C -D 5000 $USER@$REMOTEHOST
    2. brave --proxy-server="socks://localhost:5000"
    3.  Visit https://www.whatismyip.com/ to check public IP
    
- Actual result:
Provided SOCKS proxy is ignored.

- Expected result:
Provided SOCKS proxy is used.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Looks like it.
Using the same SOCKS proxy on FF works just fine.

- Can this issue be consistently reproduced?
Yes.

**Comment by module0x90** [comment]
I have compiled on my Arch Linux against 0.20.0, Git SHA  69dfb59, same problem persists.
--proxy-server is ignored.

The previous 0.17.13-1 is the binary version what Arch Linux offered.

**Comment by bsclifton** [comment]
We should get support for all the command line options that we don't already support when switching over to [brave-core](https://github.com/brave/brave-browser) 😄
