### ISSUE TITLE
Closing an opening the browser does not restore tab titles

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#9998]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Closing and opening the browser does not restore background tab titles.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Reproduces on 0.17.16, 0.17.13, 0.16.9
Bug not present in 0.15.314, 0.16.4

- Steps to reproduce:
    1. Open several tabs
    2. Close the browser
    3. Open the browser
    
- Actual result:
No tab titles are loaded

- Expected result:
Tab titles should be loaded

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
<img width="1280" alt="screen shot 2017-07-14 at 6 28 21 pm" src="https://user-images.githubusercontent.com/831718/28233259-96c6d24c-68c3-11e7-9012-e02846e69b27.png">

**Comment by alexwykoff** [comment]
Found 0.16.5 was the first instance of this issue.

**Comment by cezaraugusto** [comment]
removing from sprint/1 as this wasn't possible with #10691

**Comment by cezaraugusto** [comment]
cc @zentagonist
